### ISSUE TITLE
Delete file/directory should move it to Trash instead of permanent deletion

### ISSUE THREAD

**Issue by EstebanBorai** [zed-industries/zed#10009]
### Check for existing issues

- [X] Completed

### Describe the feature

When deleting a file currently, such file is permanently deleted without prompting the user.
It should be nice to prompt before permanently deleting the file or move to system's _trash_.

**Comment by Moshyfawn** [comment]
This has already been suggested, so I'm going to close this topic in favour of the other one. Be sure to +👍 the other feature request.

Duplicate of
- #5094
