### ISSUE TITLE
Image Viewer: White space issue with image previews

### ISSUE THREAD

**Issue by weartist** [zed-industries/zed#10002]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the image is too small, the spacing will be left blank, I'm not sure if this is a bug or the expected behavior, and then, in another case, if the image is too large, the part that exceeds the current window size of zed will not be able to display completely

<img width="1205" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/2f93663e-1767-49e5-a834-99df76cd9904">

<img width="1205" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/accca80c-2917-4d02-aa47-07ecee26f4ed">

<img width="1977" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/929b7444-dd31-496e-a281-d4bf53056b12">

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
Related #9584

**Comment by notpeter** [comment]
Going through some old issues, closing in favor of:
- https://github.com/zed-industries/zed/issues/9582

Also relevant:
- https://github.com/zed-industries/zed/issues/9584
