### ISSUE TITLE
Better preview to the side....

### ISSUE THREAD

**Issue by gdamore** [zed-industries/zed#10021]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now when I open a markdown preview, it always creates a side window.  When I'm working on a bunch of markdown files (e.g. an mdbook directory), I'd like previews to either replace the preview I already have open, or at least open in that side pane rather than creating a new pane.

The new panes are half width, and after just two of these it's illegible.  I work around it by moving tabs, but it's a manual process and it would be nicer if I could just have it open that way by default.

**Comment by bennetbo** [comment]
Hey @gdamore,
some improvements landed in #10205 which should address most of your points.

The markdown preview will now "follow" the active editor, meaning that you can switch between different markdown files and the preview will update accordingly.
Also, existing panes as well as existing markdown preview tabs are now reused when running `markdown: open preview`/`markdown: open preview to the side`.

**Comment by bennetbo** [comment]
Released as part of [preview 0.131.x](https://zed.dev/releases/preview/0.131.0), feel free to reopen or create a new issue if there is still something missing.
