### ISSUE TITLE
Highlight selected chat message

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#10024]
### Check for existing issues

- [X] Completed

### Describe the feature

When clicking on the referenced message in the reply, it would be helpful to have an indication of which message has been selected. Currently, the lack of highlighting, combined with the jitter of the chat trying to scroll the selected message to the top of the chat panel _(as described in #10026)_, further exacerbates the loss of contextual focus.

https://github.com/zed-industries/zed/assets/16290753/8f27a4f9-2110-419b-9fc7-fd1d396b6d61

**Comment by bennetbo** [comment]
Hey @Moshyfawn,
the background of the message you reply to should be highlighted for a couple of seconds already.

https://github.com/zed-industries/zed/assets/53836821/797b4a39-ba43-44eb-95f9-1542a345016d

I did find an edge case in which the messages actually not get highlighted, but this does only occur when you just created the channel and are the only one that sent messages (which does not apply to the chat in your video).

The code uses `info_background` to render the background, wondering if this might be related to your theme?

**Comment by JosephTLyons** [comment]
Yeah, seems to be theme related - works for me in Dracula.

**Comment by Moshyfawn** [comment]
I see, my mistake 🤦 There's no easy way to check if the problem is theme related or functionality related without constantly changing themes at the moment.

While digging into the Catppuccin theme [config](https://github.com/catppuccin/zed/blob/f376e3a02606b942566ad56efd3b9b07fefd8375/themes/catppuccin.json#L118C1-L120C38), I found that the 3 `info` theme entries are being used seemingly randomly, by which I mean that both the `info.border` and `info.background` entries are being used in other parts of the UI that have nothing to do with info badges, so they need to be different from the main `info` entry, as in this example: 

```json
{
  "info": "#179299",
  "info.background": "#747a9499",
  "info.border": "#747a9499"
}
```

Without documentation it's hard to tell how far off the mark I am, but overriding `info.background` to match a "highlight" colour _(like `element.selected`)_ makes the UI more consistent both for highlighting chat replies as in my example, and for the "Unshare" button when in the channels. I'm sure there are other parts of the UI I haven't noticed yet.
