### ISSUE TITLE
Select the message being replied to on "Replying to @<user name>" reply header click

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#10028]
### Check for existing issues

- [X] Completed

### Describe the feature

In the same vain as #10024, to help the user keep context better, I'd like to be able to click on the "Replying to @<user-name>" part of the UI to scroll the message into view if it's not there. At the moment it's quite easy to scroll away from the message being replied to and lose track of where it is in the chat history.

_The screenshot shows the message being selected to reply to, but it's nowhere to be seen in the chat panel._

<img width="1138" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/ee90e157-8801-477c-86bc-539b5701e66e">

**Comment by RemcoSmitsDev** [comment]
Fixed this in #10357.

**Comment by JosephTLyons** [comment]
Closing as the fixed landed!
