### ISSUE TITLE
[vim] Multi Replace mode undo error

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#10031]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/19868292/5cd02d03-8ccd-486a-8b16-099e7946b9d0

### Environment

Zed: v0.129.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by petros** [comment]
Is the expectation not to have to press `u` twice to go back to the original text?

**Comment by petros** [comment]
I checked both vim and nvim, and it seems that it's considered one change from the moment of hitting <kbd>R</kbd> up to hitting <kbd>ESC</kbd>. Which. means if you replace three characters and hit <kbd>ESC</kbd> and <kbd>u</kbd>, all three characters revert at once.

![vim-behavior](https://github.com/zed-industries/zed/assets/28818/4144e9b7-daaf-4d9b-ae46-3e846e04a1d3)

**Comment by 0x2CA** [comment]
Yes, Multi Replace mode counts as making one modification and should revert back to before the mode

**Comment by petros** [comment]
**Steps:**
1. Open a file with the text `aaaa`
2. Hit <kbd>0</kbd> to go to the beginning of the line
3. Hit <kbd>R</kbd> to enter REPLACE mode
4. Type `b` three times so that the text becomes `bbba`
5. Hit <kbd>ESC</kbd>
6. Hit <kbd>u</kbd> to undo
7. **Observation**: The text becomes `bbaa`
8. **Expectation**: The text becomes `aaaa`

**Comment by petros** [comment]
This passes currently:

```rust
#[gpui::test]
async fn test_replace_undo(cx: &mut gpui::TestAppContext) {
    let mut cx = VimTestContext::new(cx, true).await;

    cx.set_state("ˇaaaa", Mode::Normal);
    cx.simulate_keystrokes(["0", "shift-r", "b", "b", "b", "escape", "u", "u", "u"]);
    cx.assert_state("ˇaaaa", Mode::Normal);
}
```

and this fails:

```rust
#[gpui::test]
async fn test_replace_undo(cx: &mut gpui::TestAppContext) {
    let mut cx = VimTestContext::new(cx, true).await;

    cx.set_state("ˇaaaa", Mode::Normal);
    cx.simulate_keystrokes(["0", "shift-r", "b", "b", "b", "escape", "u"]);
    cx.assert_state("ˇaaaa", Mode::Normal);
}
```

with:

```
Unmarked text doesn't match buffer text
Buffer text: "bbaa"
Unmarked text: "aaaa"
Raw buffer text
bbaa
Raw unmarked text
aaaa
```

**Comment by ConradIrwin** [comment]
The right fix here is probably to use group_until_transaction in replace mode similar to how was added to insert mode in #9317.

Happy to pair with anyone on this:https://calendly.com/conradirwin/pairing
