### ISSUE TITLE
Cancel chat message action on another action selection

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#10042]
### Check for existing issues

- [X] Completed

### Describe the feature

It doesn't seem to matter whether I choose to edit my message first and then click "Reply", or the other way around, Zed seems to prioritise message editing on posting, but this isn't reflected in the UI: at the moment it shows both "Edit" and "Reply" textarea headers, which can be confusing as to which action is being fired on posting.

Perhaps the expected behaviour would be to display only the most recent action textarea header, rather than stacking both "Edit" and "Reply".

https://github.com/zed-industries/zed/assets/16290753/9177d9f1-ad2d-4757-ad44-b0a6264e41df

**Comment by RemcoSmitsDev** [comment]
I think this issue can be closed, because #10044 is merged.

**Comment by JosephTLyons** [comment]
Yep, closing this out, as its now in [v0.131.0-pre](https://zed.dev/releases/preview/0.131.0).
