### ISSUE TITLE
vscode stickyScroll

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#10064]
### Check for existing issues

- [X] Completed

### Describe the feature

reference https://code.visualstudio.com/docs/getstarted/userinterface?#_sticky-scroll

**Comment by Moshyfawn** [comment]
There's already an existing feature request for this, so I'm going to close this issue in favour of the other one to keep the conversation in one place. Be sure to leave a +👍.

Duplicate of
- #5344

**Comment by 0x2CA** [comment]
Thank you
