### ISSUE TITLE
ChatGPT support 3.5 no need to pass key

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#10066]
### Check for existing issues

- [X] Completed

### Describe the feature

OpenAI will now allow users to access its popular AI chatbot, ChatGPT, for free, even without creating an account.

<img width="609" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/e1b9b545-f951-407f-a66d-7655c88fa856">

<img width="1336" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/a5bf6810-1013-474d-b092-70a88c90636e">

/cc @nathansobo

**Comment by JosephTLyons** [comment]
I think that ChatGPT, as hosted in the browser on their page, is a different service than that of their API service to ChatGPT. We should check if the API service for 3.5 is also free, since that's what we use.

**Comment by Moshyfawn** [comment]
It still seems to ask for an API key to be included in the request.

**Comment by JosephTLyons** [comment]
Seems like we can't provide it for free then? I guess we can close the issue if not.
