### ISSUE TITLE
Autocomplete viewer not showing the packages they come from (typescript)

### ISSUE THREAD

**Issue by tleunen** [zed-industries/zed#10075]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The autocomplete viewer doesn't show from which packages the functions they come from. In the following simple case, only `useMemo` from the `react` package show in full. But the first one is actually from `@storybook/preview-api` and the last 2 are from internal packages.

Not seeing from what package they come from makes it hard to sometimes pick the right option

![CleanShot 2024-04-02 at 07 54 51@2x](https://github.com/zed-industries/zed/assets/1972567/d8a82762-2c7f-42e1-a6ed-782cdd7650ca)

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Hey,
I've recently landed a PR that should help with autocompletions a bit: #9873 
It should be out in this week's Preview tomorrow.

**Comment by tleunen** [comment]
That's great! Thank you for the update @osiewicz !
