### ISSUE TITLE
Auto close tag

### ISSUE THREAD

**Issue by Xtramemium** [zed-industries/zed#10072]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello! Want request the auto close tag feature. I suggest feature can be enabled/disabled in settings

Example: When you typing any tag like `<div>` Zed automatically closing `</div>` or any HTML tag, suppose it must work with any JS framework

I think its can significantly improve developing speed.

**Comment by widersky** [comment]
https://github.com/zed-industries/zed/issues/5267

**Comment by Moshyfawn** [comment]
Thanks! I'm going to close this issue in favour of the already existing one, to keep the conversation in one place. Be sure to +👍 the other feature request.

Duplicate of
- #5267
