### ISSUE TITLE
file_types setting not honored for eex files

### ISSUE THREAD

**Issue by jerodsanto** [zed-industries/zed#10079]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm trying to associate all `.eex` files with Elixir's `HEEX` type. I added this to my `settings.json`:

```json
"file_types": {
    "HEEX": [
      "eex"
    ]
  }
```

After re-launching the editor and opening a file called `podcast.xml.eex`, its language is still set to `Unknown`. I've also tried a few variations to see if something else would match, including: `".eex"` and `"xml.eex"`. No dice.

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.1
Memory: 64 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
I can't seem to be able to reproduce the described behaviour on Zed Stable _(`v0.128.3`)_ 🤔

https://github.com/zed-industries/zed/assets/16290753/318ca78a-55d0-4e04-87f4-1a116737d7f2

**Comment by jerodsanto** [comment]
Super weird. I'm on same version as you and I can follow your exact same steps and I get the opposite result. 

(Happy to post a video if you have to see it to believe it.)

Could there be some kind of cache or latent thing getting in my way?

**Comment by edgarkanyes** [comment]
I run into the same issue with Kotlin files. Trying to associate `.kts` (e.g. build.gradle.kts) files with Kotlin does not work.
```json
"file_types": {
    "Kotlin": ["kts"]
 }
```

**Comment by bcardarella** [comment]
I am attempting to add `HEEx` template highlighting to `.neex` templates (from LiveView Native)

```json
"file_types": {
   "HEEX": ["neex"]
}
```

no highlighting

But I also don't have highlighting for any `heex` templates either. I followed the [install instructions for Elixir](https://zed.dev/docs/languages/elixir?highlight=elixir#elixir) was there a missing step for syntax highlighting?

On another note, I'd recommend renaming the key from `HEEX` to `HEEx` as that is the proper casing of the format:
<img width="529" alt="Screenshot 2024-05-08 at 5 11 00 PM" src="https://github.com/zed-industries/zed/assets/18524/56f7aa9c-c6d2-4651-b68c-01408749e908">

**Comment by jerodsanto** [comment]
Yo! The 0.148.0 release added this nice feature:

> Added a popup that is displayed when the settings are invalid.

Which revealed that my settings file was, indeed, invalid. This is why the `file_types` setting was not being honored (along with all my other settings, lol). Fixed a typo and now it's working as advertised.

Closing this, thanks!
