### ISSUE TITLE
Two-Finger scroll on trackpad is slower than mouse scroll

### ISSUE THREAD

**Issue by tom-wegener** [zed-industries/zed#10081]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The scrolling with the trackpad is noticeable slower than in other apps or when scrolling with the mouse.

OS is Fedora Linux 39 (Wayland), dependencies installed via nix-flake.

Could be related to #7671 but not sure.

### Environment

Zed: v1.0.0 (Zed Dev)
OS: Linux 1.0.0
Memory: 14.2 GiB
Architecture: x86_64

**Comment by mikayla-maki** [comment]
This should be fixed
