### ISSUE TITLE
Claude 3 Opus `unknown variant error` error

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#10087]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Testing out Claude 3 Opus. Ran a test request and the response died midstream with an error:

```
RPC request `CompleteWithLanguageModel failed - unknown variant `error`, expected one of ....
```

---

As a side note, we should wrap the text in the error popover and maybe style the same way we style our code error popovers:

<img width="405" alt="SCR-20240402-lvkb" src="https://github.com/zed-industries/zed/assets/19867440/060045b7-91f0-429b-b0da-d049d140ed97">

The x decorator in the assistant should also probably match the styling of the one in the status bar when there are diagnostic errors:

<img width="201" alt="SCR-20240402-lvzk" src="https://github.com/zed-industries/zed/assets/19867440/8d9b0cd5-889d-4491-8c36-874ef483aa40">

<img width="48" alt="SCR-20240402-lwbd" src="https://github.com/zed-industries/zed/assets/19867440/b1570812-ed47-4ac6-bf11-392ff3807d80">

@maxdeviant?

### Environment

Zed: v0.130.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1496" alt="SCR-20240402-ltfs" src="https://github.com/zed-industries/zed/assets/19867440/1f389aea-9d5f-4cc0-baf1-24cda39b9cb0">

**Comment by JosephTLyons** [comment]
As a side note, we should wrap the text in the error popover.

**Comment by stjepangolemac** [comment]
Any updates on Claude support?

**Comment by JosephTLyons** [comment]
Can't reproduce
