### ISSUE TITLE
Add command to rewrap text

### ISSUE THREAD

**Issue by as-cii** [zed-industries/zed#1011]
Requested by @russelldb, it is bound to `alt-q` in Emacs rustic mode and I think it is equivalent to Atom `alt-cmd-q` (reflow selection).

**Comment by holman** [comment]
I think this was mistakenly closed (cc @mikayla-maki). Don't think anyone's added this to Zed yet (unfortunately!)

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/zed/pull/17909
