### ISSUE TITLE
No hints from the code

### ISSUE THREAD

**Issue by xyhcode** [zed-industries/zed#10118]
### Check for existing issues

- [X] Completed

### Describe the feature

There was no prompt when writing the code

**Comment by jansol** [comment]
What platform are you on?
What language is the code written in?
Is this a standalone file or a project with a directory hierarchy usually expected by the tooling for the relevant language?

**Comment by xyhcode** [comment]
> What platform are you on? What language is the code written in? Is this a standalone file or a project with a directory hierarchy usually expected by the tooling for the relevant language?

Is it possible that I am not responding to go or js because I am in China

**Comment by xyhcode** [comment]
> What platform are you on? What language is the code written in? Is this a standalone file or a project with a directory hierarchy usually expected by the tooling for the relevant language?

macOS .  Is it possible that I am not responding to go or js because I am in China

**Comment by jansol** [comment]
If that is the case you should see a message in the Zed log (`zed: open log` in the command palette) saying that it failed to download the language server.

For Go it's possible to tell Zed to use an existing installation of gopls in the config: #9803 (needs Zed 0.129.0 or newer)

**Comment by xyhcode** [comment]
> If that is the case you should see a message in the Zed log (`zed: open log` in the command palette) saying that it failed to download the language server.
> 
> For Go it's possible to tell Zed to use an existing installation of gopls in the config: #9803 (needs Zed 0.129.0 or newer)

I found the problem: it may be the problem of the Chinese network that causes the link to timeout. I just uninstalled it and reinstalled it, but there is a problem that sometimes there is no prompt

**Comment by jansol** [comment]
Yeah, this may be related to previous cases where zed tries to auto-update language servers and ends up breaking them when the update fails.

**Comment by xyhcode** [comment]
> Yeah, this may be related to previous cases where zed tries to auto-update language servers and ends up breaking them when the update fails.

Thank you very much for your patience

**Comment by Moshyfawn** [comment]
You can check your logs by opening the command palette and selecting `zed: open log`. The most recent logs at the end of the file might tell you that it's a network problem. Then it might be #8650.
