### ISSUE TITLE
Invalid bindings cause other bindings fail

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#10144]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the below configs, the last invalid bindings will also cause the first two bindings fail to work. 

```
[
  {
    "context": "Workspace",
    "bindings": {
      "ctrl-x ctrl-m": "command_palette::Toggle",
      "ctrl-cmd-l": "workspace::ToggleLeftDock",
      "ctrl-u ctrl x b": [ // Missing `-` between `ctrl` and `x`
        "tab_switcher::Toggle",
        {
          "select_last": true
        }
      ]
    }
  }
]
```

### Environment

Zed: v0.130.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment]
Somewhat related to #9989.

**Comment by asesh** [comment]
> Somewhat related to #9989.

@Moshyfawn  @failable 
It is related. So it would make sense to close this one and track the other one instead?

**Comment by failable** [comment]
Closing in favor of #9989 .
