### ISSUE TITLE
MD Frontmatter Support

### ISSUE THREAD

**Issue by ImpossibleReality** [zed-industries/zed#10150]
### Check for existing issues

- [X] Completed

### Describe the feature

Support for Markdown frontmatter. Currently using frontmatter results in the closing `---` having a line break added above it when formatted which is not compatible with several markdown libraries/frameworks. Additionally would be nice to have YAML syntax highlighting within frontmatter. Should be relatively easy to implement.

**Comment by ImpossibleReality** [comment]
Duplicate of #7938

**Comment by Moshyfawn** [comment]
> Duplicate of #7938 (I swear it didn't pop up in search results for some reason)

That's GitHub search for ya 🫠
