### ISSUE TITLE
Zed does not show git status and git diff when launched from a subfolder

### ISSUE THREAD

**Issue by smitchaudhary** [zed-industries/zed#10154]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you launch zed from a subfolder inside a git repo, then all the git markings do not appear.

Thus, you can no longer see the `git diff`s or any of the other things such as what file has been modified (in the project panel), or the name of the branch (in the top bar) and so on.

These things are visible only if you launch zed from the root of the repo where `.git` resides basically. But I think it would make sense for this to not be the case 

### Environment

Zed: v0.129.1 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="596" alt="Screenshot 2024-04-04 at 10 39 01 AM" src="https://github.com/zed-industries/zed/assets/25204758/0494a556-0895-4d3e-a703-f5c2bc50ba86">
<img width="699" alt="Screenshot 2024-04-04 at 10 39 18 AM" src="https://github.com/zed-industries/zed/assets/25204758/4398d7c6-6794-4860-a291-511fa994fcd4">

The same file, if I launch from the root of the repo, it works.

<img width="684" alt="Screenshot 2024-04-04 at 10 40 37 AM" src="https://github.com/zed-industries/zed/assets/25204758/09d9c84a-f293-4244-838a-208ef7456f63">

**Comment by manosriram** [comment]
@JosephTLyons I'm trying to pick this as my first contribution. Can someone point me where to look at. I can basically see that the path is not considered if there isn't a .git file in the opened folder root.

**Comment by smitchaudhary** [comment]
Addressed by #11550
