### ISSUE TITLE
When soft wrap is enabled, vim mode visual block selects wrapped parts of lines

### ISSUE THREAD

**Issue by JanKoppe** [zed-industries/zed#10159]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've enabled `soft_wrap` with `editor_width` and enabled the vim mode. I've got a bunch of text, where some of the lines have been soft-wrapped. I enter `ctrl+v` to do a visual block selection, select the first two characters of every line and then press `d` to delete those characters.

I would expect that this will only select & delete the actual first two characters of the lines.

Instead, two characters at the beginning of the soft wrap are being deleted as well in the middle of the line.

Actual vim will skip the wrapped lines, and only select the beginnings of the underlying line.

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Visually the issue can be seen here: In the soft-wrapped line 2, the text should not be highlighted/selected, as it is in the middle of the actual line 1.

<img width="687" alt="grafik" src="https://github.com/zed-industries/zed/assets/12087559/4f9fa5c1-4533-4a42-9256-e751fe666f99">

Vim handles this correctly, you can see that in the soft-wrapped line 2 the parts belonging to the actual line 1 are not being selected:

<img width="679" alt="grafik" src="https://github.com/zed-industries/zed/assets/12087559/9bbd8c5f-f3ef-43d8-ace4-00bf2682cf9e">

**Comment by ConradIrwin** [comment]
Thanks for the report! Currently the `SelectionGoal::HorizontalRange` doesn't have a way to distinguish between different parts of the wrapped line. We could "mostly" fix this by assuming we're always on the first wrap; but I think the right fix is to include the number of wraps in the goal (similar to `WrappedHorizontalPosition`, which is used outside of visual block mode).

Happy to pair with anyone on fixing this: https://calendly.com/conradirwin/pairing
