### ISSUE TITLE
zed theme should set the appearance of the app. The appearance of the app will determine the window shadow color of zed.

### ISSUE THREAD

**Issue by oirwnvvwwvc** [zed-industries/zed#10152]
### Check for existing issues

- [X] Completed

### Describe the feature

zed theme should set the appearance of the app. ([NSApplication sharedApplication] setAppearance) 
The appearance of the app will determine the window shadow color of zed.

If the current system appearance is set to dark, then the appearance of zed app will follow the dark appearance set by the system. At this time, the window of the zed app set to light theme will have a dark shadow. Conversely, the window of a zed app set to dark theme will have a light shadow.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="770" alt="system light appearance_app light theme" src="https://github.com/zed-industries/zed/assets/127220903/91f4db05-c119-414b-9065-2102c8f0a214">
<img width="742" alt="system dark appearance_app light theme" src="https://github.com/zed-industries/zed/assets/127220903/2bb10751-003e-4d14-9c0f-f051508028aa">
<img width="762" alt="system dark appearance_app dark theme" src="https://github.com/zed-industries/zed/assets/127220903/4cd8284e-02b5-46c4-9c69-9c7384501e8e">
<img width="712" alt="system light appearance_app dark theme" src="https://github.com/zed-industries/zed/assets/127220903/d72c7922-9484-4d12-9b30-f63af8d3f425">

**Comment by maxdeviant** [comment]
This is already supported by passing an object to the `theme` setting: https://github.com/zed-industries/zed/blob/main/docs/src/configuring_zed.md#theme-object

**Comment by d0sse** [comment]
Is it possible to reopen the issue? The problem persists and is frustrating.

Moreover, it is also reflected in native windows such as "Open File" etc.

VSCode uses the property: workbench.preferredDarkColorTheme or workbench.preferredLightColorTheme to override the app's native theme from the system theme

**Comment by oirwnvvwwvc** [comment]
> Is it possible to reopen the issue? The problem persists and is frustrating.
> 
> Moreover, it is also reflected in native windows such as "Open File" etc.
> 
> VSCode uses the property: workbench.preferredDarkColorTheme or workbench.preferredLightColorTheme to override the app's native theme from the system theme

Sorry, my English is poor so I gave up. You can open a new issue, use my screenshots, and describe the problem again.
