### ISSUE TITLE
[Python] Lack of syntax hightlight 

### ISSUE THREAD

**Issue by skhaz** [zed-industries/zed#10164]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="490" alt="Screenshot 2024-04-04 at 09 42 58" src="https://github.com/zed-industries/zed/assets/46259/9f489875-5535-46b2-bda2-70da3e6b5f72">

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Related to: https://github.com/zed-industries/zed/issues/4341

**Comment by JosephTLyons** [comment]
Let's close this out in favor of #4341.
