### ISSUE TITLE
Support LSP based quick fixes

### ISSUE THREAD

**Issue by marwan-at-work** [zed-industries/zed#10177]
### Check for existing issues

- [X] Completed

### Describe the feature

Gopls suggests quick fixes in various scenarios. The example I'm attaching below is when a Concrete type does not implement an Interface type, gopls can suggest declaring stubs for the missing methods, shown [here](https://github.com/golang/tools/blob/f1d5252456df50ecbf20a3fc80c154067911e925/gopls/internal/analysis/stubmethods/stubmethods.go#L95). 

It would be great if Zed supported this feature to apply suggested fixes coming from the LSP. 

Thanks!

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="382" alt="Screenshot 2024-04-04 at 2 55 44 PM" src="https://github.com/zed-industries/zed/assets/16294261/66a9e3cb-8d13-4a3b-810c-8d06d6d34c5e">

**Comment by JosephTLyons** [comment]
Hey @marwan-at-work, Zed does support quick fixes, or code actions, so there must be some issue with how we are interpretting them from `gopls`?

<img width="391" alt="SCR-20240404-nnfj" src="https://github.com/zed-industries/zed/assets/19867440/e632003f-267e-480b-9dd6-3fab81a7e89a">

cc: @ConradIrwin @mrnugget

**Comment by mrnugget** [comment]
So, I dug into this a bit but haven't found the solution yet. To record some
things already.

Here's how VS Code and Zed request a code action for the given line:

## VS Code

Params:

```json
{
  "textDocument": { "uri": "file:///Users/thorstenball/work/projs/go-proj/main.go" },
  "range": { "start": { "line": 13, "character": 26 }, "end": { "line": 13, "character": 26 } },
  "context": {
    "diagnostics": [
      {
        "range": { "start": { "line": 13, "character": 21 }, "end": { "line": 13, "character": 30 } },
        "message": "cannot use &Router{} (value of type *Router) as http.Handler value in variable declaration: *Router does not implement http.Handler (missing method ServeHTTP)",
        "code": "InvalidIfaceAssign",
        "codeDescription": { "href": "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign" },
        "severity": 1,
        "source": "compiler"
      }
    ],
    "triggerKind": 1
  }
}
```

Response:

```json
[
  {
    "title": "Declare missing methods of http.Handler",
    "kind": "quickfix",
    "diagnostics": [
      // ...
    ],
    "edit": {},
    "command": {
      "title": "Declare missing methods of http.Handler",
      "command": "gopls.apply_fix",
      "arguments": [
        {
          "Fix": "stubmethods",
          "URI": "file:///Users/thorstenball/work/projs/go-proj/main.go",
          "Range": {
            "start": { "line": 13, "character": 21 },
            "end": { "line": 13, "character": 30 }
          },
          "ResolveEdits": false
        }
      ]
    }
  }
]
```

## Zed

Request:

```json
{
  "jsonrpc": "2.0",
  "id": 213,
  "method": "textDocument/codeAction",
  "params": {
    "textDocument": { "uri": "file:///Users/thorstenball/work/projs/go-proj/main.go" },
    "range": { "start": { "line": 13, "character": 22 }, "end": { "line": 13, "character": 22 } },
    "context": {
      "diagnostics": [
        {
          "range": { "start": { "line": 0, "character": 0 }, "end": { "line": 0, "character": 0 } },
          "severity": 1,
          "code": "InvalidIfaceAssign",
          "message": ""
        }
      ],
      "only": ["", "quickfix", "refactor", "refactor.extract", "source"]
    }
  }
}
```

Response:

```json
{ "jsonrpc": "2.0", "result": null, "id": 213 }
```

## Attempts:

So, what's different in the request is that we send `only` along. I took that
out. That also didn't help.

Then I looked at what Neovim does and the request is the same as what I then
ended up sending, but on initialize they send along more code actions they
support:

Neovim:
```json
{
"codeActionLiteralSupport": {
  "codeActionKind": [
    { "", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }
  ]
}

```

Zed:

```json
{
  "codeAction": {
    "codeActionLiteralSupport": {
      "codeActionKind": {
        "valueSet": ["", "quickfix", "refactor", "refactor.extract", "source"]
      }
    }
  }
}
```

So I changed that too, but that also didn't help. Still no quick action to add
the missing members.
