### ISSUE TITLE
Renaming symbols in method arguments broken for ruby

### ISSUE THREAD

**Issue by drale2k** [zed-industries/zed#10188]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to rename a method argument name via "Rename Symbol" in ruby is broken. It appends the new name instead of replacing it. In my tests:

- It only appends to the argument, every other reference in code is renamed properly
- The issue only triggers when "Rename Symbol" is invoked on an method argument. If invoked at another place like a reference within the method, renaming works properly (including the argument)

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

As can be seen, the new name is appended to the argument but the later reference is renamed properly

https://github.com/zed-industries/zed/assets/271416/156e4e62-3dda-40e1-beda-8ef0e71b2af2

**Comment by vitallium** [comment]
Ruby LSP support is pending: https://github.com/Shopify/ruby-lsp/issues/57

**Comment by notpeter** [comment]
I believe this has been fixed upstream in:
- https://github.com/Shopify/ruby-lsp/issues/57
