### ISSUE TITLE
Git status feature state won't be reflected after setting update until next UI redraw

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#10184]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open the project panel
2. Open `settings.json`
3. Insert
```json
"project_panel": {
  "git_status": false
}
```
4. Save `settings.json`
5. See that the project panel colours have not been removed
5.1. Open another tab to see the `git_status` state reflected in the UI

The expected behaviour is that the setting will be applied and reflected in the UI after the `settings.json` file has been modified and saved.

### Environment

Zed: v0.131.0 (Zed Nightly c0d117182fc4c20f750c28345967e64855265227)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/891f51a5-58f0-49e6-9a3a-79176fca325d

**Comment by CharlesChen0823** [comment]
it works well on my machine.
