### ISSUE TITLE
Left dock file browser stuck in green color, independent of theme.

### ISSUE THREAD

**Issue by drale2k** [zed-industries/zed#10180]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My editor's sidebar file browser is stuck in a green font and icon color, no matter which theme i install. Even if the theme has no green color at all. I tried various themes including One Dark and Catpucchino. The screenshots look different than my editor shows them. This only seems to affect the left dock

My current theme is One Dark Pro

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/271416/6c58391c-05e0-442f-af7e-be350c4dc83f

**Comment by Moshyfawn** [comment]
Do you have `experimental.theme_overrides` in your `settings.json` by any chance?

**Comment by Moshyfawn** [comment]
Another theory is that it's the colours of the `git status' file state.

**Comment by drale2k** [comment]
No i don't have `experimental.theme_overrides` configured. My `settings.json` contains only:

```json
{
  "theme": "One Dark Pro",
  "ui_font_size": 15,
  "buffer_font_size": 14,
  "tab_size": 2,
  "tabs": {
    "close_position": "left"
  },
  "lsp": {
    "solargraph": {
      "initialization_options": {
        "diagnostics": true,
        "formatting": true,
        "transport": "stdio"
      }
    }
  }
}
```

> Another theory is that it's the colours of the `git status' file state.
What does this mean? Is that an unintended consequence or something i need to change?

**Comment by Moshyfawn** [comment]
> What does this mean? Is that an unintended consequence or something i need to change?

Try pasting this into your settings config.

```json
"project_panel": {
  "git_status": false
}
```

If the colour of the files in your projects is "fixed" by this, then what you're seeing is the file's [`git status`](https://zed.dev/docs/configuring-zed#git-status), which is turned on by default. It shows whether the file has been committed or modified.

**Comment by drale2k** [comment]
Oh thanks that fixed it. I have a new project and did not commit anything yet. That's why every file was green. Thanks!
