### ISSUE TITLE
Motion v i ) works on Wayland but doesn't work on X11

### ISSUE THREAD

**Issue by SethDusek** [zed-industries/zed#10199]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The motion in vim v i ) doesn't work on X11 (this should select all text inside parentheses). v i } and v i ] and others work, but this doesn't. 

Strangely, when running Zed inside Weston, this does work as expected. Also a motion like "t )" or "t (" also works in both X11 and Wayland, and in general I can type parentheses just fine. 

### Environment

Zed: v1.0.0 (Zed Dev 3ae646386962afb99a803707d1fcc70643492d89)
OS: Linux 1.0.0
Memory: 15.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/9436380/462eb905-3917-40ec-90e0-3d41708875a6

**Comment by CharlesChen0823** [comment]
I debug this phenomenon, found that shift key is emit one more time for key combinations such as (,",{
