### ISSUE TITLE
Cannot close LSP diagnostics if they are too long

### ISSUE THREAD

**Issue by ConradIrwin** [zed-industries/zed#10190]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Make some errors in your cargo files:

<img width="1810" alt="Screenshot 2024-04-04 at 19 47 10" src="https://github.com/zed-industries/zed/assets/94272/02f0718f-3133-4056-995d-6ea389a15529">

### Environment

Zed: v0.131.0 (Zed Nightly c0d117182fc4c20f750c28345967e64855265227)
OS: macOS 14.2.1
Memory: 128 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
#10090 seems like the same issue.

**Comment by ConradIrwin** [comment]
Thanks!
