### ISSUE TITLE
Git Blame: Add a button to open/close

### ISSUE THREAD

**Issue by huacnlee** [zed-industries/zed#10196]
### Check for existing issues

- [X] Completed

### Describe the feature

Maybe we can have a "Git Blame" toggle button to open/close it. Sometime use mouse to close is more easily.

### If applicable, add mockups / screenshots to help present your vision of the feature

For example:

1. Add a Git Blame toolbar when it opened, then we can click the Close icon to dismiss it.

   <img width="1045" alt="image" src="https://github.com/zed-industries/zed/assets/5518/81b0894c-9713-4d7b-a5e3-00859e95959d">

1. Add a status icon or text button to toggle. Or just to close if it opened.

   ![SCR-20240405-ly4](https://github.com/zed-industries/zed/assets/5518/06b0d180-2343-458b-aef4-d03b971c4a97)

Considering that this feature may not be commonly used by everyone, we may consider adding only a close button.

**Comment by jansol** [comment]
I prefer the status button, if only because it does not add another bar taking up space from the buffer. Maybe it could simply be a "version control" icon next to the inlay hints/buffer search/inline assist buttons in the toolbar?

**Comment by coolemur** [comment]
How do you even open git-blame without this button ? 👀

**Comment by bennetbo** [comment]
> How do you even open git-blame without this button ? 👀

In the command palette (`cmd+shift+p`) you can run `editor: toggle git blame` or wire it up to a shortcut in your settings file. Default keybinding is `"cmd-alt-g b": "editor::ToggleGitBlame"`

**Comment by coolemur** [comment]
> > How do you even open git-blame without this button ? 👀
> 
> In the command palette (`cmd+shift+p`) you can run `editor: toggle git blame` or wire it up to a shortcut in your settings file. Default keybinding is `"cmd-alt-g b": "editor::ToggleGitBlame"`

Is this feature not on released version yet? There is no `editor: toggle git blame` in my command palette.
And 'Check for updates' shows that Zed is up-to-date.

**Comment by huacnlee** [comment]
@coolemur It in the preview version
