### ISSUE TITLE
Unclearable error pane 

### ISSUE THREAD

**Issue by rgbkrk** [zed-industries/zed#10217]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If, when using Rust, an error to build a project is big enough then it's too big to clear from view: 

<img width="1840" alt="image" src="https://github.com/zed-industries/zed/assets/836375/c064cd36-4ec4-421c-8b9d-b3d1a3bf0f61">

### Environment

Zed: v0.131.0 (Zed Nightly 773a3e83ad906b622e6417dd69bb44c7e80204ef)
OS: macOS 14.4.1
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1840" alt="image" src="https://github.com/zed-industries/zed/assets/836375/5a24c024-45b1-443d-a6fd-c3f6faf6b110">

**Comment by Moshyfawn** [comment]
I have a feeling this is the problem @ConradIrwin has in #10190, which had actually been reported in #10090 🤭

**Comment by rgbkrk** [comment]
Sure enough, I'll close this one. I didn't search well enough.
