### ISSUE TITLE
In vim mode, SelectToEndOfLine is not selected to the end

### ISSUE THREAD

**Issue by weartist** [zed-industries/zed#10223]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In vim mode, I found that when using the default SelectToEndOfLine shortcut (cmd-shift-right) it was not selected to the end of the file, I wondered if this was a bug, if it was I could try to fix it
<img width="310" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/2b3d10ad-c38b-4382-bfb4-e8d1381827ee">
<img width="277" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/85c2d97b-e9a2-4ec8-b6e9-d41c0df3fd49">

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
This is a bug, and is probably related to https://github.com/zed-industries/zed/issues/8492.

When you do something that is not in vim mode, but which changes the selection, we react to that https://github.com/zed-industries/zed/blob/2687fb6b18ddd30344fda1424ac8886294c967be/crates/vim/src/vim.rs#L216; I think we need to ensure that if the selection is from left->right, we include the last character.
