### ISSUE TITLE
Don't work "Code Actions" in vue files

### ISSUE THREAD

**Issue by klyuk88** [zed-industries/zed#10245]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After clicking on Code Actions in the Vue files, nothing happens. 
This works only in TS files.

### Environment

Zed Preview 0.130.1
Vue 3 + Vite project 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1013" alt="Снимок экрана 2024-04-07 в 10 11 42" src="https://github.com/zed-industries/zed/assets/48031577/49078669-1ab5-4fd8-9f78-5205c9517178">

**Comment by JosephTLyons** [comment]
Hey @klyuk88 - I'm not a `vue` dev, should the code actions here be the same ones as delivered by the `ts`/`js` languge server (`tsserver)?

**Comment by klyuk88** [comment]
Yes, for example in nvim, webstorm, vscode Code Actions works in vue files as well as in ts files.

**Comment by chungweileong94** [comment]
This feels related/similar to #10786. Basically the code actions (or even code formatted) stop working randomly, it happens quite often in TS/JS, where we often need an extra LSP like Vue, Biome, etc. So far it never really happened for Rust or Python development, so I guess it's most likely a multi-LSPs problem.
