### ISSUE TITLE
Prettier doesn't format Java

### ISSUE THREAD

**Issue by dickeyy** [zed-industries/zed#10241]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Prettier will not format Java as it does with any other language that I've tested... I have the [Java extension](https://github.com/louisnicolas-longheval-vinci/zed-java-extension) installed and have my prettier config file set up. 

To reproduce, create any Java file and mess up the formatting, then either save or use the editor: format built-in command. No formatting happens. 

If I open up the same file in another IDE, prettier performs as expected. Not sure if it could be by settings, but I've gone through all of them and I don't see anything that may be messing it up.

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @dickeyy - Surprisingly, I didn't know prettier formatted Java at all, but I'm not heavy into the world that typically uses prettier. Checking [prettier's homepage](https://prettier.io), it shows that java support comes from [an extension](https://github.com/jhipster/prettier-java). Have you tried installing and using this?

**Comment by SomeoneToIgnore** [comment]
Zed has an extra field that prettier-supported languages has to declare in their manifests, e.g. : https://github.com/zed-industries/zed/blob/3e6a9f68907154009f6741bb8a2ec037c00b7bd8/extensions/svelte/languages/svelte/config.toml#L17-L18

Current Java extension seem to have none of these fields, so nothing will indicate that Prettier supports it and no formatting will ever happen: 

https://github.com/louisnicolas-longheval-vinci/zed-java-extension/blob/cafa9e64c1cec860ba17eb13e8554fe6d537b7b7/languages/java/config.toml

**Comment by dickeyy** [comment]
> Current Java extension seem to have none of these fields, so nothing will indicate that Prettier supports it and no formatting will ever happen:

You are the goat thank you! I have fixed it, waiting on PR merge https://github.com/louisnicolas-longheval-vinci/zed-java-extension/pull/5

**Comment by JosephTLyons** [comment]
Thanks @SomeoneToIgnore - I was wayy off here 😂 - I shouldn't try to debug things in ecosystems I'm not familiar with.
