### ISSUE TITLE
git commit dialog

### ISSUE THREAD

**Issue by aohanhongzhi** [zed-industries/zed#10259]
### Check for existing issues

- [X] Completed

### Describe the feature

I need a git commit dialog the same as vscode .

![image](https://github.com/zed-industries/zed/assets/37319319/bfd7a67a-5a24-45ba-8ff9-f29de640bdaa)

**Comment by SomeoneToIgnore** [comment]
That seems to be a part of https://github.com/zed-industries/zed/issues/8665 roadmap, so closing.
