### ISSUE TITLE
keyboard-accessible recent panel

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#10258]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Is there a keyboard-accessible way to close recents with this UI,
like tab switcher use `ctrl-backspace`
![image](https://github.com/zed-industries/zed/assets/19868292/88cdc0fd-69f3-4cdd-8720-09bf4cd88eca)

### Environment

Zed: v0.130.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @0x2CA, does `esc` work for you?
