### ISSUE TITLE
Desktop App Package (Wails.io) dIsables go lsp / disables syntax and error highlighting / terminal issues/copilot inconsistency 

### ISSUE THREAD

**Issue by mstiles-grs** [zed-industries/zed#10253]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am writing an application with Wails. I have noticed that when wails is running zed cannot use any go/terminal features. It does however work with .js/.ts/.vue files.

The following issues are holistic, due to there being so many I can't really write them in great detail. Along with that, there are no error logs present. There is no real way to show the issue I am afraid other than listing the issues. The behavior is the same across Zed stable and preview.

1.  Code actions no longer appear
2. FMT formatting doesn't fire
3. No error highlighting
4. No GO LSP support
5. Terminal does not recognize wails commands
6. With Copilot enabled, and suggestIons turned on, no suggestions are given

The first two screenshots I am attaching shows that vue LSP and copilot are working properly. The following  screenshots after shows that error highlighting/LSP/copilot suggestions are not updating/frozen. 

The issues also persist after you kill the wails application. Meaning i have to force quit Zed to have it perform as expected.

### Environment

M1 Mac
Zed stable 0.129.2
Zed preview 0.130.1
go 1.21
wails 2.8

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-04-07 at 9 55 25 AM](https://github.com/zed-industries/zed/assets/104839764/3acbc627-2f0d-4b70-af53-6c7af61bb868)
![Screenshot 2024-04-07 at 9 55 38 AM](https://github.com/zed-industries/zed/assets/104839764/973e48d8-d869-4549-aa76-79e0eb492ed8)

![Screenshot 2024-04-07 at 9 55 50 AM](https://github.com/zed-industries/zed/assets/104839764/91cea59c-c616-4255-b2c4-c5c7e687901e)
![Screenshot 2024-04-07 at 9 56 40 AM](https://github.com/zed-industries/zed/assets/104839764/74517b81-f6d9-4d13-9ce3-e57eada4aec0)

![Screenshot 2024-04-07 at 10 01 13 AM](https://github.com/zed-industries/zed/assets/104839764/615cb6d2-e882-426d-a0f2-4fb0f4952334)

**Comment by JosephTLyons** [comment]
Hey @mstiles-grs, this issue sure is a weird one. I'm curious, what happens if you run the `editor: restart language server` action after runnin the walls application? Does the functionality come back at all? Also, you mentioned having issues with the terminal as well - what issues are you running into?

**Comment by mstiles-grs** [comment]
Hi @JosephTLyons,

I just tried running the restart command and nothing happened. I also was curious if I started another LSP, like for a different language, and nothing happens not even a log.

I just had a thought though, wails has what is essentially a live reload functionality for Go... which might be the root cause of all of these issuer... The terminal inconsistency may not be as a big deal, I tried running a wails command in a vs code terminal, and it couldn't find the wails package either.... which was the terminal inconsistency. May just be a general issue with terminal emulator.

**Comment by mstiles-grs** [comment]
@JosephTLyons ,

I actually take back what I said about the terminal. I figured out how to run the wails commands in the emulated terminal (i didn't export my go path), but I think the vue LSP that zed installs messes with wails too.

The screenshot is what I git when I run`wails dev` inside the terminal. However when I run it on iterm2 I get no such error.

The Go LSP is still acting the same regardless of where I run the commands.

![Screenshot 2024-04-10 at 6 34 08 PM](https://github.com/zed-industries/zed/assets/104839764/74afd7de-e938-4026-882a-68fef194612d)
