### ISSUE TITLE
vim and BufferSearchBar

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#10263]
### Check for existing issues

- [X] Completed

### Describe the feature

in vim,BufferSearchBar is redundant interface,Is it possible to directly use a command form similar to `:/`
![image](https://github.com/zed-industries/zed/assets/19868292/b8f5fa37-7a50-4a00-b8ba-9ac66f42b81a)
This can unify `:%s/` with `:s/` and `/`, although it is better if the input is close to the bottom of the original vim.

**Comment by baldwindavid** [comment]
> in vim,BufferSearchBar is redundant interface

Not sure I'd characterize this as a "redundant" interface. In the vim implementations I've used, searched terms resulting from `/` always show up _somewhere_; it's just that this one happens to use the buffer search element. I'd probably prefer something more subtle, but there is already some amount of "unification" in leveraging the buffer search bar for regular and vim modes.

> Is it possible to directly use a command form similar to :/

I certainly would not want to type an extra `:` just to use vim search and popping up the command modal would be even more obtrusive than the buffer search bar. That being said, as long as it's not the only way to access search, I don't really have a strong opinion on whether this should or shouldn't be added.

**Comment by ConradIrwin** [comment]
This should work already, but it does cause the search bar to open, which causes the editor to jump around, which is not great. I'd like to keep using zed's search bar, but I would like to fix it so that the buffer doesn't move around when you open it (cc @iamnbutler).

<img width="675" alt="Screenshot 2024-04-08 at 11 12 17" src="https://github.com/zed-industries/zed/assets/94272/29310072-41ae-4a28-8aff-06f6f55c538c">

**Comment by baldwindavid** [comment]
> I would like to fix it so that the buffer doesn't move around when you open it

Agreed on that. Think it would be nice if it could overlay rather than take up space and be configurable at the top or bottom of the pane (I'd choose bottom since there is typically whitespace there, doesn't occlude the start of the file, and is more similar to vim).

**Comment by 0x2CA** [comment]
> This should work already, but it does cause the search bar to open, which causes the editor to jump around, which is not great. I'd like to keep using zed's search bar, but I would like to fix it so that the buffer doesn't move around when you open it (cc @iamnbutler).
> 
> <img alt="Screenshot 2024-04-08 at 11 12 17" width="675" src="https://private-user-images.githubusercontent.com/94272/320588962-29310072-41ae-4a28-8aff-06f6f55c538c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjYyOTgsIm5iZiI6MTcxMjYyNTk5OCwicGF0aCI6Ii85NDI3Mi8zMjA1ODg5NjItMjkzMTAwNzItNDFhZS00YTI4LThhZmYtMDZmNmY1NWM1MzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAxMjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYTMwMGM4ZDM2NzQ0YThkODQwYThjZDI1OWExYzI4ZjExNDBmNzI4Y2JlY2JjYjA5NTUxMjg4MTY0NzE3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rX6zT5hHDuv1IPPbPswIPAhaInDEUZ1Q4H0A2SwmGio">

I've tested it before opening this issue and it does work.But this is not a default behavior, it needs to be `:` then `/`,According to what you said, using the searchbar is still a bug right now, looking forward to fixing him!
Another query is that this function does not seem to support `\c` `\C`.

**Comment by ConradIrwin** [comment]
Makes sense, sorry for misunderstanding.

I don't really want to have two versions of search in Zed, but I do see a number of areas in which the zed search is not quite as good as the vim one (but I think we should fix those for everyone, not just vim users).
