### ISSUE TITLE
How can I run the code?

### ISSUE THREAD

**Issue by khuongtai** [zed-industries/zed#10274]
### Check for existing issues

- [X] Completed

### Describe the feature

I have a python file, how can I have a button to run that file without typing it into the terminal?

**Comment by bennetbo** [comment]
There is no "run" button right now, but you can use the task api to run a python file from the command palette. See #9834 for more information

**Comment by JosephTLyons** [comment]
> There is no "run" button right now, but you can use the task api to run a python file from the command palette. See #9834 for more information

Ironically enough, a `run` button just hit main today:

- https://github.com/zed-industries/zed/pull/10267

<img width="280" alt="SCR-20240408-juto" src="https://github.com/zed-industries/zed/assets/19867440/6e0c0667-3411-45ab-b263-cf74793cd2a5">

**Comment by JosephTLyons** [comment]
I think I will close this issue out, since we do have a button now and the Discussion linked above shows some examples of how to run a file. If you have any problems setting up a task @khuongtai, you can post in Discussion linked above.
