### ISSUE TITLE
Commands `editor: next/previous completion` are not available

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#10283]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There is a command `editor: show completion`, but the commands `editor: next/previous completion` are missing, making it impossible to map `Tab/Shift-Tab` to cycle for available completions:

<img width="544" alt="Снимок экрана 2024-04-08 в 19 35 27" src="https://github.com/zed-industries/zed/assets/230824/41c9e3dd-87e0-4786-8942-529f55e39c46">

### Environment

Zed: v0.130.1 (Zed Preview)
OS: macOS 12.7.4
Memory: 32 GiB
Architecture: x86_64

**Comment by osiewicz** [comment]
Hey, thanks for reaching out.
Completions menu uses `editor::ContextMenuNext`/`editor::ContextMenuPrev` actions for navigation.
I believe the following keybindings should do the trick for you:
```
  {
    "context": "Editor && showing_completions",
    "bindings": {
      "shift-tab": "editor::ContextMenuPrev",
      "tab": "editor::ContextMenuNext"
    }
  },
```

**Comment by VKondakoff** [comment]
Ah, yes, exactly. Thank you for pointing me. Works like a charm!

**Comment by osiewicz** [comment]
I'll close that issue out for now. Feel free to reopen if anything pops up.
