### ISSUE TITLE
How do disable references to `xxx`?

### ISSUE THREAD

**Issue by hungify2022** [zed-industries/zed#10306]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

How do we prevent clicking on attribute HTML tags or variables, etc?

Look at the video below, is there any configuration to disable it? (vscode only shows underline and unclickable)

https://github.com/zed-industries/zed/assets/126773143/da93e241-e7ec-465c-a8ee-18fbe6450c9b

### Environment

Zed: v0.130.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @hungify2022, there isn't curretnly a setting to disable `find all references` from being triggered when holding down `cmd` and clicking on some item in the editor. I'm curious to hear about you wanting to disable it - is it getting in the way of your workflow?

**Comment by JosephTLyons** [comment]
Let's close this out in favor of:

- https://github.com/zed-industries/zed/discussions/10305
