### ISSUE TITLE
Zed won't launch on Mac M2

### ISSUE THREAD

**Issue by tjstevens** [zed-industries/zed#10303]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed fails to launch from app icon and terminal open.  No error thrown nor any log file.  Macbook Air, Sonoma 14.4.1, M2 chip.

### Environment

Zed won't launch.  No access to command palette.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

No log file present.

**Comment by tjstevens** [comment]
Uploading Screen Recording 2024-04-08 at 9.34.07 PM.mov…

**Comment by mrnugget** [comment]
Does it print anything when you run `/Applications/Zed.app/Contents/MacOS/zed` from the command line?

**Comment by JosephTLyons** [comment]
I wonder if this is the same thing as:

- https://github.com/zed-industries/zed/issues/9711

**Comment by tjstevens** [comment]
FIXED

@JosephTLyons was right about this being the same as #9711 

@mrnugget FWIW the output was 
> thread 'main' panicked at crates/zed/src/main.rs:498:54:
> could not create tmp path: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
