### ISSUE TITLE
Symbol renders improperly in Zed, but works fine elsewhere

### ISSUE THREAD

**Issue by danielzsh** [zed-industries/zed#10308]
### Check for existing issues

- [X] Completed

### Describe the feature

Using JetBrains Mono font, the glyph with unicode 59160 renders like so in Hyper terminal:
<img width="218" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/ebcb393d-6502-4ed5-a118-0954a70ee412">

But renders like this in Zed:
<img width="293" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/c12edb91-85ee-48a7-b903-cfa560af0ae9">

Here's my `settings.json`:
```json
{
  "show_copilot_suggestions": true,
  "base_keymap": "VSCode",
  "theme": "Catppuccin Macchiato",
  "ui_font_size": 14,
  "buffer_font_size": 14,
  "buffer_font_family": "JetBrains Mono",
  "format_on_save": "on",
  "tab_size": 2,
  "vim_mode": true
}
```

**Comment by 0x2CA** [comment]
hi,My computer displays normally，
![image](https://github.com/zed-industries/zed/assets/19868292/289225f1-ab20-4ec1-9e2b-26aeb53ad3a2)
![image](https://github.com/zed-industries/zed/assets/19868292/0984bd7f-a509-42f5-91f2-808b02201a46)

**Comment by danielzsh** [comment]
Ah I see, I was under the impression that JetBrains Mono itself was a nerd font already...thanks for the help!
