### ISSUE TITLE
Add a collapse option on project search files

### ISSUE THREAD

**Issue by volfcan** [zed-industries/zed#10312]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to collapse files in the project search panel. I'm searching simple "parse" as a search keyword and I see millions of lines of package-lock.json file words that requires endless scrolling to skip.

### If applicable, add mockups / screenshots to help present your vision of the feature

![collapse](https://github.com/zed-industries/zed/assets/68243739/bc495ce6-731e-4c9e-832b-38131f9c8719)
™

**Comment by 0x2CA** [comment]
duplicate [Fold search result #10228](https://github.com/zed-industries/zed/issues/10228)

**Comment by JosephTLyons** [comment]
Hey @volfcan, thanks for the report - for the time being, as a workaround, you can filter these out with the `exclude` field, using some patterns like this:

<img width="787" alt="image" src="https://github.com/zed-industries/zed/assets/19867440/b304cc20-e515-4b37-9695-67b1b4e1154a">

I'm going to close this out, as a dupe, in favor of:

- https://github.com/zed-industries/zed/issues/10228
