### ISSUE TITLE
Website Changelog CSS Bug

### ISSUE THREAD

**Issue by xcrap** [zed-industries/zed#10328]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First of all, I love Zed website, it's super clean and visually effective, but there's a tiny big in the releases pages, specifically in 

https://zed.dev/releases/stable/0.129.1
https://zed.dev/releases/stable/0.125.3

And of course also https://zed.dev/releases/stable because it includes all changes.

This happens in some `<code class="bg-accent-blue/10 -mx-1 py-0.5 px-1 font-mono text-sm whitespace-nowrap">xxx</code>` elements where it breaks the width of the parent window, (can see one example below). This is easily fixed by removing the whitespace-nowrap class or changing for a whitespace-break, it of courses loses the line break but makes everything inside the div. The examples I gave was for desktop, in mobile there are more breaks. 

I'm sorry If I placed this in the wrong place, but the website it's so good and I've noticed this weeks ago and I think you should be aware because everyone can notice but it adds horizontal bars in smaller devices so it's annoying.

### Environment

n/a

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="966" alt="Screenshot 2024-04-09 at 15 59 44" src="https://github.com/zed-industries/zed/assets/828596/34463411-bde0-49e3-b049-07f1d821902c">

Without whitespace-nowrap

<img width="778" alt="Screenshot 2024-04-09 at 16 00 02" src="https://github.com/zed-industries/zed/assets/828596/f96c27d1-036b-4c28-88e1-13afb0cc4e43">

**Comment by JosephTLyons** [comment]
Thanks for the tip @xcrap - I just pushed that change up - should be live in a few minutes.

> I'm sorry If I placed this in the wrong place

This is the right place to put zed.dev bugs, as that repo isn't open source. That might change in the future, I dont think we've fully decided either way, as a team.

**Comment by JosephTLyons** [comment]
Yay! 🎉

<img width="671" alt="SCR-20240409-lxpt" src="https://github.com/zed-industries/zed/assets/19867440/1f109970-1449-47f4-9aca-8fb4473421e0">
