### ISSUE TITLE
When soft wrapping is enabled, vim moves forward fails

### ISSUE THREAD

**Issue by weartist** [zed-industries/zed#10350]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure if it has anything to do with #10159 ,  In normal mode, moving forward will stop at the beginning of the line, which should be expected, but it will also stop when soft wrapping is enabled, maybe it should be allowed to move forward here?

https://github.com/zed-industries/zed/assets/17105034/9ae4d01b-e2fd-499c-a698-e661d85842a3

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

**Comment by 0x2CA** [comment]
hi,This seems to be no problem if there are spaces in front of the lines.


https://github.com/zed-industries/zed/assets/19868292/dd1a0ef1-f29e-4b70-a6a3-5e122a3faa71

**Comment by ConradIrwin** [comment]
I think this is not related to #10159, but probably shares a common cause (the vim code seems to have been written before soft wrapping :D).

Looking at the implementation of `Left` and `Right` in vim, you can see that they use display co-ordinates, they should be updated to use buffer coordinates instead.

**Comment by weartist** [comment]
> I think this is not related to #10159, but probably shares a common cause (the vim code seems to have been written before soft wrapping :D).
> 
> Looking at the implementation of `Left` and `Right` in vim, you can see that they use display co-ordinates, they should be updated to use buffer coordinates instead.

I submitted a simple modification to accommodate soft_wrap. The right movement doesn't need to be handled, it can be done very well XD
