### ISSUE TITLE
linux: Startup memory usage is very large

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#10351]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/12579229/733635fd-3560-418d-af01-d94c55d92d99)

### Environment

deepin v23
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian

**Comment by mikayla-maki** [comment]
Thanks for letting us know, what where you doing or what project did you open that led to this problem?

**Comment by ethan-phu** [comment]
It is a C language project, and search for a function name. There are about 30,000 files in this project.

**Comment by andywampir** [comment]
Perhaps this problem related to https://github.com/zed-industries/zed/issues/9744

**Comment by balazsbotond** [comment]
I can confirm. I've just build the latest version on `master`, and with a single 13B text file open, Zed uses 1GiB of RAM:

![image](https://github.com/zed-industries/zed/assets/2791280/dbf64c21-5f45-4175-b7bc-5ddf81e2cce1)

This increases with every new window I open (2 windows: 3.0GiB, 3 windows: 4.0GiB, 4 windows: 6.0GiB), but it doesn't seem to depend on the number of files open or the size of the project in a single window.

Closing a window decreases the memory usage by the same amount it added when opening.

I use Fedora 39, KDE and Wayland on an x86_64 CPU.

**Comment by nt8r** [comment]
I ran under valgrind DHAT and obtained the attached trace: [dhat.out.131305.json](https://github.com/zed-industries/zed/files/15283267/dhat.out.131305.json)

It seems like Zed makes a single 1.46GB allocation in `[ash::device::create_descriptor_pool](https://github.com/ash-rs/ash/blob/master/ash/src/device.rs#L1584)`. Perhaps `blade-graphics`' [choice of 60000 for `ROUGH_SET_COUNT`](https://github.com/kvark/blade/blob/main/blade-graphics/src/vulkan/mod.rs#L274) isn't sane?

**Comment by nt8r** [comment]
Confirmed, decreasing the `60000` there to `500` cuts memory usage (RSS) from ~1728MB to ~180MB without any noticeable adverse effects.

**Comment by filipwiech** [comment]
@nt8r Thank you so much for this great finding, I was wondering why Zed was using so much memory with seemingly nothing going on! :+1:
@kvark This might be of interest to you, any idea if this seems to make sense to you and could be adjusted without any adverse side effects? :slightly_smiling_face:

**Comment by kvark** [comment]
I was hoping that "gpu-descriptor" would allow me to use it with the specific workflow, eventually, but this hasn't happened yet. Filed https://github.com/zakarumych/gpu-descriptor/issues/42 to track.
In the meantime, we can at least add a progressive scheme where the first pool has 10 sets, second pool has 100 sets, third has a 1000, etc.

**Comment by kvark** [comment]
Prototyped a solution here - https://github.com/kvark/blade/pull/118
