### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by machinescream** [zed-industries/zed#10359]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to have flow support extension to play with in awesome zed editor

**Comment by JosephTLyons** [comment]
Hey @machinescream, we have a request here in the `extensions` repo for flow:

- https://github.com/zed-industries/extensions/issues/474

Can you upvote that one with a 👍? I'm going to close this one out to keep all the votes in one spot.
