### ISSUE TITLE
Assistant panel crashes when opening conversation history in Zoom mode

### ISSUE THREAD

**Issue by cmuhire** [zed-industries/zed#10362]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening the assistant panel in Zoom mode, then trying to switch to conversation history, the whole assistant panel dies and attempting to re-open it consistently fails. This seems to only happen in Zoom mode.

Steps to reproduce:
- Open the assistant panel (Cmd+R)
- Switch to Zoom mode (Shift-Esc)
- Click the hamburger menu to open conversation history. The assistant panel dies
- Attempting to re-open the assistant panel consistently results in a similar fate

Here's a GIF with highlighted keystrokes to illustrate the issue
![2024-04-10 17 12 16](https://github.com/zed-industries/zed/assets/6691440/4286b679-6ae0-4333-a0b9-0da35a69141f)

### Environment

```
Zed: v0.129.2 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64
```

**Comment by JosephTLyons** [comment]
Ouch, this one feels rough - thanks for the report @cmuhire!

**Comment by Moshyfawn** [comment]
This doesn't seem to happen anymore _(Tested [`v0.149.1`](https://zed.dev/releases/preview/0.149.1))_ due to the way the assistant panel has been restructured. I'm going to close this issue, but please let us know if you're still experiencing the problem so we can re-open it.

**Comment by cmuhire** [comment]
I can confirm that the issue is now fixed. Thanks!
