### ISSUE TITLE
Re-saving saved files seems to have changed?

### ISSUE THREAD

**Issue by brandonweiss** [zed-industries/zed#10368]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you make changes and save a file it saves. If you then immediately save that file again, it does not re-save. This used to work, so I assume something must’ve changed, but I can’t tell from the release logs if that was intentional or not.

This is problematic for situations where you’re relying on a process to watch for changes to files. For example a test runner might watch which files you’re saving in order to automatically run the tests for that file in the console. Re-saving a saved file is a way to tell the runner to run the file even if there haven’t been any changes to the file.

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
There's been a bug, fixed in https://github.com/zed-industries/zed/pull/10174 and available in both latest Zed Stable (0.130) and Preview (0.131).

Sorry for the inconvenience, please update to the newer versions to get that fixed.

**Comment by brandonweiss** [comment]
@SomeoneToIgnore Thank you!
