### ISSUE TITLE
Find all is not response

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#10388]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/12579229/386b4df0-b62b-4f63-9079-85e84e34e86e)
when i search a keyword in all the files, it not response

### Environment

mac M2

**Comment by JosephTLyons** [comment]
Hey @ethan-phu, does Zed just continuously report as `Searching...` or does it eventually end, finding no results? Are you in a repository that has symlinks pointing anywhere?

**Comment by ethan-phu** [comment]
The project directory is very large, and when searching for the `send_log` function, it always shows that it is searching, and there is no response for a long time.

**Comment by JosephTLyons** [comment]
Does find project search work for you, in smaller projects?

**Comment by ethan-phu** [comment]
in smaller projects, it work well

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/20211 had improved things quite drastically on that front, so I'll close this until more details are provided.
