### ISSUE TITLE
With introduction of Image preview feature there is no way to edit textual image formats (svg) as a code in Zed

### ISSUE THREAD

**Issue by nazgu1** [zed-industries/zed#10403]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Maybe I'm missing something, but I've searched through documentation, release notes, PR related to Image preview and I can't find any way to open `.svg` files in edit mode.

Steps to reproduce:
1. Open workspace with svg file
2. Click of svg file in project tree
3. SVG preview appears
4. (Expected) User should be able to choose preview/edit mode (e.g by clicking with some modifier key)

### Environment

Zed: v0.130.5 (Zed)
OS: macOS 14.4.1
Memory: 24 GiB
Architecture: aarch64

**Comment by tao** [comment]
Same. I edit `.svg` files all the time for web development and now it just opens the preview in the latest update. 

It seems like I have to change the filetype to a `.txt` first to edit it and rename it back again?

**Comment by peloycosta** [comment]
Second this, editing SVG is extremely useful. 
Also add that it seems like failing to preview some svg files crashes zed (#10421), opening it as text as a fallback could be a workaround.

**Comment by rgbkrk** [comment]
Absent a way to flip modes, I think I better disable SVG for the image previewer. Thanks all.

**Comment by rgbkrk** [comment]
Fixed in https://github.com/zed-industries/zed/pull/10435, shipped in Zed preview.

**Comment by perkrlsn** [comment]
Couldn't `.svg` previews be toggled the same way markdown previews are toggled? It would be really nice to have the possibility to have them side by side. (Sorry for posting in a closed issue).
