### ISSUE TITLE
In vim, the inner object is wrong in the range selected

### ISSUE THREAD

**Issue by weartist** [zed-industries/zed#10413]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/17105034/28aac656-6f30-44e9-b60c-316cf434ae46

In the video I ran vi[ and va[, and I can see that vi[ doesn't have the space inside the parentheses checked, and I wonder if this is the expected behavior, or if it's a bug

### Environment

Zed: v0.130.5 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

**Comment by CharlesChen0823** [comment]
i test in vim and nvim:
- in vim: vi[ and vi] select all in `[]`,
- in nvim: vi[ select all in `[]` but trim space, vi] select all in `[]`

**Comment by weartist** [comment]
I'm thinking that if we could select all of them, it would be a lot simpler for some of the computational logic, if that's the right one
