### ISSUE TITLE
Autorepeat is sluggish on linux

### ISSUE THREAD

**Issue by brayo-pip** [zed-industries/zed#10414]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hold down a key for long enough for autorepeat to kick in. Expected behavior is that the letter is typed multiple times at a rate comparable to other text editors. It's however it's slow typing a single letter a second. This also applies when using the arrow keys for scrolling.

### Environment

# System Details Report
---

## Report details
- **Date generated:**                              2024-04-11 15:48:50

## Hardware Information:
- **Hardware Model:**                              HP HP ProBook 450 G6
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i5-8265U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (WHL GT2)
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            R71 Ver. 01.19.00
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.25-1-MANJARO

**Comment by brayo-pip** [comment]
After a while the window becomes unresponsive. A second window open is still responsive!

**Comment by brayo-pip** [comment]
I can't determine the exact conditions for reproduction, it comes and goes.

**Comment by mikayla-maki** [comment]
Fixed in https://github.com/zed-industries/zed/pull/10452

**Comment by adamczykm** [comment]
Just a question - I don't want to start a new issue rn. Can you somehow make the autorepeat faster, i.e. achieve the result similar to what `xset r rate 200 52` does?

**Comment by michalrus** [comment]
Possibly related:
* #43330
