### ISSUE TITLE
test_disabled_keymap_binding fails on Linux with "Invalid keystroke `cmd-k`"

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#10427]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

> failures:
> 
> ---- zed::tests::test_disabled_keymap_binding stdout ----
> thread 'zed::tests::test_disabled_keymap_binding' panicked at crates/zed/src/zed.rs:664:48:
> called `Result::unwrap()` on an `Err` value: Invalid keystroke `cmd-k`
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 
> failures:
>     zed::tests::test_disabled_keymap_binding
> 
> test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 3.34s

Found over in NixOS/nixpkgs#303233 where it causes the `checkPhase` of the package build process to fail.

While we can simply disable the test for packaging purposes, I think this kind of "invalid" keymap should be handled gracefully in Zed (incl. tests).

### Environment

NixOS unstable
Linux 6.8, both aarch64 and x86_64

**Comment by Luk-ESC** [comment]
Looks like the same issue as #10382, which seems to actually affect users.

**Comment by mikayla-maki** [comment]
Fixed
