### ISSUE TITLE
UI using SF (default) font instead of the Zed default

### ISSUE THREAD

**Issue by lino-levan** [zed-industries/zed#10424]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It seems like the UI font has been reset to the Mac OS default instead of using whatever Zed font it was using before. 

What Zed Preview currently looks like:
<img width="1440" alt="image" src="https://github.com/zed-industries/zed/assets/11367844/505e682f-04a0-4817-a0e3-dd813da2d834">

Seems maybe related to https://github.com/zed-industries/zed/issues/9810 but unsure. Happy to hop on a call and debug.

### Environment

Zed: v0.131.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
This is expected and has been explicitly called out in release notes: #10317

**Comment by lino-levan** [comment]
Ah, I missed that. I really don't like this as the default. It looks incredibly out of place.

**Comment by osiewicz** [comment]
Yup, I get that; you can bring back the old font with the following setting in your `settings.json`:
`"ui_font_family": "Zed Sans"`

**Comment by lino-levan** [comment]
I've already done so, thanks for documenting this workaround in this thread.

**Comment by JosephTLyons** [comment]
I think I will close this since users can configure for the old font.

**Comment by Tobbe** [comment]
I tried setting the ui font to `Zed Sans`, but get a message saying "Value is not accepted".

![image](https://github.com/user-attachments/assets/4378409b-ac75-4338-8fa7-4c5d2edd1e0c)

Scrolling to the end of the list of valid font we can indeed see that `Zed Sans` is not part of that list. Did the name of "Zed Sans" change?

![image](https://github.com/user-attachments/assets/d5603705-2a4c-4dec-8a3f-91d0ff3935f2)

**Comment by rf43** [comment]
@Tobbe I believe that `Zed Plex Sans` is likely what you're looking for

**Comment by Tobbe** [comment]
@rf43 Thanks! That works 🙂
