### ISSUE TITLE
The current Assistant Panel will only work if you have a paid OpenAI account.

### ISSUE THREAD

**Issue by elamien** [zed-industries/zed#10449]
The current Assistant Panel will only work if you have a paid OpenAI account. 

But I'm one of those users who already has access to Github Copilot Chat (in VSCode), so I'd expect to be able to use that (just like Copilot) in Zed.

_Originally posted by @srid in https://github.com/zed-industries/zed/issues/4673#issuecomment-1908629950_

**Comment by JosephTLyons** [comment]
Hey @elamien - sorry for missing your issue, we don't check the non-zed repos very often. We have an issue requesting support for Copilot Chat here

- https://github.com/zed-industries/zed/issues/4673

I'm going to close this issue out in favor of that one. Please give it an upvote! (👍)
