### ISSUE TITLE
`cargo run --release` stuck on wsl2 and make computer hang

### ISSUE THREAD

**Issue by wangjianpeng** [zed-industries/zed#10458]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

when run `cargo run --release`  on wsl2 , it stuck at the building progress 491/1155 , when I can the build, rebuild it again, it can continue to build ,but still stuck at next progress .

### Environment

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![zed_build_stuck](https://github.com/zed-industries/zed/assets/4220174/259e459c-5125-4348-ae6d-550fd79d8159)

**Comment by maxdeviant** [comment]
@wangjianpeng What are the specs for the hardware you're building on (CPU, RAM, etc.)?

**Comment by wangjianpeng** [comment]
> @wangjianpeng What are the specs for the hardware you're building on (CPU, RAM, etc.)?

I use wsl2 on windows 11 
CPU: 13th Gen Intel i7-13700F (24) @ 2.112GHz
GPU: GTX1660 Ti
RAW: the host is 32G, wsl2 is 8G

**Comment by ChrisJefferson** [comment]
I'm on the same WSL2 ubuntu version as you -- but I do allow my WSL 16GB, and it still seems to eat it all. By default, rust will run as many compilers as you have cores. Just a suggestion, could you run `cargo build --release -j1`

I'm just a drive-by WSL2 users, but this should keep memory usage much lower, and also let you see if some particular package is getting stuck?

**Comment by wangjianpeng** [comment]
> I'm on the same WSL2 ubuntu version as you -- but I do allow my WSL 16GB, and it still seems to eat it all. By default, rust will run as many compilers as you have cores. Just a suggestion, could you run `cargo build --release -j1`
> 
> I'm just a drive-by WSL2 users, but this should keep memory usage much lower, and also let you see if some particular package is getting stuck?
After reboot root system, it builds ok.I only remember I had changed memory , install vulkan , set and unset proxy .  I  feel the zed linux is not stable for wsl2.
