### ISSUE TITLE
Unable to open Zed up on multiple user accounts

### ISSUE THREAD

**Issue by twonil-jordan-stout** [zed-industries/zed#10489]
### Check for existing issues

- [X] Completed

### Describe the feature

I have a "work" account and my normal "personal" account and switch between the two users without fully logging out.

If I open up Zed on one user then switch, I'm unable to open Zed up on the second user.

**Comment by Wronskode** [comment]
Exactly the same problem since Zed 0.130.4, it works after a reboot but uninstall and reinstall don't works

**Comment by JosephTLyons** [comment]
I think this is the same issue as:

- https://github.com/zed-industries/zed/issues/4607

If I'm wrong, we can reopen this.
