### ISSUE TITLE
Rust-Analyzer does not support "OverrideCommand"

### ISSUE THREAD

**Issue by QuentinPerez** [zed-industries/zed#10498]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

👋 

Not sure if it's a feature request or a bug, since RA/vscode supports it.
Given the following `.zed/settings.json`, it seems that we can not override `check` command.
Here is an example.

```
{
    "lsp": {
        "rust-analyzer": {
            "initialization_options": {
                "check": {
                    "overrideCommand": [
                        "sh",
                        "-c",
                        "cargo clippy --message-format=json --manifest-path ./a/Cargo.toml;  cargo clippy --message-format=json --manifest-path ./b/Cargo.toml"
                    ]
                }
            }
        }
    }
}
```

### Environment

Zed: v0.131.4 (Zed Preview)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by martinschaer** [comment]
It isn't working for me either. These are my settings:

```json
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "check": {
          "overrideCommand": [
            "cargo",
            "check",
            "--target=arm-unknown-linux-musleabihf" // "--target=x86_64-apple-darwin"
          ]
        }
      }
    }
  }
}
```

In the terminal running `cargo check --target=arm-unknown-linux-musleabihf` works. Same with `cargo check --target=x86_64-apple-darwin`
