### ISSUE TITLE
Custom snippets

### ISSUE THREAD

**Issue by danielzsh** [zed-industries/zed#10499]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has a feature that allows you to write your own snippets:
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

It would be nice if Zed supported something similar. A major improvement from VSCode would be better support for multiline snippets. Currently, they have to be written in array form, like so:
https://stackoverflow.com/questions/41856706/whats-the-best-way-to-write-multi-line-code-snippets-in-vs-code

However, I think it would be nice to allow loading snippets from individual files (maybe under a `.zed/snippets` directory?), especially if it's a longer snippet (my personal use is a template for competitive programming that includes several necessary headers, macros, and globals).

**Comment by weartist** [comment]
I rely heavily on this feature, and it would be great if there were

**Comment by OSuwaidi** [comment]
Snippets or Live Templates are extremely powerful, quite an essential feature!

**Comment by 0x2CA** [comment]
duplicate  https://github.com/zed-industries/zed/issues/10499

**Comment by AllTheUserNamesAreGone** [comment]
I see this closed but you don't say if this will be something you will add in the future or not something you will ever add? 

Is this something that could be added as an extension? 

Thanks

**Comment by Moshyfawn** [comment]
> I see this is closed but you don't say if snippets will be something you will add in the future or not something you will ever add?

This issue has been closed as a duplicate of the issue linked above, which is still relevant. Be sure to follow that thread for more information on the feature.

**Comment by AllTheUserNamesAreGone** [comment]
I missed the duplicate, thanks.
