### ISSUE TITLE
Terminal + Tmux + Ctrl-Space-Prefix not working

### ISSUE THREAD

**Issue by Rocco-Gossmann** [zed-industries/zed#10502]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi, I'm new to Zed and wanted to give it a try.  Coming from NeoVim, My workflow usually involves running various scripts and TUI tools via TMUX.

For convinience I changed TMUX's default Prefix to "Ctrl+Space"  (default would be "Ctrl+B").

However, when running TMUX in Zed's Terminal, CTRL-Space does nothing. (Ctrl+B works though).

So my guess is, that something is eating up the Ctrl-Space input. The only binding to that (According to my config) is the default `editor::ShowCompletions` in the `Editor` Context.
So when I'm in the `Terminal` Context, it should be ignored.

**How to reproduce**
- Install `tmux` 
- change the default Prefix by adding the following to your `~/.tmux.conf`:
```text
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
```
- Open Zed
- Open Zed's Terminal
- Run the command in that terminal.
```bash
tmux
```
- Try pressing `ctrl-space ?` (By default it should list all of TMUX's Keybindings)

### Environment

Zed: v0.130.6 (Zed)
OS: macOS 13.6.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/127580387/76bfc06f-2957-4cb6-b3df-ef6a1c3d306d

**Comment by CharlesChen0823** [comment]
might you have key-bindings in settings which using `ctrl-space`?

**Comment by Rocco-Gossmann** [comment]
No, not at all. These are all my mappings so far.
The rest is default.

```json
[
  {
    "context": "!Terminal && vim_mode != insert",
    "bindings": {
      "cmd-j": "workspace::ToggleBottomDock",
      "cmd-h": "workspace::ToggleLeftDock",
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"],
      "ctrl-shift-i": "pane::SplitRight",
      "ctrl-_": "pane::SplitDown",
      "ctrl-shift-h": ["workspace::SwapPaneInDirection", "Left"],
      "ctrl-shift-j": ["workspace::SwapPaneInDirection", "Down"],
      "ctrl-shift-k": ["workspace::SwapPaneInDirection", "Up"],
      "ctrl-shift-l": ["workspace::SwapPaneInDirection", "Right"],
      "space f f": "file_finder::Toggle",
      "space tab": "workspace::CloseAllDocks",
      "space q": "editor::GoToDiagnostic"
    }
  },
  {
    "context": "Editor && vim_mode == normal && !VimWaiting",
    "bindings": {
      "ctrl-n": "project_panel::ToggleFocus"
    }
  }
]
```

I've noticed something else.

When typing a space in the Terminal, the Space character only shows up with a delay or once I type something else. Maybe that has something to do with it.

https://github.com/zed-industries/zed/assets/127580387/7ffc330d-bcfb-4d1d-81e9-09b694acd8e5

**Comment by CharlesChen0823** [comment]
might be that `https://github.com/zed-industries/zed/blob/e34c443331e6498dce80a6ec2d60ade1985e7b62/assets/keymaps/default-macos.json#L374`

**Comment by Rocco-Gossmann** [comment]
> might be [that](https://github.com/zed-industries/zed/blob/e34c443331e6498dce80a6ec2d60ade1985e7b62/assets/keymaps/default-macos.json#L374)

Possible. But that should be in the "Editor" Context, not the "Terminal" Context.
I'd love to test if that is the problem, but I don't know how to disable the default mappings.

**Comment by CharlesChen0823** [comment]
try set the "base_keymap" setting to None.

**Comment by Rocco-Gossmann** [comment]
> try set the `"base_keymap"` setting to `None`.

Thanks, I just tried it, but it did not help. 

Disabling all default mappings somehow fixed the delay of the space character in the terminal, but nothing else. Ctrl+Space is still not registering.

I even tried disabling all mappings that user „space“ in my „keymap.json“ too.
No changes.

**Comment by cemoktra** [comment]
In general there should be an option to allow the terminal to capture key bindings first, i configured `nano` as editor for git and i can't use `Ctrl + O` to save changes, cause it tries to open a file.

**Comment by Rocco-Gossmann** [comment]
@cemoktra 
> In general there should be an option to allow the terminal to capture key bindings first, i configured `nano` as editor for git and i can't use `Ctrl + O` to save changes, cause it tries to open a file.

you can define what keys get captured where by defining a `context` property at the same level as the `bindings` property in your keymap.json.
Unfortunatly there is no good documentation what can go into a `context`.
For example `!Terminal` does NOT work but `!Editor` somehow does?!

**Comment by mirageN1349** [comment]
The same problem + 1

**Comment by MaxThom** [comment]
I am also facing the same issue! I got tmux on ctrl+space and the keys are not being registered.
