### ISSUE TITLE
Install option disabled entirely for certain stock extensions (i.e. OCAML) 

### ISSUE THREAD

**Issue by nicosql** [zed-industries/zed#10509]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just downloaded/installed Zed today and as shown in the image certain extensions have the install option disabled (for no apparent reason).  Extensions with the install option enabled install without any issue.

Am I missing something?  

![image](https://github.com/zed-industries/zed/assets/57677891/175f64be-07e8-47c5-a759-a066ba5f4f05)
### Environment

Zed: v0.130.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Y4hL** [comment]
Clicking on the the three dots ... will let you install an older version. It seems the newest versions aren't compatible with your Zed installation.

**Comment by Moshyfawn** [comment]
It is the extension compatibility that determines whether you can install the latest version of the extension on your Zed instance.

**Comment by Moshyfawn** [comment]
The PR to help explain and make this use case more discoverable has been merged, so I'm going to close this thread now. Let me know if it needs to be reopened.

**Comment by nicosql** [comment]
i see, thanks guys.
