### ISSUE TITLE
Block comment should be added

### ISSUE THREAD

**Issue by ahmedmelihozdemir** [zed-industries/zed#10507]
### Check for existing issues

- [ ] Completed

### Describe the feature

When I want to make multiple selections and put them in the comment line, I need a collective comment rather than a line by line comment.
For example: {
*/
asdsa
asdasd
asdasd
*/
}
or other block comment ex.

**Comment by JosephTLyons** [comment]
Ope, just found an earlier request for this:

- https://github.com/zed-industries/zed/issues/4751

Please upvote the original with a 👍. If there is additional context in this request, add it as a comment on the original.

**Comment by p-iosifidis** [comment]
Since this is coming up first on google and people tend to click on  the first result, it has normal functionality as other same products. Ctrl + /, CMD + / is what you're looking for.
