### ISSUE TITLE
get environment variables , path is wrong

### ISSUE THREAD

**Issue by GengCen-Qin** [zed-industries/zed#10518]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

when I want to use solargraph to write ruby , I find log show : failed to start language server "solargraph": No such file or directory (os error 2) , 
![image](https://github.com/zed-industries/zed/assets/98941324/15ece075-5590-4586-b5cf-f42a62e9dad3)

but in terminal, I can find and use it 
![image](https://github.com/zed-industries/zed/assets/98941324/8604881c-b654-411d-9534-9410b20f0015)

so I think maybe some wrong happen when read environment variables，so I check log：
![image](https://github.com/zed-industries/zed/assets/98941324/1401ac3c-de98-4bca-97a3-6cadaa1673df)
there just has  path:/usr/bin:/bin:/usr/sbin:/sbin

but in my terminal :
![image](https://github.com/zed-industries/zed/assets/98941324/377c55b6-f7c5-44b7-8426-d4c415fc8585)

after that, I run rust code : `println!("{}",env::var("PATH").unwrap_or_default());` 
![image](https://github.com/zed-industries/zed/assets/98941324/11970eb1-175d-4ab3-8982-cf641b17e069)

I don't kown how to resolve this 

### Environment

Zed 0.130.6
MacBook Pro (Retina, 13-inch, Mid 2014)，version: 11.7.10

**Comment by GengCen-Qin** [comment]
I find when I open Zed in terminal, it is ok 
```sh
zed project
```
---
when I open Zed in folder, it is not ok
![image](https://github.com/zed-industries/zed/assets/98941324/bd2c9af1-cce8-4bff-8d6b-5418d08516ff)

**Comment by mrnugget** [comment]
Which macOS version do you have?

**Comment by mrnugget** [comment]
I'm 99% sure that this is fixed in Zed 0.131.x with this: https://github.com/zed-industries/zed/commit/b05aa381aa0f83c7f4809ca67b44568248626e55

You can try that version: https://zed.dev/releases/preview

**Comment by oz** [comment]
Ugh... lots of issues related to starting or finding Ruby's LSPs. They may be related to the many installation methods for Ruby, as devs often use "ruby version managers" which mangle the `$PATH`, sometimes when changing directories, etc. 😵

I usually install solargraph with `gem install solargraph` into a specific directory (using [chruby](https://github.com/postmodern/chruby)). With that setup, Zed finds `solargraph` in my `$PATH` *only if* I start zed from the CLI, but not otherwise. 😕

As a temporary workaround, I symlinked solargraph to a local path that does not depend on chruby, or any other ruby version manager. For example:

```
ln -s ~/.gem/ruby/3.3.0/bin/solargraph ~/.local/bin/solargraph
```

Sure that's a kludge, but for me that was enough to help Zed to find solargraph consistently. HTH.

**Comment by GengCen-Qin** [comment]
> I'm 99% sure that this is fixed in Zed 0.131.x with this: [b05aa38](https://github.com/zed-industries/zed/commit/b05aa381aa0f83c7f4809ca67b44568248626e55)
> 
> You can try that version: https://zed.dev/releases/preview

Thanks you, My Mac version is 11.7.10,  version is too low

**Comment by oz** [comment]
@mrnugget I tested with **0.132.3** (MacOS/Aarch), but there's still trouble with solargraph. Here's the app log.

```
2024-04-29T09:34:35-06:00 [INFO] Opening main db
2024-04-29T09:34:35-06:00 [INFO] starting language server "solargraph", path: "/Users/oz/etc/", id: 1
2024-04-29T09:34:35-06:00 [INFO] fetching latest version of language server "solargraph"
2024-04-29T09:34:35-06:00 [INFO] downloading language server "solargraph"
2024-04-29T09:34:35-06:00 [INFO] failed to fetch newest version of language server LanguageServerName("solargraph"). falling back to using "solargraph"
2024-04-29T09:34:35-06:00 [INFO] starting language server. binary path: "solargraph", working directory: "/Users/oz/etc/", args: ["stdio"]
2024-04-29T09:34:35-06:00 [ERROR] failed to start language server "solargraph": No such file or directory (os error 2)
2024-04-29T09:34:35-06:00 [ERROR] server stderr: Some("")
2024-04-29T09:34:35-06:00 [INFO] retrying installation of language server "solargraph" in 1s
2024-04-29T09:34:36-06:00 [INFO] Validation check requested for "solargraph" but it cannot be reinstalled
```

HTH.

**Comment by gottlike** [comment]
> Ugh... lots of issues related to starting or finding Ruby's LSPs. They may be related to the many installation methods for Ruby, as devs often use "ruby version managers" which mangle the `$PATH`, sometimes when changing directories, etc. 😵
> 
> I usually install solargraph with `gem install solargraph` into a specific directory (using [chruby](https://github.com/postmodern/chruby)). With that setup, Zed finds `solargraph` in my `$PATH` _only if_ I start zed from the CLI, but not otherwise. 😕
> 
> As a temporary workaround, I symlinked solargraph to a local path that does not depend on chruby, or any other ruby version manager. For example:
> 
> ```
> ln -s ~/.gem/ruby/3.3.0/bin/solargraph ~/.local/bin/solargraph
> ```
> 
> Sure that's a kludge, but for me that was enough to help Zed to find solargraph consistently. HTH.

Jesus.. after wasting a lot of time, I just used your symlink workaround and finally I get "ruby-lsp" etc. working. Thank you!

**Comment by mrnugget** [comment]
FWIW there have been a lot of changes to environment variable handling recently. If you haven't, try the latest Preview release.

**Comment by willcosgrove** [comment]
I can confirm that the latest preview has fixed all of my environment variable issues I was having. Thanks for all the hard work on that problem @mrnugget!

**Comment by mrnugget** [comment]
Great to hear that @willcosgrove!

**Comment by mrnugget** [comment]
Good stuff! I'm closing this issue and we can reopen it if something pops up again.

@gottlike for that, I think you should open another issue. Glitchy Scrollbars is not my department (just kidding! but it should be a separate issue)
