### ISSUE TITLE
Hide the Terminal button.

### ISSUE THREAD

**Issue by joshdales** [zed-industries/zed#10513]
### Check for existing issues

- [X] Completed

### Describe the feature

As someone that always uses an separate terminal I'd like to be able to disable/hide the integrated terminal button.

**Comment by mrnugget** [comment]
That should be relatively straightforward. We'd need to copy the `button: bool` setting from these:

https://github.com/zed-industries/zed/blob/f4f9ca0b1e32f085a8f0ec631b635caf863a9ba1/crates/collab_ui/src/panel_settings.rs#L10-L25

Add them here: https://github.com/zed-industries/zed/blob/f4f9ca0b1e32f085a8f0ec631b635caf863a9ba1/crates/terminal/src/terminal_settings.rs#L27

And then use them.

**Comment by weartist** [comment]
I'll submit a PR to fix the issue

**Comment by Moshyfawn** [comment]
Can this be considered complete?

**Comment by JosephTLyons** [comment]
I think so, let's close it out!
