### ISSUE TITLE
Sign in into Zed is glitchy

### ISSUE THREAD

**Issue by brayo-pip** [zed-industries/zed#10520]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The sign in to zed on the top right corner always displays when I relaunch the app. When I click it updates and displays my profile pic, showing that I am logged in. This should happen automatically. The sign in state is persisted but not updated on launch.

## Report details
- **Date generated:**                              2024-04-14 12:17:35

## Hardware Information:
- **Hardware Model:**                        HP ProBook 450 G6
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i5-8265U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (WHL GT2)
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            R71 Ver. 01.19.00
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.26-1-MANJARO

**Comment by apricotbucket28** [comment]
I had the same issue and figured out that Zed actually logs in automatically when not running from the terminal, and that seems to be intended.
Here's the code:
https://github.com/zed-industries/zed/blob/575eb792fb2f1c71731a259ec09e7afb58c70528/crates/zed/src/main.rs#L526-L535

**Comment by brayo-pip** [comment]
Launching it by directly works. Thanks.
