### ISSUE TITLE
Included header not resolved

### ISSUE THREAD

**Issue by lszsrd** [zed-industries/zed#10528]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On C projects, I have my own library and some header file of the current project I am working on. When including those header files, Zed highlights them with a "clang: 'file_name.h' not found" popup. Header files not being found also highlight all of my functions in red saying they do not exist because it does not find its prototypes.

### Environment

Zed: v0.130.6 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

- Create a header file outside of the current directory
- Include this header file and you should have this bug

![Capture d’écran 2024-04-14 à 18 28 04](https://github.com/zed-industries/zed/assets/146016333/a7b6ce02-4ffc-4604-8c01-9bf659789469)

**Comment by leftbones** [comment]
Also having this issue in a C++ project. I can still build and run normally, even though Zed claims my header files don't exist.

**Comment by Christofon** [comment]
I am having the same problem

**Comment by jryxxx** [comment]
Same problem, i use CMake to build C++ project, how can clang find my dependencies？

**Comment by leftbones** [comment]
I figured it out. Adding `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` towards the top of my CMakeLists.txt, building again, and reloading Zed made all of the errors go away!

After searching for people having this issue in other editors, I found that clang (and clangd) need the `compile_commands.json` file to work properly.

**Comment by mayakraft** [comment]
Not sure if this is related, but I'm having an issue with `compile_commands.json`
I build mine with bear (the only result which works). But, Zed keeps replacing the file with its own version (maybe built using clang?), and Zed's version doesn't work.
I keep pasting the intended contents into `compile_commands.json` but Zed keeps overwriting it.
Is there a way to ask Zed to stop?

**Comment by williamd1k0** [comment]
I was having a similar issue.
I have tried to include directories in a `.clangd` file without success.
Then I tried including directories in a `compile_flags.txt` (similar to @leftbones approach) and it worked fine.

Docs for reference:
- https://clangd.llvm.org/design/compile-commands#where-do-compile-commands-come-from
- https://clang.llvm.org/docs/JSONCompilationDatabase.html#alternatives

**Comment by csalmeida** [comment]
I had the same issue but `.clangd` and `compile_commands.json` did not work for me.

In my case I had a library (in this case SDL) in the `include` directory and Zed would display an `clang: 'SDL2/SDL.h' file not found` error when including `#include <SDL2/SDL.h>` even though the program compiles correctly.

Following [Zed's documentation for configuring it for `C++`](https://zed.dev/docs/languages/cpp), I managed to fix this by adding a `.zed/settings.json` file:

```json
{
  "lsp": {
    "clangd": {
      "binary": {
        "arguments": [
          "--include-directory=${workspaceFolder}/include",
          "--include-directory=${workspaceFolder}/include/SDL2"
        ]
      }
    }
  }
}
```

Looking at `compile_flags.txt` didn't work either for me but it could be I configured it wrong, here's what I tried:

```
-I
${workspaceFolder}/include
-I
${workspaceFolder}/include/SDL2
```

**Comment by Maikel1963** [comment]
Same issue for me, but it seems to be solved by adding a file named `.clangd` to the project folder containing:
```
# yaml-language-server: $schema=https://json.schemastore.org/clangd.json
CompileFlags:
  Add: [
      -xc
      -I"d:\Programs\msys64\mingw32\include\",
    ]
```
where `d:\Programs\msys64\mingw32\include\` is my path to the header files.

**Comment by brianpmaher** [comment]
Same issue for me

`Zed 0.216.1`

<img width="443" height="82" alt="Image" src="https://github.com/user-attachments/assets/ce422fc1-a0df-44a6-8c8c-f6475a9836fe" />

`CMakeLists.txt`
```cmake
# ...
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
# ...
```

`build.bat`
```bat
mkdir build
pushd build
cmake -G "Ninja" ..
cmake --build . --parallel %NUMBER_OF_PROCESSORS%
popd
```

`.clangd`
```
CompileFlags:
  CompilationDatabase: "./build"
```

Can we reopen this issue?
