### ISSUE TITLE
as of regex 1.10, `\<` and `\>` are supported as left and right word boundary assertions

### ISSUE THREAD

**Issue by BurntSushi** [zed-industries/zed#10539]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that in the docs outlining the [differences from vim regex](https://zed.dev/docs/vim#regex-differences) that it says:

> Vim uses `\<` and `\>` to represent word boundaries, in Zed these are both handled by `\b`

But as of `regex 1.10.0`, [the `\<` and `\>` assertions are now supported](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#1100-2023-10-09). Since Zed seems [to use `regex 1.10.3`](https://github.com/zed-industries/zed/blob/97c5cffbe3264c7a48d1204bcc71a48630eebd48/Cargo.lock#L7787-L7788), I think this means that Zed supports `\<` and `\>` (in addition to `\b`).

### Environment

Any

**Comment by ConradIrwin** [comment]
Thanks! Updated
