### ISSUE TITLE
add a web view into Zed for website previews

### ISSUE THREAD

**Issue by isaacmclellan** [zed-industries/zed#10533]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if there was a web view extension/built in feature for previewing websites inside of Zed without having to go into a web browser while building web apps in Zed. This could be implemented by using Tauri's Wry crate which talks to the native webview on the OS of which it's running. This would also help other GPUI apps cause they could embed webviews

**Comment by huacnlee** [comment]
If there have a WebKit component in Zed, then some case like Markdown, AsciiDoc, HTML, CSV Preview, Testing Results ..., we write easy to write and control the styling in HTML, that would easier to do than write in Rust.

**Comment by jansol** [comment]
If there was a webview component that would encourage people to write all functionality in HTML+JS, at which point you really should unironically just use vscode for better performance as that *is* a webview without all the resource use that Zed incurs from its custom UI.

**Comment by Moshyfawn** [comment]
Related:
- #5310

**Comment by huacnlee** [comment]
https://github.com/tauri-apps/wry

**Comment by isaacmclellan** [comment]
> How about wry?
> 
> https://github.com/tauri-apps/wry

That's what I said the webview would be provided by

**Comment by muvaf** [comment]
> If there was a webview component that would encourage people to write all functionality in HTML+JS, at which point you should unironically use vscode for better performance as that is a webview without all the resource use that Zed incurs from its custom UI.

@jansol Agree this would be the case if extensions were allowed to be written in HTML+JS but this could very well be a built-in feature similar to how JetBrains IDEs render markdown built-in.
