### ISSUE TITLE
TailwindCSS additional class details (style)

### ISSUE THREAD

**Issue by henrikruscon** [zed-industries/zed#10532]
### Check for existing issues

- [X] Completed

### Describe the feature

Would be very useful to have more details about the classes being suggested by autocomplete menu. It's very useful to be able to see at a glance what the class actually applies. For example compare the Zed result vs Nova below. Right now this space is only used for colors in Zed, why not everything else as well?

### If applicable, add mockups / screenshots to help present your vision of the feature

![CleanShot 2024-04-14 at 22 13 42@2x](https://github.com/zed-industries/zed/assets/1430576/3e6f3305-88f0-4a11-af51-abafced83699)
![CleanShot 2024-04-14 at 22 13 31@2x](https://github.com/zed-industries/zed/assets/1430576/e3afb796-27b8-4a24-9323-de7ac6c1649c)

**Comment by Ar4ka** [comment]
For a time it did work in hey some months ago. But now it's broken. Might look into the problem.

**Comment by henrikruscon** [comment]
> For a time it did work in hey some months ago. But now it's broken. Might look into the problem.
> 
> Edit: current main has this issue in the debug build when you have the autocomplete for tailwind classes <img alt="image" width="1014" src="https://private-user-images.githubusercontent.com/49145060/322315810-ce0bf13a-7fa5-46c9-a182-713fc0f55fda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzAyNDgsIm5iZiI6MTcxMzE2OTk0OCwicGF0aCI6Ii80OTE0NTA2MC8zMjIzMTU4MTAtY2UwYmYxM2EtN2ZhNS00NmM5LWExODItNzEzZmMwZjU1ZmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA4MzIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYWYyNzQ1MWU5NTM2NWZmYzI0Nzc1MDRkNTIyZmVlNTgwMjZiMWY2ZmIwYTMxNTY2YmVjOWRmYmRlM2I3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6DtTlb0K281MQkPWjjzVRBXbscwCAle8nmRKVjgrFTI">

Are you sure? Didn't seem to work on the screen you took for that PR. Where have you seen it work? I'm new to Zed but thinking of looking into it as well.

**Comment by henrikruscon** [comment]
From what I can see in the RPC logs, it appears there's a variable namned `documentation` and it's used to populate that part that is missing, it seems to be lacking on most of the classes in the logs, except colors. And there it works.

![CleanShot 2024-04-15 at 11 40 24@2x](https://github.com/zed-industries/zed/assets/1430576/465e941c-295b-4ef9-b0a5-b7165cb824ca)

**Comment by jasongitmail** [comment]
It'd also be useful to see color swatches for the tailwind color classes, like in Cursor/VSCode:

### Zed
<img width="398" alt="zed" src="https://github.com/zed-industries/zed/assets/50032291/4659d3fa-4ad1-4ae1-a695-99d54b64c399">

### Cursor
<img width="249" alt="vscode" src="https://github.com/zed-industries/zed/assets/50032291/64b25582-883d-4c26-bd73-debc658119cc">

**Comment by mrnugget** [comment]
So to be clear: the problem is that we only show the documentation for colors, but not for the other classes?

I think rendering the colors should be a separate issue.

**Comment by palmamartin** [comment]
I think the main issue is that the documentation of a tailwind class is not displayed in Zed in the autocomplete panel like in vscode. 

Zed:
<img width="260" alt="Screenshot 2024-05-15 at 10 44 54" src="https://github.com/zed-industries/zed/assets/381/0947c447-11a8-4e84-8679-39cf30c1d510">

vscode:
<img width="478" alt="Screenshot 2024-05-15 at 10 45 28" src="https://github.com/zed-industries/zed/assets/381/9e7923f8-4bbb-4687-a808-7c2c599b3771">
