### ISSUE TITLE
Add ability to move search to left bar

### ISSUE THREAD

**Issue by Rafi993** [zed-industries/zed#10542]
### Check for existing issues

- [X] Completed

### Describe the feature

* Add ability to move search to left bar similar to VSCode. This helps to quickly search code when you are still viewing the rest of the code
* This could be a setting that can be turned on for VSCode users who want this to feel at home

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="553" alt="Screenshot 2024-04-15 at 9 42 30 AM" src="https://github.com/zed-industries/zed/assets/8092120/8fd8f583-ed74-43b4-b86b-070c6e6bb17c">

**Comment by baldwindavid** [comment]
I've used VSCode search quite a lot so I get it that it can be tough doing things a different way. However, one of the most powerful concepts in Zed is the "multi-buffer" and that is what project search leverages to display results. I don't know what all search-related features might be planned or will evolve (e.g. find/replace live diff), but what is being requested here seems a likely departure from the vision or, if nothing else, implies major UI/UX changes/additions.

> helps to quickly search code when you are still viewing the rest of the code

Worth mentioning that I use this flow many times per day with a project-wide search (`workspace: new search`) and then navigating through the multi-buffer results like any regular buffer. Sometimes, I make changes directly in the multi-buffer and then save, which saves all the changes in the multi-buffer in one go. Other times, I want to see the result in context so will open to the side (`editor: open excerpts split`) and make changes. Personally, I find this to be a quite natural experience, but ymmv after giving it a good run.

**Comment by Rafi993** [comment]
> I've used VSCode search quite a lot so I get it that it can be tough doing things a different way. However, one of the most powerful concepts in Zed is the "multi-buffer" and that is what project search leverages to display results. I don't know what all search-related features might be planned or will evolve (e.g. find/replace live diff), but what is being requested here seems a likely departure from the vision or, if nothing else, implies major UI/UX changes/additions.
> 
> > helps to quickly search code when you are still viewing the rest of the code
> 
> Worth mentioning that I use this flow many times per day with a project-wide search (`workspace: new search`) and then navigating through the multi-buffer results like any regular buffer. Sometimes, I make changes directly in the multi-buffer and then save, which saves all the changes in the multi-buffer in one go. Other times, I want to see the result in context so will open to the side (`editor: open excerpts split`) and make changes. Personally, I find this to be a quite natural experience, but ymmv after giving it a good run.

The problem with `editor: open excerpts split` and creating a new search workspace is. If you navigate to a specific instance  highlighted item it will it navigate away from the search.  Again I'm not saying that existing search should be replaced. But instead add a setting so that search can be moved to left nav for those who wants to (turned off by default) since it will improve adoption from VSCode users.

**Comment by baldwindavid** [comment]
> If you navigate to a specific instance highlighted item it will it navigate away from the search.

Yep, I actually want the ability to stay in the search area too _sometimes_. One feature that will ship in the Preview Release tomorrow is [Preview Tabs](https://github.com/zed-industries/zed/pull/9125). I'm thinking that perhaps `editor: open excerpts split` could change to "not" navigate to the file (similar to how it works for the project panel) and then maybe an `editor: open permanent excerpts split` command could be added. Either that or maybe `editor: open permanent split` takes an argument for keymaps whether to open permanent or not. Anyway, maybe something to consider. cc @bennetbo @ConradIrwin

**Comment by GOWxx** [comment]
> Worth mentioning that I use this flow many times per day with a project-wide search (`workspace: new search`) and then navigating through the multi-buffer results like any regular buffer. Sometimes, I make changes directly in the multi-buffer and then save, which saves all the changes in the multi-buffer in one go. Other times, I want to see the result in context so will open to the side (`editor: open excerpts split`) and make changes. Personally, I find this to be a quite natural experience, but ymmv after giving it a good run.

From your reply, I can see that you are an experienced user of multi buffers. If it's convenient for you, I'd like to ask you a question:
In VSCode, you can filter out the file directory structure related to the search results in the sidebar based on the search results, so that you can get the directory structure in a concentrated manner. Is there any way I can achieve this in Zed?

Thank you for your contribution and the generous information you have contributed. Thank you!

**Comment by xzbdmw** [comment]
Will zed consider a live_grep similar to fzf or vscode's new added quick search? If I just want a specific location that way is much efficient than glance through multi-buffer results

**Comment by GOWxx** [comment]
> I think you can filter here

Thank you for your reply. I understand that I can search and filter in the buffer area, but my focus is on the sidebar, which displays the project's directory file structure. I'm looking for a way to filter the directory file structure based on the files found in the search results.
A similar example I expect is the 'Source Control' panel in VSCode, which filters out the directory file structure based on the changes made.
By the way, the current git diff in Zed cannot filter out and display only the modified directory file structure; it uses color markings instead.

**Comment by GOWxx** [comment]
> In VSCode, I can filter out the file directory structure related to the search results in the sidebar based on the search results, so that I can get the directory structure in a concentrated manner. 

now we have outline panel. [Introduce an outline panel #12637](https://github.com/zed-industries/zed/pull/12637)

**Comment by xzbdmw** [comment]
> > In VSCode, I can filter out the file directory structure related to the search results in the sidebar based on the search results, so that I can get the directory structure in a concentrated manner.
> 
> now we have outline panel. [Introduce an outline panel #12637](https://github.com/zed-industries/zed/pull/12637)

He is a machine:-

**Comment by SomeoneToIgnore** [comment]
I believe this can be closed after https://github.com/zed-industries/zed/pull/16589 and follow-ups with perf improvements had landed.

Now, we have a way to display search results in the outline panel and pin those, so the results will stay even another buffer is focused, as long as the pinned one is in the pane.
