### ISSUE TITLE
"Open to the side" functionality

### ISSUE THREAD

**Issue by vdabar** [zed-industries/zed#10549]
### Check for existing issues

- [X] Completed

### Describe the feature

Feature Description:
The "Open to the Side" feature would enable users to quickly and easily view and edit multiple files simultaneously without losing context. By simply right-clicking on a file name or using a shortcut key, the file would open in a new pane to the right or left of the current file. This functionality is highly appreciated in environments like VS Code, where it proves extremely useful for comparing files or working on different parts of a project side by side.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="307" alt="image" src="https://github.com/zed-industries/zed/assets/17545315/2a540ff5-3c80-40df-aedf-ab4d9258e5c9">

**Comment by JosephTLyons** [comment]
Hey @vdabar, if you hold down `cmd` when you click on a file in the project panel, or hold down `cmd` when you select an entry in the file finder, it should automatically create a split. Does this work for you?

**Comment by vdabar** [comment]
@JosephTLyons haha, that works! thanks!
