### ISSUE TITLE
Inline git blame author (you logic)

### ISSUE THREAD

**Issue by henrikruscon** [zed-industries/zed#10557]
### Check for existing issues

- [X] Completed

### Describe the feature

Would be neat if the newly merged inline git blame could show "You" instead of your username if it is in fact you that is to blame. Just easier/faster to recognise at glance.

### If applicable, add mockups / screenshots to help present your vision of the feature

![CleanShot 2024-04-15 at 16 00 07@2x](https://github.com/zed-industries/zed/assets/1430576/ab15f238-eec9-4e9d-8385-6d420c3b6279)

**Comment by social-anthrax** [comment]
I'd personally be hesitant to do this, it's just a matter of time before someone would change their username to "you" to try and hide a commit. If this was togglable or had some visual difference from other usernames I'd be all for it.

**Comment by jansol** [comment]
I think there are some plans to add avatars, so one would have to change both their committer name and github avatar to impersonate someone.

But there definitely could be some additional highlight, maybe with the background color?

**Comment by henrikruscon** [comment]
Not really sure what's to gain from hiding your commit from inline code, you can simply hover the git blame and you will get all the details if it's really important in a very particular case. This is just a quality of life improvement. This is a none issue.

**Comment by Calinou** [comment]
One downside of showing "You" is that screenshots become less relevant, so maybe it should just be highlighted in a different color but without changing the displayed name.

**Comment by HarshNarayanJha** [comment]
What about showing You in brackets? Like `Git Name (You)`

**Comment by social-anthrax** [comment]
I honestly think that this change would be more work than it's worth, as I hope most users know what name they're committing with. If this feature were to go ahead then the proposal by @HarshNarayanJha is something that I personally like.

**Comment by HarshNarayanJha** [comment]
I could fake this up

**Comment by HarshNarayanJha** [comment]
Okay so what about adding a config option to show
1. Author
2. Author with You
3. just You
