### ISSUE TITLE
Doesn't start at all

### ISSUE THREAD

**Issue by vruzin** [zed-industries/zed#10553]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Download latest
2. Copy to App
3. Run... but nothing starts. no windows, no messages... nothing. I tried to open a text file in Finder using Zed, but that didn’t work either.

### Environment

Macbook m1, 16Ram, 2Tb

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

~/Library/Logs/Zed - empty

**Comment by jansol** [comment]
Just to make sure - you didn't accidentally grab the x86_64 build, right? Since your mac is aarch64.

**Comment by osiewicz** [comment]
Also, can you try to run the binary from command line?
Something like:
`/Applications/Zed.app/Contents/MacOS/zed`
or
`/Applications/Zed\ Preview.app/Contents/MacOS/zed`
(depending on whether you're on Stable on Preview)
Do you see any logs in the terminal?

**Comment by vruzin** [comment]
The problem was different!
~/.cache had only view permissions. Changed permissions and it worked

**Comment by bennetbo** [comment]
Should be the same issue as #9036, so I think we can close this?
#10326 will show a window with the error message, which should make the error seen here less confusing (but that has not landed on stable yet).

**Comment by JosephTLyons** [comment]
Thanks @bennetbo, I think we can close this in favor of #9036.
