### ISSUE TITLE
Sidebar file browser indentation is too wide

### ISSUE THREAD

**Issue by bryanbuchanan** [zed-industries/zed#10568]
### Check for existing issues

- [X] Completed

### Describe the feature

The sidebar file browser uses extremely wide indentation to indicate nested files/folders. Here's a screenshot of Zed on the left + VSCode on the right:

![Screenshot 2024-04-15 at 9 59 42 AM](https://github.com/zed-industries/zed/assets/1747699/45d19f22-359b-420a-8ce3-39f2db04b3c8)

Cutting the space to half or even a third would still very easily communicate indentation, while allowing more usable space for file names before they're truncated.

Also, it may be unnecessary to indent every root-level item under a project's parent directory. Doing so doesn't communicate any useful information, though it does rob usable real estate from the UI.

![Screenshot 2024-04-15 at 10 11 57 AM](https://github.com/zed-industries/zed/assets/1747699/a77241ed-ddfe-47cf-84cc-8c60b4859448)

**Comment by bryanbuchanan** [comment]
🤦‍♂️ Sorry for the trouble. So much better, thank you!

**Comment by JosephTLyons** [comment]
No worries! Glad we have something in place the works for you.
