### ISSUE TITLE
Paid personal version without collaboration features?

### ISSUE THREAD

**Issue by josb** [zed-industries/zed#10592]
### Check for existing issues

- [X] Completed

### Describe the feature

Probably out of scope, but I would be interested in a paid personal version without any of the collaboration features.

**Comment by znycheporuk** [comment]
Why not just remove button and shortcut to open collaboration pane in settings?
It's already possible

**Comment by josb** [comment]
That would be an option, but it would still cause code to be included I'd never use, and possibly cause issues because of its inclusion. But as long as it was just dead weight on disk and didn't affect runtime, it'd be OK I suppose.
In JetBrains products, this type of functionality is implemented as plugins so there one can opt to simply not install them.
I am just looking for a capable solo developer setup here.

**Comment by ArikRahman** [comment]
If it's stripped down it should not have to be paywalled... aside from that why not just use Lapce at that point?

**Comment by notpeter** [comment]
At this time we have no plans of shipping alternate feature-specific builds.

At any given time there are 18 official "latest" binaries: MacOS/Linux for x86_x64/aarch64 in GUI/remote + MacOS Universal for each of two release channels (Stable/Preview). Which is **plenty** for me.  This does not include anyone running the non-latest release, using an unofficial open source build (Arch, etc), or building themselves (Windows, Nix, etc). 

Thanks for reporting.
