### ISSUE TITLE
lsp::Response does not comply with LSP spec (error field must be exclusive with result)

### ISSUE THREAD

**Issue by gdamore** [zed-industries/zed#10595]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

it looks like the LSP sends non-standard-conforming data
{"jsonrpc":"2.0","id":1,"result":null,"error":null}
serve-d shouldn't crash but respond invalid request
let me see if null is actually part of the spec
result
    This member is REQUIRED on success.
    This member MUST NOT exist if there was an error invoking the method.
    The value of this member is determined by the method invoked on the Server.

error
    This member is REQUIRED on error.
    This member MUST NOT exist if there was no error triggered during invocation.
    The value for this member MUST be an Object as defined in section 5.1.
no it's definitely malformed, both result and error exist but they are not allowed to exist at the same time

### Environment

This was found on my mac, using serve-d as the LSP server.  Logs were collected from serve-d, and the commentary there is from the serve-d maintainer.

**Comment by osiewicz** [comment]
Thanks for the report! Let us know if anything else pops up.
