### ISSUE TITLE
file finder cannot be used with keys while the file index isn't finished

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#10628]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening Zed, it appears that a file index with the files of the project is created. For big repos (e.g. Chromium), this index takes a while to build. During that time, using the arrows keys in the file finder moves the currently selected item, but that selection is quickly reset to the first item. After a while (probably when the index is finished), this behavior stops.

### Environment

Zed: v0.130.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

**Comment by izuzak** [comment]
I've experienced this myself more than a few times, but never bothered with figuring out why it was happening. Thanks for creating this issue!
