### ISSUE TITLE
Resizing the project panel breaks the structure of the nested files

### ISSUE THREAD

**Issue by joshuaia** [zed-industries/zed#10622]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

1. Open any project with deep nested structure and large file names
2. Resize projects panel
3. When viewing directory with large file name - resizing the project panel changes the location of these files

https://github.com/zed-industries/zed/assets/51882760/cbccc810-960c-4bcd-9dad-710f2a23fb25

### Environment

Zed: v0.130.7
OS: macOS Sonoma 14.4.1
Memory: 16GB
Architecture: Apple M2

**Comment by osiewicz** [comment]
Hey, I can repro it just fine on Zed repository (e.g. in `crates/theme/src/styles`). Just to note though, this only happens with file icons turned off.

**Comment by osiewicz** [comment]
This is gonna be fixed with today's Preview. Thank you for reporting that issue & using Zed. :)
