### ISSUE TITLE
Disable default key bindings

### ISSUE THREAD

**Issue by cholwell** [zed-industries/zed#10623]
### Check for existing issues

- [X] Completed

### Describe the feature

When using a comprehensive custom `keymap.json` ideally the default key bindings would no longer apply by default.

So far the only workaround I can find is about 200 `"keybind" : "zed::NoAction"` which isn't ideal.

**Comment by JosephTLyons** [comment]
Hey @cholwell, you can set the `"base_keymap"` setting to `None`, which completely disables all default key bindings.

**Comment by cholwell** [comment]
@JosephTLyons ah perfect, thanks for the quick response! I wonder if it might be useful adding a quick line about this somewhere on `https://zed.dev/docs/key-bindings` ?

**Comment by JosephTLyons** [comment]
Yeah - I'm going to repurpose this issue for that!
