### ISSUE TITLE
Git blame support adjust <author> width

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#10631]
### Check for existing issues

- [X] Completed

### Describe the feature

The `d1y` it's really awkward to render such a large area. I hope the width can be adjusted in the settings
/cc @mrnugget
![image.png](https://s2.loli.net/2024/04/17/TcuJ76OhLwpztsY.png)

**Comment by JosephTLyons** [comment]
It might be cool if we could compute just how much width we need dynamically, per file, so that the gutter is only as wide as it needs to be.  The counter to that might be that having varying widths might not look great when flipping between muliptle files with git blame opened.

**Comment by mrnugget** [comment]
Yeah, I think the best way to do would be to compute width dynamically. I don't like to introduce a setting for this.

**Comment by jansol** [comment]
One nice option would be to put commit, author and date on separate lines when possible and have a colored bar on one side to indicate which lines are part of the same blame chunk.

The GitHub blame view actually does this last bit so should be a good reference.
