### ISSUE TITLE
markdown font size controlled by ui_font_size

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#10640]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the font size of markdown should be buffer_font_size, but is controlled by ui_font_size

### Environment

Zed: v0.131.6 (Zed Preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Extreme Fontsize  differences for comparison
<img width="1433" alt="Screenshot 2024-04-16 at 19 18 03" src="https://github.com/zed-industries/zed/assets/121750393/3be82482-6ba3-4d73-be0e-87aec3113231">
<img width="1434" alt="Screenshot 2024-04-16 at 19 17 37" src="https://github.com/zed-industries/zed/assets/121750393/de2a3f1c-55e3-4fd1-a0b8-17e23eed2303">

**Comment by maxdeviant** [comment]
The Markdown preview uses the `ui_font_family`, so I think it makes sense that it also uses the `ui_font_size`.

**Comment by sebastienbarre** [comment]
Is it still the case, I can't find a way to increase the Markdown font size.
They should separate settings please, say `markdown_font_family`, `markdown_font_size`.
Thanks

**Comment by madisvain** [comment]
Came searching how to change the preview font size as it's just too small to easily read. Please make this possible the markdown_font_family and size suggestion sounds excellent if it existed.

**Comment by hacker-cb** [comment]
Adding `markdown_preview_font_size` will be great

**Comment by sduquemesa** [comment]
@JustFrederik this is a good feature to have as time is now spent between markdown files and code files... mostly md tbh

**Comment by olejorgenb** [comment]
Another vote for either following editor font size or a separate setting for the markdown preview font size. The font size for the general UI can be quite a bit smaller than for bigger pieces of text like the markdown preview. 

I can appreciate not wanting setting bloat - and would this setting apply across all markdown preview (commit details, agent view, etc.) - IMO yes.

Thanks @davidalecrim1  : https://github.com/zed-industries/zed/pull/55489 🎉
