### ISSUE TITLE
terminal is blank when editing with a collaborator who is hosting

### ISSUE THREAD

**Issue by calbaker** [zed-industries/zed#10649]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A coworker shared his Zed session with me so we could collaborate, and when I use `<Ctrl> + `` to open a terminal, it just appeared as a blank pane.  

### Environment

Zed: v0.130.7 (Zed)
OS: macOS 13.6.5
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/854536/7b0c5625-2c17-42be-be81-928c10f234d5)

**Comment by JosephTLyons** [comment]
Yeah, at the moment, the terminal is not collaborative and we don't end up showing the local terminal in workspaces that are being used for collaboration - this is something we want to add going forward:

- https://github.com/zed-industries/zed/issues/4767

That being said, there used to be at least a notification that came up to explain this deficiency, not sure if it showed on your end or not, but it should.

Feel free to upvote that issue with a 👍 - I'm going to close this one out in favor of that one. Let me know if I'm missing something and I can reopen this issue.
