### ISSUE TITLE
Add an option for left-side tab close buttons

### ISSUE THREAD

**Issue by igorgusarov** [zed-industries/zed#10656]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, Zed editor places the tab close buttons on the right side of each tab. However, the standard convention on macOS is to have close buttons on the left side of tabs and windows.

It would be nice to have a setting to place tab close buttons on the left side, defaulting to the current OS convention (left for macOS, right for Windows/Linux).

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="263" alt="Screenshot 2024-04-16 at 14 08 02" src="https://github.com/zed-industries/zed/assets/2374205/4274d363-15ad-4140-bf92-4cb9e5859130">

**Comment by maxdeviant** [comment]
This is already supported by the `tabs.close_position` setting:

```json
"tabs": {
  "close_position": "left"
},
```

**Comment by baldwindavid** [comment]
@igorgusarov `zed: open default settings` should do the trick.
