### ISSUE TITLE
Emmet support in xhtml, tsx, jsx, vue, & svelte

### ISSUE THREAD

**Issue by versecafe** [zed-industries/zed#10654]
### Check for existing issues

- [X] Completed

### Describe the feature

Add optional configuration to the emmet extension to enable support for HTML/XML embedded languages, most web developers are writing inside of one of these so having the zed emmet extension limited to just explicitly HTML files is restrictive, implement a system similar to

https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types

with whichever system was chosen for settings for extensions haven't checked in on that in a few weeks.

*also xhtml can be ignored but is likely the easiest as it can just work identically to the default html setup*

**Comment by drale2k** [comment]
Don‘t forget ERB as well pls 🙃

**Comment by versecafe** [comment]
also as configs for extensions become stable it would be nice to be able to map the emmet completion key off tab *or to map copilot off it since they overlap and it causes some odd behaviour*

**Comment by olrtg** [comment]
https://github.com/zed-industries/zed/pull/10779 Improves some of this. I may be able to add Svete and Vue (need to check something first though). XML doesn't seem supported.

**Comment by olrtg** [comment]
For Astro, Svelte and Vue, their language servers already should provide emmet completions so you should have already support for them (with the extensions of course). Although, from my tests only Svelte and Vue are providing completions, for some reason Astro doesn't seem to be working (or at least the language server doesn't get attached to the buffer).

**Comment by 3stbn** [comment]
Hey thanks much for this feature, I am wondering how can I start using the emmet support on tsx files ? I checked the emmet extension version and is still on v0.0.2 from April

**Comment by osiewicz** [comment]
Hey, I'm gonna cut a new 0.0.3 release for emmet extension.

**Comment by osiewicz** [comment]
Aand it's out.
