### ISSUE TITLE
Improve Extensions UI

### ISSUE THREAD

**Issue by Feel-ix-343** [zed-industries/zed#10662]
### Check for existing issues

- [X] Completed

### Describe the feature

A homepage for extensions that includes
- Preview of the README
- Button to give the repo a star
- Button to file an issue or open the github issues page
- Usage stats like in cargo.io
- Install extension
- Look through versions

### If applicable, add mockups / screenshots to help present your vision of the feature

- Something similar (and better) than the VSCode extension homepage
- Obsidian extension preview page
- Cargo.io crate homepage

**Comment by iamnbutler** [comment]
I have some pretty specific plans here, so if you start on anything let's sync up.

I don't expect us to be able to implement all of this right out the gate, but here is a directional design I've been working on:

![CleanShot - 2024-04-17 at 11 47 22@2x](https://github.com/zed-industries/zed/assets/1714999/c109642f-bc95-4fa8-b5ba-756f3906ccb1)

There are a number of blockers preventing this being implemented right now:

- Currently the extensions schema doesn't tell us if an extension is a theme, language, etc.
- There isn't currently a mechanism for attaching/consuming a README

I'm sure there are others, I haven't dug into this too much yet.

**Comment by iamnbutler** [comment]
It would be great if folks want to share screenshot examples of other places they thing extensions/similar UI are done well.

**Comment by Feel-ix-343** [comment]
Beautiful concept

I do love my github stars so I would definitely want to integrate that.

Ill attach some screenshots and do a little write up, then we should for sure sync.

**Comment by maxdeviant** [comment]
> I do love my github stars so I would definitely want to integrate that.

I don't think it makes sense to have this sort of integration with being able to star a repo from within Zed.

**Comment by Feel-ix-343** [comment]
Hey @iamnbutler where are you on this? Depending on how much is left, I may want to help out.

**Comment by iamnbutler** [comment]
No additional work has been done on this, but there is some more recent patterns we've built in Zed that might be a good starting point...

The prompt library opens a new window, which might be how we want to treat extensions. I'm not sure I'll have much time to work on this from scratch, but if someone gets things rolling I can probably pop in to help with design tweaks.
