### ISSUE TITLE
Terminal file paths cannot be clicked when column portion of path is malformed

### ISSUE THREAD

**Issue by pedrorolo** [zed-industries/zed#10688]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Create a task that prints out a file path
- run the task
- try to open the file by clicking or cmd clicking the file path

### Environment

Zed: v0.130.7 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Hey, thanks for filling in this bug report. Do you have an example output we could use to verify it on our side? As far as I can tell, output of something like`pwd` is clickable.

**Comment by pedrorolo** [comment]
```
     NoMethodError:
       undefined method `method_name' for nil:NilClass
     # ./filename.rb:37:in `method_name'
```

**Comment by osiewicz** [comment]
Hm, the following works fine for me:
`echo "     # ./crates/terminal/src/terminal.rs:39: in \`method_name\'"`
I believe the problem lies in `in` being right next to a colon. I'll see if I can make the parsing code more lenient.

**Comment by pedrorolo** [comment]
I believe that this might also be broken when there's also row information
```
# ./filename.rb:37:50:in `method_name'

**Comment by osiewicz** [comment]
It should work just fine with the PR I've opened today
