### ISSUE TITLE
Debian .deb files in the releases page

### ISSUE THREAD

**Issue by williamdes** [zed-industries/zed#10699]
### Check for existing issues

- [X] Completed

### Describe the feature

Ref #7015 

I would like to ask here first, as a Debian maintainer I would like to have Zed incorporated into Debian.
That said it's a lot of work and complexities. 

There is currently no ITP open in Debian: https://wnpp.debian.net/?type%5B%5D=O&type%5B%5D=RFA&type%5B%5D=RFH&type%5B%5D=RFP&project=zed&description=&owner%5B%5D=yes&owner%5B%5D=no&col%5B%5D=dust&col%5B%5D=type&col%5B%5D=description&col%5B%5D=installs&col%5B%5D=owner&sort=installs%2Fdesc

I guess nobody is ready to Intend To Package Zed.
Note: Debian already has a package named Zed. 
Maybe a good name will be zed-editor?

My proposal: On Debian 12 Zed runs fine. My colleagues all want to try Zed but not to have to compile it. I ask if you agree that I make a PR so we start distributing deb files in the releases page.

If you do not agree I will have to make this on my own and host my own Debian repository while this is not official. Users may start to use my repo and once it is done, migrating is always something complicated to have 100% people moved out.

Let me know how my request feels.

**Comment by mikayla-maki** [comment]
We'll be putting up alpha builds of Zed on Linux in the next few weeks :)

If you want to build your own .deb files, feel free! But we still have some bugs we want to iron out.

**Comment by ottok** [comment]
There was an attempt to have Zed officially in Debian, but stalled on structural issues as Zed seems to download too much stuff on its own and not use language servers etc already in Debian as installed via apt: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076165
