### ISSUE TITLE
Window view is small on change font size

### ISSUE THREAD

**Issue by Sirherobrine23** [zed-industries/zed#10706]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open zed

to make normal again open in full screen and return to windowed

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 12.7.4
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/50121801/21538a83-ae02-4c72-a66b-e09fc75e9e4d

**Comment by Moshyfawn** [comment]
I can't seem to reproduce this on a 1440p screen. Note how the 'traffic light' window controls are out of place in the original recording, larger than the editor toolbar 🤔

https://github.com/zed-industries/zed/assets/16290753/7756cd9f-1adb-4841-addc-5a3e1abcc4f6

**Comment by Moshyfawn** [comment]
What font size is your editor UI set to?

**Comment by Sirherobrine23** [comment]
My display is `1366 × 768 (14 inch)`

Current config this is:
```json
{
  "theme": "VScode Dark Plus",
  "ui_font_size": 14,
  "buffer_font_size": 14,
  "format_on_save": "off",
  "tab_size": 2,
  "always_treat_brackets_as_autoclosed": true,
  "auto_update": true,
  "base_keymap": "VSCode",
  "show_wrap_guides": false,
  "features": {
    "copilot": false
  },
  "autosave": {
    "after_delay": {
      "milliseconds": 2000
    }
  }
}
```

**Comment by Moshyfawn** [comment]
Oh, I see the problem you're reporting; that's not what I was talking about, my bad 🙈 Your whole other editor area is rendered black, as opposed to me manually resizing the window.

**Comment by Sirherobrine23** [comment]
this, but area is not clickable area, like it goes to another place

**Comment by Sirherobrine23** [comment]
https://github.com/zed-industries/zed/assets/50121801/93e61b63-0fa5-42f4-ab37-9dc18baa6872

**Comment by notpeter** [comment]
Although your issue came earlier, I'm going to close in favor of:
- https://github.com/zed-industries/zed/issues/13672

Please 👍 that issue and subscribe to track progress.
(And sorry Zed is misbehaving on your monitor!)
