### ISSUE TITLE
Regression: pointer does not change when hovering over draggable border

### ISSUE THREAD

**Issue by Congyuwang** [zed-industries/zed#10705]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Mouse pointer does not change consistently when hovering over draggable border of panels. It does flicker a bit, though.

https://github.com/zed-industries/zed/assets/52687642/53115c8b-bd9a-494d-bad6-2d0228205fbc

### Environment

Zed: v0.132.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
I can't seem to reproduce it on `0.132.0`. Is there anything specific you're doing after opening the editor, any dock or panel settings?

https://github.com/zed-industries/zed/assets/16290753/b9d884db-9917-4575-87fa-43cc08ae5251

**Comment by Congyuwang** [comment]
Strange. I don't think I've changed anything, but it works just fine now, and I cannot reproduce it. I think I'm going to close it. Will reopen if I encounter this problem again. Thx!
