### ISSUE TITLE
Add Configuration Option for Custom OpenAI Server URL

### ISSUE THREAD

**Issue by ZCNST** [zed-industries/zed#10716]
### Check for existing issues

- [X] Completed

### Describe the feature

As a user of the OpenAI API, I would like the ability to configure a custom server URL endpoint for API requests. Currently, we can only set the API Key, which restricts us to the default OpenAI server URL.

This feature is particularly relevant for enterprise users who have strict control over their data routing and server access policies.

Moreover, it would align the OpenAI API client with other API clients that offer similar URL configuration options, thereby meeting a common expectation for API interaction.

I look forward to seeing this feature considered for implementation, as it would significantly enhance the flexibility and control we have over our interactions with OpenAI's services. Thank you for your attention to this request.

![Screenshot 2024-04-18 at 10 56 48](https://github.com/zed-industries/zed/assets/34453570/d6acb82d-8ffa-4e33-bcab-d0b5986ed90b)

**Comment by Moshyfawn** [comment]
Check out [this comment](https://github.com/zed-industries/zed/issues/4424#issuecomment-2053646583) on how to provide a custom AI endpoint URL. Does this meet your needs?

**Comment by Moshyfawn** [comment]
Related #9617

**Comment by birdmanmandbir** [comment]
I suppose this issue has been resolved for now.

**Comment by notpeter** [comment]
This is covered in the docs: [Zed Assistant: Configuration: OpenAI](https://zed.dev/docs/assistant/configuration#openai) and has been supported for a while.

I have tested many alternate server_urls (ollama, etc) for services with OpenAI compatible APIs.
