### ISSUE TITLE
Add option to prevent focus previous tab after closing a tab

### ISSUE THREAD

**Issue by mkismy** [zed-industries/zed#10715]
### Check for existing issues

- [X] Completed

### Describe the feature

The current behaviour after closing a tab is to focus previous activated tab. 

However it is quite hard-to-use so it will be nice to have an option to prevent this and instead open the left or right tab, something equivalent to VSCode's `workbench.editor.focusRecentEditorAfterClose: false`.

In the recording below, I expect zed to open 5 -> 4 -> 3 -> 2 -> 1

https://github.com/zed-industries/zed/assets/8445575/8e7cc5cf-eae7-4a80-9715-1be7a68187b5

**Comment by bennetbo** [comment]
Hey, the order here should not be random, zed focuses the previously activated tab when closing the current one. So you probably activated the tabs in the following order 3 -> 2 -> 4 -> 1 -> 5.
Therefore when you close tab 5 zed focuses tab 1, closing tab 1 focuses tab 4, and so on...

**Comment by mkismy** [comment]
Oh, now I understand the patten. I'll rename the issue.

**Comment by elitan** [comment]
fix:

settings.json

```json
{
  "tabs": {
    "activate_on_close": "neighbour"
  }
}

https://zed.dev/docs/configuring-zed#activate-on-close

**Comment by mkismy** [comment]
Great to have a new config for this ✨
