### ISSUE TITLE
`\n` is not rendered correctly in Markdown code blocks in tooltips

### ISSUE THREAD

**Issue by jetli** [zed-industries/zed#10710]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`\n` is not rendered correctly in Markdown code blocks in tooltips
<img width="964" alt="截屏2024-04-18 13 25 02" src="https://github.com/zed-industries/zed/assets/1142758/d0bc2774-c27b-46f2-88be-3596d2ce2985">
<img width="677" alt="截屏2024-04-18 13 26 15" src="https://github.com/zed-industries/zed/assets/1142758/a0b9ddbc-ebba-4d62-bad2-daba15c2b829">

### Environment

Zed: v0.132.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment]
cc: @bennetbo
