### ISSUE TITLE
Intellisense suggestions are too slow on larger projects

### ISSUE THREAD

**Issue by smitbarmase** [zed-industries/zed#10719]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

TailwindCSS completion is too slow on larger projects; it updates suggestions quickly on smaller projects but experiences a 1-3 second lag in updating suggestions on larger ones.

Edit 1: I noticed it is not just tailwind but overall autocomplete suggestions.

Below is a screen share for the same file and the same project on Zed and VSCode.

### Environment

Zed: v0.132.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed:
https://github.com/zed-industries/zed/assets/37347831/3a4ba8cb-043b-44e4-881b-3b1e6a934afe

VSCode:
https://github.com/zed-industries/zed/assets/37347831/4e7b59fe-86a8-41a6-b238-ea79b7b711ee

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[log.txt](https://github.com/zed-industries/zed/files/15022640/log.txt)

**Comment by JosephTLyons** [comment]
Hey @smitbarmase - are you experiencing this with all langauge servers you use, or only the TailwindCSS one?

**Comment by smitbarmase** [comment]
All language servers are affected. This doesn't happen consistently, just occasionally. I will monitor this and reopen the issue if necessary.
