### ISSUE TITLE
import path renaming/refactor rename for filenames

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#10723]
### Check for existing issues

- [X] Completed

### Describe the feature

it would be a great feature if the file rename would behave exactly like the symbol rename and also rename all the imports

**Comment by Moshyfawn** [comment]
There's already a similar request, so I'm going to close this issue in favour of the other one. Be sure to +👍 and add any additional information to the other thread.

Duplicate of
- #5252
