### ISSUE TITLE
Tasks continually add terminal panel buttons to status bar

### ISSUE THREAD

**Issue by jamesgecko** [zed-industries/zed#10735]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Every time I run a task, a new terminal button is added to the bottom panel. Sometimes a lot are added at once!

(When right clicking on the buttons and changing the side of the window the terminal was docked on a few times, Zed crashed. Unsure if related, or just Zed being Zed. Logs: https://gist.github.com/jamesgecko/035b704ec056b7eae04429cf01e44dcc).

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="2672" alt="Screenshot 2024-04-18 at 12 10 37 PM" src="https://github.com/zed-industries/zed/assets/44252/8ec5eccb-943e-41d6-85da-8d083319e099">

**Comment by osiewicz** [comment]
Could be related to https://github.com/zed-industries/zed/issues/9688

**Comment by Moshyfawn** [comment]
It seems to be related to the OP's comment about "changing the side of the window the terminal was docked on a few times". Do you think we can merge these two reports?

**Comment by osiewicz** [comment]
Yeah, this looks like a duplicate to me.
