### ISSUE TITLE
copy in json can be converted to struct

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#10770]
### Check for existing issues

- [X] Completed

### Describe the feature

1. checks if input/clipboard is json `let _: serde::de::IgnoredAny = serde_json::from_str(data)?;`
2. asks user if struct should be generated
3. if true
4. paste in generated struct `let struct_string = json_typegen_shared::codegen(name, json_string, Options::default())?`
5. if false
6. paste in clipboard

**Comment by JustFrederik** [comment]
I don’t think a language server would be a good solution. It’s manipulating the clipboard and doesn’t need to read every change in the workspace. 

Rust is part of the editor so I suggested it as a feature.

I personally dislike when functionality is split up over multiple plugins and prefer if there is a single plugin and not a plugin for each
Coc,snippets,lsp,debugger,formatter,util…

this is also the case right now for the extensions(my guess because most description say language support ä and only a few syntax highlighting)

**Comment by JosephTLyons** [comment]
The Rust language server already provides the ability to transform JSON into a Rust struct:

https://github.com/zed-industries/zed/assets/19867440/a81cc27d-6ea1-4091-930c-1b927e27a106

Does this not cover your needs @elkowar?
