### ISSUE TITLE
ERB support, including syntax highlighting and auto complete broken since v0.131.6

### ISSUE THREAD

**Issue by drale2k** [zed-industries/zed#10772]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since the update yesterday to `Zed 0.131.6` ERB support seems completely broken. Including syntax highlighting, tailwind CSS classes suggestions and everything that comes with it. Please fix 🙏🏻, i am gonna revert to the previous update in the meantime. 

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="681" alt="Screenshot 2024-04-19 at 14 10 21" src="https://github.com/zed-industries/zed/assets/271416/deb7638a-23df-4c3e-b947-f185f6bc9752">

**Comment by maxbrunsfeld** [comment]
@drale2k Sorry for the bad experience there. If you install the HTML extension from the `Extensions` view, does it work as expected?

**Comment by drale2k** [comment]
@maxbrunsfeld Yes that worked, thanks a lot! Curious what broke it. Was the HTML extension before the update part of Zed and was removed? If so i believe this will cause a lot of confusion and future GH issues. 

The most confusing part is that one is able to select ERB as the language for that file but the editor is lacking HTML/ERB support. A language should only appear in the picker if the editor has support for it.
