### ISSUE TITLE
Zed putting volume drive shortcuts on desktop MacOS

### ISSUE THREAD

**Issue by spaceunifyfifty** [zed-industries/zed#10782]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After a few hours of working in Zed I will find that my desktop is suddenly riddled with several weird ejectable drive shortcuts titled `Zed` and untitled folders. 
<img width="242" alt="example" src="https://github.com/zed-industries/zed/assets/158013953/d41b8de2-4e49-463a-a705-e0710a6745b3">

I suspect I am accidentally causing this through some keyboard shortcut that I am not aware of. I have the vscode keymap turned on.

To get rid of them, I have to option click on each of the icons and press `Eject`. But more show up again every day.

What is causing this and how can I disable it?

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @spaceunifyfifty - how are you launching the Zed app? Have you copied it over to your `/applications` directory? Are you launching the app from the disk image?

**Comment by lsgng** [comment]
Same issue here. Don't see them on my desktop, but running `diskutil list` currently shows me **several hundred** mounted Zed volumes:

```
/dev/disk326 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +230.6 MB   disk326
   1:                 Apple_APFS Container disk327       230.5 MB   disk326s1

/dev/disk327 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +230.5 MB   disk327
                                 Physical Store disk326s1
   1:                APFS Volume Zed                     199.6 MB   disk327s1
```
_OS:_ MacOS 14.5
_Zed version:_ Not sure, uninstalled it (for good) before writing this comment. Probaby`0.140.5` (current version on Homebrew).

**Comment by tristonarmstrong** [comment]
i have the same issue. I also have two accounts, one of which i use zed with. When i switch back to the account i dont use zed with i notice  the plethora of drives mounted 
MacOS 14.1

**Comment by vitallium** [comment]
It seems that [the `install_release_macos` function](https://github.com/zed-industries/zed/blob/0e2d3d223ffe5c5e80a14848698a06b330bc53cf/crates/auto_update/src/auto_update.rs#L742) can leave a dangling mounted disk image in the macOS if something goes wrong during the auto-update process. This happens because in that function the unmount code executed at the end of this function. I will create a PR to fix that.
