### ISSUE TITLE
'toggle terminal' keymap works strange in vim mode

### ISSUE THREAD

**Issue by dev-hann** [zed-industries/zed#10797]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in Linux, when i open terminal use [ctrl+`]. and close terminal use [ctrl+j].
and i cannot edit vim keymap.

### Environment

```
           .-/+oossssoo+/-.               han@han-ThinkPad-T480 
        `:+ssssssssssssssssss+:`           --------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.4 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20L6S27400 ThinkPad T480 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.5.0-28-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 50 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2737 (dpkg), 20 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.9 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-8350U (8) @ 3.600GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel UHD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 5191MiB / 15863MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                  
```

**Comment by d1y** [comment]
@dev-hann can you provide more context to describe the problem? record a video?

**Comment by dev-hann** [comment]
[Screencast from 04-24-2024 07:22:47 AM.webm](https://github.com/zed-industries/zed/assets/54878755/8cc53de7-196d-4766-a1b4-b8fa21c4e59b)

Here it is . ctrl + j(toggle terminal) not work during edit code, just do vim shortcut. 
but not focus in editor works well.
Is there any solution?

**Comment by DissolveDZ** [comment]
I believe you can close this, terminal focus is for toggeling the terminal focus, if you want to toggle the terminal's visibility you have to bind workspace::ToggleBottomDock to the key you want, ctrl-' in your case

here's a quick example

    {
        "context": "Editor || Terminal || ProjectPanel",
        "bindings": {
            "ctrl-'": "workspace::ToggleBottomDock"
        }
    }

**Comment by dev-hann** [comment]
@DissolveDZ  thanks a lot it works well.
