### ISSUE TITLE
Select branch

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#10806]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="331" alt="Screenshot 2024-04-20 alle 15 49 53" src="https://github.com/zed-industries/zed/assets/20476002/55a03a17-5de7-4347-9a48-7c254392e7ce">

<img width="588" alt="Screenshot 2024-04-20 alle 15 50 58" src="https://github.com/zed-industries/zed/assets/20476002/fac69e8e-25eb-48dd-964b-7e37f794ad25">

<img width="510" alt="Screenshot 2024-04-20 alle 15 57 44" src="https://github.com/zed-industries/zed/assets/20476002/053563f6-7d24-48cd-b3bf-c91c66fc2812">

<img width="563" alt="Screenshot 2024-04-20 alle 15 58 21" src="https://github.com/zed-industries/zed/assets/20476002/da00fcdf-657f-4f4d-9357-e19513febd4e">

1) The current branch should be shown first among all, which does not happen, and it is not even clear from the selection which branch is currently in use
2) For each branch it should be displayed when the last commit was made on that branch and who made that last commit
3) For each branch as seen in the image you can do the Switch, Merge into, Rename, New branch from

**Comment by notpeter** [comment]
We are not currently seeking feedback on the design of git features of Zed.
Thanks for reporting.
