### ISSUE TITLE
History commit

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#10807]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="357" alt="Screenshot 2024-04-20 alle 16 22 10" src="https://github.com/zed-industries/zed/assets/20476002/7fb30c9e-016c-408d-b8f8-b9bc8562db91">

Details:

<img width="357" alt="Screenshot 2024-04-20 alle 16 23 13" src="https://github.com/zed-industries/zed/assets/20476002/94e0ad59-aa49-46a8-be4b-6fb99350e2fd">

<img width="357" alt="Screenshot 2024-04-20 alle 16 22 22" src="https://github.com/zed-industries/zed/assets/20476002/15695888-70ef-4037-b2ee-2bb2927959b7">

**Comment by JosephTLyons** [comment]
I'm not sure of the exact details of how the source control panel will pan out, but the commit history *could* show up there:

- https://github.com/zed-industries/zed/issues/4367

**Comment by Moshyfawn** [comment]
> I'm not sure of the exact details of how the source control panel will pan out, but the commit history _could_ show up there:
> 
> * [Source control view panel #4367](https://github.com/zed-industries/zed/issues/4367)

That's what I originally thought, but the source panel changes show the currently modified / deleted etc file, which is not exactly history. Now it could be an additional panel, say at the bottom of the source panel, but I don't think it's worth merging the two issues if you're thinking about it. I'm happy to do it if you think it's a good idea.

**Comment by someone13574** [comment]
I really like how this vscode extension does git support: https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

**Comment by notpeter** [comment]
We are not currently seeking design feedback for git features in Zed.
They are under active development.
Thanks for reporting.
