### ISSUE TITLE
Default settings doesn't make it clear it's just a guide and you're not editing the settings

### ISSUE THREAD

**Issue by hippietrail** [zed-industries/zed#10844]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The first and last of these options allow you to edit settings. The middle creates a new file which is notionally a read-only guide. But this is probably not intuitive to all new users:
- Zed/Settings/Open Settings
- Zed/Settings/Open Default Settings
- Zed/Settings/Open Local Settings

In other words, the verb "open" has different meanings. Maybe change them to "Edit", "View", and "Edit"?

Zed/Settings/Open Settings and Zed/Settings/Open Local Settings both begin with introductory comments that give some info on what they're for. Zed/Settings/Open Default Settings does not.

(I note also that "Open Local Settings" starts off by telling you it's actually called "Folder-specific settings", which may or may not add to any confusion for some users trying to figure out the differences between these three options? Might I suggest either picking one term or alternatively using both terms in the intro comment?)

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Also, something we should probaby do here is implement:

- https://github.com/zed-industries/zed/issues/5105

Typing would be forbidden in these files, which would also ight help to clear the confusion.

**Comment by xcrap** [comment]
Also in the default settings the default formatter is different from the documentation, one is set to auto the other to language_server.

**Comment by notpeter** [comment]
We now open Default Settings and Default Keymap as a read-only buffer so this is clearer (e.g. you can't edit):
- https://github.com/zed-industries/zed/pull/16906
