### ISSUE TITLE
Tasks are using file parameters from previous runs

### ISSUE THREAD

**Issue by pedrorolo** [zed-industries/zed#10845]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When running the same task a second time using Ctrol-Shift-T , the values from the old run for $ZED_FILE, and $ZED_ROW are used instead of the ones of the current context. Please notice that this might be desirable when reruning tasks with Ctrol-T.

### Environment

Zed: v0.132.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
> Please notice that this might be desirable when reruning tasks with Ctrol-T.

Exactly this.
If you want to rerun your tasks with the new context only, consider using an altered rerun flavor:
```
{
    "context": "Workspace",
    "bindings": {
        "alt-t": ["task::Rerun", { "reevaluate_context": true }]
    }
}
```

**Comment by pedrorolo** [comment]
This should be a default:
```
[
  {
    "context": "Workspace",
    "bindings": {
      "alt-shift-t": ["task::Spawn", { "reevaluate_context": true }]
    }
  }
]

**Comment by pedrorolo** [comment]
I suspect that from a product perspective what makes sense is to have revaluate_context true by default, and that alt-t should explicitly mark it as false. In most commands that use the context you will want to reevaluate it at every execution. @SomeoneToIgnore @JosephTLyons

**Comment by jessevdp** [comment]
> This should be a default:
> 
> ```
> [
>   {
>     "context": "Workspace",
>     "bindings": {
>       "alt-shift-t": ["task::Spawn", { "reevaluate_context": true }]
>     }
>   }
> ]
> ```

This does not seem to work for me.

The `{ "reevaluate_context": true }` argument seems to work as expected on `task::Rerun`. But not on `task::Spawn` it does not seem to have any effect.
(I don't know Rust well enough to track down why... )

I currently see no way to force re-evaluation of `$ZED_FILE` and `$ZED_ROW` etc on `task::Spawn`.

Except for adding `"ignore_previously_resolved": true` to the tasks definition.

```json
{
  "label": "RSpec: current file",
  "args": ["$ZED_FILE"],
  "command": "rspec --order defined --format doc --no-profile",
  "ignore_previously_resolved": true
}
```

But that breaks the ability to re-run a task without re-evaluating using `task::Rerun`.
Which is pretty desirable to me.

**Comment by SomeoneToIgnore** [comment]
I believe this should be improved in https://github.com/zed-industries/zed/pull/10873, see https://github.com/zed-industries/zed/pull/11026#issuecomment-2079040278 for more details.

**Comment by jessevdp** [comment]
The screenshots shared here https://github.com/zed-industries/zed/pull/11026#issuecomment-2079040278 looks awesome! 🤩 

I was indeed thinking that the mental model (UX) needed some improvements. Rather than the "hack" of _"if I use the spawn modal -> it resets context, but when I use rerun it does not"_.

The mental model of Task Templates vs. Task "instances" works really well there I think. Awesome idea!

* Use the "task spawner/modal" to re-run a recent task
* Use the "task spawner/modal" to run a new instance of a task
* Re-run the last task

---

I'm curious @osiewicz, are there any plans to show the arguments for the task in the UI?

Say I have the following tasks defined:
```json
[
  {
    "label": "rspec: single file",
    "args": ["$ZED_FILE"],
    "command": "rspec --order defined --format doc --no-profile",
  },
  {
    "label": "rspec: single line",
    "args": ["$ZED_FILE:$ZED_ROW"],
    "command": "rspec --order defined --format doc --no-profile",
  },
]
```

I'd want to be able to tell the difference between two recent instances of "RSpec: single line".

Note: `$ZED_FILE` resolves to an absolute path, but in the tasks UI a relative path would suffice (& be preferable of course).

**Comment by osiewicz** [comment]
Hey @jessevdp,
Yeah, it should be possible to inspect full command line of a task instance even in current Preview; we surface them in tooltips as follows:
![image](https://github.com/zed-industries/zed/assets/24362066/89750ea4-401f-4a71-8190-7998320acb5c)

Note though that if you were to run the same task twice, you'd only get one instance in your task history.

**Comment by jessevdp** [comment]
Ah I see. 

I suppose that works well enough for the problem as described in this issue.

But I wonder if there would still be room for a proper “arguments” concept for tasks. Where a “template” could have arguments of different types: fillable through pre-defined variables like `$ZED_EDITOR`, or perhaps through user-input.  (Related: #10838.)

Perhaps with some option to override defaulted values? (Though for the use case of running the file under cursor, less UI is better.)

If these arguments were first-class citizens, they could show up in the task selection UI too. 

1. Spawn a task from a template
2. (Fill out the arguments, automatically if they reference ENV variables.)
3. … it runs …
4. Re-spawn a task (with stored argument context)

Just dreaming/spitballing a bit here. Do you think it’s a worthwhile idea? Would you like me to write it out further and create a separate issue?

**Comment by osiewicz** [comment]
I think that would be nice, yeah, but I don't think now is a good time to tackle that. We probably should sort out various wrinkles with tasks first (e.g. how they're gonna integrate with extensions). I'd rather have us focus on that for now and actually get tasks more to forefront of Zed experience and *then* see how common of a limitation the lack of user input is.
A separate issue definitely sounds like a good idea.

**Comment by brundonsmith** [comment]
I don't know if this is the exact same issue that's already been discussed, but I have the following task
```json
{
  "label": "Git diff",
  "command": "git --no-pager diff",
  "args": ["$ZED_FILE"]
}
```

Series of events:
1. I `spawn` this task on file `a.txt`
2. I see the correct output for `a.txt`
3. I `spawn` it on file `b.txt`
4. I see new output for `a.txt`
5. I run `workspace: reload`
6. I `spawn` it on file `b.txt`
7.  I see the correct output for `b.txt`
8. I `spawn` it on file `a.txt`
9. I see new output for `b.txt`

So whatever `$ZED_FILE` is the first time I spawn the task, that is what `$ZED_FILE` will always be for that task until I restart the entire editor
