### ISSUE TITLE
zed -n <projectname> fails to open a new window

### ISSUE THREAD

**Issue by auspy** [zed-industries/zed#10843]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when i write "zed ." or "zed -n ." to open a new zed window using current directory nothing happens. just a closed zed app gets added to recent used in mac bottom doc.

### Environment

mac m1 8gb 256gb - sonoma 14.1.1 and zed 0.131.6

**Comment by AntoniosBarotsis** [comment]
I'm having the same issue on Windows, just built from source a few minutes ago. Running `cargo r -r` does not log anything, not sure if a logfile is created somewhere that I can include here.

**Comment by AntoniosBarotsis** [comment]
I've been looking into the code for a bit and I think I've figured out the issue, gonna try and fix it *or give up and write a detailed explanation of what I gathered so far* 😅

**Comment by notpeter** [comment]
I'm going to close this as unactionable. If you are still having this issue, please open a new issue with your zed environment details and a copy of the Zed logs as requested by the template.
