### ISSUE TITLE
Support rootFontSize in Tailwind LSP

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#10840]
### Check for existing issues

- [X] Completed

### Describe the feature

It seems like currently the only configurable part of the Tailwind's LSP is `emmetCompletions`, did I understand the codebase correctly?

I would like to be able to configure `rootFontSize` because my project is not based on `16px`, so px values in intellisense are wrong.

I tried doing all diffrent variants of stuff like:

```json
{
  "lsp": {
    "tailwindcss-language-server": {
      "initialization_options": {
        "tailwindCSS": {
          "rootFontSize": 12
        }
      }
    }
  }
}
```

but nothing worked.

### If applicable, add mockups / screenshots to help present your vision of the feature

The screenshot isn't the best example because it's from a modified configuration, hence the fraction pixel values, but hopefully it's enough to illustrate.

<img width="500" alt="Zed tooltip of a Tailwind class with pixel calculations of rem values" src="https://github.com/zed-industries/zed/assets/471278/2b6daa89-cf75-4d42-8795-f5e583d5e023">

**Comment by silvenon** [comment]
Also, this would only make sense if `lsp` option was available in **local** settings (`.zed/settings.json`), which isn't documented, https://zed.dev/docs/configuring-zed#folder-specific-settings, but I hope is the case!

**Comment by Moshyfawn** [comment]
Related #6759

**Comment by reslear** [comment]
Yeah, that would be really helpful. Any news?

**Comment by mrnugget** [comment]
This will be fixed with https://github.com/zed-industries/zed/pull/20500
