### ISSUE TITLE
no app_id on wayland

### ISSUE THREAD

**Issue by colorsakura** [zed-industries/zed#10850]
### Check for existing issues

- [X] Completed

### Describe the feature

If I don't have an app_id, I can't apply window rules when I'm using the window manager.

see: https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id

**Comment by Moshyfawn** [comment]
There was a proposal to use `app_id` to do some app classification for Linux, so I'm going to close this issue in favour of the one that already exists. Be sure to +👍 the other issue and add any missing information to the other thread. Feel free to object to merging these two issues and we'll reopen.

Duplicate of:
- #9132
