### ISSUE TITLE
Compact empty directories in the file tree

### ISSUE THREAD

**Issue by SouchonTheo** [zed-industries/zed#10853]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello everyone 👋,

It would be amazing to have something like vscode with a compact view of empty directories. See the example below:

![CleanShot 2024-04-22 at 17 30 50](https://github.com/zed-industries/zed/assets/87318821/ccd3fbfd-ac06-4653-ba25-3dc10ee0b20f)

This would greatly improve readability for Scala/Java projects!

Thanks in advance for your consideration 🙏

### If applicable, add mockups / screenshots to help present your vision of the feature

![CleanShot 2024-04-22 at 17 30 50](https://github.com/zed-industries/zed/assets/87318821/ccd3fbfd-ac06-4653-ba25-3dc10ee0b20f)

**Comment by maxdeviant** [comment]
We have a setting for this: `project_panel.auto_fold_dirs`.

https://github.com/zed-industries/zed/blob/ee531b6f4dd2090472b8aff75bf77eb9b2d6e250/assets/settings/default.json#L235-L237

**Comment by SouchonTheo** [comment]
I setup this param to true but it doesn't seems to work
![CleanShot 2024-04-22 at 18 00 40](https://github.com/zed-industries/zed/assets/87318821/65ea1809-5243-4d2b-84df-2a3e6acba6b5)

**Comment by SouchonTheo** [comment]
I really want something like

folder1/folder2/folder3/folder4
-> tmp
-> other files

**Comment by maxdeviant** [comment]
> I setup this param to true but it doesn't seems to work ![CleanShot 2024-04-22 at 18 00 40](https://private-user-images.githubusercontent.com/87318821/324529963-65ea1809-5243-4d2b-84df-2a3e6acba6b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDIyNDgsIm5iZiI6MTcxMzgwMTk0OCwicGF0aCI6Ii84NzMxODgyMS8zMjQ1Mjk5NjMtNjVlYTE4MDktNTI0My00ZDJiLTg0ZGYtMmEzZTZhY2JhNmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNzg4NzNiYjY2ZTI1MTRmZjRmY2JiZjIxMzJkNzY1ZWJmNjRlYmRkN2MyMzg1MTliODE0ODE2NTNjMGU4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNO90DZQmzZINgx11FLTJWKC3p_GPy6QxNVgN_M5vHU)

What version of Zed are you on?

And what happens if you click into the project panel? For me the project panel didn't live-update after changing the setting until I clicked into the project panel.

**Comment by SouchonTheo** [comment]
Zed 0.131.6

Nothing happen :/

**Comment by SouchonTheo** [comment]
If you need more information don't hesitate

**Comment by baldwindavid** [comment]
@SouchonTheo The `auto_fold_dirs` setting is in the Preview release (https://github.com/zed-industries/zed/releases/tag/v0.132.0-pre), but not Stable. It should get released in Stable on Wednesday.

**Comment by SouchonTheo** [comment]
oh ok ! make a lot of sense !

Do you mind if I close the ticket myself on Wednesday if everything goes well ?

Big thanks @maxdeviant @baldwindavid for your time 🙏

**Comment by SouchonTheo** [comment]
working perfectly fine thanks for the hard work !

**Comment by SouchonTheo** [comment]
working perfectly fine thanks for the hard work !

**Comment by Relmen20** [comment]
Hi everyone! May be i do something wrong, but i can`t use this feature. I create `.zed/settings.json` to my project and add `{ "project_panel": { "auto_fold_dirs": true } }` in it, but middle packages still not hidden. I use Ubuntu 22.04.4 LTS and Zed v0.143.7
