### ISSUE TITLE
Windows: Crash when selecting empty row

### ISSUE THREAD

**Issue by DissolveDZN** [zed-industries/zed#10864]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**When using the newest version of zed in release mode, it will crash and return the following**
```error: process didn't exit successfully: target\release\Zed.exe (exit code: 0xffffffff)```
when inserting a new line above the relative first line, for example the crash can easily be reproduced by pressing gg in vim mode to go to the first line and then pressing O to insert above or just trying to navigate to a new line which was created, zed will also sometimes crash when selecting text

### Environment

Zed: v0.133.0 (Zed Dev b29643168c32c11294ec7ece53efdc430f9ede36)
OS: Windows 10.0.22631
Memory: 23.9 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[zed_log.txt](https://github.com/zed-industries/zed/files/15068259/zed_log.txt)

**Comment by mikayla-maki** [comment]
cc: @JunkuiZhang

**Comment by skejeton** [comment]
Can't reproduce.
