### ISSUE TITLE
vim increment incorrectly incremtents to the left of characters, not to the right

### ISSUE THREAD

**Issue by hoodie** [zed-industries/zed#10865]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi there, nice editor! I noticed a slight edge case in which the vim commands `ctrl+a` and `ctrl+x` do not behave as intended. When your cursor is over a non-digit character (e.g. the dot `1ˇ.2)` zed currently looks backwards and increments the `1` instead of the `2` as vim would.

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
A fix for this is now included in [0.134.0-pre](https://zed.dev/releases/preview/0.134.0).
