### ISSUE TITLE
Improve Close Dialog Keyboard Accessibility (Again)

### ISSUE THREAD

**Issue by boredstiff** [zed-industries/zed#10879]
### Describe the bug / provide steps to reproduce it

Check for existing issues:
- [x] Done, but it was closed as fixed a year ago, when the dialog looks like it was a different one than it is now.
https://github.com/zed-industries/zed/issues/5990

Describe the bug:
![image](https://github.com/zed-industries/zed/assets/3489076/5201c6f6-ea2d-4792-ab92-6fc87c370574)

This dialog does not highlight a button, so I can't tab through it to select other options. I'm tabbing through, pressing up and down, and none of the buttons are highlighted.

It would be nice if the dialog functionality was fixed to how it previously worked, where the top option is selected so we can tab through it and not have to reach for the mouse to close a file.

As the original issue mentioned, the following keypresses would be nice in this dialog to be one keypress away from the action.

- Cancel: Escape
- Don't Save: Space
- Save: Enter

Thank you :) 

### Environment

MacOS 14.1.1

**Comment by SomeoneToIgnore** [comment]
Current Zed on mac spawns system dialogues that do exactly what is requested:

<img width="267" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/16efd1e5-9d2e-4ae0-97c6-0880bde67dbd">

But I have the keyboard navigation enabled in the system settings:
<img width="496" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/0a026b00-976a-4f80-b232-afc68d19db39">

If I turn that off and restart Zed, I get back to the sorry state from the screenshots, but when I turn it back, it works again.
Do you have this setting on and things still are not working for you?
