### ISSUE TITLE
Guides channel keeps showing "unread notes" marker

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#10887]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As it says in the title. Worth noting that the channel notes for that channel appear to be completely empty, which I would expect to never generate unread notifications instead of always generating them.

### Environment

Zed: v1.0.0 (Zed Dev ae3c641bbee2029fb4588d008e45ddb783593622)
OS: Linux 1.0.0
Memory: 31 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment]
cc @ConradIrwin

**Comment by ConradIrwin** [comment]
@jansol I've been meaning to remove these indicators for a while now. Would you miss them (if they weren't buggy :D)?
