### ISSUE TITLE
Workspace project order is not preserved

### ISSUE THREAD

**Issue by eth0net** [zed-industries/zed#10883]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When adding multiple project folders to a workspace they are added to the bottom of the list, but on workspace restart they are automatically organised alphabetically.

This is illogical to me and I'd like to see the order of projects in the workspace preserved, especially since I'd also like to be able to manually reorder them, like in other IDEs.

### Environment

Zed: v0.132.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 64 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment]
I forgot to report this before, thanks for doing this!

**Comment by eth0net** [comment]
So I've tested this over and over to be as sure as I can, but it looks like workspaces from before the more recent fixes have this issue. I recreated a workspace I saw this issue with and the issue is gone now. Not an ideal fix but it seems fine with new workspaces.

**Comment by eth0net** [comment]
#19232 fixes the sorting, so keep an eye out for it in an upcoming release ^^
