### ISSUE TITLE
Keyboard end does not go at the end but at first line end of wrap

### ISSUE THREAD

**Issue by williamdes** [zed-industries/zed#10888]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/7784660/3691a024-646a-4845-8f1b-bd08172029be)

As shown here
It should go to the end of the wrap when I hit <kbd>Fin (End)</kbd> on my keyboard.
Vscode works fine with this behavior. I guess this is an implementation bug.

```json

  "soft_wrap": "preferred_line_length",
  "preferred_line_length": 180,
```

### Environment

Zed: v1.0.0 (Zed Dev a0fa8a489bb4af98059e5a064c7fac2a77b49aff)
OS: Debian 12
Memory: 62.4 GiB
Architecture: x86_64

**Comment by tverghis** [comment]
Hi! I'd like to work on this issue.

**Comment by tverghis** [comment]
I believe the issue is `Editor::move_to_{beginning|end}_of_line` always stop at soft-wraps. Should this be made configurable, like it is for `Editor::select_to_{beginning|end}_of_line`?

**Comment by williamdes** [comment]
The keybindings stuff is not that intuitive to edit, but here is how to make this setting work:
In: `~/.config/zed/keymap.json`
```json
[
  // Bindings from VS Code
  {
    "context": "Editor",
    "bindings": {
      "end":  [
         "editor::MoveToEndOfLine",
         {
           "stop_at_soft_wraps": false
         }
      ],
...
```
