### ISSUE TITLE
Svelte syntax highlighting breaks using `context="module"` with Javascript

### ISSUE THREAD

**Issue by corneliusio** [zed-industries/zed#10893]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using `context="module"` on a script tag in Svelte that is also using Javascript (**not** Typescript) syntax highlighting completely breaks in the `context="module"` script tags. 

Highlighting can be restored temporarily by removing the `module` value from the attribute and re-adding. However it will break again if any content of the script tag is edited.

### Environment

Zed: v0.131.7 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="629" alt="Screenshot 2024-04-23 at 9 40 52 AM" src="https://github.com/zed-industries/zed/assets/4140885/f2db1d2a-eafd-4bab-a9c0-4f1a1ac8a7da">

**Comment by matubu** [comment]
I think this issue can be closed now
