### ISSUE TITLE
github copilot can't be started. failed to iterate over archive 

### ISSUE THREAD

**Issue by arlendarcy** [zed-industries/zed#10908]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First time using zed and trying to get setup with copilot.

Github copilot unable to be started. I have tried manually downloading the copilot files and placing them in the folder as I have seen in other issues without success. It seems zed wipes the copilot folder each time it opens trying to redownload and I see the files in the copilot/dist folder but the error remains. 

I have tried this while signed in to github copilot and not signed in but the same result either way. 

### Environment

Zed: v0.131.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-04-23 at 2 38 46 PM](https://github.com/zed-industries/zed/assets/97474500/0e150ccd-d8cf-4a1a-b8eb-be3afeccadf7)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15082280/Zed.log)

**Comment by Moshyfawn** [comment]
This seems like a familiar error message; there are a few other issues that aren't related to GitHub Copilot, but are network related:
- #10330
- #9424
- #4768

**Comment by arlendarcy** [comment]
> This seems like a familiar error message; there are a few other issues that aren't related to GitHub Copilot, but are network related:
> 
> * [Extensions: Unable to Install any extension #10330](https://github.com/zed-industries/zed/issues/10330)
> * [Windows: LSP archives are not downloaded #9424](https://github.com/zed-industries/zed/issues/9424)
> * [LSP installation problems when the local LSP already exists in other locations to install #4768](https://github.com/zed-industries/zed/issues/4768)

I am convinced it is a network issue as I see the copilot files show up in the folder after clearing it and clicking reinstall. I also see other LSPs download as well. I am able to download the `.tar.gz` files in the other issue no issue.

**Comment by huacnlee** [comment]
![image](https://github.com/zed-industries/zed/assets/5518/4c875e1e-eb0a-4f8f-ba64-fe48cf09114c)

Fixed by https://github.com/zed-industries/zed/commit/981a143e9b03fe48d9640524c5004600a29f9845

**Comment by arlendarcy** [comment]
@huacnlee unfortunately I am still seeing the error after updating. The same files appear when trying to reinstall.

**Comment by huacnlee** [comment]
Oh, that is different.

I said that is for Windows.

macOS has always been good. If this is the case, you can try to check network access, such as proxy.

**Comment by huacnlee** [comment]
Hi @arlendarcy 

Can try to download copilot archive file in Terminal?

Run this command to test:

```bash
wget https://github.com/zed-industries/copilot/releases/download/v0.5.0/copilot.tar.gz
```

And please also open this URL in Chrome to try to download it.

**Comment by huacnlee** [comment]
> @huacnlee unfortunately I am still seeing the error after updating. The same files appear when trying to reinstall.
> 
> EDIT: btw I am on M1 Mac.

@arlendarcy When you reinstall the Copilot, is the error message still: `Copilot can't be started: failed to interate over archive`?

Or other message?

----

Because I have checked the code, `failed to interate over archive` is meaning unpack the `.gz` have error, but you are said the file have unpacked successfully.

**Comment by huacnlee** [comment]
In your log, it looks like node_runtime is not install success, by this message: `[INFO] Node runtime install_if_needed`.

```
2024-04-23T14:58:42-05:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-04-23T14:58:42-05:00 [ERROR] crates/languages/src/typescript.rs:410: failed to iterate over archive
2024-04-23T14:58:42-05:00 [INFO] Node runtime install_if_needed
2024-04-23T14:58:42-05:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-04-23T14:58:42-05:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-04-23T14:58:42-05:00 [ERROR] failed to start language server "eslint": failed to launch npm subcommand install subcommand
2024-04-23T14:58:42-05:00 [ERROR] server stderr: Some("")
2024-04-23T14:58:42-05:00 [INFO] retrying installation of language server "eslint" in 1s
```

Can you show me this command result:

```
tree ~/Library/Application\ Support/Zed/ -L 4
```

---

And recently we have improved for `node_runtime`。Can you try the latest version of Zed preview, to confirm is still have this problem? 

https://github.com/zed-industries/zed/releases/tag/v0.136.2-pre

**Comment by arlendarcy** [comment]
> > @huacnlee unfortunately I am still seeing the error after updating. The same files appear when trying to reinstall.
> > EDIT: btw I am on M1 Mac.
> 
> @arlendarcy When you reinstall the Copilot, is the error message still: `Copilot can't be started: failed to interate over archive`?
> 
> Or other message?
> 
> Because I have checked the code, `failed to interate over archive` is meaning unpack the `.gz` have error, but you are said the file have unpacked successfully.

Here is what the latest of my testing shows.

When I am on my company vpn I get this error. Note if i click reinstall and then click the copilot icon really quickly after it shows me an option to sign in but it fails with the next screenshot. Note: i am able to wget and download the github file while on the VPN.
![Screenshot 2024-05-17 at 10 48 26 AM](https://github.com/zed-industries/zed/assets/97474500/60a7d729-3823-47de-931d-39d63ce5cba2)
![Screenshot 2024-05-17 at 10 49 12 AM](https://github.com/zed-industries/zed/assets/97474500/40328591-5031-4029-8e9f-347806741979)
This error makes sense as when I click reinstall the zed/copilot directory is wiped and not redownloaded due to the VPN being active. (im not sure why as I am able to wget it no problem)
![Screenshot 2024-05-17 at 10 45 42 AM](https://github.com/zed-industries/zed/assets/97474500/22efb54f-4996-4d3f-be7b-478b19540e52)

I tried without the VPN connected and I am back at the same error but I see the files being unpacked into the directory.
![Screenshot 2024-05-17 at 10 49 48 AM](https://github.com/zed-industries/zed/assets/97474500/c579e824-f1dc-4588-8ee0-089a696e0335)

**Comment by arlendarcy** [comment]
> In your log, I am not sure your node_runtime is installed correct.
> 
> ```
> 2024-04-23T14:58:42-05:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
> Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
> 2024-04-23T14:58:42-05:00 [ERROR] crates/languages/src/typescript.rs:410: failed to iterate over archive
> 2024-04-23T14:58:42-05:00 [INFO] Node runtime install_if_needed
> 2024-04-23T14:58:42-05:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
> Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
> 2024-04-23T14:58:42-05:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
> Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
> 2024-04-23T14:58:42-05:00 [ERROR] failed to start language server "eslint": failed to launch npm subcommand install subcommand
> 2024-04-23T14:58:42-05:00 [ERROR] server stderr: Some("")
> 2024-04-23T14:58:42-05:00 [INFO] retrying installation of language server "eslint" in 1s
> 
> 2024-04-23T14:58:51-05:00 [ERROR] failed to start language server "eslint": failed to launch npm subcommand install subcommand
> 2024-04-23T14:58:51-05:00 [ERROR] server stderr: Some("")
> 2024-04-23T14:58:51-05:00 [ERROR] Hit 4 reinstallation attempts for "eslint"
> ```
> 
> 🎈 Can you show me this command result:
> 
> ```
> tree ~/Library/Application\ Support/Zed/ -L 4
> ```
> 
> The result should be like this:
> 
> ```
> │   ├── typescript-language-server
> │   │   ├── node_modules
> │   │   │   ├── typescript
> │   │   │   └── typescript-language-server
> │   │   ├── package-lock.json
> │   │   └── package.json
> │   └── yaml-language-server
> │       ├── node_modules
> │       │   ├── ajv
> │       │   ├── fast-deep-equal
> │       │   ├── json-schema-traverse
> │       │   ├── jsonc-parser
> │       │   ├── lodash
> │       │   ├── prettier
> │       │   ├── punycode
> │       │   ├── request-light
> │       │   ├── require-from-string
> │       │   ├── uri-js
> │       │   ├── vscode-json-languageservice
> │       │   ├── vscode-jsonrpc
> │       │   ├── vscode-languageserver
> │       │   ├── vscode-languageserver-protocol
> │       │   ├── vscode-languageserver-textdocument
> │       │   ├── vscode-languageserver-types
> │       │   ├── vscode-nls
> │       │   ├── vscode-uri
> │       │   ├── yaml
> │       │   └── yaml-language-server
> │       ├── package-lock.json
> │       └── package.json
> ├── node
> │   └── node-v18.15.0-darwin-arm64
> │       ├── CHANGELOG.md
> │       ├── LICENSE
> │       ├── README.md
> │       ├── bin
> │       │   ├── corepack -> ../lib/node_modules/corepack/dist/corepack.js
> │       │   ├── node
> │       │   ├── npm -> ../lib/node_modules/npm/bin/npm-cli.js
> │       │   └── npx -> ../lib/node_modules/npm/bin/npx-cli.js
> │       ├── blank_global_npmrc
> │       ├── blank_user_npmrc
> │       ├── cache
> │       │   ├── _cacache
> │       │   ├── _logs
> │       │   └── _update-notifier-last-checked
> │       ├── include
> │       │   └── node
> │       ├── lib
> │       │   ├── dtrace
> │       │   └── node_modules
> │       └── share
> │           ├── doc
> │           ├── man
> │           └── systemtap
> ```
> 
> And recently we have improved for `node_runtime`。Can you try the latest version of Zed preview, to confirm is still have this problem?
> 
> https://github.com/zed-industries/zed/releases/tag/v0.136.2-pre



I am using [fnm](https://github.com/Schniz/fnm) to manage my node but my global node should be as follows.
![Screenshot 2024-05-17 at 11 00 47 AM](https://github.com/zed-industries/zed/assets/97474500/d719d689-445d-441f-9e8b-7de560ae9adb)

**Comment by huacnlee** [comment]
It's looks like your node_runtime not download success from your screenshot.

> NOTE: Zed have it own node by itself download, not use your system Node.js.

Please make sure your network is ok to visit nodejs.org.

You can try this link: https://nodejs.org/dist/latest/node-v22.2.0-darwin-x64.tar.gz

And you said, you have uses VPN? Why do you need this?

**Comment by arlendarcy** [comment]
> It's looks like your node_runtime not download success from your screenshot.
> 
> > NOTE: Zed have it own node by itself download, not use your system Node.js.
> 
> Please make sure your network is ok to visit nodejs.org.
> 
> You can try this link: https://nodejs.org/dist/latest/node-v22.2.0-darwin-x64.tar.gz
> 
> And you said, you have uses VPN? Why do you need this?

My company requires VPN unfortunately. But it looks like opening zed for the first time while connected to VPN failed. I opened zed preview without VPN and it seems to have downloaded node correctly. 

It is now working so thank you so much for your time debugging this and hopefully this helps others in the future.

**Comment by arlendarcy** [comment]
Also, im surprised zed didn't try to redownload node outside of the first time opening it. I have tried many times to open zed stable without VPN on to see if it would work but it never did.

**Comment by huacnlee** [comment]
No, I am sure about that. The node runtime will try to download again, if it not exist or have other error.

```
[INFO] Node runtime install_if_needed
```

This log is mean it is going to reinstall, but your system maybe the VPN connect cause the Node also download failed.

**Comment by arlendarcy** [comment]
got it. I will do some experimenting with my npmrc
