### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by aviralpatel** [zed-industries/zed#10907]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When trying to instal an extension by clicking on the install button the button gets disabled for 2-3 seconds and resets back to normal state, but extension doesn't get installed during the process.

### Environment

Zed: v0.131.7 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
@aviralpatel Could you please share the contents of your Zed logs (`zed: open log` in the command palette)? Are there any errors listed there?

**Comment by Moshyfawn** [comment]
This seems to be the same issue as #9802 from the behaviour described. Let me know if you don't mind if I close this issue in favour of the existing one.

**Comment by JosephTLyons** [comment]
Closing in favor of #9802.
