### ISSUE TITLE
Windows: how can i show the main menu.

### ISSUE THREAD

**Issue by E834159672** [zed-industries/zed#10919]
### Check for existing issues

- [X] Completed

### Describe the feature

on mac, there is the top panel to show the application main menu, but on windows, there is no the place , so how and where i can show the main menu ?
on windows:
![image](https://github.com/zed-industries/zed/assets/37103773/82f92c13-5f09-4780-8eb0-62ec83c07604)

on mac,  found the image from x ;
![20240424122749](https://github.com/zed-industries/zed/assets/37103773/dee89a39-ca3a-4417-b42a-118ee88cdd17)

**Comment by CharlesChen0823** [comment]
currently, not support in windows.

**Comment by citorva** [comment]
Based on my early analysis, the menu used by Zed in OSX is provided by the environment and cannot be directely transposed on Linux and Windows.

I think that it is needed to render the application menu in the userspace using the GPUI library.

However, this can be a lot of work.

**Comment by tzabbi** [comment]
Is there any chance that the main menu works on linux?

**Comment by tzabbi** [comment]
@0xtimsb Thank you very much❤️
