### ISSUE TITLE
rust test current function not working

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#10925]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="547" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/363365da-6d57-422f-9b8e-5d6d2048892d">

rust test current function not working when the package name different from folder name.

```toml
[package]
name = "abc-folder"
```

### Environment

Zed: v0.131.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/zed-industries/zed/pull/10929 and should appear in the next Zed update later today.
