### ISSUE TITLE
Disable Auto-Update on Windows and Linux

### ISSUE THREAD

**Issue by someone13574** [zed-industries/zed#10935]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently the auto-updater is Mac specific (thus failing on other platforms), so it should be disabled until other platform’s support is added and releases are actually being distributed. It also would be great if there was a compile-time flag to outright disable it as if being provided through a package manager, the updates should be handled externally.

### Environment

Linux

### If applicable, add mockups / screenshots to help explain present your vision of the feature

A “disable_auto_update” cargo feature flag which doesn’t compile the auto-updater and is enabled by default on Linux and Windows (at least for now).

Edit: Actually, it should be the other way around since cargo features can only be additive. So it would be a flag to enable auto-updates which defaults to on for Mac builds.

**Comment by osiewicz** [comment]
There's already a setting to disable auto-update:
https://github.com/zed-industries/zed/blob/main/assets/settings/default.json#L388
We could add a third option (`platform`) which defaults to `false` on Linux.

**Comment by solrwnd** [comment]
Same issue on macos 11/BigSur, rolling back and disabling auto updates for now.
