### ISSUE TITLE
Keyboard shortcut hints

### ISSUE THREAD

**Issue by derekparker** [zed-industries/zed#10949]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great to have support for something like https://github.com/folke/which-key.nvim in Zed. This is really useful, especially when picking up a new editor with different key bindings, to be able to learn what is possible and help get the navigational key bindings into muscle memory a lot faster without having to open up the full keymap documentation and search.

**Comment by baldwindavid** [comment]
Believe this is a dupe of #10910 opened yesterday.

**Comment by notpeter** [comment]
Duplicate of
- https://github.com/zed-industries/zed/issues/10910

Thanks for reporting. Please 👍 and subscribe to track progress of that issue.
