### ISSUE TITLE
Install extensions declaratively or via CLI

### ISSUE THREAD

**Issue by thomasschafer** [zed-industries/zed#10943]
### Check for existing issues

- [X] Completed

### Misc notes

It would be great to be able to install extensions without relying on the UI: preferably declaratively using `settings.json` (or another config file), or via the `zed` shell command. Is this either possible or planned?

**Comment by thomasschafer** [comment]
> We have an `auto_install_extensions` setting in Zed v0.133.x (releasing to Preview today) that allows you to indicate what extensions should be installed on startup:
> I suspect it's not exactly what you're looking for, but I figured I would mention it all the same.

Useful to know, thanks for the heads up! Am I right in thinking that this won't work for arbitrary extensions, just language specific extensions that Zed would have previously prompted for? I've just installed the 0.133 preview and added
```settings.json
  "auto_install_extensions": {
    "Dracula": true
  },
```
as a test and the extension hasn't been installed, and I couldn't work out whether this was expected from a glance at the code

**Comment by maxdeviant** [comment]
> > We have an `auto_install_extensions` setting in Zed v0.133.x (releasing to Preview today) that allows you to indicate what extensions should be installed on startup:
> > I suspect it's not exactly what you're looking for, but I figured I would mention it all the same.
> 
> Useful to know, thanks for the heads up! Am I right in thinking that this won't work for arbitrary extensions, just language specific extensions that Zed would have previously prompted for? I've just installed the 0.133 preview and added
> 
> ```json
>   "auto_install_extensions": {
>     "Dracula": true
>   },
> ```
> 
> as a test and the extension hasn't been installed, and I couldn't work out whether this was expected from a glance at the code

It should work for all extensions, but you need to use the extension ID:

```json
"auto_install_extensions": {
  "dracula": true
},
```

**Comment by thomasschafer** [comment]
> It should work for all extensions, but you need to use the extension ID:
> 
> ```json
> "auto_install_extensions": {
>   "dracula": true
> },
> ```

Ah yes, that works perfectly - thanks so much! 🙌  That was what I was looking for, so I'm happy to close this issue (unless you wanted it left open for any reason)

**Comment by maxdeviant** [comment]
> > It should work for all extensions, but you need to use the extension ID:
> > ```json
> > "auto_install_extensions": {
> >   "dracula": true
> > },
> > ```
> 
> Ah yes, that works perfectly - thanks so much! 🙌 That was what I was looking for, so I'm happy to close this issue (unless you wanted it left open for any reason)

If your use-case is resolved, then I think we can go ahead and close.

**Comment by cweagans** [comment]
This doesn't seem to be working. My config: https://github.com/cweagans/dotfiles/blob/9ce068606ad636b9ee0b9efedcfbab9936994e27/dot_config/zed/private_settings.json#L2-L44

I installed Zed through Homebrew, pulled in this config, and started Zed. Is there anything I should do to trigger this functionality or should it be fully automated?

**Comment by cweagans** [comment]
Ah, checked the logs and it looks like the extensions were installed, but I had to restart Zed so that the extensions were actually detected.
