### ISSUE TITLE
Abnormal text display

### ISSUE THREAD

**Issue by baiyuze** [zed-industries/zed#10967]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/27543832/3b109186-907d-40d9-9f9e-f437ee927c2d)
fullScreen

### Environment

Graphics/Displays:
      Chipset Model: NVIDIA GeForce GT 720
      VRAM (Total): 1023 MB
          Resolution: 1920 x 1080 (1080p FHD - Full High Definition)
          Resolution: 1920 x 1080 (1080p FHD - Full High Definition)
    Memory Slots:
          Size: 16 GB
          Speed: 2666 MHz
          Size: 16 GB
          Speed: 2666 MHz
Storage:
          Media Name: GALAX QA1M1024F Media
          Medium Type: SSD
          Media Name: GALAX QA1M1024F Media
          Medium Type: SSD
          Media Name: AppleAPFSMedia
          Medium Type: SSD
          Media Name: AppleAPFSMedia
          Media Name: AppleAPFSMedia
          Media Name: AppleAPFSMedia
          Media Name: AppleAPFSMedia
          Medium Type: SSD

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/27543832/ad76a0e0-62e1-405e-81be-cb1717be67ea)

**Comment by osiewicz** [comment]
Related to: https://github.com/zed-industries/zed/issues/6853

**Comment by baiyuze** [comment]
But this problem has not been solved, I am the latest version

**Comment by notpeter** [comment]
I'm closing this in favor of #6853.  That issue is still un-resolved and appears to be isolated to (some) Intel Macs with Nvidia graphics cards.  Please 👍 to vote on it and subscribe there to track progress.

Thanks for reporting this and hopefully we can track this down soon.

**Comment by notpeter** [comment]
@baiyuze Is this an Apple machine, if so which one? 

I couldn't find any with the Nvidia 720M or is this a hackintosh? I'm trying to gather up the common issue and all the other reporters have NVIDIA GeForce GT 650M and NVIDIA GeForce GT 750M. Thanks
