### ISSUE TITLE
Windows: when open zed source code, project tree not show scrollbar.

### ISSUE THREAD

**Issue by E834159672** [zed-industries/zed#10978]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when open zed source code , and then expand crates dir, the project tree not show scrollbar. 

### Environment

windows 11

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/37103773/a9dca743-fb1b-4c26-bc23-fed76aa3430d)

**Comment by JosephTLyons** [comment]
Hey @E834159672, scrollbars are missing in the project panel for all releases platforms (I believe):

- https://github.com/zed-industries/zed/issues/4865

We also are missing scrollbars in other places as well:

- https://github.com/zed-industries/zed/labels/scrollbar

Going to close this out in favor of the first issue, please upvote it with a 👍 reaction!
