### ISSUE TITLE
Linux: build crashed due to E0658 error 

### ISSUE THREAD

**Issue by Akiyamka** [zed-industries/zed#10980]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First attempt:
1. `git clone git@github.com:zed-industries/zed.git`
2. `git submodule update --init --recursive`
3. `rustup update`
4. `script/linux`
5. `cargo run --release` - failed, with `error[E0658]: use of unstable library feature 'bound_map'`

Second attempt:
1. `cargo clean`
2. `cargo build`
3. `cargo run`  - failed, with `error[E0658]: use of unstable library feature 'bound_map'`

See error log below

### Environment

OS: Fedora Linux 38 (Workstation Edition) x86_64
DE: GNOME 44.10
WM: Mutter
Wayland
Kernel: 6.7.9-100.fc38.x86_64
cargo 1.76.0
rustc 1.77.2 (25ef9e3d8 2024-04-09)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
error[E0658]: use of unstable library feature 'bound_map'
   --> crates/semantic_index/src/semantic_index.rs:446:62
    |
446 | ...                   deletion_range.0.map(ToString::to_string),
    |                                        ^^^
    |
    = note: see issue #86026 <https://github.com/rust-lang/rust/issues/86026> for more information

error[E0658]: use of unstable library feature 'bound_map'
   --> crates/semantic_index/src/semantic_index.rs:447:62
    |
447 | ...                   deletion_range.1.map(ToString::to_string),
    |                                        ^^^
    |
    = note: see issue #86026 <https://github.com/rust-lang/rust/issues/86026> for more information

error[E0658]: use of unstable library feature 'bound_map'
   --> crates/semantic_index/src/semantic_index.rs:654:55
    |
654 |                 let start = deletion_range.0.as_ref().map(|start| start.as_str());
    |                                                       ^^^
    |
    = note: see issue #86026 <https://github.com/rust-lang/rust/issues/86026> for more information

error[E0658]: use of unstable library feature 'bound_map'
   --> crates/semantic_index/src/semantic_index.rs:655:53
    |
655 |                 let end = deletion_range.1.as_ref().map(|end| end.as_str());
    |                                                     ^^^
    |
    = note: see issue #86026 <https://github.com/rust-lang/rust/issues/86026> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `semantic_index` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by mrnugget** [comment]
Are you sure that you're using Rust 1.77.x in that directory? Because the feature has been stabilized in 1.77: https://github.com/rust-lang/rust/commit/304a17a4750428d2d791dfe7cda69b0cb2e4fb0d

**Comment by Akiyamka** [comment]
Oh, you're right, it turns out I was unintentionally running rustc version 1.76.0.

**Comment by Akiyamka** [comment]
Resolved by switching to correct rustc binary
