### ISSUE TITLE
Some rust tasks broken under fish

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/zed#10998]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open any rust project with fish as your shell, spawn some task that uses `ZED_CUSTOM_RUST_PACKAGE`. Get
```fish
fish: Variables cannot be bracketed. In fish, please use {$ZED_CUSTOM_RUST…}.
cargo test -p ${ZED_CUSTOM_RUST_PACKAGE}
               ^

⏵ Task `cargo test -p rust-playground` finished with non-zero error code: 127
```

### Environment

Zed: v0.133.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1440" alt="Screenshot 2024-04-25 at 19 58 03" src="https://github.com/zed-industries/zed/assets/43210583/ef91e016-7987-4c0c-9817-e5726c69c3e1">

**Comment by osiewicz** [comment]
Related to: #10964

**Comment by romans-ovo** [comment]
`$ZED_CUSTOM_RUST_PACKAGE` should work for any shell.
