### ISSUE TITLE
Allow vim j/k while inside file finder, project panel, or command palette

### ISSUE THREAD

**Issue by fazulk** [zed-industries/zed#11006]
### Check for existing issues

- [X] Completed

### Describe the feature

Ideally, you could press the `tab` key from here which would then put focus on the files listed, from there you can press `j` or `k` to move up and down through the list

![image](https://github.com/zed-industries/zed/assets/21964900/befb4208-6720-4d73-a3c5-200e5fa83653)

Once you press tab, locating any items by their name is disabled because focus is now on the items listed. You need to navigate through the list either by arrow keys or jk. 

This is currently a setting in vscode that is only enabled when the VIM or Neovim extension is installed.

This same function could be applied to any finder/picker box, such as project, settings, etc.

**Comment by syphar** [comment]
to give a counterpoint, 

neovim plugins like telescope work like zed does now, where you can type normally to search, and then  use ctrl+n and ctrl+p to select entries. As it works in zed right now too

**Comment by fazulk** [comment]
> to give a counterpoint,
> 
> neovim plugins like telescope work like zed does now, where you can type normally to search, and then use ctrl+n and ctrl+p to select entries. As it works in zed right now too

hmm maybe i just need to get used to this keyboard action. does reduce the amount of fingers moving

**Comment by ConradIrwin** [comment]
I'm going to close this as WONTFIX for now, agreeing with @syphar here.

As you'd always need some non-alphabetic character to move focus out of the text box I think it's fine to rely on the default keys for this (up/down or ctrl+n/ctrl+p or ctrl+j/ctrl+k)

**Comment by xzbdmw** [comment]
> to give a counterpoint,
> 
> neovim plugins like telescope work like zed does now, where you can type normally to search, and then use ctrl+n and ctrl+p to select entries. As it works in zed right now too

Telescope do have normal mode in prompt buffer that can define a separate set of keybind, what we need is <esc> to go into normal, <esc> in normal to close panel and a/i to type search characters.
