### ISSUE TITLE
Triple slash reference types directive in typescript highlighted like regular comment

### ISSUE THREAD

**Issue by acalvino4** [zed-industries/zed#11001]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Include a triple slash reference types directive in your typescript file
```.ts
/// <reference types="vite/client" />
```

Observe the lack of syntax highlighting
![image](https://github.com/zed-industries/zed/assets/43254861/bcdc33eb-7c0e-4a1a-9c2e-ee3fbef3bb00)

Compared to vscode
![image](https://github.com/zed-industries/zed/assets/43254861/6f9efe4c-0973-4782-a41e-3935b271fdb2)

### Environment

Zed: v0.132.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: x86_64

**Comment by d1y** [comment]
Apply my patch it work 😁

<img width="517" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/b82db3e1-1ce6-497d-ad6f-2384e6c31890">

```diff
diff --git a/crates/languages/src/typescript/injections.scm b/crates/languages/src/typescript/injections.scm
index 0df1691e7..b971afa92 100644
--- a/crates/languages/src/typescript/injections.scm
+++ b/crates/languages/src/typescript/injections.scm
@@ -1,5 +1,9 @@
 ((comment) @content
   (#set! "language" "jsdoc"))
 
+(((comment) @cx
+  (#match? @cx "^/// <reference types=\"\\S+\"\\s*/>$")) @content
+  (#set! "language" "html"))
+
 ((regex) @content
   (#set! "language" "regex"))

```

**Comment by Klustre** [comment]
Typescript supports various other [Triple-Slash Directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)
```js
/// <reference types="..." />
/// <reference path="..." />
/// <reference lib="..." />
/// <reference no-default-lib="true"/>
/// <amd-module />
/// <amd-dependency />
```
