### ISSUE TITLE
Collapsible Global Search Results Tree

### ISSUE THREAD

**Issue by asmajlovicmars** [zed-industries/zed#11014]
### Check for existing issues

- [X] Completed

### Describe the feature

Would it be possible to add a feature that collapses a list of files containing a searched term, similar to how Visual Studio Code does it?

<img width="267" alt="vsc-collapse-search-tree-1" src="https://github.com/zed-industries/zed/assets/29715259/0fcc0b3d-619b-4d71-8dcd-46e5082f8e6d">

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="267" alt="vsc-collapse-search-tree-1" src="https://github.com/zed-industries/zed/assets/29715259/d1e3d2f7-9339-4f17-a611-177258b8fc0d">

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/4925
