### ISSUE TITLE
Spawn tasks on startup

### ISSUE THREAD

**Issue by ThatOneCalculator** [zed-industries/zed#11025]
### Check for existing issues

- [X] Completed

### Describe the feature

The ability to spawn multiple tasks on startup would be great. I made the following tasks for my developer environment:

```json
[
  {
    "label": "Frontend",
    "command": "bun --env-file=.env.development --filter frontend dev",
    "use_new_terminal": true,
    "reveal": "always"
  },
  {
    "label": "Backend",
    "command": "bun --env-file=.env.development --filter backend dev",
    "use_new_terminal": true,
    "reveal": "always"
  },
  {
    "label": "Database",
    "command": "surreal start file:dev.db",
    "use_new_terminal": true,
    "reveal": "always"
  }
]
```

but having to go to the command palette and start them all manually is a bit of a slog every time I open my editor.

### If applicable, add mockups / screenshots to help present your vision of the feature

A settings field:

```js
"tasks": {
      "run_on_startup": "local" // can be "all", "global", "local", or an array of labelled tasks
}
```

**Comment by osiewicz** [comment]
This looks like a duplicate of #10410 

Thanks for using tasks. ;)

**Comment by ThatOneCalculator** [comment]
Glad to use tasks on Zed, way less cumbersome than VSCode lol
