### ISSUE TITLE
Key autorepeat gets cancelled from unrelated keyup event on wayland

### ISSUE THREAD

**Issue by jakobhellermann** [zed-industries/zed#11048]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you `Hold Right` until autorepeat kicks in, then `Hold Left` until auto repeat kicks in, _then release right_, the autorepeat for holding left stops working. Other applications like vscode keep performing the repeat. 

This can easily happen when switching from holding `j` to holding `k` in vim mode.

### Environment

Zed: v1.0.0 (Zed Dev 4e04606b0d99127e8a35e76695a1ba5e636f1230)
OS: Linux 1.0.0
Memory: 30.5 GiB
Architecture: x86_64

on Wayland.

**Comment by rokyed** [comment]
This issue is still present in 0.141.3 built from source on PopOS 22.
