### ISSUE TITLE
Changing "assistant" feature settings requires "version" property to be defined

### ISSUE THREAD

**Issue by joshuaia** [zed-industries/zed#11045]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open settings and try to change `assistant` feature settings
2. For example:
```
"assistant": {
  "enabled": false,
  "button": false
}
```
3. Zed will trigger warning: `Missing property "version".`

I expect no warnings in this case, since it makes no sense to change the version of this setting.

### Environment

Zed: v0.132.2
OS: macOS Sonoma 14.4.1
Memory: 16GB
Architecture: Apple M2

**Comment by maxdeviant** [comment]
The `version` here indicates which version of the `assistant` settings to use, as there are two different sets of settings.

The `enabled` setting is only relevant for `"version": "1"`, so that's why the version needs to be specified.

Closing this, as this is the expected behavior.
