### ISSUE TITLE
Zed LOG files support for LOG Extension

### ISSUE THREAD

**Issue by xcrap** [zed-industries/zed#11055]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've created the issue here at the Zed-Log Extension https://github.com/evrsen/zed-log/issues/2
but this will need support from the Zed Team, I think it would be nice to have the extension to highlight it's own Zed Log Files, just saying :)

### Environment

Zed: v0.133.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by xcrap** [comment]
Ups my bad, closing the issue :) Thanks!

**Comment by xcrap** [comment]
Well I've read the discussion but it's out of my league, the log extension author also suggested adding the suffix to the logs, not sure how it will affect other dependencies or how hard would it be to implement but it kind of makes sense going for the simpler path. It would be definitely nice to have the highlights working for it's own log files right :)

**Comment by SomeoneToIgnore** [comment]
I'm not sure what to think about it: somebody has to adjust the Zed code to open the *.log file directly, preferrably bumping the log rotation threshold a bit.

Presumably, if all made right, that would cause the `log` extension association (as the corresponding PR got merged) but that needs a manual check — after that, things should be done?
