### ISSUE TITLE
zed available in linux with snap and flatpak support

### ISSUE THREAD

**Issue by userforsource** [zed-industries/zed#11064]
### Check for existing issues

- [X] Completed

### Describe the feature

Really need zed in linux kindly try to make it available asap.
Good to have more gnome gtk4 and macos like approach with rounded corners.

**Comment by DissolveDZ** [comment]
it's already in the Linux goals:
https://github.com/zed-industries/zed/issues/7015

for now you can easily build it yourself by following this guide:

https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_linux.md

**Comment by mikayla-maki** [comment]
We're working on it!

**Comment by userforsource** [comment]
Thanks hope to get it soon.
