### ISSUE TITLE
Can't specify Cpp standard to c++11 or any other

### ISSUE THREAD

**Issue by Hirad2hhk** [zed-industries/zed#11065]
### Check for existing issues

- [X] Completed

### Describe the feature

I wan't to select the cpp standard so the editor will stop shouting about the standard features in the problems tab

**Comment by WeetHet** [comment]
Not an editor problem. Zed uses clangd, which is configured separately. I suggest you have a look at https://clangd.llvm.org/config#add. Also, this types of questions are probably better asked in discussions or zed discord.

**Comment by Hirad2hhk** [comment]
@WeetHet thank your for your response you’re absolutely right and thanks for the tip. I must have been blind while searching.

**Comment by aramrw** [comment]
> @WeetHet thank your for your response you’re absolutely right and thanks for the tip. I must have been blind while searching.

Would you mind sharing how you fixed it? I am trying to specify C++20 but I can't figure it out...

**Comment by RohitKundra** [comment]
I have a raylib project with c++17 that I am trying to edit in Zed and it kept giving me this error.
To solve: 
create a compiler_flags.txt in the project folder (or json if you can find the format online)
After this Neovim works as well with clangd
``
-std=c++17
-I
/Users/username/homebrew/Cellar/raylib/5.0/include
-L
/Users/username/homebrew/Cellar/raylib/5.0/lib -lraylib
``
@aramrw I recommend you refer docs and add more flags as needed. This config is enough for me.
