### ISSUE TITLE
quick get return value or extract result of expression through binding key

### ISSUE THREAD

**Issue by zouyaowen** [zed-industries/zed#11063]
### Check for existing issues

- [X] Completed

### Describe the feature

when focus just before semicolon/;   to get return value.
example:
add(5,6);
through binding key -->
let add = add(5,6)

**Comment by Moshyfawn** [comment]
This sounds like an existing discussion, so I'm going to close this topic in favour of the other one. Be sure to +👍 and add any additional information.

Duplicate of:
- #8344
