### ISSUE TITLE
Windows side run error - settings_file.rs

### ISSUE THREAD

**Issue by GroophyLifefor** [zed-industries/zed#11072]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm getting error when try to run in windows and I know it's not officially released, I'm fan of waitlist and tried to built in my computer.

```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 1.04s
     Running `target\debug\Zed.exe`
[2024-04-27T00:06:56+03:00 ERROR util] crates\settings\src\settings_file.rs:76: EOF while parsing a value at line 1 column 0
[2024-04-27T00:06:57+03:00 ERROR util] crates\zed\src\zed.rs:660: EOF while parsing a value at line 1 column 0
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: ERROR_INITIALIZATION_FAILED" at C:\Users\Groop\.cargo\git\checkouts\blade-b2bcd1de1cf7ab6a\e82eec9\blade-graphics\src\vulkan\init.rs:354:18
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\Groop\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98
```

https://github.com/zed-industries/zed/blob/393b16d2262d6bf94ea0ea9c982ab2b1c2736fae/crates/settings/src/settings_file.rs#L69-L77

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 8.33 GB / 23.73 GB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

I couldn't find its location in Windows

**Comment by integrajerome** [comment]
Oh no! It should be fix by https://github.com/zed-industries/zed/pull/11028, no ?
I am building. I ll tell you what I get

**Comment by integrajerome** [comment]
> Oh no! It should be fix by #11028, no ? I am building. I ll tell you what I get

So bored of it, it is so easy on linux (x11) and osx ;)

**Comment by integrajerome** [comment]
Build is good for me!

**Comment by GroophyLifefor** [comment]
It's works well right now, also, as a little advice, if you write what you are going to write in one comment, people will be more friendly.

Thanks you ❤️
