### ISSUE TITLE
Support AceJump and EasyMotion for Vim mode

### ISSUE THREAD

**Issue by minhhua-EH** [zed-industries/zed#11092]
### Check for existing issues

- [X] Completed

### Describe the feature

In Vim, some plugins like AceJump (for IdeaVim) and EasyMotion allow us to search for a string and jump directly to a word containing that string with a shortcut. It's a very convenient feature that is widely used for Vim users so it'd be great if we have it ASAP on Zed.

### If applicable, add mockups / screenshots to help present your vision of the feature

[](https://github.com/zed-industries/zed/assets/141812477/a821fc42-3634-4474-bd0b-b09962b0ec59)

**Comment by syphar** [comment]
probably a duplicate of #4930

**Comment by ConradIrwin** [comment]
Duplicate of #4930
