### ISSUE TITLE
Linux: Zed does not close properly

### ISSUE THREAD

**Issue by bluthej** [zed-industries/zed#11093]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I close Zed I get an error message in the terminal from which I opened it, which keeps repeating over and over:
```
Protocol error 2 on object zxdg_toplevel_decoration_v1@27:
```

I have to ctrl-c to make it stop.

As a consequence, if I instead open Zed from [wofi](https://hg.sr.ht/~scoopta/wofi) (my application launcher) and close it, I have to go find the process and terminate it, otherwise it keeps running and I am unable to open a new Zed instance.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 15 GiB
Architecture: x86_64

**Comment by ap-1** [comment]
Having the same issue on KDE. Using the builtin `zed: quit` (Ctrl + Q) works fine however.

**Comment by bluthej** [comment]
@ap-1 oh indeed, I didn't notice that the built-in quit worked because I always close applications with my window manager shortcut.

**Comment by mikayla-maki** [comment]
This should be fixed!
