### ISSUE TITLE
Crash when try to open folder, Windows

### ISSUE THREAD

**Issue by GroophyLifefor** [zed-industries/zed#11094]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run the app with `cargo run` command in windows
zed running, docker deployed.
my old folder was opened everything fine.

---
I tried to open a folder with CTRL - O,

Path: "C:\Users\Groop\Desktop\Desktop\Code\kodluyoruz\insider yüzyüze\1ST Week\Timezones"
As a developer I'm supposed that space cause error (between 1ST and Week)

error: 
```
Thread "main" panicked with "already borrowed: BorrowMutError" at crates\gpui\src\app\async_context.rs:93:28
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\Groop\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98
```

### Environment

System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
  Memory: 8.33 GB / 23.73 GB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

I couldn't find its location in Windows

**Comment by GroophyLifefor** [comment]
Additional Experience: not because of the space, but I think it crashes if I try to **reopen a folder that is already open**.

**Comment by Moshyfawn** [comment]
Might be related:
- #10849

**Comment by GroophyLifefor** [comment]
> Might be related:
> - #10849

Thanks for insight, but it's not related to this.

**Comment by the-jasoney** [comment]
Able to reproduce by opening a folder that is already open

**Comment by GroophyLifefor** [comment]
@the-jasoney Let me leave a video for you to understand better.

The shortcut I use to open folders: CTRL + o

https://github.com/zed-industries/zed/assets/77299279/c0eb72fb-6675-405c-bd26-54fa2dc4a7ff

**Comment by CharlesChen0823** [comment]
this is a problem exists long time, I guess the root of the problem might be [here](https://github.com/zed-industries/zed/blob/ad44237467014b412a855afdd8a4b473e6e0bbd9/crates/gpui/src/platform/windows/window.rs#L1813), but i don't know how to deal with.

**Comment by GroophyLifefor** [comment]
> this is a problem exists long time, I guess the root of the problem might be [here](https://github.com/zed-industries/zed/blob/ad44237467014b412a855afdd8a4b473e6e0bbd9/crates/gpui/src/platform/windows/window.rs#L1813), but i don't know how to deal with.

Thanks you for insight and resource, I hope soon labels will be edited and added to the roadmap.

**Comment by MatinAniss** [comment]
This should be fixed by this PR: https://github.com/zed-industries/zed/pull/11393

**Comment by GroophyLifefor** [comment]
It looks fixed, I'm closing the issue.

Have a good working!

memo: I have a dream to do my web projects in this editor, so I hope the support for js/ts/jsx/tsx extensions is in the roadmap.
