### ISSUE TITLE
Vim mode does not turn back on until I switch tab

### ISSUE THREAD

**Issue by bluthej** [zed-industries/zed#11090]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I turn vim mode off from the `settings.json` file and save, the change takes place instantly, however when I turn it back on and save the change does not take place until I switch tab.

This is really not a big deal as I don't expect to need to do that very often, but I thought I'd bring this up just in case :)

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 15 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here is a video showing this behavior (note that I purposefully held ctrl+tab for a while so that you can see I am changing the tab to make the change happen)

https://github.com/zed-industries/zed/assets/29771403/d364fac5-f863-41d2-b251-2854413be027

Note that in the status bar at the bottom the "-- NORMAL --" indication reappears instantly after save, but I'm not actually in normal mode, if I type text is entered instead of doing normal mode stuff.

**Comment by ConradIrwin** [comment]
Fixed by https://github.com/zed-industries/zed/pull/11778, which will ship to preview on Wednesday this week.
