### ISSUE TITLE
Template inline blame

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11097]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi! @mrnugget, Would it be possible to add a template to inline blame?

```
%ic - icon commit
%ca - committer avatar
%cn - committer name
%ce - committer email
%cr - committer date, relative
%cs - committer date, short format (YYYY-MM-DD)
...
```

Link pretty format: https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emHem

```json5
"inline_blame": {
      "enabled": true,
       "template": "%ca %cn, %cr <%ce>" //"%ic %cn, %cr" default
      // Sets a delay after which the inline blame information is shown.
      // Delay is restarted with every cursor movement.
      // "delay_ms": 600
}
```

**Comment by Moshyfawn** [comment]
I think it would be fair to merge this request with #10771 by adding this information to it. Let me know what you think.

**Comment by mrnugget** [comment]
Yeah, let's merge it with #10771.

**Comment by Moshyfawn** [comment]
Be sure to +👍 the other issue if you end up on this one.

Related to:
- #10771
