### ISSUE TITLE
extension market like vs code

### ISSUE THREAD

**Issue by relaxgameing** [zed-industries/zed#11125]
### Check for existing issues

- [X] Completed

### Describe the feature

I real like how zed is so fast but why i am still not switching to zed is because it doesnt have same extension marketplace like vscode because these extension allow the user to customise there work place according to there need. this is one of my reason to not switch completely to zed

**Comment by DissolveDZ** [comment]
Totally agree, I think they said something about how they want plugins in the future but I can't see it anywhere in the https://github.com/zed-industries/zed/issues/5393

**Comment by SomeoneToIgnore** [comment]
There's a collection of extensions to install that can be opened via `zed: extensions` command:
![image](https://github.com/zed-industries/zed/assets/2690773/ac3ca2a5-9cd9-4244-8131-25711733d167)

Current plugins fall into 2 categories:
* themes
* new languages (LSP + tree sitter highlights)

and there's no (yet) way to customize certain editor elements or a public editor API , but eventually there should be.
Most of those extensions are provided by the community members, details are in the https://github.com/zed-industries/extensions repository.

So, to me it seems that 

> extension market like vs code

is present, and 

> same extension marketplace like vscode

is not really possible, as Zed is different from VSCode and things will be different in general.
So, as generic as it is, this issue could be closed — feel free to create issues with more particular requests related to the marketplace contents.

**Comment by DissolveDZ** [comment]
Right but there could be an issue to let people know that it's being worked on.
I'm pretty sure he meant plugins to customize the editor and change it's functionality so basically an editor API like you mentioned.

**Comment by Moshyfawn** [comment]
Related #10795

**Comment by felipetesc** [comment]
What about adding the ability to search and order extensions accordingly predefined categories ?

**Comment by felipetesc** [comment]
> What about adding the ability to search and order extensions accordingly predefined categories ?

Not super fancy like VS Code market but it will help a little bit
