### ISSUE TITLE
Latex support in Markdown Preview

### ISSUE THREAD

**Issue by SteveLauC** [zed-industries/zed#11126]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if Zed could render the Latex snippets in Markdown documents, like VSCode does.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="758" alt="Screenshot 2024-04-28 at 20 16 45" src="https://github.com/zed-industries/zed/assets/96880612/19973ad8-43f4-4766-b1fd-38209b262891">

**Comment by SteveLauC** [comment]
Well, I think this is duplicate with #10899, though I think we should include the keyword `latex` in that issue so that one can search and find it.

**Comment by Moshyfawn** [comment]
Updated the title of #10899 👌

I'm closing this as a duplicate. Be sure to +👍 and add any additional information to the other thread.
