### ISSUE TITLE
file explorer window, . files are listed by default. 

### ISSUE THREAD

**Issue by foxjazz** [zed-industries/zed#11122]
### Check for existing issues

- [X] Completed

### Describe the feature

I am getting all the . git files listed in the file explorer.  No way to fix, tried using:   "file.exclude": ["**/.*"]
but it doesn't help.  
![zedIssue](https://github.com/zed-industries/zed/assets/867496/74ce4c78-f266-44d7-972d-2d7f4c55532c)

**Comment by Moshyfawn** [comment]
I believe the right setting is `file_scan_exclusions`.
