### ISSUE TITLE
ctrl-a doesn't move to beginning of line

### ISSUE THREAD

**Issue by algesten** [zed-industries/zed#11129]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On macOS, when I press `ctrl-a` to "Move to beginning of line", Zed jumps to the first non-whitespace character. Only if I press `ctrl-a` again does it jump to the actual beginning of line. What's worse is that if I press `ctrl-a` when I am at the (true) beginning, it jumps forward to the non-whitespace character again.

VSCode (correct behavior):

![vscode](https://github.com/zed-industries/zed/assets/227204/499d588b-44fe-4dfc-9d73-1ce72c218ad5)

Zed jumping to beginning of non-whitespace (wrong behavior):
![zed1](https://github.com/zed-industries/zed/assets/227204/28a20309-9cfc-41ac-97e4-cde7cbe83385)

Zed jumping back/forth on ctrl-a (pathological):
![zed2](https://github.com/zed-industries/zed/assets/227204/b979e511-e289-4397-a335-70bdea95fe69)

### Environment

Zed: v0.132.3 (Zed)
OS: macOS 13.6.6
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
This behaviour seems to be described in this enhancement ticket. Let me know if it'd be fair to close this issue in favour of #7863.

**Comment by failable** [comment]
Isn't that desired behavior??? In other editors, one would even require an extension to achieve the same effect (e.g. https://github.com/alezost/mwim.el for Emacs). I've thought this feature is built in Zed.

**Comment by algesten** [comment]
@Moshyfawn I don't know. That other issue seems to be about deletion. I talk about moving. Maybe they are the same underlying problem?

@failable I don't mind some people want this behavior. I've used code editors since the early 90s and ctrl-a/e for beginning/end of line is so deep in my muscle memory that it stopped me going further with Zed currently.

**Comment by algesten** [comment]
Fixed by #15981
