### ISSUE TITLE
Terminal `alt-delete` trigger not taking effect in lazygit

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#11120]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open lazygit then commit, trigger `alt-delete` will not delete a character
But in vscode this is normal

/cc @mikayla-maki 

Zed:

https://github.com/zed-industries/zed/assets/45585937/71834d74-6c35-4e58-b7ac-bdc8b0359abd

VScode:

https://github.com/zed-industries/zed/assets/45585937/553829df-4721-4003-9e7c-e3a1be78a1aa

### Environment

Zed: v0.133.3 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by d1y** [comment]
FWIW: it seems to work without lazygit

https://github.com/zed-industries/zed/assets/45585937/f00bf894-58af-4de5-a0c7-eed116da273a

**Comment by d1y** [comment]
I downloaded `alacritty` and found that it also doesn’t work.
I don’t know if this requires configuration?

`brew install alacritty`

https://github.com/zed-industries/zed/assets/45585937/d47c2038-7fea-4a16-9164-a43d8fb54721

**Comment by CharlesChen0823** [comment]
try this [alacritty](https://github.com/alacritty/alacritty/issues/93#issuecomment-1364783147)

**Comment by Leleat** [comment]
Maybe related: On Fedora 40 (with GNOME 46) and a bash shell `Alt`+`Del` deletes the whole (as expected) but it also inserts `elete` (i. e. "delete" without the d) for whatever reason... Or is it unrelated and should I open a new issue?

**Comment by notpeter** [comment]
@Leleat Please open a new issue.

I believe what you need is this in your settings:
```json
{
  "terminal": {
    "option_as_meta": true
  }
}
```

meta+backspace (e.g. alt-delete) is delete work, but it requires `option_as_meta` to be enabled in your settings.
