### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by cholwell** [zed-industries/zed#11131]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

certain files wont save unsure why some are affected some arent

### Environment

Zed: v0.132.3 (Zed)
OS: macOS 14.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

press save and it reverts 
press undo and it comes back
press save and it revers
etc

https://github.com/zed-industries/zed/assets/53612993/c801f2aa-ea8c-45ed-9713-f6a20c78f838

**Comment by cholwell** [comment]
turning language server off fixes it so may be that

odd though

**Comment by Moshyfawn** [comment]
This sounds very similar to #7846. Let me know if you think it'd be fair to close this issue in favour of the existing one.

**Comment by cholwell** [comment]
@Moshyfawn agreed that it sounds the same, although given there are two different languages affected and both can be resolved by turning off language mode might be a generic issue is better? Idk

**Comment by mmmoli** [comment]
Getting this too. Weird

**Comment by 0legg** [comment]
Happens for me both for Gradle and Kotlin files

**Comment by notpeter** [comment]
I'm closing this as stale. The behavior described will occur when there is a misconfigured formatter (e.g. formatting via filename and not via stdin/stdout):

https://zed.dev/docs/configuring-languages#configuring-formatters

If you run into this you can always disable with `"format_on_save": "off"` per language in your settings and/or manually trigger "Save without Format" via the command palette.

If you are still having this issue please open a new issue with steps to reproduce and any formatter related settings.

Thanks for reporting.

**Comment by fzwoch** [comment]
Is there a follow up issue in this one?

I have the same with C/C++ code on Linux. Usually everything is fine, then all of a sudden sometimes when I save the code gets reverted to the last state instead. Press undo, save again, again reverted. I'll wait a couple of seconds, then the save gets through. Usually I can continue normally after that. Perhaps this is triggered more often when i very quickly open a file, edit and save it.

It happens really rarely and unpredictably, but is still very annoying when it happens.
