### ISSUE TITLE
Allow extensions to define tasks

### ISSUE THREAD

**Issue by agent3bood** [zed-industries/zed#11133]
### Check for existing issues

- [X] Completed

### Describe the feature

This is a feature request.

Since the addition of extensions recently I was looking to replicate some features found in other IDEs extensions, to support framework specific tasks, for example 'run tests' and 'run app'.

Zed does have the ability to define static tasks via `language::ContextProvider`, I suggest adding `fn context_provider(&self) -> Result<Option<language::ContextProvider>>` to the `Extension` trait to allow for custom tasks.

**Comment by mohsin** [comment]
Wouldn't it be better to allow automatically adding tasks based on the project? Zed already auto-detects languages out of the box so it would make sense to auto-detect project type and setup common tasks based on the project type. For example, an Android project would typically have Build Project, Run, Rebuild Project, Generate APK, etc.

**Comment by agent3bood** [comment]
> Wouldn't it be better to allow automatically adding tasks based on the project? 

This is exactly what extensions should do, it define tasks then zed will call the extension to get those tasks. An extension will detect the project type and return the task accordingly.

**Comment by agent3bood** [comment]
I think this can be closed now 

ref -> https://zed.dev/blog/zed-decoded-tasks
