### ISSUE TITLE
add an option to merge the tab bar and title bar

### ISSUE THREAD

**Issue by julyfun** [zed-industries/zed#11146]
### Check for existing issues

- [X] Completed

### Describe the feature

An compact tab bar will allow more vertical spaces (especially on small screens) as the title bar is a bit empty.

### If applicable, add mockups / screenshots to help present your vision of the feature

Just like in Safari 👍🏻:

<img width="838" alt="image" src="https://github.com/zed-industries/zed/assets/43675484/570a3e55-567c-4df4-9601-424aaa07d2c0">

So maybe you can add an option to do this 😊:

<img width="835" alt="image" src="https://github.com/zed-industries/zed/assets/43675484/cf1092d8-2944-494f-b122-7da2b7f4246d">

**Comment by d1y** [comment]
Here? https://github.com/zed-industries/zed/pull/7356#issuecomment-2067916861

**Comment by julyfun** [comment]
> Here? [#7356 (comment)](https://github.com/zed-industries/zed/pull/7356#issuecomment-2067916861)

thank you!  🤝 I'm going to close this
