### ISSUE TITLE
Rust Analyzer will cause the application to recompile all the dependency libs for every Cargo test run

### ISSUE THREAD

**Issue by crazybits** [zed-industries/zed#11152]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

make tiny update on the specified test case and re-run the cargo test will make the application to re-compile all the libs

### Environment

OS :Mac OS13.6
rustc: 1.77.2
cargo :1.79.0-nightly

### If applicable, add mockups / screenshots to help explain present your vision of the feature

should only re-compile  the update files rather than all the code

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

NA

**Comment by osiewicz** [comment]
Does it happen for all Rust projects for you? Or just some specific one?
Also re: 
> should only re-compile the update files rather than all the code
It is not enough to recompile the files that you've updated; RA should recompile all crates that depend on a crate you've changed.

**Comment by crazybits** [comment]
not tested on other projects. i run the `cargo test test_case` manually, looks like the Rust Analyzer will change the cache, stop Rust Analyzer  could solve the issue

**Comment by osiewicz** [comment]
I'm not sure if that's caused by Zed; could you post your settings.json? Maybe there's something in there that's causing this (I'm mostly thinking of RA initialization_options).

**Comment by SomeoneToIgnore** [comment]
It's rust-analyzer defaults that run `cargo check --workspace --all-targets` on each save, and https://zed.dev/docs/languages/rust#more-server-configuration has some pointers on how to reconfigure this.
