### ISSUE TITLE
linux compile error: bound_map

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#11166]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/12579229/33652827-2efa-4639-a5e4-661e8cafbabc)

### Environment

ubuntu 22.04

**Comment by Moshyfawn** [comment]
This appears to be a duplicate issue.

Duplicate of
- #10980
