### ISSUE TITLE
Permalinks support enterprise github repository

### ISSUE THREAD

**Issue by tkolleh** [zed-industries/zed#11160]
### Check for existing issues

- [X] Completed

### Describe the feature

Support for generating permalinks for enterprise Github repositories. 
To reproduce:
* Open project linked to an enterprise Github repo
* Type `:copy permalink`
* See the error "failed to parse Git remote URL"

**Comment by maxdeviant** [comment]
One complication here is that for self-hosted instances of GitHub/GitLab/etc. we can't tell which one is being used based on the URL alone, as the URL could be something like `git.bigco.com`.

**Comment by Moshyfawn** [comment]
I can copy a permalink to a link in a private Enterprise repository hosted on GitHub.

**Comment by jaydenseric** [comment]
Using Zed v0.136.2, attempting:

<img width="300" alt="Screenshot 2024-05-23 at 9 47 12 AM" src="https://github.com/zed-industries/zed/assets/1754873/86afda32-4f59-49e9-af97-88577e34c7ad">

Results in:

<img width="462" alt="Screenshot 2024-05-23 at 9 46 09 AM" src="https://github.com/zed-industries/zed/assets/1754873/91227b55-a6ad-4a85-9150-2a02b940ea1b">

Our Git remote doesn't look special, it's in the format:

```
https://jaydenseric@github.com/[redacted org name]/[redacted repo name].git
```

**Comment by tkolleh** [comment]
I saw the issue when attempting to link to a self-hosted instances of GitHub/GitLab/etc.

**Comment by notpeter** [comment]
We've merged preliminary support for detect custom Gitlab instances (only if they include `gitlab` in the hostname) in:
- https://github.com/zed-industries/zed/pull/19909

**Comment by maxdeviant** [comment]
> Using Zed v0.136.2, attempting:
> 
> <img alt="Screenshot 2024-05-23 at 9 47 12 AM" width="300" src="https://private-user-images.githubusercontent.com/1754873/332990131-86afda32-4f59-49e9-af97-88577e34c7ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzcyODEsIm5iZiI6MTczMDIzNjk4MSwicGF0aCI6Ii8xNzU0ODczLzMzMjk5MDEzMS04NmFmZGEzMi00ZjU5LTQ5ZTktYWY5Ny04ODU3N2UzNGM3YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMjEyMzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVmNzg0YTUzYjc5NTkyYjlkMjIwNGRkNWZmMDdiZGU3MzU4ZDkyZGQ4OGM4NTFmZWY2NmE3OWRlMjUzMmZmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xxQzs912_G1m3y6XrjmSYsdgQwB0NbLWKzE58rC8VHQ">
> Results in:
> 
> <img alt="Screenshot 2024-05-23 at 9 46 09 AM" width="462" src="https://private-user-images.githubusercontent.com/1754873/332990159-91227b55-a6ad-4a85-9150-2a02b940ea1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzcyODEsIm5iZiI6MTczMDIzNjk4MSwicGF0aCI6Ii8xNzU0ODczLzMzMjk5MDE1OS05MTIyN2I1NS1hNmFkLTRhODUtOTE1MC0yYTAyYjk0MGVhMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMjEyMzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY0NGQ0MjBhZGEwMzI4MDVmNTZlNzQxMzdmMWViNTkwYmQwOGZiN2VjYjM5MzNlMWM4NDJiYmM4NzE2MDczNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eyR_gRbm6ptjUW6DMT00YkY34X0tnbKwY-MlTimeYKk">
> Our Git remote doesn't look special, it's in the format:
> 
> ```
> https://jaydenseric@github.com/[redacted org name]/[redacted repo name].git
> ```

This should be fixed by https://github.com/zed-industries/zed/pull/19924.
