### ISSUE TITLE
[Windows] Settings EoF / Element not found on reading user credentials

### ISSUE THREAD

**Issue by sundayLOOKplants** [zed-industries/zed#11185]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed release version can't start after compile:
```   
     Finished release [optimized + debuginfo] target(s) in 55m 30s
     Running `target\release\Zed.exe`
error: process didn't exit successfully: `target\release\Zed.exe` (exit code: 0xffffffff)
```

...

```
C:\Users\User\dev\zed>cargo run --release
warning: zed@0.134.0: Info: using '5ef75919f09e31c28b75c09e695946b6c4d9c3ee' hash for ZED_COMMIT_SHA env var
    Finished release [optimized + debuginfo] target(s) in 17.67s
     Running `target\release\Zed.exe`
error: process didn't exit successfully: `target\release\Zed.exe` (exit code: 0xffffffff)

```

### Environment

Windows 10
8GB RAM

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```   2024-04-29T20:56:02+02:00 [INFO] ========== starting zed ==========
2024-04-29T20:56:02+02:00 [INFO] Use Segoe UI                         as UI font.
2024-04-29T20:56:02+02:00 [INFO] Using direct write text system.
2024-04-29T20:56:02+02:00 [INFO] Opening main db
2024-04-29T20:56:02+02:00 [INFO] Using git binary path: None
2024-04-29T20:56:02+02:00 [ERROR] crates\zed\src/main.rs:219: SHELL environment variable is not assigned so we can't source login environment variables

Caused by:
    environment variable not found
2024-04-29T20:56:02+02:00 [ERROR] crates\settings\src\settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-04-29T20:56:02+02:00 [INFO] use fallback vsync function
2024-04-29T20:56:02+02:00 [INFO] primaly refresh rate is 60Hz
2024-04-29T20:56:02+02:00 [INFO] expected interval is 16ms
2024-04-29T20:56:02+02:00 [ERROR] crates\zed\src\zed.rs:660: EOF while parsing a value at line 1 column 0
2024-04-29T20:56:03+02:00 [INFO] Opening main db
2024-04-29T20:56:03+02:00 [INFO] installing extension html latest version
2024-04-29T20:56:03+02:00 [ERROR] C:\Users\User\dev\zed\crates\client\src/client.rs:1477: Element not found. (0x80070490)
2024-04-29T20:56:03+02:00 [WARN] Rejected for device extension "VK_KHR_dynamic_rendering" not supported
```

**Comment by sundayLOOKplants** [comment]
Attaching the log failed

**Comment by the-jasoney** [comment]
I've also gotten `0xffffffff` error codes recently but it works if I just restart it

**Comment by OnayoMoro** [comment]
I've also gotten this error "error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)" after compiling with "cargo run" and "cargo run --release". I've also tried running "rustup update", "cargo clean" and "cargo build" before compiling.

**Comment by THZrry** [comment]
Hello. I tried, compared my log file with other log files in other issues, and found something.

First, environment variable, zed seems to search `PATH` and `Shell` variables in environment. 
In one log file (in issue # 9788) I found it was `zsh` so I set it to `powershell.exe`, then `environment variable not found` disappeared from my log files. I think maybe it is related with msys2's not installed.

Another issue, file not found. 
There're 3 error messages like `crates\fs\src/fs.rs:537: Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }` in my log file. My git is mingit without git bash, and my path is `%PROGRAMFILES%/gitwin/cmd`, which is different from its default path. When I rename gitwin to git (default name), the error message turned to 2 pieces even if I rename git to gitwin. This is strange, and I do not know why.

My computer has a poor performance and disk space, so I haven't try build it my self and try a prebuilt package.

**Comment by gaolin-nj** [comment]
@THZrry Hi, as you mentioned, you found the envrionment is zsh and set it to powershell. And I am facing the same question, can I ask what is the envirment variable name to set as powershell? Thanks a lot.

**Comment by THZrry** [comment]
That was `Shell`. I set that to `powershell.exe` and then ran successfully in another computer with a better GPU ( which have a better support of vulkan ). I guess `Shell` is only used for debug, because that command was
```bash
......Shell -l -i -c "printf '%s' ZED_LOGIN_SHELL_START; /usr/bin/env; exit 0;"
```
which is seemed not necessary. So if your computer have a complete support of vulkan1.2, you may set `Shell` to just an executable.

**Comment by notpeter** [comment]
I'm going to close as as unactionable since this is a post-compile error encountered 7 months ago on windows.  If you are having trouble running after compiling on windows please search for [zed issues label:windows](https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+label%3Awindows) and make sure you've read and followed the steps in the [Windows Development Docs](https://zed.dev/docs/development/windows).

Thanks fore reporting.
