### ISSUE TITLE
TASK_DELIMITER is incorrectly displayed in the terminal.

### ISSUE THREAD

**Issue by mrzzmrzz** [zed-industries/zed#11184]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I found that TASK_DELIMITER is displayed incorrectly in the terminal. It can be displayed correctly when using Zed Mono and Zed Sans, but it shows errors in other cases. Please refer to the following picture.

Monaco
<img width="761" alt="image" src="https://github.com/zed-industries/zed/assets/36831062/6b4e6133-d2be-4e2c-8591-2a5d33ba0180">

Zed Mono
<img width="675" alt="image" src="https://github.com/zed-industries/zed/assets/36831062/e891bb77-ae9a-4827-b105-d986668cfff4">

### Environment

Zed: 0.132.4
macOS: 12.7.4 (21H1123)

**Comment by Mrz-zz** [comment]
I checked on macOS 14.4 and the issue does not exist.
