### ISSUE TITLE
Zed CLI does not work when Zed is already open

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/zed#11199]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Nothing happens when running a command like the following, while Zed is running:
```
/Applications/Zed.app/Contents/MacOS/Zed file:///example:4:2
```

This makes it impossible to use tools like [Svelte Inspector](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/inspector.md) which I heavily rely on

### Environment

Zed: v0.132.4 (Zed)
OS: macOS 13.6.4
Memory: 32 GiB
Architecture: x86_64

**Comment by mrnugget** [comment]
> /Applications/Zed.app/Contents/MacOS/Zed file:///example:4:2

That's not the Zed CLI. The CLI is `/Applications/Zed.app/Contents/MacOS/cli`. You can use this in the menu bar 
![screenshot-2024-04-30-14 04 27@2x](https://github.com/zed-industries/zed/assets/1185253/a7f3c634-deb2-4fbb-b17f-2a78f9cf1fd2)

or the `cli: install` command to install that `cli` binary as `zed` in `/usr/local/bin`.

**Comment by probablykasper** [comment]
Aah ok, is it intended that both `cli` and `zed` accept a `path:line:col`, but with different behaviour? The help menus are worded the same way, so it's not clear that when `zed` will no-op

`/Applications/Zed.app/Contents/MacOS/zed --help`:
```
Usage: zed [OPTIONS] [PATHS_OR_URLS]...

Arguments:
  [PATHS_OR_URLS]...
          A sequence of space-separated paths or urls that you want to open.
          
          Use `path:line:row` syntax to open a file at a specific location. Non-existing paths and directories will ignore `:line:row` suffix.
          
          URLs can either be file:// or zed:// scheme, or relative to https://zed.dev.
```

`/Applications/Zed.app/Contents/MacOS/cli --help`:
```
Usage: cli [OPTIONS] [PATHS_WITH_POSITION]...

Arguments:
  [PATHS_WITH_POSITION]...
          A sequence of space-separated paths that you want to open.
          
          Use `path:line:row` syntax to open a file at a specific location. Non-existing paths and directories will ignore `:line:row` suffix.
```

**Comment by drochag** [comment]
hey, I'm having the same issue, even after using `cli: install`
Zed needs to be closed in order to use it on terminal, otherwise nothing happens

**Comment by mrnugget** [comment]
@drochag to be clear, you're using `/Applications/Zed.app/Contents/MacOS/cli my_file.txt` and nothing happens?

**Comment by drochag** [comment]
nope, I'm using `zed my_file.txt` or `zed .` or `zed ./folder_name` after running `cli: install`
also this is supposed to be correct
```
$ which zed
/usr/local/bin/zed
```

video here
https://github.com/user-attachments/assets/916f2bcb-af39-45d5-a6e6-e80e3a526773

notice how it tries to open Zed, but since it's already opened nothing else happens

**Comment by mrnugget** [comment]
That's very weird. Is there anything the logs? (`zed: open logs`)

**Comment by drochag** [comment]
this is what appears on `zed: open logs` whenever Zed is open and I run the command

```

2024-09-27T09:51:11.820831-06:00 [INFO] ========== starting zed ==========
2024-09-27T09:51:11.822349-06:00 [INFO] Opening main db
2024-09-27T09:51:11.82396-06:00 [INFO] Opening main db
2024-09-27T09:51:11.921653-06:00 [INFO] Got instance handshake
2024-09-27T09:51:47.870234-06:00 [INFO] ========== starting zed ==========
2024-09-27T09:51:47.87173-06:00 [INFO] Opening main db
2024-09-27T09:51:47.873403-06:00 [INFO] Opening main db
2024-09-27T09:51:47.990886-06:00 [INFO] Got instance handshake
```

**Comment by drochag** [comment]
nope, actually on both of them work correctly, but when using `zed my-folder` directly, it only works when Zed is closed and once

**Comment by drochag** [comment]
in case this is useful
```
$ ls -ln /usr/local/bin/ | grep zed
lrwxr-xr-x@ 1 502  80    40B Mar 13  2024 zed@ -> /Applications/Zed.app/Contents/MacOS/cli
```

**Comment by mrnugget** [comment]
> nope, actually on both of them worked correctly, but when using `zed my-folder` directly, it only works when Zed is closed and once

Wait, what?

1. `/usr/local/bin/zed my-folder` - works, even when Zed is open, yes?
2. `/Applications/Zed.app/Contents/MacOS/cli my-folder` - works, even when Zed is open, yes?
3. `zed my-folder` - does **not** work when Zed is open?

That... seems impossible, since `/usr/local/bin/zed` _is` the `cli`, no?

**Comment by mrnugget** [comment]
Sorry, I was super stuck in the whole SSH thing right now. Let me think about this again. Would you be open to hopping on a pairing session in Zed/Zoom/... to debug this? Also, would you be willing to compile & run Zed from source? Because if so, I can put a ton of log statements in a build for you.

**Comment by drochag** [comment]
Sure thing ! happy to help
