### ISSUE TITLE
CJK word-wrap not correct

### ISSUE THREAD

**Issue by iptton** [zed-industries/zed#11202]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When mixing Chinese and English, line breaks behave incorrectly

<img width="358" alt="image" src="https://github.com/zed-industries/zed/assets/97447/abc38943-3dd5-4aa0-a580-2f71e12e8c02">
          
It should not break new line at the red arrow

### Environment

Zed: v0.132.4 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

**Comment by zhang60626** [comment]
duplicate https://github.com/zed-industries/zed/issues/4623
