### ISSUE TITLE
Super slow "replace all" in a 5M JSON file

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#11210]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Search `{nft_collection}` (about 3000+ occurrences) and replace them`{nft_collection_name}` in this file: [data.json](https://github.com/zed-industries/zed/files/15165719/merged_questions.json) .

The CPU goes 100% and never finish replacing. Finally I have to kill Zed.

As comparison, I finish the job in Emacs under 0.2 seconds.

### Environment

Zed: v0.133.5 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
This now takes <1sec. Perhaps fixed by 
- https://github.com/zed-industries/zed/issues/13455
