### ISSUE TITLE
Make `editor: revert selected hunks` more discoverable

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#11267]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

We have the ability to revert hunks back to their original source, but users aren't aware of it. We should add some UI around this.

### Environment

Zed: v0.134.0 (Zed Nightly 6b55a6f0e1dec0c0c781d78ce2dc5497ece3f826)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
@iamnbutler @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
Current mockups from @\iamnbutler  (mock key binding values were chosen arbitrary)

![image](https://github.com/zed-industries/zed/assets/2690773/4630fe6b-d9ff-43a6-8317-aef501006523)

**Comment by SomeoneToIgnore** [comment]
Not in an exact way as the mockup, but we've arrived to 

![image](https://github.com/user-attachments/assets/1f2deaa0-7286-4130-8fd1-2c607a91b96d)

which seems to cover what's been asked for here.
