### ISSUE TITLE
Support filterText provided by LSP Server when filtering completions

### ISSUE THREAD

**Issue by wlh320** [zed-industries/zed#11299]
### Check for existing issues

- [X] Completed

### Describe the feature

According to [the LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion), if the `completionItem` responsed by an LSP server contains a `filterText`, it should be used for completion filtering instead of the `label`. I think that implementing this feature will help improve the interaction with the LSP server.

When searching `filterText` or `filter_text` in this repo, I  didn't find any implementations or discussions about this feature. If I missed something, please ignore this issue.

Thank you!

### If applicable, add mockups / screenshots to help present your vision of the feature

For example, if a `completionItem` looks like `{ "label": "foo", "filterText": "foobar" }`, this item should be shown to the user if they trigger a completion request at  `bar|`

**Comment by osiewicz** [comment]
We do make use of filterText in https://github.com/zed-industries/zed/blob/7bc1025d912b7ad2aac4f45802ce4a19f5e49bef/crates/project/src/project.rs#L10303 (and https://github.com/zed-industries/zed/blob/7bc1025d912b7ad2aac4f45802ce4a19f5e49bef/crates/language/src/language.rs#L1480)

**Comment by wlh320** [comment]
Thank you! 

Searching with GitHub didn't show the matching in `project.rs`, so I thought `filter_text` was not used. I'm sorry. 

However, I noticed that `filter_text` is only used when it is a sub string of `label`.  Is it possible that `filter_text` is longer than `label` or even they are completely different?

**Comment by osiewicz** [comment]
No worries, GH search is sometimes wacky for me too. =)

Yeah, no clue tbh; I haven't seen that happen with rust-analyzer, but it looks that logic has not changed a bit in 2 years (and the commit that introduced it does not shed light on why that's the case: https://github.com/zed-industries/zed/pull/393/commits/439d12cb8550a095c43c7e2eaa425d4fc4df7ec5#diff-1c9ec9ff065324aa7fe19fb781efaf43084b0bdc66573ce10de2e6ac7891a23d)

**Comment by wlh320** [comment]
OK. It is reasonable because the LSP spec does not specify how to use filterText. I'll close this issue until I find a case where this check is unnecessary. Thank you.
