### ISSUE TITLE
Open current line on GitHub (or other source control site)

### ISSUE THREAD

**Issue by chadoh** [zed-industries/zed#11304]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim, I have a shortcut mapped to open the current line in GitHub:

```vim
 nnoremap <leader>o :!echo `git url`/blob/`git rev-parse --abbrev-ref HEAD`/%\#L<C-R>=line('.')<CR> \| xargs open<CR><CR>
```

It's super handy! When I use Zed, I find myself opening files in vim in Zed's terminal so I can do this. 

If there's an existing extension that can do this for me, I'll install it and you can close this. Otherwise, is this a feature y'all could add? I'd imagine accessing it from a context-click, or from the little lighting bolt in the gutter.

Thanks!

**Comment by d1y** [comment]
There is only one available command to copy the link of the current line: `editor::CopyPermalinkToLine`

**Comment by baldwindavid** [comment]
@chadoh I have the following keymap for similar...

```json
  {
    "context": "Editor && VimControl && !VimWaiting && !menu",
    "bindings": {
      "space g p": "editor::OpenPermalinkToLine",
    }
  }
```

**Comment by SomeoneToIgnore** [comment]
Yes, please use the `OpenPermalinkToLine` action.

**Comment by chadoh** [comment]
Thanks all! That's perfect.
