### ISSUE TITLE
Code actions item should have the same padding horizontally as vertically

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#11307]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Now it's looking weird :)

![image](https://github.com/zed-industries/zed/assets/45122321/a5809e1b-71a3-4c61-8a54-ce2601d4c9aa)

### Environment

Zed: v0.134.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I believe this has been fixed at some point in the last six months. 
<img width="326" alt="Screenshot 2024-11-05 at 18 50 53" src="https://github.com/user-attachments/assets/c9882128-12f1-488e-b3d9-778ee35ccde8">

If I've misunderstood, please comment and i'm happy to reopen. Thanks for reporting!
