### ISSUE TITLE
Cannot close "Find in Project" tab, when it contains search result in an untitled file

### ISSUE THREAD

**Issue by Zollerboy1** [zed-industries/zed#11328]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open a project in Zed
- Create a new untitled file not related to the project (`File>New`/<kbd>⌘</kbd><kbd>N</kbd>)
- Write some text (e.g. "abc") in that file without saving it
- Open the "Find in Project" tab (`Edit>Find in Project`/<kbd>⇧</kbd><kbd>⌘</kbd><kbd>F</kbd>)
- Search for the text previously written in the unsaved file, that file will show up in the search results
- Close the file without saving it

Now the "Find in Project" tab cannot be closed anymore, probably because it thinks that it has unsaved changes (the blue dot is visible in the tab header). This also means that the whole workspace cannot be closed/restarted anymore, as it thinks that it contains unsaved changes, but has no way of saving them. The only way to exit the editor is by force quitting the application.

### Environment

Zed: v0.133.5 (Zed)
OS: macOS 13.6.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15195586/Zed.log)

**Comment by notpeter** [comment]
I can no longer reproduce with a current Zed, so I believe this has been fixed.
If this is in error, please comment and I'm happy to reopen.

See also:
- https://github.com/zed-industries/zed/issues/11661
