### ISSUE TITLE
Project panel: make lexical file name sorting optional

### ISSUE THREAD

**Issue by kud1ing** [zed-industries/zed#11349]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have files that have UUIDs for file names. In the project panel the leading zeros ("0") seem to be ignored sometimes.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="365" alt="Bildschirmfoto 2024-05-03 um 14 43 07" src="https://github.com/zed-industries/zed/assets/391975/b71e4f3c-98e1-472c-845e-7d6da7760401">

**Comment by kud1ing** [comment]
Actually it's even more complicated than that.

<img width="340" alt="Bildschirmfoto 2024-05-03 um 14 50 52" src="https://github.com/zed-industries/zed/assets/391975/674f38b2-cbf1-41d7-aa77-5434cb5c1f95">

**Comment by JosephTLyons** [comment]
From this PR:

- https://github.com/zed-industries/zed/pull/8486

These aren't being sorted directly based on the characters, but I think Zed is parsing as much of the prefix as it can into an integer. If there are leading zeros, they get dropped and it stops parsing when it gets to the first non-numeric character. So the first few files would end up being seen as these numbers:

7050
7556
7750
8111
8417
8564
9034
9303
15549
16378

That being said, I wonder if we should have a setting that switches between this mode and the normal sorting you'd initially expect.

cc @mrnugget

**Comment by kud1ing** [comment]
Ah, this makes sense. Thank you.

**Comment by kud1ing** [comment]
For what it's worth, IntelliJ has the same behaviour, which had puzzled me, too.

<img width="336" alt="Bildschirmfoto 2024-05-04 um 10 25 09" src="https://github.com/zed-industries/zed/assets/391975/dbf37715-6e15-478c-b281-a031177792ad">

**Comment by mrnugget** [comment]
Yep. I think this is then a duplicate of https://github.com/zed-industries/zed/issues/4533

**Comment by kud1ing** [comment]
Agreed.
