### ISSUE TITLE
Allow for setting Vim Setting `splitright`

### ISSUE THREAD

**Issue by jvanbaarsen** [zed-industries/zed#11342]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim you can set the flag `splitright`, this makes the command `:vsplit` to split a pane to the right instead of the left. It would be great if we could set this flag somehow as well.

**Comment by ConradIrwin** [comment]
@jvanbaarsen This is a great idea. If you'd like to pair on it, please find time here: https://calendly.com/conradirwin/pairing. We have some general actions that allow "open in split", so we could add something like this (and splitbelow) outside of vim mode too.

**Comment by Tobbe** [comment]
Came here looking for the exact same thing! I'll pair on it 🤝

**Comment by jvanbaarsen** [comment]
@Tobbe I'd be curious to work on this! Shall we set a moment to pair on this?

**Comment by Tobbe** [comment]
@jvanbaarsen sorry for the confusion. I already scheduled a time with @ConradIrwin

**Comment by jvanbaarsen** [comment]
@Tobbe No probs!
