### ISSUE TITLE
Dark themes: low contrast for hovering information window

### ISSUE THREAD

**Issue by kud1ing** [zed-industries/zed#11351]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The window that appears when one hovers over something has a low contrast in some dark themes.

Since the window should be darkish in a dark theme, maybe pronounce the frame a little more?

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="949" alt="Bildschirmfoto 2024-05-03 um 15 01 51" src="https://github.com/zed-industries/zed/assets/391975/6d5265a8-e3fb-4a3a-a70e-e6a0d35e88b1">

<img width="917" alt="Bildschirmfoto 2024-05-03 um 15 04 07" src="https://github.com/zed-industries/zed/assets/391975/30f8e410-c86b-4692-af78-d22d8be5546f">

<img width="822" alt="Bildschirmfoto 2024-05-03 um 15 04 58" src="https://github.com/zed-industries/zed/assets/391975/ee4526cd-4a30-4432-bd46-f87483d44932">

**Comment by notpeter** [comment]
Thanks for reporting this, I'm going to close in favor of:
- https://github.com/zed-industries/zed/issues/15521

I've snagged your screenshots and included them there.
Please subscribe to track progress and vote 👍 to increase visibility. 
Thanks for reporting.
