### ISSUE TITLE
(zed.dev) Code can overflow on website releases page

### ISSUE THREAD

**Issue by vandorsx** [zed-industries/zed#11384]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Related to #10328**

On small width viewports code often overflows. This causes the page to be zoomed out:

<img src="https://github.com/zed-industries/zed/assets/140852203/33fb5aaf-dfef-40ca-ad9e-cfdc6b4c9d92" width="200">

<br> 

Adding the `break-all` Tailwind class should do the trick:

```html
<code class="bg-accent-blue/10 -mx-1 py-0.5 px-1 font-mono text-sm break-all"> ... </code>
```

### Environment

iOS Safari

**Comment by danilo-leal** [comment]
Hey; this should be fixed now—thanks for the report!
