### ISSUE TITLE
Multi-buffer: excerpt -> jump to file discoverability

### ISSUE THREAD

**Issue by nixpulvis** [zed-industries/zed#11397]
### Check for existing issues

- [X] Completed

### Describe the feature

After using the find all function to search for matches and returning multiple matches within the same file, I would like to navigate to other matches by clicking on them. Unless I'm missing something, currently only the first match is opened when you click on the file name.

Sorry if this was already mentioned, I tried to search the issues. Or if I'm just missing the functionality.

**Comment by Moshyfawn** [comment]
If I understand your request correctly, you're looking for that thin line that you can press to go to the next definition on that particular line. Let me know if that's what you're looking for.

<img width="1039" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/15980bf8-f63c-4caa-a33a-91512c019310">

**Comment by nixpulvis** [comment]
Indeed that is the functionality I was looking for!

Just my two cents, but perhaps a small redesign of this interface could benefit users.

A. Allow collapsing of the top filename match (useful for searches with a lot of matched files)
B. Jump to match when clicking on the match itself

I appreciate being able to treat the match buffer more or less like a normal buffer, but given that the matched text is already specially formatted, it makes sense to me to also give it a special action.

I also noticed, if I click on the "Expand Excerpt" button it will show duplicate lines if the matches are near each other. This could be optimized to simply remove the line between the matches.

**Comment by JosephTLyons** [comment]
Adding this to the papercuts project, as we've found that a lot of users don't know they can jump from mullt-buffer to buffer.

**Comment by nixpulvis** [comment]
I'm happy to test or give feedback as a new user here. I'm loving Zed and using it more and more now.

**Comment by JosephTLyons** [comment]
Really appreciate the feedback here, but I'm going to close this out for:

- https://github.com/zed-industries/zed/issues/9718

I have it on our papercuts project as well. If you think its missing any details, feel free to add it as a comment, and make sure to upvote with 👍.
