### ISSUE TITLE
The panel state is toggled every time the editor is opened

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#11394]
It looks like with Zed Preview the panel state is toggled every time the editor is opened.

## Environment

Zed: v0.134.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

![CleanShot 2024-05-02 at 23 22 03@2x](https://github.com/zed-industries/zed/assets/57976101/4f0d9759-cd35-485c-a098-fd0193a19b9c)

Ref: bc0dd3aecbcf009baf1226cd791a98ce4f6d785d

_Originally posted by @jizhi0v0 in https://github.com/zed-industries/zed/issues/6407#issuecomment-2090803399_

**Comment by osiewicz** [comment]
Can you repro it with the latest Preview?

**Comment by Moshyfawn** [comment]
> Can you repro it with the latest Preview?

I.. don't think so? Unless I forgot how to bring it out 🤭

**Comment by osiewicz** [comment]
Ah, oki. I can't repro it either, so I guess we can close this ticket?

**Comment by Moshyfawn** [comment]
Yea, let's close. Anyone following this thread, please test Zed Preview 0.138.4 or higher to see if you can still reproduce the problem and what the steps are if you do.

**Comment by JosephTLyons** [comment]
I swore I hit this within the last 7 when Zed Dev opened after a compile - but I can't be sure.
