### ISSUE TITLE
Option to open directory/file in project panel on first click

### ISSUE THREAD

**Issue by XDeme1** [zed-industries/zed#11396]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, the project panel requires 2 clicks to open a file/directory after losing focus.

If possible, I suggest adding an option to allow users to open files/directory in 1 click after losing focus.

**Comment by mikayla-maki** [comment]
I believe this bug has been fixed in https://github.com/zed-industries/zed/pull/11371

**Comment by dinhphieu** [comment]
@mikayla-maki sorry to revive an old thread, but is it possible to do the inverse? Open files in the editor from the project tree only on 2 clicks?
