### ISSUE TITLE
LSP textDocument/didOpen Message Missing Language ID

### ISSUE THREAD

**Issue by ejjonny** [zed-industries/zed#11399]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

LSP client message textDocument/didOpen passes an empty string for textDocument.languageId.

This field is apparently necessary for language servers that support multiple languages such as sourcekit.

[LSP object for reference](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem)

I believe it is crates/project/src/project.rs line ~2383 or line ~3682 defaulting on a None value.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Nice catch, thank you.
https://github.com/zed-industries/zed/pull/11412 is supposed to fix that, using a lowercased language name as a fallback now, will be released with Zed 0.135

**Comment by ejjonny** [comment]
Awesome! Thank you!

**Comment by furby-tm** [comment]
@ejjonny hmm, I attempted to use the Swift extension just now but it's still the same broken extension it's always been with no sourcekit-lsp support, was this change supposed to allow things to begin working?

**Comment by ejjonny** [comment]
Yeah, the published swift plugin has no language server, just syntax highlighting with tree sitter. 

As far as my repo - it needed to point to a tree sitter branch with some generated files to install properly. If you pull down the latest commit you (should?) be able to get up and running.

It might help to run `export RUST_LOG=info` in the terminal session you launch Zed with so you can better see what is happening during installation.

If you don't see this (after a couple minutes) in your extensions window in Zed, the plugin didn't install successfully.
![image](https://github.com/zed-industries/zed/assets/17223924/15093cac-958f-4679-a9cc-a56456a64e48)

The diagnostics message seems to be broken on my end - if you do get up and running you should let me know if you see the same deserialization warning I'm seeing.
