### ISSUE TITLE
Key binding to show informational tooltip

### ISSUE THREAD

**Issue by narqo** [zed-industries/zed#11395]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed's `hover_popover_enabled` setting controls if editor shows a tooltip with an information about a symbol under the mouse cursor. When this setting is disabled, I don't think there is currently a way to look up such information.

I propose adding a new key binding to Zed, that opens an information tooltip for the symbol, which is currently under the editor's cursor.

### If applicable, add mockups / screenshots to help present your vision of the feature

I don't have a mockup for the feature, but what I have in mind (and what I got used to from using other code editors), is [Parameter info](https://www.jetbrains.com/guide/go/tips/parameter-info/) `⌘+P` in JetBrains IDEs:

> Parameter info: Cmd+P on macOS, Ctrl+P on Windows/Linux — Shows the method call’s arguments with types.

**Comment by Moshyfawn** [comment]
There is an `editor::Hover` keybind to trigger the hover action, which is set to `cmd-k cmd-i` by default. You can use it to toggle the symbol tooltip. See #6489 for more information. Let me know if this solves your use-case.

**Comment by narqo** [comment]
> There is an `editor::Hover` keybind to trigger the hover action

Oh, right. I was looking for a command that has "popover" or "hint" part in it, and didn't even think of "hover". Thank you for pointing it out.
