### ISSUE TITLE
error: failed to select a version for `wasmtime`.

### ISSUE THREAD

**Issue by ankushT369** [zed-industries/zed#11411]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not able to build in linux system I do have rustup as per docs

### Environment

error: failed to select a version for `wasmtime`.
    ... required by package `activity_indicator v0.1.0 (/home/ankush/zed/crates/activity_indicator)`
versions that meet the requirements `^19.0.0` (locked to 19.0.0) are: 19.0.0

the package `activity_indicator` depends on `wasmtime`, with features: `wasmtime-runtime` but `wasmtime` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

failed to select a version for `wasmtime` which could resolve this conflict

**Comment by mikayla-maki** [comment]
We'll be releasing linux builds soon enough, which should make this obsolete.
