### ISSUE TITLE
Zed simply ignore the Go language convention

### ISSUE THREAD

**Issue by skhaz** [zed-industries/zed#11416]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Create a go file with something similar to:

```go
err = h.DB.QueryRow("SELECT id, ready FROM data WHERE url = ? LIMIT 1", payload.Url).Scan(&id, &ready); if err != nil {
```

Watch Zed simply ignore the Go language convention and move the `if err != nil` to a new line, which is wrong!

VSCode does not do that.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by htor** [comment]
Does this have anything to do with the maximum line length in your settings perhaps? I assume Zed is using the one and only standard Go formatter.

**Comment by skhaz** [comment]
It was my mistake, the line should be

```
if err = h.DB.QueryRow("SELECT id, error, ready FROM data WHERE url = ? LIMIT 1", payload.Url).Scan(&id, &error, &ready); err != nil {
```
