### ISSUE TITLE
Supermaven is too fast

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#11422]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Supermaven is so fast that it is spamming on every keystroke. Some sort of debounce / throttling might be needed.

Also, Jacob mentioned:

> One of the changes we’ll make next week is to limit the suggestions to only go to the end of the current line except when the user has just accepted a suggestion. We’ve found that helps a lot with making it less distracting

**Note: Supermaven support is only available for internal testing within the Zed organization and has not been publicly released yet.**

### Environment

Zed: v0.135.0 (Zed Nightly 89039f6f34910fadce76c73258b731f0a016ccd6)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by a-usr** [comment]
> I would like to know where to apply for internal testing qualifications? It's great for me to be able to use Zed's new features and improvements in advance ^:)

I think Supermaven is already included when building from source  since i was able to see a crate called that when I compiled zed today
