### ISSUE TITLE
Hover message window can be opened in vim mode

### ISSUE THREAD

**Issue by Woodii1998** [zed-industries/zed#11423]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to support the ability to open a hover message window in vim mode with a shortcut key or command instead of the mouse?

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="437" alt="image" src="https://github.com/zed-industries/zed/assets/33593572/af16efa9-4349-4d6b-aeae-b955ff837d85">

**Comment by d1y** [comment]
Are you saying that `editor::Hover`?
https://github.com/zed-industries/zed/blob/5a71d8c7f1d2887daf62869fb6012c33d59a3cd0/assets/keymaps/vim.json#L143

**Comment by Woodii1998** [comment]
> Are you saying that `editor::Hover`?
> 
> https://github.com/zed-industries/zed/blob/5a71d8c7f1d2887daf62869fb6012c33d59a3cd0/assets/keymaps/vim.json#L143

cool thank you. I guess I wasn't looking hard enough.
