### ISSUE TITLE
can not use Chinese Input Method(Fctix5)  on ubuntu 

### ISSUE THREAD

**Issue by aohanhongzhi** [zed-industries/zed#11431]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I build  the Zed from source code , and unable to use Chinese input method. 

![image](https://github.com/zed-industries/zed/assets/37319319/95675f06-5f5a-4c4e-bfaa-b6062771086e)

### Environment

ubuntu 22.04

**Comment by jansol** [comment]
Duplicate: #9207 (AFAIK they use the same interfaces)

**Comment by aohanhongzhi** [comment]
@JosephTLyons @jansol   thanks for your replay! I close it

**Comment by lixiaya** [comment]
When using the Zed editor package installed in Archlinux, Hyperland, and Aur, when I am using Chinese, pressing Shift cannot switch (I set the input method switch button to Shift). I manually set the first input method to Chinese, but still can only input English，

https://github.com/zed-industries/zed/assets/128228011/cda94c51-2c4c-4635-9c99-f3b4c4fdac64

**Comment by jansol** [comment]
@lixiaya yes, this is because there is no IME support yet. It will be added soon in #11712 and #11657 (for Wayland and X11 respectively)

**Comment by lixiaya** [comment]
> @lixiaya yes, this is because there is no IME support yet. It will be added soon in #11712 and #11657 (for Wayland and X11 respectively)

OK, thank you for your answer

**Comment by kipade** [comment]
@lixiaya how do resolve the problem finally? I almost tried all solutions from googled, but still can't switch to Chinese input mode
