### ISSUE TITLE
Extensions / Preview: Cannot install extensions from main repo (elm, haskell, elixir, etc)

### ISSUE THREAD

**Issue by baldwindavid** [zed-industries/zed#11435]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was attempting to install an extension in Zed Preview that exists within the main Zed repo and ran into a build error.

As an example, installing an extension from the extensions repo like Git Firefly or SCSS is a matter of cloning, clicking on "Install Dev Extension", and selecting the directory. This results in the existing extension being overridden...

<img width="1028" alt="Screenshot 2024-05-05 at 3 55 44 PM" src="https://github.com/zed-industries/zed/assets/4578/8d955e8b-6225-4cf9-90c9-7ee015b1cb22">&nbsp;

I tried similar with the elm, haskell, and elixir extensions within this repo:
- Running Zed Preview (v0.134.1)
- checked out `tags/v0.134.1-pre` to match that running version
- clicked "Install Dev Extension"
- selected the `extensions/elm` directory in the checked out files

If I've searched for the Elm extension I'll see the "Install" button disabled while the extension build is attempted. However, installation fails and the "Install" button gets enabled again.

Perhaps extensions within the main repo need to be installed a different way?

### Environment

Zed: v0.134.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
2024-05-06T08:39:28-04:00 [INFO] installing extension elm latest version
2024-05-06T08:39:28-04:00 [INFO] rebuilt extension index in 32.371375ms
2024-05-06T08:39:28-04:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-05-06T08:39:29-04:00 [ERROR] crates/extension/src/extension_store.rs:1142: failed to load wasm extension elm

Caused by:
    0: error parsing wasm extension
    1: unexpected end-of-file (at offset 0x408d0)
2024-05-06T08:39:30-04:00 [INFO] rebuilt extension index in 24.592875ms
2024-05-06T08:39:30-04:00 [INFO] extensions updated. loading 0, reloading 1, unloading 0
2024-05-06T08:39:32-04:00 [INFO] rebuilt extension index in 20.326459ms
2024-05-06T08:39:32-04:00 [INFO] extensions updated. loading 0, reloading 0, unloading 1
2024-05-06T08:39:43-04:00 [INFO] compiling Rust extension /Users/davidbaldwin/Code/forks/zed/extensions/elm
2024-05-06T08:39:43-04:00 [INFO] compiling rust extension /Users/davidbaldwin/Code/forks/zed/extensions/elm
2024-05-06T08:39:50-04:00 [ERROR] crates/extensions_ui/src/extensions_ui.rs:66: failed to compile Rust extension

Caused by:
    failed to build extension    Compiling ryu v1.0.15
       Compiling bitflags v2.4.2
       Compiling itoa v1.0.9
       Compiling wit-bindgen-rt v0.22.0
       Compiling serde v1.0.196
       Compiling wit-bindgen-rust v0.22.0
    error[E0463]: can't find crate for `core`
      |
      = note: the `wasm32-wasi` target may not be installed
      = help: consider downloading the target with `rustup target add wasm32-wasi`
    
    error[E0463]: can't find crate for `compiler_builtins`
    
    error[E0463]: can't find crate for `alloc`
     --> /Users/davidbaldwin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-bindgen-rt-0.22.0/src/lib.rs:3:1
      |
    3 | extern crate alloc;
      | ^^^^^^^^^^^^^^^^^^^ can't find crate
    
    libunwind: malformed __unwind_info at 0x19097CCA8 bad second level page
    libunwind: malformed __unwind_info at 0x19097CCA8 bad second level page
```

Followed by thousands of lines of errors...

**Comment by huacnlee** [comment]
Just run `rustup target add wasm32-wasi` can fix.

**Comment by baldwindavid** [comment]
Thanks, @huacnlee . I had actually tried that in a number of places (root of repo, within extension, etc) and always get `info: component 'rust-std' for target 'wasm32-wasi' is up to date` with seemingly no change. I'm not a rust dev so perhaps this is obvious, but is there a specific location to run that?

**Comment by d1y** [comment]
@baldwindavid  FWIW: 
Have you installed double copies of rust?
Homebrew && rustup.rs
If so, try uninstalling one: brew uninstall rust?

**Comment by baldwindavid** [comment]
@d1y Ah, yes; that is it. Uninstalled the homebrew version (didn't know it was installed via that too 😓 ) and all is well. Thank you!
