### ISSUE TITLE
Tasks menu list picker contains additional bottom border

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#11451]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

_<Title and screenshot>_

### Environment

Zed: v0.135.0 (Zed Nightly c68b7003128985bb486bb499367704f0a0cb1697)
OS: macOS 14.4.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1632" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/559a5672-9ebd-492f-a9b2-8f00ba8612dd">

**Comment by JosephTLyons** [comment]
cc @someone13574 @osiewicz

**Comment by Moshyfawn** [comment]
This seems to have been resolved!
<img width="505" alt="image" src="https://github.com/user-attachments/assets/d3fe38b3-7d14-46ad-ba0a-705a65e4bcc5">
