### ISSUE TITLE
Dragging the left panel will display the Git diff view

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#11456]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In more extreme cases, such as when the entire file has been modified, there's no way to avoid triggering the `git diff` view when resizing the left dock.

### Environment

Zed: v0.135.0 (Zed Nightly c68b7003128985bb486bb499367704f0a0cb1697)
OS: macOS 14.4.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/9efc8e72-af44-4eb0-aa09-f64543346014

**Comment by JosephTLyons** [comment]
cc @SomeoneToIgnore
