### ISSUE TITLE
Default Formatter in Settings

### ISSUE THREAD

**Issue by xcrap** [zed-industries/zed#11468]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've mention this several times but it was not addressed, now that the docs are available to contribute I didn't want to make this change without confirmation. 

In the documentation the default formatter is set to "language_server", in the Zed: Open Default Settings is set to "auto", so what is it? Or auto is the same as language_server?

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="859" alt="Screenshot 2024-05-06 at 22 56 29" src="https://github.com/zed-industries/zed/assets/828596/3c22f000-2a9b-4a8f-91af-ebc047e3dd8f">
<img width="994" alt="Screenshot 2024-05-06 at 22 56 22" src="https://github.com/zed-industries/zed/assets/828596/be011963-2e52-46d9-bf42-f8a0609cfdc1">

**Comment by Moshyfawn** [comment]
See the comments for all the formatter options. Let me know if this answers your question.

https://github.com/zed-industries/zed/blob/1cf40d77e2149188f114077629acf66ae1a4e81d/crates/language/src/language_settings.rs#L396C1-L414C2

**Comment by xcrap** [comment]
Yes I got it, so the default It's Auto for Zed Prettier based on the context or file type, otherwise LanguageServer and etc, but I don't understand why the default in the documentation is not Auto instead of LanguageServer ?

This has confused me because when the PHP formatter was not working, I didn't understand why, only after I saw Zed Default Setting was Auto I understand that I could override PHP for Language Server and it start working again (I think this issue is partially solved). So that's why I don't understand the documentation writes default to LanguageServer and the zed: open default settings it's set as auto.

**Comment by maxdeviant** [comment]
@xcrap Thanks for reporting.

Indeed, the docs had the wrong value listed.

They have been updated to reflect reality.
