### ISSUE TITLE
Vim Mode: Disable Mouse

### ISSUE THREAD

**Issue by RobinRuf** [zed-industries/zed#11467]
### Check for existing issues

- [X] Completed

## Feature
In Vim, it is possible to disable the mouse completely. You can click inside of vim wherever you want but the cursor doesn't change its position. Also scrolling with the mouse isn't possible then.

Maybe this is something to add for vim mode settings?

## Implementation Idea
If so - two separate options would be nice: The ability of scrolling with mouse (on/off) and the ability of disabling the mouse (clicking without changing cursor position)

**Comment by 0x2CA** [comment]
Disabling the mouse allows you to really test the keyboard-accessible,find problems with vim

**Comment by baldwindavid** [comment]
Think that would be nice to eventually have. Somewhat related: I use vim mode and one thing that initially frustrated me was when I had to use the mouse in another app and then moved the cursor back to Zed. If the cursor happened to land over a hoverable item, a popover would appear that I didn't want to see. Anyway, if you're running into the same problem, there is a `hover_popover_enabled` setting that eliminates that specific issue.

**Comment by nilsherzig** [comment]
> popover

i can seem to find a way to toggle the popover using the keyboard in vim mode, could you please point me in the right direction for that?

**Comment by ConradIrwin** [comment]
I don't think we should have a way to disable the mouse in Zed; if you don't want to use the mouse, don't touch it :D.

https://github.com/zed-industries/zed/pull/15898 will hide it when it's not moving, which I think is good enough.

(Also @baldwindavid surely you use cmd-tab to change windows :D)

**Comment by baldwindavid** [comment]
@ConradIrwin ha, yeah...iirc this was more about apps where I have to use the mouse and have moved the cursor out of the way from my non-zed screen to my zed screen. The problem went away with `hover_popover_enabled` anyway though. #15898 looks real nice too. I still kinda yearn for a modal-first gui editor, but that dream died a bit alongside onivim 2.
