### ISSUE TITLE
It crashed when making large amount of replace using cmd + F

### ISSUE THREAD

**Issue by ramyak-mehra** [zed-industries/zed#11464]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is a rather specific scenario but i was editing a log file trying to clean it up and there. I selected the lines with regex(not sure if that does make a difference, just in case). I replaced all occurances with a blank line. It hanged for a bit but eventually did the job. I did see the memory spike but the memory usage never came down. I did a couple of similar edits. The edits are in the order of 10s of thousands each time. The final edit crashed the editor. It was close to 200k edits(I know this is a lot ). The last memory usage was close to 6GB. There were other files opened a rust analyzer running.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.3.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

I don't see any logs for the previous sessions

**Comment by notpeter** [comment]
I'm experiencing the same thing, no crash, but hangs for a while.

Here's a simple steps to reproduce:
1. Use this [6000 line text file](https://gist.github.com/notpeter/7d021805c5e66d363f88db33e26ee231)
2. Find and Replace (cmd+opt+r) with Regex
3. Find: `(.+)\t(.+)`
4. Replace: `$2="$1"`

Hangs for ~2mins20secs on my machine.

**Comment by notpeter** [comment]
This is no longer reproducible. Back in the summer there were some performance improvements with our handling of large regex replacements. Now instead of Zed hanging for 2m20s the replacement above is instant.

Thanks for reporting!
