### ISSUE TITLE
linux: Window flickering when resizing after recent commit

### ISSUE THREAD

**Issue by DissolveDZ** [zed-industries/zed#11469]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The window is flickering when resizing due to a recent commit, probably the one containing blade window transparency but i'm not quite sure

### Environment

Zed: v1.0.0 (Zed Dev f2a415135b9d4af9f4c854c74edc5348f926b9fc)
OS: Linux 1.0.0
Memory: 23.4 GiB
Architecture: x86_64

**Comment by someone13574** [comment]
I bisected it and it is indeed #10973

**Comment by someone13574** [comment]
@ConradIrwin  Can you close this since it was fixed in #13002
