### ISSUE TITLE
Character Variants don't work for Zed (Commit Mono font)

### ISSUE THREAD

**Issue by arjpar** [zed-industries/zed#11486]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Description: character variants don't seem to work on Zed (tested using the Commit Mono font but other fonts are probably affected). Stylistic sets work, but character variants don't.

1. Open Zed
2. Go to Settings
3. Ensure that "CommitMono" is used as the value for "buffer_font_family"
4. Ensure that character variants are being used in "buffer_font_features", example:>
```
// [...] other settings above
  "buffer_font_features": {
    "cv06": true,
    "cv07": true,
    "cv08": true
  },
// [...] other settings below
```

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

What the font looks like in Zed (character variants not being applied):
<img width="456" alt="image" src="https://github.com/zed-industries/zed/assets/41452613/1e80a6b1-bff6-4e09-ace7-b04668c129f8">

What the font is supposed to look like:
(Italics shown in the image to show what italics are supposed to look like)
<img width="331" alt="image" src="https://github.com/zed-industries/zed/assets/41452613/a583a156-2442-446a-baf0-68199e1e2bf7">

**Comment by JunkuiZhang** [comment]
This is the expected behavior on macOS, as macOS only supports a limited set of font features. Currently, all font features are supported on Windows.

For the features supported, see [here](https://zed.dev/docs/configuring-zed):
> Zed supports a subset of OpenType features that can be enabled or disabled for a given buffer or terminal font. The following [OpenType features](https://en.wikipedia.org/wiki/List_of_typographic_features) can be enabled or disabled too: calt, case, cpsp, frac, liga, onum, ordn, pnum, ss01, ss02, ss03, ss04, ss05, ss06, ss07, ss08, ss09, ss10, ss11, ss12, ss13, ss14, ss15, ss16, ss17, ss18, ss19, ss20, subs, sups, swsh, titl, tnum, zero.

**Comment by arjpar** [comment]
@JunkuiZhang macOS very much supports the character variants I was trying to enable. Those character variants work in every other editor I've tried (VSCode, WezTerm, Helix, etc). Are you saying its a limitation of Zed, or a limitation of macOS?

**Comment by JunkuiZhang** [comment]
Sorry for the confusion. I was referring to Zed, of course. Currently, Zed's implementation on macOS only includes these font features.

**Comment by JunkuiZhang** [comment]
You can try #11611
