### ISSUE TITLE
test task is run incorrectly on linux

### ISSUE THREAD

**Issue by sigmaSd** [zed-industries/zed#11481]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running a test task on linux fails like this

```
⏵ Task `cargo test -p qsdsq hello -- --nocapture` finished with non-zero error code: 127
⏵ Command: '/usr/bin/fish -i -c `cargo test -p qsdsq hello -- --nocapture`'
```

The problem seems to be that the shell script is quoted with ` instead of " or '

Maybe thats a macos thing ?

The relevant code https://github.com/zed-industries/zed/blob/4eca7875ae25469c5a43f3f73f7160c861cba3c8/crates/terminal_view/src/terminal_panel.rs#L342 

### Environment

Zed: v1.0.0 (Zed Nightly c68b7003128985bb486bb499367704f0a0cb1697)
OS: Linux 1.0.0
Memory: 7.6 GiB
Architecture: x86_64

**Comment by sigmaSd** [comment]
Actually for some reason cargo run task works:
```
⏵ Task `cargo run` finished successfully
⏵ Command: '/usr/bin/fish -i -c `cargo run`'
```
If I spawn the same command manually it errors (it works if I change the quotes)
```
/usr/bin/fish -i -c `cargo run`
fish: `cargo: command not found...
```

**Comment by mrnugget** [comment]
I think the problem is more that we don't support fish in tasks yet, right @osiewicz? The quotes in that window aren't the actual quotes used.
