### ISSUE TITLE
Necessary to restart Zed entirely when host ends shared session

### ISSUE THREAD

**Issue by mcncl** [zed-industries/zed#11532]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When a non-host ends a shared remote session you are not returned to the main Zed screen, where rooms etc are listed. Instead you have to wait for the session to crash/quit out of Zed in order to get back to the project view.

Joining a "room" works fine and the pairing session is smooth, however I'd expect to be kicked back to the main screen when a shared session has finished, instead none of the UI is clickable and I have to quit Zed to go back to root.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 24 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
It sounds like you’re referring to the empty window that is left after a collaboration session is ended?

You should just be able to close that individual window and return to your other open Zed window(s).

**Comment by mcncl** [comment]
@Moshyfawn I'll take a look next time I'm pairing in Zig. Perhaps that is the case; I'm used to Slack, Zoom etc just ending the session and closing the window for me.

**Comment by notpeter** [comment]
@mcncl Have you experience this issue again or have any hints of how to reproduce it? I understand the conditions may be difficult to reproduce if it requires a remote collaborator to do something specific to trigger the bug.

**Comment by mcncl** [comment]
@notpeter appreciate you following up! The folks I work with aren't using Zed any more, so I don't really have the opportunity to reproduce this. You're welcome to close the issue or I can.
