### ISSUE TITLE
Since recent commits the GitHub copilot button is back

### ISSUE THREAD

**Issue by williamdes** [zed-industries/zed#11537]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```json
  "features": {
    "copilot": false
  },
```

### Environment

Zed: v1.0.0 (Zed Dev 47ca3438034ec6c7e5f8b17a5e9274ebc4cc24eb)
OS: Debian 12
Memory: 62.4 GiB
Architecture: x86_64

**Comment by williamdes** [comment]
I was previously at 89039f6f34910fadce76c73258b731f0a016ccd6

**Comment by maxdeviant** [comment]
There was a change to the settings needed to disable the Copilot button.

You can use this setting and set the value to `"none"`: https://github.com/zed-industries/zed/blob/593f0e0c3ef08da7e528230867526dcb77e723fa/assets/settings/default.json#L16

**Comment by williamdes** [comment]
I have set
```json
  "features": {
    "copilot": false,
    "inline_completion_provider": "none"
  },
```
And the button still shows up

**Comment by andreapavoni** [comment]
@williamdes adding `"inline_completion_provider": "none"` worked for me. I had the copilot button showing up again after the latest stable update to `v0.135.2`. I usually upgrade Zed as soon as new updates come, I'm not sure why it happened only now.

> ```json
>   "features": {
>     "copilot": false,
>     "inline_completion_provider": "none"
>   },
> ```

**Comment by williamdes** [comment]
I am now at 0dd5fe313b6e44c87885215d3c4d93728d8e1ca5 (some commits after v0.137.x and the button seems gone)
