### ISSUE TITLE
Rendering of right border is missing for some tabs with custom ui_font_size

### ISSUE THREAD

**Issue by iluuu1994** [zed-industries/zed#11549]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When setting `ui_font_size` to some values, every some tab seems to be missing the right border.

Incorrect:

![Screenshot from 2024-05-08 13-45-47](https://github.com/zed-industries/zed/assets/1752683/f92bf4ef-749c-4aba-bc9f-793f843f913d)

Correct:

![Screenshot from 2024-05-08 13-45-53](https://github.com/zed-industries/zed/assets/1752683/d0696122-636a-454e-8fd2-12b76d718918)

For me, this occurs with `"ui_font_size": 19`.

I have not verified other environments.

Thank you to everyone involved for this great project!

### Environment

Zed: v1.0.0 (Zed Dev 9d681bda8d607384703f14d9e6549165e5cb9ae4)
OS: Linux 1.0.0
Memory: 31.1 GiB
Architecture: x86_64

On Linux (Fedora + Gnome + Wayland), standard 1x scaling

**Comment by Moshyfawn** [comment]
Related #11496

**Comment by iluuu1994** [comment]
This issue has disappeared for me, so let me close it. Thanks!
