### ISSUE TITLE
Collaboration invites won't run when accepted

### ISSUE THREAD

**Issue by dimitrisnl** [zed-industries/zed#11540]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I click accept whenever someone invites me to collaborate, and nothing happens. 
There's also no mention of the invitation in the Notification panel. As if it never happened.

Collaboration used to work flawlessly before, and now it's not, both in Stable and Preview channels.

I'm trying to figure out how to debug this further. I have:
- Deleted everything under `/.config/zed`
- Removed the app and installed it again
- Tried the Preview version

### Environment

```
Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 18 GiB
Architecture: aarch64
```
and

```
Zed: v0.134.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 18 GiB
Architecture: aarch64
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

This shows when I accepted the invitation.

```
2024-05-08T11:46:45+03:00 [ERROR] crates/collab_ui/src/notifications/incoming_call_notification.rs:98: RPC request JoinRoom failed: Forbidden
```

**Comment by ConradIrwin** [comment]
@dimitrisnl This doesn't sound good at all. I can see in the logs that you are seeing Forbidden responses, but not why.

The most likely cause of this seems to be that they are inviting you to a call in a channel that you are not a part of. Is that a possibility in this case?

**Comment by dimitrisnl** [comment]
@ConradIrwin 

Thanks for taking the time to look into this. We tried again and here are some observations
1. Invitation to channel fails as well
2. There's no mention of the invitation in the notification panel, only week old events

The logs I see are

```
2024-05-10T10:57:05+03:00 [ERROR] crates/collab_ui/src/notifications/incoming_call_notification.rs:98: RPC request JoinRoom failed: no such room
2024-05-10T10:57:17+03:00 [ERROR] crates/collab_ui/src/notifications/incoming_call_notification.rs:98: RPC request JoinRoom failed: Forbidden
```

Now after 3-4 tries it seems to work, so I can safely close it and monitor in case something happens again.

**Comment by ConradIrwin** [comment]
Glad it's working, but... yikes!

Let me know if you run into it again and we can sit down together and debug.
