### ISSUE TITLE
Windows: crash when trying to save log into a file

### ISSUE THREAD

**Issue by ognevny** [zed-industries/zed#11544]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. `zed: open log`
2. press `ctrl+s`
3. try to save into any directory

### Environment

Zed: v0.135.0 (Zed Dev 63a5f46df4a694cf5ccfea43628a2ac8a4f053da)
OS: Windows 10.0.22631
Memory: 15.3 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

--

**Comment by CharlesChen0823** [comment]
I know what cause it.
