### ISSUE TITLE
Windows: crash on search panel when there are too many matches

### ISSUE THREAD

**Issue by ognevny** [zed-industries/zed#11543]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. `ctrl+shift+f`
2. type `a` and press enter
3. wait until there are >1000 matches

### Environment

Zed: v0.135.0 (Zed Dev 63a5f46df4a694cf5ccfea43628a2ac8a4f053da)
OS: Windows 10.0.22631
Memory: 15.3 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

--

**Comment by CharlesChen0823** [comment]
interesting, I cannot reproduce this, can you reproduce every times?

**Comment by ognevny** [comment]
> interesting, I cannot reproduce this, can you reproduce every times?

maybe it's MinGW specific? I'll try to reproduce it multiple times later (in debug build)

**Comment by ognevny** [comment]
> interesting, I cannot reproduce this, can you reproduce every times?

now I can't reproduce it

**Comment by ognevny** [comment]
reopening, seems like it happens *sometimes*

**Comment by ognevny** [comment]
I can reproduce only with zed downloaded from [github artifacts](https://github.com/msys2/MINGW-packages/actions/runs/8998885498?pr=20056), but not from 'fresh' build

**Comment by CharlesChen0823** [comment]
this should have fixed with #11634 .

**Comment by ognevny** [comment]
looks like that's true, closing
