### ISSUE TITLE
Command pallet has assistant2

### ISSUE THREAD

**Issue by jsfour** [zed-industries/zed#11557]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open up command pallet, assistant2 is one of the options. 

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2024-05-08 at 07 06 37@2x](https://github.com/zed-industries/zed/assets/1569744/0c9df476-28d3-411a-b270-691b6fcde3f3)

**Comment by rgbkrk** [comment]
Thanks for reporting this. We have a feature flagged new assistant panel with keybindings registered under the assistant2 name. We'll have to figure out if we can hide these too.

**Comment by iamnbutler** [comment]
This isn't a big secret or anything, just the next version of the assistant that we're working on. 

Many things are not implemented yet or are still in motion so even if there is a way to access it it's not really advisable to try to use it. 

We'll figure out why the assistant2 actions are showing up there and make sure they don't until we swap the assistant over.

**Comment by maxdeviant** [comment]
This was addressed in #11940.
