### ISSUE TITLE
Diagnostics to use `buffer_font_family` or a separate setting

### ISSUE THREAD

**Issue by agu-z** [zed-industries/zed#11564]
### Check for existing issues

- [X] Completed

### Describe the feature

Other editors render diagnostics from language servers in monospace fonts. It seems that Zed uses `ui_font_family` for them, which is often proportional, and therefore some diagnostics do not line up as intended:

<img width=400 src="https://github.com/zed-industries/zed/assets/1724813/3ce9db87-e545-46fb-89bb-fed05f7ca98b"></img>

Users can use a monospace font for UI, but they might not want to do so for the rest of the editor.

The default experience could be better if diagnostics used `buffer_font_family`. Optionally, it'd be nice to have a specific font for diagnostics, but I think it should still default to the buffer one.

**Comment by agu-z** [comment]
Arguably the diagnostic in the screenshot should be improved so it doesn't contain the highlighted code. However, I still think that a monospace font would be a better default in general.

**Comment by Moshyfawn** [comment]
This has already been mentioned, so I'm going to close this issue in favour of the other one. Be sure to +👍 the other thread.

Duplicate of:
- #11527

**Comment by agu-z** [comment]
@Moshyfawn Whoops. I searched but I failed to find that one, my bad.

**Comment by Moshyfawn** [comment]
No problem at all!
