### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by gmr458** [zed-industries/zed#11573]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed consumes 1.6GB of memory for each open window even if the window does not have any files or projects open, I asked other people on social media about this and for them Zed consumes 200MB-400MB.

## Hardware Information:
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i3-6006U × 4
- **Graphics:**                                    Intel® HD Graphics 520 (SKL GT2)

## Software Information:
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **GNOME Version:**                               45.6
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.8-200.fc39.x86_64

### Environment

Zed: v1.0.0 (Zed Dev 724acaab61962f2c066a1dcc75e7fd1385a8d807)
OS: Linux 1.0.0
Memory: 7.6 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment]
#10351 mentions the same symptoms as well as the multi-window CPU usage increase. Do you think it'd be fair to close this issue in favour of the other one?

**Comment by gmr458** [comment]
closed in favor of #10351
