### ISSUE TITLE
Expanded diff hunks cover an extra line

### ISSUE THREAD

**Issue by eth0net** [zed-industries/zed#11576]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Git diff indicators next to the line numbers show which lines have been changed as expected, but when expanding the hunk to view the diff the add portions claim the next line even though it's unchanged.

### Environment

Zed: v0.135.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: x86_64

### Closed diff hunks showing the changed lines
<img width="1222" alt="Screenshot 2024-05-08 at 21 26 07" src="https://github.com/zed-industries/zed/assets/1347854/ed7c97b7-658a-45f6-b789-f571a2f173fe">

### Open diff hunks claiming the extra lines
<img width="1222" alt="Screenshot 2024-05-08 at 21 26 28" src="https://github.com/zed-industries/zed/assets/1347854/7ed434ef-c85f-4335-86c5-87f23bc0ba13">

**Comment by eth0net** [comment]
Note: I will try to resolve this myself but I am also working on #11504 right now 👀

**Comment by JosephTLyons** [comment]
cc: @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
Thank you, https://github.com/zed-industries/zed/pull/11632 is supposed to fix that.
