### ISSUE TITLE
Quick command change on macos

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11608]
### Check for existing issues

- [X] Completed

### Describe the feature

vscode:
<img width="285" alt="Screenshot 2024-05-09 alle 13 20 06" src="https://github.com/zed-industries/zed/assets/20476002/548a0d38-f294-4fd9-bc39-41ba8cb153a6">

Zed:
<img width="208" alt="Screenshot 2024-05-09 alle 13 20 50" src="https://github.com/zed-industries/zed/assets/20476002/ec670c9b-9fe5-4eb1-aa88-d5c02c1a6759">

**Comment by JosephTLyons** [comment]
It looks like we have 2 bindings registered for this action and Zed is displaying the first one:

```
"f2": "project_panel::Rename",
"enter": "project_panel::Rename",
```

Not sure why we have `f2` registered - I would just say we should remove it, but maybe there's a reason here I'm not aware of - could be some sort of backward compatibility...

**Comment by 80avin** [comment]
I just checked on mac os and linux, and looks like ``F2`` is the actual key binding to rename a variable on both.
While to rename a file, mac has Enter while linux has F2 here also.

So, I don't think this issue asks for the right change.
