### ISSUE TITLE
Suddenly close the editor after click Delete or Trash

### ISSUE THREAD

**Issue by hafidluqman50** [zed-industries/zed#11601]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![ScreenRecording2024-05-09at17 14 40-ezgif com-video-to-gif-converter](https://github.com/zed-industries/zed/assets/20903221/943f7bc9-d6d9-468e-9e0f-fea9e2343eea)

App auto close when i click Trash or Delete in some files or folder. This bug kinda annoying for me, i can't work fast without this. Let me know if this already fix. Thanks 💖

Here's the log error:

2024-05-09T17:38:44+08:00 [ERROR] {
  "thread": "main",
  "payload": "Leases must be ended with EntityMap::end_lease",
  "location_data": {
    "file": "/Users/administrator/_work/zed/zed/crates/gpui/src/app/entity_map.rs",
    "line": 175
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "Zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys_common::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::ptr::drop_in_place::<gpui::app::entity_map::Lease<project::Project>>",
    "<gpui::elements::div::Interactivity>::on_action::<project_panel::Trash, <gpui::window::ViewContext<project_panel::ProjectPanel>>::listener<project_panel::Trash, <project_panel::ProjectPanel>::trash>::{closure#0}>::{closure#0}",
    "<gpui::window::WindowContext>::dispatch_action_on_node",
    "<<gpui::window::WindowContext>::dispatch_action::{closure#0} as core::ops::function::FnOnce<(&mut gpui::app::AppContext,)>>::call_once::{shim:vtable#0}",
    "<gpui::app::AppContext>::flush_effects",
    "<gpui::window::Window>::new::{closure#7}",
    "gpui::platform::mac::window::handle_view_event",
    "-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]",
    "-[NSWindow(NSEventRouting) sendEvent:]",
    "-[NSApplication(NSEvent) sendEvent:]",
    "gpui::platform::mac::platform::send_event",
    "-[NSApplication run]",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "<gpui::app::App>::run::<Zed::init_ui::{closure#3}>",
    "Zed::main",
    "std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.134.3",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "10.15.7",
  "architecture": "x86_64",
  "panicked_on": 1715247524561,
  "installation_id": "0513eac6-8575-453b-974b-42cf5489e2c2",
  "session_id": "a8746626-ea51-4503-b055-b8be17625c94"
}

### Environment

- Zed 0.134.3

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15260557/Zed.log)

**Comment by CaptSolo** [comment]
I have the same issue - Zed crashes after trying to delete a file in the file pane (left sidebar).

Relevant portion of the log file attached: [Zed.log](https://github.com/zed-industries/zed/files/15264612/Zed.log)

**Comment by ConradIrwin** [comment]
Thanks for reporting this, that's no good!

It looks like both of you are running macOS Catalina. We had recently added support for macOS "Destructive" actions to the prompts, and these do not work on macOS Catalina.

We are building a new release that should fix this for you, and we'll roll-back the destructive action button changes fully.

**Comment by JosephTLyons** [comment]
@hafidluqman50, @CaptSolo - can you both try [v0.134.4](https://zed.dev/releases/stable/0.134.4) and let us know if your issue is fixed?

**Comment by CaptSolo** [comment]
> @hafidluqman50, @CaptSolo - can you both try [v0.134.4](https://zed.dev/releases/stable/0.134.4) and let us know if your issue is fixed?

I can confirm that the issue is fixed.

Thanks for the quick reaction time! 👍
