### ISSUE TITLE
Open Preview file md

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11607]
### Check for existing issues

- [X] Completed

### Describe the feature

As vscode does it would be possible for md files to have this command.

<img width="280" alt="Screenshot 2024-05-09 alle 13 15 49" src="https://github.com/zed-industries/zed/assets/20476002/22d706f8-dfd9-468b-9d36-3b534387c571">

**Comment by widersky** [comment]
Actually....

![image](https://github.com/zed-industries/zed/assets/45122321/b4e03e82-7e28-4622-9edb-8c4d67cb8744)

**Comment by JosephTLyons** [comment]
Yes, we do have a Markdown viewer already! Thanks @widersky! Going to close this out.
