### ISSUE TITLE
F2 - rename stopped working (in a few past preview revisions)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#11618]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`F2` (rename) stopped working

### Environment

Zed: v0.135.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Nothing reported.

**Comment by krstp** [comment]
Python. 
Let me know what other details and will gladly provide.

**Comment by krstp** [comment]
What I am seeing now, it is not only `F2` but other `Fs` as well, i.e. `F8`. A side note, I do use those with function key `Fn`. As due diligence, I tried to enable on my mac usage `F1, F2` etc as normal keys without `Fn` and it also yields no effect.

So I would rather say this affects all Fs :)

**Comment by krstp** [comment]
To add and confirm, this affects all `F`s... Such as `Got to Definition` `F12`, `Go to Implementation` `SHIFT+F12`, or `Find All References` `CMD+OPT+F12`...

To add to it, mouse right click on the `definition/method/function` and selection of any of above also does not work.

Not sure with which release it went faulty, but I was sure I mixed up keyboard shortcuts, needless to say now trying to properly track it those combinations do not work even using mouse triggers.

**Comment by p08dev** [comment]
Had a similar issue, removing Emmet fixed it for me: https://github.com/zed-industries/zed/issues/10367#issuecomment-2115841994

**Comment by krstp** [comment]
I don't have Emmet in my case.

Also with recent updated `F2` rename started working, but Got-to-definition `F12` shortcuts are still not working.

**Comment by notpeter** [comment]
Checking in to see whether this is still an issue as we've made some changes to gpui keyboard handling in the meantime which may have fixed this.

**Comment by krstp** [comment]
Works on my side. I thought this ticket has already been closed (probably a different related one). Thanks for checking. All work here.
