### ISSUE TITLE
Missing line break after blocks folding

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#11614]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Just fold the block/methods, such as:

![Screenshot 2024-05-09 at 9 10 02 AM](https://github.com/zed-industries/zed/assets/4711498/aa19d5cc-3170-4a5c-b365-d63b024cff92)

You can see there are no line breaks between different functions. I think it is customary to have a line break after each of the folded functions, such as:

![Screenshot 2024-05-09 at 9 10 14 AM](https://github.com/zed-industries/zed/assets/4711498/4b26bef6-151e-444a-b521-0a3d34cc274f)
*please disregard extra bracket in `func3`; just a typo

### Environment

Zed: v0.134.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

See above description for details

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

`zed.log` does not apply.

**Comment by krstp** [comment]
Additionally, I think the attributes should be showing up, at the moment they get folded as well. Not sure if I should open a separate issue or this is intentional behavior, see below vs above:
![Screenshot 2024-05-09 at 9 14 06 AM](https://github.com/zed-industries/zed/assets/4711498/5647f10d-4539-497b-98bc-5ebe18a4c8eb)

**Comment by aarroisi** [comment]
I would like this as well. It's a bit disorienting seeing those functions / classes so close together when collapsed.
