### ISSUE TITLE
Don't Collapse Trailing Newlines

### ISSUE THREAD

**Issue by aarroisi** [zed-industries/zed#11638]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, Zed also collapse newlines after a code section that's indented (classes, functions, etc). I would like to request so that the collapsed codes doesn't include the newlines, only the codes. VSCode behaves like this.

### If applicable, add mockups / screenshots to help present your vision of the feature

**VSCode**
> <img width="216" alt="image" src="https://github.com/zed-industries/zed/assets/34854015/e2b59e51-fce8-4b05-991d-8dd29f76b4eb">

VSCode function with one extra newline collapsed. The newline still visible.
> <img width="229" alt="Screenshot 2024-05-10 at 08 13 56" src="https://github.com/zed-industries/zed/assets/34854015/dabcc8dc-7f59-4f6f-a5e9-f5e82738347d">

VSCode class with two extra newline collapsed. The newlines still visible.
> <img width="217" alt="Screenshot 2024-05-10 at 08 18 28" src="https://github.com/zed-industries/zed/assets/34854015/1724674c-7b0d-4015-907d-4f939a4ca7ad">

**Zed**
> ![image](https://github.com/zed-industries/zed/assets/34854015/318e6fc9-e8e7-48d8-a26c-8a22e34333c2)

Zed function with one extra newline collapsed. The newline is collapsed.
![Screenshot 2024-05-10 at 08 14 10](https://github.com/zed-industries/zed/assets/34854015/1eca9188-cd9f-4690-9f45-0be972c77ca5)

Zed class with two extra newline collapsed. The newlines are collapsed.
![Screenshot 2024-05-10 at 08 18 43](https://github.com/zed-industries/zed/assets/34854015/9a7d52c8-e6eb-467f-a73e-038672dc729f)

**Comment by aarroisi** [comment]
Sorry, duplicates.

**Comment by Moshyfawn** [comment]
Duplicate of:
- #11614
