### ISSUE TITLE
Windows - Zed crashes on terminal open unless config is fixed

### ISSUE THREAD

**Issue by arihant2math** [zed-industries/zed#11645]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening the terminal (by clicking on the button on the toolbar) on windows, the entire application crashes unless the following is set in the zed settings:
```
"terminal": {
    "shell": {
        "program": "pwsh"
    }
  }
  ```
where the program is either `pwsh` or `cmd` or any other installed shell.

### Environment

Zed: v0.136.0 (Zed Dev 0c2d71f1ace6c5ca43e00179898ff9c8a982d9ae)
OS: Windows 10.0.22635
Memory: 15.9 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

The logs simply end with
```
2024-05-09T21:12:50-07:00 [INFO] Using Windows API for pseudoconsole
```

(The log message is from alacritty)

[Zed.log](https://github.com/zed-industries/zed/files/15270415/Zed.log)

**Comment by arihant2math** [comment]
It seems like [this line](https://github.com/zed-industries/zed/blob/80d3eafa303cc4921cadcddf59f263e23f132da1/crates/terminal_view/src/terminal_panel.rs#L336) is unix only.

**Comment by a-usr** [comment]
It works for me (windows 11 Build 22631.3447)
When clicking on the terminal with the default configuration it opens cmd.exe for a shell. I find it quite odd that there is no panic whatsoever. Are you building under native windows or wsl? are you sure zed isn't still running? Is cmd.exe working correctly? Try disabling any antivirus application before starting the terminal in zed.

**Comment by a-usr** [comment]
> 2. This is a silent panic that is occurring because alacrity is mis-configured in some way (to the best of my knowledge). Part of me suspects that zed is feeding in a `~` to `cmd.exe` (as part of the working directory or some other configuration), which leads to the crash or zed could be trying to spawn a `sh` shell or similar and crashing because of that.

Good thinking, but can you prove that? And what about the return code when zed exits?

**Comment by a-usr** [comment]
To be honest to me this feels like something in your environment is forcefully terminating zed for some reason. Are you on your home device? Or some sort of corporate managed device?

**Comment by arihant2math** [comment]
> To be honest to me this feels like something in your environment is forcefully terminating zed for some reason. Are you on your home device? Or some sort of corporate managed device?

The thing is, it worked after changing that setting. It is a home device.

**Comment by a-usr** [comment]
In that case i cant help you... I am very sorry, but i have no idea what could be causing this, and the fact that i cant replicate this issue on neither of my two devices doesnt help it...

**Comment by a-usr** [comment]
Allright, I was revisiting my notifications, and I just got an Idea: If this is still an issue for you, can you check what system calls zed makes using procmon? That would probably be pretty helpful

**Comment by arihant2math** [comment]
Re-tested on the latest version of zed, and the issue is no longer present.
