### ISSUE TITLE
Add "New Window" entry to Dock icon

### ISSUE THREAD

**Issue by bkircher** [zed-industries/zed#11651]
### Check for existing issues

- [X] Completed

### Describe the feature

The Zed Dock icon is missing a _"New Window"_ entry. It's just a minor thing but, yeah, I missed it since VS Code brings one.

### If applicable, add mockups / screenshots to help present your vision of the feature

Zed:
<img width="227" alt="Screenshot 2024-05-10 at 09 59 46" src="https://github.com/zed-industries/zed/assets/536464/f39498da-234e-40c5-b83c-89a4fcafbded">
VS Code:
<img width="301" alt="Screenshot 2024-05-10 at 09 59 27" src="https://github.com/zed-industries/zed/assets/536464/1b8b9643-66f8-4be4-acd9-a1b4dc998a8d">

**Comment by versecafe** [comment]
Does anyone know where this menu is actually configured in `zed` I've spent over three hours looking, and GPUI has no docks on the app level Menus just the menubar menus, I can't find where in `platform.rs` this would even be setup as `NSDocktile` is never even imported from cocoa??

I think the platform trait is missing a section for app menus, as in app icon, separate from the Menu bar.

@ConradIrwin Could you help me figure this out, I'm not sure who else might know?

**Comment by ConradIrwin** [comment]
It doesn't look like we have configured that menu yet (it seems like the default one). So we may need to build some of the infrastructure here.

If you want to pair on this, feel free to book time here: https://calendly.com/conradirwin/pairing

**Comment by bennetbo** [comment]
Not sure if this is helpful but #8952 added entries for recent projects, relevant code is [here](https://github.com/zed-industries/zed/blob/0ae0b08c3895ef3ed7bf24d5bf36c06a0a18c3fa/crates/gpui/src/platform/mac/platform.rs#L737)

**Comment by versecafe** [comment]
@ConradIrwin Are you still free for this afternoon?
