### ISSUE TITLE
hyperlink to code in terminal 

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#11653]
### Check for existing issues

- [X] Completed

### Describe the feature

if there is an error/failed test in rust it would be easier to jump directly to the line where the error occurred:
Example:
--> src/main.rs:10:9

**Comment by Moshyfawn** [comment]
I believe this is already a feature: check out this screencast.

https://github.com/zed-industries/zed/assets/16290753/b9e8cd37-139a-4806-9326-d1f4e66934c0

**Comment by Moshyfawn** [comment]
`cmd-rightclick`
