### ISSUE TITLE
Python variable highlighting

### ISSUE THREAD

**Issue by Whyhow314** [zed-industries/zed#11666]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Python variables and parameters are highlighted according to editor.foreground in the theme, not the syntax setting for variables.

### Environment

Zed: v1.0.0 (Zed Preview)
OS: Linux 1.0.0
Memory: 30.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot_20240510_123639](https://github.com/zed-industries/zed/assets/22210734/d57e3043-ad8d-406f-ae3c-7bc55c8bcbab)
In Gruvbox Dark, variables such as `gen` and `vals` are `#ebdbb2` from editor.foreground, rather than `#83a598` from variable.

**Comment by JosephTLyons** [comment]
This is now available in [v0.136.0-pre](https://zed.dev/releases/preview/0.136.0).

**Comment by Nigel007** [comment]
Hey, I updated today and am currently on v0.136.2 and it still isn't highlighted. I'm not sure why. Did you mean v0.137 instead?
