### ISSUE TITLE
Zed missing MacOS `Services` menu item breaks global keyboard shortcuts

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#11663]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It happened the MacOS custom system shortcuts stopped being accepted within ZED. In particular, I have system-wide defined shortcut to ZOOM the operational window, such as `CMD+OPT+z`, which will maximize any system window to full screen size. As such, since one of recent releases the shortcut stopped working in ZED (of course still works in other applications). 

I reckon, the issue might be related to `F` keys being outright ignored: https://github.com/zed-industries/zed/issues/11618#issuecomment-2104799616

### Environment

Zed: v0.135.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

See description above.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

There is no log generated for the event as if the key combination was outright ignored

**Comment by TeamPuzel** [comment]
Zed is not following the Cocoa documentation 😉 and is not adding the `Services` menu item which is what contains global shortcuts.

Relevant docs: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SysServices/Articles/menu.html

> The Services menu is included in the default nib file created by Xcode and Interface Builder for Cocoa applications. If the application’s menu is instead created programmatically, you need to designate a Services menu using the NSApplication method setServicesMenu:. If an application registers for services (see [Using Services](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SysServices/Articles/using.html#//apple_ref/doc/uid/20000854-CEGDDHJJ)), the appropriate items are automatically available in the Services menu.

It should be possible to fix in a few lines of code.

**Comment by krstp** [comment]
Correct, this refers to global shortcut.

**Comment by notpeter** [comment]
I can reproduce this is still broken with Zed 0.150.x, both if you set define a global or app specific shortcut via System Preferences.  You can use this as a temporary workaround:

```json
  {
    "bindings": {
      "cmd-alt-z": "zed::Zoom"
    }
  },
```

A related issue with handling Menu-item invoked shortcuts:
- https://github.com/zed-industries/zed/issues/7544
