### ISSUE TITLE
Cannot jump to an untitled file from the multi-buffer

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#11661]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

_<Title and screencast>_

### Environment

Zed: v0.136.0 (Zed Nightly 981a143e9b03fe48d9640524c5004600a29f9845)
OS: macOS 14.4.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/ace87402-350c-42a6-adb1-07a0458dfe83

**Comment by notpeter** [comment]
This is still an issue in Zed 0.155.0.
