### ISSUE TITLE
`"vim":{"use_system_clipboard": "never"}` in conjunction with multi-cursor paste, combines each region in every paste location

### ISSUE THREAD

**Issue by alecthomas** [zed-industries/zed#11687]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Add the above setting, then use multi-cursors to select > 1 region, yank the region, then paste it. All N yanked regions are duplicated at every paste point. Removing the above setting works as I would expect, pasting each individual region at its corresponding cursor position.

The video below illustrates the issue.

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 14.4.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="331" alt="image" src="https://github.com/zed-industries/zed/assets/41767/7c058042-cca9-4bdf-92a6-530596d76034">

Here's a video illustrating what happens. If the above setting is removed, multi-cursor paste works correctly.

https://github.com/zed-industries/zed/assets/41767/a09101dd-efe9-4786-a7b1-dcfa10bc610e

**Comment by ConradIrwin** [comment]
Fixed by #13025

**Comment by alecthomas** [comment]
Yay thanks!
