### ISSUE TITLE
Link is broken in the document of javascript language

### ISSUE THREAD

**Issue by postbird** [zed-industries/zed#11690]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://zed.dev/docs/languages/javascript

configuration is broken

how should we contribute the document

![image](https://github.com/zed-industries/zed/assets/16200574/0a5e551b-fcc4-4c45-b12b-98344201214d)

### Environment

document

**Comment by Moshyfawn** [comment]
You can find the Zed documenation files exposed in [the `docs` folder](https://github.com/zed-industries/zed/tree/main/docs/src).

**Comment by JosephTLyons** [comment]
Fixed via: https://github.com/zed-industries/zed/pull/11685
