### ISSUE TITLE
Allow creating new folders in the "File > Open..." file picker

### ISSUE THREAD

**Issue by leftbones** [zed-industries/zed#11706]
### Check for existing issues

- [X] Completed

### Describe the feature

This is a super minor gripe, but on VS Code whenever I start a new project, I typically would go to "Open Folder" and then create the new project folder from there, then open it. I noticed today that Zed doesn't have the "New Folder" button in that file dialog. If it's possible to enable that, it would be appreciated!

**Comment by MatheusDCasanova** [comment]
Hello there!

It seems this one has been solved in #12121, correct me if I'm wrong.

**Comment by notpeter** [comment]
Closing. @leftbones Feel free to reopen if this did not solve your issue.
Thanks @MatheusDCasanova for catching that.
