### ISSUE TITLE
Selecting Text Is Extremely Slow

### ISSUE THREAD

**Issue by Itsnotdone** [zed-industries/zed#11717]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Text selection lags, which makes zed hard to use. Ignore the fact that I use C# in the recording, I was testing it. Exactly the same is happening in Rust and other languages

### Environment

Zed: v1.0.0 (Zed Dev df00854bbcae6da12e2ea9d99bdee11234488102)
OS: Linux 1.0.0
Memory: 15.6 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/78795073/9deed04a-91f0-40e7-91c8-2a2af5b6100f

**Comment by Itsnotdone** [comment]
Hmm, scrolling is also slow, I think the whole text rendering is broken

**Comment by osiewicz** [comment]
Were you building Zed from source or using your own build?

**Comment by Itsnotdone** [comment]
> Were you building Zed from source or using your own build

I builded zed from source

**Comment by osiewicz** [comment]
Are you building it in release mode?

**Comment by Itsnotdone** [comment]
> Are you building it in release mode?

Yes

**Comment by Itsnotdone** [comment]
hm, I have changed branch (version) to 0.134.4 and it works perfectly :thinking:

**Comment by Itsnotdone** [comment]
ohgod, I'm so dumb, I've compiled the zed in debug mode (at first) and then copied it in the Apps folder in my Documents, then I compiled it in release mode and I didn't copied the executable compiled in release mode

**Comment by osiewicz** [comment]
Heh, let the person who hasn't had that happen to them cast the first stone. 😛
