### ISSUE TITLE
Delete key does not work in the editor

### ISSUE THREAD

**Issue by ErrolFernandes** [zed-industries/zed#11713]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the editor when I press the delete key it does not delete anything but works in terminal.
Also works with option key which deleted complete words

### Environment

MacOS latest

**Comment by Moshyfawn** [comment]
Do you per chance have `"vim_mode": true` in your `settings.json` file?

**Comment by ErrolFernandes** [comment]
Yes

**Comment by Moshyfawn** [comment]
So you are in Vim `NORMAL` mode, where you can jump around in the code, but you can't edit it - hence the delete button doesn't work. When you press `i`, you are in `INSERT` mode, where you can edit the text.

If you accidentally switched on the Vim mode, you can switch it off by setting `"vim_mode": false` or by deleting the line completely.

**Comment by ErrolFernandes** [comment]
Oh thankyou very much.

**Comment by Moshyfawn** [comment]
Np! I'm going to close this issue because it's working as intended, but feel free to ask if you still have any questions.
