### ISSUE TITLE
The additional documentation popover will change the height of the completions box

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#11722]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the documentation popover is displayed, the height of the completion box is increased to accommodate the popover. This can cause jarring UI height changes when the popover is displayed and hidden. If the height of the documentation popover content is slightly greater than the height of the completion box, the completion box will appear broken / misaligned.

Example case: trigger `IntoElement` suggestions and navigate the suggestions popover. https://github.com/zed-industries/zed/blob/19994fc19097aa5ee91f43de0182d5f15eb59ad9/crates/breadcrumbs/src/breadcrumbs.rs#L3

### Environment

Zed: v0.136.0 (Zed Nightly f550f23b97bcb0d900d7c321af7d91d52d97160e)
OS: macOS 14.4.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/5acc5c31-a9f3-4307-ae99-4fc9ce8757ab

**Comment by JosephTLyons** [comment]
This is now available in Zed [v0.136.0-pre](https://zed.dev/releases/preview/0.136.0).
