### ISSUE TITLE
`tabs.git_status` default value inconsistency 

### ISSUE THREAD

**Issue by ledignacio** [zed-industries/zed#11727]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `tabs.git_status` value differs between the default settings and the one shown in the autocomplete hint.

| Default Settings |  ~/.config/zed/settings.json |
| ------ | ------ |
| <img width="492" alt="Default settings" src="https://github.com/zed-industries/zed/assets/21125201/99218076-c5de-460f-89aa-44216ff2c540"> | <img width="872" alt="User custom settings" src="https://github.com/zed-industries/zed/assets/21125201/49940405-8fcd-4321-8e38-b2be38e4886b"> |

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment]
This has already been fixed on `main` and will be added to Zed Preview next Wednesday.

https://github.com/zed-industries/zed/blob/19994fc19097aa5ee91f43de0182d5f15eb59ad9/crates/workspace/src/item.rs#L70-L73
