### ISSUE TITLE
cannot disable copilot

### ISSUE THREAD

**Issue by gabrielalexandrelopes** [zed-industries/zed#11735]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The option to hide the copilot from the task bar is not working

### Environment

Zed: v0.135.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/133671070/fa1e3ef5-3a04-4e6d-8109-ab5d8b7527b2

**Comment by maxdeviant** [comment]
Does it work if you use this setting?

```json
{
  "features": {
    "inline_completion_provider": "none"
  },
}
```

**Comment by gabrielalexandrelopes** [comment]
Yes, that works! Thanks!

**Comment by JosephTLyons** [comment]
Is this issue good to be closed out?

**Comment by gabrielalexandrelopes** [comment]
yes

**Comment by gabrielalexandrelopes** [comment]
thanks for the help
