### ISSUE TITLE
Use `"double_click_in_multibuffer": "open"` as the default

### ISSUE THREAD

**Issue by ophilli** [zed-industries/zed#11733]
### Check for existing issues

- [X] Completed

### Describe the feature

When using the `Project Diagnostics` or `References to "..."` features I want to be able to click through to the file & line where the problem or reference exists.

For example, my `Project Diagnostics` page currently has 2 errors and 48 warnings. I want to be able to scroll through that list & click into one of the errors & then look at it in its full and original context.

**Comment by JosephTLyons** [comment]
Hey @ophilli - are you wanting to jump to the original buffers from the multi-buffer? If you put your cursor in the multi-buffer excerpt and run `alt-enter`, you should be able to jump to the location in the original buffer. Note that this works with multiple cursors stretching accross multiple excerpts in a multi-buffer.

In the UI, you can also click on the headers or dividers between excerpts to jump to the original buffer.

If you want to simply be able to double click to jump to an excerpt, you can add this to your settings file:

```json
"double_click_in_multibuffer": "open"
```

**Comment by ophilli** [comment]
Yes, that is exactly what I wanted! I think that opening on double click should be the default behavior. I see that it was for a brief time #9196 and then switched back in #9214. It seems the original issue for this is #5275.

I think that click-through to the original buffer should be the default.

**Comment by JosephTLyons** [comment]
Hey @ophilli - I've went ahead and updated your title to match the request of making this a default.

**Comment by SomeoneToIgnore** [comment]
Based on the internal discussions, we do not want to make it the default currently, striving to keep editing in multibuffer close to editing in singleton buffer — where the double click selects the line.

The main reason for that is the whole concept of the multibuffer as not just the panel with the results, but something editable.
Instead, we would like to improve the visibility of the `alt-enter` command that is now considered to be a preferred way to navigate into a corresponding buffer.

So, I will close this issue as not planned currently — whatever the default is, there will be people against it, but at least now it aligns with the internal preferences.

**Comment by rseymour** [comment]
Glad I found this, I was permanently trapped in the minibuffer, like a little prison of not quite enough context to edit and fix the problem and no way to get to the file.
