### ISSUE TITLE
auto-update not supported for OS "windows"

### ISSUE THREAD

**Issue by Theyashsawarkar** [zed-industries/zed#11753]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

 ❯ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 18.63s
     Running `target\debug\Zed.exe`
[2024-05-13T19:44:02+05:30 ERROR auto_update] auto-update failed: error:auto-update not supported for OS "windows"
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: NotSupportedError" at crates\gpui\src\platform\windows\window.rs:946:14
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: git_midx_writer_dump
  10: git_midx_writer_dump
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: DispatchMessageW
  16: DispatchMessageW
  17: CallNextHookEx
  18: KiUserCallbackDispatcher
  19: NtUserCreateWindowEx
  20: CreateWindowExW
  21: CreateWindowExW
  22: CreateWindowExW
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: CoreUICreateEx
  39: CoreUICallReceive
  40: CoreUICallReceive
  41: CoreUICallReceive
  42: CoreUICallReceive
  43: CoreUICallReceive
  44: CoreUICallReceive
  45: CoreUICallReceive
  46: CoreUICallReceive
  47: DispatchMessageW
  48: DispatchMessageW
  49: GetClassLongW
  50: KiUserCallbackDispatcher
  51: NtUserPeekMessage
  52: PeekMessageW
  53: PeekMessageW
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: git_midx_writer_dump
  65: BaseThreadInitThunk
  66: RtlUserThreadStart

error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)

### Environment

i use windows 11 

i have installed rust and done all the prerequesits stuff already .

**Comment by CharlesChen0823** [comment]
relate blade not support

**Comment by JunkuiZhang** [comment]
The panic reason is "NotSupportedError", which means your gpu dose not support some vulkan features, since Zed use vulkan as backend currently. You can try update your gpu driver, updating driver solves this issue in most cases.

**Comment by JunkuiZhang** [comment]
> So how can we fix this ?

In most cases, you can resolve this issue by upgrading the GPU driver.

**Comment by cuong21951** [comment]
> > So how can we fix this ?
> 
> In most cases, you can resolve this issue by upgrading the GPU driver.

I'm using 6800xt. I did re-install the amd driver but still not supported. Any ideas ?

**Comment by JunkuiZhang** [comment]
> I'm using 6800xt. I did re-install the amd driver but still not supported. Any ideas ?

Rae you using the latest driver? If not, you can download it from [here](https://www.amd.com/en/support/downloads/drivers.html/graphics/radeon-rx/radeon-rx-6000-series/amd-radeon-rx-6800-xt.html).

**Comment by laok00** [comment]
my gpu is UHD630. I also upgrade my driver. But the problem is still exsits. any idea?

**Comment by nt8r** [comment]
It's worth noting that this crash has nothing to do with the titular error message, which is an error but not a fatal one. This crash is the `.unwrap()` inside [`windows_renderer::windows_renderer`](https://github.com/zed-industries/zed/blob/dea928b00caf853b60fc19890dcb557beb814936/crates/gpui/src/platform/windows/window.rs#L964).

**Comment by notpeter** [comment]
I'm going to close this as stale.  If you are having trouble running on windows please search for [zed issues label:windows](https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+label%3Awindows) before opening a new issue.

Thanks fore reporting.
