### ISSUE TITLE
linux: Only one instance of zed can run at a time after recent commit

### ISSUE THREAD

**Issue by DissolveDZ** [zed-industries/zed#11770]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't know whether this was intentional or not but after this commit https://github.com/zed-industries/zed/pull/11585 Zed can't have multiple instances open which is really annoying as I often use multiple instances of my text editor

### Environment

Zed: v1.0.0 (Zed Dev 6429c038107249f04245aa810ac78a8530da3c49)
OS: Linux 1.0.0
Memory: 23.4 GiB
Architecture: x86_64

**Comment by ConradIrwin** [comment]
@DissolveDZ Sorry for the surprise!

Zed now ships two binaries: `zed` the main editor process, and `cli` that manages zed (as happens on macOS, etc.)

You should be able to use the `cli` tool to get the behaviour you're used to.

I do realize this is a bit confusing, so I have two thoughts:
* Maybe we could try and bundle these into one binary, which requires a bit of thought to get right.
* Maybe we should rename `cli` to `zed` and `zed` to `zed-daemon` or something.

Thoughts?

**Comment by 435vic** [comment]
I think renaming the binaries for clarity is the simplest solution.
However, `Platform<LinuxPlatform>::path_for_auxiliary_executable` is not implemented yet on Linux, so I can't use zed's built in command to install it. 
From what I can gather from just `Ctrl-F`ing the repo, right now additional binaries that are included in the Mac bundle just aren't built on other platforms (?). Do I have to manually `cargo build -p cli` for the CLI for now?

**Comment by ConradIrwin** [comment]
The tar.gz file from https://github.com/zed-industries/zed/releases should contain both zed and the cli (at the moment). You can install on most systems with `curl https://zed.dev/install.sh | bash` (see notes on [supported platforms](https://zed.dev/docs/remote-development#supported-platforms)).

@mikayla-maki has made some progress on the single-binary approach, so that may make this obsolete.

**Comment by ConradIrwin** [comment]
There are some notes on https://zed.dev/docs/development/linux how to fix this
