### ISSUE TITLE
Font rendering break when switching between recent project

### ISSUE THREAD

**Issue by filipjanevski** [zed-industries/zed#11771]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I switch to another project, the font rendering breaks and just displays gibberish text. I use the SF Mono font from Apple.

This happens in the whole application (UI, Editor, Terminal). Here is a screenshot of the issue:

<img width="740" alt="Screenshot 2024-05-13 at 23 39 13" src="https://github.com/zed-industries/zed/assets/33383452/12e53217-7deb-497f-b419-34bdc509c571">

My `settings.json` is set to the following:

```json
{
  "terminal": {
    "font_family": "SF Mono"
  },
  "font_size": 14,
  "font_family": "SF Mono",
  "ui_font_family": "SF Mono",
  "buffer_font_family": "SF Mono"
}
```

This issue started with the latest 0.134.4 update. It seems to happen with some fonts, for example it happens with SF Mono and JetBrains Mono but not with PT Mono.

### Environment

Zed: v0.134.4
MacOS: 14.4.1
Memory: 8GB
Architecture: aarch64 (M2)

**Comment by notpeter** [comment]
I'm going to close this as stale.  If this is something you're still seeing with a current version of Zed, please comment below and I'm happy to reopen.
