### ISSUE TITLE
Tasks cache the ZED_* variables

### ISSUE THREAD

**Issue by clauswitt** [zed-industries/zed#11792]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With a task definition like this:

```json
{
    "label": "Test task",
    "command": "env | grep ZED",
    "use_new_terminal": false,
    "allow_concurrent_runs": false,
    "reveal": "always"
  }
```

Once I run this task once the values of the ZED_* variables never change. 

ZED_COLUMN=41
ZED_FILE=/Users/clauswitt/Documents/Projects/Work/fliva/.zed/tasks.json
ZED_ROW=13
ZED_TERM=true
ZED_WORKTREE_ROOT=/Users/clauswitt/Documents/Projects/Work/fliva

Running it again with a different file, column and row will print the same variables. 

I would expect that using the task:spawn (shift+opt+t) would reset these variables and that task:rerun (opt+t) would use the cached values. 

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 14.2.1
Memory: 36 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Hey, this is actually expected (although admittedly a bit confusing); if there's a recent run in history with the same label as it's template, we leave out the template.
I've just merged a PR that does not filter out templates; see https://github.com/zed-industries/zed/pull/11752

As for `task::Rerun`, it takes an explicit argument (`reevaluate_context`) which drives whether the variables are reevaluated or not.

**Comment by clauswitt** [comment]
Just tried this in the preview; that solves the issue for me.

**Comment by brundonsmith** [comment]
I agree with @clauswitt that this behavior is surprising. It's intuitive that `task:rerun` might re-use the previous variables, but it's strange that `task:spawn` would quietly do a not-quite-fresh run that's based on the previous one (but only if the labels are the same). I believed for a week that this was a bug in Zed before I found this thread
