### ISSUE TITLE
Linux user collaboration keyring

### ISSUE THREAD

**Issue by mintyleaf** [zed-industries/zed#11800]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using linux build sign in to github then restart Zed - you need to sign in again
Using seahorse we can observe that zed-github-account (with empty password, eventually) entry exists
After another sign in that entry duplicates

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 7.6 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I don't really need that collaboration feature, so i logging in mostly to get rid of "Sign in" text at the title bar

It will be great to have an ability to hide all collaboration features from title bar, or, since we have "Sign out" option at the user menu it will be more trivial to put "Sign in" entry there to keep the title bar clean

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15309633/Zed.log)

**Comment by mikayla-maki** [comment]
This is intended behavior!

**Comment by mikayla-maki** [comment]
See here: https://github.com/zed-industries/zed/blob/e7214a429d2ada250d122ba18192c7a83d51a7d1/docs/src/development/linux.md?plain=1#L97
