### ISSUE TITLE
Terminal button sometimes multiplies when saving settings file with errors

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#11808]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open a terminal pane, launch something long-running but not very chatty (`cargo watch` or the like)
- Add some invalid noise to settings.json hit save
- Observe terminal button proliferation in status bar

Noticed this while faffing about trying to get Typst and Vale language servers to run together. Can't seem to reproduce this consistently, unfortunately.

### Environment

Zed: v1.0.0 (Zed Dev 4301d065ff61e1cae607dfeb3d52fab6caff355e)
OS: Linux 1.0.0
Memory: 125.7 GiB
Architecture: x86_64

**Comment by bennetbo** [comment]
Sounds like #9688 to me (although it's another button)?

**Comment by CharlesChen0823** [comment]
I might known what problems.
