### ISSUE TITLE
Considering settings on Linux (gsettings)

### ISSUE THREAD

**Issue by spikespaz** [zed-industries/zed#11823]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to see the Linux build use a standard configuration file (JSON, TOML), instead of Gsettings. I'm not always a fan of GNOME project's abstractions, I think that bringing the Registry from Windows to Linux was not a good move, and it is not a simple solution. A simple solution would be using `XDG_CONFIG_HOME` same as the rest of the ecosystem.

Why? Well, for starters, Gsettings is not very easy to manage via Nix. It would be much easier to KISS, because any program can read/write a text file, whereas using Gsettings requires special care and extra API compliance (which may change).

**Comment by mikayla-maki** [comment]
We're not going to be using gsettings to store our own. But it would be nice if we could read your linux client's settings to integrate smoothly with it.

**Comment by spikespaz** [comment]
> We're not going to be using gsettings to store our own. But it would be nice if we could read your linux client's settings to integrate smoothly with it.

What is a "Linux client" and what settings did you want to integrate with?

**Comment by mikayla-maki** [comment]
Sorry, ‘Linux Computer’, and things like double click speed or light mode vs. dark mode.

**Comment by spikespaz** [comment]
Ah, so configuration options will have a `system` or `System Settings` value that defers to heuristics that interact with arbitrary platform APIs to retrieve the users' desired global preferences if available.

Good, that's the way everything else works.

Thanks!
