### ISSUE TITLE
Sort ShowCompletions results

### ISSUE THREAD

**Issue by Spoutnik97** [zed-industries/zed#11861]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to sort completions results ? 

For example when I tap `ctrl+space` I get this pop up menu for my React App, but I don't use HTMLOptGroupElement at all and need to scroll down up to my local components in the "#shared" directory.

![image](https://github.com/zed-industries/zed/assets/30442116/8de6ac45-aac3-4480-a75a-b8d135bd77df)
 
 The problem is that I need to scroll for each import, and most of the time I tap "enter" on the wrong import because it is the first one.

I already added `"autoImportFileExcludePatterns": ["**/node_modules/@mantine/core"]`to my settings in `lsp.typescript-language-server.initialization_options.preferences` to ignore some imports, but would like to avoid adding the whole list. Moreover I think that `HTMLOptGroupElement` is from the HTML language, what I can't exclude

**Comment by JosephTLyons** [comment]
This sounds similar to:

- https://github.com/zed-industries/zed/issues/4327

**Comment by Spoutnik97** [comment]
Yes, it is quite the same.

If there is an option to choose the order, it could be better

**Comment by notpeter** [comment]
I'm going to close this issue in favor of the more general:

- https://github.com/zed-industries/zed/issues/12698
- https://github.com/zed-industries/zed/issues/4327

Please 👍 vote on those to increase visibility and subscribe to track their progress.

Thanks for reporting @Spoutnik97!
