### ISSUE TITLE
Rename "upper camel case" to "pascal case"

### ISSUE THREAD

**Issue by corneliusio** [zed-industries/zed#11865]
### Check for existing issues

- [X] Completed

### Describe the feature

It seems incredibly odd to refer to "pascal case" as "upper camel case" when using the `editor: covert` commands and I'm curious if there was a specific rational behind this that I'd be missing.

Would be easier to quickly access these commands from the command palette if they weren't both using the same name.

<img width="557" alt="Screenshot 2024-05-15 at 10 44 22 AM" src="https://github.com/zed-industries/zed/assets/4140885/7ac5b76e-f92b-40cd-80a2-41602f6ace67">

### If applicable, add mockups / screenshots to help present your vision of the feature

**Comment by JosephTLyons** [comment]
Hey @corneliusio - I named the case conversion commands (mostly) after Sublime Text's commands:

<img width="602" alt="SCR-20240515-opzf" src="https://github.com/zed-industries/zed/assets/19867440/55b2753c-bf93-4f4f-816e-f8bd9993ea57">

It is a bit difficult to change these now, as we'd be breaking users who might have a custom binding set up here.

**Comment by corneliusio** [comment]
@JosephTLyons Ahh, I see. That's understandable, I suppose that would be a hassle at this point. 

I'm actually coming from Sublime Text which has been my daily driver for the last 10+ years, but I was using a third-party package for case conversion and became very accustomed to reaching for "PascalCase" (though I can't count the number of times I've accidentally switched to Pascal syntax instead 😆). It's certainly just a "nice to have" and understand the reluctance to muck up users' bindings here even if it might be technically correct.

Appreciate taking the time to explain and all the hard work on Zed!

**Comment by JosephTLyons** [comment]
No worries - keybindings aren't totally set in stone - we've changed some in the past and I imagine there might be a day where we really clean them up before going to 1.0 - this could be something we consider.
