### ISSUE TITLE
Support natural scroll on Linux/wayland

### ISSUE THREAD

**Issue by Mythique** [zed-industries/zed#11874]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have either/both :
- An option in the setting to inverse the scroll.
- Get the settings in from the Desktop Environment (or wayland directly?) to know if "natural scroll" is selected in the DE settings.

**Comment by bbb651** [comment]
@Mythique can you make sure #11937 fixes it for you? It's already merged into `main`

**Comment by Mythique** [comment]
@bbb651 Tested main, it is indeed fixed for me. Thanks!

**Comment by bbb651** [comment]
Great! Can you close the issue as fixed? I'm not a maintainer I don't have permissions
