### ISSUE TITLE
Digraphs, vim keybindings

### ISSUE THREAD

**Issue by vmchale** [zed-industries/zed#11871]
### Check for existing issues

- [X] Completed

### Describe the feature

Vim has digraphs; by typing `<C-K><char><char>` one can input exotic characters-π, ⊢ etc.

https://vimhelp.org/digraph.txt.html#digraphs-use

Digraphs would be wonderful and vim keybindings would be even better!

**Comment by Benjamin-Davies** [comment]
I would like to work on this
