### ISSUE TITLE
On nvidia propritary driver zed is slow on linux 

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#11870]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With nvidia proprietary driver compile zed and run on linux rendering is slow 
Nvidia-drm [ERROR util] crates/zed/src/main.rs:897: Is a directory (os error 21) DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
there is this weird error i think its nvidia driver proprietary issue or somethink from blade

### Environment

annother issue too when i use the command palette
![image](https://github.com/zed-industries/zed/assets/704477/59f85691-4d7f-45a4-a9ed-2a705c8a20da)

Zed: v1.0.0 (Zed Dev 1c62839295d980039836ea90c93350eaba5340fc)
OS: Linux 1.0.0
Memory: 23.4 GiB
Architecture: x86_64

(Fedora 40 + nvidia-driver + X11 )

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Capture vidéo du 2024-05-15 19-53-58.webm](https://github.com/zed-industries/zed/assets/704477/2f85c02b-a9c7-4f0f-817f-7e61d50c2150)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

![image](https://github.com/zed-industries/zed/assets/704477/ac9ed925-0f9d-478b-a297-65b3825aecd9)

**Comment by yodatak** [comment]
compiled with cargo run --release

**Comment by yodatak** [comment]
ok maybe its linked to my container because when i execute vkcube on my container i got LLVMPIPE on CPU ( it could be intersting to add this info of what GPU is used in zed info)

<pre><font color="#9A348E"></font><span style="background-color:#9A348E">yodatak </span><span style="background-color:#DA627D"><font color="#9A348E"></font></span><span style="background-color:#DA627D"> ~ </span><span style="background-color:#FCA17D"><font color="#DA627D"></font></span><span style="background-color:#86BBD8"><font color="#FCA17D"></font></span><span style="background-color:#06969A"><font color="#86BBD8"></font></span><font color="#06969A"></font>   
 <font color="#33658A"></font><span style="background-color:#33658A"> 20:00 </span><font color="#33658A"> </font><font color="#C397D8">vkcube</font>                                                                                                                                                          <font color="#86BBD8"></font><font color="#87320E"><b>⬢ [fedora-toolbox:40]</b></font><font color="#86BBD8"></font> 
DRM kernel driver &apos;nvidia-drm&apos; in use. NVK requires nouveau.
Selected GPU 0: llvmpipe (LLVM 18.1.1, 256 bits), type: Cpu
</pre>

**Comment by yodatak** [comment]
when i execute in my nvidia enabled distrobox it use my nvidia-gpu so its works great so its just a llvm gpu based been slow

<pre><font color="#9A348E"></font><span style="background-color:#9A348E">yodatak </span><span style="background-color:#DA627D"><font color="#9A348E"></font></span><span style="background-color:#DA627D"> …/zed </span><span style="background-color:#FCA17D"><font color="#DA627D"></font></span><span style="background-color:#FCA17D">  main  </span><span style="background-color:#86BBD8"><font color="#FCA17D"></font></span><span style="background-color:#06969A"><font color="#86BBD8"></font></span><font color="#06969A"></font>   
 <font color="#33658A"></font><span style="background-color:#33658A"> 20:02 </span><font color="#33658A"> </font><font color="#C397D8">vkcube</font>                                                                                                                                                                                                          <font color="#86BBD8"></font><span style="background-color:#86BBD8">  v1.78.0 </span><font color="#87320E"><b>⬢ [fedora-toolbox:39]</b></font><font color="#86BBD8"></font> 
Selected GPU 0: NVIDIA GeForce RTX 3060, type: DiscreteGpu</pre>

**Comment by someone13574** [comment]
> With nvidia proprietary driver…

> NVK requires nouveau.

You aren’t using the proprietary vulkan driver, you are using NVK, hence the slowdown. It’s probably even worse since you seem to be mixing the open source Vulkan driver with the proprietary driver.

**Comment by yodatak** [comment]
Yes it was caused by the Nvidia runtime that don't run fine so we can close that

**Comment by lucasAlonso** [comment]
same issue here, same specs. How did you force to use the correct driver?

**Comment by someone13574** [comment]
> You have to run it without a container or with a container with nvidia runtime, flatpak version will fix this i think @ lucasAlonso

The flatpak version as it currently stands will not fix this because it doesn't run in the container.
