### ISSUE TITLE
How to debug my code

### ISSUE THREAD

**Issue by gu-xiaohui** [zed-industries/zed#11886]
### Check for existing issues

- [X] Completed

### Describe the feature

I am developing TypeScript using the Zed editor, but I haven't found any way to debug my code with breakpoints.

**Comment by SomeoneToIgnore** [comment]
Zed does not support any debuggers yet, tracking issues are https://github.com/zed-industries/zed/issues/5065 and https://github.com/zed-industries/zed/issues/5307
