### ISSUE TITLE
Vim mode: Difficulties attempting to rename a symbol

### ISSUE THREAD

**Issue by kolunmi** [zed-industries/zed#11882]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello! When attempting to rename a symbol using the `editor: rename` command in vim mode, regular keystrokes seem to randomly cancel the operation.

[Screencast_from_2024-05-15_11-56-22.webm](https://github.com/zed-industries/zed/assets/113054217/69ab1729-81a6-48ad-901b-2f1e37980760)

In this video, trying to type a character into the entry will cause it to exit and return to the editor.

Thank you!

### Environment

```
Zed: v0.136.0 (Zed Preview)
OS: Linux 1.0.0
Memory: 31.1 GiB
Architecture: x86_64
```

**Comment by CharlesChen0823** [comment]
I found in `Insert` mode will be easy rename, but in `Normal` mode, need first type `i` to `Insert` mode, then will work.

**Comment by ConradIrwin** [comment]
This doesn't seem to be broken for me (though we did recently make some changes in this area).

Are there specific keystrokes or contexts that cause this for you?

**Comment by kolunmi** [comment]
@CharlesChen0823 That works! A little jank though

@ConradIrwin Hey, this problem happens at random from what I can tell, unless you press `i` first, as Charles noted. However, I'm on linux, Gnome 46 with the Jetbrains base keymap, if that is helpful. Can you replicate it now?

Thank you both!

**Comment by 0x2CA** [comment]
> This doesn't seem to be broken for me (though we did recently make some changes in this area).
> 
> Are there specific keystrokes or contexts that cause this for you?

hi,When I found this issues I tried it and it also reproduced, but it was only a one time reproduction and later it was normal again, unknown cause

**Comment by msanft** [comment]
It seems that the problem is that if you're in normal mode, and then try to rename a symbol, it will give you the illusion of being in insert mode (e.g. the cursor style), even though you aren't. I'd suggest that renaming a symbol should always bring you into insert mode, and when done renaming, you should be put back into whatever mode you've been in before.

**Comment by ConradIrwin** [comment]
@msanft are you on Mac or linux? Although I don't know why there would be a difference, it does seem like there is.

**Comment by msanft** [comment]
> @msanft are you on Mac or linux? Although I don't know why there would be a difference, it does seem like there is.

I'm on Linux

**Comment by eddiebergman** [comment]
I found that remapping this in my vim keymap has made this very stable. Triggering this rename manually through the command pallete had the issues described above.

```json
  {
    "context": "Editor && (vim_mode == normal || vim_mode == visual) && !VimWaiting && !menu",
    "bindings": {
      // put key-bindings here if you want them to work in normal & visual mode
      "c c": "editor::Rename"
    }
  }
```

**Comment by JosephTLyons** [comment]
This is now in today's [preview release](https://zed.dev/releases/preview/0.145.0).
