### ISSUE TITLE
How to scroll down hover tooltips in Vim mode

### ISSUE THREAD

**Issue by rendaoer** [zed-industries/zed#11883]
### Check for existing issues

- [X] Completed

### Describe the feature

How to scroll down hover tooltips in Vim mode
<img width="976" alt="image" src="https://github.com/zed-industries/zed/assets/46780118/7c3a5445-d568-4f25-a6c6-b3139ef55f83">
When the hover tooltip is too long, I can't seem to scroll it without using the mouse

### If applicable, add mockups / screenshots to help present your vision of the feature

Use ctrl+u ctrl+d to scroll in hover tooltip, like helix editor

**Comment by ConradIrwin** [comment]
This is not currently supported, but if you'd like to pair on making it, I'd love to help you: https://calendly.com/conradirwin/pairing.

**Comment by ConradIrwin** [comment]
Fixed by #12650. This will hit preview next week and stable the week after.

**Comment by jacksonludwig** [comment]
Not sure if it was a regression at some point, but seems this only works for hovers in insert mode (e.g. from completion items) rather than when explicitly viewing hover documentation (e.g. `K` in normal mode).
