### ISSUE TITLE
is:issue is:open Vim-like keybindings for "go to reference", "go to definition" et cetera 

### ISSUE THREAD

**Issue by tkgalk** [zed-industries/zed#11897]
### Check for existing issues

- [X] Completed

### Describe the feature

It's pretty much universal at this point that "gd" and "gr" (or "<leader>gd", "<leader>gr") are "go to definition", "go to reference".

Other than doing those key bindings ourselves, it might be a good quality of life improvement for Vim mode devs? It seems "shift+k" got added for hover tooltip (great!) and these feel like valid next steps.

**Comment by mrnugget** [comment]
Yep:

https://github.com/zed-industries/zed/blob/8c681d0db3b804faa7167b02e748d7a526966edb/assets/keymaps/vim.json#L156-L157

See also: https://zed.dev/docs/vim#zed-specific-features

Did you not know that we had them or is your point that we don't have `gr`? (We do have `gA` for that, although I bind it to `gR`)

**Comment by tkgalk** [comment]
Interesting, I had trouble setting up my keymap, that might be why I assumed there is no binding for this. It seems everything is there, I think I'll close the issue. 👍🏻
