### ISSUE TITLE
cmd+s keybinding not working after the latest update

### ISSUE THREAD

**Issue by akashsokik** [zed-industries/zed#11907]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using macOS and I am trying to save file/s using the `cmd+s` keyboard shortcut, which used to work before however it suddenly stopped working. Tried changing the standard mapping and save it, it has not worked.

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @akashsokik - this is super strange! I'm not able to reproduce it - can you include a screencapture video?

**Comment by akashsokik** [comment]
Hey @JosephTLyons 

Here, https://github.com/zed-industries/zed/assets/145914738/3122885c-def6-4f5c-a91e-4ff19072075a. Hope it helps. thx.

**Comment by mmmoli** [comment]
I was experiencing this too.
Quit zed. Re-opened it. Checked for updates. Quit again for good measure.

When I came back, it was working again

**Comment by bennetbo** [comment]
Might be totally unrelated, but just to make sure: Another user reported a similar issue today (#11903). In this case the ChatGPT desktop client was intercepting cmd+s keypresses (https://github.com/zed-industries/zed/issues/11903#issuecomment-2114964496)

**Comment by akashsokik** [comment]
Turns out it's the same issue. I quit the ChatGPT desktop app and it worked as usual. thanks @bennetbo. Given it's duplicate with #11903, I will close this.
