### ISSUE TITLE
Cannot Save changes on Zed 0.136.0

### ISSUE THREAD

**Issue by sunilshenoy** [zed-industries/zed#11903]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just updated to Version 0.136.0 and am not able to save any changes made to files.

### Environment

Zed: v0.136.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/443598/be46165a-c354-4aea-b10a-948279af04e6

After making changes to the file I am unable to save changes in the current version.

**Comment by sunilshenoy** [comment]
Please ignore this. Turns out ChatGPT Mac Application being open was overriding the Ctrl+S keybinding.

**Comment by beamercola** [comment]
Solution if anybody needs:

<img width="692" alt="Screenshot 2024-05-17 at 11 18 40 AM" src="https://github.com/zed-industries/zed/assets/8060/3e50d35a-63f4-4918-b9c2-5d86d6fe6043">

**Comment by dwt** [comment]
Just Restarting the ChatGTP app also seems to have solved this for me.
