### ISSUE TITLE
zed can't find WaylandLib

### ISSUE THREAD

**Issue by Sebbito** [zed-industries/zed#11917]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After spending literal hours crafting a shell environment to build zed, it compiled and threw an error immediately after starting it.

Steps to reproduce:
1. Build zed in a nix-shell
2. Execute zed from command line `./target/release/Zed`
3. Error

Here's the nix-shell:
```nix
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    # nativeBuildInputs is usually what you want -- tools you need to run
    nativeBuildInputs = with pkgs.buildPackages; [
    alsa-lib
    expat
    fontconfig
    libgit2
    libgcc
    libxkbcommon
    pkg-config
    vulkan-loader
    wayland
    xorg.libxcb
    zlib
    ];
}
```

### Environment

OS: NixOS 24.05
WM: Hyprland (Wayland)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

No logs just this error:
```
thread 'main' panicked at crates/gpui/src/platform/linux/wayland/client.rs:267:49:
called `Result::unwrap()` on an `Err` value: NoWaylandLib
```

**Comment by jansol** [comment]
I use this `flake.nix` to get a shell for building zed locally and running said builds:

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = { self, nixpkgs }:
    let
      pkgs = import nixpkgs { system = "x86_64-linux"; };
      toolDeps = with pkgs; [
        pkg-config cmake python3 clang protobuf
      ];
      runtimeDeps = with pkgs; [
        expat freetype fontconfig vulkan-validation-layers
      ];
      libraryDeps = with pkgs; with xorg; [
        alsa-lib
        brotli
        bzip2
        libpng
        libX11
        libXcursor
        libXi
        libXrandr
        openssl
        zstd
        vulkan-loader
        vulkan-validation-layers
        wayland
        libxkbcommon
      ];
      libPath = pkgs.lib.makeLibraryPath libraryDeps;
    in
    {
      devShells.x86_64-linux.default = pkgs.mkShell {
        packages = toolDeps ++ runtimeDeps ++ libraryDeps;

        # Set environment variables
        LD_LIBRARY_PATH = "${libPath}:/run/opengl-driver/lib";
        PROTOC = "${pkgs.protobuf}/bin/protoc";
      };

      # You could also define extra shells or packages here
    };
}
```

(I could slim it down a bit more based on the nixpkgs package but this was a quick hack based on a `flake.nix` that I had lying around for another project already)

If you want to just use Zed on NixOS I recommend relying on the nixpkgs package instead (nixos-unstable channel). It tracks stable releases with a delay of a couple of days and has been very solid so far.
