### ISSUE TITLE
Project panel: select multiple files/folders, cut, paste with commands 

### ISSUE THREAD

**Issue by SeniorUI** [zed-industries/zed#11934]
### Check for existing issues

- [X] Completed

### Describe the feature

I would love to select multiple files/folders with keyboard

For example I'm using such commands to create, delete, rename files/folders. But there is no multiple select even with mouse.

```json
  "context": "ProjectPanel && not_editing",
    "bindings": {
      "shift-d": "project_panel::Delete",
      "shift-r": "project_panel::Rename",
      //...
```
Request for

```json
  "context": "ProjectPanel && not_editing",
    "bindings": {
      "x": "project_panel::Cut",
      "p": "project_panel::Paste",
      "v": "project_panel::Select" // as selecting folders in the macOS Finder (for example with holding Command key)
      //...
```

**Comment by JosephTLyons** [comment]
I think between the main request and comments, this issue might cover your needs. It has a handful of upvotes as well. Would you mind upvoting that issue and adding any extra details you want in a comment? I'll close this one as a duplicate. Feel free to let me know if there's enough difference between the issues to justify keeping this one open!

- https://github.com/zed-industries/zed/issues/4983
