### ISSUE TITLE
Incorrect lines indentation when interacting with git diff and git blame

### ISSUE THREAD

**Issue by unemil** [zed-industries/zed#11941]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It's my first issue report, don't judge me too harshly :)

When using **git diff** with **git blame**, indentation for deleted lines is triggered incorrectly.

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/34972940/5d64274c-9bc1-4fef-8597-ca67e92bc59d

**Comment by JosephTLyons** [comment]
Thanks for the report, @unemil!

**Comment by bennetbo** [comment]
Should be fixed by #12442
