### ISSUE TITLE
Settings window

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11959]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be useful to have a settings window, in addition to changing the Zed settings settings, it could change some of the default settings.

<img width="263" alt="Screenshot 2024-05-17 alle 10 47 19" src="https://github.com/zed-industries/zed/assets/20476002/032a3c2b-c618-4453-9716-6a745bbdc64c">

**Comment by notpeter** [comment]
We intend to implement a Zed Settings page at some point the future, but this issue is not actionable as-is. Thank you.
