### ISSUE TITLE
Re-expanded git add hunks appear in the wrong places on undo

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11956]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/20476002/332d8c8b-befc-49ea-9cae-bd054b01cb2d

### Environment

```
Zed: v0.136.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
The git hunk application interface and data structures are currently under active development and as such, this is issue will not be fixed as-is.  Thanks for reporting.
