### ISSUE TITLE
Information about commands when no file is open

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11957]
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode:
<img width="354" alt="Screenshot 2024-05-17 alle 09 46 00" src="https://github.com/zed-industries/zed/assets/20476002/3fcf74f1-eee4-43a6-8846-247335a6cb23">

Android studio:
<img width="291" alt="Screenshot 2024-05-17 alle 09 46 07" src="https://github.com/zed-industries/zed/assets/20476002/3feb6966-f71b-4aea-9386-a9d85ce5a420">

**Comment by notpeter** [comment]
There is active work to improve the Welcome screen and what is displayed by default in an empty project as part of onboarding.   We will not be implementing these suggestions at this time.  Thanks for reporting.
