### ISSUE TITLE
Duplicate keystrokes on linux after suspend

### ISSUE THREAD

**Issue by miwig** [zed-industries/zed#11966]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open Zed
2. Put the computer into suspend
3. Wake the computer
4. Type into any text input in Zed (editor, search, terminal, collab panel, chat)
5. Keystrokes are duplicated: characters appear twice
6. This also applies to additional windows created with Ctrl+O, but not to any applications other than Zed

### Environment

Zed: v1.0.0 (Zed Dev c1e291bc965e3f3c23969dead1ed93c4cc4502ae)
OS: Linux 1.0.0
Memory: 30.6 GiB
Architecture: x86_64

Gnome 46 on wayland

**Comment by bbb651** [comment]
I don't have suspend working on my system so I can't really test it, but it sounds like it's creating a duplicate seat, as we don't have multi-seat handling maybe adding a
```rs
if let Some(wl_pointer) = &state.wl_pointer {
    wl_pointer.release();
}
```
before [this line](https://github.com/zed-industries/zed/blob/main/crates/gpui/src/platform/linux/wayland/client.rs#L569) would fix it? I found the [same issue in wezterm](https://github.com/wez/wezterm/issues/1497) and [this commit](https://github.com/wez/wezterm/commit/bd9088372a31894bff17ed1720fc5e52db11bb44) fixed it but I don't really understand the code..
