### ISSUE TITLE
windows: work zed with Zed rust-analyzer with hang windows unresponse some seconds

### ISSUE THREAD

**Issue by CharlesChen0823** [zed-industries/zed#11978]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When work zed with Zed, in rust-analyzer running, window will hang unresponse some seconds.

### Environment

Zed: v0.137.0 (Zed Dev 66e873942dca65f9f44be3c8ffe033eb56f0b7b9)
OS: Windows 10.0.22631
Memory: 63.2 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
Closing as outdated.
