### ISSUE TITLE
Go to File sort order priority

### ISSUE THREAD

**Issue by bcardarella** [zed-industries/zed#11970]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently Go to File favors history over exact match:

<img width="410" alt="Screenshot 2024-05-16 at 5 02 22 PM" src="https://github.com/zed-industries/zed/assets/18524/ced93886-2a92-4a4c-ad9b-e6b6e9b4e0aa">

Some options users may want:

* exact match -  it would sort with the exact match of the file name to what is being searched first, in my screenshot I would expect `mix.exs` and `mix.lock` to sort higher than everything else
* bag distance (Jaccard index) - sort by distance between overlapping sets. This may be the more natural options for some.
* default: the current sorting method

**Comment by JonGretar** [comment]
Yeah it makes sense that history plays a role. Just not at the expense of an exact match. Even if you would write the full `mix.exs` filename there it would not be enough to push that file to the top. Which feels strange.

**Comment by JosephTLyons** [comment]
Linking this for the team:

- https://github.com/zed-industries/zed/issues/7586
