### ISSUE TITLE
ctrl+c, ctrl+v on a line does paste under line

### ISSUE THREAD

**Issue by CrazieNewb** [zed-industries/zed#11971]
### Check for existing issues

- [X] Completed

### Describe the feature

When cursor is on a line, on vscode pressing CTRL+C then CTRL+V pastes under that line.

### If applicable, add mockups / screenshots to help present your vision of the feature

Pressing CTRL+C then CTRL+V
![image](https://github.com/zed-industries/zed/assets/86976922/f4fe3125-2bbe-4e71-b287-a35d554bd3ba)
Result:
![image](https://github.com/zed-industries/zed/assets/86976922/48f55ff7-ca55-47bb-abf7-c626ad19ffde)
Expected result:
![image](https://github.com/zed-industries/zed/assets/86976922/0dacb541-4763-4463-9858-249609fb45d7)

**Comment by JosephTLyons** [comment]
Hey @CrazieNewb - which platform are you on? Windows?

**Comment by a-usr** [comment]
It seems the relevant piece of code is in this method
https://github.com/zed-industries/zed/blob/a5b14de4012beebec512a6fc8c30d3638eed7d1b/crates/editor/src/editor.rs#L6050-L6086

**Comment by CrazieNewb** [comment]
> Hey @CrazieNewb - which platform are you on? Windows?

I am on linux.

To clarify, the expected behaviour is to copy a newline \r\n before the copied line.

**Comment by a-usr** [comment]
> To clarify, the expected behaviour is to copy a newline \r\n before the copied line.

Isnt \r\n windows-specific? as far as i remember \n was always enough in unix world
