### ISSUE TITLE
[Assistant] add `custom_model` parameter

### ISSUE THREAD

**Issue by GOWxx** [zed-industries/zed#11984]
### Check for existing issues

- [X] Completed

### Describe the feature

The current assistant does not support the configuration of custom models, and there is a hope to add custom models with configurations such as:

```json
  "assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "type": "openai",
      "default_model": "gpt-3.5-turbo",
      "custom_model": ["custom_model_1", "custom_model_2"],
      "api_url": "https://www.example.com"
    }
  }
```

**Comment by GOWxx** [comment]
link #11075

**Comment by christ-offer** [comment]
I'd love to be able to use something like openrouter
