### ISSUE TITLE
Show color swatches for TailwindCSS colors

### ISSUE THREAD

**Issue by jasongitmail** [zed-industries/zed#11991]
### Check for existing issues

- [X] Completed

### Describe the feature

It'd also be useful to see color swatches for the tailwind color classes, like in Cursor/VSCode:

### Zed
<img width="398" alt="zed" src="https://github.com/zed-industries/zed/assets/50032291/4659d3fa-4ad1-4ae1-a695-99d54b64c399">

### Cursor
<img width="249" alt="vscode" src="https://github.com/zed-industries/zed/assets/50032291/64b25582-883d-4c26-bd73-debc658119cc">

Leftover aspect from https://github.com/zed-industries/zed/issues/10532

**Comment by thecrypticace** [comment]
I've wanted this feature for a while and decided to try my hand at implementing it. So far I've got a super basic version working:

<img width="286" alt="Screenshot 2024-07-10 at 21 46 12" src="https://github.com/zed-industries/zed/assets/614993/848996a6-2f98-4f02-bef9-ade5e08a8f8c">

There's still a good bit to do before I feel good about opening a PR (better perf, handling more color formats like VSCode does, more tests, etc…) but this is at least progress.

**Comment by thecrypticace** [comment]
Life and work stuff got in the way but I had some time this evening to update things a bit and open a PR: #18665

**Comment by nodgear** [comment]
what about inline swatches?

**Comment by gianpaj** [comment]
Could also support TailwindCSS 3 and 4 classes with RGB or HSL values?

<img width="557" alt="Image" src="https://github.com/user-attachments/assets/779d8a56-df97-462d-8e64-b40cedc1d130" />

<img width="357" alt="Image" src="https://github.com/user-attachments/assets/b3a5830d-7c48-4b8e-ae90-86c443a3f8c8" />
