### ISSUE TITLE
Update Gleam extension tree-sitter version.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [zed-industries/zed#11996]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Gleam 1.1.0 introduced a new `@internal` attribute. It seems Zed gets sad when I use it and syntax highlighting breaks :(

### Environment

Zed: v0.137.0 (Zed Nightly 97691c1def690949768ef5c6d2383d4e773ea611)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1680" alt="image" src="https://github.com/zed-industries/zed/assets/9001354/424c8b19-5a9c-4548-aff2-85224a5ea516">

**Comment by JosephTLyons** [comment]
It was just merged into main!

**Comment by maxdeviant** [comment]
This is available in v0.1.3 of the Gleam extension.
