### ISSUE TITLE
Detect Intelephense LSP from $PATH

### ISSUE THREAD

**Issue by patka-123** [zed-industries/zed#11994]
### Check for existing issues

- [X] Completed

### Describe the feature

When intelephense (a PHP LSP) is installed and available from $PATH it would be nice when it automatically gets picked up, just like it works for rust-analyzer. Currently the functionality to check if it is available from $PATH is not implemented yet.

(I'm using nixos so the automatic download and installation doesn't work, yet)

CC @maxdeviant because we spoke about it on Discord.

**Comment by xtrasmal** [comment]
I've installed my php extension for phpactor lsp(https://github.com/xtrasmal/zed-lsp-phpactor) as a dev extension together with the current php extension and got excellent php support(thanks to phpactor) for a short while. But I think I messed up my zed config and can't reproduce. 
It would be great if Intelephense could be put on the backseat and let phpactor take the steering wheel. 
See images.
![phpactor-code-actions](https://github.com/user-attachments/assets/b7f0e563-4788-4ff7-a141-9abd02688504)
![phpactor-code-actions-2](https://github.com/user-attachments/assets/82b4dd39-7054-4c36-9f6e-b71a48153cc1)
![phpactor-new](https://github.com/user-attachments/assets/1d0a5624-e467-4b0b-bf16-aa841196026a)
I'm going to try again this weekend. I'm a little lost when it comes to lsp's and especially Rust, so any points would be great, cause Intelephense is subpar.

**Comment by xtrasmal** [comment]
@patka-123 
Try my extension. PHP is finally working glorious in Zed 👯‍♂️ 
https://github.com/xtrasmal/zed-lsp-phpactor

**Comment by xtrasmal** [comment]
@patka-123 phpactor is part of the zed extensions now. You can forget about Intelephense now and use a much richer lsp

**Comment by maxdeviant** [comment]
@patka-123 I had followed up to your original inquiry on Discord, but it seems you deleted your account, so I’m guessing you didn’t see my question.

How did you go about installing `intelephense`?

I was just looking into this and noticed that there doesn't seem to be a Nix package for `intelephense`.

I could only find the Node package and the VS Code extension.

<img width="920" alt="image" src="https://github.com/user-attachments/assets/c3d42061-e596-437e-bac7-0d22da717886">

Although I know that Intelephense is proprietary software, so things are a bit opaque, but as far as I can tell it's just running as a Node package.

**Comment by maxdeviant** [comment]
@patka-123 This is available in v0.1.1 of the PHP extension.
