### ISSUE TITLE
Scorll lsp Document pages using ctrl-f and ctrl-b in vim mode

### ISSUE THREAD

**Issue by wishque** [zed-industries/zed#12009]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/zed-industries/zed/assets/62787567/a55a373c-a70e-4c62-b3ad-80b2bd316ff3

**Comment by JosephTLyons** [comment]
Hey @wishque - were you able to figure out a way to configure this?

**Comment by wishque** [comment]
Can we set scroll position to popups? so that pagedown will work as mouse scroll
