### ISSUE TITLE
vue-language-server does not working when using workspaces

### ISSUE THREAD

**Issue by joshuaia** [zed-industries/zed#12019]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After moving vue support from Zed to extension, in workspace dependent repositories `vue-language-server` stopped working.

To reproduce:
1. Clone https://github.com/hoppscotch/hoppscotch
2. Install all packages from root of the project using `pnpm i` (you may see some errors after the installation ends, you can skip them, they does not effect on this reproduction)
3. Navigate to any vue file (for example inside `pages` in `hoppscotch-sh-admin` package)
4. Zed will notify you in status bar about downloading `vue-language-server`
5. After downloading will finish try to hover on some code inside ts script block, it won't work. BTW I can't see any logs and related errors, it feels like vue server is not installed at all.

It happens only for `vue-language-server`, ts server works well, you can try to open any ts file in this repo and you will see it in action.

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by mtorromeo** [comment]
I have a similar issue with this error in console:

```
[2024-06-10T10:25:16+02:00 ERROR project] failed to start language server "vue-language-server": Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in node_modules/typescript/lib
[2024-06-10T10:25:16+02:00 ERROR project] server stderr: Some("")
[2024-06-10T10:25:16+02:00 ERROR project] Hit 4 reinstallation attempts for "vue-language-server"
[2024-06-10T10:25:16+02:00 ERROR util] crates/lsp/src/lsp.rs:782: oneshot canceled
```

In my case I am not using a workspace but Zed is opened on a monorepo with 2 distinct vue apps in subfolders (eg. `app1/package.json`, `app2/package.json`) but the plugin is only looking for `node_modules/typescript/lib` in the root folder.

If I open only one of the 2 apps directly in Zed everything works correctly

**Comment by bitfactory-oussama-fadlaoui** [comment]
+1 whenever opening a project with the frontend inside of the project folder that's opened (e.g. in a headless application with `/frontend` and `/backend`)

**Comment by maxdeviant** [comment]
@joshuaia I was able to reproduce the issue in v0.0.3 of the Vue extension.

Once I upgraded to v0.1.0 of the extension (which was released earlier today), things seem to be working as expected.

Could you give it a try with v0.1.0 and see if that fixes your issue?

**Comment by joshuaia** [comment]
@maxdeviant thanks a lot!
It works perfectly. I really appreciate your help!

**Comment by Moshyfawn** [comment]
Based on the previous user's feedback, I'll be closing this issue. Please feel free to open a new ticket if you encounter any other problems.

**Comment by AlexDaniel** [comment]
So for anyone who has it working, how is it today? I'm seeing issues with vue-language-server working intermittently in a multi-frontend pnpm workspace. It almost feels like it's trying to process files of the wrong project, or something like that. @joshuaia is it still working for you without issues?

**Comment by AlexDaniel** [comment]
I debugged it more, and it seems that if you have two frontend projects open at the same time, only one of them will get checked, and the other will have no diagnostics. You can get diagnostics for the other project if you close all other buffers and restart LSP. 🫠
