### ISSUE TITLE
suggestion: update `tree-sitter`

### ISSUE THREAD

**Issue by ognevny** [zed-industries/zed#12016]
### Check for existing issues

- [X] Completed

### Describe the feature

there was lots of changes from v0.20 to v0.22. I'm not sure, but I suppose that it would fix #11040

### If applicable, add mockups / screenshots to help present your vision of the feature

there are lots of `tree-sitter` crates, so I didn't find a way to update them all :D

**Comment by maxdeviant** [comment]
We're intentionally on a branch of v0.20 of Tree-sitter that contains some backported functionality from later releases.

We have been holding off on upgrading because it involves a lot of churn with the Tree-sitter grammars we depend on for native language support.

**Comment by ognevny** [comment]
> We're intentionally on a branch of v0.20 of Tree-sitter that contains some backported functionality from later releases.
> 
> We have been holding off on upgrading because it involves a lot of churn with the Tree-sitter grammars we depend on for native language support.

how long will you stay at v0.20?
