### ISSUE TITLE
Sort JSON document

### ISSUE THREAD

**Issue by arv-anshul** [zed-industries/zed#12026]
### Check for existing issues

- [X] Completed

### Describe the feature

Sort whole JSON document according to keys.

This is feature is available in VSCode through `vscode.json-language-features` builtin extension. I uses command pallet's "JSON: Sort Document" (`json.sort`) setting.

> If possible add support for `YAML` documents as well.

### If applicable, add mockups / screenshots to help present your vision of the feature

Copied from: [VS Code: Sort Lines and JSON object properties | bobbyhadz](https://bobbyhadz.com/blog/sort-lines-vscode#sort-json-object-properties-in-vs-code)

![sort-json-object.gif (670×337)](https://bobbyhadz.com/images/blog/sort-lines-vscode/sort-json-object.gif)

**Comment by fatihaziz** [comment]
(+1) i very need it, or atleast there is a way to auto format any json file using biome for example

**Comment by kurtbuilds** [comment]
the code action exists, but apparently it doesn't work right now.

https://github.com/zed-industries/zed/issues/16746
