### ISSUE TITLE
After the upgrade, zed stopped respecting the configurations.

### ISSUE THREAD

**Issue by skhaz** [zed-industries/zed#12034]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My configuration has always worked; the Copilot icon never appeared. After updating today, it reappeared.

Therefore, I consider this a bug.

<img width="539" alt="Screenshot 2024-05-19 at 10 39 38" src="https://github.com/zed-industries/zed/assets/46259/4ffc1985-4603-4765-80b0-9983f7c15f09">
<img width="97" alt="Screenshot 2024-05-19 at 10 39 29" src="https://github.com/zed-industries/zed/assets/46259/cf9d85fd-47bb-4be7-9cba-dc9cd2704d43">

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Copilot support was reworked due to SuperMaven addition and the corresponding settings were renamed.
See https://github.com/zed-industries/zed/issues/11735 also.

Unfortunately, there have not been a "breaking changes" on this one, sorry, but you can disable the entire copilot feature with 

```
{
  "features": {
    "inline_completion_provider": "none"
  }
}
```

now.

**Comment by skhaz** [comment]
Thank you.
