### ISSUE TITLE
error when running program on windows 11

### ISSUE THREAD

**Issue by tranvlnh26** [zed-industries/zed#12032]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

[2024-05-19T18:19:57+07:00 ERROR util] crates\settings\src\settings_file.rs:76: expected `,` or `}` at line 24 column 3
[2024-05-19T18:19:58+07:00 ERROR auto_update] auto-update failed: error:auto-update not supported for OS "windows"
[2024-05-19T18:20:10+07:00 ERROR project] failed to start language server "omnisharp": failed to download file: program not found
[2024-05-19T18:20:10+07:00 ERROR project] server stderr: Some("")
[2024-05-19T18:20:11+07:00 ERROR util] crates\language\src\language_registry.rs:877: server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
[2024-05-19T18:20:22+07:00 ERROR project] failed to start language server "omnisharp": failed to download file: program not found
[2024-05-19T18:20:22+07:00 ERROR project] server stderr: Some("")
[2024-05-19T18:20:23+07:00 ERROR util] crates\language\src\language_registry.rs:877: server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
[2024-05-19T18:20:26+07:00 ERROR project::prettier_support] Failed to install default prettier: prettier & plugins install: fetching latest npm versions: fetching latest npm version for package prettier: failed to execute npm info subcommand:
stdout: "{\n  \"error\": {\n    \"code\": \"ERR_SOCKET_TIMEOUT\",\n    \"summary\": \"request to https://registry.npmjs.org/prettier failed, reason: Socket timeout\",\n    \"detail\": \"This is a problem related to network connectivity.\\nIn most cases you are behind a proxy or have bad network settings.\\n\\nIf you are behind a proxy, please make sure that the\\n'proxy' config is set properly.  See: 'npm help config'\"\n  }\n}\n"
stderr: "npm ERR! code ERR_SOCKET_TIMEOUT\nnpm ERR! errno ERR_SOCKET_TIMEOUT\nnpm ERR! network request to https://registry.npmjs.org/prettier failed, reason: Socket timeout\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network 'proxy' config is set properly.  See: 'npm help config'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\admin\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\cache\\_logs\\2024-05-19T11_20_03_761Z-debug-0.log\n"
[2024-05-19T18:20:32+07:00 ERROR project] failed to start language server "omnisharp": failed to download file: program not found
[2024-05-19T18:20:32+07:00 ERROR project] server stderr: Some("")
[2024-05-19T18:20:33+07:00 ERROR util] crates\language\src\language_registry.rs:877: server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
[2024-05-19T18:20:37+07:00 ERROR project] failed to start language server "omnisharp": failed to download file: program not found
[2024-05-19T18:20:37+07:00 ERROR project] server stderr: Some("")
[2024-05-19T18:20:38+07:00 ERROR util] crates\language\src\language_registry.rs:877: server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
[2024-05-19T18:20:48+07:00 ERROR project] failed to start language server "omnisharp": failed to download file: program not found
[2024-05-19T18:20:48+07:00 ERROR project] server stderr: Some("")
[2024-05-19T18:20:48+07:00 ERROR project] Hit 4 reinstallation attempts for "omnisharp"
[2024-05-19T18:20:53+07:00 ERROR project::prettier_support] Failed to install default prettier: prettier & plugins install: fetching latest npm versions: fetching latest npm version for package prettier: failed to execute npm info subcommand:
stdout: "{\n  \"error\": {\n    \"code\": \"ERR_SOCKET_TIMEOUT\",\n    \"summary\": \"request to https://registry.npmjs.org/prettier failed, reason: Socket timeout\",\n    \"detail\": \"This is a problem related to network connectivity.\\nIn most cases you are behind a proxy or have bad network settings.\\n\\nIf you are behind a proxy, please make sure that the\\n'proxy' config is set properly.  See: 'npm help config'\"\n  }\n}\n"
stderr: "npm ERR! code ERR_SOCKET_TIMEOUT\nnpm ERR! errno ERR_SOCKET_TIMEOUT\nnpm ERR! network request to https://registry.npmjs.org/prettier failed, reason: Socket timeout\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network 'proxy' config is set properly.  See: 'npm help config'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\admin\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\cache\\_logs\\2024-05-19T11_20_30_469Z-debug-0.log\n"
[2024-05-19T18:21:19+07:00 ERROR project::prettier_support] Failed to install default prettier: prettier & plugins install: fetching latest npm versions: fetching latest npm version for package prettier: failed to execute npm info subcommand:
stdout: "{\n  \"error\": {\n    \"code\": \"ERR_SOCKET_TIMEOUT\",\n    \"summary\": \"request to https://registry.npmjs.org/prettier failed, reason: Socket timeout\",\n    \"detail\": \"This is a problem related to network connectivity.\\nIn most cases you are behind a proxy or have bad network settings.\\n\\nIf you are behind a proxy, please make sure that the\\n'proxy' config is set properly.  See: 'npm help config'\"\n  }\n}\n"
stderr: "npm ERR! code ERR_SOCKET_TIMEOUT\nnpm ERR! errno ERR_SOCKET_TIMEOUT\nnpm ERR! network request to https://registry.npmjs.org/prettier failed, reason: Socket timeout\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network 'proxy' config is set properly.  See: 'npm help config'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\admin\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\cache\\_logs\\2024-05-19T11_20_57_629Z-debug-0.log\n"

### Environment

Device name	tranvlnh
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	E4885D00-A957-4C92-B4DE-B68E1EDCC327
Product ID	00328-90000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

0 verbose cli C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\node.exe C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\admin\Documents\GitHub\zed\.npmrc Completed in 0ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\blank_user_npmrc Completed in 3ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\blank_global_npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 19ms
17 timing npm:load:configload Completed in 19ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm info prettier
21 verbose argv "info" "--cache" "C:\\Users\\admin\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\cache" "--userconfig" "C:\\Users\\admin\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\blank_user_npmrc" "--globalconfig" "C:\\Users\\admin\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\blank_global_npmrc" "prettier" "--json" "--fetch-retry-mintimeout" "2000" "--fetch-retry-maxtimeout" "5000" "--fetch-timeout" "5000"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\cache\_logs\2024-05-19T11_20_03_761Z-
26 verbose logfile C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\cache\_logs\2024-05-19T11_20_03_761Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 38ms
31 silly logfile start cleaning logs, removing 3 files
32 silly logfile done cleaning log files
33 timing command:info Completed in 22183ms
34 verbose type system
35 verbose stack FetchError: request to https://registry.npmjs.org/prettier failed, reason: Socket timeout
35 verbose stack     at ClientRequest.<anonymous> (C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
35 verbose stack     at ClientRequest.emit (node:events:513:28)
35 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
35 verbose stack     at TLSSocket.emit (node:events:525:35)
35 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
35 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
35 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:82:21)
35 verbose stack     at runNextTicks (node:internal/process/task_queues:64:3)
35 verbose stack     at listOnTimeout (node:internal/timers:538:9)
35 verbose stack     at process.processTimers (node:internal/timers:512:7)
36 verbose cwd C:\Users\admin\Documents\GitHub\zed
37 verbose Windows_NT 10.0.22631
38 verbose node v18.15.0
39 verbose npm  v9.5.0
40 error code ERR_SOCKET_TIMEOUT
41 error errno ERR_SOCKET_TIMEOUT
42 error network request to https://registry.npmjs.org/prettier failed, reason: Socket timeout
43 error network This is a problem related to network connectivity.
43 error network In most cases you are behind a proxy or have bad network settings.
43 error network
43 error network If you are behind a proxy, please make sure that the
43 error network 'proxy' config is set properly.  See: 'npm help config'
44 verbose exit 1
45 timing npm Completed in 22258ms
46 verbose code 1
47 error A complete log of this run can be found in:
47 error     C:\Users\admin\AppData\Local\Zed\node\node-v18.15.0-win-x64\cache\_logs\2024-05-19T11_20_03_761Z-debug-0.log

**Comment by CharlesChen0823** [comment]
can you request ` https://registry.npmjs.org/prettier` on chrome or cmd?

**Comment by tranvlnh26** [comment]
![image](https://github.com/zed-industries/zed/assets/92441399/c2d59e47-82ee-4188-b3bd-420e53f2a704)
Yes, I can still request

> can you request on chrome or cmd?` https://registry.npmjs.org/prettier`

**Comment by tranvlnh26** [comment]
> please share your `settings.json`.

I just clone it and haven't changed any settings

**Comment by notpeter** [comment]
I believe this is out of date and no longer applies. 
@tranvlnh26 if you are still experiencing this, please comment and I'll reopen.
