### ISSUE TITLE
Zed Shuts After Opening Voice Call/Collab

### ISSUE THREAD

**Issue by FFUV** [zed-industries/zed#12077]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Description:
I am experiencing an issue with Zed IDE on macOS where the application quits unexpectedly when I try to access the Collab/Voicecall feature. This happens immediately after I click on the Collab/Voicecall option. I have searched extensively for a solution but haven't found any relevant information, so I'm seeking help here.

Steps to Reproduce:

Open Zed IDE on macOS.
Navigate to the Collab/Voicecall section.
Click on the Collab/Voicecall option.
Expected Behavior:
The Collab/Voicecall feature should open and function properly without causing the application to quit.

Actual Behavior:
Zed IDE quits immediately after clicking on the Collab/Voicecall option.

System Information:

OS: macOS 11.7.7
Zed IDE Version: Latest

Additional Information:

I have tried restarting the application and my system, but the issue persists.
There are no error messages displayed before the application quits.
Any relevant logs or crash reports can be provided if needed.

I would appreciate any assistance in resolving this issue. Thank you!

### Environment

Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	1.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	4 GB
  System Firmware Version:	478.0.0.0.0
  SMC Version (system):	2.13f15
  Serial Number (system):	C02L84M6F5V7
  Hardware UUID:	AA957321-CBF0-5F4C-AE64-D08E549002A0
  Provisioning UDID:	AA957321-CBF0-5F4C-AE64-D08E549002A0

**Comment by FFUV** [comment]
> Did you build zed from source? Or start it from the terminal? The zed logs would also be helpful in this case

I just downloaded it off the site

**Comment by a-usr** [comment]
> I just downloaded it off the site

What about the logs?

**Comment by FFUV** [comment]
> > I just downloaded it off the site
> 
> What about the logs?

sorry deleted logs

**Comment by FFUV** [comment]
@defunkt  @JosephTLyons @a-usr @palmamartin  sorry just need this to get attention because still havent got it to work.

**Comment by a-usr** [comment]
> @defunkt @JosephTLyons @a-usr @palmamartin sorry just need this to get attention because still havent got it to work.

Im sorry, i didnt notice you answered. <ins>I still need the logs though.</ins> Also AFAIK the voice call feature is incomplete on all platforms. The major difference it seems is that on macos you are unmuted by default, unlike on windows and linux. Thats why on those two platforms you can still do stuff like share your project and chat during a "call", but not talk because when unmuting zed crashes. However I thought that was because windows wasn't supported yet...

**Comment by mikayla-maki** [comment]
@FFUV Do not ping random users who have contributed to Zed. As a-usr says, to diagnose your problem we would need a crash report from your mac and/or see the Zed log file after the crash is triggered. 

@a-usr Zed should be fully functional on macOS. Linux is still in development.

**Comment by FFUV** [comment]
> Contributor

Really sorry.

**Comment by FFUV** [comment]
Ill try getting the logs but I find you a tad bit rude.

**Comment by a-usr** [comment]
> Ill try getting the logs but I find you a tad bit rude @mikayla-maki also tell Nicole, Chris, Brayden, and Avery I said hi

\> open issue
"I can provide logs"
\> delete logs
\> ping random contributors
\> get a more or less polite warning by an actual employee at zed industries
"youre rude"
\> mention a couple of names of what i presume are other employees at zed industries

I have no sympathy for you, and I doubt that the zed team will give this issue any more attention than what was already given. Be Better.

**Comment by onlykash1** [comment]
boom
