### ISSUE TITLE
Tailwind CSS support in ~H snippets in Elixir files broken

### ISSUE THREAD

**Issue by nesadkadric** [zed-industries/zed#12105]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It looks like this was fixed before: https://github.com/zed-industries/zed/issues/6306
but now it is broken again.

TailwindCSS autocomplete does not show up in .heex components or ~H sigil snippets in Elixir files.

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/31567213/d0c7f8a4-1ecc-494b-be66-fc1867ea550b

**Comment by nesadkadric** [comment]
I made it to work with this line: "language_servers": ["tailwindcss-language-server"],

```
  "language_overrides": {
    "Elixir": {
      "language_servers": ["tailwindcss-language-server"],
      "format_on_save": {
        "external": {
          "command": "mix",
          "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
        }
      }
    }
  },
```

**Comment by nesadkadric** [comment]
It is broken again, and I have not changed anything except updating Zed to the preview version and updating Elixir.

Elixir 1.17.1 (compiled with Erlang/OTP 26)

Zed: v0.141.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by nesadkadric** [comment]
It is working again. I have not changed anything, but I saw some information about the Tailwind language server downloading.

Zed: v0.143.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by moiseshilario** [comment]
Made it work again with:

```json
 "languages": {
  "Elixir": {
        "language_servers": ["elixir-ls", "tailwindcss-language-server"]
      }
  }
```
🎉🎉🎉

**Comment by mrluc** [comment]
> Made it work again with:
>  "languages": { "Elixir": { "language_servers": ["elixir-ls", "tailwindcss-language-server"] } }...

@moiseshilario I found this because I'm trying to get the same experience with the new official community LSP, `expert`. However swapping "elixir-ls" for "expert" and restarting all the LSP's doesn't seem to work for me.
