### ISSUE TITLE
Numpad Enter is completely ignored

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#12117]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Numpad enter is currently completely ignored - I would expect it to at least behave like normal enter by default so I can i.e. choose an option in a modal dialog with it, even if it can't be bound separately. Closely related to #11948, but for this issue simply treating numpad enter identically to enter would satisfy the expected behaviour.

For context: I sometimes use a keyboard that has the numpad and arrow/home/end/etc keys merged into a single numpad-sized block of keys (cm quick fire tk), switching between the two "layers" with num lock. As a result, numpad enter is right next to the arrows and I end up frequently reaching for that instead of the main enter which is further away.

### Environment

Zed: v1.0.0 (Zed Dev 7c9c80d66345940c80e59046d5273c3af59f38a9)
OS: Linux 1.0.0
Memory: 30.9 GiB
Architecture: x86_64

**Comment by bend-n** [comment]
Im finding numpad home end pgup pgend are also completely ignored.
