### ISSUE TITLE
White splash screen when opening Zed

### ISSUE THREAD

**Issue by ZeroHawkeye** [zed-industries/zed#12112]
### Check for existing issues

- [X] Completed

### Describe the feature

![recording](https://github.com/zed-industries/zed/assets/161401688/1ca1858b-d015-4ac6-ba15-d9e83b3f8f42)
I tested win10 sdk and win11 sdk and executed cargo clean, but neither of them fixed this problem. In addition, under windows, a discrete graphics card must be used for normal use. If windows decides to use an integrated graphics card, the process will exit after a few minutes.

**Comment by CharlesChen0823** [comment]
I guess it relate blade using gpui, when gui driver hang or other compatible problem, Zed will crashed.  like `Thread "main" panicked with "GPU hung" at crates\gpui\src\platform\blade\blade_renderer.rs:412:17`

**Comment by CharlesChen0823** [comment]
And I guess, you can try update graphic driver?

**Comment by ZeroHawkeye** [comment]
> And I guess, you can try update graphic driver?

At present, I can run it normally with a discrete graphics card, but I can't let Windows decide (if it is not set by default). But my main problem is that when I open it, a white screen will appear for about 500ms. This problem is quite uncomfortable.

**Comment by notpeter** [comment]
Closing as outdated.
