### ISSUE TITLE
Syntax recognition .gitattributes

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12123]
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode:
<img width="581" alt="Screenshot 2024-05-22 alle 15 14 51" src="https://github.com/zed-industries/zed/assets/20476002/51243ec7-a397-4fc2-a1e5-bf3ec8ab62a1">

Zed:
<img width="582" alt="Screenshot 2024-05-22 alle 15 16 24" src="https://github.com/zed-industries/zed/assets/20476002/ca214dc7-d2a7-4c5f-8c72-9d2b117e288d">

**Comment by maxdeviant** [comment]
This is provided by the `git-firefly` extension.

**Comment by maxdeviant** [comment]
> @maxdeviant : I'm not sure if the variable is recognized correctly it's white so I'm not sure, I'm talking about the part of the `linguist-language` writing, personally I prefer colors in case it uses vscode.

There may be some improvements that could be made.

But since this is handled by an extension the issue that would be an issue that could be opened with the extension: https://github.com/d1y/git_firefly
