### ISSUE TITLE
Support for .html.erb syntax highlighting

### ISSUE THREAD

**Issue by TimSullivan** [zed-industries/zed#12135]
### Check for existing issues

- [X] Completed

### Describe the feature

In Rails, many files have multiple file types associated with them, most commonly HTML and ERB. When editing a file called something.html.erb, it's generally *mostly* an HTML file, and includes some ruby within it. Right now, when editing in Zed, it detects the file type as ERB and only highlights the ERB tags, leaving the HTML uncoloured and difficult to work with.

**Comment by vitallium** [comment]
@TimSullivan can you please try the Zed Preview version. AFAIK, that issue was resolved recently and `html.erb` files should have proper highlighting.

**Comment by TimSullivan** [comment]
Sure enough, the problem is solved in 0.137.0. What service! 😄
