### ISSUE TITLE
Strange behavior of the tab when a new file is opened at the beginning

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12139]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Open zed
2) Open any file
3) Do what you see in the video

https://github.com/zed-industries/zed/assets/20476002/0faa2cf5-104c-4846-841d-2089a091fcac

### Environment

```
Zed: v0.136.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by JosephTLyons** [comment]
Yeah, it looks like Zed is considering the two separate preview opens of the same file as different events in the history, and so navigating them simply does nothing.

**Comment by notpeter** [comment]
I'd be happy to review a PR which fixes this, but given that it has no measurable impact on user experience, nor does it impede usage, I'm going to close as won't fix.
