### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by Artur-Galstyan** [zed-industries/zed#12130]
### Check for existing issues

- [X] Completed

### Describe the feature

Is there a way to have nightly builds of Zed? For example, I had an issue recently with the search and it got fixed, but now I have to wait until a new preview release is released. It'd be good to have a nightly build based on the main branch.

(I'm aware that I could build this from source but the likelihood of me messing that up is just too high 😭).

**Comment by colorsakura** [comment]
https://github.com/zed-industries/zed/blob/main/script/install.sh

**Comment by JosephTLyons** [comment]
It isn't possible at the moment, but we haven't really decided on whether or not we'd open this up - it is a decision we still need to make!

**Comment by notpeter** [comment]
We currently are building Nightly for internal use only. Thanks
