### ISSUE TITLE
Symbolic link

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12142]
### Check for existing issues

- [X] Completed

### Describe the feature

It seems that the reference to a Symbolic link is not considered by zed.

Link: https://github.com/zed-industries/zed/tree/main/extensions/astro

See icon next to `LICENSE-APACHE`.

Vscode:
<img width="341" alt="Screenshot 2024-05-22 alle 20 28 30" src="https://github.com/zed-industries/zed/assets/20476002/f60ec3db-a9b0-488c-821f-2af21fb8fb1d">

Zed:
<img width="363" alt="Screenshot 2024-05-22 alle 20 28 02" src="https://github.com/zed-industries/zed/assets/20476002/c1538e7a-314f-4c3d-97f3-062d4dd071e2">

Github:
<img width="875" alt="Screenshot 2024-05-22 alle 20 26 55" src="https://github.com/zed-industries/zed/assets/20476002/76db7a51-9e1d-494f-a7a0-55cb3e47cc71">

**Comment by CFKeef** [comment]
Hi, I ended up implementing following the outline you posted @SomeoneToIgnore 

The implementation basically the same aside from having to extend the Entry struct to carry it's canonical path and that'll provide it to the details struct that the UI uses.

Just need some guidance on what icon or where to source an icon from but for now its using arrow right.

**Comment by SomeoneToIgnore** [comment]
Nice.

> aside from having to extend the Entry struct to carry it's canonical path and that'll provide it to the details struct that the UI uses

Seems fine if we do not do extra path computations (as those two canonical path calculations are enough already).

I am not sure which icon to pick either, a general guide would be to explore https://github.com/zed-industries/zed/tree/main/assets/icons catalogue and repurpose one of the arrows from there.
We're interested in a relatively small (large enough to be hovered at though) and not disturbing.
Note that the icon loaded from the assets, can also be modified further: https://github.com/zed-industries/zed/blob/2fce5cb937ae3695d788c822b37bcfcf8a3835e9/crates/ui/src/components/icon.rs#L316
