### ISSUE TITLE
ruby extension not choosing ruby-lsp automatically

### ISSUE THREAD

**Issue by Vagab** [zed-industries/zed#12144]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

probably I broke something but here it goes. I've started using `ruby-lsp` with zed some time ago when the extension was released and it worked fine. Today I decided to install zed preview and now `ruby-lsp` works neither in zed nor in zed preview. Language server logs:
<img width="225" alt="image" src="https://github.com/zed-industries/zed/assets/33145320/877e0c08-32c0-4e4d-b0e5-a54c9a87f664">
zed logs right after uninstalling/installing ruby extension:
```
2024-05-22T20:36:19+02:00 [INFO] installing extension ruby latest version
2024-05-22T20:36:21+02:00 [INFO] rebuilt extension index in 388.679958ms
2024-05-22T20:36:21+02:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-05-22T20:36:21+02:00 [INFO] starting language servers for Ruby: solargraph
2024-05-22T20:36:21+02:00 [INFO] starting language servers for Ruby: solargraph
```
`settings.json`:
```json
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      }
    }
  },
```

it seems zed things my lsp is solargraph for some reason, but there's nothing mentioning solargraph anywhere I can think of

things I've tried:
- completely uninstalling `solargraph` from everywhere on my laptop I could think of
- installing `solargraph` back cause maybe it didn't find it and that was somehow the problem 🤷‍♂️ 
- installing `ruby-lsp` with `bundler`, `gem`, `bundle exec gem`, and `asdf exec gem` just to test different envs.

additional info:
- `where solargraph` returns nothing
- `where ruby-lsp` returns `~/.asdf/shims/ruby-lsp`, and runs fine from the terminal

### Environment

Zed: v0.137.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15407457/Zed.log)

**Comment by vitallium** [comment]
@Vagab `ruby-lsp` is disabled by default, since [its support is limited](https://github.com/zed-industries/zed/pull/8613). There is a special configuration option that you can use to tell Zed which LSP server to use. Open Zed settings and paste the following JSON under the `languages` key to prefer `ruby-lsp` over `solargraph`:


```json
"Ruby": {
  "language_servers": ["ruby-lsp", "!solargraph", "..."]
}
```

Note that there is an exclamation mark in `!solargraph`. It tells Zed not to use this LSP.

Default settings are:

```json
"Ruby": {
  "language_servers": ["solargraph", "!ruby-lsp", "..."]
}
```

Let me know if that helps. Thanks.

**Comment by Vagab** [comment]
I'll try when I get home, but thank you, that makes sense! Is there by any chance something in documentation about it? I could find anything

**Comment by Vagab** [comment]
@vitallium that did work, thank you! I'll close the issue. Regarding documentation though, should I maybe put up a pr that adds this to the documentation of lsp's or something like that?

**Comment by vitallium** [comment]
> @vitallium that did work, thank you! I'll close the issue. Regarding documentation though, should I maybe put up a pr that adds this to the documentation of lsp's or something like that?

For sure, I will add that to the documentation. Thanks again!

**Comment by vitallium** [comment]
@Vagab [here is the PR](https://github.com/zed-industries/zed/pull/12232) to update documentation on switching between Ruby language servers.
