### ISSUE TITLE
BUG: .zed>settings.json settings messing with regular settings (?) Hard to describe

### ISSUE THREAD

**Issue by Artur-Galstyan** [zed-industries/zed#12148]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Ok this is a strange bug I noticed. First, I have in my settings this autoformatter using ruff:

```json
"language_overrides": {
    "Python": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "bash",
          "arguments": [
            "-c",
            "ruff check --select=I --fix --stdin-filename {buffer_path} | ruff format --stdin-filename {buffer_path}"
          ]
        }
      }
    }
  }
```

Recently, I noticed that my auto formatting stopped working. Apparently, I changed GH copilot and it created a .zed>settings.json file. This file is the cause of my troubles.

See the following video for what I mean:

https://github.com/zed-industries/zed/assets/63471891/67f12c0b-dee2-45b3-9f99-46c6e16788c6

If I just have `{}` in my settings, the auto formatter doesn't work. But if I copy paste the above code into the .zed>settings.json file, the formatting starts working again. Changing it to `{}` again makes it stop working. All the while I have *the same settings* in my main settings.json file. 

### Environment

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: MK183D/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.101.3
      OS Loader Version: 10151.101.3
      Serial Number (system): HY3QV0M9RG
      Hardware UUID: B4814D84-2B74-5387-BA15-8B1A1D001B2B
      Provisioning UDID: 00006000-001849210223401E
      Activation Lock Status: Enabled

**Comment by Artur-Galstyan** [comment]
Unfortunately, this currently means that the settings in the "general" `settings.json` file don't get applied at all, which is very frustrating 😢

**Comment by Artur-Galstyan** [comment]
[Zed.log](https://github.com/user-attachments/files/15848494/Zed.log)

Here's the log file for this issue.

**Comment by Artur-Galstyan** [comment]
I've found the issue:

```
2024-06-15T18:03:47+02:00 [ERROR] crates/settings/src/settings_store.rs:619: duplicate field `show_inline_completions`
```

Apparently, I had the flag `show_inline_completions` duplicated (?). This is strange, because it was only once in my settings.json file. I had clicked on the GH symbol and selected "Hide suggestions" and it saved that setting somewhere. But because it didn't work for me, I added it in the settings.json as well, giving this error. Now, I don't really know how to edit anything in the `settings_store` or how to clear the cache for it :(

**Comment by SomeoneToIgnore** [comment]
Could there be a `show_copilot_suggestions` (now obsolete) field somewhere in your settings too?

There seem to be an alias for `show_inline_completions` in the code:

https://github.com/zed-industries/zed/blob/dc22c82e57aed26b4d0873d7be06c0a8a0a835ef/crates/language/src/language_settings.rs#L300-L301

**Comment by Artur-Galstyan** [comment]
Ah, yes there is! I've deleted it now.

**Comment by SomeoneToIgnore** [comment]
So, everything works now?

I agree totally that Zed should 

* show a pop-up error on any discrepancies
* fall back apply what's possible still, not just use a blank default config
* be more rigorous when changing the settings, keeping the backward compatibility in mind

The first bullet seems quite a low hanging fruit already, and there had been issues created for some of these.

**Comment by Artur-Galstyan** [comment]
@SomeoneToIgnore Yes, it works now :)

**Comment by SomeoneToIgnore** [comment]
Great, I am certain that there's a settings-related issue, so will close this one for now.
