### ISSUE TITLE
Some suggestions for icons for some types of extensions

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12141]
### Check for existing issues

- [X] Completed

### Describe the feature

| Vscode | Zed |
|--------|-----|
| <img width="117" alt="Screenshot 2024-05-22 alle 19 59 38" src="https://github.com/zed-industries/zed/assets/20476002/077eaf69-8259-44e0-a0c0-a87bb0030546"> |<img width="120" alt="Screenshot 2024-05-22 alle 19 59 46" src="https://github.com/zed-industries/zed/assets/20476002/7732f329-aac2-4054-98e6-3df48440b0fb">
|<img width="159" alt="Screenshot 2024-05-22 alle 20 17 37" src="https://github.com/zed-industries/zed/assets/20476002/2aebbaa2-f7fd-4511-b6ca-b59063eb3842">|<img width="157" alt="Screenshot 2024-05-22 alle 20 18 09" src="https://github.com/zed-industries/zed/assets/20476002/e8f5bb83-58c8-4feb-b701-d8300a75400a">|
|<img width="104" alt="Screenshot 2024-05-22 alle 20 20 24" src="https://github.com/zed-industries/zed/assets/20476002/fb796ae6-9ca8-4f68-a5e6-5d453b64273a">|<img width="116" alt="Screenshot 2024-05-22 alle 20 20 46" src="https://github.com/zed-industries/zed/assets/20476002/f884804b-9091-47f5-8444-09fa6145a8dc">|

**Comment by notpeter** [comment]
We are not currently accepting external icon design feedback. Thanks.
