### ISSUE TITLE
No information popover when autocomplete suggestions are showing

### ISSUE THREAD

**Issue by effdotsh** [zed-industries/zed#12152]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When hovering over a variable/method, a popover showing information about that variable/method normally appears. However, when there is an autocomplete popover, the information popover does not show up. 

https://github.com/zed-industries/zed/assets/50590465/b5f35ed7-5196-49a8-a153-4fec6f16f216

### Environment

Zed: v0.136.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
I think I reported this issue before, but we closed it after some investigation:

- https://github.com/zed-industries/zed/issues/5097

Seems like we should leave this open though

**Comment by effdotsh** [comment]
@JosephTLyons I believe these are different issues. This is just not displaying two popovers at once, not the content of the popovers. This also wasn't python specific, here's the issue in rust:

https://github.com/zed-industries/zed/assets/50590465/e2ca11b4-9b8d-4e9f-8eb2-9bb91322cfaf

It does seem like that issue was fixed somewhere though.
