### ISSUE TITLE
Windows minimizes when you select all and drag the cursor up

### ISSUE THREAD

**Issue by user0608** [zed-industries/zed#12158]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you select content from a file and drag the mouse up, if the cursor hovers over the toolbar, the application window is minimized.

### Environment

ZED: Zed  preview 0.137.0
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-35-generic
DE: GNOME 42.9 
CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
Memory: 12041MiB / 15782MiB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/37247825/b3ec0971-6aba-47c9-98b4-93437be19422

**Comment by notpeter** [comment]
I am not able to reproduce this and believe this has been fixed.
If this is incorrect, please leave a comment below and I'm happy to reopen.
