### ISSUE TITLE
Resuming previous insert mode (gi) can't continue from the end of the line

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#12162]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The newly added `gi` seems to work well except in the instance where the insert mode ended at the end of a line — in that case it starts one character earlier. In the video I had to push the cursor to the end of the line with the arrow key so it's looks a little awkward, but the bug remains consistent.

And I checked nvim's behavior, it manages to continue from the end of the line.

### Environment

Zed: v0.136.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/471278/2d5d6cf2-d3a8-4918-8c66-4e24b6b53f91

**Comment by ConradIrwin** [comment]
Fixed by #13028
