### ISSUE TITLE
Really need to improve the return results of LSP

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#12167]
### Check for existing issues

- [X] Completed

### Describe the feature

I often encounter situations where what I really need is coding, not coding
Maybe we need to sort it out /cc @mrnugget 
![immmp](https://github.com/zed-industries/zed/assets/45585937/436f9692-3d17-4054-af05-c3ec615775e0)

**Comment by d1y** [comment]
> Hey @d1y - do you notice the poor matching only in JavaScript/TypeScript, or do you notice it in all languages?

Not all languages, it seems that a specific LSP will return such sequential results (typescript language server)

<img width="764" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/15034521-71f9-4d8e-be3d-cfe0a1846d78">

**Comment by mrnugget** [comment]
> what I really need is coding, not coding

To be clear: the issue is that you want `codegen`, not `Codegen`, yes?

**Comment by d1y** [comment]
> To be clear: the issue is that you want codegen, not Codegen, yes?

Yep

**Comment by mrnugget** [comment]
Was the closing intentional?

**Comment by mrnugget** [comment]
Seems better with the new typescript language server, right? 
![screenshot-2024-07-18-16 59 56@2x](https://github.com/user-attachments/assets/13f833d8-91ac-427b-a5c4-c98cb8f9d4f4)
