### ISSUE TITLE
Vim mode: `f` search `/` triggering the second time will display search-bar

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#12165]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After the second attempt, we won't be able to search anymore :_(
/cc @ConradIrwin
![fix_vi_search](https://github.com/zed-industries/zed/assets/45585937/d842aaf2-2740-46c8-a937-304d99b50bfb)

### Environment

Zed: v0.137.0 (Zed Nightly 5ddd343b27b0cf1a32ffc62bee186d7522f658fc)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@d1y I think this is the same as vim? If you want to go to the second / you need to do either `f / f /` or `2 f /`. From the video it looks like you're typing `f / /` which will first jump to / and then open search.

**Comment by d1y** [comment]
This is no problem, it's my memory confusion (my own Neovim custom keybind)
