### ISSUE TITLE
vim: support `(`/`)` for sentence motion

### ISSUE THREAD

**Issue by montmejat** [zed-industries/zed#12161]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In vim, I'm used to using the parenthesis to move up and down text blocks. However I'm unable to do it in Zed. Note that I'm using a french keyboard and linux. Thanks!

### Environment

Linux

**Comment by ConradIrwin** [comment]
Thanks for reporting! If you'd like to pair with me on this: https://calendly.com/conradirwin/pairing?month=2024-06

**Comment by NathanLovato** [comment]
@ConradIrwin does the offer to do pair programming on this still hold? If so, are there any prerequisites? Besides going through the available dev documentation and reading the code a bit. I'd be interested in contributing in this area as vim commands seem like fairly self-contained pieces.

**Comment by ConradIrwin** [comment]
Absolutely! https://calendly.com/conradirwin/pairing without the month restriction :D .

**Comment by ConradIrwin** [comment]
No prerequesites other than having zed working. Are you on linux or Mac?

**Comment by NathanLovato** [comment]
Linux is my daily driver, but if needed, I have access to a little ARM-based macbook I use for regression/crash testing on another technology. I just rarely use it.

I booked a time slot next Friday, thanks! I don't want to waste too much of your time so if there's anything I can study or try beforehand, let me know. I'm a rust beginner, though aside from lifetimes and concurrency, the basics look relatively straightforward.

**Comment by ConradIrwin** [comment]
Sounds great! If you want to use your linux machine, we can use Discord for audio.

Currently vim mode has sentence objects, but when I tried to re-use them to make sentence motions work (a while ago now), it didn't "just work" like I was hoping, so I think we'll want to build our own. (you can see that implementation here: https://github.com/zed-industries/zed/blob/d3b14ac515b4f679887be787bd2aa242d554c254/crates/vim/src/object.rs#L575).

I hope we can still reuse some of that code, and we'll build up some test cases as we go.

The other reference is the actual definition of these objects, which (if you haven't yet read through it) is likely more complicated than you'd imagine once you sub in the paragraph definition too :D. https://vimhelp.org/motion.txt.html#sentence.

**Comment by NathanLovato** [comment]
Thanks much Conrad! Please excuse the slow reply, I finish work late lately. I've just briefly read the code, which makes sense.

Tomorrow before the call I'm setting some time aside to read a bit more, compile, check the tests... You'll be leading and breezing through I'm sure but I don't want to be wasting your time with the most basic questions (though my understanding of rust is the most basic) !

For the paragraph definition, in zed, do you include the `nroff` syntax (`.IP` etc.) ? 

I hope it's okay but I've sent you an email with my Discord handle, to connect there.
