### ISSUE TITLE
Ico files are not rendered

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12166]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I did a test with the file found on the zed project: `./crates/zed/resources/windows/app-icon.ico`

<img width="1440" alt="Screenshot 2024-05-23 alle 00 15 22" src="https://github.com/zed-industries/zed/assets/20476002/de424fbf-ad5f-4b9d-a814-fc1aac829b65">

### Environment

```
Zed: v0.136.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by bbb651** [comment]
Seems related to #11863, `image` supports both webp and ico but the features are disabled as apparent in [it's dependencies](https://github.com/zed-industries/zed/blob/770a70298196b0fe866c2b5decac6d4e21719a96/Cargo.lock#L5260-L5272) compared to the [default ones](https://lib.rs/crates/image) which include `default-formats` which includes both `webp` and `ico`, it changed somewhere between `0.23` and `0.25.1` so the easy fix would be enabling the features, or upgrading to `0.25` if it's possible I haven't looked into it

**Comment by notpeter** [comment]
I believe this has been fixed.  I can open webp and ico in zed now.

<img width="464" alt="Screenshot 2024-08-27 at 17 02 22" src="https://github.com/user-attachments/assets/7ab35eaa-b538-403a-b6cb-b03b140a3bbc">
If you are still running into trouble, please comment and I'm happy to reopen.

**Comment by bbb651** [comment]
#13397

**Comment by merlinz01** [comment]
Here's what I see when previewing an ico file in Zed on Linux:

![Image](https://github.com/user-attachments/assets/07ce3979-c4ec-4156-aeeb-591c006adb05)

[My icon file, rename to .ico](https://github.com/user-attachments/assets/8fbd635c-2ff0-4cf6-998d-9c3d941c531d)

Zed: v0.193.1 (Zed Preview) 
OS: Linux X11 linuxmint 22.1
Memory: 62.1 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.8-1ubuntu1~24.04.1
