### ISSUE TITLE
windows 11 crashing

### ISSUE THREAD

**Issue by suffz** [zed-industries/zed#12175]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

   Compiling zed v0.138.0 (C:\Users\Brand\Downloads\zed-main\zed-main\crates\zed)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 10.90s
     Running `target\debug\Zed.exe`
[2024-05-22T21:57:17-03:00 ERROR auto_update] auto-update failed: error:auto-update not supported for OS "windows"
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: NotSupportedError" at crates\gpui\src\platform\windows\window.rs:968:14
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: git_smart_subtransport_git
  10: git_smart_subtransport_git
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: DispatchMessageW
  16: DispatchMessageW
  17: CallNextHookEx
  18: KiUserCallbackDispatcher
  19: NtUserCreateWindowEx
  20: CreateWindowExW
  21: CreateWindowExW
  22: CreateWindowExW
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: CoreUICreateEx
  39: CoreUICallReceive
  40: CoreUICallReceive
  41: CoreUICallReceive
  42: CoreUICallReceive
  43: CoreUICallReceive
  44: CoreUICallReceive
  45: CoreUICallReceive
  46: CoreUICallReceive
  47: DispatchMessageW
  48: DispatchMessageW
  49: GetClassLongW
  50: KiUserCallbackDispatcher
  51: NtUserPeekMessage
  52: PeekMessageW
  53: PeekMessageW
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: git_smart_subtransport_git
  65: BaseThreadInitThunk
  66: RtlUserThreadStart

error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)

### Environment

unsure

### If applicable, add mockups / screenshots to help explain present your vision of the feature

null

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

null

**Comment by kiucho** [comment]
May I know how did you solve this problem?
