### ISSUE TITLE
Problem with console icon location

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12188]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I set the console to the right, the icon is positioned in this way as seen in the image.

```
  "terminal": {
    "dock": "right"
  }
```

<img width="146" alt="Screenshot 2024-05-23 alle 11 36 47" src="https://github.com/zed-industries/zed/assets/20476002/340741b1-b493-4f96-aace-52c9ce115486">

After closing zed and reopening it, icona is placed back where it was before, when icona was in the bottom position.

<img width="148" alt="Screenshot 2024-05-23 alle 11 36 14" src="https://github.com/zed-industries/zed/assets/20476002/41477b20-698b-416c-8a66-86a4b91447b9">

### Environment

```
Zed: v0.137.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
This is a trivial visual issue (icons are not resorted until restart) with minimal impact on user experience.

I'd be happy to review a PR with a fix, but in order to keep the issue tracker clean I'm closing this as "won't fix".
