### ISSUE TITLE
Shortcut to toggle terminal panel

### ISSUE THREAD

**Issue by egoist** [zed-industries/zed#12184]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently  In Zed Ctrl+` only switch the focus between the editor and terminal, but in VSCode this shortcut will also hide the terminal when the editor is focused, maybe Zed could align this behavior or at least add a new shortcut for this

**Comment by egoist** [comment]
well turns out Command+J is all you need

**Comment by pshergie** [comment]
cmd+j if your terminal is at the bottom
cmd+r if your terminal is at the right

**Comment by hiscaledev** [comment]
command + J does not work in vim mode

> well turns out Command+J is all you need
