### ISSUE TITLE
Font xml comments problem

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12190]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As you can see from the image and video there are problems with the font, it's not very easy to distinguish if there is one line or two.

<img width="101" alt="Screenshot 2024-05-23 alle 12 01 00" src="https://github.com/zed-industries/zed/assets/20476002/4101bb83-e83d-4b34-b18f-9342106280e1">

https://github.com/zed-industries/zed/assets/20476002/116b4aa0-bf3d-4a1d-b18e-1ad036473550

![image](https://github.com/zed-industries/zed/assets/20476002/5eeecedd-dd33-4fce-aeb3-273babe41759)

### Environment

```
Zed: v0.137.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by maxdeviant** [comment]
What you are seeing are font ligatures.

If you don't want to see them, they can be [disabled](https://zed.dev/docs/configuring-zed#buffer-font-features):

```json
"buffer_font_features": {
  "calt": false
},
```
