### ISSUE TITLE
vim mode broken when ibus IME is used as KDE virtual keyboard

### ISSUE THREAD

**Issue by jakobhellermann** [zed-industries/zed#12198]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. install ibus and select it in KDE systemsettings virtual keyboards

![image](https://github.com/zed-industries/zed/assets/22177966/0d4278f6-4aee-430e-93ed-f8f363f33faf)

2. enable vim mode in zed

3. vim keybinds (like `i` for insert mode) don't work anymore

This is because now every keystroke (including simple letters) is received as
```rust
[crates/gpui/src/platform/linux/wayland/client.rs:1033:9] &event = CommitString {
    text: Some(
        "y",
    ),
}
```
using `zwp_text_input_v3` instead of
`wl_keyboard::Event::Key`

### Environment

Zed: v1.0.0 (Zed Dev 49538e86d24189d1d3e2b592bd04e337165d2482)
OS: Linux 1.0.0
Memory: 30.7 GiB
Architecture: x86_64

**Comment by jansol** [comment]
Key repeat does work in Firefox even with IBus enabled so I suspect this is a zed bug

**Comment by jansol** [comment]
This may be related to what @mikayla-maki said back in #11712 about wiring key presses up to the usual key input handling in zed.

**Comment by jansol** [comment]
IBus definitely works on my Ubuntu setup (Wayland) in Firefox, so that is likely a problem with your configuration.
