### ISSUE TITLE
Indent guide tab support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#12209]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Sent in by a user over Twitter / X.

### Environment

Zed: v0.138.0 (Zed Nightly 951fbc57ba1e1c512bc62cd7981e2feab6fabcef)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![GOR3w4fXEAANfCh](https://github.com/zed-industries/zed/assets/19867440/6abb6acf-78eb-4cc4-93cb-8fe378899c58)

**Comment by JosephTLyons** [comment]
cc: @bennetbo

**Comment by iluuu1994** [comment]
Hey, it works now! Thanks @JosephTLyons and @bennetbo :slightly_smiling_face:
