### ISSUE TITLE
`tsx` language disappear after selecting it in windows

### ISSUE THREAD

**Issue by Xenos-the-stupid** [zed-industries/zed#12208]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the `tsx` choice in the languages menu disappear after selecting it forever, the fact is that there is more issues like no highlight for `tsx` files

here what it looks like
https://github.com/zed-industries/zed/assets/123704726/0b69bcfd-076b-46ce-af2b-8eb1f002c1d9

and for the `tsx` syntax 
![Zed_HJ1uyV3h7x](https://github.com/zed-industries/zed/assets/123704726/944817f1-70ef-45a4-afa3-3ef8bab57ef5)

### Environment

Zed: v0.138.0 (Zed Dev feea607bac1ae99c26bd10e4bf4cd28448e3ecfe)
OS: Windows 10.0.22631
Memory: 6.8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/123704726/c6a8983b-13b8-4511-a1e2-bc04ac93d571

![Zed_HJ1uyV3h7x](https://github.com/zed-industries/zed/assets/123704726/5c994c7f-c166-4684-a314-e40988a73461)

**Comment by Luca-Ilari** [comment]
I have the same problem

**Comment by rohit20v** [comment]
Can't seem to get it working for me either

**Comment by d1y** [comment]
This may be a temporary solution
```jsonc
{
  "file_types": {
    "TSX": ["ts"]
  }
}
```
