### ISSUE TITLE
Open project behaves inconsistently

### ISSUE THREAD

**Issue by Linyuqiz** [zed-industries/zed#12202]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open project behaves inconsistently
Open method one：
Click directly to select the project and open it in the current window.
<img width="748" alt="image" src="https://github.com/zed-industries/zed/assets/48901168/167bbb0c-3538-4ff3-b9a7-f5517750c0ae">
<img width="466" alt="image" src="https://github.com/zed-industries/zed/assets/48901168/d22d0bf6-8d3a-48d8-a568-53953738c235">

Open method two：
Shortcut key option+cmd+o to open the selected project and then open it in a new project
<img width="499" alt="image" src="https://github.com/zed-industries/zed/assets/48901168/e2a1a443-bf3f-4863-a149-6b5a850aab3d">

Final suggestion: It is recommended that the opening method be unified as the current window

### Environment

<img width="257" alt="image" src="https://github.com/zed-industries/zed/assets/48901168/ac56aca8-0be1-4b9e-91fe-c64c80a4b6d5">

**Comment by notpeter** [comment]
I believe this is fixed by:
- https://github.com/zed-industries/zed/pull/20176

Thanks for reporting!
