### ISSUE TITLE
Make scripts in package.json runnable

### ISSUE THREAD

**Issue by znycheporuk** [zed-industries/zed#12215]
### Check for existing issues

- [X] Completed

### Describe the feature

Recently ability to run tasks in gutter was added.
It would be great to add ability to run scripts in package.json, similar to WebStorm and VSCode. 

Option to select runner (npm, yarn, pnpm, bun) must be present.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="487" alt="image" src="https://github.com/zed-industries/zed/assets/42861377/f88b9f78-f444-463d-925e-673f02b1b7bc">

**Comment by osiewicz** [comment]
I like this idea a lot.
Possibly related (kinda): #12118

**Comment by RemcoSmitsDev** [comment]
Yeah kinda cool, but don't think we can include runnable for JSON files inside the JavaScript extension yet. To me, it makes sense to include them inside the JavaScript extension because you also run them with JavaScript/Node.

**Comment by JosephTLyons** [comment]
This went out today in [v0.138.0-pre](https://zed.dev/releases/preview/0.138.0).

**Comment by Malix-Labs** [comment]
See https://github.com/zed-industries/zed/discussions/61230
