### ISSUE TITLE
Scrolling up/down in Terminal using keyboard

### ISSUE THREAD

**Issue by nesadkadric** [zed-industries/zed#12231]
### Check for existing issues

- [X] Completed

### Describe the feature

In iTerm, it is possible to scroll with cmd-up/down. Currently, when using the Zed terminal, I have to move my hand from the keyboard to the mouse to read long text, which disrupts my workflow.

From my understanding, the Zed terminal is based on Alacritty, which supports the following actions:

ScrollPageUp
ScrollPageDown
ScrollLineUp
ScrollLineDown
ScrollToTop
ScrollToBottom

Is it possible to implement similar scrolling capabilities in the Zed terminal? I have attempted to achieve this in both vim and normal mode but haven't been successful.

**Comment by JosephTLyons** [comment]
This was released in [v0.143.x-pre](https://zed.dev/releases/preview/0.143.0).
