### ISSUE TITLE
Wasmtime causes Zed to fail to compile on some architectures

### ISSUE THREAD

**Issue by someone13574** [zed-industries/zed#12248]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed will not compile on i686 (this one might be fixable), arm6l, arm7l, and probably more because `wasmtime`, as used by Zed's extension system, doesn't support these architectures for codegen.

Not sure how you would deal with this other than explicitly marking these architectures as unsupported so that it fails immediately instead of an hour into a build.

### Environment

.

**Comment by FlyGoat** [comment]
Maybe it's possible to use [`wasmi` ](https://github.com/wasmi-labs/wasmi) or some other wasm engine as alternative to `wasmtime`.

**Comment by 12101111** [comment]
wasmi don't support [Webassembly Component Model](https://github.com/WebAssembly/component-model)

**Comment by notpeter** [comment]
I'm going to close this is unactionable.
We do not officially support `i686`, `arm6l`, `arm7l` or any 32bit platform.
The lack of `wasmtime` support is likely one of many issues you may run into.
Thanks for reporting.
