### ISSUE TITLE
Zed Preview: organizeImports stopped working for TypeScript LSP's code_action_on_format

### ISSUE THREAD

**Issue by morlinbrot** [zed-industries/zed#12256]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm on the Preview version and some time in the last weeks, the `organizeImports` of the TypeScript LSP stopped working. In the stable version, it is still working as I noticed today, unfortunately I can't remember which update brought the breaking change.

Here's the config I'm using:
```
  "language_overrides": {
    "TypeScript": {
      "code_actions_on_format": {
        "source.organizeImports": true
      },
      "format_on_save": {
        "external": {
          "command": "node_modules/.bin/prettier",
          "arguments": ["--stdin-filepath", "{buffer_path}"]
        }
      }
    },
```

### Environment

Zed: v0.137.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Is the buffer you're saving dirty? We've stopped executing on-save format for non-dirty buffers in https://github.com/zed-industries/zed/pull/9813

**Comment by osiewicz** [comment]
Is this reproducible with latest Preview as well?
