### ISSUE TITLE
Please add "make" to script/linux 

### ISSUE THREAD

**Issue by shahverd** [zed-industries/zed#12251]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm using a fresh ubuntu (wsl) and "make" is not installed by default.

**Comment by JosephTLyons** [comment]
Ok - I completely misinterpreted that! Thanks for clarifying!

**Comment by mikayla-maki** [comment]
This doesn't seem like our issue? Rather, it's a problem with how your open ssl was configured.
