### ISSUE TITLE
Autocomplete order is not correct.

### ISSUE THREAD

**Issue by iitzrohan** [zed-industries/zed#12280]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

currently when typing "for" the autocomplete window shows for_each as top result whereas it should be for loop in c++.

### Environment

Zed: v0.137.2 (Zed Preview)
OS: Linux 1.0.0
Memory: 15 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[
![screenshot-2024-05-25-12-31-16](https://github.com/zed-industries/zed/assets/104166410/146b1920-844f-4a77-ac33-fa55c03e2421)
](url)

**Comment by notpeter** [comment]
I'm going to close this in favor of:
- https://github.com/zed-industries/zed/issues/12698

Thanks for reporting.
