### ISSUE TITLE
View NPM scripts

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12308]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/zed-industries/zed/assets/20476002/5d06a74f-9ad3-46e8-b589-4f432abe5d23

Hi! @RemcoSmitsDev : Since you've already worked on something similar, you might want to take a look.

**Comment by RemcoSmitsDev** [comment]
Can you explain more what you are missing inside Zed now and what problem the feature you are pointing out solves? If I look at the video, it seems that it's similar to this, but more in a file structure way.

<img width="335" alt="Screenshot 2024-05-26 at 11 13 46" src="https://github.com/zed-industries/zed/assets/62463826/5f2f8e37-ad72-403d-9ebd-f2d52fbe4bbf">

**Comment by versecafe** [comment]
instead of a terminal UI for it could have the tasks panel search over all `package.json`, `Cargo.toml`, etc to find all valid "scripts" ignoring dirs that are in the `.gitignore`

**Comment by versecafe** [comment]
<img width="1402" alt="image" src="https://github.com/zed-industries/zed/assets/147033096/28b83514-7bff-472e-a3eb-29fcd556ffa8">

It also picks up default tasks for rust projects such as cargo run cargo test etc

**Comment by RemcoSmitsDev** [comment]
Yeah, like @versecafe is pointing out. Zed already has a modal where you can see all the tasks that you can run inside the current context. If you would like to run tasks that are not connected to a context (file, line, column, symbol etc.) then you need to make them yourself. That you could see all the tasks, instead only the ones that you can run in the current context.

So to come back to your feature request, I think the `task: spawn` modal already shows all the tasks you want to see in a quick way.

**Comment by RemcoSmitsDev** [comment]
@Angelk90 Running scripts inside `package.json` and `composer.json` was just merged a couple of hours ago. This will probably be out Wednesday in the preview release.

**Comment by reslear** [comment]
It would also be cool to have automatic script loading with the ability to pins

https://github.com/user-attachments/assets/c36b0fbd-317a-4330-aad8-09386ff17b23

**Comment by notpeter** [comment]
Since this issue was opened, Zed has added support for detect npm scripts. Just open package.json in question:
<img width="694" alt="Screenshot 2024-12-16 at 3 01 04" src="https://github.com/user-attachments/assets/e4c0a92c-7f39-4b75-a2c7-ce3252eedde7" />
And you will have a series of Play Buttons next to them.

Zed currently does not have a dedicated tasks panel and instead has opted to include task runnables in the context where they can be used, either via the Task Modal or in the sidebar. 

This is design decision, partly to avoid the clutter common in a VSCode unified tasks panel:
<img width="408" alt="Screenshot 2024-12-16 at 3 19 40" src="https://github.com/user-attachments/assets/b2438272-98a5-4d18-bab1-430854262423" />

Thanks for reporting.

**Comment by TreeOfLearning** [comment]
Yeah, big disappointment. This is a dealbreaker for me I'm afraid.

For an IDE that claims to be all about speed and efficiency, it seems odd to me to make a design choice that intentionally aims to  _increase_ friction. I probably use the npm scripts panel in vscode over 30 times a day. It takes less than a second each time. If I were to have to open package.json and find the right section in the file each time that could easily become 5-10 seconds. Suddenly I am wasting 300+ seconds a day, 25 minutes a week. Not very efficient. 

Unless I've misunderstood what @notpeter was trying to say?

**Comment by tuckerbeauchamp** [comment]
I believe there is some confusion here.

There are 2 (and a half) ways to run NPM scripts that I have found.

1. As highlighted by @notpeter. If you navigate to the `package.json` file you can click on the arrow next to the script.

I would probably never use this. I would not want to navigate to this file every time I want to execute a script. It would be pretty cumbersome, but it's there if you find it useful.

2. If you open up the [Command Palette](https://zed.dev/docs/command-palette?highlight=command#command-palette) and run [`task:spawn`](https://zed.dev/docs/tasks?highlight=task%3A#tasks) it will show all tasks available to your Zed editor. (Alternatively you can use `cmd + shift + r`, at least thats the case for me).

The task panel displays all the NPM scripts located in `package.json` as well as any [task](https://zed.dev/docs/tasks?highlight=task%3A#tasks) that you have created yourself.

2 (and a half). If that still isn't to your liking, you can create your own tasks for common NPM scripts (start, install, test, etc..) and assign them to keybindings. 

For example, coming from Neovim I really liked using `<space>gg` to open up lazygit. To recreate this behavior, I created a task that launches lazyvim and associated it with the same keybinding. This could easily be adapted for the NPM scripts.

Edit: video didn't upload correctly, so here's screenshots instead.

<img width="444" height="303" alt="Image" src="https://github.com/user-attachments/assets/22d14723-67c2-4007-9747-5359907f6862" />

<img width="437" height="320" alt="Image" src="https://github.com/user-attachments/assets/9932dd49-d1d1-488f-bdfe-03f4106e8474" />

**Comment by ExEr7um** [comment]
> 2. If you open up the [Command Palette](https://zed.dev/docs/command-palette?highlight=command#command-palette) and run [`task:spawn`](https://zed.dev/docs/tasks?highlight=task%3A#tasks) it will show all tasks available to your Zed editor. (Alternatively you can use `cmd + shift + r`, at least thats the case for me).
> 
> The task panel displays all the NPM scripts located in `package.json` as well as any [task](https://zed.dev/docs/tasks?highlight=task%3A#tasks) that you have created yourself.
> 

It does that only if you have `package.json` opened. If you’re in any other file, it won’t show NPM scripts.

**Comment by PCOffline** [comment]
> It does that only if you have `package.json` opened. If you’re in any other file, it won’t show NPM scripts.

I personally find this caveat extremely annoying. Especially in the scope of a project that is pure JS with `package.json` at the root, I'd expect Zed to always recognise the `npm` scripts and show them in tasks, even when the `package.json` file is not open.

**Comment by fullyherge** [comment]
If anyone is interested we have built and published a workaround via a CLI package that crawls `package.json` scripts and syncs them into zed tasks.
https://www.npmjs.com/package/@fullystudios/zed-npm-script-tasks
