### ISSUE TITLE
Ui view console terminal

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12307]
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the image in the zed layout the tabs at the top are opened, if you open so many terminals it is confusing and it is not even possible to rename the tabs.

In the style of vs code this way it is more tidy.

Vscode:
<img width="550" alt="Screenshot 2024-05-26 alle 10 18 23" src="https://github.com/zed-industries/zed/assets/20476002/fa8dc853-2986-41ec-86a1-5836f6abcaab">

Zed:
<img width="643" alt="Screenshot 2024-05-26 alle 10 21 06" src="https://github.com/zed-industries/zed/assets/20476002/5a4ad624-ce44-4125-a871-1e61f959a956">

Suggestions:
<img width="504" alt="Screenshot 2024-05-26 alle 10 31 51" src="https://github.com/zed-industries/zed/assets/20476002/f2a8074f-2687-43a9-80b3-31a11581f675">

![image](https://github.com/zed-industries/zed/assets/20476002/941ca338-0ea9-4fbb-815e-7e95e123eb22)

https://user-images.githubusercontent.com/806104/161374050-7e8cc0b5-e731-49a3-a7de-6fd41328adea.mp4

**Comment by notpeter** [comment]
This request is unscoped and unactionable. Closing.

**Comment by notpeter** [comment]
@Angelk90 Stop spamming user notifications.
He is already subscribed and will get a notification.
