### ISSUE TITLE
Windows: Zed is Launching, not crashing, but not showing

### ISSUE THREAD

**Issue by firminunderscore** [zed-industries/zed#12300]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Build zed (release or debug)
Run it

### Environment

OS : Windows 11 23H2 22631.3593
CPU : AMD Ryzen 5 4600H with Radeon Graphics 3.00 GHz
RAM : 16,0 GB (15,4 GB usable) DDR4 3200MHz
GPU 0 : NVIDIA GeForce GTX 1650 Ti
GPU 1 : AMD Radeon(TM) Graphics

### If applicable, add mockups / screenshots to help explain present your vision of the feature

For debugging purpose, i've set `RUST_LOG=blade=debug`
![image](https://github.com/zed-industries/zed/assets/40271484/44e44485-d0e0-4b14-bfef-e63fa3f6c748)
![image](https://github.com/zed-industries/zed/assets/40271484/bddfeee0-21ec-49eb-bef2-a91d50d38eec)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15445429/Zed.log)

**Comment by firminunderscore** [comment]
I don't know if this helps, but none of my GPUs support Vulkan.

**Comment by notpeter** [comment]
I'm going to go ahead close as stale as it hasn't been touched in 5months. If you're still unable to launch on Windows, please open a clean issue with your system specs, driver versions and the relevant error logs. Thanks for reporting.
