### ISSUE TITLE
Treesitter scope highlighting

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/zed#12312]
### Check for existing issues

- [X] Completed

### Describe the feature

As we now have indent guides (#11503), we can now implement an incredibly useful feature which I've only seen in neovim. It highlights the current scope by making a guide thicker (see screenshots for details)

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1440" alt="Screenshot 2024-05-26 at 13 29 19" src="https://github.com/zed-industries/zed/assets/43210583/4b7e58f4-3b68-4491-b73a-a5dc53bfd156">

**Comment by mikayla-maki** [comment]
I believe we do this already, except with only a color change.

**Comment by evrsen** [comment]
> I believe we do this already, except with only a color change. 

I also think an increase in thickness would be nice, not only aesthetically but this can also be a nice feature for color blind people.

**Comment by WeetHet** [comment]
> I believe we do this already, except with only a color change.

Oh, yeah, it's really hard to notice though

**Comment by WeetHet** [comment]
@mikayla-maki if you could point me to where this is done, I'll gladly add this as an option

**Comment by matubu** [comment]
> @mikayla-maki if you could point me to where this is done, I'll gladly add this as an option

Looking at the code, it seems that the bounding boxes of indent guides are collected here: https://github.com/zed-industries/zed/blob/main/crates/editor/src/element.rs#L1403 and then rendered here: https://github.com/zed-industries/zed/blob/main/crates/editor/src/element.rs#L2735
