### ISSUE TITLE
Themes JSON schema is incomplete

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12319]
### Check for existing issues

- [X] Completed

### Describe the feature

 The example scheme file is missing some attributes with the description, see some examples below. 

Link: https://zed.dev/schema/themes/v0.1.0.json

`conflict.background, conflict.border, created.background, created.border, deleted.background, ecc..`

For example for `syntax`, the description of all keys is missing.

**Comment by maxdeviant** [comment]
> For example for `syntax`, the description of all keys is missing.

The `syntax` keys are dynamic, so it is expected that they won't have descriptions.

**Comment by notpeter** [comment]
For anyone seeking documentation about the of the `syntax` keys
- see: https://zed.dev/docs/extensions/languages#syntax-highlighting
