### ISSUE TITLE
Default font size and consistency

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#12314]
### Check for existing issues

- [X] Completed

### Describe the feature

I usually never customise the font size of applications i use because 99% of them are the same or similar, but for Zed the default font size is *huge* (is there any particular reason for this?) and i would suggest using a smaller font size by default like all other applications.

The font size for the editor (huge), the explorer (ok large), the notification panel (a bit too large) and the chat panel (extremely small) are vastly different for some reason?

### If applicable, add mockups / screenshots to help present your vision of the feature

Difference between vscodes default font size vs zeds:
![Screenshot 2024-05-26 at 13 56 20](https://github.com/zed-industries/zed/assets/146845123/efb294aa-5232-471f-b293-50434cd5ff33)

**Comment by evrsen** [comment]
Also, how come setting ui_font_size to 13.. is smaller than every other applications 13? is there like some font size standard that zed doesn't follow?

**Comment by icarusgk** [comment]
I don't have this issue, my font size is 13 on both VS Code and Zed with a line height of 1.8.

![Screenshot 2024-05-26 at 8 15 09 PM](https://github.com/zed-industries/zed/assets/38413630/853040b5-eddd-48b0-abad-62036f407e76)

**Comment by evrsen** [comment]
![Screenshot 2024-05-27 at 11 44 10](https://github.com/zed-industries/zed/assets/146845123/a4246c6f-2f1e-48da-9b15-60ff6b268aa4)
for me 13 on zed is larger than 13 on vscode
