### ISSUE TITLE
Zed does not work with taskbar auto hide on Windows

### ISSUE THREAD

**Issue by AHL00** [zed-industries/zed#12313]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Zed fullscreened on Windows with the taskbar hidden automatically, moving the mouse to the bottom of the screen does not bring up the taskbar. The issue is isolated to Zed only, every other app works perfectly fine. 

### Environment

OS: Windows 11 Pro 23H2

**Comment by MolotovCherry** [comment]
Same experience here as of posting date, on 936466e02c06c718339b7516386a8cfc5356af24

**Comment by MolotovCherry** [comment]
@JunkuiZhang Do you know anything about this? I looked a bit into it, but I can't identify what's causing this behavior.

(Note: This should be about maximizing, not fullscreen. Fullscreen works as intended by not bringing up the taskbar, but it also does not come up when window is maximized)

**Comment by JunkuiZhang** [comment]
> @JunkuiZhang Do you know anything about this? I looked a bit into it, but I can't identify what's causing this behavior.

I see, BTW, does Windows still support setting the taskbar to other sides, like the left or right? I can't seem to find the relevant settings on my Windows 11.

**Comment by MolotovCherry** [comment]
> > @JunkuiZhang Do you know anything about this? I looked a bit into it, but I can't identify what's causing this behavior.
> 
> I see, BTW, does Windows still support setting the taskbar to other sides, like the left or right? I can't seem to find the relevant settings on my Windows 11.

Looks like you're right. Apparently Microsoft removed this functionality in Win11. 😕
