### ISSUE TITLE
Theme changes back to the last theme before the current one when installing/uninstalling extensions

### ISSUE THREAD

**Issue by libewa** [zed-industries/zed#12318]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When installing or uninstalling an extension, the theme changes to the theme used before switching to the current one. The theme setting in `settings.json` is not modified. After restarting Zed, the error is fixed and the correct theme is applied. The bug also only seems to occur when the theme was changed during the current session.

This bug may be related to, but not a duplicate of 
- #9724.

### Environment

```
Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 7.7 GiB
Architecture: x86_64
```
The Linux distro is a NixOS 24.05 beta with [this `flake.lock`](https://github.com/libewa/nixconfig/blob/main/flake.lock).

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15447534/Zed.log)

**Comment by notpeter** [comment]
I believe this has been fixed in the intervening 5 months.
If you are still experiencing this, please comment below with reproduction instructions and/or a video demonstrating what you are seeing and I'm happy to reopen.

Thanks for reporting!
