### ISSUE TITLE
go: testing submodule support for runnables

### ISSUE THREAD

**Issue by anilsenay** [zed-industries/zed#12323]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As we discussed in PR https://github.com/zed-industries/zed/pull/12003, the way we did to run tests is not working for submodules. Because we use parent directory of test file in `go test` command as pattern like `go test {parentDir} -run {testName}`. It works for tests in current module but it won't if running a test in a different module.

for example we opened a project in Zed like this:
```bash
.
├── submodule/
│   ├── submodule.go
│   ├── submodule_test.go
│   └── go.mod
├── main.go
├── main_test.go
└── go.mod
```

`go test . -run TestXxx` will work but `go test ./submodule -run TestXxx` will not. 
It gives error as `main module (my-project) does not contain package my-project/submodule`

There are some potential fixes for this:

1. Most easily, using file path instead of relative path of parent directory in `go test` command: `go test ./submodule/submodule_test.go -run TestXxx`. 

2. Detect module directory of test file (`./submodule` for `submodule_test.go`) and setting `cwd` variable of `TaskTemplate` as this directory. So cwd = ./submodule and test command will be `go test . -run TestXxx`

3. Similar to 2, cwd will be set as module directory but we will use package tree instead of file system tree. Which I mean, when we detect the module of file, we should also get module name in go.mod like `github.com/xx/some-package`, then the test command should be `go test github.com/xx/some-package/submodule -run TestXxx`. 
I think vscode-go extension doing something similar to this:
`Running tool: /usr/local/go/bin/go test -timeout 300s -run ^TestSomething$ github.com/anilsenay/zed-go-test/slice`
The reason I came with this is that it could be useful for features which require package tree like this in the future:
![resim](https://github.com/zed-industries/zed/assets/1047345/547d17f1-c454-4bfa-bef6-4ec8bf446c81)

### Environment

Zed: v0.138.0 (Zed Dev ddb551c794345538dbef112c5bcc2ae99f27b07f)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Hi @anilsenay, can you check if this is still an issue with recent versions of Zed?  There has been work to improve how we detect runnables and build tasks and I wanted to see if this issue stands or if any of the details have changed in the intervening six months. Thanks

**Comment by anilsenay** [comment]
It is fixed 🚀 

I tested for an old Zed(0.138.0) and latest(0.160.7) and results are:

![resim](https://github.com/user-attachments/assets/a5cdc53d-0324-4dc9-b374-72b2ec0dcf6d)

As you see, tests in a submodule did not work in old version(on the left) but they did in latest (on the right)
