### ISSUE TITLE
Undo / redo menu items are always greyed out

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#12335]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Title

### Environment

Zed: v0.138.0 (Zed Nightly 78aaa29d5b768f09ae393bf3d3f150d9f803f3df)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/4bfd9745-0a81-4af2-b41a-93f30f31dab2)

**Comment by versecafe** [comment]
I have a quick fix by swapping from `os_action` to `action` which has everything working fine but I'm not sure if there was an underlying benefit to making it an OS action instead, if it's not very important I can go PR the patch

**Comment by versecafe** [comment]
@JosephTLyons Do you have any opinion on this patch solution?

**Comment by JosephTLyons** [comment]
To be honest - Im not entirely sure - tagging in @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
I have no clue, but here's the place where any code changes should be done, if that's possible: https://github.com/zed-industries/zed/blob/c03600c55ecde723f721ce6cf2456dd8f674379f/crates/gpui/src/platform/mac/platform.rs#L213-L220

Here, some macOS platform code is called, and some extra incarnation has to be called on top.
We call the same creation code for every action, and I've noticed that Copy & Paste actions are greyed out when the buffer is not shown, but I'm not sure what code does that.
