### ISSUE TITLE
File Structure tab is not getting updated on "Open"

### ISSUE THREAD

**Issue by alanbosco003** [zed-industries/zed#12346]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently in other IDE when we open a new folder the file structure will also get updated, but here It's not happening.

BTW, the internal files are shown(opened) in the same file system. It doesn't look good. 

Can make it a feature, when the user opens a folder the whole file system will also get updated.

<img width="1203" alt="Screenshot 2024-05-27 at 4 28 37 PM" src="https://github.com/zed-industries/zed/assets/67573902/e4830ae3-26e4-4a6b-9a4f-035bc6bcc3dd">
<img width="1203" alt="Screenshot 2024-05-27 at 4 28 37 PM" src="https://github.com/zed-industries/zed/assets/67573902/e4830ae3-26e4-4a6b-9a4f-035bc6bcc3dd">

**Comment by JosephTLyons** [comment]
Going to close this issue out. If you are still running into this in current Zed:

1. Check to see if #12254 covers what you are requesting and upvote if it does, if not
2. Feel free to open another issue providing the details @Moshyfawn requested.
