### ISSUE TITLE
Project search does not respect .gitignore automatically

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#12341]
### Check for existing issues

- [X] Completed

### Describe the feature

Project search does not respect `.gitignore` automatically. This leads to 2 behaviors:

- It is inconsistent with commands like `file_finder::Toggle`. Finding files for project automatically ignores files in `.gitignore`. 
- It searches data files (`*.json`, `*.csv`, etc.) ignored by `.gitignore` which could be large and cause Zed hanged or sometimes killed.

Although there is a toggle filters button, it's hard to input all patterns ignored by `.gitignore`. I personally think respecting `.gitignore` is a better default.

**Comment by notpeter** [comment]
I can no longer reproduce this and I believe this has been fixed.
If you are still experiencing this, please comment with steps to reproduce and I'm happy to reopen.

Thanks for reporting!
