### ISSUE TITLE
Repeating "Do you want to install the recommended  extension" pop up

### ISSUE THREAD

**Issue by sinao-dev** [zed-industries/zed#12342]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I get a repeating "Do you want to install the recommended 'php' extension for 'php'" and when I click yes it appears again until I delete the extension and install it again

### Environment

Zed: v0.136.2 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-05-27 at 11 06 25](https://github.com/zed-industries/zed/assets/69112588/1a374c7e-86b5-4897-8c0d-fcdc1998f70c)

**Comment by notpeter** [comment]
I believe this has been resolved. If you are still seeing this issue, please comment below with your current Zed environment (`zed: copy system specs to clipboard` from command palette) and I'm happy to reopen.

Thanks for reporting!
