### ISSUE TITLE
The software is very beautiful, but can some functions be made into plugins?

### ISSUE THREAD

**Issue by lvtao-net** [zed-industries/zed#12353]
### Check for existing issues

- [X] Completed

### Describe the feature

Channels and chats, as a developer, I think the lightweight nature of the software is more suitable, such features can be made into plugins.

**Comment by lvtao-net** [comment]
As a user in the Chinese mainland, OpenAI cannot be used normally. It would be best to be able to configure the API domain. Of course, it would be even better if there were other AI plugins available. For example, Groq or Gemini.

**Comment by jansol** [comment]
It is already possible to change the API endpoint, see https://zed.dev/docs/assistant-panel#using-a-custom-api-endpoint-for-openai

**Comment by Moshyfawn** [comment]
One of the pillars of the Zed concept is its "multiplayer" nature. I doubt that shipping channels as a plugin would be something the Zed team would consider.

<img width="502" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/150a8376-289a-454c-9f26-60eed22beb43">

**Comment by Moshyfawn** [comment]
Related:
- #7121

**Comment by iamnbutler** [comment]
I can say with near absolute certainty that collaboration in zed will never be made into an extension or be disabled by default, as the core of the company is build on the foundation of collaborative editing.

That being said, the project is OSS, I'm sure someone has a zed-no-collab fork going somewhere :)

Closing, but feel free to discuss further in a discussion.
