### ISSUE TITLE
Can't move mouse over tooltips from bash LSP

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#12356]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Basher extension adds support for bash-language-server which provides, among other things, hover hints based on man pages. However unlike with other language servers, these are not highlighting the symbol that is being hovered over and the tooltip is not immediately next to the symbol, meaning that it disappears when the mouse is moved from the symbol to the tooltip in order to scroll through a longer description.

bash-language-server:
![image](https://github.com/zed-industries/zed/assets/2588851/ed56c06d-0d68-4497-8f3b-b037039fc791)
clangd:
![image](https://github.com/zed-industries/zed/assets/2588851/5f9c2c20-77e8-4eda-911a-90e5f67c2c79)

### Environment

Zed: v1.0.0 (Zed Dev e19339bc1d038b39c5ee69ca728042d13d555fc7)
OS: Linux 1.0.0
Memory: 30.9 GiB
Architecture: x86_64

**Comment by osiewicz** [comment]
The results returned by bash-language-server do not include a range for which a hover is valid, which leads to theflickery. See also: https://github.com/zed-industries/zed/pull/13481#issuecomment-2230248196 which was fixed by including the range in the response from language server.

**Comment by WeetHet** [comment]
Probably fixed by #16062

**Comment by jansol** [comment]
This does indeed appear to be fixed now.
