### ISSUE TITLE
[Windows] Scrolling upwards causes Zed to click window X button and close

### ISSUE THREAD

**Issue by MolotovCherry** [zed-industries/zed#12369]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This was a bit hard to explain in the title, so here it is:

- maximize the window (this makes it easier to accidentally hit, but it is not a requirement)
- click and hold mouse button down on the right scrollbar and scroll up all the way to the top
- let your mouse cursor reach the top of the window while still holding it down
  - your mouse should now be over the window's X button
- Let your mouse release while it's over the X button
- Zed will now close since it thinks you clicked the window X button

Note: This happens with all caption buttons, Not only X, but also minimize and fullscreen/restore

### Environment

Zed: v0.138.0 (Zed Dev f7115be3d18c8964d45fb8efc1941080b20acc32)
OS: Windows 10.0.22631
Memory: 63.8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Animations](https://github.com/zed-industries/zed/assets/13651622/30255314-9944-4b44-a5ad-d42a54163fcd)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

n/a

**Comment by huacnlee** [comment]
@JunkuiZhang 

This is also appearing: 

1. Mouse down the scroll bar, 
2. Then move out of the Zed window, the scroll event will break.

**Comment by MolotovCherry** [comment]
Example of breaking the scroll event, do any of these:
- Let the mouse leave the Zed window
- Let the mouse go over the Windows titlebar.

![Animations](https://github.com/zed-industries/zed/assets/13651622/df2c9d3c-7a70-48af-ba3c-934d043d3020)
