### ISSUE TITLE
Tab highlight symbolic links

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12371]
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode also highlights in the tab that they are symbolic links.

![image](https://github.com/zed-industries/zed/assets/20476002/965fd1ad-c93b-44c9-9136-a6bc40c95e56)

Vscode:
<img width="974" alt="Screenshot 2024-05-28 alle 14 11 14" src="https://github.com/zed-industries/zed/assets/20476002/80f457fa-9dda-44cb-afa3-8a363fa61655">

Zed:

<img width="795" alt="Screenshot 2024-05-28 alle 14 05 49" src="https://github.com/zed-industries/zed/assets/20476002/8c626c84-d10e-4a5a-b999-cf9c079ccc41">

**Comment by evrsen** [comment]
Is there some specific behavior that occurs when you click this arrow?

**Comment by notpeter** [comment]
Zed currently displays an icon in the project panel to identify symlinks.
<img width="288" alt="Screenshot 2024-12-16 at 3 27 18" src="https://github.com/user-attachments/assets/0248b8d1-3a42-4e67-b3f8-8bc534762ea8" />

Closing as we intend to avoid adding additional visual clutter in the tab bar.
Thanks for reporting.
