### ISSUE TITLE
GPUI: Use a typestate builder for flexes

### ISSUE THREAD

**Issue by someone13574** [zed-industries/zed#12390]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be helpful if flex-specific functions on Div were not available unless you use .flex(). This could be pretty easily checked at compile time using a typestate builder pattern.

**Comment by maxdeviant** [comment]
I think this could cause more trouble than it's worth.

We do a bit of this already in GPUI (e.g., for `.id`), but it can cause lots of issues when you need to conditionally apply a style (and thus end up with mismatched branches within a conditional).
