### ISSUE TITLE
terminal: Alternate Scroll Mode support

### ISSUE THREAD

**Issue by Ding1367** [zed-industries/zed#12397]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

programs using curses or running vim (i dont know why youd do that in the ZED terminal but yeah) or any program that detects scrolling in the terminal, it just doesnt work with the zed terminal if you scroll ncurses or whatever doesnt pick up on it

### Environment

Zed: v0.136.2 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
This is called "Alternate Scroll Mode" and requires a setting to enable.

```json
  "terminal": {
    "alternate_scroll": "on"
  }
```

Then close and reopen your Terminal panes and bob's your uncle.

Source: [Configuring Zed: Terminal: Alternate Scroll](https://zed.dev/docs/configuring-zed#terminal-alternate-scroll)

Sorry it took so long to get you a response. Thanks for reporting.
