### ISSUE TITLE
TailwindCSS LSP doesn't work in an Astro project

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#12402]
### Check for existing issues

- [X] Completed

## Reproduction steps

1. `pnpm create astro` - select all default options - open the project in Zed.
2. `pnpm astro add tailwind` - choose `Y` for all prompts.
3. Open `src/pages/index.astro` - try adding a TailwindCSS class to the `main` tag:
```html
<main class="flex">
```
4. Note that no TailwindCSS LSP suggestions are displayed.
5. Try showing the autocompletions by selecting `editor: show completions` from the command palette.
6. Note that no TailwindCSS LSP suggestions are displayed.

## Expected behaviour

The expected behaviour in both cases `3` and `5` would be for the TailwindCSS classes autocompletions to be displayed. 

### Environment

Zed: v0.138.0 (Zed Nightly b466a8b828b69f46fe63eaae6f64b707be8ff035)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

## Zed.log

```shell
[INFO] Language server with id 13 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
```

## TailwindCSS LSP log

```shell
[Global] Creating projects: [{"folder":"/<project-path>/astro-tw-sandbox","configPath":"/<project-path>/astro-tw-sandbox/tailwind.config.mjs","isUserConfigured":false,"documentSelector":[{"pattern":"/<project-path>/astro-tw-sandbox/tailwind.config.mjs","priority":0},{"pattern":"/<project-path>/astro-tw-sandbox/**","priority":3}]}]
[Global] Adding watch patterns: /<project-path>/astro-tw-sandbox/tailwind.config.mjs, /<project-path>/astro-tw-sandbox
[tailwind.config.mjs] Initializing...
[tailwind.config.mjs] Loaded Tailwind CSS config file: /<project-path>/astro-tw-sandbox/tailwind.config.mjs
[tailwind.config.mjs] Loaded postcss v8.4.38: /<project-path>/astro-tw-sandbox/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
[tailwind.config.mjs] Loaded tailwindcss v3.4.3: /<project-path>/astro-tw-sandbox/node_modules/.pnpm/tailwindcss@3.4.3/node_modules/tailwindcss
[tailwind.config.mjs] Building...
```

## An additional log popped up (not sure when while trying to enter different classes)

```shell
Unhandled exception: Cannot read properties of undefined (reading 'colorDecorators')
TypeError: Cannot read properties of undefined (reading 'colorDecorators')
    at Object.onUpdateSettings (/<user-path>/Library/Application Support/Zed/languages/tailwindcss-language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:2953:621)
    at /<user-path>/Library/Application Support/Zed/languages/tailwindcss-language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:2953:13372
```

**Comment by imkarthikk** [comment]
@Moshyfawn I'm facing the same issue as well. I tried all sorts of configuration. Tailwind LSP is actually running properly, it unfortunately does not recognize or trigger for Astro tags to be specific. Also, from your logs, looks like only the `colorDecorators` does not work, which is find, and is a potential issue with Tailwind LSP as @mrnugget mentioned [in this PR](https://github.com/zed-industries/zed/pull/11858#issuecomment-2117119714).

On the other hand, if you are in a `.astro` file, the Tailwind LSP works just fine with autocomplete when using within the scoped `<style>` tag that Astro supports. It's weird. I used to think that TW LSP does not trigger for any `.astro` files. But then, it works within the `<style>` tag.

What's your `settings.json`? Do you have configs set for Tailwind LSP?

**Comment by Jonnotie** [comment]
I'm also running into this issue with my Astro project

**Comment by imkarthikk** [comment]
> I'm also running into this issue with my Astro project

@Jonnotie What's your `settings.json`? Do you have a config for Tailwind LSP?

**Comment by mrnugget** [comment]
99% sure I fixed it here: https://github.com/zed-industries/zed/pull/12741

Thanks for the amazing reproduction steps, @Moshyfawn.

**Comment by mrnugget** [comment]
I bumped the Astro extension to 0.0.3 here: https://github.com/zed-industries/extensions/pull/880 Should be available in a few minutes and include the fix here.

**Comment by imkarthikk** [comment]
@mrnugget Thank you for your amazing work Thorsten. 👏

**Comment by Moshyfawn** [comment]
Can confirm, the autocompletions are there now! Thanks  🙏
