### ISSUE TITLE
Markdown first underscore highlight wonky

### ISSUE THREAD

**Issue by vladdeSV** [zed-industries/zed#12424]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I believe that if the first highlighted Markdown term is with underscores, highlighting on that line becomes almost unpredictable. I can reproduce these patterns, but I cannot explain what happens. Please see provided gifs.

Please note that both examples both start with a single non-highlighted word, and only using underscores seems to cause problems.

![Kapture 2024-05-29 at 14 03 21](https://github.com/zed-industries/zed/assets/7542961/bdb15e12-15c2-4e81-bc8d-074cb713a433)

![Kapture 2024-05-29 at 14 13 54](https://github.com/zed-industries/zed/assets/7542961/5a8507b6-7962-4a30-82ea-f221c7dd2250)

### Environment

Zed: v0.136.2 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by vladdeSV** [comment]
Might be related to https://github.com/zed-industries/zed/issues/4565 and https://github.com/zed-industries/zed/issues/8108, but none of them show this exact issue I'm having

**Comment by vladdeSV** [comment]
I can no longer reproduce this bug in Zed `v0.148.1`. I assume it was fixed?

![Kapture 2024-08-19 at 17 02 05](https://github.com/user-attachments/assets/94ba897a-347f-46b5-906c-284b3d20b5a7)

**Comment by SomeoneToIgnore** [comment]
We have updated a lot of grammars recently, including a complete switch from unofficial to the official tree-sitter Markdown grammar, so I would say yes.

Thank you for rechecking.
