### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by evrensen467** [zed-industries/zed#12449]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed seems to use a lot of battery when I open large projects with it, f.e when working on the Zed repository.

### Environment

Zed: v0.137.3 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64
Chip: Apple M3

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="346" alt="Screenshot 2024-05-29 at 22 44 36" src="https://github.com/zed-industries/zed/assets/146845123/bb83fb07-9049-48ba-9f9f-3522767a4ff3">

**Comment by versecafe** [comment]
@evrsen Can you check your system usage with activity monitor to see what it's using, I have a suspicion that since you have an extremely small amount of RAM that between macOS, zed, the rust analyzer, and whatever background programs you're running your machine is heavily relying on swap which can push upwards of 9 watts which for an m3 air would be a nearly 25% power consumption bump over using the entire chip full throttle.

**Comment by evrsen** [comment]
Hmm, the RAM usage seems to be fine (doesn't go over to swap), the CPU usage also seems to be fine, however the energy levels are insanely high? I bought this MacBook yesterday, no other application I've used like Xcode and VSCode doesn't give me that energy consumption warning.
https://github.com/zed-industries/zed/assets/146845123/d4de78ca-b43e-475c-b8eb-2d9336ea7e98

**Comment by versecafe** [comment]
I'm pretty sure it's just the rust analyzer inside a massive project, every time you make a change it's doing a ton of work, it can put my M3 pro at 100% when I add a dep for example, can you do a small test of running just a light weight rust project or some small nodejs project to compare power consumption?

**Comment by evrensen467** [comment]
okay tried it on small projects, almost no energy impact at all, weird.. so it's rust-analyzer being rust-analyzer..?

**Comment by SomeoneToIgnore** [comment]
Not only — could be as well that Zed is too eager to query certain things.
Maybe inlay or completions requests could be called less frequently — but that would require a deep, through analysis of r-a load peaks to see which requests are making it so loaded.

**Comment by vishucrafts** [comment]
This happens on my M3 pro too.  Running a Next.js project with biome formatter and copilot. Ran docker-compose from zed terminal too if that matters
![Activity monitor high usage over last 12 hrs](https://github.com/zed-industries/zed/assets/45751230/49b781a6-04e9-4c1a-b7b3-35be7cc247ee)

**Comment by JosephTLyons** [comment]
Related: https://github.com/zed-industries/zed/issues/4417

**Comment by evrensen467** [comment]
I think it's a duplicate, apologies I should've searched for a similar issue more thoroughly, I'll close this one in favor of https://github.com/zed-industries/zed/issues/4417.

**Comment by JosephTLyons** [comment]
No worries @evrensen467 - I wasn't sure it was the same issue.
