### ISSUE TITLE
vim: Add a "za" shortcut for toggling code folding

### ISSUE THREAD

**Issue by CaptSolo** [zed-industries/zed#12450]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add a `za` key combination for toggling code folds open/closed in the VIM mode.

This key combination works in VIM but it does not work in Zed (instead, Zed switches to the insert mode as if just `a` was pressed).

### If applicable, add mockups / screenshots to help present your vision of the feature

Attachment: a screenshot from VIM help.

<img width="696" alt="image" src="https://github.com/zed-industries/zed/assets/39945/9c66caec-7a6e-457d-a3e6-fff3e7c84754">

**Comment by CaptSolo** [comment]
Just discovered there is an existing issue #6822 re. implementing this change. Apologies for a duplicate issue.

**Comment by JosephTLyons** [comment]
No worries @CaptSolo - feel free to upvote #6822!
