### ISSUE TITLE
Can't toggle off editor controls

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#12459]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you toggle on the editor controls, you can't toggle it off clicking on the button again, you have to click anywhere else except the popup to turn it off.

### Environment

Zed: v0.137.3 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/146845123/19d00b9c-6a8d-42d6-be44-ac0f35c379f4

**Comment by SomeoneToIgnore** [comment]
Zed 0.152.3 and above seem to have it fixed, thanks to @\osiewicz so I'll close this issue as fixed.
