### ISSUE TITLE
Cannot disable copilot

### ISSUE THREAD

**Issue by alexrkaufman** [zed-industries/zed#12479]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In my `settings.json` file I have the following json which used to disable copilot, or would at least remove the copilot button from view. This was taken from the page [Copilot x Zed](https://zed.dev/blog/copilot). Recently the copilot button showed back up but my settings file has not changed. 

`"features": {"copilot": false }`

### Environment

Zed: v0.137.3 (Zed)
OS: macOS 14.1.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="953" alt="copilot_issue" src="https://github.com/zed-industries/zed/assets/65193102/400ec917-4c6c-4fa3-ba24-16eea43dcf1d">

**Comment by Moshyfawn** [comment]
It seems that the way forward is to use
```diff
 "features": {
- "copilot": "false"
+ "inline_completion_provider": "none"
 }
```
instead.

See https://github.com/zed-industries/zed/issues/11537#issuecomment-2100495170 for more info.

**Comment by Moshyfawn** [comment]
@maxdeviant could we consider removing the `features.copilot` flag as Copilot has been decoupled in favour of multi-vendor support?

**Comment by alexrkaufman** [comment]
@Moshyfawn Thank you for directing me to 11537. I did not find that closed issue in my initial search. This solves my problem. 

It may be beneficial to include this somewhere in docs or updating the copilot page I linked to in my comment. I would be happy to lean in here if it would be helpful.
