### ISSUE TITLE
Strange editor area when showing plain text content

### ISSUE THREAD

**Issue by char8x** [zed-industries/zed#12473]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using `plain text`, a blank area appears in the editor.

<img width="1289" alt="图片" src="https://github.com/zed-industries/zed/assets/6831013/caf86095-ae8b-4cc7-be96-28d8838bbe2d">

When using `JavaScript`, the blank area disappears.

<img width="1289" alt="图片" src="https://github.com/zed-industries/zed/assets/6831013/ba3e8542-f0c2-499a-bd7c-6fe1f0660f22">

### Environment

Zed: v0.137.3
OS: macOS 13.6.7 arm64

**Comment by jansol** [comment]
Looks more like you have wrap guides disabled for JavaScript and for Plain Text you get a wrap guide at 80 columns or so?

**Comment by char8x** [comment]
Here is my settings, I didn't change the properties related to line wrapping

```json
{
  "theme": "One Dark",
  "buffer_font_family": "MesloLGS Nerd Font Mono",
  "auto_update": false,
  "base_keymap": "VSCode",
  "telemetry": {
    "metrics": false,
    "diagnostics": false
  },
  "ui_font_size": 16,
  "buffer_font_size": 16
}
```

**Comment by jansol** [comment]
Hm, looks like there indeed should not be any wrap guides by default.

From the default settings:
```json
 // Whether to show wrap guides in the editor. Setting this to true will
  // show a guide at the 'preferred_line_length' value if 'soft_wrap' is set to
  // 'preferred_line_length', and will show any additional guides as specified
  // by the 'wrap_guides' setting.
  "show_wrap_guides": true,
  // Character counts at which to show wrap guides in the editor.
  "wrap_guides": [],
  // How to soft-wrap long lines of text. This setting can take
  // three values:
  //
  // 1. Do not soft wrap.
  //      "soft_wrap": "none",
  // 2. Prefer a single line generally, unless an overly long line is encountered.
  //      "soft_wrap": "prefer_line",
  // 3. Soft wrap lines that overflow the editor:
  //      "soft_wrap": "editor_width",
  // 4. Soft wrap lines at the preferred line length
  //      "soft_wrap": "preferred_line_length",
  "soft_wrap": "prefer_line",
  // The column at which to soft-wrap lines, for buffers where soft-wrap
  // is enabled.
  "preferred_line_length": 80,
```
No language overrides for Plain Text either...

**Comment by char8x** [comment]
> Hm, looks like there indeed should not be any wrap guides by default.

When I set `show_wrap_guides` to `false`, the blank area disappears

<img width="1141" alt="图片" src="https://github.com/zed-industries/zed/assets/6831013/94af0ed3-2007-4e18-aa92-8e7e4ac51bf9">

**Comment by jansol** [comment]
Ah right, I vaguely remember that there is an implicit wrap guide drawn at `preferred_line_length` even if the `wrap_guides` list is empty. That should probably be documented better (or changed).

**Comment by notpeter** [comment]
This is fixed in dev.  Plain Text buffers (the default for untitled buffers) now default to soft wrapping at the window width and not at `preferred_line_length`.  So there will no longer be a wrap_guide by default in those buffers.

This fix is available in dev today, in the next version of Zed Preview on Wednesday (2024-07-17) and in Zed Stable a week later (2024-07-24).  Thanks for reporting!
