### ISSUE TITLE
Crash after editing task or template

### ISSUE THREAD

**Issue by nixpulvis** [zed-industries/zed#12503]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After opening the `task: spawn` modal, then clicking on "Edit template" (or perhaps "Edit task") I did something which caused Zed to crash.

I'm still learning Zed, so I'm not quite sure what I expect these actions to do, but I figure you would be interested to know when the program crashes.

### Environment

Zed: v0.137.5 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by nixpulvis** [comment]
Here's the macOS Crash Report: https://paste.rs/uVyyh.txt

**Comment by SomeoneToIgnore** [comment]
I suspect that https://github.com/zed-industries/zed/pull/12448 fixed that, thank you for the reminder that I have to cherry-pick it into the next hotfix release — either that or a new release on Wednesday is supposed to fix it.

**Comment by nixpulvis** [comment]
I'm not sure if it's relevant here or not, but the "Edit template" button seems fixed on `main` but when it turns into the "Rerun last task" button it no longer seems to work.

**Comment by osiewicz** [comment]
Oh yeah, it's just bound incorrectly (as you've said, it doesn't change behaviour at all depending on the label). Mea culpa, will fix
