### ISSUE TITLE
"Reveal in Finder" in multi-buffer doesn't work

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#12511]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open [the Zed repository](https://github.com/zed-industries/zed) in Zed.
2. Open the global search `cmd-shift-f` and search for `identifier`.
3. Right click on any entry and select the "Show in Finder" action.
4. Notice that the Finder isn't open with the file.

### Environment

Zed: v0.139.0 (Zed Nightly fda975fb76356b5a72774a84d259464be56be696)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1630" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/c7e330fb-d11c-4066-9ef7-1969159853d3">

**Comment by notpeter** [comment]
At some point this was fixed and I can no longer reproduce.
If this is incorrect, please comment below and I'm happy to reopen.
Thanks @Moshyfawn.
