### ISSUE TITLE
dim inactive panes

### ISSUE THREAD

**Issue by aexvir** [zed-industries/zed#12529]
### Check for existing issues

- [X] Completed

### Describe the feature

I usually work with multiple code splits, and without tabs, and I find it sometimes hard to know on what split I'm focused, as the cursor is small and it's in some random place of the codebase

similar to how zed has a setting for magnifying the active pane, I'd like to have a setting for dimming inactive panes, with a float number between 0 and 1, where 0 is completely transparent, and 1 is fully opaque

I checked the codebase a bit to see how this could be implemented but I didn't see any obvious way of achieving this, but I'd be very happy to contribute this feature if someone can provide me with some pointers

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1608" alt="capture-20240531152905" src="https://github.com/zed-industries/zed/assets/8055505/781f4319-6a4c-4b1e-abe1-82b648d5f14a">

**Comment by Moshyfawn** [comment]
Related:
- #8639
