### ISSUE TITLE
Support for loongarch64

### ISSUE THREAD

**Issue by Qinka** [zed-industries/zed#12537]
### Check for existing issues

- [X] Completed

### Describe the feature

Is there any plan to support loognarch64-unknown-linux-gnu.

I tried to compile zed on loongarch64 machine, but `cranelift-codegen v0.106.0` reported it does not support loongarch.

**Comment by maxdeviant** [comment]
> I tried to compile zed on loongarch64 machine, but `cranelift-codegen v0.106.0` reported it does not support loongarch.

It sounds like support for loongarch64 would need to be added upstream, if `cranelift-codegen` does not support it.

**Comment by someone13574** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/12248
