### ISSUE TITLE
Unable select (and copy) from documentation tip

### ISSUE THREAD

**Issue by gr8den** [zed-industries/zed#12547]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have ability to do selection (and copying) from documentation tip on hover (e.g for copying usage example)

**Comment by JosephTLyons** [comment]
Hey @gr8den (and everyone who has upvoted this) - I'm going to consolidate a few requests into a single issue. I think this request covers what you are looking for here - feel free to upvote it with a 👍 reaction:

- https://github.com/zed-industries/zed/issues/4606
