### ISSUE TITLE
Zed can not open after update to 0.137.6 version 

### ISSUE THREAD

**Issue by pengjianaixue** [zed-industries/zed#12549]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After update the Zed to Zed 0.137.6 version and restart, the Zed is can not open again. And I run it from terminal, and see the below **ERROR**

> ❯ /Applications/Zed.app/Contents/MacOS/zed ; exit;
> [2024-06-01T10:27:54+08:00 ERROR util] crates/workspace/src/persistence/model.rs:313: failed to read path after update

### Environment

MacBook Pro
Apple M1 Pro
Mac os 12.7.5 (21H1222)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="737" alt="image" src="https://github.com/zed-industries/zed/assets/21357301/9c96b5f7-0f62-40d4-a65e-7c83dc3d5a71">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/user-attachments/files/15520175/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @pengjianaixue - not sure what might be going on exactly. Would you mind trying something for me? Can you move the items in this directory out and somewhere else?

`~/Library/Application Support/Zed/db`

These are the databases that hold items such as recent projects, what files are open in a given project, where you were scrolled to. So after you move these items out, if Zed can successfully open, you'll lose that bit of data. I'm just curious if that would get you into Zed at least - and if so, we still have a bug here to deal with.

**Comment by pengjianaixue** [comment]
Thanks @JosephTLyons.
It's work, after I remove the content in ~/Library/Application Support/Zed/db, I get into the Zed.

**Comment by JosephTLyons** [comment]
Ok, well it isn't great that you lost all of your persisted workspace data, but at least you are up and running again. I'm going to close this issue out, but I'll keep my eye out for others who might be experiencing this, and if it comes up multiple times, we will dig into it.

**Comment by SomeoneToIgnore** [comment]
Here's another one: https://github.com/zed-industries/zed/issues/12709
