### ISSUE TITLE
Cannot rebind `cmd-+` on macos.

### ISSUE THREAD

**Issue by conradludgate** [zed-industries/zed#12555]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On vscode, I like to map cmd-shift-plus and cmd-shift-minus as the zoom in and out keys, as it's not a common operation for me. Instead, I map cmd-plus and cmd-minus as Forward/Back navigation.

I am using the following keymap.json

```json
[
  {
    "bindings": {
      "cmd-+": "pane::GoForward",
      "cmd--": "pane::GoBack",
      "cmd-=": "zed::IncreaseBufferFontSize",
      "cmd-_": "zed::DecreaseBufferFontSize"
    }
  }
]
```

But the cmd-+ key increases the font size and does not navigate forward.

### Environment

Zed: v0.137.6 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @conradludgate - I think this issue is largely the same as:

- https://github.com/zed-industries/zed/issues/12555

But it is missing the `cmd-_` case - which I've added in a comment - so I'm going to close this out. Can you upvote the other issue with a 👍?
