### ISSUE TITLE
Holding a key down, then pressing a modifier key stop sending key events

### ISSUE THREAD

**Issue by AngeloMateus** [zed-industries/zed#12566]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For example in vim mode:

- press j to nav down
- press shift while holding j

The shift event is sent but stops sending j, this means to hold uppercase j you must first press shift then j
Some vim users use capital J and K for faster navigation, this also affects arrow keys, which means to select lines you must first press shift (less of an issue I think).

Holding a character and lifting shift key will send character events again.

### Environment

Zed: v0.138.3 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

`zed/crates/gpui/src/platform/mac/window.rs line:1225`
``` rust
        if event.is_held {
            if lock.last_fresh_keydown.as_ref() != Some(&keydown) {
                return YES;
            }
        } else {
            lock.last_fresh_keydown = Some(keydown.clone());
        }
```

This seems to  prevent any other key events from being triggered after pressing modifier keys, maybe this should only affect modifier keys?
Removing it fixes this particular issue but I'm not sure exactly what it aimed to solve to begin with. Maybe someone with a better understanding of this code could take a look?

```diff
-        // Ignore events from held-down keys after some of the initially-pressed keys
-        // were released.
-        if event.is_held {
-            if lock.last_fresh_keydown.as_ref() != Some(&keydown) {
-                return YES;
-            }
-        } else {
-            lock.last_fresh_keydown = Some(keydown.clone());
-        }
+        lock.last_fresh_keydown = Some(keydown.clone());
```

**Comment by ConradIrwin** [comment]
Fixed by #13000
