### ISSUE TITLE
Wrong indent guide

### ISSUE THREAD

**Issue by willyamrb** [zed-industries/zed#12564]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There is a wrong indent guide position in the code. It seems that the indent guides are related to the indentation tabs. I attached a VSCode ref image.

### Environment

Zed: v0.138.3 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="206" alt="Screenshot 2024-06-01 at 17 55 42" src="https://github.com/zed-industries/zed/assets/43036521/80fe4856-1594-4aaa-8c4c-3c163e1a25b8">
<img width="200" alt="Screenshot 2024-06-01 at 17 57 32" src="https://github.com/zed-industries/zed/assets/43036521/f5bf0ed4-7cb7-4b35-ba88-253aaa0ededc">

**Comment by bennetbo** [comment]
Hey, thanks for the report. It looks like the indent guides are using a tab size of `2`, whereas they should be aligned with a tab size of `4`. 
What do your settings look like? Do you have a local (project specific) tab size configuration?

**Comment by willyamrb** [comment]
@bennetbo thanks for helping me, so I did not configured a specific tab_size in my settings, so when I add 4 value to the tab_size global setting it worked well. But as I work in too many projects I cannot set it globally so I tried local setting and it did not worked.

<img width="551" alt="Screenshot 2024-06-01 at 19 14 39" src="https://github.com/zed-industries/zed/assets/43036521/e5967f7d-6eb9-4ffc-bd52-515e059ebdbf">

<img width="650" alt="Screenshot 2024-06-01 at 19 14 24" src="https://github.com/zed-industries/zed/assets/43036521/ab271fa2-502c-4c50-8f4d-a1165d0bbc84">

**Comment by bennetbo** [comment]
Okay so it's working for you when you globally configure the tab size but not locally? If that's the case #12528 should fix your issue. We will probably release that fix in a patch tomorrow.

**Comment by willyamrb** [comment]
@bennetbo yes that's the problem, great to see that already fixed it! Thanks

**Comment by bennetbo** [comment]
Patch is out, this should be fixed in v0.138.4

**Comment by ACERTIJO7TESLA369** [comment]
> ### Check for existing issues
> 
> - [X] Completed
> 
> ### Describe the bug / provide steps to reproduce it
> 
> There is a wrong indent guide position in the code. It seems that the indent guides are related to the indentation tabs. I attached a VSCode ref image.
> 
> ### Environment
> 
> Zed: v0.138.3 (Zed Preview)
> OS: macOS 14.5.0
> Memory: 16 GiB
> Architecture: aarch64
> 
> ### If applicable, add mockups / screenshots to help explain present your vision of the feature
> 
> <img width="206" alt="Screenshot 2024-06-01 at 17 55 42" src="https://github.com/zed-industries/zed/assets/43036521/80fe4856-1594-4aaa-8c4c-3c163e1a25b8">
> <img width="200" alt="Screenshot 2024-06-01 at 17 57 32" src="https://github.com/zed-industries/zed/assets/43036521/f5bf0ed4-7cb7-4b35-ba88-253aaa0ededc">
> 
> 
> ### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
> 
> _No response_
