### ISSUE TITLE
serious memory leak issue on windows10

### ISSUE THREAD

**Issue by shenjackyuanjie** [zed-industries/zed#12561]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

as we all know, ( #8436 #7939
zed have some tiny memory leak(?) issue since sometimes ago
some how, it will only increase the memory usage for about 1mb/min ( on my windows 10 )

but at some times the memory leak issue became FAST

### Environment

Zed: v0.139.0 (Zed Dev 29b5253a1d67dc4582f5713cfa06fc5416b07ab6)
OS: Windows 10.0.19045
Memory: 95.9 GiB
Architecture: x86_64

![image](https://github.com/zed-industries/zed/assets/54507071/21292054-1cf6-4662-bf22-6cd5449d5535)

![image](https://github.com/zed-industries/zed/assets/54507071/bfeaba80-1042-43b0-b0ae-6f24d4e21df9)

![image](https://github.com/zed-industries/zed/assets/54507071/f7e5fe97-12d0-4154-a169-0e9d9aadfd52)

**Comment by apricotbucket28** [comment]
> but after the commit [94c3101](https://github.com/zed-industries/zed/commit/94c3101fb0ecbaf5f322dd7b94c239f8a66a5a5f), the memory leak issue became FAST

That commit didn't change anything on Windows or macOS. It only affects Linux code.

If you want to help track down the memory leak, use a tool like the Visual Studio memory profiler and post the memory dump here.

**Comment by skejeton** [comment]
After a session of debugging and tracing, it seems like the issue is not in zed itself, but in blade_graphics implementation of the Vulkan backend. `reset_descriptor_pool` resets all the `sub_pools`, however, when we allocate a new descriptor via `alloate_descriptor_set`, it only uses the latest pool, it doesn't actually reuse the previous pools.

**Comment by skejeton** [comment]
I confirm the issue is in `blade_graphics` not zed. https://github.com/kvark/blade/issues/117

**Comment by shenjackyuanjie** [comment]
thanks for tests
my GPU are AMD RX580 8G

**Comment by shenjackyuanjie** [comment]
> I confirm the issue is in `blade_graphics`, and specifically, Intel HD graphics driver, not zed. [kvark/blade#117](https://github.com/kvark/blade/issues/117)

hmmmm, so there's the problem, my gpu are AMD RX580, so it's possible not just an intel only issue, or it's anther issue

**Comment by xgfone** [comment]
FYI
![screenshot-20240612-104247](https://github.com/zed-industries/zed/assets/2664392/e52ea41f-5e9c-402b-9da3-ef94e0143aaa)

**Comment by heksesang** [comment]
So the issue with Intel HD Graphics is solved in https://github.com/kvark/blade/commit/845cdadbfe78b07a3f2b53af105cb497263b9cc4, but the zed master branch is still on an older commit it seems.

**Comment by aramrw** [comment]
I am having the same problem.

`Zed.log` seems to be looping over a git error infinitely for as long as the program is running:
```
2024-07-06T12:05:50-07:00 [ERROR] Error 
{ code: -9, klass: 4, message: "reference 'refs/heads/master' not found" } x500
```
This is a git error, however the constant error loop is causing a memory leak if I open a project with no git open, zed doesn't leak memory.

#### Environment
`Zed`: v0.144.0
`OS`: Windows 11 Home 10.0.22631 Build 22631
`Memory`: 32 Gib
`Architecture`: x64-based PC
`Gpu`: Nvidia Rtx 4090
`Cpu`: Amd 7800x3d

**Comment by notpeter** [comment]
1. Is this still an issue?
2. I recall this could occur when `git init` had been run in a project directory, but there were not yet any git commits. Does this match your situation?
