### ISSUE TITLE
Offer Extension Filter

### ISSUE THREAD

**Issue by nerdalytics** [zed-industries/zed#12576]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to request a feature. It would be beneficial if Zed provided a filter when browsing extensions. Currently, Zed displays both themes and extensions together, making it difficult to distinguish between them. Currently, identifying whether an item is an extension or a theme requires the author to include the word "Extension" or "Theme" in the short description shown in the extensions list – which requires discipline, and yet consumes a lot of time scrolling through the ever growing list of extensions/themes.

**Comment by maxdeviant** [comment]
I think this is a dupe of #8848.

**Comment by nerdalytics** [comment]
Yeah it is. I was not browsing all issues the search has surfaced.
