### ISSUE TITLE
Can't change zed's window size on linux

### ISSUE THREAD

**Issue by a15355447898a** [zed-industries/zed#12574]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/62456287/fee83009-fd13-4718-98d5-b21f95db73a9

### Environment

I use archlinux kde6+wayland

![image](https://github.com/zed-industries/zed/assets/62456287/07cd2c84-f60a-41b9-b42a-ee63efbabb27)

**Comment by jansol** [comment]
This is known, client side decorations for resizing are not implemented yet.

As a workaround you can use ctrl+right mouse button drag or ctrl+middle mouse button drag (depending on your desktop environment) to invoke the resize function of the window manager.

**Comment by jansol** [comment]
Client side decorations for resizing have apparently been added in #13611

**Comment by mrnugget** [comment]
Pretty sure this is fixed on `main` now, especially with c8b106245 and 56e3fc794. Can you give latest `main` a shot?

**Comment by KraXen72** [comment]
i can resize if i go to right click > resize, however, there is immense lag when resizing. i am also using kde6+wayland. should i open another issue about it?
