### ISSUE TITLE
Python Syntax highlighting for variables, enum and modules

### ISSUE THREAD

**Issue by nigelmj** [zed-industries/zed#12578]
### Check for existing issues

- [X] Completed

### Describe the feature

Although variable highlighting for Python was introduced in the current release, it is only available in the case where one variable is defined per line. There are several areas where Python syntax highlighting can be improved in Zed:

- Function parameters: Highlighting of arguments passed to the function in both the parameters list and within the function body
- Multiple variable unpacking: Highlighting multiple variables defined in the same line or though unpacking assignments
- Reused variables: Ensuring that variables already defined are always highlighted when resused (at the moment they are only highlighted when first defined)
- Loop variables: Highlighting the loop variables would also be helpful
- Self parameter: This could be highlighted the with the same colour as the name of the class as it represents an instance of it
- Enum members: Currently they are highlighted as normal variables instead of what is specified under the enum property in the themes json file.
- Module names: Names could be highlighted the same way as the classes being imported are. Currently they have the foreground colour. However I am not sure if this requires creating a new property for themes.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1792" alt="Screenshot 2024-06-02 at 12 28 04" src="https://github.com/zed-industries/zed/assets/87859239/f601e51b-ca4e-4aa5-8144-a91c54beeb18">

**Comment by Nigel007** [comment]
@Angelk90 Yeah that makes sense. Here's the code:

```
import os
from enum import Enum

def sum(a, b):
    return a + b

m, n = (5, 5)

a = 1
a += 1

for index in range(5):
    print(index)

class Test:
    def __init__(self):
        self.a = 1
        self.b = 2

class A(Enum):
    a = 1
    b = 2
    c = 3

a_dict = {A.a: 1, A.b: 2, A.c: 3}

a_list = [1, 2, 3, 4, 5]
print(a_list[0])
print(a_list[-1])

```

**Comment by Nigel007** [comment]
@Angelk90 I think you've set the variable colour as white and the foreground as a off-white? If you notice, only variables that are defined for the first time have the bright white colour. All other variables, be it function parameters, reused variables (line 10: `a+=1`) or mutliple varialbes (line 7: `m, n = (5, 5)`), are off-white. I think the values inside a_dict are coloured according to the `attribute` property, which is why they show up as blue.

**Comment by Nigel007** [comment]
@Angelk90 Oh apologies! I should have also uploaded an image of how it appears for me.

<img width="1792" alt="Screenshot 2024-06-02 at 13 08 05" src="https://github.com/zed-industries/zed/assets/87859239/ec31751b-d005-4b78-81a9-8e0f40a9730b">

I have my variable and attribute colours set to a reddish tone. My foreground colour is white.

**Comment by Nigel007** [comment]
I have added highlighting to all variables and set the self reference in classes to the variable.special property. Modules are highlighted in the import statements, however, they are highlighted as variables when used in the code. I assume this is because the parser is not context aware.

Further, all imports, be it classes, functions, etc are highlighted with the type property. This is non ideal as it would make more sense for different symbols to be highlighted differently. I am looking into possible solutions for this.

**Comment by Nigel007** [comment]
The issues that are still existing seem to be related to semantic highlighting because they require context awareness. That would be beyond the scope of this issue as semantic highlighting pertains to all languages.

**Comment by notmd** [comment]
it seems to happen to Rust as well as many other languages, Zed doesn't highlight `identifier` as `@variable`.

**Comment by Nigel007** [comment]
@notmd Thank you for pointing it out. At first I was a bit skeptical about using the `identifier` node for the `@variable` property as it was too broad and would give all nodes the same colour. This was why I placed it on the first line before any other highlighting rule, and I also thought there was no other way to highlight variables without individually specifying all cases where they would be used (assignment, augmentation, indexing, for loops, and other statements).

After a little trial and error, which mainly involved coming up with custom rules for each case, I discovered that the `parameter` node considers all variables and not just function parameters. This seemed like an appropriate fix to highlight the variables, so I've modified the first line in the file to set that token to the `@variable` property.

**Comment by JosephTLyons** [comment]
Closed via: https://github.com/zed-industries/zed/pull/12868

**Comment by ihoey** [comment]
@nigelmj  Hello, what is the theme of this screenshot?

**Comment by nigelmj** [comment]
@ihoey This is a custom theme based on the [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) theme for VS Code.

**Comment by xqsit94** [comment]
@ihoey, you might want to try this [Vivid Theme](https://github.com/xqsit94/zed-one-dark-vivid). It is quite similar to the one above but with a hint of the JetBrains dark theme. Just copy the themes folder to `~/.config/zed/`

![CleanShot 2024-07-10 at 12 26 40@2x](https://github.com/zed-industries/zed/assets/20275754/934d1104-441f-4b3d-b595-2c505671beaa)
