### ISSUE TITLE
Toggle Replace `cmd-alt-f` key binding not working on macOS

### ISSUE THREAD

**Issue by gabrielkoerich** [zed-industries/zed#12583]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using Zed with `vim_mode=true` and custom key bindings for search/replace. I added `"alt-cmd-f": "search::ToggleReplace"` in some contexts and it shows on the editor that this should be the correct key binding for toggling replace:
![Screenshot 2024-06-02 at 10 53 21](https://github.com/zed-industries/zed/assets/1981726/3fd96b88-cd37-4dbd-8eeb-0d5b4a5ed7fa)

But I can't make it work, I always have to do first a `cmd-f` to search and then toggle the replace manually. First I was using the SublimeText base keymap, but I remove it and added just some custom key bindings. Am I doing something wrong here? Thanks!

### Environment

Zed: v0.137.6 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

My current key bindings:

```
[
  {
    "bindings": {
      "cmd-shift-[": "pane::ActivatePrevItem",
      "cmd-shift-]": "pane::ActivateNextItem",
      "ctrl-pagedown": "pane::ActivatePrevItem",
      "ctrl-pageup": "pane::ActivateNextItem",
      "ctrl-shift-tab": "pane::ActivateNextItem",
      "ctrl-tab": "pane::ActivatePrevItem",
      "cmd-+": "zed::IncreaseBufferFontSize",
      // "ctrl-c left": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-a |": "pane::SplitRight",
      "ctrl-a _": "pane::SplitDown"
    }
  },
  {
    "context": "ProjectSearchBar",
    "bindings": {
      "escape": "project_search::ToggleFocus",
      "cmd-f": "search::FocusSearch",
      "cmd-alt-f": "search::ToggleReplace"
    }
  },
  {
    "context": "ProjectSearchView",
    "bindings": {
      "escape": "project_search::ToggleFocus",
      "cmd-alt-f": "search::ToggleReplace"
    }
  },
  {
    "context": "Pane",
    "bindings": {
      "f4": "search::SelectNextMatch",
      "shift-f4": "search::SelectPrevMatch",
      "cmd-alt-f": "search::ToggleReplace",
      "alt-cmd-f": "search::ToggleReplace"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "ctrl-shift-up": "editor::AddSelectionAbove",
      "ctrl-shift-down": "editor::AddSelectionBelow",
      "cmd-shift-space": "editor::SelectAll",
      "ctrl-shift-m": "editor::SelectLargerSyntaxNode",
      "cmd-shift-l": "editor::SplitSelectionIntoLines",
      "cmd-shift-a": "editor::SelectLargerSyntaxNode",
      "shift-f12": "editor::FindAllReferences",
      "alt-cmd-down": "editor::GoToDefinition",
      "ctrl-alt-cmd-down": "editor::GoToDefinitionSplit",
      "alt-shift-cmd-down": "editor::FindAllReferences",
      "ctrl-.": "editor::GoToHunk",
      "ctrl-,": "editor::GoToPrevHunk",
      "ctrl-backspace": "editor::DeleteToPreviousWordStart",
      "ctrl-delete": "editor::DeleteToNextWordEnd"
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-r": "outline::Toggle"
    }
  },
  {
    "context": "Workspace",
    "bindings": {
      "cmd-k cmd-b": "workspace::ToggleLeftDock",
      "cmd-t": "file_finder::Toggle",
      "cmd-r": "outline::Toggle",
      // "shift-cmd-r": "project_symbols::Toggle",
      // Currently busted: https://github.com/zed-industries/feedback/issues/898
      "ctrl-0": "project_panel::ToggleFocus",
      "cmd-shift-r": "workspace::ToggleRightDock",
      "cmd-f": "pane::DeploySearch",
      "cmd-alt-f": [
        "pane::DeploySearch",
        {
          "replace_enabled": true
        }
      ]
    }
  }
]

```

**Comment by gabrielkoerich** [comment]
If I remove `"cmd-alt-f": "search::ToggleReplace"` on Pane context, the key binding is back to the default `cmd-shift-h` which works when pressing it. But `cmd-alt-f` doesn't work, maybe some kind of conflict?

**Comment by JosephTLyons** [comment]
These seem like bugs - I'm experiencing the same issues on my end.

**Comment by notpeter** [comment]
Bump @gabrielkoerich.

Curious whether you're still running into this and whether the work around I suggested had any impact.

**Comment by gabrielkoerich** [comment]
@notpeter I doesn't work either :/ I had already tried this, if you look in my keymaps I have both: `cmd-alt-f` and `alt-cmd-f`. Tried again with just one of them but no success. This search/replace is still annoying to do only using the keyboard, I guess I need to learn to just do it using vim mode

**Comment by skatromb** [comment]
Not sure if it's worth creating another issue. But I have an issue with `cmd-shift-delete` hotkey for the `editor::DeleteLine` action: it's just now working.
```
{
    "context": "Editor",
    "bindings": {
      "cmd-shift-delete": "editor::DeleteLine"
}
```

Should I just subscribe to this issue and wait, or better making another?

**Comment by notpeter** [comment]
I took a look at this again and realized I incorrect had `project_search::ToggleFilters` specified instead of `search::ToggleReplace`.

@gabrielkoerich When I use the following in my `keymap.json` it works as 
I would expect:
```json
[
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-alt-f": ["buffer_search::Deploy", { "replace_enabled": true }]
    }
  },
  {
    "context": "BufferSearchBar",
    "bindings": {
      "cmd-alt-f": "search::ToggleReplace"
    }
  },
  {
    "context": "Pane",
    "bindings": {
      "alt-cmd-f": "search::ToggleReplace"
    }
  }
]
```

- In a buffer, `cmd-alt-f` deploys the buffer search bar with the replace part enabled. 
- In a buffer search panel, `cmd-alt-f` toggles the replace part.
- In a global search panel (triggered with `cmd-shift-f`), `cmd-alt-f` toggles the replace part.

@gabrielkoerich  Let me know if this is still broken for you, and if so, what parts.

---

@skatromb You should open a new issue, but I'd bet you an ice cream cone it'll work with:
```
  {
    "context": "Editor",
    "bindings": {
      "cmd-shift-backspace": "editor::DeleteLine"
    }
  }
```
It's a little confusing, but generally zed adopts the universal name for keys (e.g. `alt` over `option`, `backspace` over `delete`, `delete` over `delete forward`) to try and keep things simpler across platforms.

**Comment by skatromb** [comment]
Ah, @notpeter you're completely right! Thank you very much. I just found first in default keymap that there are `delete` key, and thought it's the same with Mac `delete` button. But turns out that Mac's `delete` button is `backspace` in zed's config.

Anyway, now it works ❤️

**Comment by gabrielkoerich** [comment]
> I took a look at this again and realized I incorrect had `project_search::ToggleFilters` specified instead of `search::ToggleReplace`.
> 
> [@gabrielkoerich](https://github.com/gabrielkoerich) When I use the following in my `keymap.json` it works as I would expect:
> 
> [
>   {
>     "context": "Editor && mode == full",
>     "bindings": {
>       "cmd-alt-f": ["buffer_search::Deploy", { "replace_enabled": true }]
>     }
>   },
>   {
>     "context": "BufferSearchBar",
>     "bindings": {
>       "cmd-alt-f": "search::ToggleReplace"
>     }
>   },
>   {
>     "context": "Pane",
>     "bindings": {
>       "alt-cmd-f": "search::ToggleReplace"
>     }
>   }
> ]
> * In a buffer, `cmd-alt-f` deploys the buffer search bar with the replace part enabled.
> * In a buffer search panel, `cmd-alt-f` toggles the replace part.
> * In a global search panel (triggered with `cmd-shift-f`), `cmd-alt-f` toggles the replace part.
> 
> [@gabrielkoerich](https://github.com/gabrielkoerich) Let me know if this is still broken for you, and if so, what parts.
> 
> [@skatromb](https://github.com/skatromb) You should open a new issue, but I'd bet you an ice cream cone it'll work with:
> 
> ```
>   {
>     "context": "Editor",
>     "bindings": {
>       "cmd-shift-backspace": "editor::DeleteLine"
>     }
>   }
> ```
> 
> It's a little confusing, but generally zed adopts the universal name for keys (e.g. `alt` over `option`, `backspace` over `delete`, `delete` over `delete forward`) to try and keep things simpler across platforms.

yeah I tried all those and didn't work, so I gave up. I'm just using  the default `shift+cmd+h` or vim mode search/replace
