### ISSUE TITLE
Allow to build Zed without auto_update feature

### ISSUE THREAD

**Issue by jirutka** [zed-industries/zed#12588]
### Check for existing issues

- [X] Completed

### Describe the feature

If Zed is installed using a package manager, the auto_update feature is undesirable – the updates are handled by the package manager. Can you please put it behind feature gate so that distros can build Zed without the auto_update feature and its dependencies?

Related issues: #11114

**Comment by Moshyfawn** [comment]
You can disable this feature by specifying
```json
"auto_update": false
```
in your `settings.json`.

**Comment by JosephTLyons** [comment]
I see that a PR has been opened for this already, but just wanted to mention that you can disable this locally via your `settings.json` file with:

`"auto_update": true`

I realize that isn't as desirable, but its a workaround in the meanwhile.

**Comment by someone13574** [comment]
> I see that a PR has been opened for this already, but just wanted to mention that you can disable this locally via your `settings.json` file with:
> 
> `"auto_update": true`
> 
> I realize that isn't as desirable, but it is a workaround in the meanwhile.

The idea is that there should be an option to override this setting for installations done through package managers so that there aren't cases where a user enables it and then the package gets broken in one of the numerous ways it could be (eg. non-glibc systems, shared dep mismatches, etc.).
