### ISSUE TITLE
Edit Task not work

### ISSUE THREAD

**Issue by sunliang711** [zed-industries/zed#12580]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello, I found a bug, when I press shift+option+T to call out task menu, the default hot key for "Edit Task" (option +E ) not work, am i missing something ?
<img width="334" alt="image" src="https://github.com/zed-industries/zed/assets/16303258/b907f5b6-8cb4-410a-a064-b98918c4237e">

### Environment

Zed: v0.138.3 (Zed Preview)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by RemcoSmitsDev** [comment]
You are not missing anything, the shortcut does not work properly. See the following video:

https://github.com/zed-industries/zed/assets/62463826/a1f16668-0333-41f7-9c54-6fcd3c72e7e3

**Comment by SomeoneToIgnore** [comment]
While the reason is a bit different, https://github.com/zed-industries/zed/issues/12503#issuecomment-2141310376 is related to the "does not work" case, cc @osiewicz
