### ISSUE TITLE
Register `.inl` files as C++ files.

### ISSUE THREAD

**Issue by skejeton** [zed-industries/zed#12605]
### Check for existing issues

- [X] Completed

### Describe the feature

`.inl` files are used to split multiple translation units into separate files, they are also not compiled as separate translation units by build system, which makes them good for joining into a single translation units.

**Comment by jandrej** [comment]
You can simply add this to your configuration
```json
  "file_types": {
    "C++": ["inl"]
  }
```

**Comment by JosephTLyons** [comment]
This actually seems like a thing we'd reasonably just toss in.

**Comment by dhairyanadapara** [comment]
Hey @JosephTLyons, I'd like to work on this issue. From what I understand, files with the `.inl` suffix should be treated as `cpp` files. This means the default language and syntax highlighting should be set to `cpp`.

After reviewing the code, it seems the solution involves modifying the `crates\languages\src\cpp\config.toml` file.

Specifically, adding `inl` to the list of path suffixes:
```cpp
path_suffixes = ["cc", "hh", "cpp", "h", "hpp", "cxx", "hxx", "c++", "ipp", "inl"]
```

**Comment by dhairyanadapara** [comment]
Hello @JosephTLyons, I have submitted a pull request with the changes we discussed. Please review it when you can.

**Comment by skejeton** [comment]
@dhairyanadapara thank you.
