### ISSUE TITLE
Provide a prebuilt aarch64-linux build

### ISSUE THREAD

**Issue by ConradIrwin** [zed-industries/zed#12608]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently we only build linux for x86-64. From the early remoting users, it seems like about 5% would like to use zed on an aarch machine; so it'd be nice to set up a builder so that `curl https://zed.dev/install.sh | bash` works for them.

**Comment by jvoisin** [comment]
![image](https://github.com/zed-industries/zed/assets/325724/5292b8ee-4619-43c7-9098-8fa8326ec596)

Weehee!
