### ISSUE TITLE
Use Too Many Memory

### ISSUE THREAD

**Issue by xgfone** [zed-industries/zed#12626]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Use too many memory, and not release.

### Environment

- OS: Windows11 23H2
- Rust:  1.78.0 (9b00956e5 2024-04-29)
- Zed: 
  - Commit: dc141d0f6182773b1281b019c28bcd97413102f0
  - Datet: Thu May 30 18:27:03 2024 -0400

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![screenshot-20240604-142210](https://github.com/zed-industries/zed/assets/2664392/6e3891c9-498b-4f8a-b606-129faf9aa3cd)
![screenshot-20240604-142254](https://github.com/zed-industries/zed/assets/2664392/68102a99-f816-4999-be63-8ce26a4833f8)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/user-attachments/files/15543443/Zed.log)

**Comment by SomeoneToIgnore** [comment]
Most probably a duplicate of https://github.com/zed-industries/zed/issues/12561

**Comment by xgfone** [comment]
@SomeoneToIgnore Fine, tks. FYI
