### ISSUE TITLE
C language selection is ignored when in header files

### ISSUE THREAD

**Issue by matthewsanetra** [zed-industries/zed#12634]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

clangd is not informed of the language currently selected in the editor.

This means that in header files, clangd assumes C++.

A workaround I currently use is to just use CMake and export a compile_commands.json into the project root. This passes the info that we're compiling C to clangd so it works, but I believe the editor shouldn't require us to use CMake to code in C comfortably.

### Environment

Zed: v0.137.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

C language is selected:
<img width="345" alt="Screenshot of the bottom right of the Zed editor highlighting that the current selected language is C" src="https://github.com/zed-industries/zed/assets/41018997/367b4362-317c-4ceb-b068-67861bbc4798">

Error in a header file:
<img width="345" alt="Screenshot of a snippet of code with a red underlining of bool in a typedef" src="https://github.com/zed-industries/zed/assets/41018997/55ea96e5-4368-4c0c-83f1-3a9c6e1c7995">

<img width="375" alt="Screenshot of the bottom left of the Zed editor showing an error that bool is redeclaring a C++ built-in type" src="https://github.com/zed-industries/zed/assets/41018997/55b1929e-f66a-4af6-bb7a-cd10b19e09d3">

**Comment by chakkawat-sonaruea** [comment]
I am not expert in clangd. But doesn't clangd always see files as C++.

I think change language in the editor is doesn't changing the fact that both C and C++ in Zed are using clangd, so clangd would show diagnostic according to clangd config.

As for way to configure clangd. One of the recommended way to config clangd that doesn't involve CMake is to use `.clangd`.
I suggest you take a look at clangd's configuration page.
[https://clangd.llvm.org/config](https://clangd.llvm.org/config)

**Comment by SomeoneToIgnore** [comment]
> I am not expert in clangd. But doesn't clangd always see files as C++.

It seems so, but there's a way to configure it differently, mentioned in 

https://github.com/zed-industries/zed/issues/14411#issuecomment-2227324916

**Comment by notpeter** [comment]
I've added a note to the [C Language Docs](https://zed.dev/docs/languages/c/) about how to add a `.clangd` which forces clangd to operate in C-only mode for a given project.

```yaml
CompileFlags:
  Add: [-xc]
```

I do not believe it is currently possible to hint to `clangd` that a single header file should be considered C in an LSP context.  If you have a mixed C/C++ project you could configure `.clangd` to handle `.h` as C and have all your C++ headers with the `.hpp` extension using:

```yaml
CompileFlags:
  Add: [-xc]
If:
  PathMatch: .*\.h
```

Thanks for reporting!
