### ISSUE TITLE
Make popover text selectable

### ISSUE THREAD

**Issue by msanft** [zed-industries/zed#12638]
### Check for existing issues

- [X] Completed

### Describe the feature

Related to #5698, which is marked as a duplicate of a now dead link to another issue.

It would be great if the text in the popover hints would be selectable. Juding by the age of the linked issue, this might be something that doesn't work on Linux only too. Unfortunately, I don't have a MacOS machine at hand currently to verify whether it works there.

**Comment by effdotsh** [comment]
I'll take a crack at this tomorrow

**Comment by effdotsh** [comment]
I'll take a closer look at this tomorrow, I have a basic test written with copy on click and it's already much nicer to use

**Comment by JosephTLyons** [comment]
Hey @msanft would you mind upvoting this issue via a 👍:

- https://github.com/zed-industries/zed/issues/5236

I'll close this one out as a duplicate!
