### ISSUE TITLE
Git hunk displayed when clicking split view scrollbar

### ISSUE THREAD

**Issue by jandrej** [zed-industries/zed#12644]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When having a split left/right window setup and clicking on the scrollbar next to a change a git diff hunk is popping up unwillingly.

My git related settings
```json
  "scrollbar": {
    "git_diff": false
  },
  "git": {
    "git_gutter": "hide",
    "inline_blame": {
      "enabled": false
    }
  },
```

### Environment

Zed: v0.137.6 (Zed)
OS: macOS 13.6.7
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/5412886/0ba37b7b-8c6a-47a5-98fc-20d1e0a2d06b

**Comment by JosephTLyons** [comment]
Are we ok to close this issue out, @bennetbo?

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/12671 will close it formally, albeit the functional fix was already done in https://github.com/zed-industries/zed/pull/12425

**Comment by jandrej** [comment]
Did the fix hit the stable release today? I still encounter the same issue after the update.

**Comment by SomeoneToIgnore** [comment]
Could you check the preview?

**Comment by jandrej** [comment]
Yea I think it's fixed in the preview.
