### ISSUE TITLE
Increasing/decreasing indent size with `cmd-}` or `cmd-{` shortcut will flicker code

### ISSUE THREAD

**Issue by RemcoSmitsDev** [zed-industries/zed#12679]
### Check for existing issues

- [X] Completed

### Issue
I noticed that when you increase the indent size with the `cmd-}` shortcut, this will flicker the code in that row at some point. Could not really find the underling issue, but it seems to have something to do with the code that is hitting the hit box of the scrollbar/end of the editor.

**Note**: This issue is not bound to a specific language, or typo of file.

---

### Steps to reproduce
1. Open a file (E.g. editor.rs)
2. Place the cursor at a line that contains some code
3. Hold `cmd-}` shortcut until you see the flickering, when you are at that point you can also reproduce the way back if you keep holding the `cmd-{` shortcut

https://github.com/zed-industries/zed/assets/62463826/3f8c24d8-3c47-48df-bada-94b71c40bc89

### Environment

Zed: v0.139.0 (Zed Dev ab8d25e0a2454e7aa1503d52319633dbd548e08f)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I am no longer able to reproduce this on a current version of Zed on Mac.
If you are still seeing this, feel free to comment and I'm happy to reopen.
Thanks for reporting.
