### ISSUE TITLE
Joining a collab session pins one CPU core to 100%

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#12675]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I join (someone else's) collab session to hack on Zed itself, my laptop sounds like it's about to take off and Acitvity monitor says Zed is using some 120% of CPU time. I didn't quite figure out why, though. My initial guess was that it's decoding screen share video on the CPU rather than with a hardware decoder, but it also happens when simply following someone through code files in editor views.

A quick sample taken with Activity Monitor points towards GPUI with a symbol named roughly "draw as root element" taking a lot of time. Is it rendering at excessively high framerates? I don't think the screen on this laptop does more than 60Hz to begin with.

### Environment

Zed: v0.138.1 (Zed Preview)
OS: macOS 12.7.5
Model: MacBook Pro (15-inch, 2016)
Processor: 2,6 GHz Quad-Core Intel Core i7
Memory: 16 GiB
Architecture: x86_64

**Comment by ConradIrwin** [comment]
@jansol This is not great!

I know we have some problems with LiveKit on old Mac versions (but I thought they just resulted in a crash not CPU usage). This does sound like you suspect though.

Would you be able to send the sample to me (conrad@zed.dev) please?

If you have a debug build running locally, does it exhibit the same issue? If so we can try attaching Instruments to it and see if we can get any more information.

If you want to pair on debugging this, feel free to book some time: https://calendly.com/conradirwin/pairing (though maybe we should choose a different software to collaborate with :D)

**Comment by jansol** [comment]
I didn't think to save the sample, but I can do a debug build and do a proper profiling session. I'm not very familiar with Instruments though - is there some specific preset/view you want from there?

**Comment by ConradIrwin** [comment]
@jansol For now just the CPU profile preset would be great. It's usually pretty high resolution so I'm hoping we can see what might be causing the problem for you.

**Comment by notpeter** [comment]
I'm going to go ahead and close. 
If you are experiencing this and capture a trace, feel free to open a clean issue.
Thanks for reporting.

**Comment by jansol** [comment]
We managed to get a trace and it was pointing to a lot of time being spent recomputing the UI layout at full refresh rate whenever there was a video stream, even if it was not being shown on screen. Conrad did look into it for abit but I don't know if anything ever came of that.
