### ISSUE TITLE
Linux: Middle mouse button paste does not work in editor

### ISSUE THREAD

**Issue by paradoxxxzero** [zed-industries/zed#12691]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This commit https://github.com/zed-industries/zed/commit/b31df39ab0b741b5d7aa613e29a8d3768c647ef5 adds the primary selection functionality but the middle click paste only works in terminal, it should work everywhere (editor, search, palette, ...)

This issue #11786 requests the middle button behavior to be configurable but on Linux it should be pasting the primary selection buffer by default.

### Environment

Zed: v0.138.4 (Zed Preview)
OS: Linux 1.0.0
Memory: 14.9 GiB
Architecture: x86_64

**Comment by apricotbucket28** [comment]
> This commit [b31df39](https://github.com/zed-industries/zed/commit/b31df39ab0b741b5d7aa613e29a8d3768c647ef5) adds the primary selection functionality but the middle click paste only works in terminal, it should work everywhere (editor, search, palette, ...)
> 
> This issue #11786 requests the middle button behavior to be configurable but on Linux it should be pasting the primary selection buffer by default.

Middle click paste used to work in the editor but it was regressed in https://github.com/zed-industries/zed/commit/410c46a5517e397890580c21dab13575e7839d5a

**Comment by paradoxxxzero** [comment]
> Middle click paste used to work in the editor but it was regressed in [410c46a](https://github.com/zed-industries/zed/commit/410c46a5517e397890580c21dab13575e7839d5a)

Nice find, this seems like something that would pair well with a modifier.

Indeed, multi cursor selection seems to be mapped on alt + click in vscode (on linux at least) which IMO makes more sense.

**Comment by paradoxxxzero** [comment]
Just tested Zed Preview 0.141.0, seems to be fixed :pray: 

Thanks

**Comment by mohammadrafigh** [comment]
Is there an option to disable it?

**Comment by Bass-03** [comment]
I also want to disable it.

**Comment by gengns** [comment]
Just tested Zed Stable 0.153.7 
Not working.

**Comment by Bass-03** [comment]
I have been using zed preview, it does work. 
For who finds it hard to find the option, this is my config:

```
{
# whatever configs you have, 
"middle_click_paste": false
}
```

**Comment by gengns** [comment]
Even after explicitly adding the option to the config, it doesn't work.
`"middle_click_paste": true`

**Comment by mohammadrafigh** [comment]
> I have been using zed preview, it does work. For who finds it hard to find the option, this is my config:
> 
> ```
> {
> # whatever configs you have, 
> "middle_click_paste": false
> }
> ```

Thank you, it works.

**Comment by kamoshi** [comment]
Doesn't work for me

```
Zed: v0.153.7 (Zed)
OS: Linux Wayland arch unknown
Memory: 14.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.3-arch1.1
```

**Comment by Bass-03** [comment]
> Doesn't work for me
> 
> ```
> Zed: v0.153.7 (Zed)
> OS: Linux Wayland arch unknown
> Memory: 14.5 GiB
> Architecture: x86_64
> GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.3-arch1.1
> ```

Maybe it is only live on preview

**Comment by Bass-03** [comment]
I found the same thing actually.
A few preview versions before I did have to set it to false, now it seems it is disabled always.
