### ISSUE TITLE
CLI binary name clashes with mono-runtime

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#12705]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://manpages.debian.org/bullseye/mono-runtime/cli.1.en.html

### Environment

Linux, details N/A

**Comment by ConradIrwin** [comment]
Unfortunately the package names were chosen to make sense for the Mac build; and they don't make so much sense for linux.

There's some notes here about how to sort it out: https://zed.dev/docs/development/linux#notes-for-packaging-zed

It sounds like you're keen to run your own development build of zed locally. Would it be helpful to you if we had something like `./script/install-linux` that does ./script/bundle-linux + ./script/install.sh? (kind of like `make install` would do)

**Comment by jansol** [comment]
Ah my bad, somehow glossed over the part where it got renamed to `zed`.... which still collides with [at least](https://authzed.com/) [3 other](https://zed.brimdata.io/) [tools](https://zfsonlinux.org/manpages/0.8.4/man8/zed.8.html), but I guess users/packagers will just have to live with that. Ubuntu already renames `fd` to `fdfind` for example so there is a precedent as well.

**Comment by ConradIrwin** [comment]
Yeah. The other place this came up suggested `zeditor` as a good alternative. I'll add that to the docs to try and unify on only having two standard names :D

**Comment by jansol** [comment]
> Would it be helpful to you if we had something like ./script/install-linux that does ./script/bundle-linux + ./script/install.sh? (kind of like make install would do)

Some kind `PREFIX=~/.local make install` equivalent would indeed be convenient (without bit where it copies dependency libraries, since those would have to be installed for the build to pass anyway)
