### ISSUE TITLE
Supermaven does not work

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#12715]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I used supermaven for the last couple days before I switched to Copilot in this recent week. But when I switch back Supermaven today, it stops working and no completions is provided.

<img width="210" alt="image" src="https://github.com/zed-industries/zed/assets/5475262/1d0fea77-e314-4532-a6ce-06101b05f73d">

Not sure if there is an authentication issue and can not find a way to re-login. 

Any help will be appreciated, thanks!

See https://github.com/zed-industries/zed/discussions/12412 in discussions.

### Environment

Zed: v0.139.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: x86_64

**Comment by failable** [comment]
Still unusable. Even I run `supermaven: sign out`, I still get this message. 

<img width="174" alt="image" src="https://github.com/user-attachments/assets/93e3f774-bccd-4acf-9303-35d1a064ec03">

Restarting Zed also does not work.

```
Zed: v0.146.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: x86_64
```

**Comment by alper** [comment]
I don't even see the Maven icon picked up in the bottom.

**Comment by mikededo** [comment]
Hey @JosephTLyons, I'm running Zed `0.146.3` and when hovering the Supermaven icon I still get the `Supermaven initializing`, and no suggestions/autocompletions appear. Is the issue actually fixed?
