### ISSUE TITLE
Add setting to hide tasks in gutter

### ISSUE THREAD

**Issue by mkdynamic** [zed-industries/zed#12713]
Add a setting to hide the Tasks in the gutter:

<img width="505" alt="Screenshot 2024-06-05 at 8 02 14 PM" src="https://github.com/zed-industries/zed/assets/4312/fb6ab299-9dd7-45af-a28f-e67e692f5a7f">

**Comment by mkdynamic** [comment]
Oops, I realize those are not "Code Actions" :) Updated the issue accordingly. I cannot update the labels.

**Comment by osiewicz** [comment]
Hey, this was fixed in https://github.com/zed-industries/zed/pull/13329. I'm gonna close this issue out. Feel free to reopen if you run into any issues.
