### ISSUE TITLE
Can't write ` character on macOS (alt-\ on Italian keyboard)

### ISSUE THREAD

**Issue by ilTofa** [zed-industries/zed#12726]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Up until yesterday, the key combination alt-\ generated the character ` (on an Italian keyboard). Now nothing happens.
I have no changed the default keybinding, I suspect this is related to #12708 but the existing bug is an "enhancement" type of bug, while not be able to use ` is definitely critical (for not-us people using a national keyboard, at least).
To reproduce: 
set an Italian (probably also with other European keyboards) keyboard; 
press alt-\;
Expected:
`
Actual Result:
Nothing

### Environment

Zed: v0.138.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

N/A, but it's easily reproducible

**Comment by jansol** [comment]
If you don't mind building Zed from sources you could try if it works now that #12702 is merged. (If you don't want to do your own builds, the changes should be in 0.140.0)

**Comment by ilTofa** [comment]
I was not able to compile zed (same machine). I'm using MacPorts (and not HomeBrew) and I got an undefined symbol at link time for iconv (and some related libraries). 
I probably hit the problem described on this [stackoverflow](https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx) answer, but I can't deactivate port iconv easily (it seems almost anything depends on it).
Should I file a bug for it, or using macports iconv is considered an unsupported configuration?
Thank you very much for the quick turnaround, in any case! You guys rock!

**Comment by ilTofa** [comment]
Uh, sorry. I was able to compile and run zed 0.140.0 (377e24b798a9b99237a53de26489be46ba519545) by using rust from macports (without using rustup) and compiling in debug mode.
Unfortunately the problem is still present in this revision

**Comment by ilTofa** [comment]
It's fixed on version 0.141.3. Thank you!

**Comment by destegabry** [comment]
Hi @ilTofa I'm using an Italian Apple Keyboard and I'm not able to write the backtick character with `alt+\`.

I'm on zed 0.147.2, is it working for you?

**Comment by destegabry** [comment]
It seems the only way to make it work is disabling a default key binding as noted in https://github.com/zed-industries/zed/discussions/10508#discussioncomment-9114720:

```
[{
  // Workaround to let italian keyboards write backticks
  "context": "Editor && !inline_completion",
  "bindings": {
    "alt-\\": null
  }
}]
```

**Comment by ilTofa** [comment]
Uh, you're right @destegabry , it stopped working again (it used to work on 0.141.3, and also later versions). 
Your workaround works, btw. Thank you!
