### ISSUE TITLE
Unable to drag a file from the panel area to editor area in new 0.138.4 stable version

### ISSUE THREAD

**Issue by isunjn** [zed-industries/zed#12733]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In new 0.138.4 version it's unable to drag a file from the project panel area and drop it into the editor area to open it.

In previous version (0.137.6) there is no such problem.

### Environment

Zed: v0.138.4 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: x86_64

**Comment by xcrap** [comment]
Same here, I was doing this now to open a split view and while dragging I had the text cursor.
I use this everyday so it was really from Zed 0.138.4 update.

**Comment by osiewicz** [comment]
The hotfix for both Stable and Preview is on it's way. ETA: 30 minutes or so.

**Comment by osiewicz** [comment]
The fix should be available now. Let me know if you still experience this issue.
