### ISSUE TITLE
Remote Development: Zed Starts in Headless Mode but Client Doesn't Connect

### ISSUE THREAD

**Issue by aayork** [zed-industries/zed#12738]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am logging into a remote machine using `ssh -p <port> user@11.11.11.11`

Zed is starting in headless mode, but the client is stuck waiting for a connection. This occurs on both default and manual connection modes.

![Screenshot  06-06-2024 at 10 37 39AM](https://github.com/zed-industries/zed/assets/113198662/1bbe2866-edad-433c-bb38-b0e7fdfba4cd)

### Environment

Zed: v0.139.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@aayork Thanks for trying this out!

Could you please send me the logs of your remote zed? (They should be in `cat ~/.local/share/zed/logs/Zed.log` and/or `cat ~/.local/share/zed/logs/Zed.log.old`).

When you run in manual mode, do you get any output from the zed daemon? (You can also try with `~/.local/bin/zed --foreground --dev-server-token XXX`)

**Comment by bennetbo** [comment]
We changed the way how remote development works significantly (https://zed.dev/docs/remote-development), so this should be fixed. If you can still reproduce this with the latest preview version feel free to re-open.
