### ISSUE TITLE
[Windows?] Ui font clipping top/bottom

### ISSUE THREAD

**Issue by MolotovCherry** [zed-industries/zed#12737]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Ui font size 14 is not cut, size 15 is. Unknown if this is Windows related or not, but it might be Windows specific

Don't know if this is related either, but my resolution is 3840x2160 @ 200% scale
```json
{
  "buffer_font_size": 11,
  "buffer_font_family": "FiraCode NF",
  "ui_font_size": 14, // <-- change to 15
}
```
14 ✅ 

![image](https://github.com/zed-industries/zed/assets/13651622/b00a5a77-1162-4f83-b3a7-08094fd70969)

15 🚫 Notice the subtle clipping on the top and bottom

![image](https://github.com/zed-industries/zed/assets/13651622/76df5e7a-a31d-426d-9ce9-323d34bde9d4)

![image](https://github.com/zed-industries/zed/assets/13651622/bbb54f83-4c0e-4191-8a8a-c3401a8c99eb)

### Environment

Zed: v0.140.0 (Zed Dev a574036efd13c0ae66ef3d0e57054e798fa1124e)
OS: Windows 10.0.22631
Memory: 63.8 GiB
Architecture: x86_64

**Comment by JunkuiZhang** [comment]
#13854 may fix this issue. If not, please let me know.

**Comment by MolotovCherry** [comment]
> #13854 may fix this issue. If not, please let me know.

I compiled and tested out your branch on my machine. I cannot reproduce the issue afterwards!

**Comment by Moshyfawn** [comment]
I'll close this issue as resolved. Thanks for the confirmation. Feel free to reopen it if the problem persists.

**Comment by JunkuiZhang** [comment]
@MolotovCherry That's great :)
