### ISSUE TITLE
Unable to edit Assistant prompts while `vim_mode` is `true`

### ISSUE THREAD

**Issue by Thomascountz** [zed-industries/zed#12732]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As the title says, I was unable to use the Assistant UI for managing system prompts, and it turns out, it was cause by having vim mode enabled.

With `vim_mode` set to `true`

```js
// ~/.config/zed/settings.json
{
  "vim_mode": true
}
```

I open the Assistant Panel and click the "Prompt Library..." button.
There, I cannot edit or update text within the central pane text area.
The cursor showing within the text area does  not respond to vim commands (e.g. `i` to go to insert mode, or `jkhl` for movement).
This is true for new "Untitled" prompts, as well as for existing prompts.
Once I disable `vim_mode`, the prompt UI works as expected using non-vim controls.

### Environment

Zed: v0.139.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/19786848/d5990c8c-f9a5-4ab8-9309-0dc3d9a439c7

**Comment by Thomascountz** [comment]
Similar to the issue addressed in #12701, I think the new window isn't being initialized correctly.

**Comment by ConradIrwin** [comment]
Fixed (by disabling vim mode in this editor) by #13028
