### ISSUE TITLE
Microphone and Speaker in Chat

### ISSUE THREAD

**Issue by HtetAungKhant23** [zed-industries/zed#12761]
### Check for existing issues

- [ ] Completed

### Describe the feature

When I join a chat, the microphone and speaker are already on. I believe they should be off by default.

**Comment by Moshyfawn** [comment]
There's an option to set

```json
  "calls": {
    "mute_on_join": true
  },
```

Does this suffice?

**Comment by HtetAungKhant23** [comment]
It's work. Thanks you.
