### ISSUE TITLE
[Feature] Add EOL setting, like "files.eol" in vscode

### ISSUE THREAD

**Issue by xgfone** [zed-industries/zed#12763]
### Check for existing issues

- [X] Completed

### Describe the feature

In setting, add an option, such as `"eol"`, to apply the file automatically when newing a file.

Also, it is better to support to modify EOL of the current opened file.

**Comment by xgfone** [comment]
Maybe duplicate of #5294??

**Comment by Moshyfawn** [comment]
I'm closing this thread in favour of the one linked above, as they seem to be the same. Be sure to +👍 the other thread.

Duplicate of:
- 5294
