### ISSUE TITLE
"Jump to" button is active but hidden

### ISSUE THREAD

**Issue by peterpeterparker** [zed-industries/zed#12765]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi 👋

In the results of searching for all references, the call to action button "Jump to ..." is hidden while being active.

(see screenshots)

<img width="1536" alt="Capture d’écran 2024-06-07 à 08 43 15" src="https://github.com/zed-industries/zed/assets/16886711/43f83394-1e05-472a-a921-83cab4615490">
<img width="1536" alt="Capture d’écran 2024-06-07 à 08 43 21" src="https://github.com/zed-industries/zed/assets/16886711/8f71fec5-d55f-44f5-8165-888e73dc0009">

### Environment

MacOS

**Comment by Moshyfawn** [comment]
Does #9718 resonate with what you're describing here?

**Comment by peterpeterparker** [comment]
Maybe it's related, but what I mean is that there seems to be a specific region of the bar that can be clicked to navigate to a particular piece of code, even though no call to action, such as a button, is displayed. That's surprising to me. I would expect either no action or a visual hint.

**Comment by JosephTLyons** [comment]
I think the button here is actually the divider separating the excerpts, but seems to not be correctly vertically centered around it.

**Comment by notpeter** [comment]
I don't actually think this is a hidden button as marked by the square on your screenshot.

In the current version of Zed this is a clickable area beneath the entire separator which allows to you jump to that specific section of the file:
<img width="936" alt="Screenshot 2024-11-05 at 15 59 49" src="https://github.com/user-attachments/assets/78b964bb-dc17-413c-9d41-46c52286ce60">

This is currently operating as designed, with a hover hint to help discover what clicking will do, without cluttering up each except with duplicated text and icons.

Thanks for reporting!
