### ISSUE TITLE
Shortcut for editing a task clashes with macOS shortcut for acute accent

### ISSUE THREAD

**Issue by janko** [zed-industries/zed#12770]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I hover over a task and try to type `alt-e`, instead of activating task editing, for me it types the accent modifier character (`´`) into the task bar. The same is with `alt-shift-e`. According to [this](https://www.webnots.com/option-or-alt-key-shortcuts-to-insert-symbols-in-mac-os-x/), it's a Mac shortcut. 

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/795488/5bf5614b-0040-4ed2-b4b9-32d61a9a0a95

**Comment by osiewicz** [comment]
That's already fixed on Preview. See: https://github.com/zed-industries/zed/pull/12601
I'm gonna optimistically close this issue. Feel free to reopen if you still encounter it with 0.139.6

**Comment by janko** [comment]
Awesome, thank you! 🙂
