### ISSUE TITLE
Opening split pane in Vim mode doesn't focus the new pane

### ISSUE THREAD

**Issue by janko** [zed-industries/zed#12771]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In Vim, `ctrl-w v` and `ctrl-w s` focus the newly opened pane. In Zed, the original pane remains focused.

Coming from Vim, this behavior throws me off a bit, because I'm used to open a split pane and then quickly open a file, but then I'm surprised that the file opens in the original pane instead of the new one.

Having the new pane be focused when using Vim bindings would make my transition to Zed smoother 🙂 

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@janko I cannot reproduce this. It seems like we are doing the same as vim here.

One thing that confused me when building the feature is that `s` creates a new window above by default (but I thought it'd create one below). Is it possible that is what you're seeing too?

**Comment by janko** [comment]
Ah, nevermind, I have `set splitright` and `set slitbelow` in my `.vimrc` that change the default Vim behavior (my comment there is "more intuitive splitting"). I didn't even realize that wasn't the default Vim behavior.

I was able to easily get this behavior by overriding the key bindings:

```js
{
  "ctrl-w s": "pane::SplitDown",
  "ctrl-w v": "pane::SplitRight"
}
```

**Comment by ConradIrwin** [comment]
Great!

**Comment by marblecaco3** [comment]
ctrl-w v is default bind to  pane::SplitVertical. why we have different things here? vim's default behavior also moves focus.

**Comment by janko** [comment]
Did you see my last comment? Do you happen to have `set splitright` and `set splitbelow` in your Vim configuration?

**Comment by marblecaco3** [comment]
yes, I copied that to my keymap. but at the same time I wish zed can make splitVertical right, because that action is confinable.
