### ISSUE TITLE
settings.json env variables do not get set into terminal

### ISSUE THREAD

**Issue by aryeh** [zed-industries/zed#12793]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I define variables under the "env" property in the settings.json file, it does not get set in the terminal, nor does it get set into the the Tasks environment.

Am I just not understanding the utility of the env property for the settings.  Where exactly and how can I use these variables?  

I would assume they would be accessible for use in the Tasks - i.e. you set  "PROJECT_NAME" in the local settings.json, and then can use $PROJECT_NAME in the Tasks  rather than have to set PROJECT_NAME into the env property of every single necessary task.   In fact, the Task should be able to be a global task and reference a variable set later in the local settings.json to make it specific for the project.

Regardless, unless I'm missing something the env in settings.json aren't accessible in the contexts they'd be most useful and necessary: the terminal and Tasks. 

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 128 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
I can see the variable set in `terminal.env` in the Zed terminal after restarting the editor.

**Comment by aryeh** [comment]
This is my mistake.  I didn't read the docs start to finish, but rather looked things up using the docs as reference material.

I didn't realize from the docs that the `env` property was a sub-property of `terminal`.   Similar to how the git examples illustrate:

```
{
  "git": {
    "git_gutter": "tracked_files"
  }
}
```

I would have expected the `env` example to be:

```
{
  "terminal": {
    "env": {
       "key": "val"
    }
  }
}
```

The example shows:
```
"env": {
  "ZED": "1",
  "KEY": "value1:value2"
}
```

That led me to believe the `env` property was a root property in the settings.json file, not a sub-property of `terminal`.  My apologies.

**Comment by Moshyfawn** [comment]
I see! No problem, and I'm glad it's resolved for you.
