### ISSUE TITLE
Assistant file Inclusion no longer enabled

### ISSUE THREAD

**Issue by kenshanta** [zed-industries/zed#12798]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

The file inclusion feature for the Assistant has been disabled on my environment.
I would like to re-enable the feature but cant seem to find the property for it in the `setting.json` file nor in the command line palette (cmd - shift - p) _assistant:_

Going through the official [Zed documentation](https://zed.dev/docs/assistant-panel) was a letdown as the topic about "File Inclusion/Exclusion" is excluded.

I remember wanting to disable it sometime ago and managed to do so but forgot how it was done (done during one of my overnight sessions)

### In Addition:
I tried looking up on how to disable/enable it but to no avail. only a couple of [Reddit posts](https://www.reddit.com/r/ZedEditor/comments/1d0kosv/how_to_disable_default_file_inclusion_in_zed/) that are still unaddressed.

### [Last Resort](https://youtu.be/j0lSpNtjPM8?si=YheZ2g9BwR4I5lav)
Asking the assistant on gpt-4o would be a good idea but i ran out all my openAI api key credits :(

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
In the Assistant panel, type `/` to see a list of all available actions, such as adding files to the context.

**Comment by ThomasEwalts** [comment]
I have the same issue, to add to it: adding files with `/` gives a "I'm sorry, but I cannot access specific files on your device" response from GPT 4o, 4 and 3.5

**Comment by kenshanta** [comment]
#### Since i know I'm out of credits, I've been getting an error to any request made on any model.

- The solution provided by @Moshyfawn is an interesting one as i noticed an odd behavior.
> In the Assistant panel, type `/` to see a list of all available actions, such as adding files to the context. 

you can import a specific file as you provide the directory for it after typing in `/file`
Actioning an inclusion for a _file_ is expandable & viewable within the panel itself.

On the other hand, when the inclusion is for a _project_ `/project`, I assume it will import the current open project as there are no prompts to import a specific one like when importing a file.
The *issue* here is that I cannot "expand" or view the project import made.

### Image references below

<img width="644" alt="Screenshot 2024-06-09 at 5 16 18 PM" src="https://github.com/zed-industries/zed/assets/83559262/be4547c5-b38b-46f9-a81c-5d733b111e52">
<img width="637" alt="Screenshot 2024-06-09 at 5 30 37 PM" src="https://github.com/zed-industries/zed/assets/83559262/6ae7ea07-f9c2-496b-8014-b22e1f4a62bb">
