### ISSUE TITLE
Setting both `show_copilot_suggestions` and `show_inline_completions` causes `language_overrides` to be ignored

### ISSUE THREAD

**Issue by gmcabrita** [zed-industries/zed#12799]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It seems that when setting both `show_copilot_suggestions` and `show_inline_completions` the `language_overrides` or `languages` are then ignored.

Minimal `settings.json` which triggers the bug (JavaScript files won't be using hard tabs as configured):
```json
{
  "show_inline_completions": true,
  "show_copilot_suggestions": true,
  "language_overrides": {
    "JavaScript": {
      "hard_tabs": true
    }
  }
}
```

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Relevant log message:
```
2024-06-08T12:41:07+01:00 [ERROR] crates/settings/src/settings_store.rs:619: duplicate field `show_inline_completions`
```

**Comment by SomeoneToIgnore** [comment]
`language_overrides` is an alias to `languages`, and I think there were talks of removing `language_overrides` entirely.
So, not surprising to see that when the same "entity" gets the same field twice, there's a duplication warning.
Additionally, `show_copilot_suggestions` config key does not exist per se anymore, being replaced by `show_copilot_suggestions`

https://github.com/zed-industries/zed/blob/7d8f2f795f4e8807f4cb530f8ee83eb6c3f1ccd2/crates/language/src/language_settings.rs#L298-L299

So, to fix your issues, it would be nice to remove the `language_overrides` and `show_copilot_suggestions` entirely, leaving whatever relevant settings in the `languages` section.

Zed should treat configs better and maybe show errors too, but not sure what can be done now,
