### ISSUE TITLE
Icon add runnable some padding

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12803]
### Check for existing issues

- [X] Completed

### Describe the feature

@RemcoSmitsDev : 

When I hover/click on the icon I think it needs a bit of padding on the sides, as seen in the icon after.

<img width="20" alt="Screenshot 2024-06-08 alle 18 09 08" src="https://github.com/zed-industries/zed/assets/20476002/f59cb2ea-fc7e-4faa-8d70-f29fccf9c4b8">

Example:
<img width="31" alt="Screenshot 2024-06-08 alle 18 09 23" src="https://github.com/zed-industries/zed/assets/20476002/f7dac8b0-39d4-4016-9293-e06273dcae52">

**Comment by JosephTLyons** [comment]
@iamnbutler

**Comment by maxdeviant** [comment]
This was resolved in https://github.com/zed-industries/zed/pull/12906.
