### ISSUE TITLE
Ability to close the terminal after running the script by pressing any key

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12806]
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode:

<img width="494" alt="Screenshot 2024-06-08 alle 18 36 16" src="https://github.com/zed-industries/zed/assets/20476002/57244ee4-1e11-4ccd-8a49-f013509ec76f">

Zed:
<img width="276" alt="Screenshot 2024-06-08 alle 18 40 03" src="https://github.com/zed-industries/zed/assets/20476002/cc81ab64-1001-451a-83e6-7743f4758ab2">

<img width="714" alt="Screenshot 2024-06-08 alle 18 33 17" src="https://github.com/zed-industries/zed/assets/20476002/d95d9cf6-8619-4898-8705-dd966c8a6127">

**Comment by bersace** [comment]
May be redundant with #14148

**Comment by notpeter** [comment]
Zed supports the option to close after running as @bersace has linked.
At this time we don't intend to support a close with keystroke option, as a workaround you can use `cmd-w` / the `x` on the tab or append `; read -n 1 -s -r -p "Press any key to continue..."` to your task definition (or via a similar script in your path).

Thanks for reporting.
