### ISSUE TITLE
Support Clangd textDocument/switchSourceHeader to toggle between C/C++ header and source

### ISSUE THREAD

**Issue by persidskiy** [zed-industries/zed#12801]
### Check for existing issues

- [X] Completed

### Describe the feature

Clangd has the `textDocument/switchSourceHeader` command that allows to switch between corresponding headers and sources. We need to support it to enable basic C/C++ file switching workflow. https://clangd.llvm.org/extensions.html#switch-between-sourceheader

Other editors implementations:
- nvim: https://github.com/neovim/nvim-lspconfig/blob/92166b89ab4b3d60f24e58170cac53b7141fd032/lua/lspconfig/server_configurations/clangd.lua#L9
- vscode: https://github.com/clangd/vscode-clangd/blob/eb945ec3e07226a8634a27d3d519677ce701806f/src/switch-source-header.ts#L15

**Comment by SomeoneToIgnore** [comment]
Fixed with https://github.com/zed-industries/zed/pull/14646, comes in Zed 0.151 next Wednesday.
