### ISSUE TITLE
i am having an indentation error on zed IDE 

### ISSUE THREAD

**Issue by tanishqmalik** [zed-industries/zed#12800]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

recently i was trying to code on zed using vim....when i go to next line after writing "{" i don't get tab(spaces), line starts from zero .... what to do ??

### Environment

Chip: Apple M2
Memory: 8 GB
macOS: 14.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Indentation Error](https://github.com/zed-industries/zed/assets/122337260/a60471a7-5a5e-4c90-9f0f-ce4d711bfeb3)

**Comment by Moshyfawn** [comment]
Since there are 2 community maintained Java extensions, you may want to fill out the issue in one of those repos, depending on which plugin you're using:

- https://github.com/ABckh/zed-java-language-support-jdtls/issues/new
- https://github.com/zed-extensions/java/issues/new
