### ISSUE TITLE
`.sample` files recognized as `Shell Script` files but not all

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12810]
### Check for existing issues

- [X] Completed

### Describe the feature

All the `.sample` files I have on `.git/hooks` are recognized as `Shell Script`, except one `fsmonitor-watchman.sample`.

The only difference I noticed is that all sample files start with `#!/bin/sh`, whereas the `fsmonitor-watchman.sample` file starts with `#!/usr/bin/perl`.

Going to check the extensions for the `path_suffixes` for `Shell Script` I noticed that the `sample` extension is not found. 
So how do `sample` files get recognized as `Shell Script`?

https://github.com/zed-industries/zed/blob/e829a8c3b0564bc902cc0d0a530099be7f0f036e/crates/languages/src/bash/config.toml#L1-L4

Recognized sample file:

<img width="569" alt="Screenshot 2024-06-08 alle 19 56 44" src="https://github.com/zed-industries/zed/assets/20476002/32fd2962-1b46-4232-9f1a-aa1a3b5d1f61">

Unrecognized sample file:

<img width="595" alt="Screenshot 2024-06-08 alle 19 57 05" src="https://github.com/zed-industries/zed/assets/20476002/d229ff85-1c98-42da-acb3-eed05066a294">

Going to see how vscode behaves, this file is recognized as perl, as can be seen from its initial wording `#!/usr/bin/perl` is a perl example file.

So how are other files recognized as `Shell script` ?

**Comment by notpeter** [comment]
This is working as-designed. That file is not a Shell Script, it is a perl script. If you install the Perl extension it will auto-identify the shebang and toggle the language to Perl.
https://github.com/tree-sitter-perl/zed-perl/blob/master/languages/perl/config.toml

If it were detected as a Shell Script the syntax highlighting would be for the wrong language (POSIX Shell, not Perl).
