### ISSUE TITLE
zed window is not Maximum at start

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#12826]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. make zed Maximum
2. quit zed
3. open zed, there are spaces at left:

<img width="592" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/f2b23c19-31d0-4ec6-b9be-71230ab2ef83">

4. double click header to maximum

<img width="479" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/2460b6e4-3bf8-4581-8829-f2713a727689">

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
I can't seem to be able to reproduce this behaviour 🤔

**Comment by kzhui125** [comment]
Can you reproduce with "State Manager" enbaled?

<img width="369" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/f9a35c98-3c88-47d9-b2ac-0f81fd5fc151">

<img width="1162" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/347c6ef2-956b-4c8f-8547-b79bedd2f00d">

In my environment: on Zed start up, window_x will changed from `0` to `4`.

But I don't reproduce with `examples\window_positioning.rs` (window_size: 1920, 1055), (left_top: 0, 25).

Don't know why the move happens in Zed.

**Comment by alex35mil** [comment]
It doesn't seem to be related to Zed. Neovide, Slack, and some others act the same way on my machine. Looks like a macOS bug to me.

**Comment by Moshyfawn** [comment]
@alex35mil seems to have hit the nail on the head. I don't usually use Stage Manager (SM), but when I enable it, the SM gap on the left seems to me to be quite significant.

<img width="1512" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/3c4f00bb-d088-492b-b224-c79c48cfe579">

**Comment by kzhui125** [comment]
thanks, wait for Apple to fix this issue
