### ISSUE TITLE
Capability to Save without "Hooks" with Key Binding

### ISSUE THREAD

**Issue by EstebanBorai** [zed-industries/zed#12824]
### Check for existing issues

- [X] Completed

### Describe the feature

Sometimes when editing certain files I don't want to have format on save nor ensure newline
enabled. But of course I would love to continue use it in other file updates, this is just
for exceptional cases.

I think having a shortcut for this would be useful, like for instance saving with another keys combination.

Consider `⌘ + K` then `⌘ + S`? So if you enable Command K before Saving that last save will not enforce neither format on save nor ensure last newline.

**Comment by Moshyfawn** [comment]
This is already a feature: `"cmd-k s": "workspace::SaveWithoutFormat"`.

**Comment by EstebanBorai** [comment]
Thanks so much @Moshyfawn! Im closing this issue!
