### ISSUE TITLE
Updating $TERM_PROGRAM env variable

### ISSUE THREAD

**Issue by tashi21** [zed-industries/zed#12834]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If I have a .zshrc file that executes instructions based on which terminal is being used, the zed editor doesn't update the $TERM_PROGRAM env variable on its own. Right now I am passing it in the terminal.env settings parameter to update it but I believe this should be done automatically.

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by tashi21** [comment]
Duplicate

**Comment by Moshyfawn** [comment]
Be sure to +👍 the other thread.

Duplicate of:
- #4571
