### ISSUE TITLE
Svelte syntax highlighting is lacking

### ISSUE THREAD

**Issue by didier** [zed-industries/zed#12833]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Compare VS Code (left) vs. Zed (right). You'll see the highlighting in VS Code is much more complete. I hope we can address this for Zed too.

Notable points are string interpolation, directives like `class:name={condition}`, brackets and spread operators.

![CleanShot 2024-06-10 at 10 24 52@2x](https://github.com/zed-industries/zed/assets/9499859/29666c5f-2c6b-420c-b671-99fc520b263c)

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by Gioppix** [comment]
any update on this? I'm tired of vscode crashing but i can't switch because of this :o

**Comment by matubu** [comment]
I think this is the same issue as #7774

**Comment by didier** [comment]
@matubu Hi, no, although that one's also annoying. I'm not just talking about string interpolation, but also class/, style: and other directives.

**Comment by matubu** [comment]
In which case do you have issues with `class:` and `style:`? In the latest version, it seems it may have been fixed.

![image](https://github.com/user-attachments/assets/073d82e2-88ce-4a7e-b2d3-7ccbf39a943c)

**Comment by didier** [comment]
`style` and `test` are supposed to have different colors: 
![CleanShot 2024-07-17 at 14 45 22@2x](https://github.com/user-attachments/assets/b59f1532-3ab3-4f44-b278-e54ee646ae5e)

**Comment by AlbertMarashi** [comment]
Linking:
- https://github.com/zed-industries/zed/issues/17310

**Comment by AlbertMarashi** [comment]
Additionally, things like functions inside of attributes are not syntax highlighted as expected

![image](https://github.com/user-attachments/assets/f495a807-0844-49ff-a3ab-025dadb5678f)

But they are inside of JS expressions

![image](https://github.com/user-attachments/assets/71851172-1faf-4aa7-aab7-d713e92472be)

**Comment by matubu** [comment]
> Additionally, things like functions inside of attributes are not syntax highlighted as expected
> 
> ![image](https://private-user-images.githubusercontent.com/17972275/364054332-f495a807-0844-49ff-a3ab-025dadb5678f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjAyNDcsIm5iZiI6MTcyNTQ1OTk0NywicGF0aCI6Ii8xNzk3MjI3NS8zNjQwNTQzMzItZjQ5NWE4MDctMDg0NC00OWZmLWEzYWItMDI1ZGFkYjU2NzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE0MjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZjUwNTE0ZGQ3NGJkOWM0ZTVhNWFiZmUyYzk2NDRkM2IwY2UyZjU1MmU3NDZhNjNlMDJkMmExYTM4NDhhNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oRJT-rK00eNW_I47_bgvy6jAdnG9w2waBV2nK8ghVPU)
> 
> But they are inside of JS expressions
> 
> ![image](https://private-user-images.githubusercontent.com/17972275/364054421-71851172-1faf-4aa7-aab7-d713e92472be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjAyNDcsIm5iZiI6MTcyNTQ1OTk0NywicGF0aCI6Ii8xNzk3MjI3NS8zNjQwNTQ0MjEtNzE4NTExNzItMWZhZi00YWE3LWFhYjctZDcxM2U5MjQ3MmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE0MjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MTBkODY4YTJiNDQ0Zjc0Mzc3NmMzNTBkN2JhOWE1NzI1NzYzY2JmMzM3ZWFiNjdlM2VlNDBjYjNkZWMyMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZZ-F07C6KjLn7pfCsXAhWGS2AyB2l4YbWdr6COGh_-8)

I think this is related to semantic highlighting (#5345)

**Comment by AlbertMarashi** [comment]
After implementing #17404 

Most of these issues lie with the external tree-sitter repository, rather than Zed.

The tree-sitter repository has a tonne of issues, including the lack of escaping for attributes such as:

```svelte
<foo foo="test { this_is_treated_as_a_string }">
```
