### ISSUE TITLE
Display whitespace for unidentified symbols

### ISSUE THREAD

**Issue by tashi21** [zed-industries/zed#12837]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For the Zed integrated terminal, there should be a setting option that allows us to state that for unidentified symbols, the editor should display a blank space instead of the box with a question mark.

The font I am using is MesloLGS NF

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed Editor:
![Screenshot 2024-06-10 at 2 43 38 PM](https://github.com/zed-industries/zed/assets/79501323/a282b6c9-3d1c-4b71-8415-cc3a96f748a4)

Warp Editor:
<img width="373" alt="Screenshot 2024-06-10 at 2 43 11 PM" src="https://github.com/zed-industries/zed/assets/79501323/125154ef-2470-4564-8d5b-d0b1cee44add">

**Comment by notpeter** [comment]
Zed should no longer be displaying a question mark and should show the default icon like this:
<img width="236" alt="Screenshot 2024-11-05 at 15 11 53" src="https://github.com/user-attachments/assets/cb0c477b-1006-47ed-9c46-022807a65d08">

We do support [disabling file icons](https://zed.dev/docs/configuring-zed?highlight=file%20icons#project-panel) in project panel with:
```json
{
  "project_panel": {
    "file_icons": false,
    "folder_icons": false
  }
}
```

At this time we are not looking to maintain a backlog of potential design options that we are not immediately planning on implementing so I'm going to go ahead and close. 
Thank you for reporting.
