### ISSUE TITLE
Ctrl+Left to collapse all directories in the sidebar.

### ISSUE THREAD

**Issue by skejeton** [zed-industries/zed#12841]
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode there's a feature that allows you to collapse all directories in the sidebar, once you're finished working on one thing it's nice to close it all to move on to another.

**Comment by Moshyfawn** [comment]
This is already a feature: `project panel: collapse all entries` in the command palette.

**Comment by curiousercreative** [comment]
@Moshyfawn would it be easy for a user to add a keybinding for that? The [key bindings doc](https://zed.dev/docs/key-bindings) doesn't seem to have a clearly marked example of a command invocation. What would that look like?

**Comment by Moshyfawn** [comment]
You can see examples of keymaps by looking up `zed: open default keymap` in the command palette.

Ther's a default keybinding for `project_panel::CollapseSelectedEntry` which you can reference when creating your own using `zed: open keymap` in the command palette.

The context and name of each action entry will look similar to what it is in the command palette.

So in the case of `project panel: collapse all entries` your `keymap.json` might look something like this:

```json
[
  {
    "context": "ProjectPanel",
    "bindings": {
      "cmd-l": "project_panel::CollapseAllEntries"
    }
  }
]
```

**Comment by skejeton** [comment]
Hmm this command doesn't seem to work: here's my keymap configuration:
```
[
  {
    "context": "ProjectPanel",
    "bindings": {
      "ctrl-left": "project_panel::CollapseAllEntries"
    }
  }
]
```

**Comment by Moshyfawn** [comment]
> Hmm this command doesn't seem to work: here's my keymap configuration:

It seems that the `ctrl-left` keybind [is currently reserved](https://github.com/zed-industries/zed/blob/ec9e700e7003e266c269cc257bdc1a32f033d6a7/crates/gpui/src/platform/mac/window.rs#L1340).

Zed docs [reference](https://arc.net/l/quote/tsvbubxg).

> There are some key bindings that can't be overridden; we are working on an issue surrounding this.

**Comment by curiousercreative** [comment]
@Moshyfawn gladly, I was able to bind it on Linux (where I just mimic the cmd+left from macOS).

**Comment by notpeter** [comment]
I'm going to close this users can a custom keybind for `project_panel::CollapseAllEntries` like the example [provided above](https://github.com/zed-industries/zed/issues/12841#issuecomment-2161042147) and it just seems `ctrl-left` is reserved (e.g. `cmd-left` works just fine.

Neither Zed nor VSCode has a default mapping for `Collapse Folders in Explorer` which I think is ok.
