### ISSUE TITLE
Please add Julia Language

### ISSUE THREAD

**Issue by its-popplewell** [zed-industries/zed#12875]
### Check for existing issues

- [X] Completed

### Describe the feature

I am a huge proponent of the [Julia language](https://julialang.org) and use it a lot for my work. I am a big fan of its julia-all the-way-down approach, similar to rust, and its ambitious roadmap. I am a long time nvim user and I still go back to it for Julia, which is kind of a pain. There is already a fully written Julia LSP ([see here](https://github.com/julia-vscode/LanguageServer.jl)), and I would love to see Zed adopt Julia (as I have!) as an excellent prototyping language and a great data science language.

**Comment by JosephTLyons** [comment]
Hey @its-popplewell, there is a plugin for Julia lang already in the extension store (command palette > extensions` -> "Julia")

<img width="809" alt="SCR-20240611-byhd" src="https://github.com/zed-industries/zed/assets/19867440/333c708c-278b-4642-af2d-db86ab96ea61">

The source code for that extension is here:

- https://github.com/JuliaEditorSupport/zed-julia

It looks like it adds syntax highlighting and language server support - Is this sufficient for you?

**Comment by JosephTLyons** [comment]
I think the extension should provide all that is being requested, so I'm going to close this out.
