### ISSUE TITLE
Scheme theme not updated

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12882]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I took a look at the example scheme here: https://zed.dev/schema/themes/v0.1.0.json
I compared it to the themes found on [extensions](https://github.com/zed-industries/extensions).

I noticed the following problems:

1) In the example scheme the following is used: `scrollbar_thumb.background` but in many themes `scrollbar.thumb.background` is used instead which of the two is correct?

2) Many are missing the `description`, for example in `players` what does it do?

3) In many themes you will find `accents`, what is it for?

4) There is no information about `syntax`, what properties it may have and more.

**Comment by notpeter** [comment]
cc: @maxdeviant

**Comment by notpeter** [comment]
I've published an updated theme schema on the website as part of:
- #21428 

You can find the current version here:
- https://zed.dev/schema/themes/v0.2.0.json
