### ISSUE TITLE
Configuring pyright or replacing it entirely

### ISSUE THREAD

**Issue by daniel-mosko** [zed-industries/zed#12883]
### Check for existing issues

- [X] Completed

### Describe the feature

Is there a way to configure pyright to automatically include parentheses () when autocompleting method names? Currently, it only suggests the method itself. Something like `"python.autoComplete.addBrackets": true` in VSCode?

If it is not possible, how to replace pyright with some different LSP (pylsp?) that also supports snippets?

**Comment by JosephTLyons** [comment]
Right now, I think we are stuck with Pyright, unless there is a language server we can use that is better. If there is, someone can bundle it into an extension and you can turn off Pyright in your settings and only allow the extension's language server to be used. That being said, I don't think we have any extensions offering an alternative Python language server at the moment.

Other issues about improving python / replacing pyright.

- https://github.com/zed-industries/zed/issues/7808
- https://github.com/zed-industries/zed/issues/7296
