### ISSUE TITLE
Runnable with watchmen 

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12885]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to be able to use runnable together with watchmen.

For example if I have a script in `package.json` that runs something like `node test.js`, it would be nice that every time the `test.js` file is modified then the command is re-executed again without having to do it manually.

You should also check that watchmen is installed before running the command.

@RemcoSmitsDev : Do you think this might be a feasible thing to do?

**Comment by notpeter** [comment]
We do not intend to implement an integrated watch-based auto task runner at this time.
We recommend you spawn a stand-alone tool for this purpose either in a Terminal or task.
Thanks for reporting.
