### ISSUE TITLE
can't quote text with `<>`

### ISSUE THREAD

**Issue by shenjackyuanjie** [zed-industries/zed#12898]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![recording 1](https://github.com/zed-industries/zed/assets/54507071/c767695c-3d10-48fb-b682-6024ed779c60)

as you can see

what I excepted:

![recording](https://github.com/zed-industries/zed/assets/54507071/3eeaa5b0-0e69-4327-9645-f35f1779c528)

### Environment

Zed: v0.140.0 (Zed Dev e829a8c3b0564bc902cc0d0a530099be7f0f036e)
OS: Windows 10.0.19045
Memory: 95.9 GiB
Architecture: x86_64

**Comment by SomeoneToIgnore** [comment]
More context for anyone interested in fixing this: https://github.com/zed-industries/zed/pull/13187
