### ISSUE TITLE
autoformat breaks comments in mdx file

### ISSUE THREAD

**Issue by passichenko** [zed-industries/zed#12897]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in mdx file autoformat replaces `{/* ... */}` with `{/_ ... _/}`
for example
```
{/* TODO: add example */}
```
becomes
```
{/_ TODO: add example _/}
```

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Currently we don't have a explicit language support for MDX but there is an issue tracking that progress in the extensions repository:

- https://github.com/zed-industries/extensions/issues/203
