### ISSUE TITLE
Update imports when moving or renaming files

### ISSUE THREAD

**Issue by krisfragata** [zed-industries/zed#12891]
### Check for existing issues

- [X] Completed

### Describe the feature

I thought about making the switch to zed and tested it out today. I love the ui and the noticeably faster...everything. However, upon continuing my project of restructuring the codebase at my job, I noticed a lack of a simple, key feature, automatically updating imports when moving or renaming a file. Because of this, I will have to continue using vs code for the time being. Would love to see this feature soon! Thanks in advance, Kris

**Comment by notpeter** [comment]
Hi @krisfragata,

Yes, currently we do not have support for refactoring on rename, but here is an existing issue for tracking the progress of that feature.  Please vote 👍 and subscribe that issue if you'd like to track progress for this feature in the future.

- https://github.com/zed-industries/zed/issues/5252

**Comment by somtooo** [comment]
Don't think this should be closed. Moving files to folder doesn't update imports
