### ISSUE TITLE
Comments are highlighted

### ISSUE THREAD

**Issue by effdotsh** [zed-industries/zed#12908]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="863" alt="image" src="https://github.com/zed-industries/zed/assets/50590465/31a3dde2-6cfa-4c17-8972-aaa7d4bf84cd">

<img width="863" alt="image" src="https://github.com/zed-industries/zed/assets/50590465/44eead58-0ae3-4c1a-a59c-28aac091fd65">

### Environment

Zed: v0.139.3 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Can you still repro this issue?

**Comment by effdotsh** [comment]
I tried commenting out the same lines of the codebase and did not see it.

**Comment by JosephTLyons** [comment]
> I tried commenting out the same lines of the codebase and did not see it.

I might be misunderstanding, but it sounds like you aren't running into this issue anymore, so I'm going to close this out. If I'm wrong, ping me here and I will reopen.

**Comment by effdotsh** [comment]
Correct, I have not seen it recently.
