### ISSUE TITLE
Assistant Panel: /search (semantic search) still available - but does nothing since the feature was removed.

### ISSUE THREAD

**Issue by phromo** [zed-industries/zed#12904]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the Assistant Panel, when typing `/` semantic search is still listed as an accelerator. It seems to do nothing. I searched for issues and found out the feature had been removed. I guess it is a bug that it lingers in the Assistant Panel?

### Environment

Zed: v0.140.0 (Zed Dev ec9e700e7003e266c269cc257bdc1a32f033d6a7)
OS: Linux 1.0.0
Memory: 62.1 GiB
Architecture: x86_64

**Comment by maxdeviant** [comment]
The old semantic search was removed, but the `/search` slash command is part of the new semantic search.

**Comment by remorses** [comment]
Is there any plan to bring back semantic search? It would be super useful to let the agent find code more efficiently
