### ISSUE TITLE
Broken highlighting for some zsh expansions

### ISSUE THREAD

**Issue by skwerlman** [zed-industries/zed#12917]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using some complex parameter expansions in zsh which involve expansion flags and quoted command substitution, syntax highlighting afterwards is broken.

Some examples which break highlighting:

```zsh
foo=${(f)"$(ls "$HOME")"}

foo=${(f)"$(ls ~)"}
# even removing the quotes here, its still broken
foo=${(f)$(ls ~)}
```

Very similar examples which don't:

```zsh
foo=${(f)$(ls "$HOME")}
foo=${"$(ls "$HOME")"}

foo=${(f)$(ls "~")}
foo=${"$(ls ~)"}
foo=${$(ls ~)}
```

The real-world case I ran in to is shown in the screenshots of broken highlighting

### Environment

Zed: v1.0.0 (Zed Preview)
OS: Linux 1.0.0
Memory: 62.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Broken:
![image](https://github.com/zed-industries/zed/assets/6954107/a3b0a5c4-0966-4363-9053-320e8d11b830)

Working (but illegal):
![image](https://github.com/zed-industries/zed/assets/6954107/07e2e129-ae57-4979-9be6-dd66cf3a7191)

**Comment by notpeter** [comment]
Closing as this appears to be broken in the upstream tree-sitter: [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash) and not something zed specific.
<img width="636" alt="Screenshot 2024-11-05 at 14 55 49" src="https://github.com/user-attachments/assets/22db812a-6863-4096-b11d-737f8ff83170">

Thanks for reporting.

**Comment by AndydeCleyre** [comment]
Related: https://github.com/zed-industries/extensions/issues/1368
