### ISSUE TITLE
Theme does not persist

### ISSUE THREAD

**Issue by JosiahParry** [zed-industries/zed#12916]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Previously when a theme would be changed it would persist. Zed updated itself and removed my theme choice. When I set it back it removes itself. 

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screen Recording 2024-06-11 at 20 16 14](https://github.com/zed-industries/zed/assets/13534508/09acd644-a362-41a6-ab6a-7c21900dc11a)

**Comment by Moshyfawn** [comment]
Can you check your log entries after you open Zed when it resets your theme?

**Comment by JosiahParry** [comment]
attached is the log. I am using the Rose Pine theme. I dont recall if it is from an extension or not. I can try another theme as well
[zed.log](https://github.com/user-attachments/files/15807022/zed.log)

**Comment by JosiahParry** [comment]
Every theme I've tried does not persist

**Comment by JosiahParry** [comment]
There was an issue with the settings braces. It would be awesome if there was a big ole "you messed up your json!!!" warning if the settings.json file is borked!

**Comment by Moshyfawn** [comment]
> There was an issue with the settings braces. It would be awesome if there was a big ole "you messed up your json!!!" warning if the settings.json file is borked!

Yes, we talked about this behaviour in #12389 too. But depending on which setting you have "messed up", there should be some diagnostics shown against the Zed Settings JSON schema.

**Comment by JosiahParry** [comment]
Closing in favor of #12389
