### ISSUE TITLE
Icon gitlab extensions

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12933]
### Check for existing issues

- [X] Completed

### Describe the feature

Url points to an address on `gitlab` but icon shown is that of `github`, it would be better to show gitlab icon.

![image](https://github.com/zed-industries/extensions/assets/20476002/837783dd-6e08-457c-9307-7be0d4b0baef)

**Comment by maxdeviant** [comment]
The GitHub icon here is a stand-in for a more generic "source code repository" icon.

We may swap it out for one in the future, but I don't think it's a stretch to use the GitHub icon to represent "repository", regardless of where it is hosted.

Having to support a bunch of different icons for various hosting services is going to make the extension cards look inconsistent from one another.
