### ISSUE TITLE
Empty window on macOS 15 beta

### ISSUE THREAD

**Issue by TeamPuzel** [zed-industries/zed#12930]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed opens but the window is completely blank (but the icon is visible in mission control, the surface appears to have no size)

![Screenshot 2024-06-12 at 13 16 46](https://github.com/zed-industries/zed/assets/94306330/74498d6d-dfe2-4486-9b6a-bd8f12ac3c74)

Console errors (sorry for the screenshot, I don't believe there is an export feature...)
<img width="1349" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/aab0de0b-97be-499c-81c5-478ecf436aed">

Terminal output:
```
13:20 ~ > /Applications/Zed\ Preview.app/Contents/MacOS/zed
CoreGraphics PDF has logged an error. Set environment variable "CG_PDF_VERBOSE" to learn more.
```

With the variable:
```
13:22 ~ > export CG_PDF_VERBOSE=true && /Applications/Zed\ Preview.app/Contents/MacOS/zed
Invalid value for entitlement: com.apple.coregraphics.disablepdf. Must be CFBooleanRef
Invalid value for entitlement: com.apple.coregraphics.disableinmemoryfonts. Must be CFBooleanRef
```

### Environment

N/A (Can't access palette)
It is an M2 Max 32GB MacBook Pro on the first macOS 15 Developer Beta

### If applicable, add mockups / screenshots to help explain present your vision of the feature

N/A

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

N/A

**Comment by TeamPuzel** [comment]
It worked fine for a while so this must have been a recent automatic update

**Comment by d1y** [comment]
I found out that it was the new tiling mode of macos that caused the problem

# Workaround
![image](https://github.com/zed-industries/zed/assets/45585937/37df3d4b-8c08-4d7e-9e96-765e6b92921b)

**Comment by TeamPuzel** [comment]
That workaround does work, thanks, I was worried I'd have to fall back to nvim :) Does this also happen to other apps or is it specific to something Zed is doing?
The only other app I had issues with is Steam, but they're just completely misusing the windowing APIs.

**Comment by Aaron-212** [comment]
Did you have Loop or similar Window Management software installed? I uninstalled Loop and it solves the issue.

**Comment by TeamPuzel** [comment]
No, I never used any window management software on macOS.

**Comment by Aaron-212** [comment]
I think the problem here might related to that Zed does not have a limit on how small the window could be. 
<img width="121" alt="image" src="https://github.com/zed-industries/zed/assets/38318044/9e907194-42e5-457e-91ea-96613426b479">
Maybe adding a limit could help.

**Comment by Aaron-212** [comment]
Just found a possible way to reproduce the bug. Fullscreen Zed, quit, reopen, exit fullscreen and it shrinks to void.

**Comment by sleetdrop** [comment]
I am using macOS 14.5 and Zed 0.139.3, have the same issue

**Comment by TeamPuzel** [comment]
> Just found a possible way to reproduce the bug. Fullscreen Zed, quit, reopen, exit fullscreen and it shrinks to void.

Is Zed restoring windows using the Cocoa APIs?
It doesn't seem to be doing that:

<img width="485" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/7fe0182f-04ce-4e00-ba38-8c2bd9cfe5f8">

I have this enabled, windows should only reopen if the checkbox is set on reboot or the app was closed with option-command-Q — but Zed is always reopening, so it's definitely not using the window restoration API correctly (or is not using it at all)

**Comment by mijailr** [comment]
I'm facing the same issue on MacOS 14.5 and Zed 0.139.3

**Comment by JosephTLyons** [comment]
@TeamPuzel - does this workaround do anything for you?

- https://github.com/zed-industries/zed/issues/11920#issuecomment-2156097349

**Comment by Aaron-212** [comment]
> > Just found a possible way to reproduce the bug. Fullscreen Zed, quit, reopen, exit fullscreen and it shrinks to void.
> 
> Is Zed restoring windows using the Cocoa APIs? It doesn't seem to be doing that:
> 
> <img alt="image" width="485" src="https://private-user-images.githubusercontent.com/94306330/339778923-7fe0182f-04ce-4e00-ba38-8c2bd9cfe5f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTAyOTEsIm5iZiI6MTcxODYwOTk5MSwicGF0aCI6Ii85NDMwNjMzMC8zMzk3Nzg5MjMtN2ZlMDE4MmYtMDRjZS00ZTAwLWJhMzgtOGMyYmQ5Y2ZlNWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA3Mzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOGQ4NzFiMDUxN2M4N2U5MjMwYjBmNDljZGU0YmMzNDJkOTc1MzI2MmFkYmIwOGRkNzBiZGZkNDA3OTg0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrhicrARxXiThUtM5M_VD_5RCvOQLHKt7PTa5YGvqI8">
> I have this enabled, windows should only reopen if the checkbox is set on reboot or the app was closed with option-command-Q — but Zed is always reopening, so it's definitely not using the window restoration API correctly (or is not using it at all). There isn't even a `Quit and Keep Windows` alternative menu item.
> 
> In a way this is also a different but related bug
> 
> Normally windows don't always reopen in fullscreen, they reopen on the desktop even if they were fullscreen before. This might be related too. Although sometimes they do reopen in fullscreen? Very confusing; Apple apps reopen in fullscreen but fail to switch to the correct space, and reopen on the desktop on reboot.
> 
> On top of that some of the apps remember their state separately to window state, but they seem to be low quality ported iOS apps (like iMessage) so not sure if that's intentional. Older apps like Calendar do remember state based on how the app was closed.
> 
> I guess even Apple doesn't care about this feature being consistent anymore.

<img width="354" alt="image" src="https://github.com/zed-industries/zed/assets/38318044/acd29bd4-0f0f-40cb-8a88-fd47af046a75">

Servo's rust AppKit cannot handle window restoration

**Comment by chronark** [comment]
Happens on macos 14.5 and zed 0.141.3 too

**Comment by notpeter** [comment]
Sequoia is no longer beta works properly with Zed.
Sorry we didn't get around to closing this sooner and thanks for reporting.

**Comment by dalisoft** [comment]
> # You are also a warrior
> I found out that it was the new tiling mode of macos that caused the problem I haven't studied it, but I suspect it's just missing some default values?
> 
> > `ctrl + cmd + f` enter full-screen it show window
> 
> # Workaround
> > `fn + control + c`
> 
> ![image](https://github.com/zed-industries/zed/assets/45585937/37df3d4b-8c08-4d7e-9e96-765e6b92921b)

Zed v0.170.1 and this issue still actual. Your solution worked
