### ISSUE TITLE
New Zed Project Template

### ISSUE THREAD

**Issue by felipetesc** [zed-industries/zed#12936]
### Check for existing issues

- [X] Completed

### Describe the feature

Add a new list item to the panel which is callable from the command ctrl-shift-p to allow us to create a new blanc project containing .zed folder and all custom json files. 
The list item can be called _**zed: new project**_

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/2336812/bdfeb3ba-3a93-409e-9057-b5eaee1b181f)

**Comment by someone13574** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/11280

**Comment by Moshyfawn** [comment]
Be sure to +👍 and follow the other thread.
