### ISSUE TITLE
Incorrect git status after branch switch

### ISSUE THREAD

**Issue by filipwiech** [zed-industries/zed#12941]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After switching branches Zed shows incorrect git status diff markers in files (in the editor gutter): it seems to think that the changes pulled in from the new branch are not already committed, as if I would have modified the files still in the old branch, even though `git status` shows clean repository state. After restarting the editor Zed shows (refreshes) correct status (no more phantom diffs are visible). Closing and reopening the files (buffers) doesn't help. I am switching branches (and working with git in general) outside of the editor window in the terminal if that matters.

### Environment

Zed: v0.140.0 (Zed Nightly b6ea393d140b52bab05892cf2718e1aef965bcb1)
OS: Linux 1.0.0
Memory: 31 GiB
Architecture: x86_64

**Comment by apricotbucket28** [comment]
Bisected this to edd613062a8b784135dda809febbb30223cf01bc

**Comment by someone13574** [comment]
This is also causing an issue where the git gutter status isn't cleared after a commit.

**Comment by filipwiech** [comment]
> Bisected this to [edd6130](https://github.com/zed-industries/zed/commit/edd613062a8b784135dda809febbb30223cf01bc)

Thank you for investigating, tagging @ConradIrwin. :slightly_smiling_face:

**Comment by apricotbucket28** [comment]
Fixed by https://github.com/zed-industries/zed/commit/95c69d069679c3d2894401ad53b7f6f4b73d7448 :tada:

**Comment by filipwiech** [comment]
Great news, big thanks to @ConradIrwin and @nathansobo for a quick fix! :+1: I will close this issue then. :slightly_smiling_face:
