### ISSUE TITLE
Outline panel toggle state not restored when Zed is reopened

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#12954]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open the outline panel.
2. Close Zed.
3. Open Zed.
4. Note that a different panel is displayed instead of the outline panel.

### Environment

Zed: v0.141.0 (Zed Nightly 8451dba6a77a6e2dd17670bb665ff11b112e5802)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Hmm, struggling to reproduce this on Nightly, both for no files open at all and some file left open show the outline panel with the corresponding contents.

But I've nuked by local DB a few days ago, after the startup was not working, maybe there are some extra repro steps?

**Comment by Moshyfawn** [comment]
This is a strange one, but I think I've managed to reproduce it reasonably well:

1. Open the Zed repo project.
2. Open `docker-compose.yml` **from the project panel** _(double click)_.
3. Open `livekit.yaml` **from the project panel** _(single click)_.
4. Open the outline panel via the outline panel icon button in the status bar.
5. Close Zed _(`cmd-q`)_.
6. Open Zed.
7. Notice that the project panel is open instead of the outline panel.

**Comment by Moshyfawn** [comment]
> ..maybe there are some extra repro steps?

This is a strange one, but I think I've managed to reproduce it reasonably well:

1. Open the Zed repo project.
2. Open `docker-compose.yml` **from the project panel** _(double click)_.
3. Open `livekit.yaml` **from the project panel** _(single click)_.
4. Open the outline panel via the outline panel icon button in the status bar.
5. Close Zed _(`cmd-q`)_.
6. Open Zed.
7. Notice that the project panel is open instead of the outline panel.

**Comment by yongkangchen** [comment]
Fixed by https://github.com/zed-industries/zed/pull/13601
