### ISSUE TITLE
Don't jump to the file using base_keymap JetBrains 

### ISSUE THREAD

**Issue by UtopiaEH** [zed-industries/zed#12974]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

![shoot_2024-06-13 _13 52 Zed](https://github.com/zed-industries/zed/assets/25262913/0f11f95c-e54a-4d03-8996-19923a65ead2)

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
To clarify, your reported issue is that Jump to file (alt+enter) works in the default keymap, but does work in the JetBrains keymap.  I am able to reproduce this behavior.

There is a mapping for `alt-enter` in that keymap, but I don' think it should conflict here.
https://github.com/zed-industries/zed/blob/6c70a809ecebb217004dec375c748bb69747aad5/assets/keymaps/jetbrains.json#L67-L74

**Comment by notpeter** [comment]
I am no longer able to reproduce this, `alt-enter` spawns code actions for me on MacOS as expected.  Sometime in the past five months I believe this has been fixed.  @UtopiaEH If you're still seeing this issue, please comment and I'm happy to reopen.
