### ISSUE TITLE
Zed not opening: os error 13 ~/.cache

### ISSUE THREAD

**Issue by dgl-prc** [zed-industries/zed#12979]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1012" alt="image" src="https://github.com/zed-industries/zed/assets/38609959/a01c6e4f-9c02-446d-92e4-736a050a2c9c">

### Environment

<img width="266" alt="image" src="https://github.com/zed-industries/zed/assets/38609959/43d1af26-8070-4d2e-9959-e9f35a9546f0">

**Comment by notpeter** [comment]
Hi @dgl-prc, Zed stores it's configuration in the `.config/zed` folder inside your home directory. The error is saying that it cannot create that directory.  Likely your directory permissions are incorrect.

Can you run the following command: `ls -l -d ~/.config ~/.config/zed`

```
% ls -l -d ~/.config ~/.config/zed
drwxr-xr-x@  7 peter  staff  224 Jun 11 16:31 /Users/peter/.config
drwxr-xr-x@ 30 peter  staff  960 Jun 13 09:41 /Users/peter/.config/zed
```

**Comment by seantiz** [comment]
so yes, I ran into this error as well on an M2 Air

I ran the command, got the same output in Terminal that @notpeter posted above (I don't know what this output means) and there is no `config` file in the listed `/Users/{username}/.config/zed` path when I go to that directory in Finder

**Comment by notpeter** [comment]
Please paste the output from the `ls` command, I'm trying to confirm that the username and permission bits aren't set incorrectly.

**Comment by notpeter** [comment]
I'm sorry, I misread `.cache` as `.config` in your screenshot.  My guess is that your `.cache` folder has wonky permissions. All Zed is trying to do is the equivalent of `mkdir -p ~/.cache/zed` which is coming back with permissions denied.  You should be able to change the permissions/ownership of your `.cache` folder so that your user can create new dirs.

Mine looks like this:
```
% ls -l -d ~/.cache ~/.cache/zed 
drwxr-xr-x@ 5 peter  staff  160 Jun 14 08:58 /Users/peter/.cache
drwxr-xr-x@ 2 peter  staff   64 Jun  6 15:48 /Users/peter/.cache/zed
```

**Comment by seantiz** [comment]
I'm guessing this is just my limitations with zshell as I really do not understand this output

When i ran the `ls` command on the `cache` folder I get the same permissions in the output that you posted (and this is with the existing issue that zed does not have write permissions necessary to persist settings or install new folders for extensions):

`drwxr-xr-x@ 10 root  staff  320 18 Jun 12:42 /Users/applesmg/.cache`

Then when I use Finder to change the read and write permissions on the `cache` folder and us the `ls` command again I get this as output:

`drwxrwxr-x@ 10 root  staff  320 18 Jun 12:42 /Users/applesmg/.cache`

**Comment by notpeter** [comment]
Can you just run `mkdir -p ~/.cache/zed` manually and launch zed again? Zed only needs to create that directory if it doesn't exist.

**Comment by dgl-prc** [comment]
> Hi @dgl-prc, Zed stores it's configuration in the `.config/zed` folder inside your home directory. The error is saying that it cannot create that directory. Likely your directory permissions are incorrect.
> 
> Can you run the following command: `ls -l -d ~/.config ~/.config/zed`
> 
> ```
> % ls -l -d ~/.config ~/.config/zed
> drwxr-xr-x@  7 peter  staff  224 Jun 11 16:31 /Users/peter/.config
> drwxr-xr-x@ 30 peter  staff  960 Jun 13 09:41 /Users/peter/.config/zed
> ```

Sorry for late reply. I fixed it. The reason is that folder ".cach" is previously created with sudo. So I just change the user group and user to the normal user, instead of root.
