### ISSUE TITLE
Cannot paste on Wayland

### ISSUE THREAD

**Issue by Stanko2** [zed-industries/zed#12970]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am able to copy or cut with (`Ctrl+C`), (`Ctrl+X`). However `Crtl+V`, `Ctrl+Shift+V` and also running the paste command from palette do nothing.

### Environment

Zed: v0.138.3 (Zed Preview)
OS: Linux 1.0.0
Memory: 15.2 GiB
Architecture: x86_64

**Comment by apekros** [comment]
Duplicate of #12054
