### ISSUE TITLE
Vim ysa should surround around selection, but surrounds inside

### ISSUE THREAD

**Issue by martijnarts** [zed-industries/zed#12976]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure what the correct description is in vim-lingo, but basically when I have this code:

```
function("hi")
```

And I put my cursor in the `h` and type `ysa([` it should result in this:

```
function[("hi")]
```

but currently it functions the same as `ysi([`, resulting in this:

```
function(["hi"])
```

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
Thanks for reporting! If you'd like to pair with me on a fix: https://calendly.com/conradirwin/pairing.
