### ISSUE TITLE
Tailwind LSP takes precedence as a formatter in Ruby files

### ISSUE THREAD

**Issue by vitallium** [zed-industries/zed#12973]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a Ruby project with the `solargraph` LSP enabled.
2. Enable `tailwind-language-server` for Ruby in Zed settings (order does not matter):

   ```json
   "Ruby": {
      "language_servers": [
        "tailwindcss-language-server",
        "solargraph",
        "!ruby-lsp",
        "..."
      ]
    }
   ``` 
3. Go to any Ruby file and attempt to format it.
4. Nothing happens.
5. Open settings again and disable `tailwindcss-language-server` LSP.
6. Restart language servers.
7. Try to format the file again. The file will be formatted.

### Environment

Zed: v0.141.0 (Zed Dev cfbf5dca7a8abe6286ca94a3a03a079f77e2869a)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by vitallium** [comment]
Not sure but I think when Zed registers LSP servers for languages it sets the `tailwindcss-language-server` as the primary LSP: https://github.com/vitallium/zed/blob/cfbf5dca7a8abe6286ca94a3a03a079f77e2869a/crates/languages/src/lib.rs#L191

`languages.register_available_lsp_adapter` calls the ctor of `CachedLspAdapter` and passes the `is_primary` param as `true`.

**Comment by vitallium** [comment]
I found this issue https://github.com/zed-industries/zed/issues/11288 which seems pretty much about the same problem as I described here. I think we can close this one in favor of #11288.

**Comment by drale2k** [comment]
Given this a little bump. Has been over a month now that we are not able to format on save using Ruby / Rails. Any update on this 🙏🏻

**Comment by vitallium** [comment]
Closing this issue as I think my configuration is wrong for `tailwind`. The `tailwind` LSP should not be in the `language_servers` list. The correct configuration is the following:

```
"tailwindcss-language-server": {
  "includeLanguages": {
    "erb": "html",
    "ruby": "html"
  },
  "experimental": {
    "classRegex": ["\\bclass:\\s*'([^']*)'"]
  }
}
```
