### ISSUE TITLE
Documentation tests are failed but ignored by running Nextest in CI workflow

### ISSUE THREAD

**Issue by qianyan** [zed-industries/zed#12983]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There are some documentation tests failed when I followed the instructions `cargo test --workspace` of *macos.md*.  For example
1. line 45-46 in *crates/gpui_macos/src/gpui_macos.rs* fails without declaring `dev-dependencies` in its *Cargo.toml*.
```
/// #[gpui::test]
/// async fn test_foo(mut cx: &TestAppContext) { }
```

2. line 62-66 in *crates/ui/src/components/label/label.rs* fails with the unexpected bool argument.
```
    /// ```
    /// use ui::prelude::*;
    ///
    /// let my_label = Label::new("Hello, World!").single_line(true);
    /// ```
    pub fn single_line(mut self) -> Self {
        self.single_line = true;
        self
    }
```

### Environment

Zed: v0.141.0 (Zed Dev 0a13b9ee01ef34d1e06fb5f47c73aefd3c74707f)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
This should be fixed by https://github.com/zed-industries/zed/pull/12985 and https://github.com/zed-industries/zed/pull/13015.
