### ISSUE TITLE
vim: Cannot use % to jump to matching tag

### ISSUE THREAD

**Issue by sadiksaifi** [zed-industries/zed#12986]
### Check for existing issues

- [X] Completed

### Describe the feature

When working with .jsx, .tsx, .html and etc files, the Shift + 5 keybinding does not jump between open and closing HTML/JSX tags although it works for brackets. This keybinding is expected to help navigate between matching pairs of tags but fails to do so.

> Steps to Reproduce:

1. Open any .jsx, .tsx, or .html file in Vim.
2. Place the cursor on an opening or closing HTML/JSX tag.
3. Press Shift + %.
4. Expected Behavior:
5. The cursor should jump to the matching closing or opening tag.

> Actual Behavior:
- No navigation occurs, or the cursor jumps incorrectly.

Additional Information:
I have attached a video as well for more info, and this video is of Neovim 0.9 with tsserver lsp.

Zed version: 0.139.3
OS: MacOS Sonoma 14.5

> If you guys fix, I am sold for Zed!

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/86684667/1378edb0-4a37-40e0-965f-77aa12687faa

**Comment by sadiksaifi** [comment]
@ConradIrwin has looked at the issue or not ?

**Comment by ConradIrwin** [comment]
Not yet! If you want to pair with me on a fix: https://calendly.com/conradirwin/pairing

**Comment by sadiksaifi** [comment]
@ConradIrwin I would have love to help you but I don't have enough rust knowledge

**Comment by sadiksaifi** [comment]
@ConradIrwin @as-cii @maxbrunsfeld @nathansobo 
Guys I know there would have been other important issues/feature which would be more important than this issue/feature but this is the only one which is stopping me to completely to zed. 
I am open for any help to get this issue resolved, it's just that I don't know enough rust to fix this issue. I am still learning.

**Comment by davidreuss** [comment]
is it feasible to support this feature in a generic way, where you want to jump between matching `{`, `(` and `]`, without it being powered by tree sitter queries? so it would work in any file out of the box like vim for instance?

or is there an existing way to solve that problem with current zed features?

**Comment by aaronmahlke** [comment]
I know this issue is already resolved, but I wanted to note that this same functionality would be valuable for ⁠.vue files as well.
Here the ⁠% tag navigation only works one-way - can jump down from opening to closing tags, but not back up.

https://github.com/user-attachments/assets/f4e3c49d-ef86-486c-9a5f-bb750c3374fa

**Comment by tannersltwtr** [comment]
This feature doesn't work in all files, especially if its nested inside of something like quotes, etc. This should probably be reopened as its too inconsistent currently.

**Comment by ConradIrwin** [comment]
@tannersltwtr can you please open a new issue with the specific problems you're seeing.

**Comment by ConradIrwin** [comment]
@aaronmahlke https://github.com/zed-extensions/vue/pull/15 should fix vue
