### ISSUE TITLE
ESLint rules get put inline on save

### ISSUE THREAD

**Issue by tance77** [zed-industries/zed#12997]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When saving and eslint runs rules get put inline as comment in the wrong programming language. 

It shouldn't put the rule in as a comment at all, but it also inserts it as the wrong type of comment for HTML

`settings.json`
```json
{
  "tab_size": 2,
  "theme": "Ayu Mirage",
  "base_keymap": "JetBrains",
  "buffer_font_size": 15,
  "buffer_font_family": "MonoLisa",
  "indent_guides": {
    "enabled": true,
    "coloring": "indent_aware"
  },
  "hour_format": "hour12",
  "languages": {
    "Vue.js": {
      "use_autoclose": true,
      "tab_size": 4,
      "remove_trailing_whitespace_on_save": true,
      "preferred_line_length": 1000,
      "soft_wrap": "none",
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true,
          "source.organizeImports": true
        }
      }
    },
    "JavaScript": {
      "use_autoclose": true,
      "tab_size": 4,
      "remove_trailing_whitespace_on_save": true,
      "preferred_line_length": 1000,
      "soft_wrap": "none",
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true,
          "source.organizeImports": true
        }
      }
    },
    "TypeScript": {
      "use_autoclose": true,
      "tab_size": 4,
      "remove_trailing_whitespace_on_save": true,
      "preferred_line_length": 1000,
      "soft_wrap": "none",
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true,
          "source.organizeImports": true
        }
      }
    }
  }
}
```

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

It only does it with the on save function. If i use the editors fix all problems automatically everything is fine
![Screenshot 2024-06-13 at 11 16 47 AM](https://github.com/zed-industries/zed/assets/3421501/db6761a9-eeaa-44e1-8180-1f687b3fc9f8)

![Screen Recording 2024-06-13 at 11 20 48 AM](https://github.com/zed-industries/zed/assets/3421501/e9979033-18ee-4465-998b-35065b64b9ee)

This is a vue file and puts a rule in when it shouldn't put any rule in. Even worse it puts it in as a comment but html doesn't support comments with // it needs 

So I end up with rules in my preview on the HTML page.

**Comment by tance77** [comment]
Any progress on this? This is very frustrating fighting with the comments being put in.  Loving the IDE so far.

**Comment by mrnugget** [comment]
Do you have an example configuration for ESLint/Prettier/... to reproduce this?

**Comment by tance77** [comment]
@mrnugget 
```js
/* eslint-env node */
require('@rushstack/eslint-patch/modern-module-resolution');

module.exports = {
  root: true,
  extends: ['plugin:vue/vue3-essential', 'plugin:vue/vue3-recommended', 'plugin:vue/vue3-strongly-recommended', 'eslint:recommended', '@vue/eslint-config-typescript', '@vue/eslint-config-prettier'],
  parserOptions: {
    ecmaVersion: 'latest',
  },
  rules: {
    'array-callback-return': [
      'error',
      {
        // 允许隐式
        allowImplicit: true,
      },
    ],
    'space-before-function-paren': 0,
    'no-console': 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    'vue/multi-word-component-names': 'off',
    'prettier/prettier': [
      'error',
      {
        trailingComma: 'es5',
        singleQuote: true,
        semi: true,
        tabWidth: 2,
        useTabs: false,
        vueIndentScriptAndStyle: true,
        printWidth: 1000,
        singleAttributePerLine: false,
      },
    ],
  },
};

```

**Comment by mrnugget** [comment]
Do you also have an [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for how to reproduce it? I fear that the `package.json` is as important as the ESLint configuration.

**Comment by tance77** [comment]
I am having trouble reproducing it now. Maybe a recent update fixed it?

**Comment by grzegorzkiselev** [comment]
@mrnugget 
I have the same problem. I found out that it is triggered by the source.organizeImports or source.AddMissingImports options.

Here is repository with minimal example and video demonstration:
https://github.com/grzegorzkiselev/zed-disable-rules-bug-demo

**Comment by mrnugget** [comment]
Thanks @grzegorzkiselev. Yeah, that also came up in this thread: https://github.com/zed-industries/zed/issues/13633#issuecomment-2210671815

I still don't understand how to influence that behaviour.

**Comment by grzegorzkiselev** [comment]
@mrnugget Could this be related to the globally installed version of eslint or typescript? Or with the @typescript-eslint plugin?

I migrated to eslint 9.7.0 and the problem went away.

**Comment by mrnugget** [comment]
Interesting!! So you upgraded in your local project?

**Comment by grzegorzkiselev** [comment]
This was a mistake. At first the error actually went away, but then it came back again, so it’s not a problem with version of eslint or typescript, and not with their global installation.

It seems that there is a module that is responsible for managing imports, and it somehow conflicts with existing lsps.

I did not find information on whose help import management is organized. Is this a prettier plugin? It works even if 
```json
"prettier": {
    "allowed": false
  },
```
 is set in the configuration

**Comment by mrnugget** [comment]
> I did not find information on whose help import management is organized. Is this a prettier plugin? It works even if

Depends on what you have configured. Do you have a stock Zed configuration?
