### ISSUE TITLE
When the GitHub workflow is called deploy.yml, yaml-schema reports errors

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#12999]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In your project create a file called `.github/workflows/deploy.yml`. Zed recognizes that this is a GitHub workflow, hovering over fields gives you description of what they represent, but it also recognizes it as something called the "Deployer Recipe", reporting all of the fields as disallowed.

Rename the workflow file to something else, and the errors are gone.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-06-13 at 20 52 58](https://github.com/zed-industries/zed/assets/471278/5a788a3c-b6ff-48f3-a5fd-6db0cd070ba0)

**Comment by notpeter** [comment]
Related: 
- https://github.com/redhat-developer/vscode-yaml/issues/640

**Comment by AlexDaniel** [comment]
Is there any other workaround, besides renaming the file?

**Comment by RemiBardon** [comment]
I have the same problem with `network-config.yaml`: `yaml-schema: Landing Zone Accelerator on AWS - Network Config: Property version is not allowed.` That's frustrating.

**Comment by RemiBardon** [comment]
Workarounds:

1. Add `# yaml-language-server: $schema=<SCHEMA_URL>` at the beginning of your YAML file. See [redhat-developer/yaml-language-server > Using inlined schema](https://github.com/redhat-developer/yaml-language-server?tab=readme-ov-file#using-inlined-schema) for more information.
2. When https://github.com/zed-industries/zed/issues/7636 will be resolved, you'll be able to add the following in Zed settings:

   ```json
   "lsp": {
     "yaml-language-server": {
       "initialization_options": {
         "yaml.schemas": {
           "<SCHEMA_URL>": "<YAML_FILES_GLOB>"
         }
       }
     }
   }
   ```

   See [@mikeymop's comment](https://github.com/zed-industries/zed/issues/7636#issuecomment-2241285179) and [redhat-developer/yaml-language-server > More examples of schema association](https://github.com/redhat-developer/yaml-language-server?tab=readme-ov-file#more-examples-of-schema-association) for more information.

**Comment by RemiBardon** [comment]
@AlexDaniel ping

**Comment by notpeter** [comment]
Hey folks, I've merged a fix for https://github.com/zed-industries/zed/issues/7636 in https://github.com/zed-industries/zed/pull/17479. This will be available in Zed Preview on Wednesday 2024-09-11 and Zed Stable a week later.

I've updated the [Zed YAML Language Docs](https://zed.dev/docs/languages/yaml) and 
@RemiBardon's workarounds are correct.  Anyone who runs into this today can specify a schema in a modeline comment at the top of their yaml file. For example:
```json
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ...
```

One #17479 lands you will also be able to do this in your settings:
```json
  "lsp": {
    "yaml-language-server": {
      "initialization_options": {
        "yaml": {
          "schemas": {
            "https://json.schemastore.org/github-workflow": "tasks/*.yml"
          },
        }
      }
    }
  }
```

Thanks for reporting and happy YAMLing.
