### ISSUE TITLE
[Vim] Odd Visual Selection Behavior on Last 2 Lines of Buffer

### ISSUE THREAD

**Issue by garrett-hopper** [zed-industries/zed#13005]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Attaching a recording to try to demonstrate some of the odd behaviors I'm seeing.
Mostly related to the last two lines not behaving the same as other lines when using Vim mode and visual selections.

https://github.com/zed-industries/zed/assets/3629343/a7d927b6-e4c9-43c7-8f9a-eb0395e84826

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 96 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I think this is the same behavior as the behavior reported here:

- https://github.com/zed-industries/zed/issues/6900

Please 👍 that issue to help with our prioritization queue.

**Comment by garrett-hopper** [comment]
My bad; should've spent more time searching. Thanks!
