### ISSUE TITLE
Eslint formatter inserting invalid syntax

### ISSUE THREAD

**Issue by yHSJ** [zed-industries/zed#13001]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using formatting, Eslint is replacing `any` with a long string of `unknown` and `never`.

![gif](https://github.com/zed-industries/zed/assets/79121297/a391c217-4b95-432d-bf71-878cee210624)

`settings.json`
```json
{
  "base_keymap": "VSCode",
  "theme": "Ayu Mirage",
  "ui_font_size": 14,
  "buffer_font_size": 14,
  "languages": {
    "TypeScript": {
      "code_actions_on_format": {
        "source.organizeImports": true,
        "source.fixAll.eslint": true
      }
    }
  }
}

```

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
@yHSJ Eek! That looks bad! Can you provide a snippet that triggers this behavior?

**Comment by yHSJ** [comment]
@notpeter, Interestingly, I can't seem to reproduce this behavior now. I reproduced the environment to the best of my ability, but have not seen the same behavior. 

I suppose we can close the issue as I can't reproduce.
