### ISSUE TITLE
Linux (Ubuntu) build fails: /usr/bin/ld: cannot find -lstdc++

### ISSUE THREAD

**Issue by curiousercreative** [zed-industries/zed#13020]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Building from source on Ubuntu 22.04 (Pop!_OS 22.04)  yields error
>/usr/bin/ld: cannot find -lstdc++: No such file or directory
>clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Environment

Zed: v0.140.0 (Zed Dev 1914a42b1c4cf6203ed3e33efe5e64a74c3b404c)
OS: Linux 1.0.0
Memory: 31.2 GiB
Architecture: x86_64

```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by curiousercreative** [comment]
Fixed by https://github.com/zed-industries/zed/commit/ce51c264a631ce9078162028c9ad8df11c60af93

**Comment by ranghetto** [comment]
I tried with v0.140.5 but this is still an issue
```  
= note: clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
          mold: fatal: library not found: gcc_s
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `libc` (build script) due to 1 previous error
```
