### ISSUE TITLE
fail to setup openai compatible assistant

### ISSUE THREAD

**Issue by 4t8dd** [zed-industries/zed#13033]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I setup a api which is compatible to openai api. But I can not get it run after config. I have error: fail to connect the server"

### Environment

Mac latest.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

![Screenshot 2024-06-14 at 3 22 52 PM](https://github.com/zed-industries/zed/assets/66897975/63e66291-9638-4730-a981-7bf530436008)

see the log above.

**Comment by notpeter** [comment]
Can you provide some additional context to help us reproduce your issue? Name of model/service, relevant lines from your config.json, etc.

**Comment by JosephTLyons** [comment]
Going to close this issue out. If you are still running into this issue in the most recent version of Zed, feel free to open a new issue with the details requested by @notpeter.
