### ISSUE TITLE
Low contrast on changed and selected entries in the file tree (One Light theme)

### ISSUE THREAD

**Issue by nathanael-ruf** [zed-industries/zed#13032]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Low contrast -> hard to read

### Environment

Zed: v0.140.2 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-06-14 at 09 07 46](https://github.com/zed-industries/zed/assets/104262550/ea9e347c-61d2-49a5-9129-89629907c763)

**Comment by nilskch** [comment]
Wanted to create the same issue. This is very annoying.
