### ISSUE TITLE
[install-linux] Misleading documentation

### ISSUE THREAD

**Issue by ntk148v** [zed-industries/zed#13031]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi all,

I've followed the documentation about [installing development build](https://github.com/zed-industries/zed/blob/main/docs/src/development/linux.md#installing-a-development-build) in order to install zed to system-wide `/usr`:

```shell
./scripts/install-linux /usr
```

But it failed every time, turn out that the [install-linux](https://github.com/zed-industries/zed/blob/main/script/install-linux#L5) doesn't accept any arguments.

### Environment

Ubuntu 22.04

**Comment by notpeter** [comment]
Yep. Looks like the instructions in linux.md don't match the capabilities of script/install-linux

https://github.com/zed-industries/zed/blob/0f596071007d040bf5e6415c70a65e8050ed1261/docs/src/development/linux.md?plain=1#L71-L75

https://github.com/zed-industries/zed/blob/0f596071007d040bf5e6415c70a65e8050ed1261/script/install-linux#L5-L13

**Comment by notpeter** [comment]
This has been fixed in the docs:
https://github.com/zed-industries/zed/blob/50069a215376eb369554eefc0875719949309b38/docs/src/development/linux.md?plain=1#L60-L67
