### ISSUE TITLE
GitHub avatars not showing for hidden emails

### ISSUE THREAD

**Issue by eproxus** [zed-industries/zed#13045]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a  repo with commits from either yourself or a user who has hidden their email address and view commits (either by hovering an inline blame or the blame gutter).
2. See no avatars

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

There are two types of problematic users:
1. Yourself (using your own email, but which is not publicly visible)
2. Others who have hidden their email

Case (2) might be easy to support avatars for, since the email is of the form `<randomnumber>+<github-username>@users.noreply.github.com` and thus the public username can easily be extracted from from the private address.

Case (1) is perhaps trickier, since it usually has your normal email (e.g. `John Smith <john.smith@example.com>`) and there is no way to know if this email is associated with a GitHub profile.

**Comment by notpeter** [comment]
I'm going to close this in favor of:
- https://github.com/zed-industries/zed/issues/20188
- https://github.com/zed-industries/zed/issues/19207

Thanks for reporting.
