### ISSUE TITLE
Cancel specific selection of multiple cursors

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#13058]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to be able to cancel / unselect specific selection in case I have multiple cursors in the editor by pressing something like `alt-click` on a particular selection.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/316790b4-d325-43ef-ac34-8d462ab05d9f

**Comment by mikayla-maki** [comment]
I think alt-click being a toggle would be pretty intuitive

**Comment by Moshyfawn** [comment]
> I think alt-click being a toggle would be pretty intuitive

Oh, totally! That's what I meant when I screwed up left and right again 🤭
