### ISSUE TITLE
`script/generate-licenses` builds `cargo-about` twice

### ISSUE THREAD

**Issue by Aeledfyr** [zed-industries/zed#13075]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `generate-licenses` script installs `cargo-about` twice; first, if the version is not `0.6.1`, it installs that version (`cargo-about@0.6.1`); then it runs `cargo install cargo-about`, which updates it to the latest version (which is currently `0.6.2`).

https://github.com/zed-industries/zed/blob/d5a6ca4914b5f009223df99a57cd799f2af4b470/script/generate-licenses#L17-L21

The second `cargo install` was unintentionally added in https://github.com/zed-industries/zed/pull/12961.

Since the pinned version and the latest version don't match, this will always force two full builds of `cargo-about`.

If the goal is just to have a recent version of `cargo-about`, then the version check should probably be removed, since `cargo install` will auto-update to the latest version if an older version is currently installed.

### Environment

Zed: v0.141.0 (Zed Dev 124878878069a0aa52e97e531fef22fbef43e12f)
Architecture: x86_64

**Comment by maxdeviant** [comment]
@Aeledfyr Thanks for flagging!

This has been fixed on `main`.

**Comment by Aeledfyr** [comment]
Thank you!
