### ISSUE TITLE
Search field is not wide enough

### ISSUE THREAD

**Issue by ZombieHarvester** [zed-industries/zed#13099]
### Check for existing issues

- [X] Completed

### Describe the feature

I have been doing a lot of search and replace in my project using regex and noticed that the search field is quite narrow and the pattern doesn't fit in it, making me scroll back and forth. 

There is a lot of empty space on the right, the field could probably be screen width just like in Sublime Text.

My search pattern doesn't fit
![image](https://github.com/zed-industries/zed/assets/923510/53d8d781-5435-44c0-b29a-2c819a1ce853)

A lot of unused space on the right
![image](https://github.com/zed-industries/zed/assets/923510/41de74fe-9029-4782-90e1-20b2e15f8ab2)

Sublime Text has screen width fields
![image](https://github.com/zed-industries/zed/assets/923510/97ba9fcb-d578-480d-b168-fbdeef6eed1d)

Thanks! I love Zed

**Comment by hollermay** [comment]
I can work on this
