### ISSUE TITLE
add Gotham theme to the list of built-in themes

### ISSUE THREAD

**Issue by Solarunit** [zed-industries/zed#13101]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have Gotham (very dark) theme in the list of built-in themes.

Gotham project page: https://github.com/whatyouhide/vim-gotham

Screenshot:

![](https://user-images.githubusercontent.com/3890250/206901895-954841ad-ea49-4c27-8206-1ef8aa55637c.png)

It looks pretty cool, and I use it in other apps already, so I want to see it in Zed too.

**Comment by Moshyfawn** [comment]
I believe the team is not looking to expand the list of built-in themes at this time. At this point, I'd advise [putting a request](https://github.com/zed-industries/extensions/issues/new?assignees=&labels=theme&projects=&template=0_theme_request.yml&title=%3Cname_of_theme%3E) to the community in [the `extensions` repo](https://github.com/zed-industries/extensions) to create a theme port for Zed.

However, I'll leave the topic open for other team members to chime in.

**Comment by maxdeviant** [comment]
> I believe the team is not looking to expand the list of built-in themes at this time. At this point, I'd advise [putting a request](https://github.com/zed-industries/extensions/issues/new?assignees=&labels=theme&projects=&template=0_theme_request.yml&title=%3Cname_of_theme%3E) to the community in [the `extensions` repo](https://github.com/zed-industries/extensions) to create a theme port for Zed.
> 
> However, I'll leave the topic open for other team members to chime in.

That is correct, we're not looking to provide any more built-in themes at this time.

New themes should be provided by extensions.
