### ISSUE TITLE
LSP can not work

### ISSUE THREAD

**Issue by miller-star** [zed-industries/zed#13118]
### Check for existing issues

- [X] Completed

### Describe the feature

[settings.json](https://github.com/user-attachments/files/15860623/settings.json)

lsp can not work

https://github.com/zed-industries/zed/assets/45729654/0cd34743-ddf3-47d6-8b9c-ae774c6824a7

**Comment by 0x2CA** [comment]
I don't see how the video has anything to do with vim, it seems to be about lsp not working resulting in not being able to jump to the implementation of the

**Comment by notpeter** [comment]
It looks like you are clicking "Go to Implementation" and the currently selected line is the implementation.  Can you try "Find All References" and see if that's the behavior you're looking for?

**Comment by miller-star** [comment]
> It looks like you are clicking "Go to Implementation" and the currently selected line is the implementation. Can you try "Find All References" and see if that's the behavior you're looking for?

the currently selected line is not the implementation
here is the implementation
<img width="679" alt="image" src="https://github.com/zed-industries/zed/assets/45729654/8d70ad7f-259e-4742-ab08-8c41ed819210">
I can not jump to the reference via "Go to Implementation", can only jump to the reference via "Find All References"(show in the video)

**Comment by notpeter** [comment]
> the currently selected line is not the implementation
> here is the implementation

No. The `func ReleaseToken(user model.User) (string, error) {}` block is the implementation of the function.  This is where the function is implemented.

The screenshot which you think is the implementation is instead the locations which reference that function. (Find All References).  If you were to right click on `ReleaseToken` on the `common.ReleaseToken(user)` lines and select "Go to Implementation" it would jump you to the implementation of that function (line 17).

I think this is just a language/translation issue.

In the future, please be sure to include a subject and description which describe what's actually occurring and what you expect to occur. Posting "lsp can not work" with a screen recording isn't enough.

**Comment by miller-star** [comment]
> > the currently selected line is not the implementation
> > here is the implementation
> 
> No. The `func ReleaseToken(user model.User) (string, error) {}` block is the implementation of the function. This is where the function is implemented.
> 
> The screenshot which you think is the implementation is instead the locations which reference that function. (Find All References). If you were to right click on `ReleaseToken` on the `common.ReleaseToken(user)` lines and select "Go to Implementation" it would jump you to the implementation of that function (line 17).
> 
> I think this is just a language/translation issue.
> 
> In the future, please be sure to include a subject and description which describe what's actually occurring and what you expect to occur. Posting "lsp can not work" with a screen recording isn't enough.

Thanks for your answer. I will describe the issue in detail in the future.
