### ISSUE TITLE
Windows - Zed: Massive memory spike when open Terminal

### ISSUE THREAD

**Issue by vinhphm** [zed-industries/zed#13123]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When running without open terminal panel, Zed takes around 330MB of memory.
But then if you open the terminal panel, it spikes to 3GB of memory.

### Environment

Zed: v0.141.0 (Zed Dev 15d3e54ae3ac0e0e9256cdebfd41d9e38e6cb7eb)
OS: Windows 10.0.22621
Memory: 15.7 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
There is also a jump in memory usage on MacOS (300MB -> 700MB; +400MB) but a Windows spike of ~2700MB seems not right.

Thanks for reporting.

**Comment by vinhphm** [comment]
I notice it can happen very randomly and not just due to terminal.
Here is the log file if it can help.
[Zed.log](https://github.com/user-attachments/files/15879919/Zed.log)

**Comment by notpeter** [comment]
I'm going to close this as unactionable as it's not something I am able to reproduce.
Thanks for reporting.
