### ISSUE TITLE
Extract Method/Variable support

### ISSUE THREAD

**Issue by chen-yan** [zed-industries/zed#13124]
### Check for existing issues

- [X] Completed

### Describe the feature

Can we support extract method or variable like jetbrains's IDE ?  It's useful for refactoring.

**Comment by SomeoneToIgnore** [comment]
Only if the corresponding LSP server supports that, e.g. rust-analyzer that proposes it via quick actions:
![image](https://github.com/zed-industries/zed/assets/2690773/a58eca37-67f5-4427-9bdd-8e9579a47cc3)

Zed per se is not very familiar with `method` or `variable` concepts and for sure is unaware of the language semantics to perform any kinds of extractions.

**Comment by chen-yan** [comment]
Thanks for replying, It works after updated LSP configuration.

**Comment by chen-yan** [comment]
> Would you mind sharing the language name, the server name and the extra configuration needed? https://github.com/zed-industries/zed/tree/main/docs/src/languages could benefit from more instructions, or maybe we could improve Zed defaults for that.

`"lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "features": "all"
        }
      }
    }
  }`

In configure file add rust-analyzer. I think it should configured as default. BTW, it's good to have shotcut like ( cmd+opt+m for method, cmd+opt+c for const, cmd+opt+v for variable) and have right mouse menu while code selcted.  Rightnow, I can only click the flash button on left bar.
<img width="716" alt="截屏2024-06-17 15 09 02" src="https://github.com/zed-industries/zed/assets/2889354/9bfa4420-5a47-4259-929a-a9943b850438">

**Comment by SomeoneToIgnore** [comment]
Ok, for r-a, there's no extra configuration should be needed indeed.

>  Rightnow, I can only click the flash button on left bar.

As for the keybinding, there's a `cmd-.` (same as in VSCode IIRC) to open all available actions for the current caret.
