### ISSUE TITLE
Icon Assistant panel

### ISSUE THREAD

**Issue by Johjoh-6** [zed-industries/zed#13125]
### Check for existing issues

- [X] Completed

### Describe the feature

With the last update, the assistant panel icon changed. But not in the sidebar.
A simple fix.

### new icon
<img width="175" alt="Screenshot 2024-06-17 at 08 41 33" src="https://github.com/zed-industries/zed/assets/74215632/2cb457cd-4750-4284-9280-4980f3a25b21">

### icon in the sidebar
<img width="480" alt="Screenshot 2024-06-17 at 08 42 08" src="https://github.com/zed-industries/zed/assets/74215632/ecd8607a-7486-461d-95a8-b8e7c26c7289">

It's still the previous one.

**Comment by maxdeviant** [comment]
This was fixed in #12787.
