### ISSUE TITLE
Check git differences on files

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#13136]
### Check for existing issues

- [X] Completed

### Describe the feature

It is not possible to close the view that shows the difference between how it was before and how now, as happens on vscode.

Zed:

https://github.com/zed-industries/zed/assets/20476002/a11bfdb4-a3b4-4d34-8e47-4957f288c5ef

Vscode:

https://github.com/zed-industries/zed/assets/20476002/1e994dc6-8699-4aab-9c82-19f7c60896d1

**Comment by evrensen467** [comment]
?

**Comment by SomeoneToIgnore** [comment]
What exactly is off and what does this issue want to be done?

**Comment by evrensen467** [comment]
You can use the ``esc`` key to toggle it off, likewise how you toggle off inline diagnostics, etc..

**Comment by SomeoneToIgnore** [comment]
@Angelk90 , please spend a bit more time next time and submit a similar textual description in the future issues.

Besides `esc` that will hide all diff hunks expansions, there's also an `editor: toggle hunk diff` action 
![image](https://github.com/zed-industries/zed/assets/2690773/65189197-1121-4e6b-b7ef-9cff9584ee4a)

and a https://github.com/zed-industries/zed/issues/12404 issue to improve the current, poor, discoverability, so I'll close this one as a duplicate.
