### ISSUE TITLE
Replace Functionality not working correctly if the filename or path contains a square bracket

### ISSUE THREAD

**Issue by FubyCoder** [zed-industries/zed#13131]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

How to reproduce:

Have a file where its filename or path contains a square bracket, use the replace functionality (F2 keyboard shortcut) to rename a function

After you confirm the replace you'll get a new file that replaces square brackets but provides instead %5B for [ and %5D for ]

[Screencast from 2024-06-17 11-23-33.webm](https://github.com/zed-industries/zed/assets/61201884/5c6032fa-a1cd-4d1b-96f1-9363319a8b5a)

### Environment

Zed Version: Zed from main branch (4855da53dfa62791d9dd102b9db9cf7ddb08d153)
OS: Linux ZorinOs (17.1)
Memory: 32GB 
CPU: AMD 5900x
GPU: NVDIA RTX 3090
Windowing System : x11

<details><summary>System Info</summary>
<pre>
(i used lshw command if you know something that is shorter and provides the same info let me know): 

description: Desktop Computer
    product: System Product Name (SKU)
    vendor: ASUS
    version: System Version
    serial: System Serial Number
    width: 64 bits
    capabilities: smbios-3.3.0 dmi-3.3.0 smp vsyscall32
    configuration: boot=normal chassis=desktop family=To be filled by O.E.M. sku=SKU uuid=da991415-94b0-b3ed-78ba-244bfee04962
  *-core
       description: Motherboard
       product: ROG STRIX B550-E GAMING
       vendor: ASUSTeK COMPUTER INC.
       physical id: 0
       version: Rev X.0x
       serial: 200772087901421
       slot: Default string
     *-firmware
          description: BIOS
          vendor: American Megatrends Inc.
          physical id: 0
          version: 2006
          date: 03/19/2021
          size: 64KiB
          capacity: 16MiB
          capabilities: pci apm upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer acpi usb biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: 2f
          slot: System board or motherboard
          size: 32GiB
        *-bank:0
             description: [empty]
             product: Unknown
             vendor: Unknown
             physical id: 0
             serial: Unknown
             slot: DIMM_A1
        *-bank:1
             description: DIMM DDR4 Synchronous Unbuffered (Unregistered) 3600 MHz (0,3 ns)
             product: CMK32GX4M2D3600C18
             vendor: Corsair
             physical id: 1
             serial: 00000000
             slot: DIMM_A2
             size: 16GiB
             width: 64 bits
             clock: 3600MHz (0.3ns)
        *-bank:2
             description: [empty]
             product: Unknown
             vendor: Unknown
             physical id: 2
             serial: Unknown
             slot: DIMM_B1
        *-bank:3
             description: DIMM DDR4 Synchronous Unbuffered (Unregistered) 3600 MHz (0,3 ns)
             product: CMK32GX4M2D3600C18
             vendor: Corsair
             physical id: 3
             serial: 00000000
             slot: DIMM_B2
             size: 16GiB
             width: 64 bits
             clock: 3600MHz (0.3ns)
     *-cache:0
          description: L1 cache
          physical id: 32
          slot: L1 - Cache
          size: 768KiB
          capacity: 768KiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: 33
          slot: L2 - Cache
          size: 6MiB
          capacity: 6MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: 34
          slot: L3 - Cache
          size: 64MiB
          capacity: 64MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: AMD Ryzen 9 5900X 12-Core Processor
          vendor: Advanced Micro Devices [AMD]
          physical id: 35
          bus info: cpu@0
          version: 25.33.0
          serial: Unknown
          slot: AM4
          size: 2878MHz
          capacity: 4950MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm cpufreq
          configuration: cores=12 enabledcores=12 microcode=169873417 threads=24
     *-pci:0
          description: Host bridge
          product: Starship/Matisse Root Complex
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 00
          width: 32 bits
          clock: 33MHz
        *-generic UNCLAIMED
             description: IOMMU
             product: Starship/Matisse IOMMU
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 0.2
             bus info: pci@0000:00:00.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: msi ht cap_list
             configuration: latency=0
        *-pci:0
             description: PCI bridge
             product: Starship/Matisse GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 1.1
             bus info: pci@0000:00:01.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:26 memory:fca00000-fcafffff
           *-nvme
                description: NVMe device
                product: Samsung SSD 970 EVO Plus 2TB
                vendor: Samsung Electronics Co Ltd
                physical id: 0
                bus info: pci@0000:01:00.0
                logical name: /dev/nvme1
                version: 4B2QEXM7
                serial: S6P1NS0W322698M
                width: 64 bits
                clock: 33MHz
                capabilities: nvme pm msi pciexpress msix nvm_express bus_master cap_list
                configuration: driver=nvme latency=0 nqn=nqn.1994-11.com.samsung:nvme:980PRO:M.2:S6P1NS0W322698M state=live
                resources: irq:62 memory:fca00000-fca03fff
              *-namespace:0
                   description: NVMe disk
                   physical id: 0
                   logical name: hwmon1
              *-namespace:1
                   description: NVMe disk
                   physical id: 2
                   logical name: /dev/ng1n1
              *-namespace:2
                   description: NVMe disk
                   physical id: 1
                   bus info: nvme@1:1
                   logical name: /dev/nvme1n1
                   size: 1863GiB (2TB)
                   capabilities: gpt-1.00 partitioned partitioned:gpt
                   configuration: guid=bf4f28b4-1127-4532-a92b-d65a1d3c1ce9 logicalsectorsize=512 sectorsize=512 wwid=eui.0025385331414b6a
                 *-volume:0 UNCLAIMED
                      description: Windows FAT volume
                      vendor: mkfs.fat
                      physical id: 1
                      bus info: nvme@1:1,1
                      version: FAT32
                      serial: 6c24-0d6a
                      size: 1019MiB
                      capacity: 1021MiB
                      capabilities: boot fat initialized
                      configuration: FATs=2 filesystem=fat
                 *-volume:1
                      description: Windows FAT volume
                      vendor: mkfs.fat
                      physical id: 2
                      bus info: nvme@1:1,2
                      logical name: /dev/nvme1n1p2
                      version: FAT32
                      serial: 6c24-0d6b
                      size: 4095MiB
                      capacity: 4095MiB
                      capabilities: fat initialized
                      configuration: FATs=2 filesystem=fat name=recovery
                 *-volume:2
                      description: EXT4 volume
                      vendor: Linux
                      physical id: 3
                      bus info: nvme@1:1,3
                      logical name: /dev/nvme1n1p3
                      logical name: /
                      version: 1.0
                      serial: 67c48de4-db20-4914-bad3-8893435fb7ca
                      size: 1858GiB
                      capabilities: journaled extended_attributes large_files huge_files dir_nlink recover 64bit extents ext4 ext2 initialized
                      configuration: created=2024-02-10 16:33:05 filesystem=ext4 lastmountpoint=/ modified=2024-06-17 09:47:40 mount.fstype=ext4 mount.options=rw,relatime,errors=remount-ro mounted=2024-06-17 09:47:41 state=mounted
        *-pci:1
             description: PCI bridge
             product: Starship/Matisse GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 1.2
             bus info: pci@0000:00:01.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:27 memory:fc200000-fc6fffff
           *-usb
                description: USB controller
                product: Advanced Micro Devices, Inc. [AMD]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:02:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: msi msix pm pciexpress xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:33 memory:fc6a0000-fc6a7fff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.5.0-28-generic xhci-hcd
                   physical id: 0
                   bus info: usb@1
                   logical name: usb1
                   version: 6.05
                   capabilities: usb-2.00
                   configuration: driver=hub slots=10 speed=480Mbit/s
                 *-usb:0
                      description: Bluetooth wireless interface
                      product: AX200 Bluetooth
                      vendor: Intel Corp.
                      physical id: 5
                      bus info: usb@1:5
                      version: 0.01
                      capabilities: bluetooth usb-2.01
                      configuration: driver=btusb maxpower=100mA speed=12Mbit/s
                 *-usb:1
                      description: Human interface device
                      product: AURA LED Controller
                      vendor: AsusTek Computer Inc.
                      physical id: 6
                      bus info: usb@1:6
                      version: 1.00
                      serial: 9876543210
                      capabilities: usb-2.00
                      configuration: driver=usbhid maxpower=16mA speed=12Mbit/s
                 *-usb:2
                      description: USB hub
                      product: USB2.0 Hub
                      vendor: Genesys Logic, Inc.
                      physical id: 7
                      bus info: usb@1:7
                      version: 60.60
                      capabilities: usb-2.00
                      configuration: driver=hub maxpower=100mA slots=4 speed=480Mbit/s
                    *-usb
                         description: Mouse
                         product: Logitech Gaming Mouse G402 Keyboard
                         vendor: Logitech
                         physical id: 4
                         bus info: usb@1:7.4
                         logical name: input13
                         logical name: /dev/input/event8
                         logical name: /dev/input/mouse1
                         logical name: input14
                         logical name: /dev/input/event9
                         version: 90.03
                         serial: 4975576C3830
                         capabilities: usb-2.00 usb
                         configuration: driver=usbhid maxpower=300mA speed=12Mbit/s
                 *-usb:3
                      description: USB hub
                      product: USB2.0 Hub
                      vendor: Genesys Logic, Inc.
                      physical id: 9
                      bus info: usb@1:9
                      version: 60.60
                      capabilities: usb-2.00
                      configuration: driver=hub maxpower=100mA slots=4 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.5.0-28-generic xhci-hcd
                   physical id: 1
                   bus info: usb@2
                   logical name: usb2
                   version: 6.05
                   capabilities: usb-3.10
                   configuration: driver=hub slots=4 speed=10000Mbit/s
           *-sata
                description: SATA controller
                product: Advanced Micro Devices, Inc. [AMD]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.1
                bus info: pci@0000:02:00.1
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: sata msi pm pciexpress ahci_1.0 bus_master cap_list rom
                configuration: driver=ahci latency=0
                resources: irq:39 memory:fc680000-fc69ffff memory:fc600000-fc67ffff
           *-pci
                description: PCI bridge
                product: Advanced Micro Devices, Inc. [AMD]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.2
                bus info: pci@0000:02:00.2
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pci msi pm pciexpress normal_decode bus_master cap_list
                configuration: driver=pcieport
                resources: irq:32 memory:fc200000-fc5fffff
              *-pci:0
                   description: PCI bridge
                   product: Advanced Micro Devices, Inc. [AMD]
                   vendor: Advanced Micro Devices, Inc. [AMD]
                   physical id: 0
                   bus info: pci@0000:03:00.0
                   version: 00
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci msi pm pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:34
              *-pci:1
                   description: PCI bridge
                   product: Advanced Micro Devices, Inc. [AMD]
                   vendor: Advanced Micro Devices, Inc. [AMD]
                   physical id: 4
                   bus info: pci@0000:03:04.0
                   version: 00
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci msi pm pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:35 memory:fc500000-fc5fffff
                 *-nvme
                      description: NVMe device
                      product: Samsung SSD 970 EVO Plus 2TB
                      vendor: Samsung Electronics Co Ltd
                      physical id: 0
                      bus info: pci@0000:05:00.0
                      logical name: /dev/nvme0
                      version: 2B2QEXM7
                      serial: S4J4NF0NA14700Z
                      width: 64 bits
                      clock: 33MHz
                      capabilities: nvme pm msi pciexpress msix nvm_express bus_master cap_list
                      configuration: driver=nvme latency=0 nqn=nqn.2014.08.org.nvmexpress:144d144dS4J4NF0NA14700Z     Samsung SSD 970 EVO Plus 2TB state=live
                      resources: irq:33 memory:fc500000-fc503fff
                    *-namespace:0
                         description: NVMe disk
                         physical id: 0
                         logical name: hwmon0
                    *-namespace:1
                         description: NVMe disk
                         physical id: 2
                         logical name: /dev/ng0n1
                    *-namespace:2
                         description: NVMe disk
                         physical id: 1
                         bus info: nvme@0:1
                         logical name: /dev/nvme0n1
                         size: 1863GiB (2TB)
                         capabilities: gpt-1.00 partitioned partitioned:gpt
                         configuration: guid=b106214e-3434-4aea-8cbc-d24129e81582 logicalsectorsize=512 sectorsize=512 wwid=eui.0025385a01b35424
                       *-volume:0
                            description: reserved partition
                            vendor: Windows
                            physical id: 1
                            bus info: nvme@0:1,1
                            logical name: /dev/nvme0n1p1
                            serial: 3d6b898b-e802-4df5-a88d-19ca104a9980
                            capacity: 15MiB
                            capabilities: nofs nomount
                            configuration: name=Microsoft reserved partition
                       *-volume:1
                            description: Windows NTFS volume
                            vendor: Windows
                            physical id: 2
                            bus info: nvme@0:1,2
                            logical name: /dev/nvme0n1p2
                            version: 3.1
                            serial: 68064a48-1a74-4840-82e4-0a13260adc08
                            size: 488GiB
                            capacity: 488GiB
                            capabilities: ntfs initialized
                            configuration: clustersize=4096 created=2024-01-19 22:33:34 filesystem=ntfs name=Basic data partition state=clean
                       *-volume:2
                            description: Windows NTFS volume
                            vendor: Windows
                            physical id: 3
                            bus info: nvme@0:1,3
                            logical name: /dev/nvme0n1p3
                            version: 3.1
                            serial: 10aa0034-5318-2c42-bd4f-a302973b331b
                            size: 1374GiB
                            capacity: 1374GiB
                            capabilities: ntfs initialized
                            configuration: clustersize=4096 created=2024-01-19 23:04:24 filesystem=ntfs label=Volume name=Basic data partition state=clean
              *-pci:2
                   description: PCI bridge
                   product: Advanced Micro Devices, Inc. [AMD]
                   vendor: Advanced Micro Devices, Inc. [AMD]
                   physical id: 8
                   bus info: pci@0000:03:08.0
                   version: 00
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci msi pm pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:36 memory:fc400000-fc4fffff
                 *-network DISABLED
                      description: Wireless interface
                      product: Wi-Fi 6 AX200
                      vendor: Intel Corporation
                      physical id: 0
                      bus info: pci@0000:06:00.0
                      logical name: wlp6s0
                      version: 1a
                      serial: ac:12:03:da:2d:a2
                      width: 64 bits
                      clock: 33MHz
                      capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical wireless
                      configuration: broadcast=yes driver=iwlwifi driverversion=6.5.0-28-generic firmware=77.2df8986f.0 cc-a0-77.ucode latency=0 link=no multicast=yes wireless=IEEE 802.11
                      resources: irq:33 memory:fc400000-fc403fff
              *-pci:3
                   description: PCI bridge
                   product: Advanced Micro Devices, Inc. [AMD]
                   vendor: Advanced Micro Devices, Inc. [AMD]
                   physical id: 9
                   bus info: pci@0000:03:09.0
                   version: 00
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci msi pm pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:38 memory:fc200000-fc3fffff
                 *-network
                      description: Ethernet interface
                      product: Ethernet Controller I225-V
                      vendor: Intel Corporation
                      physical id: 0
                      bus info: pci@0000:07:00.0
                      logical name: enp7s0
                      version: 02
                      serial: 24:4b:fe:e0:49:62
                      size: 1Gbit/s
                      capacity: 1Gbit/s
                      width: 32 bits
                      clock: 33MHz
                      capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                      configuration: autonegotiation=on broadcast=yes driver=igc driverversion=6.5.0-28-generic duplex=full firmware=1045:740 ip=192.168.1.253 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
                      resources: irq:37 memory:fc200000-fc2fffff memory:fc300000-fc303fff
        *-pci:2
             description: PCI bridge
             product: Starship/Matisse GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 3.1
             bus info: pci@0000:00:03.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:28 ioport:f000(size=4096) memory:fb000000-fc0fffff ioport:7000000000(size=34393292800)
           *-display
                description: VGA compatible controller
                product: GA102 [GeForce RTX 3090]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:08:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: iomemory:700-6ff iomemory:780-77f irq:152 memory:fb000000-fbffffff memory:7000000000-77ffffffff memory:7800000000-7801ffffff ioport:f000(size=128) memory:fc000000-fc07ffff
           *-multimedia
                description: Audio device
                product: GA102 High Definition Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:08:00.1
                logical name: card0
                logical name: /dev/snd/controlC0
                logical name: /dev/snd/hwC0D0
                logical name: /dev/snd/pcmC0D3p
                logical name: /dev/snd/pcmC0D7p
                logical name: /dev/snd/pcmC0D8p
                logical name: /dev/snd/pcmC0D9p
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:149 memory:fc080000-fc083fff
              *-input:0
                   product: HDA NVidia HDMI/DP,pcm=3
                   physical id: 0
                   logical name: input18
                   logical name: /dev/input/event11
              *-input:1
                   product: HDA NVidia HDMI/DP,pcm=7
                   physical id: 1
                   logical name: input19
                   logical name: /dev/input/event12
              *-input:2
                   product: HDA NVidia HDMI/DP,pcm=8
                   physical id: 2
                   logical name: input20
                   logical name: /dev/input/event13
              *-input:3
                   product: HDA NVidia HDMI/DP,pcm=9
                   physical id: 3
                   logical name: input21
                   logical name: /dev/input/event14
        *-pci:3
             description: PCI bridge
             product: Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 7.1
             bus info: pci@0000:00:07.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:30
           *-generic UNCLAIMED
                description: Non-Essential Instrumentation
                product: Starship/Matisse PCIe Dummy Function
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:09:00.0
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress cap_list
                configuration: latency=0
        *-pci:4
             description: PCI bridge
             product: Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.1
             bus info: pci@0000:00:08.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:31 memory:fc700000-fc9fffff
           *-generic:0 UNCLAIMED
                description: Non-Essential Instrumentation
                product: Starship/Matisse Reserved SPP
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:0a:00.0
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress cap_list
                configuration: latency=0
           *-generic:1
                description: Encryption controller
                product: Starship/Matisse Cryptographic Coprocessor PSPCPP
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.1
                bus info: pci@0000:0a:00.1
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix bus_master cap_list
                configuration: driver=ccp latency=0
                resources: irq:129 memory:fc800000-fc8fffff memory:fc908000-fc909fff
           *-usb
                description: USB controller
                product: Matisse USB 3.0 Host Controller
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.3
                bus info: pci@0000:0a:00.3
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:53 memory:fc700000-fc7fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.5.0-28-generic xhci-hcd
                   physical id: 0
                   bus info: usb@3
                   logical name: usb3
                   version: 6.05
                   capabilities: usb-2.00
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0
                      description: Audio device
                      product: Blue Microphones Yeti Nano
                      vendor: Blue Microphones
                      physical id: 1
                      bus info: usb@3:1
                      logical name: card1
                      logical name: /dev/snd/controlC1
                      logical name: /dev/snd/pcmC1D0c
                      logical name: /dev/snd/pcmC1D0p
                      logical name: input5
                      logical name: /dev/input/event2
                      logical name: input6
                      logical name: /dev/input/event3
                      version: 4.0a
                      serial: 2105SG00SB58_888-000445041006
                      capabilities: usb-2.00 audio-control usb
                      configuration: driver=usbhid maxpower=96mA speed=12Mbit/s
                 *-usb:1
                      description: Keyboard
                      product: USB HID GMMK Pro Mouse
                      vendor: USB HID
                      physical id: 2
                      bus info: usb@3:2
                      logical name: input10
                      logical name: /dev/input/event6
                      logical name: input12
                      logical name: /dev/input/event7
                      logical name: input7
                      logical name: /dev/input/event4
                      logical name: input7::capslock
                      logical name: input7::compose
                      logical name: input7::kana
                      logical name: input7::numlock
                      logical name: input7::scrolllock
                      logical name: input9
                      logical name: /dev/input/event5
                      logical name: /dev/input/mouse0
                      version: 0.28
                      capabilities: usb-2.00 usb
                      configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.5.0-28-generic xhci-hcd
                   physical id: 1
                   bus info: usb@4
                   logical name: usb4
                   version: 6.05
                   capabilities: usb-3.10
                   configuration: driver=hub slots=4 speed=10000Mbit/s
           *-multimedia
                description: Audio device
                product: Starship/Matisse HD Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.4
                bus info: pci@0000:0a:00.4
                logical name: card2
                logical name: /dev/snd/controlC2
                logical name: /dev/snd/hwC2D0
                logical name: /dev/snd/pcmC2D0c
                logical name: /dev/snd/pcmC2D0p
                logical name: /dev/snd/pcmC2D1p
                logical name: /dev/snd/pcmC2D2c
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:151 memory:fc900000-fc907fff
              *-input:0
                   product: HD-Audio Generic Rear Mic
                   physical id: 0
                   logical name: input22
                   logical name: /dev/input/event15
              *-input:1
                   product: HD-Audio Generic Front Mic
                   physical id: 1
                   logical name: input23
                   logical name: /dev/input/event16
              *-input:2
                   product: HD-Audio Generic Rear Mic
                   physical id: 2
                   logical name: input24
                   logical name: /dev/input/event17
              *-input:3
                   product: HD-Audio Generic Line
                   physical id: 3
                   logical name: input25
                   logical name: /dev/input/event18
              *-input:4
                   product: HD-Audio Generic Line Out Front
                   physical id: 4
                   logical name: input26
                   logical name: /dev/input/event19
              *-input:5
                   product: HD-Audio Generic Line Out Surround
                   physical id: 5
                   logical name: input27
                   logical name: /dev/input/event20
              *-input:6
                   product: HD-Audio Generic Line Out CLFE
                   physical id: 6
                   logical name: input28
                   logical name: /dev/input/event21
              *-input:7
                   product: HD-Audio Generic Front Headphone
                   physical id: 7
                   logical name: input29
                   logical name: /dev/input/event22
        *-serial
             description: SMBus
             product: FCH SMBus Controller
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 61
             width: 32 bits
             clock: 66MHz
             configuration: driver=piix4_smbus latency=0
             resources: irq:0
        *-isa
             description: ISA bridge
             product: FCH LPC Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14.3
             bus info: pci@0000:00:14.3
             version: 51
             width: 32 bits
             clock: 66MHz
             capabilities: isa bus_master
             configuration: latency=0
           *-pnp00:00
                product: PnP device PNP0c01
                physical id: 0
                capabilities: pnp
                configuration: driver=system
           *-pnp00:01
                product: PnP device PNP0c02
                physical id: 1
                capabilities: pnp
                configuration: driver=system
           *-pnp00:02
                product: PnP device PNP0b00
                physical id: 2
                capabilities: pnp
                configuration: driver=rtc_cmos
           *-pnp00:03
                product: PnP device PNP0c02
                physical id: 3
                capabilities: pnp
                configuration: driver=system
           *-pnp00:04
                product: PnP device PNP0c02
                physical id: 4
                capabilities: pnp
                configuration: driver=system
     *-pci:1
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 101
          bus info: pci@0000:00:01.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:2
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 102
          bus info: pci@0000:00:02.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:3
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 103
          bus info: pci@0000:00:03.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:4
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 104
          bus info: pci@0000:00:04.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:5
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 105
          bus info: pci@0000:00:05.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:6
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 106
          bus info: pci@0000:00:07.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:7
          description: Host bridge
          product: Starship/Matisse PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 107
          bus info: pci@0000:00:08.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:8
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 0
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 108
          bus info: pci@0000:00:18.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:9
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 1
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 109
          bus info: pci@0000:00:18.1
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:10
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 2
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10a
          bus info: pci@0000:00:18.2
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:11
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 3
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10b
          bus info: pci@0000:00:18.3
          version: 00
          width: 32 bits
          clock: 33MHz
          configuration: driver=k10temp
          resources: irq:0
     *-pci:12
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 4
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10c
          bus info: pci@0000:00:18.4
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:13
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 5
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10d
          bus info: pci@0000:00:18.5
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:14
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 6
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10e
          bus info: pci@0000:00:18.6
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:15
          description: Host bridge
          product: Matisse/Vermeer Data Fabric: Device 18h; Function 7
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10f
          bus info: pci@0000:00:18.7
          version: 00
          width: 32 bits
          clock: 33MHz
  *-graphics
       product: EFI VGA
       physical id: 1
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=1920,1080
  *-input:0
       product: Power Button
       physical id: 2
       logical name: input0
       logical name: /dev/input/event0
       capabilities: platform
  *-input:1
       product: Power Button
       physical id: 3
       logical name: input1
       logical name: /dev/input/event1
       capabilities: platform
  *-input:2
       product: Eee PC WMI hotkeys
       physical id: 4
       logical name: input17
       logical name: /dev/input/event10
       capabilities: platform
</pre>
</details>

**Comment by FubyCoder** [comment]
Looks like a regression from last stable release, i tested with the last version v0.139.3 and it's working correctly

**Comment by osiewicz** [comment]
I suspect it's related to https://github.com/zed-industries/zed/pull/12928, as it messed with how we're communicating paths to the language server. Thanks for filling out a ticket!
