### ISSUE TITLE
Project panel focus should update for image files also

### ISSUE THREAD

**Issue by ottob** [zed-industries/zed#13141]
### Check for existing issues

- [X] Completed

### Describe the feature

When I switch between source code files, the project panel focus is changed as expected.

But if I open an image file (png for example), it does not become focused in the project panel. There is also no `Reveal In Project Panel` option if I right click the tab.

**Comment by notpeter** [comment]
Got it. I can duplicate:

1. Toggling open file files (via clicking, ctrl+tab or cmd+shift+}) does not highlight image files in the project panel like it normally does for other files.
2. "Reveal in project panel" (and Open in Terminal) are missing from the right click context menu.
![image](https://github.com/zed-industries/zed/assets/145113/4847a67e-26d1-4dcf-98ef-6328ceb76b3f)

**Comment by ankhzet** [comment]
Controversial opinion: Don't change the selection in the project panel _at all_ . Or at least provide an option to turn automatic selection change off. I've scrolled to that part of the project structure _for a reason_  , tf why do you change it? Each time you select another file - it jumps around, and if you closed a file - good luck finding the directory where it was. Annoying.

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/zed-industries/zed/issues/9897

Thanks for reporting.  Please 👍 upvote that issue and subscribe to track it's progress.
