### ISSUE TITLE
Add Automated dependency updates

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#13145]
Consider adding dependabot to keep dependencies fresh.

Originally suggested by @ReillyBrogan [here](https://github.com/zed-industries/zed/issues/13073).

**Comment by maxdeviant** [comment]
I think Renovate might be a better choice than Dependabot, if we do go with this approach.

**Comment by maxdeviant** [comment]
We have [Renovate](https://www.mend.io/renovate/) setup now: https://github.com/zed-industries/zed/pull/15132

**Comment by ReillyBrogan** [comment]
> Renovate will create 144 Pull Requests

Going to be a rough few weeks until you get caught up lol. Good luck!
