### ISSUE TITLE
High CPU usage when Zed is in focus (Linux, X11)

### ISSUE THREAD

**Issue by AlexDaniel** [zed-industries/zed#13154]
Zed is using up to 100% on all cores when it's in focus. Other editors only use a few %.

No actions are performed – the mouse either moves a little or remains in the same position. Note that I'm seeing somewhat delayed keyboard input as well, but it may be because of high CPU usage.

Whenever Zed is not in focus, it practically does not use any CPU (just a few % like most apps).

![peek_3](https://github.com/zed-industries/zed/assets/5507503/e154cf25-7565-40ae-b3b2-956e453770c1)

### Environment

Debian 6.7.9-2 (2024-03-13) x86_64 GNU/Linux
X11
Note that this is a relatively old laptop – Thinkpad X230 (from 2012). Still, even VS Code performs well in the same conditions.

Zed was built by running `cargo run --release`.

**Comment by someone13574** [comment]
You probably don’t have a vulkan driver installed. Does `vulkaninfo --summary` say llvmpipe?

**Comment by apricotbucket28** [comment]
> Debian 6.7.9-2 (2024-03-13) x86_64 GNU/Linux X11 Note that this is a relatively old laptop – Thinkpad X230 (from 2012). Still, even VS Code performs well in the same conditions.

I'm guessing that Zed is using the llvmpipe driver for rendering judging by the age of the device. This is likely the same issue as https://github.com/zed-industries/zed/issues/11074.

Could you try manually selecting the graphics device with `MESA_VK_DEVICE_SELECT=`? (try setting it to `list` first to show all options)
