### ISSUE TITLE
[low-prio] Failsafe rendering option without GPU (in case of driver glitches or non-Metal macs)

### ISSUE THREAD

**Issue by stradicat** [zed-industries/zed#13159]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed having the option to render its window contents in a CPU-only fashion (e.g. plain framebuffer or basic OpenGL as fallback) if GPU drivers misbehave for the intended Zed purpose (high-performance, multi-core everything, which I find fascinating); such may be the case for `nouveau` in Linux, or the absence of Metal support in pre-2012 Macs (which are still used with OpenCore).

Perhaps it would help expand the userbase to focus on code-related features for productivity instead of just getting the editor to correctly render contents on quite heterogeneous OS+GPU scenarios.

Just a thought. I began trying Zed last week, and so far I'm generally impressed by the paradigm.

**Comment by jansol** [comment]
It could be useful to also draw some indicator when this failsafe is being used. It happens occasionally to people who are new to Linux that they don't realize they need to install GPU drivers, and the CPU rasterizer, while slow, does its job well enough for simple use.

If this fallback can be selected from the config (i.e. to work around a sort of working but buggy driver), this indicator should probably not be shown.

**Comment by notpeter** [comment]
This is something which has been discussed, but isn't an immediate priority.  I'm going to close this issue in favor of two distinct issues, one for OpenGL and one for framebuffer.  Please vote 👍 and subscribe to those issues to track their progress.

- https://github.com/zed-industries/zed/issues/13305
- https://github.com/zed-industries/zed/issues/12332

Thanks for reporting!
