### ISSUE TITLE
Can't set workspace options for typescript-language-server

### ISSUE THREAD

**Issue by LoganDark** [zed-industries/zed#13168]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```json
  "lsp": {
    "typescript-language-server": {
      "initialization_options": {
        "tsserver": {
          "path": "/home/logandark/XXXXXXXXXXXXXXXX/frontend/www/node_modules/typescript/lib/"
        }
      },
      "settings": {
        "implicitProjectConfiguration": {
          "checkJs": true,
          "module": "nodenext"
        }
      }
    }
  }
```

`initialization_options` works, but `settings` is entirely ignored.

This is needed to set [configuration options](https://github.com/typescript-language-server/typescript-language-server/blob/b224b878652438bcdd639137a6b1d1a6630129e4/docs/configuration.md#workspacedidchangeconfiguration)

### Environment

Zed: v0.136.0 (Zed Dev 6a681d29ea9156542ab517168d2c8bcb4d6accd8)
OS: Windows 10.0.25931
Memory: 127.9 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
When this issue was filed, project settings did not support configuring language server options.  As of early September 2024 this is now support.

If you are still having trouble, please open a clean issue.
Thanks for reporting!
