### ISSUE TITLE
Numbers not working in vim normal mode with layouts that don't have numbers in direct access

### ISSUE THREAD

**Issue by bluthej** [zed-industries/zed#13177]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Set up a keyboard layout that does not have numbers in direct access (e.g. the French azerty or bépo layout).

Then, do anything with a number in normal mode, like "2yy" for instance. The 2 is ignored and only the current line is copied.

You can also try setting up a custom keybinding for this like so:
```json
{
    "context": "Editor && (vim_mode == normal || vim_mode == visual) && !VimWaiting && !menu",
    "bindings": {
      "shift-«": ["vim::Number", "2"],
    }
}
```
but that does not work either (on bépo the 2 is in shift access over the character «).

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 15 GiB
Architecture: x86_64

**Comment by ConradIrwin** [comment]
Fixed by #13485
