### ISSUE TITLE
Breadcrumbs use UI font size but render in buffer font family

### ISSUE THREAD

**Issue by DarkSymm** [zed-industries/zed#13191]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

At the moment toolbar breadcrumbs is styled with a combination of using the ui_font_size and buffer_font_family.

Think it would make sense to use both ui_font_family and ui_font_size.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Here's a screenshot:
<img width="600" alt="image" src="https://github.com/zed-industries/zed/assets/145113/c8b066fb-c94a-428b-bd69-3b76f8737603">

I believe the current behavior of the breadcrumb bar (`buffer_font_family` and `ui_font_size`) was chosen for two reasons:
1. If we used `buffer_font_size` the breadcrumb bar would resize as you were zooming. I don't think I've seen an app that scales toolbars or statusbars when you zoom.
2. If you use `ui_font_family` we would be showing code (`pub enum Axis` in my screenshot) using the variable width UI font.

And so we're left with the odd pairing of `ui_font_size` and `buffer_font_family`.
