### ISSUE TITLE
Markdown title text rendering is clipped incorrectly 

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/zed#13207]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Noticed that my titles in Markdown Preview were making my eyes hurt, but couldn't put my finger on it. Then I noticed that each glyph appears to be missing its first few, left-most pixels?

<img width="630" alt="image" src="https://github.com/zed-industries/zed/assets/26578100/24270dad-01d7-4212-b471-be2aab6762c6">

See the O's in "looks", they are missing the left edge of their curves.

<img width="786" alt="image" src="https://github.com/zed-industries/zed/assets/26578100/d27374ce-3ad8-4f22-97f4-fa0db09820a4">

Edit: Oops, I accidentally wrote 'letting', not 'lettering'. Oh well, too late now.

### Environment

Zed: v0.140.4 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I am not able to reproduce this with a current version of Zed.
There were some recent improvements to Markdown preview so perhaps this was fixed as part of that work.

If you are still seeing this, please comment and I'm happy to reopen (include the fonts you're using and your current Zed version/platform information from `zed: copy system specs to clipboard).

Thanks for reporting.
