### ISSUE TITLE
Pyright not working correctly with `pyproject.toml`

### ISSUE THREAD

**Issue by konsalex** [zed-industries/zed#13206]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Pyright LSP is not working as expected with venv denifinition inside the `pyproject.toml` while works as expected if it is set inside the `pyrightconfig.json`

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.3.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/12672541/6e763ef8-6560-4d68-8af5-51de09757c06

**Comment by amtoaer** [comment]
I just started a new project, didn't run into the same problem. 

<img width="1469" alt="image" src="https://github.com/zed-industries/zed/assets/32017007/730e681c-cb69-4789-b7a5-e53c305f05b2">


[Pyright document](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) says:
> A “pyrightconfig.json” file always takes precedent over “pyproject.toml” if both are present.

Maybe remove "pyrightconfig.json" could help?

**Comment by konsalex** [comment]
@amtoaer removed the `pyrightconfig.json` did not even have it just added to debug, still the same issue 🤔

**Comment by tfeldmann** [comment]
> @amtoaer removed the `pyrightconfig.json` did not even have it just added to debug, still the same issue 🤔

Is your `pyproject.toml` in the root dir?

**Comment by amtoaer** [comment]
Oh, I see. From [zed document](https://zed.dev/docs/languages/python):
> By default, the Pyright language server will look for Python packages in the default global locations. But you can also configure Pyright to use the packages installed in a given virtual environment.
>
> To do this, create a JSON file called pyrightconfig.json **at the root of your project**.

So "pyrightconfig.json" or "pyproject.toml" should be placed at the root of your project to be used. I just opened my project from `../` to let "pyproject.toml" be in sub folder, venv didn't work, either.

**Comment by konsalex** [comment]
Oh makes sense @tfeldmann @amtoaer the toml was not in the root, as it was a monorepo with a nested Python project my bad!
