### ISSUE TITLE
Slow File Opening

### ISSUE THREAD

**Issue by kexek** [zed-industries/zed#13209]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi there,

I'm experiencing an issue where certain files take relatively long to open in Zed. I've attached a video demonstrating the problem for your reference. If you need any additional information, please feel free to ask.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.3.0
Memory: 18 GiB
Architecture: aarch64
Chip: M3 Pro

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/21371586/71a64e0a-cba0-4a52-b9c3-7ea77670e057

**Comment by notpeter** [comment]
Does this happen with all filetypes or just with ts?

**Comment by osiewicz** [comment]
How many files do you have in that project? Can you run `git ls-files | wc -l`?
Does it happen straight away, or only after you spend some time coding?

**Comment by kexek** [comment]
> Does this happen with all filetypes or just with ts?

I attempted to open a larger Python project, but the problem persists. The files take even longer to open than in the attached video. Running `git ls-files | wc -l` shows there are 540 files in this project.



> How many files do you have in that project? What's the output of `git ls-files | wc -l`? Does it happen straight away, or only after you spend some time coding?

It says 391

**Comment by osiewicz** [comment]
Does it happen if you remove your node_modules (or move it outside of this project)?

**Comment by kexek** [comment]
> Does it happen if you remove your node_modules (or move it outside of this project)?

I just removed the `node_modules` folder and it doesn't seem to affect the issue, opening files still takes long

**Comment by kexek** [comment]
Here is another video, just to make sure this is probably not my hardware problem

https://github.com/zed-industries/zed/assets/21371586/5933cb37-6e7c-4128-b568-b2f1e38ca17f

**Comment by kexek** [comment]
Hi, the issue is resolved for me now. I'm not sure if it's due to the recent updates or something else, but the files in any project are now consistently opening quickly, as expected

**Comment by kexek** [comment]
Hi, the issue is resolved for me now. I'm not sure if it's due to the recent updates or something else, but the files in any project are now consistently opening quickly, as expected
