### ISSUE TITLE
Option for disabling all collaborative features of Zed

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#13218]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello, I'd like to see an option added to disable all collaborative features of Zed. For users like me who don’t need these, they take up unnecessary space (and resources?). While hiding the buttons for the collaboration, chat, and notification panels through settings is possible, I don't think it's enough.

•	Completely disable collaboration and chat panels: Even when hidden, these panels might still be running in the background, using resources?
•	Suppress collaboration-related notifications: Invites, calls, mentions, and other notifications can be distracting when collaboration is not in use. Currently, they still generate system activity and interruptions.
•	Repurpose the top bar: The top bar currently shows user avatars and speaker highlights, which are redundant for solo users. This space could be better utilized for other purposes.

Hiding buttons is a step in the right direction, but fully disabling these features would create a cleaner, more efficient workspace for those of us who use Zed as a standalone editor. It would improve the user experience by providing a distraction-free environment and optimizing resource usage.

**Comment by evrensen467** [comment]
Hm unfortunate but fair enough, thanks for the reply in short time.

**Comment by RomanShumikhin** [comment]
I absolutely love the editor! It would be fantastic to have an option to hide the collaborative features since I’m not planning to use them. They remind me of the mandatory sign-in for MS Visual Studio. I usually work solo, and I know many other developers do too. Thanks a ton for all your hard work!

**Comment by xvbcfj** [comment]
Getting builds without this functionality would also help adoption in companies which prohibit such dependency on external services.

**Comment by rxdiscovery** [comment]
I think having a strong coupling between Zed and Github is highly questionable.

[ Looks like an editor made by and for Github (Microsoft) ]

Zed must remain neutral, or at least offer this kind of functionality via plugins.

**Comment by sa1** [comment]
Also, failing to log into Zed collab(blocked by corporate proxy) prevents usage of copilot as well (which is not blocked).

**Comment by stormasm** [comment]
I have gone ahead and successfully deleted the collab features in Zed...

For more details on this subject please take a look at these notes.

https://github.com/stormasm/zednotes/blob/main/no-collab.md

**Comment by stormasm** [comment]
> @stormasm : For me it would be enough to no longer see the words `Sign in`.

So its probably a simple fix then --- the `Sign in ` in the toolbar as discussed in my note 
has to be replaced with a blank string
when a configuration parameter is set denoting that case 👍

**Comment by stormasm** [comment]
```rust    
pub fn render_sign_in_button(&mut self, _: &mut ViewContext<Self>) -> Button {
        let client = self.client.clone();
        Button::new("sign_in", "Sign in")
            .label_size(LabelSize::Small)
            .on_click(move |_, cx| {
                let client = client.clone();
                cx.spawn(move |mut cx| async move {
                    client
                        .authenticate_and_connect(true, &cx)
                        .await
                        .notify_async_err(&mut cx);
                })
                .detach();
            })
    }
```

**Comment by maxdeviant** [comment]
> @maxdeviant : as stated both here and in #12325, many people agree on the possibility of enabling/disabling this feature, as can be seen from the reactions that can be seen in the comments. So I think it's better to create a discussion and talk about it better there.

As stated above:

> At its core Zed is a collaborative code editor, so we don't want to hide the collaborative features.

We have no plans to hide or otherwise deprioritize Zed’s collaborative features.

**Comment by nervenes** [comment]
Going to close this issue now as it seems unlikely, if an open tracker is preferred then one could be created that references this one 👍
