### ISSUE TITLE
Reset or refresh opened file

### ISSUE THREAD

**Issue by vito** [zed-industries/zed#13212]
### Check for existing issues

- [X] Completed

### Describe the feature

(Sorry if dupe, searched pretty hard and couldn't find anything.)

Zed will notice when a file has updated out-of-band and warn me when I try to save, which is great. But how can I do the equivalent to Vim's `:e!` to reset to the current file's content?

Even better would be for a buffer which was initially unmodified (i.e. saved to disk) to just automatically refresh when it notices the file changed (i.e. due to a Git branch switch). It doesn't seem like that happens now. It seems like it prefers to retain the old content and deem it "modified" (state != disk) and then warns me about closing with unsaved changes. (I could be wrong here, sorry if so.) (**edit:** just saw this working, so not sure what gave me that impression)

Side note: I have the tab bar disabled locally for a more Vim-like experience, otherwise I end up with a million tabs duped between all my panels. So not seeing the file modification state might be a factor in my UX here.

**Comment by ConradIrwin** [comment]
Thanks for reporting! Looks like we need to create an action for this, and then bind `:e` to do it. If you want to pair on this https://calendly.com/conradirwin/pairing

**Comment by jpx40** [comment]
is there a way to trigger relaod automatic. i wanna format my file with an cli tool.

**Comment by simicvm** [comment]
any updates on this?

**Comment by stuaxo** [comment]
I'd like it if it noticed the file was updated out of band immediately as well.

**Comment by alexanderjeurissen** [comment]
I filed an issue that is related to this, for me the "too lazy" reloading is most apparent in:

1. Using a CLI tool to format code from the terminal and the file not automatically reloading
2. When using Zed as a git editor and performing a git commit from the terminal, the EDIT_COMMITMSG buffer becomes sticky and only `workspace: reload` will force the reload: https://github.com/zed-industries/zed/issues/18701

**Comment by bethebunny** [comment]
The PRs closing this added `editor: reload file` if you want to bind this to a key or execute it manually. I would say this is still a persistent pain, especially when dealing with a rebase stack. As of the most recent update 2025-02-07 Zed still consistently does not recognize changes to files and automatically reload.

**Comment by ConradIrwin** [comment]
@bethebunny could you please file a new issue; Zed should (if you have no unsaved changes) automatically reload files. There are known bugs if you are using a filesystem that doesn't support inotify/fsnotify/etc.

**Comment by goce-cz** [comment]
> Zed should (if you have no unsaved changes) automatically reload files.

This works nice, however if I HAVE unsaved changes, then I can keep happily modifying the file without noticing. When I then attempt to save the file, I need to go through a PITA conflict resolution.

JetBrains editors simply display a dialog asking whether you want to keep your in-memory changes or you want to reload as soon as the file is modified externally. That would minimize the pain, I think.

**Comment by warrenc5** [comment]
Zed Noob here..  running stock Ubuntu with Ext4 fs. (without inotify-tools package installed)
 
Did a git merge on another console. Zed editor (with vim) displays pre-merge (old/stale) buffer even closing the tabs and then double clicking the file in the project file tree continues to show the same stale buffer.  

Issued :workspace reload command and all the zed instances were respawned and new buffers appeared.

I may be a bit old school -  but I usually expect an editor to be reflecting the data on the disk.
In short, an editor that doesn't save files correctly or overwrites disk changes silently is almost useless to me as a programmer. (I remember Atom suffered a similar issue.)

@goce-cz mentioned this modal dialog approach which I have used in Netbeans and Gvim. I personally dislike modal interactivity of this nature. Which results in 'all theirs or all mine' outcome.

Could we break out of the modal dialog box world?
I wonder if an synthetic/transient 3 way merge UX approach would work here (There would be disadvantages too no doubt). 
I.e. The IDE would detect the fs change and present the user a "red or orange dirty state buffer/file tab icon" (and mandate an interactive merge on save). 

If this is already something available in one of Zeds' extensive extension plugin then please forgive the author and let me know :)

**Comment by ConradIrwin** [comment]
@warrenc5 Zed should reload files automatically. We do use inotify for that, so that may be the problem. If you look in the log do you see errors about not having that? Does it resolve itself if you

**Comment by yonilevy** [comment]
> [@bethebunny](https://github.com/bethebunny) could you please file a new issue; Zed should (if you have no unsaved changes) automatically reload files. There are known bugs if you are using a filesystem that doesn't support inotify/fsnotify/etc.

any updates on this? is this currently the intended behavior that's broken or should we file a feature request?

**Comment by argh** [comment]
> > Zed should (if you have no unsaved changes) automatically reload files.
> 
> This works nice, however if I HAVE unsaved changes, then I can keep happily modifying the file without noticing. When I then attempt to save the file, I need to go through a PITA conflict resolution.

Yup, this kills me switching to Zed, it's completely non-obvious that you're making more and more changes.  Even Emacs warns you instantly if you try making a change to a buffer that isn't in sync with the file ("file has changed on disk; really edit the buffer (y, n, r or C-h)").  

I made 20 minutes of changes in Zed (not realizing autosave defaults to false!) and then discovered that my out-of-band linter and Claude Code updates were conflicting with my editor updates.

> 
> JetBrains editors simply display a dialog asking whether you want to keep your in-memory changes or you want to reload as soon as the file is modified externally. That would minimize the pain, I think.

+1, I'm mostly coming from JetBrains as well.

**Comment by warrenc5** [comment]
> [@warrenc5](https://github.com/warrenc5) Zed should reload files automatically. We do use inotify for that, so that may be the problem. If you look in the log do you see errors about not having that? Does it resolve itself if you

I do have inotify-tools install as I wrote https://github.com/warrenc5/rerunner 

I will double check the log for stupid user error :)

I really think a world class editor would ask the developer to do 3 way merge rather than two choices of sacrifices.
