### ISSUE TITLE
Adding New (ad-hoc) Languages

### ISSUE THREAD

**Issue by zacharysyoung** [zed-industries/zed#13225]
### Check for existing issues

- [X] Completed

### Describe the feature

I want to be able to define a new language and associate some file extensions with it. I've read [Adding New Languages - Zed](https://zed.dev/docs/adding-new-languages), but I don't see how to add a new language... that article looks to me to only show how to modify an existing language.

Concretely, I want Zed to stop removing the trailing spaces for my MermaidJS files. I tried to define my own language and then configure with a project-level .zed/settings.json:

```json
{
  "file_types": {
    "MermaidJS": ["mmd"]
  },
  "languages": {
    "MermaidJS": {
      "remove_trailing_whitespace_on_save": false
    }
  }
}
```

That didn't work. I don't know if something like this is currently possible... and I'm just missing some steps/configurations.

Thank you :)

As a stop-gap I can pick "Plain Text" (which isn't used anywhere else in the project):

```json
{
  "file_types": {
    "Plain Text": ["mmd"]
  },
  "languages": {
    "Plain Text": {
      "remove_trailing_whitespace_on_save": false
    }
  }
}
```

**Comment by jansol** [comment]
The proper way to go about this would be creating an extension that defines this language. You can add extensions from a local folder using the "Add dev extension" button in the extension view.

**Comment by zacharysyoung** [comment]
@jansol, thank you! I'll check that out.
