### ISSUE TITLE
Small artifacts above the collapse buttons

### ISSUE THREAD

**Issue by tfeldmann** [zed-industries/zed#13249]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

All collapse buttons have some random pixels above.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Bildschirmfoto 2024-06-19 um 10 39 51](https://github.com/zed-industries/zed/assets/385566/be40ea02-ae6d-435f-a179-ad2b932e068c)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Also observed on Linux in #13345

**Comment by someone13574** [comment]
Why does this have the linux tag? It looks like it occurs on multiple (all?) platforms.

**Comment by notpeter** [comment]
> Why does this have the linux tag? It looks like it occurs on multiple (all?) platforms.
That was my error. Removed.

**Comment by carlz32** [comment]
Try to change your font size or zoom level, you can get around it, if you are lucky.

**Comment by notpeter** [comment]
I am no longer able to reproduce and so I believe this has been fixed. If you are still seeing this issue, please comment with version/screenshot and I'm happy to reopen. Thanks!
