### ISSUE TITLE
Blurry mouse pointer on Wayland

### ISSUE THREAD

**Issue by filipwiech** [zed-industries/zed#13258]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have the following setup:
* Ubuntu 24.04 GNOME Wayland
* Main laptop screen, 100% scaling
* External 4K monitor, set to 200% scaling

When I move Zed onto the 4K screen, the window is scaled nicely (correct size and crisp graphics), however whenever I move the mouse pointer over the editor it becomes blurry. It has the correct size, but it's as if the icon used for the rendering came from a lower resolution asset. If I move the pointer outside of the Zed window (for example over the desktop or some other application) then it becomes sharp. Sorry for no images, but unfortunately it doesn't show on screenshots.

### Environment

Zed: v0.141.0 (Zed Nightly d4891a62bb3bd45db713fa576a13f8a5d95ca382)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you try the commands shown in https://github.com/zed-industries/zed/issues/14862 to see if that helps?

**Comment by senonide** [comment]
Same problem with this setup:
- Fedora 40 Gnome Wayland
- Laptop screen, 200% scaling 

Only when I move the mouse pointer over the editor, it becomes blurry. It seems that the problem comes from scaling at 200% because this does not happen when the screen is at a scaling factor of 100%.

**Comment by apricotbucket28** [comment]
I believe the issue here is that when we [set the cursor surface](https://github.com/zed-industries/zed/blob/b1a581e81b6eaa951a7ca195cb0c46c335d0d5c7/crates/gpui/src/platform/linux/wayland/cursor.rs#L94) for the pointer we don't actually specify the buffer scale for said `wl_surface`.
Here's SCTK code for reference: https://github.com/Smithay/client-toolkit/blob/c583de8dd5651f8168c6513cd282137c42aae049/src/seat/pointer/mod.rs#L458-L495

**Comment by Raiden0456** [comment]
I've just encountered this issue, mouse pointer was definitely fine a week ago. Is this an ongoing issue?

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/zed/pull/21373
