### ISSUE TITLE
Rust test runner doesn't work when the crate is not the root directory of the project

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/zed#13267]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a directory (from CLI with `zed .`) that contains multiple subdirectories which are Rust projects.

Click the `>` button in the sidebar next to a test.

It fails because it can't find `Cargo.toml` in the root project directory.

![image](https://github.com/zed-industries/zed/assets/26578100/d23ace7a-d015-4106-94db-8b8e82e7069c)

### Environment

Zed: v0.140.5 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
We could probably get away with setting a cwd of that task to the cwd of a file it's being ran on.
