### ISSUE TITLE
Zed not opening (os error 13) ~/.config/zed

### ISSUE THREAD

**Issue by Erickk0** [zed-industries/zed#13271]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

When I install Zed on my Laptop it always throws the error (os error 13) no matter if I installed the Apple Silicon or the Binaries

### Environment

MacBook Pro
Apple M3 Pro
18GB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you provide a screenshot and not which files/directories are trigging the failure?

**Comment by Erickk0** [comment]
Sure, here is the error code with the files causing it.
<img width="262" alt="Screenshot 2024-06-20 at 00 28 36" src="https://github.com/zed-industries/zed/assets/153301934/9b7316f5-8d88-4ee1-bc86-a22a1f0c65c6">

**Comment by notpeter** [comment]
Incorrect permissions on your `~/.config` directory are likely preventing Zed from creating the `~/.config/zed` directory.

Can you try running:
```
chmod u+rwx ~/.config/
```

And try again?

See also: https://github.com/zed-industries/zed/issues/12979

**Comment by Erickk0** [comment]
After pasting the command it still doesnt work I tried to make the dir myself but got that error code: `mkdir: /Users/erickzeiler/.config/zed: Permission denied`

**Comment by notpeter** [comment]
Please verify the ownership of your .config folder using the ls command in the other thread.

You likely need to `chown $USER:staff ~/.config` and then rerun the chmod command above.

**Comment by Erickk0** [comment]
Thank you for the fast replies.
Zed runs now after creating the zed folder in `~/.config`
