### ISSUE TITLE
Add V Language Support

### ISSUE THREAD

**Issue by mike-ward** [zed-industries/zed#13278]
### Check for existing issues

- [X] Completed

### Describe the feature

Add support for the V Language.

https://vlang.io

**Comment by someone13574** [comment]
There is an extension which adds support. Just search "V" and scroll down a bit.

https://github.com/zed-industries/extensions/pull/765

**Comment by mike-ward** [comment]
Ah, no wonder I didn't find. Was searching on Vlang. Thanks!

**Comment by notpeter** [comment]
See also:
- https://github.com/zed-industries/zed/issues/10340
