### ISSUE TITLE
Add Undo feature to project panel

### ISSUE THREAD

**Issue by andreeich** [zed-industries/zed#13270]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello 👋 everybody,

I've just discovered that Zed doesn't have an undo feature (Ctrl + Z) on the file panel. This means I can't undo ↩️ operations such as creation, deletion, renaming, or moving files into another directory.

This feature is available in VSCode and even the basic Finder on macOS, so it's surprising that Zed lacks it. It makes working with Zed uncomfortable, knowing you can't undo your actions. This limitation makes you overly cautious.

**Comment by JosephTLyons** [comment]
Hey @andreeich, do you mind upvoting this issue with a 👍, and providing any extra details you think it is missing, in a comment? I'm going to close this out as a duplicate.

- https://github.com/zed-industries/zed/issues/5039
