### ISSUE TITLE
Comment color collides with copilot suggestions

### ISSUE THREAD

**Issue by ottob** [zed-industries/zed#13277]
### Check for existing issues

- [X] Completed

### Describe the feature

I use the one dark theme and the color of comments are grey.
The same(ish?) color is used for copilot suggestions. This can become slightly confusing.
In VS code comments are green and copilot suggestions are grey.

**Comment by ottob** [comment]
slightly related: https://github.com/zed-industries/zed/issues/9133 - A setting to turn off Copilot when writing comments

**Comment by notpeter** [comment]
I see what you mean.  Probably worth tweaking the colors in the One Dark theme a bit. 

<img width="365" alt="image" src="https://github.com/zed-industries/zed/assets/145113/2cb45be8-f5d5-482a-96d0-19a09d0996c5">

Other themes do a little better. e.g. Solarized Dark:

<img width="364" alt="image" src="https://github.com/zed-industries/zed/assets/145113/e8f0b36d-0788-41e5-8a2f-33b123fb3773">

**Comment by notpeter** [comment]
I'm going consolidate this issue into 
- https://github.com/zed-industries/zed/issues/15521

Please 👍 that issue to help prioritize and subscribe to track it's progress.
Thanks for reporting @ottob
