### ISSUE TITLE
Ability to disable / hide buffer tab toolbar (filename breadcrumbs, etc)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#13275]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to request ZED feature that will allow me under Linux to fold/turn-off the top window bar, in presented screenshot this is the top purpose area. 

In presented sample, I work on linux's `fluxbox` and due to minimal interface layout, the top bar seems to clutter the space somewhat, especially under low resolution screen/monitors.

See screenshots for purple top-bar detail:
- Linux fluxbox existing UI screenshot sample: 
![rendering](https://github.com/zed-industries/zed/assets/4711498/6753a932-d4a2-4a5f-997d-adeb149543a8)
Note: window the rendering BUG is submitted in a separate ticket.

- This particular feature request is aimed at Linux, as in Mac I am guessing it would be hard to avoid top bar rendering (in MacOS the bar is more minimalistic compared to Fluxbox/Linux):
![MacOS](https://github.com/zed-industries/zed/assets/4711498/b0d018f5-e957-4341-ad67-8b8af60c9c59)

### If applicable, add mockups / screenshots to help present your vision of the feature

- Existing (notice visible purple bar):
![rendering](https://github.com/zed-industries/zed/assets/4711498/6753a932-d4a2-4a5f-997d-adeb149543a8)

- Proposed (notice missing purple bar):
![proposed](https://github.com/zed-industries/zed/assets/4711498/4903c7ac-ebb4-4f4b-9afb-817545a0c11d)

Note: the rendering issue is reported under https://github.com/zed-industries/zed/issues/13274

**Comment by notpeter** [comment]
I believe this is possible today with the following settings:
```json
  "toolbar": {
    // Whether to show breadcrumbs.
    "breadcrumbs": false,
    // Whether to show quick action buttons.
    "quick_actions": false,
    // Whether to show the Selections menu in the editor toolbar
    "selections_menu": false
  },
```

**Comment by AndydeCleyre** [comment]
What *is* the "selections menu?" Can anyone post a screenshot?

**Comment by fabriciorby** [comment]
> What _is_ the "selections menu?" Can anyone post a screenshot?

I was wondering the same until I found it. It was difficult to find because if you disable `quick_actions` then `selections_menu` is also gone.

![image](https://github.com/user-attachments/assets/961c054b-3ac9-4e61-9f61-91705d8b50b0)
This is the `selections_menu`
