### ISSUE TITLE
Inline assist button should be hidden when assistant is disabled

### ISSUE THREAD

**Issue by chungweileong94** [zed-industries/zed#13289]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, when the assistant is disabled in settings
```jsonc
"assistant": {
    "version": "1",
    "enabled": false,
    "button": false // This option feel redundant when we already disable the assistant
  }
```
The "Inline Assist" button from the quick action bar should be hidden, as even if it's showing, it will do nothing when we press on the button.

**Comment by notpeter** [comment]
Fixed by #13290. Thanks for reporting @chungweileong94.
