### ISSUE TITLE
Runnables: Configure visibility of play button in test files

### ISSUE THREAD

**Issue by baldwindavid** [zed-industries/zed#13280]
### Check for existing issues

- [X] Completed

### Describe the feature

Recently the concept of a "runnable" was introduced. For each test in, for example, an elixir file, a play button appears in the gutter next to a test. Clicking this button runs the test. This is a neat feature, but I generally don't click things and instead kickoff tests via keyboard shortcut. Thus, this UI element becomes unnecessary noise/clutter. I thought that this would perhaps be tied to the `gutter.code_actions` setting, but setting that to `false` has no impact. Is there a setting I'm missing or is this something that could become configurable?

**Comment by osiewicz** [comment]
Hey @baldwindavid,
Yeah, it's just an oversight; there's no option like that to disable runnables in the gutter. I'll add one tomorrow.
