### ISSUE TITLE
linux: NewlineAbove and NewlineBelow keyboard shortcut does not work correctly

### ISSUE THREAD

**Issue by izznatsir** [zed-industries/zed#13284]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Write a line
2. Try adding newline above with `ctrl+shift+enter`
3. Instead it will add a new line below
4. Try adding newline below with `ctrl+enter`
5. Nothing happens

I have also tried to add custom key bindings as follow based on the default key bindings:
```json
[
  {
    "context": "Editor && mode == full",
    "bindings": {
      "ctrl+shift+enter": "editor::NewlineAbove",
      "ctrl+enter": "editor::NewlineBelow"
    }
  }
]
```

### Environment

Zed: v0.141.0 (Zed Preview)
OS: Linux Wayland ubuntu 24.04
Memory: 9.6 GiB
Architecture: x86_64

**Comment by ConradIrwin** [comment]
@izznatsir The following should work (note that zed uses `-` not `+` in [keystroke syntax](https://zed.dev/docs/key-bindings#keybinding-syntax)):
```
[
  {
    "context": "Editor && mode == full",
    "bindings": {
      "ctrl-shift-enter": "editor::NewlineAbove",
      "ctrl-enter": "editor::NewlineBelow"
    }
  }
]
```

**Comment by izznatsir** [comment]
My silly mistake. Haha. Thanks.
