### ISSUE TITLE
Mouse click events fall through the toast notification

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#13294]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Popup messages should intercept mouse events

https://github.com/zed-industries/zed/assets/19868292/47850f38-743b-47b1-8bcf-710f7807cb73

### Environment

Zed: v0.141.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Looks like this issue is the same:

- https://github.com/zed-industries/zed/issues/10891

Going to close this one out as a dupe, feel free to upvote (👍) #10891!
