### ISSUE TITLE
Vim counts don’t work when digits are not accessible directly (shift) (Linux?)

### ISSUE THREAD

**Issue by sylbru** [zed-industries/zed#13306]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In Vim mode, preceding a command with a digit should make the command execute that many times. This works using the qwerty layout, but not when using a keyboard layout where digits are not accessible directly, but rather using the Shift modifier. Some of these layouts include French azerty (fr oss) and bépo (fr bepo). 
This is on Linux but I can’t check if that’s related.

Steps to reproduce:

1. (Possibly use a Linux build?)
2. Install and switch to a keyboard layout like French Azerty (fr oss).
3. Enable Vim mode in Zed
4. Execute a command like `5j` (typing the "5" character should be something like Shift-% on a Qwerty-printed keyboard)
5. The cursor goes down one line instead of five.
 

### Environment

Zed: v0.142.0 (Zed Nightly 0129d4e2506d5ec5e50ef0968382770b9abec390)
OS: Linux X11 linuxmint 21.2
Memory: 14.8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

I'm getting lots of "unknown button press" warnings but can't tell if it's related.
<details><summary>Zed.log</summary><pre>

...
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:21+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
2024-06-20T12:20:22+02:00 [WARN] Unknown button press: ButtonPressEvent { .. }
...
</pre></details>

**Comment by sylbru** [comment]
Hopefully it will be easily reproducible on Linux too!

**Comment by ConradIrwin** [comment]
I can reproduce this on Linux.

It looks like there are a number of differences with how zed handles this layout vs the built-in terminal app:

* If I type the keys in the top row (labeled 1-0 on my qwerty keyboard) I get:
* In gnome terminal: `&é"'(-è_çà` (and with shift: `1234567890`)
* In Zed: `1é3456è8çà`(and with shift: `!@#$%ˆ&*()`)

This means I can't figure out how to type a literal 2 into the editor in zed with this keyboard.

Is this what you experience too, or is your issue just that in vim mode shift-2 is not recognized as 2?

**Comment by ConradIrwin** [comment]
Actually, playing with this more... It seems like my problems are unrelated (If you add a new keyboard layout and then switch to it, it doesn't work properly until you restart zed).

**Comment by sylbru** [comment]
Yay thanks for the fix! Looking forward to trying it out as the Vim experience will be much more complete!

I wasn’t experiencing the issue you described, although I think I remember having to restart Zed the first time I switched keyboard layouts. Seems to be totally fine now though.
