### ISSUE TITLE
Show package latest version, link and short description

### ISSUE THREAD

**Issue by PrashantSakre** [zed-industries/zed#13303]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be good to have the popup shown on hover over the package version to show the package latest version and short description as well as link just like vscode.

### If applicable, add mockups / screenshots to help present your vision of the feature

Not sure whether to create extension or provide built-in.

**Comment by notpeter** [comment]
Interesting, I hadn't seen that in VSCode, can you paste a screenshot?

Which language(s) are you using? Is this for `package.json` or something else?

**Comment by PrashantSakre** [comment]
Yes while using package.json, could also be any other package files.
![Screenshot 2024-06-20 at 22 08 33](https://github.com/zed-industries/zed/assets/42613882/05be6b4a-21e6-451a-9d73-905928252313)
