### ISSUE TITLE
`vim_mode` and the `Workspace` context

### ISSUE THREAD

**Issue by Vagab** [zed-industries/zed#13310]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've been trying to find files in zed with vim enabled using `space f`:
```json
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "space f": "file_finder::Toggle",
    }
  }
```
and everything works great, but when I close zed and open it again there are no open files, so the `Editor` context is false, the `Workspace` context is true though. So my intuition tells me that I can do:
```json
  {
    "context": "Workspace && vim_mode == normal",
    "bindings": {
      "space f": "file_finder::Toggle"
    }
  }
```
but that doesn't seem to work. I tried to think of workarounds but none of them worked

### Environment

Zed: v0.141.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

**Comment by jujumatter** [comment]
try   "context": "(Editor && (vim_mode == normal || vim_mode == visual) && !VimWaiting && !menu) || EmptyPane || SharedScreen || (ProjectPanel && not_editing)"

**Comment by ConradIrwin** [comment]
@jujumatter's suggestion should work. I also just added an example to the docs to help.

The best way to think about contexts is as a nested set of layers. When the app is running and you're editing the layers look something like this:

```
Workspace
- Pane  [.EmptyPane]
- - Editor [vim_mode == insert, etc ]
```

Context queries are matched per-layer, so it's not possible to match Workspace and vim_mode in one go.

**Comment by Vagab** [comment]
@jujumatter that works, thank you!
@ConradIrwin thanks for the addition to the docs 👍

**Comment by rdnrtms** [comment]
What was the original @jujumatter's suggestion? I am struggling with the same... Please see the code below. The ProjectPanel toggling works, however it disrupts vim's insert mode as well, which is less than ideal...
```json
{
  "context": "Workspace && right_dock != GitPanel && vim_mode == normal",
  "bindings": {
    "space g g": "git_panel::ToggleFocus",
  },
},

{
  "context": "Workspace && right_dock == GitPanel && vim_mode == normal",
  "bindings": {
    "space g g": "workspace::ToggleRightDock",
  },
},

{
  "context": "Workspace && left_dock != ProjectPanel",
  "bindings": {
    "space e": "project_panel::ToggleFocus",
  },
},

{
  "context": "Workspace && left_dock == ProjectPanel",
  "bindings": {
    "space e": "workspace::ToggleLeftDock",
  },
},
```
