### ISSUE TITLE
Auto save not working

### ISSUE THREAD

**Issue by mike-ward** [zed-industries/zed#13316]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Auto save is not working with the following local settings file
```
{
  "format_on_save": "on",
  "formatter": {
    "external": {
      "command": "v",
      "arguments": ["fmt"]
    }
  },
  "autosave": { "after_delay": { "milliseconds": 500 } },
  "tab_size": 8,
  "hard_tabs": true
}
```

### Environment

Zed: v0.140.5 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

M2 Macbook Air

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you provide a short video demonstrating the issue and provide a copy of your Zed.log for the duration of that recording?

I'm wondering whether something is happening with the formatter failing to execute which interrupts the save.

**Comment by mike-ward** [comment]
I changed the autosave to on_focus_change as indicated in the video.

https://github.com/zed-industries/zed/assets/567927/ab68f03b-9eff-4cc7-a897-fbaed082a09d

[log.txt](https://github.com/user-attachments/files/15921417/log.txt)

**Comment by mrnugget** [comment]
Huh, interesting. I cannot reproduce, even with your exact config.

https://github.com/zed-industries/zed/assets/1185253/3a8be6e6-ae8a-45d2-a91d-daabc0489702

Wondering whether Peter is onto something here and the autoformatting fails. There's a lot of restarts and errors in your logs.

Can you try commenting out `format_on_save` and `formatter`?

**Comment by CharlesChen0823** [comment]
the difference is that, one config is in `workspace/.zed/settings.json` and another is in `~/.config/zed/settings.json`(which is global settings config)

**Comment by mike-ward** [comment]
I reduced the settings file to:
```
{
  "autosave": "on_focus_change"
}
```
and restarted the editor. Problem still occurs. Also removed the Vlang extension but problem remains.

Opened another project and added a local settings file as above and found `autosave` did not work there either.

Uninstalled and reinstalled `zed` via `Homebrew`. No change.

FWIW I found that `zed` displays my tabs as 2 spaces instead of 8 as specified in the settings file.

Anything else I can try?

**Comment by mrnugget** [comment]
> the difference is that, one config is in `workspace/.zed/settings.json` and another is in `~/.config/zed/settings.json`(which is global settings config)

Good catch!


> Anything else I can try?

Can you try adding the `settings.json` to your global Zed settings (`zed: open settings`)?

I'm wondering whether it's this issue: https://github.com/zed-industries/zed/issues/4432#issuecomment-2125443141

We still don't handle settings correctly when they're `.gitignore`d.

**Comment by mike-ward** [comment]
Moving `autosave` to global settings worked!

**Comment by mrnugget** [comment]
Okay, so last bit to confirm: the local settings were `.gitignore`d?

**Comment by mike-ward** [comment]
If I understand the question about .`gitignore`, then no. Here's the project `.gitignore` for reference
```
*/lsv
bin
```

**Comment by bigdahaut** [comment]
An example of settings.json file:
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "assistant": {
    "default_model": {
      "provider": "ollama",
      "model": "codegemma:latest"
    },
    "version": "2"
  },
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark"
  },
  "autosave": {
    "after_delay": {
      "milliseconds": 500
    }
  }
}
