### ISSUE TITLE
Rename `Reveal in Finder` context menu option to something more generic

### ISSUE THREAD

**Issue by wpkelso** [zed-industries/zed#13322]
### Check for existing issues

- [X] Completed

### Describe the feature

With the expansion of Zed into Linux support, it doesn't make sense to use a MacOS specific term for a general action, opening the system file explorer to the selected file. Perhaps something such as `Show/Reveal in Files` would work better and not require OS-specific (although admittedly widespread) knowledge of an application name. 

Another option I can think of would be to name the option based on the in-use OS, where MacOS would use `Reveal in Finder`, and other systems could use `Reveal in Files`.

**Comment by mikayla-maki** [comment]
dup: https://github.com/zed-industries/zed/issues/12776
