### ISSUE TITLE
Snippets: show word-based completions from the current buffer

### ISSUE THREAD

**Issue by piechologist** [zed-industries/zed#13334]
### Check for existing issues

- [X] Completed

### Describe the feature

Great to see the new built-in [Snippets extension](https://github.com/zed-industries/simple-completion-language-server/tree/main)!

My feature request: I'd like to see completions from the current buffer e.g., `a_long_descriptive_variable_name` declared somewhere in the buffer should be suggested when typing the first few characters.

I've used the [scls extension](https://github.com/d1y/simple-completion-zed) (many thanks to @d1y!) that provides this functionality. Both `scls` and the built-in `Snippets` are based on the same LS so, it may be straightforward to implement it.

I noticed that putting the following block into `~/.config/zed/settings.json` has no effect:
```json
  "lsp": {
    "snippet-completion-server": {
      "initialization_options": {
        "max_completion_items": 20, 
        "snippets_first": false,
        "feature_words": true,
        "feature_snippets": true,
        "feature_paths": true,
        "feature_unicode_input": false
      }
    }
  }
```
but the same config for `scls` does work.

**Comment by osiewicz** [comment]
Hey,
I've [explicitly disabled](https://github.com/zed-industries/zed/blob/main/extensions/snippets/src/snippets.rs#L109) this feature in initialization options as I've found it to be quite noisy. However, the fact that scls is not reading your settings and respecting them is a bug. I'll address that and you'll be able to enable word completions if you wish.
