### ISSUE TITLE
Pasting changes indentation (making it really hard to edit YAML)

### ISSUE THREAD

**Issue by fasterthanlime** [zed-industries/zed#13338]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

  * Copy a bunch of lines from a YAML document
  * Paste them
  * Unless you were on a line with the EXACT SAME indentation level, the freshly-pasted lines are magically re-indented (to be wrong)

https://github.com/zed-industries/zed/assets/7998310/34795ea2-02b5-4e86-9433-735582208375

I believe this was previously reported as #12236 but _with vim mode on_, then it was (incorrectly) assigned the "vim" tag.

My recording is with vim mode off (although I usually have it on) — this is a larger issue I've encountered a lot.

For languages like Rust it's usually no issue since rustfmt will take care of it on next save — but for YAML, I find myself constantly undoing auto-indentation on paste, since it changes the semantics of the file quite a bit, as I'm sure you know 🥲

### Environment

Zed: v0.141.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Pasting should not, ever, change the indentation of code I paste.

I mean, make it an opt-in setting if you want, but for YAML it feels like it's never the right thing to do.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

(N/A)

**Comment by fasterthanlime** [comment]
Still present on 0.141.1 for me!


https://github.com/zed-industries/zed/assets/7998310/ae428c14-6497-4dd0-b9cf-cdf6b37b82d3


---


Zed: v0.141.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by NotSoClassy** [comment]
This also causes issue in other languages, copy and pasting becomes really slow because you have to get rid of all the indents. There should be an easy way to disable this. 
https://github.com/zed-industries/zed/discussions/9364_

**Comment by camilonova** [comment]
This is really annoying. Pasting should not change the content being pasted.

**Comment by maxbrunsfeld** [comment]
Ok, now we specifically disable auto-indent on paste for YAML (and Markdown). That'll go to preview on Wednesday.

**Comment by alexkirsz** [comment]
I'm seeing a similar issue in Rust and RON code since recently. When pasting code, the indentation of all lignes is shifted left a few times.

**Comment by LaTrissTitude** [comment]
Same problem in Python
