### ISSUE TITLE
Add Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by hedonistrh** [zed-industries/zed#13357]
### Check for existing issues

- [X] Completed

### Describe the feature

Anthropic team just announced https://www.anthropic.com/news/claude-3-5-sonnet. I am currently using Claude 3 Opus as my AI assistant in the Zed and curious that when we can have Claude 3.5 Sonnet as that is cheaper and better. Also works very well with my use-cases.

**Comment by JosephTLyons** [comment]
Closed via: https://github.com/zed-industries/zed/pull/13371

**Comment by ligmaSec** [comment]
it looks like it is not accepting api keys, nothing happens when pressing enter on version 0.142.4

**Comment by ejpir** [comment]
Open your settings file and add this:

`
{
  "assistant": {
    "version": "1",
    "provider": {
      "default_model": "claude-3-5-sonnet",
      "name": "zed.dev"
    }
  }
}
`

Restart Zed, goto assistant, switch to sonnet, input key. save. restart.

**Comment by kreas** [comment]
Thanks, @ejpir. Now Claude is showing up as the assistant, but nothing happens when I go to reset my key.
