### ISSUE TITLE
Stop relying on binary location to be in `libexec` on Linux

### ISSUE THREAD

**Issue by Zollerboy1** [zed-industries/zed#13360]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, the Linux CLI searches for the main binary at `<cli_binary_dir>/../libexec/zed-editor`. However, some distros like Arch [discourage the use of `libexec`](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette) and recommend packagers to use `lib/<pkg_name>` instead.

You can see [here](https://aur.archlinux.org/cgit/aur.git/tree/use-lib-not-libexec.patch?h=zed-preview) that the `zed-preview` AUR package has to patch the zed source, to be able to put the main binary in the recommended directory. However, as the maintainer of the `zed-preview-bin` package, I don't have this option, as I'm using the binaries as they are distributed on the Zed website.

This situation could be improved if the CLI simply searched for the main binary in both the `libexec` and the `lib/zed` directories.

**Comment by mrnugget** [comment]
I think this has been fixed by https://github.com/zed-industries/zed/pull/13083, right?

**Comment by Zollerboy1** [comment]
@mrnugget I don't think so. This PR only silences an error with finding the `git` binary. It doesn't change the fact that the CLI expects the main binary to be in `libexec`.

Currently, I'm working on something else, but later today, I will create a PR that fixes this.

**Comment by Zollerboy1** [comment]
@mrnugget this issue has nothing to do with a `git` binary (and I don't know how you got the impression that it does). The CLI expects the `zed-editor` executable to be located at `<cli_binary_dir>/../libexec/zed-editor` and falls back to searching for `zed` in the same directory as the CLI executable as you can see here: 

https://github.com/zed-industries/zed/blob/9bdb154a9b7df8e0dc04f4e5dcc323b5d29062d3/crates/cli/src/main.rs#L188-L201
