### ISSUE TITLE
FAILED TO LAUNCH: ~/.config permissions.

### ISSUE THREAD

**Issue by icecatuk** [zed-industries/zed#13365]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

downloaded fine, when try to open it I get "Could not create directory "/Users/kevinodonnell/.config/zed": Permission denied (os error 13)

For help resolving this, please open an issue on https://github.com/zed-industries/zed"

### Environment

Could not create directory "/Users/kevinodonnell/.config/zed": Permission denied (os error 13)

For help resolving this, please open an issue on https://github.com/zed-industries/zed

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Likely the permissions on your ~/.config directory are incorrect.

Please try:
```
ls -lad ~/.config
chown $(whoami):staff ~/.config
chmod +uwrx ~/.config
ls -lad ~/.config
```
And try again.

**Comment by notpeter** [comment]
I'm going to close this. If you continue to have the issue, feel free to reopen.
