### ISSUE TITLE
The remote projects dialogue box "leaks" the panel mouse interactions below

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#13361]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

_<Title and screencast>_

### Environment

Zed: v0.142.0 (Zed Nightly fefc91c6ad60eda7d6e775d19962634bbb9b57de)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/22a70226-7c9c-489f-a911-08456e460954

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Wonder if these are the same issues:

- https://github.com/zed-industries/zed/issues/13294

**Comment by notpeter** [comment]
These panels have been entirely reworked as part of the new SSH remoting.
If you see this is a current release, please open a clean issue.

Thanks for reporting.
