### ISSUE TITLE
Selection jitter

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#13362]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

[录屏2024-06-21 20.51.26.webm](https://github.com/zed-industries/zed/assets/19868292/1423e0fb-99bf-41ce-a4da-4d3507362722)

### Environment

Zed: v0.141.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I was able reproduce this behavior.  It appears once the mouse crosses horizontally into the scroll bar (or further to the right of the window) things get really janky.  Thanks for reporting.

**Comment by RemcoSmitsDev** [comment]
This might be related: https://github.com/zed-industries/zed/issues/12679

**Comment by notpeter** [comment]
I am no longer able to reproduce this and I believe it has been fixed. 
Please comment if that is incorrect and I'm happy to reopen.
Thanks for reporting.
