### ISSUE TITLE
Move cursor when pressing PageUp or PageDown

### ISSUE THREAD

**Issue by exo-cortex** [zed-industries/zed#13389]
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode using the "PageUp" or "PageDown" keys moves also moves the cursor up and down. 
Zed does not do this and it is very annoying. When quickly scanning a file to find a relavent line I then have to nevigate there again with the arrow-keys (and have to find it again).
Especially on Thinkpad-like keyboards (where PageUp/Down keys are directly above the arrow-keys this a way of navigating files quickly that I (and presumably) many people use _constantly_.

**Comment by notpeter** [comment]
PageUp/PageDown works for me on MacOS/Linux with the default keybindings:

https://github.com/zed-industries/zed/blob/00a505e41a67de9f1093353cf7591ebc71857862/assets/keymaps/default-macos.json#L62-L73

1. Are you using one of the alternate base keybinds (JetBrains, Atom, textMate, etc)? It appears PageUp/PageDown are not mapped by default in all of those.

2. Are you by chance using using an international keyboard other than `en_US`?

3. Can you paste your Zed version and platform information ("zed: copy system specs into clipboard" from the command palette)?

Thanks

**Comment by exo-cortex** [comment]
Hm does this also work, if I have nothing besides your suggested data in my keymap.json ?

**Comment by notpeter** [comment]
> Hm does this also work, if I have nothing besides your suggested data in my keymap.json ?

It should.  Our `keymap.json` will only to override values provided by your default keymap (cmd+shift+p `zed: open default keymap`).  You don't need to provide a full keymap or anything.

I just now edited the keymap snippet above to match your desired configuration (pgup/pgdown moves the selection cursor up/down a page).  Previously I had just pasted the defaults (shift+pageup/shift+pagedown doing the same).

Let me know if it works.

**Comment by notpeter** [comment]
Previously: 
- https://github.com/zed-industries/zed/issues/8993

**Comment by exo-cortex** [comment]
Oh, I did search quite a while but didn't find this one. Sorry for that.

**Comment by exo-cortex** [comment]
Hey! It *does* work! great!!! (sorry for the late answer. I didn't have time to test it until now!)

**Comment by notpeter** [comment]
Great! With #13510 it'll be this way by default in next week's preview and in stable (0.143.x), Wednesday 2024-07-10 if all goes well. Thanks for reporting!
