### ISSUE TITLE
When changing the ollama model, `api_url` and `low_speed_timeout_in_seconds` is set to `null`

### ISSUE THREAD

**Issue by MerLant** [zed-industries/zed#13399]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. In the `settings.json` set your `api_url` and `low_speed_timeout_in_seconds` for the ollama server
2. In the `Assistant Panel`, select a different model
3. In the `settings.json` `api_url`  and `low_speed_timeout_in_seconds` has become `null`

### Environment

Zed: v0.140.5 (Zed)
OS: macOS 14.5
Memory: 8 GiB
Architecture: ARM

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/63600624/5b221113-5e88-42c5-97bd-601a7e499c7c

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by MerLant** [comment]
I also noticed that when changing the model, it becomes null and `low_speed_timeout_in_seconds`

**Comment by MerLant** [comment]
The bug hasn't gone anywhere Zed 0.141.3
`eadb45467d9600f0a2163554a1b23cb9d24eb4cf`

**Comment by MerLant** [comment]
@rtfeldman, please open issues, the bug is not fixed in the latest release 0.141.3

**Comment by rtfeldman** [comment]
Reopened!

**Comment by MerLant** [comment]
Everything was fixed in 0.142.4. 

(Sorry, I didn't fully understand the versions. pre 0.142.3 goes to 0.142.4, not to pre 0.142.3)
