### ISSUE TITLE
Add this indentation mark

### ISSUE THREAD

**Issue by Linyuqiz** [zed-industries/zed#13398]
### Check for existing issues

- [X] Completed

### Describe the feature

Add this indentation mark
<img width="533" alt="image" src="https://github.com/zed-industries/zed/assets/48901168/c16dae5c-7eea-4917-b3e5-883405046362">

**Comment by amtoaer** [comment]
This is already implemented. Add those settings to enable it:
```json
"indent_guides": {
  "enabled": true
  // if you want rainbow color indent, add the line below:
  // "background_coloring": "indent_aware"
}
```
<img width="1102" alt="image" src="https://github.com/zed-industries/zed/assets/32017007/d0df109a-3e7d-4a2d-a844-d84c02910758">

**Comment by Linyuqiz** [comment]
ok, i update
