### ISSUE TITLE
Zed crashes my terminal when running for release

### ISSUE THREAD

**Issue by Landon-Kuehner** [zed-industries/zed#13405]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My terminal crashes when building zed for a release build. There is nothing more to say than that. 
I have set alacritty to 3x verbose logging mode and set it to log to a file but it crashes without giving any logs.

### Environment

OS: Arch Linux x86_64
Host: Predator PH315-54 V1.15
Kernel: 6.9.5-arch1-1
Uptime: 6 hours, 52 mins
Packages: 977 (pacman)
Shell: bash 5.2.26
Resolution: 1920x1080
DE: Plasma 6.1.0
WM: kwin
Terminal: alacritty
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz
GPU: Intel TigerLake-H GT1 [UHD Graphics]
GPU: NVIDIA GeForce RTX 3050 Ti Mobile

**Comment by notpeter** [comment]
That's surely odd!

1. Does it crash when building other Terminal apps (Konsole, etc) too?
2. Do you know where in the build process it happens / is it consistent?
3. How did you install alacritty? `cargo install alacritty`, built from source, or other?

**Comment by Landon-Kuehner** [comment]
1. It does crash konsole
2. It happens somewhere within these packages: `assistant, search, extensions_ui, vim, outline, vcs_menu, command_palette, project, terminal_view, copilot, editor, auto_update, inline_completion_button, workspace, recent_projects, extension`
3. I have alacritty installed from arch/extra

**Comment by Landon-Kuehner** [comment]
It is no longer crashing my terminal. I changed nothing.
