### ISSUE TITLE
Linux X11: 100% CPU usage when idle

### ISSUE THREAD

**Issue by VitorRamos** [zed-industries/zed#13409]
### Check for existing issues

- [X] Completed

### Description

After [this pull request](https://github.com/zed-industries/zed/pull/13355), I am experiencing 100% CPU usage while Zed is idle. The issue appears to be caused by the change in `crates/gpui/src/platform/linux/x11/client.rs` at line 294, where `calloop::Interest::READ` was changed to `calloop::Interest::BOTH`.

With `calloop::Interest::READ`:
![both](https://github.com/zed-industries/zed/assets/14364925/da31848a-67e8-4c62-927c-a390c3ecefc2)

With `calloop::Interest::BOTH`:
![read_only](https://github.com/zed-industries/zed/assets/14364925/5ea834d2-671a-4720-997b-7e5a5bf690d2)

### Environment

Zed: v0.142.0 (Zed Dev fe7d53cb9695d04802babe9850fc1c432ca9c40e)
OS: Linux X11 ubuntu 22.04
Memory: 31.2 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mwotton** [comment]
also seeing this behaviour, can confirm that changing the line back fixes it.
