### ISSUE TITLE
Unexpected ANSI codes in terminal input after running `git log` in Zed's integrated terminal

### ISSUE THREAD

**Issue by prettyirrelevant** [zed-industries/zed#13418]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Zed's integrated terminal, running `git log` causes unexpected behavior in subsequent terminal input. ANSI color codes appear in the input line, interfering with normal command entry.

Steps to reproduce:
1. Open Zed editor
2. Open the integrated terminal
3. Navigate to a Git repository
4. Run the command `git log`
5. Press Enter to exit the log view
6. Attempt to type a new command

The terminal input will be populated with ANSI codes (e.g., `]10;rgb:ffff/ffff/ffff]11;rgb:1010/1010/1010`), making it difficult to enter new commands. This issue does not occur in other terminal emulators like WezTerm or iTerm2, suggesting it's specific to Zed's terminal implementation.

> **Note**: I have [https://github.com/dandavison/delta](delta) installed.

### Zed Integrated Terminal.
![image](https://github.com/zed-industries/zed/assets/72208758/5473829f-f432-4bdc-beac-0f87262345a0)

### Wezterm
<img width="620" alt="image" src="https://github.com/zed-industries/zed/assets/72208758/194bc65d-1aa9-49f9-bf3b-c370b0678550">

### Environment

Zed: v0.140.5 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by apricotbucket28** [comment]
Are you using git-delta? I solved this by changing
```gitconfig
[core]
    pager = delta
```
in `~/.gitconfig` to:
```gitconfig
[core]
    pager = delta --dark
```
(original issue: https://github.com/zed-industries/zed/issues/11700)

**Comment by prettyirrelevant** [comment]
> Are you using git-delta? I solved this by changing
> 
> ```gitconfig
> [core]
>     pager = delta
> ```
> 
> in `~/.gitconfig` to:
> 
> ```gitconfig
> [core]
>     pager = delta --dark
> ```
> 
> (original issue: #11700)

thanks, this worked.
