### ISSUE TITLE
Zed Fails to Launch

### ISSUE THREAD

**Issue by arashmoini** [zed-industries/zed#13426]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I downloaded the latest release of Zed for Apple Silicon (0.140.5), but I can't seem to open the app. The error I get is the following: "Could not create directory "/Users/Name/.config/zed": Permission denied (os error 13). For help resolving this, please open an issue on https://github.com/zed-industries/zed."

### Environment

MacOS Sonoma 14.5
Apple M3 Pro
18 GB RAM
512 GB Storage

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
See also #13365

**Comment by arashmoini** [comment]
Thanks for the reply. I tried the commands but unfortunately they didn't work.

**Comment by notpeter** [comment]
Hi @arashmoini, can you try manually creating the zed config directory and paste if you get an error:

```
mkdir -p ~/.config/zed
ls -lad ~/.config/ ~/.config/zed/
```

Thanks

**Comment by arashmoini** [comment]
Hey @notpeter, I ran the commands and get an error saying that permission is denied. I'm thinking it has something to do with the Sharing and Permissions settings of the .config folder, but I checked those and they all looked good to me.

**Comment by notpeter** [comment]
@arashmoini Yes.  The permissions on your `.config` are such that your user does not have rights to create subdirectories under `.config`.  If you have local administrator/sudo rights you should be able to do the following:

```shell
sudo chown $(whoami):staff ~/.config
chmod +uwrx ~/.config
```

Note, the command in the other issue was previous incorrect -- I failed to include `sudo` for the chown command.  Can you try this and see if it works?  Additionally, if you paste the output of `ls -lad ~/.config/ ~/.config/zed/` I could confirm my hypothesis.

**Comment by jansol** [comment]
Even if `~/.config` is fine, `~/.config/zed` (and everything in it) also needs to be correct. Which I guess it might not be if you happened to run Zed with `sudo` at some point... (don't do that)

**Comment by arashmoini** [comment]
Zed seems to open up fine now! Even though this is the output from the `ls` command: `ls: /Users/arashmoini/.config/zed/: No such file or directory
drwxr-xr-x  3 arashmoini  staff  96 28 May 08:53 /Users/arashmoini/.config/`.  It seems the command created the config folder but I just couldn't access it using `ls`.

Thanks for your help, everyone!
