### ISSUE TITLE
Is there any way to prevent Pyright from displaying some unnecessary errors?

### ISSUE THREAD

**Issue by miller-star** [zed-industries/zed#13438]
### Check for existing issues

- [X] Completed

### Describe the feature

Pyright always reports errors for some correctly used syntax, and the same code is indeed normal in vscode. Is there any way to prevent this error from being displayed?
<img width="1439" alt="XiaojunScreenshot2024-06-24 09 33 32" src="https://github.com/zed-industries/zed/assets/45729654/d008d9aa-766c-4c1c-b4e5-38ff8d4e25c0">
<img width="1377" alt="XiaojunScreenshot2024-06-24 09 38 08" src="https://github.com/zed-industries/zed/assets/45729654/1fe747af-ba1b-4457-8f21-939496c96f4d">

**Comment by amtoaer** [comment]
Add a file called "pyrightconfig.json" in the root of your project, set "typeCheckingMode" to "off".
Reference: [Pyright Configuration](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

**Comment by miller-star** [comment]
> typeCheckingMode"

Thanks for your answer, I have solved the problem.

**Comment by miller-star** [comment]
Thanks for @amtoaer 's answer, let's close the issue

**Comment by sirix-v** [comment]
Is there another solution? It's a bit troublesome to add a pyrightconfig.json file every time.
