### ISSUE TITLE
When editing a Markdown file, the editor cannot display it fully.

### ISSUE THREAD

**Issue by jnan77** [zed-industries/zed#13439]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing an xxx.md Markdown file using Zed 0.140.5, there is always a blank area on the right side that cannot be used, and I haven't found a way to close it. This issue does not occur when editing other files.

### Environment

![iShot_2024-06-24_10 38 01](https://github.com/zed-industries/zed/assets/1492675/4bb0bb9d-c9c8-4e56-b039-0aef2e60588a)

MacBookPro 16-inch, 2019

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Those are the line wraps.

It looks like markdown language support enforces them to be of a `preferred_line_length` size taken from the settings:
https://github.com/zed-industries/zed/blob/73f746062f4728f6ea9a2a34cdbaecdfead5180f/crates/languages/src/markdown/config.toml#L16

which is 80 by default.

This added to settings.json will apply Zed's defaults to markdown too:
```json
"languages": {
    "Markdown": {
      "soft_wrap": "prefer_line",
    },
}
```

and here are all options available:

```
// How to soft-wrap long lines of text. This setting can take
// three values:
//
// 1. Do not soft wrap.
//      "soft_wrap": "none",
// 2. Prefer a single line generally, unless an overly long line is encountered.
//      "soft_wrap": "prefer_line",
// 3. Soft wrap lines that overflow the editor:
//      "soft_wrap": "editor_width",
// 4. Soft wrap lines at the preferred line length
//      "soft_wrap": "preferred_line_length",
"soft_wrap": "prefer_line",
```

Alternatively, settings.json can get some override for this, which will apply to markdown too.

**Comment by jnan77** [comment]
> 这些是换行。
> 
> 看起来 Markdown 语言支持强制它们的大小取自设置：`preferred_line_length`
> 
> https://github.com/zed-industries/zed/blob/73f746062f4728f6ea9a2a34cdbaecdfead5180f/crates/languages/src/markdown/config.toml#L16
> 
> 默认为 80。
> 
> 添加到settings.json中也会将 Zed 的默认值应用于 Markdown：
> 
> ```json
> "languages": {
>     "Markdown": {
>       "soft_wrap": "prefer_line",
>     },
> }
> ```
> 
> 以下是所有可用的选项：
> 
> ```
> // How to soft-wrap long lines of text. This setting can take
> // three values:
> //
> // 1. Do not soft wrap.
> //      "soft_wrap": "none",
> // 2. Prefer a single line generally, unless an overly long line is encountered.
> //      "soft_wrap": "prefer_line",
> // 3. Soft wrap lines that overflow the editor:
> //      "soft_wrap": "editor_width",
> // 4. Soft wrap lines at the preferred line length
> //      "soft_wrap": "preferred_line_length",
> "soft_wrap": "prefer_line",
> ```
> 
> 或者，settings.json可以为此获得一些覆盖，这也适用于降价。

I have confirmed that the fix is working. Thank you so much for your help!
