### ISSUE TITLE
"active_line_width" option in settings.json seems not working

### ISSUE THREAD

**Issue by tibitTW** [zed-industries/zed#13443]
### Check for existing issues

- [x] Completed

### Reproduce Steps:

1. add these configs in ~/.config/zed/settings.json

```json
    "indent_guides": {
        "active_line_width": 10
    },
```

### Expected Results:

the width of activated indent line should become 10

### Actual Results:

nothing changed

### Environment

Zed: v0.140.5 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1552" alt="SCR-20240624-kkde" src="https://github.com/zed-industries/zed/assets/39118448/88a33043-1bbd-4f5d-9d93-2b0354327e30">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/15949445/Zed.log)

</pre></details>

**Comment by notpeter** [comment]
Hi @tibitTW, it appears this is a new feature that was only recently merged last week:
- https://github.com/zed-industries/zed/pull/13210

It will be included in the next Preview release (Wednesday 2024-06-26).
Stable will get it the following week (Wednesday 2024-07-03). 

Here's what it will look when it works:
<img width="553" alt="image" src="https://github.com/zed-industries/zed/assets/145113/4ea912ab-ce85-4d26-83f9-fd49562ef8f4">

Apologies about the docs being ahead of stable, please bear with us until we figure out how to best annotate required versions in documentation for new settings. Very happy to see people using new features.  Thanks!

**Comment by tibitTW** [comment]
Thanks for your response, I'd like to try it after release :)
