### ISSUE TITLE
[Linux] *nix distribution does not remember the list of recently opened projects.

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#13448]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to see ZED remember the list of recently open projects. Currently Linux distribution does not allow to view it.

**Comment by ConradIrwin** [comment]
@krstp It should show up in the recent projects menu in the top left (ctrl-alt-o on linux). Does that not work for you?

If not, could you please share details about your zed install from `ctrl-shift-p "copy system specs into clipboard"`.

**Comment by krstp** [comment]
Indeed it does work. There is one condition though, the project must be git instantiated `git init`, otherwise it will not recognize. Thanks for helping verify that.
