### ISSUE TITLE
Apply the "include path" in Search when selecting the folder in the tree-view and pressing CMD+Shift+F

### ISSUE THREAD

**Issue by deep-cognite** [zed-industries/zed#13454]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, I have to open the global search, press the filter button, type in the path, and then search. 
However, I'd like to select the specific folder in the tree view and press CMD+Shift+F to automatically fill in the "include" filter, and then search.

I use this feature a lot in Webstorm since we're working in a monorepo (and do not care to search within other apps/libs).

**Comment by SomeoneToIgnore** [comment]
I believe what you're looking is a `Find in Folder` context menu item (`project_panel::NewSearchInDirectory` action)

<img width="484" alt="Screenshot 2024-06-24 at 11 13 35" src="https://github.com/zed-industries/zed/assets/2690773/1f4cbb82-38fc-4743-89b1-289bac9d09bb">

<img width="1387" alt="Screenshot 2024-06-24 at 11 13 40" src="https://github.com/zed-industries/zed/assets/2690773/d661ddda-0594-4708-903a-645239592524">

**Comment by deep-cognite** [comment]
🤦 Yes- Thank you @SomeoneToIgnore
