### ISSUE TITLE
[Snippet] variables support

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#13456]
### Check for existing issues

- [X] Completed

### Describe the feature

https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables

If variable support is implemented, the functionality can be better extended.

Use example

https://stackoverflow.com/questions/65156083/implement-vscode-snippet-for-c-header-guard

**Comment by osiewicz** [comment]
Duplicate of: https://github.com/zed-industries/zed/issues/13301
