### ISSUE TITLE
Ability to collapse/expand all code structures in the code editor

### ISSUE THREAD

**Issue by arielf-camacho** [zed-industries/zed#13472]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has a very useful feature, it, with a key combination in the keyboard, collapses and with another combination expands, all code structures recursively. The closest we have in Zed right now, is Fold lines which only collapses the code structure the cursor stands at, and unfold which does the opposite. Collapsing a whole file with hundreds of code structures (blocks) is tedious using this. That's why I request having the same feature from VSCode if and when possible. Thanks.

### If applicable, add mockups / screenshots to help present your vision of the feature

This is what the VSCode editor looks after collapsing all blocks.

<img width="1126" alt="image" src="https://github.com/zed-industries/zed/assets/11684553/f3b45a61-24ab-45ff-aec5-9b79582fe7ea">

And then, you can expand blocks as needed. Very useful for readability and organization.

The: `editor: fold selected ranges` command in Zed, does not behave the same, it collapses the selection, but, when expanded, it expands it all, and does not allow you to block by block expand (this is what VSCode does).

**Comment by notpeter** [comment]
Zed supports this, but we hide the arrows in the sidebar until you hover:
<img width="577" alt="Screenshot 2024-06-24 at 14 50 51" src="https://github.com/zed-industries/zed/assets/145113/33c32bff-2ac1-4c6f-bdae-8b6a5a20f58e">

It's somewhat dependent on the language / language-server being used.

Can you confirm whether the current Zed functionality for golang matches your expectations or provide details of what you're looking for. Thanks.

**Comment by lee-hyunkyu** [comment]
The request (as I understand it) is to have a keyboard shortcut / command palette action to do the folding without needing to click on each arrow inside the gutter. In the example given, if I wanted to close all of the `if` statements, I would need to click 4 times. Perhaps not a big deal in that specific case but this does become a tedious chore in a 1000 line file with dozens of functions that I want to collapse. 

VSCode and Sublime both have "fold level" commands that will automatically fold code under a "level". Level 1 is any top level code, level 2 is one indentation below level 1, and so on and so forth (hopefully the examples below demonstrate this behavior)

```py
# original
def foo(bar):
    if bar:
        if bar > 10:
            print(bar)
        else:
            raise Exception(bar)
    elif bar == 0:
        print(bar)
```

```py
# fold to level 1
def foo(bar): [...]
```

```py
# fold to level 2
def foo(bar):
    if bar: [...]
    elif bar == 0: [...]
```

```py
# fold to level 3
def foo(bar):
    if bar:
        if bar > 10: [...]
        else: [...]
    elif bar == 0:
        print(bar)
```

**Comment by notpeter** [comment]
I see.  Zed supports simple folding and unfolding at the current cursor point with `cmd+alt+[` and `cmd+alt+]` but does not support all the same [folding features of vscode](https://code.visualstudio.com/docs/editor/codebasics#_folding).

There is an existing tracking an enhancement request for folding:
- https://github.com/zed-industries/zed/issues/5142

Please 👍 to vote for that issue and subscribe to track it's progress. 

Thanks @lee-hyunkyu for helping me better understand.
Thanks @arielf-camacho for reporting.

**Comment by lutogin** [comment]
I till can't collapse imports, it's unconcenient
