### ISSUE TITLE
Project search breaks on regex lookbehind/lookahead group constructs

### ISSUE THREAD

**Issue by jaydenseric** [zed-industries/zed#13486]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With this sort of regex search query using negative lookbehind:

```regex
(?<!user|tenant)RecordId = randomUUID\(\);
```

I would expect to be able to match in the last two lines:

```js
const tenantRecordId = randomUUID();
const userRecordId = randomUUID();
const fooRecordId = randomUUID();
const barRecordId = randomUUID();
```

But the Zed search input becomes red, and refuses to search when there is regex negative lookbehind syntax in the search query:

<img width="482" alt="Screenshot 2024-06-25 at 1 32 01 PM" src="https://github.com/zed-industries/zed/assets/1754873/787f83a4-4498-4359-9176-ccdfb658036c">

It's super useful to be able to use regex lookbehind/lookahead group constructs when project searching while refactoring.

### Environment

Zed: v0.141.2 (Zed Preview)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
Hey,
We don't support lookbehind at the moment. We're using https://docs.rs/regex/latest/regex/ under the hood, and it's docs explicitly state:
> The regex syntax supported by this crate is similar to other regex engines, but it lacks several features that are not known how to implement efficiently. This includes, but is not limited to, look-around and backreferences. In exchange, all regex searches in this crate have worst case O(m * n) time complexity, where m is proportional to the size of the regex and n is proportional to the size of the string being searched.

**Comment by jaydenseric** [comment]
I don't understand why you are closing this as not planned. There are multiple ways to do better here than just close the issue:

- Use a more capable rust crate for doing regex with lookaheads/lookbehinds. They exist, e.g. https://crates.io/crates/fancy-regex .
- Update the UI so that if a search regex is valid regex, but it's using regex features that Zed doesn't support yet, instead of just making the input an invalid red state, show a validation message explaining what is wrong so the user can stop attempting to debug their regex syntax which is actually perfectly valid.

As an anecdotal sample, In the last couple of weeks, both me and my immediate colleague have been using regex searches with lookbehind/lookahead group constructs to do find and replace refactoring in projects with hundreds of modules. It's not an edge case thing; today I had to fire up VS Code and use its regex find and replace because Zed doesn't have the capability.

**Comment by exalted** [comment]
I, too, would like to see ahead and look behind support in the search.

I think this issue would classify as a UX defect/bug/issue. However, there is also a feature request here. I hope we can capture both intents.

**Comment by christian-gama** [comment]
The lack of information about my Regex being "wrong" was driving me nuts. I thought I was doing something wrong when trying to create a lookbehind regex, because Zed was giving me a red box, indicating that the regex is wrong, but its not actually wrong, its not supported. It should have this information in the docs or an actual UI message telling that this is not supported (maybe another color, such as orange/yellow).

**Comment by crepantherx** [comment]
please, we also want to fully switch to zed, but hickups like (notebook not supported, and regex don't work even as sublime)  these are holding that to happen, now I am on a verge to uninstall it, as I am just carrying it's installation in my PC without using it(waiting for it to support) things which are really necessary.

**Comment by zerolincku** [comment]
This is definitely a basic function needed.

**Comment by marcospb19** [comment]
`fancy-regex` (the crate which supports look-arounds) and `regex` (the crate Zed currently uses) both depend on the same `regex-automata` engine and `regex-syntax` parser, so, it's possible to have both without adding "bloat".

A possible solution for user-given patterns is: always use `regex`, but fallback to `fancy-regex` if the pattern compilation fails.

(I'm assuming that `regex` can be faster even for a pattern that compiles in both crates)

**Comment by nicolasembleton** [comment]
It would be really nice to have this feature. It's very powerful for mass search / replace. A bit "niche" in terms of addressable user base, but definitely an important power-feature.

**Comment by tknx** [comment]
Came here to find this... Do I care if an algorithm is "inefficient" for a computer when the alternate is it being very inefficient for me to manually do stuff? Not one bit. Please reconsider.
