### ISSUE TITLE
Not opening on my Apple Silicon M3 laptop.

### ISSUE THREAD

**Issue by ritankarsaha** [zed-industries/zed#13488]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On opening the app, the app crashes instantly showing that it could not create config files over in my laptop

<img width="1086" alt="Screenshot 2024-06-25 at 11 12 18 AM" src="https://github.com/zed-industries/zed/assets/136831315/de47cf74-5f54-442b-a4b8-06439fbaf641">

### Environment

Mac os M3 chip. 

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi, the permissions on your `~/.config` folders are likely incorrect. Usually this occurs when the folder was previously created by a process (incorrectly) being run as run/via sudo.  You can fix these permissions by running:

```
sudo chown $(whoami):staff ~/.config
chmod +urwx ~/.config
mkdir -p ~/.config/zed
```

See also:
- #13271
