### ISSUE TITLE
Rust autocomplete full path visibility

### ISSUE THREAD

**Issue by konstantinzolotarev** [zed-industries/zed#13494]
### Check for existing issues

- [X] Completed

### Describe the feature

Rust autocomplete doesn't show full module path for suggestions, and when there are several options with same name it's hard to understand what will be added.

For example writing opening autocomplete for `Result` that might be added from `anyhow::Result` or other it's impossible to know where `Result` is from. The only way is to try to guess by docs, but it's also very hard.

![Screenshot 2024-06-25 at 11 44 51](https://github.com/zed-industries/zed/assets/286431/0ad3a3e8-7811-4b0d-84ca-e0f8703c3223)

**Comment by osiewicz** [comment]
Hey, thanks for filling this issue. This actually looks like a regression from https://github.com/zed-industries/zed/pull/13043, as we don't read that field in Rust. Completions used to look as follows on last Stable:
![image](https://github.com/zed-industries/zed/assets/24362066/c4b1532a-2100-4f99-ac6d-f9a4ceac2b07)

**Comment by konstantinzolotarev** [comment]
Awesome !
Thank you very much !

**Comment by konstantinzolotarev** [comment]
Updated to latest Preview Release. `Zed 0.142.2`


Now some of suggestions has module names, but not all.

**Comment by konstantinzolotarev** [comment]
Updated to latest Preview Release. `Zed 0.142.2`


Now some of suggestions has module names, but not all. Not sure if it's expected behaviour.

![Screenshot 2024-06-28 at 15 43 16](https://github.com/zed-industries/zed/assets/286431/a917d807-cd13-48bf-ba0c-35e6a508df63)


![Screenshot 2024-06-28 at 15 43 36](https://github.com/zed-industries/zed/assets/286431/9316bd9b-d1ac-4ce6-bd91-210decf7b3c5)

**Comment by ynuwenhof** [comment]
I'm currently facing the same behavior on Zed Dev 0.143.0.

![image](https://github.com/zed-industries/zed/assets/100025337/735ea7a8-0a8b-4d0b-9bd8-4ede622ac33a)

**Comment by osiewicz** [comment]
Ok, I've screwed up. We prefer `.detail` field if it's available right now, whereas in reality we should grab `label_detail.detail` first.
I'll fix it promptly, here's a sneak-peek of my dev build:
![image](https://github.com/zed-industries/zed/assets/24362066/66f64b82-88f8-424e-a18d-0cfe4ff0e38d)
![image](https://github.com/zed-industries/zed/assets/24362066/0bfb83a7-f0d8-4c09-a757-78a7c98ff68b)

**Comment by konstantinzolotarev** [comment]
OMG, it's so awesome ! 
@osiewicz Thank you very much !!! It works like a charm.

**Comment by gngeorgiev** [comment]
@osiewicz I don't think this works as of `Zed 0.167.1` :/

<img width="772" alt="image" src="https://github.com/user-attachments/assets/4afe3da5-c86f-4640-b46d-cd16c5e19037" />
