### ISSUE TITLE
Autoclosing tag in jsx bug

### ISSUE THREAD

**Issue by kriskw1999** [zed-industries/zed#13495]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/71312948/cd75cb0d-78d2-4b44-9223-b11a3dd2aedb

I found this tricky bug in the autoclosing tag new feature, what happens is that when you have an exact same matching following tag that is opened and closed and you are going to create a new one the following closing tag is overridden. 

**NOTE**: this happens only when you have props on the component like `className` with the plain tag works perfectly, this because the LSP when finds the broken tree for some reason don't recognise anymore the tag with props as a standalone tag.

### Bug

```tsx
const MainSection = () => {
  return (
    <div className="main-container">
      <div className="aa">hello</div>
      <div
        <div className="aa">world</div>
    </div>
  )
}
```

### This works

```tsx
const MainSection = () => {
  return (
    <div className="main-container">
      <div className="aa">hello</div>
      <div
        <div>world</div>
    </div>
  )
}
```

### Environment

MacOS 14.1 (23B74)
Apple M2 Pro

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
This looks like a bug in VTSLS to me. Can you file an issue with them?

**Comment by kriskw1999** [comment]
Yes I think so, I will open an issue on their repo and track the progress here below 🚀

**Comment by osiewicz** [comment]
Oh, I've just checked and they simply forward the request to tsserver, so I guess there's not much they'll be able to do on that front. FWIW, VSCode has the same problem.

**Comment by kriskw1999** [comment]
For some reason I had an old version of tsserver running, the issue was solved here https://github.com/microsoft/TypeScript/pull/57132 . Apologise for the false allarm 🙏
