### ISSUE TITLE
Vim: word motion commands over kebab case strings broken in .tsx and .jsx files

### ISSUE THREAD

**Issue by tepavcevic** [zed-industries/zed#13515]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Executing word commands over a hyphenated string eg. `ciw` over `kebab-case-string`  doesn't only delete the word where the cursor is positioned, but acts as `ciW` and deletes the entire string. Same thing happens with yanking, selecting and deleting. Issue is not present in .ts, .json .js files, but .tsx, .jsx and .css files is.

### Environment

Zed: v0.141.2 (Zed Preview)
OS: Linux Wayland ubuntu 24.04
Memory: 15.4 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
@tepavcevic Thanks for reporting this! Vim mode in zed automatically sets word-characters to match the language you're editing. In css `-` is allowed as part of class names so zed takes the configuration from there.

In vim terms we automatically set `iskeyword` to match the language, which I think is a better default than the vim default (though we don't yet have a way to override it: PRs welcome!).

For tsx/jsx it looks like this is set to happen in all strings: https://github.com/zed-industries/zed/blob/d62b96c4a55f9fcaa7b2be21e78049d10339f4df/crates/languages/src/tsx/config.toml#L27 which seems like a bug (both of those settings should probably only apply to the html className I think). I'm not exactly sure how to fix that though without breaking tailwind completion.

**Comment by ribelo** [comment]
@ConradIrwin The exact same problem occurs in Clojure.

https://github.com/zed-industries/zed/blob/main/extensions/clojure/languages/clojure/config.toml#L12
