### ISSUE TITLE
Python formatter not working in remote project

### ISSUE THREAD

**Issue by cmditch** [zed-industries/zed#13527]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the below config, I'm not getting code formatting functionality in python when using the alpha Remote Project feature. I've confirmed this settings works for local projects. I've also tried using absolute paths for the `black` binary. Tried for both the path on the remote server and on my local machine.

```
{
  "languages": {
    "Python": {
      "formatter": {
        "external": {
          "command": "black",
          "arguments": ["-"]
        }
      }
    }
  }
}
```

### Environment

Zed: v0.141.2 (Zed Preview)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

The remote logs make no mention of `Formatting failed: failed to format via external command "black"`. The local logs only mention this when I'm editing code locally with a misconfigured formatting path, but nothing about the remote session.

**Comment by ConradIrwin** [comment]
This should be fixed by the new version of remoting that landed in v0.159.x; please let me know if not.

**Comment by ConradIrwin** [comment]
We currently only respect settings set in the server's `settings.json` for remoting. See also #20024

**Comment by vkramanuj** [comment]
Didn't notice the two different configs, everything works now. Thanks!
