### ISSUE TITLE
Comparison operators in TypeScript

### ISSUE THREAD

**Issue by diuming** [zed-industries/zed#13533]
### Check for existing issues

- [X] Completed

### Describe the feature

How Do I prevent Zed to modify my source code comparison operators, like ==, !=, ===, !==, => in TypeScript

Zed version:  0.140.5

![Screenshot 2024-06-26 at 9 17 11 AM](https://github.com/zed-industries/zed/assets/39903550/812e4ee2-551b-425b-aefe-9db3b4a33b12)

**Comment by notpeter** [comment]
These are [ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)) in our default font, [Zed Mono](https://github.com/zed-industries/zed-fonts) and do not modify the file, they are harmless and for display only.

If you don't like them, you can switch any other font installed on your computer by editing `buffer_font_family` in your settings.json:
```
{
  "buffer_font_family": "Monaco"
}
```

**Comment by diuming** [comment]
I got it!
Thanks

**Comment by diuming** [comment]
I got it!
Thanks
