### ISSUE TITLE
Add editor layout actions to file tab menu

### ISSUE THREAD

**Issue by konstantinzolotarev** [zed-industries/zed#13539]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently to be able to split editor into 2 cols you have to know hotkey or go to main menu `View -> Editor Layout -> Split ****` 
Is it possible to duplicate same split actions into file tab menu (clicking right mouse button on edit file name).
So it will be way more easier to move files/split windows without additional menu clicks.

Like this (sorry for my drawing skills):

![Screenshot 2024-06-26 at 13 30 57](https://github.com/zed-industries/zed/assets/286431/afa65ded-1656-4a49-b217-5cac834e547c)

**Comment by osiewicz** [comment]
While that's not exactly what you want, there's a "Split pane" button in the tab bar already:
<img width="463" alt="image" src="https://github.com/zed-industries/zed/assets/24362066/5f7846f8-27df-464e-9238-41c91bc56775">

**Comment by konstantinzolotarev** [comment]
Yeep, it's actually make sense, think issue might be closed unless there is a way to add `Move file to right` command there.
