### ISSUE TITLE
Vim: :s with visual select should replace within selection

### ISSUE THREAD

**Issue by mattfbacon** [zed-industries/zed#13535]
### Check for existing issues

- [X] Completed

### Describe the feature

In neovim, when you have a visual selection and you start to use `:s` (actually any command), the editor will automatically add `'<,'>`, which means, perform the action within the bounds of the selection. For `:s` that means it does the find-and-replace within the selection. Zed seems to only support certain types of replacements, but not this one. I don't know if it's within scope to actually use `'<` and `'>` or what, but either way I would like to be able to type `:s` while I have a visual selection and have it work.

### If applicable, add mockups / screenshots to help present your vision of the feature

See neovim's behavior

**Comment by JosephTLyons** [comment]
This should be landing in today's preview release.
