### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by bottlenecked** [zed-industries/zed#13544]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I regularly have 3-4 zed windows open of different projects, but this is the first time I saw the "Your system has run out of application memory" dialog. It seems zed was using 89GB of memory at that point.

There are a few other open tickets that match 'memory leak' right now, but only this one https://github.com/zed-industries/zed/issues/13190 is in the same ballpark. It could be the same as I did have a python project open at the time, along with 2 elixir ones, but I never opened a .toml file for editing in the last couple of days so I'm not sure.

I got a screenshot and a memory dump, not sure if it's going to be of any help though

![Screenshot 2024-06-26 at 3 17 30 PM](https://github.com/zed-industries/zed/assets/622973/01bde00e-e82f-41fc-8e2b-342c8338c5a0)
[zed_sample_89GB.txt](https://github.com/user-attachments/files/15988287/zed_sample_89GB.txt)

### Environment

Zed: v0.140.5 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I know this doesn't help now, but in the future in Activity Monitor you can toggle to see 'All Processes Hierarchically' which might help identify a particular subprocess which is ballooning memory.
<img width="278" alt="image" src="https://github.com/zed-industries/zed/assets/145113/132e1da2-b94e-4dc8-b323-61e7b6845d4d">
<img width="925" alt="image" src="https://github.com/zed-industries/zed/assets/145113/c373b7fa-48de-4576-9f40-6ad494e258b0">

**Comment by bottlenecked** [comment]
So it happened again just now and I expanded the process tree, nothing that immediately jumps out though

![image](https://github.com/zed-industries/zed/assets/622973/fd7f4a79-f8ec-4fe2-b51d-f8380c3d7fbd)

My open projects are an elixir one and a ruby on rails one that's rather large

**Comment by mauricepoirrier** [comment]
Just adding on top of previous comments.
Same problem, under Zed i had over 5 beam.smp processes consuming ~10 gb of memory. I only had 1 zed elixir project opened

**Comment by bottlenecked** [comment]
I think I managed to replicate the issue by attempting to open a large postgres data dump file with the .sql extension (a 2GB file)
Simply opening the file (even if immediately closing the tab afterwards) seems to bring the memory into the 10s of GB

**Comment by joeds13** [comment]
I’m also seeing the same, currently on 0.151.2, but been happening for a while now, resulting in having to force close Zed multiple times per day at worse

Happy to help try and provide any additional information/profiling if needed

![Screenshot 2024-09-10 at 13 02 59](https://github.com/user-attachments/assets/197cdfd5-e6c8-48cb-980a-b94a62bb8287)
![Screenshot 2024-09-10 at 13 01 47](https://github.com/user-attachments/assets/28fef600-9cce-4f94-a1fc-2d8a5e671152)

**Comment by mikayla-maki** [comment]
I'm going to close this specific issue as it's not really actively reproducible by us. But in these comments, I have a suspicion there might be a memory leak related to our LSP handling in general.
