### ISSUE TITLE
PyRight works wrong

### ISSUE THREAD

**Issue by igor-yusupov** [zed-industries/zed#13541]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It says: `range` is not defined. When I use range function from python. It also can't define `print` and `super` from standard python.

### Environment

python3.10. I installed via brew

### If applicable, add mockups / screenshots to help explain present your vision of the feature

"range" is not defined

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi, 

Could you please edit your description to include the parts of the issue template that you skipped?

Please include:
1. Your platform/environment info (cmd+shift+p, zed: copy system specs into clipboard).
2. Anything relevant lines from your zed logs.
3. How you installed python3.10 (homebrew, python.org installer, anaconda, etc).

**Comment by igor-yusupov** [comment]
@notpeter I have updated description

**Comment by igor-yusupov** [comment]
Maybe should I remove pyright downloads and reopen? How to do that?

**Comment by igor-yusupov** [comment]
Yeah, I removed pyright downloads, then reopen and now it os OK
