### ISSUE TITLE
scroll_beyond_last_line issues

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#13559]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`scroll_beyond_last_line` shipped in today's preview (0.142.x) with default settings including `"scroll_beyond_last_line": "one_page",`

1. ~I think we should match the previous default behavior with `"scroll_beyond_last_line" = "off"`~

2. There is a bug when you scroll a short file with it set to `off`.
<img width="892" alt="image" src="https://github.com/zed-industries/zed/assets/145113/ee878de2-d8b7-4f04-8cf9-ca8454813411">

See:
- https://github.com/zed-industries/zed/issues/4962
- https://github.com/zed-industries/zed/pull/11155

### Environment

Zed: v0.142.0 (Zed Nightly d044dc8485bb97290b7adb6c701e12db838aef38)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Steps to reproduce:
1. Open a file which is shorter than your vertical display.
2. Toggle `scroll_beyond_last_line` off.
3. Scroll down off the page. 

https://github.com/zed-industries/zed/assets/145113/4d2300f4-329e-4ec2-a30e-89d050decad1

**Comment by izuzak** [comment]
> I think we should match the previous default behavior with "scroll_beyond_last_line" = "off"

👋 @notpeter Was that really the previous default behavior? 🤔 I'm almost sure it wasn't since I was excited to see this new config option because I didn't really like that Zed scrolled beyond the last line. But I also noticed problems with `"scroll_beyond_last_line" = "off"` so had to remove that from my config 😢

**Comment by notpeter** [comment]
> > I think we should match the previous default behavior with "scroll_beyond_last_line" = "off"
> 👋 @notpeter Was that really the previous default behavior? 
Nope. I was mistaken.

**Comment by wzxu** [comment]
The issue I encountered was with long file, instead.
I cannot scroll past certain threshold even though there are still many lines of file below.
Turning off soft wrap seems to temporarily bring it back to normal.

**Comment by notpeter** [comment]
FYI @evan-liu and @mikayla-maki, #11155 introduced some regressions into preview.

With `"scroll_beyond_last_line": "off",` there's some bad behavior. In this video I'm scrolling with my trackpad.

> :warning: This video flashes a lot. 

https://github.com/zed-industries/zed/assets/145113/8e70133a-bf3b-49c5-8312-d9df1008312d
