### ISSUE TITLE
Zed failed to launch

### ISSUE THREAD

**Issue by davidgogginsss** [zed-industries/zed#13563]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![CleanShot 2024-06-26 at 19 43 01@2x](https://github.com/zed-industries/zed/assets/165086054/6ee24775-9a2a-44e8-99a5-d48ec28ffd9c)

Failed to launch 0.141.2

### Environment

Software:

    System Software Overview:

      System Version: macOS 14.5 (23F79)
      Kernel Version: Darwin 23.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 days, 5 hours, 27 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac15,9
      Model Number: MUW63LL/A
      Chip: Apple M3 Max
      Total Number of Cores: 16 (12 performance and 4 efficiency)
      Memory: 48 GB
      System Firmware Version: 10151.121.1
      OS Loader Version: 10151.121.1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by michaelcosj** [comment]
Try #13271

**Comment by davidgogginsss** [comment]
thanks solved!
