### ISSUE TITLE
Format on save not respected

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#13562]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After recent update in particular:
```json
    "Markdown": {
      "format_on_save": "off"
    },
```
is not respected.

Instead upon `.md` file save the file is reformatted.

The whole block from my config states:
```json
  "language_overrides": {
    "Python": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "ruff",
          "arguments": ["format", "-"]
        }
      }
    },
    "Markdown": {
      "format_on_save": "off"
    },
    "JSON": {
      "prettier": {
        "allowed": true,
        "parser": "json"
      }
    }
  },
```

### Environment

Zed: v0.142.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Should be not format on save such as:
![Screenshot 2024-06-26 at 5 46 17 PM](https://github.com/zed-industries/zed/assets/4711498/0e3830f7-200f-4afc-9956-3b4fb98de048)

instead it reformats the file such as
![Screenshot 2024-06-26 at 5 46 33 PM](https://github.com/zed-industries/zed/assets/4711498/33bf8e44-7a1e-46ce-80b9-3762b8cae13c)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Upon formatting no relevant ZED log is displayed.

**Comment by notpeter** [comment]
Can you try setting `remove_trailing_whitespace_on_save` to false?

**Comment by SomeoneToIgnore** [comment]
As stated in the Zed 0.142.0 Preview release notes, https://zed.dev/releases/preview

```
Breaking changes
SETTINGS DEPRECATION NOTICE

In your settings.json the following keys will need to be renamed:

    language_overrides -> languages
    copilot -> inline_completions
    show_copilot_suggestions -> show_inline_completions

Previously, we were supporting the old keys as an alias for the new keys, but this led to unintended/confusing failure modes. As a result we have deprecated the old keys.

See: [Settings Deprecation Notice 2024-06-17](https://github.com/zed-industries/zed/issues/13171) for more information.
```

**Comment by krstp** [comment]
Not sure what `remove_trailing_whitespace_on_save` would entail, but did not cause any change. However, your other comment on deprecated arguments did help, thanks, works!
