### ISSUE TITLE
Linux build for Arch Linux has a broken zed.desktop file

### ISSUE THREAD

**Issue by luka-hash** [zed-industries/zed#13567]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running `cat /usr/share/applications/zed.desktop` returns this:

```text
[Desktop Entry]
Version=1.0
Type=Application
Name=Zed
GenericName=Text Editor
Comment=A high-performance, multiplayer code editor.
TryExec=
StartupNotify=true
Exec= 
Icon=zed
Categories=Utility;TextEditor;Development;IDE;
Keywords=zed;
MimeType=text/plain;inode/directory;
```

Now if I understand it correctly (notice empty `TryExec` and `Exec` fields), this does nothing, making launching zed from launcher like dmenu, rofi, wofi... impossible.

### Environment

Zed: v0.141.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 7.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

There are also 2 quirks I'd like to point out here (instead of opening new issues, because I think they are kind of related to this one, at least one of them is):
1. When running zed from the terminal, if you run it without the --foreground flag, LSP is not functioning, but if you start it with the flag, LSP does work. In relation to the desktop file bug, I don't know if the flag should be used, since I don't know what is 'foreground' in that case. Also, see #13018, since the similar thing occurs - if I start zed without the --foreground flag, there is an additional black window that opens alongsise the editor window.
2. (This one is basically unrelated to this issue, but since it is very minor, I didn't want to open a full new issue for it) Running `zeditor --version` returns `Zed  – /usr/lib/zed/zed-editor` which is not really what one would expect to see.

**Comment by someone13574** [comment]
The empty exec fields were fixed here: https://gitlab.archlinux.org/archlinux/packaging/packages/zed/-/commit/2d11c569b6e521d5e38d3a570542299fea769cb4

**Comment by luka-hash** [comment]
I'm closing this one, but it would be nice if someone takes a look at the notes in the original issue.
