### ISSUE TITLE
[vim] `r` and `shift-r` undo error,`r` count error

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#13566]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Undo Error

https://github.com/zed-industries/zed/assets/19868292/364aec45-67c2-4009-932d-ec5f6f41a68c

r should not generate characters, because r is just a single character replacement, and the original length should be whatever the maximum should be.When the count exceeds the current character, you should do nothing.shift-r allows generating characters that are longer than the original characters

https://github.com/zed-industries/zed/assets/19868292/af5bbe79-81f1-4849-8f21-8ad7968760a2

_Originally posted by @0x2CA in https://github.com/zed-industries/zed/issues/13287#issuecomment-2187819226_
            

### Environment

Zed: v0.142.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
Fixed by #13623
