### ISSUE TITLE
vim: Repeated (with count) `a` And `i` Does Not Undo Correctly

### ISSUE THREAD

**Issue by nlordell** [zed-industries/zed#13573]
### Check for existing issues

- [X] Completed

> Previously submitted https://github.com/zed-industries/zed/issues/9383
> Might be related to https://github.com/zed-industries/zed/issues/13566

### Describe the bug / provide steps to reproduce it

Using `a` or `i` **with a count** from normal mode is considered as two considered two separate edits WRT undo, and undos incorrectly leave the cursor past the end of the line.

### Environment

Zed: v0.142.1 (Zed Preview)
OS: Linux Wayland fedora 40
Memory: 30.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Assuming the following buffer and cursor position:

```
buffe|r
```

`3a.<esc>`

```
buffer..|.
```

`u`

```
buffer.|
```

_Notice that there is a leftover `.` and that the cursor is after the end of the line. It is as if the repeated appended text is a separate edit._

`u`

```
buffer|
```

_Notice the cursor position being past the last character._

**Comment by ConradIrwin** [comment]
Fixed by #13623

**Comment by nlordell** [comment]
Thanks a bunch @ConradIrwin for the quick fix!
