### ISSUE TITLE
Project Search enters Vim Visual Mode

### ISSUE THREAD

**Issue by raphaelluethy** [zed-industries/zed#13579]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the project search (so text search, not file), the window that opens is entered with `visual line` mode.

1st: Open `pane: deploy search`
2nd: Enter query and press enter
3rd: Enjoy visual line selection

### Environment

Zed: v0.142.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 36 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
Thanks for reporting this! If you'd like to pair with me on a fix:  https://calendly.com/conradirwin/pairing

**Comment by joelazar** [comment]
I can see the same behavior when I do a `FindAllReferences`, so it might have to be related to the multibuffers and vim mode in general.

**Comment by ConradIrwin** [comment]
I think it's currently a race condition. When a new editor is created in vim mode we set a flag to not select matches; but I think the project search sets the range before the flag is set. Should be solvable though
