### ISSUE TITLE
[FEATURE] A toggle for folders or files first

### ISSUE THREAD

**Issue by bobbymannino** [zed-industries/zed#13578]
### Check for existing issues

- [X] Completed

### Describe the feature

In each folder you get a list of files and folders, it would be nice to have a toggle to select if files or folders appear at the top, at the moment files appear at the bottom but when you have nested folders I cannot tell which folder the files belong to. i know I could make the indentation bigger but still a worthy feature I think

**Comment by notpeter** [comment]
I believe this is duplicate of
- https://github.com/zed-industries/zed/issues/4533

Please 👍 to vote for increased visibility and subscribe to that issue to track it's progress.
