### ISSUE TITLE
Make prompt window respect user-defined font family settings

### ISSUE THREAD

**Issue by Nriver** [zed-industries/zed#13581]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi, I'm working on a translation/globalization project for Zed https://github.com/Nriver/zed-translation. During this process, I noticed that the prompt window does not adhere to the user-defined font family settings. The Chinese characters are shown as garbled characters.

![Prompt Window Issue](https://github.com/zed-industries/zed/assets/6752679/2099ce66-0512-41e7-b4b8-960eb136a5be)

After some debugging, I discovered that the font was hard-coded in the code. You can find the relevant code snippet here:

[Hard-coded Font in Linux Prompts](https://github.com/zed-industries/zed/blob/b43df6048b46088dc399b2da24e8c989688cd8ea/crates/zed/src/zed/linux_prompts.rs#L70)

I've implemented a fix to make the font settings dynamic, and here is how it looks now:

![Fixed Prompt Window](https://github.com/zed-industries/zed/assets/6752679/688b4e0e-776f-4cb1-b81c-ca38bfed68a3)

And here is a little preview of my translation work : )
![Translated Prompt Window](https://github.com/zed-industries/zed/assets/6752679/5461c3c5-23fc-492e-8d33-94307244dc93)

**Comment by ConradIrwin** [comment]
Fixed by #13596
