### ISSUE TITLE
Setting "buffer_font_weight" resets current theme and font family to the defaults

### ISSUE THREAD

**Issue by dimeeentor** [zed-industries/zed#13598]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Set custom theme, for instance "Andromeda"
2. Add new parameter "buffer_font_weight"
3. Set a custom value 

### Environment

Zed: v0.142.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

As I see it shouldn't reset theme and font family.

https://github.com/zed-industries/zed/assets/32683179/df66146a-b8f5-4c08-92c8-b884631cb4d4

**Comment by Peiffap** [comment]
You should use
```json
{
    "buffer_font_weight": 200
}
```
without the quotes around the value -- in fact, if you try to use a string for other settings that expect numerical input, like `"buffer_font_size"` for example, you'll run into the same problem.

I personally agree that it would be much more intuitive if Zed gave some kind of error message when this happens and just gracefully ignored that particular setting.

As a sidenote, there was no documentation for the `"buffer_font_weight"` setting in "Configuring Zed". I'll add that.

**Comment by JosephTLyons** [comment]
Doing what @Peiffap should get you fixed up @dimeeentor! Let us know if that works and we can close this issue out!

**Comment by Peiffap** [comment]
@JosephTLyons Out of curiosity: are you planning on handling these types of input errors gracefully at some point in the near future?

**Comment by dimeeentor** [comment]
> Doing what @Peiffap should get you fixed up @dimeeentor! Let us know if that works and we can close this issue out!

Yup, it worked. Thanks!
