### ISSUE TITLE
unable to launch Zed after installation on macbook pro with m2 pro chip

### ISSUE THREAD

**Issue by diganta-toast** [zed-industries/zed#13591]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have tried installing Zed on my system using both installer and homebrew. But when I tried to open zed it showed below error.

### Environment

I am using Macbook pro with m2 pro chip and 16gigs memory

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1025" alt="Screenshot 2024-06-27 at 8 21 31 PM" src="https://github.com/zed-industries/zed/assets/170619883/69236ef3-9809-461d-a93a-1f106b22b6ca">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Your config folder has bad permissions. Try:
```
# verify with:
ls -lad ~/.config/ ~/.config/zed ~/.cache ~/.cache/zed
# create directories if missing
sudo mkdir -p ~/.config/zed ~/.cache/zed
# change ownership to the current user
sudo chown $(whoami):staff ~/.config ~/.config/zed ~/.cache ~/.cache/zed 
# Add user: read+write+execute bits on the directories
chmod u+rwx ~/.config ~/.config/zed ~/.cache ~/.cache/zed
# verify final permissions
ls -lad ~/.config/ ~/.config/zed ~/.cache ~/.cache/zed
```
