### ISSUE TITLE
Support for `.markdown` file extension

### ISSUE THREAD

**Issue by brandondrew** [zed-industries/zed#13608]
### Check for existing issues

- [X] Completed

### Describe the feature

Although [both `.md` and `.markdown` are standard file extensions for the Markdown format](https://docs.fileformat.com/word-processing/md/), Zed seems to only support `.md`.  It would be very nice if `.markdown` were also supported.

(Another option would be to automatically learn the user's extension associations as they select a language for any unrecognized extensions, but that should probably be a separate feature request.)

**Comment by notpeter** [comment]
Thanks for reporting. This will go out with next week's Preview release and will be available in stable the week after (2024-07-10).
