### ISSUE TITLE
Rust tests don't work with fish-shell

### ISSUE THREAD

**Issue by VlaDexa** [zed-industries/zed#13613]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After trying to start a test by pressing a button next to it the terminal shows a message

![Снимок экрана_20240628_001330](https://github.com/zed-industries/zed/assets/52157081/aeb6c5dd-2242-497d-93a0-c0e557b161e2)

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 30.5 GiB
Architecture: x86_64

**Comment by osiewicz** [comment]
Hey, thanks for filling this issue. There's already a related one that touches on this:
https://github.com/zed-industries/zed/issues/10964 (also: https://github.com/zed-industries/zed/issues/10998)
Would you be ok with closing this one out as duplicate?

**Comment by VlaDexa** [comment]
Oh, sorry, didn't find them
