### ISSUE TITLE
 [vim] : Inconsistent Arrow Key Behavior in Visual Mode

### ISSUE THREAD

**Issue by cjeanm11** [zed-industries/zed#13620]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This bug report addresses an issue where the arrow keys (up, down, left, right) in visual mode were not behaving consistently with the equivalent movement keys (k, j, h, l) in Vim.

In certain scenarios, pressing 'v' followed by the up arrow key unexpectedly exits visual mode and enters normal mode, unlike the expected behavior when using 'v' followed by the standard movement keys (j, k, h, l).

One potential quick fix is to add specific keybindings for the arrow keys within the visual mode context in your `vim.json` configuration file: https://github.com/cjeanm11/zed/commit/bacdf4fe82e1efd9ef29b68dea38a65035075636
```json 
{
    "context": "Editor && vim_mode == visual",
    "bindings": {
        "left": "vim::Left",
        "down": "vim::Down",
        "up": "vim::Up",
        "right": "vim::Right"
    }
}
``` 

### Environment

Zed: v0.141.2 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@cjeanm11 Thanks for reporting this! I am unable to reproduce it - do you have a way to make this happen reliably?

In theory `"up":` should already be bound to `"vim::Up"` regardless of mode https://github.com/zed-industries/zed/blob/38b9a3bf65e559d377bc410e545d9cb600828158/assets/keymaps/vim.json#L37, so I'm surprised this fixes anything. Could it be caused by another key binding you have configured?

**Comment by cjeanm11** [comment]
Hi @ConradIrwin, no problem, thanks for your help

To clarify, the issue specifically occurs with the following configuration:
- Having my default 'Standard macOS bindings' keymap (i.e., the content of `default-macos.json`) in `keymap.json`.
- Enabling vim_mode in `settings.json`.

Clearing out `keymap.json` resolved the issue, suggesting a conflict between having all my default keybindings in that file and having vim enabled.

**Comment by ConradIrwin** [comment]
Makes sense. We expect vim key bindings to take precedence over the built in ones, which is currently done by loading them later
