### ISSUE TITLE
can't name a file with the letter `a` since it's bind to `new file` keystroke

### ISSUE THREAD

**Issue by cpreston321** [zed-industries/zed#13647]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Go to project panel create a new file name it `prepare.ts`. It will skip keystroke `a` and the output will be -> `prepre.ts`

Only work around is to copy the text then paste the rename into the file.

### Environment

Zed: v0.142.2 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/6619884/f2a685d4-85ad-4958-8896-7754ab4394da

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Are you by chance using the Atom keymap? Perhaps it was caused by this line introduced in #13326:
https://github.com/zed-industries/zed/blob/b616f9c27fb4bff75aa28def069bb190038d98ef/assets/keymaps/atom.json#L73-L73

**Comment by cpreston321** [comment]
> Are you by chance using the Atom keymap? Perhaps it was caused by this line introduced in #13326:
> 
> https://github.com/zed-industries/zed/blob/b616f9c27fb4bff75aa28def069bb190038d98ef/assets/keymaps/atom.json#L73-L73
> 
> Edit: I was able to reproduce this by switching to the Atom keymap.

That is correct! I though I was losing my mind haha :)
