### ISSUE TITLE
Add `lua` syntax coloring/formatting to ZED.

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#13652]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently there is no `lua` syntax formatting and coloring in ZEd. I would like this feature to be added.

**Comment by notpeter** [comment]
There is an extension ("Lua") that includes syntax highlighting and lua-language-server. To install it, open the command palette (cmd+shift+p) and type "zed: extensions" then search for `Lua` and click install.  If this is not working correctly, please feel free to comment with additional details. Thanks

**Comment by krstp** [comment]
Indeed. Thanks!
