### ISSUE TITLE
Prisma autocomplete with "@" symbol works incorrect

### ISSUE THREAD

**Issue by nothugofsea** [zed-industries/zed#13662]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to use autocomplete with "@" symbol (ex. @map, @relation, @db, etc.) I got extra "@" symbols

### Environment

Zed: v0.141.3 (Zed)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/91194878/5ee7609c-14ac-4ad7-85ad-99c9b7bd3c31

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by aditya-raj-panjiyara** [comment]
Hi I know its close but I am still facing this issue on My Macbook can you guys please help me with that this is really annoying
