### ISSUE TITLE
Zed (still) forces Prettier to opt out of its usual parser inference

### ISSUE THREAD

**Issue by billyjanitsch** [zed-industries/zed#13660]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I reported https://github.com/zed-industries/zed/issues/11517 and it was marked as fixed by https://github.com/zed-industries/zed/pull/11558, but that PR is now released and the original issue can still be reproduced as reported.

Zed is still always passing the `parser` option to Prettier. For example:

```
stderr: Resolved config: {"bracketSpacing":false,"printWidth":100,"semi":false,"singleQuote":true,"plugins":["prettier-plugin-tailwindcss"],"tailwindFunctions":["clsx"],"proseWrap":"always"}, will format file '[...]/package.json' with options: {"bracketSpacing":false,"printWidth":100,"semi":false,"singleQuote":true,"plugins":["prettier-plugin-tailwindcss"],"tailwindFunctions":["clsx"],"proseWrap":"always","parser":"json","filepath":"[...]/package.json"}
```

### Environment

Zed: v0.141.3 (Zed)
OS: macOS 14.5.0
Memory: 96 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by billyjanitsch** [comment]
Looking into this more, it seems that the issue was indeed fixed in https://github.com/zed-industries/zed/pull/11558, but regressed in https://github.com/zed-industries/zed/pull/12273. Zed is now back in a state where it always chooses a parser to pass to Prettier, which prevents Prettier from auto-detecting which parser to use.

**Comment by SomeoneToIgnore** [comment]
Yeah, sorry for spoiling that — due to the whole e2e nature of the feature, it's hard to keep it tested.
https://github.com/zed-industries/zed/pull/13666 has to fix the things hopefully.
