### ISSUE TITLE
Shift + Scroll in Wayland and X11 does not scroll horizontally

### ISSUE THREAD

**Issue by kwresch** [zed-industries/zed#13677]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Zed with X11 or Wayland, and pressing Shift while scrolling I would expect scrolling to be restricted to the horizontal axis (that seems to be the behavior with Zed on my mac), but instead the editor continues scrolls vertically.

I have a simple proposal for a fix on both platforms in this PR if you're accepting outside contribution:
- https://github.com/zed-industries/zed/pull/13676

Thanks!

### Environment

Zed: v0.143.0 (Zed Dev a695322f83f2ad5d8d462b732a7141755d70ebba)
OS: Linux Wayland ubuntu 24.04
Memory: 15.5 GiB
Architecture: x86_64

_and_

Zed: v0.143.0 (Zed Dev 97159bd88d6294128479cd1ee8b74de3fdad93d8)
OS: Linux X11 ubuntu 23.10
Memory: 15.4 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mrnugget** [comment]
Fixed by https://github.com/zed-industries/zed/pull/13676
