### ISSUE TITLE
Spawning a task doesn't show any output sometimes

### ISSUE THREAD

**Issue by hron** [zed-industries/zed#13683]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Spawn an oneshot task, e.g. `echo OUTPUT`
2. Re-spawn the task and check the terminal

Expected: the terminal should always show the task output
Actual: the output is shown most of the times, but sometimes the terminal is empty, only the message that the task has been executed.

I suspect there is some kind of a race condition somewhere. It happens only with "fast" tasks like `echo`, at least I haven't seen this issue yet with slow tasks like `cargo build`.

[no-output-from-task.webm](https://github.com/zed-industries/zed/assets/39293/63086978-c6cf-4921-b693-36f40d18fa6e)

### Environment

Zed: v0.143.0 (Zed Dev e650c0166dba47e4a7badbec23d6756a57e0eacb)
OS: Linux Wayland ubuntu 24.04
Memory: 62.5 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
I wasn't able to duplicate this on Mac (tried on a new Arm and older Intel) so for the moment I'll assume this could be a linux-specific race condition with stdout, but I dunno.

**Comment by hron** [comment]
> I wasn't able to duplicate this on Mac (tried on a new Arm and older Intel) so for the moment I'll assume this could be a linux-specific race condition with stdout, but I dunno.

I have created a test to reproduce the issue and possible solution to this problem. Please have a look! From what I can see it's not Linux specific issue. This is about communication between Zed and Alacritty. Long story short, there is a param named `hold` and alacritty doesn't wait for the output to be delivered to `event_proxy` if `hold` is `false`.  https://github.com/alacritty/alacritty/blob/b3f0f68184b0d6b6221a5955acfcc4e33c01b766/alacritty_terminal/src/event_loop.rs#L266-L269

**Comment by hron** [comment]
Now, after seeing the results from CI for my PR it might be Linux specific after all %) Adding an if expression to apply this change only on Linux then. Anyway, please take a look!

**Comment by hron** [comment]
Hm... It seems the test is actually failing on MacOS, even with `hold: false`. My fix could be not sufficient then or it works only for Linux. Anyway, I think I need help with MacOS part because I have only Linux and Windows at my disposal.
