### ISSUE TITLE
Left-dock is always re-openned

### ISSUE THREAD

**Issue by NicoAdrian** [zed-industries/zed#13693]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Recently (don't remember since which release), the left dock is always openned at Zed startup. If you click on close the left-dock, quit Zed and re-open it, the dock is openned again. 

### Environment

Zed: v0.141.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Most probably fixed by https://github.com/zed-industries/zed/pull/13601
