### ISSUE TITLE
Scroll horizontally on Linux

### ISSUE THREAD

**Issue by ah8ad3** [zed-industries/zed#13696]
### Check for existing issues

- [X] Completed

### Describe the feature

First i want to thank from all contributors it is a great software.
I would like to be able to scroll horizontally on my Linux system, i clone and build the project 
here is the version i'm using: Zed Dev 0.142.0
Also checked this issue as well https://github.com/zed-industries/zed/issues/13677 shift + scroll doesn't work for me either.

**Comment by SomeoneToIgnore** [comment]
Can you try https://github.com/zed-industries/zed/pull/13676 ?

**Comment by ah8ad3** [comment]
Ok let me build and test it out @SomeoneToIgnore

**Comment by ah8ad3** [comment]
@SomeoneToIgnore 
Yes that solution works, i tested out.
But i'm interested for scroll bar if that is possible.

**Comment by SomeoneToIgnore** [comment]
That would need a totally differently named issue and description then.
Luckily, we have it already, closing this as a duplicate: https://github.com/zed-industries/zed/issues/4427
