### ISSUE TITLE
Defining the "language/LANG/format_on_save" key in settings.json locks the inline completions provider to copilot.

### ISSUE THREAD

**Issue by VictorGamerLOL** [zed-industries/zed#13690]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When configuring any language in Zed to be formatted on save, the editor will no longer respect your choice for the inline completions provider and force it to copilot.

### Environment

Zed: v0.143.0 (Zed Dev 83592306c519266814cacdf8a6abfed6b283c01d)
OS: Linux Wayland arch unknown
Memory: 13.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/51715529/279358f5-a7fc-4843-b214-db84bba39a0a)
![image](https://github.com/zed-industries/zed/assets/51715529/a1b2cb57-bc6f-496d-bf17-fe4ea59b13f7)
![image](https://github.com/zed-industries/zed/assets/51715529/aeb99d28-ef16-41cb-8e09-e1421eac526b)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16046217/Zed.log)

</pre></details>

**Comment by notpeter** [comment]
I am not able to reproduce this on MacOS, but will attempt to reproduce this on Linux later today.

**Comment by VictorGamerLOL** [comment]
I retract my words, that key was expecting a string of "on" or "off"

**Comment by notpeter** [comment]
Coming soon to a Zed near you...
<img width="601" alt="Screenshot 2024-07-03 at 16 21 29" src="https://github.com/zed-industries/zed/assets/145113/1dfc7fd3-e877-43b0-8904-93114a8eb56a">

**Comment by VictorGamerLOL** [comment]
> Coming soon to a Zed near you...
> <img width="601" alt="Screenshot 2024-07-03 at 16 21 29" src="https://github.com/zed-industries/zed/assets/145113/1dfc7fd3-e877-43b0-8904-93114a8eb56a">
> 

That's exactly how I found out about it, I compiled the latest commit 😅
