### ISSUE TITLE
It is unclear how to configure vtsls's maxTsServerMemory.

### ISSUE THREAD

**Issue by adamfaulkner-at** [zed-industries/zed#13706]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have tried all of the following to configure vtsls's maxTsServerMemory:

```json
  "lsp": {
    "vtsls": {
      "config": {
        "typescript": {
          "tsserver": {
            "maxTsServerMemory": 32768,
            "nodePath": "/Users/adam.faulkner/h/node/env-18.16.0/bin/node"
          }
        }
      }
    }
  }
```

```json
  "lsp": {
    "vtsls": {
      "initialization_options": {
        "typescript": {
          "tsserver": {
            "maxTsServerMemory": 32768,
            "nodePath": "/Users/adam.faulkner/h/node/env-18.16.0/bin/node"
          }
        }
      }
    }
  }
```

```json
  "lsp": {
    "vtsls": {
          "typescript": {
          "tsserver": {
            "maxTsServerMemory": 32768,
            "nodePath": "/Users/adam.faulkner/h/node/env-18.16.0/bin/node"
          }
        }
    }
  }
```

None of these appear to have any effect on the tsserver.js process that the language server spawns.

```bash
~/D/aws-in-a-box> ps aux | grep vtsls | grep max-old-space
adam.faulkner    93799  21.5  2.5 411705456 1689312   ??  S     9:40AM   0:15.73 /Users/adam.faulkner/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node --max-old-space-size=3072 /Users/adam.faulkner/Library/Application Support/Zed/languages/vtsls/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/ty/tmvkrv6x3_d0rh5n_k7mzx_m0000gq/T/vscode-typescript503/9c71ddecd2eb049eefa3/tscancellation-24509ce1df98fb3470b5.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
```

Note that neither the nodePath nor the maxTsServerMemory appear to have taken effect.

In Helix, this configuration does have the desired effect:
```
[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]
config.typescript.tsserver.maxTsServerMemory = 32768
```

I'm not familiar enough with the language server protocol to understand if I'm doing something obviously wrong, but many of your users will need to set this setting in order to avoid the language server crashing due to out of memory errors.

### Environment

Zed: v0.141.3 (Zed)
OS: macOS 14.3.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

(Too long, let me know if you really need something from this and I'll try to pull out the non-sensitive parts)

**Comment by osiewicz** [comment]
Hey, It looks like our VTSLS integration does not respect initialization_options. I'll fix that. I'm sorry that it caused problems for you.
