### ISSUE TITLE
Project Panel: Compact Folders support

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#13703]
### Check for existing issues

- [X] Completed

### Describe the feature

If you have a nested folder where each folder contains only a single subfolder it would be nice to present this nested structure as a single depth of folders.  This is especially helpful for Java projects which are often stored in nested folders corresponding to reverse domain notation (e.g. `java.sun.com` -> `com/sun/java`)

VSCode allowing controlling this behavior with `explorer.compactFolders` which defaults to true.

See also:
- https://github.com/zed-industries/zed/issues/7001

### If applicable, add mockups / screenshots to help present your vision of the feature

Zed vs vscode
<img width="253" alt="Screenshot 2024-07-01 at 11 52 54" src="https://github.com/zed-industries/zed/assets/145113/f9fc4f64-c711-40e6-b7c5-174ef4360b61"><img width="309" alt="Screenshot 2024-07-01 at 11 55 22" src="https://github.com/zed-industries/zed/assets/145113/3f1da237-d9ca-4fdf-95a4-776801eb7fb0">

**Comment by osiewicz** [comment]
We have `project_panel.auto_fold_dirs` setting. Doesn't that do what you're after?

**Comment by notpeter** [comment]
That's it.
