### ISSUE TITLE
Command for closing focused Terminal

### ISSUE THREAD

**Issue by Nishantdd** [zed-industries/zed#13711]
### Check for existing issues

- [X] Completed

#### Example : 
``` json
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-n": "workspace::NewTerminal",
      "ctrl-w": "terminal::CloseTerminal",
    }
  }
```

**Comment by SomeoneToIgnore** [comment]
Terminal items, same as other items such as editors, have tabs and are open on the pane.
Pane has the following default bindings: https://github.com/zed-industries/zed/blob/51ee60b421ee4cdca4330a7258c4834eeb2f04d5/assets/keymaps/default-linux.json#L264-L287

The one you're interested in is the ` "ctrl-w": "pane::CloseActiveItem", `.
It could be either changed in the same `"context": "Pane",` section or a configuration specific for the terminal is worth a try:

```json
{
  "context": "Terminal",
  "bindings": {
    "something-else-mapped": "pane::CloseActiveItem"
  }
},
```
