### ISSUE TITLE
[Linux] Ctrl+F followed with keyboard combination to _Select Next Match_ `Ctrl+Alt+G` is buggy.

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#13728]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The search of `Ctrl+Alt+G` is buggy. When I try to select next instance it takes a few seconds before it jump to the next match. On contrary, when using _reverse match_ with `Shift+Ctrl+Alt+G` it works instantaneously; which is a clear indicator the bug is present. 

Needless to say, I just found out,  the `Ctrl+F` also allows be to find _next match_ by pressing `Enter` (nice!) and _reverse match_ by using `Shift+Enter`, which both work flawlessly. This means, there is mismatch in `Ctrl+Alt+G` functionality and `Enter` in terms of next match. 

### Environment

Zed: v0.141.1 (Zed Preview)
OS: Linux X11 ubuntu 24.04
Memory: 15.3 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I would like `Ctrl+Alt+G` to work instantaneously similar to `Shift+Ctrl+Alt+G`. Currently, this is not the case.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Sometimes when using the key combination `Ctrl+Alt+G` and reverse, the following error shows up, which indicates somewhere under the hood there is hard-coded mapping to MacOS keyboard layout.

<details><summary>Zed.log</summary><pre>
2024-07-01T22:34:06-05:00 [INFO] ignoring macOS specific set_edited
2024-07-01T22:34:07-05:00 [INFO] ignoring macOS specific set_edited
</pre></details>

**Comment by notpeter** [comment]
Hi, 

Looks like there is a default binds in the linux keymap for:
```
{
  "context": "Editor",
  "bindings": {
    "ctrl-alt-g b": "editor::ToggleGitBlame"
  }
}
```

Temporary work around, just paste the above into your keymap and set the value to `null`.

For context, this keybind is meant to emulate the VSCode GitLens extension keyboard binding for toggling git blame.  This is the "chorded" variant of GitLens shortcuts which prefixes half a dozen commands with a common prefix (`alt-cmd-g` on Mac, `ctrl-alt-g` on Linux/Windows).

I think our Linux keybind could use some love here.  The vscode and jetbrains defaults for find next/previous are F3/shift-F3 on Linux/Windows and `cmd-g` and `cmd-shift-g` for MacOS.

The `ignoring macOS specific set_edited` log line I believe is unrelated and effectively a TODO added in https://github.com/zed-industries/zed/pull/12514.

**Comment by tkfv** [comment]
@notpeter @krstp  I think this issue is solved. Notice that if you applied the workaround before `"ctrl-alt-g b": null,` that worked in the past, now instead it seems to cause the problem again, so it must be removed.
