### ISSUE TITLE
multi buffer_font_family

### ISSUE THREAD

**Issue by hohowt** [zed-industries/zed#13729]
### Check for existing issues

- [X] Completed

### Describe the feature

Now configuration of buffer_font_family can only set one font. Is it possible to load multi fonts?

**Comment by 0x2CA** [comment]
duplication
[Add support for font fallback #12090](#12090)
[Multiple Fonts/Fallback Fonts #5180](#5180)

**Comment by hohowt** [comment]
@0x2CA tks
