### ISSUE TITLE
(MacOS) Change windows with ⌘-`

### ISSUE THREAD

**Issue by henry-zwart** [zed-industries/zed#13725]
### Check for existing issues

- [X] Completed

### Describe the feature

Support for the ⌘-` shortcut on MacOS to alternative between windows.

I believe this is a fairly standard shortcut on MacOS, but doesn't appear to be working/implemented in Zed (it produces a tilde in the code panel). 

It's possible this is a bug in my installation, as I couldn't see any related issues. Will change this to a bug report if that is the case :^)

**Comment by SomeoneToIgnore** [comment]
This definitely works already.
What do you have for this settings item?
<img width="737" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/85238f76-ec87-427a-aa91-64d8bc4533b7">

**Comment by henry-zwart** [comment]
Ah, good to know! I have the settings item set the same as you. This shortcut works in other applications. It's only Zed I've had issues with.

![CleanShot 2024-07-02 at 11 13 34](https://github.com/zed-industries/zed/assets/37574545/03b4676d-f897-404d-9e08-8d6c83560a2e)

**Comment by henry-zwart** [comment]
Hmm. In saying that, since opening up the keyboard settings this is now working as expected! Odd.

**Comment by SomeoneToIgnore** [comment]
Do you have multiple input sources? 

For me, cmd-` does not work on a non-English ABC-like layouts for my ANSI keyboard — sort of logical, but many editors are able to conveniently parse such keystrokes as if they were made with the English ABC layout.

Either way, will close the issue as it's been sort of solved, and the translation mechanism deserves a standalone issue (if not open already) with a better description.

**Comment by henry-zwart** [comment]
No worries. I do have multiple input sources, but it seems to be working on both. Happy to close the issue, will update if the problem resurfaces. Thanks for your help :)
