### ISSUE TITLE
Support `ZED_*` variables in keybindings

### ISSUE THREAD

**Issue by baldwindavid** [zed-industries/zed#13754]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be useful to support `ZED_*` variables in keybindings.

A workflow I use all day, everyday is to open a center terminal in a pane and navigate files via the yazi file manager as discussed at https://github.com/zed-industries/zed/discussions/9067

This is all wrapped up in the following keybinding:

```json
"_": [
  "workspace::SendKeystrokes",
  ": c r p enter : new center terminal enter ya_zed space cmd-v enter"
]
```

In order to open the file explorer at the path of the current file I first need to copy the relative path to the clipboard to then paste it into the terminal later in that keybinding.

Since this is reliant upon copying/pasting the relative path to the clipboard, it displaces anything on my clipboard. So if I want to copy something, navigate/create another file in the file explorer, I lose that copied text and end up pasting the relative path. It trips me up incessantly throughout the day. I've tried various workarounds including turning off the system clipboard, but all I want is SOME WAY to get this path in the terminal without displacing my clipboard.

I thought that the recent addition of registers might provide a way, but I've not found a way to leverage them to get them into the terminal.

I've also floated the concept of supporting [spawning a task in a center terminal](https://github.com/zed-industries/zed/issues/9445) such that there is access to the `ZED_*` variables, but I'm closing as I don't think it's a favored resolution.

What I do think would both solve this issue and open up other center terminal use cases would be to support the `ZED_*` variables directly in keybindings.

Thus, my keybinding above could be simplified to...

```json
"_": [
  "workspace::SendKeystrokes",
  ": new center terminal enter ya_zed space $ZED_RELATIVE_FILE enter"
]
```

No need to mess with the clipboard at all and allows running anything in a center terminal that someone might want to run.

**Comment by dumski** [comment]
Hi, could somebody explain how to achieve running tasks in a center terminal using this feature? Or how it is planned to be used?

**Comment by susl** [comment]
Hey! I'm not sure I understand how this issue addresses the ability to spawn a center terminal in a task directly (as described in #9445. I miss this feature a lot, to be honest.

**Comment by baldwindavid** [comment]
#22004 was just merged allowing to spawn a task in a center terminal making this unnecessary for my needs.
