### ISSUE TITLE
[Linux] File manager won't show up.

### ISSUE THREAD

**Issue by NameGoesThere** [zed-industries/zed#13753]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hello! Love this IDE and recently started using Debian Linux on X11 with the DWM window manager. I can only open files directly through the command line. When I use Control+O, or any other way to open files/folders, my file manager will not show up.

### Environment

Zed: v0.142.3 (Zed Preview)
OS: Linux X11 debian 12
Memory: 31.1 GiB
Architecture: x86_64

**Comment by NameGoesThere** [comment]
I restarted my pc and it fixed itself wtf.
I :heart: linux stability issues.

**Comment by noahfraiture** [comment]
Hello I have this same issue but  reboot doesn't solve the issue. Did you do anything else ?

**Comment by Kretikus** [comment]
I have the same issue:
Installed a plain arch linux + enlightenment.
Zed.log only adds
2024-07-12T19:10:58+02:00 [INFO] new;
