### ISSUE TITLE
Go to definition not working again in .svelte files

### ISSUE THREAD

**Issue by anthonyivol** [zed-industries/zed#13769]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Go to definition not working in .svelte files

### Environment

Zed: v0.141.3 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16081147/Zed.log)

</pre></details>

**Comment by anthonyivol** [comment]
It seems that the Snippet extension was causing this, so it is related to https://github.com/zed-industries/zed/issues/13282
Uninstalling the Snippet extension fixed the issue. 
That said both features were working well together until yesterday, and I can't say which update of what broke that harmony...

**Comment by anthonyivol** [comment]
Edit : without the snippet extension go to definition now worked, but autocompletion and auto-import doesn't at all in script tag.

**Comment by secondl1ght** [comment]
Go to Definition and Hover Documentation is not working for me in .svelte files either. I do not have the Snippet ext. only the Svelte one.

**Comment by phillx** [comment]
> Edit : without the snippet extension go to definition now worked, but autocompletion and auto-import doesn't at all in script tag.

Can confirm the issue went away after uninstalling snippet extension ( Zed 0.146.5, Linux )  🥲

**Comment by lucabrini** [comment]
> Go to Definition and Hover Documentation is not working for me in .svelte files either. I do not have the Snippet ext. only the Svelte one.

+1 (Zed 0.148.1, macOS x86)

**Comment by Gioppix** [comment]
+1, not working for me either. No snippet extension

**Comment by AlbertMarashi** [comment]
Also getting this issue, using Svelte 5 and on MacOS Zed 0.149.3

**Comment by AlexandreOrlg** [comment]
I’m experiencing the same issue with Svelte 4 on MacOS Sonoma, running Zed version 0.149.3

**Comment by Kae7in** [comment]
Go to definition has completely stopped working for me in `.svelte` files in this most release of Zed 0.149.3.

**Comment by oleksify** [comment]
This is what helped me bring it back - I try adding `svelte-language-server` to `languages` section in settings and it worked. 

```json
"languages": {
    "Svelte": {
      "formatter": "language_server",
      "language_servers": ["svelte-language-server"],
      "prettier": {
        "allowed": true
      }
    },
  }
```

**Comment by code-yeongyu** [comment]
Guess the same issue as #16619?

**Comment by SomeoneToIgnore** [comment]
I have something that looks like a fix, waiting for the review/confirmation: https://github.com/zed-industries/zed/pull/16654

Meanwhile, using

```json5
"languages": {
    "Svelte": {
      // this is a new like
      "language_servers": ["svelte-language-server", "..."],
      "prettier": {
        "allowed": true,
        "plugins": ["prettier-plugin-svelte"]
      }
    },
}
```
could help as a workaround.

**Comment by AlbertMarashi** [comment]
For those just using typescript and eslint, here's a config that worked for me

```json
    "languages": {
        "Svelte": {
            "prettier": {
                "allowed": true
            },
            "format_on_save": "prettier",
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        }
    }
```
