### ISSUE TITLE
vim: `gv` doesn't work after `y` on the visual selection

### ISSUE THREAD

**Issue by ConradIrwin** [zed-industries/zed#13760]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In vim mode:

* Select a word with `viw`
* `y` to yank it
* `gv` to reselect it.

It should restore your selection, but it doesn't.

### Environment

Zed: v0.143.0 (Zed Nightly ce48555f8d7bf6071ce6c268fe073e4f1e1b7e9c)
OS: macOS 14.5.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by kuglee** [comment]
Yeah the  gv command works weirdly. Besides this issue it doesn't reselect multiple lines if multiple line were yanked.

**Comment by JosephTLyons** [comment]
This should be included in Zed [v0.146.0-pre](https://zed.dev/releases/preview/0.146.0).
