### ISSUE TITLE
cannot open project on linux 

### ISSUE THREAD

**Issue by MangoIV** [zed-industries/zed#13766]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

after opening zed, I am trying to open a project with ctrl + o or with the bottom in the top left corner. both do nothing. 

### Environment

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/40720523/6483d565-4bac-45b4-a202-4c62bab522be)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
Are you using something like sway or hyprland without an xdg-desktop-portal set up? Please use the relevant NixOS module to set up your desktop environment correctly.

**Comment by MangoIV** [comment]
The portal normally works. Is there something I can do to trouble shoot this?

**Comment by jansol** [comment]
Make sure your portal actually provides a file chooser, as not all of them do: https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces

**Comment by jansol** [comment]
As for troubleshooting the portal, zed should be logging to the terminal (if you started it from there) and to `~/.local/share/zed/logs/`. If the portal is not accessible, that should be visible in the log IIRC.

**Comment by MangoIV** [comment]
It is not visible I the logs. I’m closing this issue because I’m giving up on Zed. There’s too many things that are not really agreeable with, including but not limited to enabling telemetry by default, or downloading (thankfully dynamically linked) closed source, unaudited executables without asking me before even becoming usable. An editor that already phones home and downloads nodejs, prettier and LLM executables before letting me open a file is not really what I imagined.

**Comment by alexlnkp** [comment]
Please, re-open the issue. This same thing is happening to me right now, and I don't see a reason to open a NEW issue just to say that it should stay open until it's fixed.
Although I STRONGLY agree with You, @MangoIV , We should still attempt to help the project as much as we can. I imagine it's not that hard to simply ask for a feature to disable all of the questionable additions, such as copilot, other LLMs, etc. Even if those request are not heard - at least we'll still have a WORKING code editor.

**Comment by alexlnkp** [comment]
> Make sure your portal actually provides a file chooser, as not all of them do: [wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces](https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces)

I have no issues with my xdg-portal. It simply can not be related to that since mine actually provides the file-picker

**Comment by jansol** [comment]
> This is simply not the case, or at least not anymore. Launching the zeditor from terminal only opens the editor and then immediately quits. I assume the executable simply launches a sub-process and if it doesn't fail - the command simply stops, since Zed was able to launch.

Ah, so the arch package already had the CLI helper installed as the default binary. That one does indeed not show anything in the terminal except the output for `--help`.

**Comment by alexlnkp** [comment]
> @alexlnkp I was having the same issue and I resolved it with this:
> 
>     * install `xdg-desktop-portal` `xdg-desktop-portal-gtk` packages
> 
>     * in the `.xinitrc` add
>       
>       * `dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY`
>       * `systemctl --user start xdg-desktop-portal-gtk xdg-desktop-portal`
> 
> 
> And this is all I needed to do, but also I'm still on X11, so you will need to adapt this to Wayland.

I'm using Hyprland, and I have TWO `xdg-desktop` portals constantly open, `xdg-desktop-portal` and `xdg-desktop-portal-hyprland`
Both seem to work like a charm, I never even had any issues with file-pickers either.
On my system, I'm using `thunar` for picking files and stuff, never had any issues with it either.

It would appear that it's the Zed that has troubles with opening a file-picker assigned by `xdg-desktop-portal`, rather than the `xdg-desktop-portal` being configured wrongly.

I'm not really knowledgeable in Rust, however I do know that it supports tools like `zenity`, which can be used as a file picker. (Seen it used on a project called `ntsc-rs`) It also seems to work as intended for me personally.

Although I must say, I'm not really knowledgeable in this stuff, therefore some of my assumptions are just speculations based on my PERSONAL experience only. Please take those with a grain of salt

**Comment by jansol** [comment]
> While we're on the topic of opening projects, it would be nice to have a way of opening a project using terminal while Zed is already open (using embedded terminal); I.E. Opening Zed, opening embedded terminal, typing something like zeditor -p /path/to/project/or/file and having the folder or the file open in the same Zed's instance's window.

That is already possible:

```
$ zed --help
Usage: zed [OPTIONS] [PATHS_WITH_POSITION]...

Arguments:
  [PATHS_WITH_POSITION]...
          A sequence of space-separated paths that you want to open.

          Use `path:line:row` syntax to open a file at a specific location. Non-existing paths and directories will ignore `:line:row` suffix.

Options:
  -w, --wait
          Wait for all of the given paths to be opened/closed before exiting

  -a, --add
          Add files to the currently open workspace

  -n, --new
          Create a new workspace
```

**Comment by alexlnkp** [comment]
> I guess you meant _switching_ the currently active workspace of the parent zed window via the command line in the embedded terminal?

Yeah, something like that. If I recall correctly, VSCodium allowed for that somehow, although i honestly don't remember

**Comment by jmanhype** [comment]
lmao this suck its still an issue
