### ISSUE TITLE
Multi user mac doesen't work

### ISSUE THREAD

**Issue by mannireis** [zed-industries/zed#13771]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use a mac and when I open Zed in one of the users and then go to lock screen login as another user try to open Zed and it doesn't open

### Environment

Mac Mini 
Chip: M2 Pro 
MacOS Version: 14.5 (23F79)

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/4607
