### ISSUE TITLE
windows: Although `base_keymap` in settings is `VSCode`, other keymap are sometimes used.

### ISSUE THREAD

**Issue by Huliiiiii** [zed-industries/zed#13804]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- default value for "ctrl-shift-d" in the vsocde keymap is "editor::SelectPrevious", but sometimes "editor::DuplicateLineDown" in the sublime text keymap is used.

note: If override them in keymap.json, everything works fine.

### Environment

Zed: v0.142.0 (Zed Dev d044dc8485bb97290b7adb6c701e12db838aef38)
OS: Windows 10.0.22631
Memory: 31.9 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I believe `ctrl-shift-d` in the Editor context should only ever be `editor::DuplicateLineDown`:
https://github.com/zed-industries/zed/blob/f31c55a76f73824e4f6a9a983610a67115982223/assets/keymaps/default-linux.json#L396

And only `editor::SelectPrevious` when preceded by `ctrl-k`
https://github.com/zed-industries/zed/blob/f31c55a76f73824e4f6a9a983610a67115982223/assets/keymaps/default-linux.json#L275

Do you perhaps have something extra in your `keymap.json` (`ctrl-k ctrl-s`)?

**Comment by Huliiiiii** [comment]
> I believe `ctrl-shift-d` in the Editor context should only ever be `editor::DuplicateLineDown`:
> 
> https://github.com/zed-industries/zed/blob/f31c55a76f73824e4f6a9a983610a67115982223/assets/keymaps/default-linux.json#L396
> 
> And only `editor::SelectPrevious` when preceded by `ctrl-k`
> 
> https://github.com/zed-industries/zed/blob/f31c55a76f73824e4f6a9a983610a67115982223/assets/keymaps/default-linux.json#L275
> 
> Do you perhaps have something extra in your `keymap.json` (`ctrl-k ctrl-s`)?

This is fixed in this commit. d1300b7
