### ISSUE TITLE
Zed window mysteriously went invisible / is not present, persistently so

### ISSUE THREAD

**Issue by joshuawarner32** [zed-industries/zed#13812]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The situation / steps I remember:
* Running zed just fine. IIRC there was an update pending.
* I did a `brew upgrade` / various other brew things, and applied an update to xcode developer tools (could be unrelated?)
* I quit zed, with the intent to instead launch it in the parent directory instead (i.e. `zed ..`)

The outcome:
* Zed (the app) launches - it appears in the menu bar, running app switcher
* However, no window is visible
* Clearly there is some data model state of open documents, since if I do cmd+q, I see a prompt to save/discard unsaved changes
* Keyboard interaction also works, e.g. I can do "cmd+shift+p, type 'copy system', hit enter" - and that clearly copies something to my system clipboard)

Things I've tried:
* `rm -rf ~/.cache/zed`
* `mv ~/.local/zed ~/.local/zed.bak`
* System restart
* Manually downloading a bunch of different zed builds, going pretty far back in time

(all with no results)

I also tried downloading + building zed from source (`cargo build`), and that works fine.

Would appreciate any tips on any other state I could try wiping. Also happy to jump into a debugger if anyone would be able to give me some pointers on what some good starting points would be.

### Environment

Zed: v0.142.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16093503/Zed.log)

</pre></details>

**Comment by SomeoneToIgnore** [comment]
There's also `~/Library/Application\ Support/Zed/` and `db` folder inside might be a culprit, mentioned around in the issues.

**Comment by mrnugget** [comment]
Yeah, I'm pretty sure it's a corrupted database in the `db` folder. Since `cargo build` works and uses a different DB, I'd bet on that.

**Comment by mrnugget** [comment]
Before you wipe the DB, @joshuawarner32, can you run the following if you have sqlite3 installed:

```
$ sqlite3 ~/Library/Application\ Support/Zed/db/0-stable/db.sqlite
```

And then inside the `sqlite3` prompt:

```sql
select window_state, window_x, window_y, window_width, window_height from workspaces;
```

I guess that window_width and window_height might be 0 for some windows.

**Comment by joshuawarner32** [comment]
Aha!

```
> sqlite3 ~/Library/Application\ Support/Zed/db/0-stable/db.sqlite
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> select window_state, window_x, window_y, window_width, window_height from workspaces;
||||
Windowed|129.0|25.0|1.0|1.0
||||
||||
Windowed|0.0|25.0|1440.0|875.0
||||
||||
```

Looks like some null rows and a 1x1 window. 🤔 

Is the database safe to blow away?

**Comment by joshuawarner32** [comment]
Did a `update workspaces set window_width=500.0, window_height=500.0 where window_width < 500.0 or window_height < 500.0;` which didn't fix anything. Then did `delete from workspaces;'` which did. I suspect one of the other rows was causing issues.

On second thought, I should have preserved the full workspaces table somewhere in case there was some useful debug info you could use from that; will do that next time!

**Comment by joshuawarner32** [comment]
(anyway, thanks!)

**Comment by mrnugget** [comment]
Interesting! If the `update workspaces ...` didn't help, then apparently it must've been one of the other rows. I wonder whether we treat `null`s as `0.0` in the end.

**Comment by joshuawarner32** [comment]
Seems sensible to add a check in the code somewhere to avoid trying to create zero-size window (or even a window smaller than 100x100 or something)?

**Comment by frol** [comment]
I hit the same issue, but I did not have time to investigate it, so I did not use Zed for a month until I finally found the time to search for the solutions and found this issue.

```
$ sqlite3 ~/Library/Application\ Support/Zed/db/0-stable/db.sqlite

> update workspaces set window_width=500.0, window_height=500.0 where window_width < 500.0 or window_height < 500.0;
```

This did the trick for me. @joshuawarner32 Thank you!

Here is the output of `select window_state, window_x, window_y, window_width, window_height from workspaces;`, just for your reference:

```
||||
Maximized||||
Maximized||||
||||
Maximized||||
Maximized||||
Fixed|204.0|55.0|1512.0|944.0
Maximized||||
Maximized||||
Fixed|4.0|0.0|1508.0|944.0
Fullscreen||||
Fixed|4.0|0.0|1916.0|1055.0
Maximized||||
||||
Maximized||||
Maximized||||
Maximized||||
Fixed|524.0|233.0|1512.0|944.0
Maximized||||
Windowed|0.0|38.0|1.0|1.0
Maximized||||
||||
Maximized||||
||||
Maximized||||
Maximized||||
||||
Fixed|524.0|260.0|1512.0|944.0
||||
||||
Maximized||||
||||
Maximized||||
Maximized||||
Maximized||||
Fixed|0.0|38.0|1512.0|944.0
Fixed|0.0|38.0|1512.0|944.0
Fixed|0.0|38.0|1512.0|944.0
||||
||||
||||
||||
Windowed|0.0|38.0|1.0|1.0
```

**Comment by paveltrpn** [comment]
Encounter same problem. System - Kubuntu 23.10, Zed 0.153.6. Steps to reproduce:
1) Open clean zed installation
2) Open C++ project folder
3) Edit some file
4) Close all
5) Attempt to reopen zed fail - new window opens filled with current desktop background, have tray icon and no responce from app.

rm ~/.local/share/zed/db/0-stable/db.sqlite works for me, but, cleans workspace

**Comment by mrnugget** [comment]
> 4\. Close all

Just to be super clear: what exactly does "Close all" mean? Do you close each file one by one? Do you close the window, including all the files?

**Comment by stefanluptak** [comment]
Ran into this today on macOS Zed 0.156.1 c844f1caa5a699e52d00d33619e8b5fe8de36d06. The `update workspaces ...` sqlite3 command fixed it.

**Comment by SpaghetMeNot** [comment]
I'm encountering the same issue I think (window turns invisible when resizing) Looking at the log there is some sort of GPU Error:

```
2026-05-08T17:01:04+01:00 ERROR [gpui_wgpu::wgpu_renderer] GPU error during frame (failure 912 of 10): Validation Error

Caused by:
  In Texture::create_view
    Texture with 'atlas' label is invalid
```

[Zed.log](https://github.com/user-attachments/files/27530390/Zed.log)
