### ISSUE TITLE
Can't type character "a" when creating file

### ISSUE THREAD

**Issue by Marcisbee** [zed-industries/zed#13820]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open left dock (file tree)
2. right click on it and select "New File"
3. type "asd" and only "sd" appears

### Environment

Zed: v0.142.5 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
Could ti be related to https://github.com/zed-industries/zed/issues/13647?

**Comment by Marcisbee** [comment]
@osiewicz yes seems to be related, just tested and this is not an issue in Preview built.

This is quite the breaking thing, would be nice to release this fix to stable.

**Comment by notpeter** [comment]
This was fixed in Zed Preview (v0.143.x) earlier in the week.
I just pushed v0.142.6 (stable) with this change as well.
