### ISSUE TITLE
Theme alternates between light and dark when changing buffer_line_height / custom

### ISSUE THREAD

**Issue by Grabber** [zed-industries/zed#13837]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was trying to change the line height.

If you set "On Light" as the theme with buffer_line_height.custom set to any value and save it's OK.

```
{
  "theme": "One Light",
  "ui_font_family": "IBM Plex Monos",
  "buffer_font_family": "IBM Plex Mono",
  "buffer_font_size": 14,
  "buffer_line_height": {
    "custom": 1.2
  },
  ...
}
```

![Screenshot 2024-07-04 at 16 25 23](https://github.com/zed-industries/zed/assets/15731/89ef7617-236d-45ed-b72b-8dc0c4213042)

BUT if you remove the "custom" key/value and save... somehow the "One Dark" theme is applied right before the save.

```
{
  "theme": "One Light",
  "ui_font_family": "IBM Plex Monos",
  "buffer_font_family": "IBM Plex Mono",
  "buffer_font_size": 14,
  "buffer_line_height": {
  },
  ...
}
```

![Screenshot 2024-07-04 at 16 25 12](https://github.com/zed-industries/zed/assets/15731/0bf4b2da-62ce-466c-863e-299062683bd5)

### Environment

MacBook Pro: 15-inch, 2019
OS: 14.5 (23F79)

**Comment by maxdeviant** [comment]
It looks like what's happening here is that when you remove the `custom` line the `buffer_line_height` setting can no longer be parsed, thus making the settings file invalid and reverting to default settings (which uses "One Dark" as the theme).

**Comment by JosephTLyons** [comment]
I think @maxdeviant is correct that what is happening is that Zed is unable to parse the file and then things revert to the default. I think we can close this issue in favor of:

- https://github.com/zed-industries/zed/issues/12389
