### ISSUE TITLE
Chat with GitHub Copilot.

### ISSUE THREAD

**Issue by uprizingFaze** [zed-industries/zed#13843]
### Check for existing issues

- [X] Completed

### Describe the feature

I have GitHub Copilot's autocomplete, but I don't know if it's possible to have the chat, like the one that already exists, where you enter the OpenAI API key, but with Copilot since I have free Copilot for being a student while the OpenAI API Key has a cost.

**Comment by atridadl** [comment]
This had been extensively discussed here: #4673 

Please search before creating an issue.
