### ISSUE TITLE
Autocompletions show no import paths, as they did before

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/zed#13849]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="552" alt="image" src="https://github.com/zed-industries/zed/assets/15632814/64f6469a-4057-4dba-8b83-49ea018f88bb">

As shown here for Rust, the only import path shown is for the local crate in the workspace.

### Environment

Zed: v0.142.5 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

There are numerous issues that mention this but after a quick glance to me it looks like most are dismissed as "missing features" and closed in favor of other issues, but **that is wrong**. The import paths were displayed before, and they're not anymore, **this is a regression**.

- https://github.com/zed-industries/zed/issues/10204
- https://github.com/zed-industries/zed/issues/4457
- https://github.com/zed-industries/zed/issues/10075
- https://github.com/zed-industries/zed/issues/7099
- https://github.com/zed-industries/zed/issues/4457

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
Hey, thanks for the report. This has already been fixed in https://github.com/zed-industries/zed/pull/13797 and should be out on Stable in 2 weeks IIRC.

**Comment by stjepangolemac** [comment]
Awesome thank you @osiewicz!

**Comment by stjepangolemac** [comment]
@osiewicz when is this hitting preview? It still doesn't work for me.

**Comment by osiewicz** [comment]
It should already be on Preview. Can you share a minimal reproduction case where you'd expect to see import path in completions, but it's not there?

**Comment by stjepangolemac** [comment]
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/31362d77-27c1-483a-b6c5-35a8fcb30bf9">

This is latest preview version. I don't know how this works but looks like functions don't show import paths while structs do?

**Comment by osiewicz** [comment]
I landed another round of improvements in https://github.com/zed-industries/zed/pull/14490

**Comment by stjepangolemac** [comment]
I'm running 144.3 now and still can't see import paths. Maybe it's still not on preview?

<img width="317" alt="image" src="https://github.com/user-attachments/assets/3fe1de8d-9b1d-4d21-b987-138b197787db">

**Comment by osiewicz** [comment]
@stjepangolemac new Preview builds are released on Wednesday so yeah, it'll be on Preview today (in 8 hours or so)

**Comment by stjepangolemac** [comment]
Just checked and it works now. Thank you!
