### ISSUE TITLE
Window is only "half the size" on UW screen on ChromeOS

### ISSUE THREAD

**Issue by UlrichAlt** [zed-industries/zed#13847]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When compiling and launching the latest Zed in the Linux environment of a Chromebook (Chromebox), the window is not properly sized. I am using an UW screen. It looks like the window is half the size of what it is supposed to be. See screencast

https://screencast.apps.chrome/1-a-LUKm81vzcwVKxmN--aCHglIp85vkc?createdTime=2024-07-05T06%3A37%3A30.678Z

### Environment

Can not run the command.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by UlrichAlt** [comment]
Reducing  the screen resolution on the otherwise same machine works around this problem, however I would like to use it on such a big screen. The resolution of the initial screen is 3840x1600.

**Comment by UlrichAlt** [comment]
Hi checking again on this ... if we start Zed with a lower resolution (1920x1080) everything is fine. While keeping Zed running, we can increase the resolution and it still works fine. It is just a problem starting Zed with a higher resolution.

When running Zed, I see CPU is in quite heavy use, probably due to non existing/emulated GPU in this environment. See attached files.

[vulkaninfo.txt](https://github.com/user-attachments/files/16159317/vulkaninfo.txt)

[lshw_display.txt](https://github.com/user-attachments/files/16159312/lshw_display.txt)

**Comment by UlrichAlt** [comment]
Checking further again: see https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/vm_tools/sommelier/README.md

For example, HiDPI aware programs can run at native display resolution, while some older programs can use half of that resolution.

Launching Zed with a specific dpi setting solves the issue which can be configured. However would be interesting to know where Zed apparently got a "wrong" DPI value from.

**Comment by UlrichAlt** [comment]
Checking once more ... there is no .Xresources file in the user home directory. However xrdb - query returns a proper Xft.dpi setting ...
Running xrdb -query > ~/.Xresources populates this file (only one line) and Zed runs without a problem.
So, maybe Zed should just look for DPIs in other places than just the local user's HOME?

**Comment by staticfrost** [comment]
I have the same issue on Pixelbook, what setting should I set to get it working? @UlrichAlt any tips would be great.

**Comment by ajorg** [comment]
The suggested workaround doesn't do anything for me on my Samsung Galaxy Chromebook, running chromeOS 126. It doesn't look to me like it's using X anyway, but Wayland. When I try to run it under `sommelier -X` to run it under X, it crashes.

**Comment by UlrichAlt** [comment]
Populating this file does not mean running Zed under XWindows. It is just a way for Zed to determine the DPI of the display whether it runs in Wayland or X. It is also running on Wayland in my machine. You can try running xrdb -query and look what it says regarding the dpi. Note also that I am running the preview build, I think there has been some movement in that area and that could also make a difference.

**Comment by UlrichAlt** [comment]
Tested with latest dev channel. Problem does not exist anymore, even without the .Xresources file. High CPU usage is also gone. I am impressed.

**Comment by ajorg** [comment]
I'm still seeing something like this on my 4K Samsung Galaxy Chromebook, with the latest preview build. Should I open a new bug for it?
![image](https://github.com/user-attachments/assets/84ad735a-3cd1-4c0c-96d2-9ed09d0da681)

**Comment by UlrichAlt** [comment]
Not preview build, dev build ... building Zed from source from the latest master branch from the repository. The problem is gone there. Preview build is kind of one week behind that, so you may also just wait a bit for the change to land in preview.

**Comment by MovByte** [comment]
This issue still exists

**Comment by UlrichAlt** [comment]
Here is the shell script that I use to setup my Linux dev environment on any Chromebox. I have stripped out things unrelated to Zed. Start Zed with "WAYLAND_DISPLAY='' zed"
[setup-chrome-box.txt](https://github.com/user-attachments/files/16710707/setup-chrome-box.txt)

**Comment by johnozbay** [comment]
Hello all 👋🏻

I cannot thank you enough for all the helpful information posted on this thread.

Thanks to [this Zed update](https://github.com/zed-industries/zed/pull/46758) I managed to get Zed to work even on my ARM Chromebook, and wrote a little tutorial / guide blog post about it to save everyone some time : 

https://blog.johnozbay.com/running-zed-editor-on-arm-chromebooks-mali-g925-crostini-2.html

Let me know if you run into any issues, and I'd be happy to update the blog post as well.

Hoping this helps!
