### ISSUE TITLE
Vim Mode not working at all

### ISSUE THREAD

**Issue by DoppleDankster** [zed-industries/zed#13873]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Vim motions suddenly stopped working all together.

i've used the command palette to enable/disable vim mode -> no effect
i've opened the settings.json and set vim mode to false / true -> no effect

NB: I've noticed that when i toggle vim mode from the cmd palette i see extremely briefly the "sync" icon ( the 2 arrows going in circle) at the bottom left for the screen where i should see "normal mode". This behavior is only observed when using the cmd palette

i've updated Zed, restarted it, even rebooted my mac -> no effect.

I'm concidering doing a fresh install of zed but it feels really weird that the settings.json is completely ignored.

---

Coincidentaly i've changed a few options in the settings.json to see if it was effective. i'm gonna document what i have observed and felt weird here, maybe this is related:

1 - context: Current theme was Zedokai

2 - action:  i open the menu bar and update the theme, selected another theme
observation: theme changed instantly and the value in the settings.json was updated instantly

3 - action: in the settings.json i reset the value to Zedokai and save the file by once again using the menu at the top
observation: theme does not change but the value in the config file stays "Zedokai" which is inconsistent. 

4 - action: i reboot zed
observation: Zedokai theme is not correctly in place as per the settings.json

### Environment

Zed: v0.142.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Is it possible your `settings.json` is invalid JSON and this is caused by #12389.

Perhaps start with an empty settings file `{}` and see if you can reproduce the issue.
There are some enhancements in [Zed Preview](https://zed.dev/releases/preview) that will be in Zed stable next week that will better highlight `settings.json` issues:

<img width="324" alt="Screenshot 2024-07-05 at 12 56 41" src="https://github.com/zed-industries/zed/assets/145113/5dfee572-2386-4bf5-ac12-e36ee01cc628">

**Comment by DoppleDankster** [comment]
@notpeter  case closed ! it's surprising that while it can't parse it's settings.json it also cannot show errors in the file itself...
