### ISSUE TITLE
Internal Prettier stopped working (PHP)

### ISSUE THREAD

**Issue by pjv** [zed-industries/zed#13878]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Sometime in the last few Zed Preview updates, the internal prettier instance stopped formatting php code for me. The code is still getting formatted - I assume by the intelephense LSP - but it suddenly stopped following the prettier config I have set up in my zed settings and that led me down a rabbit hole which led me to conclude that prettier itself is failing.

Here's the prettier config that I mentioned from my zed settings.json:

````
  "prettier": {
    "overrides": [
      {
        "files": [
          "*.php",
          "*.phtml"
        ],
        "options": {
          "phpVersion": "8.0",
          "braceStyle": "1tbs",
          "tabWidth": 2
        }
      }
    ]
  },
````

Up until recently, that config has been working fine. Yesterday, I tweaked some code, saved, and suddenly the whole file had a bunch of changes where opening braces were moved to the next line ("1tbs" keeps them on the same line).

I created a simple test project with a simple .php file and requested a format and I got a formatting failed message in the zed footer and when I clicked to see the logs, here's what it says:

````
2024-07-05T12:29:26-05:00 [ERROR] default prettier instance failed to format buffer

Caused by:
    0: prettier format request
    1: error during message '{"jsonrpc":"2.0","id":3,"method":"prettier/format","params":{"text":"..snip..","options":{"plugins":[],"parser":null,"filepath":"/Users/pjv/development/projects/test/test.php","prettierOptions":{"useTabs":false,"tabWidth":2,"printWidth":80}}}}' handling: UndefinedParserError: No parser could be inferred for file "/Users/pjv/development/projects/test/test.php".
````

Could this be related to #13666 and/or #13660 ?

### Environment

Zed: v0.143.2 (Zed Preview)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
This is due to both issue and the PR that "fixed" it.

Apparently, some files like package.json benefit from their parser being inferred (as the issue describes), and some cannot be inferred at all, even though there is supposed to be a plugin installed for it?

I wonder, if that's related to the plugin-supported files only, but even there I am clueless on the generic behavior we should be doing: *.ts file could be both a pure TypeScript file or a Tailwind-infused one that needs a plugin to work with.

For now though, could you try adding
```json
"PHP": {
    "prettier": {
        "allowed": true,
        "plugins": ["@prettier/plugin-php"],
        "parser": "php"
    }
},
```
to the `"languages":` section in the settings.json?

**Comment by pjv** [comment]
Adding that makes the error go away and makes something happen but it's not the something I'm hoping for.

Using this simple test file:
<img width="299" alt="SCR-20240705-lwjs" src="https://github.com/zed-industries/zed/assets/327716/22e6f3a1-5be1-456e-960c-d97309c7f486">

…which has a couple spaces before the opening php tag, when I request editor:format from zed the result looks like this:
<img width="264" alt="SCR-20240705-lxhe" src="https://github.com/zed-industries/zed/assets/327716/dea703e1-6116-48af-a99c-22001bdfd164">

(the opening php tag disappears and the initial spaces remain - kind of the exact opposite of what should happen in this case).

Nothing gets logged at all.

**Comment by SomeoneToIgnore** [comment]
Good, I see that this recovered prettier formatting for PHP.
For now, I would add a PR with that line proposed into the default settings.

Then, it seems that Prettier is replying blanks to Zed?

![image](https://github.com/zed-industries/zed/assets/2690773/a05dc6fe-b2b2-4be3-97b6-64f05c449da8)

Interestingly, when I copy that file into a separate directory and do
```
npm i --dev --save prettier @prettier/plugin-php
node ./node_modules/prettier/bin/prettier.cjs --plugin ./node_modules/@prettier/plugin-php/standalone.js test.php
```
I get back
```
  %
```

which is also a total nonsense, but a different one which I cannot explain.

But when I try https://github.com/harundogdu/PHPExamples/blob/main/Crud-Operations/class.php as the `test.php` contents and compare both prettiers' output, the difference seems to be in the white spaces?
That seems as the behavior I'd expect.

Do you have an examples what other editor configurations, relying on prettier, do with both kinds of php input?

**Comment by pjv** [comment]
That might have just been an edge case in my super-simple test file. When I put some more code in the editor, it seems to be formatting it ok. And it now seems to be prettier that is formatting the code and not intelephense which is a step forward.

Unfortunately it is still ignoring my prettier "overrides" and using the default formatting options instead of the ones I'm specifying in my zed settings.

**Comment by SomeoneToIgnore** [comment]
A 3rd different issue, all under the same description, huh?
I'd rather close this via https://github.com/zed-industries/zed/pull/13883 and also in favor of https://github.com/zed-industries/zed/issues/12049 for this so hopefully somebody can fix it one day.

**Comment by pjv** [comment]
LOL, yeah, sorry but that was the issue that led me to realize that the internal prettier had stopped working for PHP as I mentioned. 

Do you think it's completely unconnected? I think that maybe #12049 does not apply because in fact, up until when it stopped being able to infer its parser due to the PR you mentioned above for #13666, the prettier overrides I have specified in my settings.json were working perfectly.

**Comment by SomeoneToIgnore** [comment]
Not sure, as there's been quite a leap between the PRs and something else might have changed (including Prettier side).
Given that there's a certain commit that you're certain it works on, one could do `git bisect` and find the exact commit that broke it.

**Comment by pjv** [comment]
In case someone else wanders in here with the same issue, from looking at the LSP logs with the above fixed config, I discovered how to configure the php-plugin in this context. Instead of using the prettier "overrides" I posted in the OP above, you can just put whatever php-plugin options you want directly into the PHP.prettier config like this:

````
    "PHP": {
      "prettier": {
        "allowed": true,
        "plugins": [
          "@prettier/plugin-php"
        ],
        "parser": "php",
        "phpVersion": "8.0",
        "braceStyle": "1tbs",
        "tabWidth": 2
      },
    }
````

**Comment by pjv** [comment]
@SomeoneToIgnore Thanks for your instant help.
