### ISSUE TITLE
Add option to disable scroll on click

### ISSUE THREAD

**Issue by someone13574** [zed-industries/zed#13895]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently if you click near the top/bottom of a buffer, it will scroll slightly (around 5 lines). This is pretty annoying because I tend to double click to select and if I try that near the top/bottom it will not work because the clicks are interpreted as scrolls. Being able to disable this behavior should be an option.

**Comment by apricotbucket28** [comment]
I believe you need to set the following in your settings.json:
```json
  "vertical_scroll_margin": 0,
```
~~(I really don't like this setting)~~
