### ISSUE TITLE
lsp: server arguments

### ISSUE THREAD

**Issue by p00f** [zed-industries/zed#13890]
### Check for existing issues

- [X] Completed

### Describe the feature

Allow passing arguments to servers: at work we use a custom toolchain, so to make clangd work correctly I need to add a `--query-driver=**` argument. For now I've added it to the source code (all the `arguments` fields like https://github.com/zed-industries/zed/blob/813cc3f5e537372fc86720b5e71b6e1c815440ab/crates/languages/src/c.rs#L61)

**Comment by jansol** [comment]
You can pass command line arguments to the language server already:

```json
  "lsp": {
    "clangd": {
      "binary":{
        "path": "/etc/profiles/per-user/user/bin/clangd",
        "arguments": ["--background-index", "--compile-commands-dir=build"]
      }
    },
  }
```

I did not find a mention of this on a quick skim through the docs page though...

**Comment by p00f** [comment]
Ah nice, thanks!
