### ISSUE TITLE
Vim motion <c><t> does not recognise non-latin characters

### ISSUE THREAD

**Issue by matejcerny** [zed-industries/zed#13909]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Example:
```
<label for="guests">Počet hostů</label>
```
After changing or deleting the inside of the element via `ct<` (`dt<`), cursor stops on the czech letter `ů`

Expected behaviour: letter `ů` is also changed / deleted.

Tried a french letter ç and it also does not work.

Observation: it works for a selection, i.e. `vt<`

### Environment

Zed: v0.142.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

`ct<` does not work
<img width="357" alt="image" src="https://github.com/zed-industries/zed/assets/35267431/ee9fc1ba-346b-453f-9b4b-ef8c063c5204">
<img width="267" alt="image" src="https://github.com/zed-industries/zed/assets/35267431/0ae48b16-41fc-490a-a660-3f0e6562eb0f">

`vt<` works:
<img width="366" alt="image" src="https://github.com/zed-industries/zed/assets/35267431/9ec64e54-3c1e-4265-b14a-46a9183fca02">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
This is now in today's [preview release](https://zed.dev/releases/preview/0.145.0).
