### ISSUE TITLE
[Linux] `TAB` circulation across different selection buttons (`Cancel/OK/Save`, etc.)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#13906]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently it does not seem the `TAB` circulation work in linux. Good example is to for example try to `quit` ZED or save current buffer, where pop-up window will show up asking user to `Cancel/Quit` or `Cancel/Don't Save/Save`. Without using mouse/touchpad user currently is unable to select desired selection with `TAB`.

### If applicable, add mockups / screenshots to help present your vision of the feature

Allow `TAB` selection of pop-up window prompts.

**Comment by hron** [comment]
> Besides Tab a key to quickly select/trigger Don't Save would also be nice. @hron

I think this should be achieved in a more general way by having dynamic keyboard shortcuts for each option, e.g. yes/no can be triggered by `y` and `n`, but it would be a more complex change. Maybe next time %)
