### ISSUE TITLE
Option+mouse-click to open file in "next" Workspace Pane.

### ISSUE THREAD

**Issue by aryeh** [zed-industries/zed#13917]
### Check for existing issues

- [X] Completed

### Describe the feature

When holding Option/Alt and clicking a filename in the File-finder pane, rather than the file being opened in the current Workspace pane. it gets opened in the next Workspace pane from the current pane.

If the current Workspace has 4 panes, with the Workspace-2 pane active, if a file in the finder is option-clicked it will be opened as a tab in Workspace-3.  

If the active pane is the last Workspace pane, then the file gets opened in a new last Workspace pane.

So option-click opens in the "next" (or new) Workspace pane.

It would be great if this file-open feature was named so it can be mapped in vim as well.

Thanks!

**Comment by notpeter** [comment]
Your issue was opened first, but I'm going to close this in favor of a similar issue which includes option clicking and option dragging:

- https://github.com/zed-industries/zed/issues/14861

Please upvote 👍 and subscribe to that issue to track progress. Thanks for reporting!
