### ISSUE TITLE
the cursor does not move with Page Down/Up commands

### ISSUE THREAD

**Issue by tkfv** [zed-industries/zed#13925]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you press Page Up, Page Down the cursor does not change position. 

For example you press Page Down, and then Line Down, you go to the line below the one you were before pressing Page down.

This does not seem to be in line with what other editors do nor other commands like Move to Beginning, which also moves the cursor to the beginning of the file.

### Environment

Zed: v0.142.6 (Zed)
OS: Linux Wayland arch unknown
Memory: 30.1 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
Hi @tkfv,

This was fixed in Zed v0.143 which is the next stable release (out on Wednesday).
Alternatively it is available now Zed Preview or development versions.

- https://github.com/zed-industries/zed/pull/13510
