### ISSUE TITLE
Restart option in menu

### ISSUE THREAD

**Issue by Moosems** [zed-industries/zed#13921]
### Check for existing issues

- [X] Completed

### Describe the feature

Allow the user to restart the app from the Command+Shift+P menu. Looked for issues under "https://github.com/zed-industries/zed/issues?page=1&q=restart+option"

**Comment by SomeoneToIgnore** [comment]
There's a `workspace::Reload` action which should do this.

![image](https://github.com/zed-industries/zed/assets/2690773/865c1d8c-14e3-4caa-acd8-6ff62e6072d9)
