### ISSUE TITLE
SF Mono renders bold

### ISSUE THREAD

**Issue by lutzroeder** [zed-industries/zed#13934]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Setting `buffer_font_family` to `SF Mono` the font renders **bold**.

![Image](https://github.com/user-attachments/assets/51ad1bdb-a6cf-444c-b780-460adcac0d5d)

### Environment

macOS 14.5 (23F79)
Zed 0.142.6

**Comment by MrZLeo** [comment]
Looks like cannot reproduce the problem with setting:

<img width="349" alt="image" src="https://github.com/user-attachments/assets/8e763ac2-ca0e-4ed2-b1e6-1d413460bb55">

in

macOS 14.5
zed 0.143.6

**Comment by lutzroeder** [comment]
**Font Book** > **Settings** > **Advanced** > **Reset Fonts** resolved the issue.
