### ISSUE TITLE
Cannot use AZERTY keys in bindings

### ISSUE THREAD

**Issue by ewen-lbh** [zed-industries/zed#13956]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I set a keybinding on context `Editor && vim_mode != insert` that maps `ù` to `workspace::OpenTerminal` (the default keybinding requires AZERTY layout users to press three keys, one on the left on the keyboard, one on top and one on the right, it's just not feasible for me to use the default keybinding '^^).

This seems related to https://github.com/zed-industries/zed/issues/4624, although it may be different

My entire `keymap.json`:

```json
[
  {
    "context": "Editor && vim_mode == insert",
    "bindings": {
      "j k": ["workspace::SendKeystrokes", "escape"],
      "k j": ["workspace::SendKeystrokes", "escape"]
    }
  },
  {
    "context": "Editor && vim_mode != insert",
    "bindings": {
      "ù": "workspace::OpenTerminal"
    }
  }
]
```

As well as my config:

```json
{
  "theme": "One Dark Pro",
  "vim_mode": true,
  "ui_font_size": 14,
  "buffer_font_size": 13,
  "autosave": {
    "after_delay": {
      "milliseconds": 300
    }
  },
  "terminal": {
    "font_size": 14
  }
}
```

### Environment

Zed: v0.142.6 (Zed)
OS: Linux Wayland endeavouros unknown
Memory: 15.6 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

(not applicable, there was nothing generated in Zed.log)

**Comment by ewen-lbh** [comment]
After looking through the logs, it turns out that i was using the wrong action to toggle focus on the terminal panel

**Comment by ConradIrwin** [comment]
Though funnily enough, this *was* a real bug under X11 that's now fixed :D.
