### ISSUE TITLE
problem displaying code suggestions

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#13968]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/20476002/3372067f-7c82-4c13-80eb-40331cf1a40d

### Environment

```
Zed: v0.143.3 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by trivikr** [comment]
This issue seems to have been fixed?

https://github.com/user-attachments/assets/144325ae-b759-4860-b083-fc4253e44df7
