### ISSUE TITLE
Every Time The first Project Search results are always empty

### ISSUE THREAD

**Issue by SealinGp** [zed-industries/zed#13965]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. start project search
2. enter seach keywords
3. alsways empty every initial search
4. click "toggle match case" and results come out

### Environment

M1  Macos Sonoma 14.6 Beta
Zed 0.142.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="975" alt="image" src="https://github.com/zed-industries/zed/assets/32982627/7a84d549-59b0-4c5d-b8b6-a97f9a101f5b">

<img width="1484" alt="image" src="https://github.com/zed-industries/zed/assets/32982627/f76422b5-65ce-42a8-9b2c-2d9ee70b8c08">

![录屏2024-07-09 11 40 25](https://github.com/zed-industries/zed/assets/32982627/4c50accf-557f-41fb-bd47-44c37c94397f)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I can't tell from your screen recording are you pressing enter after you paste your search terms? We don't update the search results until you press enter.

**Comment by SealinGp** [comment]
> I can't tell from your screen recording are you pressing enter after you paste your search terms? We don't update the search results until you press enter.

got it, thanks.
