### ISSUE TITLE
Rust: Inline doc hints

### ISSUE THREAD

**Issue by ActuallyHappening** [zed-industries/zed#13980]
### Check for existing issues

- [X] Completed

### Describe the feature

Types that are named in Zed using rust-analyser aren't highlighted and can't be control+clicked, at least not in my current setup

### If applicable, add mockups / screenshots to help present your vision of the feature

From zed:
![image](https://github.com/zed-industries/zed/assets/105958073/4e586718-235a-45e4-bd44-303fff480b6f)

From VSCode (after waiting an eternity compared to zed):
![image](https://github.com/zed-industries/zed/assets/105958073/079e1e71-ed97-49d0-9437-0545572eeaf4)

From VS-Code after holding Cmd:
![image](https://github.com/zed-industries/zed/assets/105958073/5df38718-114d-493e-893e-52e64de29bfc)

**Comment by osiewicz** [comment]
Hey, what version of Zed are you using? It works for me on Nightly.

**Comment by notpeter** [comment]
I can't reproduce this either.
