### ISSUE TITLE
Building on linux pulls in .. Rust's apple toolchain

### ISSUE THREAD

**Issue by darklajid** [zed-industries/zed#14000]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
```
❯ ./script/install-linux
+ [[ 0 -gt 0 ]]
+ export ZED_CHANNEL=dev
+ ZED_CHANNEL=dev
++ pwd
+ export 'ZED_UPDATE_EXPLANATION=You need to fetch and rebuild zed in /home/bam/Dev/scratch/zed'
+ ZED_UPDATE_EXPLANATION='You need to fetch and rebuild zed in /home/bam/Dev/scratch/zed'
+ script/bundle-linux
+ getopts h flag
+ export ZED_BUNDLE=true
+ ZED_BUNDLE=true
+ channel=dev
+ target_dir=target
++ script/get-crate-version zed
info: syncing channel updates for '1.79-x86_64-unknown-linux-gnu'
info: latest update on 2024-06-13, rust version 1.79.0 (129f3b996 2024-06-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
**info: downloading component 'rust-std' for 'aarch64-apple-darwin'**
info: downloading component 'rust-std' for 'wasm32-wasi'
**info: downloading component 'rust-std' for 'x86_64-apple-darwin'**
```
### Environment

It's a System76 Pop!_OS system. There's no "system specs" I'd know to copy

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
This is currently a limitation of rust-toolchain.toml with cargo.

To my knowledge there is no way to use rust-toolchain.toml to specify host-specific targets so that mac includes `"x86_64-apple-darwin", "aarch64-apple-darwin", "wasm32-wasip1"` and windows uses `"x86_64-pc-windows-msvc", "wasm32-wasip1"`.
