### ISSUE TITLE
Status column row display as ln and col

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#14011]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to be able to choose whether to use one way or another.

Zed:

<img width="56" alt="Screenshot 2024-07-09 alle 19 57 59" src="https://github.com/zed-industries/zed/assets/20476002/efa81c30-3e1f-4932-bf4a-9eeeddab3d46">

Vscode:

<img width="92" alt="Screenshot 2024-07-09 alle 19 58 07" src="https://github.com/zed-industries/zed/assets/20476002/bb1a449e-f79f-4d09-9e1c-d1a4b665bdfa">

**Comment by notpeter** [comment]
We are opting to not implement the suggested design change at this time.
Thanks for reporting.
