### ISSUE TITLE
Add Key Bindings for Upper-Case and Lower-Case Text Transformations

### ISSUE THREAD

**Issue by benbenbang** [zed-industries/zed#14019]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello team,

I checked [ this doc](https://zed.dev/docs/key-bindings) for the built-in key binding. I'd like to share an idea (feature request, if possible) that I also use quite often,

The `cmd + k` is a modified key as it's already implemented.
- with a hint in the status bar below
![CleanShot 2024-07-06 at 22 53 17@2x](https://github.com/zed-industries/zed/assets/6682936/2042a545-22e4-4d2d-8a28-f30987453a37)
- bind with `cmd + u`  => change the selected text to be upper-case
- bind with `cmd + l` => change the selected text to be lower-case

Similar to the `selection` => `operation` concept mentioned here https://github.com/zed-industries/zed/discussions/6447

WDYT?

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/6682936/521ea01f-0f6f-419c-a2b3-0ccad89e4f9a

**Comment by notpeter** [comment]
Looks like we don't include it in the main vscode-esque [default-macos.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-macos.json) or [default-linux.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-linux.json)

But it's already there for Sublime (Mac), Atom (Mac and Linux) and Vim default keybinds:

https://github.com/zed-industries/zed/blob/9e2950a2df2d7643df1753ccef97983d7f2fb6d3/assets/keymaps/macos/sublime_text.json#L28-L29

https://github.com/zed-industries/zed/blob/9e2950a2df2d7643df1753ccef97983d7f2fb6d3/assets/keymaps/macos/atom.json#L23-L24

https://github.com/zed-industries/zed/blob/9e2950a2df2d7643df1753ccef97983d7f2fb6d3/assets/keymaps/vim.json#L380-L381

It's missing from Sublime Linux (`ctrl-k ctrl-u` / `ctrl-k ctrl-l`) [sublime source](https://gist.github.com/notpeter/0c263c8fd6e50a67aa2e4f36e4743d63#file-default-linux-sublime-keymap-json-L814-L815)

In the meantime, you can add it to your user keymap.json:
```
[
{
    "context": "Editor",
    "bindings": {
      "cmd-k cmd-u": "editor::ConvertToUpperCase",
      "cmd-k cmd-l": "editor::ConvertToLowerCase"
    }
}
]
```

**Comment by benbenbang** [comment]
@notpeter cool! Good to know. Since I am a Mac + Sublime Text user, so I didn't check the rest. I will use the keys mapping for now

**Comment by notpeter** [comment]
> but actually it doesn't seem to work. I checked the json file, and it's released + I am already on the latest version. Any clue how to fix this 🤔 ?

You can manually add them to your `~/.config/zed/keymap.json` using the code I pasted above.  Alternatively, if you switch (`welcome: toggle base keymap selector`) your default keybind to Sublime or Atom you'll get them today. At this time we're not going to add it to the vscode-esque default-macos keybindings (vscode does not bind these by default). 

Separately, I also added them to the Sublime Text (Linux) keymap because they were missing there. This has not yet been released and will go out as part of next weeks Zed Preview (v0.145.x 2024-07-17) and trickle down to Zed Stable the following week (2024-07-24).

Thanks for reporting.
