### ISSUE TITLE
Shortcut for reverse history search in terminal triggers symbol view instead

### ISSUE THREAD

**Issue by GyozaGuy** [zed-industries/zed#14033]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Starting with version 0.143.5, pressing `Ctrl+R` in the terminal to trigger a reverse history search triggers the symbols view instead. Previous to this version, the symbols shortcut was `Super+R`.

### Environment

Zed: v0.143.5 (Zed Preview)
OS: Linux X11 ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

`Ctrl+R` should not trigger the symbols view if the terminal is currently focused. Ideally, any well-known terminal shortcuts should probably not trigger other Zed features while the terminal is focused.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Yeah, a few folks have run into this.  I'm not sure the correct answer here as some people clearly people expect `ctrl-w` to be passed to the terminal (as it is currently) while others expect `ctrl-w` to close the terminal tab.

We currently have two key combinations that passthru by default in terminal:
https://github.com/zed-industries/zed/blob/89fbd6528f688cc98eaa4b3002f4b41da6c7b520/assets/keymaps/default-linux.json#L251-L257

You can add more to do the same in your ~/.config/zed/keymap.json:
```
[
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-r": ["terminal::SendKeystroke", "ctrl-r"]
    }
  }
]
```

If this doesn't work, let me know.

**Comment by GyozaGuy** [comment]
That works perfectly, thanks!

**Comment by jacobef** [comment]
That keymap.json fix doesn't work for me; ctrl+R still does nothing.

I have Zed Preview 0.195.0, with macOS Sequoia 15.5, on an M1 macbook air. ctrl+R works fine on macOS Terminal, so my .zshrc isn't the problem.

I've attached my settings.json and keymap.json. Could this issue be reopened @notpeter ? Thanks.

[keymap.json](https://github.com/user-attachments/files/21179243/keymap.json)
[settings.json](https://github.com/user-attachments/files/21179244/settings.json)

**Comment by notpeter** [comment]
@jacobef `ctrl-r` works as expected for me on macos with no custom keymap.
The above was for linux users.

Can you open `dev: key context view` and see what it shows when you type `ctrl-r` in a editor buffer? It should show two no match results. If not, you might have another global utility capturing ctrl-r before it's getting to zed.  With the above custom keymap I see this when I hit ctrl-r in Terminal:

<img width="517" height="151" alt="Image" src="https://github.com/user-attachments/assets/b026aac6-066b-4993-aca7-eddf29ad990d" />

**Comment by jacobef** [comment]
@notpeter I get the correct key context view, but the bck-i-search still doesn't show up on the terminal. Same thing happens even if I remove my .zshrc and .zprofile.

https://github.com/user-attachments/assets/4f2ae238-fe63-4582-b88e-5366ab3c2b6c

**Comment by jacobef** [comment]
@notpeter I found a way you should be able to reproduce. Edit your ~/.zshrc to have `export EDITOR=vi`, then restart Zed and open its terminal. ctrl-R will no longer search on Zed's terminal. It will still search on the macOS terminal. Does that reproduce for you?

(I was wrong about "Same thing happens even if I remove my .zshrc and .zprofile"; I assumed restarting Zed's terminal would be a sufficient reset after removing them, but I needed to restart Zed itself.)

**Comment by randych-gilad** [comment]
@notpeter your snippet worked outright on Windows 🤠
