### ISSUE TITLE
Global socks5/http/https proxy support

### ISSUE THREAD

**Issue by Zicar491** [zed-industries/zed#14036]
### Check for existing issues

- [X] Completed

### Describe the feature

The editor seems pretty awesome and I'd like to try and switch to it but one of the systems I use is a windows computer on an isolated network without any internet connectivity except for a temporary socks5 proxy. 

I know I can simply install all extensions that I need on a computer with internet access and move them over, but a better suited approach would be to have a few config lines for a proxy and have all the requests go through there when enabled.

**Comment by JunkuiZhang** [comment]
It's already supported. You can set a proxy by setting the following in your `settings.json`:

```json
"proxy": "socks5://127.0.0.1:10808",
```

**Comment by notpeter** [comment]
For future reference this you can see this by opening the command palette (cmd+shift+p or ctrl+shift+p) and searching for `zed: default settings`:

https://github.com/zed-industries/zed/blob/95637a032028a5225dc2e39c8b6e0f35365eba50/assets/settings/default.json#L910-L922

**Comment by KiraTheGenius** [comment]
I set this but nothing change!!
{
  "ui_font_size": 18,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "Andromeda"
  },
  "proxy": "http://127.0.0.1:2082"
}

when I use curl in terminal nothing changed!!!!

**Comment by notpeter** [comment]
The `proxy` setting only applies to Zed and it's network calls.  You will have to set environment variables for other programs run under terminal separately. 

Looking at the [curl proxy docs](https://everything.curl.dev/usingcurl/proxies/env.html) I think it's something like:
```
export ALL_PROXY="socks5h://127.0.0.1:2082"
curl https://zed.dev
```

**Comment by Vzhangs** [comment]
same problem as you.
I tried `all_proxy=socks5://127.0.0.1:7890 zed <myproject>`, set  `"proxy": "socks5://127.0.0.1: 7890"` in `setting.json` . I'm sure the proxy setting is not working

**Comment by JunkuiZhang** [comment]
> same problem as you. I tried `all_proxy=socks5://127.0.0.1:7890 zed <myproject>`, set `"proxy": "socks5://127.0.0.1: 7890"` in `setting.json` . I'm sure the proxy setting is not working

`Zed` does **NOT** set the system proxy for you. The `"proxy"` setting in `settings.json` is only used by `Zed` itself. If you want other applications to use a proxy, please refer to their documentation.

For example, to use `rustup` through a proxy, you should create a configuration file `~/.cargo/config.toml` and insert the following:

```toml
[http]
proxy = "socks5://localhost:10808"
```

**Comment by Vzhangs** [comment]
> > same problem as you. I tried `all_proxy=socks5://127.0.0.1:7890 zed <myproject>`, set `"proxy": "socks5://127.0.0.1: 7890"` in `setting.json` . I'm sure the proxy setting is not working
> 
> `Zed` does **NOT** set the system proxy for you. The `"proxy"` setting in `settings.json` is only used by `Zed` itself. If you want other applications to use a proxy, please refer to their documentation.
> 
> For example, to use `rustup` through a proxy, you should create a configuration file `~/.cargo/config.toml` and insert the following:
> 
> ```toml
> [http]
> proxy = "socks5://localhost:10808"
> ```

I can't get into the extensions market, and my authentication isn't working in application, and the auto update keeps failing.   I guess this is a job with the Zed itself.

<img width="779" alt="截屏2024-07-17 21 00 29" src="https://github.com/user-attachments/assets/9f5b0048-711f-4117-8952-ce42dc073f57">

<img width="1000" alt="截屏2024-07-17 21 04 02" src="https://github.com/user-attachments/assets/47fe572b-3c6a-48a9-a262-de7f5fda375f">

**Comment by notpeter** [comment]
Are on a truly isolated network without functioning DNS?
It appears you keep using `socks5` instead of `socks5h` -- I believe the latter is required if you need the SOCKS proxy to handle host resolution. Can you try that and report back?

**Comment by JunkuiZhang** [comment]
> set `"proxy": "socks5://127.0.0.1: 7890"` in `setting.json` . I'm sure the proxy setting is not working

Your settings `socks5://127.0.0.1: 7890` has a wihtespace, is this what you are using right now? Try remove that whitespace, or use a http proxy: `http://127.0.0.1:7890`

**Comment by Vzhangs** [comment]
> > set `"proxy": "socks5://127.0.0.1: 7890"` in `setting.json` . I'm sure the proxy setting is not working
> 
> Your settings `socks5://127.0.0.1: 7890` has a wihtespace, is this what you are using right now? Try remove that whitespace, or try to use a http proxy: `http://127.0.0.1:7890`

It was a typing mistik. There's no space in the actual configuration.

**Comment by Vzhangs** [comment]
> Are on a truly isolated network without functioning DNS? It appears you keep using `socks5` instead of `socks5h` -- I believe the latter is required if you need the SOCKS proxy to handle host resolution. Can you try that and report back?

I'll check on it in the next few days and report back

**Comment by Vzhangs** [comment]
It appears to be an issue of the timeout setting being set too short. When I use a cross-country network proxy, I encounter higher network latency, which usually reaches seconds. I modified the timeout configuration and rebuild zed, the problem was resolved.

**Comment by notpeter** [comment]
@Vzhangs Glad to hear it.  For the benefit of future searchers which timeout did you modify, `CONNECTION_TIMEOUT` in `crates/client/src/client.rs`?

https://github.com/zed-industries/zed/blob/4852e170ffd63532bc751da8ecc3cae05056586c/crates/client/src/client.rs#L89-L92

**Comment by Vzhangs** [comment]
@notpeter 
In here

https://github.com/zed-industries/zed/blob/4852e170ffd63532bc751da8ecc3cae05056586c/crates/http/src/http.rs#L189-L198

Modifying these two configurations allowed my zed to auto update and access the extension market, but it still didn't solve the problem of not being able to sign in, which still showing time out.

**Comment by JunkuiZhang** [comment]
>  but it still didn't solve the problem of not being able to sign in, which still showing time out.

The first login attempt shows a timeout, then it retries with the proxy. On my Windows and macOS builds with a proxy server located in New York, USA (with a 600ms lag), the login process can take 1-2 minutes.

Additionally, on Discord, someone using an isolated network was able to log in through a proxy, so I think the functionality is working correctly.

![Screenshot 2024-07-18 182231](https://github.com/user-attachments/assets/39957aec-aff9-4d72-b6c1-f7be5a6b0626)

**Comment by Vzhangs** [comment]
> > but it still didn't solve the problem of not being able to sign in, which still showing time out.
> 
> The first login attempt shows a timeout, then it retries with the proxy. On my Windows and macOS builds with a proxy server located in New York, USA (with a 600ms lag), the login process can take 1-2 minutes.
> 
> Additionally, on Discord, someone using an isolated network was able to log in through a proxy, so I think the functionality is working correctly.
> 
> ![Screenshot 2024-07-18 182231](https://private-user-images.githubusercontent.com/14981363/349918193-39957aec-aff9-4d72-b6c1-f7be5a6b0626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTk5MzcsIm5iZiI6MTcyMTI5OTYzNywicGF0aCI6Ii8xNDk4MTM2My8zNDk5MTgxOTMtMzk5NTdhZWMtYWZmOS00ZDcyLWI2YzEtZjdiZTVhNmIwNjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmM0MmI2NTgwYzIxYTkzYjRkMmQ0YjVmMjJhMDgyMmI4OTE2NDAxNTViMDhkNmFhNGY3YjE1ZDJjOTFhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JMBx0NLkeZgp27o-0JjLeCN3w2a6B6Eg5e5EgTKnNYg)

Correct, there should be no problem with the proxy function, it should be my network delay is too high
