### ISSUE TITLE
Zed show the title bar on windows 10

### ISSUE THREAD

**Issue by shenjackyuanjie** [zed-industries/zed#14059]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/54507071/9c7672f0-fa28-4fc7-93f3-531a66ef36a8)

![image](https://github.com/zed-industries/zed/assets/54507071/8eebb847-9bdc-485d-834e-18dcaef602fd)

### Environment

```
Zed: v0.145.0 (Zed Dev f147722fe08775585b8e6711ba68d0474781472b)
OS: Windows 10.0.19045
Memory: 95.9 GiB
Architecture: x86_64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/54507071/0c9b57ef-dfa6-40cd-aff1-26f14672f850)

### If applicable, attach your Zed.log file to this issue.

no log

**Comment by huacnlee** [comment]
Commit: f147722fe08775585b8e6711ba68d0474781472b is v0.145.x dev

Would you please to try other previous commits, to help us find which is work fine before.

**Comment by shenjackyuanjie** [comment]
commit 5e1521ede works well
![image](https://github.com/zed-industries/zed/assets/54507071/535c3a74-bfbe-4cfe-be0f-31a87514ccf8)

![image](https://github.com/zed-industries/zed/assets/54507071/e342bd77-8596-4737-bcbd-f82400d76498)

looking for the wrong commit

**Comment by shenjackyuanjie** [comment]
caught!

![image](https://github.com/zed-industries/zed/assets/54507071/e0a2936b-841f-43f5-a792-49a1983ce39f)

commit: 68b5ea4e606acd3ca94b0d0fe3548191705d8ce2

need revert: #13420

**Comment by shenjackyuanjie** [comment]
it's now fixed!
