### ISSUE TITLE
`CTRL` shortcuts not working properly on Linux

### ISSUE THREAD

**Issue by aminya** [zed-industries/zed#14085]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried the recently released Zed build for Linux, however, I could not work on a codebase for long, and the main issue is that `CTRL` doesn't work as expected. The critical affected shortcuts I expect to work:

```
CTRL + C:  copy
CTRL + V: paste
CTRL + A: select all
```

### Environment

Zed 0.143.6 – /home/aminya/.local/zed.app/libexec/zed-editor

```
neofetch
             `..---+/---..`              
         `---.``   ``   `.---.`            -----------------------
      .--.`        ``        `-:-.         OS: KDE neon 6.0 x86_64
    `:/:     `.----//----.`     :/-     
   .:.    `---`          `--.`    .:`      Kernel: 6.5.0-41-generic
  .:`   `--`                .:-    `:.     Uptime: 27 mins
 `/    `:.      `.-::-.`      -:`   `/`    Packages: 3095 (dpkg), 83 (brew), 40 (flatpak), 25 (snap)
 /.    /.     `:++++++++:`     .:    .:    Shell: bash 5.1.16
`/    .:     `+++++++++++/      /`   `+`   Resolution: 2560x1440, 2560x1440
/+`   --     .++++++++++++`     :.   .+:   DE: Plasma 6.1.2
`/    .:     `+++++++++++/      /`   `+`   WM: KWin
 /`    /.     `:++++++++:`     .:    .:    Theme: Breeze-Dark [GTK2], Breeze [GTK3]
 ./    `:.      `.:::-.`      -:`   `/`    Icons: breeze-dark [GTK2/3]
  .:`   `--`                .:-    `:.     Terminal: WarpTerminal
   .:.    `---`          `--.`    .:`      
    `:/:     `.----//----.`     :/-      
      .-:.`        ``        `-:-.        
         `---.``   ``   `.---.`           
             `..---+/---..`
```

(copy system specs into clipboard doesn't work on Linux)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by aminya** [comment]
I think the issue is that I had a `~/.config/zed/keymap.json` file already remaining from the time I was working on the Linux builds. Removing that file fixes the behaviour.

**Comment by llogick** [comment]
> For me, CTRL + J (for open terminal) does not work either.
> 
> However, the ones you mentioned worked for me

Weird, I just posted about this on Discord :)

The issue is there are [conflicting bindings for 'ctrl-j'](https://github.com/search?q=repo%3Azed-industries%2Fzed+%22ctrl-j%22+path%3A%2F%5Eassets%5C%2Fkeymaps%5C%2Fdefault-linux%2F&type=code)
If the Editor has focus JoinLines is triggered, if you toggle the left dock on(or off on so it grabs focus) - you get ToggleBottomDock.

**Comment by notpeter** [comment]
> Weird, I just posted about this on Discord :)
> 
> The issue is there are [conflicting bindings for 'ctrl-j'](https://github.com/search?q=repo%3Azed-industries%2Fzed+%22ctrl-j%22+path%3A%2F%5Eassets%5C%2Fkeymaps%5C%2Fdefault-linux%2F&type=code) If the Editor has focus JoinLines is triggered, if you toggle the left dock on(or off on so it grabs focus) - you get ToggleBottomDock.

Thanks for pointing this out.  I've opened a PR to fix this:
- https://github.com/zed-industries/zed/pull/14136
