### ISSUE TITLE
`mktemp: Invalid argument` when attempting to install vial curl script

### ISSUE THREAD

**Issue by quadroli** [zed-industries/zed#14082]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Upon attempting to install zed on linux via the curl script, I get `mktemp: Invalid argument`

### Environment

unfortunately I can't access the command palette but:
- Alpine Linux 3.19

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I've fixed the install script.
Alpine's busybox `mktemp` demanded `XXXXXX` and rejected `XXXXX`.
It may still take some work to get running (musl, etc) but now it'll download.
