### ISSUE TITLE
Vim: Repeating indent/outdent doesn't work and makes Zed unresponsive

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#14094]
### Check for existing issues

- [X] Completed

If #12582 hasn't yet been released, I apologize, and you can close this.

### Describe the bug / provide steps to reproduce it

On macOS:

- enable Vim mode
- make a selection with visual block mode
- indent (`>`) or outdent (`<`)
- repeat that action using the dot binding `.`

For me nothing happened, and my Zed becomes unresponsive for about 20 seconds.

### Environment

Zed: v0.143.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
cc @ConradIrwin

**Comment by ConradIrwin** [comment]
@silvenon I can reproduce that in visual block mode `.` does not work for `>` (when you select from top to bottom) because we don't restore the cursor position correctly in that case.

I am surprised that it's crashing zed for you. Do you have any custom keybindings or settings that might interfere?

**Comment by silvenon** [comment]
Erm, I can't reproduce the bug anymore, indenting and outdenting is repeatable for me now 😮 Maybe something happened during upgrading Zed that broke that functionality for me previously, and now that I restarted it it works…? But you claim to not be able to repeat it 😕 

Still, here are my settings and keymap if it helps:

<details><summary><code>settings.json</code></summary>

```jsonc
{
  "base_keymap": "VSCode",
  "vim_mode": true,
  "preview_tabs": {
    "enable_preview_from_code_navigation": true
  },
  "cursor_blink": false,
  "terminal": {
    "blinking": "off"
  },
  "tab_size": 2,
  "tab_bar": {
    "show_nav_history_buttons": false
  },
  "theme": {
    "mode": "system",
    "light": "Atelier Cave Light",
    "dark": "Ayu Dark"
  },
  "file_types": {
    "HTML": ["html", "svg"],
    "JSON": ["json", "jsonc"],
    "Shell Script": ["sh", ".env*"]
  },
  "git": {
    "inline_blame": {
      "enabled": false
    }
  },
  // https://github.com/biomejs/biome-zed/issues/15#issuecomment-2115655791
  "language_servers": ["!biome", "..."],
  "languages": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "TypeScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "TSX": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
}
```

</details>

<details><summary><code>keymap.json</code></summary>

```jsonc
[
  {
    "context": "Terminal",
    "bindings": {
      "cmd-t": "workspace::NewTerminal"
    }
  },
  {
    "context": "ProjectPanel",
    "bindings": {
      "cmd-backspace": ["project_panel::Trash", { "skip_prompt": true }]
    }
  }
]
```

</details>

https://github.com/user-attachments/assets/25482b65-b94e-4471-a19e-1f5b682d2201

**Comment by ConradIrwin** [comment]
Ok, will close for now, let me know if you can reproduce!

**Comment by ChrisW-priv** [comment]
I actually have the same issue (not crash but just not working) for any "repeat command" after I type "." in normal mode. Is there any other issue I should follow?

**Comment by ConradIrwin** [comment]
@ChrisW-priv Not that I know of. Can you please let me know what you're doing (and also share your keymap?). `.` should in general work.

**Comment by ChrisW-priv** [comment]
@ConradIrwin, sure, will do... tomorrow xd. But definitely "ciw" and then entering new text or the ">>" to increase indentent, fails after "." to repeat. Instead see some repeated "<<<<<<<<<<[...]" on the bottom ribbon. Will do some screenshots when I will have my laptop on me.

**Comment by ChrisW-priv** [comment]
<img width="1470" height="52" alt="Image" src="https://github.com/user-attachments/assets/c96a4b85-f672-4d3c-bb27-ebaa9b686f87" />

the image shows the bottom ribbon after the "." is pressed. It is definately response to the press, cuz when I later do anything else (any key command after ".") then it dissapeers.

as for the keymap:

```json
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: open default keymap`
// from the command palette.
[
  {
    "context": "Workspace",
    "bindings": {
      "alt-[": "workspace::ToggleLeftDock",
      "alt-]": "workspace::ToggleRightDock",
      "alt-0": "workspace::ToggleBottomDock",
    }
  },
  {
    "context": "Editor && vim_mode == insert && !menu",
    "bindings": {
      // "j k": "vim::SwitchToNormalMode"
    }
  }
]
```

@ConradIrwin is this enough or should I try to share something else?

**Comment by ConradIrwin** [comment]
Hmm, it also look like you have a gigantic count on the left... Do you have time to dig into this with me on a screen share? feel free to reach out to conrad@zed.dev

**Comment by ChrisW-priv** [comment]
@ConradIrwin I have never done it but I am eager to try :) . Only thing is that I cannot do this this week, how about next Tuesday? I haven't used the colab features of the zed yet. Is there a chat we can discuss the time?

**Comment by ConradIrwin** [comment]
Perfect, feel free to book time https://cal.com/conradirwin/pairing. If you haven't yet screenshared in Zed, it's worth testing that before hand to make sure you have system permissions.

**Comment by ChrisW-priv** [comment]
Seems, like I will not have time to day in the end... But I have a link so I will book time when I know I will be able to meet. Sorry, and see you soon.

**Comment by Axeldeblen** [comment]
sorry to hijack the thread but

@ChrisW-priv did you resolve the issue I have the same problem

**Comment by ChrisW-priv** [comment]
Hi @Axeldeblen sorry for the late response as well as not posting but the issue got "magically" resolved. I think that my zed installation got updated or the mac was reset and that resolved the issue but TBH, I did not go too deep into this problem.
