### ISSUE TITLE
Linux: install CLI not implemented

### ISSUE THREAD

**Issue by smirzaei** [zed-industries/zed#14118]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`cli: install` command is not working. Looks like it's not implemented yet (more detail in the application logs).

### Environment

```
Zed: v0.143.6 (Zed)
OS: Linux Wayland arch unknown
Memory: 62.6 GiB
Architecture: x86_64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/829535/1a02d08d-2c7a-452a-bfee-dc55d29c0c10)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-10T18:48:51-04:00 [ERROR] Platform<LinuxPlatform>::path_for_auxiliary_executable is not implemented yet
2024-07-10T18:48:57-04:00 [ERROR] Platform<LinuxPlatform>::path_for_auxiliary_executable is not implemented yet
2024-07-10T18:48:57-04:00 [ERROR] Platform<LinuxPlatform>::path_for_auxiliary_executable is not implemented yet
</pre></details>

**Comment by smirzaei** [comment]
I can give it a go if you tell me what this function is supposed to return exactly.
https://github.com/zed-industries/zed/blob/e6d608fa055dfa96eb9e0c65e14348f38de6968d/crates/gpui/src/platform/linux/platform.rs#L391-L395

The mac implementation uses `NSBundle::mainBundle()` but I'm familiar with macOS applications.
https://github.com/zed-industries/zed/blob/e6d608fa055dfa96eb9e0c65e14348f38de6968d/crates/gpui/src/platform/mac/platform.rs#L771-L786

**Comment by ConradIrwin** [comment]
@smirzaei I don't think `path_for_auxiliary_executable` makes much sense on Linux, as the app isn't bundled the same way.

What you do need to do is find the current path to the CLI. In the "normal" case, this will be at `../bin/zed` from the currently running `zed-editor` binary; but in the abnormal case it could be in a different place, called something different, or just totally missing.

In the case we can find it we then need to symlink it onto the users path as we do on macOS. We'll need a different way to prompt for sudo if the user has no writable directories on the path.

Thanks for taking this on!

**Comment by smirzaei** [comment]
I see, thank you for explaining it.

My initial reaction was to look for it in conventional locations such as `/usr/bin/zed`, and see if we can find the file. If found then create a symlink to it at `~/.local/bin`. This way we don't need to deal with sudo access.

But it's going to be a bit more complicated. As you mentioned each distro could put it in a different place or even name it something different. For example if I try to look for `zed` binary, in the current Archlinux package, I can't find it [because it's named `zeditor`](https://gitlab.archlinux.org/archlinux/packaging/packages/zed/-/blob/69c577ea265c80de5a16f02cbcb74fb6fc5a7214/PKGBUILD#L41):

```BASH
$ pacman -Ql zed
zed /usr/
zed /usr/bin/
zed /usr/bin/zeditor
zed /usr/lib/
zed /usr/lib/zed/
zed /usr/lib/zed/zed-editor
zed /usr/share/
zed /usr/share/applications/
zed /usr/share/applications/dev.zed.Zed.desktop
zed /usr/share/icons/
zed /usr/share/icons/zed.png
```

Another thing that we can do is to see where major distributions are putting the cli tool, create a list and go through that. But it's going to be a bit cumbersome to maintain.

Any suggestions?

**Comment by ConradIrwin** [comment]
I think we could do a simple version where:
* If zed is in `/.local/X/bin/zed` then we symlink it into your path
If not, we continue to show an error.

In most cases though I'd expect a distribution to have already put the CLI somewhere on the path (that's the whole point :D) so making the error message more helpful might help. 

"Cannot find `zed` instance. If you installed Zed from your distro, you may need to `alias zed=zedit or zed=zeditor`" Or something.

Conrad

**Comment by smirzaei** [comment]
Thanks @ConradIrwin. It's clear to me now that everything is working as intended. I was just thrown off by those error logs and thinking hey I found a bug! :D

> If zed is in /.local/X/bin/zed then we symlink it into your path

I'll skip this part since the error message clearly mentions adding `~/.local/bin` to the PATH, so I don't think it's necessary (just my personal opinion if you think otherwise, let me know).

I'll go ahead and update the error message to give more hints.
