### ISSUE TITLE
Binary plist support

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/zed#14117]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like the ability to edit binary plist (pblist) files as regular XML files. This could be supported in extensions if there's an API for custom file reading/writing.

has VSCode the [Binary Plist VSCode extension](https://marketplace.visualstudio.com/items?itemName=dnicolson.binary-plist), which uses VSCode's [Custom Editor API](https://code.visualstudio.com/api/extension-guides/custom-editors).

### Example file

[com.apple.iChat.plist.zip](https://github.com/user-attachments/files/16169836/com.apple.iChat.plist.zip)

**Comment by notpeter** [comment]
The issue you opened on the extensions repo 4minutes before you opened this issue was the correct location.  Please do not create duplicate issues.

- https://github.com/zed-industries/extensions/issues/1019

**Comment by probablykasper** [comment]
I didn't know I had posted it here, I'm sorry
