### ISSUE TITLE
KDE Open File picker behaves oddly

### ISSUE THREAD

**Issue by ColonelPhantom** [zed-industries/zed#14127]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Project folder picker is called "Open files" instead of "Open folder".

The project folder picker when you press Ctrl+O is named weirdly. Additionally, it behaves oddly (e.g. I cannot pick a directory by being in it), but I think this is an issue with the portal implementation on my system (KDE Plasma 6).

I think what happens is that the Linux platform implementation in GPUI checks `!files` only, whereas the client only sets `directory`.

### Environment

Zed: v0.142.6 (Zed)
OS: Linux Wayland arch unknown
Memory: 31.2 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by n9010** [comment]
I can confirm this. I'm unable to open any folder via the CTRL + O panel,
Kubuntu 24.04 - KDE 5.27.11
**Zed 0.143.6 **

**Comment by ColonelPhantom** [comment]
> I can confirm this. I'm unable to open any folder via the CTRL + O panel,
> Kubuntu 24.04 - KDE 5.27.11
> **Zed 0.143.6 **

A workaround is to ensure the folder is selected (if you use double-click-to-open then just click it; if you use single-click-to-open then open it and go back up) and click Select, or alternatively to type `.` into the filename bar and then hit Enter or click Select. At least, that works for me on KDE 6.
