### ISSUE TITLE
Crashes on window resize

### ISSUE THREAD

**Issue by NGStaph** [zed-industries/zed#14125]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Window resize (click+drag corners to resize) usually lags (but works) when using a trackpad, crashes when resized with external usb mouse.

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland arch unknown
Memory: 62.5 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16170225/Zed.log)

</pre></details>

**Comment by NGStaph** [comment]
adding a screenshot of `zed --foreground` output.

![image](https://github.com/zed-industries/zed/assets/76569058/b3338f1a-f5a9-46a6-bdb3-8c3582644232)

**Comment by NGStaph** [comment]
fixed in Zed 0.144.4

**Comment by erhuz** [comment]
Found this Issue and am having this problem om 0.163.3
