### ISSUE TITLE
VIM: pane::DeploySearch is in visual mode after searching

### ISSUE THREAD

**Issue by sunwxg** [zed-industries/zed#14135]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Reproduce steps:
1. In vim mode
2. Open deploy search
3. search some text
4. In the result view, it is in visual mode.

Expected:
After searching, the view is in normal mode.

### Environment

Zed: v0.142.0 (Zed)
OS: openSUSE Tumbleweed
Memory: 16 GiB
Architecture: X86-64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
Fixed by #16477
