### ISSUE TITLE
CSD should follow current DE titlebar button layout configuration

### ISSUE THREAD

**Issue by alissonlauffer** [zed-industries/zed#14131]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm loving Zed on my Linux desktop, but one of the things that still bothers me is that its CSD doesn't follow my system titlebar button layout configuration (I have it set to appear on the left, with only the close button enabled).

I'm not sure how this could be implemented in other DEs, but in GNOME at least I can get the preference with `gsettings get org.gnome.desktop.wm.preferences button-layout` (though this would probably not be reliable, as it should monitor this preference to update accordingly if it changes).

**Comment by notpeter** [comment]
I'm going to close this in favor of:
- https://github.com/zed-industries/zed/issues/14120

Please 👍 to vote for that issue and subscribe to track its progress.
