### ISSUE TITLE
Close task terminal on success

### ISSUE THREAD

**Issue by LoricAndre** [zed-industries/zed#14148]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, every terminal spawned by a task is kept after the task finishes, but is not usable.

I'd like to be able to configure the task so that the terminal pane automatically closes on success

**Comment by bersace** [comment]
This would be great for lazygit task. Leaving lazygit close the tabs. That's a cheap Source controle view panel.

cf. #4367

**Comment by claytonrcarter** [comment]
Yes, please. In particular, this would be very useful in conjunction with test tasks: run the task and close the pane/dock if it passes, or leave it open for inspection if it fails.

**Comment by bersace** [comment]
@SomeoneToIgnore you're awesome :heart:
