### ISSUE TITLE
support for snap or flatpak flathub

### ISSUE THREAD

**Issue by olumolu** [zed-industries/zed#14145]
### Check for existing issues

- https://github.com/zed-industries/zed/issues/9922

### Describe the feature

this will increase the availability of linux distros and easy to maintain and manage also and this will give benefit to the immutable distros like steam os steamos forks fedora silverble opensuse aeons and others

**Comment by notpeter** [comment]
There has been previous work and discussions here:
- https://github.com/zed-industries/zed/issues/6687
- https://github.com/zed-industries/zed/pull/12006

**Comment by tmke8** [comment]
Snap has support for the `--classic` confinement (i.e., no confinement) which might make it easier to package zed for snap compared to flatpak. Classic confinement requires explicit authorization by the snap store, but IDEs are explicitly mentioned as an example of programs where classic confinement is allowed: https://snapcraft.io/docs/reviewing-classic-confinement-snaps#supported-6 so it shouldn't be too difficult.

**Comment by popey** [comment]
I've snapped a bunch of things over the years, and would happily volunteer to help someone on the team if they need it. In short, something like this needs to happen, if the team wish to snap zed. I'm happy to help with any or all of this. 🙏 

* Build a prototype snap to make sure it's snappable and works as expected
* Register the name 'zed' in the snap store (preferably under an official 'zed industries' account
* (optionally) add a community contributor (such as myself, or other interested party) as a 'collaborator' in the store, if zed people are too busy to bootstrap this
* Request classic confinement for zed on the snapcraft forum
* Publish the snap in a 'candidate' channel
* Upload screenshots, and detailed metadata to make the web based snap store page appealing
* Put out a call for testing
* (optional, but recommended) Build automation (GH action for example) to update the snap as required
* (later, also optional) Ask Canonical to promote the snap as a 'Featured' 'Editors pick' to increase awareness

**Comment by olumolu** [comment]
Thanks if you can help on another project.
https://github.com/Jeffser/Alpaca
@popey

**Comment by olumolu** [comment]
https://github.com/zed-industries/zed/issues/9922
Repeated issues

**Comment by mikayla-maki** [comment]
This is now available on [`Flathub`](https://flathub.org/apps/dev.zed.Zed) :)

**Comment by isgj** [comment]
too bad that snap was not considered and the issue is closed :(

**Comment by jokeyrhyme** [comment]
I think the recent flatpak support satisfies the "snap or flatpak" in the title of this issue

No harm in raising a new issue to cover Snap if that's still a concern

**Comment by olumolu** [comment]
https://github.com/zed-industries/zed/issues/9922
This issue is still opened still if you want you can create a fresh.
