### ISSUE TITLE
List Flatpak on website

### ISSUE THREAD

**Issue by Vinnl** [zed-industries/zed#14152]
### Check for existing issues

- [X] Completed

### Describe the feature

According to https://github.com/zed-industries/zed/issues/6687#issuecomment-2134192336 there is now a Flatpak, but there are no pointers on where to get it (and it likely [won't be on Flathub](https://github.com/zed-industries/zed/pull/12006#issuecomment-2134191883) for a while).

Would it be possible to add a mention on https://zed.dev/docs/linux#installing-via-a-package-manager?

**Comment by olumolu** [comment]
https://github.com/zed-industries/zed/issues/9922
Duplicate

**Comment by Vinnl** [comment]
@olumolu That issue is about adding the Flatpak to Flathub, which [I gather has some hurdles to overcome](https://github.com/zed-industries/zed/pull/12006#issuecomment-2201677355). This issue is about pointing people to the Flatpak that was already added, even though it's not on Flathub (yet?).

**Comment by olumolu** [comment]
Ok

**Comment by olumolu** [comment]
When will i get this feature?

**Comment by BuonHobo** [comment]
Dude, when it's ready

**Comment by olumolu** [comment]
> Dude, when it's ready

I know but this is really important for my workflow that happens on a ostree system so installing with sh is extremely hard

**Comment by BuonHobo** [comment]
I use Silverblue and it was as easy as running one command. The install is very clean and contained within your home, it also updates automatically.

**Comment by Vinnl** [comment]
FWIW, there's a test build for Flathub now with a command to install it: https://github.com/flathub/flathub/pull/5253#issuecomment-2248503461

That won't auto-update, but it looks like it'll be added to Flathub proper soon too.

**Comment by BuonHobo** [comment]
It's your computer, who cares what's recommended, you decide. It's fine as long as you don't get issues because of it.
The recommended way to install zed in Linux right now is in the home directory (it's also the recommended way to install industry standards like Jetbrains IDEs).
The flatpak is also probably harder to use (at least now) because it runs in a sandbox, and if you break the sandbox then there's no benefit either.

I'd say just install it with the sh command and enjoy it for now. When the flatpak comes you can try it

**Comment by olumolu** [comment]
> It's your computer, who cares what's recommended, you decide. It's fine as long as you don't get issues because of it. The recommended way to install zed in Linux right now is in the home directory (it's also the recommended way to install industry standards like Jetbrains IDEs). The flatpak is also probably harder to use (at least now) because it runs in a sandbox, and if you break the sandbox then there's no benefit either.
> 
> I'd say just install it with the sh command and enjoy it for now. When the flatpak comes you can try it

Try to understand why installing .sh is wrong in the first place for all distros and all oparating systems let me tell you providing any script to run in your system with sudo is a fundamentally worng stuff to do and to be Frank.
A script can do many thing that even maybe the user don't want to do.
Hence i recommend to have a official verified flatpak makes too much sense.
Once the application is matured enough and devs have some free time may be a deb or rpm can be considered.

**Comment by olumolu** [comment]
> FWIW, there's a test build for Flathub now with a command to install it: [flathub/flathub#5253 (comment)](https://github.com/flathub/flathub/pull/5253#issuecomment-2248503461)
> 
> That won't auto-update, but it looks like it'll be added to Flathub proper soon too.

Please make sure it is verified just takes a couple of minutes but it is really good feature untill unless we have proper cryptographically signed flatpak.

**Comment by BuonHobo** [comment]
It's not a sudo script, so it only has access to your own files inside your home directory. These are the same permissions that zed is gonna have anyway...
You can also read the script, it's very short and easy to understand. It only extracts the content, makes a couple of directories and symlinks. 

There are really no issues with installing zed with that particular script...

Anyway, I agree that it's better not to keep this going. I wish good luck to the zed team, I love your editor!

**Comment by olumolu** [comment]
> It's not a sudo script, so it only has access to your own files inside your home directory. These are the same permissions that zed is gonna have anyway... You can also read the script, it's very short and easy to understand. It only extracts the content, makes a couple of directories and symlinks.
> 
> There are really no issues with installing zed with that particular script...
> 
> Anyway, I agree that it's better not to keep this going. I wish good luck to the zed team, I love your editor!

I have read the script i did not find anything wrong.
My above statement was a generalized statement does not applied for this project. But flatpak and snap give a good thing which is sandbox which can be ignored.
I have not installed that on my ostree system but i have install on my suse tumbleweed system and works well. Still i will remove that and install flatpak because
(Example i use a small model using ollama on my on suse system and i have to update that manually every 3-4 days recently i switched to alpaca which is a flatpak so I don't need to do that manually)

**Comment by mikayla-maki** [comment]
It's in :)

https://github.com/zed-industries/zed/blob/main/docs/src/linux.md#installing-via-a-package-manager
