### ISSUE TITLE
Zed won't start on arch VulkanError(ERROR_INCOMPATIBLE_DRIVER)

### ISSUE THREAD

**Issue by salman0ansari** [zed-industries/zed#14156]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Installion command 
```sh
$ curl https://zed.dev/install.sh | sh
```

```sh
$ zed .
error opening [PathLikeWithPosition { path_like: "/home/apex", row: None, column: None }]: VulkanError(ERROR_INCOMPATIBLE_DRIVER)

```

### Environment

apex@skynet 
----------- 
OS: EndeavourOS Linux x86_64 
Host: B550M DS3H AC -CF 
Kernel: 6.9.4-arch1-1 
Uptime: 1 day, 1 hour, 1 min 
Packages: 1253 (pacman) 
Shell: bash 5.2.26 
Resolution: 2112x1188 
DE: Xfce 4.18 
WM: Xfwm4 
WM Theme: Arc-Dark 
Theme: Arc-Dark [GTK2], Arc-Darker [GTK3] 
Icons: Qogir [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Source Code Pro 10 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: NVIDIA GeForce RTX 3060 Ti GDDR6X 
Memory: 7868MiB / 15896MiB 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/30106022/a43f496f-9681-4e01-b183-3f61a6fb4bfd)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16172867/Zed.log)

</pre></details>

**Comment by jplatte** [comment]
Same thing on wayland (sway) for me, using amdvlk.

**Comment by shivambegin** [comment]
any way to fix it?

**Comment by Lavishq** [comment]
> solution

https://github.com/zed-industries/zed/issues/14436

**Comment by salman0ansari** [comment]
fixed by installing nvidia drivers
