### ISSUE TITLE
Add "tab" hotkey for opening new terminal

### ISSUE THREAD

**Issue by tokiory** [zed-industries/zed#14166]
### Check for existing issues

- [X] Completed

### Describe the feature

Add secondary `Cmd + t` hotkey for opening new terminal, when user is focused on terminal.

# Why?
- Current shortcut is `ctrl-~`, it's an VSCode's hotkey (Spoiler: This is not the most convenient keyboard shortcut)
- In the future, when terminals have session recovery, this will lay the groundwork for a hotkey `Cmd + Shift + T` (Restore closed terminal)

**Comment by notpeter** [comment]
`cmd-t` is currently bound to project symbols (same as VSCode "Go to Symbol") 

https://github.com/zed-industries/zed/blob/489077befcc1ac4e1aa4505fa3f27f1a6528da48/assets/keymaps/default-macos.json#L406-L406

But you can add a custom keymap `~/.config/zed/keymap.json` ('zed: open keymap' from cmd+shift+p command palette) and change that as you see fit:

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-t": "workspace::NewTerminal",
      "cmd-alt-t": "project_symbols::Toggle"
    }
  }
]
```

Let me know if you run into any trouble.

P.S. `cmd-shift-t` reopening a closed terminal window is a good idea. I like it.
