### ISSUE TITLE
Swap tabs (pane items) left or right

### ISSUE THREAD

**Issue by eproxus** [zed-industries/zed#14174]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to have keyboard shortcuts for reordering items inside a pane. I frequently have the tabs I use the most to the left, or move related tabs next to each other. It would be nice to be able to do this with keyboard shortcuts.

### If applicable, add mockups / screenshots to help present your vision of the feature

For example, <kbd>⌘</kbd><kbd>{</kbd> and <kbd>⌘</kbd><kbd>}</kbd> are set to focus tabs left or right. It would be nice to be able add <kbd>⇧</kbd> to swap items inside a pane:

```json
[
  {
    "context": "Pane",
    "bindings": {
      "cmd-shift-{": ["pane::SwapItemInDirection", "Left"],
      "cmd-shift-}": ["pane::SwapItemInDirection", "Right"]
    }
  }
]
```

**Comment by notpeter** [comment]
Chrome supports reordering tabs via the keyboard using

- `ctrl-shift-pageup` - move tab left
- `ctrl-shift-pagedown` - move tab right

These keys are not currently bound by default in any Zed keybind. It does not support cycling from one end to the other which means you can slam a tab left or right just by holding ctrl-shift-pageup/pagedown. On a Mac laptop keyboard you can use ctrl-shift-fn-up and ctrl-shift-fn-down for this.

@eproxus On US keyboards `cmd-{` is the same as `cmd-shift-[` so `cmd-shift-{` isn't really possible.  `cmd-[` and `cmd-]` are currently used for forward/back (just like chrome).
