### ISSUE TITLE
Add vim::PreviousLineStart key mapping

### ISSUE THREAD

**Issue by ika-musuko** [zed-industries/zed#14183]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim, we can use the `-` (minus) key to navigate to the first non-whitespace character of the previous line.

I personally often use this key mapping to navigate between lines.

Zed already supports `vim::NextLineStart` and this is mapped to the `enter` key by default. I went ahead and mapped `+` to `vim::NextLineStart` in my personal keymap.json as well, as that is also a standard mapping in vim.

### If applicable, add mockups / screenshots to help present your vision of the feature

We should be able to do something like the following in the keymap.json configuration.
```json
"-": "vim::PreviousLineStart",
```

It could even be provided as a default vim keymap.

**Comment by ConradIrwin** [comment]
Fixed by #14193
