### ISSUE TITLE
Display issue when scrolling down the quick doc

### ISSUE THREAD

**Issue by Wangmz-1211** [zed-industries/zed#14216]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When my mouse hover on the variable to check doc, some information would disappear when I'm scrolling down, I tried several times but it comes the same circumstances.

Like the following image, the text inside the first two `block` disappeared. If I continue to scroll down, other will also disappear. It looks like the texts would disappear by paragraph. 
<img width="669" alt="image" src="https://github.com/zed-industries/zed/assets/72479273/d6175dc0-5632-4e1f-9055-8da7f24fc441">

### Environment

Zed: v0.143.6 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16179873/Zed.log)
</pre></details>

**Comment by notpeter** [comment]
Would it be possible for you to share an example project that triggers this bug?
I haven't been able to reproduce it yet.

**Comment by Wangmz-1211** [comment]
> Would it be possible for you to share an example project that triggers this bug? I haven't been able to reproduce it yet.

Here is project structure.

```zsh
❯ tree .
.
├── main.py
└── pyrightconfig.json

1 directory, 2 files
```

**pyrightconfig.json**

```json
{
    "venv": "hf",
    "venvPath": "/opt/homebrew/Caskroom/miniconda/base/envs/"
}
```

**main.py**

```python
from transformers import pipeline

generator = pipeline("text-generation")
res = generator("In this course, we will teach you how to")
print(res)
```

---

I opened the project in iTerm by `zed .`, then hover cursor on `pipeline` in main.py line 3, and scroll down the doc, this always happens.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/9f261297-f113-4361-a4db-c0aeadddb047">

**Comment by Wangmz-1211** [comment]
> Sadly I can't reproduce. I installed transformers in a clean venv (`pip install transformers==4.42.4`) rather than from anaconda, but otherwise should be similar.
> 
> video showing it working for me
> Which theme are you using? Can you try with one of the Zed default themes (e.g. One Dark). Are you using a custom font? If so, can you try disabling it?

It seems like something wrong with theme `Tokyo Night`, when I use `One Dark`, everything work well. Thank you for your help!

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/65e538f8-2282-491a-9b85-3375d6671004">

**Comment by ssaunderss** [comment]
Hi @notpeter I'm the extension author. I took a look at this and it looks like it might be a Zed bug - the links in the popovers lose their text color when you start scrolling and one of the links in the rendered text block nears the top of the popover:

## All links in body popover
<img width="814" alt="Screenshot 2024-07-14 at 5 19 10 PM" src="https://github.com/user-attachments/assets/467d33cb-5b19-4566-bdd1-3fea00e3fb89">

## Links start start to exit near top of popover and lose text color
<img width="820" alt="Screenshot 2024-07-14 at 5 19 21 PM" src="https://github.com/user-attachments/assets/de5495b9-15da-43e8-91fd-90035ca523f5">
