### ISSUE TITLE
Chat Panel Bug

### ISSUE THREAD

**Issue by IceSniperring** [zed-industries/zed#14226]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when I use chat panel, my volume is forced to 100% and my network won't let me play any videos

### Environment

  OS: Manjaro Linux x86_64 
  Kernel: 6.9.5-1-MANJARO 
  Uptime: 15 mins 
  Packages: 1339 (pacman) 
  Shell: bash 5.2.26 
  Resolution: 3072x1920 
  DE: Plasma 6.0.5 
  WM: kwin 
  Theme: Sierra-dark-alt [GTK2/3] 
  cons: Tela [GTK2/3] 
  Terminal: konsole 
  CPU: 12th Gen Intel i5-1240P (16) @ 4.400GHz 
  GPU: Intel Alder Lake-P GT2 [Iris Xe Graphics] 
  Memory: 4490MiB / 15678MiB 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
@IceSniperring audio/video is not yet supported on linux. See #13714 

I am a bit confused by what you mean when you say "audio is forced to 100%", as I didn't think we were doing anything with audio yet. Can you explain more?
