### ISSUE TITLE
Vim surround dot repeat not working

### ISSUE THREAD

**Issue by SimonEggert** [zed-industries/zed#14242]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce given this file:

```
foo
bar
```

1. With cursor on `foo`, type `ysiw"` to surround the word with double quotes: `"foo"`.
2. Go down to `bar`, press `.` to repeat step 1.
3. Expected behavior: `"bar"`; actual behavior:

```
"foo"
bar
bar
```

### Environment

Zed: v0.143.6 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by weartist** [comment]
I'll try to fix this
