### ISSUE TITLE
Unable to disable assistant

### ISSUE THREAD

**Issue by donmccurdy** [zed-industries/zed#14244]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm trying to disable the assistant feature, but can't do so.

1. Set `"assistant": { "enabled": false }` in Zed config
2. Continue using Zed and observe assistant suggestions

### Environment

Zed: v0.143.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Full Zed config:

```jsonc
{
  "base_keymap": "SublimeText",
  "theme": "Gruvbox Dark Soft",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "formatter": "prettier",
  "format_on_save": "on",
  "language_overrides": {
    "JSON": { "format_on_save": "off" },
    "Markdown": {
      "format_on_save": "off",
      "soft_wrap": "preferred_line_length"
    }
  },
  "assistant": { "enabled": false, "version": "1" },
  "use_autoclose": false
}

```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Hey @donmccurdy, the assistant is a panel in either the left or right dock:

<img width="1608" alt="image" src="https://github.com/user-attachments/assets/6cf346ae-151f-442b-a5f9-758d42c6c9ae">

You mentioning that you are still getting suggestions makes me think you might be referring to inline completions (copilot / supermaven), which can be disabled in the settings via:

```json
"features": {
  "inline_completion_provider": "none"
},
```

Let me know if I'm misinterpreting!

**Comment by donmccurdy** [comment]
That was my mistake, yes – didn't realize the assistant vs. inline completions distinction. Thank you!
