### ISSUE TITLE
Creating ollama plugin (copilot/chatgpt like extension)

### ISSUE THREAD

**Issue by alejandro-alzate** [zed-industries/zed#14253]
### Check for existing issues

- [X] Completed

### Describe the feature

Cut and Dry: Forget using copilot or chatgpt with their subscriptions and privacy nightmares.

We have generative transformers at home
_generative transformers at home:_
`$ ollama run codellama` `llama2` etc.

So interfacing with a local running one although with more latency which at least it only costs the electricity bill and a bit of heat.

So having in-house code completion hints would be nice.

**Comment by JosephTLyons** [comment]
Hey @alejandro-alzate, we currently have support for Ollama in the assistant panel:

https://zed.dev/docs/assistant-panel#using-ollama-on-macos

We also have an issue up for someone wanting to potentially add Ollama support for inline completions (copilot/supermaven style completions):

- https://github.com/zed-industries/zed/issues/14253

Feel free to upvote that with a 👍 one, I'm going to close this one out.

**Comment by alejandro-alzate** [comment]
Sorry for bothering though. but thanks!

**Comment by brianevanmiller** [comment]
> Hey @alejandro-alzate, we currently have support for Ollama in the assistant panel:
> 
> https://zed.dev/docs/assistant-panel#using-ollama-on-macos
> 
> We also have an issue up for someone wanting to potentially add Ollama support for inline completions (copilot/supermaven style completions):
> 
> * [Creating ollama plugin (copilot/chatgpt like extension) #14253](https://github.com/zed-industries/zed/issues/14253)
> 
> Feel free to upvote that with a 👍 one, I'm going to close this one out.

@JosephTLyons - it looks like you linked the same issue here.  

I personally think local LLM support for inline completions would be excellent.  I work on a few private codebases and don't trust Supermaven / Copilot with those codebases.

Should we open a new issue or did you mean to refer to an existing issue?

**Comment by shishkin** [comment]
I think https://github.com/zed-industries/zed/issues/18490 was supposed to be linked instead.
