### ISSUE TITLE
Workspace Freezes in Awesome Window Manager When Using Zed and Switching Workspaces

### ISSUE THREAD

**Issue by Daniel-Boll** [zed-industries/zed#14268]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Within a few minutes of opening Zed and switching workspaces in the Awesome Window Manager, all workspaces freeze. The other monitor remains unaffected, but I cannot recover from this state until I log out. Refreshing Awesome causes the windows to move to the other monitor, but they remain unresponsive and do not repaint.

Oddly, the logs do not indicate any errors, making the debugging process challenging.

### Environment

Zed: v0.143.6 (Zed)
OS: Linux X11 endeavouros unknown
Memory: 23.3 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment]
Does Awesome Window manager provide any additional logging that might help us here? I'm not sure there is much we can do here without that. I think I will close this out, feel free to reopen if you run into this again and have any additional logging we can use to drill down.
