### ISSUE TITLE
Zed window does not render at all

### ISSUE THREAD

**Issue by gsal** [zed-industries/zed#14271]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Upon launching zed, nothing appears to happen other than a new icon along the bottom task bar.

The hint that zed is attempting to render something in the screen shows after moving some existing windows...it is then that one realizes that part of the screen (where zed presumably is) remains with the same text/graphics from the pre-existing app  as if one had taken a screenshot of a region of the screen. 

### Environment

Linux, Rocky 9.3

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by thedataking** [comment]
I'm seeing the same behaviour on a debian-based Linux distro.

**Comment by JosephTLyons** [comment]
Hey @gsal, I'm adding this issue, as it might be the same thing:

- https://github.com/zed-industries/zed/issues/14314

**Comment by gsal** [comment]
It sure looks similar enough that if they solve that other issue, I am sure that would solve this one, too.

This issue marked as duplicate of  #14204

**Comment by CoderParth** [comment]
@gsal 
Can you please share your log file?
Check the following directory please:
`~/.local/share/zed/logs`

A `.panic` file is likely to have been created. Without the log file, it is quite hard to tell what might have gone wrong. 
But generally, for most users, the GUI issues on linux seem to be coming from x11, and switching to wayland has helped lot of users. Please try to do similar. 

Also, please share your hardware info as well, and please check if your drivers are up to date. 
Zed requires a `Vulkan compatible GPU`, `Vulkan 1.3 driver`, and the following desktop portals:
```
org.freedesktop.portal.FileChooser
org.freedesktop.portal.OpenURI
org.freedesktop.portal.Secret, or org.freedesktop.Secrets

glibc version >= 2.35 is recommended. 
```
