### ISSUE TITLE
Get all location use curent fn

### ISSUE THREAD

**Issue by duyendinh2021** [zed-industries/zed#14289]
### Check for existing issues

- [X] Completed

### Describe the feature

Get all fn points that are currently in use when f12 is pressed

**Comment by notpeter** [comment]
The current binding for f12 are defined here (same in `default-linux.json`)

https://github.com/zed-industries/zed/blob/489077befcc1ac4e1aa4505fa3f27f1a6528da48/assets/keymaps/default-macos.json#L328-L333

Currently "find all references" is bound to `alt-shift-f12` by default.  It's slightly different for Sublime (`shift-f12`) or JetBrains (`alt-f7`) keymaps. 

If you would like to override F12 you can easily add the following to your `~/.config/zed/keymap.json`

```
[
  {
    "context": "Editor",
    "bindings": {
      "f12": "editor::FindAllReferences"
    }
  }
]
```

Let me know if this doesn't work as expected. Thanks
