### ISSUE TITLE
Dart LSP error: "Unknown method textDocument/didSave"

### ISSUE THREAD

**Issue by ernanvr** [zed-industries/zed#14286]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I installed Dart Zed Extension.
Every time I save a file I get "Unknown method textDocument/didSave" error.
![image](https://github.com/user-attachments/assets/ff30ade7-b7be-4723-a43f-4ddf9a01e34c)

### Environment

![image](https://github.com/user-attachments/assets/c995a197-e5f8-4629-a4c4-82875fe325d7)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mcpeng** [comment]
This issue occurred in the latest Zed version (0.143.6, 0.143.7).

**Comment by avatarnguyen** [comment]
I found a related issue on [dart-lang repo](https://github.com/dart-lang/sdk/issues/36464) and [this](https://github.com/natebosch/vim-lsc/issues/164)
My understanding is that dart-lang server doesn't support `textDocumentSync`. Zed editor should check whether the server method is supported before sending it.

**Comment by jocubeit** [comment]
I'm loving Zed, but it's amazing how annoying this bug is... it's making me think about going back to vscode until there's a resolution. I wish I understood how I could fix it.

**Comment by ernanvr** [comment]
> I'm loving Zed, but it's amazing how annoying this bug is... it's making me think about going back to vscode until there's a resolution. I wish I understood how I could fix it.

That's exactly what I was thinking

**Comment by SomeoneToIgnore** [comment]
Thank you @avatarnguyen , that information was very useful.
I've created https://github.com/zed-industries/zed/pull/14412 and that seems to fix the issues.

**Comment by JosephTLyons** [comment]
Closed via 

- https://github.com/zed-industries/zed/pull/14412
