### ISSUE TITLE
vim mode blank page not work

### ISSUE THREAD

**Issue by reaink** [zed-industries/zed#14285]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

vim mode not response, in blank page

my keybinds

``` json
{
    "context": "vim_mode == normal && !menu",
    "bindings": {
      // File finder
      "space space": "file_finder::Toggle"
    }
}
```

![image](https://github.com/user-attachments/assets/970f0340-5919-412d-957e-0de5eb2b8c6b)

relation https://github.com/jellydn/zed-101-setup/issues/7

### Environment

mac
Zed 0.143.6

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
@reaink When there's no editor open there is no `vim_mode`. To bind keys in this case (and in the case you're collaborating with someone and looking at their screen) you need to use the context: `EmptyPane || SharedScreen`.

https://zed.dev/docs/vim#custom-key-bindings has a bunch more details if you're curious!
