### ISSUE TITLE
Bug (VIM): renaming sometimes fails in VIM mode

### ISSUE THREAD

**Issue by Congyuwang** [zed-industries/zed#14292]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In VIM mode, when renaming symbol _using menus_ (**through right click or command panel**),
vim commands interfere with renaming.

After clicking `enter`, the cursor jumps back to next line,
because in VimControl context, `enter` maps to `vim::NextLineStart`.

Also when inputing new variable names, when using `i`, `x` or `v`,
the character triggers vim actions instead.

When I disable VIM mode, renaming works fine.

https://github.com/user-attachments/assets/d6883867-e590-47a0-9de1-19aa8404e001

### Environment

Zed: v0.144.2 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by CharlesChen0823** [comment]
I think this is break recently.

**Comment by Congyuwang** [comment]
But that is quite unlikely. I've tried several previous versions. The problem still persists. I'll try to create a minimal project that can reproduce this.

**Comment by Congyuwang** [comment]
https://github.com/user-attachments/assets/e6388faa-b4c6-4896-9c9b-daffd2162b2d

Ok, I can reproduce this with maybe the simplest python project.

**Comment by Congyuwang** [comment]
https://github.com/user-attachments/assets/adaa5d6a-ed81-493f-b12f-b9613a0fb709

Ok, now with a simple Rust project, it is also reproducible.It sometimes succeeds to rename. Sometimes (the third time), it fails.

**Comment by CharlesChen0823** [comment]
I know what cause this problem, but i have no idea to fix it. current `rename` only stable usable in vim `insert` mode.

**Comment by Congyuwang** [comment]
Yes, I think you are right. Renaming works well in -- INSERT -- mode. When in -- NORMAL --, VIM turns into -- VISUAL -- mode. I'm thinking whether it is reasonable to instead upon renaming action turns into -- INSERT -- mode.

**Comment by CharlesChen0823** [comment]
I also think when rename change vim mode to `insert`, then after rename, change vim mode before. but current `editor` cannot get current vim mode state.

**Comment by Congyuwang** [comment]
Currently after successful renaming, the editor is in -- INSERT -- mode. So, I'd say it is fine if it changes to -- INSERT -- mode once `rename` is invoked, and stays `INSERT` afterwards. This solves the current issue. whether renaming should preserve the old VIM mode, I think belongs to another issue.

**Comment by Congyuwang** [comment]
This problem happens to me only when using trackpad to right click first and select rename, not when using shortcut to rename.

**Comment by Congyuwang** [comment]
Here is a PR that somehow fixes this, but I think it perhaps does not solve the fundamental problem here.

**Comment by Congyuwang** [comment]
I think this is the same issue #11882

**Comment by Congyuwang** [comment]
Another problem is that, when editing the name, pressing any vim-related key results in unexpected behavior. Like when I press `c`:

https://github.com/user-attachments/assets/a7c86b0a-6690-4a65-9916-6812f59c6bb8

Some of my debugging output (pressing `i`):
```
action dispatched: dyn Action { name: "editor::Rename" }

bindings: [
    KeyBinding { keystrokes: [Keystroke { modifiers: Modifiers { control: false, alt: false, shift: false, platform: false, function: false }, key: "i", ime_key: None }], context_predicate: Some(Equal("vim_mode", "visual")), action: "vim::PushOperator" }, 
    KeyBinding { keystrokes: [Keystroke { modifiers: Modifiers { control: false, alt: false, shift: false, platform: false, function: false }, key: "i", ime_key: None }], context_predicate: Some(And(Identifier("VimControl"), Not(Identifier("menu")))), action: "vim::PushOperator" }
]

action dispatched: dyn Action { name: "vim::PushOperator" }
```

Looks like the context is `VimControl` and also not `menu`, and when pressing `i`, or `c` the action dispatched is `PushOperator`.

**Comment by Congyuwang** [comment]
When I press `iikj`, you get the first `i` to be `PushOperator`, and the rest does not have any actions:

```
bindings, [KeyBinding { keystrokes: [Keystroke { modifiers: Modifiers { control: false, alt: false, shift: false, platform: false, function: false }, key: "i", ime_key: None }], context_predicate: Some(Equal("vim_mode", "visual")), action: "vim::PushOperator" }, KeyBinding { keystrokes: [Keystroke { modifiers: Modifiers { control: false, alt: false, shift: false, platform: false, function: false }, key: "i", ime_key: None }], context_predicate: Some(And(Identifier("VimControl"), Not(Identifier("menu")))), action: "vim::PushOperator" }]
action dispatched: dyn Action { name: "vim::PushOperator" }
bindings, []
bindings, []
bindings, []
```

**Comment by Congyuwang** [comment]
@CharlesChen0823 I think this time it should be fixed.

**Comment by Congyuwang** [comment]
#14617
