### ISSUE TITLE
[Linux] Infinite update loop when using manually downloaded package

### ISSUE THREAD

**Issue by ArrayBolt3** [zed-industries/zed#14291]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:

1. Download Zed 0.143.6 (one version older than the latest), unpack it, and run it.
2. Observe "Downloading Zed update..." in the lower-left corner of the screen.
3. Wait for Zed to update, then click on the label in the lower-left corner of the screen to restart Zed.

Expected result: Zed 0.143.7 should launch.

Actual result: Zed 0.143.6 launches, and immediately begins updating itself again.

Additional info:

* I installed Zed by downloading the x86_64 tarball and extracting it to `~/bin/zed.app`. I run it by opening my file manager, navigating to `~/bin/zed.app/bin/`, and then double-clicking the `zed` executable.
* Zed 0.143.7 is available after the update at `~/.local/zed.app/bin/zed`. Launching Zed from here behaves as expected.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Perhaps the `zed` executable should check to see if it is being executed from its user-wide or system-wide path, and relaunch itself from the proper location if not. The behavior could look something like this:

* Has Zed been launched from `~/.local/zed.app/bin/zed`, `/usr/bin/zed`, or `/usr/bin/zed-editor`?
* If so, all is good.
* If not:
  * Is Zed present in one of `~/.local/zed.app/bin/zed`, `/usr/bin/zed`, or `/usr/bin/zed-editor`? (Check in that order)
  * If so, check the version of Zed found in the first matching location. If it is equal to or greater than the currently running version, relaunch Zed from the correct location.
  * If not, or if Zed is not present in any of these locations, copy the running instance of Zed to the user-wide location `~/.local/zed.app`, then relaunch from there.

The logic might need some more work, but you can see the basic idea I'm going for here - the running version of Zed should always be running from a system-wide or user-wide path, so that normal system updates or automatic updates by the editor itself apply properly.

### If applicable, attach your Zed.log file to this issue.

N/A

**Comment by notpeter** [comment]
Got it.  Looks like we are not detecting the current location of the running app bundle when upacking the auto-update and just unpack to `~/.local/`.

https://github.com/zed-industries/zed/blob/489077befcc1ac4e1aa4505fa3f27f1a6528da48/crates/auto_update/src/auto_update.rs#L569-L580

I think we'll punt on fancier system-wide logic for the moment.  We expect global installs will likely be handled by distribution-specific packages that will disable our auto-updater by setting `ZED_UPDATE_EXPLANATION` at build time.  With that specified we show a notification of an available update and the packager provides an explanation (e.g. `You can update zed by running apt-get update && apt-get install --only-upgrade zed-editor` or whatever.)

**Comment by JosephTLyons** [comment]
This should be included in Zed [v0.146.0-pre](https://zed.dev/releases/preview/0.146.0).
