### ISSUE TITLE
Shift + Delete as Cut

### ISSUE THREAD

**Issue by drmad** [zed-industries/zed#14296]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm very impressed about Zed. Today I begun to use it instead of VSCodium 😄 And I'm glad almost all of its key bindings works in Zed too.

...except Shift + Delete as Cut, like Ctrl + X. Shift + Insert already paste, so make sense the Shift + Delete key binding.

I'm working with zed 0.143.7 on Manjaro Linux

**Comment by SomeoneToIgnore** [comment]
Yes, that had been spotted earlier and added in https://github.com/zed-industries/zed/pull/13900
0.143 is Stable so that fix will come on Wednesday, but feel free to adjust your keymap with that for the time being.
