### ISSUE TITLE
Crash on "View Dependency Licenses"

### ISSUE THREAD

**Issue by captn3m0** [zed-industries/zed#14302]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Launch Zed
- Click "View Dependency Licenses"

Zed crashes

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland fedora-asahi-remix 40
Memory: 7.3 GiB
Architecture: aarch64

Package installed via the recommended Terra Fedora repos.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Not on Mac, but here's the log from the crash.

<details><summary>Zed.log</summary><pre>

zed --foreground
[2024-07-12T11:45:01+05:30 ERROR theme] theme not found: Catppuccin Latte
[2024-07-12T11:46:30+05:30 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "/builddir/build/BUILD/zed-0.143.6/crates/util/src/util.rs",
    "line": 570
  },
  "backtrace": [
    "__libc_start_call_main",
    "__libc_start_main_alias_2"
  ],
  "app_version": "0.143.6",
  "release_channel": "Zed",
  "os_name": "Linux Wayland",
  "os_version": "fedora-asahi-remix 40",
  "architecture": "aarch64",
  "panicked_on": 1720764990856,
  "installation_id": "6017871e-82dd-4ebb-a8c9-29ca407f89c7",
  "session_id": "25cb3e5b-27e7-41b6-97e9-98b083fd74ee"
}

</pre></details>

**Comment by captn3m0** [comment]
Can replicate this on a x86_64 setup as well:

```
Zed: v0.143.7 (Zed)
OS: Linux Wayland arch unknown
Memory: 15 GiB
Architecture: x86_64
```


```json
{
  "thread": "main",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "/crates/util/src/util.rs",
    "line": 570
  },
  "backtrace": [
    "__libc_start_main"
  ],
  "app_version": "0.143.7",
  "release_channel": "Zed",
  "os_name": "Linux Wayland",
  "os_version": "arch unknown",
  "architecture": "x86_64",
  "panicked_on": 1720928631318,
  "installation_id": "bcf6ecd5-eb76-4382-b842-6a5eab92f754",
  "session_id": "c5afacd9-0209-44b4-a042-9a77232eede3"
}
```

**Comment by DragonDev1906** [comment]
This also happens with x11
```json
{
  "thread": "main",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "/crates/util/src/util.rs",
    "line": 570
  },
  "backtrace": [
    "__libc_start_main"
  ],
  "app_version": "0.143.7",
  "release_channel": "Zed",
  "os_name": "Linux X11",
  "os_version": "arch unknown",
  "architecture": "x86_64",
  "panicked_on": 1721036019823,
  "installation_id": "7be46a5a-263c-43a2-9fa9-c6e55983dfa5",
  "session_id": "5c7b25d2-85a6-46a5-85c9-56ce379950d6"
}
```

**Comment by graphixillusion** [comment]
Happens on Windows too.

**Comment by graphixillusion** [comment]
This bug still happening on Windows build.

**Comment by graphixillusion** [comment]
Ok, i've understood why this still happens on Windows: it's becouse the script/generate-licenses is a bash script which doesn't run on Windows's shell so a batch/powershell script is needed for this scenario. In the meantime i managed to fix this issue putting an already maded licenses.md in the assets folder before launch the build.
