### ISSUE TITLE
Allow vim:Down/Up to select file names in "find all references", "project diagnostics" etc. tabs

### ISSUE THREAD

**Issue by osa1** [zed-industries/zed#14303]
### Check for existing issues

- [X] Completed

### Describe the feature

When in vim mode, `vim::Down` and `vim::Up` jumps over file names in "find all references", "project diagnostics", and similar buffers.

As a result it's not possible to jump to the error location with just the keyboard. You have to click on the file name with mouse.

I think this is probably not a bug, because without vim mode up/down arrows also jump over these lines.

However a big part of why people use vim mode in IDEs/editors is that it allows mouse-free editing, so it might make sense to have `vim::Down/Up` to work differently and actually select the file names in these buffers.

**Comment by ConradIrwin** [comment]
You can open the excerpts with `g space` (in the current pane) or `<ctrl-w> space` (in the adjacent pane).

It is documented here: https://zed.dev/docs/vim, but not sure it's very clear! Suggestions for improving that welcome.
