### ISSUE TITLE
Highlight files with errors in the project tree

### ISSUE THREAD

**Issue by culebron** [zed-industries/zed#14300]
### Check for existing issues

- [X] Completed

### Describe the feature

If there are compilation errors in a file, change its color to red in the project tree. Set it to yellow if there are no errors, but there are warnings.

A simple sketch of what it could look like:

![image](https://github.com/user-attachments/assets/e40f4483-5325-4a97-8333-2e6efdb7ba1f)

**Comment by rudderbucky** [comment]
I believe this is #5016
