### ISSUE TITLE
[linux] no window

### ISSUE THREAD

**Issue by DevLord261** [zed-industries/zed#14314]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

simply running zed in the terminal doesnt do anything there is no window showing but the process keeps running in background as htop shows ,i am using hyprland 

### Environment

using archlinux
Linux  6.9.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:27 +0000 x86_64 GNU/Linux

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-12T12:41:17+03:00 [INFO] ========== starting zed ==========
2024-07-12T12:41:17+03:00 [INFO] perform;
2024-07-12T12:41:17+03:00 [INFO] read_command;
2024-07-12T12:41:17+03:00 [INFO] read_command;
2024-07-12T12:41:17+03:00 [INFO] socket reader;
2024-07-12T12:41:17+03:00 [INFO] Opening main db
2024-07-12T12:41:17+03:00 [INFO] new;
2024-07-12T12:41:17+03:00 [INFO] keep_updated;
2024-07-12T12:41:17+03:00 [INFO] Using git binary path: None
2024-07-12T12:41:17+03:00 [INFO] updating SHELL environment variable to value from passwd entry: "/usr/bin/bash"
2024-07-12T12:41:17+03:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-07-12T12:41:17+03:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-12T12:41:17+03:00 [INFO] Opening main db
2024-07-12T12:41:17+03:00 [INFO] perform;
2024-07-12T12:41:17+03:00 [INFO] read_command;
2024-07-12T12:41:17+03:00 [INFO] read_command;
2024-07-12T12:41:17+03:00 [INFO] socket reader;
2024-07-12T12:41:17+03:00 [INFO] set environment variables from shell:/usr/bin/bash, path:~/.dotnet/tools:/home/Ghost/.bun/bin:/home/Ghost/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/Ghost/.local/bin:/home/Ghost/.cargo/bin:/var/lib/flatpak/exports/bin:/.local/share/flatpak/exports/bin:/home/Ghost/.local/bin:/home/Ghost/.cargo/bin:/var/lib/flatpak/exports/bin:/.local/share/flatpak/exports/bin
2024-07-12T12:41:17+03:00 [INFO] Enabling Vulkan Portability
2024-07-12T12:41:17+03:00 [WARN] Rejected for device extension "VK_KHR_dynamic_rendering" not supported
2024-07-12T12:41:17+03:00 [ERROR] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
2024-07-12T12:41:18+03:00 [INFO] Node runtime install_if_needed
2024-07-12T12:43:00+03:00 [INFO] starting language server. binary path: "/home/Ghost/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/Ghost/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-12T12:43:01+03:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-12T09:43:01.092Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-12T09:43:01.092Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-12T12:43:01+03:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "9642222d-25b3-42eb-b851-feba4fbf36be",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-12T12:43:01+03:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-12T09:43:01.115Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-12T09:43:01.115Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
</pre></details>

**Comment by kondinskis** [comment]
You are probably missing vulkan drivers.

**Comment by DevLord261** [comment]
> You are probably missing vulkan drivers.

nop i checked i have them vulkaninfo runs normally and giving most of the results true i did installed vulkan in my system

**Comment by kondinskis** [comment]
You can try and install it through arch repositories, it's available there.

**Comment by DevLord261** [comment]
i installed it from the commandline at the website `Zed 0.143.7 – /home/xxx/.local/zed.app/libexec/zed-editor` and its the last version

**Comment by DevLord261** [comment]
> Did you download the binary file from the repository or ? You can try and install it through arch repositories, it's available there.

i am using hyprland and support for vulkan umm idk look at this `https://github.com/hyprwm/Hyprland/issues/1396` 
but i can run vulkan games some apps need vulkan so i doubt if its the issue

**Comment by kondinskis** [comment]
I had similar issue to yours, but after installing it through `pacman -S zed` it works now.

**Comment by DevLord261** [comment]
> I had similar issue to yours, but after installing it through `pacman -S zed` it works now.
still the same this issue has been with me since zed droped preview for linux this stable and the issue same so i dk

**Comment by stalkerg** [comment]
you should just try vkcube and vkinfo and show here

**Comment by DevLord261** [comment]
> you should just try vkcube and vkinfo and show here

vkcube works perfect vkinfo is vulkaninfo here and its long no need to print it and its working fine

**Comment by aalhitennf** [comment]
I have same problem. I previously used zed-preview from AUR and also built it myself, both worked fine. It broken after installing with pacman -S zed :sweat_smile:

**Comment by DevLord261** [comment]
> I have same problem. I previously used zed-preview from AUR and also built it myself, both worked fine. It broken after installing with pacman -S zed 😅
> 
> e. vulkan, drivers etc are installed and working fine.

did u fixed it anything u do i dont think uninstall with zed with pacman and reinstalling the preview will fix it instantly right??

**Comment by aalhitennf** [comment]
> did u fixed it anything u do i dont think uninstall with zed with pacman and reinstalling the preview will fix it instantly right??

I installed Preview version from AUR and now everything seems to be fixed

**Comment by JosephTLyons** [comment]
Hey @DevLord261, this issue sounds a bit similar to this one:

- https://github.com/zed-industries/zed/issues/14204

Can you check and see if it's the same thing you are experiencing? Just trying to collect everything in one area.

**Comment by DevLord261** [comment]
> Hey @DevLord261, this issue sounds a bit similar to this one:
> 
>     * [[Linux] Zed doesn't open #14204](https://github.com/zed-industries/zed/issues/14204)
> 
> 
> Can you check and see if it's the same thing you are experiencing? Just trying to collect everything in one area.

yep it looks the same issue i have but i did what he tries when the zed was in preview version but didnt work also as he said but i didnt bother since it was preview but looks like the issue is not fixed yet but yea same issue and with same error when i try to run the "bin/zeditor" directly instead of "bin/zed" display not detected or something but yea looks the same

**Comment by DevLord261** [comment]
duplocate of  [[Linux] Zed doesn't open #14204](https://github.com/zed-industries/zed/issues/14204)

**Comment by DevLord261** [comment]
closed duplication of [[Linux] Zed doesn't open #14204](https://github.com/zed-industries/zed/issues/14204)

**Comment by andreymal** [comment]
@DevLord261 I'm not sure it's a duplicate

In #14204, the window appears but doesn't draw anything

In this issue, the window doesn't appear at all (if I understand your initial comment correctly), and Zed hangs somewhere (note that, unlike other bug reports, the `Adapter` line doesn't appear in your log)

**Comment by DevLord261** [comment]
> @DevLord261 I'm not sure it's a duplicate
> 
> In #14204, the window appears but doesn't draw anything
> 
> In this issue, the window doesn't appear at all (if I understand your initial comment correctly), and Zed hangs somewhere (note that, unlike other bug reports, the `Adapter` line doesn't appear in your log)

yep i looked again your right but some like me and others not rendering but there is window so idk but mostly look as u said your are right maybe different bug or related i will reinstall zed and try it maybe something changes i did reinstall fresh system so maybe i got better luck

**Comment by lbrealdev** [comment]
> So after reinstalling zed and what did @andreymal said it looks the bug different and its not duplication after i also checked the changes in #14204 the bugs differ from mine theirs not rendering mine there is no window at all only background process of zed running called `zed-editor`

Yes, this seems a different problem, right now I have the problem described in #14204.

However, I was able to carry out some evidence, where zed behaved as described in this problem, where zed was running no window appeared or nothing. I was able to simulate this because I forced zed to start with a specific GPU.

**Comment by BinaryNerd01** [comment]
I am facing the same issue

I would like to know how to resolve this issue and start using the application. I didn't expect this behaviour. I waited a long time for it to be available on Linux, and now that I finally tried using it, it isn't working.

Environment
Virtualization: vmware
Operating System: Red Hat Enterprise Linux 9.4 (Plow)
Kernel: Linux 5.14.0-427.22.1.el9_4.x86_64
Architecture: x86-64
package: 1469(rpm)
Shell: bash
Resolution: 1920x1080
Desktop Environment and Window Manager: GNOME
CPU: Intel(R) Xeon(R) Platinum 8362 CPU @ 2.80GHz

Log:

[INFO] ========== starting zed ==========
[INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
[INFO] x11: compositor present: true, gtk_frame_extents_supported: true
[INFO] Try connect ibus
[INFO] perform;
[INFO] read_command;
[INFO] read_command;
[INFO] Opening main db
[INFO] socket reader;
[INFO] new;
[INFO] Using git binary path: None
[INFO] extensions updated. loading 1, reloading 0, unloading 0
[INFO] activate is not implemented on Linux, ignoring the call
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[INFO] Opening main db
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[INFO] perform;
[INFO] read_command;
[INFO] read_command;
[INFO] socket reader;
[INFO] XConnected server on 8388614, transport version: 0.0, TRANSPORT_MAX: 20
[INFO] Using Visual { id: 77, colormap: 0, depth: 32 }
[INFO] Creating colormap 31457283
[INFO] Enabling Vulkan Portability
[INFO] Enabling color space support
[INFO] Adapter "llvmpipe (LLVM 17.0.6, 256 bits)"
[INFO] No ray tracing extensions are supported
[INFO] Using surface present mode MAILBOX
[INFO] set environment variables from shell:/bin/bash, path:/u01/home/BinaryNerd/.local/bin:/u01/home/BinaryNerd/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/u01/home/BinaryNerd/.local/share/JetBrains/Toolbox/scripts:/u01/home/BinaryNerd/.local/share/JetBrains/Toolbox/scripts:/u01/home/BinaryNerd/.local/share/JetBrains/Toolbox/scripts:/u01/home/BinaryNerd/.local/share/JetBrains/Toolbox/scripts:/u01/home/BinaryNerd/.local/share/JetBrains/Toolbox/scripts
[WARN] Unable to forbid exclusive full screen
[INFO] Creating a descriptor pool for at most 16 sets
[INFO] Creating a descriptor pool for at most 16 sets
[INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
[INFO] Refreshing at 16666 micros
[INFO] Using GPU: GPUSpecs { is_software_emulated: true, device_name: "llvmpipe (LLVM 17.0.6, 256 bits)", driver_name: "llvmpipe", driver_info: "Mesa 23.3.3 (LLVM 17.0.6)" }
[INFO] Using surface present mode MAILBOX
[WARN] Unable to forbid exclusive full screen
[WARN] request completed with error: failed to connect to the server
[WARN] request completed with error: failed to connect to the server
[INFO] Opening main db
[INFO] Initializing default prettier with plugins {}
[ERROR] no worktrees when constructing ProjectLspAdapterDelegate
[INFO] Node runtime install_if_needed
[WARN] request completed with error: failed to connect to the server
[INFO] keep_updated;
[INFO] Initializing default prettier with plugins {}
[WARN] request completed with error: failed to connect to the server
[INFO] Initializing default prettier with plugins {}
[INFO] starting language server. binary path: "/u01/home/BinaryNerd/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/u01/home/BinaryNerd/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
[WARN] request completed with error: failed to connect to the server
[INFO] Language server with id 0 sent unhandled notification LogMessage:
{
"level": 0,
"message": "[DEBUG] [agent] [2024-08-01T16:27:28.890Z] Agent service starting",
"metadataStr": "[DEBUG] [agent] [2024-08-01T16:27:28.890Z]",
"extra": [
"Agent service starting"
]
}
[INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
"registrations": [
{
"method": "workspace/didChangeWorkspaceFolders",
"registerOptions": {}
}
]
}
[INFO] Language server with id 0 sent unhandled notification LogMessage:
{
"level": 0,
"message": "[DEBUG] [agent] [2024-08-01T16:27:28.914Z] Telemetry initialized",
"metadataStr": "[DEBUG] [agent] [2024-08-01T16:27:28.914Z]",
"extra": [
"Telemetry initialized"
]
}
[ERROR] DBus error Prompt was dismissed

**Comment by notpeter** [comment]
@BinaryNerd01 What is the underlying GPU in your system?
Your logs says Zed is using the llvmpipe software renderer.

**Comment by DevLord261** [comment]
Hello @notpeter @BinaryNerd01 

So  the issue was is that the GPU is old  i have GT740m which does not support `VK_KHR_dynamic_rendering` which a vulkan driver rendering comes in 1.2.6xx  unfortunatly my gpu support like 1.2.625 which is before the version that released the feature in it thats why my zed window not visible at all u can check if u got the same issue try use intel gpu if it works then i think ur gpu is old otherwise u have different issue

@JosephTLyons  IDK if my case solvable or just thats the way zed created maybe its better if u have a reqiurments page for the app where u publish dependencies and other stuff like being gpu old wont work

**Comment by notpeter** [comment]
Yeah, the 740M is pretty old (Launched April 2013) and unlikely to be supported, hopefully your intel gpu functions even if slow.  We ran into similar issues on Apple hardware with similarly aged GPUs:

- https://github.com/zed-industries/zed/issues/6853

Requirements are a bit hard to define ahead of time, for example the 650M/650M officially support Apple Metal2 (which is our minimum requirement) but it has a buggy implementation and thus unsupported in practice.

**Comment by DevLord261** [comment]
Yep i see that idk if its slow or not on my intel its working fine but i am not using zed idk what kind of development it support yet its look to me still a text editor and a beta stage to be a an alternative IDE to vscode or anyother

**Comment by DevLord261** [comment]
@notpeter BTW i wanna ask how to enable intellisence for my projects like typescript and javascrpt for react can u assist?

**Comment by notpeter** [comment]
> @notpeter BTW i wanna ask how to enable intellisence for my projects like typescript and javascrpt for react can u assist?
> 

Please see Zed docs: https://zed.dev/docs.

**Comment by ryukinix** [comment]
Just sharing this comment for potential people searching for an explanation: this also affects users with Linux and GTX 760.

**Comment by Mte90** [comment]
I have the same issue on Debian Sid with Wayland.

vulkan-dev is installed and I am using the proprietary nvidia drivers.
On shell it is printing nothing, I have tried to compile it but I had some issues with clang and lost the interest.
