### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by RegonGaming** [zed-industries/zed#14312]
### Check for existing issues

- [X] Completed

### Describe the feature

The name says it all. I want my touchscreen to work on zed.

**Comment by RegonGaming** [comment]
i just noticed there's a bug report for this but it doesn't have much talk around it so i don't think touchscreen support exists yet.

**Comment by someone13574** [comment]
What platform are you on? Windows, Linux/X11, Linux/Wayland, other?

**Comment by RegonGaming** [comment]
Arch Linux with KDE and Wayland
(im using thinkpad x390 if that matters)

**Comment by Moshyfawn** [comment]
This seems to have been suggested already, so I'll close this thread in favour of the other one. Be sure to +👍 and discuss this feature in the other thread instead.

Duplicate of:
- #13698
