### ISSUE TITLE
support treesitter incremental_selection 

### ISSUE THREAD

**Issue by reaink** [zed-industries/zed#14317]
### Check for existing issues

- [X] Completed

### Describe the feature

add treesitter incremental_selection command

https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#incremental-selection

**Comment by JosephTLyons** [comment]
Hey @reaink, we currently have `editor: select larger syntax node` (`ctrl-shift-right`) and `editor: select smaller syntax node` (`ctrl-shift-left`):

https://github.com/user-attachments/assets/cba1ead6-c86c-49a9-a76a-d46b8ecd9a3d

I'm not too familiar with `incremental_selection`, does this cover your needs?

**Comment by JosephTLyons** [comment]
I'm going to close this issue out. If the aforementioned commands don't satisfy what you are looking for, feel free to open a new issue.
