### ISSUE TITLE
linux: can't open/interact with file manager

### ISSUE THREAD

**Issue by ryuukk** [zed-industries/zed#14328]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- can't drag&drop file
- can't open folder
- can't open file
- can't 'reveal in file manager'

This happened since i removed zed from default application list, since whenever i'd open a folder in other programs, it'd open zed instead

Someone fucked up

I suspect this is what this user experienced: 
- https://github.com/zed-industries/zed/issues/13753

I can solve it if i install: ``xdg-desktop-portal-gtk`` but i should not have to, i use a different one

### Environment

Linux x64
x11
xfce4
zed 0.143.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/f55d1018-a0c2-41e7-968f-e02576fcb51f)

### If applicable, attach your Zed.log file to this issue.

```
2024-07-12T15:32:09+02:00 [ERROR] Zbus(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.UnknownMethod"), Some("No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(":1.41"), reply-serial: 66, body: Signature("s"), fds: [] }))
```

**Comment by culebron** [comment]
Ubuntu 23.10 Mate DE 1.26.2, can't reveal in file manager. "Open file" dialog shows in background, I have to alt-tab to it. (reported in #14301)

**Comment by notpeter** [comment]
Fixed by https://github.com/zed-industries/zed/pull/14401
