### ISSUE TITLE
vim comments to accepts {count} and {motion} params

### ISSUE THREAD

**Issue by ovidius72** [zed-industries/zed#14337]
### Describe the feature

Enable vim comments to accepts  {count} and {motion} params as following:

- Be able to do, as an example, `gc2j` for commenting out the current and next line, or gcgg, gcG, gcb (block), gcp (paragraph) and so on..

Thanks :-)

**Comment by notpeter** [comment]
Could please split each of these into individual issues so they can triage/discussed appropriately? There's an existing issue for number 2 already: 
- #10004

**Comment by ovidius72** [comment]
Thanks @notpeter. I've created the following issues and edited the current one.


code actions: https://github.com/zed-industries/zed/issues/14470

panel resize: https://github.com/zed-industries/zed/issues/14471

terminal shortcut: https://github.com/zed-industries/zed/issues/14472

**Comment by ConradIrwin** [comment]
:+1: Definitely. If you want to pair on this, I have some time: https://calendly.com/conradirwin/pairing

**Comment by JosephTLyons** [comment]
This should be included in Zed [v0.146.0-pre](https://zed.dev/releases/preview/0.146.0).
