### ISSUE TITLE
Very slow startup with integrated graphics enabled on PopOS

### ISSUE THREAD

**Issue by Stefano299** [zed-industries/zed#14341]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I got PopOS on a laptop with integrated AMD gpu and a nVidia 3050 dedicated gpu. If I turn off the nVidia graphics card (you can do it on PopOS), zed is very slow on opening (it needs about 20 seconds to open up). If, in my PopOS settings, I enable hybrid graphics (I enable the nVidia dedicated graphics card), the problem is solved. 

### Environment

The command doesn't work on my Linux machine. Anyway I got PopOS 22.04, 16 gb RAM, AMD ryzen 7 6800 HS (with integrated graphics) and a nVidia 3050 3gb VRAM graphics card.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I got the strace log file: 
[zed_strace.log](https://github.com/user-attachments/files/16196072/zed_strace.log)

**Comment by JosephTLyons** [comment]
I *think* this is the same issue as:

- https://github.com/zed-industries/zed/issues/14222

I'm going to optimistically close this in favor of the aforementioned issue, but let me know if I'm wrong and I will reopen.

**Comment by HarshNarayanJha** [comment]
@JosephTLyons, actually in my case (that issue #14222) the GPU is AMD integrated, so I _think_ it is different. Though if this is not a GPU dependent issue it may be the same!

**Comment by Stefano299** [comment]
Yes, this is why I opened a new issue

**Comment by pixiedevpraveen** [comment]
I'm using zed in Popos with integrated graphics and it's working fine. No lag, Fast boot time 👍🏻.
but if I switch to nvidia it start fast but lags like the watching a video on slow motion. any key I press it takes 1-2 seconds to do action.

specs:
Pop os 22.04 LTS
Intel® Core™ i3-7020U CPU @ 2.30GHz × 4 
RAM: 8gb
Storage: Samsung 980 ssd 500gb
graphics:
 - Mesa Intel® HD Graphics 620 (KBL GT2)
 - Nvidia mx110 DDR5 (driver: 470)
