### ISSUE TITLE
Install extension dev via link

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#14342]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="163" alt="Screenshot 2024-07-12 alle 17 22 40" src="https://github.com/user-attachments/assets/87efa770-9463-46c8-85c9-c2b700b4cb1e">

It would be nice to be able to install a dev extension via link, without having to download the project.

**Comment by JosephTLyons** [comment]
Related

- https://github.com/zed-industries/zed/issues/10794

**Comment by notpeter** [comment]
Dev extensions have no been reviewed and can easily spawn malicious processes. The current friction serves a purpose. Pasting a link to run arbitrary unreviewed code is an anti-feature. 

Thanks for filing, but we have no plans to implement this at this time.
