### ISSUE TITLE
Inline git blame setting resets on every file change

### ISSUE THREAD

**Issue by secondl1ght** [zed-industries/zed#14354]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I want to disable Inline Git Blame, so I click to turn it off in the Editor Controls toggle menu. It works but then as soon as I change files it gets enabled right away again. How do I turn it off permanently?

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland zorin 17
Memory: 31.2 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/82086c67-478f-47b8-ab03-96b8c9490e71)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Yeah, so far `editor` menus are saving state for the currently opened buffer.
To make it go away entirely, adjust your settings.json (`zed: open settings` command) with
```json
"git": {
    "inline_blame": {
      "enabled": false
    }
}
```

There's also `zed: open default settings` with every setting possible + some comments in that file.

**Comment by secondl1ght** [comment]
Ah, great thanks!
