### ISSUE TITLE
[File explorer] [Linux] Can't open thunar in hyprland 

### ISSUE THREAD

**Issue by AirbnbEcoPlus** [zed-industries/zed#14353]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I can't open the file explorer, i have thunar and hyprland, i have to install a precise file explorer ?

### Environment

Archlinux, Hyprland, AMD 7840u, Thunar.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

When i click open folder is not work 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by EyKo-dev** [comment]
Got the same issue here with Thunar on XFCE4.

**Comment by apricotbucket28** [comment]
You're probably missing a desktop portal implementation, see https://zed.dev/docs/linux#clicking-links-isnt-working.

See also https://wiki.archlinux.org/title/XDG_Desktop_Portal#Configuration for help configuring it.

**Comment by AirbnbEcoPlus** [comment]
Thanks a lot ! fixed after installing xdg-desktop-portal-hyprland and xdg-desktop-portal-gtk

**Comment by 0x6e7a6f** [comment]
> You're probably missing a desktop portal implementation, see https://zed.dev/docs/linux#clicking-links-isnt-working.
> 
> See also https://wiki.archlinux.org/title/XDG_Desktop_Portal#Configuration for help configuring it.

As for me, _xdg-desktop-portal_ was already present on my XFCE4 so I installed _xdg-desktop-portal-gtk_ and that fixed the problem. Thank you so much !
