### ISSUE TITLE
ctrl-j keybinding is repeated on Linux

### ISSUE THREAD

**Issue by sant123** [zed-industries/zed#14366]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open "Default Key Bindings"
- Search for "ctrl-j"

You will see it is repeated:

![image](https://github.com/user-attachments/assets/db9d15b4-1d05-4cc9-9d6c-f1ba3be62754)
![image](https://github.com/user-attachments/assets/3fe2fb4c-2fdd-4608-a356-535d83eedb73)

This makes pressing the keybinding to vary.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland fedora 40
Memory: 15.5 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
Thanks for reporting @sant123. This is fixed in v0.144.x available now in Zed Preview and in the next Zed Stable (out 2024-07-17).

- https://github.com/zed-industries/zed/pull/14136
