### ISSUE TITLE
Authentication Error: Browser Does Not Open Upon Login Attempt

### ISSUE THREAD

**Issue by c0utin** [zed-industries/zed#14375]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When attempting to log in, I encounter an error message stating "didn't receive login redirect." Despite following all recommended troubleshooting steps, my browser does not open to complete the authentication process.

### Environment

<details><summary>system environment</summary>
<pre>
System:
  Kernel: 6.9.9-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 14.1.1
  Desktop: i3 v: 4.23 Distro: Arch Linux
Machine:
  Type: Laptop System: Dell product: Latitude 3420 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 04G4X5 v: A00 serial: <superuser required> UEFI: Dell
    v: 1.32.1 date: 10/04/2023
Battery:
  ID-1: BAT0 charge: 8.9 Wh (29.8%) condition: 29.9/40.8 Wh (73.3%)
    volts: 11.0 min: 11.2 model: BYD DELL PG8YJ28 status: discharging
CPU:
  Info: quad core model: 11th Gen Intel Core i5-1135G7 bits: 64 type: MT MCP
    arch: Tiger Lake rev: 1 cache: L1: 320 KiB L2: 5 MiB L3: 8 MiB
  Speed (MHz): avg: 670 high: 1086 min/max: 400/4200 cores: 1: 980 2: 874
    3: 1086 4: 400 5: 400 6: 400 7: 400 8: 821 bogomips: 22120
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] vendor: Dell
    driver: i915 v: kernel arch: Gen-12.1 bus-ID: 0000:00:02.0
  Device-2: C7FLH18S195440316850 Integrated_Webcam_HD driver: uvcvideo
    type: USB bus-ID: 3-6:3
  Display: x11 server: X.org v: 1.21.1.13 driver: X: loaded: modesetting
    dri: iris gpu: i915 resolution: 1920x1080~60Hz
  API: Vulkan v: 1.3.279 drivers: intel surfaces: xcb,xlib devices: 1
  API: OpenGL Message: Unable to show GL data. glxinfo is missing.
Audio:
  Device-1: Intel Tiger Lake-LP Smart Sound Audio vendor: Dell
    driver: sof-audio-pci-intel-tgl bus-ID: 0000:00:1f.3
  API: ALSA v: k6.9.9-arch1-1 status: kernel-api
  Server-1: PipeWire v: 1.2.1 status: active
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi v: kernel bus-ID: 0000:00:14.3
  IF: wlan0 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: Dell driver: r8169 v: kernel port: 3000 bus-ID: 0000:2b:00.0
  IF: enp43s0 state: down mac: <filter>
  IF-ID-1: br-4d28019c70ec state: down mac: <filter>
  IF-ID-2: br-540dbb4457af state: down mac: <filter>
  IF-ID-3: docker0 state: down mac: <filter>
Bluetooth:
  Device-1: N/A driver: btusb v: 0.8 type: USB bus-ID: 3-10:4
  Report: btmgmt ID: hci0 rfk-id: 0 state: down bt-service: disabled
    rfk-block: hardware: no software: no address: N/A
RAID:
  Hardware-1: Intel Volume Management Device NVMe RAID Controller driver: vmd
    v: 0.6 bus-ID: 0000:00:0e.0
Drives:
  Local Storage: total: 238.47 GiB used: 85.71 GiB (35.9%)
  ID-1: /dev/nvme0n1 vendor: A-Data model: SM2P41C3 NVMe 256GB
    size: 238.47 GiB temp: 34.9 C
Partition:
  ID-1: / size: 237.97 GiB used: 85.63 GiB (36.0%) fs: btrfs
    dev: /dev/nvme0n1p2
  ID-2: /boot size: 511 MiB used: 79.9 MiB (15.6%) fs: vfat
    dev: /dev/nvme0n1p1
  ID-3: /home size: 237.97 GiB used: 85.63 GiB (36.0%) fs: btrfs
    dev: /dev/nvme0n1p2
  ID-4: /var/log size: 237.97 GiB used: 85.63 GiB (36.0%) fs: btrfs
    dev: /dev/nvme0n1p2
Swap:
  ID-1: swap-1 type: zram size: 4 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 48.0 C mobo: 47.0 C
  Fan Speeds (rpm): cpu: 0
Info:
  Memory: total: 16 GiB note: est. available: 15.37 GiB used: 4.35 GiB (28.3%)
  Processes: 267 Uptime: 29m Init: systemd
  Packages: 785 Compilers: clang: 18.1.8 gcc: 14.1.1 Shell: Zsh v: 5.9
    inxi: 3.3.35
</pre></details>

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![2024-07-12_20-09](https://github.com/user-attachments/assets/ab11cdbf-3831-44db-996d-4eb54b2e663b)
![2024-07-12_20-08](https://github.com/user-attachments/assets/ee3a74eb-2a78-4847-b001-90913206eeaa)

### If applicable, attach your Zed.log file to this issue.

[2024-07-12T21:12:37-03:00 ERROR gpui] Zbus(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 39, body: Signature("s"), fds: [] }))
[2024-07-12T21:14:17-03:00 ERROR workspace::notifications] didn't receive login redirect

**Comment by Hcode00** [comment]
I'm also on Arch and seeing a similar issue when i use Hyprland. with the same error message you mentioned 
Interestingly, everything works fine when I switch to KDE Plasma.
