### ISSUE TITLE
Disable Zed autocomplete suggestions in comments

### ISSUE THREAD

**Issue by soham-suki** [zed-industries/zed#14372]
### Check for existing issues

- [X] Completed

### Describe the feature

When writing comments, I often use periods to end sentences (and hit enter to go to the next line)
However, Zed suggests completions when I hit periods in comments.
Then when I hit enter, it thinks I wanted to use its suggestions, so it adds that after the period. To prevent this, I have to constantly hit Esc to dismiss suggestions.

Is there a way to disable suggestions inside of comments?

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/171621461/5dabbb3c-7637-41c7-99df-1acc62bf8df9)
As you can see above, typing `.` in the comment triggered the hover popup with `logAndSendError` as a suggestion. However, this was an unnecessary suggestion - `.` should only trigger suggestion when I'm writing code, not comments. Besides, why was `logAndSendError` suggested for `out.`?

**Comment by soham-suki** [comment]
Bump!

**Comment by soham-suki** [comment]
Why was the `ai` label added to this? I'm unsure if this concerns the ai part of Zed at all.

**Comment by mbylstra** [comment]
I also find the completion very distracting in the AI composer chat window. I think there should be an option to be able to enable AI auto completion only in code (not in comments, nor any other scenario that isn't source code)

**Comment by notpeter** [comment]
Zed should likely support a way to disable inline suggestions (Copilot/SuperMaven) when using the Assistant Panel, but there is not currently a setting for this.

A workaround (that I use) is to add the following to your settings:
```
  "languages":
    "Markdown": {
      "show_inline_completions": false
    }
  }
```

This will disable inline completions when editing Markdown files and when using the Assistant Panel (which is a Language==Markdown buffer under the hood).

**Comment by mrnugget** [comment]
Okay, actionable thing seems to be that we look at trigger characters in Go code and that we check whether it's us or `gopls` triggering this. If it's us, we need to fix it.

**Comment by mrnugget** [comment]
I can't reproduce the issue with completion after periods.

Yes, `gopls` completes in comments, but only the name of the exported symbol. Like this:

![screenshot-2024-11-06-15 52 13@2x](https://github.com/user-attachments/assets/b2ba8dfe-1717-4816-b801-cf05f95bff46)

But it doesn't complete here `anotherFunction`:

![screenshot-2024-11-06-15 52 37@2x](https://github.com/user-attachments/assets/0b2240de-d221-4eb2-9c25-c5f691a0b8b6)

And the complete-exported-symbol functionality is a feature: https://go-review.googlesource.com/c/tools/+/230215

So it looks like this is working as intended, since I can't reproduce the original bug.

**Comment by soham-suki** [comment]
I think some update of Zed must have fixed this issue, as I can't seem to run into this again either. Thanks for looking into it!

**Comment by iafisher** [comment]
I still get autocompletion suggestions when writing comments in JavaScript. Is there any way to disable this? It's especially annoying when I end a line with ':' as the autocomplete will be triggered and 'Enter' will accept instead of going to the next line.

**Comment by soham-suki** [comment]
Yeah, I've been seeing this behavior happen again as well. Can we please reopen this issue @notpeter?

<img width="801" height="135" alt="Image" src="https://github.com/user-attachments/assets/10514223-e781-4a86-aa01-9fa2983df002" />

**Comment by kaem-e** [comment]
has this too with supermaven

**Comment by notpeter** [comment]
@soham-suki and @kaem-e This issue was about LSP autocomplete in comments, you are both complaining about LLM inline completion (Zeta, Supermaven, Copilot).

You should be able to disable the behavior you are seeing with:
```json
{
  "languages": {
    "Go": {
      "edit_predictions_disabled_in": ["comment"]
    }
  }
}
```

Which was implemented in: 
- https://github.com/zed-industries/zed/pull/20508

But...it appears to be broken. Please upvote / subscribe to this issue:

- https://github.com/zed-industries/zed/issues/25744

**Comment by soham-suki** [comment]
@notpeter I'm fairly confident I'm complaining about LSP autocomplete in method docs, and not LLM inline completion - if you see my screenshot in the post before @kaem-e, edit prediction says "No Prediction" and LSP autocompletes sugar by suggesting `Sugar *zap.SugarredLogger`. I just want to type the word sugar, I don't want to reference the variable `Sugar` in method docs. In a large file, LSP suggests tons of autocompletes in method docs, which makes typing difficult since you have to hit <Esc> very frequently.

**Comment by crabmusket** [comment]
I'm having this issue too in JS/TS. It's very annoying as common words at the end of a line like `at` or `not`, when I want to hit Enter to start a new line, end up completing to random symbols defined in a file/function:

<img width="807" height="196" alt="Image" src="https://github.com/user-attachments/assets/bfff6e0a-1277-4221-b0da-4f19aad94e6e" />

I do not have any AI features enabled, this is just LSP completion.

**Comment by soham-suki** [comment]
@notpeter could we reopen this issue?

**Comment by notpeter** [comment]
I'd prefer a clean issue with just sufficient info to trigger the behavior. Could you open one please?

Sounds like there is a regression here for certain languages (JS/TS, Golang, perhaps others) where autocompelete is being triggered.  Looking at the most recent image from @crabmusket I'm wondering if this is actually word completions, not lsp completions.

Does this fix it:
```
  "completions": {
    "words": "disabled"
  }
```

Thanks.

**Comment by mstarodub** [comment]
> Does this fix it:
> 
> ```
>   "completions": {
>     "words": "disabled"
>   }
> ```
> 
> Thanks.

It does not. Using ruff and ty:

```
{
  "edit_predictions_disabled_in": [
    "comment",
    "string"
  ],
  "completions": {
    "words": "disabled"
  },
  "languages": {
    "Python": {
      "language_servers": [
        "ruff",
        "ty"
      ]
    },
}
```

I'm still seeing code completion in a comment.

**Comment by crabmusket** [comment]
This settings change _does_ work for me in TypeScript files:

```
  "completions": {
    "words": "disabled"
  }
```

I have yet to see if there are any other undesirable effects.

Looking at the [docs](https://zed.dev/docs/configuring-zed#words), I note this-

> fallback - Only if LSP response errors or times out, use document's words to show completions

I was likely running into fallback behaviour often, as I find the LSP quite slow in my project (nothing to do with Zed). So what I expect is that in files where the LSP struggles, I'll see fewer autocomplete suggestions even outside comments, where previously fallback behaviour was kicking in.

I'll have to see if this tradeoff is worth it to make comments less annoying to write!

**Comment by marcoms** [comment]
> ```
>   "completions": {
>     "words": "disabled"
>   }
> ```

Unfortunately for other languages suggestions are still displayed in comments from the LSP. Here is a CSS example:

https://github.com/user-attachments/assets/14b48290-6ca8-4566-96be-9443e1d09108

It would be great to have completions completely disabled when inside a comment
