### ISSUE TITLE
Open a project in Wayland is not working

### ISSUE THREAD

**Issue by bknightInfo** [zed-industries/zed#14384]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi,

I am trying zed to see if it can replace Vs Code and Neovim but cannot get folder picker to open but I am assuming its a dbus error in wayland but perhaps people will know.

### Environment

Zed: v0.144.2 (Zed)
Kernal: Linux 6.9.7-arch1-1
OS: Arch Linux x86_64
WM: Hyprland (Wayland)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16201171/Zed.log)

</pre></details>

**Comment by notpeter** [comment]
Fixed by https://github.com/zed-industries/zed/pull/14401
