### ISSUE TITLE
Visual Glitches on Archlinux KDE Wayland intel hd graphics 505

### ISSUE THREAD

**Issue by kennyfully88** [zed-industries/zed#14380]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open the editor and try to do anything, it is very buggy and glitchy. I'm using Archlinux KDE Wayland.

Video Proof

https://github.com/user-attachments/assets/b8fa60b6-65eb-4639-b8a4-0185105f3a6c

### Environment

<details><summary>environment details</summary>
<pre>
description: Notebook
    product: HP Pavilion x360 Convertible 11m-ad0xx (1KT77UA#ABA)
    vendor: HP
    version: Type1ProductConfigId
    serial: 8CG7362WHM
    width: 64 bits
    capabilities: smbios-3.0.0 dmi-3.0.0 smp vsyscall32
    configuration: boot=normal chassis=notebook family=103C_5335KV HP Pavilion sku=1KT77UA#ABA uuid=76f005cc-93c5-11e7-930f-3065ec65ddbb
  *-core
       description: Motherboard
       product: 830D
       vendor: HP
       physical id: 0
       version: 30.21
       serial: PGNAT1B0G930PX
       slot: Type2 - Board Chassis Location
     *-firmware
          description: BIOS
          vendor: Insyde
          physical id: 0
          version: F.09
          date: 07/21/2017
          size: 64KiB
          capacity: 3MiB
          capabilities: pci upgrade shadowing cdboot bootselect edd int9keyboard int14serial int17printer int10video acpi usb zipboot biosbootspecification netboot
     *-cpu
          description: CPU
          product: Intel(R) Pentium(R) CPU N4200 @ 1.10GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: 6.92.9
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 800MHz
          capacity: 2500MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts vnmi md_clear arch_capabilities cpufreq
          configuration: cores=4 enabledcores=4 microcode=72 threads=4
        *-cache:0
             description: L1 cache
             physical id: 6
             slot: L1 Cache
             size: 32KiB
             capacity: 32KiB
             capabilities: synchronous internal write-back instruction
             configuration: level=1
        *-cache:1
             description: L2 cache
             physical id: 7
             slot: L2 Cache
             size: 1MiB
             capacity: 1MiB
             capabilities: synchronous internal write-back unified
             configuration: level=2
     *-cache
          description: L1 cache
          physical id: 5
          slot: L1 Cache
          size: 24KiB
          capacity: 24KiB
          capabilities: synchronous internal write-back data
          configuration: level=1
     *-memory
          description: System Memory
          physical id: 25
          slot: System board or motherboard
          size: 4GiB
        *-bank
             description: SODIMM DDR3 Synchronous 1600 MHz (0.6 ns)
             product: HP16D3LS1KBGH/4G
             vendor: Kingston
             physical id: 0
             serial: 19442019
             slot: Bottom
             size: 4GiB
             width: 8 bits
             clock: 1600MHz (0.6ns)
     *-pci
          description: Host bridge
          product: Celeron N3350/Pentium N4200/Atom E3900 Series Host Bridge
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 0b
          width: 32 bits
          clock: 33MHz
        *-generic:0
             description: Signal processing controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 0.1
             bus info: pci@0000:00:00.1
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=proc_thermal latency=0
             resources: irq:24 memory:91210000-91217fff
        *-display
             description: VGA compatible controller
             product: Apollo Lake [HD Graphics 505]
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             logical name: /dev/fb0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
             configuration: depth=32 driver=i915 latency=0 resolution=1366,768
             resources: irq:128 memory:90000000-90ffffff memory:80000000-8fffffff ioport:1000(size=64) memory:c0000-dffff
        *-multimedia
             description: Audio device
             product: Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
             vendor: Intel Corporation
             physical id: e
             bus info: pci@0000:00:0e.0
             logical name: card0
             logical name: /dev/snd/controlC0
             logical name: /dev/snd/hwC0D0
             logical name: /dev/snd/hwC0D2
             logical name: /dev/snd/pcmC0D0c
             logical name: /dev/snd/pcmC0D0p
             logical name: /dev/snd/pcmC0D3p
             logical name: /dev/snd/pcmC0D7p
             logical name: /dev/snd/pcmC0D8p
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi pciexpress bus_master cap_list
             configuration: driver=snd_hda_intel latency=0
             resources: irq:133 memory:91218000-9121bfff memory:91000000-910fffff
           *-input:0
                product: HDA Intel PCH Mic
                physical id: 0
                logical name: input21
                logical name: /dev/input/event13
           *-input:1
                product: HDA Intel PCH Headphone
                physical id: 1
                logical name: input22
                logical name: /dev/input/event14
           *-input:2
                product: HDA Intel PCH HDMI/DP,pcm=3
                physical id: 2
                logical name: input23
                logical name: /dev/input/event15
           *-input:3
                product: HDA Intel PCH HDMI/DP,pcm=7
                physical id: 3
                logical name: input24
                logical name: /dev/input/event16
           *-input:4
                product: HDA Intel PCH HDMI/DP,pcm=8
                physical id: 4
                logical name: input25
                logical name: /dev/input/event17
        *-communication
             description: Communication controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series Trusted Execution Engine
             vendor: Intel Corporation
             physical id: f
             bus info: pci@0000:00:0f.0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: irq:131 memory:91220000-91220fff
        *-generic:1
             description: Unclassified device
             product: Celeron N3350/Pentium N4200/Atom E3900 Series Integrated Sensor Hub
             vendor: Intel Corporation
             physical id: 11
             bus info: pci@0000:00:11.0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel_ish_ipc latency=0
             resources: irq:26 memory:9121c000-9121dfff memory:91223000-91223fff
        *-sata
             description: SATA controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SATA AHCI Controller
             vendor: Intel Corporation
             physical id: 12
             bus info: pci@0000:00:12.0
             version: 0b
             width: 32 bits
             clock: 66MHz
             capabilities: sata msi pm ahci_1.0 bus_master cap_list
             configuration: driver=ahci latency=0
             resources: irq:126 memory:9121e000-9121ffff memory:91234000-912340ff ioport:1080(size=8) ioport:1088(size=4) ioport:1060(size=32) memory:91232000-912327ff
        *-pci:0
             description: PCI bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port A #1
             vendor: Intel Corporation
             physical id: 13
             bus info: pci@0000:00:13.0
             version: fb
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:120 ioport:2000(size=4096) memory:91300000-914fffff ioport:91500000(size=2097152)
        *-pci:1
             description: PCI bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port A #2
             vendor: Intel Corporation
             physical id: 13.1
             bus info: pci@0000:00:13.1
             version: fb
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:121 memory:91100000-911fffff
           *-network
                description: Wireless interface
                product: Dual Band Wireless-AC 3168NGW [Stone Peak]
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:02:00.0
                logical name: wlan0
                version: 10
                serial: f4:96:34:7c:31:e3
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=iwlwifi driverversion=6.9.8-arch1-1 firmware=29.198743027.0 3168-29.ucode ip=192.168.1.188 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                resources: irq:132 memory:91100000-91101fff
        *-pci:2
             description: PCI bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port A #3
             vendor: Intel Corporation
             physical id: 13.2
             bus info: pci@0000:00:13.2
             version: fb
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:122 ioport:3000(size=4096) memory:91700000-918fffff ioport:91900000(size=2097152)
        *-pci:3
             description: PCI bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port A #4
             vendor: Intel Corporation
             physical id: 13.3
             bus info: pci@0000:00:13.3
             version: fb
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:123 ioport:4000(size=4096) memory:91b00000-91cfffff ioport:91d00000(size=2097152)
        *-pci:4
             description: PCI bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port B #1
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: fb
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:124 ioport:5000(size=4096) memory:91f00000-920fffff ioport:92100000(size=2097152)
        *-pci:5
             description: PCI bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port B #2
             vendor: Intel Corporation
             physical id: 14.1
             bus info: pci@0000:00:14.1
             version: fb
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:125
        *-usb
             description: USB controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series USB xHCI
             vendor: Intel Corporation
             physical id: 15
             bus info: pci@0000:00:15.0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:127 memory:91200000-9120ffff
           *-usbhost:0
                product: xHCI Host Controller
                vendor: Linux 6.9.8-arch1-1 xhci-hcd
                physical id: 0
                bus info: usb@1
                logical name: usb1
                version: 6.09
                capabilities: usb-2.00
                configuration: driver=hub slots=8 speed=480Mbit/s
              *-usb:0 UNCLAIMED
                   description: Generic USB device
                   product: Unisoc Phone
                   vendor: Unisoc
                   physical id: 1
                   bus info: usb@1:1
                   version: 4.04
                   serial: 5120018022093588
                   capabilities: usb-2.00
                   configuration: maxpower=500mA speed=480Mbit/s
              *-usb:1
                   description: Video
                   product: HP Wide Vision HD Camera
                   vendor: Chicony
                   physical id: 4
                   bus info: usb@1:4
                   version: 32.22
                   capabilities: usb-2.00
                   configuration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
              *-usb:2
                   description: Bluetooth wireless interface
                   product: Wireless-AC 3168 Bluetooth
                   vendor: Intel Corp.
                   physical id: 6
                   bus info: usb@1:6
                   version: 0.01
                   capabilities: bluetooth usb-2.00
                   configuration: driver=btusb maxpower=100mA speed=12Mbit/s
           *-usbhost:1
                product: xHCI Host Controller
                vendor: Linux 6.9.8-arch1-1 xhci-hcd
                physical id: 1
                bus info: usb@2
                logical name: usb2
                version: 6.09
                capabilities: usb-3.00
                configuration: driver=hub slots=7 speed=5000Mbit/s
        *-generic:2
             description: Signal processing controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #1
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:27 memory:91224000-91224fff memory:91225000-91225fff
        *-generic:3
             description: Signal processing controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #4
             vendor: Intel Corporation
             physical id: 16.3
             bus info: pci@0000:00:16.3
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:30 memory:91226000-91226fff memory:91227000-91227fff
        *-generic:4
             description: Signal processing controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SPI Controller #1
             vendor: Intel Corporation
             physical id: 19
             bus info: pci@0000:00:19.0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:35 memory:91228000-91228fff memory:91229000-91229fff
        *-generic:5
             description: Signal processing controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SPI Controller #2
             vendor: Intel Corporation
             physical id: 19.1
             bus info: pci@0000:00:19.1
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:36 memory:9122a000-9122afff memory:9122b000-9122bfff
        *-generic:6
             description: Signal processing controller
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SPI Controller #3
             vendor: Intel Corporation
             physical id: 19.2
             bus info: pci@0000:00:19.2
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:37 memory:9122c000-9122cfff memory:9122d000-9122dfff
        *-generic:7
             description: MMC Host
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SDXC/MMC Host Controller
             vendor: Intel Corporation
             physical id: 1b
             bus info: pci@0000:00:1b.0
             logical name: mmc1
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=sdhci-pci latency=0
             resources: irq:3 memory:9122e000-9122efff memory:9122f000-9122ffff
        *-generic:8
             description: MMC Host
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SDIO Controller
             vendor: Intel Corporation
             physical id: 1e
             bus info: pci@0000:00:1e.0
             logical name: mmc0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=sdhci-pci latency=0
             resources: irq:42 memory:91230000-91230fff memory:91231000-91231fff
        *-isa
             description: ISA bridge
             product: Celeron N3350/Pentium N4200/Atom E3900 Series Low Pin Count Interface
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 0b
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master
             configuration: driver=lpc_ich latency=0
             resources: irq:0
           *-pnp00:00
                product: Motherboard registers
                physical id: 0
                capabilities: pnp
                configuration: driver=system
           *-pnp00:01
                product: PnP device HPQ8001
                vendor: Hewlett-Packard Co.
                physical id: 1
                capabilities: pnp
                configuration: driver=i8042 kbd
           *-pnp00:02
                product: PnP device ETD0719
                vendor: ELAN MICROELECTRONICS CORPORATION
                physical id: 2
                capabilities: pnp
                configuration: driver=i8042 aux
           *-pnp00:03
                product: Motherboard registers
                physical id: 3
                capabilities: pnp
                configuration: driver=system
           *-pnp00:04
                product: AT Real-Time Clock
                physical id: 4
                capabilities: pnp
                configuration: driver=rtc_cmos
           *-input
                product: Intel Virtual Buttons
                physical id: 5
                logical name: input6
                logical name: /dev/input/event5
                capabilities: platform
        *-serial
             description: SMBus
             product: Celeron N3350/Pentium N4200/Atom E3900 Series SMBus Controller
             vendor: Intel Corporation
             physical id: 1f.1
             bus info: pci@0000:00:1f.1
             version: 0b
             width: 64 bits
             clock: 33MHz
             configuration: driver=i801_smbus latency=0
             resources: irq:20 memory:91233000-912330ff ioport:1040(size=32)
  *-battery
       product: KN02037XL
       vendor: 333-54-2C
       physical id: 1
       version: ManufDate
       serial: DummySerialNumber
       slot: Primary
       capacity: 37229mWh
       configuration: voltage=7.7V
  *-power UNCLAIMED
       description: OEM Define 1
       product: OEM Define 5
       vendor: OEM Define 2
       physical id: 2
       version: OEM Define 6
       serial: OEM Define 3
       capacity: 75mWh
  *-input:0
       product: Lid Switch
       physical id: 3
       logical name: input0
       logical name: /dev/input/event0
       capabilities: platform
  *-input:1
       product: Power Button
       physical id: 4
       logical name: input1
       logical name: /dev/input/event1
       capabilities: platform
  *-input:2
       product: HP WMI hotkeys
       physical id: 5
       logical name: input10
       logical name: /dev/input/event12
       capabilities: platform
  *-input:3
       product: ELAN0732:00 04F3:2518
       physical id: 6
       logical name: input16
       logical name: /dev/input/event7
       logical name: /dev/input/mouse0
       capabilities: i2c
  *-input:4
       product: ELAN0732:00 04F3:2518 UNKNOWN
       physical id: 7
       logical name: input17
       logical name: /dev/input/event8
       capabilities: i2c
  *-input:5
       product: ELAN0732:00 04F3:2518 UNKNOWN
       physical id: 8
       logical name: input18
       logical name: /dev/input/event9
       capabilities: i2c
  *-input:6
       product: ELAN0732:00 04F3:2518 Stylus
       physical id: 9
       logical name: input19
       logical name: /dev/input/event10
       logical name: /dev/input/mouse1
       capabilities: i2c
  *-input:7
       product: AT Translated Set 2 keyboard
       physical id: a
       logical name: input2
       logical name: /dev/input/event2
       logical name: input2::capslock
       logical name: input2::numlock
       logical name: input2::scrolllock
       capabilities: i8042
  *-input:8
       product: Video Bus
       physical id: b
       logical name: input4
       logical name: /dev/input/event3
       capabilities: platform
  *-input:9
       product: Wireless hotkeys
       physical id: c
       logical name: input5
       logical name: /dev/input/event4
       capabilities: platform
  *-input:10
       product: PC Speaker
       physical id: d
       logical name: input8
       logical name: /dev/input/event6
       capabilities: isa
  *-input:11
       product: ETPS/2 Elantech Touchpad
       physical id: e
       logical name: input9
       logical name: /dev/input/event11
       logical name: /dev/input/mouse2
       capabilities: i8042

</pre>
</details>

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by apognu** [comment]
Exact same behavior on Arch Linux Wayland (hyprland).

**Comment by ActuallyFlamey** [comment]
Cannot replicate on Arch Linux with KDE Plasma on Wayland, but CAN replicate on a different device on Arch Linux with RiverWM on Wayland.

**Comment by jorbort** [comment]
having tha exact same issue on arch kde wayland device with intel arc integrated graphics

**Comment by neyb** [comment]
Also happens on gnome

**Comment by neyb** [comment]
also happens when running `WAYLAND_DISPLAY='' zeditor`

**Comment by AdjectiveAllison** [comment]
I believe this is the same issue and I just found the resolution (It's a mesa driver bug, not zed)

https://github.com/zed-industries/zed/issues/14101#issuecomment-2254601539

**Comment by notpeter** [comment]
I'm going to close this issue in favor of:

- https://github.com/zed-industries/zed/issues/14101

Please 👍 vote over there if you are having this issue.
Thank you everyone for reporting.

**Comment by hickscorp** [comment]
Same here - Fedora 40, KDE 6, Wayland.
