### ISSUE TITLE
Allow disabling non-tree sitter language servers for JS/TS

### ISSUE THREAD

**Issue by PoneyClairDeLune** [zed-industries/zed#14400]
### Check for existing issues

- [X] Completed

### Describe the feature

https://zed.dev/docs/languages/javascript

Sometimes (or should I say, lots of times) language servers will report a lot of non-existent problems for JavaScript projects, and are better left disabled for drowning out the real issues. However, some essential features like tab completion are still needed, leaving tree sitter still required.

![image](https://github.com/user-attachments/assets/cb5e24d3-ae7a-4239-8d18-4efe50f6c2f6)

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/a64ebb1e-6547-4165-890c-a462ad03c6f8)

**Comment by SomeoneToIgnore** [comment]
You can disable any language server in the settings, per language, see https://github.com/zed-industries/zed/discussions/14393#discussioncomment-10038676 for the config example.

There's no such thing as a "tree-sitter language server" to my knowledge though.

**Comment by PoneyClairDeLune** [comment]
> There's no such thing as a "tree-sitter language server" to my knowledge though.

If according to Zed docs, there is. JS language support is provided by both tree sitter and the TypeScript language server.

And that auto formatting is just annoying.

**Comment by SomeoneToIgnore** [comment]
> If according to Zed docs, there is... Not a language server though.

So there is no such thing as a "tree-sitter language server", as you've stated yourself in the message.

> And that auto formatting is just annoying.

There's a `"format_on_save": "off",` to disable the formatting entirely and other ways to disable the formatting per language.

> Disabling the language server disables tab completion altogether, and I don't want that.

Can you formulate better what you want? 
The issue title says "allow disabling language servers", now you don't seem to want it anymore.

**Comment by PoneyClairDeLune** [comment]
> There's a "format_on_save": "off", to disable the formatting entirely and other ways to disable the formatting per language.

That does not work for JS/TS. LSP will attempt to format the code as I write, messing everything up. Yet if I want tab completion, I cannot disable the LSP, and have to Ctrl+Z every time LSP attempts an auto formatting.

> The issue title says "allow disabling language servers", now you don't seem to want it anymore.

What I want is the ability to disable the language servers *only*, not along with tab completion. Like Atom, which provides tab completion without any language servers, probably with tree sitter alone.

**Comment by SomeoneToIgnore** [comment]
The latter is tracked in https://github.com/zed-industries/zed/issues/4957 , so I'll close this as a duplicate then.

The former seems odd, here's how it works for me (just fine): 
https://github.com/user-attachments/assets/64d9eeca-a3b1-4302-9db1-df19ec5fbcaf
I would suggest re-checking that the settings file is saved and has the correct syntax.

**Comment by PoneyClairDeLune** [comment]
> I would suggest re-checking that the settings file is saved and has the correct syntax.

Everything is saved. Here's a screen recording of the TS LSP formatting the code as I write.

https://github.com/user-attachments/assets/8dc0dfac-e3b3-4609-aaa3-deae9c9422ea

**Comment by SomeoneToIgnore** [comment]
I don't have any good ideas yet, some guesses:

* that `Snowflake Opaque` theme is underscored as a warning — maybe it causes Zed to think the config is invalid and misapply that.  Most probably I'm wrong as other things work?
* the `format_on_save` on the upper level is ignored due to more specific language configuration? That seems odd and I'd consider that as a bug, expecting the config values to be merged.

Please share your config if you can, or start with 
```json
{"format_on_save": "off"}
```
only and gradually fill it with the rest of the config to see the offending settings combination.

**Comment by PoneyClairDeLune** [comment]
```json
{
	"outline_panel": {
		"dock": "right"
	},
	"base_keymap": "Atom",
	"ui_font_size": 14,
	"buffer_font_size": 14,
	"theme": {
		"mode": "system",
		"light": "One Light",
		"dark": "Snowflake Opaque"
	},
	"hard_tabs": true,
	"tab_size": 4,
	"show_whitespaces": "boundary",
	"soft_wrap": "editor_width",
	"buffer_font_family": "DejaVu Sans Mono",
	"format_on_save": "off",
	"languages": {
		"JavaScript": {
			"enable_language_server": false
		}
	}
}
```

**Comment by SomeoneToIgnore** [comment]
That config works just fine for me.

Modified it a bit based on the feedback, now there's a language server and no formatting:

```jsonc
{
	"outline_panel": {
		"dock": "right"
	},
	"base_keymap": "Atom",
	"ui_font_size": 14,
	"buffer_font_size": 14,
	"theme": {
		"mode": "system",
		"light": "One Light",
		"dark": "Snowflake Opaque"
	},
	"hard_tabs": true,
	"tab_size": 4,
	"show_whitespaces": "boundary",
	"soft_wrap": "editor_width",
	"format_on_save": "off",
	"buffer_font_family": "DejaVu Sans Mono"
}
```

**Comment by PoneyClairDeLune** [comment]
I think it's the problem of the LSP now... Used the provided config and the formatting still happens once I typed the closing curly brace....

**Comment by SomeoneToIgnore** [comment]
Oooh, makes sense, there's more than plain format requests that LSP can do indeed.
One extra thing to disable would be 
```
"use_on_type_format": false,
```

**Comment by PoneyClairDeLune** [comment]
Thanks! Finally stopped the automatic formatting.
