### ISSUE TITLE
Cross window copy paste doesn't work on linux

### ISSUE THREAD

**Issue by HKalbasi** [zed-industries/zed#14415]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With two zed windows, I can't copy a text from one into another, and I need to paste it inside a gedit, copy it again and paste it on the destination to workaround this issue.

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland ubuntu 22.04
Memory: 7.7 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Arajtav** [comment]
I can't even copy paste from one Zed instance to the same instance, zed 0.143.7-2, arch linux x86_64 with hyprland (wayland compositor). When i built zed myself like a month ago, copy paste worked, but i don't remember which exactly version was that.

**Comment by sshine** [comment]
I also came to report this (Linux, Wayland, GNOME). An additional observation:

- I can copy-paste from one Zed to another program (e.g. Firefox, terminal), and back.
- I can't copy-paste from one Zed to another Zed.
- **When I copy-paste from another program to one Zed, I can't paste that to the other Zed until I re-copy.**

It seems as if they're sharing a single channel somewhere.

Zed: 0.141.3 (/nix/store/6xk0j54s5fcsf7ivxysy0nb58d6iw4ii-zed-0.141.3/libexec/zed-editor)
OS: NixOS (unstable)
Architecture: x86_64

**Comment by bneijt** [comment]
I have the same issue on. `zeditor --version` just gives me `Zed  – /usr/lib/zed/zed-editor`, so not sure which version this is.
- I can copy-paste using the middle click implicit copy (select text, go to other window, middle click on mouse). Both between different zed instances and other windows.
- I can copy-paste (ctrl-c, ctrl-v) inside one of the open zed editors
- I can not copy in one zed (ctrl-c) and paste in another zed window (ctrl-v)
- I can copy from zed (ctrl-c) to another window like gedit (ctrl-v)

My zed comes from `extra/zed 0.144.4-1` on Archlinux.
My `xdpyinfo` starts with:
```
name of display:    :0
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    12401001
X.Org version: 24.1.1
```

**Comment by m3rashid** [comment]
It also shows different keybindings for copy-paste sometimes (even when I have vim mode disabled)
![image](https://github.com/user-attachments/assets/d56ecc57-b0b0-45c3-935c-dfc16fa3b94b)
And these don't even work

**Comment by xhos** [comment]
I'm probably having the same issue, can't paste anything into Zed at all, but can copy from zed and paste into Firefox, for example.

NixOS, Hyprland, latest Zed from unstable nixpkgs (0.141.3)

**Comment by aiden3c** [comment]
Also getting this issue running Zed 0.146.3
Running Debian Bookworm with Gnome and Wayland

**Comment by apricotbucket28** [comment]
The [wl_data_device::selection](https://wayland.app/protocols/wayland#wl_data_device:event:selection) event states this:
> The data_offer is valid until a new data_offer or NULL is received or until the client loses keyboard focus. Switching surface with keyboard focus within the same client doesn't mean a new selection will be sent.

This seems to be the issue. I cannot reproduce on KDE but the spec states that we must handle this differently. I'll take a stab at this later.

**Comment by eduardorubim** [comment]
> Why after 2 years, this is still an issue on mac? [@Developers](https://github.com/Developers)...?

and on NixOS + GNOME latest stable and unstable

**Comment by ChrisKitching** [comment]
Seeing this today on Zed 1.2.5 on Arch Linux. Worked fine for hours, suddenly I cannot paste text into zed: I can only copy text from zed and paste it elsewhere. Nothing in the log. Not really clear on how to produce clear reproduction steps due lack of log output and the fact it just *randomly stopped working*. Even restarting zed does not revive it...?!

There seems to be a [dead pull request](https://github.com/zed-industries/zed/pull/41282) which might be related?
