### ISSUE TITLE
Editor includes unnecessary header files in C

### ISSUE THREAD

**Issue by motherboardMage** [zed-industries/zed#14411]
### Check for existing issues

- [X] Completed

### **The issue:**
While typing certain keywords or functions in the editor and using auto-complete to complete the line, the editor automatically includes any header files that the keywords or functions are a part of. While this is extremely useful, sometimes the editor includes headers that are unsupported or unavailable on the specific operating system or compiler, or headers that are completely unnecessary for the code to behave as intended  or ones that have been included in another header file in the code already.

### **Here are some screen recordings:**

https://github.com/user-attachments/assets/1df868cf-3776-4d05-8f85-27cd74359a22

As you can see, the editor prompts me to auto complete the "NULL" keyword and as I do it, it includes the "cstddef" header file which is both, unnecessary for the program to run and not available to the compiler. The standard libraries required by the program are already included in the linkedList.h header file.

<img width="364" alt="Screenshot 2024-07-13 at 11 41 20 PM" src="https://github.com/user-attachments/assets/bb0220b5-11ff-40d4-a639-7d1634eec51f">

### **Steps to reproduce:**

1. Create a new C file and include the standard input-output header (stdio.h)
2. In your function, create a pointer variable of any type and start assigning it the value NULL
3. While you type the first few letters of the keyword, the editor will prompt you to autocomplete it and show you the library "cstddef" in which NULL is supposed to be defined.
4. While the NULL keyword is highlighted in the autocomplete menu, press enter or return to complete the keyword.
5. The "cstddef" library should get included automatically and underlined in red as it is not available to clang.

There were also instances where libraries that have been already included in another header file get included again by the editor, in the same manner.

https://github.com/user-attachments/assets/b7911c57-ea39-4af0-bdec-7a635a35a90d

I have raised and seen other people raise similar issues with formatting in the past and I believe all of them have to do something with the language server itself.

https://github.com/zed-industries/zed/issues/13924#issue-2394877431
https://github.com/zed-industries/zed/issues/4842#issuecomment-2219576889
https://github.com/zed-industries/zed/issues/12154#issue-2311429453

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
This looks like the work of the LSP server underneath, which is `clangd`.
Does this server works better in any of the editors?

Zed itself knows nothing about languages — it barely has a tree-sitter syntax tree information and that's it.


> I have raised and seen other people raise similar issues with formatting in the past and I believe all of them have to do something with the language server itself.

How is formatting related to the current issue?

**Comment by motherboardMage** [comment]
> This looks like the work of the LSP server underneath, which is `clangd`.
> Does this server works better in any of the editors?
> 
> Zed itself knows nothing about languages — it barely has a tree-sitter syntax tree information and that's it.
> 
> 
> > I have raised and seen other people raise similar issues with formatting in the past and I believe all of them have to do something with the language server itself.
> 
> How is formatting related to the current issue?

As far as I have been able to understand, one of the functions of the language server is holding required information for features like formatting, code completion, code highlighting etc. and frankly, to me the issues in these posts seem similar enough to include here. I am not very well versed with this technology so pardon me for any trouble caused.

**Comment by SomeoneToIgnore** [comment]
No troubles at all, but to restate again: there's nothing on Zed side we can do except

* finding discrepancies between Zed's and other editors' behavior with the same language server — if that's the case, we need a code example and the description/video how other editors that use `clangd` are better in importing

* changing to another language server for that language — then we need a new server name and, again, a code example with the description on how this server is better

**Comment by chakkawat-sonaruea** [comment]
This is not Zed problem. I am also get suggested `NULL` in nvim that used clangd, as follow:
![Screenshot_2024-07-14_18-00-42](https://github.com/user-attachments/assets/636e60a1-3367-43f5-b268-fce91d661585)

I want to point that clangd mention C++ in the website, so it would suggest that clangd is config to work with C++ out of the box.
That why you see something C++ elements like `std::nullptr_t` in your first video.

If your project intent to only use C, I would recommand use compiler flag `-xc` for clang so that clangd to treat all files as C.

One way to configure clangd is with `.clangd.` file.
If you didn't familiar with config clangd with `.clangd` file, create `.clangd` file in the root of your project folder.

And here are example of  said config to using `-xc` to make clang treat all file as C.
```
CompileFlags:
  Add:
    - -xc
```
After this restart Zed to make sure the change apply. If nothing wrong, you should have only autocomplete for C.

Here is desired behavior:
![Screenshot_2024-07-14_19-11-25](https://github.com/user-attachments/assets/c29e895f-2097-42cd-8847-93629a34dc62)

**Comment by pfirsich** [comment]
This is a problem in multiple context, even when using C++. The way to disable this is to add the `-header-insertion=never` option to clangd. It would be nice if Zed had this as a configuration file, but as a workaround solution, you can add it to your .clangd file like so:
```
CompileFlags:
  Add: [ -header-insertion=never ]
```
