### ISSUE TITLE
Spawning tasks takes more than one second

### ISSUE THREAD

**Issue by holgerk** [zed-industries/zed#14429]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i spawn or respawn the Example Task it takes more than one second to see the first output line (Hello 1/5).
Everything else feels good and snappy.

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 10.15.7
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
If you consider the entire command output, there will be something like this:
```
Hello 1/5
Hello 2/5
Hello 3/5
Hello 4/5
Hello 5/5

⏵ Task `Example task` finished successfully
⏵ Command: '/bin/zsh -i -c `for i in {1..5}; do echo "Hello $i/5"; sleep 1; done`'
```

That `/bin/zsh -i ` (or whatever shell you have there) is the cause you are seeing the tasks' output delayed, as the task initializes the terminal first.

Here's how you can prove it:
```diff
diff --git a/crates/terminal/src/terminal.rs b/crates/terminal/src/terminal.rs
index ccd6d9813..b015a160c 100644
--- a/crates/terminal/src/terminal.rs
+++ b/crates/terminal/src/terminal.rs
@@ -146,7 +146,7 @@ pub struct ZedListener(UnboundedSender<AlacTermEvent>);
 
 impl EventListener for ZedListener {
     fn send_event(&self, event: AlacTermEvent) {
-        self.0.unbounded_send(event).ok();
+        self.0.unbounded_send(dbg!(event)).ok();
     }
 }
 
```
applied on `59ce3535d38946acaa7f7dcf6fcdf0aedd127432` in this repo will show, that 
`[crates/terminal/src/terminal.rs:149:31] event = Wakeup` is printed almost at the same time Zed outputs the next task line, and that the first wakeup is quite delayed.

We can go even deeper and take `b3f0f68184b0d6b6221a5955acfcc4e33c01b766` from https://github.com/zed-industries/alacritty/ (the emulator Zed uses) and apply a 
```diff
diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index 8da758df..0fe4bec4 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -1882,6 +1882,6 @@ impl EventProxy {
 
 impl EventListener for EventProxy {
     fn send_event(&self, event: TerminalEvent) {
-        let _ = self.proxy.send_event(Event::new(event.into(), self.window_id));
+        let _ = self.proxy.send_event(Event::new(dbg!(event).into(), self.window_id));
     }
 }
diff --git a/alacritty/src/window_context.rs b/alacritty/src/window_context.rs
index 062f9ef0..469001c3 100644
--- a/alacritty/src/window_context.rs
+++ b/alacritty/src/window_context.rs
@@ -180,6 +180,15 @@ impl WindowContext {
     ) -> Result<Self, Box<dyn Error>> {
         let mut pty_config = config.pty_config();
         options.terminal_options.override_pty_config(&mut pty_config);
+        pty_config.shell = Some(alacritty_terminal::tty::Shell::new(
+            // "/bin/zsh".to_string(),
+            "/bin/bash".to_string(),
+            vec![
+                "-i".to_string(),
+                "-c".to_string(),
+                "for i in {1..5}; do echo \"Hello $i/5\"; sleep 1; done".to_string(),
+            ],
+        ));
 
         let preserve_title = options.window_identity.title.is_some();
 

```

Running that with `cargo run -p alacritty` will show that whatever default terminal used initially will have a lag, but other terminals without large configs (`/bin/bash` for me) will behave faster.


The main reason for Zed tasks to behave so is to avoid confusions like "why did not my aliases worked", etc. ergo the `-i` flag.
I believe, there was already a request to be able to change the shell the tasks are run in, but I've failed to find one now, unfortunately.

**Comment by holgerk** [comment]
@SomeoneToIgnore Thank you very much for the perfect clarification. It was indeed my zsh configuration that was causing the delay. When i omit the configuration everything feels snappy. For now i changed my settings to:
```
{
    "shell": {
      "program": "sh"
    }
}
```
But it would be nice if there were a separate configuration option for tasks.
