### ISSUE TITLE
Add shortcuts for cursor expanding

### ISSUE THREAD

**Issue by katry0** [zed-industries/zed#14423]
### Check for existing issues

- [X] Completed

### Describe the feature

Shortcuts to expand cursor to line below / above, would be fast alternative to alt+click when someone needs to expand next / previous lines at same position.

### If applicable, add mockups / screenshots to help present your vision of the feature

Example expanding cursor  keymap in sublime-text: 
```
{ "keys": ["ctrl+shift+down"], "command": "select_lines", "args":{"forward": true},
{ "keys": ["ctrl+shift+up"], "command": "select_lines", "args": {"forward": false} }
```

**Comment by someone13574** [comment]
Zed already has this. The shortcut is `shift+alt+up/down` (on linux at least).

**Comment by katry0** [comment]
> Zed already has this. The shortcut is `shift+alt+up/down` (on linux at least).

Great! Is it possible to remap this binding? I don't see it in the manual.

**Comment by katry0** [comment]
Finally found it, under mapping `editor::AddSelectionAbove` and `editor::AddSelectionBelow` - I was confused by the "selection" word, because i had nothing "selected" but it works for both selection and cursor. Very nice!

Thank you for your help! :)
