### ISSUE TITLE
zed is open in bg but doesnt show ui

### ISSUE THREAD

**Issue by Lavishq** [zed-industries/zed#14436]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

install zed via `curl https://zed.dev/install.sh | sh`
or install it via `sudo pacman -S zed`

open zed via dmenu or type in terminal `zed` 
it will not show anything, no error but there is no ui and so i restarted it and run `zed` still same issue

i have issues w/ top so installed htop to monitor if it is running, and yep, it is running in bg w/ 114 MiB and as of writing 768M but there is no ui so i cant write code

### Environment

> pfetch

       /\           lavishq@void
      /  \          os     Arch Linux
     /\   \         host   HP Laptop 14s-fq1xxx
    /      \        kernel 6.9.9-zen1-1-zen
   /   ,,   \       uptime 15m
  /   |  |  -\      pkgs   1093

ps: im using hyprland (wayland)
i tried to look for other issues where ui doesnt load but didnt see any 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/951a34f1-113e-4ca3-9e23-577b6fb43fa1)
![image](https://github.com/user-attachments/assets/e52035b8-f36c-4b48-822b-04f0bd646557)

i have no ui

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16216399/Zed.log)
</pre></details>

**Comment by norpol** [comment]
@Lavishq Try opening an actual file (or non existent). For me just running `zed` doesn't do anything but doing `zed newfile` or `zed /etc/hosts` will actually open the editor

**Comment by Lavishq** [comment]
@norpol no i already tried to do `zed .`, but rn as you sayed to try to open a file and i got this error

❯ zed lol
error opening [PathLikeWithPosition { path_like: "/home/lavishq/lol", row: None, column: None }]: VulkanError(ERROR_INCOMPATIBLE_DRIVER)

**Comment by Moshyfawn** [comment]
I could be wrong, but #14156 seems to be related or even the same issue; can anyone confirm/deny this?

**Comment by Lavishq** [comment]
@Moshyfawn yes ser, youre correct

**Comment by nnikolov3** [comment]
I use Fedora 40, after installing cuda and ollama I get the same issue.
