### ISSUE TITLE
GNOME desktop icon does not match with app name

### ISSUE THREAD

**Issue by p5** [zed-industries/zed#14435]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using GNOME (and possibly other desktop environments), when you open the Zed desktop app, the running window and pinned dock entries are different.  This is because the name of your `.desktop` file does not match the app ID you are providing.

To resolve this, the `.desktop` file name needs to be changed to `dev.zed.Zed` (stable) or `dev.zed.Zed-Nightly` (nightly) or `dev.zed.Zed-Preview` (preview) or `dev.zed.Zed-Dev` (dev).

This will allow the icons to match with the running window.

I am happy to work on this.

### Environment

GNOME Fedora 40

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/3953210b-8828-4607-8b8f-8a240bed9d8d)

**Comment by 2zqa** [comment]
It works fine for me. Is it perhaps because you are running the preview version?

![afbeelding](https://github.com/user-attachments/assets/6608650b-1348-4d2c-be86-05c0939468ee)

On Fedora 40, Zed version 0.143.7

**Comment by p5** [comment]
I noticed a comment saying it worked fine, but that comment seemed to be removed.  
The installation script I am using can be found in [this PR](https://github.com/rsturla/eternal-images/pull/267/files), plus the fix I have suggested.

**Comment by 2zqa** [comment]
Apologies, that was me. Perhaps I should have edited instead of removing it.

To re-post:

> It works for me on stable, when installing using the curl | sh method.
>
> ![Schermafdruk van 2024-07-14 12-13-22](https://github.com/user-attachments/assets/477bd9fe-63ef-4efd-b4dc-8e66bc7ff1f4)
>
> On Fedora 40, version 0.143.7

But I noticed that in your MR you already made the distinction between release types, I removed it.

**Comment by p5** [comment]
Ah, I must have completely missed this install method.

It looks like the script has already accounted for the desktop name changes, so my implementation is slightly wrong.  Will update the PR, and that should help those who manually installed.  

Thank you!

**Comment by p5** [comment]
So it appears this issue is only affecting those who install manually, so I have updated the docs accordingly.  
Thank you @2zqa - I wouldn't have noticed otherwise!

**Comment by 2zqa** [comment]
Whew - glad I re-added my comment then. Glad to help!

**Comment by matthew-macgregor** [comment]
I encountered the same issue. I did a manual install (system-wide). Changing the desktop file name to `dev.zed.Zed` (for stable) solved the problem for me.

**Comment by JosephTLyons** [comment]
This is now in today's [preview release](https://zed.dev/releases/preview/0.145.0).
