### ISSUE TITLE
Keyboard shortcuts don't work in Cyrillic

### ISSUE THREAD

**Issue by kyborq** [zed-industries/zed#14444]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Keyboard shortcuts only work on the English keyboard layout. If you use a different input method, such as Russian (Cyrillic), some combinations, like copy, paste, and the command palette may stop working.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 15.4 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Randommist** [comment]
I also encountered this problem on Wayland Arch

**Comment by AndyDroid10X** [comment]
Duplicate of #14053
