### ISSUE TITLE
Issue with Zed on Pop!_OS using X11 - WAYLAND_DISPLAY='' set but not working, Zed Preview works fine

### ISSUE THREAD

**Issue by alexnogueirasilva** [zed-industries/zed#14453]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi,

I am experiencing an issue with Zed on Pop!_OS where the application does not open properly using X11, despite setting the `WAYLAND_DISPLAY=''` environment variable. Interestingly, the Zed Preview version opens without any problems under the same conditions.

Here are the details:

- **OS:** Pop!_OS
- **Window System:** X11
- **Issue Description:** When trying to open Zed with `WAYLAND_DISPLAY=''` set, the application fails to start correctly. However, the Zed Preview version works fine.
- **Steps Taken:**
  - Set `WAYLAND_DISPLAY=''` in my shell profile.
  - Verified that `WAYLAND_DISPLAY=''` is set by checking with `echo $WAYLAND_DISPLAY`.
  - Created and modified `.desktop` files to ensure `WAYLAND_DISPLAY=''` is set for both Zed and Zed Preview.
  - Verified that Zed Preview works, but the main Zed application does not.

**Expected Behavior:**
- Zed should start correctly using X11 when `WAYLAND_DISPLAY=''` is set, similar to how Zed Preview functions.

**Actual Behavior:**
- Zed fails to start or crashes when `WAYLAND_DISPLAY=''` is set.

**Additional Information:**
[Gravação de tela de 14-07-2024 14:38:17.webm](https://github.com/user-attachments/assets/47c95fe3-2713-468b-9bc9-710cdeea17c1)

- There are no error messages in the terminal indicating what might be wrong.
- Both applications (Zed and Zed Preview) are installed and launched in the same environment with the same settings.

Could anyone provide guidance on how to resolve this issue? Is there any additional configuration or steps that I might be missing?

Thank you for your assistance!

### Environment

OS: Pop!_OS
Window System: X11
RAM 64 GB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Thanks for reporting.  The current preview (v0.144.x) will become the new stable tomorrow.  There were quite a few changes, not quite sure which one fixed it:
- https://github.com/zed-industries/zed/compare/v0.143.7...v0.144.2-pre

But if this isn't fixed in tomorrows stable, feel free to comment and we can reopen.
Thanks!
