### ISSUE TITLE
Start maximized

### ISSUE THREAD

**Issue by bersace** [zed-industries/zed#14454]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

Zed is awesome, thanks !

What do you think of a way to start zed maximized ?

I'm thinking of a setting `"start_maximized": true` or something like that.

Regards,
Étienne

**Comment by notpeter** [comment]
Curious whether you always want it to start maximized or would be sufficient to just match the previous workspace window state (maximized and positioned at 0,0):
- https://github.com/zed-industries/zed/issues/5258

**Comment by bersace** [comment]
@notpeter . Thanks for matching the two issues. I think that #5258 could do the trick. Closing in favor of it.
