### ISSUE TITLE
Linux: "Select Previous" and "Duplicate Line Down" have the same default keybinding

### ISSUE THREAD

**Issue by xoich** [zed-industries/zed#14458]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Both these commands are bound to Ctrl-Shift-D. Pressing it will duplicate the line down.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland arch unknown
Memory: 30.1 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
Thanks for reporting this. I believe I've fixed it with PR #14600.
