### ISSUE TITLE
 vim support :bd, :bn, :bp

### ISSUE THREAD

**Issue by pckilgore** [zed-industries/zed#14457]
### Check for existing issues

- [X] Completed

### Describe the feature

> We do not (yet) emulate the full power of vim’s command line, in particular we special case specific patterns instead of using vim's range selection syntax, and we do not support arguments to commands yet. Please reach out on [GitHub](https://github.com/zed-industries/zed) as you find things that are missing from the command palette.

Like `:q`, support or `:w` support, add commands for

- `:bd` -> close current pane 
- `:bn` -> go to next pane
- `:bp` -> to go previous pane

Or allow me to define these myself.  These are a deal breaker in terms of muscle memory, particularly no `:bd` support.

**Comment by JosephTLyons** [comment]
This is now in today's [preview release](https://zed.dev/releases/preview/0.145.0).

**Comment by pckilgore** [comment]
Amazing, thank you all.
