### ISSUE TITLE
Collapsing deeply nested folder structures when possible

### ISSUE THREAD

**Issue by seyfu-t** [zed-industries/zed#14462]
### Check for existing issues

- [X] Completed

### Describe the feature

I think this is a very Java developer issue, but Java projects typically have deeply nested folders, due to the long naming scheme (e.g. com.google.code.gson). 
This can make it hard to navigate, especially due to the design decision to make the sidebar unscrollable, i find my self resizing the panel over and over again. 

### If applicable, add mockups / screenshots to help present your vision of the feature

Zed:
![image](https://github.com/user-attachments/assets/1c5a2455-fad3-410c-9934-2bc9c8e8fc6b)

VSCode:
![image](https://github.com/user-attachments/assets/9de9bd41-8342-4266-8453-eaf5ce0dce36)

**Comment by SomeoneToIgnore** [comment]
This should enable it:

```json
"project_panel": {
    "auto_fold_dirs": true
}
```

default settings.json have more descriptions for other settings parameters, in case more customizations of the project panel are needed.
