### ISSUE TITLE
Open file in split from Project Panel on Linux

### ISSUE THREAD

**Issue by ferrao** [zed-industries/zed#14465]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"Open to the side" as described in #10549 does not work on linux, I have tried Ctrl, Alt, and Super keys, nothing works and I am unable to open a file from Project Panel into a new split.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 30.6 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
this is a bug.
