### ISSUE TITLE
window not drawn on Linux Mint 21.3 using nvidia gpu 

### ISSUE THREAD

**Issue by daniejstriata** [zed-industries/zed#14469]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run Linux mint 21.3 with nvidia 545.29 display driver on X11. When I open zed 0.143.6 or 0.143.7 there is no display. I can see briefly that something is drawn on the display and when I hover my mouse over the area where I could see the change, my mouse pointer changes to resize or to a text entry field is underneath it. It captured what was displayed below the Zed window. I opened Chrome below zed to demonstrate:
![image](https://github.com/user-attachments/assets/e23e962c-bc5e-412f-a5ba-3a8e2e0981f1)

Here is some video to help describe what I'm experiencing with no other applications open on the screen besides Zed.
Hover:
https://github.com/user-attachments/assets/0fc2c33a-9d87-4d2c-aa04-957125146a42
Maximise:
https://github.com/user-attachments/assets/f46d8a91-97c9-411b-8655-a84aa28ab009

When I run zed in foreground I get:
```
[2024-07-15T07:53:41+02:00 ERROR gpui] window not found
[2024-07-15T07:53:41+02:00 ERROR gpui] window not found
```

Please let me know what other info I can provide:

### Environment

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off | 00000000:01:00.0  On |                  N/A |
| N/A   54C    P5              15W /  80W |    575MiB /  6144MiB |     34%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     26331      G   /usr/lib/xorg/Xorg                          300MiB |
|    0   N/A  N/A     36279      G   cinnamon                                     47MiB |
|    0   N/A  N/A     37402      G   ...erProcess --variations-seed-version       35MiB |
|    0   N/A  N/A     40241      G   ...seed-version=20240712-130137.211000      128MiB |
|    0   N/A  N/A    187943      G   ...ures=SpareRendererForSitePerProcess       61MiB |
+---------------------------------------------------------------------------------------+
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by daniejstriata** [comment]
I tried the preview build and it does the same

**Comment by nikiosna** [comment]
I'm having the same issue (Linux Mint 21.3, Nvidia Quadro P520)
vulkan-tools -> `vkcube` demo runs fine

**Comment by chakkawat-sonaruea** [comment]
Does press `Ctrl + O` show your native file chooser? If so the program seem to be working, but not rendering.

Also provide your `Zed.log` from `~/.local/share/zed/logs` may give more insight to your problem.

**Comment by daniejstriata** [comment]
@chakkawat-sonaruea The file chooser did pop up on `Ctrl + O`. I attached the log file.
[Zed.log](https://github.com/user-attachments/files/16233837/Zed.log)

**Comment by chakkawat-sonaruea** [comment]
This maybe unrelated. But can you try in any order, maximize, unmaximize, resize, or move, the window by using your taskbar. Does this effect the issue?

**Comment by daniejstriata** [comment]
@chakkawat-sonaruea I've demonstrated that in the second video

**Comment by daniejstriata** [comment]
installing the pka resolved my issue. @chakkawat-sonaruea  @nikiosna Should zed not draw a fallback screen if it fails to render the primary stream?
