### ISSUE TITLE
Vim Mode Retains Movement Count

### ISSUE THREAD

**Issue by sjagoori** [zed-industries/zed#14475]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Vim mode in the Zed editor, the movement count (e.g., 2k to move up two lines) is retained for subsequent movements. While this feature can be useful, it may lead to unexpected behavior for some users. It would be helpful to have an option to reset the movement count after a single motion.

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/01100caf-0e6b-4315-be9c-e50c5f4ef576

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
@sjagoori It should not do that. Have you remapped `k` to `editor::MoveUp` instead of `vim::Up`? (it's possible you want it to be `["vim::Up", { "displayLines": true }]` so it goes up by one visual line always even in the case of wrapped lines).
