### ISSUE TITLE
Add Powerline glyphs in Zed fonts

### ISSUE THREAD

**Issue by matthprost** [zed-industries/zed#14476]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I'm using Zed and zsh on my terminal, while opening the terminal inside Zed it seems like glyphs are not correctly interpreted since a recent update.

Here is how to reproduce:

1. Install zsh on your terminal
2. In your `.zshrc` file add `ZSH_THEME="agnoster"` to have the same theme as me
3. Open zed and open the terminal panel
4. You should see the following:
<img width="1800" alt="Screenshot 2024-07-15 at 10 41 30" src="https://github.com/user-attachments/assets/382de5fa-7015-4dd8-8510-02fd9c279344">

Note: it works perfectly fine in iTerm:
<img width="900" alt="Screenshot 2024-07-15 at 10 45 07" src="https://github.com/user-attachments/assets/026cfe38-9825-4edf-9b30-f243b314891b">

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
From the [agnoster-zsh-theme README](https://github.com/agnoster/agnoster-zsh-theme)

> NOTE: In all likelihood, you will need to install a [Powerline-patched font](https://github.com/Lokaltog/powerline-fonts) for this theme to render correctly.

> To test if your terminal and font support it, check that all the necessary characters are supported by copying the following command to your terminal: echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699". The result should look like this:

I'll convert this to an enhancement request for the Zed fonts to support those characters, but in the meantime you'll have to install a patched font and tell Zed to use that font with `buffer_font_family` in your settings.json.

**Comment by matthprost** [comment]
@notpeter Thanks your explanation and for your quick answer 👌

**Comment by notpeter** [comment]
FYI: Zed Mono (Iosevka derivative) is now available [as a patched NerdFont](https://www.nerdfonts.com/font-downloads) which includes powerline glyphs.  No Zed Plex Mono (IBM Plex derivative) yet, but fingers crossed.

**Comment by gbubemismith** [comment]
@matthprost If this works in VSCode, you can try using the same font found in `terminal.integrated.fontFamily` setting in VSCode. Then, you can apply a similar configuration to your Zed settings.

```
"terminal": {
    "font_family": "{font family from vscode}",
    "font_size": 15
  }
```

**Comment by macintushar** [comment]
@gbubemismith this is my VSCode setting
```
"terminal.integrated.fontFamily": "'DejaVu Sans Mono', 'PowerlineSymbols'"
```

but if I add it to my Zed settings.json, it doesn't work.

**Comment by notpeter** [comment]
> @gbubemismith this is my VSCode setting
> ```
> "terminal.integrated.fontFamily": "'DejaVu Sans Mono', 'PowerlineSymbols'"
> ```
> but if I add it to my Zed settings.json, it doesn't work.

Zed is not a VSCode fork so it has it's [own settings](https://zed.dev/docs/configuring-zed).

The easiest way to support DejaVu Sans Mono with Powerline symbols is just download [DejaVu Sans Mono for Powerline](DejaVu Sans Mono for Powerline) which includes everything in a single font.  Install that font into your OS (e.g. FontBook on MacOS), restart Zed and add it as your [terminal font_family](https://zed.dev/docs/configuring-zed#terminal-font-family).
<img width="613" alt="Screenshot 2024-10-05 at 11 49 23" src="https://github.com/user-attachments/assets/b8f9798b-79ba-4eea-a8a8-144b1ff6d3e6">

**Comment by macintushar** [comment]
@notpeter this is what I added to my Zed settings.json
```
"terminal": {
    "font_family": "'DejaVu Sans Mono', 'PowerlineSymbols'"
  }
```

I downloaded the DejaVu Sans for Powerline font and it started working immediately. Thanks for the help!

**Comment by matthprost** [comment]
Thank you all for your messages! Here is the final answer I found working:

1. In a terminal:
```sh
brew install --cask font-blex-mono-nerd-font
```

2. In Zed config file (Cmd + Shift + P > Type "settings")
```json
// ~/.config/zed/settings.json
{
  "terminal": {
    "font_family": "BlexMono Nerd Font Mono"
  }
}
```

**Comment by douglaslassance** [comment]
What about the small mismatch you get between the text background color and the arrow?
