### ISSUE TITLE
Using ⌘⇧P doesn't trigger Command Palette in macOS Sequoia if Passwords app is active in menu bar

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#14474]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When Passwords app in macOS Sequoia is active in menu bar, the default shortcut to toggle it is ⌘⇧P, same as Command Palette in Zed. When Zed window is focused, triggering ⌘⇧P should trigger Command Palette instead of triggering Passwords app.

### Environment

Zed: v0.144.2 (Zed Preview)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Hi, I don't currently have MacOS sequoia beta installed to test with.  I'm not sure it will be possible to overide a MacOS handled shortcut. Can you confirm whether this also impacts VSCode (I would expect so).

My recommendation is to pick an alternate shortcut for Passwords or an alternate shortcut in Zed for command palette.

**Comment by Dygear** [comment]
Currently this seems to be a hard coded shortcut that we are unable to turn off currently in Sequoia Beta 3. This is an Apple issue. I've submitted Feedback on this and I recommend that @Tom-Boscher does the same as this is an undesirable outcome for the Passwords app to commandeer the Shortcut and for it to not be reassignable or allow users to turn it off. I for one am never going to use Passwords so much that I need it as a keyboard shortcut.

**Comment by hugginsio** [comment]
macOS 15.0.1 (24A348) here - I'm not sure this is an issue anymore? `cmd-shift-p` no longer appears to be linked to Passwords in Menu Bar:

<img width="672" alt="image" src="https://github.com/user-attachments/assets/1dd7f9e7-3b89-45dd-ba39-10a4d234bf7d">

Furthermore, even though I do have an app that took over `cmd-shift-p` by default in macOS settings:

<img width="391" alt="image" src="https://github.com/user-attachments/assets/21e83aba-2ef7-43fa-818d-1842fe0e1a8f">

The shortcut does not trigger when Zed is focused, so the command palette works as expected.

**Comment by shyim** [comment]
I am on 15.4.1 and have the same issue. But I have this only in Zed (VSCode works), I have no glue why. 
anyone maybe an tip? (Zed Preview 0.186.1 )
