### ISSUE TITLE
Multiline Comment

### ISSUE THREAD

**Issue by PylotLight** [zed-industries/zed#14485]
### Check for existing issues

- [X] Completed

### Describe the feature

On vscode I can select some text and use alt shift a to trigger a multiline comment which wraps in a relevant comment block instead of individual comments per line. Can we add that here?

This is for GO LSP in particular.

**Comment by notpeter** [comment]
VSCode has dedicated shortcuts for this in addition to `cmd+/` / `ctrl+/`:
- Windows: shift+alt+A
- Linux: shift+ctrl+A
- MacOS: shift+option+A

Potentially related: 
- https://github.com/zed-industries/zed/issues/13318

**Comment by PylotLight** [comment]
Ah I didn't see that one. If it's related then please use that instead of this one and feel free to close.

**Comment by blazERpavlica** [comment]
I don't see why this is closed. The shortcut mentioned by @notpeter doesn't work and there is no command for it in the Command palette.

I am using Zed 0.160.7 on Linux.

**Comment by notpeter** [comment]
@blazERpavlica Perhaps I wasn't explicit enough. I closed in favor of:
- https://github.com/zed-industries/zed/issues/13318
