### ISSUE TITLE
Difficulty_In_Installing_CLI. 

### ISSUE THREAD

**Issue by malhiamitoj** [zed-industries/zed#14487]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Shot-2024-07-15-160447](https://github.com/user-attachments/assets/9f064239-b334-4e8e-a40a-469dfa78ee7b)

so as the description in the pic tells to about the source of download : 
1. from official source 
2. from package manager or other sources 
Right! 
And , I installed it from the official source : 
which is this script on the official website zed.dev -->  curl https://zed.dev/install.sh | sh 

and  the pic suggest to add ~/.local/bin to the $PATH 
which I have done shown in this screenshot below: 
![Shot-2024-07-15-160506](https://github.com/user-attachments/assets/2e8db056-18d2-4820-b5a9-204ca42fcaeb)

so anybody tell me about this because i am unable to open the local files as well in the zed. 

### Environment

Distro: archlinux
kernel: linux 6.6.39-1-lts 
Zed version: zed 0.143.7
Not using bash but zsh 
 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Shot-2024-07-15-160447](https://github.com/user-attachments/assets/13a02bf0-b122-4ea0-866c-a97b9f430a70)
![Shot-2024-07-15-160506](https://github.com/user-attachments/assets/03dbd68c-efa6-47cd-af67-4b8bb9017ea6)

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16233473/Zed.log)

**Comment by ConradIrwin** [comment]
@malhiamitoj Does running `zed .` on the command line not work for you?

It should given that you have set it up.

Maybe we should have that error message be clearer in the case it should already work!

**Comment by ngowuys** [comment]
I'm using Arch Linux too, you can install zed directly from Arch repo. Just use `sudo pacman -S zed` to install, then you can use `zeditor path/to/project` from terminal to open Zed. You can also make alias to make `zed` available.

**Comment by boydkelly** [comment]
I don't even get any error message.  I just click on "Install the Cli" and nothing happens.

**Comment by arthurdev06** [comment]
Had the same problem, I'm in Arch, btw, using pikaur here's what I did to solve it: 

1. I uninstalled zed and all his associated files;
2. Downloaded zed from the AUR the `zed-preview-bin ` .

For me it was just simple as it look's like, it solved my sign in problems too. Hope it helps in someway.

**Comment by malhiamitoj** [comment]
I don't know but it got solved with installing zed with package manager.
