### ISSUE TITLE
Attach task tab along files

### ISSUE THREAD

**Issue by bersace** [zed-industries/zed#14494]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

To workaround #4367 , I'm using a lazygit task. That's good.

I would like to have lazygit not in bottom dock but in main view, as first tab before files.

What do you think of adding a `show_in_main_stage` option to tasks.json ? I'm not sure about the name.

Zed is awesome.

Regards,
Étienne

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/ac65de12-0149-4292-9580-58c217bad40c)

**Comment by osiewicz** [comment]
You can already drag tabs out of terminal panel (where tasks reside). Does that fit your use case sufficiently?

**Comment by bersace** [comment]
Hi @osiewicz , thanks for your answer.

> You can already drag tabs out of terminal panel (where tasks reside). Does that fit your use case sufficiently?

Yes, I'm already dragging the tab as shown in the screenshot. I would like to persist this behaviour in tasks.json or any other solution.

**Comment by nullstalgia** [comment]
I also echo the desire to have tasks spawn in configurable spots (preferably override-able per-task?*).

Having the bottom half of my screen covered with the terminal isn't ideal, especially if I want to keep looking it over while it compiles/whatever.

\*Having it per task would be a nice bonus, as it would indirectly help me in quickly testing different sizes/aspect ratios for my TUI applications. 😅

**Comment by bersace** [comment]
Could we send task panel as first tab ? Or select position ?

**Comment by bersace** [comment]
Closing in favor of #17697
