### ISSUE TITLE
give priority to terminal over IDE when processing key bindings

### ISSUE THREAD

**Issue by giulianopz** [zed-industries/zed#14492]
### Check for existing issues

- [X] Completed

### Describe the feature

At the moment, if a open the integrated terminal and I press `crtl-r`, the menu for recents projects opens up (since I remapped the `Workspace::projects::OpenRecent` command to this keys) but I would like the terminal to process this keyboard input to [reverse-search](https://www.gnu.org/software/bash/manual/html_node/Commands-For-History.html#index-reverse_002dsearch_002dhistory-_0028C_002dr_0029) recent commands with bash.

**Comment by notpeter** [comment]
Hi @giulianopz please see here:
- https://github.com/zed-industries/zed/issues/14033#issuecomment-2226764353

**Comment by giulianopz** [comment]
> Hi @giulianopz please see here:
> 
>     * [Shortcut for reverse history search in terminal triggers symbol view instead #14033 (comment)](https://github.com/zed-industries/zed/issues/14033#issuecomment-2226764353)

hi @notpeter, thanks but that's weird IMHO: if so, I **must** explicitly list in the `keymap.json` all the keystrokes I want to forward to the terminal. This should be the default behaviour when the terminal it's focused (w/o any configurations). What do you think?

**Comment by notpeter** [comment]
Apologies, for the brevity.  Yes, I think this is an issue. For the moment I wanted to direct you to a workaround which will allow you to have the terminal operate as you expect.

This is definitely unsolved, especially if users want to be able to use the full range of `ctrl-` prefixed keyboard shortcuts while in terminal that doesn't leave anything for Zed. On the other hand we want to support people's usage models.  On MacOS we leverage the `cmd` key , but (for the moment) we have not create default bindings for Linux/Windows using the `super` / `windows` key as an alternate modifier.

Some people want ctrl-w to close their terminal.
Some people want ctrl-w to delete the previous word.

We are aware of the issue and trying to strike the right balance.
Please bear with us.
