### ISSUE TITLE
Terraform LSP failed to init

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#14502]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The TF LSP fails to initialise when opening a `.tf` file both with and without TF in the PATH.

### Environment

Zed: v0.145.0 (Zed Nightly e8d674dc04fdd3f74946014ef92e76fd9b78ba9c)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

Terraform: v0.0.3

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[INFO] retrying installation of language server "terraform-ls" in 1s
[INFO] About to spawn test binary
[WARN] test binary failed to launch
[WARN] test binary check failed
[INFO] beginning to reinstall server
[INFO] deleting server container
[ERROR] server container removal

Caused by:
    No such file or directory (os error 2)
[INFO] starting language server "terraform-ls", path: "/<user-path>/<project-path>", id: 6
[INFO] starting language server. binary path: "/<user-path>/Library/Application Support/Zed/extensions/work/terraform/terraform-ls-v0.34.0/terraform-ls", working directory: "/<user-path>/<project-path>", args: ["serve"]
[ERROR] failed to start language server "terraform-ls": failed to spawn command. path: "/<user-path>/Library/Application Support/Zed/extensions/work/terraform/terraform-ls-v0.34.0/terraform-ls", working directory: "/<user-path>/<project-path>", args: ["serve"]
[ERROR] server stderr: Some("")
[ERROR] Hit 4 reinstallation attempts for "terraform-ls"
</pre></details>

**Comment by dbanck** [comment]
I'm seeing the same problem.

It looks like the binary in `~/Library/Application\ Support/Zed/extensions/work/terraform` is missing the executable flag:
```
❯ ls -lha terraform-ls-v0.34.0/terraform-ls
-rw-r--r--  1 daniel.banck  staff    27M Jul 17 11:30 terraform-ls-v0.34.0/terraform-ls 
```

A temporary workaround is to set the flag manually: `chmod +x terraform-ls-v0.34.0/terraform-ls`

The source zip file for the language server contains the binary with the flag set, so I my first guess is that it is removed during installation.

**Comment by taleh007** [comment]
Looks like Zed 0.144.4 is affected too.
```sh
> ls -lah ~/Library/Application\ Support/Zed/extensions/work/terraform/terraform-ls-v0.34.1
total 56504
drwxr-xr-x  4 user  staff   128B Jul 24 12:44 .
drwxr-xr-x  8 user  staff   256B Jul 24 12:44 ..
-rw-r--r--  1 user  staff    16K Jul 24 12:44 LICENSE.txt
-rw-r--r--  1 user  staff    27M Jul 24 12:44 terraform-ls
```

**Comment by maxdeviant** [comment]
v0.0.4 of the Terraform will now mark the downloaded language server binary as executable, which should fix this issue.

Note that if you already have the latest language server version downloaded you'll need to delete the containing directory so that it gets downloaded again. On macOS the directory is `~/Library/Application\ Support/Zed/extensions/work/terraform`.

**Comment by dbanck** [comment]
Thank you! That fixes the issue for me

**Comment by taleh007** [comment]
Thanks for your work!
