### ISSUE TITLE
Assistant: File attachments to submit docs?

### ISSUE THREAD

**Issue by ezuk** [zed-industries/zed#14510]
### Check for existing issues

- [X] Completed

### Describe the feature

When I use ChatGPT for coding assistance, I sometimes start the conversation by uploading a zip with a framework's current documentation and use that to anchor the discussion. It would be helpful if there was a way to upload a zip file or provide a URL for the docs of the framework or library I'm using from the Assistant panel.

### If applicable, add mockups / screenshots to help present your vision of the feature

![cursor](https://github.com/user-attachments/assets/6916a621-ac7c-4d97-a6da-d32127d220c2)

**Comment by ezuk** [comment]
Thank you! I'll try `fetch`.

**Comment by apcamargo** [comment]
@maxdeviant is the `/docs` command still available? I couldn't find any way to retrieve the full documentation from `docs.rs`.

**Comment by maxdeviant** [comment]
> [@maxdeviant](https://github.com/maxdeviant) is the `/docs` command still available? I couldn't find any way to retrieve the full documentation from `docs.rs`.

It is, but you need to enable a setting in order to use it:

```json
"slash_commands": {
  "docs": {
    "enabled": true
  }
},
```

**Comment by apcamargo** [comment]
Thank you! It doesn't seem to be fetching all the documentation, only the index. Is this the expected behavior?

**Comment by maxdeviant** [comment]
> Thank you! It doesn't seem to be fetching all the documentation, only the index. Is this the expected behavior?

If you do `/docs docs-rs <CRATE>::*` it will wildcard all of the modules in the crate: `/docs docs-rs aes::*`.

You can do also do it for submodules: `/docs docs-rs aes::hazmat::*`.
