### ISSUE TITLE
I Cant edit anything on Zed Linux ( Seems like it is Read Only ), Cursor just jumping around when i press any key 

### ISSUE THREAD

**Issue by yhoungdev** [zed-industries/zed#14552]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Experiencing an issue with Zed, it got updated yesterday and i can't write anything, the cursor only jumps between.

I thought it was Rust only, but switched to Typescript and still got the same issue.

 I dropped a screen record of the issue below 👇👇👇

### Environment

OS: Linux 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://www.loom.com/share/5bb479560f1f4e97b64f2235cb7b0b5f?sid=2aa6c2f9-2d4e-4225-92bf-6d51a96d3cb7

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

{"signed_in":false,"milliseconds_since_first_event":195,"type":"Setting","setting":"theme","value":"One Light"}

</pre></details>

**Comment by yhoungdev** [comment]
Thanks, working fine now

**Comment by yhoungdev** [comment]
I think you are right. Toggle VIM mode is currently not performing any action. 

<img width="661" alt="Image" src="https://github.com/user-attachments/assets/681c2b43-b1b5-484d-a63f-6c20d79d07a1" />

Now, see the image above, can you see those icons below on the bottom left corner of your screen ?

**Comment by abhagsain** [comment]
> At the bottom right I see something changing when vim is toggled or not toggled, but I still cant edit the default settings.
> 
> ![Image](https://github.com/user-attachments/assets/e7cd7dbb-1b64-4ef6-bdf5-a2a9ec1656cf)
> 
> ![Image](https://github.com/user-attachments/assets/b31056b3-0e29-4fc4-8c03-c2c86148ad06)

I'm also facing the [same issue](https://x.com/abhagsain/status/1936392500962341246). I can't believe there are stupid bugs like these.
