### ISSUE TITLE
Add Config Variable for Custom settings.json Path

### ISSUE THREAD

**Issue by johnmwood** [zed-industries/zed#14568]
### Check for existing issues

- [X] Completed

### Describe the feature

# Problem

I have a dotfiles repo that I use for terminal, tmux, and other system config. It would be more  convenient to be able to point my zed config to a custom path in my dotfiles instead of the default `~/.config/zed/settings.json`. 

# Solution

In `settings.json`, add a config var that looks something like:
```
{
  "settingsCustomPath": "~/.config/dotfiles/zed/"
}
```

**Comment by notpeter** [comment]
While I appreciate the desire to manage your dotfiles centrally, the common method for this is to create a symlink at `~/.config/zed/settings.json` which points to the zed settings.json file inside your dotfiles repo (this is how I track my Zed settings).
