### ISSUE TITLE
Manually rename workspace

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#14563]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently it seems workspaces are named after the last top-level directory or file that has been added to them. This is... confusing when that happens to be say, `TODO.md`. As a default behaviour it makes sense to name workspaces after their main (and usually only) directory, but for more complicated scenarios I would prefer to give some workspaces a custom name that is entirely unrelated to the directories.

**Comment by jansol** [comment]
In the workspace switcher the "name" appears to be a comma-separated list of all top level items, so it's being inconsistent between the title bar button and the switcher, too.

**Comment by notpeter** [comment]
Hi @jansol, I'm going to close this favor of:
- https://github.com/zed-industries/zed/issues/4431 

Thanks for reporting!
