### ISSUE TITLE
Running a kernel should not add new lines to the buffer

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#14565]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried out the REPL feature, and it looks to be shaping up really nicely!

However, every time I hit "run kernel" from the kernel menu (or click the kernel button), it would add a new empty line to the buffer along with the (empty) output from the kernel.

### Environment

Zed: v0.145.0 (Zed Dev ef20afa9a43fccbbf4fca1bee04d9725373363fb)
OS: Linux Wayland ubuntu 24.04
Memory: 31.3 GiB
Architecture: x86_64

Kernel in question: python3

**Comment by rgbkrk** [comment]
This should just be ensuring there's a newline if you're at the end of a file, as we need it as an invariant. If that's not the case and it happens with in between runs, that's no good.

**Comment by jansol** [comment]
I pressed the run button 8 times and ended up with a buffer that had 9 empty lines at the end.

**Comment by rgbkrk** [comment]
Interestingly if, in Python I run `print("test", random.random())` as the last line then I get one newline. If I run an empty newline at the bottom then I get lots of newlines.

https://github.com/user-attachments/assets/57da4aa5-7ee1-48cb-a9f2-2bfdce6fd7f1

**Comment by jansol** [comment]
Yeah, that looks like what I saw.

**Comment by rgbkrk** [comment]
Ok, it looks like I can just have this not run empty code. The kernel will still start if you press the button (or submit with a key) but it won't create more block decorations.
