### ISSUE TITLE
Crashing on Arco Linux (Arch Based Distro) (Both on Wayland and Xorg) (Tried multiple desktop environments)

### ISSUE THREAD

**Issue by soumyashiskarmakar** [zed-industries/zed#14576]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

> zeditor --foreground
Xlib:  extension "NV-GLX" missing on display ":0".
[2024-07-16T21:21:38+05:30 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Result::unwrap()` on an `Err` value: ERROR_INITIALIZATION_FAILED",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-b2bcd1de1cf7ab6a/21a56f7/blade-graphics/src/vulkan/init.rs",
    "line": 384
  },
  "backtrace": [
    "__libc_start_main"
  ],
  "app_version": "0.143.7",
  "release_channel": "Zed",
  "os_name": "Linux X11",
  "os_version": "arcolinux unknown",
  "architecture": "x86_64",
  "panicked_on": 1721145098730,
  "installation_id": "ccfcdd92-a154-4434-8836-130e2ee1340b",
  "session_id": "b9791685-5da4-4608-b0fe-d8b8f30cf312"
}

### Environment

CPU: Intel i5-3470S (4) @ 2.900GHz
Memory: 1.26GiB / 3.72GiB (34%)
GPU Driver: Intel Corporation Device [8086:2111]

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
Sounds like it doesn't find a working vulkan driver. (or possibly OpenGL ES)

Can you run `vkcube`?

**Comment by soumyashiskarmakar** [comment]
Xlib:  extension "NV-GLX" missing on display ":1".
vkEnumeratePhysicalDevices reported zero accessible devices.

Do you have a compatible Vulkan installable client driver (ICD) installed?
Please look at the Getting Started guide for additional information.

**Comment by soumyashiskarmakar** [comment]
Not gonna work on this old intel?

**Comment by jansol** [comment]
It *might* just barely work if you build zed with the GLES feature of blade. But looks like vulkan can't be supported on that chip.

**Comment by soumyashiskarmakar** [comment]
Ok, thanks
