### ISSUE TITLE
I recently built zed on windows and i got a report from my anitvirus

### ISSUE THREAD

**Issue by IUB2010** [zed-industries/zed#14628]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

I build zed from source on windows and i got a report from my antivirus asking me to remove it . THis is the second time i have done this when i built zed from source the first time, I got this report too. So i removed it and it let to zed not working at all . Recently I have quarantined it and it t also lead to zed not working can i get some advise on what to do now. Should i re install zed or just leave it as it is.

### Environment

N/A

### If applicable, attach your Zed.log file to this issue.

<img width="449" alt="image" src="https://github.com/user-attachments/assets/3c4059c9-d847-4879-9d4c-48fe1a887d3f">

**Comment by notpeter** [comment]
This is likely a false positive.
Which anti-virus is triggering this?

**Comment by IUB2010** [comment]
Windows Security

**Comment by notpeter** [comment]
This issue was opened first, but I'm going to close it favor of this one:
- https://github.com/zed-industries/zed/issues/14789

Thanks for reporting.  I'm not sure there's much / anything we can do to fix this.
