### ISSUE TITLE
linux open project command does not do anything

### ISSUE THREAD

**Issue by gdbd** [zed-industries/zed#14634]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

steps:
1) installed via `curl https://zed.dev/install.sh | sh`
2) open zed
3) clieck open project or hot key ctrl+0

expected:
opens dialog to select folder

actual:
does not changed anything

system info:
Linux version 6.8.12-3-MANJARO (builduser@fv-az982-753) (gcc (GCC) 14.1.1 20240522, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Mon Jun 10 09:44:22 UTC 2024

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 manjaro unknown
Memory: 17.4 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16262900/Zed.log)

**Comment by jansol** [comment]
> i dont find where to run this command

In Zed, in the command palette (opens with ctrl+p or F1):
![image](https://github.com/user-attachments/assets/8077b190-bb64-4337-8d0d-f082977fe148)

**Comment by gdbd** [comment]
@Spargisale thank you, fixed also after i am install  xdg-desktop-portal-gtk
