### ISSUE TITLE
Not able to use openAI after completing setup properly 

### ISSUE THREAD

**Issue by DataRaj** [zed-industries/zed#14637]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Hello**, Today I started with the zed editor on my fedora based linux machine, I have completed setup of themes, plugins/extensions, keymaps and all other miscellaneous things like setting up copilot, but on clicking the button of openAI, it first asked me for an API key, which is something like **subscription** based I guess, because it has some limits (about $5/m), but after getting a putting API KEY, I still couldn't figure out how to use it. 

### Environment

Linux Fedora 39

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Hey @DataRaj, just to double check, you are using an API key you purchased here?

- https://platform.openai.com/api-keys

Also, might want to try re-entering the api key by using `assistant: reset key` when focusing on the assistant panel.

Let me know.

**Comment by notpeter** [comment]
@DataRaj Closing as stale. To use OpenAI in the assistant you need an OpenAI API key which is billed per request.  We've also improved the Assistant configuration flow and so it should be clearer how to configure various Assistant settings.

As an alternative, we now offer access to Anthropic models in the Assistant (currently gratis) without the need to configure your own API key.  Just login to Zed with your GitHub (upper right hand corner) and away you go.
