### ISSUE TITLE
Support cargo-binstall install to linux

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#14641]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi would love to use cargo binstall to install zed-editor
I think its easy  to implement 
https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md

**Comment by notpeter** [comment]
I'm not sure this is a great match for our current distribution methods. Our release artifacts for both Linux and MacOS are not just a simple static binary, they are a directory (`zed.app`) which contains compiled dynamic libraries, icons, the zed binary and the zed-editor daemon.

My understanding is that a normal `cargo install` only supports installing binaries with no bundled dynamic libraries and I believe `cargo-binstall` is similarly limited. Additionally, cargo-binstall doesn't support extracting the MacOS dmgs of our releases either.

I had never heard of `cargo-binstall`, but it sounds sounds interesting.  Thanks for the suggestion.
