### ISSUE TITLE
Makefile outline

### ISSUE THREAD

**Issue by bersace** [zed-industries/zed#14644]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

Thanks for zed. It's awesome !

File structure outline is empty for Makefiles. I suggest to list make rules in outline drawer.

Running Zed 0.143.7, Make v1.0.1.

Regards,
Étienne

**Comment by Angr1st** [comment]
This issue belongs on the [zed-make](https://github.com/caius/zed-make) issue tracker, I guess. Someone would need to add the missing outline.scm query to fix this issue.

**Comment by Angr1st** [comment]
To fix this issue we need to fix this [one](https://github.com/caius/zed-make/issues/9)

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/caius/zed-make/issues/9
