### ISSUE TITLE
Example on docs site breaks vim mode

### ISSUE THREAD

**Issue by ceuk** [zed-industries/zed#14663]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There's an example of how to enable sub-word jumping on the site:

```json
  {
    "context": "VimControl && !menu",
    "bindings": {
      "w": "vim::NextSubwordStart",
      "b": "vim::PreviousSubwordStart",
      "e": "vim::NextSubwordEnd",
      "g e": "vim::PreviousSubwordEnd"
    }
  },
```

However, when this is added, various vim motions cease to work (e.g. interacting with text objects with motions such as `caw`)

### Environment

Arch Linux

**Comment by mrnugget** [comment]
Can you try this?

```json
[
  {
    "context": "VimControl && !menu && vim_mode != operator",
    "bindings": {
      "w": "vim::NextSubwordStart",
      "b": "vim::PreviousSubwordStart",
      "e": "vim::NextSubwordEnd",
      "g e": "vim::PreviousSubwordEnd"
    }
  }
]

```

I think that fixes it.

**Comment by NathanLovato** [comment]
This issue can be closed; it's been resolved, the docs now list the example of mrnugget, and it does preserve text object operations like `caw`.
