### ISSUE TITLE
Add Key binding resolver function like emacs `describe-key`

### ISSUE THREAD

**Issue by 1925381584** [zed-industries/zed#14677]
### Check for existing issues

- [X] Completed

### Describe the feature

How can zed find the corresponding function from the shortcut key in the current panel? when i in emacs,i can find the function from the shortcut key, and i think Self-explanation is one of the best features of emacs. now in zed only support find function from function name, Do you have any plans to add this feature to zed and even more?

**Comment by notpeter** [comment]
Are you talking about discovering the name of a Zed action for a given keyboard shortcut? Like emacs' "Help: Where is?" `ctrl-h w` or Atom's "Key binding resolver".

<img width="698" alt="Screenshot 2024-07-19 at 15 14 57" src="https://github.com/user-attachments/assets/a8f6f959-ee07-4e15-b8d7-2eb6ea815a57">

Or are you talking about something else (finding a function definition in your own code base?)

**Comment by 1925381584** [comment]
What I'm trying to get at is the ctrl-h k operation in emacs.

**Comment by ConradIrwin** [comment]
You can now do this with `debug: Open Key Context View`. Type a key and it will show you what matched.
