### ISSUE TITLE
Cannot download any extensions

### ISSUE THREAD

**Issue by brenfwd** [zed-industries/zed#14699]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't download any extensions in Zed. I get a timeout error in Zed.

When I try to visit the API in the browser to download an archive, I get this when visiting `https://api.zed.dev/extensions/make/download`:

![image](https://github.com/user-attachments/assets/f27135ea-e6dd-422c-99d7-2be91a4794d7)

_`Execution Error: error returned from database: could not serialize access due to read/write dependencies among transactions`_

I can successfully download an extension in the browser using
`https://collab-staging.zed.dev/extensions/make/download`

### Environment

Zed: v0.144.3 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 58.7 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-17T20:51:43.28633431-04:00 [INFO] installing extension make latest version
2024-07-17T20:51:48.29503476-04:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-07-17T20:51:48.295124147-04:00 [ERROR] error downloading extension: request or operation took longer than the configured timeout time
</pre></details>

**Comment by tonyarnold** [comment]
I'm seeing this as well on macOS.

**Comment by JosephTLyons** [comment]
cc: @maxdeviant

**Comment by maxdeviant** [comment]
Is this issue intermittent?

I'm not able to reproduce by going to `https://api.zed.dev/extensions/make/download` in my browser. For me it downloads an `archive.tar.gz` successfully.
