### ISSUE TITLE
when soft_wrap preferred_line_length ,Accidental line breaks during narrow windows don't respect the setting

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#14700]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The status quo is a manifestation of conformity with [soft_wrap add bounded #8164](https://github.com/zed-industries/zed/issues/8164),The width of the line break is now the minimum of the window width and the line length, and this does not respect the setting of the.

https://github.com/user-attachments/assets/f628e104-5400-41f8-8669-47dfca23ace7

### Environment

Zed: v0.145.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
this current is intend behaviour, hit [here](https://github.com/zed-industries/zed/blob/eb7fe5745363b7b0f9fb1a5bd863c7a5ac5af3c2/crates/editor/src/element.rs#L4729). Don't known if zed teams want change it.

**Comment by notpeter** [comment]
> The status quo is a manifestation of conformity with #8164, The width of the line break is now the minimum of the window width and the line length, and this does not respect the setting of the.

@0x2CA I'm not able to grasp this.  Could you attempt to edit your description to expand/explain further?

**Comment by 0x2CA** [comment]
@notpeter 

In general, there are several needs for soft wrap that
1. no soft wrap.
2. Specify the width for soft wrap.
3. soft wrap according to the width of the window.
4. Specify the width and the minimum value of the window width for soft wrap.

in zed 
1. `"soft_wrap": "none"`
2.  ` `
3. `"soft_wrap": "editor_width"`
4. `"soft_wrap": "preferred_line_length" ` and `"soft_wrap": "prefer_line"`

As I understand it, `"soft_wrap": "preferred_line_length" ` should be the second type, and the status quo should be given a new name, `"soft_wrap": "bounded" `.
