### ISSUE TITLE
Navigation options don't work on Ubuntu

### ISSUE THREAD

**Issue by antonTroyan** [zed-industries/zed#14717]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have:
- Ubuntu 22.04.4 LTS
- Zed 0.144.3 (installled by script `curl -f https://zed.dev/install.sh | sh`)
- Zed automatically install java extension

Issue: All navigation options (from Rename Symbol to Code Actions) on right click don't work in Java code. 

In logs see a lot of `[WARN] Unknown button press: ButtonPressEvent { .. }`

### Environment

This stuff also doesn't work. Just no result in clipboard after executing command

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
From a quick glance, it seems that the `Java` extension does not come bundled with any language servers, so it seems like a deficiency of the extension:

https://github.com/zed-extensions/java/blob/main/extension.json

It looks like there is another java extension, `Java with Eclipse JDTLS`, which looks to ship language server support - you could give that a try:

https://github.com/ABckh/zed-java-eclipse-jdtls

**Comment by antonTroyan** [comment]
Tried to open zed: open default settings to change extension. But nothing was opened 
From Palette almost all commands doesnt work. Except stuff like zed: quit, it works

[Zed.log](https://github.com/user-attachments/files/16362637/Zed.log)

**Comment by antonTroyan** [comment]
Yeah. After some updates I can open extensions panel and changed to https://github.com/ABckh/zed-java-eclipse-jdtls
Now its woks
