### ISSUE TITLE
bug(tab icons): uneven padding

### ISSUE THREAD

**Issue by jbergstroem** [zed-industries/zed#14711]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Due to how the default state of a tab looks (hidden close), the padding when an icon is drawn seems uneven:
<img width="528" alt="Screenshot 2024-07-18 at 7 53 22 AM" src="https://github.com/user-attachments/assets/de19404d-1859-4236-a5d7-8bf80a0b1cfb">

State with close icon drawn:
<img width="232" alt="Screenshot 2024-07-18 at 7 54 26 AM" src="https://github.com/user-attachments/assets/486b076f-d38c-4ad6-8431-ea30963ba9fe">

### Environment

Zed: v0.145.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I think additional padding should be added on the right side of the icon to equal the left side at the non-hover state.

**Comment by konstantinzolotarev** [comment]
I can also add that file icons are a little bit upper than filename (more space from bottom). Not sure if it's intended to be so, but seems a bit weird 
![Screenshot 2024-07-22 at 12 26 58](https://github.com/user-attachments/assets/701aedb5-ae57-40b9-8251-982f3b6a43c8)

**Comment by fazibear** [comment]
Placing icons on right when close button is on left is on purpose? 

Terminal tab behaves differently.

![image](https://github.com/user-attachments/assets/7368b97d-1584-49c1-8438-e6373813e2e3)

**Comment by CurbaiCode** [comment]
I agree with [fazibear](https://github.com/fazibear), it would make sense if the icon appeared on the left like the terminal tab.

**Comment by jbergstroem** [comment]
I think this changed recently. It looks much better now:
<img width="397" alt="Screenshot 2024-08-23 at 4 58 36 PM" src="https://github.com/user-attachments/assets/4bd0b1f9-0277-464f-b93e-f7da86d7282a">


..perhaps open a separate issue for the terminal icon?
