### ISSUE TITLE
Python Syntax Highlighting for `t | None` is incorrect

### ISSUE THREAD

**Issue by ataractic** [zed-industries/zed#14715]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Screenshot from 2024-07-18 10-25-31](https://github.com/user-attachments/assets/60ce2f79-240d-4f27-9b4c-5a376d48da10)

When writing python code, some types are highlighted in a specific color (here blue), but only sometimes: the parameters `lidx`'s and `ridx`'s `int` type hints remains uncolored.

### Environment

Zed: v0.144.3 (Zed)
OS: Linux Wayland ubuntu 22.04
Memory: 15.3 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
I think this is an issue with [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python) it appears to parse this minimal repro case the same as Zed:
<img width="381" alt="image" src="https://github.com/user-attachments/assets/24210e0f-ff81-4ed4-a462-1f0d42fa8463">

<img width="463" alt="Screenshot 2024-07-25 at 10 50 43" src="https://github.com/user-attachments/assets/55cc71c2-1846-42ce-b849-2494473e443f">

Github highlighting is also based on tree-sitter-python and shows the same:
```python
def __init__(lidx: int | None = None):
    pass
```
