### ISSUE TITLE
Using /dev/stdin for an external formatter will empty the buffer on formatting

### ISSUE THREAD

**Issue by konstantintutsch** [zed-industries/zed#14716]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When configuring an external formatter and using `/dev/stdin` instead of `-` as input, the buffer will be emptied.

This configuration snippet lead to the issue.

```json
"languages": {
    "C": {
        "formatter": {
            "external": {
                "command": "indent",
                "arguments": [ "/dev/stdin", "-linux", "-nut", "-i4", "-o", "/dev/stdout" ]
            }
        }
    }
}
```

A short summary of the arguments:
- `/dev/stdin`: input for the formatter
- `-linux`: same styling as code in the Linux kernel
- `-nut` and `-i4`: indentation with 4 spaces
- `-o /dev/stdout`: output to stdout

This configuration snippet works and will format the buffer instead of emptying it, with practically the same input. (`/dev/stdin` was replaced with `-`)

```json
"languages": {
    "C": {
        "formatter": {
            "external": {
                "command": "indent",
                "arguments": [ "-", "-linux", "-nut", "-i4", "-o", "/dev/stdout" ]
            }
        }
    }
}
```

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland fedora 40
Memory: 30.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here's a demonstration of the two configurations, working and not working.

https://github.com/user-attachments/assets/856de08c-51b0-4447-96ef-20a533ab11da

**Comment by notpeter** [comment]
Can you confirm `/dev/stdin` is supported by your version of indent (it throws an error for me on GNU Indent 2.2.12).

<img width="802" alt="image" src="https://github.com/user-attachments/assets/c7ab4fef-ff8c-4815-85df-17987e6a6103">

Also, specifying `-o /dev/stdout` to GNU indent is incorrect. No only does indent default to stdout, but if you want to explicitly specify stdout the option is `-st`.

**Comment by konstantintutsch** [comment]
I'm getting the same error with GNU Indent 2.2.13. Looks like this issue is not related to Zed.

Thank you for correcting me on outputting to stdout with GNU Indent!
