### ISSUE TITLE
In .vue files don't work autocomplete

### ISSUE THREAD

**Issue by klyuk88** [zed-industries/zed#14723]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Autocomplete does not work in VUE files. It only works in TS files.

### Environment

Zed 0.144.3
MacOS 14.5 M1 Pro
Vue 3 + Vite project

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/db0dfc1d-d1c9-47d2-b440-ad342b7da2b2

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16280980/Zed.log)

**Comment by fazulk** [comment]
Noticed the same thing, also jump to file no longer working. Would like to see a full setup up zed actually working with vue and TS.

**Comment by maxdeviant** [comment]
@klyuk88 Could you try this with v0.1.0 of the Vue extension and see if that improves anything?

Also, if anyone is able to reproduce the issue in a project that they're able to share with the Zed team, it would be very helpful in diagnosing the issue.

**Comment by danulqua** [comment]
@maxdeviant here is a repo where the problems can be reproduced: https://github.com/danulqua/vue-universities-parser

Not working:
- Autocompleting words;
- Command+click components in the template to go to the definition;
- Writing component names in the template to get suggestions for importing them.

And, maybe, some other issues which doesn't exists, for example, in VSCode/WebStorm.

**Comment by maxdeviant** [comment]
> @maxdeviant here is a repo where the problems can be reproduced: https://github.com/danulqua/vue-universities-parser

Is this repo private? I get a 404 when I try to view it.

**Comment by fazulk** [comment]
@maxdeviant you can try this one, basic boilerplate from vue 

https://github.com/fazulk/vue-zed-demo

**Comment by danulqua** [comment]
> Is this repo private? I get a 404 when I try to view it.
@maxdeviant should be okay now

**Comment by klyuk88** [comment]
@m

> > @maxdeviant here is a repo where the problems can be reproduced: https://github.com/danulqua/vue-universities-parser
> 
> Is this repo private? I get a 404 when I try to view it.



> with v0.1.0

Not working yet, also with v0.1.0 vue extension.

**Comment by fazulk** [comment]
Just following up - From what I can tell "Reveal Definition" works correctly, but "Go to Definition" is broken. 

Its broken when trying to jump to another file, and its broken when trying to go to a definition within the same file.  

@maxdeviant If I was to debug this, where in Zed src is the best place to look?

**Comment by vanarok** [comment]
"Go to definition" works for component props, but not for the components themselves in the template tag.

**Comment by owaisahmad-dev** [comment]
Hey, also facing the same issue, it's the only blocker left for to switch to zed, my current job is a lot of vue.js and typescript

**Comment by danulqua** [comment]
Agree, very important feature that doesn't work

**Comment by owaisahmad-dev** [comment]
> Hey, also facing the same issue, it's the only blocker left for me to switch to zed, my current job is a lot of vue.js and typescript

BTW, was also facing this issue in VS Code, reverted to a previous version of the Vue.js extension, and it works fine now. Maybe it's a bug from vue.js LSP side. Don't see a way how I can do that in Zed

**Comment by fazulk** [comment]
would say this can be closed thanks to https://github.com/zed-industries/zed/pull/16654

**Comment by Moshyfawn** [comment]
Based on the previous user's feedback, I'll be closing this issue. Please feel free to open a new ticket if you encounter any other problems.
