### ISSUE TITLE
zed does not start - vulkan err

### ISSUE THREAD

**Issue by asuka-405** [zed-industries/zed#14758]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried building zed from source through
yay -S zed-git
and installing it using the bootstrap script provided as well

im getting a vulcan error even though i dont even have a graphics card but an AMD APU

error - 
error opening [PathLikeWithPosition { path_like: "/home/suryansh", row: None, column: None }]: VulkanError(ERROR_INCOMPATIBLE_DRIVER)

i have amdvlk installed

My zed log file - [Zed.log.txt](https://github.com/user-attachments/files/16286908/Zed.log.txt)

### Environment

OS: Arch Linux x86_64 
Kernel: 6.9.9-arch1-1 
Shell: zsh 5.9 
DE: Plasma 6.1.2 
WM: kwin 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 2323MiB / 17933MiB 

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
@asuka-405 https://zed.dev/docs/linux#zed-fails-to-open-windows has some debugging steps.

Does `vkcube` work for you?

**Comment by asuka-405** [comment]
It didnt
I had the amdvlk files (at some location chatgpt told me should ensure vulkan installation, skill issues)
After i installed vulcan icd (that vkcube was asking me to install) - vulkan-icd-loader lib32-vulkan-icd-loader vulkan-radeon lib32-vulkan-radeon
Its working now

Thanks for the help

**Comment by asuka-405** [comment]
Solution that worked for me, installing following packages that are part of Vulkan ICD:

vulkan-icd-loader lib32-vulkan-icd-loader vulkan-radeon lib32-vulkan-radeon
