### ISSUE TITLE
Recognize "using" as a keyword in Typescript

### ISSUE THREAD

**Issue by matthieusieben** [zed-industries/zed#14762]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `using` [keyword](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html) is not recognized as one in Js/Ts.

### Environment

Zed: v0.144.3 (Zed)
OS: macOS 14.5.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="506" alt="Capture d’écran 2024-07-18 à 12 16 02" src="https://github.com/user-attachments/assets/47160b41-00a7-45f9-b57c-058c9d0a7be3">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by versecafe** [comment]
@matthieusieben Should be resolved now but you can wait for the newest nightly release to come out or build for yourself to check (also patched it for TSX files)

**Comment by JosephTLyons** [comment]
Since it looks like @versecafe's PR has been merged, I'm going to close this out! Thanks!
