### ISSUE TITLE
"Y" should yank to end of line

### ISSUE THREAD

**Issue by amer** [zed-industries/zed#14771]
### Check for existing issues

- [X] Completed

### Describe the feature

In Zed Editor's vim mode, the "Y" command currently does not behave as expected in standard Vim. The desired behavior is for "Y" to yank from the cursor position to the end of the line, consistent with Vim's functionality.

**Comment by vbhavsar** [comment]
@ConradIrwin This can be closed.

**Comment by hortovanyi** [comment]
Hi ... shift y normally yanks the line. I've never seen 'Y" to tank to end of line. Its really stuffed my coding up

https://docs.oracle.com/cd/E19253-01/806-7612/editorvi-43/index.html

**Comment by ConradIrwin** [comment]
Maybe we should revert then :D. Seems like `nvim` is the outlier here: 

```
                                                 default-mappings
Nvim creates the following default mappings at startup. You can disable any
of these in your config by simply removing the mapping, e.g. ":unmap Y".

        nnoremap Y y$
        nnoremap <C-L> <Cmd>nohlsearch<Bar>diffupdate<Bar>normal! <C-L><CR>
        inoremap <C-U> <C-G>u<C-U>
        inoremap <C-W> <C-G>u<C-W>
        xnoremap * y/\V<C-R>"<CR>
        xnoremap # y?\V<C-R>"<CR>
        nnoremap & :&&<CR>
```

**Comment by hortovanyi** [comment]
All the vim enabled IDEs I've used and I think nvim to, have shift y mapped to line yank. Can we reopen and fix?

**Comment by AnsonH** [comment]
In case you still want to map `Y` to yank till end of line:

```json
[
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "shift-y": ["workspace::SendKeystrokes", "y $"],
  }
]
```

**Comment by nik-rev** [comment]
There's also a dedicated action for this:

```json
{
  "context": "VimControl && !menu",
  "bindings": {
    "shift-y": "vim::YankToEndOfLine"
  }
}
```
