### ISSUE TITLE
Working Tree

### ISSUE THREAD

**Issue by hsraktu17** [zed-industries/zed#14788]
### Check for existing issues

- [X] Completed

### Describe the feature

# Whatever changes we have made in precommited file should reflected side by side. 

## For example
![image](https://github.com/user-attachments/assets/a6885e3b-5776-4fee-97d0-deb9f7177951)

To provide easy way to revert back the changes

**Comment by notpeter** [comment]
I think this is duplicate of these:
- https://github.com/zed-industries/zed/issues/4367
- https://github.com/zed-industries/zed/issues/4523

You can also follow an overview here:
- https://github.com/zed-industries/zed/issues/8665

Please subscribe to those issues to track their progress and vote 👍 to increase visibility. Thanks for reporting.
