### ISSUE TITLE
Multiple documentation windows are shown after upgrading to v0.145.0 (Zed Preview)

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#14790]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Multiple documentation windows are shown.

<img width="357" alt="image" src="https://github.com/user-attachments/assets/002208f4-cfd9-4e77-8b2c-8914cfca9cd5">

### Environment

Zed: v0.145.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
I have a hunch this is the same bug as:

- https://github.com/zed-industries/zed/issues/14161

**Comment by JosephTLyons** [comment]
@failable, can you show your settings.json file contents to me? I have a feeling a setting tweak like this will fix your issue:

- https://github.com/zed-industries/zed/issues/14161#issuecomment-2246291300

**Comment by failable** [comment]
I tried this setting

```
{
      "language_servers": ["!pyright", "basedpyright", "ruff"],
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "pyformat",
          "arguments": ["-"]
        }
      }
    }
```

But it does not work. Though the `basedpyright` is [not merged](https://github.com/zed-industries/extensions/pull/1080) yet.

**Comment by m1guer** [comment]
because is to merged yet you need download the extension in you machine and then install  by "add dev extension"

**Comment by failable** [comment]
@m1guer I mean, even I disable `pyright`, two documentation popups are shown there.

**Comment by m1guer** [comment]
oh ok, I was thinking the error was related to the extension itself

**Comment by drcongo** [comment]
As far as I can work out it's not actually possible to disable pyright - certainly `!pyright` doesn't kill it for me in Zed Preview 0.146.1

**Comment by failable** [comment]
>  it's not actually possible to disable pyright 
@drcongo That might be the issue.
