### ISSUE TITLE
Incorrect html and django templates formatting

### ISSUE THREAD

**Issue by swayll** [zed-industries/zed#14802]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

When saving an html file with django template tags, the code is incorrectly formatted (prettified), which leads to code malfunction.
<img width="213" alt="Снимок экрана 2024-07-19 в 13 24 33" src="https://github.com/user-attachments/assets/8c8a7e6a-edf9-4345-92a3-48faa5af0d89">
<img width="359" alt="Снимок экрана 2024-07-19 в 13 24 52" src="https://github.com/user-attachments/assets/d713d837-f7c5-4822-9a19-f00f1ea09106">
I did not find the auto-formatting feature disabled in the settings. Please add it.

### Environment

Zed: v0.144.3 (Zed)
OS: macOS 13.6.7
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxdeviant** [comment]
You can disable formatting on save for individual languages in your settings.

If your Django templates are treated as HTML, this is what you would want to add:

```json
"languages": {
    "HTML": {
      "format_on_save": "off"
    }
  }
```
