### ISSUE TITLE
`auto update: view release notes` doesn’t do anything (`… locally` works)

### ISSUE THREAD

**Issue by sylbru** [zed-industries/zed#14813]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On my Linux Zed install (pre-beta, now on 0.146), the `auto update: view release notes` command doesn’t do anything. I always have to use `auto update: view release notes locally`, but I’m confused about the difference between these. Also currently the tab that opens is titled "Release Notes: Zed v0.144.3" so I’m confused. Is that all because I’m on a nightly channel?

### Environment

Zed: v0.146.0 (Zed Nightly 836f623800fce6a69341f7b2b9f5021763491882)
OS: Linux X11 linuxmint 21.2
Memory: 14.8 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment]
Hey @sylbru - the `auto update: view release notes` is supposed to open the release notes in your default browser. I added `auto update: view release notes locally` a while ago, hoping that it would supersede the former command, but our Markdown renderer still has some unpolished bits and so I never deprecated the former. Do you have any output in your logs (command palette > `zed: open logs`) when running the former?

**Comment by notpeter** [comment]
You were running Nightly, which doesn't have release notes (because it's just a point in time snapshot of main). 

With #17967 instead of a no-op, it will take you to the commit history for the most recent Nightly on GitHub.

**Comment by sylbru** [comment]
Sorry I forgot to report back on this! I switched to the regular release channel and indeed everything was fine!
