### ISSUE TITLE
remoting: opening settings/keymap broken

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#14810]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:
1. Open a remote project in Zed (single workspace open)
2. Press `cmd+,` or `cmd+k cmd+s` (settings or keymap)

Expected: settings.json or keymap.json opens
Actual: A new empty workspace opens, but without settings.json/keymap.json

Bonus steps:
1. Close that empty workspace.
2. Press `cmd+,` or `cmd+k cmd+s` (settings or keymap)
3. This time nothing happens.

### Environment

Zed: v0.146.0 (Zed Nightly 836f623800fce6a69341f7b2b9f5021763491882)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

**Comment by leviska** [comment]
also opening local settings for some reason decided to open `~/.config/zed/.zed/settings.json` instead of `{current_project}/.zed/settings.json`

**Comment by notpeter** [comment]
There are multiple settings:

- `.zed/settings.json` (per Project)
- `~/.config/zed/settings.json` (per User)
- compiled-in settings (global defaults)

"Local" means per User. I don't believe we have an action which spawns the project settings, but we do for "local settings" and "default settings".

Perhaps we need better language (e.g. Zed Global default settings, Zed User settings, Zed project settings?) to be consistent and more clearly communicate.

**Comment by leviska** [comment]
but opening local settings on my machine actually opens folder specific settings, and the comment (in both files, on remote in ~/.config and in local machine in {{folder}}) is
```
// Folder-specific settings
```

**Comment by leviska** [comment]
also user specific settings are just ignored on remote (i.e. settings on `remote:~/.config/...`)

**Comment by leviska** [comment]
I've updated to 1.146 preview and it seems fixed

**Comment by ConradIrwin** [comment]
Fixed by v0.159.x
