### ISSUE TITLE
REPL: some type of outputs overlap with the following line almost completely

### ISSUE THREAD

**Issue by pantheraleo-7** [zed-industries/zed#14855]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In [pyspark](https://spark.apache.org/docs/latest/api/python/), when creating a SparkSession or a SparkContext, the output it produces is just text but I guess it's asynchronous? So what happens is that the next line (potentially more?) gets completely hidden by the output. Happens on both the latest version of Zed & Zed Preview

Sample code to reproduce:
`from pyspark import SparkContext`
`spark = SparkContext()`
`line = 'not visible'`

run line1 and then 2, line3 will get hidden

### Environment

Zed: v0.145.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

Zed: v0.144.4 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/fc0506ea-92c7-4a5a-9bad-58cef19c77a9

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by pantheraleo-7** [comment]
@rgbkrk

**Comment by pantheraleo-7** [comment]
Just checked, it can hide more than 1 line if the output is big enough. One weird thing I noticed is that if the output is scrolled past just enough, the whole output overlay vanishes. Is that suppose to happen?


Uploading Screen Recording 2024-07-20 at 10.16.47 PM.mov…

**Comment by pantheraleo-7** [comment]
Also since this issue is about outputs, I might as well mention this (I'll file a separate issue if needed).
Sometimes when a given line is run multiple times, its output gets stacked. This mostly starts with error outputs stacking one below the other but the final successful error-less output gets stacked below them as well. This might just be specific to me, and the real problem is that outputs (error or otherwise) are getting stacked in general (for some other reason).

I'll edit this with a video showing the minimal reproducible example

**Comment by pantheraleo-7** [comment]
Outputs are getting stacked

https://github.com/user-attachments/assets/97f6fda7-a78a-4bb3-aed8-d82ceed679bb

**Comment by rgbkrk** [comment]
I tried to get to this one before launch and got a bit stuck with the pseudo-terminal implementation. It's high on my list of essential fixes and want to let you know I'm investigating.

**Comment by rgbkrk** [comment]
Closed by https://github.com/zed-industries/zed/pull/15713.

I've also got some new terminal rendering coming in _soon_.
