### ISSUE TITLE
Annoying sounds

### ISSUE THREAD

**Issue by 1925381584** [zed-industries/zed#14857]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The zed makes an annoying beep when a certain key is entered. Is there an option to turn it off

### Environment

win10

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
> when a certain key is entered

How are people supposed to reproduce this?
Please add more details — which file are you in, what are you pressing, etc.
Logs and videos are also very welcome, same as description of

> an annoying beep

it's not Zed's one so most probably comes out of your system.

> win10

To note, Windows is not officially supported yet, and only certain, few, external contributors deal with Windows code.
So most probably this will stay not fixed for a while.
As an idea, I would ensure that there are no Windows-specific bindings to the same "a certain key is entered".

**Comment by 1925381584** [comment]
<img width="343" alt="zed_kBUntjvac6" src="https://github.com/user-attachments/assets/55c84e92-7572-4fc5-90a7-cd9bb791eae0">
hi，like this,when i bing alt-x to this command, and i clicked alt-x,the command will be done,but also has the sound at the same time. Several of the commands I've bound have done this, and I think it should be easy to reproduce

**Comment by SomeoneToIgnore** [comment]
I wonder if that's what you're hitting.
https://support.microsoft.com/en-us/office/keyboard-shortcuts-for-international-characters-108fa0c1-fb8e-4aae-9db1-d60407d13c35

```
The Unicode character for the specified Unicode (hexadecimal) character code
	

The character code, ALT+X

For example, to insert the euro currency symbol , press 20AC, and then hold down the ALT key and press X.
```

So, you press something, then press alt-x and whatever was pressed before is attempted to be parsed as a Unicode character, invalid ergo the beep.

Have you tried changing the shortcut or repeating the same sequence of actions in, e.g. Notepad.exe?

**Comment by 1925381584** [comment]
Thanks for the answer, but that's not the case. I found that the alt key connected to any key comes out with this tone

**Comment by JunkuiZhang** [comment]
Windows treats the `alt + key` combination as a shortcut. If Windows thinks it is not properly handled, it will beep. I will create a PR to address this issue.

**Comment by JunkuiZhang** [comment]
Could you try #14872 ?

**Comment by JunkuiZhang** [comment]
> Do I need to close this issue?

No, it will be closed when the PR is merged.
