### ISSUE TITLE
Default formatter breaks HTML

### ISSUE THREAD

**Issue by 2n** [zed-industries/zed#14867]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The default formatter may break the HTML if the closing tags for `<li>` elements are omitted.
  
  
This is the original HTML source.

```html
<div>
  <ul>
    <li>item 1
    <li>item 2
      <ul>
        <li>nested 1
        <li>nested 2
      </ul>
    <li>item 3
  </ul>
</div>
```

This is the result of formatting.
It's broken.

```html
<div>
  <ul>
    <li>item 1</li>
    <li>
      item 2
      <ul>
        <li>nested 1</li>
        <li>nested 2</li>
      </ul>
  </ul>li>

    <li>item 3</li>
  </ul>
</div>
```

A single undo (Cmd+Z) will revert it to a correctly formatted state.
(However, the extra blank line is still there.)

```html
<div>
  <ul>
    <li>item 1</li>
    <li>
      item 2
      <ul>
        <li>nested 1</li>
        <li>nested 2</li>
      </ul>
    </li>

    <li>item 3</li>
  </ul>
</div>
```

### Environment

Zed: v0.144.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by versecafe** [comment]
```html
<div>
  <ul>
    <li>item 1
    <li>item 2
      <ul>
        <li>nested 1
        <li>nested 2
      </ul>
    <li>item 3
  </ul>
</div>
```
Isn't exactly proper HTML syntax, while it *CAN* render to the browser the behaviour could vary you really should be correctly closing your list items, following an XML like syntax is the best way to guarantee formatters will correctly work, the issue you are seeing comes from prettier itself being unsure of the correct behaviour as this is semi undefined the closing tag can only be omitted if followed by another `<li>` or an empty space, which is not true of item 2, for the source spec see W3 here https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#optional-tags

**Comment by 2n** [comment]
Thank you for your reply.

Shouldn't the formatter leave the code as it is if it cannot properly format it? 
What was renderable in the browser at least may become broken due to the default `format_on_save`, which can be a bad experience.

It is strange that undoing reverts it to a correctly formatted state.
Could this be a bug in the editor?

**Comment by versecafe** [comment]
@2n really it's a bug in [prettier](https://prettier.io/) *the formatter zed is using for JS, TS, TSX, Astro, Vue and a few others*, it won't format if it can't by default if you throw a syntax error in you can test it yourself. The issue comes when you have *questionable* html, technically the fact it renders in the browser is a bug as it's not spec compliant but HTML unlike XHTML doesn't have a proper syntax parser so it always renders *something* with whatever fallback the browser developer decided

**Comment by notpeter** [comment]
Yeah, this sounds like a bug in how prettier handles this ambiguous HTML.  You can disable `format_on_save` for HTML by adding the following to your settings.json:

```
  "languages": {
    "HTML": {
      "format_on_save": "off"
    }
  },
```
