### ISSUE TITLE
Linux lock screen recovery interface disappears

### ISSUE THREAD

**Issue by ZeroHawkeye** [zed-industries/zed#14868]
### Check for existing issues

- [X] Completed

### Describe the feature

- After the Linux lock screen is restored, the interface disappears, but the mouse can be clicked normally. I have encountered this situation before in Ubuntu. My current environment is: wayland, kde6, arch linux

### If applicable, add mockups / screenshots to help present your vision of the feature

![tmp](https://github.com/user-attachments/assets/652f9ad5-bce9-4191-aed2-8594b89e5b25)

**Comment by mateossh** [comment]
Similar thing happens on macOS after waking from sleep. Entire interface hangs, but buffers can be scrolled. Just need to minimize and unminimize windows to start rendering.

**Comment by ZeroHawkeye** [comment]
But under Linux, minimizing and restoring the window will not restore the view to normal, it will always be like this

**Comment by ZeroHawkeye** [comment]
> Similar thing happens on macOS after waking from sleep. Entire interface hangs, but buffers can be scrolled. Just need to minimize and unminimize windows to start rendering.

But under Linux, minimizing and restoring the window will not restore the view to normal, it will always be like this

**Comment by JosephTLyons** [comment]
@mateossh, I think this is the same as

- https://github.com/zed-industries/zed/issues/12827

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Comment by ZeroHawkeye** [comment]
Oh my god, I found another problem because of this file. For example, if you put this file in the Desktop directory and use zed to open this directory without opening this json file, it will still get stuck. The system I use is arch linux, memory: 32 GB CPU: i9-14900HX
