### ISSUE TITLE
Can not open files with file picker - xdg-desktop-portal implementation missing

### ISSUE THREAD

**Issue by mikkurogue** [zed-industries/zed#14874]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When trying to open the file picker to open a file or project, this error shows up: 
![image](https://github.com/user-attachments/assets/9e07addc-f267-4f5c-a9fd-dbef1d661541)

After clicking the link, it goes to the docs but the entry is empty, see this link: [Zed Docs](https://zed.dev/docs/linux#i-cant-open-any-files)

I tried re-installing the following:
`xdg-desktop-portal-wlr`
`xdg-desktop-portal-gtk`
`xdg-desktop-portal-hyprland` (also tried `xdg-desktop-hyprland-git`)

Tried it in something like VScode and that did open my file picker as expected (see below)

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland arch unknown
Memory: 31.2 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Added vscode example: 
![image](https://github.com/user-attachments/assets/ef933a61-7c9a-4d53-b4b0-afa36a715457)

Zed full view of editor with error:
![image](https://github.com/user-attachments/assets/3ad3a62b-b37e-42ba-816f-2880d89b133b)

XDG desktop portal hyprland service running:
![image](https://github.com/user-attachments/assets/417af941-4e67-4a68-8999-56fa3026da5b)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Mis-nomer** [comment]
I suggest going through Arch's [XDG_Desktop_Portal](https://wiki.archlinux.org/title/XDG_Desktop_Portal) documentation and pick the backend that has a file chooser. `xdg-desktop-portal-wlr` and `xdg-desktop-portal-hyprland` doesn't have one, so adding [xdg-desktop-portal-lxqt](https://archlinux.org/packages/?name=xdg-desktop-portal-lxqt) to the mix worked for me.

**Comment by mikkurogue** [comment]
Ah this seems to do the trick, thanks very much! I knew it had to be something "simple" like this, but after scouring arch, hyprland and zed docs for donkeys I couldn't see the trees for the forest it seems.

**Comment by musjj** [comment]
Wait, can this be re-opened? I can open a file picker in Firefox, Chrome, VS Code and pretty much every other graphical apps on my system (both in XWayland and native Wayland) without any additional configuration.

IMO, Zed shouldn't require the user to install additional desktop portals just so they can have a functioning file picker, so this sounds like a bug to me.

**Comment by christophberger** [comment]
@notpeter I'd second @musjj's request. Great software like Zed should make a great first impression on the user.

**Comment by apricotbucket28** [comment]
Zed *does* support a fallback file picker when the portal isn't available. See https://github.com/zed-industries/zed/pull/14524

**Comment by christophberger** [comment]
Thank you for clarifying. It turned out that my package manager does not offer the latest Zed version. I'll try to get hold of the latest version

**Comment by IGN-Styly** [comment]
tried everything including various hacks, nothing works i call this a regression. Because it worked.

**Comment by nms-scribe** [comment]
Although @F8RZD 's instructions didn't apply to my situtation, I did learn an important part of the installation process to get this to work. After installing your portal of choice, you may need to run the following:

```
systemctl --user restart xdg-desktop-portal
```

I do agree with @musjj however, that zed shouldn't require this separate step to install. This is the first application I have ever installed where the file picker didn't just work.

**Comment by mikkurogue** [comment]
@nms-scribe Agreed, however I did have a similar issue with some other apps that uses file pickers too (Firefox, oddly enough) when using hyprland but not the xdph portal. This was at the time Zed has the same issue for me too, which but the Firefox one "fixed" itself once xdph was installed. Zed eventually started working once I also had dolphin setup properly etc alongside the desktop portals

**Comment by chris-morgan** [comment]
I’m just trying out Zed. I’m encountering this problem, despite having a fully-functional xdg-desktop-portal setup (being used by at least one app for years). I’m on current Arch Linux, sway 1:1.10-1, zed 0.170.2-1, xdg-desktop-portal 1.18.4-2, xdg-desktop-portal-wlr 0.7.1-1, user xdg-desktop-portal service running.

I don’t know if it’s linked, but I’m also having an awful time just trying to create a file—Vim mode, I’d expect `:e ~/.config/zed/themes/something.json` or `:new` and `:w ~/.config/zed/themes/something.json` to achieve the desired result, but had to instead open one of the directories as a project or some such thing. (I’m not used to such workflows, being strictly a Vim user hitherto, so I don’t know if that’s normal, or what.) Don’t know if that stuff warrants a new issue, or if it could be directly caused by this.

**Comment by Hman15** [comment]
![Image](https://github.com/user-attachments/assets/5fe95960-567b-47d8-aee5-c3597b0e6d15)

I have a functioning file picker and the popup still shows up. Zed should just have an open to ignore it forever

**Comment by guilhermegalabarof** [comment]
I have installed zed in my arch+hyprland, it give me the same message of OP
every other application can use my file picker, except zed.
in browser(zen), control+o open nautilus, why not zed does the same?

**Comment by notpeter** [comment]
> Zed should just have an open to ignore it forever

```json
  "use_system_path_prompts": false,
```

**Comment by chouzan** [comment]
I also use Hyprland. I wish I could explain why this happens, but I can't. I only know what solved it for me: moving my `xdg.portal` config from the NixOS module to the home-manager module. This way I don't need to make any systemd override or edit any Zed config. Having the config in the NixOS module doesn't actually install the appropriate portal backends via the `xdg.portal.extraPortals`, hence the error. Perhaps it's a bug on the NixOS side?

**Comment by codayon** [comment]
I was having this issue on AwesomeWM while the file picker in firefox worked fine. After doing some tinkering I figured out that, my system was missing the critical session variables, `DISPLAY` `XDG_CURRENT_DESKTOP` `XDG_SESSION_TYPE`.
