### ISSUE TITLE
inline_assistant: Tabs are overwritten with space characters when first line in selection has no indentation

### ISSUE THREAD

**Issue by arturhoo** [zed-industries/zed#14885]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:

1. Open a go project that uses tabs, for example https://github.com/samber/lo
2. Trigger the inline assistant while selecting a function with no indentation in the first line of the selection
3. Observe that the suggestions replace tabs with spaces

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/c94c11f7-26b8-4d79-a873-86d1202227a1">

### Environment

Zed: v0.145.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
This should be included in Zed [v0.146.0-pre](https://zed.dev/releases/preview/0.146.0).
