### ISSUE TITLE
Typo on the Zed website

### ISSUE THREAD

**Issue by Bamboooz** [zed-industries/zed#14909]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Typo on the zed 404 page, "We couldn't find the page you were looking for. If you think is an error, you can let us know", it should be "If you think it is an error, you can let us know."

### Environment

-

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![obraz](https://github.com/user-attachments/assets/8320a71f-76f6-4e7c-a869-767b391f2931)
![obraz](https://github.com/user-attachments/assets/5bc82a0e-ddba-4b6a-af94-0dcd1ed57e4b)

### If applicable, attach your Zed.log file to this issue.

-

**Comment by maxdeviant** [comment]
Thanks for reporting this, @Bamboooz!

This typo is fixed now.
