### ISSUE TITLE
How disable auto-compile for Rust-lang extention? 

### ISSUE THREAD

**Issue by GildedHonour** [zed-industries/zed#14930]
### Check for existing issues

- [X] Completed

### Describe the feature

The Rust-lang support  feature or extention, whichever it be compiles the code in background, after every change, all the time. How to disable this?

Does Zed support overwritting functionality of an extention with the rules of the higher priority?

**Comment by JosephTLyons** [comment]
Hey @GildedHonour, I think this is what you are looking for - add this snippet to your settings.json file:

```json
"lsp": {
  "rust-analyzer": {
    "initialization_options": {
      "checkOnSave": false,
    },
  }
}
```

**Comment by JosephTLyons** [comment]
I've tested this and it seems to work on my end, so I'm going to close this out. Feel free to let me know if it isn't working for you and we can go from there.

**Comment by GildedHonour** [comment]
@JosephTLyons how about other languages? Let's say, JS, Python.
