### ISSUE TITLE
Ctrl+W does not work to close Task panel

### ISSUE THREAD

**Issue by megatux** [zed-industries/zed#14934]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Doing right click and selecting the "Close    Ctrl+W" context menu option works but the keyboard shortcut do not.

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland nobara 40
Memory: 31.2 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment]
Hey @megatux, just for clarity, are you referring to the tab that holds the `tasks.json` file after running `zed: open tasks`?

**Comment by megatux** [comment]
Hi @JosephTLyons , the pane I'm referring is the bottom pane that opens when running a task already defined. This one:

![Captura desde 2024-07-24 09-48-45](https://github.com/user-attachments/assets/a4b3a17d-5d35-4ff3-b3c6-7b729bd56429)
 
The context menu says that Ctrl+W close the pane but it does nothing so I have to use always the menu with mouse Thx!

**Comment by BaptisteRoseau** [comment]
@megatux  If you are using Vim motions the keybinding is overridden by Vim. I had the same problem and fixed it in the config with the following:

```json
    {
        "context": "(VimControl && !menu) || vim_mode == insert",
        "bindings": {
            "ctrl-d": ["editor::SelectNext", { "replace_newest": false }],
            "ctrl-w": "pane::CloseActiveItem"
        }
    }
```

Works with any shortcut that have been overridden by vim motions.

**Comment by megatux** [comment]
@BaptisteRoseau nope, nothing vim related installed.
But found that Ctrl+Shift+W works fine to hide the panels (like the terminal).
If Shift key is always required, maybe update the label to include _Shift_ .

Regards

**Comment by omegaatt36** [comment]
Hi @megatux,

I encountered the same issue. In the end, I didn't want to use ctrl+shift+w to close the task panel, so I added a configuration in keymap.json to set ctrl+w as the close button for the task panel when we're in the terminal panel.

I've added the following to my keymap.json:

```
{
  "context": "Terminal",
  "bindings": {
    "ctrl-w": "pane::CloseActiveItem"
  }
}
```

I'll remove this custom keymap if there's an official update addressing this issue in the future.

**Comment by megatux** [comment]
I'd prefer to keep _Ctrl+W_ as the normal Linux terminal shortcut to _cut-word-to-the-left_ and rename the menu label shortcut to the one it works, _Ctrl+Shift+W_ .

**Comment by omegaatt36** [comment]
@megatux 
Oh thanks, when I use Alacritty on Linux, I typically use Ctrl+Delete to delete a word backwards, but for some reason, it 
doesn't delete anything in Zed. Thank you for providing me with a method to achieve what I wanted to do.
