### ISSUE TITLE
Panel button hover tooltips not working properly

### ISSUE THREAD

**Issue by hanmingk** [zed-industries/zed#14938]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I hover over an already opened panel button, the hover tooltip does not appear.
In version 0.143.7 it can be displayed normally.
![Screenshot from 2024-07-22 08-53-49](https://github.com/user-attachments/assets/d5cd3a11-bf48-41d9-aee5-4cc60cee2d06)
But in the latest version it is not showing.
![Screenshot from 2024-07-22 08-56-28](https://github.com/user-attachments/assets/90ad6573-4a4b-4388-9e2e-19cb0871cbc9)

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland Ubuntu 24.04
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I can reproduce this on MacOS too. It broke between `0.143.7` and `0.144.0` but I haven't done the full bisect yet.
