### ISSUE TITLE
[Linux] Some Key bindings like Ctrl + O does not work in editing window

### ISSUE THREAD

**Issue by tzabbi** [zed-industries/zed#14947]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Maybe I miss someting but I have some issues with Zed with key bindings. For example when the focus is in the editing window and I press "Ctrl + O" (Open a new project) no windows pops up with a context which ask me which directory I want to open. When I focus on the termnal section of zed the key binding works as expected.

Im running zed on Linux on Fedora and Ubuntu and on both systems the issue occures.

### Environment

Linux Ubuntu 22.04 and Fedora 40

Zed Version: 0.144.4 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
OH, this might actually explain some of the other recent reports about the Open File action not working.

**Comment by notpeter** [comment]
@tzabbi Are you using vim bindings?

I think the ctrl-o defined in the global context:
https://github.com/zed-industries/zed/blob/7fb906d774683bcef54da924ed8b8bf5feac0695/assets/keymaps/default-linux.json#L26

Is being overriden by the vim `ctrl-o` (back / "goto Old") in the `VimControl && !menu` context:

https://github.com/zed-industries/zed/blob/7fb906d774683bcef54da924ed8b8bf5feac0695/assets/keymaps/vim.json#L65-L66

I'd be willing to bet the default bind for `ctrl-i` is broken there too:
https://github.com/zed-industries/zed/blob/7fb906d774683bcef54da924ed8b8bf5feac0695/assets/keymaps/default-linux.json#L100

**Comment by tzabbi** [comment]
Yes im using vim mode. This will explain my issue. But I don't like it. It is possible to create another keybinding for opening project?

**Comment by notpeter** [comment]
> Yes im using vim mode. This will explain my issue. But I don't like it. It is possible to create another keybinding for opening project?

Yes, you can easily create a [custom keybinding](https://zed.dev/docs/key-bindings) by putting something like the following in your `~/.zed/config/keymap.json

```json
[
  {
    // global keybinding (no context)
    "bindings": {
      "ctrl-alt-o": "workspace::Open"
    }
  }
]
```

**Comment by tzabbi** [comment]
I see that ctrl-k + crtl-o works all the time.
