### ISSUE TITLE
[linux] Add copy as an option in zed terminal 

### ISSUE THREAD

**Issue by sidharthpunathil** [zed-industries/zed#14957]
### Check for existing issues

- [X] Completed

### Describe the feature

* I feel like the Copy is missing from the options
* Similar to Clear and Close

![image](https://github.com/user-attachments/assets/303468b1-5a6e-4e4d-82ba-56eb00f5d5a0)

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/14828 had fixed that, comes with Zed Preview 0.146 next Wednesday.
