### ISSUE TITLE
Ability to switch panels via Ctrl + h/j/k/l

### ISSUE THREAD

**Issue by metallerok** [zed-industries/zed#15020]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm trying to set up changing panels via
```json
  {
    "context": "Dock",
    "bindings": {
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]

    }
  }

```
But it works very strangely. If i press `ctrl-h` it activates search panel with word under cursor
![image](https://github.com/user-attachments/assets/da1d9b54-918f-456f-ad84-6075474b9a14)
if i press `ctrl-h` another one it toggle replace on search panel.

If i press `ctrl-j` it activates terminal panel, as expected, but after this i cannot return on code panel by `ctrl-k`.
![image](https://github.com/user-attachments/assets/d97ccff5-7503-4a7f-8dbe-4fac9b53dde5)
But from terminal panel i can activate project panel by `ctrl-h` as expected. and from project panel i can return to code by `ctrl-l`, as expected.

If i split code window verticaly and try move from left panel to right by `ctrl-l` it starts select rows as vim visual mode.
![image](https://github.com/user-attachments/assets/a177b2d2-478b-4b00-850e-c72f5465c903)

I checked this issue https://github.com/zed-industries/zed/issues/9547 but it doesn't work for me. Another similar closed issues with similar problems didn't give me any solution

Editor version:
![image](https://github.com/user-attachments/assets/721fb942-7d87-4980-9d4f-4de254fec403)
OS: Linux, Ubuntu 22.04

**Comment by metallerok** [comment]
I think i found the solution. In documentation example `context: "Dock"`
![Screenshot from 2024-07-23 19-51-39](https://github.com/user-attachments/assets/53bbdd0d-6c09-432c-9ade-bf384bae3a88)
If remove this `context` property it works fine.
```json
  {
    "bindings": {
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]
    }
  }

```

**Comment by ferrao** [comment]
This works for me @metallerok :

```
{
    "context": "Workspace",
    "bindings": {
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]
    }
  }
```

**Comment by qudo-code** [comment]
Thanks @ferrao ! Exactly that
