### ISSUE TITLE
Ruby: Go to definition stop working if ruby-lsp is enabled together with rubocop

### ISSUE THREAD

**Issue by evkorotkov** [zed-industries/zed#15023]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Go to definition stop working if ruby-lsp or solargraph is enabled together with rubocop.
Looks like request `textDocument/definition` goes to rubocop instead of ruby-lsp
Example of settings:
```json
{
  "theme": "Andromeda",
  "wrap_guides": [120],
  "current_line_highlight": "line",
  "toolbar": {
    "breadcrumbs": false,
    "quick_actions": false
  },
  "buffer_font_family": "Monaco",
  "buffer_font_size": 13,
  "buffer_line_height": {
    "custom": 1.5
  },
  "nightly": {
    "enabled": true
  },
  "ui_font_size": 16,
  "vim_mode": true,
  "vim": {
    "use_system_clipboard": "always",
    "use_multiline_find": true
  },
  "git": {
    "inline_blame": {
      "enabled": false
    }
  },
  "format_on_save": "off",
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      },
      "rubocop": {
        "initialization_options": {
          "safeAutocorrect": false
        }
      }
    }
  },
  "languages": {
    "Ruby": {
      "language_servers": ["rubocop", "ruby-lsp", "!solargraph"]
    }
  }
}
```

### Environment

Zed: v0.144.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/b1f899be-c110-4c1f-b87e-5500c5f64efa)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed_ruby-lsp.log](https://github.com/user-attachments/files/16352225/Zed_ruby-lsp.log)
</pre></details>

**Comment by maxcroy1** [comment]
Seems like this might be an issue with Ruby-LSP in general? I don't even have rubocop specified in my settings, and I'm running into the same issue here.

**Comment by vitallium** [comment]
> Seems like this might be an issue with Ruby-LSP in general? I don't even have rubocop specified in my settings, and I'm running into the same issue here.

Hi! I think it could be. Can you please attach server and RPC messages from Ruby LSP when you use `Go to Definition`?

**Comment by maxcroy1** [comment]
These are the only errors I get when I run go to definition:
```
stderr: [server] RuboCop 1.60.1 language server initialized, PID 25011
stderr: [server] Ignoring workspace/didChangeConfiguration
```

My guess is that the command doesn't even have a chance to run - seems like it's failing at initialization. 

Another weird quirk - it seems like Zed is looking for solargraph despite the gem not being excluded in my settings:
```
Caused by:
    No such file or directory (os error 2)
2024-07-25T15:45:52.719064Z [INFO] starting language server "solargraph", path: "/Users/mcroy/Priceline/supply_chain", id: 6
2024-07-25T15:45:53.65163Z [ERROR] failed to start language server "solargraph": solargraph must be installed manually
2024-07-25T15:45:53.651716Z [ERROR] server stderr: Some("")
2024-07-25T15:45:53.651773Z [ERROR] Hit 4 reinstallation attempts for "solargraph"
2024-07-25T15:47:06.110301Z [INFO] Initializing default prettier with plugins {}
2024-07-25T15:47:06.110707Z [INFO] starting language servers for Ruby: solargraph, rubocop
2024-07-25T15:47:06.110762Z [INFO] starting language servers for Ruby: solargraph, rubocop
2024-07-25T15:47:06.110815Z [INFO] starting language servers for Ruby: solargraph, rubocop
2024-07-25T15:47:06.111849Z [WARN] Skipping path "/Users/mcroy" that has no prettier dependency and no workspaces section in its package.json
2024-07-25T15:47:06.341851Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 1,
  "message": "[INFO] [ghostText] [2024-07-25T15:47:06.341Z] Cancelled during debounce",
  "metadataStr": "[INFO] [ghostText] [2024-07-25T15:47:06.341Z]",
  "extra": [
    "Cancelled during debounce"
  ]
}
```

Settings, as specified by Ruby language documentation:
```
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "base_keymap": "VSCode",
  "theme": "Catppuccin Mocha",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "tab_size": 2,
  "vim_mode": true,
  "cursor_blink": false,
  "scrollbar": {
    "show": "never"
  },
  "vertical_scroll_margin": 0,
  "context": "Dock",
  "bindings": {
    "ctrl-w h": ["workspace::ActivatePaneInDirection", "Left"],
    "ctrl-w l": ["workspace::ActivatePaneInDirection", "Right"],
    "ctrl-w k": ["workspace::ActivatePaneInDirection", "Up"],
    "ctrl-w j": ["workspace::ActivatePaneInDirection", "Down"]
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      }
    }
  },
  "Ruby": {
    "language_servers": ["rubocop", "ruby-lsp", "!solargraph", "..."]
  }
}
```

**Comment by maxcroy1** [comment]
LSP Errors:
```
stderr: [server] RuboCop 1.60.1 language server initialized, PID 25011
stderr: [server] Ignoring workspace/didChangeConfigurationstderr: [server] Ignoring workspace/didChangeConfiguration
stderr: [server] Ignoring workspace/didChangeConfiguration
stderr: [server] Ignoring workspace/didChangeConfiguration
```

Zed Log:
```
Caused by:
    No such file or directory (os error 2)
2024-07-25T15:45:52.719064Z [INFO] starting language server "solargraph", path: "{REDACTED}", id: 6
2024-07-25T15:45:53.65163Z [ERROR] failed to start language server "solargraph": solargraph must be installed manually
2024-07-25T15:45:53.651716Z [ERROR] server stderr: Some("")
2024-07-25T15:45:53.651773Z [ERROR] Hit 4 reinstallation attempts for "solargraph"
2024-07-25T15:47:06.110301Z [INFO] Initializing default prettier with plugins {}
2024-07-25T15:47:06.110707Z [INFO] starting language servers for Ruby: solargraph, rubocop
2024-07-25T15:47:06.110762Z [INFO] starting language servers for Ruby: solargraph, rubocop
2024-07-25T15:47:06.110815Z [INFO] starting language servers for Ruby: solargraph, rubocop
2024-07-25T15:47:06.111849Z [WARN] Skipping path "{REDACTED}" that has no prettier dependency and no workspaces section in its package.json
2024-07-25T15:47:06.341851Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 1,
  "message": "[INFO] [ghostText] [2024-07-25T15:47:06.341Z] Cancelled during debounce",
  "metadataStr": "[INFO] [ghostText] [2024-07-25T15:47:06.341Z]",
  "extra": [
    "Cancelled during debounce"
  ]
}
```

Settings:
```
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "base_keymap": "VSCode",
  "theme": "Catppuccin Mocha",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "tab_size": 2,
  "vim_mode": true,
  "cursor_blink": false,
  "scrollbar": {
    "show": "never"
  },
  "vertical_scroll_margin": 0,
  "context": "Dock",
  "bindings": {
    "ctrl-w h": ["workspace::ActivatePaneInDirection", "Left"],
    "ctrl-w l": ["workspace::ActivatePaneInDirection", "Right"],
    "ctrl-w k": ["workspace::ActivatePaneInDirection", "Up"],
    "ctrl-w j": ["workspace::ActivatePaneInDirection", "Down"]
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      }
    }
  },
  "Ruby": {
    "language_servers": ["rubocop", "ruby-lsp", "!solargraph", "..."]
  }
}
```

**Comment by mrnugget** [comment]
Does this change if you change the order of the language servers in your settings?

**Comment by vitallium** [comment]
> Does this change if you change the order of the language servers in your settings?

Nope, it doesn't, unfortunately. I could be wrong but Zed currently uses for commands line `Go to Definition`, `Go to Type Definition` and `Go to Implementation` the first registered language server that actually started faster. I am still new to the Zed's code base, but I see [here](https://github.com/zed-industries/zed/blob/d93891ba630345d7e28b324aa027e650f4e7832f/crates/project/src/project.rs#L5434) Zed sends the corresponding LSP request:

```rust
fn definition_impl(
        &self,
        buffer: &Model<Buffer>,
        position: PointUtf16,
        cx: &mut ModelContext<Self>,
    ) -> Task<Result<Vec<LocationLink>>> {
        self.request_lsp(
            buffer.clone(),
            LanguageServerToQuery::Primary,
            GetDefinition { position },
            cx,
        )
    }
```
which is calls the `self.request_lsp` method that [asks for the primary language server](https://github.com/zed-industries/zed/blob/d93891ba630345d7e28b324aa027e650f4e7832f/crates/project/src/project.rs#L7488) for the current buffer:

```rust
let language_server = match server {
                LanguageServerToQuery::Primary => {
                    match self.primary_language_server_for_buffer(buffer, cx) {
                        Some((_, server)) => Some(Arc::clone(server)),
                        None => return Task::ready(Ok(Default::default())),
                    }
                }
                LanguageServerToQuery::Other(id) => self
                    .language_server_for_buffer(buffer, id, cx)
                    .map(|(_, server)| Arc::clone(server)),
            };
```

The `primary_language_server_for_buffer ` implementation is quite simple ([link](https://github.com/zed-industries/zed/blob/d93891ba630345d7e28b324aa027e650f4e7832f/crates/project/src/project.rs#L10234)):

```rust
fn primary_language_server_for_buffer(
        &self,
        buffer: &Buffer,
        cx: &AppContext,
    ) -> Option<(&Arc<CachedLspAdapter>, &Arc<LanguageServer>)> {
        self.language_servers_for_buffer(buffer, cx)
            .find(|s| s.0.is_primary)
    }
```

All in all, I think this method returns the first started and registered language server. I hope that gives a hint.

**Comment by mrnugget** [comment]
Yeah, it returns the first one that was added and that's `is_primary`, but the way I read this code

https://github.com/zed-industries/zed/blob/a3300b2aa23fb34dea974f0a40227a564d1761d1/crates/project/src/project.rs#L2964-L2986

It looks to me like the order _does_ matter. Weird.

In any case, doesn't your PR https://github.com/zed-industries/zed/pull/15111 fix this? Should we close the the ticket?

**Comment by vitallium** [comment]
> Yeah, it returns the first one that was added and that's `is_primary`, but the way I read this code
> 
> https://github.com/zed-industries/zed/blob/a3300b2aa23fb34dea974f0a40227a564d1761d1/crates/project/src/project.rs#L2964-L2986
> 
> It looks to me like the order _does_ matter. Weird.
> 
> In any case, doesn't your PR #15111 fix this? Should we close the the ticket?

Unfortunately, it fixed another issue where Zed sends a `Go to definition` request to a language server that does not support this command.

>It looks to me like the order does matter. Weird.

I think this because `language_server_ids_for_buffer` method that is used in `primary_language_server_for_buffer` doesn't use the ordered languages servers and returns all of them in no particular order:

```rust
fn language_server_ids_for_buffer(
        &self,
        buffer: &Buffer,
        cx: &AppContext,
    ) -> Vec<LanguageServerId> {
        if let Some((file, language)) = File::from_dyn(buffer.file()).zip(buffer.language()) {
            let worktree_id = file.worktree_id(cx);
            self.languages
                .lsp_adapters(&language) // this returns all LSP adapters for a language in no particular order
                .iter()
                .flat_map(|adapter| {
                    let key = (worktree_id, adapter.name.clone());
                    self.language_server_ids.get(&key).copied()
                })
                .collect()
        } else {
            Vec::new()
        }
    }
```

So for the Ruby language it returns all LSP adapters defined there (in this order): `rubocop`, `ruby-lip`, `solargraph`. I'm not sure if I am on the right track, but I guess this could provide a hint."

**Comment by evkorotkov** [comment]
> In any case, doesn't your PR https://github.com/zed-industries/zed/pull/15111 fix this? Should we close the the ticket?

I just want to confirm that unfortunately PR https://github.com/zed-industries/zed/pull/15111 didn't fix the issue
I'm using nightly builds and the problem is still here

**Comment by mrnugget** [comment]
Yeah, I think overall the issue is that extensions can't register a language server as a _secondary_ language server yet (which is what we do for Tailwind/ESLint, for example).

Fixing the order seems like a crutch, so instead I went the other direction and opened a PR that allows extension authors to define whether a language server is secondary or not: https://github.com/zed-industries/zed/pull/15597

Hope that's possible without it requiring a hard change to the extension API, but I don't think so.

With that (and the Ruby extension updated locally to the dev version that includes the change) it works:

https://github.com/user-attachments/assets/47fceda9-56ac-416c-aa8c-7c0b7e6cac79

**Comment by vitallium** [comment]
@mrnugget @maxdeviant I can also confirm that everything works like a charm now. You and the whole Zed team are awesome. I know you are extremely busy with other features, but you still find time to fix issues like this one. Thank you! ❤️

**Comment by vitallium** [comment]
P.S. We can close this issue.

**Comment by maxdeviant** [comment]
> I think this because `language_server_ids_for_buffer` method that is used in `primary_language_server_for_buffer` doesn't use the ordered languages servers and returns all of them in no particular order:

This ended up being the crux of the issue.

`language_server_ids_for_buffer` pulls from the `lsp_adapters` list which _does_ store an ordered list of language server adapters for a given language, but the problem was it was entirely reliant on the order in which they were initially inserted (which may be different from the order denoted by the setting).

In https://github.com/zed-industries/zed/pull/15624 I changed it so that each time we start up the language servers we reorder that list to reflect the order from the `language_servers` setting, so that should now be the authoritative ordering of the language servers.

The first language server in the `language_servers` list will be treated as the "primary" one.

**Comment by maxdeviant** [comment]
> @mrnugget @maxdeviant I can also confirm that everything works like a charm now. You and the whole Zed team are awesome. I know you are extremely busy with other features, but you still find time to fix issues like this one. Thank you! ❤️

Thank you for testing it out!

**Comment by mrnugget** [comment]
Closing this since it seems to be fixed by https://github.com/zed-industries/zed/pull/15624. I also updated the docs here: https://github.com/zed-industries/zed/pull/15633

**Comment by evkorotkov** [comment]
@mrnugget @maxdeviant @vitallium everything works now!
Thanks a lot for the quick response and fix!

**Comment by mrnugget** [comment]
> This has stopped working again in zed 0.150.4

So it did work with zed 0.149.x and on the same project with the same configuration it stopped? Can you confirm this by downloading and running the 0.149.x release?

**Comment by ksr-13** [comment]
> > This has stopped working again in zed 0.150.4
> 
> So it did work with zed 0.149.x and on the same project with the same configuration it stopped? Can you confirm this by downloading and running the 0.149.x release?

I had tried that version and "same project with the same configuration it stopped".
Its working now with "same project with the same configuration" after upgrading to version 0.151.1

**Comment by mrnugget** [comment]
Okay, well, then let's hope it keeps working!
