### ISSUE TITLE
Shortcut for open in terminal option

### ISSUE THREAD

**Issue by AdityaPandey6243** [zed-industries/zed#15049]
### Check for existing issues

- [X] Completed

### Describe the feature

I know the there is already a shortcut for to the terminal, but none for the 'open in terminal' option.

**Comment by notpeter** [comment]
Where would you use "Open in Terminal" and what would it do?

Like if you had a directory selected in the project panel it would open a terminal and `cd` there? Or would this be for files?

**Comment by AdityaPandey6243** [comment]
See right now the " ctrl + ` " opens the terminal in the root directory.
[image: Screenshot 2024-07-27 115522.png]
The open in terminal option is there but its only available for mouse click
[image: Screenshot 2024-07-27 115634.png]
There should be just a keyboard shortcut for it and it should cd to the
folder in which the file currently opened in the workspace is
[image: Screenshot 2024-07-27 115744.png]
Like this.

**Comment by notpeter** [comment]
Ah. There's just no default keybinding for the `workspace::OpenInTerminal` action.

Add this to your `~/.config/zed/keymap.json`:

<img width="590" alt="Screenshot 2024-07-28 at 9 18 26" src="https://github.com/user-attachments/assets/c03168c0-d2fc-4d08-893e-45cbd4461ae7">
