### ISSUE TITLE
Clojure/ClojureScript - Renaming symbol or var alter all values with the same name

### ISSUE THREAD

**Issue by mtmr0x** [zed-industries/zed#15050]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just created a ClojureScript test project with Reagent + Re-Frame and went adjusting some values. When I altered the import from :as to :refer, it caused some issues in all :as symbols (see video), and the same happened to a function when applying a simple space before it and then deleting the space (also see video)

https://github.com/user-attachments/assets/7e2c00f0-a1fe-4234-99fa-b34ed01eed6a

https://github.com/user-attachments/assets/f8d0006f-2b3f-4d64-bb78-dc2b73452d32

### Environment

Zed: v0.144.4 (Zed)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ribelo** [comment]
@mtmr0x  Setting `"linked_edits": false` resolves the issue. 

If the problem lies with the `linked_edits` implementation on `clojure-lsp` side, I can move the issue to their project.

**Comment by mtmr0x** [comment]
@ribelo thanks a lot! It actually solved the problem

**Comment by paulbutcher** [comment]
@ribelo I just stumbled across this (and can confirm that disabling `linked_edits` addresses the problem). I can't find an issue in https://github.com/clojure-lsp/clojure-lsp/issues. Are they aware of the problem?

If not, I'll create an issue.

**Comment by paulbutcher** [comment]
See also #20002
