### ISSUE TITLE
fix zed fonts

### ISSUE THREAD

**Issue by RustoMCSpit** [zed-industries/zed#15053]
### Check for existing issues

- [X] Completed

### Describe the feature

"It also saves us about 8Mb of space, and fixes some font fallback issues on Linux. The Zed fonts were gigantic and configured a bit wrong (it turns out in hindsight :D)."
@ConradIrwin https://github.com/zed-industries/zed/pull/13596#issuecomment-2221061672

many people, including myself, preferred the old font. it would be nice if the issues for it were fixed so that it can once again be used properly

### If applicable, add mockups / screenshots to help present your vision of the feature

this issue blocks https://github.com/zed-industries/zed/issues/14522

**Comment by ConradIrwin** [comment]
@RustoMCSpit You are welcome to build and distribute a new version of the Zed fonts based on https://github.com/zed-industries/zed-fonts (or just download the latest release of the old fonts from there).

Closing this as we're not planning to work more on those fonts any time soon (though it's great to hear how much everyone loved them :D).

**Comment by RustoMCSpit** [comment]
well could you give a brief overview on what makes them "configured wrong" so the community knows what to fix

**Comment by ConradIrwin** [comment]
The WidthClass is set to 400 instead of 300, which breaks cosmic texts fallback stack on Linux. (Also they're really big, for some reason I don't know yet)

**Comment by RustoMCSpit** [comment]
> The WidthClass is set to 400 instead of 300, which breaks cosmic texts fallback stack on Linux. (Also they're really big, for some reason I don't know yet)

can i make a separate issue for this here or is that something for the other repo? is zed fonts abandoned forever?
