### ISSUE TITLE
Supermaven suggesting existing text after current cursor position

### ISSUE THREAD

**Issue by danielsuguimoto** [zed-industries/zed#15052]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Supermaven completions are duplicating text after the cursor, such as existing closing brackets quotes, and semi-colons.
 

### Environment

Zed: v0.144.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/3a0bb4b7-f07a-4392-9ae5-59ce1997e2e8)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by danielsuguimoto** [comment]
@notpeter Just realized that the PR https://github.com/zed-industries/zed/pull/13884 might fix it and make Zed usable with Supermaven

**Comment by SomeoneToIgnore** [comment]
It does truncate the text suggested, ergo closing.
