### ISSUE TITLE
Zed crashed on first run

### ISSUE THREAD

**Issue by adityavsx** [zed-industries/zed#15062]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I did a source build for  Zed on windows, and everything compiled up until it was time to build the zed(bin). 
The following error messages were shown in the terminal : 
```
[2024-07-24T09:23:45+05:30 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-07-24T09:23:45+05:30 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-07-24T09:23:46+05:30 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
Zed failed to open a window: NoSupportedDeviceFound. See https://zed.dev/docs/linux for troubleshooting steps.
```
Now, for the ```Zed failed to open a window:NoSupportedDeviceFound" I read the zed.dev/docs/ for the troubleshooting steps and on doing those : 

1. Vulkan was fine, it showed the rotating cube indicating that the driver's compatible 
2. Driver was updated, tried manually updating and windows was sure that the drivers updated (however there is a more updated version available) 

I have been stuck at this for quite sometime, any help diagnostic would be helpful. 
Also note, there is no ```~Library/Logs/Zed/Zed.log" that Zed has generated where it can dump the logs. I did a reinstall and then caught these errors command line. 

### Environment

My Device Specifications : 
Processor	Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz   2.21 GHz
Installed RAM	24.0 GB (23.9 GB usable)
System type	64-bit operating system, x64-based processor

My Windows Specifications : 
Edition	Windows 11 Home Insider Preview Single Language
Version	24H2
OS build	26252.5000
Experience	Windows Feature Experience Pack 1000.26252.5000.0

My Driver Specification : 
Driver : Intel(R) UHD Graphics 620
Version : 27.20.100.8853

Also, as an extra, I did check the Driver files and indeed, unlike what the trouble-shooting page says, the driver has ```Windows\system32\vulkan-1-dll``` installed, as well as, ```Windows\SysWow64\vulkan-1-dll```. 

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Polygons1** [comment]
Update your graphics driver (https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html)

**Comment by adityavsx** [comment]
> Update your graphics driver (https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html)

thankyou so much. This seems to have fixed it. However, can you explain why my previous version was not compatible? Should the docs be updated?

**Comment by Polygons1** [comment]
I think the reason is because that Vulkan was introduced to graphics drivers after 27.20.100.8853

**Comment by Polygons1** [comment]
I don’t know about that
