### ISSUE TITLE
Disable terminal when open in window

### ISSUE THREAD

**Issue by anHiep** [zed-industries/zed#15060]
### Check for existing issues

- [X] Completed

### Describe the feature

I have built zed in window using rust. But whenever I click on zed.exe. A terminal window also appear and I want to hide it (like nogui in Pascal I think :v)

**Comment by aohanhongzhi** [comment]
FYI https://github.com/emilk/egui/discussions/1003

```shell
cargo build  --release --target x86_64-pc-windows-msvc
```
