### ISSUE TITLE
Custom command via an extension

### ISSUE THREAD

**Issue by mauscoelho** [zed-industries/zed#15069]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello, I want to create an extension to open the current line on GitHub web via the command palette.
Do you know if I can create a custom command via extensions?

### If applicable, add mockups / screenshots to help present your vision of the feature

[command palette](https://marketplace.visualstudio.com/items?itemName=sysoev.vscode-open-in-github)

**Comment by SomeoneToIgnore** [comment]
Extensions can define tasks as https://github.com/zed-industries/zed/blob/main/extensions/php/languages/php/tasks.json so that could help

**Comment by notpeter** [comment]
There are existing actions built into Zed for this. See:
 - `editor: open permalink to line`
 - `editor: copy permalink`
<img width="558" alt="Screenshot 2024-07-24 at 15 18 27" src="https://github.com/user-attachments/assets/a91abbcf-e78b-43db-b334-05f757d31ba4">

There's no default mapping for these, but you can add custom binds:

```json
// File: ~/.config/zed/keymap.json
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-alt-cmd-z": "editor::CopyPermalinkToLine",
      "ctrl-alt-cmd-x": "editor::OpenPermalinkToLine"
    }
  }
]
```

**Comment by mauscoelho** [comment]
thanks @notpeter
