### ISSUE TITLE
Vim: Macros

### ISSUE THREAD

**Issue by Kethku** [zed-industries/zed#1506]
Macros are an important part of using vim effectively. Zed gets part of the way there with fast integrated multiple cursors, but a good vim mode should implement these features as well.

**Comment by estk** [comment]
Why was this closed as completed?

**Comment by Artur-Galstyan** [comment]
This issue should be re-opened. AFAIK, Vim macros are not yet implemented and there seems to be no issue tracking it. 

(Unless Vim macros are so far ahead on the roadmap and are not planned for a very long time in which case it'd be nice to know :) )

**Comment by Zollerboy1** [comment]
@mikayla-maki could you please elaborate on why this issue was closed?

**Comment by mikayla-maki** [comment]
No idea, probably a general clean up of old issue tracking that went a little too far.

**Comment by mvolkmann** [comment]
I want to use Zed, but there are two main issues holding me back. The first is this one (lack of Vim macros) and the second is lack of Git integration (including nice side-by-side diffs like I get in VS Code).

**Comment by mvolkmann** [comment]
@ConradIrwin By fixed do you mean that in Vim command mode we can type q followed by a letter (like x) to begin recording a macro, enter a bunch of Vim commands, press q again to stop recording the macro, move the cursor somewhere else, and press @x to execute the macro? That isn't working for me.

**Comment by ConradIrwin** [comment]
@mvolkmann Are you on the latest main?

This will ship to preview today and to stable in about a week.

**Comment by mvolkmann** [comment]
I wasn't building zed from the GitHub repo. I just tried that and macros work great. Thanks so much for adding that feature!

I think it took about 20 minutes to build zed on an M1 Mac. The Rust build process sure is slow!

**Comment by ConradIrwin** [comment]
Ugh, tell me about it!

You'll also want to build in —release mode to get good runtime performance,
but it takes even longer 😭
