### ISSUE TITLE
vim: Uppercase Y does not yank the rest of the line from the cursor

### ISSUE THREAD

**Issue by lucascherzer** [zed-industries/zed#15064]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Desired behaviour
---
In plain nvim, when you press `Y`, it yanks everything in the line starting from the cursor position.
For example, when pressing `Y` in this context - with the cursor above "d":
```
abc[cursor]def
```
It yanks "def".

Current behaviour
---
It yanks the whole line, so instead of "def", you get "abcdef"

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by sleeping-at-night** [comment]
Is this similar to #14771 ?

**Comment by ConradIrwin** [comment]
Fixed by #14771 - should ship to preview today and stable next week
