### ISSUE TITLE
Zed failed to launch. Could not create directory in "/Users/.../.cache/zed". Permission denied (os error 13)

### ISSUE THREAD

**Issue by kennethwolters** [zed-industries/zed#15071]
I was in a situation where zed just wouldn't start anymore a couple months ago and I didn't use it because of that. I can remember deleting the .app file in the Applications directory and re-installing with a fresh .dmg didn't change the behaviour.

Today I did the same and now I am getting the following message:

<img width="308" alt="Screenshot 2024-07-24 at 10 37 23" src="https://github.com/user-attachments/assets/deba21cf-cfce-45f3-be8f-8f88d377a54a">

So it seems this particular problem is not solved for at least my machine.

_Originally posted by @kennethwolters in https://github.com/zed-industries/zed/issues/6148#issuecomment-2247234679_

**Comment by SomeoneToIgnore** [comment]
I have no idea why there's a message about creating an issue, as users are able to solve this pretty easily themselves by changing the directory's permissions to the current user, please follow https://github.com/zed-industries/zed/issues/13426#issuecomment-2187288480 and below for the instructions.

Hopefully https://github.com/zed-industries/zed/issues/13619 fixes the usability but I do not think we should keep this issue open.

**Comment by kennethwolters** [comment]
Hi @SomeoneToIgnore, I did the steps at https://github.com/zed-industries/zed/issues/13426#issuecomment-2187288480 and I am still getting exactly the same error (I am on macOS apple silicon).

`ls -lad ~/.config/ ~/.config/zed/ ` outputs:
`drwxr-xr-x  10 kenneth  staff  320 Jul 26 20:56 /Users/kenneth/.config/
drwxr-xr-x@ 24 kenneth  staff  768 Mar 22 10:10 /Users/kenneth/.config/zed/`

**Comment by SomeoneToIgnore** [comment]
The error says `~/.cache/zed` though? And you show the `.config` directory permissions which look file — let's do the same for the former.

**Comment by kennethwolters** [comment]
Thank you, careful reading doesn't seem to be my strength! It is really weird that my user didn't have write permissions in .cache  I wonder how that arises...  I am guessing it's not normal behaviour for a macOS machine

**Comment by SomeoneToIgnore** [comment]
Yes, something was run with the root privileges before, and created this dir, this is not very good but now you know.
