### ISSUE TITLE
Custom URI Scheme for 3rd party integrations (DevPod)

### ISSUE THREAD

**Issue by pascalbreuninger** [zed-industries/zed#15070]
### Check for existing issues

- [x] Completed

### Describe the feature

Hey 👋 

## Motivation
I'm the maintainer of an open source project called [DevPod](https://github.com/loft-sh/devpod) which let's you create dev environments based on devcontainer.json on any infrastructure and the connect it to the most popular IDEs. 
Zed has gained a lot of traction lately and unsurprisingly we now have requests to support it in DevPod ([ref](https://github.com/loft-sh/devpod/issues/1185)). 
I know your remote development implementation is in the early stages but it might be interesting to consider integrating with other tools such as DevPod for the GA release of this feature. 

## Suggestion
VSCode and Jetbrains IDEs currently expose a custom uri scheme to create new remote workspaces, i.e.
- `vscode://vscode-remote/ssh-remote+$HOST/$FOLDER_TO_OPEN`
- `jetbrains-gateway://connect#idePath=$IDE_FOLDER_ON_REMOTE&projectPath=FOLDER_TO_OPEN&host=$HOST&type=ssh&deploy=false`

Zed could also implement a similar custom protocol using the existing parsing features to open files with `zed://filename` if I saw that correctly glimpsing over the code.

## Alternatives
- Add a new CLI command to launch a remote workspace, `zed launch --host=$HOST --folder=$FOLDER` or something along those lines
- I haven't tried it yet but external tools could potentially use the existing [SQLite client](https://github.com/zed-industries/zed/blob/ba6c36f3704deb86d09c255d9714c4236c716923/crates/collab/src/db/queries/dev_servers.rs#L95) to update the internal state manually although it's error prone and likely to fail soon

**Comment by ConradIrwin** [comment]
@pascalbreuninger Thanks for suggesting this! We're in the middle of a rewrite of our SSH layer, but we do intend to support some kind of URL. Like `zed://ssh/$HOST/$PATH`.

I'm assuming dev containers rarely need other ssh options, but I'd like to make sure we have the support for that too.

**Comment by pascalbreuninger** [comment]
@ConradIrwin yup that should pretty much be enough. Most tools write their own SSH host config anyway if they need more options. As long as we can let zed know which host (or command) to use and where the workspace is located on the remote machine, we're good 👍 
Looking forward to your refactoring!

**Comment by mrnugget** [comment]
It definitely works to connect to a DevPod via SSH:

![screenshot-2024-10-29-13 02 25@2x](https://github.com/user-attachments/assets/1b5febbf-b33f-47fa-bde4-8c0c37f116ef)

Problem is that you have to specify the workspace folder manually and you get an error that the folder is not owned by the current user.

**Comment by pascalbreuninger** [comment]
With the addition of `zed ssh://` we can automate that from DevPod and pass the correct workspace folder to zed. 
Are you on linux @mrnugget?

**Comment by mrnugget** [comment]
Screenshot was taken on macOS.

**Comment by ConradIrwin** [comment]
I've gone ahead and added `zed://ssh/` because I think it'll be nice to have a one-click open.

**Comment by pascalbreuninger** [comment]
Thanks a lot @ConradIrwin, we've released [DevPod 0.6.0](https://github.com/loft-sh/devpod/releases/tag/v0.6.0) which includes support for Zed
