### ISSUE TITLE
Slow find and replace for large number of matches

### ISSUE THREAD

**Issue by VitorRamos** [zed-industries/zed#15102]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While working on a large JSON file, I accidentally searched for character space which took about 20 seconds to complete with the screen frozen; in comparison, vscode can do the same search almost instantly (although it stops highlighting after 20k matches).

The same problem applies to replacement if I try to replace space in this file it takes around a minute to complete, while vscode takes 3 seconds.

I can reproduce this with this fake file by searching for "A".
```bash
#!/bin/bash

#Output file name
output_file = "output.txt"
# Number of lines
num_lines=320000
# Number of characters per line
chars_per_line=25
# Character to repeat

char = "A"
line=$(printf "%0.s$char" $(seq 1 $chars_per_line))
head -c $((num_lines * (chars_per_line + 1))) < <(yes "$line") > "$output_file"
echo "File $output_file created with $num_lines lines and $((num_lines * chars_per_line)) characters."
```

With a bit of debugging (building a release with full debug info) I discovered that one of the reasons is `Editor::highlight_background` more specifically `summary_for_anchor` for all ranges.
![flamegraph_find](https://github.com/user-attachments/assets/2b57428d-e691-4420-b4e5-75e868faa114)

The loop decoding each character seems very expensive in `impl<'a> From<&'a str> for TextSummary` for the usize TextDimension since it only needs the .len() apparently.

### Environment

Version: Zed v0.146.0 (Zed Dev 846fc67519d976a72512235adfe54e189d522127)
OS: Linux X11 ubuntu 22.04
Memory: 31.2 GB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2070 with Max-Q Design || NVIDIA || 550.90.07

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
Hey, thanks for reporting this issue. Summary creation was one of the last things that stood out when I looked at the traces for buffer search performance.
It looks like the call to `summary_for_anchor` is there to catch an invalid anchor sooner. We can get rid of it.

**Comment by osiewicz** [comment]
I've just merged a fix. Can you test it on your side? You'll have to build from the latest main.

**Comment by VitorRamos** [comment]
Now it's almost instantly as well, thanks.
