### ISSUE TITLE
Broken link in release notes for `v0.146.0-pre`

### ISSUE THREAD

**Issue by khipp** [zed-industries/zed#15126]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the generated release notes for `v0.146.0-pre`, the link to the blog post on REPL support points to https://github.com/zed-industries/zed/blob/v0.146.0-pre/www.zed.dev/blog/repl rather than https://zed.dev/blog/repl.

### Environment

N/A

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Thank you so much @khipp! The change should be live in a few moments.
