### ISSUE TITLE
Build from source in windows failed caused VulkanLoadingError

### ISSUE THREAD

**Issue by SayorNotDo** [zed-industries/zed#15139]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

while I try to build zed by `cargo run`, then get err which told `blade_graphics::hal::init Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExw{...})` and err occurred msg located on `"location_data": {"file": "crates\gpui\src\platform\windows\windows.rs", "line": 971}`

### Environment

"app_version": "0.144.4",
"os_name": "windows",
"os_version": "10.0.22631",
"architecture": "x86_64"

**Comment by SomeoneToIgnore** [comment]
I think we have enough of Windows + this error in our tracker: https://github.com/zed-industries/zed/issues?q=is%3Aissue+Missing+Vulkan+entry+points
closing as a duplicate.

**Comment by SayorNotDo** [comment]
well, got it.
