### ISSUE TITLE
Freeze when opening a large file on Linux

### ISSUE THREAD

**Issue by iwansyahp** [zed-industries/zed#15154]
I believe there was a similar issue encountered (and solved) on MacOS version of Zed. Creating a new issue since that one can not be reopened.

I encounter this problem when using Zed opening a `*.txt` file on Arch Linux.

Here is the screenshot of `journalctl` on my system. 

![image](https://github.com/user-attachments/assets/fb66dadd-072b-44f8-b30c-eed172eb3b27)

File size is: 6.7MB
Number of lines: 39791

_Originally posted by @iwansyahp in https://github.com/zed-industries/zed/issues/9055#issuecomment-2249744711_

**Comment by mrnugget** [comment]
It allocated ~83GB but only used ~8GB? Wow. Can you reproduce it by opening the same file again? Can you share the file? Can you reproduce it with a modified version of the file? (i.e. replace all characters with `a` or something)

**Comment by iwansyahp** [comment]
> 1. Can you reproduce it by opening the same file again?
I can not reproduce it. One thing I notice that when scrolling the file contents, sometime the CPU usage goes beyond 100% (based on btop monitoring specifically on running Zed instance) 

> 2. Can you share the file?

It contains sensitive information, can not do that.

> 3. Can you reproduce it with a modified version of the file? (i.e. replace all characters with a or something)

Similar to what I get in #1.

**Comment by mrnugget** [comment]
Well, if you can reliably reproduce it with a non-sensitive version of the file, that'd be great. Until then it's hard to fix this.

**Comment by iwansyahp** [comment]
I will close this issue and reopen if I encounter the bug again. Thanks for checking
