### ISSUE TITLE
open golang project show this error

### ISSUE THREAD

**Issue by diucicd** [zed-industries/zed#15158]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/70059f86-3c40-40e5-bf12-7c45b95b429c)

### Environment

macos

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16373596/Zed.log)

</pre></details>

**Comment by notpeter** [comment]
1. What version of gopls do you have? `/usr/local/bin/gopls version`
2. How did you install gopls? / Can you upgrade `gopls`?

I think your version of gopls would have to be >2years old to not have hints support.

**Comment by diucicd** [comment]
thank! @notpeter , you are right, the latest is installed in go/bin/gopls, /usr/local/bin/gopls is so dam old! I deleted this old bin and everything now works!
