### ISSUE TITLE
Terraform autoformatter/autocomplete stoped working 

### ISSUE THREAD

**Issue by vlad-mck** [zed-industries/zed#15153]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After save or auto-save I have no longer formatter or autocomplete on resources blocks using latest version as well as using past 3 versions of Zed.

### Environment

macOS Sonoma 14.5

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by vlad-mck** [comment]
found in #14502, thanks! hope fix is on the way

**Comment by notpeter** [comment]
> Note that if you already have the latest language server version downloaded you'll need to delete the containing directory so that it gets downloaded again. On macOS the directory is `~/Library/Application\ Support/Zed/extensions/work/terraform`.

_Originally posted by @maxdeviant in https://github.com/zed-industries/zed/issues/14502#issuecomment-2250211285_
