### ISSUE TITLE
Align X icon for expanded hunks better

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#15164]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/user-attachments/assets/b69b4ef8-1377-45fd-bd23-b467c2a0f61e

As you can see from the video, that `x` there seems a bit wrong.
It would be better to remove it.

@SomeoneToIgnore :

https://github.com/user-attachments/assets/43abd9d5-4550-402a-89c1-6457553b2492

**Comment by SomeoneToIgnore** [comment]
> It would be better to remove it.

No it is not, I disagree.
But it indeed needs a better padding.
