### ISSUE TITLE
Ctrl-D mapped to delete and not select next

### ISSUE THREAD

**Issue by lsunsi** [zed-industries/zed#15160]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open zed, on an editor, select some text and type Ctrl+D. Before last update, it selected next occurrence of selected text.
After 0.145.1 it just deletes the selected section.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland fedora 40
Memory: 30.5 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by HarshNarayanJha** [comment]
Right, the keybind was changed in a past commit. But I couldn't find what select next is bind to.

**Comment by lsunsi** [comment]
I think this is a bug since `delete` was also mapped to `delete` and I also couldn't find the previous binding anywhere. Also Zed in general has close keymap to vscode, so this change would feel weird to current users I guess.

**Comment by HarshNarayanJha** [comment]
It has been changed to `ctrl-shift-down` and `-up`
https://github.com/zed-industries/zed/blob/7fb906d774683bcef54da924ed8b8bf5feac0695/assets/keymaps/default-linux.json#L277

I (and anyone else who wants that old behaviour) could just swap these two shortcuts in the `keymap`.

I think this issue can be closed

**Comment by notpeter** [comment]
@lsunsi You are correct this got changed in my attempt to match VSCode keybindings.

Does anyone know the provenance of the other `ctrl-d` binding? It was new to me.

**Comment by vdwees** [comment]
@notpeter on linux, `ctrl-d` is the same in vscode and sublime
https://www.sublimetext.com/docs/multiple_selection_with_the_keyboard.html#quick-add-next

**Comment by fcolecumberri** [comment]
> It has been changed to `ctrl-shift-down` and `-up`
> 
> https://github.com/zed-industries/zed/blob/7fb906d774683bcef54da924ed8b8bf5feac0695/assets/keymaps/default-linux.json#L277
> 
> I (and anyone old who wants that old behaviour) could just swap these two shortcuts in the `keymap`.
> 
> I think this issue can be closed

This issue should not have been closed yet. The documentation here: https://zed.dev/docs/key-bindings#editor
states that `Control + D` on `Editor` context `Delete`. However now the default does is select next. The docs should have been updated to reflect the new configuration before closing this issue.
