### ISSUE TITLE
Title bar becomes transparent when Zed is on background

### ISSUE THREAD

**Issue by lsunsi** [zed-industries/zed#15163]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When Zed is on background (for example, while I'm typing this issue), the topbar (not sure how to call it, title bar? the bar above tabs and project tree) becomes transparent. This did not happen prior to 0.145.1, it just started happening now.
I'm on Linux Wayland, probably relevant.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland fedora 40
Memory: 30.5 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by usmanghanni** [comment]
same issue on my side,using ubuntu 24.04

**Comment by jansol** [comment]
What theme are you using? This is almost certainly happening because your theme does not specify an inactive color for the title bar. Granted, the fallback value should probably not be transparent.
