### ISSUE TITLE
Typescript callback types stick after accepting code completion

### ISSUE THREAD

**Issue by otaviomad** [zed-industries/zed#15187]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Take the following code:
```ts
const functionWithCallback = (
  callback: (data: {
    hello: string;
    hi: {
      I: {
        am: {
          a: {
            super: {
              complex: {
                type: string;
              };
            };
          };
        };
      };
    };
  }) => void
) => {};

functionWithCallback((data) => {

});
```

If you write `data.` inside the callback, press ctrl-space and accept the solution for `hi`, you'll get a hint that looks like this:
<img width="724" alt="image" src="https://github.com/user-attachments/assets/f8610e4a-4a9c-46b2-8599-3a9a30d2206e">
This specific hint will not go away on cursor movement, you have press esc to close it. This is specially annoying because it may occlude the actual type suggestions, if it's down enough so that the menu doesn't fit on the screen. The hint sticks even if you move the cursor using the mouse, by clicking elsewhere inside the body of the callback.

### Environment

Zed: v0.145.1 (Zed)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
This is the signature help popover that had been landed recently, and it is relatively useful when using small methods without such extraordinary nested level.

You can disable it with
```
"show_signature_help_after_edits": false,
```
(see default settings for the config description) and still be able to call the thing with `cmd-i` whenever needed.

**Comment by otaviomad** [comment]
Aha! I'm stupid. Thanks, this disables it :)
