### ISSUE TITLE
Rust language's outline.scm has no static items

### ISSUE THREAD

**Issue by alefminus** [zed-industries/zed#15208]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the outline panel does not show a static item. Using the latest preview. 0.146.0.

### Environment

Zed: v0.146.0 (Zed Preview)
OS: Linux Wayland fedora 40
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.1.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/84152e6f-5b98-40a0-9d09-75d4c1452778)

```rust
static FOO: u32 = 20;

fn main() {
    println!("{}", FOO);
}
```

**Comment by SomeoneToIgnore** [comment]
The issue is that 

https://github.com/zed-industries/zed/blob/001376fd6d7b33062236c139278e551960c4bba1/crates/languages/src/rust/outline.scm#L1

file has no static item definitions yet.
