### ISSUE TITLE
open terminal in new tab instead of pane

### ISSUE THREAD

**Issue by pcause** [zed-industries/zed#15221]
### Check for existing issues

- [X] Completed

### Describe the feature

can we have a setting that opens terminals in tabs instead of a pane?  i can drag the pane tab to the top and get the desired layout, but I want to be able to set the default to that layout.  whichever layout is default, ctrl+click the terminal icon on the dock should open the terminal in the other layout.  so if a pane is the default, ctrl+click opens a terminal in the top pane.

**Comment by bbb651** [comment]
I think you’re looking for “workspace: new center terminal”

**Comment by pcause** [comment]
thanks but i want to be able to set this as default for opening terminals.  no one wants to scroll through all the commands to find this and "centered" is also a bit strange.  why not just "terminal: hotizonal split" or "terminal in tabs" or some such language.

**Comment by pcause** [comment]
I tried to bind the ctrl-~ to workspace::NewCenteredTerminal and workspace::NewTerminalCentered and neither worked.  I tried to make it a global binding.  Any help?  The function for new terminal centered isn't documented

**Comment by bbb651** [comment]
```
[
    {
        "context": "Workspace",
        "bindings": {
            "ctrl-`": "workspace::NewCenterTerminal"
        }
    }
]
```
works for me, I don't think the `ctrl-~` binding actually works even with shift (at least on linux)

**Comment by pcause** [comment]
I removed, cleared everything, reinstalled and it works.  I think I previously might not of capitalized workspace.  And I use Fedora and ctrl-~ does work.
