### ISSUE TITLE
ability to have the top bar come back

### ISSUE THREAD

**Issue by RustoMCSpit** [zed-industries/zed#15245]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/user-attachments/assets/9097e5ef-4ee8-4c25-9434-444fabd9167c)

you see how in the left there was a top bar? i need that for certain linux features shown below. i also prefer it aesthetically,even if it did work, it still is an eyesore in my opinion and it would be nice as an option as no other app on linux does that for me and it breaks the aesthetic standard

![image](https://github.com/user-attachments/assets/6df3fc78-9bf8-41b7-8f02-4c382ae42274)

**Comment by vehere-suhaib** [comment]
The context menu should still pop up on the Zed top bar.

![image](https://github.com/user-attachments/assets/a4ef8978-ab18-4634-8e58-0671bb6c4a68)

**Comment by suhaibkn** [comment]
The context menu should work and pop up on the Zed top bar as well

![image](https://github.com/user-attachments/assets/e5b1d1f4-1e9a-4024-bcbf-df50c31925e1)

**Comment by RustoMCSpit** [comment]
it doesnt

linux mint cinammon LTS

**Comment by apricotbucket28** [comment]
Duplicate https://github.com/zed-industries/zed/issues/14326
