### ISSUE TITLE
No keystrokes while inputting in CJK with IME

### ISSUE THREAD

**Issue by csmoe** [zed-industries/zed#15258]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The input.rs example in gpui does not print keystrokes when inputting CJK words with IME
![20240726144455_rec_](https://github.com/user-attachments/assets/57e5f5ab-d63e-4801-9fbf-c82da15692a5)

### Environment

Zed: v0.146.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
This might be intentional? Do you have some use case where keystrokes are needed in the middle of IME composition?

**Comment by shenjackyuanjie** [comment]
预期的是 在输入输入法的时候也会有输入事件嘛？
(这玩意算个老大难问题, 毕竟输入法就是为了代理你的输入事件
我也感觉是故意这么整的, 毕竟这里的输入事件应该是被输入法屏蔽了

**Comment by notpeter** [comment]
I think this is working as intended.  If you have a use case where it would be appropriate (and possible) to capture keystrokes mid-IME composition, please comment and we can reopen.
