### ISSUE TITLE
Vim `ciw` and friends not working in v0.145.1

### ISSUE THREAD

**Issue by felipecruz91** [zed-industries/zed#15268]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi,

Since v0.145.1 the vim `ciw` does not change the entire word anymore. Same broken behavior for `diw`.

### Environment

macOS Sonoma Version 14.5 (23F79)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by vbhavsar** [comment]
`ciw` works for me in 0.145.1.

**Comment by felipecruz91** [comment]
@vbhavsar I don't think it is. Please find the recording attached where you can see the keys that are pressed (`ciw`) and how the word doesn't change after that.


https://github.com/user-attachments/assets/79df07ac-444f-4183-8ee4-fa793f8eb457

**Comment by vbhavsar** [comment]
That's strange. It is definitely working for me. Can you share your `~/.config/zed/settings.json`?

**Comment by felipecruz91** [comment]
```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "theme": "Tokyo Night",
  "vim_mode": true,
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "ui_font_family": "Zed Sans",
  "relative_line_numbers": true,
  "language_overrides": {
    "Make": {
      "hard_tabs": true,
      "tab_size": 4
    }
  },
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "git": {
    "inline_blame": {
      "enabled": false
    }
  }
}
```

**Comment by vbhavsar** [comment]
@felipecruz91 Sorry, I'm at a loss. Maybe @ConradIrwin has some insights?

**Comment by ConradIrwin** [comment]
I made a bunch of changes to key bindings in 0.145.1.

is it possible you copy pasted the old vim map into your personal key map. If so it would be broken

if not, can you also share your current key map and we can see if there are conflicts

**Comment by felipecruz91** [comment]
Deleting the key map file at `~/.config/zed/keymap.json` fixed it. Thank you both.
