### ISSUE TITLE
ruff extension: sort imports

### ISSUE THREAD

**Issue by bersace** [zed-industries/zed#15264]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

Thanks for ruff extension !

ruff has two formatting command : one for basic style (spacing, quoting, etc.) and another for sorting imports.

For now, ruff extension does only the first one. This lead to ruff complaining about import order, even after `editor::Format` call.

The workaround is to use an external formatter like this:

``` json
  "languages": {
    "Python": {
      "formatter": {
        "external": {
          "command": "bash",
          "arguments": ["-c", "ruff check --select I --fix - | ruff format -"]
        }
      },
      // "formatter": { "language_server": { "name": "ruff" } },
      "format_on_save": "on",
      "language_servers": ["pyright", "ruff"]
    }
  }
```

ruff consider import sorting as a lint fix, not a formatting issue. Actually, user expect formatting to fix import sorting. Would you consider fixing import in ruff extension ? I don't know if ruff server handle this.

Regards,
Étienne

**Comment by osiewicz** [comment]
Try the following as your `formatter`/`format_on_save` setting:
```
      "formatter": [ // Or format_on_save
        { "code_actions": { "source.organizeImports.ruff": true } },
        { "language_server": { "name": "ruff" } }
      ]
```

This syntax is only applicable to latest Preview (0.146.0). It'll execute the code action for import organization first and then run the formatting.

**Comment by bersace** [comment]
@osiewicz you're awesome !

**Comment by osiewicz** [comment]
Thanks :)
