### ISSUE TITLE
Unable to enable hints for tailwindcss

### ISSUE THREAD

**Issue by tranvlnh26** [zed-industries/zed#15265]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Unable to enable hints for tailwindcss.
my setting:

```
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `zed: Open Default Settings` command
// from the command palette
{
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "JetBrains New Dark"
  },
  "lsp": {
    "tailwindcss-language-server": {
      "settings": {
        "classAttributes": ["class", "className", "ngClass", "styles"]
      }
    },
    "$LANGUAGE_SERVER_NAME": {
      "initialization_options": {
        "preferences": {
          "includeInlayParameterNameHints": "all",
          "includeInlayParameterNameHintsWhenArgumentMatchesName": true,
          "includeInlayFunctionParameterTypeHints": true,
          "includeInlayVariableTypeHints": true,
          "includeInlayVariableTypeHintsWhenTypeMatchesName": true,
          "includeInlayPropertyDeclarationTypeHints": true,
          "includeInlayFunctionLikeReturnTypeHints": true,
          "includeInlayEnumMemberValueHints": true
        }
      }
    },
    "eslint": {
      "settings": {
        "codeActionOnSave": {
          "rules": ["import/order"]
        }
      }
    }
  },
  "languages": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
}
```

### Environment

Device name	LAPTOP-48TGT8D1
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	2CF61366-7D9C-4700-AC6C-529B253572E9
Product ID	00328-90000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I'm not well-versed in our tailwindcss support, but the `"$LANGUAGE_SERVER_NAME"` bits of your config are definitely incorrect, they should instead be inside the `tailwindcss-language-server` block like so:

```json
  "lsp": {
    "tailwindcss-language-server": {
      "settings": {
        "classAttributes": ["class", "className", "ngClass", "styles"],
        "initialization_options": {
          "preferences": {
            "includeInlayParameterNameHints": "all",
            "includeInlayParameterNameHintsWhenArgumentMatchesName": true,
            "includeInlayFunctionParameterTypeHints": true,
            "includeInlayVariableTypeHints": true,
            "includeInlayVariableTypeHintsWhenTypeMatchesName": true,
            "includeInlayPropertyDeclarationTypeHints": true,
            "includeInlayFunctionLikeReturnTypeHints": true,
            "includeInlayEnumMemberValueHints": true
          }
        }
      }
    }
  },
```

**Comment by tranvlnh26** [comment]
> I'm not well-versed in our tailwindcss support, but the `"$LANGUAGE_SERVER_NAME"` bits of your config are definitely incorrect, they should instead be inside the a specific lsp language server block.
> 
> E.g. for `tailwindcss-language-server`:
> 
> ```json
>   "lsp": {
>     "tailwindcss-language-server": {
>       "settings": {
>         "classAttributes": ["class", "className", "ngClass", "styles"],
>         "initialization_options": {
>           "preferences": {
>             "includeInlayParameterNameHints": "all",
>             "includeInlayParameterNameHintsWhenArgumentMatchesName": true,
>             "includeInlayFunctionParameterTypeHints": true,
>             "includeInlayVariableTypeHints": true,
>             "includeInlayVariableTypeHintsWhenTypeMatchesName": true,
>             "includeInlayPropertyDeclarationTypeHints": true,
>             "includeInlayFunctionLikeReturnTypeHints": true,
>             "includeInlayEnumMemberValueHints": true
>           }
>         }
>       }
>     }
>   },
> ```

I try and it failed
