### ISSUE TITLE
Unable to create file with same name as existing directory

### ISSUE THREAD

**Issue by moesy** [zed-industries/zed#15288]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When attempting to create a new file that has the same name as an existing directory in the Zed IDE, an "already exists" error is encountered. This prevents the creation of files that share names with directories, which can be a valid and desired operation in some cases.

**Steps to Reproduce**
- Open Zed IDE
- Navigate to a directory where you have write permissions
- Attempt to create a new file with the same name as an existing directory in that location

In my case I have a directory named "build" and I am trying to create a file called "BUILD" in the root of my project.

### Environment

Zed: v0.146.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>
Caused by:
    Is a directory (os error 21)
2024-07-26T16:35:05.477048Z [ERROR] creating file "......./mydir/BUILD"

</pre></details>

**Comment by notpeter** [comment]
What filesystem are you using? APFS / HFS+ are case-insensitive filesystems and you cannot have a directory named `build` and a file named `BUILD` in the same parent directory.

<img width="335" alt="Screenshot 2024-07-26 at 17 36 58" src="https://github.com/user-attachments/assets/ef3bcc17-216b-4d8c-a42b-7a602552b9b9">
