### ISSUE TITLE
`tab_size` maybe not work on ubuntu 22.04

### ISSUE THREAD

**Issue by aohanhongzhi** [zed-industries/zed#15320]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://zed.dev/docs/configuring-zed

### Environment

ubuntu 22.04

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/417f5aef-3870-4801-8d2f-27ca70aad6e6)

![image](https://github.com/user-attachments/assets/c7dd2e9f-855c-4ad2-bc7a-c85125d5e9cb)

maybe I need set up Indent  (Spaces or Tab)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
1. Please provide a more complete explanation of what you're trying to do, what you expected to happen and what actually happened.
2. Please include your Zed environment as requested in the issue template ('zed: copy system specs into clipboard' from the command palette, ctrl-shift-p)
3. `editor.insertSpaces` is not a valid Zed settings key (that's from vscode)

Usually golang projects use gofmt which uses tabs by default.  Are you trying to use 4 spaces instead? See also: [`hard_tabs`](https://zed.dev/docs/configuring-zed#hard-tabs).
