### ISSUE TITLE
Settings doesn't auto-complete for extension provided languages

### ISSUE THREAD

**Issue by fcolecumberri** [zed-industries/zed#15342]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have installed the extension to support *CSV* (I have tried with both huacnlee's and weartist's), so now Zed understands that CSV files are CSV (I can see them in the bottom part, in the language section).
However if I add:

```json
{
  "languages": {
    "CSV": {
      "soft_wrap": "prefer_line"
    }
  }
}
```

On the settings, zed just ignores the soft_wrap.

Also the autocomplete don't complete to CSV.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux X11 Garuda unknown
Memory: 62.7 GiB
Architecture: x86_64

Garuda is Arch/Linux

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you demonstrate the behavior you're seeing and explain how to you expect it to operate?  If I remember correctly `prefer_line` wraps after something is 500-ish columns wide (`MAX_LINE_LEN = 1024`, MAX_LINE_LEN / 2 minus a few columns the line numbers in the gutter I think) which works correctly for me:

<img width="442" alt="Screenshot 2024-07-28 at 10 32 31" src="https://github.com/user-attachments/assets/d170de74-c865-4208-98a4-5c42cfbadda4">

Perhaps you were looking for `"soft_wrap": "editor_width"`?

**Comment by fcolecumberri** [comment]
Ok, sorry, I just realize I should have tried with `editor_width`, sorry.

Still, it would be nice if the autocomplete in settings, also autocompleted custom installed languages.
