### ISSUE TITLE
Black hole register in Vim mode

### ISSUE THREAD

**Issue by idr4n** [zed-industries/zed#15367]
### Check for existing issues

- [X] Completed

### Describe the feature

To my knowledge, Zed's Vim mode already has some registers implementation (namely `+` and `*`).

It would be great if the "black hole" register `_` is also added, so I can define a mapping for `d` in which it performs the delete operation without saving it to any register. For example, I would like to define these keymaps:

```json
"d d": ["workspace::SendKeystrokes", "\" _ d d"]
"D": ["workspace::SendKeystrokes", "\" _ D"]
"d i w": ["workspace::SendKeystrokes", "\" _ d i w"]
```

Similarly, when I paste on a selection (visual mode), I don't want to loose the previous yanked text:

```json
"p": ["workspace::SendKeystrokes", "\" _ d P"]
```

Thanks in advance!

**Comment by baptisteArno** [comment]
No workaround for this? I really don't like that behavior 🙄

**Comment by ConradIrwin** [comment]
The black hole register was fixed in normal mode in v0.153 (and in visual mode after #18418)

**Comment by idr4n** [comment]
@ConradIrwin thanks a lot for looking into this.

I just tested it out, and while it works if I use the blackhole register manually (e.g., entering `"_dd` deletes the whole line without yanking it or copying it to the clipboard when `"use_system_clipboard": "always",), I still haven't managed to use it in a keymap. For example, this is not working for me:

```
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "d d": ["workspace::SendKeystrokes", "\" _ d d"],
      "x": ["workspace::SendKeystrokes", "\" _ x"]
      "d i w": ["workspace::SendKeystrokes", "\" _ d i w"]
    }
  },
```

It seems like any mention to the Vim registers in the documentation has been removed as well. **Perhaps I'm missing something**. Apologies if I am.

Thanks again!

**Comment by amao** [comment]
@idr4n You can do like this:

"x": ["workspace::SendKeystrokes", "\" shift-_ x"]

**Comment by ConradIrwin** [comment]
`workspace::SendKeystrokes` is unfortunately recursive (it's on my list to fix this; and maybe give it a better syntax). You have to first bind the "d"/"x" to a different key, this should work:

```
{
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "ctrl-shift-d": ["vim::PushOperator", "Delete"],
      "ctrl-shift-x": "vim::DeleteRight",
      "d d": ["workspace::SendKeystrokes", "\" _ ctrl-shift-d d"],
      "x": ["workspace::SendKeystrokes", "\" _ ctrl-shift-x"],
      "d i w": ["workspace::SendKeystrokes", "\" _ ctrl-shift-d i w"]
    }
  }
```

**Comment by idr4n** [comment]
Nice! Thanks a lot @ConradIrwin. That is indeed working for me.

This is a full set of keybindings adjustments that I would normally use:

```json
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "ctrl-shift-d": ["vim::PushOperator", "Delete"],
      "ctrl-shift-x": "vim::DeleteRight",
      "ctrl-shift-c": ["vim::PushOperator", "Change"],
      "ctrl-shift-cmd-c": "vim::ChangeToEndOfLine",
      "d d": ["workspace::SendKeystrokes", "\" _ ctrl-shift-d d"],
      "x": ["workspace::SendKeystrokes", "\" _ ctrl-shift-x"],
      "d i w": ["workspace::SendKeystrokes", "\" _ ctrl-shift-d i w"],
      "c l": ["workspace::SendKeystrokes", "\" _ ctrl-shift-c l"],
      "c c": ["workspace::SendKeystrokes", "\" _ ctrl-shift-c c"],
      "c e": ["workspace::SendKeystrokes", "\" _ ctrl-shift-c e"],
      "c i w": ["workspace::SendKeystrokes", "\" _ ctrl-shift-c i w"],
      "C": ["workspace::SendKeystrokes", "\" _ ctrl-shift-cmd-c"],
      "m m": ["workspace::SendKeystrokes", "\" + ctrl-shift-d d"],
      "m e": ["workspace::SendKeystrokes", "\" + ctrl-shift-d e"],
      "m i w": ["workspace::SendKeystrokes", "\" + ctrl-shift-d i w"]
    }
  },
  {
    "context": "Editor && vim_mode == visual",
    "bindings": {
      "ctrl-shift-d": "vim::VisualDelete",
      "ctrl-shift-x": "vim::VisualDelete",
      "ctrl-shift-c": "vim::Substitute",
      "d": ["workspace::SendKeystrokes", "\" _ ctrl-shift-d"],
      "x": ["workspace::SendKeystrokes", "\" _ ctrl-shift-x"],
      "c": ["workspace::SendKeystrokes", "\" _ ctrl-shift-c"],
      "m": ["workspace::SendKeystrokes", "\" + ctrl-shift-d"]
    }
  },
```
