### ISSUE TITLE
Freezed zed

### ISSUE THREAD

**Issue by ArtemIsmagilov** [zed-industries/zed#15386]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After correction installing and running Zed, application is freezing.
I checked openGL, not problem, this tool correctly showing.
the advice on your official website when saying that you need to update opengl or check it did not work.

It would be great if you also add Zed to the Ubuntu apt repo

### Environment

Not needed

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ArtemIsmagilov** [comment]
In general, all interaction in the application is very slow. and also overclocks my cpu by 100%. I believe that rust, by its signature, should be the least demanding compared to other idle, so this application is actually not possible to use.

**Comment by SomeoneToIgnore** [comment]
I'm sure that issue was already reported in https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+freezes+

https://github.com/zed-industries/zed/issues/14763 in particular
