### ISSUE TITLE
X11: layout switching doesn't work

### ISSUE THREAD

**Issue by marcospb19** [zed-industries/zed#15388]
Reopen of #15380, but more specific.

### Describe the bug / provide steps to reproduce it

It's necessary to restart Zed after switching keyboard layout for it to work.

Example:
1. Run `setxkbmap us`.
2. Open Zed.
3. Run `setxkbmap br abnt2`.
4. Try typing quotes, and you'll realize it's still stuck in the `us` layout.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux X11 arch unknown
Architecture: x86_64

**Comment by marcospb19** [comment]
Possibly related to #14053.

**Comment by XDeme1** [comment]
Can you try #15059 and see if it fixes this issue?

**Comment by marcospb19** [comment]
https://github.com/zed-industries/zed/pull/15059 fixed the issue :) ty
