### ISSUE TITLE
Zed renders ">=" as "⩾"

### ISSUE THREAD

**Issue by imbev** [zed-industries/zed#15381]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a file containing `>=` in Zed

Observe the visual replacement of `>=` with `⩾`

This bug causes confusion and a discrepancy between Zed and other text editors.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland fedora 40
Memory: 30.7 GiB
Architecture: x86_64

**Comment by SomeoneToIgnore** [comment]
It's called "ligatures" and is not a bug.
Consider opening default settings and searching for "ligatures" to see how you can turn them off, or use a font without them.
