### ISSUE TITLE
Fuzzy search palette should prioritize most recently used files.

### ISSUE THREAD

**Issue by Fingel** [zed-industries/zed#15393]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm not sure if this is a bug or intended behavior. 

The fuzzy search in the ctrl+p seems to be (when all else is equal) listed in alphabetic order. While this seems like good default behavior, it would be nice to bump up results of recently used/open buffers. There does seem to be some indication of this with the "rewind time" icon, but it doesn't seem to effect the results:

![image](https://github.com/user-attachments/assets/32a4ccac-acf8-44c0-9726-778b6d580b84)

This makes it somewhat tedious to work on projects with many same-named files in different directories, as the files you are actually working on aren't necessarily placed in the top of the fuzzy list.

Again, I notice the "rewind time" icon is present and it would make sense that those files get some kind of priority, so I'm wondering if this is actually a bug?

Great work on Zed!

Operating System: Linux, on Wayland.
Zed version: Preview 0.146.1

**Comment by SomeoneToIgnore** [comment]
It's a very small input that causes a lot of tastes to collide.

Current, default, behavior is dictated by other feedback, where people disliked exactly the opposite: despite the query being input, the history items were always in the top, making navigation to the first non-history match a chore in many cases.

Ergo the compromise default behavior now: we do try to bubble the history items to the top, but bubble up better query matches if there are any. 
In the case of the screenshot, the match score seems to be even (same letters, same sequence of them, same number of segments in the parent path), but the `base` parent path is just earlier alphanumerically ergo it's on the top.

If you change your keybindings and add

```json
{
  "context": "Workspace",
  "bindings": {
    "cmd-p": ["file_finder::Toggle", { "separate_history": true }]
  }
}
```

history items will always stick to top, even if they are score matched worse.
