### ISSUE TITLE
Automatic scrolling to the last line (e.g. tail log files)

### ISSUE THREAD

**Issue by fwcd** [zed-industries/zed#15420]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if Zed had a way to automatically "stay scrolled to the bottom line" even as a file gets appended. This would make viewing log files a lot more convenient.

### If applicable, add mockups / screenshots to help present your vision of the feature

It seems as if Zed already implements this to some degree, but only if the last line is at the top (at which point the logs above it aren't visible, so that makes it not very useful):

https://github.com/user-attachments/assets/5a569669-e08b-4112-88bf-c84e477f705d

I can see why the current behavior would be useful in an editing context, so perhaps the best solution would be having some kind of toggle for this, like in VSCode's output panel:

![image](https://github.com/user-attachments/assets/0d2a684c-55b4-4c62-8e0e-fb25471ce0bb)

(Sorry if there is already a way of doing this, I couldn't find it at least)

**Comment by notpeter** [comment]
I like it.

In the meantime as a workaround I use a task with `tail -f`:
```json
  {
    "label": "tail zed logs",
    "command": "tail -f ~/Library/Logs/Zed/zed.log"
  },
```

**Comment by notpeter** [comment]
I'm going to close in favor of:
- https://github.com/zed-industries/zed/issues/18737
- https://github.com/zed-industries/zed/issues/21276

Thanks for reporting.
