### ISSUE TITLE
Option to "Trash" file not in project root

### ISSUE THREAD

**Issue by Jayy001** [zed-industries/zed#15430]
### Check for existing issues

- [X] Completed

### Describe the feature

If a file isn't in the project root, there's no "trash" or "delete" option in the right-click menu.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/33425a5d-d750-4545-90d2-8819713009ed)

**Comment by notpeter** [comment]
This has been fixed at some point.
<img width="342" alt="Screenshot 2024-10-29 at 10 30 57" src="https://github.com/user-attachments/assets/ced8b430-1dc2-4f71-891b-366d8f7ab649">
Thanks for reporting.
