### ISSUE TITLE
Support common python refactoring

### ISSUE THREAD

**Issue by rowillia** [zed-industries/zed#15458]
### Check for existing issues

- [X] Completed

### Describe the feature

Users coming from other editors/IDEs like VSCode or PyCharm are expecting the same basic refactoring tools available in those tools.

I recognize this may be a bit tricky as Pyright doesn't offer any of these features, only Pylance [doesn't support anything more than type checking](https://github.com/microsoft/pyright/issues/4263#issuecomment-1335585261).  The astral folks appear to be working on a typechecker of their own (https://github.com/astral-sh/ruff/tree/main/crates/red_knot) but I don't think it's ready for external use.

Maybe we can create a LSP proxy that supports these via CodeActions and supports these in the meantime via something like `libcst`?

In rough order of priority:

- [ ] Automatic Import
- [ ] Extract Method
- [ ] Introduce Variable
- [ ] Inline Method

**Comment by vkramanuj** [comment]
+1, would be very useful for me

**Comment by SomeoneToIgnore** [comment]
Not related to Zed, as it knows nothing about the languages and most probably never will.
Whatever will happen on the LSP/plugin should stay in that tracker.
