### ISSUE TITLE
"Portal request didn't suceed: Other" error when closing file chooser with ESC

### ISSUE THREAD

**Issue by osa1** [zed-industries/zed#15485]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Run "workspace: open" command.
- Press ESC to close the file chooser and cancel the command.

It generates a "Portal request didn't succeed: Other" error, with a "See docs" link to https://zed.dev/docs/linux#i-cant-open-any-files, but (1) the section is empty (2) the problem is not that I can't open any files, actually there isn't a problem. I just closed the file chooser.

Closing the file chooser with the "cancel" button does not generate the same error.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 62.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot_2024-07-30_16-48-56](https://github.com/user-attachments/assets/04b61117-21b6-49a8-9091-cc361b0d8c31)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I wasn't able to generate this on my Linux setup, but I would like to try and reproduce.

Can you share some more details about your setup (Distro, Windows Manager, which XDG portals / File Choose you're using, etc)?

**Comment by osa1** [comment]
Distro: Ubuntu 22.04.4 LTS
WM: i3
XDG portals: not sure how to check, but I have these related packages installed: `xdg-desktop-portal`, `xdg-desktop-portal-gnome`, `xdg-desktop-portal-gtk`.

**Comment by edy-tanto** [comment]
Ubuntu 24.04 LTS, having the same issue here

**Comment by MartinLaskowski** [comment]
[Using i3 window manager on Ubuntu 24.xx]

Perhaps related: I get a blank screen (or so I thought) upon running 'workspace: open' but now realize that this is in fact the file picker, just not the entirety of it is in view. The blank section populates with folder contents if I type random stuff that triggers the search.

A workaround: if I do 'Mod + F' to toggle full screen mode on and then off again, the file picker window seems to see the error of its ways and resize correctly such that I can now see all the contents, and the sidebar which until now was left of screen somewhere, languishing in the shadows.

Hope this might help.
