### ISSUE TITLE
Step Trough Words When Using Copilot. 

### ISSUE THREAD

**Issue by physics515** [zed-industries/zed#15487]
### Check for existing issues

- [X] Completed

### Describe the feature

In VS Code for instance when an inline Copilot response is returned you can use `cntrl + right`  to approve the response word by word instead of all or nothing. This is incredibly useful because the long tail of the response may not be accurate but the first line may be.

**Comment by SomeoneToIgnore** [comment]
We have it

![image](https://github.com/user-attachments/assets/fab82da1-1aaf-4708-8573-a1ec3e693679)


(the top entry has the keybinding, the bottom entry is left for compatibility reasons)

**Comment by notpeter** [comment]
Looks like the default keybindings is `alt-right` on Linux and MacOS
https://github.com/zed-industries/zed/blob/99bc90a372155f66ca0c6846c36e861575a96501/assets/keymaps/default-linux.json#L124

https://github.com/zed-industries/zed/blob/99bc90a372155f66ca0c6846c36e861575a96501/assets/keymaps/default-macos.json#L155

But VSCode uses `ctrl-right` (Linux/Windows) and `cmd-right` on MacOS.
<img width="804" alt="Screenshot 2024-07-30 at 12 54 30" src="https://github.com/user-attachments/assets/2f4e9a30-5fbe-4683-9788-6884a7569711">

**Comment by SomeoneToIgnore** [comment]
I would love to have it changed to `ctrl-right` as Supermaven integration always forces me to hit cmd-z when jumping over the words.

**Comment by notpeter** [comment]
> I would love to have it changed to `ctrl-right` as Supermaven integration always forces me to hit cmd-z when jumping over the words.

This is in main with #15495.
