### ISSUE TITLE
Clangd stopped showing function docs after 0.144.4 -> 0.145.1 update

### ISSUE THREAD

**Issue by mrvladus** [zed-industries/zed#15498]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Functions docs provided by clangd lsp dissappeared after update. I've tried to install previous version and it worked fine. Then updated and issue comes back.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland fedora 40
Memory: 7.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Before update:

![Снимок экрана от 2024-07-30 20-48-55](https://github.com/user-attachments/assets/7f979ed9-84f2-4f55-98ca-5c860b434825)

After:

![Снимок экрана от 2024-07-30 20-49-22](https://github.com/user-attachments/assets/30f05511-97a1-4039-8b1e-60ca1c8f5d1d)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16431822/Zed.log)

</pre></details>

**Comment by mrvladus** [comment]
Still present in **0.155.2**. How can I help test this?

**Comment by SomeoneToIgnore** [comment]
If you could check `debug: open language server logs` and check all RPC messages (and other related logs, just in case) in each version, it might become more clear.

**Comment by mrvladus** [comment]
I've done same actions in **0.144.4** and **0.155.2**. Here is the logs:

<details> 
<summary>0.144.4</summary>

```
stderr: I[12:17:44.467] <-- initialized
stderr: I[12:17:44.467] <-- workspace/didChangeConfiguration
stderr: I[12:17:44.467] <-- textDocument/didOpen
stderr: I[12:17:44.468] --> textDocument/publishDiagnostics
stderr: I[12:17:44.468] Failed to find compilation database for /var/home/vlad/Documents/GitHub/Errands/src/data.c
stderr: I[12:17:44.468] ASTWorker building file /var/home/vlad/Documents/GitHub/Errands/src/data.c version 0 with command clangd fallback
stderr: [/var/home/vlad/Documents/GitHub/Errands/src]
stderr: /usr/bin/clang -x c -I/usr/include/libadwaita-1 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/cairo -I/usr/include/libxml2 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/graphene-1.0 -I/usr/lib64/graphene-1.0/include -I/usr/include/fribidi -I/usr/include/appstream -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/gtksourceview-5 -resource-dir=/var/home/vlad/.local/share/zed/languages/clangd/clangd_19.1.0/lib/clang/19 -- /var/home/vlad/Documents/GitHub/Errands/src/data.c
stderr: I[12:17:44.558] <-- workspace/didChangeConfiguration
stderr: I[12:17:45.128] Built preamble of size 13560208 for file /var/home/vlad/Documents/GitHub/Errands/src/data.c version 0 in 0.66 seconds
stderr: I[12:17:45.129] Indexing c17 standard library in the context of /var/home/vlad/Documents/GitHub/Errands/src/data.c
stderr: I[12:17:45.153] --> textDocument/publishDiagnostics
stderr: I[12:17:45.213] Indexed c17 standard library: 2819 symbols, 27 filtered
stderr: I[12:17:45.769] <-- textDocument/hover(2)
stderr: I[12:17:45.771] --> reply:textDocument/hover(2) 1 ms
stderr: I[12:17:46.307] <-- workspace/didChangeConfiguration
stderr: I[12:17:47.470] <-- textDocument/hover(3)
stderr: I[12:17:47.471] --> reply:textDocument/hover(3) 1 ms
```

</details>

<details> 
<summary>0.155.2</summary>

```
stderr: I[12:16:30.936] <-- initialized
stderr: I[12:16:30.936] <-- workspace/didChangeConfiguration
stderr: I[12:16:30.937] <-- textDocument/didOpen
stderr: I[12:16:30.938] --> textDocument/publishDiagnostics
stderr: I[12:16:30.938] Failed to find compilation database for /var/home/vlad/Documents/GitHub/Errands/src/data.c
stderr: I[12:16:30.938] ASTWorker building file /var/home/vlad/Documents/GitHub/Errands/src/data.c version 0 with command clangd fallback
stderr: [/var/home/vlad/Documents/GitHub/Errands/src]
stderr: /usr/bin/clang -x c -I/usr/include/libadwaita-1 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/cairo -I/usr/include/libxml2 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/graphene-1.0 -I/usr/lib64/graphene-1.0/include -I/usr/include/fribidi -I/usr/include/appstream -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/gtksourceview-5 -resource-dir=/var/home/vlad/.local/share/zed/languages/clangd/clangd_19.1.0/lib/clang/19 -- /var/home/vlad/Documents/GitHub/Errands/src/data.c
stderr: I[12:16:31.594] Built preamble of size 13560208 for file /var/home/vlad/Documents/GitHub/Errands/src/data.c version 0 in 0.65 seconds
stderr: I[12:16:31.594] Indexing c17 standard library in the context of /var/home/vlad/Documents/GitHub/Errands/src/data.c
stderr: I[12:16:31.616] --> textDocument/publishDiagnostics
stderr: I[12:16:31.671] Indexed c17 standard library: 2819 symbols, 27 filtered
stderr: I[12:16:31.939] <-- workspace/didChangeConfiguration
stderr: I[12:16:31.973] <-- workspace/didChangeConfiguration
stderr: I[12:16:31.973] <-- workspace/didChangeConfiguration
stderr: I[12:16:32.097] <-- workspace/didChangeConfiguration
stderr: I[12:16:32.461] <-- workspace/didChangeConfiguration
stderr: I[12:16:35.505] <-- textDocument/hover(2)
stderr: I[12:16:35.507] --> reply:textDocument/hover(2) 1 ms
stderr: I[12:16:36.567] <-- textDocument/hover(3)
stderr: I[12:16:36.570] --> reply:textDocument/hover(3) 2 ms
```

</details>

Doesn't seem much different.

**Comment by SomeoneToIgnore** [comment]
Those are the server logs (highlighted in dark on my next screenshot), but I'm more curious about the `RPC messages oone` from the same screenshot below:

![image](https://github.com/user-attachments/assets/4ad9d32b-96b5-44a0-88fe-287024bab0f1)

which might be different.

The first thing to try the same place in the same example and see if `// Send:` data that Zed sends is different.
![image](https://github.com/user-attachments/assets/0ec8057f-c965-4de5-969f-9a1235c5fe67)

These logs can grow, but In our case, it's `textDocument/hover` that we're interested in mainly, which narrows the search.

**Comment by SomeoneToIgnore** [comment]
Interesting, that's not what I would've expected but thank you for sharing.
Now I can only think of running from the sources and bisecting, as not aware of any rendering changes that well.

**Comment by mrvladus** [comment]
I found that completion popover has the doc string, but mouse hover don't.

![Снимок экрана от 2024-10-26 19-09-31](https://github.com/user-attachments/assets/85cf6e13-48f4-48d1-a332-e2628093fa28)

**Comment by shahamran** [comment]
Hi, after a bit of tinkering, I found that the issue is that the response markdown contains `---` that are _meant_ to be parsed as horizontal rules, but instead are parsed as yaml metadata blocks, effectively discarding everything in the middle.

Taking the example from one of the comments above:
~~~
### function `errands_data_read`

---     <-- parsed as yaml metadata begin
→ `char *`
Function to read a file into a string

---     <-- parsed as yaml metadata end
```cpp
static char *errands_data_read()
```
~~~

To verify that, I added this line at the start of crates/markdown/src/parser.rs:parse_markdown():
```rust
    options.remove(pulldown_cmark::Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
```
and got a correctly rendered hover popover.

I see that metadata was intentionally and explicitly removed in 556449128e5e7613b674bcc05e159448ba477fd8, so I'm not sure what's the way forward here.

As I see it the options are:

* Language-specific workaround for clangd in Zed.
* Opening an issue in clangd requesting a different, non-ambiguous, rule syntax (e.g. adding more `-` to the response).
* Revert the "metadata hiding feature".

@SomeoneToIgnore FYI, and thanks for the guidance :)

**Comment by Release-Candidate** [comment]
> Hi, after a bit of tinkering, I found that the issue is that the response markdown contains `---` that are _meant_ to be parsed as horizontal rules, but instead are parsed as yaml metadata blocks, effectively discarding everything in the middle.

But three dashes are (more or less the only) universally supported Markdown markup for a horizontal line. And source documentation being Markdown isn't that uncommon, I'd say

**Comment by shahamran** [comment]
@Release-Candidate I think it's just part of the [commonmark spec][1]. I also think that 3 _or more_ dashes are parsed as horizontal line, this is why I suggested changing clangd's response.

But the more I think of it, the more I think that ignoring this metadata syntax (perhaps with an option to turn it on) is the correct approach.

**Comment by shahamran** [comment]
Hi @ConradIrwin, any idea if this will be added to the next release?
