### ISSUE TITLE
Repl output doesn't scroll horizontally

### ISSUE THREAD

**Issue by yaroslavyaroslav** [zed-industries/zed#15491]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the quite long output of the kernel it's got cut by the window width.

On the screenshot below there's no way to see the farthest right text of the output

related to #14855 and #5273

### Environment

Zed: v0.147.0 (Zed Dev 65c63defccac454cc92bf972f728563b13383015)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1624" alt="Screenshot 2024-07-30 at 18 41 10" src="https://github.com/user-attachments/assets/a9bb6505-d061-4b8f-9e09-eff9d8ecff2b">

**Comment by amanaknows** [comment]
Poopy peepee not to the rescueeee

Nah fr tho check my pinned

**Comment by amanaknows** [comment]
> Poopy peepee not to the rescueeee
> 
> Nah fr tho check my pinned

Boy*

**Comment by SomeoneToIgnore** [comment]
@amanaknows , this is the second issue filled with useless unreadable comments.
This is inappropriate here and urge you to stop.
Here's a link with more details: https://zed.dev/docs/code-of-conduct

**Comment by rgbkrk** [comment]
Closed by https://github.com/zed-industries/zed/pull/15713.
