### ISSUE TITLE
Repl output isn't copiable

### ISSUE THREAD

**Issue by yaroslavyaroslav** [zed-industries/zed#15494]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The output provided by kernel is unable to copy, despite that cursor become "text like" on hover those.

related to https://github.com/zed-industries/zed/issues/14855 and https://github.com/zed-industries/zed/issues/5273 and #14855

### Environment

Zed: v0.147.0 (Zed Dev 65c63defccac454cc92bf972f728563b13383015)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1624" alt="Screenshot 2024-07-30 at 18 41 10" src="https://github.com/user-attachments/assets/24705f2b-2a5b-465f-bcbc-094e1e985493">

**Comment by rgbkrk** [comment]
Started working on this in https://github.com/zed-industries/zed/pull/16649
