### ISSUE TITLE
`Projects: open remote`: Add a field for "label"

### ISSUE THREAD

**Issue by danfuzz** [zed-industries/zed#15502]
### Check for existing issues

- [X] Completed

### Describe the feature

The list of remote servers shown by `Projects: open remote` uses the remote command as the label, which gets cut off after a couple dozen characters or so. If you have two servers whose commands differ after that — as I actually do! — you can't tell the difference between them by looking at the label. Perhaps an explicit "label" field could be added?

Screenshot of my situation (slightly redacted):

<img width="517" src="https://github.com/user-attachments/assets/7e9ef296-1c3e-42ce-ae51-5e23c579d544">

### If applicable, add mockups / screenshots to help present your vision of the feature

Mockup:
<img width="517" src="https://github.com/user-attachments/assets/4c19d911-ec63-4efa-baab-e047a045db17">

**Comment by mrnugget** [comment]
We now have a `nickname` field that can be set in the settings or in the UI.

https://github.com/user-attachments/assets/1fbf8da5-1713-45b6-9766-e9852fff2f20
