### ISSUE TITLE
Symbol Documentation Not Appearing on Hover.

### ISSUE THREAD

**Issue by MEXdave1997** [zed-industries/zed#15505]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When hovering over a symbol, I only get the symbol with the related arguments, and not any comments/documentation associated with the symbol.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 7.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is the behavior I expect, and was getting until recently (example displayed is in VS Code)
![image](https://github.com/user-attachments/assets/c59574ca-2ad0-43ac-93bd-f7c04a2dadf9)

And this is what I get in Zed:
![image](https://github.com/user-attachments/assets/90951ab1-cd84-42f4-b0d9-d53fdd2c3435)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16432845/Zed.log)

</pre></details>

**Comment by mrvladus** [comment]
Same with me #15498

**Comment by MEXdave1997** [comment]
Dug through the log, and it seems like this is part of the issue:

` 2024-07-31T11:59:07.811183406-07:00 [WARN] request completed with error: failed to connect to the server`

Not sure if it's on Zed's side, or if it's on clangd's side. But it's something to

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/zed-industries/zed/issues/15498

Thanks for reporting.
