### ISSUE TITLE
Allow disabling of git tracking in scrollbar

### ISSUE THREAD

**Issue by lukeed** [zed-industries/zed#15500]
### Check for existing issues

- [x] Completed

### Describe the feature

There exists a `git.git_gutter = "hide"` configuration option, but that toggles the (left) gutter. I'd like to keep that one and separately disable the git-tracking status in the (right) scrollbar. This is because the deletions look/feel like syntax error positions, especially coming from VSC.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Image](https://github.com/user-attachments/assets/6ab1733c-356c-4696-8515-4aef0e1c2436)

**Comment by osiewicz** [comment]
You can use `  "scrollbar": { "git_diff": false },` to disable the diff in a scrollbar.

**Comment by lukeed** [comment]
Oh, thanks. Then I guess the issue could be made about the config location? Expected it to fall under git umbrella, especially since gutter config is there.

I'll close this either way though
