### ISSUE TITLE
Document extensions.toml

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#15504]
### Check for existing issues

- [X] Completed

### Describe the feature

- [x] Document extensions.toml: [developing extensions](https://zed.dev/docs/extensions/developing-extensions#directory-structure-of-a-zed-extension)
- [ ] slash_commands
- [ ] indexed_docs_providers
- [x] grammars [language extensions#grammar](https://zed.dev/docs/extensions/languages#grammar)
- [x] language_servers: [language servers](https://zed.dev/docs/extensions/languages#language-servers)

**Comment by notpeter** [comment]
I updated the description with links to new docs from 
- #15876 

I also added a TBD for `slash_commands` and `indexed_doc_providers` for when those fully land as they are currently in flux.
https://github.com/zed-industries/zed/blob/0eb96c72e39c4eb7bab91cad3a9620e3cfc3f45c/docs/src/extensions/developing-extensions.md#L26
