### ISSUE TITLE
Comment a block of text with azerty fr layout don't work 

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#15526]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in french azerty layout we don't allay have the `/` directly  without `SHIFT` it does a `:`
![image](https://github.com/user-attachments/assets/fa59ce75-a7d2-4d8b-a1e0-12b5dbe4730b)
so we need to do if we want to comment a block of text in vscode by exemple

`CTRL + SHIFT + /`

![image](https://github.com/user-attachments/assets/90b30007-33d2-42c0-a0cf-89383a66779f)

In zed if don't work with the azerty layout it would be cool to make it works great ( and add some documentation for shortcut and layout ^^)

In gnome 
![image](https://github.com/user-attachments/assets/4a8e4c29-865c-498a-a275-89a45a66d7d4)

![image](https://github.com/user-attachments/assets/769b56c3-d0df-4b36-a86a-7a40288c20c1)

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland bazzite 40
Memory: 23.4 GiB
Architecture: x86_64

**Comment by yodatak** [comment]
The command https://github.com/zed-industries/zed/blob/c78ea0df7ee21594049c146521a0dffbae629e9d/assets/keymaps/default-linux.json#L272

**Comment by notpeter** [comment]
A little confused, are you reporting the fact that the `ctrl-/` shortcut doesn't work for you? Or just that `ctrl-/` is not an ergonomic shortcut on AZERTY FR layout keyboards?

If the latter, you could add custom keybind to your ~/.config/zed/keymap.json: 
```
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-:": ["editor::ToggleComments", { "advance_downwards": false }], 
    }
  }
]
```

**Comment by yodatak** [comment]
Sorry to not be clear it not something about ergonics for me but  we must use ctrl-shift-/ in vscode and in zed ctrl-shift-/ don't work.
On azerty layout ctrl-/ is imposible we must use ctrl-shift-/ 

i try to make a video ifs not clear

**Comment by yodatak** [comment]
[Capture vidéo du 2024-08-01 19-33-10.webm](https://github.com/user-attachments/assets/b9048227-f38c-4931-bb87-930c339d8924)

The problem in video

the divide is the / on my numpad so with a laptop it dont exist

**Comment by apricotbucket28** [comment]
The 0.146.3 release mentions:
> Linux: Fixed typing shortcuts like ctrl-/ on some systems.

Could you try updating Zed and see if the issue is fixed?

**Comment by yodatak** [comment]
Its works now thankkks a lot <3

**Comment by yodatak** [comment]
It was fixed in  this PR 
https://github.com/zed-industries/zed/pull/15013/files
