### ISSUE TITLE
Improve Contrast in default themes

### ISSUE THREAD

**Issue by msehnout** [zed-industries/zed#15521]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello,

I'm trying out Zed and it looks really cool, but I find it hard to read the text using the default themes. For example comparing to PyCharm on Linux or XCode on macOS, the default seems harder to read. Would it be possible to include a default theme with higher contrast? I'm not a big fan of user defined themes, because there is always something unreadable.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot from 2024-07-31 09-53-45](https://github.com/user-attachments/assets/70b6d76a-7f4a-43f0-9ae7-3f1c8efc12fc)

**Comment by piegamesde** [comment]
All default light themes are using pretty muffled colors for the background, which just makes them look gray and sad compared to all my other applications.

**Comment by notpeter** [comment]
More examples as I consolidate issues into one place:

One Light when you have changed entries in the file tree. (credit: @nathanael-ruf)
![image](https://github.com/user-attachments/assets/14454991-efa3-49e8-89d5-4559b2fd2648)

Copilot completions (One Dark)
<img width="365" alt="image" src="https://github.com/zed-industries/zed/assets/145113/2cb45be8-f5d5-482a-96d0-19a09d0996c5">

Copilot completions (Solarized Dark) is better
<img width="364" alt="image" src="https://github.com/zed-industries/zed/assets/145113/e8f0b36d-0788-41e5-8a2f-33b123fb3773">

Copilot completions Atelier Sulphurpool Light (only `/playdate` is copilot): 
<img width="403" alt="image" src="https://github.com/zed-industries/zed/assets/145113/e7372cd7-2ce3-4bcc-8a19-7105f1037e68">

**Comment by donjan** [comment]
I too find Zed hard to work with due to the bleached appearance. In this screenshot of (VSCode - Zed - Geany), the two other editors are much easier to read, and that's with the highest contrast light theme I could find for Zed.
![Screenshot from 2024-09-04 17-19-33](https://github.com/user-attachments/assets/7c3b8fa9-864a-4299-92dd-e875bc40a33b)
On Linux, the font weight setting might be an issue, as changing it to 100 or 900 doesn't make any difference. The glyphs in Zed just look malnourished!

**Comment by notpeter** [comment]
Atelier Sulphurpool Light also has poor contrast in non-AI completions as 
<img width="401" alt="Screenshot 2024-09-24 at 16 42 15" src="https://github.com/user-attachments/assets/38c51a9c-ddbc-477f-80d4-f652a5433087">
![image](https://github.com/user-attachments/assets/cfbaa88b-8313-4c79-a5b4-413ddf93abd4)
As originally reported in https://github.com/zed-industries/zed/issues/4876

**Comment by notpeter** [comment]
The hover windows in Dark theme also offer nearly no contrast compared to the main background color.
![image](https://github.com/user-attachments/assets/4a91b07e-7abb-4420-87ee-76dcbcd69823)
![image](https://github.com/user-attachments/assets/1a69b2a8-43e6-4af1-896b-7cac72a68d5c)
![image](https://github.com/user-attachments/assets/794fcd8d-0403-41a9-8fc3-01aa5732f900)

Originally reported here:
- https://github.com/zed-industries/zed/issues/11351
