### ISSUE TITLE
REPL: env detection not working properly

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#15563]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

let's create 2 different virtual environments, one with `polars` as a dependency, one without

### create first env
```sh
# create dir
>  mkdir env1

>  cd env1

# create virtual env
>  python3 -m virtualenv .venv 

>  source .venv/bin/activate
>  pip install ipykernel 
>  python -m ipykernel install --user
>  pip install polars
>  cd - 
```

### Same thing but without the additional dependency 
```sh
# create dir
>  mkdir env2

>  cd env2

# create virtual env
>  python3 -m virtualenv .venv 

>  source .venv/bin/activate
>  pip install ipykernel 
>  python -m ipykernel install --user
```

Now create a simple file in both directories
```py
# env1/main.py
# %% Cell 1
import polars as pl
```

```py
# env2/main.py
# %% Cell 1
import polars as pl
```

I would fully expect running 'Cell 1' from `env2` to fail as the dependency is not installed in that virtualenv, but it instead uses the other one. 

### Environment

Zed: v0.146.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/baab0bf1-5b09-4a65-9f0b-6d46b1cf690c)

![image](https://github.com/user-attachments/assets/c85ee2f8-9ce3-4bad-a08d-c67db354f354)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by rgbkrk** [comment]
For the moment, I recommend installing the kernel using `python -m ipykernel install --user --name myenv --display-name "Python (myenv)"` and then configuring it as the one to use: https://zed.dev/docs/repl#changing-kernels

I totally agree we should have more environment detection and selection built in.

**Comment by Rupin817** [comment]
@rgbkrk sorry I do not fully understand the configuration link you provided there? Are we saying we do not have any buttons or pragmatically way to switch between kernel created in diff env?
