### ISSUE TITLE
Custom keymap binding not working

### ISSUE THREAD

**Issue by corneliusio** [zed-industries/zed#15561]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently have the following keybindings in my `~/.config/zed/keymap.json`. This has been working for quite some time as expected, however two or three updates ago the `cmd-i` has stopped executing `search::SelectNextMatch` when the search buffer is open. 

`buffer_search::Deploy` and `search::SelectPrevMatch` are both being executed as expected, it's only `search::SelectNextMatch` that won't execute when the defined keybinding is used.

This also appears to only be happening with `cmd-i`. I've gone through the default keymap bindings to see what other bindings are assigned to `cmd-i` and found only a single binding within the `Editor` context which is why I've added the `zed::NoAction` binding, however this doesn't appear to change anything.

```json
[

    {
        "context": "Editor",
        "bindings": {
            "cmd-i": "zed::NoAction",
        }
    },
    {
        "context": "Editor && mode == full",
        "bindings": {
            "cmd-i": ["buffer_search::Deploy", { "focus": true }]
        }
    },
    {
        "context": "BufferSearchBar",
        "bindings": {
            "enter": "buffer_search::Dismiss",
            "cmd-i": "search::SelectNextMatch",
            "cmd-shift-i": "search::SelectPrevMatch"
        }
    }
]
```

### Environment

Zed: v0.146.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Do this work?
```json
  {
    "context": "Editor",
    "bindings": {
      "cmd-i": "search::SelectNextMatch"
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-i": ["buffer_search::Deploy", { "focus": true }]
    }
  },
  {
    "context": "BufferSearchBar",
    "bindings": {
      "enter": "buffer_search::Dismiss",
      "cmd-i": "search::SelectNextMatch",
      "cmd-shift-i": "search::SelectPrevMatch"
    }
  },
```

**Comment by corneliusio** [comment]
@notpeter Yes, thank you! If I add these bindings to both the `Editor` and `BufferSearchBar` contexts it does work as expected. Is there any concern that this behavior changed recently or is this the intended behavior now?

**Comment by notpeter** [comment]
Currently it's a little difficult to custom remap keys which are in the default keymap and ensure it keeps working for future release.  Currently there is no way to signal "unmap `cmd-i` in every context where it's mapped so I can use it and instead you have to explicitly unmap (assign to `null`) and/or remap in the same context(s) where it is defined.

So if we change the context of an existing keybind (e.g. from `Editor` to `ContextEditor > Editor`) you may have to add additional overrides for the new context(s) when they appear in a release. Not great, but for the moment that's how it is.

The easiest way to reference all possible places a key might be mapped is to look in the [assets/keymap folder](https://github.com/zed-industries/zed/blob/main/assets/keymaps/) in the source tree. There are potentially up to three keymaps which apply: [default-macos.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-macos.json) or [default-linux](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-linux.json), [vim.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/vim.json) if you use vim and any platform specific compatibility keymaps if you're using them (e.g. [macos/jetbrains.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/macos/jetbrains.json)).
