### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by rengler-noodle** [zed-industries/zed#15576]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

go to install sql extension, nothing happens

2024-07-31T22:04:02.465775Z [INFO] installing extension sql latest version
2024-07-31T22:04:07.601197Z [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-07-31T22:04:07.601835Z [ERROR] error downloading extension: request or operation took longer than the configured timeout time

i noticed the github link is for `https://github.com/evrsen/zed-sql`
which redirects to `https://github.com/evrensen467/zed-sql`
so maybe that's the problem?

### Environment

Zed: v0.146.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I was not able to reproduce your issue with v0.146.3 on MacOS (tested aarch64 and x86_64).
Maybe a transient Github or network connectivity issue?

Thanks for the update about the github username change. This should not impact your ability to install (github quietly redirects) but I opened a PR on the extensions repo to update that:
- https://github.com/zed-industries/extensions/pull/1177

Can you restart zed and try again and see if it works?

**Comment by rengler-noodle** [comment]
Interesting, still today i can't install it even after restart. i'll try reinstalling the entire app

**Comment by notpeter** [comment]
Are you perhaps in a network restricted environment (corporate proxy, ISP with aggressive carrier NAT, great firewall of china, etc)?

Can you try via an alternate network connection (phone tethering, etc) to rule that out?
