### ISSUE TITLE
Unable to Execute zed-remote-server-stable Command on Ubuntu Server 22.04 Due to Missing libssl.so.1.1

### ISSUE THREAD

**Issue by j3r0lin** [zed-industries/zed#15599]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using SSH to remotely connect to an Ubuntu Server 22.04 development environment, the execution of the zed-remote-server-stable command fails due to a dependency on libssl.so.1.1, which has been deprecated in Ubuntu 22.04.

#### Error Log:
```txt
2024-08-01T10:04:34.823854Z [ERROR] failed to run command: .local/zed-remote-server-stable: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by .local/zed-remote-server-stable)
```

### Environment

no

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Thanks for reporting.  We had run into this internally as well.

**Comment by reiderbelimo** [comment]
I have run into the same while trying to debug remote dev using ssh://localhost:2222/home/me/work.

**Comment by cweagans** [comment]
Also ran into this on debian bookworm.

**Comment by WintersMichael** [comment]
Not sure if this is related, but FYI I'm hitting this on Arch too even though libssl.so.1.1 is still available here.

```bash
$ ll /usr/lib/libssl.so.1.1
-rwxr-xr-x 1 root root 556792 Jul  7 02:45 /usr/lib/libssl.so.1.1

$ pacman -F /usr/lib/libssl.so.1.1
usr/lib/libssl.so.1.1 is owned by core/openssl-1.1 1.1.1.t-1
```

**Comment by WintersMichael** [comment]
I've discovered that libssl 1.1 needs to be available on the remote server.  Once corrected, this now works.

**Comment by sandhawalia** [comment]
Confirming for 

## client
```
macOS Sonoma Version 14.6.1
```

## remote
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
