### ISSUE TITLE
Terminal toggle (show-hidden) should be added.

### ISSUE THREAD

**Issue by ahmedmelihozdemir** [zed-industries/zed#15610]
### Check for existing issues

- [X] Completed

### Describe the feature

I done my job with terminal i dont want to close it but i want hide it. Zed has togglefocus in terminal settings.  togglevisible should be add.

**Comment by arnaudsm** [comment]
Seems you can use `workspace::ToggleBottomDock` for that

**Comment by notpeter** [comment]
`workspace::ToggleBottomDock` has a default shortcut of `ctrl-j` (Linux) `cmd-j` (Mac).
