### ISSUE TITLE
Flutter/Dart Support does not show definitions correctly.

### ISSUE THREAD

**Issue by srihariash999** [zed-industries/zed#15638]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The definiton of items in zed is different from what I see in other editors for a flutter project. Somehow Dart LSP is not able to figure out the types and definitions of inbuilt dart libraries too.  I am adding screenshots to describe what I mean.

This is hovering over 'run' method from Process class from dart:io library.

Zed:
<img width="991" alt="image" src="https://github.com/user-attachments/assets/d4a630c8-80a7-4d7c-b73d-29a528f13628">

VS Code:

<img width="807" alt="image" src="https://github.com/user-attachments/assets/6829fe23-069b-4841-a30b-cb1e86c9c9d7">

### Environment

Zed: v0.146.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by srihariash999** [comment]
An update @notpeter. I removed my current installed Flutter sdk completely, cleaned up any dart things installed via homebrew, then did a fresh installation of flutter. This issue does not appear now. 
I still have no answer to why it was working okay on vscode. 

Your call to keep this issue open or close it. Ideally zed and vs code should behave same as the LSP is the same. But this just might be some quirk of dartls or something wrong with my installation.

**Comment by notpeter** [comment]
I'll close. But if you run into again, feel free to comment and we can reopen. Thanks!
