### ISSUE TITLE
pyright does weird stuff

### ISSUE THREAD

**Issue by timptner** [zed-industries/zed#15644]
### Check for existing issues

- [X] Completed

Related issues:
#13541 #13206 #12883 #11508 #10587 #7296 #8541 #7646 #5524

### Describe the bug / provide steps to reproduce it

> Pyright complaints about unresolvable imports and undefined values.

Fresh install of Zed and starting a python project with virtualenv pyright highlights all non-standard library imports as unresolvable. This is fine because pyright doesn't know anything about my virtualenv. But it also marks any python standard functions, e. g. `print()` or `int()`.

(1) Using `./pyproject.toml` it recognizes all custom imports but no longer standard library. Still does not know anything about standard python functions.

```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
```

(2) Using `./pyrightconfig.json` same results as with `./pyproject.toml`.

```json
{
  "venvPath": ".",
  "venv": ".venv"
}
```

(3) Using global `~/.config/zed/settings.json` it does find all third-party libraries installed inside .venv and also finds standard libraries. But it still does not know about standard functions (print, int, dict, sorted, ...).

```json
{
  "lsp": {
    "pyright": {
      "settings": {
        "python": {
          "pythonPath": ".venv/bin/python"
        }
      }
    }
  }
}
```

I'm quite sure that some weeks ago I could solve all pyright errors by using `pyproject.toml` or `pyrightconfig.json`. But in the meantime nothing seems to work anymore. Using combinations of those 3 options above `pyrightconfig.json` will overwrite `pyconfig.toml` and `settings.json` in their behaviour.

### Environment

Zed: v0.146.4 (Zed)
OS: macOS 13.6.7
Memory: 8 GiB
Architecture: x86_64

Python is installed via brew (python@3.12). PyRight is **not** installed via brew or as global pip package. (Brew stops one with a warning when trying `python3 -m pip install <package>` outside of an virtualenv.)

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16461015/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @timptner, do you have any projects you could share that show the issue? I'm not able to reproduce this on my end - here's a project where print is being recognized by pyright:

<img width="1168" alt="SCR-20240802-kfob" src="https://github.com/user-attachments/assets/410313d0-2b6a-4ab1-bcdb-1394df06d916">

We've had some issues where restarting Zed, after creating a `pyrightconfig.json` file, would correct some weird pyright issues - do your issues still persist after restarting Zed?

**Comment by timptner** [comment]
Freshly project:

<img width="1440" alt="Bildschirmfoto 2024-08-02 um 22 29 08" src="https://github.com/user-attachments/assets/7e0d69a0-685e-43bb-9d0c-d518c1b8e13d">

Restartet Zed multiple times in between those 3 options above. Even restarted Zed before creating this project and also tried `zed .` while CWD is this project, which some other issue mentioned as solution.

**Comment by timptner** [comment]
<img width="388" alt="Bildschirmfoto 2024-08-02 um 22 31 29" src="https://github.com/user-attachments/assets/ee491f98-e6a7-4b1f-befa-46801d73989a">

**Comment by timptner** [comment]
I noticed that each time I restart Zed it always checks for pyright updates and everytime downloads pyright. Don't know if this is expected behaviour.

**Comment by timptner** [comment]
Just checked with my second workstation (debian) and there I don't get the pyright errors

**Comment by imbev** [comment]
I've encountered the same problem:

1. Open empty directory
2. `uv init`
3. `uv venv`
4. Set pyproject.toml dependencies to `dependencies = ["requests"]`
5. `uv pip compile pyproject.toml -o requirements.txt`
6. `uv pip sync requirements.txt`
7. Add `import requests` to src/test/\_\_init\_\_.py

There will be a warning with `Pyright: Import "requests" could not be resolved from source`.

As @timptner said, this can be resolved by adding the following to pyproject.toml:

```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
```

However this is a tweak that isn't needed when working in other editors.

**Comment by timptner** [comment]
Even `.toml` files show weird errors.

<img width="388" alt="Bildschirmfoto 2024-08-07 um 22 50 44" src="https://github.com/user-attachments/assets/5cc066b1-19af-420c-8a14-7fff9d476b68">

**Comment by ikheifets** [comment]
the same behaviour, venv's libraries pyright recognizing correctly, but pythons builtins not:

```
Pyright: "str" is not defined
```

P.S. Previously it worked fluently, it seems that something has been broken after update

**Comment by timptner** [comment]
Just installed `pyright` with pip and checked the files.

```shell
(.venv) aiven@MacBook-Pro test % pyright --version
pyright 1.1.375
(.venv) aiven@MacBook-Pro test % pyright main.py
0 errors, 0 warnings, 0 informations
```

Seems like it's a local problem of the pyright version inside Zed.

**Comment by ikheifets** [comment]
@timptner for me working this workaround:

```
rm -rf ~/Library/Application\ Support/Zed/languages/pyright
```

After that need to restart Zed that will automatically download new pyright version

**Comment by timptner** [comment]
> @timptner for me working this workaround:
> 
> ```
> rm -rf ~/Library/Application\ Support/Zed/languages/pyright/
> ```
> 
> After that need to restart Zed and it will automatically download latest pyright version

This has solved it!

**Comment by imbev** [comment]
This is still a problem on the Linux version of Zed.

After running this command, the newly downloaded pyright has the same issues.

`rm -rdf ~/.local/share/zed/languages/pyright/`

**Comment by ikheifets** [comment]
@imbev you have another [problem](https://github.com/zed-industries/zed/issues/15644#issuecomment-2269878889). In our case pyright can't recognize python stdlib, in your case third-patry libs. In your case [docs](https://zed.dev/docs/languages/python#virtual-environments) should help

**Comment by bhanusanghi** [comment]
I encountered the same on zed preview, forced reinstall of pyright by deleting the existing pyright as suggested by @timptner
