### ISSUE TITLE
Ctrl-t broken in new version

### ISSUE THREAD

**Issue by rongyi** [zed-industries/zed#15664]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I remapped my Ctrl-t to pane::GoBack，but not work after upgrading to 0.146.3

### Environment

![图片](https://github.com/user-attachments/assets/09bcb799-9025-461a-aee4-72c45aaa57c9)

**Comment by rongyi** [comment]
still not work in version 0.146.4

**Comment by JosephTLyons** [comment]
Hey @rongyi, do you have any issue with removing the key binding from the pane context and just setting it directly in editor:

```json
{
  "context": "Editor",
  "bindings": {
    "ctrl-t": "pane::GoBack"
  }
}
```

**Comment by rongyi** [comment]
@JosephTLyons thanks for your advice, now it works again!
