### ISSUE TITLE
Language Support for Julia

### ISSUE THREAD

**Issue by DarianNwankwo** [zed-industries/zed#15661]
### Check for existing issues

- [x] Completed

### Describe the feature

I have a workflow that involves C++, Python and Julia. I'd love to switch over to Zed, but it doesn't have language support for Julia. The Julia community is increasingly growing and I think supporting this language would be nice.

**Comment by osiewicz** [comment]
There's an extension for Julia. Have you tried it out?
You can install an extension by going to the extensions store (search for `zed: Extensions` in your command palette) and searching for Julia there.

**Comment by JosephTLyons** [comment]
As Piotr said, we do have an extension for this! I'm going to close this issue out. Feel free to open an issue if you have any problems with getting the extension to work.
