### ISSUE TITLE
H and L to switch tabs while in Vim mode

### ISSUE THREAD

**Issue by danielzsh** [zed-industries/zed#15670]
### Check for existing issues

- [X] Completed

### Describe the feature

In LazyVim, pressing "H" and "L" in normal mode allow you to quickly go to the tab to the left/right respectively; I would love to see this in Zed.

**Comment by danielzsh** [comment]
If this suggestion seems reasonable, I can also try implementing it :)

**Comment by m4saurabh** [comment]
add this to your `keymap.json`
```jsonc
[
  {
    "context": "VimControl && !menu",
    "bindings": {
      // ... other normal and visual mode keymaps
      "L": "pane::ActivateNextItem",
      "H": "pane::ActivatePrevItem",
    }
  },
]
```

**Comment by danielzsh** [comment]
OH tysm that worked!

**Comment by patrickvonplaten** [comment]
Great exactly what I was looking for as well!

**Comment by Wozacosta** [comment]
@m4saurabh 

I had to switch from `ActivatePrevItem` to `ActivatePreviousItem`.
