### ISSUE TITLE
Toggle git blame keyboard shortcut not working: `cmd-alt-g b`

### ISSUE THREAD

**Issue by pavles6** [zed-industries/zed#15676]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After upgrading to [0.146.3](https://zed.dev/releases/stable/0.146.3) I'm no longer able to toggle git blame sidebar via the shortcut `cmd+opt+G B`

Note: I'm using vim mode, just in case that somehow affects this defect

### Environment

Zed: v0.146.4 (Zed)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

**Comment by amanaknows** [comment]
👾

**Comment by maxdeviant** [comment]
> Note: I'm using vim mode, just in case that somehow affects this defect

Does it work if you disable Vim mode?

**Comment by pavles6** [comment]
> Does it work if you disable Vim mode?

Nope, even after disabling it It still won't open git blame side-bar

**Comment by notpeter** [comment]
This is really odd. On my Macbook (Arm) it's broken everywhere (Zed Stable 0.146.4, Zed Preview 0.147.2, Zed Nightly 0.148.x and compiled from main). It's also broken on multiple old versions of Zed where I know it worked before.  Also broken are the two other binds for `alt-cmd-g` to `search::ToggleRegex` in `ProjectSearchBar` and `ProjectSearchView` contexts.

Crazily on my Intel Mac it's broken in Zed Stable 0.146.4, but on Zed Preview 0.147.2 `cmd-alt-g b` works but `alt-cmd-g` ToggleRegex is also broken, while `alt-cmd-x` bound to the same thing works fine.

Things I've tested:
- empty settings.json and user keymap.json (still broken)
- Blow away Zed workspace `rm -rf ~/Library/Application\ Support/Zed/; rm ~/Library/Caches/dev.zed.Zed* ; rm -rf /Users/peter/Library/Logs/Zed` (still broken)
- mapping other things to `cmd-alt-g b` or `cmd-alt-g x` (also broken)
- custom keybind: `{"context": "Editor", "bindings": {"cmd-alt-b": "editor::ToggleGitBlame"}` (works)

I'm very much at a loss here. But something is fishy with cmd-alt-g 
As a workaround I suggest you create a custom keybind until we can track this down.

**Comment by notpeter** [comment]
Ok. So this should be fixed in Preview/Nightly since this was merged:
- https://github.com/zed-industries/zed/pull/15103

Which explains why it works in Preview on my Intel Macbook (fixed!).
But I have no idea why is still broken for me on my Arm Macbook.

**Comment by JosephTLyons** [comment]
[Zed v0.146.5 ](https://zed.dev/releases/stable/0.146.5) is now published. I think I'll close this out optimistically, but feel free to ping us @pavles6, if you are still hitting the issue after updating.

**Comment by pavles6** [comment]
Everything works now as usual, thank you so much for such a fast patch! You guys rock!
