### ISSUE TITLE
Facing Memory leak issues, High power/memory consumption 

### ISSUE THREAD

**Issue by DataRaj** [zed-industries/zed#15692]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I recently have started using a zed editor, I am developing SPA typescript based applications,  When I use typescript, zed relies too much on node based libraries such as emmets , autocomplete and error detector, such as eslint, prettier, although having a single project running on the system, I still found that around 1.3 Gib of memory usages on single projects, its more than my previous editor, Vs Code, so there might be some optimization issues, please look into them, and try to resolve them 

### Environment

Ryzen - 5500u
linux (Fedora 40) 
gnome(wayland)
8Gib ram

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ghall89** [comment]
I think this might be related to my issue which I posted a few months back. Definitely seems like there's something up with Zed's TypeScript implementation but I haven't seen anything on my or other similar issues which doesn't give me a lot of confidence. In the meantime I'm using VSCode 🤷 

https://github.com/zed-industries/zed/issues/14352

**Comment by rubin55** [comment]
I just noticed I am running into this issue (Arch Linux, kernel 6.11.4, nvidia-dkms, gnome-on-wayland).

In `dmesg`:

```
NVRM: Xid (PCI:0000:01:00): 31, pid=14149, name=zed-editor, Ch 00000055, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC3 GPCCLIENT_ROP_1 faulted @ 0x1_23030000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
```

Reproducible with a few resizes of the window (I'm using the tiling shell extension). Maybe it is significant that I could *not* reproduce this when resizing the window by hand.

**Comment by mikayla-maki** [comment]
There isn't sufficient info to work with this issue, closing in favor of https://github.com/zed-industries/zed/issues/14352
