### ISSUE TITLE
[linux] Auto update fails if rsync is unavailable

### ISSUE THREAD

**Issue by azam** [zed-industries/zed#15701]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am on Arch Linux, installed `zed` using the `install.sh` script and did not have `rsync` installed.
When there is an update, auto update always fails with attached log.
Made a guess based on the source [here](https://github.com/zed-industries/zed/blob/e2eb68abcaacfca3e4fa1209ece1f2f17897b756/crates/auto_update/src/auto_update.rs#L696-L701),  since the error is not something explicitly thrown, I tried installing `rsync`, reran auto update and auto update was successful.
Raising this issue anyway just in case someone else encounters the same.

It would be great if either:
1. this requirement is documented
2. more specific message in the log
3. `rsync` equivalent behavior is implemented

### Environment

Zed: v0.146.5 (Zed)
OS: Linux Wayland arch unknown
Memory: 60.6 GiB
Architecture: x86_64
GPU: AMD Radeon 760M (RADV GFX1103_R1) || radv || Mesa 24.1.4-arch1.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-08-02T22:13:42.86325792+09:00 [INFO] downloaded update. path:"/tmp/zed-auto-updateR7hKNx/zed-linux-x86_64.tar.gz"
2024-08-02T22:13:43.655703485+09:00 [ERROR] auto-update failed: error:No such file or directory (os error 2)
</pre></details>

**Comment by sirNugg3ts** [comment]
Can confirm that had the same issue, installing rsync solved the issue.
make installer.sh install rsync too perhaps?

**Comment by kaangiray26** [comment]
I can also confirm that installing rsync solved the issue for me.

**Comment by Rizaaal** [comment]
Yep, same for me. Installing rsync solve the issue. Thanks azam!

**Comment by Ammaraly** [comment]
> Can confirm that had the same issue, installing rsync solved the issue. make installer.sh install rsync too perhaps?

I can also confirm this resolved the issue on arch (using the preview, manually installed)
