### ISSUE TITLE
Implement options other than `system` for the `terminal.shell` setting

### ISSUE THREAD

**Issue by snoopdouglas** [zed-industries/zed#15726]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, `"system"` is the only valid option for the `terminal.shell` setting:

![Screenshot from 2024-08-03 10-22-23](https://github.com/user-attachments/assets/d64a5b27-b9b4-40a0-b8d7-86199eaba3d3)

I'd like to be able to set this to either:

- An absolute path to a executable
- An executable within `PATH` (like in the screenshot)
- An appropriately quoted arguments list as if I were running a command from my system shell

In my case, I prefer to have my system shell set to bash, but run fish as a custom command in terminal emulators.

This is different (but related) request to #5320. Apologies if it's already on the roadmap, I can't find an issue for this specifically.

**Comment by claire-west** [comment]
Configuration is documented here: https://zed.dev/docs/configuring-zed#shell

While not all things are included on that page, many of the settings that are absent are present in the default configuration accessed with `open default settings` from the command palette.

In your case, this configuration should do the trick:

```json
"shell": {
    "program": "fish"
}
```

Or with arguments:


```json
"shell": {
  "with_arguments": {
    "program": "/bin/fish",
    "args": ["--arg1"]
  }
}
```

**Comment by snoopdouglas** [comment]
Aah nice one, thanks, that works great - I'll close this. Do you know whether changing the autocomplete to additionally suggest `{}` is on the roadmap?
