### ISSUE TITLE
Can not invoke inline assistant if terminal is dragged out of dock

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#15729]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open a terminal.
- Drag it out of dock and into a individual pane.
- Invoke the inline assistant and notice nothing is happened.

### Environment

Zed: v0.147.2 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Thanks for the feedback @failable - definitely a papercut we should fix!

Just to note it for the devs, this problem also exists when using `workspace: new center terminal` command, which implies that any terminal in the center stage exhibits this issue, and isn't caused from dragging it out from the dock.
