### ISSUE TITLE
ESLint not work for json files

### ISSUE THREAD

**Issue by hyoban** [zed-industries/zed#15747]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Follow the guide from [eslint-plugin-jsonc](https://ota-meshi.github.io/eslint-plugin-jsonc/user-guide/)

It seems ESLint now only works with the following languages.

https://github.com/zed-industries/zed/blob/f8234aec6a18a4a6cf677e8537db3f57b15f8e7a/crates/languages/src/lib.rs#L241

### Environment

Zed: v0.146.5 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by KennyxLan** [comment]
Is this issue still open and going to be fixed by a commit? Or should it be addressed via settings as mentioned [here](https://github.com/zed-industries/zed/pull/16086) ?

**Comment by hyoban** [comment]
```json
{
  "languages": {
    "JSON": {
      "language_servers": ["eslint"]
    },
    "JSONC": {
      "language_servers": ["eslint"]
    }
  }
}
```

**Comment by phsd0** [comment]
Don't forget to include json-language-server itself or you will loose some of its features
```json
"JSONC": {
  "language_servers": ["eslint", "json-language-server"]
},
"JSON": {
  "language_servers": ["eslint", "json-language-server"]
}
```
