### ISSUE TITLE
Zed Missing Title Bar / can't move window [nixos]

### ISSUE THREAD

**Issue by sidharthpunathil** [zed-industries/zed#15757]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* I am not able to drag and move the nixos window with mouse
* I can double tap on the top bar to maximise  
* There is no close button or maximise button for zed

### Environment

![image](https://github.com/user-attachments/assets/bc255272-46a1-4e81-868e-680cd3fb263e)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/1d6d6939-fa12-4537-9a63-42814564a7db)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Could you please paste your Zed environment (most importantly Zed version)?

Open the command palette (`ctrl-shift-p`) and `zed: copy system specs to clipboard`.

**Comment by JuliusDeBoer** [comment]
The fact that there is no close or maximize button makes me think this issue is similar to https://github.com/zed-industries/zed/issues/16344. Could you please tell us which version of zed you are running like notpeter suggested?

**Comment by blessedbythestorm** [comment]
Getting the same on nixos with plasma KDE.
I seem unable to move the main editor window by dragging it with the mouse. 

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 30.6 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
@blessedbythestorm How did you install Zed? The Zed version (v1.0.0) and OS (Linux 1.0.0) you provided do not correspond to what should be displayed from a Zed official binary.

Are you perhaps running [NixOS on the 24.05 channel](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=zed-editor) which is shipping v0.135.2 (from [2024-05-15](https://github.com/zed-industries/zed/releases/tag/v0.135.2))? Can you try with [v0.149.3](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=zed-editor) from the NixOS unstable channel?

----

I don't know the NixOS packaging policies but it is definitely a waste of Zed team members' time to have users reporting issues against an orphaned pre-release unofficial build of Zed which has been abandoned from NixOS maintainers.

@GaetanLepage and @niklaskorz: You two are listed as NixOS package maintainers for the `zed-editor` package.  I understand that the `24.05` channel is meant to receive "fewer" updates than `unstable` but I think users are extremely poorly served by being served an known broken build.  I noticed that other packages in `24.05`, for example [firefox](https://search.nixos.org/packages?channel=24.05&show=firefox&from=0&size=50&sort=relevance&type=packages&query=firefox), are continuously updated (current Firefox v129.0.2 is from 2024-08-20; two days ago).

Is it possible to give Zed the same treatment in NixOS `24.05`?

**Comment by blessedbythestorm** [comment]
@notpeter  I installed it via the nix package manager.

 ``` 
 environment.systemPackages = [
    pkgs.zed-editor
  ];
  ```
Sorry, I assumed getting it through the stable channel would have the latest stable version. 
Will give the unstable channel a try.

**Comment by niklaskorz** [comment]
@notpeter That won't be possible, as the latest Zed releases require Rust 1.80 to build. As Rust 1.80 introduced backwards incompatible regressions, I doubt it will be backported to 24.05.

**Comment by notpeter** [comment]
I didn't realize it was Rust thing. Sigh. I don't think we're likely to do that at this stage.   Thanks for explaining.

I wish we could pull that old package from NixOS `24.05` completely.

**Comment by GaetanLepage** [comment]
> I wish we could pull that old package from NixOS `24.05` completely.

I think that this is feasible/sensible.
If the version currently on `nixos-24.05` is not stable and not suited for usage (especially in a supposedly "stable" software repository), then I guess that we can make this happen.

I definitely understand you not wanted to get bothered by reports about this version.

**Comment by notpeter** [comment]
Thank you @GaetanLepage, I think everyone will be happier if they can't install a known bad package, I appreciate you taking care of it. Separately, I wanted to express my appreciation of  your maintenance of the package in the first place. Package maintenance is anonymous, largely thankless work, but let me explicitly say: Thank you. We appreciate your efforts.

**Comment by GaetanLepage** [comment]
> Thank you @GaetanLepage, I think everyone will be happier if they can't install a known bad package, I appreciate you taking care of it. Separately, I wanted to express my appreciation of your maintenance of the package in the first place. Package maintenance is anonymous, largely thankless work, but let me explicitly say: Thank you. We appreciate your efforts.

You are welcome ! This is indeed the least worst solution.

I am glad to make it possible for the growing nix user-base to enjoy zed !
We currently only support the linux build. We are waiting for you to switch to the rust-based version of livekit in order to ship the darwin version.

Best of luck with Zed's development :)
