### ISSUE TITLE
How do I deal with Pyright warnings and errors?

### ISSUE THREAD

**Issue by yasainet** [zed-industries/zed#15755]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm new to Python, so apologies if this is a misguided question.

Example.
```
from dotenv import load_dotenv
```

`Pyright: Import "dotenv" could not be resolved`

I always get messages like this.

---

1. `conda activate hogehoge`
2. `pip install -r requirements.txt`

requirements.txt:
```
python-dotenv
```

How can I fix this problem?
If there is any information missing, please ask a question. I will be happy to comment with additional information.

### Environment

```
❯ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac15,8
      Model Number: Z1AU002FMJ/A
      Chip: Apple M3 Max
      Total Number of Cores: 16 (12 performance and 4 efficiency)
      Memory: 128 GB
      System Firmware Version: 10151.121.1
      OS Loader Version: 10151.121.1
      Activation Lock Status: Enabled
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="767" alt="image" src="https://github.com/user-attachments/assets/1dbdcfa2-1700-4bfe-b091-592527758629">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Hey @yasainet, have you tried adding a `pyrightconfig.json` file to the root of your project to tell pyright where to look for the virtual environment? Something like this:

```json
{
  "venvPath": ".",
  "venv": ".venv"
}
```

[Zed Python docs](https://zed.dev/docs/languages/python)

**Comment by yasainet** [comment]
Thank you for your response!

I have also reviewed all the documents you suggested.

However, I have a virtual environment with `miniconda`.

I am sure there are many users who use `conda`, so I would be glad if you could add it to the official documentation.

---

Once again, I have done `conda info` in my environment.
How should I set up `pyrightconfig.json` in this case?

```
❯ conda info

     active environment : base
    active env location : /opt/homebrew/Caskroom/miniconda/base
            shell level : 1
       user config file : /Users/USERNAME/.condarc
 populated config files : /Users/USERNAME/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.5.0=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /opt/homebrew/Caskroom/miniconda/base (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/homebrew/Caskroom/miniconda/base/pkgs /opt/homebrew/Caskroom/miniconda/base/pkgs
                          /Users/USERNAME/.conda/pkgs
       envs directories : /opt/homebrew/caskroom/miniconda/base/pkgs /opt/homebrew/Caskroom/miniconda/base/envs
                          /Users/USERNAME/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.4 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5 .8 aau/0.4.4 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False False
```

**Comment by yasainet** [comment]
Resolved.

1. go to the root directory of Project
2. copy `vim pyrightconfig.json` to
3. enter the following
```
{
  "venvPath": "/opt/homebrew/Caskroom/miniconda/base/envs",
  "venv": "/opt/homebrew/Caskroom/miniconda/base/envs/<envname>"
}
```


That's all I need to solve the problem!
Thank you very much.
