### ISSUE TITLE
`pane::DeploySearch` tooltips do not show keyboard shortcuts

### ISSUE THREAD

**Issue by osa1** [zed-industries/zed#15758]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Buttons at the bottom for opening Project Panel, Outline Panel etc. show the key binding for them in the tooltips.

However in the search pane the buttons for enabling case sensitive (alt-c), word search (alt-w) and other buttons do not shot the key bindings.

Key binding is shown in the Outline Panel button tooltip:

![Screenshot_2024-08-04_09-16-01](https://github.com/user-attachments/assets/4f83d740-6a47-4ba6-9ae1-141089828947)

But not in "Match whole words" button tooltip in search pane:

![Screenshot_2024-08-04_09-16-15](https://github.com/user-attachments/assets/6fd2b4ef-9d39-4e02-911f-adf739b28944)

### Environment

Zed: v0.146.5 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 62.5 GiB
Architecture: x86_64
GPU: AMD Unknown (RADV GFX1101) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mrnugget** [comment]
Fixed by https://github.com/zed-industries/zed/pull/18282
