### ISSUE TITLE
cmd delete then save in the "project diagnostics" tab recovers the file

### ISSUE THREAD

**Issue by kurtbuilds** [zed-industries/zed#15776]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a rust project:

1. Create a file that cargo will throw an error or warning on.
2. Open the project diagnostics tab, confirm that the warning / error from (1) appears.
3. From the project diagnostics tab, select the erroring file in the file pane, and delete it (shift delete to skip the dialog box)
4. cmd+s to save while still in the project diagnostics tab. Reflexively, that's the command I use to "re-run" cargo check / diagnostics.

The bug is that doing (4) causes the file to re-appear, rather than stay deleted.

### Environment

macbook m1 pro / OS X

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
I think this is generally an issue with multi-buffers, as they tend to hold onto the file, even after it is deleted, and any subsequent save to the multi-buffer restores the file.

- https://github.com/zed-industries/zed/issues/9101
