### ISSUE TITLE
how to jump the file use shortcut key in the pane

### ISSUE THREAD

**Issue by 1925381584** [zed-industries/zed#15786]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="538" alt="zed_AyrG1YiwrR" src="https://github.com/user-attachments/assets/2dd66408-50c7-458e-aa49-f70cadc7e51e">

hi, in this pane, does have shortcut key to open the file?

### Environment

system: win10
zed: 0.148

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by m4saurabh** [comment]
You can use the editor command `editor: open excerpts` and `editor: open excerpts split`

![Screenshot_20240805_130942](https://github.com/user-attachments/assets/ffdb50e9-d64b-4e38-8687-8d1872bf2634)
