### ISSUE TITLE
Gleam Syntax Not Updated

### ISSUE THREAD

**Issue by ghivert** [zed-industries/zed#15792]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Gleam 1.4.0 introduces a new syntax with shorthand properties access for records, and the tree-syntax grammar should be updated!

### Environment

Zed: v0.146.5 (Zed)
OS: macOS 14.6.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1912" alt="Capture d’écran 2024-08-05 à 10 58 26" src="https://github.com/user-attachments/assets/3c4cd5f5-8d01-44bf-9dfe-16d3de01ae22">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxdeviant** [comment]
The grammar was updated in https://github.com/zed-industries/zed/pull/15659, but it's pending a new release of the Gleam extension.

It might be a little bit, since currently the Gleam extension depends on an unpublished version of the extension API, and I've been busy with other things.
