### ISSUE TITLE
cmd+enter not add a new line

### ISSUE THREAD

**Issue by ocarreterom** [zed-industries/zed#15794]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The shortcut `cmd+enter` is not working to add a new line.

### Environment

Zed: v0.146.5 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by dwt** [comment]
Looking at the default key bindings it seems that this shortcut is bound in two contexts:

```
  {
    "context": "Editor && mode == full && !jupyter",
    "bindings": {
      "cmd-enter": "editor::NewlineBelow"
    }
  },
  {
    "context": "Editor && mode == auto_height",
    "bindings": {
      "ctrl-enter": "editor::Newline",
      "shift-enter": "editor::Newline",
      "ctrl-shift-enter": "editor::NewlineBelow"
    }
  },
```

I noticed this in the python mode, which should be a full editor mode?

**Comment by JosephTLyons** [comment]
Hey @ocarreterom, can you check the [latest preview build](https://zed.dev/releases/preview/latest) and see that the issue is fixed for you? The changes in preview will be landing in tomorrow's stable release.

**Comment by dwt** [comment]
@JosephTLyons Preview Build performs cmd+enter as expected.

**Comment by ocarreterom** [comment]
@JosephTLyons cmd+enter its working as expected in last preview (0.147.2) 👍

**Comment by JosephTLyons** [comment]
Great! Glad to hear!
