### ISSUE TITLE
`ctrl-enter` does not go to a new line below (vscode keymap)

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#15813]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

pressing `ctrl-enter` does not seem to work even when the keymap is avaliable.

### Environment

Zed 0.146.5
Linux Mint 21.3

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by m4saurabh** [comment]
Duplicate #15794

**Comment by JosephTLyons** [comment]
Hey @sparrowsl, I believe this issue is fixed on the latest preview, and should be in stable tomorrow.
