### ISSUE TITLE
ticked checkbox contrast in dark themes

### ISSUE THREAD

**Issue by deauthe** [zed-industries/zed#15825]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

open the editor for the first time, click any checkbox 

### Environment

macos 14.4.1 (23E224)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

# Theme: Atlier Savanna Dark 
<img width="960" alt="Screenshot 2024-08-06 at 12 17 52 AM" src="https://github.com/user-attachments/assets/d5b51833-8d93-4e51-9e1e-0fd08caa8ae7">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Yeah, the checkbox contrast is definitely not great in:
- Atlier Savanna Dark
- Atlier Health Dark
- Atlier Lakeside Dark
- Atlier Seaside Dark

https://github.com/user-attachments/assets/2a6d6076-5fb9-4edc-8383-c2a4877d59d3

**Comment by notpeter** [comment]
I'm going to consolidate this into another issue:
- https://github.com/zed-industries/zed/issues/15521

Please 👍 to increase visibility and subscribe to track that issue's progress. Thanks for reporting!
