### ISSUE TITLE
Overwrite the clangd ferror-limit setting

### ISSUE THREAD

**Issue by Tackoil** [zed-industries/zed#15839]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm working on a large cpp project with Zed. Is there some way to make `ferror-limit` larger or set to 0 for more file be analyzed? 

The error message is `clang: Too many errors emitted, stopping now`.

- Zed version: 0.146.5
- OS: macOS 15.0 beta 5

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="799" alt="image" src="https://github.com/user-attachments/assets/be6f2323-8b90-4960-aeea-ad6116fab0e9">

**Comment by sleeping-at-night** [comment]
How about setting `-ferror-limit` via to clangd via `.clangd`?

You can setting compile flags for clangd via `.clangd`.
Here one way to config clangd via `.clangd` to set ferror-limit to 100
```.clangd
CompileFlags:
  Add: -ferror-limit=100
```

Here are more infomations about clangd configurations.
https://clangd.llvm.org/config#files
https://clangd.llvm.org/faq#can-you-give-an-example-configuration-file-for-clangd

**Comment by Tackoil** [comment]
> How about setting `-ferror-limit` to clangd via `.clangd`?
> 
> You can setting compile flags for clangd via `.clangd`. Here one way to config clangd via `.clangd` to set `-ferror-limit` to 100
> 
> ```
> CompileFlags:
>   Add: -ferror-limit=100
> ```
> 
> Here are more infomations about clangd configurations. https://clangd.llvm.org/config#files https://clangd.llvm.org/faq#can-you-give-an-example-configuration-file-for-clangd

Thank you. It works quite well on me.
