### ISSUE TITLE
Add path globs to LanguageMatcher

### ISSUE THREAD

**Issue by aohoyd** [zed-industries/zed#15847]
### Check for existing issues

- [X] Completed

### Describe the feature

Inspired by discussion in https://github.com/zed-industries/extensions/pull/746

# The problem
Now the only way to choose a language for file is `path_suffix` configuration option in https://github.com/zed-industries/zed/blob/7cef5b29566dac6d9319e67956136955db1b7535/crates/language/src/language.rs#L616. Sometimes the language to use is not determined by file's extension but file's location or it's name.

# Proposed fix
Extend [LanguageMatcher](https://github.com/zed-industries/zed/blob/7cef5b29566dac6d9319e67956136955db1b7535/crates/language/src/language.rs#L616) with `path_globs` field with a list of globs matching file path.

**Comment by osiewicz** [comment]
We can already use globs for matching languages: https://github.com/zed-industries/zed/pull/12043

**Comment by WhySoBad** [comment]
Hi, 
If I'm not mistaken @aohoyd wanted to add a option for a language extension to specify file paths using globs for which the language of the extension should be used. As far as I can tell #12043 only added support for globs in the user settings but not in the extension settings. 
Should I be wrong, then the documentation about language extensions should be updated accordingly: https://zed.dev/docs/extensions/languages
