### ISSUE TITLE
CLI install overwrites main Zed app when Preview version is present

### ISSUE THREAD

**Issue by ShaikRehan123** [zed-industries/zed#15890]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

So, I've both zed preview and zed on my mac... cause zed preview has one of the feature I am missing on zed, when I do "cli: install" from command bar, it installs to the name "zed". So this replaces the main zed app, is there a way I can have different names for different applications

### Environment

Zed: v0.147.2 (Zed Preview)
OS: macOS 14.2.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
You can create your own symlinks, that's all that `zed: install cli` is doing:

```
ls -la /usr/local/bin/zed*
sudo ln -s /Applications/Zed\ Preview.app/Contents/MacOS/cli /usr/local/bin/zedp
sudo ln -s /Applications/Zed.app/Contents/MacOS/cli /usr/local/bin/zeds
```
