### ISSUE TITLE
Named registers are overwritten when yanking into default register in Vim mode

### ISSUE THREAD

**Issue by bww** [zed-industries/zed#15938]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As of the most recent update, yanking text into the default register seems to simultaneously overwrite other registers.

This appears to have broken in:
Zed 0.147.2 / eb91b716c8f3c94309ed303a16a84ccd8b5f445a

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

In this example, I am:

1. Selecting some text and yanking it into register `a`
2. Yanking different text into the default register
3. Pasting register `a`
4. Pasting the default register

Both pastes are the same text: the contents of the default register.

https://github.com/user-attachments/assets/872863f4-fc6b-41a5-af5e-e7d94545cfba

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bww** [comment]
Just an update, having dealt with this for a while: as far as I can tell, named registers essentially don't work at all. It's not possible to expect that, when yanking text into any particular register, pasting text back from that register at a future point will actually paste the previously-yanked text.

Frequently the register seems to be overwritten by the default or system clipboard register, as the case may be. Although sometimes it seems as though perhaps the paste operation is just using the wrong register rather than the right one being overwritten? It also seems like perhaps it may sometimes be dependent on the mode you're in, normal or visual. It's hard to pin it down, though.

Anyway, it's sort of unusable in its current state. I would think that getting this sort of basic functionality right would be a higher priority than all the AI integrations and collaboration features, but I guess not...

**Comment by okira-e** [comment]
I'd like to update this thread that the version 0.156.2 (could be a version before but I never noticed) has fixed this issue.

**Comment by bww** [comment]
Yes, that appears to be the case. I'll close this issue.
