### ISSUE TITLE
Assistant panel empty if provided model is custom

### ISSUE THREAD

**Issue by uhidontkno** [zed-industries/zed#15935]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Go into your Zed config file and set a model for the assistant that is not an official OpenAI model (eg. `gpt-4o-mini`). For example, making the model value something like `mistralai/Mixtral-8x22B-Instruct-v0.1` when trying to use with a custom OpenAI will cause the assistant panel to be completely empty. The assistant panel is working when you revert the change.

### Environment

Zed: v0.147.2 (Zed)
OS: Linux X11 debian 12
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 4600 (HSW GT2) || Intel open-source Mesa driver || Mesa 22.3.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/25750461-65ca-47c6-a575-9db1304b210b)

**Comment by bennetbo** [comment]
Hey,

to setup a custom model for OpenAI you have to declare the custom model first, something like this:

```json
"language_models": {
  "openai": {
    "version": "1",
    "available_models": [
      {
        "name": "your-model",
        "max_tokens": 10000
      }
    ]
  }
},
"assistant": {
  "default_model": {
    "provider": "open",
    "model": "your-model"
  },
  "version": "2"
}
```

(Also: We changed the way the configuration view works on main already, so it still opens up even if you use "invalid" settings)

**Comment by uhidontkno** [comment]
Thanks
