### ISSUE TITLE
Windows: REPL python formatting spawns command window

### ISSUE THREAD

**Issue by tranvlnh26** [zed-industries/zed#15955]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/user-attachments/assets/264f71b2-ed31-4bf8-85f2-ba95d0987295)

When using Python REPL on windows, autoformat on save spawns a visible command prompt instead of happening invisibly in the background.

**Comment by notpeter** [comment]
Hi @tranvlnh26,

1. Can you edit the issue description to explain further your enhancement request? (What you're looking for the command to do, when would it trigger (format, save, cell execute, etc)
2. Can you edit the issue title to reflect the nature of the request?

**Comment by tranvlnh26** [comment]
> Hi @tranvlnh26,
> 
> 1. Can you edit the issue description to explain further your enhancement request? (What you're looking for the command to do, when would it trigger (format, save, cell execute, etc)
> 2. Can you edit the issue title to reflect the nature of the request?

When launching the REPL or every time the code is formatted, a cmd called to run python will appear. I find it quite annoying. Sorry my English is not good

**Comment by notpeter** [comment]
> > Hi @tranvlnh26,
> > 
> > 1. Can you edit the issue description to explain further your enhancement request? (What you're looking for the command to do, when would it trigger (format, save, cell execute, etc)
> > 2. Can you edit the issue title to reflect the nature of the request?
> 
> When launching the REPL or every time the code is formatted, a cmd called to run python will appear. I find it quite annoying. Sorry my English is not good

Wonderful. This was enough. I've edited the issue to reflect what you've reported, feel free to edit to add more context. 

Please note that Zed is still under development and Windows is not currently a supported platform so this issue may not get fixed quickly.  Thank you for reporting.
