### ISSUE TITLE
Large vertical_scroll_margin breaks ctrl+u and ctrl+d vim shortcuts

### ISSUE THREAD

**Issue by sean-brandenburg** [zed-industries/zed#15950]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

 I'm looking to always keep my cursor in the center of my screen regardless of screen size with a large vertical_scroll_margin, but it doesn't appear to play nicely with vim mode

When setting `vertical_scroll_margin` to a number larger than the number of lines than fit on a single screen, the half page scrolling shortcuts for vim (ctrl+u and ctrl+d) move the screen but the cursor does not move properly (seems like it might be adding the amount of lines that vertical_scroll_margin overflows + the number of lines on a half screen).

Repro steps
- Set `vertical_scroll_margin` to a large number
- Enable vim mode
- go to the top of a file and press ctrl + d
- The screen will have scrolled half a screen, but you won't have a visible cursor on screen
- Tap k to move up one line and you'll find that the cursor is now at the bottom of the document

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/6bb6138b-c217-42d7-b2ff-71a0b9443de6

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by sleeping-at-night** [comment]
I am also opend my the Issue about this problem in #15101.

**Comment by sean-brandenburg** [comment]
@sleeping-at-night Ah, thanks didn't see this. I'll close this issue since it looks like your issue already has some discussion
