### ISSUE TITLE
Markdown Preview Button Disappears When First Line Doesn't Start with Markdown Syntax

### ISSUE THREAD

**Issue by Adhithya03** [zed-industries/zed#15958]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Markdown preview button disappears if the first character of the first line is not a Markdown syntax character (e.g., a hash #).

Steps to reproduce:

1. Create a new Markdown file.
2. In the first line, type any character that is not part of Markdown syntax (e.g., a letter or number).

### Environment

Zed: v0.148.0 (Zed Dev 990774247ecb61ddf69f0325d28eb3b203fc3699)
OS: Windows 10.0.22635
Memory: 15.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 Ti || NVIDIA || 551.68

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Markdown preview icon:

![zed_t5oDulRapa](https://github.com/user-attachments/assets/dec2579c-8e35-4f99-a236-4553dbc83d5e)

It disappears after any character is entered in the first line:

![u0YqFeFeti](https://github.com/user-attachments/assets/83cdd0b1-3fd4-4038-825d-417ae7eebd7b)

If the 1st line starts with say h1 tag

![5zHe32PPCL](https://github.com/user-attachments/assets/c4fbceda-7ba6-4609-ba62-2678143ae384)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bennetbo** [comment]
Thanks for providing a detailed way to reproduce the issue. Should be fixed by #15961!
