### ISSUE TITLE
Cannot type curly brackets to the terminal on a Finnish keyboard layout

### ISSUE THREAD

**Issue by esamattis** [zed-industries/zed#15964]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On Finnish keyboard layout curly brackets are typed using shift+option+8/9. It works on the text editor but not on the terminal. See the video.

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 13.6.7
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/297f226d-37b1-4c15-8cd1-5289a3cde8fd

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by villem** [comment]
Me too, also with Finnish keyboard. Is there any workaround?

**Comment by rooperuu** [comment]
This also affects other symbols like `$` and `|` that are used frequently in the terminal. Looks like the problem is caused by https://github.com/zed-industries/zed/pull/15535. As a workaround, set `terminal.option_as_meta` back to `false`.

**Comment by atlekberg** [comment]
I can confirm that this is also an issue for MacOS with Norwegian keyboard layout.

**Comment by eproxus** [comment]
I have <kbd>Option</kbd>+<kbd>2</kbd> set to generate `@` in my macOS keyboard layout (Swedish) and this is not possible to use in the terminal anymore. Setting the option `terminal.option_as_meta` to `true` or `false` (or removing it) doesn't fix it. It never works.

**Comment by ville-nroc** [comment]
The workaround for me is to put this in config.json


```json
"terminal": {
    "option_as_meta": false
  },
```

**Comment by elevesque-nexapp** [comment]
This is affecting me as well using the bépo layout. Option is used for multiple characters I use very frequently in the terminal like `&`, `~`, `\`, `|`, `{` and `}`.

**Comment by jimmycallin** [comment]
also happens for swedish keyboards

**Comment by htor** [comment]
This issue can be closed
