### ISSUE TITLE
Switching between different Zed windows does not work when full screen

### ISSUE THREAD

**Issue by lrvdijk** [zed-industries/zed#15979]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Have multiple Zed windows open (e.g., different projects)
2. Make one full-screen (macOS green button)
3. Try to switch to the other window with Cmd+`
4. Other window does *not* appear

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
This is a MacOS limitation with how it uses spaces for fullscreen.  You can verify this by creating, two Chrome windows, making one fullscreen one and then trying to use <kbd>cmd-`</kbd>  (it doesn't work).

There are a few enhancement requests which would potentially support toggling between fullscreen Zed workspaces by creating alternate fullscreen modes that don't use MacOS Spaces:

- https://github.com/zed-industries/zed/issues/13687
- https://github.com/zed-industries/zed/issues/13687
