### ISSUE TITLE
Unable to scroll the code space

### ISSUE THREAD

**Issue by Midnight1938** [zed-industries/zed#15970]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Unable to scroll the editor after using the Zeditor for a few minutes, or sometimes at launch.
The pinch to zoom feature continues to work.

Have used trackpad and mouse to compare to no avail. But has chances of fixing itself with next launch

### Environment

Zed: v0.146.5 (Zed)
OS: Linux X11 endeavouros unknown
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 24.1.5-arch1.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by tusx** [comment]
+1 on this
my logs seems to indicate this, not sure if this is helpful or not
![Screenshot_20240916_010558](https://github.com/user-attachments/assets/53afa95c-ea02-4d7b-b9be-c99d1296141d)

**Comment by mrnugget** [comment]
Fixed by #18484
