### ISSUE TITLE
Auto completion stops working after ui interaction

### ISSUE THREAD

**Issue by Hinkolas** [zed-industries/zed#15983]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I discovered that when pressing the "Browse documentation for package main" item in this dropdown menu the auto completion stops working. After a full restart of zed its works again.

https://github.com/user-attachments/assets/6f87caa0-5555-43b1-b81c-6b0855c23b69

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Hey @Hinkolas, do you see anything in your Zed log after hitting the play button? Also, do autocompletions come back after running an `editor: restart language server` action?
