### ISSUE TITLE
Suppress macOS notice about files beginning with a dot

### ISSUE THREAD

**Issue by brandondrew** [zed-industries/zed#16007]
### Check for existing issues

- [X] Completed

### Describe the feature

On macOS it is standard for the normal OS-supplied save dialog to prompt you before creating a file that begins with a dot.  This is slightly annoying in general, but it's especially out of place in a code editor.  Of course this is entirely Apple's fault, but it seems like there must be some way that Zed could suppress this notice.

<img width="912" alt="image" src="https://github.com/user-attachments/assets/0767eb23-1c97-4e5b-9f3b-bcf9c5758577">

**Comment by notpeter** [comment]
I don't believe this is a behavior we can alter as this is handled entirely by the native MacOS controls.  As a work-around, you can create the file in the project panel sidebar (`cmd-n` or right-click and `New File`) and create all the dotfiles you like.

Happy to reopen if there is an option to suppress these warnings via MacOS platform APIs.

Thanks for reporting (I find this dumb too!) :D
