### ISSUE TITLE
Markdown preview fails to activate upon clicking a tab

### ISSUE THREAD

**Issue by brandondrew** [zed-industries/zed#16003]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I have multiple Markdown tabs open, along with a Markdown preview pane, the preview pane is not activated when I click on another tab--only when I click in the body of the Markdown document.

Steps:

1. create 2 Markdown documents (ensuring that both have their types set to Markdown);
2. open a Markdown Preview pane;
3. click on the tab of the Markdown document that is not open, but don't click in the body;
4. notice that the Markdown Preview pane does not update what it displays.

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/4426e7c8-1cc9-4fd8-9260-62f61f99b871">

**Comment by JosephTLyons** [comment]
cc @bennetbo
