### ISSUE TITLE
Keybindings Not Working with Non-English Keyboard Layouts

### ISSUE THREAD

**Issue by chanios** [zed-industries/zed#16014]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
I am experiencing an issue where keybindings or shortcuts are not functioning correctly when the keyboard layout is changed to a language other than English. Specifically, the save function and potentially other shortcuts are impacted.

Set the keyboard layout to a language other than English (e.g., Thai, etc.).
Try using a keybinding or shortcut that is configured to use keys.
Observe that the keybinding or shortcut does not work.

### Environment

Zed: v0.147.2 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4090 || NVIDIA || 535.183.01

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/10972
