### ISSUE TITLE
Sync configuration to cloud

### ISSUE THREAD

**Issue by costinsin** [zed-industries/zed#16032]
### Check for existing issues

- [X] Completed

### Describe the feature

I am using Zed on multiple machines and I was wondering if the Settings config and Vim config could be uploaded to cloud and synced on every machine where I am logged with my GitHub account.

VSCode has a similar feature:
![image](https://github.com/user-attachments/assets/f99afd87-d11e-453d-9b92-3705b05d6a1c)

**Comment by notpeter** [comment]
Duplicate of:
- https://github.com/zed-industries/zed/issues/5010
