### ISSUE TITLE
`autosave` causes inline assistant suggestions to be accepted automatically

### ISSUE THREAD

**Issue by rowillia** [zed-industries/zed#16042]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Add the following setting:

```json
  "autosave": {
    "after_delay": {
      "milliseconds": 500
    }
  },
  ```
  
  2. Use the AI Inline Assistant to make a change
  
Note that the change is automatically accepted.  It'd be good if saving the underlying file automatically didn't trigger accepting the change.

### Environment

Zed: v0.149.0 (Zed Nightly a561398e7395cf3a60a02b57c347afc8492da7a1)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I can reproduce. Thanks for reporting.
