### ISSUE TITLE
Crash on hovering over error

### ISSUE THREAD

**Issue by tinfoil-knight** [zed-industries/zed#16058]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Clone https://github.com/tinfoil-knight/mini-lsm/tree/zed-crash
- Go to `mini-lsm-starter/src/lsm-storage.rs`
- Hover over the `iters` word in line 378 which has some long Rust type error
- Zed crashes

Aside:
- I can see the error by opening the Project Diagnostics tab from the status bar. The error is long enough that the window gets stuck doesn't scroll over horizontally to show the full error. Maybe that's related to why Zed is crashing on hovering over the error in the normal. Editor view.

Here are my Zed settings:

<details>
<summary>local settings</summary>
<pre>
{
  "collaboration_panel": {
    "dock": "right"
  },
  "features": {
    "inline_completion_provider": "none"
  },
  "project_panel": {
    "dock": "right"
  },
  "theme": "Ayu Dark",
  "buffer_font_family": "MonoLisa",
  "buffer_font_size": 14,
  "terminal": {
    "font_size": 13
  },
  "base_keymap": "VSCode",
  "git": {
    "inline_blame": {
      "enabled": false
    },
    "git_gutter": "hide"
  },
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "check": {
          "command": "clippy"
        }
      }
    }
  }
}
</pre>
</details>
### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details>
<summary>Details</summary>

<details><summary>Zed.log</summary><pre>

</details>

Since the log had too many characters, I've created a Gist here: https://gist.github.com/tinfoil-knight/ca51a63fb126457da788ccdad3c1f6a5#file-zed-crash-log

If it helps, I've also added the log that Mac records separately on crash and added it in the gist above.

</pre></details>

**Comment by notpeter** [comment]
Excellent reproduction steps! This reliably crashes on Zed Stable (0.147.2) and on Zed Nightly (0.149.x). It does not crash the minibuffer, only when hovered in the main editor:

<img width="1441" alt="Screenshot 2024-08-12 at 11 45 44" src="https://github.com/user-attachments/assets/fdfeeb0d-d73c-45e0-94e9-b39af375d270">

**Comment by uladkaminski** [comment]
Added PR for that issue. Let me know if any comments.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0280cd97-2d28-4248-96ad-31142fe19d8b">


https://github.com/zed-industries/zed/pull/16132
