### ISSUE TITLE
When open Project with same name, the editor tabs remain open

### ISSUE THREAD

**Issue by Himasnhu-AT** [zed-industries/zed#16059]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When we open a project with the same name, the editor tabs remain open.

## FOR EXAMPLE:
I cloned two different repositories named `demo` in my local system for testing.

I closed on the demo repo, `two days ago` Now when I open it in zed, same name, it opens all existing editors from there. they were empty and didn't contain any code, as expected.

## Steps to reproduce:
- clone a project in dir `<any>`
- open it in zed. now open two or three files from there. Close the project without closing the editor.
- Now clone another project in dir `<any>/<any>`
- open it in zed. You will see editors with the same name present there.

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### INFO:
If possible, i would love to work on this issue. As im new to zed, might take some time.
also making [unofficial docs](https://himasnhu-at.github.io/GPUI-docs-unofficial) of zed's GPUI, so im going through the repo anyways

**Comment by notpeter** [comment]
I attempted to reproduce this and was unable. I think I'm missing something about the nested git repos (cloning a different repo as a subproject of the previous clone?) which triggers the bug for you.

Can you try and provide an explicit step-by-step process for me to reproduce? Thanks
