### ISSUE TITLE
Prefix added to Powershell terminal when opened with command `zed <path_to_dir>` on Windows.

### ISSUE THREAD

**Issue by khulenikhil** [zed-industries/zed#16068]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I observed this issue on Windows.

1. Build the source using these instructions: [Building Zed for Windows](https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md#building-zed-for-windows)
2. Add the `target/release` to PATH.
3. Run `zed <path_to_dir>` from any terminal.
4. Open the terminal.
5. Run `pwd`. The prefix `Microsoft.PowerShell.Core\FileSystem::\\?\` will be show in the path.
6. Observe the powershell profile prefix.

When I checked the recent projects I found two projects (screenshot attached). The one with the correct path works fine.

### Environment

Zed: v0.148.0 (Zed Dev 990774247ecb61ddf69f0325d28eb3b203fc3699)
OS: Windows 10.0.22631
Memory: 15.2 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD proprietary driver || 21.30.40.04

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Terminal Screenshot](https://github.com/user-attachments/assets/5ea3d833-0117-4e9d-91a0-90d477d32e9a)
![Recent projects](https://github.com/user-attachments/assets/2ab82c64-08e6-49cc-8fcf-ff166f951176)

**Comment by JunkuiZhang** [comment]
Should be fixed by #15856
