### ISSUE TITLE
C++ LSP should recognize .cu and .cuh

### ISSUE THREAD

**Issue by SamKG** [zed-industries/zed#16070]
### Check for existing issues

- [X] Completed

### Describe the feature

CUDA files (using the .cu and .cuh extensions) are supported out-of-the-box by clangd; it would make sense for zed to map these extensions by default to the C++ LSP.

**Comment by Athishpranav2003** [comment]
@SamKG i have raised the PR for the same. If possible please check

**Comment by notpeter** [comment]
That PR has been merged into main.  This will likely be available in Zed Preview tomorrow (Wednesday 2024-08-13) and Zed Stable in a week (2024-08-20).

Thanks for reporting @SamKG and thanks for the PR @Athishpranav2003.
