### ISSUE TITLE
Key Binding missing for applying fixes

### ISSUE THREAD

**Issue by Chetic** [zed-industries/zed#16078]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When fixes are available, from e.g. clang-tidy in my case (C++), I have not been able to find a way to apply the fix without using the mouse. Is this missing at the moment?
Here's the code that I had to reproduce it:
```c++
#include <cstdio>
int main(int argc, char** argv)
{
    std::cout << "Hello, world!\n";
    return 0;
}
```
Putting the cursor on the line with "std::cout" shows that there is a missing include and that a fix is available. I can click the lightning-icon to the left and apply the fix, or I can use autocomplete to get the include added automatically but I was expecting an action for applying fixes in general.

### Environment

Zed: v0.147.2 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1080 Ti || NVIDIA || 535.183.01

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/606b8455-430e-439d-ab78-08fce5f0f808)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
`ctrl-.`?

https://github.com/zed-industries/zed/blob/2571447eb44bbef698134a0059f4660148af4aaa/assets/keymaps/default-linux.json#L290

**Comment by Chetic** [comment]
Yes, that is what I was looking for. Thanks! 

Suggestion:
"No member named 'cout' in namespace 'std' (fix available)"

Maybe "fix available as code action" instead? To help others on what to search for in the command palette.
