### ISSUE TITLE
`zed: open account settings` leads to 404

### ISSUE THREAD

**Issue by akihironitta** [zed-industries/zed#16081]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Following these steps leads me to https://zed.dev/settings:
1. Press `Cmd+Shift+P`
2. Select `zed: open account settings`

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.6.0
Memory: 18 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
I believe this is expected at the moment.

**Comment by JosephTLyons** [comment]
Piotr is right, this account page is related to a feature we are about to launch, but haven't yet. Sorry that that is confusing, it probably should've been behind a feature flag. Since this will be available soon, I'm going to close this issue out.
