### ISSUE TITLE
Terminal tab does not close when I type exit or ctrl+d after changing the terminal program

### ISSUE THREAD

**Issue by timfennis** [zed-industries/zed#16104]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've just started playing around with Zed and after I changed my terminal program to `fish` I noticed the tab doesn't close anymore when I type `exit` or `ctrl+d`.

It appears to me to be the exact same issues described here: https://github.com/zed-industries/zed/issues/6176

This is my full config for reference

```
{
  "base_keymap": "JetBrains",
  "project_panel": {
    "auto_reveal_entries": true
  },
  "vim_mode": true,
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "Ayu Dark",
    "dark": "One Dark"
  },
  "buffer_font_family": "Hack",
  "terminal": {
    "shell": {
      "program": "/usr/bin/fish"
    }
  }
}
```

If I remove the `"program"` section from the JSON it works. If I change it to `bash` which is my system shell the same problem happens as well. If I set `"shell"` to the default value of `"system"` it works as expected.

### Environment

Zed: v0.149.0 (Zed Dev da8d1306af711c95757fd9b7a653d7b45613c674)
OS: Linux Wayland arch unknown
Memory: 62.5 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 24.1.5-arch1.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I can reproduce this on Ubuntu Linux 22.04.
Works as expected on MacOS.

**Comment by timfennis** [comment]
@notpeter I've just updated my system and recompiled Zed and the problem seems to have been fixed. Output of `zeditor --verison`:

```
Zed  dev 0.151.1.r104.g1c6dbe0 – /usr/lib/zed/zed-editor
```

Feel free to close the issue at your discretion.

**Comment by SomeoneToIgnore** [comment]
This got fixed in https://github.com/zed-industries/zed/pull/16847 , thank you for testing.
