### ISSUE TITLE
Strange flicker issue

### ISSUE THREAD

**Issue by dwSun** [zed-industries/zed#16100]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Just open it,and move mouse over its window.

https://github.com/user-attachments/assets/51c31c96-5750-46d8-8377-9c9f7acd5718

### Environment

![5281069999](https://github.com/user-attachments/assets/f7edd4b6-f16c-4014-bb0a-16538c0931d3)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

1.

**Comment by apricotbucket28** [comment]
This is already fixed in version 0.148. Original issue:
- https://github.com/zed-industries/zed/issues/14101

**Comment by dwSun** [comment]
> This is already fixed in version 0.148. Original issue:
> 
> * [Zed window flickers - Linux with Intel Graphics #14101](https://github.com/zed-industries/zed/issues/14101)

Thank you so much
