### ISSUE TITLE
Getting "failed to blame: could not open object name list: .git-blame-ignore-revs"

### ISSUE THREAD

**Issue by brookback** [zed-industries/zed#16106]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a file.
2. Run `editor: toggle git blame` from command palette.

## Expected

I should be able to view the git blame for the file.

## Actual

An error is showing:

> Failed to blame: <file>: git blame process failed: fatal: could not open object name list: .git-blame-ignore-revs

It seems to want to open the file `.git-blame-ignore-revs` in this project, but when that file doesn't exist, this error shows.

***

I think this is happening when I run `editor: toggle git blame inline` too.

### Environment

Zed: v0.148.0 (Zed Preview)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="462" alt="image" src="https://github.com/user-attachments/assets/c65a3f40-d404-4d9f-b8b8-a7a865ab4330">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>
2024-08-12T08:57:54.422368Z [ERROR] failed to get git blame data: Failed to blame ".mocharc.js"

Caused by:
    git blame process failed: fatal: could not open object name list: .git-blame-ignore-revs
    
</pre></details>

**Comment by notpeter** [comment]
This is not a Zed issue. You have a `blame.ignoreRevsFile .git-blame-ignore-revs` in your git config, but there is no `.git-blame-ignore-revs` in the current repository. If you ran `git blame` from the CLI you'd see the same.

You can see whether it's set in your global git config (`~/.gitconfig`) or in your local repo config with this:
```
git config --list --show-origin |grep revs
```

See: [git blame docs](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt-blameignoreRevsFile) for more.

**Comment by brookback** [comment]
Sorry, that's correct — my mistake! Thank you.
