### ISSUE TITLE
Character variant not working (Inconsolata LGC font)

### ISSUE THREAD

**Issue by virtualritz** [zed-industries/zed#16110]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This seems like a duplicate of/related to #11486.

I'm trying to use [Inconsolata LGC](https://github.com/MihailJP/Inconsolata-LGC) with old style numerals (OTF feature [`onum`](https://github.com/MihailJP/Inconsolata-LGC?tab=readme-ov-file#onum-old-style-numerals)).

For example, in VSCode, I (successfully) use this:
```json
  "editor.fontFamily": "'Inconsolata LGC', 'Courier New', monospace",
  "editor.fontLigatures": "'onum'",
```

And in `zed` I have this:
```json
  "buffer_font_family": "Inconsolata LGC",
  "buffer_font_features": {
    "onum": true
  },
```

The `buffer_font_features.onum` has no effect. Even after restarting `zed`.

### Environment

Zed: v0.147.2 (Zed)
OS: Linux Wayland ubuntu 23.10
Memory: 14.8 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV REMBRANDT) || radv || Mesa 23.2.1-1ubuntu3.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
This is essentially the same issues as #15752
