### ISSUE TITLE
Add a color viewer: see #ffffff as a color in Editor

### ISSUE THREAD

**Issue by yesagainivan** [zed-industries/zed#16116]
### Check for existing issues

- [X] Completed

### Adding a little box to see the color (#ffffff, for example ) in the editor, like in Vscode. 

This could be done with an extension probably. the picking is not really needed but just the ability to see the color would help a lot.

**Screenshot**

<img width="230" alt="color" src="https://github.com/user-attachments/assets/184166cf-3062-4ae1-bbe5-d54f83d0517a">

Thank you !

**Comment by notpeter** [comment]
Duplicate of:
- https://github.com/zed-industries/zed/issues/4678
