### ISSUE TITLE
A super long one line text will be broke into 2 lines

### ISSUE THREAD

**Issue by musicq** [zed-industries/zed#16153]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A super long oneline text without wrap will be broke into 2 lines. Max oneline character is 512.

<img width="491" alt="image" src="https://github.com/user-attachments/assets/87b7ed18-14c8-4766-b53e-bb35e32b8007">

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
this is intend, default line lenght might be 1024 byte(if i member correctly).

**Comment by notpeter** [comment]
The default behavior for `soft_wrap` is to wrap lines >512 columns.

To disable `soft_wrap` please add the following to your `~/.zed/settings.json`

```json
  "soft_wrap": "none",
```

[soft_wrap docs](https://zed.dev/docs/configuring-zed?highlight=soft_wrap#soft-wrap)

Note, you can include `soft_wrap` nested inside a [Language Specific Setting](https://zed.dev/docs/configuring-languages#language-specific-settings) if you wish to have different settings for different types of files.

**Comment by musicq** [comment]
@notpeter Thanks for the tip!

It looks like it will truncate the line after I set `soft_wrap: none`, although user can input but after a certain characters limits, the words are just not showing.

https://github.com/user-attachments/assets/5b303d80-78ff-4561-ba38-5db8ff1b9d50

**Comment by ed-lam** [comment]
I'm also getting this issue. It wraps whenever there are more than 510 characters on a line. I would like it to display the full line with horizontal scroll.

**Comment by teohhanhui** [comment]
https://zed.dev/docs/configuring-zed#soft-wrap

> `none` to avoid wrapping generally, unless the line is too long

We need a `"soft_wrap": "never"` that never wraps, regardless of how long the line is...
