### ISSUE TITLE
Unified locator (switch between file search, symbol search etc. using short prefixes)

### ISSUE THREAD

**Issue by thorbenk** [zed-industries/zed#16176]
## Description of the "Unified locator" feature

I've been using [Qt Creator](https://www.qt.io/product/development-tools) (open source C++ IDE) for a long time and one of the very nice features it pioneered (?) is the locator ([doc](https://doc.qt.io/qtcreator/creator-editor-locator.html)).
It's similar to a feature in VSCode where you can prepend "@" or "#" in the Ctrl-P finder and to ideas from [neovim's telescope](https://github.com/nvim-telescope/telescope.nvim).

If you hit the shortcut for the locator (equivalent to Ctrl+P dialog in Zed), you get:
![image](https://github.com/user-attachments/assets/f196ae29-a765-4d76-a46d-636ea808b1d7)

If you start typing, the matches appear. Per default, it fuzzy matches across your project files.

To switch to a different find mode, *write the prefix + space in front of your query*. For example:

- Searching for a file in the file system to open:
  ![Screenshot_20240813_210320](https://github.com/user-attachments/assets/deaa7168-24bd-467f-ba19-abf98a5bf478)
- Searching for a C++ symbol:
  ![Screenshot_20240813_210155](https://github.com/user-attachments/assets/96bda32e-0037-48c8-9b5c-9b068ef3f5aa)

There are many prefixes available, they are configured here:
![Screenshot_20240813_205309](https://github.com/user-attachments/assets/ca0fc6e3-f07c-4aaa-bbed-6d7ace4920ea)

VSCode has a similar feature ([doc](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_go-to-symbol-in-file))
![Screenshot_20240813_210550](https://github.com/user-attachments/assets/dcc4d407-0e2c-4d02-a1af-e50edbd7728d)
but I think Qt Creator's locator is even more powerful.

## Why is this feature useful?

It reduces friction. There's just one shortcut (Zed's Ctrl+P) to press when the intent is "I need to find something". _How_ to find it comes next. Sometimes it's easier to search by symbol, sometimes by filename or via some other method. It's easy to switch between the different methods all while formulating the search query.

It's also very powerful, and could lend itself to extensions (for ideas, one can also look to neovim's telescope).

_Note_: The feature request for switching between the "file finder" and "command palette" using the ">" symbol exists already as https://github.com/zed-industries/zed/issues/15896 . Let me know if this feature request should be folded into that ticket instead.

**Comment by notpeter** [comment]
Potentially related:
- #14249
