### ISSUE TITLE
[Bug] Latest preview .dmg package builds do not open up

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#16175]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Unable to install the latest update. 

Double clicking any of the latest ZED packages do not open the `.dmg` package. 
Ref: https://zed.dev/releases/preview

I reckon the same happens within the main ZED window, where I get `Auto update failed`:
![zed-failed-update](https://github.com/user-attachments/assets/266730db-39ef-4133-885c-4b60612eb6b8)

### Environment

```
Zed: v0.146.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64
```

### If applicable, attach your Zed.log file to this issue.

After initiating `Check update` inside ZED, the following log is generated:
<details><summary>Zed.log</summary><pre>
[...]
2024-08-13T19:02:41.933605Z [INFO] downloaded update. path:"/var/folders/mm/9lkm3vdn35z8n25m6rtj_h1r0000gq/T/zed-auto-update8L054t/Zed.dmg"
2024-08-13T19:02:44.217713Z [ERROR] auto-update failed: error:failed to mount: "hdiutil: attach failed - no mountable file systems\n"
2024-08-13T19:03:02.634664Z [INFO] downloaded update. path:"/var/folders/mm/9lkm3vdn35z8n25m6rtj_h1r0000gq/T/zed-auto-updaterzR6R9/Zed.dmg"
2024-08-13T19:03:04.232127Z [ERROR] auto-update failed: error:failed to mount: "hdiutil: attach failed - no mountable file systems\n"
</pre></details>

What is also somewhat bizarre, because I work on `aarch64` I would assume the update will download the relevant file such as https://zed.dev/api/releases/preview/0.148.0/Zed-aarch64.dmg?browserId=1914d192c5890a-0790a9e6e84945-19525637-2b6b58-1914d192c592931, instead it seems Universal `Zed.dmg` is pulled, but I cannot verify it as temporary `/var` path at log reported `/var/folders/mm/9lkm3vdn35z8n25m6rtj_h1r0000gq/T/zed-auto-update8L054t/` seems to be removed. It is possible Zed under the hood renames the install file but ¯|-(ツ)_/¯

**Comment by notpeter** [comment]
If you originally installed from the Zed.dmg (Universal Binary) the auto-update will fetch the Universal Binary for updates. If you manually replace your universal app with the aarch64 version you can save yourself the extra 60MB downloads and ~165MB on disk.

I was not able to reproduce your issue -- I was able to update from Zed Preview 0.146.1 just fine.

I worry that your manually downloaded dmgs are corrupted as well.  Do you perhaps operate in a restrictive network environment (corporate proxy, etc) where there could be a corrupted cache or some such?

For reference here are the sha256 checksums for the current [Zed Preview v0.148.0](https://github.com/zed-industries/zed/releases/tag/v0.148.0-pre):
```
9cfaf949cfe0a48e05c04d8160da67e5722bed03f8f67c2b7b261c0e38be8060  Zed-aarch64.dmg
339733bf4f79cd63fd9c7f61fe0b48a20b3abf405ee56a0aad84e9d968d84ec0  Zed-x86_64.dmg
5e3adbed64578f40ae362f28892b06b665d1058be876c25735d742a9ec3e240b  Zed.dmg
```

**Comment by osiewicz** [comment]
@notpeter the universal binaries do update themselves to non-universal versions, so the user does not need to opt into arch-specific version manually.

**Comment by krstp** [comment]
Thanks for the update.

I did check the `sha256 checksum` and for the latest preview `0.148.0` I do get the same `9cfaf949cfe0a48e05c04d8160da67e5722bed03f8f67c2b7b261c0e38be8060 Zed-aarch64.dmg`

However, I still get the same error. What I tried was:
`hdiutil attach Zed-aarch64.dmg`
but get: `hdiutil: attach failed - no mountable file systems` :( 

Just in case, I also tried to remove quarantine attributes with:
`xattr -d com.apple.quarantine Zed-aarch64.dmg`, but it did not help :(

I also tried converting the image to `iso`:
`hdiutil convert Zed-aarch64.dmg -format UDTO -o Zed-aarch64.iso` but it is also unopenable as well :( 

![Screenshot 2024-08-13 at 5 41 56 PM](https://github.com/user-attachments/assets/973343e5-9d3f-42ac-8153-88b40cf8cfdc)

I reckon, it must be something my "corporate" introduced. I will try later to toy around it. Thanks for all your answers.

**Comment by krstp** [comment]
OK, not sure what was going on. One bit to admit I have not restart my machine for quite some time. Restart allowed latest version to install. All checks out. Thanks everyone for your input and verification.

**Comment by notpeter** [comment]
I got this too tonight.  Only impacted my Nightly Zed (Preview/Stable updated just fine).
Only way to solve it was to restart. 🤷

**Comment by notpeter** [comment]
Restarting Zed did not fix it.
Logging out did not fix it.
Restarting the computer did not fix it.
So I removed the `Zed Nightly.app` from /Applications and manually reinstalled from DMG.
🇼🇹🇫

**Comment by notpeter** [comment]
Update: Yesterday's nightly build (2024-10-12) had an auto-update related bug with the new http_client which was not following a redirects correctly.

Today's build fixed the issue, but needed to be manually downloaded.

**Comment by WarningImHack3r** [comment]
I just encountered the same problem after clicking on the update label that says `Downloading update` (because I was wondering why such a thing was even clickable) - terrible mistake, it stopped the process and failed to download anything ever again because of a seeming timeout during the process.

`zed --foreground`, suggested by https://github.com/zed-industries/zed/issues/6857#issuecomment-2529635675, helped me finding this issue.

A quick `ps -a | grep hdiutil` helped me notice a running `rg hdiutil` process.

**The fix? Killing it. No need to reboot. Just `sudo pkill rg`.**
