### ISSUE TITLE
Windows: Supermaven spawns command window

### ISSUE THREAD

**Issue by vinhphm** [zed-industries/zed#16194]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When set code autocomplete to use Supermaven, it will spawns a command window with path `C:\Users\username\AppData\Local\Zed\supermaven\sm-agent-26` and stays there. When close it, the feature stops working. It feels similar to #15955 

### Environment

Zed: v0.149.0 (Zed Dev 355aebd0e493aa9f60900179acf8011a1fc9117b)
OS: Windows 10.0.22621
Memory: 15.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JunkuiZhang** [comment]
Could you try #16203?
