### ISSUE TITLE
git commit popup messages strip newlines and brackets

### ISSUE THREAD

**Issue by bestgopher** [zed-industries/zed#16220]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Raw commit messages is:
<img width="679" alt="image" src="https://github.com/user-attachments/assets/0a0a75e5-61c1-422d-a11d-f754796cd2f7">

Get it from zed:
<img width="495" alt="image" src="https://github.com/user-attachments/assets/56ef1356-2cfe-4363-a427-d5b89e2d39a8">

"\n", "<", ">" is gone.

### Environment

macbook

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I am able to reproduce.
Reproduction steps:
```
mkdir issue16620
cd issue16220
echo "test" > a
git add a
git commit -m "test

Line 1
Line 2

Signed-off-by: somebody <user@fake.com>"
zed .
```
Then hover over the inline blame.

**Comment by bestgopher** [comment]
According to source code of zed, the commit messages are parsed to markdown. The process may cause some characters lost. In my opinion, commit messages needn't be parsed to markdown.

**Comment by notpeter** [comment]
I like Zed rendering markdown in commit messages similar to how GitHub handles it (links, lists, **bold**, etc) but IIRC in most contexts Github does not treat single newline as a no-op like the default Markdown spec.  Might be as simple as a pre-processing step like:

```
.replace("\n+", "\n\n")
.replace("<", "&lt;")
.replace(">", "&gt;")
```

**Comment by dovakin0007** [comment]
![image](https://github.com/user-attachments/assets/97e2af18-8562-4888-b5dd-c54614c38478)
something like this is expected?

**Comment by dovakin0007** [comment]
okay just raising this it seems like softbreaks are handled with space character so adding a \n\n does break the formatting and turning each line into paragraph so
![image](https://github.com/user-attachments/assets/47cbd3bf-c738-4eda-8705-5c3ea1ec3b5f)

**Comment by bestgopher** [comment]
There are some other issues. For example, for golang comments, I think they needn't render to markdown too.
![image](https://github.com/user-attachments/assets/05b30f1b-0f39-4fd3-9fea-8b489036843e)
![image](https://github.com/user-attachments/assets/73c08a07-c3a3-4ce4-81f1-acedb1b66d62)

**Comment by dovakin0007** [comment]
rendering it as text does fix the issues but it does change the formatting so for now it's better to render it as  markdown

![image](https://github.com/user-attachments/assets/61ae8190-13d4-415f-bb1c-c211ae6e74fe)

**Comment by dovakin0007** [comment]
should I raise a pr with the changes for brackets?
