### ISSUE TITLE
Linux X11: Drag and drop support

### ISSUE THREAD

**Issue by sonulohani** [zed-industries/zed#16225]
### Check for existing issues

- [X] Completed

### Describe the feature

Sometimes I need to drag and drop the files into the editor. This doesn't work in the current version of zed.

https://github.com/user-attachments/assets/3517328c-b3aa-4c06-98dc-bfdd801ed4c4

### Environment

Zed: v0.147.2 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 31 GiB
Architecture: x86_64
GPU: NVIDIA RTX A2000 8GB Laptop GPU || NVIDIA || 535.183.01

**Comment by notpeter** [comment]
Hi @sonulohani, drag and drop is supported on Linux.

It works for me on Ubuntu22 (Wayland, DE: Plasma, WM: kwin) when dragging from Dolphin (the KDE file explorer).

I pasted your environment from your other issue, bu tcan you share a bit about your setup (Desktop Environment, Window Manager, etc.) which might help narrow down a bit.  Similarly does drag and drop work to other applications (Chrome, etc) or is it just Zed that's broken.

**Comment by apricotbucket28** [comment]
Drag and drop is supported on Wayland, but not on X11. [XDND reference](https://www.freedesktop.org/wiki/Specifications/XDND/) if anyone would like to implement it.
