### ISSUE TITLE
Setting to allow disabling grouping code when autoclosing brackets

### ISSUE THREAD

**Issue by Seldom-SE** [zed-industries/zed#16239]
### Check for existing issues

- [X] Completed

### Describe the feature

When you open a bracketed group, Zed tries to predict where to close the group (so prepending `MyUnitStruct` with `(` yields `(MyUnitStruct)`), but this doesn't predict well with my code, so I would like a setting that configures whether this behavior is enabled.

**Comment by Moshyfawn** [comment]
There's `"use_autoclose": false` to enable/disable this behaviour globally. You can also add it to the specific language config like this:

```json
{
  "languages": {
    <language-name-here>: {
      "use_autoclose": true,
    }
  }
}
```

**Comment by Seldom-SE** [comment]
Could you reopen this? That solution doesn't fit my use case. I don't want to disable autoclosing entirely, I just don't want it to group any code. The problem is, it guesses where it should close the group wrong often enough that I always have to find where it put the closing character every time anyway. So I want the same behavior as other editors like VSCode.
