### ISSUE TITLE
Incorrect entry in release notes for `v0.149.0-pre`

### ISSUE THREAD

**Issue by khipp** [zed-industries/zed#16245]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the generated release notes for `v0.149.0-pre`, the entry for PR #16142 is present despite having been reverted in #16167.

### Environment

N/A

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Thank you, I've updated the notes to reflect the current state of things.
