### ISSUE TITLE
[Bug] Bug in the assistant configuration panel and terminal

### ISSUE THREAD

**Issue by Fi44er** [zed-industries/zed#16280]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Scrolling does not work on the assistant configuration tab (see screenshot 1)
2) The terminal accumulates text if you open the right tab for the entire workspace (see screenshots 2-4)

### Environment

Zed: v0.148.0 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 15.6 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 950 || NVIDIA || 535.183.01

### If applicable, add mockups / screenshots to help explain present your vision of the feature

1) ![Снимок экрана от 2024-08-15 15-38-34](https://github.com/user-attachments/assets/ef56396a-1fc6-4210-aebe-371cc6fd69ca)

2) ![Снимок экрана от 2024-08-15 15-39-14](https://github.com/user-attachments/assets/7da3eff5-a061-4973-9adf-ace2161491b4)

3) ![Снимок экрана от 2024-08-15 15-39-26](https://github.com/user-attachments/assets/210a8638-1b20-4fa0-93cb-2e868a502285)

4) ![Снимок экрана от 2024-08-15 15-39-59](https://github.com/user-attachments/assets/5cb3ef16-998c-4565-8858-0472bcf15df4)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bennetbo** [comment]
Hey,

we just released a patch to fix the scrolling (https://zed.dev/releases/stable/0.148.1). I'm not sure about the other issue, could you perhaps record a small video which showcases when this happens? I'm not able to repro the issue and I'm not clear on what exactly is happening from you're explanation.
