### ISSUE TITLE
Highlight Bad Unicode Characters

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#16310]
### Check for existing issues

- [X] Completed

### Describe the feature

Working with a document that had some invisible `U+200D` [zero-width joiner](https://www.charset.org/utf-8/9) characters which resulted in some odd rendering bugs.

Zed should highlight these and optionally potentially other classes of "bad" characters:
- `U+200B` (Zero Width Space), `U+200C` Zero Width Non-joiner, `U+200D` (Zero Width Joiner)
- Bidirectional text control characters (`U+200E`, `U+200F`)
- Control characters (U+0000 to U+001F, U+007F to U+009F)
- Combining characters (U+20E3, U+20DD)

Additionally it might be helpful to optionally support highlighting "maybe bad" characters:
- Smart quotes (left/right of single/double)
- Emdash / Endash `–` `—`
- Elipses: `…` (U+2026)
- Unicode Ligatures, etc

Vscode:
<img width="175" alt="image" src="https://github.com/user-attachments/assets/95cbbf4c-7253-45a6-840e-1f2ba21b9249">
Zed:
<img width="199" alt="image" src="https://github.com/user-attachments/assets/a3c9c2f1-f026-46e8-85f8-476555df6b46">

VSCode includes a bunch of settings which help control this behavior `editor.unicodeHighlight.* as inspirations for how to control this behavior.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="373" alt="Screenshot 2024-08-15 at 14 53 49" src="https://github.com/user-attachments/assets/43bf852b-b006-4108-b434-295dbca47cae">

**Comment by dovakin0007** [comment]
it seems like some of the control characters are not getting rendered any ideas what we can do when I add a space or character the highlights rendered over the text
![image](https://github.com/user-attachments/assets/322aed26-902b-44e2-bf67-c038370c70d6)

**Comment by notpeter** [comment]
Adding Non-Breaking space: " " to this list.
On MacOS, type <kbd>option</kbd> + <kbd>space</kbd> to create one.
Thanks @tjconcept for the [easy reproduction](https://github.com/zed-industries/zed/issues/5151#issuecomment-2368820171)
