### ISSUE TITLE
Markdown preview not working as expected

### ISSUE THREAD

**Issue by kaiguang** [zed-industries/zed#16318]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I cannot open the markdown preview if the first line is a paragraph, however, if the first line is empty the preview works.

Please see video demo.

https://github.com/user-attachments/assets/36f5ccac-f432-44a9-aab0-1cacd440fc78

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

**Comment by richyk1** [comment]
Experience the same issue on my M1 Pro. Even trying `markdown: open preview` or `markdown: open preview to the side` does not work for me.

**Comment by bennetbo** [comment]
This was fixed on preview (0.149.x, #15961) and will land on stable next week.
