### ISSUE TITLE
Remove UI Bloat

### ISSUE THREAD

**Issue by kanelee** [zed-industries/zed#16322]
### Check for existing issues

- [X] Completed

### Describe the feature

Remove and Avoid Future UI Bloat.

Remove Icons in the Dock and Editor Panel. Instead, Add The Ability To Add Favorites To The Command Palette.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Zed 2](https://github.com/user-attachments/assets/54ba0f4b-b8eb-4e88-81e0-81f75977dddf)
![Zed 3](https://github.com/user-attachments/assets/bc2c35e1-9bbe-4865-aca6-687842390583)

**Comment by baldwindavid** [comment]
All of those are already able to be hidden via your settings (`zed: open settings`).  Access `zed: open default settings` in the command palette to track them down. The status bar icons have `button: bool` settings and quick actions can all be hidden via `toolbar.quick_actions`.

**Comment by kanelee** [comment]
Awesome! Works like a charm. Thank you!On Aug 15, 2024, at 5:30 PM, David Baldwin ***@***.***> wrote:﻿
All of those are already able to be hidden via your settings (zed: open settings).  Access zed: open default settings in the command palette to track them down. The status bar icons have button: bool settings and quick actions can all be hidden via toolbar.quick_actions.

**Comment by rgbkrk** [comment]
Closing since, as @baldwindavid pointed out, you can disable `toolbar.quick_actions` as well as buttons for any panels.


```jsonc
  "chat_panel": {
    "button": false
  },
  "collaboration_panel": {
    "button": false
  }
```

**Comment by notpeter** [comment]
For anyone who finds this in the future here are some of the settings you can use to "simplify" the UI experience:

  - `scrollbar.git_diff` false
  - `scrollbar.cursors` false
  - `scrollbar.search_results` false
  - `scrollbar.diagnostics` false
  - `git.git_gutter` "hide"
  - `git.inline_blame.enabled` false
  - `show_inline_completions` false
  - `toolbar.breadcrubs` false
  - `toolbar.quick_actions` false
  - `toolbar.selections_menu` false
  - `gutter.code_actions` false
  - `gutter.runnables` false
  - `gutter.folds` false
  - `assistant.button` false
  - `tabs.git_status` false
  - `tab_bar.show_nav_history_buttons` false
  - `indent_guides.enabled` false
  - `collaboration_panel.button` false
  - `notification_panel.button` false
  - `chat_panel.button` false

All of these should be documented in [configuring zed](https://zed.dev/docs/configuring-zed) and in [default.json](https://github.com/zed-industries/zed/blob/main/assets/settings/default.json) in the repo.
