### ISSUE TITLE
Paired Bracket Not Highlighted in SQL Files

### ISSUE THREAD

**Issue by Seaweed0112** [zed-industries/zed#16328]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello,

I've noticed an issue in Zed Editor when working with SQL files. When the cursor is positioned at one bracket (e.g., ( or {), the corresponding paired bracket is not highlighted. This makes it difficult to locate and match the paired bracket, especially in complex SQL queries.

This issue affects the user experience as it hampers quick navigation and readability within the code.

Steps to reproduce:

Open an SQL file in Zed Editor.
Place the cursor on any opening or closing bracket (e.g., ( or {).
Observe that the corresponding paired bracket is not highlighted.
Expected behavior:
The corresponding paired bracket should be highlighted when the cursor is placed on one bracket, similar to the behavior in other file types.

Thank you for looking into this issue. I hope it can be resolved in a future update.
![image](https://github.com/user-attachments/assets/f90751ff-8397-41ca-ab49-ef33ab5ce08d)

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Moshyfawn** [comment]
This issue should be addressed in the community extension repository. Please [create an issue](https://github.com/evrensen467/zed-sql/issues/new/choose) in their repository to report the problem and seek assistance.

**Comment by Seaweed0112** [comment]
I see. Thank you for the information! I will create an issure there.
