### ISSUE TITLE
Add Radius To Tab Corners

### ISSUE THREAD

**Issue by kanelee** [zed-industries/zed#16323]
### Check for existing issues

- [X] Completed

### Describe the feature

Replace right angle corners with radiuses.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Zed 4](https://github.com/user-attachments/assets/3d8b9a4f-b868-4169-8638-1d53ceb20d66)

**Comment by iamnbutler** [comment]
Hey! We appreciate folks might want to be able to visually customize tabs like this. However, we don't currently have any plans to do it, so closing this out as wontfix for now.
