### ISSUE TITLE
TSX comment stopped working in html tags

### ISSUE THREAD

**Issue by Tsolmonx** [zed-industries/zed#16337]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i try to comment the code in tsx html tags it comment with double slash. It used to work before with right comment in html tags now its all //.

### Environment

![image](https://github.com/user-attachments/assets/c600cd25-95e3-4fb3-bcfc-fa26dc4289dd)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/bf48e8b7-23ee-4ea1-8367-d20f88874c96)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
I believe this happens due to https://github.com/tree-sitter/tree-sitter-typescript/issues/306 and the corresponding update to the newer tree-sitter-typescript crate in Zed that we had to do at some point.

**Comment by mrvfino** [comment]
Experiencing this as well, i thought i just broke something in my config.

**Comment by m1guer** [comment]
any update?

**Comment by animify** [comment]
+1 need a fix for this 🙏

**Comment by Edgarfp** [comment]
I think it has been fixed in latest version. I tested it and it's working fine.

**Comment by mikayla-maki** [comment]
Closed from: https://github.com/zed-industries/zed/pull/17734
