### ISSUE TITLE
No Close buttons on Wayland

### ISSUE THREAD

**Issue by qawsedrftgzh** [zed-industries/zed#16344]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't have any window buttons (max min close) under wayland.
![image](https://github.com/user-attachments/assets/150521d3-53eb-4c9c-a42c-fd9e72353933)
The same problem does not exist under x11, but the window decoration are the one kde provides, not the one zed uses.

### Environment

Operating System: NixOS 24.05
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.2
Kernel Version: 6.6.45 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-5600U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500

### If applicable, add mockups / screenshots to help explain present your vision of the feature

How it should look and looks on the Linux prewiev:
![image](https://github.com/user-attachments/assets/1195c0b3-497f-4457-9f3b-240f39a4d20a)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JuliusDeBoer** [comment]
I dont have this problem on wayland. My best guess is you are running v0.135.2. Instead of the more recent version on nixpkgs unstable (0.147.2). From the top of my head that version was before Linux support was "official". Altough I could be wrong about that one.

**Comment by qawsedrftgzh** [comment]
I installed zed from unstable, it works now
