### ISSUE TITLE
Conflicting default keybinding for assistant::InsertIntoEditor on swedish locale mac - can't switch window

### ISSUE THREAD

**Issue by hedefalk** [zed-industries/zed#16343]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On a swedish locale Mac, the native window switching within app is with cmd-<.

In zed for a while now, I haven't been able to reliably switch windows - it has worked sometimes and sometimes not. I even learnt a trick to activate the menu before I could do it. I thought it was a bug/missing feature for some time, but just realized it's dependent on which file is active so this tells me that there's a context thing and therefore probably a conflicting keybinding. So it took me a while to find `"cmd-<": "assistant::InsertIntoEditor",` and fixed it finally with ` "cmd-<": null`.

Just not sure if this is a good default keybinding? 

It's one thing to take care of keybindings on first setup with really open eyes, but I guess the issue for me is that new default keybindings still popup on auto-update releases that might conflict like that, creating untimely regressions.

Maybe default keybindings need to be locale dependent? Maybe all new keybindings need to be put in release notes under some "possibly breaking changes" label and I need to turn off auto-update? Not sure about the answer… :)

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Thanks for reporting and sorry you ran into that.  I didn't realize that MacOS on other locales used a different keybind for window cycling (US English uses ``` cmd-` ```<key> for that). I wonder if there are any others.  I couldn't find any international versions of [Mac keyboard shortcuts](https://support.apple.com/en-us/102650), but would love to diff them and see if we can identify future potential conflicts before they happen.

How do you cycle in reverse? We use ``cmd-shift-` ``

As for locale specific keymaps, I think we're likely a ways off from implementing that, but we should avoid mapping keyboard shortcuts we know will conflict with OS defaults, even if it only impacts a subset of users.  Let me know if you find other conflicts with MacOS in the default key binding.

Thanks for reporting.

**Comment by hedefalk** [comment]
>How do you cycle in reverse? We use cmd-shift-` 

It's cmd-shift-< or actually cmd-> as they are the same:

<img width="242" alt="image" src="https://github.com/user-attachments/assets/e39eaeda-2f2a-4579-ada6-a2b2f0ea0cf7">

**Comment by notpeter** [comment]
I think this may potentially impact quite a number of locales, not just Swedish. Looking at [various Mac keyboard variations](https://keyshorts.com/blogs/blog/37615873-how-to-identify-macbook-keyboard-localization), if it's every keyboard that doesn't doesn't have grave accent/tilde above tab and has `<` `>` to the left of Z it could be as broad as: Sweden, Belgium, Bosnian, Danish, Estonian, Finnish, French, German, Icelandic, Italian, Norwegian, Portuguese, Spanish ISO, Turkish. Eek.

**Comment by schmurfy** [comment]
I confirm this issue also happens with French locale.

**Comment by dwt** [comment]
Also happens in the German locale, the workaround recommended in #17582 that disables some keybindings, seems to work for now. But  I am looking forward to you freeing up those shortcuts again.

```json
[
  {
    "context": "ContextEditor > Editor",
    "bindings": {
      "cmd-<": null
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-<": null
    }
  }
]
```
