### ISSUE TITLE
"FindAllHunks" multibuffer

### ISSUE THREAD

**Issue by Cianidos** [zed-industries/zed#16347]
### Check for existing issues

- [X] Completed

## Idea: Create a Multi-Buffer View for Discovering Git Hunks

**Workflow:**  Check and review wide editing changes before committing.
It would also be beneficial to integrate `git show` into this multi-buffer view to
discover already committed changes.

 **Workflow:** Imagine finding a suspicious line in the code. You can use `git
blame` to copy the commit hash, then open the hunk multi-buffer (similar to a
project search). Paste the hash, and it will display all blocks from that
commit which are still present in the current state.

**Comment by SomeoneToIgnore** [comment]
Oh yes, that's the way we want to approach Git display in general, there's even a prototype: https://github.com/zed-industries/zed/issues/8665#issuecomment-2194000497

The current issue with the approach is the amount of churn code needed by every multi buffer user to update its excerpts.
We plan to rewrite the multi buffer a bit and move that code inside it, so all we have to do so say `multi_buffer.set_new_data(diff_ranges);` and that will update automagically.

After that's done, the prorotype rewrite and enhancements follow, and later, checking out random revision and showing that may follow.

Nothing is made for "show blame commit's changes only" but it's more or less included into the parent issue I think, so let's close this one for now.
