### ISSUE TITLE
Clicking on project switcher then Cmd+Enter opens a new window, but Option+Cmd+O then Cmd+Enter doesn't

### ISSUE THREAD

**Issue by fasterthanlime** [zed-industries/zed#16361]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The title says everything.

If I click on the project switcher up here:

![CleanShot 2024-08-16 at 19 08 28@2x](https://github.com/user-attachments/assets/64ac250f-4f0f-4561-8d9f-8e880c784b94)

Then pick a project:

![CleanShot 2024-08-16 at 19 08 44@2x](https://github.com/user-attachments/assets/36b28f81-eb85-4393-84c4-d56c8427c6f6)

...and then hit Cmd+Enter, it opens a new window.

If instead I open the project switcher with `Option+Cmd+O`, then `Cmd+Enter` replaces the existing zed window.

### Environment

Zed: v0.149.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I can reproduce this on MacOS/Linux with current nightly.
Thanks for reporting.

**Comment by fasterthanlime** [comment]
Still hitting this semi-regularly :(

**Comment by fasterthanlime** [comment]
Thank you so much 🙏 ✨  Y'all are the best!!
