### ISSUE TITLE
Using "zed ." will open Zed in current folder in Linux

### ISSUE THREAD

**Issue by AsharSi** [zed-industries/zed#16366]
### Check for existing issues

- [ ] Completed

### Describe the feature

Currently while using the command zed . in terminal for opening zed in current directory is not working in Linux (I'm using Kali).  Am I the only one who is getting this issue or this feature in not available in linux version yet?

**Comment by notpeter** [comment]
Nope this should work. 

Can you include your `zed: copy system specs to clipboard` in the description and provide a little bit more about your setup and what happens?

**Comment by AsharSi** [comment]
![image](https://github.com/user-attachments/assets/85b35969-f1fb-4918-b721-29e06841927b)


You can see. In the last command I had used "zed ." but it is showing that "command zed not found"

**Comment by notpeter** [comment]
Please read more carefully, after the curl installer finishes it tells you what to do.

You can find the zed cli at `~/.local/bin/zed` and need to add `~/.local/bin` to your path. 
<img width="496" alt="image" src="https://github.com/user-attachments/assets/0f9db23c-5a33-4617-bc92-f00677c104fb">
```
Run:
   echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc
   source ~/.bashrc
To run Zed now, '~/.local/bin/zed'
```

**Comment by Rust44** [comment]
worked for me by adding path to zshrc
Here's how you can do it

1. use this command if you are using zsh terminal `nano ~/.zshrc`
2. add this line at the last: `export PATH="$HOME/.local/bin:$PATH"`
3. Save and Exit using Ctrl + O and Ctrl + X
4. Now reload it using `source ~/.zshrc`
