### ISSUE TITLE
Unable to open ZED after installing on Mac OS 15 for the first time

### ISSUE THREAD

**Issue by snoseakin** [zed-industries/zed#16375]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After adding Zed to application folder. I open it and get the error Zed failed to launch 
![image](https://github.com/user-attachments/assets/5d98fd02-51a1-4dbb-a516-38d52bf2cbee)

### Environment

Hardware:
  - Model Name: MacBook Air
  - Model Identifier: Mac15,12
  - Model Number: MXCU3LL/A
  - Chip: Apple M3
  - Total Number of Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
  - System Firmware Version: 11881.0.285.0.3
  - OS Loader Version: 11881.0.285.0.3

Memory:
  - 16 GB LPDDR5 by Hynix

Software:
  - macOS 15.0 (24A5298h)
  - Kernel Version: Darwin 24.0.0
  - Time Since Boot: 23 hours, 5 minutes

Power:
  - Battery Model: bq40z651
  - Battery Serial Number: F5D40630TKV10DLCK
  - Battery Condition: Normal
  - Cycle Count: 8
  - Maximum Capacity: 100%
  - State of Charge: 66%
  - System Power Settings:
    - AC Power: Sleep Timer (0 Minutes), Disk Sleep Timer (0 Minutes), Display Sleep Timer (180 Minutes), etc.
    - Battery Power: Sleep Timer (1 Minute), Disk Sleep Timer (10 Minutes), Display Sleep Timer (2 Minutes), etc.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

cat: /Users/sxxxxxx/Library/Logs/Zed/Zed.log: No such file or directory

**Comment by notpeter** [comment]
The permissions on your ~/.config directory are incorrect. Correct them and Zed will launch.
See here for more:
- https://github.com/zed-industries/zed/issues/13619

**Comment by snoseakin** [comment]
Thank u, that worked perfectly!!
