### ISSUE TITLE
[Accessibility] Alternative display style for editor.document_highlight.read_background

### ISSUE THREAD

**Issue by thataboy** [zed-industries/zed#16380]
### Check for existing issues

- [X] Completed

### Describe the feature

AFAIK, the only way to change appearance of dynamic bracket highlighting is with `editor.document_highlight.read_background`. This value is very dim by default in most themes, but regardless, changing the background color of a single character does not make it stand out very much. You don't want to go overboard since making it too bright only reduce contrast. Plus this color is also used to highlight words matching the one under the cursor and it would get too distracting. 

 
<img width="692" alt="Screenshot 2024-08-14 at 9 12 32 AM" src="https://github.com/user-attachments/assets/eed73d4e-2bbe-4137-9c4b-2a4d4f82087a">

I request another option to using the background color for this purpose, such as combination of different foreground color, style, and/or drawing a line beneath. Sublimetext does all of that as shown here

<img width="648" alt="Screenshot 2024-08-14 at 9 13 17 AM" src="https://github.com/user-attachments/assets/2cd39d45-00a4-4131-98be-e15cb57cadf3">

This is very clear and also looks nice (IMO). Obviously people with better eyes than mine will choose less bright colors, but I think this is an accessibility feature that will benefit everyone

**Comment by notpeter** [comment]
I see. So you're wanting support for `font_style` on things like `editor.document_highlight.read_background` which currently only support a hex color string. We already support this for `syntax` elements, so it's not too crazy. For example you can easily make comments italic using [theme overides](https://zed.dev/docs/themes#theme-overrides):

```json
  "experimental.theme_overrides": {
    "syntax": {
      "comment": {
        "color": "#afabb1ff",
        "font_style": "italic"
      }
    }
  },
```

<img width="495" alt="Screenshot 2024-08-16 at 17 04 43" src="https://github.com/user-attachments/assets/9119265a-322e-48b3-8c22-b783ffda36b0">

**Comment by thataboy** [comment]
> I see. So you're wanting support for `font_style` on things like `editor.document_highlight.read_background` which currently only support a hex color string. We already support this for `syntax` elements, so it's not too crazy. For example you can easily make comments italicKeAFJFCWPmAsik9E42KF2Ni9EoZ_AVrTE">

Yes, so instead of `editor.document_highlight.read_background`, we could have

```
"editor.document_highlight.read.style" = {
   "background": null,
   "foreground": "#f0f000",
   "font_style": "italic",
   "font_weight": 700  
}
```

Or maybe it'd make more sense as part of the syntax? I don't know

```
"syntax": {
   "punctuation.bracket.highlight": {
       "color": "#f0f033",
       "font_style": "italic",
       "font_weight": 700
   },
}
```
