### ISSUE TITLE
zed icon does not show in ubuntu dock

### ISSUE THREAD

**Issue by mahdic200** [zed-industries/zed#16396]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I'm using ubuntu 24 and it's default gnome gui . I installed zed with zed download page instructions . I have created ~/.local/share/zed-preview.desktop file and this is its configurations :
```config
[Desktop Entry]
Version=1.0
Type=Application
Name=Zed Preview
GenericName=Text Editor
Comment=A high-performance, multiplayer code editor.
TryExec=zed
StartupNotify=true
Exec=zed %U
Icon=~/.local/zed-preview.app/share/icons/hicolor/512x512/apps/zed.png
Categories=Utility;TextEditor;Development;IDE;
Keywords=zed;
MimeType=text/plain;inode/directory;x-scheme-handler/zed;
Actions=NewWorkspace;
Icon=~/.local/zed-preview.app/share/icons/hicolor/512x512/apps/zed.png

[Desktop Action NewWorkspace]
Exec=zed --new %U
Name=Open a new workspace
Icon=~/.local/zed-preview.app/share/icons/hicolor/512x512/apps/zed.png

```

when I open zed or new window with zed , there is no sign of zed icon in the dock

![Screenshot from 2024-08-17 07-41-28](https://github.com/user-attachments/assets/121afaa1-c17e-4785-8971-053d33c04055)

I have searched a lot and tried out many ways , but it's not going to be fixed . logged in/out for thousands of times . updated gnome desktop database / caches . other applications are just fine and when you give them the Icon path in .desktop file they will be fixed and the icon in the dock is right . but zed :) . it doesn't respect to my settings . 

### Environment

ubuntu 24.04 LTS
zed 0.147.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
> I have created ~/.local/share/zed-preview.desktop file

The name of that file is wrong, it should be `dev.zed.Zed-Preview.desktop`, matching the application id Zed sets on itself.

**Comment by mahdic200** [comment]
thanks a lot , you saved me ! . I didn't know that . there is no integrated gnome tutorial for beginners or at least I haven't found it ! . thanks a lot by the way .

**Comment by jansol** [comment]
In case someone stumbles here later on: the install.sh script writes this file with the correct name, and the [manual installation docs](https://zed.dev/docs/linux#downloading-manually) show the correct name for the stable release channel
