### ISSUE TITLE
C++ include missing header code action

### ISSUE THREAD

**Issue by Chetic** [zed-industries/zed#16399]
### Check for existing issues

- [X] Completed

### Describe the feature

main.cpp:
```c++
int main() {
  foo();
}
```
header.h:
```c++
static void foo() {}
```
header.h is in the include-path of main.cpp.
I expect to be able to automatically include header.h using a code action, at least for symbols available in the include path.

I'm not sure if there also is a bug lurking here since I get a popup that gives the impression zed recognizes the symbol (see screenshot below). Auto-completion does not add the include for me.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/d545590d-4daf-4dc6-9821-1bb6f615c9c4)

**Comment by WeetHet** [comment]
That's probably not a zed issue, but a clangd issue: https://github.com/clangd/clangd

**Comment by Chetic** [comment]
Well obviously it could be added on top of clangd since other IDEs must already have done it if it is not part of clangd. And there are good reasons to do this, if zed is to compete with those editors.

But maybe this is part of zed development philosophy - to not build features on top of language servers?

**Comment by WeetHet** [comment]
> Well obviously it could be added on top of clangd since other IDEs must already have done it if it is not part of clangd. And there are good reasons to do this, if zed is to compete with those editors.
> 
> But maybe this is part of zed development philosophy - to not build features on top of language servers?

Right now it seems like the team's focus is not on providing language server extensions, especially this complicated. It will surely be possible in the future as the extension API matures to implement it yourself. Please also note that VSCode with clangd doesn't provide this functionality either
