### ISSUE TITLE
Failing to initialize remote

### ISSUE THREAD

**Issue by paulgp** [zed-industries/zed#16406]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I execute `projects: open remote` for our high-performance cluster, I am able to successfully login to the server, where I get the following error:

```
/gpfs/home/psg24/.local/bin/zed: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /gpfs/home/psg24/.local/bin/zed)
```

The full log follows:

```
/gpfs/home/psg24/.local/bin/zed: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /gpfs/home/psg24/.local/bin/zed)
+ curl -f https://zed.dev/install.sh
+ sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4318  100  4318    0     0  15462      0 --:--:-- --:--:-- --:--:-- 15476
Downloading Zed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   565  100   565    0     0    394      0  0:00:01  0:00:01 --:--:--   395
100 57.5M  100 57.5M    0     0  28.5M      0  0:00:02  0:00:02 --:--:--  108M
Zed has been installed. Run with 'zed'
+ ZED_HEADLESS=1
+ /gpfs/home/psg24/.local/bin/zed --dev-server-token 5089.qrk37fCZtdXCTWM4Xt5JrbhsRoYN6SwASFtly3UIAU8NOk-r6FyFtxQvI1viKBYX
/gpfs/home/psg24/.local/bin/zed: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /gpfs/home/psg24/.local/bin/zed)

⏵ Task `Install zed over ssh` finished with non-zero error code: 1
⏵ Command: 'ssh psg24@hpc-sms.som.yale.edu'
```

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.1.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Moshyfawn** [comment]
From [Linux docs](https://github.com/zed-industries/zed/blob/5e6e465294c0605eaa76a30c9dcea2f98d410010/docs/src/linux.md?plain=1#L84):

> If you see an error like "/lib64/libc.so.6: version 'GLIBC_2.29' not found" it means that your distribution's version of glibc is too old. You can either upgrade your system, or [install Zed from source](./development/linux.md).

Please let us know if you were able to resolved the problem. Thank you.

**Comment by notpeter** [comment]
@paulgp Could you add a note of which distribution your cluster is running for future searchability?

I'm going to close this as it's a known issue but if run into problems building from source feel free to comment and I can reopen.

**Comment by paulgp** [comment]
Thanks very much everyone. 

The server runs Rocky Linux release 8.9 (Green Obsidian). I will try to build from source next!

**Comment by tannal** [comment]
I tried building from source. 

```bash
cargo install --path crates/zed/
```

```bash
ld.lld: error: unable to find library -lxcb
ld.lld: error: unable to find library -lxkbcommon
ld.lld: error: unable to find library -lxkbcommon-x11
```
why doe we need to link x11 libs for a remote server build?

**Comment by notpeter** [comment]
> Why doe we need to link x11 libs for a remote server build?

We do not currently have a build-time conditional for remote-only zed (sans X11, etc). Sorry.

**Comment by notpeter** [comment]
Statically compiled remote server has been merged here:
- https://github.com/zed-industries/zed/pull/19571

That has no glibc requirement. We expect this to be available in the next preview.
