### ISSUE TITLE
Escape line gets deleted with auto-format on, even in Regex queries.

### ISSUE THREAD

**Issue by yorunoken** [zed-industries/zed#16411]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

write the following in `index.js`
```js
const educationDuration = "(İÖ) (Ücretli) (2 Yıllık)";
        
// Regular expression to match a number followed by " Yıllık"
const match = educationDuration.match(/(\d+)\s*Yıllık/); // the `\d` and `\s` will become `d` and `s` after the auto-format.
        
console.log(match); // Will return `undefined` every single time because when the file is saved, the auto-formatter will remove `/`
```

### Environment

Zed: v0.148.1 (Zed)
OS: Linux Wayland arch unknown
Memory: 15.5 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6600 XT (RADV NAVI23) || radv || Mesa 24.2.0-arch1.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi @yorunoken, I was not able to reproduce this under Linux or MacOS with the default settings when I trigger a format.

Could you share your settings.json or any other configuration which might help reproduce this behavior? Thanks

**Comment by yorunoken** [comment]
Sorry @notpeter, I realized now that I was using double quotes to define the regex like `"/(\d+)\s*Yıllık/"`, it works fine without the quotes (which is how you're supposed to do it anyways), sorry for wasting time. You may close the issue now
