### ISSUE TITLE
Syntax highlighting stops working when copying / pasting code

### ISSUE THREAD

**Issue by oluijks** [zed-industries/zed#16415]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It is hard to give concrete example, but the title says it all. Usually, syntax highlighting stops working after copying / pasting some code. Halfway the file it stops the highlighting... Closing and reopening the file is my workaround for now. I mostly use svelte and rust files...

### Environment

Zed: v0.150.0 (Zed Dev f7f5a255845b45ac33ab88bfdc023894034168b7)
OS: Linux X11 arch unknown
Memory: 15.2 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 24.1.6-arch1.1

**Comment by notpeter** [comment]
I haven't experienced this personally, but if you can provide an example that reproduces it and/or any relevant lines from your Zed.log (`ctrl-shift-p`, `zed: open log`) when it occurs maybe we can track it down.

**Comment by soerenmeier** [comment]
I think i might have them same issue:
[Screencast from 2024-08-29 21-04-20.webm](https://github.com/user-attachments/assets/80376a73-b221-44f7-8e02-aa596e7695a0)
After the fourth level of indentation something is broken with syntax highlighting.

A reload fixes this.

## System
```
Zed: v0.150.4 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2080 Ti || NVIDIA || 535.183.01
```

## Extensions
```
emmet: 0.0.3
svelte: 0.0.3
scss: 0.0.3
html: 0.1.2
```

**Comment by notpeter** [comment]
Without concrete steps to reproduce there's not much we can do.
There have been improvements to the svelte extension, but if you are still seeing this please open an issue on the [zed svelte extension](https://github.com/zed-extensions/svelte) repo.

Thanks for reporting.

**Comment by soerenmeier** [comment]
My posted issue does not appear anymore
