### ISSUE TITLE
missing field `tooltip_text` for extension slash-commands-example

### ISSUE THREAD

**Issue by MBeggiato** [zed-industries/zed#16427]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Clone the repo and install the example extension "slash-commands-example".
In the logs you then can see the following:
```
2024-08-18T12:00:23.030408Z [ERROR] invalid extension.json for extension slash-commands-example

Caused by:
    TOML parse error at line 9, column 1
      |
    9 | [slash_commands.echo]
      | ^^^^^^^^^^^^^^^^^^^^^
    missing field "tooltip_text"
   ```

This can be fixed by adding the missing tooltip_text property in the extension.toml from the repo.

```
id = "slash-commands-example"
name = "Slash Commands Example"
description = "An example extension showcasing slash commands."
version = "0.1.0"
schema_version = 1
authors = ["Zed Industries <hi@zed.dev>"]
repository = "https://github.com/zed-industries/zed"

[slash_commands.echo]
description = "echoes the provided input"
tooltip_text = "echoes the provided input"
requires_argument = true

[slash_commands.pick-one]
description = "pick one of three options"
tooltip_text = "pick one of three options"
requires_argument = true
```

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

2024-08-18T12:00:23.030408Z [ERROR] invalid extension.json for extension slash-commands-example

Caused by:
    TOML parse error at line 9, column 1
      |
    9 | [slash_commands.echo]
      | ^^^^^^^^^^^^^^^^^^^^^
    missing field `tooltip_text`

**Comment by maxdeviant** [comment]
The `tooltip_text` field was removed in #16312. That change is currently available in Zed Preview v0.149.1, which is what the example extension requires (due to v0.1.0 of the Zed extension API).

It will land on Zed Stable this week.
