### ISSUE TITLE
Support for sed style s/regex/replace/ statements

### ISSUE THREAD

**Issue by baronyoung** [zed-industries/zed#16439]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm a frequent user of these kinds of searches from many years of vim use.  I have some pretty strong muscle memory for searching and replacing using the following keystrokes as an example: 
`:'<,'>s/textToSearch\(testToCapture\)/replaceWithThis\1/g`

The above includes the ability to search within selected text which is a separate issue. I'll create a separate feature request for that.

**Comment by notpeter** [comment]
@baronyoung I believe we actually support this already although there's very little visual feedback to indicate it will work.

For example, to replace double quotes with single quotes in `<a href="a.html">something</a>`: 

`:s/href="\([^"]+\)"/href='\1'/g` worked as expected.

Thanks for filing the other issue separately and apologies for leading you astray via email.
- https://github.com/zed-industries/zed/issues/16440

**Comment by baronyoung** [comment]
I swear this didn't work the first time I tried it but it is certainly working now.  I'm happy to continue trying out this editor now.  Great to see such rapid progress!

**Comment by notpeter** [comment]
It may not have. Our Vim mode has been rapidly improving, largely driven by user requests.

Please file issues for any other vim motions you use that don't behave as expected.
