### ISSUE TITLE
vim support for replace within a selection

### ISSUE THREAD

**Issue by baronyoung** [zed-industries/zed#16440]
### Check for existing issues

- [X] Completed

### Describe the feature

This doesn't appear to be supported at present and is something I use often, especially within sed style searches like this:

`:'<,'>s/textToSearch\(testToCapture\)/replaceWithThis\1/g`

**Comment by notpeter** [comment]
Zed has support for this. For GUI searches, it's the 'Toggle Search Selection' button. 
<img width="188" alt="Screenshot 2024-08-23 at 14 06 09" src="https://github.com/user-attachments/assets/b584e6c2-f52f-473c-b79a-30b0200d003a">
This is the `search::ToggleSelection"` action, bound to `cmd-alt-l` on MacOS or `ctrl--l` on Linux by default.

---
In vim mode, just press `:` with a selection then enter your substitution in that box and it should work as expected.
<img width="563" alt="Screenshot 2024-08-23 at 14 10 58" src="https://github.com/user-attachments/assets/c1afef32-5cb9-4eac-96a6-4f3b3c53adb8">

I wasn't aware Zed had added this feature back in June with:
- https://github.com/zed-industries/zed/pull/10831

Learn something new everyday!
