### ISSUE TITLE
.env file is being considered as Python virtual environment when launching terminal

### ISSUE THREAD

**Issue by frixaco** [zed-industries/zed#16448]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening terminal in **any** directory that has **`.env`** file inside Zed throws error:

```bash
source: Error encountered while sourcing file '/Users/frixaco/personal/test-zed/.env/bin/activate':
source: Not a directory
```

Reproduction:
1. Create a folder and `cd` into it
2. Create `.env` file
3. Open the folder with Zed

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
That seems to be fixed in the current Preview (v0.149.1), this Wednesday this gets propagated to Stable too.

https://github.com/zed-industries/zed/issues/15570#issuecomment-2294177968
