### ISSUE TITLE
.env file is considered as a virtual environment by terminal

### ISSUE THREAD

**Issue by vlebert** [zed-industries/zed#16462]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a python project if you have

- a `.env` file
- a `.venv `virtual env

Zed terminal tries to activate .env file instead of .venv directory

Generally, having a .env files generate error when opening terminal as zed consider it as a virtual environment

You can make a workaround by editing the order of the possible directory name in the setting 

Default setting 

```
"detect_venv": {
      "on": {
        // Default directories to search for virtual environments, relative
        // to the current working directory. We recommend overriding this
        // in your project's settings, rather than globally.
        "directories": [".env", "env", ".venv","venv"],
        // Can also be `csh`, `fish`, and `nushell`
        "activate_script": "default"
      }
    }
```

Workaround

```
"detect_venv": {
      "on": {
        // Default directories to search for virtual environments, relative
        // to the current working directory. We recommend overriding this
        // in your project's settings, rather than globally.
        "directories": [".venv", ".env", "env", "venv"],
        // Can also be `csh`, `fish`, and `nushell`
        "activate_script": "default"
      }
    }
```

The workaround still gives error for projects with only a .env file

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I believe this has been fixed in the current Zed Preview and will be in Zed Stable on Wednesday. See:

- https://github.com/zed-industries/zed/issues/15570#issuecomment-2294177968
