### ISSUE TITLE
Vue "Go to definition" no longer works

### ISSUE THREAD

**Issue by amir20** [zed-industries/zed#16469]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I thought I was doing something wrong, but started recently. Zed's `command+click` or right click to `go to definition` no longer works in Vue files. 

I have tested with a brand new project with `pnpm create vite` and then use Vue as template. 

Note that react using `pnpm create vite` still works. 

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/f8005875-12e0-4d90-acaf-93ff9a29a53d

### If applicable, attach your Zed.log file to this issue.
[Zed.log](https://github.com/user-attachments/files/16663237/Zed.log)

**Comment by amir20** [comment]
Note in the video the first window is a React example and second is the broken experience in Vue.

**Comment by fazulk** [comment]
related to this issue https://github.com/zed-industries/zed/issues/14723

**Comment by amir20** [comment]
That's funny because autocomplete works me. 🤷🏼‍♂️

**Comment by d1y** [comment]
I think you can provide the logs. I suspect that you may have installed other plugins?

**Comment by amir20** [comment]
Updated with logs.  Attached screenshot with extensions. 

This used to work. But now it is broken all my vue projects so I don't think it's related to something I am doing. 


<img width="1797" alt="Screenshot 2024-08-19 at 9 59 42 AM" src="https://github.com/user-attachments/assets/8431cc6c-68a1-459a-b35a-072213688745">

**Comment by d1y** [comment]
@amir20  I have also reproduced this issue and found that it seems to be caused by tailwindcss lsp(maybbbbe?)
Please try disabling it
After disabling it, I can work

```jsonc
{
	// disable tailwindcss
	"language_servers": ["!eslint", "!typescript-language-server", "!tailwindcss-language-server", "..."],
}
```

https://github.com/user-attachments/assets/695be601-ce26-42a8-934a-be2c41e7263f

**Comment by amir20** [comment]
Confirmed. `"language_servers": ["!tailwindcss-language-server"]` fixes the issue. Now the problem is, I do use Tailwind too. 

Is this related to https://github.com/zed-industries/zed/issues/14723? It doesn't seem like it.

**Comment by vknowles-rv** [comment]
I downgraded back to 1.142.2 and go to/code navigation started working again.

**Comment by amir20** [comment]
Yea I think I misspoke. Even with tailwind disabled I see this happening. I am wondering if some extension got auto updated. 

I also lost a lot of time. Going back to Vscode for a while.

**Comment by icarusgk** [comment]
Disabling the Tailwind extension with `"language_servers": ["!tailwindcss-language-server"]`
worked for me too.

**Comment by danulqua** [comment]
I don't even have the Tailwind extension, so it doesn't work even with `"language_servers": ["!tailwindcss-language-server"]`

**Comment by icarusgk** [comment]
@danulqua Try adding the three dots at the end `"language_servers": ["!tailwindcss-language-server", "..."]`

**Comment by flootr** [comment]
> I downgraded back to 1.147.2 and go to/code navigation started working again.

Downgrading worked for me, too. Setting `"language_servers": ["!tailwindcss-language-server", "..."]` did not, unfortunately.

**Comment by danulqua** [comment]
@icarusgk didn't work. Go to definition doesn't work at all everywhere, in `<template>` and in `<script>`.

**Comment by SomeoneToIgnore** [comment]
I have something that looks like a fix, waiting for the review/confirmation: https://github.com/zed-industries/zed/pull/16654

Meanwhile, using

```json5
"languages": {
  "Vue.js": {
    // this is a new line
    "language_servers": ["vue-language-server", "..."],
    "prettier": {
      "allowed": true
    }
  },
}

```
could help as a workaround.

**Comment by icarusgk** [comment]
Thank you @SomeoneToIgnore, That works! 🚀

**Comment by amir20** [comment]
Thank you @SomeoneToIgnore for the great work.

**Comment by misaelvillaverde** [comment]
Hello, same thing with Astro.

Used:
```json
  "languages": {
    "Astro": {
      "language_servers": ["astro-language-server"]
    },
    ...
  }
```

**Comment by SomeoneToIgnore** [comment]
Astro seems to have a single language server supported, so this seems a bit unrelated: the current workaround forces a certain, primary, language server to be used first, e.g. :
```json
    "language_servers": ["vue-language-server", "..."],
```

which is not applicable to a single entry, really.

**Comment by misaelvillaverde** [comment]
I understand, but the "go to definition" doesn't work in astro files (at least on my end) without explicitly setting that up.

**Comment by shishkin** [comment]
@SomeoneToIgnore I can confirm that your workaround fixes Astro as well.

**Comment by lamcc21** [comment]
> "language_servers": ["vue-language-server", "..."],

this worked for me
