### ISSUE TITLE
Add "trailing" option for whitespace rendering

### ISSUE THREAD

**Issue by ZestyGarlicPickles** [zed-industries/zed#16500]
### Check for existing issues

- [X] Completed

### Describe the feature

As of right now, there is no option to render trailing whitespace only. This is a quality of life feature I always appreciate, because it only shows the whitespace characters you probably want to get rid of.

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/5237

**Comment by beniaminzagan** [comment]
> ### Check for existing issues
> 
> * [x]  Completed
> 
> ### Describe the feature
> 
> As of right now, there is no option to render trailing whitespace only. This is a quality of life feature I always appreciate, because it only shows the whitespace characters you probably want to get rid of.
> 
> ### If applicable, add mockups / screenshots to help present your vision of the feature
> 
> _No response_

Hi, I think we already cover this with: "remove_trailing_whitespace_on_save": true, which is already true by default.
