### ISSUE TITLE
Vim: absolute numbering in any mode except `insert` mode

### ISSUE THREAD

**Issue by Conaclos** [zed-industries/zed#16514]
### Check for existing issues

- [X] Completed

### Describe the feature

I am using the following vim configuration that allows relative numbering in any mode except in insert mode:

```vim9
set relativenumber # Relative line numbering

autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber
```

For now, Zed forces me to choose between relative line numbering or absolute line numbering.

I am not sure how this feature should be introduced. I see two possible approaches:

- add a new option `line_numbers` that takes `absolute`, `relative` and `both` as values. `both` could be the behavior I described here. Unfortunately I didn't find a better name...
- add a way to change settings using contexts (the same concept used by keymaps).
  We could imagine something like:
  ```json
  {
    "context": "vim_mode == insert",
    "settings": { "relative_line_numbers": false }
  },
  {
    "context": "vim_mode != insert",
    "settings": { "relative_line_numbers": true }
  }
  ```
  However, this could introduce many issues. For example: should we accept any settings like theme, ...?

**Comment by 0x2CA** [comment]
Can refer to the VSCode Vim plugin to add a setting for smart relative line numbers.
https://github.com/VSCodeVim/Vim/issues/3020

**Comment by feketegy** [comment]
I know I'm in the minority but I usually use both numbering in Neovim, absolute and relative side-by-side so an option for showing `both` would be awesome.

This is how Neovim does it:

![absolute-relative](https://github.com/user-attachments/assets/38f5b450-fcd0-46b8-b683-ab19620dffb9)

**Comment by LittleFat3Tuan** [comment]
> I know I'm in the minority but I usually use both numbering in Neovim, absolute and relative side-by-side so an option for showing `both` would be awesome.
> 
> This is how Neovim does it:
> 
> ![absolute-relative](https://private-user-images.githubusercontent.com/489775/360862050-38f5b450-fcd0-46b8-b683-ab19620dffb9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTkyNjEsIm5iZiI6MTcyNTUxODk2MSwicGF0aCI6Ii80ODk3NzUvMzYwODYyMDUwLTM4ZjViNDUwLWZjZDAtNDZiOC1iNjgzLWFiMTk2MjBkZmZiOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNjQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTZjYmYxMmRmODM3YWVlZDUxMGVjYzM1MTFkYzcyNTYyNWZlYWIyOGYyMDNjZTczYmFjMDg3Yjg4MWRmNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTT69oFNTAyAurWovYNZ3n5vbL8mmsyShIJjvi6WkQ4) [ ![absolute-relative](https://private-user-images.githubusercontent.com/489775/360862050-38f5b450-fcd0-46b8-b683-ab19620dffb9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTkyNjEsIm5iZiI6MTcyNTUxODk2MSwicGF0aCI6Ii80ODk3NzUvMzYwODYyMDUwLTM4ZjViNDUwLWZjZDAtNDZiOC1iNjgzLWFiMTk2MjBkZmZiOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNjQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTZjYmYxMmRmODM3YWVlZDUxMGVjYzM1MTFkYzcyNTYyNWZlYWIyOGYyMDNjZTczYmFjMDg3Yjg4MWRmNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTT69oFNTAyAurWovYNZ3n5vbL8mmsyShIJjvi6WkQ4) ](https://private-user-images.githubusercontent.com/489775/360862050-38f5b450-fcd0-46b8-b683-ab19620dffb9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTkyNjEsIm5iZiI6MTcyNTUxODk2MSwicGF0aCI6Ii80ODk3NzUvMzYwODYyMDUwLTM4ZjViNDUwLWZjZDAtNDZiOC1iNjgzLWFiMTk2MjBkZmZiOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNjQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTZjYmYxMmRmODM3YWVlZDUxMGVjYzM1MTFkYzcyNTYyNWZlYWIyOGYyMDNjZTczYmFjMDg3Yjg4MWRmNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTT69oFNTAyAurWovYNZ3n5vbL8mmsyShIJjvi6WkQ4) [ ](https://private-user-images.githubusercontent.com/489775/360862050-38f5b450-fcd0-46b8-b683-ab19620dffb9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTkyNjEsIm5iZiI6MTcyNTUxODk2MSwicGF0aCI6Ii80ODk3NzUvMzYwODYyMDUwLTM4ZjViNDUwLWZjZDAtNDZiOC1iNjgzLWFiMTk2MjBkZmZiOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNjQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTZjYmYxMmRmODM3YWVlZDUxMGVjYzM1MTFkYzcyNTYyNWZlYWIyOGYyMDNjZTczYmFjMDg3Yjg4MWRmNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTT69oFNTAyAurWovYNZ3n5vbL8mmsyShIJjvi6WkQ4)

Would love this, too. Don't know why this is already marked "closed".

**Comment by ConradIrwin** [comment]
@LittleFat3Tuan Sounds like a different feature request than the one described here. Could you please open a separate issue for it.

**Comment by muja** [comment]
Has anything been done in this regard? Relative line numbers are a must _locally_, but when you're scrolled 200 lines away from your cursor, they are useless. Context-sensitive absolute line numbers would be awesome. Always side-by-side would be a trade-off although it's a bit bloaty
