### ISSUE TITLE
Could not create directory /Users/x/.cache/zed": Permission denied (os error 13)

### ISSUE THREAD

**Issue by demeoni** [zed-industries/zed#16543]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

launching app error:

Zed failed to launch
Could not create directory /Users/x/.cache/zed": Permission denied (os error 13)

### Environment

App version : 0.149.3
08/20/2024

mac m1 air, on macos 12.7.2

**Comment by LukasGaebler** [comment]
i have the same issue. mac m3 pro, on macos 14.6.1

**Comment by SomeoneToIgnore** [comment]
There's been quite a lot of similar issues, searching them might help to find the solution: https://github.com/zed-industries/zed/issues?q=is%3Aissue+Permission+denied+%28os+error+13%29+is%3Aclosed+

For instance, https://github.com/zed-industries/zed/issues/13271#issuecomment-2179543825 has some instructions.

Closing in favor of https://github.com/zed-industries/zed/issues/13619
