### ISSUE TITLE
Zed assistant not returning anything

### ISSUE THREAD

**Issue by mfvas** [zed-industries/zed#16541]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When logged in to Zed, to use the default Zed AI assistant, the assistant never returns a reply.

It looks similar to not having any OpenAI credits left, but shouldn't it work using the default Zed assistant?

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2024-08-20 at 21 07 09@2x](https://github.com/user-attachments/assets/c3612950-0de9-4ba2-be82-68f5934a3de6)
![CleanShot 2024-08-20 at 21 03 33@2x](https://github.com/user-attachments/assets/a3e0212a-ac76-4894-b8c5-d1cec512ae45)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxdeviant** [comment]
It looks like you're on Zed v0.148.x. Could you install the latest update (v0.149.3, if you're on the Stable channel) and try again?

**Comment by ribelo** [comment]
I had the same issue. The `provider` automatically changes to `zed.dev`. You need to manually set it to `anthropic` or `openai` in the config file and then it starts working.

**Comment by mfvas** [comment]
Soo, I didn't do anything, but it works today 🤷‍♂️ Thank you for your answers!
