### ISSUE TITLE
Hide language models

### ISSUE THREAD

**Issue by KaBankz** [zed-industries/zed#16568]
### Check for existing issues

- [X] Completed

### Describe the feature

Add a setting to hide language models.

There are a lot of models listed in the assistant panel, but I only use a handful of them, usually Ollama and Copilot. I haven't set up the rest, nor do I want to.

The unused models clutter up the menu, and waste space, so being able to hide them would be much appreciated.

### If applicable, add mockups / screenshots to help present your vision of the feature

| Before | After |
|--------|--------|
| ![Before](https://github.com/user-attachments/assets/f9609151-d49c-43b7-b3d2-7d95f3b69318) | ![After](https://github.com/user-attachments/assets/73b751ed-cbd9-4d5d-8692-354250b72b39) |

**Comment by Malix-Labs** [comment]
@danilo-leal I feel like #20392 is not exactly what has been asked and that [this issue has been closed](https://github.com/zed-industries/zed/issues/16568#event-15215377498) a bit prematurely

#20392 hides models that are not configured, but I don't think it makes Zed users able to hide models they want to hide

For example, I am using GitHub Copilot as a provider, but I cannot hide the models I will never use (for instance, GPT-4.1) :

<img width="318" height="405" alt="Image" src="https://github.com/user-attachments/assets/53b068a6-d58b-43ee-b249-7febc8af4712" />
