### ISSUE TITLE
High CPU Usage When Opening https://zed.dev

### ISSUE THREAD

**Issue by screw-hand** [zed-industries/zed#16563]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello, I have noticed that when I open the website https://zed.dev/, it causes unusually high CPU usage on my machine. Here are some details that might help in diagnosing the issue:

1. Operating System and Version: macOS 13.6.6
2. Browser and Version:Microsoft Edge 128.0.2739.5 Dev (arm64)
3. Steps to Reproduce: Simply visiting https://zed.dev/ causes the CPU spike.
4. Hardware Specifications:
	CPU: Apple M1 Pro
	RAM: 16GB
5. Additional Information:
The issue persists even when using Edge in Incognito mode and with all extensions disabled.

Thank you for looking into this issue. If more information is required, please let me know.

![image](https://github.com/user-attachments/assets/8b51bf32-b736-44f1-ba82-ba6515158616)

### Environment

.

**Comment by failable** [comment]
The official website eats all my CPUs.

**Comment by danilo-leal** [comment]
Hey—thanks for reporting! We recently pushed a fix to this; I suspect it was mostly due to the large particle effect we had on display in the features section. Can y'all check again and report if it's better? Will wait for the feedback to close the issue.
