### ISSUE TITLE
Can't input the @ symbol in the terminal window anymore!

### ISSUE THREAD

**Issue by smellord** [zed-industries/zed#16581]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use a German layout keyboard on a Mac and to type the @ symbol I would normally press Alt gr + Q but that shortcut has been assigned to something like "delete current line" in one of the later updates. 
There is no way for me to input the @ symbol.. I tried looking for the default or custom shortcuts but I couldn't find any alt+q shortcut so it must be something hardcoded

### Environment

Model Name:	MacBook Pro
  Model Identifier:	Mac15,6
  Model Number:	MRX33D/A
  Chip:	Apple M3 Pro
  Total Number of Cores:	11 (5 performance and 6 efficiency)
  Memory:	18 GB
  System Firmware Version:	10151.121.1
  OS Loader Version:	10151.121.1
  Serial Number (system):	J04D94KXL6
  Hardware UUID:	394D1D1A-0DF3-5035-86B6-CCED325644AF
  Provisioning UDID:	00006030-000611640C84001C
  Activation Lock Status:	Enabled

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
you can try set settings with
```json
{
  "terminal": {
    "option_as_meta": false,
  }
}
```

**Comment by chronark** [comment]
Hey, I encountered a similar issue, also on a macbook pro with german layout. Disabling `option_as_meta` as suggested by @CharlesChen0823 did the trick

context: https://x.com/chronark_/status/1830570848194891875

**Comment by smellord** [comment]
yes, it's solved. thanks a bunch!

**Comment by minimo-io** [comment]
Similar problem on a Mac mini with an spanish keyboard. Unable to create a pipe |
`  "option_as_meta": false,` solved the issue!

**Comment by jesuspavonm** [comment]
How do you set this? I mean, which file should I need to edit to make this work?
