### ISSUE TITLE
Inconsistent Functionality of "GoToDefinitionSplit" (Alt + Ctrl + LMB) in Zed IDE on Windows

### ISSUE THREAD

**Issue by a-kachurin** [zed-industries/zed#16605]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a .py file in Zed IDE that includes definitions or references (e.g., functions, classes);
2. Hold the Alt and Ctrl keys simultaneously, click on a definition or reference using the Left Mouse Button (LMB)  to trigger the "GoToDefinitionSplit" function, which should open the definition in a split tab

### Environment

Zed: v0.151.0 (Zed Dev 28568429aa26260f273b86294b8f5d1bc5d95b7b)
OS: Windows 10.0.22631
Memory: 63.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4090 || NVIDIA || 555.99

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by a-kachurin** [comment]
The issue occurs when we quickly attempt to perform "Go to Definition" before the tooltip for the function, attribute, etc. appears.

**Comment by a-kachurin** [comment]
Can someone help with this? My main obstacle before using IDE( If you tell me where to look, I would try to figure out the problem(

**Comment by biblicabeebli** [comment]
There's two operations, you may just want to swap to the other one.  This is from the Jetbrains base keyboard layout.
```
"f12": "editor::GoToDefinition",
"alt-f12": "editor::GoToDefinitionSplit",
```

**Comment by a-kachurin** [comment]
It opens by keyboard fine, my problem is that it works intermittently through a mouse click + ctrl + alt(
