### ISSUE TITLE
odd behavior for ERB templates

### ISSUE THREAD

**Issue by Roguelazer** [zed-industries/zed#16617]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing ERB templates in Zed, I'm getting two strange behaviors:

 - When typing the `|` character, two pipes (`||`) get inserted and the cursor gets moved after the second one
 - Indentation is four spaces despite my setting `tab_size: 2` for both ERB and Ruby languages

Relevant settings:
```json
{
  "tab_size": 4,
  "hard_tabs": false,
  "use_autoclose": false,
  "languages": {
    "Ruby": {
      "language_servers": ["ruby-lsp", "rubocop", "!solargraph"],
      "use_auto_surround": true,
      "tab_size": 2
    },
    "ERB": {
      "tab_size": 2
    }
  }
}
```

The status bar shows the language as ERB.

### Environment

Zed: v0.149.3 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

**Comment by vitallium** [comment]
@Roguelazer thanks for reporting! Can you please share an example? I tried to reproduce it with Ruby extension 0.1.0 and Zed Dev 0.151.0 but everything looks as it should be. I think a simple ERB snippet should be enough.

**Comment by Roguelazer** [comment]
It actually happens for me on a blank ERB file! Here's a small screen recording:


https://github.com/user-attachments/assets/ee202123-96df-4bd2-9213-8614ce221a77

**Comment by Roguelazer** [comment]
That seems to have fixed it! Thanks for your help! It might be worth calling out some of these details (that ERB is also HTML, and that `onTypeFormatting` is a bit wonky) in the docs somewhere, but that works for me.

Cheers!

**Comment by benjaminwelch** [comment]
@vitallium I think i'm running into the same issue but instead it's quotes (single/double) when using ERB.

I wanted to try disabling the feature you mentioned for "ruby-lsp" but I wasn't sure where to put this in Zed.

Here is an example of what I'm seeing. It's some bug with autoclose:

![zed-quote-insert-bug](https://github.com/user-attachments/assets/3c7710e6-0977-4216-a6d1-82b8e3e37b2e)

This happens with all autoclose characters: { [ ( ' " etc. when using ERB. Thanks for your help!

**Comment by vitallium** [comment]
> @vitallium I think i'm running into the same issue but instead it's quotes (single/double) when using ERB.
> 
> I wanted to try disabling the feature you mentioned for "ruby-lsp" but I wasn't sure where to put this in Zed.
> 
> Here is an example of what I'm seeing. It's some bug with autoclose:
> 
> ![zed-quote-insert-bug](https://private-user-images.githubusercontent.com/610197/361001904-3c7710e6-0977-4216-a6d1-82b8e3e37b2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTg5ODYsIm5iZiI6MTczNDE5ODY4NiwicGF0aCI6Ii82MTAxOTcvMzYxMDAxOTA0LTNjNzcxMGU2LTA5NzctNDIxNi1hNmQxLTgyYjhlM2UzN2IyZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzUxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTMzY2Y5YTYzNDRjZGNiZWU4MmFlMDJmNjk3OTZhMmRlNDJjNThjOWE4MjU1N2YxOTQ5NzE3NjY0ZTMwYTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-hKl0DqFI6RyJXLJZXFWRWFbsTlwNBRb3y2h5145LEk) [ ![zed-quote-insert-bug](https://private-user-images.githubusercontent.com/610197/361001904-3c7710e6-0977-4216-a6d1-82b8e3e37b2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTg5ODYsIm5iZiI6MTczNDE5ODY4NiwicGF0aCI6Ii82MTAxOTcvMzYxMDAxOTA0LTNjNzcxMGU2LTA5NzctNDIxNi1hNmQxLTgyYjhlM2UzN2IyZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzUxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTMzY2Y5YTYzNDRjZGNiZWU4MmFlMDJmNjk3OTZhMmRlNDJjNThjOWE4MjU1N2YxOTQ5NzE3NjY0ZTMwYTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-hKl0DqFI6RyJXLJZXFWRWFbsTlwNBRb3y2h5145LEk) ](https://private-user-images.githubusercontent.com/610197/361001904-3c7710e6-0977-4216-a6d1-82b8e3e37b2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTg5ODYsIm5iZiI6MTczNDE5ODY4NiwicGF0aCI6Ii82MTAxOTcvMzYxMDAxOTA0LTNjNzcxMGU2LTA5NzctNDIxNi1hNmQxLTgyYjhlM2UzN2IyZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzUxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTMzY2Y5YTYzNDRjZGNiZWU4MmFlMDJmNjk3OTZhMmRlNDJjNThjOWE4MjU1N2YxOTQ5NzE3NjY0ZTMwYTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-hKl0DqFI6RyJXLJZXFWRWFbsTlwNBRb3y2h5145LEk) [ ](https://private-user-images.githubusercontent.com/610197/361001904-3c7710e6-0977-4216-a6d1-82b8e3e37b2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTg5ODYsIm5iZiI6MTczNDE5ODY4NiwicGF0aCI6Ii82MTAxOTcvMzYxMDAxOTA0LTNjNzcxMGU2LTA5NzctNDIxNi1hNmQxLTgyYjhlM2UzN2IyZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzUxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTMzY2Y5YTYzNDRjZGNiZWU4MmFlMDJmNjk3OTZhMmRlNDJjNThjOWE4MjU1N2YxOTQ5NzE3NjY0ZTMwYTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-hKl0DqFI6RyJXLJZXFWRWFbsTlwNBRb3y2h5145LEk)
> 
> This happens with all autoclose characters: { [ ( ' " etc. when using ERB. Thanks for your help!
> 
> EDIT: I noticed that this only happens the first time in an ERB tag. For example:
> 
> ```
>   <%= turbo_stream.replace "new_transaction", partial: "transactions/form" %>
> ```
> 
> The issue happens for `"new_transaction"` but not for `"transactions/form"`. Once the first quote, bracket, etc is closed, the rest work as expected within that tag.

Sorry for the late reply, @benjaminwelch. Could you please check if this issue occurs with the latest versions of Zed and the Ruby extension? I tried to reproduce it but had no luck. Perhaps a recent change in Zed has already fixed the issue. If you can reproduce it, could you please open an issue on the Ruby extension tracker at https://github.com/zed-extensions/ruby? Thanks!

**Comment by benjaminwelch** [comment]
@vitallium I just updated Zed and it asked me if I wanted to update my Ruby extension which I did and things are working great now. I no longer see this issue.

Thanks so much for the follow-up.
