### ISSUE TITLE
Add ability to collapse all open folders

### ISSUE THREAD

**Issue by CoryWritesCode** [zed-industries/zed#16627]
### Check for existing issues

- [X] Completed

### Describe the feature

Add button or command to collapse all open folders.
This just allows a user to keep their folder system clean.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/user-attachments/assets/58761b7c-2876-4123-a17f-23f53aceb3c1

**Comment by 0x2CA** [comment]
This command exists, you just need to bind a keymap to call it quickly.
![image](https://github.com/user-attachments/assets/e20f108a-e079-474c-af4c-afd0c2f854a8)

**Comment by dialguiba** [comment]
I think that you can right-click the parent folder and select 'collapse all'

**Comment by JosephTLyons** [comment]
I think one of these issues probably covers this request, so feel free to upvote these (👍)

- https://github.com/zed-industries/zed/issues/15966
- https://github.com/zed-industries/zed/issues/4379

Will close this out as a duplicate.

**Comment by CoryWritesCode** [comment]
> This command exists, you just need to bind a keymap to call it quickly.

Thanks for pointing this out albeit the nomenclature is a bit above my head it would seem. I wouldn't have ever searched for "entries" as it relates to files or directories.

**Comment by rubin55** [comment]
In current versions of Zed, these options do not show up. Additionally, right-mouse-menu "Collapse All" menu item does not collapse any folders in the project pane. I susepct this is because it is a project with multiple folders. This is Zed `0.187.8` on Linux btw.
