### ISSUE TITLE
Website: a small typo on the FAQ page

### ISSUE THREAD

**Issue by chenyo-17** [zed-industries/zed#16664]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A small typo on the [FAQ page](https://zed.dev/faq): "collectiong" -> "collection"

### Environment

N/A

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![zed_faq_typo](https://github.com/user-attachments/assets/3202a76a-a212-4b50-a34e-657b968b7575)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by danilo-leal** [comment]
Hey! Thanks for the report—the fix has been pushed and will be live soon; appreciate it.
