### ISSUE TITLE
"vim: increment" is inconsistent with vim

### ISSUE THREAD

**Issue by xzfc** [zed-industries/zed#16672]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've stumbled to the following limitations/inconsistencies with the `^A` ("vim: increment") command:

1. The range is limited to `i32` range. I.e. incrementing `2147483647` results in `-2147483648`, and not `2147483648` as expected. By comparison, the original vim support values from `-18446744073709551615` to `18446744073709551615`, aka 2⁻⁶⁴ to 2⁶⁴. Given that most modern languages support 53-bit or 64-bit integer literals, it's a not rare situation to have such huge values in the code.
2. It drops leading zeroes. E.g. incrementing `0x0001` results in `0x2` and not in `0x0002` as in the original vim.
3. Incrementing `0x39u32` twice (`^A ^A`) results in `0x3au33`, and not in `0x3bu32` as in the original vim.

### Environment

zed 0.149.3

**Comment by ConradIrwin** [comment]
Thanks for reporting! If you want to pair with me on any of these: https://calendly.com/conradirwin/pairing
