### ISSUE TITLE
Assistant New Context button / new file mixed behavior depending on area focus

### ISSUE THREAD

**Issue by smltr** [zed-industries/zed#16676]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

# Issue

When the Assistant panel is not focused, and the + (New Context) button is pressed at the top right of the assistant panel, instead of opening a new context, a new untitled file is opened in the file editor area. Also, If the assistant panel is focused, using the new file command opens a new context. This seems confusing and there should maybe be a separate command for new context / new file. It seems currently adding a new context uses the same command as adding a new file and the area focus decides if it creates a new file / new context.

 ## To Reproduce

- Click somewhere out of the assistant panel such as the text editor area or file tree area, then click the + (New Context) button in the assistant panel. A new file opens when you would expect a new Assistant Context to open. (See first screen recording below)
- Click to focus the Assistant Panel, then run the new file command. A new Assistant Context opens when you would expect a new untitled file to be created. (See second screen recording below)

## Fix

I think it would make sense to separate the new context and new file functionalities into unique commands. This would involve adding a new command for the new context, as there doesn't seem to be one now.

I have been wanting to start contributing, this seems like it could be a good first issue for me if help is wanted here.

### Environment

Zed: v0.149.3 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/2d3db351-ca82-48ce-b6d0-e7f407a52300

https://github.com/user-attachments/assets/82be8fa9-cbaa-46aa-a06b-19f74ae1f127

> 

> 

### If applicable, attach your Zed.log file to this issue.

N/A

**Comment by ramipellumbi** [comment]
Seeing this issue as well (0.150.4 MacOS). If focused in the editor pane and I select `New Context` in the chat pane, it opens a new file in the editor.

**Comment by osiewicz** [comment]
You're spot on, we reuse `editor::NewFile` for spawning new context and that's why you're observing this behavior.

**Comment by ramipellumbi** [comment]
I have this fixed locally -- will open a PR later today
