### ISSUE TITLE
LSP output to agent context

### ISSUE THREAD

**Issue by o1lo01ol1o** [zed-industries/zed#16683]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to be able to send some or all of the Project Diagnostics (from the active LSP) to the agent's context in the same way as files or buffers.  Type errors are the lingua franca of strongly typed langauges and are necessary to develop with AI support.

**Comment by rgbkrk** [comment]
`/diagnostics` will get you errors from the LSP and `/diagnostics --include-warnings` will also bring in warnings. Note that inline assist uses your current active chat, so if you summon diagnostics there, it'll be available to the model.
