### ISSUE TITLE
Can't install dev extensions

### ISSUE THREAD

**Issue by DanielEdrisian** [zed-industries/zed#16693]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Clicking on "Install Dev Extension" opens the folder upload dialog, but when selecting a folder, it silent quits and no extension is installed. I have tried both the example dev extension as well as my own extension. Nothing happens.

Based on Zed logs, it seems that there's an `[ERROR] failed to compile Rust extension`, but I can't seem to understand why.

### Environment

Zed: v0.149.3 (Zed)
OS: macOS 14.4.0
Memory: 36 GiB
Architecture: aarch64

## Step 1: Click Install Dev Extension button

<img width="300" alt="Screenshot 2024-08-22 at 11 50 57 AM" src="https://github.com/user-attachments/assets/af93b1d5-5836-457f-a9c2-e11237f8a330">

## Step 2: Select folder for sample extension
<img width="300" alt="Screenshot 2024-08-22 at 11 50 53 AM" src="https://github.com/user-attachments/assets/eca5aa67-d25c-4f3f-b54b-a8a6353be76e">

## Step 3: Watch as nothing happens
<img width="300" alt="Screenshot 2024-08-22 at 11 50 46 AM" src="https://github.com/user-attachments/assets/cca01ce1-bb80-45b9-8ee0-9da4614761c2">

I have also tried reloading the workspace and nothing happens.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-08-22T18:48:30.245645Z [INFO] compiling Rust extension /Users/danieledrisian/Downloads/zed-main/extensions/slash-commands-example
2024-08-22T18:48:30.249274Z [ERROR] failed to compile Rust extension

Caused by:
    0: failed to run rustc
    1: No such file or directory (os error 2)
2024-08-22T18:50:54.1274Z [INFO] compiling Rust extension /Users/danieledrisian/Downloads/zed-main/extensions/slash-commands-example
2024-08-22T18:50:54.128777Z [ERROR] failed to compile Rust extension

Caused by:
    0: failed to run rustc
    1: No such file or directory (os error 2)

</pre></details>

**Comment by DanielEdrisian** [comment]
Update: Found the problem. I hadn't installed rust on my mac.

After [installing rust](https://www.rust-lang.org/tools/install) and repeating the steps, and then refreshing extensions (cmd+shift+p & search extension) a couple of times, the sample rust extension appeared.

**Comment by sagarspatil** [comment]
> Update: Found the problem. I hadn't installed rust on my mac.
> 
> After [installing rust](https://www.rust-lang.org/tools/install) and repeating the steps, and then refreshing extensions (cmd+shift+p & search extension) a couple of times, the sample rust extension appeared.

Spent an hour trying to figure out what's wrong. They should setup rust as part of zed setup or document that dev installs require rust. 
I'll try opening a PR.
