### ISSUE TITLE
Allow SendKeystrokes to enter spaces

### ISSUE THREAD

**Issue by daytonn** [zed-industries/zed#16692]
### Check for existing issues

- [X] Completed

### Describe the feature

`SendKeystrokes` apparently uses spaces to concatenate individual keystrokes. This prevents the `SendKeystrokes` command from inserting spaces.

### If applicable, add mockups / screenshots to help present your vision of the feature

I use key chords to insert certain syntax. For example `|>` or `=>` for Elixir. I would like to bind a keycombo that inserts the `|>` with a space after it for quick pipeline editing in Elixir:

```
"super-alt-=": ["workspace::SendKeystrokes", "=> "],
"super-alt-.": ["workspace::SendKeystrokes", "|> "],
```

Currently the space at the end of this definition is ignored.

**Comment by SomeoneToIgnore** [comment]
Could you use `", ,": ["editor::HandleInput", ","]` for similar purposes?

**Comment by daytonn** [comment]
@SomeoneToIgnore That works! Thanks for the suggestion. I wasn't aware of `editor::HandleInput`.

It seems like this is the better way to bind key combos to character sequences. This fix would also apply to https://github.com/zed-industries/zed/issues/16691

I'll leave this open to let the devs consider whether they still consider this a defect but for my purposes of setting a key-binding `editor::HandleInput` solves my issue.

**Comment by feketegy** [comment]
Space can be written as a special text like `space`. This should work I think:


```
"super-alt-=": ["workspace::SendKeystrokes", "=> space"],
"super-alt-.": ["workspace::SendKeystrokes", "|> space"],
```

**Comment by SomeoneToIgnore** [comment]
That makes a lot of sense to me, actually, so I think everything works as expected.
