### ISSUE TITLE
make the tab switcher searchable/filterable

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#16710]
### Check for existing issues

- [X] Completed

### Describe the feature

most of the other modals (command palette, file finder, project symbols, and buffer symbols) are all searchable. When I have many tabs open, I'd like to be able to perform the same search/filtering I can do with all of these other modals.

**Comment by Moshyfawn** [comment]
This has already been brought up in another issue, so I will close this one in its favour to keep the conversation in one place. Be sure to +👍 the other thread.

Duplicate of:
- #16055
