### ISSUE TITLE
Disable EvenBetterTOML while preserving syntax highlighting

### ISSUE THREAD

**Issue by knyazer** [zed-industries/zed#16726]
### Check for existing issues

- [X] Completed

### Describe the feature

I am using a pretty extensive ruff (python language server) configuration file in my pyproject.toml, and there is a part that looks like this (opt-in into everything): 
```toml
[tool.ruff.lint]
select = ["F", "E", "W", "C90", "I", "N", "UP", "YTT", "ASYNC",
    "ASYNC1", "S", "FBT", "B", "A", "COM", "C4", "DTZ",
    "T10", "DJ", "EM", "EXE", "FA", "ISC", "ICN", "LOG", "G", "INP",
    "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM",
    "TID", "INT", "ARG", "PTH", "TD", "FIX", "ERA", "PD",
    "PL", "C", "R", "TRY", "FLY", "NPY", "AIR", "RUF"]

```

However, the TOML extension v0.1.1 (on the preview Zed) not only reformats it (which I want to avoid), but also complains about EvenBetterTOML violation.

I would love to have the ability to enable syntax highlighting in toml files, while ignoring EvenBetterTOML and possibly formatting. My current solution is to not have the extension installed, thus having no syntax highlighting.

### If applicable, add mockups / screenshots to help present your vision of the feature

Maybe adding  some configuration for the extension (oh wow, this sounds like a very large feature that was already requested a million times) or make an extension like "universal highlight", that would enable highlighting in all the files out there.

**Comment by SomeoneToIgnore** [comment]
I am not sure this about the exact syntax, but this is the direction to disable langservers: adjust `language` settings in your settings.json 

```json
"languages": {
    "TOML": {
      "language_servers": ["!Taplo"]
    }
}
```

and mention the language name as the key, and LSP server as a name. 
According to https://github.com/zed-industries/zed/blob/bdf26fe38ad0106346ac221c5a9c017df6268bcb/extensions/toml/extension.toml#L12-L15 it seems to be correct, but I did not try it.

**Comment by knyazer** [comment]
Wow, it works! Thanks @SomeoneToIgnore
