### ISSUE TITLE
Alt/Option not working in integrated terminal (german keyboard)

### ISSUE THREAD

**Issue by gtnebel** [zed-industries/zed#16730]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run Zed on macos and I really like it so far. But the integrated terminal is not working for me. I have a german keyboard layout. All Alt/Option keyboard combinations (for example | { } \ [ ]) are not working and simply do not print any character. That makes the integrated terminal not usable but for the simplest tasks.

When using this keyboard combinations, no log entries are generated. 

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

German keyboard
Default (VSCode) keymap

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you try adding this to your zed settings?
```
{
  "terminal": {
    "option_as_meta": false
  }
}
```

See: [Terminal: Option-as-meta](https://zed.dev/docs/configuring-zed#terminal-option-as-meta) in the docs.  We currently enable this by default to support emacs/readline style `meta+key` style actions by default in terminal.

**Comment by gtnebel** [comment]
@notpeter: I have added `option_as_meta: false` to the settings. Now I can enter the pipe and bracket symbols, which is good. But `meta+key` style actions (I have tried in `hx` editor) are not working anymore.

It's not the perfect solution, but it helps already a lot and makes the integrated terminal a lot more usable. Would be good though if both uses of the Alt/Option key would work.

**Comment by notpeter** [comment]
There is an active discussion about altering how we handle keybindings which you may find relevant:
- https://github.com/zed-industries/zed/discussions/17031
