### ISSUE TITLE
Remove always on args types suggestion that overlays params suggestions

### ISSUE THREAD

**Issue by zeptozor** [zed-industries/zed#16748]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

i have a function/object and whenever i try to write down its args, this big suggestion shows up and hides value suggestions (AND, NOT)
<img width="592" alt="Screenshot 2024-08-23 at 17 25 49" src="https://github.com/user-attachments/assets/d30e8439-561b-4622-bddc-a2e07c52e3b1">

how to disable this type suggestion on make it so, that it does not overlay value suggestions?

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Here are the relevant settings:

https://github.com/zed-industries/zed/blob/6841f7b9d792f6f89ca1b1bcbfca9dc763b66531/assets/settings/default.json#L134-L138

placing `"show_signature_help_after_edits": false` inside your local config will disable it popping up automatically.
You can still call it with cmd-i (`editor: show signature help`)
