### ISSUE TITLE
Zed window resize causes KDE Plasma (Wayland) desktop to completely freeze

### ISSUE THREAD

**Issue by saltrocks** [zed-industries/zed#16765]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Resizing the window causes the desktop to completely freeze to an irrecoverable state that requires a reboot.

### Environment

Zed Version: 0.149.5
Linux Distribution: CachyOS (based on Arch Linux, freeze occurs on regular unoptimized extra/zed package as well)
KDE Plasma Version: 6.1.4
Kernel: 6.10.6-3-cachyos
Graphics Platform: Wayland
NVIDIA Proprietary Driver Version: 560.35.03

**Comment by notpeter** [comment]
Your issue is older, but closing in favor of:
- https://github.com/zed-industries/zed/issues/17129

See [this comment](https://github.com/zed-industries/zed/issues/17129#issuecomment-2323473932):
> This is a bug with the Nvidia 560 drivers. Going back to the 555 drivers or running Zed with Xwayland, or using a compositor that doesn't support explicit sync, resolves the issue for me.

**Comment by kootoopas** [comment]
Resized window with hotkey (win-left) and got same freeze requiring reboot.
Only happens when editor is focused or when maximizing (win-up).

Zed: v0.168.2 (Zed)
OS: Linux Wayland arch unknown (Archlinux)
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GT 1030 || NVIDIA || 565.77
