### ISSUE TITLE
Can't show code completion when ctrl-space

### ISSUE THREAD

**Issue by XardoniK** [zed-industries/zed#16777]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi, I can't show code completions in .js or .astro files like you describe here: https://zed.dev/docs/completions
I tried default keymaps (no keymaps property in settings json) 

and I tried 
`[
  {
    "bindings": {
      "ctrl-space": "editor::ShowCompletions"
    }
  }
]`

and 

`[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-space": "editor::ShowCompletions"
    }
  }
]`

together with JetBrains keymaps.

When I clicked ctrl + space it doesn't show completions popup. I can only trigger completions by write eg `variable.`(it show completions for variable after dot sign) or by run command from command popup

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by zeptozor** [comment]
there already was the same issue
go to <code>System settings</code> <code>Keyboard</code> <code>Keyboard shortcuts...</code> <code>Input sources</code>, and remove the checkbox from <code>Select the previous input source</code>

**Comment by XardoniK** [comment]
Thank you so so much - it works!!!

**Comment by panaC** [comment]
Hello @zeptozor can you explain me how to access to this setting please, the completion doesn't work on my side, please.

**Comment by panaC** [comment]
I apply this setting, but it change nothing, i cannot have a showcompletion on js or whatever with ctrl+n or ctrl+space, if you have any idea, I take it.

**Comment by panaC** [comment]
I found the issue, the file must be saved on the disk to enable autocompletion, this is not an issue on majority of text editor.
