### ISSUE TITLE
404 dev toolchain

### ISSUE THREAD

**Issue by j2is** [zed-industries/zed#16785]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the link https://zed.dev/docs/developing-zed doesn't exist 

### Environment

none

### If applicable, add mockups / screenshots to help explain present your vision of the feature

-

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

-
</pre></details>

**Comment by maxdeviant** [comment]
This page moved to https://zed.dev/docs/development. I added a redirect there.
