### ISSUE TITLE
Disable Tab as accept inline completion 

### ISSUE THREAD

**Issue by snorreks** [zed-industries/zed#16799]
### Check for existing issues

- [X] Completed

### Describe the feature

I am coding in gdscript, similar to python. And for me to get into start coding in the screenshot below i have to use tab, but i don't want to accept the current inline completion. So the workaround now is to accept it and then delete all the code.

I would like to change the keybinding to something else, but from the [documentation](https://zed.dev/docs/key-bindings) I only see possibility to add custom keys and not to replace. 

![image](https://github.com/user-attachments/assets/3f221789-8e9a-49b5-a7e6-158d6e1f4abf)

**Comment by notpeter** [comment]
Here are the default keybinds (you can see than with `cmd-shift-p`, `open default keymap`): 

https://github.com/zed-industries/zed/blob/7969275ab1001db0a0cab1f82566a867616b7c67/assets/keymaps/default-macos.json#L474-L483

You can just rebind them to `"editor::Tab"` in your ~/.config/zed/keymap.json:
```json
 {
   "context": "Editor && showing_completions", 
   "bindings": { 
     "tab": "editor::Tab" 
   } 
 }, 
 { 
   "context": "Editor && inline_completion && !showing_completions", 
   "bindings": { 
     "tab": ""editor::Tab" 
   } 
 }, 
```

**Comment by snorreks** [comment]
Thanks I got it working now by:
1. ctrl-shift-p, open keymap
2. Add
```jsonrc
  {
    "context": "Editor && inline_completion && !showing_completions",
    "bindings": {
      "tab": "editor::Tab",
      "enter": "editor::AcceptInlineCompletion"
    }
  }
```

And you can replace "enter" with whatever key you want as the AcceptInlineCompletion.

**Comment by zoyron** [comment]
@snorreks I added your snippet, and following snippet. It is still not circling to next suggestion when I press Tab

`    "context": "Editor && (showing_code_actions || showing_completions)",
    "bindings": {
      "up": "editor::ContextMenuPrev",
      "tab": "editor::ContextMenuPrev",
      "down": "editor::ContextMenuNext",
      "tab-shift": "editor::ContextMenuNext"
    }
`
