### ISSUE TITLE
Missing chat scroll bar

### ISSUE THREAD

**Issue by kingwill101** [zed-industries/zed#16796]
### Check for existing issues

- [X] Completed

### Describe the feature

Chat panes should show a scroll bar when messages can't fit. While the current pane allows scrolling, it is very tedious having to scroll from where you left off.
![image](https://github.com/user-attachments/assets/722aec7c-3636-4fa9-a28c-c80bbb4d5238)

A +1 would allow jumping to the latest message once you send a message.

**Comment by bennetbo** [comment]
Hey, this is already getting tracked in #15324
