### ISSUE TITLE
"Please try again" error doesn't really make sense

### ISSUE THREAD

**Issue by bitfield** [zed-industries/zed#16795]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If I open a file with Zed that contains non-UTF-8 text (or, presumably, that triggers any other kind of `io::Error`), I get an alert that says:

"Failed to open file. stream did not contain valid UTF-8. Please try again."

Well, trying again won't help! I'm not sure this message really makes sense in this context; perhaps it would be better just to report the error's self-description ("stream did not contain valid UTF-8") as is.

Repro:
1. `echo '\x80' >test.txt`
2. `zed test.txt`

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 10.15.7
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-08-24 at 12 09 24](https://github.com/user-attachments/assets/184d03e0-745e-4cf2-a604-fb7219661f57)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Yeah, the error message is not the best.  We have a common error function which is used dozens of places where a retry might make sense (disconnects, time out, etc) but it obviously doesn't here.

- https://github.com/zed-industries/zed/blob/089014cb504e4b79ba1b537ad67bddeffbce16fa/crates/workspace/src/notifications.rs#L660

I appreciate you reporting but we're unlikely to refactor this so a single message is more appropriate at the moment.
