### ISSUE TITLE
Search key bindings in command palette

### ISSUE THREAD

**Issue by anddam** [zed-industries/zed#16793]
### Check for existing issues

- [X] Completed

### Describe the feature

Opening command palette shows command keybindings along with commands.
Typing characters fuzzy search commands, keybindings are not considered for match in the search.

I suggest the palette command should be able to fuzzy search keybindings too.

### If applicable, add mockups / screenshots to help present your vision of the feature

Mockup for `Ctrl + O` search, binding to `workspace::Open`

![zed-feature-request](https://github.com/user-attachments/assets/e1ec21a7-6bdc-4622-9fdb-1b473754ebb5)

**Comment by notpeter** [comment]
Duplicate of:
- #10910 

Feel free to add your mock as a comment on that issue. Thanks
