### ISSUE TITLE
Provide alternative login method (email/login code)

### ISSUE THREAD

**Issue by Bewinxed** [zed-industries/zed#16815]
### Check for existing issues

- [X] Completed

### Describe the feature

Github is blocked at work so anything that needs to sign to github i can only do using the login code and entering it on my phone.

would appreciate providing alternative methods like sign in with google/GitHub or using GitHub login code.

ty

**Comment by notpeter** [comment]
We currently only support GitHub for Zed authentication. In the future we may support alternate methods of login but for it's just GitHub. Sorry.
