### ISSUE TITLE
.doc / .docx files won't open in Zed

### ISSUE THREAD

**Issue by axoking** [zed-industries/zed#16826]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a .doc or .docx file in Zed, nothing happens. It does not open a new tab for the file or shows any kind of error message.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Zed does not support opening Microsoft Word Documents (doc or docx).
The lack of an error message is fixed by:
- https://github.com/zed-industries/zed/issues/5348

Which will be available in Zed Preview tomorrow and Zed Stable in a week.
