### ISSUE TITLE
Feature Request: Support for Drag and Drop Functionality

### ISSUE THREAD

**Issue by krabhi1** [zed-industries/zed#16830]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to request the addition of drag-and-drop functionality in the Zed editor. This feature would allow users to easily move files within the editor or between different sections of the interface by simply dragging and dropping them.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Peek 2024-08-28 15-14](https://github.com/user-attachments/assets/97aa4832-9167-4c7c-af49-30894519c053)

### System info
Zed: v0.149.5 (Zed)
OS: Linux X11 manjaro unknown
Memory: 7.7 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 4400 (HSW GT2) || Intel open-source Mesa driver || Mesa 24.1.6-arch1.1

**Comment by Chen1Plus** [comment]
See #4958

**Comment by krabhi1** [comment]
like dropping files from file explorer to zed

**Comment by apricotbucket28** [comment]
This should be fixed in 0.153 now that X11 drag and drop support got merged:
- https://github.com/zed-industries/zed/pull/17491

**Comment by Cre8or** [comment]
Confirmed! I can now drag and drop files out of Dolphin into Zed. Thank you! :heart:
