### ISSUE TITLE
How can I hide these AI assistants?

### ISSUE THREAD

**Issue by skhaz** [zed-industries/zed#16839]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="570" alt="Screenshot 2024-08-25 at 15 49 14" src="https://github.com/user-attachments/assets/cf1a14bb-5b47-43ec-9f50-cb50412ee99e">

Is there any config that I can disable completely AI features? I do not want them.

**Comment by SomeoneToIgnore** [comment]
By adding

https://github.com/zed-industries/zed/blob/a006a1845286eca3fd864d1cd6ad56acdaa81860/assets/settings/default.json#L391-L392

```json
"assistant": {
    "enabled": false,
}
```

into the settings.

Note that terminal panel has the same icon that does not go away yet, but https://github.com/zed-industries/zed/pull/16845 will fix that too.

**Comment by skhaz** [comment]
Nope, still on the interface.

**Comment by skhaz** [comment]
I completely understand that dealing with open-source projects is extremely stressful and thankless, but closing an issue with a vague response leaves users very frustrated.

If Zed wants to compete with editors like VS Code and JetBrains, it will have to work hard to provide good support.

That said, here is my setup.

Whenever Zed launches an AI feature, I'll come and complain in the issues, because I am personally very much against it.

Want to push AI in everyone's face? Fine, I'll go

```json
{
  "theme": "One Dark",
  "project_panel": {
    "dock": "right"
  },
  "languages": {
    "HTML": {
      "tab_size": 2
    }
  },
  "formatter": {
    "language_server": {
      "name": "biome"
    }
  },
  "lsp": {
    "biome": {
      "settings": {
        "require_config_file": true
      }
    }
  },
  "features": {
    "inline_completion_provider": "none"
  },
  "assistant": {
    "enabled": false,
  }
}
```
![Uploading Screenshot 2024-08-25 at 20.28.21.png…]()
 back to using vi.

**Comment by SomeoneToIgnore** [comment]
<img width="319" alt="image" src="https://github.com/user-attachments/assets/9365a886-22e5-450d-9a96-132ea64bd24d">

This shows that indeed, there has to be another field added.


```json
"assistant": {
  "enabled": false,
  "version": "2"
}
```

The one I stated was incorrect, I'll adjust that so other people can find it and use the correct settings.
