### ISSUE TITLE
ZBus ERROR: org..freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by Carson-yy** [zed-industries/zed#16865]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/user-attachments/assets/189e62a2-64e0-4d67-a6be-97cf1cd504c7)

**Comment by jansol** [comment]
https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Comment by Carson-yy** [comment]
> https://wiki.archlinux.org/title/XDG_Desktop_Portal

Thanks
