### ISSUE TITLE
how to select next suggestion using `tab` insteaf of `arrow keys`

### ISSUE THREAD

**Issue by Keith-amateur** [zed-industries/zed#16864]
### Check for existing issues

- [X] Completed

### Describe the feature

`tab` is used to accept the suggestion by default.
I wonder how to select next/previous suggestion using `tab`/`shift + tab`.
In VScode, I can change the following settings in `Keyboard Shortcuts`.
```
"acceptedSelectedSuggestion": Enter
"selectNextSuggestion": Tab
"selectPrevSuggestion": Shift + Tab
```

**Comment by Keith-amateur** [comment]
I tried the follwing configs in `keymap.json`. 
```json
  {
    "context": "Editor && (showing_code_actions || showing_completions)",
    "bindings": {
      "up": "editor::ContextMenuPrev",
      "tab-shift": "editor::ContextMenuPrev",
      "down": "editor::ContextMenuNext",
      "tab": "editor::ContextMenuNext",
      "pageup": "editor::ContextMenuFirst",
      "pagedown": "editor::ContextMenuLast"
    }
  }
```
It didn't work.
Are they `key bindings` which can't be overridden? (mentioned in https://zed.dev/docs/key-bindings#custom-key-bindings)

**Comment by CharlesChen0823** [comment]
try this [settings](https://github.com/zed-industries/zed/discussions/14621#discussioncomment-10069636)

**Comment by Keith-amateur** [comment]
> try this [settings](https://github.com/zed-industries/zed/discussions/14621#discussioncomment-10069636)

It works. Thank you!
