### ISSUE TITLE
Improve Gleam syntax highlighting

### ISSUE THREAD

**Issue by ghivert** [zed-industries/zed#16874]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi! I'm not sure where to talk about the subject, so I prefer open an issue. 🙂

Those days, I was trying to see if we can improve the syntax highlighting for Gleam.
Currently, in the syntax highlighting, we got all functions calls highlighted as records access when they're done in a fully qualified way.

```gleam
import my_package
pub fn main() {
  my_package.function() // <-- On Zed, this is highlighted as record property, and not function.
}
```

What do you think to modify the Gleam syntax highlighting (i.e. `highlights.scm`) to highlight every functions used from records with proper functions highlighting? [I tried to implement it here](https://github.com:ghivert/zed) to figure out how it can be. (I'm absolutely not sure it's correctly implemented, I mainly wanted to prove myself it was possible.) I also joined two screenshots on how it feels directly in the editor.

I know tree sitter can not know if the field is a function or not (because we can have a constant, so calling it will result in an error), but the LSP could take care of this, and — in my opinion — having a proper function highlighting for fields called as functions will improve readability.

### Function syntax highlighted
<img width="578" alt="Capture d’écran 2024-08-26 à 15 29 38" src="https://github.com/user-attachments/assets/f7590f35-525d-4743-8a17-692e5097014d">

### Record syntax highlighted
<img width="579" alt="Capture d’écran 2024-08-26 à 15 29 46" src="https://github.com/user-attachments/assets/1ffc9977-417b-4360-be84-0d01df359e28">

**Comment by JosephTLyons** [comment]
Hey @ghivert, we recently moved the `zed-gleam` repo to the Gleam org, so I went ahead and moved this issue over there. Had to do it manually, but here is the link:

- https://github.com/gleam-lang/zed-gleam/issues/4
