### ISSUE TITLE
vim: command add %y

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#16937]
### Check for existing issues

- [X] Completed

### Describe the feature

For full text copying, it's usually better to use `%y`, which requires fewer keystrokes (compared to `ggyG`) and, more importantly, won't change the cursor position.

**Comment by 0x2CA** [comment]
@ConradIrwin  #17448 

There's a bit of a problem, no copying prompt, and after copying, the mouse cursor didn't return to its original position.

I originally wanted to implement this function myself, and in the end, I also encountered these problems. I found that the reason is that the command's range defaults to modifying the mouse position and selecting the range, and then when copying, because it's in visual mode, the copy prompt animation won't play.

**Comment by ConradIrwin** [comment]
:+1: We can implement it more manually. I didn't think about the destination of the mouse when building the range abstraction. It does the same as nvim for `:delete`, but (as always) vim differs for `:yank`
