### ISSUE TITLE
Latest `@tailwindcss/language-server` (0.0.23) broken

### ISSUE THREAD

**Issue by EtienneLem** [zed-industries/zed#16946]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There are a lot of reports (https://github.com/tailwindlabs/tailwindcss-intellisense/issues) saying the latest Tailwind VS Code extension is broken, which also relies on `@tailwindcss/language-server` v0.0.23. The fix on VS Code is to use the previous extension version.

On Zed, the way I found to make it temporarily work is:
1. Change version in `~/Library/Application Support/Zed/languages/tailwindcss-language-server/package.json` to `0.0.22`
2. Run `npm install` in that directory
3. Run the `editor: restart language server` command in Zed

It will work until the app is restarted, where the broken v0.0.23 version will be used again, probably because of this line: https://github.com/zed-industries/zed/blob/2b08e2abe5278fab95bdd8cdcaf0daeeb6f336b7/crates/languages/src/tailwind.rs#L88

### Environment

Zed: v0.149.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Do you have a project example, where Zed breaks with the `v0.0.23` langserver version?

I have tried an internal project and did not notice any issues with autocompletion (as https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1039 states).
So, maybe the issue is not with the language server, but with the extension?

**Comment by EtienneLem** [comment]
The issue has been fixed on `@tailwindcss/language-server` and when launching Zed this morning the version is `0.0.24` and everything works as expected. Reading the commit that fixed the issue (https://github.com/tailwindlabs/tailwindcss-intellisense/commit/cb0992178b6a775270c7640974e51d11d94541ab), I think the one thing that was required to reproduce the bug was to have inline comments in a `.scss` file.

I do realize the issue wasn’t necessarily a Zed one per se, but such scenarios may happen again in the future where being able to lock these built-in LSPs to a specific version might be useful. In any case, we may consider this issue close for the time being 😄
