### ISSUE TITLE
Zed adds .s to my SQL files

### ISSUE THREAD

**Issue by axoking** [zed-industries/zed#16969]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Whenever I save a file a name it e.g. `test.sql`, zed saves it as `test.sql.s` without notifying me. I have no option to disable that behaviour. It doesn't matter wether I selected SQL syntax or not.

I thought that this is maybe an intended feature for auto-completing the filenames, but I found no setting for that kind of behaviour so maybe it's also a bug.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by versecafe** [comment]
@axoking  I can't seem to replicate this, was this happening on every sql file?

**Comment by axoking** [comment]
@versecafe yes it seems to happen with every sql file

**Comment by axoking** [comment]
OK edit

It seems like Zed always autocorrects my file endings. Like when I name a file `.txtx`, it becomes `.txtx.txt`. So it looks like Zed doesn't know the `.sql` ending and thinks I'm writing assembly because of the `s` so it corrects it to `.sql.s`. But I couldn't find neither a description of that feature nor how to disable it.

Is there a way to disable this or should I create a feature request issue for this?

**Comment by CharlesChen0823** [comment]
this is might not feature...., but I cannot reproduce.

**Comment by axoking** [comment]
https://github.com/user-attachments/assets/1e80f0e0-ce37-47f0-85e3-c408f5ff1df9

This is what happens. I'm sorry you can't reproduce it. Are you using mac for this?

**Comment by axoking** [comment]
https://github.com/user-attachments/assets/ff1677cf-b00d-4714-82bd-263f8f2a0bea

okkk edit here:
Zed is not the one to blame, that's a fucking Apple feature...
It does this in Apple's TextEdit, as well as in Sublime Text... Looks like whenever some app uses the Finder file dialog to save a file, macOS autocorrects it.

Could be a beta feature because I'm on Sequoia beta right now. I will look for an option to change this. Maybe you can also disable it when calling the file dialog in the application, idk if Apple thought about making that possible.

I'll try to check if it's beta only and if there's a way for me to disable it. Gonna write some feedback using that nice feedback assistant...

I guess that issue can be closed now.

**Comment by CharlesChen0823** [comment]
because I had seen another same issue.

**Comment by versecafe** [comment]
I would recommend creating files in zed through the CLI with touch, or zed ./file/path, or creating them through the editor to avoid macOSs file generation extension autocorrect in finder, windows has similar behaviour too with some files

**Comment by axoking** [comment]
Yes, I don't think Zed developers can do much here. Creating a file from the command line or by clicking New file in the sidebar works without problems, it's only when you use the Finder dialog to save something.

**Comment by breck7** [comment]
My goodness. Thanks everyone for posting about this issue. I thought I was going insane or something fucked with my machine.

It started happening right after I upgraded to Sequoia. 

https://forum.sublimetext.com/t/sublime-text-started-adding-a-s-to-new-files-very-annoying/73628/4

**Comment by breck7** [comment]
Shout out to @axoking for figuring out this was an Apple Sequoia bug!

**Comment by firecall** [comment]
Another test case:

Create a file called 'foo.html.haml' and macOS Sequoia will append .h to the file, resulting in 'foo.html.haml.h'.

**Comment by axoking** [comment]
Looking at https://news.ycombinator.com/item?id=41618926, it might also be a bug and not a feature. For me it looked like something that wouldn't  happen from a bug, but I have no idea how all the stuff works internally so it could also be unintended.

**Comment by breck7** [comment]
I'm sure Apple is aware of this, but I have filed my own report (https://feedbackassistant.apple.com/feedback/15301291), it doesnt seem like they have public bug reporting, but putting that link for my own future reference to keep an eye on this. If they update my issue, I'll report back here.

**Comment by daviehh** [comment]
also reported via feedback, looks like fix may be coming soon

<img width="517" alt="Screenshot 2024-10-07 at 16 17 46" src="https://github.com/user-attachments/assets/bc09ad66-b64d-44c6-9e4b-f31c6810475e">

**Comment by breck7** [comment]
I just checked, no updates to my issue from apple.

**Comment by ConradIrwin** [comment]
:( Ok. Super yucky workaround incoming: https://github.com/zed-industries/zed/pull/20195
