### ISSUE TITLE
Vim: `:s/search/replace/` substitution scope is global instead of local (current line)

### ISSUE THREAD

**Issue by kent0** [zed-industries/zed#16977]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `:s/search/replace/` substitution behavior is equivalent to `:%s/search/replace/` (global) while expected behavior is that of `:.s/search/replace/` (local, current line). The `:.s/search/replace/` pattern is verified to work in accordance to expectation.

### Environment

Zed: v0.150.4 (Zed Preview)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by 0x2CA** [comment]
Hi, this behavior is consistent with vscodevim and lazyvim
