### ISSUE TITLE
Quick search

### ISSUE THREAD

**Issue by AurevoirXavier** [zed-industries/zed#16994]
### Check for existing issues

- [X] Completed

### Describe the feature

As mentioned in https://github.com/zed-industries/zed/issues/16055. There is already a search box, we can reuse that UI I think.

Also, another relate issue is https://github.com/zed-industries/zed/issues/15896.

The quick search idea comes from the VSCode quick search.

### If applicable, add mockups / screenshots to help present your vision of the feature

Demo video: https://www.youtube.com/watch?v=pL7JKHcHcjs

**Comment by notpeter** [comment]
I've collected all of the different modes of the VSCode command palette as a comment under this issue so I'm going to close in favor of:
- https://github.com/zed-industries/zed/issues/15896

Thanks for reporting this, this was new to me.
