### ISSUE TITLE
Copy files/folders across projects

### ISSUE THREAD

**Issue by alex35mil** [zed-industries/zed#16995]
### Check for existing issues

- [X] Completed

### Describe the feature

When I copy files or folders in a file tree, these are scoped to the current project only, means I can't paste them into another opened project. It would be great to be able to copy/paste files across different projects.

**Comment by SomeoneToIgnore** [comment]
Closing as a duplicate of https://github.com/zed-industries/zed/issues/16741 if we're speaking of different windows here, or, otherwise, as solved with https://github.com/zed-industries/zed/pull/15396 if we're speaking of different worktrees in the same window.

**Comment by alex35mil** [comment]
@SomeoneToIgnore Just to double-check it's the same thing as #16741 - I'm having issues with coping stuff in file-tree only. I don't have issues with copying code as text.

**Comment by notpeter** [comment]
@alex35mil I think your issue is actually this one instead:
- https://github.com/zed-industries/zed/issues/11757
