### ISSUE TITLE
Configuring TypeScript with Yarn PnP in Zed Editor: Global vs. Local Settings

### ISSUE THREAD

**Issue by Brayan233** [zed-industries/zed#17046]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi everyone,

I’ve been trying to set up TypeScript with Yarn Plug'n'Play (PnP) in Zed following the steps outlined in the [official documentation](https://zed.dev/docs/languages/yarn). 

I configured the vtsls language server and set the TypeScript SDK path to the Yarn PnP SDK directory.

Here’s the configuration I added to my global settings (~/.config/zed/settings.json):

`{
  "lsp": {
    "vtsls": {
      "initialization_options": {
        "typescript": {
          "tsdk": ".yarn/sdks/typescript/lib"
        },
        "vtsls": {
          "autoUseWorkspaceTsdk": true
        }
      }
    }
  }
}
`

With this setup in the global config, everything works fine. However, it doesn't seem to work when I try to apply the same configuration in the local project settings (.zed/settings.json in my project folder). 

The language server doesn’t pick up the settings as expected.

Is this behavior normal? Are LSP configurations like these intended to work only at the editor (global) level, or is there something specific I’m missing to make them functional at the project level?

Any insights or suggestions would be really helpful. 

Thanks in advance!

### Environment

Zed: v0.150.4 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by baptisteArno** [comment]
Same issue, it looks like by default `autoUseWorkspaceTsdk` is set to true but when checking the logs, it does not use the sdk in workspace

**Comment by baptisteArno** [comment]
Right, same issue,

I confirm that logging `override_options` here:

https://github.com/baptisteArno/zed/blob/b41ddbd0184d285400e1378172a9db9f480f95e5/crates/languages/src/vtsls.rs#L270-L290

It prints what's in my global settings, but not in my workspace settings.

**Comment by ConradIrwin** [comment]
Fixed by https://github.com/zed-industries/zed/pull/17657

**Comment by XiNiHa** [comment]
Looks like https://github.com/zed-industries/zed/pull/17757 reverted the change. Can we have this back?

**Comment by Brayan233** [comment]
Was working, but as @XiNiHa mentioned, it's not working anymore...

Zed: v0.154.2 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: x86_64
