### ISSUE TITLE
Terminal, impossible to type \ antislash

### ISSUE THREAD

**Issue by rcarlier** [zed-industries/zed#17057]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello

I use Zed to prepare a postgresql course, and I use the terminal for many manipulations.

So I detected that I can't enter the `\` (antislash) character in the terminal, and I have to enter it in the editor and copy/paste it in terminal... Annoying to make a `\q` for example ;-)

If I am at the bash level (not in psql), successively pressing \ and \ makes an `ls`

I've check `settings>key bindings` and `settings>default key bindings` I didn't detect anything suspect (I didn't change the default values)

Of cours, i'ts possible to make a \ in the classic terminal, in the VSC terminal, and in other applications in general

### Environment

MacBook Air
MacOS  Sonoma 14.4.1 (23E224)

To obtain \ a need to use shift+option+/

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
In zed can you open the command palette (cmd-shift-p) and then 'copy system specs into clipboard' and edit your issue description to include that info (zed version number, etc).

What's your keyboard layout? (e.g. something other than US English?)

**Comment by rcarlier** [comment]
Of course

```
Zed: v0.147.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64
```
Keyboard : azerty, french (`com.apple.keylayout.French`)

**Comment by notpeter** [comment]
I think this might be relevant:
- https://github.com/zed-industries/zed/discussions/17031

**Comment by nexeck** [comment]
I am facing the same problem on MacOS.

\ / | and all those keys stopped working within the terminal.

Running some scripts which ask for user input are printing control chars/garbage into the input field (without typing anything) like:

Project name (lala): ]11;rgb:3b3b/4141/4d4d\
Sorry, ']11;rgb:3b3b/4141/4d4d\' is not a valid Project name: project names may only contain alphanumerics, hyphens, underscores, and periods

**Comment by martoche** [comment]
Same problem here with a French keyboard, I can't type the `[` character in the terminal with the usual `option-shift-(` key combination.

**Comment by rcarlier** [comment]
Try to add in `config/zed/settings.json`

```json
{
  "terminal": {
    "option_as_meta": false
  }
}
```

See issue https://github.com/zed-industries/zed/discussions/17031 for details...
