### ISSUE TITLE
Restore unsaved buffers when no projectis open

### ISSUE THREAD

**Issue by non-bin** [zed-industries/zed#17051]
### Check for existing issues

- [X] Completed

### Describe the feature

I often open a new window to quickly take notes, but my computer crashed and I lost my unsaved buffers.
Restoring unsaved files works when I have a folder open in the project panel, but not in a new empty window

Loving Zed so far, thank you <3

**Comment by SomeoneToIgnore** [comment]
Will close it as a duplicate of https://github.com/zed-industries/zed/issues/15098

**Comment by non-bin** [comment]
Thanks, sorry I didn't see it

**Comment by SomeoneToIgnore** [comment]
No worries at all, it's quite hard sometimes for differently named issues.
