### ISSUE TITLE
Verry slow start with huge git repo with running from cli

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#17080]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I clone this repo
https://github.com/truecharts/charts/
and then i cd in charts folder and do zed .

and it verry verry slow after one minute zed is not yet open and after it get kill because of memory usage

### Environment

Zed: v0.151.0 (Zed Preview)
OS: Linux Wayland bazzite 40
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA || 560.35.03

**Comment by osiewicz** [comment]
I can't repro it on Mac. Could you post your settings.json, logs and the list of installed extensions?

**Comment by yodatak** [comment]
For now i cannot reproduce so i close for now
