### ISSUE TITLE
Folder selector on ubuntu (x11) forces you to descend to a file

### ISSUE THREAD

**Issue by B-Lorentz** [zed-industries/zed#17096]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Any of the actions that use the system folder selector to select a folder
(such as "open project" or "install dev extension")
launch it in some improper mode, where clicking 'Open' will just descend into the given directory, instead of opening it as expected:
![image](https://github.com/user-attachments/assets/18d82225-b9b2-49e8-9d9b-a2f196f266cf)
After clicking the green open:
![image](https://github.com/user-attachments/assets/cd4deff6-ea28-4ff2-a04b-9ffb0f0f2eae)
Instead of the folder getting opened in zed.

The 'Open' only returns to Zed if you apply it to a regular file, which logs the following error:
```
2024-08-29T18:01:56.273124128+02:00 [ERROR] failed to load config.toml extension.toml

Caused by:
    Not a directory (os error 20)
```

This can be worked around by just running 'zed .' in the right folder, when trying to open a project, but it seems to prevent me altogether from using a dev extension

### Environment

Zed: v0.149.6 (Zed)
OS: Linux X11 ubuntu 20.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Quadro RTX 3000 || NVIDIA || 535.183.01

**Comment by B-Lorentz** [comment]
I've managed to reproduce with the following:
```rust
use ashpd::desktop::file_chooser::OpenFileRequest;
use gpui::*;

fn main() {
    App::new().run(|cx: &mut AppContext| {
        cx.spawn(|acx| async move {
            let request = OpenFileRequest::default()
                .modal(true)
                .title("test")
                .multiple(false)
                .directory(true)
                .send()
                .await
                .unwrap()
                .response();
            println!("{:?}", request)
        })
        .detach();
    });
}
```
under
```toml
[dependencies]
ashpd = "0.9.1"
gpui = { git = "https://github.com/zed-industries/zed.git", rev = "00eed768ce5cc72ac6af7e161e5324d77f28031f" }
```

So this is an ashpd bug.
I tried to check what ashpd does under the hood, I can see it ulimately ends up marshalling the message body using serde and zvariant to 'dbus'.
I guess it is somewhere in this process where the 'directory' flag gets lost (or when unmarshalling it on the other side)

**Comment by B-Lorentz** [comment]
It seems this is not a bug in zed or even in ashpd, I merely have an old version of gnome that doesn't support 'directory'.
However, other apps manage to use directory chooser, so there must be some other way

**Comment by apricotbucket28** [comment]
> However, other apps manage to use directory chooser, so there must be some other way

They're directly calling GTK APIs. However, that doesn't translate well to other desktops (e.g. KDE) and adds an unnecessary dependency on GTK 😕

Ubuntu 20.04 is generally also not very well supported by Zed (e.g. Mesa drivers are too old and Gnome is missing a lot of Wayland protocols and desktop portals)

**Comment by B-Lorentz** [comment]
@apricotbucket28 I see, thank you.
I guess I should just upgrade.
One thing I can think of, could there be a way to add a file-picker free way of installing a dev extension? Like a configuration field which is an array of paths on which dev extensions are expected to be found?
This could even be useful to people who might want to use multiple dev extensions all the time..

**Comment by just-an-engineer** [comment]
I'm on Wayland and I have the same issue. Other than that, same specs

**Comment by apricotbucket28** [comment]
Now that I remember, you can also enable the (basic) built-in Zed file picker in the settings:
```json
{
  "use_system_path_prompts": false,
}
```

That should allow you to open directories, though it won't use the system picker 🙂

**Comment by B-Lorentz** [comment]
That worked for me.
Feel free to close the issue

**Comment by just-an-engineer** [comment]
Does that just disable Zed from opening a GUI for navigating files? Because I could always add directories from manually typing out the path once I closed the GUI.
I don't think we should close the issue until it's actually fixed on Linux

**Comment by B-Lorentz** [comment]
@just-an-engineer The config flag uses a very spartan directory picker that's builtin to zed.
But I don't think they will be able to support all kind of old variants of linux, if the D-Bus interfaces just don't have the right options supported.
Though I guess it would be possible to autodiscover the capabilties, and switch to the builtin picker automatically

**Comment by just-an-engineer** [comment]
Yeah, that's fair. I can always try to mess with the code myself in the future at some point
