### ISSUE TITLE
rust-analyzer code completion not working after . or :

### ISSUE THREAD

**Issue by frederik-uni** [zed-industries/zed#17119]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't get any suggestions after . or :. this doesn't seem to be an issue with the lsp as the the trigger characters in rust are :.`(

### Environment

Zed: v0.151.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/e01d56cf-f6da-40c4-895c-af48ecd2bd6c

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by MolotovCherry** [comment]
I cannot reproduce this on 6403385. These are my details below details.

I'm on RA `rust-analyzer 0.3.2089-standalone (0f7f68dad 2024-08-27)`
```
Zed: v0.152.0 (Zed Dev 6403385468690754a1058e1fec80fd5e0501a69c)
OS: Windows 10.0.22631
Memory: 63.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU || NVIDIA || 560.94
```

**Comment by frederik-uni** [comment]
It seems to be a duplicate. I searched for rust-analyzer issues, bc taplo was working fine at the time. That stopped now, so I looked again and found #8766
