### ISSUE TITLE
Extensions: split themes out to different section from extensions

### ISSUE THREAD

**Issue by Cass67** [zed-industries/zed#17120]
### Check for existing issues

- [X] Completed

### Describe the feature

Id like to see Zed extension browser have sections related to just extensions relating to coding, parsing, linting etc in a different place to themes.  The themes are getting a little bit in the way when trying to browse whats available.. Maybe a little dropdown or checkbox to show extensions and/or themes at top of the page would do it.

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/zed-industries/zed/issues/9066
