### ISSUE TITLE
Keymap to move a tab left and right

### ISSUE THREAD

**Issue by paolodelfino** [zed-industries/zed#17134]
### Check for existing issues

- [X] Completed

### Describe the feature

As far as I seen there is no keymap to move a tab left or right though you can with the mouse. I mean editor files tabs and also for example terminal tabs

**Comment by lougreenwood** [comment]
@paolodelfino Great idea, I'd also add to this having the the ability to move a tab to adjacent panes in any direction, something like `pane::MoveBufferToPaneInDirection` which accepts the following args: `Left, Down, Up, Right`.

**_Sidenote_**: When I was thinking of what to name the `MoveBufferToPaneInDirection` command, it occurred to me that there doesn't seem to be a name used in Zed for the view which the tab holds. In vim we'd call this a `window`, or maybe (but incorrectly) a `buffer` (although technically in Vim we'd be moving the window containing the buffer).

**Comment by nt8r** [comment]
This is a duplicate of #14174.

**Comment by oioix** [comment]
It appears to be working now, but it’s either poorly or completely undocumented. 
After searching for a while, I finally figured out how to switch between tabs and, more importantly, how to access hidden tabs:

a) Scroll using the mouse wheel over the tab bar.
b) Swipe left/right on the trackpad (using two fingers) over the tab bar.
c) Mac keyboard shortcut: Option + Command + Left/Right Arrow keys

**It would be great to add this to the documentation!**
