### ISSUE TITLE
Keymap to toggle the terminal

### ISSUE THREAD

**Issue by paolodelfino** [zed-industries/zed#17135]
### Check for existing issues

- [X] Completed

### Describe the feature

As far as I've seen there is no keymap to toggle the terminal only one to toggle the focus, though you can do it clicking on the icon in the bottom bar

**Comment by SomeoneToIgnore** [comment]
Zed allows to toggle docks, one of which should contain the terminal pane.
Toggling that dock may be what you need?

![image](https://github.com/user-attachments/assets/4618f3fe-e1b0-42ba-b9a0-819da4d31525)

**Comment by paolodelfino** [comment]
Yes, thanks
