### ISSUE TITLE
Do not run ai generated commands automatically by default.

### ISSUE THREAD

**Issue by bilal-houari** [zed-industries/zed#17144]
### Check for existing issues

- [X] Completed

### Describe the feature

as of now, if I go to the terminal and use the ai inline assistant to generate a command, the command runs automatically once ENTER is pressed, the user can't see what the command is. I dont know if there is a setting to turn this off (which, I think, there should be), but I would argue that the default behavior is to be able to see the command before choosing whether to execute or not.

Thanks.

**Comment by bennetbo** [comment]
Can you clarify what you mean here? I'm able to see the command before I choose whether it should be executed or not.
In the video I spawn the inline assistant, then I type in my prompt and hit enter to start the generation. Once the LLM responds, I'm able to see the command that's about to be executed and can choose to either run it or discard it.

https://github.com/user-attachments/assets/84b0c308-c788-40c1-9768-1d7aa0a17f9f

**Comment by bilal-houari** [comment]
I'm on the latest stable release 0.150.4, this is the behavior on my machine. let me know if it's the intended behavior.

Thanks.
[video.webm](https://github.com/user-attachments/assets/797bea18-0298-4b8f-847f-4f4d4dbb33fb)
