### ISSUE TITLE
allow to pin tab

### ISSUE THREAD

**Issue by olegKusov** [zed-industries/zed#17169]
### Check for existing issues

- [X] Completed

### Describe the feature

VS Code allows to pin tab. It helps a lot to manage opened tabs by priority (when you want to close all tabs except pinned). I miss this feature a lot .

**Comment by Moshyfawn** [comment]
This has already been brought up, so I'm going to close this issue as a duplicate. Be sure to +👍 the other thread.

Duplicate of:
- #5046
