### ISSUE TITLE
Support vim count sections `[m` and `[[`

### ISSUE THREAD

**Issue by valentinewallace** [zed-industries/zed#17177]
### Check for existing issues

- [X] Completed

### Describe the feature

If you run `:help [m` and `:help [[`  in vim you can get more details on how it works.

**Comment by notpeter** [comment]
See: 
- [VimHelp: \[m](https://vimhelp.org/motion.txt.html#%5Dm)
- [VimHelp: \[\[](https://vimhelp.org/motion.txt.html#%5D%5D)

**Comment by valentinewallace** [comment]
I don't think I'll have time to work on this, but appreciate you looking into it! I'm interested in zed but I do use this vim command quite frequently..

**Comment by ConradIrwin** [comment]
This was implemented in #20924
