### ISSUE TITLE
Change of Zed icon for better visibility

### ISSUE THREAD

**Issue by jamesli2021** [zed-industries/zed#17187]
### Check for existing issues

- [X] Completed

### Describe the feature

I've lost count of how many times I've accidentally opened our old favorite IDE and VSCode instead of Zed. The visibility of Zed icon is not so prominent compare to other.

### If applicable, add mockups / screenshots to help present your vision of the feature

NA

**Comment by notpeter** [comment]
We're unlikely to change the design of our icon the near future.  Perhaps you'd find the the blue icon of [Zed Preview](https://zed.dev/releases/preview) more pleasing?
![image](https://github.com/user-attachments/assets/fe5f2f4d-6f72-4c8d-aad5-b713fec9663c)

**Comment by jamesli2021** [comment]
Still a little not visible for my vision, the desire could be a white background.

Zed come in 3 icons:
Default: The blue background
Dark: Black background
Light: White background
