### ISSUE TITLE
Button to apply Rust compiler suggestions

### ISSUE THREAD

**Issue by kurtbuilds** [zed-industries/zed#17213]
### Check for existing issues

- [X] Completed

### Describe the feature

rustc / rust-analyzer often give suggestions to fix code issues. Here's one example from adding cli args to a tauri application:

```
error[E0599]: no method named `cli` found for mutable reference `&mut tauri::App` in the current scope
  --> app/src-tauri/src/lib.rs:21:30
   |
21 |     if let Ok(matches) = app.cli().matches() {
   |                              ^^^ method not found in `&mut App`
   |
   = help: items from traits can only be used if the trait is in scope
help: trait `CliExt` which provides `cli` is implemented but not in scope; perhaps you want to import it
   |
1  + use tauri_plugin_cli::CliExt;
```

It'd be AMAZING for Zed to have a button to *apply* the suggested change to the file.

It might be out of scope, but I view it as analogous to Cursor's AI functionality of "apply" a diff generated by the AI - only in this case, it's a diff coming from the compiler/analyzer rather than the AI/LLM model.

**Comment by bbb651** [comment]
The suggestion is from rustc not rust-analyzer. Are your sure rust-analyzer is working? It doesn't have a cli interface, it implements the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (LSP), and Zed implements it as well on the client side, and it's entire point is giving you apply-able suggestions and refactors (code actions). It is a separate tool from rustc so the set of actions it supports might be different, but it can definitely import traits, if you go to that line do you see a small lighting bolt in the gutter? Or a blue squiggly underline in the code you can hover?

**Comment by kurtbuilds** [comment]
That's interesting... not sure if I missed it, or something about tauri was preventing the analyzer from doing its thing.

I'll close for now, re-open if I encounter. Thank you
