### ISSUE TITLE
support proxy for llm

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#17210]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="695" alt="image" src="https://github.com/user-attachments/assets/5c3f245a-e224-4c43-84e8-157fef42818e">

<img width="731" alt="image" src="https://github.com/user-attachments/assets/fa902cfc-629d-48e9-8097-80df672528d9">

### Environment

latest Zed

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Zed supports global proxy settings as shown in your first screenshot.  It should use that proxy for all outbound connectivity (include https requests to the zed.dev llm provider).  If there are portions of Zed which are not respecting that proxy setting, that is a bug.

The second screenshot is for our server-side code which runs the zed.dev provider that your assistant panel connects to (not the code that runs on your machine).
