### ISSUE TITLE
Zed terminal rendering issue

### ISSUE THREAD

**Issue by syscl** [zed-industries/zed#17221]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi zed team,

Thanks for bring such an amazing and lightweight editor, it is butter smooth and powerful.

During using of zed, I just noticed that the powerlevel10k theme seems to be a bit off for the triangle 
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/dd5dfeb4-193a-48ea-a43e-b8c5c7c54985">

Below is a screenshot from item and vscode terminal

<img width="655" alt="image" src="https://github.com/user-attachments/assets/1428293b-cce8-43b4-9928-bcaafc8ab322">

<img width="564" alt="image" src="https://github.com/user-attachments/assets/de1764c8-2505-4c0a-ac9b-104c32bc7724">

Thanks in advance,
syscl

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

screenshot attach above

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16826097/Zed.log)

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Looks like a duplicate of https://github.com/zed-industries/zed/issues/15927

**Comment by notpeter** [comment]
@syscl Can you try downloading and installing [IBM Plex Mono](https://github.com/IBM/plex/releases/tag/%40ibm%2Fplex-mono%401.0.0), restarting Zed and then adding the following to your settings to see if you get better results?

```json
  "terminal": {
    "font_family": "IBM Plex Mono",
    "line_height": "standard"
  }
```

If so, it's a duplicate of this:
- https://github.com/zed-industries/zed/issues/15542

**Comment by syscl** [comment]
@notpeter thanks for the suggestion, but does it mean I need to use another font to fix the issue?

**Comment by notpeter** [comment]
We are looking to migrate to vanilla "IBM Plex Mono" from "Zed Plex Mono" (a slightly customized version of IBM Plex Mono) because of some issues in our customized version.

I was hoping you could temporarily install IBM Plex Mono and see if like #15542, using the vanilla version of the font solved the issues.  If it's the same root cause (I think it is) the fix would come when we switch to IBM Plex Mono, but a workaround for the issue now might be just using IBM Plex Mono.

If that doesn't fix it, there's something else going on and I'd want to know about that too.

**Comment by syscl** [comment]
Thanks @notpeter didn't notice that. I am happy to try with the new font, but another concern is about what if developers change the font family (usually monospace).

**Comment by syscl** [comment]
@notpeter I tried with IBM Plex Mono, and noticed there's some nerd symbol missing,
<img width="295" alt="image" src="https://github.com/user-attachments/assets/0a08fed8-b05a-41c8-a394-b1dfeb0b7c34">

Usually, SF Mono + Nerd patch gave me this rendering
<img width="430" alt="image" src="https://github.com/user-attachments/assets/5944d612-63a1-4167-93f6-0d58186e94f4">

So maybe, with IBM Plex Mono, the patch still needs some patch for nerd symbols

**Comment by notpeter** [comment]
Yep. We don't currently include powerline/nerd symbols in the default font.

There is a patched version of IBM Plex Mono, [BlexMono Nerd Font Mono](https://www.nerdfonts.com/font-downloads) (install `BlexMonoNerdFontMono-{Regular,Bold,Italic,BoldItalic}.ttf`) which does include them.

Or you can use `font_fallbacks` if you have an alternate font with those glyphs that you can fallback to.  We're missing docs for `terminal.font_fallbacks` but it's the same idea as [`buffer_font_fallbacks`](https://zed.dev/docs/configuring-zed#buffer-font-fallbacks).

```json
  "terminal": {
//    "font_family": "BlexMono Nerd Font Mono",
    "font_family": "IBM Plex Mono",
    "font_fallbacks": ["FiraCode Nerd Fonts"],
    "line_height": "standard"
  },
```

Can you confirm this solves your rendering issue?

**Comment by syscl** [comment]
@notpeter thanks for this tips. This sounds a good idea, I currently used a patched mono font with powerline/nerd symbols. THis way I can keep minimal config change/overrides.

**Comment by notpeter** [comment]
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/15542

**Comment by ajbrown** [comment]
FYI for anyone else landing here, here is the terminal configuration that ended up working for me.  I'm using [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) in my powerlevel10k configuration
 
```json
  "terminal": {
    "font_family": "IBM Plex Mono",
    "font_fallbacks": ["MesloLGS NF"],
    "line_height": "standard"
  },
```
