### ISSUE TITLE
Waking up from suspend makes zed ui broken

### ISSUE THREAD

**Issue by gyongph** [zed-industries/zed#17237]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using ubuntu linux
Open your project folder in zed
then suspend the system
wake up the system 
log in
and then the zed ui is not working

### Environment

# System Details Report
---

## Report details
- **Date generated:**                              2024-09-01 21:53:47

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. PRIME B360M-A
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i3-8100 × 4
- **Graphics:**                                    NVIDIA GeForce GTX 1050 Ti
- **Disk Capacity:**                               128.0 GB

## Software Information:
- **Firmware Version:**                            3202
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.8.0-41-generic

**Comment by gyongph** [comment]
welp

**Comment by notpeter** [comment]
Perhaps related:
- https://github.com/zed-industries/zed/issues/12827
