### ISSUE TITLE
PHP doesn't have Inlay Hints

### ISSUE THREAD

**Issue by datgausaigon** [zed-industries/zed#17233]
### Check for existing issues

- [X] Completed

### Describe the feature

I see Inlay Hints are available and working well with languages ​​like Rust Lang, Type Script.

I work with PHP a lot and I really like the Inlay Hints feature for PHP on PHPStorm. Can you check if the miss of Inlay Hints for PHP is a bug? If not, can you add this feature?
If I have to configure how in setting.json file please guide.

No Toggle On/Off Inlay Hints for PHP screenshot

![Screenshot 2024-09-01 at 19 29 29](https://github.com/user-attachments/assets/015bbe40-b5b6-4954-97dc-c84379153da1)

### If applicable, add mockups / screenshots to help present your vision of the feature

Here is Inlay Hints for PHP from Jet Brains.
https://www.jetbrains.com/guide/java/tips/inlay-hints/

Thanks
🐻

**Comment by SomeoneToIgnore** [comment]
Also

> Here is Inlay Hints for PHP from Jet Brains.

JetBrains IDEs are not based on LSP and produce inlay hints based on their local implementations.
