### ISSUE TITLE
Scrolling doesn't work with trackpad and mouse wheel

### ISSUE THREAD

**Issue by mikysett** [zed-industries/zed#17230]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It's the second time scrolling doesn't work anymore with the mouse wheel and the track-pad, while keyboard navigation still works `properly.`
Relaunching the application fixes the issue.
I have Zed automatically launch at start-up, maybe that's a relevant info.

Thanks a lot for your hard work :smile: 

### Environment

Zed: v0.150.4 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 15.4 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 || NVIDIA || 535.183.01

**Comment by pushplay** [comment]
I'm having the same problem with scroll wheel and track pad not working.  Button presses work as expected.

OS: Kubuntu 24.04.1 LTS x86_64 
Host: Laptop (13th Gen Intel Core) A6 
Kernel: 6.8.0-39-generic 
Uptime: 48 days, 1 hour, 41 mins 
Packages: 2283 (dpkg), 18 (snap) 
Shell: fish 3.7.0 
Resolution: 2256x1504 
DE: Plasma 5.27.11 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: BeautyFolders [Plasma], BeautyFolders [GTK2/3] 
Terminal: yakuake 
CPU: 13th Gen Intel i7-1360P (16) @ 5.000GHz 
GPU: Intel Raptor Lake-P [Iris Xe Graphics] 
Memory: 9092MiB / 31803MiB

`[WARN] Unknown button press: ButtonPressEvent { .. }` in the log looks very relevant.

[Zed.log](https://github.com/user-attachments/files/16966322/Zed.log)

**Comment by supercraigmiller** [comment]
Similar/confirmation report from me, scroll wheel & trackpad scroll not working. Relaunch also doesn't work

Zed: v0.153.6
OS: Ubuntu 24.04.1
Host: Laptop  Lenovo Thinkpad X1 Carbon Gen 12
Kernel: 6.8.0-45-generic
Desktop: X11, Gnome 46.0-0
Memory: 64 GB
Architecture: x86_64
CPU: Intel Core Ultra 7 165U
GPU: Intel Corporation Meteor Lake-P [Intel Graphics] (rev 08)

In the log, I as well have a never ending amount of `[WARN] Unknown button press: ButtonPressEvent { .. }`

Log is from opening the editor, and attempting to scroll.

[Zed.log](https://github.com/user-attachments/files/17070512/Zed.log)

**Comment by jeff-finofo** [comment]
This is now working for me as of 0.155.2.

(Thanks so much!)

**Comment by mrnugget** [comment]
Great to hear! Closing this then.

**Comment by greenlaw110** [comment]
Mouse wheel not working on my 0.159.7

**Comment by mrnugget** [comment]
> Mouse wheel not working on my 0.159.7

did it work before? Is this a regression?

**Comment by pushplay** [comment]
It's still working for me on 0.159.10 (and every update since the fix).

**Comment by Sad-Abd** [comment]
Mouse wheel not working on my 0.162.5

**Comment by haykerman** [comment]
Mouse scrollwheel does not work for me on latest version. Pop!_OS 22.04

**Comment by darinkishore** [comment]
I still have this on macos!

**Comment by pietrom16** [comment]
Not working for me, either. Neither with an external USB mouse, nor with the trackpad.

Zed 0.198.2 
KUbuntu 25.04

**Comment by saroroce** [comment]
MacOS is here - 10 minutes and zed has scroll-lag

**Comment by bfmatei** [comment]
Using macOS + Apple Magic Trackpad results in very poor scrolling performance. No Mac Mouse Fix nor any other software installed.

It's the same on 60Hz as well as 144Hz.

Scrolling using the up/down keys seems to work fine.
