### ISSUE TITLE
[Linux] Alt+tab header overlap on window rendering

### ISSUE THREAD

**Issue by ppotara** [zed-industries/zed#17244]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First of all great work on Zed. I wanted to try it after seeing it was for OSX only.

The current issue with the attached video capture demonstrates the presented causes in which once `Alt+Tab` is pressed. Zed header loses its focus and the header presents an underlying application background.

Ideally, Zed should remain completely visible as long as another application isn't selected. 

### VID 1

We can see Chome application header visible while Zed application is still displayed.

https://github.com/user-attachments/assets/d470a204-6515-4552-91b4-db8293607f61

### VID 2

We can see VSCode header displayed while Zed is still focused as the primary application.

https://github.com/user-attachments/assets/7998ef13-d1d7-494b-a0aa-29ec2826da61

### VID 3

Is is also reproducible while application is reduced.

https://github.com/user-attachments/assets/faa826dc-4288-4e20-bcaf-d830dcfe2e43

 

### Environment

Zed: v0.150.4 (Zed)
OS: Linux Wayland ubuntu 22.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by apricotbucket28** [comment]
This is ultimately a theme issue but should be fixed in 0.151 (https://github.com/zed-industries/zed/pull/16833)

**Comment by ppotara** [comment]
> This is ultimately a theme issue but should be fixed in 0.151 (#16833)

@apricotbucket28 Thanks for the quick answer. I will close the issue as it looks to be fixed already on master.
