### ISSUE TITLE
Vim treesitter syntax motions should take a count

### ISSUE THREAD

**Issue by baffalop** [zed-industries/zed#17245]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm just starting to explore Zed and I'm quite excited! I just found out about the special treesitter syntax tree motions `]x` and `]x`, which are really cool! But one of the first things I tried with that is to give a count, eg. `3[x` or `[3x`. In the first, the count was ignored, and in the second, the `[` was ignored.

I would probably go with `[3x`, on analogy with things like `c3aB`: I would expect this to select the 3rd node up in the tree, ie. the equivalent of repeating `[x` 3 times. Perhaps `3[x` should be treated the same way.

**Comment by ConradIrwin** [comment]
:+1: If you'd like to pair with me on this: https://calendly.com/conradirwin/pairing
