### ISSUE TITLE
Autocomplete for ~/.config/zed/themes/*

### ISSUE THREAD

**Issue by thataboy** [zed-industries/zed#17251]
### Check for existing issues

- [X] Completed

### Describe the feature

While editing `experimental.theme_overrides` in `setting.json` we get autocomplete for theme keys and values

<img width="717" alt="Screenshot 2024-09-01 at 5 26 34 PM" src="https://github.com/user-attachments/assets/7400fb67-eb2a-47ef-8dda-4f9a3aa5ae22">

Yet when editing a theme directly inside `~/.zed/config/themes`, there's no such awareness. It would be nice to have autocompletion inside themes.

**Comment by notpeter** [comment]
Add this to your theme json and it should pickup the schema:
```
  "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
```
<img width="733" alt="Screenshot 2024-09-01 at 22 22 55" src="https://github.com/user-attachments/assets/3368e2bf-a159-4317-be1c-9b0d9f020df4">

We should probably add this to the built-in themes and encourage extension themes to include it too.
