### ISSUE TITLE
Support selecting intermediate directories in project panel with auto_fold_dirs true

### ISSUE THREAD

**Issue by gabwill10** [zed-industries/zed#17252]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am experiencing a problem when creating files and folders in the Zed editor. Here's the issue I'm encountering:

I create a folder (let's call it "folder1").
Inside "folder1", I create another folder ("subfolder2").
Inside "subfolder2", I create yet another folder ("subfolder3").
After these steps, the editor displays everything in a path format like folder1/subfolder2/subfolder3. However, I am unable to click on or select any folder other than "subfolder3". It seems like the editor is not allowing me to interact with the parent folders once a subfolder is created.

This behavior is making it difficult to manage my files and folders effectively. Could you please look into this issue?

![image](https://github.com/user-attachments/assets/3a67c57c-eb7c-4b4f-ac21-62f6c1975e99)

If you see the image, I can't select subfolder1 or folder1. I can't return to nodes.

### Environment

I'm running Zed 0.150.4
macOS 14.16.1 - Apple M1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/639310f4-d89d-4b15-a901-01fa39f57a28)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by gabwill10** [comment]
This issue is quite frustrating and significantly hinders my productivity because I have to create my folder structure through the terminal. This has caused me to switch back to using VSCode.

**Comment by notpeter** [comment]
Yep. As a workaround you can disable [Auto Fold Dirs](https://zed.dev/docs/configuring-zed#auto-fold-dirs) via your settings.json:
```
  "auto_fold_dirs": false,
```

**Comment by osiewicz** [comment]
I will look into this.
