### ISSUE TITLE
Using Zed as EDITOR for git rebase, commit, etc

### ISSUE THREAD

**Issue by dahankzter** [zed-industries/zed#17258]
### Check for existing issues

- [X] Completed

### Describe the feature

When I set `EDITOR=zed` in my env and issue a command like `git rebase -I` an empty document shows in zed and not the customary commit list that I want to rebase.
It would be very nice if I could switch to zed for at least my git operations but preferably all EDITOR operations.

**Comment by bitfield** [comment]
This is working for me, with `EDITOR` set to `zed --wait`.

**Comment by dahankzter** [comment]
I know I missed #5748 sorry about that.
