### ISSUE TITLE
Zed is Not Launching On Fedora Linux

### ISSUE THREAD

**Issue by IshanAsati** [zed-industries/zed#17256]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I open zed and then i can see it in the taskbar for like a split second then it crashes, I also cant launch with the terminal
I don't know how to recreate it tbh

### Environment

# System Details Report
---

## Report details
- **Date generated:**                              2024-09-02 11:07:59

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad Gaming 3 15ARH05
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 4600H with Radeon™ Graphics × 12
- **Graphics:**                                    AMD Radeon™ Graphics
- **Graphics 1:**                                  NVIDIA GeForce GTX 1650
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            FCCN21WW
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.10.6-200.fc40.x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/user-attachments/files/16832671/Zed.log)

**Comment by Rerum02** [comment]
As far as I can tell, Zed on Nvidia will only launch in x11 session.

**Comment by jacobwhall** [comment]
Same story as @ramipellumbi. When I run `zed --foreground`, I get the same output as [this comment](https://github.com/zed-industries/zed/issues/17129#issuecomment-2323265456). It looks like this issue has to do with a graphics driver update.

**Comment by ramipellumbi** [comment]
> Same story as @ramipellumbi. When I run `zed --foreground`, I get the same output as [this comment](https://github.com/zed-industries/zed/issues/17129#issuecomment-2323265456). It looks like this issue has to do with a graphics driver update.

From that same thread -- I am working around it for now via: https://github.com/zed-industries/zed/issues/17129#issuecomment-2323817322

**Comment by deng232** [comment]
happens to me today
wayland, with intel mesa driver.

**Comment by snapfast** [comment]
Not working on fedora ZED :(

**Comment by snapfast** [comment]
```
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1661:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1662:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1663:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1664:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1665:1: unrecognized keysym "dead_hamza" on left-hand side
wl_surface#22: error 0: DRM Syncobj surface object already created for surface 22
[2024-09-14T00:27:35+05:30 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Result::unwrap()` on an `Err` value: ERROR_SURFACE_LOST_KHR",
  "location_data": {
    "file": "/home/actions-runner/.cargo/git/checkouts/blade-b2bcd1de1cf7ab6a/e142a3a/blade-graphics/src/vulkan/init.rs",
    "line": 930
  },
  "backtrace": [
    "core::panicking::panic_fmt",
    "core::result::unwrap_failed",
    "blade_graphics::hal::init::<impl blade_graphics::hal::Context>::resize",
    "gpui::platform::blade::blade_renderer::BladeRenderer::new",
    "gpui::platform::linux::wayland::window::WaylandWindow::new",
    "<gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::platform::LinuxClient>::open_window",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::open_window",
    "gpui::window::Window::new",
    "workspace::Workspace::new_local::{{closure}}::{{closure}}",
    "async_task::raw::RawTask<F,T,S,M>::run",
    "<gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::platform::LinuxClient>::run",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::run",
    "gpui::app::App::run",
    "zed::main",
    "std::sys_common::backtrace::__rust_begin_short_backtrace",
    "std::rt::lang_start::{{closure}}",
    "std::rt::lang_start_internal",
    "main",
    "__libc_start_call_main",
    "__libc_start_main_alias_1",
    "_start"
  ],
  "app_version": "0.152.3",
  "release_channel": "Zed",
  "os_name": "Linux Wayland",
  "os_version": "fedora 40",
  "architecture": "x86_64",
  "panicked_on": 1726253855252,
  "installation_id": "56858ff5-4a92-4ea3-be00-44e094d9ca02",
  "session_id": "38a9dd39-f0e5-445b-82a4-a8f0546f53fb"
}


```

Error when running `zed --foreground`

**Comment by notpeter** [comment]
@IshanAsati Which version of the Nvidia driver are you using?

1. Running `export DRI_PRIME=1` before running `zed` from the command line (which will default to using your AMD CPU integrated graphics before launch)

2. Attempt to apply the NVidia kernel driver settings mentioned here (not sure exactly how to do this in Fedora, but it should be possible):
- https://github.com/zed-industries/zed/issues/17859#issuecomment-2357305247

**Comment by akseg73** [comment]
This issue still exists on Fedora 40, utilizing DRI_PRIME=1 does not help.  We have to be able to utilize the iGPU because the Nvidia GPU is occupied by the LLM ...

**Comment by akseg73** [comment]
Found it, to utilize iGPU you have to say DRI_PRIME=0 not 1 as is suggested by someone sel

**Comment by tobico** [comment]
I'm running into this same issue also. Running from the terminal after `export DRI_PRIME=1` functions as a workaround, but I have no idea how I'd make it work when launched normally, and I'd prefer not to have to launch GUI applications from the terminal.

**Comment by notpeter** [comment]
> I'm running into this same issue also. Running from the terminal after `export DRI_PRIME=1` functions as a workaround, but I have no idea how I'd make it work when launched normally, and I'd prefer not to have to launch GUI applications from the terminal.

You can edit the desktop shortcut to include that in the environment.  For example:
```sh
$ cat ~/.local/share/applications/dev.zed.Zed.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=Zed
GenericName=Text Editor
Comment=A high-performance, multiplayer code editor.
TryExec=/home/peter/.local/zed.app/libexec/zed-editor
StartupNotify=true
Exec=/home/peter/.local/zed.app/libexec/zed-editor %U
Icon=/home/peter/.local/zed.app/share/icons/hicolor/512x512/apps/zed.png
Categories=Utility;TextEditor;Development;IDE;
Keywords=zed;
MimeType=text/plain;application/x-zerosize;inode/directory;x-scheme-handler/zed;
Actions=NewWorkspace;

[Desktop Action NewWorkspace]
Exec=/home/peter/.local/zed.app/libexec/zed-editor --new %U
Name=Open a new workspace
```

Just edit the Exec line:
```
Exec=env DRI_PRIME=1 /home/peter/.local/zed.app/libexec/zed-editor %U
```
[reference](https://github.com/zed-industries/zed/issues/16863#issuecomment-2321922418)

**Comment by snapfast** [comment]
I really don't understand, they made a Code editor and it doesn't work on Linux. **What ? Why ?**

**Comment by tobico** [comment]
> Just edit the Exec line:
> 
> ```
> Exec=env DRI_PRIME=1 /home/peter/.local/zed.app/libexec/zed-editor %U
> ```

For anyone else facing this issue, I found that after editing my desktop file as described, I also had to run `sudo update-desktop-database` before Zed would launch correctly.

**Comment by SilenLoc** [comment]
For Fedora 40 users:
Going to Fedora 41 and switching to GNOME XOrg fixed it for me.

**Comment by notpeter** [comment]
@IshanAsati Have you been able to try the suggestions presented in this thread?

**Comment by IshanAsati** [comment]
Switching o fedora 41 worked

**Comment by tobico** [comment]
> For Fedora 40 users: Going to Fedora 41 and switching to GNOME XOrg fixed it for me.

Also seems to be working fine now with Fedora 41 on Wayland. No need to go back to Xorg.
