### ISSUE TITLE
Themes becoming transparent on Linux

### ISSUE THREAD

**Issue by RuanCampello** [zed-industries/zed#17263]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have noticed that some themes on Linux have become transparent, although I'm unsure when this issue started. This primarily affects light-coloured themes.

1. Dracula theme is entirely transparent.
2. Gleam Dark theme becomes transparent only when the window is unfocused or hovered.

![Captura de tela de 2024-09-02 09-28-50](https://github.com/user-attachments/assets/dc7f1e27-40ad-43af-9456-96295bfe4838)
> That's happening mainly with light or themes with light colours. As its visible above, in Dracula case, is totally transparent. 

[Gravação de tela de 02-09-2024 09:32:22.webm](https://github.com/user-attachments/assets/af4d37d8-b6e2-44f5-84e8-0e4c36fbb4d6)
> In Gleam Dark theme.

Steps to Reproduce:
- Install Zed Editor v0.150.4 on Linux.
- Apply a theme like Dracula or Gleam Dark.
- Observe the transparency issue in the editor.

### Environment

uname -a: 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

OS: Ubuntu 22.04.4 LTS
Shell: zsh 5.8.1 
Resolution: 1920x1080 
Disto: GNOME 42.9 
WM: Mutter 
WM Theme: Nordic-darker-v40 
CPU: Intel i3-10100F (8) @ 4.300GHz 
GPU: AMD ATI Radeon RX 6600/6600 XT

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
These are third party themes and I believe this is an issue with dracula/zed not with Zed:
- https://github.com/dracula/zed/issues/16

This was their suggested workaround:
```
"experimental.theme_overrides": {
    "background": "#282a36ff",
    "title_bar.background": "#141119ff",
    "title_bar.inactive_background": "#1c1d26ff",
    "status_bar.background": "#141119ff",
    "background.appearance": "opaque"
  },
```

If this is actually a Zed caused bug, not a misconfigured third-party theme please comment and I'm happy to reopen.

**Comment by Otterpocket** [comment]
it's a zed + linux issue. The theme requires that transparency to work with Blurred and Transparent themes.

**Comment by RuanCampello** [comment]
> If this is actually a Zed caused bug, not a misconfigured third-party theme please comment and I'm happy to reopen.

I don't think the problem is with the themes since they were working before. The issue started after a recent update (though I’m not sure exactly when).

**Comment by notpeter** [comment]
It looks like dracula has background transparency values set for background:
[<img width="472" alt="Screenshot 2024-09-03 at 11 24 56" src="https://github.com/user-attachments/assets/2a60a1eb-9f40-4737-8a3c-1e5e9b2c7c94">](https://github.com/dracula/zed/blob/c60784cf4d98d2e3e657218916e92196199d5b8a/themes/dracula.json#L16-L19)
Where as that's `ff` in all the default zed themes: 
https://github.com/zed-industries/zed/blob/122f01f9e5d6b2ba868cc75c9465e296a390507c/assets/themes/solarized/solarized.json#L16-L19

I wonder whether transparency was broken in Linux and we recently "fixed" it.

As a work around you can fork Dracula and put it under `~/.zed/themes/` or just override the values you don't want to be transparent via settings:
```
  "experimental.theme_overrides": {
    "surface.background": "#242631ff",
    "background": "#b597e0ff"
  }
```

**Comment by Otterpocket** [comment]
> It looks like dracula has background transparency values set for background: [<img alt="Screenshot 2024-09-03 at 11 24 56" width="472" src="https://private-user-images.githubusercontent.com/145113/364044922-2a60a1eb-9f40-4737-8a3c-1e5e9b2c7c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzkyNzQsIm5iZiI6MTcyNTQzODk3NCwicGF0aCI6Ii8xNDUxMTMvMzY0MDQ0OTIyLTJhNjBhMWViLTlmNDAtNDczNy04YTNjLTFlNWU5YjJjN2M5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwODM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWYxYzY1Yzg3ZjFmMTVjMzg5MGFkNWVmODk5YjhkMzg5MTc0Y2I3NjgyZWU1NDhkYTNhMGE0MTg5MjE4MGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UUnfzGryylK6N9BQw22EYf4MI5j_Z9R4VQCAyHm4hQ8">](https://github.com/dracula/zed/blob/c60784cf4d98d2e3e657218916e92196199d5b8a/themes/dracula.json#L16-L19) Where as that's `ff` in all the default zed themes:
> 
> https://github.com/zed-industries/zed/blob/122f01f9e5d6b2ba868cc75c9465e296a390507c/assets/themes/solarized/solarized.json#L16-L19
> 
> I wonder whether transparency was broken in Linux and we recently "fixed" it.
> 
> As a work around you can fork Dracula and put it under `~/.zed/themes/` or just override the values you don't want to be transparent via settings:
> 
> ```
>   "experimental.theme_overrides": {
>     "surface.background": "#242631ff",
>     "background": "#b597e0ff"
>   }
> ```

I'm the Dracula theme maintainer/creatotr btw.

It has to have that transparency for the transparent settings to work (which they do on Mac). The linux version of zed simply does not follow the rules of the transparency setting logic correctly.

The themes without transparency (which most of them don't) will simply do nothing when you turn on the transparency feature.

So it's obviously fine if you override those colour in the theme it just means if the Linux Version of Zed starts handling the transparency setting correctly it will no longer be transparent/blurred.

**Comment by AlexTLDR** [comment]
Regarding Dracula theme, I have created a [settings.json](https://github.com/AlexTLDR/zed-dracula-linux) config which solves the transparency issue.
