### ISSUE TITLE
Shortcut to open a file in project

### ISSUE THREAD

**Issue by paderick** [zed-industries/zed#17268]
### Check for existing issues

- [X] Completed

### Describe the feature

When a project is open, a shortcut (like e.g. Shift + command + O in Xcode for "Open Quickly" or the same in JetBrains IntelliJ) should help to find and open a file by name to save time and not need to navigate through the project navigator to find the file.

**Comment by notpeter** [comment]
Are you familiar with `cmd-p` / `ctrl-p` which toggles the file_finder?

Or are asking for an enhancement to the file finder to support arbitrary paths outside of the folders in the current workspace (e.g. `cmd-shift-p` and then `/` or `~/` etc)?

**Comment by paderick** [comment]
Hi @notpeter, no, this shortcut was new to me. But yes, I was looking for the "Go to file" / "file_finder" functionality. For me and I guess, for the most other users also, is it confusing to have a different keymap for the most used functions which is typically the same at the most IDEs.

**Comment by notpeter** [comment]
Our default keymaps try to match users expectation (mac or linux/win):
- VSCode (default): `cmd-p` or `ctrl-p` 
- Atom/Sublime/TextMate: `cmd-t` or `ctrl-t`
- JetBrains: `cmd-shift-o` or `ctrl-shift-n`)

Our default keymap uses `cmd-shift-o` for Outline::toggle, but you can remap if you'd like.  Just add the following to your ~/.zed/keymap.json (cmd-k, cmd-s).

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-shift-o": "file_finder::Toggle",
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-shift-o": "file_finder::Toggle"
    }
  }
]
```

There was some discussion 18months ago about adding an XCode compatibility keymap perhaps that should be revisited.
