### ISSUE TITLE
Vim mode repeat last command (.) doesn't appear to be repeating commands completely

### ISSUE THREAD

**Issue by TrevorHinesley** [zed-industries/zed#17308]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For the sake of simple reproduction, if you do exactly the commands listed in [@kconner's reply here](https://github.com/zed-industries/zed/issues/5930#issuecomment-1908719651), then it seems to be using stale register data. Here's the commands for quick reference:

> In many vim modes this command makes the difference to me between an OK experience and a great one. I will often move to a word, `*N` to load it into search and then focus it again, `ce` to replace the word, type, finish the edit, then `n.n.n.n.` to make the same edit wherever else I found it, sometimes skipping the `.` case by case.

For instance, at some point in this session I had copied the text `.png`, or it was placed into the default register through some means. After doing the commands listed above, which would normally replace subsequent instances with whatever I changed the word to, it's replacing with `.png` -- even if I specifically yank (`y`) other text in between.

### Environment

Zed: v0.150.4 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@TrevorHinesley I can't make it break as you describe, maybe I'm missing something:

* Yank "png" with `" a y i w`.
* Focus "width", then  `* N c e ctrl-r a` replaces the first "width" with "png". `n .` does the same.
* If I now yank "jpg" with `" a y i w` then `n .` then it replaces the final "width" with "jpg"

Would you mind typing out exactly the keys you're pressing to break it?

**Comment by TrevorHinesley** [comment]
Odd. This is also working for me now. For now, I'll close unless/until I can reproduce again. The only difference is I updated Zed last night to latest release via the in-app update dialog.
