### ISSUE TITLE
Vim registers don't seem to be working properly

### ISSUE THREAD

**Issue by TrevorHinesley** [zed-industries/zed#17306]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm seeing two particular quirks that I _believe_ might be related (hence the single issue):

1. If I highlight some text and use the command `"_d`, it should delete the text and drop it into the blackhole register (`_`), but it doesn't. If I then `p` or `CMD+v`, it pastes the deleted text, meaning it wasn't saved to the blackhole register but rather the default register.
2. I get the pinwheel of death for ~10 seconds sometimes if I do a replace-all in a file with the following series of commands: `/<search-term-here>`, `CMD+Shift+H` to pull up the replace input, input some replacement text, `CMD+Enter` to replace all. This is tough to reproduce, and I'll report back if I can figure out what's causing it, but it definitely happens. Important to note: I have had multiple windows open every time I've experienced this. Unsure if that's a red herring, but I thought it worth noting given that's caused issues with other things in the past, based on what I've seen in other unrelated Github issues.

### Environment

Zed: v0.150.4 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
I think they are likely separate issues. I know we landed some performance improvements to replace all in the last few weeks, but if that is still happening please let us know!

**Comment by TrevorHinesley** [comment]
I think the replace all issue I was referring to is this: https://github.com/zed-industries/zed/issues/17457
