### ISSUE TITLE
Consecutive opened files in current session

### ISSUE THREAD

**Issue by Ktoks** [zed-industries/zed#17312]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add consecutive opened files with Zed to be opened on the current session.
This is the behavior that VSCode and Neovim's Server have.

**Comment by notpeter** [comment]
What do you mean by "consecutive opened files"? Like if you select multiple files in the Project Panel and press `space` it opens all of them?

**Comment by Ktoks** [comment]
I mean - open one file in Zed - then some time later - open another file in Zed from Explorer, Commander, or WinSCP, etc... - and them all opening into the current session.

**Comment by notpeter** [comment]
Ah, duplicate of:
- https://github.com/zed-industries/zed/issues/9370
