### ISSUE TITLE
Custom Views in Extension API

### ISSUE THREAD

**Issue by breynard0** [zed-industries/zed#17325]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has the ability to embed custom views into the editor. This not allows the support of various file formats in the editor, but allows dedicated editors such as waveform viewers to be built directly into the app. I do not know the feasibility of this, but if the extension API could be expanded to allow developers to write custom views using GPUI, I feel the Zed ecosystem could benefit enormously from the feature.

**Comment by matubu** [comment]
I am not sure if its possible yet but I would be great if the Extension API also allowed to create side views like `debug: open syntax tree view`. For example it would allow the svelte extension to show the code and compiled code side by side like in vscode.

**Comment by singalen** [comment]
Would really love the ability to implement an IntelliJ-like git client view in Zed.

This is my personal blocker to move away from IntelliJ.
