### ISSUE TITLE
Support for Raspberry Pi 5 8GB running RPi OS

### ISSUE THREAD

**Issue by beingminimal** [zed-industries/zed#17336]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

You need RPi5 8GB with RPi OS installed into it.
Run `sudo rpi-update` command to upgrade rpi os
and then install zed and run it.
You will see attached image as popup showing incompatibility with rpi5 and rpi5 os.

### Environment

RPi5 8GB with RPi OS latest version

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![20240904_09h40m39s_grim](https://github.com/user-attachments/assets/92e9344b-e4a6-4c47-814c-6316cfdeb964)

![image](https://github.com/user-attachments/assets/3af98bb7-4429-494e-843a-df8ef152b599)

![20240904_15h52m55s_grim](https://github.com/user-attachments/assets/19db03ef-1814-4976-be5a-9a479c1005b2)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by beingminimal** [comment]
Please read important info here
https://discord.com/channels/869392257814519848/1204679850208657418/1280855649668038656

**Comment by notpeter** [comment]
Could you try the kisak PPA to see if that gets you a mesa that works?

```sh
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update && sudo apt upgrade
```

- For more, see: https://github.com/zed-industries/zed/issues/16428

**Comment by beingminimal** [comment]
> Could you try the kisak PPA to see if that gets you a mesa that works?
> 
> ```shell
> sudo add-apt-repository ppa:kisak/kisak-mesa
> sudo apt update && sudo apt upgrade
> ```
> 
> * For more, see: 
[Tracking Issue: Invisible Window on Linux  #16428](https://github.com/zed-industries/zed/issues/16428)

It shows like this. 
![20240904_20h01m11s_grim](https://github.com/user-attachments/assets/44964243-c44b-4627-a508-85a27d0623ee)

**Comment by notpeter** [comment]
```
sudo apt-get update
apt-get install software-properties-common
```
And then try again.

**Comment by margosall** [comment]
:heavy_check_mark: This fixes the issue Mesa 24.2.2 kisak-mesa is working nice and using GPU instead of CPU utilised 4 cores 100% :1st_place_medal:

**Comment by beingminimal** [comment]
> ```
> sudo apt-get update
> apt-get install software-properties-common
> ```
> 
> And then try again.

After running this command also, it's same. Please give solution, if possible.
![20240907_14h39m18s_grim](https://github.com/user-attachments/assets/8d656633-0359-415e-bca1-5fa3b41bb1c1)

**Comment by notpeter** [comment]
That command is so that the add-apt-repository works. You still have to run the original command which adds the ppa and installs the packages.

I've edited my original comment to include both. Please try that.

**Comment by beingminimal** [comment]
> That command is so that the add-apt-repository works. You still have to run the original command which adds the ppa and installs the packages.
> 
> I've edited my original comment to include both. Please try that.

Still it uses 100% CPU and not GPU. And same that unsupported GPU popup is also came.

![20240908_15h31m38s_grim](https://github.com/user-attachments/assets/1b427c7c-8537-40ce-9170-e7f45a916a42)
