### ISSUE TITLE
Debug and Run mode for Spring boot maven in Zed

### ISSUE THREAD

**Issue by developer-ivolve** [zed-industries/zed#17347]
### Check for existing issues

- [X] Completed

### Describe the feature

Debug and Run mode for Spring boot maven in Zed is required just like in vscode or intelliJ so that devs can run the application in debug mode.

**Comment by notpeter** [comment]
Zed does not support any debuggers yet, tracking issues are:
- https://github.com/zed-industries/zed/issues/5065 and
- https://github.com/zed-industries/zed/issues/5307
