### ISSUE TITLE
Highlight Files with Errors in Project Pannel for Flutter Projects

### ISSUE THREAD

**Issue by ZhiaDev** [zed-industries/zed#17340]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It is expected that when there is an error in one of the project files, the color of that file will change to red among the other files in the project panel or a sign will be shown on it to show that there is an error in that file.

Language and framework used: Dart (Flutter)

### how to reproduce:
open a basic flutter project
Make an error on purpose (such as remove a semicolon)

### Environment

Zed: v 0.150.4
OS: MacOS 14.6.1
Memory: 8 GiB
Architecture: arm64
GPU: Apple M1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1136" alt="Screenshot 2024-09-04 at 9 50 58 AM" src="https://github.com/user-attachments/assets/406b7dfd-439c-4d57-8fa4-4dd261ceb6a4">

**Comment by hoactp** [comment]
I think this is duplicated with [#5016](https://github.com/zed-industries/zed/issues/5016)
