### ISSUE TITLE
Rust analyzer type do not display

### ISSUE THREAD

**Issue by wiiznokes** [zed-industries/zed#17350]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a rust repo  (example https://github.com/pop-os/cosmic-osd)

The type do not display

### Environment

Zed: v0.151.1 (Zed Preview)
OS: Linux Wayland fedora 40
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 Ti || NVIDIA || 560.35.03

### If applicable, add mockups / screenshots to help explain present your vision of the feature

zed
![screenshot-2024-09-04-14-38-23](https://github.com/user-attachments/assets/73eb1264-f67c-44af-b0ca-020c33eefd19)
vscode
![screenshot-2024-09-04-14-37-57](https://github.com/user-attachments/assets/63aeb761-f47a-4320-bbd4-16091f43f38f)

**Comment by osiewicz** [comment]
You can enable inlay hints in the upper right hand corner:
![image](https://github.com/user-attachments/assets/9bd02863-cc10-4f5e-8b19-e377c1b101ad)

**Comment by KimdowEin** [comment]
Thanks.I think maybe we could turn it true by default ?

**Comment by SomeoneToIgnore** [comment]
One can make it a default by using

https://github.com/zed-industries/zed/blob/534475d7aa4d9fc925136b0fe174a867e3b610da/assets/settings/default.json#L536-L538

part of the default settings and changing `"enabled"` to `true`.
