### ISSUE TITLE
Focused symbol in Vue templates adds a background that is not theme-able

### ISSUE THREAD

**Issue by amsul** [zed-industries/zed#17361]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the caret is focused on a string symbol in any Vue template, all instances of that symbol end up with this background color that is illegible (in this theme):

<img width="358" alt="Screenshot 2024-09-04 at 1 05 55 PM" src="https://github.com/user-attachments/assets/fe068116-80d7-4203-9a98-8999dcc13846">

I've tried several attempts at theme overrides but nothing seems to target this highlight color directly.

### Environment

Zed: v0.151.1 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Moshyfawn** [comment]
What theme are you using?

**Comment by amsul** [comment]
@Moshyfawn Serendipity Midnight: https://github.com/meocoder31099/Serendipity-Theme-Zed

Is this something that is controllable by the theme? By my attempts, it didn't seem possible.

**Comment by meocoder31099** [comment]
> Is this something that is controllable by the theme? By my attempts, it didn't seem possible.

Yes, it is adjustable via theme.
