### ISSUE TITLE
Cannot enter pipe '|' in the integrated terminal

### ISSUE THREAD

**Issue by dwt** [zed-industries/zed#17393]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the terminal, I cannot enter a pipe symbol `|` into the terminal. I always get the 7 instead. (German keyboard layout).

1. Open the terminal (cmd-j)
2. enter a pipe by typing alt-7

While trying this out, I noticed that alt-ctrl-7 seems to enter the pipe symbol - a shortcut that is different to the rest of my system - as well as what I use to enter a pipe in the text editor part of zed.

### Environment

Zed: v0.150.4 (Zed)
OS: macOS 14.6.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
try [this](https://github.com/zed-industries/zed/issues/16581#issuecomment-2303999836)

**Comment by dwt** [comment]
Yes, that helps, so this is a duplicate of that bug.
