### ISSUE TITLE
URL's with `(` parenthesis should be clickable in the terminal

### ISSUE THREAD

**Issue by AlbertMarashi** [zed-industries/zed#17391]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/035cc110-2cab-435a-af55-c2c26e8d89a8)

Currently, URLs with parenthesis `(` `)` are not clickable in the terminal.

SvelteKit uses theses types of file routes to create layout groups. So this is quite annoying.

### Environment

N/A

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
See https://github.com/zed-industries/zed/pull/16724 as an example of a similar fix: the culprit is the url regex that does not capture enough symbols.
