### ISSUE TITLE
√独占配信*@JPN√ 日本 vs 中国ライブ ・放送・テレビ放送・生中継・生放送 2024年09月05日

### ISSUE THREAD

**Issue by zenzbd2** [zed-industries/zed#17405]
### Check for existing issues

- [X] Completed

### Describe the feature

【テレビ放送】サッカー日本代表 中国戦の地上波中継・ネット配信予定 2026年W杯アジア最終予選第1節
****

【サッカー日本代表 テレビ放送予定】ワールドカップアジア最終予選第1節、日本対中国のTV・ネット中継予定・視聴方法・試合日程・キックオフ時間まとめ。
【9月5日】サッカー日本代表 中国戦のテレビ放送・ネット配信予定｜FIFAワールドカップ26アジア最終予選【サッカー日本代表放送予定】9月5日開催のFIFAワールドカップ26アジア最終予選、日本代表(SAMURAI BLUE)対中国代表の日程・キックオフ時間・ライブ配信予定を紹介。
FIFAワールドカップ26アジア最終予選が2024年9月5日に開催され、日本代表(SAMURAI BLUE)と中国代表が対戦する。

▶【サッカー日本代表】中国戦はDAZNがライブ配信！9/13まで年間プラン(月々払い)が最初の3ヶ月・月々500円に割引

本記事では、日本対中国の試合日程、キックオフ時間、テレビ放送・ネット配信予定、視聴方法をまとめている。

日本vs中国｜試合日程・キックオフ時間
W杯アジア最終予選の日本対中国は、9月5日(木)に埼玉の「埼玉スタジアム2002」で開催される。

キックオフは19:35を予定している。

日本vs中国｜テレビ放送・ネット配信予定
W杯アジア最終予選、日本代表と中国代表の一戦はテレビは『テレビ朝日系列』、ネットは『 DAZN 』が中継、ライブ配信する。

SPOTV NOWやU-NEXT、ABEMA、BS/CS放送、その他ネットでの中継・配信はない。

2024年9月5日(木)に行われるFIFAワールドカップ26アジア最終予選（3次予選）で、日本代表(SAMURAI BLUE)が中国代表と対戦する。

▶【今だけお得】DAZN年間プランが最初の3ヶ月・月々500円に！9月13日まで限定
本記事では、日本vs中国の試合日程、キックオフ時間、テレビ放送予定を紹介していく。

日本vs中国 試合日程・キックオフ時間
日本代表vs中国代表は、9月5日(木)に埼玉の埼玉スタジアム2002で開催される。

大会：FIFAワールドカップ26アジア最終予選（3次予選）
日時：2024年9月5日(木) 19:35キックオフ
対戦：日本代表(SAMURAI BLUE) vs 中国代表
会場：埼玉スタジアム2002

**Comment by osiewicz** [comment]
This is spam advertising a Japanese TV channel.
