### ISSUE TITLE
vim-mode: Add Visual mode hard wrapping `g` `q`

### ISSUE THREAD

**Issue by jac-cbi** [zed-industries/zed#17434]
### Check for existing issues

- [X] Completed

### Describe the feature

In Vim, I can highlight a paragraph of text, say in a commit message or markdown file, and then enter the command `gq`, vim will automagically hard-wrap my lines to line-length. 

I didn't realize the feature was missing from Zed until I went to format a LaTeX doc... 

Running Zed 0.151.1 on macOS

**Comment by haasn** [comment]
Tangentially related, I feel like this is rather a limitation of existing LSP / formatters. Besides an explicit wrap command like in vim, I would expect to be able to select my lines and hit `=` to automatically format the chunk, joining and wrapping lines as needed.

In particular, there should be a "fallback" builtin formatter for buffers without an explicit LSP that is capable of such tasks. (As well as the ability to e.g. select subwords, words, sentences etc as syntax nodes.)

**Comment by kamoshi** [comment]
I feel like `gw` should be added too, it always reflows the lines and doesn't depend on `formatprg`/`formatexpr` in vim, so it is in fact the canonical way to do the hard wrapping. It also has a different behavior regarding the cursor position afterwards.

I would say adding this keybind is very important for seamless vim workflow.

**Comment by ConradIrwin** [comment]
gq/gw shpiped în v0.154.
