### ISSUE TITLE
Deno cannot find resolved dependencies

### ISSUE THREAD

**Issue by NetOpWibby** [zed-industries/zed#17441]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="784" alt="SS 2024-09-05 at 11 07 10 AM" src="https://github.com/user-attachments/assets/d3742fe7-4425-4f54-ba68-dfed614a738b">

I'm using the Deno extension so this is confusing.

### Environment

Zed: v0.151.1 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I think to use deno you'll want to disable the default language servers used for ts/tsx.

Can you try adding the following to your settings.json:

```json
{
  "languages": {
    "TypeScript": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ]
    },
    "TSX": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ]
    }
  }
}
```

**Comment by NetOpWibby** [comment]
I added these and nothing changed, unfortunately.

**Comment by sigmaSd** [comment]
You need to configure the lsp correctly see https://zed.dev/docs/languages/deno

**Comment by notpeter** [comment]
> I added these and nothing changed, unfortunately.

I believe what @sigmaSd is suggesting is that you also add the following to your settings:
```
  "lsp": {
    "deno": {
      "settings": {
        "deno": {
          "enable": true
        }
      }
    }
  },
```

This was recently added that to the docs in https://github.com/zed-industries/zed/pull/17579 (thanks @sigmaSd!)

**Comment by NetOpWibby** [comment]
@notpeter No, I had to had everything in @sigmaSd's link. Looks like it works now, thanks y'all!
