### ISSUE TITLE
Need inline_completion_provider support ollama

### ISSUE THREAD

**Issue by modeckrus** [zed-industries/zed#17451]
### Check for existing issues

- [X] Completed

### Describe the feature

Need suport inline_completion_provider in settings.json for ollama and local AI
example of settings.json 
```json
{
  "features": {
    "inline_completion_provider": "ollama"
  },
  "assistant": {
    "default_model": {
      "provider": "ollama",
      "model": "codegemma:latest"
    },
    "version": "2"
  }
}
```
So you can fully use only `local` AI

**Comment by notpeter** [comment]
Duplicate of:
- https://github.com/zed-industries/zed/issues/15968
