### ISSUE TITLE
Open a folder as a project by drag-and-drop the folder icon onto the Zed icon

### ISSUE THREAD

**Issue by quinncomendant** [zed-industries/zed#17470]
### Check for existing issues

- [X] Completed

### Describe the feature

This is expected behavior on macOS, but probably on Linux and Windows too: dragging a folder onto an application icon should open that folder in the application. Currently, dragging a folder to Zed on macOS does nothing.

I know there are some workarounds, such as using an automator script to feed the folder path to the zed CLI, but those don't work for me. Drag-and-drop to open a file by an application is a 1991 technology (from Macintosh System 7 :)

**Comment by SomeoneToIgnore** [comment]
> Currently, dragging a folder to Zed on macOS does nothing

Can you elaborate on that? Project example, reproduction steps description and/or video
Seems to work for me just fine:

1. Zed is not started and opens a new project on folder drop:


https://github.com/user-attachments/assets/a286b150-1e2c-41f9-9a0e-f3191894e16e


2. Zed is running already and opens a new project on folder drop:


https://github.com/user-attachments/assets/eb7fc37d-353d-4fee-b4a1-98ae62d8ae42

**Comment by quinncomendant** [comment]
@SomeoneToIgnore, you're correct, this works as expected.

I think the issue was that I had two copies of Zed installed (from an interrupted upgrade) and was dragging the folder onto the Zed icon that was not running. I'm closing this issue.
