### ISSUE TITLE
LM Studio offline model support

### ISSUE THREAD

**Issue by aaronhma** [zed-industries/zed#17482]
### Check for existing issues

- [ ] Completed

### Describe the feature

Add a section in the AI Models Configuration page to allow users to use a model from [LM Studio](https://lmstudio.ai/).

This has already been done before with https://github.com/zed-industries/zed/issues/4424. (image attached below)

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="628" alt="Ollama" src="https://github.com/user-attachments/assets/d1bd6976-d2b2-43db-9326-9bbdbb1c1f48">

**Comment by notpeter** [comment]
The LM Studio API only supports OpenAI, not the Ollama API, but it works just fine.

1. Start the server
<img width="213" alt="Screenshot 2024-09-06 at 12 29 48" src="https://github.com/user-attachments/assets/1efbb87f-08db-43dd-a538-bd5cbe398de0">

2. Add the following to your zed settings.json:

```json
  "language_models": {
    "openai": {
      "version": "1",
      "api_url": "http://localhost:1234/v1",
      "available_models": [
        {
          "provider": "openai",
          "name": "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
          "display_name": "LM Studio",
          "max_tokens": 2048
        }
      ]
    }
  },
```

3. Open the AI Assistant Configuration page and enter a random string into the OpenAI API key (e.g. `FAKEFAKE`), press enter and off you go.
<img width="616" alt="Screenshot 2024-09-06 at 12 26 03" src="https://github.com/user-attachments/assets/9de0aa20-7ca2-452c-9917-e52822b8b405">

We're unlikely to add explicit support for a proprietary llama distribution (see [LM Studio Terms of Use](https://lmstudio.ai/terms)) in-app, but it should work just fine.

**Comment by lavilao** [comment]
Just wanted to say that this method also works with llama.cpp-server.

**Comment by Qervas** [comment]
> Just wanted to say that this method also works with llama.cpp-server.

thanks so much. i just deployed my llama.cpp. Happy New Year

**Comment by lavilao** [comment]
> > Just wanted to say that this method also works with llama.cpp-server.
> 
> thanks so much. i just deployed my llama.cpp. Happy New Year

Happy new year!

**Comment by taranjlu** [comment]
@notpeter Hey, this worked for me, but if I try to run multiple models at the same time it seems to have an issue. In my scenario, I am running quen-2.5 and llama-3.2 and both are loaded on the LM Studio side (I am also able to chat with either, so they appear to be working). On the Zed side, I added another two entries based on your post, but I get an error: `Error interacting with language model` and the error pop-up actually lists the specific model it complained about not being able to load. If I disable/eject on of the models on the LM Studio side, then Zed will work correctly for that model. Any idea how I could get Zed to properly talk to either model when both are available?
