### ISSUE TITLE
[linux] Rejected for device extension "VK_KHR_dynamic_rendering" not supported. Please update the driver!

### ISSUE THREAD

**Issue by AndrewOt** [zed-industries/zed#17553]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I attempted top open the editor and am greeted with this
![image](https://github.com/user-attachments/assets/6068caf1-cc93-4f28-87eb-0e1867725ec3)

As you can see in the included logs, it has something to do with the `VK_KHR_dynamic_rendering` extension. I have double checked my environment and am not sure why it is not working because everything seems compatible according to the docs (but of course, I could be missing something :D I'm newish to Linux). In short, I have an NVIDIA GeForce RTX 2070 with the latest driver which includes the Vulkan 1.3.280 api (which is what the websites says you need) but I'm still getting the error.

I installed using the curl command on the website: `curl -f https://zed.dev/install.sh | sh`

### Environment

OS details:
NAME="Pop!_OS"
VERSION="22.04 LTS"

NVIDIA GeForce RTX 2070

<details><summary>vulkaninfo</summary><pre>
WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/x86_64-linux-gnu/libvulkan_virtio.so. Skipping this driver.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.280

Instance Extensions: count = 23
===============================
	VK_EXT_acquire_drm_display             : extension revision 1
	VK_EXT_acquire_xlib_display            : extension revision 1
	VK_EXT_debug_report                    : extension revision 9
	VK_EXT_debug_utils                     : extension revision 2
	VK_EXT_direct_mode_display             : extension revision 1
	VK_EXT_display_surface_counter         : extension revision 1
	VK_EXT_surface_maintenance1            : extension revision 1
	VK_EXT_swapchain_colorspace            : extension revision 4
	VK_KHR_device_group_creation           : extension revision 1
	VK_KHR_display                         : extension revision 23
	VK_KHR_external_fence_capabilities     : extension revision 1
	VK_KHR_external_memory_capabilities    : extension revision 1
	VK_KHR_external_semaphore_capabilities : extension revision 1
	VK_KHR_get_display_properties2         : extension revision 1
	VK_KHR_get_physical_device_properties2 : extension revision 2
	VK_KHR_get_surface_capabilities2       : extension revision 1
	VK_KHR_portability_enumeration         : extension revision 1
	VK_KHR_surface                         : extension revision 25
	VK_KHR_surface_protected_capabilities  : extension revision 1
	VK_KHR_wayland_surface                 : extension revision 6
	VK_KHR_xcb_surface                     : extension revision 6
	VK_KHR_xlib_surface                    : extension revision 6
	VK_LUNARG_direct_driver_loading        : extension revision 1

Layers: count = 8
=================
VK_LAYER_INTEL_nullhw (INTEL NULL HW) Vulkan version 1.1.73, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_MESA_device_select (Linux device selection layer) Vulkan version 1.3.211, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.3.211, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_NV_optimus (NVIDIA Optimus layer) Vulkan version 1.2.175, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_fossilize_32 (Steam Pipeline Caching Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_fossilize_64 (Steam Pipeline Caching Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_overlay_32 (Steam Overlay Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_overlay_64 (Steam Overlay Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (NVIDIA GeForce RTX 2070)
		Layer-Device Extensions: count = 0

		GPU id = 1 (llvmpipe (LLVM 15.0.7, 256 bits))
		Layer-Device Extensions: count = 0

... truncated for brevity

</pre></details>

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-07T21:04:04.819530654-05:00 [INFO] ========== starting zed ==========
2024-09-07T21:04:04.86803485-05:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-09-07T21:04:04.868107526-05:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-09-07T21:04:04.875322803-05:00 [INFO] Try connect ibus
2024-09-07T21:04:04.876036991-05:00 [INFO] perform;
2024-09-07T21:04:04.876074531-05:00 [INFO] authenticate;
2024-09-07T21:04:04.876139804-05:00 [INFO] read_command;
2024-09-07T21:04:04.876384512-05:00 [INFO] Opening main db
2024-09-07T21:04:04.876619011-05:00 [INFO] new;
2024-09-07T21:04:04.876664557-05:00 [INFO] socket reader;
2024-09-07T21:04:04.877291331-05:00 [INFO] keep_updated;
2024-09-07T21:04:04.883468272-05:00 [INFO] Using git binary path: None
2024-09-07T21:04:04.917783287-05:00 [ERROR] No such file or directory (os error 2) about ["/home/andrewottaviano/.config/github-copilot"]
2024-09-07T21:04:04.918075985-05:00 [INFO] initializing context server client
2024-09-07T21:04:04.918175682-05:00 [INFO] Registering built-in prompt template: content_prompt
2024-09-07T21:04:04.918487707-05:00 [INFO] Registering built-in prompt template: edit_workflow
2024-09-07T21:04:04.918841319-05:00 [INFO] Registering built-in prompt template: step_resolution
2024-09-07T21:04:04.919341606-05:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-09-07T21:04:04.919559765-05:00 [INFO] No prompt template overrides directory found at /home/andrewottaviano/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-09-07T21:04:04.934811517-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.934866881-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.934900694-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.934933996-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.935064381-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.936736213-05:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-09-07T21:04:04.936807466-05:00 [INFO] Opening main db
2024-09-07T21:04:04.942938181-05:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2024-09-07T21:04:04.943001089-05:00 [INFO] Creating colormap 41943043
2024-09-07T21:04:04.943095506-05:00 [INFO] perform;
2024-09-07T21:04:04.943138216-05:00 [INFO] authenticate;
2024-09-07T21:04:04.943196916-05:00 [INFO] read_command;
2024-09-07T21:04:04.943351576-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.943486298-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.94355137-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.943627032-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.943708294-05:00 [INFO] socket reader;
2024-09-07T21:04:04.943756865-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:04.980347342-05:00 [INFO] Enabling Vulkan Portability
2024-09-07T21:04:04.980393238-05:00 [INFO] Enabling color space support
2024-09-07T21:04:04.998711635-05:00 [INFO] Adapter: "NVIDIA GeForce RTX 2070"
2024-09-07T21:04:04.998812594-05:00 [WARN] Rejected for device extension "VK_KHR_dynamic_rendering" not supported. Please update the driver!
2024-09-07T21:04:04.998878658-05:00 [INFO] Adapter: "llvmpipe (LLVM 15.0.7, 256 bits)"
2024-09-07T21:04:04.999440951-05:00 [INFO] No ray tracing extensions are supported
2024-09-07T21:04:05.011786689-05:00 [INFO] Using surface present mode MAILBOX
2024-09-07T21:04:05.01190438-05:00 [WARN] Unable to forbid exclusive full screen
2024-09-07T21:04:05.012114574-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-07T21:04:05.012148587-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-07T21:04:05.012181729-05:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-09-07T21:04:05.079597143-05:00 [INFO] set environment variables from shell:/bin/bash, path:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.local/bin:/home/andrewottaviano/.nvm/versions/node/v22.4.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
2024-09-07T21:04:05.087102824-05:00 [INFO] Refreshing at 13334 micros
2024-09-07T21:04:05.088156007-05:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: true, device_name: "llvmpipe (LLVM 15.0.7, 256 bits)", driver_name: "llvmpipe", driver_info: "Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319 (LLVM 15.0.7)" }
2024-09-07T21:04:05.088866037-05:00 [INFO] XConnected server on 25165839, transport version: 0.0, TRANSPORT_MAX: 20
2024-09-07T21:04:05.157430042-05:00 [INFO] Using surface present mode MAILBOX
2024-09-07T21:04:05.157553844-05:00 [WARN] Unable to forbid exclusive full screen
2024-09-07T21:04:05.16504637-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:05.165173729-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:05.165222721-05:00 [INFO] rebuilt extension index in 517.78µs
2024-09-07T21:04:05.165280148-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:05.165943791-05:00 [ERROR] no worktrees when constructing ProjectLspAdapterDelegate
2024-09-07T21:04:05.167729717-05:00 [INFO] Opening main db
2024-09-07T21:04:05.228423529-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:05.28345874-05:00 [WARN] request completed with error: failed to connect to the server
2024-09-07T21:04:06.450087958-05:00 [INFO] Node runtime install_if_needed
2024-09-07T21:04:07.676797991-05:00 [WARN] Unknown request DestroyIcReply { input_method_id: 9, input_context_id: 48 }
2024-09-07T21:04:11.809577293-05:00 [INFO] starting language server. binary path: "/home/andrewottaviano/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/andrewottaviano/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-09-07T21:04:12.435533616-05:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-08T02:04:12.395Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-09-08T02:04:12.395Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-09-07T21:04:12.437079952-05:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "955b1094-ef33-4479-b65c-03485b953bda",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-09-07T21:04:12.487657913-05:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-08T02:04:12.441Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-09-08T02:04:12.441Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-09-07T21:04:13.455299645-05:00 [WARN] Unknown request DestroyIcReply { input_method_id: 9, input_context_id: 49 }
2024-09-07T21:04:28.546860184-05:00 [WARN] Unknown request DestroyIcReply { input_method_id: 9, input_context_id: 51 }
</pre></details>

**Comment by AndrewOt** [comment]
I also attempted to install from the Pop! shop (which I think is a snap package??) and got the same answer.

**Comment by AndrewOt** [comment]
Compiling from source also yielded the same result.

**Comment by notpeter** [comment]
Can you try what's suggested in this thread:
- https://github.com/zed-industries/zed/issues/15629#issuecomment-2277195893

**Comment by AndrewOt** [comment]
I set that to `off`
```
username@pop-os:~/.local$ cat /etc/prime-discrete
off
```

Error still persists.

**Comment by AndrewOt** [comment]
I didn't include the whole log out put from `vulkaninfo` above because it is very verbose. But here is the only place in the whole log it mentions the `VK_KHR_dynamic_rendering` extension:

> Device Extensions: count = 124
	VK_AMDX_shader_enqueue                        : extension revision 1
	VK_ARM_rasterization_order_attachment_access  : extension revision 1
	VK_EXT_4444_formats                           : extension revision 1
	VK_EXT_attachment_feedback_loop_dynamic_state : extension revision 1
	VK_EXT_attachment_feedback_loop_layout        : extension revision 2
	VK_EXT_border_color_swizzle                   : extension revision 1
	VK_EXT_calibrated_timestamps                  : extension revision 2
	VK_EXT_color_write_enable                     : extension revision 1
	VK_EXT_conditional_rendering                  : extension revision 2
	VK_EXT_custom_border_color                    : extension revision 12
	VK_EXT_depth_clip_control                     : extension revision 1
	VK_EXT_depth_clip_enable                      : extension revision 1
	VK_EXT_depth_range_unrestricted               : extension revision 1
	VK_EXT_descriptor_buffer                      : extension revision 1
	VK_EXT_descriptor_indexing                    : extension revision 2
	VK_EXT_dynamic_rendering_unused_attachments   : extension revision 1
	VK_EXT_extended_dynamic_state                 : extension revision 1
	VK_EXT_extended_dynamic_state2                : extension revision 1
	VK_EXT_extended_dynamic_state3                : extension revision 2
	VK_EXT_external_memory_host                   : extension revision 1
	VK_EXT_graphics_pipeline_library              : extension revision 1
	VK_EXT_host_image_copy                        : extension revision 1
	VK_EXT_host_query_reset                       : extension revision 1
	VK_EXT_image_2d_view_of_3d                    : extension revision 1
	VK_EXT_image_robustness                       : extension revision 1
	VK_EXT_image_sliced_view_of_3d                : extension revision 1
	VK_EXT_index_type_uint8                       : extension revision 1
	VK_EXT_inline_uniform_block                   : extension revision 1
	VK_EXT_line_rasterization                     : extension revision 1
	VK_EXT_load_store_op_none                     : extension revision 1
	VK_EXT_memory_budget                          : extension revision 1
	VK_EXT_memory_priority                        : extension revision 1
	VK_EXT_mesh_shader                            : extension revision 1
	VK_EXT_multi_draw                             : extension revision 1
	VK_EXT_multisampled_render_to_single_sampled  : extension revision 1
	VK_EXT_mutable_descriptor_type                : extension revision 1
	VK_EXT_nested_command_buffer                  : extension revision 1
	VK_EXT_non_seamless_cube_map                  : extension revision 1
	VK_EXT_pageable_device_local_memory           : extension revision 1
	VK_EXT_pipeline_creation_cache_control        : extension revision 3
	VK_EXT_pipeline_creation_feedback             : extension revision 1
	VK_EXT_post_depth_coverage                    : extension revision 1
	VK_EXT_primitive_topology_list_restart        : extension revision 1
	VK_EXT_primitives_generated_query             : extension revision 1
	VK_EXT_private_data                           : extension revision 1
	VK_EXT_provoking_vertex                       : extension revision 1
	VK_EXT_rasterization_order_attachment_access  : extension revision 1
	VK_EXT_robustness2                            : extension revision 1
	VK_EXT_sampler_filter_minmax                  : extension revision 2
	VK_EXT_scalar_block_layout                    : extension revision 1
	VK_EXT_separate_stencil_usage                 : extension revision 1
	VK_EXT_shader_atomic_float                    : extension revision 1
	VK_EXT_shader_atomic_float2                   : extension revision 1
	VK_EXT_shader_demote_to_helper_invocation     : extension revision 1
	VK_EXT_shader_object                          : extension revision 1
	VK_EXT_shader_stencil_export                  : extension revision 1
	VK_EXT_shader_subgroup_ballot                 : extension revision 1
	VK_EXT_shader_subgroup_vote                   : extension revision 1
	VK_EXT_shader_viewport_index_layer            : extension revision 1
	VK_EXT_subgroup_size_control                  : extension revision 2
	VK_EXT_texel_buffer_alignment                 : extension revision 1
	VK_EXT_transform_feedback                     : extension revision 1
	VK_EXT_vertex_attribute_divisor               : extension revision 3
	VK_EXT_vertex_input_dynamic_state             : extension revision 2
	VK_EXT_ycbcr_2plane_444_formats               : extension revision 1
	VK_EXT_ycbcr_image_arrays                     : extension revision 1
	VK_GOOGLE_decorate_string                     : extension revision 1
	VK_GOOGLE_hlsl_functionality1                 : extension revision 1
	VK_KHR_16bit_storage                          : extension revision 1
	VK_KHR_8bit_storage                           : extension revision 1
	VK_KHR_bind_memory2                           : extension revision 1
	VK_KHR_buffer_device_address                  : extension revision 1
	VK_KHR_copy_commands2                         : extension revision 1
	VK_KHR_create_renderpass2                     : extension revision 1
	VK_KHR_dedicated_allocation                   : extension revision 3
	VK_KHR_depth_stencil_resolve                  : extension revision 1
	VK_KHR_descriptor_update_template             : extension revision 1
	VK_KHR_device_group                           : extension revision 4
	VK_KHR_draw_indirect_count                    : extension revision 1
	VK_KHR_driver_properties                      : extension revision 1
	VK_KHR_dynamic_rendering                      : extension revision 1
	VK_KHR_external_fence                         : extension revision 1
	VK_KHR_external_memory                        : extension revision 1
	VK_KHR_external_memory_fd                     : extension revision 1
	VK_KHR_external_semaphore                     : extension revision 1
	VK_KHR_format_feature_flags2                  : extension revision 2
	VK_KHR_get_memory_requirements2               : extension revision 1
	VK_KHR_image_format_list                      : extension revision 1
	VK_KHR_imageless_framebuffer                  : extension revision 1
	VK_KHR_incremental_present                    : extension revision 2
	VK_KHR_maintenance1                           : extension revision 2
	VK_KHR_maintenance2                           : extension revision 1
	VK_KHR_maintenance3                           : extension revision 1
	VK_KHR_maintenance4                           : extension revision 2
	VK_KHR_maintenance5                           : extension revision 1
	VK_KHR_maintenance6                           : extension revision 1
	VK_KHR_map_memory2                            : extension revision 1
	VK_KHR_multiview                              : extension revision 1
	VK_KHR_pipeline_library                       : extension revision 1
	VK_KHR_push_descriptor                        : extension revision 2
	VK_KHR_relaxed_block_layout                   : extension revision 1
	VK_KHR_sampler_mirror_clamp_to_edge           : extension revision 3
	VK_KHR_sampler_ycbcr_conversion               : extension revision 14
	VK_KHR_separate_depth_stencil_layouts         : extension revision 1
	VK_KHR_shader_atomic_int64                    : extension revision 1
	VK_KHR_shader_clock                           : extension revision 1
	VK_KHR_shader_draw_parameters                 : extension revision 1
	VK_KHR_shader_float16_int8                    : extension revision 1
	VK_KHR_shader_float_controls                  : extension revision 4
	VK_KHR_shader_integer_dot_product             : extension revision 1
	VK_KHR_shader_non_semantic_info               : extension revision 1
	VK_KHR_shader_subgroup_extended_types         : extension revision 1
	VK_KHR_shader_terminate_invocation            : extension revision 1
	VK_KHR_spirv_1_4                              : extension revision 1
	VK_KHR_storage_buffer_storage_class           : extension revision 1
	VK_KHR_swapchain                              : extension revision 70
	VK_KHR_swapchain_mutable_format               : extension revision 1
	VK_KHR_synchronization2                       : extension revision 1
	VK_KHR_timeline_semaphore                     : extension revision 2
	VK_KHR_uniform_buffer_standard_layout         : extension revision 1
	VK_KHR_variable_pointers                      : extension revision 1
	VK_KHR_vulkan_memory_model                    : extension revision 3
	VK_KHR_zero_initialize_workgroup_memory       : extension revision 1
	VK_NV_device_generated_commands               : extension revision 3

I assume that the ":extension revision 1" means that it is enabled.

I would love it if someone could help me on this one because I'd love to try out Zed!

**Comment by AndrewOt** [comment]
Not sure if this is helpful, but just confirmed my nvidia driver version

<pre>+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.239.06   Driver Version: 470.239.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:0A:00.0  On |                  N/A |
|  9%   57C    P0    50W / 175W |    827MiB /  7974MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2741      G   /usr/lib/xorg/Xorg                435MiB |
|    0   N/A  N/A      2885      G   /usr/bin/gnome-shell              168MiB |
|    0   N/A  N/A     34142      G   ...c3e3b70b434329aaa71e1dc21      102MiB |
+-----------------------------------------------------------------------------+</pre>

**Comment by AndrewOt** [comment]
@notpeter I was doing some digging on this and it seems that people think moving from x11 to wayland might fix the issue (see https://github.com/pop-os/pop/issues/3336#issuecomment-2261567625). Does zed have to run on wayland? I am currently running x11.

```
user@pop-os:~$ loginctl
SESSION  UID USER SEAT  TTY 
      2 1000 user seat0 tty2

1 sessions listed.
user@pop-os:~$ loginctl show-session 2 -p Type
Type=x11
```

**Comment by AndrewOt** [comment]
@mrnugget do you have any ideas?

**Comment by notpeter** [comment]
> Does zed have to run on wayland? I am currently running x11.

We support running on either Wayland or X11.  The wild world of broken Linux video drivers (both outdated and on the bleeding edge) has meant that some users have had better luck using one or the other for their setup.  I have both working in my Linux setup but I have an old/boring single integrated Intel UHD Graphics 630 running on boring Ubuntu 22.

I did some digging and it looks like PopOS ships a version of Mesa ([24.0.3](https://apt.pop-os.org/release/pool/jammy/mesa/7a9f319c88f043e5878f717e3ea4b8d9db07834c/)) which is more up to date than vanilla Ubuntu 22.04 (`23.2.1-1ubuntu3.1~22.04.2`) but less up to date than Ubuntu 24.04 ([`24.0.9-0ubuntu0.1`](https://launchpad.net/ubuntu/noble/+package/mesa-vulkan-drivers)) or the [kisak-mesa ppa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) (`24.2.3~kisak1`) that others have reported success with.

Maybe give the kisak ppa a try?

**Comment by AndrewOt** [comment]
Yeah can confirm, this extension isn't enabled until Mesa [24.1](https://docs.mesa3d.org/relnotes/24.1.0.html). I'm running an older version:
```
vulkaninfo --summary

...
GPU1:
...
	driverName         = llvmpipe
	driverInfo         = Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319 (LLVM 15.0.7)
...
```

Guess I'm going to have to wait for the Pop!_OS team. Thank you @notpeter for investigating this!

**Comment by notpeter** [comment]
> Guess I'm going to have to wait for the Pop!_OS team. Thank you @notpeter for investigating this!

Did you try the kisak-mesa ppa?
I believe it should support PopOS as it's largely jammy compatible:

```
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt-get dist-upgrade
```

If it doesn't work you should be able to remove those packages and easily revert:
```
sudo apt install ppa-purge
sudo ppa-purge -d jammy ppa:kisak/kisak-mesa
sudo apt-get dist-upgrade
```

**Comment by k4ss4n** [comment]
I tried to reproduce this issue building from source following
https://github.com/zed-industries/zed/blob/main/docs/src/development/linux.md
using Pop!_OS 22.04 LTS with `Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319` and can run the editor without being shown this message on a RX6600.

The link to the Mesa 24.1.0 Release Notes only mentions "v3dv: enable VK_KHR_dynamic_rendering" which is, as far as I understand, related to Vulkan graphics driver for the Raspberry Pi 4 and Raspberry Pi 5 devices.

Posting for other people like me that are looking into the following vulkaninfo warnings on PopOS!, not necessarily related to zed:
`WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/x86_64-linux-gnu/libvulkan_virtio.so. Skipping this driver.
==========`

**Comment by AndrewOt** [comment]
@notpeter I don't see your comment here anymore but got the email notification, tried it and could get the new version installed properly (probably a skill issue haha).

@k4ss4n, that is interesting. I have an Nvidia RTX2070 card so I'm guessing it is something w/the proprietary drivers I have installed. They come pre-packaged in Pop and I guess you have to wait until they update the version bundled w/the OS.

**Comment by notpeter** [comment]
> @notpeter I don't see your comment here anymore but got the email notification, tried it and could get the new version installed properly (probably a skill issue haha).

Yeah, the comment was just instructions for how to install a newer mesa backported to Ubuntu 22 from the kisak ppa which other people have had success with.

I deleted it because it included some revert/uninstallation instructions which I hadn't tested and wasn't confident were correct/complete.

**Comment by k4ss4n** [comment]
@AndrewOt 
`WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.`
was the result of a faulty vulkan development environment on my end. After removing vulkan sdk, headers and tools it was possible to reinstall latest 1.3.290 release of the LunarG Vulkan SDK without problems. Can't tell the reason for this as I got a pretty much vanilla installation of Pop!OS with no extra source repos except for vscode and lunarg vulkan sdk.

**Comment by AndrewOt** [comment]
I got it working on my setup! I was able to upgrade my driver from `nvidia-driver-470` to `nvidia-driver-560` in the Pop!_Shop of all places! I should've checked sooner. In the screenshot below, you can see the install button next to the 470 driver, earlier it was next to the 560 driver and I clicked it, seems to be stable so far!
![image](https://github.com/user-attachments/assets/886b67bc-99bc-42b6-af37-4d5c18f762bb)

Thank you all who helped pitch in to help me problem solve this. Should've remembered to check the most obvious place first haha

**Comment by goldenratio** [comment]
is there any solution for nvidia driver 470.256.02? I have a legacy GPU (GT 755M).

**Comment by jonekdahl** [comment]
My problem was also solved by upgrading the nvidia driver (Pop!_OS 22.04 with an NVIDIA Quadro T2000 Mobile / Max-Q graphics card). 

For me, the drivers didn't appear in Pop!_Shop as mentioned [above](https://github.com/zed-industries/zed/issues/17553#issuecomment-2418420021) but tab completion gave me this list of options:

```
$ sudo apt install nvidia-driver-
nvidia-driver-390              nvidia-driver-465              nvidia-driver-525-open         nvidia-driver-550-server
nvidia-driver-418              nvidia-driver-470              nvidia-driver-525-server       nvidia-driver-550-server-open
nvidia-driver-418-server       nvidia-driver-470-server       nvidia-driver-530              nvidia-driver-555
nvidia-driver-430              nvidia-driver-495              nvidia-driver-530-open         nvidia-driver-560
nvidia-driver-435              nvidia-driver-510              nvidia-driver-535              nvidia-driver-565
nvidia-driver-440              nvidia-driver-510-server       nvidia-driver-535-open         nvidia-driver-565-open
nvidia-driver-440-server       nvidia-driver-515              nvidia-driver-535-server       nvidia-driver-565-server
nvidia-driver-450              nvidia-driver-515-open         nvidia-driver-535-server-open  nvidia-driver-565-server-open
nvidia-driver-450-server       nvidia-driver-515-server       nvidia-driver-545              nvidia-driver-570
nvidia-driver-455              nvidia-driver-520              nvidia-driver-545-open         nvidia-driver-570-open
nvidia-driver-460              nvidia-driver-520-open         nvidia-driver-550              nvidia-driver-570-server
nvidia-driver-460-server       nvidia-driver-525              nvidia-driver-550-open         nvidia-driver-570-server-open
```

After installing the latest version at the time (`nvidia-driver-570`), the "Unsupported GPU" message in Zed went away.
