### ISSUE TITLE
Suggestion: make "show_completions_on_input" default to true

### ISSUE THREAD

**Issue by mak448a** [zed-industries/zed#17555]
### Check for existing issues

- [X] Completed

### Describe the feature

Could you make the autocompletion work by default? VSCode does this by default, and it would be nice to have one less line to configure. Thank you!

**Comment by maan2003** [comment]
https://github.com/zed-industries/zed/blob/894866da9478003e77458e7a849353312d4c282c/assets/settings/default.json#L125-L127

it already defaults to true

**Comment by mak448a** [comment]
Oh, ok. They must've already changed it. It didn't used to be this way. Thank you!
