### ISSUE TITLE
LSP hangs after `workspace/workspaceFolders` request

### ISSUE THREAD

**Issue by rabbiveesh** [zed-industries/zed#17574]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am working on a zed extension for Perl, located at `https://github.com/tree-sitter-perl/zed-perl`.
I have set up [perlnavigator](https://github.com/bscan/PerlNavigator) to run as LSP either via being available on $PATH or to be installed from github releases.
However, it fails to actually do anything, b/c all of its functionality first does a check [here](https://github.com/bscan/PerlNavigator/blob/a02f86e1b18f619041ebcd5d4f7d4aaa6c8fa535/server/src/server.ts#L287) for the workspace folders. 

That request simply hangs and never returns. I can't imagine this is intended behavior; it's also not doing anything out of the ordinary (as far as I understand) in that it's using vscode's node LSP package.

From my foray in the zed sources, it looks like it tells hapless clients that it supports the workspaceFolders request, but reading zeds logs it just says it received an unhandled message when it gets a workspaceFolders request.

Any help would be appreciated b/c this is blocking perl support, and i'm running out of hair to pull out.

### Environment

Zed: v0.151.2 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by rabbiveesh** [comment]
Kinda makes me think of these lines https://github.com/zed-industries/zed/blob/dd257b8412c3c8005c710185dc8fc2eed3cc67ba/crates/project/src/lsp_store.rs#L4777-L4779

Perhaps empty handling for the `workspace/workspaceFolders` request should be implemented?

**Comment by osiewicz** [comment]
Yep, you're onto something; also, we declare support for workspace folder in https://github.com/zed-industries/zed/blob/56bc3c36ad1140562c4ded64536c65f17e0d173f/crates/lsp/src/lsp.rs#L552
I think it's a bit ambiguous in the spec whether this relates to the `workspaceFolders` field in client initialization params or the request.

I'll implement support for this request. Should be pretty straightforward.

**Comment by rabbiveesh** [comment]
ya, the original title of this ticket reflected that line in `lsp.rs`; i changed the tone after i had time to cool down :smile:

**Comment by osiewicz** [comment]
I merged a PR that adds support for workspace/workspaceFolders. Can you give current main a shot?

**Comment by osiewicz** [comment]
This should be going into stable today I think.
