### ISSUE TITLE
"Middle click paste" on Linux followed by a "left click" is being recognized as a "double left click"

### ISSUE THREAD

**Issue by wdiasjunior** [zed-industries/zed#17573]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"Middle click paste" on Linux immediately followed by a "left click" is being recognized as a "double left click" and selects the text instead of changing cursor position.

### Environment

Zed: v0.150.4 (Zed)
OS: Linux X11 arch unknown
Memory: 30.7 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.1-arch1.1

**Comment by caramboleyo-no2fa** [comment]
now middle mouse paste is not working at all, "middle_click_paste": true setting has no effect.
Is it possible this fix broke it?

v0.155.2 on ubuntu 24.04

**Comment by wdiasjunior** [comment]
can confirm, middle click paste stopped working even with  `"middle_click_paste": true`, and the original issue still persists.  

v0.155.2
