### ISSUE TITLE
Improve wavy underline appearance

### ISSUE THREAD

**Issue by ncor** [zed-industries/zed#17595]
### Check for existing issues

- [X] Completed

### Describe the feature

I slightly changed (#17586) the fragment shader of wavy underline so that it looks like the usual one:
![image](https://github.com/user-attachments/assets/2e7fd479-8144-43af-b656-3b93dedae5aa)

I would also suggest increasing the underline depending on the size of the text so that it remains proportional to it.

**Comment by notpeter** [comment]
Apologies for my ignorance, but what makes this more "correct" than the existing squiggles?

<img width="586" alt="Screenshot 2024-09-17 at 10 18 48" src="https://github.com/user-attachments/assets/4a8548f9-e802-4e2c-a235-0bc34542813f">

Can you show the before/after improvement?

**Comment by ncor** [comment]
> Apologies for my ignorance, but what makes this more "correct" than the existing squiggles?
> 
> <img alt="Screenshot 2024-09-17 at 10 18 48" width="586" src="https://private-user-images.githubusercontent.com/145113/368205064-4a8548f9-e802-4e2c-a235-0bc34542813f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTM4NzYsIm5iZiI6MTcyNjYxMzU3NiwicGF0aCI6Ii8xNDUxMTMvMzY4MjA1MDY0LTRhODU0OGY5LWU4MDItNGUyYy1hMjM1LTBiYzM0NTQyODEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QyMjUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjFmMWM5ZmNmNDQ0MmU3NGQ5NzFjY2M0NWE0ODYyODU4ZjUxMmViNmIzMWRmZDA1MzE1YjlkYzE3NGFmYWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.19HUsXxA8gDUxXXzNwfs456iJjL5_WVkCDEYbJdjmb0">
> Can you show the before/after improvement?

Sure.

**Before:**
![image](https://github.com/user-attachments/assets/7c176cf4-7138-4be0-9394-cb1355b998ab)

**After:**
![image](https://github.com/user-attachments/assets/13519c6b-a171-4833-a2bc-6904f3b57999)

The line doesn't clip and has an optimal frequency in relation to the average font size, which is usually 14pt.

**Comment by gabdumal** [comment]
This is indeed a good feature. There could be at least an option to change between long and short style.

**Comment by ncor** [comment]
> This is indeed a good feature. There could be at least an option to change between long and short style.

Agreed. But now it's more important to make it work with different scales. The underlines are displayed at the same scale every time, only the width changes.

![image](https://github.com/user-attachments/assets/7aee2c86-9a29-46d6-9fbb-1733e89e16bc)
_(my version of the shader acts the same way)_
