### ISSUE TITLE
Crash when hovering on methods with markdown definition lists

### ISSUE THREAD

**Issue by M1kep** [zed-industries/zed#17607]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When hovering over some python methods, such as `fixture` on `@pytest.fixture` the markdown changes from https://github.com/zed-industries/zed/pull/17418 trigger a crash due to definition lists being unimplemented.

I'm not entirely sure how to create a markdown that specifically trigger this, but it can be reproduced via:

```
python -m venv ./.venv
```
Setup pyrightconfig.json
```
{
  "venvPath": "<path_to_folder>",
  "venv": ".venv"
}
```
Create a conftest.py
```
import pytest

@pytest.fixture
def test()
...
```

Hover on `.fixture`, triggers crash.

### Environment

Zed: v0.153.0 (Zed Nightly c92a49e7aea41d125f7cddcdd00d2fa98184e935)
OS: macOS 14.6.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-09T10:27:41.200602-07:00 [ERROR] {
  "thread": "<unnamed>",
  "payload": "not implemented: definition lists are not yet supported",
  "location_data": {
    "file": "crates/markdown/src/parser.rs",
    "line": 323
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys_common::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "<markdown::parser::MarkdownTag as core::convert::From<pulldown_cmark::Tag>>::from",
    "markdown::parser::parse_markdown",
    "<markdown::Markdown>::parse::{closure#0}",
    "<async_task::raw::RawTask<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<markdown::ParsedMarkdown, anyhow::Error>> + core::marker::Send>>, core::result::Result<markdown::ParsedMarkdown, anyhow::Error>, <gpui::executor::BackgroundExecutor>::spawn_internal<core::result::Result<markdown::ParsedMarkdown, anyhow::Error>>::{closure#0}, ()>>::run",
    "_pthread_mach_thread_np"
  ],
  "app_version": "0.153.0",
  "release_channel": "Zed Nightly",
  "os_name": "macOS",
  "os_version": "14.6.1",
  "architecture": "aarch64",
  "panicked_on": 1725902861200,
  "installation_id": "80fb8d24-f9cb-440b-a64a-8633eaf03660",
  "session_id": "cbdeb994-7bc4-409d-95c0-8d3d699eaa36"
}
</pre></details>

**Comment by rowillia** [comment]
Confirmed that reverting back to `e1a865295bb86371e0551b3327d1a3a571d8b289` fixes the crash.  I tried reverting `b54d1aa95e1f37893cf13b4a827023cf5b0d44e6` but encountered other crashes afterwards.
