### ISSUE TITLE
[bug]: VulkanError(ERROR_INITIALIZATION_FAILED). See https://zed.dev/docs/linux for troubleshooting steps. 

### ISSUE THREAD

**Issue by Thecode764** [zed-industries/zed#17626]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi 

i checked for existing issues but i can't find how to fix?

okay i use parch linux (an arch-based linux distribution created by iranians) okay my error is

VulkanError(ERROR_INITIALIZATION_FAILED). See https://zed.dev/docs/linux for troubleshooting steps. 

### Environment

OS: Parch Linux x86_64 
Laptop: Asus tuf gaming
 Kernel: 6.10.1-arch1-1 
CPU: 11th Gen Intel i5-11400H (12) @ 4.500GHz 
 GPU: Intel TigerLake-H GT1 [UHD Graphics] 
 GPU: NVIDIA GeForce RTX 3050 Mobile 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

i dont have any screenshot

### If applicable, attach your Zed.log file to this issue.

...

**Comment by jansol** [comment]
Make sure you have the `vulkan-icd-loader`, `nvidia` and `vulkan-intel` packages installed. (Having only one of `nvidia` and `vulkan-intel` should be fine if you know you never want to use the other GPU, but the ICD loader is important to have in any case)

**Comment by Thecode764** [comment]
@jansol my new error: VulkanLoadingError(LibraryLoadFailure(DlOpen { desc: "/usr/lib/libvulkan.so.1: file too short" })). See https://zed.dev/docs/linux for troubleshooting steps.

**Comment by Thecode764** [comment]
@jansol how to fix?

paru -S vulkan-icd-loader?

**Comment by jansol** [comment]
No idea, I'm not familiar with that distro. Try reinstalling (and make sure it *actually* reinstalls) the relevant packages and report a bug to the distro if it's still broken.

**Comment by Thecode764** [comment]
i migrated to kubuntu 

fixed
