### ISSUE TITLE
Windows: cannot save the new file buffer

### ISSUE THREAD

**Issue by xgfone** [zed-industries/zed#17622]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open Zed.
2. Click `Ctrl+N` to new a file buffer.
3. Input some characters.
4. Click `Ctrl+S` to save the file.
5. Show an argument error.

### Environment

Zed: v0.153.0 (Zed Dev f71cb14d7a3c876b1a5a69949a5a198ed3bfbd5a)
OS: Windows 10.0.22631
Memory: 15.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/0e9f91d1-9c0a-4b69-b77c-3be23b437cac)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16938381/Zed.log)

</pre></details>

**Comment by xgfone** [comment]
Open the exist file, update the file buffer and Click `Ctrl+S`, it's OK. But for the new file buffer, it does not work.

**Comment by xgfone** [comment]
I deleted the folder `~/AppData/Local/Zed`, and re-open `Zed`. When saving a new file buffer, a `Save As` explorer window is opened, but both Zed and the explorer window are hung.

[Zed.log](https://github.com/user-attachments/files/16956813/Zed.log)

**Comment by xgfone** [comment]
After starting `Zed`, open `Zed.log` and find that there are errors:
```
2024-09-12T10:58:04.0049802+08:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-09-12T10:58:04.1293565+08:00 [ERROR] No composite alpha flag for transparency: OPAQUE | INHERIT
```

[Zed.log](https://github.com/user-attachments/files/16972741/Zed.log)

**Comment by xgfone** [comment]
I built `Zed` on main branch 25b6e43b0f8faf3b24b4ab4ee02456d3933539ce, the trouble still exists. But, after applying the patch #17708 , it is solved. @dovakin0007 

If opening chinese input method, such as pinyin or wubi, both `Zed` and the explorer dialog window will hang. It may be another issue.

**Comment by dovakin0007** [comment]
> I built `Zed` on main branch 25b6e43b0f8faf3b24b4ab4ee02456d3933539ce, the trouble still exists. But, after applying the patch #17708 , it is solved. @dovakin0007 
> 
> 
> 
> If opening chinese input method, such as pinyin or wubi, both `Zed` and the explorer dialog window will hang. It may be another issue.

Let me try that then thank you

**Comment by xgfone** [comment]
hi, no any progress ??

**Comment by xgfone** [comment]
On Windows, Zed cannot save the new file buffer as a new file. However, PR #17708 maybe fix it. May the PR be merged to the main branch?

**Comment by xgfone** [comment]
Because Zed team does not support Windows officially, I build the main branch everyday as the nightly version to try the new features.
