### ISSUE TITLE
[BUG] Image File is Not Updating

### ISSUE THREAD

**Issue by Tahinli** [zed-industries/zed#17640]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you open an image inside Zed. Even if you change the image but keep it same name. Zed shows old image. I think you're doing some kind of caching this prevents image file to reopen.

### Environment

Fedora 40 KDE

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Duplicate of:
- #11529

**Comment by Tahinli** [comment]
sorry
