### ISSUE TITLE
Impossible to save YML files without Zed messing up my double quotes

### ISSUE THREAD

**Issue by armchairdj** [zed-industries/zed#17649]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My project uses double quoted strings in YML files. Example:

```
en:
  errors:
    messages:
      contains_url: "cannot contain a url"
```

But Zed is currently too stupid to understand that preference making it impossible for me to get work done in Zed in Rails without constantly swtiching to another editor every time I open a yml file.

Zed configured like this:

```
  "lsp": {
    "yaml-language-server": {
      "initialization_options": {
        "yaml": {
          "format": {
            "singleQuote": false
          }
        }
      }
    }
  }
```

But every time I save a YML file, Zed tries to convert every double quoted string to a single quoted string. Apostrophes within those double quoted strings hopelessly confused Zed, so it's not every single line that gets edited.

Seems like my only current recourse is to completely disable any kind of lint-on-save behavior globally.

Please help.

### Environment

Zed: v0.149.6 (Zed)
OS: macOS 13.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi @armchairdj. 

The settings key for this has moved from `initialization_options` to `settings`.
You should be able to just rename that key and things should just work.

https://zed.dev/docs/languages/yaml will be updated once #18081 has merged.

Thanks!

**Comment by SomeoneToIgnore** [comment]
Another attempt to debug this:

I do not see any prettier-related config overrides in the settings posted above, and we do allow prettier for yaml:
https://github.com/zed-industries/zed/blob/2ff8dde925b75d62f030755843cd93c402a41022/assets/settings/default.json#L921-L925

and have prettier enabled as a default formatter: 

https://github.com/zed-industries/zed/blob/2ff8dde925b75d62f030755843cd93c402a41022/assets/settings/default.json#L531-L534

So most probably, it's not at all related to language servers, but the prettier config?

Interesting enough, that my version of prettier formatter does the opposite, replacing single quotes with the double ones:

https://github.com/user-attachments/assets/b82988f4-d5fb-4ac9-81be-65d210d23ff3

So just to be sure, I'd first open the LSP logs (`debug: open language server logs` command, my video has it on the left) and ensured that there's no prettier/biome/etc. formatter in the dropdown there and indeed the formatting goes through LSP.
I suspect it does not, and then we can consider configuring it:
```json
"prettier": {
    "allowed": true,
    "singleQuote": false
  },
```

Maybe it's some other LSP server that spoils it, then it has to be configured somehow.
