### ISSUE TITLE
Go 1.23 : Code completion/navigation does not work using

### ISSUE THREAD

**Issue by eko** [zed-industries/zed#17664]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using a `go.mod` file containing `go 1.23` directive, the code completion and navigation stop working in Zed.

When I type `go 1.22` in the `go.mod` file (instead of 1.23), it does work.

### Environment

macOS Sonoma 14.6.1
Go 1.23.1 installed

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Simple `go.mod` file:

```
module github.com/eko/test-zed

go 1.23
```

and a really simple Hello world example:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello world")
}
```

**Comment by bestgopher** [comment]
Please check your gopls version.  
`ls ~/Library/Application\ Support/Zed/languages/gopls/`

Gopls must be newer than [v0.16.0](https://github.com/golang/tools/releases/tag/gopls%2Fv0.16.0).

**Comment by eko** [comment]
Hi @bestgopher, you're right, I was on version v0.15.2. I just upgraded to v0.16.2 and it works properly :-)

Thank you! I close this issue.
