### ISSUE TITLE
Release Notes: Duplicate and outdated entries due to reverted/superceded PR

### ISSUE THREAD

**Issue by MrSubidubi** [zed-industries/zed#17669]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the release notes for [Zed Stable 0.152.3](https://zed.dev/releases/stable/0.152.3) and [Zed Preview 0.152.0](https://zed.dev/releases/preview/0.152.0), there are outdated and duplicate entries in the "Languages" - section due to a reverted PR.

[PR 16747](https://github.com/zed-industries/zed/pull/16747) introduced the following changes (and entries):
- Add `@variable.parameter` highlight scope
- Add `@attribute highlight` scope
- Add markdown injection inside `doc_comment` s

However, it was reverted in #17073 due to panics caused by the markdown insertions.

#17097 superseded the first pull request, removing the markdown-insertions from the previous PR, and introduced the release note:
-  Improved Rust syntax highlighting queries.

In both release notes for the aforementioned Stable and Preview, the note on the added markdown injections is still present despite being reverted. Futhermore, the "other" release notes from both PRs refer to the same changes, so the notes from one PR should be removed.

### Environment

~

**Comment by Moshyfawn** [comment]
The GitHub release notes have been updated, but the site will probably be up to date with the next release.
