### ISSUE TITLE
One of the problems of this editor To work on large projects, Golang is unable to index libraries well

### ISSUE THREAD

**Issue by mrbardia72** [zed-industries/zed#17686]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

One of the problems of this editor
To work on large projects, Golang is unable to index libraries well

### Environment

One of the problems of this editor
To work on large projects, Golang is unable to index libraries well

### If applicable, add mockups / screenshots to help explain present your vision of the feature

One of the problems of this editor
To work on large projects, Golang is unable to index libraries well

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bestgopher** [comment]
You need provide more useful messages.  Zed uses gopls as language server of golang, and your projects can be indexed well by other editors( vscode, etc)?

**Comment by mrbardia72** [comment]
Yes, they are indexed by other editors. Does this editor have a configuration to index better?

**Comment by bestgopher** [comment]
I haven't encountered your issue, and I don't have any specific configurations. My project has over a million lines of code.  You may check if gopls version matches your go version. https://github.com/zed-industries/zed/issues/17664#issuecomment-2342973537

**Comment by mrbardia72** [comment]
thank you

**Comment by notpeter** [comment]
@mrbardia72 Was this fixed by upgrading your version of `gopls`? (should this issue be closed)
