### ISSUE TITLE
keep_alive setting is ignored when talking to ollama

### ISSUE THREAD

**Issue by graelo** [zed-industries/zed#17688]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi, 

I observed that whatever `keep_alive` value I set in my settings file [(string or int)](https://github.com/zed-industries/zed/blob/ec189fe884f48109d17ca3f2984c49c933b46253/crates/ollama/src/ollama.rs#L45), my choice does not get sent to the server. I checked this by inspecting the http request received, and at the moment, `keep_alive = -1` is sent independently of my settings.

I'm almost certain my setting is correct because I can change the `max_tokens` value (sibling of keep_alive) and its value gets reflected in the UI.

```json
  "language_models": {
    "ollama": {
      "api_url": "http://myllama",
      "low_speed_timeout_in_seconds": 120,
      "available_models": [
        {
          "provider": "ollama",
          "name": "mistral-nemo:12b-instruct-2407-q5_K_M",
          "max_tokens": 12000,
          "keep_alive": "3m"
        }
      ]
    }
  },
 ```

This is an excerpt from a tcpdump capture

```
{"model":"mistral-nemo:12b-instruct-2407-q5_K_M","messages":[{"role":"user","content":"\nToday's date:\nToday is Wed, 11 Sep 2024 08:34:41 +0200.\n\n\nhola\n"},{"role":"assistant","content":"..Hola! ..En qu.. puedo ayudarte hoy?\n","tool_calls":null},{"role":"user","content":"hola"}],"stream":true,"keep_alive":-1,"options":{"num_ctx":12000,"num_predict":null,"stop":[],"temperature":1.0,"top_p":null},"tools":[]}

HTTP/1.1 200 OK
Content-Type: application/x-ndjson
Date: Wed, 11 Sep 2024 06:43:43 GMT
Connection: close
Transfer-Encoding: chunked
```

I'm using an up-to-date zed-preview (0.153.1 as of this writing)

Thanks!

### Environment

Zed: v0.153.1 (Zed Preview)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
`keep_alive` is not currently a supported configuration option via settings.json, but it wouldn't be too difficult to add.

Can you provide some context as to why this would desirable in your use case?

**Comment by graelo** [comment]
Thanks. This setting indicates to ollama it can release GPU memory after the delay has expired. Releasing the VRAM lets other processes use that precious VRAM (in my case, that's tritonserver).

**Comment by notpeter** [comment]
@graelo Can you test the `ollama_keep_alive` branch. I believe this PR will fix:
- https://github.com/zed-industries/zed/pull/17906

**Comment by graelo** [comment]
Thanks again! 😊 

I replied in the PR comments, but just wanted to reiterate that it works perfectly.

Also, just wanted to say thanks for making the build process so seamless - `cargo run --release` is a dream. Your work is really showing off its quality with each new PR!

**Comment by notpeter** [comment]
Glad to hear it. Merged.

It'll be available in Zed Preview on Wednesday and in Zed Stable a week later.

Thanks for reporting!
