### ISSUE TITLE
Search in project randomly toggles highlight for search term

### ISSUE THREAD

**Issue by Marcisbee** [zed-industries/zed#17690]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While using `cmd+shift+F` for searching in whole project, some of the files don't get highlighting for search term. And highlight just randomly shows up and hides itself when scrolling.

https://github.com/user-attachments/assets/4fe72724-5b2b-4617-b2f0-a3c78636af98

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by failable** [comment]
Some matches are not highlighted at all after a recent update of Zed.

```
Zed: v0.154.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
Thanks for reporting. Updates for Zed Stable and Zed Preview including the fix are building now and should be available shortly.
