### ISSUE TITLE
Reload file ?

### ISSUE THREAD

**Issue by stuaxo** [zed-industries/zed#17699]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be good if there was an option to reload a file from a disk (not just the whole workspace).

Also: if an open file changes outside the editor, it would be handy to have the option of reloading.

**Comment by kuglee** [comment]
I think this is related to this issue:
When a file is changed outside of the editor it created a copy of the changed file with a tilde in the name and on save it saves this copy:
![image](https://github.com/user-attachments/assets/adc3bc07-16e3-4b2f-813a-c5abfc0289b1)

**Comment by schpet** [comment]
in vim i'm used to writing `:e!` to trigger this behavior

**Comment by schpet** [comment]
i think this is a dupe of https://github.com/zed-industries/zed/issues/13212 fyi!
