### ISSUE TITLE
Recent panel project showing empty records

### ISSUE THREAD

**Issue by Warkanlock** [zed-industries/zed#17696]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The recent panel project exhibits an issue where names are truncated after N rows, seemingly at random. As a result, I’m currently unable to provide a consistent set of reproduction steps.

I can investigate further to determine if this is a rendering bug. However, it could also be related to the window slice logic used during rendering, which might be trimming names beyond a certain range.

Here's a demo:

https://github.com/user-attachments/assets/ffd1142d-dfc1-4de9-b294-d9ed5020c3cb

### Environment

Zed: v0.151.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
reference #16159
