### ISSUE TITLE
SendKeystrokes not working with capital letters

### ISSUE THREAD

**Issue by nmsobri** [zed-industries/zed#17701]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
  {
    "context": "vim_mode == insert",
    "bindings": {
      "k l": ["workspace::SendKeystrokes", "escape A"]
    }
  }

```
Above is my keybinding.. I want , when i type `kl`, the editor escape from insert mode and then place the cursor at the end of line. But that doesnt happen

### Environment

Zed: v0.151.2 (Zed)
OS: macOS 14.5
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
`shift-A` works for me.
Thanks @JunkuiZhang

**Comment by nmsobri** [comment]
yeah its working with `shift-a`
