### ISSUE TITLE
vim search doesn't work in assistant panel

### ISSUE THREAD

**Issue by maan2003** [zed-industries/zed#17704]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

open assistant panel and press / in vim mode. it is a no-op

### Environment

Zed: v0.153.0 (Zed Dev)
OS: Linux Wayland nixos 24.11
Memory: 7.4 GiB
Architecture: aarch64
GPU: Apple M1 (G13G B1) || Honeykrisp || Mesa 24.3.0-devel

**Comment by ConradIrwin** [comment]
Doesn't look like it has search at all yet! If you want to pair with me on fixing this: https://calendly.com/conradirwin/pairing

**Comment by maan2003** [comment]
ctrl+f works in insert mode

> If you want to pair with me

:+1: booked
