### ISSUE TITLE
Removing Icons

### ISSUE THREAD

**Issue by bearwithtea** [zed-industries/zed#17719]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great to have the ability to remove icons from the tray. I never use the AI feature or the chats, so I would like to remove the icons.

### If applicable, add mockups / screenshots to help present your vision of the feature

old
<img width="80" alt="old" src="https://github.com/user-attachments/assets/da327b41-184e-4bb5-99a7-25071503c046">

new (sorry for bad mockup)
<img width="80" alt="new" src="https://github.com/user-attachments/assets/b578c051-e86c-4d50-8777-b4b7e39bfbfd">

**Comment by bearwithtea** [comment]
Wow, thank you for the fast response. I should have assumed it was something to do with the .json config.

**Comment by bearwithtea** [comment]
@RemcoSmitsDev 

would you happen to know what the json is to hide the language and line?
<img width="81" alt="Screenshot 2024-09-11 at 5 13 24 PM" src="https://github.com/user-attachments/assets/67b18ba1-8966-4977-bb61-595c438d2141">

**Comment by RemcoSmitsDev** [comment]
There are no settings to disable these icons yet.

**Comment by bearwithtea** [comment]
Thank you so much! Have a nice day.
