### ISSUE TITLE
Snippet for HTML5

### ISSUE THREAD

**Issue by EloySM** [zed-industries/zed#17726]
### Check for existing issues

- [x] Completed

### Describe the feature

I Just would like to have a snippet to create the html structure like VSCode, the snippet '!' or 'html' I don't know something faster to create the structure

**Comment by Moshyfawn** [comment]
Check out the emmet extension in the Extensions tab in Zed.

**Comment by JosephTLyons** [comment]
Closing this out, as I think the emmet extension is the correct answer here. Feel free to open a new issue if this doesn't provide what you are looking for.
