### ISSUE TITLE
Cannot jump to the end of a very long line.

### ISSUE THREAD

**Issue by Tallone** [zed-industries/zed#17736]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Well, looks like it can only display 1024 characters in one line, Is this a bug or a feature?
below is compared with neovim.

<img width="1473" alt="image" src="https://github.com/user-attachments/assets/773d8b51-c47e-4f74-886b-0e66592a9223">

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
feature

**Comment by JosephTLyons** [comment]
I don't think its a bug, as it seems to be intentionally hardcoded here:

- https://github.com/zed-industries/zed/blob/75cb199a54666032e7a62dfb64739283556ae96c/crates/editor/src/editor.rs#L176

However, I'm not sure of the technical reason why - maybe this was some sort of quick patch to address some performance issues with files with pathologically-long lines.

@maxbrunsfeld might have a better understanding.

**Comment by maxbrunsfeld** [comment]
We should be soft-wrapping that line so that you can see the whole thing (but wrapped). I can't reproduce that behavior yet. @Tallone can you share that file, and your zed settings?

**Comment by Tallone** [comment]
I turn off the soft_wrap in my setting. because i don't like it...
test content is from Zed blog.
[zed.txt](https://github.com/user-attachments/files/17143186/zed.txt)
[settings.json](https://github.com/user-attachments/files/17143188/settings.json)

**Comment by maxbrunsfeld** [comment]
Ok, that makes sense. Currently, Zed has a limitation on how long of lines can be rendered, so the intended behavior is to force a soft-wrap at that length (even if soft-wrap is set to `none`) in cases where lines are really really long. But we're not doing that anymore. The immediate fix will be to restore that wrapping.
