### ISSUE TITLE
Rust Language Server Stalling / Crashing on Mac

### ISSUE THREAD

**Issue by markusmoenig** [zed-industries/zed#17739]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Rust Language server becomes unresponsive on Mac. This happened in a previous build, but was fixed in one of the last builds. But with Zed 0.152.3 it happens again.
I cannot work for more than 2 minutes without the language server not reacting anymore.

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by DylanVerstraete** [comment]
+1

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/17376
