### ISSUE TITLE
openai link in assistant chat window setup leads to anthropic

### ISSUE THREAD

**Issue by vextorspace** [zed-industries/zed#17749]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open the the assistant configuration window
2. look at the openai generate key link : it is console.anthropic.com/settings/keys but should be https://platform.openai.com/api-keys

### Environment

Zed: v0.152.3 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 62 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV REMBRANDT) || radv || Mesa 24.0.9-0ubuntu0.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by MrSubidubi** [comment]
This has been fixed yesterday on `main`.

- #17675

**Comment by JosephTLyons** [comment]
Closed via:

https://github.com/zed-industries/zed/pull/17675
