### ISSUE TITLE
Custom Terminal Support

### ISSUE THREAD

**Issue by mya4k** [zed-industries/zed#17750]
### Check for existing issues

- [X] Completed

### Describe the feature

Looked to see for a similar issue. Didn't find any. So here it is.

I know Zed uses Alacritty as the terminal emulator, I would like there to be a configuration to be able to customize what terminal emulator is used.

**Comment by maan2003** [comment]
zed doesn't use alacritty as program it uses alacritty as a library with custom renderer. you can't trivially use other terminals

**Comment by notpeter** [comment]
How are you envisioning this?  Would all terminal and tasks spawn use an external terminal application? Or is there a particular terminal application that supports being embedded as a library that you are proposing we adopt?
