### ISSUE TITLE
Open Recent Projects from top-right menu and from `projects::openRecent` do not have the same confirm key bindings

### ISSUE THREAD

**Issue by Ptitet** [zed-industries/zed#17765]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you go to the top-right burger menu and click on `Project > Open Recent Projects`, it says `enter reuses this window, ^enter opens a new one`.
When the open the same floating-menu with the action `projects::openRecent` via key bindings, it says the opposite : `^enter reuses this window, enter opens a new one`.
Also, actually using `^enter` does not work, it just "deletes" the text `enter reuses...`.

I cannot provide screenshots as the floating-menu disappear when I trigger the screenshot

### Environment

Zed: v0.152.3 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 7.7 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 5500 (BDW GT2) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

**Comment by kuku929** [comment]
hello, adding this to keymap.json fixes it. This should be the default setting, can I work on submitting a PR for this?
`
    {
        "context": "Workspace",
        "bindings": {
            "alt-ctrl-o": [
                "projects::OpenRecent",
                {
                    "create_new_window": false
                }
            ]
        }
    }
`

**Comment by Ptitet** [comment]
Thanks for the workaround ! Where are these kind of options (`{ "create_new_window": false }`) documented ?

**Comment by kuku929** [comment]
I am new here myself, but I found it in the default keymap. I am also curious about the documentation regarding this.

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/zed-industries/zed/pull/20176

**Comment by timriley** [comment]
Hi @SomeoneToIgnore, does https://github.com/zed-industries/zed/pull/20176 also address this aspect of the original issue?

> Also, actually using ^enter does not work, it just "deletes" the text enter reuses....

**Comment by SomeoneToIgnore** [comment]
Sounds like not, then, nice example of how mixing issues together does nothing good in the end.
I'd suggest creating a separate one for this particular issue.

**Comment by jliverman** [comment]
@timriley I am also seeing this with Zed 0.162.5 on macOS.

But it seems _inconsistent_. When I get it into a "mode" where it will accept cmd-enter as opening the project in a new window, it seems to work repeatedly regardless of how I opened the "Open recent project" window (File > Open Recent... OR clicking "Open recent project" OR alt-cmd-o). But if I ever get it into a "mode" where it ignores the new window directive i.e. cmd-enter just opens the project in the current window then it seems to retain that behavior for repeated attempts 🤷‍♂️ 

Also note that File > Open Recent... does not show the keybind (alt-cmd-o).

@SomeoneToIgnore Should we be opening a new issue for this? Or can this issue be re-opened seeing as how it is not actually fixed?

**Comment by SomeoneToIgnore** [comment]
> Should we be opening a new issue for this?

Yes, just like I wrote just one message above.

> Or can this issue be re-opened seeing as how it is not actually fixed?

The issue was about a different keybinding mainly, with a large header saying

> Open Recent Projects from top-right menu and from projects::openRecent do not have the same confirm key bindings

and a tiny line below mixing in something else about the bad keybinding in place.

I do not think it's good to combine things together in one issue, those are different.
