### ISSUE TITLE
Editor zoom level does not persist on restart

### ISSUE THREAD

**Issue by NiloCK** [zed-industries/zed#17760]
### Check for existing issues

- [X] Completed

### Describe the feature

Ubuntu, Zed 152.3

- Open a file with zed
- Zoom in or out (`ctrl +`, `ctrl -`)
- close zed
- reopen the same (or another) file

Result:
- Zed has returned to default zoom level

Desired result:
- configured zoom level persists

**Comment by Moshyfawn** [comment]
This has already been requested, so I'm going to close it in favour of the existing issue. Be sure to +👍 the other thread.

Duplicate of:
- #5380

**Comment by NiloCK** [comment]
> This has already been requested, so I'm going to close it in favour of the existing issue. Be sure to +👍 the other thread.
> 
> Duplicate of:
> 
>     * [Persist font size changes #5380](https://github.com/zed-industries/zed/issues/5380)

Apologies and thanks. I promise I searched. I am just a little blind sometimes.
