### ISSUE TITLE
Add support for new OpenAI `o1-preview` and `o1-mini` models

### ISSUE THREAD

**Issue by brianevanmiller** [zed-industries/zed#17772]
### Check for existing issues

- [X] Completed

### Describe the feature

Add new models to the Zed Assistant.  

`o1` "thinks" longer on prompts before answering, which would be nice within the Assistant panel for brainstorming / implementing more complicated solutions.

Intro: https://openai.com/o1/
Model docs: https://platform.openai.com/docs/models/o1
Playground: https://platform.openai.com/playground/chat?models=o1-mini

**Comment by gianpaj** [comment]
I opened this quick PR. 

https://github.com/zed-industries/zed/pull/17773
I don't have access to the model, so I can't test, and I'm abroad with my work laptop, so I couldn't try to build Zed :/

**Comment by micahscopes** [comment]
The beta o1 chat completions endpoint has [some limitations](https://platform.openai.com/docs/guides/reasoning/beta-limitations) complicating integration with zed as is.

Specifically there's not yet support for streaming responses, stop sequences or the temperature parameter.  I think it could be possible to hack together some support for this beta API endpoint but it doesn't seem to be drop-in compatible.
