### ISSUE TITLE
Language-Specific Theme Override settings have no effect

### ISSUE THREAD

**Issue by anssilap** [zed-industries/zed#17788]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I added language specific override to my Zed config as documented here: https://zed.dev/docs/configuring-languages#language-specific-theme-overrides
but it didn't have any effect.

Minimal example config that doesn't color syntax magenta as expected:
```JSONC
{
  "languages": {
    "Python": {
      "theme_overrides": {
        "syntax": {
          "function": {
            "color": "#FF00FF"
          }
        }
      }
    }
  }
}
```

Minimal example config that does color syntax magenta as expected, but as far as I know isn't configurable separately for each language:
```JSONC
{
  "experimental.theme_overrides": {
    "syntax": {
      "function": {
        "color": "#FF00FF"
      }
    }
  }
}
```

Python code where I'd expect words `main` and `print` to be highlighted in magenta with both configs:
```python
def main():
    print("This is a test")
```

Is this working as intended? I can't find any other documentation on how to make separate theme syntax overrides for different languages.

### Environment

Zed: v0.153.0 (Zed Dev 63188b6754276cf424aed2c1cc9947738d9c6116)
OS: Linux Wayland fedora 40
Memory: 31.3 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6800 XT (RADV NAVI21) || radv || Mesa 24.1.7

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
The documentation is incorrect, this is not supported.

Currently `experimental.theme_overrides` is only supported as a root level settings key and cannot be used as described.
