### ISSUE TITLE
Docs entry for Live Server

### ISSUE THREAD

**Issue by th0jensen** [zed-industries/zed#17792]
### Check for existing issues

- [X] Completed

### Describe the feature

I want to add an entry into the docs with tips and a suggested example on how to use Live Server in Zed.

This is one of the most frequently asked questions on the r/Zed subreddit, and I think it would be easier for the community to redirect people to comprehensive documentation instead of repasting the same answer in the subreddit.

### If applicable, add mockups / screenshots to help present your vision of the feature

N/A

**Comment by frederik-uni** [comment]
@th0jensen what kind of docs/examples would that be. there is no configuration for it yet. It could easily be added, but I didn't do it yet. the only options are if it should update on keypress or save, if it should open the port only on 127.0.0.1 or on 0.0.0.0 and what the start_port should be. The extension itself is just a lsp yet. registering commands with zed isn't possible yet as far as I know. How the workaround works is explained when clicking on the GitHub icon.

**Comment by frederik-uni** [comment]
now there is a config & it seems like commands are now working in zed(or whatever was broken on my machine isn't anymore), so I fixed the command

pub struct Config {
    /// Set if update on save or keypress [Default: false]
    lazy: Option<bool>,
    /// 0.0.0.0 or 127.0.0.1 [Default: false]
    public: Option<bool>,
    /// Set the port number
    start_port: Option<u16>,
}
