### ISSUE TITLE
bug in the front end compiler in c

### ISSUE THREAD

**Issue by ElAv252** [zed-industries/zed#17793]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have an issue that the "Problem diagnostic" show me that I have some errors in the code, but actually I don't.

I would love for you to look into the matter, thank you very much!!

### Environment

 Model Name: MacBook Pro
      Chip: Apple M1 Pro
      Memory: 16 GB

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
The C diagnostics are provided by clangd, which is a 3rd party tool. If you use compiler flags that are not defaults for your version of clangd (such as a new language version - Apple is somewhat notorious for shipping an outdated version of the LLVM toolchain!), you may have to [tell clangd what flags to build with](https://clangd.llvm.org/config.html#compileflags). Or if your project uses something like cmake/meson/premake to generate build files, those tools can be instructed to generate a `compile_commands.json` with all the necessary flags on a per-source-file basis.

**Comment by ElAv252** [comment]
I used gcc compiler...

And i show the erros in the "Problem diagnostic" panel of zed.

**Comment by jansol** [comment]
What compiler you use for actually building your code is irrelevant. You need to tell the language server what flags to build with  so that the language server can do its thing correctly.

**Comment by ElAv252** [comment]
Ok, got it.
Thanks!
