### ISSUE TITLE
Can't download any extension

### ISSUE THREAD

**Issue by Notwatch** [zed-industries/zed#17791]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't seem to install any extensions.

I think it's Zed server that is blocking my IP or something, because when I tried manually requesting to this url `https://api.zed.dev/extensions/html/download` it's also got stuck and got timed out
```
$ wget https://api.zed.dev/extensions/html/download
--2024-09-13 18:41:24--  https://api.zed.dev/extensions/html/download
Resolving api.zed.dev (api.zed.dev)... 104.26.11.80, 172.67.73.169, 104.26.10.80
Connecting to api.zed.dev (api.zed.dev)|104.26.11.80|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://zed-extensions.nyc3.digitaloceanspaces.com/extensions/html/0.1.2/archive.tar.gz?x-id=GetObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=DO0024BKKDAMB3MYP3DP%2F20240913%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20240913T114124Z&X-Amz-Expires=180&X-Amz-SignedHeaders=host&X-Amz-Signature=ba5f51766b824e087a2f2aed812774512366f2a6ed6d2dcdd3f38704331e197a [following]
--2024-09-13 18:41:25--  https://zed-extensions.nyc3.digitaloceanspaces.com/extensions/html/0.1.2/archive.tar.gz?x-id=GetObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=DO0024BKKDAMB3MYP3DP%2F20240913%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20240913T114124Z&X-Amz-Expires=180&X-Amz-SignedHeaders=host&X-Amz-Signature=ba5f51766b824e087a2f2aed812774512366f2a6ed6d2dcdd3f38704331e197a
Resolving zed-extensions.nyc3.digitaloceanspaces.com (zed-extensions.nyc3.digitaloceanspaces.com)... 162.243.189.2
Connecting to zed-extensions.nyc3.digitaloceanspaces.com (zed-extensions.nyc3.digitaloceanspaces.com)|162.243.189.2|:443... failed: Operation timed out.
Retrying.

--2024-09-13 18:42:41--  (try: 2)  https://zed-extensions.nyc3.digitaloceanspaces.com/extensions/html/0.1.2/archive.tar.gz?x-id=GetObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=DO0024BKKDAMB3MYP3DP%2F20240913%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20240913T114124Z&X-Amz-Expires=180&X-Amz-SignedHeaders=host&X-Amz-Signature=ba5f51766b824e087a2f2aed812774512366f2a6ed6d2dcdd3f38704331e197a
Connecting to zed-extensions.nyc3.digitaloceanspaces.com (zed-extensions.nyc3.digitaloceanspaces.com)|162.243.189.2|:443... 
```

I've checked other similar issues, but I don't think it's the same as my issue

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-13T18:37:53.868974+07:00 [INFO] installing extension html latest version
2024-09-13T18:37:59.239001+07:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-13T18:37:59.239819+07:00 [ERROR] error downloading extension: request or operation took longer than the configured timeout time
2024-09-13T18:38:03.117309+07:00 [INFO] installing extension html latest version
2024-09-13T18:38:08.547149+07:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-13T18:38:08.547779+07:00 [ERROR] error downloading extension: request or operation took longer than the configured timeout time
</pre></details>

**Comment by sentabi** [comment]
I'm facing the same problem, it seems getting blocked on DigitalOcean space
```
* Issue another request to this URL: 'https://zed-extensions.nyc3.digitaloceanspaces.com/extensions/html/0.1.2/archive.tar.gz?x-id=GetObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=DO0024BKKDAMB3MYP3DP%2F20240913%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20240913T152232Z&X-Amz-Expires=180&X-Amz-SignedHeaders=host&X-Amz-Signature=2b44c50419e6aaf7bbd6039adc325e9ef91362f8989811b99d70f7fc340e9a8d'
* Host zed-extensions.nyc3.digitaloceanspaces.com:443 was resolved.
* IPv6: (none)
* IPv4: 162.243.189.2
*   Trying 162.243.189.2:443...
```

so for a workaround, I use VPN. 


Environment
```
Zed: v0.152.3 (Zed)
OS: Linux X11 fedora 40
Memory: 13.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.1.7
```

**Comment by notpeter** [comment]
I feel like there's a good chance this is an upstream (DigitalOcean Storage Spaces) issue which has likely been resllve.  Are you still seeing this issue or was just transient?

**Comment by Notwatch** [comment]
I just checked again, and yes the issue still persist

**Comment by notpeter** [comment]
I have seen reports of the IP address(es) used to host DigitalOcean Storage Spaces being incorrectly flagged as hosting malware, but they should be managing reputation by hostname (zed-extensions.nyc3.digitaloceanspaces.com) not by IP (162.243.189.2).

Are you by chance using an anti-virus / endpoint security product on your machine or network which might be blocking this?

**Comment by notpeter** [comment]
Sorry you're having a bad time, but I'm going to go ahead and close as unactionable.
Your local network or endpoint security is likely blocking access to DO spaces IPs and that is beyond our control. 

Conceivably in the future which could migrate this to an alternate provider (e.g. CloudFlare R2) which might be less likely to be blocked, but we have no immediate plans to do so.
