### ISSUE TITLE
Add support for new OpenAI models o1-mini and o1-preview

### ISSUE THREAD

**Issue by YngveMolnes** [zed-industries/zed#17790]
### Check for existing issues

- [X] Completed

### Describe the feature

https://openai.com/index/introducing-openai-o1-preview/

OpenAI recently released a new set of models that supposedly reason more, and supposedly codes better than most of us. I ran auto-update in zed, currently running 0.152.3 and the models are now available in my LLM-context panel.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/3596a463-f151-4d05-8228-23f2873e740f)

**Comment by YngveMolnes** [comment]
Closed as duplicate #17772

**Comment by micahscopes** [comment]
@YngveMolnes I'm not seeing `o1-preview` or `o1-mini` there in the screenshot you posted, only `gpt-4o`
 and `gpt-4o-mini`
![image](https://github.com/user-attachments/assets/43a15c3f-b71d-4107-b132-8265e3a234ea)

At any rate, it seems like o1 chat completion endpoints are missing some key features that zed currently relies on.
