### ISSUE TITLE
cmd-n doesn't open new tab in assistant panel

### ISSUE THREAD

**Issue by nickelser** [zed-industries/zed#17807]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. hit cmd-n to open a new tab with an assistant tab focused
2. new window opens in the main editor tabs, not in the assistant

split views seem to work fine, and this is a regression from a version or two ago

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
This has been fixed in #17407 and is already available in Preview [`v0.153.2`](https://zed.dev/releases/preview/0.153.2) and will move to Stable mid next week.
