### ISSUE TITLE
Expand Excerpts causes Zed to crash

### ISSUE THREAD

**Issue by wolfadex** [zed-industries/zed#17803]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open project search
2. Search for something that brings up multiple results
3. Move the cursor to the very last position possible
4. Run any of the "Expand Excerpts" commands
5. Zed crashes

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16997571/Zed.log)

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/zed/pull/17955
