### ISSUE TITLE
Toggle code hiding buttons

### ISSUE THREAD

**Issue by verhovsky** [zed-industries/zed#17813]
### Check for existing issues

- [X] Completed

### Describe the feature

I have never used these things that hide scopes, I would like to hide them so I don't have this large piece of empty space between the file browser and the editor window

<img width="94" alt="Screenshot 2024-09-13 at 15 02 19" src="https://github.com/user-attachments/assets/77e959df-884d-4e73-8d8a-c173a200900d">

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="73" alt="Screenshot 2024-09-13 at 15 02 19 copy" src="https://github.com/user-attachments/assets/2e8e7f6e-ce44-4c5f-a934-5b08e0bad9ae">

**Comment by Moshyfawn** [comment]
This is supported.

```json
{
  "gutter": {
    "folds": false
  }
}
```

**Comment by verhovsky** [comment]
Thank you, I searched for `editor: toggle` and it wasnt there

**Comment by Moshyfawn** [comment]
You can reference the default `settings.json` comfig by selecting `zed: open default settings` from the command palette to try and find settings you're looking for.
