### ISSUE TITLE
Clipboard manager / history

### ISSUE THREAD

**Issue by thomaseizinger** [zed-industries/zed#17812]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed should remember all the things I copied and offer me to paste previous entries as well. Ideally, the default paste shortcut should just paste the last item and a different shortcut (CTRL+SHIFT+V maybe?) should open a selection menu of the items that were previously copied.

**Comment by Moshyfawn** [comment]
This feature has already been requested, so I'm going to close this issue in favour of the existing one. Be sure to +👍 the other thread.

**Comment by thomaseizinger** [comment]
> This feature has already been requested, so I'm going to close this issue in favour of the existing one. Be sure to +👍 the other thread.
> 
> Duplicate of:
> 
>     * [Add a built-in clipboard manager #4412](https://github.com/zed-industries/zed/issues/4412)

I searched "clipboard history" and didn't find it, sorry about the dupe!

**Comment by Moshyfawn** [comment]
Np!
