### ISSUE TITLE
zed closes unexpectedly when trying to use ai assistant

### ISSUE THREAD

**Issue by sfclub** [zed-industries/zed#17825]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

zed (Zed 0.152.3/ 21ab87dc640928edb8e22ec04d7868c1b312df6d) closes unexpectedly when trying to use ai assistant.
See video 

https://github.com/user-attachments/assets/4f5ec73e-da68-4508-bf51-4b29448c0f48

 

### Environment

mac os 12.7.5

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17002756/Zed.log)

</pre></details>

**Comment by sfclub** [comment]
console output:



 /Applications/Zed.app/Contents/MacOS/zed
[2024-09-14T17:00:11+03:00 ERROR theme] theme not found: New Darcula
[2024-09-14T17:00:11+03:00 ERROR theme] theme not found: New Darcula
[2024-09-14T17:00:11+03:00 ERROR theme] theme not found: New Darcula
[2024-09-14T17:00:11+03:00 ERROR theme] theme not found: New Darcula
[2024-09-14T17:00:11+03:00 ERROR theme] theme not found: New Darcula
[2024-09-14T17:00:12+03:00 ERROR zed] failed to parse header value
[2024-09-14T17:03:16+03:00 ERROR zed::reliability] {
  "thread": "main",
  "payload": "byte index 118 is not a char boundary; it is inside 'п' (bytes 117..119) of `///\n    /// Мы используем Arc, чтобы избежать ненужного использования прост`",
  "location_data": {
    "file": "crates/rope/src/rope.rs",
    "line": 736
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys_common::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::str::slice_error_fail_rt",
    "core::str::slice_error_fail",
    "<rope::Chunks>::peek",
    "<rope::Chunks as core::iter::traits::iterator::Iterator>::next",
    "<assistant::prompts::PromptBuilder>::generate_content_prompt",
    "<assistant::inline_assistant::Codegen>::build_request",
    "<assistant::inline_assistant::PromptEditor>::count_tokens::{closure#0}::{closure#0}",
    "<async_task::raw::RawTask<<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), anyhow::Error>>>>>, core::result::Result<(), anyhow::Error>, <gpui::executor::ForegroundExecutor>::spawn::inner<core::result::Result<(), anyhow::Error>>::{closure#0}, ()>>::run",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "<gpui::app::App>::run::<zed::main::{closure#3}>",
    "zed::main",
    "std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.152.3",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "12.7.5",
  "architecture": "x86_64",
  "panicked_on": 1726322596664,
  "installation_id": "b005505b-cbe3-446b-82b5-6de5ffdbe642",
  "session_id": "443c0aa6-a1f0-4968-9755-e452804d61df"
}
[1]    7967 abort      /Applications/Zed.app/Contents/MacOS/zed

**Comment by sfclub** [comment]
[Zed.log](https://github.com/user-attachments/files/17002758/Zed.log)

**Comment by AlbertMarashi** [comment]
@sfclub this looks to be some sort of character encoding issue

**Comment by sfclub** [comment]
> @sfclub this looks to be some sort of character encoding issue with your language judging by this line
> 
> ```
> "payload": "byte index 118 is not a char boundary; it is inside 'п' (bytes 117..119) of ///\n    /// Мы используем Arc, чтобы избежать ненужного использования прост",
> ```

does the video show what my actions can lead to an encoding problem?
