### ISSUE TITLE
Zed creates `~/.cache/zed` instead of using `$XDG_CACHE_HOME` or `~/Library/Caches` (macOS)

### ISSUE THREAD

**Issue by joshklein** [zed-industries/zed#17835]
### Check for existing issues

- [X] Completed

##### Current Behavior

Zed creates a cache hardcoded to the path `~/.cache/zed` on launch

##### Expected Behavior

Zed should respect `$XDG_CACHE_HOME` if set and otherwise use the OS's default cache location, i.e. `~/Library/Caches` in the case of macOS.

##### Related Issues

 Possibly [#14221 ](https://github.com/zed-industries/zed/issues/14221) and the issues it links to.

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

N/A

### If applicable, attach your Zed.log file to this issue.

N/A, but while looking through my `~/Library/Logs/Zed/Zed.log` I noticed the line:

`... [INFO] set environment variables from shell:/bin/zsh ...`

This also suggests a separate issue of hardcoded configuration, since I do not use the default macOS zsh shell. It also seems to only be grabbing the $PATH and not other environment variables. 

I'm not submitting this as a separate issue at this time because it is not an actual bug I'm experiencing, but it could produce one in the future.

**Comment by notpeter** [comment]
Hi @joshklein,

Thanks for reporting.  #17949 should fix this.

Re: 
> `... [INFO] set environment variables from shell:/bin/zsh ...`
> This also suggests a separate issue of hardcoded configuration, since I do not use the default macOS zsh shell. It also seems to only be grabbing the $PATH and not other environment variables.

We do attempt to detect your shell and behave accordingly.  Earlier in the function which outputted the `set environment variables from shell` log  you can see we're picking it up from the SHELL env var:

https://github.com/zed-industries/zed/blob/1d20cd76a230248d290ca27b73ee5e7410a547f9/crates/zed/src/main.rs#L995-L999

What is the value of `SHELL` for you? E.g. Have you changed your shell (e.g. via `chsh`) or are you just launching your preferred shell as a subprocess via `~/.zshrc`?

**Comment by joshklein** [comment]
Hi @notpeter,

I realize my mistake regarding `SHELL` now -- it was indeed still set to `/bin/zsh`  --  but please allow me some elaboration that might be useful intel.

> What is the value of SHELL for you? E.g. Have you changed your shell (e.g. via chsh) or are you just launching your preferred shell as a subprocess via ~/.zshrc?

The answer to your straightforward question is slightly convoluted, unfortunately. I've `chsh` my shell in the past, which required adding a new entry to `/etc/shells`. On system updates, Apple writes over all changes made under `/etc`, so the more sustainable approach turns out to be modifying the shell settings of the terminal emulator.

In my case, that means changing Terminal.app via **Settings** -> **General** -> **Shells open with:** -> **Command:** to run `/opt/local/bin/fish`. Launching the new shell as a subprocess via `~/.zshrc` could be another option.

This extra complication wouldn't affect anyone using one of the shells already appearing in `/etc/shells` per Apple's defacto configuration: 

```
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
```

While I might be an outlier in using `/opt/local/bin/fish`, I expect plenty of developers trying Zed will be using Homebrew or Macports to `brew` or `port` install a more recent version of these shells than has been provided by Apple. Zed will also "clobber" those shell changes, as `SHELL` will remain the default  `/bin/zsh` despite the user expectation.

This should all be relatively easy to work around now that I'm aware of it. I'll either wrap the Zed application to set `SHELL` before launching, or maybe try something like `/bin/launchctl setenv SHELL /opt/local/bin/fish` to see if Zed picks it up that way.  Just thought the info might be worth sharing. 

Cheers!

**Comment by injust** [comment]
> The answer to your straightforward question is slightly convoluted, unfortunately. I've `chsh` my shell in the past, which required adding a new entry to `/etc/shells`. On system updates, Apple writes over all changes made under `/etc`, so the more sustainable approach turns out to be modifying the shell settings of the terminal emulator.
> 
> In my case, that means changing Terminal.app via **Settings** -> **General** -> **Shells open with:** -> **Command:** to run `/opt/local/bin/fish`. Launching the new shell as a subprocess via `~/.zshrc` could be another option.

This shouldn't be necessary. I use fish (installed with Homebrew). I don't remember how I configured it as my default shell, but `/usr/local/bin/fish` is listed in my `/etc/shells` and I've never had to do any weird hacks like this.

**Comment by injust** [comment]
@joshklein https://support.apple.com/en-us/102360

Follow the steps under "How to change your default shell" and then under "From Users & Groups settings"

**Comment by joshklein** [comment]
Thanks @injust, I wasn't aware of that System Settings submenu. It looks like the UI itself just runs `chsh`, but I assume using this method means Apple's updates will have the awareness to avoid writing over the user change in the future. Good stuff!
