### ISSUE TITLE
The entire application is transparent

### ISSUE THREAD

**Issue by Ramun-R** [zed-industries/zed#17830]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just installed Zed as instructed from https://zed.dev/download, after installation i tried running it but the window seems invisible, i can see it in the task bar but the window itself is invisible, it also looks like whatever was on my screen at the time i opened, i opened it with my browser open and now it looks like the piece of the browser it appeared on top of

### Environment

Can't access it, but i ran "inxi -Fxz" and got 

```
System:
  Kernel: 6.8.0-40-generic x86_64 bits: 64 compiler: N/A
    Desktop: Cinnamon 6.0.4 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Mecer product: Xtreme v: N/A
    serial: <superuser required>
  Mobo: Intel model: DQ45CB v: AAE30148-207 serial: <superuser required>
    UEFI: Intel v: CBQ4510H.86A.0093.2009.0724.1353 date: 07/24/2009
CPU:
  Info: dual core model: Intel Core2 Duo E7500 bits: 64 type: MCP
    arch: Core Yorkfield rev: A cache: L1: 128 KiB L2: 3 MiB
  Speed (MHz): avg: 1600 min/max: 1596/2926 cores: 1: 1600 2: 1600
    bogomips: 11733
  Flags: ht lm nx pae sse sse2 sse3 sse4_1 ssse3 vmx
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 710] vendor: Gigabyte driver: nvidia
    v: 470.256.02 bus-ID: 01:00.0
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1280x1024
  OpenGL: renderer: NVIDIA GeForce GT 710/PCIe/SSE2
    v: 4.6.0 NVIDIA 470.256.02 direct render: Yes
Audio:
  Device-1: Intel 82801JD/DO HD Audio driver: snd_hda_intel v: kernel
    bus-ID: 00:1b.0
  Device-2: NVIDIA GK208 HDMI/DP Audio vendor: Gigabyte
    driver: snd_hda_intel v: kernel bus-ID: 01:00.1
  Sound Server-1: ALSA v: k6.8.0-40-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82567LM-3 Gigabit Network driver: e1000e v: kernel
    port: e0e0 bus-ID: 00:19.0
  IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8
    bus-ID: 2-2:2
  Report: hciconfig ID: hci0 rfk-id: 0 state: down
    bt-service: enabled,running rfk-block: hardware: no software: no
    address: <filter>
Drives:
  Local Storage: total: 1.35 TiB used: 213.16 GiB (15.5%)
  ID-1: /dev/sda vendor: Kingston model: SA400S37480G size: 447.13 GiB
  ID-2: /dev/sdb vendor: Western Digital model: WD10EZEX-00BBHA0
    size: 931.51 GiB
Partition:
  ID-1: / size: 438.55 GiB used: 213.16 GiB (48.6%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 7 MiB (1.4%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 440 MiB (21.5%) file: /swapfile
Sensors:
  System Temperatures: cpu: 52.0 C mobo: N/A gpu: nvidia temp: 56 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 57%
Info:
  Processes: 272 Uptime: 58m Memory: 5.72 GiB used: 3.25 GiB (56.9%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.4.0 clang: 14.0.0-1ubuntu1.1
  Packages: 3708 Shell: Zsh v: 5.8.1 inxi: 3.3.13

```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot from 2024-09-14 22-04-28](https://github.com/user-attachments/assets/a02bca4c-f86b-483b-9e10-5be8d1362f33)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17003611/Zed.log)
</pre></details>

**Comment by apricotbucket28** [comment]
From looking at the logs:
> 2024-09-14T20:27:20.842729124+02:00 [INFO] Adapter: "NVIDIA GeForce GT 710"
2024-09-14T20:27:20.842889759+02:00 [WARN] Rejected for device extension "VK_KHR_dynamic_rendering" not supported. Please update the driver!
2024-09-14T20:27:20.842959042+02:00 [INFO] Adapter: "llvmpipe (LLVM 15.0.7, 128 bits)"

It rejects your GPU because the drivers are too old, and it falls back to software rendering, but that seems to cause a blank screen for some reason.

**Comment by Ramun-R** [comment]
I am on Nvidia driver 470.256.02, i also already tried [0.151.2](https://zed.dev/releases/stable/0.151.2)

**Comment by Ramun-R** [comment]
I tried v143.6 and 145.1, both gave me the same result

**Comment by JosephTLyons** [comment]
Hey @Ramun-R, do you experience any of the other symptoms, as reported here?

- https://github.com/zed-industries/zed/issues/14648

**Comment by Ramun-R** [comment]
@JosephTLyons They are basically identical, I checked with htop and the CPU does shoot up but only for a brief moment on mine

**Comment by JosephTLyons** [comment]
Ok, since they similar enough, let's use that one and close this one out, since it has a handful of upvotes on it already (👍).

**Comment by Ramun-R** [comment]
@JosephTLyons I also have to mention that i also tried building from source and got the same result
