### ISSUE TITLE
Support OSC52 escape sequence in terminal

### ISSUE THREAD

**Issue by shahamran** [zed-industries/zed#17848]
### Check for existing issues

- [X] Completed

### Describe the feature

Reference:
* <https://github.com/microsoft/vscode/issues/193508>
* <https://github.com/xtermjs/xterm.js/issues/3260>

Copied from the xtermjs issue:

> ANSI OSC 52 is a sequence to transport some data from remote console app to client's clipboard. For example, tmux can use it on remote side, and xterm (terminal app), Windows terminal and a number of others -- on client side. It would be very convenient to have such a feature in ~~xterm.js~~ **zed's terminal**.
>
> Here is a simple test which sends a string from remote to local clipboard (taken https://github.com/realh/roxterm/issues/206#issue-433783926):
>
> ```shell
> printf "\033]52;c;$(printf "%s" "blabla" | base64)\a"
> ```

Please and thank you :)

**Comment by notpeter** [comment]
It appears alacritty (used for Zed's terminal) supports OSC52 so we may potentially be able to reuse some of that functionality. https://alacritty.org/config-alacritty.html#terminal

**Comment by piechologist** [comment]
I accidentally discovered that this is working now! 🎉👌

I'm using Zed Preview 0.155.1. Can't remember seeing it in the release notes though.
