### ISSUE TITLE
`/perplexity` slash command extension not published

### ISSUE THREAD

**Issue by ribelo** [zed-industries/zed#17845]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/pull/16438#issuecomment-2314497724

### Environment

Zed: v0.152.3 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 30.6 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV REMBRANDT) || radv || Mesa 24.2.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi @ribelo, 

We have not yet published the perplexity extension in the Extension store, but it should work when installed from source as a 'dev extension'.  I added a [readme](https://github.com/zed-industries/zed/tree/main/extensions/perplexity) with some instructions yesterday.  Can you see if you can follow those and report if things are working as expected.

Additionally, even with the correct environment variables set, the perplexity slash command only works if you have a workspace open (e.g. a folder, not just an empty window or some orphan files).  I haven't discussed it internally, but I believe these rough corners are part of the reason we have refrained from publishing it.

**Comment by Benjamin-van-Heerden** [comment]
Any updates on this?
I think this feature could be useful.

**Comment by notpeter** [comment]
Enjoy!
