### ISSUE TITLE
[Windows 11 WSL2] Assistant Panel is blank

### ISSUE THREAD

**Issue by avcode-exe** [zed-industries/zed#17844]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I connected to WSL2 in Windows 11 through "projects: open remote" command palette action. Then in my WSL2 env, the assistant panel is blank; while in the usual Windows 11 env, the assistant panel is normal.
Btw, I installed Zed in Windows 11 through Scoop.

### Environment

Zed: v0.154.0 (Zed Dev 6f337de440687bdc233c4e6f845f88d44a8f9740)
OS: Windows 10.0.26100
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/b266d83c-d595-423e-8f8e-4b2ebdf507ab)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17005501/Zed.log)
</pre></details>

**Comment by bennetbo** [comment]
Should be fixed in the latest preview release, see https://github.com/zed-industries/zed/issues/17898#issuecomment-2443987447
