### ISSUE TITLE
[feature request] Allow creating folders and file at the same time

### ISSUE THREAD

**Issue by melMass** [zed-industries/zed#17849]
### Check for existing issues

- [X] Completed

### Describe the feature

*Sorry if duplicate, I looked but there are a lot of issues and I'm not sure of the terms to use.*

In neovim I regularly create folder and file at the same time: `myfolder/myfile.ext`, I naively assumed Zed did too (IIRC VSCode did that as well) but I end up in a strange state where is seems to half work?
<img width="301" alt="image" src="https://github.com/user-attachments/assets/23a985fd-6ecc-463e-8361-c64a4d192e5e">

As you can se in the screenshots it creates 2 folders nested instead of one folder with one file inside

<img width="507" alt="image" src="https://github.com/user-attachments/assets/46bc0d65-5635-4862-817b-70ebe353ae74">

I hesitated between bug and feature request because of that.

### If applicable, add mockups / screenshots to help present your vision of the feature

*added in the main body*

**Comment by RemcoSmitsDev** [comment]
You can disable this by adding the following to your config file:
```json
{
  "project_panel": {
    "auto_fold_dirs": false
  }
}
```

**Comment by melMass** [comment]
Thanks I will try that, so this would still allow creating the parent folder but the leaf will properly be a file?

**Comment by RemcoSmitsDev** [comment]
By setting this value to false, it does not fold directories when it does not have direct files inside it. So if you create a file inside the plugin directory without changing the setting it will display it as you expect it would.

**Comment by melMass** [comment]
I think there is a misunderstanding, I want to create the plugins folder at the same time as the file here so I write `plugins/file.py` in the create new file text box. That creates 2 folders currently (nested as expected) but it should create 1 folder and 1 file (nested)

**Comment by notpeter** [comment]
@melMass Are you using `New File` (cmd-n) or `New Folder` (cmd-alt-n)?  The latter exhibits the behavior you describe (creates 2 folders) while the former exhibits the behavior you desire (creates one file and one folder).

Can you verify you are using the correct function?

**Comment by melMass** [comment]
Oh I feel dumb... I'm not sure what shortcut I was using before!
Add file (cmd+n) indeed does exactly what I wanted 🙈
