### ISSUE TITLE
Vim Mode - Multicursor Spawn at Beginning/End of Line

### ISSUE THREAD

**Issue by titouandk** [zed-industries/zed#17842]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has a nice feature to spawn multiple cursors in Vim mode (this is not a native Vim behavior).

You can select lines using the Vim visual line selection mode (`Shift+V`), and press `Shift+I` or `Shift+A` to add cursors to the beginning/end of each line.

### Desired Behavior (VSCode as a reference)

https://github.com/user-attachments/assets/3a5969ce-5153-49bf-9672-c94c6db74f9d

https://github.com/user-attachments/assets/99203650-6c75-4a10-b3df-9dcdde0253d4

### Current Zed Behavior

Here are the current behaviors in zed for the same key inputs in Vim mode.

Visual line selection `Shift+V`, then `J` `J` `J` `J` to select following lines, then `Shift+I` to add a cursor at the beginning of lines:

https://github.com/user-attachments/assets/94aaa53f-842c-4cb6-94aa-77d8184dd9a8

Visual line selection `Shift+V`, then `J` `J` `J` `J` to select following lines, then `Shift+A` to add a cursor at the end of lines:

https://github.com/user-attachments/assets/fcf8b636-7bdf-48a7-84c7-e0efb052d2fc

**Comment by sebb3** [comment]
I use Visual block mode for this, which works great. (ctrl+v, j, j, j, j, shift+i)

however, it would be great to be able to select several insertion points that are not adjacent to eachother, without relying on alt+mouse. I know we have cmd+d but it only works if you're looking for the same word.

**Comment by titouandk** [comment]
@sebb3 I think the visual line way is more practical to place cursors at the beginning and end of a line (we have less keystrokes in most of the cases).

In the case you would want to place cursors at the end of lines of unequal lengths by example, block selection would force you to add a keypress ($) to move all cursors at the end of the lines before entering insert mode (shift+a).

https://github.com/user-attachments/assets/e313f7f0-2257-40e2-b36b-9c04efe4619e


The same is true if you want to add text at the beginning of the line, if your cursor is not already at the beginning of a line. 
(With the line selection method, your cursor may be anywhere on the line.)

**Comment by sergioengineer** [comment]
Visual Block mode currently has a big disadvantage which is: it doesn't allow you to go back to normal mode.
As soon as you press shift+I, you are commited to only adding new text to the beginning of the line. As soon as you press CTRL+C/ESC, you are back to having one cursor only.

Besides, there's another use case to mr's @titouandk suggestion which is being able to work with text objects.
If you want to add all the lines of text inside a DIV into new separated divs for example: You can vit -> gI -> type <div> -> CTRL+C -> $ -> type </div> and voilà.

It would work with other commands as well such as vi and va(egg. 'va{' ).

It's a lot more powerful than what visual block offers right now.

Now, the suggestion for having the ability to add arbitrary cursors  is an awesome one. It is something we are lacking right now. But we'd need to discuss about keybindings and behavior in a new issue though.
