### ISSUE TITLE
`hi@zed.dev` email appears to be broken?

### ISSUE THREAD

**Issue by thomaseizinger** [zed-industries/zed#17865]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Emails sent to `hi@zed.dev` bounce. Not sure how else to report this? :)

### Environment

n/a

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/c20e55c4-d671-431d-8b52-7a1498f4751b)

**Comment by notpeter** [comment]
Hi @thomaseizinger,

This is really odd.  I just tested this an the message was delivered as expected.

Can you try again or email me directly (myfirstname@zed.dev) and see if that works?

**Comment by thomaseizinger** [comment]
> Hi @thomaseizinger,
> 
> This is really odd. I just tested this an the message was delivered as expected.
> 
> Can you try again or email me directly ([myfirstname@zed.dev](mailto:myfirstname@zed.dev)) and see if that works?

I tried again with `hi@zed.dev` and it still didn't work. At the bottom, it says:

> The account $myemail is disabled.

**Comment by notpeter** [comment]
Can you try from an alternate email address / provider?  I believe this message can you occur when **your** google account is disabled/suspended. [source](https://support.google.com/a/answer/3237621?hl=en)

<img width="979" alt="Screenshot 2024-09-16 at 9 23 38" src="https://github.com/user-attachments/assets/857cf32b-6f81-4af9-8e3a-d2d4313425da">

**Comment by thomaseizinger** [comment]
> when **your** google account is disabled/suspended. [source](https://support.google.com/a/answer/3237621?hl=en)

My email is not hosted on Google though so I am not sure how this would apply?

**Comment by thomaseizinger** [comment]
> Can you try again or email me directly ([myfirstname@zed.dev](mailto:myfirstname@zed.dev)) and see if that works?

I also emailed you directly and did **not** receive a bounce-back. Did you receive that one?

**Comment by notpeter** [comment]
I received your email from eizinger.io to me.
I received your email from firezone.dev to hi@zed.dev.

Hopefully it was just something transient with Google 🤷
