### ISSUE TITLE
Tasks using 'system' shell try to use the local system's shell in remote development mode

### ISSUE THREAD

**Issue by davidspry** [zed-industries/zed#17862]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Tasks using the `system` shell try to use the local system's shell, rather than the remote system's shell, in remote development mode.

For example, if I start a remote development session from macOS, then tasks (including those stored on the remote system) will attempt to use `zsh` on systems in which `zsh` is not installed.

```
sh: line 1: /bin/zsh: No such file or directory

⏵ Task `build` finished with non-zero error code: 127
⏵ Command: '/bin/zsh -i -c `path/to/script.sh`'
```

### Environment

**Local system**
Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

**Remote system**
Zed: v0.152.3 (Zed)
OS: Linux Wayland fedora 38
Memory: 38.9 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 23.1.9

**Comment by mrnugget** [comment]
I'm pretty sure this is fixed in the newest versions. Most likely by #19297
