### ISSUE TITLE
Expo QR code not display well in terminal

### ISSUE THREAD

**Issue by wogno** [zed-industries/zed#17904]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When qr code is displayed in termial he cannot be display well.  so qrcode is not scannable.

Step to product.
1. Init new expo app
2. Start project with npx expo start

<img width="421" alt="Capture d’écran 2024-09-16 à 18 59 24" src="https://github.com/user-attachments/assets/9e8470cb-17fd-40b2-83d8-54cc1946db73">

### Environment

I used macbook pro 2019 with zsh terminal

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="742" alt="Capture d’écran 2024-09-16 à 18 59 37" src="https://github.com/user-attachments/assets/bf2322bd-e317-4de8-9d2a-2c96c8b87495">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
By default Zed uses a golden ratio terminal line height ("comfortable") you can switch this to "standard" by altering the [Terminal Line Height](https://zed.dev/docs/configuring-zed#terminal-line-height) and you won't have margin between lines:

```
{
  "terminal": {
    "line_height": "standard"
  }
}
```

Let me know if that doesn't work. Thanks

**Comment by mrevanzak** [comment]
hey it still not working on me
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/e2a7150f-d11a-480f-ad3a-e1e269d90134">

**Comment by alexmitchelldev** [comment]
Fixed this applying these settings:
```
"terminal": {
    "line_height": {
      "custom": 1.3
    },
    "font_family": "PT Mono"
  }
```
