### ISSUE TITLE
Dark theme for Zed website

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#17911]
### Check for existing issues

- [X] Completed

### Describe the feature

I often read the documentation on [Zed website](https://zed.dev/) and I would like to have a dark mode to read the documentation when working late at night.

**Comment by Msuf123** [comment]
Can you help me remove this banner telling about function defination
![Screenshot_2024-09-17_04-23-19](https://github.com/user-attachments/assets/7faa3d01-0afb-4955-af8c-d000e21a3941)
