### ISSUE TITLE
Ruby-lsp is completely ignored with Ruby extension installed

### ISSUE THREAD

**Issue by tobico** [zed-industries/zed#17917]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Install the ruby extension
2. Install the ruby-lsp gem with `gem install ruby-lsp`
3. Configuring settings as follows (from the ruby extension docs):
```
{
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      }
    },
    "languages": {
      "Ruby": {
        "language_servers": ["ruby-lsp", "rubocop", "!solargraph", "..."]
      }
    }
  }
}
```
4. Open a ruby file.

No language server runs, and language hints are not available for the ruby file. There is no error message displayed anywhere, and opening logs with "open language server logs" shows only the option of solargraph and not ruby-lsp, with no output for solargraph.

### Environment

Zed: v0.152.4 (Zed)
OS: Linux Wayland fedora 40
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.1.6

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17022110/Zed.log)

</pre></details>

**Comment by vitallium** [comment]
@tobico Hi! Your configuration is not correct, there is no `languages` key setting under the `lsp` key. Can you try this configuration?

```jsonc
{
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      }
    }
  },
  "languages": {
    "Ruby": {
      "language_servers": ["ruby-lsp", "rubocop", "!solargraph", "..."]
    }
  }
}
```

**Comment by gottlike** [comment]
I have a similar problem, here is my config:

```json
{
  "languages": {
    "Ruby": {
      "language_servers": ["ruby-lsp", "!solargraph", "!rubocop", "..."],
      "format_on_save": "on"
    }
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false,
          "formatting": true
        },
        "formatter": "rubocop"
      }
    }
  }
}
```

And Zed has this error:

```
2024-09-17T15:05:15.261006+02:00 [INFO] starting language server "ruby-lsp", path: "/Users/erik/Desktop/Business/Altsson", id: 5
2024-09-17T15:05:15.26177+02:00 [ERROR] failed to start language server "ruby-lsp": ruby-lsp must be installed manually. Install it with `gem install ruby-lsp`.
2024-09-17T15:05:15.262009+02:00 [ERROR] server stderr: Some("")
2024-09-17T15:05:15.262228+02:00 [INFO] retrying installation of language server "ruby-lsp" in 1s
2024-09-17T15:05:16.269493+02:00 [INFO] About to spawn test binary
2024-09-17T15:05:16.270049+02:00 [WARN] test binary failed to launch
2024-09-17T15:05:16.270416+02:00 [WARN] test binary check failed
2024-09-17T15:05:16.27078+02:00 [INFO] beginning to reinstall server
2024-09-17T15:05:16.271191+02:00 [INFO] deleting server container
2024-09-17T15:05:16.272008+02:00 [ERROR] server container removal

Caused by:
    No such file or directory (os error 2)
2024-09-17T15:05:16.272429+02:00 [INFO] starting language server "ruby-lsp", path: "/Users/erik/Desktop/Business/Altsson", id: 6
2024-09-17T15:05:16.273413+02:00 [ERROR] failed to start language server "ruby-lsp": ruby-lsp must be installed manually. Install it with `gem install ruby-lsp`.
2024-09-17T15:05:16.273744+02:00 [ERROR] server stderr: Some("")
2024-09-17T15:05:16.27401+02:00 [ERROR] Hit 4 reinstallation attempts for "ruby-lsp"
```

So it very much looks like it's a PATH issue.. but I can't figure out how to debug this. Clearly it's not finding my "ruby-lsp" command (it works in my terminals).

**Comment by gottlike** [comment]
FYI, I found a workaround: https://github.com/zed-industries/zed/issues/10518#issuecomment-2355822311
 
Ugly and should be fixed somehow in Zed, but works for now.

**Comment by gottlike** [comment]
@mrnugget With the preview it works, thank you!

The "path" ist just the project path, not where "ruby-lsp" is located.

**Comment by mrnugget** [comment]
Yeah, sorry, I realized that after the fact.

**Comment by vitallium** [comment]
Glad to see that it finally worked! I will double-check everything and see if the documentation around that should be updated. Thank you all!

**Comment by vitallium** [comment]
Also, the `ruby-lsp` also has some documentation about activating it properly via various version managers - https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md I think we could link it in the Zed documentation.

**Comment by tobico** [comment]
> @tobico Hi! Your configuration is not correct, there is no `languages` key setting under the `lsp` key. Can you try this configuration?
> 
> ```js
> {
>   "lsp": {
>     "ruby-lsp": {
>       "initialization_options": {
>         "enabledFeatures": {
>           "diagnostics": false
>         }
>       }
>     }
>   },
>   "languages": {
>     "Ruby": {
>       "language_servers": ["ruby-lsp", "rubocop", "!solargraph", "..."]
>     }
>   }
> }
> ```

Thanks, that fixed it! I must have put the code in the wrong spot and not noticed.

Maybe it would be good to have a complete configuration example in a single block on the documentation at https://zed.dev/docs/languages/ruby to avoid mistakes when people are quickly trying to get set up.

**Comment by mrnugget** [comment]
Makes sense! I opened a PR here: https://github.com/zed-industries/zed/pull/17987

I'm closing this, let me know if we should reopen.
