### ISSUE TITLE
new keymap option: reveal_in_side_bar

### ISSUE THREAD

**Issue by tameraydin** [zed-industries/zed#17935]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to be able to assign a keymap to reveal the active file on the project sidebar (dock). (similar to `reveal_in_side_bar ` in SublimeText)

**Comment by SomeoneToIgnore** [comment]
That side bar with the files is called a project panel, and we're supposed to have that action available:
<img width="807" alt="image" src="https://github.com/user-attachments/assets/b8babdcd-83e8-4bac-968f-f1366091b807">

so all that's needed presumably is a custom keybinding.

**Comment by SomeoneToIgnore** [comment]
Closing this for now as I'm quite certain this is the thing requested.

**Comment by tameraydin** [comment]
@SomeoneToIgnore pardon my ignorance;
1) I'm currently using the latest version of Zed (0.152.4) - why I don't see the menu item ("Reveal In Project Panel") while having an active project opened and having a selected text (which we shouldn't need actually?). I can send a screenshot if you need to.
2) What is the command to be used for key binding (which is my main issue is about) - I could not find the relevant command in the default key bindings (so that I could use to map) 🤔

**Comment by SomeoneToIgnore** [comment]
1. It's a screenshot of a tab context menu, that's where that action is put only.
No text selection or anything buffer-related is relevant to this context menu.

2. `pane::RevealInProjectPanel`
We do not document these well alas, but you can derive any action name out of the command name:
<img width="570" alt="image" src="https://github.com/user-attachments/assets/5b1c9455-a127-4e17-9cb5-620e1b092c08">

as you can notice, `pane:` turns into `pane::`, and the rest is turned into UpperCamelCase.

**Comment by tameraydin** [comment]
That was insightful, thank you!
