### ISSUE TITLE
Ability to stop (SIGINT) and re run a task

### ISSUE THREAD

**Issue by louisnw01** [zed-industries/zed#17950]
### Check for existing issues

- [X] Completed

### Describe the feature

Many tasks will run indefinitely until they are manually stopped with CTRL+C. It would be great if there was a field in `tasks.json` which, on a re-run, would send SIGINT to the previous task before running the task again.

### If applicable, add mockups / screenshots to help present your vision of the feature

```json
[
    {
        "label": "run sever",
        "command": "yarn dev",
        "stop_on_rerun": true, // flag to stop the task when re-running
    }
]

```

**Comment by SomeoneToIgnore** [comment]
It's a bit more convoluted but is possible already, can you try adding
```
"allow_concurrent_runs": true,
"use_new_terminal": false
```
to your task and test?

The former says that reruns are ok to schedule even if the current task is running, and the latter says that it has to reuse the same terminal for that new thing that starts — which will drop the old task, effectively cancelling it.

**Comment by louisnw01** [comment]
> It's a bit more convoluted but is possible already, can you try adding
> 
> ```
> "allow_concurrent_runs": true,
> "use_new_terminal": false
> ```
> 
> to your task and test?
> 
> The former says that reruns are ok to schedule even if the current task is running, and the latter says that it has to reuse the same terminal for that new thing that starts — which will drop the old task, effectively cancelling it.

This does work, thanks!

**Comment by markuswustenberg** [comment]
It this documented somewhere in the official docs? I needed this as well (common use case for running a development server, for example) and only found the solution here.

**Comment by SomeoneToIgnore** [comment]
Both parameters are documented, but that particular combination is not anyhow highlighted in https://zed.dev/docs/tasks

That doc page is generated from https://github.com/zed-industries/zed/blob/aad3ed7f9135aac72527c10cf568fc13966bcb9b/docs/src/tasks.md?plain=1#L1 so a PR with more info could be added on top.

**Comment by markuswustenberg** [comment]
@SomeoneToIgnore thanks!

Before I go editing something I don't understand: `use_new_terminal` defaults to `false`, so setting just `allow_concurrent_runs` to `true` actually achieves the desired behavior.

It seems to be that the naming of the variables is a bit off, because it's not actually a concurrent run if it's in the same terminal, then the current task is stopped first (right?).

Would it make sense to change the naming? That would obviously be a breaking change, but could make the intended behavior more clear.

**Comment by SomeoneToIgnore** [comment]
The naming is somewhat odd indeed, the idea was in the fact that certain tasks may run concurrently (opening multiple terminal tabs) and some not.

I don't know if we want to break anything at this stage just for this small bit: after all, it's possible to achieve the desired behavior.

**Comment by markuswustenberg** [comment]
@SomeoneToIgnore what do you think of https://github.com/zed-industries/zed/pull/20539 ?

**Comment by SomeoneToIgnore** [comment]
Not sure, looks a bit confusing tbh as does not specify that another parameter value has to be set to a specific value too.

I would just add another ### -header in the docs, not in the json, wdyt?

**Comment by markuswustenberg** [comment]
For posterity, #20539 was merged and this is now in the docs at https://zed.dev/docs/tasks

<img width="779" alt="image" src="https://github.com/user-attachments/assets/3ffbf472-b9b5-4a75-a57e-cf4555c7c149">
