### ISSUE TITLE
"Failed to Load Image Invalid Padding" in R Kernel (REPL Ark)

### ISSUE THREAD

**Issue by abdullahahmed-dev** [zed-industries/zed#17956]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried to use R version 4.4.1 in Zed. Although I use R Studio, I wanted to use Zed because of its quick load times to get a mockup of the graph I am making. Zed is very fast and has excellent syntax support. I am planning to do nothing fancy, such as installing packages or checking environment variables, which I know won’t be supported. I am using the Ark Kernel for R as suggested in the Zed/REPL Docs. I don't know if it even loads the package. When I try to execute all the code at once it does nothing and gives errors. I don’t know if the problem is with the Ark Kernel or the R extension. The most important thing I want it to do is to at least show me an image of the plot I intend to make. I used different packages, including ggplot2 and meta, but ended up with the same error. Please fix this issue.

### Environment

Zed: v0.152.4 (Zed)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1678" alt="image" src="https://github.com/user-attachments/assets/7cea646a-3b36-4d13-ae74-3ff3be396763">
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/dcb96216-3569-48fa-883a-df0c93dc3013">
<img width="1678" alt="image" src="https://github.com/user-attachments/assets/c5889530-c51e-4887-bc6b-c89205b9c3be">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17032777/Zed.log)

</pre></details>

**Comment by notpeter** [comment]
These fixes will be available in today's Preview (v0.162.x) and Stable (v0.161.x) to be released later this afternoon.

**Comment by ivansigmund** [comment]
i have Zed Preview 0.162.0 and when i do plt.plot(x,y) plt.show(), i get 
<img width="318" alt="Screenshot 2024-11-14 at 13 29 15" src="https://github.com/user-attachments/assets/5032521c-4884-4cf5-b16a-d2e0f5107cac">

before updates the REPL was doing good
