### ISSUE TITLE
Flash nvim behavior for VIM mode

### ISSUE THREAD

**Issue by Benjamin-van-Heerden** [zed-industries/zed#17966]
### Check for existing issues

- [X] Completed

### Describe the feature

Coming from neovim, the thing I absolutely miss most is flash-nvim (https://github.com/folke/flash.nvim). It is by far the most effective way I have found in navigating, selecting and deleting code. I know this one probably wouldn't be easy, but I am opening a feature and keeping my fingers crossed.

**Comment by ConradIrwin** [comment]
Duplicate of #14801.

It's not impossible (we also have requests for easy motion etc.)
