### ISSUE TITLE
rust-analyzer does not work

### ISSUE THREAD

**Issue by bestgopher** [zed-industries/zed#17999]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I updated to latest zed, and rust-analyzer does not work anymore.

### Environment

Zed: v0.152.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/85cb5138-b79e-4e54-8225-e23e45bbc7f2)
Here no lsp launched.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
>  If applicable, attach your Zed.log file to this issue.

Pretty please? How are people supposed to debug this otherwise?

Also seems like a duplicate of https://github.com/zed-industries/zed/issues/17376

**Comment by bestgopher** [comment]
> > If applicable, attach your Zed.log file to this issue.
> 
> Pretty please? How are people supposed to debug this otherwise?

Ok, I will support the file tomorrow. I debuged it by myself and no useful messages found from logfile.

**Comment by SomeoneToIgnore** [comment]
I'd recommend also checking `main` as there were some improvements on that front yesterday.

**Comment by bestgopher** [comment]
@SomeoneToIgnore It works fine now. I don't known what happened. Thanks for your help.
