### ISSUE TITLE
Autocomplete for functions omits parenthesises with vtsls language server

### ISSUE THREAD

**Issue by s3bba** [zed-industries/zed#18014]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This [PR](https://github.com/zed-industries/zed/pull/17757) has introduced inconsistent behavior across language servers for JS/TS projects.
Using `vtsls` server functions no longer get completed with parenthesises and function argument. Eg.: `variable.functionName`
While if `typescript-language-server` is used we get expected behavior. Eg.: `variable.functionName(args)`

The first commit that has this issue is `02d5f320ad621e92cafaa7075f61e6496e12cd98`

### Environment

Zed: v0.154.0 (Zed Dev 2699fa8d4a10eb38445e0c5979dfb56a2193f949)
OS: Linux X11 arch unknown
Memory: 23.5 GiB
Architecture: x86_64
GPU: AMD Radeon VII (RADV VEGA20) || radv || Mesa 24.2.2-arch1.1

**Comment by vdegenne** [comment]
I have the same issue, I could swear I had autocompletion for functions with `ts_ls` before but even this server seems to ignore completion. So now I am not sure if that's an option to switch back on or something.

**Comment by JosephTLyons** [comment]
cc: @mrnugget

**Comment by s3bba** [comment]
Thanks! I can confirm that https://github.com/zed-industries/zed/pull/18259 has resolved this issue for me.
