### ISSUE TITLE
Add setting for custom Gitlab base URL

### ISSUE THREAD

**Issue by vmoeykens** [zed-industries/zed#18012]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed will automatically detect if the Git remote is a `github.com` or `gitlab.com` base URL and link commits to their appropriate location on the web. However, if the git repo remote is a custom Gitlab url such as `gitlab.mycompany.com` there is no way to utilize this feature. In theory as long as you specify it still follows Gitlab url conventions you could override the automatic detection and force it to use the base url of `gitlab.mycompany.com` and all the other url generation logic could stay the same.

**Comment by notpeter** [comment]
Thanks for filing this, you're right we do not currently support custom gitlab URLs.

It wouldn't be too tough to also detect urls like `gitlab.mycompany.com` and treat them as we do gitlab.com:

https://github.com/zed-industries/zed/blob/0f4ebdfbca721614f3cadafc3b44e4fbf099afda/crates/git_hosting_providers/src/providers/gitlab.rs#L28-L35

**Comment by collinmurch** [comment]
I implemented this on this PR but it was closed with little explanation. Can we look into this more? I've tested and confirmed my PR addresses the issue without limiting current functionality. Thanks!

https://github.com/zed-industries/zed/pull/19868

**Comment by MichaelBitard** [comment]
From what I can infer from the label removal/add, I think they want to move this in the enterprise edition of zed, hence the reason why our PRs got rejected.

Notpeter changed his comment from 'giving pointers on how to do this', to 'we don't support this' so I say we can give up on this feature for now (I prefer your PR BTW).

**Comment by notpeter** [comment]
Apologies for the poor communication. We want to add support for this but are opting for a different implementation than the PRs which have been opened. Thanks for your understanding.

**Comment by collinmurch** [comment]
Got it. Is there anything I can reference to track the implementation of this feature. I know of several people at my org who'd really enjoy this fix (we all use the same Gitlab self-hosted instance) and it seemed initially like a quick win.

I'd be happy to help contribute towards implementing this in a way that y'all desire if you give some pointers on what that would look like.

**Comment by maxdeviant** [comment]
> I implemented this on this PR but it was closed with little explanation. Can we look into this more? I've tested and confirmed my PR addresses the issue without limiting current functionality. Thanks!
> 
> Edit: it seems the same thing happened to @MichaelBitard who implemented an almost identical solution to me (earlier this month).
> 
> * [Add support for GitLab self-hosted instances #18427](https://github.com/zed-industries/zed/pull/18427)
> * [Allow for Gitlab self-hosted instance remote Git urls #19868](https://github.com/zed-industries/zed/pull/19868)

Apologies for not providing a better explanation sooner.

Both of the previous attempts relied on changing the interface of the `GitHostingProvider` trait in order to make this change, which was not desired.

There's a PR up here that adds in this functionality without modifying the `GitHostingProvider` trait: https://github.com/zed-industries/zed/pull/19909

**Comment by collinmurch** [comment]
Fantastic, appreciate the explanation @maxdeviant!

Funny, this was actually my initial implementation but I refactored it to avoid changing the `BTreeMap` construction with ` provider_registry.register_hosting_provider(Arc::new(Gitlab::new()));` or ` provider_registry.register_hosting_provider(Arc::new(Gitlab::default()));`.

**Comment by MichaelBitard** [comment]
Thanks for the explanations and the PR!

I have an issue with what have been done, I have some projects where we use gitlab subgroup, and your implementation does not work anymore.

Actually I think #19924 is responsible for the new bug. (should I open a new issue?)

I have the test case that fails: in `crates/git_hosting_providers/src/providers/gitlab.rs`

```rust

    #[test]
    fn test_parse_remote_url_given_https_url_with_subgroup() {
        let remote_url = "https://gitlab.my-enterprise.com/group/subgroup/zed.git";
        let parsed_remote = Gitlab::from_remote_url(remote_url).unwrap().parse_remote_url(remote_url).unwrap();

        assert_eq!(
            parsed_remote,
            ParsedGitRemote {
                owner: "group/subgroup".into(),
                repo: "zed".into(),
            }
        );
    }
```
I'm not sure what you want to do with the new implementation of RemoteUrl so I'm not confortable proposing a fix.

Regards,
Michaël

**Comment by maxdeviant** [comment]
> Thanks for the explanations and the PR!
> 
> I have an issue with what have been done, I have some projects where we use gitlab subgroup, and your implementation does not work anymore.
> 
> Actually I think #19924 is responsible for the new bug. (should I open a new issue?)
> 
> I have the test case that fails: in `crates/git_hosting_providers/src/providers/gitlab.rs`
> 
> ```rust
>     #[test]
>     fn test_parse_remote_url_given_https_url_with_subgroup() {
>         let remote_url = "https://gitlab.my-enterprise.com/group/subgroup/zed.git";
>         let parsed_remote = Gitlab::from_remote_url(remote_url).unwrap().parse_remote_url(remote_url).unwrap();
> 
>         assert_eq!(
>             parsed_remote,
>             ParsedGitRemote {
>                 owner: "group/subgroup".into(),
>                 repo: "zed".into(),
>             }
>         );
>     }
> ```
> 
> I'm not sure what you want to do with the new implementation of RemoteUrl so I'm not confortable proposing a fix.
> 
> Regards, Michaël

Thank you for the report and the reproduction!

I have a fix here: https://github.com/zed-industries/zed/pull/19962
