### ISSUE TITLE
ZED `0.153.5` preview release will not install.

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#18026]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As described in the title. Aarch64 Apple Silicon.

### Environment

```
Zed: v0.153.3 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64
```

### If applicable, attach your Zed.log file to this issue.

Auto update log:
```
2024-09-18T13:17:40.237294-05:00 [ERROR] auto-update failed: error:failed to mount: "hdiutil: attach failed - no mountable file systems\n"
2024-09-18T13:25:31.594985-05:00 [INFO] downloaded update. path:"/var/folders/mm/9lkm3vdn35z8n25m6rtj_h1r0000gq/T/zed-auto-updateTreSlA/Zed.dmg"
2024-09-18T13:25:34.315589-05:00 [ERROR] auto-update failed: error:failed to mount: "hdiutil: attach failed - no mountable file systems\n"
2024-09-18T13:28:55.596255-05:00 [INFO] downloaded update. path:"/var/folders/mm/9lkm3vdn35z8n25m6rtj_h1r0000gq/T/zed-auto-update4C89X9/Zed.dmg"
2024-09-18T13:28:59.291964-05:00 [ERROR] auto-update failed: error:failed to mount: "hdiutil: attach failed - no mountable file systems\n"
```

Additionally I have downloaded the latest previous from `zed.dev` releases page and it will not open `.dmg`, this seems as if the install file is corrupted. In the past I had similar issue the restart of the machine did help as system update for whatever reason interfered with update. This time the issue occurred before the system update (as well as after), where the machine restart did not help.

**Comment by krstp** [comment]
Tested on Intel as well and fails:
```
Zed: v0.153.4 (Zed Preview)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
Hi, I am in the process of building a v0.153.6 release to supersede v0.153.5.  We have been having some CI difficulties, please bear with us.

**Comment by notpeter** [comment]
This should be fixed. If you are still having issue. Please comment and I'll reopen.
Thanks for reporting.

**Comment by krstp** [comment]
Just tried to update from within ZED as well as downloading directly `0.153.6` from the website. The issue still persists :( Thanks for the quick update

**Comment by krstp** [comment]
Requesting to reopen

**Comment by notpeter** [comment]
I know this sounds patronizing, but can you please try restarting MacOS and try again?

Another user reported a similar issue where the hdiutil would complain and the DMG wouldn't mount and then it worked after restart. 🤞 

- https://github.com/zed-industries/zed/issues/16175#issuecomment-2287758990

**Comment by krstp** [comment]
Indeed the restart helped. Wondering what is so critical in 3rd party solution that requires system restart. Somewhat bizarre, especially having to need restart *nix system such as macos 🤔 

Either way, with latest latest release works now.
