### ISSUE TITLE
Anthropic link in AI Configuration panel for OpenAI

### ISSUE THREAD

**Issue by mileusna** [zed-industries/zed#18035]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In AI Configuration panel, in OpenAI section there is a link to Anthropic API instead OpenAI API link:

<img width="573" alt="Screenshot 2024-09-18 at 21 54 47" src="https://github.com/user-attachments/assets/30e94ce6-4103-4f84-9f27-1db4e8a35525">

### Environment

Zed: v0.152.4 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
This was fixed in main by:
- https://github.com/zed-industries/zed/pull/17675

I intend to cherry-pick it when we do our Zed Stable and Zed Preview releases tomorrow.
