### ISSUE TITLE
Nerd symbols not rendered correctly when using "Symbols Nerd Font" as fallback

### ISSUE THREAD

**Issue by mil-ad** [zed-industries/zed#18064]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have the following setting for my fonts:

```
  "buffer_font_family": "Cascadia Code",
  "buffer_font_fallbacks": ["Symbols Nerd Font"],
```

and I noticed that some Nerd glyphs are not rendered with the right height/width in the terminal:

<img width="278" alt="image" src="https://github.com/user-attachments/assets/71a341e1-bcf6-468e-a3b1-1a1b2d585117">

This is how they are rendered in Kitty and VS Code:
<img width="543" alt="image" src="https://github.com/user-attachments/assets/d5e1b017-60f4-4026-9aaa-0213f16a9b81">

Probably related to #4746

### Environment

Zed: v0.153.6 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
As a workaround `Cascadia Code` now ships a native font that includes Nerd Font symbols.

https://github.com/microsoft/cascadia-code/releases/tag/v2404.23

The ttf fonts you want in that download are:
```
CascadiaCodeNF.ttf
CascadiaCodeNFItalic.ttf
```

Then in your settings:
```json
  "buffer_font_family": "Cascadia Code NF",
```
