### ISSUE TITLE
CMD + / (Toggle Comments) doesn't comment out correctly anymore in TSX files

### ISSUE THREAD

**Issue by cpreston321** [zed-industries/zed#18070]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

create a new tsxfile:

```tsx
const TestComponent = () => {
  return (
    <div>
      <h1>Test Component</h1>
    </div>
  )
}
```

When using the toggle comments command within the tsx it does this now: 

```tsx
const TestComponent = () => {
  return (
    <div>
      // <h1>Test Component</h1>
    </div>
  )
}
```

vs the CORRECT way would be 

```tsx
const TestComponent = () => {
  return (
    <div>
      {/* <h1>Test Component</h1> */}
    </div>
  )
}
```

### Environment

Zed: v0.153.6 (Zed Preview)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/48b53cea-6626-4047-b244-e3d139de8708

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by gabwill10** [comment]
This is a duplicate issue for https://github.com/zed-industries/zed/issues/5291 currently has a first fix that has not yet been released.
