### ISSUE TITLE
Incorrect font rendering with question mark and dot symbol

### ISSUE THREAD

**Issue by avdept** [zed-industries/zed#18074]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When having question mark as last symbol before dot - there's some extra space added(see screenshot below)
Or use following code - `any_required_remote_fields?.empty?`

### Environment

Zed: v0.152.4 (Zed)
OS: macOS 15.0.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="496" alt="Screenshot 2024-09-19 at 17 43 32" src="https://github.com/user-attachments/assets/a0744372-ff95-41ca-bc71-e9e1e89fb8a2">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
What you are seeing is a ligature in the default Zed Plex Mono font.
https://github.com/user-attachments/assets/7c4c8c18-bf6b-4c70-8f1f-d6dc82faffe4

You can disable ligatures by adding the following into your settings:
```
  "buffer_font_features": {
    "calt": false
  }
```

Or by switching to a different font 

See: https://zed.dev/docs/configuring-zed#buffer-font-features

**Comment by avdept** [comment]
Nice, thanks for explaining!
