### ISSUE TITLE
Inconsistent Rust syntax highlighting of `enum_variant`

### ISSUE THREAD

**Issue by xpe** [zed-industries/zed#18080]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Summary**: In the example below, the syntax tree knows that `A` is an `enum_variant` but nevertheless colors it the same as `Q` a constant identifier.

```rust
struct XY;

enum Foo { A, Bee }

const Q_Y: u8 = 16;
```

<img width="673" alt="image" src="https://github.com/user-attachments/assets/b9364e52-1046-4a61-8c87-09bade5991cc">

### Environment

Zed: v0.153.6 (Zed Preview)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
We do not account for enclosing scope when syntax highlighting, as that information is not always available; take `Foo::A` as an example; all tree-sitter can infer about this syntax is that it is a scoped_identifier.
There's a tracking issue for adding support for a LSP feature that would help us in these ambiguous cases (e.g. by answering questions such as `is this identifier an enum variant?`):
https://github.com/zed-industries/zed/issues/7450

Closing in favor of that one, but thank you nonetheless for filling this issue out.
