### ISSUE TITLE
Zed Not Opening/Building On Windows 11: error: failed to run custom build command for `wasmtime-c-api-impl v24.0.0

### ISSUE THREAD

**Issue by anay-208** [zed-industries/zed#18084]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Run `cargo run`
2. Wait for a few mins

### Environment

Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎31-‎07-‎2023
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

The folder was empty inside `%LOCALAPPDATA%\Zed\logs`, however, I'm sharing command logs
<details><summary>Zed.log</summary><pre>

Anay@DESKTOP-QHKT0CQ MINGW64 ~/documents/zed (main)
$ RUST_BACKTRACE=1 cargo run
   Compiling cranelift-wasm v0.111.0
   Compiling git2 v0.19.0
   Compiling release_channel v0.1.0 (C:\Users\Anay\documents\zed\crates\release_channel)
   Compiling wasmtime-c-api-impl v24.0.0
   Compiling lazy_static v1.5.0
   Compiling schannel v0.1.23
   Compiling tree-sitter v0.23.0
   Compiling serde_json_lenient v0.2.1
   Compiling der v0.7.9
   Compiling zstd-sys v2.0.13+zstd.1.5.6
   Compiling webpki v0.22.4
   Compiling concurrent-queue v2.5.0
error: failed to run custom build command for `wasmtime-c-api-impl v24.0.0`                                                                                                                                    
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Anay\documents\zed\target\debug\build\wasmtime-c-api-impl-df457f5e0ddcf409\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=cmake/features.cmake
  cargo:rerun-if-changed=cmake/install-headers.cmake
  cargo:rerun-if-changed=include

  --- stderr
  thread 'main' panicked at C:\Users\Anay\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmtime-c-api-impl-24.0.0\build.rs:41:33:
  failed to spawn `cmake`: Error { kind: NotFound, message: "program not found" }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
     1: core::panicking::panic_fmt
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
     2: core::result::unwrap_failed
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\result.rs:1679
     3: core::result::Result<T,E>::expect
     4: alloc::raw_vec::RawVec<T,A>::try_allocate_in
     5: core::ops::function::FnOnce::call_once
     6: std::ffi::os_str::<impl core::convert::AsRef<std::ffi::os_str::OsStr> for alloc::string::String>::as_ref
     7: std::rt::lang_start::{{closure}}
     8: std::rt::lang_start_internal::closure$2
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
     9: std::panicking::try::do_call
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:557
    10: std::panicking::try
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:521
    11: std::panic::catch_unwind
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panic.rs:350
    12: std::rt::lang_start_internal
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
    13: std::rt::lang_start
    14: main
    15: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    16: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    17: BaseThreadInitThunk
    18: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
                                                           

</pre></details>

**Comment by SomeoneToIgnore** [comment]
> thread 'main' panicked at C:\Users\Anay.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmtime-c-api-impl-24.0.0\build.rs:41:33:

> failed to spawn cmake: Error { kind: NotFound, message: "program not found" }

**Comment by notpeter** [comment]
[Windows development docs](https://zed.dev/docs/development/windows#dependencies) reflect the need for cmake.

https://github.com/zed-industries/zed/blob/28a54ce122fdd5efb2e23cc77a5efab78c07061c/docs/src/development/windows.md#L25

**Comment by anay-208** [comment]
I already have it installed, here are the updated logs:
```
Anay@DESKTOP-QHKT0CQ MINGW64 ~/documents/zed (main)
$ rustup target add wasm32-wasip1
info: component 'rust-std' for target 'wasm32-wasip1' is up to date

Anay@DESKTOP-QHKT0CQ MINGW64 ~/documents/zed (main)
$ cargo run
   Compiling wasmtime-cranelift v24.0.0
   Compiling git v0.1.0 (C:\Users\Anay\documents\zed\crates\git)
   Compiling wasmtime-c-api-impl v24.0.0
   Compiling serde_json_lenient v0.2.1
   Compiling prost v0.9.0
   Compiling wasmtime-c-api-macros v24.0.0
   Compiling tree-sitter-json v0.23.0
   Compiling rustls v0.20.9
   Compiling winapi v0.3.9
   Compiling spin v0.5.2
   Compiling untrusted v0.7.1
   Compiling spki v0.7.3
error: failed to run custom build command for `wasmtime-c-api-impl v24.0.0`

Caused by:
  process didn't exit successfully: `C:\Users\Anay\documents\zed\target\debug\build\wasmtime-c-api-impl-df457f5e0ddcf409\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=cmake/features.cmake
  cargo:rerun-if-changed=cmake/install-headers.cmake
  cargo:rerun-if-changed=include

  --- stderr
  thread 'main' panicked at C:\Users\Anay\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmtime-c-api-impl-24.0.0\build.rs:41:33:
  failed to spawn `cmake`: Error { kind: NotFound, message: "program not found" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
                                                                                                                                                                                                               
Anay@DESKTOP-QHKT0CQ MINGW64 ~/documents/zed (main)
$
```

**Comment by SomeoneToIgnore** [comment]
Is it in your PATH? What does `cmake` command output in that same terminal?

**Comment by anay-208** [comment]
`cmake` command not found

```
Anay@DESKTOP-QHKT0CQ MINGW64 ~/documents/zed (main)
$ cmake
bash: cmake: command not found
```

**Comment by SomeoneToIgnore** [comment]
Welp, you have not installed it.

**Comment by anay-208** [comment]
And few days ago, It was working completely fine

**Comment by SomeoneToIgnore** [comment]
A few days ago, there was no cmake dependency in our source tree, it had been introduced recently in https://github.com/zed-industries/zed/commit/bc5ed1334ff019e026cbf7a6bbad4a8c2c5d68df

**Comment by anay-208** [comment]
Got it, Installing it now, thanks
