### ISSUE TITLE
Zed Preview 0.153.6 Remote Requiress GLIBC 2.35

### ISSUE THREAD

**Issue by TTDRosen** [zed-industries/zed#18088]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the latest nightly zed on an ubuntu 20.04 system I see the following error reported by my local Zed instance.

```
failed to run command: .local/zed-remote-server-preview: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by .local/zed-remote-server-preview)
.local/zed-remote-server-preview: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by .local/zed-remote-server-preview)
.local/zed-remote-server-preview: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by .local/zed-remote-server-preview)
.local/zed-remote-server-preview: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by .local/zed-remote-server-preview)
```

On previous versions of nightly I was able to use the remote development feature without issue.

#### On remote system
```
~ > /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.16) stable release version 2.31.
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 9.4.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
```

```
~ > uname -a
Linux yyz-lab-207 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
````

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
See https://github.com/zed-industries/zed/pull/17643 for more context: GitHub removed all Linux ARM runners with Ubuntu 20 and we cannot ship binaries with older libc that easy anymore.

Ubuntu 20.04 EOL is 23 April 2025n which is ~6 months so it makes not much sense for us to keep something more complex in CI for 6 months only.

**Comment by TTDRosen** [comment]
Thanks for the reply! This is an x86 based system, which I'm unfortunately going to be stuck using for the next 6 months 😅.  But I imagine that note in the linked issue about the new 2.35 requirement is what's catching me here.

Any insight into if getting around this problem by building on a more up to date system and statically linking to musl would cause more trouble than it's worth?

**Comment by notpeter** [comment]
The note in the [0.152.3 changelog](https://zed.dev/releases/stable/0.152.3) reflect the move Ubuntu 22.04 for the ARM runners was correct.

Separately this week we moved our Linux x86 runners to Ubuntu 22.04 as well in https://github.com/zed-industries/zed/commit/d3d3a093b4a757f1e82cd870a7f9e3cbee9ae933

This was unintentionally missing from the Release Notes in today's releases of Preview/Stable.  I've updated the [v0.153.6](https://github.com/zed-industries/zed/releases/tag/v0.153.6) [v0.154.0-pre](https://github.com/zed-industries/zed/releases/tag/v0.154.0-pre).

**Comment by venkatb-zelar** [comment]
First of all, thank you for this tool. I liked it for the short period i could use.

My journey with Zed:
- I had to wait so long because zed was only available on Mac first
- As soon as it's available on Linux, it didn't work as i was using Ubuntu 20.x
- After trying numerous workarounds, finally there was a solution
- After customising the editor for my liking and just about to be productive. I'm hit with this error

I'd at least recommend you to document(not just changelog), what are the supported OSes. Thank you!

**Comment by notpeter** [comment]
This is an issue with Redhat and Amazon Linux as well. Ideally we could setup a CI build environment where we were linking against an older glibc but for the moment we're using the runners we have available to us.

I'd be happy to review PRs which add references to which Linux Distro versions are explicitly supported/unsupported, I think it's an area where we could certainly improve. Thanks

**Comment by morganrivers** [comment]
Perhaps this is useful to others who have a remote server with an older glibc version (it appears Ubuntu 20.04 has GLIBC_2.31 at latest?): my temporary resolution to this was to build from source on the remote server after cloning `https://github.com/zed-industries/zed/blob/v0.153.5-pre`, manually connecting to the remote, and running `cargo run -- --dev-server-token <server token provided>`

**Comment by mskonovalov** [comment]
Would be nice to have support for Ubuntu 20 back

**Comment by notpeter** [comment]
Working on it.
- https://github.com/zed-industries/zed/pull/18442

**Comment by notpeter** [comment]
An update: I merged #18442 and got a Nightly built with and it's working.
Planning on pushing a Hotfix for stable and Preview tomorrow to restore Ubuntu 20.04 and only require glibc >= 2.31 for official binaries.

I've also done some additional work which should make it possible to build binaries (via containers) to further lower the requirement to glibc >= 2.28 which would also enable RedHat 8.x and clones (Rocky Linux 8, CentOS Stream 8, Amazon Linux 2023, Oracle Linux 8, AlmaLinux 8) on both aarch64 and x86_64 if there is sufficient demand for such binaries.

- https://github.com/zed-industries/zed/pull/18480

**Comment by mskonovalov** [comment]
Awesome :)
Is there a way to download nightly build?
When I try https://zed.dev/releases/nightly I get HTTP500

**Comment by notpeter** [comment]
This is out in Preview and Stable now.  Apologies for all those impacted.
