### ISSUE TITLE
New Macbook wont open Zed - Anybody getting this?

### ISSUE THREAD

**Issue by roger-rangel** [zed-industries/zed#18093]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Screenshot 2024-09-19 at 11 51 40](https://github.com/user-attachments/assets/9eb4fcbc-c9fd-46c6-9352-88b7c65e157b)

### Environment

I just downloaded Zed for apple silicon version and it wont open

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
> Check for existing issues

There's been a bunch of issues on the topic: https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+permission+denied

E.g. https://github.com/zed-industries/zed/issues/9805
For the time being, you need to change the folder permissions, e.g. as described in https://github.com/zed-industries/zed/issues/9805#issuecomment-2091387744

Closing this as a duplicate.
