### ISSUE TITLE
cursor_shape: removing setting doesn't restore the default (bar) value

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/zed#18119]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- open settings and change the `cursor_shape`, for eg add `"cursor_shape": "block"` and save
- delete the previously added line and save again

The cursor shape will still be `block`: it should be set to the default one: `bar`.

### Environment

Zed: v0.154.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

In the following video, the cursor shape is at the start set to the default (bar) value. I then change it to `block` and save: it's being updated as expected. But then I delete the setting, save, and the shape is still set to `block`.

https://github.com/user-attachments/assets/e3978b0f-343f-4211-a317-b2a30989c445

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I believe this may be a regression related to:
- https://github.com/zed-industries/zed/pull/17934

CC: @mrnugget
