### ISSUE TITLE
When using zed on my computer, the keyboard fails. 

### ISSUE THREAD

**Issue by Grace-H7** [zed-industries/zed#18137]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't know what settings have been changed. zed can't edit. Except for the letter key that can be typed, other things such as esc, backspace, space, enter, etc. are invalid. I don't know what caused it, and reinstallation is also invalid.

### Environment

my computer：M1mac 
mem：16g
os：15.1

### If applicable, attach your Zed.log file to this issue.

[issue.txt](https://github.com/user-attachments/files/17076151/issue.txt)

**Comment by JosephTLyons** [comment]
Hey @Grace-H7, what does your `keymap.json` file look like (command palette > `zed: open keymap`)?

**Comment by Grace-H7** [comment]
> Hey @Grace-H7, what does your `keymap.json` file look like (command palette > `zed: open keymap`)?

Thanks for your reply. Based on your suggestion, I opened the settings and found that the base_keymap had been changed to none. After modifying it, everything is working normally now. Thank you for your support.
