### ISSUE TITLE
Ignore `vertical_scroll_margin` when the user moves the cursor using the mouse.

### ISSUE THREAD

**Issue by filippogallizia** [zed-industries/zed#18148]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, when moving the cursor with the mouse, the `vertical_scroll_margin` is applied, causing the page to scroll. This results in the cursor no longer aligning with the mouse pointer after clicking, which can feel unintuitive.

Requested Behavior:

Disable the vertical_scroll_margin when the user moves the cursor by clicking with the mouse.
The vertical_scroll_margin should still be respected when using keyboard navigation (e.g., arrow keys), but not for mouse interactions.

I come from JetBrains editor which behave like this and I think it's better.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/user-attachments/assets/d1771a6a-0861-4f67-b22c-a4378556acd4

**Comment by kuglee** [comment]
Just wanted to report this. It would be nice to have the option to disable this. Coming from Intellij with IdeaVim I really miss this feature.
