### ISSUE TITLE
Crash when pressing control on macos when globe and control are inverted

### ISSUE THREAD

**Issue by plichard** [zed-industries/zed#18159]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I had control and globe inverted, and whenever I pressed control (remapped to globe), Zed would instantly crash with the same error message as the one in the logs (was running it with `--foreground`).
I cannot reproduce it anymore unfortunately since removing and reapplying the remapping.

### Environment

Zed: v0.154.0 (Zed Preview)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-15T11:17:34.952546+02:00 [ERROR] {
  "thread": "main",
  "payload": "panic in a function that cannot unwind",
  "location_data": {
    "file": "library/core/src/panicking.rs",
    "line": 221
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_nounwind_fmt",
    "core::panicking::panic_nounwind",
    "core::panicking::panic_cannot_unwind",
    "gpui::platform::mac::window::handle_key_event",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "<gpui::app::App>::run::<zed::main::{closure#3}>",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.153.2",
  "release_channel": "Zed Preview",
  "os_name": "macOS",
  "os_version": "14.6.1",
  "architecture": "aarch64",
  "panicked_on": 1726391854952,
  "installation_id": "60390221-cdaf-4bb0-a0a9-ba7c97c31fa7",
  "session_id": "ab2f84fd-fed0-41b0-ae7a-bd938acf4fab"
}
</pre></details>

**Comment by notpeter** [comment]
I think this is likely the same issue as:
- https://github.com/zed-industries/zed/issues/18139

The issue randomly stopped happening for them too.
I'm going to close as non-reproducible, but happy to reopen if anyone has this issue in the future.

Thanks for reporting @plichard I'll keep my eye out for this in the future.
