### ISSUE TITLE
Setting up a comment line break

### ISSUE THREAD

**Issue by yanballas** [zed-industries/zed#18176]
### Check for existing issues

- [ ] Completed

### Describe the feature

Hello everybody! I ran into a problem - if I move a line with a comment using enter, the next line also starts with a comment. How can I disable this feature?
![Снимок экрана от 2024-09-21 11-41-32](https://github.com/user-attachments/assets/7f530bab-ac98-4863-82cb-0f57fc608015)

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/015e873f43d8be87bf6e363f1989c2b5ae977a76/assets/settings/default.json#L502-L503

**Comment by SomeoneToIgnore** [comment]
Also, cmd-enter works.

**Comment by yanballas** [comment]
> https://github.com/zed-industries/zed/blob/015e873f43d8be87bf6e363f1989c2b5ae977a76/assets/settings/default.json#L502-L503

thanks my friend!!!
