### ISSUE TITLE
zed Extension develop, failed to build extension 

### ISSUE THREAD

**Issue by cfanbo** [zed-industries/zed#18174]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Extension Tutorials: https://github.com/zed-industries/zed/tree/main/extensions/slash-commands-example

IDE cann't load Extension from local disk.  https://zed.dev/docs/extensions/developing-extensions#developing-an-extension-locally
```
# zed -v
Zed 0.153.6 – /Applications/Zed.app

# rustup target list | grep wasm32-wasi
wasm32-wasi (installed)
wasm32-wasip1 (installed)
wasm32-wasip1-threads
```

### Environment

# OS
macOS MONTEREY
version 12.7.6
MacBook Pro (Retina, 13-inch, Early 2015)
Processor: 2.7 GHz Dual-Core Intel Core i5

# rustup
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.81.0 (eeb90cda1 2024-09-04)`

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

# tail -f ~/Library/Logs/Zed/Zed.log
2024-09-21T14:08:47.138932+08:00 [INFO] compiling Rust extension /Users/sxf/workspace/ai-translate/helloworld
2024-09-21T14:08:47.493748+08:00 [INFO] compiling Rust crate for extension /Users/sxf/workspace/ai-translate/helloworld
2024-09-21T14:08:48.266968+08:00 [ERROR] failed to compile Rust extension

Caused by:
    failed to build extension    Compiling serde v1.0.210
       Compiling wit-bindgen-rt v0.22.0
       Compiling memchr v2.7.4
       Compiling ryu v1.0.18
    error[E0463]: can't find crate for `core`
      |
      = note: the `wasm32-wasip1` target may not be installed
      = help: consider downloading the target with `rustup target add wasm32-wasip1`

    For more information about this error, try `rustc --explain E0463`.
    error: could not compile `wit-bindgen-rt` (lib) due to 1 previous error
    warning: build failed, waiting for other jobs to finish...
    error: could not compile `ryu` (lib) due to 1 previous error
    error: could not compile `memchr` (lib) due to 1 previous error
    error[E0463]: can't find crate for `std`
      |
      = note: the `wasm32-wasip1` target may not be installed
      = help: consider downloading the target with `rustup target add wasm32-wasip1`

    error: could not compile `serde` (lib) due to 1 previous error
</pre></details>

**Comment by bestgopher** [comment]
Try to build your extension with cargo directly: `cargo build --target=wasm32-wasi`.

**Comment by cfanbo** [comment]
> Try to build your extension with cargo directly: `cargo build --target=wasm32-wasi`.

# cargo build --target=wasm32-wasi
   Compiling serde v1.0.210
   Compiling wit-bindgen-rt v0.22.0
   Compiling serde_json v1.0.128
   Compiling itoa v1.0.11
   Compiling bitflags v2.6.0
warning: the `wasm32-wasi` target is being renamed to `wasm32-wasip1` and the `wasm32-wasi` target will be removed from nightly in October 2024 and removed from stable Rust in January 2025

error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasi` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasi`

For more information about this error, try `rustc --explain E0463`.
warning: `itoa` (lib) generated 1 warning
error: could not compile `itoa` (lib) due to 1 previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
warning: `wit-bindgen-rt` (lib) generated 1 warning (1 duplicate)
error: could not compile `wit-bindgen-rt` (lib) due to 1 previous error; 1 warning emitted
warning: `bitflags` (lib) generated 1 warning (1 duplicate)
error: could not compile `bitflags` (lib) due to 1 previous error; 1 warning emitted
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasi` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasi`

warning: `serde` (lib) generated 1 warning (1 duplicate)
error: could not compile `serde` (lib) due to 1 previous error; 1 warning emitted

**Comment by bestgopher** [comment]
Apologies for the confusion. Zed has switched to wasm32-wasip1 as the WebAssembly target (reference: [Zed PR](https://github.com/zed-industries/zed/pull/17440/files)). Please run cargo build --target=wasm32-wasip1 locally to verify if it compiles successfully.

**Comment by cfanbo** [comment]
> `cargo build --target=wasm32-wasip1`

$ cargo build --target=wasm32-wasip1
   Compiling wit-bindgen-rt v0.22.0
   Compiling serde v1.0.210
   Compiling memchr v2.7.4
   Compiling itoa v1.0.11
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasip1` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasip1`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `wit-bindgen-rt` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `itoa` (lib) due to 1 previous error
error: could not compile `memchr` (lib) due to 1 previous error
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasip1` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasip1`

error: could not compile `serde` (lib) due to 1 previous error

**Comment by bestgopher** [comment]
I apologize, but I'm not sure why this happened. However, I am confident that it was not caused by Zed.

**Comment by notpeter** [comment]
This works for me on aarch64 with MacOS Sonoma as expected.
Hopefully this isn't an Monterey or Intel specific issue.

Apologies if this sounds patronizing, but could you please try uninstalling everything related to rust and reinstalling. E.g.:
```
rustup self uninstall
brew uninstall rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup target add wasm32-wasip1

cd extensions/slash-commands-example
cargo build --target=wasm32-wasip1
```

**Comment by cfanbo** [comment]
> This works for me on aarch64 with MacOS Sonoma as expected. Hopefully this isn't an Monterey or Intel specific issue.
> 
> Apologies if this sounds patronizing, but could you please try uninstalling everything related to rust and reinstalling. E.g.:
> 
> ```
> rustup self uninstall
> brew uninstall rust
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> rustup target add wasm32-wasip1
> 
> cd extensions/slash-commands-example
> cargo build --target=wasm32-wasip1
> ```

Thank you for your reply
I have tested this solution and the result is still the same. 

**I suspect it may be related to my OS version， it is too old **

**Comment by bestgopher** [comment]
@cfanbo  If possible, you could share your code on github, I am pleased to download it and try to compile it.

**Comment by cfanbo** [comment]
> @cfanbo If possible, could you share your code on GitHub? I would be happy to download it and try to compile it.

https://github.com/cfanbo/zed-ai-translate

**Comment by bestgopher** [comment]
![image](https://github.com/user-attachments/assets/cfd932ff-8a4d-49c4-8b32-496c9b6cdf96)

**Comment by cfanbo** [comment]
> ![image](https://private-user-images.githubusercontent.com/36840497/370146385-cfd932ff-8a4d-49c4-8b32-496c9b6cdf96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTY5ODUsIm5iZiI6MTcyNzE1NjY4NSwicGF0aCI6Ii8zNjg0MDQ5Ny8zNzAxNDYzODUtY2ZkOTMyZmYtOGE0ZC00OWM0LThiMzItNDk2YzliNmNkZjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA1NDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjEyMWVmZTM1NjcxZTA4NjAzMDczYmYxMDUyZjVmNzc4MGU2NWQxMDE3YTkwNDFlOGI5MzM0NjA3YjQ1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.34pzcXawi8rotcK7YeS1AHZdITExC6xk-1WjBGbfWrc)

What is the OS version?
> The code runs normally on Ubuntu armm64, but fails to execute on macOS 12 amd64。

**Comment by cfanbo** [comment]
OS Version
![image](https://github.com/user-attachments/assets/80a21c1e-982b-4042-8e38-730924d86a1b)

**Comment by bestgopher** [comment]
Zed: v0.153.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by AnkushinDaniil** [comment]
Try [this](https://stackoverflow.com/a/75676790/22845956)
I had the same issue.

**Comment by cfanbo** [comment]
Thank you very much！！！

**Comment by stalexxx** [comment]
I faced this when I had one more rust install via homebrew
