### ISSUE TITLE
Add read-only mode

### ISSUE THREAD

**Issue by zzhaolei** [zed-industries/zed#18197]
### Check for existing issues

- [X] Completed

### Describe the feature
The most classic scenario is: `jump to source code`. Don't want to accidentally change the contents of files outside your workspace

### If applicable, add mockups / screenshots to help present your vision of the feature
Similar to  https://github.com/Microsoft/vscode/issues/4873.

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/5105
