### ISSUE TITLE
Cannot write @ on a Hungarian keyboard since I updated to 0.154.0 preview

### ISSUE THREAD

**Issue by FightMan01** [zed-industries/zed#18196]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the Hungarian keyboard you write the @ symbol with Option + Q. But when I press it in Zed nothing happens since the last update.

### Environment

Zed: v0.154.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/2ac0b75c-5f1a-44df-ad46-501c2b2d0a47

**Comment by MrSubidubi** [comment]
The same issue occurs for QWERTZ-layouts, see my issue: #18104 .

You have to manually remove the binding for `Editor::rewrap` in your `keymap.json`:

```json
[
{
    "bindings": {
        "alt-q": null
    }
},
...
]
```

Do you wish me to update my issue so that it reflects other keyword-layouts are also affected? That way we can keep the discussion at one place.

**Comment by FightMan01** [comment]
Thank you, I somehow missed your issue. Yes, keep the discussion at one place, I will close mine.

**Comment by MrSubidubi** [comment]
No worries. I updated my issue to reflect that your keyboard-layout is also affected.
