### ISSUE TITLE
Zed removes spaces from diff/patch files upon saving even though ``format_on_save`` is set to off

### ISSUE THREAD

**Issue by EDLLT** [zed-industries/zed#18200]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a diff or a patch file which contains newlines with spaces.
Example:
```
Disable cargo commands
\/ There is a space here(upon saving, Zed removes it which messes up diff and patch files)
 
     meson.add_install_script(
         'build-aux/meson_post_install.py',
```

Then save
Zed will remove the space

### Environment

Ubuntu 24.04
Zed version: 0.153.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Irrelevant

```
### If applicable, attach your Zed.log file to this issue.

// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette
{
  "assistant": {
    "default_model": {
      "provider": "zed.dev",
      "model": "claude-3-5-sonnet-20240620"
    },
    "version": "2"
  },
  "base_keymap": "VSCode",
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "ui_font_size": 23,
  "buffer_font_size": 20,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark"
  },
  "format_on_save": "off"
}
```

**Comment by teohhanhui** [comment]
Removing trailing whitespace is also a no-no for other languages like YAML and Markdown.

**Comment by notpeter** [comment]
@teohhanhui It is true that you can create YAML, Markdown (and even Handlebars) files where trailing whitespace is significant, I think the default of `remove_trailing_whitespace` for these is correct. In most editor configurations it is literally invisible "code".

I feel strongly that intentionally relying on trailing whitespace to express programmer intent is anti-social behavior.
(This is my personal opinion, not necessarily that of my employer).

It is possible with both YAML and Markdown to have a construction where trailing whitespace is not required.  With the rare exception of a Markdown/YAML test cases (test cases should always be excluded from auto-formatting), [PEP20](https://peps.python.org/pep-0020/#the-zen-of-python) are words to live by: 

```yaml
# implicit
obj1: 
  header: |
    Trailing whitespace is bad.  
    No, it's actually the worst.

# explicit
obj2:
  header: "Trailing whitespace is bad.  \n\
    No, it's actually the worst.\n"
```

```md
# implicit
I hate paragraph tags but want a linebreak.  
Because I hate my coworkers.

# explicit
I hate paragraph tags but want a linebreak.
<br/>
Because I hate my coworkers.
```

Diff has a good excuse: it was invented in 1974.  And so in addition to maintaining backwards compatibility (excellent) there is no workaround for expressing trailing whitespace. As a hilariously recursive example, you can't express a patch for removing trailing whitespace without your diff file having trailing whitespace.

YAML and Markdown have no such excuse (created in 2001 and 2004 respectively). If you hold a conflicting opinion you are free to add the following to your settings for your own private repos and continue using Zed, I just feel sorry for anyone with whom you need to collaborate:
```json
  "languages": {
    "YAML": {
      "remove_trailing_whitespace_on_save": false
    },
    "Markdown": {
      "remove_trailing_whitespace_on_save": false
    }
  }
```

**Comment by teohhanhui** [comment]
Well, your personal opinions aside, that's how YAML and Markdown have been designed, and we'd do best to follow the spec, or we'll risk breaking many things...

**Comment by notpeter** [comment]
Apologies for coming on so strong. I've spent many hours considering default settings and clearly have strong feelings on the topic.

In Zed `remove_trailing_whitespace_on_save` defaults to true:
https://github.com/zed-industries/zed/blob/f73a076a636972a3b12802378642860b74b08a89/assets/settings/default.json#L516-L518

You believe `"we'd do best to follow the spec"`, but if Zed adopted the behavior you've proposed, any project that wanted a policy of "no trailing whitespace" (a great policy, btw) would have to add the following confusing boilerplate to every repo's in a `.zed/settings.json` file: 

```json
{
  "remove_trailing_whitespace_on_save": true
  "Languages"
    "YAML": {
      "remove_trailing_whitespace_on_save": true
    },
    "Markdown": {
      "remove_trailing_whitespace_on_save": true
    }
  }
}
```

Whereas now it's just Zed's default behavior.

**Comment by teohhanhui** [comment]
> any project that wanted a policy of "no trailing whitespace" (a great policy, btw) would have to add the following confusing boilerplate to every repo's in a .zed/settings.json file

No, they'd just use the industry standard that is EditorConfig. None of this should be a problem once EditorConfig support is implemented. Our discussion here should only be the default in the absence of EditorConfig files, which would not be any reasonable project out there.
