### ISSUE TITLE
Terminal panel won't open with ctrl+j when docked in a diffrent position

### ISSUE THREAD

**Issue by khalil-cheddadi** [zed-industries/zed#18204]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

as the title says, the keyboard shortcut to toggle the integrated terminal Ctrl+j wont work when the panel is docked right or left (non default position)

### Environment

Zed: v0.153.6 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 7.5 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (ICL GT1) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
> keyboard shortcut to toggle the integrated terminal Ctrl+j wont

This is incorrect: the keybinding is not for toggling the **terminal** but the **bottom dock**.

https://github.com/zed-industries/zed/blob/015e873f43d8be87bf6e363f1989c2b5ae977a76/assets/keymaps/default-linux.json#L374-L376

So it works as expected.
