### ISSUE TITLE
[documentation/website] Change recommended way to install zed on Linux

### ISSUE THREAD

**Issue by arnaudvergnet** [zed-industries/zed#18215]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**This is not an issue with the zed editor in itself, but with the website. If this is not the place to report such issues, please direct me to the right one.**

The [current download page](https://zed.dev/download) ([also here](https://zed.dev/docs/linux#other-ways-to-install-zed-on-linux)) shows the command `curl -f https://zed.dev/install.sh | sh` as the recommended way to install Zed.

While this works, this is a bad practice to make people execute random scripts from the internet. People should never have to run such commands to install software as it makes it easier for malware developers to run phishing attacks.

It would be a lot better to recommend a cross-distribution systems like Flatpack or the zip file.

### Environment

/

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/14498#issuecomment-2228850507

> Just below your screen-shot is a link that says "For other installation options and help troubleshooting [read the guide](https://zed.dev/docs/linux)".
> 
> We don't currently have plans to promote a different primary installation mechanism, as this one works the most reliably for the most users. Once we get to a point where a majority of linux users can install via their systems package managers (which is a long road to travel) we will likely switch to recommending that instead (as this can help us ensure that the dependencies we need are available).
> 
> If you'd like to help with that effort, see https://zed.dev/docs/development/linux#notes-for-packaging-zed.
