### ISSUE TITLE
ClangD & .clangd file

### ISSUE THREAD

**Issue by skhaz** [zed-industries/zed#18226]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have an `.clangd` with some configuration on root of my project, but it seems that clangd bunded "with" zed is not reading it/

### Environment

Zed: v0.153.6 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

N/A

**Comment by jansol** [comment]
How does this manifest? Is the root of your project also a root of your Zed workspace?

**Comment by skhaz** [comment]
It is the root of my project on Zed root workspace

**Comment by maxbrunsfeld** [comment]
@skhaz Do you know if there is some configuration that we need to send to clangd during initialization to get it to read that file?

**Comment by skhaz** [comment]
@maxbrunsfeld, no. When I was using VSCode, I had a plugin to handle C++ projects.

This is the same project as I was using on VSCode, I am using Zed for all.

I think, Zed should tell the location of the file to clangd, becase some CMake based projects have a build dir.

**Comment by jansol** [comment]
clang-format and clangd are two different tools that do very different things
