### ISSUE TITLE
Keybinding toggle Project Pane

### ISSUE THREAD

**Issue by kresdjan** [zed-industries/zed#18230]
### Describe the feature

There doesn't seem to be a command to toggle the Project Pane, so you can't add a custom keybinding for this. It would be lovely if that was possible. Some like 
```
"bindings": {
    "cmd-0": "project_panel::Toggle"
}
```

**Comment by SomeoneToIgnore** [comment]
The project pane is located in a dock (left one by default, but can be moved to the right).
Docks are togglable just fine with https://github.com/zed-industries/zed/blob/2ff8dde925b75d62f030755843cd93c402a41022/assets/keymaps/default-macos.json#L410-L412
