### ISSUE TITLE
Multibuffer doesn't always highlight all search results

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#18254]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:
1. Checkout zed repo and open it in Zed
2. cmd-shift-f for `save_as` and press enter
3. Scroll down and some of the results are not highlighted.

It's not always the same results, but it's quite consistent.

I did the git bisect and I believe it broke v0.151.0-pre due to commit  1d868e19f28ba6c6858790284b66f4efc8116388 from PR #16960:
- #16960

CC: @mrnugget 

### Environment

Zed: v0.155.0 (Zed Nightly bb7d9d35256825c9b022a3c89c556c1521664c8d)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="771" alt="Screenshot 2024-09-23 at 22 00 50" src="https://github.com/user-attachments/assets/a5277a99-815f-4ac2-b37a-97161c4e03bb">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
#18219 might also relate this.

**Comment by failable** [comment]
https://github.com/zed-industries/zed/issues/17690

**Comment by notpeter** [comment]
Thanks for reporting.  Updates for Zed Stable and Zed Preview including the fix are building now and should be available shortly.
