### ISSUE TITLE
Vim Mode: exit insert mode on file save

### ISSUE THREAD

**Issue by kraftwer1** [zed-industries/zed#18264]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd find it super handy if saving the file (e.g. using `cmd-s`) would leave insert mode and switch back to normal mode. But maybe that's just me. What do others think of that?

**Comment by ConradIrwin** [comment]
@kraftwer1 you can achieve this by adding the following to your key bindings file:

```
[{
  "context": "vim_mode == insert",
  "bindings": {"cmd-s": ["workspace::SendKeystrokes", "escape cmd-s"]}
}]
```

**Comment by vipexv** [comment]
The solution above doesn't seem to work for me, maybe a new update or?
