### ISSUE TITLE
Graceful closing of terminal panels

### ISSUE THREAD

**Issue by julian7** [zed-industries/zed#18272]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As it is not obvious that pane focus doesn't follow my eye movement, I often close terminal panels by mistake. Unfortunately, there is no conditional for terminal panel close (cmd+w is pretty much generic), and on top of losing all the contents of the shell, already running items continue to run under PPID 1.

I'd rather disallow cmd+w for terminals, but apart from that annoying me, my ask is to handle terminal session, and cleaning up on close.

### Environment

Zed: v0.153.6 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
> my ask is to handle terminal session, and cleaning up on close.

Can you expand further upon this? Do you have an example which reproduces the behavior you're seeing? 

Separately, you cannot easily disallow `cmd-w` for terminals on MacOS in Zed.  Even once https://github.com/zed-industries/zed/issues/7544 is fixed, there will need to be additional work to unbind cmd-w (if not mapped in the menus MacOS traps `cmd-w` and sends it as a CloseWindow event which closes the entire workspace). I don't have a timeline, but I wanted to let you know we are working towards making that possible.

**Comment by julian7** [comment]
> Can you expand further upon this? Do you have an example which reproduces the behavior you're seeing?

TBH I had this problem last week, but I can't reproduce it anymore.

> Separately, at the moment you cannot easily disallow cmd-w for terminals on MacOS in Zed. Even once https://github.com/zed-industries/zed/issues/7544 is fixed, there will need to be additional work to handle cmd-w in particular (if not mapped in the menus MacOS traps cmd-w and sends it as a CloseWindow event which closes the entire workspace). I don't have a timeline, but I wanted to let you know we are working towards making that possible.

This is awesome! From the look of it, I always had the feeling that this is going to be a hard nut to crack. However, I'm glad it's on the radar.

As there is no immediate issues left, I'm closing the case. Thank you for your work, you're awesome!
