### ISSUE TITLE
Supermaven: Completions with graphemes will cause a panic

### ISSUE THREAD

**Issue by s3bba** [zed-industries/zed#18278]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Supermaven crate cannot handle graphemes, the bug is simple to reproduce:
1. Enable supermaven
2. Add a comment like `// Add a 📁 icon inside a string`
3. Supermaven will return the icon, but the as [completion_state_from_diff](https://github.com/zed-industries/zed/blob/3a2f0653d16bdbacf2e090c15bcf424d96de9e64/crates/supermaven/src/supermaven_completion_provider.rs#L78C25-L78C58) cannot handle graphemes main thread will panic with:
```
Thread "main" panicked with "byte index 1 is not a char boundary; it is inside '📁' (bytes 0..4) of `📁\";`" at crates/supermaven/src/supermaven_completion_provider.rs:78:40
```

### Environment

Zed: v0.155.0 (Zed Dev dbc325ea12b7c06183149e472008f67a2ce0ce5f)
OS: Linux X11 arch unknown
Memory: 23.5 GiB
Architecture: x86_64
GPU: AMD Radeon VII (RADV VEGA20) || radv || Mesa 24.2.2-arch1.1

**Comment by notpeter** [comment]
I believe this was also reported here:
- https://github.com/zed-industries/zed/issues/18027#issuecomment-2362812365

And there is another PR here:
- https://github.com/zed-industries/zed/pull/18121

**Comment by ConradIrwin** [comment]
Superseded by https://github.com/zed-industries/zed/pull/18279
