### ISSUE TITLE
Add qwen2.5-coder context to known model lengths

### ISSUE THREAD

**Issue by thehamsti** [zed-industries/zed#18289]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The model qwen2.5-coder was just released and is one of the highest performing local/small models for coding. At the moment it defaults to 2048 context length, but it supports up to 128k as per https://ollama.com/library/qwen2.5-coder

### Environment

Zed: v0.155.0 (Zed Dev 5e62bbfd29172c966c4a9e494d0063acdba639b9)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Note, this will improved the default from 2048 and will be available in Zed Preview tomorrow (Stable next Wednesday) but you can always provide an override in your settings and specify your desired max_tokens explicitly (even before this patch lands). 

```
  "language_models": {
    "ollama": {
      "low_speed_timeout_in_seconds": 120,
      "available_models": [
        {
          "provider": "ollama",
          "name": "qwen2.5-coder",
          "max_tokens": 32768
        }
      ]
    }
  }
```

By default we clamp from the model max to a lower value of `16384` so that we don't crash ollama for users with non-heroic GPU memory: 
https://github.com/zed-industries/zed/blob/8a7ef4db59668f9dda841a9550abd1cc78651fa3/crates/ollama/src/ollama.rs#L77 

Docs: https://zed.dev/docs/assistant/configuration#ollama-context

**Comment by AidfulAI** [comment]
Stumbled across this in the latest changelog. I updated to 0.155.2 on my Linux setup with a GeForce 3090 with 24GB VRAM, but for qwen2.5-coder (also for deepseek-coder-v2, not explored for others) it still shows 0/16k tokens for me.
![Selection_741](https://github.com/user-attachments/assets/e4031d76-691f-47d4-888d-277cfe5c14af)

Also, adding the manual setting override as shown by @notpeter in the previous post does not change this. From my understanding of the code, the "clamp" method is still applied and sets the context window to its upper bound of 16k.

Anything else I need to change to use the full context window?

**Comment by notpeter** [comment]
If you look more carefully [at the code](https://github.com/zed-industries/zed/blob/8a7ef4db59668f9dda841a9550abd1cc78651fa3/crates/ollama/src/ollama.rs#L92-L102) that function is only called as a fallback if there's no max_tokens provided.

See [Assistant Configuration: Ollama Context](https://zed.dev/docs/assistant/configuration#ollama-context) in the docs and try the config shown there.  If this doesn't work for you, please open a new issue with your config.

<img width="1036" alt="Screenshot 2024-10-07 at 21 00 43" src="https://github.com/user-attachments/assets/c32cfb0b-74b4-43b6-9232-c020a5b48a3b">

**Comment by AidfulAI** [comment]
Thanks for your prompt reply. I missed that it does not overwrite the default version of the model, but adds a new configuration with larger context windows. 🤦

I confirmed that it works by adding the setting in my Windows and Linux setup, but the default config for the model stays at 16k.

Thanks again for your support @notpeter!
