### ISSUE TITLE
Running ollama LLM models remotely is no longer directly supported

### ISSUE THREAD

**Issue by mangoleaf** [zed-industries/zed#18304]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After a recent update, zed now requires that ollama is running locally on the machine zed is running on even when an api url is provided in the config.

For my setup, I have ollama running in WSL on my desktop and I call it from zed within windows and on my mac. In the past I have been able to use this remotely with no issues. Since a recent update, without installing ollama on windows or the mac, zed refuses to call ollama even though I have provided an api url for it to use.

![image](https://github.com/user-attachments/assets/eb6166fc-bcee-43de-904e-58f2f310d024)

```zed_config
  "language_models": {
    "ollama": {
      "api_url": "http://10.0.0.53:11434",
      "low_speed_timeout_in_seconds": 120,
      "available_models": [
        {
          "provider": "ollama",
          "name": "deepseek-coder-v2",
          "display_name": "DeepSeek Coder v2",
          "max_tokens": 33000,
          "keep_alive": "10m"
        },
        {
          "provider": "ollama",
          "name": "codestral:latest",
          "display_name": "Codestral",
          "max_tokens": 33000,
          "keep_alive": "10m"
        }
      ]
    }
  },
```

When supplying the ollama api_url in the config, I expect zed to not ignore if ollama is not installed locally.

Update: If I install ollama, I can once again start calling the remote instance of ollama but this should not be expected and I dont want it installed :)

### Environment

```windows
Zed: v0.155.0 (Zed Dev 692590bff435da3bdb7a0bd1bf9f139c3bdc6eb1)
OS: Windows 10.0.22631
Memory: 127.1 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4090 || NVIDIA || 561.09
```

```mac
Zed: v0.153.7 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
> N/A, environment is not relavant

This is extremely relevant, the version of Zed you are running and platform on which you are running are essential for us to track down the issue. Please provide open zed, open the command palette and type "zed: copy system specs to clipboard" and edit your description. 

Do you have any sense when it broke so we can narrow in on the version/commit which introduced the regression?

Anything of note in your Zed logs? (cmd-shift-p, Zed logs)

**Comment by mangoleaf** [comment]
Ah, you are right sorry, I took environment to be more about my shell when reading that for some reason.

> Do you have any sense when it broke so we can narrow in on the version/commit which introduced the regression?
Sorry, I havent been active in development so I havent been keeping track of version numbers, but, I noticed it first on my mac about 2 weeks ago. I generally hit update zed whenever there is an update and could no longer communicate with my ollama server. At the time, I installed ollama to work around it.

On my windows machine I rebuild from the HEAD of main about once or twice a month. I did this yesterday and again encountered the issue.

> Anything of note in your Zed logs?
No, nothing related to the AI panel or ollama. It is 99% of lines like the one below along with a few buffer and texture info logs
```
2024-09-25T11:49:58.6110378-06:00 [ERROR] Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }
```

**Comment by notpeter** [comment]
We made some changes recently to ollama stuff (see: [crates/ollama/src/ollama.rs](https://github.com/zed-industries/zed/commits/main/crates/ollama/src/ollama.rs)), specifically in 2c8a6ee7cc18cb8b3e29fa4c7efa74dde8458f4f looks like we changed how we are handling http.

You could probably checkout [v0.153.4-pre](https://github.com/zed-industries/zed/releases/tag/v0.153.4-pre) and build to see if that works.  Maybe you (or some kind soul similarly impacted) could do the git bisect to track down the specific commit where things broke.

There is also this PR (no issue) that I expect is related:
- https://github.com/zed-industries/zed/pull/18310

---

> `2024-09-25T11:49:58.6110378-06:00 [ERROR] Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }`

I think this is caused by you having running `git init` but not having any actual commits in your working directory. Filed:

- https://github.com/zed-industries/zed/issues/18358

**Comment by jmonster** [comment]
I haven't had a chance to dig into this, but _me too_, as someone who just installed Zed for the first time a few minutes ago and was trying to point it at an Ollama somewhere on my local network. Nothing happens when I click `Connect`, presumably since it is not available from `localhost`.

```
Zed: v0.154.2 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64
```

**Comment by mangoleaf** [comment]
> HOWEVER! I went back and tried the Op's settings (adjusting for my IP) and it now says `Connected`. So for me, it's a matter of missing docs?

Very interesting that my settings worked for you, I will try to make some time this weekend to experiment more with this.

**Comment by notpeter** [comment]
@mangoleaf There is a fix in main. Please try building from there and report back if that helps:
- https://github.com/zed-industries/zed/pull/18417#event-14426148455

@jmonster The docs for Zed Assistant [Ollama Configuration](https://zed.dev/docs/assistant/configuration#ollama) included a reference to setting an `api_url` but I've improved them given a custom Ollama endpoint is more common than say a custom Anthropic endpoint:
- https://github.com/zed-industries/zed/pull/18440

**Comment by notpeter** [comment]
@mangoleaf I tested it and I was wrong, #18417 does not fix ollama timeouts on main.  We are going to fail forward there and fix timeouts with the new http_client work in the coming days.

In the meantime, we will be releasing a hotfix to Preview this afternoon.
This will include the changes that @13w put up in:
- https://github.com/zed-industries/zed/pull/18310
Which will be merged in:
- https://github.com/zed-industries/zed/pull/18449

After that you can checkout the `v0.155.x` (which currently corresponds to Zed Preview), rebuild and I expect things will work for you.

Thanks for reporting. Please close if this works for you.

**Comment by mangoleaf** [comment]
Confirmed working for me on `v0.155.2` thanks for the fix!
