### ISSUE TITLE
Add support for new OpenAI models o1-mini and o1-preview models through the Github Copilot integration

### ISSUE THREAD

**Issue by sa1** [zed-industries/zed#18316]
### Check for existing issues

- [X] Completed

### Describe the feature

o1-mini and o1-preview were added via the OpenAI integration directly in https://github.com/zed-industries/zed/issues/17790, but usage through github copilot is not enabled currently.

**Comment by sa1** [comment]
I think there were some additional stuff added in https://github.com/zed-industries/zed/pull/17804/files that probably needs to be supported in this case too.

**Comment by AurevoirXavier** [comment]
GitHub doesn't publish their API documentation.

Needs to determine the request structure first. The stream completion is no longer functional for o1 models.

**Comment by AurevoirXavier** [comment]
Would love to implement this if someone can obtain and share the API details.

**Comment by sa1** [comment]
seems like it's fixed by #19968
