### ISSUE TITLE
zed in FIPS mode crashes with OpenSSL internal error

### ISSUE THREAD

**Issue by vroetman** [zed-industries/zed#18335]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```bash
❯ zed --foreground
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
```
This was built with the `./script/install-linux` script on a Red Hat Enterprise Linux laptop running in FIPS mode. 
```bash
❯ sysctl crypto.fips_enabled
crypto.fips_enabled = 1
```
zed crashes immediately with `zed --foreground` but hangs with `zed`.
The debug build (`cargo run` or `cargo run -p cli`) works and does not produce this error.

`Zed.log` is empty. I have pasted tail portions of  `strace zed` or `strace zed --foreground` output below.

I am not very familiar with Rust or how to build `zed`, so am not sure how to build a debug build that would have these same OpenSSL errors.

### Environment

Zed: v0.153.7 (Zed)
OS: Linux X11 rhel 8.10
Memory: 31 GiB
Architecture: x86_64
GPU: Quadro T2000 with Max-Q Design || NVIDIA || 550.107.02

OpenSSL version: 1.1.1k
RPMS:
openssl-devel-1.1.1k-12.el8_9.x86_64
openssl-libs-1.1.1k-12.el8_9.x86_64
openssl-1.1.1k-12.el8_9.x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
`Zed.log` is not created with this crash.

<details><summary>portion of strace zed</summary><pre>

lstat("/home/vic/.local/zed.app/libexec/zed-editor", {st_mode=S_IFREG|0755, st_size=162021400, ...}) = 0
socket(AF_UNIX, SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = 3
mkdir("/tmp/.tmp71nukh", 0777)          = 0
bind(3, {sa_family=AF_UNIX, sun_path="/tmp/.tmp71nukh/socket"}, 110) = 0
listen(3, 10)                           = 0
mmap(NULL, 2101248, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7efe6aadf000
mprotect(0x7efe6aae0000, 2097152, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7efe6acdee30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[1924750], tls=0x7efe6acdf700, child_tidptr=0x7efe6acdf9d0) = 1924750
mmap(NULL, 2101248, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7efe6a8de000
mprotect(0x7efe6a8df000, 2097152, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7efe6aadde30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[1924751], tls=0x7efe6aade700, child_tidptr=0x7efe6aade9d0) = 1924751
socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 5
connect(5, {sa_family=AF_UNIX, sun_path="/home/vic/.local/share/zed/zed-stable.sock"}, 51) = -1 ECONNREFUSED (Connection refused)
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7efe6b907fd0) = 1924753
close(5)                                = 0
futex(0x7efe6acdf9d0, FUTEX_WAIT, 1924750, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=1924753, si_uid=364607592, si_status=SIGABRT, si_utime=0, si_stime=0} ---
futex(0x7efe6acdf9d0, FUTEX_WAIT, 1924750, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)

</pre></details>

<details><summary>portion of strace zed --foreground</summary><pre>

lstat("/home/vic/.local/zed.app/libexec/zed-editor", {st_mode=S_IFREG|0755, st_size=162021400, ...}) = 0
socket(AF_UNIX, SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = 3
mkdir("/tmp/.tmpFnTaCa", 0777)          = 0
bind(3, {sa_family=AF_UNIX, sun_path="/tmp/.tmpFnTaCa/socket"}, 110) = 0
listen(3, 10)                           = 0
mmap(NULL, 2101248, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f93c7e81000
mprotect(0x7f93c7e82000, 2097152, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f93c8080e30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[1927071], tls=0x7f93c8081700, child_tidptr=0x7f93c80819d0) = 1927071
mmap(NULL, 2101248, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f93c7c80000
mprotect(0x7f93c7c81000, 2097152, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f93c7e7fe30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[1927072], tls=0x7f93c7e80700, child_tidptr=0x7f93c7e809d0) = 1927072
mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f93c8cb2000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7f93c8cbaff0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 1927073
munmap(0x7f93c8cb2000, 36864)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(1927073, crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
[{WIFSIGNALED(s) && WTERMSIG(s) == SIGABRT && WCOREDUMP(s)}], 0, NULL) = 1927073
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=1927073, si_uid=364607592, si_status=SIGABRT, si_utime=0, si_stime=0} ---
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7f93c8cbe000, 12288)           = 0
exit_group(0)                           = ?
+++ exited with 0 +++

</pre></details>

**Comment by notpeter** [comment]
Hi @vroetman, 

Our pre-compiled binaries ship with a dylib dependency to openssl but you should absolutely see if you can build your own Zed binaries to see if you can get it to work. Our docs include a section on [Building Zed for Linux](https://zed.dev/docs/development/linux), but once you've setup cargo/rust and installed the necessary dependencies it be as simple as `cargo run` to see if it works and `cargo build --release` to build a release binary.

Can you give that a whirl and see if you have any luck?

It is possible we are using algorithms in openssl which are not included in OpenSSL in FIPS (MD5, RC4, Blowfish, IDEA, etc).

Long shot - Do you by chance have multiple openssl versions installed? In a previous life I ran into `FATAL FIPS SELFTEST FAILURE` when an app was finding a OpenSSL 1.0 lib installed for compatibility with a legacy app.

**Comment by vroetman** [comment]
Thank you for your reply.  I just learned that if I run `zed-editor` directly, it crashes.
```
❯  ~/.local/zed.app/libexec/zed-editor
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
[1]    157724 abort (core dumped)  ~/.local/zed.app/libexec/zed-editor
```

The pre-compiled binaries say they require GLIBC_2.29 or later. RHEL8 only has glibc 2.28, which is why I am trying to build.

Strangely, running the pre-compiled binaries on a RHEL-9 VM, it still fail with:
```
$ zed.app/bin/zed --foreground
/home/elsys/zed.app/libexec/zed-editor: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /home/elsys/zed.app/libexec/zed-editor)
```
It seems, then, that `libm.so.6` requires either 2.29 or 2.35??

`cargo run` works fine.

After running `cargo build --release`, `./target/release/zed` also seems to work fine (but has no --foreground option).

But the version installed with ` ./script/install-linux` is the one that fails with the OpenSSL error. Maybe it's the `remote_server` package that is having troubles?

**Comment by notpeter** [comment]
Please forgive my ignorance, I'm not a linker expert by any means.  But this makes some sense.  My understanding is that in FIPS environments the intention is to block all non-FIPS certified openssl so that you can be sure everything is running with the FIPS certified libs.

It's good to know that users in such an environment user can basically just:
```
rm ~/.local/zed.app/lib/libssl.so.1.1
rm ~/.local/zed.app/lib/libcrypto.so.1.1
```
And get a working version of Zed.

We expect Linux distribution package maintainers in the future will distribute Zed packages which are appropriate for their environment (e.g. link to system openssl) but currently our binaries are intentionally a little one-size-fits-all.

I wonder whether it would be desirable to detect if we are running running in a FIPS environment (`cat /proc/sys/crypto/fips_enabled`, etc) and behave differently.

Thank you reporting and I appreciate the updates.

**Comment by vroetman** [comment]
@notpeter, thank you for your prompt response to this issue and your help in figuring it out.

After thinking about this, I agree that package maintainers can build it against the right libraries and make sure it links against the system libssl.

Could we add a note to the Troubleshooting section of `docs/src/linux.md` to try removing 
`zed.app/lib/libssl.so.1.1`
`zed.app/lib/libcrypto.so.1.1`
if they see the
```
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
```
error?
