### ISSUE TITLE
Normal keybindings are overridden in embedded terminal

### ISSUE THREAD

**Issue by hedefalk** [zed-industries/zed#18354]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On SE locale Mac, I need to use alt/option to write things like | which is simply alt-7 and @ is alt-2 and so forth. 

These work fine in the editor but NOT in the embedded terminal.

If I hit alt-7 anywhere on this machine including an editor window in zed I get the pipe symbol |. If I do it in the terminal in zed I get just 7. And that's on fish. If I from fish start bash I can see some control chars:

✗ bash
bash-5.2$ ^[7^[7

With zsh its even weirder, I can see I get some cmd to repeat the next char. So hitting cmd-7 and then d gives me 7 d's:

viktor@viktor:// > ddddddd

alt-2 that is used for @ gives me two characters.

### Environment

My own keysettings seems unrelated, this is all:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-shift-r": "pane::RevealInProjectPanel",
      "cmd-alt-left": "pane::GoBack",
      "cmd-alt-right": "pane::GoForward",
      "cmd-<": null,
      "cmd-shift-d": "editor::DuplicateLineDown"
    }
  },
  {
    "context": "Editor && !showing_completions",
    "bindings": {
      "tab": "editor::Indent"
    }
  }
]
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you try adding the following to your `~/.config/zed/settings.json`?
```
  "terminal": {
    "option_as_meta": false
  }
```

**Comment by hedefalk** [comment]
> Can you try adding the following to your `~/.config/zed/settings.json`?

That works! Fanx!
