### ISSUE TITLE
vim: increment with left padded number

### ISSUE THREAD

**Issue by ThomAub** [zed-industries/zed#18360]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When incrementing with `<C-a>` or `<C-x>` vim respect the left 0-padding of the number 

`0000ˇ5` with `<C-a>` should display `00006` but Zed may display: `6`

### Environment

```
Zed: v0.154.1 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64
```

**Comment by ConradIrwin** [comment]
Closed by #18362
