### ISSUE TITLE
Rewrap doesn't work on multi-line doxygen style comments in C++ files

### ISSUE THREAD

**Issue by oliverlee** [zed-industries/zed#18361]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Thanks for adding the new re-wrap command! I tried it out on a C++ file, but it does not wrap Doxygen style documentation comments:

```cpp
/// Every blade has a grade, where the grade is the number of factors, equal to `sizeof(Is...)`. The grade of the blade cannot exceed the algebra's dimension.
```

Feel free to close if this is a duplicate of:
- https://github.com/zed-industries/zed/issues/18221 or 
- https://github.com/zed-industries/zed/issues/18162

### Environment

Zed: v0.154.1 (Zed)
OS: macOS 14.6.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxdeviant** [comment]
My guess is that `///` is not registered as a valid line comment prefix for C++.

**Comment by maxdeviant** [comment]
https://github.com/zed-industries/zed/blob/1deed247eb37080b6db5d84ed5054214691554e9/crates/languages/src/cpp/config.toml#L4
