### ISSUE TITLE
remote paywall: allow to SSH remote without Zed login

### ISSUE THREAD

**Issue by paulcarroty** [zed-industries/zed#18392]
### Check for existing issues

- [X] Completed

### Describe the feature

"To continue with remote development features, you need to sign in to Zed" - why I need it for access machine over SSH?

**Comment by osiewicz** [comment]
This feature is still in alpha and allowing usage without GitHub log-in was on our to-do list. We're not paywalling it. :)
I've just opened a PR which allows use of direct ssh mode when the user is not logged in.

**Comment by paulcarroty** [comment]
Sorry, great to hear.
