### ISSUE TITLE
The proxy settings do not work in version 0.154.1 and later.

### ISSUE THREAD

**Issue by suxiaoshao** [zed-industries/zed#18391]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Set in settings.json
```json5
{
  "proxy": "http://127.0.0.1:7890"
}
```

However, the network for Zed's automatic updates, extensions downloads, and Assistant does not go through the proxy server; I'm not sure why. However, if you open Zed using the following command, it will work properly with the proxy.

```bash
https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890 zed .
```

### Environment

Zed: v0.154.2 (Zed)
OS: macOS 15.0.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by kzhui125** [comment]
you should restart Zed after the proxy setting change @suxiaoshao

**Comment by CharlesChen0823** [comment]
can you try pre-release? if this problem still exists?

**Comment by kzhui125** [comment]
there are bug in 154.2, proxy not working.

**Comment by CharlesChen0823** [comment]
there is a commit to fix proxy setting problem, if the pre-release is work, i think it  had fixed.

**Comment by kzhui125** [comment]
yeah, should be this issue:

https://github.com/zed-industries/zed/issues/18155

**Comment by notpeter** [comment]
Can you try Zed Preview v0.155.0 and see if that works for you. It includes #18155.

Separately, there is no need to setup multiple environment variables:
```
https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890 zed .
```
Looking at the code we will only pickup the first of these env vars we find:
https://github.com/zed-industries/zed/blob/25e2e9c6727ba9b77415588cfa11fd969612adb7/crates/http_client/src/http_client.rs#L248-L265

So in your case the proxy setting will be from `all_proxy=socks5://127.0.0.1:7890` note this is different from the settings you have specified above (`"proxy": "http://127.0.0.1:7890"`).  If you are running a socks proxy you should use `socks5` (or really `socks5h`) and if you specify `http` Zed will use the http proxy protocol.  Your proxy may be configured to support both on the same port, but `"proxy": "http://127.0.0.1:7890"` and `"proxy": "socks5h://127.0.0.1:7890" are not equivalent.

**Comment by kzhui125** [comment]
It seems that not all proxy issues was fixed, because in `crates/isahc_http_client/src/isahc_http_client.rs`, `IsahcHttpClient::proxy` return None.

So that `cx.http_client().proxy()` will get None in `Client::production(cx);`

https://github.com/zed-industries/zed/blob/6d4ecac6100f7908278e78cb8c5102f7f91c54c5/crates/client/src/client.rs#L534

This means all later options to get proxy() from Client will get None, for example `RealNodeRuntime`:

@notpeter 

<img width="838" alt="image" src="https://github.com/user-attachments/assets/980d939a-fba0-44b6-99a9-87d87b23b4ff">

**Comment by kzhui125** [comment]
maybe we can make `IsahcHttpClient` struct private, and use `HttpClientWithProxy` in the whole project?
can let the HttpClientWithProxy wrap `IsahcHttpClient` and create it in new fn
