### ISSUE TITLE
doc: add the info about `zed-java-eclipse-jdtls`

### ISSUE THREAD

**Issue by HeavySnowJakarta** [zed-industries/zed#18419]
### Check for existing issues

- [X] Completed

### Describe the feature

There is no LSP supports reported on https://zed.dev/docs/languages/java, and [`zed-java-eclipse-jdtls`](https://github.com/ABckh/zed-java-eclipse-jdtls) claims it has added support for java language servers (eclipse-jdtls).

**Comment by HeavySnowJakarta** [comment]
ref:

- https://github.com/zed-industries/extensions/issues/500#issuecomment-2088676462
- https://github.com/zed-extensions/java/issues/4#issuecomment-2276136111
- https://github.com/zed-extensions/java/pull/7

**Comment by HeavySnowJakarta** [comment]
now the promblem is, we have [@valentinegb's fork](https://github.com/valentinegb/zed-java/tree/lsp), as well as [@ABckh's another extension](https://github.com/ABckh/zed-java-eclipse-jdtls) (they might were just doing the same thing), and the [origin](https://github.com/zed-extensions/java) seems not merging the fork, and there might be some users not seeing their works on the doc, and mistakenly think nobody was doing works on adding lsp support to java. maybe the doc needs to be updated?

**Comment by valentinegb** [comment]
Heyo,

In case it's not known already, zed-extensions/java#7 was merged! I am also now a maintainer of that extension, so it shouldn't be stuck without any new changes anymore. I'm for [@ABckh's extension](https://github.com/ABckh/zed-java-eclipse-jdtls) being in the Zed docs too, but I also think we should probably now mention that [zed-extensions/java](https://github.com/zed-extensions/java) uses a language server, too. Right now only the tree sitter the extension uses is listed.
