### ISSUE TITLE
A new terminal overlaps existing tabs

### ISSUE THREAD

**Issue by tomhemmes-rl** [zed-industries/zed#18438]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Let me start by saying I love Zed so far and I'm not sure whether this is a bug or I'm missing how to switch between the panes.

When I open a new terminal pane by clicking the button or `ctrl+`` it overlaps any existing open text-editor panes. Despite my i3 showing that the original text editor file is still in focus. Example in picture where I opened README.md, i3 still shows that, but I can't reach it anymore except by closing the terminal. I feel like I have tried every pane switching shortkey listed in the docs.

(seems from the title similar to https://github.com/zed-industries/zed/issues/7549, but its a different issue)

### Environment

Zed: v0.154.2 (Zed)
OS: Linux X11 fedora 40
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.1.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![zed_terminal_issue](https://github.com/user-attachments/assets/2bb80dca-b70c-462c-82fd-844cda7b9556)

### If applicable, attach your Zed.log file to this issue.

I didnt see any new loglines when going through the steps, so figured there wasn't anything relevant there.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by AkisKourouklis** [comment]
@tomhemmes-rl  Your terminal is just full height, you can drug it down by moving the mouse on the top of the terminal. This could actually have a height limit, but I don't think it is an issue right now.

I am not on Linux to tell if it is working there, but on Mac it works pretty well.

<img width="713" alt="Screenshot 2024-09-28 at 5 01 39 PM" src="https://github.com/user-attachments/assets/4eb81f2c-3819-4b1d-b955-22ebccf9abfb">

**Comment by tomhemmes-rl** [comment]
Aha, that is very helpful thank you! Actually I was not able to drag it down, but I was able to drag the pane to the right, revealing the other tabs, 'back+forward' and 'Inline assist+New+Zoom in'.

It is somewhat surprising that New file opens a new tab, but new terminal opens this fullscreen overlay terminal by default.
