### ISSUE TITLE
Filenames with circular brackets fails to load

### ISSUE THREAD

**Issue by xtanion** [zed-industries/zed#18434]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a filename that includes brackets e.g. `files_123(2).json` it fails to open the file and instead creates a new file by name `files_123.json`

### Environment

macos sonoma

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by hotleave** [comment]
also has the problem on macos sequoia, but it will be ok if I drag the file in it

**Comment by SomeoneToIgnore** [comment]
This is fixed in https://github.com/zed-industries/zed/pull/19057 and should come with the next release on Wednesday.
