### ISSUE TITLE
Automatic context title ends up way too verbose

### ISSUE THREAD

**Issue by sylbru** [zed-industries/zed#18432]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Contexts in the Assistant panel get automatically named after the contents of the context, using the LLM itself, same as ChatGPT and other interfaces. Using Claude 3.5 Sonnet (Zed) at least, these titles seem to end up being way too verbose and therefore useless because of the very limited space in a tab. A few examples:

- Here is a brief Python script to change Zed’s theme based on a command-line argument:
- Based on your question, here is a concise title summarizing the context:
- Based on the error message provided, a concise title summarizing the context could be:
- Here’s a JavaScript function that generates the Fibonacci sequence:

Two of these examples give a relevant title, but in a sentence that’s way too long. The other two seem to leak the instruction that was given to the LLM.

### Environment

Zed: v0.154.2 (Zed)
OS: Linux X11 linuxmint 21.2
Memory: 14.8 GiB
Architecture: x86_64
GPU: AMD Unknown (RADV RENOIR) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/16ea8abc-cdd2-42a8-ae03-8e5d9e2ce4bd)

**Comment by JosephTLyons** [comment]
Seems like we should tune whatever prompt is being used to ask for titles for those files. Or we should provide a setting to turn it off and allow the user to write their own, if they want.

**Comment by sylbru** [comment]
I’ve always thought of this feature as a great idea and perfect use for a LLM.

It’s probably an easy although approximate kind of fix, I’ve never worked with fixed prompts in a application like this.

I would have liked to try and help with this fix, but I couldn’t find anywhere in the code with words like "concise title summarizing the context" which seems to be part of the prompt. Is it in another git repo?

**Comment by maxdeviant** [comment]
Has this improved at all after https://github.com/zed-industries/zed/pull/19530?

**Comment by sylbru** [comment]
Yes it seems to have improved a lot indeed! I’ll close this issue then.
