### ISSUE TITLE
Macos Sequoia Go-To-File Crashing

### ISSUE THREAD

**Issue by BWheatie** [zed-industries/zed#18455]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using Sublime Text keybindings "cmd+t" "go-to-file" and beginning to type anything causes the whole app to crash. 

### Environment

Zed: v0.154.2 (Zed)
OS: macOS 15.0.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-27T10:52:37.44919-07:00 [ERROR] {
  "thread": "main",
  "payload": "candidate info not found",
  "location_data": {
    "file": "crates/file_finder/src/file_finder.rs",
    "line": 417
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::option::expect_failed",
    "file_finder::matching_history_items::<&alloc::vec::Vec<file_finder::FoundPath>>",
    "<file_finder::FileFinderDelegate>::spawn_search::{closure#2}::{closure#0}",
    "<async_task::raw::RawTask<<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>, (), <gpui::executor::ForegroundExecutor>::spawn::inner<()>::{closure#0}, ()>>::run",
    "gpui::platform::mac::dispatcher::trampoline",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "<gpui::app::App>::run::<zed::main::{closure#5}>",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.154.2",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "15.0.0",
  "architecture": "aarch64",
  "panicked_on": 1727459557449,
  "system_id": "d2457efe-6b97-4ed5-af04-f3b042aa4f26",
  "installation_id": "df086a56-8855-4288-9323-434b46f6d19b",
  "session_id": "47cba4ad-017a-4a44-aaa8-feac4b076611"
}
</pre></details>

**Comment by CharlesChen0823** [comment]
i thought this had been fixed by #18374

**Comment by BWheatie** [comment]
Seems I didn't have that update available when I opened the ticket. Thanks!
