### ISSUE TITLE
remoting: SSH timeout while waiting for user input

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#18466]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When trying to connect to a remote server with `zed ssh://host/~/project` I was prompted for a 2FA code and password as expected (I have to go through an SSH jump host that requires both of those things). However while I was digging up the TOTP app for the 2FA code, Zed decided that the connection had timed out and refused to proceed even after entering the prompted info.

### Environment

Zed: v0.156.0 (Zed Dev d96834f6a6dc368b86a269c85365400d28c19f82)
OS: Linux Wayland nixos 24.11
Memory: 125.7 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7900 XTX (RADV NAVI31) || radv || Mesa 24.2.2

### If applicable, attach your Zed.log file to this issue.

```
[2024-09-28T05:16:34+03:00 ERROR zed] Read operation timed out

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14
   1: <T as core::convert::Into<U>>::into
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/convert/mod.rs:759:9
   2: remote::ssh_session::SshClientState::new::{{closure}}
             at ./crates/remote/src/ssh_session.rs:600:24
   3: remote::ssh_session::SshSession::client::{{closure}}
             at ./crates/remote/src/ssh_session.rs:143:90
   4: recent_projects::ssh_connections::connect_over_ssh::{{closure}}::{{closure}}
             at ./crates/recent_projects/src/ssh_connections.rs:393:
<snip>
```

**Comment by jansol** [comment]
I managed to get past the timeout by having my password in the clipboard and pasting it into the dialog, but when I tried actually opening a folder I was prompted again for... my "password". Except pasting the password again did not work - turns out it was still asking for the 2FA code first (and then again for the password), the label in the prompt was just wrong this time.

**Comment by fonnesbeck** [comment]
The remote setup timeout is **way** too short.

**Comment by jansol** [comment]
Not seeing any timeouts on the password + 2FA prompt any more on v0.159.0

@fonnesbeck if you're getting timeouts during the process of copying the server binary over and launching it, that's a separate issue I think.
