### ISSUE TITLE
watching logic doesn't handle symlinks 

### ISSUE THREAD

**Issue by maan2003** [zed-industries/zed#18472]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

ref https://github.com/zed-industries/zed/pull/17499

here ~/src/fync is symlink to /src/dev-sandbox/fync
```
[2024-09-28T16:41:22+05:30 ERROR worktree] ignoring event "/home/user/src/fync/src/main.rs" outside of root path "/src/dev-sandbox/fync"
```

### Environment

Zed: v0.156.0 (Zed Dev c7ab82e51e47d3adc91a339d29100c8c9b942b6c)
OS: Linux Wayland nixos 24.11
Memory: 7.4 GiB
Architecture: aarch64
GPU: Apple M1 (G13G B1) || Honeykrisp || Mesa 24.3.0-devel

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maan2003** [comment]
cc @osiewicz

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/17605 ?

**Comment by maan2003** [comment]
sorry
