### ISSUE TITLE
inputting scrolling between mouse and trackpad scrolls to document edges

### ISSUE THREAD

**Issue by kootoopas** [zed-industries/zed#18485]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

mouse scrolling followed by trackpad scrolling (or opposite order) scrolls to document start or end

may be the same issue: https://github.com/zed-industries/zed/issues/17230

### Environment

Zed: v0.153.6 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 23 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

**Comment by mgsloan** [comment]
Coincidentally I just wrote a fix for this!  #18484

**Comment by kootoopas** [comment]
thanks king

**Comment by JosephTLyons** [comment]
Hey @kootoopas, would you be able to include a screen recording of what you're seeing, just so we have a bit more clarity here?

**Comment by JosephTLyons** [comment]
Sorry, I missed the mention of the PR fixing this. Closing this out.
