### ISSUE TITLE
I hope that control and UI creation-related functions can be added to the extensions API.

### ISSUE THREAD

**Issue by yuWorm** [zed-industries/zed#18496]
### Check for existing issues

- [X] Completed

### Describe the feature

Thank you to the Zed team for developing such a great editor. I'm now gradually migrating my work to Zed, and the experience is excellent. I want to try developing some utility extensions to assist with my work, but I've noticed that there don't seem to be any UI-related APIs in the extensions. So, I hope that Zed can add UI control and creation-related APIs to its extensions. This would make the extensions more versatile, allowing for the creation of many useful and interesting extensions.

**Comment by notpeter** [comment]
Yep.  We intend to gradually add support for more features to the Extensions API, but at this point do not have a timeline nor a sequence of potential future enhancements (including extension UIs).

The current Extension APIs and future enhancements will be documented here:
https://zed.dev/docs/extensions/developing-extensions

Thanks for filing!
