### ISSUE TITLE
Disable Mouse Toggle & Settings - To Help Users Use The Keyboard More To Increase Productivity

### ISSUE THREAD

**Issue by trymeouteh** [zed-industries/zed#18522]
### Check for existing issues

- [X] Completed

### Describe the feature

It is faster to use a keyboard and ones needs to master the keyboard commands to do so. However it is a challenge to began getting use to the keyboard when navigating Zed due to the habit of using the mouse.

I would like to suggest these setting in Zed to disable the mouse...

- Disable mouse in editor
- Disable mouse in panel
- Disable mouse in sidebar
- Show mouse toggle button in status bar (Will show a button that can be clicked on to toggle the state of the mouse being enabled/disabled in Zed)
- Enable mouse timer (How long to enable the mouse for in seconds. If set to 0, it will keep the mouse enabled forever until the mouse toggle is toggled again)

And to have a keyboard shortcut to toggle the mouse being enabled/disabled in Zed.

When the mouse is disabled for a certain section of the program (editor, panel, sidebar, etc), the user cannot use the mouse to left click, right click, scroll, middle click, highlight or even hover over to get more details.

There are other editors out there that are keyboard only. However I would like to use Zed with both mouse and keyboard, but more keyboard and to have Zed not allow me to "cheat" and use the mouse in things like the editor or terminal for example. And Zed is the best editor on the market especially due to the massive amounts of extensions that are available for the IDE.

I think such a feature when enabled could over time help make users more productive by keeping their hands on the keyboard.

**Comment by notpeter** [comment]
While I appreciate the goal (Zed being fully keyboard navigable, no mouse required) we're not actually there today.  I think we're unlikely to adding a bunch of settings for disabling the mouse in individual areas (e.g. project panel, assistant panel, but not the status bar, etc) to support this niche use case (training to be mouse free).

My suggestion is that you handle this at the operating system level and have a global keyboard shortcut which enables/disables the mouse.  On Linux you could use something [this script](https://superuser.com/questions/1284275/disable-mouse-when-keyboard-key-is-pressed-in-linux).  

In the past I've used [uhubctl](https://github.com/mvp/uhubctl) on MacOS and Linux for almost exactly this purpose.  It doesn't work with every USB hub, but the hub in my Dell monitor is supported, so I can easily script turning off/on my Logitech trackball:
<img width="816" alt="Screenshot 2024-10-01 at 13 07 17" src="https://github.com/user-attachments/assets/da101030-2fb5-4643-a911-f91aed178491">

You could easily create two scripts: `mon` and `moff` to trigger via terminal or a global hotkey. Anyways, good luck on your keyboard-free adventures.
