### ISSUE TITLE
Setting `font_buffer_weight` to a high value makes Zed crash

### ISSUE THREAD

**Issue by 0hDEADBEAF** [zed-industries/zed#18531]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing the settings, using the value `1000` (and probably any higher value) for `buffer_font_weight` property makes Zed crash.
The console gives the following error message:

```
[2024-09-30T12:27:46+02:00 ERROR] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-09-30T12:27:46+02:00 ERROR] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-09-30T12:27:46+02:00 ERROR] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-09-30T12:27:46+02:00 ERROR gpui::platform::windows::direct_write] JetBrainsMono Nerd Font not found, use Segoe UI instead.
[2024-09-30T12:27:46+02:00 ERROR] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-09-30T12:27:47+02:00 ERROR zed::reliability] {
  "thread": "<unnamed>",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "crates\\gpui\\src\\platform\\windows\\direct_write.rs",
    "line": 441
  },
  "backtrace": [
    "backtrace::backtrace::dbghelp64::trace",
    "backtrace::backtrace::trace_unsynchronized<backtrace::capture::impl$1::create::closure_env$0>",
    "backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>",
    "backtrace::capture::Backtrace::create",
    "backtrace::capture::Backtrace::new",
    "zed::reliability::init_panic_hook::closure$0",
    "alloc::boxed::impl$50::call",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::closure$0",
    "std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>",
    "std::panicking::begin_panic_handler",
    "core::panicking::panic_fmt",
    "core::panicking::panic",
    "core::option::unwrap_failed",
    "core::option::Option::unwrap",
    "gpui::platform::windows::direct_write::impl$4::select_font::closure$0",
    "core::option::Option::unwrap_or_else<gpui::text_system::FontId,gpui::platform::windows::direct_write::impl$4::select_font::closure_env$0>",
    "gpui::platform::windows::direct_write::DirectWriteState::select_font",
    "gpui::platform::windows::direct_write::impl$3::font_id",
    "gpui::text_system::TextSystem::font_id",
    "gpui::text_system::TextSystem::resolve_font",
    "gpui::text_system::TextSystem::line_wrapper",
    "editor::display_map::wrap_map::impl$0::rewrap::async_block$0",
    "core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,tuple$<editor::display_map::wrap_map::WrapSnapshot,text::patch::Patch<u32> > > >,core::marker::Send>,alloc::alloc::Global> >",
    "async_task::raw::RawTask::run<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,tuple$<editor::display_map::wrap_map::WrapSnapshot,text::patch::Patch<u32> > > >,core::marker::Send>,alloc::alloc::Global> >,tuple$<editor::displ",
    "async_task::runnable::Runnable::run<tuple$<> >",
    "gpui::platform::windows::dispatcher::impl$0::dispatch_on_threadpool::closure$0",
    "windows::System::Threading::WorkItemHandlerBox::Invoke<gpui::platform::windows::dispatcher::impl$0::dispatch_on_threadpool::closure_env$0>",
    "DllGetClassObject",
    "BaseThreadInitThunk",
    "RtlUserThreadStart"
  ],
  "app_version": "0.154.3",
  "release_channel": "Zed",
  "os_name": "Windows",
  "os_version": "10.0.22621",
  "architecture": "x86_64",
  "panicked_on": 1727692067700,
  "system_id": "bf161767-79d3-4e02-b575-efc2943a319b",
  "installation_id": "b608adb2-2cfd-4fce-86da-05f903b5ff3c",
  "session_id": "2b4f54f0-58f2-46d0-8b8b-ab8b37bfdbae"
}
error: process didn't exit successfully: `target\debug\zed.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

### Environment

Zed: v0.154.3 (Zed)
OS: Windows 10.0.22621
Memory: 31.3 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD proprietary driver || 23.40.26 (LLPC)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JunkuiZhang** [comment]
I can set 2000 without crash, this may be font-related. Needs more investigation.

![Screenshot 2024-10-01 000659](https://github.com/user-attachments/assets/bf98c55c-2f0c-49a3-8806-1de829bea494)

**Comment by JunkuiZhang** [comment]
Yes, basically you cannot set a value higher than 999

**Comment by 0hDEADBEAF** [comment]
From the official website (see [here](https://zed.dev/docs/configuring-zed#buffer-font-weight)), it should be an integer between 100 and 900 so maybe you meant 900?
Anyway, it's not much about whether the value is right or not but rather at how Zed handles it. I don't think crashing is an intended behavior when facing an invalid value for a setting.
Zed probably should warn about an invalid value being used for the `buffer_font_weight` parameter while using the default value (`400` according to the official website) rather than crashing (it's especially annoying since you would need to edit the configuration file and bring back that parameter to a valid value with another editor because Zed can't run at all otherwise).

**Comment by JunkuiZhang** [comment]
> From the official website (see [here](https://zed.dev/docs/configuring-zed#buffer-font-weight)), it should be an integer between 100 and 900 so maybe you meant 900?

Sorry for the confusion. What I mean is, based on my testing, the Windows API we're calling internally accepts values below 1000, but anything higher causes a crash.

> Anyway, it's not much about whether the value is right or not but rather at how Zed handles it. I don't think crashing is an intended behavior when facing an invalid value for a setting. Zed probably should warn about an invalid value being used for the `buffer_font_weight` parameter while using the default value (`400` according to the official website) rather than crashing (it's especially annoying since you would need to edit the configuration file and bring back that parameter to a valid value with another editor because Zed can't run at all otherwise).

You're absolutely right, and I will certainly fix this crash. However, I would first like to confirm if macOS has a similar issue, so I can address both in the same PR.

**Comment by 0hDEADBEAF** [comment]
Alright! Good luck, thank you for your answer :)
