### ISSUE TITLE
Typo on multibuffers page

### ISSUE THREAD

**Issue by NinjaInShade** [zed-industries/zed#18533]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Head over to https://zed.dev/docs/multibuffers and in the "Diagnostics" section there is a typo: `diagnostcs: Deploy`. This should be `diagnostics: Deploy`

### Environment

Zed: v0.154.3 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 30.5 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7900 XTX (RADV NAVI31) || radv || Mesa 24.2.3 - kisak-mesa PPA

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Thank you,  https://github.com/zed-industries/zed/pull/18535 will take care of this.
