### ISSUE TITLE
Texlab, LaTeX extension and LaTeX: Previewer opens in the wrong place

### ISSUE THREAD

**Issue by mocenigo** [zed-industries/zed#18539]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Refer to https://github.com/latex-lsp/texlab/issues/1227 for the description. I do not know whether it is a bug in TeXLab, the latex extension passes the wrong parameters, or in Zed.

### Environment

Zed: v0.154.3 (Zed)
OS: macOS 15.1.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
As currently written this is unactionable.

Please provide reproduction instructions and example code triggering the issue and an explicit description of what is currently happening (wrong behavior) and what you expect to happen (correct behavior).

This most likely sounds like a [zed-latex](https://github.com/rzukic/zed-latex) or a texlab issue.

Happy to re-open if there's something clear that Zed could be doing to improve the situation (extension infrastructure, additional context to LSP, etc).
