### ISSUE TITLE
Rust triple-slash comment [///] breaking after trait assignment

### ISSUE THREAD

**Issue by marstaik** [zed-industries/zed#18548]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hey all, I have encountered an issue with triple slash comments a few times, and have managed to come up with a minimal reproduction example. It seems to occur after a trait assignment `=` with a template parameter. It does not occur on super-trait inheritance `: traits {}`, or a trait assignment without a template parameter.

```rust
/// I am okay, I am not a trait assignment
/// (peekaboo)
pub trait ImNotTheProblem<K, T>: Fn(K) -> () {}

/// I don't have any type parameters
/// So I dont break
pub trait ImAlsoNotTheProblem = Fn(u32) -> ();

/// After me, I break comments because of the type parameter.
/// If you comment out the following line, the issue disappears
pub trait ImTheProblem<K> = Fn(K) -> ();

/// Line 1
/// Line 2 (I break)
```

<img width="549" alt="image" src="https://github.com/user-attachments/assets/9f1b8e44-7757-48ae-9eb0-509b513c448f">

### Environment

Zed: v0.154.3 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by marstaik** [comment]
As a side. note, there are some weird syntax colors happening with each of the 3 variants.
In the first example, `K` is symbol blue.
In the second example 'u32' is white when it should be symbol blue.
In the third example 'K' is const purple when it should be symbol blue.

**Comment by osiewicz** [comment]
This syntax is valid only in nightly. I'd suggest filling an issue with [tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust) instead, as we depend on it for the AST we do highlighting on.

**Comment by notpeter** [comment]
Since this is an upstream issue and is a night-only syntax, I'm going close this.

@marstaik Can you please file an issue upstream with [tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust/issues) and link that issue in a comment below.

Thanks for reporting.
