### ISSUE TITLE
GUI file manager

### ISSUE THREAD

**Issue by trymeouteh** [zed-industries/zed#18563]
### Check for existing issues

- [X] Completed

### Describe the feature

A GUI file manager simular to Windows Explorer or Nemo on Linux Mint

When managing files in this built in file manager, it will update the local history accordingly.

### If applicable, add mockups / screenshots to help present your vision of the feature

- Icon View
- List View
- Multiple Tabs
- Perminately Delete Files/Folders option

**Comment by jansol** [comment]
> When managing files in this built in file manager, it will update the local history accordingly.

What does this mean?

**Comment by jansol** [comment]
I have never used VScode, I don't know what "local history" refers to there. I take it it doesn't refer to automatically staging/committing things to git?

**Comment by notpeter** [comment]
While it's fun to think about being able to do everything in Zed, we're unlikely to implement a Finder/Windows Explorer/Midnight Commander competitor any time soon.

For the moment I'd settle for undo:
- https://github.com/zed-industries/zed/issues/5039
