### ISSUE TITLE
can't tab through input fields in project search after latest update

### ISSUE THREAD

**Issue by hedefalk** [zed-industries/zed#18575]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have:

```
  {
    "context": "Editor && !showing_completions",
    "bindings": {
      "tab": "editor::Indent"
    }
  }
```

for indenting in _editor_ context only.

Since last update I cannot tab through the fields of project search, but just insert tabs instead:

<img width="746" alt="image" src="https://github.com/user-attachments/assets/fcd4b6ba-a7f6-479a-ae50-a9b51e88293f">

I'm positive this worked before but it seems the "Editor && !showing_completions" context is now active even if cursor is in project search. If I remove my keysettings it works as normal.

### Environment

Zed: v0.154.3 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by hedefalk** [comment]
I've tried all kinds of resetting by looking at defaultkeymap but nothing seems to work but removing my existing keymap for tab:

```
{
    "context": "ProjectSearchBar",
    "bindings": {
      "tab": "menu::SelectNext"
    }
  },

  {
    "context": "ProjectSearchBar > Editor",
    "bindings": {
      "tab": "menu::SelectNext"
    }
  },
  {
    "context": "ProjectSearchBar && in_replace > Editor",
    "bindings": {
      "tab": "menu::SelectNext"
    }
  },
  {
    "context": "ProjectSearchView",
    "bindings": {
      "tab": "menu::SelectNext"
    }
  }
```

Is there any good documentation on these contexts?

**Comment by CharlesChen0823** [comment]
this is interesting, i don't set any keybindings for this, `tab` always worked IIRC in windows.

**Comment by JosephTLyons** [comment]
I also don't have any keybindings and tab has always worked for me to cycle through input fields in project search. 🤔

**Comment by notpeter** [comment]
There is some context documentation here:
- https://zed.dev/docs/key-bindings#contexts

But it definitely needs some work:
- #14718 

We've recently added `debug: open key context view` (accessible from the command palette) which definitely can help shed some light on this stuff:

<img width="823" alt="Screenshot 2024-12-03 at 16 20 04" src="https://github.com/user-attachments/assets/514aa1ac-fa7a-4599-8ff6-4f3faaf09bce">

The above is the "Find in files" and it's `Editor && mode=single_line` while in a normal editor it's `Editor && mode=full`. You should be able to adjust your keybindings appropriately, either by changing the context of your existing bind or by rebinding `Editor::Tab` in the `BufferSearchBar` context.

There's definitely some complexity here, but I think this is behaving as designed.

**Comment by hedefalk** [comment]
I still can't figure this out.

I have:


```
{
    "context": "Editor && !showing_completions",
    "bindings": {
      "tab": "editor::Indent"
    }
  },
  {
    "context": "ProjectSearchBar > Editor",
    "bindings": {
      "tab": "menu::SelectNext"
    }
  }
```

According to the rules defined at https://zed.dev/docs/key-bindings#precedence they are of the same level and therefore the  and therefore the latter one should take precendence. It doesn't:

<img width="1154" alt="Image" src="https://github.com/user-attachments/assets/aac5939e-6369-4240-b81c-2910f4ce15b3" />


The other suggestion with `Editor && mode=single_line`  doesn't parse?

<img width="1085" alt="Image" src="https://github.com/user-attachments/assets/cea9a3d4-0975-4930-9b5b-5207e9986424" />
