### ISSUE TITLE
Mouse pointer and cursor positions mismatch on Wayland

### ISSUE THREAD

**Issue by donjan** [zed-industries/zed#18579]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After a while, the mouse pointer position doesn't match the cursor any more.
Clicking into the editor puts the cursor further to the down and right than expected. See attached video.
Restarting Zed doesn't help.

### Environment

Zed: v0.154.3 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/f7ad9020-dcd8-4ea7-baa8-f955237706c4

### If applicable, attach your Zed.log file to this issue.
-

**Comment by notpeter** [comment]
Are you by chance using scaling/HiDPI, perhaps with fractional scaling (e.g. 125% or 150%)
![image](https://github.com/user-attachments/assets/c5fbf6b3-1bc7-4445-a7e8-998db89c0eec)

**Comment by donjan** [comment]
Scaling is at 1x, fractional scaling is off, no nondefault DPI settings.

It might be connected to switching between the built-in laptop screen and 4k monitor when I move around during the day. Will have to test it when I can close down everything (since restarting only Zed still exhibits the issue, I'd have to restart the desktop session).

**Comment by donjan** [comment]
After a bit of restarting, I can't reproduce the correct behaviour any more. The text cursor is always off compared to the mouse cursor. I'd assume it's due to a Zed update, not a environmental change.

**Comment by donjan** [comment]
Zed 0.157.5 does not show the problematic behaviour anymore.
I'll pipe up if it comes back, but until then, no need to keep this open.

**Comment by Bahnschrift** [comment]
I'm running to this issue with zed 0.167.1 on Hyprland. Interestingly, this only seems to be an issue in the editor (other text is fine), and is also an issue in vscode (when it's running under wayland), so I'm not really sure if this a zed issue, wayland issue, or some other library.
