### ISSUE TITLE
Cannot insert ‘@’ symbol with Latin American keyboard layout on MacBook Pro after version 0.154.4

### ISSUE THREAD

**Issue by gabwill10** [zed-industries/zed#18607]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since version 0.154.4, my Latin American keyboard layout on a MacBook Pro (Sequoia) does not allow me to insert the ‘@’ symbol using the usual alt+q combination. I tried changing the key combination, but nothing works. This issue is exclusive to Zed editor, as I have tested the same layout in other editors and it works fine. The only way I was able to insert the ‘@’ symbol was by changing the keyboard configuration entirely.

Please investigate and fix this issue, as it affects the usability of the editor with Latin American keyboards on Mac.

### Environment

Zed editor 0.154.4
MacBook Pro M1 - sequoia

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
ref #18196

**Comment by angel77lgo** [comment]
The same thing happens to me

**Comment by gabwill10** [comment]
> The same thing happens to me

You can resolve like this:

`[
  {
    "bindings": {
      "alt-q": null
    }
  `}]

in your keymap.json

**Comment by angel77lgo** [comment]
it worked, thanks!!
