### ISSUE TITLE
SSH remoting erroneously uses client binary paths for remote language servers

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#18618]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Slightly related to #18616 

When using the new SSH remoting, if the client specifies a custom binary path for language servers, that path is sent to the remote. In my case this caused all language servers to break since one end was NixOS and the other was Ubuntu, so the LSP binary paths did not match up and the language servers could not be launched.

### Environment

Zed: v0.156.0 (Zed Dev 051627c4493b5f5446cb3957576be89899b1d386)
OS: Linux Wayland nixos 24.11 / ubuntu 24.04 
Memory: 128GiB /  32 GiB
Architecture: x86_64
GPU: N/A

**Comment by ConradIrwin** [comment]
As of v0.158 you should now be able to create a settings file on the remote that takes precedence over your local settings. Does that work for you?

**Comment by jansol** [comment]
Does that mean the normal zed settings on the remote? Those are what I get when I run `zed: open server settings`. Those do indeed specify a binary for clangd but not for taplo nor rust-analyzer.

**Comment by mikayla-maki** [comment]
I'm not sure what your question is @jansol. Right now we're using the same thing that VSCode does, where your local settings are copied up, `zed: open settings`, and then your server settings, `zed: open server settings`, are applied on top of those. Does that clarify how your binary resolution is happening?

**Comment by jansol** [comment]
It does, yes.

So it is using the settings from `~/.config/zed/settings.json` on the remote, where I've let it pick up the LSPs from PATH instead of defining them manually since that worked fine when sitting physically at that machine and helped keep the config a bit shorter. Guess I'll have to specify explicit paths for all LSPs I use then.

**Comment by mikayla-maki** [comment]
> Guess I'll have to specify explicit paths for all LSPs I use then.

No? Don't you just have to change your remote server's settings to use the binaries on your PATH? I think I'm missing something.
