### ISSUE TITLE
Accessibility: Ctrl+Scroll to increase/decrease buffer font size

### ISSUE THREAD

**Issue by fornellas-udemy** [zed-industries/zed#18627]
### Check for existing issues

- [X] Completed

### Describe the feature

My eye sight is pretty bad, and I rely heavily on increasing / decreasing the font size frequently, on all apps I use. Generally speaking, ctrl+scroll works (eg: Chrome, Sublime, other editors), but Zed seems to only allow font size change via the keyboard:

https://zed.dev/docs/key-bindings#global
ctr +, ctrl -

It is very handy to _also_ be able to control font size via ctrl+scroll, like in other apps.

Can we have a key binding to allow this to be set?

Thanks.

**Comment by danilo-leal** [comment]
Hey, thanks for the issue! I'm a bit confused by the scroll keybinding there—just pressing command (given I'm on a mac) and scrolling doesn't affect the font-size in any of the apps you mentioned... In Zed, if you press command and the plus/minus key, you should already see the buffer font-size change.

**Comment by fornellas-udemy** [comment]
> Hey, thanks for the issue! I'm a bit confused by the scroll keybinding there—just pressing command (given I'm on a mac) and scrolling doesn't affect the font-size in any of the apps you mentioned... 

@danilo-leal yeah... MacOS is a special cookie. In all other major OSs, this works fine. I used it for a while, and these "accessibility papercuts" were too big of a burden, I moved away.

>  In Zed, if you press command and the plus/minus key, you should already see the buffer font-size change.

Absolutely, but you have to understand the use case. My eye sight is bad, I zoom in and out a LOT during the day. Every change, requires 5+ key presses on every direction, which is a hassle. I suffer from a condition similar to carpal tunnel syndrome, so I really need to save my movements (even [built my own keyboard](https://github.com/fornellas/3dpkbd2) to fit my use case), and all these small things, stack up to a bad experience.
