### ISSUE TITLE
`low_speed_timeout_in_seconds` not respected: request or operation took longer than the configured timeout time (ollama, o1-mini, o1-preview, etc.)

### ISSUE THREAD

**Issue by firleaf** [zed-industries/zed#18647]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In version v0.156.0 (Preview) the setting `language_models.ollama.low_speed_timeout_in_seconds` is not being respected. This seems to be a regression as the setting is being respected in v0.155.2 (Stable).

```jsonc
// settings.json
{
  "telemetry": {
    "diagnostics": true
  },
  "features": {
    "inline_completion_provider": "none"
  },
  "assistant": {
    "default_model": {
      "provider": "ollama",
      "model": "qwen2.5-coder:7b"
    },
    "version": "2"
  },
  "vim_mode": true,
  "language_models": {
    "ollama": {
      "api_url": "http://localhost:11434",
      "low_speed_timeout_in_seconds": 300,
      "available_models": [
        {
          "provider": "ollama",
          "name": "qwen2.5-coder:7b",
          "keep_alive": 300,
          "max_tokens": 128000
        }
      ]
    }
  }
}

```

### Environment

Zed: v0.156.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[WARN] request completed with error: request or operation took longer than the configured timeout time
</pre></details>

**Comment by simjak** [comment]
same for o1, it is not reacting to "low_speed_timeout_in_seconds": 300,

**Comment by gianpaj** [comment]
o1 mini errors out after 10 seconds

![image](https://github.com/user-attachments/assets/bc7ba453-2156-4420-a1a9-1fae7e7a9506)

config
```json
{
  "assistant": {
    "default_model": {
      "provider": "openai",
      "model": "o1-mini"
    },
    "version": "2",
    "openai": {
      "low_speed_timeout_in_seconds": 50
    }
  },
```

macOS Zed version: `0.156.2`

**Comment by rorads** [comment]
This issue seems to be a generalised across models.

```
Zed: v0.156.2 (Zed)
OS: macOS 14.4.0
Memory: 18 GiB
Architecture: aarch64
```

I have tried to set `low_speed_timeout_in_seconds` to both large and small values to try to observe different behaviour and haven't been able to discern anything. 

In my case, openai o1 models given large `/file` parameters are the only ones which fail. M3 pro might mean that ollama is unaffected given I'm using 3.2 3B and responses are generally very snappy.

For o1 models I'm assuming this is partly because nothing is streamed to Zed whilst the model is "thinking", but I would expect `low_speed_timeout_in_seconds` to handle this, unless I'm understanding it's expected usage wrong. 

FWIW I did try to input a value < 1 but this is validated against.

**Comment by nanobeep** [comment]
Can confirm, I'm seeing the same behavior on macos with `low_speed_timeout_in_seconds` not being respected and 10 seconds being the effective timeout, which makes o1-mini and o1-preview unusable for most requests.

**Comment by nanobeep** [comment]
Took a quick look at the codebase and noticed these hard-coded 10 second "timeouts":

https://github.com/zed-industries/zed/blob/main/crates/rpc/src/peer.rs#L97

```rust
pub const RECEIVE_TIMEOUT: Duration = Duration::from_secs(10);
```

https://github.com/zed-industries/zed/blob/main/crates/client/src/client.rs#L96

```rust
pub const MAX_RECONNECTION_DELAY: Duration = Duration::from_secs(10);
```


I'm not a rust dev and not familiar with this codebase, but maybe that will help someone who is.

**Comment by nanobeep** [comment]
Also, @firleaf - if possible, it might be good to update the title of this issue since I had a hard time finding it and I ignored it multiple times since it seemed only applicable to ollama. It is probably affecting a lot of people trying to use o1-mini / o1-preview and this would get more thumbs up and attention if those people can find it easier. Thanks!

**Comment by nanobeep** [comment]
Here's a temporary fix:

I got around this for now by increasing the timeout here:

https://github.com/zed-industries/zed/blob/main/crates/rpc/src/peer.rs#L97

```rust
pub const RECEIVE_TIMEOUT: Duration = Duration::from_secs(300);
```

Now o1-mini, o1-preview, etc work fine and I no longer get the timeout error after 10 seconds.

Just a temporary hack until the experts can resolve this, but if anyone wants to have it working right now, it works.

I've never built a rust project, but it was surprisingly easy following the instructions here: https://zed.dev/docs/development/macos - took me less than 10 minutes from start to finish, so not bad at all.

Also, thanks @firleaf for updating the title!

**Comment by firleaf** [comment]
Ok, so from what I've gathered, the `low_speed_timeout_in_seconds` setting is applied only if the connection has been established and data has been sent already. The request will be canceled, if more than `low_speed_timeout_in_secons` seconds elapse [in between reads](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.read_timeout) (in this case tokens sent by the model provider). The `RECEIVE_TIMEOUT` on the other hand will cancel the request, if the client has not yet received any data from the model provider. This means, that requests for model configurations with a high time-to-first-token (in this case more than ~10 seconds) will timeout based on this.

I believe there are two ways forward regarding this issue. Either unify the semantics of `RECEIVE_TIMEOUT` with `low_speed_timeout_in_seconds`, so that the timeout for _low speed_ applies to the receive timeout aswell, or make `RECEIVE_TIMEOUT` configurable in zed's settings.

**Comment by harveyfullstack** [comment]
For anyone who doesn't want to go through the entire build process themselves, the last official version before this issue is [0.151.2](https://zed.dev/releases/stable/0.151.2).

**Comment by nanobeep** [comment]
> For anyone who doesn't want to go through the entire build process themselves, the last official version before this issue is [0.151.2](https://zed.dev/releases/stable/0.151.2). Additionally, you'll want to set this in your config to prevent Zed from auto-updating: `"auto_update": false`.

Thanks, but downloaded and tried to get it working with o1-mini/o1-preview models and no luck: `Unsupported parameter: 'stop' is not supported with this model`

So far only custom build works for me with the o1-* models.
