### ISSUE TITLE
Python unittest tasks do not run within venv

### ISSUE THREAD

**Issue by jrderuiter** [zed-industries/zed#18649]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running a Python unittest task from the UI that imports a project-specific dependency (e.g. installed into the projects virtual environment) fails as the task runs tests using the system-default Python and not the virtual environment.

You can recreate this issue by creating a new Python project with a specific dependency:

```
poetry new --src test-example
cd test-example
poetry init
poetry add returns
```

And then creating dummy test (`tests/test_example.py`) that imports that dependency: 

```python
import unittest

class TestImport(unittest.TestCase):
    def test_import(self):
        import returns

if __name__ == "__main__":
    unittest.main()
```

which results in the following error when run from the UI:

```
======================================================================
ERROR: test_import (tests.test_example.TestImport.test_import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/.../tests/test_example.py", line 15, in test_import
    import returns
ModuleNotFoundError: No module named 'returns'
```

even though running tests with an activated virtual env in the terminal runs fine:

```
❯ python tests/test_example.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

Note that `detect_venv` is configured for zed and tested to be working in the terminal:

```json
{
  "terminal": {
    "detect_venv": {
      "on": {
        "directories": [".venv", "venv"],
        "activate_script": "fish"
      }
    }
  }
}
```

To fix this issue, the tasks should be run using the Python of the virtualenv instead of the global Python.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 15.0.0
Memory: 36 GiB
Architecture: aarch64

**Comment by jrderuiter** [comment]
Looking at the code it seems that the tasks run commands that always call the system-wide python3 instead of attempting to use the virtual env. 

We could probably address this issue by instead trying to discover the virtual env and using it if it exists. Discovery could use the same logic as is being used in the terminal code.

Implementation-wise, would it be best to reuse the existing settings and logic that’s being used for the terminal? Or maybe it makes more sense to have a language level configuration option for the venv and use this for both the terminal and these tasks?

A language level setting would also potentially allow us to pass the venv setting to pyright as well, allowing us to emit the extra setting we currently now need to set for pyright.

**Comment by osiewicz** [comment]
Heads up, I am working on Venv detection in https://github.com/zed-industries/zed/pull/19576; once this PR lands, I will work on exposing the currently selected toolchain to tasks. As you've noted @jrderuiter we always use global python, so it should be as "easy" as using the python from the venv (I assume we don't need to actually activate the virtual env and it should be enough to use the python binary from venv?)

**Comment by jrderuiter** [comment]
Great, that should be fine indeed! I’ll pick this PR up again in a week, though I might wait for your PR to land first.

**Comment by SirSilver** [comment]
I actually think that this issue is related to [this](https://github.com/zed-industries/zed/issues/19227) issue. I can make tasks running within venv with [this](https://github.com/zed-industries/zed/discussions/18806#discussioncomment-10868677).

**Comment by PlexSheep** [comment]
This is half working for me with the following setting for pyenv:

```jsonc
    "terminal": {
        "font_family": "FiraCode Nerd Font",
        "detect_venv": {
            "on": {
                // Default directories to search for virtual environments, relative
                // to the current working directory. We recommend overriding this
                // in your project's settings, rather than globally.
                "directories": [
                    ".venv",
                    ".env",
                    "env",
                    "venv",
                    "$PYENV_ROOT/versions",
                    "/home/plex/.pyenv/versions"
                ],
                // Can also be `csh`, `fish`, and `nushell`
                "activate_script": "default"
            }
        }
    }
```
And also a `pyrightconfig.json` in my project root:

```json
{
    "venv": "sennen",
    "venvPath": "/home/plex/.pyenv/versions/sennen/bin/python"
}
```

What works is tasks and opening a new shell, what does not work is clicking the run icon next to pytest functions, as it does not have the module I'm developing installed then.
