### ISSUE TITLE
Cursor size is zoom, even after I can see that it is resolved.

### ISSUE THREAD

**Issue by rajendrakumaryadav** [zed-industries/zed#18643]
### Check for existing issues

- [X] Completed

### Describe the feature

I found it in the existing issue. Still, the issue is persisting.

https://github.com/zed-industries/zed/pull/17496

### If applicable, add mockups / screenshots to help present your vision of the feature

![screenshot](https://github.com/user-attachments/assets/afafe51a-7301-4eb1-b89f-1d03f73f6c35)

**Comment by mikayla-maki** [comment]
The issue has been solved on main, even though it hasn't been released yet :)
