### ISSUE TITLE
is it possible to have different colors for the terminal, context window, and codespace?

### ISSUE THREAD

**Issue by RustoMCSpit** [zed-industries/zed#18653]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/user-attachments/assets/9d265355-e7cb-4461-825c-8943cb1cea50)
![image](https://github.com/user-attachments/assets/4565ab33-3fd8-41da-8a3f-5eb9f010da9f)

all the themes look like the above for me: the terminal, context window, and codespace all are colored the same. this is an eyesore. is it possible to theme these parts of the gui differently? say have a dark terminal with a bright codespace as if the two images were fused? am i missing something?

**Comment by RustoMCSpit** [comment]
> Yes, themes explicitly specify the background colors for the editor, panels and the terminal separately. A lot of other elements also have their own backgrounds.

oh? sorry i didnt know as all the built in themes share colors across editor, terminal, panel. do i install these other ones off of an unoffical github repo or?

**Comment by jansol** [comment]
A number of themes are available as extensions, you can install them directly from within zed (click on the menu in the top right where it shows your github pfp or just a `v` if you're not signed in). You can also manually place custom theme .json files in zed's config directory as described in the docs: https://zed.dev/docs/themes

There is also a 3rd party theme gallery: https://zed-themes.com/ with a graphical theme editor (TIL) if you want to roll your own.
