### ISSUE TITLE
Remap x to delete but not update default register in Vim mode

### ISSUE THREAD

**Issue by labrnth** [zed-industries/zed#18681]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm not sure if this is a bug or a feature request, but I'm unable to remap X in Vim mode, to delete but not update the default register. I generally copy stuff into macOS pasteboard and then will use X to delete characters in a file, and then paste from the pasteboard using P or while in insert mode (⌘ + V).

If there is something already in the pasteboard and I use X to delete characters, it takes the last deleted character and put's it into the default register/pasteboard. Having the ability to prevent this would be highly desirable in my situation as it's built deeply into my muscle memory.

### Environment

Zed: v0.154.4 (Zed)
OS: macOS 14.7.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

In Neovim I use the following mapping (lua) config to acheive this:

map("n", "x", '\"_x', { desc = "remap x to delete but not update default register", noremap = true})

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17238873/Zed.log)

</pre></details>

**Comment by ConradIrwin** [comment]
You should be able to do something like:

```
[
  {
    "context": "VimControl",
    "bindings": {
      "ctrl-shift-x": "vim::DeleteRight",
      "x": ["workspace::SendKeystrokes", "\" _ ctrl-shift-x"]
    }
  }
]
```
