### ISSUE TITLE
Terminal shortcut appears not to work if grave is a dead key

### ISSUE THREAD

**Issue by ISSOtm** [zed-industries/zed#18717]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My keymap is set to `en gb extd`, which notably has the grave `` ` `` character as a dead key. Unfortunately, this means that the Terminal shortcut, `` Ctrl+` ``, instead writes the backtick/grave “placeholder” character.

### Environment

Zed: v0.155.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 7.1 GiB
Architecture: x86_64
GPU: AMD Radeon 760M (RADV GFX1103_R1) || radv || Mesa 24.2.3-arch1.1

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/17252667/Zed.log)

**Comment by notpeter** [comment]
Yep.  This is a known issue.  We have begun long-term work on altering key mapping system to better handle dead-keys and related issues with non-US keyboards (e.g. some languages use `cmd->` to cycle between app windows, where as ANSI US uses <kbd>cmd-`</kbd>.

There is some discussion here:
- https://github.com/zed-industries/zed/discussions/17031

And a number of similar open issues [label: macos, label:kb](https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+keyboard+label%3A%22keymap+%2F+key+binding%22+label%3Amacos) 

Thanks for reporting.
