### ISSUE TITLE
ProjectPanel creating on renaming field still listens for keybindings when entering file name

### ISSUE THREAD

**Issue by joezak11** [zed-industries/zed#18716]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the `ProjectPanel` active I have a keybinding for `rename` to `r` however when I try to create a file and the name contains the letter `r` in the input field it is blocked and does not type.

### Environment

```
Zed: v0.155.2 (Zed)
OS: Linux Wayland manjaro unknown
Memory: 7.5 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.2-arch1.1
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
you need mapping keybinding like this`"context": "ProjectPanel && not_editing",`

**Comment by joezak11** [comment]
Thank you so much, that does indeed work. I thought I missed something in the docs and went through it again but did not find any reference to `not_editing`
