### ISSUE TITLE
Colocate extension with tree-sitter grammar

### ISSUE THREAD

**Issue by reesericci** [zed-industries/zed#18731]
### Check for existing issues

- [X] Completed

### Describe the feature

I am writing a language with a Tree-sitter parser, and it's not possible to include the Zed extension with the grammar as part of a monorepo, since it always wants to pull from a git repo. This is an issue because it makes the Zed extension go out of sync with grammar updates, requiring me to update multiple places.

**Comment by notpeter** [comment]
Yes, our current assumption is the tree-sitter grammars will be published in their own repo. This is the standard for how tree-sitter grammars are published -- one grammar per repo, in the root of the repo.

I understand this may be a bit of a headache if you are building a grammar for the sole purpose of using it in a zed extension, but it ensures that your tree-sitter grammar may also be easily reused by other non-zed editors that include tree-sitter support (NeoVim, Emacs, Helix, VSCode Anycode, etc).

**Comment by reesericci** [comment]
It's moreso that I have a monorepo for the grammar and compiler.

**Comment by notpeter** [comment]
> It's moreso that I have a monorepo for the grammar and compiler.

Gotcha, so the issue is that you have a monorepo with a compiler that also includes the grammar.  For similar reasons, you will want to publish a dedicated repo with the tree-sitter.

If you want to avoid duplication you could setup that tree-sitter repo as a submodule of the compiler repo and make sure they are updated in lock-step or you could just create a script that runs nightly and updates the tree-sitter repo to reflect changes in the upstream mono repo.

**Comment by notpeter** [comment]
We actually can support tree-sitters under a subdirectory in the repo by adding a `path` key like this:
```
[grammars.apex]
repository = "https://github.com/aheber/tree-sitter-sfapex"
commit = "c99ad4b16d112fea91745e3f1b769754239fdaba"
path = "apex"
```

Sadly, it still would be a kind of unergonomic to keep the Zed extension and the tree-sitter in the same repo.  You'd have to commit the tree-sitter bits, get a commit id and then make another commit references that earlier commit.  Awkward, but possible.

**Comment by reesericci** [comment]
The tree-sitter grammar is still in a monorepo with the compiler, so I did use the path thingy to specify the location of the grammar
