### ISSUE TITLE
window not open and does not load the previous project 

### ISSUE THREAD

**Issue by haniissa** [zed-industries/zed#18759]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1-it give me `failed to load the database file`
2-and the zed window not open until I press `Bring to front` to show the window 

### Environment

in windows window not open and database for files not load it
and in msys2 keyboard not work !

**Comment by co-bby** [comment]
#18705  fixes it.

**Comment by SomeoneToIgnore** [comment]
And also we have https://github.com/zed-industries/zed/issues/18610 so I'll close it as a duplicate.

**Comment by haniissa** [comment]
what about keyboard in msys2?

**Comment by SomeoneToIgnore** [comment]
Nothing good, as it seems: https://github.com/msys2/MINGW-packages/issues/22071
