### ISSUE TITLE
dart: Wrong indent on newline

### ISSUE THREAD

**Issue by CalebQ42** [zed-industries/zed#18758]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a dart project and hit enter where the newline should have an increased indent level, such when starting a function's body.

### Environment

Zed: v0.155.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 13.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.4-arch1.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Screencast From 2024-10-05 01-02-48.webm](https://github.com/user-attachments/assets/108e7427-b4d5-4239-8977-82c97eeb5d84)

**Comment by notpeter** [comment]
I am not a dart developer so this is entirely blind, but I took a crack at fixing it here:
- https://github.com/zed-industries/zed/pull/18845

Can you test that and see if it works as expected?

**Comment by CalebQ42** [comment]
Looks like this fixes #18845, thank you!
