### ISSUE TITLE
Rule eslint(prettier/prettier) not showing any sign knowing that the code is not following the rule

### ISSUE THREAD

**Issue by hungify** [zed-industries/zed#18757]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed notices that the code does not follow the rules and collects it to display in the project diagnostics tab. However, the problematic line does not show any sign of the issue faced.

![CleanShot 2024-10-05 at 12 13 56@2x](https://github.com/user-attachments/assets/285e52fc-3320-4fc1-9ba0-af6367486ce0)

vs 

![CleanShot 2024-10-05 at 12 13 00@2x](https://github.com/user-attachments/assets/d1982008-1eef-4f04-b7dc-7ba91e008cd4)

### Environment

Zed: v0.156.0 (Zed Preview)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Can you include a file with a minimal reproduction case?

**Comment by hungify** [comment]
```
Zed: v0.157.3 (Zed Preview)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64
```

Great news! In version v0.157.3 (Zed Preview), the issue has been resolved.

warning

> ![Zed Preview 2024-10-14 21 34 04](https://github.com/user-attachments/assets/c79a8db7-2af5-4a32-b3de-2d56ddedebf1)


error

> ![CleanShot 2024-10-14 at 21 38 36@2x](https://github.com/user-attachments/assets/5506533c-7dca-4037-91ac-db7c2c1b6f94)
