### ISSUE TITLE
Add language server support to newly created proto extension

### ISSUE THREAD

**Issue by prskr** [zed-industries/zed#18762]
### Check for existing issues

- [X] Completed

### Describe the feature

As discussed with @maxdeviant in zed-industries/extensions#1479 I would like to add basic language server support to the newly created (thanks again!) proto extension.

The language server in question is [this one](/asorda/protobuf-language-server).

**Comment by eth0net** [comment]
So I've tried to use the proto extension, but the linked language server isn't available! Any chance we can switch it to use the buf language server?

**Comment by prskr** [comment]
the [buf LS](/bufbuild/buf-language-server) is archived, whereas the other one is actively maintained. The only inconvenience is that you've to install [the other one](/lasorda/protobuf-language-server) manually because it doesn't have release artifacts (yet) and AFAIK the WASI runtime does not allow to run arbitrary commands (as `go install ...`) so there's currently no possibility to auto-install the necessary binary

**Comment by eth0net** [comment]
That link works, the one in the PR above is incorrect then. Thanks for the updated link!

**Comment by prskr** [comment]
I fixed the link in the description but this needs documentation anyway and probably updated default settings (if not already done 😅) I forgot to add it 🙈
