### ISSUE TITLE
Memory usage super high

### ISSUE THREAD

**Issue by huhu415** [zed-industries/zed#18769]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I set the proxy in my zed config file: "proxy": "http://127.0.0.1:6152 socks5://127.0.0.1:6153", and then I set the
``
which zed
zed: aliased to all_proxy=socks5://127.0.0.1:6153 zed
``
When I open it with zed, the memory is 100GB+, then when I don't open it with `zed` command, but just click on the icon, zed still uses 50GB+ of memory.

### Environment

Zed 0.155.2

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac15,6
      Model Number: MRX63CH/A
      Chip: Apple M3 Pro
      Total Number of Cores: 11 (5 performance and 6 efficiency)
      Memory: 18 GB
      System Firmware Version: 10151.140.19
      OS Loader Version: 10151.140.19

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="431" alt="截屏2024-10-06 11 53 37" src="https://github.com/user-attachments/assets/51bfd999-f46b-439c-993a-033d1fcf471d">
<img width="1004" alt="截屏2024-10-06 11 53 42" src="https://github.com/user-attachments/assets/3495b104-0876-4578-91bc-a29e2ffb8bab">

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/17268124/Zed.log)

**Comment by notpeter** [comment]
> I set the proxy in my zed config file: "proxy": "http://127.0.0.1:6152/ socks5://127.0.0.1:6153",

This looks wrong. The value should be `http://127.0.0.1:6152/` or `socks5://127.0.0.1:6153` not both.
```
[ERROR] Error parsing proxy settings: invalid uri character
```

1. Can copy paste the relevant line from your settings?
2. Does the issue happen if you start with an empty settings.json?
3. Are you open (restoring) an existing workspace directory when this happens?
4. Does it happen if you open zed to an empty workspace (`mkdir /tmp/ws && zed /tmp/ws`)?
5. Do you have any extensions installed? If yes, can you try uninstalling all of them?

I have recently seen folks reporting something similar when opening a workspace with a large number of ansible yaml files with the Ansible Zed extension, I wonder whether this is something similar.

**Comment by huhu415** [comment]
I restarted zed, then changed the correct proxy, and opened a different project, and it worked, I'm afraid I can't reproduce it.🙁

**Comment by huhu415** [comment]
i will do that when i see this bug again
