### ISSUE TITLE
Keymap ignored in `repl: sessions`

### ISSUE THREAD

**Issue by donjan** [zed-industries/zed#18761]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed's default shortcuts are _Ctrl+w_ to close a tab and _Ctrl+Shift+w_ to close the editor.
I prefer a more defensive _Ctrl+Shift+w_ to close a tab, closing the editor is unassigned.

```json
    "bindings": {
      "ctrl-w": null,
      "ctrl-shift-w": "pane::CloseActiveItem",
    }
```

This works well until I check the REPL sessions with `repl: sessions`. In that tab, Zed appears to use the default shortcuts, so my _Ctrl+Shift+w_ shuts down the whole editor. And _Ctrl+w_ closes this tab.

Having two sets of shortcuts depending on the active tab is bad UX.
I haven't checked for other "special" tabs that ignore the users keymap.

### Environment

Zed: v0.155.2 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

**Comment by CharlesChen0823** [comment]
can you share your whole keymaps.json, i tested in windows/ubuntu, it worked as expected.

**Comment by notpeter** [comment]
Yes, please share you complete keymap, in particular the context matters.

The default `ctrl-w` mapping under Linux is under the `Pane` context so if you're looking to remap you'll want to match that:
https://github.com/zed-industries/zed/blob/8f27ffda4d99f31b323e523bc3490339c7864bfe/assets/keymaps/default-linux.json#L246-L252

```json
[
  {
    "context": "Pane",
    "bindings": {
      "ctrl-w": "pane::CloseActiveItem",
      "ctrl-w": "pane::CloseActiveItem",
  }

**Comment by donjan** [comment]
```
$ cat .config/zed/keymap.json 
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: open default keymap`
// from the command palette.
[
  {
    "context": "Workspace",
    "bindings": {
      // "shift shift": "file_finder::Toggle"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "ctrl-w": null,
      "ctrl-shift-w": "pane::CloseActiveItem"
    }
  }
]
```
Not sure if this was the default context or I pasted it from a random search, but changing `"context": "Editor",` to `"context": "Pane,` makes it work for `repl: sessions` as well.
Thank you!
