### ISSUE TITLE
Project Panel: Cannot create directory in parent directory within parent directory if path looks like `directory/subdirectory`

### ISSUE THREAD

**Issue by arayofcode** [zed-industries/zed#18770]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried creating a file in a directory that contains only a subdirectory using the project panel. On doing this, it keeps creating the file in subdirectory inside it. That is, for path `myDir/subDir`, on right clicking `myDir` and creating new directory, the new file path is always `myDir/subDir/newFile.txt`.

Steps to Reproduce:
1. Create a new directory in workspace
2. Use project panel to create a subdirectory within this directory
3. Right click on parent dir to create another file or dir. It creates the new file in subdirectory.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
This appears to be a regression. This was originally reported here:
- https://github.com/zed-industries/zed/issues/17252

And was fixed here:
- https://github.com/zed-industries/zed/pull/17520

But I can reproduce what you're seeing with the current zed nightly.
I'll see if I can do the bisect and figure out when it broke.

As a workaround, you can add the following to your settings:
```
  "project_panel": {
    "auto_fold_dirs": false
  },
```
Thanks for reporting.

**Comment by notpeter** [comment]
Ok. I spoke with @osiewicz and now understand what's happening:

1. We currently do not have mouse click handlers for selecting amongst the folded directories, but keyboard navigation works (left / right)
2. Bug: New File / New Folder don't work correctly when selecting a folded dir -- the last dir is always used. Everything else in the context menu (cut/copy/paste/delete/copy path/find in folder/etc) works, just not new file / folder.

Hopefully we'll get this sorted in the coming days. Thanks for reporting.
