### ISSUE TITLE
Syntax highlighting for Handlebars

### ISSUE THREAD

**Issue by Edweis** [zed-industries/zed#18772]
### Check for existing issues

- [X] Completed

### Describe the feature

.hbs and .handlebars files do not have syntax highlighting, even when using the `html` extensions.

**Comment by notpeter** [comment]
[Ember Extension](https://github.com/jylamont/zed-ember) includes a Glimmer/Handlebar syntax highlighter.

<img width="728" alt="Screenshot 2024-10-07 at 12 22 48" src="https://github.com/user-attachments/assets/d1bf54be-9595-4ccf-988a-c28987e54240">

**Comment by Edweis** [comment]
Thank you, that's right.

**Comment by Abourass** [comment]
This doesn't seem to work for .handlebar files, and thus, doesn't seem a complete solution

**Comment by notpeter** [comment]
@Abourass 
The extension only configures it for *.hbs:
https://github.com/jylamont/zed-ember/blob/main/languages/glimmer/config.toml

But there's nothing stopping you from selecting "Handlebars" from the language selector for other extensions or adding the following to your settings:

```json
  "file_types": {
    "Handlebars": ["hbs", "handlebars", "mustache"],
  }
```

Feel free to submit a PR upstream to add `handlebars` and then it'll be fixed for ever.
