### ISSUE TITLE
The key bindings in the assistant panel are not working.

### ISSUE THREAD

**Issue by 1925381584** [zed-industries/zed#18798]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/565719af-adcf-421d-be30-88e43c7a4b07)

### Environment

Zed: v0.157.0 (Zed Dev 03c84466c22390bce5802c6ba4f27108d2ab5d61)
OS: Windows 10.0.19045
Memory: 15.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
These work for me on MacOS, so perhaps a Windows specific issue
```
  {
    "context": "AssistantPanel",
    "bindings": {
      "cmd-t": "assistant::NewContext",
      "space f n": "assistant::NewContext"
    }
  },
```

**Comment by CharlesChen0823** [comment]
no, this work in windows
