### ISSUE TITLE
Support of Windows entreprise proxy

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#18797]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run a nightly windows build and i got some issues when the extentions seek for updates exemple i got this error

Language server error: bash-language-server

failed to execute npm info subcommand:
stdout: "{\n  \"error\": {\n    \"code\": \"ETIMEDOUT\",\n    \"summary\": \"request to https://registry.npmjs.org/bash-language-server failed, reason:\",\n    \"detail\": \"This is a problem related to network connectivity.\\nIn most cases you are behind a proxy or have bad network settings.\\n\\nIf you are behind a proxy, please make sure that the\\n'proxy' config is set properly.  See: 'npm help config'\"\n  }\n}\n"
stderr: "npm error code ETIMEDOUT\nnpm error errno ETIMEDOUT\nnpm error network request to https://registry.npmjs.org/bash-language-server failed, reason: \nnpm error network This is a problem related to network connectivity.\nnpm error network In most cases you are behind a proxy or have bad network settings.\nnpm error network\nnpm error network If you are behind a proxy, please make sure that the\nnpm error network 'proxy' config is set properly.  See: 'npm help config'\nnpm error A complete log of this run can be found in: C:\\Users\\yodatak\\AppData\\Local\\Zed\\node\\node-v22.5.1-win-x64\\cache\\_logs\\2024-10-07T08_13_50_101Z-debug-0.log\n"
-- stderr--

0 verbose cli C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\node.exe C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.2
2 info using node@v22.5.1
3 silly config load:file:C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\node_modules\npm\npmrc
4 silly config load:file:C:\Users\yodatak\Downloads\zed-windows (1)\zed-release\.npmrc
5 silly config load:file:C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\blank_user_npmrc
6 silly config load:file:C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\blank_global_npmrc
7 verbose title npm info bash-language-server
8 verbose argv "info" "--cache" "C:\\Users\\yodatak\\AppData\\Local\\Zed\\node\\node-v22.5.1-win-x64\\cache" "--userconfig" "C:\\Users\\yodatak\\AppData\\Local\\Zed\\node\\node-v22.5.1-win-x64\\blank_user_npmrc" "--globalconfig" "C:\\Users\\yodatak\\AppData\\Local\\Zed\\node\\node-v22.5.1-win-x64\\blank_global_npmrc" "bash-language-server" "--json" "--fetch-retry-mintimeout" "2000" "--fetch-retry-maxtimeout" "5000" "--fetch-timeout" "5000"
9 verbose logfile logs-max:10 dir:C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\cache\_logs\2024-10-07T08_13_50_101Z-
10 verbose logfile C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\cache\_logs\2024-10-07T08_13_50_101Z-debug-0.log
11 silly logfile done cleaning log files
12 http fetch GET https://registry.npmjs.org/bash-language-server attempt 1 failed with ETIMEDOUT
13 http fetch GET https://registry.npmjs.org/bash-language-server attempt 2 failed with ETIMEDOUT
14 http fetch GET https://registry.npmjs.org/bash-language-server attempt 3 failed with ETIMEDOUT
15 verbose type system
16 verbose stack FetchError: request to https://registry.npmjs.org/bash-language-server failed, reason: 
16 verbose stack     at ClientRequest.<anonymous> (C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
16 verbose stack     at ClientRequest.emit (node:events:520:28)
16 verbose stack     at _destroy (node:_http_client:875:13)
16 verbose stack     at onSocketNT (node:_http_client:895:5)
16 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
17 error code ETIMEDOUT
18 error errno ETIMEDOUT
19 error network request to https://registry.npmjs.org/bash-language-server failed, reason: 
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose cwd C:\Users\yodatak\Downloads\zed-windows (1)\zed-release
22 verbose os Windows_NT 10.0.22631
23 verbose node v22.5.1
24 verbose npm  v10.8.2
25 verbose exit 1
26 verbose code 1
27 error A complete log of this run can be found in: C:\Users\yodatak\AppData\Local\Zed\node\node-v22.5.1-win-x64\cache\_logs\2024-10-07T08_13_50_101Z-debug-0.log

i open issue too in some extentions 

https://github.com/d1y/dockerfile.zed/issues/10

### Environment

Zed: v0.156.0 (Zed Dev 675673ed5462711916e7824528698fc235d679b2)
OS: Windows 10.0.22631
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>
[Zed.log](https://github.com/user-attachments/files/17275458/Zed.log)

**Comment by notpeter** [comment]
Have you set [`proxy` in zed settings](https://zed.dev/docs/configuring-zed#network-proxy)?

**Comment by yodatak** [comment]
> Have you set [`proxy` in zed settings](https://zed.dev/docs/configuring-zed#network-proxy)?

No but i find something weird i dont need it to install extentions but I need to set proxy in settings did I done something bad or is it linked to proxypac file ?

**Comment by notpeter** [comment]
Your issue title is "Support of Windows enterprise proxy".
I assumed this was because you needed to setup proxy support.
But actually your issue is that installing extensions works, but updating extensions fails?

Please take the time to describe the issue you are having.
Please use multiple sentences. 
Please describe what you are trying to do, what you expect to happen and what is actually happening.

Currently there is insufficient information to dive in.

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/zed-industries/zed/issues/19620
- https://github.com/zed-industries/zed/issues/19806
