### ISSUE TITLE
Remote SSH - Zed fails to load remote files/directories

### ISSUE THREAD

**Issue by dickeyy** [zed-industries/zed#18793]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you open a remote project, Zed fails to list any of the files in the directory you open.

Reloaded window, restarted Zed, removed Dev server and re-added it. Nothing I do seems to fix this.

See the screenshot below.
 
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/360511a2-446a-4909-88d2-e242eb43520b">

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 15.0.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by boetro** [comment]
Ran into this also and followed the steps here: https://github.com/zed-industries/zed/issues/17400#issuecomment-2332567144 to get it working

**Comment by dickeyy** [comment]
@notpeter That didn't seem to work.

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/3800222a-cd91-488c-9d6c-efc1d18960f2">

**Comment by notpeter** [comment]
1. Anything in your Zed.log suggesting what might be happening?
2. What's the remote host OS/distribution/version?

There are significant changes to remoting which are currently in main and will be in Zed Preview on Wednesday.  Would you be willing to build zed and see if this has already been fixed.

```
git clone https://github.com/zed-industries/zed.git
cd zed
git checkout main
git pull
script/linux
cargo run -- ssh://user@host.tld:~/whatever
```

**Comment by sandhawalia** [comment]
> 1. Anything in your Zed.log suggesting what might be happening?
> 2. What's the remote host OS/distribution/version?
> 
> There are significant changes to remoting which are currently in main and will be in Zed Preview on Wednesday. Would you be willing to build zed and see if this has already been fixed.
> 
> ```
> git clone https://github.com/zed-industries/zed.git
> cd zed
> git checkout main
> git pull
> script/linux
> cargo run -- ssh://user@host.tld:~/whatever
> ```

Build from source fixes it. Looking forward to the preview release.
