### ISSUE TITLE
Linux X11: dragging out a Firefox tab onto Zed crashes it

### ISSUE THREAD

**Issue by athre0z** [zed-industries/zed#18811]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open Zed and Firefox
- Create two tabs in Firefox with arbitrary contents
- Drag out a tab into a separate window, dropping it over the Zed window
- SIGABRT

Sometimes it takes 3-4 attempts to crash if both windows are on the same monitor. The chance seems to be higher if the applications are on different screens.

### Environment

Zed: v0.155.2 (Zed)
OS: Linux X11 debian unknown
Memory: 62.7 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3070 Ti || NVIDIA || 535.183.06

Extra info: this is Debian Testing running Gnome.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-07T15:31:50.07828683+02:00 [WARN] unhandled capability registration: Registration { id: "d6d6b084-3566-4321-88d5-66514975c1ed", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-10-07T15:31:55.655321643+02:00 [ERROR] {
  "thread": "main",
  "payload": "already borrowed: BorrowMutError",
  "location_data": {
    "file": "crates/gpui/src/platform/linux/x11/client.rs",
    "line": 1365
  },
  "backtrace": [
    "core::panicking::panic_fmt",
    "core::cell::panic_already_borrowed",
    "<gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::set_cursor_style",
    "gpui::window::WindowContext::dispatch_event",
    "gpui::window::Window::new::{{closure}}",
    "gpui::platform::linux::x11::window::X11WindowStatePtr::handle_input",
    "gpui::platform::linux::x11::client::X11Client::handle_event",
    "gpui::platform::linux::x11::client::X11Client::process_x11_events",
    "<core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events",
    "<gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::run",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::run",
    "gpui::app::App::run",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace",
    "std::rt::lang_start::{{closure}}",
    "std::rt::lang_start_internal",
    "main",
    "__libc_start_main",
    "_start"
  ],
  "app_version": "0.155.2",
  "release_channel": "Zed",
  "os_name": "Linux X11",
  "os_version": "debian unknown",
  "architecture": "x86_64",
  "panicked_on": 1728307915655,
  "system_id": "7db9a251-93ba-454b-84b0-cac63e7be65f",
  "installation_id": "92130564-5cb0-41fb-9b93-b904f9e9295f",
  "session_id": "d8015916-36db-48c9-a0a7-2c6266487971"
}

</pre></details>

**Comment by alejandro-alzate** [comment]
It happened to me I thought that was a fluke, I'm my case I was trying to swap a tab to another firefox window, but slipped to zed and I thought "maybe I miss clicked onto the X"

Some bugs are obscure and wild.
