### ISSUE TITLE
Tooltip for inline assist model

### ISSUE THREAD

**Issue by wolffiex** [zed-industries/zed#18826]
### Check for existing issues

- [X] Completed

### Describe the feature

When using alternative inline assists, there's no easy way to know which model was responsible for which completion. A tooltip might be good here.

**Comment by danilo-leal** [comment]
Hey, thanks for the issue! Quick clarifying question: what do you mean by "alternative inline assists"? Would it be that you're performing each transformation with a different model? We display the currently used model in the tooltip that's displayed on hovering this icon button, but wanted to check whether what you have in mind is something else:

<img width="400" alt="Screenshot 2024-10-08 at 11 10 30 AM" src="https://github.com/user-attachments/assets/d9433867-8b2c-4131-9c5c-b3a543ef341e">

**Comment by wolffiex** [comment]
Oh sure, yes is this is the relatively obscure [Alternative Inline Assist](https://zed.dev/docs/assistant/configuration#alternative-assists) feature
![CleanShot 2024-10-08 at 08 33 42@2x](https://github.com/user-attachments/assets/61183780-13a0-488c-aca9-c60c0b236a2f)
