### ISSUE TITLE
cargo test --workspace failures

### ISSUE THREAD

**Issue by noctis711** [zed-industries/zed#18839]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Followed build guide for windows 10: https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md
During the test build phase, cargo test --workspace.  I can't get the latest build to work it just opens and closes, nothing happens.

failures:

---- slash_command::file_command::test::test_file_sub_directory_rendering stdout ----
thread 'slash_command::file_command::test::test_file_sub_directory_rendering' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported

---- slash_command::file_command::test::test_file_exact_matching stdout ----
thread 'slash_command::file_command::test::test_file_exact_matching' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported

---- context::context_tests::test_workflow_step_parsing stdout ----
thread 'context::context_tests::test_workflow_step_parsing' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported

---- slash_command::file_command::test::test_file_deep_sub_directory_rendering stdout ----
thread 'slash_command::file_command::test::test_file_deep_sub_directory_rendering' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- assistant_settings::tests::test_deserialize_assistant_settings_with_version stdout ----
thread 'assistant_settings::tests::test_deserialize_assistant_settings_with_version' panicked at crates\assistant\src\assistant_settings.rs:552:14:
called `Result::unwrap()` on an `Err` value: cannot overwrite the root

failures:
    assistant_settings::tests::test_deserialize_assistant_settings_with_version
    context::context_tests::test_workflow_step_parsing
    slash_command::file_command::test::test_file_deep_sub_directory_rendering
    slash_command::file_command::test::test_file_exact_matching
    slash_command::file_command::test::test_file_sub_directory_rendering

test result: FAILED. 32 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out;

### Environment

Zed: v0.157.0
OS: Win 10 version 10.0.19045
Memory: 64 GiB
Architecture: x64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jojje** [comment]
I am able to get zed to start, but am getting the exact same test failures as OP.

Using commit 4325819075 which is the latest on main as of writing this.

Since a assistant _settings.rs seems to have changed from when OP posted the ticket, here is the corresponding set of failures from my test on the mentioned commit.

```
failures:

---- context::context_tests::test_workflow_step_parsing stdout ----
thread 'context::context_tests::test_workflow_step_parsing' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported

---- slash_command::file_command::test::test_file_exact_matching stdout ----
thread 'slash_command::file_command::test::test_file_exact_matching' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported

---- slash_command::file_command::test::test_file_deep_sub_directory_rendering stdout ----
thread 'slash_command::file_command::test::test_file_deep_sub_directory_rendering' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- slash_command::file_command::test::test_file_sub_directory_rendering stdout ----
thread 'slash_command::file_command::test::test_file_sub_directory_rendering' panicked at crates\fs\src/fs.rs:870:45:
prefix paths aren't supported

---- assistant_settings::tests::test_deserialize_assistant_settings_with_version stdout ----
thread 'assistant_settings::tests::test_deserialize_assistant_settings_with_version' panicked at crates\assistant\src\assistant_settings.rs:570:14:
called `Result::unwrap()` on an `Err` value: cannot overwrite the root


failures:
    assistant_settings::tests::test_deserialize_assistant_settings_with_version
    context::context_tests::test_workflow_step_parsing
    slash_command::file_command::test::test_file_deep_sub_directory_rendering
    slash_command::file_command::test::test_file_exact_matching
    slash_command::file_command::test::test_file_sub_directory_rendering

test result: FAILED. 33 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 19.10s
```

**Comment by SomeoneToIgnore** [comment]
I do not think we need this issue.

* Windows support is tracked here: https://github.com/zed-industries/zed/issues/5394
* There's no way around fixing all the tests before Windows is supported
* The issue contains some odd list that's not even complete
* https://github.com/zed-industries/zed/pull/19773 fixes a few (if not all) of the items from the incomplete list above
* Instead of creating more issues like this and/or posting yet another comment in it, it's much more productive to fix at least a single test on Windows instead
