### ISSUE TITLE
JSON language schema definition ($schema) is ignored unless file extension is JSON

### ISSUE THREAD

**Issue by tinacious** [zed-industries/zed#18838]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First I'd like to say thanks for building such a beautiful editor. I appreciate the attention to detail and it's a really nice experience.

This is a bug report related to JSON schema definition support when using language=json but the file extension is not `*.json`.

Some configuration files are in JSON but do not use a `*.json` file extension, e.g. `.prettierrc` and other `*rc` files.

When changing the language to JSON, I get syntax highlighting, which is great, but the JSON `$schema` definition is not kicking in with auto-complete functionality as it does with `*.json` file extensions. 

Workaround: I can change the file extension to have `*.json`, and for new projects this is fine, but for existing ones, it's not ideal.

In my opinion, this functionality should work based on the language rather than the file extension, as it does in VSCode and WebStorm.

There's also some strange behaviour where this file appears to be treated as JavaScript. After Zed picked up my `.prettierrc` file, it started treating the configuration file as JavaScript. One of the configuration values I have is to use single quotes, so it replaced all double quotes with single quotes in the `.prettierrc` file, even though the language is set to JSON. File extension and language support feels out of sync. 

I cannot edit this file with Zed unless I change the file extension to `.json` as it treats it like JavaScript and format on save creates invalid JSON.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Expected behaviour working as expected for `*.json` files:

![CleanShot 2024-10-07 at 18 35 26](https://github.com/user-attachments/assets/8a5ccb85-bc8c-48b1-85f7-27ee0872cd47)

Current behaviour (before the editor picked up my .prettierrc file) – JSON schema definition language support is not enabled:

![CleanShot 2024-10-07 at 18 34 25](https://github.com/user-attachments/assets/adbbd51d-e439-4132-979b-4b749aa4a144)

VSCode supports JSON schema definition language support when language is set to JSON regardless of file extension:

![CleanShot 2024-10-07 at 18 39 29](https://github.com/user-attachments/assets/9c33b73e-a8c2-459f-a761-269bca3cfebb)

After Zed picked up my `.prettierrc` file, it started treating the configuration file as JavaScript. One of the configuration values I have is to use single quotes, so it replaced all double quotes with single quotes, even though the language is set to JSON. File extension and language support feels out of sync.

![image](https://github.com/user-attachments/assets/f1732bfe-d7d9-4a54-9aad-be7ca816f8f5)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I can reproduce. With the following named `prettierrc.json` I get schema validation, but when named `.prettierrc` with the manually selected JSON language or defined via `"file_types": {"JSON": [".prettierrc"]}` in settings there is no completion.

**Comment by notpeter** [comment]
I believe this has been fixed since this issue was opened.
Now setting this in my settings:
```
  "file_types": {
    "JSON": [".prettierrc"]
  }
```
I get completions as expected:
<img width="642" alt="Screenshot 2024-11-25 at 14 11 53" src="https://github.com/user-attachments/assets/d96f8f35-15af-4798-be26-8862e8be6ab7">

If you are still experiencing this, please comment below and I'm happy to reopen.
Thanks for reporting.
