### ISSUE TITLE
gopls support and error check

### ISSUE THREAD

**Issue by codecreatede** [zed-industries/zed#18847]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Thank you for the development of the Zed editor, which is really fast and a good one. I want to say that i am using it for Go, Python, Julia and Javascript and although the gopls is working and show the language server but it doesnt show error as where the variable are missing or anything else when you save the file and before running the check. 

If i do the same in Neovim then it shows that this static type is not possible and also what comabinations and error could be there while compiling the program. My Go configuration looks like this in the JSON. 

```
 "Go": {
            "code_actions_on_format": {
                "source.organizeImports": true
            }
        },
```
can you help me with this. Thank you,
Gaurav

### Environment

Linux gauravsablok 6.10.12-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 30 21:38:25 UTC 2024 x86_64 GNU/Linux

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
1. Can you paste your zed environment ("zed: copy system specs to clipboard" from the command palette)?
2. How did you install gopls? (can you try updating it -- we've seen issues which have been fixed in newer versions of `gopls`.
3. Do you have an example file / minimal project which reproduces this issue?

**Comment by codecreatede** [comment]
here are the system configuration attached.
![Snapshot_2024-10-08_15-00-17](https://github.com/user-attachments/assets/69e690d7-85c6-439d-b95d-0c9e977585c9)

gopls was install as go install. I enabled the system and the inlay hints and it seems to pick up the language. 

Additionally, do you have any suggestion as how to see the coloured brackets such as rainbow brackets as i cant see the bracket annotation in Zed. 

Thank you Gaurav

**Comment by notpeter** [comment]
1. Can you update gopls? `go install golang.org/x/tools/gopls@latest`
2. Can you confirm gopls is in your path by running `gopls version`?

For rainbow brackets see: 
- https://github.com/zed-industries/zed/issues/5259

**Comment by codecreatede** [comment]
Yes, i just checked it and it is in the path and now it is working. Thank you for the suggestion. Any plans to add the rainbow brackets to the Zed code editor?. If you can show me how to add that then it will be very good. 

Gaurav

**Comment by notpeter** [comment]
You can vote 👍 to that issue (as you can see a lot of people want this too).
I don't have a timeline but needless to say it's on our radar.

**Comment by codecreatede** [comment]
Thank you and sure i would like to see that feature and i can vote. Let me know if you are building something and i can add code to that. You can look at what i use for the same. 

Thank you,
Gaurav
