### ISSUE TITLE
Characters become invisible in long strings

### ISSUE THREAD

**Issue by wangxuepeng** [zed-industries/zed#18849]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If the editor window contains a line of text that exceeds a length of 746 characters, some of the characters may become invisible.

The more text is added, the more characters become invisible, see the screenshots below:

![image](https://github.com/user-attachments/assets/86782883-a6dd-4c3b-8a7f-bfe018a7076b)

![image](https://github.com/user-attachments/assets/74ad2188-091d-47fb-86ce-acda8e90f91b)

![image](https://github.com/user-attachments/assets/9332bf86-dcaf-43bf-b250-60b000eebdb1)

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 12.7.6
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
I cannot reproduce this on my M3 Max. Since you're using x86_64 Mac, maybe it is related to https://github.com/zed-industries/zed/issues/6853#issuecomment-2014539999 ?

**Comment by notpeter** [comment]
@wangxuepeng Are you perhaps running on a Hackintosh with a Nvidia 600/700M series or an iMac (21.5-inch, Late 2013) with a NVIDIA GeForce GT 750M 1 GB?  If so, sadly these cards do not properly support the graphics API (Apple Metal) we rely on.

**Comment by wangxuepeng** [comment]
> this on my M3 Max. Sinc

Sadly, it is. My graphics card is an NVIDIA GeForce GT 750M 1 GB :(
