### ISSUE TITLE
[Feature] Add a "prettying" action to the command pallete

### ISSUE THREAD

**Issue by alejandro-alzate** [zed-industries/zed#18844]
### Check for existing issues

- [X] Completed

### Describe the feature

I've noticed that sometimes zed touches up the file space and indention on save
It would be cool to have something similar like the web browsers that gets the minified javascript into a readable version of the same thing.

Making this language agnostic would be a nice perk as well.

### If applicable, add mockups / screenshots to help present your vision of the feature

You can take a look to sublime's JSON reindent plugin.

> Making this language agnostic would be a nice perk as well.

This plugin only works on json files.

**Comment by notpeter** [comment]
You're looking for `editor: format`.

It's the same action which is triggered on save when `format_on_save` is `"on"` for a given language. If you don't like the results you can always just undo. See also `workspace: save without format`

**Comment by alejandro-alzate** [comment]
Oh thanks for the heads up,

now if let's say i have a one-liner json/js/lua/etc can i tell zed to expand it?

And there's any reverse operation? like minifying back to a one-liner?

**Comment by notpeter** [comment]
Currently formatting is tied to the language of a buffer.  The support is language specific, a bunch use prettier, but you can also use the language-server or specify an external command to use formatting. See [Configuring Languages: Formatting and Linting](https://zed.dev/docs/configuring-languages#formatting-and-linting) in the docs for more.

To expand a oneline, paste it into an empty buffer and then set the language (clicking in the status bar and picking your language, or use the `language_selector::Toggle` action from the command palette) and trigger `editor:format`.

There's no built it support minifying/compacting an existing buffer, but you could probably create a task which would do it.  Not sure the best way to rewrite the existing buffer but you could certainly create a task which was something like "jq -c . ${ZED_FILENAME} | pbcopy" which would take a json file and put a compacted version of it on your clipboard.
