### ISSUE TITLE
Small inconsistancy with `ctrl-6` 

### ISSUE THREAD

**Issue by anoopkcn** [zed-industries/zed#18871]
### Check for existing issues

- [X] Completed

### Describe the feature

The zed:default key-binding `"ctrl-6": ["pane::ActivateItem", 5]` and vim:default key-binding `"ctrl-6":"pane::AlternateFile"` produce an inconsistency when Vim_mode is turned on.

**Comment by notpeter** [comment]
If you would prefer not to use the vim default binding for `ctrl-6` (switch to last buffer) you should be able to override it by adding the following to your keymap:
```json
[
  {
    "context": "VimControl && !menu",
    "bindings": {
      "ctrl-6": ["pane::ActivateItem", 5]
    }
  }
]

**Comment by anoopkcn** [comment]
Thanks, but I turned the tab bar off. tab-switcher is much better and also feels closer to Vim workflow. The only problem now is when a file is modified, there is no indicator :)
