### ISSUE TITLE
Error Interacting with language model not connected 

### ISSUE THREAD

**Issue by noahc** [zed-industries/zed#18916]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the last couple days I've been getting Error interacting with language model not connected. 
![image](https://github.com/user-attachments/assets/6e0da96e-a21a-4073-9f78-c31917e946d3)

I've found users with a similar issue, but their error message was slightly different. I've confirmed that I am showing up as being located in the US.

```shell
❯ curl -s -4 --location --request GET 'https://www.cloudflare.com/cdn-cgi/trace' |grep loc                              
loc=US

❯ curl -s -6 --location --request GET 'https://www.cloudflare.com/cdn-cgi/trace' |grep loc                              
loc=US
```
This is what I see at the top and I am using the Zed version of 3.5 Sonnet. 

![image](https://github.com/user-attachments/assets/d3aa0d4c-8a70-4390-ad3f-4b6685a764c8)

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by dustydecapod** [comment]
What was the resolution here? I've been having this issue for a month.

**Comment by IcelandicIcecream** [comment]
Have the same issue as well.

**Comment by magicwave** [comment]
I've encountered this after rewriting context history. I seem to recall that it seemed to have to do with not having white space after the last LLM reply, however today that was not the case. I was able to continue from where I left off after clicking to upgrade and restart Zed and then simply entering again, where the "Assistant Error" and "You" tags were still at the end of the context. Updated to Zed 0.156.2

**Comment by creslinux** [comment]
I've had this for 3 days - what was the solution?

**Comment by titlestad** [comment]
I get this. Isn't this the whole point with this app? Why is this failing?

**Comment by noahc** [comment]
I think adding this to settings.json fixed it...

```
"assistant": {
    "default_model": {
      "provider": "zed.dev",
      "model": "claude-3-5-sonnet-20240620"
    },
    "version": "2",
    "enable_experimental_live_diffs": true
}
```

**Comment by Carlmarion** [comment]
Updating zed on the left bottom corner solved the issue for me

**Comment by xeverse** [comment]
client:reconnect
