### ISSUE TITLE
typescript: vue module resolution from within ts files 

### ISSUE THREAD

**Issue by oleasteo** [zed-industries/zed#18914]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

From within `.vue` files, other `.vue` files can be imported without any ts error shown. The same is not true from within `.ts` files.

```
ts: Cannot find module './App.vue' or its corresponding type declarations.
```

![image](https://github.com/user-attachments/assets/688b3238-a437-47a0-8d6d-cea79b53b07d)

## Reproduction

1. `bun create vue` — enable typescript; the rest should be irrelevant
    1. run `cd` and `bun install` as described
2. open src/main.ts

### Environment

Zed: v0.155.2 (Zed)
OS: Linux Wayland endeavouros unknown
Memory: 15.4 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.4-arch1.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I was able to reproduce this on MacOS:

```
cd ~/source/
brew install oven-sh/bun/bun
bun create vue
# <enter>, yes for typescript, then <enter> <enter> <enter> for the rrest
cd vue-project
zed . src/App.vue
```
<img width="820" alt="Screenshot 2024-10-13 at 15 49 29" src="https://github.com/user-attachments/assets/43f5c802-af30-4a45-8aaf-3f4e32f1b814">

I'm not sure whether this is bun issue or something else. See also:
- https://github.com/zed-industries/extensions/issues/173

**Comment by armankudabaev** [comment]
i have the same issue with Node in `.ts` files

**Comment by hungify** [comment]
This seems to be related to the current issue: [#8336](https://github.com/zed-industries/zed/issues/8336#issuecomment-2306473736)

You can also test it on this [repo](https://github.com/fazulk/vue-zed-demo).

**Comment by oleasteo** [comment]
Duplicate of #8336
