### ISSUE TITLE
Can't type '@' character on Latin America keyboard

### ISSUE THREAD

**Issue by FabianVegaA** [zed-industries/zed#18929]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I create a new file or edit a file, I can't type '@' (use option + q to type it), but I can type it in any other program.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by gabwill10** [comment]
It is duplicated of https://github.com/zed-industries/zed/issues/18607 you can find the solution there.

**Comment by FabianVegaA** [comment]
It works, thank you!
