### ISSUE TITLE
rust: add Open Documentation support

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#18924]
### Check for existing issues

- [X] Completed

### Describe the feature

in other editors i can select "Open Documentation" and it will open the docs.rs site for that item in the browser.

**Comment by notpeter** [comment]
I believe this is `rust-analyzer.openDocs`

**Comment by andrewbanchich** [comment]
Not sure if this is possible, but could this eventually build and open local documentation sites for private crates which are not available on docs.rs?

**Comment by wanlufun** [comment]
> Not sure if this is possible, but could this eventually build and open local documentation sites for private crates which are not available on docs.rs?

```
        workspace.update(&mut cx, |_workspace, cx| {
            // Check if the local document exists, otherwise fallback to the online document.
            // Open with the default browser.
            if let Some(local_url) = docs_urls.local {
                if fs::metadata(Path::new(&local_url[8..])).is_ok() {
                    cx.open_url(&local_url);
                    return;
                }
            }

            if let Some(web_url) = docs_urls.web {
                cx.open_url(&web_url);
            }
        })
```

After using `cargo doc` to generate local documentation, you can use `open docs` to open the local documentation (for example, private crates).

**Comment by andrewbanchich** [comment]
Awesome, thank you!

**Comment by wanlufun** [comment]
You’re welcome! I'm glad you liked it!
