### ISSUE TITLE
add NextPanel and PreviousPanel keybindings

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#18951]
### Check for existing issues

- [X] Completed

### Describe the feature

In Emacs, `ctrl-x right` selects the next buffer and `ctrl-x left` selects the previous one, ordered by most recent selection. This makes it very easy to jump between them without needing to think about what number they are assigned to / tab layout. It would be awesome if Zed could add keybindings for these.

**Comment by aexvir** [comment]
@andrewbanchich there's already `workspace::ActivateNextPane` and `workspace::ActivatePreviousPane`, as far as I understand this issue those should already achieve what you need

**Comment by andrewbanchich** [comment]
hmm, i added this but it doesn't seem to have any effect:

```
  {
    "context": "Workspace",
    "bindings": {
      "ctrl-x right": "workspace::ActivateNextPane",
      "ctrl-x left": "workspace::ActivatePreviousPane",
```

**Comment by aexvir** [comment]
I've just tried and works correctly for me 🤔 
I press ctrl-x, I lift both, then I tap left or right and it navigates between panes
![keybind](https://github.com/user-attachments/assets/51d6b0de-9806-4bd7-9298-d2e59ed57dcc)
note, panes are the splits, if what you want is to navigate between tabs of a split then you need
```json
"ctrl-x right": "pane::ActivateNextItem",
"ctrl-x left": "pane::ActivatePrevItem"
```
instead

**Comment by andrewbanchich** [comment]
ah, that's it! thank you so much :smile:
