### ISSUE TITLE
Cant make $ sign in terminal

### ISSUE THREAD

**Issue by AugustAxelsson** [zed-industries/zed#19003]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

You cant write the $ sign in the terminal, the terminal freezes for a second and doubles the next input. 

### Environment

Zed: v0.156.0 (Zed)
OS: macOS 15.1.0
Memory: 18 GiB
Architecture: aarch64

**Comment by htor** [comment]
What keyboard layout do you use? Are you using the Meta (Alt) key for inserting the $ sign? If so, check out the `terminal.option_as_meta` option.

**Comment by AugustAxelsson** [comment]
> What keyboard layout do you use? Are you using the Meta (Alt) key for inserting the $ sign? If so, check out the `terminal.option_as_meta` option.

Im using Swedish layout, so option 4 for $.
is `terminal.option_as_meta` suppose to be a field in settings?

**Comment by htor** [comment]
Yes! Try setting `terminal.option_as_meta = false` in your `settings.json`.

**Comment by AugustAxelsson** [comment]
> Yes! Try setting `terminal.option_as_meta = false` in your `settings.json`.
Thanks! it works!
