### ISSUE TITLE
typescript: selected intellisense item gets inserted after a delay

### ISSUE THREAD

**Issue by soulsam480** [zed-industries/zed#19005]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Note: this started happening from yesterday's release i.e. 0.156. I'll explain it below
- I have a large typescript codebase
- I write a function
- inside the function body i type `ret` and hit control + space
- once I hit return on intellisense item, it gets inserted after a delay
- I also tried on multiple kind of items e.g. TS types, imports, export declarations etc. 

### Environment

Zed: v0.156.0 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

here's a gif of it happening
![ezgif-7-ea59492327](https://github.com/user-attachments/assets/6774433b-2537-424d-be5b-c4a48709589c)

if you can see above, it took approx. 2 seconds for it to insert. everything was fine untill last release.

**Comment by SomeoneToIgnore** [comment]
Thank you for the report, new patch versions for Preview and Stable should be out with the fix.

**Comment by mocenigo** [comment]
In my case it is the completions popup from the ltex LSP that appears with a delay. Or does not appear at all.

**Comment by SomeoneToIgnore** [comment]
There's no such issue or test existing.

I also have no clue how are you supposed to create such test that is able to 

* reliably expose he completion perf issues (without false-positives and other noise, otherwise it will be ignored quite soon)
* is not a chore to maintain

**Comment by krshrimali** [comment]
> There's no such issue or test existing.
> 
> I also have no clue how are you supposed to create such test that is able to
> 
> * reliably expose the completion perf issues (without false-positives and other noise, otherwise it will be ignored quite soon)
> * is not a chore to maintain

Thanks for the response. I'll try to explore a bit further to see if it's possible in Rust and for editors/lsp features. In case I find something reliable and maintainable, will create an issue with more details.
