### ISSUE TITLE
Linux weird appearance

### ISSUE THREAD

**Issue by anHiep** [zed-industries/zed#19008]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I installed it, the cursor is extra large. And It don't follow my ubuntu 22.04 gtk theme. Moreover, I want to zoom in the application.
![Screenshot from 2024-10-10 15-22-36](https://github.com/user-attachments/assets/161887ba-933f-47b7-bd84-db2bfb5d259a)

### Environment

Ubuntu 22.04 - Kernel:
6.8.0-45-generic
gtk3-theme
gnome 43

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by andrewbanchich** [comment]
I ran into this as well. Going to GNOME settings and enabling fractional scaling (even if kept at 100%) fixed this for me.

**Comment by feschber** [comment]
https://blogs.kde.org/2024/10/09/cursor-size-problems-in-wayland-explained/

**Comment by 0xtimsb** [comment]
Duplicate: https://github.com/zed-industries/zed/issues/17771
PR: https://github.com/zed-industries/zed/pull/18642

This is fixed in preview release.

**Comment by JosephTLyons** [comment]
Closing this out, as it is supposedly fixed on preview. Feel free to open a new issue if it is not fixed for you.
