### ISSUE TITLE
Document variable interpolation in settings.json

### ISSUE THREAD

**Issue by alexkirsz** [zed-industries/zed#19016]
### Check for existing issues

- [X] Completed

### Describe the feature

In order to better support migrating from VS Code's settings.json, the Zed documentation should explain all variables that are valid in its own settings.json.

For instance, there's `{buffer_path}`, but it's currently only documented as part of examples.

Is there also such a thing as VS Code's `${workspaceFolder}`?

**Comment by notpeter** [comment]
Currently `{buffer_path}` is the only variable supported in settings and it is only supported when included in the Formatter Arguments array. I've added docs here:
- https://github.com/zed-industries/zed/pull/19156

There is not `${workspaceFolder}` equivalent in Zed.
Thanks for reporting.
