### ISSUE TITLE
Open Remote not working in local container

### ISSUE THREAD

**Issue by simlal** [zed-industries/zed#19039]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Built a basic python image and ran a docker container on local using DevPod
2. Validated ssh and proper container function
3. Tried to open Remote server with ssh containername.devpod
4. Error trying to build the zed headless bin into the container

![image](https://github.com/user-attachments/assets/f1251571-b3e9-4b5f-b6d1-ef28c080145c)

container runtime info:
```bash
vscode-remote-try-python on  main via  v3.11.2 on   (ca-central-1)
❯ ssh vscode-remote-try-python.devpod
vscode ➜ /workspaces/vscode-remote-try-python (main) $ cd .local/
vscode ➜ /workspaces/vscode-remote-try-python/.local (main) $ ls -a
.  ..
vscode ➜ /workspaces/vscode-remote-try-python/.local (main) $ which gzip
/usr/bin/gzip

# Checking zed bin and glibc version
vscode ➜ ~/.local/bin $ ls
flask
vscode ➜ ~/.local/bin $ ldd --version
ldd (Debian GLIBC 2.36-9+deb12u8) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I can change the file from Zed:
![image](https://github.com/user-attachments/assets/cda83709-53c7-4143-821c-f421c590687e)

And changes are reflected inside the container
```bash
vscode ➜ /workspaces/vscode-remote-try-python (main) $ python -m flask run --port 9000
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:9000
Press CTRL+C to quit
127.0.0.1 - - [10/Oct/2024 19:23:03] "GET / HTTP/1.1" 200 -
```

```bash
vscode ➜ /workspaces/vscode-remote-try-python (main) $ curl -X GET http://127.0.0.1:9000
<html>
    <head>
        <title>ZED</title>
    </head>
    <body>
        <h1>Changed?</h1>
        <p>Y</p>
    </body>
```

But I know that I am using the local env since 
![image](https://github.com/user-attachments/assets/7379db0b-d8ed-4041-bb0a-256a61c5f50a)

### Environment

Using debian 12, KDE 5 on local. Zed preview 0.157.2

Container runtime:
vscode ➜ ~/.local/bin $ ldd --version
ldd (Debian GLIBC 2.36-9+deb12u8) 2.36

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

 2024-10-09T09:06:45.329348951-04:00 [WARN] request completed with error: failed to connec
       │ t to the server
</pre></details>

**Comment by JosephTLyons** [comment]
I'm linking this other issue, since it *may* be the same thing or similar, at least:

https://github.com/zed-industries/zed/issues/19131
