### ISSUE TITLE
Zed not available in Nautilus's File Chooser (flatpak)

### ISSUE THREAD

**Issue by yioannides** [zed-industries/zed#19030]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to launch a Python file via Zed after a fresh install (flatpak), but Zed is not available in Nautilus's File Chooser panel, as seen below:

![Screenshot from 2024-10-10 18-12-12](https://github.com/user-attachments/assets/fe6f8b0c-c8c8-4fc7-a193-fe6b68c61687)
![Screenshot from 2024-10-10 18-12-23](https://github.com/user-attachments/assets/abd5d0ad-13bb-4fe3-9428-ec85f4054ef8)

### Environment

Zed: v0.156.0 (Zed)
OS: Linux Wayland fedora 40
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (TGL GT1) || Intel open-source Mesa driver || Mesa 24.1.7

(I also have a NVIDIA RTX 3050 Ti)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17330420/Zed.log)

</pre></details>

**Comment by yioannides** [comment]
I would also like to mention that even manually inputting `text/x-python=dev.zed.Zed.desktop` in `~/.config/mimetypes.list` doesn't launch Zed, so I don't think it's necessarily a Nautilus bug.

**Comment by yioannides** [comment]
It does, however, seem to appear on what seems to be an empty document (it's not .txt):

![image](https://github.com/user-attachments/assets/80b02ca5-494a-4b31-8169-44698fa1b409)

**Comment by 0xtimsb** [comment]
Thank you! It will be fixed soon.

In the meantime, you can edit `/var/lib/flatpak/exports/share/applications/dev.zed.Zed.desktop` as follows:

```diff
- Exec=/usr/bin/flatpak run --branch=master --arch=x86_64 --command=zed dev.zed.Zed --foreground
+ Exec=/usr/bin/flatpak run --branch=master --arch=x86_64 --command=zed --file-forwarding dev.zed.Zed --foreground @@u %U @@
```

Afterward, update the icon cache by running: `sudo gtk-update-icon-cache /usr/share/icons/hicolor`

**Comment by yioannides** [comment]
Thank you for the workaround, but it didn't work for me...

**Comment by 7system7** [comment]
This is still an issue. I have the v0.187.5 and the Zed completely missing from the file chooser.

**Comment by 7system7** [comment]
@smitbarmase I use arch, btw. The window manager is GNOME. The specs, you requested:

```
Zed: v0.187.5 (Zed) 
OS: Linux Wayland arch unknown
Memory: 62.1 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6600 (RADV NAVI23) || radv || Mesa 25.1.1-arch1.1
```
