### ISSUE TITLE
Wrong active file after closing a file

### ISSUE THREAD

**Issue by JulesSorensen** [zed-industries/zed#19036]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

# Description

When a file is closed, the active file becomes the file that follows in the nav menu (the one to the right of the file that has just been closed in the navigation menu) instead of the active file being the last file opened (even if it was displayed before the closed file in the navigation menu)

# Reproduce

- Open three files, 1, 2 and 3 respectively, in the order in which they appear in the tab menu
- Visit files 1 and 2
- Close file 2
- The bug appears; the active file is now file 3

The active file after closing file 2 should be 1, as it is the last to have been visited recently

Thanks 🙏 

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

**Comment by icarusgk** [comment]
Yeah, I was going to mention this too, it becomes more apparent when navigating to definitions. After closing the definitions tab, it doesn’t take you back to the file you were working on, but to the one next to it, which usually can be unrelated to the current workflow. 

Thank you for opening this issue!
