### ISSUE TITLE
Display c++ icon for "*.c++" files (modified)

### ISSUE THREAD

**Issue by bnjmnjrk** [zed-industries/zed#19038]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently ZED only recognizes the ".cc" and ".cpp" file extensions for C++, please add support for the ".c++" extension.

**Comment by jruz** [comment]
In the meantime you could try this on your `settings.json`
```json
{
"file_types": {
    "C++": [
      "cc",
      "cpp",
      "c++"
    ],
}
```

**Comment by bnjmnjrk** [comment]
At second glance, I see that the C++ language is selected for “*.c++” files, but the C++ icon for the file is not displayed in the UI.
