### ISSUE TITLE
Cargo check configuration

### ISSUE THREAD

**Issue by jruz** [zed-industries/zed#19042]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

I would like to be able to run `clippy::pedantic`.
I tried this config without any luck.
Is there a way to override the check command?

```json
"languages": {
    "Rust": {
      "check_on_save": "on",
      "check": {
        "external": {
          "command": [
            "cargo",
            "clippy",
            "--",
            "-W",
            "clippy::pedantic"
          ]
        }
      }
    },
  },
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "check": {
          "command": [
            "clippy",
            "--",
            "-W",
            "clippy::pedantic"
          ]
        }
      }
    }
  },
```

**Comment by bitfield** [comment]
Are you looking for `extraArgs`? This is the config I'm using:

```json
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "checkOnSave": {
          "enable": true,
          "command": "clippy",
          "extraArgs": ["--", "-W", "clippy::pedantic"]
        },
      ...
```

**Comment by jruz** [comment]
Thanks! @bitfield that worked

**Comment by bitfield** [comment]
Should we perhaps document this somewhere? At least two people have had trouble figuring it out.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/04bade7cedb6cc32a3c72a8951e519f08a41d345/docs/src/languages/rust.md?plain=1#L1

**Comment by bitfield** [comment]
Is `extraArgs` shown on that page? If so, I'm just not seeing it for some reason.

**Comment by berkus** [comment]
> Is `extraArgs` shown on that page? If so, I'm just not seeing it for some reason.

It is not.

**Comment by bitfield** [comment]
@JosephTLyons please reopen?
