### ISSUE TITLE
Zed fails to start (ERROR_SURFACE_LOST_KHR)

### ISSUE THREAD

**Issue by conformally** [zed-industries/zed#19053]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
zed --foreground
``` 
returns
```
wp_linux_drm_syncobj_manager_v1#45: error 0: surface already exists
[2024-10-11T12:45:50+08:00 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Result::unwrap()` on an `Err` value: ERROR_SURFACE_LOST_KHR",
  "location_data": {
    "file": "/builddir/build/BUILD/zed-0.156.1/.cargo/git/checkouts/blade-b2bcd1de1cf7ab6a/e142a3a/blade-graphics/src/vulkan/init.rs",
    "line": 930
  },
  "backtrace": [
    "__libc_start_call_main",
    "__libc_start_main@@GLIBC_2.34"
  ],
  "app_version": "0.156.1",
  "release_channel": "Zed",
  "os_name": "Linux Wayland",
  "os_version": "fedora 40",
  "architecture": "x86_64",
  "panicked_on": 1728621950771,
  "system_id": "ef7c7427-08e3-4bbe-bb04-b8883151e28c",
  "installation_id": "648b27d0-0595-4331-a841-e7c6bebc7f15",
  "session_id": "bd6af6f8-8daf-4b42-9de0-b820b0266369"
}
``` 

### Environment

OS: Fedora Linux 40 x86_64
Kernel: Linux 6.10.12-200.fc40.x86_64
DE: KDE Plasma 6.2.0
CPU: 11th Gen Intel(R) Core(TM) i7-11800H (16) @ 4.60 GHz
GPU 1: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
GPU 2: Intel UHD Graphics @ 1.45 GHz [Integrated]

Nvidia driver version: 560.35.03

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
This issue is bad, it did not added any crash information and it checked the "Check for existing issues" without even an attempt to search for the error:

https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+ERROR_SURFACE_LOST_KHR

**Comment by conformally** [comment]
Sorry for this embarrassing mistake :/ 
I did search for the issue but very possibly with a wrong keyword so I didn't get any results. Will be extra cautious next time.
