### ISSUE TITLE
`worktree.read_text_file` does not work correctly

### ISSUE THREAD

**Issue by luckydye** [zed-industries/zed#19050]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The [`tead_text_file`](https://github.com/zed-industries/zed/blob/main/crates/project/src/lsp_store.rs#L7665) function of worktrees seems to not work corretly. 

As I understand it, the function should read files relative to the worktree root, wich it does not do currently.

Effects https://github.com/biomejs/biome-zed/issues/50

Possibly introduced by https://github.com/zed-industries/zed/pull/17655

### Environment

Zed: v0.157.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Possible fix? 
https://github.com/zed-industries/zed/commit/59cdf5a2cc3dd25ffeb9232d6b1f998cd0aadc77#diff-5b9d51b75b74266b5c651ef3c6988fe2e62d1680ac138d806cdaa75900bc8b5fR7666

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
The old code does look odd indeed, and the fix looks legit.
I'd restyle it as 
```diff
diff --git a/crates/project/src/lsp_store.rs b/crates/project/src/lsp_store.rs
index 7a7bd2863b..2732d12b37 100644
--- a/crates/project/src/lsp_store.rs
+++ b/crates/project/src/lsp_store.rs
@@ -7663,9 +7663,14 @@ impl LspAdapterDelegate for LocalLspAdapterDelegate {
     }

     async fn read_text_file(&self, path: PathBuf) -> Result<String> {
-        if self.worktree.entry_for_path(&path).is_none() {
-            return Err(anyhow!("no such path {path:?}"));
-        };
+        let entry = self
+            .worktree
+            .entry_for_path(&path)
+            .with_context(|| format!("no worktree entry for path {path:?}"))?;
+        let abs_path = self
+            .worktree
+            .absolutize(&entry.path)
+            .with_context(|| format!("cannot absolutize path {path:?}"))?;
         self.fs.load(&path).await
     }
 }
```

but the idea is the same. 
Does the fix work for you?

**Comment by luckydye** [comment]
If you also do

```diff
- self.fs.load(&path).await
+ self.fs.load(&abs_path).await
```

then, it works 👍.

**Comment by SomeoneToIgnore** [comment]
Oh, of course.
Great, would you want to open a PR or should I do that?

**Comment by luckydye** [comment]
I'll make one, thx for the feedback!

**Comment by nileshmali** [comment]
I can see this again after installing 0.157.5 latest release?
