### ISSUE TITLE
Please use deno as the base of JS & TS language server instead of node

### ISSUE THREAD

**Issue by Demolemon11** [zed-industries/zed#19065]
### Check for existing issues

- [X] Completed

**Comment by SomeoneToIgnore** [comment]
> Node.js is too slow & bloated!!!!

{{[Citation needed](https://en.wikipedia.org/wiki/Template:Citation_needed)}}

There's a way to use Deno currently: https://zed.dev/docs/languages/deno and nothing should stop anyone from configuring Zed once (you can do that even without launching it, by editing your global settings.json) to use Deno for all.

So far, the majority of the projects, hence users seem to use Node, so we'll stick for this as a default.
