### ISSUE TITLE
Markdown preview: Copy button for source code blocks

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#19061]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be useful if the source code was displayed in this way, with a button that appears as if you could copy the code on github.

Github:
<img width="1214" alt="Screenshot 2024-10-11 alle 11 13 56" src="https://github.com/user-attachments/assets/56f03823-da2f-4486-9896-2a876d5d7394">

Zed:
<img width="1422" alt="Screenshot 2024-10-11 alle 11 14 22" src="https://github.com/user-attachments/assets/2614a353-7a2e-4f98-b102-4d1968c28cf3">

**Comment by Irilith** [comment]
> The tooltip part is missing, it would be nice if it did like github does.

I gave it a try, but it turned out to be more challenging than I expected with my current knowledge. I’ll keep looking into how to do it when I have time, but if someone else figures it out first, I’d be glad to see it!
