### ISSUE TITLE
ruby: Permission to extract the extension to an external repo

### ISSUE THREAD

**Issue by vitallium** [zed-industries/zed#19075]
### Check for existing issues

- [X] Completed

### Describe the feature

Hey, this is a small issue about requesting a permission to extract the Ruby extension to an external repo under my personal name. Asking because I noticed the same thing for the Gleam lang (https://github.com/zed-industries/zed/pull/19072). I had this idea for some time but just didn't have time to ask. I think it's about the time now. 

<hr />

My name is Vitaly Slobodin, and I am writing to request permission to extract and host a version of the Ruby extension currently available on GitHub under [your repository](https://github.com/zed-industries/zed/tree/main/extensions/ruby). I would like to move the Ruby extension code to an external repository under [my personal GitHub account](https://github.com/vitallium).

I intend to retain the same license ([Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0)) as the original repository to ensure that your terms and conditions are fully respected. The primary purpose of creating this new repository is to consolidate all Ruby-related issues and continue further development of the extension. I believe this setup will streamline the development process and provide a more focused avenue for enhancements and issue tracking. I am fully committed to include all necessary attributions and references back to the original repository as required by the license.

Please let me know if you need any further information or have any special requirements for this request.

Thanks.

**Comment by maxdeviant** [comment]
> I would like to move the Ruby extension code to an external repository under [my personal GitHub account](https://github.com/vitallium).

I don't know about moving it to a personal repo, but we would happily move it to a repository under @zed-extensions and give you maintainer rights on the repository.

Would you be open to that arrangement?

**Comment by notpeter** [comment]
Hi Vitallium,

Would it be sufficient to extract the ruby extension to a new repo under the [zed-extensions](https://github.com/zed-extensions/) org and make you a maintainer there?

I took a stab at the history import here: https://github.com/zed-extensions/ruby

**Comment by vitallium** [comment]
@maxdeviant @notpeter My idea is to clean up the issue tracker a bit by moving all Ruby-related issues there and maintaining Ruby development in that repo. I also recall there was an issue about confusion regarding which extension is affiliated with Zed and which is not. 

Your suggestion to move it to https://github.com/zed-extensions/ruby is even better. I hadn’t thought of that. I am totally in favor of it. Thanks again!
