### ISSUE TITLE
Again sign in after closing zed ( Linux )

### ISSUE THREAD

**Issue by veaquer** [zed-industries/zed#19116]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Idk why it happening, but if i sign in, then close zed & open again i should sign in again.Maybe some problems with saving idk.I even tried after reboot(i knew it shouldn't help).

### Environment

Zed: v0.156.1 (Zed)
OS: Linux Wayland arch unknown
Memory: 7.5 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.4-arch1.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
See: [Linux: Zed isn't remembering my login](https://zed.dev/docs/linux#zed-isnt-remembering-my-login) in the docs.

<img width="804" alt="Screenshot 2024-10-12 at 2 54 48" src="https://github.com/user-attachments/assets/2bbdd1dc-83b8-4b4e-82e6-f644aab0fdae">

**Comment by veaquer** [comment]
> See: [Linux: Zed isn't remembering my login](https://zed.dev/docs/linux#zed-isnt-remembering-my-login) in the docs.
> <img alt="Screenshot 2024-10-12 at 2 54 48" width="804" src="https://private-user-images.githubusercontent.com/145113/375933470-2bbdd1dc-83b8-4b4e-82e6-f644aab0fdae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTY0MTQsIm5iZiI6MTcyODcxNjExNCwicGF0aCI6Ii8xNDUxMTMvMzc1OTMzNDcwLTJiYmRkMWRjLTgzYjgtNGI0ZS04MmU2LWY2NDRhYWIwZmRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNjU1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTc1NmMzNGUxZjRjMjU5OTY0Njc4YmRhOGU3MDUyMWUxNzRlMDgxYjQ4NDIyYzE1YTEwZWY4ZTA2NGI1NjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ym_gV5pj8KAM-T3xS_v4xjf-tg_0oc8Zo7pxEv-iEDc">

Oh, sorry

**Comment by cvanelteren** [comment]
Thanks!
