### ISSUE TITLE
'Select line' moving cursor to next line

### ISSUE THREAD

**Issue by ftr002** [zed-industries/zed#19111]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When selecting a line using the keybindings 'ctrl + L' it moves the cursor to the next line, rather than to the end of the selected line.

If deselecting line with 'esc' after that, cursor stays on the other line.

![image](https://github.com/user-attachments/assets/ad3d6d7b-58c4-4abf-9125-d43806a0f52c)

![image](https://github.com/user-attachments/assets/a1445d3a-b0a8-44c0-8356-217f3f974d61)

### Environment

Zed: v0.156.1 (Zed)
OS: Linux Wayland ubuntu 24.04
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Correct function should be cursor moves to end of the line when whole line is selected, or stays where it is.

Probably stays where it is so that if deselected using 'esc' it remains in the same position. Not 100% sure though on what is best. Just not what it is currently.

**Comment by JosephTLyons** [comment]
Hey @ftr002, our behavior here seems to be consistent with VS Code, where hitting `esc` keeps the cursor on the line below. Are you using another editor where it does something different?

https://github.com/user-attachments/assets/200a28bc-d8c2-42b2-89f6-a314202e30cf

**Comment by ftr002** [comment]
Thanks for the response and video. It seems I'm just going crazy I think maybe tbh lol. That is exactly what it does. I was using VS Code before ZED, however, I've tried some things in between there and have been changing a lot of things around before settling here. Weird that felt foreign all of a sudden.

I guess I just got confused in all that. I apologise for wasting your time and thanks again for getting back to me.

**Comment by andrewbanchich** [comment]
@JosephTLyons I noticed this as well - the issues description has two things:

1. "select line" moves the cursor to the next line instead of the end of the current one
2. cancelling keeps the cursor on the next line

I understand 2, but I wouldn't have expected 1. I'd have thought selecting the current line should stop before the newline character, not include it.

**Comment by JosephTLyons** [comment]
> Thanks for the response and video. It seems I'm just going crazy I think maybe tbh lol. That is exactly what it does. I was using VS Code before ZED, however, I've tried some things in between there and have been changing a lot of things around before settling here. Weird that felt foreign all of a sudden.
> 
> I guess I just got confused in all that. I apologise for wasting your time and thanks again for getting back to me.

To be fair, I'm not saying that maybe we shouldn't do something different, I'm just assuming whoever wrote this command followed suit on what was already out there.

**Comment by andrewbanchich** [comment]
Yep, I agree! I'm just saying, without more context into why they included the newline, I would think we wouldn't want to include it. Maybe we could look into that / possibly change it?
