### ISSUE TITLE
No data verification on deployment of remote server

### ISSUE THREAD

**Issue by samhjn** [zed-industries/zed#19112]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I used remote development function. Because of the poor network connection to github in my country, the download process of the development server timed out, leaving a half completed remote server tar package in the app directory.
When I tried to connect to that server again, zed repeatedly copy the corrupt tar package to the remote server and try to extracting it, without any data verification or checksum. It seems to be a very dangerous behavior.

### Environment

Zed: v0.156.0 (Zed)
OS: macOS 14.4.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-10T17:23:23.86121+08:00 [INFO] uploading remote development server (994kb)
2024-10-10T17:23:24.587463+08:00 [INFO] uploaded remote development server in 726.257875ms
2024-10-10T17:23:24.72378+08:00 [ERROR] failed to run command:
gzip: .local/zed-remote-server-stable.gz: unexpected end of file
</pre></details>

**Comment by mrnugget** [comment]
This should be fixed by https://github.com/zed-industries/zed/pull/19700
