### ISSUE TITLE
Mismatch | alt-shift-down in Zed DOCS key-bindings set as ctrl-alt-shift-down in Default key Bindings

### ISSUE THREAD

**Issue by ftr002** [zed-industries/zed#19110]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/edb0468f-2b70-49d5-a8e1-5b62e8a4f65f)

![image](https://github.com/user-attachments/assets/116a8609-13eb-43f1-9c41-6e3a2bdd12d6)

### Environment

not sure what this is sorry. Seems pretty straightforward anyway.

**Comment by notpeter** [comment]
This is difference between the default Mac and Linux keybinding:
https://github.com/zed-industries/zed/blob/f805fcd0ff5e9692d6f232dffa87d5fba8c4fc4f/assets/keymaps/default-macos.json#L323-L324
https://github.com/zed-industries/zed/blob/f805fcd0ff5e9692d6f232dffa87d5fba8c4fc4f/assets/keymaps/default-linux.json#L284-L286

That page of documentation is not auto-generated and has not been updated to reflect Linux keybindings, nor note where they diverge. There has been some work in this area:

- https://github.com/zed-industries/zed/pull/16554

We are aware that those pages could use some love.
Thanks for reporting.
