### ISSUE TITLE
Inline assist suggested changes difficult to read due to background color

### ISSUE THREAD

**Issue by esbeto** [zed-industries/zed#19128]
### Check for existing issues

- [X] Completed

### Describe the feature

The background color used for the inline assist suggestions is difficult to read in any theme. I tried to look for a way to configure it but couldn't find it.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/user-attachments/assets/b0424be2-4724-4f68-8f0b-13299219dfc2

**Comment by thataboy** [comment]
try  changing `info.background` and `modified.background`

**Comment by esbeto** [comment]
@thataboy Hmm... where exactly? I'm looking at: https://zed.dev/docs/configuring-zed#folder-specific-settings, and can't find where.

**Comment by thataboy** [comment]
> @thataboy Hmm... where exactly? I'm looking at: https://zed.dev/docs/configuring-zed#folder-specific-settings, and can't find where.

In your theme. or in your settings.json, you can add it to 

```
  "experimental.theme_overrides": {
     "info.background": "#333366",
},
```

**Comment by VoiceNPO** [comment]
Changing those settings doesn't do anything for me.  It's always bright blue and impossible to read.

<img width="372" alt="image" src="https://github.com/user-attachments/assets/fdd32c66-4226-4c61-97ed-f7a95ef482b0">

<img width="839" alt="image" src="https://github.com/user-attachments/assets/c58b7b4c-4000-44e8-a4da-423256290f70">

**Comment by VoiceNPO** [comment]
Correction -- The change is applied, it's just not applied to the current tab.  It seems you either need to open a new tab or reload the workspace for it to pick up the change.  Thanks!

**Comment by esbeto** [comment]
OK, so now that I experimented a little bit I noticed these colors are bad only for that particular theme. The theme switcher does not update the background colors of the AI suggestions, but once you switch to a different theme you will get appropriate colors for that particular theme.

**Comment by danilo-leal** [comment]
Closing this issue for now as it seems like it was theme-specific and less of a "native" error. Most themes I have here (the bulk of them being the ones that come by default with Zed) look all right—granted, some are better than others, but nothing inaccessible to read, such as the screenshots.

https://github.com/user-attachments/assets/e02f711b-69cc-45a1-9c39-281692aee475
