### ISSUE TITLE
Only show copilot completions when requested by keyboard shortcut

### ISSUE THREAD

**Issue by sebastiansandqvist** [zed-industries/zed#19132]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to only display inline copilot completions when specifically requested via a keybinding, such as `"cmd-<": "copilot::Suggest"`?

My ideal workflow would be to never see copilot completions unless I press a keybinding. After pressing that keybinding, I'd like to be able to press it again to accept the completions rather than overloading the `tab` key.

Is any of this possible currently with zed?

**Comment by JosephTLyons** [comment]
Hey @sebastiansandqvist, I think that you can disable completions, via your `settings.json` file:

```json
"features": {
  "inline_completion_provider": "none"
},
```

... then, there's a command palette action: `editor: show inline completions`, which you can rebind to whatever binding, and it should allow you to only summon the suggestion on demand. Does this work for you?

**Comment by sebastiansandqvist** [comment]
Thanks for the quick reply @JosephTLyons. I gave that a try without success. Not sure that it matters, but I'm using `supermaven` as the completion provider, so if I have the `inline_completion_provider` set to `none` the editor probably has no idea that it should attempt to use `supermaven` when I request completions.

```json
  "features": {
    "copilot": true,
    "inline_completion_provider": "supermaven"
  },
```

My keyboard shortcuts look like this:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "cmd->": "editor::ShowCompletions",
      "cmd-<": "editor::ShowInlineCompletion",
    }
  }
]
```

I've also tried binding `copilot::Suggest`, but that didn't change the outcome.

**Comment by JosephTLyons** [comment]
Oh wow, you're correct. If you have it set to`none`, how would Zed know which provider to use? Good call. Clearly, I don't have Zed set up this and wasn't thinking about it too deeply about this.

**Comment by brandondrew** [comment]
would this be easily solved if there were an additional setting to toggle between automatic and on-demand triggering of completions?

```json
"features": {
  "inline_completion_trigger": "command" },
```

"command" refers to the command you've presumably bound to a keystroke.... I couldn't think of a better word... "auto" or "pause" could refer to how it now works

**Comment by bennetbo** [comment]
As far as I am aware, we already support this by setting `show_inline_completions` to `false`.
When set to `false`, you can manually trigger `editor: Show inline completion` to show inline assistant completions.

Explained in more detail in our docs here: https://zed.dev/docs/completions#disabling-inline-completions

Feel free to re-open if I am missing something
