### ISSUE TITLE
Opening the assistant chat window with vim mapping does not work

### ISSUE THREAD

**Issue by TympanicLemon** [zed-industries/zed#19138]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening the assistant chat window, while in normal vim mode...
WHILE having the vi cursor select empty text so nothing is under the cursor
While using a key, something like "space a c" or whatever else you want to imagine, will cause the editor to open the assistant window, but not have a cursor there ready for you to type in

So the idea, is right now it works just fine, if i use the same keymap "space a c" while in vim normal mode, and there is something under my cursor or i try to send text over for context with some lines highlighted all of that works fine

Steps:
1. Either start with an empty file or a file with code
2. For an empty file, write some text and indent it
3. This step is the same for the file with code, move the vim cursor in normal mode to the left (with the mouse or with h/l )
4. With the vim cursor now above nothing (nothing is under it just emtpy space) open the assistant window using a keymapping while in vim normal mode (like "space a c" which is what i have, but any vim keymap does this i have tested it)
5. The assistant chat window opens, but no cursor is there for me to type or to shift into insert mode etc etc

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

The way it should work, is regardless of where my mouse and/or cursor is, or wether its in visual or normal mode I should be able to do any kind of "space key" keymap to open the assistant window and start chatting

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
I cannot reproduce this after binding `space a c` to `assistant::ToggleFocus`. Is there something else you're doing?

Probably a duplicate (and an anagram) of #19381
