### ISSUE TITLE
Terminal supports custom shortcut commands

### ISSUE THREAD

**Issue by Avey777** [zed-industries/zed#19141]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/user-attachments/assets/ae3d7e2b-04bc-4131-8dc6-129cfec6b6db)
![image](https://github.com/user-attachments/assets/42d4180b-1005-4a3f-a4ed-678eb450cb21)

**Comment by notpeter** [comment]
This is not the direction we are pursuing for terminal at this time.
Thanks for reporting.
