### ISSUE TITLE
Zed on windows spawns obnoxious command prompt windows that then immediatelly close, just to check python path or node version, frequently, multiple times.

### ISSUE THREAD

**Issue by anamoyee** [zed-industries/zed#19167]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Compile Zed from source on Windows 10 using the given instructions.
2. Lauch Zed
- 2-3 command prompts launch for .1 of a second and then close
3. Do something within zed, i am not sure what else other than launching the app triggers it as well but i've seen opening the settings file worked, so open settings.
- another few command prompts spawn and close again immediately

Further analysis with sysinternals procmon.exe shows that the command prompt windows are launching python and checking its path or launching node and checking its version, etc.

![image](https://github.com/user-attachments/assets/b89658ef-ce63-4de2-8005-7d29ba775533)

I am not sure if this should go into the bug category but i don't know where else to put it, it's not like, preventing me from using the app but really seems like a bug.

### Environment

Zed: v0.158.0 (Zed Dev ec5d6e96bb304886f49680b54e58c9b0e7221cd6)
OS: Windows 10.0.19045
Memory: 31.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA || 555.99

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Video showing the weird behaviour:
https://github.com/user-attachments/assets/6ee504f2-1dd4-48b8-9330-be94c0da8d7e

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JunkuiZhang** [comment]
Dup of #18371 , see the PR which would address this #18447
