### ISSUE TITLE
can not jump function defined

### ISSUE THREAD

**Issue by freeman-zt** [zed-industries/zed#19174]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am encountering an issue where the 'Go to Definition' and 'Go to Declaration' functions are not working as expected in my Linux development environment.

### Environment

linux c

### If applicable, add mockups / screenshots to help explain present your vision of the feature

no

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>
no

**Comment by SomeoneToIgnore** [comment]
Works on my Linux machine™

So please, fill this very vague issue with more details:

* the language and the language server you are trying to use
* the code repo link or something similar; the video at least
* errors and other logs from `debug: open language server logs` command (it will open a panel with a dropdown of all language servers available: is the one for the language you use there? What does its `RPC messages` show?)
* Zed logs from `zed: open log` command
