### ISSUE TITLE
How to create SSH remote connection with custom identify file?

### ISSUE THREAD

**Issue by diuming** [zed-industries/zed#19171]
### Check for existing issues

- [X] Completed
### Describe the feature

![Screenshot 2024-10-14 at 10 40 11 AM](https://github.com/user-attachments/assets/e035d496-1563-4412-b0da-f58d99899c74)

ssh -i ~/.ssh/my_rsa remove_user_name@192.168.1.31

![Screenshot 2024-10-14 at 10 37 45 AM](https://github.com/user-attachments/assets/5c3fd4c3-e12f-4faa-abe7-62099a8bd23c)

**Comment by notpeter** [comment]
We are intentionally not going duplicate all of the options supported by ssh.
You'll need to use an ~/.ssh/config:

```ssh_config
Host example-server
    HostName example.com
    User username
    IdentityFile ~/.ssh/example_private_key
    Port 22
```
