### ISSUE TITLE
Some SendKeystrokes Keyboard Shortcuts Ending in a Space Character Type Out A Space

### ISSUE THREAD

**Issue by biblicabeebli** [zed-industries/zed#19181]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I believe this is an oversight, not intentional behavior.

Goal: (typeable!) whitespace characters in keystrokes sequences and keyboard shortcuts should require their canonical name be entered, and (typeable!) leading, trailing, and repeated whitespace characters should be coalesced and elided.

Issue: 
- `["workspace::SendKeystrokes",  "shift-up"]` types just a shift-up.
- `["workspace::SendKeystrokes",  " shift-up"]` types just a shift-up.
- **`["workspace::SendKeystrokes",  "shift-up "]` types a shift-up and then a space.**  <<-- this one, this one is the bug.

Details of current behavior:

All of these work as expected
- `["workspace::SendKeystrokes", "a     a"]` types `aa` with no spaces.
- `["workspace::SendKeystrokes", "a \ "],` does not appear to be validly parsed. An error `jsonc: Invalid escape character in string.` is yielded and the keystroke of the command appears to be passed through
  -  (I was doing `alt-n`, it typed `n`). 
- `["workspace::SendKeystrokes", "a a a a a a a a a a a a a a a a a a a a a a a a a a a a "]` types `aaaaaaaaaaaaaaaaaaaaaaaaaaaa` with no spaces.
- All of the following print `aaaaaaaaaaaaaaaaaaaaaaaaaaaa` with no leading, trailing, or interstitial spaces:
  - ```
    ["workspace::SendKeystrokes", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
    ["workspace::SendKeystrokes", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa "]
    ["workspace::SendKeystrokes",  " aaaaaaaaaaaaaaaaaaaaaaaaaaaa "]
    ["workspace::SendKeystrokes",  " aaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
    ["workspace::SendKeystrokes",  " aaaaaa aaaaaaaaa aaaaaaa aaaaaa"]
    ["workspace::SendKeystrokes",  "aaaaaa aaaaaaaaa aaaaaaa aaaaaa"]
    ["workspace::SendKeystrokes",  "aaaaaa aaaaaaaaa aaaaaaa aaaaaa "]
    ["workspace::SendKeystrokes",  " aaaaaa aaaaaaaaa aaaaaaa aaaaaa "]
    ```

<hr>

<details> <summary> <i> Click here to reveal the extremely normal keyboard shortcut that lead me to discover this. </i> </summary>

```
"shift-pageup": [
  "workspace::SendKeystrokes",
  "shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up shift-up "
],
```
</details>

### Environment

Zed: v0.156.1 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 30.6 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

**Comment by CharlesChen0823** [comment]
you can try `a space a`?

**Comment by biblicabeebli** [comment]
`a space a` , ` a space a`, `a space a `, and ` a space a `  all yield `a a`

**Comment by htor** [comment]
Looks like space characters (`U+0020`) are used as delimiters when parsing the keystroke string are are stripped away from the resulting characters.

> a space a ,  a space a, a space a , and a space a all yield a a

And `space a space a space` yields ` a a ` giving you inbetween/leading/trailing whitespaces. Isn't that what you want?

**Comment by biblicabeebli** [comment]
~The bug is bolded in the description~ -- it was not very visibly bold, especially on dark mode. I will .... add a marker...

This is the bug:
> `["workspace::SendKeystrokes",  "shift-up "]` types a shift-up and then a space.

`"shift-up "` with the trailing space character inside the quotation mark is not correctly stripping out the trailing space character.

All the other details here are to indicate that the behavior for every other case I could think of trims trailing (and leading) whitespace.

(I have not tested other "shift-up"-like combined keystrokes.)

**Comment by notpeter** [comment]
Thanks for reporting @biblicabeebli.
I've reordered your description so the incorrect behavior comes first.
