### ISSUE TITLE
Editor Becomes Unresponsive When Opening 7.3M JSON File (Not a Large File Issue)

### ISSUE THREAD

**Issue by polyglotSE** [zed-industries/zed#19194]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am experiencing an issue where Zed Editor becomes unresponsive when attempting to open a 7.3M JSON file. This is different from other reported issues where the file sizes are significantly larger (greater than 1GB). My file is only 7MB, but the editor still freezes entirely, requiring a force stop.

I have attached the following for your reference:

Log files
Screenshot of the unresponsive state

**Steps to Reproduce:**

1. Open Zed Editor.
2. Attempt to open the JSON file.
3. Observe the editor becoming unresponsive.

**Expected Behavior:**
The editor should handle opening and editing 7MB files without performance degradation.

**Actual Behavior:**
Zed Editor freezes and becomes completely unresponsive when opening the file.

**JSON File**
[hi_dictionary.json](https://github.com/user-attachments/files/17364889/hi_dictionary.json)

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-10-14 at 7 07 32 PM](https://github.com/user-attachments/assets/72722446-a408-4c12-a4ea-6f530f76ab26)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17364700/Zed.log)

</pre></details>

**Comment by osiewicz** [comment]
It seems like we spend 99.6% of time in the body of https://github.com/zed-industries/zed/blob/6e2869a321de7a51a970f97012f00cf3335ea06e/crates/gpui/src/platform/mac/text_system.rs#L434

Worth noting, this JSON file is pretty heavy on the use of non-ASCII characters. I'm not making excuses or anything, just pointing that out.

**Comment by mocenigo** [comment]
All on a single line? This is quite extreme.

**Comment by osiewicz** [comment]
Ok, I spent a bit of time on this and made it less miserable. I wouldn't say that the experience is now smooth, but it should feel better. Opening the file takes a second or two and typing in the file is not impossible anymore. I'll keep this issue open because I think we can do better still.

**Comment by polyglotSE** [comment]
@osiewicz Thanks so much for jumping on this and improving the performance! It's great to hear that things are already feeling smoother with opening and typing. I really appreciate you taking the time to address it.

By the way, I've just started learning Rust and would love to contribute to the project in the future. If there's anything beginner-friendly to tackle, I'd be happy to help out.

Thanks again for the quick fix and for keeping the issue open for further improvements!

**Comment by osiewicz** [comment]
I'm glad to hear you'd be interested in contributing. I'd suggest picking something that interests you - I know it sounds vague, but if there's a bug that's nagging you, or if you have an idea you'd love to see come to life, it makes it that much more interesting to pursue compared to "ordinary tickets" from our issue tracker.
Also, I'd recommend joining our [Discord](https://discord.gg/aXkTBfnU); there are plenty of like-minded people there.

**Comment by notpeter** [comment]
@polyglotSE You might also take a look at the [good first issue](https://github.com/zed-industries/zed/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label too.
