### ISSUE TITLE
Workflow edits from transform created in the middle of existing functions

### ISSUE THREAD

**Issue by fonnesbeck** [zed-industries/zed#19195]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The transforms based on workflow edits in the AI sidebar often end up being placed at arbitrary points within the target file, often breaking existing code. For example:

```python


def build_model(
    
def build_new_model(
    df: pd.DataFrame,
    target_name: str,
    continuous_features: list[str],
    categorical_features: list[str],

```

where `build_new_model` is placed right after the existing declaration of `build_model` (but before the body of the code), which completely breaks things. This happens almost every time I use the workflow context.

I have tried adding the instruction "Place new code at the end of the file, and not in the middle of existing code", but this did not work.

### Environment

Zed: v0.156.1 (Zed)
OS: Linux Wayland bluefin 40
Memory: 60.6 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV GFX1103_R1) || radv || Mesa 24.1.7

**Comment by notpeter** [comment]
There is a significant rewrite in progress to restructure the way these proposed changes are shown in the editor:

- https://github.com/zed-industries/zed/pull/18240

I know this may be unsatisfying, but I'm going to close this as when that merges, Zed is unlikely to exhibit the same bugginess that you're seeing now (it'll be All New™ bugs).  If I'm wrong and it's still broken after that, please comment and I'm happy to reopen.

Thanks for reporting. The current behavior is clearly suboptimal, please bear with us as we attempt to improve.

**Comment by fonnesbeck** [comment]
Has this fix found its way into a release yet? I'm still getting suggested code being dropped into random locations.
