### ISSUE TITLE
Can't Do @ Character in Turkish Keyboard 

### ISSUE THREAD

**Issue by sonumuto** [zed-industries/zed#19201]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi,

I’m having trouble typing the “@” character on a Turkish keyboard. I know it sounds strange, but it works fine in other editors, IDEs, and notepads. Normally, we use the key combination Q + Option to get the “@” character. Let me know if you need more details about the issue. Thanks!

### Environment

Not applicable to MacOS.

MacOS Version 15.0.1 (24A348)
Macbook Pro M2 Pro

**Comment by htor** [comment]
Have you tried setting `terminal.option_as_meta = false` in your `settings.json`?

**Comment by sawakaga** [comment]
On Terminal once you do **terminal.option_as_meta = false** it works and @ enables. 

Inside editor still I cannot do @ also

> Have you tried setting `terminal.option_as_meta = false` in your `settings.json`?

**Comment by htor** [comment]
> Inside editor still I cannot do @ also

That might be a conflicting key binding you need to unbind.  In my `Default Key Bindings` I have ` "alt-q": "editor::Rewrap"`. Maybe you need to remap that to `null`?

**Comment by notpeter** [comment]
@htor is correct.  You will want to add the following to your keymap.json (cmd+k, cmd+s):

```json
[
  {
    "context": "Editor",
    "bindings": {
      "alt-q": null
    }
  }
]
```

The work to fix this properly is planned and there is a discussion about some of the details here:
- https://github.com/zed-industries/zed/discussions/17031
