### ISSUE TITLE
Font suggestion in the format of actual font

### ISSUE THREAD

**Issue by DataEnggNerd** [zed-industries/zed#19209]
### Check for existing issues

- [X] Completed

### Describe the feature

While trying to change the font in `settings.json`, a drop down with the font names are displayed. This is a great feature in my opinion. It would be great if the fonts are displayed in the font style itself instead of just the names. 

### Current

![zed-font-suggestions](https://github.com/user-attachments/assets/11ca3b45-95ec-4b57-bea3-44c6d18806d1)

### Expected 

Similar to this

<img width="237" alt="Screenshot 2024-10-15 at 12 08 54 PM" src="https://github.com/user-attachments/assets/1bdeb057-efc1-4264-b37c-a4aef3fbbf8d">

**Comment by jansol** [comment]
This would be nice! But how should it handle fonts that don't contain any latin characters? E.g. emoji/symbol fonts or fonts for languages that don't use latin letters.
