### ISSUE TITLE
Regular Expression Replacement with Case Conversion

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#19205]
### Check for existing issues

- [X] Completed

### Describe the feature

in Vscode

You can use `\u` `\U` `\l` `\L` to convert groups to case

Upper case is for the entire string, lower case is for the first character

https://github.com/user-attachments/assets/2a52bb87-96ca-4e9e-b148-d542f7624bc1

**Comment by notpeter** [comment]
Neat, I'd never seen these before.  I couldn't find a standard name for them, but they are effectively specialized Replacement Escape Strings.

I think the vscode regex library supports [even more substitution elements](https://learn.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions) too:
- `$$` - Literal `$`
- `$1$2$3` etc. Numbered capture groups
- `${name}` Named capture groups
- `\U\L` - Modify the pattern that follows to UPPERCASE/lowercase: e.g. `\U\1`
- `\u\l` - Modify the first character of the pattern that follows to Uppercase/lOWERCASE
- `\E` - Used in combination with `\U\u\l\L` to end case conversion.
- `$&` - Copy of the entire match
- <kbd>$`</kbd> - Copy of everything prior to the match
- `$'` - Copy of everything after the match
- `$+` - Last capture group
- `$_` - Entire input string

We use the [rust regex crate](https://docs.rs/regex/latest/regex/) which only supports `$$`, `$1$2$3` and `${name}` from the above list. it does does not support using `\u\U` and `\l\L` to adjust case. Also neat that it supports stacking so `\u\l\uaBc` becomes `AbC`.

Perhaps worth filing an enhancement request upstream:
- https://github.com/rust-lang/regex/issues

I've been working on some explicit Zed docs for regexes, I will definitely include a reference that these are not supported.

Thanks for reporting.

**Comment by cravussin** [comment]
I don't understand why this issue has been closed given Zed's main goal is to be a VSCode competitor?

**Comment by notpeter** [comment]
Close ws unintentional.

**Comment by jeremyjacob** [comment]
As a stopgap one can use the find in files multibuffer with multi-cursor and command palette functions like convert to lowercase.

**Comment by andyburke** [comment]
Landed here tonight wishing this were merged. 👍 from me on this PR.
