### ISSUE TITLE
Enable the <insert> key on the keyboard to switch between insert and replace mode in vim mode

### ISSUE THREAD

**Issue by rudolfkastl** [zed-industries/zed#19224]
### Check for existing issues

- [X] Completed

### Describe the feature

With vim pressing the insert key once puts vim in insert mode. Pressing the insert key again toggles between insert and replace mode. I am really used to use that key instead of the "i" key for activating insert mode. 

Now with zed i can not seem to map that button to the mode toggle. It would be great to implement that to work by default. Thank you for the great work on the platform.

**Comment by rudolfkastl** [comment]
Platform is Linux. I tried that latest stable release zed-0.156.2. I am talking about the insert key in the 6 key block below "print" left of the numkey pad.

**Comment by KaKi87** [comment]
Hi,

What about non-vim mode ? How to overtype then ?

Thanks

**Comment by elijh** [comment]
Same question. I am missing something? When you are not using vim mode, there doesn't appear to be any command for toggle between insert mode and overwrite / replace / overtype mode.
