### ISSUE TITLE
Autodetecting virtual environment randomly works

### ISSUE THREAD

**Issue by vlebert** [zed-industries/zed#19227]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My current setting for terminal is

```
"terminal": {
    "font_family": "MesloLGS NF",
    "detect_venv": {
      "on": {
        // Default directories to search for virtual environments, relative
        // to the current working directory. We recommend overriding this
        // in your project's settings, rather than globally.
        "directories": [".venv", ".env", "env", "venv"],
        // Can also be `csh`, `fish`, and `nushell`
        "activate_script": "default"
      }
    }
  },
```

When I open a project and open a terminal it generaly does not load in the virtual environment. Sometimes, closing and reopening the terminal is enough to load the virtual environment.

Sometimes not. If I activate manually, and close/open the terminal, is sometimes load at root (`/`) instead of current directory

```
❯ pwd
/
```

Maybe it is somehow related.

I am not sure what can I provide to help with this issue. Virtual environment detection used to work as expected previously. Did something break in last verions ?

### Environment

Zed: v0.156.2 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SirSilver** [comment]
Check if [this](https://github.com/zed-industries/zed/discussions/18806#discussioncomment-10868677) is related. Also if you open terminal with files like zed global settings in active tab, it loads at root

**Comment by vlebert** [comment]
Thanks @SirSilver 

I just tested : unfolding `.env`or `.venv`forder definitely makes terminal work as expected (i.e. loading virtual environment :)

**Comment by notpeter** [comment]
LOL wat? This makes me very unhappy.

**Comment by jacobwhall** [comment]
I am also experiencing this issue, in Zed 0.160.7 on Linux.

When I open the terminal in Zed, the detect_venv activation command is not run unless I have unfolded the .venv directory in the left dock since opening the project.

**Comment by antonpolishko** [comment]
having this issue with uv and mac.
