### ISSUE TITLE
Pressing the enter key in the find bar in vim mode instead of searching it go to the next line

### ISSUE THREAD

**Issue by jkevingutierrez** [zed-industries/zed#19237]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Having a file opened, and opening the find bar (cmd + f) having `"vim_mode": true,`, if you press the enter key it won't navigate using the search term, but instead, it will go to the next line (as if the search bar wasn't open)

When vim mode is disabled, it navigates correctly through the file using the search term. Vim mode should have the same behavior 

### Environment

Zed: v0.156.2 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/6cce8a0e-9b1b-4abe-b96c-f61057114876

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jkevingutierrez** [comment]
Oh I see. Probably to someone that is used to vim it is the correct way to handle it. I was used to the way that VSCode handles it (they have the search bar separate from the search  `/` in vim), but feels like is not a real bug then.

**Comment by baldwindavid** [comment]
Makes sense. All these editors have to make many decisions about how to blend vim in with their own concepts which can result in surprises. In some cases this is more art than science, but think Zed has done / is doing a great job (h/t @ConradIrwin) with blending concepts and custom keybindings can fit other workflows.

**Comment by ConradIrwin** [comment]
Closing as pretty similar to #7692.

I'd like to keep `/ enter` to work like vim; but `cmd-f enter` I have less opinion about.
