### ISSUE TITLE
Support assembly

### ISSUE THREAD

**Issue by lu-zero** [zed-industries/zed#19236]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now assembly support seems completely missing:
- [ ] Apparently there is no syntax highlight enabled out of box
- [ ] There is no support for asm-lsp

**Comment by notpeter** [comment]
There is a community maintained [Assembly Syntax Zed Extension](https://github.com/DevBlocky/zed-asm) which supports syntax highlighting.

You could open an issue there about adding `asp-lsp` support.
Thanks for reporting!
