### ISSUE TITLE
Add missing import does nothing in Astro

### ISSUE THREAD

**Issue by shishkin** [zed-industries/zed#19239]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Astro LSP correctly detects missing imports and suggests code actions. But when I click the "Add import from ..." option (or any other related imports option) nothing happens.

Same feature works as expected in TypeScript files in the same project.

### Environment

Zed: v0.156.2 (Zed)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>astro-language-server server logs</summary><pre>

workspace.semanticTokens.refreshSupport is not supported by the client but could be used by the server.
textDocument.codeAction.disabledSupport is not supported by the client but could be used by the server.

</pre></details>

**Comment by notpeter** [comment]
Did the config you mentioned in:
- https://github.com/zed-industries/zed/pull/16654#issuecomment-2414529004

fix it?
```
  "languages": {
    "Astro": {
      "language_servers": ["astro-language-server", "..."],
      "prettier": {
        "allowed": true
      }
    }
  }
```

If so, we should probably add it to the default settings:
https://github.com/zed-industries/zed/blob/b682fc6d1dad395ef97255307485c6da00f99c69/assets/settings/default.json#L825-L831

**Comment by shishkin** [comment]
Thanks @notpeter! Adding `"plugins": ["prettier-plugin-astro"]` indeed fixed the import issue.
