### ISSUE TITLE
Ghost remote connection after update

### ISSUE THREAD

**Issue by affanshahid** [zed-industries/zed#19260]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just opened my remote projects panel after a while and noticed that my added remote is missing however it still says "1 connection" in the popup. How do I remove this ghost connection?

### Environment

Zed: v0.157.4 (Zed Preview)
OS: macOS 14.6.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="572" alt="image" src="https://github.com/user-attachments/assets/bead12d0-3942-439b-88dd-311719a9258b">

**Comment by SomeoneToIgnore** [comment]
![image](https://github.com/user-attachments/assets/28672767-a247-460e-8111-b59e602ef59d)

Not anymore in the latest code.
Also to note, this feature is not really released, so may change drastically, and contain bugs along the way, so reporting issues might not be the most productive at this stage.
