### ISSUE TITLE
Kubernetes support and autocompletion

### ISSUE THREAD

**Issue by nicraMarcin** [zed-industries/zed#19287]
### Check for existing issues

- [X] Completed

### Describe the feature

How to configure autocompletions for kubernetes manifests?

### If applicable, add mockups / screenshots to help present your vision of the feature

![Zrzut ekranu 2024-10-16 o 17 04 54](https://github.com/user-attachments/assets/b9e9e2b8-261a-46f3-bc84-9b40c86af14d)

**Comment by nicraMarcin** [comment]
@notpeter I see that yaml-language-server is present in `~/Library/Application Support/Zed/languages/yaml-language-server`. I've added this setting but still don't have suggestions  😢

**Comment by notpeter** [comment]
The path you specify `"./config/*.yaml"` needs to match where your yaml files are.

**Comment by nicraMarcin** [comment]
> The path glob you specify `"./config/*.yaml"` needs to match where your yaml files are.

Are you saying about my kubernetes files or schema files? I tried with `*.yaml`, `/*.yaml` with the same result - no result :(

**Comment by nicraMarcin** [comment]
I have found the schema, configured this way:
```json
    "yaml-language-server": {
      "settings": {
        "yaml": {
          "completion": true,
          "schemaStore": {
            "enable": true
          }
        },
        "schemas": {
          "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.1-standalone-strict/all.json": [
            "/*.yaml",
            "/*.yml"
          ]
        }
      }
    }
```
And doesn't work 😔 But when I use inline schema but strict to kubernetes resource 
`# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.1-standalone-strict/secret.json`
![Zrzut ekranu 2024-10-17 o 21 14 47](https://github.com/user-attachments/assets/3b0114c1-5afe-4c45-ad45-088817d4da8a)

It works.
What I am doing wrong? 🤔

**Comment by nicraMarcin** [comment]
Not this scope of schema
```json
"yaml": {
          "completion": true,
          "schemaStore": {
            "enable": true
          },
          "schemas": {
            "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.1-standalone-strict/all.json": "/*.yaml"
          }
        }
```

but now I says that there is too much schemas 😕 
![Zrzut ekranu 2024-10-17 o 21 32 40](https://github.com/user-attachments/assets/81442721-7347-4a55-9faa-ee55f31e5782)
any ideas?

**Comment by yodatak** [comment]
Hello thanks for this issue, but it don't work for flux2 kubenetes yaml ( i think we should make it default and do some docs )
