### ISSUE TITLE
Remote server setup impossible due to short timeout

### ISSUE THREAD

**Issue by fonnesbeck** [zed-industries/zed#19307]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As of version 0.156 and later, I am no longer able to set up a remote server. The process times out after a few seconds even thought the proxy is actively being set up. This is a far too aggressive timeout setting given how much  data needs to be transferred, even over a very fast connection.

### Environment

Zed: v0.157.4 (Zed)
OS: Linux Wayland bluefin 40
Memory: 60.6 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV GFX1103_R1) || radv || Mesa 24.1.7

### If applicable, attach your Zed.log file to this issue.

```
2024-10-16T14:45:19.17896835-05:00 [INFO] uploading remote development server (13887kb)
2024-10-16T14:45:22.011042647-05:00 [INFO] uploaded remote development server in 2.83208123s
2024-10-16T14:45:27.703889287-05:00 [ERROR] failed to establish connection: Timeout detected
2024-10-16T14:45:27.70420365-05:00 [ERROR] Timeout detected
2024-10-16T14:45:27.704265667-05:00 [INFO] shutting down ssh processes
```

**Comment by mrnugget** [comment]
Did you type in the password in the UI? If so, this should be fixed. We didn't take the user prompt into account first. But in the newest Preview version it should be fixed, can you give that a shot? https://zed.dev/releases/preview

**Comment by fonnesbeck** [comment]
This was fixed by the new remote server setup.

**Comment by mlzxy** [comment]
is it possible to customize this through a setting or env variable? I try to connect to a slow and proxy server (with initial commands to be run for each login), zed always timeouts but regular ssh can login (given enough waiting time)
