### ISSUE TITLE
Create a new module

### ISSUE THREAD

**Issue by kurtbuilds** [zed-industries/zed#19313]
### Check for existing issues

- [X] Completed

### Describe the feature

In zed, you can create a new file, but I'd like the ability to add a new module (in Rust) - meaning that when you create the new file, a `mod foo` line automatically gets added to the parent module.

IntelliJ has this functionality.

### If applicable, add mockups / screenshots to help present your vision of the feature

Here's what IntelliJ looks like:

<img width="412" alt="image" src="https://github.com/user-attachments/assets/d961e1a3-68d5-471e-82dd-23561e069afa">

**Comment by notpeter** [comment]
This is already supported via the actions menu (`cmd-.`).

Just create your empty file and then press (`cmd-.`) and rust-analyzer will suggest `Insert mod foo`.

https://github.com/user-attachments/assets/0d39fdeb-bfcc-4685-ba37-7f36dbdd6566

You can do this the other way too. Just write `mod foo;` and then open the actions menu and rust-analyzer will volunteer to create the file for you.

https://github.com/user-attachments/assets/a2bca876-32ac-4de0-ae96-74f1009e87a0

**Comment by kurtbuilds** [comment]
Thank you!
