### ISSUE TITLE
auto update failed from Zed 0.156.2 to 0.157.5 on linux

### ISSUE THREAD

**Issue by ali-42** [zed-industries/zed#19345]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The auto update failed after downloading on Zed startup as well as with the 'check for update' trigger

### Environment

Zed: v0.156.2 (Zed)
OS: Linux Wayland debian 12
Memory: 30.6 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV GFX1103_R1) || radv || Mesa 22.3.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/9332ffa0-c428-496a-b369-a0f07982d7c1)

### If applicable, attach your Zed.log file to this issue.

```
2024-10-17T09:51:16.853202991+02:00 [INFO] downloaded update. path:"/tmp/zed-auto-updatedGoTvI/zed.tar.gz"
2024-10-17T09:51:17.655565389+02:00 [ERROR] auto-update failed: error:No such file or directory (os error 2)
```

**Comment by notpeter** [comment]
Do you have `rsync` installed?

**Comment by ali-42** [comment]
No. I ended up updating by running the install script. It worked

**Comment by mattdaw** [comment]
I had the same issue on a new Arch install, after adding rsync the autoupdate works for me.

**Comment by notpeter** [comment]
Lack of rsync will now show log an error rather than failing silently.
- https://github.com/zed-industries/zed/pull/19392

Thanks all for reporting.
