### ISSUE TITLE
Replace tabs with spaces when pressing tab

### ISSUE THREAD

**Issue by tzabbi** [zed-industries/zed#19342]
### Check for existing issues

- [X] Completed

### Describe the feature

I come from VS Code and want to import all settings. What I didn't found yet is the ability that when pressing tab, zed will replace every tab with the amount of spaces which are configured.

The setting in VS Code is called: 
"editor.insertSpaces": true

**Comment by notpeter** [comment]
By default, we set [`hard_tabs`](https://zed.dev/docs/configuring-zed#hard-tabs) = `false` and set [`tab_size`](https://zed.dev/docs/configuring-zed#tab-size) = `4`.

You can set these globally in your settings or override them per-language in your user settings (`~/.zed/settings.json`) or project settings (`.zed/settings.json`):

```json
"languages": {
  "JSON": {
    "tab_size": 4
  }
}
```

Basically, the default in Zed is equivalent to `editor.insertSpaces` = true.
If I've misunderstood your request can you please provide more detail.
Thanks

**Comment by tzabbi** [comment]
Strange, 

You understand it correctly. Maybe something is overriding the default behavior. I set "hard_tabs: false" in the settings.json and it works. When I remove this line from the settings.json file, it will using tabs again in my go files.

I'm using the linux version 0.157.5 on a ubuntu 22.04

**Comment by notpeter** [comment]
Yes. We override the defaults for golang specifically here:

https://github.com/zed-industries/zed/blob/9d61cd512093f11b4c987d2bbe700b829d4fc6cb/crates/languages/src/go/config.toml#L15-L16

Language extensions can similarly do this, like Makefile which also requires tabs:
https://github.com/caius/zed-make/blob/main/languages/make/config.toml

If you have golang project(s) that uses spaces, I recommend you create a `.zed/settings.json` in the repo with:

```json
{
  "languages": {
    "Go": {
      "hard_tabs": false
    }
  } 
}
```

Editorconfig is still a WIP, but once that lands you could set it per-repo there as well.

Thanks!
