### ISSUE TITLE
Un-binded cursor keys for editor(mode=full) should work in auto-complete dropdowns

### ISSUE THREAD

**Issue by romans-ovo** [zed-industries/zed#19356]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm learning "jkhl" keys for vim mode. For motivation I have un-binded my cursor keys:

```
  {
    "context": "Editor && mode == full",
    "bindings": {
      "up": "zed::NoAction",
      "down": "zed::NoAction",
      "left": "zed::NoAction",
      "right": "zed::NoAction"
    }
```

Sadly this affects auto-complete dropdowns also and I can no longer navigate up/down:

<img width="461" alt="Screenshot 2024-10-17 at 11 31 37" src="https://github.com/user-attachments/assets/8d1bc3a9-cf08-43a4-ba2b-a32db715f488">

I wonder if there is a context or mode to exclude dropdowns? See also: https://github.com/zed-industries/zed/issues/14718

### Environment

Zed: v0.158.1 (Zed Preview)
OS: macOS 14.7.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
If you want to unbind the keys for `up`, `down`, `left`, `right` you'll want to do it everywhere they are bound in [default-macos.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-macos.json) and potentially potentially also rebind `hjkl` there too if necessary.

Some quick searching yielded:
- Global (no context)
- Editor
- ProjectPanel
- OutlinePanel && not_editing
- Editor && (showing_code_actions || showing_completions)

I think what you ran into is this probably the last one needing `j` / `k` added:
https://github.com/zed-industries/zed/blob/5ad392035e5b8855c5a886e45302baf7d4c755cb/assets/keymaps/default-macos.json#L509-L519

FYI: There is also some funkiness with determining which is the "most specific" keybinding context (e.g. if a key is bound under both `Editor && showing_code_actions` or `Editor && mode == full"` which one "wins"? I believe the answer is currently "it depends). So it may be worth trying a few different things.

**Comment by ConradIrwin** [comment]
I think you can fix this by not unbinding things when the menu is open:

```
 {
    "context": "Editor && mode == full && !menu",
    "bindings": {
      "up": "zed::NoAction",
      "down": "zed::NoAction",
      "left": "zed::NoAction",
      "right": "zed::NoAction"
    }
```
