### ISSUE TITLE
extension to install linter & formatter for shell script files

### ISSUE THREAD

**Issue by kurtbuilds** [zed-industries/zed#19378]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, user has to manually set up tools for shell files. It'd be nice to have an extension to set those up - probably shellcheck for linting, and shfmt for formatting.

**Comment by notpeter** [comment]
There is an existing extension which handles this, Basher.
- https://github.com/d1y/bash.zed

<img width="643" alt="Screenshot 2024-10-17 at 16 36 13" src="https://github.com/user-attachments/assets/d55cbeb3-5b1d-4778-9624-4437cffcc894">
