### ISSUE TITLE
Insert an opened  file into the assitant context  should be easier. 

### ISSUE THREAD

**Issue by pdenapo** [zed-industries/zed#19377]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, I find that inserting a currently opened file into the assistant context with /file is not very practical.

I suggest adding "Insert into assistant context" to the contextual menu (that is opened with right-click on the document). Aso /file should show first the opened documents. And may be optionally open a "File Open" dialog would be more user-friendly.

**Comment by pdenapo** [comment]
The current way of choosing the file is particularly uncomfortable when working with something  like svelte-kit when you always have many files with the same name (like +page.svelte, etc.)

**Comment by SomeoneToIgnore** [comment]
Currently opened files can be managed by `/tab` slash command, separately from the files one.

**Comment by notpeter** [comment]
Yeah, `/tab` will default to the currently open tab and `/tab ` will give you a list of open tabs to choose from and `tab all` will add all open tabs.
