### ISSUE TITLE
in vim mode some keymaps are not working for linux

### ISSUE THREAD

**Issue by tednaaa** [zed-industries/zed#19386]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in other apps (like google or vscode), `ctrl + w` closing tab, but in zed it do nothing
only happens for vim mode true

> some other not working keymaps

- `ctrl + w` - close tab
- `ctrl + k w` - close all
- `ctrl + k u` - close clean
- `ctrl + k shift + enter` - pin tab

same issue for both x11 and wayland

### Environment

Zed: v0.157.5 (Zed)
OS: Linux X11 arch unknown
Memory: 15.4 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4060 Laptop GPU || NVIDIA || 560.35.03

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<details>

<summary>settings.json</summary>

```jsonc
{
	"vim_mode": true,
	"vim": { "use_system_clipboard": "always" },
	"relative_line_numbers": true,
	"vertical_scroll_margin": 10,

	"theme": "Ayu Dark",
	"buffer_font_family": "JetBrainsMono Nerd Font",
	"ui_font_family": "JetBrainsMono Nerd Font",
	"buffer_font_features": { "calt": false },
	"cursor_blink": false,
	"ui_font_size": 16,
	"buffer_line_height": { "custom": 1.8 },
	"buffer_font_size": 15,

	"indent_guides": { "enabled": true },
	"tabs": { "file_icons": true },
	"tab_size": 2,
	"hard_tabs": true,
	"show_whitespaces": "selection",
	"soft_wrap": "none",

	"lsp": {
		"rust-analyzer": {
			"initialization_options": { "check": { "command": "clippy" } }
		}
	},

	"features": { "inline_completion_provider": "supermaven" },
	"show_inline_completions": false,

	"git": { "inline_blame": { "enabled": false } }

	// "telemetry": { "diagnostics": false, "metrics": false },
}
```

> keymap.json

```jsonc
[
	{
		"bindings": {
			"ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
			"ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
			"ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
			"ctrl-j": ["workspace::ActivatePaneInDirection", "Down"],

			"z": "project_panel::CollapseAllEntries"
		}
	},
	{
		// normal mode
		"context": "Editor && vim_mode == normal && !VimWaiting && !menu",
		"bindings": {
			"shift-l": "pane::ActivateNextItem",
			"shift-h": "pane::ActivatePrevItem",

			"space v": "pane::SplitRight",
			"space s": "pane::SplitDown",

			"space r": "editor::Rename"
		}
	},
	{
		"context": "ProjectPanel && not_editing",
		"bindings": {
			"z": "project_panel::CollapseAllEntries"
		}
	},
	{
		// insert mode
		"context": "Editor && vim_mode == insert && !menu",
		"bindings": {
			"j j": "vim::NormalBefore"
		}
	},
	{
		// normal & visual mode
		"context": "Editor && (vim_mode == normal || vim_mode == visual) && !VimWaiting && !menu",
		"bindings": {}
	},
	{
		// visual, visual line & visual block modes
		"context": "Editor && vim_mode == visual && !VimWaiting && !menu",
		"bindings": {}
	}
]
```

</details>

**Comment by notpeter** [comment]
You can override the defaults, but `ctrl-w` is intentionally unbound from the default keymap because it is bound in insert mode
https://github.com/zed-industries/zed/blob/2bcf9fc4904fca6ea9aa24eba5a4df5259048e3d/assets/keymaps/vim.json#L337
And used by other chords:
https://github.com/zed-industries/zed/blob/2bcf9fc4904fca6ea9aa24eba5a4df5259048e3d/assets/keymaps/vim.json#L160-L210

---
So you are reporting none of these work for you?
- `ctrl-k w` 
https://github.com/zed-industries/zed/blob/2bcf9fc4904fca6ea9aa24eba5a4df5259048e3d/assets/keymaps/default-linux.json#L257
- `ctrl-k u`
https://github.com/zed-industries/zed/blob/2bcf9fc4904fca6ea9aa24eba5a4df5259048e3d/assets/keymaps/default-linux.json#L256
- `ctrl-k shift-enter`
https://github.com/zed-industries/zed/blob/2bcf9fc4904fca6ea9aa24eba5a4df5259048e3d/assets/keymaps/default-linux.json#L270

**Comment by tednaaa** [comment]
yes, if I do for example, `ctrl + k` then click `w` - it just go next word
and for `ctrl + k u` - it do undo

**Comment by CharlesChen0823** [comment]
you can remap `"ctrl-k": null`, then remap `ctrl-k-w` and `ctrl-k-u`

**Comment by ConradIrwin** [comment]
In vim, `ctrl-w` contains a bunch of pane management commands.

If you want `ctrl-w` to close the tab instead you have to add it to your keybindings file (`ctrl-shift-p zed: Open Keymap`):

```
[
  {
    "bindings": {
      "ctrl-w": "pane::CloseActiveItem"
    }
  }
]
```

Also in vim, `ctrl-k` is overridden to type digraphs in insert mode. This one is quite a bit more annoying to fix, as you currently have to copy *all* the bindings from the default-linux keymap to your own keymap; but you should be able to use the ctrl-k shortcuts from normal mode still.

**Comment by tednaaa** [comment]
strange, for me even in normal mode ctrl + k related keymaps are not working


https://github.com/user-attachments/assets/c51b749e-ff04-4578-bd2c-0ded8e14a0b3

**Comment by tednaaa** [comment]
@ConradIrwin I still facing same issue for normal mode, also for terminal

if I write something, then press `ctrl-w` to close terminal tab it will just clear existing text 


https://github.com/user-attachments/assets/13b331af-f419-4b1e-9a8b-96e5c8055ba9

**Comment by ConradIrwin** [comment]
@tednaaa I believe that is expected in the terminal (because ctrl-w already had a defined meaning, we don't override it in that context).
