### ISSUE TITLE
When ssh asks for input, the Zed preview doesn't let me input

### ISSUE THREAD

**Issue by sophiawisdom** [zed-industries/zed#19389]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I paste in the ssh command to log in to my server, ssh asks if I want to connect to the server, but Zed doesn't let me type yes/no.
<img width="577" alt="image" src="https://github.com/user-attachments/assets/77f65b7f-0486-4421-87e6-101aec1a6b0b">

### Environment

Zed: v0.158.1 (Zed Preview)
OS: macOS 14.2.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Thanks for reporting. I've added it to our internal hit list.

As a workaround you can manually connect once from the command like (`ssh user@host`), say yes and and SSH will cache the host key in `~/.ssh/known_hosts` or you can add `StrictHostKeyChecking accept-new` to your `~/.ssh/config` and SSH will auto-accept keys for new hosts, but still detect if host keys have changed.

But we plan to fix it in the coming days. Thanks
