### ISSUE TITLE
Key strokes in vim mode freezing(or debouncing)

### ISSUE THREAD

**Issue by pedroferreira37** [zed-industries/zed#19402]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hey folks! 

I'm having an issue in Zed where, when I press keys in sequence, like 'jk' or 'kj,' it seems like the keys are being debounced or something, which causes the cursor movement to freeze. If I'm stop pressing the keys, after some that everything is released and the cursor moves again.

This is an extreme example just to show the bug. It creates an annoying effect where, when I'm editing code, the cursor doesn't go where I expect it to.

@mrnugget I'm tagging you because early you said to. 

Thank you all. 

https://github.com/user-attachments/assets/1e8e286a-789f-43c7-98aa-ba6e0982e49e

### Environment

OS: macOS Sequoia 15.0.1
Machine: Macbook Air M1 8GB 2020

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SirSilver** [comment]
If you have "jk" key map for leaving insert mode, make sure your bind does not affect normal mode too. Or maybe you have some other key map including "j"
