### ISSUE TITLE
`vim-surround` aliases don't work as expected

### ISSUE THREAD

**Issue by olivercederborg** [zed-industries/zed#19417]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Some of the `vim-surround` aliases do not work properly. Specifically `b` (parentheses) and `B` (curly brackets).
Looking at the default vim bindings it seems to already be implemented for "change surround", but only applies to the selecting part of the operation.

These are the expected vs actual behaviors I've ran into 👇

For adding surrounds:

Text | Command | Expected | Actual
-- | -- | -- | --
sample text | `yssb` | (sample text) | bsample textb
(sample text) | `ysibB` | ({sample text}) | (Bsample textB)

For changing surrounds:

Text | Command | Expected | Actual
-- | -- | -- | --
(sample text) | `csbB` | {sample text} | Bsample textB
{sample text} | `csBb` | (sample text) | bsample textb

For deleting surrounds:

Text | Command | Expected | Actual
-- | -- | -- | --
(sample text) | `dsb` | sample text | (sample text)
{sample text} | `dsB` | sample text | {sample text}

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mike-lloyd03** [comment]
I took a stab at implementing these aliases.
