### ISSUE TITLE
Option to insert comment character(s) at the beginning of the line(s)

### ISSUE THREAD

**Issue by NichtJens** [zed-industries/zed#19459]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to have the option to change the commenting behavior (preferably per language, but for the entire editor would also work) such that `ctrl+/` on line 3 in this example:

```python
1: def func(a):
2:    if a > 10:
3:        return a * 2
4:    return a**2
```

produces

```python
def func(a):
    if a > 10:
#        return a * 2
    return a**2
```

instead of the current

```python
def func(a):
    if a > 10:
        # return a * 2
    return a**2
```

I.e., instead of inserting `# ` after the indentation, insert `#` at the start of the line.

**Comment by htor** [comment]
I don't how you would make a key binding per language, but putting this in `keymap.json` seems to work:

```
"bindings": {
  "ctrl-/": ["workspace::SendKeystrokes", "ctrl-a ctrl-a #"],
}
```

`ctrl-a` is mapped by default to `editor::MoveToBeginningOfLine` so doing that twice will go to the beginning, ignoring indents and then inserting a literal `#`.

**Comment by NichtJens** [comment]
That's definitely a cool idea for a workaround, the problem is that it would only insert more and more `#` on repeated presses, whereas `ctrl+/` toggles the comment on/off.

On my machine, `ctrl+a` is "mark all" (as I would expect it from most other editors, actually). However, `"home home #"` seems to work.

I suppose, I could define a second one for uncomment: `"home home delete"` ... but still the toggle would be much better.

Additionally, the cursor is obviously moved with this, whereas `ctrl+/` leaves it where it was.

---

Slightly off topic, but: This makes me wish for being able to script the editor. Basically map a script of some sort to a key press, and it has to contain a pre-defined function that receives the currently marked text block as argument. Then, the function has to return a text block, which will be inserted to replace the marked block. This seems relatively simple and would allow basically all sorts of manipulations.

**Comment by htor** [comment]
Yeah, I guess if you want an intelligent keybinding you'd be better off using `"editor::ToggleComments"` as the action, as it will work regardless of language. Maybe the `editor::ToggleComments` action could have an option like:

```
      "ctrl+/": ["editor::ToggleComments", { "ignore_indent": true }],
```

to ignore indentation levels.

**Comment by NichtJens** [comment]
I would assume that the behavior of `ToggleComments` is defined as language specific (Some languages might simply not allow comments to be inserted after the indent, some need a closing string as well, etc.). This probably means that one could modify the behavior in a language extension? If this was feasible, I would be happy to attempt it.

**Comment by notpeter** [comment]
The ToggleComments action is implemented in crates/editor/src/editor.rs in the `toggle_comments` function:
https://github.com/zed-industries/zed/blob/92c29be74cc2ac09dfe0d71d5a1048121b6ab4c6/crates/editor/src/editor.rs#L8659

And is not something which is directly exposed via the Extensions API.  A non-default parameter like the `ignore_indent` @htor proposed above would be one potential path to implement this.
You can see how `["editor::ToggleComments", { "advance_downwards": true }]` is implemented for an example of how that works:
https://github.com/zed-industries/zed/blob/92c29be74cc2ac09dfe0d71d5a1048121b6ab4c6/crates/editor/src/editor.rs#L8906-L8911

If there are languages which always require this (some flavors of INI, COBOL, FORTAN) it could additionally be exposed as a per-language setting via `config.toml` files too.

**Comment by NichtJens** [comment]
@notpeter and @htor, I hope #19746 is what you had in mind :)

**Comment by htor** [comment]
Hey, neat PR!
