### ISSUE TITLE
leading dots confuse the file switcher

### ISSUE THREAD

**Issue by kurtbuilds** [zed-industries/zed#19474]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Various CLI tools will spit out relative paths like:

`./Cargo.toml` or `../../Cargo.toml`

If I copy/paste that into the file finder, it gets confused and returns no results, because nothing matches the `.`.

It should strip either leading, or (I believe this is preferred), any path segment that matches either '.' or '..'. It's doing fuzzy matching, so path changes like that shouldn't affect the result.

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Folding into:
- https://github.com/zed-industries/zed/issues/13408
