### ISSUE TITLE
Don't require unfolding directories in order to create folders/files

### ISSUE THREAD

**Issue by a-non-a-mouse** [zed-industries/zed#19470]
### Check for existing issues

- [X] Completed

### Describe the feature

Let's say I create the folders `React`, and `React/MyComponent`, and then I want to create `React/MyComponent2`.

At the moment, you have to manually unfold the `React/MyComponent` dir in the side panel first.

It'd be nice if right clicking on `React` would create a file/folder there, and right clicking on `MyComponent` would create on there.

**Comment by notpeter** [comment]
I've taken your feedback and some additional bugs I discovered while trying to reproduce and rolled them into a new issue:

- https://github.com/zed-industries/zed/issues/19566

The issue you described was noted in another issue, which was unintentionally closed:
- https://github.com/zed-industries/zed/issues/18770#issuecomment-2402846491

Thanks for reporting.
