### ISSUE TITLE
Zed uses too much memory on big projects

### ISSUE THREAD

**Issue by 30c4** [zed-industries/zed#19490]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have a project with more than a hundred gigabytes of XML files. 
I cannot open this folder with Zed because for some reason it tries to load everything in memory, even though the files themselves are not open in any bufffer. 

It specifically happens when new files are added while the editor is open, for example when a zip file is unzipped inside a folder within the project. 
If the editor is then closed and opened again, it has the same effect. 

Only when a new window is opened and the project is opened again the problem does not persist.

This bug unfortunately makes Zed unusable for bigger projects or projects with a lot of data right now. 

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 14.7.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-10-20 at 14 46 58](https://github.com/user-attachments/assets/a777d196-0723-4c13-9171-3f9b9afbc887)

**Comment by maxbrunsfeld** [comment]
Zed doesn't open any files that you don't ask it to open, but it does store the paths to all files and directories in your project. Could you share a project that showcases this problem?

**Comment by 30c4** [comment]
@maxbrunsfeld unfortunately I do not have a project online that could showcase this problem. 
I think this might be pretty niche as well. 

I just tried it again and could not reproduce so I will close this issue
