### ISSUE TITLE
Zed Ollama integration is BROKEN starting with 0.158.0

### ISSUE THREAD

**Issue by pjv** [zed-industries/zed#19509]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Starting in v 0.158.0, zed preview truncates ollama assistant model output after about a page-worth of text and throws this error:

<img width="409" alt="SCR-20241021-gbdj" src="https://github.com/user-attachments/assets/3e519714-8f71-4fc9-b765-89292eb0edd3">

`Error interacting with language model error decoding response body`

The error occurs independently of which (of several) different ollama models are chosen and also independently of the prompt. The ollama instance that I am connecting to is on another host on my LAN and is at version 0.3.14.

There is absolutely nothing relevant logged into the zed log.

Downgrading Zed preview to version 0.157.4 fixes this issue with no changes to settings and the exact same prompt.

### Environment

Zed: v0.158.0 (Zed Preview)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

EDIT: below are my zed assistant settings

````
  "assistant": {
    "default_model": {
      "provider": "ollama",
      "model": "llama3.1:8b-instruct-q8_0"
    },
    "version": "2"
  },
  "language_models": {
    "ollama": {
      "api_url": "http://pjv-mba:11434",
      "low_speed_timeout_in_seconds": 30
    }
  },
````

**Comment by lmomimi** [comment]
same error zed 0.158.2 ,linux

**Comment by vsguzev** [comment]
Same error. zed 0.159.7, linux

**Comment by pjv** [comment]
I'm guessing all the core Zed devs are using Zed AI / Anthropic and so they don't see and are not impacted by this pretty severe regression.

What is the future of Zed AI integrations? Should we be expecting Zed to continue supporting multiple AI integrations or is there a near future where the only AI assistant that is supported is the Zed AI offering?

**Comment by quachpas** [comment]
Reproduced on v0.160.7 on Copilot models.

**Comment by qingy1337** [comment]
Getting the same error with Ollama

**Comment by KhazAkar** [comment]
![image](https://github.com/user-attachments/assets/e05269dd-524d-44d0-bdbf-b23dcd822df8)
same thing :(

**Comment by jecarroll** [comment]
First hour using Zed and hit this error :(

**Comment by kityr** [comment]
Same error on 0.162.0 here with ollama

**Comment by as-cii** [comment]
Thanks everyone for the feedback and apologies for this bug! I am going to look into this today.

**Comment by mrnugget** [comment]
So is the problem about running ollama on a different machine?

Because locally I can't reproduce this.

![screenshot-2024-11-14-11 09 02@2x](https://github.com/user-attachments/assets/efb9ccb0-f7ff-4e28-8632-dc4267a0ebe1)

![screenshot-2024-11-14-11 11 02@2x](https://github.com/user-attachments/assets/3e1b5e32-2646-4942-a37d-2b812c9dae65)

**Comment by kityr** [comment]
@mrnugget the problem occurs when the llm's reply exceeds some length, try getting a longer output. This bug occurs for me even for locally installed ollama btw.

**Comment by mrnugget** [comment]
Even that seems to work for me:

https://github.com/user-attachments/assets/7a0b39d0-d4e9-48e6-8603-26e035d5a21a

Does anyone have any log output when they run into this error? `zed: open logs`?

**Comment by KhazAkar** [comment]
> So is the problem about running ollama on a different machine?
> 
> Because locally I can't reproduce this.
> 

In my case I run Ollama locally

**Comment by kityr** [comment]
@mrnugget just now recreated it, anything specific i should look for in the logs?
![image](https://github.com/user-attachments/assets/906b5f2d-d4da-42d6-953d-53d3bf6d29f0)

**Comment by mrnugget** [comment]
I'm not sure, my hope is that we log an error somewhere, but maybe we don't even do that. We'll need to improve the logging.

Which version of Ollama are you using?

**Comment by kityr** [comment]
ollama 0.3.6 here

**Comment by mrnugget** [comment]
Is anything logged on the Ollama side? https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

**Comment by pjv** [comment]
I just updated Zed Preview to 0.162.0. I'm running Ollama v. 0.41.

I just reproduced the exact same error that I originally reported in the OP.

There is nothing logged in the Zed log related to using the AI.

The entirety of what is logged on the Ollama side in response to the prompt in Zed that caused the error looks like this:

`[GIN] 2024/11/14 - 04:52:43 | 200 | 29.958155625s |    10.111.5.102 | POST     "/api/chat"`

(That's it: 1 line in the log)

**Comment by kityr** [comment]
same as @pjv here, tailing Zed.log while reproducing the error seems to produce no output at all
Ollama server logs don't show anything other than the POST request either

**Comment by mrnugget** [comment]
Alright, let me look into adding more logging. While I do that: do you have any special prompts in use? In your default prompts maybe? Do you use normal chat?

**Comment by kityr** [comment]
I personally never customized the LLM chat feature, so I don't think I'm using any custom prompts

**Comment by pjv** [comment]
> do you have any special prompts in use? In your default prompts maybe? Do you use normal chat?

I have not created any special prompts nor modified the default (empty) prompt. I don't know what "normal chat" means in this context.

@mrnugget if you didn't see it, you might want to take a look at this [post above](https://github.com/zed-industries/zed/issues/19509#issuecomment-2457036033).

**Comment by KhazAkar** [comment]
No customizations etc.Ollama 0.4.1, downloaded today. Zed system specs:
```
Zed: v0.161.1 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 5500 (BDW GT2) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2
```

I have maybe something in logs from Zed side:
```
024-11-14T12:06:30.668173312+01:00 [INFO] perform;
2024-11-14T12:06:30.668246145+01:00 [INFO] authenticate;
2024-11-14T12:06:30.668425754+01:00 [INFO] read_command;
2024-11-14T12:06:30.670203016+01:00 [INFO] socket reader;
2024-11-14T12:06:32.989381615+01:00 [INFO] perform;
2024-11-14T12:06:32.989454011+01:00 [INFO] authenticate;
2024-11-14T12:06:32.98949812+01:00 [INFO] perform;
2024-11-14T12:06:32.989540986+01:00 [INFO] authenticate;
2024-11-14T12:06:32.989578254+01:00 [INFO] read_command;
2024-11-14T12:06:32.989618435+01:00 [INFO] read_command;
2024-11-14T12:06:32.989770454+01:00 [INFO] perform;
2024-11-14T12:06:32.989827164+01:00 [INFO] authenticate;
2024-11-14T12:06:32.989890427+01:00 [INFO] read_command;
2024-11-14T12:06:32.991036824+01:00 [INFO] socket reader;
2024-11-14T12:06:32.995011924+01:00 [INFO] socket reader;
2024-11-14T12:06:32.996206437+01:00 [INFO] socket reader;
2024-11-14T12:06:36.852974928+01:00 [ERROR] missing field `name` at line 76 column 1
```
![image](https://github.com/user-attachments/assets/e257047f-8beb-492b-8b78-303c71c020c8)

**Comment by KhazAkar** [comment]
I bumped mine from default to 900 seconds and worked in my case. Would be best for others to test it :)

**Comment by jecarroll** [comment]
Confirmed workaround for me too.

Before I overrode `low_speed_timeout_in_seconds`, I ran a stopwatch on the long-running Ollama generation and it failed at exactly 60 seconds. I then overrode `low_speed_timeout_in_seconds` to be 900 and re-ran the same prompt. Execution completed after 133 seconds with no error message.
