### ISSUE TITLE
Sync installed extensions

### ISSUE THREAD

**Issue by tzabbi** [zed-industries/zed#19512]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm using zed with multiple devices. I'm managing the settings and hotkeys through my dotfiles repository, which works really well. Which is a bit of pain is the extension management. I have to install it on every device separately. My proposal is that there is a third file or a section in the settings file which contains all installed extensions. On every startup, zed takes care of it and installs extensions which are in this section/file or uninstalls extensions which are not part of this section/file but installed on the system.

Thanks

**Comment by maxdeviant** [comment]
You might be able to leverage the `auto_install_extensions` setting for this:

https://github.com/zed-industries/zed/blob/755fd695f5271115a692d0beab872aa676011b7d/assets/settings/default.json#L817-L823

Having an extension set to `true` will make sure it's always installed, and having it set to `false` will mean it will never be installed.

**Comment by tzabbi** [comment]
Nice thank you! How I get the names of the extensions?

**Comment by maxdeviant** [comment]
> Nice thank you! How I get the names of the extensions?

If you have the extensions installed, you can look at the directory names in the [extension installation directory](https://zed.dev/docs/extensions/installing-extensions#installation-location).

So on my machine:

```
λ ls -l ~/Library/Application\ Support/Zed/extensions/installed/
total 0
drwxr-xr-x  4 maxdeviant  staff  128 Aug 27 16:06 chanterelle/
drwxr-xr-x  4 maxdeviant  staff  128 Aug 29 13:02 code-stats/
drwxr-xr-x  6 maxdeviant  staff  192 Oct 15 14:13 gleam/
drwxr-xr-x  4 maxdeviant  staff  128 Oct  4 10:01 gleam-theme/
drwxr-xr-x  6 maxdeviant  staff  192 Oct 16 16:21 html/
drwxr-xr-x  6 maxdeviant  staff  192 Aug 19 15:29 julia/
drwxr-xr-x  5 maxdeviant  staff  160 Oct  7 10:47 just/
drwxr-xr-x@ 4 maxdeviant  staff  128 Sep 30 12:06 melange/
drwxr-xr-x  6 maxdeviant  staff  192 Jul  5 16:57 nix/
drwxr-xr-x  6 maxdeviant  staff  192 Jul 27 20:44 pest/
drwxr-xr-x  5 maxdeviant  staff  160 May 13 16:30 scheme/
drwxr-xr-x  6 maxdeviant  staff  192 Sep  3 09:55 scss/
drwxr-xr-x  5 maxdeviant  staff  160 Aug 27 16:03 sql/
drwxr-xr-x  6 maxdeviant  staff  192 Aug 23 13:43 swift/
drwxr-xr-x  6 maxdeviant  staff  192 May 13 12:17 toml/
drwxr-xr-x  6 maxdeviant  staff  192 May 21 14:57 wit/
```

Each of those directory names is the extension's ID.
