### ISSUE TITLE
Unable to sign in to Copilot

### ISSUE THREAD

**Issue by agjini** [zed-industries/zed#19539]
Hi,
I'm experiencing the same bug. The copilot sign in modal seems to be stuck.

I'm running manjaro i3 - Zed 0.152.4.

No error in logs.

![2024-10-22_09-27](https://github.com/user-attachments/assets/7733230b-61f0-4d3d-9c91-820680927bb0)

Is it a regression ?

_Originally posted by @agjini in https://github.com/zed-industries/zed/issues/7309#issuecomment-2428539915_

**Comment by notpeter** [comment]
Please do not create issues that bypass the templates.
Please create a new "Bug Report" issue that includes your Zed Environment and relevant content from your logs.

https://github.com/zed-industries/zed/issues/new/choose
