### ISSUE TITLE
Rewrap adds a blank line when words don't fit in target line length

### ISSUE THREAD

**Issue by scottyeager** [zed-industries/zed#19532]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running the rewrap command on text that contains words longer than the target line length results in a blank line added above the targeted text.

The simplest example is when a line contains a single word that's longer than the wrap length. Using a comment helps make the outcome clearer. Here's an example in Python mode.

Before rewrap:
```
# https://github.com/zed-industries/zed/issues/new?assignees=&labels=admin+read%2Ctriage%2Cdefect&projects=&template=1_bug_report.yml
```

After rewrap:
```
#
# https://github.com/zed-industries/zed/issues/new?assignees=&labels=admin+read%2Ctriage%2Cdefect&projects=&template=1_bug_report.yml
```

This also applies when applying the rewrap command to multiple lines, if and only if the top line is a word too long to break. If the long word is on a lower line, wrapping proceeds normally and no extra line is inserted.

If there are words following the long word on the same line, they are wrapped, but the new line is still added above.

### Environment

Zed: v0.157.5 (Zed)
OS: Linux X11 arch unknown
Memory: 23.2 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 (KBL GT2) || Intel open-source Mesa driver || Mesa 24.2.5-arch1.1

**Comment by notpeter** [comment]
I can reproduce (MacOS Zed Nightly 0.159.0).
