### ISSUE TITLE
commands to toggle copilot on and off easily

### ISSUE THREAD

**Issue by humanchimp** [zed-industries/zed#19545]
### Check for existing issues

- [X] Completed

#### Summary:
I'd like to request the addition of commands in Zed to easily toggle Copilot on and off.

#### Description:
In Vim, I can quickly enable and disable Copilot by typing `:Copilot enable` or `:Copilot disable`. I prefer to have Copilot turned off by default to maintain focus, but there are times when it's useful to turn it on temporarily. Having a similar functionality in Zed would make it easier to control when Copilot is active without diving into menus or settings. This feature would greatly improve my workflow by offering a more focused editing experience with the option to enable Copilot when needed.

#### Benefits:
- Allows users to control Copilot's distraction level by toggling it on or off quickly.
- Reduces the need to navigate through settings, enhancing productivity.
- Mirrors a familiar and efficient workflow from Vim for users who are accustomed to such shortcuts.

Thank you for considering this!

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="602" alt="Screenshot 2024-10-22 at 6 48 48 AM" src="https://github.com/user-attachments/assets/4e21cad5-d68b-4b78-bf6a-d3fae26b9b31">

_Exhibit_: I do not see my beloved copilot: enable and copilot: disable commands from vim

**Comment by bennetbo** [comment]
I think we already have support for this? There is `editor::ToggleInlineCompletions` which allows to temporarily enable/disable inline completions.

**Comment by bennetbo** [comment]
I'm going to close this, but feel free to re-open if I am missing something.

**Comment by notpeter** [comment]
For anyone looking to attach a keybind to this you can drop the following in your `~/.zed/keymap.json`:
```json
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-alt-cmd-\\": "editor::ToggleInlineCompletions"
    }
  }
]
```

And change the keyboard shortcut to whatever you'd like.
