### ISSUE TITLE
Annoying structure fields popup

### ISSUE THREAD

**Issue by DevNulPavel** [zed-industries/zed#19586]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello

After completition for struct fields usually popups struct description window over completiton panel? How can i disable it? 

<img width="699" alt="Screenshot 2024-10-23 at 09 45 28" src="https://github.com/user-attachments/assets/ecdd4557-9e41-4abc-a570-2848708fbc46">

<img width="923" alt="Screenshot 2024-10-23 at 09 51 01" src="https://github.com/user-attachments/assets/0234bdef-b804-4f2c-86eb-6eb30708fdba">

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
You're looking for 
https://github.com/zed-industries/zed/blob/d0bc84eb33627620dee3bd5b784ffc2774a2287a/assets/settings/default.json#L150-L152

so adding `"show_signature_help_after_edits": false` in your local settings should help.
