### ISSUE TITLE
editor::GoToImplementation should be editor::FindAllImplementations

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#19582]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

not sure if i'm misunderstanding this name, but when i tried this command out it displayed a list of all implementations for the type, similar to editor::FindAllReferences. i'd expect "GoTo" to take me to a single location, e.g. editor::GoToDefinition

### Environment

Zed: v0.157.5 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
The way it works is similar to VSCode, where GoToDefinition falls back to finding all usages if no definitions to navigate to were found.

Not sure what can be done here, as either way there will be people that want something else.

One way to improve this could be adding a field into `GoToDefinition` action to control the fallback behavior: this way, people can alter their bindings if they prefer fallback-less navigations.

See https://github.com/zed-industries/zed/pull/19746 for the example of such change.

**Comment by andrewbanchich** [comment]
> The way it works is similar to VSCode, where GoToDefinition falls back to finding all usages if no definitions to navigate to were found.

that seems odd to me - i'm not sure why someone would want all usages / references when they're looking for an implementation of something. i'd rather it just tell me it couldn't find it. plus, `editor:FindAllReferences` exists already.

but yeah, it would be great to have a general optional "fallback" config setting for these things.

i'll open a different ticket to suggest this. thanks!
