### ISSUE TITLE
Scrolling up/down X lines with key shortcut in non-vim mode

### ISSUE THREAD

**Issue by snaerseljan** [zed-industries/zed#19591]
### Check for existing issues

- [x] Completed

### Describe the feature

I would love to be able to scroll up/down x lines with a key shortcut. I know this is possible in vim mode but I am not there yet. This is the only thing keeping me going completely over

Thank you for your awesome editor

**Comment by CharlesChen0823** [comment]
maybe you can use go_to_line？

**Comment by snaerseljan** [comment]
@CharlesChen0823 how would that keybinding look like. I want to go lets say 5 lines up and 5 lines down.

**Comment by CharlesChen0823** [comment]
ahhh, sorry, i'm misreading. `editor: half page down/up` might do some help.

**Comment by snaerseljan** [comment]
Thank you so much 🙏 . Game changer for me
