### ISSUE TITLE
How can I hide this topbar

### ISSUE THREAD

**Issue by Demolemon11** [zed-industries/zed#19598]
### Check for existing issues

- [X] Completed

### Describe the feature

![Screenshot from 2024-10-23 18-32-27](https://github.com/user-attachments/assets/4800acbd-2121-4eb7-a41b-776de879520b)

**Comment by Demolemon11** [comment]
On Linux, window manager is `Mutter`

**Comment by JosephTLyons** [comment]
We don't currently have a way to hide the title bar in Zed. Feel free to upvote (👍) so we can keep all of the votes in one spot:

- https://github.com/zed-industries/zed/issues/5120
