### ISSUE TITLE
Scrolling using mouse doesn't work on linux

### ISSUE THREAD

**Issue by Kibranoz** [zed-industries/zed#19603]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am unable to scroll using my mouse wheel. My mouse works on other apps

### Environment

Zed: v0.157.5 (Zed)
OS: Linux X11 pop 22.04
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment]
Which part of the app are you scrolling in? We have scrollbars in project panel and editor. Can you scroll in either?

**Comment by Kibranoz** [comment]
I cannot scroll in either

**Comment by Kibranoz** [comment]
It also doesn't work in 0.158.1

**Comment by Kibranoz** [comment]
It is working in 0.158.2
