### ISSUE TITLE
Zig support | build_on_save/check doesn't appear to be working

### ISSUE THREAD

**Issue by iamcdonald** [zed-industries/zed#19617]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the zig language extension I'm unable to get syntax highlighting expected for `build_on_save` functionality as outlined in this [blog post](https://kristoff.it/blog/improving-your-zls-experience/).

I'm unsure if there's more I need to configure on top of the out of the box extension and even defining something like (whilst picking up the `--enable-dbug-messages args`) doesn't appear to work.
```
"languages": {
    "zig": {
      "formatter": "language_server",
      "language_servers": ["zls"]
    }
  },
  "lsp": {
    "zls": {
      "binary": {
        "path": "/Users/ooooo/.zvm/bin/zls",
        "arguments": ["--enable-debug-log", "--enable-message-tracing"]
      },
      "initialization_options": {
        "enable_autofix": true,
        "enable_build_on_save": true,
        "inlay_hints_hide_redundant_param_names": true,
        "warn_style": true,
        "highlight_global_var_declarations": true
      }
    }
  }
  ```

I'm wondering if anyone can point me to what I'm doing wrong or can attest to it working for them.

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="468" alt="Screenshot 2024-10-23 at 11 03 38" src="https://github.com/user-attachments/assets/177bb80c-1776-4bc9-8ea0-d909c0677aa0">

Upon saving the above I expected the `check` command to be run by the language server (`zls`) and the resulting error to be surfaced. Just for completeness this is the error produced from running `check`.
```
src/test.zig:4:35: error: type 'i16' cannot represent integer value '2147483647'
    const x: i16 = std.math.maxInt(i32);
```

**Comment by Techatrix** [comment]
> @Techatrix hate to ping you but youve practically written half of zls at this point

I don't mind being pinged. Always happy to help wherever I can :)

---

I was not able to reproduce this issue. I have copied the provided Zed settings, manually specified the path to my ZLS nightly (`0.14.0-dev.175+ea2c303`) and added Zig nightly (`0.14.0-dev.2034+56996a280`) to my PATH. I inspected the log file and saw that ZLS correctly ran `zig build check` and reported the diagnostics. `zig ast-check` diagnostics also worked for me.

If haven't anything that let me to believe that this issue is related to Zed specifically. @iamcdonald Did you use the latest nightly of Zig and ZLS? If so, could you also share your [zls.log](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output) file?

**Comment by xdBronch** [comment]
huh its working for me now, i updated zed last night after a little while i wonder if that fixed it. fwiw my logs showed zls running build on save, i just didnt get any diagnostics from it

**Comment by iamcdonald** [comment]
Hi @Techatrix, @xdBronch  

thanks for taking a look, really appreciate it.

I put together a [demo repo](https://github.com/iamcdonald/zed-syntax-highlighting-test) to show the exact setup I have only to find it then start working.

Now it's working I _think_ I'm noticing a couple of issues but they're more related to `zls` so I've popped a couple of issues ([1](https://github.com/zigtools/zls/issues/2060), [2](https://github.com/zigtools/zls/issues/2061)) there. Happy to be told it's just my misunderstanding though.

Going to close this issue though.

Thanks again everyone.

**Comment by griffi-gh** [comment]
it works at first but for some reason stopped working in all of my projects as they grew
