### ISSUE TITLE
Distribution not always updated

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#19613]
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the images, not all distributions are updated to the latest versions.

Link: https://repology.org/project/zed-editor/versions

![image](https://github.com/user-attachments/assets/ba8f62e5-5102-48e6-a3bb-c626360181c7)

<img width="786" alt="Screenshot 2024-10-23 alle 16 26 25" src="https://github.com/user-attachments/assets/ffce4206-c926-456a-ade3-53b0c4a51394">
<img width="618" alt="Screenshot 2024-10-23 alle 16 22 11" src="https://github.com/user-attachments/assets/fa9890ec-1e6a-446e-a23d-ea74f283b096">
<img width="573" alt="Screenshot 2024-10-23 alle 16 22 27" src="https://github.com/user-attachments/assets/2dc0b7bf-cc31-436e-85b3-996baa5e38b7">
<img width="559" alt="Screenshot 2024-10-23 alle 16 22 53" src="https://github.com/user-attachments/assets/111d35e4-5fed-4901-8f77-e0cbe906f3c0">
<img width="800" alt="Screenshot 2024-10-23 alle 16 23 41" src="https://github.com/user-attachments/assets/319a14c2-801c-4dc0-bbe5-c6f99d862d8b">
<img width="838" alt="Screenshot 2024-10-23 alle 16 24 05" src="https://github.com/user-attachments/assets/110586ce-c56f-4f3d-bad3-d765b624e3c9">
<img width="827" alt="Screenshot 2024-10-23 alle 16 24 47" src="https://github.com/user-attachments/assets/68571f72-f678-42ea-89b8-8a013efc7aa5">
<img width="828" alt="Screenshot 2024-10-23 alle 16 24 57" src="https://github.com/user-attachments/assets/8973e706-be04-42fa-9982-c336f06d71e7">

**Comment by notpeter** [comment]
These unofficial packages are not maintained by Zed and are instead managed by the individual packages maintainers.  If you are seeing outdated packages for your distro you may need to nudge those maintainers.
