### ISSUE TITLE
Running zed as root fails/bugs out

### ISSUE THREAD

**Issue by htor** [zed-industries/zed#19648]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Starting zed as root user using `zed` fails with an error message:
```
~ # zed
Error: cannot start app bundle Zed 0.158.1 – /Applications/Zed Preview.app
~ #
```
It's unclear to me why zed can't start as root and the message here doesn't provide many clues.

Alternatively, starting zed as root using `sudo zed` opens zed, but the sudo password prompt somehow appears _inside_ zed in the terminal, not in the terminal running the sudo command: 
<img width="1241" alt="Screenshot 2024-10-24 at 00 44 11" src="https://github.com/user-attachments/assets/258f0814-7bc8-49bd-9494-9e63fadf57c1">

I may login there, but my shell is no longer a login shell (indicated by the value of `$0`) so it complains about functions missing from `.bash_profile`:

<img width="964" alt="Screenshot 2024-10-24 at 00 52 13" src="https://github.com/user-attachments/assets/bca97fc6-ed11-489a-a6c4-f5210411c4c2">

### Environment

Zed: v0.158.1 (Zed Preview)
OS: macOS 12.7.4
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
We do not support running Zed as root. This is for a number of reasons, but notably any files created while running Zed under sudo (`~/.config/zed/settings.json`, `~/Library/Caches/Zed`, etc) will be owned by root which will likely make it impossible for a user to ever /not/ run as root in the future as there will `permission denied` when trying to write to those files.

See also:
- https://github.com/zed-industries/zed/issues/13259
