### ISSUE TITLE
Can't select outline panel item with keyboard

### ISSUE THREAD

**Issue by jkempff** [zed-industries/zed#19664]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When moving the focus to the outline panel via `⌘ + ⇧ + B`, I can use the arrow keys to navigate through symbols. Selecting a symbol via keyboard is not possible though. On the other hand, clicking on an item works as expected.

### Environment

Zed: v0.158.1 (Zed)
OS: macOS 14.6.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Pressing Enter should move the focus to the corresponding symbol in the active buffer. Basically the same as with `⌘ + ⇧ + O`.

For me personally it's not a big problem, since I use `⌘ + ⇧ + O` most of the time, but consistency wise, I'd say it make sense to align those two lists.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/0ffc92ab6524000ead73b75ff5a21fcbeab37e05/assets/keymaps/default-macos.json#L563

`space` is a default binding for opening things in outline/project panels as `enter` is a default binding for renaming in macOs.
This can be overridden to `enter` if needed, but the mac defaults are unlikely to change.

**Comment by SomeoneToIgnore** [comment]
It's a dichotomy between UI elements' workflow.

`⌘ + ⇧ + O` opens an outline modal, which operates same as other modals: enter to accept, esc/defocus to dismiss, arrows to navigate, etc. 
UI-wise, it would be odd to make outline modal to accept something else.

The panel can hold an arbitrary contents and less bounded by keybinding agreements, but in the outline panel case, it replicates the same tree view as the project panel has, up to the point of having the same autofold features.
So it would be odd not to copy basic navigation from the project panel, wouldn't it?

Albeit the outline panel is readonly and does not allow renaming anything, opening is a different operation in the project panel, with its own keybinding, so the same was used there too.
Opening keybinding was picked to mimic VSCode and a few other editors on macOS, as other people thought it's a bit odd not to behave the same way.
The way to do that in VSCode on macOS by default, is to mimic Finder behavior from macOS.

> But maybe it'll be possible to rename/refactor symbols from there at some point..

I have no idea what kind of refactoring is supposed to help here, and definitely no renaming of anything is needed.

I also do not believe it's feasible to change the default keybindings for macOS too at this point — someone find another way of doing things a bit odd anyway.

Instead, seems more beneficial to keep it more consistent by default, and allow overriding things for people who what something else.

**Comment by jkempff** [comment]
> But maybe it'll be possible to rename/refactor symbols from there at some point..

When reading my comment again, I realise that it sounds like I'm suggesting to refactor or rename anything in Zed. That is not at all what I wanted to say. I didn't mean to change any default keybindings either. Sorry if I gave the wrong impression here.

My thought when writing the comment was that `enter` in the outline panel could behave just like in the project panel: When pressing `enter` on an item in the outline panel, a user could rename this specific symbol. Just like you can rename a file in the project panel with `enter`,  you could rename a symbol in your code. 

…but it was only a small thought. I have no idea if it would make sense in all cases and the effort might outweigh the usefulness.

> I also do not believe it's feasible to change the default keybindings for macOS too at this point
> Instead, seems more beneficial to keep it more consistent by default, and allow overriding things for people who what something else.

I fully agree.
