### ISSUE TITLE
Zed Editor Crash with SOCKS5 Proxy Settings

### ISSUE THREAD

**Issue by benmooo** [zed-industries/zed#19665]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed Editor crashes upon startup when configured with SOCKS5 proxy settings.

**Steps to Reproduce:**  
1. Configure the proxy settings to use the socks5 schema. 
2.  Open Zed Editor.  

### Environment

Zed: v0.158.1 (Zed)
OS: macOS 13.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

$ zed --foreground                                                                           (base)
[2024-10-24T16:08:41+08:00 ERROR zed::reliability] {
  "thread": "main",
  "payload": "could not start HTTP client: builder error\n\nCaused by:\n    unknown proxy scheme",
  "location_data": {
    "file": "crates/zed/src/main.rs",
    "line": 474
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::result::unwrap_failed",
    "<<gpui::app::App>::run<zed::main::{closure#5}>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}",
    "gpui::platform::mac::platform::did_finish_launching"
  ],
  "app_version": "0.158.1",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "13.5.0",
  "architecture": "aarch64",
  "panicked_on": 1729757321320,
  "system_id": "4721296a-ee3a-4d78-bbac-12b2dde821da",
  "installation_id": "b3e731a5-07b7-4909-b565-9d5bb1b6a6ab",
  "session_id": "2b7a7dbf-3d72-454d-92c9-3a058236cba1"
}
</pre></details>

**Comment by JunkuiZhang** [comment]
Already fixed via #19123, the proxy should work again in newer release.

**Comment by notpeter** [comment]
Can you try the latest [Zed Preview](https://zed.dev/releases/preview) and see if it's fixed there?

I'll try to get a hotfix for stable out soon which includes:
- https://github.com/zed-industries/zed/pull/19123

**Comment by benmooo** [comment]
Yes, the latest Zed Preview resolved the panic issue.

> Can you try the latest [Zed Preview](https://zed.dev/releases/preview) and see if it's fixed there?
> 
> I'll try to get a hotfix for stable out soon which includes:
> 
> * [reqwest_client: Fix `socks` proxy settings #19123](https://github.com/zed-industries/zed/pull/19123)

**Comment by zavakid** [comment]
0.158.2  has the same problem, can we release a new stable version?

**Comment by huhu415** [comment]
0.158.2 has the same problem, can we release a new stable version?

```
2024-10-25T11:22:20.590581+08:00 [INFO] ========== starting zed ==========
2024-10-25T11:22:20.592928+08:00 [INFO] Opening main db
2024-10-25T11:22:20.594453+08:00 [INFO] Opening main db
2024-10-25T11:22:20.62166+08:00 [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-10-25T11:22:20.674813+08:00 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/hello/.orbstack/bin:/Users/hello/go/bin
2024-10-25T11:22:20.771992+08:00 [ERROR] {
  "thread": "main",
  "payload": "could not start HTTP client: builder error\n\nCaused by:\n    unknown proxy scheme",
  "location_data": {
    "file": "crates/zed/src/main.rs",
    "line": 474
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::result::unwrap_failed",
    "<<gpui::app::App>::run<zed::main::{closure#5}>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}",
    "gpui::platform::mac::platform::did_finish_launching"
  ],
  "app_version": "0.158.2",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "15.0.1",
  "architecture": "aarch64",
  "panicked_on": 1729826540771,
  "system_id": "c8f06adc-6a03-4085-8c78-b5f962bc42ea",
  "installation_id": "c74be8bb-63f4-42ba-ad96-12bb70aefa72",
  "session_id": "b2a4e6c6-eed6-4cee-81b7-1bc6d3cf8258"
}
```

**Comment by ConradIrwin** [comment]
v0.159 stable was released with this fix.
