### ISSUE TITLE
No workflow in 0.159.0

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#19671]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="270" alt="image" src="https://github.com/user-attachments/assets/f1661f2a-fcaa-4c43-9857-f44975fedbad">

### Environment

Zed: v0.159.0 (Zed Preview)
OS: macOS 15.0.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by arrrrny** [comment]
/workflow is the best feature of ZED AI that I use all the time and now it is gone. Nothing on the release notes.
 I am on Preview 0.159.2
<img width="603" alt="Screenshot 2024-10-29 at 10 45 04 AM" src="https://github.com/user-attachments/assets/73ce11b8-661c-4e3e-9768-10b36d0dc885">

**Comment by SomeoneToIgnore** [comment]
See also https://github.com/zed-industries/zed/pull/19900

**Comment by arrrrny** [comment]
> I was able to bring it back by enabling the [`enable_experimental_live_diffs`](https://github.com/zed-industries/zed/pull/19900#issue-2621396380) in `0.159.4`.
> 
> ```json
>   "assistant": {
>     "enable_experimental_live_diffs": true
>   }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/21281852/381320759-f2e0ee4e-32d3-4039-b250-f55c69127808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTA5NDMsIm5iZiI6MTczMDM1MDY0MywicGF0aCI6Ii8yMTI4MTg1Mi8zODEzMjA3NTktZjJlMGVlNGUtMzJkMy00MDM5LWIyNTAtZjU1YzY5MTI3ODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0NTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NWU3N2JkOGYzODJiNWUwNWZiMTA1NzUwNzFkMjE1NmI2MzEwZDg3YTE0YTkwOTk0YzgyMmRlZWM4OTliZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NI5u0w-9tQpMprZWcbItlhhrUysigWwFw3ZI964PXEU)

fantastik!

**Comment by arrrrny** [comment]
BEWARE!

On the latest version of the Zed Preview 0.160.0 , this trick setting  "enable_experimental_live_diffs": true
 does not work.

**Comment by lougreenwood** [comment]
Also, `enable_experimental_live_diffs` was V buggy yesterday and just garbled it's changes. IMO hold off on upgrading to 0.16.

Also, why is this closed @SomeoneToIgnore - AFAIU, `/workflow` is still missing without using a (currently buggy) feature flag...

**Comment by arrrrny** [comment]
I went back to using 0.158.2 It works like a charm. I like the UI as well. @zed-industries please keep that UI.

**Comment by graelo** [comment]
Hi, my use of zed also depends on the workflow feature, however, given we're living on preview and activating experimental flags, I think we should ensure our messages convey our expectations *and* some good level of support for the devs.

Zed devs, you rock, thank you so much for the great work.

**Comment by SomeoneToIgnore** [comment]
@lougreenwood Have you read [the PR above](https://github.com/zed-industries/zed/pull/19900)?

It states pristine clear that /workflow is removed, so this issue won't really make any sense in the future.
What comes after is apparently gated by `enable_experimental_live_diffs` and is not ready for the public.

Whatever happens next has to be asked from the author of the PR, I'm not really sure about that.

**Comment by lougreenwood** [comment]
Thanks @SomeoneToIgnore 🙇 - I didn't see that they explicitly mentioned removing `/workflow`... but I also see that in 0.159.5 (stable) that `workflow` is also gone and there is no mention of that in the release notes.

So maybe this PR is still valid until they update the release notes... but that's your call 👍

**Comment by SomeoneToIgnore** [comment]
Silent removals are very bad indeed, as you could have noticed in the same PR mentioned, I had to come into the comments and demand the release notes added there 😢 

Sorry for that, but unfortunately it's not my field and I have no clue what to do there, I am barely trying to keep up the tracker somewhat sane.

I suspect this might be related to https://github.com/zed-industries/zed/pull/19618 and the fact that `/workflow` was intended to be feature gated too, but someone did a bad job there.

I do not have a good solution to the current problem except waiting for further improvements on the `enable_experimental_live_diffs` thing or using an ancient version of Zed.

**Comment by masci** [comment]
@SomeoneToIgnore you might also want to edit the call out video on https://zed.dev/, starting around minute 4:00 `/workflow` is showcased as a killer feature of Zed (like it was) and newcomers won't have a clue about why it doesn't show up in their editors.

**Comment by arrrrny** [comment]
@masci think of it like an easter egg. it is not a bug. It is a feature. I am so much thankful to ZED team for /workflow. I am on version 158 since I cant do without it. It is 5x productivity for me. Keep up the great work.

**Comment by azachar** [comment]
Hi there, is there any alternative to this functionality?  I hate copy pasting, especially when a change requires to modify lot of files. Anyway, thanks a lot for great work!

**Comment by EdAyers** [comment]
I'm on Zed 0.183.11. You can get this functionality with `"enable_experimental_live_diffs": true,`, rather than typing in `/workflow`, a button appears at the bottom of the assistant pane saying "Suggest Edits".
