### ISSUE TITLE
Always use latest AI models

### ISSUE THREAD

**Issue by morgenthum** [zed-industries/zed#19676]
### Check for existing issues

- [X] Completed

### Describe the feature

When I choose a model, e.g. Claude 3.5 Sonnet, then it automatically sets `claude-3-5-sonnet-20240620`. Anthropic released new model versions (`claude-3-5-sonnet-20241022`). We could prevent updating the model identifiers by always using `claude-3-5-sonnet-latest`.

**Comment by morgenthum** [comment]
Btw it can easily be changed in the settings, but I think it would be cool if it's already preselected as soon as I change the model. I don't know any reason why someone would prefer an older model by default.

**Comment by notpeter** [comment]
Hi @morgenthum,

I actually merged a change to do exactly this yesterday:

- https://github.com/zed-industries/zed/pull/19615

I missed the merge window for yesterday's release but it'll be included in the Preview and Stable releases (v0.158.2 and v0.159.1-pre) which are currently building and will be available in ~30mins.

Thanks for reporting.

**Comment by morgenthum** [comment]
Oh sorry, I checked for duplicates, but obviously used the wrong keywords. But yeah, fine that it's already implemented 🥰
