### ISSUE TITLE
Autocomplete dialog for module import does not show labelDetails.description from LSP in Elixir

### ISSUE THREAD

**Issue by guidomb** [zed-industries/zed#19688]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In an Elixir file, when typing the name of module and then triggering autocomplete with cmd+space to show the list of possible modules to alias, the displayed list does not show the labelDetails.description from the CompletionItem responded by the LSP which shows the full module path which helps for disambiguation.

This is the LSP response in VSCode when doing cmd+space. As you can see in `labeDetails.description` field the alias that will be inserted is displayed.

```
Result: {
    "isIncomplete": true,
    "items": [
{
            "additionalTextEdits": [
                {
                    "range": {
                        "end": {
                            "character": 0,
                            "line": 1
                        },
                        "start": {
                            "character": 0,
                            "line": 1
                        }
                    },
                    "newText": "  alias ExAws.CredentialsIni.File\n"
                }
            ],
            "deprecated": false,
            "detail": "module",
            "documentation": {
                "kind": "markdown",
                "value": "File\n"
            },
            "filterText": "File",
            "insertText": "File",
            "insertTextFormat": 2,
            "insertTextMode": 2,
            "kind": 9,
            "label": "File",
            "labelDetails": {
                "description": "alias ExAws.CredentialsIni.File"
            },
            "sortText": "00000006",
            "tags": []
        },
        {
            "additionalTextEdits": [
                {
                    "range": {
                        "end": {
                            "character": 0,
                            "line": 1
                        },
                        "start": {
                            "character": 0,
                            "line": 1
                        }
                    },
                    "newText": "  alias StudioPhx.DataPointInput.File\n"
                }
            ],
            "deprecated": false,
            "detail": "struct",
            "documentation": {
                "kind": "markdown",
                "value": "File\n"
            },
            "filterText": "File",
            "insertText": "File",
            "insertTextFormat": 2,
            "insertTextMode": 2,
            "kind": 22,
            "label": "File",
            "labelDetails": {
                "description": "alias StudioPhx.DataPointInput.File",
                "detail": "struct"
            },
            "sortText": "00000007",
            "tags": []
        }
]
}
```

I'll be more than happy to collaborate and submit a PR. I have experience with Rust but good love to get some hints on how to navigate the source code to fix this issue. Thanks!

### Environment

Zed: v0.158.1 (Zed)
OS: macOS 14.7.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is how it looks in VSCode:
<img width="764" alt="Screenshot 2024-10-24 at 10 25 41 AM" src="https://github.com/user-attachments/assets/8dbcdc69-76a9-4277-9d71-a45a7ee71932">

This is how it looks in Zed:
<img width="397" alt="Screenshot 2024-10-24 at 10 24 44 AM" src="https://github.com/user-attachments/assets/40cb56a2-7920-4ea6-b3ea-40fa1113b2e1">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bangbangsheshotmedown** [comment]
My PR adds support for labelDetails, the elixir plugin will need to be updated to take advantage of it

https://github.com/zed-industries/zed/issues/14278
