### ISSUE TITLE
On MacOS: OPT+L becomes "ls" in the terminal instead of "@"?

### ISSUE THREAD

**Issue by Artur-Galstyan** [zed-industries/zed#19695]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Basically this:

https://github.com/user-attachments/assets/6fb57a75-5a04-4503-98c0-e2fe444334ad

I have the same issue on another MacBook as well.

### Environment

Zed: v0.158.1 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

Edit: forgot to mention: the "pipe" symbol has also a strange behaviour, that I don't even know how to describe. My keyboard uses the German layout.

**Comment by htor** [comment]
Have you set `terminal.option_as_meta = false` in `settings.json`?

**Comment by Artur-Galstyan** [comment]
No, I didn't, but adding this has fixed my problem! Thank you very much!
