### ISSUE TITLE
Close unpinned tabs action

### ISSUE THREAD

**Issue by oleasteo** [zed-industries/zed#19708]
### Check for existing issues

- [X] Completed

### Describe the feature

I propose new actions: `Pane: close unpinned items` and `Workspace: close unpinned tabs and panes`

This would provide the necessary control to define a "clean slate" state of open tabs and panes to recover to in between project tasks.

**Comment by CharlesChen0823** [comment]
ref #19593

**Comment by oleasteo** [comment]
Well, duplicate enough then #19560 
I really wonder why I missed that during search o.O Sorry.
