### ISSUE TITLE
Conflicting "accept partial inline completion" key binding, discards rest of line

### ISSUE THREAD

**Issue by alexkirsz** [zed-industries/zed#19715]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The current default key binding for `editor: accept partial inline completion` is `cmd+right`. On macOS, this conflicts with the default behavior of `cmd+right`, which is "jump to end of line". 

This means that the behavior of `cmd+right` depends entirely on whether there is a proposed code completion at the moment. So if the model has a bit of latency, you might end up accepting a completion you didn't mean to, because you were trying to jump to end of line. This behavior is very surprising and jarring coming from VS Code, which does not have this binding (or at least not on an existing binding).

Furthermore, accepting a partial inline completion discards whatever text was following it on the current line (see video). This can probably be classified as a separate bug. Let me know and I'll create another issue.

https://github.com/user-attachments/assets/6c6a2a8d-06f5-49c6-8bf9-5ab3ec55f9c4

**Expected behavior:**

1. On macOS, cmd+right is always "jump to end of line", and never anything else.
2. `editor: accept partial inline completion` does not discard the rest of the line.

**Actual behavior:**

1. Depending on whether there is a completion suggestion, cmd+right is either "jump to end of line" or "accept partial inline completion".
2. `editor: accept partial inline completion` discards all characters right of the cursor.

The key binding and action were implemented in https://github.com/zed-industries/zed/issues/8020

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
That is supposed to be fixed in https://github.com/zed-industries/zed/pull/20419 and I see not cmd-right in the default keymap anymore in all Zed versions including Stable:

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/e8d036e4-2ca9-4e39-a22c-41456fce6e65">

So closing this.


@boundless-forest , can you elaborate? 
What is your Zed version, what does default keymap show and if it's the same as on the screenshot, whether you have any custom keybindings?
