### ISSUE TITLE
Pane is stuck in between / is not filling out viewport

### ISSUE THREAD

**Issue by zweizeiler** [zed-industries/zed#19722]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

At some point when I closed the right pane (in split view) the left pane flipped into the middle. Since then it is stuck in this position and I can't get it back. Only if I open a second pane (split) the full viewport is filled out again.

https://github.com/user-attachments/assets/5cb3dcb8-8f0f-491f-80de-df90f063eb43

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
Hey @zweizeiler, I almost looks like the `workspace: toggle centered layout` was triggered. Can you run that action in the command prompt and see if your workspace returns to normal? It is clearly still a bug, just trying to understand the state it gets into here.

**Comment by zweizeiler** [comment]
Yea, I did have it toggled on – toggling it off fixed it! Sorry about that.
