### ISSUE TITLE
editor::Rewrap not working for chinese text

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#19733]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I execute the `editor::Rewrap` command on Chinese paragraphs, the lines are not aligned according to the configured "preferred_line_length" setting of 80 characters.
 

### Environment

Zed: v0.160.0 (Zed Dev 0173479d18e2526c1f9c8b25ac94ec66b992a2b2)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Before:
![image](https://github.com/user-attachments/assets/ef1a4708-c047-4949-aa65-60f7d16c4807)

After `editor::Rewrap`:
![image](https://github.com/user-attachments/assets/e2315055-32a8-49df-9995-99a863fc85b3)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by opsnull** [comment]
related issue：https://github.com/zed-industries/zed/issues/19940

**Comment by wbbradley** [comment]
Thanks @opsnull for reporting this issue. The [fix](https://github.com/zed-industries/zed/pull/20218) is not a complete fix for complex scripts or Han scripts or mixed scripts wrapping in general, but hopefully it is an improvement from where we were.
