### ISSUE TITLE
can't input single-letter key bindings character when rename in project panel

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#19736]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using single-letter key bindings in the project panel, these single letters cannot be entered as file names when performing rename operations.

for example, I'm using blow keymap settings, I can't input o/n/p when renaming.

```json
  {
    "context": "ProjectPanel", 
    "bindings": {
      "escape": "menu::Cancel",
      "tab": "project_panel::OpenPermanent", 
      "space": "project_panel::OpenPermanent",

      "o": "project_panel::OpenPermanent", 
      "n": "menu::SelectNext",
      "p": "menu::SelectPrev",
      "^": "project_panel::SelectParent",
    }
```

### Environment

Zed: v0.160.0 (Zed Dev 0173479d18e2526c1f9c8b25ac94ec66b992a2b2)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
modify `"context": "ProjectPanel && not_editing", `

**Comment by opsnull** [comment]
@CharlesChen0823 that working, thanks!
