### ISSUE TITLE
package-version-server: Autocomplete package.json npm versions

### ISSUE THREAD

**Issue by oleasteo** [zed-industries/zed#19777]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great if package versions in package.json `dependencies` & `*Dependencies` could be autocompleted.

In other IDEs, this has helped tremendously with keeping upgrades easy to do, especially selective ones.

It should ignore SemVer range prefixes, for example `^2.[autocomplete]` should work as one could expect.

**Comment by osiewicz** [comment]
A new version of package-version-server has been released (0.0.5), but there's a bug in how we currently process the completions which makes the completions go away after you type in `.`. That's fixed in Nightly now, so we'll have to wait for it to hit stable.
