### ISSUE TITLE
In vim mode, capturing a single paragraph with `ap` sometimes selects the following paragraph as well

### ISSUE THREAD

**Issue by mobismanino** [zed-industries/zed#19778]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The smallest example i managed to generate which reliable allows to reproduce this issue is this:

```
func TestMustLoad(t *testing.T) {
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if gotLogDebug != tt.wantLogDebug {
				t.Errorf("MustLoad() gotLogDebug = %v, want %v", gotLogDebug, tt.wantLogDebug)
			}
		})
	}
}

func TestAsBool(t *testing.T) {
}
```

When the cursor is in the first paragraph, doing `vap` incorrectly captures both paragraphs.

If the inner-most `{}` block is removed from this example, then `vap` correctly catches only the first paragraph, e.g.:

```
func TestMustLoad(t *testing.T) {
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
		})
	}
}

func TestAsBool(t *testing.T) {
}
``` 

Correct behaviour occurs even if only the content inside the quotations is removed from the first example, e.g.:

```
func TestMustLoad(t *testing.T) {
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if gotLogDebug != tt.wantLogDebug {
				t.Errorf("", gotLogDebug, tt.wantLogDebug)
			}
		})
	}
}

func TestAsBool(t *testing.T) {
}
```

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="705" alt="Screenshot 2024-10-26 at 07 48 12" src="https://github.com/user-attachments/assets/ff1cec78-d2e3-4063-9ef9-13a07ef44876">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment]
@mobismanino I cannot reproduce this by copying your example into Zed. Could you please upload a file that reproduces the problem (in case there's some character that's been stripped out by the round-trip through Github).

**Comment by mobismanino** [comment]
Indeed i cannot reproduce it either at the moment. But i have ran into more instances of this exact behavior in the meantime (i thought at the time that more examples were unnecessary). I'll keep an eye on it some more, and then i'll follow up either in this issue or i'll open a new one if you decide to close this.

**Comment by mobismanino** [comment]
[load_test.txt](https://github.com/user-attachments/files/17597522/load_test.txt)

Never mind! I ran into it in just a slightly different spot now, so here is the file.

This is a go file, but the extension is changed to `.txt` only because github doesn't let me upload `.go` files.

If i place the cursor on the paragraph at line 40, `vap` correctly selects the single paragraph 40-47. If i place it at 48, it incorrectly selects two paragraphs 48-61. Furthermore, it correctly selects a single paragraph for all paragraphs before line 40, and it incorrectly selects two paragraphs for all paragraphs after line 48. So there's like a point (or a line) after which it starts behaving in this incorrect manner.

The file extension or language mode seems to not matter. I tested this now both when it has a `.go` extension and a `.txt` extension, and when i change the language mode to Go within the `txt` file; the behavior is consistent in all 3 of those cases. My regular `vim` from the terminal correctly selects a single paragraph for all paragraphs across the whole file (indicating that there isn't a leftover character that connects the lines).

I have also quit zed and started it again to make sure it's not something that happens during the runtime, and disabled all my installed extensions, but the bug is still persistent and reproducible with the code in that file.

It is also quite interesting that i (still) cannot reproduce the bug with that first example that i posted, but i can consistently reproduce it with the example in this newly uploaded file.

My minor version of zed is upgraded now though:

```
Zed: v0.159.5 (Zed)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64
```

**Comment by mobismanino** [comment]
Found the cause of the issue! 

The reason the previous example wasn't reproducing the bug for me either now, is because i changed my preferred line length from 80 to 100 in the meantime.

This bug is caused when there is a line that exceeds the `preferred_line_length` and when i use `"soft_wrap":"bounded"`. When these two things are true, then `vap` incorrectly selects two paragraphs instead of one for every paragraph after the offending line for the rest of the file.

**Comment by ConradIrwin** [comment]
Nice find! Can reproduce, now why?!

**Comment by mobismanino** [comment]
<img width="922" alt="Screenshot 2024-11-05 at 10 46 35" src="https://github.com/user-attachments/assets/2a2c7a5d-9609-4ded-9196-702c67cf66da">

Another hopefully helpful discovery is that if i have two lines that exceed the preferred_line_length, then `vap` selects 3 paragraphs. It seems to behave like it thinks an exceeding line adds -1 to the number of empty lines.
