### ISSUE TITLE
Zed Preview 0.159.1 updates itself to 0.158.2 stable

### ISSUE THREAD

**Issue by morya** [zed-industries/zed#19780]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed Preview 0.159.1 updates itself to 0.158.2 stable

### Environment

Zed Preview 0.159.1 updates itself to 0.158.2 stable

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed Preview 0.159.1 updates itself to 0.158.2 stable

### If applicable, attach your Zed.log file to this issue.

Zed Preview 0.159.1 updates itself to 0.158.2 stable

**Comment by notpeter** [comment]
You've said the same thing five times.
But you've managed to provide no meaningful context.

What platform are you on? ('copy system specs to clipboard' as requested in the template) 
How did you install Zed? ("steps to reproduce" in the template)
How are you launching Zed? ("steps to reproduce" in the template)

**Comment by morya** [comment]
> You've said the same thing five times. But you've managed to provide no meaningful context.
> 
> What platform are you on? ('copy system specs to clipboard' as requested in the template) How did you install Zed? ("steps to reproduce" in the template) How did you update Zed? ("steps to reproduce" in the template) How are you launching Zed? ("steps to reproduce" in the template) Do you have both Zed Preview and Zed Stable installed but accidentally are launching one instead of the other?

- platform: macos 15.0.1
- install method: deleted old 0.158.2, download and installed zed Preview 0.159.1
- how to update zed: did nothing, auto updated
- how are you launching: just normally started ( with sock5 proxy setting enabled)
- no, old version is deleted

**Comment by morya** [comment]
I will install zed preview again, and try it
