### ISSUE TITLE
Snippets priority in code completion

### ISSUE THREAD

**Issue by leeratyou** [zed-industries/zed#19786]
### Check for existing issues

- [X] Completed

### Describe the feature

How to set snippets priority in code completion popup be first?
e.g. "r" for "return " on screenshot

Or if there is not such feature - it is feature request 

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/3fb949e2-56dc-4ada-a275-164641f6aecb)

**Comment by SomeoneToIgnore** [comment]
> Exact matches should precede the inexact matches.

Will you be able to compile https://github.com/zed-industries/zed/tree/kb/completion-matches and check if that makes things better for you?

**Comment by 80avin** [comment]
@SomeoneToIgnore Yes, it helps. This was the first thing I myself tried.

However, I'm thinking if in the case of Strong Match, we sort by match score and in case of weak match, we sort alphabetically, that will also solve the asked issue and probably be more meaningful to the user.

**Comment by SomeoneToIgnore** [comment]
Sounds like you know what to do better than me — I am somewhat blind and lack a testcase which shows how things improve.

Would you mind creating a PR with the test like this? 
Or, at least, I'd appreciate a good example which I can try and reproduce things.

**Comment by 80avin** [comment]
Yes sure.
I already created test cases and trying things locally. Because of limited time and knowledge of Rust/repo, I'll be taking some time.

In few days, I'll share a finished PR.

**Comment by rengler33** [comment]
Very much looking forward to this option. Here's another example if it helps with a common elixir snippet: 
<img width="311" alt="image" src="https://github.com/user-attachments/assets/7fc293dc-c6fb-4b0e-91bb-4ca2fbcef904">

**Comment by smitbarmase** [comment]
We added a new setting that will allow you to change this behavior: https://github.com/zed-industries/zed/pull/29429

**Comment by smitbarmase** [comment]
By default snippet sort order is `inline`, if you want it as top you can:

```json
 "snippet_sort_order": "top"
```
