### ISSUE TITLE
Zed in mise-en-place don't work

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#19790]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I add the posibility to add zed to mise tool but for now it don't work because of this error

yodatak@pcfixamd.home ~ [1]> /var/home/yodatak/.local/share/mise/installs/ubi-zed-industries-zed/0.158.2/bin/zed 
Error: Bundle detection

Caused by:
    could not find any of: ../libexec/zed-editor, ../lib/zed/zed-editor, ./zed
    
    
 see PR here 
https://github.com/jdx/mise/pull/2822

I add 
this in my mise config `/var/home/yodatak/.config/mise/config.toml`

```toml
"ubi:zed-industries/zed" = {version="latest" }
```

### Environment

bazzite 41 and mise --version
2024.10.10 linux-x64 (3029d46 2024-10-25) 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by yodatak** [comment]
Maybe linked to this 
https://github.com/zed-industries/zed/blob/03a1c8d2b8c1e1a623702b70796d1c5b1d265aff/crates/cli/src/main.rs#L112
But i don't know

**Comment by yodatak** [comment]
here my path that it creed by mise 
PATH=/home/yodatak/.local/share/mise/installs/meson/latest/bin:/home/yodatak/.local/share/mise/installs/shellcheck/latest/bin:/home/yodatak/.local/share/mise/installs/go/1.23.2/bin:/home/yodatak/.local/share/mise/installs/go/1.23.2/go/bin:/home/yodatak/.local/share/mise/installs/mold/latest/bin:/home/yodatak/.local/share/mise/installs/cargo-make/latest/bin:/home/yodatak/.local/share/mise/installs/rust/latest/bin:/home/yodatak/.local/share/mise/installs/rust-analyzer/2024-10-21/bin:/home/yodatak/.local/share/mise/installs/argocd/latest/bin:/home/yodatak/.local/share/mise/installs/flux2/latest/bin:/home/yodatak/.local/share/mise/installs/helm/latest/bin:/home/yodatak/.local/share/mise/installs/mc/2024-10-08T09-37-26Z/bin:/home/yodatak/.local/share/mise/installs/k3d/latest/bin:/home/yodatak/.local/share/mise/installs/k9s/latest/bin:/home/yodatak/.local/share/mise/installs/krew/latest/bin:/home/yodatak/.local/share/mise/installs/kubectl/latest/bin:/home/yodatak/.local/share/mise/installs/kubectx/latest/bin:/home/yodatak/.local/share/mise/installs/kubeshark/latest/bin:/home/yodatak/.local/share/mise/installs/kubespy/latest/bin:/home/yodatak/.local/share/mise/installs/kustomize/latest/bin:/home/yodatak/.local/share/mise/installs/sops/latest/bin:/home/yodatak/.local/share/mise/installs/stern/latest/bin:/home/yodatak/.local/share/mise/installs/weave-gitops/latest/bin:/home/yodatak/.local/share/mise/installs/awscli/latest/bin:/home/yodatak/.local/share/mise/installs/crane/latest/bin:/home/yodatak/.local/share/mise/installs/nerdctl/latest/bin:/home/yodatak/.local/share/mise/installs/buildpack/latest/bin:/home/yodatak/.local/share/mise/installs/packer/latest/bin:/home/yodatak/.local/share/mise/installs/choose/latest/bin:/home/yodatak/.local/share/mise/installs/duf/latest/bin:/home/yodatak/.local/share/mise/installs/exa/latest/bin:/home/yodatak/.local/share/mise/installs/fd/latest/bin:/home/yodatak/.local/share/mise/installs/jq/latest/bin:/home/yodatak/.local/share/mise/installs/jx/latest/bin:/home/yodatak/.local/share/mise/installs/ripgrep/latest/bin:/home/yodatak/.local/share/mise/installs/ubi-burnt-sushi-ripgrep/latest/bin:/home/yodatak/.local/share/mise/installs/cargo-binstall/latest/bin:/home/yodatak/.local/share/mise/installs/mkcert/latest/bin:/home/yodatak/.local/share/mise/installs/yq/latest/bin:/home/yodatak/.local/share/mise/installs/vhs/latest/bin:/home/yodatak/.local/share/mise/installs/bitwarden/latest/bin:/home/yodatak/.local/share/mise/installs/starship/latest/bin:/home/yodatak/.local/share/mise/installs/lazygit/latest/bin:/home/yodatak/.local/share/mise/installs/marp-cli/latest/bin:/home/yodatak/.local/share/mise/installs/pandoc/latest/bin:/home/yodatak/.local/share/mise/installs/neovim/latest/bin:/home/yodatak/.local/share/mise/installs/node/latest/bin:/home/yodatak/.local/share/mise/installs/pnpm/latest/bin:/home/yodatak/.local/share/mise/installs/ollama/latest/bin:/home/yodatak/.local/share/mise/installs/ubi-zed-industries-zed/latest/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/yodatak/.local/bin:/usr/condabin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin

**Comment by notpeter** [comment]
Apologies for my ignorance, but [mise-en-place](https://mise.jdx.dev/) appears to be a combined tool that manages tool versions/packages, environment variables and tasks.

Are you trying manage your Zed version via mise-en-place?

Or are you trying to have Zed to add support mise-en-place in some way?

**Comment by notpeter** [comment]
Is there a specific change that you are requesting the packaging/installation of Zed to change to accommodate mise-en-place?  We currently ship a tarball e.g. [zed-linux-x86_64.tar.gz for v0.158.2](https://github.com/zed-industries/zed/releases/download/v0.158.2/zed-linux-x86_64.tar.gz) which we extract to `~/.local/zed.app/` by default for Zed Stable (or `~/.local/zed-preview.app` for Zed Preview).  This has the following contents:
```
peter@think21:~/.local/zed-preview.app$ find -type f
./lib/libz.so.1
./lib/libzstd.so.1
./lib/libxcb-xkb.so.1
./lib/libXau.so.6
./lib/libxkbcommon-x11.so.0
./lib/libasound.so.2
./lib/libXdmcp.so.6
./lib/libbsd.so.0
./lib/libssl.so.1.1
./lib/libcrypto.so.1.1
./lib/libxkbcommon.so.0
./lib/libxcb.so.1
./libexec/zed-editor
./bin/zed
./share/applications/zed-preview.desktop
./share/icons/hicolor/512x512/apps/zed.png
./share/icons/hicolor/1024x1024/apps/zed.png
./licenses.md
```

You should be able to safely extract this to whatever directory you'd like. So if you wanted to support multiple versions of Zed being installed you could install them to `/usr/local/zed/v0.159.2-pre/zed-preview.app/` or just `/usr/local/zed/v0.159.2-pre/` with some minimal tar-fu.  If you're running Zed this way I suggest you add `"auto_update": false,` to your settings.json as our AutoUpdate will likely fail.

Given that there doesn't appear to be a specific request here I'm going to close.  Happy to reopen if you comment with more details about what you're asking for.
