### ISSUE TITLE
tab_switcher::Toggle `select_last: true` doesn't work if remapped

### ISSUE THREAD

**Issue by aleclarson** [zed-industries/zed#19798]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to use Alt+w to switch tabs. Here's the keymap I'm trying:

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "alt-w": "tab_switcher::Toggle",
      "shift-alt-w": ["tab_switcher::Toggle", { "select_last": true }]
    }
  }
]
```

The problem is that Shift+Alt+w does not select the previously selected tab when pressed. Instead, it behaves the exact same as Alt+w.

The default key bindings work as expected, where Ctrl+Tab moves top to bottom and Ctrl+Shift+Tab will move the opposite direction in the list.

Note that Shift+Alt+w *does* open the tab switcher at the bottom, but still moves down instead of up on repeated keypresses.

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 14.4.1
Memory: 20 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment]
Hey @aleclarson, can you test this again using the latest stable or preview? These bindings currently work for me.
