### ISSUE TITLE
Open File at Specific Line Number

### ISSUE THREAD

**Issue by jorauch** [zed-industries/zed#19799]
### Check for existing issues

- [X] Completed

## Summary
I would like to request a feature that allows users to open a file at a specific line number directly from the command line, similar to the functionality available in Vim.

## Description
In Vim, it is possible to open a file at a specific line number using the following syntax:
```
vim +<LineNumberHere> fileName
```
This feature is incredibly useful for quickly navigating to a specific part of a file, especially when dealing with large codebases or log files.

## Proposed Implementation
I propose adding a similar feature to Zed, where users can open a file at a specific line number using a command line argument. For example:
```
zed +<LineNumberHere> fileName
```
When this command is executed, Zed should open the specified file and automatically navigate to the given line number.

## Benefits
- Improved efficiency and productivity for developers and users who need to quickly access specific lines in files.
- Enhanced usability for those transitioning from Vim or other editors with similar functionality.
- Streamlined workflow for debugging and code review processes.

**Comment by GetOutOfMyBakery** [comment]
This looks to already be available, albeit with a different formatting than you're used to:

``` shell
zed --help
Usage: zed [OPTIONS] [PATHS_WITH_POSITION]...

Arguments:
  [PATHS_WITH_POSITION]...
          A sequence of space-separated paths that you want to open.

          Use `path:line:row` syntax to open a file at a specific location. Non-existing paths and directories will ignore `:line:row` suffix.
```

Example, line 3, row 20:
``` shell
zed my/file/path:3:20
```

**Comment by GetOutOfMyBakery** [comment]
This looks to already be available, albeit with a different format than you're familiar with:
``` shell
zed --help
Usage: zed [OPTIONS] [PATHS_WITH_POSITION]...

Arguments:
  [PATHS_WITH_POSITION]...
          A sequence of space-separated paths that you want to open.

          Use `path:line:row` syntax to open a file at a specific location. Non-existing paths and directories will ignore `:line:row` suffix.
```

Example, line 3, row 20:
``` shell
zed path/to/file:3:20
```
