### ISSUE TITLE
Last item in project panel hidden under scrollbar

### ISSUE THREAD

**Issue by katry0** [zed-industries/zed#19808]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When project tree contains enough items to reach bottom of the panel last item is overlaid with horizontal scrollbar.

### Environment

Zed: v0.158.2
OS: Archlinux (6.6.58-1-lts)
Memory: 64 GiB
Architecture: amd64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Snímek obrazovky z 2024-10-27 17-38-13](https://github.com/user-attachments/assets/b7e065bc-89bf-4144-8784-994ad3e2e477)

**Comment by SomeoneToIgnore** [comment]
This got fixed in https://github.com/zed-industries/zed/pull/19403 and should arrive to Stable next Wednesday as already available in Preview.
Will close it optimistically.
