### ISSUE TITLE
zed main thread hang when view large json file(955KB) or add big directory with lots of files to workspace

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#19817]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![图片](https://github.com/user-attachments/assets/4e25e669-aaa5-49a1-9528-2955fbef8cbb)

here is Macos Instrument trace file：
https://drive.google.com/file/d/1lSFSBOdGyrZaSozXLasCmhYbp8cXL4A5/view?usp=sharing

Another issue is that when adding a directory containing a large number of files to the workspace, Zed immediately scans all files under that directory, and the debug log shows that this causes Zed to hang.

### Environment

Zed: v0.160.0 (Zed Dev ffe36c9beb40caf128535a536619b12e6153aa6a)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

view large json file hang log：[debug-log-json-hang.txt](https://github.com/user-attachments/files/17538405/debug-log-json-hang.txt)

add big directory to workspace hang log：[add-directory-to-workspace-hang-log.txt](https://github.com/user-attachments/files/17539837/add-directory-to-workspace-hang-log.txt)

**Comment by osiewicz** [comment]
Could you provide a precise repro? Instruments trace is great, but it would be great to have an actual file.
Going off of the trace the FoldMap is at fault.

**Comment by osiewicz** [comment]
According to @SomeoneToIgnore this issue is related to outline panel, which also shows up in traces you've provided.

**Comment by opsnull** [comment]
yes，it is related to outline panel.

I noticed that when I place the cursor on longer JSON string lines, the probability of hanging/freezing increases

![Oct-28-2024 22-13-19](https://github.com/user-attachments/assets/ceda2bf4-2172-46bb-b7e0-6948d8ecad25)

![图片](https://github.com/user-attachments/assets/d37590d7-0fcd-42ff-aacc-09a913bab399)

test json file：
https://drive.google.com/file/d/1ULWOYjK2vLYlKXGqH3w-699UOtzv5pLv/view?usp=sharing

Instrument file：
https://drive.google.com/file/d/1w0zYGsq4SCR4JD-iE16nW5fpEz3niuOW/view?usp=sharing

**Comment by SomeoneToIgnore** [comment]
With https://github.com/zed-industries/zed/pull/20031 I see no outline panel in the traces and the caret movements seem to be smooth again on that file attached.

I will close this optimistically with the PR merge, but we can reopen if something else persists still (I see no such possibility though).

Thanks a lot for the trace and the file, that helped immensely to move this!

**Comment by opsnull** [comment]
You're welcome. Glad to hear this helping，^_^
