### ISSUE TITLE
[BUG] Terminal not showing zsh characters correctly

### ISSUE THREAD

**Issue by alessandromrc** [zed-industries/zed#19833]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that while using ZSH within the Zed terminal it causes the rendering of some characters to be garbled.

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="946" alt="Screenshot 2024-10-28 at 16 05 10" src="https://github.com/user-attachments/assets/ad64695f-9e88-483b-96ec-e38c105fe728">

**Comment by SomeoneToIgnore** [comment]
![image](https://github.com/user-attachments/assets/d5e45d5a-16ef-4b29-be50-b87b0dd9900d)

I use zsh and have not spotted any issues with rich text so far, what is this prompt and which symbols are not displayed?
Could it be the font that lacks them?

**Comment by alessandromrc** [comment]
> ![image](https://private-user-images.githubusercontent.com/2690773/380772525-d5e45d5a-16ef-4b29-be50-b87b0dd9900d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTU3OTAsIm5iZiI6MTczMDE1NTQ5MCwicGF0aCI6Ii8yNjkwNzczLzM4MDc3MjUyNS1kNWU0NWQ1YS0xNmVmLTRiMjktYmU1MC1iODdiMGRkOTkwMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMjI0NDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNlYWEwZGIyMGNjNGZhZjhlNjI5ZTcxNWFmYzNkNmZlMTcwMGY0NDYwZDM4MWIxNjA4OWZlYzllNjQ0ZDQyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.isDvT7hX7PiRX0bOmduNFTPh_vvwWseB_WpnMv_hDnc)
> 
> I use zsh and have not spotted any issues with rich text so far, what is this prompt and which symbols are not displayed? Could it be the font that lacks them?

I am not quite sure about which font zed uses by default for the terminal... I don't remember changing it at all (if you have any idea on where I can look that up I can check it)

I ran the same commands as you and the output is this one:

```
❯ echo $ZSH_VERSION
5.9
❯ echo -e "\u2387 \u27A6 \u2442 \u2B60 \u2B61"
⎇ ➦ ⑂ ⭠ ⭡
```

As you can see those characters aren't garbled at all like in my own case.

![image](https://github.com/user-attachments/assets/accbdf46-74d8-4a9b-a617-e9765e15f506)

Maybe my installation got corrupted? (I have Zed installed for quite some time now)

This is the correct output on iTerm2:

![image](https://github.com/user-attachments/assets/fc42f68a-bf63-4ffd-a91b-4bd8129ec4a2)

**Comment by SomeoneToIgnore** [comment]
I don't think your local install is broken then, and the terminal defaults without any extra changes should be the "IBM Plex Mono" (it's Zed Plex Mono actually, with extra ligatures on top) which should have many glyphs in it (as you can see, those extra symbols from my comment work for you too).

Your last screenshot seems to capture something else then, can you which symbols are displayed in that `Quanta` case properly in iTerm? And you can copy-paste them here, right? That's what's needed.

If you are interested, you can also try https://github.com/alacritty/alacritty (as that's what Zed uses) and see whether Zed-less, standalone terminal emulator is working or not.

**Comment by alessandromrc** [comment]
> I don't think your local install is broken then, and the terminal defaults without any extra changes should be the "IBM Plex Mono" (it's Zed Plex Mono actually, with extra ligatures on top) which should have many glyphs in it (as you can see, those extra symbols from my comment work for you too).
> 
> Your last screenshot seems to capture something else then, can you show which symbols are displayed in that `Quanta` case properly in iTerm? And you can copy-paste them here, right? That's what's needed.
> 
> If you are interested, you can also try https://github.com/alacritty/alacritty (as that's what Zed uses) and see whether Zed-less, standalone terminal emulator is working or not.

I confirm that even Alacritty has the same issue when standalone, when using iTerm2 it works fine... 

You were correct that I didn't "cd" into the repository but I can notice it being perfectly fine only on iTerm like as you can see here:

![image](https://github.com/user-attachments/assets/7b9fa290-9f70-4461-8d83-c7b86b835b62)


`
    ~/Doc/GitHub/Quanta  on   main +1 !4 ?2                                                               ✔ `

Obviously the characters cannot be seen correctly when pasting the terminal output here on GitHub.

**Comment by SomeoneToIgnore** [comment]
Thank you for rechecking.

The only similar thing I see is https://github.com/alacritty/alacritty/issues/8050 but on the related screenshots I can see the corresponding glyphs being shown.

So _maybe_ it's Alacritty's issue, but we need to ensure the font is the same in iTerm and in Alacritty before claiming that.

**Comment by alessandromrc** [comment]
> Thank you for rechecking.
> 
> The only similar thing I see is [alacritty/alacritty#8050](https://github.com/alacritty/alacritty/issues/8050) but on the related screenshots I can see the corresponding glyphs being shown.
> 
> So _maybe_ it's Alacritty's issue, but we need to ensure the font is the same in iTerm and in Alacritty before claiming that.

iTerm2 is using "MesloLGS NF" as font... not sure on how to check for Alacritty... I see everyone mentioning custom configs, which I don't have at all.

**Comment by alessandromrc** [comment]
> Yeah, I have no clue how to configure fonts in standalone Alacritty (I'd guess some `~/foo/alacritty.conf`-like file has to be created and docs can be explored for more).
> 
> In Zed, you can try altering
> 
> https://github.com/zed-industries/zed/blob/273cb1921f999e158a9de75ac8bb9fc5a9615c18/assets/settings/default.json#L785
> 
> by placing the
> 
> ```json
> "terminal": {
>   "font_family": "MesloLGS NF",
> }
> ```
> 
> But for that, you have that font to be installed in the system and hope that Zed takes the one correctly (it should, but I'm not sure whether I've used the right string in this example).

yep, can confirm that overriding the font does the job fine... I wonder if other people might have the same issue in the future... I guess they will just hopefully land over this issue.

Thanks!
