### ISSUE TITLE
Can't completelly unsinstall extensions on MacOS

### ISSUE THREAD

**Issue by guinunez** [zed-industries/zed#19849]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I uninstall the HTML extension, after restarting it goes back again

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 14.6.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxdeviant** [comment]
The HTML extension is auto-installed by default.

https://github.com/zed-industries/zed/blob/80f89059aabade8f83c35a371ba1cc3a713a5cd6/assets/settings/default.json#L822-L828

If you don't want it installed anymore, you can add the following to your settings:

```json
  "auto_install_extensions": {
    "html": false
  },
```

Then once you uninstall it it won't come back.

**Comment by JosephTLyons** [comment]
Since we do provide a way to opt out of this, I'm going to close this issue. We likely just need to document this setting in some discoverable way.
