### ISSUE TITLE
Stop jumping in the left dock file explorer when viewing a file

### ISSUE THREAD

**Issue by PonasKovas** [zed-industries/zed#19857]
### Check for existing issues

- [X] Completed

### Describe the feature

For me it is incredibly annoying when I switch the opened file tab or close a file and then the file explorer on the left dock immediately jumps to show the next file that opens in the tab. In my huge code base I always have to scroll and look for the files that I'm working on again.

Could you please remove this functionality or at least add a setting to disable it?

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/ffe36c9beb40caf128535a536619b12e6153aa6a/assets/settings/default.json#L351-L354

Putting this setting with `false` value in your local settings should help.
