### ISSUE TITLE
run task failed：IOError: Failed to spawn command '/opt/homebrew/bin/bash': Not a directory 

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#19873]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm editing `/Users/alizj/.config/zed/keymap.json` file, and then run `lazygit` task defined as:
``` json
  {
    "label": "Lazygit",
    "command": "lazygit",
    "args": [],
    "env": {},
    "use_new_terminal": true,
    "allow_concurrent_runs": false
  }
```

zed UI don't show terminal panel, and print Error log:
``` text
[2024-10-29T14:00:49+08:00 ERROR terminal_view] Working directory: /Users/alizj/.config/zed/keymap.json Shell command: `/opt/homebrew/bin/bash -i -c lazygit`, IOError: Failed to spawn command '/opt/homebrew/bin/bash': Not a directory (os error 20)

Caused by:
    Failed to spawn command '/opt/homebrew/bin/bash': Not a directory (os error 20)

```

The `Working directory: /Users/alizj/.config/zed/keymap.json` is wrong.

### Environment

Zed: v0.160.0 (Zed Dev 85ff03cde047d4fd77931252ef4f31e141d3ce49)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Looks like we're detecting your current shell as '/opt/homebrew/bin/bash' for some reason. (there are no references in to code to `/opt/homebrew` so this is something funky with your env).

Do you perhaps have an old symlink to homebrew bash lying around?

```
echo $SHELL
dscl . -read /Users/$USER UserShell
which -a bash
ls -l /usr/local/bin/bash
```

As a workaround, you can specify a valid `shell` on your [task definition](https://zed.dev/docs/tasks).

**Comment by opsnull** [comment]
@notpeter 

``` sh
zj@a:~$ echo $SHELL
/opt/homebrew/bin/bash
zj@a:~$ dscl . -read /Users/$USER UserShell
UserShell: /opt/homebrew/bin/bash
zj@a:~$ which -a bash
/opt/homebrew/bin/bash
/bin/bash
/opt/homebrew/bin/bash
zj@a:~$ ls -l /usr/local/bin/bash
ls: cannot access '/usr/local/bin/bash': No such file or directory
zj@a:~$ ls -l /opt/homebrew/bin/bash
lrwxr-xr-x 1 alizj 30  3 28  2024 /opt/homebrew/bin/bash -> ../Cellar/bash/5.2.26/bin/bash*
```

**Comment by opsnull** [comment]
same issue：https://github.com/zed-industries/zed/issues/20060

**Comment by yitzhakbg** [comment]
Here's the same problem on Mac: 
ls -l `which zed`
lrwxr-xr-x  1 root  wheel  40 Dec  9 20:05 /usr/local/bin/zed -> /Applications/Zed.app/Contents/MacOS/**cli**

Solved it by changing to:
lrwxr-xr-x  1 root  wheel  40 Dec  9 20:05 /usr/local/bin/zed -> /Applications/Zed.app/Contents/MacOS/**zed**
