### ISSUE TITLE
Scroll bar should be upmost in project pane

### ISSUE THREAD

**Issue by csmoe** [zed-industries/zed#19875]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/23ffbe0b-a69a-4b5d-abc2-a3ec308fcde3)

### Environment

Zed: v0.159.2 (Zed Preview)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

**Comment by BLANKatGITHUB** [comment]
I would like to work on this. 
It's my first time contributing to zed I would appreciate little help.

**Comment by CLoaKY233** [comment]
> I would like to work on this. It's my first time contributing to zed I would appreciate little help.

I wish to join in, any way I can help?

**Comment by HarshNarayanJha** [comment]
I don't understand the issue. Isn't scrollbar already on the top? It is it's opacity that makes the blue outline visible
