### ISSUE TITLE
Copy Relative Path on mouse right-click is copying current buffer relative path instead of click tab

### ISSUE THREAD

**Issue by hfvmarques** [zed-industries/zed#19915]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you have an opened buffer, and right clicks another ones tab looking for its relative path, the copied path is not of the one that you clicked, instead it copies the current buffer relative path.

The same does NOT occur when copying complete file path. When copying complete file path, it copies to clipboard the path of the clicked tab.

### Environment

Zed: v0.157.4 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 30.7 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.0.9-0ubuntu0.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/e88d3f9b-faca-4d17-adfb-8bd97c5aab82)

Copied relative path: `.../taskers/subscriptions_score.rb`

![image](https://github.com/user-attachments/assets/e2477c99-9b6b-4c1a-83f1-242e137c3c4f)

Copied path: `.../tasker_history/discount_fidelity.rb`

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
> Zed: v0.157.4 (Zed)

This version is quite old, and the issue was fixed v0.158.0 with https://github.com/zed-industries/zed/pull/19206
