### ISSUE TITLE
Windows build does not compile due to a dependency with a too long path

### ISSUE THREAD

**Issue by avdg** [zed-industries/zed#19929]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was attempting to compile zed on windows on main (commit fb97e462dec8238c02059e78bf7e00b3ca44dbf7) but the build breaks with the following error:
![Screenshot 2024-10-29 214933](https://github.com/user-attachments/assets/b14d61bf-7492-4462-afba-770c6f311a9a)

After digging further down, the first breaking commit seems to be cdddb4d3603691406ac846f97bc66699c3dc093a. The commit before (03bd95405b3398691c64d16b02783b6dce214c18) did not had issues

### Environment

Windows

**Comment by osiewicz** [comment]
Yup, that same commit also enabled `core.longpaths` for git: [see here](https://github.com/zed-industries/zed/commit/cdddb4d3603691406ac846f97bc66699c3dc093a#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR196-R197).

Feel free to reopen this issue if doing that does not fix the problem for you.
