### ISSUE TITLE
on macOS provide "normal" terminal usage as default. i.e. default to option_as_meta to false 

### ISSUE THREAD

**Issue by internettechnik** [zed-industries/zed#19942]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Terminal NOT USABLE. 

Without configuration changes, users cannot enter backslash or pipe symbols in the terminal. 

### Environment

tested on macos

### If applicable, add mockups / screenshots to help explain present your vision of the feature

  "terminal": {
    "option_as_meta": false
  }

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
It is set to `false` by default:

https://github.com/zed-industries/zed/blob/9ac84345bd9c2048484fdef11121b0a7dbd3aa08/assets/settings/default.json#L740

so this issue is NOT ACTIONABLE without further information.
Start with the version number and elaborate more.

**Comment by notpeter** [comment]
This default was changed in Preview last week and in Stable today:
- https://github.com/zed-industries/zed/pull/19364
<img width="892" alt="Screenshot 2024-10-30 at 16 35 10" src="https://github.com/user-attachments/assets/68b93471-674d-4dd9-821a-a8098e49165d">
