### ISSUE TITLE
remote-development doesn't work with fish

### ISSUE THREAD

**Issue by bbigras** [zed-industries/zed#19976]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
zeditor --foreground ssh://localhost/~/dev/something
[2024-10-30T15:15:22-04:00 ERROR recent_projects::ssh_connections] Failed to open project: Failed to download server binary

Caused by:
    failed to run command: fish: Missing end to balance this if statement
                if command -v wget >/dev/null 2>&1; then
```

It seems fine when using ssh with another host (that is using zsh).

### Environment

Zed: v0.159.5 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 31.1 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6700 XT (RADV NAVI22) || radv || Mesa 24.2.4

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxbrunsfeld** [comment]
Do you have `bash` aliased to `fish`? That script is explicitly invoked with `bash`.

**Comment by bbigras** [comment]
I'm not 100% sure, but I don't think so.

If I run this, `$SHELL` says `fish` but `eval $(ssh-agent)` is not supposed to work with fish.

```
❯ bash

[bbigras@desktop:~]$ echo $SHELL
/run/current-system/sw/bin/fish

[bbigras@desktop:~]$ eval $(ssh-agent)
Agent pid 307400
```

**Comment by bbigras** [comment]
I have the same error with 40802d91d4faf849ad35fb53d6b00320c1d04cc1.

**Comment by bbigras** [comment]
with f80eb264fb9598ef929bbc38558f0adaac52e603, I get:

```
[2024-10-30T21:28:12-04:00 ERROR recent_projects::ssh_connections] Failed to open project: Failed to download server binary

Caused by:
    failed to run command: fish: Missing end to balance this if statement
                if command -v curl >/dev/null 2>&1; then
```

**Comment by bbigras** [comment]
@notpeter, I still have this error with 0.159.6.

Zed: v0.159.6 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 31.1 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6700 XT (RADV NAVI22) || radv || Mesa 24.2.4


```
Caused by:
    failed to run command: fish: Missing end to balance this if statement
                if command -v curl >/dev/null 2>&1; then
                ^^
```

**Comment by bbigras** [comment]
It seems to work with fish on nixos now. Thank you very much.
