### ISSUE TITLE
Smarter assistant insertion

### ISSUE THREAD

**Issue by savoygrizzly** [zed-industries/zed#19995]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great to have a feature that enables code generated code from the assistant to be « merged » in the proper file(s), maybe a button or shortcut. It would be even better to have it create the potentially missing structure (files and folders). This would help match the gap with the newest announced features from Cursor and the likes.

**Comment by notpeter** [comment]
There is significant ongoing work to alter/improve the process used to apply file changes from the assistant panel to replace the previous `/workflow` implementation  This should help with incorrect indentation / duplicated content in diffs as they are applied.

In the absence of a specific enhancement request beyond "merge generated code better" I'm going to close as unactionable.

**Comment by savoygrizzly** [comment]
Well, as an "example" I would point toward the very homepage of [cursor.com](cursor.com) which showcases exactly what I meant, a button to push the generated code to the context.

I wasn't aware Zed's "maintainers" got so sour. You started with a goal, then discard constructive comments that help you toward said goal.
