### ISSUE TITLE
Remote server timeout

### ISSUE THREAD

**Issue by bjorn3** [zed-industries/zed#20018]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Try to use remote server
2. Enter `ssh -4 gh-bjorn3@dev-desktop-eu-1.infra.rust-lang.org` as ssh command to use
3. Press enter
4. It first says "Starting Proxy" and then shows a popup with "Failed to connect" and "Timeout detected. Please try again."
5. Ssh'ing into the remote server shows that the `zed-remote-server-stable-linux-aarch64 proxy` command was already running before the timeout.

![image](https://github.com/user-attachments/assets/eed783ec-ebe4-4174-8363-5884bdee18fd)

### Environment

Zed: v0.159.5 (Zed)
OS: Linux X11 debian 12
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 22.3.6

### If applicable, attach your Zed.log file to this issue.

After several tries the log file ends with:

```
2024-10-31T11:25:56.971740367+01:00 [ERROR] failed to establish connection: Timeout detected
2024-10-31T11:25:56.972169543+01:00 [ERROR] Timeout detected
2024-10-31T11:26:01.137057603+01:00 [INFO] server binary is opened by another process. not updating
2024-10-31T11:26:06.214314604+01:00 [ERROR] failed to establish connection: Timeout detected
2024-10-31T11:26:06.21465454+01:00 [ERROR] Timeout detected
2024-10-31T11:26:34.26139124+01:00 [INFO] remote development server present and matching client version
2024-10-31T11:26:39.333994019+01:00 [ERROR] failed to establish connection: Timeout detected
2024-10-31T11:26:39.334297231+01:00 [ERROR] Timeout detected
2024-10-31T11:26:50.880147623+01:00 [INFO] server binary is opened by another process. not updating
2024-10-31T11:26:55.95482567+01:00 [ERROR] failed to establish connection: Timeout detected
2024-10-31T11:26:55.95508331+01:00 [ERROR] Timeout detected
```

**Comment by mateka** [comment]
Probably I had a similar issue: I cannot open two Zed instances showing two different projects on the same remote.

**Comment by unexge** [comment]
I'm having the same issue with Zed 0.159.7 (`0000569e4aff8fe8e4532001199e08a1872e8e76`), in my case it seems like server is stuck in this loop: https://github.com/zed-industries/zed/blob/main/crates/remote_server/src/unix.rs#L636-L643.

```bash
$ cat /proc/20400/fd/2
{"level":4,"module_path":"remote_server::unix","file":"crates/remote_server/src/unix.rs","line":640,"message":"(remote proxy) waiting for server to be ready to accept connections..."}
{"level":4,"module_path":"remote_server::unix","file":"crates/remote_server/src/unix.rs","line":640,"message":"(remote proxy) waiting for server to be ready to accept connections..."}
...

$ strace -p 20400
strace: Process 20400 attached
restart_syscall(<... resuming interrupted read ...>) = 0
stat("/home/unexge/.local/share/zed/server_state/dev-server-\"...\"-unexge/stdout.sock", 0x7fff1f479980) = -1 ENOENT (No such file or directory)
write(2, "{\"level\":4,\"module_path\":\"remote"..., 184) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=20400, si_uid=22659122} ---
nanosleep({tv_sec=0, tv_nsec=20000000}, 0x7fff1f47a120) = 0
stat("/home/unexge/.local/share/zed/server_state/dev-server-\"...\"-unexge/stdout.sock", 0x7fff1f479980) = -1 ENOENT (No such file or directory)
write(2, "{\"level\":4,\"module_path\":\"remote"..., 184) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=20400, si_uid=22659122} ---
```

**Comment by ConradIrwin** [comment]
It turns out that we were exceeding the length of the absolute path to a socket in some cases.  (Which TIL is about 100 characters for the absolute path: https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars) 

Fix incoming: #20093 

@mateka your problem is probably not the same as this would cause all connections to fail. Can you explain more about what you're seeing?

**Comment by mateka** [comment]
Sure! My workflow is as follows: I use https://github.com/lima-vm/lima for the Ubuntu 24 virtual machine on Mac M1. Projects from my work (mostly Python ones) are on the VM. Yesterday, I tested a remote connection with Zed, and it was great! I was editing one project and trying to check something in the other one. I was consistently getting the connection error when opening the second editor window. Today Zed installed an update and everything works fine!

**Comment by bjorn3** [comment]
I can confirm this is fixed with the latest stable release.
