### ISSUE TITLE
Unable to run on NixOS

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/zed#20015]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On nixos:
- install with `nix-shell -p zed-editor vulkan-tools`
- run `zeditor --foreground`

Output:
```

[2024-10-31T11:05:00+01:00 ERROR fs] No such file or directory (os error 2) about ["/home/shot/.config/github-copilot"]
wp_linux_drm_syncobj_manager_v1#44: error 0: Surface already has a syncobj attached
[2024-10-31T11:05:02+01:00 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Result::unwrap()` on an `Err` value: ERROR_SURFACE_LOST_KHR",
  "location_data": {
    "file": "/build/cargo-vendor-dir/blade-graphics-0.5.0/src/vulkan/init.rs",
    "line": 930
  },
  "backtrace": [
    "core::panicking::panic_fmt",
    "core::result::unwrap_failed",
    "blade_graphics::hal::init::<impl blade_graphics::hal::Context>::resize",
    "gpui::platform::blade::blade_renderer::BladeRenderer::new",
    "gpui::platform::linux::wayland::window::WaylandWindow::new",
    "<gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::platform::LinuxClient>::open_window",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::open_window",
    "gpui::window::Window::new",
    "workspace::Workspace::new_local::{{closure}}::{{closure}}",
    "async_task::raw::RawTask<F,T,S,M>::run",
    "<gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::platform::LinuxClient>::run",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::run",
    "gpui::app::App::run",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace",
    "std::rt::lang_start::{{closure}}",
    "std::rt::lang_start_internal",
    "main",
    "__libc_start_call_main",
    "__libc_start_main_alias_2",
    "_start"
  ],
  "app_version": "0.157.5",
  "release_channel": "Zed",
  "os_name": "Linux Wayland",
  "os_version": "nixos 24.11",
  "architecture": "x86_64",
  "panicked_on": 1730369102292,
  "system_id": "55a84e46-0bfd-4bf5-b95b-c8e739be502f",
  "installation_id": "eb45938f-924e-4dce-a12e-13642fefa1eb",
  "session_id": "41c3f37e-e92f-4721-ade1-ab90ba36a368"
}
```
`vkcube` is working as expected. I have tried running with `DRU_PRIME=1 zeditor` and `nvidia-offload zeditor` which result in the same issue.

### Environment

OS: NixOS 24.11.20241023.2768c7d (Vicuna) x86_64
                                                                                                                                                   Host: TUXEDO InfinityBook Pro Gen8 (MK2) (Standard)
                                                                                                                                                   Kernel: Linux 6.6.58
                                                                                                                                                   Uptime: 1 hour, 44 mins
                                                                                                                                                   Packages: 1475 (nix-system)
                                                                                                                                                   Shell: zsh 5.9
                                                                                                                                                   Display (S34C65xU): 3440x1440 @ 100 Hz in 34" [External]
                                                                                                                                                   Display (BOE0A3B): 2560x1600 @ 240 Hz in 16" [Built-in]
                                                                                                                                                   WM: Hyprland (Wayland)
                                                                                                                                                   Theme: Materia-dark-compact [GTK2/3/4]
                                                                                                                                                   Cursor: phinger (24px)
                                                                                                                                                   Terminal: kitty 0.36.4
                                                                                                                                                   Terminal Font: IosevkaNF-Bold (11pt)
                                                                                                                                                   CPU: 13th Gen Intel(R) Core(TM) i7-13700H (20) @ 5.00 GHz
                                                                                                                                                   GPU 1: NVIDIA GeForce RTX 4060 Max-Q / Mobile
                                                                                                                                                   GPU 2: Intel Iris Xe Graphics @ 1.50 GHz [Integrated]
                                                                                                                                                   Memory: 7.29 GiB / 31.09 GiB (23%)
                                                                                                                                                   Swap: 0 B / 59.99 MiB (0%)
                                                                                                                                                   Disk (/): 103.59 GiB / 1.82 TiB (6%) - btrfs
                                                                                                                                                   Locale: en_US.UTF-8

**Comment by SomeoneToIgnore** [comment]
> Check for existing issues

https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+ERROR_SURFACE_LOST_KHR

That seems to be covered already.
