### ISSUE TITLE
Open a collaborative session in same ssh directory

### ISSUE THREAD

**Issue by HKalbasi** [zed-industries/zed#20012]
### Check for existing issues

- [X] Completed

### Describe the feature

Having multiple people on a same directory is almost always wrong, since they can change files without other party noticing. Having a collaboration session and seeing the other person's cursor can help a lot. And since ssh is developed on top of collaboration feature, I guess it would be easy to implement.

If it doesn't require internet access or login, it would be even more great.

**Comment by notpeter** [comment]
Collaboration is supported with remote projects. If you add a Remote project via SSH to Zed and then join a Collab channel you can share this project and other users can collaborate just as with a normal local project.

Or am I misunderstanding?

**Comment by HKalbasi** [comment]
It is possible to make a collaboration session using normal collaboration mechanisms. What I'm asking here is to create a collaboration session automatically when two users ssh into a single directory of a single server, preferably without requiring connection to the zed servers and using the ssh connections as the data transfer medium. The benefits are:
* Users might prefer their data to not go through zed servers for privacy reasons.
* Users in airgapped networks can use the collaboration feature in this way without needing to setup an independent collaboration server.

**Comment by notpeter** [comment]
> Having multiple people on a same directory is almost always wrong

I fully agree.

> Having a collaboration session and seeing the other person's cursor can help a lot.

I fully agree.

> And since ssh is developed on top of collaboration feature, I guess it would be easy to implement.

This is an incorrect assumption.

> Users in airgapped networks can use the collaboration feature in this way without needing to setup an independent collaboration server.

Supporting peer-to-peer collaboration exclusively over SSH, without any coordinating server for project sharing, nor access to LiveKit servers for audio/screen sharing is a massive change in direction and not something we are planning on undertaking at this time.

Thanks for reporting!
