### ISSUE TITLE
Zed remote fails to download zed server binary on fly.io server

### ISSUE THREAD

**Issue by remorses** [zed-industries/zed#20019]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i try to open Zed remote on Fly server Zed fails to download the binary.

The logs do not add any information, maybe log the command that is tried to be run in the Zed logs next release so this kind of issue is easier to debug

### Environment

Zed: v0.159.5 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

```
2024-10-31T11:30:52.928412+01:00 [ERROR] Failed to download server binary

Caused by:
    failed to run command: 
2024-10-31T11:32:27.21752+01:00 [ERROR] Failed to download server binary

Caused by:
    failed to run command: 
2024-10-31T11:33:24.792839+01:00 [ERROR] Failed to download server binary

Caused by:
    failed to run command: 

```

**Comment by notpeter** [comment]
Can you try again with v0.159.6 (released this morning) there were some small improvements in adjacent areas which might have fixed this.

Could you provide steps to reproduce (e.g. `flyctl` commands used to spin an instance, any additional relevant setup) so I can see if I can reproduce?

**Comment by remorses** [comment]
It works now thank you!
