### ISSUE TITLE
我在终端运行python文件，没有任何报错反馈

### ISSUE THREAD

**Issue by ottopan** [zed-industries/zed#20021]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As shown in the picture, I run: python crawltest.py, but there is no feedback in the terminal.
![image](https://github.com/user-attachments/assets/d72329eb-f9d0-4e76-b88a-418ddb753ef5)

### Environment

Zed: v0.160.0 (Zed Dev 2d16d2d0363ad69653ab0c1a3736de74a07f476e)
OS: Windows 10.0.22631
Memory: 79.8 GiB
Architecture: x86_64
GPU: AMD Radeon 780M Graphics || AMD proprietary driver || 24.7.1 (LLPC)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
What is supposed to be in the output?

What does VSCode's (other editors') terminal does for your case?

If it does things better, can you share the script?
