### ISSUE TITLE
Add `confirm_delete` settings option

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#20020]
### Check for existing issues

- [X] Completed

### Describe the feature

when I delete a file/folder on the side panel using the `delete` key, I always get a confirm dialog asking if I want to delete _(personally I always turn it off)_

It would be cool to have this as a setting.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/633b665379c18a06959102c3857889b8bcbde4bb/assets/keymaps/default-macos.json#L602-L603

You can see how things are configured by default, reconfiguring those in your local keymap is supposed to help:
```
 "cmd-delete": ["project_panel::Delete", { "skip_prompt": true }], 
```

**Comment by sparrowsl** [comment]
thanks for the guide, :+1: 
_personally I don't like reconfiguring kepmaps_ :smile:

**Comment by SomeoneToIgnore** [comment]
It's always a conflict of interests there, the whole `{ "skip_prompt": false }` had appeared due to someone personally wanting the opposite of your workflow.

Zed tries to be somewhat generic, but cannot satisfy all.

**Comment by daveycodez** [comment]
Need an option to skip the confirmation dialog when right-clicking to delete. This should live in the project_panel settings. Very easy boolean setting to implement I imagine.
