### ISSUE TITLE
Disable auto close for single quotes while commenting

### ISSUE THREAD

**Issue by andrewyur** [zed-industries/zed#20035]
### Check for existing issues

- [X] Completed

### Describe the feature

I like the auto-close feature, but find it annoying that whenever I am writing a word inside a comment that requires an apostrophe, I have to delete the extra apostrophe it adds. It would probably be easier to disable auto close entirely within comments, but I feel like apostrophes/single quotes are the only ones that make this a problem.

**Comment by SomeoneToIgnore** [comment]
What is the language you're dealing with?

**Comment by andrewyur** [comment]
Python and Nix are the two languages I have tested it with (both use # for comments)

**Comment by notpeter** [comment]
Yeah, it would be neat to support a more granular, comment-aware `use_autoclose`.

- Closing as duplicate of https://github.com/zed-industries/zed/issues/9195
- See also: https://github.com/zed-industries/zed/issues/14372
