### ISSUE TITLE
Telemetry tmp file cleanup

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#20045]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Previously we moved temporary storage of telemetry files from ~/.config/zed to the platform log directory (good) but we still aren't cleaning up old files (bad).  I have 841 on my Mac, the largest of which is ~300KB.
 
```
# linux:
ls -l ~/.local/share/zed/logs/.tmp* |wc -l

# macos:
ls -la ~/Library/Logs/Zed/.tmp* |wc -l
```

Related issues:
- https://github.com/zed-industries/zed/issues/14221
- https://github.com/zed-industries/zed/issues/7155
- https://github.com/zed-industries/zed/pull/14002

### Environment

Zed: v0.161.0 (Zed Nightly 7ce131aaf8e471e77e16cafb028fc7d1fbc5be9c)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="557" alt="Screenshot 2024-10-31 at 15 53 48" src="https://github.com/user-attachments/assets/a70905de-317f-42ab-979e-d3993b19a053">

### If applicable, attach your Zed.log file to this issue.

N/A

**Comment by ConradIrwin** [comment]
I think we should probably stop writing them entirely, cmd-shift-p "open telemetry logs" shows you recent information; and if people want to know more about what we collect, they can contact us.
