### ISSUE TITLE
Error occurred while compiling Zed on Windows 10.

### ISSUE THREAD

**Issue by mylvghb** [zed-industries/zed#20052]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Run `cargo run --release` in the CMD on Windows 10.
2. 
![image](https://github.com/user-attachments/assets/f04481e4-322a-4a43-b026-9ab9f58316e5)

### Environment

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎5/‎8
操作系统内部版本	19045.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by CharlesChen0823** [comment]
which shell do you use? pwsh or powershell?, you can try powershell, again?

**Comment by mylvghb** [comment]
> which shell do you use? pwsh or powershell?, you can try powershell, again?

The same issue exists in PowerShell.
![image](https://github.com/user-attachments/assets/66225b50-adb5-4cb6-baaf-b7893e4900b5)

**Comment by CharlesChen0823** [comment]
powershell version?

**Comment by mylvghb** [comment]
> powershell version?

![image](https://github.com/user-attachments/assets/c09be98c-a76f-4b84-84f8-c37d205b77b9)

**Comment by CharlesChen0823** [comment]
this might the ps old version not support, you can try download windows terminal, then try

**Comment by mylvghb** [comment]
In Powershell 7:
![image](https://github.com/user-attachments/assets/f9c1076f-0942-4f4d-b927-0df23c44e2c6)

**Comment by mylvghb** [comment]
> this might the ps old version not support, you can try download windows terminal, then try

In Powershell 7:

![image](https://github.com/user-attachments/assets/3b8a1bb9-c3f0-463d-940d-48a140851ce8)

**Comment by CharlesChen0823** [comment]
download this, `https://github.com/microsoft/terminal`. This should be powershell deal with long path problem, might be .NET Framework version not supported.

**Comment by mylvghb** [comment]
I 

> download this, `https://github.com/microsoft/terminal`. This should be powershell deal with long path problem, might be .NET Framework version not supported.

I have resolved the issue. The reason was that the maximum length for regular paths in the Windows system is limited to 260 characters.

**Comment by CharlesChen0823** [comment]
> regular paths in the Windows system is limited to 260 characters

I known this. in new powershell, the limited might not exists.  you can send a PR to the docs, I thought, someone will also hit this problem.
