### ISSUE TITLE
Wierd Auto Complete Keeps Open

### ISSUE THREAD

**Issue by lassejlv** [zed-industries/zed#20062]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

So whenever i type, 9/10 of the time the autocomplete box keeps being there until i click esc. Watch video i linked.

https://github.com/user-attachments/assets/bcff7b68-50c1-4456-891f-4bfa69989a08

### Environment

Zed: v0.159.5 (Zed)
OS: macOS 15.0.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
You can disable this by changing the defaults for

https://github.com/zed-industries/zed/blob/08b124c8d44aa6a0a6f746dd148e5c1ccee7d17e/assets/settings/default.json#L150-L152

**Comment by lassejlv** [comment]
Thanks, works now!
