### ISSUE TITLE
Name a project

### ISSUE THREAD

**Issue by lode** [zed-industries/zed#20064]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm having a multi-folder project and would like to give this project a custom name. Currently in the top left the first folder is mentioned, but this is not the best description of the project.

Also, the project switcher shows all the project folders in the name and in the folder list. This makes it a bit hard to switch project since the long list of folders makes scrolling / overview of projects messy.

For context, my project consists of 13 folders. The parent folder of these 13 is not a candidate, as it also contains folders I don't want in my project, and the folders are not on the same level.

### If applicable, add mockups / screenshots to help present your vision of the feature

I would like a project setting to provide a custom name for the project. This name is then shown in the top left, and as the name in the project switcher.

Also, when such a project name is set, or maybe also without, it would be nice to limit the list of folders shown in the project switcher. So it gives more overview.

**Comment by MankiratSingh1315** [comment]
Do you mean something like I commented [here](https://github.com/zed-industries/zed/issues/19898#issuecomment-2447216458) ?

**Comment by lode** [comment]
> Do you mean something like I commented [here](https://github.com/zed-industries/zed/issues/19898#issuecomment-2447216458) ?

I'm not sure I follow you.

But both problems (saving folded state & naming) occur with projects with multiple folders.

And in the screenshot you commented there is an 'untitled (workspace)' label. I don't know VSCode but I assume you can give that an own name. I'm using Sublime, and there a project is a file that you save. The filename is then used as the name for the project, also allowing to customize the name.

**Comment by jansol** [comment]
#4431 seems like it covers the custom name part?
And #15120 is about better support for workspaces with multiple independent root directories.

Unless I'm missing something, it would seem appropriate to close this in favour of upvoting / commenting on those two?

**Comment by lode** [comment]
Thanks! Duplicate of #4431
