### ISSUE TITLE
In the outline panel, executing menu::SelectNext and menu::SelectPrev can be done without moving focus to the Editor

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#20073]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, when selecting items in the Outline Panel or using `menu::SelectNext` and `menu::SelectPrev` commands, Zed automatically moves the focus to the editor each time, which interrupts continuous navigation operations and is quite inconvenient. 

It would be more better to have a configuration option similar to the `change_selection` parameter in `outline_panel::Open` to control this behavior.

**Comment by SomeoneToIgnore** [comment]
Bisected to https://github.com/zed-industries/zed/commit/80f89059aabade8f83c35a371ba1cc3a713a5cd6
