### ISSUE TITLE
Cannot open more than one file normally from file explorer

### ISSUE THREAD

**Issue by RayZ3R0** [zed-industries/zed#20070]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If I already have one file opened in Zed, i cannot double click to open a file from the file explorer and my mouse will keep loading until I close the file explorer. I can open a file by double clicking if zen is not already opened. I can work around this by dragging and dropping files into Zed but its annoying still

### Environment

Zed: v0.160.2 (Zed Preview)
OS: Linux X11 linuxmint 22
Memory: 15.5 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6600 || AMD open-source driver || 2024.Q3.3 (LLPC)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/ddb3dbb1-8c5b-41e2-89ff-79bbb366a864

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17599246/Zed.log)
</pre></details>

**Comment by mgsloan** [comment]
This is working for me with Ubuntu 22.04.05 + X11 + Nautilus 42.6 + Zed devel 0.163.0

**Comment by kantmn** [comment]
not working for me with Linux Mint 22 X11 + Zed 161.2 + Nemo 6.2.8

**Comment by 0xtimsb** [comment]
I was able to reproduce the issue and found a fix. Check PR for more detail.

For those affected, until this PR is merged, you can manually update all instances of `libexec/zed-editor` to `bin/zed` in the desktop files located in `~/.local/share/applications`.

For example:
```diff
- TryExec=/home/tims/.local/zed.app/libexec/zed-editor
+ TryExec=/home/tims/.local/zed.app/bin/zed
```

**Comment by kantmn** [comment]
@0xtimsb great finding, i can confirm changing the path of my startmenu record for zed 

- TryExec=/home/USERNAME/.local/zed.app/libexec/zed-editor %U
+ TryExec=/home/USERNAME/.local/zed.app/bin/zed %U

works and opening multiple tabs via doubleclick in nemo explorer suddenly works,
using zed 0.162.5
