### ISSUE TITLE
Graphviz preview 

### ISSUE THREAD

**Issue by spirosmaggioros** [zed-industries/zed#20096]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed lacks of a preview tool for graphviz(either by default or an extension). VScode provides the graphviz interactive preview that renders .dot files.

**Comment by notpeter** [comment]
It would appear that the VSCode [Graphviz Interactive Preview](https://marketplace.visualstudio.com/items?itemName=tintinweb.graphviz-interactive-preview) Extension operates by rendering a graphviz file to an interactive webview.

Closing in favor of:
- #21208
