### ISSUE TITLE
Copy line

### ISSUE THREAD

**Issue by VoxlDevv** [zed-industries/zed#20103]
### Check for existing issues

- [X] Completed

### Describe the feature

like copy line up/down in vscode, it will make write code faster, without pressing Ctrl+C and Ctrl+V

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/773a3b335edc1cd686d06cf1e3a259f359a21d2c/assets/keymaps/default-macos.json#L324-L325
