### ISSUE TITLE
Undo with vim broken on linux

### ISSUE THREAD

**Issue by jrg1k** [zed-industries/zed#20111]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Undo with vim is broken for me on linux. When I use it it mangles the text, e.g. when undoing it will place a random change from the undo tree at the wrong place.

### Environment

Zed: v0.159.7 (Zed)
OS: Linux Wayland fedora 41
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6900 XT (RADV NAVI21) || radv || Mesa 24.2.5

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by gwik** [comment]
I have the same issue, undo leaves parts of the changes in place.
I don't use vim mode.

Linux / same version.
