### ISSUE TITLE
Tab highlighting when file has changes

### ISSUE THREAD

**Issue by srihariash999** [zed-industries/zed#20128]
### Check for existing issues

- [X] Completed

### Describe the feature

- When a tab is open of a file and it has some changes made (the open file has diffs and the file is highlightes in the file explorer view) it is useful if the tab itself can have some kind of highlighting. 
- A color change, a dot beside the name or any kind of visual cue will be appreciated. Bonus points if it follows the colors of the git diff (orange-ish for changes, green for untracked etc)

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1354" alt="Screenshot 2024-11-03 at 11 23 45 AM" src="https://github.com/user-attachments/assets/7768cbf8-44ff-485d-b914-3ef40d0c1008">

**Comment by yqj13** [comment]
### good

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/3b76ba6d5ab6745cd12d2cb632ae4a55680dc89a/assets/settings/default.json#L529-L532
