### ISSUE TITLE
Redo-ing previously undone edits results in inconsistent buffer state, must be manually resolved

### ISSUE THREAD

**Issue by bww** [zed-industries/zed#20147]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After undo-ing a few steps back, redo-ing a few steps forward will result in a buffer state that never existed before.

It seems as possible that some (one?) undo states are skipped over on redo and, as a result, text ranges that are being used on by subsequent redo operations do not point to the correct content anymore since some edits were not applied as expected, so the buffer is corrupted.

The effect is that redo operations basically modify the buffer in a way that cannot be undone (or redone) back out of because the undo/redo state is corrupted and the buffer is corrupted, so I have to manually edit text until it's back in a consistent state and then restart Zed. Not super confidence inspiring...

I've noticed this in very recent versions (currently using 0.159.7). It happens quite frequently.

### Environment

Zed: v0.159.7 (Zed)
OS: macOS 15.0.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by kddige** [comment]
+1

**Comment by mrnugget** [comment]
@SomeoneToIgnore isn't this what you worked on?

**Comment by SomeoneToIgnore** [comment]
Could be so too, albeit we did check the undos only.
Worth rechecking after v0.159.10 (released right now)

**Comment by bww** [comment]
@SomeoneToIgnore, @mrnugget: I upgraded to v0.159.10 and haven't noticed the problem after a day of use, so I'm inclined to say that version fixes the problem. Thanks, I'll close this issue.
