### ISSUE TITLE
Enable word wrap for markdown files by default

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#20150]
### Check for existing issues

- [X] Completed

### Describe the feature

Enable word wrap for markdown files by default, like VSCode does.

This is helpful for markdown files with long paragraph in a single line.

**Comment by machin3io** [comment]
Add this to your settings.json
![image](https://github.com/user-attachments/assets/b62792a9-bb2d-4f49-9f6f-055bb6b3f210)

**Comment by kzhui125** [comment]
thanks this should be supported by default instead of explicit settings by user

**Comment by SomeoneToIgnore** [comment]
As usual, one way or another, there are people who want the opposite.

We've removed this setting by default in https://github.com/zed-industries/zed/pull/14304 due to people being very confused by the vertical line appearing in markdown only.

**Comment by kzhui125** [comment]
@SomeoneToIgnore The previous default is not the same as VSCode, the vertical line is ugly, that's why people get confused.

What VSCode does is don't have the vertical line, and the width can auto change when the editor width changes.

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/70b46c98-ae0c-427d-9cff-84465b0e573d">

[test.md](https://github.com/user-attachments/files/17619660/test.md)

**Comment by kzhui125** [comment]
What we should do is not restrict the width for markdown files in default settings, but auto wrap to next line when it reach the end of the editor.

Or is there a setting in Zed that support this feature?

If not, I think this should be a feature request.

**Comment by machin3io** [comment]
Toggle soft wrap.

**Comment by kzhui125** [comment]
```json
    "Markdown": {
      "soft_wrap": "editor_width"
    }
```

I have tried with this setting and it works now, it doesn't have vertical line.

I think this should be the default, and people won't **be confused by the vertical line appearing in markdown only.**

**Comment by SomeoneToIgnore** [comment]
Ah, so instead of 
`soft_wrap = "preferred_line_length"`

you want
`soft_wrap = "editor_width"`

That won't have the vertical line and will presumably behave similar to what you've described.

It makes some sense, but then it raises the questions of "why not enable this soft wrap for other things, text files, *.rs files, my-favourite-files, etc.

And I do not have a good answer why this particular language has it and others do not — seems more like a preference based on a matter of taste.

My preference based on a matter of taste prefers uniform settings instead, and others may change it.

**Comment by kzhui125** [comment]
This is VSCode: https://github.com/microsoft/vscode/issues/21301#issuecomment-282251944
default setting of markdown:

<img width="639" alt="image" src="https://github.com/user-attachments/assets/db464890-98fe-4915-ba26-19ce178af0eb">

Here is what happens when we edit VSCode github README.md without word wrap:

[README.md](https://github.com/user-attachments/files/17620029/README.md)

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/650f8bc2-50ab-4ab3-b3f8-7f98812e3956">

I think this is why VSCode use word wrap as markdown default.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/8cc9d484-0c70-4bd5-b7a7-99ce3f0bc9c9">

Thanks,

**Comment by SomeoneToIgnore** [comment]
1. Yes, I understand that VSCode has it by default.

Do you understand that Zed is not VSCode and does certain things differently?

2. LLM cannot reason really, here's another text from it:

![image](https://github.com/user-attachments/assets/9980eac4-6676-49d1-af01-a404d757861d)

So please keep this nonsense out of the discussion.

3. Yes, there are markdown files with long lines, same as Rust files, text files and many other ones.

So, again, I have to ask you:
> "why not enable this soft wrap for other things: text files, *.rs files, my-favourite-files, etc."

4. So far, it's your opinion against mine (also, the other commenter here seems to be opposed to your opinion)

I see two large differences between you and me in this context:

* you have not done anything in this repo besides posting in this issue: https://github.com/zed-industries/zed/pulls/kzhui125  
while I have been around for some time

* you and hundreds of others will come and go, but it's me (and the other maintainers) that have to live with the fall-outs of the changes made here, especially the fundamental ones touching the defaults. What for?

-------------------------

So far, I would still lean to the uniform defaults we have now and this is my last message on the topic here unless some more intelligent reason appears.

**Comment by kzhui125** [comment]
I understand the reasoning behind keeping the current default markdown settings. I'm not pushing for a change and appreciate the concerns about leaving this choice to users.

**This was simply my personal suggestion and can be marked as "not planned" or closed.**

Thanks,

<details><summary>Other questions</summary><pre>

> Do you understand that Zed is not VSCode and does certain things differently?

I understand that Zed is its own distinct editor with its own philosophy and approach,
separate from VSCode. However, since VSCode is currently one of the most popular code editors,
it can serve as a useful reference point when discussing certain aspects of editors,
particularly for subjective features or design choices.

> LLM cannot reason really

While I know LLMs can present arguments for both sides,
I shared this particular perspective because it aligns more closely with my views.

> why not enable this soft wrap for other things: text files, *.rs files, my-favourite-files, etc.

1. Code files (*.rs, *.py, *.cs, etc.) require precise formatting.
Enabling word wrap can break code readability, as syntax elements like braces `{` might wrap to the next line inappropriately.
2. While .txt files are common, they serve various purposes beyond paragraph text.
They might contain structured data, base64 strings, logs, or configuration information.
3. Other file extensions are less common and have varied use cases
4. Markdown files are primarily used for writing prose,
where paragraphs can be stored as single lines (similar to Assistant Panel).

> So far, it's your opinion

Please feel free to ignore my opinion.

> you have not done anything in this repo besides posting in this issue

As Zed is currently my favorite editor, I was happy to raise issues and make suggestions,
believing they could help improve Zed further. I apologize if my feedback
has taken up too much of your time.
</pre></details>

**Comment by xpe** [comment]
@kzhui125 I wanted to say your comments strike me as incredibly kind and humble. Not to mention well-thought out and explained. This is really a breath of fresh air here on the Internet where people often get quite upset.
