### ISSUE TITLE
zed installed in wrong linux directory

### ISSUE THREAD

**Issue by media-informatics** [zed-industries/zed#20174]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed is currently installed in /usr/sbin/zed. However this directory is supposed to contain binaries for system admin. If a user installed binary is not installed from a package manager, then it should be placed in the
/usr/local/bin directory if all users should have access and in $HOME/bin or possibly  $HOME/.local/bin if a non-admin user installs it for himself only.

The rules for binary placement have been weakened in linux over time, since currently the directories /usr/sbin and /sbin are part of the PATH for a regular user - originally they should only be in the path for adminstrators.

### Environment

System is Linux Mint 22:
Linux cuchulainn 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
The official Zed linux installer will not install into /usr/sbin/zed -- my guess is that you have likely installed `zed - zfs event daemon` installed via your package manager.

If you use the Zed [official linux installer](https://zed.dev/linux) it will install in `~/.local/zed.app` with a symlink placed at `~/.local/bin/zed` as you would expect.
