### ISSUE TITLE
Jump from outline panel to code using the keyboard

### ISSUE THREAD

**Issue by dmbfm** [zed-industries/zed#20187]
### Check for existing issues

- [X] Completed

### Describe the feature

Maybe I am wrong, but when using the outline panel the only way to select an item and jump to the item in the source code, focusing the editor pane, is by double clicking the item? It would be really nice if you could just press a key, like enter, space or any other, and jump to the editor at the correct place without the need of using a mouse.

**Comment by notpeter** [comment]
`space` will jump scroll to the correct part of the file, but it doesn't move your cursor or toggle focus to the editor 🫤

**Comment by SomeoneToIgnore** [comment]
Yes, we definitely should rework the defaults.
The tricky bit here is to keep the keyboard navigation within the panel, as any caret placement will move the focus away.

Meanwhile, you can remap them:

https://github.com/zed-industries/zed/blob/8196db6022b3a041b0b595ebc4130b8e029759f1/assets/keymaps/default-macos.json#L580

`"change_selection": true` will behave similar way as a double click.
