### ISSUE TITLE
.editorconfig takes control over soft-wrap

### ISSUE THREAD

**Issue by LGLO** [zed-industries/zed#20194]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello!

Recent update included usage of .editorconfig by Zed.

.editorconfig file that contains `max_line_length` to a numeric value (ie. not `off`) causes that soft-wrap is enabled.

`max_line_length` should be used for hard-wrapping, see: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length

> Forces hard line wrapping after the amount of characters specified. off to turn off this feature (use the editor settings).

So, in other words `max_line_length` is meant for limiting actual line length if formatted files.
Soft-wrap setting is for user display preferences and should not be overridden by file meant for consistency of formatting in multi-user projects.

I propose to just remove soft-wrap related parts from [fn merge_with_editorconfig](https://github.com/zed-industries/zed/blob/8196db6022b3a041b0b595ebc4130b8e029759f1/crates/language/src/language_settings.rs#L872)

Greetings!

### Environment

Zed: v0.159.10 (Zed)
OS: Linux Wayland fedora 41
Memory: 60.6 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV GFX1103_R1) || radv || Mesa 24.2.5

**Comment by katry0** [comment]
Hi, I think it should be configurable in settings for example by property "editorconfig_soft_wrap": `false` / `true`, by default set on `false`. I know it is non-standard but some people including me uses `max_line_length` property also to set ruler which is not possible since this change.
