### ISSUE TITLE
Task does not close on success anymore after newest update (10/04/2024)

### ISSUE THREAD

**Issue by TympanicLemon** [zed-industries/zed#20208]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

    {
        "label": "lazygit",
        "command": "lazygit",
        "hide": "on_success"
    }

This should close lazygit as soon as i hit q/escape out of lazygit which it DID do all the time, up until today. And i havent changed anything in my config.

### Environment

Zed: v0.159.10 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
This appears to be fixed in Zed Preview.  The fix will be available in Zed Stable on Wednesday with v0.160.x.

Thanks for reporting.
