### ISSUE TITLE
Hide `xdg-desktop-portal` warning if false is provided for "use_system_path_picker"

### ISSUE THREAD

**Issue by alexlnkp** [zed-industries/zed#20239]
### Check for existing issues

- [X] Completed

### Describe the feature

Despite there being an option to explicitly only use fallback folder/file picker, introduced by #14524, the warning for whenever you use the fallback folder/file picker still appears every time, which is really annoying. So the suggestion is to simply not show this warning if the user explicitly stated that they want to use ONLY the fallback folder/file picker in the settings.

**Comment by notpeter** [comment]
I'm not sure I'm familiar with the warning you are mentioning.  Can you share a screenshot?

I have the following my settings.json on both my Mac and Linux machine without issue.
```json
  "use_system_path_prompts": false,
```
