### ISSUE TITLE
LSP logs: Name just shows 'node' for some language servers

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#20245]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:
1. Open a `.html` file
2. Open `debug: language server logs` (LSP Logs)
3. Notice is no entry for `html-language-server`, but two entries are listed as `node (zed)`

### Environment

Zed: v0.161.0 (Zed Nightly c41a8e33a0aa05708b6e21731e7e708a8f34e6c3)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="214" alt="Screenshot 2024-11-05 at 10 08 08" src="https://github.com/user-attachments/assets/651ef487-be9a-45a1-a172-8e5bc2b67e35">

**Comment by osiewicz** [comment]
... except that e.g. HTML language server does not fill this property out, so we couldn't use that anyways for some servers. I recall though that we used to show server name verbatim at some point.

**Comment by SomeoneToIgnore** [comment]
Closed via https://github.com/zed-industries/zed/pull/20428
