### ISSUE TITLE
Generated permalinks are incorrect when working in a subdirectory of the repository

### ISSUE THREAD

**Issue by cdevoogd** [zed-industries/zed#20260]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is the same #12542, but when that issue was closed it was mentioned there that a new issue should be created if it still exists.

If I check out the Zed repo and open the editor in the root of the repository, the permalink does work properly.

```
❯ git clone https://github.com/zed-industries/zed
❯ cd zed
❯ zed .
```

In the editor I navigate to the first line of `script/bootstrap`, run the permalink command, and get the correct permalink:
```
https://github.com/zed-industries/zed/blob/6dfff1b46d38ed25d53c4d415de989da58078ab1/script/bootstrap#L1
```

But if you instead open the editor inside of the `script` subdirectory, the permalink is incorrect.

```
❯ git clone https://github.com/zed-industries/zed
❯ cd zed/script
❯ zed .
```

If I open the same file and get a permalink, the link returns a 404
```
https://github.com/zed-industries/zed/blob/6dfff1b46d38ed25d53c4d415de989da58078ab1/bootstrap#L1
```

It seems like the links are still being created relative to the current directory rather than relative to the root of the repository.

### Environment

Zed: v0.159.10 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Sorry, I misunderstood. Thank you for following up. I've reopened the original issue:
- https://github.com/zed-industries/zed/issues/12542
