### ISSUE TITLE
Remote SSH connection fails to check if binary is in use

### ISSUE THREAD

**Issue by joshbainbridge** [zed-industries/zed#20272]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When testing the new remote feature I'm unable to connect to the remote server. The message 'failed to check if binary is in use. Please try again.' is displayed.

The server OS is Red Hat Enterprise Linux 9 with a manually installed ~/.zed_server/zed-remote-server-linux-x86_64 from https://github.com/zed-industries/zed/releases/tag/v0.159.10. The server is using a 'tcsh' shell and does not have access to the internet.

Hope that is helpful. Let me know if you need any more information. Zed is a great tool, thank you for all the hard work.

### Environment

Zed: v0.159.10 (Zed)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/bba04cdd-0edc-4c72-a8ff-55eb93fe6d97">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-11-05T23:54:36.803868Z [ERROR] failed to check if binary is in use

Caused by:
    failed to run command: Unmatched '''.
    Ambiguous output redirect.
    Ambiguous output redirect.
    fi: Command not found.
    Ambiguous output redirect.
    Ambiguous output redirect.
    fi: Command not found.
    fi: Command not found.
    Unmatched '''.
```
</details>

**Comment by joshbainbridge** [comment]
Also tested with `v0.160.7-pre` and got the same result. The stage displayed in the background is `Acquired lock file on host...` in case this is important.

**Comment by joshbainbridge** [comment]
Looking at the log it appears this might be due to using tcsh on the remote server. The error indicates that a bash(like) script is being run which uses syntax that isn't compatible with tcsh.

**Comment by joshbainbridge** [comment]
Looks like this script is being called in:

https://github.com/zed-industries/zed/blame/571f9de553f5c44ac670fd6ae4cb19e33eab6e72/crates/remote/src/ssh_session.rs#L1928

but that function is now removed in the latest 'main' branch. I'll test on the next preview and see if the issue is resolved.

**Comment by ConradIrwin** [comment]
@joshbainbridge thanks for the investigative work, this should indeed be fixed on the latest main (which should ship to preview at some point tomorrow)

**Comment by joshbainbridge** [comment]
That worked, I’m now able to connect. Thank you @ConradIrwin for such a fast turnaround in getting that release out.

I’ll close the issue.
