### ISSUE TITLE
(vim mode) Default register for select, delete & change

### ISSUE THREAD

**Issue by tlvenn** [zed-industries/zed#20280]
### Check for existing issues

- [X] Completed

### Describe the feature

Coming from neovim, I am used to https://github.com/gbprod/cutlass.nvim and the way it overrides the following keys to always use the black hole register: `c`, `C`, ` s`, `S`, `d`, `D`, `x`, `X`.

It also add a proper cut operator key which is super useful.

Maybe to keep it simple, we could configure the default register used by vim operators like:
```
registers = {
    select = "_",
    delete = "_",
    change = "_",
  }
```

### Environment

NA

**Comment by ConradIrwin** [comment]
@tlvenn Since #20277 you can achieve this with:

```
[
  {
    "context": "vim_mode == normal || vim_mode == visual",
    "bindings": {
      "c": ["workspace::SendKeystrokes", "\" _ c"],
      "shift-c": ["workspace::SendKeystrokes", "\" _ shift-c"],
      "d": ["workspace::SendKeystrokes", "\" _ d"],
      "shift-d": ["workspace::SendKeystrokes", "\" _ shift-d"],
      "s": ["workspace::SendKeystrokes", "\" _ s"],
      "shift-s": ["workspace::SendKeystrokes", "\" _ shift-s"],
      "x": ["workspace::SendKeystrokes", "\" _ x"],
      "shift-x": ["workspace::SendKeystrokes", "\" _ shift-x"]
    }
  }
]
```

Happy to accept PRs to add this to the documentation, but I don't think we need a different way to configure this.

**Comment by HarshNarayanJha** [comment]
Hey @tlvenn we also have this setting in zed that allows to configure when to use system clipboard. It might be useful for you, since I was looking for the same thing.

https://zed.dev/docs/vim#changing-vim-mode-settings

```json
"vim": {
    "use_system_clipboard": "on_yank",
  },
```

**Comment by tlvenn** [comment]
Thanks for the reply @ConradIrwin, sorry somehow missed your message. 

Any idea how i could create a cut key similarly to what cutlass does ? Trying to bind "m" to do a regular "d". Tried different things without much success so far.

**Comment by tlvenn** [comment]
For reference:

![Image](https://github.com/user-attachments/assets/14c518fa-f597-4b98-9a0d-37ba005762cd)

**Comment by ConradIrwin** [comment]
@tlvenn You should be able to bind `m` to `vim::PushDelete` directly.  And `shift-m` to "vim::DeleteToEndOfLine".

**Comment by tlvenn** [comment]
Ha yes I should had thought about mapping directly to the vim action...
The only remaining issue is how to handle "mm" the equivalent of "dd".

```
  {
    "context": "vim_mode == operator",
    "bindings": {
      // Cut key for supporting "mm"
      //"m": "vim::PushDelete"
       "m": ["workspace::SendKeystrokes", "d"]
    }
  }
```

I tried both of the above but it does not work.
The action does nothing and sending the keystroke is actually being filtered even though it should not match the context

![Image](https://github.com/user-attachments/assets/65f3d50f-8e06-415f-b499-5ccb9d62f17c)

**Comment by ConradIrwin** [comment]
Confusingly `vim_mode == operator` is currently only used for operators like `f`/`t` that require input.

```
  {
    "context": "vim_operator == d",
    "bindings": {
      "m": "vim::CurrentLine"
    }
  },

```
seems to work.

I'm not sure why the SendKeystrokes doesn't work in that context – probably because  it hits https://github.com/zed-industries/zed/blob/5e1fd9e21acd7ab2902a666d0d23b125d8abd920/crates/vim/src/vim.rs#L797-L814 before being handled; so we're back in normal mode, so it hits your other binding.

**Comment by tlvenn** [comment]
Thank you so much @ConradIrwin, it works flawlessly now.
