### ISSUE TITLE
Incorrect comment in Ruby

### ISSUE THREAD

**Issue by Rusydy** [zed-industries/zed#20284]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to comment out lines in Ruby using `cmd+/`. It gives me this `//` instead of this `#`.

To solve this, in which file should I start?

### Environment

Darwin Users-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112 arm64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by vitallium** [comment]
@Rusydy can you please provide an example? I can't reproduce this on my end.

**Comment by Rusydy** [comment]
I can't share footage since this issue occurs in a file from my company's repository. Interestingly, it only happens in one specific file.

I'll update this thread once I am able to replicate it in a new Rails project.

Thank you, @vitallium
