### ISSUE TITLE
Incrementally accept inline auto complete / suggestion

### ISSUE THREAD

**Issue by lougreenwood** [zed-industries/zed#20282]
### Check for existing issues

- [X] Completed

### Describe the feature

When using something like copilot or supermaven for autocomplete I often find that it's suggestion is correct for the first few tokens, but then goes off on one suggesting masses of stuff I don't want.

This is especially common when autocomplete is enabled in the Assistant panel.

For example, see this screenshot:

![Screenshot 2](https://github.com/user-attachments/assets/27893908-47e2-4a23-9ca5-a6089679772d)

Let's say I want to accept the next word, but not the whole suggestion, I can't do this now. Either I need to just type the word out completely myself or accept the whole thing and remove the excess.

This feels like a regression from the pre-copilot days of inline completion where the suggestions were more constrained to dictionaries or language server suggestions - but as a result were more accurate because the suggestions were smaller, simpler and more focuesed.

The above is a minor ergonomic issue, however, I have also had problems where autocomplete is being overly zealous in a function signature or call and will add some incorrect type or incorrect arg. In this case I can either accept the whole thing and break my code or I need to just disregard the whole suggestion, even if it starts out correctly & useful.

## Solution

It would be useful if we could incrementally accept a suggestion, perhaps with something like `shift-tab` to accept one word / space delimited fragment at a time.

This would allow me to accept the suggestion to autocomplete the word `autocomplete` in the above example and then continue typing out my idea manually.

### Environment

Zed: v0.160.2 (Zed Preview)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
We seem to have it

https://github.com/zed-industries/zed/blob/e47b305ca7dde20cbc567746498c41d71fb785da/assets/keymaps/default-macos.json#L158

**Comment by lougreenwood** [comment]
@SomeoneToIgnore 

Amazing... I thought I had tried all key combos, but I have no idea how I missed this.

Thanks for the amazingly quick response! Will close
