### ISSUE TITLE
Incorrect display of folder ui

### ISSUE THREAD

**Issue by huhu415** [zed-industries/zed#20290]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I write the following two rules in my .gitignore, my `grpc_server` folder and `grpc_client` folder are grayed out, my expectation should be that the grpc_server file and grpc_client file are grayed out, not the folder.     
   
<img width="146" alt="截屏2024-11-06 19 16 02" src="https://github.com/user-attachments/assets/271f31ad-df7c-4876-aa58-ed4c23b3d9b3">

.gitignore
```
grpc_server 
grpc_client 
```

### Environment

.

**Comment by jansol** [comment]
The gitignore documentation disagrees: https://git-scm.com/docs/gitignore#_pattern_format

> If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.
