### ISSUE TITLE
Eslint crash - Failed to run eslint.

### ISSUE THREAD

**Issue by AlejoPeque** [zed-industries/zed#20333]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1427" alt="Screenshot 2024-11-06 at 11 33 18 PM" src="https://github.com/user-attachments/assets/71465e2f-7609-461c-a732-7c250054012e">
I have this issue with ESLint where it breaks and doesn't pick up the errors from the JS files.

### Environment

<img width="1008" alt="Screenshot 2024-11-06 at 11 35 36 PM" src="https://github.com/user-attachments/assets/1dab9653-cd84-4ada-b7b5-347d2ce2da99">

Here's the error log.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by 799189288** [comment]
same as #19709

**Comment by JosephTLyons** [comment]
Closing in favor of:

- https://github.com/zed-industries/zed/issues/19709

Please upvote (👍) this issue so we know what to prioritize!
