### ISSUE TITLE
Ensure docs for settings are up to date with the actual settings

### ISSUE THREAD

**Issue by bjorn3** [zed-industries/zed#20346]
### Check for existing issues

- [X] Completed

### Describe the feature

Several of the settings listed in https://zed.dev/docs/configuring-zed have changed their default value compared to what is documented. There are also a fair amount missing entirely from this page. I had to look at the default setting file to find them instead. Rust-analyzer automatically generates the docs for all settings it has from the type definitions in the source code itself and also generates the preference list in the vscode extension metadata from the same type definitions. Maybe Zed could do the same. Or if that is not possible it could have a check that verifies that the settings in the source code and the docs are in sync with each other.

### Environment

N/A

**Comment by notpeter** [comment]
This is a known issue.  There has been some work to automate generation of documentation but it is not yet completed.
- https://github.com/zed-industries/zed/pull/16554

So it's on our radar, but just hasn't gotten done. Thanks for reporting.
