### ISSUE TITLE
crash after clicking on "Prompt Library" inside "Assistant Menu"

### ISSUE THREAD

**Issue by norflin321** [zed-industries/zed#20369]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

crash after clicking on "Prompt Library" inside "Assistant Menu"

https://github.com/user-attachments/assets/658e5aa8-dc02-4ffd-87e6-89fd7a524680

### Environment

Zed: v0.161.0 (Zed Preview)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/user-attachments/files/17667134/Zed.log)
[details.txt](https://github.com/user-attachments/files/17667147/details.txt)

```
2024-11-07T20:09:11.998245+03:00 [ERROR] {
  "thread": "main",
  "payload": "index out of bounds: the len is 0 but the index is 0",
  "location_data": {
    "file": "crates/gpui/src/key_dispatch.rs",
    "line": 516
  },
  "backtrace": [
    "backtrace::capture::Backtrace::create",
    "backtrace::capture::Backtrace::new",
    "zed::reliability::init_panic_hook::{{closure}}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::panicking::panic_bounds_check",
    "gpui::key_dispatch::DispatchTree::dispatch_path",
    "gpui::key_dispatch::DispatchTree::context_path",
    "gpui::window::WindowContext::bindings_for_action",
    "ui::components::keybinding::KeyBinding::for_action",
    "<assistant::prompt_library::PromptLibrary as gpui::element::Render>::render",
    "gpui::view::any_view::render",
    "<gpui::view::AnyView as gpui::element::Element>::request_layout",
    "gpui::element::Drawable<E>::request_layout",
    "<gpui::element::Drawable<E> as gpui::element::ElementObject>::layout_as_root",
    "gpui::window::WindowContext::draw",
    "gpui::window::Window::new::{{closure}}::{{closure}}",
    "gpui::window::Window::new::{{closure}}",
    "gpui::platform::mac::window::display_layer",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "gpui::app::App::run",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace",
    "std::rt::lang_start::{{closure}}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.161.0",
  "release_channel": "Zed Preview",
  "os_name": "macOS",
  "os_version": "14.6.1",
  "architecture": "aarch64",
  "panicked_on": 1730999351998,
  "system_id": "c33c2076-7748-4946-8e0e-fb4e9fb26230",
  "installation_id": "32f199fa-f925-4a81-90e7-31437d117f9b",
  "session_id": "5cef2da6-900f-4bac-8fad-0e53b544590a"
}
```

**Comment by notpeter** [comment]
Can you provide a copy of your keymap?

**Comment by Moshyfawn** [comment]
> 1. Which base keymap do you use (vscode (default), jetbrains, atom, textmate)
> 2. Do you have vim mode enabled?
> 3. Can you paste a copy of your user keymap?

1. vscode (default)
2. No
3. `[]`

**Comment by norflin321** [comment]
@notpeter 
[keymap.json](https://github.com/user-attachments/files/17669814/keymap.json)
[settings.json](https://github.com/user-attachments/files/17669815/settings.json)

**Comment by notpeter** [comment]
Thanks. I can reproduce.  If I delete my `~/.config/zed/prompts` directory the newly created one crashes Zed Preview (but not Zed Stable).  My old `prompts` runs find in either.

**Comment by notpeter** [comment]
I believe this was fixed in the Zed Preview released today with this reversion:
- https://github.com/zed-industries/zed/pull/20367

Thanks for reporting.

**Comment by norflin321** [comment]
it is fixed for me, thanks
