### ISSUE TITLE
Layout shift with 3-character password in remote server field

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#20381]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Entering a 3-character password in the remote server field causes the second asterisk to shift upwards.

1. Open the Remote Server dialog _(Command Palette > `projects: open recent` > `Remote Server` > `Connect New Server`)_.
2. `ssh` into a remote server with a password.
3. Enter a 3-character password.
4. Observe the second asterisk shift upwards.

### Environment

Zed: v0.162.0 (Zed Nightly 083f06322d10b0187da39ab1de0fe0ca4e4f94cd)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/f2ff6d74-412e-40ba-9f3a-312ff81ce36e">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by ConradIrwin** [comment]
@Moshyfawn do you have a *** ligature in your font by any chance?

**Comment by Moshyfawn** [comment]
> @Moshyfawn do you have a *** ligature in your font by any chance?

It appears to be the case! I'm on a fresh system install, so I'm using the default Zed font, which seems to be the Zed Plex Mono font 🤔

**Comment by notpeter** [comment]
Yeah. Zed Plex Mono includes a `***` ligature by default.
I don't know if there's a way in gpui to conditionally disable ligatures.
We don't show ligatures in Terminal, we shouldn't here either.

**Comment by ConradIrwin** [comment]
Oops, I hadn't realized I'd been running with a non-default font. Thanks for the heads up!
