### ISSUE TITLE
System dialog appears on failed remote server reconnection attempts

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#20380]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the connection to the remote server is lost, an in-editor dialog is shown. If reconnection fails, a system dialog appears, which is inconvenient _(and might've lead to loosing untitled buffers, but I couldn't reliably reproduce that)_.

### Environment

Zed: v0.162.0 (Zed Nightly 083f06322d10b0187da39ab1de0fe0ca4e4f94cd)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

| Attempt # | Dialog type |
|-------------|------------|
| 1           | <img width="1138" alt="image" src="https://github.com/user-attachments/assets/1de8e5b4-62f1-40a9-8f46-50a69e222bc9"> |
| 2           | <img width="1136" alt="image" src="https://github.com/user-attachments/assets/f8a8c1cd-b60a-4bf8-8d8b-5b2913419584"> |

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by ConradIrwin** [comment]
:+1: I know @iamnbutler is thinking about a way to remove the system dialogues from Zed.

Unsaved changes are persisted locally, so you should be ok (though I agree it's scary!). Open to suggestions on making the error message clearer.
