### ISSUE TITLE
Zed terminal doesn't open when docked right

### ISSUE THREAD

**Issue by omennia** [zed-industries/zed#20388]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the default zed behaviour for the dock:
`
"terminal": {
    "dock": "bottom"
 }
`
I can use cmd+j (or ctrl+j on linux) to toggle the terminal.
I prefer to have the terminal on the right, so I changed it to:
`
"terminal": {
    "dock": "right"
  }
}
`
But cmd+j no longer toggles the terminal.
Am I getting something wrong? 

I reproduced the behaviour on macOS and Linux Mint.

Thanks

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/8cc3ce1f17a313d60589b8d87207efcfb4100c90/assets/keymaps/default-macos.json#L420-L422

There are multiple docks, and each of them is toggled with a separate default keybinding.
