### ISSUE TITLE
SFTP Sync

### ISSUE THREAD

**Issue by QarthO** [zed-industries/zed#20398]
### Check for existing issues

- [X] Completed

### Describe the feature

With the introduction of remote developmenet, I would love an alternative approach, that uses SFTP. This would let you sftp into a remote and view the files. Letting you sync a temp local directory allowing you to modify and create files that you can save/push to the remote (via SFTP)

This would be similar to the vs code extension https://marketplace.visualstudio.com/items?itemName=Natizyskunk.sftp

This would be helpful for remotes where we don't have the ability to install a zed remote server with the current remote development implementation.

### Environment

Zed: v0.159.10 (Zed)
OS: macOS 15.1.0
Memory: 24 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Sorry, we are unlikely to add support to Zed whereby you can automatically sync changes from a local folder with a remote host over SFTP.  Synchronizing with remote folders is a non-trivial problem (deletion propagation, conflict resolution, detection of files changed remotely, synchronizing `.git`, platform specific `node_modules`, etc).

As a result, it's not something we plan to implement in the near future. Thanks for reporting.

**Comment by mhomeister** [comment]
In most cases i think, a remote treeview would be enough, open the file, edit it, saving pushes it back. No need to resolve Class declarations and so on. My workflow mostly pushes to github but on daily wordpress website management tasks, sshing into a managed server and change the wp-config or other files would be nice and easy.

**Comment by d0sse** [comment]
It would be nice to have this feature, even just to do a diff-remote with the production version of the file, even without edit or replace.
