### ISSUE TITLE
Ability to hide the open recent projects button from the settings

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20413]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="291" alt="Screenshot 2024-11-08 alle 14 42 38" src="https://github.com/user-attachments/assets/cb2ef779-833d-47a3-8225-a09c48d2b303">
<img width="222" alt="Screenshot 2024-11-08 alle 14 42 51" src="https://github.com/user-attachments/assets/cc406e96-e3ee-4b9a-b178-209692f2fc04">

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
I have no idea what is being requested here.
