### ISSUE TITLE
[Windows] "zed ." command opens path wrongly 

### ISSUE THREAD

**Issue by DarkSavci** [zed-industries/zed#20421]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When running the `zed .` command on Windows, the expected behavior is to open the directory at the specified path (e.g., `C:\Users\darks\projects\tezcoz-mobile-app`). However, the command opens an incorrect path format, specifically:

```plaintext
Microsoft.PowerShell.Core\FileSystem::\\?\C:\Users\darks\projects\tezcoz-mobile-app
```

This incorrect format causes multiple issues, including:

1. **#18371** - Multiple open and closed terminals at startup.
2. **#19866** - `cd` command issues when using the PowerShell (`pwsh`) shell.

**Additionally**
- Using the "Open Project" option in the UI functions as expected and opens the path correctly, which indicates that the issue is specific to the `zed .` command when executed in the PowerShell environment on Windows.
- View the logs for more info

**Steps to Reproduce**

1. Open PowerShell.
2. Run `zed .` with the intended project path.
3. Observe the path format error.

**Expected Behavior**

The `zed .` command should open the project directory directly at `C:\Users\darks\projects\tezcoz-mobile-app` without the prefixed `Microsoft.PowerShell.Core\FileSystem::\\?\` format.

### Environment

Zed: v0.158.2 (Zed)
OS: Windows 10.0.22631
Memory: 15.9 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6700 XT || AMD proprietary driver || 24.9.1 (AMD proprietary shader compiler)

### If applicable, attach your Zed.log file to this issue.

[https://paste.ubuntu.com/p/N5nNhnfhBF/](https://paste.ubuntu.com/p/N5nNhnfhBF/)

**Comment by JunkuiZhang** [comment]
Dup of #19866, and #18371 has nothing related to this.
