### ISSUE TITLE
Padding select element from file

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20420]
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the second image `WebStorm` puts a `padding`, instead of taking all the space like `zed` does when a file is selected.

<img width="377" alt="Screenshot 2024-11-08 alle 16 50 23" src="https://github.com/user-attachments/assets/b06b2503-a4fe-458d-a87e-b6e442969d28">
<img width="317" alt="Screenshot 2024-11-08 alle 16 50 15" src="https://github.com/user-attachments/assets/7a488a31-16c1-489b-9704-60ef4ee8858c">

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
There is much room for improvement with the selection rectangle in the project panel.  A suggestion to make it narrower is insufficient to keep open as a dedicated issue.

Thanks for reporting.
