### ISSUE TITLE
Go to next match using ⌘ G doesn't work after `editor: open file` with G F

### ISSUE THREAD

**Issue by theherk** [zed-industries/zed#20437]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The title is a fairly complete description.

I one does a workspace wide search, ⌘ G and ⌘ ⇧ G will jump between match excerpts. If one then uses G F to go to the file of one of those excerpts, then comes back to the multibuffer, the shortcuts for jumping between matches no longer works. The arrow buttons in the search interface still work, but he shortcuts don't.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @theherk, I'm unable to reproduce this on macOS. Would you be able to provide a video showing the issue? I might be not quite getting something right on my end.

**Comment by theherk** [comment]
Somewhat irritatingly, but also a good thing I guess... I cannot replicate it now either. I have no idea what was going on, but I can't get into the same state. Sometimes I need `G F` to go to the file of an excerpt, but I can't recall when, but in most cases I use `G <space>`, and in that case this is not an issue. If I can recall when I need to use `G F` maybe, I'll follow up. In the meantime, I'll close this to get it out of the already massive queue. :) Sorry for the trouble.
