### ISSUE TITLE
Wrong element focused when deleting items in project panel

### ISSUE THREAD

**Issue by neunato** [zed-industries/zed#20444]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After removing a file/folder from sidebar, keyboard focus is switched to the first entry in the panel. This makes deleting multiple files very impractical.

Solution would be to focus the next file after the deleted one.

### Environment

Zed: v0.160.7 (Zed)
OS: Linux X11 arch unknown
Memory: 62.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 with Max-Q Design || NVIDIA || 565.57.01

**Comment by 0xtimsb** [comment]
make sense. i'm picking this.
