### ISSUE TITLE
Search restores deleted files on focusing search tab

### ISSUE THREAD

**Issue by atassis** [zed-industries/zed#20462]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open search tab
2. Find a text in a wanted file with the search
3. delete the wanted file
4. Switch focus from and back to search
5. Deleted file is restored back the same it was during the search (not quite sure, but looks like it)

### Environment

Zed: v0.162.0 (Zed Dev 0a28800049e2a7e9093e870c5a4e4ad83aa80430)
OS: Linux Wayland fedora 41
Memory: 30.6 GiB
Architecture: x86_64
GPU: AMD Radeon 680M (RADV REMBRANDT) || radv || Mesa 24.2.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot From 2024-11-09 20-45-33](https://github.com/user-attachments/assets/9c910a97-ea92-436b-9ce9-1a4cfb9038f5)
After making a screenshot, a file has created by itselves
![Screenshot From 2024-11-09 20-45-41](https://github.com/user-attachments/assets/2dbbc528-7ad9-4904-a44a-efe952e821dc)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

2024-11-09T20:44:07.199879337+03:00 [INFO] Language server with id 14 sent unhandled notification telemetry/event:
{
  "eventName": "KeyHoverProvider",
  "properties": {
    "isActivationEvent": "false",
    "result": "Succeeded"
  },
  "measurements": {
    "count": 1,
    "durationMu": 4.22,
    "durationSigma": 0,
    "durationMedian": 68
  },
  "groupingStrategy": "eventNameAndProperties"
}
2024-11-09T20:44:11.91876064+03:00 [INFO] Language server with id 7 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/atassis/repositories/flipping-project/apps/frontend/src/features/projects/creation/form-breadcrumbs.tsx"
  }
}
2024-11-09T20:44:21.800518223+03:00 [INFO] new;
2024-11-09T20:44:21.801123367+03:00 [INFO] keep_updated;
2024-11-09T20:44:23.842120176+03:00 [INFO] Language server with id 7 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/atassis/repositories/flipping-project/apps/frontend/src/features/projects/creation/team-form.tsx"
  }
}

</details>

**Comment by JosephTLyons** [comment]
Not the same issue, but similar bug to:

- https://github.com/zed-industries/zed/issues/9101

**Comment by mgsloan** [comment]
With #20742, autosave of a multibuffer won't do anything if the multibuffer involves deleted files (or otherwise conflicted files, as before)
