### ISSUE TITLE
Empty panel while switching projects after moving terminal 

### ISSUE THREAD

**Issue by aretrace** [zed-industries/zed#20484]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When working in one project where the terminal was moved over from the bottom panel to a top-level tab, if you switch projects, where the terminal bottom panel would usually be you instead fine a blank (not removable) section of space.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/16f82166-89f3-487e-b432-9d4ba55c6b59">

**Comment by Calerid** [comment]
I attempted to reproduce this issue, and I was unable to get it to occur. Attempted to switch between the projects, and open new projects with the terminal as a tab. Each time the terminal would render correctly. 

Environment:
Zed: 0.160.7
OS:  Sonoma 14.7
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Yuck. That's not good. Happy to reopen if you (or anyone else) can reproduce, but for the moment closing as unactionable.
