### ISSUE TITLE
Have `Complete current statement` for Rust (like what RustRover has)

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/zed#20483]
### Check for existing issues

- [X] Completed

### Describe the feature

In [RustRover](https://www.jetbrains.com/rust/), you can do this:

<img width="953" alt="image" src="https://github.com/user-attachments/assets/15e3633c-0d88-49f0-b441-78b650ce5eb8">

Which automatically completes the line, so from this:

`println!("test")`

it turns it into

`println!("test");`

It's super useful and I wish Zed had it too.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.2.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

I just want it as keybind ideally so I can fast complete my statements (mostly so I don't have to manually write out the `;` in rust.

**Comment by Calerid** [comment]
Hey just my personal opinion - this sounds like a good idea for an extension - not a core feature. Having auto completion isn't everyone's idea of ideal. More often than not, I have it get in my way. Having potential errors caught/recommendations is nice; however, when my editor attempts to complete things for me it gets annoying. I picture something like this attempting to finish out what it parses as a statement, when I am attempting to use method chains on separate lines.

**Comment by notpeter** [comment]
This is the sort of thing that would likely be implemented as an LSP action for each individual language, since the LSP is aware of the current language and syntax and how to parens/brackets in need of closing.

Closing in favor of this upstream rust-analyzer issue:
- https://github.com/rust-lang/rust-analyzer/issues/14765
