### ISSUE TITLE
Save as / Overwrite existing file name with `use_system_path_prompts` = false fallback picker

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#20496]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="498" alt="image" src="https://github.com/user-attachments/assets/a823bbf3-7e4d-409d-b822-b6f945f6152e">

<img width="295" alt="image" src="https://github.com/user-attachments/assets/abcf4e2d-b182-4272-9353-d758ca94ae72">

Failed to save new buffer in keyboard-first picker if the file is already existed.

One would expect a confirm box instead.

### Environment

Zed: v0.161.1 (Zed Preview)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
I can reproduce with `"use_system_path_prompts": false,` in my settings and have frequently run into this as well.

**Comment by carlos-gn** [comment]
@notpeter can you share the steps to reproduce it? Ill try to fix this one

**Comment by notpeter** [comment]
I believe Conrad and I may have fixed this with some improvements for how working directories are handled using the fallback picker. If someone is able to reproduce this issue with a current Zed, please comment below with reproduction steps and I am happy to reopen.

Thanks for reporting.
