### ISSUE TITLE
Shell Language - Syntax Highlight breaks with substring matching

### ISSUE THREAD

**Issue by GrabbenD** [zed-industries/zed#20502]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Substring matching breaks syntax highlight in ZED _(which doesn't happen with VSCode nor GitHub Markdown)_. 

Bash 5.2 enables substring matching by default (see [patsub_replacement](https://www.gnu.org/software/bash/manual/bash.html#The-Shopt-Builtin)). This is particularly useful for injecting strings, but _only_ when a _$variable_ is present. In this example `--volume=/tmp/mnt:/mnt` wont be printed unless `export MOUNTS` is uncommented:

```shell
#!/usr/bin/env bash

export MOUNTS=(
  #/tmp/mnt:/mnt
)

export PARAMS=(
  "${MOUNTS[@]/*/'--volume='&}"
  --tty='1'
  --interactive='1'
)

podman run "${PARAMS[@]}" archlinux
# podman run --tty=1 --interactive=1 archlinux

```

---

### Reproducible example:

```shell
PARENT_FUNC() {
  local LIST=(1 2)
  export ITEMIZED=(
    #"${LIST[@]/*/'prefix'&'suffix'}" # OK
    "${LIST[@]/*/'prefix'&}"          # BREAKS HIGHLIGHT
  )

  NESTED_FUNC() {
    echo "${ITEMIZED[@]}"  # prefix1 prefix2
  }
}

PARENT_FUNC
NESTED_FUNC
```

---

### Environment

Zed: v0.159.7 (Zed)
OS: Arch Linux Wayland
Memory: 62.6 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7900 XT (RADV NAVI31) || radv || Mesa 24.1.3-arch1.1

---

### If applicable, add mockups / screenshots to help explain present your vision of the feature

ZED without any extensions:

* OK
  ![highligh_ok](https://github.com/user-attachments/assets/701d03ab-7da6-4fbe-bd67-3dc2899b708a)

* BROKEN
  ![highlight_broken](https://github.com/user-attachments/assets/6f7519dc-b64f-41ec-b254-773faa8a6818)

_For reference, I've also tried installing [d1y/bash.zed (extensions/basher)](https://github.com/zed-industries/extensions/pull/412) & [rburmorrison/shell.zed (extensions/shell)](https://github.com/zed-industries/extensions/pull/1078) but either behaves identically as ZED with no extensions_

**Comment by SomeoneToIgnore** [comment]
> which doesn't happen with VSCode nor GitHub Markdown

They use different approaches to highlights, and whatever tree-sitter grammar in Zed is used, it seems to have issues with it.
It seems that this report should go to https://github.com/tree-sitter/tree-sitter-bash and not here.

**Comment by GrabbenD** [comment]
https://github.com/tree-sitter/tree-sitter-bash/issues/279
