### ISSUE TITLE
Automatic folding of directories doesn't match default setting

### ISSUE THREAD

**Issue by tdjlkk** [zed-industries/zed#20511]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just did a fresh installation of MacOS, and Zed with it, and noticed that by default (without the **auto_fold_dirs** setting specified) the folders are folded, even though the default says the folders shouldn't fold. When I manually set **auto_fold_dirs** to **false**, they actually don't fold, and when I set it to true they fold.

The issue is either with the description of the **auto_fold_dirs** option, or the functionality not obeying the default setting.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/42f04f97-b0c0-4c27-8e81-2871a16e275e)

**Comment by SomeoneToIgnore** [comment]
> even though the default says the folders shouldn't fold

This is not correct, as the defaults are set to fold now, can you point to that place (or fix it in the PR)?

**Comment by tdjlkk** [comment]
Of course, should be visible on the image below - CMD + Space on the setting, and it says **Default: false**.

![image](https://github.com/user-attachments/assets/5bef2a20-8e98-4c12-a198-9433cd307760)

**Comment by SomeoneToIgnore** [comment]
Thanks, overlooked rustdocs with this part, fixed in https://github.com/zed-industries/zed/pull/20517
