### ISSUE TITLE
Tasks, $ZED_FILE and $ZED_DIRNAME doesn't escape spaces. 

### ISSUE THREAD

**Issue by Dubonteco** [zed-industries/zed#20521]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed's task variable $ZED_FILE, $ZED_DIRNAME doesn't properly escape directory spaces. 

<img width="1440" alt="Screenshot 2024-11-12 at 01 02 59" src="https://github.com/user-attachments/assets/f7e8cb22-d0b9-40d8-b579-a6fefc5d006f">
<img width="1440" alt="Screenshot 2024-11-12 at 01 03 18" src="https://github.com/user-attachments/assets/83509ba2-954b-4e89-8470-2ef2f2c8bc2f">

Here are my tasks :

<img width="1440" alt="Screenshot 2024-11-12 at 01 03 56" src="https://github.com/user-attachments/assets/e2643483-0909-47c8-898a-6f9dfaa73964">

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
In the current task implementation, these variables are passed to the task's process environment not interpolated via Zed, so you will need to explicitly escape them when using a simple `command` definition.

If you pass them via `args` instead they will escape just fine.

```json
  {
    "label": "stat current file",
    "command": "stat",
    "args": ["${ZED_FILE}"]
  }
```

<img width="1820" alt="Screenshot 2024-11-15 at 10 59 48" src="https://github.com/user-attachments/assets/9f3a621a-5e30-4cba-8754-5c351b5c18e7">

Thanks for reporting, I've updated the [Zed Tasks Docs](https://zed.dev/docs/tasks) to explicitly cover this.
