### ISSUE TITLE
add `pane: close all other items`

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#20541]
### Check for existing issues

- [X] Completed

### Describe the feature

it's a common scenario where i've been working on something and have a bunch of open buffers, so many that i have a hard time finding the one i want again. at this point i want to close all of them except for the current one.

### Environment

Zed: v0.160.7 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

**Comment by SomeoneToIgnore** [comment]
We have this
https://github.com/zed-industries/zed/blob/181c3724aa99e67ebc5f8147dce8d6ee2f77276d/assets/keymaps/default-linux.json#L256
