### ISSUE TITLE
Keybinding bind keys to multiple commands 

### ISSUE THREAD

**Issue by F8RZD** [zed-industries/zed#20556]
### Check for existing issues

- [X] Completed

### Describe the feature

I was looking for a feature to bind a key to multiple commands for example I want to when I press `ctrl+<backtick>` saveAll files and also toggle focus on terminal

reading through the docs I didn't find anything about binding to multiple commands

But I were able to hack my way through using this example:

```json
[
  {
    "bindings": {
      "ctrl-3": "terminal_panel::ToggleFocus",
      "ctrl-4": "workspace::SaveAll",
      "ctrl-`": ["workspace::SendKeystrokes", "ctrl-4 ctrl-3"]
    }
  }
]

```

Points of my issue:

Will such functionality be a part of zed?
Is there a better solution to this currently?
And maybe help out someone who is looking to hack their way to achieve same kind of keybindings

### Environment

Zed 0.160.7

**Comment by JosephTLyons** [comment]
Related:

- https://github.com/zed-industries/zed/issues/17710
