### ISSUE TITLE
Can't run REPL for Python

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#20565]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't running Python code using the built-in Jupyter REPL. I can see the Jupyter kernel with `repl:sessions` but I don't find `repl:run` command. I tried using my custom keybind or clicking on the REPL icon but it does nothing.

<img width="745" alt="image" src="https://github.com/user-attachments/assets/bc628c9d-9e72-4973-ad07-58c1503db858">

### Environment

Zed: v0.161.1 (Zed Preview)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by rgbkrk** [comment]
The upcoming preview release (tomorrow) adds support for choosing the kernel based on your python environments.

**Comment by rgbkrk** [comment]
Oh, that `repl:run` issue is something that needs to be cherry picked from https://github.com/zed-industries/zed/pull/20445

**Comment by Tom-Boscher** [comment]
Oh I will test with the next preview release so

**Comment by Tom-Boscher** [comment]
> The upcoming preview release (tomorrow) adds support for choosing the kernel based on your python environments.

@rgbkrk Will it be possible to use a Jupyter remote kernel?

**Comment by seandaddy** [comment]
I came up with exactly same issue. Please let me know if you find the solution. Thanks in advance.

**Comment by rgbkrk** [comment]
@seandaddy fixes went out for both preview and stable. Run `auto update: check` to pull a fresh install.

**Comment by seandaddy** [comment]
It works as a charm. Thanks a lot.

**Comment by Tom-Boscher** [comment]
Works great on my side, thanks!
