### ISSUE TITLE
Request: Ability to disable trimming of blank lines

### ISSUE THREAD

**Issue by trbabb** [zed-industries/zed#20560]
### Check for existing issues

- [X] Completed

### Describe the feature

At least in C++, I [can't find a way](https://github.com/zed-industries/zed/discussions/18558) to stop Zed from clearing blank lines. This is against the style of my codebase, and I find it pretty annoying to have the editor change the text in ways I can't control. Setting `"format_on_save": "off"` in the settings did not seem to stop this behavior.

It would be great if this could be disabled with a config option!

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: x86_64

**Comment by neunato** [comment]
The setting you're after would be `remove_trailing_whitespace_on_save`.

**Comment by JosephTLyons** [comment]
I *believe* what @neunatto said that is the case. That setting trims trailing whitespace, but for all lines, and there isn't currently a way to customize it to only apply to to just blank lines. That being said, if having the trailing whitespace on non-blank lines trimmed is fine with your codebase, then this would work for you.

**Comment by trbabb** [comment]
Turning off the trailing whitespace setting will suffice I think— trailing whitespace isn't really much of a problem.

**Comment by teohhanhui** [comment]
Tested with the latest stable (`v0.191.7`). The `remove_trailing_whitespace_on_save` setting only prevents trailing whitespace(s) from being removed when the line is not the last line, and setting it still does not keep blank lines at the end of file.

**Comment by notpeter** [comment]
@teohhanhui I can reproduce and have filed this:
- https://github.com/zed-industries/zed/issues/33164
