### ISSUE TITLE
Error indicators in project panel should use different border for selected files

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/zed#20572]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In #18182 error indicators were added. For the selected file, the border used for the error icon is of  an incorrect color

<img width="189" alt="Screenshot 2024-11-13 at 10 26 35" src="https://github.com/user-attachments/assets/146e2265-cdf3-4e08-9d73-4c26d488d375">

### Environment

Zed: v0.162.0 (Zed Nightly 55cd99cdc4d22bf82c0a59d8fa76f4ab9b85370c)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

**Comment by nilskch** [comment]
I can change that later if this is not intentional?

**Comment by WeetHet** [comment]
> I can change that later today if this is not intentional?

I think it doesn't look good, but I'd prefer to hear @danilo-leal's opinion on it

**Comment by danilo-leal** [comment]
You're referring to the white stroke around the x, right? If that's the case, this is a bit challenging at the moment because these different states in the project panel items (like hover or selection) use colors that leverage opacity, whereas the diagnostic icon uses a solid color. If we use exactly the same token as we use for the states, the knockout effect wouldn't quite work.

That original PR was merged because I think we're in a good spot with icon positioning, API to do the icon knockout effect, and, generally, the functionality. But there's still room to make this perfect, which includes possibly refining the color tokens we use for project panel items, ensuring the knockout thing always works well.

Does this make sense?

**Comment by WeetHet** [comment]
> If that's the case, this is a bit challenging at the moment because these different states in the project panel items (like hover or selection) use colors that leverage opacity, whereas the diagnostic icon uses a solid color. If we use exactly the same token as we use for the states, the knockout effect wouldn't quite work.

It seems like, when the file isn't in focus, the white stroke blends in with the background. Can't we update the decoration color depending on the status of the entry?
<img width="218" alt="Screenshot 2024-11-13 at 14 13 54" src="https://github.com/user-attachments/assets/ce869180-b0c6-44f8-a15a-2b3abb18cefa">

**Comment by danilo-leal** [comment]
We can yeah, but it's what I said—other states of the project panel item use transparent colors, which means the icon stroke wouldn't blend perfectly as they do in the resting/default state. The solution seems to be _not_ in the color used by the icon, but rather in the color token itself.

**Comment by WeetHet** [comment]
> We can yeah, but it's what I said—other states of the project panel item use transparent colors, which means the icon stroke wouldn't blend perfectly as they do in the resting/default state. The solution seems to be _not_ in the color used by the icon, but rather in the color token itself.

Yeah, makes sense

**Comment by nilskch** [comment]
@danilo-leal not sure if I understood this correctly, but I think `item_colors.selected` needs to be `item_colors.marked_active` instead.

https://github.com/zed-industries/zed/blob/093c9cc87b052c4bdf2afc09a6d52e86eb9c7d3d/crates/project_panel/src/project_panel.rs#L2808-L2812

<img width="215" alt="Screenshot 2024-11-14 at 08 31 50" src="https://github.com/user-attachments/assets/a9aaff4f-497d-485f-a87a-d725cb260dfb">


`selected` and `default` are the same color here:


https://github.com/zed-industries/zed/blob/093c9cc87b052c4bdf2afc09a6d52e86eb9c7d3d/crates/project_panel/src/project_panel.rs#L254-L264

We still have this issue in the hover state though.

**Comment by nilskch** [comment]
I think this works pretty well. I'm going to create a PR for this tmr. I think we should fix this before https://github.com/zed-industries/zed/pull/18182 makes it into the normal release.

**Comment by danilo-leal** [comment]
Yeah, good call @nilskch. I opened up https://github.com/zed-industries/zed/pull/20723 to update the active color and remove the not used `selected` variable. Hover is trickier—curious about how you pulled it off as we don't have some akin to `is_marked`.

**Comment by nilskch** [comment]
Hey @danilo-leal, sorry for making that much noise. I love your design for the diagnostics and having the diagnostics in the project panel makes my DX so, so much better, but can we try to address this issue before https://github.com/zed-industries/zed/pull/18182 makes it into the normal release? I proposed a solution in https://github.com/zed-industries/zed/pull/20760, can you take a look at that please?
