### ISSUE TITLE
Possible to resize panels so wide it can never be resized

### ISSUE THREAD

**Issue by Explosion-Scratch** [zed-industries/zed#20593]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/338ee60a-1b75-45ba-9354-89488d1ce3b0">

I have resized the file explorer to take up the full window, but I can't undo it. I can click on files; theoretically, they're showing up, but I can't fix this. Whenever I open a new folder, quit and restart zed, etc it just opens like this with whichever project.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
To fix, quit Zed and run:
```
cd ~/Library/Application\ Support/Zed/db
rm -rf 0-stable
```
