### ISSUE TITLE
Disable prev and next hunk controls

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20609]
### Check for existing issues

- [X] Completed

### Describe the feature

I think it is clear from watching the videos that when there is no prev or next element the next button should be disabled.

https://github.com/user-attachments/assets/e6bad3bf-abc8-4008-bcf1-a3c7e0905f12

https://github.com/user-attachments/assets/c7a430f5-3721-40de-a2ca-aa185b4fade9

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by wanlufun** [comment]
I believe this is the default behavior, as it works the same way in VSCode.

**Comment by SomeoneToIgnore** [comment]
Also, not clear at all, as some people (like me) want to wrap around the end of the file to the next hunk, which the feature now does.
