### ISSUE TITLE
Jupyter Move controls to the right and be able to save/download image

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20601]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to be able to move the controls to the right like in git hunk, see image below and pr: #19515
and be able to save/download image.

![image](https://github.com/user-attachments/assets/fac72e3d-cc63-489a-b075-20cb66874adb)

Git hunk:
![image](https://github.com/user-attachments/assets/037e74c9-1f1a-413e-817f-92ac5ba2a61e)

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
We do not intend to implement these changes at this time.
Thank for your suggestions.
