### ISSUE TITLE
ssh: Host key verification failed

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#20604]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps reproduce:
```
rm ~/.ssh/known_hosts
zed ssh://localhost
```

Workaround: `ssh` via terminal and manually say `yes` to this prompt:
```
The authenticity of host 'localhost (::1)' can't be established.
ED25519 key fingerprint is SHA256:cw5IJnsFlqwwSgfdAXRf/LFlURfQ1TT7lagyapEro4U.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
```

Expected: Be able to accept host key from within zed.

### Environment

Zed: v0.162.0 (Zed Dev 3a319e6cbe466fc21c3645e2dcaccee47af60de5)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="268" alt="Screenshot 2024-11-13 at 10 54 26" src="https://github.com/user-attachments/assets/5f982e24-bcd9-4a28-85c0-b0150be0582f">

### If applicable, attach your Zed.log file to this issue.

```
[2024-11-13T10:53:59-05:00 ERROR recent_projects::ssh_connections] Failed to open project: failed to connect: Host key verification failed.
```

**Comment by notpeter** [comment]
Another adjacent issue. Steps to reproduce:
```
rm ~/.ssh/authorized_keys
zed ssh://localhost
zed ssh://localhost/~/zcode/zed
```

The first yields this:
<img width="263" alt="Screenshot 2024-11-13 at 11 02 15" src="https://github.com/user-attachments/assets/000fbe12-5c66-4ba9-876d-81433407b9d1">

The second yields this:
<img width="262" alt="Screenshot 2024-11-13 at 11 03 37" src="https://github.com/user-attachments/assets/230cf333-8810-4ed0-aeba-e43d22f87a7c">

**Comment by ConradIrwin** [comment]
@notpeter you should see this in that scenario:

<img width="1136" alt="Screenshot 2024-11-13 at 18 33 27" src="https://github.com/user-attachments/assets/d1ee9df4-ea3f-4c80-b69f-8ad731248eab">

From the second error message it seems like something is not working for you with the way we set up askpass. If you have time tomorrow let's look into this together; I'm curious what's different on your machine :D .

**Comment by SomeoneToIgnore** [comment]
Related: https://github.com/zed-industries/zed/issues/20634
