### ISSUE TITLE
Lateral spacing of line numbers

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20608]
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the images, the lateral spacing of the line numbers is too much, maybe if there are run buttons it is better to place them more internally?

| Zed    | Webstorm |
| -------- | ------- |
| <img width="552" alt="Screenshot 2024-11-13 alle 17 06 50" src="https://github.com/user-attachments/assets/ccedc468-3a6c-463b-8d98-f61770c4103a">  | <img width="540" alt="Screenshot 2024-11-13 alle 17 07 06" src="https://github.com/user-attachments/assets/8dc67f9a-c248-4a9c-ac81-4adc4029a08b">  |

<img width="353" alt="Screenshot 2024-11-13 alle 17 18 39" src="https://github.com/user-attachments/assets/ef648630-e2ce-45bd-884d-90bdf069ba70">

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
>  the lateral spacing of the line numbers is too much

This a personal design opinion.
The work suggested is undefined and unscoped. Closing
