### ISSUE TITLE
hunk controls increase the size of the controls

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20602]
### Check for existing issues

- [X] Completed

### Describe the feature

The icon size seems too small.
It would be helpful to be able to increase the size

<img width="118" alt="Screenshot 2024-10-24 alle 12 28 59" src="https://github.com/user-attachments/assets/737ba192-9348-4c1f-a50e-3533b5060c0b">
<img width="1440" alt="Screenshot 2024-10-24 alle 12 30 18" src="https://github.com/user-attachments/assets/89000cc5-c9d7-4a83-a5e1-30302a0e7822">

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
We are not currently seeking design feedback about the size of controls.
