### ISSUE TITLE
Button size run too small

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20610]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="71" alt="Screenshot 2024-11-13 alle 17 36 15" src="https://github.com/user-attachments/assets/289c87be-fd6c-40f0-9bbc-51b434e3ed7f">

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
We are not currently seeking design feedback about our choice of icons. Hopefully at some point in the futrue Zed will support icon customization via extension or other means, so I'm going to close in favor of:
- #8843 

Thanks for reporting.
