### ISSUE TITLE
Problems with using Claude 3.5 sonnet in the Assistant Panel

### ISSUE THREAD

**Issue by goodlux** [zed-industries/zed#20633]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi - I'm trying to use Claude 3.5 Sonnet in the Assistant panel. I have both an API key with Anthropic, I also have paid for credits on Zed.dev website.  

 My ANTHROPIC_API_KEY is set in .env file, and I can use this with other libraries like liteLLM, etc without issue.

For some reason, I'm not able to connect to Claude 3.5 though Zed. I've tried various settings, 

### Environment

![Screenshot 2024-11-13 at 2 33 38 PM](https://github.com/user-attachments/assets/3e40a047-6e13-43e2-b2a3-46c702b27c65)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

In this screenshot, the tab says Claude 2, the model is reporting Claude 3, and the dropdown says Claude 3.5.

![Screenshot 2024-11-13 at 2 34 41 PM](https://github.com/user-attachments/assets/297b0440-e8ff-4245-a004-2fbe1326ece8)

In this screenshot, you can see my settings.json file. I have tried many iterations (copying directly from Zed website, changing model numbers, opening and closing Zed, etc etc. 

![Screenshot 2024-11-13 at 2 37 46 PM](https://github.com/user-attachments/assets/56d3c66e-628e-4996-8b10-0b1c182c949c)

Sometimes I get Claude 2, sometimes 3. Selecting different models from the dropdown has mixed results, but never Claude 3.5 Sonnet .... in other applications, 3.5 is always very straightforward about his model number and date. This is with completely fresh settings, selecting Claude 3.5 from the dropdown, then restarting (i get Claude 3 sonnet this time instead of 3.5)

![Screenshot 2024-11-13 at 2 52 51 PM](https://github.com/user-attachments/assets/f1c0542b-0980-4cb2-a9b8-3b545ae2d079)

Logfile from this last open is attached.

**Comment by goodlux** [comment]
tried attaching log, but it was too big and couldn't post.

**Comment by goodlux** [comment]
Update. I've spent hours trying to debug this, but was not able to even get Claude 3.5 in any version or format. I have Zed.dev, anthropic, and Github copilot_chat .... paying for all of these but can't get a recent anthropic model. I took the whole debugging thread and fed in into the Claude website for a summary, here goes:

Comprehensive Update on Claude Integration Issues
1. Model Name & Version Inconsistencies
Current Names Found in Zed:

Default settings reference: "claude-3-5-sonnet" (incorrect/outdated)
Settings.json auto-populates: "claude-3-5-sonnet-latest" when using zed.dev provider
Dropdown shows multiple variations of Claude 3.5 Sonnet without clear versioning

Correct Model Names (per Anthropic's documentation):

Claude 3.5 Sonnet: claude-3-5-sonnet-20241022 (or alias claude-3-5-sonnet-latest)
Claude 3 Sonnet: claude-3-sonnet-20240229
Claude 3 Haiku: claude-3-haiku-20240307
Claude 3 Opus: claude-3-opus-20240229

2. Provider Configuration Issues

Direct Anthropic API connections result in 400 Bad Request errors
Zed.dev provider works but connects to Claude 3 instead of 3.5
API URL configuration doesn't seem to affect connection behavior

3. Context and Persistence Problems

Model selection persists across contexts unexpectedly
Settings changes require new contexts to take effect
Sometimes changes don't take effect even with new contexts
Got stuck on GPT-4 despite Claude being configured as default

4. UI/Settings Discrepancies

Dropdown shows multiple versions of same model
Settings.json changes don't always reflect in actual connections
Default provider settings seem to override custom configurations
Model selection in dropdown doesn't always match active connection

5. Documentation Gaps

Unclear how to properly configure direct Anthropic connection
No documentation about context persistence behavior
Ambiguous model naming in dropdown vs configuration

Bug Impact

When connection fails, appears to fall back to Claude 3 Sonnet without indicating the fallback
Multiple entries in dropdown don't clearly indicate which version string is being used
The zed.dev provider seems to use different model strings than direct Anthropic connections
Settings and UI show inconsistent model naming patterns across different parts of the interface
Version mismatch appears to be contributing to the 400 Bad Request errors when attempting direct Anthropic API connections

Recommendations

Update default settings to reference current model versions
Fix direct Anthropic API connection issues
Make model switching behavior more predictable
Clarify relationship between settings.json and UI selections
Document context persistence behavior
Clean up duplicate model entries in dropdown

**Comment by JosephTLyons** [comment]
Hey @goodlux, you should be using Claude 3.5 Sonnet. These models typically aren't able to correctly explain what version they are. I dont know the exact details of how you might've gotten accurate results when asking a model about itself in another tool, but I'm guessing those other tools might inject some default prompt, for each LLM, that maybe provides those details in the context? I'm not sure. As far as I can tell, you are using Claude 3.5 Sonnet in Zed.

**Comment by goodlux** [comment]
Hi @JosephTLyons ... I'm doing some more testing and research on this now. The reason I believed that Zed.Dev assistant connections were NOT in fact claude-3-5-sonnet-20241022 (latest model name). Is because when I use Claude via the Anthropic HTML portal, he always is very clear that he is definitively identifies as claude-3-5-sonnet-20241022. 

When I use Zed's assistant interface, it never responds clearly, often says Claude 3, or 2, as documented here.

However, I'm running some more tests tonight, and finding that my independent connections, outside of Zed interface, using both using Anthropic SDK and liteLLM to connect show the same pattern of behavior. 

Also, I looked briefly though the Zed source code (still learning my way around) and I did see some code that specifies claude-3-5-sonnet-20241022 on main branch ... I haven't checked if that same code is 0.161.1 that I'm using yet, that was the next thing to explore.

I should say: The reason I'm digging into this so much is because I want to implement some of the "Tool Use" features via Zed assistant. For instance, I'd like to just be able to ask the assistant things like: "Please look at the repo for this project and tell me x" or use other arbitrary tools on my local system. 

When I was asking the Zed.Dev assistant who he was, and he was responding with "I'm claude 3, I don't know about Tool Use" I assumed that it wasn't actually claude-3-5-sonnet-20241022. Additionally, claude-3-5-sonnet-20241022 has a knowledge cutoff date of April 2024 (20241022 is the release date, not the training date). Since tool use was released in May of 2024, it makes sense to me now that the model might not know about these features, even though the Claude portal does. I think the Claude portal has some magic built in where it knows some things about Antropic's dev stack to help with support, maybe a LangChain implementation happening in the background. 

So the two outstanding questions I have are: 

1. Why am I having problems connecting to Anthropic directly via Zed .... is something wrong in my settings.json? (I've tried many examples on the Zed website and was never able to get this working)

2. Can I use "tool use" features via Zed.Dev? 

3. Is the intention with Zed's assistant specifically to not use or limit "tool use"?  I'm guessing this is not the case because there is an example on Zed's website that mentions it, but I could understand there might be reasons to not want to use this functionality in Assistant. 

I'm hoping not though, there are a ton of features where I can imagine "tool use" being helpful inside of Zed. I'm actually thinking about learning some more rust to try and build/prototype. For instance, it would be really amazing to have a feature where the assistant can go to the web and check recent docs for a particular version of an SDK to diagnose exactly why the SDK isn't working, or have the assistant "look" at an actual GUI interface to see what the user sees, etc. Just amazed at what these things can do!

**Comment by goodlux** [comment]
To help debug, this is the exact settings.json I'm using when trying to connect directly to Anthropic API. 

```json
{
  "assistant": {
    "version": "2",
    "enabled": true,
    "default_model": {
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20241022"
    }
  },
  "language_models": {
    "anthropic": {
      "version": "1",
      "api_url": "https://api.anthropic.com/v1/messages",
      "available_models": [
        {
          "name": "claude-3-5-sonnet-20241022",
          "display_name": "Claude 3.5 (Tool-enabled)",
          "max_tokens": 128000,
          "max_output_tokens": 2560,
          "tools": [
            {
              "name": "run_tree",
              "description": "Execute the tree command in the current directory to display the directory structure. Returns the output as a string.",
              "input_schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "description": "The directory path to start from, defaults to current directory if empty"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```
When I start a completely new window, add this in, then try, I get the following tail on my Zed logs

Last login: Sat Nov 16 04:30:58 on ttys003

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Mac-Studio:~ rob$ ~/Library/Logs/Zed/zed.log
-bash: /Users/rob/Library/Logs/Zed/zed.log: Permission denied
Mac-Studio:~ rob$ tail -f ~/Library/Logs/Zed/zed.log
  "schemaUri": "https://json.schemastore.org/pyproject.json",
  "meta": {
    "name": "PyProject",
    "description": "Python project metadata and configuration",
    "source": "catalog",
    "catalog_url": "https://www.schemastore.org/api/json/catalog.json"
  }
}
2024-11-16T04:32:06.896556-08:00 [INFO] language server 7: unregistered workspace/DidChangeWatchedFiles capability with id 1a369bab-ed37-4159-a161-892741c2cd33
2024-11-16T04:32:07.883342-08:00 [INFO] language server 7: unregistered workspace/DidChangeWatchedFiles capability with id 5e27056e-a06a-4a75-a6f6-fab106e69731

Assistant fails. When I then go back to "Zed.dev" the top part of settings.json changes to this:

```json
{
  "assistant": {
    "version": "2",
    "enabled": true,
    "default_model": {
      "provider": "zed.dev",
      "model": "claude-3-5-sonnet-latest"
    }
  },
```
This assistant works, but the newly created "Tool-Use" assistant fails with "Error interactive with language model failed to stream completion"

Tail shows:

024-11-16T04:39:03.565082-08:00 [INFO] Initializing default prettier with plugins {}
2024-11-16T04:39:03.565291-08:00 [INFO] Initializing default prettier with plugins {}
2024-11-16T04:39:03.565726-08:00 [INFO] Initializing default prettier with plugins {}
2024-11-16T04:39:03.566071-08:00 [INFO] Initializing default prettier with plugins {}
2024-11-16T04:39:03.566221-08:00 [INFO] Initializing default prettier with plugins {}
2024-11-16T04:39:03.567068-08:00 [INFO] Initializing default prettier with plugins {}
2024-11-16T04:39:03.932274-08:00 [INFO] Language server with id 10 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/rob/repos/llm_harness/pyproject.toml",
  "schemaUri": "https://json.schemastore.org/pyproject.json",
  "meta": {
    "name": "PyProject",
    "description": "Python project metadata and configuration",
    "source": "catalog",
    "catalog_url": "https://www.schemastore.org/api/json/catalog.json"
  }
}
2024-11-16T04:39:04.639826-08:00 [INFO] language server 9: unregistered workspace/DidChangeWatchedFiles capability with id c79f8e68-a664-46d6-8285-f6add18f403a
2024-11-16T04:39:05.387719-08:00 [INFO] language server 7: unregistered workspace/DidChangeWatchedFiles capability with id 1a301d55-3f58-468e-8076-b5ac761b8add
2024-11-16T04:39:05.623599-08:00 [INFO] language server 9: unregistered workspace/DidChangeWatchedFiles capability with id ebcae0a0-6270-4a11-bf04-7b5d8829e2ae
2024-11-16T04:39:17.211159-08:00 [ERROR] Other(Failed to log: 400 Bad Request)

**Comment by goodlux** [comment]
Ok, finally got antropic connection working. There's definitely something janky in the provider selection / gui that isn't working quite right. It seems to want you to pick one provider and stay with it, not switch between. If that's the case, the GUI should be designed a bit differently. 

I'm cool with sticking with just this for now. I'm not sure what made this configuration actually 'stick' ... I think I had to be looking at the zed.dev config, change it, then you get a dialog to save. Not sure what caused that.

Now it uses this config even when I switch providers. I'm ok with this for now!

```json
{
  "assistant": {
    "version": "2",
    "enabled": true,
    "default_model": {
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-latest"
    }
  },
  "language_models": {
    "zed.dev": {
      "version": "1",
      "available_models": [
        {
          "provider": "anthropic",
          "name": "claude-3-5-sonnet-latest",
          "display_name": "Claude 3.5 (Tool-enabled)",
          "max_tokens": 128000,
          "max_output_tokens": 2560,
          "tools": [
            {
              "name": "run_tree",
              "description": "Execute the tree command in the current directory to display the directory structure. Returns the output as a string.",
              "input_schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "description": "The directory path to start from, defaults to current directory if empty"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by goodlux** [comment]
Just jumping back on this thread one more to put down some findings. I went into the source and did some debugging and was able to get tool_use functionality working. This is the proper format for using tools, but the source has to be modified for them to actually work (now tool is actually already in the codebase, shows the current time). 

Just want to say I saw the context_server tool, and WOW what a great architecture! I can't wait to set up a context server locally. SO USEFUL. Zed it the best! 

Looking forward to seeing what you develop with this, and would love to help out

```json
{
  "assistant": {
    "version": "2",
    "enabled": true,
    "default_model": {
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-latest"
    }
  },
  "language_models": {
    "anthropic": {
      "version": "1",
      "available_models": [
        {
          "name": "claude-3-5-sonnet-latest",
          "display_name": "Claude 3.5 (Tool-enabled)",
          "max_tokens": 128000,
          "max_output_tokens": 2560
        }
      ],
      "available_tools": [
        {
          "name": "now",
          "description": "Returns the current datetime in RFC 3339 format.",
          "input_schema": {
            "type": "object",
            "properties": {
              "timezone": {
                "type": "string",
                "enum": ["utc", "local"],
                "description": "The timezone to use for the datetime"
              }
            }
          }
        }
      ]
    }
  }
}

```
