### ISSUE TITLE
Newly added python language server showing new error/warnings

### ISSUE THREAD

**Issue by mkismy** [zed-industries/zed#20646]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After updating to 0.162.0, my python project started showing many error/warnings, triggered by mypy and pycodestyle.

I have neither added to my project so I assume the cause is python-lsp-server added in 0.162.0.
I had some rules ignored on the previous pyright but the current one ignores them.

Are there any way I can disable the newly added language server and restore the original one?

### Environment

Zed: v0.162.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

**Comment by drcongo** [comment]
@mkismy I had the same, fiddling around in the settings I ended up with this...
```
"languages": {
    "Python": {
      "language_servers": ["ruff", "!pylsp", "python-refactoring", "!pyright"],
      "format_on_save": "on",
      "formatter": [
        {
          "code_actions": {
            "source.organizeImports.ruff": true,
            "source.fixAll.ruff": true
          }
        },
        {
          "language_server": {
            "name": "ruff"
          }
        }
      ]
    }
  },
```

The `"!pylsp"` is the bit you need, though I had to restart Zed for it to take effect.

**Comment by JosephTLyons** [comment]
Is there something we should tweak in the default settings, @osiewicz?

**Comment by rgbkrk** [comment]
It looks like we'd want to set `plugins.pycodestyle.enabled` to `false` by default: https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md. I'm surprised if mypy warnings are coming up... unless someone has mypy configured in their `pyproject.toml`.

**Comment by osiewicz** [comment]
@mkismy you can disable pylsp for now with:
`"languages": { "Python": { "language_servers": ["!pylsp", "..."] } },`

@rgbkrk IIRC mypy is enabled by default, but we should probably check whether it is actually enabled on users end.

**Comment by vlebert** [comment]
I was also creating an issue when I found this one:

Recently I started having linter error for example for import of missing or for line length

![digi-studio 2024-11-21 at 20 48 16](https://github.com/user-attachments/assets/c5fd6a9d-47d6-4fdc-9fe0-187f12f4dbc2)

Previously with pyright and ruff I did not get such errors

There seems to be a new linter called "mypy" and creating files in the project (`.mypy_cache` and `.ropeproject`)

What is this new linter and how to configure it ? I could not find anything mentioning it in changelog or documentation

**Comment by pb1729** [comment]
For people using pyright, a similar solution to drcongo's worked for me, where I just disabled everything other than pyright:

```
{
    ...
    "languages": {
        "Python": {
            "language_servers": [
                "!ruff",
                "!pylsp",
                "!python-refactoring",
                "pyright"
            ],
            ...
        },
        ...
    },
    ...
}
```

I also deleted `.mypy_cache` and `.ropeproject` after I made this change and Zed didn't add them back afterwards.

**Comment by vlebert** [comment]
For my understanding :

- is this an issue to be fixed or expected behavior ?
- When editing settings, how ca we know the list of language servers available for Python on current setup ? When I open default setting, they are not listed

**Comment by osiewicz** [comment]
@vlebert this is an issue to be fixed; our rollout of new pylsp is not as smooth as I've expected.  I'm sorry for that.
As for knowing which language servers are associated with a given language, there's currently no affordance for that in the UI. Once again, we can do better here.

**Comment by vlebert** [comment]
Wow you're quick

![digi-studio 2024-11-22 at 08 25 25](https://github.com/user-attachments/assets/f9fc8708-b76e-4f0d-9c36-4a624c443eab)

Thanks
