### ISSUE TITLE
Cannot SSH for remote development into Windows machine

### ISSUE THREAD

**Issue by thomaseizinger** [zed-industries/zed#20650]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Try to SSH into a remote VM that is running Windows. Connection fails with the command `uname` not being found.

### Environment

Zed: v0.159.7 (Zed)
OS: Linux Wayland nixos 24.05
Memory: 60.6 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV GFX1103_R1) || radv || Mesa 24.0.7

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/19892

**Comment by SomeoneToIgnore** [comment]
Sure, it's a totally different use case, but Zed has a binary that it has to start on the host, which does not support Windows/WSL2/etc. anyway.

See also https://github.com/zed-industries/zed/pull/20586

**Comment by Kreijstal** [comment]
just use msys2
