### ISSUE TITLE
Search all files not working

### ISSUE THREAD

**Issue by samolego** [zed-industries/zed#20661]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi there, I have an issue with searching through all files. Until I open a file manually by clicking on it, it is not found in the `Search project files` menu (`shift-shift` with intellij keybindings).

### Environment

Zed: v0.161.1 (Zed)
OS: Linux Wayland ubuntu 24.10
Memory: 13.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.3-1ubuntu1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Before opening the file:
![Screenshot_20241114_113350](https://github.com/user-attachments/assets/6a08155e-81dc-4cdf-8e49-6e111002756a)

After opening:
![Screenshot_20241114_114008](https://github.com/user-attachments/assets/4dfbc8d2-05cf-41b8-9d8c-3e5e32751d69)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
Are those files inside .gitignored directories by any chance?
Would be ineresting to get that repo cloned (or any other public one with the same issue).

**Comment by samolego** [comment]
They were. I was not aware of that search doesn't go through these (although it makes sense now). Thanks for the help!
