### ISSUE TITLE
redact_private_values setting is not always respected

### ISSUE THREAD

**Issue by KhazAkar** [zed-industries/zed#20676]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening `.env` file with this option set to true (it's disabled by default, why?), values are still being shown

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland ubuntu 22.04
Memory: 15.2 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 (WHL GT2) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/df972a27-af9d-40f9-998c-f51d19692001)

**Comment by notpeter** [comment]
I can reproduce. Steps:

Add `"redact_private_values": true,` to your Zed settings.

```sh
mkdir -p /tmp/20676
cd $_
echo "FOO=BAR" > .env
zed .env
```

Note for `redact_private_values` works as expected I open the file open inside a workspace instead of as a singleton: `zed . .env`  instead of `zed .env`.

**Comment by KhazAkar** [comment]
To be honest, that file was in workspace, I needed to cut screenshot due to privacy reason :)

**Comment by KhazAkar** [comment]
Inside workspace doesn't work for me, too.
![image](https://github.com/user-attachments/assets/86047cd7-77f3-415e-b6f3-9b3b44d9f9f0)

**Comment by notpeter** [comment]
Can confirm:
* On MacOS it only works inside a workspace (not for orphan files)
* On Linux it doesn't work at all.
Thanks for reporting.

**Comment by KhazAkar** [comment]
It seems that this issue is WM/DE dependent. Right now, .env file in workspace is respected, but I'm running sway, not GNOME Wayland, on my another machine.
![20241116_15h42m30s_grim](https://github.com/user-attachments/assets/0d7450c6-84af-4c16-8113-25ad829f8da9)
