### ISSUE TITLE
Assistant slash command menu: descriptions can overflow

### ISSUE THREAD

**Issue by ToxicalNoob3062** [zed-industries/zed#20678]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The bug is in rendering i think. When I click on the context button of Assist panel I see this bug. I am on linux.\

![image](https://github.com/user-attachments/assets/ec9b489c-31b8-41aa-9751-8a28eba48b28)

### Environment
```
Zed: v0.161.2 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 15 GiB
Architecture: x86_64
GPU: AMD Unknown (RADV RENOIR) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.2
```
Did I installed the wrong version or something?

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Please provide your zed version details ("zed: copy system specs to clipboard") as requested by the template.

**Comment by ToxicalNoob3062** [comment]
@notpeter 

Zed: v0.161.2 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 15 GiB
Architecture: x86_64
GPU: AMD Unknown (RADV RENOIR) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.2

**Comment by notpeter** [comment]
Hi @ToxicalNoob3062,

What non-default settings do you have in your `~/.config/zed/settings.json`?

I can reproduce by setting by adding this to my settings:
```
  "ui_font_family": "Zed Plex Mono",
```

<img width="318" alt="Screenshot 2024-11-15 at 12 42 51" src="https://github.com/user-attachments/assets/e01ee4ca-ec7d-402e-9666-1a8d172e54ad">

**Comment by ToxicalNoob3062** [comment]
```
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "ui_font_size": 20,
  "buffer_font_size": 20,
  "theme": "VSCode Dark Modern",
  "ui_font_family": "Fira Code",
  "buffer_font_family": "Fira Code",
  "autosave": "on_focus_change",
  "current_line_highlight": "none",
  "auto_update": true,
  "format_on_save": "prettier",
  "soft_wrap": "editor_width",
  "project_panel": {
    "dock": "right"
  },
  "assistant": {
    "default_model": {
      "provider": "copilot_chat",
      "model": "gpt-4o"
    },
    "version": "2",
    "enabled": true
  },
  "auto_update_extensions": {
    "enabled": true
  }
}
```

This is my settings.json. But the question is why it will create problem in choosing a font? It's a bug right?
