### ISSUE TITLE
Support XF86 keyboard symbols in keymap

### ISSUE THREAD

**Issue by coroa** [zed-industries/zed#20687]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to assign the linux keyboard symbols `XF86Forward` and `XF86Back` (which are usually invoked by the multimedia keys) to `pane::GoForward` and `pane::GoBack`.

After adding the following bindings to `keymap.json`, pressing the keys did not go back or forward like the `ctrl-o`, `ctrl-i` vim bindings:
```json
  {
    "context": "Pane",
    "bindings": {
      "XF86Back": "pane::GoBack",
      "XF86Forward": "pane::GoForward"
    }
  }
```

### Environment

```
Zed: v0.161.2 (Zed)
OS: Linux X11 pop 22.04
Memory: 62.4 GiB
Architecture: x86_64
GPU: Intel(R) Arc(tm) Graphics (MTL) || Intel open-source Mesa driver || Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
```

**Comment by notpeter** [comment]
I don't have such a keyboard to test, but could you build zed on this branch:
- https://github.com/zed-industries/zed/pull/20695

And see if you can create custom bindings to `back` and `forward` in your keymap?

It's pretty easy to build from source, some instructions are here: https://zed.dev/docs/development/linux

**Comment by coroa** [comment]
yes, i can confirm #20695 works correctly with the back/forward keys.
thanks for the quick implementation. Loving it.

**Comment by notpeter** [comment]
I've added those to the PR as default mapping for linux/windows.
Thanks for reporting!
