### ISSUE TITLE
Hiding Command in Tasks

### ISSUE THREAD

**Issue by omennia** [zed-industries/zed#20697]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello, 
I use tasks quite often to automate some big commands I have to run for debugging purposes.
Some times these commands are 6 or 7 lines long and after running it there is a lot of clutter.

I want to know if it's possible to hide this:
```sh
⏵ Task `...` finished successfully
⏵ Command: ...
```
Specially the Command part, which can get very long.

Thank you so much, loving the editor.

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 15.1.0
Memory: 18 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
To be clear, you're looking for a task-specific parameter that allows suppressing the command itself from being included in the task output, right?

**Comment by omennia** [comment]
Yes, for example having the options
```json
  "display_task": "true",
  "display_command": "false
```
As parameters in the tasks.json file.

**Comment by omennia** [comment]
To clarify, this is the behaviour I was looking for:

https://github.com/user-attachments/assets/769eaff1-2901-4091-9175-90c6f4d91323

I can submit a pull request :-)

**Comment by nicholaswmin** [comment]
@omennia so which setting is it?

**Comment by omennia** [comment]
> [@omennia](https://github.com/omennia) so which setting is it?

You can find it here:
[Tasks Documentation](https://zed.dev/docs/tasks)

Specifically, the show_summary, and show_output.
