### ISSUE TITLE
tests don't use fully qualified path

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#20693]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in rust, if you write a test fn `foo_works()` in module `a::b` and `foo_works()` in module `c::d`, clicking the "run test" button next to either of them will run both. i'm guessing this is because the underlying command is just `cargo test foo_works` when it should be e.g. `cargo test a::b::foo_works` (the input passed to `cargo test` is a substring search of the full path).

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
This looks pretty much as https://github.com/zed-industries/zed/issues/10968 and has more details there, so I'll close this one in favor of.
