### ISSUE TITLE
Token usage showing as 1.3k regardless of LLM or project

### ISSUE THREAD

**Issue by pchalasani** [zed-industries/zed#20690]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open the assistant pane, with just my short default prompt (< 30 tokens) and no other context inserted, it already shows I've used 1.3k tokens, e.g. with Claude 3.5 Sonnet it shows 1.3k/200k, see image. The 1.3k remains same regardless of which LLM or which project I open zed with.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="239" alt="image" src="https://github.com/user-attachments/assets/090fd007-8dc9-4071-b217-630614a1bd25">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Upgrade Zed.  Zed >= 0.161.x include this fix:
- https://github.com/zed-industries/zed/pull/20180
