### ISSUE TITLE
Unnamed register and a way to use it as default register for yanking operation

### ISSUE THREAD

**Issue by aakashsigdel** [zed-industries/zed#20703]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently zed automatically yanks to system clipboard in vim mode when `use_system_clipboard` is set. The default vim behaviour is to yank it to the unnamed register.

It would be great if we could implement a setting to enable this. Something like:
```typescript
{
  "vim": {
    "default_yank_register": "system_clip_board" | "unnamed" | "other_options_available"
  }
}
```

### Environment

```
Zed: v0.161.2 (Zed)
OS: macOS 14.1.0
Memory: 16 GiB
Architecture: aarch64
```

**Comment by ConradIrwin** [comment]
How is "default_yank_register": "unnamed" different from "use_system_clipboard": "never"?
