### ISSUE TITLE
A setting to disable the helper box floating around with my cursor

### ISSUE THREAD

**Issue by deauthe** [zed-industries/zed#20725]
### Check for existing issues

- [X] Completed

### Describe the feature

not sure if I should add this as an issue or I am just not able to find the setting inside it. But this helper/hint box keeps floating around my cursor even when I'm not hovering on things. This blocks my vision enough that I switch to another IDE. 
<img width="910" alt="Screenshot 2024-11-15 at 7 57 02 PM" src="https://github.com/user-attachments/assets/41e31663-f22e-467f-9255-d5441f3e94ac">

### Environment

# zed : 0.161.2
`d664f56fac161cec8b14d9093dc553c07936fe34`

**Comment by SomeoneToIgnore** [comment]
This should be a  `"show_signature_help_after_edits": false,` and we'll disable it starting from the next version, as it seems to cause more questions than needed.

**Comment by deauthe** [comment]
appreciated
