### ISSUE TITLE
Task Execution Fails

### ISSUE THREAD

**Issue by andre0xFF** [zed-industries/zed#20720]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When creating or editing a new task and attempting to run it, the task does not execute. No terminal window appears, and the following error is logged: `IOError: Failed to spawn command '/bin/zsh': Not a directory (os error 20)`.

**Steps to Reproduce:**
1. Create a new task with the following configuration:
    ```json
    {
      "label": "gitversion",
      "command": "docker run -it gittools/gitversion:5.12.0"
    }
    ```
2. Attempt to run the task.
3. Observe that no terminal window appears and the task does not execute.

**Expected Result:**
The task should run successfully, and a terminal window should appear showing the output of the command.

**Actual Result:**
The task does not run, and no terminal window appears.

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-11-15T09:52:24.174063Z [ERROR] Working directory: /Users/user/.config/zed/tasks.json Shell command: `/bin/zsh -i -c docker run -it gittools/gitversion:5.12.0`, IOError: Failed to spawn command '/bin/zsh': Not a directory (os error 20)

Caused by:
    Failed to spawn command '/bin/zsh': Not a directory (os error 20)
```
</details>

**Comment by SomeoneToIgnore** [comment]
Mine seems to work just fine:

without Docker:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5d2a5452-dd1d-4faf-adf9-66302121eadc">

with Docker:
<img width="965" alt="image" src="https://github.com/user-attachments/assets/85b066a7-7b4d-47b8-a4cb-05b8a725e890">

-------------------------

> `'/bin/zsh': Not a directory`

Looks like the task reuses the shell that's somehow not available to Zed (?).
What is your default shell?

If you open Zed's integrated terminal and do
`echo $SHELL` and `file /bin/zsh`, what does it output?
So the same outside Zed, in the system terminal, what does it output?

**Comment by andre0xFF** [comment]
I just want to point that task run sometimes. But usually it fails after editing the tasks file.

Here's the output:
```bash
❯ echo $SHELL
/bin/zsh

❯ file /bin/zsh
/bin/zsh: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/zsh (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/zsh (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

I have the same exact output on the system shell:
```bash
❯ echo $SHELL
/bin/zsh

~ 
❯ echo $SHELL
/bin/zsh

❯ file /bin/zsh
/bin/zsh: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/zsh (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/zsh (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

**Comment by SomeoneToIgnore** [comment]
Thanks for more details, can reproduce this way, trying to spawn the task right after editing does nothing and there's an error in the logs.

**Comment by jeremyckahn** [comment]
I'm seeing something similar on Ubuntu as well:

```
Caused by:
    Failed to spawn command '/bin/bash': Not a directory (os error 20)
2024-11-15T08:48:02.952157662-06:00 [ERROR] oneshot canceled
2024-11-15T08:48:10.64456675-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
2024-11-15T08:48:10.980858258-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
2024-11-15T08:48:11.54990817-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
2024-11-15T08:48:11.566684095-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
```

I have Zed installed as a Flatpak. Perhaps that's related to this issue?

Additionally, I've found that I'm only able to run tasks successfully when I'm focused on the log file (`/home/jeremyckahn/.var/app/dev.zed.Zed/data/zed/logs/Zed.log`), not an actual code file.

**Comment by notpeter** [comment]
I can reproduce too.
I believe we are incorrectly determining the working directory for non-project files.

As a workaround, can you explicitly specify a `cwd` in your task definition:
```json
{
  "label": "gitversion",
  "command": "docker run -it gittools/gitversion:5.12.0",
  "cwd": "$ZED_WORKTREE_ROOT"
}
```
And see if that works?

**Comment by jeremyckahn** [comment]
> I can reproduce too. I believe we are incorrectly determining the working directory for non-project files.
> 
> As a workaround, can you explicitly specify a `cwd` in your task definition:
> 
> ```json
> {
>   "label": "gitversion",
>   "command": "docker run -it gittools/gitversion:5.12.0",
>   "cwd": "$ZED_WORKTREE_ROOT"
> }
> ```
> 
> And see if that works?

I attempted to run this task and nothing happened (like all the other tasks I tried to run). Log output:

```
2024-11-16T09:47:02.017655328-06:00 [ERROR] Working directory: /home/jeremyckahn/.var/app/dev.zed.Zed/config/zed/tasks.json Shell command: `/bin/bash -i -c docker run -it gittools/gitversion:5.12.0`, IOError: Failed to spawn command '/bin/bash': Not a directory (os error 20)

Caused by:
    Failed to spawn command '/bin/bash': Not a directory (os error 20)
```

**Comment by jeremyckahn** [comment]
To followup here, I don't think this is related to Flatpak packaging. I uninstalled the Flatpak and reinstalled via `curl -f https://zed.dev/install.sh | sh` and get similar results:

```
Caused by:
    Failed to spawn command '/bin/bash': Not a directory (os error 20)
2024-11-16T15:50:13.330203701-06:00 [ERROR] Working directory: /home/jeremyckahn/.config/zed/tasks.json Shell command: `/bin/bash -i -c docker run -it gittools/gitversion:5.12.0`, IOError: Failed to spawn command '/bin/bash': Not a directory (os error 20)

Caused by:
    Failed to spawn command '/bin/bash': Not a directory (os error 20)
2024-11-16T15:50:15.855026061-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
2024-11-16T15:51:04.437723183-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
2024-11-16T15:51:05.417852472-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
2024-11-16T15:51:05.429642829-06:00 [WARN] Linux: Wayland: Unable to get default cursor too!
```

**Comment by jeremyckahn** [comment]
Looking at this bit:

```sh
`/bin/bash -i -c docker run -it gittools/gitversion:5.12.0`
```

If I simplify this to:

```sh
/bin/bash -i -c echo hi
```

And run it in my terminal, nothing happens. If I add quotes:

```sh
/bin/bash -i -c "echo hi"
```

It prints `hi` as I expect. Perhaps the constructed Bash command just needs quotes?

**Comment by opsnull** [comment]
related issues：
https://github.com/zed-industries/zed/issues/19873
https://github.com/zed-industries/zed/issues/20060
