### ISSUE TITLE
v0.162.1: Vim mode escape sequence prefixes no longer inserted in Insert mode

### ISSUE THREAD

**Issue by smsegal** [zed-industries/zed#20732]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have the following snippet in my `keymap.json` that enables me to use a keychord to escape from Insert mode back to Normal.

```json
  {
    "context": "vim_mode == insert",
    "bindings": {
      "f d": "vim::NormalBefore",
    }
  }
```

The expected behaviour when pressing "f d" is to switch from Insert -> Normal when the second key in the sequence is observed (up to a timeout period). This worked as intended on versions < 0.162.1.

On Zed Preview (0.162.1), the first key in the sequence (`f` in my case) is no longer inserted into the buffer. If I press the full sequence, I do still go from `insert -> normal`, but I can no longer type an `f` at all.

There are a couple of other confirmed reports of the same issue on the discord #vim-mode, although I'm not sure how to permalink those. 

I've downgraded back to Zed Stable (0.161.2) and the keys are working as expected. 

### Environment

Zed: v0.162.1 (Zed Preview)
OS: macOS 15.1.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>
Had to truncate the log, had work-related project names etc in there. These are the most recent two lines, and nothing else *seems* related. 

```
2024-11-15T12:06:09.215796-05:00 [WARN] unhandled capability registration: Registration { id: "8a7d8c71-eb17-4684-994f-11cbbc0d664c", method: "workspace/didChangeConfiguration", register_options: Some(Object {"section": String("bashIde")}) }
2024-11-15T12:06:09.961735-05:00 [INFO] skipping numeric progress token 16807
```
</details>

**Comment by akbxr** [comment]
> Looks like the new stable release also suffers from this bug. I haven't updated to test, since it's unclear if I can downgrade to an older version (and tbh, I don't feel like going through the effort during the workday).

I've updated it, it's fixed in the latest preview and stable version.

**Comment by smsegal** [comment]
Awesome, can confirm it's fixed for me as well. Will close.
