### ISSUE TITLE
Allow overrides for json-language-server settings

### ISSUE THREAD

**Issue by 4teapo** [zed-industries/zed#20739]
### Check for existing issues

- [X] Completed

### Describe the feature

You currently can't customize settings for json-language-server, even though it would be very useful, e.g. to set schemas for certain files without adding a "$schema" to each of them. The YAML module merges user settings with defaults, but the JSON module doesn't.

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Do you have any example setting(s) you're looking to use or is it just a custom schema association?

Once implemented I think it would translate to something like this in zed settings.json
```json
  "lsp": {
    "json-language-server": {
      "settings": {
        "json": {
          "schemas": [
            "fileMatch": ["something.json"],
            "schema": "https://json.schemastore.org/babelrc"
          ],
        }
      }
    }
  }
```
Which would need to merge with the defaults defined here:
https://github.com/zed-industries/zed/blob/e25a03cd3c68db346c6d0987981e73efa659386f/crates/languages/src/json.rs#L90-L103
