### ISSUE TITLE
Unable to use "trash" action in project panel during SSH remote session

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#20747]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When attempting to delete a file using the "trash" action in Zed's project panel while connected to an Ubuntu server via SSH, the action fails silently with no user feedback.

### Environment

Zed: v0.163.0 (Zed Nightly a8df0642a8d124b8de6fe280dc0f806f7fae604f)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
[ERROR] (remote server) server:error handling message. type:DeleteProjectEntry, error:ZBus Error: I/O error: No such file or directory (os error 2)
[ERROR] RPC request DeleteProjectEntry failed: ZBus Error: I/O error: No such file or directory (os error 2)
```
</details>

**Comment by notpeter** [comment]
I don't think there is the concept of a remote trash for Zed to use via SSH.
We should probably only present delete remotely in the project panel.

**Comment by Moshyfawn** [comment]
> I don't think there is the concept of a remote trash for Zed to use via SSH. We should probably only present delete remotely in the project panel.

You're right, I didn't even think about it in the context of a GUI 🙈

**Comment by Moshyfawn** [comment]
Closing in favour of #20845
