### ISSUE TITLE
[Docs} Svelte link 404 Page Not Found

### ISSUE THREAD

**Issue by shinokada** [zed-industries/zed#20768]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://zed.dev/docs/languages/svelte?highlight=svelte#svelte

When I click the first link for Svelte extension in the doc, it goes to 404 Page Not Found.

The link should be https://github.com/zed-extensions/svelte
### Environment

N/A

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/5590e23c-b7d3-456c-b11a-0282a6730f8e)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by Moshyfawn** [comment]
The extension's been moved to a separate repo, hence the 404 link. Sorry about that (ref: #19425)
