### ISSUE TITLE
Delta cannot detect light/dark theme from within terminal

### ISSUE THREAD

**Issue by samhh** [zed-industries/zed#20761]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using Zed's built-in terminal with Delta configured as the pager for something like Git, it's unable to detect light mode. This is in contrast to running the same command (e.g. `git show`) in Kitty.

Delta can be forced into light mode by configuring it with `--light`, which exposes how it should look when Zed is in light mode.

Here's Delta's change: https://github.com/dandavison/delta/pull/1615
And here's Lazygit for example fixing compatibility: https://github.com/jesseduffield/lazygit/issues/3419

### Environment

Zed stable 0.161.2, macOS 15.1

**Comment by notpeter** [comment]
Can you provide explicit steps to reproduce?
What is the behavior you were expecting / what actually happened?

Here's what I did:
```
brew install delta
echo -e "FOO=BAR\nBAR=BAZ\n\MOP=POP\n" > a.env
echo -e "FOO=BAR\nBAR=BOP\n\MOP=POP\n" > b.env
delta a.env b.env
```

One Light
<img width="509" alt="Screenshot 2024-11-18 at 17 50 30" src="https://github.com/user-attachments/assets/da2258e5-69a3-4cfd-b47e-09fca384f333">

One Dark
<img width="516" alt="Screenshot 2024-11-18 at 17 50 57" src="https://github.com/user-attachments/assets/808745b2-59b7-47f9-b6e6-d807c123c489">

**Comment by samhh** [comment]
It works now 🤷 Thanks for taking a look.
