### ISSUE TITLE
Vim motions are hardcoded on US keyboard layout

### ISSUE THREAD

**Issue by Ukendio** [zed-industries/zed#20777]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Vim motions does not seem to be completely compatible with my swedish layout keyboard. E.g. end of line does not work properly as `$` on my keyboard is `alt gr + 4` and not `shift + 4`
changing my keyboard layout to the US layout does fix this issue for me but i dont think that should have to be necessary

### Environment

Windows 11 Zed Dev 0.144.0

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by JunkuiZhang** [comment]
Related #17031

**Comment by ConradIrwin** [comment]
@Ukendio This is fixed by Zed 0.162 and above.
