### ISSUE TITLE
`à` char breakes "show_whitespaces"

### ISSUE THREAD

**Issue by fricht** [zed-industries/zed#20782]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- always show whitespaces by adding  `"show_whitespaces": "all"` to zed settings
- insert the character `à` somewhere in a file

There is the gray dot indicating for a whitespace after the `à`, even if there is no character at all

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland fedora 41
Memory: 7.5 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot From 2024-11-17 11-28-03](https://github.com/user-attachments/assets/45557961-23bf-48ea-a7a2-182b4bf3cc0f)

Here on this line, there is only the char `a` and no spaces

We can see it better if a add a `O` after. The dot will end up insite the O

![Screenshot From 2024-11-17 11-28-46](https://github.com/user-attachments/assets/2ac257de-6ca7-4c32-9ec9-2d1b8d01159c)

### If applicable, attach your Zed.log file to this issue.

I found nothing relevant in the logs

**Comment by notpeter** [comment]
I'm going to merge this into: 
- https://github.com/zed-industries/zed/issues/20781
