### ISSUE TITLE
Add Bazel support

### ISSUE THREAD

**Issue by sibi-venti** [zed-industries/zed#20786]
### Check for existing issues

- [X] Completed

### Describe the feature

bazel BUILD MODULE and Workspace Support

### Environment

bazel buidifier supprt linux and Mac

### If applicable, add mockups / screenshots to help present your vision of the feature

bazel runs in sandbox

**Comment by notpeter** [comment]
Can you please be more specific with what features in Zed you would like to help better support your use of Bazel?

**Comment by bethebunny** [comment]
Not OP but here's some features I'd really like:
- Syntax highlighting / LSP support for Skylark (Bazel's subset of Python)
- go-to-definition both for Bazel dev (follow directives to their definitions in included `.bzl` files) and for rules (follow rule names through to their definitions)
- Outline panel lists rules and directives defined in the file
- `buildifier` (bazel file formatter) available as a linter/formatter

Beyond that, I think further integration would fall under https://github.com/zed-industries/zed/issues/5065. VSCode for instance allows deep integration to detect build, execution, and test targets and their relationships to files in the codebase to facilitate running and debugging from the editor.

**Comment by bethebunny** [comment]
Indeed this is amazing! It's extremely snappy too :D I'll file followup issues there, thanks so much for the pointers.
