### ISSUE TITLE
False Positive Error for Modern C++ Brace Initialization in Zed Editor

### ISSUE THREAD

**Issue by LeksinMaksim** [zed-industries/zed#20813]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Zed editor's clang analyzer incorrectly flags the standard C++ uniform initialization syntax int x {}; with the error "Expected ';' at end of declaration". This initialization syntax is valid modern C++ (since C++11) and is actually recommended as a best practice to prevent narrowing conversions. The editor should recognize this as valid syntax and not report it as an error.

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="813" alt="image" src="https://github.com/user-attachments/assets/1c04afec-6620-4ce4-a00e-7813a0a1e3f7">

**Comment by SomeoneToIgnore** [comment]
The Zed editor has nothing to do with it, as it knows nothing about what a language is, neither it is capable of checking any semantics-related questions.

**Comment by SomeoneToIgnore** [comment]
Zed Editor uses https://github.com/clangd/clangd as a language server for all C and C++ -related analysis.
It might have certain flags to enable such behavior already, or you can search for related issues or create one.

**Comment by SomeoneToIgnore** [comment]
https://zed.dev/docs/languages/cpp#more-server-configuration

and around contains Zed + clangd configuration examples.
