### ISSUE TITLE
Does not reloade image on change

### ISSUE THREAD

**Issue by SiebenCorgie** [zed-industries/zed#20816]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that Zed does not reload image files when they change. I have a `.png` image in my project that gets periodically re-rendered. Even if I close the buffer/view in Zed and reopen it, it still shows the _old_ image, not the new one. I currently have to open the image in my system's image-viewer instead.

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 31.3 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6800 XT || AMD open-source driver || 2024.Q3.3 (LLPC)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by jansol** [comment]
Your Zed version is too old, reloading images in the image preview was only implemented last week: #20374  (it usually takes about two weeks for new changes to reach stable releases)
