### ISSUE TITLE
Default prompts are not automatically expanded in v0.162.x

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/zed#20820]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the latest Preview, it looks like "Default" prompts are not automatically expanded.

Steps to reproduce:
1. Open a new Chat
2. Notice the token count
3. Unfold "Default" prompts
4. All default prompts are to be manually expanded 💥

https://github.com/user-attachments/assets/1e7c4f95-a0d2-4f3b-9331-f73475a5e5cc

### Environment

Zed: v0.162.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
I can reproduce.  Works in Stable. Broken in Preview.
Thanks for reporting.
