### ISSUE TITLE
ctrl + scroll wheel up and down should enlargen or shrink text

### ISSUE THREAD

**Issue by RustoMCSpit** [zed-industries/zed#20835]
### Check for existing issues

- [X] Completed

### Describe the feature

in the same way in your browser, you should be able to scroll up and down with ctrl to resize everything

### Environment

Zed: v0.161.2 (Zed)
OS: Linux X11 linuxmint 22
Architecture: x86_64

**Comment by notpeter** [comment]
Duplicate of:
- https://github.com/zed-industries/zed/issues/10647
