### ISSUE TITLE
Graphics support in the integrated terminal

### ISSUE THREAD

**Issue by mil-ad** [zed-industries/zed#20860]
### Check for existing issues

- [X] Completed

### Describe the feature

Terminal emulators such as Kitty or iTerm2 have [their](https://sw.kovidgoyal.net/kitty/graphics-protocol/) [own](https://iterm2.com/documentation-images.html) protocols for displaying grapgics in the terminal. These have been adopted by other emulators including vscode's terminal. It would be great if Zed could also support this in its integrated terminal.

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 14.6.0
Memory: 36 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Zed uses Alacritty and does not modify it in any way, esp. related to graphics: all related issues should go there.

I believe you're looking for https://github.com/alacritty/alacritty/issues/910

**Comment by mil-ad** [comment]
> I believe you're looking for https://github.com/alacritty/alacritty/issues/910

Indeed. But that's a pretty sad 🧵

I didn't realise Zed uses Alacritty under the hood. I doubt it will ever get sixel or kitty support - it's not in the same league as leading terminal emulators.

Thanks for looking into it though.
