### ISSUE TITLE
Build on Windows is failing

### ISSUE THREAD

**Issue by vednig** [zed-industries/zed#20895]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've been using Zed for over 6 months now on Windows, by compiling and running it, somethings changed after recent updates few weeks ago I've started getting this error
![image](https://github.com/user-attachments/assets/b3664fa2-a6fd-457b-887d-1623be8d7d3e)
So I researched a little on windows support and came to [ this repo ](https://github.com/superboxes/zed-windows?tab=readme-ov-file)
I know issue for Windows support is still an open issue

### Environment

OS: Windows 24H2
RAM: 24GB
Arch : 64 bit
Branch : main

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```
The following warnings were emitted during compilation:

warning: msvc_spectre_libs@0.1.2: No spectre-mitigated libs were found. Please modify the VS Installation to add these.

error: failed to run custom build command for `msvc_spectre_libs v0.1.2`

Caused by:
  process didn't exit successfully: `C:\Users\asus\Documents\Testing\zed\target\debug\build\msvc_spectre_libs-8ef79fc3b387750e\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=No spectre-mitigated libs were found. Please modify the VS Installation to add these.

  --- stderr
  thread 'main' panicked at C:\Users\asus\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc_spectre_libs-0.1.2\build.rs:37:13:
  No spectre-mitigated libs were found. Please modify the VS Installation to add these.
```
</details>

**Comment by SomeoneToIgnore** [comment]
Check out https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md#dependencies , it got updated recently: you have to install more MSVC libs.

**Comment by gantrol** [comment]
I have same question, though I have installed all of x64 MSVC libs(excluding outdays).

**Comment by SomeoneToIgnore** [comment]
The spectre-mitigated libs too?
The only idea I can come up is https://github.com/zed-industries/zed/discussions/20142#discussioncomment-11140185

**Comment by gantrol** [comment]
> The spectre-mitigated libs too? The only idea I can come up is [#20142 (comment)](https://github.com/zed-industries/zed/discussions/20142#discussioncomment-11140185)

Yes. And I use English locale

**Comment by gantrol** [comment]
> I have same question, though I have installed all of x64 MSVC libs(excluding outdays).

The issue was resolved by updating Visual Studio Build Tools 2022 to version 17.12.2 (released on Nov. 26th). The problem occurred in versions 17.12 and 17.12.1.

**Comment by elimossrosenberg** [comment]
Visual Studio Professional 17.12.3 with listed dependencies.

I had to change `cargo.toml` such that git2 is
`git2 = { version = "0.19", features = ["vendored-libgit2"]}`

Then set the environment variable (using powershell)
`$Env:LIBGIT2_NO_VENDOR="0"`

Then the build works. Otherwise, the toolchain could have trouble finding git2.lib (and probably openssh). This situation could vary depending on your windows and VS toolchain environment.
