### ISSUE TITLE
How to hide "[SHORTCUT] to chat, [SHORTCUT] to generate" inline hint?

### ISSUE THREAD

**Issue by ArturGalstyan1** [zed-industries/zed#20902]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since the latest build, I get this inline hint:
<img width="294" alt="image" src="https://github.com/user-attachments/assets/fe072911-0fce-4e8d-bb28-80b6d1c98e24">

(It's not even the correct bindings)

Is there any way to disable/hide it?

I'm on Zed 0.163.0, 3c57a4071cd3e3400a1e0b3329fccb0f0477e1ea

I looked around but couldn't find a similar question :( 

### Environment

Zed: v0.163.0 (Zed Dev 3c57a4071cd3e3400a1e0b3329fccb0f0477e1ea)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by RemcoSmitsDev** [comment]
This was added here https://github.com/zed-industries/zed/pull/20824, you can disable it by adding `{"assistant": {"show_hints": false}}` to your `settings.json` file.

**Comment by ArturGalstyan1** [comment]
Ah, yes! Thank you!
