### ISSUE TITLE
Zed 0.161.1 not running on Linux - "called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by migldasilva** [zed-industries/zed#20921]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Install Zed from source code (compilation goes fine)
2. Run Zed in foreground mode

Besides, I'd like to clarify that in Gentoo, the source code is downloaded from official sources. Concretely, in Zed's case, code is downloaded from `https://github.com/zed-industries/zed/archive/refs/tags/v0.161.1.tar.gz`

### Environment

Zed: v0.161.1 (Zed)
OS: Gentoo Linux peligro.oymiakon 6.6.38-gentoo #1 SMP PREEMPT_DYNAMIC Wed Aug 14 23:50:49 CEST 2024 x86_64 AMD FX(tm)-8350 Eight-Core Processor AuthenticAMD GNU/Linux
Memory: 16 GB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
[2024-11-20T18:55:56+01:00 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "/var/tmp/portage/app-editors/zed-0.161.1/work/zed-0.161.1/crates/util/src/util.rs",
    "line": 579
  },
  "backtrace": [
    "__libc_start_main"
  ],
  "app_version": "0.161.1",
  "release_channel": "Zed",
  "os_name": "Linux X11",
  "os_version": "gentoo 2.17",
  "architecture": "x86_64",
  "panicked_on": 1732125356256,
  "system_id": "dbd28b2e-e328-46a5-9b69-8f78c4267c29",
  "installation_id": "34d4013e-09db-4138-8596-08a4943fe8ad",
  "session_id": "866f02dd-e6bb-4f22-a352-ab605f56268e"
}
```
</details>

**Comment by CharlesChen0823** [comment]
if you compile from source code, you should using `script/install-linux`,

**Comment by migldasilva** [comment]
> if you compile from source code, you should using `script/install-linux`,

Thanks for the reply. I couldn't install using `script/install-linux` either. Here is the output:

```
   Compiling zed v0.161.1 (/home/myuser/repos/zed/crates/zed)
    Finished `release` profile [optimized + debuginfo] target(s) in 22m 41s
+ [[ x86_64-unknown-linux-musl == \x\8\6\_\6\4\-\u\n\k\n\o\w\n\-\l\i\n\u\x\-\m\u\s\l ]]
+ export 'RUSTFLAGS= -C link-args=-Wl,--disable-new-dtags,-rpath,$ORIGIN/../lib -C target-feature=+crt-static'
+ RUSTFLAGS=' -C link-args=-Wl,--disable-new-dtags,-rpath,$ORIGIN/../lib -C target-feature=+crt-static'
+ cargo build --release --target x86_64-unknown-linux-musl --package remote_server
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.19.0
   Compiling memchr v2.7.4
   Compiling byteorder v1.5.0
   Compiling libc v0.2.161
   Compiling typeid v1.0.2
   Compiling itoa v1.0.11
   Compiling serde v1.0.209
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `once_cell` (lib) due to 1 previous error
error: could not compile `libc` (lib) due to 1 previous error
error: could not compile `byteorder` (lib) due to 1 previous error
error: could not compile `itoa` (lib) due to 1 previous error
error: could not compile `typeid` (lib) due to 1 previous error
error: could not compile `memchr` (lib) due to 1 previous error
error: could not compile `serde` (lib) due to 1 previous error
```

Actually, what I previously meant with compiling direct from the sources in Gentoo is that the source code is pulled from an official source (in this case, this is Zed's Github repo), all dependencies are solved and the code is compiled on the target machine. It's not a pre-compiled bin packaged.

On the other hand, following what I pasted from `Zed.log`, something seems not right in `zed-0.161.1/work/zed-0.161.1/crates/util/src/util.rs` file. Unfortunately, my knowledge on Rust is not enough for helping in this issue.
