### ISSUE TITLE
When shift is pressed, the string shift is printed

### ISSUE THREAD

**Issue by jizhi0v0** [zed-industries/zed#20963]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when knock the shift key, the string shift is append in current line

https://github.com/user-attachments/assets/cdb51b28-1691-40d8-a997-b3bb0904fe37

### Environment

zed preview 0.162.3 version
Apple M3 Max
36 GB
15.1 (24B83)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
[Zed.log](https://github.com/user-attachments/files/17839514/Zed.log)

```
</details>

**Comment by jizhi0v0** [comment]
This issue only in 0.163.0 preview and 0.162.3 stable

**Comment by jizhi0v0** [comment]
c4a382d7cb93f5fbd3e9bc0821dfb6f74fc64de9 is the first bad commit

**Comment by caturbgs** [comment]
This is very frustrating issue I got today after updating Zed, hope this will take up soon

**Comment by eatenpancreas** [comment]
Having the same issue here

**Comment by lebe-dev** [comment]
Approved, v0.161.2 is not affected

**Comment by piechologist** [comment]
Do you all have a key binding for `"shift shift"`?

For me, pressing shift twice runs the bound action as intended. Pressing shift just once inserts `shift` into the editor after a split second. Removing the key binding solves the issue.

The same issue occurs with the other modifiers e.g., binding `"cmd cmd"` inserts `platform`.

**Comment by BraisonCrece** [comment]
I've found something that could be interesting for debugging the issue:

I thought about defining a key binding that sets to `null` the combination that sometimes generates this issue for me (`cmd shift`), I did it and suddenly I got a new word printed (`platform`)

![Screen Recording 2024-11-21 at 12 04 11](https://github.com/user-attachments/assets/c3551ed0-289f-4be2-a80b-8ea485ed600d)

**Comment by BraisonCrece** [comment]
> Do you all have a key binding for `"shift shift"`?
> 
> For me, pressing shift twice runs the bound action as intended. Pressing shift just once inserts `shift` into the editor after a split second. Removing the key binding solves the issue.
> 
> The same issue occurs with the other modifiers e.g., binding `"cmd cmd"` and inserts `platform`.

Yes, I have `shift shift` binding and disabling it fixes the problem 👍

**Comment by eatenpancreas** [comment]
@piechologist do you mean like this? I'm getting it but very inconsistently so
![image](https://github.com/user-attachments/assets/e5fcc933-0d7d-437a-b60d-eebe01cdb507)

**Comment by eatenpancreas** [comment]
I figured out what's causing it on my end.

For me, it's only happening if i select something, while selected press shift (just once) and then leave the selection by clicking somewhere else. It'll then just get pasted wherever i clicked to next.

https://github.com/user-attachments/assets/ce751ce8-73ce-439d-b24f-90c585ec2f2a

**Comment by piechologist** [comment]
> For me, it's only happening if i select something

I can't replicate that. It doesn't matter if there's a selection or not. With the `shift shift` binding commented out, nothing gets inserted.

**Comment by xplodwild** [comment]
Same happens for me on Linux v0.162.3, with a "shift shift" keybinding enabled, pressing shift then an arrow key leads to "shift" being inserted in the current buffer.

**Comment by blueambr** [comment]
I don't have any bindings and this happens. It's a ridiculously annoying bug. Wonder how it was introduced into the stable build.

**Comment by HarshNarayanJha** [comment]
Can confirm. It is happening on the latest stable. I do have a shift-shift key binding to open ctrl+p menu

<details>
<summary>System Info</summary>

Zed: v0.162.3 (Zed)
OS: Linux Wayland garuda unknown
Memory: 7.1 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.7-arch1.1

</details>

**Comment by VladimirTaytor** [comment]
Same here. I don't have `"shift shift"` custom bindings, but I do have `"base_keymap": "JetBrains"`
Please take a look asap, it's very annoying 🙏

**Comment by eatenpancreas** [comment]
> Same here. I don't have `"shift shift"` custom bindings, but I do have `"base_keymap": "JetBrains"` Please take a look asap, it's very annoying 🙏

now that you say it, i also have JetBrains base keymap as well, so that could be a part of it
