### ISSUE TITLE
Language server error: python-refactoring

### ISSUE THREAD

**Issue by iaxat** [zed-industries/zed#20978]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Language server error: python-refactoring

cst_lsp must be installed and available in $PATH.
-- stderr--

### Environment

ProductName:		macOS
ProductVersion:		15.1.1
Ram - 16
M2pro
Zed 0.162.3

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by KhazAkar** [comment]
1. It's because plugin doesn't provide this language server
2. You can install it yourself, using `uv tool install cst_lsp` afaik

**Comment by notpeter** [comment]
This is an issue with a 3rd party extension.
https://github.com/rowillia/zed-python-refactoring
It includes instructions in their README
Please open support requests as issue on that repo, not here.
