### ISSUE TITLE
Toggle comments stopped working for SE locale mac

### ISSUE THREAD

**Issue by hedefalk** [zed-industries/zed#20980]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't toggle comments anymore since latest update. I understand that it must be related to

https://zed.dev/blog/keyboard-localization
https://github.com/zed-industries/zed/issues/20425

but can't understand why and how to fix it.

`"cmd-/": ["editor::ToggleComments", { "advance_downwards": false }]`

is the default. Slash for my keyboard is shift-7, sorry about the cat hairs:

<img width="365" alt="image" src="https://github.com/user-attachments/assets/47797e69-80d6-498c-8c1c-45215bbbe321">

Tried with explicit:

"cmd-shift-7": ["editor::ToggleComments", { "advance_downwards": false }]
    }

but doesn't work either. It works explicitly using the command:

<img width="606" alt="image" src="https://github.com/user-attachments/assets/1f73125b-f2f2-454f-a724-fa38f5b5508c">

but the keymap is dead.

### Environment

Zed: v0.162.3 (Zed)
OS: macOS 15.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
It's quite hard to find this one https://github.com/zed-industries/zed/issues/20926 but I'd still want to keep similar issues consolidated in fewer issues possible, so will close this one.

**Comment by hedefalk** [comment]
Thanks, sorry I didn't find it.
