### ISSUE TITLE
bug: .C and .H file extensions should be detected as cpp

### ISSUE THREAD

**Issue by budde25** [zed-industries/zed#20996]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening a file with a .H or .C (note the capitalization) file extension will cause the auto detected language to show "unknown" rather than picking cpp.

discussion about valid cpp extensions:
https://stackoverflow.com/a/3223792

relevant pr for the helix editor:
https://github.com/helix-editor/helix/pull/5808

Thanks!

### Environment

Zed: v0.162.3 (Zed)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by ashtanko** [comment]
Experiencing the same issue, particularly with CPP files.
