### ISSUE TITLE
Rust - Add missing fields for struct initialization

### ISSUE THREAD

**Issue by Leikoe** [zed-industries/zed#21010]
### Check for existing issues

- [X] Completed

### Describe the feature

In rust rover, when writing the struct initialization syntax (in rust), the ide has an "Add missing fields" prompt which can, when clicked, add all the missing fields and their respective type's default value.

![image](https://github.com/user-attachments/assets/52971e60-3b1a-4348-8f7a-c96546c745e0)

### Environment

Zed: v0.162.3 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

**Comment by Leikoe** [comment]
I'm guessing it has to do with this https://rust-analyzer.github.io/manual.html#missing-fields

**Comment by osiewicz** [comment]
There's already a code action to fill missing struct fields + the diagnostics:
![image](https://github.com/user-attachments/assets/2c9e3c7c-5e18-445b-8be4-5763a2c25b44)

**Comment by Leikoe** [comment]
> There's already a code action to fill missing struct fields + the diagnostics: ![image](https://private-user-images.githubusercontent.com/24362066/388662652-2c9e3c7c-5e18-445b-8be4-5763a2c25b44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTc3NDUsIm5iZiI6MTczMjIxNzQ0NSwicGF0aCI6Ii8yNDM2MjA2Ni8zODg2NjI2NTItMmM5ZTNjN2MtNWUxOC00NDViLThiZTQtNTc2M2EyYzI1YjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE5MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2JmYWI3NWEzZjBmYTBkMmY0ZTk3ZGIyYzdjZmVlZDA1YTNiMWU1ODZjNTc2ZWY0MzBiZTIxMjgxNzQzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6Iwo-QqN-rve1RTWatX2a7iX8oCoaxDK90wBycWWRik)

Thank you so much, I've searched for this for the longest time. 
Sorry to have wasted your time : (

**Comment by osiewicz** [comment]
No worries!

**Comment by Leikoe** [comment]
> No worries! I hope you're having blast using Zed :)

Thank you so much, I AM ! 😁
