### ISSUE TITLE
"//nolint:" comment in Go is reformatted to "// nolint:"

### ISSUE THREAD

**Issue by nirs** [zed-industries/zed#21035]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The golangci-lint tool use `//nolint:` machine readable comments to disable linter checks for line or block. This is useful to avoid false positives for specific file.

When saving, the comment is reformatted to `// nolint:`. This make things worse since golangci-lint does not treat this as comment, and it adds 2 extra failures for not formatting the nolint comment properly.

This may need to be fixed by golangci-lint by accepting `// nolint:`, but I think the formatter should be smarter about such comments since this is a very popular tool.

It seems that the formatter need to learn about `//nolint:` comments by default, or support anything with this pattern: `^//[\w+]:`.

This is a pretty bad bug - your options are:

- Use another editor to edit the file and fix the broken comment
- Change the code to avoid lint issue
- Disable the specific linter globally in the project

All options are bad.

https://golangci-lint.run/usage/false-positives/#nolint-directive

### Environment

Zed: v0.162.3 (Zed)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
I am not able to reproduce.

Some background, Zed does not directly implement a formatter for Go or any other language, it uses Prettier, Language Server formatting or external formatters specified by users.  The issue you are experiencing is likely not a Zed issue, but instead with the upstream project handling formatting.
 
In the default configuration, I believe Zed will use gopls (uses go fmt under the hood) this is handled correctly and the `//nolint:foo` example remains untouched. For example:

```
package main

import "fmt"

func main() {

	//nolint:foo
	fmt.Println("Hello, World!")
}
```

Can you give an example file which formats incorrectly?
Are you perhaps using an old version of gopls or an external formatter?

**Comment by nirs** [comment]
You cannot reproduce since `//nolint:foo` works, but `//nolint: foo` does not, so we have an easy workaround.

We always use the second format since it is more natural and no tool we used so far tried to "fix" the second form.

Tools that work with both forms:
- `gofmt`
- vscode go formatter
- vim-go plugin

I see that go build comments use the first form:
```
//go:build !ignore_autogenerated
```

It is possible that the "official" spec for go machine readable comments is the first form, but since this is common and other tools are more permissive, I think Zed or the formatter it uses should support both forms.

**Comment by nirs** [comment]
OK, checking relevant source we have:

```
% git grep '//nolint:' | wc -l
     107
% git grep '//nolint: ' | wc -l
       6
```

Closing since using the first form is good way to avoid this issue.

**Comment by notpeter** [comment]
> Due to a change of go fmt inside go1.19.
> We have to enforce the directive style.
> 
> So the option allow-leading-space has been dropped.
> 
> The syntax of directives is: [a-zA-Z]+:[a-zA-Z].*.
> The spaces around : and after the // must be removed.
```
// nolint:foo // <-- malformed
//nolint :foo // <-- malformed
//nolint: foo // <-- malformed

//nolint:foo // <-- OK
```
> If you do that your IDE or go fmt will format the directive as a directive and it will not add extra space.

- Source: https://github.com/golangci/golangci-lint/issues/3110#issuecomment-1219153237
