### ISSUE TITLE
Rust example code in Zed doesn't run with the run icon

### ISSUE THREAD

**Issue by mylvghb** [zed-industries/zed#21044]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/2a5376cb-ee8c-4e69-ace0-aa4da7fdf897)
![image](https://github.com/user-attachments/assets/56834d64-0c72-4b50-8d85-57e500126007)
Clicking on this icon performs no action.

### Environment

Zed: v0.164.0 (Zed Dev 14ea4621ab98a315c4742c379723b8dbfd2087b9)
OS: Windows 10.0.19045
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GT 1030 || NVIDIA || 560.94

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by osiewicz** [comment]
Does it not even spawn the terminal? I suppose we might be not handling examples correctly, but I would still expect us to open up a terminal. Maybe the code to find the name of a binary target is failing silently and so is the task variable substitution?

**Comment by mylvghb** [comment]
> Does it not even spawn the terminal? I suppose we might be not handling examples correctly, but I would still expect us to open up a terminal. Maybe the code to find the name of a binary target is failing silently and so is the task variable substitution?

Yes, clicking on the **run** icon did not spawn the terminal, but manually typing the command `cargo run -p kv2 --example client` in the terminal worked fine for the example program.
