### ISSUE TITLE
Import downloaded vscode extension from marketplace website

### ISSUE THREAD

**Issue by 1mehdifaraji** [zed-industries/zed#21058]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now we can download vscode extensions from [vscode marketplace](https://marketplace.visualstudio.com/) under the resources of any extension.

![download-extension](https://github.com/user-attachments/assets/0a346cae-3e01-4622-96ba-224a58c494bf)

It would be great If we could just import the downloaded extension file which format is `.vsix` from zed extensions page `Install Dev Extension` button.

![install-dev-ext](https://github.com/user-attachments/assets/86e903cb-ccdd-4012-bc96-bc6102911f63)

Right now zed cannot import `.vsix` files.

![import-vsix](https://github.com/user-attachments/assets/577b9b13-b9e4-43e9-ac26-e78be1f62645)

### Environment

Zed: v0.162.4 (Zed)
OS: macOS 15.0.1
Memory: 8 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
"Just" when we'll support anything from VSCode extensions API, which most likely won't happen in the near future: https://github.com/zed-industries/zed/issues/4845
