### ISSUE TITLE
Not able to disable python language support

### ISSUE THREAD

**Issue by geohuz** [zed-industries/zed#21066]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

with the following user configuration:

```json
  "languages": {
    "Python": {
      "tab_size": 2,
      "enable_language_server": false
    }
  }
```

The pyright and pyflake still loads. I don't have type information for my project, can I disable pyright for type checking? I've tested the following options but failed:

```pyright.disableLanguageServices: true```

```json
  "lsp": {
    "pyright": {
      "python.analysis": {
        "typeCheckingMode": "off"
      }
    }
  }
```

By using the menu: open settings

None of them takes effect.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
I am not able to reproduce. When I add this to my settings, restart Zed and open a python file there are no pyright subprocess running.
```
  "languages": {
    "Python": {
      "enable_language_server": false
    }
  }
```

Do you perhaps have any extensions installed (BasedPyright, Python LSP, etc)?

**Comment by geohuz** [comment]
Ok, the problem is actually with the remote editing, I've ssh into the remote machine and changed the `.zed/settings.json` then no pyright

**Comment by notpeter** [comment]
Ah, gotcha. Glad you figured it out.
