### ISSUE TITLE
Adding "exclude" to pyproject.toml makes Pyright check the entire .venv folder?

### ISSUE THREAD

**Issue by ArturGalstyan1** [zed-industries/zed#21061]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First off, I'm not 100% sure if this is a bug, but it seems to be at least unexpected behaviour to me.

I've captured the problem in this video:

https://github.com/user-attachments/assets/be6ebadf-e9f4-4561-92d3-763d8a4dbce4

Basically, adding the exclude field in the pyproject.toml file makes pyright analyse the entire .venv folder, which takes a LOT of time and it keeps redoing it when you install new dependencies or restart the language server.

Steps to reproduce:
0. Install uv
1. `uv init && uv venv && source .venv/bin/activate && uv add torch equinox`
2. go to the `pyproject.toml` file and add: 
```
[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = ["scripts"]
```

### Environment

Zed: v0.164.0 (Zed Dev 114c4621433eb948b87fa5f4f41df8af6601f66e)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by osiewicz** [comment]
Thanks for a thorough report! It seems like an explicit decision on PyRight's end:
https://github.com/microsoft/pyright/issues/9057#issuecomment-2366938099
> If you provide an explicit exclude setting, there are no auto-excludes and you are responsible for specifying which directories. I suspect what's happening is that you have a virtual environment in your project folder, so pyright is treating all of the files within this virtual environment as project source files and attempting to type check them.
