### ISSUE TITLE
Zed freezes when opening link if browser is slow

### ISSUE THREAD

**Issue by marcospb19-cw** [zed-industries/zed#21065]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I opened the changelog and clicked on a PR link 

<img width="327" alt="image" src="https://github.com/user-attachments/assets/a315b8ea-46dc-4ffa-bab4-7c3a9ba4b7a0">

Zed waited for my browser to respond, but the browser took long to open, in the meanwhile, Zed was frozen.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 14.7.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by marcospb19-cw** [comment]
I can't re-reproduce this, and it's always possible that the freeze happened for other cause.

**Comment by notpeter** [comment]
Ok. Happy to reopen if you have any ideas how to reproduce.
Thanks for reporting.

**Comment by notpeter** [comment]
@marcospb19 That sounds plausible.

**Comment by marcospb19-cw** [comment]
@notpeter I confirm this is not an issue.

I managed to make my browser unresponsive by freezing the process, then I clicked on a bunch of links.

Next report I'll try to confirm before creating an issue 🙏 .
