### ISSUE TITLE
None keymap on windows

### ISSUE THREAD

**Issue by PoXel69** [zed-industries/zed#21068]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

# Issue Description:
When setting base_keymap to "None", no key presses are registered, and only mouse input works. This behavior is consistent and easy to reproduce.

## Steps to Reproduce:

- Set "base_keymap": "None" in the configuration file.
## Observed Behavior:

Key presses are entirely ignored, and only mouse input is functional.

### Environment

Zed: v0.164.0 (Zed Dev 114c4621433eb948b87fa5f4f41df8af6601f66e)
OS: Windows 10.0.22631
Memory: 7.9 GiB
Architecture: x86_64
GPU: Radeon RX 580 Series || AMD proprietary driver || 24.7.1 (AMD proprietary shader compiler)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Anything in your Zed.log?

**Comment by PoXel69** [comment]
I don't have Log file for my zed.
I checked zed installation path and `%appdata%/zed/`
I installed via scoop from this repo https://github.com/deevus/zed-windows-builds

**Comment by ConradIrwin** [comment]
I would expect that if you have the "None" keyboard then only typing letters and numbers will work. Things like space/tab/enter/ctrl-s/etc. are all defined by the keymap.

You almost certainly don't want "None", but use "VSCode" instead.
