### ISSUE TITLE
Discord invite link is broken

### ISSUE THREAD

**Issue by BrianHicks** [zed-industries/zed#21063]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Discord invite linked in several places around the documentation (https://discord.gg/zed-community) appears to be expired or broken. When I follow it, I get the following:

![A discord error page with a frowning gray poop emoji. The error message says "invite invalid. this invite may be expired, or you may not have permission to join." There is a button to "Continue to Discord"](https://github.com/user-attachments/assets/70c27d60-5dc0-4874-88cd-137b51ed12a4)

### Environment

n/a

**Comment by notpeter** [comment]
I'm updating all the links I could find to point at https://zed.dev/community-links which should always include the up-to-date invite.

Let me know if you find others in the future.

Thanks!

**Comment by BrianHicks** [comment]
Thank you! I was able to get in with that.
