### ISSUE TITLE
Make it possible to disable the assistant hint (^? to chat, ^enter to generate)

### ISSUE THREAD

**Issue by kityr** [zed-industries/zed#21106]
### Check for existing issues

- [X] Completed

### Describe the feature

This newly added hint is quite distracting as it follows the cursor and only appears on empty lines. Would be nice to have a settings toggle to disable it or have it disable itself after using the shortcuts a couple times.

I could neither find a way to turn it off, nor an already existing request for this feature.

### Environment

Zed: v0.163.2 (Zed Preview)
OS: Linux Wayland arch 20240913.0.262611
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 24.2.7-arch1.1

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/blob/f30de4852a5c672b4cb43ab528156c953f1c6eb0/assets/settings/default.json#L488-L495

You're looking for `assistant.show_hints` setting, disabling that (or the assistant) disables the hint.
