### ISSUE TITLE
navigate to test

### ISSUE THREAD

**Issue by drdozer** [zed-industries/zed#21111]
### Check for existing issues

- [X] Completed

### Describe the feature

I have run `cargo test --workspace` within the zed bash area. A test failed. The test ouptut contains both fully qualified names for the failing tests (e.g. `blame::tests::test_parse_git_blame_complex` and also panic messages with source code locations (e.g. `thread 'blame::tests::test_parse_git_blame_complex' panicked at crates/git/src/blame.rs:358:13`). It would be neat if either of these were hyperlinked back to the source.

### Environment

Zed: v0.162.5 (Zed)
OS: Linux X11 devuan 5
Memory: 62.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX TITAN X || NVIDIA || 535.183.01

**Comment by SomeoneToIgnore** [comment]
Does ctrl-click work for you, when you focus the terminal?

Works for me on macOS:

https://github.com/user-attachments/assets/a4ccb575-31d8-45a7-912c-0a5294db07ee

**Comment by drdozer** [comment]
Yes! Ctrl+hover makes it a clickable URL. I'd missed it because there was no visual cues that I should need a modifier. For example, the text didn't have a hover styling. Thanks.
