### ISSUE TITLE
clangd lint errors showing up (with linting disabled in settings.json)

### ISSUE THREAD

**Issue by tintor** [zed-industries/zed#21122]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

repro:
add   "linting": {  "enabled": false  } to settings.json
restart zed
open any *.cc file
clangd lint errors show up

### Environment

Zed 0.162.5
MacOS 13.6.3

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
>  add "linting": { "enabled": false } to settings.json

Can you elaborate on that?
This is not a part of Zed's settings.json valid properties, and https://zed.dev/docs/languages/cpp explicitly states you have to configure clangd via `arguments` that does not accept json.
