### ISSUE TITLE
"Failed to run python-refactoring" always shows up at bottom

### ISSUE THREAD

**Issue by pchalasani** [zed-industries/zed#21139]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See image. When I open a project (or have it open for a while), I see this warning at the bottom saying
"Failed to run python-refactoring. Click to show error".

I never asked for any refactor, so this shouldn't be showing up.

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 15.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="431" alt="image" src="https://github.com/user-attachments/assets/49f8d895-dcbe-49b0-b35d-1621e38b11f1">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
This is an issue with a 3rd party extension.
https://github.com/rowillia/zed-python-refactoring
It includes install instructions in their README.
Please open support requests as issue on that repo and not here.

Thanks!
