### ISSUE TITLE
rust analyzer shows errors on tokio when the program compiles and is missing autocompletion for the std library.

### ISSUE THREAD

**Issue by Houdiee** [zed-industries/zed#21149]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I opened a workspace for a new rust project, didn't configure rust analyzer or edit my lsp settings or anything like that, and I noticed that autocompletion was missing for the std library. I thought it wasn't that big of a deal until I ran "cargo add tokio --features=full" where I would get an error for the following code:
```
#[tokio::main]
async fn main() {
}
```
error: no sysroot

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland nixos 25.05
Memory: 31.3 GiB
Architecture: x86_64
GPU: AMD Radeon RX 5700 XT (RADV NAVI10) || radv || Mesa 24.2.6

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
That seems more like a rust-analyzer issue which Zed is not able to improve itself.

Does the same scenario works on VSCode?

**Comment by Houdiee** [comment]
> That seems more like a rust-analyzer issue which Zed is not able to improve itself.
> 
> Does the same scenario works on VSCode?
> 
> Also, what is in Zed's logs?

You're right. Same things happens in vscode. I thought it was a zed issue since I've never had this problem with neovim before, but that was before I switched to zed.

Thanks
