### ISSUE TITLE
cmd-. is toggling line comment not ToggleQuickAction

### ISSUE THREAD

**Issue by Dracks** [zed-industries/zed#21155]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Until some days ago, when pressing the shortcut cmd-. it was opening the quick actions menu (super usefull) which is the same shortcut than in vscode. But now cmd-. is toggling the line comment, and I cannot change this, I tried with the shortcuts configuration of zed and others. 

Is super annoying, the default shortcuts configuration say the shortcut is ok. I'm editing typescript files

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
I believe this is related to https://github.com/zed-industries/zed/issues/20425 but without more data (e.g. keyboard layout) it's not possible to say.

**Comment by Dracks** [comment]
Keyboard layout is Spanish qwerty. 

I also saw it, and yes it can be related, but not sure about that. 

Anything extra needed, please ask.

**Comment by SomeoneToIgnore** [comment]
Sorry, I am not in the context of this change, so I'd suggest posting this data into that issue, so @ConradIrwin could notice that case too.

**Comment by ConradIrwin** [comment]
@Dracks the default for Spanish cmd-. becomes cmd-ç. 

In v0.162.x I shipped a change to automatically localize keyboard shortcuts. https://zed.dev/blog/keyboard-localization

If you want to restore this behavior

```
{
    "use_layout_keys": true // for Zed v0.162 ..= v0.165
    "context": "Workspace",
    "bindings": {
      "cmd-.": "editor::ToggleCodeActions"
    }
}
```

In v0.166 `"use_layout_keys"` will become the default.

**Comment by Dracks** [comment]
Waw, I never thought the nightmare of shortkuts with internationalization.
