### ISSUE TITLE
Animated image preview support (GIF, WEBP)

### ISSUE THREAD

**Issue by kotkifotki** [zed-industries/zed#21160]
### Check for existing issues

- [X] Completed

### Describe the feature

As Zed already provides previews for other image formats like WEBP, JPG, and PNG, it would be beneficial to add support for previewing GIF formats as well, including animated WEBP.

Currently, when opening a GIF or animated WEBP file, the preview remains static, which doesn't accurately represent how the formats are intended to work.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

**Comment by xdBronch** [comment]
it seems gif support was added in #21274, webp still doesnt play

**Comment by xdBronch** [comment]
looks like this can be closed now after https://github.com/zed-industries/zed/pull/20778
