### ISSUE TITLE
"Open recent projects" closes the current project, but it shouldn't (UX Improvement)

### ISSUE THREAD

**Issue by lebe-dev** [zed-industries/zed#21201]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm working on project A and i want to open project B from "recent list". After selection Zed closes project A and opens project B. I'd like to work on N+1 projects in the same time.

**Workaround:** open folder as a new project, but you have to specify full path to project directory (it's super annoying :).

### Environment

OS:
- ArchLinux (latest) + wayland + sway
- MacOS 15.0.1

Zed: 0.162.5

### If applicable, add mockups / screenshots to help explain present your vision of the feature

it should open each project in a new window.

**Comment by SomeoneToIgnore** [comment]
<img width="562" alt="image" src="https://github.com/user-attachments/assets/1b92340c-dde2-41fd-9048-37896adf6aa5">

We have these placeholders for Linux too, those should suppose a way to open another window.

There's also a way to override this behavior via the keymap: 
https://github.com/zed-industries/zed/blob/84e11d164bbbc1a246f08bf2e8e0e4b747ce007f/assets/keymaps/default-linux.json#L372-L374
