### ISSUE TITLE
French keyboard key combinations interpretation differ from physical key pressed

### ISSUE THREAD

**Issue by bienoubien-studio** [zed-industries/zed#21200]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**When using a French Mac keyboard:**
1. Pressing `cmd-$` is interpreted by Zed as `cmd-]`
2. Pressing `cmd-/` is interpreted by Zed as `cmd->`

**Problem #1: Terminal Panel Toggle (`cmd-$`)**
- I want to use `cmd-$` to toggle the terminal panel
- My keybinding configuration:
```json
{
    "context": "Workspace",
    "bindings": {
      "cmd-$": "terminal_panel::ToggleFocus"
    }
}
```
- However, when I press `cmd-$`, Zed triggers `editor::Indent` (the default action for `cmd-]`) instead of my custom `terminal_panel::ToggleFocus` command
- This can be verified in the debug key context view where pressing `cmd-$` shows the correct key combination but executes the wrong command :

<img width="429" alt="image" src="https://github.com/user-attachments/assets/0d7fad60-93f5-43c6-8bc8-d2631588dabf">

**Problem #2: Comment Toggle (`cmd-/`) not working anymore**
- On French keyboards, the slash key is accessed via `cmd-shift-:`
- Previously, `cmd-shift-:` would trigger `editor::ToggleComments`
- To make it work, I now need to map `cmd->` instead:
```json
{
    "context": "Editor",
    "bindings": {
      "cmd->": ["editor::ToggleComments", { "advance_downwards": false }]
    }
}
```

<img width="343" alt="image" src="https://github.com/user-attachments/assets/429eda83-0464-499b-a168-c5b6ae72da97">

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by BeyondEvil** [comment]
Same issue on macos with Swedish keyboard.

**Comment by ConradIrwin** [comment]
In v0.162.x I shipped a change to automatically localize keyboard shortcuts, this applied to user keybinding files (which was in hindsight a mistake). https://zed.dev/blog/keyboard-localization

If you want to bind these keys you can use:

```
{
    "use_layout_keys": true // for Zed v0.162 ..= v0.165
    "context": "Workspace",
    "bindings": {
      "cmd-$": "terminal_panel::ToggleFocus"
    }
}
```

In v0.166 `"use_layout_keys"` will become the default.

**Comment by maelp** [comment]
@ConradIrwin I still have the issue
Zed: v0.192.8 (Zed) 
OS: macOS 15.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@maelp which problem exactly?

**Comment by maelp** [comment]
@ConradIrwin issue is mostly that I can't reliably set keymaps, it's utterly unintuitive on French keyboard, I have to "guess" somehow which key I should use with the "use_key_equivalents" option in order for the real shortcut I'm looking for to work...

I guess you could just do something a bit like the current "key context view" thing, but which shows also the currently pressed shortcut **before** the use_key_equivalents are applied

eg for me I wanted (on my French keyboard) that "cmd-/" does the "ToggleComments" action

if I just use "cmd-/" it doesn't work, if I use "cmd-/" + "use_key_equivalents" it doesn't work, I had to guess (by finding it on this post) that the correct mapping as to use "cmd->" + "use_key_equivalents", and then if I go to "key context view" and press the shortcut, it displays "cmd-/" (so the shortcut **after** key equivalents are applied) rather than "cmd->" (which would let me know which key I actually have to set in my config)... so I guess the pane should show both?

**Comment by ConradIrwin** [comment]
@maelp 

Testing this, on a French Azerty keyboard on macOS (where `/` is typed with `shift-:`); it seems to work how I'd expect without `use_key_equivalents`:

```
{ "bindings": { "cmd-/": "editor::ToggleComments" } },
```

<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/46a0ef09-74d9-4e2c-897b-71ae81a08d35" />

To trigger the shortcut I press cmd, shift, and the key just above right option (`:` with `/` on Azerty; or `.` with `>` on Qwerty).

It also works as you describe, with:

```
{ "use_key_equivalents": true, "bindings": { "cmd->": "editor::ToggleComments" } },
```

Can you take a screenshot of the key context view when it's not working for you?

(Fwiw, the action should also be available on Azerty by default as `cmd-:`, i.e. on the same key but without shift).

**Comment by maelp** [comment]
Also I have a weird bug: whenever I press "enter" to validate a field (eg when typing in the cmd+k search bar, or renaming a file in the interface, etc), it just inputs a "\n" string at that location, but it doesn't "validate" what I'm typing... how to have `enter` perform the correct action?

here's my keymap

```
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: open default keymap`
// from the command palette.
[
  {
    "context": "Workspace",
    "bindings": {}
  },
  {
    "context": "Editor",
    "use_key_equivalents": true,
    "bindings": {
      "cmd->": "editor::ToggleComments"
    }
  },
  // To avoid completions on "enter"
  {
    "context": "Editor && edit_prediction",
    "bindings": {
      "tab": "editor::AcceptEditPrediction",
      "enter": "editor::Newline"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "tab": "editor::Tab",
      "enter": "editor::Newline"
    }
  },
  {
    "context": "Editor && showing_completions",
    "bindings": {
      "tab": "editor::ComposeCompletion",
      "enter": "editor::Newline"
    }
  },
]
```

**Comment by maelp** [comment]
Okay seems this solve the issue:

```
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: open default keymap`
// from the command palette.
[
  {
    "context": "Workspace",
    "bindings": {}
  },
  {
    "context": "Editor",
    "use_key_equivalents": true,
    "bindings": {
      "cmd->": "editor::ToggleComments"
    }
  },
  // To avoid completions on "enter"
  {
    "context": "Editor && edit_prediction",
    "bindings": {
      "tab": "editor::AcceptEditPrediction",
      "enter": "editor::Newline"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "tab": "editor::Tab",
    }
  },
  {
    "context": "Editor && showing_completions",
    "bindings": {
      "tab": "editor::ComposeCompletion",
      "enter": "editor::Newline"
    }
  },
]

```
