### ISSUE TITLE
git worktrees after a `--bare` clone don't work

### ISSUE THREAD

**Issue by mrnugget** [zed-industries/zed#21210]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

We added support for git worktrees in #20164 but that doesn't seem to cover worktrees that were created from a `--bare` clone.

See comment here: https://github.com/zed-industries/zed/issues/4670#issuecomment-2500074480

To reproduce:

```
git clone --bare git@github.com:stefanluptak/stefanluptak.github.io.git
cd stefanluptak.github.io.git
git worktree add main
cd main
zed .
```

### Environment

N/A

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by m4salah** [comment]
Looking forward to this issue resolve, the git integration in bare repo is non exists.

**Comment by hargriffle** [comment]
Did this ever work? I feel like it did - but I could be misremembering 🤔
