### ISSUE TITLE
Setting to disable auto-includes

### ISSUE THREAD

**Issue by trbabb** [zed-industries/zed#21219]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm unsure if this is a Zed setting or a clangd setting, but in C++ the editor keeps adding unnecessary `#include` directives at the top of the file when it autocompletes something not in the current file.

Often these inserted includes are not necessary at all because they're already indirectly included by a different header that's already used. Adding unnecessary includes makes the file messier, makes include dependencies and cycles harder to trace, and can significantly affect compile times. In C++ include order can matter as well, so inserting these includes at a random location can cause problems.

Perhaps this setting already exists, but is there a way to turn this off? If not, I think this should definitely be an option.
Thanks!

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
This is definitely an upstream clangd thing.
I think what you're looking for is `--header-insertion=never`.
From `clangd --help`:
```
  --header-insertion=<value>          - Add #include directives when accepting code completions
    =iwyu                             -   Include what you use. Insert the owning header for top-level symbols, unless the header is already directly included or the symbol is forward-declared
    =never                            -   Never insert #include directives as part of code completion
```

So something like this (untested)
```
{
  "lsp": {
    "clangd": {
      "binary": {
        "arguments": ["--header-insertion=never"]
      }
    }
  }
}
```
See: https://zed.dev/docs/languages/cpp

**Comment by trbabb** [comment]
This is probably what I'm looking for. Thanks for the help!

**Comment by rcmz** [comment]
Thanks this was getting really annoying !
There should be a built-in GUI setting for this IMO
