### ISSUE TITLE
Unable to uninstall dev extension

### ISSUE THREAD

**Issue by schpet** [zed-industries/zed#21252]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in zed preview i'm not able to uninstall a dev extension

### Environment

Zed: v0.164.0 (Zed Preview)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/aa082ae5-6f0a-4a65-9d0a-e4ef0de38425

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-11-27T13:18:36.931663-08:00 [INFO] Language server with id 0 sent unhandled notification conversation/preconditionsNotification:
{
  "results": [
    {
      "type": "chat_enabled",
      "status": "ok"
    }
  ],
  "status": "ok"
}
```

after clicking uninstall:

```
2024-11-27T13:18:36.931663-08:00 [INFO] Language server with id 0 sent unhandled notification conversation/preconditionsNotification:
{
  "results": [
    {
      "type": "chat_enabled",
      "status": "ok"
    }
  ],
  "status": "ok"
}
2024-11-27T13:18:45.576137-08:00 [INFO] rebuilt extension index in 19.392333ms

```
</details>

**Comment by notpeter** [comment]
You can manually clean up dev extensions like so:

```sh
cd ~/Library/Application\ Support/Zed/extensions
rm -rf {installed,work}/haml
```

Let me know if that doesn't work.

**Comment by schpet** [comment]
@notpeter thanks for the tip 🙏🏻

just fyi in addition to those steps, i had to remove the key manually from 

~/Library/Application Support/Zed/extensions/index.json


otherwise it would re-create the deleted `~/Library/Application Support/Zed/extensions/installed/zed-haml` directory
