### ISSUE TITLE
Build with Nix fails

### ISSUE THREAD

**Issue by jaredramirez** [zed-industries/zed#21256]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Building with Nix fails:

```
$ nix build
error: hash mismatch in fixed-output derivation '/nix/store/yi7g7c8jp3anqbvp3wjiy7w8gjrh5412-zed-editor-nightly-vendor-staging.drv':
         specified: sha256-xL/EBe3+rlaPwU2zZyQtsZNHGBjzAD8ZCWrQXCQVxm8=
            got:    sha256-KURM1W9UP65BU9gbvEBgQj3jwSYfQT7X18gcSmOMguI=
error: 1 dependencies of derivation '/nix/store/v00knc87sfywzlw168vzdx1fd2jn3xgw-zed-editor-nightly-vendor.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pw6ag00xwbx6kxaiwhmqzilk9l543n3d-zed-editor-nightly.drv' failed to build
```

### Environment

```
macOS 14.3.1
nix (Nix) 2.24.10
```

Current `main` branch (`66ba9d5b4b27bc26571e6cb98b08cb46b7a0ae41`), I believe this started after https://github.com/zed-industries/zed/pull/21075 was merged

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by WeetHet** [comment]
Yeah, it was a bad idea to use a FOD and assuming that the hash would stay up to date without any checks in CI. I'm going to return to crane in a PR today, so we don't depend on the hash staying correct
