### ISSUE TITLE
Copilot chat logged out while autocomplete is logged in

### ISSUE THREAD

**Issue by toonvd** [zed-industries/zed#21255]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am signed in but still see the login prompt. Autocompletion is working.
Got copilot through our company profile, has Github enterprise.

If there is any useful debug info I can provide you, I would be happy to help.

<img width="637" alt="Screenshot 2024-11-27 at 23 33 02" src="https://github.com/user-attachments/assets/a78cb1bc-39e0-4fea-abfe-c07c7828c05f">

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

I could not find any relevant log entries.

**Comment by toonvd** [comment]
While tailing, I did find this during opening of the assistant:

```
2024-11-27T23:41:47.425884+01:00 [ERROR] error sending request for url (http://localhost:11434/api/tags)

Caused by:
    0: client error (Connect)
    1: tcp connect error: Connection refused (os error 61)
    2: Connection refused (os error 61)
```

**Comment by WeetHet** [comment]
I also had this issue. It's very difficult to reproduce, even removing zed's application support directory doesn't seem to trigger it after I've fixed it. What I've done is reset zed by removing `~/Application Support/Zed` and start copilot through the 0.151.1 release, which seems to have resolved this for me, making me think that the issue is with the new versions of zed somehow, but now I can't reproduce it which is even more weird, as copilot version seems to not have changed from when I've had this issue

**Comment by piedrahitac** [comment]
This is happening to me too with Copilot license provided by my employer.

Line completion works fine (and shows the status icon as logged in) but the assistant panel remains logged out with a warning that reads `LLM provider is not configured`.

Clicking on the sign in button from the assistant panel goes through all the usual flow and shows me the following:

![image](https://github.com/user-attachments/assets/caa92a5a-5154-4e96-9af0-1a68698804fc)

However, it remains logged out.

**Environment**
Zed: v0.163.2 (Zed)
OS: macOS 15.1.1

**Comment by fred-sch** [comment]
It appears that the format and location of the Github Copilot file, from which the OAuth token is extracted, have changed. This might be related to the changes introduced in https://github.com/zed-industries/zed/pull/20520. 

The reason Copilot chat is not functioning properly seems to be that the OAuth token is no longer stored in `.config/github-copilot/hosts.json`, but rather in `.config/github-copilot/apps.json`. Additionally, the format of this JSON file has changed slightly. The new file format is:
```json
{"github.com:randomAppId":{"user":"username","oauth_token":"token","githubAppId":"randomAppId"}}
```
whereas Zed is expecting a format like
```json
{"github.com":{"user":"username","oauth_token":"token","githubAppId":"randomAppId"}}
```
Thus, the easy workaround is to 
```bash
cp ~/.config/github-copilot/apps.json ~/.config/github-copilot/hosts.json
```
and then to edit the hosts.json file and remove `:randomAppId` after `github.com`.

I think this should work for Linux and macOS, on Windows the path would look like something like `C:\Users\Username\AppData\Local\github-copilot\apps.json`

**Comment by thoroc** [comment]
Is that fixed? I had to follow the work around to get it to work on v0.163.3

**Comment by reidq** [comment]
This is not working for me in Linux / PikaOS(Debian based distro)
