### ISSUE TITLE
How to have highlighting make every line an active line? 

### ISSUE THREAD

**Issue by rajerthat1** [zed-industries/zed#21261]
### Check for existing issues

- [x] Completed

### Describe the feature

I want only the line with the cursor to be the active line. 
I wish it remains:
"editor.line_number"
instead of
"editor.active_line_number"
for highlighted regions.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1280" alt="Screenshot 2024-11-27 at 5 48 50 PM" src="https://github.com/user-attachments/assets/4d7eca83-80da-4dcc-9c43-e5d85133be87">

**Comment by JosephTLyons** [comment]
Sorry for being late to get to this @rajerthat1, were you able to find some suitable solution via a settings configuration?

**Comment by rajerthat1** [comment]
I did not, but I actually prefer the way the line numbers are currently.
