### ISSUE TITLE
File finder starts up slow

### ISSUE THREAD

**Issue by cemoktra** [zed-industries/zed#21280]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It takes more than a second from pressing the keyboard shortcut to the dialog opening. This had been much faster in earlier versions.

### Environment

Zed: v0.163.2 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (TGL GT1) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

**Comment by cemoktra** [comment]
[zed_issue.webm](https://github.com/user-attachments/assets/62d405ec-998e-408b-8172-abc44854b938)

**Comment by SomeoneToIgnore** [comment]
Do you have any custom keymap bindings, that start with `ctrl-p`?

**Comment by cemoktra** [comment]
> Do you have any custom keymap bindings, that start with `ctrl-p`?

Oh yes. I do, so i need to find another key map for (p)and -> (n)ext
