### ISSUE TITLE
Guess language when pasting into fresh window

### ISSUE THREAD

**Issue by verhovsky** [zed-industries/zed#21293]
1. Press Cmd+n to open a new blank editor

2. Paste some code

Desired: the code is highlighted

Actual: I have to manually set the language of the code I pasted with the language selector

VS Code does this.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

**Comment by uncenter** [comment]
Duplicate of #4868 fwiw.
