### ISSUE TITLE
Cmd+d doesn't work as "Don't Save" for 2 or more files

### ISSUE THREAD

**Issue by verhovsky** [zed-industries/zed#21294]
1. Open a new blank file with cmd+n and type something into it
2. Open a second blank file with cmd+n and type something into it
3. Close Zed with cmd+q
4. You will see this dialog

<img width="275" alt="Screenshot 2024-11-28 at 11 19 51" src="https://github.com/user-attachments/assets/bf0fb100-a32d-47c7-b3a5-baab4f4b1e36">

5. Press cmd+d to select "Discard all"

Desired: editor quits

Actual: cmd+d has no effect

This works when you just have one file with unsaved changes but doesn't work with 2 or more.

On macOS cmd+D is the generic shortcut for "Don't save".

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
That's not how macos keyboard navigation of modal prompts works.

See my comment here for more:
- https://github.com/zed-industries/zed/issues/21658#issuecomment-2524081437
