### ISSUE TITLE
Prevent newlines when doing format

### ISSUE THREAD

**Issue by diuming** [zed-industries/zed#21312]
### Check for existing issues

- [X] Completed

### Describe the feature

How can I do for that?

![Screenshot 2024-11-29 at 1 38 04 PM](https://github.com/user-attachments/assets/1ca9599e-b71a-45f9-adba-e153f23498cb)

### Environment

Apple M1 macOS Sequoia  15.1.1
Zed 0.163.2

**Comment by 0xtimsb** [comment]
Zed uses Prettier to format you files. You can simply have `.prettierrc.json` in your project root and use below config. It specify the line length that the Prettier will wrap on.

```json
{
  "printWidth": 150
}
```

**Comment by diuming** [comment]
> Zed uses Prettier to format you files. You can simply have `.prettierrc.json` in your project root and use below config. It specify the line length that the Prettier will wrap on.
> 
> ```json
> {
>   "printWidth": 150
> }
> ```

It works but some statements not work.
take a look below.

html, body { height: 100%; }

**Comment by notpeter** [comment]
This is an upstream prettier configuration issue. You can verify this by running prettier on the command line and seeing the output.  Prettier is an opinionated formatter that offers little in the way of tunables, so you may not be able to get it to output exactly what you are looking for.

If you would prefer to use an alternate auto-formatter you can define a formatter in your settings [Formatter Docs](https://zed.dev/docs/configuring-zed#formatter).

For example if you would prefer to use `html-language-server` as your formatter for HTML:
```
  "languages": {
    "HTML": {
      "formatter": "language_server"
    }
  }
```
