### ISSUE TITLE
Search for overlapping terms of text on input fields

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21317]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When zed is in its minimum size while doing text search, see video.
A strange effect of overlapping text on input fields happens.

https://github.com/user-attachments/assets/346a88c8-562f-4784-a60d-ed50954beffa

### Environment

```
Zed: v0.164.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by danilo-leal** [comment]
@Angelk90 it will be soon! 😄 Thank you for the nudge.
