### ISSUE TITLE
language_servers Configuration Order Affects Server Availability

### ISSUE THREAD

**Issue by mrzzmrzz** [zed-industries/zed#21322]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When configuring multiple language_servers on a remote server or local machine, the order of the servers in the configuration affects their functionality:
	•	With  `"language_servers": ["ruff", "pyright", "!pylsp"]`, Pyright does not work, but Ruff works as expected.
	•	With  `"language_servers": ["pyright", "ruff", "!pylsp"]`, both Pyright and Ruff work properly.

### Environment

Zed Preview 0.164.0
macOS 15.1.1
Ubuntu 22.04 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
The order of the language servers in that array is significant [Zed Docs: Choosing Language Servers](https://zed.dev/docs/configuring-languages#choosing-language-servers)
<img width="759" alt="Screenshot 2024-12-13 at 17 42 51" src="https://github.com/user-attachments/assets/b28fec52-826d-4f20-82d0-2abc0b8ba5ab" />

If you are using both pyright and ruff, pyright needs to come first.
This is hinted at in the [Ruff Editor Setup Docs](https://docs.astral.sh/ruff/editors/setup/#zed)
<img width="910" alt="Screenshot 2024-12-13 at 17 40 52" src="https://github.com/user-attachments/assets/dc101e0e-170e-4918-9647-01b21661c48c" />

I'll add this to the [Zed Python docs](https://zed.dev/docs/languages/python).

Thanks for reporting.
