### ISSUE TITLE
Go to definition & Refactor feature is not working while I have installed Biome lsp enabled...  

### ISSUE THREAD

**Issue by a4arpon** [zed-industries/zed#21321]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't know why Zed team is not responding to this but I reported this issue several times... 

But after much frustration, I debugged the issue myself, and I am now reporting it again with proper resolution steps. 

Detailed Issue: https://github.com/zed-industries/zed/issues/20792 

Summary: F12 - Go to definition feature not working TypeScript project or refactor not working

Details:

I use Zed for my typescript projects. But I don't like using Prettier or ESLint. I prefer using Biome any other toolchain now a days. 

But Everything is working without these 2 features F12 I mean Go To definition, declaration and refactor. 

But this happens only when I have these 2 extensions installed :

Snippets Server: snippet-completion-server 

And Toolchain : biome

My Language servers config is:

```json
"language_servers": [
    "snippet-completion-server",
    "json-language-server",
    "biome",
    // "typescript-language-server",
    "vtsls",
    "typos-lsp",
    "typos"
  ]
  ```
  
  
  I tried turning off one at a time but both are causing the same issue. 
  
  
  I think these are causing the issues. 
  
  
  

### Environment

Zed: v0.163.2 (Zed)
OS: Linux Wayland ubuntu 24.10
Memory: 14.8 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.3-1ubuntu1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by h14h** [comment]
I have been running into the same issue, and was able to resolve it by having `"biome"` come after `"vtsls"` in the `language_servers` array (works the same for `"typescript-language-server"`).

I had this originally (after following [Biome's Zed docs](https://biomejs.dev/reference/zed/#project-based-configuration)):
```
// <workspace>/.zed/settings.json
{
  "language_servers": [ "biome", "vtsls" ]
}
```

And I was observing the same problem of "Go to definition" silently not working.

Things worked as-expected after switching to this:
```
// <workspace>/.zed/settings.json
{
  "language_servers": [ "vtsls", "biome" ]
}
```

I was able to confirm this fixed the issue by flipping the order a few times and running the `editor: restart language server` command each time I did.

Hope this helps!
