### ISSUE TITLE
Cmd+/ doesn't work anymore to comment/uncomment lines  CH-FR keyboard

### ISSUE THREAD

**Issue by SnapshotCiTy** [zed-industries/zed#21333]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Been using **Cmd+/** to comment in/out code - for years. Works on Sublime Text, VSCode, used to work on Zed until recently.
Using a CH-FR keyboard layout, this means that Cmd+/ is obtained with CMD+shift+7.

I have disabled in macOS **_System Settings / Keyboard / Keyboard Shortcuts / App Shortcuts / All Applications / Show Help Menu_** (by default using Cmd+Shift+/)

**_Zed / Settings / Open Default Key Bindings_** has this  line : 
      _"cmd-/": ["editor::ToggleComments", { "advance_downwards": false }],_
+ I am NOT using custom key bindings, only the defaults

**_Zed menu / Edit / Toggle Line Comment_** shows as shortcut : Cmd+' (apostrophe) (where is that coming from, it's not in the Default Key Bindings file?)

How to get it back to respecting what is specified in the Default Key Bindings file and use CMD+/ to comment / uncomment lines?

Is this a 'works for a US keyboard' but not for other locales, issue?

Thanks in advance for your help.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

**Comment by CordlessWool** [comment]
I have the same problem with a german keyboard, but even set it to an other shortkey had no effect.

**Comment by BeyondEvil** [comment]
Same issue with Swedish layout.

**Comment by ConradIrwin** [comment]
In v0.162.x I shipped a change to automatically localize keyboard shortcuts. This is the solution macOS uses (for people who haven't gone out of their way to disable the default shortcuts that take precedence in this case). https://zed.dev/blog/keyboard-localization

If you want to restore cmd-/ to toggle comments, you can:

```
{
    "use_layout_keys": true // for Zed v0.162 ..= v0.165
    "bindings": {
      "cmd-/": "editor::ToggleComments"
    }
}
```

In v0.166 `"use_layout_keys"` will become the default.

**Comment by BeyondEvil** [comment]
Where do I put that config @ConradIrwin ?

**Comment by ConradIrwin** [comment]
@BeyondEvil in ~/.config/zed/keymap.json (cmd-shift-p `zed: open keymap`).

**Comment by SnapshotCiTy** [comment]
doesn't work for me
says : "Incorrect type, expected array"  then when restarting zed, Cmd-/ doesn't comment / uncomment
see screenshot

![Screenshot 2024-12-09 at 10 28 10](https://github.com/user-attachments/assets/cc428a77-67e1-49cb-98a1-36cce44c6022)

**Comment by ConradIrwin** [comment]
@SnapshotCiTy sorry for the confusion, you need to wrap this excerpt in `[` and `]`; the file format is an array of these objects.

**Comment by SnapshotCiTy** [comment]
updated to 0.166.1 - and apparently it doesn't revert the behaviour, what am I missing ?

**Comment by SnapshotCiTy** [comment]
why is this issue closed ? In 0.166.1 the issue is still there.

Default key bindings clearly state :       "cmd-/": ["editor::ToggleComments", { "advance_downwards": false }],
but in the Edit menu the displayed shortcut is Cmd-' 

@ConradIrwin said that with 0.166 some default thing that had been 'missed' will be the default and that some manual overriding of the keybindings with "use_layout_keys" will not be needed anymore. Not sure what it means, what is clear is that there is a discrepancy between the behavior of the app + what is shown in the edit menu as a shortcut - and what is explicitly stated in the key bindings config file.

I hope Zed is not / will not be another one of those US-centric companies where all is great for us-keyboard users and international users get a confusing mess of shortcuts.

**Comment by CordlessWool** [comment]
When I define "use_layout_keys" and the binding in my own keymap it works, but it does not seem to work in the default configuration.

**Comment by blynx** [comment]
By now it is apparently `use_key_equivalents`:

```
{
    "context": "Editor",
    "use_key_equivalents": false,
    "bindings": {
        "cmd-/": ["editor::ToggleComments", { "advance_downwards": false }]
    }
}
```

Which fixed it for me with a German keyboard layout on macOS.

**Comment by SnapshotCiTy** [comment]
@blynx  thanks. Any idea where this is all documented?

**Comment by reneoelke** [comment]
This works for me (Zed 0.173.11, macOS 15.3.1, German keyboard layout QWERTZ):
```
# ~/.config/zed/keymap.json
[
  {
    "context": "Editor",
    "use_key_equivalents": false,
    "bindings": {
      "cmd-/": ["editor::ToggleComments", { "advance_downwards": false }]
    }
  }
]
```

**Comment by Morpa** [comment]
Thank you @reneoelke  it worked just fine here

**Comment by emilbratt** [comment]
> This works for me (Zed 0.173.11, macOS 15.3.1, German keyboard layout QWERTZ):
> 
> ```
> # ~/.config/zed/keymap.json
> [
>   {
>     "context": "Editor",
>     "use_key_equivalents": false,
>     "bindings": {
>       "cmd-/": ["editor::ToggleComments", { "advance_downwards": false }]
>     }
>   }
> ]
> ```

Did the trick for me (macOS). Thanks! :)

**Comment by AMDphreak** [comment]
I don't like tricks. How about reopening this issue and fixing it at the source? My key combination (US keyboard) is defaulted to Ctrl K + Ctrl C , and it sucks.
