### ISSUE TITLE
Number of different search results on the same project

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21342]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As you can see from the images, searching for the same text on different [IDEs](url) results in different numbers of results.

Webstorm:
<img width="659" alt="Screenshot 2024-11-29 alle 17 52 20" src="https://github.com/user-attachments/assets/effd92ed-d6a6-4e58-87c1-cbdb80db033e">

vscode:
<img width="398" alt="Screenshot 2024-11-29 alle 17 53 01" src="https://github.com/user-attachments/assets/49515cf5-084f-4e03-8345-c91b4c264ac1">

online vscode:
<img width="397" alt="Screenshot 2024-11-29 alle 17 55 14" src="https://github.com/user-attachments/assets/c6a8554c-b628-42b1-8921-9aefd455fe3c">

<img width="407" alt="Screenshot 2024-11-29 alle 18 01 25" src="https://github.com/user-attachments/assets/67568cfa-79a0-44e1-a006-73522b46ae56">

Zed:
<img width="694" alt="Screenshot 2024-11-29 alle 17 53 25" src="https://github.com/user-attachments/assets/132b27e6-1ac8-4469-bc6d-6f4c9b386898">

Edit:

Applying this on vscode:
<img width="498" alt="Screenshot 2024-11-29 alle 18 00 02" src="https://github.com/user-attachments/assets/4574488b-3109-4bc1-8099-e3cf48bc2a99">

In this case there are no exclusions, does zed do it automatically?

### Environment

```
Zed: v0.164.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Yes. Zed applies a number of `file_scan_exclusions` by default:
https://github.com/zed-industries/zed/blob/c021ee60d67cfbecb800f33f5d644a201a6bb567/assets/settings/default.json#L669-L678

Given that we match the VSCode number of results (55) I'm going to close this as unactionable.
