### ISSUE TITLE
Find in project as side panel

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21344]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be possible to have the find in project as a side panel.

Having it on the side would allow you to have the open files on the right, while on the left you do the search.
Instead of having a tab just for the search.

Vscode:

<img width="833" alt="Screenshot 2024-11-29 alle 18 17 16" src="https://github.com/user-attachments/assets/5208974c-7a2d-4f6d-b0cb-974900450996">

### Environment

```
Zed: v0.164.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by SomeoneToIgnore** [comment]
We have an outline panel for this, and no other plans for now.

**Comment by TeijiW** [comment]
I needed to have the same requirements as the issue's author to understand how and why to use the outline panel. It works very well.
