### ISSUE TITLE
Jump to unsaved buffer from project search results in duplicate tabs

### ISSUE THREAD

**Issue by neunato** [zed-industries/zed#21369]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I would expect the existing tab to be reused.

https://github.com/user-attachments/assets/1a1496aa-8be7-442a-9f7d-802a90e17018

### Environment

Zed: v0.163.2 (Zed)
OS: Linux X11 arch unknown
Memory: 62.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 with Max-Q Design || NVIDIA || 565.57.01

**Comment by cole-miller** [comment]
This seems to be because the unsaved buffer doesn't have a `ProjectEntryId`:

https://github.com/zed-industries/zed/blob/a76cd778c4eaf6af69f68f31190563836e25fb89/crates/workspace/src/workspace.rs#L2715-L2740
