### ISSUE TITLE
Cannot open files except in first window

### ISSUE THREAD

**Issue by ChaiTRex** [zed-industries/zed#21377]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a new window.
2. Add a folder to the first window's project.
3. Open a second new window.
4. Add a different folder to the second window's project.
5. With the second window focused, open a file outside the project directories.
6. See that the file opens in the first window instead of the second window.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

**Comment by pjv** [comment]
Existing issues: #16426 #17401

**Comment by ChaiTRex** [comment]
Thanks. It seems like #17401 is the same.
