### ISSUE TITLE
Go to definition split does not split

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#21380]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Command "editor::GoToDefinitionSplit" does not split in the latest Zed preview 0.164.0. It used to be worked in older version.

- Open a Python file
- Input `import os`
- Run `"editor::GoToDefinitionSplit"`
- The window is not split.

### Environment

Zed: v0.164.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
Seems to work for me on simple case, what else are we missing?

https://github.com/user-attachments/assets/6e12efce-ff88-4559-8de7-175967b5ec94

**Comment by failable** [comment]
I have tried multiple tests, sometimes it works sometimes it doesn't. Or maybe it work for some window / project, while others not. I haven't seen this issue before.

Reopening  the project does not solve the issue.

https://github.com/user-attachments/assets/c3789720-383e-4e9a-bf41-38888d39e38c

The video show that it dose not work for the first project but do work for the second and third projects.

**Comment by failable** [comment]
After some trials and restarting, I don't seem to be able to reproduce the issue now.

**Comment by SomeoneToIgnore** [comment]
Next time it would be useful to check Zed logs and, more importantly, LSP logs: I suspect there might be multiple Python LSP servers interfering somehow.
