### ISSUE TITLE
Alt-combination keybindings can not be forwarded to terminal

### ISSUE THREAD

**Issue by lorefnon** [zed-industries/zed#21387]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello, thanks for creating & maintaining Zed. It has been a great experience so far. 

To forward keybindings to terminal, the docs recommend following approach in keymap.json: 

```
{
    "context": "Terminal",
    "bindings": {
      "ctrl-b": ["terminal::SendKeystroke", "ctrl-b"]
    }
}
```

This works for above (a keybinding which uses ctrl) but not for keybindings that use `alt`. 

```
{
    "context": "Terminal",
    "bindings": {
      "alt-b": ["terminal::SendKeystroke", "alt-b"]
    }
}
```

The above does suppress the action on zed side, but the terminal does not seem to be receiving it. So I can't use alt-b to move the cursor back by a word

### Environment

Zed: v0.163.2 (Zed)
OS: Linux X11 zorin 17
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

**Comment by notpeter** [comment]
This is likely what you need:

```
   "terminal": {
        "option_as_meta": true
    }
```

**Comment by lorefnon** [comment]
Thank you. This worked.
