### ISSUE TITLE
IME Menu does not close when moving cursor, editing, switching tabs

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/zed#21392]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* Open an editor
* On a US keyboard layout, hold down the `a` key
* See the IME menu open, showing composition options (à, á, etc)
* Move the cursor, (or backspace)
* 💥 The menu stays open (even if you switch to a different tab)

### Environment

Zed: v0.165.0 (Zed Nightly 57a45d80ad1e3d2b7c87d68fc4e3499527543d1f)
OS: macOS 14.3.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by maxbrunsfeld** [comment]
@ConradIrwin Could this be related to the recent IME changes?

**Comment by opsnull** [comment]
Same problem here. I'm also US keyboard and using[ chinese weixin input method](https://z.weixin.qq.com/).

**Comment by rtfeldman** [comment]
I bisected this and https://github.com/zed-industries/zed/commit/96deabfb7816094e2591ab39de2806b92bf6e453 introduces the regression; the commit before it is fine.

**Comment by ConradIrwin** [comment]
Thanks, will take a look
