### ISSUE TITLE
Allow Extensions to Create and Manage Customizable Side Panels

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21400]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to propose a feature that allows developers to create extensions that add customizable side panels to the Zed interface. 

**Key features of the proposed feature:**

1. Left and right side panels:
- The ability to dock the side panel on both the left and right sides of the UI.
- Developers should be able to easily move the side panel between the two sides to suit their workflow.

2. Side panel UI customization:
- Extensions should have the ability to define the content of the side panel, including custom UI components (such as buttons, tables, text inputs, selectors, viewports, etc.).

### Environment

```
Zed: v0.164.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
I'm going to go ahead and close this as unactionable. Yes, at some point in the future we intend to support visual elements, but this issue as-is is not actionable and is just clutter in the issue tracker. Thanks
