### ISSUE TITLE
Ruff "lineLength" Configuration Not Working in Zed 0.164.2

### ISSUE THREAD

**Issue by ZuidVolt** [zed-industries/zed#21434]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After updating to Zed version 0.164.2, the Ruff line length configuration is not being respected. Despite setting a line length of 120 in the configuration, the editor defaults to a line length of 80 when formatting or saving files

Current configuration:
```jsonc
    "Python": {
      "tab_size": 4,
      "language_servers": ["ruff"],
      "format_on_save": "on",
      "formatter": [
        {
          "code_actions": {
            "source.organizeImports.ruff": false,
            "source.fixAll.ruff": false
          }
        },
        {
          "language_server": {
            "name": "ruff"
          }
        }
      ],
      "show_inline_completions": true
    },
    "lsp": {
      "ruff": {
        "initialization_options": {
          "settings": {
            "lineLength": 120,
            "lint": {
              "extendSelect": ["I"]
            }
          }
        }
```

### Environment

OS: macOS Sequoia
CPU: Apple M3
Memory: 16 GB
Zed 0.164.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by ZuidVolt** [comment]
I think this is the same issue as #21448

**Comment by ZuidVolt** [comment]
Log update:
With the configuration from the top message, I'm getting:

2024-12-04T09:34:43.803095+08:00 [INFO] attempting to start language server "ruff", path: "/Users/usr/Dev/vscode/ping-search-engines/benchmark_search_engines.py", id: 3
2024-12-04T09:34:43.803654+08:00 [INFO] starting language server process. binary path: "/Users/usr.venv/bin/ruff", working directory: "/Users/usr/Dev/vscode/ping-search-engines", args: ["server"]
2024-12-04T11:28:52.58072+08:00 [WARN] no language server found matching 'ruff'

**Comment by notpeter** [comment]
@ZuidVolt I am not able to reproduce.

I believe it may because your settings are incorrect, `lsp` should be a top-level settings key (two space indent) not under "languages" (four space indent). Or it could just be a copy paste indentation error 🤷.

I am able to use the following settings.json:
```
{
  "languages": {
    "Python": {
      "auto_indent_on_paste": false,
      "language_servers": ["ruff"],
      "format_on_save": "on",
      "formatter": [
        {
          "code_actions": {
            "source.organizeImports.ruff": false,
            "source.fixAll.ruff": false
          }
        },
        {
          "language_server": {
            "name": "ruff"
          }
        }
      ]
    }
  },
  "lsp": {
    "ruff": {
      "initialization_options": {
        "settings": {
          "lineLength": 120
        }
      }
    }
  }
}
```

https://github.com/user-attachments/assets/45c23d25-e62b-4648-969f-1cda83275df4

If you are still seeing this, can you create a mini repo with a `.zed/settings.json` with a minimal settings that reproduces the issue when your user settings.json is empty (`{}`).

**Comment by notpeter** [comment]
Just re-reading your second comment:
> 2024-12-04T11:28:52.58072+08:00 [WARN] no language server found matching 'ruff'

Do you have the `ruff` extension installed?

**Comment by ZuidVolt** [comment]
after update the newest version ZED the issue seem to be fixed
