### ISSUE TITLE
fill-paragraph

### ISSUE THREAD

**Issue by hillegass** [zed-industries/zed#21459]
### Check for existing issues

- [X] Completed

### Describe the feature

I write a lot of latex and markdown.  These ignore whitespace, but in consideration to other authors who will edit the file, it is considered polite to keep the number of columns down to what can be seen on a screen.  On emacs, I use ESC-q (AKA fill-paragraph), which creates/deletes linebreaks and places the cursor at the end of the paragraph..  Could you include a similar functionality in Zed?

### Environment

Zed: v0.163.3 (Zed)
OS: macOS 15.1.1
Memory: 36 GiB
Architecture: aarch64

**Comment by hillegass** [comment]
For reference here is the elisp file.  Look for "defun fill-paragraph".
[fill.txt](https://github.com/user-attachments/files/17994839/fill.txt)

**Comment by JosephTLyons** [comment]
Hey @hillegass  - I'm not too familiar with Emacs - is this similar to `editor: rewrap`? Rewrap tries to rewrap all the text to fit into your preferred line length, however, it doesn't move your cursor to the end.

**Comment by hillegass** [comment]
Ah, that's it! (I couldn't find it in the documentation. Is it in there?)  Thank you, and I'm sorry for the hassle.

**Comment by JosephTLyons** [comment]
> Ah, that's it! (I couldn't find it in the documentation. Is it in there?) Thank you, and I'm sorry for the hassle.

Absolutely no issue whatsoever. Always happy to help, where I can.
