### ISSUE TITLE
Option to Hide Profile Picture

### ISSUE THREAD

**Issue by davidbarsky** [zed-industries/zed#21464]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello! I'd love to have the option to hide my profile picture in the title bar. This is potentially an odd thing to complain about, but I find that little profile picture of myself to be somewhat distracting/jarring when placed against my custom theme. I'd love to have an option to switch that profile picture to switch to the signed-out dropdown button!

### Environment

Zed: v0.164.1 (Zed Preview)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

This is the current signed-in state:

<img width="207" alt="Screenshot 2024-12-03 at 3 21 12 PM" src="https://github.com/user-attachments/assets/569093ee-124c-4eb9-a5a4-f9aedfbbcd98">

I would be pleased with an option that gets me the signed-out state with _just_ the downward facing arrow (and without the "sign in" text):
<img width="204" alt="Screenshot 2024-12-03 at 3 26 04 PM" src="https://github.com/user-attachments/assets/bb532271-fb6c-4799-bd05-911a2091ea3b">

**Comment by notpeter** [comment]
See also:
- https://github.com/zed-industries/zed/issues/5120
