### ISSUE TITLE
Cannot configure GitHub Copilot Chat in Assistant Panel

### ISSUE THREAD

**Issue by afossa** [zed-industries/zed#21499]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I cannot use GitHub Copilot as LLM provider in the Assistant Panel, even though I am logged in and the inline suggestions are working.

What I did:
- click on the Copilot icon in the bottom-right corner, and follow the instruction to login
- The Copilot icon reflect the fact that I am logged in, and the inline suggestions when I am editing a file are working
- I open the Assistant Panel and go to "Configure Providers", here Copilot shows a "Sign in" button
- If I click on the button, a pop-up appears saying "Copilot Enabled!"
- However, when I open a new chat I get a warning "LLM provider is not configured" and I cannot use the chat

I also have this in my settings (automatically added by Zed)
```json
  "assistant": {
    "default_model": {
      "provider": "copilot_chat",
      "model": "gpt-4o"
    },
    "version": "2"
  },
```

I am experiencing this problem on macOS Sequoia aarch64.
I am also logged in with the same Copilot account on an Intel Mac (macOS Sonoma) and a workstation with Ubuntu 22.04, and in these other machines the chat works fine.

### Environment

Zed: v0.163.3 (Zed)
OS: macOS 15.1.1
Memory: 48 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by yoleuh** [comment]
I think there is a workaround: https://github.com/zed-industries/zed/issues/21255#issuecomment-2508940898

Should be fixed by #21360

**Comment by afossa** [comment]
Yes, the workaround fixed the issue. Thanks!

**Comment by AstralBaby** [comment]
still the same fkn issue oh my god.
