### ISSUE TITLE
Dynamic themes

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#21517]
### Check for existing issues

- [X] Completed

### Describe the feature

This is an idea i've had for a while that I've not seen in any code editor *yet*.

On macOS we have dynamic wallpapers that can change appearance and color depending on the time of the day, darkest wallpaper being applied at midnight and then a semi-dark/light in the morning,  light during the day and a semi-dark/light at the evening - we could map this to themes - so a theme could "bundle" 4 (or more) versions of itself where the user can switch between any of them if they'd like to (as regular) or enable a dynamic option which cycles between them depending on the time of the day.

As a bonus; it'd be really nice for themes to have access to the system accent color - which would allow themes to pick the preferred system color for accents in their theme, which i think would also help improve the "dynamicity" of themes, at least on macos.

### Environment

none

**Comment by jansol** [comment]
There is already the option to switch automatically between a "light" and a "dark" theme based on the system appearance, so if your system is set up to automatically switch between light and dark mode you can sort of achieve the effect you describe:

```json
  "theme": {
    "dark": "Ayu Glass Dark",
    "light": "Ayu Glass Light",
    "mode": "system"
  }
```

**Comment by jansol** [comment]
As for the accent color, I think that warrants its own separate issue. The concept does exist on all 3 desktops so it is likely possible to make use of it in zed in a way that is consistent across platforms.

**Comment by nervenes** [comment]
It seems undesired so i'll let go off the idea so closing this one now, but i'll open a new issue for the accent color 👍 thanks

**Comment by jansol** [comment]
FWIW, [XDG Desktop Portal has an API for retrieving the accent color](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html) and Zed is already using the portal for various things so that looks like it could be a relatively low friction path forward for that.
