### ISSUE TITLE
Rename duplicates zig enum elements

### ISSUE THREAD

**Issue by LDprg** [zed-industries/zed#21515]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use Zed as an editor for a project, but I noticed a bug when renaming a zig enum element. When renaming an enum element, it seems to duplicate the var name (renaming to "test" would result in "testtest").

However, if this enum element is used in another file it gets renamed correctly, only seems to affect the definition.

Not sure if related, but when renaming a lot it stops working, causing a zls crash most of the time.

How to reproduce:
1) clone my project or download file: https://github.com/LDprg/UniNote/blob/254f9654389c96bbe74b7a9daae691954b9c7e0e/src/event.zig
2) rename any enum element to any other name with zed
3) See the duplicate name after confirmation

### Environment

Zed: v0.163.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 14.9 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV GFX1103_R1) || radv || Mesa 24.3.0-cachyos1.2

**Comment by SomeoneToIgnore** [comment]
Using the example enum and renaming `quit` in an arbitrary document produces the following LSP messages:

```
// Send:
{"jsonrpc":"2.0","id":41,"method":"textDocument/rename","params":{"textDocument":{"uri":"file:///Users/someonetoignore/work/other/ghostty/src/crash/main.zig"},"position":{"line":28,"character":4},"newName":"quitssss"}}

// Receive:
{"jsonrpc":"2.0","id":41,"result":{"changes":{"file:///Users/someonetoignore/work/other/ghostty/src/crash/main.zig":[{"range":{"start":{"line":28,"character":4},"end":{"line":28,"character":8}},"newText":"quitssss"},{"range":{"start":{"line":28,"character":4},"end":{"line":28,"character":8}},"newText":"quitssss"}]}}}
```

seems that zls produces two identical changes, which Zed honestly applies.

While Zed definitely should do better and deduplicate such changes, it's quite odd to see such responses form the server, and IMO worth reporting to zls.
