### ISSUE TITLE
Auto-complete for Typescript LSP not working correctly

### ISSUE THREAD

**Issue by wagnrd** [zed-industries/zed#21516]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Auto-complete suggestions have incomplete information on Typescript LSP. However this only seems to happen when typing either a single character or very quickly. On hover you get the info, though. 
I think the LSP takes some time to respond the whole info and the suggestions don't update if when they are finally present.

This behaviour is consistent throughout any project using Typescript (Next.js, Svelte Kit, Node). Tested on MacOS and Linux with 4 different machines.

Closed but unresolved issue with the same bug and many people experiencing it: https://github.com/zed-industries/zed/issues/7198#issuecomment-2307047941

### Environment

Mac: MacOS 14.6.1 M1, 32 GB Ram
Linux: Fedora 40, 32 GB Ram, x64 CPU
Zed Version: Preview 0.164.0

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![grafik](https://private-user-images.githubusercontent.com/15080468/360935404-8794f494-a87b-49c0-a5d3-dca78517d420.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDIzOTgsIm5iZiI6MTczMzMwMjA5OCwicGF0aCI6Ii8xNTA4MDQ2OC8zNjA5MzU0MDQtODc5NGY0OTQtYTg3Yi00OWMwLWE1ZDMtZGNhNzg1MTdkNDIwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4NDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDQ2MDUyOGEwNzIyYjdlYjgzOWJhYTc0YzdhMGM5NmFhMGI0ZWUxOWJjZTAwOGMyMDdiZjM1ZGQxYjMyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0uBMcLzPTVk2KcENA8j8T1eqcNPu1groH68-F5bTnmU)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by JosephTLyons** [comment]
Hey @wagnrd, does this other issue accurately describe what you are experiencing? Just want to consolidate, if possible.

- https://github.com/zed-industries/zed/issues/20715

**Comment by wagnrd** [comment]
> Hey @wagnrd, does this other issue accurately describe what you are experiencing? Just want to consolidate, if possible.
> 
>     * [Slow completions/suggestions (Typescript) #20715](https://github.com/zed-industries/zed/issues/20715)

Hi, no the suggestions come fast enough, but they are incomplete.

**Comment by wagnrd** [comment]
> Hey @wagnrd, does this other issue accurately describe what you are experiencing? Just want to consolidate, if possible.
> 
>     * [Slow completions/suggestions (Typescript) #20715](https://github.com/zed-industries/zed/issues/20715)

Hi, no the other issue is about the appearance of the suggestions, and this issue is about the content.

**Comment by wagnrd** [comment]
@SomeoneToIgnore Thank you very much for the quick fix!
But the issue is not entirely resolved. The the information in the suggestions panel are now shown correctly, but only for the selected option. Every other entry still hasn't all the info, until you select/highlight them (e.g. navigating with arrow keys).

![ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/c70f43ae-15dc-432c-8cdd-9ed871e99821)

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/21705 is supposed to take care of it, albeit we might alter the behaviour later.
