### ISSUE TITLE
type cmd-escape  get dot 

### ISSUE THREAD

**Issue by marblecaco3** [zed-industries/zed#21520]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

  i often type cmd-s and escape, it's weird to got something repeated

https://github.com/user-attachments/assets/f9dd93e6-2ef2-4bbb-aa10-d8bb81556c7d

### Environment

Zed: v0.163.3 (Zed)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
That's odd. I can reproduce with `com.apple.keylayout.US` too.
If I actually map it:
```
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-escape": "editor::Tab"
    }
  }
]
```
Then in correctly shows `cmd-escape` 🤔 
<img width="413" alt="Screenshot 2024-12-04 at 16 25 31" src="https://github.com/user-attachments/assets/e7306a28-f5ce-4048-b39c-abf1b8d954f3">

**Comment by marblecaco3** [comment]
https://github.com/user-attachments/assets/f73defa6-5d28-4c36-bbf8-046613f7c96f

I tried bind cmd-escape to null  and editor::Cancel, don't work. and editor::Tab insert space in vim normal mode.
