### ISSUE TITLE
Markdown preview image rendering crashes with empty alt text / title

### ISSUE THREAD

**Issue by uncenter** [zed-industries/zed#21534]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Add `![]()` or `![](https://picsum.photos/200/300)` (doesn't matter if there is an image link or not, depends solely on the alt text presence as far as I can tell) to a markdown file.
2. Open the markdown preview panel, and then focus back on the text/buffer (this is important, it does't crash until you do this).

Crashes with the following error:
```
Thread "main" panicked with "index out of bounds: the len is 0 but the index is 0" at crates/markdown_preview/src/markdown_elements.rs:28:49
```

Which is this line here:
https://github.com/zed-industries/zed/blob/3019960f83e6852a5b9ce3706f88addce3aa2983/crates/markdown_preview/src/markdown_elements.rs#L28

Looks like it doesn't account for the length of the vec of the parsed elements being zero. Is the inside of the alt text area being parsed as markdown text? I would assume you can only use plaintext inside the brackets there.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 18 GiB
Architecture: aarch64

**Comment by jychen6688** [comment]
https://github.com/user-attachments/assets/faf9e936-a0fc-4afb-b85c-adae378e6179

there is a example
