### ISSUE TITLE
Rust kernel support for Jupyter Notebook style cells 

### ISSUE THREAD

**Issue by aaelony** [zed-industries/zed#21546]
### Check for existing issues

- [X] Completed

### Describe the feature

I hope this already exists, but I could not find documentation.

Notebooks are used in data science and research purposes to capture code and results output. Cells contain either the output of computation or markdown text descriptions. 

Zed documentation about using a repl [here](https://zed.dev/docs/repl) exists for Python kernels but there is no mention of using **Rust as a kernel**.

1. If one used Rust for research purposes in Zed, how might a Notebook be set up and viewed in Zed?
2. The main feature request is a "notebook" of some kind that shows the Rust commands followed by the data frame (e.g. polars) or plot (png) for each cell, with the ability to store this in an ipynb format.

### Environment

n/a

### If applicable, add mockups / screenshots to help present your vision of the feature

Just like a Jupyter Python notebook, but with a Rust language kernel (if possible).

**Comment by aaelony** [comment]
Found documentation.

**Comment by lrisguan** [comment]
> Found documentation.

It's very kind of you if you can tell me where the documentation is.

**Comment by aaelony** [comment]
cargo install jupytercargo install evcxr_jupyterOn Aug 30, 2025, at 07:58, gzqccnu ***@***.***> wrote:﻿gzqccnu left a comment (zed-industries/zed#21546)

Found documentation.

It's very kind of you if you can tell me where the documentation is.
