### ISSUE TITLE
clangd: Generate diagnostics for all files in project, regardless of which ones are open

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#21547]
### Check for existing issues

- [X] Completed

### Describe the feature

It appears that diagnostics are only generated for files that are actually open in the editor. This always felt a bit awkward in the All Diagnostics multi-buffer. Getting diagnostics indicators in the project panel recently has further accentuated this, as the markers will appear and disappear depending on what tabs are open. (This also means that the diagnostics in the project panel are not helpful)

### Environment

Zed: v0.164.0 (Zed Dev 61e8d0c39bd1171f31952da25708f04c7cbc82bb)
OS: Linux Wayland ubuntu 24.04
Memory: 31.3 GiB
Architecture: x86_64
GPU: Radeon Vega Frontier Edition (RADV VEGA10) || radv || Mesa 24.0.9-0ubuntu0.2

**Comment by notpeter** [comment]
I think this is actually language server specific.  For example rust-analyzer will surface errors across your project, but definitely others only do diagnostic checks on files you open.

Which language / LSP are you seeing this?

**Comment by jansol** [comment]
In my case, clangd in C/C++ projects that use cmake (i.e. can generate a `compile_commands.json` that covers all relevant files). Specifically it caught my attention with https://github.com/pocl/pocl/

**Comment by jansol** [comment]
Looks like this is indeed a clangd thing: clangd/clangd#1973
