### ISSUE TITLE
When certain symbols are pressed, snippet completion will be triggered

### ISSUE THREAD

**Issue by rendaoer** [zed-industries/zed#21576]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

When you press a single quote, semicolon, bracket, etc., snippet completion will be triggered, even if the completed snippet has nothing to do with these symbols
(A snippet of the Rust bevy engine I use)

<img width="325" alt="image" src="https://github.com/user-attachments/assets/9cd9e35b-e4ac-4269-8b7f-0c1753bc478b">
<img width="278" alt="image" src="https://github.com/user-attachments/assets/56e8ad19-8bc2-47d2-8a70-e6a831837d68">
<img width="275" alt="image" src="https://github.com/user-attachments/assets/362fd01b-ca13-4386-b1e7-67f00d47b875">
<img width="279" alt="image" src="https://github.com/user-attachments/assets/afaaac98-d909-4d88-8365-154d61510a91">

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by 0xtimsb** [comment]
I'm able to reproduce this. Looking into this.

**Comment by 0xtimsb** [comment]
Thanks, @rendaoer. I caused this in [#21524](https://github.com/zed-industries/zed/pull/21524) and made a fix.
