### ISSUE TITLE
`workspace::SendKeystrokes` no longer able to send commands to terminal

### ISSUE THREAD

**Issue by Jeff-SearchPilot** [zed-industries/zed#21584]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have this workspace keybinding, which has been working for months..

```
    "bindings": {
      "alt-g": [
        "workspace::SendKeystrokes",
        "ctrl-shift-p new center terminal enter lazygit; exit enter"
      ],
```
As you can see, I can press `alt-g` and it will fire up a full height terminal with lazygit running. When I updated to "Zed Preview 0.165.1" today this has stopped working. Now when triggering the keybinding a terminal pane opens but the `lazygit;exit` command is inserted into the file I was editing, rather than the terminal.

This was working on the previous release

### Environment

Zed: v0.165.1 (Zed Preview)
OS: Linux Wayland fedora 41
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.7

**Comment by notpeter** [comment]
In general SendKeystrokes doesn't work as you might expect with async steps.  E.g. spawning a new center terminal would needs to wait for the terminal to spawn and the focus to change and SendKeystrokes can't do that.

I recommend you use a task for this:
tasks.json:
```json
[
  {
    "label": "lazygit",
    "command": "lazygit",
    "hide": "on_success"
  },
]
```

keymap.json:
```
[
  {
    "context": "Workspace",
    "bindings": {
      "alt-g": ["task::Spawn", { "task_name": "lazygit" }]
    }
  }
]
```

**Comment by notpeter** [comment]
At the moment, I don't think there is. There has been some discussion here:
- #17710 

As a workaround you could spawn an external terminal (like alacritty) with lazy git like so:
```
  {
    "label": "lazygit",
    "command": "alacritty -o 'window.startup_mode=\"SimpleFullscreen\"' --working-directory ${ZED_WORKTREE_ROOT} --command lazygit",
    "hide": "always"
  },
```
But it'd be nice to support something similar entirely within Zed.

**Comment by baldwindavid** [comment]
I had just reported this regression in #21610 and then found this closed issue. This is a definite bummer as I've relied upon it for the last year for both lazygit and to approximate netrw-style file navigation. I'm all for the task route, but tasks cannot target the center terminal as requested in #9445
