### ISSUE TITLE
Render __ and ^^ wrapped text as sub/superscript in Markdown Preview

### ISSUE THREAD

**Issue by caiigee** [zed-industries/zed#21591]
### Check for existing issues

- [X] Completed

### Describe the feature

To the best of my knowledge, there is currently no way to write sub/superscript text in Markdown for it to be rendered in the preview. This a feature that other Markdown editors provide (e.g. Joplin). The syntax for sub/superscript text is super important for scientific note taking as that kind of subject involves a lot of sub/superscript text.

Right now, I resort to using [Compose sequences](https://cgit.freedesktop.org/xorg/lib/libX11/plain/nls/en_US.UTF-8/Compose.pre), which is very much not ideal.

I suggest to use the underscore `_` and circumflex `^` as the "escape" characters for sub/superscript, respectively. I understand that underscore wrapped text currently renders to *italic* but I find that weird as asterisk `*` wrapped text also renders to *italic*. There is clearly potential here for better syntax rules.

On a sidenote, I find it very strange that Zed's markdown preview does not render HTML. For example, I tried writing "Ca\<sup>2+\</sup>" and the preview rendered only "Ca". Every other Markdown editor I used previously could render HTML elements.

### Environment

Zed: v0.163.2 (Zed)
OS: Linux Wayland nixos 25.05
Memory: 14.9 GiB
Architecture: x86_64
GPU: AMD Radeon 680M (RADV REMBRANDT) || radv || Mesa 24.2.6

### If applicable, add mockups / screenshots to help present your vision of the feature

H_2_O → H₂O
K^+^ → K⁺

**Comment by notpeter** [comment]
>  I find it very strange that Zed's markdown preview does not render HTML. 

Zed does not ship an embedded web view and so our Markdown Preview is a (limited) gpui-native Markdown renderer not a Markdown->HTML compiler + webview as is more common in apps that include a web browser.

> I suggest to use the underscore _ and circumflex ^ as the "escape" characters for sub/superscript, respectively.

We are unlikely to implement non-standard characters like `_` as a subscript and `^`.
Our current target is compatibility is [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

If we ship an HTML webview for Markdown that may support HTML `<sup>` / `<sub>` but in the meantime we still have a ways to go implementing core Markdown features. See:

- https://github.com/zed-industries/zed/issues/5346
- #21208 

I understand that's not the answer you're looking for, but I'd rather close as not planned than leave an issue open that we have no intention of (directly) working on in the near future. Thanks for filing.
