### ISSUE TITLE
Wierd themes colors issue

### ISSUE THREAD

**Issue by lassejlv** [zed-industries/zed#21604]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Install a theme with the latest version. And see that the color on the file tree stops with the last file. I downgraded to 0.163 and there was no issues. And i tried with multiple themes. View image
<img width="626" alt="Screenshot 2024-12-05 at 20 08 24" src="https://github.com/user-attachments/assets/2c805917-beb1-4cdf-8332-58ad590096f3">

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by jbanety** [comment]
Same here with the theme `Call trans opt: received. 2-19-98 13:24:18 REC:Log>`. 
Nice colors for xmas 😁 
<img width="231" alt="Capture d’écran 2024-12-05 à 20 59 24" src="https://github.com/user-attachments/assets/e2e334b5-d5e1-4476-9c3a-a27d2d2631c3">

**Comment by lassejlv** [comment]
What the eare you using @jbanety ?

**Comment by danilo-leal** [comment]
Hey! This has been fixed in: https://github.com/zed-industries/zed/pull/21559. It will be out next week! For the time being, try running Zed locally to double check whether it's really fixed. I'll close the issue for now.

**Comment by jbanety** [comment]
> What the eare you using @jbanety ?

What do you mean by eare ?

**Comment by lassejlv** [comment]
@danilo-leal its fixed with the local version 👍
