### ISSUE TITLE
regression: preview release: keybindings - "typed" text no longer entered in new center terminal via SendKeystrokes

### ISSUE THREAD

**Issue by baldwindavid** [zed-industries/zed#21610]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In #9445 I've requested spawning a task in a center terminal in order to open a TUI file explorer (yazi) within the current pane. As a workaround for nearly a year now I've approximated this sort of thing with a keybinding that leverages `SendKeystrokes` to copy the current path, open a new center terminal, and then open yazi at that current path.

```json
"-": [
  "workspace::SendKeystrokes",
  ": c r p enter cmd-w : new center terminal enter ya_zed space cmd-v enter"
],
```

However, as of the latest Preview release this no longer works (still works in the Stable release). Instead, the current path is pasted into the current file and a new center terminal is opened with no text placed in it. I suspect that something in #21238 might have impacted this behavior only because it makes a good bit of changes to the terminal, but perhaps it's something else.

Maybe I was relying on behavior I ought not to have been, but it was a workaround that got things most of the way there.

For more background, here is a video of the behavior I've had up until now in this comment... https://github.com/zed-industries/zed/discussions/9067#discussioncomment-8987171

### Environment

Zed: v0.165.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by baldwindavid** [comment]
Adding an example that is even simpler:

This keybinding _previously_ opened `lazygit` in a center terminal...

```json
"cmd-g": [
  "workspace::SendKeystrokes",
  ": new center terminal enter lazygit enter"
],
```

Now in Preview it opens a new center terminal but the text and enter are ignored so it's basically as if I had only done...

```json
"cmd-g": "workspace::NewCenterTerminal"
```

**Comment by baldwindavid** [comment]
Just found that this was reported in #21584 and won't be fixed so closing.

**Comment by mikayla-maki** [comment]
While this issue probably won't be fixed, I have implemented the underlying request for spawning a task in the center terminal! https://github.com/zed-industries/zed/pull/22004

**Comment by baldwindavid** [comment]
@mikayla-maki Yep, I am excite. I was only using `SendKeystrokes` as a hacky workaround anyway and targeting the center is a much cleaner and less problematic all around. Thanks!
