### ISSUE TITLE
Allow Rust name refactors to affect intra-doc links

### ISSUE THREAD

**Issue by ActuallyHappening** [zed-industries/zed#21620]
### Check for existing issues

- [X] Completed

### Describe the feature

When renaming a struct, enum, function or item, the relevant intra-doc links are also updated to the new name. See here for the specification: https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html#valid-links

I believe VSCode supported this feature. I'm not sure this functionality is exposed by rust-analyzer, but I've never had much to do with rust-analyzer directly before

### Environment

Zed: v0.165.0 (Zed Dev 94faf9dd56c494d369513e885fe1e08a95256bd3)
OS: Linux X11 pop 22.04
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7800 XT (RADV NAVI32) || radv || Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319

### If applicable, add mockups / screenshots to help present your vision of the feature

IntelliJ has this feature as well? https://github.com/intellij-rust/intellij-rust/issues/6905

**Comment by SomeoneToIgnore** [comment]
> I believe

It's quite simple to check, so it would be great to exclude questions of faith out of the issues.
Specifically this, does not seem to work at all in VSCode + latest, Nightly, r-a:

https://github.com/user-attachments/assets/aac29720-2528-430a-9168-2fbb26561d25

> I'm not sure this functionality is exposed by rust-analyzer

I see nothing in https://rust-analyzer.github.io/manual.html#rename and around, so seems like not.
Zed cannot be better at such things if r-a is not providing any means for this, and IntelliJ is not really relevant as they are introspecting code inside their product, opposed to Zed and VSCode who know nothing about languages.

**Comment by ActuallyHappening** [comment]
Hmm, OK, I wonder how much effort this would take to implement
Thanks anyway

**Comment by SomeoneToIgnore** [comment]
When it's ready in r-a, then it will be picked up automatically, but not sure how much efforts it takes there.
