### ISSUE TITLE
Not start zed

### ISSUE THREAD

**Issue by Ruhaan838** [zed-industries/zed#21638]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Could not create directory "/Users/user_name/.config/zed": Permission denied (os error 13)

### Environment

Chip: Apple M2
Memory : 8GB
macOS Sonoma 14.5

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

I don't find the file but i got this error 
![image](https://github.com/user-attachments/assets/0956a522-ce05-426d-8c13-b6077061bfc7)

**Comment by SomeoneToIgnore** [comment]
> Check for existing issues

https://github.com/zed-industries/zed/issues?q=is%3Aissue+Permission+denied+%28os+error+13%29+

For instance, this has an answer: https://github.com/zed-industries/zed/issues/20162#issuecomment-2455039731
