### ISSUE TITLE
The repository remains highlighted as a Git repository after removing the .git folder

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21642]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After initializing a Git repository using the `git init` command and then removing the `.git` folder with the `rm -rf .git` command, the repository continues to appear as a Git repository, with the folder remaining "highlighted" or marked as such.

This behavior occurs despite the removal of the .git folder, which should remove all traces of Git from the project. The project folder no longer appears to be a Git repository, but Zed continues to treat it as if it were.

I have to change projects and then reopen them to make the highlighted one disappear.

https://github.com/user-attachments/assets/6011e2b8-40b2-4af1-a6f1-e90c8b0232c7

### Environment

```
Zed: v0.165.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
There are significant changes in progress with respect to our git functionality.
We are not currently prioritizing the seamless handling of removing a .git folder while running zed.

As a workaround I recommend you cmd-shift-p `zed: reload workspace` after removing your git folder.
