### ISSUE TITLE
[MacOS] TAB circulation across different selection buttons (Cancel/OK/Save, etc.)

### ISSUE THREAD

**Issue by bryan-pop** [zed-industries/zed#21658]
### Check for existing issues

- [X] Completed

### Describe the feature

Two issues related to this were closed for Linux, but it would be awesome to get this feature enabled on MacOS

<img width="266" alt="Screenshot 2024-12-06 at 11 30 20 AM" src="https://github.com/user-attachments/assets/ec3e3bf3-072e-4c9f-a85e-b27a618088f8">

I'd like to tab to select _Don't Save_ or choose a hotkey (ie. `d`, or `n`, etc) then use the space bar (or enter) to click don't save. Currently, I can only access this with the mouse.

https://github.com/zed-industries/zed/issues/13906
https://github.com/zed-industries/zed/issues/13916

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="266" alt="Screenshot 2024-12-06 at 11 30 20 AM" src="https://github.com/user-attachments/assets/a0b6a632-6e49-49f4-900c-038c729d7b3e">

It could be an underscore underneath the `n` for "no hotkey"

Or it could just allow toggling via tab.

Space bar (or enter) would select.

**Comment by notpeter** [comment]
MacOS supports tab circulation, you just have to enable it in your System Preferences->Keyboard->Keyboard Navigation
<img width="708" alt="Screenshot 2024-12-06 at 15 13 48" src="https://github.com/user-attachments/assets/c6360337-7580-4936-bca8-891c4c4dd282">

Then you can use tab to cycle between them.  For example:
<img width="269" alt="Screenshot 2024-12-06 at 15 12 29" src="https://github.com/user-attachments/assets/ca1b93f1-a1f5-4441-8779-71a722d7caf9">
Enter will "save"
Space will "don't save"
and Escape will "Cancel"

Letter-based navigation is not supported in macos native controls.
Sorry

**Comment by VKondakoff** [comment]
`Full keyboard access` is definitely an accessibility feature (not the regular keyboard navigation feature). Enabling it disables many of the _normal_ `Tab` hotkeys (for example `Ctrl-Tab` to switch between Zed tabs). 

So, I strongly suggest to consider some kind of keyboard navigation on Zed modals without enabling the `Full keyboard access`.

**Comment by VKondakoff** [comment]
> I am suggesting "Keyboard->Keyboard Navigation" not "Accessibility->Full Keyboard Access"

Ah, thank you. Yes, you are right. Silly me!
`Keyboard navigation` works well.
