### ISSUE TITLE
Add more image viewing tools

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21683]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/user-attachments/assets/a1c1c1c3-3b7f-42a0-bcad-790c879ae48d

### Environment

```
Zed: v0.165.3 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
This is a great screenshot recording, but it doesn't bother to enumerate an actual request. Closing as unscoped/unactionable.

See also:
- #9584 
- https://github.com/zed-industries/zed/issues/21281

**Comment by notpeter** [comment]
> I would like to understand what I should dwell on in the explanation.

Because our issues should be optimized for reading. Just as paragraphs of text can be be a distraction, relying on a video is almost failing to explicitly define what an issue is about. You are relying on an implicit assumption that your reader has the same context as you which is a bad assumption.
