### ISSUE TITLE
“Copy Path” Copies Paths to Multiple Elements in Project Tree

### ISSUE THREAD

**Issue by taras-mrtn** [zed-industries/zed#21690]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the “Copy Path” feature in the project tree, if one element (file or directory) is selected and then a right-click is performed on a different element, selecting Copy Path copies the paths to both:
	•	The previously selected element.
	•	The element where the right-click was performed.

This behavior is incorrect. Only the path to the element where the right-click was performed should be copied.

**Steps to Reproduce**
	1.	Open a project in Zed.
	2.	Select any file or directory in the project tree.
	3.	Right-click on a different file or directory.
	4.	Select the Copy Path option from the context menu.

**Expected Behavior**

Only the path to the element where the right-click was performed should be copied.

**Actual Behavior**

Paths to both the previously selected element and the element where the right-click was performed are copied.

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by MrSubidubi** [comment]
I believe #21707 fixed this issue.
