### ISSUE TITLE
Please tag this repo as rust-lang to help discovery

### ISSUE THREAD

**Issue by dandv** [zed-industries/zed#21694]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/topics/rust-lang doesn't show Zed.

### Environment

[GitHub](https://github.com/zed-industries/zed/)

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/fb3a1be2-d90e-4815-96f5-17e2d17cde93)

**Comment by JosephTLyons** [comment]
Good idea @dandv! Done!

<img width="297" alt="SCR-20241212-mjkb" src="https://github.com/user-attachments/assets/d452731c-7a0b-4f2e-8c12-580d809da36d" />
