### ISSUE TITLE
`editor: open url` command should only open the selected portion of a url

### ISSUE THREAD

**Issue by xdBronch** [zed-industries/zed#21718]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/631f7b49-0e94-4700-b899-c66546008327)
this for example should only open `https://google.com` but it currently uses the entire URL. vim and nvim both handle this as i would expect

### Environment

Zed: v0.166.0 (Zed Dev a30ea2fc682bdaec572f3e130631e297670612a6)
OS: Linux Wayland alpine 3.21.0
Memory: 15.6 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6950 XT (RADV NAVI21) || radv || Mesa 24.2.8

**Comment by JosephTLyons** [comment]
It seems like this would be a setting.

Vim and Nvim open the url in the selection, VS Code opens the entire URL, regardless of selection.
