### ISSUE TITLE
fresh zed install can't run json lang server

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#21710]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

fresh reinstall of zed is unable to provide intellisense for settings.json
<img width="1136" alt="Skärmavbild 2024-12-08 kl  19 51 48" src="https://github.com/user-attachments/assets/6e479d39-0628-4a43-accf-cc9c8547b418">

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by osiewicz** [comment]
GETing `https://registry.npmjs.org/vscode-langservers-extracted` works for me; can you try to install this language server again? Perhaps there was an outage?

**Comment by nervenes** [comment]
it works now, yeah. don't know what the issue was, i can't reproduce it again.

**Comment by osiewicz** [comment]
Sweet; I'll go ahead and close this issue. Feel free to reopen if it arises again. Thanks for reporting it though!
