### ISSUE TITLE
Rust LSP not working in packages excluded from a workspace

### ISSUE THREAD

**Issue by najibkr** [zed-industries/zed#21735]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I exclude a package from a Rust workspace, the rust LSP fails to highlight syntax, or indicate errors within the independent package residing in the rust workspace directory.

### Environment

Not Applicable

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
This is how https://github.com/rust-lang/rust-analyzer/ works and Zed cannot make it better, so this issue is not really actionable here.
