### ISSUE TITLE
Extensions fail to start without internet connection.

### ISSUE THREAD

**Issue by somewhatfrog** [zed-industries/zed#21741]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When there is no internet connection, on startup the check for extensions updates fails and doesn't allow to load extensions at all. Please add the option to disable automatic check for extensions updates and allow the app to load those regardless if it can or cannot check for the updates.

Thank you. 

ps. I have big hopes for this project so I can completely ditch vscodium and its bloat, in fact this is the second app on my system where I keep the telemetry enabled. Love what you're doing here, keep it up!

### Environment

irrelevant

### If applicable, add mockups / screenshots to help explain present your vision of the feature

irrelevant

### If applicable, attach your Zed.log file to this issue.

irrelevant

**Comment by uncenter** [comment]
Related (duplicate?) of #12163.

**Comment by somewhatfrog** [comment]
My bad, duplicate, closing!
