### ISSUE TITLE
Project diagnostics: do not show when there is no open project or file

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21791]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="428" alt="Screenshot 2024-12-10 alle 10 54 53" src="https://github.com/user-attachments/assets/ac1c8e1e-3769-4512-8b17-6f4ee305db3d">

### Environment

```
Zed: v0.165.3 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
I cannot reproduce.
When I open an empty project and click the Diagnostics button it spawns an empty panel as expected.
<img width="679" alt="Screenshot 2024-12-16 at 0 58 48" src="https://github.com/user-attachments/assets/5c179cca-d499-4de5-b96a-77c64d17fc25" />
