### ISSUE TITLE
When calling the context menu on a file in the file tree, the file that had focus is not deselected.

### ISSUE THREAD

**Issue by thecoooler** [zed-industries/zed#21797]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The focus is set on some file. When right-clicking on another file (which has no focus, it is not selected) to call the context menu and clicking on any action - this action is performed for the file in focus and the one for which I called the context menu. This behavior is not obvious and I have not had this happen in other editors.

In the screenshot below, I had the TVResponse.php file selected. Then I right-clicked on the Dates.php file and clicked delete. As you can see in the screenshot, the editor assumes that I want to delete both files.

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/26cb77ab-efa8-4705-86c3-b91069a9bf61">

### Environment

"app_version": "0.165.4",
"release_channel": "Zed Preview",
"os_name": "macOS",
"os_version": "14.6.1",
"architecture": "x86_64",

**Comment by MrSubidubi** [comment]
This was fixed by #21707 recently and should land in Preview later today 😄
