### ISSUE TITLE
Code play button, strange behavior when changing font size buffer

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21806]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I change the buffer font size, the play button, seems to behave strangely, it becomes too small.

https://github.com/user-attachments/assets/05cb8073-67ab-4d16-91a4-935d13361267

![image](https://github.com/user-attachments/assets/21c33d52-31a5-40ec-8ec3-b6bf773e30b2)
![image](https://github.com/user-attachments/assets/e5689e13-b29a-4b76-a9b9-87ae58d87260)

### Environment

```
Zed: v0.165.4 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
> When I change the buffer font size, the play button, seems to behave strangely, it becomes too small.

I feel like a broken record, but a video and a sentence is not sufficient for conveying what you are trying to express.

I don't see an issue here.
Default `buffer_font_size` is 15.
The icon is smaller when you when you have it set to 12.
