### ISSUE TITLE
Add a claude artifacts like features to Zed AI

### ISSUE THREAD

**Issue by ashish01** [zed-industries/zed#21840]
### Check for existing issues

- [X] Completed

### Describe the feature

Implementing a feature in Zed editor similar to "artifacts" in Anthropic's Claude. 

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

**Comment by mrnugget** [comment]
Hey! That's an interesting idea, but that's pretty far down on the roadmap right now.
