### ISSUE TITLE
UI Issue for long project names on Mac

### ISSUE THREAD

**Issue by narendasan** [zed-industries/zed#21877]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Have a long project name

### Environment

Zed: v0.166.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="358" alt="image" src="https://github.com/user-attachments/assets/2e0b4f42-1978-4047-9f9d-c102b434a06e" />

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by danilo-leal** [comment]
@mrnugget look what we have here again 😅

**Comment by danilo-leal** [comment]
<img width="800" alt="Screenshot 2024-12-13 at 00 58 22" src="https://github.com/user-attachments/assets/4751e543-25b7-40cb-b08f-2313e09d1633" />

For context, while we were developing the Remote Development project, this label behavior was intermittent. We didn't fully understand—nor looked incredibly deep into it back then—why this happens. For example, even when trying to force a long-label scenario, I can't reproduce it ☝️. But it sounds like it's there and should be worth digging in more.

**Comment by notpeter** [comment]
Easy steps to reproduce:
Create a hostname alias in your `~/.ssh/config`:

```ssh_config
Host face-something-hiro-lab-2
  HostName localhost
```

```sh
zed ssh://face-something-hiro-lab-2/~/code/zed
```

<img width="336" alt="Screenshot 2024-12-15 at 21 23 20" src="https://github.com/user-attachments/assets/54a1d9c9-2d73-4686-ba9b-7e9f931b8a0c" />

**Comment by mrnugget** [comment]
Yeah, I wonder whether we should be more aggressive with the truncation or think of another way to display this. @notpeter the problem goes away when you add one more character to the name, right?

**Comment by notpeter** [comment]
> @notpeter the problem goes away when you add one more character to the name, right?

No. With `face-something-hiro-lab-22` instead of `face-something-hiro-lab-2` still broken:
<img width="330" alt="Screenshot 2024-12-17 at 13 13 25" src="https://github.com/user-attachments/assets/e86dbce7-3e7b-4f1e-8b7b-e3368f42db22" />
