### ISSUE TITLE
Cursor names are cut off in Vim normal mode during collaboration

### ISSUE THREAD

**Issue by AaronFeickert** [zed-industries/zed#21887]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When collaborating with a user editing in Vim normal mode (where a block cursor symbol is used), the user's name pops up from time to time for identification purposes. When this happens, the first letter of the name is partially cut off due to overlap with the character under the cursor.

This does not happen in insert mode, or when Vim modes are disabled.

### Environment

Zed: v0.165.4 (Zed)
OS: macOS 15.1.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by AaronFeickert** [comment]
I'm new to the codebase, but I wonder if the issue is with the cursor [layout](https://github.com/zed-industries/zed/blob/fff12ec1e5278e1825d912241f62179387ac8176/crates/editor/src/element.rs#L6372-L6400) implementation.

**Comment by AaronFeickert** [comment]
This isn't specific to Vim.

When the cursor is at the top line, the name popup is positioned at the [right side](https://github.com/zed-industries/zed/blob/fff12ec1e5278e1825d912241f62179387ac8176/crates/editor/src/element.rs#L6383) of the cursor. But when it is on any other line, it is positioned at the [left side](https://github.com/zed-industries/zed/blob/fff12ec1e5278e1825d912241f62179387ac8176/crates/editor/src/element.rs#L6385) of the cursor. In practice, this only affects block-shaped cursors, which is why it is particularly noticeable in Vim normal mode.

Here's an example of the overlap in action:
<img width="171" alt="Screenshot 2024-12-13 at 18 00 54" src="https://github.com/user-attachments/assets/e93f736d-8bcb-4572-b0eb-1091f5c3e93a" />

**Comment by ConradIrwin** [comment]
I think we could fix this by rendering the cursor's background before the name, but I haven't looked at the details.

**Comment by AaronFeickert** [comment]
@ConradIrwin: is there any reason why the linked PR doesn't suffice?

**Comment by ConradIrwin** [comment]
Sorry I missed that!
