### ISSUE TITLE
Rust: Typing | inserts ||

### ISSUE THREAD

**Issue by road2react** [zed-industries/zed#21913]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Typing `|` inserts `||` inside a function in a Rust file

### Environment

Zed: v0.165.4 (Zed)
OS: Linux Wayland arch unknown
Memory: 93.5 GiB
Architecture: x86_64
GPU: AMD Radeon 680M (RADV REMBRANDT) || radv || Mesa 24.3.1-arch1.3

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/2f886b13-4c3a-401f-8906-55814ddf6631)

I pressed `|` once, but `||` showed up instead. Cursor is not in between, so doesn't look like closure bracket autoclose.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by JosephTLyons** [comment]
The team pointed out that this is an upstream rust-analyzer issue:

- https://github.com/rust-lang/rust-analyzer/pull/18647
