### ISSUE TITLE
Add Shared Terminal Feature

### ISSUE THREAD

**Issue by Baokker** [zed-industries/zed#21915]
### Check for existing issues

- [X] Completed

### Describe the feature

Can we add shared terminals like live share and code with me's share terminal functions?
We can also try to enhance the security of shared terminal. They all can use read/write permission, which is dangerous.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/4767
