### ISSUE TITLE
Terminal process opening strange behavior

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21957]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On `Zed` I noticed that when a terminal is opened (even if it does nothing it remains waiting), in turn a waiting process is opened we can say, but this process is assigned the name of `login` and as user `root`.

Instead on `VScode` same thing as above, but the name that is assigned to the process is the name of `zsh` and as user `my username`.

I ran the command on both:
`ps -p $$ 
`

Zed:
<img width="230" alt="Screenshot 2024-12-13 alle 11 40 58" src="https://github.com/user-attachments/assets/204379ba-39e0-4384-be6a-1fb18d52bf22" />

<img width="216" alt="Screenshot 2024-12-13 alle 11 16 26" src="https://github.com/user-attachments/assets/1421ccae-9c59-4c52-89ff-1cb55fd80ff7" />
<img width="949" alt="Screenshot 2024-12-13 alle 11 17 29" src="https://github.com/user-attachments/assets/5afb9aef-dd86-41be-bbf8-92fca5e42dd7" />

Vscode:
<img width="302" alt="Screenshot 2024-12-13 alle 11 40 27" src="https://github.com/user-attachments/assets/a8e70764-23a2-4d63-9aed-bf6d1c1daa9f" />

<img width="383" alt="Screenshot 2024-12-13 alle 11 12 29" src="https://github.com/user-attachments/assets/f9b43541-ea55-4017-9323-20511a55275d" />
<img width="843" alt="Screenshot 2024-12-13 alle 11 13 23" src="https://github.com/user-attachments/assets/f19cc5f3-f375-4da1-bf63-430cf2c3dcc7" />

Edit:

I don't understand what's happening, why two processes are created.
Every time I open a terminal on `Zed`.
One `login` and one `zsh`.

<img width="790" alt="Screenshot 2024-12-13 alle 19 59 43" src="https://github.com/user-attachments/assets/7b8cdd66-5eff-4ae8-b8d3-c06536f7320e" />
<img width="417" alt="Screenshot 2024-12-13 alle 19 58 43" src="https://github.com/user-attachments/assets/2ac5bbd1-aca6-4b21-94f4-3309e901242d" />

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by ankddev** [comment]
Maybe, it is related to [this](https://zed.dev/docs/environment#launched-via-window-manager-dock-or-launcher).
> In order to still have a useful environment, Zed spawns a login shell in the user's home directory and gets its environment. This environment is then set on the Zed process. That means all Zed windows and projects will inherit that home directory environment.

**Comment by notpeter** [comment]
> On Zed I noticed that when a terminal is opened (even if it does nothing it remains waiting), in turn a waiting process is opened we can say, but this process is assigned the name of login and as user root.

> Instead on VScode same thing as above, but the name that is assigned to the process is the name of zsh and as user my username.

These are no sentences.
