### ISSUE TITLE
Project Search options buttons

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21959]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/user-attachments/assets/16a71a1e-ef48-4947-97c3-bdb02114f23d

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Without a description this is insufficiently described and a waste of time.
Do not open issue which only contain a video and contain no description.
