### ISSUE TITLE
Side panel search symbols strange resizing

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21963]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/user-attachments/assets/e090dd89-563f-4f0e-b67c-40c61325ea9f

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
I'm happy to review PRs which improve how we handle resizing the Outline panel.
But we don't plan to implement a fix at this time.
Thanks for reporting.
