### ISSUE TITLE
Symbols search modal No matches

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21964]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As you can see from the image in the Symbols search modal, in the input field there is no text entered, but it already says `No matches`, wouldn't it be more correct not to make it appear and make it appear only when a text is entered that is not found?

<img width="573" alt="Screenshot 2024-12-13 alle 12 33 58" src="https://github.com/user-attachments/assets/0b686762-df47-4b95-b3a4-f8e7af54cd8e" />

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
Thank you for the suggestions. We don't plan to implement these changes at this time.
