### ISSUE TITLE
missing direnv errors from log

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#21972]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've got a message saying direnv failed that I can press to see Zed.log, but in the log there isn't any mention of direnv.
<img width="260" alt="Screenshot 2024-12-13 at 15 24 42" src="https://github.com/user-attachments/assets/fe963a6b-f592-4ec6-9d34-696b83273861" />

### Environment

Zed: v0.165.4 (Zed)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by mrnugget** [comment]
Yeah, I've run into this too, been meaning to look into it. I think it has something to with the settings.json file being open, or at least that's a way to reproduce it. cc @WeetHet

**Comment by WeetHet** [comment]
> Yeah, I've run into this too, been meaning to look into it. I think it has something to with the settings.json file being open, or at least that's a way to reproduce it. cc @WeetHet

Yeah, I've ran into that as well. I don't have a reproduction though, so I can't really do anything about it until one is found

**Comment by hferreiro** [comment]
It happens to me everytime in a particular project. Let me know if I can help debug the issue.

**Comment by WeetHet** [comment]
> It happens to me everytime in a particular project. Let me know if I can help debug the issue.

Could you share the logs?

**Comment by hferreiro** [comment]
[Zed.log](https://github.com/user-attachments/files/18195960/Zed.log)

**Comment by WeetHet** [comment]
> [Zed.log](https://github.com/user-attachments/files/18195960/Zed.log)

The message you are seeing could only be returned from here:

https://github.com/zed-industries/zed/blob/d54662e683a45617fb66d32d4391729320b9aba3/crates/project/src/direnv.rs#L20-L24

If it was `DirenvError::NonZeroExit`, then the log would contain something about `direnv`, as per:
https://github.com/zed-industries/zed/blob/d54662e683a45617fb66d32d4391729320b9aba3/crates/project/src/direnv.rs#L54-L64

As there is no mention of direnv in the logs, this leads me to believe that we are seeing the `FailedRun` variant of the enum. This means this line should be triggered:
https://github.com/zed-industries/zed/blob/d54662e683a45617fb66d32d4391729320b9aba3/crates/project/src/direnv.rs#L49

So we need to look for errors in the logs and the only one matching is 
```
2024-12-19T10:54:04.216954+01:00 [ERROR] Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Which is super weird, we check for direnv above:
https://github.com/zed-industries/zed/blob/d54662e683a45617fb66d32d4391729320b9aba3/crates/project/src/direnv.rs#L38-L40

So, the `dir` doesn't exist? I don't understand what is going on honestly

@mrnugget any ideas?

**Comment by mrnugget** [comment]
Yeah, I think I know what this is. It always happens with single-file worktrees. Looking into it. Should have fix soon.

**Comment by mrnugget** [comment]
Fix is in https://github.com/zed-industries/zed/pull/22246 — at least very likely so.
