### ISSUE TITLE
Copy full SHA show toast message that was successful

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#22024]
### Check for existing issues

- [X] Completed

### Describe the feature

Showing a message via toast that the copy of the full SHA was successful would be great.

https://github.com/user-attachments/assets/53c1f152-1893-4980-8e2e-ce0ad6d4cbf3

Showing a tooltip as well, explaining what it does, would be nice.

<img width="273" alt="Screenshot 2024-12-14 alle 22 58 23" src="https://github.com/user-attachments/assets/5b53146a-75c2-45eb-9d0a-92ed3dc51129" />

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
I tried to implement the tooltip, but we don't currently support nested hover states (displaying a hover tooltip inside a hover window). Similarly we have not yet built the GPUI components required to do an inline auto-dismissing toast as suggested.

Thank you for the suggestions. We don't plan to implement these changes at this time.

**Comment by notpeter** [comment]
@Angelk90 If this issue implicitly requires implementing unscoped gpui functionality it is not a well scoped issue.  

"Add a tooltip" / "Add toast messaging confirming something happened" are not bugs or enhancement requests -- once the pre-requisite work is done it no longer justifies a dedicated issue as it's just UI/Design polish. Worth doing? Sure. Worth tracking in an issue? My judgment says no.
