### ISSUE TITLE
Git blame tooltip be able to select and copy text

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#22025]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/user-attachments/assets/c093fea5-16b2-4745-8962-2e47db4759e2)

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
Duplicate of:
- https://github.com/zed-industries/zed/issues/16292
