### ISSUE TITLE
Toolchain: detect `$VIRTUAL_ENV`

### ISSUE THREAD

**Issue by pantheraleo-7** [zed-industries/zed#22021]
### Check for existing issues

- [X] Completed

### Describe the feature

It is not very convenient to put a venv on `$PATH`. Zed should read `$VIRTUAL_ENV` and show the venv in the toolchain. VS Code does this (when a folder is open).

The use case is that in non-package (library) centric fields, mostly a "global" venv is used rather than per-project basis.

### Environment

Zed: v0.166.1 (Zed Preview)
OS: macOS 15.2.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

`export VIRTUAL_ENV="$HOME/.local/share/ds"`
VS Code:
<img width="742" alt="image" src="https://github.com/user-attachments/assets/9d79a3d8-9843-4590-ae0f-148fc5cbf62f" />

**Comment by pantheraleo-7** [comment]
\cc @osiewicz

**Comment by pantheraleo-7** [comment]
Seems like VS Code had this venv cached or something from the last time I put it on `$PATH`. VS Code and Zed both use PET for detection therefore both should be same, as I initially thought, and this is indeed the case.

So this should be added upstream as this is very common and needed (detecting `$VIRTUAL_ENV` that is).

(in the meantime Zed could add this)

**Comment by notpeter** [comment]
Here's the issue @pantheraleo-7 opened an issue upstream:
- https://github.com/microsoft/python-environment-tools/issues/180

Thanks for reporting.
