### ISSUE TITLE
Support limited subset of HTML elements in markdown preview

### ISSUE THREAD

**Issue by uncenter** [zed-industries/zed#22033]
### Check for existing issues

- [X] Completed

### Describe the feature

Prior issues:
- https://github.com/zed-industries/zed/issues/14830
- https://github.com/zed-industries/zed/issues/21992

Would love to see the markdown preview have the ability to render some basic HTML elements commonly used, such as `<img>`s and `<kbd>` (see above two issues).

### Environment

N/A

**Comment by notpeter** [comment]
Closing as duplicate of the linked issues.

See also:
- https://github.com/zed-industries/zed/issues/5346
