### ISSUE TITLE
bug: button `Delete` is deleting more than requested

### ISSUE THREAD

**Issue by BlackAsLight** [zed-industries/zed#22127]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the sidebar, when you click on a file to view it, it has it selected, if you now go and right click on another file and select Delete in the drop down menu, it lists both of those files (the file you're viewing and the file you want to delete) for deletion instead of only the file I right clicked on for deletion. This has lead me to delete newly written and uncommitted code several times now.

### Environment

Zed: 0.165.4
OS: MacOS 15.1.1
RAM: 16GB

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![Screenshot 2024-12-17 at 13 38 05](https://github.com/user-attachments/assets/6c06afa4-362b-448a-af22-913f46c540e8)
![Screenshot 2024-12-17 at 13 38 08](https://github.com/user-attachments/assets/781e1501-8402-4c63-b5a5-44967498324d)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by 5brian** [comment]
See: 
- https://github.com/zed-industries/zed/issues/22038#issuecomment-2544488793
