### ISSUE TITLE
Scrollbar behaviour not working as intended

### ISSUE THREAD

**Issue by conrad-mo** [zed-industries/zed#22172]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed editor doesn't show horizontal scrollbar when there is character overflow horizontally (shown in the panel on the left) as well as it shows scrollbar vertically, even when LOC is small enough where the entire file can be shown (panel on the right)

### Zed Version and System Specs

Zed: v0.165.4 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![image](https://github.com/user-attachments/assets/1c979057-27c4-400e-a8e8-3bcb192662c2)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by osiewicz** [comment]
We've never had horizontal scrollbar up until https://github.com/zed-industries/zed/pull/19495, which landed just today.
As for your complaint on vertical scrollbar, this can be disabled with the setting:
```
"scroll_beyond_last_line": "off"
```

Feel free to reopen if you feel like this should not have been closed.
