### ISSUE TITLE
terminal doesnt show last line on full screen, and zed's status bar disappear.

### ISSUE THREAD

**Issue by vovacooper** [zed-industries/zed#22227]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when making the terminal full screen the Zed's status bar (at the bottom) dissapears and the last line of the terminal also.

this is not full screen 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/027d7daa-54fa-4db5-b17d-f4516b1bc05f" />

this is full screen terminal

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/64248372-f1a8-4cfc-9099-77afb3ae8fe0" />

### Zed Version and System Specs

Zed 0.163.3
67d405ddf745641edff369ac2110f3f8864d6f8d

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/12966
