### ISSUE TITLE
"Show in folder" from third party app opens zed instead of native file explorer

### ISSUE THREAD

**Issue by aryzing** [zed-industries/zed#22221]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the "Show in folder" of a third party app, the native file explorer used to open as expected. Somewhat recently, Zed hijacked the default option somehow and now "Show in folder" opens Zed, which doesn't make sense

### Zed Version and System Specs

Zed: v0.163.2 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 30.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV GFX1103_R1) || radv || Mesa 24.0.9-0ubuntu0.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by jansol** [comment]
Sounds like you have some remnants of a rather old build left somewhere on your system. Namely a `.desktop` file that advertises support for opening folders. That was removed in #16940 for this exact reason. The desktop file should have been overridden by the automatic update mechanism, but if you switched to a different packaging mechanism before that change you may still have an old file lying around somewhere in `~/.local/share/applications` or `/usr/local/share/applications`.

**Comment by aryzing** [comment]
Appreciate the help, found a `dev.zed.Zed.desktop` file in the first location supporting the innonde mime type removed by the PR. Removed it and now all is good
