### ISSUE TITLE
json-language-server appears to be downloaded every time Zed is opened

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#22241]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Every time I open Zed, I get these logged:
```
[INFO] fetching latest version of language server "json-language-server"
..
[INFO] downloading language server "json-language-server"
```

The modification time of ~/Library/Application Support/Zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server is from several months ago.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.2.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by mrnugget** [comment]
It doesn't actually download it, it only checks whether it needs to install a newer version:

https://github.com/zed-industries/zed/blob/cbd2e81a7ef0fc0a65ec1d55a5c35a3947bade03/crates/languages/src/json.rs#L150-L177
