### ISSUE TITLE
Vim: delete sentence forward/backward works differently from select sentence and then delete

### ISSUE THREAD

**Issue by thomasheartman** [zed-industries/zed#22249]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was playing around with Zed's vim mode today and came across the `vim::SentenceBackward` and `vim::SentenceForward` operators. Coming from Emacs, I wanted to see if I could use them to achieve the same as `M-a`, `M-e`, and `M-k`, which do:
- move to the start of the current sentence
- move to the end of the current sentence
- kill till the end the current sentence

The first two work fine with the default bindings (well, technically, you get to the start of the next sentence, but that's often what you want), but the last one: `d)` and `d(` behaves very strangely. It appears to ... act on visual lines? Or something?

I used this text (taken from a different discussion in this repo):
> Recently came across this editor and I have been impressed by the speed of it. I generally use neovim as my main editor 99% and if I am able to incorporate my frequently used keybindings then I can attempt to daily drive Zed. The keybindings I would like to incorporate are:

It might be worth noting that it's all on one line, and my editor is set to wrap when necessary.

It looks like this:
![image](https://github.com/user-attachments/assets/c831eb59-645c-4edc-8162-005e92f84e78)

For the sake of ease in this demonstration, I'll be putting the text in with line breaks in the examples. The `|` character signifies my current position.

Let's take this as the starting position:

```
Recently came across this editor and I have been impressed by the speed of it. I generally use neovim as 
my main editor 99% and if I am |able to incorporate my frequently used keybindings then I can attempt to
daily drive Zed. The keybindings I would like to incorporate are:
```

If I do `v)d`, my result is:

```
Recently came across this editor and I have been impressed by the speed of it. I generally use neovim as 
my main editor 99% and if I am |he keybindings I would like to incorporate are:
```

But if I do `d)`, I get an empty buffer?

```
|
```

Likewise, if I go backwards, `v(d` yields:
```
Recently came across this editor and I have been impressed by the speed of it. |able to incorporate my frequently used keybindings then I can attempt to daily drive Zed. The keybindings I would like to incorporate are:
```

but `d(` yields:
```
daily drive Zed. The keybindings I would like to incorporate are:
```

There's probably more corner cases here, but this is seems strange. It might be because of some settings I've got, but I don't know. Happy to help out! But it's also not something I use very often, so it's not a big deal. (but side note: text objects for SentenceEnd (maybe PreviousSentenceEnd) could be nice, although I've got other text objects I'd much rather see before then)

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

Here's some lines that I pulled out. That unexpected normal mode motion operator may be relevant, but I'm not sure. The rest of the appear to be related to language servers and copilot.

<details><summary>Zed.log</summary>

```
2024-12-19T14:42:28.586261+01:00 [ERROR] buffer has no file
2024-12-19T14:42:44.379473+01:00 [ERROR] buffer has no file
2024-12-19T14:43:25.762092+01:00 [ERROR] Unexpected normal mode motion operator: Object { around: true }
2024-12-19T14:43:39.238653+01:00 [ERROR] buffer has no file
2024-12-19T14:43:55.312477+01:00 [ERROR] buffer has no file
2024-12-19T14:44:14.821107+01:00 [ERROR] buffer has no file
2024-12-19T14:44:24.656767+01:00 [ERROR] buffer has no file
2024-12-19T14:44:32.496813+01:00 [ERROR] buffer has no file

```
</details>

**Comment by jmagaram** [comment]
Maybe related or same as https://github.com/zed-industries/zed/issues/22151

**Comment by thomasheartman** [comment]
Oh, I think you're right. Sorry, I must've not seen that when looking. How I missed it, though, I'm not sure 😳 I'll close this as a duplicate of yours but add my repro case as an additional comment.
