### ISSUE TITLE
Cursor is thinner on blank lines and at the end of lines

### ISSUE THREAD

**Issue by AaronFeickert** [zed-industries/zed#22260]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using a block, hollow, or underline cursor shape, the cursor is thinner (perhaps by a single pixel) on any blank line in a file. This also occurs at the end of a line when not in Vim mode.

This bug is not present when using a bar cursor shape.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by baldwindavid** [comment]
This is not just in empty files. The cursor becomes thinner on any blank line in a file. It has annoyed me for awhile, but apparently not enough for me to report it. :)

**Comment by AaronFeickert** [comment]
So it is! Updated to reflect this.

**Comment by AaronFeickert** [comment]
The issue here is that the cursor width for an empty line is [defined](https://github.com/zed-industries/zed/blob/3632b36fde4c4e73eadc7e231d7b040a3b7fb55b/crates/editor/src/element.rs#L1061) to be an (apparently [historical](https://en.wikipedia.org/wiki/Em_(typography)#Obsolete_alternative_definition) definition of an [em width](https://github.com/zed-industries/zed/blob/3632b36fde4c4e73eadc7e231d7b040a3b7fb55b/crates/editor/src/element.rs#L721-L726). This results in a cursor that is thinner on at least the default fixed-width font.
