### ISSUE TITLE
Wrong cursor theme in Zed (Linux)

### ISSUE THREAD

**Issue by Hy1ex** [zed-industries/zed#22264]
> **I'm using Debian 12 GNU/Linux with KDE Plasma 5 - X11**

After installing Zed from the bash script provided in main page of download for linux(not package manager), I open it and The first thing I notice it was that cursor theme is wrong, This just include the default cursor.

Chroma Black M's default cursor change to Breeze default one
It's like force replace(IDK)

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: Linux X11 debian 12
Memory: 15.4 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 22.3.6

**Comment by jansol** [comment]
I'm not familiar with the X11 side of things, but how did you change your cursor?

**Comment by Hy1ex** [comment]
Using KDE System Settings -> Appearance -> Cursor
X11 is just a display render, I don't think the problem is X11 but I didn't test other display renders like Xorg & Wayland.

**Comment by jansol** [comment]
For all intents and purposes X11 and Xorg are the same thing. And it's arguably *a lot* more than just "a display render".

Anyway Zed treats X11 and Wayland as "platforms" with their own window management, input and mouse handling, hence the label.

**Comment by Hy1ex** [comment]
When I said "Display Renderer", I meant it overall. And I didn't know about how Zed works with These display servers(If I say it correctly) behind the scenes.

**Comment by 0xtimsb** [comment]
I happened to be using KDE with X11, which made it easier to reproduce the issue. I found the suspected problem and created a pull request.
