### ISSUE TITLE
Soft wrap bounded mode missing from docs

### ISSUE THREAD

**Issue by scottyeager** [zed-industries/zed#22272]
### Check for existing issues

- [X] Completed

### Describe the feature

"Bounded" mode for soft wrapping was introduced: https://github.com/zed-industries/zed/issues/8164

But it's missing from the docs:

https://github.com/zed-industries/zed/blob/3632b36fde4c4e73eadc7e231d7b040a3b7fb55b/docs/src/configuring-zed.md?plain=1#L1628-L1640

### Zed Version and System Specs

Affects the currently deployed docs at time of writing.

**Comment by sofaspawn** [comment]
This seems like an easy enough chore, Since its been open for the past week, I think I'll go ahead an fix it. I hope that is acceptable :)

**Comment by sofaspawn** [comment]
I just made a pull request for this issue, I'd be happy if the maintainers could take a look.
