### ISSUE TITLE
Hotkeys for git add and git commit.

### ISSUE THREAD

**Issue by Filipp-Druan** [zed-industries/zed#22298]
### Check for existing issues

- [X] Completed

### Describe the feature

Good afternoon!
I'm working in Zed, and I absolutely hate having to switch to the terminal to type git add and git commit.
Please add a hotkey so that I can add a file that is open in the current tab with a single click. 

It might be a bit more complicated with commit, but I don't think it would be a problem either.

It would make the work much, much more convenient!

### Zed Version and System Specs

Zed: v0.165.4 (Zed)
OS: Linux X11 manjaro unknown
Memory: 7.5 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 4600 (HSW GT2) || Intel open-source Mesa driver || Mesa 24.3.1-arch1.3

**Comment by xdBronch** [comment]
this can be easily done with [tasks](https://zed.dev/docs/tasks), it doesnt really make sense to add something like this officially without the rest of the git integration imo
```json
{
  "label": "git add $ZED_FILE",
  "command": "git add $ZED_FILE",
  "hide": "on_success",
},
```

**Comment by 0xtimsb** [comment]
Duplicate: https://github.com/zed-industries/zed/issues/12925
