### ISSUE TITLE
No action type registered for workspace::MoveItemToPane  

### ISSUE THREAD

**Issue by domschab23** [zed-industries/zed#22358]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I added keybindings for `workspace::MoveItemToPane`

```
  {
    "bindings": {
      "alt-1": ["workspace::MoveItemToPane", { "destination": 0 }],
      "alt-2": ["workspace::MoveItemToPane", { "destination": 1 }],
      "alt-3": ["workspace::MoveItemToPane", { "destination": 2 }],
      "alt-4": ["workspace::MoveItemToPane", { "destination": 3 }]
    }
  },
```

And `workspace::MoveItemToPane` does not move item to other pane. Recording (also shows that alt-1 / alt-2 works as a keybinding to other action)

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

https://github.com/user-attachments/assets/e437a022-83eb-4463-824f-01f5e6d1f6fd

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-22T18:26:42.615504-05:00 [ERROR] invalid binding value for keystroke alt-1, context None

Caused by:
    no action type registered for workspace::MoveItemToPane
2024-12-22T18:26:42.615595-05:00 [ERROR] invalid binding value for keystroke alt-2, context None

Caused by:
    no action type registered for workspace::MoveItemToPane
2024-12-22T18:26:42.61566-05:00 [ERROR] invalid binding value for keystroke alt-3, context None

Caused by:
    no action type registered for workspace::MoveItemToPane
2024-12-22T18:26:42.615723-05:00 [ERROR] invalid binding value for keystroke alt-4, context None

Caused by:
    no action type registered for workspace::MoveItemToPane
```
</details>

**Comment by domschab23** [comment]
Related to https://github.com/zed-industries/zed/issues/20205 and cc @Igonato

**Comment by Igonato** [comment]
> Zed: v0.166.1 (Zed)

Yep. It's the version before the change. The change went live in 0.167 (currently a pre-release) https://zed.dev/releases/preview/0.167.0

**Comment by domschab23** [comment]
Good to know it was a user error in the end :) Thanks for replying
