### ISSUE TITLE
Unable to install on M3 Macbook Air

### ISSUE THREAD

**Issue by Skywalker311** [zed-industries/zed#22365]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1029" alt="Screenshot 2024-12-22 at 9 53 24 PM" src="https://github.com/user-attachments/assets/e87b78da-1820-47aa-bc76-24d780423215" />

I am getting a dialog box shown in the image above when trying to install Zed on my new M3 Macbook Air 

### Zed Version and System Specs

Zed Version: 0.166.1
System: mac os 15.2
M3 16GB RAM

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by 0x2CA** [comment]
Normally, there should be corresponding directory permissions.

Can you check the permissions of this directory?

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/13426#issuecomment-2187288480 here are the command examples.
Will include those in the modal after https://github.com/zed-industries/zed/pull/22368 , and closing this for now.
