### ISSUE TITLE
Zed can't use o1-preview model in GitHub Copilot chat since GA by GitHub

### ISSUE THREAD

**Issue by chirpcel** [zed-industries/zed#22375]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Activate GitHub Copilot assistant integration
2. Open assistant chat and choose GitHub Copilot Model 'o1-preview'
3. Send a message to chat

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.2.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![CleanShot 2024-12-23 at 16 29 22@2x](https://github.com/user-attachments/assets/c1e36612-332a-43af-acae-56a0135db3ba)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
The fix for this will be available Wednesday Jan 1st in Stable and Preview releases or with the next hotfix release if one goes out before then.
