### ISSUE TITLE
Open on GitHub (remote)

### ISSUE THREAD

**Issue by carloscuesta** [zed-industries/zed#22393]
### Check for existing issues

- [X] Completed

### Describe the feature

Hey! 👋🏼  

As a user, I’d love the ability to open a specific file on the repository’s remote (GitHub) directly from my editor. This would make it much easier to share links with team members and point to specific parts of the codebase.

This feature was previously available in Atom via the [open-on-github package](https://github.com/atom/open-on-github/tree/master):  

> ![Preview of the Open on GitHub feature](https://github.com/user-attachments/assets/569913da-63b8-4305-b41e-fcb4e5783474)

A few potential implementation details:

- An option "Open on GitHub" through the command palette.  
- Shortcuts support for quick access.  
- Deep linking to specific lines of code if a range is selected.  

Let me know if you need more details or examples—happy to help! 😊

Happy holidays! 🎄✨ 

### Zed Version and System Specs

Zed: v0.165.4 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Qkessler** [comment]
You actually can with `editor: open permalink to line`. Let me know if that's enough.

**Comment by carloscuesta** [comment]
Hey! 👋🏼 

Thanks for the quick response. That's what I was looking for, definitely a few more options can be added into this functionality (see atom ref) but it solves the issue 😊

**Comment by dastrobu** [comment]
Is there also an action to open the remote repository (without a specific reference to a file)? Would be helpful to check for open issues/PRs...
