### ISSUE TITLE
zed creates the LSP process but does not close it

### ISSUE THREAD

**Issue by DJCCRK** [zed-industries/zed#22411]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I first used zed to open a Go project folder, I could see in the system monitor that zed created a gopls process, which is normal. But when I used the ctrl+alt+o shortcut to open another Go project in this window, zed would create another gopls process, but would not close the previous gopls process. Now I have only opened one project, but there are two gopls processes running in the background, each of which takes up about 300MB of memory. If I switch projects frequently, my machine's memory will soon be filled up by the gopls processes created by zed.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: Linux X11 ubuntu 24.10
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.2.3-1ubuntu1

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![截图 2024-12-25 14-14-26](https://github.com/user-attachments/assets/74dc1ef3-9fc3-4132-a272-c9795a0382ae)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by CharlesChen0823** [comment]
depulicate #21906
