### ISSUE TITLE
Cannot save empty file because `ensure_final_newline_on_save` adds a newline

### ISSUE THREAD

**Issue by injust** [zed-industries/zed#22474]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With `ensure_final_newline_on_save` enabled (which is by default), Zed adds a newline to empty files, making it impossible to save an actually empty file.

This is _technically_ correct, as an empty file doesn't have a trailing newline...but you probably never want this behaviour.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: x86_64

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/11044
