### ISSUE TITLE
`use_autoclose` is not respected when writing Rust

### ISSUE THREAD

**Issue by iriri** [zed-industries/zed#22493]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Configure `"use_autoclose": false` (and also `"use_auto_surround": false` for good measure) and perform the following editing actions:
```rust
use std::collections::VecDeque;
//                    ^ Insert `{` here

fn foo(x: i32) {
   match x {
      _ => (),
      //   ^ Insert `(` here
   }
}
```
Expected outcome:
```rust
use std::collections::{VecDeque;

fn foo(x: i32) {
   match x {
      _ => ((),
   }
}
```
Actual outcome:
```rust
use std::collections::{VecDeque};

fn foo(x: i32) {
   match x {
      _ => (()),
   }
}
```

### Zed Version and System Specs

Zed: v0.168.0 (Zed Dev f6dabadaf79bd29c89c8d55a1e9f1d33236f736e) OS: Linux Wayland

**Comment by SomeoneToIgnore** [comment]
Besides Zed, LSP may also place brackets after typing.

This is enabled by default

https://github.com/zed-industries/zed/blob/344284e01331667c018e6ade5d791a20598a3a5c/assets/settings/default.json#L179-L181

and rust-analyzer does insert brackets.
See https://rust-analyzer.github.io/manual.html#on-typing-assists for more details.

You can either disable `use_on_type_format` (globally or per language), or configure rust-analyzer language server with
`"rust-analyzer.typing.excludeChars": "<|"` (note that this is VSCode syntax, in Zed, you need to replace each `.` with an object, https://zed.dev/docs/languages/rust has some examples.
