### ISSUE TITLE
Allow View > Terminal Panel to always return focus to last-used terminal?

### ISSUE THREAD

**Issue by mcabbott** [zed-industries/zed#22510]
### Check for existing issues

- [X] Completed

### Describe the feature

At present, clicking View > Terminal Panel in the menu (shortcut  ``` cmd-c ctrl-` ```) switches focus to the most recently used terminal located in the Bottom Dock, or opens a new one if needed. 

I can drag such a terminal pane to the right of the screen, ~~into the Right Dock,~~ and use it there. But once I do this, the command / shortcut no longer switches to my existing terminal, but instead opens a new one at the bottom.

I don't know if this is a bug report or a feature request, but I'd like this (or another) shortcut to follow where I put the terminal. On the side of the screen, it takes up less-valuable space. 

Possibly related to #21144. Also discussed in a work-around for #16102.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.1.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

Edit -- screenshot added after some clarification of terminology / dock behaviours below. 

<img width="832" alt="Screenshot 2024-12-30 at 19 37 31" src="https://github.com/user-attachments/assets/d0256363-124f-416b-a105-0792c684ea70" />

**Comment by SomeoneToIgnore** [comment]
> I can drag such a terminal pane to the right of the screen, into the Right Dock,

Can you elaborate on that?
As of now, no docs can be dragged, it's the settings update or right click on the dock button & "Dock right" click that makes the terminal pane to move to the right dock:

<img width="371" alt="image" src="https://github.com/user-attachments/assets/0e4b9f22-7a28-43f2-a2f4-1fc5822dfe37" />

If you do drag something, this is not moving the Dock, splitting the central pane instead:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/de5e742a-f47f-4130-9b4d-460722067359" />

in this case, the behavior is expected, as the action tries to open the terminal panel, which is still at the bottom.

I have moved my terminal pane to the right dock with the right click, and action works for me as expected:
> switches focus to the most recently used terminal located in the Bottom Dock, or opens a new one if needed.

**Comment by mcabbott** [comment]
Thanks for having a look!

OK, now I see that:
* The home of the terminals can indeed be permanently moved to the right as you show, to what's really called the right dock. (After this, "View > Toggle Bottom Dock" does nothing, while "View > Terminal Panel" acts on this right dock.) I did not think to right-click that button.

* Previously, I dragged just one terminal (pane? tab?) out of the dock, to a right column which seems to be called a column of the central pane. This is the case when  "View > Terminal Panel" opens a new terminal (in the dock/panel) instead of re-using the open one. (If I drag the terminal from the central pane back to the dock, it can become again the one "Terminal Panel" refers to.)

There are advantages and disadvantages to having the terminal in this special dock, vs. mixed up with other files. It's easier to hide the special dock, and having it on the right is a partial solution for me.

Having the terminal as a split part of the central pane (mixed up with files), I can split again to have some other file visible. That's nice for e.g. looking at plots. Perhaps changing "View > Terminal Panel" to snap me there would annoy other people. In which case, the request is really for some easy way to go back to the most-recently used terminal, wherever it is located.

**Comment by SomeoneToIgnore** [comment]
I do not think we will be changing this part in the near future:

* the split-off terminal is not in the dock, and not in the terminal panel, so focusing it with the `View > Terminal Panel` seems wrong

* for each pane (central or in the terminal panel), we have history which can be navigated + various "activate split N" actions. That split-off terminal is yet another item in the pane, so it should already obey these actions, making focusing it somewhat more convenient.

I agree that there's even better convenience with re-focusing the last terminal, but from Zed's side that will be quite a complication to both pieces of logic from the bullets above.

For now, it seems that the right dock + `workspace::ActivatePane` (cmd-digit on mac layout) cover 80% of the use cases.
