### ISSUE TITLE
Release DMG images should be accessible on non-APFS systems.

### ISSUE THREAD

**Issue by mrcbax** [zed-industries/zed#4199]
Th release DMG images are currently being packaged as APFS, this is unacceptable for those of us with older machines. It is considered bad practice to release the DMG as anything other than HFS+.

Even if the alpha versions are targeting only the latest version of MacOS at this time, this needs to be addressed moving forward so that it doesn't become an issue later.

**Comment by JosephTLyons** [comment]
Because Zed [only officially supports macOS Catalina (10.15)](https://zed.dev/download) and because HPS+ was replaced with <> in macOS High Sierra (10.13), it seems like we likely won't support HPS+. I'm going to close this issue out.
