### ISSUE TITLE
Show lines selected

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#4204]
I noticed that the number of characters selected is now shown down in the bottom right.  I think it is very useful when the editor shows the number of lines selected as well.

An example using Sublime Text (I think their way of showing this is pretty nice):

When the cursor is not highlighting text:

<img width="94" alt="CleanShot 2021-11-30 at 23 49 23@2x" src="https://user-images.githubusercontent.com/19867440/144173940-075f2f60-8afc-4d04-8a70-c27bd3541213.png">

The display shows:

<img width="95" alt="CleanShot 2021-11-30 at 23 49 30@2x" src="https://user-images.githubusercontent.com/19867440/144173969-13c80380-30ae-47d2-9598-22e7b6b91929.png">

Once you highlight some text:

<img width="98" alt="CleanShot 2021-11-30 at 23 49 53@2x" src="https://user-images.githubusercontent.com/19867440/144173992-fdf34073-56bf-46b3-87cb-666102a86744.png">

The display switches to this:

<img width="171" alt="CleanShot 2021-11-30 at 23 50 06@2x" src="https://user-images.githubusercontent.com/19867440/144174014-45dfefd5-b9be-4d61-bb6c-4b654374bded.png">

This is just an example.  I do sort of like that Zed still shows the cursor position when text is highlighted.

Maybe for Zed, when no text is highlighted, you'd see:

`1,1`

When a single line of text is highlighted

`1,17 (16 characters)`

When a multiple lines of text is are highlighted:

`13,3 (13 lines, 206 characters)`

**Comment by titouandk** [comment]
I think the bottom bar should also tell us the number of active cursors:

<img width="256" alt="number-of-cursors" src="https://github.com/zed-industries/zed/assets/5413308/64c83b97-d5bc-421c-b99e-7bb3594c1281">

**Comment by weartist** [comment]
@JosephTLyons Hi, would like to ask you for help with this problem, does this issue still need to be optimized?

**Comment by bartekpacia** [comment]
I would really love to see this small yet useful feature implemented in Zed. It's a shame that in VSCode I need an extension for that.

In addition to the "full display" mode as described in the OP:

```
13,3 (13 lines, 206 characters)
```

I'd also like to see a "mini display" mode:

```
13,3 (13 l, 206 c)
```

so it wouldn't take up too much space.
