### ISSUE TITLE
publish zed to nixos package registry

### ISSUE THREAD

**Issue by brizzbuzz** [zed-industries/zed#4252]
Hey :) so excited this is open-sourced now.

Would love for this to be published to the nix package registry for easy installs to NixOS

**Comment by srid** [comment]
Adding a `flake.nix` to this repo would also be an useful thing to do because, in addition to being able to `nix run`'ing it off this repo (without relying on nixpkgs), you can also use Nix to [develop](https://nixos.asia/en/dev) on the project. 

The flake can also be used as reference for upstreaming to nixpkgs at this point, making that a simpler process.

**Comment by Reverier-Xu** [comment]
*zed currently only supports macOS, and getting it to support Linux may take a while of work.

**Comment by gimbling-away** [comment]
> *zed currently only supports macOS, and getting it to support Linux may take a while of work.

Nix is available on macOS. :)

**Comment by toplinuxsir** [comment]
Support linux is a great idea

**Comment by liberodark** [comment]
I hope a package for NixOS

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/284010

**Comment by musjj** [comment]
Already merged now. But an upstream `flake.nix` would still be nice to have to make it easier for Nix users to contribute.

**Comment by boomshroom** [comment]
Complication: Zed downloads its own prebuilt binary of NodeJS (currently `18.15.0`; closest version in nixpkgs is `18.20.2`). While less of an issue for MacOS or other Linux distros that have Nix added on, NixOS itself wouldn't be able to run the packaged version of node without [`nix-ld`](https://github.com/Mic92/nix-ld).

**Comment by PedroHLC** [comment]
> Complication: Zed downloads its own prebuilt binary of NodeJS (currently `18.15.0`

We could substituteInPlace the occurrences of `zed::node_binary_path()`, that would help a lot.

But Zed could use having more configurable paths (Settings and/or EnvVars) because for example, the elm-language-server support is very tied to using it through their nodejs, meanwhile we could use it from drop-in executable.

**Comment by libewa** [comment]
> but then we have to install the extensions as dev

This could be partially fixed (or worked around) by publishing the extensions to nixpkgs using a zedExtensions namespace (i.e. publishing the extensions as `zedExtensions.something`) and installing them through [home-manager]. I am currently working on a home-manager module for Zed, so installing extensions with nix would also be one of my bucket list items.

[home-manager]: https://github.com/nix-community/home-manager

**Comment by libewa** [comment]
I got this working using `auto_install_extensions`, the module is now waiting for approval in nix-community/home-manager#5455.

**Comment by sokai** [comment]
JFYI: https://zed.dev/blog/zed-on-linux
.oO(Maybe it can help here?)
KR

**Comment by IvanTurgenev** [comment]
Looks like it is already there

**Comment by PedroHLC** [comment]
yeah, this can be closed, Nixpkgs has the latest tag that can be built with rust 1.79 (and pretty sure as soon as 1.80 is in-repo we'll bump it again)

**Comment by acgxv** [comment]
It seems that this hasn’t been updated for quite some time.

**Comment by sokai** [comment]
Hey @aurexav ! This is sad. But maybe you _should better ask_ the maintainer(s) at nixpkgs (from [the initial package PR](https://github.com/NixOS/nixpkgs/pull/284010)?). KR

**Comment by jansol** [comment]
Idk what you're complaining about, Zed in nixpkgs was updated to this week's stable version literally a few hours after it dropped on zed.dev: https://github.com/NixOS/nixpkgs/pull/463288
