### ISSUE TITLE
Ability to Duplicate Line Upward

### ISSUE THREAD

**Issue by EvanZhouDev** [zed-industries/zed#4259]
### Check for existing issues

- [X] Completed

### Describe the feature

In addition to the `editor::DuplicateLine` command, also have an `editor::DuplicateLineUpward`, which copies the line above the current line, and moves the cursor up to the line above. Like the default `alt-shift-up` behavior in VSCode.

**Comment by t-eckert** [comment]
I have some notion of how this would be done. Starting [here](https://github.com/zed-industries/zed/blob/90c1d8f734615552297a65e12dd430bf0825cdb0/crates/editor/src/editor.rs#L4753), the function could be duplicated to create a `duplicate_line_up` func. 

My thinking is that these lines would need to be changed somehow to copy the line to the right place:

```rust
            let start = Point::new(rows.start, 0);
            let end = Point::new(rows.end - 1, buffer.line_len(rows.end - 1));
            let text = buffer
                .text_for_range(start..end)
                .chain(Some("\n"))
                .collect::<String>();
            edits.push((start..start, text));
```

I would be happy to tackle this if someone was willing to jump on and pair with me to get me started. I could take it over the finish line.

**Comment by EvanZhouDev** [comment]
@t-eckert Any updates? This is genuinely one of the only features left (never knew I was so reliant on such an obscure thing!) that would get me to migrate to VSCode (other than Copilot Chat, but that's slightly less priority)... please let me know if you have any ideas.

**Comment by ExplodedViewMelon** [comment]
You can do the following to get the desired functionality:
```
"bindings": {
    "shift-alt-down": "editor::DuplicateLine",
    "shift-alt-up": ["workspace::SendKeystrokes", "shift-alt-down up"],
}
```

**Comment by EvanZhouDev** [comment]
@Moshyfawn this looks great! Thank you.
