### ISSUE TITLE
Enable additional Elixir Language Server configuration

### ISSUE THREAD

**Issue by mattbaker** [zed-industries/zed#4260]
### Check for existing issues

- [X] Completed

### Describe the feature

ElixirLS provides the ability to disable dialyzer, but I can't see a way to pass that configuration to Zed. 

Is this possible? If so, we should update the ElixirLS docs. If not this would be a feature request.

**Comment by crbelaus** [comment]
I was going to open a similar issue but found this one first.

Dialyzer is slow and not used by every project. Having the possibility of disabling it would be great.

**Comment by mattbaker** [comment]
The setting in question:
https://elixir-lsp.github.io/elixir-ls/features/#dialyzer-integration

**Comment by mattbaker** [comment]
@joetrimble Yeah I was hoping that would work too! I've tried various permutations and none of them seemed to have any affect unfortunately, but it was a good idea

**Comment by moomerman** [comment]
I have a branch that "works" but isn't complete, I got stuck on some rust-specific stuff that I couldn't understand and chat CPT was no help at all! 

https://github.com/moomerman/zed/tree/workspace-configuration

this allows you to add config like this in Zed's `settings.json`

```json
"lsp": {
    "elixir-ls": {
      "workspace_configuration": {
        "elixirLS": {
          "dialyzerEnabled": false
        }
      }
    }
  }
```

**Comment by mattbaker** [comment]
@moomerman I don’t know Rust but maybe you could open a PR and someone could help get it over the finish line?  This is awesome!
