### ISSUE TITLE
Zed doesn't respect file access permissions

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#4261]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a file with Zed from a protected location, such as Desktop or iCloud Drive, for the first time, a files and folders access dialog will appear. If permission is not granted, Zed will still open and display the file. All further file openings will be allowed from the protected location and won't display the Files and Folders Access dialogue.

This behaviour occurs in both Zed Beta and Zed Preview, whether via the system menu or file dropping.

Toggling the permission on and off in the system settings does not change this behaviour.

### Environment

Zed: v0.118.1 (Zed), v0.119.9 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![zed-file-access-permissions](https://github.com/zed-industries/community/assets/16290753/c3de7cae-7c04-4810-8167-452902ac7d01)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
My understanding is that the folder based sandbox restriction does not restrict access to individual files which are are dropped or accessed to via file open -- instead it restricts the ability of the application to enumerate the files in those directories and attempt to open other files not through the system dialogs.

So if you deny the access it's actually not the opening of the file that triggered that prompt (dragging/opening the file means it is already "allowed") it's likely Zed attempting to access the parent directory (Desktop/Downloads) that is triggering the prompt.

Additionally, if I remember correctly, MacOS keeps a cache of recent files. So if you've opened a file once via drag/drop or via the Open File dialog, Zed will continue to have access for the future even if you directly open it (say via the project panel).

I think this is behaving as designed.
