### ISSUE TITLE
Vim: support `gn` command

### ISSUE THREAD

**Issue by baldwindavid** [zed-industries/zed#4273]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm enjoying Zed and the vim mode has really come a long way since the last I tried it. I've attempted switching to this as my full-time editor and finding that apparently my muscle-memory leverages vim's `gn` command extensively.

I am happy to elaborate, but VimCasts can do it more justice than I... http://vimcasts.org/episodes/operating-on-search-matches-using-gn/

Perhaps this is supported _somehow_ in Zed of which I'm not aware. Regardless, as of now it appears the default vim keymap in Zed assigns `g n` already as documented at https://docs.zed.dev/general/vim#zed-specific-features...

```
g n   Add a visual selection for the next copy of the current word
```

If the intent is to eventually, as noted in the documentation, "do what you expect", the `gn` command is one I'd expect to be present.

**Comment by algora-pbc** [comment]
💎 **baldwindavid** is offering a **$100** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #4273` in the PR body and joining algora.io

**Comment by joaquin30** [comment]
Hi, so for earning the bounty I need to rebind `gn` to `gl` and implement `gn` vim original funcionality, right?

**Comment by baldwindavid** [comment]
Hi @joaquin30 ! It's solely about matching the functionality of the `gn` command provided by vim.

As for rebinding `vim::SelectNext/Previous`, the `gl` keybind seems fine, but I'd leave that decision up to @ConradIrwin and @mrnugget .

**Comment by ConradIrwin** [comment]
Yup, we should change the current gn to gl

**Comment by algora-pbc** [comment]
🎉🎈 @joaquin30 has been awarded **$100** by @baldwindavid! 🎈🎊

* [Share on socials](https://console.algora.io/awards/cludkas2d0001l30fdxqs9ake)
* [Give feedback](https://console.algora.io/claims/cludkas2d0001l30fdxqs9ake)

**Comment by baldwindavid** [comment]
Really great work! My perception is that the `gn` command is very underrated/utilized, but it's incredibly useful for my workflow. Thanks so much.
