### ISSUE TITLE
Adding parentheses to highlighted text replaces the text in Lua 

### ISSUE THREAD

**Issue by marc2o** [zed-industries/zed#4287]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce the issue:

- Open Lua source code or create a new file and set the language to **Lua**
- type something, such as `foo`
- highlight/select the term and then type `(`

As a result the term `foo` is replaced by `(`.

Expected behavior: the term `foo` is enclosed in parentheses `(foo)`.

The problem only exists with parentheses – brackets `[ ]`, braces `{ }` and quotes `" "` do work as expected. As far as I tested, the issue is only present in Lua. (In Plain Text, none of the above works, but that is not really a problem.)

### Environment

Zed 0.118.1
MacBook Air (Apple M2, 8 GB)
macOS 14.2.1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
I believe this was recently fixed and I am no longer able to reproduce this in the current Zed stable version.

Thanks for reporting this (I'm a lua user too and this was a pain point) and feel free to reopen if you are still seeing this issue. Thanks!

**Comment by marc2o** [comment]
@notpeter Thanks for getting back to this. After it was transferred, I could no longer follow. But I noticed when it was fixed, really a while ago, and I am glad about it!
