### ISSUE TITLE
Pressing Tab to accept copilot autocomplete suggestion doesn't work

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#4288]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After pressing Backspace to clear the indentation to "help" Copilot work out what to suggest next, I can't accept the Copilot's suggestion.

### Environment

Zed: v0.118.1 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

Zed: v0.119.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/16290753/636e1d07-ecd8-4f82-8598-69543e8b162d

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mmtftr** [comment]
I also experience this issue

**Comment by Moshyfawn** [comment]
This has become harder to reproduce _(perhaps some fixes have been made)_, but it's still very noticeable to me when I get a long copilot suggestion. Note in the screencast below how I don't have the cursor when the first (pre-cached) suggestion appears, but the cursor appears when I get a more concise suggestion paragraph.

https://github.com/zed-industries/zed/assets/16290753/91ba9f78-c336-4004-b87a-aad7fcab43a7

**Comment by Moshyfawn** [comment]
I'm going to close this one in favour of the other one, because it has both more info and a bigger conversation. Be sure to +👍.

Duplicate of
- #4549
