### ISSUE TITLE
Support "boundary" option for rendering whitespace

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#4290]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm missing this option from VS Code.
Showing leading indentation is important, and trailing spaces make it clear to be trimmed, but I don't care about normal single whitespace between code (multiple ones should still show; see example from VS Code below).
<img width="402" alt="image" src="https://github.com/zed-industries/community/assets/5619348/7649fb41-2401-4895-8c77-60e7812ce67d">

### Example
VS Code:
<img width="502" alt="image" src="https://github.com/zed-industries/community/assets/5619348/4d1e9255-3f94-464e-8867-be8d267b80b8">
Zed (using "show_whitespaces"="all"):
<img width="498" alt="image" src="https://github.com/zed-industries/community/assets/5619348/2c97daa7-a720-40fb-80e8-cdec9ecff784">

**Comment by JosephTLyons** [comment]
This just landed in [v0.139.0-pre](https://zed.dev/releases/preview/0.139.0) today.

**Comment by wzxu** [comment]
@JosephTLyons Great news, but default settings and doc doesn't seem to have been updated?

<img width="678" alt="38383" src="https://github.com/zed-industries/zed/assets/5619348/ff85c5bd-4831-4dfd-8ee3-67b89e54cbb0">

Zed: v0.139.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Thanks for the catch, added some docs in https://github.com/zed-industries/zed/pull/12717

**Comment by CodaBool** [comment]
sorry to comment on closed ticket but the docs weren't updated

https://zed.dev/docs/configuring-zed#show-whitespaces

**Comment by SomeoneToIgnore** [comment]
Thanks for spotting another docs place, feel free to toss in the PR next time if you want to.
I've added the fourth option in https://github.com/zed-industries/zed/commit/124878878069a0aa52e97e531fef22fbef43e12f but since the list is quite brief, omitted the `boundaries` description.
