### ISSUE TITLE
--query-driver for clangd

### ISSUE THREAD

**Issue by giuseppesalvo** [zed-industries/zed#4295]
### Describe the feature

When cross-compiling C++ projects, it's useful to pass the [--query-driver](https://releases.llvm.org/10.0.0/tools/clang/tools/extra/docs/clangd/Configuration.html) option to `clangd` with the compiler used, so `clangd` can properly extract the include paths. 

After reading the Zed docs, I tried something like this, but it doesn't seem to work

```json
{
  "lsp": {
    "clangd": {
      "initialization_options": {
        "--query-driver": "path/to/compiler"
      }
    }
  }
}
```
Is there a way to pass custom configuration options to LSPs using the `settings.json`? Maybe undocumented, with a different syntax. If not, it would be great to be able to, in the future.

**Comment by danieroux** [comment]
`--query-driver` is not part of the LSP `initialization_options`.

It is a flag that has to be set when calling the `clangd` binary. No flags are (and can be) passed to the `clangd` binary: https://github.com/zed-industries/zed/blob/3a43adba005ce0ccce950dad9e3521e80517cbd7/crates/languages/src/c.rs#L320

**Comment by hferreiro** [comment]
You can pass arguments if you provide the path to a local binary: https://github.com/zed-industries/zed/pull/10608

**Comment by notpeter** [comment]
@giuseppesalvo Can you try this and see if it works for you?
```
{
  "lsp": {
    "clangd": {
      "binary": {
        "path": "/usr/bin/clangd",
          "arguments": ["--query-driver"]
      },
    }
  }
}
```

**Comment by danieroux** [comment]
@hferreiro Ah, thank you. Writing it down here: https://github.com/zed-industries/zed/pull/13740/

**Comment by giuseppesalvo** [comment]
@notpeter I tried with the latest Zed build available, but it doesn't seem to work. 
I suspect that the `binary` field is ignored, so neither the binary path or the arguments are respected. Does it work for you?

**Comment by danieroux** [comment]
@hferreiro It does not seem to work for me. It seems `binary` gets ignored, mirroring @giuseppesalvo's experience. I tried Preview and current Stable:

Local settings for the project:

 ```
$ cat .zed/settings.json
// Folder-specific settings
//
// For a full list of overridable settings, and general information on folder-specific settings,
// see the documentation: https://zed.dev/docs/configuring-zed#folder-specific-settings
{
  "lsp": {
    "clangd": {
      "binary": {
        "path": "/nix/store/47z3292wf87i4d1ivyqxa2ds7bnj9dal-clang-tools-16.0.6/bin/clangd",
        "arguments": ["--log=verbose"]
      }
    }
  }
}

```

`clangd` is there: 

```
$ /nix/store/47z3292wf87i4d1ivyqxa2ds7bnj9dal-clang-tools-16.0.6/bin/clangd --version
clangd version 16.0.6
Features: mac
Platform: aarch64-apple-darwin23.5.0
```

When opening the project, it starts this `clangd`:

```
$ ps -ef | grep clang
  501 68428 68057   0  5:08PM ??         0:00.00 /Library/Developer/CommandLineTools/usr/bin/clangd
```

(I am also trying to set `--query-driver`)

**Comment by KaeLL** [comment]
Can confirm `lsp.clangd.binary` is getting completely ignored. I have to `ln` my way into making Zed use the clangd I want, otherwise it uses its own. Checking htop, seems arguments are also not getting relayed to clangd.

**Comment by carterols** [comment]
I am too seeing that the `lsp.clangd.binary.arguments` are not getting passed to clangd when it is started.

**Comment by carterols** [comment]
Ah, so after investigating, I found that Zed ignores the LSP settings if the user specifies them at the project-level. You must specify them at the user-level settings, which isn't ideal, as this currently doesn't work with remote development.

This is definitely a bug. Looking at the code, we should also make the C/C++ LspAdapter's code similar to that of Rust or Go or abstract it.
@hferreiro

**Comment by oliverlee** [comment]
> Ah, so after investigating, I found that Zed ignores the LSP settings if the user specifies them at the project-level. You must specify them at the user-level settings, which isn't ideal, as this currently doesn't work with remote development.

@carterols Is there an issue tracking this?

**Comment by carterols** [comment]
@oliverlee No, not that I'm aware of.

**Comment by notpeter** [comment]
> Zed ignores the LSP settings if the user specifies them at the project-level.

@oliverlee @carterols I believe this is fixed in main and will be available in Zed Preview on Wednesday.
- https://github.com/zed-industries/zed/pull/17753

**Comment by giuseppesalvo** [comment]
Can confirm that this now works correctly!
