### ISSUE TITLE
Inline assist button 

### ISSUE THREAD

**Issue by seenyat** [zed-industries/zed#4297]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When pressing inline assist button, ui panel can be opened infinitely many times. Each one requires to close it with escape button.
![CleanShot 2023-12-26 at 10 15 59@2x](https://github.com/zed-industries/community/assets/2016169/d41c41a7-9567-40d6-a9df-7869f1e3b4c3)
![CleanShot 2023-12-26 at 10 17 38@2x](https://github.com/zed-industries/community/assets/2016169/3e6f3c8a-c750-4231-8890-de61bd6c18f4)

### Environment

Zed: v0.118.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by piotrpalek** [comment]
Would this be a good first issue to work on if somebody wants to get their hands dirty?

**Comment by seenyat** [comment]
Looks like this issue is not longer relevant for newest version, feel free to close it.
