### ISSUE TITLE
Double quotation auto insert bug on Macos

### ISSUE THREAD

**Issue by allyfx** [zed-industries/zed#4298]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On Mac you need to add double quotes and then hit space for it to be considered as a single character. For example, if I type `"` and then the character `a` without hitting space it makes this character -> `ä`. But when I hit space on Zed it doubles the quotes like this `""""` and I have to remove the quote.

This is because of the keyboard layout. In Brazilian's we need to have this feature because of the language's accents that has conflict with english's quotes. For example the `'` can also be used to create the `é` accent.

So maybe this is a bug that happens because of different keyboard layouts.

### Environment

MacBook Pro M1 macOS Sonoma 14.1.2
Brazilian input sources (Brazilian input layout)
![Screenshot 2023-12-25 at 12 17 59](https://github.com/zed-industries/community/assets/66289769/618333d0-2e83-4c28-a6f8-b6196fc547ea)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/66289769/20ed97fe-90cb-4dd0-9b26-4dc35c6c51d1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by andremacola** [comment]
I had already posted in some issues about the problem, but they never took this issue seriously with International English-type keyboards.

Zed is almost unusable for those who use keyboards that are not US and need accentuation.

There are several problems that exist, but I also highlight one which is:

1 - Select a sentence or a string.
2 - Put double quotes so that quotes are applied to the entire selection.
3 - Press any key on the keyboard and the quotes will multiply.


https://github.com/zed-industries/zed/assets/3408809/3fc70011-28e5-4ddf-a2ad-ce229351e2e4

**Comment by allyfx** [comment]
@andremacola Yes! This happens to me as well. This and other issues make Zed unusable for me while working and on a daily environment. Now I can only use it when I'm working on personal projects (which I'm ashamed to say is not a big part of my weeks). Now that it's open source I believe we can get together to find a solution for this.

I'll try and see if I find anything, if you want to join me let me know. It'd be really helpful (I have zero to none experience with editors haha)

**Comment by t1gu1** [comment]
This is the issue that me it not really usable for me..

**Comment by t1gu1** [comment]
This is the issue that me it not really usable for me.

My keyboard layout is `US international`.

I even change that setting to be false `"use_autoclose": false` and still have that issue..

**Comment by mrnugget** [comment]
Can someone give me some exact steps to reproduce and expected vs. actual behaviour?

I just switched to the Brazilian layout and I can type `"` and `ä` and `""` fine:

https://github.com/zed-industries/zed/assets/1185253/9c02e238-c663-45ac-96de-3cdc23b7f36a

Is the problem that you don't have to press `<space>` to get out of the dead key state?

**Comment by allyfx** [comment]
@mrnugget Basically the problem is that we don't have support for when you want to press `<space>` to get out of the dead key state, because doing so will duplicate the quotes.

As I said, in Brazillian's keyboard we need this feature to leave the state of (I'll call it "pressed quote"). If you don't press `<space>` and instead press any vowel it'll add accents.

If you're using Mac, you'll see that when you type one of the quotes before pressing `<space>` the quote gets highlighted with an underscore, indicating that it's in the "pressed quote" state and that if you press a vowel it'll apply the accent. See attached image:
![Capture d’écran 2024-02-05 à 08 34 19](https://github.com/zed-industries/zed/assets/66289769/50b6b225-7154-4d80-9f73-0d211a9db365)

The current behavior is:
- Press `"` and it creates `""`
- Press `<space>` and it duplicates `""""`

The expected behavior is:
- Press `"` and it creates `""` (or not, this should be customizable)
- Press `<space>` and it leaves the "pressed quote" state and doesn't duplicate the quotes

With the expected behavior it'll prevent annoying problems like:
- Press `'` and it creates `''`
- Press `a` and it changes to `á`

Hope this explanation explains better. Let me know if you need further informations.

**Comment by mrnugget** [comment]
Thanks @allyfx! Very helpful. One question: when you open an empty new buffer, with no language set, do you agree that it works as expected? i.e. the input handling is only a problem when auto-insertion of brackets is involved, yes?

**Comment by ponei** [comment]
Also experiencing this. Very annoying when typing anything related to strings.

**Comment by mrnugget** [comment]
Doesn't fix _this_ yet, but it's certainly one first improvement: https://github.com/zed-industries/zed/pull/7488

**Comment by mrnugget** [comment]
Doesn't fix _this_ yet either, but here's the next one improvement: https://github.com/zed-industries/zed/pull/7494

**Comment by mrnugget** [comment]
Here's the final fix: https://github.com/zed-industries/zed/pull/7611

**Comment by andremacola** [comment]
> Here's the final fix: #7611

This not solves all the problems in the keyboard, the issues I post here still there.

> I had already posted in some issues about the problem, but they never took this issue seriously with International English-type keyboards. I hope that now that it has become open source, we can see some progress in this area.
> 
> Zed is almost unusable for those who use keyboards that are not US and need accentuation.
> 
> There are several problems that exist, but I also highlight one which is:
> 
> 1 - Select a sentence or a string. 2 - Put double quotes so that quotes are applied to the entire selection. 3 - Press any key on the keyboard and the quotes will multiply.
> 
>  Gravacao.de.Tela.2024-01-27.as.14.14.13.mov

**Comment by joyousblunder** [comment]
Hey, I am having the exactly same problem here. Brazilian with an International English keyboard, but this time on Fedora linux 41 and zed 0.164.2. Can we reopen the issue or create a new one?

**Comment by Nic-Soares** [comment]
Same error here

`¨` + `space` resulting in `"""""""`

https://github.com/user-attachments/assets/cffa2af9-4fb1-412c-9501-626111607b40
