### ISSUE TITLE
Support for Gemini Pro API Key

### ISSUE THREAD

**Issue by gophersumit** [zed-industries/zed#4299]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed currently supports OpenAPI keys as part of assist. Now with launch of Gemini Pro, it should be possible to build enhance assist interface to support Gemini Pro keys.

**Comment by avastmick** [comment]
I'd like to bump this, if I may. 

I have been using "Gemini Advanced" (via a browser session) for a week, and I get a much higher rate of accuracy than I have been with `GPT-4-turbo` for the last few months via the Zen assistant feature. The latter has increasingly been frustrating.

Over Christmas, I hacked out a Rust client for Gemini, which may be useful: [google-generative-ai-rs](https://github.com/avastmick/google-generative-ai-rs). It works for my current job (using a Vertext AI endpoint). Disclaimer: the code is pretty rough; I am under time pressure right now at work and am struggling to find time to refine and make it more robust.

Thanks.

**Comment by OmerWow** [comment]
Would love to see it!

GPT is pretty expensive, and on my Intel Mac Ollama can barely run any model.
Gemini is pretty good and has a pretty generous free tier so it'll be great to be able to use inside Zed.

**Comment by bilal-houari** [comment]
Gemini Flash has a very generous free tier, 1000+ calls per day and having 1M token to work with, i looked for an extension that allows one to bring their own on vscode but i couldnt find any. i would love to be able to use it on zed.

**Comment by notpeter** [comment]
We now explicitly support Google AI API keys in the application to support usage of Gemini 1.5 Flash and Gemini 1.5 Pro.  Checkout the newest Zed Preview and give it a whirl.

![Screenshot_20240815_145232](https://github.com/user-attachments/assets/3ad7d77f-4dc5-4ef4-ad51-02d74c70229c)
