### ISSUE TITLE
Zed won't launch/start after update

### ISSUE THREAD

**Issue by michealp-coder** [zed-industries/zed#4300]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Download either Zed Stable or Preview from https://zed.dev/releases/stable

2. Double-click on the downloaded Zed.dmg file.

3. Drag the Zed Preview app to the Application folder

I receive the following error:

`"Zed Preview" can't be opened because Apple cannot check it for malicious software.`

Doesn't matter if it's Zed 0.117.0 (Stable) or Zed 0.118.0 (Preview).

Note: Zed worked last month but when I went to go update it, it now broke.

### Environment

I'm unable to run that comment, since Zed won't launch.

Apple M1
16 GB RAM
Ventura 13.6.3

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Log size exceed max form length.

Log found below:

https://gist.githubusercontent.com/michealp-coder/01a5ac91f9194e175a1b82e746d836a0/raw/ad53f12e52786ae59ef1be92c1aedafab3367d14/gistfile1.txt

**Comment by eclecticjohny** [comment]
Receiving the same error “Zed” can’t be opened because Apple cannot check it for malicious software." dialog.

**Comment by notpeter** [comment]
We improved our signing/notarization of MacOS packages and are now notarizing both the app file and the dmg.  If you have Gatekeeper issues with a current download for MacOS please open a new issue we'll be happy to troubleshoot.
