### ISSUE TITLE
Strange TypeScript code highlighting in interface declaration

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#4305]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/community/assets/45122321/3b555de4-3e52-41d8-a4cf-3a4891e27919)

As you can see, the optional props are highlighted in an incorrect way. File with TSX syntax.

### Environment

Zed: v0.117.0 (Zed Preview)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
@widersky Are you still able to reproduce this in v0.119.19?

It appears to be fixed when I tried it out:

<img width="354" alt="Screenshot 2024-01-25 at 11 37 00 PM" src="https://github.com/zed-industries/zed/assets/1486634/2f47d406-c45c-47e6-afb2-84ea2d3636d4">

**Comment by widersky** [comment]
@maxdeviant Yes, everything looks good now, for me on 0.120.2 🔥

![image](https://github.com/zed-industries/zed/assets/45122321/a4bb6ab9-baaf-4aa1-aaf9-db1013d9c236)
