### ISSUE TITLE
Add Vim <Ctrl-r> Register Support

### ISSUE THREAD

**Issue by binc4t** [zed-industries/zed#4308]
### Check for existing issues

- [X] Completed

### Describe the feature

thanks for the great work of ZED, I really love it. Please consider implementing [Vim's Register](https://learnvim.irian.to/basics/registers), which would be a great help for people like me who uses this feature in vim everyday.

**Comment by notpeter** [comment]
Closing as I believe this was fixed by:
- https://github.com/zed-industries/zed/pull/13085

Thanks for filing the issue!
