### ISSUE TITLE
Vi mode: in normal mode, support goto next/prev function, and goto next/prev class

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#4316]
### Check for existing issues

- [X] Completed

### Describe the feature

I think it'd be awesome to support goto next/prev funciton/class.  Which is supported in neovim.

The key can be `]]`, `]m`, `[[`, `[m`
![图片](https://github.com/zed-industries/community/assets/22256154/2ce33df7-bc9c-41ac-9a1c-9b04aed4f425)

![图片](https://github.com/zed-industries/community/assets/22256154/38b95b61-c5ce-4176-bf31-dfc0131b8bdd)

**Comment by ConradIrwin** [comment]
This shipped in https://github.com/zed-industries/zed/pull/20924
