### ISSUE TITLE
Azure OpenAI Support

### ISSUE THREAD

**Issue by vivekrp** [zed-industries/zed#4321]
### Check for existing issues

- [X] Completed

### Describe the feature

Does Zed support Azure OpenAI? If not please add the support.

**Comment by sheldonhull** [comment]
Azure OpenAI has the same models just a different endpoint. Same api as OpenAI I believe. 

Just adding this context as supporting azure OpenAI is not the same supporting completely different providers like Anthropic (to my understanding 😀)

**Comment by tecandrew** [comment]
we self host our 'Assistant' OpenAI API-like LLM on a private server. Azure support and others, or just having a custom endpoint, would be hugely beneficial.

**Comment by Xtrah** [comment]
> Azure OpenAI has the same models just a different endpoint. Same api as OpenAI I believe.

This is correct, it is the exact same models.

Having an option to customize the endpoint which currently seem to be specified in `OPEN_AI_API_URL` in [crates/ai/src/providers/open_ai.rs](https://github.com/zed-industries/zed/blob/444f918e51effada7097cec8a4857bb9a21b5823/crates/ai/src/providers/open_ai.rs#L9) might be enough to support OpenAI models in Azure (which most enterprise users probably prefer).

**Comment by Xtrah** [comment]
> Azure OpenAI has the same models just a different endpoint. Same api as OpenAI I believe.

This is correct, it is the exact same models.

Having an option to customize the endpoint which currently seem to be specified in `OPEN_AI_API_URL` in [crates/ai/src/providers/open_ai.rs](https://github.com/zed-industries/zed/blob/444f918e51effada7097cec8a4857bb9a21b5823/crates/ai/src/providers/open_ai.rs#L9) and the [authentication header](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference), is enough to support OpenAI models in Azure.

Businesses that already rely on Microsoft for data processing are likely to favor Azure as it would be covered under the same contracts, potentially broadening the user base for the assistant panel significantly.

**Comment by gtn1024** [comment]
It's better to provide a config for `OPEN_AI_API_URL`

**Comment by jgrant95** [comment]
Just tried using this with azure openai, but can't seem to get it working. Looking at the recent implementation for `open_api_url`, it may because from the azure docs, we need to supply an api-version after `chat/completions` - which isn't possible with the implementation.

See the azure docs that I'm referring to here - https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions

**Comment by FabianHertwig** [comment]
I would also like to know if it is possible to configure the Azure OpenAI API and what the settings are.

**Comment by tombailey** [comment]
If anyone still wants to try Azure, I have a very hacky PR/branch for it:
https://github.com/zed-industries/zed/pull/8493/

I don't have an Azure API key to test with so please let me know if it works 🙇

**Comment by israrwz** [comment]
I had to create a proxying script running locally that allowed me to use my Azure OpenAI deployment seamlessly with Zed.

Here is the script: [https://gist.github.com/israrwz/10c10b2adae480646eb62e5b926b9898](https://gist.github.com/israrwz/10c10b2adae480646eb62e5b926b9898)

configure three variable in the script file:

```python
AZURE_API_ENDPOINT = "<YOUR_DEPLOYMENT_ENDPOINT_URL>"
                   # "https://****************.cognitiveservices.azure.com/openai/deployments/o3-mini"
AZURE_API_VERSION = "<DEPLOYMENT_API_VERSION>"
                  # "2025-01-01-preview"
AZURE_API_KEY = "<YOUR_API_KEY>"
```

start the script with:
```bash
python azure-openai-proxy.py
```

finally add the following model configuration to Zed's `settings.json` file:

```json
  "language_models": {
    "anthropic": {
      "version": "1"
    },
    "openai": {
      "version": "1",
      "api_url": "http://localhost:8000",
      "available_models": [
        {
          "api_version": "2024-12-01-preview",
          "display_name": "o3-mini",
          "name": "o3-mini",
          "max_tokens": 200000
        }
      ]
    }
  },
```

**Comment by JairajSustained** [comment]
Is this still working? @israrwz

**Comment by tomprogramuje** [comment]
don't know if anyone still fumbles, but it actually can be done, trick is to not use the standard azure openai endpoint, but the one for openai sdk (you can find it in your model deployment):

E.g. 

 ```
"language_models": {
    "openai_compatible": {
      "Azure OpenAI": {
        "api_url": "https://<your-deployment>.openai.azure.com/openai/v1/",
        "available_models": [
          {
            "name": "gpt-5",
            "display_name": null,
            "max_tokens": 200000,
            "max_output_tokens": 32000,
            "max_completion_tokens": 200000,
            "capabilities": {
              "tools": true,
              "images": false,
              "parallel_tool_calls": false,
              "prompt_cache_key": false
            }
          }
        ]
      }
     }
```

i made it all including api key via the UI that emitted the above settings but apparently it could be done directly in settings plus api key exposed as env variable as stated here: https://zed.dev/docs/ai/llm-providers#openai-api-compatible

**Comment by hlthi** [comment]
<img width="690" height="254" alt="Image" src="https://github.com/user-attachments/assets/c89eb3f2-67d6-4a37-b6cd-9f9fcf543bf4" />

Just set openai sdk from right dropdown.

Thank you @tomprogramuje 


> don't know if anyone still fumbles, but it actually can be done, trick is to not use the standard azure openai endpoint, but the one for openai sdk (you can find it in your model deployment):
> 
> E.g.
> 
> ```
> "language_models": {
>    "openai_compatible": {
>      "Azure OpenAI": {
>        "api_url": "https://<your-deployment>.openai.azure.com/openai/v1/",
>        "available_models": [
>          {
>            "name": "gpt-5",
>            "display_name": null,
>            "max_tokens": 200000,
>            "max_output_tokens": 32000,
>            "max_completion_tokens": 200000,
>            "capabilities": {
>              "tools": true,
>              "images": false,
>              "parallel_tool_calls": false,
>              "prompt_cache_key": false
>            }
>          }
>        ]
>      }
>     }
> ```
> 
> i made it all including api key via the UI that emitted the above settings but apparently it could be done directly in settings plus api key exposed as env variable as stated here: https://zed.dev/docs/ai/llm-providers#openai-api-compatible
