### ISSUE TITLE
Project Panel: Single click on a file should focus Editor when preview tabs disabled

### ISSUE THREAD

**Issue by porsager** [zed-industries/zed#4324]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When selecting a file in the sidebar, the file is shown, but there is no active cursor. 

Clicking the open tabs works as expected (there is a cursor).

I found that double clicking works, but this doesn't seem like the normal behaviour? 

### Environment

Zed: v0.113.0 (preview)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
The current behavior exists to enable quickly viewing multiple files (single click) without each one opening their own tab. This behavior matches VSCode (single click to preview, double click open file for editing).  JetBrains IDEs appear to do nothing on single click and only open on double-click.

The current behavior also enables keyboard navigation of the project panel.  You can preview the selected file with space bar, then navigate up/down and press space again to toggle open files.

I totally understand how this could be surprising and undesirable behavior for some users so I'll leave this open as an enhancement request. Thanks

**Comment by narqo** [comment]
> The current behavior exists to enable quickly viewing multiple files (single click) without each one opening their own tab. This behavior matches VSCode (single click to preview, double click open file for editing).

Shouldn't the `preview_tabs.enabled=false` setting change this behaviour?

I also find the tabs preview a confusing when tabs are hidden. That is, when the editor doesn't have tabs, the preview is less different from regular opening of a file. At least there is no visible indicators, that the file went into the "preview" mode, when I single-clicked on it from the file explorer.

**Comment by notpeter** [comment]
Yes, I would consider this a defect.  When disabling [Preview Tabs](https://zed.dev/docs/configuring-zed#preview-tabs) with:
```json
  "preview_tabs": {
    "enabled": false
  },
```

Single-clicking a filename in the project panel should focus to the editor pane.  Currently a double-click is always required to focus to the editor, even with Preview Tabs disabled.

> I also find the tabs preview a confusing when tabs are hidden. That is, when the editor doesn't have tabs, the preview is less different from regular opening of a file. At least there is no visible indicators, that the file went into the "preview" mode, when I single-clicked on it from the file explorer.

Fair. I've mentioned this in a related issue:
- https://github.com/zed-industries/zed/issues/18870
