### ISSUE TITLE
Native support eslint fix on save

### ISSUE THREAD

**Issue by korywka** [zed-industries/zed#4325]
### Check for existing issues

- [X] Completed

### Describe the feature

The issue is the half one of the resolved https://github.com/zed-industries/zed/issues/5612 that was closed only with Prettier support.

VSCode, Atom, WebStorm and so on support eslint out of the box, just with `eslint` npm package and `.eslintrc` config.
It would be awesome if Zed could do the same.
For now, Zed lints errors, but no autofix on save for simple config:

```json
{
  "theme": "Andromeda",
  "buffer_font_size": 15,
  "language_overrides": {
    "JavaScript": {
      "format_on_save": "on",
      "formatter": "auto"
    }
  }
}
```

eslint is the linter number 1 for JavaScript, so I believe this feature will not only help Zed users, but also increase usage of the editor among JS developers. Thanks 🖤

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="468" alt="283544939-dc08be1a-de71-4cb8-89df-01725bbc5002" src="https://github.com/zed-industries/community/assets/988471/965b5fc5-9049-4d34-beb7-e92b5a952488">

**Comment by r614** [comment]
+1 to exposing eslint fixes as code actions, I miss the dropdown from vscode

**Comment by korywka** [comment]
@JosephTLyons No rush, but please take a look how popular the issue is 🥹

**Comment by mrnugget** [comment]
We do have this now: https://github.com/zed-industries/zed/pull/7860

See here for how to set it up: https://github.com/zed-industries/zed/issues/4840#issuecomment-1961282033

What we don't have is what @jaydenseric asked for. @jaydenseric can you create a separate ticket for that? Because I think `eslint fix on save` is fixed by adding code actions on save. I'm going to close to issue, but if someone disagrees that this is still not fixed, let's reopen it.

**Comment by mrnugget** [comment]
Based on the comments above I'd say it's this:

```json
  "languages": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
```

You don't need to set a formatter, since that's unrelated to eslint. What this does is to run the code actions of the primary language servers when you format.

Does that make sense/work? (I'll try to reproduce shortly and can then document)

**Comment by korywka** [comment]
https://github.com/zed-industries/zed/assets/988471/9d254ee1-c031-4f57-9e89-6261edf37158

nope, errors are not fixed, looks like the file is formatted with other (default?) formatter, not `eslint`.

**Comment by mrnugget** [comment]
Ah, got it. I think the issue here is that `eslint` is not the primary language server. Reopening!

**Comment by eidriahn** [comment]
@mrnugget just letting you know that for me everything works

**Comment by korywka** [comment]
@eidriahn autofix for eslint? can you share please `settings.json`?

**Comment by throrin19** [comment]
Same problem Here, I try all documented here but none works : 

This is my settings.json : 

```json
{
  "formatter": "language_server",
  "languages": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "TypeScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
}
```

But when I save typescript or javascript files, I have a default formatter action, not my eslint config action

**Comment by mrnugget** [comment]
I've got a first fix for eslint-on-format here: https://github.com/zed-industries/zed/pull/8496

@jaydenseric I'll look into your case next, so it's possible to specify the rules that are used when running eslint-fix-on-format. I'm tracking that here: https://github.com/zed-industries/zed/issues/8533

**Comment by mrnugget** [comment]
Here's the 2nd part that allows you to specify which rules to use when using `code_actions_on_format`: https://github.com/zed-industries/zed/pull/8537

Next step would be that we upgrade to a newer version of `vscode-eslint`.

**Comment by sanketnaik99** [comment]
@mrnugget It seems like the ESLint fix on save works but is there a way to disable prettier formatting so that the ESLint formatting is saved?

**Comment by hungify2022** [comment]
@sanketnaik99 It looks like some rules conflict with Prettier
You need to turn off rules that conflict with Prettier

**Comment by mrnugget** [comment]
> @mrnugget It seems like the ESLint fix on save works but is there a way to disable prettier formatting so that the ESLint formatting is saved?

Yeah, you can change format on save and the formatter: https://zed.dev/docs/configuring-zed#format-on-save

So, for example, you can essentially turn `prettier` off by saying you want the primary language server (`typescript-language-server`) to do formatting, which is a no-op

```json
    "JavaScript": {
      "formatter": "language_server",
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
```

Or you use https://github.com/prettier/eslint-config-prettier to configure eslint so it doesn't clash with prettier.

**Comment by hungify2022** [comment]
@mrnugget 
Thanks
Folder-specific settings with these configs would resolve that.

**Comment by sanketnaik99** [comment]
> > @mrnugget It seems like the ESLint fix on save works but is there a way to disable prettier formatting so that the ESLint formatting is saved?
> 
> Yeah, you can change format on save and the formatter: https://zed.dev/docs/configuring-zed#format-on-save
> 
> So, for example, you can essentially turn `prettier` off by saying you want the primary language server (`typescript-language-server`) to do formatting, which is a no-op
> 
> ```json
>     "JavaScript": {
>       "formatter": "language_server",
>       "code_actions_on_format": {
>         "source.fixAll.eslint": true
>       }
>     },
> ```
> 
> Or you use https://github.com/prettier/eslint-config-prettier to configure eslint so it doesn't clash with prettier.

Here's my Zed config! When I hit save, it formats the document but misses some of the ESLint rules that I have configured. Can you help me figure out what I'm missing here? I've attached a video that shows the formatting issues.

```json
{
    "tab_size": 4,
    "language_overrides": {
        "TSX": {
            "formatter": "language_server",
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        },
        "TypeScript": {
            "formatter": "language_server",
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        }
    }
}
```

https://github.com/zed-industries/zed/assets/25388014/3c110ab5-5701-42fc-8b93-ae74bea08be8

**Comment by mrnugget** [comment]
> Can you help me figure out what I'm missing here?

Let's find out:

1. Does ESLint fix on format work at all? Meaning: does it fix other things?
2. Which rules _does_ it miss? Are those rules maybe not auto-fixable?

**Comment by korywka** [comment]
@sanketnaik99 Please make sure you use the latest build, but not the stable one: https://github.com/zed-industries/zed/releases (assets)

**Comment by sanketnaik99** [comment]
@mrnugget Yeah it seems like the format works and it fixes other things such as no trailing commas, one prop per line, etc.

It seems like the only thing that doesn't work is the spacing rule. I have confirmed that it works in VSCode and it was also working when I defined a custom command for format on save as shown below

```json
"format_on_save": {
        "external": {
          "command": "eslint_d",
          "arguments": [
            "--stdin",
            "--fix",
            "--fix-to-stdout",
            "--stdin-filename",
            "{buffer_path}"
          ]
        }
      }
```

**Comment by mrnugget** [comment]
@sanketnaik99 interesting! can you create a sample project to reproduce? example file and eslint config etc.?

**Comment by mrnugget** [comment]
@sanketnaik99 another thing: can you capture the logs of what happens when you hit save? Like this:

https://github.com/zed-industries/zed/assets/1185253/1b61a937-ddf3-4ca0-b93a-b724bec1d3cb

**Comment by throrin19** [comment]
In my case the option `"formatter": "language_server"` is ignored, zed apply eslint fix + prettier. I don't want to apply prettier but only eslint

**Comment by korywka** [comment]
Have the same issue. Maybe this issue/PR will fix it: https://github.com/zed-industries/zed/issues/8823

**Comment by mrnugget** [comment]
> In my case the option `"formatter": "language_server"` is ignored, zed apply eslint fix + prettier. I don't want to apply prettier but only eslint

Yeah. I think that's still an open issue. Do you want to create a ticket for it? We need to figure out a non-awkward configuration schema so we can say "run code actions when formatting, but not the formatter."

**Comment by mrnugget** [comment]
Also, @throrin19 can you share your config here? The `languages` part at least. When `formatter: language_server` is configured, it shouldn't use `prettier`, I think:

https://github.com/zed-industries/zed/blob/eb2c60f0fdb5780aff0abb3839f69d0e4f71ddce/crates/project/src/project.rs#L4430-L4446

**Comment by korywka** [comment]
https://github.com/zed-industries/zed/assets/988471/9735f956-b19f-4dc2-ae85-34d0d7a00a4b

I have the same issue: if you edit something and save - eslint is fixed. If just press save next time - prettier is fixed. But my config is `language_server`.

**Comment by korywka** [comment]
It is a bit confusing that typescript is responsible for formatting and not obvious according to which rules typescript do format. Does he use prettier config to format?

**Comment by korywka** [comment]
Or these settings are applied after eslint:

https://github.com/typescript-language-server/typescript-language-server/blob/b224b878652438bcdd639137a6b1d1a6630129e4/docs/configuration.md?plain=1#L137-L163

**Comment by mrnugget** [comment]
Yeah, I think that's it. 

No, order is not random. It's: code actions first, then formatter (language server, prettier, external command, ...).

Don't you agree that the fix for your problem is to turn off the language server formatter and just run ESLint?

**Comment by korywka** [comment]
For typescript / eslint - for sure. But I don't know how it matches for other languages. So strange to have 3rd formatter on TS LSP side, while we have prettier and eslint for these needs...

**Comment by throrin19** [comment]
@mrnugget sorry for my response time.

This is my actual config : 

```json
{
        "languages": {
        "JavaScript": {
            "formatter": "language_server",
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        },
        "TypeScript": {
            "formatter": "language_server",
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        }
    },
    "formatter": "language_server"
}
```

I saw sed made eslint format and just after it launch prettier format. It's not possible to deactivate prettier ? In many projects we don't want use it but only eslint or no formatter at all

**Comment by mrnugget** [comment]
@throrin19 can you confirm that it's actually _prettier_ doing the formatting after ESLint? Because I'm 99.99% sure it's `typescript-language-server`.

In general, yes: the problem is that you just want the code actions to format.

**Comment by mrnugget** [comment]
I created a ticket here: https://github.com/zed-industries/zed/issues/8992

**Comment by mrnugget** [comment]
Merged today: https://github.com/zed-industries/zed/pull/10121 Will go out with the next preview release today, 0.130.x.

**Comment by throrin19** [comment]
> @throrin19 can you confirm that it's actually _prettier_ doing the formatting after ESLint? Because I'm 99.99% sure it's `typescript-language-server`.
> 
> In general, yes: the problem is that you just want the code actions to format.

Actually it seems to be sometimes prettier and sometimes typescript-language-server but I don't understand why this format my files, normally it is made by prettier or eslint config :/

**Comment by mrnugget** [comment]
> Actually it seems to be sometimes prettier and sometimes typescript-language-server but I don't understand why this format my files, normally it is made by prettier or eslint config :/

That's our "auto" logic: when no formatter is explicitly configured, we first try to use prettier, and if that fails we try to use the primary language server connected to a buffer. It sounds like sometimes prettier is used because it works, and sometimes we fall back to the server.

**Comment by vteivans** [comment]
Is it possible to assign this functionality to a keyboard shortcut?

**Comment by mrnugget** [comment]
> Is it possible to assign this functionality to a keyboard shortcut?

You mean execute only the code actions?

**Comment by nicholaswmin** [comment]
cant believe that a code editor attempts every magic trick there is yet 3 years later suggest a comically haphazard patch up to do the one thing it's supposed to do:

allow you to write code in your own style. in JS of all languages.

**Comment by Pinkcolorrr** [comment]
Guys am I missing something? I can't disable "prettier" and "lang service" as formatters and run only "eslint --fix" on save. Why changes from [#1012](https://github.com/zed-industries/zed/pull/10121) are not allowed now?

**Comment by Pinkcolorrr** [comment]
for those who are still searching I finally figured out how can I disable default formatting

Here is my config

```
"TypeScript": {
  "formatter": [],
  "format_on_save": "on",
  "code_actions_on_format": {
    "source.fixAll.eslint": true
  }
},
```
