### ISSUE TITLE
Freeze when trying to save settings.json file after opening a .tsx file

### ISSUE THREAD

**Issue by samu** [zed-industries/zed#4326]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After opening a .tsx file, when i try to save zed's settings.json file, zed crashes.

Steps to reproduce:

1. open a .tsx file, then close it
2. open settings.json, then try to save

I do not see any logs after save.

### Environment

Zed: v0.113.0 (stable)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
@Liam-Breen is this still an issue with the newest versions of Zed? We've changed quite a few things when saving settings.

**Comment by mrnugget** [comment]
Sweet! Then let's close this and if it does happen again, let's reopen :)
