### ISSUE TITLE
Enhance Command Pallet Search With Substring Behavior

### ISSUE THREAD

**Issue by martinbliss** [zed-industries/zed#4328]
### Check for existing issues

- [X] Completed

### Describe the feature

As a full stack engineer, I need the Zed command pallet to search each "word" entered separately and to include a result if the word is found in the middle or end of the relative file path of the file, not just the beginning. This would enable users to quickly navigate complex codebases where file names or folder names are repeated per convention. See below for an example.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/community/assets/11949431/a8637a65-b51c-4a2c-b545-69b8e15b92b5)
Above is an example of using the command pallet in VSCode to search for a `service.go` file that happens to be nested in a folder that contains the word `invoice`. Note how using the words `invoice` and `service` cause the most relevant hit to surface to the top?

![image](https://github.com/zed-industries/community/assets/11949431/55b8ac87-775d-4c4c-b1c3-c1911cbb9362)
Example of using the same process in Zed on the same codebase.

![image](https://github.com/zed-industries/community/assets/11949431/c5c017c8-b804-43a4-9310-f3e221f1a415)
Example of searching just for any `service.go` files and having to sift through the list to find the correct one, because Zed appears to only pull matches which _**begin with**_ the search criteria. Note how the most relevant result, `cmd/invoicesLambda/service.go` isn't even in the top 6 results (it is somewhere around 10 in the list.)

**Comment by notpeter** [comment]
Hi @martinbliss, I believe sometime in the intervening months search has improved and added the feature you have requested.

<img width="548" alt="Screenshot 2024-06-24 at 15 07 41" src="https://github.com/zed-industries/zed/assets/145113/cb9b0a27-2a23-4e4d-aed1-c711c6ce3d71">

Can you confirm whether this meets your needs or whether there's additional functionality you're looking for?  Thanks

**Comment by JosephTLyons** [comment]
Going to close this issue out. If the current behavior mentioned by @notpeter doesn't include the functionality you are looking for, feel free to open a new issue.
