### ISSUE TITLE
Scrollbar in file explorer (left dock)

### ISSUE THREAD

**Issue by sporto** [zed-industries/zed#4349]
### Check for existing issues

- [X] Completed

### Describe the feature

The file explorer doesn't have a scrollbar. It seems that the only way to scroll is by using the mouse wheel.
This is very time consuming when you have hundreds of files. I would appreciate a way to quickly go to the top and bottom, which a scrollbar provides.

**Comment by shahverd** [comment]
Is this still an issue? 
![Screenshot from 2024-06-25 18-21-37](https://github.com/zed-industries/zed/assets/1610694/273511ac-516a-48f6-8e0b-d24cb24ce283)

**Comment by shahverd** [comment]
It's okay with the latest source code and not okay on the latest released package (on Linux)

**Comment by JosephTLyons** [comment]
Let's close this issue out, as [it is now available for macOS](https://zed.dev/releases/preview/0.142.0), and open a new Linux specific issue.
