### ISSUE TITLE
Be able to split terminal panel

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#4351]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great if (like in VSCode) we could divide terminal panel in several pane.
Currently we have to use tabs but we can’t display tabs in several splitted pane in terminal panel.

**Comment by jackTabsCode** [comment]
What kind of work would need to be done to move this forward @JosephTLyons?

**Comment by Tom-Boscher** [comment]
I'm interested to help too!

**Comment by rcssdy** [comment]
Interested to see this!

**Comment by rgbkrk** [comment]
The place to go after this is in `clone_on_split` of the `impl Item for TerminalView` of `crates/terminal_view/src/terminal_view.rs`. Based on the current comment it appears that there's more work to be done to make it keep the current working directory:

```
    fn clone_on_split(
        &self,
        _workspace_id: WorkspaceId,
        _cx: &mut ViewContext<Self>,
    ) -> Option<View<Self>> {
        //From what I can tell, there's no  way to tell the current working
        //Directory of the terminal from outside the shell. There might be
        //solutions to this, but they are non-trivial and require more IPC

        // Some(TerminalContainer::new(
        //     Err(anyhow::anyhow!("failed to instantiate terminal")),
        //     workspace_id,
        //     cx,
        // ))

        // TODO
        None
    }

```

As an example implementation you can look at https://github.com/zed-industries/zed/pull/9425.

**Comment by mikayla-maki** [comment]
FYI for anyone looking to implement this, that comment is out of date. the `Model<Terminal>` has a `get_cwd()` method on it that can be used for this purpose.

**Comment by MrBns** [comment]
So is there any solution ?  need help .. please.

**Comment by trev-gulls** [comment]
I still can't figure out how to split the terminal pane so I can see two terminals at once. Is this feature on the project roadmap? Do we know when this feature may be available?

**Comment by iambudi** [comment]
> I still can't figure out how to split the terminal pane so I can see two terminals at once. Is this feature on the project roadmap? Do we know when this feature may be available?

Can you drag the second terminal tab and position it side by side with the first terminal?

**Comment by iambudi** [comment]
How can I prevent Zed from opening code files in the terminal tab when it’s docked vertically? I often forget to switch focus, and new files end up in the terminal pane.

**Comment by AlbertMarashi** [comment]
Related UX proposal to improve pane management:
- https://github.com/zed-industries/zed/issues/17678
