### ISSUE TITLE
VIM issue - v + e

### ISSUE THREAD

**Issue by decomoraes** [zed-industries/zed#4354]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello, I notice that I'm having an issue with the vim mode, for example, I have this code:
```
string(character)
```

I put the cursor in the first letter of character, I press v + e, to select the word, but it selects also the `)` character.

### Environment

zsh: command not found: copy

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Is this still an issue? When I try `string(character)` with cursor on `s` and hit `v e` I get `<string>(character)`, with `<>` being the selection. Seems to be the same thing as in Vim.

**Comment by andmarek** [comment]
> Is this still an issue? When I try `string(character)` with cursor on `s` and hit `v e` I get `<string>(character)`, with `<>` being the selection. Seems to be the same thing as in Vim.

Seems fine for me now as me as well.

**Comment by mrnugget** [comment]
Alright, closing for now! We can always reopen :)

**Comment by decomoraes** [comment]
Hello, it's not resolved, 

For example

```
const letter = "a"

something(letter)
```

Put your cursor on `l`, then hit `v e`

**Comment by andmarek** [comment]
> Hello, it's not resolved,
> 
> For example
> 
> ```
> const letter = "a"
> 
> something(letter)
> ```
> 
> Put your cursor on `l`, then hit `v e`

Ah I see.  I suppose I attempted to re-produce your issue incorrectly the first time.  I initially added a semi-colon, which does indeed work correctly:

<img width="263" alt="Screenshot 2024-01-30 at 9 51 49 AM" src="https://github.com/zed-industries/zed/assets/19277395/a31a9878-418a-4b35-b577-49ce56f89ef3">

But when I omit the semi-colon after the function invocation:
<img width="292" alt="Screenshot 2024-01-30 at 9 52 09 AM" src="https://github.com/zed-industries/zed/assets/19277395/ad56dc9e-547b-4959-99b5-4930f8156cc5">

The issue that you were facing still occurs.

**Comment by decomoraes** [comment]
Well observed, thank you for your attention. I'm really looking forward to contributing to Zed through programming.

**Comment by decomoraes** [comment]
Hello @mrnugget, can you reopen this issue?
