### ISSUE TITLE
Tab bar doesn't scroll to active tab if filled

### ISSUE THREAD

**Issue by porsager** [zed-industries/zed#4356]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Having the tab bar filled and then opening a new tab (open file / search etc) doesn't scroll to the active tab.

Also closing a tab doesn't scroll to the newly active tab.

### Environment

Zed: v0.112.0 (preview)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I can no longer reproduce this in:

```txt
Zed: v0.155.0 (Zed Nightly 6b56530a4ab0b45d072ce5fe2c19e10e8cd3f58b)
OS: macOS 14.4.0
Memory: 64 GiB
Architecture: aarch64
```

I'm going to close this issue out as completed!
