### ISSUE TITLE
Enable gpt-3.5 Turbo-1106 & other new models

### ISSUE THREAD

**Issue by 8times4** [zed-industries/zed#4369]
### Check for existing issues

- [X] Completed

### Describe the feature

It'd be nice if other GPT models were enabled aside from `0613` for `3.5` and `4`.

Thank you!
-8x4

**Comment by Moshyfawn** [comment]
Correct me if I'm wrong, but it seems that these are the GPT models currently available in Zed:

- `gpt-3.5-turbo-0613`
- gpt-4-0613
- gpt-4-1106-preview

Do these satisfy this feature request?

**Comment by 8times4** [comment]
Yup, thank you!
