### ISSUE TITLE
If you open the Zed OpenAI panel for the first time, then make your window smaller than half the screen width, then quit the app, it will keep crashing upon reopen

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#4371]
### Discussed in https://github.com/zed-industries/community/discussions/2234

<div type='discussions-op-text'>

<sup>Originally posted by **winstonpurnomo** November  6, 2023</sup>
Don't do that.</div>

**Comment by ConradIrwin** [comment]
Very likely fixed by the gpui2 rewrite, so closing; but please do let me know if you can still reproduce
