### ISSUE TITLE
"terminal panel: toggle focus" hotkey not working on Swedish layout keyboard.

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#4378]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the hotkey is ^ + ` according to the command palette, but it doesn't work

### Environment

Zed: v0.110.2 (stable)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bobmaerten** [comment]
Does not seem to work on French layout either.
