### ISSUE TITLE
Find all references progress

### ISSUE THREAD

**Issue by dgrr** [zed-industries/zed#4380]
### Check for existing issues

- [X] Completed

### Describe the feature

A progress bar or a progress log for when `Find All References` is triggered. Currently there's no progress bar when looking for references. Sometimes I can take minutes for it to find the references. A progress bar or a progress log (like when a project is being loaded and rust-analyzer runs) would be nice.

### If applicable, add mockups / screenshots to help present your vision of the feature

Log line like the following on the left down side with the reference we are searching for + some progress bar.

<img width="375" alt="image" src="https://github.com/zed-industries/community/assets/10146748/eea51557-6e41-485b-95fe-ba64e8f6669e">

**Comment by danielzsh** [comment]
I would like to implement this but am not quite sure how to go about it...I noticed the `on_lsp_work_start` method for `Project` which seemed promising, but it's private and I'm not sure how to properly interact with it. Any pointers? 😅
