### ISSUE TITLE
Format and lint untitled / unsaved buffers

### ISSUE THREAD

**Issue by lindit** [zed-industries/zed#4386]
### Check for existing issues

- [X] Completed

### Describe the feature

Usually I only use zed for quick prototyping code snippets or copy & pasting things around. 
It's really annoying that I have to save the file somewhere and give it a name just to format the code and lint it. 

So my feature request is pretty simple:
Open a new file -> select a language -> paste code.
Should be able to lint and format

**Comment by notpeter** [comment]
I think we've made some improvements here.
There are now default keyboard shortcuts for the following:

| shortcut    | action                      | command palette           |
| ----------- | --------------------------- | ------------------------- |
| cmd+k, m    | `language_selector::Toggle` | language selector: toggle |
| cmd+shift+i | `editor::Format`            | editor: format            |

Which means that entirely using the keyboard you can create a new document, paste something in, toggle the language and format. It's a bit of a sequence but... `cmd+n, cmd+v, cmd+k, m, cmd+shift+i` should work.

You can also map additional shortcuts for those in your `keymap.json` too:

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-alt-ctrl-l": "language_selector::Toggle"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "alt-shift-f": "editor::Format",
    }
  }  
]
```

**Comment by krstp** [comment]
So the drill you described somewhat works, however, one first needs to save the `json` file. Without saving the formatting will not work :(

**Comment by notpeter** [comment]
I thought that was working, but it's not, so I reopened. My apologies.

**Comment by krstp** [comment]
I thought I have replied under this thread. It does work, one of you other comments under https://github.com/zed-industries/zed/issues/13562#issuecomment-2193877544 referring to settings attribute name changes resolves it. Thanks.

**Comment by bobir01** [comment]
@krstp hello, I still could not find exact answer how to format(pretty) json ;(

do you have any guideline on how to achieve this ?

**Comment by notpeter** [comment]
You should be able to use "Format Document" from the command palette (cmd-shift-p) if you have a language selected in the status bar Language Selector (other than Plain Text, like JSON).

**Comment by krstp** [comment]
@bobir01 Yeah, it is not ideal. You need to really match JSON format otherwise it does flake out. For this reason I still go back to Sublime for JSON pretties ;)

**Comment by krstp** [comment]
One thing that would help is the JSON formatted in ZED to report code error to the user, atm formatter will just flake out leaving user in the dark what might be wrong with provided snippet

**Comment by bobir01** [comment]
> @bobir01 Yeah, it is not ideal. You need to really match JSON format otherwise it does flake out. For this reason I still go back to Sublime for JSON pretties ;) 

@krstp oh yeah seems i should return back too, we'll back to zed when it is stable)

**Comment by krstp** [comment]
Well, ZED is very stable and I see no reason to revert from using it. For the sake formatting one can for now save the file. Standing strong with ZED :)

**Comment by Edweis** [comment]
Resurrecting this one, doing `editor: Format` still does not format an unsaved JSON. I have an ESLint that is formatting saved JSON properly. I don't have a specific config to format unsaved JSON.

What should I do? For now I have to leave Zed every time I want to format a JSON.

**Comment by krstp** [comment]
@Edweis indeed, it is a little bit wonky, however, two points needs to be said:
- what I do is to save it as dummy `.json` file and formatting works.
- however... your JSON needs to be a properly structured JSON, otherwise it will not work :(
- ... and yes, it would be great to have a feature that would point to erroneous part of the JSON if it is not correct
    -  side note: Sublime is doing a bit something along those lines by pointing what is wrong - not always works, but overall - imho - much easier to work with JSONs there whenever I get stuck

I also agree on the front that it is not the most user friendly experience atm to format `.json` in ZED. A simple `PrettyJSON` command-panel option would be nice to have.

**Comment by metabacalhau** [comment]
Why is this issue closed? Formatting of well-structured, but unsaved JSON files still doesn't work in Zed.
