### ISSUE TITLE
Configurable 'Vim' clipboard interaction

### ISSUE THREAD

**Issue by khalil-omer** [zed-industries/zed#4390]
### Check for existing issues

- [X] Completed

### Describe the feature

In Vim mode, pretty much every visual mode delete operation (`d`, `s`, `c`) copies the selection to the system keyboard. Most Vim users do not want all those operations to also have 'cut' behavior, so I think this should be configurable. It is quite annoying if you have something already copied and then go to delete something. (You can overwrite your selection with clipboard contents with `p` but often a copy - delete - paste workflow is not so linear.)

**Maybe in a future release there could be a `"vim"` object in settings, not just the `"vim_mode"` bool.**

**Comment by mmkaram** [comment]
Vim has a separate clipboard than the system's. Honestly, I've found that this works best (because of all those cuts that happen when you use a command like `dd ` for example. In some IDE's though, when in insert mode you can use `ctrl+c/ctrl+v` to copy/paste from the system's clipboard. 

I feel like that approach offers the best of both worlds, so I'll try and implement it on my build.

**Comment by ConradIrwin** [comment]
@mmkaram Thanks for taking the leadership here! I'd love to work together on this and talk through the approach, feel free to book time here: https://calendly.com/conradirwin/pairing.

**Comment by sixhobbits** [comment]
yes please, started using Zed recently and this is the only downside for me so far. When I use vim in iTerm2 it keeps a completely separate clipboard from system, which is much nicer. I have both the issues already mentioned with the current system

- I use Alfred for clipboard history and this gets completely filled with stuff I don't want there when using Zed
- I often end up doing a Cmd+V expecting to paste something I copied in a different app only to have my vim register appear instead

Would love an option to allow Zed to keep all vim clipboard operations contained within vim buffers and leave the system clipboard alone

**Comment by JosephTLyons** [comment]
This is now included in [v0.125.0-pre](https://zed.dev/releases/preview/0.125.0).
