### ISSUE TITLE
Request for tighter vertical line spacing (or introduction of top/bottom padding)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4391]
### Check for existing issues

- [X] Completed

### Describe the feature

It is much appreciated ZED team introduced `buffer_line_height` however it would be desired we we could go below `1` values, such as:

```
  "buffer_line_height": {
    "custom": 0.9
  },
```
or perfectly to have an option such as:
```
    "line_padding_bottom": -2,
    "line_padding_top": -2,
```
This way I would be able to accomplish desired look as in attached screenshot.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot 2023-11-01 at 12 26 12 PM](https://github.com/zed-industries/community/assets/4711498/1d2d681b-1882-4cab-a2a4-59b81a453921)

**Comment by jadijadi** [comment]
I was testing this. It seems it is possible to set the values lower than 1; although there is a check in the code. It seems its being bypassed somewhere. Can you please retry?

```
  "buffer_line_height": {
    "custom": 0.7
  },
```

works for me.

**Comment by krstp** [comment]
Awesome! I've just tested. Works like a charm! Thanks all!
