### ISSUE TITLE
autocomplete for rust dont work 

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#4394]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

when i open zed and i start typing,the intellisense window dont shows up! i dont know why 

### Environment

Zed: v0.109.3 (stable)
OS: macOS 13.5.2
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Standaa** [comment]
> @Standaa, I know its not what you want for you workflow, but does the Rust language server at least work for you if you open the rust projects directly as the root directory?

Will check and report this weekend
