### ISSUE TITLE
Open source checklist 📝

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#4395]
- [x] Port Zed over to GPUI2 (see replies below for screenshot updates)
- [x] Promote Zed Nightly to Zed Preview (read about it [here](https://zed.dev/blog/gpui-2-on-preview))
- [X] Extended preview period (download a copy [here](https://zed.dev/releases/preview))
- [x] Channels shipped to Zed Preview (read about it [here](https://zed.dev/blog/channels))
- [x] Code documentation
- [X] CONTRIBUTING.md guide
- [x] Promote Zed Preview to Zed Stable
- [x] Potential blog posts

*This list is a work in progress. Items may be added or removed over time.*

**Comment by trevyn** [comment]
Congratulations on the open source launch. A piece of feedback: GPL is a rough license, and a CLA is a no-go. I won't be even able to investigate the feasibility of building on top of Zed.
