### ISSUE TITLE
"preferred_line_length is in vain 

### ISSUE THREAD

**Issue by zdcin** [zed-industries/zed#4397]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when i reopen a txt file， preferred_line_length is in vain

### Environment

Zed: v0.109.3 (stable)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Im going to close this issue out, as there aren't enough details to understand the problem. Feel free to open a new issue, with some more details, if you are still experiencing an issue.
