### ISSUE TITLE
[vim mode] `Enter` does not always execute current quickfix selection

### ISSUE THREAD

**Issue by aesterline** [zed-industries/zed#4399]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* In Vim mode, find an error in the code and press `g .`. This will pop up the quick fix list. 
* Choose one of the items using the arrow keys and hit enter.

Sometimes, this will execute the quick fix that is selected. Enter will often close the quick fix list and move the cursor in the main editing window to the next line without executing the quick fix selected.

If the mouse is used to select the quick fix, it always works.

### Environment

Zed: v0.109.3 (stable)
OS: macOS 14.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2023-10-28 at 07 33 26](https://github.com/zed-industries/community/assets/6849/c829fe24-02a8-426d-920c-d98e83e08184)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
We changed the way that keyboard handling works significantly in the GPUI rebuild earlier this year, and I know I was also experiencing this before, but now I am not. Please let me know if you can still reproduce this, and I will reopen.
