### ISSUE TITLE
Autocomplete not showing best options first

### ISSUE THREAD

**Issue by Programatic** [zed-industries/zed#4400]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using autocomplete with tsx, for some reason the very obvious choices are not showing up first. For example. in the below screenshot backgroundColor is the first option, even though color is the obvious best choice. Now shown in the screenshot, is that color is way down the list, which makes me believe that color is not an option (when it definitely is).

![image](https://github.com/zed-industries/community/assets/41210901/af59854d-37d4-4826-b067-246a4a8c26c5)

### Environment

Zed: v0.109.1 (stable)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
I'm going to close this issue in favor of the more general:

- https://github.com/zed-industries/zed/issues/12698

Additionally beyond exact match first, we could probably come up with a better sorting when there isn't an exact match too.

- https://github.com/zed-industries/zed/issues/4327


Please 👍 vote on those to increase visibility and subscribe to track their progress.

Thanks for reporting @Programatic!
