### ISSUE TITLE
Tailwind CSS within Vue template

### ISSUE THREAD

**Issue by tomhaerter** [zed-industries/zed#4403]
### Check for existing issues

- [X] Completed

### Describe the feature

Add Tailwind CSS class completion inside Vue templates. Right now there seems to be no support.

### If applicable, add mockups / screenshots to help present your vision of the feature

Vue vs HTML

<img width="400" alt="image" src="https://github.com/zed-industries/community/assets/16882922/68f028ba-0196-4874-9bcd-cd6f1c4ecb15">

<img width="400" alt="image" src="https://github.com/zed-industries/community/assets/16882922/50381d59-e5c4-49ab-8b50-ac5e3f3842bb">

**Comment by mulhoon** [comment]
It would also be nice for completions to work within the style tag in vue templates too. Any news on this? Thanks

```css
<style scoped>
.large {
    @apply px-8 rounded-lg;
}
</style>
```
