### ISSUE TITLE
Vim - command in/around pair selector (' " < ` etc) doesn't work if cursor is on first of pair

### ISSUE THREAD

**Issue by caliguIa** [zed-industries/zed#4407]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For example, if you have the following text: `const foo = "bar"`
If your cursor is on the first `"` (after the `=` and before the `b`), and you run any command of the following type; `ci"` (change inside `"`), `va"` (select around `"`), `di"` (delete inside `"`) etc. the command will not work.

If your cursor is on any of the following characters, including the last `"` the command works as expected.

To clarify this is not just broken on text wrapped in `"` but in any wrapping symbol eg `" ' < ( { [` etc.

forgive me if this is a duplicate I searched for anything I thought relevant in the issues and could not see anything relating to this.

Also worth noting I have only tried this in a .tsx Typescript React file, not any other language, so maybe an issue with treesitter/some language server issue?

### Environment

Zed: v0.108.2 (stable)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/30220663/66f38480-b6e4-4b10-8a06-d90f1cc3ca0f

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
I'm closing this because I'm pretty sure it's fixed.
