### ISSUE TITLE
Comments should be less visible

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#4410]
### Check for existing issues

- [X] Completed

### Describe the feature

In most of available themes here the comments are too "insistent". Only in the `One Dark' theme they look good in my opinion, because they are slightly dimmed and do not catch the eye so much.

**Comment by ojkelly** [comment]
Custom themes and overrides landed in preview. I'm using the following in `settings.json` and can finally use `Ayu` :D

```
  "experimental.theme_overrides": {
    "syntax": {
      "comment": {
        "color": "#55555555"
      },
      "comment.doc": {
        "color": "#66666666"
      }
    },
    "editor.invisible": "#55555555"
  }
```

It's not the specific colours, but it's a good enough patch for now.
