### ISSUE TITLE
Git `COMMIT_EDITMSG` support

### ISSUE THREAD

**Issue by caius** [zed-industries/zed#4416]
### Check for existing issues

- [X] Completed

### Language

Git

### Misc notes

It's a custom preamble, combined with diff below comments (for `git commit -v`). Neovim has it implemented at: https://github.com/neovim/neovim/blob/master/runtime/syntax/gitcommit.vim

Would be really useful for reviewing diffs before writing the commit message, using Zed as the `GIT_EDITOR`.

**Comment by hferreiro** [comment]
This seems to be a duplicate of https://github.com/zed-industries/zed/issues/7048.

**Comment by caius** [comment]
Oh neat, missed someone had fixed this. Closed by #7147 then
