### ISSUE TITLE
The golang go mod zed editor dependency package check is not updated

### ISSUE THREAD

**Issue by jorahbi** [zed-industries/zed#4423]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The golang go mod zed editor dependency package check that it has not been updated, in fact it has already been updated. Turn it off and back on to display no red underline normally

### Environment

golang 1.20
macos 12.7

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by imraan-go** [comment]
I am unable to use this one my work project because of this issue. Is there any timeline when this will be fixed?
