### ISSUE TITLE
Add the possibility to use offline models (maybe via ollama)

### ISSUE THREAD

**Issue by gawlk** [zed-industries/zed#4424]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

Having the possibility to use other models for example llama (most likely via ollama) would be really amazing instead of being forced to use the proprietary and unethical ChatGPT.

Here's a link to their API docs: https://github.com/jmorganca/ollama/blob/main/docs/api.md

Since an API is also used for ChatGPT it shouldn't be too much work

**Comment by willtejeda** [comment]
This would be awesome. 

this project seems like it could serve as inspiration for the feature 

[https://github.com/continuedev/continue](url)

**Comment by tjohnman** [comment]
It should be easy to add support to any service that provides an OpenAI-compatible API, such as Perplexity, or LiteLLM for local models.

**Comment by octoth0rpe** [comment]
ollama is now OpenAI-compatible as well: https://ollama.ai/blog/openai-compatibility

**Comment by shaqq** [comment]
a quantized version of CodeLlama would work well locally on macs:

https://huggingface.co/TheBloke/CodeLlama-34B-GGUF

ollama has a way of interacting with a [quantized CodeLlama](https://ollama.com/library/codellama), but up to the Zed team whether they'd rather use ollama or run llama.cpp within Zed (ollama runs llama.cpp under the hood)

IMO this should be more generic than "offline vs. online", and more about giving users choice in which CoPilot model they'd like to use. There's a balance for sure!

**Comment by Belluxx** [comment]
A low effort approach to include this feature is allowing the configuration of a custom proxy for copilot.
It is already possible today in VSCode's Copilot extension using this config:
```json
"github.copilot.advanced": {
    "debug.testOverrideProxyUrl": "http://localhost:5001",
    "debug.overrideProxyUrl": "http://localhost:5001"
}
```
It would be really cool to have this tweak available in Zed too

**Comment by rcgtnick** [comment]
Thanks for the config, @sumanmichael .

I can get it to hit my API and it's passing the API key I entered in the GUI. However, I entered the wrong API key and now I can't figure out how to change it! I tried deleting `~/.config/zed`, but when I launched zed again it clearly remembered some things, including my API key.

Is there a way to change your OpenAI API key in zed?

**Comment by Belluxx** [comment]
@sumanmichael Thank you for the tip. Can you confirm that this only works for "Assistant Panel" (chat) and "Inline Assist"?
I tried to use it for copilot (theoretically supported since copilot uses OpenAI-APIs) but with no success because i don't have a Microsoft/Copilot account.

Is there a way to bypass Zed login requirement to use Copilot?

**Comment by taylorgoolsby** [comment]
Can this also be made to work with any local server running an API similar to OpenAI's API? Specifically, I'm interested in using LM Studio.

**Comment by JayGhiya** [comment]
just integrate continue.dev please this will exponentially increase adoption as continue dev solves all of llm worries and works with all possible providers both local and cloud

**Comment by rcgtnick** [comment]
> Can this also be made to work with any local server running an API similar to OpenAI's API? Specifically, I'm interested in using LM Studio.

Same here, I'm using LiteLLM which presents an OpenAI-compatible API, and integrates with a bunch of model loaders on the back end (ollama, tgi, etc.). Would be nice to be able to just set a URL and token and have it use my server.

**Comment by rcgtnick** [comment]
> just integrate continue.dev please this will exponentially increase adoption as continue dev solves all of llm worries and works with all possible providers both local and cloud

Yeah, Continue is very flexible. This is what the Continue config looks like:

```json
  "models": [
    {
      "title": "mixtral",
      "provider": "openai",
      "model": "mixtral:8x7b",
      "apiBase": "https://skynet.becomes.self.aware.io:444",
      "apiKey": "sk-somethingsomething"
    }
  ]
```

I suppose if Zed only supports the OpenAI API it wouldn't need `provider`, but otherwise that's a nice way to let users configure their server.

**Comment by jianghoy** [comment]
> > just integrate continue.dev please this will exponentially increase adoption as continue dev solves all of llm worries and works with all possible providers both local and cloud
> 
> Yeah, Continue is very flexible. This is what the Continue config looks like:
> 
> ```json
>   "models": [
>     {
>       "title": "mixtral",
>       "provider": "openai",
>       "model": "mixtral:8x7b",
>       "apiBase": "https://skynet.becomes.self.aware.io:444",
>       "apiKey": "sk-somethingsomething"
>     }
>   ]
> ```
> 
> I suppose if Zed only supports the OpenAI API it wouldn't need `provider`, but otherwise that's a nice way to let users configure their server.

So I suppose a couple of QoL improvements can be made here, assuming all LLM below are compliant with OpenAI's specs:
* [ ] Zed should be able to store multiple LLM configs, following the schema used by `continue.dev`, which, IMHO looks pretty robust.
* [ ] Zed should be able to toggle between multiple LLM providers using configs provided by users.

**Comment by rcgtnick** [comment]
> Zed should be able to toggle between multiple LLM providers using configs provided by users.

As a starting point, even the ability to configure one model hosted locally or on my server would be great.

**Comment by taylorgoolsby** [comment]
Also, since OpenAI is so proprietary, I do not really feel comfortable with the idea that all these open source/weight models are copying the OpenAI API spec. It would not surprise me if in the future, an open standard is created rather than relying on OpenAI to set the standard. I'm not saying we should decide on an open spec right here right now, but just wanted to point this out, and emphasis a need for simplicity.

**Comment by franz101** [comment]
> Also, since OpenAI is so proprietary, I do not really feel comfortable with the idea that all these open source/weight models are copying the OpenAI API spec. It would not surprise me if in the future, an open standard is created rather than relying on OpenAI to set the standard. I'm not saying we should decide on an open spec right here right now, but just wanted to point this out, and emphasis a need for simplicity.

The OpenAI API spec is already the norm for many libraries.
Ollama has a PR to list model endpoint soon:
https://github.com/ollama/ollama/pull/2476

I would propose to keep it simple and allow custom models names if the default api is anything other than openai

**Comment by thosky** [comment]
> > ollama is now OpenAI-compatible as well: https://ollama.ai/blog/openai-compatibility
> 
> This is how, it's working for me
> 
> I couldn't add my custom model to the "default_open_ai_model" setting, For now, Zed is allowing only OpenAI models ("gpt-3.5-turbo-0613","gpt-4-0613","gpt-4-1106-preview"). So I had to clone it to proxy it.
> 
> **Pull and run Mistral model from [Ollama library](https://ollama.com/library)** **Clone the Mistral model as gpt-4-1106-preview**
> 
> ```
> ollama run mistral
> ollama cp mistral gpt-4-1106-preview
> ```
> 
> **Added this to my Zed Settings (`~/.config/zed/settings.json`)**
> 
> ```
> "assistant": {
>     "openai_api_url": "http://localhost:11434/v1"
>  }
> ```
> 
> **Restart Zed**

I have tried this solution with Mistral running locally with ollama. It doesn't work for me. Did anybody else actually make this work?

**Comment by janerikmai** [comment]
Works for 

> > > ollama is now OpenAI-compatible as well: https://ollama.ai/blog/openai-compatibility
> > 
> > 
> > This is how, it's working for me
> > I couldn't add my custom model to the "default_open_ai_model" setting, For now, Zed is allowing only OpenAI models ("gpt-3.5-turbo-0613","gpt-4-0613","gpt-4-1106-preview"). So I had to clone it to proxy it.
> > **Pull and run Mistral model from [Ollama library](https://ollama.com/library)** **Clone the Mistral model as gpt-4-1106-preview**
> > ```
> > ollama run mistral
> > ollama cp mistral gpt-4-1106-preview
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Added this to my Zed Settings (`~/.config/zed/settings.json`)**
> > ```
> > "assistant": {
> >     "openai_api_url": "http://localhost:11434/v1"
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Restart Zed**
> 
> I have tried this solution with Mistral running locally with ollama. It doesn't work for me. Did anybody else actually make this work?

Works for me as described but using codellama:7b-instruct not mistral but it also worked with mistral.
<img width="1800" alt="Screenshot 2024-03-04 at 20 42 39" src="https://github.com/zed-industries/zed/assets/2346648/51febef0-ea37-404b-a8ae-af20917c2fdf">
<img width="1800" alt="Screenshot 2024-03-04 at 20 43 48" src="https://github.com/zed-industries/zed/assets/2346648/c4087a1b-327c-4733-9fc3-2de05327ff65">

**Comment by taylorgoolsby** [comment]
How would zed know what a model's token limit is?

**Comment by thosky** [comment]
@janerikmai 
Thanks for confirming it's working. It's working for me as well now after reinstalling Ollama. The old version might not have supported the open api.

**Comment by james-haddock** [comment]
If you want to use another model available on Hugging Face that's not native to Ollama (DeepSeek-Coder, WizardCoder etc), when creating from GGUF you can explicitly name it to be compatible with Zed when reading from the Modelfile.

`ollama create gpt-4-1106-preview -f Modelfile`

**Comment by Krukov** [comment]
After https://github.com/zed-industries/zed/pull/8646  to make local LLM work you need to add this to Zed Settings (~/.config/zed/settings.json)
```json
  "assistant": {
    "provider": {
      "type": "openai",
      "api_url": "http://localhost:11434/v1"
    }
  }

```

**Comment by versecafe** [comment]
How is this working with the openAI calls for ada embeddings? or is that just dysfunctional?

`crates/ai/src/providers/open_ai/embeddings.rs`
```rs
impl OpenAiEmbeddingProvider {
    pub async fn new(client: Arc<dyn HttpClient>, executor: BackgroundExecutor) -> Self {
        let (rate_limit_count_tx, rate_limit_count_rx) = watch::channel_with(None);
        let rate_limit_count_tx = Arc::new(Mutex::new(rate_limit_count_tx));

        // Loading the model is expensive, so ensure this runs off the main thread.
        let model = executor
            .spawn(async move { OpenAiLanguageModel::load("text-embedding-ada-002") })
            .await;
        let credential = Arc::new(RwLock::new(ProviderCredential::NoCredentials));

        OpenAiEmbeddingProvider {
            model,
            credential,
            client,
            executor,
            rate_limit_count_rx,
            rate_limit_count_tx,
        }
    }
    // ... additional code
 }
 ```

**Comment by andreicek** [comment]
For what it's worth this is what I needed to do to make it work locally:

```json
  "assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "api_url": "http://localhost:11434/v1"
    }
  }
```

Then pick a model: `ollama run mistral` and then `ollama cp mistral gpt-4-turbo-preview`. Restart zed and enjoy.

**Comment by craigcomstock** [comment]
I tried this and I get a prompt to enter an OpenAI API key. I seem blocked even though I have the assistant config mentioned [earlier](https://github.com/zed-industries/zed/issues/4424#issuecomment-2011440348).

If I enter a junk key it doesn't help then I get errors about not being able to connect to OpenAI. So the settings aren't working apparently?

my $HOME/.config/zed/settings.json
zed version: Zed 0.128.3

```
{
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "api_url": "http://localhost:11434/v1"
    }
  }
}
```

**Comment by duggan** [comment]
Looks like there are some new required settings, this does the trick for me:

```
  "assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "type": "openai",
      "default_model": "gpt-4-turbo-preview",
      "api_url": "http://localhost:11434/v1"
    }
  
  ```

**Comment by ednanf** [comment]
Here is a complete rundown of how I got it to work after collecting all the pieces of information in this thread:
*Note: I run Ollama on Mac, if you run anything differently, you have to adapt it.*

1. Add the following configuration to Zed config:
```
"assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "type": "openai",
      "default_model": "gpt-4-turbo-preview",
      "api_url": "http://localhost:11434/v1"
    }
  }
```

2. Download Mistral via ollama cli:
```
ollama run mistral
```

3. Copy the downloaded Mistral, changing its name:
```
ollama cp mistral gpt-4-turbo-preview
```

4. Add the OpenAI API key to Zed ([source](https://ollama.com/blog/openai-compatibility)):
```
ollama
```

5. Restart Zed to ensure everything is working as it is supposed to.

I hope this helps!

**Comment by matthieuHenocque** [comment]
I wish Zed could provide an easy way to point to a server API like the Continue extension. Here is an example in my config file in VSCodium.

```
"models": [
    {
      "title": "Mistral",
      "model": "mistral-7b-instruct-v0.2-code-ft.Q5_K_M",
      "contextLength": 4096,
      "provider": "lmstudio"
    }
  ],
"tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "lmstudio",
    "model": "mistral-7b-instruct-v0.2-code-ft.Q5_K_M",
    "apiBase": "http://localhost:1234/v1/"
  },
```

LM Studio supports multiple endpoints for different context:
```
GET /v1/models
POST /v1/chat/completions
POST /v1/embeddings            
POST /v1/completions
```

I followed @sumanmichael (Thank you so much) steps to make my local Mistral work, but while the chat box works flawlessly, the code completion is still messy compared to the same exact model running through Continue in VSCodium.

Being able to manually set an API endpoint instead of letting Zed concatenating '/completion' to an alleged openai server HTTP address would allow any type of installation.

**Comment by psyv282j9d** [comment]
> Yeah, Continue is very flexible. This is what the Continue config looks like:
> 
> ```json
>   "models": [
>     {
>       "title": "mixtral",
>       "provider": "openai",
>       "model": "mixtral:8x7b",
>       "apiBase": "https://skynet.becomes.self.aware.io:444",
>       "apiKey": "sk-somethingsomething"
>     }
>   ]
> ```

fwiw, I managed to get Continue to generate this very useful config fragment for using Ollama:

```json
"models": [
    {
      "model": "AUTODETECT",
      "title": "Ollama",
      "completionOptions": {},
      "apiBase": "http://localhost:11434",
      "provider": "ollama"
    }
  ],
```

You need to restart VSCode when you add a model to Ollama, but at least you don't need to add another config fragment... very nice.

**Comment by aohan237** [comment]
vote for this feature。
copilot and lsp should be plugins，users can have choices on their own needs

**Comment by dagbdagb** [comment]
> Here is a complete rundown of how I got it to work after collecting all the pieces of information in this thread: _Note: I run Ollama on Mac, if you run anything differently, you have to adapt it._
> 
[snip]
>     4. Add the OpenAI API key to Zed ([source](https://ollama.com/blog/openai-compatibility)):
> 
> 
> ```
> ollama
> ```
> 
>     5. Restart Zed to ensure everything is working as it is supposed to.
> 
> 
> I hope this helps!

I gives hope, at least. Can you please tell us how to define the key in ollama and the exact syntax for adding it to the  zed config?

**Comment by ednanf** [comment]
> > Here is a complete rundown of how I got it to work after collecting all the pieces of information in this thread: _Note: I run Ollama on Mac, if you run anything differently, you have to adapt it._
> 
> [snip]
> 
> > ```
> > 4. Add the OpenAI API key to Zed ([source](https://ollama.com/blog/openai-compatibility)):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > ollama
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 5. Restart Zed to ensure everything is working as it is supposed to.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this helps!
> 
> I gives hope, at least. Can you please tell us how to define the key in ollama and the exact syntax for adding it to the zed config?
> 
> Trying to add a key in the assistant panel results in the following in the console: crates/assistant/src/completion_provider/open_ai.rs:255: DBus error Prompt was dismissed

All you do is to type "ollama" as the openai api key in zed. There's no extra configuration in ollama. at it did not have any for me in both  macs I run. No syntax to add in Zed too. The first time you open the assistant panel (that little "z" icon on the bottom status bar, should be on the right side by default if I recall it correctly), it will have a field to paste the api key. you type ollama and you are good to go.

**Comment by mrnugget** [comment]
Thanks @ednanf. For now I documented the settings here: https://github.com/zed-industries/zed/pull/11790

**Comment by adamierymenko** [comment]
Setting a custom URL works, but it's still incredibly clunky to have to rename/copy a model in Ollama to make it pretend to be ChatGPT.

Seriously this is very easy to do. Just make a generic OpenAI-compatible model type that can take any model name and a local URL.

**Comment by dagbdagb** [comment]
OK. I have followed the instructions, to the best of my ability. The following will result in a response from ollama, when used with curl:
```
curl http://localhost:11434/api/generate -d '{ "model": "gpt-4-turbo-preview", "prompt": "Why isnt the sky green?" }'
```
So the ollama bit appears to work? But not with zed. 

I do get prompted for the key. But upon entering it, the console prints:
```
[2024-05-17T10:10:55+02:00 ERROR util] crates/assistant/src/completion_provider/open_ai.rs:266: DBus error Prompt was dismissed
```

`export OPENAI_API_KEY=ollama` prior to starting zed removes the key prompting. But getting a response from ollama with zed still eludes me.

How much of the URL path should I use in settings.json? I have tried with '', '/api' and '/api/generate'. No go. Do I need to build ollama with particular options? Is the '/v1' part of the URL hardcoded in zed somehow?

**Comment by matthieuHenocque** [comment]
Latest release 0.136.2 add a setting for *anthropic*

Still not an official way to connect to Ollama, but that's progress.

Did anyone try to hack this feature yet?

**Comment by j4ys0n** [comment]
would be pretty easy to connect this to the api run by LM studio if there was a place to enter the url. it's exactly the same as openai.

**Comment by rgbkrk** [comment]
For those following along here, I've made a native Ollama provider in https://github.com/zed-industries/zed/pull/12902

I tried out Ollama with the OpenAI server last week when I was without internet and loved it. Really happy to bring in _all the models_ now.

**Comment by j4ys0n** [comment]
I still think it would be helpful to be able to customize the OpenAI endpoint for the case that someone wants to use another provider. Not everyone trusts those guys with our data. 😅 
Example: I run LM Studio for a couple things, I also occasionally use infermatic.ai. Both of those implement the same API spec as OpenAI. It's inefficient to run multiple separate models, especially when they use so much VRAM/RAM. One model can suffice. Integrated Ollama is great, but I don't think that addresses the issue. Just my opinion and use case. Thank you for considering.

**Comment by rgbkrk** [comment]
For that we will continue to recommend using the OpenAI provider https://zed.dev/docs/assistant-panel#using-a-custom-api-endpoint-for-openai with a custom api url.

What this doesn't have is a listing of all the models available. You're required to set a custom model name (unless you alias). Based on what I did for the Ollama PR, I think adding model listing would be a great addition for all the providers. Let me know if you make a PR.

**Comment by j4ys0n** [comment]
> For that we will continue to recommend using the OpenAI provider https://zed.dev/docs/assistant-panel#using-a-custom-api-endpoint-for-openai with a custom api url.

maybe i'm missing the point here - zed doesn't use the LLM to suggest as you type? that's what i was expecting but probably just because that's what vscode does.

**Comment by rgbkrk** [comment]
There are two main interfaces

* Code completion (inline, as in GitHub copilot)
* Assistant panel (chat on the side, also used by the zed inline assist)

It's the assistant panel that has a soon-to-be-officially launched ollama provider you can swap out.

The code completion provider relies on a separate service, either copilot or supermaven. That trait can be implemented by another service, and you'll likely find that you want lower latency as well as reliance on embeddings in order to create code based on the code base you're in.

**Comment by j4ys0n** [comment]
i see - that makes sense now, thank you.

i'm not quite sure what you're implying with this comment though
>That trait can be implemented by another service, and you'll likely find that you want lower latency as well as reliance on embeddings...

could the code completion component be handled by a local api? apologies for the ignorance of the copilot api, i am however very familiar with the openai api spec, and embeddings.

**Comment by rgbkrk** [comment]
Basically I'm saying you could give code completion with Ollama a shot, using the copilot or supermaven implementations as a guide. I'm tempted myself, but I need to polish off other parts of the code base for a bit.

**Comment by j4ys0n** [comment]
if i had the bandwidth, i'd take it on. i'm just trying to figure out if it's possible to use local models for code completion. in any code editor really.

**Comment by matthieuHenocque** [comment]
@j4ys0n I'm a daily user of local LLM for coding. I'm currently using _Codestral_ in Ollama via the Continue.dev extension in VSCodium for code completion and chat, and nomic-embed-text for embeddings.

**Comment by yaroslavyaroslav** [comment]
> and nomic-embed-text for embeddings.
@matthieuHenocque how good is that? I mean does it provides semantic search or just leveraging completion suggestions?

**Comment by j4ys0n** [comment]
> @j4ys0n I'm a daily user of local LLM for coding. I'm currently using _Codestral_ in Ollama via the Continue.dev extension in VSCodium for code completion and chat, and nomic-embed-text for embeddings.

i'll check this out!

**Comment by j4ys0n** [comment]
@matthieuHenocque you saved the day! up and running with local llama3 70b and codestral 22b. thanks! 🙌

**Comment by yaroslavyaroslav** [comment]
> if i had the bandwidth, i'd take it on. i'm just trying to figure out if it's possible to use local models for code completion. in any code editor really

There is quite a solid solution for AI assistance for sublime text: OpenAI completion plugin. It supports llama and llama.cpp since not too long.

**Comment by matthieuHenocque** [comment]
I came here to say that Zed 0.140.5 is absolutely awesome. You nailed it guys! Thanks!

**Comment by ddegner** [comment]
!! Thanks !!

**Comment by matthieuHenocque** [comment]
I just ran a bunch of tests using Codestral and it looks like there is an issue with the inline assist. The model act as if it was in chat context. Maybe there's a problem with the Ollama endpoint you are using in this context?

Anyway, thanks a lot and keep going!

**Comment by AndydeCleyre** [comment]
Is it currently possible to use ollama with Zed on Linux? Is this documented anywhere?
