### ISSUE TITLE
Horizontal Scrollbar?

### ISSUE THREAD

**Issue by cunninghamd** [zed-industries/zed#4427]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add a horizontal scrollbar when text inside the editing window surpasses the available width.

**Comment by charlis-fl** [comment]
Its been a year guys, when can we expect this

**Comment by rashidnhm** [comment]
I thought for sure I was missing a simple configuration option to enable it, hard to believe it doesn't exist (yet).

This would be a great improvement especially if you want to keep your code more centred within your monitor.

Currently it feels odd when the code (especially writings docs), it at the very edge of the monitor.

**Comment by IAmJafeth** [comment]
Are there any update for the Horizontal Scroll Bar?

**Comment by krabhi1** [comment]
when ?

**Comment by rengler-noodle** [comment]
Also in support of this

**Comment by aretrace** [comment]
Surprised to see no horizontal scrollbar when I encountered @cunninghamd situation, is there a technical reason for this? 
🙁

**Comment by MolotovCherry** [comment]
@SomeoneToIgnore This solves the project panel, but this issue was also about the text editor area too wasn't it? From my testing of that commit I still don't see a horizontal bar in the file editor area if the text exceeds the length

**Comment by SomeoneToIgnore** [comment]
Indeed, there's a horizontal scroll in an unwrapped editor (which got me confused) but no scrolling in the multiline editors, sorry.

**Comment by frqubit** [comment]
What's the progress on adding a horizontal scrollbar to the editor? I've been working on this on a separate fork to get more familiar with the Zed repository, and this has been one of the main things I've been trying to work on. Is there currently someone else working on this?

**Comment by frqubit** [comment]
![image](https://github.com/user-attachments/assets/c8c8bd8d-84c0-4e00-b613-c613b9e9ad49)

Here's an example of what I have laid out so far. A lot of the Zed scrolling functionality assumes that there's only one scrollbar, so it has to be split into two scrollbars with two separate dimensions/hitboxes/ranges etc. Most of that seems to be working, but both hitboxes still seem to be tied together, and using one scrollbar makes both activate like an etch-a-sketch. I'm working on fixing that. It's also not particularly optimized, so that would need to be fixed too.

If there is someone else working on this, that's great. I don't see anything in here indicating any work is being done on the editor itself though, at least not under this issue.

**Comment by frqubit** [comment]
https://github.com/user-attachments/assets/bf352a3f-97e0-43ea-9cfe-eaf8f4c8a730

The scrollbars now work as intended. It just needs to be optimized and be tested, and it's all set. It looks like @SomeoneToIgnore did a pull request for the project panel recently. Do you contribute to Zed often? Some pointers on the specific repository/pull request process would be helpful. I didn't see much on it in the `CONTRIBUTING.md` file.

**Comment by aretrace** [comment]
@frqubit, nice but...
now we what the option to disable it 💀

**Comment by KaKi87** [comment]
Are left/right scroll wheel buttons supported ?

**Comment by SomeoneToIgnore** [comment]
@frqubit 

> Some pointers on the specific repository/pull request process would be helpful.

I do not think there are any specific ones, here are some very generic ideas:

* I would test the thing, ensure that settings allow disabling it and that only one direction of scrolling is possible at the same time
* ensure no perf oddities happen (but maybe the review will tell it better)
* when scrolled to the right down corner, things do not start to look bad: I think overlapping scrollbars is not a good thing, maybe something else is not — I expect the design to be the main issue here but do not have enough expertise here to comment

Overall, you just use this feature a bit yourself, then polish (or at least mention in the PR) the rough edges and create the PR.

**Comment by osiewicz** [comment]
@frqubit Just a heads-up, there's already a PR open that adds a scrollbar component to our `ui` crate (https://github.com/zed-industries/zed/pull/18927). Granted that we'd need to do some extra work to make it work with editor, but I feel like that might be worthwhile.

**Comment by frqubit** [comment]
> @frqubit, nice but... now we want the option to disable it 💀

That should be easy to do. The scrollbar layout already uses `Option` in case the vertical scrollbar is disabled. Maybe there can be a setting for something like `y_only` in the `show` option? (https://zed.dev/docs/configuring-zed#editor-scrollbar) I'm not sure what we would call it. It would be easy to add either way.

**Comment by frqubit** [comment]
> @frqubit Just a heads-up, there's already a PR open that adds a scrollbar component to our `ui` crate (#18927). Granted that we'd need to do some extra work to make it work with editor, but I feel like that might be worthwhile.

I'll have to take a look at that pull request. It probably will be. Currently, the scrollbar is just a track background with a thumb that moves, and both are simple rectangles. Having something that's more generic and customizable may come in handy.

**Comment by frqubit** [comment]
Would it be beneficial to have the scrollbar go past the text in the horizontal direction? I noticed it does that for the vertical scroll, and maybe it'd be good to keep that consistent.

**Comment by fauzymadani** [comment]
> fixed_etch_a_sketch.mp4 
> The scrollbars now work as intended. It just needs to be optimized and be tested, and it's all set. It looks like @SomeoneToIgnore did a pull request for the project panel recently. Do you contribute to Zed often? Some pointers on the specific repository/pull request process would be helpful. I didn't see much on it in the `CONTRIBUTING.md` file.

How to enable that horizontal scrollbar? i have tried
```json
"editor.wordWrap": "off",
  "editor.scrollBeyondLastColumn": 5,
  "editor.horizontalScrollbar": true,
  "autosave": "off",
  "scrollbar": {
    "show": "always"
  }
```
but it's just show the vertical scrollbar, i'm using zed on linux.

**Comment by osiewicz** [comment]
@fauzymadani we don't have a horizontal scrollbar for the editor itself yet.

**Comment by fauzymadani** [comment]
> @fauzymadani we don't have a horizontal scrollbar for the editor itself yet. The video shared by @frqubit is the state of #19495

ooohh, i see. thank you for the information!
