### ISSUE TITLE
Zed local settings aren't always applied & are sometimes overwritten

### ISSUE THREAD

**Issue by rdjpalmer** [zed-industries/zed#4432]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Replicate the settings not being applied**

1. Zed > Settings > Open local settings
2. Set `tab_size` property
3. Close zed fully
4. Open zed
5. Proceed to code w/language where default `tab_size` is different to set value

Doesn't happen if you open `./zed/settings.json` via the sidebar.

**Replicate the settings being overwritten**

1. Zed > Settings > Open local settings
2. Add some configuration
3. Close zed fully
4. Open zed
5. Zed > Settings > Open local settings
6. See an empty configuration file

Doesn't happen if you open `./zed/settings.json` via the sidebar.

### Environment

Zed: v0.106.2 (stable)
OS: macOS 13.5.2
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/2162181/f90ed25c-607f-45d9-81b1-a9ad9fc152e8

https://github.com/zed-industries/community/assets/2162181/08d8d56f-10db-4c96-81e7-6b17e12cb722

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by coratgerl** [comment]
I encounter the same issue for prettier it's very problematic :(

**Comment by perragnar** [comment]
I have the same issue with ignored local setting. I have a local settings.json with format_on_save set to false but it still autoformats on save.

**Comment by WeetHet** [comment]
As far as I see, local settings do not work at all

**Comment by kspadhi** [comment]
This is very gereric issue any settings i try to apply in zed

**Comment by aarroisi** [comment]
I also experience this issue. Very annoying. Right now I always use global settings as a workaround, but would like this to be fixed.

**Comment by perragnar** [comment]
I just found out that the local settings are loaded if you open the local settings file.

**Comment by MadYurySolovyov** [comment]
Yup, I've been poking local settings to get them applied, somewhat annoying.

**Comment by YurySolovyov** [comment]
Yup, I've been poking local settings to get them applied, somewhat annoying.

**Comment by mrnugget** [comment]
I cannot reproduce this.

What I did:

1. Open folder in Zed
2. Use `zed: open local settings` to create new `.zed/settings.json` file
3. Add this to the file: `{ "tab_size": 8, "show_whitespaces": "all" }`
4. Save file
5. Close all open tabs
6. Close Zed
7. Reopen Zed, open same folder
8. Whitespace is visible and tab size is 8

**Comment by YurySolovyov** [comment]
I just tried the following:
- .zed/settings.json:
```json
{
  "tab_size": 2
}
```
- don't close all tabs, have e.g. a rust file
- moved to impl, typed
```rs
pub fn hey() { | // <-cursor here
```
hit enter 
Result: wrong tab width

https://github.com/zed-industries/zed/assets/2168518/aa9837d9-842a-408e-8556-c2ad1e4460b9

**Comment by GyozaGuy** [comment]
I have this issue on the Linux build. What works for me is to simply open the local settings once, then they apply. 🤷🏼‍♂️

**Comment by mrnugget** [comment]
> I just tried the following:

Are you on Windows? Asking because the cursor doesn't look like a macOS cursor.

**Comment by mrnugget** [comment]
Changing the tab size also works for me:

https://github.com/zed-industries/zed/assets/1185253/29017f94-c4b8-4a03-83f7-68d06608aaf0

**Comment by YurySolovyov** [comment]
> Are you on Windows? Asking because the cursor doesn't look like a macOS cursor.

Yes, I'm on mac, cursor could be an artifact of recording tool? (peek)

Could it be that I also have additional ext filetypes mapping?
```js
 "file_types": {
    "Ruby": ["yrs"]
  }
```

**Comment by mrnugget** [comment]
> Could it be that I also have additional ext filetypes mapping?

You tell me! Is it a `yrs` file?

**Comment by YurySolovyov** [comment]
No, I just have that setting in my settings, but I only care about rust files (`yrs` files in the tree are just text files)

I mention this just in case there is some weird interaction between these settings

**Comment by mrnugget** [comment]
Do you have any global settings that might interfere?

I'd suggest cleaning your global settings.json and just setting it to a blank `{}`, then creating a test repository in which you have your single Rust file and a new `.zed/settings.json` with `tab_width` and see if that works.

**Comment by YurySolovyov** [comment]
No, I don't have any global settings. I'll try to come up with a clean case. But seems like I'm not the only one affected

**Comment by YurySolovyov** [comment]
I think I figured it out: I tried making a simple rust repo with `cargo init` and I could not reproduce the issue, but in my project it was still reproducible, so I looked at the difference, and the only (seemingly important) thing was that `.zed` dir is under `.gitignore`, which made it occur in repro case now.

So anyway, here is a repo
```
https://github.com/YurySolovyov/zed-settings-repro
```
with example settings file

**Comment by kobbythedev** [comment]
who knows where i can copy and paste the settings again, i messed up mine
