### ISSUE TITLE
Multi-codepoint graphemes split apart and rendered separately in terminal

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#4437]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use Starship prompt with Nushell, ☁️ emoji is used as an icon for AWS cloud, it works perfectly with iTerm but on Zed the emoji is not display.

### Environment

Zed: v0.106.2 (preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Capture d’écran 2023-10-02 à 15 37 50](https://github.com/zed-industries/community/assets/24520681/b7246fcc-cc89-4e1d-93c3-73630b8abcca)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by antonengelhardt** [comment]
Update:

The icon for git is now working in the same project (after some update). In another project, Git, Kubernetes, Cargo, Rust are working and Openstack is not: 
![Screenshot-Zed-005844@2x](https://github.com/zed-industries/zed/assets/106314688/e3b61d31-72b1-4cd0-ba58-d24566405849)

**Comment by notpeter** [comment]
I'm going to close this in favor of:
- https://github.com/zed-industries/zed/issues/5224

Thanks for reporting.  Please 👍 and subscribe that issue to track it's progress.
