### ISSUE TITLE
Zed should exit vim visual mode after `cmd-/`

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#4439]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Select a few lines in vim visual mode.
2. Run a command: cmd+/ (comment) or shift-J (join lines).
3. The command is executed but the selected lines remain selected. Instead, Zed should transition to normal mode.

### Environment

Zed: v0.105.5 (stable)
OS: macOS 13.5.2
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This is now included in [v0.125.0-pre](https://zed.dev/releases/preview/0.125.0).

**Comment by hferreiro** [comment]
This appears to work for most commands, but not for commenting (cmd-/).

**Comment by ConradIrwin** [comment]
yup. I'd really like to add something like vim-commentary; but in the meantime we can fix this by wrapping the editor::ToggleComments action in a vim::ToggleComments action that also changes mode.

Happy to work together on this if you'd like: https://calendly.com/conradirwin/pairing

**Comment by ConradIrwin** [comment]
Since I last commented you can now get the vim-commentary like behavior with `gc`
