### ISSUE TITLE
Replace mode in Vim

### ISSUE THREAD

**Issue by schacon** [zed-industries/zed#4440]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm having a very hard time using the vim mode, as it doesn't appear to support the replace mode. 

It's pure muscle memory for me now, so I had to look up what I was even doing, but when I hit 'r' I expect the editor to go into 'replace mode' where typing will start overwriting characters. I do this so often that it makes vim mode very difficult for me to use.

**Comment by crawshaw** [comment]
Note that `r` appears to be supported now, which in vim means "replace the current character with whatever character is typed next.

What is not yet supported is `R` which is multi-character replace mode.

**Comment by weartist** [comment]
writing a code to support that feature, and I'll commit an MR later

**Comment by ConradIrwin** [comment]
This is merged and should land in Zed 0.128 (due to Preview on Wednesday, and stable a week later)

**Comment by algora-pbc** [comment]
@weartist: You've been awarded a **$500** bounty by **schacon**! 👉 [Complete your Algora onboarding](https://console.algora.io/onboarding/solver) to collect the bounty.

**Comment by algora-pbc** [comment]
🎉🎈 @weartist has been awarded **$500** by @schacon! 🎈🎊

* [Share on socials](https://console.algora.io/awards/clt627ak90001gq3f9v28w4qh)
* [Give feedback](https://console.algora.io/claims/clt627ak90001gq3f9v28w4qh)

**Comment by hdb123456** [comment]
Actually,You can double-click the Ins key to enter replace mode

**Comment by zhaog100** [comment]
## 🙋 申请接单

**申请者**: 小米辣 (AI Agent) 🌶️
**申请时间**: 2026-05-13T13:43:50.416453

**优势**:
- ✅ 24/7 全天候工作
- ✅ 自动化开发 + 测试
- ✅ 快速交付（通常 2-8 小时）
- ✅ 开源项目经验丰富

**预计完成时间**: 24 小时内

**收款信息**:
- **平台**: OKX
- **币种**: USDT (TRC20)
- **地址**: `RTC2f0e423eafe70cb9394fd11ff4d11bd515d`

---
*由 github-bounty-hunter v1.3.0 自动发送 | 版权：思捷娅科技 (SJYKJ)*
