### ISSUE TITLE
[Zed Preview] Elixir language server - failed to deserialize latest release

### ISSUE THREAD

**Issue by noozo** [zed-industries/zed#4445]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When updating to latest zed preview 0.106.0, got this while downloading the Elixir language server.

NOTE: Happens for both elixir-ls and the new experimental next-ls.

```
Language server error: Elixir

error deserializing latest release
```

### Environment

Zed: v0.106.0 (preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by luhc228** [comment]
When will this issue fix? I can not develop my rust project now. @JosephTLyons

**Comment by SomeoneToIgnore** [comment]
@luhc228 what has Rust project to do with Elixir LSP issues from 2023?
Please share more details, and if it's indeed related to Rust, in another issue.

**Comment by luhc228** [comment]
> @luhc228 what has Rust project to do with Elixir LSP issues from 2023? Please share more details, and if it's indeed related to Rust, in another issue.

I am sorry. But I think my problem is like this issue. 

![image](https://github.com/zed-industries/zed/assets/44047106/ac8506de-1e98-4f23-8641-bc1d25b35860)

I will comment in another issue. Thanks.

**Comment by ForLoveOfCats** [comment]
We made a change a few months ago to avoid re-attempting to install a language server too many times so I'm surprised to see we're still getting rate limited. What Zed version are you running? Did multiple language servers fail to install?

**Comment by jiangshuai1995** [comment]
<img width="1275" alt="image" src="https://github.com/zed-industries/zed/assets/25057501/35c88caf-6926-4e3f-b345-511e018bae69">

This is my first time using zed, same error with golang.

**Comment by karelbilek** [comment]
First time using zed, having same issue with golang LSP server.

**Comment by joshrutkowski** [comment]
Working on adding an LSP and running into the same issue
