### ISSUE TITLE
vim Command display

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#4447]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/zed-industries/community/assets/19868292/f1623a82-4ca4-4767-a496-dbf50d0c7173

**Comment by weartist** [comment]
@ConradIrwin Maybe we could add a display component below to synchronize the contents of the current vim operation stack, do you think that's possible?

**Comment by ConradIrwin** [comment]
Yup! 

We could probably reuse the ModeIndicator.

**Comment by JosephTLyons** [comment]
This landed in [Zed v0.132](https://zed.dev/releases/preview/0.132.0).
