### ISSUE TITLE
cmd-p should move to next entry when in file finder

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#4450]
### Check for existing issues

- [X] Completed

### Describe the feature

After opening the file finder with cmd-p, cmd-p should move the focus to the next entry, instead of closing the file finder. This is the current behavior of vscode, and allows to quickly switch between recent files.

**Comment by alygin** [comment]
It looks like #6947 solves the problem (quickly switches to the previously opened file), though in the IntelliJ IDEA style.

**Comment by JosephTLyons** [comment]
Yep, I think you're right @alygin, let's close this as completed!

**Comment by hferreiro** [comment]
Should I open a new issue for https://github.com/zed-industries/zed/issues/4450#issuecomment-1908621350?

**Comment by JosephTLyons** [comment]
> Should I open a new issue for https://github.com/zed-industries/zed/issues/4450#issuecomment-1908621350?

Oh yeah, let's open another issue for that.

**Comment by JosephTLyons** [comment]
Some discussion happened here as well:

https://github.com/zed-industries/zed/issues/4450#issuecomment-1908621350

Just to note, a new tab switcher is being worked on at the moment:

- https://github.com/zed-industries/zed/pull/7338

**Comment by alygin** [comment]
And a relevant discussion: [Action Release trigger](https://github.com/zed-industries/zed/discussions/8310)
