### ISSUE TITLE
It's not possible to login to CoPilot when `show_copilot_suggestions` is set to `false`

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#4451]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When `show_copilot_suggestions` is set to false, but Copilot is enabled, it is impossible to log in to the service. When I click on the CoPilot icon and the `Sign In` option, nothing happens. When I switch the `show_copilot_suggestions` option to `true` - everything works as it should.

### Environment

Zed: v0.105.4 (preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
I'm going to go ahead and close this as `show_copilot_suggestions` is no longer a setting for Zed. If you are still experiencing this, please open a new issue with full details as what's happening.  Thanks for reporting.
