### ISSUE TITLE
Cannot click the "Copy diagnostic message" tooltip

### ISSUE THREAD

**Issue by kwando** [zed-industries/zed#4452]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Enable inlay hints, go to a line where there is an error/warning. Hover over the inlay hint and wait for the "Copy diagnostic message" to appear... try to click on it. 9/10 times  it disappears before I can move my mouse and click on it.

### Environment

Zed: v0.105.3 (preview)
OS: macOS 13.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Skärmavbild 2023-09-26 kl  09 17 48 1](https://github.com/zed-industries/community/assets/891566/414e2a63-12f3-4065-ae69-3bf6c2ba7e3f)

I think a short delay before hiding the tooltip will make it easier to click on.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I'm not able to reproduce any issue with copying warnings or errors in v0.161.0. We've changed things here a bit since this issue was filed.
