### ISSUE TITLE
` char now impossible on French keyboard

### ISSUE THREAD

**Issue by BastienVigneron** [zed-industries/zed#4459]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since the version 0.104.4 the ` char (backtick) is now impossible to type on a French keyboard in the integrated terminal (note the ~ char is still unavailable too).

### Environment

Zed: v0.104.4 (stable)
OS: macOS 13.5.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Tom-Boscher** [comment]
Same issue here with a ISO-FR layout.
`~` is not possible to as described here: https://github.com/zed-industries/zed/issues/7451
