### ISSUE TITLE
Zed deletes symlinked settings.json file when changing theme via `theme selector: toggle`

### ISSUE THREAD

**Issue by clo4** [zed-industries/zed#4469]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When ~/.config/zed/settings.json is a symlink, changing the theme via the command palette seemingly performs an atomic write, deleting the symlink then writing a new JSON file in its place. This affects anyone that wants to store their Zed config in a central "dotfiles" repository with a symlink to the correct location

I can't think of any other commands that would change the config file, off the top of my head, but I'd guess they're affected by this issue too.

### Environment

Zed: v0.104.3 (preview)
OS: macOS 13.5.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Support for this has landed in today's [v0.123.1-pre](https://zed.dev/releases/preview/0.123.1) release.

Since initial Clojure support has landed, let's close this issue out and open new issues for whatever comes up.

**Comment by clo4** [comment]
Oh wait, my mistake. This should be closed, the Kotlin message was what confused me. Joseph was right!

**Comment by JosephTLyons** [comment]
> Oh wait, my mistake. This should be closed, the Kotlin message was what confused me. Joseph was right!

Oops! Caught me with the copy and paste error! 😂
