### ISSUE TITLE
Allow updating themes or make existing themes actually have good contrast

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/zed#4482]
### Check for existing issues

- [X] Completed

### Describe the feature

I like using `Atelier Plateau Light` theme but suggestions look like this:

<img width="665" alt="image" src="https://github.com/zed-industries/community/assets/6391776/083e0982-cc4c-4101-9f72-6e6f4ce9f747">

Focused suggestion from search is barely readable. 😞

Can I change it so I can use the suggestions properly?

If I can't change it as theme support is not implemented, can you at least update it to make default themes work well.

Thank you.

**Comment by maxdeviant** [comment]
We now have user theme support and allow overriding themes via `experimental.theme_overrides` in the settings file.

We're still figuring out what the future of the built-in Zed themes is, but we're not looking to make changes to those themes at this point.
