### ISSUE TITLE
Incorrect paste when Opening file

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4485]
### Check for existing issues

- [X] Completed

### Describe the feature

When trying to open a file (`CMD+O`) when `CMD+V` (Paste) is pressed, it will paste whatever in-memory (clipboard) text content is there. The clipboard will be pasted within currently active pane. I believe such behavior should not be happening.
Note: Other functions moving around text are not accessible, which is correct, nonetheless `CMD+V` works.

On the other hand, it would come handy the ability to paste clipboard saved path to file, i.e. `/Users/<user>/magical_file.ext` when pasted into `CMD+O` window, the window shall take user into the file path.

### If applicable, add mockups / screenshots to help present your vision of the feature

Current erroneous window after `CMD+V` action:
![Screenshot 2023-09-12 at 5 34 44 PM](https://github.com/zed-industries/community/assets/4711498/f96bb612-8c2a-46c4-bb34-5a3f56cc6f7b)

**Comment by notpeter** [comment]
@krstp I believe sometime in the last 9 months we fixed the bug you reported with paste. If this is still happening, feel free to leave a comment and we can re-open.

As for the feature request, we can't actually override the OS provided open controls to implement a feature like pasting to jump to a path.  But...on MacOS if you press cmd+shift+g (Goto...) you can paste there and it will jump to the correct file and folder, so you should be able to do this today!
