### ISSUE TITLE
Inline Assistant change default model

### ISSUE THREAD

**Issue by rwese** [zed-industries/zed#4486]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- have no access to the openai - gpt4 model
- modify user settings, or folder settings, to use the `assistant > default_open_ai_model > 'gpt-3.5-turbo'`
- attempt in-line assistant
- get error: `Failed to connect to OpenAl API: The model 'gpt-4-0613 does not exist or you do not have access to it. ...`

If I enable `include conversation` it will use the model and context of the chat, but often include the entire chat-response, when creating new content.

### Environment

Zed: v0.102.2 (stable)
OS: macOS 13.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature
even though the screenshot shows `.zed/settings.json`, where this is not supported per the documentation, I've set it also in the settings `.config/zed/settings.json`.
<img width="589" alt="image" src="https://github.com/zed-industries/community/assets/7153716/56a90492-8f5e-4260-83af-526178144e8c">

```json
{
  "assistant": {
    "default_open_ai_model": "gpt-3.5-turbo"
  }
}
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by dignifiedquire** [comment]
similar issue here, getting this for all models though

**Comment by barrynorman** [comment]
Same here. Unfortunately I cannot use OpenAI at all.

**Comment by daiotsulabs** [comment]
> Same here. Unfortunately I cannot use OpenAI at all.

me too,

**Comment by notpeter** [comment]
We have drastically revamped the settings and configuration structure for OpenAI and the Assistant Panel in general. If you are still having trouble configuring OpenAI, please take a look at our docs:
https://zed.dev/docs/assistant/configuration#openai

Alternatively, Zed offers Anthropic Claude 3.5 access at no cost within Zed, just login to Zed with your GitHub account, and away you go, no API keys necessary.

I'm closing this as no longer applicable. If you run into issues please feel free to open a new clean issue for assistance.

Thanks for reporting all.
