### ISSUE TITLE
How to have Error Lens (inline errors in editor)

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/zed#4494]
### Check for existing issues

- [X] Completed

### Describe the feature

I need this plugin in Zed https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

VSCode:

<img width="901" alt="image" src="https://github.com/zed-industries/community/assets/6391776/999bbc68-3f2b-4cd6-af3c-9cf241f59d8b">

Zed:

<img width="674" alt="image" src="https://github.com/zed-industries/community/assets/6391776/15690512-3779-41e0-b4a0-ec3733d205dd">

Can I achieve this?

**Comment by Moshyfawn** [comment]
Can this be considered a duplicate of #4901 as it has more upvotes?

**Comment by JosephTLyons** [comment]
> Can this be considered a duplicate of #4901 as it has more upvotes?

I think so. Let's close this one out. If there's something about this issue that is different @nikitavoloboev, let us know and we can reopen it, or extra details can be added to #4901.

**Comment by nikitavoloboev** [comment]
No extension. Was like this.

**Comment by kriptonian1** [comment]
I was really planning to switch to zed but error lens was a deal breaker

**Comment by kriptonian1** [comment]
thanks @gurubyte your solution worked for me

**Comment by gurubyte** [comment]
> [@nikitavoloboev](https://github.com/nikitavoloboev) [@kriptonian1](https://github.com/kriptonian1)
> 
> ```
> "diagnostics": {
>         "include_warnings": true,
>         "inline": {
>             "enabled": true
>         }
> }
> ```
> 
> Worked for me.
> 
> Its in `~/.config/zed/settings.json` file

for some reason, I installed Zed again and it stopped working. I dont have error lens right now

**Comment by araea** [comment]
> @nikitavoloboev [@kriptonian1](https://github.com/kriptonian1)
> 
> ```
> "diagnostics": {
>         "include_warnings": true,
>         "inline": {
>             "enabled": true
>         }
> }
> ```

thanks! it is truly helpful~
