### ISSUE TITLE
Support JSON Schema autocomplete

### ISSUE THREAD

**Issue by jezikk** [zed-industries/zed#4496]
### Check for existing issues

- [X] Completed

### Describe the feature

Specifications: https://json-schema.org
Examples:
```json
{
  "$schema": "https://turbo.build/schema.json",
  "globalDependencies": ["**/.env.*local"],
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "lint": {},
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}
```

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "composite": false,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": false,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true
  },
  "exclude": ["node_modules"]
}
```

### If applicable, add mockups / screenshots to help present your vision of the feature

Autocomplete in VSCode:
<img width="583" alt="vscode" src="https://github.com/zed-industries/community/assets/7671531/cfe522c7-6ab9-472a-bf2f-8e81e2727186">

**Comment by dxts** [comment]
+1, would greatly improve experience when writing Kubernetes resources and build config files.
 
The [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) already has settings for JSON schema support. 
> * yaml.completion: Enable/disable autocompletion
> * yaml.schemas: Helps you associate schemas with files in a glob pattern 
> * yaml.schemaStore.enable: When set to true the YAML language server will pull in all available schemas from [JSON Schema Store](https://www.schemastore.org/json/)
> * yaml.schemaStore.url: URL of a schema store catalog to use when downloading schemas.


But I'm not sure how to manipulate these from zed settings, as the `lsp` setting only includes `initialization_options`. 
And also `lsp` settings cannot be overridden at folder level (which would be necessary for the `yaml.schemas` setting).

**Comment by JosephTLyons** [comment]
Hey @jezikk, Zed does provide autocompletions for json schema:

<img width="1608" alt="SCR-20240412-onkt" src="https://github.com/zed-industries/zed/assets/19867440/a5bce952-1408-4a72-8f6b-d303d48f403e">

Does this satisfy what you are looking for?

**Comment by jezikk** [comment]
Yes thank you.

<img width="1036" alt="image" src="https://github.com/zed-industries/zed/assets/7671531/88a447cf-7898-4e6f-879e-b14f056d3218">
