### ISSUE TITLE
Add a setting to hide Inline Assist button

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#4500]
### Check for existing issues

- [X] Completed

### Describe the feature

I don't use Inline Assist functionnality and I like to have a very clean and minimalist workspace, I don't think I am the only one to don't use the Inline Assist so I think it would be great to have a settings to hide/show the Inline Assist button in editor.

**Comment by avrong** [comment]
How to hide it now? I did not find any docs for the feature implemented in this issue

**Comment by SomeoneToIgnore** [comment]
Here's a list: https://github.com/zed-industries/zed/issues/7121#issuecomment-1919269392
We keep it documented in the comments of the corresponding knobs in the default settings file (`zed: open default settings` command) but this is not the best place in terms of discoverability.
Would be great to get a https://github.com/zed-industries/zed/tree/main/docs/src updated with that knowledge.

**Comment by avrong** [comment]
@SomeoneToIgnore Thanks! I have these settings in my config, but it doesn't remove Inline Assist button from the UI.

<img width="585" alt="image" src="https://github.com/zed-industries/zed/assets/6342851/ec570428-f7ed-496a-a711-bc281418fe35">

**Comment by SomeoneToIgnore** [comment]
Oh that one — sorry, confusing the terms apparently.
There's no setting for that one, alas, another PR is needed to add it.
