### ISSUE TITLE
vim mode: support `gf` command

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#4501]
### Check for existing issues

- [X] Completed

### Describe the feature

The "goto file" command in vim allows to navigate to the file whose name is under or after the cursor.

This command is very handy to navigate to header files in C/C++.

**Comment by mirageN1349** [comment]
It's very difficult without this function

**Comment by vmchale** [comment]
<C-w><C-f> will open the file in a new buffer (in Zed, I suppose a new tab) as well.

**Comment by mrnugget** [comment]
I added this in: https://github.com/zed-industries/zed/pull/16534
