### ISSUE TITLE
vim - HTML tag support

### ISSUE THREAD

**Issue by eiiot** [zed-industries/zed#4503]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim, you can use `cit` to change the content inside of a HTML tag, `dit` to delete the content inside of a HTML tag, or `dat` to delete the tag itself. It would be great if zed could replicate this feature as well.

**Comment by weartist** [comment]
I'm willing to submit a PR for this requirement if I can

**Comment by AkiPraveen** [comment]
I am also willing to submit a PR if nobody else is working on it. Glad that I wasn't imagining this / doing something wrong!

**Comment by mirageN1349** [comment]
> I am also willing to submit a PR if nobody else is working on it. Glad that I wasn't imagining this / doing something wrong!
> 
> Has anyone else tested this outside of languages like HTML and XML and found similar shortcomings in 'tag' languages? Currently I am thinking we need to look at the following file formats. Please feel free to reply and correct me.
> 
> * HTML
> * JSX
> * TSX
> * XML

Hello! .vue

**Comment by weartist** [comment]
I've written a simplified version of the code, which is being optimized and tested, and I'll add the delete logic when I'm done

**Comment by Moshyfawn** [comment]
I see the PR went in last month. Can this be considered resolved?

**Comment by ConradIrwin** [comment]
Yes. Though some follow-up is needed #9844 and #8994

**Comment by hanumanman** [comment]
This doesnt work in TSX anymore in Zed's latest version. It still works fine in html files

**Comment by sj26** [comment]
This doesn't seem to work in ERB, either.
