### ISSUE TITLE
.htm and .shtml support

### ISSUE THREAD

**Issue by sweetppro** [zed-industries/zed#4510]
### Check for existing issues

- [X] Completed

### Language

htm, shtml

### Tree Sitter parser link

https://github.com/tree-sitter/tree-sitter-html

### Language server link

https://github.com/Microsoft/vscode/tree/master/extensions/html-language-features/server

### Misc notes

**html** support is already present in Zed, support for **.shtml** and **.htm** should also be available.
thanks
:)

**Comment by maxdeviant** [comment]
This is available in [Zed v0.121.0](https://zed.dev/releases/preview/0.121.0).
