### ISSUE TITLE
Rust: rustdoc comments not multiline-friendly during input

### ISSUE THREAD

**Issue by mcginty** [zed-industries/zed#4512]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While normal comments (`//`) are carried on after a newline during input, a rustdoc triple-slash (`///`) comment is not.

For example, say that your inputs in the IDE in a `sample.rs` file is `// First line<Enter>This is the second`

The output by Zed would be (correctly):

```rust
// First line
// This is the second
```

Now if instead we input `/// First line<Enter>This is the second`

Zed currently produces

```rust
/// First line
This is the second
```

when I would expect

```rust
/// First line
/// This is the second
```

### Environment

Zed: v0.101.1 (preview)
OS: macOS 13.5.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by onbjerg** [comment]
I've been trying to look at this, I'm not entirely sure why this is happening, since it works in tests. If we duplicate the `test_newline_comments` test with Rust-like comments:

```rust
#[gpui::test]
async fn test_rust_newline_comments(cx: &mut gpui::TestAppContext) {
    init_test(cx, |settings| {
        settings.defaults.tab_size = NonZeroU32::new(4)
    });

    let language = Arc::new(Language::new(
        LanguageConfig {
            line_comments: vec!["// ".into(), "/// ".into(), "//! ".into()],
            ..LanguageConfig::default()
        },
        None,
    ));
    {
        let mut cx = EditorTestContext::new(cx).await;
        cx.update_buffer(|buffer, cx| buffer.set_language(Some(language), cx));
        cx.set_state(indoc! {"
        /// Fooˇ
    "});

        cx.update_editor(|e, cx| e.newline(&Newline, cx));
        cx.assert_editor_state(indoc! {"
        /// Foo
        /// ˇ
    "});
        // Ensure that if cursor is before the comment start, we do not actually insert a comment prefix.
        cx.set_state(indoc! {"
        ˇ/// Foo
    "});
        cx.update_editor(|e, cx| e.newline(&Newline, cx));
        cx.assert_editor_state(indoc! {"

        ˇ/// Foo
    "});
    }
    // Ensure that comment continuations can be disabled.
    update_test_language_settings(cx, |settings| {
        settings.defaults.extend_comment_on_newline = Some(false);
    });
    let mut cx = EditorTestContext::new(cx).await;
    cx.set_state(indoc! {"
        /// Fooˇ
    "});
    cx.update_editor(|e, cx| e.newline(&Newline, cx));
    cx.assert_editor_state(indoc! {"
        /// Foo
        ˇ
    "});
}
```

The test passes

I'd imagine the bug is somewhere in https://github.com/zed-industries/zed/blob/8bc105ca1d49faf6c013ffc06feec904a1ed5143/crates/editor/src/editor.rs#L2456

**Comment by onbjerg** [comment]
This was solved yesterday in https://github.com/zed-industries/zed/pull/6713 which is why the test passes 😄

**Comment by mcginty** [comment]
Closed as dupe, great news!
