### ISSUE TITLE
The project panel does not scroll file far enough into view

### ISSUE THREAD

**Issue by brandonweiss** [zed-industries/zed#4513]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you have a project with enough folders/files that it fills the entire vertical space of the project panel, when you use the Go To File command (fuzzy-finder) to open a file it will expand the folders and highlight the file in the project panel. But it puts the highlighted file at the bottom of the project panel—that is, it scrolls downwards until the file _just_ comes into view and then stops.

Here’s what that looks like:

<img width="322" alt="Screenshot 2023-08-29 at 10 56 42 AM" src="https://github.com/zed-industries/community/assets/4727/b27b1e6b-21b6-419d-bdad-138a786c2651">

I think this is problematic because it’s not immediately obvious where the file is in the project panel or that it has been scrolled into view, and when scanning for it it’s really hard to pick out because the highlighted row is roughly the same color as the status bar.

I think in general people would be more likely to expect to see the project panel scrolled until the file is roughly in the center of the project panel.

### Environment

Zed: v0.99.1 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This issue is still valid, but we have a new issue that just came in that has one more vote than this one, so I will close this one out in favor of that one. Please 👍 the new issue and feel free to add any additional details to it via a comment:

- https://github.com/zed-industries/zed/issues/18255
