### ISSUE TITLE
~/.zprofile is not sourced when opening terminal pane

### ISSUE THREAD

**Issue by lxwbr** [zed-industries/zed#4521]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening the terminal (CMD-J) I always need to source ~/.zprofile as it is not picked up automatically. This seems weird as zsh is still used as shell.

### Environment

Zed: v0.99.1 (stable)
OS: macOS 13.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by choonchernlim** [comment]
I was able to replicate this problem too. It appears to be sourcing `~/.profile` instead of `~/.zprofile`.

My temporary workaround is to create `~/.profile` with the same content as `~/.zprofile`.

My settings for terminal looks like this:

```
  "terminal": {
    "shell": {
      "program": "/bin/zsh"
    }
  },
```
