### ISSUE TITLE
global searche close,action not stop

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#4522]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Use search and then close search, memory growth does not stop

### Environment

Zed: v0.101.0 (preview)
OS: macOS 13.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
@0x2CA Can you confirm whether you are still experiencing this issue?  A lot has happened in the last 10months and I'm trying to groom the backlog a bit.

**Comment by 0x2CA** [comment]
Haven't noticed if it's still a problem lately, I'll close it and if it happens again I'll open it again
