### ISSUE TITLE
Can not format unsaved file/buffer with custom formatter

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4529]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Set an arbitrary formatter for some language in `"language_overrides"`.
2. Call the new file command to create a new file without saving it.
3. Input some unformatted content into the buffer.
4. Call the format command.

Observation: The buffer is not formatted.

### Environment

Zed: v0.100.0 (preview)
OS: macOS 13.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by NicoAdrian** [comment]
Same problem here :(

**Comment by edtorba** [comment]
Ran into the same issue. Just to add on, it's pretty normal for devs to do stuff like copying a messy api response (e.g. json) and trying to make sense of it. In VS Code, it's a as simple as - just set the type, right-click, and hit "Format".

**Comment by eproxus** [comment]
It seems this is not possible with built-in formatters either. To reproduce:

1. Open a new (unsaved) buffer
2. Paste some unformatted JSON
3. Set syntax to `JSON`
4. Try to format the buffer (nothing happens)
5. Save it as `temp.json`
6. Try to format the buffer (now it works)

**Comment by jessevdp** [comment]
Same experience here. Not using any language overrides. For a JSON file.

I recorded a video in #9773.

For what it's worth, I'm able to run a formatter like this in VSCode.

**Comment by NicoAdrian** [comment]
Any update on this matter ?

**Comment by eh-lucas-maffazioli** [comment]
This is really essential to an in-development code editor, this will make me ditch VSCode as my second IDE

**Comment by failable** [comment]
@mrnugget 

The release note says `Added the ability to format unsaved buffers with Prettier. `

Is that mean only [languages](https://prettier.io/docs/en/) supported by Prettier will work? So I can not format Python or Rust code in a unsaved buffer?

Besides, why not just use the same formatter of files for unsaved buffers? For example one use `jq` for JSON file , but have to use `Prettier` for unsaved buffers. One would have to deal with different config options to make them consistent.

**Comment by mrnugget** [comment]
Reopening this since, yes, the issue isn't fixed for custom formatters. 

I went with prettier first, because that's consistent across many file types and languages and by default allows formatting arbitrary text input.

For external commands (custom formatters) we'll have to make sure the syntax is consistent so that it works with saved/unsaved buffers alike.

For language servers (rust-analyzer, ...) the problem is that Zed doesn't even know which language server should be associated with a file if it's not saved.

**Comment by jessevdp** [comment]
Does that mean that language servers are picked based on file extensions? 

I don't know what else would prevent Zed from knowing what language server to associate with a file.

Since syntax highlighting is controlled by the language selector right? I would assume that also controls the language server, but perhaps not?

Mainly just curious! 😁

**Comment by mrnugget** [comment]
> I don't know what else would prevent Zed from knowing what language server to associate with an unsaved a file.

I'll need to dig into this, I think maybe it works the way you described it.

**Comment by bennetbo** [comment]
> I don't know what else would prevent Zed from knowing what language server to associate with an unsaved a file.

It looks like the LSP protocol does not support formatting files that are not saved to disk ([formatting spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting).

All requests that do some kind of formatting expect a `TextDocumentIdentifier`, which point to the corresponding file path. 

Do you know any editors that support this? Looks like VSCode does not support it, e.g. when trying to format an unsaved rust file I see:

<img width="272" alt="image" src="https://github.com/zed-industries/zed/assets/53836821/d20d6c53-d9e0-44cb-ab59-569c881bd2a3">

**Comment by failable** [comment]
Formatting unsaved buffers works in Emacs.

```
      "formatter": {
        "external": {
          "command": "pyformat", // Or whatever
          "arguments": ["-"]
        }
      }
```

I think at least the external formatter setting should be able to work in this case.  Just like the last release of `Prettier`. But instead of using `Prettier`, we merge that two configs into one. 

```
"formatter": ...  (Why would one have two formatter configs for every language?)
"prettier": ...
```

**Comment by mrnugget** [comment]
> But instead of using `Prettier`, we should merge that two configs into one.

This is orthogonal to this ticket, but I don't understand why we should do this.

`formatter` specifies which formatter to use globally/per-language, `prettier` specifies which options to pass to prettier if/when it's used.

**Comment by failable** [comment]
@mrnugget  Maybe I misunderstood what `Prettier` is, I have thought the config should be like

```
      "formatter": {
        "external": {
          "command": "prettier",
          "arguments": ["options to pass to prettier "]
        }
      }
```

**Comment by mrnugget** [comment]
We do have prettier built-in, so it's not really an external command like the others. That's why we have 3 options (language server, prettier, external command).

**Comment by failable** [comment]
> We do have prettier built-in

Didn't know that, thanks for the information.

**Comment by magician11** [comment]
> We do have prettier built-in, so it's not really an external command like the others. That's why we have 3 options (language server, prettier, external command).

I wanted to customise prettier to use single quotes.

`{
  "singleQuote": true
}
`

But just creating a `.prettierrc` at the root of the project with that JSON didn't work. I don't fully understand what it means that prettier is built-in, but to get the editor to recognise my customisations, I needed to..

1. update my settings.json file

```
{
  "features": {
    "copilot": false
  },
  "theme": "One Light",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "languages": {
    "JavaScript": {
      "format_on_save": {
        "external": {
          "command": "prettier",
          "arguments": ["--stdin-filepath", "{buffer_path}"]
        }
      }
    }
  }
}
```

2. also install prettier globally

`pnpm add -g prettier`

Then it recognises my `.prettierrc` file, and formats as I would like it to on save.

**Comment by eproxus** [comment]
I don't know if this ever worked, but this has a regression in Zed 0.176.1. If I create a new unsaved buffer and set the language to JSON and format it nothing happens.

**Comment by bennetbo** [comment]
https://github.com/user-attachments/assets/4b8a976b-0cf2-4077-9848-4c94d5dc1c32

Works fine for me, do you have anything in the logs? What does you're settings.json look like?

**Comment by eproxus** [comment]
@bennetbo Thanks for the reply and screen recording! After checking it was a false alarm. Apparently I was missing the explicit Prettier config for JSON 🤦
