### ISSUE TITLE
HTML Tags Auto-Rename

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#4535]
### Check for existing issues

- [X] Completed

### Describe the feature

Add a setting that allows linked editing of HTML tags.

The request comes from [this discussion post](https://github.com/zed-industries/community/discussions/1905).

**Comment by sohcfst** [comment]
+1 👍 to this issue! It's the one feature stopping me from using Zed - more than happy to try and learn Rust and whip up a plugin once Zed becomes extensible though!

**Comment by osiewicz** [comment]
I've looked into this following https://x.com/iangrayhazzard/status/1792720672701268178 and it seems like we just don't do renaming for HTML language server?
VSCode sends out a request for rename according to LSP spec whereas we do.. nothing. Triggering "Rename Symbol" on HTML tag does nothing; no communication, nada, null.
I'll look into why that is. I suspect that the "linked editing" bit comes from language server itself.

**Comment by corneliusio** [comment]
Is there a way to disable this in settings? It's causing some minor issues for me. One it adds a space to the closing tag if you go to add attributes on the opening tag. Plus I'm so accustomed to using multi-cursor for this that I end up causing this feature to duplicate every keystroke.

**Comment by osiewicz** [comment]
@corneliusio 
Sure, you can disable it with:
```
"languages": {
  "language-you-want-to-disable-linked-editing-for":
    {
      "linked_edits": false
    }
}
```

**Comment by corneliusio** [comment]
@osiewicz 🙏🏼 Thank you!
