### ISSUE TITLE
Show focused symbol on the scrollbar

### ISSUE THREAD

**Issue by fxsalazar** [zed-industries/zed#4538]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be exactly the same as the search but when focusing a symbol.

### If applicable, add mockups / screenshots to help present your vision of the feature

When focusing, it is highlighted on the code but not shown on the scrollbar:
<img width="1058" alt="Screenshot 2023-08-12 at 16 05 57" src="https://github.com/zed-industries/community/assets/2998771/871f868d-238e-4f08-a6c8-d73b179d6710">

When searching, all the matches are shown:
<img width="1137" alt="Screenshot 2023-08-12 at 15 58 49" src="https://github.com/zed-industries/community/assets/2998771/705b797f-34ea-4bd0-a924-f4c62b05c317">

**Comment by alygin** [comment]
@fxsalazar , @JosephTLyons , shouldn't this one be closed because of #7029?

**Comment by JosephTLyons** [comment]
Looks like it! Thanks!
