### ISSUE TITLE
ruff-lsp

### ISSUE THREAD

**Issue by stalexsm** [zed-industries/zed#4539]
### Check for existing issues

- [X] Completed

### Describe the feature

Is ruff-lsp supported for python in zed. If supported, can I find out an example of the settings?
If not supported, are there plans to add ruff-lsp support?

**Comment by bersace** [comment]
There's now a ruff language server in ruff extension.

It supports formatting but not import sorting.

**Comment by JosephTLyons** [comment]
As @bersace said, we have an extension now, so I'm going to close this issue out!

<img width="992" alt="SCR-20240728-doqx" src="https://github.com/user-attachments/assets/32122658-b26a-4882-afd3-0f33336e143e">
