### ISSUE TITLE
Zed should watch relevant project files (e.g. .gitignore)

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#4545]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If `.gitignore` is changed on disk, Zed will not notice immediately. For example, cmd+p will still search on newly ignored directories.

Opening a new file, or editing the current appears to make Zed aware of the change. 

### Environment

Zed: v0.98.2 (stable)
OS: macOS 13.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
At some point in the last year this behavior was implemented and Zed will watch .gitignore and immediately update the project panel to reflect ignored files when .gitignore is updated.

Thanks for reporting!
