### ISSUE TITLE
Set Assistant panel default model (to GP4)

### ISSUE THREAD

**Issue by dctanner** [zed-industries/zed#4547]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to be able to set the default model the Assistant panel uses to gpt-4, so I don't have to click it every time to change.

**Comment by Moshyfawn** [comment]
I believe you can already do this by providing the assistant config `default_model`.

```json
{
  "assistant": {
    "provider": {
      "type": "openai",
      "api_url": "https://api.openai.com/v1",
      "default_model": "gpt-4-1106-preview"
    }
  }
}
```

Moreover, the `gpt-4-1106-preview` is currently the default model without providing the config.

I'll close this as resolved.
