### ISSUE TITLE
Outline view show wrong structure of TypeScript class

### ISSUE THREAD

**Issue by futurist** [zed-industries/zed#4553]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The repo:  https://github.com/microsoft/vscode
The file: https://github.com/microsoft/vscode/blob/main/src/vs/base/common/lifecycle.ts
The Bug: displayed the incorrect outline of the typescript class, see the attached image.

### Environment

MacOS 13.4
Zed Preview 0.97.5

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/community/assets/159167/3c9e43b6-c56b-4757-b85e-cb2462f20bf1)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by coolemur** [comment]
+1. Outline view is weird. Not only in ts files, but in other filetypes as well.

For comparison, VSC lists all members of .tsx, while Zed outline shows only top-nested function (usually single member) and skips all members that are inside that function. Html outline doesn't work at all, .svelte as well.

**Comment by coolemur** [comment]
Yes. This is still an issue with Zed. Outline shows only top level members. While in VS Code it's show as expandable tree to navigate nested members.

Checked this after updating to a Preview version of Zed.
