### ISSUE TITLE
Incorrect control-A and control-E behavior with soft_wrap

### ISSUE THREAD

**Issue by sethherr** [zed-industries/zed#4554]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing a file that with soft wrapping:

- control-e goes to the end of the soft-wrap line
- control-a goes to the beginning of the soft-wrap line

These should go to the beginning and end of the _line_, not the soft wrapped character limit.

control-k behaves correctly, and deletes to the end of the line, rather than the soft-wrap line.

### Environment

Zed: v0.97.5 (stable)
OS: macOS 13.4.1
Memory: 32 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I don't like Zed's handling of `ctrl-e` and `ctrl-a` with soft-wrap enabled. It is surprising that behavior changes depending on the width of my editor pane: "ctrl-e goes to the end of the line, unless your window is narrow and then you have to press ctrl-e twice".

So I took a survey:

Editors that ignore soft wrap when jumping to the beginning/end with `ctrl-a`/`ctrl-e`
- Chrome on MacOS (e.g. this textbox on GitHub)
- TextEdit
- EMacs
- VSCode
- Atom
- Sublime
- Lapce (broken, but it tries)

Same as Zed (double tap when navigating thru a word wrap):
- GNU nano (`esc $` to enable softwrap) 
- Kate 
- IntelliJ (kinda broken). First `ctrl-e` goes to the last non space at end of the soft-wrapped line. A second `ctrl-e` moves one character over after the trailing space. A third `ctrl-e` will jump you to the real end of the line.

**Comment by notpeter** [comment]
This is now supported via custom keymap.  Here's what I use:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "home": ["editor::MoveToBeginningOfLine", { "stop_at_soft_wraps": false }],
      "end": ["editor::MoveToEndOfLine", { "stop_at_soft_wraps": false }],
      "cmd-left": ["editor::MoveToBeginningOfLine", { "stop_at_soft_wraps": false }],
      "ctrl-a": ["editor::MoveToBeginningOfLine", { "stop_at_soft_wraps": false }],
      "cmd-right": ["editor::MoveToEndOfLine", { "stop_at_soft_wraps": false }],
      "ctrl-e": ["editor::MoveToEndOfLine", { "stop_at_soft_wraps": false }]
    }
  }
]
```
