### ISSUE TITLE
Missing folders icons on initial load

### ISSUE THREAD

**Issue by sunilshenoy** [zed-industries/zed#4584]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After each update to the Preview release, the initial load of sidebar does not display the folder icon. 

Clicking on one of the folder names though, causes the folder view to update and all the folder icons are visible.

### Environment

Zed: v0.97.4 (preview)
OS: macOS 13.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/12189069/Zed.log)

**Comment by Moshyfawn** [comment]
I believe this is no longer an issue. Feel free to report if you're still seeing it.
