### ISSUE TITLE
Add command to toggle hard wrap/unwrap paragraphs

### ISSUE THREAD

**Issue by Yevgnen** [zed-industries/zed#4588]
### Check for existing issues

- [X] Completed

### Describe the feature

The command should work for current block/graph of texts based on `"preferred_line_length"`. For example

```
The English Wikipedia is the primary[a] English-language edition of Wikipedia, an online encyclopedia. It was created by Jimmy Wales and Larry Sanger on January 15, 2001, as Wikipedia's first edition.

English Wikipedia is hosted alongside other language editions by the Wikimedia Foundation, an American non-profit organization. Its content is written independently of other editions[1] in various varieties of English, aiming to stay consistent within articles. Its internal newspaper is The Signpost.

English Wikipedia is the most-read version of Wikipedia[2] and has the most articles of any edition, at 6,689,175 as of July 2023.[3] It contains 10.9% of articles in all Wikipedias,[3] although it lacks millions of articles found in other editions.[1] The edition's one-billionth edit was made on January 13, 2021.[4]
```

If the cursor in the second block of text, toggling hard wrapping should turn the text into 

```
The English Wikipedia is the primary[a] English-language edition of Wikipedia, an online encyclopedia. It was created by Jimmy Wales and Larry Sanger on January 15, 2001, as Wikipedia's first edition.

English Wikipedia is hosted alongside other language editions by the
Wikimedia Foundation, an American non-profit organization. Its content
is written independently of other editions[1] in various varieties of
English, aiming to stay consistent within articles. Its internal
newspaper is The Signpost.

English Wikipedia is the most-read version of Wikipedia[2] and has the most articles of any edition, at 6,689,175 as of July 2023.[3] It contains 10.9% of articles in all Wikipedias,[3] although it lacks millions of articles found in other editions.[1] The edition's one-billionth edit was made on January 13, 2021.[4]
```

toggling again should go back to the original text.

**Comment by bersace** [comment]
Keybinding on Emacs is `alt-q`.

**Comment by zakj** [comment]
Similar to [zed-industries/extension#515](https://github.com/zed-industries/extensions/issues/515).

**Comment by notpeter** [comment]
Zed v0.154.x has support for rewrap:
- https://github.com/zed-industries/zed/pull/17909

This is available now in Zed Preview and in Zed Stable on Wednesday.

I'm going to leave this open for the additional functionality of being able to `unwrap` multiple hard wrapped lines into a single line.

**Comment by ConradIrwin** [comment]
We already support unwrap through `J` or `:join`

**Comment by osa1** [comment]
@Yevgnen at least in vim mode, `editor:join lines` doesn't require selecting the lines. If it does without the vim mode then perhaps that's a bug.

The reflow command is still less than ideal IMO. In vim `gq` joins short lines and rewraps. In Zed you have to manually join the short lines, except it's not smart enough to remove the comment syntax when you do that, so you get `// a // b` when you join two comment lines `// a` and `// b`.

I've checked the follow-up tasks in https://github.com/zed-industries/zed/pull/17909#issuecomment-2368857682 but this isn't in the list. We should probably file a feature request..

**Comment by taylorthurlow** [comment]
> The reflow command is still less than ideal IMO. In vim `gq` joins short lines and rewraps. In Zed you have to manually join the short lines, except it's not smart enough to remove the comment syntax when you do that, so you get `// a // b` when you join two comment lines `// a` and `// b`.

This does not match with how I'm experiencing usage of `gq` in vim mode with Zed, it has no trouble shortening your exact example into both `// a b` and `# a b` for JavaScript and Ruby, respectively.

**Comment by aleclarson** [comment]
In TypeScript, the `Editor::Rewrap` command works with single-line comments grouped together, but not with multi-line comment blocks.

```ts
/**
 * Multi-line comment block that should be split into two lines when Editor::Rewrap is used.
 */

// Single-line comments grouped together are properly split when Editor::Rewrap is used.
// Give it a try.
```

**Comment by austinorth** [comment]
Just for anyone else who stumbles upon this issue, I just added the following to my keybindings and it enabled the `gq` functionality that I was looking for.

```json
  {
    "context": "Editor",
    "bindings": {
      "gq": "vim::Rewrap"
    }
  },
```
