### ISSUE TITLE
Move to first / last line in Intellisense popup window.

### ISSUE THREAD

**Issue by jezikk** [zed-industries/zed#4592]
### Check for existing issues

- [X] Completed

### Describe the feature

If the user press key UP when the first item is focused in the intellisense suggestion, the focus should move to the last item.
<img width="413" alt="up" src="https://github.com/zed-industries/community/assets/7671531/a9397226-92e4-467b-8b47-9d398714aa84">

If the user press key DOWN when the last item is focused in the intellisense suggestion, the focus should move to the first item.
<img width="375" alt="down" src="https://github.com/zed-industries/community/assets/7671531/27a1e5bc-0087-4976-aa2e-6dce78303557">

**Comment by JosephTLyons** [comment]
It looks like this feature is now in current Zed:


https://github.com/user-attachments/assets/b774a5c4-e121-412a-a279-31a3d848e37d
