### ISSUE TITLE
LSP Support for Elm

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#4595]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/elm-tooling/elm-language-server

**Comment by w0rm** [comment]
:wave:

@absynce and I are trying to make it work with some help from @razzeee, the maintainer of elm-language-server. 

The basic integration seems to be working fine, just need to fix some errors and propagate configuration options.

![elm-lsp](https://github.com/zed-industries/zed/assets/43472/a107cba9-cf9a-45b6-bb13-a866956abbb7)
