### ISSUE TITLE
PHP rename variable does not work

### ISSUE THREAD

**Issue by RemcoSmitsDev** [zed-industries/zed#4596]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you try to rename a variable name using one of the following methods below, and confirm the rename, the variables don't get replaced.

#### Using shortcut
1. click on variable
2. press FN + F2 (maybe VS Code shortcut)
3. rename variable name
4. press enter to confirm rename

#### Using the command pallet
1. execute command: `editor: rename`
5. rename variable
6. execute command: `editor: confirm rename`

### Environment

Zed: v0.96.2 (preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/62463826/5d52ac9f-33d8-4703-9cd4-1ae365e29cf8

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by RemcoSmitsDev** [comment]
This does work when you have the correct license file.

**Comment by gabrielbidula** [comment]
I encountered the same problem because I named the file "license.txt" instead of "licence.txt." Once corrected, I was able to access premium Intelephense features.

`2024-02-15T21:18:29+00:00 [INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Intelephense premium features enabled."
`

**Comment by xtrasmal** [comment]
https://github.com/xtrasmal/zed-lsp-phpactor

Phpactor is king.
I need to get this extension working still.

Yesterday I installed this next to the current PHP extension and got none reproducible awesome refactors finally working(stopped working after some config tinkering).

Fantastic Code actions:
![image](https://github.com/user-attachments/assets/7dbf5587-dc3e-4b4c-9638-5917a1b1f228)

![image](https://github.com/user-attachments/assets/a40d2ea2-a944-4836-8b60-611ce479344a)

![image](https://github.com/user-attachments/assets/821e481a-2573-4aee-9f8e-7cdbb0e27788)
