### ISSUE TITLE
Cmd+P search files should also search for opened files regardless of gitignore

### ISSUE THREAD

**Issue by futurist** [zed-industries/zed#4599]
### Check for existing issues

- [X] Completed

### Describe the feature

After opening some files from node_modules, in a node.js repo, list of Cmd+P search files don't include the opened files in `node_modules` because it's git-ignored.

The opened files should be listed when searching for files, even if they're git-ignored.

**Comment by notpeter** [comment]
I am no longer able to reproduce this issue and I believe it has been fixed.
If this is incorrect, please comment and I'm happy to reopen.
Thanks!
