### ISSUE TITLE
Hover tooltip does not respect `buffer_line_height`

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4601]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure if this is a bug. 

But since the hover tooltip shares the same font family and font size with the buffer. I think it should also use the same line height of the buffer?

### Environment

Zed: v0.96.2 (preview)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
@failable Could you clarify what you mean by "hover tooltip"? A screenshot of which element you're referring to would be very helpful.

**Comment by maxdeviant** [comment]
In our popovers in the editor we do seem to respect the buffer line height:

`"buffer_line_height": "standard"`

<img width="688" alt="Screenshot 2024-03-12 at 3 26 30 PM" src="https://github.com/zed-industries/zed/assets/1486634/7997fcb5-71cc-41a7-a18a-34fa8c54d0ca">

`"buffer_line_height": "comfortable"`

<img width="707" alt="Screenshot 2024-03-12 at 3 26 40 PM" src="https://github.com/zed-industries/zed/assets/1486634/4610b184-4bd0-44c8-8275-c3abb074c61a">

**Comment by failable** [comment]
It seems the issue does not exist in the latest version any more. I'm going to close this issue.
