### ISSUE TITLE
Removing empty brackets

### ISSUE THREAD

**Issue by jezikk** [zed-industries/zed#4605]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Language: TSX

If I add an empty React props using **intellisense** and then remove the first bracket, only the first bracket is removed. If I create empty brackets manually and then remove the first bracket, both brackets are correctly removed. The same use case can be applied to "".

### Environment

Zed: v0.95.3 (stable)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/7671531/277128d6-2d8f-4694-85e1-575932513477

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by weartist** [comment]
@JosephTLyons I want to submit a PR to fix this, is that okay?

**Comment by weartist** [comment]
I've found some of the problem, for the current cursor-matched parenthetical combinations, we add them to the current parenthetical array when we press the key to enter the event:
deal input
https://github.com/zed-industries/zed/blob/176f63e86eefeaf1673ca2bc25a2dec3fbc4c126/crates/editor/src/editor.rs#L2276
add to vec
https://github.com/zed-industries/zed/blob/176f63e86eefeaf1673ca2bc25a2dec3fbc4c126/crates/editor/src/editor.rs#L2439

But for copilot autocomplete, we don't have that method in the stack of methods we insert the content, but call a separate method, so these processes are not performed:
https://github.com/zed-industries/zed/blob/176f63e86eefeaf1673ca2bc25a2dec3fbc4c126/crates/editor/src/editor.rs#L4031

I think a good way to do it is to modify the editor input no matter what happens, and some processing time needs to be performed, but this requires reorganizing the current `handle_input method`, and extracting the parts that need to be updated after each input, and then letting the `insert_snippet` call this part of the method, and other, which is a bit troublesome, and the temporary solution may be to just add the processing again after the `insert_snippet`

**Comment by mrnugget** [comment]
Hey! Just so I understand this correctly: this is only about the case when accepting autocomplete-suggestions, right?

**Comment by jezikk** [comment]
Yes, I think so.
