### ISSUE TITLE
Add possibility to copy text from hover tooltip

### ISSUE THREAD

**Issue by jezikk** [zed-industries/zed#4606]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to add a possibility to select and copy a text from the hover tooltip. Currently, the hover tooltip is closed when it is clicked. For example in some cases in Typescript, it is faster to copy the type than to write it manually.

### If applicable, add mockups / screenshots to help present your vision of the feature

Zod:
<img width="787" alt="zed" src="https://github.com/zed-industries/community/assets/7671531/8cd84246-5cdf-42e7-be1c-1a392cc2690c">

VSCode - selected text which is possible to copy:
<img width="944" alt="vscode" src="https://github.com/zed-industries/community/assets/7671531/e4037682-9077-437f-a160-a1ffe1dca782">

Error message - copy error message and paste into the browser
<img width="937" alt="vscode_error" src="https://github.com/zed-industries/community/assets/7671531/61769c58-a549-40ef-aa2f-93496ca6bb2b">

Eslint message - copy eslint rule
<img width="735" alt="vscode_eslint" src="https://github.com/zed-industries/community/assets/7671531/1e5191fe-c56a-41c4-b0f0-b8734d8c19c0">

**Comment by lcptrs** [comment]
As a vim user I'd love to see this to be navigateable via the keyboard. In vim I can simply press `ctrl-w-w` to jump in and out of the tooltip and while being inside I can navigate with vim movements and yank text using them.

**Comment by JosephTLyons** [comment]
This issue is a bit old, but it is still a valid issue - however, I realized that when triaging it before, I forgot that we already had an issue for this. I'm going to close this in favor of:

- https://github.com/zed-industries/zed/issues/5236

For anyone subscribed to this thread wanting this feature, please upvote #5236!

**Comment by ttenbrinkzenz** [comment]
While #5236 allows copying with mouse, as far as I'm aware it's not possible to copy with keyboard only?
