### ISSUE TITLE
unable to use `shift shift` as a shortcut

### ISSUE THREAD

**Issue by Yneth** [zed-industries/zed#4615]
### Check for existing issues

- [X] Completed

### Describe the feature

As a user I want the Zed editor to support the `shift shift` shortcut to start searching everywhere.
Not particularly interested in the search everywhere functionality. Mainly interested in shortcut to work.

#### Expected behavior:
`shift shift` performs assigned shortcut.

#### Actual behavior:
nothing happens. All shortcuts defined after the definition of `shift shift` stop working

**Comment by styx** [comment]
@JosephTLyons curious how hard would it be to implement this feature?

**Comment by JosephTLyons** [comment]
I don't really have a good idea of how much of a lift this would be, but my gut instinct says it would require some significant changes, as I don't think any of our keybinding logic is set up to listen for multiple taps on a modifier key, but I could certainly be wrong.

**Comment by JosephTLyons** [comment]
Even though this issue is older, there are more upvotes on this issue, so I'm going to close this one out in favor of it:

- https://github.com/zed-industries/zed/issues/6460

Please upvote this issue with a 👍 emoji!

**Comment by JosephTLyons** [comment]
This is now in [preview](https://zed.dev/releases/preview)!
