### ISSUE TITLE
vim keymap: is it possible?

### ISSUE THREAD

**Issue by futurist** [zed-industries/zed#4622]
In vscode there's project: https://github.com/VSCodeVim/Vim to enable VIM keys only for editor.
Is it possible to only enable keymap in editor mode of Zed for using VIM keymaps?

**Comment by notpeter** [comment]
We have since launched [Zed Vim Mode](https://zed.dev/docs/vim).  Please try it out (cmd+shift+p "workspace: toggle vim mode") and let us know what you think.

P.S. You might also enjoy this: https://zed.dev/blog/zed-decoded-vim
