### ISSUE TITLE
CJK chars aren't wrapped correctly

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4623]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Line wraps only happen in spaces now and do not break on CJK chars. See the screenshots below for comparison with Emacs.

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed: (Note how the paragraphs are wrapped at whitespaces after list bullets and English words.)
<img width="654" alt="image" src="https://github.com/zed-industries/community/assets/5475262/a5c88887-0f3a-4bc3-b707-5b7c45b5a400">

Emacs:
<img width="649" alt="image" src="https://github.com/zed-industries/community/assets/5475262/e1adf650-1e2b-4ec7-ae93-7028b5d27a3b">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by aukw** [comment]
This problem  also appears on my macOS. I have tried v0.87.6/v0.104/v0.117/v0.122.2 Preview, It exists in all these versions. And I find it existing in Textmate/Geany too.

<img width="485" alt="ScreenShot 2024-02-14 at 10 20 19" src="https://github.com/zed-industries/zed/assets/822144/f70e9d5e-8459-4380-9757-be62cc8119eb">

**Comment by failable** [comment]
Fixed in

```
Zed: v0.154.1 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: x86_64
```
