### ISSUE TITLE
squiggly lines too big / looks bad

### ISSUE THREAD

**Issue by kwando** [zed-industries/zed#4625]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This kinda superficial , but I fund the squiggly lines to look bad. They are way to big for my liking.

![Skärmavbild 2023-07-15 kl  12 54 27](https://github.com/zed-industries/community/assets/891566/fcdd4f65-4523-48fd-bca0-f0458c146b54)

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.4.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is from vs code:
![Skärmavbild 2023-07-15 kl  12 57 47](https://github.com/zed-industries/community/assets/891566/07480a3e-4209-44d8-988b-46e74e976e11)
compared to zed:
![Skärmavbild 2023-07-15 kl  12 54 27](https://github.com/zed-industries/community/assets/891566/10ad59cf-e91f-45f6-ad99-4dd9d70ba6e6)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bryanbuchanan** [comment]
I came across this same issue. Squiggles look great on a MBP, but are larger on a 72ppi monitor. I don't mind the larger squiggles *too* much, but they *are* getting cropped along the bottom when they're this large.

![Screenshot 2024-04-24 at 12 52 36 PM](https://github.com/zed-industries/zed/assets/1747699/b9d89664-660c-4de6-a73b-d1dec7cb8b0a)
