### ISSUE TITLE
Better inlay hint faces

### ISSUE THREAD

**Issue by liebkne** [zed-industries/zed#4626]
### Check for existing issues

- [X] Completed

### Describe the feature

The new inlay hints feature is great. But all themes use bold face for it. This causes the hints to draw too much attention.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="744" alt="Screenshot 2023-07-15 at 18 38 47" src="https://github.com/zed-industries/community/assets/5475262/0104c948-680e-4883-abd4-508fde68f337">

**Comment by spartanatreyu** [comment]
Here's another example of "muted" inlay hints, this time from vscode (with the monokai theme, with visible whitespace characters, rainbow indents, and rainbow brackets):

![vscode screenshot](https://github.com/zed-industries/zed/assets/3240456/90c6c51e-c45c-4fd4-a818-4acb28f3fbd4)

**Comment by SomeoneToIgnore** [comment]
Hints' boldness was removed in https://github.com/zed-industries/zed/pull/8283 so seems that this issue can be closed.
