### ISSUE TITLE
Show visual diff / rollback options when clicking changed lines indicator

### ISSUE THREAD

**Issue by tychedelia** [zed-industries/zed#4630]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, there are visual indicators of diffs to a file to the left of line numbers that show additions, deletions, etc. I would like to click this indicator and show the diff hunk of what changes, as well as have some quick options to operate on that hunk, primarily rollback.

Example from IntelliJ, clicking the "back" arrow will roll this line back to what's shown in the diff:
<img width="565" alt="image" src="https://github.com/zed-industries/community/assets/10366310/972d74e7-d94c-476a-b332-e203a706146a">

**Comment by amatiash** [comment]
I'm also missing this feature! Looking forward to it!

**Comment by JosephTLyons** [comment]
Zed now can show the diff inline and we have a few options for reverting the hunk or the full file:

<img width="470" alt="SCR-20240728-dknf" src="https://github.com/user-attachments/assets/85729913-23d4-40d4-9099-6956065145cc">

I'm going to close this issue out, please open new issues if you there is more functionality wanted here.
