### ISSUE TITLE
Add key binding for opening a file from ProjectPanel context

### ISSUE THREAD

**Issue by jezikk** [zed-industries/zed#4632]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have a key binding for opening a file from the ProjectPanel context. Actually if I change the current key binding "project_panel::Rename" from default value to "Enter" key, it's not possible to open any file in project panel using keyboard.

**Comment by Moshyfawn** [comment]
There's `"space": "project_panel::Open"`.
