### ISSUE TITLE
Sidebar file focus

### ISSUE THREAD

**Issue by sgnilreutr** [zed-industries/zed#4643]
### Check for existing issues

- [X] Completed

### Describe the feature

You have multiple files open, you switch from one file to the other via the file viewer, the sidebar will focus on on the same item.

In other words, the sidebar follows the focus view of the user so it matches the focused file in the editor.

**Comment by Moshyfawn** [comment]
I believe this is now working as requested.

https://github.com/zed-industries/zed/assets/16290753/d019d739-66c9-43b9-8022-3c677ac1fb88
