### ISSUE TITLE
gopls support settings

### ISSUE THREAD

**Issue by leeyongda** [zed-industries/zed#4660]
### Check for existing issues

- [ ] Completed

### gopls support settings
https://github.com/golang/tools/blob/master/gopls/doc/settings.md

#### example: support go package autoimport
![20230625101129](https://github.com/zed-industries/community/assets/11832476/6f13ddbb-700c-4376-b133-6d880c063ee9)

#### example: not support go package autoimport :
![20230625102115](https://github.com/zed-industries/community/assets/11832476/03aed014-0c70-418d-9ba9-b788aa57a1d5)

### If applicable, add mockups / screenshots to help present your vision of the feature

expect example：
![20230625101755](https://github.com/zed-industries/community/assets/11832476/34f3c998-ab48-4667-bf05-57fc1c793d89)

**Comment by mrnugget** [comment]
You can specify `buildFlags` like this in your settings.json:

```jsonc
{
    "gopls": {
      // "binary": {
      //   "path": "/Users/thorstenball/bin/gopls",
      //   "arguments": ["-debug=0.0.0.0:9090"]
      // },
      "initialization_options": {
        "usePlaceholders": true,
        "buildFlags": ["-tags=debug"],  // <--------------- buildFlags!
        "completeUnimported": true,
        "experimentalPostfixCompletions": true,
        "hints": {
          "assignVariableTypes": false,
          "compositeLiteralFields": false,
          "compositeLiteralTypes": false,
          "constantValues": true,
          "functionTypeParameters": true,
          "parameterNames": true,
          "rangeVariableTypes": true
        }
      }
    }
  }
}
```

And auto-importing also works out of the box:

![screenshot-2024-04-16-14 26 51@2x](https://github.com/zed-industries/zed/assets/1185253/00df5fa9-839f-4cd7-812b-fc86c1223ec0)

So I think we can close this.

**Comment by AlexisZankowitch** [comment]
I confirm that @mrnugget config is working like a charm for me 🤩 
Thanks a lot !!

**Comment by dundee** [comment]
Works for me as well. Thanks!

Just note for others: the config needs to be placed inside `pls` block.
For example:

```json
{
  "theme": "One Dark",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "lsp": {
    "gopls": {
      "initialization_options": {
        "buildFlags": ["-tags=or_e2e,or_int,or_test"]
      }
    }
  }
}
```

**Comment by mrnugget** [comment]
Woops, sorry about that @dundee! Updated it.

**Comment by benbenbang** [comment]
> ```js
> usePlaceholders
> ```

Hello @mrnugget 

I was searching Zed's official gopls docs, and I found this post and see you put the config: `usePlaceholders`

Does it really work? I tried to disable it, but it's not working.

Do you mind sharing whether it works in your Zed? Thanks

**Comment by mrnugget** [comment]
`usePlaceholders` is the default by now: https://github.com/zed-industries/zed/blob/83592306c519266814cacdf8a6abfed6b283c01d/crates/languages/src/go.rs#L237 Well, since this PR: https://github.com/zed-industries/zed/pull/7780

It works for me:

https://github.com/zed-industries/zed/assets/1185253/309723ca-f42f-49bb-b393-a4f7776495c4

Do you want to disable it?

**Comment by benbenbang** [comment]
Yes, I tried setting it to false here and there. None of them worked. Do you confirm that disabling also works on your side?

**Comment by mrnugget** [comment]
Disabling works for me:

https://github.com/zed-industries/zed/assets/1185253/f622e234-811b-4094-b4df-08cf6106b72f

These are the `settings.json` I used:

```json
{
  "vim_mode": true,
  "lsp": {
    "gopls": {
      "initialization_options": {
        "usePlaceholders": false
      }
    }
  }
}

```

**Comment by benbenbang** [comment]
Thank you @mrnugget 
I finally found out why it didn't work for me. A stupid mistake:
Since `rust-analyzer` is the first object in the `lsp`, I accidentally put the `gopls` to the same level as `lsp` instead of the same as `rust-analyzer`. So that's also why I cannot figure out why other lsp doesn't work...
Thanks again 🙏🏻

**Comment by mrnugget** [comment]
Great you found it and, ugh, sorry to hear you bumped into this. Will look into whether we can make the settings show an error.

**Comment by vizh** [comment]
The option with global settings for Zed helps, but if you work with multiple projects that actively use tags, you constantly have to adjust the global settings. It would be great to have the ability to define them for each specific project.
