### ISSUE TITLE
Unable to drag file to dock

### ISSUE THREAD

**Issue by mattbaker** [zed-industries/zed#4665]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I could be making a mistake, but [the website](https://zed.dev/features) makes me think I can drag a file to the dock.

>  By default it opens with a terminal but any editor or tab may be dragged into it.

But I see this [recent blog post](https://zed.dev/blog/new-panel-system) is more focused on the idea of a terminal dock and a project dock, and less the general idea of a dock, so maybe the design goals of the dock shifted.

I don't have a strong opinion on whether or not docking files should be possible, but if it's no longer a feature it'd be good to update the website. The website also refers to the old shift-esc shortcut that I believe has been replaced with ctrl-`.

### Environment

Zed: v0.90.2 (stable)
OS: macOS 12.6.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![move-to-dock](https://github.com/zed-industries/community/assets/55462/f8689f82-65db-49f9-b80f-2440361703ae)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
This is not currently supported in Zed, you cannot drag a file into the Bottom dock and only Terminal tabs are supported in the bottom dock.

As a work around you can drag terminal tabs out of the bottom dock in the center editor which can support all types of tabs (Terminal tabs, file tabs, assistant tabs) co-mingled and you can hide the bottom dock with `cmd-j`.

Thanks for reporting!
