### ISSUE TITLE
Support git worktree

### ISSUE THREAD

**Issue by dangh** [zed-industries/zed#4670]
### Check for existing issues

- [X] Completed

### Describe the feature

[git worktree](https://git-scm.com/docs/git-worktree) is a great way to work on multiple branches simultaneously without multiple clones of the same repo, especially huge repos.

Inside a git worktree, the .git is not a directory but a text file with pointer to the git dir. An example:

```sh
cat .git
gitdir: /Users/t/Desktop/test/.git/worktrees/test-branch
```

Zed doesn't understand git worktree so it doesn't track modified files at all.

**Comment by stefanluptak** [comment]
@dangh is this working for you now with the Zed Preview? It's not for me.

**Comment by mrnugget** [comment]
@stefanluptak any steps to reproduce? See this as an example: https://github.com/zed-industries/zed/issues/19842#issuecomment-2442173803

**Comment by stefanluptak** [comment]
Hey @mrnugget, yes. The problematic part seems to be the `--bare` option when cloning the repo. Without that, it's showing the blame correctly.

```bash
git clone --bare git@github.com:stefanluptak/stefanluptak.github.io.git
cd stefanluptak.github.io.git
git worktree add main
cd main
zed .
```

**Comment by mrnugget** [comment]
I see, so it's the `--bare` part that doesn't work then?

**Comment by stefanluptak** [comment]
> I see, so it's the `--bare` part that doesn't work then?

Exactly.

- `git clone --bare <repo>` and then do git worktrees ❌ doesn't show blame in Zed
- `git clone <repo>` and then do git worktrees ✅ shows blame in Zed
