### ISSUE TITLE
Git support when opening monorepo subfolder

### ISSUE THREAD

**Issue by ajsharp** [zed-industries/zed#4672]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you open a subfolder of a monorepo in zed (a folder that does not have a `.git` directory at it's root) you lose all source control support inside zed (file navigator highlighting etc). Currently, zed expects the .git folder to be in the root. It's often nice to not have to open the entire monorepo folder.

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by esamattis** [comment]
dup https://github.com/zed-industries/zed/issues/5161
