### ISSUE TITLE
Add equivalent to VSCode "centered layout" view option.

### ISSUE THREAD

**Issue by borisgoro** [zed-industries/zed#4685]
### Check for existing issues

- [X] Completed

### Describe the feature

Add a view option that horizontally centers pane's content.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1470" alt="image" src="https://github.com/zed-industries/community/assets/65460569/a680b596-d587-404c-8daf-53fc88ed4a08">

**Comment by iamnbutler** [comment]
Now that we are open source, I'd love to see someone try to pick this up and build it 🥹

**Comment by qti3e** [comment]
This is a very nice feature. Does it also make sense to have `{"enable": true | false | "fullscreen", ... }` to allow automatically enabling/disabling this feature on/off full screen? As an ultra-wide screen user, I find having the `"enable": "fullscreen"` really useful.

I can draft up a PR for it as well.

c.c @iamnbutler

**Comment by DissolveDZ** [comment]
i think it already got merged, you can use the toggle centered layout command, but i feel like it's not an option so it won't save if you restart the editor

**Comment by JosephTLyons** [comment]
As @DissolveDZ mentioned, we do have a `workspace: toggle centered layout` action now and it is saved and restored per workspace, so it persists across app restarts:

<img width="1608" alt="SCR-20240728-dbro" src="https://github.com/user-attachments/assets/1967093b-001e-4f12-8c4c-a644108e6f4a">

**Comment by MrBns** [comment]
Zed center layout is not resizeable like vscode.

**Comment by ShalokShalom** [comment]
> As [@DissolveDZ](https://github.com/DissolveDZ) mentioned, we do have a `workspace: toggle centered layout` action now and it is saved and restored per workspace, so it persists across app restarts:


That's amazing. 🥳 

I looked into Zed again and again over the last year, 
and every time I looked, I did hope for that feature to be available. 

And since I am used to VSCode (like apparently a lot of people here), did I hope to find it in the "View" entry at the toolbar.

<img width="2880" height="1800" alt="Image" src="https://github.com/user-attachments/assets/9d177e2f-ce7d-4890-ba8e-480ffefb491e" />

Never in a million years would I have thought that to be a command action. 😲

**Comment by ShalokShalom** [comment]
> Zed center layout is not resizable like vscode.

It is resizable, just not as intuitive as in VSCode. 

Go to the settings: 

<img width="2880" height="1800" alt="Image" src="https://github.com/user-attachments/assets/dcce4cf8-3b67-4510-94b8-114d442d851a" />

**Comment by VihangaFTW** [comment]
Please make it resizable like vscode. That's the whole point of the centered layout for me.
