### ISSUE TITLE
Add GitHub link to zed.dev website

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4690]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add somewhere an easy link that could take website user to Zed's GitHub page.

### If applicable, add mockups / screenshots to help present your vision of the feature

![github_link](https://github.com/zed-industries/community/assets/4711498/de34959b-4eb6-419a-b155-7a002bccfbc5)

**Comment by maxdeviant** [comment]
There is now a link to the GitHub repo on the homepage:

<img width="1530" alt="Screenshot 2024-01-25 at 11 02 59 AM" src="https://github.com/zed-industries/zed/assets/1486634/b7e33411-ed0c-42f3-bfc3-e2581342b6c6">
