### ISSUE TITLE
`extend_comment_on_newline` does not apply to vim mode's `o`

### ISSUE THREAD

**Issue by ThreeFx** [zed-industries/zed#4691]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the cursor is on a comment, and I press `o`, then there are no comment characters inserted on the next line, even though I've set `extend_comment_on_newline` to `true`.

```
// This is a comment
      ^
      cursor position
```

then, after hitting `o`, I expect to see the following

```
// This is a comment
// 
   ^
   cursor position
```

However, no such thing happens, and the line is left empty, with the cursor at the start of a new, empty (and also unindented) line.

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by osa1** [comment]
> We're working to clean up our issue tracker by closing older issues that might not be relevant anymore. Are you able to reproduce this issue in the latest version of Zed?

Yes, this issue still exists.
