### ISSUE TITLE
 In the integrated terminal, swiftly tapping the "Up + Enter" keystroke combination will overlook the Enter

### ISSUE THREAD

**Issue by zhylmzr** [zed-industries/zed#4693]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not solely limited to the carriage return key, any swift combination involving the "Up" or "Down" keys (for browsing terminal history) will be overlooked.

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/15730824/2b9e6c8e-2ed0-43f8-b6ab-648850c087c2

By way of comparison, in the external terminal, the identical procedure yields the following outcome.

https://github.com/zed-industries/community/assets/15730824/465f3c70-c48c-4b9d-9428-bb681fe7fc53

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by N8th8n8el** [comment]
I cannot reproduce this. Maybe this has been fixed?

**Comment by zhylmzr** [comment]
Yeah, looks like it's been fixed.
