### ISSUE TITLE
Missing VS Code keybindings for duplicating and moving lines

### ISSUE THREAD

**Issue by ryanwinchester** [zed-industries/zed#4703]
### Check for existing issues

- [X] Completed

### A) Moving lines or selections

Was partially mentioned in zed-industries/zed#6079 but not addressed (and I haven't seen another issue yet with these ones).

**`alt-up`** move current line (or selected lines) up
**`alt-down`** move current line (or selected lines) down

### B) Duplicating lines or selections

**`alt-shift-up`** duplicate current line (or selected lines) above
**`alt-shift-down`** duplicate current line (or selected lines) below

### If applicable, add mockups / screenshots to help present your vision of the feature

VS Code behaviour on duplicating and moving line(s):

https://github.com/zed-industries/community/assets/2897340/a50596e6-366e-481f-b035-729939188405

**Comment by LinusU** [comment]
Slightly related, but I'm also trying to copy over all my VS Code bindings and since I couldn't find "move line up" or something similar in the documentation, I found this thread very helpful!

I also missed cmd-shift-k to delete the current line, it was easy to add:

```
  "cmd-shift-k": "editor::DeleteLine"
```

**Comment by damnsamn** [comment]
> @ryanwinchester can I close this one out given that you found the commands you were looking for? There's definitely some room for improvement, but the core functionality should all be there. 🙂

@hovsater  I'd not consider the core functionality to be there currently. 

In VS code, you can `alt-shift-up` as well as `alt-shift-down` to duplicate lines in those corresponding directions. If there were a way to chain multiple functions for one binding (eg. `["editor::DuplicateLine", "editor::MoveLineUp"]`, I think **that** would mean the core functionality is accounted for.

**Comment by carlosbaraza** [comment]
It may sound simplistic, but I think these missing shortcuts are a major blocker for adoption by VS Code users. A few of my colleagues completely dismissed Zed because it just takes some muscle memory to get used to the new shortcuts. A better strategy for Zed would be to fully match all the VS Code shortcuts out of the box, if not by default, with a simple button to get all the bindings setup. This will remove a big part of the friction.

**Comment by ryanwinchester** [comment]
> We have dedicated keymaps for other editors, including VSCode. People had added more bindings to those in PRs like #7464 (that was for Intellij, but the idea is exactly the same), so, presumably, somebody can come and add those into the VSCode keymap too? Seems like it would need less characters typed than for any of the messages above.

Is there both a duplicate line above and duplicate line below now? Or still just `"editor::DuplicateLine"`?

**Comment by ryanwinchester** [comment]
I will learn rust someday, but it's not today. `somethingsomething.unwrap().unrwap().unwrap()`

**Comment by carlosbaraza** [comment]
I didn't know Zed had some keymap files for other editors. Maybe those keybinding options could be added to a menu where a simple non contributor user could see the list of default available keymaps to quickly choose their preferred keymap without having to dig inside the Zed GitHub issues + Zed codebase + figure out how to do key bindings?

At this point I am not a code contributor to Zed, so the best I can do is to contribute to the discussion, if that is something that is appreciated by the community. These code changes might be obvious/easy to the committed contributor, but newcomers could spend a significant amount of time to resolve them. Maybe their two cents are still valuable to the community?

**Comment by josfaber** [comment]
Added `cmd-shift-k` also 
```
[
  {
    "context": "Editor",
    "bindings": {
      "alt-up": "editor::MoveLineUp",
      "alt-down": "editor::MoveLineDown",
      "alt-shift-down": "editor::DuplicateLine",
      "cmd-d": "editor::DuplicateLine",
      "cmd-shift-k": "editor::DeleteLine"
    }
  }
]
```

**Comment by JosephTLyons** [comment]
I think these have landed in [Zed v0.126.0](https://zed.dev/releases/preview/0.126.0), so I'll close this out.

**Comment by Moshyfawn** [comment]
> I think these have landed in [Zed v0.126.0](https://zed.dev/releases/preview/0.126.0), so I'll close this out.

I'm not sure that `editor::DuplicateLine' fulfils this requirement, if that's what you're referring to.

**Comment by Banyc** [comment]
@Moshyfawn I have investigated a bit and i see this:
<img width="493" alt="image" src="https://github.com/zed-industries/zed/assets/36535895/cefaa59c-3807-4c0c-8bd3-98349553a61f">

In the future release it will be `alt-shift-up` and `alt-shift-down`.

**Comment by Moshyfawn** [comment]
> In the future release it will be `alt-shift-up` and `alt-shift-down`.

I see! Thanks for the info, it does make sense 👍

**Comment by acusti** [comment]
for anyone who stumbles across this issue because they were used to the previous non-vscode-based key bindings (which i believe were based on atom’s key bindings) and they want those key bindings back, open your key bindings config (Zed › Settings… › Open Key Bindings or from the command-palette, `zed: open keymap`) and paste in the following config:
```json
[
    {
        "context": "Editor",
        "bindings": {
            "cmd-shift-d": "editor::DuplicateLine",
            "ctrl-cmd-up": "editor::MoveLineUp",
            "ctrl-cmd-down": "editor::MoveLineDown"
        }
    }
]
```

**Comment by croustibat** [comment]
for Zed `0.139.3` you need to specify DuplicateLineDown or DuplicateLineUp. 
Here is the one working for me : 

```json
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-up": "editor::MoveLineUp",
      "cmd-down": "editor::MoveLineDown",
      "cmd-shift-d": "editor::DuplicateLineDown"
    }
  }
]

```

**Comment by SHREYAS290601** [comment]
On linux: 24 
Zed 0.143.7 
In my keymap.json I have
`[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-alt-up": [
        "editor::DuplicateLineUp",
        {
          "move_upwards": true
        }
      ],
      "ctrl-alt-down": ["editor::DuplicateLineDown"]
    }
  }
]
`
However I am unable to run the commands even after reloading the editor, appreciate any help!!
