### ISSUE TITLE
Zed Adds Spaces In Front of URLs When Saving

### ISSUE THREAD

**Issue by ymolodtsov** [zed-industries/zed#4704]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When saving an .html document with some templates, Zed adds spaces in front of links, effectively killing them. Seems to be connected with Zed adding breaks to some tags and structures.

Before Cmd-S
![CleanShot 2023-06-13 at 08 41 35@2x](https://github.com/zed-industries/community/assets/2446078/0ca2e696-9fd2-46b2-b96c-aeb84fa626dc)

After Cmd-S
![CleanShot 2023-06-13 at 08 41 41@2x](https://github.com/zed-industries/community/assets/2446078/629606b5-44d0-403a-82e0-fd41082272f0)

The expected behavior would be Zed not touching anything unless it was specifically requested.

### Environment

Zed: v0.89.2 (stable)
OS: macOS 13.0.0
Memory: 16 GiB
Architecture: MacOS

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Yep, the HTML mode is not going to have a good time trying to format your templatized HTML.  As a workaround you can disable `format_on_save` in your settings.

Which templating engine are you're using?

There are some existing issues tracking support for various templating languages:
- https://github.com/zed-industries/extensions/issues/916
- https://github.com/zed-industries/extensions/issues/487
