### ISSUE TITLE
Auto-signed back into my GitHub account after sign out

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#4716]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

# Description

After signing out of my GitHub/Zed account and reopening Zed, I am automatically logged back in.

# Expected behaviour:

I would expect Zed to launch without automatically signing me back into my GitHub/Zed account.

# Reproduction steps:

1. Open Zed.
2. Make sure you are logged into your GitHub/Zed account.
3. Click on your profile picture.
4. Select the "Sign Out" button.
5. Close Zed.
6. Re-open Zed.
7. See you are not automatically logged back into your GitHub/Zed account (you should see your profile picture).

# Note

Might be related to zed-industries/zed#4908. Altho, in my case, I'm **explicitly** signing out of my account

### Environment

Zed: v0.88.5 (stable)
OS: macOS 13.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/16290753/c4bfd1c0-2d17-42b8-95fe-dd79afd9efae

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This landed in [Zed v0.132](https://zed.dev/releases/preview/0.132.0).
