### ISSUE TITLE
Tab bar of panel flashes when command is executed

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4717]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The tab bar of the panel sometimes flashes when some command is executed. See the movie below.

### Environment

Zed: v0.88.3 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![output](https://github.com/zed-industries/community/assets/5475262/b8d0738f-b3ca-4d58-9521-6877229faa35)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
I can't seem to reproduce this problem anymore. I'm going to close it, but feel free to report back if the problem persists.

**Comment by Moshyfawn** [comment]
Welp, spoke too soon 🤪
