### ISSUE TITLE
Toggling Copilot breaks per-language settings

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/zed#4721]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My Settings had a `language_overrides` section that looked like this:
<img width="294" alt="image" src="https://github.com/zed-industries/community/assets/26578100/6ce7962c-fff0-4fab-80e7-dcca0eafaa13">

I toggled "Hide suggestions for Rust" (with my `settings.json` still open in another tab if that's relevant)
<img width="315" alt="image" src="https://github.com/zed-industries/community/assets/26578100/6521798d-fd31-45b9-acfc-67548bdda97e">

It broke my file:
<img width="393" alt="Screenshot 2023-05-30 at 9 13 34 pm" src="https://github.com/zed-industries/community/assets/26578100/a3497439-c00e-4ff9-a922-40ca8f53c293">

### Environment

Specs:

```
Zed: v0.87.6 (stable)
OS: macOS 13.3.1
Memory: 8 GiB
Architecture: x86_64
```

Here's my full Settings json (pre-breakage) in case it helps:

```json
{
  "theme": "One Dark",
  "tab_size": 2,
  "buffer_font_family": "Menlo",
  "buffer_font_size": 16,
  "scrollbar": {
    "show": "system",
    "git_diff": false
  },
  "language_overrides": {
    "C": {
      "format_on_save": "off"
    },
    "Rust": {
      "format_on_save": "on",
      "tab_size": 4
    },
    "JavaScript": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "prettier",
          "arguments": [
            "--stdin-filepath",
            "{buffer_path}"
          ]
        }
      }
    },
    "TypeScript": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "prettier",
          "arguments": [
            "--stdin-filepath",
            "{buffer_path}"
          ]
        }
      }
    },
    "TSX": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "prettier",
          "arguments": [
            "--stdin-filepath",
            "{buffer_path}"
          ]
        }
      }
    }
  }
}

```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
It's been a while and it doesn't look like it's happening anymore. I'm going to close this thread, but feel free to reopen it if it's still there.
