### ISSUE TITLE
Custom cursor style of terminal

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4731]
### Check for existing issues

- [X] Completed

### Describe the feature

Make the cursor style of terminal customizable.

**Comment by warpdesign** [comment]
Would love that too :)

**Comment by Calinou** [comment]
Are you referring to having options for a line or underscore caret? I'd like to have that as well (especially line caret as it would match the main editor window), but I'm asking to make sure.

**Comment by warpdesign** [comment]
Yes, that's what I meant.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/12398 had almost brought that in, if anybody's willing to continue — welcome to ping me in the next PR.
