### ISSUE TITLE
Upon quit, show unsaved file name during confirmation window pop-up

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4736]
### Check for existing issues

- [X] Completed

### Describe the feature

Whenever I work on multiple files, at times I edit them. When this happens, upon ZED closure a pop-up window shows up asking if given changes should be saved. The problem is, the pop-up window does not show/point to which file the "save" reference is pointing to.

I would like to request a feature such as:
- pop-up window provides a name of the file that is to be saved or discarded
- behind the pop-up window the background focus shall change to the file to be closed/saved.

### If applicable, add mockups / screenshots to help present your vision of the feature

Current pop-up window does not include reference to the file under operation:
![Screenshot 2023-05-20 at 9 38 32 PM](https://github.com/zed-industries/community/assets/4711498/e44241c7-5c2a-4f72-9dba-d2a1451030bb)

Within the pop-up provide reference to the file as well as change the background focus to the file/tab under consideration.

**Comment by JosephTLyons** [comment]
Zed no longer forces you to save files with unsaved changes in it now, as we now serialize this files, and their changes, on app close, and restore them when reopening Zed.

- https://github.com/zed-industries/zed/pull/13546

However, if you turn this feature off via `{"session": {"restore_unsaved_buffers": false}}`, and close Zed out with files with unsaved changes, we now give more information about the files needing to be saved:

<img width="312" alt="SCR-20240728-cxkr" src="https://github.com/user-attachments/assets/dd1af11d-ff1f-40cb-a9b3-84bddf13d129">
