### ISSUE TITLE
Crash when doing project-wide search

### ISSUE THREAD

**Issue by hovsater** [zed-industries/zed#4742]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When doing a project-wide search for the term `footnotes`, Zed crashes. See [crash log](https://gist.github.com/hovsater/29eccd201d360e63d94843abc19d5db7).

### Environment

Zed: v0.85.4 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
Closing as we haven't made progress on this in a year, and we haven't see this crash in our crash logging.

Please do let me know if you are still experiencing this (or similar) though.
