### ISSUE TITLE
syntax highlighting for code in es6 multiline strings

### ISSUE THREAD

**Issue by jimniels** [zed-industries/zed#4748]
### Check for existing issues

- [X] Completed

### Describe the feature

In essence, this: https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html

Syntax highlighting for code inside backticks in JavaScript, e.g.

```js
function MyComponent(props) {
  const { message } = props;

  return /*html*/`
    <div>
      <p>Get HTML syntax highlighting inside this string in javascript.</p>
      <p>${message}</p>
    </div>
  `
}
```

### If applicable, add mockups / screenshots to help present your vision of the feature

[Image courtesy of es6-string-html](https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html)

![image](https://github.com/zed-industries/community/assets/1316441/2f5cb859-9434-4288-98be-86e61eef406d)

**Comment by Moshyfawn** [comment]
I think you're right, thanks!

I'm going to close this thread in favour of the other one, as it already has more upvotes. Be sure to +👍 to show your interest.

Duplicate of
- #5184

**Comment by jaydenseric** [comment]
This issue is not a duplicate of https://github.com/zed-industries/zed/issues/5184 . That issue is about syntax highlighting tagged template strings:

```js
import gql from "fake-tag";

const typeDefs = gql`
  "A foo."
  type Foo {
    "The \`Foo\` ID."
    id: ID!
  }
`;
```

This issue is about using comments to syntax highlight template strings:

```js
const typeDefs = /* GraphQL */ `
  "A foo."
  type Foo {
    "The \`Foo\` ID."
    id: ID!
  }
`;
```

Which sadly still doesn't work in Zed, and might force me to go back to VS Code.

**Comment by McxCZE** [comment]
> This issue is not a duplicate of [#5184](https://github.com/zed-industries/zed/issues/5184) . That issue is about syntax highlighting tagged template strings:
> 
> import gql from "fake-tag";
> 
> const typeDefs = gql`
>   "A foo."
>   type Foo {
>     "The \`Foo\` ID."
>     id: ID!
>   }
> `;
> 
> This issue is about using comments to syntax highlight template strings:
> 
> const typeDefs = /* GraphQL */ `
>   "A foo."
>   type Foo {
>     "The \`Foo\` ID."
>     id: ID!
>   }
> `;
> 
> Which sadly still doesn't work in Zed, and might force me to go back to VS Code.

Oh, so I am not the only one :))) Also would love to see this implemented.

**Comment by samrocksc** [comment]
well, this is unfortunate
