### ISSUE TITLE
Fig prompt positioned outside built-in terminal window

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#4750]
### Check for existing issues

- [X] Completed

#### Description
The Fig prompt is not anchored to the command line and instead appears relative to the editor window.

#### Reproduction steps

1. Install [Fig](https://fig.io/)
2. Open the Zed text editor.
3. Open the built-in terminal window within a dock that is anchored to the bottom of the editor.
4. Begin entering a command that Fig recognizes _(such as `fig <whitespace>`)_
5. Observe that the Fig prompt appears at the top of the editor window, instead of being anchored to the command line.

#### Expected behavior

The Fig prompt should be anchored to the command line.

### Environment

Zed: v0.85.3 (stable)
OS: macOS 13.3.1
Memory: 16 GiB
Architecture: aarch64
Fig CLI: 2.16.0

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1439" alt="image" src="https://github.com/zed-industries/community/assets/16290753/4d8a819f-8be7-4e1a-ae42-fc7147f279fd">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
As @Moshyfawn mentioned, [Fig](https://fig.io) is no longer a living tool, so I'm going to close this issue out.
