### ISSUE TITLE
Better Vim integration with File Explorer

### ISSUE THREAD

**Issue by ChristianChiarulli** [zed-industries/zed#4753]
### Check for existing issues

- [X] Completed

### Describe the feature

- I would like the ability to at least bind a key to switch between the editor and the file explorer.
- I would like to be able to traverse the file explorer with jk for moving down and up and hl for closing a folder and opening a file.

**Comment by wmstack** [comment]
Isn't this completed @JosephTLyons? There are now bindings hjkl for going up and down collapsing and expanding, and o/enter to open a directory. - and cmd b focus on the explorer.

The only thing left seems to be a key binding to switch between the editor and the explorer (without collapsing the project panel). But it feels pretty complete.

Personally I would like to have `/` bound to doing a file search inside the project panel though.

**Comment by mrnugget** [comment]
> The only thing left seems to be a key binding to switch between the editor and the explorer (without collapsing the project panel). But it feels pretty complete.

That's already possible, see: https://zed.dev/docs/vim#settings

```
{
    "context": "Dock",
    "bindings": {
        "ctrl-w h": ["workspace::ActivatePaneInDirection", "Left"],
        "ctrl-w l": ["workspace::ActivatePaneInDirection", "Right"],
        "ctrl-w k": ["workspace::ActivatePaneInDirection", "Up"],
        "ctrl-w j": ["workspace::ActivatePaneInDirection", "Down"]
        // ... or other keybindings
    }
}
```

**Comment by mrnugget** [comment]
I agree with @wmstack. I think this is done. It might not be 100%, but I think we can close this and create separate issues/PRs for missing keybindings.

**Comment by ethanmsl** [comment]
Those bindings are helpful, thanks all, but small problem for me: 
The above mappings apply even when editing/writing file names. 
(So typing `j` in a file name jumps you down to the next file, for example.)

Looked at the default keybindings keep track of context and `not_editing` seems to work for the defaults and fix the above.

`"context": "ProjectPanel",` ~~> `"context": "ProjectPanel && not_editing",`
```json
     {
        "context": "ProjectPanel && not_editing",
        "bindings": {
            "h": "project_panel::CollapseSelectedEntry",
            "l": "project_panel::ExpandSelectedEntry",
            "j": "menu::SelectNext",
            "k": "menu::SelectPrev",
            "o": "menu::Confirm",
            "r": "project_panel::Rename",
            "z c": "project_panel::CollapseSelectedEntry",
            "z o": "project_panel::ExpandSelectedEntry",
            "shift-o": "project_panel::RevealInFinder",
            "x": "project_panel::Cut",
            "c": "project_panel::Copy",
            "p": "project_panel::Paste",
            "d": "project_panel::Delete",
            "a": "project_panel::NewFile",
            "shift-a": "project_panel::NewDirectory",
            "shift-y": "project_panel::CopyRelativePath",
            "g y": "project_panel::CopyPath"
        }
    }
```

**Comment by wmstack** [comment]
I think there is also `!renaming` context which I recently used to do a compound action, once I select a file, it picks it in the editor view and collapses the project panel at the same time, but doesn't activate when renaming files.

**Comment by baldwindavid** [comment]
@ethanmsl Think you're already saying this, but the `vim: open default keymap` command includes `not_editing` already. So best to use the defaults rather than the suggestions in this thread...and one more good reason to have closed this issue as completed to avoid confusion.
