### ISSUE TITLE
[tree] Configure indentation width

### ISSUE THREAD

**Issue by lukeed** [zed-industries/zed#4754]
### Check for existing issues

- [X] Completed

### Describe the feature

IMO there's not enough indentation between file/folder levels by default. (I've also modified this in VSCode)

A setting to control the indentation width would be great. Attached VSCode's setting name

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="425" alt="Screen Shot 2023-05-08 at 12 39 32 PM" src="https://user-images.githubusercontent.com/5855893/236917311-75ac3b70-e062-4867-b48b-05c526702f25.png">

**Comment by Moshyfawn** [comment]
The indentation of the project panel can now be adjusted.

```json
"project_panel": {
  "indent_size": 24
}
```
