### ISSUE TITLE
multi-buffer breadcrumbs hover display "Show symbol outline"

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#4763]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It is invalid and prompts an error

### Environment

Zed: v0.84.3 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by olejorgenb** [comment]
It still show the tooltip though? And clicking it does nothing.

<img width="747" height="328" alt="Image" src="https://github.com/user-attachments/assets/758323fa-9abd-4823-bb06-65f94acf5839" />

A very minor thing though 🤷
