### ISSUE TITLE
ctrl+tab to switch between recently open files

### ISSUE THREAD

**Issue by sheikalthaf** [zed-industries/zed#4772]
### Check for existing issues

- [X] Completed

### Describe the feature

Need option to switch between recently opened files similary to VSCode

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://user-images.githubusercontent.com/22526247/235059346-2320c515-c2d7-44a9-8752-aeb209ee3e3a.png)

**Comment by kjrjay** [comment]
I also very much miss the ctrl+tab behaviour of vscode to go to last visited pane. Currently in zed, going to previous visited pane can sort of be done with a few extra clicks: by clicking cmd+p, p again and enter. 

I would like that, when Ctrl+tab is pressed, it lists the panes in most recent visited order and I can cycle through them by pressing tab again and again without releasing Ctrl. A single Ctrl+tab and release goes to last visited pane.

**Comment by AndreaBarghigiani** [comment]
Looking forward for this, it's soo convenient

**Comment by andrejsm** [comment]
Nice! `cmd-p` now auto-selects previous active file. We must hit `enter`, though. But we are just this one feature away for getting the so well known `ctrl-tab` behavior where file is activated upon releasing pressed keys.

I can see that adding this activation upon release when pressing `cmd-p` doesn't make sense. The file finder has this input field for searching for files. which is awesome. A separate solution must be built specifically for `ctrl-tab`.

Anyway, thank you Zed team for `cmd-p` improvements. It's easier now to switch between recent files.

**Comment by AndreaBarghigiani** [comment]
Totally agree here, `cmd-p` auto-selection is a great achievement. But being able to embrace the `ctrl-tab` flow would be even a bigger accomplishment.

Maybe the majority of users are used to `cmd-p` even between opened files, but I am just **addicted** to `crtl-tab` 😅

**Comment by osiewicz** [comment]
Isn't this solved by tab switcher @JosephTLyons ? Perhaps it could be closed.

**Comment by littleStudent** [comment]
yeah works like a charm for me 👏.
There is one potential improvement. While the switcher is kept open, i find myself using the arrow keys to move file selection up or down (especially up). 
Thx for the work and the implementation, great job 👏.

**Comment by JosephTLyons** [comment]
> yeah works like a charm for me 👏. There is one potential improvement. While the switcher is kept open, i find myself using the arrow keys to move file selection up or down (especially up). Thx for the work and the implementation, great job 👏.

Funny that you brought this up, as I just added it last night! 😂 

- https://github.com/zed-industries/zed/pull/10396

This will be in preview next week and stable the following, although I could fast track it such that it lands in whatever next stable and preview patchs come out.

At any rate, you can simply copy the keybindings over into your `keymap.json`, temporarily, until it lands in those builds:

```json
{
  "context": "TabSwitcher",
  "bindings": {
    "ctrl-up": "menu::SelectPrev",
    "ctrl-down": "menu::SelectNext",
    "ctrl-shift-tab": "menu::SelectPrev",
    "ctrl-backspace": "tab_switcher::CloseSelectedItem"
  }
}
```

**Comment by JosephTLyons** [comment]
> Isn't this solved by tab switcher @JosephTLyons ? Perhaps it could be closed.

Yep! Closing this out! 🎉

**Comment by prbxr** [comment]
I am confused. Is there simply ctrl-tab doing back and forth between last two tabs?

**Comment by LeartS** [comment]
> I am confused. Is there simply ctrl-tab doing back and forth between last two tabs?

@prbxr `ctrl-tab` will open the tab switcher, which by default points to the last active tab. When you release ctrl, it opens to the selected entry, so effectively pressing and releasing ctrl-tab works as a back and forth between two tabs; but you can also do more by just releasing the tab key and using arrow keys to navigate.

you can also assign a shortcut to switch in your keymap. For example, I like to use `space tab` ([Spacemacs](https://github.com/syl20bnr/spacemacs/)-style) to quickly switch to previous (history-wise) tab:

```json
{
  "context": "Editor",
  "bindings": {
      "space tab": ["workspace::SendKeystrokes", "ctrl-tab enter"],
  }
}
```

**Comment by Foorack** [comment]
@LeartS  But is it possible to switch between tabs in the order they are in, not according to history? This is similar to how many browsers do with ctr+tab and ctrl+shift+tab. Thank you!

**Comment by Foorack** [comment]
Nevermind! I was able to solve it by adding the following to keymap.json:
```
{
        "bindings": {
            "ctrl-shift-tab": "pane::ActivatePrevItem",
            "ctrl-tab": "pane::ActivateNextItem"
        }
    }
```

Thanks very much to https://github.com/zed-industries/zed/issues/5401#issuecomment-1908676122

**Comment by manaskarekar** [comment]
> @LeartS But is it possible to switch between tabs in the order they are in, not according to history? This is similar to how many browsers do with ctr+tab and ctrl+shift+tab. Thank you!

Thanks for this. The default behavior was really annoying.

**Comment by manaskarekar** [comment]
> Nevermind! I was able to solve it by adding the following to keymap.json:
> 
> ```
> {
>         "bindings": {
>             "ctrl-shift-tab": "pane::ActivatePrevItem",
>             "ctrl-tab": "pane::ActivateNextItem"
>         }
>     }
> ```
> 
> Thanks very much to [#5401 (comment)](https://github.com/zed-industries/zed/issues/5401#issuecomment-1908676122)

Thanks for this. The default behavior was unusable.
