### ISSUE TITLE
Find Implementations command

### ISSUE THREAD

**Issue by jaihindhreddy** [zed-industries/zed#4773]
### Check for existing issues

- [X] Completed

### Describe the feature

The `editor::FindAllReferences` command helps navigate to all callsites of a function, but there is no equivalent to find all implementations of a given interface.

I'm looking for something like `editor:FindAllImplementations`, which when invoked on an interface method-name, or the interface-name itself, shows all types that implement it.

I'm currently using Zed with Go, and the `go-pls` language server has `lsp-find-implementation`, which does exactly that.
I find this (along with zed-industries/zed#4809) to be the one of the biggest things that's preventing me from using Zed solely, for Go at least.

**Comment by painhardcore** [comment]
>  that's preventing me from using Zed solely, for Go at least.
Same for me, must have in big projects

**Comment by painhardcore** [comment]
@jaihindhreddy I've noticed that they added. It's quite slow, but at least works 
<img width="425" alt="image" src="https://github.com/zed-industries/zed/assets/4718161/f6000d4a-e144-4df7-ae2b-e93b4cfb8377">

**Comment by jaihindhreddy** [comment]
Thanks @painhardcore!
Now that `editor::GoToImplementation` exists, I'm closing this issue.
