### ISSUE TITLE
Not all JS extensions are highlighted as JS

### ISSUE THREAD

**Issue by Zeko369** [zed-industries/zed#4774]
### Check for existing issues

- [X] Completed

### Language

.cjs, .cts, .mts

### Misc notes

Just add `.cjs`, `.cts`, `.mts` as aliases for `.js`/`.ts`

**Comment by jaydenseric** [comment]
I've raised this separate issue regarding the file icons: https://github.com/zed-industries/zed/issues/7804 .

**Comment by maxdeviant** [comment]
Looks like this was fixed at some point:

https://github.com/zed-industries/zed/blob/14a0d8039b9d666ca4f989fc835bc1789b6e3e75/crates/languages/src/javascript/config.toml#L3

https://github.com/zed-industries/zed/blob/14a0d8039b9d666ca4f989fc835bc1789b6e3e75/crates/languages/src/typescript/config.toml#L3
