### ISSUE TITLE
F2 (rename) does not work on files in Project Panel (docs state otherwise)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4775]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As in the subject, when focused on project panel (`CMD+SHIFT+E`), I would expect `F2` (rename) functionality to work on files as [current docs state](https://docs.zed.dev/configuration/key-bindings), which at the moment is not the case.

I would like to point out, the renaming works on folders, which is consistent with reported `zed.log` message (see below).

### Environment

Zed: v0.82.9 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Relevant log message:
`2023-04-26T08:29:59 [ERROR] Not a directory (os error 20)`

**Comment by maxdeviant** [comment]
Going to close this out, as it appears to be working in Zed v0.119.19.
