### ISSUE TITLE
Select Block/Paragraph with OPT+SHIFT+UP/DOWN

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4776]
### Check for existing issues

- [X] Completed

### Describe the feature

Combination of OPT+SHIFT+UP/DOWN would result is whole paragraph or block selection. See screenshot for detail.

### If applicable, add mockups / screenshots to help present your vision of the feature

Before selection
![Screenshot 2023-04-24 at 11 14 17 PM](https://user-images.githubusercontent.com/4711498/234172946-b84ecb20-35dd-4784-89d3-7380037c294e.png)

After OPT+SHIFT+UP/DOWN:
![Screenshot 2023-04-24 at 11 14 25 PM](https://user-images.githubusercontent.com/4711498/234172979-0d526d80-1799-4206-a11b-7f0d9115d346.png)

**Comment by JosephTLyons** [comment]
We currently have actions to move to the beginning/end of a paragraph/block, and also selection a paragraph/block:

<img width="1012" alt="SCR-20240728-csto" src="https://github.com/user-attachments/assets/084979ae-f5b5-4013-9271-269ffdec576f">

You can change these to be the key bindings you mentioned via:

```json
[
    "context": "Editor",
    "bindings": {
      "alt-shift-up": "editor::SelectToStartOfParagraph",
      "alt-shift-down": "editor::SelectToEndOfParagraph"
    }
]
```
