### ISSUE TITLE
When saving new file without folder selection ZED will complain it is not a folder

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4779]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently, when in project, during saving new file by default the save window select one of previously created files. As such when creating a new file and trying to save it ZED will complain `The operation couldn't be completed. Not a directory`. The behavior is not present when creating a fresh new window and file, it will only occur when saving in existing project.

### Environment

Zed: v0.82.8 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature
Before saving:
![Beforre_save_button_push](https://user-images.githubusercontent.com/4711498/234041652-21ac947f-64ec-4822-8be9-76ca8b9faa2b.png)

After trying to save:
![After_save_button_push](https://user-images.githubusercontent.com/4711498/234041850-7dbd6e7e-303b-4543-88de-495d49eb14a9.png)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
I am not able to reproduce this issue with the current Zed release.
@rootalley / @krstp if you are still experiencing this issue, please feel free to reopen with a comment.

Thank you @rootalley for providing detailed reproduction instructions. I very much appreciate you for writing them up.

**Comment by krstp** [comment]
I confirm. In latest release of ZED all works as desired. Thanks.
