### ISSUE TITLE
Hover over warnings, results in empty text box

### ISSUE THREAD

**Issue by ls-ivan-kiselev** [zed-industries/zed#4781]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the latest update, there's confusing empty text box appears in UI suggesting there should be some language-server feedback text.

VSCode screenshot is attached for comparison 

### Environment

Zed 0.82.8
Apple M1 Pro
MacOS 13.3.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![bug_report_screenshot](https://user-images.githubusercontent.com/86964964/233830233-004cf64c-648d-4060-8d65-a4ec3f835969.png)

<img width="350" alt="Screenshot 2023-04-23 at 11 05 19" src="https://user-images.githubusercontent.com/86964964/233830422-1214233e-41ed-4b9b-bcc2-eb29e6410c24.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Doesn't seem to be applicable.

**Comment by maxdeviant** [comment]
This seems like it's on a pretty old Zed version, at this point. I'm going to close this out since a lot of things have changed since then.

@ls-ivan-kiselev If this issue is still happening for you, feel free to reopen.
