### ISSUE TITLE
Gray out unused variables

### ISSUE THREAD

**Issue by cktang88** [zed-industries/zed#4785]
### Check for existing issues

- [X] Completed

### Describe the feature

Gray out unused variables, such as the following in VS code attached (`b` is unused).

I believe most LSPs, including Pylance for python, has this info, we just need to show it in the editor, ideally configurable.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="111" alt="image" src="https://user-images.githubusercontent.com/10319942/233556078-626d2f11-de46-4ae0-8296-5a07fe4c030e.png">

**Comment by zarifpour** [comment]
+1, please also make this configurable for unused imports.

Here is an example:

## What is happening now (Zed)
![CleanShot 2024-02-27 at 12 38 08 on Zed — provider ts](https://github.com/zed-industries/zed/assets/16494335/fbf27642-62a2-40e2-94fb-57fd78c9f704)

![CleanShot 2024-02-27 at 12 37 39 on Zed — provider ts](https://github.com/zed-industries/zed/assets/16494335/b0d5a1c9-0ab0-47a3-92e1-00ed9cca04e8)

### Code responsible

```json
"themes": [
  {
    "name": "XY-Zed",
    "appearance": "dark",
    "style": {
      "unreachable": "#aca8aeff",
      "unreachable.background": "#262933ff",
      "unreachable.border": "#2b2f38ff",
     }
  }
]
```

## What I would like to configure (VS Code)

![CleanShot 2024-02-27 at 12 40 35 on Code — node_modulesetherssrc tsproviders — provider ts — 21cli](https://github.com/zed-industries/zed/assets/16494335/4303f379-7ca7-4b21-a3e8-f5a3833613d4)

![CleanShot 2024-02-27 at 12 41 15 on Code — node_modulesetherssrc tsproviders — provider ts — 21cli](https://github.com/zed-industries/zed/assets/16494335/1bd1d0f2-fd99-40b0-a019-004ca014bf9a)

### Code responsible

```json
"workbench.colorCustomizations": {
  "editorUnnecessaryCode.opacity": "#0000005e"
}
```

**Comment by MatthewScholefield** [comment]
Zed already supports greying out unused code right? At least it works for Javascript. The one remaining thing to support is customizing the opacity. Right now ([code ref](https://github.com/zed-industries/zed/blob/59ce3535d38946acaa7f7dcf6fcdf0aedd127432/crates/editor/src/display_map.rs#L77)) it appears to be fixed at 0.3 which is too similar for my liking.

If it doesn't work for other languages perhaps the LSP isn't fully integrated.

**Comment by JosephTLyons** [comment]
Current Zed does support graying out of unused variables, so I think I will close this issue out. Feel free to open a new issue explaining what sort of settings around this you'd like to see, if you would like that feature.

<img width="292" alt="SCR-20240727-uqte" src="https://github.com/user-attachments/assets/c0b98fb6-12d3-4857-a5bb-46fa1439b393">

**Comment by pantheraleo-7** [comment]
> Current Zed does support graying out of unused variables

I can't seem to get this happen in python. Is it controlled by themes (if yes, which property)? Or is it not supported for python?

**Comment by pantheraleo-7** [comment]
> Current Zed does support graying out of unused variables

for python also?

**Comment by saha84** [comment]
add this to settings.json:

`"unnecessary_code_fade": 0.6,`

View this commit:
https://github.com/zed-industries/zed/pull/14442/commits/4de6520f0538cc81da2c97f3b754b0d2ca621fbf

**Comment by curio77** [comment]
Sorry about being late to get back to this, but the fade value doesn't make a difference.  I guess for Go, cases such as unused *exported* global identifiers (say, consts, funcs) just aren't detected and thus not subject to this.  May be intentional.
