### ISSUE TITLE
SHIFT-ENTER compiles/interprets the code under selection and presents result in a pop-up or in-line as a comment with result

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4786]
### Check for existing issues

- [X] Completed

### Describe the feature

Allow for code compilation/execution of code block under selection, i.e. `SHIFT+ENTER`. Assuming the selected block logic is correct and includes return/print commands, Zed would execute the compiler/interpreter in the background and present outcome in popup window OR as a commented block. Python/Rust could be a good use case.

### If applicable, add mockups / screenshots to help present your vision of the feature

I can provide a mock-up, but I believe above text is somewhat self explanatory. If not, I can later sketch something out.

**Comment by JosephTLyons** [comment]
Zed now has built-in evaluation of code for languages supported by a Jupyter kernel. See the docs [here](https://zed.dev/docs/).
