### ISSUE TITLE
Keyboard shortcut for scrolling the hover tooltip

### ISSUE THREAD

**Issue by EricHenry** [zed-industries/zed#4787]
### Check for existing issues

- [X] Completed

### Describe the feature

When using vim you can remap the `editor::Hover` command. It would be nice to allow for commands to scroll the the tooltip if it is long enough to be scrollable. Currently this can only be accomplished with a mouse + scroll wheel. They could be `editor::TooltipScrollUp` and `editor::TooltipScrollDown`.

**Comment by Vagab** [comment]
I think making it vim-like in a way that if you trigger the hover event again the focus/cursor jumps to the hover window would be amazing

**Comment by Vagab** [comment]
I think this issue should now be closed, it's working now. We didn't get actual cursor in the hover panel but from my brief discussion with @ConradIrwin this is very hard to do

**Comment by jubalh** [comment]
> it's working now.

How exactly is it working?
I use `editor:hover` and then tried arrow keys and regular vim keys jk. In each scenario it closes the popover/tooltip and does the movement in the main editor.

**Comment by zbyju** [comment]
So there is no way of achieving this? This is something that I use very often; and I do the same with diagnostics (for long diagnostics I would navigate to the line and open a similar view the the hover which would show the full message, then when doing that again it would move my cursor into the hover and allow me to navigate inside that (e.g. for easy copying of the error message)

**Comment by ConradIrwin** [comment]
You can use `gh` to open the hover, and then the normal scroll shortcuts (`pageup`/`pagedown`/`ctrl-u`/`ctrl-d` to scroll it). There is no way (yet) to put your focus into that view and select/copy text unfortunately.

**Comment by KorigamiK** [comment]
> You can use `gh` to open the hover, and then the normal scroll shortcuts (`pageup`/`pagedown`/`ctrl-u`/`ctrl-d` to scroll it). There is no way (yet) to put your focus into that view and select/copy text unfortunately.

`ctrl-d/u` is really nice but for vim mode something like pressing `k` twice (triggering the hover twice) which focuses in the hover view is a really nice qol and vim compatiblity feature. i would love to see it happen!
