### ISSUE TITLE
Reopen an already moved opened file don't work

### ISSUE THREAD

**Issue by dupeiran001** [zed-industries/zed#4797]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

when a file is opened, then move it to other folder by terminal command `mv xxxx`

then click on the file browser the same file, it won't open

### Environment

Zed: v0.81.1 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Today, moving the file within the project updates both the file path in the editor and the project panel.
