### ISSUE TITLE
Specify file location for auto import when multiple imports with the same name exist.

### ISSUE THREAD

**Issue by nb-midwestern** [zed-industries/zed#4804]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://user-images.githubusercontent.com/103958286/230922964-a837564d-638f-488f-a842-b0a3c9cdc9b3.png)
as you can see from the screenshot above, it's hard to know which scrollbar to import. A simple `customScrollBar src` would help solve this issue.

**Comment by JosephTLyons** [comment]
Current Zed now shows the file name where the symbols are stored:

<img width="272" alt="SCR-20240728-clmj" src="https://github.com/user-attachments/assets/98ac842a-c0dd-4572-be8f-4259a542141b">
