### ISSUE TITLE
Failed to install HTML language server

### ISSUE THREAD

**Issue by m0xai** [zed-industries/zed#4806]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After fresh install I'm getting: "Language server error: HTML

failed to execute npm install:
stdout: ""
stderr: "npm ERR! code 127\nnpm ERR! path /Users/m0xai/Library/Application Support/Zed/languages/vscode-html-language-server/4.6.0/node_modules/core-js\nnpm ERR! command failed\nnpm ERR! command sh -c node -e \"try{require('./postinstall')}catch(e){}\"\nnpm ERR! sh: node: command not found\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/m0xai/.npm/_logs/2023-04-09T15_08_37_265Z-debug-0.log\n"

### Environment

Zed: v0.80.5 (stable)
OS: macOS 10.15.7
Memory: 8 GiB
Architecture: x86_64

Node: v18.15.0
npm: v18.15.0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ForLoveOfCats** [comment]
I think this was probably fixed in https://github.com/zed-industries/zed/commit/2d8159998d03da2ac96fee1e2469cf4ecf9a6e52, please let us know if you still experience this issue on a modern Zed version :)
