### ISSUE TITLE
About shortcut

### ISSUE THREAD

**Issue by marlkiller** [zed-industries/zed#4813]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

  I plan to use zed instead of sublime and need to change the default shortcut to accommodate it
I encountered some problems while modifying the shortcut keys. I only need to modify shortcut keys under the menu 'Selection', but I can't find any modification in Default Key bindings.
I hope to get your guidance

### Environment

macos m1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="858" alt="issue" src="https://user-images.githubusercontent.com/25897113/230581694-4cee41a9-99fb-4529-a84c-fe9d7de82feb.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @marlkiller, I'm going to close this issue out, as I think the keybinding I mentioned above should work.
