### ISSUE TITLE
Allow usage for multiple formatters

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4822]
### Check for existing issues

- [X] Completed

### Describe the feature

Ability to use multiple (at least two) different external `formatters` would be useful, such as in case of Python a chained combination of `flake8` followed with `black`. Note one is the code linter, whereas the other focuses on formatting.

**Comment by AndydeCleyre** [comment]
This seems to be unsafe in it's current state, yielding mangled content, based on my own attempts and the discussion at #15544.
