### ISSUE TITLE
Unique lines (a.k.a. remove duplicates)

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#4831]
### Check for existing issues

- [X] Completed

### Describe the feature

I wish there was a way to keep only one copy of repeating text in a buffer’s all lines (or a selected portion of it).

There may be different operating modes. For example, in one mode;

```
Foo
Bar
Foo
Foo
Bar 
```

… may be converted into:

```
Foo
Bar
```

… (i.e., removing *all* repeating occurrences of each line). Note, however, if this was implemented as “first sort [internally], then remove dups” then one must be thoughtful how the sorting works, because, for example, if sorting was making decisions about “what comes first” (e.g., case-sensitive or insensitive, numbers first VS letters first, special characters, similar accented chars to behave as one «e.g., ôöòóœø», etc.), this would impact on the final output of this feature.

In another mode the same input above might become:

```
Foo
Bar
Foo
Bar 
```

… (i.e., only the last repeating `Foo`s are removed, because other repeating occurrences weren’t continuous.)

And maybe even in a multi-cursor selection like this:

<img width="347" alt="CleanShot 2023-04-06 at 10 32 25@2x" src="https://user-images.githubusercontent.com/314398/230324281-63b87959-fd09-4390-8467-7764e3c2a950.png">

The end result, after the dups are removed, might look like this:

<img width="355" alt="CleanShot 2023-04-06 at 10 32 53@2x" src="https://user-images.githubusercontent.com/314398/230324371-8a7a7225-9833-4b81-8df4-976f918c7462.png">

So the words wrapped around `~` in the screenshot below are removed from the initial input, because they’re appearing for the n-th time:

<img width="391" alt="CleanShot 2023-04-06 at 10 33 12@2x" src="https://user-images.githubusercontent.com/314398/230324507-3c8fa787-488e-4b89-88e0-89a6163f8ae9.png">

What do you think?

(P.S.: This may be a sub-feature of https://github.com/zed-industries/zed/issues/5438.)

**Comment by porsager** [comment]
I really think this ought to be a builtin considering #5788 got added 🙏

**Comment by SomeoneToIgnore** [comment]
This looks doable, see https://github.com/zed-industries/zed/pull/2786 for the reference.
One needs to create another `Editor::manipulate_lines` wrapper and another action for that + add a test into `editor_tests.rs`

**Comment by JosephTLyons** [comment]
One decision that we probably need to make here is whether or not this command should 

- remove all duplicates, or
- remove only consecutive duplicates

The `Vec::dedup` method only works on consecutive duplicates.  You get a bit more control over the latter option, since you can always sort your lines first before deduplicating, but something tells me I'd never want to have the behavior of removing only consecutive duplicates.

**Comment by porsager** [comment]
A single data point here, but I've never needed to only remove consecutive duplicates ;)

**Comment by exalted** [comment]
I hear both of you, but if ever someone needed "remove only consecutive dups", only one of the two approaches would allow it, while for anyone who would like to "sort & dedup", well, they can do that 😉 

My :two-cents: , I'd totally dig having multiple commands:

* dedup all
* dedup consecutive 

Each enabling any combinations of the following modes: 

* case-aware
* variant-aware

Also, I'd expect these to work with:

* entire file, it nothing is selected
* on single selection 
* on multiple selections 
* cross-selections 

And last, but not least 😅, all this should also work on multi-file-buffers (e.g., project search results window.)

Easy, right?! 🙂

**Comment by SomeoneToIgnore** [comment]
I disagree with the tendency to overcomplicate and believe that a simple `HashSet::contains`-like, case-aware, deduplication is all we need — this is exactly what VSCode and Sublime provide, the original issue required for and exactly what we should start here.

The rest of the related wishes could go into separate issues/PRs and I suspect those would not be as popular.

**Comment by exalted** [comment]
Can't argue with that 🙂 

All the additional features, if any and if ever, can be a plug-in one day.

**Comment by JosephTLyons** [comment]
> I disagree with the tendency to overcomplicate and believe that a simple `HashSet::contains`-like, case-aware, deduplication is all we need — this is exactly what VSCode and Sublime provide, the original issue required for, and exactly what we should start here with.
> 
> 
> 
> The rest of the related wishes could go into separate issues/PRs and I suspect those would not be as popular.

Yeah, using a hashset seems like the right approach to me. :)

**Comment by dalton-oliveira** [comment]
Hi! Looking forward to make my first contribution! Is it ok to try this one ? I did manage to craft a solution that It doesn't keep selection after dedup action. Would that satisfies this Issue ?
What I though initially is to create a new method `Editor::replace_lines` which is a kinda simplified version of  `Editor::manipulate_lines` and passes a `&mut Vec<&str>` as callback paramenter. 
```rust

    pub fn unique_lines_case_sensitive(
        &mut self,
        _: &UniqueLinesCaseSensitive,
        cx: &mut ViewContext<Self>,
    ) {
        self.replace_lines(cx, |lines| {
            let mut seen = HashSet::default();
            lines.retain(|line| seen.insert(*line));
        })
    }
```
and at ``Editor:replace_lines`` would have:
```rust
            let mut lines = text.split("\n").collect_vec();
            callback(&mut lines);
```
These are some test scenarios:
```rust

    // Consider continuous selection as single selection
    cx.set_state(indoc! {"
        aaa«aa
        cˇ»c«c
        bb
        aaaˇ»aa
    "});
    cx.update_editor(|e, cx| e.unique_lines_case_insensitive(&UniqueLinesCaseInsensitive, cx));
    cx.assert_editor_state(indoc! {"
        aaaaa
        ccc
        bbˇˇ
        "});

    // Consider non continuous selection as distinct dedup operations
    cx.set_state(indoc! {"
        «aaaaa
        bb
        aaaaa
        aaaaaˇ»

        «aaaaaˇ»
    "});
    cx.update_editor(|e, cx| e.unique_lines_case_insensitive(&UniqueLinesCaseInsensitive, cx));
    cx.assert_editor_state(indoc! {"
        aaaaa
        bbˇ

        aaaaaˇ
    "});
   ```

How does that approach sounds like ?

**Comment by SomeoneToIgnore** [comment]
@dalton-oliveira welcome to submit a PR.
I think any good-first-issue labeled issue that has an approach description that more or less matches yours can safely get a PR straight away, without the discussion.

But what you did in `unique_lines_case_sensitive` looks exactly what I've imagined the fix would be.
Could not comprehend the diff for `manipulate_lines` but that does not look bad either — as long as the PR has a test for this, it's fine.

**Comment by JosephTLyons** [comment]
@dalton-oliveira landed unique lines in this PR, which will be in preview next Wed.

- https://github.com/zed-industries/zed/pull/7526

Let's close this issue out and open new ones for any extra line/text manipulation commands.
