### ISSUE TITLE
Prisma support

### ISSUE THREAD

**Issue by tingfeng-key** [zed-industries/zed#4832]
### Check for existing issues

- [X] Completed

### Language

prisma

### Tree Sitter parser link

https://github.com/victorhqc/tree-sitter-prisma

### Language server link

https://github.com/prisma/language-tools/tree/main/packages/language-server

**Comment by ndneighbor** [comment]
Hey there, started using Zed after the OSS launch! Congratulations! 

Is there a way we can open a PR to the LSP protocol or develop and extension to zed so that we can parse `.prisma` files?

**Comment by jyavorska** [comment]
It might be nice if there was a simple configuration 

```
"extension_overrides": { 
  "*.prisma": {
    "format_on_save": {
      "external": {
        "command": "prisma",
        "arguments": ["format", "--schema", "{buffer_path}"]
      }
    }
  }
}
```

**Comment by nexus9111** [comment]
I see that it's still not available, when will it be available ?

**Comment by broisnischal** [comment]
prisma and graphql lsp support!

**Comment by nexus9111** [comment]
@broisnischal I just reinstalled zed and I still don't have syntax coloring in my ide,
