### ISSUE TITLE
Close main window with CMD+W

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4835]
### Check for existing issues

- [X] Completed

### Describe the feature

After closing all the TAB there is no option to close open empty window. Good example is when I have multiple windows open with multiple tabs. Sometimes I just want to close one of those... so I hit CMD+W to close the tabs, but when no tabs are open this particular window would still stay open. It would be also nice if there was a prompt at the end asking user if user really wants to close the main window.

**Comment by julien-c** [comment]
Agree with this request

**Comment by danielweck** [comment]
upvoting!

(see my duplicate issue, now closed https://github.com/zed-industries/zed/issues/7200 )

**Comment by danielweck** [comment]
https://github.com/JosephTLyons FYI there is a 2 years old issue with more votes / thumbs up than this one, which I think is a duplicate:

https://github.com/zed-industries/zed/issues/5322

**Comment by JosephTLyons** [comment]
> @JosephTLyons FYI there is a 2 years old issue with more votes / thumbs up than this one, which I think is a duplicate:
> 
> https://github.com/zed-industries/zed/issues/5322 

Ah yeah! You're right. When searching for the original, I swore there were more upvotes.  Ok, let's close this one as well. If you've voted on this issue, please upvote on the original.

Side note, wish there was a better way, where upvotes could be merged.
