### ISSUE TITLE
Light theme with white background and clearly separable comments

### ISSUE THREAD

**Issue by kortesmv-etasku** [zed-industries/zed#4837]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently the light themes all prefer tinted / shaded background. It would be nice if there was at least one with proper white (#ffffff) background. As a plus, comments should be clearly separable from normal code, while still being easily readable :)

**Comment by maxdeviant** [comment]
This can be solved with user-provided themes now.

Maybe check out the "GitHub Light" theme in the extension store?

<img width="1289" alt="Screenshot 2024-03-12 at 1 58 29 PM" src="https://github.com/zed-industries/zed/assets/1486634/d5523678-cbe9-4661-92f7-db16d5ec38fe">

Not sure if it's _quite_ solid white.
