### ISSUE TITLE
Key Binding for "Organize Imports"

### ISSUE THREAD

**Issue by zauni** [zed-industries/zed#4840]
### Check for existing issues

- [X] Completed

### Describe the feature

I don't know if this is already possible, but it looks like we can not bind a key to the code action "Organize Imports".

In my TS files I would like to have a key binding to quickly organize the imports without opening the code action menu. Currently I have a key binding to format the code (`"alt-shift-f": "editor::Format"`) and in this style would it be possible to have `"alt-shift-o": "editor::OrganizeImports"` or something like that?

This feature request is similiar to zed-industries/zed#5232 but refers to a action on save.

**Comment by mirageN1349** [comment]
This is a very useful feature

**Comment by fredrikburmester** [comment]
I'd also love this feature.

**Comment by monmush** [comment]
Good want. Hope to have that feature in the near future

**Comment by klausbreyer** [comment]
need!
For now: is there at least an automation to to this at save?

**Comment by aarroisi** [comment]
Hi, is this not supported for Python? I already add this settings in:

- Global settings
- Project settings

Like this:
`{
  "languages": {
    "Python": {
      "code_actions_on_format": {
        "source.organizeImports": true
      }
    }
  }
}`

Or, like this:
`{
  "language_overrides": {
    "Python": {
      "code_actions_on_format": {
        "source.organizeImports": true
      }
    }
  }
}`

Still doesn't sort my imports. I use it alongside `format_on_save` config with external command (black formatter).

**Comment by doossee** [comment]
Are there any keybindings for "Add all imports" and "Remove unused code" ?

**Comment by mvolonnino** [comment]
Anyone know how/if we can customize to have zed sort imports like it does, but grouped by 3rd party packages first with a line break and then the repo packages grouped next?
