### ISSUE TITLE
add auto complete for opencv-python

### ISSUE THREAD

**Issue by updoo** [zed-industries/zed#4843]
### Check for existing issues

- [X] Completed

### Describe the feature

zed has no promps for opencv as vscode does, hope add this feature

**Comment by JosephTLyons** [comment]
Im going to close this issue out - I tested setting up `opencv_python` and I saw completions in Zed. Here's the project, though you'll have to make a venv and install the requirements.

[open_cv.zip](https://github.com/zed-industries/zed/files/14794583/open_cv.zip)
