### ISSUE TITLE
vscode extension support

### ISSUE THREAD

**Issue by howarddo2208** [zed-industries/zed#4845]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello Zed team,

As a user of Zed, I have been impressed with its speed and user-friendly interface. However, I believe that to attract more users to your platform, it would be beneficial to consider supporting VS Code extensions.

Many developers rely on VS Code extensions to enhance their workflow. The ability to leverage the vast library of VS Code extensions could make Zed more appealing to a wider audience. This could help improve the adoption of Zed. Moreover, I don't think many developers would want to rewrite their extensions for a small and new app like Zed, at least not just yet.
 
You can implement your custom extension API for more performance too, but it can come later. VS Code extension support is a must right out of the box imo.

**Comment by shinebayar-g** [comment]
Is it even possible?

**Comment by berkus** [comment]
> Is it even possible?

It is, but the amount of work here is pretty non-trivial:

- expose editor bindings for all the things that exist in vscode
  - bridge/thunk things that work differently
- support a JS runtime environment for plugins
- support compatible plugin configuration storage

**Comment by aelkoussy** [comment]
+1 with a suggestion
If you manage to add vscode extensions support with a better way of handling the really heavy extensions (like eslint for example), I think a lot of people would be excited to try and maybe switch from vscode to zed

So far, vscode is very fast and solid overall, with that problem above as a small nuisance - not sure if the host editor (vscode/zed) can control and improve the behaviour of extensions or not though tbh

**Comment by marek-nereca** [comment]
+1

**Comment by berkus** [comment]
I wonder if [boa](https://boajs.dev/blog/2024/03/07/boa-release-18) could become a JS engine to power the extensions.

**Comment by kerns** [comment]
I would love to see this. I am sure it isn't trivial to implement, but the competitive adv. and stickiness of VS Code's extension ecosystem isn't trivial either.

**Comment by eimfach** [comment]
I think it would nog make sense to support every vscode extension out there.. only a specific subset

**Comment by subhasish-smiles** [comment]
This would be phenomenal !!
Was just thinking the same thing

**Comment by eimfach** [comment]
> can we at least short list some?

I think you need a specification on which parts of the VSCode Extension API to support as a start ..

**Comment by himat** [comment]
Likewise, I don't think Zed has a shot of being a daily driver for a large part of the market until extensions are supported. I had finally switched from pure vim to vscode after many years only because there were certain AI extensions that made my workflow far superior. And I think zed would need those too.

**Comment by ShalokShalom** [comment]
> Likewise, I don't think Zed has a shot of being a daily driver for a large part of the market until extensions are supported. I had finally switched from pure vim to vscode after many years only because there were certain AI extensions that made my workflow far superior. And I think zed would need those too.

Zed now has AI features implemented.
See the homepage.

**Comment by thendodev** [comment]
I would like to say it doesn't matter how non-trivial the implementation is... the only real way to compete with VS Code is to support all if not most of their extensions otherwise, this is just another cool editor I can't use, there's no getting around that, it should probably be the most important focus for zed, that and the UI.

**Comment by berkus** [comment]
> I would like to say it doesn't matter how non-trivial the implementation is... the only real way to compete with VS Code is to support all if not most of their extensions

The good ones shall be reasonably easy to replicate. All the other duplicate crap probably is not very necessary.

I am personally just one extension short of the "comfortable set" and rather have fast and secure extensions in wasm rather than "do what you want with entire computer" JS from VSCode.

**Comment by ShalokShalom** [comment]
I imagine it makes sense to simply document the API in a way, that assists people with porting their apps.

Idk how far wasm extensions are supported.

Ideally, its possible to simply port existing extensions from one API to another - JS can be transpiled into wasm.

**Comment by notpeter** [comment]
While this is an interesting subject to consider, but at this time we have no plans to attempt a re-implementation the [VSCode Extension API](https://code.visualstudio.com/api) inside Zed as would be required to support VSCode extensions, and as a result I'm going to convert this to a github discussion.  Thanks for reporting.
