### ISSUE TITLE
Provide keyboard shortcut to open file in GIT repo (GitHub/BB/GitLab)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4855]
### Check for existing issues

- [X] Completed

### Describe the feature

Provide a keyboard shortcut, such as for example `CMD+\`, that allows direct file opening from editor to its web repo page, such as BB/GitLab/GitHub etc.

### If applicable, add mockups / screenshots to help present your vision of the feature

After CMD+\ the relevant repo page is opened in its BB/GitLab/GitHub repository.

**Comment by krstp** [comment]
Another reference, close/merged but not functional: https://github.com/zed-industries/zed/issues/6777

**Comment by notpeter** [comment]
We now have actions for "Open Permalink to Line" and "Copy Permalink to Line" which supports cloud hosted repos on GitHub, GitLab, Codeberg, Gitee, Bitbucket and Sourcehut.

You can assign a custom keyboard shortcut with:
```
  {
    // https://github.com/zed-industries/zed/pull/15113
    "context": "Editor",
    "bindings": {
      "ctrl-alt-cmd-z": "editor::CopyPermalinkToLine",
      "ctrl-alt-cmd-x": "editor::OpenPermalinkToLine"
    }
  },
```

More: [zed docs: git](https://zed.dev/docs/git)
