### ISSUE TITLE
CLI file opening to the same ZED opened window (and without fullscreen resize)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4861]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently when trying to `/Applications/Zed.app/Contents/MacOS/cli ~/.zshrc` ZED opens a new window which is forced into full screen. I would like ZED to be able to open the indicated file in currently opened window. Also right now the new opened window does not seem to follow the indicated theme.

**Comment by michaelwestphal** [comment]
Please consider adding a CLI option similar to how [`subl --add`](https://www.sublimetext.com/docs/command_line.html#usage) or [`code --reuse-window`](https://code.visualstudio.com/docs/editor/command-line#_core-cli-options) functions. My preference would be `zed --add` (or `zed -a`) like Sublime.
