### ISSUE TITLE
Add a vertical scroll bar to project panel

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#4865]
### Check for existing issues

- [X] Completed

### Describe the feature

HI, I found that zed doesn't have a scroll bar in project panel, when I have a project with large source file tree, it's too slow to navigate to other directory quickly if I don't have scroll bar.   If I have a scroll bar, I can drag it to the position I want quickly.

![图片](https://user-images.githubusercontent.com/22256154/228116392-ab202f8d-5c8d-43eb-b9b3-39b1e9bcfee4.png)

I think it's good to have a scroll bar for large projects, or have a short-cut to fold directories in explorer

### If applicable, add mockups / screenshots to help present your vision of the feature

Here is how vscode doing:
![图片](https://user-images.githubusercontent.com/22256154/228115898-cdc893e0-a5ce-48ff-a9f5-22790e0456a5.png)

**when I focus** on Explorer, it shows scroll bar, but if I don't, the scroll bar disappeared.

**Comment by jansol** [comment]
Doesn't even have to be a generated directory, opening e.g. `lib/CL` of https://github.com/pocl/pocl/ already leads to an eternity of scrolling when using a mouse with a simple scrolling wheel.

**Comment by jiangjie217527** [comment]
Also, please Add a scroll bar to bottom dock(usually be a terminal window). when I output too many information in the terminal, It is hard to scroll.

**Comment by hichemfantar** [comment]
@kumomiX same issue here
