### ISSUE TITLE
Display hunks/diagnostics/search results in scroll bar

### ISSUE THREAD

**Issue by AcrylicShrimp** [zed-industries/zed#4866]
### Check for existing issues

- [X] Completed

### Describe the feature

First of all, thank you for this amazing work.

I'd like to show indicators on scroll bar. I'm a big fan of indicators on scroll bar, it helps me locate errors, search results and recent changes faster, especially dealing large files. I hope this feature to be implemented.

### If applicable, add mockups / screenshots to help present your vision of the feature

Below is same feature of VSCode. Please ignore the mini-map; it's not what I mean.

<img width="1840" alt="스크린샷 2023-03-28 오전 9 15 41" src="https://user-images.githubusercontent.com/19178575/228094694-8c2b4e4e-e0c7-4440-8892-6953769d9be4.png">

As we can see, it's very easy to locate errors, even if it's out of screen.

**Comment by JosephTLyons** [comment]
Zed now shows selections, errors, git information, and selections, in the scrollbar:

<img width="1608" alt="SCR-20240727-ukqm" src="https://github.com/user-attachments/assets/4a95a05d-161d-4de5-bedf-2d8ed182bab1">
