### ISSUE TITLE
Unusable system (keyboard/mouse not working correctly)

### ISSUE THREAD

**Issue by jabr** [zed-industries/zed#4870]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm not certain this was due to Zed, but the timing was awfully suspicious.

Shortly after I installed Zed (and it was running but I wasn't actively using it), my system "broke". I could move my mouse cursor, but clicking did nothing. Additionally, some key events would get processed, but not all of them.

For example, I could bring up the force quit window with cmd+opt+esc, but the up/down arrows would not scroll through the list. And pressing return would not trigger the default button on the modal.

I couldn't figure out a better option than a hard reset, and since then I have *not* launched Zed and I have *not* seen the issue since. It only occurred that one time while I had Zed running for 20 minutes or so.

### Environment

MacBook Pro (14-inch, 2021), pomacOS 12.6.3, Apple M1 Pro, 32 GB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Zed has seen a lot of changes since this issue was open and we haven't had anyone else reporting this issue, so I think I'm going to optimistically close this out. If you run into this issue again, please open a new issue! 🙏
