### ISSUE TITLE
Light theme: git gutter is too thin and not really visable

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#4875]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi, I just found that git gutter is not really visiable in light theme, and it's width is various from `buffer_font_size` setting.

Using SF Mono font with font size 15:
![图片](https://user-images.githubusercontent.com/22256154/227090862-dc527924-a034-42df-888b-0148137817f2.png)

Using SF Mono font with font size 14:
![图片](https://user-images.githubusercontent.com/22256154/227091074-7c4ce9bd-9fa9-437f-9a6e-7bbca8caba78.png)

To me, it seems that it's too thin to notice that a change happened in the specific code block.

And I'm using `Gurvbox Light Soft` theme, I can reproduce in other other light themes, except One Light theme, the git gutter color in One Light theme is good.  But it's still too thin..

### Environment

Zed 0.78.1
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Maybe we can put git gutter to the right side of line-number like vscode, it's thin too, but it's more readable to me:
![图片](https://user-images.githubusercontent.com/22256154/227092701-07b034e3-9122-44f1-a88f-57d397c846c5.png)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by failable** [comment]
For me, it is to wide. I wish there's a setting for it.

**Comment by JosephTLyons** [comment]
We've increased the width of the gutter since this issue was filed, so I'm going to close this issue out. If you think it's still too hard to see, feel free to open a new issue. Thank you!

<img width="159" alt="SCR-20240727-ulxs" src="https://github.com/user-attachments/assets/61fefb24-da59-4ae1-a530-c5066b76db98">

**Comment by rahulchaudhari06** [comment]
is there a way that we can edit it ourselves?
or just disable it??

**Comment by burdiyan** [comment]
Came here to see if there's a way to make it thinner :) Coming from VS Code I find the Git gutter lines in Zed way too thick.

**Comment by TheHamkerCat** [comment]
It's too wide for me as well

<img src="https://github.com/user-attachments/assets/b405c1e1-092c-4c69-95de-dd15ffcba20b" width="300"/>
