### ISSUE TITLE
Atelier Light theme: code complete popped up menu is not really readable

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#4876]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi, after play a bit with atelier light theme, I found that I like it very much, but with a little issue about popped up menu.

Given the following rust code:
```rust
# main.rs
fn a_test_func(from: &str, to: &str) -> bool {
    true
}

fn main() {
    a_test_
}
```

when I'm typing `a_test_`, the selected item in popped up menu is low contract and not really readable.

![img](https://user-images.githubusercontent.com/22256154/227087003-71731aae-259a-4dd9-868e-ebcedc32c676.png)

The theme I'm using is Atelier Sulphurpool Light, but I can reproduce similar issues in other Atelier light themes

### Environment

Zed 0.78.1
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I'd expected the selected item's contract is high enough to be readable.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Thanks for reporting this.  I'm going to consolidate this issue into:
- https://github.com/zed-industries/zed/issues/15521

I've included your screenshot as an example in a comment.
Thanks for reporting.
