### ISSUE TITLE
Having "languages" and "language_overrides" in Settings breaks it.

### ISSUE THREAD

**Issue by ivansvlv** [zed-industries/zed#4877]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

⚠️ **I've searched backlog and didn't find an issue related to this. I'm sorry if I missed it and if it's a duplicate. Appreciate your work.**

I had the following settings in my `settings.json` to change the `tab_size` for the specified languages.
```json
    "languages": {
        "JavaScript": {
            "tab_size": 4
        },
        "TypeScript": {
            "tab_size": 4
        }
    }
```
I've looked up `languages` in default settings to know what property I have to change. Then I decided to change the formatter for these languages to Prettier, and added the following:
```json
   "language_overrides": {
        "JavaScript": {
            "format_on_save": {
                "external": {
                    "command": "prettier",
                    "arguments": [
                        "--stdin-filepath",
                        "{buffer_path}"
                    ]
                }
            }
        },
        "TypeScript": {
            "format_on_save": {
                "external": {
                    "command": "prettier",
                    "arguments": [
                        "--stdin-filepath",
                        "{buffer_path}"
                    ]
                }
            }
        }
    }
```
Which has broken the settings for the editor. By that I mean, when I restarted the theme, font, etc. have been set to default. After tinkering with it for a while a realised that deleting the `languages` setting and moving `tab_size` changes to `language_overrides` has fixed the issue. 
```json
   "language_overrides": {
        "JavaScript": {
            "tab_size": 4,
            "format_on_save": {
                "external": {
                    "command": "prettier",
                    "arguments": [
                        "--stdin-filepath",
                        "{buffer_path}"
                    ]
                }
            }
        },
        "TypeScript": {
            "tab_size": 4,
            "format_on_save": {
                "external": {
                    "command": "prettier",
                    "arguments": [
                        "--stdin-filepath",
                        "{buffer_path}"
                    ]
                }
            }
        }
    }
```

Looking at [docs](https://docs.zed.dev/configuration/configuring-zed#available-settings) `languages` is not even listed there. I don't know the expected behaviour but if the language overrides are meant to be done via `language_overrides` then maybe `languages` should not even be available in settings?

### Environment

Zed: v0.77.3 (stable)
OS: macOS 12.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
We've removed this setting and now only `languages` is supported, so I'm going to close this issue out!

- https://github.com/zed-industries/zed/pull/13164

**Comment by ivansvlv** [comment]
Great! Thank you! 🙏
