### ISSUE TITLE
trigger parameter hints

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#4879]
### Check for existing issues

- [X] Completed

### Describe the feature

in vscode ,you can use `Shift ⇧` + `Cmd ⌘` + `Space` trigger
![image](https://user-images.githubusercontent.com/19868292/226910707-3ece009d-0a71-4dbf-a166-b29437cfa04e.png)
This is very useful, especially if I forget what arguments does the function take
I use vim mode,I would like to be able to allow auto-prompt as you type, or use a keyboard shortcut, hopefully compared to vim

**Comment by elsassph** [comment]
I was honestly surprised this feature was missing - it took me a while to find this issue.

**Comment by m4es7r0** [comment]
add this to your keymap.json

[
  {
    "context": "Editor",
    "bindings": {
      "cmd-space": "editor::ShowCompletions"
    }
  }
]

**Comment by soham-suki** [comment]
@m4es7r0  I don't think `editor::ShowCompletions` is what the requirement is - we need a way to parameter hints inside the (), which this doesn't do.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/12909 brought initial support for this feature which is almost complete but only shows a single, first signature help it gets (and also does not show description labels, just the signatures).

This works well for many languages that have no overrides, so I'll let the PR close this issue automatically and will wait for more feedback in separate issues.

This is planned to be released as part of Zed 0.145

**Comment by MaMrEzO** [comment]
If you land here like me, bind a key-stroke to `editor::ShowSignatureHelp`, or hit this command`show signature help`.
