### ISSUE TITLE
Saving doesn't import or remove Go modules

### ISSUE THREAD

**Issue by mislavperi** [zed-industries/zed#4886]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Typing in code some struct from a go package and hitting save won't import it. No longer using a package in code (removing `fmt` prints for example) and saving the file will not remove the import from the project.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by d1y** [comment]
Hello friends, what’s going on now? My side is still not working (unused packages will not be deleted)
> good in vscode 😵‍💫
![fix_go_remove](https://github.com/zed-industries/zed/assets/45585937/6800b24e-3691-4138-93a7-2f52d66c5978)

**Comment by regexPattern** [comment]
@d1y Works fine for me (the clip only shows adding missing packages but removing unused ones works as well). Make sure you have `goimports` installed globally on your system and that it is in your path.

https://github.com/zed-industries/zed/assets/47466248/193a6617-384f-4d74-87fa-eaedf8faa11e

**Comment by d1y** [comment]
> @d1y Works fine for me (the clip only shows adding missing packages but removing unused ones works as well). Make sure you have `goimports` installed globally on your system and that it is in your path.
> 
>  Screen.Recording.2024-01-26.at.10.57.04.mov

it worked!

**Comment by derekperkins** [comment]
This suggestion resolves it how I would prefer. `goimports` can be slow (6-8s in our repo), and `gopls` is already running, so a setting to trigger `Organize Imports` on save is how I would prefer to do it.
https://github.com/zed-industries/zed/issues/5232

**Comment by JosephTLyons** [comment]
This has landed in [v0.124.0](https://zed.dev/releases/preview/0.124.0).
