### ISSUE TITLE
mark completion with some sign to indicate weather it is smart completion or not

### ISSUE THREAD

**Issue by victororlyk** [zed-industries/zed#4894]
### Check for existing issues

- [X] Completed

### Describe the feature

use some big react app on the internet and try to type some stuff.
I would expect relevant compelition highlighted somehow different, maybe like in vs code

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="829" alt="zed" src="https://user-images.githubusercontent.com/33072590/226269154-75ce7188-51ea-47b1-a91f-54bbed5f93d8.png">
<img width="543" alt="vscode" src="https://user-images.githubusercontent.com/33072590/226269158-3cd1e290-89c3-4452-8996-151c0e043904.png">

**Comment by JosephTLyons** [comment]
I'm thinking that this will be covered by:

- https://github.com/zed-industries/zed/issues/4943

So I will close this issue out.
