### ISSUE TITLE
Lower left problem status indicates problems; problems view shows no problems

### ISSUE THREAD

**Issue by GKJCJG** [zed-industries/zed#4896]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't know what particular steps produced this, but the bug is easy enough to describe: the bottom left problem status bar item shows problems, but the problem view itself shows none:

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/43424668/226231919-8637113c-95e7-40b9-9d3a-698d222c4dd9.png">

The workspace contains files in several languages. I had opened a Python file open with two diagnostics, then I closed that. I had also had a couple of JS files that had a few errors. Later in the session, I opened one of JS files again, and it had three problems, but the problem count in the lower left didn't update for that, either.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This should be fixed in 0.134.0 (currently in preview, but will be in stable this week).

- https://zed.dev/releases/preview/0.134.0
