### ISSUE TITLE
ability to copy text/error from popover

### ISSUE THREAD

**Issue by victororlyk** [zed-industries/zed#4898]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be cool if user would be able to copy text from popovers

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="528" alt="Screenshot 2023-03-19 at 21 44 53" src="https://user-images.githubusercontent.com/33072590/226205062-c6329a15-2fbb-4562-b21d-3def012c64f0.png">

**Comment by JosephTLyons** [comment]
Hey @victororlyk - I'm going to consolidate a few requests into a single issue. I think this request covers what you are looking for here - feel free to upvote it with a 👍 reaction:

- https://github.com/zed-industries/zed/issues/4606
