### ISSUE TITLE
Ruby right-hand assignment syntax bug

### ISSUE THREAD

**Issue by willcosgrove** [zed-industries/zed#4902]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Ruby like this will break syntax highlighting for the remainder of the file:

```ruby
def a_method
  a_method_call => a_variable, another_variable
end
```

It handles right-hand assignment, but breaks when the right hand destructures the assignment. So it works up until I add the comma.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by joeldrapper** [comment]
I believe this should be closed as fixed.

**Comment by willcosgrove** [comment]
It's close. It works better than it did when I opened the issue. But adding parenthesis breaks the highlighting again

```rb
def a_method
  a_method_call() => a_variable, another_variable
end
```

**Comment by joeldrapper** [comment]
I don’t know when this happened, but this is fixed now even with the parenthesis.

![CleanShot 2024-06-06 at 11 46 01@2x](https://github.com/zed-industries/zed/assets/246692/c26b0f03-f3e3-423e-9273-128367ed5a75)

**Comment by vitallium** [comment]
I also can confirm this issue is resolved and can be closed.
