### ISSUE TITLE
Open file outside project like opening project file using `file_finder::Toggle`

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4906]
### Check for existing issues

- [X] Completed

### Describe the feature

The `file_finder::Toggle` is great for opening project files. Selecting a file is as simple as typing and filtering. It would also be nice to have a command for opening file from arbitrary path (using the macOS Finder dialog from menubar is a bit inconvenient).

For example, after running the command, a finder like the one opened by `file_finder::Toggle` is displayed.

```
-----------------------------
| ~/a/b/c/                   | 
-----------------------------
| file1                      |  
| file2                      |
| ...                        |
-----------------------------
```

The finder is pre-input the PWD (of current buffer) and the candidates are files under this directory (Note that, no recursively). 

When one keep updating the input text of the finder, the candidate list is kept updating to the files in the directory of that path. 

Finally using <kbd>Enter</kbd> to select a file or create a new file when the file doest not exist.

### If applicable, add mockups / screenshots to help present your vision of the feature

- Opening the finder
<img width="254" alt="Screenshot 2023-03-18 at 23 51 26" src="https://user-images.githubusercontent.com/5475262/226116426-c528dabc-cdda-47b2-8654-613fb93aff02.png">

- Filtering
<img width="260" alt="Screenshot 2023-03-18 at 23 51 34" src="https://user-images.githubusercontent.com/5475262/226116428-22f3ad34-1415-4904-a625-b1cc1cd7f00d.png">

- Go into sub directory
<img width="248" alt="Screenshot 2023-03-18 at 23 51 39" src="https://user-images.githubusercontent.com/5475262/226116429-4446d0a8-8c8a-4140-ad9a-6bfc2a346b35.png">

- Select an existed file
<img width="316" alt="Screenshot 2023-03-18 at 23 51 51" src="https://user-images.githubusercontent.com/5475262/226116430-e78a998f-65eb-4547-88e6-5262d2a368fa.png">

- Create a new file
<img width="296" alt="Screenshot 2023-03-18 at 23 52 06" src="https://user-images.githubusercontent.com/5475262/226116431-242cebac-5620-46c5-99e7-66e699ccf396.png">

**Comment by meguriau** [comment]
+1

The default file finder on macOS is a bit clunky. I wish there is a native solution in side the editor to replace with the default "Open..." menu. Supporting fuzzy file finding would also be great.

**Comment by failable** [comment]
Seems this is covered by `  "use_system_path_prompts": false` now.
