### ISSUE TITLE
"Sign In" button alignment is off offline 

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#4909]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

1. Be signed out from your GitHub account in Zed
2. Turn off your internet connection
3. See "Sign In" button not aligned with the "cloud" offline icon _(not centered in the toolbar)_

_P.S. I've filled out a feedback file through the Zed feedback feature with this bug before found this "official" way of reporting bugs, my apologies_

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="134" alt="image" src="https://user-images.githubusercontent.com/16290753/226081255-eb9a5583-9bdb-46a2-b8f2-3450e037e9df.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
Closing this, as it predates the GPUI 2 rewrite.
