### ISSUE TITLE
Left sidebar doesn't remember its width

### ISSUE THREAD

**Issue by Amparose** [zed-industries/zed#4910]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open sidebar and resize it (normally larger).
2. Close the sidebar.
3. Open sidebar.

The reopened sidebar reverts back to a default width.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
This is now working as requested.
