### ISSUE TITLE
Add Tasks to Zed

### ISSUE THREAD

**Issue by PJUllrich** [zed-industries/zed#4913]
### Check for existing issues

- [X] Completed

### Describe the feature

I love VSCode's [Tasks](https://code.visualstudio.com/docs/editor/tasks) and have a keyboard shortcut for running all tests in a file or run a single test. It would be nice to be able to create such Tasks in Zed and run them through custom shortcuts.

### Example of a `tasks.json`
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run Elixir Tests in open File",
      "type": "shell",
      "command": "mix",
      "args": ["test", "${relativeFile}"],
      "options": {
        "cwd": "${workspaceRoot}"
      },
      "problemMatcher": ["$mixCompileError", "$mixCompileWarning", "$mixTestFailure"],
      "presentation": {
        "focus": true
      }
    }
  ]
}
```

### Example of custom shortcut
```json
  {
    "key": "cmd+shift+l",
    "command": "workbench.action.tasks.runTask",
    "args": "Run Elixir Tests in open File"
  }
```

**Comment by SomeoneToIgnore** [comment]
Tasks were added to Zed in https://github.com/zed-industries/zed/pull/8009 and coming in the next Preview (0.124), but no custom shortcuts are supported on them yet.

**Comment by jffin** [comment]
> Tasks were added to Zed in #8009 and coming in the next Preview (0.124), but no custom shortcuts are supported on them yet.

Hello, this is a great feature, many thanks. Is it possible to create the tasks.json file at the project level?

**Comment by SomeoneToIgnore** [comment]
Yes, there's a shortcut for that: 
![image](https://github.com/zed-industries/zed/assets/2690773/9a5be491-6368-414e-bfb4-841bc7114fb3)

**Comment by gdamore** [comment]
So would be great if this supported the problemMatcher too!

**Comment by PJUllrich** [comment]
Closing this because Zed now has Tasks and allows custom shortcuts for them.
