### ISSUE TITLE
Collaboration is not working after adding a new contact

### ISSUE THREAD

**Issue by enzime4u** [zed-industries/zed#4914]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After adding a new contact I can't start a collab session with him ! Even thru it worked in the beginning ! 

### Environment

![Screenshot 2023-03-17 at 12 25 51](https://user-images.githubusercontent.com/10274752/225904115-13db365b-818d-401b-9ff7-4690fc40c88c.jpg)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Zed has changed quite a bit since this issue was created, collaboration as well. I think I will close this issue out, but if you run into it again, please let us know via a new issue!
