### ISSUE TITLE
Better Folder Content Visualization

### ISSUE THREAD

**Issue by koloz193** [zed-industries/zed#4915]
### Check for existing issues

- [x] Completed

### Describe the feature

Currently when you expand a folder the name of the contained files are only indented by a single space. This can be confusing and not obvious for which files are in the parent level directory or the subdirectory. I'd love for the subfiles to be a little more obvious (i.e. to be in a slightly shaded box, have a tree structure showing theyre part of the folder, etc)

**Comment by JosephTLyons** [comment]
Hey @koloz193 - Now, there is a setting now for adjusting the indent size:

```json
  "project_panel": {
    "indent_size": 20,
}
```

For indent guides in the project panel, feel free to upvote this issue:

- https://github.com/zed-industries/zed/issues/12673
