### ISSUE TITLE
Support page up/down keybindings for scrolling Terminal 

### ISSUE THREAD

**Issue by tekumara** [zed-industries/zed#4917]
### Check for existing issues

- [X] Completed

### Describe the feature

Support page up/down keybindings for moving up/down in the Terminal scrollback.

**Comment by chuck-alt-delete** [comment]
I can get this functionality using `fn+up/down`.

What I would like though is the ability to scroll up and down with the trackpad. I have this in vs code, but I don't remember if this is something I had to enable in a special way

**Comment by wvovaw** [comment]
```keymap.json
// keymap.json
{
    "context": "Terminal",
    "bindings": {
      "ctrl-shift-k": "terminal::ScrollLineUp",
      "ctrl-shift-j": "terminal::ScrollLineDown"
    }
  }
  ```
  
  For those who want to set custom keys.
