### ISSUE TITLE
Undo and Redo disabled in Edit menu even though you can perform those commands

### ISSUE THREAD

**Issue by dmackinn** [zed-industries/zed#4920]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Undo and Redo commands within the Edit menu are shown as disabled. However, if you use the keyboard shortcutss you can perform those actions.

### Environment

MacBook Pro (14-inch, 2021)
MacOS Monterey 12.6.3 
Zed 0.77.3

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="287" alt="Screen Shot 2023-03-16 at 2 17 56 PM" src="https://user-images.githubusercontent.com/903385/225743025-4d5d7397-0927-4c85-bfc4-02e0258cb65b.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Despite that this is older, closing in favor of:
- https://github.com/zed-industries/zed/issues/12335

Thanks for reporting.
