### ISSUE TITLE
Tab Preview

### ISSUE THREAD

**Issue by zimt28** [zed-industries/zed#4922]
### Check for existing issues

- [X] Completed

### Describe the feature

Just _reading_ code, the number of open tabs grows quickly – it would be nice if there was an option to preview tabs, meaning that tabs close again unless the files get edited or saved.

[VSCode has this option](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode):
> When you single-click or select a file in the Explorer, it is shown in a preview mode and reuses an existing Tab. This is useful if you are quickly browsing files and don't want every visited file to have its own Tab. When you start editing the file or use double-click to open the file from the Explorer, a new Tab is dedicated to that file.
>
> Preview mode is indicated by italics in the Tab heading [...]

**Comment by johanneskares** [comment]
Yes, this would be great, I never understood how people can work without this setting.

**Comment by lhonay** [comment]
Is this option already being developed?

**Comment by SomeoneToIgnore** [comment]
There are some attempts but look stale currently: https://github.com/zed-industries/zed/pull/6782

**Comment by edtorba** [comment]
This needs more upvotes! ☝️

**Comment by SoloReverse** [comment]
This is affecting my workflow and I need to use zed

**Comment by JosephTLyons** [comment]
Preview tabs have landed in [Zed v0.132](https://zed.dev/releases/preview/0.132.0).

**Comment by sagardspeed2** [comment]
really needed feature is now available
