### ISSUE TITLE
Ability to see collapsed / files containing search

### ISSUE THREAD

**Issue by talaviram** [zed-industries/zed#4925]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently if you search something, you see a long list with header containing the filename and occurrences.

It would be beneficial if you could collapse or see just the files without the occurrences.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/6911158/225555930-0eee8baf-1503-4275-8a71-7a743b377334.png">

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://user-images.githubusercontent.com/6911158/225556624-79562c12-3fe4-44b7-b48e-ac4db46ba27a.png)

**Comment by volfcan** [comment]
Looking for this 👀

**Comment by JosephTLyons** [comment]
We now have the outline panel, which can give you a high-level overview of the results of any multi-buffer, including search multi-buffers!

This doesn't fully cover what you have asked for, as you can't collapse the results in the multi-buffer, but I think this covers most of what was annoying about using multi-buffers in the past.

<img width="1608" alt="SCR-20240727-pcek" src="https://github.com/user-attachments/assets/c937ea33-b751-40e7-85a2-716c67efdcd4">

**Comment by RichardJECooke** [comment]
@JosephTLyons, is there a way to fold the outline view? Even that is too long. Or is there an issue for that already

**Comment by MaxEvan** [comment]
> @JosephTLyons, is there a way to fold the outline view? Even that is too long. Or is there an issue for that already

Any news on that? It's kinda hard to scan with your eyes in larger repos.

**Comment by abdurrahmanarikan** [comment]
For a better visualization of a search result, zed should have folder search results.

**Comment by marcospb19** [comment]
> For a better visualization of a search result, zed should have folder search results.

Like this?

![image](https://github.com/user-attachments/assets/84e60a90-2ab1-43cb-9b4d-e2ccfb213af0)

This is the outline panel, it shows search results in folders.

---

@JosephTLyons did you want to show a picture of the outline panel in https://github.com/zed-industries/zed/issues/4925#issuecomment-2254255611? That's the project panel in your image :v .

**Comment by marcospb19** [comment]
Now that we can see the files containing search results, I'd suggest that this issue is completed, and then someone creates a new one with a proposal for the collapsing of multi-buffer excerpts, it's worth debating what that would look like and where to place the buttons, etc.

**Comment by MaxEvan** [comment]
> Now that we can see the files containing search results, I'd suggest that this issue is completed, and then someone creates a new one with a proposal for the collapsing of multi-buffer excerpts, it's worth debating what that would look like and where to place the buttons, etc.
> 
> I searched, and there is no existing issue for that.

While this works pretty well, discoverability of search results is bad. For example, if I search the whole repo for something I can indeed open the outline panel and view the results. Problem is when there are a lot of results, I want to collapse the folders and then dig through to get to the part of the app I want to explore. I can use "outline panel: collapse all entries" action right now but it is bugged because some the of folders won't reopen after collapsing initially. If that was fixed, I'd agree that this issue is now complete but not right now.
