### ISSUE TITLE
Unable to use `cmd-0` to toggle dock visibility

### ISSUE THREAD

**Issue by sent-hil** [zed-industries/zed#4933]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First of all, great project, love the speed and looking forward to migrating from VSCode.

While moving some of my keymappings, I ran into an issue. I added the following to keymap.json so I could use `cmd-0` to toggle dock visibility.

```
    {
        "context": "Editor",
        "bindings": {
            "cmd-0": "dock::FocusDock"
        }
    },
    {
        "context": "Dock",
        "bindings": {
            "cmd-0": "dock::HideDock"
        }
    }
```

With the above mapping, I'm able to open the dock with `cmd-0`, however, I'm not able to close it. I'm guessing once it's focused on dock, `cmd-0` is being sent to the terminal directly and therefore not having an effect. I saw there's support for `shift+esc` in the default key mapping which toggles the dock visibility.

Would appreciate support for this if possible.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by timfjord** [comment]
I have the same issue but with the `project_panel::ToggleFocus` command.
I think the reason why it is not working is that the `cmd-0` is defined [in the global keybindings](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default.json#L26)
So it looks like the user keymaps with some context don't override the default keymap, but they should.
Just in case, here is the `keymap.json` to reproduce this issue
```jsonc
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-0": "project_panel::ToggleFocus"
    }
  }
]
```
