### ISSUE TITLE
Project name not properly aligned if Zed launches in fullscreen

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#4935]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Probably related to zed-industries/zed#5485 

Steps to reproduce:
1. Open a project in Zed
2. Enter full screen
3. Quit Zed
4. Launch Zed again, which will enter full screen automatically, and observe the project name is now misaligned

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="275" alt="image" src="https://user-images.githubusercontent.com/5619348/225373748-faba08ff-cb8f-4ce3-b834-e581c1eb3672.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
This seems to be fixed in the latest version of Zed, so I'm going to close this issue as resolved. Be sure to let us know if you're still seeing this problem.
