### ISSUE TITLE
Erlang support

### ISSUE THREAD

**Issue by eproxus** [zed-industries/zed#4939]
### Check for existing issues

- [X] Completed

### Language

Erlang

### Tree Sitter parser link

https://github.com/WhatsApp/tree-sitter-erlang

### Language server link

https://github.com/erlang-ls/erlang_ls

**Comment by Copser** [comment]
Hello, I've started with adding support for Erlang [here](https://github.com/zed-industries/zed/compare/main...Copser:zed:add-erlang-support). I've used WhatsApp [tree-sitter-erlang](https://github.com/WhatsApp/tree-sitter-erlang) as requested. 

I'm missing an Erlang Language Server implementation :)

**Comment by wingyplus** [comment]
👋 Start working on Erlang support. 😄

<img width="341" alt="Screenshot 2567-01-30 at 15 26 38" src="https://github.com/zed-industries/zed/assets/484530/c43a4bd3-4140-40b7-a8ce-f32262c7ba78">

**Comment by codeadict** [comment]
Lol i started tok @wingyplus , and added erlang_ls as well. I can review your PR

**Comment by codeadict** [comment]
Added an alternative PR https://github.com/zed-industries/zed/pull/7093, @wingyplus I'm happy to keep yours and if we can incorporate  my changes that would be grat too
