### ISSUE TITLE
Code commenting does not work in .css

### ISSUE THREAD

**Issue by steakscience** [zed-industries/zed#4950]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Cmd + / does not comment code in .css files

I'm guessing this is an oversight because it works in other files such as .js

### Environment

N/A

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
<kbd>Cmd</kbd> + <kbd>/</kbd> correctly toggles commenting code for me in Zed v0.119.19.

@steakscience I'm going to close this, but we can reopen if you're still seeing the issue.

**Comment by steakscience** [comment]
Nice. 1 day after going opensource my backlogged issue immediately gets addressed
