### ISSUE TITLE
Show recent files and projects in macOS Dock menu

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#4960]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed should populate the macOS Dock context menu with recently opened files and projects.

### If applicable, add mockups / screenshots to help present your vision of the feature

VS Code for example:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/5619348/224555952-fd5399ce-fbdf-41de-97ad-26fe94f01a80.png">

**Comment by JosephTLyons** [comment]
This is now available, so I'm going to close this out. Feel free to open a new issue if further improvements on this are needed.
