### ISSUE TITLE
Option to disable Scroll Beyond Last Line

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#4962]
### Check for existing issues

- [X] Completed

### Describe the feature

VS Code parity. An option to stop the editor from scrolling and showing all the extra empty space when already at the end of file.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/5619348/224554504-5d7c1604-75df-403c-975c-970133933f0f.png">

**Comment by zhuweiyou** [comment]
I really need this bool option, because I can roll down. I think there is still content below, which is not in line with my habits in VSC and IDEA.

**Comment by gopeter** [comment]
> I really need this bool option, because I can roll down. I think there is still content below, which is not in line with my habits in VSC and IDEA.

Check out the [latest release](https://zed.dev/releases/stable/0.122.2), there is a new option called `vertical_scroll_offset`

**Comment by eproxus** [comment]
A partial workaround with `keymap.json` if you, like me, are using <kbd>PageUp</kbd> and <kbd>PageDown</kbd> to scroll:

```javascript
[
  {
    "context": "Editor",
    "bindings": {
      // Prevent scrolling "off-screen" at the bottom of the file
      "pageup": "editor::MovePageUp",
      "pagedown": "editor::MovePageDown",
    }
  }
]

```

**Comment by Erlendms** [comment]
+1 for this.

I get that it might be irrational, but I find it super annoying when I scroll down and I just get blank space. 😛 

**I’d link it to the `vertical_scroll_margin` so that scrolling down with a mouse/trackpad would stop the same place as doing it with cmd+down.**

Here’s an example, where I’ve set the vertical_scroll_margin as high as 15:
![CleanShot 2024-03-17 at 01 39 24@2x](https://github.com/zed-industries/zed/assets/83519391/b8711b05-7dc9-42b3-a60c-fe8ffd74301c)

**Comment by thedocbwarren** [comment]
Monitoring this as well.  Need this option.

**Comment by pekeler** [comment]
I'd be very interested in reading a reason from people who like the last line of code at the top of their editor instead of the bottom because I can't imagine why anyone might like it (unless this is some kind of accessibility thing for people who can't move their eyeballs vertically?).

**Comment by guillemap** [comment]
The only utility I've found is when comparing two files side-by-side and you need the last line to be at a certain height in the display... Anyways I'd also like the bool! :D

**Comment by yasainet** [comment]
I really like the `"scroll_beyond_last_line": "off"` feature!

However, I have one request.

Is it possible to specify different values for the Editor and Assistant Panel?

I would like to have the following available

Editor:.
`"scroll_beyond_last_line": "off"`

Assistant Panel:
`"scroll_beyond_last_line": "one_page"`
