### ISSUE TITLE
Indent Key binding not working properly when cursor is at the beginning

### ISSUE THREAD

**Issue by cddm-gh** [zed-industries/zed#4966]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the keybindings to Indent, if the cursor is placed at the beginning of the line it won't work, one has to move the cursor one character and then the command works.

Steps to reproduce:
1- set the cursor at the beginning of a line
2- hit the Indent keybindings (`CMD + ]`)
3- no indentation happens
4- now move the cursor 1 character to the right and try again
5- the indentation now works again

### Environment

Zed: v0.75.2 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Cursor at the beginning of the line:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/5694218/224495440-cdb11d2a-28a0-4dd5-95af-e17e7766d945.png">

The cursor is at the 2nd character of the line allowing the Indent to work properly again
<img width="465" alt="image" src="https://user-images.githubusercontent.com/5694218/224495419-981c4717-0ecd-4638-9341-500983acbc75.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
I am no longer able to reproduce this issue.
Please re-open if you are still seeing this.

https://github.com/zed-industries/zed/assets/145113/e3a347aa-9b03-48a6-ab1a-ec63f3a33e08
