### ISSUE TITLE
global search performance

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#4975]
### Check for existing issues

- [X] Completed

### Describe the feature

when there are a large number of results (105000), scrolling is very clunky, memory usage is very high (6G), and the process cpu shows 100%

**Comment by JosephTLyons** [comment]
We've had a lot of performance enhancements to search since this issue was filed, so I'm going to optimistically close this issue out. If you are still running into performance issues in current Zed, feel free to open a new issue!
