### ISSUE TITLE
Initial suggestion from IME has no visual indicator

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#4982]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When IME is enabled TextEdit always shows an underline under all text that is not committed yet:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/2588851/223088946-68bee13e-c4dd-4464-b591-e99fa6ff04f4.png">

Zed does not underline the initial text:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/2588851/223089214-03bc9ec1-d1fe-43eb-9503-f9b92b3cf59f.png">

Tabbing through suggestions makes an underline appear but it has extremely bad contrast against the background with all themes I tried (both light and dark themes).

### Environment

Zed: v0.74.3 (stable)
OS: macOS 12.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mikayla-maki** [comment]
This was fixed at some point.
