### ISSUE TITLE
Preserve untitled files for next time

### ISSUE THREAD

**Issue by assayire** [zed-industries/zed#4985]
### Check for existing issues

- [X] Completed

### Describe the feature

As a Zed lover, I want Zed to not ask to save/delete untitled files when quitting the app but preserve them as is, and have them available for me to work on next time I open zed.

PS: Feature can be tried out in Sublime Text and couple of other editors.

**Comment by porsager** [comment]
Very much miss this feature, but one super important thing - if it is added - is absolute certainty that you won't loose content in these "unsaved buffers/documents". Once you start relying on this feature it's an extremely great way to keep notes / snippets, etc, but it needs to be something you can trust. I have 9 year old unsaved content in Sublime, which I'd love to move over, but I don't want to risk loosing them (happened a couple of times in the good old textmate days during an upgrade).

**Comment by jacksongoode** [comment]
Agree, this is without a doubt a feature I can't migrate to Zed from Sublime without.

**Comment by Parithi** [comment]
+1 Looking forward to having this feature on Zed. This is the one that stops me from migrating from VSCode.

**Comment by ddegner** [comment]
Cat sat on my power button and force quit everything.  Lost an hour or so of writing.

Hopefully the feature will save me next time.

**Comment by akano-su** [comment]
Just ran into this issue and was very upset. Zed. Please. Since Atom stopped development, I haven't migrated to another text editor but you were SUPPOSED TO BE THE ONE!!

**Comment by NicolayD** [comment]
Chiming in on this - this would allow users to use new tabs for notes. It would be immensely helpful.

**Comment by rgilbert82** [comment]
+1 for this.

**Comment by selfish** [comment]
Chiming in - this is the only thing stopping me from uninstalling Sublime and fully making the switch.

**Comment by mileusna** [comment]
I was just about to raise this issue too. All major editors like VS Code and Sublime preserve unsaved files. Zed should do the same, especially considering its frequent updates that require restarts.

**Comment by ddegner** [comment]
> Cat sat on my power button and force quit everything. Lost an hour or so of writing.
> 
> Hopefully the feature will save me next time.

Bug fixed. It was faster to get rid of the cat.

**Comment by MemeKing** [comment]
I would love for this feature to be added. It's more than just a convenience, it's practically a whole lifestyle.

**Comment by mrnugget** [comment]
A first version of this has been merged: https://github.com/zed-industries/zed/pull/13546

It'll go into Preview release this week, on Wednesday. Stable release next week, pending any bug fixes or revision.

Please see the constraints in the pull request description that apply to this version.

**Comment by ddegner** [comment]
The cat will be allowed back inside. 

https://github.com/user-attachments/assets/cd68f5ae-52a4-4eaa-a6a8-963399011478

**Comment by JosephTLyons** [comment]
The following PRs have added quite a bit to the workspace serialization story:

- https://github.com/zed-industries/zed/pull/13546
- https://github.com/zed-industries/zed/pull/14965

There are a few known missing bits here, but I think its best that we close this issue out, in favor of new issues that describe those missing bit, so that we can get a clear understanding of how important these bits are to you all, now that most of the functionality has landed. Here are the new issues (upvote via 👍):

- https://github.com/zed-industries/zed/issues/15098
- https://github.com/zed-industries/zed/issues/15097

**Comment by selfish** [comment]
Thank you @JosephTLyons!
I understand the decision to close that issue. With that I think it's important to mention that #15098 is actually the main reason this feature is so desired. Open a new buffer, type something in, and just know it won't be lost.

**Comment by JosephTLyons** [comment]
> Thank you @JosephTLyons! I understand the decision to close that issue. With that I think it's important to mention that #15098 is actually the main reason this feature is so desired. Open a new buffer, type something in, and just know it won't be lost.

Note that this will work right now (in today's preview release) if you are opening an untitled buffer and there's a worktree in your project panel. 

https://github.com/user-attachments/assets/61345285-1b99-41c8-a805-9ce1ba697458

The only case in which this doesn't work is if you open up a brand new instance of Zed, one that has no projects in it, and then open a new file. I think we definitely want that, but I think a lot of the headache (80 percent or more) has been addressed by @mrnugget's PRs.

**Comment by mrnugget** [comment]
> I am on Zed Zed 0.150.4 my MBP M1 froze and restarted, and I had an untitled document with very important info, Zed restarted empty. Any chance I can recover it from somewhere?

Was that file in a project-less window? i.e. just a single window with unnamed buffers? Because those aren't persisted yet (see above).

But here's what you can do to check whether it's been saved:

```
sqlite3 ~/Library/Application\ Support/Zed/db/0-stable/db.sqlite 'select contents from editors where contents is not null;'
```

(That's on macOS, on Linux the path is different.)

This returns the contents of all files where content has been saved.

**Comment by Timoffey** [comment]
When I was in a switching process from sublime to zed, this feature worked.
But now, on Cmd+Q it asks me if I want to save changes, and if I update zed, it quits without saving any changes.
Maybe I need to mark anything explicitly? But I didn't find any options in the settings.

**Comment by mrnugget** [comment]
Hey @Timoffey, did you see this part in [Joseph's comment](https://github.com/zed-industries/zed/issues/4985#issuecomment-2248988244)?

> The only case in which this doesn't work is if you open up a brand new instance of Zed, one that has no projects in it, and then open a new file. 

Maybe you had an untitled window open?

**Comment by Timoffey** [comment]
@mrnugget wow, that's true... sorry me. So I'll create a folder zed-drafts as a project to hack it. Thanks!

**Comment by ovitrif** [comment]
Exactly, another user of Sublime as actual text editor, and without this I can't really use Zed, despite loving it.

So, while I am an user, I am in no way active user and can't be without this.

Thanks and good luck, maybe once I level up my Rust game, I can help, until then I'll be just an annoying user expecting devs to do the work :D

**Comment by mrnugget** [comment]
Sorry, haven't had the time to look into this more with our SSH release last week. Hope to take another stab at it before the end of the year.

**Comment by mrnugget** [comment]
No, sorry about that, super super busy with other things and I also don't have any traction on this issue since it requires (I think/fear) refactoring how Zed thinks about workspaces/projects/worktrees.

**Comment by vKarter** [comment]
Absolutely! We really need this feature. :)

**Comment by dehlen** [comment]
I see this issue is closed. Is there any other issue I am not finding where potential future improvements are tracked regarding untitled buffers? Would like to subscribe to any changes in this direction as I am also a sublime text user looking for this feature to really dive into Zed.

**Comment by dionisvl** [comment]
Why is it closed?

**Comment by git-mosis** [comment]
Just learned about Zed and immediately wanted to see if this feature is available however I see this is closed with no reason why. Any updates appreciated.

**Comment by denisazevedo** [comment]
This is related:

https://github.com/zed-industries/zed/issues/15098
