### ISSUE TITLE
Emmet snippets support

### ISSUE THREAD

**Issue by chloerei** [zed-industries/zed#4992]
### Check for existing issues

- [X] Completed

### Describe the feature

Allow use emmet snippets to input html/css. 

vscode docs https://code.visualstudio.com/docs/editor/emmet

### If applicable, add mockups / screenshots to help present your vision of the feature

![emmet](https://user-images.githubusercontent.com/49931/221176939-50523ae2-ef25-42ec-b2ad-dbdadc7aa264.gif)

**Comment by bbb651** [comment]
I'm not aware of an existing emmet implementation in rust, I was interested in building one a couple of years ago so I claimed the crate [emmet](https://crates.io/crates/emmet) but never got around to it, I think it can be pretty useful to have as a crate so if you're interested in taking ownership of the crate I'm happy to transfer it, I might give it another try myself it sounds fun (although I'm on linux so I can't work on the integration with zed)

**Comment by faisalahammad** [comment]
Love to see emmet support in Zed +1

**Comment by ggarciajr** [comment]
👍

**Comment by ShubhamPatilsd** [comment]
agreed, in vscode "wrap with html" is one of my most used commands

**Comment by mandarliev** [comment]
btw, do you plan on adding React snippets?

**Comment by nilanjan2002** [comment]
> btw, do you plan on adding React snippets?

Agreed, would be an absolute life saver

**Comment by d1y** [comment]
https://github.com/aca/emmet-ls

**Comment by endigma** [comment]
I would settle for even an analogue of emmet syntax, I **very** frequently use basic things like `div*5` and `div.flex.flex-row.gap-2`, it doesn't necessarily need to be a full Emmet snippet implementation to be useful.

**Comment by jasonc624** [comment]
just started using zed right now and i desperately need this AND to be able to click on a symbol from the html to its definition (angular). Thats really all i need and zed would be perfect for me

**Comment by michaelGregoire** [comment]
For this editor to be a serious replacement for either vs code or even vim, we need this… full stop.

**Comment by airamstudio** [comment]
this is urgently needed full stop

**Comment by Moshyfawn** [comment]
The significance of the feature is determined by the number of 👍 reactions on the original post, rather than any fabricated urgency comments. Please avoid cluttering threads with generic replies such as "+1" or "urgently needed" in the future. It only makes the issue harder to follow and does not increase its priority in any way.

**Comment by airamstudio** [comment]
> The significance of the feature is determined by the number of 👍 reactions on the original post, rather than any fabricated urgency comments. Please avoid cluttering threads with generic replies such as "+1" or "urgently needed" in the future. It only makes the issue harder to follow and does not increase its priority in any way.

New to this, appreciate the feedback! I'll contribute more specific comments in the future. I'd advice you not to dismiss other people's comments as 'fabricated' though... my intention was sincere, no need for passive-aggressiveness 😅

**Comment by muhrusdi** [comment]
waiting for this

**Comment by joyal-jij0** [comment]
The only feature that doesn't allow me to switch to zed. Zed should had emmet from the start.

**Comment by nicecraftz** [comment]
Its happening **Hooray! 🎉**

**Comment by d8vjork** [comment]
I think snippets in general should be a thing in Zed, I always switch to Zed then just close it because my speed of coding has been reduced by so much.

Don't care its lacking some LSP features, but snippets for PHP, JS, etc should be a must.

**Comment by wallyfoo** [comment]
> I think snippets in general should be a thing in Zed, I always switch to Zed then just close it because my speed of coding has been reduced by so much.

This is veering off topic, but there's a point to be made for Textmate -> Sublime Text snippet support. Or something of the like. There's plenty of community action out there that would slot right in.

**Comment by thekiwidev** [comment]
I am reluctant to use Zed cause of many features VS code had provided out of the box, like auto close tags, suggestions, and most importantly "EMMET" IntelliSense for all file types, even if it can't be done out of the box, at least we should get an extension that does this... Go Zed

**Comment by aecsar** [comment]
Good things are happening : #9910

**Comment by aecsar** [comment]
Many thanks, @osiewicz for making this happen!

**Comment by osiewicz** [comment]
Hey,
We've landed experimental Emmet support as an extension. It is *not* being suggested right now as outlined in [original PR](https://github.com/zed-industries/zed/pull/9910#issuecomment-2035190445). You have to install it manually from the extension store.
It should only kick in for HTML files for now, though the work to associate an extension with more than one language server is already underway.

**Comment by osiewicz** [comment]
The extension is out. You should be able to install it from both latest Preview and Stable Zed builds.

**Comment by michaelGregoire** [comment]
@osiewicz Thanks to everyone involved in making this happen!

**Comment by JosephTLyons** [comment]
Since initial support for this is is now out, let's close this issue out. Please open new issues to request additional features related to Emmet support.

**Comment by arshabh** [comment]
What about emmet support for React codebases with .jsx and .tsx extensions ?

**Comment by gabeidx** [comment]
> What about emmet support for React codebases with .jsx and .tsx extensions ?
> 
> 

@arshabh That should already be possible today. What is your configuration and which problems are you experiencing?

Unless you meant "emmet auto completing React components from your code base", in which case it's not an issue with emmet itself I believe.

**Comment by tomasguba** [comment]
The extension mentioned in this thread is causing the following LSP errors while it's enabled:

```
[WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
[WARN] Generic lsp request to node failed: Unhandled method textDocument/implementation
```

You can't jump to the the definition of a function or it's implementation for the **PHP language.**
There's literally nothing anywhere on the internet about this being related to the _Emmet_ extension.

I learned the hard way.

**Comment by gabeidx** [comment]
> Support for .vue, please.

@tuiris see above:

> Please open new issues to request additional features related to Emmet support.

**Comment by andrienko** [comment]
Emmet support is a joke in zed. Useless.

It is supposed to be quick (so I type `div` in HTML or `w100p` in CSS, press a button and it expands). In zed it works via suggestions, and when there is no match - there is no completion. And sometimes when there is a snippet - it is not at the top, so you have to select it via arrows or something, which is not quick.

There is no dedicated command to expand emmet abbreviation, either.
