### ISSUE TITLE
Restarting language server (that resolves code issues) leaves project issues icon

### ISSUE THREAD

**Issue by JacobWithACapitalJ** [zed-industries/zed#4993]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After adding a `go.work` file to a monorepo root and restarting the language server (so that gopls picks up the new workspace file to resolve the issues), leaves the `project diagnostics` icon still showing the previous errors.

### Environment

Zed: 0.74.2
Go: 1.20
macos: 13.0.1 (intel)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="352" alt="Screenshot 2023-02-24 at 09 28 36" src="https://user-images.githubusercontent.com/49863988/221142564-d94b9e74-c24e-4be6-bfac-9329cb849ee1.png">
<img width="88" alt="Screenshot 2023-02-24 at 09 28 30" src="https://user-images.githubusercontent.com/49863988/221142568-4faea1a8-8266-4680-b55e-781a828ad81c.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2023-02-24T09:21:13 [INFO] unhandled notification window/logMessage:
{
  "type": 1,
  "message": "2023/02/24 09:21:13 errors loading workspace: You are outside of a module and outside of $GOPATH/src.\nIf you are using modules, please open your editor to a directory in your module.\nIf you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.\n\tsnapshot=6\n\tdirectory=file:///Users/*******/Documents/GitHub/*******\n"
}
2023-02-24T09:21:27 [ERROR] oneshot canceled
2023-02-24T09:21:27 [INFO] unhandled notification window/logMessage:
{
  "type": 3,
  "message": "2023/02/24 09:21:27 go env for /Users/*******/Documents/GitHub/synap\n(root /Users/*******/Documents/GitHub/*******)\n(go version go version go1.20 darwin/amd64)\n(valid build configuration = true)\n(build flags: [])\nGOMOD=/dev/null\nGOFLAGS=\nGOCACHE=/Users/*******/Library/Caches/go-build\nGOMODCACHE=/Users/*******/go/pkg/mod\nGOWORK=/Users/*******/Documents/GitHub/*******/go.work\nGO111MODULE=\nGOPRIVATE=\nGOPROXY=https://proxy.golang.org,direct\nGOINSECURE=\nGONOSUMDB=\nGOPATH=/Users/*******/go\nGOSUMDB=sum.golang.org\nGONOPROXY=\nGOROOT=/usr/local/go\n\n"
}
2023-02-24T09:21:28 [INFO] unhandled notification window/logMessage:
{
  "type": 3,
  "message": "2023/02/24 09:21:28 go/packages.Load zed-industries/community#1\n\tsnapshot=0\n\tdirectory=file:///Users/*******/Documents/GitHub/*******\n\tquery=[builtin github.com/*******/*******/libraries/dev-hq-2/...]\n\tpackages=11\n"
}
2023-02-24T09:21:28 [INFO] unhandled notification window/logMessage:
{
  "type": 3,
  "message": "2023/02/24 09:21:28 go/packages.Load zed-industries/community#1: updating metadata for 274 packages\n"
}
```

**Comment by JosephTLyons** [comment]
We've done some work to improve Zed's diagnostics being up to date, so I think I will close this issue out. If you are still running into this, please open up a new issue!
