### ISSUE TITLE
Ability to add extra file extensions for a specific type

### ISSUE THREAD

**Issue by noozo** [zed-industries/zed#4994]
### Check for existing issues

- [X] Completed

### Describe the feature

I would love for the settings to allow specifying non-standard file extensions to a particular type. For example:
- (Elixir) Surface (.sface) files as the HTML type
- mix.lock as JSON type
- Dockerfile as Docker type (unsure this one is actually supported in Zed yet)

As a side note, it would be lovely if Elixir support included the ability to syntax highlight sigil content, including surface (~F, ~H), as most Phoenix Live View code includes rendered HTML inside sigils and it currently looks sad and hard to code.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="870" alt="image" src="https://user-images.githubusercontent.com/3353/221026041-aeca7b98-f97a-4ae0-98e1-0b9aad4805d2.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/3353/221026140-ab8cbaf0-bff5-438b-99e6-0a2111c43451.png">

**Comment by JosephTLyons** [comment]
Hey @noozo, we now have support for this. You can add this setting to your `settings.json` file and map whatever you'd like:

```json
"file_types": {
    "JSON": ["flake.lock"],
    "JSONC": ["**/.zed/**/*.json", "**/zed/**/*.json", "**/Zed/**/*.json", "tsconfig.json"]
},
```
