### ISSUE TITLE
Errors in deleted file remain in diagnostics

### ISSUE THREAD

**Issue by Pringlers** [zed-industries/zed#4997]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you delete the files with the errors, Zed should not display errors anymore.

Reproduce: 
- Create a file with syntax error
- Make sure Zed detects it
- Delete the file and every occurrence
- Observe Zed still shows the errors

### Environment

Zed: v0.73.3 (stable)
OS: macOS 13.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/98678118/220276264-f144ec53-a25f-4319-8724-db3511032b42.mov

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Nothing special

**Comment by osiewicz** [comment]
I can't repro this with Rust project anymore (or a .js one).

**Comment by JosephTLyons** [comment]
> I can't repro this with Rust project anymore (or a .js one).

I just tested in our zed.dev TypeScript project and for me, the errors reported disappeared when deleting the file, so I think this is fixed now. I'm going to close this issue out.
