### ISSUE TITLE
Keymap does not work

### ISSUE THREAD

**Issue by zongUMR** [zed-industries/zed#5001]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I defined customized keymap but it doesn't work.

### Environment

```
Zed: v0.73.3 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="894" alt="Screenshot 2023-02-20 at 11 06 12" src="https://user-images.githubusercontent.com/11454175/220000302-d0fad314-cbf4-40e6-bdb9-b5ebff68109d.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Althougth the below log has an `invalid keystore ctrl-c-d` error, but I already changed it to `ctrl-c ctrl-d`, but doesn't work either.
[log.txt](https://github.com/zed-industries/community/files/10779122/log.txt)

**Comment by obahareth** [comment]
I am also having an issue where I am not sure what happens when I press keys.

I tried to add some shortcuts I am familiar with from VS Code, but none of them are working:

```json
{
  "context": "Editor",
  "bindings": {
    "cmd-shift-k": "editor::DeleteLine",
    "alt-up": "editor::MoveLineUp",
    "alt-down": "editor::MoveLineDown",
    "alt-shift-up": "editor::DuplicateLine",
    "alt-shift-down": "editor::DuplicateLine"
  }
}

```

**Comment by munozr1** [comment]
I am trying to re-bind ctrl-1 to shift-1 because my pinky hurts 🤕 

```
{
    "context": "Editor && vim_mode == normal && !VimWaiting && !menu",
    "bindings": {
      // put key-bindings here if you want them to work only in normal mode
      "space l": "pane::SplitRight",
      "space h": "pane::SplitLeft",
      "space p": "file_finder::Toggle",
      "space k": "editor::MoveRight",
      "shift-1": ["pane::ActivateItem", 0],
      "shift-2": ["pane::ActivateItem", 2],
      "shift-3": ["pane::ActivateItem", 3]
    }
  },
```

However, it does not seem to be working 😞

**Comment by lougreenwood** [comment]
Is there any movement on this? I want to map `editor:MoveLineUp` to `ctrl-k`, but that's already taken by `editor::CutToEndOfLine`.

I've spent so long trying to figure this out. It seems like this is an ordering issue, the default's shouldn't take precedence when evaluating a key binding, the user's should have priority.

Are there plans to address in an upcoming release? 🙏

**Comment by JosephTLyons** [comment]
I just tested the original keymap submitted in this issue and all of the bindings work for me, so I think the original issue here is solved. For any other issues brought up in this thread, please open up a new issue!
