### ISSUE TITLE
Zed crashed while renaming a symbol (Typescript LSP): assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#5002]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Tried to use the `Rename symbol` feature on a global function in a typescript file.
I saw how Zed renamed the function and half a second later it crashed.

After restarting Zed the function had the old name again, but a second try worked perfectly.

### Environment

Zed: v0.73.3 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Zed logs:
```
2023-02-16T13:38:43 [ERROR] thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Local {0: 7004}`,
 right: `Local {0: 7006}`: invalid insertion': crates/text/src/text.rs:1817   0: backtrace::capture::Backtrace::new
   1: Zed::init_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::assert_failed_inner
   8: core::panicking::assert_failed
   9: text::BufferSnapshot::summary_for_anchor
  10: gpui::executor::any_local_future::{{closure}}
  11: async_task::raw::RawTask<F,T,S>::run
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <gpui::platform::mac::platform::MacForegroundPlatform as gpui::platform::ForegroundPlatform>::run
  25: gpui::app::App::run
  26: Zed::main
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: std::rt::lang_start::{{closure}}
  29: std::rt::lang_start_internal
  30: _main
```

**Comment by JosephTLyons** [comment]
I'm not able to reproduce this crash, but if you run into it again, feel free to ping me here or open a new issue!
