### ISSUE TITLE
File search is flickering if files are created/deleted in the background

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#5006]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The file search modal is flickering if there are file created/deleted in the background.
I had a build script running and wanted to search for something in the meantime.
See recording:

https://user-images.githubusercontent.com/19362696/218990205-2c9ccb22-c67d-4549-acd7-169376904e37.mov

If you look closely you can see it flickers between `No matches` and the results.

### Environment

Zed: v0.72.5 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I believe we landed a fix for this in:

- https://github.com/zed-industries/zed/issues/7519

So I'm going to close this issue out!
