### ISSUE TITLE
Show something when workspace is empty

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#5007]
### Check for existing issues

- [X] Completed

### Describe the feature

Examples from VS Code and IDEA:
![Snipaste_2023-02-15_16-30-27](https://user-images.githubusercontent.com/40336192/218974809-8cf3009c-7b34-4d71-ab06-90a2e7e1cf79.png)
<img width="1680" alt="Snipaste_2023-02-15_16-31-37" src="https://user-images.githubusercontent.com/40336192/218974817-6ae25db5-559a-44eb-8e21-6b638fcdf215.png">

current zed:
<img width="1520" alt="Snipaste_2023-02-15_16-32-35" src="https://user-images.githubusercontent.com/40336192/218975205-7a5c1e89-156f-432b-957a-25ad8cb04b68.png">

**Comment by maxdeviant** [comment]
We have a welcome screen now.
