### ISSUE TITLE
Support dragging and dropping files from finder into Zed

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5008]
### Check for existing issues

- [X] Completed

### Describe the feature

We now have support for dragging and dropping files onto the Zed icon, but we should also support dragging files directly into Zed.

**Comment by maxdeviant** [comment]
@SomeoneToIgnore I believe this is supported now with the work you did, yea?

**Comment by SomeoneToIgnore** [comment]
Indeed, we can close it, thanks!

**Comment by jocelinqueau** [comment]
is there already requests for drag and drop files on dock icon ?
