### ISSUE TITLE
Go to definition opens new tab even if target file is already open in another panel

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#5009]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproude (for me this is a typescript project, but don't think it matters):
- Have file `A` which contains the definition for something that is used in file `B`.
- Have file `A` open on the left and file `B` on the right in a split panel configuration.
- Click on `Go to definition` on the thing in file `B`.
-> Opens up file `A` in the right panel instead of focusing the already open file on the left.

I find this a bit annoying when I, for example, have code open on the left and a test file on the right.

### Environment

Zed: v0.72.5 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by blackeyeddan** [comment]
Using splits to group / organize files is very handy for workflow.

With the current behavior, the editor essentially throws chaos into intentionally organized splits, which erodes flow. Grouping splits quickly begins to feel futile. It shouldn't be futile! It's a handy technique.

Thanks @N8th8n8el for opening the issue. 🙏
