### ISSUE TITLE
Improve autocompletion order

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/zed#5013]
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode rust-ananlyzer puts `Vec` type before `vec!` macro when autocompleting something like
```rust
fn main() {
    let x: V
}
```
In Zed autocomplete order also definitely should respect at least the case of item being autocompleted, and if possible also try rearanging completions arrording to some heuristic or maybe even some pretrained neural network, which would assign weight to completions

Also, using macros for types is quite rare, so they can be moved down

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1440" alt="Screenshot 2023-02-09 at 17 43 25" src="https://user-images.githubusercontent.com/43210583/217844772-a724efe7-0fb2-4416-bee3-bbe333bc0e65.png">
<img width="1440" alt="Screenshot 2023-02-09 at 17 42 42" src="https://user-images.githubusercontent.com/43210583/217844781-c4f2af50-5ce1-49df-a869-9a2b9c398f14.png">

**Comment by DannyJJK** [comment]
Similar issue with PHP (in this case using the Laravel framework).

I start typing `whereBetween` however the first result on the autocomplete is `orWhereBetween` and the actual one I want is further down.

<img width="444" alt="image" src="https://github.com/zed-industries/zed/assets/11057501/80fdf031-650b-4b03-a7b4-14ed16bb12c9">

**Comment by mrnugget** [comment]
Just to record this here: Theo also mentioned this in [his video](https://www.youtube.com/watch?v=ZOYp6-k9HhE)

![screenshot-2024-02-13-10 18 38@2x](https://github.com/zed-industries/zed/assets/1185253/5ea1e797-6d46-45d2-a788-5f990bee4a28)

**Comment by mrnugget** [comment]
@DannyJJK that last one, that's a different issue: we rank recent items higher. There's a very thin line after the first 2 results. Admittedly, it's really hard to spot and we should probably improve that UI.
---

In https://github.com/zed-industries/zed/pull/7727 we just made some improvements that should help with the bug that Theo reported and some of the others reported in here (`string`/`String` and `UIAlert`). The `vec` vs. `Vec` thing in Rust is still unchanged (and matches VS Code btw.!)

**Comment by Dorjderem2002** [comment]
Same problem happens with C++ too.

**Comment by mrnugget** [comment]
> Same problem happens with C++ too.

Can you provide more information? i.e. what did you type, what did you expect to see, what did you see instead, etc.?

**Comment by Dorjderem2002** [comment]
> > Same problem happens with C++ too.
> 
> Can you provide more information? i.e. what did you type, what did you expect to see, what did you see instead, etc.?

Sure, when I write "for" it does not show for loop instead it shows for_each function. I assume for loop should be most used. And I never used for_each in my project or file so it is recommending it out of nowhere. Zed version 0.125.3

![Uploading Screenshot 2024-03-09 at 4.59.28 PM.png…]()

**Comment by mrnugget** [comment]
I can't see that screenshot, but that does sound like an issue. Like I wrote above:

> I think it would be best to have separate issues with clear descriptions on how to reproduce the problem and what the expected/actual behavior are

Can you create a new ticket for this?

**Comment by bernardinorafael** [comment]
Same here, not fixed yet...

<img width="680" alt="image" src="https://github.com/zed-industries/zed/assets/102430354/b14930e8-b3df-41a4-8cb4-b20d9267e7b3">

**Comment by wolfadex** [comment]
I've created a new ticket https://github.com/zed-industries/zed/issues/12590 with steps to reproduce in Elm

**Comment by Benjamin-van-Heerden** [comment]
Tailwind completion order are really not so great as well

![image](https://github.com/user-attachments/assets/9fc6d215-347f-4893-8b45-23fb5683d3e5)

It should be suggesting just "px-2,..." when I scroll down, they are there, but this should be the first suggestion

**Comment by tinrab** [comment]
Can somebody else confirm that this is still an issue? This was addressed in #2169, but it breaks completions for me. If I enable "smart case" in `fuzzy::match_strings`, meaning it's always `true`, then completions seem to work as expected. I've tested it for Rust and TypeScript.

**Comment by bernardinorafael** [comment]
@tinrab 

running ok for me(zed 0.147.2)

**Comment by TeoBale** [comment]
Running version 0.151.2 I realize that the autocomplete order is really inconvenient...

I noticed this by trying zed in tailwind and typescript

**Comment by ZencareJake** [comment]
I created a new discussion [here](https://github.com/zed-industries/zed/discussions/21222), but wanted to post on this closed issue regardless. See the screenshot below. The ideal suggestion, `filteredTagString` shows up 6th in this list.

<img width="984" alt="Screenshot 2024-11-26 at 11 54 01 AM" src="https://github.com/user-attachments/assets/d42d7721-6bb0-46b3-9388-03af77c4d227">

**Comment by T1ckbase** [comment]
0.215.3

![Image](https://github.com/user-attachments/assets/840818c3-a004-4ff3-830f-443e31956650)
