### ISSUE TITLE
Error hover tooltip cutting from the upper boundary

### ISSUE THREAD

**Issue by khushmeeet** [zed-industries/zed#5015]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When hovering over a function to view the error, the tooltip that shows the function signature is cutting from the upper boundary.

<img width="1085" alt="Screenshot 2023-02-07 at 2 57 50 PM" src="https://user-images.githubusercontent.com/8711912/217351845-af7c4ac1-ef5a-4b7d-9a18-be866c30f00a.png">

Let me know, if anything else is required.

### Environment

Zed: v0.71.3 (stable)
OS: macOS 13.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I somehow missed this duplicate. Closing in favor of:

- https://github.com/zed-industries/zed/issues/5227
