### ISSUE TITLE
Show errors/warning counts in tree view

### ISSUE THREAD

**Issue by djc** [zed-industries/zed#5016]
### Check for existing issues

- [X] Completed

### Describe the feature

In VS Code, I rely a lot on the explorer showing me in which files the compiler has found errors/warnings. Ideally, it would both use colors and a number of errors/warnings to indicate how badly my current state is broken.

**Comment by nilskch** [comment]
I know you are dealing with an enormous amount of requests/Issues and I really appreciate your work! I wanted to ask if this Issue is somewhere on the roadmap? This is something that would make my DX significantly better. I am going all-in on Zed but this is something I miss from VSCode.

**Comment by djc** [comment]
FWIW, this seemed to be one of the most popular replies in this recent Twitter thread:

https://twitter.com/thorstenball/status/1772196113128272116

**Comment by solhosty** [comment]
Yes this would be a fantastic add.

**Comment by ActuallyHappening** [comment]
I would greatly benefit from this feature

**Comment by sudomaxime** [comment]
Same here, our toolchain creates and modify files automatically, sometimes it's hard to know we have an issue before compile time. I'm absolutely in love with Zed and it's the last remaining feature that would make zed my daily driver !

**Comment by nikuz** [comment]
Same issue, the only two missing parts for me are the source control tab and this one. I'm fine not having the source control tab any time soon, but not seeing errored files in the tree view and in the opened tabs list doesn't allow me to switch to Zed today.

**Comment by SomeoneToIgnore** [comment]
If that could help, Zed has an outline view which can be opened for any [multi] buffer.

There's no coloring, but if you open a diagnostics multi buffer it will show all files with errors in a tree:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0a5e63d4-1455-41fd-80ae-a39fe1fa86a6">

**Comment by AustinCase** [comment]
> If that could help, Zed has an outline view which can be opened for any [multi] buffer.
> 
> There's no coloring, but if you open a diagnostics multi buffer it will show all files with errors in a tree: <img alt="image" width="1728" src="https://private-user-images.githubusercontent.com/2690773/350681486-0a5e63d4-1455-41fd-80ae-a39fe1fa86a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDIyMTksIm5iZiI6MTcyMzcwMTkxOSwicGF0aCI6Ii8yNjkwNzczLzM1MDY4MTQ4Ni0wYTVlNjNkNC0xNDU1LTQxZmQtODBhZS1hMzlmZTFmYTg2YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDYwNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTM1ZWRjN2E0NjFjODFhNjRiZTMwNTkxOGQxZjA5YTcyNWQ4N2M4ZWFjNjlhMjI5YjUxNjEwMDM0YTJjYjBmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RzkA0J5b5W44vSqmgoLyB2XRz7N3luETk5hxmvQZjv4">

This is definitely helpful, but just like a file is yellow if it has a change in it... having it red is immensely helpful. I don't have the screen real-estate to keep this window open -- love Zed, but this is the thing I miss most about vscode

**Comment by mattrltrent** [comment]
Any update on this? Or even an alpha/beta build we can use to have this feature early?

**Comment by sarzhann** [comment]
This feature is the only deal-breaker for switching to Zed...

**Comment by zeyaddeeb** [comment]
Agreed, with large monorepos this is essential.

**Comment by sbusso** [comment]
👍🏻

**Comment by Lubba-64** [comment]
tried to edit bevy in zed, it was not an optimal experience. it also doesn't work well with my VST

**Comment by ActuallyHappening** [comment]
Would still benefit from an error lens implementation
