### ISSUE TITLE
Clicking a split of an unfocused Zed window should focus that split

### ISSUE THREAD

**Issue by rkusa** [zed-industries/zed#5020]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Clicking a split of an unfocused Zed window should focus that split.

Consider a Zed window with two splits, a left and right one, and the following steps:
1. The left split is focused
2. Whole Zed window is unfocused
3. Zed window is re-focused by clicking into the right split

Current behaviour: left split is still active, I have to click again into the left split to activate it
Expected behaviour: the right split is focused right away

I mainly notice this when I have a terminal split open and want to insert/paste something into the terminal. I click into the terminal of an unfocused Zed window and start typing/pasting right away. But this often ends up in another editor split that was focused before (and it takes me a moment to realize that I don't see my input because the focus is not where I expected it to be).

### Environment

Zed: v0.71.3 (stable)
OS: macOS 13.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Current behaviour in Zed:

https://user-images.githubusercontent.com/409021/216304443-1fa4689d-9db4-4536-b6e2-c76cd985d86d.mov

Expected behaviour using VSCode as an example:

https://user-images.githubusercontent.com/409021/216304561-745af7ee-28ae-4824-b3d1-c6b8854338dd.mov

Ideal solution: IMO the ideal solution would actually be a mix of both. I dislike that VSCode moves the cursor. I'd rather have it to just focus the split. So clicking a split of an unfocused should IMHO focus the split (but not change the cursor's position).

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This seems to be fixed in current Zed, so I'm going to close this issue out.
