### ISSUE TITLE
Call drops as soon as accepted, with `ERROR gpui::executor] error connecting to room`

### ISSUE THREAD

**Issue by russelldb** [zed-industries/zed#5022]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- I call my colleague
- The show as connected
- Very soon after the call is dropped
- This error happens in the log `ERROR gpui::executor] error connecting to room`

Likewise, if they call me, they experience the above.

### Environment

Zed: 0.70.1 (stable)
OS: macOS 13.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/feedback/files/10534664/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @russelldb Hey @russelldb, I think I'm going to close this issue out, as it is pretty old. If you are still running into it in current Zed, please open up a new issue!
