### ISSUE TITLE
Support formatting a code block / selection

### ISSUE THREAD

**Issue by shekharnwagh** [zed-industries/zed#5026]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode/IntelliJ has the option to select a block of code and format only that instead of the whole file. This would be helpful if you only want to reformat newly added/altered code instead of the whole file to avoid creating big diffs.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="250" alt="Screenshot 2023-01-28 at 2 11 11 PM" src="https://user-images.githubusercontent.com/41412488/215256274-45c55179-c794-4b31-b717-8cb65e2d657d.png">

**Comment by ElijahBus** [comment]
Certainly a needed feature 👍

**Comment by sangelxyz** [comment]
Also neovim has it, you use = to format the selection, very handy feature which is missing?

**Comment by kurtpeniket** [comment]
> Also neovim has it, you use = to format the selection, very handy feature which is missing?

@sangelxyz , I have this in my `keymap.json` to emulate what I'm used to in nvim:

```json
  {
    "context": "Editor && VimControl && !VimWaiting && !menu",
    "bindings": {
      "space =": "editor::Format",
    }
```

 but that formats the entire file as far as I know and not just the visual block like in vim unfortunately.

**Comment by hferreiro** [comment]
There's a PR for this at https://github.com/zed-industries/zed/pull/18752.

**Comment by mrnugget** [comment]
Fixed by https://github.com/zed-industries/zed/pull/18752
