### ISSUE TITLE
Not respecting vim theme

### ISSUE THREAD

**Issue by SilentGlasses** [zed-industries/zed#5027]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have airline theme in my vim setup and editing in the Zed Terminal does not respect that... 

### Environment

Zed: 0.70.0 (stable)
OS: macOS 12.6.3
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screen Shot 9](https://user-images.githubusercontent.com/22822565/215002337-7ec7bb91-777f-406c-9739-cf54f90f3485.png)

The left is Zed, the right is Terminal

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

No errors in the logs

**Comment by mikayla-maki** [comment]
Thanks for the fix, almost a year since you first found the bug!

**Comment by clo4** [comment]
@mikayla-maki Any time! I’ve got a list of other stuff I’ll be fixing soon too :) Just had to wait for some free time. The Zed codebase is fantastic to work in
