### ISSUE TITLE
Feed for blog

### ISSUE THREAD

**Issue by d12bb** [zed-industries/zed#5030]
### Check for existing issues

- [X] Completed

### Describe the feature

The Zed blog should have a [RSS](https://www.rssboard.org/rss-specification)/[Atom](https://www.rfc-editor.org/rfc/rfc5023)/[JSON](https://www.jsonfeed.org/) feed, for people to follow in their news aggregators.

**Comment by maxdeviant** [comment]
The RSS feed for the Zed blog can be found at [https://zed.dev/blog.rss](https://zed.dev/blog.rss).
