### ISSUE TITLE
Add a `http_proxy` setting

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#5032]
### Check for existing issues

- [X] Completed

### Describe the feature

FYI, programmers in China face restrictions from the [Great Firewall](https://en.wikipedia.org/wiki/Great_Firewall)(GFW) and require a VPN service to access the internet freely. When I launch Zed, it automatically downloads the LSP server, which is blocked by the GFW and fails to complete. Therefore, I need to set the `http_proxy` env variable in a terminal session and open Zed using the CLI.

It would be very helpful if there were settings related to `http_proxy`. Take VS Code as an example:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/40336192/214094468-10c39410-07ba-4615-a9a6-4dfde3d5f83d.png">

**Comment by Banyc** [comment]
This project uses `isahc = { version = "1.7.2", default-features = false, features = ["static-curl", "text-decoding"] }
` which [respects](https://github.com/sagebind/isahc/blob/096aff7b13f4ff5bb474fdc27bc30b297a2968f6/src/config/mod.rs#L456) both `https_proxy` and `http_proxy`. To let the app be aware of this, you should follow the [macOS mechanism](https://stackoverflow.com/a/25912736/9920172) by setting env like this:

```bash
launchctl setenv https_proxy http://address
launchctl setenv http_proxy http://address
```
Now you can access the Internet.

**Comment by smallfish** [comment]
try to start zed with command line:

```bash
cd /Applications/Zed.app/Contents/MacOS
export http_proxy=xxx
export https_proxy=yyy
zed
```

**Comment by seven1240** [comment]
It doesn't seems to work with OpenAI API, is there any recommended way to use a proxy with OpenAI API ?

**Comment by crazybits** [comment]
i am using zed behind proxy, tired all workarounds above does not solve my issue, assistant still nothing response,
