### ISSUE TITLE
Don't ask to save multibuffers if all files with changes are already open elsewhere in the workspace

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5033]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This would be the next step in reducing the redundancy we have around asking users to save files being closed that are still open elsewhere in the editor.  Relates to

- https://github.com/zed-industries/zed/issues/5615

### Environment

Zed: 0.70.0 (preview)
OS: macOS 13.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hmm, this one might actually already been implemented - can someone else double check? Don't know how this snuck past me.

**Comment by Moshyfawn** [comment]
> Hmm, this one might actually already been implemented - can someone else double check and we can simply close out if so? Don't know how this snuck past me.

I think this confirms that it's already been implemented. I'm going to close this issue.

https://github.com/zed-industries/zed/assets/16290753/82c2b6b0-6781-40d3-b343-6f6230d46265

**Comment by JosephTLyons** [comment]
Yep! Thanks for sanity checking that @Moshyfawn!
