### ISSUE TITLE
Add a scrollbar in popovers

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#5034]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/40336192/213897434-00a334a6-d4a6-4dcf-8143-f5382a51fee4.png">

### If applicable, add mockups / screenshots to help present your vision of the feature

Example from idea, VS Code:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/40336192/213897463-70f80ec2-0a4b-4fa0-8730-5015ac76b5fe.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/40336192/213897496-25257309-16a0-4070-982f-0e25275eb4a6.png">

**Comment by osiewicz** [comment]
I added support for info popovers in #20184; I wonder if we need it for diagnostics as well, seeing as they shouldn't be nearly as long as info popovers.
