### ISSUE TITLE
GPUI window transparency

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#5040]
### Check for existing issues

- [X] Completed

### Describe the feature

I don't have access to the alpha so not sure if this is supported but judging from screenshots it does not seem to be the case.

It would be very nice to have the option to make the background of zed windows slightly transparent, similarly to my current go-to setup of running neovim in alacritty with 75% background opacity.

Besides the obvious aesthetic that blends in nicely with almost any wallpaper/theme, this also allows me to put an actively updating window behind the editor (either an unrelated application or something that is hot reloading the file I am editing). The background dims the window behind the editor enough so it does not distract from editing, but still allows me to monitor the changes in the other window live without having to sacrifice editing space or alt+tabbing around.

At least on Linux it is sometimes possible to request the compositor to adjust the opacity of specific windows, but that also makes text transparent. For readability it would be important that the application handles background transparency by itself, so text and important UI symbols can remain fully opaque. The main gotcha with this appears to be that different platforms have different requirements for transparent windows (e.g. macOS wants non-premultiplied alpha, Wayland wants premultiplied).

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="915" alt="image" src="https://user-images.githubusercontent.com/2588851/213169721-981fba3d-59de-4c7d-ab5f-b499b9be36d0.png">

**Comment by jansol** [comment]
Reminder that issue popularity is programmatically tracked based on :+1: reactions to the top post, not by comments.

**Comment by WilliamWelsh** [comment]
My b

**Comment by jansol** [comment]
Since blur is a particularly popular component to this request, the platform-specific features for implementing that appear to be:
- macOS:
  - [NSVisualEffectView](https://developer.apple.com/documentation/appkit/nsvisualeffectview) Apple's way or the highway - note that the original configuration values for the view got deprecated very quickly
- Windows:
  - [Acrylic material](https://learn.microsoft.com/en-us/windows/apps/design/style/acrylic)
  - [Mica material](https://learn.microsoft.com/en-us/windows/apps/design/style/mica)
  - [DWM_BLURBEHIND](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ns-dwmapi-dwm_blurbehind)
  - see also https://github.com/tauri-apps/window-vibrancy/
- Linux/Wayland: (plain alpha blending is part of Wayland core)
  - [org_kde_kwin_blur](https://wayland.app/protocols/kde-blur) seems to be the only application-controlled way that is actually usable somewhere
  - [ext_blur_v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/272) based on org_kde_kwin_blur so migrating should be easy once this gets accepted
  - Some compositors have their own blur settings, but those are generally not directly controllable by the application
  - Some compositors are explicitly against having blur support
- Linux/X11:
  - [the UNIX philosophy](https://github.com/yshui/picom), not application-controllable
  - KDE has some settings for forcing blur, may or may not be application-controllable (saw some mention of an API but didn't dig into it)
  - GNOME has extensions for forcing blur, does not seem to be application-controllable

**Comment by jansol** [comment]
So upon further inspection I concluded that the only somewhat consistent solution across platforms is:
* The undocumented `CGSSetWindowBackgroundBlurRadius` (should be safe as long as Terminal.app relies on it)
* DWM_BLURBEHIND
* org_kde_kwin_blur/ext_blur_v1

The NSVisualEffectView and Acrylic/Mica materials have Opinions that are based on the system theme (tint towards bright/dark), which gets very awkward unless one designs separate themes for dark and light mode and automatically switches based on the active system theme. Additionally such themes would not really look the intended way on platforms other than the one they were created on. OTOH with the plain blur the theme can specify a semitransparent background color to tint the background in the desired way.

I started working on the somewhat portable solution (well, the macOS part of it - PR coming as soon as I have time to clean it up a bit), but I won't be touching the more platform specific ones. Those should be easy enough to add as alternatives later on if someone feels like they would be good to have.

**Comment by Luk4h** [comment]
Hello @jansol, a lover of the transparent look here as well. I would like to know how is your progress so far? I tried myself to achieve something and so far I got to render the blurred/transparent view below the zed view. I believe meaning if we got to remove the background of the zed view, to see the blurred/transparent background. I am not very comfortable with rust, which made a bit hard for me to find anything related to the zed background, at least not relevant. And my tries with applying a transparent background with themes was not successful as well. I believe this would be the first step to achieve the style we are looking for, later we would need to create a way to toggle this, since most users do not want it. I would love to contribute to this feature since I love the look. If you are willing to collaborate, or anyone else interested. Hit me up. I have [forked the zed repo](https://github.com/Luk4h/zed) with my progress.

**Comment by jansol** [comment]
@Luk4h I got it working with the `CGSSetWindowBackgroundBlurRadius` approach, which turned out to be much simpler more convenient for theming than `NSVisualEffectView`. Right now my implementation is mainly stuck in figuring out how to do the plumbing from the theme to the GPUI window. I've made some decent progress with that, but it's still missing some bits before it's ready for a PR.

**Comment by Luk4h** [comment]
Are you able to share your work? Interested in seeing your approach, since It was what I aimed for, but got lost and ended up using the NSVisualEffectView, which can't get it to work together with the CAMetalLayer.

**Comment by JosephTLyons** [comment]
This is now available in [v0.130.0-pre](https://zed.dev/releases/preview/0.130.0).

**Comment by krstp** [comment]
A snippet of code that show a guidance how to properly implement it would be much appreciated. It is not exactly clear how to leverage it correctly.

**Comment by Luk4h** [comment]
> A snippet of code that show a guidance how to properly implement it would be much appreciated. It is not exactly clear how to leverage it correctly. Thanks.

On the [patch notes](https://arc.net/l/quote/ejwpgawl) it mentions how to specify the new property. You can also override it using the "experimental.theme_overrides" property on your settings file.

**Comment by ThatOneCalculator** [comment]
Any chance we could get this on Linux too?

**Comment by xcrap** [comment]
<img width="2559" alt="Screenshot 2024-04-11 at 01 54 33" src="https://github.com/zed-industries/zed/assets/828596/2b390d92-22b3-46d9-9ef7-da6e2dad4dba">

Still have to fix some borders, but looks so sweet :)

**Comment by evwltrs** [comment]
![image](https://github.com/zed-industries/zed/assets/20270765/81736725-2d90-427d-92ee-4e2826f0284c)

For the impatient Gruvbox users like me based off @xcrap's config.

```json
"experimental.theme_overrides": {
    "background.appearance": "blurred",
    "background": "#4c464290",
    "editor.background": "#00000030",
    "editor.gutter.background": "#00000030",
    "tab_bar.background": "#00000030",
    "terminal.background": "#00000030",
    "toolbar.background": "#00000030",
    "tab.active_background": "#28282820",
    "tab.inactive_background": "#00000000",
    "status_bar.background": "#00000030",
    "title_bar.background": "#00000030",
    "panel.background": "#00000030",
    "border.variant": "#00000000",
    "scrollbar.track.border": "#00000000",
    "editor.active_line.background": "#00000000"
  }
  ```

**Comment by jansol** [comment]
Linux support for transparent and blurred windows has been merged in #10973

Blur is only supported on Wayland with compositors supporting the kde-blur protocol for now -- i.e. Plasma.

On X11 it may be possible to configure a compositor to blur window backgrounds but Zed has no way to influence that.

**Comment by Jervx** [comment]
https://github.com/user-attachments/assets/f47a8bd9-cf13-475b-806d-ccc3037454df

**Comment by hfjallemark** [comment]
> simplescreenrecorder-2024-08-07_15.19.23.mp4

Sorry for off topic but what theme is that @Jervx?

**Comment by Jervx** [comment]
> > simplescreenrecorder-2024-08-07_15.19.23.mp4
> 
> Sorry for off topic but what theme is that @Jervx?

Catppuccin Themes
![image](https://github.com/user-attachments/assets/627ebc07-3d7a-4af7-9fc3-506c7fd3936b)

**Comment by martin503** [comment]
Darcula config I use for transparent:
```
"experimental.theme_overrides": {
      "background.appearance": "transparent",
      "background": "#282a3669",
      "editor.background": "#282a3669",
      "editor.gutter.background": "#282a3669",
      "tab_bar.background": "#282a3669",
      "terminal.background": "#282a3600",
      "toolbar.background": "#282a3669",
      "tab.active_background": "#282a3642",
      "tab.inactive_background": "#282a3669",
      "status_bar.background": "#282a3669",
      "title_bar.background": "#282a3669",
      "panel.background": "#282a3679",
      "border.variant": "#282a3669",
      "scrollbar.track.border": "#282a3669",
      "editor.active_line.background": "#420069",
      "players": [
        {
          "selection": "#420069"
        }
      ]
    }
```
kudos, great feature!
Now waiting for image in background https://github.com/zed-industries/zed/discussions/11086 :D

**Comment by AurevoirXavier** [comment]
Is possible to change the transparent level? Something like 0.75, 0.5.

**Comment by xcrap** [comment]
> Is possible to change the transparent level? Something like 0.75, 0.5.

It's not like rgba values, it's hexadecimal values. The first six characters (RRGGBB) represent the red, green, and blue components, just like in a normal hexadecimal color code, The last two characters (AA) represent the alpha (transparency) channel, where 00 is fully transparent and FF is fully opaque. So yes, you can control the transparency as you like using hexadecimal values instead of the more common opacity in css for example. 

For example, black with full transparency, 00000000, black with no transparency 000000FF, black with a tiny bit of transparency 000000DD.

Here's an example converter: https://rgbacolorpicker.com/rgba-to-hex#google_vignette

When the color has no transparency you don't need to add nothing, for example pure white #FFFFFFF can be like does do not need to add #FFFFFFFF

**Comment by xcrap** [comment]
Unfortunately they have none of this information in their docs, they should, it's important.

**Comment by AurevoirXavier** [comment]
> > Is possible to change the transparent level? Something like 0.75, 0.5.
> 
> It's not like rgba values, it's hexadecimal values. The first six characters (RRGGBB) represent the red, green, and blue components, just like in a normal hexadecimal color code, The last two characters (AA) represent the alpha (transparency) channel, where 00 is fully transparent and FF is fully opaque. So yes, you can control the transparency as you like using hexadecimal values instead of the more common opacity in css for example.
> 
> For example, black with full transparency, 00000000, black with no transparency 000000FF, black with a tiny bit of transparency 000000DD.
> 
> Here's an example converter: https://rgbacolorpicker.com/rgba-to-hex#google_vignette
> 
> When the color has no transparency you don't need to add nothing, for example pure white #FFFFFFF can be like does do not need to add #FFFFFFFF

Yep, I know. But thanks for your explnation.

I mean if there's a way to specify a `0.5` (which can be automatically converted to hex) or `DD` and apply or append these to every background, that would be excellent.

Currently, I need to identify every color utilized by the theme and add the alpha channel to each value.

**Comment by xcrap** [comment]
I mean it's easy to convert any color to hex and vice versa, the alpha channel you can convert the alpha value (from 0 to 1) to a percentage and then into a hexadecimal value (00 to FF).

Ex: Alpha: 0.125 (12.5%) → 12.5% of 255 = 32 → 20 in hex

But the above link you can convert any rgba color to their hex with alpha equivalent. When you change the theme settings you have a almost real time preview so it's very easy to change and check and mostly colors will have a common transparency levels or you will use like 3 or 4 different depending on each setting but it's not the worse. I think they mentioned this use about something related with GPU rendering but i'm not sure, but they could have a converted to accept rgba or hsla values or example, not sure if it's a great priority as the theme development as the plugins still need a lot of work. The theme converted they have is rust based and there are some themes I would love to port but it's too much work :)

**Comment by AurevoirXavier** [comment]
I set the alpha channel to `60`.

With no file opening, the background is almost 100% transparent:å

<img width="534" alt="image" src="https://github.com/user-attachments/assets/c99b724a-0796-4717-b14b-1b4507b547e3">

With file openning:

<img width="502" alt="image" src="https://github.com/user-attachments/assets/bb509adc-ad7d-4b40-b8c3-110a02ab5cd9">

**Comment by xcrap** [comment]
Keep in mind for example the editor is affected by two backgrouds, so there are multiple layers.

"background": "#00000060", 
"editor.background": "#00000060",

So if you set full transparency in the main background and set some transparency in the editor it's one thing, if you set some transparency in the main background plus some transparency in the editor background it will affect differently. 

<img width="978" alt="Screenshot 2024-09-11 at 10 14 45" src="https://github.com/user-attachments/assets/159797b8-e661-4d19-b1a2-93417467f6bb">
<img width="1003" alt="Screenshot 2024-09-11 at 10 14 37" src="https://github.com/user-attachments/assets/0320ea51-008b-4334-acf7-ae1e7ffd4e85">

 "background.appearance": "blurred",

Also keep in mind that having the background appearance blurred is different than transparent, this is something you'll have to play with. The best thing is start with a clean slate and using the auto complete you figure out the values for each thing. In their docs they recommend to see a theme to figure out the settings but yes, they should have much more info in the settings docs to help us figure everything out :)

**Comment by thedeveloper-sharath** [comment]
Is there anyway this works on windows? I mean, i tried changing the settings and all but no effect?

**Comment by maxiim3** [comment]
> To each their own but why would you want transparency on an editor? Terminal I can understand to a point.
> 
> Pretty sure there will be an option at some point but nothing that I've seen as yet.
> 
> The docs are all here by the way... https://zed.dev/docs/configuration/configuring-zed

You want continuity in your overall theme. Also I like to have a slight transparency on my windows, I find it pretty and pleasant

**Comment by lewyuburi** [comment]
Looks great! Thanks! 


<img width="1218" alt="image" src="https://github.com/user-attachments/assets/d76e64a8-1224-4e64-b3c3-cec57348977a">

```
"theme": {
  "mode": "system",
  "light": "One Light",
  "dark": "One Dark"
},
"experimental.theme_overrides": {
  "background.appearance": "blurred",
  "background": "#3b414daa",
  "title_bar.background": "#3b414ddf",
  "toolbar.background": "#282c3344",
  "tab_bar.background": "#2f343e33",
  "tab.inactive_background": "#2f343e00",
  "tab.active_background": "#282c3311",
  "panel.background": "#2f343e44",
  "editor.background": "#282c334f",
  "status_bar.background": "#3b414dee"
}
```

Pd: values from https://github.com/zed-industries/zed/blob/main/assets/themes/one/one.json

**Comment by momchilvanchev** [comment]
It would really be awesome if the transparency was cross theme. Meaning you don't have to set the actual color of each part, but you can set the overall transparency or individual transparency of the parts, regardless of the theme set...

**Comment by Msouza91** [comment]
> It would really be awesome if the transparency was cross theme. Meaning you don't have to set the actual color of each part, but you can set the overall transparency or individual transparency of the parts, regardless of the theme set...

Absolutely especially for weirdos like me that use the Automatic Light/Dark option for my setup and I have to pick one of the themes to look right...
Weird how this was easier to get working, despite a more convoluted setup, with Neovim than with Zed while looking nicer. :(

https://github.com/user-attachments/assets/22801585-c3e5-4d7f-abc6-25a7cace18a0

**Comment by jansol** [comment]
> It would really be awesome if the transparency was cross theme. Meaning you don't have to set the actual color of each part, but you can set the overall transparency or individual transparency of the parts, regardless of the theme set...

That would end up looking bad due to the way UI components are layered in Zed.

> Weird how this was easier to get working, despite a more convoluted setup, with Neovim than with Zed while looking nicer. 

Same issue, neovim has exactly 1 layer of transparency to take care of while Zed has around 4 layers for buttons and then another set for tooltips on top of that.

As for light/dark mode switching, that Just Works if you configure Zed to use separate themes for light and dark mode and both of those themes are set up for transparency.

**Comment by rodolfo-arg** [comment]
Base theme: Monospace
<img width="1349" alt="Screenshot 2024-12-02 at 2 24 21 pm" src="https://github.com/user-attachments/assets/c3b440b2-aad6-4a19-a701-2f5620e6d66b">

```
"experimental.theme_overrides": {
    "renamed.background": "#FFFFFF20",
    "search.match_background": "#FFFFFF20",
    "ghost_element.background": "#00000010",
    "ghost_element.hover": "#00000099",
    "background.appearance": "blurred",
    "background": "#000000CC",
    "editor.background": "#00000010",
    "editor.gutter.background": "#00000010",
    "title_bar.background": "#000000DF",
    "toolbar.background": "#00000010",
    "terminal.background": "#00000000",
    "status_bar.background": "#000000DF",
    "tab.active_background": "#000000",
    "tab.inactive_background": "#00000000",
    "tab_bar.background": "#00000010",
    "panel.background": "#00000010",
    "border": "#00000000",
    "border.variant": "#00000000",
    "scrollbar.track.border": "#00000000",
    "scrollbar.track.background": "#00000000",
    "scrollbar.thumb.background": "#00000000",
    "scrollbar.thumb.hover.background": "#00000000",
    "scrollbar.thumb.active.background": "#00000000",
    "scrollbar.thumb.border": "#FFFFFF90",
    "editor.line_highlight": "#00000000",
    "editor.active_line.background": "#00000000",
    "editor.selection.background": "#00000000",
    "editor.selection.foreground": "#00000000",
    "editor.selection.border": "#00000000",
    "editor.selection.inactive.foreground": "#00000000",
    "editor.selection.inactive.border": "#00000000",
    "editor.selection.active.background": "#00000000",
    "editor.selection.active.foreground": "#00000000",
    "editor.selection.active.border": "#00000000",
    "editor.selection.inactive.background": "#00000000"
  }
```

**Comment by mvaliolahi** [comment]
You can try this one:

  "experimental.theme_overrides": {
    "background.appearance": "blurred",
    "background": "#09090bBB",
    "panel.background": "#00000000",
    "editor.background": "#00000000",
    "tab_bar.background": "#00000000",
    "terminal.background": "#00000000",
    "toolbar.background": "#00000000",
    "tab.inactive_background": "#00000000",
    "tab.active_background": "#3f3f4650",
    "border": "#00000000",
    "status_bar.background": "#09090bBB",
    "title_bar.background": "#09090bBB",
    "border.variant": "#00000000",
    "scrollbar.track.background": "#52525b20",
    "scrollbar.track.border": "#00000000",
    "scrollbar.thumb.background": "#52525b30",
    "scrollbar.thumb.border": "#00000000",
    "elevated_surface.background": "#00000090",
    "surface.background": "#00000090",
    "editor.active_line_number": "#ffffffcc",
    "editor.gutter.background": "#00000000",
    "editor.indent_guide": "#ffffff30",
    "editor.indent_guide_active": "#ffffff80",
    "editor.line_number": "#ffffff80",
    "editor.active_line.background": "#3f3f4640"
  },

**Comment by solrac97gr** [comment]
Do this transparency tweaks work in Full screen mode in MacOS?

**Comment by heydoyouknowme0** [comment]
@mvaliolahi 
![screenshot-2024-12-23-04-37-14](https://github.com/user-attachments/assets/4205fb11-b4bf-4e0b-94eb-9a48837208fa)
would you know how to make files background transparent, I wasn't able find the variable.

**Comment by lamcc21** [comment]
> Base theme: Monospace <img alt="Screenshot 2024-12-02 at 2 24 21 pm" width="1349" src="https://private-user-images.githubusercontent.com/176843882/391400459-c3b440b2-aad6-4a19-a701-2f5620e6d66b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAxMzIyMTMsIm5iZiI6MTc0MDEzMTkxMywicGF0aCI6Ii8xNzY4NDM4ODIvMzkxNDAwNDU5LWMzYjQ0MGIyLWFhZDYtNGExOS1hNzAxLTJmNTYyMGU2ZDY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMVQwOTU4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjQ1NmExYjY1MWU2MzI0ZDNjMzhmNDVkMjE0NDQ2MWU4YWU0MGFkMTZkYmMyMGU5MDY1YWVlOTBhNDQ4MTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vFRbR8O1hQ9PiQHibt21b_pcaZeVWWLBbIddr5sMEqw">
> 
> ```
> "experimental.theme_overrides": {
>     "renamed.background": "#FFFFFF20",
>     "search.match_background": "#FFFFFF20",
>     "ghost_element.background": "#00000010",
>     "ghost_element.hover": "#00000099",
>     "background.appearance": "blurred",
>     "background": "#000000CC",
>     "editor.background": "#00000010",
>     "editor.gutter.background": "#00000010",
>     "title_bar.background": "#000000DF",
>     "toolbar.background": "#00000010",
>     "terminal.background": "#00000000",
>     "status_bar.background": "#000000DF",
>     "tab.active_background": "#000000",
>     "tab.inactive_background": "#00000000",
>     "tab_bar.background": "#00000010",
>     "panel.background": "#00000010",
>     "border": "#00000000",
>     "border.variant": "#00000000",
>     "scrollbar.track.border": "#00000000",
>     "scrollbar.track.background": "#00000000",
>     "scrollbar.thumb.background": "#00000000",
>     "scrollbar.thumb.hover.background": "#00000000",
>     "scrollbar.thumb.active.background": "#00000000",
>     "scrollbar.thumb.border": "#FFFFFF90",
>     "editor.line_highlight": "#00000000",
>     "editor.active_line.background": "#00000000",
>     "editor.selection.background": "#00000000",
>     "editor.selection.foreground": "#00000000",
>     "editor.selection.border": "#00000000",
>     "editor.selection.inactive.foreground": "#00000000",
>     "editor.selection.inactive.border": "#00000000",
>     "editor.selection.active.background": "#00000000",
>     "editor.selection.active.foreground": "#00000000",
>     "editor.selection.active.border": "#00000000",
>     "editor.selection.inactive.background": "#00000000"
>   }
> ```

this is awesome thanks

**Comment by ntwrknrd** [comment]
Is this broken/incomplete on macOS or am I missing something? I've set transparent values for every applicable setting I could find:

```
// Zed settings
//
{
  "experimental.theme_overrides": {
    "panel.overlay_background": "#11111Bcc",
    "panel.overlay_hover": "#11111Bcc",
    "pane.focused_border": "#11111Bcc",
    "pane_group.border": "#11111Bcc",
    "panel.focused_border": "#11111Bcc",
    "hidden.background": "#11111Bcc",
    "editor.subheader.background": "#11111Bcc",
    "title_bar.inactive_background": "#11111Bcc",
    "border.transparent": "#11111Bcc",
    "background.appearance": "transparent",
    "editor.background": "#11111B66",
    "editor.gutter.background": "#11111B66",
    "editor.active_line.background": "#11111B66",
    "panel.background": "#11111Bcc",
    "toolbar.background": "#11111Bcc",
    "tab_bar.background": "#11111Bcc",
    "title_bar.background": "#11111Bcc",
    "status_bar.background": "#11111Bcc",
    "tab.active_background": "#11111Bcc",
    "tab.inactive_background": "#11111Bcc",
    "terminal.background": "#11111Bcc",
    "scrollbar.track.background": "#11111Bcc",
    "scrollbar.thumb.background": "#11111B00",
    "border": "#585b70cc",
    "border.variant": "#585b70cc",
    "border.focused": "#585b70cc",
    "border.disabled": "#585b70cc",
    "elevated_surface.background": "#11111Bcc",
    "surface.background": "#11111Bcc",
    "background": "#11111Bcc"
  }
}
```

And yet, only certain parts of the window are transparent:

![Image](https://github.com/user-attachments/assets/61886908-2ca4-4043-9dc8-ba04eb30754f)

![Image](https://github.com/user-attachments/assets/3422cd77-9b37-45f9-9d29-8b8ef1805d92)

**Comment by jansol** [comment]
@ntwrknrd the different components are stacked on top of each other (and "background") and after a couple of layers with "cc" alpha there's not a lot of the underlying color left

**Comment by JxavierP** [comment]
Can we have a simple opacity options in the preference that simply turns down the background transparency similar to how alacritty does it? The need literally remake existing themes just to get transparency is such a hassle. Is this a limitation of gpui or just a no-go for the zed editor?

**Comment by xXMariahScaryXx** [comment]
> Can we have a simple opacity options in the preference that simply turns down the background transparency similar to how alacritty does it? The need literally remake existing themes just to get transparency is such a hassle. Is this a limitation of gpui or just a no-go for the zed editor?

bumping this

**Comment by jansol** [comment]
Please open a new issue for additional transparency settings.

**Comment by saatvik333** [comment]
Hi, is there a way to add blur to the popup menus of zed?

<img width="617" height="514" alt="Image" src="https://github.com/user-attachments/assets/f0757518-8d0b-4acd-936b-d8155a79c45e" />


I got the transparency setup for the menus and inside my niri config; enabled blur for popup menus. But it doesn't work

<img width="369" height="185" alt="Image" src="https://github.com/user-attachments/assets/5d6db93d-3f9c-456d-8c95-553f879ace61" />


Is this correct?

> Zed's custom graphics engine (GPUI) renders everything—the editor, the terminal, the command palette, and the menus—into a single flat image that it sends to Niri. Because Niri only receives one single flat image for the whole Zed window, it cannot selectively blur the text *behind* the command palette. Niri only knows how to blur the desktop wallpaper behind the transparent parts of the window.

WM: Niri 26.04
Zed: 1.0.0

**Comment by jansol** [comment]
> I got the transparency setup for the menus and inside my niri config; enabled blur for popup menus. But it doesn't work

It doesn't work because - like the comment you are quoting says - Zed's popup menus are not real popups, they are drawn inside the main window. And Zed itself does not do any blurring between its internal UI layers.

**Comment by NyllRE** [comment]
blurring on the internal UI layers would be the icing on the cake
