### ISSUE TITLE
Allow to pin tab

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#5046]
### Check for existing issues

- [X] Completed

### Describe the feature

Sometimes a very useful option turns out to be the ability to pin cards. Working with VSCode, I prefer to have, for example, an open terminal on the card equivalent to files, so as not to clutter up the view with additional panels. I then pin a card with a terminal so as not to accidentally close it and that it is always at hand. BTW, IMO pinned card should only present an icon - as, for example, in Chrome.

**Comment by Costiss** [comment]
Sugestion, pinned tabs be independent of the tabs it self. So the editor can have only pinned tabs
Something like this -> https://github.com/ThePrimeagen/harpoon

**Comment by bbernag** [comment]
is this not possible yet?
