### ISSUE TITLE
When close window which has multiple unsaved edits, it's better to have `Don't Save for all` option in the popped up dialog

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#5047]
### Check for existing issues

- [X] Completed

### Describe the feature

If I have two unsaved edits, and then I close window, I expect to have an option to Don't Save for all, so I don't need to interactive with the dialog twice

https://user-images.githubusercontent.com/22256154/211442416-79f67520-a17f-4a1c-9617-f968fc4bb60b.mov

Here is how vscode do, when I click Don't save, it just close the window directly, whatever how many unsaved edits here:

https://user-images.githubusercontent.com/22256154/211442430-ad348ebc-55f7-49c5-bda3-e1d1efeec6f3.mov

Sorry if the title seems too long, I'm not sure how to express it well

**Comment by JosephTLyons** [comment]
This has been in Zed for some time now. Closing this out.
