### ISSUE TITLE
Add light theme for https://zed.dev/

### ISSUE THREAD

**Issue by LimingFang** [zed-industries/zed#5050]
### Check for existing issues

- [X] Completed

### Describe the feature

The zed editor itself has different theme, i think it's better to provide at least dark/light theme for the website. IMO, the rust related web usually has three or more themes like (rust, coal, light) 

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://user-images.githubusercontent.com/28479651/211232412-a52ae85a-daf8-4490-89ae-7af6e239b5e6.png)

**Comment by maxdeviant** [comment]
zed.dev only has a light theme now.
