### ISSUE TITLE
Support Links in Go Doc Comments

### ISSUE THREAD

**Issue by existagon** [zed-industries/zed#5060]
### Check for existing issues

- [X] Completed

### Describe the feature

[Links can be added to Go Doc Comments](https://go.dev/doc/comment#links) which can be very useful for linking to external documentation or for clarification. Currently, Zed does not support this and shows the comment without the hyperlink. 

### If applicable, add mockups / screenshots to help present your vision of the feature

Example from go doc:
```go
// Package json implements encoding and decoding of JSON as defined in
// [RFC 7159]. The mapping between JSON and Go values is described
// in the documentation for the Marshal and Unmarshal functions.
//
// For an introduction to this package, see the article
// “[JSON and Go].”
//
// [RFC 7159]: https://tools.ietf.org/html/rfc7159
// [JSON and Go]: https://golang.org/doc/articles/json_and_go.html
```

Current Behaviour:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/55012346/210163131-0c9eb393-1595-44b6-a4dc-7071d4baf13e.png">

With support added:
<img width="641" alt="Screenshot 2023-01-01 at 01 58 32" src="https://user-images.githubusercontent.com/55012346/210163311-3bd8e619-4bc6-4d78-a522-6df0feaa338c.png">

**Comment by JosephTLyons** [comment]
Hey @existagon, I'm going to close this issue out for a more generic issue here:

- https://github.com/zed-industries/zed/issues/4310

Please upvote it with a 👍
