### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by tarainfluxd** [zed-industries/zed#5064]
### Check for existing issues

- [X] Completed

### Describe the feature

When editing Markdown (.md) files, it would be great if there were a live preview in another pane so both would be alongside each other.

I hesitate to [reference](https://github.com/atom/markdown-preview) it, but, it worked pretty well in Atom.

**Comment by dwt** [comment]
This seems to work fine? `cmd-shift-p` -> `markdown: open preview`?

**Comment by SomeoneToIgnore** [comment]
It does, we've just forgotten to close the issue, thank you.
