### ISSUE TITLE
explorer auto reveal configurable

### ISSUE THREAD

**Issue by zhylmzr** [zed-industries/zed#5071]
### Check for existing issues

- [X] Completed

### Describe the feature

I will jump to `node_modules` when i click on the library statement in TypeScript. At this time, the explorer will be a long and deep tree.

I hope there is a switch that can be turned off, or a exclude directories/files config.

<img width="675" alt="SCR-20221221-ewv" src="https://user-images.githubusercontent.com/15730824/208808364-a4572454-de29-44be-9baf-1c60fe719986.png">

The VSCode example:
<img width="626" alt="SCR-20221221-f0u" src="https://user-images.githubusercontent.com/15730824/208808969-6812f046-74a6-4973-ac8b-0c1f83ed78fa.png">

**Comment by williamdes** [comment]
I may try to implement this, it is very annoying not having a setting to change this.
Since I use Zed on Linux (a couple of days since CTRL+P works) it has been a major workflow disruption since vscode.

**Comment by williamdes** [comment]
In fact I think this issue can be closed.
Fixed by https://github.com/zed-industries/zed/pull/3604

Use the config
```json
  "project_panel": {
    "auto_reveal_entries": false
  }
```

cc @mikayla-maki

**Comment by shirshak55** [comment]
Is there anyway to exclude node modules only?

**Comment by RonaldEAM** [comment]
Can I have auto reveal without this "Gitignored entries are never auto revealed"?
When I go to a type or definition in a file in node_modules I want the project panel to focus that file, so I can explore other files in that package.
I feel like we should have a setting so auto reveal doesn't necessarily uses .gitignore
Because even with cmd-shift-e it doesn't auto reveal the file in node_modules

**Comment by Cammisuli** [comment]
> Can I have auto reveal without this "Gitignored entries are never auto revealed"? When I go to a type or definition in a file in node_modules I want the project panel to focus that file, so I can explore other files in that package. I feel like we should have a setting so auto reveal doesn't necessarily uses .gitignore

As a temporary workaround, you can still "reveal" the file by going into the command prompt. Open the command prompt and type in `reveal in project panel`, and it will open the node_modules folder.
