### ISSUE TITLE
`editor::ScrollCursorCenter` is busted in Atom keymap

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5073]
A user reported not being able to use this command:

`"cmd-<": "editor::ScrollCursorCenter"`

**Comment by Moshyfawn** [comment]
This seems to be an old enough problem where the system has changed quite drastically and the leybinds are now built in. The only confusion I can see is that the keymap is `cmd-<`, which implies that it also needs the `shift` key pressed, which may be unintuitive. @JosephTLyons
