### ISSUE TITLE
Adding `"enter": "menu::Confirm"` to the keybindings causes issues with confirming things

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5078]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Adding `"enter": "menu::Confirm"` causes Zed to have issues with confirming things.  If you try to rename a file in the project panel, the name reverts.  If you try to select an item in a picker, the action doesn't take.  I do realize that this binding is a default one and so it doesn't need to be added to a keymap.json file, but I feel like it should still work.

### Environment

Zed 0.67.2 – /Applications/Zed Preview.app
macOS 13.1
architecture arm64

**Comment by notpeter** [comment]
Pretty sure this is no longer an issue.
