### ISSUE TITLE
Language server failure: rust (permission denied)

### ISSUE THREAD

**Issue by wangeguo** [zed-industries/zed#5085]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After opening the rust project, the status bar shows downloading Rust Language Server, but it has been unsuccessful, repeated attempts have failed, I have enabled VPN

### Environment

Zed 0.66.0 – /Applications/Zed.app
macOS 12.6.1
architecture x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

11:17:33 [INFO] ========== starting zed ==========
11:17:33 [INFO] Database migrated to version 1
11:17:33 [INFO] set environment variables from shell:/bin/zsh, path:/Users/wangeguo/flutter/bin:/usr/local/opt/bison/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/wangeguo/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wangeguo/.cargo/bin
11:18:18 [INFO] ========== starting zed ==========
11:18:19 [INFO] set environment variables from shell:/bin/zsh, path:/Users/wangeguo/flutter/bin:/usr/local/opt/bison/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/wangeguo/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wangeguo/.cargo/bin
11:20:37 [INFO] set status on client 0: Authenticating
11:20:45 [INFO] set status on client 0: Connecting
11:20:46 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
11:20:48 [INFO] add connection to peer
11:20:48 [INFO] waiting for server hello
11:20:48 [INFO] got server hello
11:20:48 [INFO] set status to connected (connection id: 0, peer id: 17199)
11:20:48 [INFO] set status on client 0: Connected { peer_id: PeerId(17199), connection_id: ConnectionId(0) }
11:22:16 [WARN] request completed with error: failed to connect to the server
11:22:16 [WARN] failed to send user avatar request: failed to connect to the server
11:23:16 [ERROR] Os { code: 2, kind: NotFound, message: "No such file or directory" }
11:25:45 [WARN] request completed with error: failed to connect to the server
11:25:45 [ERROR] no cached binary
11:25:45 [ERROR] error downloading release: failed to connect to the server
11:25:45 [ERROR] error downloading release: failed to connect to the server
11:26:06 [ERROR] Invalid argument (os error 22)
11:26:07 [ERROR] Invalid argument (os error 22)
11:26:07 [ERROR] Invalid argument (os error 22)
11:26:29 [ERROR] Invalid argument (os error 22)
11:26:30 [ERROR] Invalid argument (os error 22)
11:26:30 [ERROR] Invalid argument (os error 22)
11:26:35 [ERROR] Invalid argument (os error 22)
11:28:31 [WARN] request completed with error: failed to connect to the server
11:28:31 [ERROR] no cached binary
11:28:31 [ERROR] error downloading release: failed to connect to the server
11:33:35 [INFO] ========== starting zed ==========
11:33:36 [INFO] set environment variables from shell:/bin/zsh, path:/Users/wangeguo/flutter/bin:/usr/local/opt/bison/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/wangeguo/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wangeguo/.cargo/bin
11:33:36 [INFO] set status on client 0: Authenticating
11:33:36 [INFO] set status on client 0: Connecting
11:33:37 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
11:33:39 [INFO] add connection to peer
11:33:39 [INFO] waiting for server hello
11:33:39 [INFO] got server hello
11:33:39 [INFO] set status to connected (connection id: 0, peer id: 17270)
11:33:39 [INFO] set status on client 0: Connected { peer_id: PeerId(17270), connection_id: ConnectionId(0) }
11:36:43 [ERROR] unexpected item event after pane was dropped
11:37:08 [ERROR] unexpected item event after pane was dropped
11:51:32 [ERROR] timed out waiting on app_will_quit
11:51:34 [INFO] ========== starting zed ==========
11:51:34 [INFO] set environment variables from shell:/bin/zsh, path:/Users/wangeguo/flutter/bin:/usr/local/opt/bison/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/wangeguo/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wangeguo/.cargo/bin
11:51:34 [INFO] set status on client 0: Authenticating
11:51:34 [INFO] set status on client 0: Connecting
11:51:36 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
11:51:37 [INFO] add connection to peer
11:51:37 [INFO] waiting for server hello
11:51:37 [INFO] got server hello
11:51:37 [INFO] set status to connected (connection id: 0, peer id: 17374)
11:51:37 [INFO] set status on client 0: Connected { peer_id: PeerId(17374), connection_id: ConnectionId(0) }
11:51:48 [ERROR] Invalid argument (os error 22)
11:51:49 [ERROR] Invalid argument (os error 22)
11:51:54 [ERROR] Permission denied (os error 13)
11:57:05 [ERROR] Permission denied (os error 13)
11:57:19 [ERROR] Permission denied (os error 13)
12:00:36 [INFO] ========== starting zed ==========
12:00:36 [INFO] set environment variables from shell:/bin/zsh, path:/Users/wangeguo/flutter/bin:/usr/local/opt/bison/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/wangeguo/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wangeguo/.cargo/bin
12:00:37 [INFO] set status on client 0: Authenticating
12:00:37 [INFO] set status on client 0: Connecting
12:00:38 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
12:00:39 [INFO] add connection to peer
12:00:39 [INFO] waiting for server hello
12:00:39 [INFO] got server hello
12:00:39 [INFO] set status to connected (connection id: 0, peer id: 17426)
12:00:39 [INFO] set status on client 0: Connected { peer_id: PeerId(17426), connection_id: ConnectionId(0) }
12:00:50 [ERROR] Invalid argument (os error 22)
12:00:54 [ERROR] Invalid argument (os error 22)
12:00:58 [ERROR] Permission denied (os error 13)

**Comment by JosephTLyons** [comment]
We haven't had many reports of this recently, so I'm going to optimistically close this issue out. Please open a new one if you run into this again.
