### ISSUE TITLE
Allow piping of command output into Zed CLI

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5093]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

This was suggested by Yasyf.  The Zed CLI should be able to take in input from a previous command.  With the code CLI, you can do:

```sh
ls | code -
```

to open up VS Code with the output of `ls`.

### Describe the solution you'd like

-

**Comment by bitfield** [comment]
Yes, this would be very useful—I use it all the time in VS Code.

With the terminal in the bottom dock, it's usually only a few lines high, so when a command that produces more output than that, it's hard to read without lots of fiddly scrolling. Instead, I pipe it into Code:

```sh
kubectl -h | code -
```

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/zed-industries/zed/pull/16084 and should be a part of Preview already?
If not already, comes next Wednesday.
