### ISSUE TITLE
Move files to system trash when deleting a file within Zed

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5094]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

A user had a great suggestion of not hard deleting files when they are deleted within Zed, but instead moving them into the system trash bin.  Despite us not really hearing this feedback a lot, I think it's important to reduce the chances of destroying a user's work (for example, if a file isn't tracked by Git).

It probably makes sense for us to add a setting for this, since some users do seem to like the idea of hard deleting.  VS Code has a setting for this:

<img width="619" alt="SCR-20221204-j5x-2" src="https://user-images.githubusercontent.com/19867440/205509539-00018aa8-4eba-490c-a90d-e2d5a2719053.png">

### Describe the solution you'd like

-

**Comment by cgiacomi-work** [comment]
Just deleted a file by mistake and lost 2 hours of work because I had not committed my changes, if the file had been send to the trash can I could have recovered my work!
