### ISSUE TITLE
Expand `log` to `console.log()`

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5096]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

In JetBrains’ tooling, in JS and TS, you can type `log` then hit `tab` and it will expand to `console.log()`.  It’s a small thing, but it’s so nice.  We should see if we can add this feature.  Maybe this calls for some generic system that allows you to define, per language, maps that link some input text into an expanded form.

### Describe the solution you'd like

https://user-images.githubusercontent.com/19867440/205404075-3ebdb865-7651-41e8-81cb-019fee3f87d6.mov

**Comment by mediabeastnz** [comment]
Bumping as this is one little thing that makes me miss VSCode. It's just muscle memory but such a time saver!

**Comment by plato-creative** [comment]
bumping this.

**Comment by monarcode** [comment]
Waiting desperately for snippet support

**Comment by jhoonyKorolkov** [comment]
This little thing still doesn’t work, come on guys, we’re really looking forward to it)

**Comment by SomeoneToIgnore** [comment]
This is a part of https://github.com/zed-industries/zed/issues/4611 actually and not sure how hard, but somebody have to work on this.

**Comment by JosephTLyons** [comment]
This week's release mentions how to configure this in the release notes for snippet support!

https://zed.dev/releases/stable/0.140.5

**Comment by bearfriend** [comment]
For anyone coming across this, the release notes are gone, but the [Snippets docs](https://zed.dev/docs/snippets?highlight=snipp#snippets) have this exact request covered

**Comment by JosephTLyons** [comment]
Here are the release notes attached to the GitHub release: Zed.dev only goes back so far with the release history, but everything can be found in GitHub releases:

https://github.com/zed-industries/zed/releases/tag/v0.140.5
