### ISSUE TITLE
Add data types to Python autocompletion menu entries

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5097]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See if we can add python data types within the autocompletion menu.  PyRight has the type info, even if it's unknown.  We can see it on hover.  

<img width="514" alt="SCR-20221129-mm8" src="https://user-images.githubusercontent.com/19867440/204649772-0b13c380-be2c-4dc1-a9dd-a87c7f67d5f6.png">
<img width="267" alt="SCR-20221129-mmh" src="https://user-images.githubusercontent.com/19867440/204649775-876835f5-71ed-412b-8cf8-b9ae020ee3ff.png">

But the autocompletion menu is missing data type info for any given symbol (class, function, variable, etc.)

---

Update

Aside from the bug in:

- https://github.com/zed-industries/zed/issues/8126

It seems we do have type info in the autocompletions now, however, there may still be bugs?

https://github.com/zed-industries/zed/assets/19867440/c476825a-ce8d-4942-be58-9237ccb41568

This is a bit weird, `run_command` has no inline type info, but has the type info in an additional documentation popover on the right, while `batch_run_commands` has the opposite. I'll leave this to the team to decide what to do here. Should we close this out in favor of another issue? I think this bug, if its on our end, should still go into quality week.

### Expected behavior

-

### Environment

Zed 0.66.0 – /Applications/Zed Preview.app
macOS 13.0.1
architecture arm64

**Comment by JosephTLyons** [comment]
Aside from the bug in:

- https://github.com/zed-industries/zed/issues/8126

It seems we do have type info in the autocompletions now, however, there may still be bugs?

https://github.com/zed-industries/zed/assets/19867440/c476825a-ce8d-4942-be58-9237ccb41568

This is a bit weird, `run_command` has no inline type info, but has the additional documentation popover on the right, while `batch_run_commands` has the opposite. I'll leave this to the team to decide what to do here. Should we close this out in favor of another issue? I think this bug, if its on our end, should still go into quality week.

**Comment by JosephTLyons** [comment]
Maybe this would be a good one for @ForLoveOfCats?

**Comment by osiewicz** [comment]
We talked with @JosephTLyons  and dediced to leave the current behavior as is.
