### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by HarryET** [zed-industries/zed#5098]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Missing support for Terraform/HCL

### Describe the solution you'd like

Add support for [terraform-ls](https://github.com/hashicorp/terraform-ls) so that we can have syntax highlighting and auto-complete for terraform configurations

### If applicable, add mockups / screenshots to help present your vision of the feature

N/a

**Comment by caius** [comment]
@AMaliutsin @HarryET not sure if you’ve seen but the repo is open source now, makes it easier to open a Pull Request to push this forward rather than waiting?

**Comment by wadhah101** [comment]
I love how fast and clean zed is, the only reason i go back to vscode is terraform.
Does anyone know a way how to make tf files open as Scheme by default  ?

**Comment by JosephTLyons** [comment]
Feel free to coordinate and work on it if you like, we'll pull terraform in directly if a PR emerges :)

**Comment by Abdelwaheb-Hnaien** [comment]
Any news about HCL syntaxe support ? Zed is really fantastic !

**Comment by romans-ovo** [comment]
Still missing Language Server support:

https://github.com/zed-industries/zed/blob/main/crates/zed/src/languages.rs#L325

**Comment by JosephTLyons** [comment]
Tnis landed in preview today: [v0.121.1-pre](https://zed.dev/releases/preview/0.122.1).

**Comment by refl3ction** [comment]
This worked for me after Syntax highlighting for Terraform was added:

__settings.json__
```json
  "languages": {
    "Terraform": {
      "formatter": {
        "external": {
          "command": "terraform",
          "arguments": [
            "fmt",
            "-"
          ]
        }
      }
    }
  }
```

**Comment by chinyongcy** [comment]
any idea when will the formatting works with .hcl files?
Have just tried, it works with .tf file as mentioned above.

**Comment by avtar** [comment]
> What kind of HCL do you write?

Terragrunt and [its use of HCL](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#example) is quite common when working with Terraform.

**Comment by stv-io** [comment]
@avtar `terragrunt hclfmt` - https://terragrunt.gruntwork.io/docs/getting-started/configuration/#formatting-hcl-files

**Comment by chinyongcy** [comment]
> @chinyongcy What kind of HCL do you write? Packer files for example?
> 
> Unlike some other formats like JSON and YAML, HCL was designed as a toolkit for building languages rather than as a language in itself, so there's a lot more application-level interpretation involved than you might be used to with other grammars. That's why formatting is usually done by specific applications rather than by a product-agnostic formatter.
> 
> The Terraform plugin/language server is only equipped to format Terraform files and won't format generic HCL. Many tools provide application-specific formatters, such as [`packer fmt`](https://www.packer.io/docs/commands/fmt) or [`vault policy fmt`](https://www.vaultproject.io/docs/commands/policy/fmt). Depending on the type of HCL you're writing, I hope you can find something similar.

terragrunt hcl, new to zed, i tried doing this based on some of the reply above for terragrunt.
<img width="590" alt="image" src="https://github.com/zed-industries/zed/assets/55968202/794897a7-a5c4-4695-8ec6-7de92b92a4bb">
but every time when I save my hcl, it clears the file.

**Comment by begemotik** [comment]
The tricky part to make the formatter work is to make sure the `terragrunt hclfmt` command outputs the file to stdout. Following the recommendation [here](https://github.com/gruntwork-io/terragrunt/issues/1037#issuecomment-2143442454) adjusted inline formatter as following and should admit that it works as a charm:

```
"HCL": {
      // Workarond to be able to format_on_save terragrunt files
      // https://github.com/gruntwork-io/terragrunt/issues/1037#issuecomment-2143442454
      "format_on_save": {
        "external": {
          "command": "sh",
          "arguments": [
            "-c",
            "TMPFILE=$(mktemp) && cat - > $TMPFILE && terragrunt hclfmt --terragrunt-hclfmt-file $TMPFILE && cat $TMPFILE && rm $TMPFILE"
          ]
        }
      }
```

**Comment by ChzenChzen** [comment]
How can I rename variables affecting all occurrences throughout the code?

**Comment by Yethal** [comment]
@begemotik Terragrunt has a `--terragrunt-hclfmt-stdin` flag now

**Comment by angelsrp1994** [comment]
I dont know what is going onwith the terragrunt hcl fmt but this works for me

```
"HCL": {
      "format_on_save": {
        "external": {
          "command": "terraform",
          "arguments": ["fmt", "-"]
        }
      }
    }
```

**Comment by nikolay** [comment]
@JosephTLyons I'm not sure why I have to specify the following file extensions when they must be used by default:

```JSON
{
  "file_types": {
    "HCL": ["*.hcl", "*.tf", "*.tfbackend", "*.tftest.hcl", "*.tfvars", "*.tofu"]
  }
}
```
Of course, there are also JSON variants for both Terraform and OpenTofu: `.tf.json` and `.tofu.json`.
