### ISSUE TITLE
Command to move a tab/editor rather than split/duplicate it

### ISSUE THREAD

**Issue by n7trd** [zed-industries/zed#5100]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I searched for key bindings/commands for that, but couldn't find one

### Describe the solution you'd like

**Use Case:** 
I have multiple tabs open and want to move one tab to a specific side.
Very useful I you want to have an overview of both tabs.
Currently I can only split the tab _and_ must close the other one if I want to avoid multiple tabs that I don't need.

A keyboard shortcuts would be really useful. That also affects the context menu for users that use a mouse.
The issue is kind of related to zed-industries/zed#5107 that I created. I would go even so far to suggest to make it the default behavior (if there was only one button) or priorities it in the context menu(s). In ~90% of the cases I want to move a tab and don't duplicate it. Not sure why duplicating is the default behavior in most editors. But that needs more investigation of course.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://user-images.githubusercontent.com/44614967/204379826-b5f95f84-a580-4e7a-9c4b-956ad0884f5a.mov

**Comment by douglas** [comment]
I used it all the time in Atom and would love to move a tab to another pane without having to close the original one, which was duplicated.

**Comment by notpeter** [comment]
Closing in favor of:

- https://github.com/zed-industries/zed/issues/15722

This issue is older, but that one has more upvotes.
Please 👍 and subscribe there to track progress.
