### ISSUE TITLE
Allow creating new folders via the`foo/bar/baz.txt` convention in the project panel when creating new files

### ISSUE THREAD

**Issue by AssertionBit** [zed-industries/zed#5101]
### Check for existing issues

- [X] Completed

#### Steps to achieve:

1. Open Any folder with zed
2. Right click -> Create file
3. Type `foo/bar.txt`
4. Here it is

![Screenshot](https://user-images.githubusercontent.com/113050317/204166653-11f9b99b-aba2-41ba-a137-7b71715f51e1.png)

#### Aftermath

After that application lives blank line in the navigation bar. It doesn't broke navigation at all and next create of file/folder with default typing `foo` or `bar.txt` will work fine.

### Expected behavior

I thought that there might be VSCode like file creation with `Create new file option` or folder otherwise.

### Environment

* Zed 0.65.2 – /Applications/Zed.app
* macOS 13.0.1
* architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/113050317/204167342-e08cad39-bee1-40ea-a3b3-b22b83c5fb77.mov

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

```log
5069   │ 23:54:22 [INFO] ========== starting zed ==========
5070   │ 23:54:22 [INFO] open paths ["/Users/assertionbit/git"]
5071   │ 23:54:22 [INFO] set status on client 0: Authenticating
5072   │ 23:54:22 [INFO] set status on client 0: Connecting
5073   │ 23:54:22 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/s
       │ bin:/Users/assertionbit/Library/Application Support/JetBrains/Toolbox/scripts:/Users/assertionbit/Library/Application Support/JetBrains/Toolbox/scripts
5074   │ 23:54:22 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
5075   │ 23:54:23 [INFO] add connection to peer
5076   │ 23:54:23 [INFO] waiting for server hello
5077   │ 23:54:23 [INFO] got server hello
5078   │ 23:54:23 [INFO] set status to connected (connection id: 0, peer id: 70275)
5079   │ 23:54:23 [INFO] set status on client 0: Connected { peer_id: PeerId(70275), connection_id: ConnectionId(0) }
5080   │ 23:54:32 [INFO] ========== starting zed ==========
5081   │ 23:54:32 [INFO] open paths ["/Users/assertionbit/git/.github"]
5082   │ 23:54:32 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/s
       │ bin:/Users/assertionbit/Library/Application Support/JetBrains/Toolbox/scripts:/Users/assertionbit/Library/Application Support/JetBrains/Toolbox/scripts
5083   │ 23:54:32 [INFO] set status on client 0: Authenticating
5084   │ 23:54:32 [INFO] set status on client 0: Connecting
5085   │ 23:54:32 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
5086   │ 23:54:33 [INFO] add connection to peer
5087   │ 23:54:33 [INFO] waiting for server hello
5088   │ 23:54:33 [INFO] got server hello
5089   │ 23:54:33 [INFO] set status to connected (connection id: 0, peer id: 70276)
5090   │ 23:54:33 [INFO] set status on client 0: Connected { peer_id: PeerId(70276), connection_id: ConnectionId(0) }
5091   │ 23:54:48 [ERROR] No such file or directory (os error 2)
```

**Comment by EstebanBorai** [comment]
Hello! Does this issue still open? I would like to give this a shot!

**Comment by mrnugget** [comment]
I think so, yep! I'd personally would love to see this.

**Comment by JosephTLyons** [comment]
> Hello! Does this issue still open? I would like to give this a shot!

We have this feature now. I think @mikayla-maki implemented it some time ago. Is there a bug here that we need to fix still?

**Comment by JosephTLyons** [comment]
I'm going to close this out, as I think we've got what it was originally asking. Feel free to reopen if I've missed something.
