### ISSUE TITLE
Clicking the `x` to close a tab activates the tab until the mouse button is released

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/zed#5106]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* Open multiple tabs
* Move the mouse cursor over a non-active tab's `x` button
* Press the mouse button, but don't release it
* :boom: That tab is spuriously activated

### Expected behavior

Clicking a tab's close button should not activate that tab.

### Environment

Zed 0.65.2 – /Applications/Zed.app
macOS 12.6.1
architecture arm64

**Comment by maxdeviant** [comment]
This no longer occurs in Zed v0.127.0.
