### ISSUE TITLE
Move the split button from the tabs panel to the tab

### ISSUE THREAD

**Issue by n7trd** [zed-industries/zed#5107]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Not a problem but definitely an enhancement

### Describe the solution you'd like

Currently the "split button" is on the right side of the tabs.
While it looks like some kind of global action that affects the
overall tabs the action only applies to the focused tab like
the close button only applies to a specific tab.

It would therefore move the button next to the close button.

**Pro:**
- It's more clear for the user what action affects what. 
- It works the same way we are used to, if we work with windows
- I can hover over other tabs/files the are not in focus and split them 
- (optional) You gain some space for an "additional action button (...)" for real global actions, like close all tabs and so on :-)

**Con:** 
- I didn't see other editor do this but they are all bad designed anyway :-)

Optional: Don't show a context menu with all split options if the user clicks on the button, just split it to the right site. That's what most devs do anyway. The option to split in an other direction is in the global menu anyway. Optionally there could be an additional setting to change the split direction.

Below: 
Mockup (mouse-over-state) with optional "additional action button "

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://user-images.githubusercontent.com/44614967/203871726-924e5fc2-99c3-4a95-9717-fdb78a273be9.png)

**Comment by maxdeviant** [comment]
I don't see us moving this button into the tabs themselves.
