### ISSUE TITLE
When starting SolarGraph, try to respect project-specific installation

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/zed#5109]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

If a user has multiple versions of the SolarGraph language server, Zed should use the one that's most appropriate for the current project.

### Describe the solution you'd like

From this [comment](https://github.com/zed-industries/feedback/issues/113#issuecomment-1322651896) by @attilagyorffy

I believe Zed should ideally follow the [Convention Over Configuration paradigm](https://en.wikipedia.org/wiki/Convention_over_configuration) and be smart about the above without the need of any configuration necessary. I believe a sensible priority (from higher to lower) would be the following:

* Use the solargraph bin stub if present (`./bin/solargraph`)
* Use the bundled version of solargraph if specified by the bundler context (see method described above)
* Use the matching solargraph in the `$PATH` (which should match the version of Ruby -> This is the current implementation if I understand correctly)
* Fail with a helpful error message, and with a link to a publicly available piece that helps setting things up

**Comment by alexandreh92** [comment]
Hey guys, do we have any progress on this one? I want to use it but the LSP keeps returning:

```bash
stderr: [WARN] Failed to load gems from bundle at /Users/my-user/my-project
stderr: #<Thread:0x00000001180a50c8 /Users/my-user/.rvm/gems/ruby-2.7.4/gems/solargraph-0.47.2/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):
stderr: /Users/my-user/.rvm/gems/ruby-2.7.4/gems/rubocop-1.47.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load': cannot load such file -- rubocop-graphql (LoadError)
```

The project is using `Ruby 3.1.3` and the LSP server keeps targeting `2.7.4` (default) as default in [rvm](https://rvm.io). 

I appreciate your work here!

**Comment by m0n9oose** [comment]
hey guys. I think I may have the same problem, but wanted to add some details.
Readme says:

> Zed currently doesn't install Solargraph automatically. To use Solargraph, you need to install the gem. Zed just looks for an executable called `solargraph` on your `PATH`

But i don't think this is true. I have installed `solargraph` with my project's Gemfile, not globally. The `solargraph` bin is in `PATH` but Zed still fails to find it, because it looks in wrong place:

```log
2024-02-22T14:28:08+01:00 [INFO] starting language server "solargraph", path: "/Users/i/project", id: 3
2024-02-22T14:28:08+01:00 [INFO] starting language server. binary path: "solargraph", working directory: "/Users/i/project", args: ["stdio"]
2024-02-22T14:28:08+01:00 [ERROR] failed to start language server "solargraph": No such file or directory (os error 2)
2024-02-22T14:28:08+01:00 [ERROR] server stderr: Some("")
2024-02-22T14:28:08+01:00 [INFO] Validation check requested for "solargraph" but it cannot be reinstalled
```

```sh
$ which solargraph
/Users/i/.rvm/gems/ruby-3.2.1@project/bin/solargraph
```

Another thing to mention: I see that `settings.json` allows to set a path to lsp binary:

```json
  "elixir": {
    // Change the LSP zed uses for elixir.
    // Note that changing this setting requires a restart of Zed
    // to take effect.
    //
    // May take 3 values:
    //  1. Use the standard ElixirLS, this is the default
    //         "lsp": "elixir_ls"
    //  2. Use the experimental NextLs
    //         "lsp": "next_ls",
    //  3. Use a language server installed locally on your machine:
    //         "lsp": {
    //           "local": {
    //             "path": "~/next-ls/bin/start",
    //             "arguments": ["--stdio"]
    //            }
    //          },
    //
    "lsp": "elixir_ls"
  }
```

But I believe this setting does not work for ruby.
