### ISSUE TITLE
Syntax highlighting for additional Ruby-related file types

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5115]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Gemfile, *.ru, *.rake

### Describe the solution you'd like

-

**Comment by joeldrapper** [comment]
I believe this issue should be closed as fixed.

**Comment by joeldrapper** [comment]
@JosephTLyons this issue is definitely fixed.

**Comment by JosephTLyons** [comment]
Alright! Another issue closed - thanks @joeldrapper!
