### ISSUE TITLE
Ruby auto-indent bug

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5116]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A user in our Discord community spotted this

### Expected behavior

-

### Environment

Not sure what the user's environment was

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

https://user-images.githubusercontent.com/19867440/202996721-d5d062a0-3316-4488-87f4-4ce80babe5d9.mov

**Comment by joeldrapper** [comment]
@JosephTLyons this issue has been fixed.

**Comment by vitallium** [comment]
Can confirm that too this issue has been fixed.
