### ISSUE TITLE
Make links in diagnostics clickable

### ISSUE THREAD

**Issue by Shadow53** [zed-industries/zed#5118]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Possibly related to: zed-industries/zed#5404 

`clippy` (Rust) diagnostics often include a link to learn more about a given lint, and sometimes that link includes information on how to configure that lint. Currently, I cannot interact with that text in any way, neither clicking on it to open the link nor selecting it to copy/paste into my browser manually.

### Describe the solution you'd like

I'd like to be able to click that link in the editor and open it in my default browser. Short of that, being able to highlight and copy/paste would be sufficient.

**Comment by JosephTLyons** [comment]
Links are now clickable in documentation popovers. Text is also copyable as well.
