### ISSUE TITLE
Discrete GPU activated on launch

### ISSUE THREAD

**Issue by emilazy** [zed-industries/zed#5124]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After launching Zed on an 16" Intel MacBook Pro the fans immediately started spinning up and the laptop became warm. Checking in Activity Monitor showed that this is because it activated the discrete AMD GPU:

<img width="1076" alt="Screenshot 2022-11-17 at 02 51 31" src="https://user-images.githubusercontent.com/18535642/202343000-d04d051d-7d36-4835-8fa2-0dc0453bcecb.png">

This won't be relevant for Apple Silicon systems, of course, but it has a major impact on thermals and battery life on Intel laptops, which I think is undesirable for a code editor. I understand that the discrete GPU might allow for better performance, but it shouldn't be required (and I can't imagine it makes enough of a difference in this use case to be worth the cost).

(Apologies if this has already been reported; I did a couple quick searches and couldn't find anything.)

### Expected behavior

Zed should not activate the discrete GPU, or at least it should be possible to disable that behaviour with a setting.

### Environment

Zed 0.64.0 – /Applications/Zed.app
macOS 13.0.1
architecture x86_64

(By the way, `echo "\n"` doesn't do what you might expect, on macOS at least (the behaviour of `echo` is [notoriously unportable](https://www.etalabs.net/sh_tricks.html)); I had to edit the output manually. I suggest using `printf '%s\nmacOS %s\narchitecture %s\n' "$(zed --version)" "$(sw_vers -productVersion)" "$(uname -m)"` in the template instead.)

**Comment by denlukia** [comment]
+1 For this issue. It's the main thing preventing me from trying Zed as of now ;(

From what I researched here's what might be useful for a fix:

1. It seems that GPUI uses this method to choose a GPU for rendering

https://github.com/zed-industries/zed/blob/f4bafd58992c8318dc0edd446f0d9ba3120c7a7c/crates/gpui/src/platform/mac/metal_renderer.rs#L67

2. Which [under the hood](https://github.com/gfx-rs/metal-rs/blob/b0f88c1c1ba4f0a45a2d5b0b99050008d52a917e/src/device.rs#L1511) of `metal` crate resolves to
```rust
    pub fn system_default() -> Option<Self> {
        // `MTLCreateSystemDefaultDevice` may return null if Metal is not supported
        unsafe {
            MTLCreateSystemDefaultDevice()
```

3. Which is as [described by Apple](https://developer.apple.com/documentation/metal/gpu_devices_and_work_submission/getting_the_default_gpu) defaults to discrete GPU on machines with multiple GPUs

4. It seems that the `system_default()` thing should be replaced with the process described by Apple [here](https://developer.apple.com/documentation/metal/gpu_devices_and_work_submission/multi-gpu_systems/getting_the_gpu_that_drives_a_view_s_display):

> Get the [CGDirectDisplayID](https://developer.apple.com/documentation/coregraphics/cgdirectdisplayid) value for the display in which your view currently appears. Then call the [CGDirectDisplayCopyCurrentMetalDevice(_:)](https://developer.apple.com/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald) function to get the device that drives that display. 

```swift
guard let viewDisplayID = mtkView.window?.screen?.deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] as? CGDirectDisplayID else { return }
let displayDevice = CGDirectDisplayCopyCurrentMetalDevice(viewDisplayID)
```

Plus code for switching the device on connections of new monitors and dragging the window between screens rendered by different GPUs, which (I think?) might be omitted at least for first version of a fix – just making it not turn on discrete GPU would stop Zed from turning my Mac intro leg-burning machine (which is totally expected for rendering videos or 3D but not for code editing)

The last part I'm not really sure how it would look ported to rust, but I hope we'll someday see contributor to figure it out.

**Comment by jansol** [comment]
I think that last part is already exposed via the FFI crate that is being used in GPUI.

**Comment by denlukia** [comment]
For the ones, who can't wait, I tried today a (super hacky but still) a solution:

Beware, I know little to nothing about Rust and this repository

1. Copied the repo, 
2. Did everything needed according to [Building Zed](https://github.com/zed-industries/zed/blob/f4bafd58992c8318dc0edd446f0d9ba3120c7a7c/docs/src/developing_zed__building_zed.md) instructions.
3. Replaced [these lines](https://github.com/zed-industries/zed/blob/f4bafd58992c8318dc0edd446f0d9ba3120c7a7c/crates/gpui/src/platform/mac/metal_renderer.rs#L67-L72) with:

```rust
let device: metal::Device = {
    let all_devices = metal::Device::all();
    let integrated_gpus: Vec<_> = all_devices
        .into_iter()
        .filter(|d| d.is_low_power() && !d.is_removable())
        .collect();

    if let Some(integrated_gpu) = integrated_gpus.first() {
        integrated_gpu.clone()
    } else {
        log::error!("No integrated GPU found");
        std::process::exit(1);
    }
};
```

4. Compiled with cargo build --release
5. After compilation it runs the app, we can close it and run executable from /target/release

Does someone know how to turn it into beautiful installation into Applications (maybe with a different icon and name)?

I know I loose updates this way and server-dependent features ;(

### Why I don't propose this as a PR
I'm afraid Zed won't accept this because theoretically this can cause performance regressions for users with multiple GPUs (one random day after updating their Zed copy will start using lower-powered gpu). I guess ideally that would have been a config option like "preferIntegratedGPU", but I have no Idea how to pass it all the way from Zed initialization, through window creation, through renderer creation and to here. 

That said though, for me such Zed runs as smooth as before, and now little happy "i" is shining in my gfxCardStatus :)

**Comment by emilazy** [comment]
I have opened https://github.com/zed-industries/zed/pull/13685 to hopefully get this fixed. Thank you @denlukia for the inspiration! If Zed had been FOSS when I opened this issue I might have gotten around to it sooner.

**Comment by TNieuwdorp** [comment]
Not a true measurement, but after the merge Zed no longer pops up under the "Using significant energy" tab on my Intel Macbook! Thanks for fixing at this :)
![image](https://github.com/zed-industries/zed/assets/9988640/36356d1b-1a12-4b40-9ac1-ff331e14172e)

**Comment by TiagoRibeiro25** [comment]
This is happening for me under linux

**Comment by Lablace** [comment]
Can someone help to make this an option like @denlukia had suggested? I upgraded Zed and felt really sorry that it got a little clumsy, I opened activity monitor and it told that Zed was running on integrated GPU. I am using a Mac mini with eGPU setup, and running on the eGPU is preferred as I have 4 monitors connected to it

**Comment by mrnugget** [comment]
I opened a PR here, but I'm a bit unsure about the code organization still: https://github.com/zed-industries/zed/pull/14738

**Comment by mrnugget** [comment]
New PR here: https://github.com/zed-industries/zed/pull/14744
