### ISSUE TITLE
Markdown code syntax does not render

### ISSUE THREAD

**Issue by Noe-dar** [zed-industries/zed#5125]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hover your mouse over any structure that uses markdown code syntax in its documentation and wait for the documentation to appear

### Expected behavior

It is rendered like in VSCode, provided a screenshot

### Environment

Zed 0.64.0 – /Applications/Zed.app
macOS 12.6.1 
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed
<img width="657" alt="image" src="https://user-images.githubusercontent.com/113918346/202342000-ca619f27-17f6-4de8-ba0d-8d383c74299f.png">
VSCode
<img width="785" alt="image" src="https://user-images.githubusercontent.com/113918346/202342059-cb04abdb-616c-4d3f-96ca-3aedaa4dafe9.png">

**Comment by CurbaiCode** [comment]
This looks similar to #5313.

**Comment by JosephTLyons** [comment]
I believe you are right @CurbaiCode, lets close this in favor of #5313.
