### ISSUE TITLE
Code runner

### ISSUE THREAD

**Issue by chlorocodes** [zed-industries/zed#5141]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I think it would be pretty cool to be able to execute code from within the editor without needing to manually run a `node *` or `python *` command from a terminal tab. Basically looking for something similar to VSCode's [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) extension.

### If applicable, add mockups / screenshots to help present your vision of the feature

[VSCode Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)

![](https://github.com/formulahendry/vscode-code-runner/raw/HEAD/images/usage.gif)

**Comment by olegchir** [comment]
Hello, it's very important feature. Of course, you can write your own automation on top of AHK-Windows/X11-Linux/whatever, but it's way better to have at least an easy way to land a build-and-run shortcut

**Comment by Anthony-Eid** [comment]
I'm interested in contributing to this issue, but would need some guidance. Could someone please point me in the right direction to start working on this?

**Comment by SomeoneToIgnore** [comment]
Me and @osiewicz are working https://github.com/zed-industries/zed/issues/7108 

It is not planned to be as fancy as in the video initially, but soon™ we expect to have a way to have `pyhonN some_script.py` dynamic tasks in the corresponding modal.

@osiewicz works on that particular bit and things looked good so far, consider pairing with him if you want to work on this particular task.

**Comment by osiewicz** [comment]
Hey, yeah, tagging is enough; what timezone are you in?
I am in GMT+1 and I am (generally speaking) available between 10am and 6pm; if you're in US timezones I can also stay a bit longer, especially on Tuesdays and Thursdays.

**Comment by Anthony-Eid** [comment]
I'm in EST so I think you're about 6 hours ahead of me. 

Would you be free to pair up this Thursday?

**Comment by osiewicz** [comment]
Yep! I've sent you a message on Discord, let's figure out the schedule there.

**Comment by berkaayildiz** [comment]
Hello, is there any updates regarding this issue?

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/10548 (will be part of Zed 0.132) had added language tasks to Bash and Python, allowing to run a selection, or the opened file via user's default shell or `python3` in it.
There are caveats (such as `python3`-only hardcode), but this is a start for basic cases which hopefully helps many people already.

Zed tasks can be customized and [have access](https://zed.dev/docs/tasks) to editor selections, so other languages may be supported locally now already.
The tasks modal with all tasks applicable for the latest caret position is opened with `task::Spawn` action or a command panel, also there's a footer button to show the modal and task status:
![image](https://github.com/zed-industries/zed/assets/2690773/a78ba1b3-93b3-454a-a005-a8d450f5fbb1)

What's missing so far:

* more language support, preferably on the extension level. 
* more logic to better select an appropriate executable for all cases (e.g. python2 or a proper `node` binary)
* "run task for current line" + corresponding UI for visibility — @osiewicz works on this and will use the same language task providers

Technically, the issue could be closed and the missing parts considered in follow-ups, but let's keep the issue open at least before the 0.132 is actually released.

**Comment by notpeter** [comment]
Tasks have been out for a bit and so I'm going close this issue.

Feel free to open additional issues with enhancement requests for improving task functionality in Zed. See: [Zed Tasks Documentation](https://zed.dev/docs/tasks) for more.

-----
For reference, there is a default task for "execute selection" (as requested above) but if you want a custom version of the same (say using an alternate binary) you can easily do so using `ZED_SELECTED_TEXT` [task variable](https://zed.dev/docs/tasks#variables):

```
// .zed/tasks.json
[
  {
    "label": "myvenv: execute selection",
    "command": "myvenv/bin/python3",
    "args": ["-c", "${ZED_SELECTED_TEXT}"]
    //"cwd": "/path/to/dir",
    //"env": { "foo": "bar" },
  }
]
```

Happy tasking!

**Comment by igniscyan** [comment]
@notpeter Sorry to necro this, but I followed another issue that mentioned the debugger feature request being bundled here - is an in client debugger something that's still in the pipeline or has that changed?

**Comment by skhaz** [comment]
You do not need a debugger if you have AI in your editor /s

**Comment by aizigao** [comment]
share my config 
task
```json
{
    "label": "[NODE] CODE RUNNER: execute selection",
    "command": "[YOUR_PATH]/code_runner-zed--js.sh", // change to your path
    "use_new_terminal": false
},
{
    "label": "[BASH] CODE RUNNER: execute selection",
    "command": "[YOUR_PATH]/code_runner-zed--bash.sh",
    "use_new_terminal": false
},
{
    "label": "[TS] CODE RUNNER:  execute selection",
    "command": "[YOUR_PATH]/code_runner-zed--ts.sh",
    "use_new_terminal": false
},
{
    "label": "[PY] CODE RUNNER: execute selection",
    "command": "[YOUR_PATH]/code_runner-zed--py.sh",
    "use_new_terminal": false
}
```
scripts 

code_runner-zed--bash.sh
```sh
#!/usr/bin/env bash
set -e

# Temporary bash file path

TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.sh"

# Clean up old file
[ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"

# Get selected code from environment variable
CODE="${ZED_SELECTED_TEXT:-}"

if [ -z "$CODE" ]; then
  echo "⚠️ NO CODE SELECTED"
  exit 1
fi

# Generate shell script
# Write to temporary script file
{
  echo "#!/usr/bin/env bash"
  echo ""
  echo "$CODE"
} > "$TEMP_FILE"

# Grant execute permission
chmod +x "$TEMP_FILE"

# Output prompt
echo "✅ CODE_RUNNER RUN: $TEMP_FILE"
echo "-----------------------------------"

# Execute temporary script
bash "$TEMP_FILE"
```

code_runner-zed--js.sh
```sh
#!/usr/bin/env bash
set -e

if [ -z "$ZED_SELECTED_TEXT" ]; then
  echo "⚠️ NO CODE SELECTED"
  exit 1
fi

# Temporary file path (in current directory)
TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.js"


# Delete existing file if present
[ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"

# Get selected text from Zed variable (passed-in argument or stdin)
if [ -n "$ZED_SELECTED_TEXT" ]; then
  echo "$ZED_SELECTED_TEXT" > "$TEMP_FILE"
else
  # Support piping content from standard input (if the editor supports it)
  cat > "$TEMP_FILE"
fi

# Output execution info
echo "▶ CODE RUNNER Run: $TEMP_FILE ..."
echo "---------------------------------------"

# Execute file
node "$TEMP_FILE"
```

code_runner-zed--ts.sh
```sh
#!/usr/bin/env bash
set -e

if [ -z "$ZED_SELECTED_TEXT" ]; then
  echo "⚠️ NO CODE SELECTED"
  exit 1
fi

# Temporary file path (in current directory)
TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.ts"

# printenv | grep ZED
# Delete existing file if present
[ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"

# Get selected text from Zed variable (passed-in argument or stdin)
if [ -n "$ZED_SELECTED_TEXT" ]; then
  echo "$ZED_SELECTED_TEXT" > "$TEMP_FILE"
else
  # Support piping content from standard input (if the editor supports it)
  cat > "$TEMP_FILE"
fi

# Output execution info
echo "▶ CODE RUNNER Run: $TEMP_FILE ..."
echo "---------------------------------------"

# 判断下是否有 tsx
if ! command -v tsx &> /dev/null; then
    # 添加下颜色
    echo -e "\033[33m⚠️  tsx not found\033[0m"
    echo -e "\033[36mplease install tsx\033[0m"
    echo -e "\033[32mnpm i -g tsx\033[0m"
  exit 1
fi

# Execute file
tsx "$TEMP_FILE"
```


code_runner-zed--py.sh

```sh
#!/usr/bin/env bash
set -e

if [ -z "$ZED_SELECTED_TEXT" ]; then
  echo "⚠️ NO CODE SELECTED"
  exit 1
fi

# Temporary file path (in current directory)
TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.py"

# printenv | grep ZED
# Delete existing file if present
[ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"

# Get selected text from Zed variable (passed-in argument or stdin)
if [ -n "$ZED_SELECTED_TEXT" ]; then
  echo "$ZED_SELECTED_TEXT" > "$TEMP_FILE"
else
  # Support piping content from standard input (if the editor supports it)
  cat > "$TEMP_FILE"
fi

# Output execution info
echo "▶ CODE RUNNER Run: $TEMP_FILE ..."
echo "---------------------------------------"

# Check if python3 is available
if ! command -v python3 &> /dev/null; then
    # Add some color
    echo -e "\033[33m⚠️  python3 not found\033[0m"
    echo -e "\033[36mplease install Python 3\033[0m"
    echo -e "\033[32mbrew install python\033[0m"
  exit 1
fi

# Execute file
python3 "$TEMP_FILE"

```


```sh
chmod +x code_runner-zed--bash.sh 
chmod +x  code_runner-zed--js.sh
chmod +x  code_runner-zed--ts.sh
chmod +x  code_runner-zed--py.sh
```


NOTE:  don't use recently one

<img width="1158" height="441" alt="Image" src="https://github.com/user-attachments/assets/37d3f801-db04-4604-878b-450510d0538b" />

**Comment by aizigao** [comment]
> share my config task
> 
> {
>     "label": "[NODE] CODE RUNNER: execute selection",
>     "command": "[YOUR_PATH]/code_runner-zed--js.sh", // change to your path
>     "use_new_terminal": false
> },
> {
>     "label": "[BASH] CODE RUNNER: execute selection",
>     "command": "[YOUR_PATH]/code_runner-zed--bash.sh",
>     "use_new_terminal": false
> },
> {
>     "label": "[TS] CODE RUNNER:  execute selection",
>     "command": "[YOUR_PATH]/code_runner-zed--ts.sh",
>     "use_new_terminal": false
> },
> {
>     "label": "[PY] CODE RUNNER: execute selection",
>     "command": "[YOUR_PATH]/code_runner-zed--py.sh",
>     "use_new_terminal": false
> }
> scripts
> 
> code_runner-zed--bash.sh
> 
> #!/usr/bin/env bash
> set -e
> 
> # Temporary bash file path
> 
> TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.sh"
> 
> # Clean up old file
> [ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"
> 
> # Get selected code from environment variable
> CODE="${ZED_SELECTED_TEXT:-}"
> 
> if [ -z "$CODE" ]; then
>   echo "⚠️ NO CODE SELECTED"
>   exit 1
> fi
> 
> # Generate shell script
> # Write to temporary script file
> {
>   echo "#!/usr/bin/env bash"
>   echo ""
>   echo "$CODE"
> } > "$TEMP_FILE"
> 
> # Grant execute permission
> chmod +x "$TEMP_FILE"
> 
> # Output prompt
> echo "✅ CODE_RUNNER RUN: $TEMP_FILE"
> echo "-----------------------------------"
> 
> # Execute temporary script
> bash "$TEMP_FILE"
> code_runner-zed--js.sh
> 
> #!/usr/bin/env bash
> set -e
> 
> if [ -z "$ZED_SELECTED_TEXT" ]; then
>   echo "⚠️ NO CODE SELECTED"
>   exit 1
> fi
> 
> # Temporary file path (in current directory)
> TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.js"
> 
> 
> # Delete existing file if present
> [ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"
> 
> # Get selected text from Zed variable (passed-in argument or stdin)
> if [ -n "$ZED_SELECTED_TEXT" ]; then
>   echo "$ZED_SELECTED_TEXT" > "$TEMP_FILE"
> else
>   # Support piping content from standard input (if the editor supports it)
>   cat > "$TEMP_FILE"
> fi
> 
> # Output execution info
> echo "▶ CODE RUNNER Run: $TEMP_FILE ..."
> echo "---------------------------------------"
> 
> # Execute file
> node "$TEMP_FILE"
> code_runner-zed--ts.sh
> 
> #!/usr/bin/env bash
> set -e
> 
> if [ -z "$ZED_SELECTED_TEXT" ]; then
>   echo "⚠️ NO CODE SELECTED"
>   exit 1
> fi
> 
> # Temporary file path (in current directory)
> TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.ts"
> 
> # printenv | grep ZED
> # Delete existing file if present
> [ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"
> 
> # Get selected text from Zed variable (passed-in argument or stdin)
> if [ -n "$ZED_SELECTED_TEXT" ]; then
>   echo "$ZED_SELECTED_TEXT" > "$TEMP_FILE"
> else
>   # Support piping content from standard input (if the editor supports it)
>   cat > "$TEMP_FILE"
> fi
> 
> # Output execution info
> echo "▶ CODE RUNNER Run: $TEMP_FILE ..."
> echo "---------------------------------------"
> 
> # 判断下是否有 tsx
> if ! command -v tsx &> /dev/null; then
>     # 添加下颜色
>     echo -e "\033[33m⚠️  tsx not found\033[0m"
>     echo -e "\033[36mplease install tsx\033[0m"
>     echo -e "\033[32mnpm i -g tsx\033[0m"
>   exit 1
> fi
> 
> # Execute file
> tsx "$TEMP_FILE"
> code_runner-zed--py.sh
> 
> #!/usr/bin/env bash
> set -e
> 
> if [ -z "$ZED_SELECTED_TEXT" ]; then
>   echo "⚠️ NO CODE SELECTED"
>   exit 1
> fi
> 
> # Temporary file path (in current directory)
> TEMP_FILE="${ZED_WORKTREE_ROOT}/tempCodeRunnerFile.py"
> 
> # printenv | grep ZED
> # Delete existing file if present
> [ -f "$TEMP_FILE" ] && rm "$TEMP_FILE"
> 
> # Get selected text from Zed variable (passed-in argument or stdin)
> if [ -n "$ZED_SELECTED_TEXT" ]; then
>   echo "$ZED_SELECTED_TEXT" > "$TEMP_FILE"
> else
>   # Support piping content from standard input (if the editor supports it)
>   cat > "$TEMP_FILE"
> fi
> 
> # Output execution info
> echo "▶ CODE RUNNER Run: $TEMP_FILE ..."
> echo "---------------------------------------"
> 
> # Check if python3 is available
> if ! command -v python3 &> /dev/null; then
>     # Add some color
>     echo -e "\033[33m⚠️  python3 not found\033[0m"
>     echo -e "\033[36mplease install Python 3\033[0m"
>     echo -e "\033[32mbrew install python\033[0m"
>   exit 1
> fi
> 
> # Execute file
> python3 "$TEMP_FILE"
> chmod +x code_runner-zed--bash.sh 
> chmod +x  code_runner-zed--js.sh
> chmod +x  code_runner-zed--ts.sh
> chmod +x  code_runner-zed--py.sh
> NOTE: don't use recently one
> 
> <img alt="Image" width="1158" height="441" src="https://private-user-images.githubusercontent.com/14126445/507388922-37d3f801-db04-4604-878b-450510d0538b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODUyMjA2MzcsIm5iZiI6MTc4NTIyMDMzNywicGF0aCI6Ii8xNDEyNjQ0NS81MDczODg5MjItMzdkM2Y4MDEtZGIwNC00NjA0LTg3OGItNDUwNTEwZDA1MzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzI4VDA2MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMzEzMWY5NWMyYjQ5YjdmYzE3MTk2ZmIwNzFiZTgzYTcxOGZkODI0MDM1YzAwMzEwOTYzODFiYTc4Y2M4MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.x9Ut6SBUBmy2j_O8OmesoBROSCKLglrCVLoLJulyRC8">

after ZED Add new env ZED_LANGUAGE, so I update my scripts to single js script 

> your_path/scripts/code_runner-zed

```js
#!/usr/bin/env node
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const { ZED_SELECTED_TEXT, ZED_FILENAME, ZED_LANGUAGE, ZED_WORKTREE_ROOT, ZED_DIRNAME, ZED_FILE } = process.env;


// Extend PATH - GUI apps don't inherit shell PATH
const home = os.homedir();
const extraPaths = [
  '/bin',
  '/usr/bin',
  '/usr/local/bin',
  '/opt/homebrew/bin',
  `${home}/.nvm/versions/node/*/bin`,
  `${home}/.fnm/node-versions/*/installation/bin`,
  `${home}/.pyenv/shims`,
];
const expandedPaths = extraPaths.flatMap(p => {
  if (p.includes('*')) {
    const [base, suffix] = p.split('*');
    try { return fs.readdirSync(base).filter(d => !d.startsWith('.')).map(d => path.join(base, d, suffix)); }
    catch { return []; }
  }
  return [p];
});
process.env.PATH = [...new Set([...expandedPaths, ...(process.env.PATH || '').split(':')])].filter(Boolean).join(':');

if (!ZED_SELECTED_TEXT) {
  console.log('⚠️ NO CODE SELECTED');
  process.exit(1);
}

// Detect from file extension first, then fall back to ZED_LANGUAGE
const extMap = {
  '.sh': ['sh', 'bash'], '.bash': ['sh', 'bash'],
  '.js': ['js', 'node'],
  '.py': ['py', 'python3'],
  '.ts': ['ts', 'tsx'],
};

const langMap = {
  'bash': ['sh', 'bash'], 'shell script': ['sh', 'bash'], 'shellscript': ['sh', 'bash'],
  'javascript': ['js', 'node'],
  'python': ['py', 'python3'], 'python3': ['py', 'python3'],
  'typescript': ['ts', 'tsx'],
};

const fileExt = path.extname(ZED_FILENAME || '').toLowerCase();
const lang = (ZED_LANGUAGE || '').toLowerCase();

const mapping = extMap[fileExt] || langMap[lang];
if (!mapping) {
  console.log(`⚠️ Unsupported: ZED_FILENAME=${ZED_FILENAME}, ZED_LANGUAGE=${ZED_LANGUAGE}`);
  process.exit(1);
}

const [ext, runnerName] = mapping;

// Resolve runner to absolute path
function resolveRunner(name) {
  const knownPaths = {
    bash: ['/bin/bash', '/usr/bin/bash'],
    node: ['/usr/local/bin/node', '/opt/homebrew/bin/node', '/usr/bin/node'],
    python3: ['/usr/local/bin/python3', '/opt/homebrew/bin/python3', '/usr/bin/python3'],
    tsx: ['/usr/local/bin/tsx', '/opt/homebrew/bin/tsx'],
  };
  for (const p of knownPaths[name] || []) {
    if (fs.existsSync(p)) return p;
  }
  // Check nvm/fnm
  for (const base of [`${home}/.nvm/versions/node`, `${home}/.fnm/node-versions`]) {
    try {
      for (const v of fs.readdirSync(base)) {
        const p = path.join(base, v, 'installation/bin', name);
        if (fs.existsSync(p)) return p;
      }
    } catch {}
  }
  return name;
}

const runner = resolveRunner(runnerName);
const worktree = ZED_WORKTREE_ROOT || ZED_DIRNAME || (ZED_FILE ? path.dirname(ZED_FILE) : '') || os.tmpdir();

const tempFile = path.join(worktree, `tempCodeRunnerFile.${ext}`);
if (fs.existsSync(tempFile)) fs.unlinkSync(tempFile);
fs.writeFileSync(tempFile, ZED_SELECTED_TEXT);

console.log(`▶ CODE RUNNER [${ZED_LANGUAGE}]: ${tempFile}`);
console.log('---------------------------------------');
try {
  execSync(`${runner} "${tempFile}"`, { stdio: 'inherit' });
} catch (e) {
  if (/not found|ENOENT|No such/.test(e.message)) {
    const hints = { python3: 'brew install python', tsx: 'npm i -g tsx' };
    console.error(`⚠️ ${runnerName} not found${hints[runnerName] ? `\n  → ${hints[runnerName]}` : ''}`);
  }
}

```
