### ISSUE TITLE
Code Folding Levels

### ISSUE THREAD

**Issue by NathBabs** [zed-industries/zed#5142]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Going through large files is really difficult.

### Describe the solution you'd like

When I open a large file in VS Code, i can immediately fold all the code at a particular nesting level(Cmd + k + 4 (or a number) to be able to go through the code. It is very helpful to me in my DX.
And also folding in the UI by the line numbers should be possible.
The current folding capability in Zed is too basic to be useful for me

**Comment by vuon9** [comment]
> Atom had this folding feature not sure why it's missing as a basic feature in Zed. Can we get a fold option as part of the line number sidebar?
> 
> This is a very handy feature for when dealing with indented code to be able to focus on things within a certain indentation level.
> 
> ![Screen Shot 9](https://user-images.githubusercontent.com/22822565/214712196-f26ee43b-111f-4782-8f52-0a4583d40724.png)

What is the name of these vertical lines? It's really helpful to work with python code or yaml in VSCode with these lines, but Zed doesn't have.

**Comment by SomeoneToIgnore** [comment]
There's an issue for those to be added in Zed, and there they are called "indent guides": https://github.com/zed-industries/zed/issues/5373

**Comment by SilentGlasses** [comment]
Sorry @vuon9 .. Those lines are part of Pulsar (formerly Atom), they are called Indent Guides and is a built in feature of the editor.

I stopped using Zed and just moved to [Pulsar](https://pulsar-edit.dev/).

**Comment by canselcik** [comment]
I'd also like to chime in and state interest for Fold-All.

**Comment by mkdynamic** [comment]
This is a feature Sublime Text had as well, and something I really miss in Zed.

**Comment by notpeter** [comment]
For reference, here are the VSCode keyboard shortcuts for folds ([source](https://code.visualstudio.com/docs/editor/codebasics#_folding)):

> - [x] Fold (⌥⌘[) folds the innermost uncollapsed region at the cursor.
> - [x] Unfold (⌥⌘]) unfolds the collapsed region at the cursor.
> - [ ] Toggle Fold (⌘K ⌘L) folds or unfolds the region at the cursor.
> - [ ] Fold Recursively (⌘K ⌘[) folds the innermost uncollapsed region at the cursor and all regions inside that region.
> - [ ] Unfold Recursively (⌘K ⌘]) unfolds the region at the cursor and all regions inside that region.
> - [ ] Fold All (⌘K ⌘0) folds all regions in the editor.
> - [ ] Unfold All (⌘K ⌘J) unfolds all regions in the editor.
> - [ ] Fold Level X (⌘K ⌘2 for level 2) folds all regions of level X, except the region at the current cursor position.
> - [ ] Fold All Block Comments (⌘K ⌘/) folds all regions that start with a block comment token.

**Comment by asins** [comment]
This issue began to be discussed in 2022, and it is surprising that it has not yet entered the development plan.

Using the 'Cmd+Shift+o' component key solves the mitigation problem, but it is still unbearable to use.

**Comment by gazhay** [comment]
Just arrived from linux, and yup can't stay if folding is not a "zed" thing.

**Comment by equt** [comment]
This would also help to enable the `zM` (close  all folds) in Vim.

**Comment by maxhoffmann** [comment]
Oh no, I also just realized this feature is missing in Zed. It’s very handy in JS to fold all cases of a switch statement, since these don’t show up in the outline for example

**Comment by Francisneibl** [comment]
Any predictions on when this feature will be released?

**Comment by achalddave** [comment]
Not sure if this is the best place to share, but for zM and zR, the following workaround works okay for me: 

```
  {
    "context": "vim_mode == normal",
    "bindings": {
      "z M": ["workspace::SendKeystrokes", "cmd-a z c escape g g"] // fold all
    }
  },
  {
    "context": "vim_mode == normal",
    "bindings": {
      "z R": ["workspace::SendKeystrokes", "cmd-a z o escape g g"] // unfold all
    }
  }
```

**Comment by jfcalvo** [comment]
This is one of the features that I miss the most with Zed. It's really difficult to navigate big files without it.

**Comment by ConradIrwin** [comment]
#18421 added many of the fold related features that overlap between vim and vscode. Still no numbered levels yet though!

**Comment by fornellas** [comment]
Thanks @ConradIrwin , can confirm #18421 to be working pretty well. Looking forward to numbered levels, the main dough here!

**Comment by JosephTLyons** [comment]
Numbered levels are in!

**Comment by NathBabs** [comment]
> Numbered levels are in!

Thank you very much @JosephTLyons , As the creator of this issue, I am really happy with this feature.
Well done to the team.

There is one issue left, i dont know if i should create a new issue or just comment it here.

The issue is the relation between the position of the cursor and the code folding action. 
When my cursor is in a particular nested block and i decide to code fold with the shortcut key e.g  CMD + K + 2, it shouldn't fold the the top level block i am in based on my cursor position, it should only fold lower nested level.

The aim of this code folding is for focus, so it shouldnt just fold everything in a file while not taking into account where the cursor is. e.g when i press  CMD + K + 2 and my cursor is in a nested block of 2 levels( e.g a function in a class) , it should fold other functions in that class but leave the function I am in open.

But the current functionality folds everything and i lose focus and have to manually unfold that function my cursor is in from the number sidebar.

I will be grateful if this is implemented.(you can look at this behaviour in vscode and see how it works)

Well done

**Comment by JosephTLyons** [comment]
> > Numbered levels are in!
> 
> Thank you very much [@JosephTLyons](https://github.com/JosephTLyons) , As the creator of this issue, I am really happy with this feature. Well done to the team.
> 
> There is one issue left, i dont know if i should create a new issue or just comment it here.
> 
> The issue is the relation between the position of the cursor and the code folding action. When my cursor is in a particular nested block and i decide to code fold with the shortcut key e.g CMD + K + 2, it shouldn't fold the the top level block i am in based on my cursor position, it should only fold lower nested level.
> 
> The aim of this code folding is for focus, so it shouldnt just fold everything in a file while not taking into account where the cursor is. e.g when i press CMD + K + 2 and my cursor is in a nested block of 2 levels( e.g a function in a class) , it should fold other functions in that class but leave the function I am in open.
> 
> But the current functionality folds everything and i lose focus and have to manually unfold that function my cursor is in from the number sidebar.
> 
> I will be grateful if this is implemented.(you can look at this behaviour in vscode and see how it works)
> 
> Well done

Hey @NathBabs - a new issue would be greatly appreciated, so we dont lose track of it and so that if it gets upvotes, its popularity is visible.
