### ISSUE TITLE
"Peek" files / temporary tabs

### ISSUE THREAD

**Issue by jbergstroem** [zed-industries/zed#5145]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I would like Zed to not keep a tab open unless the file is modified or "intentionally" (lack for a better word) open. This means that if you click a file in your browser, it opens but the tab would not persist if you choose another file.

### Describe the solution you'd like

1. Choosing a file opens the tab for viewing it
2. If the file is interacted with (edited, etc), the tab persists
3. If the file is double clicked, the tab persists
4. (else) the tab goes away if you choose another file

### If applicable, add mockups / screenshots to help present your vision of the feature

This is an example using Nova.app, where I:
1. browse files,
2. double click a file to keep it open
3. edit a file to keep it open

https://user-images.githubusercontent.com/176984/200120532-0a5316ae-480d-4439-b8d3-048d8e7624ef.mov

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/10730 brought this functionality in, relevant settings in Zed:
```jsonc
// Settings related to preview tabs.
"preview_tabs": {
  // Whether preview tabs should be enabled.
  // Preview tabs allow you to open files in preview mode, where they close automatically
  // when you switch to another file unless you explicitly pin them.
  // This is useful for quickly viewing files without cluttering your workspace.
  "enabled": true,
  // Whether to open tabs in preview mode when selected from the file finder.
  "enable_preview_from_file_finder": false,
  // Whether a preview tab gets replaced when code navigation is used to navigate away from the tab.
  "enable_preview_from_code_navigation": false
},
```
