### ISSUE TITLE
Hide directories

### ISSUE THREAD

**Issue by MassonNN** [zed-industries/zed#5150]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Many of directories like .git or .github distract you when you navigates your project in the Project Pane 

### Describe the solution you'd like

Feature to disable previewing some directories (by regex and\or by name) in the Project Pane

**Comment by Moshyfawn** [comment]
Isn't the `file_scan_exclusions` setting supposed to prevent the file from being shown in the project panel? I'd consider this request fulfilled.

**Comment by notpeter** [comment]
I'm going to close this. @MassonNN, please comment here or create a new issue if `file_scan_exclusions` doesn't meet your needs.

Here are the current defaults for `file_scan_exlcusions` which you can override in your settings.json: 

https://github.com/zed-industries/zed/blob/95c69d069679c3d2894401ad53b7f6f4b73d7448/assets/settings/default.json#L492-L501
