### ISSUE TITLE
Invisible Unicode Characters are not displayed

### ISSUE THREAD

**Issue by stefhol** [zed-industries/zed#5151]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/35531567/199631372-e457e28b-68e3-455f-929e-019d7c1f97b6.png">

As you can see in this picture. There are some Unicode characters, zed renders nothing, also you can't delete these symbols in zed.

### Expected behavior

Show that there are Unicode Characters like in VSCode. Able to delete these symbols

### Environment

echo $(/Applications/Zed.app/Contents/MacOS/cli --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)

**Comment by tjconcept** [comment]
Reproduce: on MacOS, type <kbd>option</kbd> + <kbd>space</kbd>. Then you'll get these:         invisible ones.

**Comment by notpeter** [comment]
This issue is older, but I'm going to close this in favor of this one because it has more upvotes:
- https://github.com/zed-industries/zed/issues/16310

Thanks for reporting this and thanks for following up with an excellent test case for nbsp!
