### ISSUE TITLE
Allow multi-cursors to be deleted using alt-click

### ISSUE THREAD

**Issue by r0ckwav3** [zed-industries/zed#5152]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

When placing multi-cursors, I sometimes miss and want to quickly remove the misplaced multi-cursor.

### Describe the solution you'd like

Alt-clicking in the same location should remove a previously placed multi-cursor

### If applicable, add mockups / screenshots to help present your vision of the feature

Example in VSCode: Removing a misplaced multicursor in line 3

https://user-images.githubusercontent.com/33732392/199589332-8f0c6d22-218b-42e4-9094-31cbf1088a03.mov

**Comment by JosephTLyons** [comment]
This is now supported in Zed!
