### ISSUE TITLE
Use different colors for constants and values

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5153]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

-

### Expected behavior

-

### Environment

Zed 0.62.4 – /Applications/Zed.app
macOS 13.0
architecture x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

*This is a user's image*

<img width="486" alt="Screenshot_2022-11-02_at_6 56 28_pm" src="https://user-images.githubusercontent.com/19867440/199586502-923aa742-cc5f-435f-8e3e-ea3f58791ca5.png">

**Comment by maxdeviant** [comment]
Closing this since it just impacts the built-in themes, as user themes are free to do what they want with their syntax highlighting.
