### ISSUE TITLE
Active items in the project panel style incorrectly when cut

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/zed#5158]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Select a file in the project panel
2. Cut file
3. 💥
4. (Select a different file and you can see the intended styling)

### Expected behavior

The active style should change to the cut style when the cut action happens.

### Environment

N/A

**Comment by JosephTLyons** [comment]
I'm no longer able to reproduce this, so I'm going to close this out.
