### ISSUE TITLE
Gleam support

### ISSUE THREAD

**Issue by ssaunderss** [zed-industries/zed#5162]
### Check for existing issues

- [X] Completed

### Language

Gleam

### Tree Sitter parser link

https://github.com/gleam-lang/tree-sitter-gleam

### Language server link

https://github.com/gleam-lang/gleam/blob/c9877cd39b7263072b97159b49ed12473d6f2902/compiler-cli/src/lsp.rs

### Misc notes

We have Elixir, now it's time to get some other ERTS languages on Zed 😎

**Comment by maxdeviant** [comment]
Gleam support was added in #6733 and is available in [Zed v0.121.0](https://zed.dev/releases/preview/0.121.0).
