### ISSUE TITLE
telemetry: use custom domain name (telemetry.zed.dev)

### ISSUE THREAD

**Issue by jbergstroem** [zed-industries/zed#5164]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I use a dns that returns "nxdomain" for many hosts related to advertising and telemetry. I don't mind sharing telemetry for Zed but seeing how it seems to be using a generic domain (api2.amplitude.com?), I see a ton of these in my logs:

```
Caused by:
    [7] Couldn't connect to server
10:17:14 [WARN] request completed with error: failed to connect to the server
10:17:14 [ERROR] failed to connect to the server

Caused by:
    [7] Couldn't connect to server
10:20:58 [WARN] request completed with error: failed to connect to the server
10:20:58 [ERROR] failed to connect to the server
```

### Describe the solution you'd like

1. Set up a [proxy](https://www.docs.developers.amplitude.com/analytics/domain-proxy/) (`telemetry.zed.dev`) to allow customizing the intercepting domain (tbh I assumed amplitude would support custom CNAMEs - would a proxy like cloudflare do it?). With this, it is easier to build trust with your users.
2. improve error logging. What server does it fail to connect to?
3. Also, it would be great to see dates in the log

**Comment by maxdeviant** [comment]
We now send telemetry data through `api.zed.dev`.
