### ISSUE TITLE
Zed prevents MacOS global shortcut keys from working

### ISSUE THREAD

**Issue by ucomru** [zed-industries/zed#5168]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I created keyboard shortcuts to launch apps in macOS using Automator.
For example I use `CMD + CTRL + Z` - to launch _iTerm_ ...
But when Zed window is active such keyboard shortcuts don't work.
It seems to me, Zed intercepts all other system combinations of keyboard shortcuts.
Available only own Zed combinations.

### Expected behavior

All keyboard shortcuts to launch apps in macOS using Automator are  available when Zed window is active.

### Environment

Zed 0.61.0 – /Applications/Zed.app
macOS 12.6
architecture arm64

**Comment by Harrywg** [comment]
Any fix for this?

**Comment by notpeter** [comment]
I can confirm this is still an issue.  Steps to reproduce:
1. Open Shortcuts app
2. Create a shortcut (any shortcut) and Edit it
3. (i) button in upper right
4. put a shortcut key in the "Run with:" box
5. Test the shortcut in other apps (works)
6. Test the shortcut in Zed (doesn't work)

<img width="750" alt="Screenshot 2024-08-27 at 10 15 43" src="https://github.com/user-attachments/assets/2274ebac-9eff-418d-a824-969b5ce04558">

**Comment by notpeter** [comment]
I'm actually closing this in favor of:
- https://github.com/zed-industries/zed/issues/11663

As I believe that has the solution (Zed needs to add `Services` menu item)
