### ISSUE TITLE
Add tooltip to `+` button (collaboration window)

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5170]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

-

### Describe the solution you'd like

-

**Comment by maxdeviant** [comment]
Looks like this is done:

<img width="202" alt="Screenshot 2024-03-12 at 6 10 57 PM" src="https://github.com/zed-industries/zed/assets/1486634/e332631a-fe79-43b2-9245-f2ccece08947">
