### ISSUE TITLE
Support for removing or managing collaborators

### ISSUE THREAD

**Issue by clo4** [zed-industries/zed#5172]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

After adding or inviting a collaborator, there's no way to remove (unfriend) them. This is applicable when
* Inviting a friend that you don't want to be able to see your work projects
* Leaving a job where your (now-ex) colleagues don't want _you_ to be able to see their work projects

### Describe the solution you'd like

It would make sense to include this in the new collaborators UI or have a command in the command palette

**Comment by maxdeviant** [comment]
There is now a "Remove Contact" option in the context menu for a contact:

<img width="212" alt="Screenshot 2024-03-12 at 6 12 11 PM" src="https://github.com/zed-industries/zed/assets/1486634/f9563138-80d4-4de7-b49f-c508b52e116b">

(@/osiewicz, I would never remove you ❤️)
