### ISSUE TITLE
Bug with line indicator in bottom right

### ISSUE THREAD

**Issue by ComputerDuck** [zed-industries/zed#5173]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I have multiple split panels open and I hover over one that is not active (one that I'm not writing in right now) it tells me in the bottom right corner what line I was last on in that document. But this does not apply to all of the inactive panels. Also this only occurs while I'm moving my mouse
<img width="1680" alt="Screenshot 2022-10-11 at 11 35 42" src="https://user-images.githubusercontent.com/84136629/196494626-e956cffa-37a0-48f8-9411-7f665f39474a.png">
<img width="1680" alt="Screenshot 2022-10-11 at 11 35 24" src="https://user-images.githubusercontent.com/84136629/196494658-e04ce35a-45b2-4b2e-a464-1b0019443484.png">

### Expected behavior

I should not display a line of an inactive file. Or if it should it should work for all panels.

### Environment

Zed 0.60.4 - /Applications/Zed.app
macOS 12.5.1
architecture x86_64

**Comment by JosephTLyons** [comment]
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. Feel free to open a new issue if you are able to reproduce this somehow.
