### ISSUE TITLE
Adding new files / folders to a workspace is unintuitive

### ISSUE THREAD

**Issue by hueys** [zed-industries/zed#5174]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When closing the last document in a window, the window title isn't updated to reflect that there are no longer any open documents.

**Steps to Reproduce**
1. Create a new Zed window.
2. Either open an existing document or create a new one. If creating a new document, be sure to save it.
3. The window title should update to show the name of the document.
4. Close the document. The window title remains as the name of the document that was just closed.

### Expected behavior

I'd expect when the last document is closed, that the window title would revert to it's default, empty value.

### Environment

`Zed 0.60.4 – /Applications/Zed.app \nmacOS 12.6 \narchitecture x86_64`

**Comment by notpeter** [comment]
It looks like the confusion was due to the project panel being closed and so I'm going to close this issue.  If this is in error, please feel free to reopen with details about how Zed could improve this experience. Thanks for reporing @hueys.
