### ISSUE TITLE
Inline error removal is not discoverable

### ISSUE THREAD

**Issue by r0ckwav3** [zed-industries/zed#5175]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In C++, when Zed finds an error, clicking the error will put it into an inline format. If you then fix the bug, the inline error remains and cannot be removed (as far I could manage).
<img width="230" alt="Screen Shot 2022-10-17 at 12 10 42 PM" src="https://user-images.githubusercontent.com/33732392/196262580-4d1fb8a0-2bc8-4470-a5fa-828171335070.png">
<img width="393" alt="Screen Shot 2022-10-17 at 12 10 52 PM" src="https://user-images.githubusercontent.com/33732392/196262584-ec5be483-920c-43ce-a3de-3e139a330774.png">
<img width="370" alt="Screen Shot 2022-10-17 at 12 11 01 PM" src="https://user-images.githubusercontent.com/33732392/196262589-159ab748-ec2c-42c9-890e-2524bdf45cbf.png">
<img width="352" alt="Screen Shot 2022-10-17 at 12 11 09 PM" src="https://user-images.githubusercontent.com/33732392/196262585-595c3c34-aadc-4857-91c6-53fcdcba9096.png">

(there's another inline error in the second image behind the pop-up, which is my prior attempt at recreating the bug)

### Expected behavior

Either fixing the error would cause the inline error to dissapear or there would be a clear close button to dismiss it.

### Environment

Zed 0.60.4 – /Applications/Zed.app
macOS 12.6
architecture arm64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/9803802/Zed.log)

**Comment by danielzsh** [comment]
Escape still works for me and I'm using vim mode? My two cents: simply clicking on the error to dismiss it (seeing as there's already a copy button so we shouldn't need to worry about the user doing click + drag).

**Comment by JosephTLyons** [comment]
We now present an `x` inline. We may need to polish this UI up a bit, but it currently is visible and hopefully discoverable. I'm going to close out this issue.

<img width="366" alt="SCR-20240727-exqi" src="https://github.com/user-attachments/assets/087928c2-eca3-45c2-be3b-811630da242c">
