### ISSUE TITLE
Astro support

### ISSUE THREAD

**Issue by idioticdev** [zed-industries/zed#5176]
### Check for existing issues

- [X] Completed

### Language

Astro

### Language server link

https://github.com/withastro/language-tools/tree/main/packages/language-server

### Misc notes

Astro has a monorepo for Language tools → https://github.com/withastro/language-tools.

It doesn't appear they have a tree-sitter parser yet. There is a user generated one though → https://github.com/virchau13/tree-sitter-astro

**Comment by JosephTLyons** [comment]
Closing in favor of:

- https://github.com/zed-industries/zed/issues/5263

Also, Astro support will be shipping with today's preview (v0.123.1-pre).
