### ISSUE TITLE
A settings to allow mapping file types to known languages in Zed

### ISSUE THREAD

**Issue by daxartio** [zed-industries/zed#5178]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I want to see Cargo.lock content with highlights syntax’s.

### Describe the solution you'd like

Add a setting to settings.json

### If applicable, add mockups / screenshots to help present your vision of the feature

settings.json

```json
{
    "files": {
        "associations": {
            "*.avsc": "json",
            "Cargo.lock": "toml"
        }
    }
}
```

**Comment by ljwljwljwljw** [comment]
Has anyone started working on this?

**Comment by ljwljwljwljw** [comment]
> > Has anyone started working on this?
> 
> Not that I'm aware of. Feel free to open a PR if it's something you're interested in. :)

I'm trying to implement this, but I found that the current architecture assumes `LanguageConfig` is static and will not be updated by any `Settings`, the `path_suffixes` in `LanguageConfig` for each language  is loaded by [`languages::init(languages.clone(), node_runtime.clone(), cx)`](https://github.com/zed-industries/zed/blob/1f6bd6760fec123000321096819d211d8bd4bed4/crates/zed/src/main.rs#L153) before user's local settings and project settings are loaded. Are there any APIs or callbacks, like `onLocalSettingsLoaded`, that we can use to update the language configs after local settings are loaded?

**Comment by ljwljwljwljw** [comment]
> > > Has anyone started working on this?
> > 
> > 
> > Not that I'm aware of. Feel free to open a PR if it's something you're interested in. :)
> 
> I'm trying to implement this, but I found that the current architecture assumes `LanguageConfig` is static and will not be updated by any `Settings`, the `path_suffixes` in `LanguageConfig` for each language is loaded by [`languages::init(languages.clone(), node_runtime.clone(), cx)`](https://github.com/zed-industries/zed/blob/1f6bd6760fec123000321096819d211d8bd4bed4/crates/zed/src/main.rs#L153) before user's local settings and project settings are loaded. Are there any APIs or callbacks, like `onLocalSettingsLoaded`, that we can use to update the language configs after local settings are loaded?

Another solution may be to pass `AppContext` as an argument to [`language_for_file`](https://github.com/zed-industries/zed/blob/1f6bd6760fec123000321096819d211d8bd4bed4/crates/language/src/language.rs#L893-L897), `language_for_name`, `language_for_name_or_extension` in order to load the user's custom path suffixes settings, however, it requires a lot of changes.

**Comment by nalladev** [comment]
This feature not working for svg - html association
``` json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "features": {
    "edit_prediction_provider": "zed"
  },
  "format_on_save": "off",
  "icon_theme": "VSCode Icons for Zed (Dark)",
  "agent": {
    "default_profile": "write",
    "always_allow_tool_actions": true,
    "default_model": {
      "provider": "copilot_chat",
      "model": "claude-sonnet-4"
    },
    "model_parameters": []
  },
  "buffer_font_size": 15,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark"
  },
  "file_types": {
    "svg": ["html"]
  }
}

```
**Zed 0.215.3**
