### ISSUE TITLE
Basic settings for cursor styling

### ISSUE THREAD

**Issue by partnano** [zed-industries/zed#5179]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Because of the usage of many other editors and tools, I'm used to block-style cursors with which the entire character is highlighted (as it is, I think, the case with vim-mode). Now, as it seems that this a relatively typical customisation option, it was one of the first settings I wanted to change, but found that I couldn't.

### Describe the solution you'd like

The customisation of the cursor could of course be driven ad absurdum, with css-like styling and animations, but I think it probably boils down to 2 main things:

`"cursor_style": ["line", "block", "underline"]` customising what the cursor actual looks like. The proposed list is non-exhaustive of course, but that's the main 3 I can think of right now.

`"cursor_blink": ["always", "temporary", "never"]` customising the blinking behaviour of the cursor, with "always" meaning the cursor blinks forever, even with a while of inactivity, "never" meaning the cursor always stays solid in visible (VSCode named this option "solid") and "temporary" meaning the cursor will blink for a while (e.g. 10 times) and will then stay solid.

There is a lot of room for further customisations that I can see (manual cursor heights and widths, cursor blink speed and exact numbering of how long it should blink, smooth animations, solid or border-only caret, etc.), but I personally think that those 2 simple settings should fulfil most of the cursor-customisation needs.

### If applicable, add mockups / screenshots to help present your vision of the feature

Screenshots of block and underline styles in other editors:

<img width="108" alt="image" src="https://user-images.githubusercontent.com/6125826/196007660-d3db1f6c-30be-4ed6-bf68-a30aec4d0f98.png">
The block placed on the "d" would insert a character before the "d" - it is essentially a line caret extended over the character to the right. (Changing "World" to e.g. "Worlad")

<img width="120" alt="image" src="https://user-images.githubusercontent.com/6125826/196007704-72128115-7fe9-493a-9128-3438f1a9af13.png">
Same behaviour as with the block, described above.

**Comment by ryanwinchester** [comment]
A solid non-blinking block in Vim `normal` and `visual` modes would be nice. 
In `insert` mode the line cursor can blink, would be cool.

**Comment by markomitranic** [comment]
Hey there :) is there any chance that `cursor_style` or `cursor_shape` would be implemented?

**Comment by pierrelegall** [comment]
I consider it is an accecebility feature.

I'm blind as a bat and block cursor help me a lot 🤓

**Comment by charlesphil** [comment]
Looks like there are two newer issues that should really be folded into this one:

- https://github.com/zed-industries/zed/issues/7203
- https://github.com/zed-industries/zed/issues/14447
