### ISSUE TITLE
Sub-language support

### ISSUE THREAD

**Issue by tbeseda** [zed-industries/zed#5184]
### Check for existing issues

- [X] Completed

### Language

Langs in a JS tagged template literal: HTML, CSS, JS

### Misc notes

I'm unsure, but I believe this would need to be a separate JS parser :/

Tree Sitter doc: http://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents

### Comparison screenshot
Here, the JS parser sees the `html` method name and invokes (or has its own?) HTML parser for the tagged template literal. And then the HTML parser even uses a CSS parser when encountering a `<style>` tag.

VS Code  
Zed
![image](https://user-images.githubusercontent.com/15697/195736587-6206a60a-5eb2-41ff-8b8b-9e3a5ab6ba30.png)

**Comment by DeviousM** [comment]
This thing is one of 2 things that is holding me back from switching to zed. This and custom icons in the file explorer 😅 
It'd be awesome to see sublanguage support in a finite future as it's quite a part of a modern frontend, whether we like it or not.

Considering we already have language highlighting in markdown it feels like it shouldn't be that hard to implement for other languages, no?

**Comment by zkat** [comment]
https://github.com/tree-sitter/tree-sitter-javascript/issues/163 suggests that the javascript tree sitter syntax already supports this? somehow? as long as you have html installed?

**Comment by aretrace** [comment]
this is so needed! js has had tagged template literals since es6 and has grown an ecosystem of libraries that use them. it looks like [python](https://github.com/jimbaker/tagstr) could be next.

**Comment by claire-west** [comment]
The opposite case also seems to share the same issue; JS inside an HTML file is highlighted using the HTML rules.

**Comment by cipopescu-dev** [comment]
Perhaps this feature should be added as an extension (see [vscode lit-html](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html)) but it's definitely needed! super useful!

**Comment by XiNiHa** [comment]
Actually it looks like the language injection feature itself is already present. What is missing right now is the interface for extensions to extend existing language queries. I guess the implementation itself will be somewhat straightforward if we have consensus on the interface design.

**Comment by cipopescu-dev** [comment]
This feature was added with release 0.149.3
Thanks a lot Zed team! ❤️

> Added syntax highlighting for tagged template literals in javascript, typescript and tsx languages for css, html, js, json, sql, ts, yaml and yml ([#15984](https://github.com/zed-industries/zed/pull/15984); thanks [RobinMalfait](https://github.com/RobinMalfait)).

**Comment by mrnugget** [comment]
You mean adding an extensions API to change the queries? Yeah, I think a separate issue for that is good.

**Comment by tbeseda** [comment]
This is rad. I am seeing the nested languages in ECMAScript now:

![image](https://github.com/user-attachments/assets/970d3415-a607-4672-9928-49aed441d954)

Thanks, team!

**Comment by JAForbes** [comment]
I'm seeing highlighting for html but not sql, is there something extra I need to configure first?

**Comment by XiNiHa** [comment]
Have you installed the SQL extension?

**Comment by henrikklee** [comment]
how to make this work with comment tagged template literals? e.g.

```ts
const query = /* sql */ `
  SELECT * FROM users;
`;

**Comment by henrikklee** [comment]
Can this issue be reopened for comment tagged template literals?

**Comment by prigaux** [comment]
For comment tagged template literals, it is now handled, cf https://github.com/zed-industries/zed/pull/44180
