### ISSUE TITLE
Movable dedicated panel for the Integrated terminal

### ISSUE THREAD

**Issue by seanmrnda** [zed-industries/zed#5189]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

It is really frustrating when you want to move or drag the terminal around the code editor. 

### Describe the solution you'd like

We need a feature that allows to move the panel around and to be able to just place it anywhere we like.

**Comment by JosephTLyons** [comment]
Hey @seanmrnda, the terminal can now be docked in either the left, right, or bottom dock. I think the following issue might cover what this one is asking, so I'm going to close it out.

- https://github.com/zed-industries/zed/issues/5215
