### ISSUE TITLE
Ctrl + \` increases the character count

### ISSUE THREAD

**Issue by aclementev** [zed-industries/zed#5195]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Typing `` Ctrl + ` `` in the editor increases the character count (or moves the internal cursor position) while visually no character appears on the screen. 

In the attached screenshot I pressed the combination 30 times, and each time the count increased by 1.

This could be related to zed-industries/zed#5196 , since the key combination should be the one that opens the Terminal. 

### Expected behavior

Either some character should appear or the character count should not increase (or the cursor should not move).

### Environment

```
Zed 0.59.0 – /Applications/Zed.app
macOS 12.5.1
architecture arm64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://user-images.githubusercontent.com/17129652/194925467-b7ac1d22-faf4-4380-a0fa-72dd8f8494d3.png)

**Comment by Hug0-Drelon** [comment]
I experience the same issue with a "French" layout.
Also, it prevents the default shortcut "ctrl+`" to open the terminal.

**Comment by jon301** [comment]
> Also, it prevents the default shortcut "ctrl+`" to open the terminal.

Experiencing this too

> What keyboard layout are you using? 

French layout (azerty)

> What does that key combination do for you in other in TextEdit.app?

https://github.com/user-attachments/assets/fd3d7524-5b54-490a-8220-5d140ee6ed19

**Comment by notpeter** [comment]
I am no longer able to reproduce this in current versions of Zed with Spanish keyboard layout. I believe this has been fixed by:
- https://github.com/zed-industries/zed/issues/20425

Thanks for reporting.
