### ISSUE TITLE
Editable themes

### ISSUE THREAD

**Issue by stickyburn** [zed-industries/zed#5206]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Most themes are stunning but it'll be nice to customize or create new ones from scratch!

### Describe the solution you'd like

Every editor I've used has had a bunch of json that can be used to edit themes. Creating them is usually more complicated as it's packaged as an extension. 
A UI would be awesome, tho unsure how friendly it would be without putting too much time.

**Comment by jansol** [comment]
@JosephTLyons this can probably be closed now? We have downloadable theme extensions, custom user themes and theme overrides in settings.
