### ISSUE TITLE
Unable to enter text after making a breaking edit (Python)

### ISSUE THREAD

**Issue by GiacomoPope** [zed-industries/zed#5216]
### Check for existing issues

- [X] Completed

### Describe the bug

While writing a class in python, I deleted some text (I think I removed the colon from the function, or the return value of the function) it seems as though pylance then was trying to check the file and then got upset with me.

The result was I could move the cursor, but whatever I typed had no effect in Zed. The way I fixed it was by opening the file in another editor, fixing the function, saving and then I could type again.

I noticed slowness in other times when pylance wanted to complain "too quickly" when i would edit a function which would break it, so I assume that there was just some very slow deep error with pylance when you have a long class with a broken function spilling over and breaking all functions beneath it?

Sorry I can't be more precise... 

### To reproduce

I haven't been able to replicate this, mainly because I didn't pay enough attention to what was happening. Knowing the work I was doing, I probably broke a function in a class while editing code so that the function didnt return breaking all the other functions below it?

### Expected behavior

I expect to be able to maintain typing even if an edit breaks a function while writing it.

### Environment

Zed 0.54.0 – /Applications/Zed.app 
macOS 12.6 
architecture x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/9611343/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @GiacomoPope, I don't believe we've any other reports of this (I've not ran into it either), so I'm going to close this issue out. If you're still using Zed and run into it again, feel free to open up a new issue!

**Comment by GiacomoPope** [comment]
Thanks! I haven't encountered it against since I made the issue so it's probably been fixed along the way
