### ISSUE TITLE
Mouse doesn't send up events correctly

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#5221]
### Check for existing issues

- [X] Completed

### Describe the bug

The terminal's mouse mode implementations seem to be incorrect.

### To reproduce

1. Run emacs with spacemacs configured
2. Click the mouse
3. move the mouse, observe the selection expand despite the mouse up

### Expected behavior

Not that

### Environment

echo $(/Applications/Zed.app/Contents/MacOS/cli --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)

**Comment by JosephTLyons** [comment]
Is this something you can still reproduce @mikayla-maki?
