### ISSUE TITLE
Ability to disable highlighting of current line

### ISSUE THREAD

**Issue by chriskrycho** [zed-industries/zed#5222]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Current line highlighting is great, but I don't always want it! Especially when *writing* vs. *coding*.

### Describe the solution you'd like

A flag to disable the current line highlight.

**Comment by JackLicc** [comment]
I strongly agree with this proposal. The highlighted line is quite annoying and user-unfriendly.
