### ISSUE TITLE
Empty/unused space in tab area

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5223]
### Check for existing issues

- [X] Completed

### Describe the bug

-

### To reproduce

-

### Expected behavior

-

### Environment

Zed 0.53.1 – /Applications/Zed.app
macOS 12.4
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/19867440/189246464-395d03e0-f021-46d3-b3d9-2f1152c50c5d.mov

**Comment by maxdeviant** [comment]
The empty space is the drop target for dragging new tabs into the tab bar.

I think this is working as intended.
