### ISSUE TITLE
zero-width joined emojis are treated as two characters

### ISSUE THREAD

**Issue by ad-chaos** [zed-industries/zed#5225]
### Check for existing issues

- [X] Completed

### Describe the bug

Pretty much what the title says.

### To reproduce

Open zed.
Paste in 🤷🏻
Try backspacing over it

### Expected behavior

Emoji should be backspaced in a single stroke

### Environment

Zed 0.53.1
macOS 12.5 
architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/90276965/188805568-d2af2347-00c3-4ee7-b7d4-1213a19a28f1.mov

**Comment by znkr** [comment]
I ran into this issue too but with box drawing characters. I believe that multibyte characters are not handled correctly. Not only do they not display correctly, the column position in the status bar at the bottom is incorrect too (i haven’t verified this, but I think it’s a byte offset and not the character offset).

**Comment by JosephTLyons** [comment]
This doesn't seem to be an issue in current Zed, so I'm going to close this out. Feel free to open a new issue if you run into this again.
