### ISSUE TITLE
Hover near top of document exceeds bounds of window

### ISSUE THREAD

**Issue by colin-grant-work** [zed-industries/zed#5227]
### Check for existing issues

- [X] Completed

### Describe the bug

A hover that is triggered near the top of the window extends beyond the top of the window, and there is no way to scroll the top of the hover into view.

### To reproduce

1. Trigger a hover near the top of the window
2. Observe that you can't see the top of the hover.

### Expected behavior

The hover should never extend beyond the window. It should either render above but be locked to the top of the window, or render below the item hovered on. Long hovers should be scrollable.

### Environment

Zed 0.53.1 – /Applications/Zed.app 
macOS 12.5.1 
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="774" alt="image" src="https://user-images.githubusercontent.com/62660806/188327412-14e303c0-8937-4270-9637-28e0847c9820.png">

**Comment by JosephTLyons** [comment]
There's a screenshot of this in:

- https://github.com/zed-industries/zed/issues/5015
