### ISSUE TITLE
Provide the ability to run code actions on save

### ISSUE THREAD

**Issue by zmb3** [zed-industries/zed#5232]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

In order to get a "goimports" like experience where the imports are updated/organized on save, the `gopls` language server provides the 'organize imports' code action.

VS Code is set up to run that action on save, but Zed doesn't have that option, so when introducing a new import you have to manually scroll to the top to run the organize imports action.

In VS Code, the config looks like:
```
"[go]": {
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
}
```

### Describe the solution you'd like

Add a config option to run certain code actions on save for certain file types.

**Comment by JosephTLyons** [comment]
This has landed in [v0.124.0](https://zed.dev/releases/preview/0.124.0).

**Comment by ThomasP1988** [comment]
Can someone explain how to use it please?

**Comment by ConradIrwin** [comment]
You can add a section to your config (`cmd-,`) that looks like this:

```
{
  "languages": {
    "Go": {
      "code_actions_on_format": {
        "source.organizeImports": true
      }
    }
}
```

This is now the default for Go  (https://github.com/zed-industries/zed/blob/main/assets/settings/default.json#L500-L506) but if you want to do other things you'll have to configure them.

If there are sane defaults for other languages please let us know and we can add them to the settings too.

**Comment by ThomasP1988** [comment]
Oh that's the preview release that's why i couldn't see it, downloaded it and it works, thank you very much, will be able to use zed now.

**Comment by albinpk** [comment]
How do I enable this for Dart? My current configuration is:
```json
  "languages": {
    "Dart": {
      "code_actions_on_format": {
        "source.fixAll": true,
        "source.organizeImports": true
      }
    }
  }
```
It doesn’t seem to have any effect. Thanks!
