### ISSUE TITLE
Add a command to focus the pane by specifying the direction

### ISSUE THREAD

**Issue by amaany3** [zed-industries/zed#5235]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

It is not intuitive to use separate focus commands (file tree, git integration) to focus the editor, sidebar, and footer panels.

### Describe the solution you'd like

Add a command to focus the pane by specifying the direction.
It would be intuitive and easy to use if it were possible to focus on a pane by specifying a direction, like tmux.

#### vscode
<img width="709" alt="スクリーンショット 2022-08-29 15 44 08" src="https://user-images.githubusercontent.com/25783732/187139446-9520c841-869d-4e2f-b59b-5e91fda9c347.png">

#### atom
<img width="866" alt="スクリーンショット 2022-08-27 15 06 43" src="https://user-images.githubusercontent.com/25783732/187017419-13cfb10e-e1c6-4e69-ae6c-518266da0b87.png">

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/zed/pull/2757
