### ISSUE TITLE
Selectable text in hover/inline-diagnositics

### ISSUE THREAD

**Issue by ForLoveOfCats** [zed-industries/zed#5236]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

There are a lot of situations where it is useful to copy some text out of some hover popup or inline diagnostic message

### Describe the solution you'd like

The ability to select text in hover popups and inline diagnostics

### If applicable, add mockups / screenshots to help present your vision of the feature

N/A

**Comment by JosephTLyons** [comment]
I've consolidated some issues that were duplicates of this one. Since we've already got a button that allows us to copy diagnostic text, this issue can be retooled to be simply about being able to copy text within popovers.

**Comment by ttenbrinkzenz** [comment]
Would be great if somehow we could also focus the popover when using only keyboard, because now this requires the mouse
