### ISSUE TITLE
Key-bindings for cycling tabs and selecting specific tabs

### ISSUE THREAD

**Issue by avrame** [zed-industries/zed#5244]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

It's cumbersome and slow to have to use the mouse to click on editor tabs to switch between files.

### Describe the solution you'd like

I prefer the vscode:

- [ ] defaults for tab switching, which is ctrl-tab / ctrl-shift-tab for cycling
- [X] ~ctrl-1 ctrl-2, etc for selecting specific tabs. Ideally these keybindings could be specified by the user.~

**Comment by gianpaj** [comment]
Another 2 cents.
<kbd>cmd</kbd> + <kbd>1</kbd>, + <kbd>2</kbd>, etc. are the default shortcuts for switching Tabs in Chrome on Mac

I'm not sure if they're also for VSCode

**Comment by JosephTLyons** [comment]
We currently have commands to cycle tabs in Zed. On macOS, they are `cmd-opt-{left, right}`. We also have the aforementioned commands to selecting specific tabs, so I'm going to close this issue out.
