### ISSUE TITLE
Missing key bindings

### ISSUE THREAD

**Issue by chriskrycho** [zed-industries/zed#5247]
### Check for existing issues

- [X] Completed

### Describe the bug

Props on getting most of the Emacs-influenced CoreText bindings implemented out of the gate (a rarity for a new editor!). There are a handful missing, though:

- [ ] <kbd>Ctrl</kbd><kbd>L</kbd>: should center the cursor in the buffer
- [x] <kbd>Ctrl</kbd><kbd>V</kbd>: should do page down (moving the cursor) – and I could not get key bindings to do this for me; unclear why!
- [ ] <kbd>Ctrl</kbd><kbd>Y</kbd>: should “yank” from the “kill ring”, which is normally separate from the copy/paste buffer. If you choose to keep it in the copy/paste buffer, that’s fine but then <kbd>Ctrl</kbd><kbd>Y</kbd> should be bound to match <kbd>⌘</kbd><kbd>V</kbd>

### To reproduce

Try any of the keystrokes here and notice that they don't work.

### Expected behavior

I, being a very long-time macOS-user, expect these to work *everywhere*. (Chrome and Firefox’s mixed support for them is *the worst*. :joy:)

### Environment

Zed 0.50.0 – /Applications/Zed.app
macOS 12.5
architecture arm64

**Comment by jish** [comment]
I searched around and found this thread, and I'd like to plus one this as well. I think the important point here is that "these keybindings work **everywhere** in mac os".

If I go into the URL bar at the top of my browser window, compose a new mail message, heck they even work in spotlight searches, they just work **anywhere.** I can press `ctrl-a` to go to the beginning of the line `ctrl-e` to go to the end of the line. `option-delete` to "delete word". I didn't realize just how much I use all of these shortcuts, and just how widely they are supported in every single mac os application.

Is there some sort of core support we can add that gets all of these keybindings at once?

**Comment by kiaradlf** [comment]
- [ ] ctrl shift page up: move tab to left
- [ ] ctrl shift page down: move tab to right

**Comment by notpeter** [comment]
> I searched around and found this thread, and I'd like to plus one this as well. I think the important point here is that "these keybindings work everywhere in mac os". (@jish)

These are officially in the [Apple: Mac keyboard shortcuts](https://support.apple.com/en-us/102650) but originate from the GNU Readline emacs mode which is used for implementing line editing for all sorts of CLI applications (notably it was born from Bash).

@chriskrycho I've created a distinct issue for a cut buffer / yank support here:
- https://github.com/zed-industries/zed/issues/14260

@clo4 There's an existing issue for ctrl-o here:
- https://github.com/zed-industries/zed/issues/9891

@kiaradlf I opened this issue for those shortcuts (which I believe are chrome, not Apple derived)
- https://github.com/zed-industries/zed/issues/14261

This leaves `ctrl-l` which is currently bound to `"ctrl-l": "editor::NextScreen"`.  Which appears to toggle scrolling between a top / center / bottom placement of the cursor in the window and only has a keybinding on MacOS.  I'm going to see about changing this default binding, but in the meantime you could add this to your keymap.json and get the behavior you're looking for:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-l": "editor::ScrollCursorCenter"
    }
  }
]
```

Thanks all for reporting these opportunities for Zed to improve.

Please click over to those individual issues and click "subscribe" to follow their progress and 👍 upvote to increase visibility.
