### ISSUE TITLE
Setting to turn off lightning bolt

### ISSUE THREAD

**Issue by albingroen** [zed-industries/zed#5249]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I'm not keen on having lightning bolts everywhere in my code.

### Describe the solution you'd like

A setting to turn off the lightning bolts on the start of lines.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="620" alt="image" src="https://user-images.githubusercontent.com/19674362/184965837-71f0e232-3f70-430f-9219-3ba8e635ce13.png">

**Comment by vaidotasp** [comment]
With the work that has been done on https://github.com/zed-industries/zed/pull/7665, perhaps adding a setting for lightning bolt removal would be easier?

On the flip side, I've been working with Zed for a while now and I dont even notice it popping up on each line in typescript codebases.

**Comment by bbb651** [comment]
Turns out that pr did add it!
```json
"gutter": {
    "code_actions": false
}
```
I think the issue can be closed @albingroen

**Comment by arembridge** [comment]
```json
"gutter": {
    "code_actions": false
}
```

gives me `Property code_actions is not allowed.`

has this setting moved?  the little lightning bolt follows me around telling me that i can organize my (already organised) imports 🫠
