### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by rranjan14** [zed-industries/zed#5251]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

It'd really be helpful to see the images in the workspace. It's really annoying to open the folder in the explorer and see the images.

### Describe the solution you'd like

A simple image preview as shown in VS Code will be sufficient.

**Comment by jansol** [comment]
Bonus points for including support for .dds and .ktx, which are not too common otherwise but heavily used in games. ([I definitely don't have any vested interest in this or anything](https://github.com/jansol/texpresso/))

**Comment by deadcoder0904** [comment]
I get `stream did not contain valid UTF-8. Please try again.`

What's the solution? This looks to be done 6-8 months ago.

**Comment by jansol** [comment]
@deadcoder0904 what image format did you try? PNG, JPEG and GIF should at least Just Work.

**Comment by deadcoder0904** [comment]
Nope, `arcads.png` didn't work but I did try others like PNG, JPG, JPEG, WEBP, or any of the common image formats.

![Image](https://github.com/user-attachments/assets/87683b44-5536-47c0-aff8-02cc485024e0)

I didn't try GIF tho but did try others.

**Comment by jansol** [comment]
Works for me. Please open a new issue with more specific details of your setup and images.

**Comment by deadcoder0904** [comment]
I would have but you guys have maintainers who get mad for opening issues. Like someone whose name starts with `not` so I don't prefer to anymore :)

**Comment by julien-blanchon** [comment]
It's not working for me with a remove (ssh) dev

**Comment by JackLicc** [comment]
Not working for me neither. I tried (.png, .ico, .jpeg), None of them worked in Zed. It says "stream did not contain valid UTF-8. Please try again.", I do love Zed very much with the speed.

**Comment by johnwee1** [comment]
<img width="492" alt="Image" src="https://github.com/user-attachments/assets/561d80a6-1909-4557-a6cf-154c91ba799e" />

I think image viewing is not supported over SSH yet, which is a bummer. How is vscode able to do it though?

**Comment by babhishek21** [comment]
I get it randomly on MacOS. In some projects, images open just fine. And then in others I get this error.
