### ISSUE TITLE
When renaming folders, update module name in code as well

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#5252]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

When changing the name of a folder or file, I have to go through and manually rename all my `mod` statements.

### Describe the solution you'd like

It would be nice if Zed could be tightly integrated with languages which care about file names and would automatically update back and forth.

Note that this is already implemented if using the rename dialog in code. This is about the reverse direction, a file rename action causing a code rename action.

**Comment by park-jemin** [comment]
Bumping this as it's one of the reasons holding my team back from adopting zed

**Comment by hexsprite** [comment]
also came here looking for this as this is a necessary feature for refactoring

**Comment by deveshXm** [comment]
I agree with @huypham50 . I love Zed but whenever I move files I have to manually fix the imports and forces me to back to vs code.

**Comment by galaxymacos** [comment]
Updating global import is also important for me, as this is a feature that only Jetbrains provides now. VSCode can only auto update imports if they are imported using relative path, but can't pick up all the changes if global import alias "@" is used in NextJS project.

**Comment by slowdownitsfine** [comment]
This is one of these not so frequently used tools that remind me of VS Code or Webstorm when using Zed. This would be really nice to have indeed.

Still, Zed is such a breath of fresh air, thank you making it!

**Comment by paulkass** [comment]
Also wanted to put my two cents on this feature: would be really helpful for refactoring projects.

**Comment by mikalsande** [comment]
I ❤️ Zed so far, but I really miss this feature.

**Comment by mk3-14159** [comment]
Any update on this? This is the only thing that's holding me back from migrating fully.

**Comment by h-jennings** [comment]
I've been following this issue closely and this feature appears to have landed in [v0.166.1](https://github.com/zed-industries/zed/releases/tag/v0.166.1) 🎉 

Here's the implementation PR: https://github.com/zed-industries/zed/pull/21651

Thanks to @osiewicz for their work on this!

**Comment by mikayla-maki** [comment]
Good catch, thanks @h-jennings!

**Comment by osiewicz** [comment]
Which language server are you using? This depends on the language server reacting to our notification, so it is plausible that the language server is not handling it.

**Comment by Archivec** [comment]
> Which language server are you using? This depends on the language server reacting to our notification, so it is plausible that the language server is not handling it.

vtsls doesn't seem to handle it

**Comment by seanhealy** [comment]
I'm using Typescript and it turned out to be a problem between the keyboard and chair. I was just missing the little popup in the bottom right corner of the editor asking if I wanted to update imports. 🤦

**Comment by rougsig** [comment]
@seanhealy what popup? Looks like i have literally the same issue between the keyboard and chair.

**Comment by andrienko** [comment]
The popup is helpful, but it asks on every operation. It has an "always" option, but it does not seem to work - I am still getting the popup everytime I rename/move something...

**Comment by kurt-rhee** [comment]
Does this work in python? I'm using ruff and pyright

**Comment by JulienLecoq** [comment]
> p is helpful, but it asks o

Yep, very annoying to have to click on the popup every time
