### ISSUE TITLE
ctrl + click doesn't behave as right click on MacOS

### ISSUE THREAD

**Issue by dlsmith** [zed-industries/zed#5257]
### Check for existing issues

- [X] Completed

### Describe the bug

In my experience on MacOS, it's standard for `ctrl + click` to have the same behavior as right click.

### To reproduce

`ctrl + click` on a symbol

### Expected behavior

I'd expect a context menu to appear, as I'd get using a right click.

### Environment

Zed 0.49.1 – /Applications/Zed.app
macOS 11.5.1
architecture x86_64

**Comment by JosephTLyons** [comment]
`ctrl-click` now works within Zed!
