### ISSUE TITLE
Astro support

### ISSUE THREAD

**Issue by max** [zed-industries/zed#5263]
### Check for existing issues

- [X] Completed

### Language

Astro

### Tree Sitter parser link

https://github.com/virchau13/tree-sitter-astro

### Language server link

https://github.com/withastro/language-tools/tree/main/packages/language-server

**Comment by flvffywvffy** [comment]
Any updates on this?

**Comment by RichardSPrins** [comment]
Just downloaded Zed as well, and do a lot of Astro development. I currently have to tell the editor it's an HTML file, but would love astro support natively. Hoping for an update soon!

**Comment by maxhoffmann** [comment]
This is the PR where Astro support is being worked on:

https://github.com/zed-industries/zed/pull/6896

**Comment by JosephTLyons** [comment]
Support for this has landed in today's [v0.123.1-pre](https://zed.dev/releases/preview/0.123.1) release.
