### ISSUE TITLE
`zed --wait` does not exit when closing the entire Zed window

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/zed#5264]
### Check for existing issues

- [X] Completed

### Describe the bug

The `--wait` flag lets you use the Zed CLI as an `EDITOR` for things like commit messages. The `zed` CLI process will run until the given files have been closed. But right now, if I close a file by closing its entire Zed window, the `zed` CLI process will fail to exit.

### To reproduce

1. Run `zed --wait some/file`
2. Close the resulting Zed window with `cmd-shift-w`
3. :boom: See that the `zed --wait` command is still running

### Expected behavior

The command should exit when closing the window, because the file is no longer open.

### Environment

Zed 0.49.1 – /Applications/Zed.app
macOS 12.4
architecture arm64

**Comment by notpeter** [comment]
I think this is fixed.  I used zed as my git commit editor and have not run into this.

A related enhancement:
- https://github.com/zed-industries/zed/issues/13477
