### ISSUE TITLE
TypeScript "export type from" syntax highlight regression

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/zed#5266]
### Check for existing issues

- [X] Completed

### Describe the bug

When using `export type { ... } from "module"` on multi-lines, the path loses the syntax highlight.

> Regression as I don't remember seeing this behaviour on any Zed's previous version, but I may be wrong.

### To reproduce

1. Create a TypeScript file
2. Add `export type {} from "react"`
3. Force braces to go on multiple lines:
   ```js
   export type {
   } from "react";
   ```

### Expected behavior

The path maintains the syntax colour

### Environment

Zed 0.49.0 – /Applications/Zed.app
macOS 12.1
architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="247" alt="Screenshot 2022-07-27 at 12 39 03" src="https://user-images.githubusercontent.com/8927326/181227606-05f833e5-8e78-4fdc-9102-2c665f1621fd.png">

**Comment by Moshyfawn** [comment]
I believe that it is working as expected today.
