### ISSUE TITLE
Zed changes indentation of comment blocks

### ISSUE THREAD

**Issue by Daeraxa** [zed-industries/zed#5268]
### Check for existing issues

- [X] Completed

### Describe the bug

At least in Rust, if you create a comment block with `/*...*/`, maybe just to comment out a section of code, on save Zed is reformatting the block by left aligning everything to the indentation level of the first line of the block.
It also changes the formatting of the block on first writing it then changes it again, kind of contradicting its own formatting changes.

### To reproduce

Create a new .rs file with (using auto pair indentation as created by Zed):
```rs
fn main () {
    for i in &v {
        println!("{}", i);
        counter += 1;
    }
}
```
Add comment block characters (note the indentation change on the `for`'s `}`.
```rs
fn main() {
    /*for i in &v {
        println!("{}", i);
        counter += 1;
        }*/
}
```
Save the file (note the change to the entire indentation).
```rs
fn main() {
    /*for i in &v {
    println!("{}", i);
    counter += 1;
    }*/
}
```

### Expected behavior

Formatting of code in comment blocks should be left alone, messing with the formatting makes it hard to read commented code.

### Environment

Zed 0.48.1 – /Applications/Zed.app 
macOS 11.5.2 
architecture x86_64

**Comment by notpeter** [comment]
This is an upstream rustfmt thing:
```sh
peter@scruffy rpo % cat r.rs 
fn main() {
    /*for i in &v {
        println!("{}", i);
        counter += 1;
        }*/
}
peter@scruffy rpo % rustfmt r.rs 
peter@scruffy rpo % cat r.rs 
fn main() {
    /*for i in &v {
    println!("{}", i);
    counter += 1;
    }*/
}
peter@scruffy rpo % 
```
