### ISSUE TITLE
Double-click in multi-buffer to jump to that location in a single-buffer

### ISSUE THREAD

**Issue by rkusa** [zed-industries/zed#5275]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

While using Zed as the only editor for a whole day, I was constantly trying to double-click into a multi-buffer to open that location in a single-buffer, but this doesn't work.

I know that Zed has little arrows to jump to locations, but I personally found them to be hard to locate and hard to mentally assign them to their corresponding code locations (as they are always quite far off to the up and right of the code location they correspond to):
![Screenshot 2022-07-21 at 15 09 53](https://user-images.githubusercontent.com/409021/180223444-eb59e423-0602-4996-9e57-78d490fcd9a9.png)

### Describe the solution you'd like

In both Sublime Text and VSCode, you can double-click the occurrence in a search result to open it in a single-buffer.

In Sublime Text, it only works for double clicks on the highlighted occurrence. Double-clicks everywhere else in the excerpt fall back to the default double-click behaviour. In VSCode it works for double-clicks everywhere in the excerpt and it moves the cursor in the single-buffer to the location you've double-clicked.

I'd personally prefer the behaviour of VSCode as I sometimes want to directly jump to an adjacent line. I'd also like this to work in all multi-buffers, e.g. in the find all references one.

### If applicable, add mockups / screenshots to help present your vision of the feature

Example from Sublime Text:

https://user-images.githubusercontent.com/409021/180222442-d252d853-9add-4d4c-85b5-bb891761bfe8.mov

**Comment by hgezim** [comment]
Adding my vote here. Super frustrating and I definitely thought this was a bug. When there are multiple locations that have a search results, it's really unclear on how to get to one of them. Is it even possible right now?

<img width="1452" alt="CleanShot 2024-02-06 at 12 27 14@2x" src="https://github.com/zed-industries/zed/assets/124675/0a9b51e2-b306-412c-a3c9-de935ad6dde5">

**Comment by xixixao** [comment]
For prioritization: Can say this was my immediate and first frustrating experience with Zed. There's no education alt-enter, and I don't even see the arrow mentioned in some old screenshots.

**Comment by SomeoneToIgnore** [comment]
This is supposed to be shipped in Zed 0.127.0

**Comment by hferreiro** [comment]
Hey, I would expect that for the default setting "select", alt + double click would open in a new buffer. Wouldn't that make sense?

**Comment by SomeoneToIgnore** [comment]
Frankly speaking, the whole "double click to navigate" multibuffer feature does not make any sense to me with the alt-enter binding present; now I also regret touching this issue at all as it had caused some controversy around.

This is the code responsible for everything related:

https://github.com/zed-industries/zed/blob/65152baa3f7a55b7a57030d7eef1f94640bb9afa/crates/editor/src/element.rs#L419-L471

there seems to be some logic related to `alt` + single clicks that places another caret in the [multi]buffer if the settings are right, but that does not seem very related to this issue, so the `// do nothing special on double click, all selection logic is below` part could be replaced with more logic to handle this case.

Does not seem like a wrong thing to do, but I won't be the one pushing more changes on top of all this — yet ready to review some, if tagged in the PR.
