### ISSUE TITLE
Zed CLI installation does not working due to app translocation

### ISSUE THREAD

**Issue by hovsater** [zed-industries/zed#5276]
### Check for existing issues

- [X] Completed

### Describe the bug

When installing the CLI tool using `zed: install command line interface`, the symlink in `/usr/local/bin` was not what I expected. It pointed to `/private/var/folders/lp/053qjqyj1cg5gx_23kr9fphc0000gn/T/AppTranslocation/EB60641D-B689-46D7-853D-7875F0B9FFCA/d/Zed.app/Contents/MacOS/cli` instead of `/Applications/Zed.app/Contents/MacOS/cli`. I believe this is due to me moving `Zed.app` via Alfred (https://www.alfredapp.com). I remember reporting similar behaviour to TextMate a while back, as well as Sublime Text.

- TextMate addressed the issue in https://github.com/textmate/textmate/commit/2f09c4562bbc877b3e4d04fbaeabbd3424039f74
- I reported the problem to Sublime Text in https://github.com/sublimehq/sublime_text/issues/3233 and this answer gave some more insight into what's going on (see https://github.com/sublimehq/sublime_text/issues/3233#issuecomment-598786048).

### To reproduce

1. Download Zed from https://zed.dev/releases
2. Move the Zed Binary to `/Applications` using [Alfred](https://www.alfredapp.com/).
3. Install the CLI using `zed: install command line interface`
4. Observe the symlink in `/usr/local/bin`

### Expected behavior

The symlink should point to `/Applications/Zed.app/Contents/MacOS/cli` not the translocated path.

### Environment

Zed 0.48.1 – /Applications/Zed.app
macOS 12.4
architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/503025/180004856-2e17d79d-1fd3-4ccf-9b56-5e609c65261f.mov

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/9150624/Zed.log)

**Comment by notpeter** [comment]
I spent a few minutes seeing if I could duplicate this and I could not.  Perhaps Alfred.app fixed the issue or we're being smarter about the symlink.

Notably if you `zed` cli is pointing at the wrong location (say because you moved the app bundle to a different folder) just rerun Zed->Install CLI again and it will recreate the symlink at /usr/local/bin/zed pointing to the location of the currently running Zed app bundle.
