### ISSUE TITLE
SQL support

### ISSUE THREAD

**Issue by ijzerbroot** [zed-industries/zed#5282]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
(basic) SQL syntax highlighting would be a quality of life improvement feature for me.
I imagine it would/should be way down on the list of things to add but hey, one can always ask :)

Attached is an example of how neovim does it (which is imperfect but gives the general idea)
In practice to me it would mainly be sensible to colorize:
- Reserved keywords (INSERT, UPDATE, DELETE, BEGIN, CREATE, ALTER, DROP, FROM, SELECT, UNION, etc.)
- Quoted strings
- Numeric values
- Comments
- Data types (text, integer, bigint, float, serial, numeric, varchar, etc).

Taking the neovim example as reference I would even prefer they just kept SELECT, AND and NOT in the same color as the other keywords. 

**Describe alternatives you've considered**
N/A

**Screenshots**
<img width="638" alt="Screenshot 2022-07-17 at 11 39 35" src="https://user-images.githubusercontent.com/27082653/179392635-1e18b44b-a499-45ae-a59c-748a92b59539.png">

**Comment by gekh** [comment]
Surprised to have no SQL highlighting. Hope to see it soon.

**Comment by AlexandrePh** [comment]
Any ETA on this feature?
if not could you provide some info around how I could add this to my editor as a custom LSP, perhaps eventually even write this feature for all of us to use (aka contribute to zed)

**Comment by oliver-kriska** [comment]
@AlexandrePh  maybe this doc will help you https://zed.dev/docs/adding-new-languages 
now when it's open source and also recently they added support for extensions so it should be more easy to add support for SQL.
