### ISSUE TITLE
Add project/worktree name to macOS window title

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/zed#5283]
**Describe the solution you'd like**
Right now we title all zed windows "Zed", we should adopt a format like "Zed – Project name" or "Project Name – Zed"

**Screenshots**

Currently not a great experience when minimized, or cmd + tabbing.
<img width="458" alt="CleanShot - 2022-07-16 at 11 46 23@2x" src="https://user-images.githubusercontent.com/1714999/179362021-94df17a8-cb28-42d5-b6bd-aabf5c66d3e0.png">

**Comment by JosephTLyons** [comment]
This has been implemented!
