### ISSUE TITLE
A bit counterintuitive `delete word` behavior

### ISSUE THREAD

**Issue by justicecurcian** [zed-industries/zed#5285]
**Is your feature request related to a problem? Please describe.**
`delete word` behavior is different to other code editors like sublime text and vs code when deleting non-word characters.

**Describe the solution you'd like**
Make it like in vs code.

**Describe alternatives you've considered**
No alternatives available.

**Screenshots (Videos)**
If applicable, add mockups / screenshots to help explain present your vision of the feature.

This is vs code:

https://user-images.githubusercontent.com/24634903/179301934-fa882b9f-f54d-4e27-9210-866f4c250693.mov

This is sublime text 4:

https://user-images.githubusercontent.com/24634903/179300781-03a2920f-87a4-4027-bd0e-4ded90631d0e.mov

This is Zed:

https://user-images.githubusercontent.com/24634903/179301926-c289fa62-8079-478c-8968-abdec7057816.mov

**Comment by notpeter** [comment]
Zed's "word delete" (cmd+backspace) behavior you've demonstrated above is definitely not what I expected.
I similarly expected `cmd-backspace` to only delete the newline and not the last word on the previous line.

The default keybinding suggests cmd-backspace should be bound to `editor::DeleteToBeginningOfLine` but the actual behavior of cmd-backspace is `editor::DeleteToPreviousWordStart`.

https://github.com/zed-industries/zed/blob/89739d5874c4c9626f70580fa2bb3fea10d42632/assets/keymaps/default-macos.json#L50-L50

Additionally, when I open the command palette it shows multiple incorrect cmd+backspace shortcuts:
<img width="563" alt="image" src="https://github.com/zed-industries/zed/assets/145113/32b4953c-ba86-4ab4-8861-339596a5b2b6">

This behavior definitely diverges from what I would expect after using other editors (Sublime/VScode/MSWord/Chrome textbox) although it does match the behavior of others (TextEdit/TextMate/XCode/emacs).

I think perhaps the behavior of `editor::DeleteToPreviousWordStart` should be altered to consider a newline as a "word" and then create a new alternate command like `editor::DeleteToPreviousWordStartIgnoringNewlines` for the current behavior.

Not sure which is the correct behavior for `ctrl-w`.

**Comment by dabeeeenster** [comment]
This still hasnt hit the production build - how come?

**Comment by SomeoneToIgnore** [comment]
https://zed.dev/docs/development/releases

> Zed currently maintains two public releases for macOS:
>
> * [Stable](https://zed.dev/download): This is the primary version that people download and use.
> * [Preview](https://zed.dev/releases/preview): which receives updates a week ahead of Stable for early adopters.

**Comment by dabeeeenster** [comment]
Ah many thanks
