### ISSUE TITLE
Configurable Interface Font/Font Size

### ISSUE THREAD

**Issue by dnjp** [zed-industries/zed#5286]
**Describe the solution you'd like**
I would like to be able to configure both the font and font size for the interface surrounding the editor window. Currently, the default font does not match the font or font size I'm using for the editor window.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/37786372/179285157-0f7236d6-4562-4d4a-b03f-92bed4b5ea5b.png">

**Comment by frou** [comment]
Woop woop. It's now possible:

* Install Apple's **SF Pro** font in such a way that it's available to other applications:
```shell
brew install --cask homebrew/cask-fonts/font-sf-pro
```

* Add to Zed's settings file:
```json
"ui_font_family": "SF Pro",
"ui_font_size": 15,
```

**Comment by bsiegel** [comment]
SF Pro's internal font name seems to be simply "System Font". On a whim I tried adding `"ui_font_family": "System Font",` to my settings and it worked.

**Comment by maxbrunsfeld** [comment]
This is done.

**Comment by eproxus** [comment]
@bsiegel Can confirm this works. There's a tooltip that says "Value is not accepted" but it works anyway.

**Comment by eur2** [comment]
@dnjp love your settings on the screenshot. 
How did you set the top bar thinner with the name of the repo inside?

**Comment by jhaemin** [comment]
@bsiegel `"System Font"` is exactly what I was looking for without installing additional fonts. Thanks.

**Comment by escandiel** [comment]
> **Describe the solution you'd like** I would like to be able to configure both the font and font size for the interface surrounding the editor window. Currently, the default font does not match the font or font size I'm using for the editor window.
> 
> <img alt="image" width="872" src="https://user-images.githubusercontent.com/37786372/179285157-0f7236d6-4562-4d4a-b03f-92bed4b5ea5b.png">

Which font-family are you using in the editor?

**Comment by apostoiis** [comment]
@escandiel it must be Iosevka (or a custom variation of it)

**Comment by IArnaut2** [comment]
I'd like to configure menu bar font individually too, because it's too small.

<img width="1920" height="1020" alt="Image" src="https://github.com/user-attachments/assets/32854b6a-db23-4747-845b-4ff4c05bd104" />
