### ISSUE TITLE
Ability to easily jump to the beginning of any visible word in the active buffer

### ISSUE THREAD

**Issue by damoonrashidi** [zed-industries/zed#5289]
**Before you begin**
I tried searching for jump / cursor etc but didn't find anything relevant, so hopefully this isn't a dupe, sorry if it is. Also I recognise that this is a pretty low priority request!

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd love for a way to move the cursor to the beginning of any visible word in the active buffer using only keyboard shortcuts.

**Describe alternatives you've considered**
The closest thing currently available is hitting `cmd+shift+o` to open the outline viewer and go to a declaration in close proximity to where you want to go to minimise the number of arrow key presses necessary. Unfortunately this doesn't work if there isn't a declaration close to where you want to jump.

Another alternative is hitting `ctrl+g` and jump to the beginning of specific line and then hitting `⌥ + →` until you hit your destination.

**Screenshots**
There are extensions for sublime/vs code that achieve this by overlaying a character sequence over every word when a keyboard shortcut is hit as shown below.

before hitting `cmd+shift+;`
![image](https://user-images.githubusercontent.com/207421/179216639-7c488710-80cc-4dab-bff4-efdd15b05a06.png)

after hitting `cmd+shift+;`
![image](https://user-images.githubusercontent.com/207421/179216675-c9f3d42c-43f6-496a-905d-60c35e4d10ff.png)

after typing any highlighted character / pair of characters (e.g. `u` `vk` `nd` etc) the cursor jumps to the highlighted location.

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/zed-industries/zed/issues/4930

There is also a separate request for UI navigation using similar motions:
- https://github.com/zed-industries/zed/issues/5063

Thanks for reporting.
