### ISSUE TITLE
Sort command palette items alphabetically

### ISSUE THREAD

**Issue by alejandrovrojas** [zed-industries/zed#5293]
**Is your feature request related to a problem? Please describe.**
Being new to Zed, the command palette is a handy way of browsing through features and keyboard shortcuts. 

**Describe the solution you'd like**
It isn't very clear how all the commands are sorted, but it would be much easier to go through the list if all commands were sorted alphabetically, specially since they're already grouped by categories: _editor, vim, workspace_, etc.

**Comment by JosephTLyons** [comment]
Zed now sorts these actions alphabetically by default, but then later adds some rankings as you use the commands (recency). These rankings are not serialized and are reset when closing and reopening Zed. I think this satisfies the original request, so I'm going to close this out. Please open a new issue if there is more here we should do.
