### ISSUE TITLE
Deleting a file while having project search or multibuffer interface will restore it

### ISSUE THREAD

**Issue by yoroshikun** [zed-industries/zed#5297]
**Describe the bug**
Deleting a file while having project search / multi-buffer interface will restore it without indication.
This also is somewhat connected to multi-buffer saving ALL files with command+s, 

**To reproduce**
Steps to reproduce the behavior: Make a file with project text searchable text, search that text, delete the file, save the file while search still open.

**Expected behavior**
Either a note saying that you are trying to save deleted content. Related to zed-industries/zed#5335 
Deleted files should cause project search to research?

**Screenshots**
![reappearing-zed-delete](https://user-images.githubusercontent.com/1892447/178907884-2dc2dbbd-4422-497b-aa1a-c2725ac1b453.gif)

**Environment:**
Copy & paste output of this command:
```sh
Zed 0.47.0 – /Applications/Zed.app
macOS 13.0
architecture arm64
```

**Comment by JosephTLyons** [comment]
I'm going to close this out in favor of:

- https://github.com/zed-industries/zed/issues/9101

If anyone is following this thread, please upvote (👍) #9101.
