### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by undersquire** [zed-industries/zed#5299]
[OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn) seems to be the best option for a C# language server.

**Comment by just-ero** [comment]
Roslyn's Language Server Protocol recently went open source: https://github.com/dotnet/roslyn/tree/main/src/Features/LanguageServer.

It should be more trivial to support all languages which use Roslyn as a compiler (C#, VisualBasic) now.

**Comment by fminkowski** [comment]
I opened a [PR](https://github.com/zed-industries/zed/pull/6908) for C# support.

**Comment by JosephTLyons** [comment]
C# support shipped with [v0.121.0-pre](https://zed.dev/releases/preview/0.121.0)!

**Comment by wk-j** [comment]
@JosephTLyons 

Code action doesn't work,  the suggested code action does not yield any response or result

<img width="1212" alt="image" src="https://github.com/zed-industries/zed/assets/860704/09bcd59f-c34e-41a8-a265-1ae85139d509">

**Comment by luizen** [comment]
> @JosephTLyons
> 
> Code action doesn't work, clicking on the suggested code action does not yield any response or result

Same here. Nothing happens when I click any of the options (Go To Definition / Find All References, etc). Am I missing something?

**Comment by Moshyfawn** [comment]
My advice would be to create a separate issue if one doesn't already exist.

**Comment by fminkowski** [comment]
Omnisharp is slow to start up. Do you still not receive any options after waiting a bit?

**Comment by luizen** [comment]
I managed to make it working by following the workaround described here: https://github.com/zed-industries/zed/issues/8352#issuecomment-1962887464

**Comment by abliger** [comment]
Hello, I need to use the nuget package. How can LSP find the association?

**Comment by davidnagli** [comment]
![Screenshot 2024-04-25 at 11 21 51](https://github.com/zed-industries/zed/assets/6759650/101d6122-268d-4082-9cf4-f8edff662496)

I'm running the latest Zed release (Zed 0.132.2) but I don't see C# in the language selector... am I doing something wrong?

**Comment by maxbrunsfeld** [comment]
@davidnagli you should have been prompted to install the C# extension:

![Screenshot 2024-04-25 at 1 29 57 PM](https://github.com/zed-industries/zed/assets/326587/5dae4f16-5597-47f9-b45a-b9e06bf9dbda)

Did that prompt not show up for you?

In any case, you can fix this by opening the Extensions pane, searching for `C#`, and installing the extension.

**Comment by davidnagli** [comment]
Strange, that prompt didn't show up but all good I found the extension and
installed it. Thanks!

Once I installed it and configured it I had a memory leak and crash (over
5GB RAM used by Zed!), but I'll open a separate issue for that :)

**Comment by MidKnightXI** [comment]
Is it normal that I don't have any suggestions anymore for my projects in ASPNET, it was working fine some time ago and tried it out recently and nothing ?

The extension is installed on my side but I just have the "colorization" of code but nothing else?

Is it a known issue or did I do something wrong ?

**Comment by davidnagli** [comment]
> I managed to have it finally working by following the workaround described here: [#8352 (comment)](https://github.com/zed-industries/zed/issues/8352#issuecomment-1962887464)

@MidKnightXI Seems like a known-ish issue with a workaround which can be found there ^

I followed the workaround yesterday and it fixed my issue and got the actual language server to start (not just syntax highlighting)
