### ISSUE TITLE
Zig support

### ISSUE THREAD

**Issue by undersquire** [zed-industries/zed#5300]
Zig has an [official language server](https://github.com/zigtools/zls) that can be used.

**Comment by ThatXliner** [comment]
https://github.com/zed-industries/zed/blob/90c1d8f734615552297a65e12dd430bf0825cdb0/crates/zed/src/languages.rs#L23


This could be a good place to start. Is there an official guide on how to contribute new languages?

**Comment by cldixon** [comment]
@JosephTLyons _Zig for Zed_ sounds so great. 😄

**Comment by JosephTLyons** [comment]
@cldixon - I just ran into a user in the Ghostty community who has a branch with Zig all wired up in Zed!

**Comment by JosephTLyons** [comment]
Closed via https://github.com/zed-industries/zed/pull/6690
