### ISSUE TITLE
Zed to embed other apps' windows

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#5310]
Okay, in all fairness, this one is pretty _on the edge_ as a "feature request", but bear with me…

I know recently you've started building a terminal into Zed (which is totally okay), and possibly in the future, there will be other requests for Zed to visualize more things than the editor UI itself (e.g., a browser window).

So, I was wondering, how wild (and doable) of an idea would it be if Zed was to have some type of "window management" features? What I mean by "window management" is something like Zed opening a new tab/panel and constraining another macOS app's window to stay in its boundaries (possibly, if possible, cropping out the title bar, frame, the shadow, etc.)?

This app's process obviously wouldn't be as "integrated" into Zed (e.g., it wouldn't maybe Zed's built-in search, etc.) but it WOULD; 1) behave as if it was part of Zed's window; 2) allow Zed to virtually work with any type of wild "external" app.

Here's an example wireframe of the iTerm2 app (my preferred terminal app):

![New Wireframe 2](https://user-images.githubusercontent.com/314398/177951394-2b74329f-0a24-4ff3-ba74-ef8b267f906d.png)

And here's another wireframe with a Chrome window, with DevTools open:

![New Wireframe 3](https://user-images.githubusercontent.com/314398/177951476-878bf42a-2683-43a3-91ca-45a2baccaf84.png)

I don't know whether this is pure wishful thinking on my part or is it actually possible to "embed/pilot" other apps' windows on macOS, but it sure is a neat trick to pull off!

This feature request is also somewhat tangent to a future "screen sharing" feature where, whilst pairing with another developer, Zed wouldn't have to share the user's entire screen, rather only the split panel's frame.

**Comment by rgbkrk** [comment]
> I think this post could be a strong indication that there's a demand for an OS windowing system based on the pane model, rather than the traditional free floating windows. Interesting idea!

Bloomberg Terminal makes the big $$$ as a pane interface. It could be the real-time data access but I'd like to believe its the paneling.

**Comment by ConradIrwin** [comment]
Closing this as "not very likely to happen in the next decade" :D.

**Comment by exalted** [comment]
@ConradIrwin LOL! Fair… I will take my chances… 😉

**Comment by zaunere** [comment]
The availability of a straightforward yet robust, cross-platform GUI framework is something the broader open source community desperately needs.

Otherwise we'll remain under the thumb of the incessantly evil, corrupted and manipulated "standardized" web view.

Something that wraps the web view, vs always trying to get into the walled garden.

Like Midnight Commander - TUI/GUI switching would be cool too :)

Hans

**Comment by kubijo** [comment]
I was just thinking of this as well... granted, if I were an author of an app and someone would suggest this I would facepalm really hard…

…but lately I've been trying to use Zed fully for the LLM-driven dev and I love the new agent threads / ACP render + code + terminal on one window that is the whole dev flow.

Much better than having to wrangle separate windows between IDE, terminal with shell & agent TUI.
But I would prefer a Warp terminal view embedded in that terminal window.
