### ISSUE TITLE
Render markdown in comments/doc comments

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/zed#5313]
Basically, title. We can definitely do a better job rendering md than VSCode is doing here.

## Zed:
<img width="1118" alt="CleanShot - 2022-07-07 at 11 53 30@2x" src="https://user-images.githubusercontent.com/1714999/177817545-bc7aaade-7029-4c81-8cad-5113c4ea96de.png">
<img width="1037" alt="CleanShot - 2022-07-07 at 11 53 48@2x" src="https://user-images.githubusercontent.com/1714999/177817595-da9a7da2-14bd-45c2-a4ba-99213b0a19e9.png">
<img width="1126" alt="CleanShot - 2022-07-07 at 11 55 49@2x" src="https://user-images.githubusercontent.com/1714999/177818012-cdfff39e-5261-49c3-abc1-7a0596160e0f.png">
<img width="1080" alt="CleanShot - 2022-07-07 at 11 58 26@2x" src="https://user-images.githubusercontent.com/1714999/177818601-4f108a44-94c5-45ea-bee0-1a12a1c9227b.png">

## VSCode:
<img width="675" alt="CleanShot - 2022-07-07 at 11 56 19@2x" src="https://user-images.githubusercontent.com/1714999/177818125-d1201bf2-bcaf-4839-afb7-fd502f71d854.png">
<img width="668" alt="CleanShot - 2022-07-07 at 11 57 56@2x" src="https://user-images.githubusercontent.com/1714999/177818502-fadd9348-53c3-491f-a3a8-f56bbccada6d.png">
<img width="988" alt="CleanShot - 2022-07-07 at 11 57 26@2x" src="https://user-images.githubusercontent.com/1714999/177818400-230eaa1a-3f17-459e-a213-0b6f3b0c11db.png">
<img width="834" alt="CleanShot - 2022-07-07 at 11 56 52@2x" src="https://user-images.githubusercontent.com/1714999/177818281-631ccf8c-2b2c-4a6d-aa34-b6317b311453.png">

**Comment by olrtg** [comment]
I would like to work on this! were (more or less) should I look into @iamnbutler @JosephTLyons?

**Comment by iamnbutler** [comment]
I think this exists now? 
![CleanShot 2024-10-03 at 13 38 21@2x](https://github.com/user-attachments/assets/22613a59-fbea-41ad-8291-a81f07a3df97)

I'm going to close this, but @JosephTLyons feel free to re-open if that isn't correct for some reason.
