### ISSUE TITLE
Separator between split panes disappears at certain window widths when using external display

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/zed#5314]
**Describe the bug**
When I use an external display (In my case a Dell U3219Q) and use to horizontally split panes the separator between them disappears at some window widths.

**To reproduce**
Bring up Zed on external monitor and adjust window width until the separator disappears.

**Screenshots**
https://user-images.githubusercontent.com/43202406/177748933-d385019f-1530-4ea2-ba0a-a2a95deb3f16.mov

**Environment:**
```
Zed 0.45.0 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64
```

**Comment by JosephTLyons** [comment]
Hey @shot-codes, this issue is pretty old and Zeds GPUI framework has been mostly rewritten from the ground up. I'm not able to reproduce this issue, so I'm going to close it out. If you hit it again, feel free to open a new issue.
