### ISSUE TITLE
OCaml (+ ReasonML) support

### ISSUE THREAD

**Issue by maxkorp** [zed-industries/zed#5316]
Preliminarily, the TLDR basic request here is syntax and LSP support for OCaml and ReasonML (another syntax for OCaml).
I realize that this may need to be a third party extension, but perhaps all of this can provide context on what's required to support it by adding ones own LSP calls (as I think that's on the short term roadmap?). 

In VSCode, this is provided by this extension: https://github.com/ocamllabs/vscode-ocaml-platform
That extension calls out to this LSP, which I'll describe installation of below: https://github.com/ocaml/ocaml-lsp 

The minimum file syntax support would be for `.ml`, `.mli`, `.re` and `.rei` files which I _believe_ is provided through the LSP. There are more related file types listed here: https://github.com/ocamllabs/vscode-ocaml-platform#features. Not sure if those are included via LSP or separately. 

A bit more detail that I hope will be useful:
A bit of a note is that the ocaml toolchain is not typically installed directly but as a package by `opam` (the primary ocaml package manager, think nvm + npm), or sometimes esy (which also does venv-type sandbox stuff and also ties into actual npm). 
Opam uses "switches" (think `nvm use 12`, but with names so you can many on the same version) which are either global or local. esy uses sandboxes (which can be defined with an `esy.json` file or inside of `package.json` iirc). The vscode extension allows you to switch to the sandbox you desire so it can run the appropriate LSP. Whatever solution comes soon for running one's own LSP would need a way to specify which switch to activate before running the lsp, unless starting the lsp is left to the user to do externally. There's also a need to pass flags to the LSP at times in a project, which again would need to be doable if this is controlled within zed. 

Hopefully that wasn't more confusing than helpful!

**Comment by smorimoto** [comment]
tree-sitter: https://github.com/tree-sitter/tree-sitter-ocaml

**Comment by JosephTLyons** [comment]
Since OCaml language support has landed in Zed, let's close this issue out and open a new issue for whatever else didn't make it in from the original request.

**Comment by davesnx** [comment]
Hey, do I need to open another issue for ReasonML? 

Tree-sitter is here: https://github.com/reasonml-editor/tree-sitter-reason

**Comment by jpx40** [comment]
> Hey, do I need to open another issue for ReasonML?
> 
> Tree-sitter is here: https://github.com/reasonml-editor/tree-sitter-reason

just wanted to open a issue myself xd

**Comment by davesnx** [comment]
Go for it @jpx40

**Comment by jpx40** [comment]
> Go for it @jpx40 

Do you know if u could add multiple treesitter in one extension maybe i could make a commit for the ocaml one, it's not worth to add a specific reason extension because of the lsp. It's the same as the ocaml one.

**Comment by Khady** [comment]
@jpx40 I believe it is, the ocaml extension already has multiple ones

https://github.com/zed-extensions/ocaml/blob/f03fd28794a003e8f266eeb91f1483e438b07f7d/extension.toml#L13-L25

**Comment by jpx40** [comment]
@Khady yeah, it would be nice to have reasonml as well.
