### ISSUE TITLE
Cannot install gopls when Go is not in the default env path

### ISSUE THREAD

**Issue by jacobbednarz** [zed-industries/zed#5318]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Describe the bug**

When opening a Golang file, I encounter the following error.

```
Language server error: Go

failed to install gopls. Is go installed?
```

**To reproduce**

- Use asdf-vm to install Go
- Ensure it is correctly setup
- Attempt to open a Golang file
- See error reported

**Expected behavior**

- Go file opens and `gopls` can be installed (or use the existing one on my $PATH

**Screenshots**

**Environment:**

Zed 0.45.0 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jacob/Library/Caches/go-build"
GOENV="/Users/jacob/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jacob/.asdf/installs/golang/1.17.9/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jacob/.asdf/installs/golang/1.17.9/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/jacob/.asdf/installs/golang/1.17.9/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jacob/.asdf/installs/golang/1.17.9/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.9"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jacob/go/src/github.com/cloudflare/cloudflare-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/36/zlscnhfn27n1yxx52cr1kdmr0000gp/T/go-build632993627=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```
$ which go gopls
/Users/jacob/.asdf/shims/go
/Users/jacob/.asdf/shims/gopls
```

Is there a way I can manually work around this in the meantime? Either by downloading the language server manually or forcing it in? Docs state Go isn't yet supported but the invite email said it was so unsure if this is still in progress.

**Comment by cyberbeast** [comment]
Encountering the same issue. Running `sudo zed .` in my application directory seemed to work. Any reason why `sudo` is required to make it work?

**Comment by DavidConnack** [comment]
This happens with go (and gopls) installed with brew as well:
```
which go gopls
/opt/homebrew/bin/go
/opt/homebrew/bin/gopls
```

**Comment by alexey-drozd** [comment]
Still experiencing it. My current workaround is to start zed from the shell after entering the directory with an `.envrc`.

**Comment by mrnugget** [comment]
Interesting, because when we look for `gopls`, we do launch a shell in the project's directory, try to load `direnv`, and then get the PATH from that. If we then find `gopls` in that PATH, we start `gopls` with that environment, which should also presumably be the environment in which the correct `go` version is found, right? See here: https://github.com/zed-industries/zed/blob/main/docs/src/environment.md

**Comment by jacobbednarz** [comment]
i'm no longer experiencing this with either asdf-vm or mise. happy to close out unless someone can provide a reproduction case where they are still seeing it (we should really just close this one in favour of a fresh report if that's the case).

**Comment by mrnugget** [comment]
> (we should really just close this one in favour of a fresh report if that's the case).

Yep, I'm with you! Let's do that.

**Comment by alexey-drozd** [comment]
Filed #18908 for the exact problem I'm experiencing.
