### ISSUE TITLE
Save window state (size + position) for next launch

### ISSUE THREAD

**Issue by themisir** [zed-industries/zed#5319]
**Is your feature request related to a problem? Please describe.**
Currently when I launch new zed instance it launches with a maximized window. I usually got used to apps saving window state so when I set specific size and launch a new window or instance it usually uses previously set window state.

**Comment by Moshyfawn** [comment]
I think this is already today's behaviour, so I will close this issue. Please let us know if you're still seeing the unwanted behaviour.
