### ISSUE TITLE
Support user's default shell

### ISSUE THREAD

**Issue by gaetgu** [zed-industries/zed#5320]
When I open up the terminal, it uses `zsh` (macOS's default), but I have set the default to fish. This isn't *that* big of a deal, but I would really love it if the terminal used my default (fish) instead of mac's default (zsh).

**Environment:**
Zed 0.44.1 – /Applications/Zed.app
macOS 13.0
architecture arm64

**Comment by joefitzgerald** [comment]
I cannot seem to reproduce this issue, and I use fish / MacOS.

**Comment by snokpok** [comment]
can reproduce the issue for me; have both zsh and fish on my Mac

**Comment by jasongitmail** [comment]
I experienced something related that might help others encountering this Github Issue.

**Problem**
For Zed's integrated terminal, `which fish` would return `/usr/local/bin/fish` (undesired). But every other terminal on my system, `which fish` returns `/opt/homebrew/bin/fish`. This resulted in Zed's terminal having an older NodeJS version, among other things.

**Solution**
My fish config contained `eval (/opt/homebrew/bin/brew shellenv)`, which has always been sufficient to set up Homebrew for my system previously. But for Zed's integrated terminal, I had to also add `set -gx PATH /opt/homebrew/bin $PATH` below that line in my Fish config. With it, Zed's integrated terminal returns `/opt/homebrew/bin/fish` for `which fish` and all works as expected.

(M1 series Mac, Zed 0.133.7, Homebrew 4.2.20, Fish 3.7.1)

**Comment by jerrygreen** [comment]
I use nushell as my default shell, it works without an issue. So there’s such a feature, and it is working. And I didn’t have to include any workarounds like `set -gx` something. That’s weird.

By the way, if you like fish, you will probably love nushell, have a try it’s really great

**Comment by Approximately-Equal** [comment]
Want to second checking /etc/passwd. Not sure if there are more normal ways of fixing this, but I had this issue on macOS. Using `which fish` was correct but the shell still didn't use fish. You can always use the nuclear option and manually change root in /etc/passwd to wherever path your shell is. It will change it for all users as far as I can tell (which is why its a nuclear option), but if you're the only person using the machine it shouldn't matter.

**Comment by notpeter** [comment]
I believe this has been fixed for a while and Zed detects the users shell when launching terminal.

**Comment by aswinmohanme** [comment]
For future users, I had reset my mac and changed the shell, but Zed was not detecting it. I had to restart my mac to get Zed to switch to fish shell.
