### ISSUE TITLE
`Cmd+W` with no open tabs doesn't close the window

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/zed#5322]
**Is your feature request related to a problem? Please describe.**

Just a tiny nit (feel free to say if these tiny bugs aren't helpful), but when the window is empty, I would have expected `Cmd+W` to act like `Cmd+Shift+W`, but it currently does nothing.

(See: behaviour in Atom, VS Code)

**Comment by fredngo** [comment]
This is expected MacOS behaviour and sorely needed!

**Comment by dangh** [comment]
TBH I think the way VSCode designed this feature is a mistake. There are two separate actions:
- Close a pane
- Close a window (which is empty)
and it happens that we want to use the same keybinding for these actions. The proper way to implement it is mapping the same key in different contexts, not introducing an "option".

Also, there is not an application on macOS that I know behaves this way. They never have an "empty" state as it always requires a file/document to work with. But in Zed, we have an empty state and it is useful. Following macOS behavior is just wrong.

My apologies if it sounds harsh. Zed is moving fast and ships lots of useful features but it also introduces breaking changes that make it frustrating to use. Especially with someone who didn't come from VS Code world like me.

**Comment by clseibold** [comment]
I agree with @dangh . On Linux and Windows, VSCode doesn't close the window on Ctrl+W, but Zed now does apparently. Yuck! I **hate** that!

**Comment by maxdeviant** [comment]
We are reverting this change in https://github.com/zed-industries/zed/pull/10986.

A new Preview build will be out soon without this behavior.

**Comment by mijndert** [comment]
@maxdeviant any chance we can get this back for macOS? Not being able to close the window with cmd+w when no tabs are left is really the opposite of what you would expect from a Mac app.

**Comment by fuzenco** [comment]
> @maxdeviant any chance we can get this back for macOS? Not being able to close the window with cmd+w when no tabs are left is really the opposite of what you would expect from a Mac app.

I agree. I’ve been running Mac for nearly 30 years and no native app leaves a window open. And even Electron apps adhere to that. Give us an option.

**Comment by dangh** [comment]
@fuzenco I hope the option would be mapping the key in different contexts like I described above. In fact, that's how Safari does it too. When the window has tab, Cmd+W is bind to Close Tab, but on an empty window it's bind to Close Window.

All the macOS apps I know either work with single documents (so there's no point leaving an empty window) or have an option to restore the closed window (all browsers have that). If we want to make that the default behavior for Zed then restoring window must be a thing.

**Comment by clseibold** [comment]
Most apps don't have the concept of an open project where you would want to keep a window open with no tabs. But for a text editor, people frequently keep a project/folder open with no tabs. That is why I consider this macOS design to be awful UX. In a browser, you *can* just close the window when you close the tab. **Not so** for text editors. Context matters in UX-design.

**Comment by fuzenco** [comment]
>  **Not so** for text editors. Context matters in UX-design.

I don’t know about that. One of the longest-running text editors on Mac—over 30 years—the famed BBEdit, allows for closing a project window when there is no tab open.

**Comment by clseibold** [comment]
> I don’t know about that. One of the longest-running text editors on Mac—over 30 years—the famed BBEdit, allows for closing a project window when there is no tab open.

Sure, and my opinion is that that is terrible design.

**Comment by fuzenco** [comment]
> > I don’t know about that. One of the longest-running text editors on Mac—over 30 years—the famed BBEdit, allows for closing a project window when there is no tab open.
> 
> Sure, and my opinion is that that is terrible design. Almost every editor I know doesn't do this on Windows/Linux, including VSCode and Sublime Text. There's a reason for that.

And that’s why we are asking for the **option**, even if that’s not the default you would wish.

**Comment by clseibold** [comment]
> allows for closing a project window when there is no tab open.

Also, you **can** close a window without this option. You use the specific keybinding that closes the window: Ctrl+Shift+W.

**Comment by fredngo** [comment]
I was so excited to see this was finally done and then saw it was reverted!

I understand that perhaps it doesn't work like that in Windows or Linux. But on Mac, it *is* expected behavior to have `Cmd+W` close the app when there is no file open. Don't care about whether it is wrong or not -- unfortunately there is decades of history behind that now.

So, we need an if statement basically! Annoying that things don't behave the same way in Mac and Windows but I'm sure this can't be the only if statement to take care of stuff like that in the whole program.

**Comment by clseibold** [comment]
I was under the impression that this close window on Cmd+W when no tabs are open was started by VSCode, because of a comment someone mentioned in the Discord.

Anyways, I guess I just don't get the *importance* of this feature. Cmd+Shift+W works just fine and it's less prone to accidental closing of the window.

**Comment by fredngo** [comment]
So... this issue is closed now. But it's not. Can we re-open please?

**Comment by bartekpacia** [comment]
It still doesn't work for me (macOS Sonoma, Zed 0.133.5)

**Comment by huangqun** [comment]
It's not working for me either (macOS Sonoma 14.4.1, Zed 0.133.5).

**Comment by maxdeviant** [comment]
> It still doesn't work for me (macOS Sonoma 14.4.1, Zed 0.133.5)

We reverted the change, so that’s why it isn’t working.

**Comment by thuvasooriya** [comment]
> > It still doesn't work for me (macOS Sonoma 14.4.1, Zed 0.133.5)
> 
> We reverted the change, so that’s why it isn’t working.

whyy whyy whyy
can i override the keybindings?

**Comment by mikayla-maki** [comment]
It's on main now, should be hitting stable in two weeks and change :)

**Comment by SunBK201** [comment]
Is the "when_closing_with_no_tabs" option still valid on macOS? I tried it on the latest macOS and it seems that when all tabs are closed, the window still does not close automatically. #21100

**Comment by staciax** [comment]
it's work now thank you <3

Zed 0.176.3 
MacOS 15.3.1

```json
{
  "when_closing_with_no_tabs": "keep_window_open"
}

```
