### ISSUE TITLE
Support spaces in fuzzy search

### ISSUE THREAD

**Issue by nathansobo** [zed-industries/zed#5324]
@wilhelmklopp pointed out that VS Code supports spaces in fuzzy search queries, though we didn't figure out exactly their behavior. We should support this as well, because not doing it will frustrate developers who are used to the behavior in VS Code. Seems pretty easy to support.

**Comment by iamnbutler** [comment]
Bumping this! Now that we are open source this feels like an isolated enough issue someone might be able to pick it up. Personally I'd love this to be supported!

**Comment by maxdeviant** [comment]
This is available in [Zed v0.121.0](https://zed.dev/releases/preview/0.121.0).

**Comment by failable** [comment]
@maxdeviant That seems not support outline.
