### ISSUE TITLE
Crash on startup with undefined symbol: '___darwin_check_fd_set_overflow' 

### ISSUE THREAD

**Issue by deontologician** [zed-industries/zed#5325]
**Describe the bug**
When I open up Zed on my mac, it crashes immediately.
I did get a little flash of the editor window, I think I can make out a tab at the top before it disappears.
I tried running it from the terminal, but there wasn't anything logged

**Environment:**
Zed 0.42.0 – /Applications/Zed.app \nmacOS 10.14.6 \narchitecture x86_64

**Files**
[crash_dump.txt](https://github.com/zed-industries/feedback/files/9023543/crash_dump.txt)
[Zed.log](https://github.com/zed-industries/feedback/files/9023521/Zed.log)
The last line in the file is probably from the time I tried running it from the terminal.

**Comment by ConradIrwin** [comment]
Closing this as it hasn't appeared in our crash logging since we started logging. Please do reopen if it recurs.
