### ISSUE TITLE
Syntax highlighting improvements

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5329]
Bundling a few syntax highlighting issues up into one meta issue:

- https://github.com/zed-industries/zed/issues/5481
- https://github.com/zed-industries/zed/issues/5330
- https://github.com/zed-industries/zed/issues/5432
- https://github.com/zed-industries/zed/issues/5239
- https://github.com/zed-industries/zed/issues/5266
- https://github.com/zed-industries/zed/issues/5744
- https://github.com/zed-industries/zed/issues/5491 (? Maybe this doesn't belong here)

**Comment by Moshyfawn** [comment]
Ay! The last item on the list has just been merged, so this 2yo meta issue is closed 😊
