### ISSUE TITLE
Syntax highlighting in editor is inconsistent

### ISSUE THREAD

**Issue by undersquire** [zed-industries/zed#5330]
**Describe the bug**
Some parts of my code are being highlighted "incorrectly" (looking at how other parts are being highlighted). There might be other inconsistencies that I missed, and if I run into any more later on I will add them to this issue. Here is a couple of examples:

1. C++ Struct/Class Fields & Method Identifiers

<img width="276" alt="image" src="https://user-images.githubusercontent.com/55647897/176542689-436de74a-eae6-4e05-b30d-47aa97814a9b.png">

As you can see, the class field name `some_field` is highlighted the same color as keywords and the `double` type. This makes it harder to read since it's the same color. And also the method `some_method` name is highlighted the same as keywords/data types which also makes it inconsistent, as functions outside of a class/struct are highlighted white (in the cave_dark theme).

2. C++ weird macro parameter highlighting

<img width="466" alt="image" src="https://user-images.githubusercontent.com/55647897/176543755-67ab63c4-b594-47b0-a5b7-4037b447c885.png">

As you can see, inside the first usage of `sizeof`, the parameter `array` is highlighted the same as custom class data types (aqua color), but when I use an actual defined data type (class Test), it highlights `Test` white, the color that normal variables are highlighted. Instead, I expected it to be the opposite, where `sizeof(array)` "array" is highlighted white, and `sizeof(Test)` "Test" is highlighted the aqua color.

3. Rust Struct Members

<img width="240" alt="image" src="https://user-images.githubusercontent.com/55647897/176544408-4292fb93-0b26-4ab4-a380-a015cab3ccb8.png">

Same problem that the C++ highlighting had, where struct members are highlighted the same as keywords.

4. Rust Enum members

<img width="261" alt="image" src="https://user-images.githubusercontent.com/55647897/176544594-8e6df4fc-afcd-4370-b222-d278cdf19ed1.png">

This one is less of an issue, and I am not bothered by it. However, I think it would be nicer if enum members were highlighted with a unique color so they stand out more, rather than the same color as keywords.

5. Inconsistency between languages (Rust, C++ for example)

<img width="344" alt="image" src="https://user-images.githubusercontent.com/55647897/176544869-4da96e06-d8c9-4dc1-9419-daae47164ecb.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/55647897/176544941-01bf908f-cf17-4b5d-b767-cd7962d7b106.png">

The main inconsistency between these two is the coloring of the function names. In rust, it's the orange/brown color, but in C++, it's white. I would *expect* both languages to have function names highlighted the same, however it isn't a huge deal. I've noticed that this is an issue with almost every IDE/editor I've used, and I'm not really sure what causes it.

Another small inconsistency here is the operator `+`, which is orange/brown in C++ but white in Rust.

When it comes to the data types, I am not really bothered by the fact that C++ data types (`int` in this example) are highlighted the same as keywords, vs in Rust they are highlighted the aqua color like custom struct/class types etc, but this could be considered an inconsistency between languages.

**To reproduce**
This happens using any theme, just different colors. This might be an issue with Zed's built-in themes or maybe tree-sitter grammar itself? Either way, this isn't a super urgent issue, just something that I think should be considered to make things more consistent.

**Environment:**
Zed 0.42.0 – /Applications/Zed.app
macOS 12.4
architecture arm64

**Comment by Moshyfawn** [comment]
I believe most of the issues raised have been fixed through multiple iterations since this issue was created. I'm going to close it, but be sure to follow up with a separate issue / find already existing ones about any specific point that was missed.
