### ISSUE TITLE
Arrow keys + modifiers do not work correctly

### ISSUE THREAD

**Issue by ianthehenry** [zed-industries/zed#5332]
**Describe the bug**
Arrow keys + modifier behavior does not match native macOS controls.

**To reproduce**

Hold left or right to scroll. While still holding one of them, start holding down alt or shift. Cursor will stop cold.

**Expected behavior**
Cursor continues to move, either between words or while moving the selection.

**Environment:**
Copy & paste output of this command:
```
Zed 0.42.0 – /Applications/Zed.app
macOS 12.3.1
architecture x86_64
```

**Comment by notpeter** [comment]
I am no longer able to reproduce this and I believe sometime in the past 2 years this has been fixed.  If you are still seeing this issue, please feel free to comment and I'm happy to reopen.  Otherwise thanks for reporting!
