### ISSUE TITLE
Add option for disabling tab row

### ISSUE THREAD

**Issue by aexvir** [zed-industries/zed#5333]
**Is your feature request related to a problem? Please describe.**
I'm really used to switching between files with the cmd+p shortcut on both vscode and goland, so the tab row is redundant for me and it's just wasting space

**Describe the solution you'd like**
add an option for hiding the tab bar completely
as the breadcrumbs already include the filename there's no need for any other indicator for what file is being used, at least for me

**Describe alternatives you've considered**
no alternatives, is not something that has many choices I think 😅 

**Screenshots**
I'm attaching screenshots of both my vscode and goland windows, where I have tabs hidden
![capture-20220629135045](https://user-images.githubusercontent.com/8055505/176430564-b1362209-4a6d-4c85-8ef0-231185a5b4a8.png)
![capture-20220629135232](https://user-images.githubusercontent.com/8055505/176430554-2aedaa12-357d-4402-9683-cc0338d30016.png)

**Comment by Moshyfawn** [comment]
This is now possible with this configuration:

```json
"tab_bar": {
  "show": false
}
```
