### ISSUE TITLE
Dark theme contrast

### ISSUE THREAD

**Issue by oreqizer** [zed-industries/zed#5334]
The dark theme's blue color, and some other colors, have quite low contrast compared to the background, making them quite challenging to read, especially when outdoors.

Would appreciate better contrast, also in the file explorer on the left 💡 

![image](https://github.com/user-attachments/assets/d9a31041-7aed-412b-8f24-ce967df77362)

**Comment by thedocbwarren** [comment]
Would be great to use the theme and be able to set the background color of the editor to black.  I want One Dark pro and a black editor background.

**Comment by bennetbo** [comment]
@thedocbwarren You should be able to achieve this by using theme overrides, in your settings file you can add something like this:

```json
"experimental.theme_overrides": {
    "editor.background": "#000000"
},
```

**Comment by alexlatif** [comment]
@bennetbo i cannot seem to get these settings to work. is there anyway to do this to the overall theme contrast between font and background?

**Comment by isaac-mcfadyen** [comment]
Just to chime in here: I have somewhat poor vision and the default low contrast actually made Zed unusable for me as I couldn't read the text on the sidebar.

Theme overrides partially fixed this - however it would seem logical to update the core themes to be accessible by default (as things should be with a modern code editor).

**Comment by pavles6** [comment]
If you are looking for an alternative to default One Dark but with enhanced color contrast and better readability, I've recently published a theme that aims to accomplish just that: https://github.com/pavles6/one-dark-darkened
