### ISSUE TITLE
Deleting a file inside zed is inconsistent

### ISSUE THREAD

**Issue by aadibajpai** [zed-industries/zed#5335]
If I click on a file to delete it inside zed, it gets opened. That's ok. Now I press delete and get the confirmation popup. Now, if I confirm deletion, the open tab of the file gets the little blue icon indicating it's been changed.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/27063113/176348848-055c2057-ce04-4599-991a-85eecfd2ff99.png">
But when I try to close it, it asks if I want to save the unsaved edits. I would think that the unsaved edit is effectively the fact that I deleted it, but that actually restores the file. 

I expect the fix is probably just closing the file tab if it's open when it is deleted.

**Comment by Moshyfawn** [comment]
@hez is right: the current behaviour is that described.
