### ISSUE TITLE
Scroll acceleration is not reset when 'hitting' a 'barrier'.

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#5339]
**Describe the bug**

Scrolling up to a barrier (e.g. the top of a file) produces a logical 'collision' that removes scroll momentum. However, Zed does not report this collision, so scroll events continue to be fired after the user reaches the top of a file then jumps back down. Note that this happens in other apps too, Alacritty and VSCode show the same scroll acceleration behavior while Pages and Google Docs do not.

**To reproduce**

0. Use a mouse with scroll acceleration configured
1. Put the cursor below the the screen height 
2. Scroll up to the top quickly and load scroll acceleration (with my laptop, that means scrolling to the top and then continuing to scroll rapidly with two fingers)
3. Type a character so that the buffer jumps to where your cursor is
4. Observe that the scroll events are still being fired and so the buffer immediately scrolls you up

**Expected behavior**

The scroll momentum should be cancelled.

**Screenshots**

https://user-images.githubusercontent.com/2280405/176240510-93733aa0-791c-4451-bfbb-175d240ba639.mov

**Environment:**

Zed 0.41.0 – /Applications/Zed.app
macOS 12.3.1
architecture arm64

**Comment by JosephTLyons** [comment]
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. Let me know if you are able to, @mikayla-maki.
