### ISSUE TITLE
Find all references highlight

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5340]
**Is your feature request related to a problem? Please describe.**
When I do a Find All References action, I sometimes have a hard time spotting the symbol in the excerpts text.  I'll mention that I have dyslexia and that I realize that this is probably more of a personal problem than a real issue.

![SCR-20220628-f9i](https://user-images.githubusercontent.com/19867440/176212711-edb1dd76-f7c2-43e8-bf19-33cd4ee64f3e.jpeg)

**Describe the solution you'd like**
I'm not sure what the best solution is, but I kind of wish there was some sort of highlight, in the same way that using Find In Project highlights the text it finds:

![SCR-20220628-f9m](https://user-images.githubusercontent.com/19867440/176212889-8a9e3948-6783-45c6-a134-6d9cdf8f3370.jpeg)

Maybe there are other instances of multi-buffers that could also highlight their items?

If this doesn't make sense for anyone else, feel free to close this out.

**Comment by Moshyfawn** [comment]
I think this is already a thing, if I understand the request correctly?

<img width="1354" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/228a24df-3a7c-45fd-a301-ccfcc7ea4675">

**Comment by Moshyfawn** [comment]
Let me know if you want this reopened.

**Comment by JosephTLyons** [comment]
I think the highlight is just weak on a bunch of our shipped themes:

<img width="1608" alt="SCR-20240531-otqs" src="https://github.com/zed-industries/zed/assets/19867440/39535b5b-3b01-4236-9230-3a45617ab6ae">

<img width="1564" alt="SCR-20240531-ouik" src="https://github.com/zed-industries/zed/assets/19867440/b874f1f8-b381-4d04-9162-6c4c1412de02">

<img width="1608" alt="SCR-20240531-ouli" src="https://github.com/zed-industries/zed/assets/19867440/872b61da-0672-40bf-9bf0-20ec670b0bce">

Atelier Heath Light looks good:

<img width="1608" alt="SCR-20240531-otis" src="https://github.com/zed-industries/zed/assets/19867440/c3554cd5-638a-4c87-b9c2-6c7eda40a5e2">

**Comment by Moshyfawn** [comment]
I feel like this is mostly #5334 now
