### ISSUE TITLE
Provide crate metadata completions in `Cargo.toml` files

### ISSUE THREAD

**Issue by noib3** [zed-industries/zed#5342]
**Is your feature request related to a problem? Please describe.**

When adding/modifying dependencies in Rust projects I often find myself googling a crate just to check the current version number or the list of available features.

**Describe the solution you'd like**

It'd be cool if Zed provided completions for both the `Cargo.toml` schema (e.g. the available keys under `[package]`, `[lib]`, `[workspace]`, etc) and the metadata associated to individual crates.

That data is [freely accessible](https://crates.io/data-access).

**Comment by Moshyfawn** [comment]
Today, Zed autocompletes key names for `Cargo.toml` entries, as well as dependency-specific keys.

**Comment by JosephTLyons** [comment]
I don't think we offer up crate versions yet, unlike the [`crates`](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates)  plugin.
