### ISSUE TITLE
Flutter/Dart support

### ISSUE THREAD

**Issue by futurepaul** [zed-industries/zed#5343]
**Is your feature request related to a problem? Please describe.**

No syntax highlighting or language server for Flutter.

**Describe the solution you'd like**

Syntax highlighting, `dart format`, go to definition, hover, autocomplete, problems, and suggested fixes (for imports especially!) would be enough for me to do Flutter work from Zed.

LSP info here:
https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md

Stretch goals would be some sort of "snippets" feature (flutter has a lot of boilerplate for class definitions) and a "run" button to give those IDE vibes.

Personally I'm doing Rust + Flutter projects right now, so I don't know if there's anything extra hard about showing problems from two different LSPs at once.

**Comment by KristijanZic** [comment]
As a Flutter developer I can tell you that we really need this. VS Code works well but becomes incredibly slow and resource heavy as soon as you get an hour into your work and have a few more tabs opened. Android Studio is even worse tho.

Dart and Flutter support would be very much appreciated.

**Comment by rumanabwu** [comment]
VS code and Android studio as both resource heavy, so flutter support on this would be great, thanks in advance.

**Comment by itfidele** [comment]
Flutter support would make this awesome Zed IDE the King of IDEs, until then i'm enjoying every frame of this gaming editor

**Comment by M1chlCZ** [comment]
I would want to voice my support for this request. Dart/Flutter on Zed would be great. Until then I can use it for my GO, Rust programming.

**Comment by JacquesKovacs** [comment]
Flutter support would make this the king.

**Comment by PsHohe** [comment]
Flutter support would be awesome.

**Comment by MaherSafadii** [comment]
Yes please, tired of VScodes web experience, especially when the project is large it gets slow and heavy on resources.

**Comment by rodydavis** [comment]
Is it possible to still work with Dart only projects via the LSP?

**Comment by steevedevops** [comment]
Any update about this guys ?

**Comment by imujtaba8488** [comment]
Expressing my support for this. We truly desire it.

**Comment by agent3bood** [comment]
Hello all, would you checkout my branch and test it to point out any issues or improvements you can find.

https://github.com/zed-industries/zed/pull/7220

**Comment by steevedevops** [comment]
@agent3bood i possible to use zed with your improvements with dart ?

**Comment by gaganyadav80** [comment]
Flutter support would be awesome!
And thank you @agent3bood for you contribution to add Dart support.

**Comment by eauw** [comment]
Zed is awesome 🤩 and Flutter support would lift our DX to another level.

**Comment by ebsangam** [comment]
Need Flutter support..

**Comment by realkoc** [comment]
+1 
Flutter support is literally the only thing from keeping me doing the full switch from vscode

**Comment by sabowsla** [comment]
im just here trying to do some autocompletion on vs code completly lagging, help zed team

**Comment by timka-123** [comment]
+1 need flutter, please

**Comment by plooliveira** [comment]
We needs ZED for Flutter.  We no longer have one option for clean, straightforward and fast code editor to make decent work with flutter.

**Comment by ZorinFoss** [comment]
Dart support will ship in Zed 0.124. :ship: :rocket:
https://github.com/zed-industries/zed/pull/7220#issuecomment-1953044960

**Comment by eauw** [comment]
> Dart support will ship in Zed 0.124. 🚢 🚀 [#7220 (comment)](https://github.com/zed-industries/zed/pull/7220#issuecomment-1953044960)

I'm very happy to hear that. But since Dart support doesn't mean Flutter support I may ask what the plans for adding Flutter support are?

**Comment by DavidOrakpo** [comment]
I tried the beta version of the ide to experience Dart. It's an average experience sadly without flutter support built in. Launch configurations are also not adhered to by the IDE. No simple way to spin up emulators or simulators as well. You can ofcourse spin up your application using the Flutter cli commands, but that's just about it. Maybe in a few months it'd be a better experience

**Comment by Reprevise** [comment]
> I tried the beta version of the ide to experience Dart. It's an average experience sadly without flutter support built in. Launch configurations are also not adhered to by the IDE. No simple way to spin up emulators or simulators as well. You can ofcourse spin up your application using the Flutter cli commands, but that's just about it. Maybe in a few months it'd be a better experience 

Agreed, though I think this should be handled by a Flutter plugin/extension instead of being baked into the editor itself.

**Comment by Muzammil-Bit** [comment]
> > I tried the beta version of the ide to experience Dart. It's an average experience sadly without flutter support built in. Launch configurations are also not adhered to by the IDE. No simple way to spin up emulators or simulators as well. You can ofcourse spin up your application using the Flutter cli commands, but that's just about it. Maybe in a few months it'd be a better experience
> 
> Agreed, though I think this should be handled by a Flutter plugin/extension instead of being baked into the editor itself.

Yes, but that would also mean for zed to open up for plugins & extensions.

**Comment by caleb654** [comment]
In the meantime before we have full Flutter support does anyone know a way to trigger hot reload on save when running an app in Zed's terminal?

**Comment by Rujitsuki** [comment]
> In the meantime before we have full Flutter support does anyone know a way to trigger hot reload on save when running an app in Zed's terminal?

currently i use [Dashmon](https://pub.dev/packages/dashmon) together with Zed for hot reload. Works for me fine.

**Comment by bigjjjim** [comment]
Very excited to see this thread, would love to see full flutter support as well! 🔥

**Comment by crefter** [comment]
still waiting flutter support !!!🔥

**Comment by mhmzdev** [comment]
I literally fell in love with the speed and performance of it. VSCode is getting slow on large flutter projects, files literally show errors if we even switch branch and it stays there for a long time.

Awaiting on this, downloaded Zed 👍🏼

**Comment by moverishere** [comment]
WE NEED FLUTTER SUPPORT!

**Comment by Moshyfawn** [comment]
Please refrain from spamming. Thank you!

**Comment by AfaqAnwar** [comment]
The Dart support is great, just tried it out. Using Copilot it's barely usable with Flutter projects.
Would love auto-complete for Flutter with its widget system. Hoping this gets implemented in the future.

**Comment by JoseDFS** [comment]
Anyone knows if there any way to attach de debugger? ive been working with the devtools on browser setting breakpoints there but i dont know if exists a more easy or comfortable way of debugging flutter with zed

**Comment by agent3bood** [comment]
Zed does not have a debugger.

**Comment by Rodrigolmti** [comment]
Can we re open the issue since we still don't have support for flutter? Dart is indeed a milestone for that but we are not there yet, right?

**Comment by Moshyfawn** [comment]
I don't think this particular issue will be reopened, so as not to prolong feature requests. The Dart support has landed, which triggered the closure of this ticket. Consider +👍ing [the Flutter extension request](zed-industries/extensions#247) instead and moving the conversation over to the other thread, as Flutter won't be supported in the core of the Zed.

**Comment by ctkqiang** [comment]
Hey there! 😊 Just wanted to check in and see if there's any update on Flutter support in Zed. I’ve been really enjoying using Zed for my projects, and having Flutter integration would make it even more amazing! It would be a huge help for those of us working with Flutter to have all the great Zed features available for Flutter development too. Any progress on this, or plans in the pipeline? Thanks so much for your hard work on Zed – it’s an awesome tool!
