### ISSUE TITLE
Opening a large (non-rust) text file with the extension `.rs` causes lag, delays, program freezes, and excessive CPU usage

### ISSUE THREAD

**Issue by imron** [zed-industries/zed#5353]
**Describe the bug**
Opening a non-rust text file that has the `.rs` extension causes issues for zed.

**To Reproduce**
1. Download "[Moby Dick](https://www.gutenberg.org/files/2701/2701-0.txt)" from the Gutenberg Project and save it as `moby.rs`
2. Open `moby.rs` in zed
3. Wait 10-15 seconds for syntax highlighting to kick in
4. Jump to the end of the document
5. Type a long sentence as quickly as you can, e.g. "the quick brown fox jumps over the lazy dog"
6. Note the lag between keypresses and the characters appearing on the screen
7. Scroll up from the bottom of the document and after a few screens start scrolling up and down
8. Note the lag in the scrolling, and also that Zed can occasionally lock up for a few seconds
9. Press Cmd-A to select all the text
10. Paste it 10 times (each paste is an extra ~1MB of text)
11. Close `moby.rs` with Cmd-W (but keep zed open)
12. Note that CPU usage still stays high for a prolonged period of time, despite the file no longer being open

**Expected behavior**
At step 6. there should be no lag betwen keypresses and characters appearing on screen
At step 8. there should be no lag, or locking up in scrolling
At step 12. there should be no excessive CPU use once the file is closed
In general, there should be no excessive CPU use if it's determined that file with a source code extension is actually not a file containing source code (e.g. if it has more than a certain number of errors)

**Environment:**
 - Architecture [Intel]:
 - Mac OS Version: [macOS 12.3.1]:
 - Zed Version [e.g. 0.39.0]:

**Additional context**
Just trying to do unexpected/pathological things to see how well Zed handles edge cases and extremes.

**Comment by notpeter** [comment]
I attempted to reproduce this but was not able.

```
mkdir -p /tmp/moby
cd /tmp/moby
wget https://www.gutenberg.org/files/2701/2701-0.txt
mv 2701-0.txt moby.rs
zed .
```

If you are still able to reproduce or have alternate steps, please comment and I'm happy to reopen.  Thanks for reporting!
