### ISSUE TITLE
Show warning/control codes for bidirectional control characters in text

### ISSUE THREAD

**Issue by imron** [zed-industries/zed#5354]
**Is your feature request related to a problem? Please describe.**
In order to prevent [TrojanSource attacks](https://github.com/nickboucher/trojan-source), Zed should make it clear to the user if unicode bidirectional control characters are used in source code.

**Describe the solution you'd like**
Implement something similar to what GitHub does when it detects code that uses these control characters.  It has a banner explaining the problem (which you can hide) and also allows you to toggle visible display of the control characters, and finally each affected line has a warning symbol next to it.

See for example [here](https://github.com/nickboucher/trojan-source/blob/main/C%2B%2B/commenting-out.cpp).

**Describe alternatives you've considered**
Rust already has a compiler error for this (since 1.56), which is picked up by Rust Analyser in Zed, however other languages may not have similar warnings or errors (or may not have them turned on).

Despite this, it would be nice to make the issue clear to the user when it happens (see for example GitHub's solution to this above).

**Comment by notpeter** [comment]
Although this issue older, I'm going to consolidate under:
- https://github.com/zed-industries/zed/issues/16310

Thanks for reporting this @imron.
Please 👍 that issue and subscribe to track progress.
