### ISSUE TITLE
SCSS support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5356]

**Comment by Orange4Broom** [comment]
Hi, i would like to as if the SCSS support was added, i am on version 0.120.6.

**Comment by gianpaj** [comment]
Is there no way to use CSS language for `.scss` files?

I can't find how to do that on the config docs or Github search
- https://zed.dev/docs/configuring-zed
- https://github.com/search?q=repo%3Azed-industries%2Fzed+extension+overwrite&type=issues

**Comment by WMcKibbin** [comment]
Throwing my voice here as well. I really want to switch to zed but this lack of scss syntax highlighting is stopping me. Almost all the projects I touch have it at work. Checking last years surveys it does appear to me the most popular preprocessor

https://2023.stateofcss.com/en-US/other-tools/#pre_post_processors

Might be worth making this a thing to grab folks like me as users. Granted, im sure there are lots of examples blocking people from trying zed out as a daily driver. 

If I find time I will start attacking some issues. @iamnbutler Would you be willing to file github issues for what you found in your notes on the upstream with the specific examples you produced the errors with? Or even just a link to the docs.

**Comment by samlogan** [comment]
SCSS syntax highlights is the last thing preventing me from switching to Zed too @WMcKibbin. I have put together the following PR to default SCSS to CSS whilst full support is pending, which is being reviewed by the Zed team.

https://github.com/zed-industries/zed/pull/7789

Hopefully, this or full support will be added soon 🙏

**Comment by xfer** [comment]
I have a branch with SCSS support (https://github.com/xfer/zed/tree/feature/scss), but some code is based on nvim-treesitter and I'm not sure about licensing (nvim-treesiter is Apache 2 and Zed is triple licensed).

**Comment by scr2em** [comment]
this and the icons

**Comment by gianpaj** [comment]
Thanks to this PR https://github.com/zed-industries/zed/pull/9290, you can add this to your `settings.json` file 🎉 
```json
"file_types": {
  "CSS": ["scss"]
}
```
From version Zed 0.128.3 https://zed.dev/releases/stable

At least we have a workaround until full SCSS support 🙂

**Comment by bryanbuchanan** [comment]
I don't know anything about tree sitter, but I did stumble across this, is it better than the other grammar? https://github.com/tree-sitter-grammars/tree-sitter-scss

**Comment by ollietreend** [comment]
> I don't know anything about tree sitter, but I did stumble across this, is it better than the other grammar? https://github.com/tree-sitter-grammars/tree-sitter-scss

This looks promising, but I wonder how stable/mature it is as a project given that the repo is only 3 weeks old and has just 3 commits.

**Comment by abejfehr** [comment]
> > I don't know anything about tree sitter, but I did stumble across this, is it better than the other grammar? https://github.com/tree-sitter-grammars/tree-sitter-scss
> 
> This looks promising, but I wonder how stable/mature it is as a project given that the repo is only 3 weeks old and has just 3 commits.

The author's hobby seems to be contributing to tree sitter grammers, so I think that's pretty telling

**Comment by JosephTLyons** [comment]
Since we now have the SCSS extension in our store, I think we can close this issue out.

<img width="1157" alt="SCR-20240501-oefp" src="https://github.com/zed-industries/zed/assets/19867440/e6424754-c1d6-460d-9b2a-5b802b5b0935">

**Comment by marcolaux** [comment]
> Since we now have the SCSS extension in our store, I think we can close this issue out.

Sadly though, auto complete / suggestions don't work with it.

**Comment by jk-propeller** [comment]
> > Since we now have the SCSS extension in our store, I think we can close this issue out.
> 
> Sadly though, auto complete / suggestions don't work with it.

@marcolaux  FYI: This problem ist now fixed. The SCSS extension now provides an language server for completion and suggestions.

**Comment by marcolaux** [comment]
> > > Since we now have the SCSS extension in our store, I think we can close this issue out.
> > 
> > 
> > Sadly though, auto complete / suggestions don't work with it.
> 
> @marcolaux FYI: This problem ist now fixed. The SCSS extension now provides an language server for completion and suggestions.

It doesn't support things like `@include` or SASS / SCSS specific things it seems.

Also no suggestions from previously imported scss files.

**Comment by cseelus** [comment]
Support for SASS (SCSS alternative, indented syntax) is also still missing.

**Comment by DoggyXomaX** [comment]
Are there any updates on the SASS syntax?
I still can't migrate to this IDE due to no SASS support.

**Comment by mrfoggg** [comment]
I agree, SASS support is needed
