### ISSUE TITLE
Validate config files

### ISSUE THREAD

**Issue by noib3** [zed-industries/zed#5358]
**Is your feature request related to a problem? Please describe.**

After reading the docs on the website I quickly wrote this basic `settings.json`:

```json
{
    "format-on-save": true,
    "preferred-line-length": 79,
    "soft-wrap": "preferred_line_length",
    "theme": "rosé-pine-dawn",
    "vim-mode": true,
}
```

but after saving the file none of the configs were applied. Looking at it a little bit closer I remembered that json is particularly anal about trailing commas. Ok, changing `"vim-mode": true,` to `"vim-mode": true` should fix it, right? Nope, still no luck.

After quitting and reopening Zed a few times I checked back the docs to make sure I didn't misspell any settings. Sure enough, all the dashes (`-`) were supposed to be underscores (`_`) :/

**Describe the solution you'd like**

Validating both the JSON syntax and the settings' names and values would definitely be a welcome addition. For example, both `"format-on-save": true` and `"format_on_save": 42` should cause the user to be shown an error message describing the issue.

Just as an example, here's what the Alacritty terminal shows when it tries to load an invalid config file:

<img width="1013" alt="Screen Shot 2022-06-20 at 6 26 51 PM" src="https://user-images.githubusercontent.com/59321248/174651177-924ec74f-8acf-4ded-9939-d31f0c32bb90.png">

Btw, if you're using Serde for the deserialization there's the [serde_path_to_error](https://docs.rs/serde_path_to_error/latest/serde_path_to_error/) crate which gives you the full path of a config option that caused a deserialization error.

**Comment by jadijadi** [comment]
This is working fine now. If no new complains we might be able to close this and reduce our issue count.

![image](https://github.com/zed-industries/zed/assets/1290639/60a30f8f-b531-4b45-a1ee-2a4c58e0b7cd)

**Comment by Moshyfawn** [comment]
I'll close this one. Feel free to object.
