### ISSUE TITLE
Font size will be reset on saving settings.json

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#5359]
**To Reproduce**

1. Increase the font size. 
2. Open settings.json and hit save. 
3. Observe that editor's font size has been reset to whatever the default value is.

**Expected behavior**

I'd expect the font size to persist, considering I didn't change anything related to the font size (my settings.json doesn't contain anything related to the font size to begin with).

**Environment:**
- Architecture: `arm64`
- macOS Version: `12.4 (21F79)`
- Zed Version: `0.39.0`

**Comment by JosephTLyons** [comment]
Closing this out as a duplicate of:

- https://github.com/zed-industries/zed/issues/5380
