### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by clo4** [zed-industries/zed#5361]
**Is your feature request related to a problem? Please describe.**
There's no way to use the Deno language server (`deno lsp`) which means Zed doesn't support most of my personal projects.

**Describe the solution you'd like**
A way to configure the language server that gets used

**Describe alternatives you've considered**
Currently the only alternative is use an editor that supports setting the language server, eg. vim/vscode

**Comment by smorimoto** [comment]
@maxbrunsfeld I think we can close this now.

**Comment by NetOpWibby** [comment]
It'd make more sense to close once the Deno feature is actually in the released app, no?

**Comment by lino-levan** [comment]
Deno's LSP isn't fully integrated yet. Maybe we wait until we hit feature parity (or close) with vscode_deno?

**Comment by Ducky07** [comment]
I'd wait until the feature has properly launched. Can't wait to start having better support for Deno, since I'm using Deno daily for my own projects.

**Comment by maxdeviant** [comment]
This is available in [Zed v0.121.0](https://zed.dev/releases/preview/0.121.0).

**Comment by NetOpWibby** [comment]
<img width="695" alt="SS 2024-01-31 at 3 03 45 PM" src="https://github.com/zed-industries/zed/assets/1288356/20d1cd9b-9957-4db7-908c-2e62394530d9">

I'm still getting red squiggles on that version.

**Comment by rotu** [comment]
@NetOpWibby
> I'm still getting red squiggles on that version.

Deno is off by default.

I had to add `"deno": { "enable": true }` to my [global settings](https://zed.dev/docs/configuring-zed#global-settings). Adding it to the folder-specific settings did not work.

**Comment by NetOpWibby** [comment]
<img width="876" alt="SS 2024-02-01 at 7 23 54 PM" src="https://github.com/zed-industries/zed/assets/1288356/fb95bf7b-6c5c-4fdc-befc-f387feb39f90">

Okay I have that working but now I'm getting these errors for valid code. My `import_map.json` sets up these import paths.

**Comment by rotu** [comment]
> Okay I have that working but now I'm getting these errors for valid code. My `import_map.json` sets up these import paths.

You probably need to [add that to your `deno.json`/`deno.jsonc` file](https://docs.deno.com/runtime/manual/basics/import_maps).

You can either put it right in your `deno.json`:
```jsonc
{
  "imports": { "std/": "https://deno.land/std@0.210.0/" }
}
```
or use a separate import map file:
```jsonc
{
  "importMap": "import_map.json"
}
```

**Comment by igorbrasileiro** [comment]
I downloaded this [pre release](https://github.com/zed-industries/zed/releases/tag/v0.121.1-pre), then set ~/.config/zed/settings.json this:

```json
{
  "theme": "One Dark",
  "vim_mode": true,
  "ui_font_size": 12,
  "buffer_font_size": 12,
  "deno": { "enable": true }
}
```
and refresh the zed, but the lsp didn't started at the LSP logs.

**Comment by rotu** [comment]
@igorbrasileiro your setup works for me. You *do* have to quit and restart Zed after enabling Deno. Or run the "workspace: restart" command. The "editor: restart language server" command does not switch over from the typescript to the deno language server.

Also, in the "debug: language server logs" page, slightly confusingly there's a a dropdown at the top to choose between language servers. Is `deno-language-server` in that dropdown?

**Comment by igorbrasileiro** [comment]
> @igorbrasileiro your setup works for me. You _do_ have to quit and restart Zed after enabling Deno. Or run the "workspace: restart" command. The "editor: restart language server" command does not switch over from the typescript to the deno language server.
> 
> Also, in the "debug: language server logs" page, slightly confusingly there's a a dropdown at the top to choose between language servers. Is `deno-language-server` in that dropdown?

Oh, thank you, yeah, after restar it worked. I thought it didn`t worked, but the delay was the deno lsp timeout

**Comment by nathansobo** [comment]
I’d love to improve this. Anyone @ me if you want to pair on it. Why do we
need a restart?

**Comment by clo4** [comment]
Seems like we can close this issue now - there's probably a lot of low hanging fruit that can be fixed, but Deno support has landed in main. From this point it's going to be more useful to create issues for the individual things that don't work so it's easier to track what needs to get done.

**Comment by JosephTLyons** [comment]
I agree with @clo4, let's close this issue out in favor of new issues for further fixes / enhancements.

**Comment by dahlia** [comment]
It seems that the formatter doesn't use `deno fmt` yet.  For now, I could use `deno fmt` by configuring it like below:

```json
{
  "deno": { "enable": true },
  "format_on_save": "on",
  "formatter": {
    "external": {
      "command": "deno",
      "arguments": ["fmt", "-"]
    }
  }
}

```

**Comment by andreasvirkus** [comment]
For a monorepo setup, is there a way to configure the formatter based on the file paths in the workspace settings?

**Comment by kewp** [comment]
<img width="470" alt="Screenshot 2024-05-03 at 12 35 20" src="https://github.com/zed-industries/zed/assets/396394/c1447fd9-5f1b-4627-a923-1a3d9b40b650">

started to get squilly lines in the latest deno version 

<img width="312" alt="Screenshot 2024-05-03 at 12 35 52" src="https://github.com/zed-industries/zed/assets/396394/df52fd17-f116-49dd-9e83-8fe62b4cdce1">

this is in the stock-standard tutorial project for fresh

**Comment by igorbrasileiro** [comment]
> <img alt="Screenshot 2024-05-03 at 12 35 20" width="470" src="https://private-user-images.githubusercontent.com/396394/327647002-c1447fd9-5f1b-4627-a923-1a3d9b40b650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Mzk2NDcsIm5iZiI6MTcxNDczOTM0NywicGF0aCI6Ii8zOTYzOTQvMzI3NjQ3MDAyLWMxNDQ3ZmQ5LTVmMWItNDYyNy1hOTIzLTFhM2Q5YjQwYjY1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMjI5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGZiNWU2YTM2MmFmMTJkYTdhMThmZjZjZTI1OTQ2Y2Y4NjMyNzdhOTJhOTEzNWFmMDcwYjRlZmM1OGQ5NzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bRu0YhYb-MLYKoejkJnpPwam0JvM1bHShNNolYg2zqQ">
> started to get squilly lines in the latest deno version
> 
> <img alt="Screenshot 2024-05-03 at 12 35 52" width="312" src="https://private-user-images.githubusercontent.com/396394/327647064-df52fd17-f116-49dd-9e83-8fe62b4cdce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Mzk2NDcsIm5iZiI6MTcxNDczOTM0NywicGF0aCI6Ii8zOTYzOTQvMzI3NjQ3MDY0LWRmNTJmZDE3LWYxMTYtNDlkZC05ZTgzLThmZTYyYjRjZGNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMjI5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2VkZDJkYmMxMmZjNjVlNGJjNTFkYjlmZTQ0MzExZWY0MjNiMzljYjMwNDAyMDBkMTUxMzAwNjNiMjhmMzEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.biUsPlFgHXXa3IKSIAiB1-AYPMIYLqzAdSoNwMml5Bw">
> this is in the stock-standard tutorial project for fresh

If you show the diagnostics, the language server that reported is Typescript? I'm facing the same issue and the LS that's reporting is Typescript. The message:
```
typescript: Cannot find module 'deco/deps.ts' or its corresponding type declarations.
```

**Comment by kewp** [comment]
yeah weird @igorbrasileiro not sure why it happened but some people on discord helped me out https://discord.com/channels/684898665143206084/684898665151594506/1235814362388889601

basically you need to install the deno plugin from zed (it's version 0.0.1 ... and only have like 150 installs) and then disable the built-in typescript server by changing your settings:

```
{
  "languages": {
    "TypeScript": {
      "language_servers": ["deno", "!typescript-language-server", "!eslint", "..."]
    },
    "TSX": {
      "language_servers": ["deno", "!typescript-language-server", "!eslint", "..."]
    }
  }
}
```

**Comment by mxdvl** [comment]
Thanks for the tip @kewp – this had worked for a few weeks for me.

In the last few days, however, I’m getting TS errors all over my project 😢 

<img width="487" alt="ts: Cannot find name 'Deno'. (2304)" src="https://github.com/zed-industries/zed/assets/76776/ae694b2b-0932-48fe-b414-7d087734a280">

**Comment by kewp** [comment]
hey @mxdvl yeah I'm also having issues, not with your fix but with monorepos ... I need to be able to tell Zed "please use this language server for this directory", much like @andreasvirkus meantioned ...

**Comment by sachaw** [comment]
I'm having issues when using dependencies from JSR
![image](https://github.com/zed-industries/zed/assets/11172820/458efa55-aed4-416a-ad8a-f359ca79ef36)
As you can see, the Deno plugin is loaded and working, but I cannot get type declarations.
What is interesting is that import suggestions work.

**Comment by sant123** [comment]
> It seems that the formatter doesn't use `deno fmt` yet. For now, I could use `deno fmt` by configuring it like below:
> 
> ```json
> {
>   "deno": { "enable": true },
>   "format_on_save": "on",
>   "formatter": {
>     "external": {
>       "command": "deno",
>       "arguments": ["fmt", "-"]
>     }
>   }
> }
> ```

You can use now:

`"formatter": "language_server"`

So your settings should look like:

```json
{
  "languages": {
    "TypeScript": {
      "language_servers": [
        "deno"
      ]
    }
  },
  "formatter": "language_server"
}
```

**Comment by kewp** [comment]
Nothing is working for me now ...

I don't understand how this all works ... there is an extension for Deno. But how does Zed know which extension to use when? So ... I guess it looks first at the global `settings.json`? And then if there is a `.zed/settings.json` in your project that overrides it?

Ok, and then how does Zed know to use the Deno language server - because of `"deno": { "enabled":true }`?

And how do I check ... which language server Zed is actually using? All I see it `Typescript` at the bottom ...

I've done all the above and ... well I get nothing - no tooltips, no errors ... and I can't see what is happening.

**Comment by sant123** [comment]
This is my config @kewp 

``` json
{
  "languages": {
    "TypeScript": {
      "language_servers": [
        "deno",
        "!vtsls"
      ]
    }
  },
  "formatter": "language_server"
}
```

However I'm getting errors so at least you can see them. Also notice even with errors it "resolves" the dependencies in the deno.json file:

![image](https://github.com/user-attachments/assets/31ab6a80-0ead-495a-9471-1a9e2e198c6b)

**Comment by kewp** [comment]
Weird. Do you not need to say `"deno": { "enabled": true }`? I'm so confused. I tried your configuration, still nothing - no errors or tooltips. I even opened up the language server logs and it looks pretty normal:

```
stderr: Refreshing configuration tree...
stderr: Resolved .npmrc: "/Users/karl/.npmrc"
stderr: Server ready.
stderr: Refreshing configuration tree...
stderr: Resolved .npmrc: "/Users/karl/.npmrc"
```

It says `deno (project) - Server logs`. The tab title is `LSP logs`.

**Comment by kewp** [comment]
One thing that has worked - creating an empty `deno.json` file in the project root. Now the tooltips work even without a `.zed/settings.json` file

**Comment by sant123** [comment]
It is curious, I get intellisense but Zed marking errors yet 
![image](https://github.com/user-attachments/assets/8c272e56-111c-4131-937e-db7364f7a8b2)

**Comment by kewp** [comment]
I'm seeing the same. I think two language servers are running at once. I see both errors and intellisence

**Comment by maxdeviant** [comment]
> I'm seeing the same. I think two language servers are running at once. I see both errors and intellisence

If you open `debug: open language server logs` and then open the dropdown to show the list of active language servers, which ones do you see running?

<img width="299" alt="Screenshot 2024-07-21 at 1 52 29 PM" src="https://github.com/user-attachments/assets/adda21bd-f7f4-4dd3-a8bf-8b857907c877">

**Comment by kewp** [comment]
> > I'm seeing the same. I think two language servers are running at once. I see both errors and intellisence
> 
> If you open `debug: open language server logs` and then open the dropdown to show the list of active language servers, which ones do you see running?
> <img alt="Screenshot 2024-07-21 at 1 52 29 PM" width="299" src="https://private-user-images.githubusercontent.com/1486634/350787155-adda21bd-f7f4-4dd3-a8bf-8b857907c877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1ODUyODAsIm5iZiI6MTcyMTU4NDk4MCwicGF0aCI6Ii8xNDg2NjM0LzM1MDc4NzE1NS1hZGRhMjFiZC1mN2Y0LTRkZDMtYThiZi04Yjg1NzkwN2M4NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMTgwMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdiNTA4NDAyZTFjZTI1MWMwNTU1MWZhZDYwODJkODI5YzM3MGJiYmUwYTI2ZmFmYzc1Yzk5ZjlmMDI2MTczNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R5Ctw72Bqi00dFuPJm5qhgkpFrEotW9CmMCukQuSRMw">
<img width="229" alt="Screenshot 2024-07-21 at 20 03 46" src="https://github.com/user-attachments/assets/c529bb48-737f-4c05-977a-9ffcc5f371b2">

**Comment by maxdeviant** [comment]
> > > I'm seeing the same. I think two language servers are running at once. I see both errors and intellisence
> > 
> > 
> > If you open `debug: open language server logs` and then open the dropdown to show the list of active language servers, which ones do you see running?
> > <img alt="Screenshot 2024-07-21 at 1 52 29 PM" width="299" src="https://private-user-images.githubusercontent.com/1486634/350787155-adda21bd-f7f4-4dd3-a8bf-8b857907c877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1ODUyODAsIm5iZiI6MTcyMTU4NDk4MCwicGF0aCI6Ii8xNDg2NjM0LzM1MDc4NzE1NS1hZGRhMjFiZC1mN2Y0LTRkZDMtYThiZi04Yjg1NzkwN2M4NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMTgwMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdiNTA4NDAyZTFjZTI1MWMwNTU1MWZhZDYwODJkODI5YzM3MGJiYmUwYTI2ZmFmYzc1Yzk5ZjlmMDI2MTczNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R5Ctw72Bqi00dFuPJm5qhgkpFrEotW9CmMCukQuSRMw">
> 
> <img alt="Screenshot 2024-07-21 at 20 03 46" width="229" src="https://private-user-images.githubusercontent.com/396394/350787790-c529bb48-737f-4c05-977a-9ffcc5f371b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1ODU2MzIsIm5iZiI6MTcyMTU4NTMzMiwicGF0aCI6Ii8zOTYzOTQvMzUwNzg3NzkwLWM1MjliYjQ4LTczN2YtNGMwNS05NzdhLTlmZmNjNWYzNzFiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQxODA4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzllMGViODg5YWIzNTUxY2FiOGE2YTQ0MmMzYzc0NmI3YTk2N2UyZDc1YzIxODBlYmE1ZDE5MTk5NTYxZmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UZPO6_Jd5JFtRm1mf75-x9ieWJE2aZ7sr4535mNj8Vc">

So it looks like you have `vtsls` running in addition to Deno.

You'll need to make sure that the `language_servers` setting is configured for any languages in your project that default to using `vtsls` to have them use Deno instead:

```json
{
  "TypeScript": {
    "language_servers": ["deno", "!typescript-language-server", "!vtsls", "..."],
  },
  "TSX": {
    "language_servers": ["deno", "!typescript-language-server", "!vtsls", "..."],
  },
  "JavaScript": {
    "language_servers": ["deno", "!typescript-language-server", "!vtsls", "..."],
  }
}
```

**Comment by kewp** [comment]
Thanks @maxdeviant that has not worked, I just put what you sent into `.zed/settings.json` but it didn't change anything ... I restarted the language server ...

**Comment by sant123** [comment]
It would be nice when Zed detects a deno.json applies that configuration as Visual Studio Code.

**Comment by elyobo** [comment]
Any guidance on how to set up deno for a mixed repo? We have a project using supabase which is generally TypeScript but uses Deno for edge functions.

Getting docs for `zed` added to the [`deno` editor guides](https://docs.deno.com/runtime/manual/getting_started/setup_your_environment/) would generally be a good move too.

**Comment by canadaduane** [comment]
In case it helps someone else:

I had to run `deno cache --reload main.ts` on a [fresh](https://fresh.deno.dev/) project template in order to get the red squigglies to go away (the error, when hovered, said: "deno: uncached or missing remote").

**Comment by cod1r** [comment]
https://zed.dev/docs/languages/deno

maybe these docs can help. they provide settings.

**Comment by kaitpw** [comment]
has anyone tried the dynamic routes (eg. greet/[name].tsx)? the lsp doesn't seem to pick up on these for me, even though it works with everything else.

**Comment by mickeyvip** [comment]
Following this documentation: https://zed.dev/docs/languages/deno,

for me, the following worked:

Open `Zed -> settings -> Open Settings` (`~/.config/.zed/settings.json`) and add:
```json
{
  "lsp": {
    "deno": {
      "settings": {
        "deno": {
          "enable": true
        }
      }
    }
  }
}
```
This will enable Deno LSP for any project.

Open `Zed -> Settings -> Open Project Settings` (`path_to_project/.zed/settings.json`) and add:
```json
{
  "languages": {
    "TypeScript": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ],
      "formatter": "language_server"
    },
    "TSX": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ],
      "formatter": "language_server"
    }
  }
}
``` 
This will make TypeScript resolve things and format via Deno LPS.

For some reason adding the JSON that enables Deno to project specific `settings.json` didn't work, so I moved it to global `settings.json`. 
Probably would work also if added to default `settings.json`.

Hope this helps.

**Comment by harryjwright** [comment]
My story:

- I installed deno with `curl -fsSL https://deno.land/install.sh | sh`.
- I ran `deno jupyter --install` from my project which added the kernel.
- I restarted my computer for the changes to take effect (Ubuntu).
- I started building a project but came across the red squiggles. I installed the deno extension. This did not solve things.
- I created `.zed/settings.json` and placed the second code snippet from @mickeyvip in it.
- I restarted zed.

Result:

No more squiggles.
![fixdeno](https://github.com/user-attachments/assets/13b25fcd-1bb0-443b-98a0-2cfa421ec4dc)

**Comment by igneosaur** [comment]
Just wondering if something else has changed recently? I have followed the instructions on this page https://zed.dev/docs/languages/deno: Deno extension downloaded and included that JSON in my `settings.json`.

I have also tried putting the `lsp` bit in the global settings and a few other combinations. It just looks like there are several (maybe three) language servers running and giving errors.
<img width="463" alt="Screenshot 2024-11-27 at 09 37 22" src="https://github.com/user-attachments/assets/c0ae5cf0-c9fc-465b-9017-73414692ac45">
Is there a new language server or a rename or anything people are aware of?

**Comment by cod1r** [comment]
You need to make sure you only have the deno lsp running and all ts servers stopped

**Comment by igneosaur** [comment]
@cod1r 
>  I have followed the instructions on this page https://zed.dev/docs/languages/deno: Deno extension downloaded and included that JSON in my settings.json.
Is there something else I need to be doing aside from downloading the Deno extention and putting this in `settings.json`?

```
{
  "lsp": {
    "deno": {
      "settings": {
        "deno": {
          "enable": true
        }
      }
    }
  },
  "languages": {
    "TypeScript": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ],
      "formatter": "language_server"
    },
    "TSX": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ],
      "formatter": "language_server"
    }
  }
}
```

I am on Zed 0.162.5.

**Comment by igneosaur** [comment]
As a sanity check. I have removed the Deno extension and removed all the LSP settings. I have now just added this to the `languages` in `settings.json`:

```json
"TypeScript": {
  "language_servers": ["!typescript-language-server", "!vtsls", "!eslint"],
  "formatter": "language_server"
}
```

And the `typescript-language-server` seems to have stopped (there are no `typescript-language-server` logs) but `vtsls` and `eslint` are still logging out and I'm getting errors from `ts` in my `main.ts`. Is something off or am I being stupid?

**Comment by steveadams** [comment]
> My story:
> 
> * I installed deno with `curl -fsSL https://deno.land/install.sh | sh`.
> ...

@mickeyvip Is this still working for you? I'm on:


- Zed 0.166.1
- Zed extension Deno v0.0.2
- deno:
  -  2.1.4 (stable, release, aarch64-apple-darwin)
  - v8 13.0.245.12-rusty
  - typescript 5.6.2

It's partially working for me, but I can't jump to definitions of imports from npm or jsr. It opens a new empty file with the name of the module as the file name. This might be an issue with the Deno extension specifically; I'll dig into it a bit more. I wanted to make a note of this here in case anyone has encountered and resolved this already.

**Comment by igneosaur** [comment]
By the way, my issues above seem to have now been resolved now in version 0.166.1. The negating of other language servers is now working correctly with the above config (found [here](https://zed.dev/docs/languages/deno)). Thanks to the devs!

**Comment by mickeyvip** [comment]
Hi @steveadams,

just tried the latest versions of Zed (`0.166.1`) and Deno (`2.1.4`).

After I copied all the Deno config to `<project_folder>/.zed/settings.json` and reloaded the workspace (`Cmd+Shift+P` and choose `workspace:reload`) - I got Deno support. 
This time I put the `"lsp"` part also inside the project settings file and it worked correctly.

I have added a line `import * as an emoji from "npm:node-emoji";` to my `.ts` file, and the "go to definition" worked well.
![image](https://github.com/user-attachments/assets/19c26d21-aecd-4717-8969-2f5acb84d292)


Then I installed `oak` (`deno add jsr:@oak/oak`) and copied the example from `oak`'s website. Hovering over imported entities from there correctly shows JSDoc. But "go to definition" behaved just like you described - opened a new empty file:

![image](https://github.com/user-attachments/assets/963f1d3a-8bd5-4b11-b53a-bf9853033ba3)

Maybe this is related: https://github.com/zed-industries/zed/issues/10108

**Comment by igorbrasileiro** [comment]
> After I copied all the Deno config to <project_folder>/.zed/settings.json and reloaded the workspace (Cmd+Shift+P and choose workspace:reload) - I got Deno support.

@mickeyvip which config are you talking about? Can you share?

**Comment by mickeyvip** [comment]
@igorbrasileiro 

https://zed.dev/docs/languages/deno

Zed -> Settings -> Open Project Settings (path_to_project/.zed/settings.json)

```
{
  "lsp": {
    "deno": {
      "settings": {
        "deno": {
          "enable": true
        }
      }
    }
  },
  "languages": {
    "TypeScript": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ],
      "formatter": "language_server"
    },
    "TSX": {
      "language_servers": [
        "deno",
        "!typescript-language-server",
        "!vtsls",
        "!eslint"
      ],
      "formatter": "language_server"
    }
  }
}
```

**Comment by igorbrasileiro** [comment]
@mickeyvip by disabling the tsserver it makes tailwindcss language server doesn't work well, that relies on tsserver (as far as i know), don't?

**Comment by devdumpling** [comment]
Is there an official / supported way to automatically toggle on deno for projects that use it (have a `deno.json` or are manually set to use deno in some config file) vs ones that don't?

I work on both and having to comment out the deno bits in my config and restart servers everytime I switch projects is annoying.

**Comment by dandv** [comment]
Does anyone know who the author of the Deno extension is? The extension doesn't have its GitHub URL set:

![Image](https://github.com/user-attachments/assets/909c2e70-363a-4440-96bf-107f51cd8fa0)

And @lino-levan [doesn't seem to have published the repo](https://github.com/lino-levan/astral/issues/141).

**Comment by fourcolors** [comment]
Would be nice to have an MCP configure this kind of stuff...

**Comment by lino-levan** [comment]
I don't actually have any special access to the deno extension. As you pointed out, you can find it at https://github.com/zed-extensions/deno.
