### ISSUE TITLE
Inconsistent line spacing on large files

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5371]
The space between lines starts to become inconsistent after so many lines:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/19867440/169139756-3ecb5e49-47c1-495d-97f7-94e850cce404.png">

[long_file.txt](https://github.com/zed-industries/zed/files/8720238/long_file.txt)

**Comment by osiewicz** [comment]
Heh, we're simply running into float precision limits when doing layout. You love to see it. =)
