### ISSUE TITLE
Deleting closing brace causes cursor to jump

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5374]
The cursor seems to jump to the previous scope's indentation level:

https://user-images.githubusercontent.com/19867440/137953037-b73e4c25-e25b-4912-a376-782c01d38d64.mov

**Comment by Moshyfawn** [comment]
This doesn't seem to be the case anymore, unless there's a specific language you're seeing this in. I'm going to close the issue, but be sure to follow up if this is still the case.

**Comment by JosephTLyons** [comment]
Nice! I either stopped paying attention to the bug or it has been fixed for a long time, because it was totally off my radar.
