### ISSUE TITLE
Certain interactive aspects of the UI in Zed randomly stop working

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5375]
**Describe the bug**
I originally discovered this on my MacBook (trackpad) and was worried that maybe my trackpad was failing, because it was extremely random when it happened.  I decided to try it on my iMac (mouse) and initially couldn't reproduce, but I eventually ran into it.  This seems to affect the draggable dividers between the Project Browser and the editor and between the editor and the collaborator list on the right.  I *feel* life I've witnessed this happen with other elements of the UI, like simply clicking on the editor to move the mouse, but I can't seem to reproduce anything with that.

**To Reproduce**
Repeatedly try dragging one of the dividers mentioned above. 

**Screenshots**
Note that in this video, between each attempt to drag the divider, I'm releasing the mouse button / trackpad and re-engaging it before starting the next one.  Something to note is that it did not happen on the first 5 or 6 tries, where my mouse remained on top of the divider, but on the try where my mouse slid off of the divider, became and pointer, and moved back to the divider, on that try, the issue surfaced.
https://user-images.githubusercontent.com/19867440/173290746-66c5ae87-6552-4176-a884-d14b47273e68.mov

**Environment:**
 - Architecture [Intel, Apple Silicon]: Intel
 - Mac OS Version: [e.g. iOS]: 12.4
 - Zed Version [e.g. 0.6.1]: 0.38.0

**Comment by maxdeviant** [comment]
@JosephTLyons Do you know if this is still reproducible in current versions of Zed?

**Comment by JosephTLyons** [comment]
Thanks for closing this out, this was old and I can't reproduce it in modern GPUI.
