### ISSUE TITLE
Buffer view jumps at unexpected row upon two fingers tap

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/zed#5376]
**Describe the bug**
Sometimes, two fingers tap on an open buffer moves the view to an unexpected row (generally a _lower_ line).

**To Reproduce**
- Open a buffer with many lines
- Position the cursor
- Scroll down
- Tap the mousepad with two fingers

> **Note** If the bug doesn't show after the first tap, reposition the cursor, scroll and tap again

**Expected behavior**
No behaviour

**Screenshots**

https://user-images.githubusercontent.com/8927326/172939277-0c64940c-18d4-4bd8-acd0-b8672bce46aa.mp4

> In the above video, every time that the buffer view jumps I was tapping on the mousepad with two fingers.

**Environment:**
 - Architecture: Apple Silicon
 - Mac OS Version: 12.1
 - Zed Version: 0.37.0

**Additional context**
My mousepad has _tap to click_ disabled.

**Comment by notpeter** [comment]
I attempted to try and reproduce this behavior (with and without tap-to-click; with and without two finger secondary mouse) and was unable to do so using a current version of Zed.

@fdionisi Are you still experiencing this issue?
