### ISSUE TITLE
Ability to expand to more lines in multi-buffer view

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/zed#5377]
**Is your feature request related to a problem? Please describe.**
Project search and multi-buffer editing is a killer feature. Kudos!
But at times when searching for a term in a big/unknown repo, you may want to have more context _around_ the result.

**Describe the solution you'd like**
Similarly as the GitHub PR provides (fig. below), would be cool if the multi-buffer view could allow users to expand lines above and/or below a result. 

**Describe alternatives you've considered**
Perhaps having the ability to open the file in a normal buffer view, but would defeat the amazing multi-buffer experience.

<img width="127" alt="Screenshot 2022-06-09 at 15 09 33" src="https://user-images.githubusercontent.com/8927326/172867461-4c2b8eca-9af6-4cd2-b19f-8e74929394aa.png">

**Comment by maxdeviant** [comment]
Feedback from @erikareads in the Gleam Discord:

> is there a way to expand the number of lines shown in the search view?
> That is, before and after the search result?
> A co-worker uses Zed, and the context we needed was just below the fold on each of the search results because of how the call-sites were prettified.
> Context I could/would add: `ripgrep` separates this into two flags:
`--after-context` which does lines after the matched line
and `--before-context` which does lines before the matched line. 
`--context` is a shorthand for doing both.

**Comment by JosephTLyons** [comment]
This PR adds in the UI and a keybinding to expand the multi-buffer excerpts:

- https://github.com/zed-industries/zed/pull/10300

You can customize the number of lines that get expanded (see the PR). I think we can close this issue out. This does not add in the ability to shrink the excerts, but if the demand for that is high enough for that, we can add that in in a a follow-up.
