### ISSUE TITLE
Format Shorthand Markdown Tables

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/zed#5382]
**Is your feature request related to a problem? Please describe.**
Zed currently doesn't format shorthand markdown tables. Current experience:

<img width="876" alt="CleanShot - 2022-06-07 at 11 44 07@2x" src="https://user-images.githubusercontent.com/1714999/172423953-31b713de-241d-431a-818d-389abb3c885a.png">

**Describe the solution you'd like**
On format, shorthand markdown tables would expand to the correctly spaced version, as this is super tedious to do by hand.

VSCode before format:
<img width="1121" alt="CleanShot - 2022-06-07 at 11 45 24@2x" src="https://user-images.githubusercontent.com/1714999/172424032-9e183aea-99a0-4901-bce4-12c01eb0cf77.png">

VSCode after format:
<img width="980" alt="CleanShot - 2022-06-07 at 11 45 48@2x" src="https://user-images.githubusercontent.com/1714999/172424092-f8450a7e-b598-4670-9e3f-588ff5e3ebf2.png">

**Describe alternatives you've considered**
Right now I just open VSCode to format tables.

**Additional context**
[Github flavored markdown](https://github.github.com/gfm/) has a variety of table variations not in the base markdown spec.

**Comment by buzbohdan** [comment]
@iamnbutler This is what I get on `Zed 0.123.2` and the `One Dark` theme

<img width="798" alt="Screenshot 2024-02-22 at 16 11 08" src="https://github.com/zed-industries/zed/assets/6121977/c00c0cec-25e6-4427-b99a-eaa89c2585b1">

Seems like a problem was resolved at some point. Please confirm this

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/7904 adds prettier formatting to markdown and it seems to reformat such tables based on my experiments.
