### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5395]
🚨 Update: A tracking issue for Linux has been written up here:

- https://github.com/zed-industries/zed/issues/7015

---

A quick note on platform support can be found here:
- https://github.com/zed-industries/zed/issues/5391

**Comment by JosephTLyons** [comment]
A tracking issue for Linux can be found [here](https://github.com/zed-industries/zed/issues/7015).

**Comment by mikayla-maki** [comment]
Completed as of 143.5 :)
