### ISSUE TITLE
Action to "restart" Zed

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5423]
I'm not sure how feasible it is, but having an action that closes Zed and reopens it would be nice.  It could be displayed somehow after an update, so the user wouldn't have to manually close and open Zed, and it could potentially be registered as a Command Palette action, if there would ever be a reason an individual would want to restart Zed.

**Comment by dandv** [comment]
1. For those who land here from a search, the action name is `workspace: reload` (searching in the command palette for "restart" won't find it).
2. [The action omits the `--user-data-dir` CLI param, so custom workspaces won't reload](https://github.com/zed-industries/zed/issues/58490).
