### ISSUE TITLE
Wrap guide

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5433]
I would love to have wrap guide support in Zed.  Some things to consider upfront would be the ability to have multiple wrap guides and maybe the ability to set wrap guides per language.  I imagine for the settings, there could be a global array of values for wrap guides, then language-specific arrays to override.

**Comment by lupodellasleppa** [comment]
hello,
so it is my understanding that Zed doesn't support multiple colored rulers (like VSCode does)? The `"wrap_guides"` object seems to only support an array of integers (the integers being the column at which to display the ruler), while in VSCode it can be an array of objects specifying column and color. Not that it is a matter of life and death but I'm just getting accustomed to Zed and trying to get the hang of it

![Image](https://github.com/user-attachments/assets/9e288331-eaee-4366-9ad8-9f5f11b4aa18)
