### ISSUE TITLE
Inlay Hint Support

### ISSUE THREAD

**Issue by Cupnfish** [zed-industries/zed#5482]
**Is your feature request related to a problem? Please describe.**
It's a lot easier to have this when I'm writing rust code in vscode. And it increases the efficiency of reading the code.

**Describe the solution you'd like**
Something like vscode would be nice: 
![vscode inlay hint](https://user-images.githubusercontent.com/13157904/169626384-4c3fc38c-93c7-4bb3-b2dc-486f6e84b73b.png)

**Describe alternatives you've considered**
[I'm not sure how difficult it would be to implement this, but there are definitions in the lsp documentation.](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint)

**Screenshots**
![inlay hints at the tail end](https://user-images.githubusercontent.com/23398472/124373902-10434480-dcb4-11eb-9649-4a74a9735d16.png)

**Comment by SteveLauC** [comment]
> I have always found these distracting because they can make lines pretty long,

True, then optimization comes to the party, Neovim implemented this feature in the past versions without too much optimization, and for Rust types that have many generic types, it is a disaster. But Clion/RustRover handles it so well that makes me stay with this feature.
