### ISSUE TITLE
An option to put the 'Close tab' button on the left

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/zed#5486]
**Is your feature request related to a problem? Please describe.**

Close tab buttons in macOS are usually on the left of the tab. See: Safari and tabs in Finder.

**Describe the solution you'd like**

VS Code has `"workbench.editor.tabCloseButton": "left",` and Atom had https://atom.io/packages/close-on-left

It'd be great to get this feature in Zed, too. I imagine it'd be relatively simple to do, but not obvious as a feature that some people would want 😅 

**Describe alternatives you've considered**

We could wait until Zed has mature extension support and try to implement it via an extension, like with Atom. But it would be nice to have it built in like Visual Studio.

**Screenshots (side-by-side mockup)**

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/26578100/175612988-8180b3fe-438c-45c7-86a9-04fdc2f17d72.png">

**Comment by drale2k** [comment]
Imo this should be the default for macOS
