### ISSUE TITLE
Cannot type characters '"˜` on the US International keyboard (and others)

### ISSUE THREAD

**Issue by ricardopieper** [zed-industries/zed#5521]
I was recently invited to test Zed, version 0.42.0.

**Describe the bug**

Some characters cannot be typed, specifically '"˜`. My OS is in Brazillian Portuguese, keyboard is Portuguese - Brazillian ABNT2. Instead of typing it, the editor just does nothing, and that popping sound of "invalid action" plays (same sound that plays if you open the terminal and press ESC multiple times).

Some latin characters with diacritics and ç and tilde (like ã) are rendered impossible to type due to this.

Changing the keyboard to English - US International does not solve the problem. 

**To reproduce**
 Try typing any of ``'"`˜``. 

**Expected behavior**
Characters typed as expected.

**Environment:**
macOS 12.4 
architecture arm64

**Logs**

[Zed.log](https://github.com/zed-industries/feedback/files/9021424/Zed.log)

**Comment by zex3prog** [comment]
hi
why not work `<space>` key in Persian keyboard in arch Linux
