### ISSUE TITLE
Support Python virtual environments

### ISSUE THREAD

**Issue by nathansobo** [zed-industries/zed#5524]
Here's a [document on python virtual environments in VS Code](https://code.visualstudio.com/docs/python/environments). When talking about Zed with @willhelmklopp, he pointed out that we need to support this in order to support his workflow. Not sure how common this is for Python development, but I imagine it's pretty importart.

**Comment by chuck-alt-delete** [comment]
I am a new Zed user and am also having an issue trying to get pyright to recognize virtual environments (attached). I found this issue and I just want to add that right now, https://zed.dev/docs/python returns a 404 not found, and the docs are not searchable, so I currently am really restricted in Python development.

![image](https://github.com/zed-industries/zed/assets/87353672/2c2612a6-c6d9-48d7-98d7-dc05aed2b3c5)

**Comment by JosephTLyons** [comment]
> Edit: Sorry I missed this link earlier in the convo: https://github.com/microsoft/pyright/blob/main/docs/configuration.md . I was trying to find out how to do this through the Zed docs, not the pyright docs.
> 
> I am a new Zed user and am also having an issue trying to get pyright to recognize virtual environments (attached). I found this issue and I just want to add that right now, https://zed.dev/docs/python returns a 404 not found, and the docs are not searchable, so I currently am really restricted in Python development.
> 
> ![image](https://private-user-images.githubusercontent.com/87353672/300104497-2c2612a6-c6d9-48d7-98d7-dc05aed2b3c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDg2MDgsIm5iZiI6MTcwNjg0ODMwOCwicGF0aCI6Ii84NzM1MzY3Mi8zMDAxMDQ0OTctMmMyNjEyYTYtYzZkOS00OGQ3LTk4ZDctZGMwNWFlZDJiM2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA0MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZTAyM2Y4OGFjMDc2YmQxMmIyOWJlYWFkOTEyY2Y3NjlhODkyYmU4ZWIwNWViNzZlZjJiMzZjYTE1ZTU2NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rezFUd28IGb1NWV20bmb9obIUnAtCVoPBA7eWO7asuw)

We are in a weird state where our docs are being transitioned and not everything has been moved over. If you haven't already, trying adding a `pyrightconfig.json` file to your project's root:

```json
{
  "venvPath": ".",
  "venv": ".venv"
}
```

**Comment by timptner** [comment]
I'm very confused. When I do not have `pyrightconfig.json` in my project directory pyright does not find my packages installed via pip inside my virtualenv `.venv`. But when I configure pyright by placing `pyrightconfig.json` pyright does find all my installed packages but is no longer able to resolve python standard libraries.

**Comment by pjv** [comment]
@timptner 

If you want to configure pyright globally with your zed settings to look for your python installed in your `.venv`, the configuration in `settings.json` that is working for me looks like this:

````
  "lsp": {
    "pyright": {
      "settings": {
        "python": {
          "pythonPath": ".venv/bin/python"
        }
      }
    },
````

**Comment by timptner** [comment]
> @timptner
> 
> If you want to configure pyright globally with your zed settings to look for your python installed in your `.venv`, the configuration in `settings.json` that is working for me looks like this:
> 
> ```
>   "lsp": {
>     "pyright": {
>       "settings": {
>         "python": {
>           "pythonPath": ".venv/bin/python"
>         }
>       }
>     },
> ```

Does not work at all for me.

**Comment by skhaz** [comment]
It's still not working for me.

I've tried both `pyrightconfig` and `pyproject.toml`:

```toml
[tool.pyright]
strict = ["strec"]
ignore = ["tests"]
venvPath = "."
venv = ".venv"
```

None of these solutions have worked, and I’m sure my virtual environment is functioning correctly because I can import the libraries I've installed in Python.
