### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5525]
**Is your feature request related to a problem? Please describe.**
Something I would enjoy having in Zed would be file icons.

**Describe the solution you'd like**
The easiest route would be to just use the [images that were used for Atom's File Icons plugin](https://github.com/file-icons/icons). The license permits these to be used in commercial software.  A VS Code package was made with this image set as well, but I think VS Code may use a different set of images by default.

Places images could show up:

- File Tree  
- Tabs
- File Searcher
- Anywhere else that displays file names?

**Comment by maxall41** [comment]
Bump

**Comment by jackblackCH** [comment]
I love Zed and I deeply want to ditch VSCode, but I agree that file icons would improve the experience a lot and would make the switch easier.

**Comment by rodrigoherrerai** [comment]
> I love Zed and I deeply want to ditch VSCode, but I agree that file icons would improve the experience a lot and would make the switch easier.

Second this. Colourful file icons and folders really needed

**Comment by alexandre-embie** [comment]
Please add material icon or similar to zed, the current monochrome is very hard to differentiate.

**Comment by ricardocarrola** [comment]
Yep. Agree. The monochrome won't work for visual detection of file types.

**Comment by anton-patrushev** [comment]
What's the status of it? Is there any way to install some custom icons from extensions or somehow else?

**Comment by inoas** [comment]
Colours is what I am looking for. Material icons etc.

**Comment by noahgsolomon** [comment]
Same here. This should be a functionality able to be changed in an extension like vscode allows

**Comment by realitymolder** [comment]
Just support icon themes :) like the support of the themes themselves

**Comment by inoas** [comment]
> Just support icon themes :) like the support of the themes themselves

I agree. It is fine that the default theme is grayscale but some people prefer recognizability over consistent style I suppose and this should be user customizable.
