### ISSUE TITLE
Terminal tab title changes while in other shells

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5539]
**Describe the bug**
The terminal tab's title changes from "Terminal" to the project directory path when in other shells.  I'm in Nushell in the screenshot below and after I run the first command after switching into Nushell, the tab title changes.
**To reproduce**

**Screenshots**
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/19867440/177570759-f590671a-415c-4deb-b8ce-6599fb338d59.png">

**Environment:**
Zed 0.44.1 – /Applications/Zed.app
macOS 12.4
architecture x86_64

**Comment by fdncred** [comment]
Just looking at nushell issues here and saw this one. Nushell sets tab titles through ansi escape sequences. However, this can be disabled by changin nushell's config.nu and setting `shell_integration` to false.
