### ISSUE TITLE
Add option/config to be able to hide tabs

### ISSUE THREAD

**Issue by shekohex** [zed-industries/zed#5548]
**Is your feature request related to a problem? Please describe.**
I one of the people that does want their editor as minimal as possible, de-cluttering the UI is the first thing I do when I try a new Editor. Zed is already pretty minimum at the moment (from the UI point), but I would like to be able to the following:

**Describe the solution you'd like**
A configuration option to be able to:
1. **Hide editor tabs**: they got me really distracted, I always find using cmd+p and type the file name is way faster than using the file-tree/tabs by using the mouse.
**Describe alternatives you've considered**
No option is available to do so.
  
**Screenshots**

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/14620076/177650246-85fac1e3-44a4-46b4-b66f-4d199b1373cc.png">

> As you can see here also from this screenshot, using the file/buffer tabs here is useless like you see opening different mod.rs file does not include the full/relative path for example to make them different.

**Comment by EdricChan03** [comment]
Encountering this too - seems that the issue link's now a 404, is there an updated issue reference?
