### ISSUE TITLE
Some font configurations make zed completely unresponsive.

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/zed#5554]
**Describe the bug**
I set the buffer_font_family to "Iosevka" and Zed becomes completely unresponsive. I get a Mac spinning beach ball cursor, and when I force quit the app I am not able to open it again. I am only able to make it responsive again by changing the font configuration in the settings files from elsewhere, after which it works fine.

**To reproduce**
Set buffer_font_family to "Iosevka".

**Expected behavior**
Either the font changes or nothing happens if it is misconfigured, but it shouldn't become unresponsive.\

**Environment:**
```
Zed 0.45.0 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64
```

[Zed.log](https://github.com/zed-industries/feedback/files/9062247/Zed.log)

**Comment by emirror-de** [comment]
The same problem still occurs for me using Iosevka 33.2.4 in Zed 0.189.5 on a M2 Macbook with MacOS 15.5. It only occurs when using Iosevka, no matter which version or variant. I tried the TTF Webfont, TTC and Nerd Font both standard and fixed variant. Any other font works (I tried mostly Nerd Fonts).

At a random point in time, Zed freezes, takes 100% CPU usage and does not come back so I need to kill it via terminal emulator. As far as I could observe, this happens most likely when scrolling a buffer via touchpad. I checked the log files but only found messages related to `rust-analyzer`.
