### ISSUE TITLE
Built-in settings/keymaps sync feature

### ISSUE THREAD

**Issue by zongUMR** [zed-industries/zed#5566]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think it will be great for zed to add a built-in settings/keymap sync. For sublime text users, we can download a [plugin](https://packagecontrol.io/packages/Sync%20Settings) and use it to sync the settings on the GitHub Gist. I think zed can also do it but with the built-in feature.

**Describe alternatives you've considered**
Upload, sync, and download the settings from the gist so we don't need to manually configure it everywhere.

**Screenshots**
If applicable, add mockups / screenshots to help explain present your vision of the feature.

**Comment by RokeJulianLockhart** [comment]
@zongUMR, I'd mark it as a duplicate of [`issues/5010`](https://github.com/zed-industries/zed/issues/5010#issue-2098794403).
