### ISSUE TITLE
vim-mode switch/move panes using C-w {h,j,k,l}

### ISSUE THREAD

**Issue by HanEmile** [zed-industries/zed#5574]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**
Switching and moving panes in vim mode using the keyboard only.

**Describe the solution you'd like**
So in vim, you can normally switch panes by pressing C-w ("Control + w") and then h, j, k or l to move to that pane. Another thing that is kind of tied to that is moving the panes them selves using C-w + H, J, K or L (so the uppercase versions of the previously described action, swaps out the current pane with the pane you'd move to).

**Describe alternatives you've considered**
Well, you could use the mouse, but if you're already using vim mode, why not use the existing vim motions.  

**Screenshots**
Not applicable

**Comment by etiennelacoursiere** [comment]
Im trying Zed and loving what i see so far! I can navigate my pane like i would mostly do in neovim and tmux with `<c-w> whjkl` but there is one small thing missing. I can navigate to a terminal pane, but can't come back from it. When i am on a terminal pane, `<ctrl-w>` is bind to clearing the input ( i think ). I would love to be able to itterate on my program, navigate with `<c-w> j` to my term., Run the program then `<ctrl-w>k` back up to the code. 

Here a video showing what i mean. 
First im in the left pane, then right, then left again, then down, and then im stuck.

https://github.com/zed-industries/zed/assets/12648647/e75643c4-96ac-4b57-89d1-f22f37297eaa

**Comment by mrnugget** [comment]
@etiennelacoursiere I want the same! I have a branch locally that even makes it work, but it needs to be consistent with the other panels too. Need to put more work into it.

In the meantime: I have this in my `keymap.json`

```json
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-w t": "terminal_panel::ToggleFocus",
      // ...
    }
  },
```

That lets me go back to the previously-focused pane.

**Comment by A-caibird** [comment]
@etiennelacoursiere ,  use 

<img width="340" alt="Image" src="https://github.com/user-attachments/assets/866e2a71-88e2-40cf-a889-aa04a9b83ad1" />

**Comment by uzantome** [comment]
@etiennelacoursiere

the `ToggleFocus` solution didn't do what i was looking for

this in my `keymap.json` works like a charm:
```json
[
  {
    "bindings": {
      "ctrl-w h": "workspace::ActivatePaneLeft",
      "ctrl-w l": "workspace::ActivatePaneRight",
      "ctrl-w k": "workspace::ActivatePaneUp",
      "ctrl-w j": "workspace::ActivatePaneDown"
    }
  }
]
```

**Comment by mrchantey** [comment]
For some reason remapping the keys does nothing for me, whereas the default `ctrl-k shift-left` works fine, running zed 0.179.4 on linux

```json
  {
    "context": "Workspace",
    "bindings": {
      // has no effect
      "ctrl-alt-left": "workspace::SwapPaneLeft",
      "ctrl-alt-right": "workspace::SwapPaneRight"
    }
  },


```

**Comment by ConradIrwin** [comment]
@mrchantey If you use the debug key context view (`cmd-shift-p debug: Key Context View`) you will probably find that the bindings in Editor for MoveToNextSubwordStart and MoveToPrevSubwordEnd are taking precedence. You can fix this by removing the `"context": "Workspace"` or making it `"context": "Workspace || Editor"`

**Comment by mrchantey** [comment]
@ConradIrwin thank you that fixed it, neat tool too :)
