### ISSUE TITLE
Ability to move project panel to the right-hand side

### ISSUE THREAD

**Issue by maraisr** [zed-industries/zed#5582]
Would be nice for the sidebar to be placed on the right hand side of the viewport. Seeing as its toggle-able, be nice for my code pane to not shift right, but rather when toggling to just reduce the space.

Ive uploaded a video of VSCode demonstrating this. Notice how the code stays in tack so i don't loose place mentally, when looking at the pane for example. This would possible be the same for all panes.

https://user-images.githubusercontent.com/599459/178389145-16fea24d-0378-4941-80c6-cc0f6512caa2.mov

**Comment by bhumit070** [comment]
Hey @JosephTLyons  please let me know how to configure it I am on Zed 0.121.7
and unable to find option for that
