### ISSUE TITLE
Zed closes immediately on macOS Mojave (10.14.6) 

### ISSUE THREAD

**Issue by keinander** [zed-industries/zed#5589]
**Describe the bug**
When launching Zed (0.47.1) on a mac which runs macOS Mojave (10.14.6), the app closes immediately after launch with no error message. Cannot see anything that looks like an error in the log file either. Does Zed support Mojave?

**To reproduce**
Download and install Zed on macOS Mojave (10.14.6) and launch it.

**Expected behavior**
That Zed does not close on launch.

**Environment:**
```
Zed 0.47.1 – /Applications/Zed.app 
macOS 10.14.6 
architecture x86_64
```

Only log statement:
```
17:14:47 [INFO] set environment variables from shell:/bin/bash, path:
/Users/[myuser]/Library/Android/sdk/platform-tools:/Users/[myuser]/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/go/bin
```

**Comment by bitsnaps** [comment]
For those looking for the latest working version for macOS v10.14.6 is [v0.29.0](https://github.com/zed-industries/zed/releases/tag/v0.29.0).
