### ISSUE TITLE
Show whitespace/invisibles

### ISSUE THREAD

**Issue by Daeraxa** [zed-industries/zed#5592]
It would be nice if Zed could display whitespace characters/invisibles. 
I find this really useful when editing documentation and reviewing certain types of log files so is often left on.

Atom has settings for showing whitespace characters/invisibles (Editor > Invisibles) where visible types of whitespace can be identified. This is also present in other editors (Notepad++, VSCode).

I like the amount of flexibility provided by Atom to change the character displayed for each whitespace "type" but personally I've never changed it from the default.
If implemented it would be nice to toggle from the command palette rather than setting in the options, again like in Atom `Window: Toggle invisibles`

![image](https://user-images.githubusercontent.com/58074586/179065112-fb3460e6-8dbf-4597-8c75-f5908bb74b96.png)
![image](https://user-images.githubusercontent.com/58074586/179065287-44edbfad-17af-4322-ae88-21832c021c81.png)

**Comment by pshergie** [comment]
the visible whitespaces across all included light themes are way too prominent, could you make it paler or give us an option to edit the color?

**Comment by joseftw** [comment]
It's possible to change the color like this:
```
"experimental.theme_overrides": {
    "editor.invisible": "#777777"
  },
```

**Comment by pshergie** [comment]
> It's possible to change the color like this:
> 
> ```
> "experimental.theme_overrides": {
>     "editor.invisible": "#777777"
>   },
> ```

it works! didn't know about the setting

**Comment by bajtos** [comment]
> It's possible to change the color like this:
> 
> ```
> "experimental.theme_overrides": {
>     "editor.invisible": "#777777"
>   },
> ```

How does this setting interact with dark/light mode and custom theme colours? Instead of configuring the exact colour, have you considered allowing the user to configure the opacity (alpha channel) that will be applied to the theme-specific colour?

**Comment by pshergie** [comment]
> It's possible to change the color like this:
> 
> ```
> "experimental.theme_overrides": {
>     "editor.invisible": "#777777"
>   },
> ```

the problem with the setting is that it works for light themes but looks bad for dark ones

**Comment by VladimirCores** [comment]
How could I change color of the whitespaces dots to less pop?

**Comment by olejorgenb** [comment]
> If implemented it would be nice to **toggle from the command palette** rather than setting in the options

Was this never implemented?

EDIT: I had forgotten that selecting text reveals the whitespace. Which is sufficient to use for my needs. I still think it would be nice to have commands to toggle such settings though. But perhaps behind a generic (chained?) "toggle setting:" command

**Comment by ajbonner** [comment]
I was looking for this feature too - it's really handy especially in makefiles.
