### ISSUE TITLE
Can not insert diacritics

### ISSUE THREAD

**Issue by belcar-s** [zed-industries/zed#5597]
I apologize if there’s already an issue open about this! I couldn’t find it, although zed-industries/zed#5521 seems related. 

**Describe the bug**
I can not add diacritics to any character in the editor using my Spanish keyboard layout. 

**To reproduce**
Press the acute accent key followed by a vowel, like A. Observe that an alert sound is played, and then ‘a’, lacking the diacritical mark, appears. 

**Expected behavior**
á is inserted.

**Environment:**
```
Zed 0.47.1 – /Volumes/Zed/Zed.app 
macOS 12.4 
architecture arm64
```

**Comment by fcolecumberri** [comment]
I am using Linux, Spain's Spanish keyboard (I know Latinamerican and Spain have different layouts), I can't insert ` nor any of áéíóúü
