### ISSUE TITLE
Override language mode

### ISSUE THREAD

**Issue by aiakared** [zed-industries/zed#5608]
**Is your feature request related to a problem? Please describe.**
Allow overriding the language mode for specific file extensions and/or the current file. This would allow for basic support in a limited number of languages that currently aren't supported by default.

**Describe the solution you'd like**
1. An option in the command palette for changing the current language mode.
2. In the `settings.json` an option similar to VS Code's `files.associations` where you can map a file extension to a language, e.g:
```json
{
    "language_overrides": {
        ".vue": "html",
    }
}
```

**Describe alternatives you've considered**
None.

**Screenshots**
N/A

**Comment by oscherler** [comment]
> Hey [@aiakared](https://github.com/aiakared), there's a similar issue for this here https://github.com/zed-industries/feedback/issues/207, …

This issue does not exist anymore.
