### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by aiakared** [zed-industries/zed#5609]
~~Vue has an official language server [here](https://github.com/vuejs/vetur/tree/master/server).~~

Update: it seems like Volar was made into a framework agnostic language framework(?). The official Vue language tools are in [vuejs/language-tools](https://github.com/vuejs/language-tools) with the LSP in [packages/vue-language-server](https://github.com/vuejs/language-tools/tree/master/packages/vue-language-server).

**Comment by beejaz** [comment]
Using Zed 0.122.2 with Vue3 project, I get these errors in my .vue files, indicating it doesnt work at all. Is there any issues with using script setup syntax?

![Skärmavbild 2024-02-15 kl  13 43 17](https://github.com/zed-industries/zed/assets/9569157/216293f5-f17b-4905-8c59-7334a3b5b635)

**Comment by so1ve** [comment]
Have you installed the dependencies?

**Comment by klyuk88** [comment]
Also vue-langauge-server does not work. It starts in logs and does not work in files.  Dependencies are installed.
Do I need to write additional configurations for it or should it work out of the box?

**Comment by epreglej** [comment]
> Also vue-langauge-server does not work. It starts in logs and does not work in files. Dependencies are installed. Do I need to write additional configurations for it or should it work out of the box?
same for me

**Comment by beniaminzagan** [comment]
Inlay hints seems indeed to not be supported by the Vue extension. I've tried so many different setups nothing works. 
Zed Preview 175.3
