### ISSUE TITLE
french-swiss keyboard: comment/uncomment the selected text (shortcut cmd-/) does not work

### ISSUE THREAD

**Issue by rudifa** [zed-industries/zed#5610]
With my **french-swiss** keyboard, comment/uncomment the selected text (shortcut `cmd-/`) does not work in Zed

**Expected behavior**
With this keyboard, it is actually `shift-cmd-7` that toggles comments (in Atom, VSCode, BBEdit, Xcode, ...) using the comment character(s) specific to the programming language

**Describe the bug**
Pressing `shift-cmd-7` opens the app's Help dialog (which is the normal behavior outside of editors)

**Environment:**
```
Zed 0.47.1 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64
```

**Comment by maelp** [comment]
Same issue on french keyboard with latest version, see https://github.com/zed-industries/zed/issues/33907
