### ISSUE TITLE
Eslint/Prettier Support

### ISSUE THREAD

**Issue by jamesdbruner** [zed-industries/zed#5612]
I tried every way I could think of to try to get `format_on_save` to work with my existing eslint/prettier setup but I can't figure out how to make it work. I have a narwhal monorepo with an `eslintrc.json` file at the root and one in every project and have it setup to use prettier as the formatter. 

In vscode and webstorm they pickup the nearest eslintrc and use those rules to format my file on save since I added these lines to my settings.json

```
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
},
```

Here's an example of what that root `eslintrc.json` looks like:
```
{
  "root": true,
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": ["*"]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": [
        "plugin:@nrwl/nx/typescript",
        "plugin:prettier/recommended"
      ],
      "rules": {
        "prettier/prettier": [
          "warn",
          {
            "semi": false,
            "singleQuote": true,
            "tabs": true,
            "useTabs": true,
            "tabWidth": 1,
            "printWidth": 120,
            "endOfLine": "auto"
          }
        ]
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ]
}
```

Can I use the current `format_on_save` setting to replicate how vscode or webstorm work in this regard? I'm probably just being dumb but would really appreciate some clarification or direction. Awesome work so far, and if I can get this figured out Zed will likely be my editor of choice for the foreseeable future.

**Comment by alex-zabyshny** [comment]
Prettier is really slow with execution via `node_modules/.bin/prettier` (in comparison with VSCode). Hopefully this will be fixed by a plugin when they come out.

**Comment by LinusU** [comment]
For anyone looking to get TypeScript formatting via [`dprint`](https://dprint.dev):

```json
{
  "language_overrides": {
    "TypeScript": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "node_modules/.bin/dprint",
          "arguments": [
            "fmt",
            "--stdin",
            "{buffer_path}"
          ]
        }
      }
    }
  }
}
```

**Comment by shinebayar-g** [comment]
It looks like Zed has some support of Prettier? While there is a `prettier` as a formatter option, it didn't work for me.

![image](https://github.com/zed-industries/zed/assets/3091558/2e7323e5-8032-4a5b-b223-49c38b7cb76a)


Until Zed supports Prettier through native extension, external command invocation seems like a great alternative!
However, calling `node` or `npx` is too slow for me. It takes almost 1 second every time I save my file.
I found out that `bun` is a great alternative in this use case! It's almost instant and as fast as native VSCode extension.
```json
  "formatter": {
    "external": {
      "command": "bunx",
      "arguments": ["prettier", "--stdin-filepath", "{buffer_path}", "--write"]
    }
  }
```

**Comment by alex-zabyshny** [comment]
@shinebayar-g Works for me!

<img width="311" alt="Screenshot 2024-02-08 at 23 08 44" src="https://github.com/zed-industries/zed/assets/93944018/d4a366ba-5e49-40a0-9f34-c0bd9e5ce04c">

Feels like instant formatting

**Comment by stabildev** [comment]
please reopen and fix this. 

> Until Zed supports Prettier through native extension, external command invocation seems like a great alternative! However, calling `node` or `npx` is too slow for me. It takes almost 1 second every time I save my file. I found out that `bun` is a great alternative in this use case! It's almost instant and as fast as native VSCode extension.

This is working as a workaround for now

**Comment by TudorEsan** [comment]
this seems to work for me

  "lsp": {
    "typescript-language-server": {
      "initialization_options": {
        "checkOnSave": {
          "command": "eslint_d",
          "arguments": [
            "--stdin",
            "--stdin-filename",
            "{buffer_path}",
            "--fix-to-stdout"
          ]
        }
      }
    }
  }
  
  however warnings are not fixed for example:
  <img width="1212" alt="Screenshot 2024-02-24 at 21 31 36" src="https://github.com/zed-industries/zed/assets/55596191/05ecdcc3-f120-456e-805b-d1f8a02891c0">
  
  only errors are fixed when i save

**Comment by hungify2022** [comment]
@stabildev @shinebayar-g 
Seems Zed supported format by Prettier with this `"formatter": "auto"` config, but your discovered looks so nice.
![CleanShot 2024-02-27 at 09 14 38@2x](https://github.com/zed-industries/zed/assets/126773143/166f56dd-94e2-45f2-b55b-efbe837a48cf)

**Comment by weskor** [comment]
> ```json
> "language_overrides": {
>     "TypeScript": {
>       "format_on_save": "on",
>       "formatter": {
>         "external": {
>           "command": "node_modules/.bin/dprint",
>           "arguments": [
>             "fmt",
>             "--stdin",
>             "{buffer_path}"
>           ]
>         }
>       }
>     }
>   }
> ```

Also wondering this. I tried some different things, but could not get it work in zed. It only removes error.

**Comment by korywka** [comment]
@throrin19 I moved eslint to the new issue #4325 cause this one is closed only with prettier support despite the title 🫠

**Comment by mrnugget** [comment]
Just to follow-up here: I closed #4325 because I merged changes that allow eslint fix-all to work on save. 

Also see this comment on how to "turn off" prettier: https://github.com/zed-industries/zed/issues/4325#issuecomment-1970637174

**Comment by patrykk21** [comment]
I have the same issue with eslint where it doesn't fix imports

**Comment by demeralde** [comment]
I haven't been able to get ESLint working at all with Zed.

Honestly, I don't know why everyone is calling this the "VSCode" killer when it's barely on par with other editors in terms of functionality. It's a cool idea, but I'm not going to use this app until it's finished and not half-baked.

**Comment by Moshyfawn** [comment]
> Honestly, I don't know why everyone is calling this the "VSCode killer" when it's barely on par with other editors in terms of functionality. It's a cool idea, but I'm not going to use this app until it's finished and not half-baked.

Because it's the internet, everyone is overly dramatic and you shouldn't believe everything they write 😉

There are currently 2 channels for Zed: Stable and Preview. Preview gets most of the updates at the moment, but it is a bit unstable as things can change and things are being ironed out. A bit of patience and potential contributions can help speed up the process of Zed "training to be The Killer of VSCode" lol

**Comment by ijsnow** [comment]
I'd like to reiterate my solution above for anyone coming here still. The solution solved `eslint` support, including formatting with `prettier` for me using the [eslint_d](https://www.npmjs.com/package/eslint_d?activeTab=readme) daemon.

```json
{
  "lsp": {
    "typescript-language-server": {
      "initialization_options": {
        "checkOnSave": {
          "command": "eslint_d",
          "arguments": [
            "--stdin",
            "--stdin-filename",
            "{buffer_path}",
            "--fix-to-stdout"
          ]
        }
      }
    }
  }
}
```

**Comment by zzzej** [comment]
> I'd like to reiterate my solution above for anyone coming here still. The solution solved `eslint` support, including formatting with `prettier`, using the [eslint_d](https://www.npmjs.com/package/eslint_d?activeTab=readme) daemon.
> 
> ```json
> {
>   "lsp": {
>     "typescript-language-server": {
>       "initialization_options": {
>         "checkOnSave": {
>           "command": "eslint_d",
>           "arguments": [
>             "--stdin",
>             "--stdin-filename",
>             "{buffer_path}",
>             "--fix-to-stdout"
>           ]
>         }
>       }
>     }
>   }
> }
> ```

Thank you for sharing! How did you manage to make zed "respect" rules in `.eslintrc.json` of the local project?

**Comment by zzzej** [comment]
Update, this worked for me:

```json
{
"languages": {
    "TypeScript": {
      "formatter": {
        "external": {
          "command": "eslint_d",
          "arguments": [
            "--stdin",
            "--stdin-filename",
            "{buffer_path}",
            "--fix-to-stdout"
          ]
        }
      }
    },
    "TSX": {
      "formatter": {
        "external": {
          "command": "eslint_d",
          "arguments": [
            "--stdin",
            "--stdin-filename",
            "{buffer_path}",
            "--fix-to-stdout"
          ]
        }
      },
      "preferred_line_length": 100
    }
}
```

**Comment by mrnugget** [comment]
@demeralde can you expand a bit on this here?

> I haven't been able to get ESLint working at all with Zed.

What have you tried? What's your setup? Do you have any steps to reproduce?

I wish it were as easy as merging one PR and it's fixed for everyone, but sadly it's not. There are a _lot_ of different configurations that people use and VS Code (and its extensions!) have many fallbacks and different combinations that are hard to reproduce from the start. So we have to iterate and improve this bit by bit. 

For others and myself ESLint works: it shows diagnostics, it fixes everything when saved. The video here isn't fake: https://github.com/zed-industries/zed/pull/8496 But that doesn't mean it works with every project yet! So I need all of your help by giving me some information on how to make it work for you :)

**Comment by diegofontenelle** [comment]
For anyone looking for a pure `Eslint` solution, without prettier or `eslint_d`, this did the trick for me:

```json
"languages": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "TypeScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  },
  "formatter": {
    "external": {
      "command": "eslint --fix",
      "arguments": ["fmt", "--stdin", "{buffer_path}"]
    }
  }

**Comment by mrnugget** [comment]
@diegofontenelle that would do the same thing twice, right? What happens when you only use `code_actions_on_format`? What does it say in the language server logs for ESLint? (`debug: open language server logs`)

**Comment by diegofontenelle** [comment]
@mrnugget I tried using both individually, but only combined I got `eslint` to properly format. 

With only the languages configuration I got it to format, but it was overwritten by the LSP formatter. After adding the formatter configuration it stopped being overwritten and worked as expected.

**Comment by korywka** [comment]
@diegofontenelle haven't tried but this solution looks like should work too and do not format twice the same code: https://github.com/zed-industries/zed/issues/8992#issuecomment-1995458959

**Comment by diegofontenelle** [comment]
> @diegofontenelle haven't tried but this solution looks like should work too and do not format twice the same code: [#8992 (comment)](https://github.com/zed-industries/zed/issues/8992#issuecomment-1995458959)

Indeed it does work as well, thanks

**Comment by mrnugget** [comment]
Got it thanks! Yes, we need a way to only format with code actions.

**Comment by dev-abota** [comment]
Is there a way to support **stylelint** formatting on a **vue** file, when saving?

**Comment by mrnugget** [comment]
@dev-abota you can always shell out to a formatter: https://zed.dev/docs/javascript#code-formatting Would that help? Sorry, not super familiar with `stylelint` or `vue`.

**Comment by throrin19** [comment]
I have already problem in latest main zed version. 

Eslint format correctly file but directly after that, prettier launch it as you can see in this capture : 

![Kapture 2024-03-29 at 13 18 18](https://github.com/zed-industries/zed/assets/1394778/47f5c754-d7d9-4918-9f29-5e9dc7c797c5)

In log I can't seend eslint do something but I saw pretier do formatting : 

```
stderr: Resolved config: {}, will format file 'repo/stacks/alerts/tests/handlers/alerts-cleanup-api.test.ts' with options: {"printWidth":80,"tabWidth":4,"plugins":[],"parser":"typescript","filepath":"repo/stacks/alerts/tests/handlers/alerts-cleanup-api.test.ts"}
```

This is my config : 

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
    "features": {
        "copilot": false
    },
    "tab_size": 4,
    "ui_font_size": 16,
    "buffer_font_size": 16,
    "terminal": {
        "font_size": 11
    },
    "languages": {
        "JavaScript": {
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        },
        "TypeScript": {
            "code_actions_on_format": {
                "source.fixAll.eslint": true
            }
        }
    },
    "show_whitespaces": "all",
    "show_wrap_guides": true,
    "show_completion_documentation": true
}
```

But, If I save file twice, the second time only eslint formatting is made 😨 : 

![Kapture 2024-03-29 at 13 22 10](https://github.com/zed-industries/zed/assets/1394778/06874310-3f5a-4207-b95f-353b81882005)

**There's really no way to just say, I don't want to prettier at all, disable it?**

**Comment by joshkent94** [comment]
I have the same issue on the below version:

Zed: v0.128.3 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

It seems prettier is clashing with ESLint, there's a flicker when saving.

In the prettier LSP logs I have:

stderr: Resolved config: {"tabWidth":4,"singleQuote":true,"arrowParens":"always","bracketSpacing":true,"printWidth":120,"jsxBracketSameLine":true,"semi":true,"trailingComma":"none","quoteProps":"consistent"}

and in my settings.json I have:

"languages": {
    "JavaScript": {
        "code_actions_on_format": {
            "source.fixAll.eslint": true
        }
    },
    "TypeScript": {
        "code_actions_on_format": {
            "source.fixAll.eslint": true
        }
    },
    "Vue.js": {
        "code_actions_on_format": {
            "source.fixAll.eslint": true
        }
    }
}

When saving, it seems my ESLint config is applied, but then the prettier config is applied afterwards, leaving me with ESLint errors.

**Comment by mrnugget** [comment]
Yeah, there's no way to only format via code actions. I'll try to add something this week.

**Comment by hungify2022** [comment]
I want to use Zed and VS Code interchangeably because some features in Zed don't exist. How can I configure Zed to get similar results to VS Code?

**Comment by raoulkent** [comment]
@hungify2022 I think you will need to wait quite a bit longer. There are a lot of features present in VSCode that will take some time to develop. And there is a massive number of plugins to VSCode that it is unrealistic to expect the same level of customisability within the near future.

Hang tight and if you want try to contribute?

**Comment by mrnugget** [comment]
Just to record this here: I merged https://github.com/zed-industries/zed/pull/10121 which adds ability to only format via code actions.

**Comment by ai212983** [comment]
In case someone (like me) runs into this problem: as of today, the configuration map key should be "languages", not "languages_override". You can find this in the [Zed docs for JavaScript](https://zed.dev/docs/languages/javascript?highlight=format#code-formatting).

```
{
  "languages": {
    "JavaScript": {
      "formatter": {
        "external": {
          "command": "prettier",
          "arguments": ["--stdin-filepath", "{buffer_path}"]
        }
      }
    }
  }
}
```

**Comment by FlorianWendelborn** [comment]
In my case I had to change this in my `settings.json`:

```diff
-"format_on_save": "on",
+"format_on_save": "language_server",
```

Instantly made it work as expected (together with)

```json
{
	"formatter": {
		"code_actions": {
			"source.fixAll.eslint": true
		}
	}
}
```
