### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/zed#5672]
### Check for existing issues

- [x] Completed

### Language

Svelte

### Tree Sitter parser link

https://github.com/Himujjal/tree-sitter-svelte

### Language server link

https://github.com/sveltejs/language-tools

Specifically: https://github.com/sveltejs/language-tools/tree/master/packages/language-server

**Comment by carsick** [comment]
https://www.youtube.com/watch?v=FtB1FWQ7IcE
