### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by daxartio** [zed-industries/zed#5743]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Add possibility creating snippets for fast adding some code

### Describe the solution you'd like

For example, vscode snippets. It's just json files with snippets

### If applicable, add mockups / screenshots to help present your vision of the feature

`.config/zed/snippets/python.json`

```
// Place your snippets for python here. Each snippet is defined under a snippet name and has a prefix, body and
// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the
// same ids are connected.
```

```json
{
    "Print to console": {
        "prefix": "print",
        "body": [
            "print('$1');",
            "$2"
        ],
        "description": "Print to console"
    }
}
```

**Comment by thekarananand** [comment]
It didn't worked

![Uploading image.png…]()

**Comment by thekarananand** [comment]
It didn't worked

![Screenshot from 2024-07-12 01-38-39](https://github.com/zed-industries/zed/assets/68910143/ec0e3bd6-c576-43ee-8d35-e2f929b10593)

**Comment by rm-arun-kumar** [comment]
@SomeoneToIgnore 


For me, the snippets are shown in the middle of the suggestion list. I want snippets at the top, but I'm unable to find settings configuration for that. Can anyone help me?

**Comment by mrchantey** [comment]
@rm-arun-kumar the setting for this is:
```json
{
  "snippet_sort_order": "top",
}
```
