### ISSUE TITLE
Use zed as `EDITOR` for git

### ISSUE THREAD

**Issue by ruza-net** [zed-industries/zed#5748]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I want to use zed as an `EDITOR`, which is used by e.g. git to edit rebase todos and commit messages.

Zed `cli` can open such a file, but since it spawns a new zed tab and then exits, git doesn't wait for me to edit the todo / commit message.

On the other hand, the program `Zed.app/Contents/MacOs/zed` allows me to edit the file properly, but it doesn't signal to git that the file closed. Hence in this case, git waits indefinitely.

### Expected behavior

Zed should signal that it closed a given file.

I don't know how the file manipulations are implemented in zed differently from other editors, so I can't say what exactly that interaction should look like.

### Environment

Zed 0.59.0 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

1. `git rebase -i ...`
2. Zed opens `git-rebase-todos` in a new window
3. Edits are made and window is closed.
4. git performs the rebase

**Comment by Yevgnen** [comment]
Same issue. I'd like to bring the focus back to the terminal automatically.

**Comment by mabequinho** [comment]
Is this `--wait`  possible on Win? Currently running scoop build.
