### ISSUE TITLE
Don't disable .gitignore'd files defined beyond the first parent directory that contains a git repository

### ISSUE THREAD

**Issue by nfrasser** [zed-industries/zed#5749]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I set up my home directory as a git repository to sync my shell config between machines. I have a .gitignore there which includes my code projects (separate git repos). After setting this up, I noticed that any repo I open Zed has every file greyed out in the sidebar as if it was .gitignore'd. 

Steps to reproduce:

1. Create a git repository in the home directory with a .gitignore file
   ```sh
   cd ~
   git init
   echo "*.txt" > .gitignore
   ```
2. Create a git repo with a single file in the home directory
   ```sh
   mkdir example-repo
   cd example-repo
   git init
   touch example.txt
   ```
3. Open the repo in Zed
   ```
   zed .
   ```

I suspect this was introduced with the fix for zed-industries/zed#5456 

### Expected behavior

I expect `example.txt` file to be available in the sidebar. Instead it is greyed out even though it is not included in the project's .gitignore (but is in the parent directory's). 

This also means I can't use `Cmd+P` to open file patterns ignored in the parent git repository but not the project git repository.

### Environment

Zed 0.59.0 – /Applications/Zed.app 
macOS 12.6 
architecture x86_64

**Comment by hferreiro** [comment]
Can you reopen? The fix at https://github.com/zed-industries/zed/commit/31241f48bef316eacd5c0e874a96357755f12948 was reverte (accidentally I suppose) at https://github.com/zed-industries/zed/commit/c5a195052284fb9a713a705ed877952f80c3077f#diff-32e79711f2f6a38bc75a8affe201ae19ed7fa9104f77ae6420c145a262fa6f53.

**Comment by osiewicz** [comment]
Thanks for tracking that down and yeah, that was unintentionally reverted. I'll post a fix shortly.
