### ISSUE TITLE
Autoclose quotes on strings are broken

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/zed#5772]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I attempt to type a string literal the autoclose quotation gets stuck in front of the cursor and I can only move passed it with a stroke of the right arrow key.

https://user-images.githubusercontent.com/43202406/197623087-994b01da-4707-4778-9ffc-c4438ee9e9c9.mov

### Expected behavior

When I finished typing my string and type the final `"` character, I expect that my cursor simply moves over the autoclose quotation

### Environment

Zed 0.61.0 – /Applications/Zed.app
macOS 12.6
architecture x86_64

**Comment by graphixillusion** [comment]
Is there any way to enable the autoclose feature for the plaintext too? I see that it works only for languages but if you are in plain text mode, autoclose doesn't work. I've tried to put an exception in the settings like:

```
"languages":{
  "Plain Text": {
    "use_autoclose": true
  }
}
```
but it doesn't seems to work
