### ISSUE TITLE
rebranding or the new logo

### ISSUE THREAD

**Issue by yournumberone** [zed-industries/zed#5796]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

what do you think about the rebranding or the new logo? I really like your product, but the association with the conflict in Eastern Europe repels me.

### Describe the solution you'd like

new logo

**Comment by danilkinkin** [comment]
Any updates? It's really hard to use this editor because "Z" symbol associate with like a putin "nazi" regime, and it's morally repulsive (
