### ISSUE TITLE
Unable to remove specific keybindings

### ISSUE THREAD

**Issue by SogoCZE** [zed-industries/zed#5844]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that you cannot remove specific keybindings. If you remove a keybinding from the custom keybinding config, it will fall back to the default one. The problem I have is that in my Czech keyboard layout, I type `{ `with `alt-b` and `}` with `alt-n`, and there are default keybindings for these combinations, so I cannot type `{` in Zed right now.

To solve this, I would suggest either:

1. Allowing to pass an empty string, `false`, or `null` as a keybinding command, so that these keybinds wouldn't block the default OS behavior.
2. Don't fall back to default keybindings.

### Environment

Zed 0.66.0 – /Applications/Zed.app
macOS 13.0
architecture arm64

**Comment by liebkne** [comment]
Does not work for me.

```
[
{
    "context": "Editor && mode == full",
    "bindings": {
      "ctrl-g": null
    }
}
]
```

**Comment by OSuwaidi** [comment]
Similarily, the below does not work either:
```
  {
    "context": "Workspace",
    "bindings": {
      "cmd-r": null
    }
```

**Comment by johan-remarkable** [comment]
Related issue here. In macOS while using a Norwegian keyboard, the default system shortcut to switch between windows within an app is cmd + option + ´. This key combo increases editor font size in default Zed. Strangely, I can't find this binding in Zed's default key bindings. And overriding it with `null` doesn't do anything.

**Comment by chrs-b** [comment]
This issue is not resolved (using v0.190.4) unfortunately @JosephTLyons .

Mapping an existing mapped key to null does not remove the mapping. Instead, the key is still matched, see screenshot.

![Image](https://github.com/user-attachments/assets/8795d7f6-b610-462b-9ad8-ce53436ac95e)

**Comment by Benjamin-van-Heerden** [comment]
Why not just have something like VSCode where you can remove the mapping
e.g.
"cmd-shift-g": "-search::SelectPreviousMatch"

The minus indicating that the mapping should be removed

**Comment by chrs-b** [comment]
I believe the mapping to `null` already indicates (or can indicate) that the mapping should be removed.

The problem is, the mapping is not removed. Instead a mapping to `null` is stored and matched against (see screenshot above).

**Comment by chrs-b** [comment]
@JosephTLyons could you please reopen the issue or link to a replacement?

**Comment by AnPiakhota** [comment]
As was mentioned in https://github.com/zed-industries/zed/issues/7089, it becomes difficult to use Guake and similar drop down terminals that are usually toggled with F12 key. Setting null does not do anything 

```json 
  {
    "context": "Editor",
    "bindings": {
      "f12": null
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "g t d": "editor::GoToDefinition"
    }
  }
```

While in the editor, the key is nonfunctional. More over, it seems no other key combination works, when having it changed on Guake side. It looks like Guake just blocks any key combination. 

Could you please reopen this issue. It really makes the professional coding difficult if choosing Zed as the primary IDE.  

@JosephTLyons
