### ISSUE TITLE
Ensure newline at end of file

### ISSUE THREAD

**Issue by d12bb** [zed-industries/zed#5870]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Files consist of lines, and lines are ended with a newline character. Without a newline character, the last line in a file wouldn't be a complete line. When saving a file, Zed must ensure the file ends with a newline character, as lots of utils rely on this.

### Environment

Zed 0.67.5 – /Applications/Zed.app
macOS 13.1
architecture arm64

**Comment by jstasiak** [comment]
> Hey @d12bb, it isn't super easy to find, but we do have an existing issue for this, bundled with another similar request. Would you mind upvoting that one, since it already has a handful of votes? I'm going to close this one in favor of that one.
> 
> https://github.com/zed-industries/feedback/issues/127

This link appears dead currently.
