### ISSUE TITLE
When I try and call a collaborator it will not work, and for them I show as "busy"

### ISSUE THREAD

**Issue by russelldb** [zed-industries/zed#5880]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I click on their name, nothing happens. The log says:

```
[2023-01-12T10:10:00Z ERROR gpui::executor] RPC request CreateRoom failed - Query Error: error returned from database: duplicate key value violates unique constraint "index_room_participants_on_user_id"
```

### Environment

Zed: 0.68.1 (stable)
OS: macOS 12.6.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/10400444/Zed.log)

**Comment by serge-bedzhyk** [comment]
I'm currently in a block state myself, although all related Issues seem to be closed. See details here: https://github.com/zed-industries/zed/discussions/17276

**Comment by smileart** [comment]
@as-cii can you help me with this? I've been locked from calls for nearly three month already. ☝️
