### ISSUE TITLE
Confirm Quit dialog

### ISSUE THREAD

**Issue by aleksa-stajcic** [zed-industries/zed#5887]
### Check for existing issues

- [X] Completed

### Describe the feature

When using Cmd-Q to quit there is no dialog to confirm if you want to quit. I think it would be a nice feature to have, as someone who constantly misses key bindings.

**Comment by rommyarb** [comment]
Now you can use the quit confirmation dialog by setting "confirm_quit" to true, on your `settings.json`:

```json
{
  "confirm_quit": true
}
```

**Comment by fxmxa** [comment]
> Now you can use the quit confirmation dialog by setting "confirm_quit" to true, on your `settings.json`:
> 
> {
>   "confirm_quit": true
> }

not working

**Comment by rommyarb** [comment]
@fxmxa It's literally on the official doc here: https://zed.dev/docs/configuring-zed#confirm-quit
Could you give me your machine info & zed version? This could be a bug.

**Comment by fxmxa** [comment]
> [@fxmxa](https://github.com/fxmxa) It's literally on the official doc here: https://zed.dev/docs/configuring-zed#confirm-quit Could you give me your machine info & zed version? This could be a bug.

Zed 0.183.11 
macOS 15.4.1 (24E263)

**Comment by enesbala5** [comment]
> Now you can use the quit confirmation dialog by setting "confirm_quit" to true, on your `settings.json`:
> 
> {
>   "confirm_quit": true
> }

Not working for me either on Linux.

Zed nightly 1.3.0
OS: NixOS 25.11.20260225.1267bb4 (Xantusia) x86_64
DE: Hyprland (Wayland)
