### ISSUE TITLE
Zed only restores that last open project directory window upon restart

### ISSUE THREAD

**Issue by johnm** [zed-industries/zed#5897]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed only restores that last open project directory window upon restart.

Open a window to a given project/directory.
Open another window to another project/directory.
Close Zed
Reopen Zed and only the *last* window opened on a project/directory is restored.

Zed supports multiple windows and multiple panes per window and it's fast. So the only thing that makes any sense is to reopen everything that was open when Zed was shutdown. Losing all of those windows setup just so is incredibly annoying.

Note also that this isn't even consistent... If I open a random file or say the various settings files in their own window then those windows will not be restored even if it was active when Zed was shutdown! Ugh

### Environment

Zed: 0.69.2 (stable)
OS: macOS 12.6.2
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by rope-hmg** [comment]
This is something I've noticed too. I've migrated over from Sublime Text and I normally have two, three, more windows open at a time. If I `cmd+q` quite Sublime it'll restore everything. I believe they have a setting for that, but I haven't seen anything in Zed's settings. 

The most annoying time that it happens is with updates. If I click "restart to update" then, as OP said, only the last window is reopened.
