### ISSUE TITLE
Setting to disable ligatures

### ISSUE THREAD

**Issue by boynton** [zed-industries/zed#6000]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently the "!=" sequence in a source file gets rendered as "≠" in a buffer, as well as in the search dialog, etc. I would like to turn off that "feature". Noticed it in both C and Go source files. Is it just not documented, or is this actually hardwired behavior? Would prefer WYSIWYG.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="382" alt="Screenshot 2023-03-15 at 1 27 11 PM" src="https://user-images.githubusercontent.com/372157/225435567-a7a958bf-117a-47ea-bdf4-ceedcf61d200.png">

**Comment by jish** [comment]
This feature isn't working for me.

I have the following setting:

```json
{
  "buffer_font_features": {
    "calt": false
  },
  // ...
}
```

And the following sequence `=>` displays like this:

![Screenshot 2024-03-01 at 15 36 30](https://github.com/zed-industries/zed/assets/1817/eb5ec17e-1563-4510-b0cb-ff7cdee7a0fc)

How do I disable this `=>` conversion?

**Comment by Moshyfawn** [comment]
I think this is tracked in #4313

**Comment by dejlek** [comment]
This does not work for me (with latest Zed).

**Comment by iskrisis** [comment]
Should this work on Linux? Docs says windows and mac. It doesnt work for me on Linux although it does work on mac. 
This is kinda dealbreaker if you dont like ligatures.

**Comment by jansol** [comment]
No, opentype feature configuration is unfortunately not in place on Linux yet.

**Comment by KaKi87** [comment]
Hello,

Is there an issue tracking the ability to disable ligatures on Linux ?

If not, I will open a new one, unless this issue is reopened for Linux.

Thanks

**Comment by dejlek** [comment]
I gave up on this - I switched to `JetBrains Mono NL` (it does not have ligatures) and all is good...

**Comment by KaKi87** [comment]
@JosephTLyons Please reopen this for Linux :pray:

**Comment by gwillen** [comment]
For the record, this seems to work on linux now (and doesn't even seem to require a restart anymore.)

**Comment by ExplodingCabbage** [comment]
Yep, `buffer_font_features` didn't used to work for me on Linux but I checked again after seeing @gwillen's post above and can confirm it does now. Looks like the fix happened back in May. Links:
* Issue: https://github.com/zed-industries/zed/issues/15752
* PR: https://github.com/zed-industries/zed/pull/27808
* Commit on main: https://github.com/zed-industries/zed/commit/2b249f9e68b4a9c8c957940040a500aa9a52ada0

🎉

**Comment by KaKi87** [comment]
Indeed, thanks !

**Comment by cbrunnkvist** [comment]
Zed 1.5.3 on macOS (Tahoe), default font, setting `"calt"`, whatevertheham that means, to `false` fixed it for me. Finally Markdown tables and general ASCII art looks accurate.

(I can't tell if `"liga"` has any effect at all)

**Comment by jansol** [comment]
> Setting `"calt"`, whatevertheham that means, to `false` fixed it for me.
> 
> (I can't tell if `"liga"` has any effect at all)

Both of those are names of "OpenType features", and they are somewhat arbitrary names that each font can make up and assign its own meanings to, so which one(s) you need specifically depends on the font you use. The names "calt" (Contextual ALTernatives) and "liga" (LIGAtures) are two well-documented conventional names for {programming etc ligatures, general ligatures}, but as you've probably found out there is still a lot of variation in the exact interpretations.

A full list of feature names and what exactly they control is nowadays usually provided in the README of a font. Failing that, there are some online analyzers that you can drop a font file onto and they'll show you a list of features and what they do to which glyphs.

**Comment by RPGillespie6** [comment]
I can confirm 
```
  "buffer_font_features": {
    "calt": false,
  },
```
Is working on Debian 13, but _only_ if using `.ZedMono` as the font family. If you try to switch to a system font like `Roboto Mono` (for example), then ligatures return.

**Comment by tryashtar** [comment]
Is there a way to disable ligatures in the breakpoint condition interface?

It appears to use the `buffer_font_family`, but the key in `buffer_font_features` doesn't appear to affect it.

<img width="180" height="87" alt="Image" src="https://github.com/user-attachments/assets/f7bf049b-0c2f-42ba-accc-bc85161e9e80" />
