### ISSUE TITLE
Opening Zed should always create a new window. ⌘N with nothing open should make a new window with a new file. ⌘⌥O should open recent projects with no window open.

### ISSUE THREAD

**Issue by fwrs** [zed-industries/zed#6007]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Steps to reproduce:**
1. Freshly install Zed
2. Open it for the first time
3. Cmd+Q it without opening any projects
4. Open Zed again (any subsequent relaunch yields this)
5. Observe that there's no Zed window, just the menu bar

**Actual result:**
The application starts (there's a dot under the dock icon) but there isn't a window. You have to manually click `File > New Window` for anything to appear.
<img width="388" alt="Screenshot 2023-03-16 at 4 46 13 PM" src="https://user-images.githubusercontent.com/44343874/225636711-f3b62025-1b00-4144-a993-f1b2fb034444.png">

**Expected result**
A Zed window appears.

Side note: this bug is slightly concealed due to the fact that you currently can't close a project. If you have an open project and click the "Remove from Project" context menu item it'll still pop up with the same project rather than an empty window on next relaunch.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by NicoAdrian** [comment]
Hi

I don't think the issue is completed because all the workaround mentionned here don't solve the original problem: When clicking on "Remove from project" and closing the app (with cmd+Q"), openning Zed again still open the project closed previously. Is there anything I can do in settings file to prevent this from happening ?

**Comment by usmanayubsh** [comment]
I can confirm the behaviour reported by @NicoAdrian.

**Comment by Cristianald00** [comment]
This issue is still happening and none of the other solutions worked for me. Included a video as reference:

https://github.com/zed-industries/zed/assets/37743128/2083e5b9-1ae9-40ff-b0d0-58f6e1eab0e1

**Comment by af-1878** [comment]
Can you please add a "create_window_at_startup" type function to the settings?

**Comment by Cristianald00** [comment]
> Can you please add a "create_window_at_startup" type function to the settings?

How can I add that? I have already added the "Open at Login" option

**Comment by juliankoehn** [comment]
i updated to the recent version, and i have either a window. But i realized when i am opening a new window, a new instance is "created" but without a GUI?

<img width="276" alt="image" src="https://github.com/zed-industries/zed/assets/3044061/b4f141d4-915c-41a4-8d6a-5088fcb3b0d8">

<img width="248" alt="image" src="https://github.com/zed-industries/zed/assets/3044061/fa0dcc3f-ce3c-4a2f-a2b6-1525aefcc276">


Navigating to `Window` -> `Zoom` opened up a Window (for all instances)

(Silicon, Sonoma)

**Comment by jay0063** [comment]
It works for me!

**Comment by Zenkylo** [comment]
For me the app was running normally, but was a tiny window off screen. If I did the Mac mission control view thing I could grab it and drag it to a new desktop. 
![image](https://github.com/zed-industries/zed/assets/11342698/44c59ab3-e9b4-472a-aa21-cb5b043856e5)

**Comment by ArbazIrshad** [comment]
Thank you so much @juliankoehn. The zoom fix worked for me too.

**Comment by andreaperizzato** [comment]
I still experience this issue with the latest version `0.147.2` `eb91b716c8f3c94309ed303a16a84ccd8b5f445a`
