### ISSUE TITLE
support todo highlight

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6013]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="523" alt="image" src="https://user-images.githubusercontent.com/45585937/225674300-5d78aa64-cb14-4681-a5c5-5cabf45c5207.png">

**Comment by krstp** [comment]
Is this one implemented? Doesn't seem so. Just tried `json` as well as `python`, none of those recognize those markers.

**Comment by berkus** [comment]
Not completed yet, but the relevant original ticket is #5053. I see you already reaslised that, posting just for continuity :)
