### ISSUE TITLE
CLI: Add option to open file at specific line:column

### ISSUE THREAD

**Issue by porsager** [zed-industries/zed#6026]
### Check for existing issues

- [X] Completed

### Describe the feature

To improve interoperability with other tools it would be great if the zed cli allowed opening a file at a specific line and column. This is implemented in every other editor.

Eg. sublime does it this way:

```
subl someFile.js:42:10
```

Which will open the file and position the cursor at line 42 column 10.

Semi related issues are:
https://github.com/zed-industries/zed/issues/5737
https://github.com/zed-industries/zed/issues/5740

**Comment by binbard** [comment]
Not working in windows
