### ISSUE TITLE
Lint and format files on save

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#6083]
### Check for existing issues

- [X] Completed

### Describe the feature

Files upon save should have an option to be formatted and linted to the tools of choice (installed within current system).

**Comment by ciscodea** [comment]
> Ah... wait. I realized the env ZED runs in shell did not have `black` installed. After `pip install black`, the black formatting works. Thanks all for help! Closing.

how do you do that, i've tried but it does not seem working, i have black installed globally :(

**Comment by ace-express** [comment]
> Thank you to both of you, `-` is what I was looking for, first trying `%` and `$` arguments of course without success 😄
> 
> Nonetheless, I did try `-`, using it two ways, through:
> 
> * `formatter` key with `external` ([link](https://docs.zed.dev/configuration/configuring-zed#formatter))
> * `language_overrides` block, by adding `Python` block within it ([link](https://docs.zed.dev/configuration/configuring-zed#language-overrides))
> 
> Just for the kicks to make sure I tried all the options, I tried to use it as standalone block as well. None of the above options worked 😞 For reference here is the block I used:
> 
> ![black_formatting](https://user-images.githubusercontent.com/4711498/230394979-c2f9ef09-cb35-4208-be12-e08b90cd8d26.png)
> 
> BTW: Per your above comments, good to know `format_on_save` can be used with `external` as well and in general`external` can be used with other keys as well on top of `formatting` 👍
@krstp how to make it only work on python?
