### ISSUE TITLE
A way (eg. ctrl/cmd+click) to follow links in markdown

### ISSUE THREAD

**Issue by yw662** [zed-industries/zed#6084]
### Check for existing issues

- [X] Completed

### Describe the feature

There are often links to another file or directory in the project, or a web page in markdown file. Vscode allow you to follow these links with ctrl+click (and a single click in preview). It will open the file in a new tab, or open the directory in the sidebar, or  open the url in browser.

It would be handy if zed could support the same feature.

**Comment by dan-oak** [comment]
@JosephTLyons , sorry for necro-bump.  but i found this feature-request by looking up why folder link are not being opened when ctrl-clicking in Markdown files or when clicking the links in rendered Markdown previews.

this feature is not completely done.  folder links are not followed.  only files and URLs.
