### ISSUE TITLE
Detect language based on shebang

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#6089]
### Check for existing issues

- [X] Completed

### Describe the feature

Now that we can manually set the language of any buffer, this is not a major issue, but still, I wish Zed was able to detect a file's language based on the [shebag](https://en.wikipedia.org/wiki/Shebang_(Unix)) on the first line. This would be nice for files without an extension.

```
Zed: v0.80.5 (stable)
OS: macOS 13.3.0
Memory: 64 GiB
Architecture: aarch64
```

**Comment by andrewthauer** [comment]
Curious where the list of languages it can detect based on shebang lives and if it can be extended? Looking to add support for `nu`.

**Comment by andrewthauer** [comment]
Figured out this can be done by setting the `first_lint_pattern` in the language extension config https://zed.dev/docs/extensions/languages

**Comment by nixpulvis** [comment]
I use `#!/usr/bin/env ruby` for Ruby and this doesn't seem to pick it up.

**Comment by andrewthauer** [comment]
It's called `language selector: toggle`. I actually looked under syntax first myself.

**Comment by nixpulvis** [comment]
Oh, wild! Ruby isn't included!

I guess I have to figure out how to add it. There doesn't seem to be a simple command to install language packages like in other editors.
