### ISSUE TITLE
Zed won't open

### ISSUE THREAD

**Issue by etep** [zed-industries/zed#6105]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After downloading both Zed 0.80.5 and Zed 0.79.1 (just to be sure, I tried different versions) and installing (opening the .dmg file and dragging to Applications), Zed will not open. I have clicked through from the Applications gui and tried to open using the `zed` binary under `Applications/Zed.app/Contents/MacOS`. In the terminal, I see the following:

```
>RUST_BACKTRACE=full ./zed
thread 'main' panicked at 'could not create config path: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', crates/zed/src/main.rs:283:56
stack backtrace:
   0:        0x106be6bc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
   1:        0x106c054b8 - core::fmt::write::hc60df9bae744c40c
   2:        0x106be0a68 - std::io::Write::write_fmt::h1c4129dfc94f7c33
   3:        0x106be69d8 - std::sys_common::backtrace::print::h34db077f1fa49c76
   4:        0x106be8530 - std::panicking::default_hook::{{closure}}::hff4fe3239c020cef
   5:        0x106be8288 - std::panicking::default_hook::hd2988fbcc86fdc46
   6:        0x106be8b54 - std::panicking::rust_panic_with_hook::h01730ad11d62092c
   7:        0x106be8974 - std::panicking::begin_panic_handler::{{closure}}::h30f454e305d4a708
   8:        0x106be702c - std::sys_common::backtrace::__rust_end_short_backtrace::hb7ff1894d55794a1
   9:        0x106be86d0 - _rust_begin_unwind
  10:        0x106d938c0 - core::panicking::panic_fmt::hf1070b3fc33229fa
  11:        0x106d93bf8 - core::result::unwrap_failed::h334387d5f1f555c1
  12:        0x104add188 - Zed::main::h3ede68c77edf0427
  13:        0x104aef790 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb0c48201b725886f
  14:        0x104ac56e0 - std::rt::lang_start::{{closure}}::h231bd61fbeca8b79
  15:        0x106bdaee0 - std::rt::lang_start_internal::h24d09c16ec322e75
  16:        0x104adf460 - _main
```

### Environment

New Apple M2 mac book pro. Cannot open zed, hence cannot run copy system specs from the command palette.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

n/a

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
>cd ~/Library/Logs/Zed 
cd: no such file or directory: /Users/jps/Library/Logs/Zed
```

**Comment by nelsonuprety1** [comment]
> > Hi @hovsater -
> > Thanks for the reply. Here is what I see from those `ls` commands:
> > ```
> > jps@jps-mbp:~>ls -ld ~/.config
> > drwxr-xr-x  3 root  staff  96 Apr  1 11:58 /Users/jps/.config
> > jps@jps-mbp:~>ls -ld ~/Library
> > drwx------@ 88 jps  staff  2816 Apr 14 10:07 /Users/jps/Library
> > ```
> 
> Thanks for that. It looks like your `.config` folder is owned by root. I have no idea how that happened. Could you please run the following command (you may be prompted to enter your password) and then check if it resolved your issue? 🙂
> 
> ```
> $ sudo chown -R $(whoami):staff ~/.config
> ```

Thank You for helping by providing a detailed explanation. I faced the same issue and your provided solution worked perfectly. Cheers.

**Comment by koenverburg** [comment]
Hi, 

I'm trying to install zed and use it but I'm not able to open zed at all.
With the  `RUST_BACKTRACE=full zed` it just hangs.

Binaries I have tried.
- Latest of the zed.dev download
- Latest preview
- The one brew uses

I'm running a M2 pro from 2023, I will try it on my personal m1 once I'm home.

Any ideas I can try in the meantime?

<img width="1164" alt="image" src="https://github.com/zed-industries/zed/assets/10489237/afdb43f7-843e-428f-9bb8-3b0eece71f1c">

**Comment by hello1101n** [comment]
> Hi,
> 
> I'm trying to install zed and use it but I'm not able to open zed at all. With the `RUST_BACKTRACE=full zed` it just hangs.
> 
> Binaries I have tried.
> 
> * Latest of the zed.dev download
> * Latest preview
> * The one brew uses
> 
> I'm running a M2 pro from 2023, I will try it on my personal m1 once I'm home.
> 
> Any ideas I can try in the meantime?
> 
> <img alt="image" width="1164" src="https://private-user-images.githubusercontent.com/10489237/303355827-afdb43f7-843e-428f-9bb8-3b0eece71f1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjc5MTcsIm5iZiI6MTcxNjIyNzYxNywicGF0aCI6Ii8xMDQ4OTIzNy8zMDMzNTU4MjctYWZkYjQzZjctODQzZS00MjhmLTliYjgtM2IwZWVjZTcxZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE3NTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZmM3OGEyMWU4MTNiNDA4MGQ2ZDA0YjgyNjc3MDUwNGI0OGZhMTY0NTdmOWY5ZjljMzA4ZTFkNmUyYTlmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6yh-xFi93aqfRQ_254_eK-E48EJUccsPWsOrTpPJanc">

Same issue
