### ISSUE TITLE
JS/TS always use absolute import paths

### ISSUE THREAD

**Issue by posthardcode** [zed-industries/zed#6115]
### Check for existing issues

- [X] Completed

### Describe the feature

For JavaScript/TypeScript files, Zed currently automatically adds an import when typing a variable name and pressing tab - which is awesome.

It also seems to respect `tsconfig` and use absolute import paths - but not always. If the module to be imported is at the same level, or a level above, relative paths are used.

Is there a way to force absolute paths to always be used? If not, is this on your roadmap?

Thanks!

**Comment by valtism** [comment]
For posterity, to get this working, you need to provide a configuration like this:

```json
{
  "lsp": {
    "vtsls": {
      "settings": {
        "typescript": {
          "preferences": {
            "importModuleSpecifier": "non-relative"
          }
        }
      }
    }
  }
}
```
