### ISSUE TITLE
Vim commands should repeat if command includes a number

### ISSUE THREAD

**Issue by kurtbuilds** [zed-industries/zed#6129]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim, if I type something like `d2d`, it will delete two lines (where `dd` deletes the current line). This works for arbitrary integers (e.g. `d57d`).

Zed should support this. Right now, the number causes the command to not resolve/execute.

**Comment by ConradIrwin** [comment]
Yup! If you want to work with me to fix this, feel free to pick some time: https://calendly.com/conradirwin/pairing
