### ISSUE TITLE
Vim mode - go to definition triggers visual selection

### ISSUE THREAD

**Issue by OlegGulevskyy** [zed-industries/zed#6135]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When in Vim mode, go to definition triggers visual mode selection. So whenever I end up on the definition, I am in a selection mode all the time.

### Environment

Zed: v0.84.4 (stable)
OS: macOS 13.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mmktomato** [comment]
Seems this happens again? I'm using Zed 0.150.4

**Comment by mmktomato** [comment]
Maybe fixed in Zed 0.151.1 via #16477 . Thank you!
