### ISSUE TITLE
Option to fold in all folders in project panel

### ISSUE THREAD

**Issue by PaulvdDool** [zed-industries/zed#6144]
### Check for existing issues

- [X] Completed

### Problem description
After working for a bit, due to the auto focus in the Project Panel for the file in the active tab, the Project Panel will have multiple folders open potentially several items deep into the project tree. Some of these folders can contain a lot of files. It's easy to loose oversight and it becomes difficult to navigate via the Project Panel.

### Feature description
An option to close all folders on all tree levels in the project panel. This way I, as a user, can start navigating down the tree again form a "clean slate".

### Additional information
WebStorm (and other Jetbrains IDEs) have a caret pointing up to close all folders and a caret pointing down to unfold all folders.

**Comment by bholmesdev** [comment]
@JosephTLyons Ah ha, I hadn't realized the project panel should be in focus to use this command! Not sure how intuitive that actually. Is there a reason that the command palette is context-dependent like this?

**Comment by stalkerg** [comment]
Can we have UI icon for that?

**Comment by kcebil** [comment]
The same icon as the one used in VSCode would be perfect 👌
<img width="219" height="87" alt="Image" src="https://github.com/user-attachments/assets/87064e3a-a866-4e7b-a39a-184d89a6b0ff" />
