### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#6164]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hmm.. after recent updates something changed. The text scrolling is slow compared to any other editor etc. Good comparison vs. sublime which is super snappy compared to current ZED release.

### Environment

Mac M2

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by 7flash** [comment]
This is sometimes noticeable to me on macbook M2 with touchpad, it feels like /staircase/ if it makes sense?

**Comment by mrnugget** [comment]
Hey @7flash! Do you think https://github.com/zed-industries/zed/issues/6427 matches what you're describing?
