### ISSUE TITLE
eslint using `@typescript-eslint/parser` looks for `tsconfig.json` in the wrong directory.

### ISSUE THREAD

**Issue by timfee** [zed-industries/zed#6165]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See https://github.com/timfee/zed-eslint

1. `pnpm create next-app` with default options.
2. change the parser to `@typescript-eslint/parser`, for example: 
```json
{
  "extends": [
    "next/core-web-vitals",
    "plugin:@typescript-eslint/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2021,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    },
    "project": "./tsconfig.json"
  }
}
```
3. observe that Zed reports an eslint error that `/users/timfee/sites/zed-eslint/app/tsconfig.json` cannot be read (it shouldn't be looking in that folder; it should be looking one level up, in the root).

Note: If I add `./test.ts` to the root folder of the project, it doesn't complain. \
Note 2: It tells me `./tailwind.config.js` was included by way of parserOptions, but it isn't.

Also, it seems to be ignoring case (not sure if that's an issue; but on Mac, my `Users` and `Sites` folder have initial caps).

### Environment

Zed: v0.88.6 (stable)
OS: macOS 13.4.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screen Shot 2023-06-01 at 17 52 12](https://github.com/zed-industries/community/assets/3246342/55cc250a-6ae1-43b8-98b8-b897d97c9107)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/11630903/Zed.log)

**Comment by Bjorn-Eric-Abr** [comment]
This still happens for me, even if there is a `tsconfig.json` four levels up.
