### ISSUE TITLE
Zed v0.90.2 displays a bright pink blank screen

### ISSUE THREAD

**Issue by Thorin0ak** [zed-industries/zed#6174]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I updated Zed to the latest version this morning, and now all I get is a bright pink screen. Menus seem functional, but I cannot see the command palette. Only the About popup seems to be working. Opening a previous project opens the same blank pink app.

### Environment

MBP M2 Max with Ventura 13.4. Zed is 0.90.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/community/assets/94575046/c7991090-c108-4547-b3b5-11f74b24da38)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Log output when opening the log file itself:

2023-06-16T04:10:58 [ERROR] oneshot canceled
2023-06-16T04:10:58 [ERROR] oneshot canceled
2023-06-16T04:10:58 [ERROR] oneshot canceled

**Comment by SergeyZh** [comment]
I've got it also right now.
<img width="1020" alt="image" src="https://github.com/zed-industries/zed/assets/249955/150094a2-4110-4178-a8b4-22d62509fd5a">

**Comment by SergeyZh** [comment]
And it was self fixed even without restart of Zed after my lunch. :-)
<img width="1027" alt="image" src="https://github.com/zed-industries/zed/assets/249955/37b28aac-8f2c-40d7-a918-e24cf0af6ca4">
