### ISSUE TITLE
Elixir LS failing to download

### ISSUE THREAD

**Issue by nbernardes** [zed-industries/zed#6179]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening any project on Zed, I always get this error

```
Language server error: Elixir

no asset found matching "elixir-ls.zip"
```

`elixir-ls` works in VSCode, and I'm using `elixir` and `erlang` via `asdf`

```
> elixir -v
Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.5 (compiled with Erlang/OTP 25)

> asdf current
elixir          1.14.5-otp-25
erlang          25.3.2.2
```

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
...
2023-06-20T09:22:56 [INFO] starting language server name:elixir-ls, path:"/Users/bernardes/Developer/elixir/arcada", id:0
2023-06-20T09:22:57 [ERROR] crates/zed/src/languages/elixir.rs:105: no cached binary
2023-06-20T09:22:57 [ERROR] crates/project/src/project.rs:2455: no asset found matching "elixir-ls.zip"
2023-06-20T09:23:18 [ERROR] unexpected item event after pane was dropped
2023-06-20T09:24:21 [ERROR] crates/terminal_view/src/terminal_view.rs:264: view Terminal was dropped
2023-06-20T09:52:30 [ERROR] connection error: error reading rpc message from socket
...
```

**Comment by nicklayb** [comment]
I'm not sure if I'm having the same issue, but `elixir-ls` won't start with message

```
Could not run the elixir language server, `elixir-ls`, because `elixir` was not found.`
```

It's installed through `asdf` so I'm under the impression that Zed does not have the right environment when it tries to download and run the language server, `asdf` installed deps are probably not in the env. I tried to configure the `terminal.shell` setting to use my `zsh` shell with the right `.zshrc` file but that doesn't change anything (The terminal do open with the right shell though)

**Comment by mrnugget** [comment]
@nicklayb the `terminal.shell` here is unrelated. What Zed tries to do on startup is to load the environment in a login shell and set that on itself. Here:

https://github.com/zed-industries/zed/blob/080e25dd4531f402271c9b3fae9f0314cc19b664/crates/zed/src/main.rs#L840

When we then lookup `elixir`, we just use Rust's stdlib to lookup in `$PATH`, which by now should be the one you get when you run `zsh -i -l -c 'elixir'`. 

Where and how is your `asdf` configured?

Can you create a ticket and tag me on it?

(I'm also happy to look at this together, if you want feel free to book some time here: https://calendly.com/thorsten-ball-zed/30min)

**Comment by emr** [comment]
I didn't have this error before but with the new release of elixir-ls (v29), Zed failed to fetch the build file due to the asset in the release is published in a different name convention.

Opened the issue: https://github.com/elixir-lsp/elixir-ls/issues/1225
