### ISSUE TITLE
Command pallette should preserve input or order by most recent commands

### ISSUE THREAD

**Issue by tychedelia** [zed-industries/zed#6210]
### Check for existing issues

- [X] Completed

### Describe the feature

As a user, I'm exceptionally lazy, and want to format a bunch of files one by one, but I've forgotten the keybinding for format and refuse to learn it. I open a file, fuzzy search "format" and hit enter. However, when I click on a new file to format and open the command palette, I have to type "format" all over again, which is hard because I'm lazy. Ideally, the command palette would preserve the most recently entered text, so I can just spam it + enter on a bunch of different files. An alternative would be to include recent actions that could be navigated by arrow keys. See IntelliJ for prior art.

**Comment by hferreiro** [comment]
This is not working as of today. Can you reopen?

**Comment by Ornataweaver** [comment]
What is the command for preserving input in settings.json? Is it in settings.json?
Dear @osiewicz, are you sure it was implemented? I couldn't find it anywhere in settings.json.
Thank you so much.

If this isn't implemented yet, please consider these:
```json
  // This preserves the last command palette's input, in vscode:
  "workbench.commandPalette.preserveInput": true,
```
You can also put it in the command palette settings.
```json
  // Command palette settings:
  "command_palette": {
    // Preserve the last input in the command palette when you reopen the palette.
    "preserve_input": true
  },
```

**Comment by osiewicz** [comment]
@Ornataweaver 
I implemented this feature (https://github.com/zed-industries/zed/pull/2954).
It is not gated behind any settings, though we only use hit count ordering when there's no query in the command palette.

**Comment by Ornataweaver** [comment]
@osiewicz, thanks for being so responsive.
Then this solves ordering the commands by the most recent.
What I'd like to experience is keeping the text, e.g. "settings", so when I reopen the palette, I have other "settings" options to try.
Do you recommend that I open a new issue, or do you recommend reopening this issue? 🙏🏻

**Comment by osiewicz** [comment]
Please open a new issue. It should be relatively straightforward

**Comment by butvinm** [comment]
@osiewicz Could you please help me clarify my understanding of the feature you implemented? What I was expecting from the title "order by most recent commands" is that commands I have used recently would be at the top of the command panel when I open it again, but currently I do not see such behavior. In the screencast, I open a new Zed session, search for the "open settings" command and execute it. Then I open the command panel again and expect to see that command at the top, but it isn't there. It was the only command I have used during this session, I have executed it a few times, so I expect it to be at the top. What am I doing or understanding wrong?

https://github.com/user-attachments/assets/f0807ffa-fc67-4ff1-91e0-490c821cd8c2

**Comment by stepankuzmin** [comment]
@butvinm, unfortunately, this is not implemented yet, i.e., recent commands are not preserved when you start typing in the command palette

**Comment by ClaPalo** [comment]
Not sure if this is something obvious, but for me it wasn't so sharing it here for future viewers.
When opening the command palette, if you click arrow_up the palette will start iterating through the most recent commands in order

**Comment by stepankuzmin** [comment]
@ClaPalo this is nice, however the recent commands are still not preserved when you start typing, so the issue is still there.
