### ISSUE TITLE
Remote development via SSH

### ISSUE THREAD

**Issue by ibrahim-koz** [zed-industries/zed#6222]
### Check for existing issues

- [X] Completed

### Describe the feature

Remote development via SSH including development containers.

### If applicable, add mockups / screenshots to help present your vision of the feature

You can look at VsCode for reference.

**Comment by tv42** [comment]
> Duplicates https://github.com/zed-industries/zed/issues/5347

Not really -- you guys have chosen to interpret that issue as "remote development with Zed SaaS as a middleman", which is very different.

**Comment by JosephTLyons** [comment]
> > Duplicates #5347
> 
> Not really -- you guys have chosen to interpret that issue as "remote development with Zed SaaS as a middleman", which is very different.
> 
> _And_ that issue is locked, so I can't point that out in that issue either.

Is it the fact that the original implementation here did not include SSH? We have that now:

<img width="545" alt="SCR-20240528-tbnj" src="https://github.com/zed-industries/zed/assets/19867440/5dc67c84-86a9-4a4f-b3cc-addfbeb5fa13">
