### ISSUE TITLE
In Find, "Select Previous/Next Match" with enter key is broken

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#6228]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I hit enter to "Select Next Match", focus goes from the search field into the editor area, so subsequent enters won't do search but inputs newlines in the editor. And shift-enter clears the search field instead of performing "Select Previous Match".

### Environment

Zed: v0.96.1 (preview)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by sebastiansandqvist** [comment]
@JosephTLyons I'm using v0.125.3 and still face this issue (Vim mode enabled + Sublime keybindings). I'm able to get around it by using the `n`/`N` vim commands, but would definitely prefer to be able to be able to use enter to cycle through search matches.

**Comment by Moshyfawn** [comment]
I could be wrong, but it seems to me that this is intentional, since `n` / `N` is the way you cycle through the matches, isn't it?

**Comment by sebastiansandqvist** [comment]
Ah that's a good point @Moshyfawn. The fact that Zed focuses the editor after making a search when Vim mode is enabled makes sense when `n`/`N` is how you want to cycle through the matches. I'm curious then if there is a way to disable that behavior for more of a hybrid approach, similar to how Sublime Text works when a Vim plugin is enabled, to allow using `Enter`/`Shift + Enter` to cycle matches instead.

**Comment by RolandStolz** [comment]
I'm also still facing the same issue. Does anybody have at least a workaround to enable the Enter / Shift + Enter behavior for search, even when vim is enabled?

**Comment by xlsama** [comment]
I think this is what caused it: 

<img width="2014" height="450" alt="Image" src="https://github.com/user-attachments/assets/5fbee2c2-3770-4a0b-9781-312da64f21ad" />

Add the following configuration to `keymap.json`; this worked for me.

```json
[
  {
    "context": "(BufferSearchBar && !in_replace)",
    "bindings": {
      "enter": null
    }
  },
  {
    "context": "BufferSearchBar",
    "bindings": {
      "enter": "search::SelectNextMatch"
    }
  }
]
```

**Comment by s7dhansh** [comment]
any way to do this in Project Search as well?
