### ISSUE TITLE
Convert variable names to different conventions

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#6235]
### Check for existing issues

* [X] Completed

### Describe the feature

For instance - snake_case to camelCase

**Comment by al6x** [comment]
Would be interesting to have an option to view only in different convention, without actually changing the code.

There's one plugin for VSCode that does that, you define regex and replacement, and the code displayed differently. But it's slow.

**Comment by cgraham149** [comment]
Was wondering if you could add:

- PascalCase
- Pascal_Snake_Case
- path/case
- Train-Case

![image](https://github.com/user-attachments/assets/2d93e318-da9f-41df-b0f7-b243583c24bc)
