### ISSUE TITLE
`CTRL` + `Space` should trigger syntax hints

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#6277]
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode as well as in Jetbrains IDE's there is the ability to show syntax hints if for some reason they do not show up (for example, when you insert a space after `->` in PHP). When you press `CTRL` + `Space` the menu reappears.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/community/assets/45122321/d2898f6c-c64a-4335-9586-4a5556b23fb8)

**Comment by Blankeos** [comment]
I'll just quickly add some info on how this happened to me. 
I never turned this on manually.
 
But I think MacOS definitely did when I ran the "Setup Keyboard" after plugging in an external keyboard, and chose some other setting or something.

**Comment by 8spw** [comment]
I cant really see `Select the previous input source` I'm on macos26 

<img width="624" alt="Image" src="https://github.com/user-attachments/assets/9efae08d-dbd4-41ee-8344-3dbdc14f1ef3" />

**Comment by joaoprocopio** [comment]
@8spw recorded on macos 26.1.  
the screen that you're seeing is the text input screen.

https://github.com/user-attachments/assets/682cbf34-f93d-4e48-9db6-6c0e4d916ec4

**Comment by 8spw** [comment]
> [@8spw](https://github.com/8spw) recorded on macos 26.1. the screen that you're seeing is the text input screen.
> 
>  Screen.Recording.2025-12-10.at.14.55.42.mov

Thanks for reply, I resolved that already
