### ISSUE TITLE
Project manager

### ISSUE THREAD

**Issue by zisra** [zed-industries/zed#6279]
### Check for existing issues

- [X] Completed

### Describe the feature

Can there please be a project manager similar but better than VScode? I want to create a new window but it always shows the new "untitled" file. It would be nice if this project manager saved a list of project directories, automatically removing those that don't exist.

**Comment by sirenkovladd** [comment]
Is it possible to delete folders?
missing recursive search as in https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager (projectManager.git.baseFolders)
I would also like to be able to add tags (as an example of how we will do it in the extension above)
