### ISSUE TITLE
New version doesn't show python's errors

### ISSUE THREAD

**Issue by igor-yusupov** [zed-industries/zed#6308]
### Check for existing issues

- [X] Completed

### Describe the regression

New version doesn't show python's errors at the bottom of the screen. 
In the previous version, it was convenient to see all python code errors at once at the bottom of the screen.

Btw Is it possible to roll back to a previous version?

**Comment by mrnugget** [comment]
Hey @igor-yusupov, can you reproduce this issue with the newest versions? If so, do you have any specific steps to reproduce and/or a sample project that we could use to reproduce?
