### ISSUE TITLE
Add TailwindCSS support to PHP+HTML files

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#6342]
### Check for existing issues

- [X] Completed

### Describe the feature

Now Tailwind autocompletion works only in pure HTML files but not inside HTML code in PHP files.

**Comment by xcrap** [comment]
It's been a while but since moving to extensions I lost the support for tailwind in PHP.... everything worked so good before, the PHP extensions move broke a lot of things. I'm not sure if it still supports installing Emmet at the same time as well...
