### ISSUE TITLE
JS/TS diagnostics not working

### ISSUE THREAD

**Issue by refrainsclub** [zed-industries/zed#6364]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I cannot see JavaScript/TypeScript diagnostics (errors and warnings). For example, when I type invalid syntax there are no red squiggly lines. Nor are there errors under the project diagnostics.

Autocomplete works. If I type `document.get`, it will give options such as `getElementById`, `getElementsByClassName`. So I assume the LSP is working besides for the diagnostics.

Steps to produce:
1. Install latest Zed release on macOS
2. Create a JavaScript file
3. Write invalid code
4. Check if there are any errors

I have tried:
1. Using the latest preview version of Zed
2. Deleting node_modules, package.json and related files from my home directory
3. Cloning relevant LSPs into the Zed application support folder
4. Deleting ~/Library/Application Support/Zed
5. Reinstalling Zed
6. Upgrading the NodeJS install using nvm
7. Checking other languages (Rust diagnostics do work)
8. Disabling features such as Copilot

### Environment

Zed: v0.111.6 (stable)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="367" alt="Screenshot 2023-11-11 at 9 51 50 PM" src="https://github.com/zed-industries/community/assets/36752154/fe19e9f3-6817-48dc-9b3c-eabae264bfd3">
<img width="361" alt="Screenshot 2023-11-11 at 9 52 01 PM" src="https://github.com/zed-industries/community/assets/36752154/061ce5e2-54de-4a88-852f-2e652459867a">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/13325014/Zed.log)

**Comment by 0xSimbo** [comment]
typescript LSP nor javascript is working for me it looks like.

I dont get type hinting, type inference, autocompletion, autoimporting, linting, or error correction.

**Comment by dagi3d** [comment]
> typescript LSP nor javascript is working for me it looks like.
> 
> I dont get type hinting, type inference, autocompletion, autoimporting, linting, or error correction.

I just faced same problem(I am using zed preview 0.120.3) and restarting the editor fixed it.

**Comment by 0xSimbo** [comment]
> > typescript LSP nor javascript is working for me it looks like.
> > I dont get type hinting, type inference, autocompletion, autoimporting, linting, or error correction.
> 
> @0xSimbo I just faced same problem(I am using zed preview 0.120.3) and restarting the editor fixed it.

By restarting do you mean just closing and reopning? I tried that, but unfortunately no success. I've also updated to the last version and still not getting the server to work unfortunately

**Comment by 0xSimbo** [comment]
> > > typescript LSP nor javascript is working for me it looks like.
> > > I dont get type hinting, type inference, autocompletion, autoimporting, linting, or error correction.
> > 
> > 
> > @0xSimbo I just faced same problem(I am using zed preview 0.120.3) and restarting the editor fixed it.
> 
> By restarting do you mean just closing and reopning? I tried that, but unfortunately no success. I've also updated to the last version and still not getting the server to work unfortunately

Now switched to zed preview 0.120.4 and still not able to get typescript server to work.

**Comment by osenvosem** [comment]
Zed 0.147.2 still broken.

**Comment by Elue-dev** [comment]
i cant believe this is still a thing, no TS errors whatsover, only saw a lot of errors when building the project, had to move back to vs code due to this, what is the fix for this?
