### ISSUE TITLE
It looks like with Zed Preview the panel state is toggled every time the editor is opened.

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#6407]
It looks like with Zed Preview the panel state is toggled every time the editor is opened.

## Environment

Zed: v0.119.8 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

https://github.com/zed-industries/community/assets/16290753/72b29b5a-32f8-4da4-bc96-4795571df848

_Originally posted by @Moshyfawn in https://github.com/zed-industries/zed/issues/4919

**Comment by jizhi0v0** [comment]
Looks like it's reappearing

Zed Preview 0.134.1

bc0dd3aecbcf009baf1226cd791a98ce4f6d785d

![CleanShot 2024-05-02 at 23 22 03@2x](https://github.com/zed-industries/zed/assets/57976101/4f0d9759-cd35-485c-a098-fd0193a19b9c)

**Comment by jizhi0v0** [comment]
> Looks like it's reappearing
> 
> Zed Preview 0.134.1
> 
> [bc0dd3a](https://github.com/zed-industries/zed/commit/bc0dd3aecbcf009baf1226cd791a98ce4f6d785d)
> 
> ![CleanShot 2024-05-02 at 23 22 03@2x](https://private-user-images.githubusercontent.com/57976101/327486609-4f0d9759-cd35-485c-a098-fd0193a19b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjM4MDcsIm5iZiI6MTcxNDY2MzUwNywicGF0aCI6Ii81Nzk3NjEwMS8zMjc0ODY2MDktNGYwZDk3NTktY2QzNS00ODVjLWEwOTgtZmQwMTkzYTE5YjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZGM4ZmMyZTYzYThjMTRkYzc5ZjdiNTM5NmY2OGYyZTNiZTkyZDllNGM1ZDExMzYyZTIyOThjMjgyYzIxZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDe3vNN169dj8N3_YCr7TPbdp2mVz3Wd2hXQWVSwzxQ)

Also in Zed 0.133.5 version.
