### ISSUE TITLE
Slow tab switching (Zed 0.119.17)

### ISSUE THREAD

**Issue by Labrium** [zed-industries/zed#6426]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When simply switching tabs, Zed sometimes does switch instantly like 0.188.1, but most of the time freezes for almost a full second before actually switching to the new tab.

### Environment

Zed: v0.119.17 (Zed)
OS: macOS 10.15.7
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14042739/Zed.log)

**Comment by as-cii** [comment]
Hey @Labrium, thanks for the report! Do you have `Instruments.app` installed and, if so, would you mind capturing a CPU Profile while you move across tabs and Zed freezes? We are unable to reproduce this on our machines, so this would be huge to help diagnose what the problem is. Thank you! 🙏

**Comment by Labrium** [comment]
Sure thing. I also just found that switching tabs using the keyboard shortcut does not trigger the freezing, only clicking on the tabs.

**Comment by Labrium** [comment]
From these profiles, it looks like Zed is creating a ton of threads when you click to switch tabs, but not when you use the keybinding:
[ZedTabSwitchingClick.trace.zip](https://github.com/zed-industries/zed/files/14054015/ZedTabSwitchingClick.trace.zip)
[ZedTabSwitchingKeybinding.trace.zip](https://github.com/zed-industries/zed/files/14054018/ZedTabSwitchingKeybinding.trace.zip)

**Comment by mrnugget** [comment]
@Labrium nothing really stands out in the trace. Any timestamp in particular you think we should focus on?

Also: is there anything special about the files you're opening? Are they large? LSP attached?

A screen recording would be ideal, because it's really hard to reproduce this.

**Comment by Labrium** [comment]
https://github.com/zed-industries/zed/assets/76017200/8f4100d8-0d97-4012-b03f-8c6e6ae10a83

**Comment by ClanEver** [comment]
Same as this
Zed: v0.119.20 (Zed)
OS: macOS 12.2.1
Memory: 16 GiB
Architecture: arm

**Comment by mrnugget** [comment]
@Labrium thanks! Wow, that's interesting. Exactly 1s frames. Sadly I can't see those blocks in the traces you provided. 

Could you maybe re-record a trace but this time add the `Thread State Trace` instrument? To do, you need to hit the `+` in the top right corner of `Instruments.app` and add it. Like this:

![screenshot-2024-01-29-16 34 48@2x](https://github.com/zed-industries/zed/assets/1185253/c6efe9b7-d5a7-4643-b4fb-be21d597eace)

That will then record a trace showing what each thread was doing. Ideally we'd see the 1s show up somewhere.

![screenshot-2024-01-29-16 35 36@2x](https://github.com/zed-industries/zed/assets/1185253/887dd093-0558-442e-abee-73e9de10bdc4)

**Comment by Labrium** [comment]
@mrnugget I was about to record that trace for you, but it looks like this issue is completely fixed in Zed 0.121.5!

**Comment by mrnugget** [comment]
Ha! Well, I wish I knew what it was, but I'll take a closed issue :)
