### ISSUE TITLE
recently visited files in file search don't include their folder

### ISSUE THREAD

**Issue by abejfehr** [zed-industries/zed#6428]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It's hard to concisely describe the bug in a title, but the reproduction steps are very simple:

```
.
├── project-a/
│   └── package.json
└── project-b/
    └── package.json
```

1. create the aforeshown file structure
2. open both project-a and project-b in the workspace so they're siblings in the treeview
^ do this by right-clicking the empty tree view and choosing "Add Folder to Project" and choosing `project-a`, then repeating with `project-b`

Now, use command + P and search for "package.json"

<img width="575" alt="image" src="https://github.com/zed-industries/zed/assets/3917428/8b08eb08-7572-4623-859c-f29a504a2fea">

^ both files show up and you can easily see which project they're in, and that's very useful and nice.

if you open one of them, say `project-a/package.json` and close it, doing command + P shows it as a recent file, before you even type anything:

<img width="577" alt="image" src="https://github.com/zed-industries/zed/assets/3917428/4627a43d-aba8-4e82-9724-92b355c9c3f2">

^ that path is useless though, it's just `package.json` repeated twice. How am I to know which project `package.json` is in? The search results before this became a "recently visited" file were better because they included the project's directory

subsequent searches don't even reveal project-b/package.json, I have to literally find the file in the tree view: 

<img width="600" alt="image" src="https://github.com/zed-industries/zed/assets/3917428/1dcb309e-9d34-443a-bc3b-5c251cfc2260">

### Environment

Zed: v0.119.17 (Zed)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Included in the reproduction steps

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by YeungKC** [comment]
<img width="1624" alt="image" src="https://github.com/zed-industries/zed/assets/11473691/0752911a-7df6-4fd2-bdc9-ad12154fadd6">


Do you have any relevant configurations? I can't reproduce it.

**Comment by abejfehr** [comment]
> <img alt="image" width="1624" src="https://private-user-images.githubusercontent.com/11473691/299524483-0752911a-7df6-4fd2-bdc9-ad12154fadd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTcxOTMsIm5iZiI6MTcwNjE5Njg5MywicGF0aCI6Ii8xMTQ3MzY5MS8yOTk1MjQ0ODMtMDc1MjkxMWEtN2RmNi00ZmQyLWJkYzktYWQxMjE1NGZhZGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MWUxNGYxMzRjZjkxNDI3MGZjN2I1Y2YwYzBiNWE1MTIwMmI0NDlmMzZiMGZjZTdiNTA2ZjYyZWQ2NmVkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._-iS4vqmoF7gKSB8Alk6RcYoHZ-TE7D2Xnn831SM5eI">
> 
> Do you have any relevant configurations? I can't reproduce it.

I don't have any custom configuration yet. Have you selected one of those options? If you choose `project-a/package.json` from the list and then do it a second time you should be able to reproduce it
