### ISSUE TITLE
Site RSS is broken after recent update

### ISSUE THREAD

**Issue by trustmaster** [zed-industries/zed#6432]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Sorry for offtopic, I couldn't find an issue tracker for zed.dev website. I was subscribed to Zed blog updates via RSS. Recently the link specified in the HTML as 

```html
<link rel="alternate" type="application/rss+xml" title="Zed Industries - Blog" href="https://zed.dev/blog.rss"/>
```
stopped working. Now it gives 404. It used to work before.

### Environment

https://zed.dev/blog.rss

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxbrunsfeld** [comment]
@maxdeviant Could you look into what happened with the RSS feed?

**Comment by maxdeviant** [comment]
@trustmaster RSS feed is back: https://zed.dev/blog.rss

Apologies for the disruption!

**Comment by trustmaster** [comment]
Thanks for a quick response and quick fix! Keep the Zed up 💪
