### ISSUE TITLE
”Select all matches” considerably slower than Sublime in large documents

### ISSUE THREAD

**Issue by robinwhittleton** [zed-industries/zed#6440]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a large document with lots of matches, Zed is dramatically slower than Sublime Text when selecting all matches.

To replicate:
1. Download https://github.com/standardebooks/edgar-allan-poe_poetry/blob/master/src/epub/text/poetry.xhtml and open in both Zed and Sublime
2. Select the text `<span` in both
3. Hit ctrl + cmd + g in Sublime. It finds (on my version of the file) 2,351 occurrences and selects them in <200ms
4. Hit cmd + shift + l in Zed. It also finds 2,351 selections but takes 4 to 5 seconds and beachballs my machine while doing it

Ideally Zed would perform to within a factor of two of Sublime. Well, ideally I guess it’d be faster than Sublime 🙂

Also, I think I’d prefer to see the number of selections than the total number of characters selected. But that’s a separate issue.

### Environment

Zed: v0.119.18 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Thanks @robinwhittleton for reporting! That was a fun one. In the next release, select-all-matches should be a lot faster. See #6700 for details.
