### ISSUE TITLE
Regression: next search result keyboard shortcut, cmd+G, no longer works

### ISSUE THREAD

**Issue by mistydemeo** [zed-industries/zed#6441]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

macOS has a standard keyboard shortcut, cmd+G, to move to the next search result when a search is already open. Zed used to support it, but it's stopped working as of today's release. This last worked in 0.118.1; it stopped working in 0.119.17. I downgraded to 0.118.1 to confirm.

### Environment

Zed: v0.118.1 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by osiewicz** [comment]
Hey,
It works on my end with the latest stable (0.119.18); can you upgrade to that version again and re-check?
We've had a PR that addressed exactly that issue last week (https://github.com/zed-industries/zed/pull/4100), but that was a part of (IIRC) 0.119.16.

**Comment by mistydemeo** [comment]
After testing, it looks like what's broken is slightly more subtle: on older builds, if you hit esc to back out of the search panel, you can still use cmd+g to cycle search results. In the newer build, you can only cycle search results if the search panel is still open and cmd+g does nothing if you've closed it. (For context, the older behaviour is standard for macOS: try it in Safari or any other app using the native UI toolkits.)

**Comment by osiewicz** [comment]
Yup, that sounds like a bug; I'll open up a PR tomorrow. Thanks for the report!
