### ISSUE TITLE
Open projects from terminal

### ISSUE THREAD

**Issue by congdv** [zed-industries/zed#6457]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi! I tried to search the backlog, it seems zed doesn't support to open a folder from Terminal( please correct me if I'm wrong).
VSCode can open folder through terminal by `code <folder-name>`
If it is possible, can zed support to it? Something like this:

````
> zed my-project

```` 
it will open `my-project` folder in zed.

**Comment by ThatXliner** [comment]
On macOS, the current alternative is to run `open <whatever directory> -a Zed`

So, to emulate the command you described, just add this to your dotfiles (`.zshrc` for Zsh, `.bashrc` for bash):

```zsh
zed() {
    open "$1" -a Zed
}
```

**Comment by przytrzask** [comment]
> You need to install the Zed CLI.
> 
> This can be done through the command palette:
> 
> <img alt="Screenshot 2024-01-24 at 10 13 49 PM" width="573" src="https://private-user-images.githubusercontent.com/1486634/299526015-39566b28-2395-41ec-a8c3-f64598220fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTQwOTgsIm5iZiI6MTcxODQ1Mzc5OCwicGF0aCI6Ii8xNDg2NjM0LzI5OTUyNjAxNS0zOTU2NmIyOC0yMzk1LTQxZWMtYThjMy1mNjQ1OTgyMjBmYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMTIxNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhmMzNlMWE4NzFmZjUwMDdkZGQ4MmZhOTg1MjFhYjJmZmQ2M2RmNTVjZGViNTk0OTNkNDg0MDg5ZDk2ZTcxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.od2cbDSGmMahPtzq1xbsfVD_QpNHd35emEFXXmJNQwc">
> Once the CLI is installed you can use `zed <path>` to open that file/directory in Zed.

and is it possible to open new window for particular directory while zed is already running?
I am getting ```zed is already running``` when trying to do this
