### ISSUE TITLE
Automatic docstring

### ISSUE THREAD

**Issue by apertureless** [zed-industries/zed#6692]
### Check for existing issues

- [X] Completed

### Describe the feature

I know this might be a low priority request, but it would be great if we could have automatic docstrings. So if you start a docstring and press return it will automatically append the comment on the new line. 

### If applicable, add mockups / screenshots to help present your vision of the feature

VScode:
![vscode_doc](https://github.com/zed-industries/zed/assets/4975917/6b1b3a27-a0c8-46c0-aa91-d19452440c6c)

Zed:
![zed_doc](https://github.com/zed-industries/zed/assets/4975917/a5fb1ce5-3657-4c29-9b11-83b5886e01c2)

**Comment by osiewicz** [comment]
Hey, we already have the logic in place for something similar (non-doc comments). This sounds doable; we'd have to add doc comments to language config.toml and then modify [that part](https://github.com/zed-industries/zed/blob/main/crates/editor/src/editor.rs#L2505) of an editor. I can take a look later, as I've missed that feature for a bit but never quite got around to implementing it.
