### ISSUE TITLE
Vim support:  "%" matching tag jumping does not work

### ISSUE THREAD

**Issue by tonyhb** [zed-industries/zed#6702]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Enable vim mode
2. Attempt to use "%" to navigate to the matching paren (brackets, square tags, curly braces)
3. Nothing happens.

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 13.1.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Hey @tonyhb! Thanks for reporting. I have a hard time reproducing this: `%` doesn't work for all the things it works on in Vim, but it does for on `(`, `[`, `{` for me. See (`shift-5` is `%` on my keyboard):

https://github.com/zed-industries/zed/assets/1185253/3413d502-c343-43eb-9d4e-f06b62891fdd

**Comment by sschepens** [comment]
seems related to the programming language, `rust` works OK, but `c++`, `go` aren't working, don't know about others.

**Comment by mrnugget** [comment]
Ah! That helps, thanks @sschepens!

**Comment by whj768702** [comment]
I have the same problem. % doesn't work correctly. I develop react. and i make a small demo.

Environment
Zed 0.179.5 
Mac OS 15.3.2 (24D81)

https://github.com/user-attachments/assets/2b37909f-9c62-4f9b-aa80-f3fa36f50726
