### ISSUE TITLE
Allow editing of already sent messages in the channel chat

### ISSUE THREAD

**Issue by bennetbo** [zed-industries/zed#6707]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to be able to edit already sent messages inside the chat panel.

![image](https://github.com/zed-industries/zed/assets/53836821/a5ffbaf7-d264-4215-9083-c39283cb6d82)
Idea: add a new context menu entry "edit message" and allow editing the message "in place".

Also would be nice to display a badge for a given message if it was edited (e.g. like discord)

**Comment by ConradIrwin** [comment]
This shipped to 0.128.0-pre and will hit stable next week
