### ISSUE TITLE
Setting font to Jetbrains Mono makes the editor render gibberish

### ISSUE THREAD

**Issue by jamesgecko** [zed-industries/zed#6717]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My editor looks like this:

<img width="1037" alt="Screenshot 2024-01-25 at 12 21 38 PM" src="https://github.com/zed-industries/zed/assets/44252/ad7e58db-51c8-4991-9cb1-8080434b8159">

The following `settings.json` can cause it. Just setting the font to JetBrains Mono breaks everything. Other fonts such as Arial and Menlo work fine. JetBrains Mono renders fine in other editors on my system.

```json
{
  "buffer_font_family": "JetBrains Mono"
}
```

Version 0.119.18 worked fine yesterday, but today both it and 0.119.19 render everything incorrectly.

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by tml** [comment]
I am unable to reproduce this in Zed 0.119.20, with or without Jetbrains Mono being installed into Font Book:
<img width="668" alt="image" src="https://github.com/zed-industries/zed/assets/35148/99d96d0f-ae5c-4fdb-8411-4dffdd57a65b">

**Comment by jamesgecko** [comment]
Maybe it's related to a specific version of the font I'm using? Here's what's in my `/Library/fonts` directory.
[JetBrainsMono fonts.zip](https://github.com/zed-industries/zed/files/14087088/JetBrainsMono.fonts.zip)

**Comment by tml** [comment]
Maybe try [clearing your font cache](https://gist.github.com/jaredhowland/2da83f0cc0fbb1ac523f)?

**Comment by jamesgecko** [comment]
I installed the font from the `homebrew/cask-fonts/font-jetbrains-mono` Homebrew cask; it's on whatever the latest version of that is. I also manually installed the Nerd Font version of the font from https://github.com/ryanoasis/nerd-fonts/ on June 4, 2023. _That_ version of the font works fine, weirdly.

This is my current `settings.json`, but I can reliably reproduce with it completely empty except for the `buffer_font_family` property.

```
{
  "theme": "Ayu Mirage",
  "buffer_font_family": "Menlo",
  "buffer_font_size": 12,
  "ui_font_size": 15,
  "ui_font_family": "System Font",
  "buffer_line_height": "standard",
  "vim_mode": true,
  "base_keymap": "VSCode",
  "features": {
    "copilot": false
  },
  "terminal": {
    "dock": "right",
    "font_family": "Menlo",
    "font_size": 12,
    "line_height": "standard"
  }
  // "telemetry": {
  //     "diagnostics": false,
  //     "metrics": false
  // }
}
```

I'll try clearing the font cache, although I'm using this font in Visual Studio Code and iTerm without issues.

**Comment by jamesgecko** [comment]
I closed applications, ran `sudo atsutil databases -remove` in Terminal, and rebooted. No change.

(The `atsutil server -shutdown` command displays a message that the ATS utility is unsupported in macOS 14)
