### ISSUE TITLE
Assistant not working

### ISSUE THREAD

**Issue by RajatPawar** [zed-industries/zed#6719]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi! 

First of all, I really like the look of this product. Thanks for open sourcing it.

I am trying to set the assistant up, but the assistant just renders empty responses whenever I try to input anything into it. 

## Example
![Screenshot 2024-01-25 at 9 44 58 AM](https://github.com/zed-industries/zed/assets/18614743/8c2e5d0d-2325-445c-95ff-4637deb3a62b)

I've used 3 different OpenAPI keys, used different models (gpt3.5/4/turbo), quit & restarted, and `tail -f ~/Library/Logs/Zed/Zed.Log` doesn't add any new logs when I converse with the assistant. Here they are, anyway - 

[Zed.log](https://github.com/zed-industries/zed/files/14056242/Zed.log)

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 13.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by LORE-D-NATO** [comment]
I had the same issue, make sure you have money in your credit balance under the billing section of your OpenAI account and then generate a new key.

**Comment by alexkli** [comment]
I have the same issue, but I do have openai credits.

Notes:
- Installed zed for first time today, version `0.119.19`
- After installation, the assistant panel was ready (with same no-response behavior) even though I didn't even put in my api key yet. Manually reset it via the `assistant: reset key` as per the [docs](https://zed.dev/docs/assistant-panel). But problem still persists.
- It responds so quickly (with an empty message) that it feels like no HTTP request is even made to openai.

**Comment by RajatPawar** [comment]
I'll keep this open for @alexkli, but my issue seemed to have been around OpenAI credits. Thanks.

**Comment by algoflows** [comment]
Same issue for me, tried both my personal api key and also corporate - nothing worked.

**Comment by algoflows** [comment]
Actually its working - I needed to generate a new api key after adding credits.

**Comment by alexkli** [comment]
Today it works. Two things:
- it seems the api key needs the "All" permission. "Read-only" doesn't work
- when I changed the permissions yesterday to try, it probably took a while to become effective on the openai side, so it kept failing while I was trying

Would be good to clarify the permission in the api docs and show the user an error message.

**Comment by herko** [comment]
I can confirm - Adding credits to OpenAI account and THEN regenerating new API key helped.

**Comment by RajatPawar** [comment]
Seems like everyone's happy now :) Closing this!
