### ISSUE TITLE
The bell icon for notifications should signal that there are new notifcations

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#6721]
### Check for existing issues

- [X] Completed

### Describe the feature

As the title says...

**Comment by dammerung2718** [comment]
Where is @thisizkp?

**Comment by thisizkp** [comment]
🙌🏼 I'm here...

**Comment by JosephTLyons** [comment]
Might need to ping @iamnbutler's for design stuff

**Comment by iamnbutler** [comment]
I'll be out for the foreseeable future as I'm headed out on patleave, but @maxdeviant can probably advise here.

Fast option is an icon swap, correct option would be to use an indicator overlaid on the icon.

Note: we won't add a count on the notification status bar tool - we don't want to create additional distraction in the editor.

**Comment by maxdeviant** [comment]
> I'll be out for the foreseeable future as I'm headed out on patleave, but @maxdeviant can probably advise here.
> 
> Fast option is an icon swap, correct option would be to use an indicator overlaid on the icon.
> 
> Note: we won't add a count on the notification status bar tool - we don't want to create additional distraction in the editor.

Yea, I took a quick look at this and the way rendering of the icons is done in the status bar is quite limited at the moment, so swapping the icon is the limit of what we can do unless we rework the API.
