### ISSUE TITLE
Notifications get displayed on each monitor

### ISSUE THREAD

**Issue by bennetbo** [zed-industries/zed#6723]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use my MacBook with two external monitors. When sharing a new project via channels, I see the notification on all my monitors at the same time.

![image](https://github.com/zed-industries/zed/assets/53836821/fa4a0963-d02d-4a84-a472-2cae8d57aa43)

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
It looks like this is the intended behavior (or at least that was the case ~2 years ago): https://github.com/zed-industries/zed/pull/1817

**Comment by bennetbo** [comment]
I find the behavior a little unusual, I would expect notifications will be displayed on the primary display, or the display that currently shows zed. 
But maybe that's just me. I thought this is a bug, but if this is actually intended im fine with that 👍🏻
