### ISSUE TITLE
Disconnecting/Leaving from a channel

### ISSUE THREAD

**Issue by dsp** [zed-industries/zed#6731]
### Check for existing issues

- [X] Completed

### Describe the feature

At the moment, it is possible to join a channel via link. However there seems to be no way to leave a channel effectively so that it no longer shows up in the channel list. The context menu does not provide an option, the command pallette does not provide an option and there is no button. In the provided screenshot there is no way to quit a channel. I would expect a "Leave Channel" option. <img width="238" alt="image" src="https://github.com/zed-industries/zed/assets/14013/cfe63f5e-e51f-4a8a-b68e-6de1c2e52437">

**Comment by jansol** [comment]
There is now a "Leave Channel" option in that context menu so I think this can be closed?
