### ISSUE TITLE
vim mode impl `wildfire.vim` plugin

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6738]
### Check for existing issues

- [X] Completed

### Describe the feature

Unfortunately🥹, the vscode-vim plug-in does not implement this function either: https://github.com/VSCodeVim/Vim/issues/2834

![wirefire](https://github.com/zed-industries/zed/assets/45585937/8d9ba1e2-0ac9-4403-aeef-d3ce882f2d9d)

https://github.com/gcmt/wildfire.vim
https://github.com/SUSTech-data/wildfire.nvim
https://github.com/tpope/vim-jdaddy

**Comment by jansol** [comment]
I believe this is covered with the `editor::SelectLargerSyntaxNode` action that already exists? In normal mode that seems to be bound to alt+up by default, but I didn't see a vim mode binding for it.

**Comment by d1y** [comment]
Wow looks great ^:) 
```json
{
  "context": "Editor && VimControl && !VimWaiting && !menu",
  "bindings": {
    "enter": "editor::SelectLargerSyntaxNode"
}
```
![111111](https://github.com/zed-industries/zed/assets/45585937/9a6e0cd6-af47-4aee-b3bc-dd3963f0a0a8)
