### ISSUE TITLE
Preview all regex matches as you type in find/replace

### ISSUE THREAD

**Issue by sambeau** [zed-industries/zed#6757]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to propose that, while finding text, ALL regex matches are highlighted in the text as you type.

Currently, if you do a find using a regex, the first match is highlighted as you type, and the position of all other matches appear dynamically in the scrollbar. This makes it tricky to discover if your regex is correct. A live update would make it possible to use trial and error before hitting select all matches (or at the very least boost everyone's confidence about pressing the button ).

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="325" alt="Screenshot 2024-01-26 at 09 18 54" src="https://github.com/zed-industries/zed/assets/1320362/61bee98f-1fe7-4f47-a101-b9b459b5d492">

**Comment by osiewicz** [comment]
Hey, thanks for the report; I believe we're already highlighting all matches of a regex (or a search query in general), though in some themes the contrast of a match background is quite low. See the attached screenshot:
![image](https://github.com/zed-industries/zed/assets/24362066/b7b5c141-3bb9-44b0-b0c1-3bf5cf42e8e5)

**Comment by sambeau** [comment]
Confirmed.

_Maybe using an older version that didn't have this feature?_

<img width="738" alt="Screenshot 2024-03-05 at 17 00 35" src="https://github.com/zed-industries/zed/assets/1320362/825f7cb0-6b95-4303-9eb6-5b56d5251604">
