### ISSUE TITLE
Zed theme automatically changes based on system (light/dark)

### ISSUE THREAD

**Issue by vanloc1808** [zed-industries/zed#6764]
Hi guys, 
On Visual Studio Code, there is a feature which allows the theme automatically changes based on system theme (for example, light at light time, and dark when the night shift is on).
I read on Zed documentation but saw no information about this.
Does Zed have this feature?
Thank you.

**Comment by TheDarkchip** [comment]
Not yet

**Comment by jansol** [comment]
Looks like a duplicate of #5326

**Comment by vanloc1808** [comment]
> Looks like a duplicate of #5326

Thank you, I will close this
