### ISSUE TITLE
Allow providing a custom binary path for ZLS and other language servers.

### ISSUE THREAD

**Issue by paperdave** [zed-industries/zed#6767]
### Check for existing issues

- [X] Completed

### Describe the feature

Excited to see merging of the Zig integration. I built the editor locally to try it out, and it's great to see syntax highlighting for it finally.

But I have the nightly version of zig and zls installed on my machine. Zed seems to load the stable version 0.11. That makes it unable to parse the build.zig in Bun because of new features the language has seen that have not been released into stable.

<img width="1320" alt="image" src="https://github.com/zed-industries/zed/assets/24465214/c6a81f48-9a79-4f89-ac60-1841c4ba9740">

I solve this in VSCode with these options:

<img width="612" alt="image" src="https://github.com/zed-industries/zed/assets/24465214/d1f819d1-6040-4530-81a0-596e0cc351cb">

Furthermore, in Bun's repo, we hardcode a specific path relative to the project as our build system downloads a specific version of the compiler.

<img width="708" alt="image" src="https://github.com/zed-industries/zed/assets/24465214/633b7192-e4e3-463b-823b-1e5897918d77">

(the .exe is a specific workaround because Windows binaries must have .exe as a suffix; on Posix we symlink the extensionless binary to a .exe to get this working on all platforms seamlessly)

Honestly would be amazing if Zed could just peek at the vscode config and steal the properties to make this "just work", but I believe the proper feature request is having some Zed equivalents of these settings. I could not find any within the code so I assume they do not exist.

**Comment by paperdave** [comment]
Sorry, it seems this isnt a issue with ZLS. but rather the grammar.

<img width="741" alt="image" src="https://github.com/zed-
industries/zed/assets/24465214/9bbb8193-55ae-498a-85bf-2a68c3749426">

I believe my feature request is still valid as I do need to configure specific versions of the compiler.

**Comment by jansol** [comment]
Related: #4978

**Comment by paperdave** [comment]
It seems #9293 opens up the door to add this to Zig, which would solve my own use case.

**Comment by llogick** [comment]
I'm not confident enough in my Rust skills to PR it https://github.com/zed-industries/zed/commit/d40fb6a54168832bb71768302a26f0d41f9f6736

**Comment by GildedHonour** [comment]
![image](https://github.com/user-attachments/assets/c34bc937-7490-4492-9663-d170b419bfeb)

**Comment by notpeter** [comment]
I believe this is now supported. Can you test and see if this works for you?

```json
  "lsp": {
    "zls": {
      "binary": {
        "path": "/opt/homebrew/bin/zig"
      }
    }
  }
```

**Comment by mkaito** [comment]
> I believe this is now supported. Can you test and see if this works for you?
> 
> ```json
>   "lsp": {
>     "zls": {
>       "binary": {
>         "path": "/opt/homebrew/bin/zig"
>       }
>     }
>   }
> ```
> 
> If not, please comment and I'm happy to reopen. Thanks

Does this allow for relative paths? My use case would be ruby gem bundle binstubs.

**Comment by notpeter** [comment]
> Does this allow for relative paths? My use case would be ruby gem bundle binstubs.

I think so. Not sure whether it's:
- `whatever/bin/ruby-ls`
- `project_dir/whatever/bin/ruby-ls`
- `./whatever/bin/ruby-ls`

We should document this better. If it doesn't work go ahead and open a new issue. 

Alternatively you should also be able to add that bin dir to your path and it'll pick it automatically.
