### ISSUE TITLE
Minimizing Terminal

### ISSUE THREAD

**Issue by rabeehrz** [zed-industries/zed#6773]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has the feature to minimize the terminal on pressing <kbd>Command</kbd> + <kbd>`</kbd>.

In Zed, the terminal just switches focus.

I think on smaller screens (Using a 13-inch MacBook Pro), the terminal takes up too much vertical space.

**Comment by devdumpling** [comment]
+1, would love this

**Comment by Tom-Boscher** [comment]
You can minimise it using `cmd + J` (if I remember correctly)

**Comment by basitcodeenv** [comment]
+1

**Comment by wzxu** [comment]
You can override the key binding for this.
```json
{
  "bindings": {
    "ctrl-`": "workspace::ToggleBottomDock"
  }
}
```

**Comment by JosephTLyons** [comment]
In the command palette, you can find the `workspace: toggle {left,right,bottom} dock` commands. Just toggle the dock your terminal is in.

**Comment by rabeehrz** [comment]
> In the command palette, you can find the `workspace: toggle {left,right,bottom} dock` commands. Just toggle the dock your terminal is in.

Yep. That works. Issue can be closed.
