### ISSUE TITLE
[command palette] file bug report 404

### ISSUE THREAD

**Issue by devdumpling** [zed-industries/zed#6774]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open command palette (cmd shift p)
2. `file bug report`
3. navigates to https://github.com/zed-industries/zed/issues/new?assignees=&labels=admin+read,triage,defect&projects=&template=2_bug_report.yml
4. 404

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by onbjerg** [comment]
This was fixed in https://github.com/zed-industries/zed/pull/5862
