### ISSUE TITLE
Copy GitHub permalink from zed

### ISSUE THREAD

**Issue by DemianParkhomenko** [zed-industries/zed#6777]
### Check for existing issues

- [X] Completed

### Describe the feature

Copy GitHub permalink from zed. 

### If applicable, add mockups / screenshots to help present your vision of the feature

For reference see usage from VSCode. In VSCode it is implemented as part of https://github.com/microsoft/vscode-pull-request-github

It copies this link: https://github.com/dev-KPI/messenger-backend/blob/13e9d64bd28c81a1e191ee9cc656e7001d7ae198/application/api/example/add.js#L4-L7

https://github.com/zed-industries/zed/assets/95881717/0fb319c2-5b76-4d41-87a3-61138a8fee00

**Comment by d1y** [comment]
Very useful function, support

**Comment by maxdeviant** [comment]
This is available in [Zed v0.121.0](https://zed.dev/releases/preview/0.121.0).

**Comment by krstp** [comment]
Well I can see there is: `editor: copy permalink to line`, but does not seem to work :( (nothing happens). Paste will not paste the link.

TBH, what would be great is the keyboard shortcut such as `CMD+\` that would open immediately the link in the default browser.

**Comment by krstp** [comment]
Hmm... after reinstating the project it does work now 🤔 I will keep an eye why it is like that... What might have happened I added to the project additional file that has been on top of the file tree, nonetheless, I cannot verify it now as it work.

**Comment by krstp** [comment]
@JosephTLyons Latest update to 0.122.2 does not allow custom themes to be read anymore :( I was right in the middle of defining my own theme and did the update and now "my-cool-theme" does not show up any more :(

**Comment by krstp** [comment]
Correction... when there are duplicate entires in the config, it will flake out. Correcting those, I am back operational :)

**Comment by krstp** [comment]
I am having a little problem finding the right attribute to define selection/highlighted text color. Any help? Thanks.

**Comment by krstp** [comment]
FYI: Again, multiple restarts, the perm link after latest update `0.121.2` does not work again :(
