### ISSUE TITLE
[command palette] new journal entry opens new window even if journal already open

### ISSUE THREAD

**Issue by devdumpling** [zed-industries/zed#6783]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open your journal project (mine is at `~/journal` and was autocreated by Zed)
2. open command palette
3. `new journal entry`

Instead of it simply opening a new file in the already open Zed window that has your journal up, it opens in a new window. This is an awkward user experience where I have to close one of the windows. 

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by selfish** [comment]
+1
I use the Journal many times a day.
I have a window with common projects that I reference all the time open, and when I use `journal: new journal entry` it:
1. opens a new window even if today's file is already open
2. opens a new window even when the journal directory is already part of the open workspace

It would be great to see zed "find" the right place (open file, or workspace with file/folder)
