### ISSUE TITLE
Copilot accept keybinding

### ISSUE THREAD

**Issue by mbriggs** [zed-industries/zed#6788]
### Check for existing issues

- [X] Completed

### Describe the feature

I don't know if I'm the only one who interacts with copilot this way, but I find the biggest challenge of copilot is learning how to ignore it when the suggestions are bad. Something I find helps with that is separating out copilot accept into another key bind, instead of tying it to <tab> (autocomplete accept). Typically, I will use cmd+; for this. It would be cool if there was a way to set this independently if desired :)

Thank you, zed is super cool, really looking forward to seeing where it goes!

**Comment by raphaelluethy** [comment]
Is there any progress on this issue? It would make my workflow so much easier :)

**Comment by ray-pH** [comment]
> Is there any progress on this issue? It would make my workflow so much easier :) At the moment I just don't use Copilot as having the accept on `Tab` just intervenes too much while typing :/

You can bind them to another keymap. Unfortunately, I don't think there's a dedicated action to accept copilot suggestions, but `"editor::Tab"` does the job for me.  I'm currently using `ctrl-j` to accept Copilot's suggestion
```
"ctrl-j": "editor::Tab"
```

**Comment by raphaelluethy** [comment]
> > Is there any progress on this issue? It would make my workflow so much easier :) At the moment I just don't use Copilot as having the accept on `Tab` just intervenes too much while typing :/
> 
> You can bind them to another keymap. Unfortunately, I don't think there's a dedicated action to accept copilot suggestions, but `"editor::Tab"` does the job for me. I'm currently using `ctrl-j` to accept Copilot's suggestion
> 
> ```
> "ctrl-j": "editor::Tab"
> ```

Thank you for your suggestion, the main issue I have is that I would like to deactivate accepting inline suggestions when pressing tab so that i can still press tab without accepting the suggestion.

**Comment by elitan** [comment]
https://github.com/zed-industries/zed/issues/8707#issuecomment-2496132432
