### ISSUE TITLE
Preview tabs for rendered markdown, SVG, etc

### ISSUE THREAD

**Issue by naiyerasif** [zed-industries/zed#6789]
### Check for existing issues

- [X] Completed

### Describe the feature

I often work on markdown and SVGs and preview the outputs on an adjacent split tab in VSCode. Would be great if there's something similar on Zed as well so that I won't have to switch context to preview what I'm working on.

This feature can be potentially useful for many other languages as well, for example, [AsciiDoc](https://asciidoc.org/), HTML, [Marp](https://marp.app/), [d2](https://d2lang.com/), etc.

An associated API would be potentially useful for plugin writers in future who can build their own preview mechanisms for the language plugins they develop.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1450" alt="Screenshot 2024-01-26 at 22 41 27" src="https://github.com/zed-industries/zed/assets/19614213/0fc35f76-8cab-4ca0-8939-93e63c61cf75">

**Comment by d1y** [comment]
yep. need this 😍

**Comment by JosephTLyons** [comment]
Hey @naiyerasif, a PR just landed to introduce a markdown rendered view. I think it has some small defects here and there and images probably isn't supported yet, but the feature is largely here!

- https://github.com/zed-industries/zed/pull/6958
