### ISSUE TITLE
PHP: Allow single quote autocomplete + update line comments 

### ISSUE THREAD

**Issue by RemcoSmitsDev** [zed-industries/zed#6794]
### Check for existing issues

- [X] Completed

### Describe the feature

When you type a single quote, the editor does not autocomplete this for you because it's missing inside the `php/config.toml` file. And in PHP, it's also possible to have a single line comment with `#` as starter point.

**Comment by JosephTLyons** [comment]
Closed via https://github.com/zed-industries/zed/pull/6796. Thank you!
