### ISSUE TITLE
Remove node/openssl/archs directories from the node download

### ISSUE THREAD

**Issue by dj-documentation** [zed-industries/zed#6803]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`node/openssl/archs` contains almost 50 MB of unneeded files. Removing them would help people on slow metered internet connections. 
```
$ du -h ~/Library/Application\ Support/Zed/node/node-v18.15.0-darwin-arm64/include/node/openssl/archs | tail -1
 49M	/Users/mac/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/include/node/openssl/archs
 ```
 ```
 $ ls ~/Library/Application\ Support/Zed/node/node-v18.15.0-darwin-arm64/include/node/openssl/archs         
BSD-x86			VC-WIN64A		darwin64-x86_64-cc	linux-ppc64le		linux64-riscv64
BSD-x86_64		aix64-gcc-as		linux-aarch64		linux-x86_64		linux64-s390x
VC-WIN32		darwin-i386-cc		linux-armv4		linux32-s390x		solaris-x86-gcc
VC-WIN64-ARM		darwin64-arm64-cc	linux-elf		linux64-mips64		solaris64-x86_64-gcc
```

### Environment

macOS

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
Are you sure these are present in the `.dmg`?

That directory is where we install the Node runtime that gets downloaded when it's needed: https://github.com/zed-industries/zed/blob/5db7e8f89ee4f5d9801a2eab88adc1db3fda0f46/crates/node_runtime/src/node_runtime.rs#L59-L115

**Comment by dj-documentation** [comment]
You're right those files only show up after running the app. I'm on a slow metered connection so saving 50 MB is still helpful.

**Comment by dj-documentation** [comment]
The title and description of the issue have been updated

**Comment by dj-documentation** [comment]
It's a nodejs issue
https://github.com/nodejs/node/issues/46451

**Comment by maxdeviant** [comment]
> `node/openssl/archs` contains almost 50 MB of unneeded files. Removing them would help people on slow metered internet connections.

If the files are already being downloaded by Node, what would be the purpose in having Zed remove them once they are downloaded?

**Comment by dj-documentation** [comment]
Could you provide users the choice before downloading the large files? I assumed everything was included in the DMG since it was over 100 MB.

**Comment by dj-documentation** [comment]
The issue will be resolved when nodejs is upgraded

**Comment by dj-documentation** [comment]
See #7054 for why these files are downloaded
