### ISSUE TITLE
Include the Monokai theme in the default theme selection

### ISSUE THREAD

**Issue by simylein** [zed-industries/zed#6808]
### Check for existing issues

- [X] Completed

### Describe the feature

I would love to see the Monokai theme from vscode as a default theme option in zed. 
If that's not possible, I am looking forward to the planned theme 1.0 spec for importing custom ones. 

### If applicable, add mockups / screenshots to help present your vision of the feature

For clarification, those are the theme colours used in vscode (the code is not relevant, its just something to show the various colours)
<img width="991" alt="Screenshot 2024-01-26 at 21 19 29" src="https://github.com/zed-industries/zed/assets/67859356/1e573eef-75d8-4874-955f-130d79128ae7">

**Comment by d1y** [comment]
+1

**Comment by epmoyer** [comment]
I would pay $60 right now to have Molokai added.  Take my money!

I know customers always say they have "one feature" keeping them from using a product, and sometimes they are blowing smoke. Perhaps letting someone pay $60 for a feature lets them show that they mean it :) 

I would love to start using Zed in earnest but my brain is so very tuned to monokai that the speed gains of using Zed (or even the desire to just "kick the tires") are thwarted by my inability to quickly understand my code at-a-glance when it is in a different syntax highlighting style. If Zed exposed a modifiable custom style I'd happily sink 5 hours into that job just to get Monokai working.  I can't be the only person with a style that matters deeply to them. Perhaps an "interim" fix that exposes a _single_ configurable "custom" style would let the community author style sheets that could get everyone over the hump of having their own personal "must-have-style" until a broader theming solution shows up in a later version.

In practice I won't actually start using Zed for anything until I can get Monokai working somehow.

Cheers!

**Comment by epmoyer** [comment]
<img width="819" alt="image" src="https://github.com/zed-industries/zed/assets/136718/ae41a5d0-73b5-4699-b4e1-dfa2c21c4dfb">
Okay, embarrassingly I forgot that Zed went open source recently :).  I managed to get it building, added a new "Monokai" style (copied from Andromeda), and successfully changed one of the colors (strings, to yellow), which means I should be able to create my own local Monokai from here.  Wooohooo!!!

If I manage to complete a good conversion then I'll make a PR.

**Comment by epmoyer** [comment]
<img width="1046" alt="image" src="https://github.com/zed-industries/zed/assets/136718/e556d61b-1e7a-45c5-b419-356bae0b7ba3">

I got far enough with my port of Monokai to figure out that today the screenshot above is about as close as you can get (Zed on the left, VSCode on the right).  The current capabilities of the syntax highlighter don't allow you distinguish between some elements which Monokai traditionally colors differently (such as called procedure names (blue) vs procedure definitions (green)).

That said, it's close enough to achieve whatI wanted, which was to feel "at home" in Zed.

While I was looking up how to set my font to take the screenshot above I found out that 3 days ago the Zed team [Announced](https://zed.dev/blog/user-themes-now-in-preview) that they now support user themes in the "Zed Preview" release.  I tried converting the "OneMonokai-color-theme" VSCode theme to Zed using their new `theme_importer` tool and got the result below (which has the same issues I'd found when doing my own conversion; i.e. that some elements which Monokai would traditionally color differently share the same styling).

<img width="865" alt="image" src="https://github.com/zed-industries/zed/assets/136718/579cc2d4-7e4b-48e8-9aee-5beb3beb060e">

I've gotten this far so I may as well tie it with a bow and publish what I have.  I personally prefer the "bright" version (first screenshot) which I made manually than the lower-contrast of "OneMonokai" (second screenshot) but I will try to publish the latter as well. The [OneMonokai](https://github.com/azemoh/vscode-one-monokai) repo I used for the conversion is published with an MIT license so I'll be able to post that conversion feely.

Cheers! 
And **thanks** Zed team for going open source, and for adding User Theming!!!!!

**Comment by epmoyer** [comment]
I have published my Zed Monokai themes (my version and 2 conversions) at [Zed Monokai Theme](https://github.com/epmoyer/Zed-Monokai-Theme)

Share and Enjoy!

**Comment by nicodevs** [comment]
I will definitely use it when the 'user themes' feature lands on the stable version. Thank you!

**Comment by seanaguinaga** [comment]
Need the full Monokai theme to switch to any editor - currently VSCode has the best implementation

**Comment by d8vjork** [comment]
I was looking into this 😍  Thank you so much @epmoyer I'm a huge fan of Monokai since 12 years ago when I first wrote my own "hello worlds" in Sublime Text 2

**Comment by notpeter** [comment]
We're not adding additional default themes to Zed, but there are multiple monokai themes available as extensions.
<img width="657" alt="image" src="https://github.com/zed-industries/zed/assets/145113/45241292-fbcb-46e6-93ba-0982eaa713d9">


Thanks y'all.
