### ISSUE TITLE
AssistantPanel does not work , even when logged in to GitHub, nothing happens

### ISSUE THREAD

**Issue by ElijahLynn** [zed-industries/zed#6809]
The Conversation mode is not working right now. Nothing happens when I submit text. 

![image](https://github.com/zed-industries/zed/assets/1504756/027567ce-4c24-4b8b-a2b3-a6418191193a)

This behavior is the same with choosing 3.5, 4 or 4 turbo. The UX is confusing as the behavior is the same wether or not I am logged in. 

Another piece of feedback, the fact that I can choose the model suggests that this would be going straight to OpenAI, not Copilot, which I was excited for because I can ask broader questions to OpenAI than I can Copilot as the latter is limited to just code. I assume the feature is WIP, but wanted to pass on feedback for now.

**Comment by maxdeviant** [comment]
The Zed Assistant and Copilot are two separate features.

Using the assistant requires an OpenAI to be entered.

From your screenshot it looks like you might not have a valid OpenAI key (although we do need to improve this state so that it is clearer).

**Comment by herko** [comment]
Paid OpenAI API key is required for Assistant feature to work properly.

1. add credits to OpenAI
2. generate new API key
3. use `assistant: reset key` command
4. enter new key
5. possibly restart zed editor

**Comment by ElijahLynn** [comment]
Thanks, I haven't yet seen a UI to enter the key. 

When I press cmd + shift + p, and type "assistant" I only see these three options:
![image](https://github.com/zed-industries/zed/assets/1504756/31e8fb55-f608-426f-a3f2-98c276e4bfe5)


I installed with brew fwiw. 

```
Zed 0.119.19
020eadc7a43f28d3f91c9e19fbe2e24382a22c3e
```

**Comment by ElijahLynn** [comment]
> The Zed Assistant and Copilot are two separate features.

Thanks for clarifying, I was thinking of the Assistant like the Copilot Chat in VSCode. I am happy to hear that Assistant can use ChatGPT APIs directly and not be limited to coding only like Copilot. I like Copilot in the code editor and native ChatGPT in the Assistant. Looking forward to trying it out once I figure out how to enter the OpenAI API keys (I have a paid account, plus credits).

**Comment by ElijahLynn** [comment]
I see now the docs suggest that when I first open the Assistant that it will prompt for a key > https://docs.zed.dev/general/assistant-panel#setup. That never happened as far as user flow goes.

**Comment by ElijahLynn** [comment]
In addition, another odd thing is that I can click on "You" and change it to "Assistant" or "System", not sure if that is intended, but thought I would mention it.

**Comment by mikkelsvartveit** [comment]
I have the exact same issue, can't find anywhere to input my API key

**Comment by vigneshksaithal** [comment]
@ElijahLynn  @mikkelsvartveit  Refer this https://github.com/zed-industries/zed/issues/6685#issuecomment-1913032296 I got it working by following these steps.

**Comment by ElijahLynn** [comment]
> @ElijahLynn  @mikkelsvartveit  Refer this https://github.com/zed-industries/zed/issues/6685#issuecomment-1913032296 I got it working by following these steps.

Thanks, i just don't see that option, reset key.

**Comment by vigneshksaithal** [comment]
@ElijahLynn open chat assistant panel and then search you will get reset key option.

**Comment by JosephTLyons** [comment]
> > @ElijahLynn  @mikkelsvartveit  Refer this [#6685 (comment)](https://github.com/zed-industries/zed/issues/6685#issuecomment-1913032296) I got it working by following these steps.
> 
> Thanks, i just don't see that option, reset key.

Yes, make sure you are focused on the assistant panel when you open the command palette.

**Comment by omegabyte** [comment]
Even after inputting the api key and restarting Zed the conversation panel doesn't work. 
Inline assistant is working but not on chat. 

Not sure how to proceed

**Comment by vigneshksaithal** [comment]
@omegabyte In chat did you press cmd + enter after typing?

**Comment by mrnugget** [comment]
@omegabyte did you make sure to add credits to your OpenAI account? I updated the docs here to make that clearer: https://zed.dev/docs/assistant-panel

**Comment by mrnugget** [comment]
> a subscription to openai.com doesn't work ? you need to add extra credits ?

Depends. ChatGPT is OpenAI's tool on top of their APIs, essentially. If you want to use the API itself (which is what Zed does) then you need extra credit to use the API.

**Comment by ElijahLynn** [comment]
Just got the update to try this again. And I see the UI improvement to communicate this now: 
![image](https://github.com/zed-industries/zed/assets/1504756/0ba5f66e-14b5-4950-bf87-040fdb7534c7)

Feedback: 
- Make this a clickable link (https://platform.openai.com/api-keys)
- After I entered the key, it worked but took me to a blank screen, I finally figured out to click the + (plus) sign to start a chat, some feedback here would be good

**Comment by glenmiracle18** [comment]
Mine is not working as well
I added the open ai key, but to no avail

**Comment by mrnugget** [comment]
Did you add credits to your OpenAI account?

**Comment by Moshyfawn** [comment]
This feels like a troubleshooting discussion as the initial bug has been fixed. I'm going to close this issue, but please let me know if I should reopen it or create an Assistant Panel enhancement ticket.
