### ISSUE TITLE
Cross Platform Support

### ISSUE THREAD

**Issue by theoparis** [zed-industries/zed#6814]
As the platform support issue was locked I have no way to post this information other than to create a new issue...

I'm sure the zed team is aware but I wanted to point out some of the things that would  be torwards adding cross-platform support in case anyone else can help out.

- CoreMedia APIs used are *not always* specified as macos-only in multiple Cargo.toml files
- Implement the Platform trait for other platforms - there is only a current_platform implementation for macos

I guess this should belong in a separate issue so I will make one if necessary but it would be nice to replace git2 with [gitoxide](https://github.com/Byron/gitoxide).

**Comment by maxdeviant** [comment]
> I'm sure the zed team is aware but I wanted to point out some of the things that would be torwards adding cross-platform support in case anyone else can help out.
> 
> * CoreMedia APIs used are _not always_ specified as macos-only in multiple Cargo.toml files
> * Implement the Platform trait for other platforms - there is only a current_platform implementation for macos

We're only just getting starting on cross-platform support, so these things will be addressed in due time.

> I guess this should belong in a separate issue so I will make one if necessary but it would be nice to replace git2 with [gitoxide](https://github.com/Byron/gitoxide).

It looks like `gitoxide` is a reimplementation of Git in Rust? I suspect we'll continue to use `git2` for the foreseeable future, as these are just bindings to Git.

**Comment by Byron** [comment]
> I suspect we'll continue to use `git2` for the foreseeable future, as these are just bindings to Git.

That would be lovely! If such bindings would exist and would be nice, I think `gitoxide` would be less likely to exist. 

Unfortunately `git2` is 'just' a crate providing (fantastic) bindings to `libgit2` which in turn is a C library that implements a lot of Git, but by far not everything that it can do. This leads to compatibility problems as it won't read some more advanced repositories, and sometimes there are performance problems as well. Most of the time though it's really good so I would also recommend using `git2` until there is clear value in bringing in `gitoxide`.
