### ISSUE TITLE
Vim Mode - Space Key

### ISSUE THREAD

**Issue by titouandk** [zed-industries/zed#6815]
### Check for existing issues

- [X] Completed

### Describe the feature

Guys, I'm going to use my new pair of eyes on this very nice project 👍  to report the minor inconveniences I see.

So It seems like the space key in Command mode has no effect.
In Vim, my space key is moving the cursor to the next character.

**Comment by mrnugget** [comment]
To be nitpicky: you mean _normal_ mode, right?

**Comment by titouandk** [comment]
@mrnugget Yes indeed, I was referring to the normal mode.
