### ISSUE TITLE
lint: 'await' has no effect on the type of this expression although it does

### ISSUE THREAD

**Issue by Dinuda** [zed-industries/zed#6841]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have an async function that returns an object. However when I try to use it with `await`. There is a warning saying that `await has no effect on the type of this expression`.  

### Environment

Node v21.10

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="866" alt="image" src="https://github.com/zed-industries/zed/assets/63149008/2512abf2-1e97-42f5-b01f-74a44d20f0ce">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by oskar-szulc** [comment]
it can be caused by incorrect JSDoc on the awaited function: https://stackoverflow.com/questions/60368017/await-has-no-effect-on-the-type-of-this-expression
