### ISSUE TITLE
Add option to delay symbol highlights on caret hover

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#6843]
### Check for existing issues

- [X] Completed

### Describe the feature

When navigating with the caret, matching symbols are highlighted instantly, leading to visual noise. A ~200ms delay would be a more pleasant experience.

**Comment by smadeja** [comment]
I think it would be great to also have an option to disable this highlighting altogether

**Comment by jshrssll** [comment]
![CleanShot 2024-06-27 at 08 31 28@2x](https://github.com/zed-industries/zed/assets/7219867/0936350b-746b-42a3-80b2-b6e392f33d87)

Any update on this issue? When clicking into a word it should not highlight the entire word. This makes it visually difficult to differentiate when the whole word is selected by the cursor, or the cursor is just placed inside the word as depicted in my screenshot.

**Comment by nilsherzig** [comment]
> whole word 

![image](https://github.com/user-attachments/assets/9bf6043e-3569-4359-8382-d0546e49e998)

or - depending on the language - multiple lines

**Comment by GGGeorgiev20** [comment]
I managed to disable with a bit of a workaround. Add this to your settings.json
```md
"experimental.theme_overrides": {
    "editor.document_highlight.read_background": "#00000000"
}
```

**Comment by nilsherzig** [comment]
@GGGeorgiev20 thank you so much, i can finally try using this editor for a while

**Comment by xzbdmw** [comment]
There is a [hard coded 75ms delay](https://github.com/zed-industries/zed/blob/c5b6d78d5b01e0fcd243499bf3fb09cb1c758902/crates/editor/src/editor.rs#L188)  for DocumentHighlight, I'd like it to be 0, for instant highlight.

**Comment by mtasic85** [comment]
I use this to completely disable current symbol highlight:

```json
  "experimental.theme_overrides": {
      "editor.document_highlight.read_background": "#00000000",
      "editor.document_highlight.write_background": "#00000000"
  },
```

![image](https://github.com/user-attachments/assets/a868ef8f-fe64-47a6-abf3-f2223c95b9e1)

**Comment by xzbdmw** [comment]
You'll lose matching brackets highlights by this way, after the pr merged, you can set `"lsp_highlight_debounce": 9999999999,`

**Comment by stepankuzmin** [comment]
Is there a way to disable such LSP highlighting completely?
