### ISSUE TITLE
Split divider missing when left pane is active

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#6844]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

~~It shows up for a moment with the scroll bar but then disappears~~ edit: that was the scrollbar area border, the split divider doesn't show up. When the right pane is active it looks normal.

### Environment

Zed: v0.120.3 (Zed Preview)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1511" alt="image" src="https://github.com/zed-industries/zed/assets/14058796/4eaa2484-03fa-44da-831c-16ecefed95b1">
<img width="1511" alt="image" src="https://github.com/zed-industries/zed/assets/14058796/e0310050-920a-4309-aba1-3bf273a3f4b8">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
I haven't been able to reproduce this yet in Zed Preview v0.120.3:

<img width="2032" alt="Screenshot 2024-01-28 at 11 17 41 AM" src="https://github.com/zed-industries/zed/assets/1486634/0b553e35-cb5c-484d-919c-d2e8f98b5a71">

**Comment by diocletiann** [comment]
> I haven't been able to reproduce this yet in Zed Preview v0.120.3:
> <img alt="Screenshot 2024-01-28 at 11 17 41 AM" width="2000" src="https://private-user-images.githubusercontent.com/1486634/300277019-0b553e35-cb5c-484d-919c-d2e8f98b5a71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjcyMzIsIm5iZiI6MTcwNjQ2NjkzMiwicGF0aCI6Ii8xNDg2NjM0LzMwMDI3NzAxOS0wYjU1M2UzNS1jYjVjLTQ4NGQtOTE5Yy1kMmU4Zjk4YjVhNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTgzNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc2MjdkZjhkZTM0NTE0ODU0ZDUyZjk3OWZkNzkzZDY0MGUzNjJkNzEyYTU5NWI2NDdiMGVmZTFiYzgyMjVmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kIdPPrvu7UFM9uFgsRnJPxOP0M9dTFBJWz2vDnb8Ww0">

hmm, I still see it. Using `"active_pane_magnification": 1.8`

**Comment by maxdeviant** [comment]
> > I haven't been able to reproduce this yet in Zed Preview v0.120.3:
> 
> Ah, I see why. It happens when using "active_pane_magnification".

What do you have your `active_pane_magnification` value set at?

**Comment by diocletiann** [comment]
> > > I haven't been able to reproduce this yet in Zed Preview v0.120.3:
> > 
> > 
> > Ah, I see why. It happens when using "active_pane_magnification".
> 
> What do you have your `active_pane_magnification` value set at?

1.8

**Comment by tugkanpilka** [comment]
I've tracked down the bug and found that it is all about the code block:

```rust
for (ix, child_layout) in layout.children.iter_mut().enumerate() {
    if active_pane_magnification.is_none() {
        if ix < len - 1 {
            child_layout.handle =
                Some(Self::layout_handle(self.axis, child_layout.bounds, cx));
        }
    }
}
```

When i delete the if condition the bug disappeared.
```rust
for (ix, child_layout) in layout.children.iter_mut().enumerate() {
    if ix < len - 1 {
        child_layout.handle =
            Some(Self::layout_handle(self.axis, child_layout.bounds, cx));
    }
}
``` 

But i did not understand why there is a condition for  `if active_pane_magnification.is_none()` and is it have any side effects when deleted. Any thoughts?
