### ISSUE TITLE
State this Prominently: "Currently, Zed only supports macOS"

### ISSUE THREAD

**Issue by abebeos** [zed-industries/zed#6846]
### Check for existing issues

- [X] Completed

### Describe the feature

"from the creators of Atom" - what does this imply? Mac only?

Respect users time.

State this Prominently: "Currently, Zed only supports macOS"

- [ ] github project description
- [ ] https://github.com/zed-industries/zed/pull/6860
- Etc.

### If applicable, add mockups / screenshots to help present your vision of the feature

Code at the speed of thought – Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter. **For now macOS-only.**

**Comment by maxdeviant** [comment]
We now mention the supported platforms in the `Installation` section of the README: https://github.com/zed-industries/zed/tree/1564bd82f25c3cef74da581489c31389810d39f7#installation
