### ISSUE TITLE
Zed Auto update failed

### ISSUE THREAD

**Issue by ArmmGh** [zed-industries/zed#6857]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hi, the issue is "Auto update failed" which appeared today.
It also happens when I click on "check for updates" from top menu

I've tried @pan93412's suggestion from closed [issue](https://github.com/zed-industries/zed/issues/6231) to run `sudo pkill -9 mDNSResponder` but no luck, it still fails on auto update

Error message: 
```
2024-01-27T12:19:57 [INFO] downloaded update. path:"/var/folders/_f/h88mlptn3ln7d33tv8zfsh_40000gn/T/zed-auto-update.TvCh3cyCn6Mk/Zed.dmg"
2024-01-27T12:20:02 [ERROR] auto-update failed: error:failed to copy app: "rsync: failed to set times on \"/private/var/folders/_f/h88mlptn3ln7d33tv8zfsh_40000gn/T/AppTranslocation/6E6321BB-2A65-4914-9E31-A0DF55A35A1C/d/Zed.app/.\": Operation not permitted (1)\nrsync: failed to set times on \"/private/var/folders/_f/h88mlptn3ln7d33tv8zfsh_40000gn/T/AppTranslocation/6E6321BB-2A65-4914-9E31-A0DF55A35A1C/d/Zed.app/Contents\": Operation not permitted (1)\nrsync:
```

It seems to me like permission issue to some directories needed for the update of Zed version

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="251" alt="image" src="https://github.com/zed-industries/zed/assets/21320770/02642ffb-3bd2-40e0-bbae-dd3e6fdbb919">

<img width="240" alt="image" src="https://github.com/zed-industries/zed/assets/21320770/ff15e466-a86f-4fb6-a7ae-c41749896ced">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14072280/Zed.log)

**Comment by ArmmGh** [comment]
After upgrading Macos to the latest 14.3 the issue was solved

**Comment by JosephTLyons** [comment]
Thanks @ArmmGh - please reopen if you hit this again.

**Comment by zisra** [comment]
I'm getting this issue as well

**Comment by ArmmGh** [comment]
> I'm getting this issue as well

Do you use macOS, if so have you updated to 14.3?
Also consider updating Zed to the newest version

**Comment by tuan-h** [comment]
I have this issue as well. I'm on macOS 14.3 and using Zed 0.123.2

**Comment by watchgou** [comment]
I'm getting this issue as well

**Comment by watchgou** [comment]
I'm getting this issue as well

**Comment by watchgou** [comment]
I have this issue as well. I'm on macOS 14.3.1 and using Zed 0.123.2

**Comment by JosephTLyons** [comment]
Hey @tuan-h / @watchgou, can you open up a new issue for this?

**Comment by tuan-h** [comment]
@JosephTLyons 

For me it was a permissions issue. I installed Zed on user_A and then used it on user_B and couldn't auto update as user_B. I fixed it by changing the ownership to user_B.

```
sudo chown -R {user_B}:{user_group} /Applications/Zed.app
```

**Comment by bartekpacia** [comment]
I also encounter the problem. I was on Zed 0.123.6, updated to 0.124.7 when it became available, but the updating process begins on every startup now, and it fails - even though I was already on the latest version.

Sorry for commenting on a closed issue but I don't have time nor enough repro info to create a new one.

**Comment by joaoprocopio** [comment]
currently i am having the same problem.

to help y'all, please run zed with `zed --foreground`, you can get some useful messages.

in my case:
```
> zed --foreground
[2024-12-09T19:06:07-03:00 ERROR auto_update] auto-update failed: error:Aborting. Could not find rsync which is required for auto-updates.
[2024-12-09T19:06:07-03:00 ERROR zed] missing field `name` at line 29 column 1
```

and after installing `rsync` (`sudo apt install rsync -y`) this issue was fixed.  
i suggest that `rsync` should be included in the https://zed.dev/install.sh since most linux distros doesn't come with it.

**Comment by jdu211171** [comment]
> currently i am having the same problem.
> 
> to help y'all, please run zed with `zed --foreground`, you can get some useful messages.
> 
> in my case:
> 
> ```
> > zed --foreground
> [2024-12-09T19:06:07-03:00 ERROR auto_update] auto-update failed: error:Aborting. Could not find rsync which is required for auto-updates.
> [2024-12-09T19:06:07-03:00 ERROR zed] missing field `name` at line 29 column 1
> ```
> 
> and after installing `rsync` (`sudo apt install rsync -y`) this issue was fixed. i suggest that `rsync` should be included in the https://zed.dev/install.sh since most linux distros doesn't come with it.

after installing rsync it worked for me
