### ISSUE TITLE
Line Height

### ISSUE THREAD

**Issue by carlca** [zed-industries/zed#6864]
### Check for existing issues

- [X] Completed

### Describe the feature

There have been many requests for a configurable line height setting both < and > 1.0 for the main editing window, not just the terminal window. Here is another. Like many have said, this is the only thing stopping me using Zed and loudly proclaiming its brilliance loud and wide. So, please, do me, other people, and yourselves a favour and get it sorted!

### If applicable, add mockups / screenshots to help present your vision of the feature

![SCR-20240127-mduf](https://github.com/zed-industries/zed/assets/260612/f34e864f-0129-4f72-afa2-2e21c80729d3)

![SCR-20240127-meer](https://github.com/zed-industries/zed/assets/260612/bc8f6a9f-8928-41e3-be1e-eeb04be29970)

**Comment by sissyaboo** [comment]
You can set both options to `standard` and get 1.3 which is way better than 1, but it would be great to have an option for custom value:

```json
{
  "buffer_line_height": "standard",
  "terminal": {
    "line_height": "standard",
  }
}
```

**Comment by sissyaboo** [comment]
You can set both options to `standard` and get 1.3 which is way better than 1. Or use custom value:

```json
{
  "buffer_line_height": "standard",
  "terminal": {
    "line_height": "standard",
  },
  "terminal": {
    "line_height": {
      "custom": 2
     },
   },
}
```

**Comment by carlca** [comment]
Thanks for the reply! Where should this be entered? I've tried putting this in both global and local settings, and, either way, I'm getting these errors...

![SCR-20240127-mtuj](https://github.com/zed-industries/zed/assets/260612/44bd3dcc-e40e-4d70-8162-53c25a501a8a)

**Comment by carlca** [comment]
If you meant just this...

**Comment by sissyaboo** [comment]
Second terminal entry is for showcasing setting for custom option, you need to choose one.
If you use Settings > Open Default Settings you'll get every option with explanation.

**Comment by carlca** [comment]
It's only changing the line height on the terminal, not the main coding panel!

![SCR-20240127-nazd](https://github.com/zed-industries/zed/assets/260612/77069e7c-55c9-4534-aa10-510184b3d346)

**Comment by sissyaboo** [comment]
For code buffer you need to use `"buffer_line_height": "standard"` which I mentioned earlier, and you could check default settings before using anything to check what you can set. It would take you 30 seconds to find it without posting this issue.

**Comment by carlca** [comment]
What part of "It's having no effect on the main code editing panel..." do you not understand?

And then you have the gall to tell me, "It would take you 30 seconds to find it without posting this issue."
I suggest you don't reply and leave the issue to someone else that is not going to waste my time.

**Comment by sissyaboo** [comment]
Here's a screenshot from default config: 
![Screenshot 2024-01-27 at 16 02 20](https://github.com/zed-industries/zed/assets/154403323/e5960fc2-7c33-4639-8fa6-87e58d2fc9f6)

In your setting you set this with all other options you want and it will work:

```json
{
  "buffer_line_height": "standard",
  "terminal": {
    "line_height": "standard",
  }
}
```

**Comment by carlca** [comment]
I've had `Zed` installed for a long time, months, if not years. Maybe that's why that sample code does not appear in my `settings.json`. This is what I have in that part of the file...

![SCR-20240127-nkps](https://github.com/zed-industries/zed/assets/260612/cd6f7200-cf5d-46a9-879e-04ab998e9d78)

"Standard" did the trick! It looks like we've both had our time wasted by Zed's failure to cater for longer-term users 😠
