### ISSUE TITLE
Clearing terminal with Cmd+K occassionally takes a long time

### ISSUE THREAD

**Issue by telectr** [zed-industries/zed#6872]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On occasion, clearing the in-built terminal with `Cmd+K` takes almost a second to complete.

1. Close and reopen Zed.
2. Enter the integrated terminal
3. Type `Cmd+K` to clear the terminal
4. Observe how long it takes

**Note:** For me, this only occurs sometimes after running a command or opening Zed, not every time.

### Environment

Zed: v0.120.3 (Zed Preview)
OS: macOS 14.3.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Thanks for the report @telectr - I believe this was fixed with:

- https://github.com/zed-industries/zed/pull/4219
