### ISSUE TITLE
The border vanishing at the corners

### ISSUE THREAD

**Issue by stonkol** [zed-industries/zed#6876]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It seems that all four borders have the same visual issue, have not this issue in other apps.
It appeared both in dark and light themes.

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

![light](https://github.com/zed-industries/zed/assets/12591176/bb1eb2c9-4118-4d1c-82bf-136f8e3801d0)
![dark](https://github.com/zed-industries/zed/assets/12591176/985ecd07-ecae-487e-a0d9-4c2ffc916d27)

**Comment by klchoi** [comment]
It shouldn't have borders there to begin with. All the native macOS apps and the Zed 1 app also have no borders.

**Comment by maxdeviant** [comment]
This is resolved by #8922.
