### ISSUE TITLE
sub github copilot dialog UI add close button

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6878]
### Check for existing issues

- [X] Completed

### Describe the feature

I know I can just cmd p to close (it’s not fun)
<img width="517" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/867f50f9-f2f2-4c6b-ae23-60d20bbe651f">

**Comment by JosephTLyons** [comment]
Thanks for bringing this up @d1y!

**Comment by Moosems** [comment]
<img width="398" alt="Screenshot 2024-02-09 at 9 54 34 AM" src="https://github.com/zed-industries/zed/assets/95927277/dc6af072-1876-4d3d-85f3-97c0cdb99402">

I don't get any text at all in the most recent version.

**Comment by subashcs** [comment]
I am thinking about adding a cancel button like the following.

<img width="545" alt="Screenshot 2024-02-15 at 13 00 53" src="https://github.com/zed-industries/zed/assets/29421465/cba00119-5aab-454f-ad94-6c3e6af7e057">

I invite feedback from @Moosems and @JosephTLyons  on this matter. Please share your thoughts.

**Comment by JosephTLyons** [comment]
This has landed in [v0.124.0](https://zed.dev/releases/preview/0.124.0).
