### ISSUE TITLE
"file bug report" command palate action leads to 404 page

### ISSUE THREAD

**Issue by noahlh** [zed-industries/zed#6895]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"file bug report" from the command palate leads to the following URL:

https://github.com/zed-industries/community/issues/new?assignees=&labels=defect%2Ctriage&template=2_bug_report.yml&environment=Zed%3A%20v0.119.20%20%28Zed%29%0AOS%3A%20macOS%2014.2.1%0AMemory%3A%2064%20GiB%0AArchitecture%3A%20aarch64

Which is a 404 as of today (27 Jan 2024).

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Thank you, this got fixed a few days ago: https://github.com/zed-industries/zed/pull/5862 and is supposed to come in the next release.

**Comment by noahlh** [comment]
@SomeoneToIgnore cool!  Sorry I missed the other issue - i thought I did a thorough search but it wasn't thorough enough!  Thanks for the update,
