### ISSUE TITLE
Vim - Visual Model: 'u'/'U' doesn't change the casing of the selection

### ISSUE THREAD

**Issue by gm0stache** [zed-industries/zed#6901]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- enter visual mode
- select some text
- try changing the casing by pressing `u` or `U`

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by titouandk** [comment]
Indeed: this triggers an 'undo' instead of changing the case.

Same problem with the `guW` or `gUW` commands, interpreted as 'undo' and 'move to next word' (`g` is not taken into account).
