### ISSUE TITLE
rename module support

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#6916]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="382" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/3b7c4d56-4414-441e-9966-a2479bb0e161">

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jansol** [comment]
Is this not handled by rust-analyzer's "refactor: rename" function?

**Comment by kzhui125** [comment]
@jansol VSCode works, Zed rename doesn't work..

**Comment by maxdeviant** [comment]
@kzhui125 Could you clearly describe the behavior you are seeing?

Zed does support renaming modules via `rust-analyzer`, although we don't yet currently support renaming the actual files themselves containing the modules.

**Comment by kzhui125** [comment]
I want to rename `module1` to `module2`, as in the picture. @maxdeviant 

After rename operation, zed is still 'module1'

VSCode:
![vscode](https://github.com/zed-industries/zed/assets/11925432/f2591d90-1506-4b5c-9b04-191c33783ac8)

Zed:
![zed](https://github.com/zed-industries/zed/assets/11925432/88bb1434-d272-4dfd-97bb-3180ab1261bc)

**Comment by maxdeviant** [comment]
I was able to reproduce this locally.

Renaming a module within the same file works, but when I try to rename a module that corresponds to another file I'm seeing this error in the logs:

```
[2024-01-28T20:29:53Z ERROR util] crates/editor/src/element.rs:311: Client does not support rename capability.
```

**Comment by maxdeviant** [comment]
> I was able to reproduce this locally.
> 
> Renaming a module within the same file works, but when I try to rename a module that corresponds to another file I'm seeing this error in the logs:
> 
> ```
> [2024-01-28T20:29:53Z ERROR util] crates/editor/src/element.rs:311: Client does not support rename capability.
> ```

@SomeoneToIgnore Do you have ideas on what the issue might be here?

**Comment by maxdeviant** [comment]
I did track down where the error message is coming from: https://github.com/rust-lang/rust-analyzer/blob/7219414e81810fd4d967136c4a0650523892c157/crates/rust-analyzer/src/handlers/request.rs#L2151-L2164

**Comment by SomeoneToIgnore** [comment]
`client` is Zed is in this context, and apparently we did forget another capability in `lsp.rs` that caused rust-analyzer to return an error.
The harder part would be to support that request, but presumably it's yet another notification that we need to implement.

**Comment by SomeoneToIgnore** [comment]
This is the relevant spec part: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit
and looks like we do support file renames in Zed code already: https://github.com/zed-industries/zed/blob/444f918e51effada7097cec8a4857bb9a21b5823/crates/project/src/project.rs#L5362

so it might be just a forgotten capability, checking.

**Comment by SomeoneToIgnore** [comment]
Thank you for the find, it should help with all language servers.
