### ISSUE TITLE
make a "good first issue" label

### ISSUE THREAD

**Issue by evrsen** [zed-industries/zed#6917]
### Check for existing issues

- [X] Completed

### Describe the feature

it helps beginners to the project to find issues that are easier to tackle down, it also helps beginners overall who's learning rust and wants to contribute to open source projects, myself included there are people surfing GitHub issues with "good first issue" labels.

**Comment by JosephTLyons** [comment]
We actually have this label, it just isnt on anything yet. I'll keep my eye open for issue that seem beginner friendly. And for community members, feel free to @ me if you think an issue should have that label.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/4831 had got that label, so now there's proof of existence.
This one seems to be fixed and can be closed.
