### ISSUE TITLE
support switch activate terminal

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6921]
### Check for existing issues

- [X] Completed

### Describe the feature

My main reason is that it seems that direct switching (command) through terminal is not supported now. like ```workspace::ActivateTerminal```?
<img width="728" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/133a86e7-7fad-4029-b988-e5498c5e52cc">

**Comment by tolluset** [comment]
Is this issue solved by https://github.com/zed-industries/zed/pull/9963?
