### ISSUE TITLE
Features request so I can ditch Webstorm my favourite editor

### ISSUE THREAD

**Issue by totaland** [zed-industries/zed#6928]
### Check for existing issues

- [X] Completed

### Describe the feature

- [ ]  Indent guide - I can't see through the code without using the indent guide
- [ ] Test runner - TDD is a key for me so I need to run the jest test or whatever test it is in the same test file. 
- [ ] Copilot chat - log in with github so I don't have to try to find my key etc
- [ ] Rainbow coloring braket - I just need it for the ease of use
- [x] Structure - I want to see the structure of the file, functions, variable etc similar to Webstorm - I guess we can use Tree-sitter here.
- [ ] Commit - Similar to webstorm a side panel to see what files I have changes in git, check box to each file so I can rollback if I want to
- [ ] Npm list - a side panel showing all current scripts and you can click on to run 
- [ ] Todo list - find where the todos are in the project and show it here so we can easily track it

_No response_

**Comment by osiewicz** [comment]
Hi, thanks for reaching out. 
> Structure - I want to see the structure of the file, functions, variable etc similar to Webstorm - I guess we can use Tree-sitter here.

We already use tree-sitter extensively in Zed (in fact, one of the founders is creator of tree-sitter) and you can open an outline view via an action (default keybind is cmd-shift-o, though that might be different depending on the keymap) and under the tab bar, next to the file path.

As for Runnables ("Test runner" and "Npm list") and better Git support, we have that on our roadmap.

**Comment by jansol** [comment]
* indent guides: #5373
* test runner: #5141 #5242
* Copilot chat - I thought that is what the assistant panel does right now? (admittedly I've never tried it out)
* rainbow brackets: #5259
* git panel: #4367
* npm list - sounds like an extension to the test/command runner?
* todo list: #4808

**Comment by totaland** [comment]
> Hi, thanks for reaching out.
> 
> > Structure - I want to see the structure of the file, functions, variable etc similar to Webstorm - I guess we can use Tree-sitter here.
> 
> We already use tree-sitter extensively in Zed (in fact, one of the founders is creator of tree-sitter) and you can open an outline view via an action (default keybind is cmd-shift-o, though that might be different depending on the keymap) and under the tab bar, next to the file path.
> 
> As for Runnables ("Test runner" and "Npm list") and better Git support, we have that on our roadmap.

Thanks Osiewickz for clarify that. I saw the structure like in Zed now and it looks nice. Appreciated that. I wish we have a bit more than that.
<img width="345" alt="image" src="https://github.com/zed-industries/zed/assets/36496259/35145b6c-e12e-4e32-a8b1-0fd6be8493c3">

Currently in Zed we only show the first layer of the functions that available and the nested variable and functions are not shown.

**Comment by JosephTLyons** [comment]
> * indent guides: [Indent guides #5373](https://github.com/zed-industries/zed/issues/5373)
> * test runner: [Code runner #5141](https://github.com/zed-industries/zed/issues/5141) [Test runner integration #5242](https://github.com/zed-industries/zed/issues/5242)
> * Copilot chat - I thought that is what the assistant panel does right now? (admittedly I've never tried it out)
> * rainbow brackets: [Rainbow brackets #5259](https://github.com/zed-industries/zed/issues/5259)
> * git panel: [Source control view panel #4367](https://github.com/zed-industries/zed/issues/4367)
> * npm list - sounds like an extension to the test/command runner?
> * todo list: [Better comments #4808](https://github.com/zed-industries/zed/issues/4808)

* Copilot chat - https://github.com/zed-industries/zed/issues/4673

**Comment by JosephTLyons** [comment]
@totaland, it seems like we have existing issues for almost all of these requests. If there are not existing issues for something you've mentioned, feel free to open up a new issue for that specific item. I'm going to close this issue out. Check out the linked issues for progress on those items.
