### ISSUE TITLE
github auth login is not work

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#6934]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/12579229/5dcb417f-457b-4c92-98f0-5c0b71b85d7c)

### Environment

![image](https://github.com/zed-industries/zed/assets/12579229/2b779a5b-5c8d-4ffc-b8ae-7789597db61c)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14076400/Zed.log)

**Comment by danielweck** [comment]
Same here.

**Comment by danielweck** [comment]
Ah, now it works again :)

**Comment by mrnugget** [comment]
Sorry about that! We had a bit of an incident with our database. Things should work again!
