### ISSUE TITLE
Docs on Telemetry page have horizontal overflow

### ISSUE THREAD

**Issue by owickstrom** [zed-industries/zed#6945]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The [Telemetry](https://zed.dev/docs/telemetry) docs page is slightly horizontally scrollable at 1024px viewport width, due to long texts that overflow in the right-hand navigation sidebar. Could probably be solved with some overflow and text-overflow rules in CSS. But I'm not sure how to edit the theme, hence no PR.

(This was found by [Squidler](https://squidler.io/home), a service that I'm working on. Screenshot from the problem report below.)

<img width="938" alt="image" src="https://github.com/zed-industries/zed/assets/1464328/0918d999-970f-491b-ab85-50962df3764b">

### Environment

Website, not the editor itself.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
@owickstrom I pushed a change for this, can you see if that resolved the issue?

**Comment by owickstrom** [comment]
Yep, looks good now! You're almost as responsive as the editor itself. 😄  @maxdeviant 

If you want, I can report other issues. There are some accessibility problems, and possibly some language problems that I haven't looked through yet. Depends on what you think is valuable for your site.
