### ISSUE TITLE
ProjectPanel support `workspace::ActivatePaneIn*`

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6959]
### Check for existing issues

- [X] Completed

### Describe the feature

I want `workspace::ActivatePaneIn*` to also penetrate (work on) the ProjectPanel, Is there already some way to make it work?
```jsonc
{
    // global mode
    "bindings": {
      "shift-cmd-j": "workspace::ToggleZoom",
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]
    }
}
```
![global_keybind](https://github.com/zed-industries/zed/assets/45585937/6fd271fa-fcd6-4fb7-a7e8-5044d385d6dc)

**Comment by rauann** [comment]
VSCode allows moving up and down using bindings in the file tree as well. I would like the same for the Zed Left Dock.

**Comment by d1y** [comment]
workaround keybind

```json
{
	"context": "ProjectPanel && not_editing",
	"bindings": {
	 		"ctrl-l": "project_panel::ToggleFocus"
	}
}
```

**Comment by christian-gama** [comment]
I had to do something like this to work properly, because once I was in the terminal, it did not change the Pane and sometimes when I was in the ProjectPanel moving to the right direction would not work. Doing something like this makes everything work as expected.

```json
{
  {
    "bindings": {
      "ctrl-w ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-w ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-w ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-w ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]
    }
  },
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-w ctrl-k": "workspace::ActivateNextPane"
    }
  },
  {
    "context": "ProjectPanel",
    "bindings": {
      "ctrl-w ctrl-l": "workspace::ActivateNextPane"
    }
  }
}
```
