### ISSUE TITLE
Emulate vim-commentary

### ISSUE THREAD

**Issue by OldWorldOrdr** [zed-industries/zed#6964]
### Check for existing issues

- [X] Completed

### Describe the feature

When vim mode is enabled, gcc should comment/uncomment the selected line, and in visual mode gc should comment/uncomment all selected lines and then deselect.  The VS Code vim plugin did this and I miss it.

**Comment by mrnugget** [comment]
Hey there! I have the following in my `keymap.json` (because I missed that functionality too) and it works pretty well for me:

```json
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "g c c": "editor::ToggleComments"
    }
  },
  {
    "context": "Editor && vim_mode == visual",
    "bindings": {
      "g c": "editor::ToggleComments"
    }
  },
```

**Comment by OldWorldOrdr** [comment]
That's good enough for me
