### ISSUE TITLE
open keymap/setting so slow

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6968]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Everything is fast, but opening keymap/settings is really slow, as shown in the picture👀
![slow](https://github.com/zed-industries/zed/assets/45585937/f62b847d-3835-4052-9812-88811d9087ba)

### Environment

Zed: v0.120.3 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by osiewicz** [comment]
Hey, thanks for the report. I've recently merged a fix for this issue in https://github.com/zed-industries/zed/pull/6770 ; let me know if it still feels slow in the next Preview.

**Comment by JosephTLyons** [comment]
This feels pretty fast to me in Preview, which contains the fix. Im going to close this out - feel free to reopen if you are expiencing more delay than usual.
