### ISSUE TITLE
Terminal support cmd+click abs-file(dir)

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6983]
### Check for existing issues

- [X] Completed

### Describe the feature

yep
<img width="694" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/286559c2-0cd2-4da4-a634-4a8425af3894">

**Comment by mrnugget** [comment]
Hey @d1y. `Cmd-click` works for me as long as the path is relative to the project root directory. 

Is this a request to make it support paths relative to the terminals current working directory?

**Comment by mkdynamic** [comment]
Interesting edge case for me, line 1 (`app/views/views/show.tsx:1471:in`) is *not* CMD-clickable, but the other lines with relative file paths are:

```
22:28:17 web.1  | app/views/views/show.tsx:1471:in `<unknown>'
22:28:50 ssr.1  | change views/show.tsx
22:28:51 ssr.1  | [395.98ms] build client
22:28:55 ssr.1  | change views/show.tsx
22:28:55 ssr.1  | ✘ [ERROR] Expected identifier but found ")"
22:28:55 ssr.1  |
22:28:55 ssr.1  |     app/views/views/show.tsx:1471:71:
22:28:55 ssr.1  |       1471 │ ...nu.Item>{getPathDisplayName(fields, path.)}</DropdownMenu.Item>;
22:28:55 ssr.1  |            ╵                                             ^
```
