### ISSUE TITLE
Hint overlay details flicker

### ISSUE THREAD

**Issue by elsassph** [zed-industries/zed#6990]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing, the hint details briefly disappear after each key press, at least for TypeScript, causing a distracting flickering effect.

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 13.6.3
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here's a slowed-down video of what happens

https://github.com/zed-industries/zed/assets/297963/a4cd2e3c-f429-4429-a2f2-9ff818376daa

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by eikopf** [comment]
Worth pointing out that this issue also occurs when the diagnostic popup pushes the hover popup upwards such that its upper edge intersects some of the UI above the pane; is this an issue with the way its height is calculated?


https://github.com/zed-industries/zed/assets/60985094/06e34cdd-9a63-43ee-ab21-8c71becfd518
