### ISSUE TITLE
Match File Tree Icon Color to Git State

### ISSUE THREAD

**Issue by shellscape** [zed-industries/zed#6991]
### Check for existing issues

- [X] Completed

### Describe the feature

One of my favorite features of Atom was subtle and unassuming, but one that I've gone through great lengths to reproduce within VS Code, is the icon color of a file tree entry matching the Git state color of the entry name. Please note the differences below. 

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="328" alt="Screenshot 2024-01-29 at 9 53 38 AM" src="https://github.com/zed-industries/zed/assets/76371/4cfc1d08-3866-42ea-ad19-ae41ff196046">

**Comment by osiewicz** [comment]
Hey, thanks for reaching out. Icon color is set on [this line](https://github.com/zed-industries/zed/blob/d2968866b29403ccfeaf6015e644b58bdd59cbe4/crates/project_panel/src/project_panel.rs#L1383). /cc @maxdeviant

**Comment by maxdeviant** [comment]
This is available in [Zed v0.121.0](https://zed.dev/releases/preview/0.121.0).

**Comment by shellscape** [comment]
incredible, thank you
