### ISSUE TITLE
Project panel horizontal scroll

### ISSUE THREAD

**Issue by NicolayD** [zed-industries/zed#7001]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The left dock doesn't seem to have a horizontal scroll and the names of nested files are hidden. Resizing manually works, but it would be a welcome addition to have a horizontal scroll.

### Environment

Zed: v0.119.20 (Zed)
OS: macOS Sonoma 14.3
Memory: 8 GiB
Architecture: aarch64, Apple M1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by timfjord** [comment]
As per https://github.com/zed-industries/zed/issues/5550 it is a design decision to make it unscrollable

**Comment by NicolayD** [comment]
> As per #5550 it is a design decision to make it unscrollable

It's still very strange to use - even at only 5 or 6 levels deeply nested directories filenames start to get hidden and it's not very comfortable to have to manually expand it and shrink it. For example, in Sublime it is scrollable and in my experience has worked without issues.

**Comment by timfjord** [comment]
I think it has to do with how renaming items works in Zed.
In Zed, you rename files directly in the Project Panel whereas in ST there is a popup located outside of the sidebar.

**Comment by tausifcreates** [comment]
> I think it has to do with how renaming items works in Zed.

It's not just related items tho. if the file names are long or file structure is deeply nested, I need to resize the panel often to view the files.

**Comment by tausifcreates** [comment]
To tackle the problem of renaming the file in place (not a popup like Intellij), we could possibly lock the x-scroll when a file is being edited in Zed. As code is read more than it's written, it would make some sense cause files are renamed miniscule amount of times than it is read 🙂

**Comment by belianu** [comment]
I have the same problem too. 
When you have many folders and the file names are long it is really frustrating not to be able to scroll the file view horizontally. 
Zed is really good at many things, keeping the file view unscrollable would be a really bad lapse in style. 
I hope that the slider will be implemented in the future, or at least give the possibility to activate it from the settings if someone wants to activate it.

**Comment by notpeter** [comment]
A potential workaround: Zed has a settings option for the project panel to folder/collapse nested folders which only contain a single directory:
```
  "project_panel": {
    "auto_fold_dirs": true
  },
```

<img width="240" alt="image" src="https://github.com/zed-industries/zed/assets/145113/4c03f74c-6702-44f2-9c52-2f59394e9f94"><img width="241" alt="image" src="https://github.com/zed-industries/zed/assets/145113/07f42908-b92b-4013-95e3-6b3f6dcf2fcc">

In your example this would save you three levels of indentation as `java/com/estinguo/app` would show at one level. (Note you have to reload Zed for this to take effect)

**Comment by Eigilak** [comment]
> @notpeter
> 
> ![image](https://private-user-images.githubusercontent.com/31597742/345792767-2173aad1-d7ea-478b-8342-f958eabd0f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzIyMzUsIm5iZiI6MTcyMzIzMTkzNSwicGF0aCI6Ii8zMTU5Nzc0Mi8zNDU3OTI3NjctMjE3M2FhZDEtZDdlYS00NzhiLTgzNDItZjk1OGVhYmQwZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE5MzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZGI3YzFmNDY0YWI0NzM2YjQxNGExNzE4YWNjYjQ0ODYwOWZmNDJiM2JmOGQ3M2U2ZTcwNDMyN2M4OWQ1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xi1uC34uM4rkOkt5tUEUrYg0M_6DtTVxkRuVbNWAg-k)
> 
> This feature is useful in very few specific cases where you have a list of folders that contain only one internal folder in succession. It's practically like not having it. However, the problem remains that I cannot scroll horizontally in the list of files and above all the vertical guides that mark the beginning and end of the folder contents are missing. In my opinion, these are now necessary features to work well and without frustration. At the moment these two are the main features that prevent me from using zed as a code editor.

SAAAAAAME

**Comment by aretrace** [comment]
I almost cried 😭 when I realized horizontal scroll was not possible on the project panel. This is especially annoying in Java projects 🥲, hope the Zed team can ease the pain this sometimes causes.

**Comment by aretrace** [comment]
0.156.0 
@SomeoneToIgnore is a hero 🫡
