### ISSUE TITLE
Cannot select files in project panel with auto_reveal_entries set to false

### ISSUE THREAD

**Issue by KristalAlfred** [zed-industries/zed#7005]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure this an actual issue, but the behaviour is unexpected to me at least. Submitting this as an issue since navigating with keyboard works fine.

It seems like disabling the `auto_reveal_entries` setting also disables selecting files in the project pane with the cursor. Mostly a graphical issue, since the functionality of opening files works the same.

To reproduce:
1. Set `project_panel.auto_reveal_entries = false`
2. Try to click a file with the cursor

Loving Zed btw! :)

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 13.6.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/83819096/2ff93508-2b99-418a-aa8f-3f5fc210e292

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This feels like a bug to me, thanks @KristalAlfred for the report.

**Comment by KristalAlfred** [comment]
Fixed in #7245.
