### ISSUE TITLE
Add GPUI GitHub label

### ISSUE THREAD

**Issue by ted-marozzi** [zed-industries/zed#7018]
### Check for existing issues

- [X] Completed

### Describe the feature

I just want to search issues via a GPUI label to see if an issue relating to GPUI has been raised yet.

**Comment by JosephTLyons** [comment]
I created the label and added it to a handful of platform issues, but I didn't do an exhaustive search. We can add the label as we run into issues that it would fit on.

**Comment by ted-marozzi** [comment]
Thanks so much 👑
