### ISSUE TITLE
Font Family Not changing

### ISSUE THREAD

**Issue by master-of-none** [zed-industries/zed#7020]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After the new update today, anything I change ```buffer_font_family``` is not getting updated and it is always set to default font settings.

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="729" alt="Screenshot 2024-01-29 at 2 12 05 PM" src="https://github.com/zed-industries/zed/assets/37535815/fe00f31c-c6bf-4a37-a4b3-909202007051"> <br>
Here as you can see I have set the font to FiraCode and its not changed

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by master-of-none** [comment]
Zed was automatically formatting the first line in the code, hence JSON was not being parsed properly. Removed the comments given by Zed and it worked.

**Comment by pranjal201** [comment]
"ui_font_family": "CodeNewRoman Nerd Font Mono",
  "buffer_font_family": "CodeNewRoman Nerd Font Mono",
just set buffer_font_family to your respective value
