### ISSUE TITLE
Feature Request: Support for Opening URLs via cmd+click in Zed Editor

### ISSUE THREAD

**Issue by antimora** [zed-industries/zed#7021]
### Check for existing issues

- [X] Completed

#### Issue:
The Zed editor currently lacks the functionality to open URLs directly through a cmd+click action. While cmd+click is effectively used for opening files within Zed, this convenience does not extend to URLs, which could significantly enhance user experience and workflow efficiency.

#### Expected Behavior:
Ideally, users should be able to navigate to URLs directly from within the editor by using the cmd+click action on hyperlinks. This feature is common in many modern text editors and IDEs, providing a seamless workflow for users dealing with documentation, references, or web-based resources.

#### Current Behavior:
As of now, cmd+click in Zed is limited to opening files. Attempting this action on a URL does not yield any result, thereby requiring users to manually copy and paste URLs into a web browser, disrupting the workflow.

#### Steps to Reproduce:
1. Open any document in Zed editor that contains a URL.
2. Try using cmd+click on the URL.
3. Observe that there is no response or action taken by the editor.

### Suggested Solution

Implement a feature where URLs can be recognized and made clickable within the editor. When a user presses cmd and clicks on a URL, the editor should open the default web browser and navigate to the specified address.

### Additional Context

- This feature request is based on the current understanding that Zed does not support URL opening via cmd+click as of the latest version (Zed 0.119.21).
- The addition of this feature would align Zed with other contemporary editors, enhancing its usability and appeal to a broader user base.

### Environment

- Zed Editor Version: Zed 0.119.21
- Operating System: Mac

This feature request aims to improve the Zed editor's functionality and user experience. The ability to quickly access web resources directly from the editor is a valuable addition for many users, especially those frequently dealing with online documentation or resources.

**Comment by good-lly** [comment]
i know it looks like a minor detail, but overall its a important function of any editor ... it is breaking flow to not be able to swiftly jump to code or file

**Comment by JosephTLyons** [comment]
This is now on main and will be going into the next preview (v0.122.x)

- https://github.com/zed-industries/zed/pull/7312

https://github.com/zed-industries/zed/assets/19867440/d3caf51b-2052-4341-aff0-69a85d212010
