### ISSUE TITLE
Cannot enter vim insert mode with a/i if visual mode active

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#7026]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Requires escaping to normal mode before insert mode.

### Environment

Zed: v0.120.4 (Zed Preview)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
Hi @diocletiann! I think this is expected behavior, in vim (and zed) you need to use the upper case versions  (`A` and `I`) to switch from visual mode to insert mode.

In visual mode `a` and `i` start a selection expansion action (so you can do `vaw` to select the current word).

Please let me know if `A` and `I` are not working for you, and we can debug!

**Comment by diocletiann** [comment]
> Hi @diocletiann! I think this is expected behavior, in vim (and zed) you need to use the upper case versions (`A` and `I`) to switch from visual mode to insert mode.
> 
> In visual mode `a` and `i` start a selection expansion action (so you can do `vaw` to select the current word).
> 
> Please let me know if `A` and `I` are not working for you, and we can debug!

You're right, I wasn't clear enough. `A` and `I` seem to work as intended. 

To reproduce my issue, try selecting some text as if you were copying, and then click somewhere else (where you might want to paste). Then `a`/`i` should at least let you enter insert mode, and in Vim just moving the caret with the mouse cancels the selection and reverts to normal mode.

**Comment by mrnugget** [comment]
I think that's being worked on in here: https://github.com/zed-industries/zed/pull/6985
