### ISSUE TITLE
Terminal support GitEditor(commit)

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#7048]
### Check for existing issues

- [X] Completed

### Describe the feature

I need to git commit in the terminal to edit in zed, and I think it can be done better than vscode, for PREFIX setting highlighting, for example: `fix / feat / chore / docs`
![fix](https://github.com/zed-industries/zed/assets/45585937/0e29aabe-d8d5-48f8-a201-ce7bb18ef1ca)

**Comment by JosephTLyons** [comment]
Hey @d1y, did your PR address the things you wanted here?

**Comment by d1y** [comment]
> Hey @d1y, did your PR address all the things you wanted here?


Running well 🥳

https://github.com/zed-industries/zed/assets/45585937/93c3bff6-33be-4c66-a8d8-46cf403e74e6

**Comment by hferreiro** [comment]
I'm getting this error everytime I try to edit a commit message in Zed:
> [ERROR] failed to load language Git Commit: no such grammar git_commit

**Comment by d1y** [comment]
> I'm getting this error everytime I try to edit a commit message in Zed:
> 
> > [ERROR] failed to load language Git Commit: no such grammar git_commit

fix to https://github.com/zed-industries/zed/pull/7982

**Comment by SomeoneToIgnore** [comment]
Had noticed that in my Linux builds in VMs, an eternity is spent during

```
    Building [=====================> ] 1163/1168: tree-sitter-gitcommit(build)                                                            
```

@d1y would you consider moving that into an extension, given that it's all about the highlights?

**Comment by d1y** [comment]
> Had noticed that in my Linux builds in VMs, an eternity is spent during
> 
> ```
>     Building [=====================> ] 1163/1168: tree-sitter-gitcommit(build)                                                            
> ```
> 
> @d1y would you consider moving that into an extension, given that it's all about the highlights?

Are you talking about fallback to extensions? next I'll roll it back to the extension, contains other git related highlights

- [git commit](https://github.com/gbprod/tree-sitter-gitcommit)
- [git rebase](https://github.com/the-mikedavis/tree-sitter-git-rebase)
- [.gitattributes](https://github.com/tree-sitter-grammars/tree-sitter-gitattributes)
- [.gitignore](https://github.com/shunsambongi/tree-sitter-gitignore)
- [.gitconfig](https://github.com/the-mikedavis/tree-sitter-git-config)
- ...etc

**Comment by wuvinotre** [comment]
Do you need to make any additional settings? 
i installed the extension but when i used the "git commit" command i was unsuccessful.

**Comment by d1y** [comment]
> Do you need to make any additional settings? i installed the extension but when i used the "git commit" command i was unsuccessful.

I guess you need to set the $EDITOR environment variable

```json
{
  "terminal": {
      "env": {
        "EDITOR": "zed"
      }
    },
}
```

**Comment by GOWxx** [comment]
> I guess you need to set the $EDITOR environment variable

I think the correct config is `"EDITOR": "zed --wait"`

```json
{
  "terminal": {
    "env": {
      "EDITOR": "zed --wait"
    }
  }
}
```

**Comment by schillermann** [comment]
If a default editor is set for git, this will override the editor set in zed.
At least that is the case in Ubuntu.

**Comment by injust** [comment]
`$GIT_EDITOR` is probably the most correct environment variable to set for this purpose. (It's what VS Code uses when the "Git: Terminal Git Editor" setting is enabled.)
