### ISSUE TITLE
Tree item indentation changed on panel resize 

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#7058]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/40336192/74ba3b0b-aad8-4dca-9df9-e0e2d992dcd4

### Environment

Zed: v0.120.4 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I'm unable to reproduce this in:

```txt
Zed: v0.155.0 (Zed Nightly 6b56530a4ab0b45d072ce5fe2c19e10e8cd3f58b)
OS: macOS 14.4.0
Memory: 64 GiB
Architecture: aarch64
```

If you are still able to reproduce it, feel free to ping me and I will reopen this issue!
