### ISSUE TITLE
Inconsistent docs URL in config JSON

### ISSUE THREAD

**Issue by danielweck** [zed-industries/zed#7061]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As @maxdeviant said:

> "The Gitbook version of the docs running at https://docs.zed.dev/ is the legacy docs. The new docs live at https://zed.dev/docs."

Original discussion: https://github.com/zed-industries/zed/discussions/6955

Problem description: the legacy GitBook docs generator produced unnecessary heavy HTML markup which breaks copy/paste functionality in Firefox (in addition to wasting bandwidth etc. :)

* https://github.com/zed-industries/zed/blob/cddc0fbf928a6a7a9f8f6f8a57bc33c46a96fbce/assets/settings/initial_local_settings.json#L4 => https://docs.zed.dev
* https://github.com/zed-industries/zed/blob/cddc0fbf928a6a7a9f8f6f8a57bc33c46a96fbce/assets/settings/initial_user_settings.json#L4 => https://zed.dev/docs/

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.3.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Thanks @danielweck, it looks like this PR cleaned it up:

https://github.com/zed-industries/zed/commit/5e64d45194e0cd41f36c62fef82bb7273c30e388
