### ISSUE TITLE
Ignore all spaces in file finder query

### ISSUE THREAD

**Issue by Otterpocket** [zed-industries/zed#7066]
### Check for existing issues

- [X] Completed

### Describe the feature

Trying to find files by path and names without spaces can be messy, especially when using partial names.

### Current Behaviour
![image](https://github.com/zed-industries/zed/assets/7274458/d374c2f9-f6f8-4f79-950e-66a46f714763)

### Suggested Behaviour
![image](https://github.com/zed-industries/zed/assets/7274458/a630b0f5-e65b-48c1-aa01-bf72bb3233ee)

**Comment by lucasreppewelander** [comment]
same as #7077

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/zed-industries/zed/issues/5324
