### ISSUE TITLE
Code navigation doesn't work (cmd+click)

### ISSUE THREAD

**Issue by birosrichard** [zed-industries/zed#7075]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hey, I'm currently on the Zed 0.119.21 and after installation, selecting theme + keybinding + installing CLI my code navigation between files and function definiton doesn't work. When I hover over function name (or import) while pressing CMD I don't see it is a link. I tried to reinstall Zed many times (been trying it from version 0.119.18) but I'm not able to fix the issue. 

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
@birosrichard What language(s) are you seeing this with?

**Comment by fran122157** [comment]
This happened to me as well in my first intallation of zed.

Checkout #4628 ([this comment](https://github.com/zed-industries/zed/issues/4628#issuecomment-1908628375) in particular) 

Removing the package.json and node_modules from my home dir and reinstalling zed did de trick.

**Comment by ForLoveOfCats** [comment]
Gonna close this as if that's the issue you were having we have a fix in place which will go out in our next stable release Wednesday
