### ISSUE TITLE
Empty PDF display

### ISSUE THREAD

**Issue by Zarox28** [zed-industries/zed#7076]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open a PDF file in the right panel, the display is empty.

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.3.0
Memory: 8 GiB
Architecture: aarch64

<img width="400" alt="image" src="https://github.com/zed-industries/zed/assets/41804375/14245250-9756-4ee0-ada5-f174fb2ffbf2">

**Comment by jansol** [comment]
This seems more like a feature request than a bug -- PDF is very far from being a plain text format. Slightly related to #6789

**Comment by SuperKenVery** [comment]
Hi, could you please consider re-opening this issue, since #6789 has been closed?

**Comment by fvirdia** [comment]
This is important for me too. I am an academic researcher, and in my job I am often writing code in Python or C++ to run experiments, to later generate plots in PDF format, as these are relatively painless to share between colleagues and to add within Latex figures. Being able to open the file witin editor is really useful when you have, say, hundreds of instances of a plot in a directory within your project.

**Comment by jansol** [comment]
> generate plots in PDF format, as these are relatively painless to share between colleagues and to add within Latex figures

FWIW for that exact purpose I use SVG, which is already technically supported in Zed (just needs some UI wiring for previews) and can be imported to LaTeX with the svg package.

**Comment by fvirdia** [comment]
Sure, but unfortunately I have to deal with existing projects with thousands of plots in PDF which I don't think right now it's worth regenerating.

I looked into writing an extension for Zed to display PDFs, but IIUC extensions can only deal with limited functionality (language support, slash commands), and not rendering, correct?

**Comment by jansol** [comment]
Yes, PDF rendering would have to be implemented in Zed itself.
