### ISSUE TITLE
Scrollbar cutting off last character on line.

### ISSUE THREAD

**Issue by MordFustang21** [zed-industries/zed#7098]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Have a long line that goes beyond width and have to horizontal scroll. Furthermost character is hidden behind scrollbar. In the example below there should be a `{`
![image](https://github.com/zed-industries/zed/assets/8725798/ed9da622-2558-49fb-9047-2e896d5e3334)

### Environment

Zed: v0.121.0 (Zed Nightly)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by simoncocking** [comment]
Further to this, I'd like to see a setting to allow a configurable amount of horizontal overscroll - allow the view to scroll `n` characters _beyond_ the end of the longest visible line. VS Code's setting for this:
![image](https://github.com/zed-industries/zed/assets/1700927/fdc44c3a-b4cd-40ff-b4c6-fc1a1f40e051)

**Comment by jnovakdev** [comment]
Can confirm, it causes unnecessary confusion while having a long line of a text. 
![Screenshot 2024-04-05 at 7 57 53](https://github.com/zed-industries/zed/assets/30055019/9d06443d-987a-44ed-8e53-367c53687fad)

**Comment by SamHep0803** [comment]
Any update to this? Very annoying when it comes to working in files with long line lengths.

**Comment by Nitemaeric** [comment]
This is pretty critical. When writing a long line, it's hard to determine how the line was "closed".

```ruby
let(:something) { "a really long string" }
```

The `}` gets cut off, so it doesn't give the desired confidence.

![CleanShot 2024-05-01 at 23 00 00](https://github.com/zed-industries/zed/assets/4231530/85518c0f-d4d0-4927-8064-f53e42a404a6)

**Comment by SomeoneToIgnore** [comment]
Should come in Zed 0.136 thanks to @\alygin

**Comment by carlsverre** [comment]
I'm still seeing this issue in Zed version 0.168.2.

**Comment by by-theo** [comment]
try setting `"soft_wrap": "bounded"`
