### ISSUE TITLE
Import Themes from VSCode

### ISSUE THREAD

**Issue by michealp-coder** [zed-industries/zed#7111]
> I just wanted to mention that we have been working on a VS Code theme importer and that at some point, it will be public, so others can simply import whatever VS Code themes into Zed!

_Originally posted by @JosephTLyons in https://github.com/zed-industries/zed/discussions/6659#discussioncomment-7821670_

**Comment by JosephTLyons** [comment]
The VS Code theme importer is public now. Right now, its just tied up in the repo [here](https://github.com/zed-industries/zed/tree/main/crates/theme_importer).

**Comment by michealp-coder** [comment]
@JosephTLyons , that's super exciting.

Question: will this be exposed in the GUI of Zed? I ask because it's not super clear to me how to use that crate from the ReadMe file.

**Comment by JosephTLyons** [comment]
> @JosephTLyons , that's super exciting.
> 
> Question: will this be exposed in the GUI of Zed? I ask because it's not super clear to me how to use that crate from the ReadMe file.

Yeah, sorry, things aren't documented at the moment. I wasn't on the team who made it and I decided to give it a spin last night. What I did was:

1. Found a VS Code theme I liked
2. Found the location of that theme package in `~/.vscode/extensions`
3. Did a `cargo run <location_of_theme>
4. Copied the contents of the output and placed it into a new file that had this structure:

```json
{
    "name": "Some name",
    "author": "Some author",
    "themes": [
        {
            <output_of_theme_importer_here
        }
    ]
}
```
5. Saved that file into `~/.config/zed/themes`
6. Restarted Zed (note that this hasn't hit Preview or Stable yet).

Sorry this is pretty informal and not great documentation, we will add some instructions and probably streamline the process a bit more going forward.

**Comment by CodeNinjaUG** [comment]
```~/.config/zed/themes isnt available do we create manually or it has already been pushed in the new versions ```

<img width="949" alt="Screenshot 2024-01-31 at 09 38 02" src="https://github.com/zed-industries/zed/assets/23071912/ff2bbb8e-7007-4c90-a4d8-d35c92246427">

**Comment by michealp-coder** [comment]
> 3. Did a `cargo run <location_of_theme.json>`

@JosephTLyons 

Thanks for the help but I run into this error on step # 3

`-ksh: cargo: not found`

My environment is:

macOS 14.3
Zed 0.120.4

I assume I need to install the CLI, or install something from https://www.rust-lang.org

I'll give this a try and report back https://doc.rust-lang.org/cargo/getting-started/installation.html

Question: any word if this will be exposed in the GUI? It's such a great feature that I think so many would appreciate!

**Comment by JosephTLyons** [comment]
@michealp-coder, hang tight, we are putting out a blog post today that explains it in better detail. Sorry for any confusion I've caused.

**Comment by CodeNinjaUG** [comment]
had pushed a commit explaining how i done it in cli.. it wasnt approved i
guess
[image: photograph]

Segayi Andrew
Web Designer & Web Applications Developer
M +256789291217
P +256704277679
E ***@***.***
ThinkITLimited
Plot 120 Semawata Road, Ntinda
Ntinda Semawata Road
www.thinkitlimited.com
[image: linkedin icon]
<https://www.linkedin.com/in/segayi-andrew-3026b8142/>
[image: Banner]

**Comment by michealp-coder** [comment]
> @michealp-coder. Oops, I made the bad assumption that users already have `cargo` installed. Sorry, that's silly on my part. The source is written in Rust, so you'd have to install the cargo toolchain to compile it easily, as you pointed out. If you are still having issues, hang tight, we are about to publish a small blog post on it today that might clear it up a bit.

@JosephTLyons super excited about this functionality, question though.

From the blog post (https://zed.dev/blog/user-themes-now-in-preview), it says:

> Note that you'll need to have the Zed [development toolchain](https://zed.dev/docs/developing-zed) setup locally in order to use the theme importer.

Am I reading the development toolchain correct in that: Postgres, Xcode, and much much more is needed to be installed and setup - just to import in a theme?

I don't want to come across as unappreciative, but doesn't it seem a bit excessive to have to install Postgres and Xcode just to import a theme?

**Comment by silite** [comment]
> > @JosephTLyons , that's super exciting.
> > Question: will this be exposed in the GUI of Zed? I ask because it's not super clear to me how to use that crate from the ReadMe file.
> 
> Yeah, sorry, things aren't documented at the moment. I wasn't on the team who made it and I decided to give it a spin last night. What I did was:
> 
> 1. Found a VS Code theme I liked
> 2. Found the location of that theme package in `~/.vscode/extensions` and found the internal `.json` file
> 3. Did a `cargo run <location_of_theme.json>`
> 4. Copied the contents of the output and placed it into a new file that had this theme family data structure:
> 
> ```json
> {
>     "name": "Some name",
>     "author": "Some author",
>     "themes": [
>             <output_of_theme_importer_here>
>     ]
> }
> ```
> 
> 5. Saved that file into `~/.config/zed/themes`
> 6. Restarted Zed (note that this hasn't hit Preview or Stable yet).
> 
> Sorry this is pretty informal and not great documentation, we will add some instructions and probably streamline the process a bit more going forward.

I've built out the theme json file now, and I'm wondering how to replace the existing theme json, overriding the existing styles to achieve the replacement theme. 
Where is the directory for Zed's theme json file?

**Comment by maxdeviant** [comment]
> > @michealp-coder. Oops, I made the bad assumption that users already have `cargo` installed. Sorry, that's silly on my part. The source is written in Rust, so you'd have to install the cargo toolchain to compile it easily, as you pointed out. If you are still having issues, hang tight, we are about to publish a small blog post on it today that might clear it up a bit.
> 
> @JosephTLyons super excited about this functionality, question though.
> 
> From the [blog post](https://zed.dev/blog/user-themes-now-in-preview), it says:
> 
> > Note that you'll need to have the Zed [development toolchain](https://zed.dev/docs/developing-zed) setup locally in order to use the theme importer.
> 
> And the development toolchain requires: Postgres, Xcode, and much much more to be installed and setup.

The `theme_importer` is runnable with fewer dependencies (the only thing you really _need_ is Rust installed), but because it's in the Zed repo it's possible some other dependencies may need to be present in order to get the building (although Postgres is only needed to build the collab server, which isn't necessary here).

> I don't want to come across as unappreciative, but doesn't it seem a bit excessive to have to install Postgres and Xcode just to import a theme?

At some point we'll have a better "golden path" for importing themes, perhaps even built-in to Zed itself, but for right now the expectation is that to use the `theme_importer` you do have to be able to compile (at least some of) the Zed codebase.

**Comment by JosephTLyons** [comment]
This is now shipped. There might be a bit of friction, since users have to install the necessary tools to compile the importer, but it is technically shipped, so I'm going to close this issue out. We will improve the process going forward to streamline it more, as Marshall said.

**Comment by JosephTLyons** [comment]
> > @michealp-coder. Oops, I made the bad assumption that users already have `cargo` installed. Sorry, that's silly on my part. The source is written in Rust, so you'd have to install the cargo toolchain to compile it easily, as you pointed out. If you are still having issues, hang tight, we are about to publish a small blog post on it today that might clear it up a bit.
> 
> @JosephTLyons super excited about this functionality, question though.
> 
> From the [blog post](https://zed.dev/blog/user-themes-now-in-preview), it says:
> 
> > Note that you'll need to have the Zed [development toolchain](https://zed.dev/docs/developing-zed) setup locally in order to use the theme importer.
> 
> And the development toolchain requires: Postgres, Xcode, and much much more to be installed and setup.
> 
> I don't want to come across as unappreciative, but doesn't it seem a bit excessive to have to install Postgres and Xcode just to import a theme?

We know there is a bit of friction here, but this is the first step to at least getting the ball rolling. Improvements will be made going forward.

**Comment by blackmann** [comment]
Authored a simple VSCode extension to streamline this: https://marketplace.visualstudio.com/items?itemName=degreat.theme-to-zed

It allows to select a theme directly from vscode and export it directly to the zed themes folder.

<img width="1214" alt="Screenshot 2024-02-01 at 11 16 40 PM" src="https://github.com/zed-industries/zed/assets/5024388/6ad0c158-5f35-4677-99bd-a17d2dd03413">

**Comment by JosephTLyons** [comment]
> Authored a simple VSCode extension to streamline this: https://marketplace.visualstudio.com/items?itemName=degreat.theme-to-zed
> 
> 
> 
> It allows to select a theme directly from vscode and export it directly to the zed themes folder.
> 
> 
> 
> No need to download the zed repo and build stuff.
> 
> 
> 
> <img width="1214" alt="Screenshot 2024-02-01 at 11 16 40 PM" src="https://github.com/zed-industries/zed/assets/5024388/6ad0c158-5f35-4677-99bd-a17d2dd03413">
> 
> 
> 
> Here's Monokai in Zed
> 
> <img width="1005" alt="Screenshot 2024-02-01 at 8 47 39 PM" src="https://github.com/zed-industries/zed/assets/5024388/0f987cd4-b587-4b85-a0ef-3540820533b4">
> 
> 
> 
> 

Amazing!!

**Comment by Raees678** [comment]
@blackmann This is awesome. Also by any chance could you share the exported json of your monokai theme? I got some different results with some borders etc missing during my export using your tool (probably because we are using different base themes in VSCode).

**Comment by blackmann** [comment]
[monokai-color-theme.json](https://github.com/zed-industries/zed/files/14138059/monokai-color-theme.json)

@Raees678

**Comment by khanakia** [comment]
Getting this error using this extension  https://marketplace.visualstudio.com/items?itemName=degreat.theme-to-zed

```
Failed to export theme: Default Dark Modern (Error: Command failed: /usr/local/bin/theme_importer "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_modern.json" Error: failed to parse theme "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_modern.json" Caused by: missing field `tokenColors` at line 1 column 4479 )
```

**Comment by Edgar200021** [comment]
> > @JosephTLyons , that's super exciting.
> > Question: will this be exposed in the GUI of Zed? I ask because it's not super clear to me how to use that crate from the ReadMe file.
> 
> Yeah, sorry, things aren't documented at the moment. I wasn't on the team who made it and I decided to give it a spin last night. What I did was:
> 
>     1. Found a VS Code theme I liked
> 
>     2. Found the location of that theme package in `~/.vscode/extensions` and found the internal `.json` file
> 
>     3. Did a `cargo run <location_of_theme.json>`
> 
>     4. Copied the contents of the output and placed it into a new file that had this theme family data structure:
> 
> 
> ```json
> {
>     "name": "Some name",
>     "author": "Some author",
>     "themes": [
>             <output_of_theme_importer_here>
>     ]
> }
> ```
> 
>     5. Saved that file into `~/.config/zed/themes`
> 
>     6. Restarted Zed (note that this hasn't hit Preview or Stable yet).
> 
> 
> Sorry this is pretty informal and not great documentation, we will add some instructions and probably streamline the process a bit more going forward.

To be honest, I have not understood how to run cargo run, from where exactly, there should be a file cargo.toml, can you describe the steps in detail?

**Comment by tarngerine** [comment]
@Edgar200021  you have to follow all the steps from https://zed.dev/docs/development, including cloning the zed repo. then you run that cargo command within the /zed repo

**Comment by an1ndra** [comment]
I have tried to use theme_importer to convert [SpaceBox-color-theme.json](https://github.com/user-attachments/files/17651151/SpaceBox-color-theme.json) theme to Zed theme, but getting `clang` error. Can some one help me to convert it to Zed theme.
```shell
$ cargo run SpaceBox-color-theme.json 
   Compiling proc-macro2 v1.0.89
   Compiling serde v1.0.209
   Compiling libc v0.2.161
   Compiling typeid v1.0.2
error: linking with `clang` failed: exit status: 1
  |
 ```
also tried this `cargo run -p theme_importer -- ~/Downloads/vitesse-dark-soft.json` but same result

**Comment by sipec** [comment]
I got errors with the blackmann's vscode extension above. Anyways I think its overkill to have to set up Rust toolchain just to convert json. So here's a simple node script that I wrote instead

https://gist.github.com/sipec/76678ffc5da38afe96db280401fd1a1c

It breaks if there are any comments and it can only do one file per theme, but it does work. I was able to convert the noctis theme this way.
Would people find it helpful if I published this as an npm package? The script is only 400 lines though and its literally just a mapping from the keys of vscode json format to zed json format. Should be easy for y'all to hack on. If you don't have node you could probably ask just give this to an AI and ask it for a python or bash version.

**Comment by asibahi** [comment]
I used `theme_importer` to import a theme from a json file ([related issue]( https://github.com/vanyauhalin/moondusttheme/issues/5)) and for whatever reason Zed fails to recognize the two files. Also they seem to have a different schema than the ones in https://zed-themes.com/ .
