### ISSUE TITLE
+1 messages notify 44 participants of this issue and are less valuable than thumbs up emoji on the issue itself (it counts in the issue ratings), hence locking the issue to prevent the flood.

### ISSUE THREAD

**Issue by passes0d** [zed-industries/zed#7113]
+1 messages notify 44 participants of this issue and are less valuable than thumbs up emoji on the issue itself (it counts in the issue ratings), hence locking the issue to prevent the flood.

_Originally posted by @SomeoneToIgnore in https://github.com/zed-industries/zed/issues/5347#issuecomment-1910185889_
            
Does locking issue #5347 prevent thumbs up?

**Comment by SomeoneToIgnore** [comment]
Please prefer the GitHub discussions platform for questions.

I think it does prevent adding thumbs up too, it's a limitation of GitHub.
Picking between that and a flood of +1's, I'm fine with the locking.
Also the feature is already one of the topmost upvoted ones, and somebody
