### ISSUE TITLE
Relative terminal links only work relative to project

### ISSUE THREAD

**Issue by porsager** [zed-industries/zed#7144]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Relative links in terminal only looks relative to the project root, but I expected it to look relative to the cwd in the terminal rather than the project root. I actually think both could be nice, where the resolution logic would first try cwd, and then project dir.

### Environment

Zed: v0.120.4 (Zed Preview)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
We use a two staged approach to highlight such links, represented via `NewNavigationTarget` event: https://github.com/zed-industries/zed/blob/ac3b682900f77c978bfed27d7aa15a38f995bb6b/crates/terminal_view/src/terminal_view.rs#L177

both stages (and the only two files that use this enum variant) need adjustments:

1. `terminal.rs` code finds a "word" (matched with regex) hovered in alacritty terminal, and emits the event with the next word it wants to highlight in the UI.
`Terminal` has a `foreground_process_info` with its current directory, we would need to add this to the information, hover updates trigger the `update_selected_word` code path.

2. `terminal_view.rs` needs to check with the new information in mind in `possible_open_targets` and still allow falling back to workspace search in the end

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/7303 has implemented that, comes in the next preview.
