### ISSUE TITLE
Alternative implmentation of the skip-over closing characters feature

### ISSUE THREAD

**Issue by timfjord** [zed-industries/zed#7146]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, Zed follows VSCode and allows to skip over the closing characters only directly after they have been entered.

https://github.com/zed-industries/zed/assets/471335/daa64fe3-cdbf-417e-9cad-f77c787b1f26

https://github.com/zed-industries/zed/assets/471335/24f81a2a-3023-471e-bd40-5331acdee0cc

So if you've moved the cursor you cannot skip over the closing characters anymore.
This approach is a bit limited, especially for those coming from other editors.

Editors like Sublime Text 4 or XCode (and probably others) use a bit different and simpler approach.
Basically, they skip over a closing character every time you type the character that matches the following character.
If `ˇ` is the cursor position, typing `}` three times for `ˇ}}}` text will result in `}}}ˇ` (see ST/Xcode demos below).

----

To provide more flexibility it would be great to support both implementations and control this via the settings(say `always_skip_over_closing_characters`). So when `always_skip_over_closing_characters` is `false`(the default value) it follows the current behaviour, otherwise (when `true`) it follows the ST/Xcode behaviour.

I am happy to send a PR with this feature, as I've already spent some digging around and would love to have this feature implemented.

### If applicable, add mockups / screenshots to help present your vision of the feature

Here is how this feature is implemented in Sublime Text and Xcode

https://github.com/zed-industries/zed/assets/471335/d416c2b4-65c5-4dea-a565-b74b9e177334

https://github.com/zed-industries/zed/assets/471335/6a15dd5c-b950-42e5-b01b-d86f8b6b72c1

**Comment by ConradIrwin** [comment]
This shipped to 0.128.0-pre and will hit stable next week
