### ISSUE TITLE
Assistant API Reset Key is not showing up in command panel

### ISSUE THREAD

**Issue by CodeBreaker0913** [zed-industries/zed#7156]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Step 1. Open Zed
Step 2. Do Shift + Command + P
Step 3. Search Assistant Reset Key
Step 4. Not see it

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Hey there! I just updated the documentation on that here: https://zed.dev/docs/assistant-panel

It works slightly differently than previously described. See the steps:

1. Create an API key
2. Make sure it has credits
3. Open the panel
4. Focus on the panel
5. Open the command palette and execute the `assistant: reset key` action
6. Enter key

**Comment by mrnugget** [comment]
I also just merged a PR that should fix the root problem: https://github.com/zed-industries/zed/pull/7197

Once this is released, I can revert my changes to the docs.
