### ISSUE TITLE
GPT-4 is acually GPT-3 All along

### ISSUE THREAD

**Issue by CodeBreaker0913** [zed-industries/zed#7157]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Step 1. Select GPT-4
Step 2. Ask "Which version of GPT are you"

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Uploading Screenshot 2024-01-31 at 21.54.20.png…]()

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by piercegov** [comment]
This is not an effective way to verify the model version being used as large language models hallucinate. Additionally, as far as I know, the base GPT-4 being used has a training data cutoff before GPT-4 was announced, so it is not 'aware' that GPT-4 has been released. 

GPT-4 is currently using `gpt-4-0613` and GPT-4 Turbo is using `gpt-4-1106-preview` version/api endpoints.

**Comment by clo4** [comment]
Asking the model which model it is won’t be helpful. If reading the source is out of the picture, you can use Proxyman to verify which endpoint it’s actually hitting

**Comment by mrnugget** [comment]
Yep, asking the model itself is not reliable.

You can see in the code which model names we send along with the requests:

https://github.com/zed-industries/zed/blob/5e64d45194e0cd41f36c62fef82bb7273c30e388/crates/assistant/src/assistant_settings.rs#L20-L22
