### ISSUE TITLE
VIM Mode select motion

### ISSUE THREAD

**Issue by Tsolmonx** [zed-industries/zed#7182]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When selecting words with `vf` and any letter i want to go to i cant jump to next instance of word with `;`. But without selecting using just `f` works fine with `;` 
<img width="375" alt="image" src="https://github.com/zed-industries/zed/assets/108046456/bb02af97-03f2-442b-8938-632d1346608b">
Right now in select mode i cant jump to select next instance of letter e 

### Environment

Macos 14.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="375" alt="image" src="https://github.com/zed-industries/zed/assets/108046456/bb02af97-03f2-442b-8938-632d1346608b">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This should be fixed in [0.122.1-pre](https://zed.dev/releases/preview/0.122.1).
