### ISSUE TITLE
Failed to download TOML LSP server

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#7183]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
```console
Language server error: TOML

no asset found matching "taplo-full-darwin-aarch64.gz"
```

Related PR: #7034 

### Environment

Zed: v0.121.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by d1y** [comment]
The same problem, it seems to be the interface limitation of github
<img width="785" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/55e50292-3b64-4698-85f1-6e85dd8c1aa4">

**Comment by TENX-S** [comment]
I guess we should download binaries from the most recent release that has binaries rather than the latest release.
https://github.com/zed-industries/zed/blob/3df7da236d54c0011ae85297e76422bf5a5da486/crates/zed/src/languages/toml.rs#L29-L36

At this time, they have not uploaded the LSP server artifacts yet:
<img width="1358" alt="image" src="https://github.com/zed-industries/zed/assets/40336192/3d9299b7-0d25-4a4f-b7da-9d4690ce29f3">

**Comment by TENX-S** [comment]
> The same problem, it seems to be the interface limitation of github <img alt="image" width="785" src="https://private-user-images.githubusercontent.com/45585937/301387657-55e50292-3b64-4698-85f1-6e85dd8c1aa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjU3MjEsIm5iZiI6MTcwNjc2NTQyMSwicGF0aCI6Ii80NTU4NTkzNy8zMDEzODc2NTctNTVlNTAyOTItM2I2NC00Njk4LTg1ZjEtNmU4NWRkOGMxYWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA1MzAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmM2RmY2E5NjY3YjYzZmZiYmEyNzIwYzhiM2U3MWU1N2I1MTdjMzYwNTZkNTBiOTE4ZjFhYjJjNmJmMDg3YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4cpra-dlod8hHWr0RNNW7AU3wEXjhBlrbVBOg22hE4E">

IMHO, that looks like a problem on your proxy service. Rate limit has nothing to do with zed itself.

**Comment by d1y** [comment]
This repository [tamasfe/taplo](https://github.com/tamasfe/taplo) can confirm whether it has the full binary by matching whether it is released by github-action
<img width="918" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/1e03951d-0b6a-48a7-9848-5740ca881cdc">

<img width="670" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/aeaafb0c-c5e6-471a-aecf-6a9c51e4b369">

**Comment by d1y** [comment]
I think the following way can get the real download link 🤣
```rust
// /crates/util/src/github.rs
    releases
        .into_iter()
        .find(|release| {
            if repo_name_with_owner == "tamasfe/taplo" {
                return release.name.starts_with("Taplo CLI")
            }
            return release.pre_release == pre_release
        })
```

**Comment by TENX-S** [comment]
It may not work after they upload the LSP server artifacts for taplo-cli-0.9.0 🤣(Or you want to write some nasty corner case):
<img width="1141" alt="image" src="https://github.com/zed-industries/zed/assets/40336192/f385ad09-7f34-4c10-820e-6233db0a7a97">

**Comment by codering** [comment]
This just started happening to me!

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/31261
