### ISSUE TITLE
Toggling terminal with Command+J closes the terminal too slow

### ISSUE THREAD

**Issue by Ardivaba** [zed-industries/zed#7190]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Reproduce:**
- Press Command+J twice in quick succession

**Issue:**
- After terminal is shown, it takes a full second to hide it

**Desired behavior:**
- Terminal is hidden immediately, even if it takes time to terminate terminal in the background (completely disconnect it from computer performance)

**Reasoning:**
- Since it's very common for developers to switch between terminal and editor, the experience there should be as smooth as possible

**Edit:**
- Switching between any panel seems to have unnecessary delay, just render previous panel's content into a texture, and show that immediately when switching back, then switch to the real view once real view has finished rendering...it's not a "real" performance gain, but to the user it will definitely feel like that, as they need to re-focus their attention anyways before taking any action when view changes (we're talking about milliseconds here)

### Environment

- M1 Pro 14-inch

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I'm going to leave this open, but I am not seeing any performance issues on my end - deploying that terminal dock feels instantaneous to me. Are you able to capture a video of what you are hitting, @Ardivaba?

**Comment by hhh42** [comment]
I've seen this a few times myself but not every time.  Not sure the specific conditions.

**Comment by mrnugget** [comment]
Does this still happen on the newest versions?

**Comment by giangvo1125** [comment]
> Does this still happen on the newest versions?

I don't see it. It's good for now. Thanks.

**Comment by mrnugget** [comment]
Okay, let's close this issue then and reopen should it occur again.
