### ISSUE TITLE
"file_scan_exclusions" not working in local (folder) settings

### ISSUE THREAD

**Issue by kharenzze** [zed-industries/zed#7195]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Defining "file_scan_exclusions" in a project `.zed/.settings` does not work, it keeps including files in searches.
Defining that array in global settings works perfectly. 

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by danielweck** [comment]
Yes I noticed that too. I had no choice but to create a global `file_scan_exclusions` configuration for __all__ projects / workspaces opened in Zed, which obviously isn't a scalable solutions as the config itself isn't portable from one project to another (different file names / paths, which may in fact conflict).

Related issue:
https://github.com/zed-industries/zed/issues/7071

**Comment by usizu** [comment]
It would be a great and useful feature to have per-project `file_scan_exclusions` settings, to meet the needs of unique project setups.

**Comment by notpeter** [comment]
I just tested this on the current Zed (v0.157.x) and this is now supported.
Thanks for reporting!
