### ISSUE TITLE
IntelliSense / auto-complete not working

### ISSUE THREAD

**Issue by davidruisinger** [zed-industries/zed#7198]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Auto-complete not working
- Go to definition (`CMD` + click) not working

Fresh install using the following settings:
```
{
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "base_keymap": "VSCode",
  "theme": "One Dark",
  "vim_mode": false,
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "tabs": {
    "git_status": true,
  },
}
```

### Environment

Zed: v0.120.5 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature
Comparison with VSCode
![autocomplete](https://github.com/zed-industries/zed/assets/5305150/947d3085-d3e3-42ab-a5da-1a8327562ee8)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14122945/Zed.log)

**Comment by davemaier** [comment]
I have the same Issue. Downloaded zed for the first time today and could not get this working.

**Comment by chris-plato** [comment]
I believe I also have the same issue:

https://github.com/zed-industries/zed/assets/102544583/4a037a62-7b3f-4634-b910-8a788f74fde5

My expectation being that `.` is sufficient to populate the list of predictions.

**Comment by JosephTLyons** [comment]
Hey all, are any of you seeing any errors in the status bar (at the bottom) related to language servers not installing? Do you see any status messages at all when opening these files?

**Comment by davemaier** [comment]
This is what I see in the status bar every time I start zed. If I open a file in another language I see the exactly same thing with the language server of the other language. 

https://github.com/zed-industries/zed/assets/3687869/b0d8a040-e9ff-47eb-beef-5f654ca7fc93

**Comment by davidruisinger** [comment]
> Hey all, are any of you seeing any errors in the status bar (at the bottom) related to language servers not installing? Do you see any status messages at all when opening these files?
I also see some update checks and downloading of language server but seems to be successful

<img width="1573" alt="Screenshot 2024-02-02 at 09 40 52" src="https://github.com/zed-industries/zed/assets/5305150/b19a0cfe-3a87-4ea6-b5f9-22db35948d87">

**Comment by tngan** [comment]
I have found a workaround to get rids of this. I found the language server is not installed properly under the languages folder.

1. Quit zed application
1. Remove the `typescript-language-server` under `~Library/Application Support/Zed/languages`
1. Install manually by `git clone https://github.com/typescript-language-server/typescript-language-server.git` and run `npm install`
1. Re-open zed 

then you can see the autocomplete

**Comment by davemaier** [comment]
I just noticed that I had a `packages.json` file in my home directory and that zed had installed the lsp into the home directory. Removing the `package.json` (and `node_modules` and `package-lock.json`). And then restarting zed fixed the problem for me. 
Found this solution here: https://github.com/zed-industries/zed/issues/4628#issuecomment-1908628375

**Comment by shellscape** [comment]
For those watching this issue, v0.122.1 seems to have fixed this in my projects

**Comment by davidruisinger** [comment]
> For those watching this issue, v0.122.1 seems to have fixed this in my projects

Same for me. Working with the latest update 🙌🏻

**Comment by chris-plato** [comment]
Is this considered a different issue?:
https://github.com/zed-industries/zed/issues/7198#issuecomment-1922438299

It has been months and yet this still does not work properly in `Zed 0.140.5`

**Comment by Bishwas-py** [comment]
For elixir, auto complete suddenly stops working. `Zed  dev 0.142.0, fedora`

**Comment by chris-plato** [comment]
Not sure what to do here, I started to create a new issue by the same name, because the title for this well describes my issue; however then I read:
> Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a +1 (👍) on it.

This leads me to think I should just drop _yet another_ comment on this issue.

I have recently gotten a new macbook, and this problem still plagues me:
https://github.com/zed-industries/zed/issues/7198#issuecomment-1922438299

I keep trying Zed, hoping to adopt it as my main editor, but stuff like this is too disruptive to ignore.

Please let me know if I should create a whole new issue for this, or if this is sufficient 🙇

**Comment by JohnGalt1717** [comment]
This isn't working in the latest version using C#.

**Comment by wagnrd** [comment]
I am experiencing the same issue. But this seems only to happen when typing only one letter or the whole thing very fast. On hover you get the info, though.
https://github.com/user-attachments/assets/2a749ccf-4543-4c47-957c-2434be87bb0c

**Comment by SharafatKarim** [comment]
Using `zed 0.149.5` on Arch Linux, and not working at all. Even auto complete in it's own setting isn't working.

**Comment by afonsomatos** [comment]
I don't have autocomplete either, and using Typescript.

**Comment by branilaa** [comment]
I have the exact same issue with the latest version of zed on arch linux

**Comment by finnar-bin** [comment]
Just experienced a similar issue as well. Over time the lsp seems to bog down and eventually just stopping to provide autocompletions and other functionality. Had to manually restart the lang servers and it seem to have resolved the issue. I'll keep an eye out if it starts to slow down again.

**Comment by hermann-p** [comment]
Same here, not autocomplete, no eslint, no prettier. Is there a way to show zed's logs/errors?

NixOS 24.05
Zed 0.149.6

**Comment by hermann-p** [comment]
> Same here, not autocomplete, no eslint, no prettier. Is there a way to show zed's logs/errors?
> 
> NixOS 24.05 Zed 0.149.6

Ok, I'll take it back. Zed does simply not pick up existing language servers from `$PATH`, so on nix you have to use a workaround and [launch it from an FHS-environment](https://github.com/NixOS/nixpkgs/issues/309662#issuecomment-2316118392) so it will install its own lsp-servers.

**Comment by LeilaVerbeeck** [comment]
Autocomplete also doesn't work for me

OS: Fedora 40
Zed 0.150.4

**Comment by SharafatKarim** [comment]
> Edit: When I check the LSP logs, I can see for example the tailwind lsp start up properly but the phpactor server logs are empty.
Can you please tell me how to do so? So that I can try myself.

**Comment by DemianAvila** [comment]
Linting and autocomplete is not working with golang

OS: Debian GNU/Linux 12 (bookworm) x86_64
 Zed: 0.152.3

**Comment by koknese** [comment]
> Linting and autocomplete is not working with golang
> 
> OS: Debian GNU/Linux 12 (bookworm) x86_64 Zed: 0.152.3

Same issue here but with every language

Arch Linux x86_64 
Zed 0.152.4-1

**Comment by albertdugba** [comment]
I'm also having the same issue

**Comment by nicolascavallin** [comment]
Same issue with 0.160.7

**Comment by RomanMIzulin** [comment]
after update to 0.162.5 my python pyright previously perfectly working config got broken

**Comment by SuperKenVery** [comment]
Same on 0.163.2, Using `editor: show completions` works perfectly but completion just won't show up when normally typing.

**Comment by jamshid17** [comment]
> after update to 0.162.5 my python pyright previously perfectly working config got broken

Can you share your pyright config? I am having the same issue on mac

**Comment by LeilaVerbeeck** [comment]
How come this thread is closed? Still seems to be broken.

**Comment by chris-plato** [comment]
Zed's dead @LeilaVerbeeck... Zed's dead.

**Comment by SuperKenVery** [comment]
Zed has improved a lot in the past year. Maybe check your LSP logs in the bottom-left corner? It looks like a lightning icon.

<img width="211" height="162" alt="Image" src="https://github.com/user-attachments/assets/7428d5a6-186f-476b-bb1f-bde213a3f548" />
