### ISSUE TITLE
it should be possible to compile Zed without providing GitHub credentials to LiveKit

### ISSUE THREAD

**Issue by slymax** [zed-industries/zed#7202]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed can't currently be compiled without granting access to github.com credentials in the macOS keychain for LiveKit

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="999" alt="screenshot" src="https://github.com/zed-industries/zed/assets/3922572/8a95f2a5-4745-4b48-964f-d9c872c58ef2">

**Comment by notpeter** [comment]
I believe this has been fixed.
If you are still seeing this, please comment and I'm happy to reopen.
Thanks for reporting!
