### ISSUE TITLE
Make cursor shape configurable

### ISSUE THREAD

**Issue by unorsk** [zed-industries/zed#7203]
### Check for existing issues

- [X] Completed

### Describe the feature

Block cursor is currently only available in vim mode.
It would be nice to have this as a configurable option, so it could be changed in settings to "block", "underline" etc

**Comment by xzhseh** [comment]
Just to mention, it would be nice if the terminal cursor could be configurable as well - e.g., I can freely adjust my cursor shape to either `Block` or `Beam` for my local alacritty configuration, but not in zed. (yes, I know zed comes with an integrated terminal emulator that uses alacritty as its backend, but that does not allow me to configure any setting related to cursor)
