### ISSUE TITLE
Add support for column selection mode

### ISSUE THREAD

**Issue by lpicanco** [zed-industries/zed#7215]
### Check for existing issues

- [X] Completed

### Describe the feature

Could you add support for column selection mode?

Examples: 
- https://www.jetbrains.com/help/idea/multicursor.html#column_selection
- https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection

**Comment by JosephTLyons** [comment]
Hey @lpicanco, Zed does have column selection, holding `opt-shift` and performing a cursor drag should get you there:

https://github.com/zed-industries/zed/assets/19867440/ee4794bb-59cb-4830-851b-a72f1b4e9926

**Comment by zacharysyoung** [comment]
@JosephTLyons, can a key binding be configured (instead of having to use the pointing device and dragging)?

**Comment by JosephTLyons** [comment]
> @JosephTLyons, can a key binding be configured (instead of having to use the pointing device and dragging)?

Are you looking for `editor: add selection below` and `editor: add selection above`? Those will add 1 new cursor either above or below the current one.  From there, you can can use `shift-left` or `shift-right` (and a combination of `opt` or `cmd`)  to select horizontally.

https://github.com/zed-industries/zed/assets/19867440/87638e9f-c3fb-4f47-9499-ee9c3ebf719d

You can customize the keybindings in your `keymap.json` file:

```json
{
  "context": "Editor",
  "bindings": {
    "cmd-alt-down": "editor::AddSelectionBelow",
    "cmd-ctrl-n": "editor::AddSelectionBelow",
  }
}
```

**Comment by zacharysyoung** [comment]
@JosephTLyons, that's great, I'll take it! Thank you.

**Comment by malomalo** [comment]
@JosephTLyons Sorry but are you saying it's not possible to configure column select to behave like default on MacOS TextEdit / TextMate?

I would like `opt` to be column select and `opt-shift` to be multi cursor.

The Keybindings don't work well if a line in the selection is shorter or longer. It will skip that line entirely if to short. And `shift+arrow` will flow to the next line and get jank if the end of line don't align  :/

**Comment by dcog989** [comment]
This was posted a month after this ticket: https://zed.dev/blog/text-manipulation

```
column-based selection - alt-shift-mouse-drag
```

I find it works best by positioning cursor at start then `Alt+Shift+Left Click` at end point.

**Comment by joelberkeley** [comment]
I asked on discord https://discord.com/channels/869392257814519848/1509014232568561694
