### ISSUE TITLE
JS add jsdoc highlighting support

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#7224]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/tree-sitter/tree-sitter-jsdoc
<img width="688" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/b7039365-0bc0-4c3e-a34f-fc27d7ca56a1">

**Comment by ConradIrwin** [comment]
This shipped to 0.128.0-pre and will hit stable next week
