### ISSUE TITLE
Community: `awesome` repo

### ISSUE THREAD

**Issue by shellscape** [zed-industries/zed#7225]
In the same spirit of the `Positive Feedback` issue, I'd like to suggest an `zed-industries/awesome` repository following the excellent guidelines by sindre https://github.com/sindresorhus/awesome/blob/main/awesome.md

This would be a great way to let users submit their themes (and plugins when they drop) without having to build a marketplace or website around that. It would surely help fuel collaboration and help grow the library of themes available.

**Comment by JosephTLyons** [comment]
Hey @shellscape, we do intend to build out a theme and plugin store, but I think the idea of an `awesome` repo makes sense. I'll get a super basic one started here shortly and add a link to it.

**Comment by JosephTLyons** [comment]
Here is the link:

- https://github.com/zed-industries/awesome/settings
