### ISSUE TITLE
Not able to format some JSON files

### ISSUE THREAD

**Issue by amesas** [zed-industries/zed#7227]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I try to format some medium sized json files, the format command does nothing.

Syntax Highliting works, just JSON does not get formatted.

### Environment

Zed 0.121

### If applicable, add mockups / screenshots to help explain present your vision of the feature

JSON should get formatted.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by matejcerny** [comment]
From my experiments it looks like only saved files can be formatted, which is a bummer 😞

**Comment by eproxus** [comment]
This is tracked in #4529 (I think)

**Comment by Moshyfawn** [comment]
Saved files are formatted correctly and @eproxus is right (thanks!), the issue is already being tracked.

**Comment by Moshyfawn** [comment]
Duplicate of #4529

**Comment by KaKi87** [comment]
Hello,
I don't understand how the linked issue solves this ?
I'm not trying to install a custom formatter.
Thanks
