### ISSUE TITLE
Support custom fetch github api use self Token

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#7233]
### Check for existing issues

- [X] Completed

### Describe the feature

When a large amount of access to the github api will be restricted, you need to configure the token yourself.
> #7183 Causes requests to continue until restricted by github (403)

<img width="747" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/6a5ce04d-7ce7-49c3-9987-5ebb9f64baec">

> https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28

There are two things to do:

1. Add an option to set `github-token` globally in the settings
2. Bring this token in our request👀

```bash
curl --request GET \
--url "https://api.github.com/octocat" \
--header "Authorization: Bearer YOUR-TOKEN" \
--header "X-GitHub-Api-Version: 2022-11-28"
```

**Comment by d1y** [comment]
At least we are relying on github services now. Will we host those lsp-servers on zed-self-host in the future? (Just asking🤔)

**Comment by jansol** [comment]
#7219
