### ISSUE TITLE
formatting (on save) using standardjs formatter wipes out js file content completely

### ISSUE THREAD

**Issue by ricochenft** [zed-industries/zed#7238]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have `standardjs` installed via
`npm I -g standard` and I can confirm I can format a js file without issues. For example
`standard --fix some_file.js` would format `some_file.js` according to the standardjs styles. 

I have the js formatter settings as followed:
```js
  "language_overrides": {
    "JavaScript": {
      "format_on_save": {
        "external": {
          "command": "standard",
          "arguments": ["--fix", "{buffer_path}"]
        }
      }
    }
  }
```

It works as expected that zed is able to format a js file without problems right after I made the above changes. However, if I quit zed, re-open it and try to edit and save a js file. its content got wiped out completely. I've seen the behavior in the previous release as well.

### Environment

Zed: v0.120.5 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

see description

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-01T17:44:56 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-01T17:47:53 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-01T17:47:53 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition

**Comment by itsmewes** [comment]
Could this be a similar issue to https://github.com/zed-industries/zed/issues/4477#issuecomment-1922751590, where the external formatter relies on stdout instead of the file being updated by the formatter.

**Comment by ricochenft** [comment]
@itsmewes  What I found out is the opposite actually. The `prettier` example given by the zed doc (https://github.com/zed-industries/zed/blob/main/docs/src/languages/javascript.md) works because it outputs the formatted text to stdout. On the other hand `standard` changes the target files directly (with `--fix` option). `prettier-standard` exhibits the same behavior as `standard` since it doesn't output to stdout like `prettier` does. It appears that external formatting works only if the program sends output to stdout. For that matter, I am wondering if there's a zed setting to support in-place formatting.

**Comment by itsmewes** [comment]
> @itsmewes What I found out is the opposite actually. The `prettier` example given by the zed doc (https://github.com/zed-industries/zed/blob/main/docs/src/languages/javascript.md) works because it outputs the formatted text to stdout. On the other hand `standard` changes the target files directly (with `--fix` option). `prettier-standard` exhibits the same behavior as `standard` since it doesn't output to stdout like `prettier` does. It appears that external formatting works only if the program sends output to stdout. For that matter, I am wondering if there's a zed setting to support in-place formatting.

What I meant is what you have outlined 😊 Zed expects any external formatters to output the result to stdout and since the formatters we are using don't output anything or outputs diagnostics, what gets updated in the file isn't correct.

**Comment by midnightcodr** [comment]
You are totally right. I should have read your comment more carefully  😄 

Maybe some time in the future zed can support the tools that we mentioned, but for now I am using this work-around for js formatting, in case anyone is interested
```json
  "language_overrides": {
    "JavaScript": {
      "format_on_save": {
        "external": {
          "command": "prettier",
          "arguments": ["--stdin-filepath", "--no-semi", "{buffer_path}"]
        }
      }
    }
  }
```

**Comment by ricochenft** [comment]
You are totally right. I should have read your comment more carefully  😄 

Maybe some time in the future zed can support the tools that we mentioned, but for now I am using this work-around for js formatting, in case anyone is interested
```json
  "language_overrides": {
    "JavaScript": {
      "format_on_save": {
        "external": {
          "command": "prettier",
          "arguments": ["--stdin-filepath", "--no-semi", "{buffer_path}"]
        }
      }
    }
  }
```

**Comment by AndydeCleyre** [comment]
OHHH. Thanks! I've been struggling to figure this out with a different external formatter for Python. It would be great to have this (IMO unexpected) behavior mentioned in the tooltip description of `formatter.external.command`!
