### ISSUE TITLE
"Search inside" doesn't work for multi-folder work

### ISSUE THREAD

**Issue by abejfehr** [zed-industries/zed#7242]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you open Zed and add multiple folders via right-clicking in the tree view and saying "Add Folder to Project": right-clicking on the folder root and saying "Search inside" doesn't add a filter that works on the search page

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

in VSCode I'm able to do "./my-repo/src" as the filter and it _only_ looks inside the `my-repo` folder in the project, even when I've added many separate folders

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by abejfehr** [comment]
Here's a screenshot indicating what the "Project search" page looks like after having clicked "Search inside"
<img width="1344" alt="image" src="https://github.com/zed-industries/zed/assets/3917428/2a4256ed-39d9-4ddc-baa6-bbbf4191a8a0">

**Comment by mikey-** [comment]
On Zed 0.154.2 for macOS (25e2e9c6727ba9b77415588cfa11fd969612adb7): Right clicking on a folder and selecting "Find in folder" now opens up a new project search with the path to the selected folder as a filter. 

Also, when opening up a new project search (without selecting a folder), it's possible to "toggle filters" to show the filters (and add your own).

Is that the same for you @abejfehr?

**Comment by notpeter** [comment]
I can no longer reproduce this and it appears to be working as expected.

**Comment by mikey-** [comment]
Can confirm that it is working as expected for me too :) Thanks
