### ISSUE TITLE
Invalid sorting of history items in File finder

### ISSUE THREAD

**Issue by alygin** [zed-industries/zed#7244]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a project with three files `1.txt`, `2.txt`, `3.txt`:
1. Open files in the numerical order
2. Switch tabs in the reverse order: `3.txt`, `2.txt`, `1.txt`
3. Open File finder (`Cmd+P`)

Expected: `2.txt` is the second item in the list (because it was previously selected).
Actual: `3.txt` is the second item in the list.

The erroneous behaviour was introduced in this PR: https://github.com/zed-industries/zed/pull/7210
Here's a test that reproduces the bug: https://github.com/alygin/zed/commit/18bb2109b7832f6278717635dccea5788ed292e7

### Environment

Zed: v0.122.0 (Zed Dev)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Erroneous behavour:

https://github.com/zed-industries/zed/assets/2101250/efbb3d96-228a-4dec-830d-35515a6ddb7d

Expected behaviour:

https://github.com/zed-industries/zed/assets/2101250/ff35882f-dbf0-42f2-9565-099008bfba65

**Comment by SomeoneToIgnore** [comment]
Great find, you definitely have a good eye for tests.
I think, we should swap the comparison of paths https://github.com/zed-industries/zed/pull/7210/files#diff-eac7c8c99856f77cee39117708cd1467fd5bbc8805da2564f851951638020842R257 to the reverse one and it will fix the issue.

Would you want to try and create the PR?

**Comment by SomeoneToIgnore** [comment]
```diff
diff --git a/crates/file_finder/src/file_finder.rs b/crates/file_finder/src/file_finder.rs
index 5880ec465..be3d2feb8 100644
--- a/crates/file_finder/src/file_finder.rs
+++ b/crates/file_finder/src/file_finder.rs
@@ -1,7 +1,7 @@
 #[cfg(test)]
 mod file_finder_tests;
 
-use collections::HashMap;
+use collections::{HashMap, HashSet};
 use editor::{scroll::Autoscroll, Bias, Editor};
 use fuzzy::{CharBag, PathMatch, PathMatchCandidate};
 use gpui::{
@@ -222,9 +222,11 @@ impl Matches {
         query_matches: Option<&'a HashMap<Arc<Path>, ProjectPanelOrdMatch>>,
         history_items: impl IntoIterator<Item = &'a FoundPath> + 'a,
     ) {
-        let history_items_to_show = history_items
+        let mut processed_paths = HashSet::default();
+        self.history = history_items
             .into_iter()
             .chain(currently_opened)
+            .filter(|&path| processed_paths.insert(path))
             .filter_map(|history_item| match &query_matches {
                 Some(query_matches) => Some((
                     history_item.clone(),
@@ -232,31 +234,22 @@ impl Matches {
                 )),
                 None => Some((history_item.clone(), None)),
             })
-            .sorted_by(|(path_a, match_a), (path_b, match_b)| {
-                match (
+            .enumerate()
+            .sorted_by(
+                |(index_a, (path_a, match_a)), (index_b, (path_b, match_b))| match (
                     Some(path_a) == currently_opened,
                     Some(path_b) == currently_opened,
                 ) {
+                    // bubble currently opened files to the top
                     (true, false) => cmp::Ordering::Less,
                     (false, true) => cmp::Ordering::Greater,
-                    _ => match_b.cmp(match_a),
-                }
-            });
-
-        self.history.clear();
-        util::extend_sorted(
-            &mut self.history,
-            history_items_to_show.collect::<Vec<_>>(),
-            100,
-            |(path_a, match_a), (path_b, match_b)| match (
-                Some(path_a) == currently_opened,
-                Some(path_b) == currently_opened,
-            ) {
-                (true, false) => cmp::Ordering::Less,
-                (false, true) => cmp::Ordering::Greater,
-                _ => match_b.cmp(match_a).then(path_b.cmp(path_a)),
-            },
-        );
+                    // arrange the files by their score (best score on top) and by their occurrence in the history
+                    // (history items visited later are on the top)
+                    _ => match_b.cmp(match_a).then(index_a.cmp(index_b)),
+                },
+            )
+            .map(|(_, paths)| paths)
+            .collect();
     }
 }
 
@@ -319,7 +312,7 @@ fn matching_history_item_paths(
     matching_history_paths
 }
 
-#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
+#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
 struct FoundPath {
     project: ProjectPath,
     absolute: Option<PathBuf>,
```

This is the fix, I believe:
* we do not need another sorting when there's itertools
* we need to sort history items by their order of appearance in addition to the rest of the ordering criteria

@alygin wdyt? Does not seem to break the new (and existing) tests.

**Comment by alygin** [comment]
> Does not seem to break the new (and existing) tests.

@SomeoneToIgnore, yep, tests are green with this fix. Paths comparison swapping alone didn't solve the issue.
