### ISSUE TITLE
make Context Window resizable and make it movable around!

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#7247]
### Check for existing issues

- [X] Completed

### Describe the feature

This feature will add the chance to move and resize context window of variable and other data structure as the user wants

**Comment by JosephTLyons** [comment]
Hey @Iovans, just to clarify, which window are you wanting to be resizable / movable?

**Comment by Iovans** [comment]
When you hover a variabile or the api it shows the info

**Comment by JosephTLyons** [comment]
Ok, I understand now. Thanks for clariying. :)

**Comment by Iovans** [comment]
How Is called that Window?
