### ISSUE TITLE
Hover doc Markdown links in RustDoc comments do nothing, don't open browser or go to link.

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/zed#7250]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Add a rustdoc comment above a struct (`/// [Base16](https://github.com/chriskempson/base16)`
2. Hover over the struct and click the link
3. boom - expected: the link opens in some browser

@JosephTLyons I did look for another issue but didn't find an obvious one, feel free to merge in if it is a dupe.

![CleanShot 2024-02-01 at 17 15 33@2x](https://github.com/zed-industries/zed/assets/1714999/d076cf8d-31b8-4159-b8e6-8c62bcaf0901)

### Environment

Zed: v0.122.0 (Zed Nightly)
OS: macOS 14.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

N/A

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

N/A

**Comment by t1gu1** [comment]
Not sure if it's kind of the same issue that i got.
I test the pre-release and they seems to have fix the problem.

If you want to test: https://github.com/zed-industries/zed/releases/tag/v0.121.1-pre

**Comment by mrnugget** [comment]
Also works for me on latest Nightly:

https://github.com/zed-industries/zed/assets/1185253/138e8006-c749-4b40-abce-1f5f2c715f0a

**Comment by iamnbutler** [comment]
Nice – might be fixed then. I'll close and re-open if I hit it again!
