### ISSUE TITLE
Vim - Custom key bindings - space & leader

### ISSUE THREAD

**Issue by t1gu1** [zed-industries/zed#7255]
### Check for existing issues

- [X] Completed

### Describe the feature

I would love to be able to use `space` for vim shortcuts.

Example:
```json
{
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "space-e": "workspace::ToggleLeftDock"
    }
 }  
```

---

Another point is that could be nice that we could define a **<leader> key** in the **settings** and simply reuse it with the `leader` keyword in the Custom key bindings.

Example:
```json
{
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "leader-e": "workspace::ToggleLeftDock"
    }
 }  
```

**Comment by ConradIrwin** [comment]
@t1gu1 You can already use space, the syntax is `"space e": "workspace::ToggleLeftDock"`. 

I'm not sure about adding specific leader key; obviously you can already get what you want by just editing your settings file.

One option would be as part of #7033 to allow something like: `",": [SimulateInput, "leader"]` and then let you use "leader" as though it were a key in your bindings.

If you want to pair on making something like this a reality (or just with help getting your keybindings perfect), book time here: https://calendly.com/conradirwin/pairing.

**Comment by t1gu1** [comment]
Thanks! It works!

I didn't see anywhere in the documentation spacing between commands of a key binding as `"space e"`
So it was just not intuitive for me to try that.

Oh, i just found that: <https://github.com/zed-industries/zed/blob/main/assets/keymaps/vim.json>
It was hidden in the Predefined keymaps of that section: <https://zed.dev/docs/key-bindings>

My bad.
Thx again.

**Comment by ConradIrwin** [comment]
I added some more documentation here: https://zed.dev/docs/key-bindings, does that clarify?
