### ISSUE TITLE
Missing rename keybinding in JetBrains binding

### ISSUE THREAD

**Issue by litsynp** [zed-industries/zed#7261]
### Check for existing issues

- [X] Completed

### Describe the feature

I noticed that `rename` feature is missing when using `JetBrains` keybinding. Perhaps it's because it's missing from https://github.com/zed-industries/zed/blob/b35a722/assets/keymaps/jetbrains.json ?

It works fine after I added these lines:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "shift-f6": "editor::Rename"
    }
  },
  {
    "context": "ProjectPanel",
    "bindings": {
      "shift-f6": "project_panel::Rename"
    }
  }
]
```

If it's ok, I'd make a PR for this.

**Comment by JosephTLyons** [comment]
Yes! Feel free to make a PR. :)
