### ISSUE TITLE
Can't open folder

### ISSUE THREAD

**Issue by duke-git** [zed-industries/zed#7264]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to select and open a project folder, zed hangs there, I can do nothing, but kill it. Reopen the editor to do same , it happened again and again. see screenshot.

<img width="1486" alt="image" src="https://github.com/zed-industries/zed/assets/5037603/1a0bfc27-9669-47bb-ac2a-6ba38749fc9a">

### Environment

Macos 12.6

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @duke-git, can you check you the zed log and see if there are any relevant errors in there?

`~/Library/Logs/Zed/Zed.log`

**Comment by duke-git** [comment]
Hi @JosephTLyons, I try again and get the zed log, it seem to be the downloading copilot issue. How to aviod it?

zed log screenshot:
<img width="1660" alt="image" src="https://github.com/zed-industries/zed/assets/5037603/81da2ac1-a8c3-4034-80af-39eaf06cc82e">

**Comment by JosephTLyons** [comment]
Hmm, strange. I'm not sure that that would be related. Does the issue happen when opening all folders, or just that specific one (`~/Documents`)?

**Comment by duke-git** [comment]
It happened when opening all folders. But it works now, after I restarted my computer and updated the version of zed.

**Comment by JosephTLyons** [comment]
Since we didn't observe this issue coming up for others, I'm going to assume it's some extreme edge case or no longer valid and close it out. If you run into it again, feel free to open a new issue.
