### ISSUE TITLE
Vim mode: using "space" as a leader key sometimes doesn't activate

### ISSUE THREAD

**Issue by SamHep0803** [zed-industries/zed#7270]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

From time to time, if a custom keybinding uses space as a "leader key", the default behaviour will still occur, meaning that the custom keybinding will not fire correctly. For example, if the binding is "space o t" in order to focus the terminal panel, sometimes the default binding for space (which moves the cursor to the right by one character) is triggered, meaning that the other keys pressed (o and t) are fired as normal, which will create a new line and insert the letter t.

### Environment

Zed: v0.121.1 (Zed Preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
We do have a timeout of 1sec in which you need to hit the following keys. Do you think you might run into this? Or do you have any other steps to reproduce?

**Comment by SamHep0803** [comment]
That's the thing, there is no 1sec timeout because it immediately just uses the default binding. I'll get a quick screencap of this.

**Comment by SamHep0803** [comment]
https://github.com/zed-industries/zed/assets/14109339/355f9373-bbe1-43ad-918a-3b4753165c78

Here I'm using the "space o t" keybind I referred to in my original comment.

**Comment by SamHep0803** [comment]
Not quite sure then, bare in mind this isn't just an issue with the `space o t` keybind, for me this is happening regardless of the letters after `space` is hit.

**Comment by SamHep0803** [comment]
Okay, weird. After a restart it seems to be working fine now. Sorry for the inconvenience!

**Comment by SamHep0803** [comment]
Apologies, thought this was fixed after a reboot, but no such luck.
