### ISSUE TITLE
Multiple commands with the same key (vim_mode), how to achieve it if possible 

### ISSUE THREAD

**Issue by viniciuspalma** [zed-industries/zed#7274]
### Check for existing issues

- [X] Completed

### Describe the feature

I currently have this keymap on neovim, where I scroll down but at the same time centralize the cursor:

```lua
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
```

How could I achieve the same on zed?

I tried something like:

```json
      "ctrl-u": ["vim::ScrollUp", "editor::ScrollCursorCenter"],
      "ctrl-d": ["vim::ScrollDown", "editor::ScrollCursorCenter"]
```

But without success, there's a way to execute multiple commands in the same keybinding?

**Comment by JosephTLyons** [comment]
I dont think this is possible at the moment, but maybe my info is out of date here. cc @ConradIrwin

**Comment by ConradIrwin** [comment]
This is currently not possible, but it is the number one feature request for vim at the moment :D.  We're tracking it here: #7033.

If you'd like to pair with me on building it, please book time here: https://calendly.com/conradirwin/pairing!

**Comment by christofferbergj** [comment]
This was closed as completed, but I can't work out how to actually do it. 
I feel I've tried everything:

```json
  "ctrl-u": ["vim::ScrollUp", "editor::ScrollCursorCenter"],
  "ctrl-d": ["vim::ScrollDown", "editor::ScrollCursorCenter"],

  "ctrl-u": ["workspace::SendKeystrokes", "ctrl-u z z"],
  "ctrl-d": ["workspace::SendKeystrokes", "ctrl-d z z"],

  "ctrl-u": ["workspace::SendKeystrokes", ": scroll up enter z z"],
  "ctrl-d": ["workspace::SendKeystrokes", ": scroll down enter z z"],

  "ctrl-u": ["workspace::SendKeystrokes", ": scroll up enter : scroll cursor center enter"],
  "ctrl-d": ["workspace::SendKeystrokes", ": scroll down enter : scroll cursor center enter"]
  
"ctrl-u": ["DispatchActions", ["vim::SrollUp"], ["editor::ScrollCursorCenter"]],
"ctrl-d": ["DispatchActions", ["vim::SrollDown"], ["editor::ScrollCursorCenter"]]
```

🤷‍♂️😀

**Comment by ConradIrwin** [comment]
@christofferbergj Ugh, sorry this is so hard to use!

We currently don't have a "noremap" equivalent so you can't override an existing key and call that keys definition (yet...).

One workaround for now would be to do this in two passes, one to set a new definition for ctrl-d/ctrl-u and then the other to add the zz:

```
      "ctrl-shift-u": "vim::ScrollUp",
      "ctrl-shift-d": "vim::ScrollDown",
      "ctrl-u": ["workspace::SendKeystrokes", "ctrl-shift-u z z"],
      "ctrl-d": ["workspace::SendKeystrokes", "ctrl-shift-d z z"
```

**Comment by christofferbergj** [comment]
@ConradIrwin 

Thanks! That works! 
I use Vim bindings but have never really delved into understanding how the different mapping modes actually work. 

But this makes sense. Hope a "noremap" equivalent will make its way into Zed eventually. 👍

**Comment by qborisb** [comment]
> ```json
>       "ctrl-u": ["vim::ScrollUp", "editor::Scrol
> ```

Would love to make the same bindings, but when using "n" in search mode, mapping it to "n" -> "n zz", but seems like it is not possible at the moment to map a key binding to `vim::MoveToNextMatch` (or previous match)?

**Comment by ConradIrwin** [comment]
Hmm. It should be possible...

You'll need to do the same intermediate-mode thing I talked about above:

```
 "ctrl-shift-n": "vim::MoveToNextMatch",
 "n": ["workspace::SendKeystrokes", "ctrl-shift-n z z"],
```

**Comment by qborisb** [comment]
@ConradIrwin I get the following warning if I use vim::MoveToNextMatch:

![Screenshot 2024-04-18 at 14 32 10](https://github.com/zed-industries/zed/assets/54835674/44b7ec78-e9d8-4f3c-b211-d680994c5f1e)

**Comment by MostHated** [comment]
Is there a reason that this would not work with ctrl+s when in insert mode to save and the leave insert mode?

```jsonc
// Insert mode
{
  "context": "Editor && vim_mode == insert && !VimWaiting && !menu",
  "bindings": {
    "atl+s": "workspace::SaveWithoutFormat",
    "ctrl+s": ["workspace::SendKeystrokes", "alt+s escape"]
  }
},

```

**Comment by patrykk21** [comment]
On the latest zed version this is working for me

```
      "ctrl-u": ["workspace::SendKeystrokes", "ctrl-u z z"],
      "ctrl-d": ["workspace::SendKeystrokes", "ctrl-d z z"]
```

However any way to keep the jumps? Corresponding vim command would be 

`nnoremap <C-d> :keepjumps normal! <C-d><CR>`

**Comment by ConradIrwin** [comment]
We don't have any jumplist control yet. Would be nice to add something.

Also the Zed jump list is quite a bit different to the vim jump list; not sure how much I want to change that (as it mostly seems to work well) but there are some edge-cases where more control would be nice.
