### ISSUE TITLE
Support `documentation` as a provider for `completionItem/resolve`

### ISSUE THREAD

**Issue by huwaireb** [zed-industries/zed#7288]
### Check for existing issues

- [X] Completed

### Describe the feature

👋

Currently some LSPs e.g `ocamllsp` (support merged in #6929) don't send documentation on the completionItem request, but instead require clients to resolve them. As a result, there's no documentation sent for completion items as of right now.

<img width="1346" alt="Screenshot 2024-02-02 at 20 16 58" src="https://github.com/zed-industries/zed/assets/69181766/0b163732-270c-43f8-8932-8e36ba4d1713">

This is a valid use case per the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion): 
>If computing full completion items is expensive, servers can additionally provide a handler for the completion item resolve request (‘completionItem/resolve’). This request is sent when a completion item is selected in the user interface. A typical use case is for example: the [textDocument/completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) request doesn’t fill in the documentation property for returned completion items since it is expensive to compute.

There seems to be some implementation already, but it's not officiated. I'm wondering if someone is willing to explain the degradation that caused it to be omitted, since adding "documentation" to the list of [resolve_support of completion](https://github.com/zed-industries/zed/blob/cf4f3ed79acc361e470ad8cff11ea1d98e20ae81/crates/lsp/src/lsp.rs#L560C1-L566C28) works. I wouldn't mind fixing it.

**Comment by SomeoneToIgnore** [comment]
> I'm wondering if someone is willing to explain the degradation that caused it to be omitted

If that's a reference to the missing client capabilities in the lsp.rs, most probably it had been just missed when implemented initially.
If it really just works by adding another bit and does not break any documents for existing "main" language supports like Rust, let's definitely add that!

**Comment by huwaireb** [comment]
> > I'm wondering if someone is willing to explain the degradation that caused it to be omitted
> 
> If that's a reference to the missing client capabilities in the lsp.rs, most probably it had been just missed when implemented initially. If it really just works by adding another bit and does not break any documents for existing "main" language supports like Rust, let's definitely add that!

Sounds great, but just in case:

I think there was  a reference to the documentation provider for completionItem/resolve here https://github.com/zed-industries/zed/issues/6367#issuecomment-1908739488

would you mind double checking with @ForLoveOfCats if this is related?

**Comment by SomeoneToIgnore** [comment]
@ForLoveOfCats is welcome to chime in and correct me, but here's what I see:

That comment seems to indicate the fact that we did query a lot of completions, and never bothered to cancel their resolve requests, even if the user typed more on top.

I do not think that removing things from the capabilities is a good way to solve it, related or not — and I do not think it's related.
And even if it is — we cannot stay in this status quo and never resolve any completions at all as this issue indicates — so we need a better design then.

Also: 
* https://github.com/zed-industries/zed/pull/3391 completion resolutions are being canceled now? Same date as the comment mentioned, and no capabilities amended due to that fix
* https://github.com/zed-industries/zed/pull/7115 and completions are throttled down on typing, and again, no capabilities touched

So, while this task needs some exploration and checking that completions did not regress for multiple servers (checking them all now gets hard, but Rust and another one should be checked), it's not blocked, and neither editing lsp.rs is blocked.

**Comment by huwaireb** [comment]
> @ForLoveOfCats is welcome to chime in and correct me, but here's what I see:
> 
> That comment seems to indicate the fact that we did query a lot of completions, and never bothered to cancel their resolve requests, even if the user typed more on top.
> 
> I do not think that removing things from the capabilities is a good way to solve it, related or not — and I do not think it's related. And even if it is — we cannot stay in this status quo and never resolve any completions at all as this issue indicates — so we need a better design then.
> 
> Also:
> 
> * [zed2(ish) Cancel completion resolution when new list #3391](https://github.com/zed-industries/zed/pull/3391) completion resolutions are being canceled now? Same date as the comment mentioned, and no capabilities amended due to that fix
> * [Add debounce for re-querying completion documentation #7115](https://github.com/zed-industries/zed/pull/7115) and completions are throttled down on typing, and again, no capabilities touched
> 
> So, while this task needs some exploration and checking that completions did not regress for multiple servers (checking them all now gets hard, but Rust and another one should be checked), it's not blocked, and neither editing lsp.rs is blocked.

All valid points that make absolute sense! How would you like to proceed? It's just the addition of a single string, would you like me to open a PR or will you do it? 

I actually had it in the OCaml PR, but i mistook some other regressions for it so i removed it ;p

**Comment by ForLoveOfCats** [comment]
Whoops! Yeah I just overlooked that, my bad 😅 Thanks for figuring it out!
