### ISSUE TITLE
Editor hover popover can be dismissed by moving the mouse between them

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#7304]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently requires very precise cursor movement to prevent it fading away, and with some cursors like the I-beam, it goes away even when the cursor appears to be touching the tooltip. 

Also, crossing an error tooltip to get to the symbol info tooltip requires a perfect and rapid motion because of the gap between the two.

### Environment

Zed: v0.121.2 (Zed Preview)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Video here:

https://github.com/zed-industries/zed/issues/8401
