### ISSUE TITLE
Upgrade nodejs so unneeded nodejs files aren't downloaded

### ISSUE THREAD

**Issue by koramangalacode** [zed-industries/zed#7308]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Unneeded nodejs files are being downloaded, wasting data for those stuck with metered internet 
#6803
https://github.com/nodejs/node/issues/46451

### Environment

macOS

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
Looking at the linked Node issue (https://github.com/nodejs/node/issues/46451), it seems like those files are still present in the Node distributions?

I only saw mention of removing them from the Docker images, which Zed does not use.

**Comment by koramangalacode** [comment]
I'm not sure how but those files end up on my mac and someone else has confirmed it happens to them too.

#7054

**Comment by maxdeviant** [comment]
Zed installs the Node runtime when it is needed for certain language servers, and those files are distributed with Node, AFAICT.

**Comment by maxdeviant** [comment]
This is blocked on upstream changes in Node, so going to close it out as there's nothing for us to do at the moment.
