### ISSUE TITLE
Unable to sign in to Copilot

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#7309]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to sign in to Copilot, the sign in window appear and is truncated but I can't do anything and after this process Copilot is not connected to my account.

### Environment

Zed: v0.121.2 (Zed Preview)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/24520681/4e78cc6e-4d30-4c47-be20-f251a2e8dcf8

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-03T00:17:36+01:00 [INFO] ========== starting zed ==========
2024-02-03T00:17:36+01:00 [INFO] Opening main db
2024-02-03T00:17:36+01:00 [ERROR] crates/zed/src/main.rs:103: login shell exited with error
2024-02-03T00:17:37+01:00 [ERROR] crates/zed/src/zed.rs:519: EOF while parsing a value at line 1 column 0
2024-02-03T00:17:37+01:00 [INFO] Opening main db
2024-02-03T00:17:37+01:00 [INFO] set status on client 0: Authenticating
2024-02-03T00:17:37+01:00 [INFO] set status on client 73682: Connecting
2024-02-03T00:17:37+01:00 [INFO] Opening main db
2024-02-03T00:17:37+01:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-02-03T00:17:37+01:00 [INFO] add connection to peer
2024-02-03T00:17:37+01:00 [INFO] waiting for server hello
2024-02-03T00:17:37+01:00 [INFO] got server hello
2024-02-03T00:17:37+01:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 327, id: 251356 })
2024-02-03T00:17:37+01:00 [INFO] set status on client 73682: Connected { peer_id: PeerId { owner_id: 327, id: 251356 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }

**Comment by JosephTLyons** [comment]
Thanks for the report @Tom-Boscher. This is very strange. I can see the state that your copilot modal is frozen in on my side, as it looks like it flashes from that state, then into a the full modal for me. I'll see if we can find a way to reproducet this.

**Comment by mrnugget** [comment]
@Tom-Boscher this might be completely unrelated, but I want to get this out of the way: in the log messages above it prints an error because Zed can't start your login shell to get its environment variables (it also prints an error because you have a syntax error in your keymap, but _that_ I think is really unrelated).

Can you try to manually run the command?

First, what is `$SHELL?`: run ` env | grep SHELL`

Then, run the following command with `$SHELL`: `$SHELL -lic 'echo ZED_LOGIN_SHELL_START && /usr/bin/env -0'`

Does that work? If not, what does it say?

**Comment by Tom-Boscher** [comment]
I use **Nushell**, `$SHELL` is `/opt/homebrew/bin/nu`

Using **Nushell** I have a syntax error:
```
~> /opt/homebrew/bin/nu -lic 'echo ZED_LOGIN_SHELL_START && /usr/bin/env -0'
                                                                   
Error: nu::parser::missing_flag_param

  × Missing flag argument.
   ╭─[source:1:1]
 1 │ nu -lic
   ·    ──┬─
   ·      ╰── flag missing string argument
   ╰────
   ```
   
   But if I use **Zsh** I have this:
   
   ```
   ~> zsh -lic 'echo ZED_LOGIN_SHELL_START && /usr/bin/env -0'

ZED_LOGIN_SHELL_START
ALACRITTY_WINDOW_ID=4294967297CMD_DURATION_MS=14COLORTERM=truecolorCOMMAND_MODE=unix2003DIRS_POSITION=0HOME=/Users/tomLAST_EXIT_CODE=1LC_ALL=en_US.UTF-8LOGNAME=tomLaunchInstanceID=4D570375-BE28-414E-BDB0-0CDE80730AC8NU_LOG_DATE_FORMAT=%Y-%m-%dT%H:%M:%S%.3fNU_LOG_FORMAT=%ANSI_START%%DATE%|%LEVEL%|%MSG%%ANSI_STOP%NU_VERSION=0.89.0OLDPWD=/Users/tomPATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/binPWD=/Users/tomSECURITYSESSIONID=186b3SHELL=/opt/homebrew/bin/nuSHLVL=0SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZSEXkPewrj/ListenersTERM=xterm-256colorTMPDIR=/var/folders/vf/szyq6yw97hq73rtm09v25g_80000gn/T/USER=tomWINDOWID=4294967297XPC_FLAGS=0x0XPC_SERVICE_NAME=0ZED_TERM=true__CFBundleIdentifier=dev.zed.Zed-Preview__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1HOMEBREW_PREFIX=/opt/homebrewHOMEBREW_CELLAR=/opt/homebrew/CellarHOMEBREW_REPOSITORY=/opt/homebrewMANPATH=/opt/homebrew/share/man::INFOPATH=/opt/homebrew/share/info:_=/usr/bin/env
   ```

**Comment by Tom-Boscher** [comment]
Btw, after a factory reset I still encounter this error, maybe it's due to **Nushell**

**Comment by mrnugget** [comment]
Thanks! That's very helpful.

**Comment by mrnugget** [comment]
I have a fix for the Nushell env not loading here: https://github.com/zed-industries/zed/pull/7442 But that doesn't guarantee that Copilot will work.

When you start Zed from the command line (using `zed .`, for example) -- what happens then? Because if launched from CLI it doesn't try to load the env, but uses the env from the command line.

**Comment by clo4** [comment]
LOL I think I figured it out, I was running into this too. I don't know if it's the same root cause, but if you have `"show_copilot_suggestions": false` in your settings, the copilot server is disabled, so when the modal is created, it gets a status of `Disabled` and doesn't render anything https://github.com/zed-industries/zed/blob/5c8073d3444eb17254e59f6740e48256079dbf38/crates/copilot_ui/src/sign_in.rs#L151-L164

**Comment by clo4** [comment]
@Tom-Boscher Can you check your settings (command-,) and see if there's anything related to copilot in there? Also worth checking your workspace to see if there's a hidden `.zed` directory, because that might also be setting your settings to disable copilot. Try deleting any settings related to it and try signing in again.

**Comment by Tom-Boscher** [comment]
@clo4 Well, it was indeed due to `"show_copilot_suggestions": false`! Thanks a lot for your help!

**Comment by Kapaak** [comment]
I still have this issue even when I set show_copilot_suggestions: true. The "Connect to Github" button does nothing".

**Comment by Moshyfawn** [comment]
> I still have this issue even when I set show_copilot_suggestions: true. The "Connect to Github" button does nothing".

Which version of Zed are you on? If it's `0.127.3` or `0.128.0`, the bug has been identified and fixed in [`0.128.1`](https://zed.dev/releases/preview/0.128.1).

**Comment by Kapaak** [comment]
> > I still have this issue even when I set show_copilot_suggestions: true. The "Connect to Github" button does nothing".
> 
> Which version of Zed are you on? If it's `0.127.3` or `0.128.0`, the bug has been identified and fixed in [`0.128.1`](https://zed.dev/releases/preview/0.128.1).

I see that the latest stable version is still 0.127x , the fixed version is currently only on preview.

**Comment by Moshyfawn** [comment]
> I see that the latest stable version is still 0.127.3 (which I have downloaded) , the fixed version is currently only on preview.

Gotcha. The the fix to Stable will be released in a bit.

**Comment by agjini** [comment]
Hi,
I'm experiencing the same bug. The copilot sign in modal seems to be stuck.

I'm running manjaro i3 - Zed 0.152.4.

No error in logs.

![2024-10-22_09-27](https://github.com/user-attachments/assets/7733230b-61f0-4d3d-9c91-820680927bb0)

Is it a regression ?

**Comment by fogzot** [comment]
This is happening to me too, on version 0.206.6 (f6695400b1463d0be8f2ed13589446da41541b90, Linux).
I attach my config and log files.

[Zed.log](https://github.com/user-attachments/files/22679891/Zed.log)

[settings.json](https://github.com/user-attachments/files/22679898/settings.json)

**Comment by bkniffler** [comment]
Same for me under macOS. Seems copilot can't start.
```
2025-10-07T12:31:47+02:00 INFO  [copilot] Checking Node.js version for Copilot at: "/Users/bkniffler/.volta/bin/node"
2025-10-07T12:31:47+02:00 INFO  [copilot] Node.js version 20.19.1 meets Copilot requirements (>= 20.8.0)
2025-10-07T12:31:47+02:00 INFO  [lsp] starting language server process. binary path: "/Users/bkniffler/.volta/bin/node", working directory: "/", args: ["/Users/bkniffler/Library/Application Support/Zed/copilot/node_modules/@github/copilot-language-server/dist/language-server.js", "--stdio"]
2025-10-07T12:31:47+02:00 ERROR [lsp] cannot read LSP message headers
2025-10-07T12:31:47+02:00 ERROR [lsp] Server reset connection for a request "initialize" id 0
2025-10-07T12:31:47+02:00 ERROR [lsp] Broken pipe (os error 32)
2025-10-07T12:31:47+02:00 ERROR [lsp] Shutdown request failure, server copilot (id 0): server shut down
2025-10-07T12:31:47+02:00 ERROR [copilot] copilot hasn't started yet
2025-10-07T12:32:11+02:00 WARN  [lsp::input_handler] failed to deserialize LSP message:
{"jsonrpc":"2.0","result":{}}
```

Also tried to delete `~/Library/Application Support/Zed/copilot` and reinstall. But doesn't work.

**Comment by maximvl** [comment]
Same here on macOS, copilot doesn't work anymore

PS fixed in recent update
