### ISSUE TITLE
vim mode: it's good to flashing yanked selections once, so users can know which lines they yanked.

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#7311]
### Check for existing issues

- [X] Completed

### Describe the feature

I think it's good to highlight on yanked, it's useful if user yank through `Y`, e.g: `3Y`, `5Y`.

Then user knows if he made a corrent yank.

It can be powered by the following config in neovim:
https://github.com/nvim-lua/kickstart.nvim/blob/7af594fd319fbae6b2aaa06337f3df8acbbb7f18/init.lua#L347-L354

### If applicable, add mockups / screenshots to help present your vision of the feature

This is how it works in neovim:
[![asciicast](https://asciinema.org/a/cS5MmG3ymJApkk6KHMxT3vRDk.svg)](https://asciinema.org/a/cS5MmG3ymJApkk6KHMxT3vRDk)

**Comment by ConradIrwin** [comment]
Nice! I like this idea.

If you want to pair with me feel free to book time: https://calendly.com/conradirwin/pairing (and I hope the call works better this time!).

It doesn't seem to be built into vim, are you using https://github.com/machakann/vim-highlightedyank or similar?

**Comment by WindSoilder** [comment]
Sure, I just submit to calendly.

> It doesn't seem to be built into vim, are you using https://github.com/machakann/vim-highlightedyank or similar?

Not really sure about vim, but we can config them inside neovim.(sorry for pointing out wrong lines in the link previously)
```lua
local highlight_group = vim.api.nvim_create_augroup('YankHighlight', { clear = true })
vim.api.nvim_create_autocmd('TextYankPost', {
  callback = function()
    vim.highlight.on_yank()
  end,
  group = highlight_group,
  pattern = '*',
})
```
