### ISSUE TITLE
regression: unresponsive window when building `master`, related to #7305

### ISSUE THREAD

**Issue by claytonrcarter** [zed-industries/zed#7318]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I pulled `master` this morning, rebased my local branches and ran `cargo run`. The build succeeded, but the resulting window is unresponsive to key input, clicks, etc. The "Window" menu *says* that there is a file open, but the window only shows the title bar & status bar, w/ no file browser or open files. Opening files, projects, etc doesn't do anything. The status bar is stuck saying "Checking for Zed updates...".

Suspecting my local changes were at fault, I checked out `master` and tried again ... same thing. I did some manual bisecting and landed on commit 15edc46 (from #7305) as the culprit. Everything seems to work fine when building the parent commit, f2ba969.

### Environment

Zed: v0.122.0 (Zed Dev)
OS: macOS 14.3.0
Memory: 64 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="800" src="https://github.com/zed-industries/zed/assets/1420419/b7e61cbe-b811-4991-800c-8b18b9b41a53">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

I removed my `Zed.log` and reran the build, but after closing the non-responsive window the log file is still empty.

**Comment by as-cii** [comment]
Hey @claytonrcarter, thanks for the report. Can you double check we're getting updates from the display link? You can do that by applying the following diff to the current main (54aecd21ecc80642eed28a897b5e4760a69e89cd):

```diff
diff --git a/crates/gpui/src/window.rs b/crates/gpui/src/window.rs
index 19ed1c909..0d13eeb39 100644
--- a/crates/gpui/src/window.rs
+++ b/crates/gpui/src/window.rs
@@ -348,7 +348,9 @@ impl Window {
             let dirty = dirty.clone();
             let last_input_timestamp = last_input_timestamp.clone();
             move || {
+                println!("requested frame");
                 if dirty.get() {
+                    println!("  was dirty");
                     measure("frame duration", || {
                         handle
                             .update(&mut cx, |_, cx| {
@@ -358,6 +360,7 @@ impl Window {
                             .log_err();
                     })
                 } else if last_input_timestamp.get().elapsed() < Duration::from_secs(2) {
+                    println!("  underclock debounce");
                     // Keep presenting the current scene for 2 extra seconds since the
                     // last input to prevent the display from underclocking the refresh rate.
                     handle.update(&mut cx, |_, cx| cx.present()).log_err();
```

**Comment by claytonrcarter** [comment]
Happy to help! OK, I just:
1. `git checkout master`
1. applied patch
2. `cargo run` - built, opened and printed first 2 lines
3. Menu: File > New - opened new empty window and printed next 3 lines
4. Closed that and re-did File > New - opened new empty window and printed last 2 lines
```
requested frame
  was dirty
requested frame
  was dirty
[2024-02-03T08:54:13-05:00 ERROR util] crates/gpui/src/window.rs:408: window not found
requested frame
  was dirty
```

Clicking buttons, pressing keys, etc doesn't emit any more output.

**Comment by alygin** [comment]
I've got the same problem. I noticed that editor displays main UI elements after resizing the main window, but the application still remains unresponsive:

https://github.com/zed-industries/zed/assets/2101250/e64f6d48-0d75-42a8-bf4d-0e828890f367

**Comment by SomeoneToIgnore** [comment]
Thanks for spotting, that was a very recent commit, and it's reverted for now.

**Comment by SomeoneToIgnore** [comment]
One thing that I found strange: on my M1 Max laptop that commit works just fine, but on my M1 Pro macMini it did not work.
It would be interesting to know what configurations were affected, please share yours if you want to.

**Comment by as-cii** [comment]
Hey @alygin and @claytonrcarter, we merged another pull request that should re-introduce the improvements without the bug you were seeing. It would be great if could give `main` another try to confirm things work correctly now. Thank you! 🙏

**Comment by alygin** [comment]
@as-cii, for me, the current `main` works perfectly now. Thanks!

**Comment by claytonrcarter** [comment]
Yes, It works for me too. Thank you!

**Comment by as-cii** [comment]
Amazing! Thank you both so much for the feedback! ✨
