### ISSUE TITLE
Show Autocomplete with respective file paths

### ISSUE THREAD

**Issue by Tsolmonx** [zed-industries/zed#7324]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="563" alt="image" src="https://github.com/zed-industries/zed/assets/108046456/8946d732-d0ee-40e7-bce2-33be3f5ae3f2">
I guess we all will be writing same functions in different file a lot and autocomplete shows with respective file path will help a lot to select the ones that i want.

**Comment by JosephTLyons** [comment]
Hey @Tsolmonx, I think this request is similar to these, so I'm going to close it out. Feel free to add a comment if there's something else I'm missing and I will reopen this:

- https://github.com/zed-industries/zed/issues/7099
- https://github.com/zed-industries/zed/issues/4457
