### ISSUE TITLE
Text selection highlight color

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#7333]
### Check for existing issues

- [X] Completed

### Describe the feature

I it is great to see user custom themes implemented. I am loving it! However, I cannot find the field that is responsible for the selected text highlight color, i.e.
![Screenshot 2024-02-03 at 12 35 31 PM](https://github.com/zed-industries/zed/assets/4711498/525a22ef-3e64-4284-a7ed-06485cb34d52)
It can be seen, the highlight is light blue, I would like to make it yellowish. Feature/attribute to be able to change it would be invaluable. 

### If applicable, add mockups / screenshots to help present your vision of the feature

The results i would like to see is something like this, where I am able to define the color of the <b>selected</b> `foreground` text (in this case black) as well as `background` color (in this case yellow):
![Screenshot 2024-02-03 at 12 37 40 PM](https://github.com/zed-industries/zed/assets/4711498/d7a73684-a275-4859-9ab0-99ef03e759e0)

**Comment by maxdeviant** [comment]
The selections are controlled by the player colors in the theme.

The first player is the one we use for selections when not collaborating: https://github.com/zed-industries/zed/blob/a80a3b8706b83e70476ed4a89252b3324edfb391/crates/theme/src/styles/players.rs#L124-L126

**Comment by krstp** [comment]
Great, this is what I was looking for. Thanks much for the pointer.
Side note: I did try it before, but I guess I wasn't getting the result I was expecting or possibly latest updates did solve.

Needless to say, still the foreground color on the selection/highlight portion is missing. However, I am glad with what I have at the moment. Color differentiation actually plays well here. Thanks.
