### ISSUE TITLE
Python: allow Docstring coloring different than other "strings"

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#7346]
### Check for existing issues

- [X] Completed

### Describe the feature

This is request to enable different Docstring coloring vs. other "strings". I say strings, because currently ZED does not differentiate between any regular string definition and Docstring. I would rather expect Docstring to be recognized to similar coloring as in-line comments or perfectly a separate color block.

### If applicable, add mockups / screenshots to help present your vision of the feature

Current status of _Docstring_ coloring: see attached screenshot. Notice `log` string statement has the same color as the `"""` _Docstring_ text. IMHO, those two should definitely have separate colors. Notice also coloring of the in-line comment. I would sooner expect _Docstring_ to have similar coloring to the comment text.
![Screenshot 2024-02-03 at 4 56 29 PM](https://github.com/zed-industries/zed/assets/4711498/92f8bc91-b295-4160-b198-b915f2e75cae)

What I would perfectly want to achieve:
![proposed](https://github.com/zed-industries/zed/assets/4711498/ad182feb-2669-425e-ba86-bed4cb973809)

**Comment by jansol** [comment]
I'd argue that docstrings should be considered doc comments for the purpose of syntax highlighting

**Comment by krstp** [comment]
This is fine, all I care about is ability to specify diff color between those two.

**Comment by krstp** [comment]
Reference to similar ticket: https://github.com/zed-industries/zed/issues/4296

**Comment by jansol** [comment]
I specifically mentioned that because the user themes that landed in preview builds last week *do* have separate styles for "comment" and "comment.doc". So this would just be a matter of making the tree sitter definition categorize the doc strings correctly.

**Comment by krstp** [comment]
Yeah, I've seen it.
Needless to say it is not clear to me what `comment.doc` does affect. At least on `python` level I do not see it affecting code or any comments in any way. Thanks though for reiterating this.

**Comment by maxdeviant** [comment]
I took a stab at this in https://github.com/zed-industries/zed/pull/7585 and was able to get it working.

However, after a bit of further investigation, it seems that treating docstrings as comments/doc comments from a syntax highlighting perspective is a bit of a contentious topic, and both GitHub and VS Code seem to call on the side of treating them as strings.

While I don't think treating docstrings as comments _by default_ is the right choice, it does seem like a desirable feature to be able to style them separately, should you want to.

I ended up introducing a new `string.doc` syntax node for docstrings in https://github.com/zed-industries/zed/pull/7587.

By default, Python docstrings will be displayed using the `string` styles, but if you add a `string.doc` in your theme it will take precedence and allow you to style docstrings separately from strings.

**Comment by krstp** [comment]
Thank you for taking care of this. And yes, this is what I had in mind. Can't wait to test it out with next release 🙏

**Comment by tommydangerous** [comment]
Is this live? I don’t see mt obe able to get it to work.

**Comment by Gedaria** [comment]
> Is this live? I don’t see mt obe able to get it to work.

Yes. Although the default themes don't seem to use nor have a `string.doc` parameter under , thus defaulting to the `string` color/style.

For my particular theme, I added these:

```
"string.doc": {             //
    "color": "#69676c",     // These lines
    "font_style": "italic"  // in particular
}, 
```

So that my docstring styles match my comment style.

**Comment by NoahMenezes** [comment]
I am working on updating the Python test runnable queries in crates/grammars/src/python/runnables.scm to support pytest functions ending with _test (e.g. login_test()) in addition to functions starting with test_. Will open a PR shortly!
