### ISSUE TITLE
Integrated Terminal Crashes Immediately

### ISSUE THREAD

**Issue by r0mankeys** [zed-industries/zed#7349]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I attempt to open the integrated terminal (after having launched the app using the desktop client) it immediately crashes.

_I must stress that this works perfectly when launching Zed through the CLI, which leads me to believe this problem stems from Zed not being able to resolve my shell environment, however, I don't know how to fix this_

Steps I take:
1. Open Zed through the desktop client
2. Press keys: cmd + ` (I have also tried using the "+" icon in the top right corner)

### Environment

- Installation: Installed using homebrew
- MacOS version: Sonoma 14.2.1
- Shell: zsh (MacOS default)
- Shell Config: Configured with "Oh My ZSH"

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
It is very hard to understand what's causing this issue by just the description.
Do you see any backtraces or other unusual things in the ~/Library/Logs/Zed/Zed.log ? 
Sharing that might be helpful.

**Comment by mrnugget** [comment]
@r0mankeys can you reliably reproduce this? If so, can you try to comment out your `.zshrc` bit by bit and see what in it causes it to crash?

Also, to be clear: it "only" crashes the terminal, right? Zed still works, I assume?

**Comment by r0mankeys** [comment]
> @r0mankeys can you reliably reproduce this? If so, can you try to comment out your `.zshrc` bit by bit and see what in it causes it to crash?
> 
> 
> 
> Also, to be clear: it "only" crashes the terminal, right? Zed still works, I assume?


I will try that thank you, and yes Zed functions normally it's only the integrated terminal crashing

**Comment by megatux** [comment]
It's happening here too, on Linux. Downloaded today Zed. From command palette I can create terminal panels but if I try to use ctrl+` it crashes.

**Comment by notpeter** [comment]
Without logs this is not something we can diagnose.

If you are still experiencing this consistently, please open a new issue that includes steps which trigger the issue and a copy of your logs.  Thanks for reporting.
