### ISSUE TITLE
Editor is always opening in full screen 

### ISSUE THREAD

**Issue by ashuvssut** [zed-industries/zed#7358]
### Describe the bug / provide steps to reproduce it

The Zed editor consistently opens in fullscreen mode, and I prefer it to open in a non-fullscreen mode. I am seeking assistance in configuring the editor to open in a windowed or non-fullscreen state by default.

### Environment

MacOS Sonoma

**Comment by jerrygreen** [comment]
I would actually prefer to open Zed in full-screen 🙈
How to do that? I ain't seeing any option in settings

**Comment by ashuvssut** [comment]
Zed always opens with the same window size as in your previous session. For instance, if you closed Zed while it was in fullscreen mode, the next time you open Zed, it will be restored to fullscreen.

**Comment by jerrygreen** [comment]
Well in my case it seems it is broken as my Zed always opens in windowed mode, and I constantly have to put it to fullscreen manually.

**Comment by ashuvssut** [comment]
@jerrygreen you might be having an old version of Zed.
See the following video. For me. Zed always opens with the same window size as in my previous session. 

https://github.com/zed-industries/zed/assets/60546840/e15ece25-1b29-4129-a771-634171be6774


My zed version is `0.133.7`

**Comment by jerrygreen** [comment]
Uhhh, I get that. That's not version, we simply call «fullscreen» two different things.

What you show on your recording – simply resizing window, manually. My zed also supports that, no difference.

What I mean by fullscreen – the feature when you click green button at top-left of the window. It automatically resizes to fullscreen, and moves it to separate virtual desktop. Zed doesn't remember this state.

**Comment by alexpyattaev** [comment]
I'd love to somehow have Zed do the reasonable thing and go full screen when opened in a non-tiling WM, at least have that as a tunable in settings... As a workaround, on KDE you can force this behavior through window rules from the window manager side.

**Comment by rajerthat1** [comment]
same issue

**Comment by bendytree** [comment]
Not pretty, but here's a BetterTouchTool apple script to exit fullscreen when Zed opens:
https://gist.github.com/bendytree/48faf9d112cf2e5d5903f4d7bb402635

+1 for a config setting to avoid the fullscreen behavior:

```
  "window": {
    "x": 100,
    "y": 50,
    "width": 1280,
    "height": 800
  }
```
