### ISSUE TITLE
Project search gets stuck in Searching ...

### ISSUE THREAD

**Issue by kanatti** [zed-industries/zed#7360]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Project search is not working for any text. It gets suck in `Searching...`.

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 13.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-02-04 at 12 24 37 PM](https://github.com/zed-industries/zed/assets/8623654/38ef1be6-5d97-4723-8000-57a96257d2a4)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14157699/Zed.log)

**Comment by razvan-warden** [comment]
+1

**Comment by JosephTLyons** [comment]
We had a potential fix land for this issue, so I'm going to close this issue out. If the bug is still reproducible in or after v0.151.0, please open another issue.
