### ISSUE TITLE
High memory usage - system prompt to close applications

### ISSUE THREAD

**Issue by pknaus3** [zed-industries/zed#7361]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I opened my $HOME directory in Zed which was in background running, after 15minutes (Maybe less) I got system prompt to close applications due high memory usage where ZED was winning with 28GB of RAM (Most of the usage went to SWAP, thanks god). Attaching screenshot with the message
<img width="454" alt="image" src="https://github.com/zed-industries/zed/assets/47193837/68e293c4-d19f-452b-83ac-dc307dc0ddad">

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Thanks for the report. That seems very unfortunate... I'm wondering: did you see in the logs whether it started a language server?

**Comment by JosephTLyons** [comment]
Related issue:

- https://github.com/zed-industries/zed/issues/6027

**Comment by HarishBaskaran-FW** [comment]
still facing this issue 

Environment
Zed: v0.136.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: M1 chip aarch64

**Comment by mrnugget** [comment]
@HarishBaskaran-FW can you reproduce and have reliable steps to reproduce?

**Comment by notpeter** [comment]
Closing as inactive.  If you have steps to reproduce and are seeing this with a current Zed version, please open a new issue and happy to dive in.
