### ISSUE TITLE
Autoupdate does not autosave focused editor

### ISSUE THREAD

**Issue by ttiimm** [zed-industries/zed#7365]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Enable the setting `"autosave": "on_focus_change"`.
2. Have an unsaved editor open.
3. Autoupdate by by clicking in the bottom left corner of the editor.

Expected result: The focused unsaved editor is saved before the autoupdate occurs.
Actual result: The contents was unsaved and an older version of the file was re-open on start up.

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 13.6.3
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by artemijan** [comment]
I suppose autosave should happen if you click the mouse in any place (not only on focus change), meaning you stopped typing and now using mouse (touchpad) to do something else, so it should save current state.

**Comment by notpeter** [comment]
We serialize the state of unsaved changes now and persist that across restarts, so we should no longer result in data loss when applying an update. Thanks for reporting.
