### ISSUE TITLE
Search matches text is hard to read

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#7368]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While making a buffer search, the matches text is hard to read, it happened in most of themes.

![图片](https://github.com/zed-industries/zed/assets/22256154/b73602af-a635-42bc-8f68-908ef7d9fd77)

### Environment

Zed: v0.121.2 (Zed Preview)
OS: macOS 13.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
This should be addressed by #7382 and #7385.
