### ISSUE TITLE
status bar icons aren't properly aligned

### ISSUE THREAD

**Issue by slymax** [zed-industries/zed#7374]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="256" alt="screenshot" src="https://github.com/zed-industries/zed/assets/3922572/2ff53830-f80f-403d-9a02-860e1e2bb753">

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
I think this has to do with the sizing of the icons themselves.

**Comment by wzxu** [comment]
Glad I'm not the only one driven crazy by the icons' slight variations in size and alignment whenever I take a look at them. 😅

**Comment by iamnbutler** [comment]
![CleanShot 2024-10-03 at 13 55 17@2x](https://github.com/user-attachments/assets/7178de1f-19ef-4331-a18a-c54454b7790c)

This looks old. Closing.
