### ISSUE TITLE
zed cli should not create files

### ISSUE THREAD

**Issue by ConradIrwin** [zed-industries/zed#7400]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently if you do `zed x.txt` and `x.txt` does not exist; the CLI will create an empty file with that name, and then open it with Zed.

I would like for the cli to open a new buffer with that name, that is not created until I save in Zed.

This most frequently happens to me when I am trying to do autocomplete in bash, so I do `zed Car<tab><enter>` and end up with a new file called `Cargo.` in the directory.

Related to #4441.

### Environment

Zed: v0.122.0 (Zed Dev)
OS: macOS 14.2.1
Memory: 128 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Seems like this was done on purpose in https://github.com/zed-industries/zed/pull/2049. I guess the underlying problem is that we can't have a named buffer in Zed that isn't saved, right?

**Comment by ConradIrwin** [comment]
Yeah, I think it'll need that to fix it. My read of the discussion at #2049 was that this was a compromise to let you create new files at all

**Comment by avetisk** [comment]
It would be great to follow `code` (VS Code) and thus not only create a buffer with the given filename, but also create the whole path is not existing.

E.g: `zed /some/path/that/does/not/exists.ts`

When `exists.ts` is saved, `/some/path/that/does/not` should be created (e.g `mkdir -p PATH`).
