### ISSUE TITLE
Terminal: cursor doesn't blink until I press a key

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/zed#7401]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I added this to the settings json:

```json
  "terminal": {
    "blinking": "on"
  }
```

And cursor doesn't blink unless I type something in the terminal.

### Environment

Zed: v0.121.3 (Zed Preview)
OS: macOS 13.6.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/199648/d0df54a7-9d5f-46db-b127-c2afcbaf124e

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Thanks for reporting! I fixed it in #7428, which will go out with a Preview release this week and a stable release next week (or maybe we'll cherry-pick before)
