### ISSUE TITLE
vim: zt/zg should make current line goto the top/bottom of view

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#7415]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In normal mode: pressing `zt` or `zb` doesn't make current line go to the top and bottom of view :-(

![图片](https://github.com/zed-industries/zed/assets/22256154/63a94cf1-010e-4ded-a58d-4d83d1c72c3c)

![图片](https://github.com/zed-industries/zed/assets/22256154/71830b32-e590-49c1-bfb6-d44ff8434ef3)

It's trivial, but sometimes it's also annoying.

### Environment

Zed: v0.121.3 (Zed Preview)
OS: macOS 13.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is how it works in meovim:

![图片](https://github.com/zed-industries/zed/assets/22256154/394684c0-fe97-4036-9fba-3ee39f00674a)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
:wave: Thanks for reporting @WindSoilder! 

I think this will be fixed by tomorrow's preview release if you set `"vertical_scroll_margin": 0` in your zed configuration.

Currently zed always acts as though you had `:scrolloff=3` in vim.

Please let me know if this is not the case!
