### ISSUE TITLE
vim: Allow alactritty vim mode

### ISSUE THREAD

**Issue by NukaCody** [zed-industries/zed#7417]
### Check for existing issues

- [X] Completed

### Describe the feature

Alacritty has a vim mode option and it seems like y'all use alacritty as the embedded terminal. Is there an option to enable vim mode movements when the terminal is focused?

**Comment by ConradIrwin** [comment]
@NukaCody this is an interesting idea!

One of the problems we ran into recently was wanting to make `ctrl-w down` go to the terminal pane; but unfortunately `ctrl-w` is already used for the terminal; so you can't go back.

The way vim solves this is to have the terminal be modal too (you can do `i` to get into terminal mode and `ctrl-\ ctrl-n` to leave).

Is this what you're imagining, or is it something else?

**Comment by mrnugget** [comment]
I think what they're referring to is Alacritty's vi mode: https://github.com/alacritty/alacritty/blob/master/docs/features.md#vi-mode Ever used tmux and used its `ctrl-b [` scrollback mode where you can navigate through your terminal with keybindings? That's similar, except it's built into Alacritty.

**Comment by NukaCody** [comment]
What mrnugget mentioned was what I was referring too but honestly any mechanism that allows the ability to find error message or json output in the terminal message and "yank" it to system clipboard is neat. The inspiration came from how jonhoo navigates his terminal during rust streams.

**Comment by NukaCody** [comment]
Giving this a try over the next couple weekends: https://github.com/zed-industries/zed/discussions/18555

**Comment by mrnugget** [comment]
> Giving this a try over the next couple weekends: #18555

I wonder whether there isn't a better, more holistic approach: instead of implementing a vi-mode inside the terminal, I've long thought about whether it wouldn't be possible to turn the terminal itself into a buffer/editor and back again, so that we could use Vim/Zed mode to edit/navigate. Kinda like neovim's built-in terminal.

**Comment by NukaCody** [comment]
I wouldn't have the first clue where to start lol. I get where you're coming from though, something like the AI assistant panel except terminal.
