### ISSUE TITLE
Delete open projects from the list

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#7426]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be possible to add the function that allows you to delete a project that has been opened from the list of open projects.

**Comment by SomeoneToIgnore** [comment]
Linking the discussion here: https://github.com/zed-industries/zed/discussions/6703#discussioncomment-8281516

Seems that we have all building blocks to call the actual remove and what's needed is some UI for that that calls the methods.

**Comment by tunght** [comment]
I'm new to this project and I'd like to tackle this issue.
For UI would something like adding a delete button next to each project in the list is ok? 
Like this image but with a nice delete icon instead
![Screenshot 2024-02-10 at 5 22 46 PM](https://github.com/zed-industries/zed/assets/1823955/e2b517be-a7be-4286-b816-757c70627ba2)

**Comment by tunght** [comment]
Hi, im kinda stuck on this issue, Im not sure why. Any one can help me on this please.
I added these function, and called to delete the workspace. the function does execute but somehow it doesnt delete the workspace from the database table.
<img width="911" alt="Screenshot 2024-02-14 at 10 41 44 PM" src="https://github.com/zed-industries/zed/assets/1823955/18652b4b-ee
<img width="764" alt="Screenshot 2024-02-14 at 10 42 38 PM" src="https://github.com/zed-industries/zed/assets/1823955/483fa244-a2a7-47a8-aa29-5dcb9d09f7f5">
ce-4a7f-9bca-a9697ca2dc5a">

**Comment by SomeoneToIgnore** [comment]
I do not think you need to anything for that, what does `delete_stale_workspace` method do for you?
And what happens if you start zed with `env RUST_LOG=info`, are there any errors for your method?

**Comment by tunght** [comment]
I used RUST_LOG=info, there is no errors for the method. The reason i wrapped delete_stale_workspace is because of the name, maybe I can just change the name, it's supposed to remove the workspace in workspaces table, but it doesn't

**Comment by tunght** [comment]
THank you very much for your suggestion. My code is very similar to that. I just found out that the delete_workspace function is called but the marcro query function delete_stale_workspace never got called.
I will try it in the confirm function to see if it's working

BTW, agreed on preventing the user to delete the current workspace ( will remove the delete button if the workspace is currently opened ).
There is another scenario where user opens several workspaces at the same time then we can't delete those workspaces either.

**Comment by tunght** [comment]
I got it working! @SomeoneToIgnore if you have time, can you give any feedback for me pls?

There are still couple of things:
 - When hover on the icon it doesn't highlight the icon. I'm still looking for examples in the code. Any suggestion is appreciated
 - Disable the delete button for the current project. Not sure how to get the project information from the workspace in
 
[zed/crates/recent_projects/src/recent_projects.rs](https://github.com/zed-industries/zed/blob/aa319ccfd052b71e791a03afbf73f8bf586b760e/crates/recent_projects/src/recent_projects.rs#L119)

**Comment by SomeoneToIgnore** [comment]
I propose to move the further discussion inside the PR, but will answer your recent questions here:

> When hover on the icon it doesn't highlight the icon. I'm still looking for examples in the code. Any suggestion is appreciated

We could go another way around and do not display icons at all, until those are hovered.
Speaking of the icons: I would prefer an `X`-like button instead of those, since ⌫ symbol associates with the backspace keystroke: Zed does draw keystroke labels and this one not working feels very odd.

> Disable the delete button for the current project. Not sure how to get the project information from the workspace in

That link above I've posted
https://github.com/zed-industries/zed/blob/aa319ccfd052b71e791a03afbf73f8bf586b760e/crates/recent_projects/src/recent_projects.rs#L119
is the workspace the popover gets opened in.  Knowing about other open workspaces is harder, but there's a `WorkspaceStore` in the `AppState` here: https://github.com/zed-industries/zed/blob/6665ecd65296dac9af7157a1633057fe254a14b2/crates/workspace/src/workspace.rs#L348

**Comment by tunght** [comment]
> @tunght :
> 
> Here is some feedback:
> 
> 1. Delete the entire list of open projects
> 
> <img alt="Screenshot 2024-02-16 alle 07 24 15" width="195" src="https://private-user-images.githubusercontent.com/20476002/305323276-33b7b38f-17a0-4c38-aeec-af94212b222b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDIwMTksIm5iZiI6MTcwODEwMTcxOSwicGF0aCI6Ii8yMDQ3NjAwMi8zMDUzMjMyNzYtMzNiN2IzOGYtMTdhMC00YzM4LWFlZWMtYWY5NDIxMmIyMjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE2NDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZjEyM2Y0M2QzYjZkNTU4Yzk5Y2M2NDAwODM5ZGYwNmYwNTdhM2VlZjVmNmVjYjIwNjExYjQ4Yjc0MzI0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XRwTA5ci2lKRLf_F5uFioA6fq3pGWToTZsqfXowEtk">
> 2. On Mac OS if this feature is not present, if the project is selected delete it using the delete button or the delete+cmd button combination.
> 3. It would be interesting if, under the name, the date of the last time the project was opened or modified was somehow displayed.

Thank you, those are intersting suggestions. I will include them in the PR.

**Comment by tunght** [comment]
> I propose to move the further discussion inside the PR, but will answer your recent questions here:
> 
> > When hover on the icon it doesn't highlight the icon. I'm still looking for examples in the code. Any suggestion is appreciated
> 
> We could go another way around and do not display icons at all, until those are hovered. Speaking of the icons: I would prefer an `X`-like button instead of those, since ⌫ symbol associates with the backspace keystroke: Zed does draw keystroke labels and this one not working feels very odd.
> 
> > Disable the delete button for the current project. Not sure how to get the project information from the workspace in
> 
> That link above I've posted
> 
> https://github.com/zed-industries/zed/blob/aa319ccfd052b71e791a03afbf73f8bf586b760e/crates/recent_projects/src/recent_projects.rs#L119
> 
> 
> is the workspace the popover gets opened in. Knowing about other open workspaces is harder, but there's a `WorkspaceStore` in the `AppState` here:
> https://github.com/zed-industries/zed/blob/6665ecd65296dac9af7157a1633057fe254a14b2/crates/workspace/src/workspace.rs#L348

Thank you! I thought the ⌫ is werid too!

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/7885 had dealt with this (thanks @tunght for going through all hickups!) and will be a part of Zed Preview 0.125 next Wednesday.
