### ISSUE TITLE
After multiple windows are used and closed, the memory will not decrease.

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#7438]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open multiple zed windows and close them until there is only one window left after finishing my work, I find that the memory usage does not decrease. When I only open one window, it stabilizes at about 170 MB. When I open 2 windows, it stabilizes at 273 MB. When I close the second window, the memory still needs to use about 262 MB. If you open the window repeatedly, the memory will continue to increase.
1. first window
![image](https://github.com/zed-industries/zed/assets/12579229/800adfe1-1e76-4468-aec9-6d5937a149ff)
2. two window
![image](https://github.com/zed-industries/zed/assets/12579229/c0b8fa74-b5ed-4bbb-b538-44dc72275ea6)
3. close  window 2
![image](https://github.com/zed-industries/zed/assets/12579229/1b19522c-cb2c-4ab7-aea0-93eb02f81936)
4. reopen window 2
![image](https://github.com/zed-industries/zed/assets/12579229/d91b8d82-2060-4039-82df-aa6f6f528706)
5. close and reopen again
![image](https://github.com/zed-industries/zed/assets/12579229/344ff9cb-1be2-44ae-bc1f-220dd197010b)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by yingbo** [comment]
@ethan-phu If I were you, I won't post my macbook's SN on internet. It's better to mask it.

**Comment by ethan-phu** [comment]
> @ethan-phu If I were you, I won't post my macbook's SN on internet. It's better to mask it.

oh this is very important, I didn’t notice this, thank you for reminding me

**Comment by phiberber** [comment]
> > @ethan-phu If I were you, I won't post my macbook's SN on internet. It's better to mask it.
> 
> oh this is very important, I didn’t notice this, thank you for reminding me

Good to mention, anyone can see the old comment still, editing it has no effect.
