### ISSUE TITLE
Show left dock on open new project showing folder structure

### ISSUE THREAD

**Issue by emersonjds** [zed-industries/zed#7439]
### Check for existing issues

- [X] Completed

### Describe the feature

When we open a new project, by default Zed does not display the project's folder structure, making it necessary to click to display the dock on the left.

Ideally, when opening a new project, zed should do this by showing the project's folder structure

Thanks

### If applicable, add mockups / screenshots to help present your vision of the feature

How it works today

<img width="527" alt="Screenshot 2024-02-06 at 11 33 46" src="https://github.com/zed-industries/zed/assets/12503997/5559b8d5-cf9a-418a-96ef-a08e0a5880b9">

Improvement suggestion

<img width="443" alt="Screenshot 2024-02-06 at 11 38 52" src="https://github.com/zed-industries/zed/assets/12503997/d023a251-3eff-4ec5-8246-e24b2d7177e4">

**Comment by JosephTLyons** [comment]
Thanks for the report @emersonjds, this is a bit odd, I swear we had this functionality added before. Maybe a regression happened...

**Comment by Zavalaesteban1** [comment]
How do i add this into zed
