### ISSUE TITLE
cmd+f highlights are barely visible in most themes

### ISSUE THREAD

**Issue by marwan-at-work** [zed-industries/zed#7448]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you watch the following video, you'll notice the highlight color of the results of a cmd+f/finder query is barely visible:

https://github.com/zed-industries/zed/assets/16294261/c5c34fc1-5bee-4592-baf3-88663a2420fc

Not sure if this is a misconfiguration on my side or others have experienced the same thing. 

Thanks!

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.3.0
Memory: 96 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Already included above.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This was just improved on main. Here is One Light:

<img width="1608" alt="SCR-20240206-llau" src="https://github.com/zed-industries/zed/assets/19867440/502fdb8a-db61-4dd7-a0a2-e1528a8eae5f">

Going to close this. Please open a new issue if you run into other contrast issues like this.

**Comment by JosephTLyons** [comment]
No worries at all. Finding dupes is hard - I miss them all the time and I'm in here hourly.

**Comment by marwan-at-work** [comment]
@JosephTLyons 👋🏼 

was this fix included in 0.121.5? 

I'm still seeing it as you can see here. As well as "Atelier Forest Dark" if you want to try another example.

Notice the left-most highlighted result is barely visible. 

<img width="1481" alt="Screenshot 2024-02-07 at 4 44 21 PM" src="https://github.com/zed-industries/zed/assets/16294261/cb884f2c-2501-4d48-a493-992a97ef3975">

Thanks!!

**Comment by JosephTLyons** [comment]
> @JosephTLyons 👋🏼
> 
> was this fix included in 0.121.5?
> 
> I'm still seeing it as you can see here. As well as "Atelier Forest Dark" if you want to try another example.
> 
> Notice the left-most highlighted result is barely visible.
> 
> <img alt="Screenshot 2024-02-07 at 4 44 21 PM" width="1481" src="https://private-user-images.githubusercontent.com/16294261/303147221-cb884f2c-2501-4d48-a493-992a97ef3975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDUwMjQsIm5iZiI6MTcwNzM0NDcyNCwicGF0aCI6Ii8xNjI5NDI2MS8zMDMxNDcyMjEtY2I4ODRmMmMtMjUwMS00ZDQ4LWE0OTMtOTkyYTk3ZWYzOTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIyMjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMWQzOGVhMzgzYjM1MjQ3ZmMxYzgwZmRkMWFjMjg1YjNlNTM2OWFiM2I5YTYyMmEwZTZlODRkYWIyMGRiZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmES2RzekLAFaj0VDt2vnCsRz9tZMG28I2MOyRoIJpY">
> Thanks!!

I think the fix just landed on preview today, so it will be in preview in 7 days, unless we put out a patch to fast ship it.

**Comment by marwan-at-work** [comment]
Hi @JosephTLyons thank you for the response and apologies for pinging again :) 

I think the fix has landed as I'm running 0.123.3. 

The search highlights look great. However, the highlight that your cursor is currently landed on, is still very hard to distinguish.

If you notice the screenshot below, the 5th word context is actually the highlighted one but you have to zoom a lot to really tell the difference.

<img width="870" alt="Screenshot 2024-02-23 at 9 41 11 AM" src="https://github.com/zed-industries/zed/assets/16294261/b4e798e2-b45a-4737-b7d3-9cfbbd9a93e9">

**Comment by JosephTLyons** [comment]
> Hi @JosephTLyons thank you for the response and apologies for pinging again :)
> 
> I think the fix has landed as I'm running 0.123.3.
> 
> The search highlights look great. However, the highlight that your cursor is currently landed on, is still very hard to distinguish.
> 
> If you notice the screenshot below, the 5th word context is actually the highlighted one but you have to zoom a lot to really tell the difference.
> 
> <img alt="Screenshot 2024-02-23 at 9 41 11 AM" width="870" src="https://private-user-images.githubusercontent.com/16294261/307355296-b4e798e2-b45a-4737-b7d3-9cfbbd9a93e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODE0OTUsIm5iZiI6MTcwODk4MTE5NSwicGF0aCI6Ii8xNjI5NDI2MS8zMDczNTUyOTYtYjRlNzk4ZTItYjQ1YS00NzM3LWI3ZDMtOWNmYmJkOWE5M2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIwNTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOTgyYzFkMjYyMGY2NGMwMmFjNGY1ZWM3OTlmNTNkZTI1ZWNlOGQxZjUyYzNlZDM1ZDVlMzdkMTYyNGMzYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0RMDwGIp55drW7gInc7HQSHRjgfefZ6gpZm_yScSv3A">

You're right - let's open up a new issue to track that.
