### ISSUE TITLE
Execute shell commands on the command palette

### ISSUE THREAD

**Issue by NeddM** [zed-industries/zed#7460]
### Check for existing issues

- [X] Completed

### Describe the feature

Would be nice to execute commands straight on the command palette.

As a Neovim user I often execute commands on the command line like this:
```
:!git add .
``` 

It might be cool to run commands directly from the command palette, even if the response is shown in a new terminal panel.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Captura de pantalla 2024-02-06 a las 21 44 35](https://github.com/zed-industries/zed/assets/91211902/17c44d1b-f3b9-49c0-b41b-4df1d6f52168)

**Comment by JosephTLyons** [comment]
Hey @NeddM, check out this tracking issue, we are laying the foundation for defining runnables within Zed:

- https://github.com/zed-industries/zed/issues/7108

**Comment by osiewicz** [comment]
This should be a part of the next Preview; type in your command in runnables picker and then use cmd+enter to spawn it.
