### ISSUE TITLE
Seems that not all avaiable commands are shown in the Execute Command Panel

### ISSUE THREAD

**Issue by lucasamoroso** [zed-industries/zed#7462]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was looking for the `Show symbol outline` but I couldn't find it while searching it in the `Execute Command`  palette. Luckily I found in the ui a way to execute the command and it's shortcut but I'd expect to be able to search for any command in this palette

<img width="1504" alt="image" src="https://github.com/zed-industries/zed/assets/18125567/7bd0bf8d-561c-423c-ad91-882de2d0ea22">

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1504" alt="image" src="https://github.com/zed-industries/zed/assets/18125567/7bd0bf8d-561c-423c-ad91-882de2d0ea22">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by osiewicz** [comment]
Hey, thanks for the report; that particular action is just named differently (look for `outline: toggle`) though it bugs me that we have that inconsistency in naming sometimes.

**Comment by JosephTLyons** [comment]
Oh this one pains me. I spent a long time cleaning up a bunch of keymap stuff ages ago, but it was shut down because the team didnt want to break anyone's stuff and it was a lot easier to justify back then. I still think we should just break everyone's stuff before 1.0 and get everything cleaned up. We have varying names in actions like 'prev' and 'previous' and then different names in the command palette vs the tool tips.

- https://github.com/zed-industries/zed/pull/2341/files

**Comment by lucasamoroso** [comment]
> Hey, thanks for the report; that particular action is just named differently (look for `outline: toggle`); I think we should strive for consistency, but it's hard to fix in retrospect (as the name from command palette is tied to the name used in keybindings); we'll have to tackle that problem somehow.

Ohh I see, I found the command `outline: toggle`.  Thanks :) 


> Oh this one pains me. I spent a long time cleaning up a bunch of keymap stuff ages ago, but it was shut down because the team didnt want to break anyone's stuff and it was a lot easier to justify back then. I still think we should just break everyone's stuff before 1.0 and get everything cleaned up. We have varying names in actions like 'prev' and 'previous' and then different names in the command palette vs the tool tips.
> 
> * [Update keybinding names #2341](https://github.com/zed-industries/zed/pull/2341)

I agree with you that naming consistency would be nice to have before 1.0.  Do you want me to change the title to something like "naming inconsistency between actions"? So it's easier to find an issue?
