### ISSUE TITLE
Setting terminal font_size

### ISSUE THREAD

**Issue by zhytang** [zed-industries/zed#7469]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

typo in "assets/setting/default.json"
<img width="794" alt="image" src="https://github.com/zed-industries/zed/assets/16872071/9be9a5c5-da2a-4435-9dd4-65a270804ab0">

terminal.font_size should be number

### Environment

Zed 0.120.6
MacOS 14.3 (23D56)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/zed-industries/zed/pull/7649
