### ISSUE TITLE
zoom in edit window, terminal layout error ?

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#7472]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Maybe this one is a minor issue, but it looked bad to me.

https://github.com/zed-industries/zed/assets/19868292/ff7f9d35-9f99-47e2-a816-fc76645d8da0

### Environment

Zed: v0.121.4 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Are you referring to the gap/border? I think that's done on purpose so you know that there's other windows behind it.

**Comment by 0x2CA** [comment]
I mean when the edit window is zoomed in, the terminal window is aligned top in the background, and the project panel is fixed aligned right in the background

**Comment by mrnugget** [comment]
I see. You mean the difference between zoomed editor and terminal, yes?

![screenshot-2024-02-07-10 10 40@2x](https://github.com/zed-industries/zed/assets/1185253/541efcbe-4b7a-4921-b126-202bb7d9a11d)

![screenshot-2024-02-07-10 11 32@2x](https://github.com/zed-industries/zed/assets/1185253/ea672c14-911e-4456-8c70-4d5d80123905)

**Comment by sawhil** [comment]
What's the shortcut key that we use to enter the zoomed in mode ?
I can't seem to figure them out.
