### ISSUE TITLE
[Bug] Click on link doesn't work for JSDoc

### ISSUE THREAD

**Issue by vitalics** [zed-industries/zed#7482]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open JSDoc on hover. Try to click on link (`cause` in my case)

<img width="924" alt="image" src="https://github.com/zed-industries/zed/assets/8816260/9933220a-6e72-4492-8017-bedd2adab721">

Actual Result: hovered popup is closed and URL is not opened.

### Environment

OS: macOS 14.3 23D56 arm64
Host: Mac14,9
Kernel: 23.3.0
CPU: Apple M2 Pro
GPU: Apple M2 Pro
Memory: 16384MiB

zed version: 0.120.6
zed commit: f6836cbc9189d03bbbae8b84679a2b4c042f4042

### If applicable, add mockups / screenshots to help explain present your vision of the feature

in comparison to VSCode. it opens an additional dialog window
<img width="722" alt="image" src="https://github.com/zed-industries/zed/assets/8816260/6af1815f-0977-40f0-ae89-59b74a3ca2a6">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @vitalics, I'm going to close this issue out for a more generic issue here:

- https://github.com/zed-industries/zed/issues/4310

Please upvote it with a 👍
