### ISSUE TITLE
Can't bind "pane::RevealInProjectPanel" 

### ISSUE THREAD

**Issue by avetisk** [zed-industries/zed#7485]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While `"pane::RevealInProjectPanel"` is auto-completed (i.e it is recognized as a valid keybinding) and there is such an item in the context menu on the file tab (which works fine when I click on it), when I press the chosen keybinding (tried different ones), it's not working (i.e nothing happens).

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.2.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
```
2024-02-07T09:22:12 [ERROR] crates/settings/src/keymap_file.rs:89: invalid binding value for keystroke cmd-shift-x, context Some("Editor")

Caused by:
    0: Attempting to build action pane::RevealInProjectPanel
    1: missing field `entryId`
```

**Comment by mrnugget** [comment]
Yes, that doesn't work for two reasons:

1. `RevealInProjectPanel` requires an argument: `entryId`. That's the internal ID of the file/dir it should reveal in the panel.
2. The action is only available in the `pane` scope, which is where the right click menu is. We'd have to create it in the editor scope too. That's fixable!

**Comment by avetisk** [comment]
Fixing this may also help those who are waiting for the "auto-focus current editor file in explorer pane".

**Comment by mrnugget** [comment]
Just merged https://github.com/zed-industries/zed/pull/7487 -- that should fix your binding problems and adds a default keybinding for Vim mode.
