### ISSUE TITLE
Open workspace from cli

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#7513]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to be able to open a workspace from the cli similar to how I can via vscode's `code`

This should open up the `sqlparser-rs` directory as a zed workspace. Instead it just opens up zed with the last opened workspace. 

```sh
> zed ../sqlparser-rs/
```

**Comment by JosephTLyons** [comment]
Thanks @TheBeachMaster! Yep, we already have this, so I'm going to close this out. :)
