### ISSUE TITLE
Code Actions: garbled text on final line

### ISSUE THREAD

**Issue by rubjo** [zed-industries/zed#7548]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See screen recording. Multiple items on the same / text wrapping issue or something :)

https://github.com/zed-industries/zed/assets/42270947/a751ad9d-9d2c-46ee-9f59-42152182747b

Thank you for making and open-sourcing this editor, looks incredibly promising!

### Environment

Zed: v0.121.5 (Zed)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by demenik** [comment]
I have the same issue. I haven't looked into this but from what it looks like it could be the text overflowing into the second row.

<img width="394" alt="Screenshot 2024-02-16 at 1 50 39 AM" src="https://github.com/zed-industries/zed/assets/45211712/571881fb-29dc-4d13-8d08-e64c22785273">
