### ISSUE TITLE
terminal: text overlaps UI (tabs)

### ISSUE THREAD

**Issue by avetisk** [zed-industries/zed#7549]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As you can see in the picture below the `|` is overlapping the tab.

Here's my terminal config in Zed:

```json
  "terminal": {
    "alternate_scroll": "on",
    "blinking": "terminal_controlled",
    "copy_on_select": true,
    "default_width": 640,
    "dock": "right",
    "env": {},
    "font_family": "Victor Mono",
    "font_size": 14,
    "line_height": "standard",
    "working_directory": "current_project_directory"
  }
```

<img width="640" alt="image" src="https://github.com/zed-industries/zed/assets/737729/d799ff2f-824e-4ab7-ab36-ee3a6988be24">

### Environment

Zed: v0.121.5 (Zed)
OS: macOS 14.3.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by rubjo** [comment]
Font author here (who happened to file an issue just around the same time as you :). I'm not seeing the same on my setup.

You could try a few things:
- Omitting the whole `"line_height": "standard",` line
- If you're using the version downloaded from the font web site, try the Google Fonts distribution of Victor Mono instead, it has some minor adjustments
- Trying the Nerd Fonts variant of Victor Mono instead

**Comment by avetisk** [comment]
> * Omitting the whole `"line_height": "standard",` line

Can't do that, I want to have a small line height :)

> * If you're using the version downloaded from the font web site, try the Google Fonts distribution of Victor Mono instead, it has some minor adjustments

Tried it, didn't work (I had to remove 2px from the font size I had set though)

> * Trying the Nerd Fonts variant of Victor Mono instead

Same, still having the issue.

I think beyond the issue with the font, the terminal should clip the overflow.

BTW, a huge thank for the Victor Mono font, it's been my favorite since I got ❤️🙏

**Comment by rubjo** [comment]
Anyway, it's probably not `|` but rather `│` (box-drawing character U+2502), which might not be straightforward to fix.

**Comment by avetisk** [comment]
Indeed, but I still think the issue is not the font but the way the overflow is handled. 

The CSS equivalent of the terminal's viewport should be `overflow: hidden`.

**Comment by notpeter** [comment]
I am no longer able to reproduce this and I believe it has been fixed. If you are still seeing this, please comment with a screenshot from a current release version and I'm happy to reopen. Thanks for reporting!
