### ISSUE TITLE
Disable typescript autocomplete async suggestions

### ISSUE THREAD

**Issue by jansedlon** [zed-industries/zed#7560]
### Check for existing issues

- [X] Completed

### Describe the feature

I think it's related to this comment https://github.com/zed-industries/zed/issues/5166#issuecomment-1908645526 but not sure if the issue got lost. Basically when autocomplete is triggered, the suggestions are reordered many times and many times it happens that I select something, press enter and in the meantime, the order changes and I selected the wrong suggestion

**Comment by mrnugget** [comment]
Does this still happen on the newest versions? Asking because https://github.com/zed-industries/zed/pull/7115 got merged and that can have an effect here.

**Comment by jansedlon** [comment]
It seems better, thank you 💪
