### ISSUE TITLE
Support for alternate OpenAI URL in settings

### ISSUE THREAD

**Issue by tjohnman** [zed-industries/zed#7565]
### Check for existing issues

- [X] Completed

### Describe the feature

Some services, like Perplexity AI, offer an OpenAI-compatible drop-in replacement API. By providing a way to change the URL Zed uses to send requests to OpenAI, it would get support for these services "for free".

### If applicable, add mockups / screenshots to help present your vision of the feature

Something like:
```
{
  "assistant":  {
    "default_open_ai_url": "https://api.perplexity.ai/"
    ...
  }
}
```

**Comment by willtejeda** [comment]
I was looking for this setting, it's surprising that it's not implemented already.

Ollama now has openai compatible API ( for chat completion) so it's a great time to get this added

**Comment by afinno** [comment]
This would be a great enhancement. I'd also like to point out that LM Studio also offers an OpenAI compatible API locally.

It could work similarly to the **Continue** plugin for VSCode.

Sample of **Continue** `config.json`:

```json
{
  "models": [
    {
      "title": "GPT-4",
      "provider": "openai",
      "model": "gpt-4"
    },
    {
      "title": "Mixtral",
      "provider": "lmstudio",
      "apiBase": "http://localhost:1234/v1",
      "completionOptions": {},
      "model": "mixtral-8x7b"
    }
  ]
}
```

**Comment by afinno** [comment]
Also a related thread/issue.

https://github.com/zed-industries/zed/issues/6708

**Comment by localSummer** [comment]
The openai_api_url setting has been added in the latest preview version

**Comment by SomeoneToIgnore** [comment]
Closed in https://github.com/zed-industries/zed/pull/7484
