### ISSUE TITLE
When comes to windows 10/11?

### ISSUE THREAD

**Issue by vsl-dev** [zed-industries/zed#7572]
### Check for existing issues

- [X] Completed

### Describe the feature

When comes?

**Comment by SomeoneToIgnore** [comment]
Consider [discussions](https://github.com/zed-industries/zed/discussions) for asking generic questions next time. 

Zed comes to Windows when somebody ports it there: https://github.com/zed-industries/zed/issues/5394
So far, the porting effort is concentrated on Linux though, so no estimates can be made.
