### ISSUE TITLE
Zed loses responsiveness after v0.121.5

### ISSUE THREAD

**Issue by ivansvlv** [zed-industries/zed#7580]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After updating Zed from v0.120.6 to v0.121.5, it started acting weird. Here is the list of what I've noticed after working in it for less than an hour.

1. Opening file in already opened project can hang for 1-3 seconds.
2. Cursor can hang and stop blinking, or blink not evenly, a bit sporadically.
3. Closing the tab (CMD+W) can hang Zed for 1-3 seconds.
4. Closing Zed (CMD+Q) can hang it for 1-3 seconds.
5. Visible lag of syntax highlighting, even in the loaded document as I type. For e.g. in Ruby - `Struct.new()`, it takes noticeable time to re-paint `new` in a proper color.

Please let me know what additional info you might need.

### Environment

Zed: v0.121.6 (Zed)
OS: macOS 14.3.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JeetChhatrala** [comment]
Facing the same issue on

**Environment**
Zed: v0.121.6 (Zed)
OS: macOS 14.3.0
CPU: M2 Pro
Memory: 16 GiB
Architecture: aarch64

**Comment by maxbrunsfeld** [comment]
Thanks for the report, and sorry for the bug. We're building a patch release to fix this.

**Comment by JosephTLyons** [comment]
Hey, for those of you experiencing these bugs, can you test the latest builds and see if the issues persist?

- Stable: [v0.121.7](https://zed.dev/releases/stable/0.121.7)
- Preview: [v0.122.2-pre](https://zed.dev/releases/preview/0.122.2)

**Comment by JeetChhatrala** [comment]
Great work!!! it's working butter smooth again.

**Comment by ivansvlv** [comment]
Same from my side, everything is buttery smooth again! Thank you!

**Comment by mikayla-maki** [comment]
Glad to hear it :D

**Comment by JosephTLyons** [comment]
🧈
