### ISSUE TITLE
Cmd+G (SelectNextMatch) is lagged around 1-2s

### ISSUE THREAD

**Issue by thethongngu** [zed-industries/zed#7588]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`search::SelectNextMatch` by `Cmd+G` is lag around 1-2s. It is not the case if we use:
- `Enter` while focusing on search input field
- Run command by Cmd+Shift+P
- Custom keymap for `search::SelectNextMatch`

### Environment

Zed: v0.121.6 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/8380567/ff8c8256-1bfc-4cd8-8bfa-12b3a6cdefac

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Could be related: https://github.com/zed-industries/zed/issues/7580

**Comment by JosephTLyons** [comment]
Hey @thethongngu, can you test either stable or preview and see if your problem persists?

- Stable: [v0.121.7](https://zed.dev/releases/stable/0.121.7)
- Preview: [v0.122.2-pre](https://zed.dev/releases/preview/0.122.2)

**Comment by thethongngu** [comment]
I tested for both
```
Zed: v0.121.7 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64
```
and
```
Zed: v0.122.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64
```

Both versions have this issue. 

I will also trace around to see if I got any luck spotting the issue

**Comment by mrnugget** [comment]
I can't reproduce this on the newest versions. Here's what I tried:

1. Open a buffer
2. Search for something in the buffer
3. Hit `cmd-g` repeatedly

How do you reproduce it @thethongngu?

**Comment by thethongngu** [comment]
Okay, I figured it out. That is because I set this custom keymap

```
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-g cmd-d": "editor::GoToDefinition",
    }
  }
]

```

I guess Zed would wait a bit to see whether I press the `cmd-d` next. One improvement I can think of is showing the pressed key chain while waiting for the next key press.

Sorry for the noise. I will close this issue. 🙏
