### ISSUE TITLE
Missing left padding makes right scrollbar overlap last character in line

### ISSUE THREAD

**Issue by borisnezlobin** [zed-industries/zed#7590]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The last character in a very long line will be hidden by the scrollbar (still visible behind the semi-transparent part, but not at all behind the version-control indicator)

Here's an image (ignore the copilot suggestion, lol). Focus in particular on the rightmost part, especially the last character
<img width="1244" alt="image" src="https://github.com/zed-industries/zed/assets/146669165/43613f15-c346-4fb1-b126-1700471cea11">

For comparison, here's vscode with the same file (scrolled as far to the right as possible):
<img width="1124" alt="image" src="https://github.com/zed-industries/zed/assets/146669165/6c3f7014-a3bd-4d05-b0d7-f7e8d12d69f3">

### Environment

Zed: v0.121.5 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bennetbo** [comment]
Looks like a duplicate of #7098.

**Comment by borisnezlobin** [comment]
Looks like you're right! I'll close this issue
