### ISSUE TITLE
Text for the solarized dark theme is too bright

### ISSUE THREAD

**Issue by carlocaione** [zed-industries/zed#7594]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The regular text on the solarized dark theme is way too bright.

<img width="687" alt="Screenshot 2024-02-08 at 22 36 21" src="https://github.com/zed-industries/zed/assets/357758/c91a4600-462e-4a9c-8067-02e3fad4676f">

See the correct solarized theme for neovim on the left and Zed on the right

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.3.0
Memory: 24 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
As mentioned in https://github.com/zed-industries/zed/pull/7616#issuecomment-1936208348, we don't currently have plans to rework the existing built-in themes.

There is a more accurate Solarized theme available in the [Zed extension registry](https://github.com/zed-industries/extensions/tree/main/extensions) as `neosolarized` that folks will (soon) be able to install if they're looking for this.
