### ISSUE TITLE
Release notes popup no longer showing

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#7597]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Starting at v0.122.1-pre, the popup that appeared after updating to tell users to check the release notes stopped showing.

### Environment

Zed: v0.122.1 (Zed Preview)
OS: macOS 14.1.2
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
I didn't get the notification with the latest `v0.125.0` if it was supposed to show up.

**Comment by ConradIrwin** [comment]
Sadly I fixed it just after that release!

**Comment by Moshyfawn** [comment]
Ah, my mistake! I treated the release and closure of this issue as if it was included in the scope 🤦
