### ISSUE TITLE
Per project terminal.shell not working as documented

### ISSUE THREAD

**Issue by wesleycoder** [zed-industries/zed#7599]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is my first time trying zed, if I'm out of place let me know :)

I checked all the open issues and couldn't find anything directly related, #5320 seems a little bit related but is about a different symptom, so I decided continue with this issue.

---

I was trying to get tmux to open as zeds integrated terminal, (similar to this [article for vscode](https://dev.to/techspresso/tmux-and-vscode-persist-terminals-for-productivity-and-profit-2nd1#:~:text=terminal.integrated.profiles.osx)).
With this I followed the zed's [docs for configuring the terminal](https://zed.dev/docs/configuring-zed#terminal).

Configuring `tmux` worked at the user config level `~/.config/zed/settings.json`, but not on a project level.

But with this I discovered that Zed isn't respecting the `.zed/settings.json` file created by the `Zed > Settings > Open Local Settings` command.

I wished to be able to set this on a per project level, because I couldn't get a dynamic name for the workspace (as the article for vscode suggests), this would be nice to have on Zed too, but of course is out of scope for this issue.

`~/.config/zed/settings.json`:
```json
{
  "project_panel": {
    "dock": "right"
  },
  "theme": "Ayu Dark",
  "ui_font_size": 16,
  "buffer_font_size": 13
}
```
`~/project_dir/.zed/settings.json`:
```json
{
  "terminal": {
    "shell": {
      "with_arguments": {
        "program": "tmux",
        "args": [
          "new",
          "-As",
          "zed"
        ]
      }
    }
  }
}
```

I've restarted the editor presuming a reload would fix, but no luck.
I've attached a recording of the process, but I reiterate that I'm newbie when it comes to zed config.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/22945955/788982a4-0daf-43bc-8e75-5a1ad51b89cc

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

`Zed.log` file was too big for github to accept it inline (or inside a details tag), so i created a gist for it:
https://gist.githubusercontent.com/wesleycoder/f99800a8be42059c2a0a4501355c52fa/raw/6294e69dae943a0f6d8c180adb0a415275434df9/Zed.log

**Comment by LoganDark** [comment]
Just ran into this. Some of my projects are in WSL and need a project-specific shell or else I won't be able to execute any commands on them at all, since they're on the WSL filesystem. I can manually run `wsl.exe -d whatever` every time I start a terminal, but it would be a lot more helpful if Zed just respected the local settings instead.

**Comment by LoganDark** [comment]
#11526
