### ISSUE TITLE
Yaml LSP `initialization_options` not working

### ISSUE THREAD

**Issue by mchieco** [zed-industries/zed#7636]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I work heavily with AWS Cloudformation and was trying to add a setting on the yaml LSP for custom Tags. Following the docs for both the LSP and zed, i added the `yaml.customTags` property in the lsp section of my settings. This doesn't seem to be working as the LSP is still throwing errors on the cloudformation tags. The docs here for the LSP are what i refereced for the custom tags. https://github.com/redhat-developer/yaml-language-server?tab=readme-ov-file#adding-custom-tags

Here are the configurations i've tried:
```
"lsp": {
    "yaml-language-server": {
      "initialization_options": {
        "yaml": {
          "customTags": [
            "!And scalar",
            "!And mapping",
            "!And sequence",
            "!If scalar",
            "!If mapping",
            "!If sequence",
            "!Not scalar",
            "!Not mapping",
            "!Not sequence",
            "!Equals scalar",
            "!Equals mapping",
            "!Equals sequence",
            "!Or scalar",
            "!Or mapping",
            "!Or sequence",
            "!FindInMap scalar",
            "!FindInMap mappping",
            "!FindInMap sequence",
            "!Base64 scalar",
            "!Base64 mapping",
            "!Base64 sequence",
            "!Cidr scalar",
            "!Cidr mapping",
            "!Cidr sequence",
            "!Ref scalar",
            "!Ref mapping",
            "!Ref sequence",
            "!Sub scalar",
            "!Sub mapping",
            "!Sub sequence",
            "!GetAtt scalar",
            "!GetAtt mapping",
            "!GetAtt sequence",
            "!GetAZs scalar",
            "!GetAZs mapping",
            "!GetAZs sequence",
            "!ImportValue scalar",
            "!ImportValue mapping",
            "!ImportValue sequence",
            "!Select scalar",
            "!Select mapping",
            "!Select sequence",
            "!Split scalar",
            "!Split mapping",
            "!Split sequence",
            "!Join scalar",
            "!Join mapping",
            "!Join sequence"
          ]
        }
      }
    }
```

and 

```
"lsp": {
    "yaml-language-server": {
      "initialization_options": {
        "yaml.customTags": [
            "!And scalar",
            "!And mapping",
            "!And sequence",
            "!If scalar",
            "!If mapping",
            "!If sequence",
            "!Not scalar",
            "!Not mapping",
            "!Not sequence",
            "!Equals scalar",
            "!Equals mapping",
            "!Equals sequence",
            "!Or scalar",
            "!Or mapping",
            "!Or sequence",
            "!FindInMap scalar",
            "!FindInMap mappping",
            "!FindInMap sequence",
            "!Base64 scalar",
            "!Base64 mapping",
            "!Base64 sequence",
            "!Cidr scalar",
            "!Cidr mapping",
            "!Cidr sequence",
            "!Ref scalar",
            "!Ref mapping",
            "!Ref sequence",
            "!Sub scalar",
            "!Sub mapping",
            "!Sub sequence",
            "!GetAtt scalar",
            "!GetAtt mapping",
            "!GetAtt sequence",
            "!GetAZs scalar",
            "!GetAZs mapping",
            "!GetAZs sequence",
            "!ImportValue scalar",
            "!ImportValue mapping",
            "!ImportValue sequence",
            "!Select scalar",
            "!Select mapping",
            "!Select sequence",
            "!Split scalar",
            "!Split mapping",
            "!Split sequence",
            "!Join scalar",
            "!Join mapping",
            "!Join sequence"
          ]
        }
      }
    }
```
### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-02-09 at 5 01 14 PM](https://github.com/zed-industries/zed/assets/31969451/9d324ca2-f0b6-4c1e-a47d-b584d68cc33a)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by chriskuchin** [comment]
Looks like the yaml lsp doesn't actually support the zed settings for lsp:

https://github.com/zed-industries/zed/blob/75377bbe0f1b6d4b8f313adcd5dd5005601d0756/crates/languages/src/yaml.rs#L96

You can see the rust one reading it's settings here

https://github.com/zed-industries/zed/blob/75377bbe0f1b6d4b8f313adcd5dd5005601d0756/crates/languages/src/rust.rs#L42C1-L47C12

**Comment by mikeymop** [comment]
It tracks that the issue is with loading the configuration because I can apply a schema from the inline directive:
```
# yaml-language-server: $schema=http://json.schemastore.org/chart.json
```

However I cannot via a `./.zed/settings.json`:
```json
{
  "lsp": {
    "yaml-language-server": {
      "initialization_options": {
        "yaml.schemas": {
          "http://json.schemastore.org/chart.json": "templates/*.yaml"
        }
      }
    }
  }
}
```

I have also tried passing the arguments via `lsp.yaml-language-server.binary.arguments` with no luck.

**Comment by yodatak** [comment]
Same issue for me and its an issue for most of people that do kubernetes and to mutch yaml in devops

**Comment by notpeter** [comment]
@mchieco Thanks for providing a nice complex example of tags so I could validate.

P.S. Your list is missing `!Condition`:
<img width="788" alt="Screenshot 2024-09-06 at 1 07 01" src="https://github.com/user-attachments/assets/20ca17d6-5a88-466b-91d7-222435d9eb66">

**Comment by notpeter** [comment]
The fix will be available in Zed Preview on Wednesday 2024-09-11 and Zed Stable a week later.

**Comment by notpeter** [comment]
The settings key for this has moved from `initialization_options` to `settings`.
I've updated the YAML docs in #18081 to reflect this.
See: https://zed.dev/docs/languages/yaml for more.

**Comment by gmeligio** [comment]
Thank you for working into this @notpeter . The custom schemas don't work for me though when using Zed 0.153.6 settings but they work when using the YAML directive. Are the custom schemas fixed as well with https://github.com/zed-industries/zed/pull/17479 or should this be a separate issue?

```json
"lsp": {
    "yaml-language-server": {
      "settings": {
        "yaml": {
          "schemas": {
            "http://json.schemastore.org/chart.json": [
              "*.yml.tftpl"
            ]
          }
        }
      }
    }
  },
```

There is also this discussion about the same topic https://github.com/zed-industries/zed/discussions/14528 where I mentioned that I couldn't see the RPC message related to the schema when configured in Zed settings, but I could see it when using the YAML directive.
![image](https://github.com/user-attachments/assets/280433d6-dbb9-419e-9045-768f04c4bb22)

It would be nice if you clarify what part of the settings are currently supported. Thank you.

**Comment by notpeter** [comment]
@gmeligio I replied to your discussion https://github.com/zed-industries/zed/discussions/14528.

It schemas via settings should be supported. If not please file a new issue with a simple reproduction case. (let's not hijack this issue)
