### ISSUE TITLE
Minor typo on the main site

### ISSUE THREAD

**Issue by joshrotenberg** [zed-industries/zed#7642]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Possibly missing the word `to` in this paragraph on https://zed.dev : 

Intelligence on tap

Save time and keystrokes by generating code with AI. Zed supports GitHub Copilot out of the box, and you can use GPT-4 :wave: generate or refactor code by pressing ctrl-enter and typing a natural language prompt. Interact with the model conversationally without switching context in the built-in assistant panel, then reference your conversation during inline generation.

### Environment

the web

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="504" alt="Screenshot 2024-02-09 at 8 28 52 PM" src="https://github.com/zed-industries/zed/assets/3231/a1d4e842-9a5d-4c99-9635-c325b274099d">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
This will be deployed shortly.
