### ISSUE TITLE
Changes with stdsimd on latest Rust Nightly version.

### ISSUE THREAD

**Issue by nshout** [zed-industries/zed#7644]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Rustc Version: `rustc 1.78.0-nightly (d44e3b95c 2024-02-09)`

Description:
When attempting to compile Zed using the latest Nightly version of Rust, users encounter an E0635 error. This error specifically points to an unknown feature, namely stdsimd. Subsequent investigation reveals recent alterations within the Rust repository related to stdsimd.

Steps to Reproduce:

Install the latest Nightly version of Rust.
Clone the Zed repository.
Attempt to compile Zed using the standard build process.

Behavior:
Compilation fails with the E0635 error, indicating an unknown feature stdsimd.

Additional Information:
Upon further research, it was found that recent changes in the Rust repository may have impacted the compatibility of Zed's build process and packages that leverage stdsimd in general.

First Discovery:
Upon attempting to use GPUI for my personal project. (I was able to successfully use GPUI before updating to the latest Nightly version of Rust.)

Dependencies used with said GPUI project:
[dependencies]
gpui = { git = "https://github.com/zed-industries/zed"}

[Rust commit with stdsimd changes](https://github.com/rust-lang/rust/commit/ea37e8091fe87ae0a7e204c034e7d55061e56790)

Command: cargo run

(Skipped successful compiled packages logs until error)

   Compiling rust-embed-impl v8.2.0
error[E0635]: unknown feature `stdsimd`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.2/src/lib.rs:12:49
   |
12 | #![cfg_attr(pf_rustc_nightly, feature(simd_ffi, stdsimd))]
   |                                                 ^^^^^^^

   Compiling futures v0.3.30
   Compiling url v2.5.0
For more information about this error, try `rustc --explain E0635`.
error: could not compile `pathfinder_simd` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

### Environment

Zed: v0.121.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
cc @osiewicz

**Comment by osiewicz** [comment]
Hey, thanks for filling this issue. It looks like we pull in `pathfinder_simd` through font-kit (for which we have our own fork); it looks like folks are already aware of the issue upstream (see: https://github.com/servo/font-kit/issues/233). I'll sync up our fork tomorrow and upgrade pathfinder_simd to resolve that issue.
