### ISSUE TITLE
Option to select python environments 

### ISSUE THREAD

**Issue by gksoriginals** [zed-industries/zed#7646]
### Check for existing issues

- [X] Completed

### Describe the feature

I am only seeing option to select programming language. How can I select existing conda or venv environments in the editor ?

**Comment by mchieco** [comment]
I had the same questions initially. You can follow these docs to get pyright to point at your venv correctly. https://github.com/zed-industries/zed/blob/main/docs/src/languages/python.md

**Comment by Andree37** [comment]
@mchieco cheers, this works great!
Is there a solution for Zed in such a way that we could do the same behavior as, say, other jetbrains tools have it? Where the .idea/ stores the necessary information needed for a project, without having to create these configuration files by ourselves?

**Comment by mchieco** [comment]
Not to my knowledge. It’s not actually the IDE doing the work here, it’s the LSP, and since the venv can be different per repo, i have my config stored on each. but i’m sure you could set a global config if your venv is the same on each

**Comment by lxysl** [comment]
Can I use conda env? I made a conda configuration as follows, but it does not work.
```json
{
  "venvPath": "/Users/lxy/opt/miniconda3/envs",
  "venv": "/Users/lxy/opt/miniconda3/envs/ml"
}
```

**Comment by lxysl** [comment]
> Can I use conda env? I made a conda configuration as follows, but it does not work.
> 
> ```json
> {
>   "venvPath": "/Users/lxy/opt/miniconda3/envs",
>   "venv": "/Users/lxy/opt/miniconda3/envs/ml"
> }
> ```

sorry, that's correct, it worked.

**Comment by kodahrt** [comment]
> > Can I use conda env? I made a conda configuration as follows, but it does not work.
> > ```json
> > {
> >   "venvPath": "/Users/lxy/opt/miniconda3/envs",
> >   "venv": "/Users/lxy/opt/miniconda3/envs/ml"
> > }
> > ```
> 
> sorry, that's correct, it worked.

Can i know how yours work? Cause mine is not working.

**Comment by lxysl** [comment]
> Can i know how yours work? Cause mine is not working.

Specify your conda environment path as above in the `pyrightconfig.json` file and put it in the root path of your project. Restart Zed for the changes to take effect. The Language Server Protocol (LSP) will then be able to resolve it.

**Comment by anesmemisevic** [comment]
> > Can I use conda env? I made a conda configuration as follows, but it does not work.
> > ```json
> > {
> >   "venvPath": "/Users/lxy/opt/miniconda3/envs",
> >   "venv": "/Users/lxy/opt/miniconda3/envs/ml"
> > }
> > ```
> 
> sorry, that's correct, it worked.

Could you make it work with Poetry? Tried the same approach by linking the poetry env directory in pyrightconfig.json but still didn't work.

**Comment by YashM8** [comment]
`{
  "venvPath": "/Users/ypm/miniconda3/envs",
  "venv": "/Users/ypm/miniconda3/envs/mllibs"
}
`

I have put this in `pyrightconfig.json` at the root and restarted. But still doesn't work.

**Comment by dwinkler1** [comment]
For me the full paths didn't work either what does work is the following. I have my conda envs in the folder `/User/daniel/mambaforge/envs` (if I `ls` there I get a list of folders with the names of the environments I created). Let's say I have an env called "great_project". The following is the config for that:

```json
{
  "venv": "great_project",
  "venvPath": "/Users/daniel/mambaforge/envs"
}
```

**Comment by Moshyfawn** [comment]
Related #8541

**Comment by danielcs88** [comment]
FWIW, I made Conda (Miniforge) work on Zed and used my `(base)` environment by using the following settings.

```json
{
  "venvPath": "/Users/daniel/miniforge3/",
  "venv": "/Users/daniel/miniforge3/",
  "executionEnvironments": [
    {
      "python": "/Users/daniel/miniforge3/bin/python"
    }
  ]
}
```

**Comment by cccccroge** [comment]
Following `pyrightconfig.json` work well for Poetry project:

```
{
  "venvPath": "/Users/allen.he/Library/Caches/pypoetry/virtualenvs/",
  "venv": "cyberbiz-data-api-edPw3-qJ-py3.8"
}
```

You can get the path via `poetry env info`

**Comment by colinvwood** [comment]
What if you want to use the currently active conda environment without continuously editing a configuration file?

**Comment by lesonky** [comment]
> Following `pyrightconfig.json` work well for Poetry project:
> 
> ```json
> {
>   "venvPath": "/Users/allen.he/Library/Caches/pypoetry/virtualenvs/",
>   "venv": "cyberbiz-data-api-edPw3-qJ-py3.8"
> }
> ```
> 
> You can get the path via `poetry env info`

I use pipenv ,and the fllowing config works well
```json
{
  "venvPath": "/Users/shaojiasong/.local/share/virtualenvs/",
  "venv": "pandas_test-6SWXZJHk"
}
```


notice that ,you should use full path , don't replace home path with '~'

**Comment by maciejgryka** [comment]
Is there a solution for not hard-coding the `venvPath`? If I'm checking in `pyrightconfig.json` to my repo and sharing with other team members, everyone will have a different `venvPath`.

**Comment by JacobCoffee** [comment]
On top of the above comment, I manage 3-4 versioned venvs due to library maintenance and would like to be able to swap between them. Hardcoding any, let alone all, would not be ideal.

Basically some version of this for telling pyright or whatever to use as a target? 

<img width="308" alt="image" src="https://github.com/zed-industries/zed/assets/45884264/437b21c9-921e-4b23-aed7-47d02336a88c">

**Comment by newtome8888** [comment]
> pyrightconfig

still not working for me, my config as following:
![截屏2024-04-19 07 56 19](https://github.com/zed-industries/zed/assets/58249340/8b6fd030-3863-4a63-b913-68fb8b8de2a7)

**Comment by newtome8888** [comment]
> Following `pyrightconfig.json` work well for Poetry project:
> 
> ```json
> {
>   "venvPath": "/Users/allen.he/Library/Caches/pypoetry/virtualenvs/",
>   "venv": "cyberbiz-data-api-edPw3-qJ-py3.8"
> }
> ```
> 
> You can get the path via `poetry env info`

still not work, my config:
![Uploading 截屏2024-04-19 07.56.19.png…]()

**Comment by newtome8888** [comment]
> Following `pyrightconfig.json` work well for Poetry project:
> 
> ```json
> {
>   "venvPath": "/Users/allen.he/Library/Caches/pypoetry/virtualenvs/",
>   "venv": "cyberbiz-data-api-edPw3-qJ-py3.8"
> }
> ```
> 
> You can get the path via `poetry env info`

not work for me, my config as following:
![截屏2024-04-19 07 56 19](https://github.com/zed-industries/zed/assets/58249340/64f47837-d6a1-4947-835c-80adad29a73e)

**Comment by Spoutnik97** [comment]
Is it possible to use an environment variable like $CONDA_PREFIX ? 
```
{
  "venvPath": "$CONDA_PREFIX/envs",
  "venv": "$CONDA_PREFIX/envs/my_env"
}

```

This does not work for me :(

**Comment by aezomz** [comment]
Look like not working for monorepo for pyproject.toml. 
For example in a directory: 
awesome_project (folder)
|- api_server (in golang)
|- python_sdk (in python)
My `pyproject.toml` is in `python_sdk`.  I have set the pyright section. But Zed doesn't seem to detect it.
> venvPath = "."
venv = "venv"

**Comment by ayansengupta17** [comment]
Doesn't work for mono repo. :(

**Comment by jrosebr1** [comment]
Anyone get Zed working with `pyenv`? Can't seem to nail down what the correct `pyrightconfig.json` should be.

**Comment by jrosebr1** [comment]
Okay, for anyone wondering how to get `pyenv` to play nicely with Zed, here is my example `pyrightconfig.json`:

```json
{
   "venv" : "pyfintech",
   "venvPath" : "/Users/adrianrosebrock/.pyenv/versions"
}
```

Additionally, take a look at [pyenv-pyright](https://github.com/alefpereira/pyenv-pyright) which can help you generate your `pyrightconfig.json` files.

**Comment by ItsJimi** [comment]
> > Following `pyrightconfig.json` work well for Poetry project:
> > ```json
> > {
> >   "venvPath": "/Users/allen.he/Library/Caches/pypoetry/virtualenvs/",
> >   "venv": "cyberbiz-data-api-edPw3-qJ-py3.8"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can get the path via `poetry env info`
> 
> not work for me, my config as following: ![截屏2024-04-19 07 56 19](https://private-user-images.githubusercontent.com/58249340/323790352-64f47837-d6a1-4947-835c-80adad29a73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzI2ODgsIm5iZiI6MTcxNjk3MjM4OCwicGF0aCI6Ii81ODI0OTM0MC8zMjM3OTAzNTItNjRmNDc4MzctZDZhMS00OTQ3LTgzNWMtODBhZGFkMjlhNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA4NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZGYzMzM3NjRiMGViMDE3MjMwMzljMmI1NWI0MWQwZTBiNmE3YTU0MDc1OWRhNjMwYzg3Yzg2MmU1OWVkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JHPpQtfpkwmiy7eh4Q5uqumQ3IZA6wcdqn2p0VxBC8g)

@newtome8888 Hi, i use this and it works for me 😔
Try this:
```json
{
  "venvPath": "/Users/liudong/Library/Caches/pypoetry/virtualenvs",
  "venv": "/Users/liudong/Library/Caches/pypoetry/virtualenvs/webserver-P4NjN8WG-py3.12"
}
```

**Comment by khalidelborai** [comment]
i have this in my bash profile

```bash
if [[ -f "pyproject.toml" ]]; then
  env_path=$(poetry env info -p)
  venv_dir=$(basename "$env_path")
  venv_path=$(dirname "$env_path")
  
  if ! grep -q "\[tool.pyright\]" pyproject.toml; then
    echo "[tool.pyright]" >> pyproject.toml
    echo "venvPath = \"$venv_path\"" >> pyproject.toml
    echo "venv = \"$venv_dir\"" >> pyproject.toml
  else
    if ! grep -q "venvPath" pyproject.toml; then
      sed -i "/\[tool.pyright\]/a venvPath = \"$venv_path\"" pyproject.toml
    fi
    if ! grep -q "venv" pyproject.toml; then
      sed -i "/\[tool.pyright\]/a venv = \"$venv_dir\"" pyproject.toml
    fi
  fi
  poetry shell && clear
fi
```

it sets 

```toml
[tool.pyright]
```

in `pyproject.toml` if it dosen't exist and solves two problems 

- Pyright
- Chossing the right venv in terminal launch

**Comment by khalidelborai** [comment]
> i have this in my bash profile
> 
> ```shell
> if [[ -f "pyproject.toml" ]]; then
>   env_path=$(poetry env info -p)
>   venv_dir=$(basename "$env_path")
>   venv_path=$(dirname "$env_path")
>   
>   if ! grep -q "\[tool.pyright\]" pyproject.toml; then
>     echo "[tool.pyright]" >> pyproject.toml
>     echo "venvPath = \"$venv_path\"" >> pyproject.toml
>     echo "venv = \"$venv_dir\"" >> pyproject.toml
>   else
>     if ! grep -q "venvPath" pyproject.toml; then
>       sed -i "/\[tool.pyright\]/a venvPath = \"$venv_path\"" pyproject.toml
>     fi
>     if ! grep -q "venv" pyproject.toml; then
>       sed -i "/\[tool.pyright\]/a venv = \"$venv_dir\"" pyproject.toml
>     fi
>   fi
>   poetry shell && clear
> fi
> ```
> 
> it sets
> 
> ```toml
> [tool.pyright]
> ```
> 
> in `pyproject.toml` if it dosen't exist and solves two problems
> 
> * Pyright
> * Chossing the right venv in terminal launch

tweaking this to work with other venv managers should be easy.

hope it helps others solve the problem until we get it in zed.

also it would be helpful if someone can direct me to where this can be implemented into zed.

i can give it some time later.

**Comment by Ltalhado** [comment]
Any ideas for those using conda as prefer env manager? I am having a similar issues too.

**Comment by esc** [comment]
The idea user-work-flow for me would be to `cd` to the root of the tree I am working on and launch `zed` from there and it just picks up whatever venv/conda env or whatever is configured, i.e. the first entry when doing `which -a python`. That would be the definintion of "seamless integration". All the other hacks above seem cumbersome and error prone.

**Comment by esc** [comment]
And if I switch conda env for example with `conda activate` `zed` would just follow suit and then use the currently active env.

**Comment by srbh001** [comment]
I have created a simple[ task](https://zed.dev/docs/tasks) in the editor that allows me choose from all the virtual envs in python that I have. Upon execution it searches for all the venvs and using fzf lets me select one then creates the pyrighconfig.json in the current directory.
```json
{
    "label": "(Python) : Select Virtual Env",
    "env": {
      "cwd": "$ZED_DIRNAME"
    }
    "command": "~/selectenv.sh",
    "use_new_terminal": true
  }
```


where selectenv.sh is 
```bash
#!/bin/bash

search_venvs() {
  local search_path=$1
  if [ -d "$search_path" ]; then
    find "$search_path" -type d -name 'bin' -exec test -e '{}/activate' \; -print 2>/dev/null | sed 's|/bin||'
  fi
}

paths=(
  "$PWD"
  "$HOME/.local/share/virtualenvs"
  "$HOME/Library/Caches/pypoetry/virtualenvs"
  "$HOME/.local/share/pdm/venvs"
  "$HOME/.pyenv/versions"
  "$HOME/.virtualenvs"
  "$HOME/.conda/envs"
)


if [ -n "$CONDA_PREFIX" ]; then
  paths+=("$CONDA_PREFIX")
fi

venv_paths=()
for path in "${paths[@]}"; do
  while IFS= read -r line; do
    venv_paths+=("$line")
  done < <(search_venvs "$path")
done


if [ ${#venv_paths[@]} -gt 0 ]; then
  selected_venv=$(printf '%s\n' "${venv_paths[@]}" | fzf --prompt="Select a virtual environment: ")
  if [ -n "$selected_venv" ]; then
    echo "You selected: $selected_venv"

    venv_name=$(basename "$selected_venv")
    venv_path=$(dirname "$selected_venv")

    cat <<EOL > pyrightconfig.json
{
  "venvPath": "$venv_path",
  "venv": "$venv_name"
}
EOL

    if [ -f "pyrightconfig.json" ]; then
      echo "pyrightconfig.json updated with the selected environment."
    else
      echo "pyrightconfig.json created with the selected environment."
    fi
  else
    echo "No virtual environment selected."
  fi
else
  echo "No virtual environments found."
fi
```

**Comment by srbh001** [comment]
A preview of this task in zed 
![ezgif-7-db247d0efb](https://github.com/zed-industries/zed/assets/116420817/439254fe-f8d8-4ee2-b3b5-dee57f95c001)

**Comment by pavelzw** [comment]
The [pixi package manager](https://github.com/prefix-dev/pixi) also creates conda environments and stores them in `$PWD/.pixi/envs/<env-name>`.

Adding something like 

```json
{
  "venvPath": ".pixi/envs/",
  "venv": "default"
}
```

works for pyright and IDE integration but `terminal.detect_venv` currently doesn't work with conda environments (and thus pixi environments) at all. There, you would need to run `pixi shell` or `eval "$(pixi shell-hook)"` to activate the environment.

**Comment by sapiosaturn** [comment]
in case anyone is having trouble resolving imports for a conda env even after setting the venv and venvpath to the correct values, what fixed it for me was also explicitly specifying the `pythonVersion` in the project pyrightconfig.json file

**Comment by MannavaVivek** [comment]
I am also having this issue wherein if I add pyrightconfig.json to my gitignore (because obviously, I don't want my local workspace settings overriding others') then the venv settings are not respected anymore, and I am back to having all the errors. Any suggestions on how to fix this?

**Comment by Alejandro-FA** [comment]
In my case, my `conda` environment was only detected when having a `pyrightconfig.json` with:

```json
{
  "venv": "great_project",
  "venvPath": "/Users/alex/miniconda3/envs/"
}
```

**AND** after moving the `conda init` setup from `.zshrc` to `.zprofile`. Furthermore, I noticed that specifying `venvPath` in the lsp settings of `settings.json` (instead of doing so in `pyrightconfig.json`) does not work.

**Comment by swarajban** [comment]
We have a monorepo with multiple python apps, each with its own virtualenv. How can I configure zed to use different virtualenvs for language highlights / running code for different directories? Can we have multiple pyrightconfig.json files pointing to different venvs?

**Comment by albas99** [comment]
I think what people are looking for is what VSCode does with virtual environments, regardless of whether it's from `venv` or 'conda env`, VSCode recognizes that environment and provides a UI to select which one to use.  This is one of the crucial features that I think would entice a lot of people into switching completely to Zed. Extensions is already a done deal, it's only a matter of does the extension you use exist in Zed?

https://github.com/user-attachments/assets/cfc4d563-52a0-4454-bd60-00d6a2478c6b

**Comment by arthur-st** [comment]
Agreed with @albas99 and @swarajban, we have multi-project repositories where people will be changing their active Python environment multiple times per day. Having to edit Zed settings and Pyright settings both, on every switch, is not the best UX.

**Comment by truh** [comment]
You can add multiple folders to a project in Zed, then every folder can have their own pyright config

**Comment by Muthukamalan** [comment]
Hi Team,

I tried to setup conda-env in repl.
- Is my config correct or am i missing something?
- can we setup project-setting config within workspace level? I don't want to messup otherworkspace


```
{
  "telemetry": {
    "diagnostics": true,
    "metrics": true
  },
  "ui_font_size": 15,
  "buffer_font_size": 15,
  "tab_size": 2,
  "theme": {
    "mode": "dark",
    "light": "One Light",
    "dark": "One Dark"
  },
  "jupyter": {
    "enabled": true,
    "kernel_selections": {
      "python3": "/home/muthu/miniconda3/envs/venv/share/jupyter/kernels/python3"
    }
  },
  "venv": "venv",
  "venvPath": "/home/muthu/miniconda3/envs"
}
```

**Comment by arthur-st** [comment]
A slash command would be much better UX than what's in place now, in all fairness. Not great, but clearly better.

**Comment by JaLnYn** [comment]
I've attempted to write a slash command but unable to read filesystem it seems. I've opened an issue: https://github.com/zed-industries/zed/issues/16933

**Comment by Pixel-Minions** [comment]
Hello everyone, first, love the project.

The issue is that now, I am using the basedpyright extension, and disabling pyright, it seems a bit complicated to configure the interpreter or not sure, if I have to go back to pyright to set the interpreter. But I guess that the place where the interpreter is set should be more global thank just to pyright, so all extension can use it.

**Comment by vincentamato** [comment]
I was having a hard time getting Zed to recognize a conda environment (pyrightconfig.json was not working), so I found a workaround. If you open the local settings and specify the exact python executable, it works:
```json
{
  "lsp": {
    "pyright": {
      "settings": {
        "python": {
          "pythonPath": "/Users/vincentamato/miniconda3/envs/cs1430/bin/python"
        }
      }
    }
  }
}
```
Hopefully this helps others who are having the same problem.

**Comment by aaishikdutta** [comment]
> For me the full paths didn't work either what does work is the following. I have my conda envs in the folder `/User/daniel/mambaforge/envs` (if I `ls` there I get a list of folders with the names of the environments I created). Let's say I have an env called "great_project". The following is the config for that:
> 
> ```json
> {
>   "venv": "great_project",
>   "venvPath": "/Users/daniel/mambaforge/envs"
> }
> ```

this worked for me as well, thnx

**Comment by docsteveharris** [comment]
FWIW it won't expand `~` so do as above in `pyrightconfig.json`
**Don't do**
```
{
  "venv": "great_project",
  "venvPath": "~/mambaforge/envs"
}
```

**Comment by PlexSheep** [comment]
I'd like to add that this is only really solved for the language server. For me at least, tools like integrated pytest or the builtin task system of zed still do not work with the virtual environments.

THe closest workaround I've found is using tasks like the following:

```jsonc
    {
        "label": "sennen generate (skip daily)",
        // this is hacky, but zed doesn't really understand venvs yet...
        "command": "source /home/plex/.pyenv/versions/sennen/bin/activate && poetry run sennen generate --skip-daily",
        "reveal": "never",
        "reveal_target": "dock",
        "hide": "always"
    },
    {
        "label": "pytest all",
        "command": "source /home/plex/.pyenv/versions/sennen/bin/activate && PYTHONPATH=/home/plex/Dokumente/code/py/sennen/src pytest",
        "reveal": "no_focus",
        "reveal_target": "dock",
        "hide": "never"
    }

```

This is not ideal, as these paths are specific to the local machine. They cannot easily be shared accross systems.

**Comment by RafayAhmad7548** [comment]
i cant seem to get zed to recoginze my python venv, i tried pyrightconfig.json, pyproject.toml, and also the local settings file, zed does show completions but running with repl doesnt work

**Comment by Chuong98CC** [comment]
am I the only one that could not get any of the suggestion working for Anaconda?
my `pyrightconfig.json` is placed at the root of folder, and
```
{
    "venv": "depthany",
    "venvPath": "/home/chuong/miniconda3/envs"
}
```
python path
```
❯ which python
/home/chuong/miniconda3/envs/depthany/bin/python
```
create a new terminal still using the base, no suggestion or importing lib does not work

**Comment by karannb** [comment]
@Chuong98CC With miniconda, it seems to be slightly different, this worked for me - 

```json
{
    "venv": "crawler",
    "venvPath": "/path/to/miniconda3/condabin/conda",
}
```

This is placed in `.zed/settings.json` in my current project directory.

**Comment by langrock** [comment]
None of this worked for me using miniforge. The project always reverts back to the 'base' conda environment instead of the one for the project. Every time one starts the editor one has to manually switch to the proper environment.

**Comment by rustanacexd** [comment]
its been years and this one is still not working. sad

**Comment by ODAncona** [comment]
Let's say I open a folder on a new project like
`uv init project` 
`uv venv`

How can I choose it using zed ? 

please this is much needed

**Comment by warpedgeoid** [comment]
So, there is no way for me to specify a conda or pyenv environment for a script without first creating a project? If true, this seems like a major oversight.
