### ISSUE TITLE
Tab Switcher

### ISSUE THREAD

**Issue by alygin** [zed-industries/zed#7653]
### Check for existing issues

- [X] Completed

### Describe the feature

When working on tabless editing mode (#6424), [there was a discussion](https://github.com/zed-industries/zed/pull/2742#issuecomment-1638903687) about the need to implement Tab Switcher -- a panel similar to the File Finder that would show the list of opened tabs in the active pane and allow to switch between them and close them right in this panel.

I tried to figure out how such switcher could look and how it could be implemented, and decided to file it as a separate feature request, because there's a lot of things to discuss (and probably to change in the code).

## How it will look and work

<img width="360" alt="zed-tab-switcher" src="https://github.com/zed-industries/zed/assets/2101250/e32ed164-f81b-4dfb-8222-1286d3b50c00">

- Default shortcut is `ctrl-tab`. It also moves selection to the next item.
- Selection is confirmed by either releasing of a modifier key (`ctrl` by default) or with a mouse click.
- Items are sorted in the reverse order of the tab activation history.
- Second item (if exists) is selected by default. This will allow to switch to the previous tab with a single keystroke.
- We need item icons here to distinguish files from terminal, search results etc.
- Close button is displayed when hover over item.
- Implemented using the existing Picker functionality, but with the query editor hidden.

## Tasks

- [x] Implement #8757
- [x] Implement headless picker #9099
- [ ] Implement tab switcher

## How others do this

See comments below:
- [VSCode](https://github.com/zed-industries/zed/issues/7653#issuecomment-1936952462)
- [IntelliJ IDEA](https://github.com/zed-industries/zed/issues/7653#issuecomment-1936952779)
- [Sublime Text](https://github.com/zed-industries/zed/issues/7653#issuecomment-1936952882)

## Related issues and PRs

- #6424
- https://github.com/zed-industries/zed/pull/2742#issuecomment-1638903687
- #7356
- #8757

**Comment by alygin** [comment]
### VSCode

VSCode has a tab bar dropdown menu wit the "Show Opened Editors" action in it:

<img width="299" alt="vscode-tab-bar-menu" src="https://github.com/zed-industries/zed/assets/2101250/487b9670-684b-4c27-82c8-0bcecdc76e4c">

When clicked, it displays a panel that is very similar to File Finder. Tabs of the selected pane (group) are listed in the reverse history order. Name, path, git status, modification mark etc. are the same as in the tabs, including the Close button:

<img width="604" alt="vscode-opened-editors-list" src="https://github.com/zed-industries/zed/assets/2101250/dceb2f39-a7ea-4910-b2e2-b47f1fb716a2">

VSCode also has the Open Editors panel that can be displayed in the left pane, along with the project structure:

<img width="317" alt="vscode-opened-editors-panel" src="https://github.com/zed-industries/zed/assets/2101250/87ceecdd-094a-443d-8920-4a1dccd22bac">

VSCode doesn't have a setting that would allow to automatically close tabs when there're too many of them.

**Comment by alygin** [comment]
### Jet Brains IDEA

IDEA doesn't provide such feature, though it also has a drop down menu in the tab bar that contains actions:

<img width="309" alt="idea-tab-bar-menu" src="https://github.com/zed-industries/zed/assets/2101250/ce142a28-3409-4a1e-addc-114ebb1a480d">

Though it provides ability to automatically close unused tabs to prevent cluttering when tab bar is hidden.

**Comment by alygin** [comment]
### Sublime Text

Sublime Text has an "Add" button and a simple dropdown list with opened tabs:

<img width="339" alt="sublime-tab-bar-menu" src="https://github.com/zed-industries/zed/assets/2101250/4a3d0854-d6e4-4b63-a13f-4eb0dfd8ac00">

**Comment by diocletiann** [comment]
If Zed had a unified bufferline this wouldn't be an issue.

**Comment by alexander-irbis** [comment]
> IDEA doesn't provide such feature

Idea provides such feature (with additional options where to switch). Also it allows to select elements in the list with arrows (while Ctrl is pressed).

<img width="591" alt="image" src="https://github.com/zed-industries/zed/assets/1448323/458a5549-a8d8-4dac-897e-049956cf244d">

**Comment by alygin** [comment]
> Idea provides such feature

You're right, thanks for pointing that out! I've added a link to your comment.

**Comment by oxaronick** [comment]
If Zed supports ctrl-tab to switch between recent tabs the way VSCode and Firefox do, that will be great.

**Comment by maximvl** [comment]
Nice one! I hope a fuzzy-search feature can be added too, it is so convenient to use it after trying it in Emacs.

**Comment by tymscar** [comment]
I can back up what @maximvl is saying. I'm coming from emacs and being able to fuzzy search open tabs (buffers) is a massive benefit!

**Comment by ceuk** [comment]
More prior art around filtering open buffers/tabs can be seen in (neo)vim extensions such as Telescope's [`buffers`](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#vim-pickers) picker
