### ISSUE TITLE
buffer search: No results indicator (red border) not removed when switching from regex to text mode

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#7658]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you search for something that has results in text mode, but no results in regex mode this can happen:

https://github.com/zed-industries/zed/assets/19362696/7c951838-6094-4abe-93ac-5e53724f9346

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @N8th8n8el, thanks for letting us know. I just double checked and the behavior still exists (#7675 recently merged and changed some things). @alygin, is this something you might be interested in fixing? No worries if not.

**Comment by alygin** [comment]
@JosephTLyons, yeah, sure, I'll take a look.

**Comment by N8th8n8el** [comment]
This can be closed now @alygin, right?

**Comment by SomeoneToIgnore** [comment]
Yes, according to the PR message, closing optimistically.

**Comment by alygin** [comment]
> This can be closed now @alygin, right?

Yes, the described erroneous behaviour was fixed.
