### ISSUE TITLE
terminal: Search option state weirdly shared with buffer search

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#7660]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Switching the search mode (text/regex) in the buffer search of an editor changes the terminal search mode instead if the terminal was previously in focus.

https://github.com/zed-industries/zed/assets/19362696/f6ebb5f8-0c13-45b0-a12e-27f1c0611d4b

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by N8th8n8el** [comment]
Seem like the `ActivateRegexMode` action is sent to the wrong `BufferSearchBar` instance (logged the memory addresses of both instances).

**Comment by JosephTLyons** [comment]
Hey @N8th8n8el, are you able to reproduce this faithfully? I see it in your video, so I know it exists, but haven't been able to repro on my end - just curious.

**Comment by N8th8n8el** [comment]
I can't on 
```
Zed: v0.122.2 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64
```
but can on 
```
Zed: v0.123.1 (Zed Dev)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64
```
(debug built of current `main`).
