### ISSUE TITLE
doesn't render layouts properly on Mac M1

### ISSUE THREAD

**Issue by TwistingTwists** [zed-industries/zed#7667]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The pane becomes blank.

Try to horizontal split followed by vertical split on left pane. 

I think this maybe due to my zed settings. 
```json
"active_pane_magnification": 1.7
```

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1728" alt="image" src="https://github.com/zed-industries/zed/assets/11463027/780fc772-262f-494e-ac78-3d950d68bef1">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by TwistingTwists** [comment]
after I click on the left bottom tab, i can see it clearly, but otherwise, it remains like this.

**Comment by JosephTLyons** [comment]
Yep, I'm able to reproduce this with the same setting @TwistingTwists, nice work on narrowing it down to that.

**Comment by TwistingTwists** [comment]
I'd be happy to contribute a bug fix. 

Would you be open to a PR?

**Comment by JosephTLyons** [comment]
> I'd be happy to contribute a bug fix.
> 
> Would you be open to a PR?

Yeah, absolutely!

**Comment by TwistingTwists** [comment]
@JosephTLyons  Can you please point me to the files / folders where I should go looking?

**Comment by tugkanpilka** [comment]
I think the problem is expanding panes with statically typed flex value.

```rust
let child_flex = active_pane_magnification
.map(|magnification| {
    if self.active_pane_ix == Some(ix) {
        magnification
    } else {
        1.
    }
})
.unwrap_or_else(|| flexes[ix]);
```

I've changed the `1.` with `total_flex / len as f3` which is a dynamic flex value which calculating the flex for each inactive pane in a pane group and the problem fixed.

Do you have any comments or suggestions? @JosephTLyons
