### ISSUE TITLE
GPUI Transparency

### ISSUE THREAD

**Issue by jafioti** [zed-industries/zed#7668]
### Check for existing issues

- [X] Completed

### Describe the feature

Native GPUI support for transparency would allow mac apps to match the feel of macos builtin apps, which are often translucent.

I understand this is a more involved feature to add, and I'd love to contribute if it helps, I just don't know where to start. Any pointers in the right direction would be welcome!

### If applicable, add mockups / screenshots to help present your vision of the feature

Something like this is what I'm going for:

<img width="997" alt="Screenshot 2024-02-10 at 11 56 04 PM" src="https://github.com/zed-industries/zed/assets/13525371/0573caf2-736b-46c4-b8a6-58e1b705a491">

which matches how many macos apps look (including spotlight search).

**Comment by ronanxe** [comment]
![2024-02-12T04-36-34,232683396-05-30.png](https://github.com/zed-industries/zed/assets/159469572/a5dd7b1e-de2c-473c-9b6f-57cc6d6da90a)

![2024-02-12T04-43-41,962712933-05-30.png](https://github.com/zed-industries/zed/assets/159469572/9b5e0b38-5166-461e-8c55-9593f3814c28)

![2024-02-12T04-41-55,161740627-05-30.png](https://github.com/zed-industries/zed/assets/159469572/1eaf575e-d352-4c50-b636-7bde246a0620)

![2024-02-12T04-44-35,208305100-05-30.png](https://github.com/zed-industries/zed/assets/159469572/94cdd3d6-48dc-4018-a89a-bf5005530365)

**Comment by WeetHet** [comment]
How about we also include the blur support in this issue as it also is a necessary part of the native looking applications in macOS?

**Comment by JosephTLyons** [comment]
Let's go ahead and close this one out in favor of #5040. For those following this thread, please upvote #5040 with a 👍 reaction.  As for where to get some help on maybe implementing this, maybe @mikayla-maki or @ForLoveOfCats would know what layer to start with.
