### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by oepir** [zed-industries/zed#7678]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to compile Zed, I followed the instructions. However, I run into the following error:
  [1/1] Planning build
  Compiling plugin SwiftProtobufPlugin...
  Building for debugging...
  [1/5] Compiling LiveKit LocalParticipant.swift
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Participant/LocalParticipant.swift:352:34: error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate
          let name = _state.mutate {
                                   ^
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Participant/LocalParticipant.swift:364:38: error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate
          let metadata = _state.mutate {
                                       ^
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Participant/LocalParticipant.swift:550:33: error: cannot convert return expression of type 'Promise<LocalTrackPublication>' to return type 'Promise<Promise<LocalTrackPublication?>>'
                      return self.publishVideoTrack(track: track, publishOptions: publishOptions as? VideoPublishOptions)
                                  ^
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Participant/LocalParticipant.swift:550:33: note: arguments to generic parameter 'Value' ('LocalTrackPublication' and 'Promise<LocalTrackPublication?>') are expected to be equal
                      return self.publishVideoTrack(track: track, publishOptions: publishOptions as? VideoPublishOptions)
                                  ^
  [2/5] Compiling LiveKit VideoCapturer.swift
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Track/Capturers/VideoCapturer.swift:120:47: error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate
              let didStart = self._state.mutate {
                                                ^
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Track/Capturers/VideoCapturer.swift:148:46: error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate
              let didStop = self._state.mutate {
                                               ^
  [3/5] Emitting module LiveKit
  [4/5] Compiling LiveKit MacOSScreenCapturer.swift
  /Users/sduvan/code/zed/target/aarch64-apple-darwin/LiveKitBridge_target/checkouts/client-sdk-swift/Sources/LiveKit/Track/Capturers/MacOSScreenCapturer.swift:768:20: error: cannot convert return expression of type 'MacOSDisplay' to return type 'Promise<MacOSDisplay>'
              return source
                     ^~~~~~
  thread 'main' panicked at crates/live_kit_client/build.rs:80:9:
  Failed to compile swift package in /Users/sduvan/code/zed/crates/live_kit_client/LiveKitBridge

% rustc --version
rustc 1.76.0 (07dca489a 2024-02-04)
MacOS version: 13.6.4 (22G513)

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 13.6.4
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Do you have Xcode setup correctly? What version do you have? Do you maybe have a different clang in your `$PATH`? See: https://github.com/zed-industries/zed/issues/7541#issuecomment-1934116399

**Comment by oepir** [comment]
I eventually got things working by upgrading XCode.  Version 15.2 seems to work while version 13.3.1 did not.
