### ISSUE TITLE
Rendering is done in sRGB color space instead of linear

### ISSUE THREAD

**Issue by kvark** [zed-industries/zed#7684]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Following up on #7666.
The surface format used in Zed is currently `BGRA8Unorm`, and we aren't explicitly requesting a color space from `CALayer`. Default color space is always "srgb non-linear". You can see this in [VkColorSpace](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkColorSpaceKHR.html): `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR` is zero. On Metal, a similar setting called [colorspace](https://developer.apple.com/documentation/coregraphics/cgcolorspace) exists, but the documentation is less explicit:
> The default value is nil, indicating that the rendered content isn’t color-matched.

What this means is - Metal wouldn't be trying to configure the monitor in any way. And the convention for the monitors since CRT days is that they assume the surface data is in "sRGB" space. See https://bottosson.github.io/posts/colorwrong/#non-linear-transfer-function.
In practice, your colors are going to be put to the power of "2.2" (roughly) before being emitted by the display, which makes colors darker.

This isn't easily evident in general because most of the colors come from constants (the visual "theme"), and theme authors make sure that these constants are specified in a way that makes a particular end result visually. So, as long as you only ever display a constant color from some table - it's OK. Problem shows up in the interpolation of colors: gradients and blending, as you can see in the blog post by Björn Ottosson. Zed isn't a full-featured browser, but technically it does blending on all primitives, so it's affected by using the wrong color space.

Here is how we could fix this. Proposal:
1. Switch the `CALayer` format to be `BGRA8Unorm_srgb`.
2. For any image that is taken from the outside, it should be assumed that the contents are in sRGB format, so the associated texture should also be in `BGRA8Unorm_srgb`.
3. All the intermediate data, such as the sprite atlas, would still use `BGRA8Unorm`. It means - to assume linear color space at this step in the pipeline.
4. In the shader code for `hsla_to_rgba`, we'd also do the "srgb -> linear" conversion, since all of the theme data today is assumed to be in sRGB color space. Can also do it earlier in the pipeline, e.g. when a theme is loaded.

### Environment

macOS

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I don't know how to create a gradient in Zed/GPUI.

**Comment by jansol** [comment]
Given the woes wayland devs have had with defining how untagged surfaces should be handled I'm not entirely sure about that "[monitors] assume the surface data is sRGB" bit, although there certainly often is "sort of" that kind of assumption. But I digress.

CSS does [explicitly default to sRGB](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color) so for theming it makes a lot of sense to do the same, regardless of internal rendering colorspace.

As for gradients, I think you'd see the inaccuracies if you zoom in on the rounded border of an element with a different color than the background? And of course on font glyphs.

**Comment by mikayla-maki** [comment]
We do want to extend GPUI to support gradients and such, so getting this right is important.
