### ISSUE TITLE
Add an option to disable "open last project on start"

### ISSUE THREAD

**Issue by glebsam** [zed-industries/zed#7694]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add an option to disable "open last project on start". I don't need to spin up the whole LSP machinery just to have a quick look on some file (or just use Zed as a simple lightweight text editor).

**Comment by evrsen** [comment]
On top of that I'd also like to be able to close a project and have zed remember that my last window didn't have a project open.

**Comment by defaude** [comment]
I would really like to have the option to configure the behavior:

**Either** always re-open the project(s) that were opened when zed exited.

**Or** don't remember anything. Open the folder/project I gave to zed on launch - or just give me a blank, fresh window when no folder/project was given at launch

**Comment by haunt98** [comment]
Finally, thanks @osiewicz for your hard work

**Comment by defaude** [comment]
Thank you so much - you totally ROCK 😍

**Comment by lufog** [comment]
I added `"restore_on_startup": "none"` to the `settings.json`, but it had no effect. When I close the editor and open it again, it opens with the project (folder) already loaded.

Perhaps I'm doing something wrong...

Arch Linux
Zed 0.142.6

**Comment by romanovzky** [comment]
I have the same issues as @lufog , Zed 0.144.4

**Comment by JGMelon22** [comment]
Same issue as you guys as well.
Zed 0.144.4
Arch Linux X11
