### ISSUE TITLE
Add some kind of an SQL viewer

### ISSUE THREAD

**Issue by SsNiPeR1** [zed-industries/zed#7695]
### Check for existing issues

- [X] Completed

### Describe the feature

An SQL (specifically, SQLite) viewer would be useful to observe your databases easily

### If applicable, add mockups / screenshots to help present your vision of the feature

Something like that: https://marketplace.visualstudio.com/items?itemName=qwtel.sqlite-viewer

**Comment by jansol** [comment]
Duplicate of #4838

**Comment by SsNiPeR1** [comment]
> Duplicate of #4838

whoops, overlooked
