### ISSUE TITLE
Buffer search layout fixes

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#7703]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The padding on the `replace next` button should probably match the padding on the button above

<img width="766" alt="image" src="https://github.com/zed-industries/zed/assets/19867440/6f73196a-343d-4b35-b263-5b70a405b987">

### Environment

Zed: v0.123.0 (Zed Nightly)
OS: macOS 14.1.2
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by alygin** [comment]
@JosephTLyons, thanks, I’ll fix the padding issues in the buffer search bar (there’s also one with the ”select all matches” button) and change the project search bar layout.

**Comment by JosephTLyons** [comment]
Close via https://github.com/zed-industries/zed/pull/7715
