### ISSUE TITLE
Ctrl + ^ (Ctrl + 6) doesn't toggle between alternate files

### ISSUE THREAD

**Issue by danielnieto** [zed-industries/zed#7709]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Vim's [Ctrl+^ shortcut allows you to toggle between two files](https://vimhelp.org/editing.txt.html#CTRL-%5E), meaning that if you open two files and keep pressing Ctrl + ^, it will loop through these 2 files. Currently on Zed, it just show the "alternate file" (the old one) but if you press it again, then nothing happens, so in reality it just goes back to the previous file, once.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by baldwindavid** [comment]
This can be done with the tab switcher (`ctrl + tab` by default) as it switches between the two most recent tabs, but looks like #11367 does it without a flash of the modal.

**Comment by ConradIrwin** [comment]
This was fixed by #11367
