### ISSUE TITLE
Support injected language syntax

### ISSUE THREAD

**Issue by derekperkins** [zed-industries/zed#7710]
### Check for existing issues

- [X] Completed

### Describe the feature

IntelliJ supports language injections, so that you can get full language support for subsets of a file. For example, it's common to have SQL or HTML snippets inside another language file like Rust or Go. IntelliJ auto-matches those and adds syntax highlighting automatically, or you can do temporary / permanent injections manually.
https://www.jetbrains.com/help/idea/using-language-injections.html

**Comment by JosephTLyons** [comment]
Hey @derekperkins, Zed does support language injections, its just that at the moment, they are hardcoded for specific languages we have baked into Zed. We are working on plugins right now and are moving things out of Zed, so at some point, we will probably need to make this a configurable thing.

**Comment by MordFustang21** [comment]
Just saw this PR for adding regex injection into js/ts. I assume we can do something similar in Go once we get sql support. https://github.com/zed-industries/zed/pull/7851/files I'm not sure how detailed you can get in the queries to be able to narrow it down to a sql string though.

**Comment by JosephTLyons** [comment]
Zed supports arbitrary injections now.

**Comment by MordFustang21** [comment]
> Zed supports arbitrary injections now.

Is this a recent change? I tried implementing this a couple weeks ago and couldn't get sql to inject into a Go string, I was only able to get regex working.

**Comment by firu11** [comment]
In Go, regex highlighting works great! But I can't get inline SQL highlighting to work. I even tried both string literals (`"` and ``` ` ```).

```go
func crazyRegex() {
	regexp.Compile("a-z{2-4}|0-9+|A-Z*")      // ✅ highlighting
	s := "a-z{2-4}|0-9+|A-Z*"                 // ⚠️ highlighting (which is ok I guess)
}

func innocentQuery() {
	DB.Query(`DELETE FROM user WHERE TRUE;`)  // ❌ highlighting
	DB.Query("DELETE FROM user WHERE TRUE;")  // ❌ highlighting
}
```

**Comment by polc** [comment]
I also was unable to highlight SQL in PHP : 

```php
<?php

$query = "DELETE FROM user WHERE TRUE"; // ❌ highlighting
```

**Comment by firu11** [comment]
Still not working...
Could we reopen this issue?

@MordFustang21 @JosephTLyons

**Comment by alkarkhi** [comment]
Doesn't work for me in Rust for both Regex and SQL

<img width="481" height="94" alt="Image" src="https://github.com/user-attachments/assets/9e4b0342-7818-4590-9a62-cd1aba789863" />

**Comment by SuperluminalKnight** [comment]
Does not work for styled-jsx npm package

<img width="609" height="487" alt="Image" src="https://github.com/user-attachments/assets/d682d0fd-ac81-4637-b0e4-bad08e673435" />

**Comment by Sk7Str1p3** [comment]
this is less trivial tho, but i couldn't get nushell syntax highlighting in nix files

<img width="736" height="263" alt="Image" src="https://github.com/user-attachments/assets/a388150e-f762-4545-9afe-0eab31e22929" />
