### ISSUE TITLE
Visual cue to know if it is a variable or a function or a class

### ISSUE THREAD

**Issue by eznix86** [zed-industries/zed#7717]
### Check for existing issues

- [X] Completed

### Describe the feature

Autocompletion is great but when peaking inside a class or a sub item we should know if it is a function or a class. We need a visual cue of what it is without hovering on it. 

### If applicable, add mockups / screenshots to help present your vision of the feature

For PHP
<img width="478" alt="Screenshot 2024-02-13 at 10 52 19" src="https://github.com/zed-industries/zed/assets/26553194/bde7d37e-58e9-4bdc-a2ae-0410f08c81da">

For Python
<img width="343" alt="Screenshot 2024-02-13 at 10 54 19" src="https://github.com/zed-industries/zed/assets/26553194/434f46fa-051a-4560-aad3-fef7f41b2e2f">

Currently when we want to access values from a class or a sub item of a value we do not know if it is a class or a function. There is no visual cue.

Vscode Example:

<img width="616" alt="Screenshot 2024-02-13 at 10 56 52" src="https://github.com/zed-industries/zed/assets/26553194/186999ad-0049-4cf5-9b54-fe493d83a60f">
<img width="647" alt="Screenshot 2024-02-13 at 10 57 51" src="https://github.com/zed-industries/zed/assets/26553194/8b1dfd7e-b562-43f0-8a88-261f6206ffe6">

We have a little bit of insight because of the symbols, we know which are functions and which are variables.

**Comment by jansol** [comment]
Previously seen as #5287, please upvote that instead.

**Comment by JosephTLyons** [comment]
Closing in favor of #5287.
