### ISSUE TITLE
Include the Lapce editor on the Zed website

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#7725]
### Check for existing issues

- [X] Completed

### Describe the feature

[Lapce](https://lapce.dev) is another popular GUI code editor written in Rust that's growing in popularity. It would be fair to include this editor in the insertion latency, startup time and memory footprint tests. Here's why:
- Lapce and Zed are the only two rising GUI editors written in Rust
- Both are developed with performance in mind
- In terms of UX both are aimed to be alternatives to the popular VSC editor.

With that said, comparing the two can lead to two benefits:
- Competition, as said above both are popular GUI editors within the Rust ecosystem and so, a healthy competition would lead to frequent development of both editors for the better, just like how Apple and Samsung have had an ever-going competition for features and UX.
- Marketing, asserting that one is leading in X can draw attention.

Sublime is more so a legacy editor these days, CLion is aimed for power users with huge feature integrations, and VSC is a fair competition to go against but the majority of the users who cares enough to look for alternatives already knows VSC is a bloated browser. And so, I think competing more with Lapce 1-1 would be better.

**Comment by AndydeCleyre** [comment]
> Sublime is more so a legacy editor these days

I am eagerly awaiting the development of *any* open source editor to offer me the features, performance, and resource usage of Sublime Text 4, which currently achieves either 2nd or 1st place in each of the metrics charted on Zed's homepage.

Aside from not understanding this take, I don't know what it adds to the issue description in any case. Unless you're requesting that ST4 be removed from the comparison? If so, I would push back against that, as I am looking to switch to Zed if and only if it ever out-competes ST4 specifically.

**Comment by evrensen467** [comment]
I'm not requesting for any editor to be removed, I'm requesting to add another editor. Competition is a good thing, and Lapce is another open source code editor written in rust that's also characterized by its performance, it would be more than fair to include them in these benchmarks.

**Comment by teotikalki** [comment]
This is actually the only comparison I was looking for on that page... comparing yourself to incumbents is fine, but it's extremely relevant to compare yourself to your direct competition.

People leaving Atom/Suublime/VSCode/etc already know that they want something new or we wouldn't be at your site in the first place. I can't think that it's uncommon that someone is trying to decide which of Lapce/Zed to switch TO from *any* of those.

**Comment by AndydeCleyre** [comment]
Can someone link to the current comparison? I tried using the site search for each of "comparison," "lapce", and "sublime," but can't find it.

**Comment by nervenes** [comment]
@AndydeCleyre i think they removed it completely, hence i closed this issue
