### ISSUE TITLE
Characters sent to terminal when `option_as_meta` is true

### ISSUE THREAD

**Issue by sam-lord** [zed-industries/zed#7728]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With config:
```JSON
   "terminal": {
        "option_as_meta": true
    }
```

In terminal, open Emacs (`emacs -nw`), use option+X (Emacs binding `M-x`), instead of just opening the minibuffer, it's opened and types `≈` (which is the character typed by Option+X). This character shouldn't appear, but it seems like option+X and meta+X are both sent.

Alternatively, just use `M-x` outside of emacs, and see that ≈ is typed.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.2.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by slidingshade** [comment]
Same thing when using Option+b, Option+f in command line, it navigating through the command text (word forward backward) but also types ∫ and ƒ  symbols.

**Comment by sam-lord** [comment]
> Same thing when using Option+b, Option+f in command line, it navigating through the command text (word forward backward) but also types ∫ and ƒ symbols.

Yeah, thank you for mentioning that. I tried to mention this in the original issue, but this applies to all keystrokes with a respective Option character.

**Comment by filedesless** [comment]
here's a crude workaround filedesless/zed@cc2849e

**Comment by denisw** [comment]
It seems like the following two event callbacks are called independently of another (in that order):

1. `TerminalView::send_keystroke` (which forwards e.g. option+b to the shell)
2. `InputHandler::replace_text_in_range` implementation of `TerminalElement` (adds the character)

I wonder if GPUI offers some way for callback 1 to stop further handling of the key press so that callback 2 is not called anymore.

**Comment by denisw** [comment]
I found a fix: #14151
