### ISSUE TITLE
Modal UI should not be closing on a temporary focus loss

### ISSUE THREAD

**Issue by romans-ovo** [zed-industries/zed#7729]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When any UI is open like this one:

<img width="1096" alt="Screenshot 2024-02-13 at 13 12 45" src="https://github.com/zed-industries/zed/assets/92028468/b3b6cfb5-aee2-47f1-be7b-d19acefa6aa6">

and editor looses focus (i have focus-follows-mouse on mac) this also closes the UI (project selection ui). I believe there is no reason to close UI just because Zed window lost focus. Ideally it could close if focus is not regained within 1 second.

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by alygin** [comment]
Looks like a duplicate of #7503
