### ISSUE TITLE
Disable Copilot for certain file types

### ISSUE THREAD

**Issue by dwt** [zed-industries/zed#7730]
### Check for existing issues

- [X] Completed

### Describe the feature

When using copilot, I do not want certain files to be fed into copilot as context ever. For example `.env` files that hold passwords and other credentials for critical infrastructure should _never_ get sent to potentially untrusted parties like OpenAI.

Apart from this being totally reasonable, this is also a requirement from our data protection department that prevents me from trying this editor on company code.

### If applicable, add mockups / screenshots to help present your vision of the feature

This could be done in the settings file, not quite sure what the best syntax should be? In VSCode or IDEA I can disable Copilot for certain file types and be done with this.

**Comment by jylamont** [comment]
I think this already exists: https://zed.dev/docs/configuring-zed#copilot

**Comment by dwt** [comment]
Oh indeed! Thanks!
