### ISSUE TITLE
Duplicating file names on project structure when renaming file on terminal

### ISSUE THREAD

**Issue by valdirmendesdev** [zed-industries/zed#7732]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/1057524/5d4fa1f9-c4bb-4018-9720-0f3fce08504f

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Thanks for the report @valdirmendesdev. I have a sneaking suspicion that this is related to:

- https://github.com/zed-industries/zed/issues/5211

**Comment by valdirmendesdev** [comment]
Hey @JosephTLyons! Yes! I think can be the same! Sorry, if it is duplicated! I searched before open the issue and I didn't find anything.

**Comment by mrnugget** [comment]
@JosephTLyons this here is definitely fixed by https://github.com/zed-industries/zed/pull/7768, so I'm going to close it. The other issue still seems to be a problem, #5211.
