### ISSUE TITLE
Zed panics when entering a channel with a custom theme

### ISSUE THREAD

**Issue by jaimeelso** [zed-industries/zed#7733]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you load a theme customization file into ~/.config/zed/themes and use it in Zed, when you go to collaboration and try to enter a channel, the application crashes and closes.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[2024-02-13T17:05:10+01:00 ERROR util] crates/theme/src/settings.rs:344: theme not found: Catppuccin Latte
[2024-02-13T17:05:10+01:00 ERROR util] crates/extension/src/extension_store.rs:124: No such file or directory (os error 2)
[2024-02-13T17:05:10+01:00 ERROR util] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
[2024-02-13T17:05:10+01:00 ERROR util] crates/extension/src/extension_store.rs:139: failed to read extensions directory

Caused by:
    No such file or directory (os error 2)
Thread "main" panicked with "attempt to calculate the remainder with a divisor of zero" at crates/theme/src/styles/players.rs:143:16
   0: backtrace::backtrace::libunwind::trace
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized::<<backtrace::capture::Backtrace>::create::{closure#0}>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace::<<backtrace::capture::Backtrace>::create::{closure#0}>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/mod.rs:53:14
   2: <backtrace::capture::Backtrace>::create
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:176:9
   3: <backtrace::capture::Backtrace>::new
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:140:22
   4: Zed::init_panic_hook::{closure#0}
             at crates/zed/src/main.rs:586:29
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   8: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   9: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  10: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  11: <theme::styles::players::PlayerColors>::color_for_participant
             at crates/theme/src/styles/players.rs:143:16
  12: <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}
             at crates/collab_ui/src/collab_titlebar_item.rs:129:56
  13: <&mut <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2} as core::ops::function::FnMut<(&&call::participant::RemoteParticipant,)>>::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:294:13
  14: <core::slice::iter::Iter<&call::participant::RemoteParticipant> as core::iter::traits::iterator::Iterator>::find_map::<gpui::elements::div::Stateful<gpui::elements::div::Div>, &mut <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/iter/macros.rs:319:38
  15: <core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}> as core::iter::traits::iterator::Iterator>::next
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/adapters/filter_map.rs:63:9
  16: <core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>, <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::children<gpui::elements::div::Stateful<gpui::elements::div::Div>, core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>>::{closure#0}> as core::iter::traits::iterator::Iterator>::next
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/adapters/map.rs:104:9
  17: <smallvec::SmallVec<[gpui::element::AnyElement; 2]> as core::iter::traits::collect::Extend<gpui::element::AnyElement>>::extend::<core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>, <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::children<gpui::elements::div::Stateful<gpui::elements::div::Div>, core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>>::{closure#0}>>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smallvec-1.11.1/src/lib.rs:2076:36
  18: <gpui::elements::div::Div as gpui::element::ParentElement>::extend::<core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>, <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::children<gpui::elements::div::Stateful<gpui::elements::div::Div>, core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>>::{closure#0}>>
             at crates/gpui/src/elements/div.rs:1048:9
  19: <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::extend::<core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>, <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::children<gpui::elements::div::Stateful<gpui::elements::div::Div>, core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>>::{closure#0}>>
             at crates/gpui/src/elements/div.rs:2239:9
  20: <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::children::<gpui::elements::div::Stateful<gpui::elements::div::Div>, core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>>
             at crates/gpui/src/element.rs:171:9
  21: <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}
             at crates/collab_ui/src/collab_titlebar_item.rs:122:29
  22: <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::util::FluentBuilder>::when_some::<((alloc::sync::Arc<client::user::User>, rpc::proto::PeerId), gpui::app::entity_map::Model<call::room::Room>), <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}>::{closure#0}
             at crates/gpui/src/util.rs:37:17
  23: <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::util::FluentBuilder>::map::<gpui::elements::div::Stateful<gpui::elements::div::Div>, <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::util::FluentBuilder>::when_some<((alloc::sync::Arc<client::user::User>, rpc::proto::PeerId), gpui::app::entity_map::Model<call::room::Room>), <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}>::{closure#0}>
             at crates/gpui/src/util.rs:19:9
  24: <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::util::FluentBuilder>::when_some::<((alloc::sync::Arc<client::user::User>, rpc::proto::PeerId), gpui::app::entity_map::Model<call::room::Room>), <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}>
             at crates/gpui/src/util.rs:35:9
  25: <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render
             at crates/collab_ui/src/collab_titlebar_item.rs:91:17
  26: gpui::view::any_view::request_layout::<collab_ui::collab_titlebar_item::CollabTitlebarItem>::{closure#0}
             at crates/gpui/src/view.rs:421:54
  27: <gpui::window::WindowContext as gpui::VisualContext>::update_view::<collab_ui::collab_titlebar_item::CollabTitlebarItem, gpui::element::AnyElement, gpui::view::any_view::request_layout<collab_ui::collab_titlebar_item::CollabTitlebarItem>::{closure#0}>
             at crates/gpui/src/window.rs:1748:22
  28: <gpui::window::element_cx::ElementContext as gpui::VisualContext>::update_view::<collab_ui::collab_titlebar_item::CollabTitlebarItem, gpui::element::AnyElement, gpui::view::any_view::request_layout<collab_ui::collab_titlebar_item::CollabTitlebarItem>::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:284:9
  29: <gpui::view::View<collab_ui::collab_titlebar_item::CollabTitlebarItem>>::update::<gpui::window::element_cx::ElementContext, gpui::element::AnyElement, gpui::view::any_view::request_layout<collab_ui::collab_titlebar_item::CollabTitlebarItem>::{closure#0}>
             at crates/gpui/src/view.rs:75:9
  30: gpui::view::any_view::request_layout::<collab_ui::collab_titlebar_item::CollabTitlebarItem>
             at crates/gpui/src/view.rs:421:27
  31: <gpui::view::AnyView as gpui::element::Element>::request_layout::{closure#0}
             at crates/gpui/src/view.rs:292:40
  32: <gpui::window::element_cx::ElementContext>::with_view_id::<(gpui::taffy::LayoutId, gpui::view::AnyViewState), <gpui::view::AnyView as gpui::element::Element>::request_layout::{closure#0}>::{closure#0}
             at crates/gpui/src/window/element_cx.rs:1136:30
  33: <gpui::text_system::line_layout::LineLayoutCache>::with_view::<(gpui::taffy::LayoutId, gpui::view::AnyViewState), <gpui::window::element_cx::ElementContext>::with_view_id<(gpui::taffy::LayoutId, gpui::view::AnyViewState), <gpui::view::AnyView as gpui::element::Element>::request_layout::{closure#0}>::{closure#0}>
             at crates/gpui/src/text_system/line_layout.rs:329:22
  34: <gpui::text_system::WindowTextSystem>::with_view::<(gpui::taffy::LayoutId, gpui::view::AnyViewState), <gpui::window::element_cx::ElementContext>::with_view_id<(gpui::taffy::LayoutId, gpui::view::AnyViewState), <gpui::view::AnyView as gpui::element::Element>::request_layout::{closure#0}>::{closure#0}>
             at crates/gpui/src/text_system.rs:295:9
  35: <gpui::window::element_cx::ElementContext>::with_view_id::<(gpui::taffy::LayoutId, gpui::view::AnyViewState), <gpui::view::AnyView as gpui::element::Element>::request_layout::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:1131:9
  36: <gpui::view::AnyView as gpui::element::Element>::request_layout
             at crates/gpui/src/view.rs:284:9
  37: <gpui::element::DrawableElement<gpui::view::AnyView>>::request_layout::{closure#0}
             at crates/gpui/src/element.rs:286:17
  38: <gpui::window::element_cx::ElementContext>::with_element_state::<gpui::view::AnyViewState, gpui::taffy::LayoutId, <gpui::element::DrawableElement<gpui::view::AnyView>>::request_layout::{closure#0}>::{closure#0}
             at crates/gpui/src/window/element_cx.rs:623:43
  39: <gpui::window::element_cx::ElementContext>::with_element_id::<gpui::taffy::LayoutId, gpui::window::ElementId, <gpui::window::element_cx::ElementContext>::with_element_state<gpui::view::AnyViewState, gpui::taffy::LayoutId, <gpui::element::DrawableElement<gpui::view::AnyView>>::request_layout::{closure#0}>::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:414:26
  40: <gpui::window::element_cx::ElementContext>::with_element_state::<gpui::view::AnyViewState, gpui::taffy::LayoutId, <gpui::element::DrawableElement<gpui::view::AnyView>>::request_layout::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:574:9
  41: <gpui::element::DrawableElement<gpui::view::AnyView>>::request_layout
             at crates/gpui/src/element.rs:285:29
  42: <core::option::Option<gpui::element::DrawableElement<gpui::view::AnyView>> as gpui::element::ElementObject>::request_layout
             at crates/gpui/src/element.rs:407:9
  43: <gpui::element::AnyElement>::request_layout
             at crates/gpui/src/element.rs:450:9
  44: <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0}
             at crates/gpui/src/elements/div.rs:1069:38
  45: <&mut <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0} as core::ops::function::FnOnce<(&mut gpui::element::AnyElement,)>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:305:13
  46: <core::option::Option<&mut gpui::element::AnyElement>>::map::<gpui::taffy::LayoutId, &mut <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0}>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1072:29
      <core::iter::adapters::map::Map<core::slice::iter::IterMut<gpui::element::AnyElement>, <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0}> as core::iter::traits::iterator::Iterator>::next
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/adapters/map.rs:104:26
  47: <smallvec::SmallVec<[gpui::taffy::LayoutId; 2]> as core::iter::traits::collect::Extend<gpui::taffy::LayoutId>>::extend::<core::iter::adapters::map::Map<core::slice::iter::IterMut<gpui::element::AnyElement>, <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0}>>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smallvec-1.11.1/src/lib.rs:2076:36
  48: <smallvec::SmallVec<[gpui::taffy::LayoutId; 2]> as core::iter::traits::collect::FromIterator<gpui::taffy::LayoutId>>::from_iter::<core::iter::adapters::map::Map<core::slice::iter::IterMut<gpui::element::AnyElement>, <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0}>>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smallvec-1.11.1/src/lib.rs:2060:9
  49: <core::iter::adapters::map::Map<core::slice::iter::IterMut<gpui::element::AnyElement>, <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}::{closure#0}> as core::iter::traits::iterator::Iterator>::collect::<smallvec::SmallVec<[gpui::taffy::LayoutId; 2]>>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2054:9
  50: <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}
             at crates/gpui/src/elements/div.rs:1066:40
  51: <gpui::window::element_cx::ElementContext>::with_text_style::<<gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}, gpui::taffy::LayoutId>
             at crates/gpui/src/window/element_cx.rs:381:26
  52: <gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}
             at crates/gpui/src/elements/div.rs:1065:17
  53: <gpui::elements::div::Interactivity>::layout::<<gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}>
             at crates/gpui/src/elements/div.rs:1273:25
  54: <gpui::elements::div::Div as gpui::element::Element>::request_layout
             at crates/gpui/src/elements/div.rs:1061:46
  55: <gpui::element::DrawableElement<gpui::elements::div::Div>>::request_layout
             at crates/gpui/src/element.rs:293:44
  56: <core::option::Option<gpui::element::DrawableElement<gpui::elements::div::Div>> as gpui::element::ElementObject>::request_layout
             at crates/gpui/src/element.rs:407:9
  57: <gpui::element::AnyElement>::request_layout
             at crates/gpui/src/element.rs:450:9
  58: gpui::view::any_view::request_layout::<workspace::Workspace>
             at crates/gpui/src/view.rs:422:25
  59: <gpui::view::AnyView>::draw::{closure#0}::{closure#0}
             at crates/gpui/src/view.rs:258:57
  60: <gpui::window::element_cx::ElementContext>::with_absolute_element_offset::<(), <gpui::view::AnyView>::draw::{closure#0}::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:526:22
  61: <gpui::view::AnyView>::draw::{closure#0}
             at crates/gpui/src/view.rs:257:13
  62: <gpui::window::element_cx::ElementContext>::paint_view::<(), <gpui::view::AnyView>::draw::{closure#0}>::{closure#0}
             at crates/gpui/src/window/element_cx.rs:1156:30
  63: <gpui::text_system::line_layout::LineLayoutCache>::with_view::<(), <gpui::window::element_cx::ElementContext>::paint_view<(), <gpui::view::AnyView>::draw::{closure#0}>::{closure#0}>
             at crates/gpui/src/text_system/line_layout.rs:329:22
  64: <gpui::text_system::WindowTextSystem>::with_view::<(), <gpui::window::element_cx::ElementContext>::paint_view<(), <gpui::view::AnyView>::draw::{closure#0}>::{closure#0}>
             at crates/gpui/src/text_system.rs:295:9
  65: <gpui::window::element_cx::ElementContext>::paint_view::<(), <gpui::view::AnyView>::draw::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:1147:9
  66: <gpui::view::AnyView>::draw
             at crates/gpui/src/view.rs:256:9
  67: <gpui::window::WindowContext>::draw::{closure#0}::{closure#0}::{closure#0}
             at crates/gpui/src/window.rs:971:21
  68: <gpui::window::element_cx::ElementContext>::with_key_dispatch::<(), <gpui::window::WindowContext>::draw::{closure#0}::{closure#0}::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:1120:22
  69: <gpui::window::WindowContext>::draw::{closure#0}::{closure#0}
             at crates/gpui/src/window.rs:955:17
  70: <gpui::window::element_cx::ElementContext>::with_z_index::<(), <gpui::window::WindowContext>::draw::{closure#0}::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:492:22
  71: <gpui::window::WindowContext>::draw::{closure#0}
             at crates/gpui/src/window.rs:954:13
  72: <gpui::window::WindowContext>::with_element_context::<(), <gpui::window::WindowContext>::draw::{closure#0}>
             at crates/gpui/src/window/element_cx.rs:175:9
  73: <gpui::window::WindowContext>::draw
             at crates/gpui/src/window.rs:953:9
  74: <gpui::window::Window>::new::{closure#0}::{closure#1}::{closure#0}
             at crates/gpui/src/window.rs:366:33
  75: <gpui::app::AppContext as gpui::Context>::update_window::<(), <gpui::window::Window>::new::{closure#0}::{closure#1}::{closure#0}>::{closure#0}
             at crates/gpui/src/app.rs:1242:26
  76: <gpui::app::AppContext>::update::<core::result::Result<(), anyhow::Error>, <gpui::app::AppContext as gpui::Context>::update_window<(), <gpui::window::Window>::new::{closure#0}::{closure#1}::{closure#0}>::{closure#0}>
             at crates/gpui/src/app.rs:353:22
  77: <gpui::app::AppContext as gpui::Context>::update_window::<(), <gpui::window::Window>::new::{closure#0}::{closure#1}::{closure#0}>
             at crates/gpui/src/app.rs:1233:9
  78: <gpui::app::async_context::AsyncAppContext as gpui::Context>::update_window::<(), <gpui::window::Window>::new::{closure#0}::{closure#1}::{closure#0}>
             at crates/gpui/src/app/async_context.rs:70:9
  79: <gpui::window::AnyWindowHandle>::update::<gpui::app::async_context::AsyncAppContext, (), <gpui::window::Window>::new::{closure#0}::{closure#1}::{closure#0}>
             at crates/gpui/src/window.rs:2597:9
  80: <gpui::window::Window>::new::{closure#0}::{closure#1}
             at crates/gpui/src/window.rs:364:25
  81: util::measure::<(), <gpui::window::Window>::new::{closure#0}::{closure#1}>
             at crates/util/src/util.rs:175:9
  82: <gpui::window::Window>::new::{closure#0}
             at crates/gpui/src/window.rs:363:21
  83: <alloc::boxed::Box<dyn core::ops::function::FnMut<(), Output = ()>> as core::ops::function::FnMut<()>>::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2022:9
  84: gpui::platform::mac::window::step
             at crates/gpui/src/platform/mac/window.rs:1583:9
  85: <unknown>
  86: <unknown>
  87: <unknown>
  88: <unknown>
  89: <unknown>
  90: <unknown>
  91: <unknown>
  92: <unknown>
  93: <unknown>
  94: <unknown>
  95: <unknown>
  96: <unknown>
  97: <unknown>
  98: <unknown>
  99: <unknown>
 100: <() as objc::message::MessageArguments>::invoke::<()>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
 101: objc::message::platform::send_unverified::<objc::runtime::Object, (), ()>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27:9
 102: objc::message::send_message::<objc::runtime::Object, (), ()>
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178:5
      <*mut objc::runtime::Object as cocoa::appkit::NSApplication>::run
             at /Users/jaime/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.25.0/src/appkit.rs:603:9
 103: <gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run
             at crates/gpui/src/platform/mac/platform.rs:387:13
 104: <gpui::app::App>::run::<Zed::main::{closure#3}>
             at crates/gpui/src/app.rs:139:9
 105: Zed::main
             at crates/zed/src/main.rs:123:5
 106: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
 107: std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
 108: std::rt::lang_start::<()>::{closure#0}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
 109: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
 110: std::rt::lang_start::<()>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
 111: _main

**Comment by jaimeelso** [comment]
Bug is in crates/theme/src/styles/players.rs in fn color_for_participant(): The panic message indicates an attempt to calculate the remainder with a divisor of zero.

**Comment by jaimeelso** [comment]
[catppuccin.json](https://github.com/zed-industries/zed/files/14270611/catppuccin.json)

The theme that I'm using while Zed panics

**Comment by JosephTLyons** [comment]
This has landed in [v0.124.0](https://zed.dev/releases/preview/0.124.0).
