### ISSUE TITLE
gpui: text input is lost immediately after changing focus

### ISSUE THREAD

**Issue by synoet** [zed-industries/zed#7748]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Like many vim users, I love to spam `:w` quite regularly. I've noticed that due to the command menu having some default option + some input delay that I frequently end up executing some unwanted command when running `:w` very quickly.

Basically when executing `:` then `w` then `enter`, it seems like the w doesn't get captured and instead uses the default value.

*ps*: I've tried my best to make sure there is no duplicate but I apologize if there is.

### Environment

Zed: v0.121.7 (Zed)df
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64dff

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I've tried to record a video showing the issue with a key visualizer.
![CleanShot 2024-02-13 at 18 51 43](https://github.com/zed-industries/zed/assets/10552019/b391b5d1-e262-4730-9325-e936defa814a)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
Thanks for the detailed report, and congratulations on getting this to happen, it seems that you must type *very* quickly.

It should be the case that once `w` is input into the command palette we wait until the matches have been updated; so it seems most likely the `w` is not in fact getting to the input...

Looking into this a bit, I think there's a race-condition between focus changes and keyboard input handling:

1. You hit `:` which creates a command palette and focuses it. It does not yet render it, but marks the window as dirty to be rendered on the next frame.
2. You hit `w` which gets dropped on the ground.
3. 8-16ms later the frame gets rendered, and the command palette registers itself as the new input handler.
