### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by play113** [zed-industries/zed#7763]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

cargo run
error: failed to parse manifest at `/noRAID/tmp/zed/zed-0.121.7/Cargo.toml`

Caused by:
  expected a boolean or an integer for key `profile.dev.debug`

### Environment

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie

rustc 1.63.0
cargo 1.65.0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by kazatsuyu** [comment]
[profile.dev.debug](https://doc.rust-lang.org/cargo/reference/profiles.html#debug) is now string acceptable. I think you have to update toolchain

**Comment by maxdeviant** [comment]
> rustc 1.63.0

It looks like you're running an older version of Rust.

Zed tracks the latest stable version of Rust fairly closely, and at time of writing Zed requires a minimum Rust version of 1.75 (and perhaps even 1.76).
