### ISSUE TITLE
Setting Python Interpreter

### ISSUE THREAD

**Issue by Armoniad1234** [zed-industries/zed#7764]
### Check for existing issues

- [X] Completed

### Language

python

### Misc notes

How can I set the desired Python interpreter on Mac Osx, let's say to be Python 3.11, as long as the default interpreter is on terminal 2.7?

**Comment by JosephTLyons** [comment]
We currently don't have a UI view for this, but I'm hoping we can get one soon!

**Comment by FrankensteinPillow** [comment]
I'm also looking forward to this feature.
Zed looks promising as an editor)

**Comment by FeSens** [comment]
Me too

**Comment by deathblade287** [comment]
+1

**Comment by jonnyhoff** [comment]
Me too!
