### ISSUE TITLE
[Ruby]: overriding `!=` method breaks syntax highlighting

### ISSUE THREAD

**Issue by ivansvlv** [zed-industries/zed#7776]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm not sure this is a right place to report this bug since I guess it's a `tree-sitter` bug, but it's still concerns language support in Zed.

I believe this is a related issue: https://github.com/tree-sitter/tree-sitter-ruby/issues/174

Code (It's funny but it breaks GitHub syntax highlighting as well):
```Ruby
class BugReport
  def ==(other)
    puts "overridden '=='"
    other == "test"
  end

  def !=(other)
    puts "overridden '!='"
    other != "test"
  end
end

t = BugReport.new
puts t == 'test'
puts t != 'test'
```

Code works and returns:
```
overridden '=='
true
overridden '!='
false
```

You can see here that `end` keyword that closes `class` is not highlighted. Which makes the previous `end` keyword to be matched by both `class` and method `def` when clicking on them.

![CleanShot 2024-02-14 at 17 05 53](https://github.com/zed-industries/zed/assets/16175855/818c2343-1dca-4a77-afd0-d9efc95930af)

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by joeldrapper** [comment]
I opened a PR to fix this in `tree-sitter-ruby`. https://github.com/tree-sitter/tree-sitter-ruby/pull/261
