### ISSUE TITLE
Copy / Paste Folder with files into itself, creates empty folder

### ISSUE THREAD

**Issue by cwerner1** [zed-industries/zed#7778]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When copying a folder with a single File, and then pasting the folder into itself zed while create multiple folders in a loop:

```
mkdir testfolder
touch testfolder/testfile.xxx
```

copying the testfolder with CMD+C
Select the testfolfder and press CMD+V

Zed creates many empty subfolders - see screencap

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 12.7.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screencapture of the Problem
https://github.com/zed-industries/zed/assets/1199614/474349d2-0d33-478a-a923-7a34751a91af

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I wonder if this is the same issue @iamnbutler had here:

- https://github.com/zed-industries/zed/issues/7314

**Comment by mrnugget** [comment]
Yeah, they are both the same issue. I'm going to close this one as duplicate, since #7314 is a bit older.
