### ISSUE TITLE
Extensions list filtering

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#7785]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great to be able to filter down to

- themes
- languages

and 

- [X] installed
- [X] uninstalled

**Comment by 0x2CA** [comment]
can add sort

**Comment by unnamedd** [comment]
Just to share: I have started drafting something requested for this issue.

**Comment by JosephTLyons** [comment]
Oops, this wasn't supposed to be closed, as filtering on themes and languages still isn't supported.

**Comment by jansol** [comment]
Looking at the extensions repo it seems like it's possible for an extension to provide both themes and languages at the same time? So the filtering would need to account for that.

**Comment by JosephTLyons** [comment]
Closing in favor of:

- https://github.com/zed-industries/zed/issues/8848
