### ISSUE TITLE
Generate license file: unable to parse license expression for 'tree-sitter-hcl

### ISSUE THREAD

**Issue by palmamartin** [zed-industries/zed#7788]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When working on PR https://github.com/zed-industries/zed/pull/7775 we noticed that on the "[Generating license file](https://github.com/zed-industries/zed/actions/runs/7903898704/job/21573156560?pr=7775#step:6:17)"  the following error:
```
2024-02-14 16:04:18.311242 +00:00:00 [ERROR] unable to parse license expression for 'tree-sitter-hcl 0.0.1': Apache
```

I prepared a simple fix for it here: https://github.com/palmamartin/zed/commit/f7fcdb84a3a9e90f506c9e2a068dd06ca4acd444

If preferred I can open a PR.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by palmamartin** [comment]
Don't know if this is worth including due to the fact of the introduction of extensions, so I can imagine in the near future all these tree-sitter and language related stuff will eventually extracted to extensions.

**Comment by JosephTLyons** [comment]
Not quite sure what to do here: cc @mikayla-maki
