### ISSUE TITLE
Checkboxes to respond to label clicks

### ISSUE THREAD

**Issue by alexventuraio** [zed-industries/zed#7794]
### Check for existing issues

- [X] Completed

### Describe the feature

From a UX stand point, when you present a checkbox to the user, the user expect to click either on the label or the check and both should respond to the event to check/uncheck it.

Right now, at least the checkboxes in the initial screen do not behave like that.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="560" alt="Screenshot 2024-02-14 at 14 37 58" src="https://github.com/zed-industries/zed/assets/13169164/df77ada0-f1b4-4cb4-8d72-a6686861098d">

**Comment by Fleebee** [comment]
Hey @alexventuraio ,

 I made some attempts at getting these clickable and in the end, just replaced them with buttons. 

I've had a look through the structs and I think maybe a custom label would be better but I couldn't figure it out.
Only started using Zed yesterday. Hopefully somebody more seasoned can help! 

The welcome screen file is:
crates/welcome/src/welcome.rs

https://github.com/Fleebee/zed/tree/clickable-welcome-labels

**Comment by alexventuraio** [comment]
@Fleebee thanks for the heads up and looking at it!
