### ISSUE TITLE
Markdown: open preview stopped working.

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#7799]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With latest ZED preview release 0.123.1, the markdown: open preview stopped working.

### Environment

`0.123.1`

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Glad to see people using markdown preview, thank you for noticing that.
It will be fixed in https://github.com/zed-industries/zed/pull/7830 and has to be released as a current preview hotfix, but I would love to keep it in Nightly for a day or two to ensure I did not break other things.

**Comment by SomeoneToIgnore** [comment]
Preview 0.123.2 had been released and should contain the fix for this.
