### ISSUE TITLE
Open Markdown file in browser for preview

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#7800]
### Check for existing issues

- [X] Completed

### Describe the feature

Open Markdown file in browser for preview to investigate/check rendering.

**Comment by jansol** [comment]
You mean like #5064 ?

**Comment by krstp** [comment]
Yup. definitely https://github.com/zed-industries/zed/issues/4791 is the answer. I forgot I put this one here. So to sum up, git-like rendering in browser window. Thanks!

**Comment by SomeoneToIgnore** [comment]
Yes, I cannot see how this differs from https://github.com/zed-industries/zed/issues/4791 hence closing as a duplicate.

**Comment by JosephTLyons** [comment]
Closing in favor of #4791
