### ISSUE TITLE
Allow to combine Command Pallete and Go to File

### ISSUE THREAD

**Issue by lucsoft** [zed-industries/zed#7802]
### Check for existing issues

- [X] Completed

### Describe the feature

I like how i can in vscode use F1 to run commands or with a simple back button choose files. Would be nice if Zed could do the same

**Comment by JosephTLyons** [comment]
I'm going to close this issue out in favor of:

- https://github.com/zed-industries/zed/issues/15896

Typically, I don't close out older issues over newer ones, especially if the upvote count is higher, but the newer issue has some more details about this feature and has the same amount of upvotes.
