### ISSUE TITLE
Add Jupyter Notebook support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#7809]
### Check for existing issues

- [X] Completed

### Describe the feature

Title

**Comment by jansol** [comment]
Previously: #5273

**Comment by sa-** [comment]
Between this issue, [remote development](https://github.com/zed-industries/zed/issues/5347), & making the python experience wonderful (#7808), this is pretty much all you need to support AI/machine learning workflows.

I would like to add that VS Code created some incompatibilities when trying to implement their own version of the notebook frontend - results in some plotting libraries & widgets not working among other inconveniences. 

I'm not sure if this is possible, but maybe the jupyter installed in the venv could be used to render the notebook?
