### ISSUE TITLE
typescript partial no color or color error?

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#7810]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1105" alt="image" src="https://github.com/zed-industries/zed/assets/19868292/8fbe05f9-d80d-4b78-b637-fb368c34a438">

### Environment

Zed: v0.123.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by arrrrny** [comment]
bump
