### ISSUE TITLE
Broken editor/terminal rendering after project search

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#7813]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See screenshot. Recovered after searching for something else. Not reproducible, but had it once a few days ago already.

https://github.com/zed-industries/zed/assets/19362696/ff23b6c1-740e-4716-a6d8-bd23de71e7c4

### Environment

Zed: v0.123.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by N8th8n8el** [comment]
When I can reproduce it's always when the first search result is a huge minified js file (where everything is in one line).

**Comment by N8th8n8el** [comment]
Also only happens when the window is quite large (almost full 4k screen). Everything is fine on a smaller window size.
Another recording:
Uploading Screen Recording 2024-02-15 at 08.40.38_480.mov…
(sorry for the bad quality, GitHub only allows 10MB)

**Comment by JosephTLyons** [comment]
This is a super strange bug. If you find that there's a way to reproduce it, let us know, but I'm guessing this is some random state that isn't easy to trigger.

**Comment by N8th8n8el** [comment]
Had something similar just now, but not triggered by search:

https://github.com/zed-industries/zed/assets/19362696/19e4047b-9f0d-4e93-a359-374343d1f1e5

Lot's of output in the terminal and Zed taking up the whole 4k screen (not macOS full screen).

**Comment by N8th8n8el** [comment]
And again:

https://github.com/zed-industries/zed/assets/19362696/67333eec-54c8-4b87-b0e9-1d1d9deacc8e

**Comment by nathanael-ruf** [comment]
https://github.com/zed-industries/zed/assets/104262550/cc1b650a-4201-49bc-93fb-0e9f5969edb3

Another instance. Seems to happen when I open a file with a single long line (e.g. js bundle) AND if the windows is full screen (but not the macos full screen mode) on a 4k monitor.

**Comment by nathanael-ruf** [comment]
![Screenshot 2024-03-21 at 11 54 51](https://github.com/zed-industries/zed/assets/104262550/267e8835-ec24-4c0f-8c90-bca983d076e6)

Another instance that shows that not only the terminal starts acting weirdly. The first search result was a js bundle again with one long line. And again only happening when full screen on a 4k monitor. It goes away when I resize the window to roughly 80% of the full sreen.

**Comment by nathanael-ruf** [comment]
Another instance that is perhaps easier to reproduce:

https://github.com/zed-industries/zed/assets/104262550/c4a6924a-e15f-4ffb-8bf6-327842308fd1

`adsasdddasadsasdddasadsasdddasadsasdddasadsasdddasadsasdddasadsasdddasadsasdddasasdddddddddddddddadadasdasdads`

```
echo "asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
asadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsadsdasadsddsadassssasadsdasadsa
"
```

**Comment by nathanael-ruf** [comment]
@JosephTLyons I think we need to rename this as it seems to have nothing todo with search.

**Comment by JosephTLyons** [comment]
Yikes! Thanks for elevating this @nathanael-ruf - seems pretty bad.

**Comment by kag359six** [comment]
Is there any update on this? I installed Zed on MacOS 11.7.10 and immediately ran into this issue opening a TS file. Would love to give the editor a fair shot

**Comment by mrnugget** [comment]
Pretty sure this was fixed by https://github.com/zed-industries/zed/pull/11849. Closing, but happy to reopen if it's still there on latest Preview.

**Comment by kag359six** [comment]
@mrnugget I'm still observing this issue on my 2013 Macbook Pro running MacOS 11.7.10 (Intel chip):

[Here's a loom re-production](https://www.loom.com/share/c194591814584b1ca7319d7aafbe9827)

**Comment by mrnugget** [comment]
@kag359six even on the newest Preview release? There should be errors in `~/Library/Logs/Zed/Zed.log` — are there any?
