### ISSUE TITLE
Ruby: Code Completion not working 

### ISSUE THREAD

**Issue by odedharth** [zed-industries/zed#7819]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Even though code completion is enabled, it's not working for me on any file types that I tested (.rb, .html.erb).

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 13.4.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/624023/b42203a4-dbef-416b-b536-b79e5a0d3942

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Hey! Did you follow the instructions here to install `solargraph` manually? https://github.com/zed-industries/zed/blob/main/docs/src/languages/ruby.md#setup

**Comment by odedharth** [comment]
Hey @mrnugget,

I just installed Solargraph and I see there are some auto-completions now, but it's still not properly auto-completing:

1. Variable names.  For example in the video below, you can see it didn't complete "@products".
2. All functions. For example in the video below, you can see it's not completing the most common model functions such as "find" and "where. 

See here:

https://github.com/zed-industries/zed/assets/624023/03b80d4c-7061-4dc2-86d1-c2ca312475c9

**Comment by mrnugget** [comment]
> 1. Variable names.  For example in the video below, you can see it didn't complete "@products".

Yeah, that's a bug on our side, I think. I saw `solargraph` returning that completion but us throwing it away.



> 2\. All functions. For example in the video below, you can see it's not completing the most common model functions such as "find" and "where.

That matches what `solargraph` extension in VS Code does, though. So I think something like https://github.com/iftheshoefritz/solargraph-rails might be the solution here? Although I haven't tried that yet.

**Comment by mrnugget** [comment]
> 1. Got it, yes, I just noticed that as well, it looks like a bug.

Alright, I got a fix for this here: https://github.com/zed-industries/zed/pull/7824

> 2. I just installed solargraph-rails and followed the instructions adding it to .solargraph.yml, but it still doesn't work.

Same here. I also couldn't get it to work in VS Code. I do have some ideas for how we could make launching language-servers more reliable, but this seems like we first need to find out how to get solargraph running in Rails.

**Comment by mrnugget** [comment]
I'm going to close this because I think it's fixed.
