### ISSUE TITLE
Inlay Hints don't work with TypeScript

### ISSUE THREAD

**Issue by jackTabsCode** [zed-industries/zed#7821]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Inlay Hints are not working with the Typescript language.
(They are working with Rust!)

I've made sure they're enabled in the settings.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
If Rust has them and TS does not, it could mean two things: either TS langserver is broken for some reason, or it is not configured enough and needs more configuration.
In the latter case, I would appreciate someone adding those to the 
https://github.com/zed-industries/zed/blob/main/docs/src/languages/typescript.md docs section.

Looking at https://github.com/typescript-language-server/typescript-language-server?tab=readme-ov-file#inlay-hints-textdocumentinlayhint I wonder, if it could be solved by adding

```
"typescript-language-server": {
        "initialization_options": {
            "preferences": {
                "includeInlayVariableTypeHints": true,
                "includeInlayParameterNameHints": "all",
                "includeInlayParameterNameHintsWhenArgumentMatchesName": true,
                "includeInlayFunctionParameterTypeHints": true,
                "includeInlayVariableTypeHintsWhenTypeMatchesName": false
                // "includeInlayPropertyDeclarationTypeHints": true,
                // "includeInlayFunctionLikeReturnTypeHints": true,
                // "includeInlayEnumMemberValueHints": true,
            }
        }
    },
```

to Zed's config? 

To start debugging this, one needs to call the "debug: open language server logs" and see the RPC trace for the TS language server.
If hints are enabled, Zed has to query `textDocument/inlayHint` in those logs and the server has to reply with something.

**Comment by jackTabsCode** [comment]
> Looking at https://github.com/typescript-language-server/typescript-language-server?tab=readme-ov-file#inlay-hints-textdocumentinlayhint I wonder, if it could be solved by adding
> ...
> to Zed's config?
> 

This did in fact work. Thanks! Though, this probably should be set or configured by default by Zed.

**Comment by SomeoneToIgnore** [comment]
Yes, the more I think of it: we do disable inlays by default but LSP configs should be ready to display those.

So, there's no need for the docs PR, but a need for init options PR.

**Comment by texastoland** [comment]
I came to report this exact issue! Thanks for the fix 🔥
