### ISSUE TITLE
Cannot sign in to Copilot with self-signed certificates

### ISSUE THREAD

**Issue by contrast-jproberts** [zed-industries/zed#7828]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using Zed for work on a laptop provided by my employer. All traffic from the laptop is routed through a Secure Web Gateway for auditing. The gateway uses its own self-signed certificates to intercept SSL.

When I attempt to sign in to Copilot, the UI flashes with `zed_x_copilot.svg` and then disappears. There's no notification about an error, but Copilot continues to show as signed out. Looking at the logs, I see that the sign-in request failed because of the self-signed certificate.

This issue was first reported by @LaustinSpayce in https://github.com/zed-industries/zed/issues/4759#issuecomment-1913842737 . I'm creating a new issue because I believe this failure is in a different system than https://github.com/zed-industries/zed/issues/4759 .

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2024-02-15T07:58:22-05:00 [ERROR] crates/copilot/src/copilot.rs:115: Request signInInitiate failed with message: self-signed certificate in certificate chain
```

**Comment by contrast-jproberts** [comment]
This was a misconfiguration on my end. I'm able to sign in to Copilot after setting the [`NODE_EXTRA_CA_CERTS` environment variable](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) to a PEM bundle provided by the gateway product.

I expect this network setup is too rare to include in other docs, so I'm closing the issue. If there are any more changes the team would like to make to improve support, I'm happy to respond to any questions about the setup or the current UX.

**Comment by shinebayar-g** [comment]
It looks like I maybe running into same issue. However in my case Copilot was **working fine** until few days ago. Then it stopped working suddenly. When I click sign-in button of copilot, copilot icon flashes temporarily then nothing happens.

In VSCode I used this extension https://marketplace.visualstudio.com/items?itemName=linhmtran168.mac-ca-vscode to solve the issue. What should I do?
