### ISSUE TITLE
Cannot hide bottom dock with custom key binding if the dock is in focus

### ISSUE THREAD

**Issue by toksdotdev** [zed-industries/zed#7833]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If there's a custom key binding to `workspace::ToggleBottomDock` and the terminal dock is currently in focus, hiding it via the custom binding is not possible. To successfully hide it in that state, one has to lose focus from the terminal dock before pressing the custom key binding.

It'd be great if we could toggle the hidden property while the bottom dock is in focus and triggered using a custom key binding.

The closest issue I could see was #6773, which doesn't address this specific case.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Can you show the custom keybinding? Is the `context` for that in `Workspace`?

**Comment by toksdotdev** [comment]
Oops! I got the `context` mixed up in this case. I had this binding set to the `Editor`. Changing it to `Workspace` fixed the issue.

Thanks for the comment.

**Comment by srihariash999** [comment]
@toksdotdev  Can you give the keybinding please?
