### ISSUE TITLE
Allow syntax formatting without the need to save the file first.

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#7838]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like ZED allow formatting at with, for example through CMD+SHIFT+P invocation and `format <language>` call. Currently, in order to format I need to first save the file with the right extension, only then ZED will recognize the syntax and format the code upon save.

PS. I did try to select syntax, i.e. JSON, before saving and then try to call `editor: format` hoping it would deliver what I need, but this was/is not the case. File always needs to save first.

In short, there should be no need to have to save the file first. User should be able to work on unsaved newly created file/buffer, should be able to select syntax manually, then be able to manually invoke CMD+SHIFT+I to format the desired pasted syntax (it really helps with quick formatting of some of the `json` payloads).

### If applicable, add mockups / screenshots to help present your vision of the feature

ZED should allow syntax formatting without first requiring user to save the file, i.e.
Currently when I paste, f.ex. `json`, code ZED will not format it:
![Screenshot 2024-02-15 at 9 12 36 AM](https://github.com/zed-industries/zed/assets/4711498/24665895-1117-4c64-9eb9-8f404e72bafb)

I have to save the file first, i.e. `.json` only then ZED will allow me to format the file:
![Screenshot 2024-02-15 at 9 12 50 AM](https://github.com/zed-industries/zed/assets/4711498/54634611-7bcb-4c50-8b15-002444e7aefa)

**Comment by mrnugget** [comment]
Fixed here: https://github.com/zed-industries/zed/pull/12095
