### ISSUE TITLE
Add `.cljc`, `.edn`, and `.bb` file name extensions to the Clojure list

### ISSUE THREAD

**Issue by cap10morgan** [zed-industries/zed#7845]
### Check for existing issues

- [X] Completed

### Describe the feature

Follow up from #5292. In addition to `.clj` and `.cljs`, Clojure language mode should also be triggered when someone opens a file with `.cljc`, `.edn`, and `.bb` file name extensions.

`.cljc` is for files that mix code for different Clojure platforms (e.g. JVM Clojure and ClojureScript) using the `#?` reader macro.

`.edn` is for [extensible data notation](https://github.com/edn-format/edn) files that are essentially non-executable Clojure data structures w/ some extensibility features added on. Because they are the same data structure literals as Clojure itself and the extensibility features are implemented in terms of Clojure reader macro syntax, just activating Clojure language mode should suffice for these.

`.bb` is for Clojure code that is only intended to be executed by [Babashka](https://babashka.org) which is a Clojure scripting runtime. It's still just Clojure code, though, so Clojure language mode should work fine.

**Comment by JosephTLyons** [comment]
This is now included in [v0.125.0-pre](https://zed.dev/releases/preview/0.125.0).
