### ISSUE TITLE
`gpui` fails to build on msys2/mingw

### ISSUE THREAD

**Issue by ognevny** [zed-industries/zed#7847]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. install [msys2](https://msys2.org)
2. install all needed dependencies
```console
$ pacman -S pactoys
$ pacboy -S rust:p pkgconf:p clang:p
```
##### install libdispatch
currently it's not packaged in the repo
3. install an artifact from https://github.com/msys2/MINGW-packages/actions/runs/7917855073 and unpack
4. install libdispatch (`$ pacman -U *.pkg.*`)
5. run `RUST_BACKTRACE=1 cargo build --release`
6. `gpui` fails to build
```
  --- stderr
  thread 'main' panicked at crates\gpui\build.rs:151:10:
  called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::unwrap
               at C:\M\B\src\rustc-1.76.0-src\library\core\src\result.rs:1073:23
     4: build_script_build::compile_metal_shaders
               at .\build.rs:135:18
     5: build_script_build::main
               at .\build.rs:14:5
     6: core::ops::function::FnOnce::call_once
               at C:\M\B\src\rustc-1.76.0-src\library\core\src\ops\function.rs:250:5
```
looks like it's not inteded to be built on windows

### Environment

the command doesn't exist for windows, so...
OS: Windows 11 build 22621
Rust target triple: `x86_64-pc-windows-gnu`
cc:
```
clang version 17.0.6
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Not sure if it's actionable at this point: there's no support for Windows (yet) in Zed hence mingw failures are not something we're ready to consider too.

**Comment by ognevny** [comment]
update: now `live_kit_server` fails to build
```
error: failed to run custom build command for `live_kit_server v0.1.0 (C:\_\B\src\zed-0.126.2\crates\live_kit_server)`
  Caused by:
    process didn't exit successfully: `C:\_\B\src\zed-0.126.2\target\release\build\live_kit_server-2c10e7e40f3a298a\build-script-build` (exit code: 101)
    --- stderr
    thread 'main' panicked at crates\live_kit_server\build.rs:4:10:
    called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/livekit_room.proto: No such file or directory\r\n" }
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
