### ISSUE TITLE
Display Ruby method visibility in outline view

### ISSUE THREAD

**Issue by Otterpocket** [zed-industries/zed#7849]
### Check for existing issues

- [X] Completed

### Describe the feature

The ability to display the visibility of ruby methods in the Outline view.

Either by having the visibility displayed with the method name, or a section of the outline visually wrapped with the visibility.

Unlike other languages ruby does not define visibility along with the method name but instead as a section of the class, or less commonly as a method call with the method names as arguments.(Nobody really does the latter afaik)

I realise this functionality is quite language specific so feel free to dismiss this issue.

### If applicable, add mockups / screenshots to help present your vision of the feature

(This not a mockup, but more of a visual explanation of the issue)

<img width="728" alt="image" src="https://github.com/zed-industries/zed/assets/7274458/888dfd7b-6852-49bc-8696-debd6bc993a2">

**Comment by mrnugget** [comment]
Hey! I'm not sure yet whether the tree-sitter parser would allow it, but this _could_ (!) be relatively easy:

1. Run Zed from source: `cargo run`
2. Open Ruby file
3. Open tree-sitter debug view: `debug: open syntax tree view`
4. In another Zed: open https://github.com/zed-industries/zed/blob/main/crates/zed/src/languages/ruby/outline.scm and modify it to match what you're seeing in the tree-debug-view/outline

**Comment by Otterpocket** [comment]
> Hey! I'm not sure yet whether the tree-sitter parser would allow it, but this _could_ (!) be relatively easy:
> 
> 1. Run Zed from source: `cargo run`
> 2. Open Ruby file
> 3. Open tree-sitter debug view: `debug: open syntax tree view`
> 4. In another Zed: open https://github.com/zed-industries/zed/blob/main/crates/zed/src/languages/ruby/outline.scm and modify it to match what you're seeing in the tree-debug-view/outline

Thanks @mrnugget that's super helpful, I am familiar with the process as I'm working on the ruby/highlights scm. I didn't realise there were specific language files for the outline view! I'll have a tinker and see what I happens.

**Comment by JosephTLyons** [comment]
This has landed in [v0.124.0](https://zed.dev/releases/preview/0.124.0).
