### ISSUE TITLE
Import snippets from other editors

### ISSUE THREAD

**Issue by jwerre** [zed-industries/zed#7855]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great I could import snippets from other editors. This would really ease the barrier to entry.

**Comment by SomeoneToIgnore** [comment]
We do not interact with other editors, so nothing can be really imported that easily from there — it's worth a separate issue with the interaction design.

As for the snippets themselves, we have an issue for that: https://github.com/zed-industries/zed/issues/4611 so I'll close this as a duplicate.
