### ISSUE TITLE
Release 0.121.7 dissapearing on zed.dev Stable Releases Page

### ISSUE THREAD

**Issue by r0ckwav3** [zed-industries/zed#7877]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently on [the release page for 0.122.2](https://zed.dev/releases/stable/0.122.2), you can see link to the release notes for 0.121.7. However on [the release page for 0.121.6](https://zed.dev/releases/stable/0.121.6), the link doesn't appear. Other release pages either display 0.121.7 or not in a consistent way, but I'm not sure what the pattern is.

(watch the navigation bar on the left)

https://github.com/zed-industries/zed/assets/33732392/7dfa230b-6257-445f-8436-3d4435d19039

### Environment

Site issue, N/A

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @r0ckwav3, are you still seeing this behavior? I can't reproduce at the moment.

**Comment by r0ckwav3** [comment]
It's gone for me as well, not sure why. I'll mark this as closed for now unless someone can reproduce it.
