### ISSUE TITLE
create a new folder, file tree ui error

### ISSUE THREAD

**Issue by youngxhui** [zed-industries/zed#7884]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when i create a new folder, rename `
Neovim Beginner's Guide (Part Three): LSP Configuration (Part One)` ,the file tree ui has error, display folder and file name mix.

![image](https://github.com/zed-industries/zed/assets/16971804/850c6a9e-0d48-46d5-9651-28159891906e)

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/16971804/850c6a9e-0d48-46d5-9651-28159891906e)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jadijadi** [comment]
I tried different variations but was unable to reproduce. Can you please share your exact steps?

This is my idea but leads to correct tree ui:

- activate the right panel
- right click there and "new folder". name the folder "Neovim Beginner's Guide (Part Three): LSP Configuration (Part One)"
- right click the folder and "new file" and name it "Neovim Beginner's Guide (Part Three): LSP Configuration (Part One)"

In my case, the UI looks fine. can you please share your exact steps
