### ISSUE TITLE
All zed windows close when I "Cmd+Q" out of it

### ISSUE THREAD

**Issue by lakubuDavid** [zed-industries/zed#7893]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I have multiple windows open and I try to close one with Cmd+Q it closes all the windows which is quite annoying.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by fabianbeier** [comment]
That is standard Mac behavior. "CMD + Q" always closes all windows of the current application.

**Comment by SomeoneToIgnore** [comment]
Yes, not sure why we're supposed to change that.
It is also not clear what behavior @lakubuDavid wants to achieve, so I would assume, to close the window?
Then it's `cmd-shift-w` (close window) as "execute command" dialogue (`cmd-shift-p`) suggests:
![image](https://github.com/zed-industries/zed/assets/2690773/50e562ce-83a1-421b-a462-6ad73e322eba)
