### ISSUE TITLE
Make projects with the same name Distinguishable in "recent projects" selector

### ISSUE THREAD

**Issue by Otterpocket** [zed-industries/zed#7897]
### Check for existing issues

- [X] Completed

### Describe the feature

Different projects that have the same name can't be distinguished from one another in the "recent projects selector"

<img width="498" alt="image" src="https://github.com/zed-industries/zed/assets/7274458/18562d55-257d-4661-ba99-653e0239c2b8">

In this example I have 3 "zed" projects.

2 of them are
/Users/benhamment/Projects/zed-dracula-theme/zed/
/Users/benhamment/Projects/zed/

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="376" alt="image" src="https://github.com/zed-industries/zed/assets/7274458/6a52a594-7afb-42e0-876a-faafdfae9561">

Ugly I know, but just a simple solution

**Comment by SomeoneToIgnore** [comment]
This is being tacked in https://github.com/zed-industries/zed/pull/7528 and pretty close to completion at this point.

**Comment by Otterpocket** [comment]
> This is being tacked in #7528 and pretty close to completion at this point.

Awesome, great work!

Going to close this issue, look forward to trying it out.
