### ISSUE TITLE
Format issue

### ISSUE THREAD

**Issue by Muning69** [zed-industries/zed#7898]
The right mouse button always formats automatically, breaks lines automatically, and sometimes splits a line of code into multiple lines. This design experience is not good, and I hope it can be removed.

**Comment by Muning69** [comment]
When the computer enters sleep and is used again, there is always no code completion, and the software needs to be restarted.

**Comment by JosephTLyons** [comment]
Hey @Muning69, can you give a bit more detail about how the right mouse button relates to the formatting issue? I'm not quite sure I understand. Thanks.

**Comment by Muning69** [comment]
@JosephTLyons 
Right click the mouse button within any window of the software.

**Comment by Moshyfawn** [comment]
Either you do something completely different, or it's no longer reproducible.

https://github.com/zed-industries/zed/assets/16290753/629b1696-cceb-4ed2-8ea4-0a269797594e

**Comment by notpeter** [comment]
@Muning69 Are you still experiencing this issue?

**Comment by Moshyfawn** [comment]
I'm going to close this as it's no longer reproducible. Feel free to update this thread with more information if you still see the problem and we can reopen.
