### ISSUE TITLE
Change not qual sign displaying

### ISSUE THREAD

**Issue by AlexHladin** [zed-industries/zed#7900]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, the `not equal` sign is displayed as a single character (see image)
<img width="297" alt="image" src="https://github.com/zed-industries/zed/assets/7945837/f8381506-4a9b-4818-b2c0-65af4f1516b1">

Is it possible to add a configuration how to display the `not equal` sign? For me, the most preferable way to display it in a standard way is `!==`.
<img width="222" alt="image" src="https://github.com/zed-industries/zed/assets/7945837/86f4a7f5-0686-4290-bdcc-9d308867aea3">

**Comment by JosephTLyons** [comment]
Yep, this can be disabled via the setting that @mrnugget pointed out, so I'm going to close this issue out. :)

**Comment by AlexHladin** [comment]
@mrnugget @JosephTLyons yes, I added the next settings to the configuration, and everything is working!
```json
  "buffer_font_features": {
    "calt": false
  }```
  
  Thank you!
