### ISSUE TITLE
WHY IS YOUR SOFTWARE STILL FULL OF BUGS

### ISSUE THREAD

**Issue by confxsd** [zed-industries/zed#7901]
### Check for existing issues

- [X] Completed

I really like to use it but it is unbearable. I just don't understand why it's so hard to provide a stable software

Using latest macos

**Comment by mrnugget** [comment]
Hey! Sorry to hear you're frustrated. Anything specific that you can name?

**Comment by ALEZ-DEV** [comment]
oh... this issue is very specific

**Comment by SomeoneToIgnore** [comment]
Not sure what to discuss here, and issues is not a good place for such generic questions anyway.
Consider using https://github.com/zed-industries/zed/discussions next time.
