### ISSUE TITLE
error downloading release: request or operation took longer than the configured timeout time

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#7909]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
Language server error: Rust

error downloading release: request or operation took longer than the configured timeout time
```

how to config timeout?

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by crazybits** [comment]
same issue here

**Comment by resse92** [comment]
same problem when login

**Comment by guangzan** [comment]
Same problem when logging in or checking for updates.

**Comment by kzhui125** [comment]
@guangzan you can try http proxy.
I have tested http proxy is working, but socks5 proxy:

```
Error { kind: BadServerCertificate, context: None, source: Some(Error { description: "SSL peer certificate or SSH remote key was not OK", code: 60, extra: None }), source_type: Some("curl::error::Error"), local_addr: Some(127.0.0.1:63151), remote_addr: Some(127.0.0.1:1080) }
```

```rs
    #[test]
    fn it_works() {
        // let proxy = "http://127.0.0.1:1090".parse::<isahc::http::Uri>().unwrap();
        let proxy = "socks5://127.0.0.1:1080"
            .parse::<isahc::http::Uri>()
            .unwrap();
        let client = isahc::HttpClient::builder()
            .connect_timeout(Duration::from_secs(5))
            .low_speed_timeout(100, Duration::from_secs(5))
            .proxy(proxy)
            .build()
            .unwrap();
        let mut response = client.get("https://youtube.com").unwrap();
        println!("Status: {}", response.status());
        println!("Headers: {:#?}", response.headers());

        print!("{}", response.text().unwrap());
    }
```

**Comment by guangzan** [comment]
@kzhui125 Thanks for the reply, I tried the HTTP proxy but it still failed. 

```json
{
  "proxy": "http://127.0.0.1:1087"
}
```

```
2024-06-21T10:00:17+08:00 [ERROR] auto-update failed: error:request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2024-06-21T10:00:19+08:00 [INFO] set status on client 66259: Reauthenticating
2024-06-21T10:00:19+08:00 [INFO] set status on client 66259: Reconnecting
2024-06-21T10:00:21+08:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-06-21T10:00:22+08:00 [INFO] add connection to peer
2024-06-21T10:00:22+08:00 [INFO] add_connection;
2024-06-21T10:00:22+08:00 [INFO] waiting for server hello
2024-06-21T10:00:22+08:00 [INFO] got server hello
2024-06-21T10:00:22+08:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 446, id: 1632915 })
2024-06-21T10:00:22+08:00 [INFO] set status on client 66259: Connected { peer_id: PeerId { owner_id: 446, id: 1632915 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-06-21T10:00:27+08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-21T10:00:27+08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
```

**Comment by kzhui125** [comment]
@guangzan have you quit zed and restart?

**Comment by guangzan** [comment]
@kzhui125 After restarting zed, check that the update is working. Thinks.

**Comment by BytesZero** [comment]
Same problem, can't `sign in` Github

### Screenshot

![image](https://github.com/zed-industries/zed/assets/8764899/05a6c2fd-3554-47fb-a6b8-f8e7109ebf7f)



### Error

``` log
Error: request or operation took longer than theconfigured timeout time: request or operationtook longer than the configured timeout time:[28]Timeout was reached
```


###  Solved

Adding the following code and restarting solved my problem

``` json
{
  "proxy": "http://127.0.0.1:7890"
}
```

![image](https://github.com/zed-industries/zed/assets/8764899/a827b7ef-b186-40c3-8181-526c66b90244)

**Comment by metashops** [comment]
I can't log in either, the web page says Authentication Successful, but the zed editor can't log in.
![WeChat5c6e90cb2bf104a47dbdf935afbd20a2](https://github.com/zed-industries/zed/assets/58295733/35fe900e-732c-4c24-9414-a2a4d6c706d8)

**Comment by BytesZero** [comment]
> 我也登录不了，网页显示验证成功，但是zed编辑器登录不了。 ![WeChat5c6e90cb2bf104a47dbdf935afbd20a2](https://private-user-images.githubusercontent.com/58295733/346408467-35fe900e-732c-4c24-9414-a2a4d6c706d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDUyNDMsIm5iZiI6MTcyMDQwNDk0MywicGF0aCI6Ii81ODI5NTczMy8zNDY0MDg0NjctMzVmZTkwMGUtNzMyYy00YzI0LTk0MTQtYTJhNGQ2YzcwNmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NGY0ODRmMmEzYThhODJlNzhlYjcwODZjM2Q3NzU0YTM0MjAyMjg3OTc3NzgwYTZmNDk4MWY0ZmM2YmIwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmp93_e1SLxhna7Obnzc1HxvvXgnS-43USIw7VNNA2Q)

经常看的公众号，可以试试我上面的方法，一定要重启 Zed

**Comment by kzhui125** [comment]
yeah, both http proxy and socks5 works.
