### ISSUE TITLE
how to manually install extension

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#7912]
### Check for existing issues

- [X] Completed

### Describe the feature

for example: rust language extension.

VSCode support install from visx.

**Comment by maxdeviant** [comment]
You can install an extension manually by placing it in the `~/Library/Application\ Support/Zed/extensions/installed/` directory.

Right now the extension docs are here:

https://github.com/zed-industries/extensions/blob/c7a2d90c59fd17db6ae186405eb1ad6bf6c5432d/AUTHORING_EXTENSIONS.md#testing-your-extension-locally

**Comment by kzhui125** [comment]
@maxdeviant I failed to download language extension

```
Language server error: TOML

error downloading release

Caused by:
    0: request or operation took longer than the configured timeout time
    1: [28] Timeout was reached
```

how can I install toml language extension manually?

Download from `https://github.com/tamasfe/taplo/releases`, which file?

then copy the file to `/Users/someuser/Library/Application Support/Zed/languages/taplo-ls/`?

Thanks,

**Comment by maxdeviant** [comment]
We don't currently support loading language servers from extensions.

This is something we are working on that will be coming soon.

**Comment by kzhui125** [comment]
<img width="1137" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/fbdd96b2-f203-4693-834b-b4c484c08590">

Thanks, I am trying to manually download the file, since the timeout reached and proxy not working...

**Comment by JosephTLyons** [comment]
Let's close this issue out, since the answer was provided, but feel free to open an issue about the timeouts you ran into, if they pesist.
