### ISSUE TITLE
Inlay Hints do not work with Svelte

### ISSUE THREAD

**Issue by rpfaeffle** [zed-industries/zed#7913]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Inlay hints do not work with svelte language server (they do work with TypeScript).

If enabled, a `textDocument/inlayHint` request is send to the `svelte-language-server` but the response of it is `null`.

```json
// ...
// Send:
{"jsonrpc":"2.0","id":37,"method":"textDocument/inlayHint","params":{"textDocument":{"uri":"file:///<path-to-svelte-kit-demo-app>/src/routes/Counter.svelte"},"range":{"start":{"line":44,"character":0},"end":{"line":102,"character":0}}}}
// Receive:
{"jsonrpc":"2.0","id":37,"result":null}
// ...
```

### Environment

Zed: v0.123.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Looks like another langserver that has them disabled by default and needs some extra configuration.
Here's an example of how gopls and typescript-language-server are configured: https://github.com/zed-industries/zed/pull/7854 but I did not find anything for this language server.

**Comment by rpfaeffle** [comment]
Yeah, it seems like disabled by default. I did some research and it seems like the inlay hints (for VSCode) would rely on `javascript.inlayHints.*` and `typescript.inlayHints.*`.

**Comment by rpfaeffle** [comment]
Update: I did some experiments and finally found out how to activate them. I would create a PR and enable them by default.
