### ISSUE TITLE
Can't Hide Search in Terminal

### ISSUE THREAD

**Issue by CurbaiCode** [zed-industries/zed#7924]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After using <kbd>cmd</kbd> + <kbd>F</kbd> while focused on the Terminal Panel, I can't hide the search bar. Also, the toolbar is empty when viewed as a tab (see screenshot below) so there is no toggle button, and there is currently no command in the Command Palette to do so either.

![Screen Shot](https://github.com/zed-industries/zed/assets/47488521/64d29c49-5b18-4791-aeba-5fb1aaaed4f8)

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 12.6.6
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @CurbaiCode, this PR just landed support to add an `x` button to close search area out:

- https://github.com/zed-industries/zed/pull/7675

This is in [preview](https://zed.dev/releases/preview) and will be in stable next week. If you arent interested in being on the preview channel, hitting `esc` while the cursor is in the search editor should close it out, which you can use while waiting for that fix to hit stable.
