### ISSUE TITLE
Support frontmatter

### ISSUE THREAD

**Issue by jacobdalamb** [zed-industries/zed#7938]
### Check for existing issues

- [X] Completed

### Describe the feature

Frontmatter is a section at the beginning of a file that contains metadata about the file or the document. It's often used in static site generators such as Astro. The information is written in YAML, JSON, or TOML format and is enclosed between a set of triple-dashed lines (`---` or `+++`). The metadata within can include properties such as title, date, layout, categories, etc.

```
---
title: "My Blog Post"
date: 2021-01-31
---
```

In this example, "title" and "date" are metadata fields contained within the frontmatter. The information in the frontmatter can be used to generate webpages, sort posts, create navigations, among other uses.

Static site generators which use frontmatter in Markdown files:

- [jekyll](https://github.com/jekyll/jekyll)
- [hugo](https://github.com/gohugoio/hugo)
- [zola](https://github.com/getzola/zola)
- [pandoc](https://github.com/jgm/pandoc)
- [docusaurus](https://github.com/facebook/docusaurus)
- [markdoc](https://github.com/markdoc/markdoc)
- [middleman](https://github.com/middleman/middleman)
- [aettlr](https://github.com/Zettlr/Zettlr)

**Comment by alvgaona** [comment]
For Astro, it's been added in #6896

**Comment by jacobdalamb** [comment]
Yeah I'm talking about markdown support for it

**Comment by andreacfromtheapp** [comment]
+1 with a note: please support both YAML (---) and TOML (+++) frontmatter

**Comment by notpeter** [comment]
Thanks for the heads up @andreacfromtheapp I've updated PR #21503 to correctly support this.
