### ISSUE TITLE
Hover Preview for TailwindCSS is not working

### ISSUE THREAD

**Issue by johnalbert-dot-py** [zed-industries/zed#7947]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Only the Hover Preview for TailwindCSS classes is not working. 

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 13.6.4
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/67201700/0a483f1d-81fa-401d-b8ae-7c07860eea5f

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by johnalbert-dot-py** [comment]
is there any ways to fix this?

**Comment by gawlk** [comment]
It's super important for Tailwind users, I hope it'll be fixed soon.

**Comment by dotRarufu** [comment]
same issue here

[Screencast from 2024-03-25 17-56-27.webm](https://github.com/zed-industries/zed/assets/81721522/7b48cd19-2044-4d29-a9d7-4d7d41f0458c)
in my case, "left-0" does not work, but  "left-[0]" work

i've tried creating a new project to replicate my case, but failed to.
ive also tried:
- restart my computer
- reinstall node modules  

i hope this get fixed soon

**Comment by SomeoneToIgnore** [comment]
This is now available in [v0.130.0-pre](https://zed.dev/releases/preview/0.130.0).

![Screenshot 2024-04-04 at 12 17 49](https://github.com/zed-industries/zed/assets/2690773/e0db2078-6330-4f6f-8f32-59e7fc375b8b)
