### ISSUE TITLE
xcrun: error: unable to find utility "metal", not a developer tool or in PATH

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#7948]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When running `cargo run` I got this error:
```
  --- stderr
  Failed to run rustfmt: cannot find binary path (non-fatal, continuing)
  metal shader compilation failed:
  xcrun: error: unable to find utility "metal", not a developer tool or in PATH

warning: build failed, waiting for other jobs to finish...
```

Command line tools are already installed here `/Library/Developer/CommandLineTools`

### Environment

Zed: v0.123.2 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by sexnine** [comment]
I had the same issue, but having XCode installed and running `xcode-select --switch /Applications/Xcode.app/Contents/Developer` fixed the issue for me.

Found this solution here: https://github.com/gfx-rs/gfx/issues/2309#issuecomment-413695219

**Comment by BuonOmo** [comment]
I think it is also worth mentionning the [Building ZED on MacOS documentation](https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_macos.md) here, at least that's what was missing for me.

**Comment by LukeLIN-web** [comment]
I failed
xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/Developer'

I have installed command line tools. xcode-select --install xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates
