### ISSUE TITLE
The opening of zed is slow!

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#7949]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The opening of zed is too slow, at least for me, i dont think is my computer because is great.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Most probably https://github.com/zed-industries/zed/pull/7775 will fix it, but it's not released yet, so we will see in the next preview (0.124) only.

**Comment by Iovans** [comment]
> Most probably https://github.com/zed-industries/zed/pull/7775 will fix it, but it's not released yet, so we will see in the next preview (0.124) only.

Okay thank you for the  info
