### ISSUE TITLE
Ability to tweak rust-analyzer integration?

### ISSUE THREAD

**Issue by nixpulvis** [zed-industries/zed#7950]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm just getting started with Zed, hacking on a little Rust. It's cool how it integrates with the LSP and gives info on hover for all my idents. However, I often make use of feature flags.

Is there a way to pass feature flags to Zed's Rust integration?

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="614" alt="Screenshot 2024-02-17 at 9 26 56 AM" src="https://github.com/zed-industries/zed/assets/715947/855c70b1-58da-4abb-91e0-961aa106eb4e">

**Comment by SomeoneToIgnore** [comment]
I'm not sure how feature flags work in r-a, but if it accepts those via language server configuration, you can pass them via the `lsp` config section in your settings.json.

Here's an example of my config and it works for me:

```
"lsp": {
    "rust-analyzer": {
        "initialization_options": {
            "inlayHints": {
                "maxLength": null,
                "lifetimeElisionHints": {
                    "useParameterNames": true,
                    "enable": "skip_trivial"
                },
                "closureReturnTypeHints": {
                    "enable": "always"
                }
            },
            "procMacro": {
                "enable": true,
                "attributes": {
                    "enable": true
                }
            },
            "completion": {
                "snippets": {
                    "custom": {
                        "Arc::new": {
                            "postfix": "arc",
                            "body": ["Arc::new(${receiver})"],
                            "requires": "std::sync::Arc",
                            "scope": "expr"
                        },
                        "Some": {
                            "postfix": "some",
                            "body": ["Some(${receiver})"],
                            "scope": "expr"
                        },
                        "Ok": {
                            "postfix": "ok",
                            "body": ["Ok(${receiver})"],
                            "scope": "expr"
                        },
                        "Rc::new": {
                            "postfix": "rc",
                            "body": ["Rc::new(${receiver})"],
                            "requires": "std::rc::Rc",
                            "scope": "expr"
                        },
                        "Box::pin": {
                            "postfix": "boxpin",
                            "body": ["Box::pin(${receiver})"],
                            "requires": "std::boxed::Box",
                            "scope": "expr"
                        },
                        "vec!": {
                            "postfix": "vec",
                            "body": ["vec![${receiver}]"],
                            "description": "vec![]",
                            "scope": "expr"
                        }
                    }
                }
            },
            "diagnostics": {
                "experimental": {
                    "enable": true
                }
            }
            // "checkOnSave": false,
        }
    }
}
```

so please try adding features there and, if it works, I would really appreciate you adding a section into https://github.com/zed-industries/zed/blob/main/docs/src/languages/rust.md

**Comment by nixpulvis** [comment]
Apparently I need more storage space on my Mac before I can install Xcode to build Zed. I'm trying to trace how `"initialization_options"` passes things through to the underlying LSP implementation.

It seems like this _should_ work, but it doesn't and I have no errors/warnings, or messages to help.

```json
"lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "features": [
            "history"
          ]
        }
    }
}
```

Sorry I can't be more helpful at this moment.

**Comment by Razboy20** [comment]
> Apparently I need more storage space on my Mac before I can install Xcode to build Zed. I'm trying to trace how `"initialization_options"` passes things through to the underlying LSP implementation.
> 
> It seems like this _should_ work, but it doesn't and I have no errors/warnings, or messages to help.
> 
> ```json
> "lsp": {
>     "rust-analyzer": {
>       "initialization_options": {
>         "cargo": {
>           "features": [
>             "history"
>           ]
>         }
>     }
> }
> ```
> 
> Sorry I can't be more helpful at this moment.

Not sure if something has changed between 5 days ago and now, however this configuration *does* work for me. (on preview 0.124.1)

**Comment by SomeoneToIgnore** [comment]
Stable r-a gets released every Monday, so might be that we were seeing new docs, but the binary was old.
Glad that it works for you, and welcome to submit a docs PR if you feel like it 🙂

**Comment by nixpulvis** [comment]
I downloaded the latest build from https://zed.dev (0.123.3) and now the same configuration seems to break the rust-analyzer altogether. Whereas before, it seemed to just do nothing.

I'll gladly send a doc PR once I understand what's going on here.

**Comment by RemiBardon** [comment]
> I downloaded the latest build from https://zed.dev (0.123.3) and now the same configuration seems to break the rust-analyzer altogether. Whereas before, it seemed to just do nothing.
> 
> I'll gladly send a doc PR once I understand what's going on here.

The provided snippet breaks my rust-analyzer too, but by setting `"features"` to `"all"` (not in an array), I managed to make it work again AND it now analyzes code in `#[cfg(feature = "whatever")]` 🥳

```diff
"lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
-         "features": [
-           "history"
-         ]
+         "features": "all"
        }
    }
}
```

**Comment by xpe** [comment]
I can confirm the following `settings.json` example works at present (Zed Preview 0.183.6) to change the feature flags of the current project:

```json
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "features": ["feature1", "feature2]
        }
      }
    }
  }
}
```
