### ISSUE TITLE
Keymap active item custom

### ISSUE THREAD

**Issue by Natchii59** [zed-industries/zed#7952]
### Check for existing issues

- [X] Completed

### Describe the feature

We cannot modify the keymap for active tabs.
It would be nice if it was customizable.

<img width="492" alt="image" src="https://github.com/zed-industries/zed/assets/96394660/03e5ff12-e4b0-4433-8bb2-08af6666835d">

**Comment by JosephTLyons** [comment]
Hey @Natchii59, could you explain a bit more what you are wanting to do? I'm a bit confused here. Thanks.

**Comment by Natchii59** [comment]
Hey @JosephTLyons, It would be nice to be able to customize these keys.
For example, I can't change the shortcut for `Active item 1` to `cmd+1`

**Comment by benbenbang** [comment]
+1
I would like to remap them to be the same as those in Sublime Text

**Comment by notpeter** [comment]
I believe this is now possible, these are just defined as part of the regular keymap and you create your own custom binds to these actions or rebind these keys to other actions as desired.

https://github.com/zed-industries/zed/blob/75377bbe0f1b6d4b8f313adcd5dd5005601d0756/assets/keymaps/default-macos.json#L384-L393

Thanks.
