### ISSUE TITLE
Use time formatting settings specified in system settings rather than going by default language

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#7956]
### Check for existing issues

- [X] Completed

### Describe the feature

Follow-up on discussion in #7945
On Linux this basically means looking at `LC_TIME` instead of `LANG`, not sure what the correct way is on macOS.

**Comment by evrsen** [comment]
All in all I think being able to access the native system language & time locale would be a nice feature to have in GPUI. I'm not sure how this would be done, but I would love to follow up on this issue and learn from it. 😁
