### ISSUE TITLE
Windows & Linux support

### ISSUE THREAD

**Issue by alejandro-esquivel** [zed-industries/zed#7964]
### Check for existing issues

- [X] Completed

### Describe the feature

Why is this only available for Mac when there are more people who use Windows and Linux distros than Mac?

**Comment by tulpenkiste** [comment]
Existing issues: #5395, #5394
Relevant issue: #7015 (Linux)

**Comment by SomeoneToIgnore** [comment]
Also, a metaissue: https://github.com/zed-industries/zed/issues/5391
