### ISSUE TITLE
Better bash IDE

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#7979]
### Check for existing issues

- [X] Completed

### Describe the feature

lsp-server: https://github.com/bash-lsp/bash-language-server
format: https://github.com/mvdan/sh

**Comment by Bloeckchengrafik** [comment]
Pretty sure languages should be added via extensions like [here](https://github.com/zed-extensions/nu) now.

**Comment by jansol** [comment]
Correct, but for the time being having tracking issues for those extensions here is still fine AFAIK.

Previous discussion: #5457 (also mentions that same lsp)

**Comment by JosephTLyons** [comment]
@Bloeckchengrafik, @jansol - I think this is correct in most cases, but I have a feeling bash might be one of the languages we ship with Zed. That hasn't been confirmed with anyone on the team, so I could be entirely wrong, but it feels reasonable to ship with bash support.

**Comment by d1y** [comment]
@maxdeviant I saw that you turned the built-in language support into an extension. Are there any plans to support bash-lsp 🤔
