### ISSUE TITLE
Zed DMG does not open on macOS 14.4 beta 2

### ISSUE THREAD

**Issue by danpalmer** [zed-industries/zed#7984]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure if this is specific to my machine, specific to macOS 14.4B2, or a general issue, but the DMG for Zed downloadable from the website right now does not open. Other DMGs appear to work fine.

The DMG fails to open because of a `EXC_BAD_ACCESS` in DiskImageMounter. This suggests to me that it's a macOS bug, but the end result is that Zed is not installable, while other applications so far seem unaffected.

### Environment

N/A, cannot install Zed.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

N/A

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

N/A

**Comment by danpalmer** [comment]
I wonder if #4199 is related. I could imagine that APFS DMGs are a bit of an edge case, whereas HFS+ DMGs must be a very well exercised path. The other DMGs I've found to test this with have all been HFS+.

**Comment by mrnugget** [comment]
Is this related? https://github.com/zed-industries/zed/issues/7132#issuecomment-1923509197

**Comment by danpalmer** [comment]
Yep, that looks like the same thing. Sorry I had a search through but perhaps only through open issues and that one is closed.

While it sounds like an Apple bug, I'd suggest Zed just package with a different compression format, at least for now. It's not a great experience and comes across as a Zed bug. I'm also not confident that it's the sort of thing that Apple will fix in time for a public release.

**Comment by danpalmer** [comment]
Hey, just thought I'd ping on this. I went to use Zed again today and realised I'm still unable to actually get a copy of it!

**Comment by mrnugget** [comment]
Hey @danpalmer! In that other issue (#7132) there's a comment that says that it was fixed in a newer version of macOS: https://github.com/zed-industries/zed/issues/7132#issuecomment-1935779099

Did you try that build yet?

**Comment by learnsomuch** [comment]
I also have same problem in Mac M1 with 14.4 (23E214) version. Can't open Zed.app
I also removed files inside Library/Logs/Zed and no luck. Then, I removed Zed.app under Applications folder and tried to install via brew (brew install zed) and still there is no logs created and Zed.app was not being opened.

I also tried to execute command RUST_BACKTRACE=full zed and see if there is any improvement. But, unfortunately, nothing helped.

**Comment by danpalmer** [comment]
@mrnugget thanks for the reply...

> Hey @danpalmer! In that other issue (#7132) there's a comment that says that it was fixed in a newer version of macOS: [#7132 (comment)](https://github.com/zed-industries/zed/issues/7132#issuecomment-1935779099)
> 
> Did you try that build yet?

I haven't had a chance to update my Mac yet so haven't tried this, but I'm happy to close the issue and re-open it if it doesn't work, as it sounds plausible from others that it is indeed fixed.

@learnsomuch 

> I also have same problem in Mac M1 with 14.4 (23E214) version. Can't open Zed.app I also removed files inside Library/Logs/Zed and no luck. Then, I removed Zed.app under Applications folder and tried to install via brew (brew install zed) and still there is no logs created and Zed.app was not being opened.

This is a different problem. This issue was specifically about the DMG distribution, not the app itself.
 
> I also tried to execute command RUST_BACKTRACE=full zed and see if there is any improvement. But, unfortunately, nothing helped.

For future reference, this is only for debugging, it won't actually help with running the application if it's crashing.

> Finally, I tried to execute as (Looks like some files needs to be created and permissions were missing. So, added sudo before executing zed) sudo /Applications/Zed.app/Contents/MacOS/zed ; exit;
> This solved the problem and I could be able to open Zed.app :)

Glad you can use Zed! This shouldn't be a permission issue though, Zed shouldn't need to run as sudo. It's possible you have antivirus on your machine that is conflicting here, or something like [Santa](https://github.com/google/santa) preventing untrusted binaries from launching. I'd suggest looking in Console.app for crash reports in the future as these are often enlightening.

For any more help here @learnsomuch I suggest opening a new bug.

- - -

Closing this issue as it's most likely resolved.
