### ISSUE TITLE
Automatic whitespace trimming

### ISSUE THREAD

**Issue by Morgandri1** [zed-industries/zed#7988]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, there is no way to disable whitespace removal on save. afaik, this is a prettier feature. If i create a newline with autosave on, the line starts at the leftmost position, regardless of outer indent.

**Comment by JosephTLyons** [comment]
Also, just to point it out, we have a few settings that strip whitespace from files on save that are turned on by default:

`remove_trailing_whitespace_on_save` and `ensure_final_newline_on_save`.
