### ISSUE TITLE
Large buffer font size rendering editor unusable.

### ISSUE THREAD

**Issue by tsymalla** [zed-industries/zed#8003]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

By accident, I changed the buffer font size to 1620 in the settings.json document. This caused all text in the buffers to disappear, even leaving the settings.json uneditable. While this might be intended (since 1620 is an eligible font size), it might be good to at least clamp that value to some upper bound or warn the user. Editing the settings.json file is obviously also not possible anymore, leading the app to be unusable.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @tsymalla - we now clamp the font sizes so that this is no longer possible:

- https://github.com/zed-industries/zed/commit/2baa704af7e6150e99da63d19a9fa42223e8acce
