### ISSUE TITLE
Zed stop working when opening a large file (4GB)

### ISSUE THREAD

**Issue by tadeumaia** [zed-industries/zed#8005]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Here are the steps I took after installing zed.

1. Open zed
2. Open a large json file, this one was around 3.84 GB around 1M elements
3. Zed takes a long time to open the file
4. Mac says zed is unresponsive 
5. Zed never finished up opening the file

VS Code for comparison opens the file fine after warning about no syntax highlight and takes around 8GB memory

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2024-02-19 at 04 44 19@2x](https://github.com/zed-industries/zed/assets/1054273/ddce36e7-40e8-4f04-b83a-e87711db586c)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by 0x2CA** [comment]
#4701

**Comment by SomeoneToIgnore** [comment]
Oh, that one I've failed to find, thank you.
