### ISSUE TITLE
vim-mode insert `j` dislocation

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8006]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

What's going on?
![WIP](https://github.com/zed-industries/zed/assets/45585937/9ab1b561-8c71-40d2-ba39-6d6b9dd2902b)

My configuration
```jsonc
  {
    // insert mode
    "context": "Editor && vim_mode == insert",
    "bindings": {
      "j j": "vim::NormalBefore",
      "alt-shift-backspace": "editor::DeleteToNextWordEnd"
    }
  }
```

### Environment

Zed: v0.123.2 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Ah, I see it. Easy to reproduce:

1. Add the binding from above
2. Try typing `project` in insert mode

**Comment by d1y** [comment]
> Ah, I see it. Easy to reproduce:
> 
> 1. Add the binding from above
> 2. Try typing `project` in insert mode

What? I don’t understand what you mean. Look at my gif, and there’s still something wrong.

![fix.gif](https://s2.loli.net/2024/02/19/i7xZjD3vRpPnyIL.gif)

**Comment by mrnugget** [comment]
Yes, that's what I'm saying. I can now reproduce the bug you're running into.

**Comment by d1y** [comment]
Sometimes, I feel that jj inputs too slowly, as if it takes a second?

**Comment by mrnugget** [comment]
Yes, that's how it works: there's a delay to check whether you want to hit `jj` to escape insert mode or whether you want to type `jj`. Vim has the same thing. In Vim the duration is configurable though, we don't have that yet.

But coming back to this issue here, I'm pretty sure this is a recent regression. Did you have it working before?

**Comment by d1y** [comment]
I kind of forgot, after all, I couldn’t input j before.

**Comment by Nobody9512** [comment]
This is the lag I'm having now, when I press `j` the deer hits the screen after a while.

Zed version: Zed 0.147.2
OS: Linux (Ubuntu 22.04)
Arch: x86_64
