### ISSUE TITLE
vim mode: `2y$` should yank two lines rather than one line

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/zed#8007]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In vim normal mode, if we type something like `2y$` or `3y$`, it should yank from current cursor to next 1 or 2 lines.

Currently it only yank one line.

I want to remap from `Y` to `y$`(this is how neovim does: https://github.com/neovim/neovim/pull/13268), so `2Y` will yank from current cursor to next line end, but I think I can't do this because `2y$` doesn't work as expected.

### Environment

Zed: v0.123.2 (Zed Preview)
OS: macOS 13.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
Thanks for this report!

I think the problem is that we don't pass the `count` to end_of_line. If you'd like to send a pull request, please do (or feel free to book time https://calendly.com/conradirwin/pairing).

**Comment by WindSoilder** [comment]
Sure!  I'll take a look at it in 2 weeks

**Comment by JosephTLyons** [comment]
This is available in Zed [v0.126.0-pre](https://zed.dev/releases/preview/0.126.0).
