### ISSUE TITLE
vim: when splitting window, buffers shouldn't be split, each split window can access any opened buffer.

### ISSUE THREAD

**Issue by SamiAlsubhi** [zed-industries/zed#8013]
### Check for existing issues

- [X] Completed

### Describe the feature

on vim, when screen is split, each split can access can access any opened buffer. like the following screen shot:

<img width="1171" alt="Screenshot 2024-02-19 at 4 42 10 PM" src="https://github.com/zed-industries/zed/assets/2551232/a3e4896c-0756-4748-bb13-41460f6ba5d5">

buffers are not separated by each screen split.

my suggestion is to have this as an option that can be activated to serve vim users.
I really like this editor and I hope it gets all of these necessary features for vim users.

**Comment by 0x2CA** [comment]
I agree,In fact, the label is just a buffer display, and is not strongly associated with the window, more than one window is just a different layout, you can freely switch the label to switch the current window to display the buffer, you can also directly open the file to replace the current window of the buffer
zed
![image](https://github.com/zed-industries/zed/assets/19868292/3e1817b4-6cb4-438b-8c0e-c6ca126c6fac)
vim
![image](https://github.com/zed-industries/zed/assets/19868292/46cf76eb-45be-4f72-b81b-7f1be34d1ace)
nvim
![image](https://github.com/zed-industries/zed/assets/19868292/69e68def-deb7-4603-98ca-81458771fc8a)

**Comment by 0x2CA** [comment]
vim roadmap
![image](https://github.com/zed-industries/zed/assets/19868292/c3ace25f-aaa9-45bf-9487-5630c89376dc)

**Comment by mrnugget** [comment]
I agree that this doesn't work that well with Vim mode, but I think for now it is WONTFIX since it requires too much changing of non-Vim mode too.

**Comment by cserb** [comment]
> I agree that this doesn't work that well with Vim mode, but I think for now it is WONTFIX since it requires too much changing of non-Vim mode too.

That's unfortunate. I dislike very much the visual clutter that the non-vim tab buffer way creates (in addition to the inferior workflow)

I think though there is a good compromise. If we could turn off displaying the tabs bar, we could have one step towards that. Then switching "buffers" or files would be via `crtl-tab` or `cmd+p`
