### ISSUE TITLE
Allow the use of custom proxy for copilot

### ISSUE THREAD

**Issue by Belluxx** [zed-industries/zed#8034]
### Check for existing issues

- [X] Completed

### Describe the feature

Allow users to specify a custom proxy to use for the copilot API.
It should also be possible to specify a localhost proxy so that it would enable the usage of OpenAI-Compatible APIs like _Ollama_, _llamacpp-python_ etc... 
This would (at least partially) solve #4424 without any GUI work and minimal backend changes.

### If applicable, add mockups / screenshots to help present your vision of the feature

In VSCode it's already possible by using this configuration snippet:
```json
"github.copilot.advanced": {
    "debug.testOverrideProxyUrl": "http://localhost:5001",
    "debug.overrideProxyUrl": "http://localhost:5001"
}
```

**Comment by mrnugget** [comment]
Closing this as duplicate of this: https://github.com/zed-industries/zed/issues/6701

**Comment by flatsiedatsie** [comment]
@mrnugget Is local LLM support "not planned"?

> [mrnugget](https://github.com/mrnugget) closed this as [not planned](https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) [yesterday](https://github.com/zed-industries/zed/issues/8034#event-11858943591)

**Comment by mrnugget** [comment]
See my comment right above: 

> Closing this as duplicate of this: https://github.com/zed-industries/zed/issues/6701
