### ISSUE TITLE
Toggle Line Numbers

### ISSUE THREAD

**Issue by akmaksumov** [zed-industries/zed#8041]
### Check for existing issues

- [X] Completed

### Describe the feature

To be able to toggle line numbers inside the editor

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/7665 will allow to use settings to show/hide line numbers in the gutter.

**Comment by SomeoneToIgnore** [comment]
And now it's merged and comes with Zed 0.125.0
