### ISSUE TITLE
Markdown Preview overflows

### ISSUE THREAD

**Issue by nilskch** [zed-industries/zed#8047]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the Markdown Preview, long content overflows and does not resize. In the video, I added the (from my side) preferred behaviour. This example is from a VSCode extension.

I am unsure if this is wanted behaviour from your side, but I wanted to flag this here.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[![](https://github.com/zed-industries/zed/assets/52418412/d2e6677f-8a41-42eb-bd3d-2ad1174e4c0e)](https://github.com/zed-industries/zed/assets/52418412/d2e6677f-8a41-42eb-bd3d-2ad1174e4c0e)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
It looks like a PR for this just landed:

- https://github.com/zed-industries/zed/pull/8052

Closing this out for now, feel free to open a new issue if the behavior persists.

**Comment by nilskch** [comment]
nice community, thanks!
