### ISSUE TITLE
Plus, split and assistant icons pulse

### ISSUE THREAD

**Issue by exaby73** [zed-industries/zed#8050]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The icons along the tab bar and file name on top of the pane pulse.

### Environment

Zed: v0.124.0 (Zed Dev)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

Additional info:
Macbook Pro M1 Max
Zed built from master (3ef8a9910d0da47f53be239bd1e5473a2f6410ce)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/50555895/b6cb0455-49c1-4fa1-8b94-1c1395179393

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by oliver-kriska** [comment]
hi, still existing issue even in new Preview Release where you wrote that it's fixed 
- Zed Preview 0.125.0
- Macbook Pro M1 Pro
- Sonoma 14.3.1

https://github.com/zed-industries/zed/assets/39122854/f399303d-dcbc-44b9-91ce-561116b349f6

btw: also you wrote in release `zed: view release notes locally` but how you can see on video it's `auto update: view release notes locally`
