### ISSUE TITLE
Crash when deleting big chunk of JSON file

### ISSUE THREAD

**Issue by FrittenKeeZ** [zed-industries/zed#8057]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have a JSON file with 34299 lines / 1,4 MB and trying to remove a big chunk of it results in a fatal crash.
If I remove small chunks of the file everything is fine.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 13.5.2
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Example JSON I'm editing
[311731469-status-0.json](https://github.com/zed-industries/zed/files/14344142/311731469-status-0.json)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[crash.log](https://github.com/zed-industries/zed/files/14344155/crash.log)

**Comment by ConradIrwin** [comment]
This was fixed by a refactoring to breadcrumbs a few weeks ago
