### ISSUE TITLE
Feature Request: Add Cursors to Line Ends Functionality

### ISSUE THREAD

**Issue by bnsouza** [zed-industries/zed#8065]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to request the addition of a functionality similar to the "Add Cursors to Line Ends" feature found in Visual Studio Code, specifically the **`editor.action.insertCursorAtEndOfEachLineSelected`** command. This feature allows users to add multiple cursors at the end of each line within a selected block of text. It enables efficient simultaneous editing of multiple lines, greatly enhancing the editing experience for tasks that involve repetitive changes at the end of lines, such as appending semicolons, commas, or making other consistent modifications.

The expected behavior is that when a user selects a block of text and activates this command, a cursor is placed at the end of each line within the selection. The user can then type or perform actions that are applied to all selected lines simultaneously.

This feature would significantly boost productivity and align with the expectations of developers who are accustomed to such advanced editing capabilities in their code editors.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Captura de Tela 2024-02-20 às 10 55 58](https://github.com/zed-industries/zed/assets/8568452/985248d9-5dae-42e4-bb89-20953b50cb8f)

**Comment by JosephTLyons** [comment]
Hey @bnsouza, try the `editor: split selection into lines` command and see if that does what you are looking for.

**Comment by cmuhire** [comment]
can comfirm `editor::SplitSelectionIntoLines` does indeed do that. @bnsouza can confirm so that issue can be closed

**Comment by ns-sjorgedeaguiar** [comment]
I second @mitchbne ; I tend to use this feature a lot in vscode and it's really something I miss having a shortcut for.
