### ISSUE TITLE
"Failed to join project"

### ISSUE THREAD

**Issue by nixpulvis** [zed-industries/zed#8068]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a channel I created clicking on my own project folder will trigger an error: "Failed to join project: already subscribed to entity. Please try again."

I'm still learning Zed so I'm not quite sure what I expect this to do, but the error message doesn't really help me much. I'm assuming it's because it's my own project and it's always going to be open. Having yet to play with Zed with multiple users, I can't say what I expect this to do, but hopefully this issue makes sense.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

<img width="312" alt="Screenshot 2024-02-20 at 9 55 12 AM" src="https://github.com/zed-industries/zed/assets/715947/fe590578-73fe-4a81-a8ff-c6a48576329f">

**Comment by ConradIrwin** [comment]
Thanks for the report! We should notice you are already joined and just focus the window instead of erroring.
