### ISSUE TITLE
UI shaking

### ISSUE THREAD

**Issue by alygin** [zed-industries/zed#8084]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Some UI elements that are meant to be static, are moving back and forth by themselves when there's a blinking cursor on the screen. They become static when focus is switched and the cursor disappears.

I think it happens with stretched or relatively positioned elements when container has certain width. The problem disappears when the container is resized to other width.

### Environment

Zed: v0.124.0 (Zed Dev)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: x86_64

Can't reproduce in 0.122.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/2101250/2b0d704a-9b6c-4d78-bfce-5510c38376dc

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I'm having something similar where popovers are flickering on and off in time with the cursor.

**Comment by JosephTLyons** [comment]
cc: @ForLoveOfCats

**Comment by JosephTLyons** [comment]
Also, wondering if this is the same:

- https://github.com/zed-industries/zed/issues/8050

**Comment by alygin** [comment]
> Also, wondering if this is the same:

Oh, sorry, I didn't notice that issue. It looks like the problem is the same. I guess, mine may be closed as a dublicate.

**Comment by JosephTLyons** [comment]
No worries at all - closing this in favor of #8050.

Also, just wanted to say that we really appreciate all the work you've put into Zed @alygin.

**Comment by alygin** [comment]
@JosephTLyons, thank you. It's my pleasure to make a small contribution to such a cool project to which I wish great success.
