### ISSUE TITLE
Markdown highlight errors

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8108]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![todo](https://github.com/zed-industries/zed/assets/45585937/dfae23c6-4a74-4dad-93a5-c396abb25aa4)

### Environment

Zed: v0.123.2 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by romans-ovo** [comment]
I've reproduced it with the following text:

```
Hello `there` and Hello `<world>` - syntax is messed up
```

<img width="644" alt="Screenshot 2024-02-22 at 15 42 58" src="https://github.com/zed-industries/zed/assets/92028468/2889d3cc-7d35-4f96-b5d3-ec5747d58fa5">

**Comment by JosephTLyons** [comment]
Another similar one, if anyone jumps on this:

- https://github.com/zed-industries/zed/issues/4565
