### ISSUE TITLE
Wrong LSP gets used sometimes

### ISSUE THREAD

**Issue by ryanwinchester** [zed-industries/zed#8129]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Sometimes the wrong LSP is used.

Sometimes the default LSP starts instead of the one I have defined in my config.

config:
```json
  "elixir": {
      "lsp": {
        "local": {
          "path": "~/Code/forks/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
          "arguments": []
        }
      }
    },
```

I'm only noticing it this week.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

You can see there is a `.elixir_ls` directory when it should be _only_ `.lexical`

<img width="1353" alt="Screenshot 2024-02-21 at 12 04 49 PM" src="https://github.com/zed-industries/zed/assets/2897340/3e8e5048-5050-4125-9f87-b93ece12ffe9">

And you can see the errors showing up are from `ElixirLS` and not `Lexical`

<img width="1189" alt="Screenshot 2024-02-21 at 12 05 41 PM" src="https://github.com/zed-industries/zed/assets/2897340/8a0b22b0-540f-4cb8-907e-4f0ab42309c0">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"45"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"46"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"47"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"48"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"49"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"50"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"51"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"52"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"53"}
2024-02-21T11:54:05-04:00 [WARN] failed to deserialize LSP message:
{"error":{"code":-32800,"message":"Request cancelled"},"id":"54"}

**Comment by diocletiann** [comment]
I tried this for ZLS and it's still using the default one.
