### ISSUE TITLE
unresolved extern crate on rustc_* crates

### ISSUE THREAD

**Issue by lucarlig** [zed-industries/zed#8140]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

added this to the cargo.toml and tried to use same setup for vscode

```
# in cargo toml
[package.metadata.rust-analyzer]
rustc_private = true

# in settings
  "rust-analyzer.rustc.source": "discover",
  "lsp.rust-analyzer.rustc.source": "discover",
  "lsp": {
    "rust-analyzer": {
      "rustc": {
        "source": "discover"
      }
    }
  }
```
it gives unresolved extern crate when importing any rustc_* crate for example `rustc_session`
<img width="408" alt="image" src="https://github.com/zed-industries/zed/assets/20149527/7388ffb9-673c-4119-86d9-986fecd5f603">

cargo build works no problems
```
proj on  main [!] is 📦 v0.1.0 via 🦀 v1.78.0-nightly took 2s
❯ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
```

### Environment

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Model Number:	MK183B/A
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	10151.81.1
  OS Loader Version:	10151.81.1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by lucarlig** [comment]
@JosephTLyons I would be happy to contribute if it’s a simple fix, any pointer to what I should be looking at to make this work?

**Comment by JosephTLyons** [comment]
Going to lean on @SomeoneToIgnore to help answer this, as I'm not quite sure.

**Comment by SomeoneToIgnore** [comment]
* we do not have any LSP-level configs that start with `source`: https://github.com/zed-industries/zed/blob/e01a6066164fb27b498f6d2d070b420fb8c66620/crates/project/src/project_settings.rs#L63-L68
So I wonder if that value has to be passed in the `initialization_options`?
```json
"lsp": {
        "rust-analyzer": {
            "initialization_options": {
                "source": "discover",
...snip
```

* I've not developed rustc, but the config doc (https://rust-analyzer.github.io/manual.html#configuration) has something suspicious:
```
rust-analyzer.rustc.source (default: null)

    Path to the Cargo.toml of the rust compiler workspace, for usage in rustc_private projects, or "discover" to try to automatically find it if the rustc-dev component is installed.

    Any project which uses rust-analyzer with the rustcPrivate crates must set [package.metadata.rust-analyzer] rustc_private=true to use it.

    This option does not take effect until rust-analyzer is restarted.
```
so maybe there also has to be more configs enabled?

**Comment by lucarlig** [comment]
@SomeoneToIgnore wow! thanks, now I can use zed. Just missed rustc, this works:
```json
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "rustc": {
          "source": "discover"
...snip
```
I wonder why adding that extra step in the config, probably something like removing that extra field would keep the docs from rust-analyzer relevant, maybe something like this:
``` rust
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, JsonSchema)]
#[serde(rename_all = "snake_case")]
type LspSettings = Option<serde_json::Value>;
```
not sure if this breaks other lsp tough

**Comment by SomeoneToIgnore** [comment]
It would break everybody's existing configs for sure, so if we're planning to break it, I would suggest to do something more human-readable as VSCode has it: `rust-analyzer.rustc.source`.
Maybe we should do that at some point.
