### ISSUE TITLE
OpenSUSE package installation script support

### ISSUE THREAD

**Issue by QazCetelic** [zed-industries/zed#8141]
### Check for existing issues

- [X] Completed

### Describe the feature

I've looked and the required packages from the existing script have the following names on OpenSUSE:
- `alsa-lib-devel`
- `fontconfig-devel`
- `vulkan-validationlayers`
- `libxkbcommon-x11-devel`

There is no package named `wayland` on OpenSUSE, but that shouldn't matter because people that do use Wayland instead of X11 obviously already have it installed.

I'm currently compiling zed and will share whether I've been able to successfully run it when it's done.

**Comment by QazCetelic** [comment]
**Update**: I've been able to run it, but it's not without flaws.

Both displays disconnect (monitor receives no Displayport input) a couple seconds after the editor opens. A few seconds later, the main monitor comes back but the second one requires disabling and enabling it to get it back.

**Comment by QazCetelic** [comment]
I've moved the monitor disconnect issue to a separate issue.

**Comment by PonyLucky** [comment]
Using Nobara OS (Fedora based), I had the error: `could not find system library 'alsa' required by the 'alsa-sys' crate`. This got fixed by:
`sudo dnf install alsa-lib-devel`

Screenshoot
![image](https://github.com/zed-industries/zed/assets/60187395/5af75787-c2fe-4d09-a7de-0e10ffd614bc)

**Comment by Encephala** [comment]
> Using Nobara OS (Fedora based), I had the error: `could not find system library 'alsa' required by the 'alsa-sys' crate`. This got fixed by: `sudo dnf install alsa-lib-devel`

Chiming in, for someone having similar issues on a Debian(-based) system: I had the exact same build error, had to `apt-get install libasound2-dev` to get it working.

**Comment by ConradIrwin** [comment]
Closing this. Please send PRs to add any missing build deps to the script
