### ISSUE TITLE
`ToggleGraphicsProfiler` Command Causes Panic

### ISSUE THREAD

**Issue by CurbaiCode** [zed-industries/zed#8145]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Both the `ToggleGraphicsProfiler` command and the menu action `Help -> Toggle Graphics Profiler` cause Zed to crash unexpectedly.

### Environment

Zed: v0.123.2 (Zed)
OS: macOS 12.6.6
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

<details>
<summary>Zed.log</summary>
<pre>
2024-02-21T12:54:46-07:00 [ERROR] {
  "thread": "main",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "/Users/administrator/actions-runner-2/_work/zed/zed/crates/gpui/src/app.rs",
    "line": 1239
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "Zed::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys_common::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::panicking::panic",
    "<editor::Editor>::show_cursor_names::{closure#0}::{closure#0}",
    "<async_task::raw::RawTask<<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::option::Option<()>>>>>, core::option::Option<()>, <gpui::executor::ForegroundExecutor>::spawn::inner<core::option::Option<()>>::{closure#0}, ()>>::run",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "Zed::main",
    "std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.123.2",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "12.6.6",
  "architecture": "x86_64",
  "panicked_on": 1708545286651,
  "installation_id": "9cc83f16-ce14-455d-b6a3-16fe25fab29f",
  "session_id": "333120a7-89b6-45ad-a35a-d51c76eb6cbb"
}
</pre>
</details>

**Comment by jansol** [comment]
I suspect that your macOS version might simply not *have* said profiler.

**Comment by SomeoneToIgnore** [comment]
> I suspect that your macOS version might simply not have said profiler.

I believe, every macOs has the HUD
![image](https://github.com/zed-industries/zed/assets/2690773/9a923140-ae1f-4130-9de0-0c9626618851)
 and this sentence is wrong.

This is actually a thing for me too: it does not happens always, but something makes it panic from time to time.

**Comment by jansol** [comment]
At least I wasn't able to get anything HUD-related to show up on 12.7.3

**Comment by JosephTLyons** [comment]
What's interesting is this feature hasn't worked for me at all. Toggling does nothing.

**Comment by SomeoneToIgnore** [comment]
This is also an issue for me, have you tried toggling it twice in a row?
That does "work" for me when the HUD is on and I want to hide it.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/8567 solves this in a radical way by reverting the functionality.

To get the hud in Zed on macOs, one could set the corresponding env variable, e.g.: `/bin/launchctl setenv MTL_HUD_ENABLED 1`, so far this is the only way.
