### ISSUE TITLE
Elixir Programming Language Server Support: Lexical LSP

### ISSUE THREAD

**Issue by Nezteb** [zed-industries/zed#8148]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed currently supports ElixirLS and Next LS, which is fantastic:

- https://github.com/zed-industries/zed/blob/main/docs/src/languages/elixir.md
- https://github.com/zed-industries/zed/blob/main/crates/zed/src/languages.rs#L165-L183
- https://github.com/zed-industries/zed/blob/main/crates/zed/src/languages/elixir.rs

There is a third Elixir language server I'd love to see supported called Lexical: https://github.com/lexical-lsp/lexical

If you are curious to compare the three, here are some of my notes: https://gist.github.com/Nezteb/dc63f1d5ad9d88907dd103da2ca000b1

**Comment by zoedsoupe** [comment]
someone is already tackling this issue? i would like to contribute to the zed project and it would be awesome to start with this issue as i really like lexical's features and want this support too

**Comment by maxdeviant** [comment]
Lexical is now available as a language server in the Elixir extension (extracted in #10948).

To use it you can install the Elixir extension and add the following to your settings:

```json
{
  "languages": {
    "Elixir": {
      "language_servers": [ "lexical", "!elixir-ls", "!next-ls", "..."]
    }
  }
}
```

**Comment by camstuart** [comment]
Are we not required to specify the path of lexical somewhere?

**Comment by maxdeviant** [comment]
> Are we not required to specify the path of lexical somewhere?

Lexical gets downloaded from a GitHub releases, or you can override it by having `lexical` on your $PATH:

https://github.com/zed-industries/zed/blob/83592306c519266814cacdf8a6abfed6b283c01d/extensions/elixir/src/language_servers/lexical.rs#L25-L27
