### ISSUE TITLE
Add Code Shortcuts For HTML (and maybe other languages)

### ISSUE THREAD

**Issue by Hugoonreplit** [zed-industries/zed#8156]
### Check for existing issues

- [X] Completed

### Describe the feature

# The Feature
I think that a perfect feature for .html files in Zed would be like in VSCode where you can simply initialize a div with an id or a class, or even both! Here is a simple example

```html
=> Div with class and id named "test"
.test#test

=> Input with class named "test"
input#test
```

And as you've seen in the example you can also do this with other arguments like inputs! Not only that but if you need multiple divs or any other element you can simple multiply them with an asterisc followed by the number of times you want the argument.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1376" alt="Screenshot 2024-02-22 at 00 10 21" src="https://github.com/zed-industries/zed/assets/93369643/11db08f4-abc4-439f-bef7-1b9a55ac3927">

**Comment by jansol** [comment]
So basically "snippets"? #5743 #4611

**Comment by JosephTLyons** [comment]
I think this might be more specifically about Emmet support:

- https://github.com/zed-industries/zed/issues/4992

Is that right @Hugoonreplit? I think I will close this in favor of the aforementinoed.
