### ISSUE TITLE
command palette filter should trim spaces

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#8184]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Press cmd-shift-p
2. Press `space` 6 times
3. There are no matches

The main impact is obviously when spaces are typed in between search terms.

### Environment

Zed: v0.123.2 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Imgkl** [comment]
@JosephTLyons can you close this? The fix has been merged to main.
