### ISSUE TITLE
Local LLM Support

### ISSUE THREAD

**Issue by jstn-ck** [zed-industries/zed#8192]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to use local LLM model for the copilot (chat/inline) ? So we dont have to use the OpenAI Keys.

**Comment by Belluxx** [comment]
It's being discussed here #4424

**Comment by rubjo** [comment]
@jstn-ck See https://github.com/zed-industries/zed/issues/4424#issuecomment-1958886354
