### ISSUE TITLE
typescript: renaming exported constants are not updated in files importing them

### ISSUE THREAD

**Issue by sirber** [zed-industries/zed#8204]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
./constant.ts
export cosnt MyConstant = 1;

/myfile.ts
import { MyConstant  } from './constant.ts'
```

then I rename `MyConstant` to  `MY_CONSTANT`

in `myfile.ts`, the autocomplete still show `MyConstant` as the correct import. Closing files and reopening them does not solve the issue, I have to quit and relaunch Zed to have the updated constant name.

### Environment

Zed: v0.123.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @sirber, does this rename work as expected in VS Code? I'm curious if this is something wrong with tsserver or with Zed itself.

**Comment by sirber** [comment]
> Hey @sirber, does this rename work as expected in VS Code? I'm curious if this is something wrong with tsserver or with Zed itself.

I haven't seen this issue with vscode.

**Comment by georgeiliadis91** [comment]
I can second this.
