### ISSUE TITLE
Mouse Pointer Flicker

### ISSUE THREAD

**Issue by justinrclarke** [zed-industries/zed#8207]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After Zed restarted from a recent update this morning, I found the mouse flickering between the default arrow to the pointer hand while hovering over directories and files on the project pane.

The actions I took before I noticed the flicker. I moved the Zed window to my right monitor and used BetterSnapTool to expand the window to full screen, not full-screen mode. I then clicked on Zed > Settings > Select Theme. Click on the window outside the theme selector to close it.

This issue is gone now, after closing and re-opening the app multiple times. I could re-create the issue a second time by opening the application from the CLI command in a project directory. Took the same steps to move the window to a different monitor. But when I moved focus to a new app via CMD+TAB and came back the issue was no longer present. And hasn't shown up again.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14376865/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @justinrclarke, we are working to get this resolved as soon as possilbe - its one of our top priorities.

**Comment by mehmehsloth** [comment]
![image](https://github.com/user-attachments/assets/3ab117b1-7a87-49e8-958c-2640270c4f72)

I am assuming this is the type of flicker mentioned in the above issue. This is still happening on Linux (Pop OS). I am running Zed 0.147.2 

I have noticed this kind of flicker before but usually is fixed when I switch workspaces

**Comment by SephReed** [comment]
Not fixed yet
