### ISSUE TITLE
If create/access `~/Library/Logs/Zed/Zed.log` failed, Zed can't be launched.

### ISSUE THREAD

**Issue by Wyvern** [zed-industries/zed#8209]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

Zed app launch need `~/Library/Logs/Zed/Zed.log` file to be created, is it necessary?
If some system disable log writing, you can't create/write log files to specific folder.

1. Zed app launch shouldn't crash if log file can't be created or accessed.
2. Zed.log file should set as an logging option NOT a requirement.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Log file initialization happens here:

https://github.com/zed-industries/zed/blob/991c9ec441711a4c0b10ce595f3025f430123800/crates/zed/src/main.rs#L512-L534

Also, there's `OpenLog` action that has to be altered too: https://github.com/zed-industries/zed/blob/991c9ec441711a4c0b10ce595f3025f430123800/crates/zed/src/zed.rs#L473

**Comment by dheeraj-coding** [comment]
I am looking at the code now refactoring it. Do I simply default to stdout logger in case we can't open file or also provide a settings option to set explicitly log outputs?

**Comment by SomeoneToIgnore** [comment]
I would start with the simple approach first and, if that looks ok after implementing, give the options a stab.

I'm not sure options will work that well, because they are initialized way below `main.rs` (in `zed.rs`) and most probably that refactoring will be big.
