### ISSUE TITLE
Can't move throught completions with arrows

### ISSUE THREAD

**Issue by teziovsky** [zed-industries/zed#8211]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The problem is related to the completion menu. When I trigger the completion menu, I can't move selection with arrows 🤔

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/36273653/0ae01c15-332e-44ca-a908-1962df986b78

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
It works for me with standard settings and keybinds:


https://github.com/zed-industries/zed/assets/1185253/25e32202-204c-497f-a204-ecf347a397fc

Do you have a special keyboard layout? Or did you change your keymap?

**Comment by teziovsky** [comment]
Oh yea, something is broken with my keymaps 😔 It would be great to have UI interface to change keybindings like in vs code for example 😶‍🌫️
So I think it's resolved. I'm closing this issue, thank your for help 🙏🏼
