### ISSUE TITLE
Regression in File Tree: Cannot Move or Create Files

### ISSUE THREAD

**Issue by shellscape** [zed-industries/zed#8215]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Feb-22-2024 13-44-10](https://github.com/zed-industries/zed/assets/76371/cbbe4a83-c91e-45f7-8644-a30555c5954a)

Context I forgot to add: Confirmed that `src` was a directory, even though it's showing as a file icon. 

### Environment

System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 579.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

The logs didn't contain anything from the timestamps that the recording was made

**Comment by JosephTLyons** [comment]
This is odd, I'm not able to reproduce it on my end. I'll try a few more things - maybe some other users will run into this as well.

**Comment by shellscape** [comment]
If we can't reproduce, I'll nuke the install and reinstall.

**Comment by shellscape** [comment]
Thanks for the ping. I nuked the install today and got thratest preview, issue is magically gone. Closing 🫡
