### ISSUE TITLE
Crash when navigating trough themes while in a call 

### ISSUE THREAD

**Issue by Sethback** [zed-industries/zed#8221]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While in a call in zed (at least thats how I can reproduce it), go to themes, and navigate trough it with arrow down.. at some point zed crashes and quits. 

I'm available on discord by the same name and can collaborate if any extra info is necessary. 

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-22T20:39:24+01:00 [ERROR] {
  "thread": "main",
  "payload": "attempt to calculate the remainder with a divisor of zero",
  "location_data": {
    "file": "crates/theme/src/styles/players.rs",
    "line": 143
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "Zed::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys_common::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::panicking::panic",
    "<core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>, <gpui::elements::div::Stateful<gpui::elements::div::Div> as gpui::element::ParentElement>::children<gpui::elements::div::Stateful<gpui::elements::div::Div>, core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<&call::participant::RemoteParticipant>, <collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render::{closure#2}::{closure#2}>>::{closure#0}> as core::iter::traits::iterator::Iterator>::next",
    "<collab_ui::collab_titlebar_item::CollabTitlebarItem as gpui::element::Render>::render",
    "gpui::view::any_view::request_layout::<collab_ui::collab_titlebar_item::CollabTitlebarItem>",
    "<gpui::view::AnyView as gpui::element::Element>::request_layout::{closure#0}",
    "<gpui::view::AnyView as gpui::element::Element>::request_layout",
    "<gpui::element::DrawableElement<gpui::view::AnyView>>::request_layout",
    "<gpui::elements::div::Div as gpui::element::Element>::request_layout::{closure#1}::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::request_layout",
    "<gpui::element::DrawableElement<gpui::elements::div::Stateful<gpui::elements::div::Div>>>::request_layout",
    "gpui::view::any_view::request_layout::<workspace::Workspace>",
    "<gpui::view::AnyView>::draw::{closure#0}",
    "<gpui::view::AnyView>::draw",
    "<gpui::window::WindowContext>::draw",
    "<gpui::window::Window>::new::{closure#0}::{closure#1}",
    "<gpui::window::Window>::new::{closure#0}",
    "gpui::platform::mac::window::step",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "Zed::main",
    "std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.123.3",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "14.3.1",
  "architecture": "aarch64",
  "panicked_on": 1708630764140,
  "installation_id": "e861c22a-9952-4606-9499-9d68c079100a",
  "session_id": "a57f0ee2-2e67-48ff-a498-e094fc772a49"
}

**Comment by slymax** [comment]
I think this might already be fixed in the latest preview release – see #7733

**Comment by Sethback** [comment]
Indeed can't reproduce it in preview.
