### ISSUE TITLE
Zed frame drops below 60FPS

### ISSUE THREAD

**Issue by Imgkl** [zed-industries/zed#8224]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that Zed some times below 60FPS. Is this because of variable refresh rate or something?

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1799" alt="Screenshot 2024-02-23 at 2 32 48 AM" src="https://github.com/zed-industries/zed/assets/25414681/1c43a1f3-3acd-4384-a648-366db27aff43">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jansol** [comment]
Yes, if nothing has changed and there is no other reason to redraw, Zed won't. There's a whole blog post about this: https://zed.dev/blog/120fps

**Comment by SomeoneToIgnore** [comment]
Yes, I think this is the answer — if you try scrolling that list, the FPS meter should go up.

**Comment by JosephTLyons** [comment]
I think this is fine.  If nothing is going on, the frame rate is reduced, which helps with energy consumption. You should see it spike back up when there is activity going on. Going to close this out for now - let me know if there's anything I missed here that we should reopen for.
