### ISSUE TITLE
automatic terminal startup takes raw filepath without escaping spaces

### ISSUE THREAD

**Issue by Approximately-Equal** [zed-industries/zed#8226]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening a new terminal that contains a virtual environment automatically tries to source the virtual environment. If the root directory has spaces (eg "project name") then the terminal will try to run `source path/to/project name/.venv/bin/activate`, which will fail because the terminal sees the whitespace as different arguments.

Reproduce: 
1. Open python directory with pre-existing virtual environment
2. Open a new terminal window, the terminal should automatically run to try and source the project, so the top lines of the terminal should be 

    > source path/to/directory with spaces/.venv/bin/activate
    > Last login: ...
    > $ source path/to/directory with spaces/.venv/bin/activate                                                                                    
    > source: no such file or directory: path/to/directory (notice the lack of the full directory name "directory with spaces")

How to fix: Unless there is a reason not to, a simple fix would be to wrap the source in quotes. source "path/to/directory with spaces/.venv/bin/activate" will work, regardless of whether there are spaces or not. 

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.2.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Approximately-Equal** [comment]
Came back to look at fixing this. Noticed some extra stuff. For one, its one of the directories in the global path, and not the root directory, that has a space. Not that I think this makes a difference. The weird thing is that this should be getting fixed by the activate_python_virtual_environment function.

**Comment by JosephTLyons** [comment]
Hey @Approximately-Equal, I think this might be fixed via this PR that landed:

https://github.com/zed-industries/zed/pull/7787

I think this goes out to the stable channel this week.

**Comment by Approximately-Equal** [comment]
Thanks for the clarification. As you can see I noticed the wrapper, but I didn't realize that it hadn't gone out get, so I thought it just didn't work.
