### ISSUE TITLE
Language extensions need to be able to provide language settings

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#8232]
### Check for existing issues

- [X] Completed

### Describe the feature

For example, a language exension needs to be able to supply `tab_size`, so the user doesn't have to add a language_override section to their `settings.json` file for each of their language extensions.

**Comment by JosephTLyons** [comment]
@maxbrunsfeld - what do you think about this? I sort of view this as the last required piece for language packages:

- Ability to provide grammar
- Ability to provide language server
- Ability to provide default settings

**Comment by maxbrunsfeld** [comment]
Yeah, it makes sense.

**Comment by JosephTLyons** [comment]
Closed via: https://github.com/zed-industries/zed/pull/10296
