### ISSUE TITLE
Selecting the semantic search option causes Zed to instantly crash

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#8250]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Title

### Environment

Zed: v0.125.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[crash_report.txt](https://github.com/zed-industries/zed/files/14382436/crash_report.txt)

**Comment by ConradIrwin** [comment]
Semantic search is gone
