### ISSUE TITLE
add ability to copy text from completion doc panel

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#8251]
### Check for existing issues

- [X] Completed

### Describe the feature

for example, in VSCode:

I can copy the rust example into editor.

<img width="891" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/65eb8924-bb8c-48d0-bf71-77772cde0364">

**Comment by JosephTLyons** [comment]
I think this would be solved with this request:

- https://github.com/zed-industries/zed/issues/4606

Just getting copy and paste supported in popovers in general.  Going to close this one out as a duplicate.
