### ISSUE TITLE
Error Tooltip (on hover) is unusable with a custom theme

### ISSUE THREAD

**Issue by DanceParty** [zed-industries/zed#8254]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

_First off, apologies if I missed a separate bug report, I tried searching~_

TypeScript error dialog is transparent which makes it nearly impossible to read from. Updating the experimental settings doesn't work either currently. Maybe it requires a separate bug report, but the setting `experimental.error.background: "#000"` doesn't work either but for a separate reason (screenshot below) in that it blinks with the cursor instead of stays separate. This is fixed by removing the cursor blink in the settings.

Steps to reproduce first issue:

1. Install "Smooth Dark"
2. Set custom theme in the settings
3. Hover over TypeScript error
4. See un-viewable tooltip/dialog

Settings for the second issue:

```json
{
  "experimental.theme_overrides": {
    "error.background": "#000"
  },
}
```

Settings for a workaround:

```json
{
  "experimental.theme_overrides": {
    "error.background": "#000"
  },
  "cursor_blink": false
}
```

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

**First described issue**
![Background transparent bug](https://github.com/zed-industries/zed/assets/10778294/8e75d3d0-bfb3-4201-9e3f-1c152c508b4d)

**Second described issue**
![Dialog blinking bug](https://github.com/zed-industries/zed/assets/10778294/f5db0801-8b91-4342-8564-36d9b6b01352)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @DanceParty, thanks for bringing up the first issue. I think the second issue you describe is related to:

- https://github.com/zed-industries/zed/issues/8207

And this is one of our top priorities being worked on right now.

**Comment by segersniels** [comment]
Hi @DanceParty, I'm the creator of the Smooth theme. I noticed the transparent background as well. Let me see if I can fix that on my end.
