### ISSUE TITLE
Allow me to disable popup warning

### ISSUE THREAD

**Issue by nckre** [zed-industries/zed#8255]
### Check for existing issues

- [X] Completed

### Describe the feature

![CleanShot 2024-02-23 at 10 04 49](https://github.com/zed-industries/zed/assets/29370294/f5b51495-7b3d-4cfe-bc92-c4ddd169db84)

Not sure if this is a bug or expected behaviour. I copy+pasted some faulty code into my prisma.schema.

With each key stroke, I get a popup warning that I should switch the language server, making it hard to fix the code.

**Comment by jordanjones98** [comment]
#8229 is slightly related, Language Servers should show errors in the bottom bar not intrusive windows like this I think.
