### ISSUE TITLE
Terminal file link – Path with + are not clickable

### ISSUE THREAD

**Issue by binajmen** [zed-industries/zed#8256]
### Check for existing issues

- [X] Completed

### Describe the feature

The second link is clickable. The first is not, most probably due to the `+` and/or `$` character(s).
```
/Users/.../app/routes/manager.$id+/projects+/new.tsx
   70:9   error  'actionData' is assigned a value but never used                  @typescript-eslint/no-unused-vars
  365:22  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities

/Users/.../app/utils/postgres.server.ts
  1:7  error  'INTEGRITY_CONSTRAINT_VIOLATION' is assigned a value but never used  @typescript-eslint/no-unused-vars
  2:7  error  'RESTRICT_VIOLATION' is assigned a value but never used              @typescript-eslint/no-unused-vars
```

I found a related issue but the fix was limited to square brackets: https://github.com/zed-industries/zed/issues/6246

**Comment by SomeoneToIgnore** [comment]
This is the regex we use to detect "words" that might become paths: https://github.com/zed-industries/zed/blob/50dd38bd0283d341d249d34769f59f7225a4f37c/crates/terminal/src/terminal.rs#L420

and here are the hacks we do to support `[]` in paths: 
https://github.com/zed-industries/zed/blob/50dd38bd0283d341d249d34769f59f7225a4f37c/crates/terminal/src/terminal.rs#L834-L848

Seems that it would be enough to adjust the regex, but if all fails, one can adjust the hacks too.

**Comment by zephaniahong** [comment]
Hi! May I know how you're the following to appear? i.e. What command are you running 
I want to be able to replicate it

Thank you!

> ```
> /Users/.../app/routes/manager.$id+/projects+/new.tsx
>    70:9   error  'actionData' is assigned a value but never used                  @typescript-eslint/no-unused-vars
>   365:22  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities
> 
> /Users/.../app/utils/postgres.server.ts
>   1:7  error  'INTEGRITY_CONSTRAINT_VIOLATION' is assigned a value but never used  @typescript-eslint/no-unused-vars
>   2:7  error  'RESTRICT_VIOLATION' is assigned a value but never used              @typescript-eslint/no-unused-vars
> ```

**Comment by crbellis** [comment]
Hey @SomeoneToIgnore, 

This was a pretty quick fix. I updated the following line to include both `$` and `+` characters:
https://github.com/zed-industries/zed/blob/11ac649bc612106aaed7999febbf1c3e117fcfb0/crates/terminal/src/terminal.rs#L420

Added my PR [here](https://github.com/zed-industries/zed/pull/8321).

Here is an example of the path link working correctly:
<img width="1019" alt="Screenshot 2024-02-23 at 8 59 45 PM" src="https://github.com/zed-industries/zed/assets/63214891/2715eba6-5a29-4187-8812-c75259233a1b">

**Comment by SomeoneToIgnore** [comment]
Great, thank you for helping with that and glad to see another `good first issue` label telling the truth.

**Comment by danielzsh** [comment]
Since #8321 was merged, should this issue be closed?

**Comment by SomeoneToIgnore** [comment]
Definitely, thank you for reminding.

**Comment by binajmen** [comment]
Sorry, I didn't notice the activity on the ticket (I should have received a notification 👀).
Glad to see it is already fixed! 🙏 🚀
