### ISSUE TITLE
Show import path

### ISSUE THREAD

**Issue by TudorEsan** [zed-industries/zed#8259]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi!

I don t know if this exists or not and I did not found a soultion for it.

It would be nice for the intelisense to show the import pat of the Component/Function

 or whatever. As you can see in the photo, there are 2 Components named "Badge" and its really hard to know wich one to choose

<img width="586" alt="Screenshot 2024-02-23 at 11 37 54" src="https://github.com/zed-industries/zed/assets/55596191/dc5a15d0-5959-4855-b1a6-cdc31c177b9a">

**Comment by JosephTLyons** [comment]
Hey @TudorEsan, I think this request is similar to these, so I'm going to close it out. Feel free to add a comment if there's something else I'm missing and I will reopen this:

- https://github.com/zed-industries/zed/issues/7099
- https://github.com/zed-industries/zed/issues/4457
