### ISSUE TITLE
scrolling still isn't smooth (smoother than before the fix but still off)

### ISSUE THREAD

**Issue by Leikoe** [zed-industries/zed#8264]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

on a m1 pro macbook pro 2021 14", scrolling in zed still feels off compared to apple's TextEdit (on 120hz)

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.1.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by amatiash** [comment]
On my machine `macOS 12.7.3 (21H1015), Intel` the scroll got worse (less responsive, feels fluid) after [Theo - t3․gg](https://www.youtube.com/@t3dotgg) mentioned he had scroll issues and "fixes" being introduced. Fixed for him but mine broke. Didn't have scroll issues before.

**Comment by amatiash** [comment]
https://github.com/zed-industries/zed/assets/4305962/6ea0e1be-2090-4052-96ba-13677cdd2bb4
