### ISSUE TITLE
Zed Not Recognizing Git Extension in Subfolders

### ISSUE THREAD

**Issue by siaminz** [zed-industries/zed#8275]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Zed editor in a mono repository, I’ve noticed that it doesn’t consistently recognize Git extensions when working within subfolders. Specifically:

When I open the main folder, Git integration works as expected.
However, when I open a subfolder, Zed fails to recognize the Git status.
This behavior makes it challenging to work efficiently in mono repos where subfolders are common. I’d appreciate any insights or solutions to address this issue.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Hey! To clarify: do you mean submodules? Can you give us some steps to reproduce?

**Comment by siaminz** [comment]
Hi. No.  Here are the steps to reproduce:

1. Create a folder structure as follows:

- a/
  ├── b/
  └── c/
  
2. Initialize Git in the main folder (a).
3. Open the main folder (a). Git integration works correctly.
4. However, when opening subfolders (b or c) alone, Zed fails to recognize Git in the parent folder.

**Comment by simoncocking** [comment]
Yeah stuck between a rock and a hard place on this one:
1. Zed won't recognise the git repo in a parent folder; and
2. `next-ls` can't initialise the LSP when running in the parent folder because that's not where the Mix project is defined.

This leaves me choosing between having _either_ Git integration working, _or_ the LSP. 😖
