### ISSUE TITLE
Improper tooltip stacking over context menu

### ISSUE THREAD

**Issue by ntoskrn** [zed-industries/zed#8276]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening a mouse context menu doesn't necessarily lock up the editor for actions like hovering over a keyword, which causes the hint to go to the back of the context menu, ideal solution would to be lock up the editor in such way, that you can't scroll or hover anywhere until you've closed out the context menu.

Reproduction steps:
- right click anywhere 
- hover over a keyword thats around the same x and y position of the context menu
- hover tooltip is stacked behind the context menu, even if it was opened afterwards

<img width="749" alt="image" src="https://github.com/zed-industries/zed/assets/126423229/a987a1c7-2f95-4d4b-bc6a-1b1b3e52248d">

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.2.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
I can no longer reproduce this with the current Zed release.
If you are still experiencing this issue, I'm happy to reopen.
