### ISSUE TITLE
the "wrap_guides" are almost invisible - make them configurable

### ISSUE THREAD

**Issue by erf** [zed-industries/zed#8304]
### Check for existing issues

- [X] Completed

### Describe the feature

If i enable  "wrap_guides" they looks almost invisible, perhaps it's **alpha** and **thickness** could be made configurable.

E.g.

```
wrap_guide_alpha = 0.5
wrap_guide_thickness = 2.0 // or "width"?
```

version Zed Preview 0.124.4

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="519" alt="Screenshot 2024-02-23 at 21 19 17" src="https://github.com/zed-industries/zed/assets/1562523/3e5a192d-d87b-4ae3-b0df-5464d3a85c96">

**Comment by jansol** [comment]
The colour can already be set in themes (and you can override it in your config, see `theme_overrides` as described in https://zed.dev/blog/user-themes-now-in-preview)
