### ISSUE TITLE
Use backreferences during replace for capture groups in search

### ISSUE THREAD

**Issue by zacharysyoung** [zed-industries/zed#8315]
### Check for existing issues

- [X] Completed

### Describe the feature

I wanted to search and replace the following text:

```none
r1c1,r1c2
r2c1,r2c2
```

with:

```none
R1C1,R1C2
R2C2,R1C2
```

I can search for all instances of `r(\d)c(\d)`, but I cannot replace them with `R\1C\2`, or `R$1C$2`.

This might be related to #7999 or #7645.

**Comment by mayfieldiv** [comment]
It looks like `R${1}C${2}` works in this case. Here's the reference for the method being used in the find-replace: https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace

**Comment by zacharysyoung** [comment]
@mayfieldiv, ah, thank you! I'll close the issue.

**Comment by tecandrew** [comment]
> It looks like `R${1}C${2}` works in this case. Here's the reference for the method being used in the find-replace: https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace

I think this answer suffices enough to close #7999. It's not the 'traditional' like `\1` vim type of nomenclature, but it works!

**Comment by zacharysyoung** [comment]
An update on the syntax for specifying capture groups in the replacement...

For the example I originally posted, `${#}` is necessary because... I don't really know. My guess is that the $# tokens don't have any whitespace around them, so the parser needs some extra notation to know where a token begins and ends, `R${1}C${2}`. 

In other cases, `$#` works.

If I want to change this list of tab-separated capital cities and countries:

```none
Abu Dhabi	United Arab Emirates
Abuja	Nigeria
Accra	Ghana
Adamstown	Pitcairn Islands
```

then, the regexp `(.+)\t(.+)` correctly represents the two different groups, and the replacement `"$1": "$2"` correctly transforms them to:

```none
"Abu Dhabi": "United Arab Emirates"
"Abuja": "Nigeria"
"Accra": "Ghana"
"Adamstown": "Pitcairn Islands"
```

**Comment by zacharysyoung** [comment]
@tecandrew, this issue is about capture groups in **replace**, and I just read #7999, and that's about using capture groups in **search**.

For the text `kfk`, OP has the regex `(k).\1`, and I believe (even though not said) they expect the entire kfk string to be matched (highlighted) because `\1` means `k` in that context.
