### ISSUE TITLE
Ability to pass current file name to a task

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#8324]
### Check for existing issues

- [X] Completed

### Describe the feature

```json
{
  "label": "run",
  "command": "python",
  "args": ["{current_file}"],
}
```

**Comment by osiewicz** [comment]
We already have ZED_FILE, though we might want to enhance it with things like "worktree-relative path", "path-to-parent-directory" and so on.

**Comment by wmstack** [comment]
There is a bug with the ZED_FILE, it only works for some extensions and doesn't work for other extensions.

**Comment by SomeoneToIgnore** [comment]
Could you recheck this on Zed 0.132 (or above, if happens later) and, if the issue persists, provide more details — which language extensions do and do not have it for you?

**Comment by wmstack** [comment]
Well, I am still on 0.131.6 and I don't think I can update it from inside. However, it doesn't work with java files and text files.

I have a simple echo task, that outputs `"$ZED_FILE"` and it is often a blank line. It seems to work with python but the important part is that with java and some text files it is just blank.

**Comment by JosephTLyons** [comment]
I'm going to close this issue out because we now support `ZED_FILE` - @wmstack, can you open up a new issue for the problem you are encountering?

**Comment by SomeoneToIgnore** [comment]
Thanks, indeed files with languages that do not have tasks, have blank `ZED_FILE` on Stable and Preview improves the general logic, and now filters such tasks away entirely.

I'll work on a fix, so maybe an issue is note really needed.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/10764
