### ISSUE TITLE
VS code's terminal shortcuts not working properly

### ISSUE THREAD

**Issue by Imgkl** [zed-industries/zed#8342]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I press ``Control + ` ``, the ternimal is opening fine, but upon pressing the same keys, it' not closing the terminal

### Environment

Zed: v0.124.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/25414681/c9490c7a-8987-4105-80e5-49ad63f2c952

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
I don't think it's meant to close the terminal panel. The `ctrl-~` keymap is mapped to the `terminal_panel::ToggleFocus` command, as opposed to `"cmd-shift-h": "search::ToggleReplace"`, which e.g. toggles the replace search input.

**Comment by Imgkl** [comment]
@Moshyfawn but don't you think it should be toggling open and close, this is default behaviour in VSC.

**Comment by Moshyfawn** [comment]
To toggle the bottom dock on and off, there's this keymap:

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-j": "workspace::ToggleBottomDock"
    }
  }
]
```

**Comment by Imgkl** [comment]
Yep, This works as expected. It's just weird that with the keymap set to VSC, it's not the default behaviour. 

Thanks @Moshyfawn

**Comment by huacnlee** [comment]
<img width="638" alt="image" src="https://github.com/zed-industries/zed/assets/5518/1c471d25-a257-4b64-af72-56b937b1d58a">

This ``` ctrl+` ``` is `terminal_panel::ToggleFocus`, if changed to `terminal_panel::ToggleDock`, that will better, we can do with ``` ctrl+` ``` open or close the terminal dock.

In currently, we can use ``` ctrl+` ``` to do toggle show/hide if that is **Zoom in** mode.

So, can we do the same behavior for **Zoom out** mode?

**Comment by xezrunner** [comment]
Neither `workspace::ToggleBottomDock`, nor `terminal_panel::ToggleFocus` currently match the VS Code behavior that I'm used to.

In VS Code, pressing the key always first focuses the terminal if it's open, and only closes it when it's already in focus:  
_(I am unsure whether this can be configured, but I couldn't quickly find anything related to it in the Settings)_

```
{
    "key": "cmd+t",
    "command": "workbench.action.terminal.toggleTerminal"
}
```

https://github.com/zed-industries/zed/assets/8061077/c45dac13-709a-4c29-b0ab-8329811d6aca

In Zed, focusing and toggling the panel are separate actions:

```
workspace::ToggleBottomDock
Toggles the panel, regardless of its focus state.

terminal_panel::ToggleFocus
Toggles focus of the panel, but never toggles the panel itself.
```

https://github.com/zed-industries/zed/assets/8061077/21cd6300-82e8-4c21-8d68-3c1721a0fed3

Coincidentally, after looking at 0.133.0's release notes, I figured out that there are context-specific bindings, which allow for re-creating this:

```
{
    "context": "Terminal",
    "bindings": {
      "cmd-t": "workspace::ToggleBottomDock"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "cmd-t": "terminal_panel::ToggleFocus"
    }
  }
```

https://github.com/zed-industries/zed/assets/8061077/9631caeb-41cb-4ef3-bccb-cbe9bbbc9f00

It would be neat if Zed could replicate this with a command (`terminal_panel::FocusToggle`?), or include it as an example in the default keymap.

**Comment by notpeter** [comment]
> It would be neat if Zed could replicate this with a command (terminal_panel::FocusToggle?), or include it as an example in the default keymap.

This is a great idea. I'm including this in the template when I do:
- https://github.com/zed-industries/zed/issues/14248

Given that there's a workaround for emulating the vscode behavior I'm going to close this issue.  Just put this in your ~/.config/zed/keymap.json.  Thanks for sharing this out @xezrunner.

```
[
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-`": "workspace::ToggleBottomDock" // match vscode behavior
    }
  }
]
```

**Comment by victorgxn** [comment]
I have tried a thousand ways and in all of them I have to do ctrl-` twice and in my vscode with one it works and it always ends typing `on line where I am before opening the terminal. It is very lazy. Any advice? I am testing with
[
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-`": "workspace::ToggleBottomDock"
    }
  }
]

**Comment by notpeter** [comment]
@victorgxn When I add the settings you provided this works as expected for me on MacOS.

The default keybinding (in the Workspace context) will
https://github.com/zed-industries/zed/blob/5bb18adbe86edbe368676f9ed3131a9982522b0c/assets/keymaps/default-macos.json#L405 show the BottomDock and focus the existing terminal if present (or spawn a new terminal if not).

And the custom keybinding only applies when in-terminal and hides the dock.

Can you provide some additional info about your environment? (e.g. MacOS/Linux/Windows, keyboard locale, etc). Are you perhaps in a locale where backtick is a [deadkey](https://en.wikipedia.org/wiki/Dead_key)?
