### ISSUE TITLE
Zed opens everytime on the wrong monitor

### ISSUE THREAD

**Issue by rehoehle** [zed-industries/zed#8345]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Everytime you open Zed. It's opened on the Macbook Monitor and not on the monitor where it was placed the last time so the external monitor. Thats a bit annoying. Is there a trick?

### Environment

MacBook Pro M2 with external Monitor.

### Log

When you close the window this appears in the log.

```
2024-02-24T21:16:11+01:00 [ERROR] crates/gpui/src/window.rs:425: window not found
2024-02-24T21:16:11+01:00 [ERROR] crates/gpui/src/window.rs:416: window not found
```

**Comment by asesh** [comment]
I find this really annoying. Please fix this issue. Thanks
