### ISSUE TITLE
API Example usage dont show in the autocomplete window

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#8346]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i see the api docs on the autocomplete window it doesnt show the example usage

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-02-24 alle 21 16 22](https://github.com/zed-
![Screenshot 2024-02-24 alle 21 16 22](https://github.com/zed-industries/zed/assets/53220110/7c356305-915a-4dc4-ac33-35f5a1ecca88)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bennetbo** [comment]
Not sure why, but the actual rust docs do not specify an example, you can see it [here](https://doc.rust-lang.org/std/primitive.i32.html#method.checked_abs).

It works perfectly fine for `i32::wrapping_rem(...)`, which actually has an example:
![image](https://github.com/zed-industries/zed/assets/53836821/64898fe7-e1dd-4439-8b4e-db8b230a74a0)

**Comment by Iovans** [comment]
the example that you gave me dont work because is an experimental api and that reasonable, but in my case are not experimental, it should shows the code!

**Comment by bennetbo** [comment]
My point is, that there is no code in the rust doc itself, it's just empty. So Zed displays it correctly. Screenshot from rust doc (link I posted in the last message):
<img width="998" alt="image" src="https://github.com/zed-industries/zed/assets/53836821/0dd69855-42b5-4e30-8d89-666c353633f1">

**Comment by bennetbo** [comment]
Sorry, looks like I am the one that's confused here. For some reason I thought the rust doc itself is empty. Looks like there is something wrong with the rendering indeed.

**Comment by bennetbo** [comment]
Looks like this is an issue of the language server (rust-analyzer), see https://github.com/rust-lang/rust-analyzer/issues/7688

**Comment by Iovans** [comment]
okay thank you for tell me about it, they are fixing it right?

**Comment by maxdeviant** [comment]
Closing this, since we've identified it as an upstream issue.
