### ISSUE TITLE
Python language server download fails if ipv6 does not work and it's enabled

### ISSUE THREAD

**Issue by fuomag9** [zed-industries/zed#8349]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If an IPv6 address is assigned to the system, but the address is non-routed, there's no fallback to ipv4 and the python language server download will fail

```
Language server error: Python

failed to execute npm info subcommand:
stdout: "{\n  \"error\": {\n    \"code\": \"ENETUNREACH\",\n    \"summary\": \"request to https://registry.npmjs.org/pyright failed, reason: connect ENETUNREACH 2606:4700::6810:1d22:443\",\n    \"detail\": \"\"\n  }\n}\n"
stderr: "npm ERR! code ENETUNREACH\nnpm ERR! syscall connect\nnpm ERR! errno ENETUNREACH\nnpm ERR! request to https://registry.npmjs.org/pyright failed, reason: connect ENETUNREACH 2606:4700::6810:1d22:443\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/fuomag9/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-02-24T22_38_40_710Z-debug-0.log\n"
```

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @fuomag9, does this only affect the python language server download, or all language server downloads? I would image the latter, but double checking.

**Comment by fuomag9** [comment]
> Hey @fuomag9, does this only affect the python language server download, or all language server downloads? I would image the latter, but double checking.

Unfortunately I do not know to check for updates for other language servers, as it only seems to be checking for python :(
