### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by dheeraj-coding** [zed-industries/zed#8362]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

App crashes on start. Suspect the new commit #8306 is the root cause. Commits prior to that work fine on the same system.

### Environment

M1 Pro. MacOS Sonoma v14.2.1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Crash Report partial:
Process:               Zed [18979]
Path:                  /Users/USER/*/Zed
Identifier:            Zed
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [883]
Responsible:           iTerm2 [869]
User ID:               501

Date/Time:             2024-02-24 20:26:18.2687 -0800
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        9D045249-BBCC-0E00-1F4D-5E4D1AF45FD8

Time Awake Since Boot: 160 seconds

System Integrity Protection: enabled

Crashed Thread:        13  Dispatch queue: com.apple.root.user-initiated-qos

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000000016c32de90
Exception Codes:       0x0000000000000002, 0x000000016c32de90

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [18979]

VM Region Info: 0x16c32de90 is in 0x16c32c000-0x16c330000;  bytes after start: 7824  bytes before end: 8559
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                       16c2a4000-16c32c000    [  544K] rw-/rwx SM=PRV  thread 13
--->  Stack Guard                 16c32c000-16c330000    [   16K] ---/rwx SM=NUL  
      Stack                       16c330000-16c3b8000    [  544K] rw-/rwx SM=PRV  

Thread 0:: main Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x189971874 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x189983cf0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18997a4b0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x189971bf8 mach_msg + 24
4   CoreFoundation                	       0x189a8fbf4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x189a8e4bc __CFRunLoopRun + 1208
6   CoreFoundation                	       0x189a8d9ac CFRunLoopRunSpecific + 608

**Comment by dheeraj-coding** [comment]
[crashreport.txt](https://github.com/zed-industries/zed/files/14395249/crashreport.txt)
Full Crash report

**Comment by SomeoneToIgnore** [comment]
Thank you, reverted that commit for now and things work again.
