### ISSUE TITLE
projects::OpenRecent list is empty and flashing

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8364]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can clearly see that it had content at first, but then it was cleared.
https://github.com/zed-industries/zed/assets/45585937/c2fe6b33-a909-4d91-8581-f1a32f31af12

### Environment

Zed: v0.124.4 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
I fear this is another case of https://github.com/zed-industries/zed/pull/7528#issuecomment-1944568080 but that did not appear for me, I wonder if Vim mode has to do something with it.
cc @bennetbo

**Comment by bennetbo** [comment]
There was an oversight in the layout code I modified when there are a lot of projects in the list. Should be fixed with this. Would be great if @d1y could test this, although running from source will not use the same recent projects list as the one shown above.

By the way, what's the name of your theme? It looks great.

**Comment by d1y** [comment]
> lot of projects in the list fixed by #8376

I have opened many projects and this PR seems to be working @bennetbo 
But I think the rendering part of the list is now overflowing and not fully displayed, which makes me feel abrupt.
![image.png](https://s2.loli.net/2024/02/25/ytjnKgTWZoJOFa7.png)

> what's the name of your theme?

![image.png](https://s2.loli.net/2024/02/25/jd5anbDTQkZ4tYf.png)

**Comment by bennetbo** [comment]
> But I think the rendering part of the list is now overflowing and not fully displayed, which makes me feel abrupt.

What would you expect to happen if there are more projects in the list? Cutting them off seems like a bad idea cause it looks like they are missing.

Thanks for the theme name!

**Comment by d1y** [comment]
> > But I think the rendering part of the list is now overflowing and not fully displayed, which makes me feel abrupt.
> 
> What would you expect to happen if there are more projects in the list? Cutting them off seems like a bad idea cause it looks like they are missing.
> 
> Thanks for the theme name!

Rewrite to telescope-style lol :) <<https://github.com/zed-industries/zed/issues/8279>>

> refer: https://github.com/nvim-telescope/telescope-project.nvim/tree/master

![](https://raw.githubusercontent.com/nvim-telescope/telescope-project.nvim/master/demo.gif)

> In my impression, @iamnbutler  has developed a concept UI for extension-ui, which is very similar to telescope.

**Comment by d1y** [comment]
> > But I think the rendering part of the list is now overflowing and not fully displayed, which makes me feel abrupt.
> 
> What would you expect to happen if there are more projects in the list? Cutting them off seems like a bad idea cause it looks like they are missing.
> 
> Edit: Just making sure you can see the items when you scroll down/use the arrow keys to navigate, right?
> 
> Thanks for the theme name!

If possible, I think it is better not to display its path, or just put it on the right side. I think the hover tooltip is enough.

**Comment by bennetbo** [comment]
I tried to display the path on the right [earlier in my PR](https://github.com/zed-industries/zed/pull/7528#pullrequestreview-1869514924) but there is not enough space to render long paths and long project names side by side. Personally, I feel like the path should always be displayed, because there might be projects with the same name in different folders.

**Comment by SomeoneToIgnore** [comment]
In fact, there was an issue asking exactly that (showing the path always), so trimming seems reasonable atm.
