### ISSUE TITLE
Font antialiasing configuration support

### ISSUE THREAD

**Issue by DevNulPavel** [zed-industries/zed#8366]
### Feature

Hello

VSCode supports `Font Aliasing` feature.

I usually use `antialiased` mode for thin fonts on MacBook, which (on my opinion) is easy to look on.

**Setting in VSCode:**
<img width="382" alt="Screenshot 2024-02-25 at 09 11 40" src="https://github.com/zed-industries/zed/assets/14924622/1de7f6b4-90b0-4a91-b7b9-f1b93046f0b7">

**Default:**
<img width="593" alt="Screenshot 2024-02-25 at 09 14 07" src="https://github.com/zed-industries/zed/assets/14924622/a450c987-ea1d-4732-b33b-7e8c7fdcbe83">

**Antialiased:**
<img width="601" alt="Screenshot 2024-02-25 at 09 14 14" src="https://github.com/zed-industries/zed/assets/14924622/2d064218-ddc6-4077-b3fe-f42959926c9a">

**Comment by Moshyfawn** [comment]
Possibly related #8366

**Comment by jansol** [comment]
@Moshyfawn that's this issue. I'm guessing you meant #4334

**Comment by Moshyfawn** [comment]
Yup, my bad 🤦

**Comment by JosephTLyons** [comment]
Closing in favor of:

- https://github.com/zed-industries/zed/issues/4334
