### ISSUE TITLE
Abitility to Highlight certain comments

### ISSUE THREAD

**Issue by srihariash999** [zed-industries/zed#8367]
### Check for existing issues

- [X] Completed

### Describe the feature

I feel it will be very nice to have comment styles depending on the 'type' of the comment. 

For example, see this image: 
<img width="374" alt="image" src="https://github.com/zed-industries/zed/assets/30948010/2abdf330-3b07-40a9-8163-090e49a7d758">

I setup my workflow using TODO comments which I write down to map out the feature, then I resolve them one by one to completion.

The important and warning comments are quite helpful in documenting the code and the striking colors against a relatively plain theme will be attention grabbing when needed/intended.

I know this is a very niche or unimportant feature, but I feel like it can be considered, if it is not very complicated to implement.

**Comment by Moshyfawn** [comment]
Related #7874

**Comment by srihariash999** [comment]
I tried finding existing issues by comments, highlight, todo keywords, somehow did not hit on #7874. 

Please let me know if this would be better just as a comment on that issue rather than its own one, since this only extends the OG one by a bit. Happy to close this and add a comment on the other one.

**Comment by JosephTLyons** [comment]
Hey @srihariash999, let's close this one out, since the other issue has a good amount of upvotes on it already. You can add a comment on that issue to add in the extra details you have here.
