### ISSUE TITLE
Improving Theme Switching Performance in Zed

### ISSUE THREAD

**Issue by balaji-sivasakthi** [zed-industries/zed#8371]
### Check for existing issues

- [X] Completed

## Issue Description:
I recently switched themes in Zed, and I noticed that there's a slight lag when using the combo box to switch between different themes. Specifically, when I try to switch themes using the up and arrow keys, there's a noticeable delay in the transition. This lag detracts from the overall user experience and could be frustrating for users who frequently change themes.

## Steps to Reproduce:
1. Open zed.
2. Navigate to the theme selection combo box.
3. Use the up and arrow keys to cycle through different themes.
4. Notice the delay/lag in the transition between themes.

## Expected Behavior:
Theme switching should be smooth and responsive, with no noticeable delay when using the up and arrow keys to cycle through themes.

## Actual Behavior:
There is a slight lag when using the up and arrow keys to switch between themes, which affects the overall responsiveness of the application.

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
@balaji-sivasakthi Are you able to provide more details? Being able to see it in a video would be helpful.

Testing it out locally, I am not able to notice any perceptible delay when switching between themes.

Also, the version of Zed you're using is a bit outdated at this point. Are you able to reproduce on the latest version of Zed?

**Comment by balaji-sivasakthi** [comment]
@maxdeviant Thank you, The latest version is working well.
