### ISSUE TITLE
Catppuccin OOTB support

### ISSUE THREAD

**Issue by fschlegelone** [zed-industries/zed#8378]
Catppuccin should be the most popular Theme in the Coding community as far as I know, nevertheless its not coming with Zed out of the box. 
The Catppuccin Team is already working (maybe even finished) a Theme for Zed & I'm sure they're open to collaborate. 

![image](https://github.com/zed-industries/zed/assets/118682177/85b2023d-4bef-4e5b-a31b-07d54220b8d1)

**Comment by bennetbo** [comment]
Not sure if you are aware, but you can install the catppuccin theme using the extensions panel (command palette -> zed: extensions).
Repo: https://github.com/catppuccin/zed

**Comment by fschlegelone** [comment]
@bennetbo I know, I have the extension theme installed, but imo it would make sense to add it to the themes that come with Zed, since its so popular.

**Comment by maxdeviant** [comment]
We're not looking to add any more built-in themes to Zed at the moment.

We may revisit in the future, but for now we're letting the state of themes evolve via the extension system.
