### ISSUE TITLE
Tree Sitter queries documentation

### ISSUE THREAD

**Issue by postsolar** [zed-industries/zed#8379]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello, I'd like to improve queries for a particular language, but I couldn't find any documentation for the queries used by Zed.
Specifically I'm interested in
- Which captures are used for highlights
- Differences (if any) from TS query language

**Comment by SomeoneToIgnore** [comment]
Zed uses tree-sitter queries for everything including highlights, you can check out `${LANGUAGE_NAME}/highlights.scm` for examples, e.g. TypeScript ones: https://github.com/zed-industries/zed/blob/934af6ad451684fa2659fc0f9fb943e02c5b3572/crates/languages/src/typescript/highlights.scm

Not sure what "TS query language" is so not sure I can answer that part.

**Comment by postsolar** [comment]
@SomeoneToIgnore
Examples are indeed helpful but I wondered if there are precise (to the extent possible) mappings between language concepts and capture groups. Good examples of such mappings are [Helix documentation](https://docs.helix-editor.com/themes.html#syntax-highlighting) or [Neovim Tree-sitter documentation](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights). Note that both lists are exhaustive and leave no doubts as to what is available.

By "TS query language" I meant the set of S-expressions used by Zed queries. These can be different across various editors. Here's an example of [incompatibility](https://github.com/nvim-treesitter/nvim-treesitter/pull/5626#discussion_r1382373242) between what's accepted in Helix and what's accepted in Neovim.

**Comment by SomeoneToIgnore** [comment]
Ok, in that case I would rather ask @maxbrunsfeld for clarifications.

From my amateur point of view, there's no strict mappings defined for any of the languages, but I might be very wrong.

**Comment by frou** [comment]
> Zed uses tree-sitter queries for everything including highlights, you can check out `${LANGUAGE_NAME}/highlights.scm` for examples, e.g. TypeScript ones: https://github.com/zed-industries/zed/blob/934af6ad451684fa2659fc0f9fb943e02c5b3572/crates/languages/src/typescript/highlights.scm

From a user perspective, what's the workflow for iterating on such a **highlights.scm** file? Can it be placed somewhere special in the filesystem and Zed will pick up changes to it (possibly after an app restart)?

**Comment by notpeter** [comment]
This was done as part of the Docs Party this summer:
- https://github.com/zed-industries/zed/pull/15876

[Language Extensions: Tree-Sitter Queries](https://zed.dev/docs/extensions/languages#tree-sitter-queries) in the Docs.
