### ISSUE TITLE
GPT Model selection not remembered (Assistant Panel)

### ISSUE THREAD

**Issue by fschlegelone** [zed-industries/zed#8381]
### Check for existing issues

- [X] Completed

### Description

On every Zed startup, the GPT-Model ﻿selectable in Assistant Panel resets back to GPT4-Turbo and does not remember the user selection. That could lead to users spending more money on accident.
Can be fixed by allowing users to set a default option in the Zed config or remembering the last choice.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### Screenshot

![CleanShot 2024-02-25 at 14 22 15@2x](https://github.com/zed-industries/zed/assets/118682177/c2a5770a-fdba-4184-a6cc-dfd52403be55)

**Comment by TerminalFi** [comment]
Is the settings not working for you?

```json

  "assistant": {
    "default_open_ai_model": "gpt-4-1106-preview"
  },
  ```
