### ISSUE TITLE
Missing hover documentation for some settings keys

### ISSUE THREAD

**Issue by fschlegelone** [zed-industries/zed#8383]
### Check for existing issues

- [X] Completed

### Description

In the Zed settings.json, some property information is displayed when hovering over it, but many are missing. **Just as an example**:
Hovering over the setting "font_size" => **shows information**
Hovering over the setting "font_family" => **doesn't show information**. 

This problem runs through more than just the settings.json, its a general problem, for typescript, javascript, ... files as well.

### As you can see "shell" or "font_size" is supported, but most settings aren't
![CleanShot 2024-02-25 at 14 44 55@2x](https://github.com/zed-industries/zed/assets/118682177/7913bcd4-0b8d-4875-baa4-e8c53abb91d2)

**Comment by ForLoveOfCats** [comment]
It looks like some set of our settings fields are missing doc comments, thanks for spotting this
