### ISSUE TITLE
Pretty TypeScript Errors

### ISSUE THREAD

**Issue by fschlegelone** [zed-industries/zed#8385]
### Check for existing issues

- [X] Completed

### Describe the feature

We all know that TypeScript errors are extremely hard to read. VSC & Zed couldn't address this issue yet, but for VSC there's an amazing extension called "Pretty TypeScript Errors" that solves this problem. 
My Feature Request is to have a look at this extension, learn from it and figure out how you can improve TypeScript errors in Zed.
Maybe even collaborate with @yoavbls .

### If applicable, add mockups / screenshots to help present your vision of the feature

VSC Extension Repo
https://github.com/yoavbls/pretty-ts-errors

**Comment by zisra** [comment]
Duplicate #7844

**Comment by yoavbls** [comment]
@fschlegelone Thank you for tagging me in this issue, I will comment on #7844
