### ISSUE TITLE
completion box height incorrect

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#8389]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```rs
"".to_string().mak
```

Zed: there are only 4 lines, but the box seems be 8 lines height.

<img width="670" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/9efb8025-446b-40a0-bb4b-191d1a2bcfaa">

VSCode:

<img width="661" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/711a6140-c6a0-4e6f-9a8c-5d705b1cdfe3">

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by danielzsh** [comment]
Isn't this because of the long function documentation on the right?
<img width="1086" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/15d8b97f-de33-498f-a643-0ebe0c0e5235">
