### ISSUE TITLE
Renaming Bug

### ISSUE THREAD

**Issue by Ravinder74599** [zed-industries/zed#8402]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If we are renaming a file/ Folder from capital case to lower case it reverts to same file 
exp. Fronted(Current Name of Folder) -> fronted(Renamed to) -> Frontend(Reverts Back to Same)
Vice versa.

### Environment

I am using Macbook Air M2

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by imsk17** [comment]
I Would like to work on this

**Comment by Imgkl** [comment]
@imsk17, give it a try and raise a PR. 🙌🏼

**Comment by Imgkl** [comment]
For anyone who is willing to pick this up.

Steps to recreate

- Rename a file.
- if you press enter, the changes applies. If you click anywhere on the window, the name reverts back to the original name.

**Comment by JosephTLyons** [comment]
Hey @Ravinder74599, this has already been fixed via:

- https://github.com/zed-industries/zed/pull/7835

But the change hasn't made its way into the stable channel yet. It should be on stable tomorrow, in v0.124.
