### ISSUE TITLE
clang-format on C code remove existent code

### ISSUE THREAD

**Issue by Warkanlock** [zed-industries/zed#8410]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After setting a language configuration for C code in `languages` my code, after being saved, is replaced with the latest N-1 step previously done on the editor.

For example:
1. I added a summary comment before a `struct` definition.
2. _ctrl + s_
3. I added a `struct,` together with a summary comment.
4. _ctrl + s_
5. my code disappears, and it keeps showing the previous step (0)

This is the configuration used (utilizing `clang-format` as default):
```json
[{
    "C": {
      "formatter": {
        "external": {
          "command": "clang-format",
          "arguments": ["{buffer_path}"]
        }
      },
      "format_on_save": "on"
}] 
```

Turning `format_on_save` to `off` solves the issue, but I need to manually `save > format` workflow.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

With ``format_on_save: on``

https://github.com/zed-industries/zed/assets/145113/0d044fd9-33ab-4019-8d24-57d2c3e683de

With ``format_on_save: off``

https://github.com/zed-industries/zed/assets/145113/0c5509e3-6f41-490f-b98d-6c81b30e8608

**Comment by notpeter** [comment]
@Warkanlock I can't reproduce this. I did observe some similar behavior around the time of this report where `format_on_save` was losing my file content, but haven't seen it in a few months.

Can you see if you are still experiencing thing scary behavior?

**Comment by Warkanlock** [comment]
> @Warkanlock I can't reproduce this. I did observe some similar behavior around the time of this report where `format_on_save` was losing my file content, but haven't seen it in a few months.
> 
> Can you see if you are still experiencing thing scary behavior?

Might it be solved on the latest versions of Zed? I've not used Zed anymore for C programming, given this issue, so I cannot confirm nor deny that this keeps happening

**Comment by 0xVitea** [comment]
@notpeter I think this problem still persists.
This is my config:
```
{
  "telemetry": {
    "diagnostics": true,
    "metrics": false
  },
  "theme": "Kanagawa Wave",
  "vim_mode": true,
  "ui_font_size": 16,
  "font_family": "Fira Mono",
  "buffer_font_family": "Fira Mono",
  "buffer_font_size": 16,
  "autosave": "on_focus_change",
  "relative_line_numbers": true,
  "project_panel": {
    "dock": "right",
    "git_status": true
  },
  "terminal": {
    "font_family": "Fira Mono",
    "blinking": "on"
  },
  "preferred_line_length": 180,
  "languages": {
    "C++": {
      "tab_size": 4,
      "formatter": {
        "external": {
          "command": "clang-format",
          "arguments": ["{buffer_path}"]
        }
      },
      "format_on_save": "on"
    }
  }
}
```

MacBook M1 - macOS Sonoma 14.5 - Zed 0.143.7

Whenever I delete any line and press escape to `:w`, the code just reappears. 

https://github.com/user-attachments/assets/637b7aba-39eb-40d1-ac5a-129bd2fb385e

**Comment by Warkanlock** [comment]
I went back to my configuration file after reading this thread since I opened a long time ago, and something that fixed the issue for me was to disable the `format_on_save` 

```
    ...
    "C": {
      "show_copilot_suggestions": true,
      "formatter": {
        "external": {
          "command": "clang-format",
          "arguments": ["{buffer_path}"]
        }
      },
      "format_on_save": "off"
    }
    ...
```

Using this configuration chunk now essentially I can use Zed as part of the workflow; however, I need to run the `format` command every time I wanna use `clang-format` (which is not a big deal, honestly)

**Comment by 0xVitea** [comment]
Thanks for quick response.

Disabling `format_on_save` worked for me. I've also added a quick keymap for this one.

I agree it's not a priority, rather a good feature to have. It would be great if you could add a message or a quick note about `clang-format` in documentation.

Thank you once again for what you're doing. Switched fully to zed and enjoy it on a daily basis !

**Comment by konstantintutsch** [comment]
This issue might not be related to only `clang-format`. It also occurs when using GNU Indent as the external formatter for C.

### Configuration

Here is a snippet of my Zed configuration.
```json
"languages": {
    "C": {
        "formatter": {
            "external": {
                "command": "indent",
                "arguments": [ "{buffer_path}", "-linux", "-nut", "-i4", "-o", "/dev/stdout" ]
            }
        }
    }
}
```

A short summary of the arguments:
- `-linux`: same styling as code in the Linux kernel
- `-nut` and `-i4`: indentation with 4 spaces
- `-o /dev/stdout`: output to stdout

### Enviroment

Zed: 0.143.6 (via DNF, Terra)
OS: Fedora 40 with Linux 6.9.8
Memory: 32GB
Architecture: x86_64 (AMD)

**Comment by konstantintutsch** [comment]
I've read the Zed documentation again. Using `{buffer_path}` is not intended, instead stdin should be used.

![Bildschirmfoto vom 2024-07-18 10-11-33](https://github.com/user-attachments/assets/7514d084-9e43-42c6-9682-bbbffa644e27)

```
"languages": {
    "C": {
        "formatter": {
            "external": {
                "command": "indent",
                "arguments": [ "-", "-linux", "-nut", "-i4", "-o", "/dev/stdout" ]
            }
        }
    }
}
```
Replacing `{buffer_path}` with `-` fixes the issue with `format_on_save`.

**Comment by konstantintutsch** [comment]
Using `/dev/stdin` instead of `-` doesn't work. (#14716)

**Comment by siboehm** [comment]
This works for clang-format:
```
  "languages": {
    "C": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "bash",
          "arguments": ["-c", "clang-format"]
        }
      }
    }
  },

```

**Comment by bigbrett** [comment]
New to Zed, so apologies if this is dumb, but I cannot for the life of me seem to get clang-format working in Zed. I must be missing something. I've tried @siboehm solution, as well as a few others, yet it never seems to work. If I highlight a chunk of text and choose "format selection" or "format buffer", nothing happens. Every other IDE (Vscode, eclipse, etc), vim, and others all have no problems invoking clang-format. Any suggestions? This is on Ubuntu if it matters.

**Comment by notpeter** [comment]
@bigbrett This is a specific issue where clang-format is working but is not including the most recent changes.  You should look at the [Zed C++ Language Docs](https://zed.dev/docs/languages/cpp) and your Zed logs and file a distinct issue if you are having trouble getting `clang-format` to work at all.

**Comment by notpeter** [comment]
After looking at this, I think I understand the confusion here.

From the [Zed Formatter Docs](https://zed.dev/docs/configuring-zed#formatter)
<img width="804" alt="Screenshot 2024-11-12 at 14 28 10" src="https://github.com/user-attachments/assets/9eea408f-1428-40fc-90e9-0fa6f08edee7">

Zed does not supporting calling a external formatters which can only read/write from files, the formatter must be able to read from stdin and write to stdout.  The formatter should not use `{buffer_path}` for reading input -- only as an optional hint like [`prettier --stdin-filepath`](https://prettier.io/docs/en/options.html#file-path) uses it.

The "loosing" of recent changes is occurring with `format_on_save` because Zed has not saved your changes to the buffer and clang-format is operating on the previously save file.  There are no arguments required to get clang-format to operate in the stdin/stdout mode Zed expects.

For example:
```sh
echo -e '#include <stdio.h>\nint main() {printf("Hello, World!");return 0;}' | clang-format
```
Yields
```c
#include <stdio.h>
int main() {
  printf("Hello, World!");
  return 0;
}
```

So the original posters Zed configuration (wrong):
```json
    "C": {
      "formatter": {
        "external": {
          "command": "clang-format",
          "arguments": ["{buffer_path}"]
        }
      },
      "format_on_save": "on"
    }
```

Can be made to work with this:
```json
  "languages": {
    "C": {
      "formatter": {
        "external": {
          "command": "clang-format"
        }
      },
      "format_on_save": "on"
    }
  }
```

But ultimately in most environments this would be redundant, because by default Zed uses the language server for formatting (`clangd`) for C/C++.  And clangd embeds clang-format.

I'm going to update the docs to reflect this.
