### ISSUE TITLE
Show files with errors in different colour

### ISSUE THREAD

**Issue by ThomasAlban** [zed-industries/zed#8412]
It would be nice if files in the file explorer would be shown in a different colour (e.g. red) if they have errors in them, similar to VSCode - this makes it easier to see where errors are in your project. It should be possible to turn it off for those that don't want it though!

**Comment by jansol** [comment]
#5016

**Comment by mattrltrent** [comment]
"Not planned"...? This may be the sole reason I continue to use VS Code then. Shoot!

**Comment by jansol** [comment]
> "Not planned"...? This may be the sole reason I continue to use VS Code then. Shoot!

Github unfortunately does not have a way to explicitly close issues as duplicates, which this is.
