### ISSUE TITLE
vim read-only can modify

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#8423]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/19868292/3e98ed1d-c108-436c-b4c6-8c4f01aa5f45

### Environment

Zed: v0.124.4 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This is now included in [v0.125.0-pre](https://zed.dev/releases/preview/0.125.0).

**Comment by 0x2CA** [comment]
@ConradIrwin  The new feature ysiw' breaks it!

**Comment by 0x2CA** [comment]
@ConradIrwin  

A lot of features break it now

`vim-surround` 
 `vim-commentary` 
 `vim::ToggleReplace` 
`Convert to XXX`

**Comment by ConradIrwin** [comment]
Hmm. I think we need to put the check in a better place. Want to take a pass at this? Otherwise I will in a bit.

I'm also OK to just add checks for the missing ones.

**Comment by 0x2CA** [comment]
> Hmm. I think we need to put the check in a better place. Want to take a pass at this? Otherwise I will in a bit.
> 
> I'm also OK to just add checks for the missing ones.

I support putting inspections in a better position, otherwise these problems will be endless and will keep recurring.
