### ISSUE TITLE
The elevated surface border is missing.

### ISSUE THREAD

**Issue by Imgkl** [zed-industries/zed#8424]
Looks like `elevated_surface.background`'s description is wrong. It's not border, it's background.

<img width="846" alt="image" src="https://github.com/zed-industries/extensions/assets/25414681/0b8a3ced-008c-4f07-b349-15dff504659a">

Also the key to configure elevated surface's border is missing.

**Comment by vfilter** [comment]
It would be great to have this as with darker themes, a more accentuated contrast would be much easier on the eyes
