### ISSUE TITLE
Vim Mode: use `gd` to jump to caller

### ISSUE THREAD

**Issue by hamza72x** [zed-industries/zed#8427]
### Check for existing issues

- [X] Completed

### Describe the feature

Hey!

Thanks for the project. I have almost switched to Zed for some of my workflow (Go + Rust).
I have a small feature request is that:

If I do `gd` on `function name`, it should open`caller` of the function, if there is only one caller of the function.
If there are more than one caller of that function, then it can open `Find All Occurrences`, even though we already have `gA` for that.

This feels very fast way to navigate. I am not sure if there is already a key-binding for such action.

Attaching a screencast (VSCode + Vim Plugin):

https://github.com/zed-industries/zed/assets/48919542/7d9e7bb4-83e8-41d5-a9bb-58275ee36ec2

Similarly, it can/may also work with `struct / class / variable`

Thanks again.

**Comment by mrnugget** [comment]
We already have a PR for that (except the Vim binding): https://github.com/zed-industries/zed/pull/6924 But it seems a bit stale.

**Comment by hamza72x** [comment]
Didn't see that, closing then. Thanks.

**Comment by hamza72x** [comment]
That PR is not related to VIM mode, so re-opening this one. But I think that should also solve this one.
Keeping this open, so that we can validate with Vim mode and close later, if that makes sense.

**Comment by mrnugget** [comment]
Yeah, I think the scope for this one would be to add a vim keybinding if that's not done in the original PR.

**Comment by hamza72x** [comment]
@jansol sorry, the title was slightly misleading. It's about opening the caller of the function/class/variable.

**Comment by vricop** [comment]
`gd` isn't for going to caller if I'm not mistaken, stands for Go To Definition, as `gr` i for Go To Reference.

**Comment by hamza72x** [comment]
@vricop I was referring to VSCode+Vim Extension's default behaviour.

**Comment by vricop** [comment]
> @vricop I was referring to VSCode+Vim Extension's default behaviour.

That’s weird the VSCode-neovim plugin does the same neovim does. Maybe it’s a vanilla vim thing. It doesn’t make sense imho thought.

**Comment by hamza72x** [comment]
Tested with latest `Zed Preview`, working with custom keybindings.
By default it's mapped to `gA` -> [Reference](https://zed.dev/docs/vim)

```json
[
    {
        "context": "Editor && vim_mode == normal && !VimWaiting && !menu",
        "bindings": {
            "g d": "editor::FindAllReferences"
        }
    }
]
```
