### ISSUE TITLE
Scrolling gets stuck when scrolling over large blocks of duplicated Rust code

### ISSUE THREAD

**Issue by mrnugget** [zed-industries/zed#8434]
Sorry for the hyper-specific issue title, but I don't know what the exact circumstances are in which it replicates.

Steps to reproduce:

1. Open Rust file
2. Create a line that says `let foo = HashMap::new()`
3. Copy & paste that line 50-100 times
4. Hold down <kbd>up</kbd>, <kbd>down</kbd> pressed to scroll over it

What happens: Zed seems to get stuck when scrolling over these lines

What I expected to happen: it scrolls smoothly

Video:

https://github.com/zed-industries/zed/assets/1185253/001df6f0-42ee-470c-838b-b0c2be60e51d

Ignore the details on the right, those are just printed to show that scroll events are being sent when holding downt he key.

**Comment by alygin** [comment]
Can't reproduce this one. Does this problem still exist after recent optimizations?

**Comment by mrnugget** [comment]
No, I don't think so. Let's close it!
