### ISSUE TITLE
Image viewer within Zed

### ISSUE THREAD

**Issue by GeoffNN** [zed-industries/zed#8435]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to view images directly within Zed. I use Zed fullscreen, so I currently need to leave zed, and use another tool (finder, vscode...) to view images. My use case is logging image plots that my code creates.

**Comment by emersonjds** [comment]
@GeoffNN it's very usefull !!!

**Comment by jansol** [comment]
Yet another victim of #5251 :wink:

**Comment by JosephTLyons** [comment]
Yep, let's close this out in favor of #5251
