### ISSUE TITLE
Python venv should be set up using std::env and not by inputing bytes to the terminal

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/zed#8440]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, python venv is set up by sending the command to the terminal on startup. It prevents the tasks from working properly in the projects with venv-s (see #8334) and is not cross shell compatible. The venv/bin/activate script does not do much, in fact, it can be quickly reproduced using Rust to set environment variables, like done in
https://github.com/zed-industries/zed/blob/b907ad769ab0a3e1715596328519c67040df1ac0/crates/terminal/src/terminal.rs#L343-L344

This would allow for better python support across multiple other shells while allowing #8334 to work properly.

**Comment by Arpit3150** [comment]
hi

**Comment by WeetHet** [comment]
Hmm, I don't remember why I didn't close this one, it seems to be long resolved
