### ISSUE TITLE
Ability to add custom commands in command palette through extensions

### ISSUE THREAD

**Issue by Imgkl** [zed-industries/zed#8441]
### Check for existing issues

- [X] Completed

### Describe the feature

As the title suggests, expanding zed's capability through extensions seems like a good idea. Users should be able to install extensions which adds custom commands to the command palette. 

Since this idea has dependency on both extension repo and this repo, I'm filing a feature request here.

**Comment by eliasrenman** [comment]
This was closed without any reference to if it was actually implemented or not. I have a usecase similar to #12876 and i'm curious if this is something that's documented anywhere so I can start building my extension.

**Comment by mrexodia** [comment]
Another related issue: #18043

**Comment by brandonzylstra** [comment]
@eliasrenman as far as I can tell this is not possible and there are no immediate plans to make it possible.  In conversation with someone close to the Zed team, I was told

> No, sorry. This is a challenging task since extensions run in the WASM env in Zed. Tying WASM in with GPUI integration is going to be no small feat, and the Zed team hasn’t yet done any exploration on it, AFAIK.

This is very disappointing, of course.
