### ISSUE TITLE
Keymap issues conflicting with typing text

### ISSUE THREAD

**Issue by jeffplays2005** [zed-industries/zed#8454]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If the keymap for the ProjectPanel bindings for `project_panel::NewFile` is changed to `a`(similarly to Atom), you are unable to type the character "a" while creating a new file as the text editor assumes that you are wanting to create another new file. 

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="625" alt="Screenshot 2024-02-27 at 11 26 33 AM" src="https://github.com/zed-industries/zed/assets/61447509/f4fdc0c5-cbeb-413f-a727-5095fd9ae7a8">
<img width="176" alt="Screenshot 2024-02-27 at 11 26 50 AM" src="https://github.com/zed-industries/zed/assets/61447509/ee39535f-ec0b-4add-b4c4-083c4b62fa10">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by 0x2CA** [comment]
you need "ProjectPanel && not_editing"

**Comment by JosephTLyons** [comment]
@jeffplays2005, does @0x2CA's suggestion work for you?

**Comment by jeffplays2005** [comment]
Yes, that worked. Thank you so much!
<img width="124" alt="Screenshot 2024-02-29 at 4 46 18 PM" src="https://github.com/zed-industries/zed/assets/61447509/afe2c44a-57ff-46d3-8804-a481e55e10bf">
