### ISSUE TITLE
Go forward command description should be `Control` + `Shift` + `-` instead of `Control` + `_` 

### ISSUE THREAD

**Issue by jianghoy** [zed-industries/zed#8459]
### Check for existing issues

- [X] Completed

### Describe the feature

Today go forward icon tooltip in editor and key binding in configuring_zed_key_bindings.md is `Control` + `_`. It's hard to tell the difference between `_` and `-` especially in the editor tooltip.
**Suggested changes**:
* [ ] in configuring_zed_key_bindings.md, the descriptions should be changed to `Control` + `Shift` + `-`;
* [ ] For the tooltip it should be `^⇧-` instead of `^_`

**Comment by notpeter** [comment]
Sadly I had to revert this
- https://github.com/zed-industries/zed/issues/14418
- https://github.com/zed-industries/zed/pull/14570
