### ISSUE TITLE
`zed .` fails

### ISSUE THREAD

**Issue by sj26** [zed-industries/zed#8465]
### Check for existing issues

- [X] Completed

### Describe the feature

I often open an editor in the current directory. That doesn't seem to work for me using macOS  14.1 (23B2073) and Zed 0.123.6:

```
$ zed .
Error: path "." canonicalization

Caused by:
    No such file or directory (os error 2)
```

but PWD works:

```
$ zed $PWD
```

Could the CLI expand the path supplied?

Or have I hit something that _should_ work?

**Comment by sj26** [comment]
Never mind, I think I was using it within a directory that was gone 😅

**Comment by mckennajones** [comment]
@sj26 just out of curiosity, have you set up some alias in your shell config to get the `zed` command working? I installed zed via the release dmg, but I don't seem to have a `zed` command in my path.

**Comment by sj26** [comment]
No, I just installed it during first time setup when prompted and it has worked since.

```
$ which zed
/usr/local/bin/zed
```

**Comment by bennetbo** [comment]
> @sj26 just out of curiosity, have you set up some alias in your shell config to get the `zed` command working? I installed zed via the release dmg, but I don't seem to have a `zed` command in my path.

@mckennajones You should be able to install the CLI in the menu bar under Zed > Install CLI

**Comment by mckennajones** [comment]
Ty @bennetbo! Completely missed that.
