### ISSUE TITLE
Accept Next Word Of Inline Suggestion

### ISSUE THREAD

**Issue by sirenkovladd** [zed-industries/zed#8467]
### Check for existing issues

- [X] Completed

### Describe the feature

> used to accept the next word/non-word segment of the current inline suggestion

vscode: editor.action.inlineSuggest.acceptNextWord

### If applicable, add mockups / screenshots to help present your vision of the feature

https://code.visualstudio.com/updates/v1_74#_command-to-partially-accept-inline-completions

**Comment by Imgkl** [comment]
Possible duplicate of #8020 ?

**Comment by sirenkovladd** [comment]
Really looks like that
