### ISSUE TITLE
:w

### ISSUE THREAD

**Issue by noritada** [zed-industries/zed#8477]

**Comment by noritada** [comment]
There was a time when I was writing code in Zed and Zed was not responding. At that time I seemed to have unintentionally filed an issue.

**Comment by noritada** [comment]
There was a time when I was writing code in Zed and Zed was not responding. At that time I seemed to have unintentionally filed an issue.

**Comment by noritada** [comment]
There was a time when I was writing code in Zed and Zed was not responding. At that time I seemed to have unintentionally filed an issue.

**Comment by mrnugget** [comment]
We've reached the next level: instead of Vim folks leaving `:w` in files, we now have GitHub issues 🙂 ❤️
