### ISSUE TITLE
rust-analyzer bug in modules

### ISSUE THREAD

**Issue by JohnKesko** [zed-industries/zed#8478]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm quite new to Rust so bare with me.

When using a lib.rs and declaring a public module inside lib.rs, I have a few macros. For example:

`    
#[macro_export]
    macro_rules! info {
        ($($arg:tt)*) => {{
            $crate::logger::log($crate::logger::LogLevel::Info, format!($($arg)*));
        }};
    }
`
    
The log function and macros lives inside the same module. 

However, the macro info! is calling the log function but if the log function is not using the 'pub' keyword, the rust-analyzer complains about "dead code" so it wont compile. See screenshot. If I add the 'pub' keyword, it's fine.

Is this expected behaviour or just me being a newb?

### Environment

M1 - Sonoma 14.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

With 'pub' keyword:
![pub](https://github.com/zed-industries/zed/assets/87022265/ce162caa-2844-4b67-bd71-62463439433f)

No 'pub' keyword:
![no  pub](https://github.com/zed-industries/zed/assets/87022265/47c5ad92-bf4f-4e38-87f9-1bf24c1916cc)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment]
Are you saying that this is a Zed issue or is it a rust-analyzer issue? If it's the latter, I think an issue opened in the rust-analyzer repository might make more sense :)

**Comment by maxdeviant** [comment]
This doesn't seem like a Zed issue.
