### ISSUE TITLE
File finder selected item flickers when rust-analyzer is running

### ISSUE THREAD

**Issue by StevenWong12** [zed-industries/zed#8479]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It is hard to select a file in the file finder when rust-analyzer is running, since the selected Item flickers. Please refer to the video I attached.

It is easy to reproduce when open zed and use cmd+p to select a file.

https://github.com/zed-industries/zed/assets/56827396/8d70873a-05a7-4a92-935b-6710415686f6

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.1.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
This is tracked in https://github.com/zed-industries/zed/issues/7519 and being fixed in https://github.com/zed-industries/zed/pull/8343 so hopefully will go away soon.
Closing this as a duplicate.
