### ISSUE TITLE
Dart Autoformatting Issue with Semicolons in Code `;` 

### ISSUE THREAD

**Issue by steevedevops** [zed-industries/zed#8483]
### Check for existing issues

- [X] Completed

### Describe the feature

Dart formatting is encountering an unexpected behavior where adding a semicolon`;` at the end of a line of code triggers an automatic reformatting of the entire code block. 
This issue disrupts the intended formatting and layout, leading to inconsistencies and potential errors in the code. 
It's also important to note that we have already attempted to disable autoformatting in the editor, but the problem persists.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/25157485/0a9fbaad-8750-4afd-9589-6c91bac50ff2)
![image](https://github.com/zed-industries/zed/assets/25157485/f2dc16ae-74f6-49e0-b589-fa7f964922a5)

**Comment by flo80** [comment]
I guess this behavior is triggered by "On Type Formatting" of the Dart LSP. 

Try adding the following setting to deactivate this: 
```
{
    "use_on_type_format": false 
}
```

PS: to avoid this more generally in Dart / Flutter, try [using trailing commas](https://docs.flutter.dev/tools/formatting#using-trailing-commas)

**Comment by steevedevops** [comment]
> I guess this behavior is triggered by "On Type Formatting" of the Dart LSP.
> 
> Try adding the following setting to deactivate this:
> 
> ```
> {
>     "use_on_type_format": false 
> }
> ```
> 
> PS: to avoid this more generally in Dart / Flutter, try [using trailing commas](https://docs.flutter.dev/tools/formatting#using-trailing-commas)

Thankyou @flo80 it work nice now

**Comment by saifulapm** [comment]
@steevedevops Can you share your dart configuration for zed please ?
