### ISSUE TITLE
Linux: movement by word uses unexpected keys

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#8489]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed on Linux moves the cursor by a word when pressing alt+arrows. In other applications, e.g. Firefox, this moves to the next/previous tab instead. Movement by word is usually bound to ctrl+arrow.

### Environment

Zed 0.125-pre (7cbdea2c)
Ubuntu 24.04
GNOME Wayland

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by apricotbucket28** [comment]
This was fixed by https://github.com/zed-industries/zed/pull/9673, didn't notice this issue when I made that.
