### ISSUE TITLE
Linux: command palette shortcut gets overridden by editor::SelectUp

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#8491]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a random file in Zed and try to open the command palette with ctrl-shift-up. Zed instead selects moves the cursor cursor up by a line and selects the text it moved over. The only way to open the command palette is to click on the project explorer to move focus away from the editor and then press the shortcut.

### Environment

Zed 0.125-pre (7cbdea2c)
Ubuntu 24.04
GNOME Wayland

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mikayla-maki** [comment]
I don't think ctrl-shift-up is the binding we use for the command palette, are you using a custom keymap?

**Comment by jansol** [comment]
Ah, looks like I somehow messed that one up. The binding in question was of course ctrl+shift+p which *used* to be bound to editor::SelectUp, mirroring ctrl+p of editor::MoveUp (emacs things I guess?).

Anyway this is no longer the case.
