### ISSUE TITLE
File switcher arrows are moving

### ISSUE THREAD

**Issue by jbergstroem** [zed-industries/zed#8495]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/176984/843dc552-2eaa-45cb-a4a5-10a72b289f55

The file switcher arrows seems to be growing/shrinking in size based on state. Found while doing searches (where they kept toggling even without moving the cursor)

### Environment

Zed: v0.124.6 (Zed Preview)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bennetbo** [comment]
Looks like a duplicate of #8050

**Comment by jbergstroem** [comment]
Yep. Thanks for that. Lots of different terminology for it making it hard to search for.
