### ISSUE TITLE
Makefile syntax highlighting doesn't work (Extension already installed)

### ISSUE THREAD

**Issue by larrysammii** [zed-industries/zed#8518]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi all,

I have already installed the extension for makefile and it seems that the syntax highlighting still doesn't work.
I've already restarted Zed, rebooted, etc.
Is there anyone experiencing the same issue?

Screenshot:
<img width="373" alt="Screenshot 2024-02-28 at 3 19 47 PM" src="https://github.com/zed-industries/zed/assets/133651590/f6421429-523c-449f-b73d-9447fed3de21">

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Syntax highlighting in the Makefile extension is not yet implemented according to [this PR](https://github.com/zed-industries/extensions/pull/231).

I would suggest moving this issue to the [`zed-make`](https://github.com/caius/zed-make) repository as Zed has no control over 3rd party extensions.

**Comment by JosephTLyons** [comment]
I agree with @Moshyfawn, since this is related to an extension, this issue should probably be opened up over at that repo. Going to close this issue here.
