### ISSUE TITLE
Extension suggestions

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#8520]
### Check for existing issues

- [X] Completed

### Describe the feature

1) As you can see below in the images, you cannot see if a theme is installed or not, there is no difference, you have to go and read the writing, sometimes you don't even notice it.

It would be better if they were separated.

For example, those installed are displayed in a separate tab and not shown with those not installed.

So two tabs, one for those already installed, in case of uninstallation it will be removed from the following tab and the non-installed tab will be updated, also showing the one just removed.

2) Show the date of the last theme update

3) Filter by latest update, number of downloads

Install:

<img width="1181" alt="Screenshot 2024-02-28 alle 09 35 37" src="https://github.com/zed-industries/zed/assets/20476002/3f615d6a-a307-4030-a538-5edd33169991">

Unistall:

<img width="1180" alt="Screenshot 2024-02-28 alle 09 37 51" src="https://github.com/zed-industries/zed/assets/20476002/4556da4f-191f-44d3-9893-1c2f47801f36">

**Comment by JosephTLyons** [comment]
Hey @Angelk90, do the new filters satisfy what you are asking for here?

<img width="1109" alt="SCR-20240305-mfeh" src="https://github.com/zed-industries/zed/assets/19867440/1cb3b3f9-254f-4bbf-8a83-9737534ba6d4">

**Comment by notpeter** [comment]
This issue is no longer relevant and has been fixed.
