### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#8534]
[EditorConfig](https://editorconfig.org) is somewhat of an industry-standard these days. Although not a priority for me, you might want to take into consideration being compatible with existing EditorConfig configurations.

**Comment by JosephTLyons** [comment]
Ok, I understand this a bit more now. I've moved the issue back to the Zed repository!

**Comment by x4fingers** [comment]
Is there any plan to support .editorconfig until now? Once again, I have to mention its importance.

**Comment by Princesseuh** [comment]
> Is there any plan to support .editorconfig until now? Once again, I have to mention its importance.

I'm sure if you send a PR the Zed team would be happy to review it!

**Comment by BuonOmo** [comment]
I've started working on it with a friend of mine, there is already one design question we had: what configuration should we prioritize?

There are basically three configs:
- zed local
- zed global
- editor config

I'd go for editor config being first priority as if there is one in a repo, it is likely that contributions to this repo would require following it...

This is also the least effort implementation seing how the configuration is implemented related to language for zed and related to glob paths for editorconfig, intertwining both would mean having to make wider changes in the hashmaps used to load configs, thus also maybe resulting in a slower implementation

**Comment by plinss** [comment]
`.editorconfig` files should always take precedence. Also note that `.editorconfig` files need to be checked for in the same directory as each opened file, and every parent directory until you find one that has `root=true` in it. So every directory in a repo could have its own configuration. See https://editorconfig.org/#file-location

**Comment by BuonOmo** [comment]
@plinss yes I know about that ! Fortunately, there is already a rust lib that does all the parsing (see [above in this thread](https://github.com/zed-industries/zed/issues/8534#issuecomment-1969046769). Thank you for your opinion on precedence, may I know the reasoning?

**Comment by plinss** [comment]
The precedence rule is a consequence of the sub-directory support. Consider the following, I have a Python application and my coding convention is for 4 space indents and Unix line endings. Now in my application I include a local copy of an external module in a subdirectory (maybe a git submodule/subrepo) that I need to tweak. That module uses 2 space indents and Windows line endings. I'm editing files from both my application and the submodule within the same project/editing session. I need the editor to respect the `.editorconfig` in the submodule and use those settings for files in that directory. Therefore `.editorconfig` settings always override the editor's global or per-project settings.

**Comment by drornir** [comment]
Thanks toy so much @BuonOmo for working on this! would love to help if I can.

I agree with @plinss in that .editorconfig should take precendence by default. 

It's not polite to not respect what .editoconfig specifies, so enabling it by default makes unaware devs not step on anyone's toes. Even if you don't really know what .editorconfig does, and don't really care about tabs vs. spaces, to just be able to work on that codebase.

**Comment by texastoland** [comment]
Strangely neither the builtin Prettier formatter nor the Lua 1 seem to read `.editorconfig` (which Lua [depends on](https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/docs/format_config_EN.md)). Any workaround?

**Comment by lingjin666** [comment]
+1 for supporting `.editorconfig` as it could be compatible with our existed projects

**Comment by Moosems** [comment]
@maxbrunsfeld One thing to point out is that you can add (at root) arbitrary settings that can simply be ignored by other editors but used by Zed for what its worth. If its a matter of "local support for any Zed setting" you can just specify in a document custom settings to put at root that other editors would throw away (E.G. `zed_inline_completions = true`).

**Comment by stormwarning** [comment]
> One thing to point out is that you can add (at root) arbitrary settings that can simply be ignored by other editors but used by Zed 

I recently found out this is what [JetBrains does](https://www.jetbrains.com/help/idea/editorconfig.html) in their IDEs

**Comment by Moosems** [comment]
Yep! Keeps things simple and consistent :)

**Comment by bersace** [comment]
a workaround could be a `.editorconfig` -> `.zed/settings.json` script to help meanwhile.

**Comment by bersace** [comment]
Is it possible to write an extension for this feature ?

**Comment by jabr** [comment]
> a workaround could be a `.editorconfig` -> `.zed/settings.json` script to help meanwhile.

BuonOmo posted [such a script](https://gist.github.com/BuonOmo/0425a964ef7bf2ff835f27fc68477e1b) in a [comment up above](https://github.com/zed-industries/zed/issues/8534#issuecomment-1969046737).

**Comment by jabr** [comment]
> Is it possible to write an extension for this feature ?

This kind of functionality can't currently be added through a Zed extension. [Extensions only allow adding grammars, languages, and themes.](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md)

**Comment by bersace** [comment]
> I got a really small ball rolling with [this script (gist)](https://gist.github.com/BuonOmo/0425a964ef7bf2ff835f27fc68477e1b) that intents to generate a `.zed/settings` file from a local `.editorconfig` file.

I created a more elaborate solution at https://gitlab.com/bersace/zeditorconfig

``` console
$ go run gitlab.com/bersace/zeditorconfig@latest
```

This will handle braces, brackets en directories.

Thanks @BuonOmo for the orignal Ruby script, I used it for inspiration.

**Comment by PedroHLC** [comment]
Sorry guys, but `.editorconfig` fills like native for most text-editors and IDEs out there. No way I'm converting them all just to randomly edit a project in Zed. I have been using them since always and never had to care about an app not supporting them, until now:

```
╰─λ find ~/ -name '.editorconfig' -type f | wc -l
327
```

Nothing worse than opening a PR and the project leader telling you “your PR is breaking our indentation and EOF that we have enforced on `.editorconfig`, configure your IDE” -- something I have not encountered in years

**Comment by BuonOmo** [comment]
I think there's enough traction on this... I'll open a PR during next week! If any of you would like to pair on that during the week, email me :)

**Comment by shellscape** [comment]
@BuonOmo looking forward to that!

**Comment by dbarnett** [comment]
Just to summarize current status:
 - in the PR it looks like @SomeoneToIgnore has an open concern about how to handle multiplayer support / remote workflows
 - in August they said "It might take some time though, as LanguageSettings is quite a foundational thing in our codebase and there's another task I have to tackle first."

**Comment by SomeoneToIgnore** [comment]
The PR in question: https://github.com/zed-industries/zed/pull/16349
To add on top, the PR now has a great single player part prototype and a nice test to check the correctness of the feature.

Two main problems with it that it new plugin API now needs to pass a file path to get a language setting for, which was not the case before; and the fact that the PR changes the place to make a recursive FS lookup in a method, that is called during rendering, potentially up 120 times per second...

To make it closer to amortisized O(1) without any FS checks, quite a different code has to be written, even the one in the code of the feature, related to parsing and merging the actual files.

I've described a way to implement this in one of the comments to the PR https://github.com/zed-industries/zed/pull/16349#issuecomment-2379609054

and this has to wait before ssh remoting feature forms into some public form, otherwise the development work related to that ssh remoting might change things a lot, as it already did since the time the PR was open.

**Comment by Dev-cmyser** [comment]
How to use this ?
I can't find docs please help

**Comment by feryardiant** [comment]
It's apparently working just fine, but there's no syntax highlighting?

<img width="1106" alt="Image" src="https://github.com/user-attachments/assets/17c85cce-c936-4d60-afca-72bdc11b1e6d" />

**Comment by BuonOmo** [comment]
@feryardiant syntax highlighting was not the topic of this issue. It was about supporting it as a configuration tool. If you want to push this forward, you should have a look at https://github.com/zed-industries/extensions. This is the repository were language support is requested and added.

**Comment by feryardiant** [comment]
> syntax highlighting was not the topic of this issue. It was about supporting it as a configuration tool.

I see, thanks for explanation.

**Comment by BuonOmo** [comment]
Sorry for the spam... I actually found that there is already support for it in the `ini` extension for Zed: https://github.com/justinmk/tree-sitter-ini. It is just lacking detection of editorconfig files.

**Comment by tednaaa** [comment]
about my issue, here I recorded video about that bug, the use case is, when I work in some project, then I wanna change some settings in dotfiles, as you can see, in `~/dotfiles` project `.editorconfig` working, and I get json format with spaces, but when I format it from `~/projects/bcup` it will use tabs

I guess the issue is coming from `hard_tabs: true` setting in my zed config?
I think zed should prefer `.editorconfig` instead of `hard_tabs` in this case

https://github.com/user-attachments/assets/49ac3bee-eba9-4f91-ac72-b39e57476c77

**Comment by teohhanhui** [comment]
> However, Zed still doesn't always prioritize explicit .editorconfig settings over other formatters' default settings. E.g. if I set indent_style = space and indent_size = 2 in .editorconfig, I still get Rust code indented with 4 spaces.

If it did, it'd be undesired behaviour. I think it's a huge misunderstanding of EditorConfig's role. EditorConfig is the baseline. It shouldn't override specific formatting tools' configurations, e.g. `rustfmt`.

**Comment by shishkin** [comment]
> If it did, it'd be undesired behaviour. I think it's a huge misunderstanding of EditorConfig's role. EditorConfig is the baseline. It shouldn't override specific formatting tools' configurations, e.g. `rustfmt`.

There are nuances. Completely ignoring the baseline is IMHO also undesirable. I think the following is a reasonable order of precedence for formatting options (from lowest to highest):

1. Hardcoded defaults
  a. from formatter
  b. from Zed
2. user config
  a. from ~/.editorconfig
  b. from formatter
  c. from Zed
3. project config
  a. project .editorconfig
  b. project Zed config
  c. project formatter config

This allows to specify a minimal baseline and override whatever is necessary at higher levels without duplicating the same configuration between the tools.

**Comment by heygarrett** [comment]
@teohhanhui is right. EditorConfig configures _editor_ settings, not _formatter_ settings. Coming from Neovim, which has built-in support for EditorConfig, specifying tabs in `.editorconfig` will not change a formatter's behavior _unless_ that editor specifically reads from the `.editorconfig` file (eg, Prettier, shfmt). But regardless of the formatter's prerogative, the _editor_ will be configured to use tabs.

**Comment by notpushkin** [comment]
> EditorConfig configures _editor_ settings, not _formatter_ settings.

Some formatters do work with EditorConfig (e.g. Prettier), and it would be nice to have more of them do it! But that’s better discussed with formatter maintainers I guess.

**Comment by silverwind** [comment]
The python formatter definitely does not respect `.editorconfig`. I have configured 2-space indent in `.editorconfig`, but hitting tab stil does it's 4-space default.

**Comment by teohhanhui** [comment]
> The python formatter definitely does not respect `.editorconfig`. I have configured 2-space indent in `.editorconfig`, but hitting tab stil does it's 4-space default.

You should think of `.editorconfig` as the default in the absence of a formatter. It's not meant to be used to override your formatter config.

**Comment by ShalokShalom** [comment]
> > The python formatter definitely does not respect `.editorconfig`. I have configured 2-space indent in `.editorconfig`, but hitting tab stil does it's 4-space default.
> 
> You should think of `.editorconfig` as the default in the absence of a formatter. It's not meant to be used to override your formatter config.

Wouldnt it be ideal, if we can set the option, to prioritize .editorconfig?

**Comment by silverwind** [comment]
I would make it priorize `.editoconfig` because it's a per-repo setting which is more specific than the formatter global setting. An option would also work.

**Comment by ShalokShalom** [comment]
Yeah well, prioritize .editorconfig by default, and provide an opt-out.

**Comment by silverwind** [comment]
For the record, editorconfig settings taking precedence over other settings is also how it works in VSCode with the popular [EditorConfig extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig):

> This plugin [attempts](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig#known-issues) to override user/workspace settings with settings found in .editorconfig files

**Comment by teohhanhui** [comment]
> This plugin [attempts](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig#known-issues) to override user/workspace settings with settings found in .editorconfig files

I think that might be confusing, but I believe that's talking about overriding the editor's user/workspace settings in vscode, not having anything to do with how formatters for specific languages work.
