### ISSUE TITLE
Installing or removing extensions changes theme to One Light

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#8535]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Had theme set to Ayu Dark, uninstalled an extension that I don't really need and Zed switched my theme to One Light. The config file still shows Ayu Dark, though.

### Environment

Zed 0.125-pre (f81e6841)
Ubuntu 24.04
GNOME Wayland

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
I can't reproduce this.

@jansol Are you still seeing this issue?

**Comment by jansol** [comment]
Yep, last time today with 39a0841ea81ea27b428734a015007c2e0bcefde5

**Comment by jansol** [comment]
Although, today I only noticed it when I tried installing some theme extensions then switching my theme to one of them and uninstalling the other.

**Comment by notpeter** [comment]
I can reproduce something similar under two conditions:

1. If I uninstall my active theme, Zed leave the (now invalid) theme still specified in settings. This then reverts to the default settings value for `theme` which is:
```
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark"
  },
```
I have my system set to Auto, which during the daytime means when I uninstall a theme it will revert to One Light. 

2. If your settings.json on disk are invalid, the theme specified in settings may not reflect the current state of Zed. Reloading the workspace will revert to the default settings including One Light as theme.
- https://github.com/zed-industries/zed/issues/12389
 
@jansol Does either of these match your conditions? Are you still experiencing this issue?

**Comment by jansol** [comment]
No, the issue was specifically about Zed reverting to One Dark when a non-active theme was uninstalled. This no longer seems to be happening as of 0.141.3.
