### ISSUE TITLE
unable to install on linux(gentoo) rust cargo returns rust error E0562

### ISSUE THREAD

**Issue by tjallingk** [zed-industries/zed#8539]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

i am trying to install zed on gentoo linux (used protage for rustup) when running the script for dependency's i get unsupported linux so i manually installed the dependency's. and then i tried cargo run and cargo run --release but both return rust error E0562 the full error is in output.txt. if there is any info required to solve this problem let me know.
[output.txt](https://github.com/zed-industries/zed/files/14437043/output.txt)

### Environment

neofetch output:

```
OS: Gentoo Linux x86_64 
Host: 82RF Legion 5 Pro 16IAH7H 
Kernel: 6.7.0-gentoo-gentoo-dist 
Uptime: 1 hour, 32 mins 
Packages: 1354 (emerge) 
Shell: bash 5.1.16 
Resolution: 2560x1600, 1920x1080 
DE: Plasma 5.27.10 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: terminator 
CPU: 12th Gen Intel i7-12700H (20) @ 4.600GHz 
GPU: Intel Alder Lake-P GT2 [Iris Xe Graphics] 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
Memory: 4551MiB / 64029MiB 
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mikayla-maki** [comment]
As @jansol says

**Comment by tjallingk** [comment]
for those who find the same issue it turns out gentoo (portage) doesnt install the latest version of rust/rustup so manual installation is required. this will probably tell you that rust is already installed just ignore it as it looks like it is not an issue.
