### ISSUE TITLE
Scrolling stops if a code folding arrow is encountered while scrolling

### ISSUE THREAD

**Issue by srihariash999** [zed-industries/zed#8547]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When scrolling using mouse/trackpad in Zed, if a code folding arrow is in the way of scroll, the scroll stops at that point.  If you place your cursor on one of those arrows and then try to scroll, the editor won't scroll.

I have a habit of folding code blocks and scrolling down to scan the whole code and when the scroll suddenly stops, it's jarring.

Please see the attached screen grab for a better understanding -

https://github.com/zed-industries/zed/assets/30948010/79317581-415a-4e94-a438-8dbf25f1c3c9

Maybe these issues are related, but they are not exactly the same: #4414  #8434

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Scroll event should still go on, not depending on whether or not the cursor is on the arrow.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
This no longer seems to be the case in:

```txt
Zed: v0.156.0 (Zed Nightly 6167688a63eed63791814e39b3b8fd1a10da0e9b)
OS: macOS 14.4.0
Memory: 64 GiB
Architecture: aarch64
```

Closing this out. Let me know if I'm wrong and I will reopen!

**Comment by srihariash999** [comment]
Can confirm, no longer an issue.
