### ISSUE TITLE
Vim repeat issue after append

### ISSUE THREAD

**Issue by smpallen99** [zed-industries/zed#8550]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

with an empty `~/.config/zed/keymap.json`

start with the following code

```
debug("one")
debug("two")
```
* move cursor to the `(` on the first line
* type `ap + ` and escape
* move to the `(` on the 2nd line
* type `.`

Expected result
```
debug(p + "one")
debug(p + "two)
```

Actual result
```
debug(p + "one")
debug("twop + ")
```

### Environment

Zed: v0.124.6 (Zed Preview)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
@smpallen99 Thanks for reporting this! I believe this was fixed by #8513, which shipped in `v0.125.0-pre` earlier today.
