### ISSUE TITLE
Saving Default Keymap causes 'Spinning Wait Cursor' to appear

### ISSUE THREAD

**Issue by mabdulker** [zed-industries/zed#8564]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I found it quite weird how you have 3 different mappings for ```ToggleLeftDock```, ```ToggleRightDock``` and ```ToggleBottomDock``` so I tried to remap them all to ```cmd-j``` (*what I have in vscode*) in Default Key Bindings file.

After making the changes I tried to save the file, but every time I do that the spinning wait cursor appears. When it disappears the file is still not saved. To those unaware, this is the spinning wait cursor 👇
![spinny wheel](https://github.com/zed-industries/zed/assets/97461667/7b6d33ea-66b1-4f51-b96a-3d6167a25229)

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
You shouldn't update the default keymaps, but the `keymap.json` file by opening the command palette and selecting "zed: open keymap".  More info in [this thread](https://github.com/zed-industries/zed/discussions/8198#discussioncomment-8559715).

**Comment by mabdulker** [comment]
That works
