### ISSUE TITLE
Extend AI Support for local LLMs using OpenAI API

### ISSUE THREAD

**Issue by eleaese** [zed-industries/zed#8571]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently Zed only supports OpenAI. Please evaluate the option to enter URL & API Key (optional) to allow Zed to connect to local LLMs using OpenAi API.

**Comment by Moshyfawn** [comment]
Duplicate of #4424

**Comment by Moshyfawn** [comment]
Make sure to +👍 the initial post if you want to see it happen.
