### ISSUE TITLE
editor default behavior: don't format txt file

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#8575]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I want a txt file without end line.

<img width="486" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/3330200f-5b58-447c-a94e-9add3a00a5a5">

But after Zed save:

<img width="301" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/98927fdd-c85b-4ce0-9b01-58a55eb367d0">

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
You can add this config to your `settings.json` file to disable the last new line on save.

```json
"languages": {
  "Plain Text": {
    "ensure_final_newline_on_save": false
  }
}
```

**Comment by kzhui125** [comment]
Thanks, I think the default behavior should change...

**Comment by maxdeviant** [comment]
Since this behavior can be configured in settings, I'm closing this issue.

I think the current default behavior is the right one.

**Comment by lokitechz** [comment]
> You can add this config to your `settings.json` file to disable the last new line on save.
> 
> ```json
> "languages": {
>   "Plain Text": {
>     "ensure_final_newline_on_save": false
>   }
> }
> ```

i setting like that for typesciprt but it not work

**Comment by nkalait** [comment]
I have` "ensure_final_newline_on_save": false ` in my local settings but it does not work, new line is created when I save. I tried placing the line in settings also but it does not work.

**Comment by btrazzini** [comment]
I have set it to false, but when I use the format command (cmd-shit-i), it still adds a blank line at the end of the file.

```json
{
  "ensure_final_newline_on_save": false,
  "format_on_save": "off",
  "remove_trailing_whitespace_on_save": true
}
```
