### ISSUE TITLE
need a reverse proxy service for chatgpt/openai

### ISSUE THREAD

**Issue by xinx1n** [zed-industries/zed#8576]
### Check for existing issues

- [X] Completed

### Describe the feature

oepnai's reverse proxy service is very common, I tried adding the following configuration, but it didn't work
```json
"assistant": {
        "openai_api_url": "https://api.somereverseproxy.com/v1/chat/completions"
},
```
If this works, both the reverse proxy service and the offline model can be used

**Comment by Moshyfawn** [comment]
Somewhat related:

- #5032 
- #4424

**Comment by unknownjedi** [comment]
[#8525](https://github.com/zed-industries/zed/pull/8525) This adds support for Azure OpenAI. This should also work for reverse proxy / Local LLMs (Didn't test it though).

**Comment by maxdeviant** [comment]
> oepnai's reverse proxy service is very common, I tried adding the following configuration, but it didn't work
> 
> ```json
> "assistant": {
>         "openai_api_url": "https://api.somereverseproxy.com/v1/chat/completions"
> },
> ```

The `openai_api_url` setting should only contain the base URL.

What happens if you do it like this?

```json
"assistant": {
  "openai_api_url": "https://api.somereverseproxy.com/v1"
},
```

**Comment by xinx1n** [comment]
> > oepnai's reverse proxy service is very common, I tried adding the following configuration, but it didn't work
> > ```json
> > "assistant": {
> >         "openai_api_url": "https://api.somereverseproxy.com/v1/chat/completions"
> > },
> > ```
> 
> The `openai_api_url` setting should only contain the base URL.
> 
> What happens if you do it like this?
> 
> ```json
> "assistant": {
>   "openai_api_url": "https://api.somereverseproxy.com/v1"
> },
> ```

Sorry, I can't test this problem now, because I found that my key (sk-xxxx) was not saved correctly to keychain access.app, only "sk-" was saved, even if I save it manually, I couldn't save it.
