### ISSUE TITLE
Flashing issue with information window when hovering over functions, structs, etc.

### ISSUE THREAD

**Issue by spencerbart** [zed-industries/zed#8579]
![Screenshot 2024-02-28 at 20 37 58](https://github.com/zed-industries/zed/assets/38776747/feeadc68-71e0-4efc-8de8-ef346dff2e33)

![Screenshot 2024-02-28 at 20 37 41](https://github.com/zed-industries/zed/assets/38776747/3ae22e66-21f2-4a4e-85e7-a1823c5d3ba1)

The information window alternates between open and closed at various frequencies when hovering over functions, structs, etc. I am on 0.124.7 (latest).

**Comment by spencerbart** [comment]
This flashing only occurs when there is a syntax issue with the code. The flashing went away when I fixed the error on line 16.

**Comment by Moshyfawn** [comment]
I can't seem to reproduce on latest [preview](https://zed.dev/releases/preview) `v0.125.0`

<img width="1136" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/853bf19f-ce40-4739-8a31-f758dcbff69b">

**Comment by spencerbart** [comment]
https://github.com/zed-industries/zed/assets/38776747/75bbe1d7-36a6-4d92-8d52-95ee346d67f9



Just switched to 0.125.0 and it still happens

**Comment by zxch3n** [comment]
https://github.com/zed-industries/zed/assets/18425020/b97af84d-957b-4eba-b89c-102220ca3489

on 0.124.8
