### ISSUE TITLE
GitHub Sponsorship

### ISSUE THREAD

**Issue by iMonZ** [zed-industries/zed#8586]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to add GitHub Sponsorships to this Repo?

**Comment by JosephTLyons** [comment]
Hey @iMonZ 👋

We are incredibly flattered by the idea of users wanting to potentially sponsor us, but I don't think we are currently at a place where we can accept anything. We are funded and backed by investors.  The next best thing we can suggest, if anyone is looking to help us out, is to donate towards groups building depedencies we rely on.  

- [Rust](https://github.com/rust-lang/rust)
- [Taffy](https://github.com/DioxusLabs/taffy)
- [Wasmtime](https://github.com/bytecodealliance/wasmtime)
- [Tree sitter](https://github.com/tree-sitter/tree-sitter) 

Some of these groups may not accept donations, but their maintainers might.
