### ISSUE TITLE
Build issue on Linux

### ISSUE THREAD

**Issue by olivierb2** [zed-industries/zed#8597]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm getting the following error during the build.

```
error[E0061]: this method takes 3 arguments but 2 arguments were supplied
    --> crates/editor/src/editor.rs:7712:47
     |
7712 | ...                   workspace.open_project_item(target.buffer.clone(), cx)
     |                                 ^^^^^^^^^^^^^^^^^ --------------------- an argument of type `gpui::View<Pane>` is missing
     |
note: method defined here
    --> /home/olivierb/Developments/github.com/zed/crates/workspace/src/workspace.rs:2054:12
     |
2054 |     pub fn open_project_item<T>(
     |            ^^^^^^^^^^^^^^^^^
help: provide the argument
     |
7712 |                                     workspace.open_project_item(/* gpui::View<Pane> */, target.buffer.clone(), cx)
     |                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `editor` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### Environment

Debian Trixie, with Rust 1.76.0.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Not applicable.

**Comment by SomeoneToIgnore** [comment]
Thank you.

Please pull the fresh `main` changes, that got fixed in https://github.com/zed-industries/zed/commit/953bc5eee21cb2438cc58dad39e5aa59becbdbf1 , the CI for Linux is passing there (and for the next commit in `main`)

**Comment by olivierb2** [comment]
Thanks, now compiling is almost finished :-)
