### ISSUE TITLE
Line feed character in file names cause multi-line and overlapping

### ISSUE THREAD

**Issue by jnsprnw** [zed-industries/zed#8603]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First of all, I don’t know how I got the character in there, but:

[Line feed character](https://www.fileformat.info/info/unicode/char/000a/index.htm) in file names cause them to appear in multiple lines in (1) the left dock, (2) the tab bar, and (3) the symbol outline. In the left dock, it also causes the following items to overlap.

Find the file and repository here: https://github.com/Data-Visualization-Berlin/datavis.berlin/blob/master/content/jobs/akademischer-mitarbeiterin-bereich-datenvisualisierung-und-interfacedesign-wmd%0A-verguetung-nach-entgeltgruppe-13-tv-l.md

I suppose you could argue that this is the correct behaviour given the special character, but it also breaks the UI in some way.

### Environment

Mac Mini M2 Pro, Sonoma 14.3.1 (23D60), Zed 0.124.7

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1557" alt="image" src="https://github.com/zed-industries/zed/assets/5550700/c7d6c581-a728-4b45-8092-30f88e1d621e">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by teddythinh** [comment]
I'm also getting this error on Mac Intel, Sonoma 14.2, Zed 0.125.3

<img width="409" alt="image" src="https://github.com/zed-industries/zed/assets/85171754/3a6c8b3f-f229-47cf-8290-77672b28a5bd">
