### ISSUE TITLE
singled out drag'n'drop not working as it should

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#8615]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For details see: https://github.com/zed-industries/zed/issues/5110

### Environment

```
Zed: v0.125.0 (Zed Preview)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @krstp, is it this comment specifically you are referencing in this issue?

https://github.com/zed-industries/zed/issues/5110#issuecomment-1969300993

**Comment by notpeter** [comment]
I'm going to close out this issue as it doesn't actually contain the details of a request. 
@krstp feel free to edit the issue text and reopen or open a new clean issue if you're still experiencing this problem.

Thanks again for your assistance identifying areas of improvement for Zed's support of non-Github source control systems.
