### ISSUE TITLE
Selection-constrained search/replace

### ISSUE THREAD

**Issue by zambetti** [zed-industries/zed#8617]
### Check for existing issues

- [X] Completed

### Describe the feature

It seems that, as it is now, Zed can only perform search/replace on an entire document, and there is no way to constrain search/replace to only the selected text.

When you click the magnifying glass while text is selected, it assumes that you are searching for the selected text. This assumption might speed up some scenarios, but it necessitates that all searching is to be done for the entire document. This limits the value of "replace all".

Link to [discussion](https://github.com/zed-industries/zed/discussions/8608) on this topic.

### If applicable, add mockups / screenshots to help present your vision of the feature

A proposed modification to the existing search/replace function is:

1) Remove auto-fill of selected text in search field when opening "Buffer Search" via clicking on magnifying glass or via cmd-E. Auto-fill of search field would still happen as it does today with cmd-F.

2) Add toggle button for "Selected text only" to the "Buffer Search" UI

**Comment by JosephTLyons** [comment]
Not sure if there is anything salvagable this long after the fact, but an older employee had begun work on this here:

- https://github.com/zed-industries/zed/pull/1406

Might be useful to someone else wanting to work on this.

**Comment by timcki** [comment]
Hi! I'd like to try implementing this feature if @zambetti hasn't started work on it yet (:

**Comment by hferreiro** [comment]
Currently, when multiple lines are selected, only the first one is auto-filled, so what about only using auto-fill when the selection doesn't span over more than 1 line?

**Comment by hshreekar** [comment]
Hey, can i try to implement this feature (specifically fetaure 2)?. 

I have gone through the linked PR , and some of the code of the Search functionality. I am gonna try to explain what I understood from the code, any guidance on my understanding or documentation about it would be helpful.

_crates/search/src/search.rs_ - This contains the searchOptions struct which is needed for SearchQuery struct which is in _(crates/project/src/search.rs)_

The Changes in search.rs are just adding a field named ToggleSelection and defining the icon etc,etc.
My understanding is that _crates/search/src/search.rs_ is intended to be used by extending the SearchOptions and does not contain the search functionality, the main functionality that needs to be changed is in _crates/search/buffer_search.rs_, 


I have added Some screenshots. The first file is just the search.rs in project crate
![image](https://github.com/zed-industries/zed/assets/53833237/af7c32a2-9960-4ef3-9bd0-aea0919c6238)

This screenshot is of project search in search crate, i dont think i will have to modify this ?  (This is just to match paths ?? )
![image](https://github.com/zed-industries/zed/assets/53833237/1d268b70-c1e5-40e6-8146-30c03f07f7c9)

and for the last file, buffer_search in search crate, this is where i need to understand the flow the most. Buffer Search has an active query field , which calls find_matches on it and i cant seem to understand the flow from there. :(
![image](https://github.com/zed-industries/zed/assets/53833237/d7ed641c-c2f1-4e81-8693-e9e29fb14735)


I am sorry for tagging you but any help would be greatly appreciated @JosephTLyons  . Thanks in advance. And sorry for any rude behaviour and for such a large comment

**Comment by Anthony-Eid** [comment]
@hshreekar I just started working on this issue, do you want to collaborate on it together?

**Comment by hshreekar** [comment]
Sure @Anthony-Eid. Would love to colloborate with you on this issue

**Comment by Anthony-Eid** [comment]
I'm available this week or next week to collaborate on it with you. On you on the discord? We could figure out a time for us to hope on a call together there.

**Comment by Anthony-Eid** [comment]
Should this issue be closed because #10831 was merged?
