### ISSUE TITLE
dnf dependencies in `script/linux` seem to be missing c++

### ISSUE THREAD

**Issue by AlanCoding** [zed-industries/zed#8622]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First time here, following instructions for building on Linux, which are:

https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_linux.md

I'm not interested in collaborative features, and I just want to use it for now, so following these instructions looked like:

 - `git submodule update --init --recursive`
 - `rustup update`
 - `rustup target add wasm32-wasi`
 - `script/linux`
 - `cargo run --release`

The final step took a long time, and errored on this:

https://gist.github.com/AlanCoding/dbbca6805d4039834267d87b58eabfc4

>   --- stderr
> 
> 
>  error occurred: Failed to find tool. Is `c++` installed?

This was resolved by running `sudo dnf install gcc-c++` and then re-running `cargo run --release`

### Environment

unclear if this applies to my system

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This suggests the specific resolution of:

```diff
diff --git a/script/linux b/script/linux
index 5c5571701..9b45f68a0 100755
--- a/script/linux
+++ b/script/linux
@@ -28,6 +28,7 @@ if [[ -n $dnf ]]; then
     wayland-devel
     libxkbcommon-x11-devel
     openssl-devel
+    gcc-c++
   )
   $maysudo "$dnf" install -y "${deps[@]}"
   exit 0
```

But that would logically be applied to the dependency list for other platforms as well, which would be more complex to verify. It also could be a problem with other dependencies failing to declare their dependencies, but from the output I'm unclear if that might be `mio` or `tree-sitter-yaml` or both.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jansol** [comment]
For all other distros I think the relevant compiler package seems to be just called "gcc".
Either way, can't hurt adding it to the script for all platforms.

**Comment by AeroBliss** [comment]
Why does zed need gcc? Is anyone able to provide an explanation?

**Comment by AeroBliss** [comment]
I am on Linux Mint (Ubuntu). I had to install the `g++`  and `libstdc++-12-dev` packages to be able to build and run zed.

**Comment by mikayla-maki** [comment]
I think we have fixed this

**Comment by lolouthefox** [comment]
> I am on Linux Mint (Ubuntu). I had to install the `g++` and `libstdc++-12-dev` packages to be able to build and run zed.

When I try to install `libstdc++-12-dev` it gives me:
```
E: Unable to locate package libstdc++-12-dev
E: Couldn't find any package by regex 'libstdc++-12-dev'
```
