### ISSUE TITLE
Resize windows using the keyboard

### ISSUE THREAD

**Issue by Massolari** [zed-industries/zed#8628]
### Check for existing issues

- [X] Completed

### Describe the feature

In Vim we have the `:resize` command that we can use to resize windows, it'd be nice if we had something similar so we could map to a key and resize windows using the keyboard

**Comment by JosephTLyons** [comment]
I added the `vim` label, but this might be nice outside of vim mode as well.

**Comment by mbylstra** [comment]
Yeah, whether it's vim or a native way to be able to resize a pane using the keyboard, not having it is one of my biggest pain points coming from VSCode.
