### ISSUE TITLE
Issue Navigating in Show Project Files

### ISSUE THREAD

**Issue by Eshanatnight** [zed-industries/zed#8630]
Sometimes, When I go in Show Project Files fuzzy finder, up and down navigations is not working.

Steps for replication:
`cmd+p` 
fuzzy find 
try and navigate up and down

I can't get it to replicate consistently though

**Comment by SomeoneToIgnore** [comment]
Does that happen for you during project load?
We've just fixed a fix for that https://github.com/zed-industries/zed/pull/8343 and hopefully next Preview version will have it.

**Comment by Eshanatnight** [comment]
> Does that happen for you during project load?
> We've just fixed a fix for that https://github.com/zed-industries/zed/pull/8343 and hopefully next Preview version will have it.

I have seen it twice and both times I already had a project loaded. 

P.S. love Zed, switched to it as my primary editor and love it!

**Comment by notpeter** [comment]
Hi @Eshanatnight, Just following up.  Is this still something you're experiencing using Zed?

**Comment by Eshanatnight** [comment]
I have not faced it in a while, but I have been only using zed for on fairly small project, since I posted the issue. Not sure if the number of files in the Project is a factor, but wanted to share the information just in case

**Comment by notpeter** [comment]
I appreciate it.  I'm going to close this issue. If you (or anyone else) runs into this in the future, please comment and I'm happy to reopen.  Thanks for following up.
