### ISSUE TITLE
Doc hint is blinking

### ISSUE THREAD

**Issue by glebcomissarov** [zed-industries/zed#8631]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the mouse hovers over an object with an error, the documentation hint will blink.

https://github.com/zed-industries/zed/assets/49168459/862d8a6a-2ed0-4237-8d38-4118b85b1edc

### Environment

Zed 0.124.8

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Duplicate of #8579

**Comment by Moshyfawn** [comment]
Make sure to +👍 the other issue and possibly add any additional info you might have.
