### ISSUE TITLE
Unable to resize panes with the cursor in Zed

### ISSUE THREAD

**Issue by evrsen** [zed-industries/zed#8640]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello, I'm unable to use my cursor for resizing panes in Zed, the behaviour is odd and I'm not sure how I'd describe it, the resize cursor pops up *sometimes* but it instantly changes back to the regular pointer cursor before I'm able to click and drag, here is a screen recording demonstrating the problem:

https://github.com/zed-industries/zed/assets/146845123/0d8b4ea4-045e-42b2-b4fa-16a2ff357133

### Environment

Zed: v0.125.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I think this is likely another instance of our flickering UI bug, but its hard for me to know for sure. I'll bring it up with the team.
