### ISSUE TITLE
[vim] `menu::SelectFirst` doesn't work in the `ProjectPanel` context

### ISSUE THREAD

**Issue by nauvalazhar** [zed-industries/zed#8653]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi, I'm trying to remap the project panel with Vim key bindings, but I can only use the `menu::SelectNext` and `menu::SelectPrev`, not the `menu::SelectFirst` and `menu::SelectLast`. Is this expected behavior?

Steps to reproduce:
1. Add the following custom keymaps
2. Press `gg` or `G`

Keymaps:
```json
[
{
    "context": "ProjectPanel",
    "bindings": {
      "h": "project_panel::CollapseSelectedEntry",
      "l": "project_panel::ExpandSelectedEntry",
      "a": "project_panel::NewFile",
      "A": "project_panel::NewDirectory",
      "enter": "project_panel::Open",
      "cmd-x": "project_panel::Cut",
      "cmd-c": "project_panel::Copy",
      "cmd-v": "project_panel::Paste",
      "y": "project_panel::CopyPath",
      "alt-cmd-shift-c": "project_panel::CopyRelativePath",
      "r": "project_panel::Rename",
      "d": "project_panel::Delete",
      "alt-cmd-r": "project_panel::RevealInFinder",
      "alt-shift-f": "project_panel::NewSearchInDirectory",
      "j": "menu::SelectNext",
      "k": "menu::SelectPrev",
      "g g": "menu::SelectFirst",
      "shift-g": "menu::SelectLast"
    }
  }
]
```

Thank you!

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.2.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mirageN1349** [comment]
+1

**Comment by ConradIrwin** [comment]
@nauvalazhar This should be fixed by https://github.com/zed-industries/zed/pull/11078 (release in 0.134.x)
