### ISSUE TITLE
Debug build of Zed violates unsafe precondition

### ISSUE THREAD

**Issue by Liamolucko** [zed-industries/zed#8658]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to run a debug build of Zed I get this error:

```
thread 'main' panicked at library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

The issue's in this bit of code:

https://github.com/zed-industries/zed/blob/aeed9d0d8b5300836419f6a1c7f9836a947ab9e1/crates/gpui/src/platform/mac/platform.rs#L681-L694

It's assumed that if the app's running inside a bundle, that bundle will have a version associated with it. But it doesn't, so `bytes` is null causing the failed unsafe precondition.

`len` is also 0, which is presumably why it works fine in release mode.

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

(zed version isn't really relevant because that's the version I have installed, not the version I'm building (eb1ab69))

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I already have a fix for the issue:

```diff
diff --git a/crates/gpui/src/platform/mac/platform.rs b/crates/gpui/src/platform/mac/platform.rs
index 473fb5978..8b35114b7 100644
--- a/crates/gpui/src/platform/mac/platform.rs
+++ b/crates/gpui/src/platform/mac/platform.rs
@@ -5,7 +5,7 @@ use crate::{
     MenuItem, PathPromptOptions, Platform, PlatformDisplay, PlatformInput, PlatformTextSystem,
     PlatformWindow, Result, SemanticVersion, Task, WindowAppearance, WindowOptions,
 };
-use anyhow::anyhow;
+use anyhow::{anyhow, bail};
 use block::ConcreteBlock;
 use cocoa::{
     appkit::{
@@ -685,6 +685,9 @@ impl Platform for MacPlatform {
                 Err(anyhow!("app is not running inside a bundle"))
             } else {
                 let version: id = msg_send![bundle, objectForInfoDictionaryKey: ns_string("CFBundleShortVersionString")];
+                if version.is_null() {
+                    bail!("bundle does not have version");
+                }
                 let len = msg_send![version, lengthOfBytesUsingEncoding: NSUTF8StringEncoding];
                 let bytes = version.UTF8String() as *const u8;
                 let version = str::from_utf8(slice::from_raw_parts(bytes, len)).unwrap();
```

I'm just opening this issue first because it seems odd that I seem to be the only one having this issue. Surely I'm not the only one building debug versions of Zed during development?

The fact that Zed's running inside a bundle shouldn't be due to any kind of weird way I'm running it, it's just a plain `cargo run`.

[The docs for `NsBundle::mainBundle()`](https://developer.apple.com/documentation/foundation/nsbundle/1410786-mainbundle?language=objc) say that 'This method may return a valid bundle object even for unbundled apps', so it doesn't seem like it's out of the ordinary for Zed to be running inside a bundle even when it's not been manually packaged into one.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by osiewicz** [comment]
Hey, thanks for the report!
It looks like this doesn't crash at runtime because `assert_unsafe_precondition` (which is what gets called to verify these preconditions in [from_raw_parts](https://github.com/rust-lang/rust/blob/b0696a5160711c068cb1f01b7437db7990d15750/library/core/src/slice/raw.rs#L99)) is a noop in release build per [docs](https://stdrs.dev/nightly/x86_64-unknown-linux-gnu/core/intrinsics/macro.assert_unsafe_precondition.html)

> This macro expands to a check at runtime if debug_assertions is set. 
Still, this looks like a valid issue for dev builds that are not bundled.

**Comment by osiewicz** [comment]
If you're using nightly then I suppose this is a prime suspect as to why you're experiencing it: https://github.com/rust-lang/rust/pull/120594
I occasionally build with nightly, though I never run it.

**Comment by osiewicz** [comment]
The patch you've provided looks fine to me, feel free to submit it as a PR :)

**Comment by Liamolucko** [comment]
> If you're using nightly then I suppose this is a prime suspect as to why you're experiencing it

Ah, yep, that's the reason: I set it up last month (for `-Zthreads=8`) and then forgot about it 😅. Anyway, I've opened #8691.
