### ISSUE TITLE
can't to find reset assistant reset key

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#8672]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/12579229/e6aac121-6903-4eef-b6a0-02e1387be7d6)

I can not to reset open_ai key

### Environment

Zed Preview 0.125.1
MacBook Air (13-inch, 2017)
cpu: 1.8 GHz Intel Core i5

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Ref: #8200

**Comment by ljh740** [comment]
> 参考号：#8200

![image](https://github.com/zed-industries/zed/assets/9330229/0807aef7-9ff7-4837-b14f-d608a8de60d6)
no options
version :  0.124.8 0ec803cea977afad95f836bc869efd1016de8b8d

**Comment by Moshyfawn** [comment]
> no options
> version : 0.124.8 [0ec803c](https://github.com/zed-industries/zed/commit/0ec803cea977afad95f836bc869efd1016de8b8d)

You will need to focus the assistant panel for the contextual assistant's command to be listed.
