### ISSUE TITLE
Add a function for sorting.

### ISSUE THREAD

**Issue by ZeroDot1** [zed-industries/zed#8683]
### Check for existing issues

- [X] Completed

### Describe the feature

I think it is important to have a function for sorting lines. In most editors, this always has to be added on somehow. i think it is better to implement a sorting function directly.
The sorting function should do the following.
Sort the rows by number from A-Z and remove duplicates.

Such a function makes it easier for developers of e.g. blacklists for adblockers and other lists to quickly edit and exclude duplicates.

**Comment by RustoMCSpit** [comment]
usually a function like the above is included within the language itself or a module if youre referring to a csv or something. are you referring to a csv file or the coding file within zed itself? if the zed file, im not sure what you mean, that could be 

1) automatic indentation
2) corrected minor syntax (e.g. in python fixing correcting between = == ===)
3) automatically assigning proper name convention standards in a specific language like having zed rename all functions in gdscript to camelcase (if it had a language dictionary and broke the words down) and all class names to whatever name casing gdscript uses.
4) correcting the spelling and grammar within strings (e.g. 'hlelo i am silly' to 'Hello, I am silly.')
5) automatically assigning variable types and adding in automatic error catching like 
`def reporter(f,x): 
    try:
        if f(x):  
            # f(x) is not None and not throw any exception. Your last case
            return "Generic"
        # f(x) is `None`
        return "No Problem"
    except ValueError:
        return 'Value'
    except TypeError:
        return 'Type'
    except E2OddException:
        return 'E2Odd'`
6) common code optimisations (e.g. changing out one sorting method for another)
7) better coding readability e.g. preventing nested if statements by using ! [in python](https://www.youtube.com/shorts/Zmx0Ou5TNJs)
8) etc.

very confused about this issue ngl

**Comment by baldwindavid** [comment]
> The sorting function should do the following.
> Sort the rows by number from A-Z and remove duplicates.

@ZeroDot1 There is a builtin sort command already. Select whatever lines you'd like to sort, open the command palette (`cmd-shift-p`), and search for `:sort`.

This is not going to remove duplicates. A separate command to remove duplicate lines might be interesting, but I would not expect a sort function to remove lines.

**Comment by maxdeviant** [comment]
As @baldwindavid mentions, we already have this functionality available:

- The `editor: sort lines case sensitive` and `editor: sort lines case insensitive` commands will sort the selected lines
- The `editor: unique lines case sensitive` and `editor: unique lines case insensitive` commands will sort the selected lines as well as remove any duplicates

**Comment by RustoMCSpit** [comment]
> As @baldwindavid mentions, we already have this functionality available:
> 
> * The `editor: sort lines case sensitive` and `editor: sort lines case insensitive` commands will sort the selected lines
> * The `editor: unique lines case sensitive` and `editor: unique lines case insensitive` commands will sort the selected lines as well as remove any duplicates

do you have the stuff i mentioned?

**Comment by RustoMCSpit** [comment]
> As @baldwindavid mentions, we already have this functionality available:
> 
> * The `editor: sort lines case sensitive` and `editor: sort lines case insensitive` commands will sort the selected lines
> * The `editor: unique lines case sensitive` and `editor: unique lines case insensitive` commands will sort the selected lines as well as remove any duplicates

do youve thr functionality i mentioned?

**Comment by Moshyfawn** [comment]
@RustoMCSpit We'd appreciate it if you'd tone it down a bit. I've noticed that you've been spamming comments in a number of threads, some of which have been somewhat disrespectful, and now you're reposting your off-topic comment. Let's keep it civil.

**Comment by baldwindavid** [comment]
> @ZeroDot1 There is a builtin sort command already. Select whatever lines you'd like to sort, open the command palette (`cmd-shift-p`), and search for `:sort`.

@ZeroDot1 If it's not in the command palette then 🤷 . Perhaps someone on Linux can chime in.
