### ISSUE TITLE
Native Full Screen Causes 4k HDR Display to Stop Working

### ISSUE THREAD

**Issue by Kenny-MWI** [zed-industries/zed#8687]
### Check for existing issues

- [X] Completed

## Description 

When I click the green button in the top left of the Zed window to make the application full screen on my HDR monitor, the display turns black and I can't do anything on it. My mouse cursor is not visible and I'm unable to use Cmd+Tab or gestures to switch to other windows that were open on that display and I cannot use Cmd+Q to close the application. I can move my cursor to the left and right to my non-HDR displays so I know the machine is not frozen. I have to disconnect that monitor from my laptop to to close the application before plugging it back in. 

## Steps to reproduce: 

- I have a Samsung LU28R55 4k HDR monitor connected to my 2020 Macbook Pro via USB-C to DisplayPort cable but I suspect any HDR monitor would work for this. 
- Open the Mac System Settings > Displays and ensure the option for "High Dynamic Range" is enabled. 
- Open Zed and go into full screen using the green full screen button on the window or View > Enter Full Screen
- The screen goes black and nothing works on it until the screen has been disconnected and application closed or taken out of full screen mode.

## Workaround:

- Open the Mac System Settings > Displays and ensure the option for "High Dynamic Range" is **disabled**.
- Native full screen works as expected. 

### Environment

```
Zed: v0.124.8 (Zed)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: x86_64
```

If it matters, this Macbook is using Intel Iris Plus Graphics, 1536 MB and has a 2.3 GHz Quad-Core i7 CPU. 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here's the system setting I had to change for this display: 
 
<img width="474" alt="Screenshot 2024-03-01 at 2 55 27 PM" src="https://github.com/zed-industries/zed/assets/72874890/95e5c154-9378-4149-9fcd-54ea8a4d6278">

I don't have to disable this for any other application to run full screen which leads me to believe this is a bug with Zed rather than MacOS. Toggling this system setting off every time I want to use Zed is tedious and not a long term solution. 

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Nothing gets written to the log when this bug occurs

**Comment by Tom-Boscher** [comment]
I have a 4K HDR external monitor too (with HDR enabled) and I never has this issue. Maybe it's specific to your model.

**Comment by Tom-Boscher** [comment]
@Kenny-MWI I have a MacBook Pro M1 Pro, running Sonoma 14.3.1
