### ISSUE TITLE
selecting path while terminal is not active

### ISSUE THREAD

**Issue by danielzsh** [zed-industries/zed#8699]
### Check for existing issues

- [X] Completed

### Describe the feature

In vscode, you are able to cmd + click to open a path from terminal, even if the terminal is not currently selected. However, in Zed, you have to click into the terminal first before you can interact with cmd + click. It's a minor issue, but I feel like it would improve QOL (I thought Zed was being unresponsive at first before realizing I had to click into the terminal first 😅 )

**Comment by Moshyfawn** [comment]
There's already a feature request for cursor focus management. I will close this one in favour of it. Please make sure to +👍 it and add any additional information that might be missing.

**Comment by Moshyfawn** [comment]
Duplicate of #8167

**Comment by danielzsh** [comment]
Ah sorry, didnt see it 😓

**Comment by Moshyfawn** [comment]
No problem at all!
