### ISSUE TITLE
file_finder match ">" prefix goto command_palette

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8703]
### Check for existing issues

- [X] Completed

### Describe the feature

The VScode behavior: "cmd-p" -> ">" ≈ "cmd-shift-p"
![code](https://github.com/zed-industries/zed/assets/45585937/1e9ec162-a599-4b29-a9f4-9bd29d6fa1d9)
Zed:
![zed](https://github.com/zed-industries/zed/assets/45585937/73305938-e906-4e14-b0b4-e9056b165b19)

**Comment by wmstack** [comment]
I prefer `;` because it is on the home row and doesn't require pressing shift.

**Comment by notpeter** [comment]
Closing as duplicate of:
- #15896 

This issue was opened first, but that one has more upvotes.
