### ISSUE TITLE
Scroll bar covers highlight.

### ISSUE THREAD

**Issue by Congyuwang** [zed-industries/zed#8705]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/52687642/65df4411-51d6-450a-8986-afbabb5cd799

The bar of the scrolling bar covers the highlights. I think either the highlight should float above the scroll bar or the scroll bar should be semi-transparent.

In VS Code, the highlights are visible under the scroll bar.

Related: #4866.

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Congyuwang** [comment]
I figured that this only occurs when I use the [MacOS classic theme](https://github.com/huacnlee/zed-theme-macos-classic) installed from the extension panel. I've tried another theme from the extension store, which does not have this issue. I'm not sure if this is an issue for Zed or the extension.

**Comment by Wappen** [comment]
Had the same issue when creating my own theme. To fix I added alpha to scrollbar.thumb.background
