### ISSUE TITLE
Fix popover_menu toggle

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8709]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Obviously, it's not a toggle
All popover_menus have this issue
![fix_popover](https://github.com/zed-industries/zed/assets/45585937/43537cf1-ac14-4546-98cf-aa748db72ffa)

### Environment

Zed: v0.125.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Just so I'm clear, are you saying that the design of these buttons doesn't indicate that it's a popover, like dropdown arrow icons etc?
