### ISSUE TITLE
gpui: Defining multiple AssetSources

### ISSUE THREAD

**Issue by Bloeckchengrafik** [zed-industries/zed#8713]
### Check for existing issues

- [X] Completed

### Describe the feature

Trying to build a gpui-library for using lucide-icons, I noticed that there is no way of providing assets without adding some kind of hook into the user's AssetSource. I think this is not optimal behaviour. I don't know yet, how this could be implemented specifically.

**Comment by maxdeviant** [comment]
This seems like it is solvable in userspace by implementing `AssetSource` that composes more `AssetSource`s together.

For example, the `load` method could check `lucide-icons` first, and then check the application's own asset source.

**Comment by Bloeckchengrafik** [comment]
Yep, that's what I'm currently doing. Seems like that's the way of doing things! Thanks!

**Comment by filippovd** [comment]
look at https://github.com/filippovd/gpui-assets
