### ISSUE TITLE
[vim] I set it to do escape when I press jk, but it doesn't work when I press jk during auto completion.

### ISSUE THREAD

**Issue by YoungHaKim7** [zed-industries/zed#8729]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I set it to do escape when I press jk, but it doesn't work when I press jk during auto completion.

```json
{
  "context": "Editor && vim_mode == insert && !menu",
  "bindings": {
    // put key-bindings here if you want them to work in insert mode
    // ~~~~~~ Insert Mode
    "j k": ["vim::SwitchMode", "Normal"]
  }
},

```

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.2.1 23C71 arm64
Memory: 16 GiB
Architecture: aarch64(M1 macPro)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

- My NeoVim

https://github.com/zed-industries/zed/assets/67513038/b7db96e0-5b83-45f1-aee1-30851bfad0dc

- Zed (Not Working)

https://github.com/zed-industries/zed/assets/67513038/579e9fc4-a35c-4141-9ad4-6e9e75850e74

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by eminoz** [comment]
"bindings": {
      "j k": "vim::NormalBefore" // remap jk in insert mode to escape.
    }
  }
you must replace your code with this

**Comment by YoungHaKim7** [comment]
https://github.com/zed-industries/zed/discussions/6661

When I press jk, there is something I have to type with a delay of 250ms. When I type, I press faster than that time, so I have to type it like the code above to input jk immediately.

**Comment by ConradIrwin** [comment]
In your context you have `"  "context": "Editor && vim_mode == insert && !menu"`. This means that the bindings won't apply when the menu is open.

I think you need: `  "context": "Editor && vim_mode == insert",` instead.

Getting the contexts right in the keybindings file is a known problem right now, so help clarifying the documentation is much appreciated.

**Comment by YoungHaKim7** [comment]
It works fine, thank you.

```json
  {
    "context": "Editor && vim_mode == insert && !menu",
    "bindings": {
      // put key-bindings here if you want them to work in insert mode
      // ~~~~~~ Insert Mode
      "j k": ["vim::SwitchMode", "Normal"]
    }
  },
  {
    "context": "Editor && vim_mode == insert && menu",
    "bindings": {
      // put key-bindings here if you want them to work in insert mode
      // ~~~~~~ Insert Mode
      "j k": ["vim::SwitchMode", "Normal"]
    }
  },
```
