### ISSUE TITLE
Code Action text overlaps when too long

### ISSUE THREAD

**Issue by ThomasAlban** [zed-industries/zed#8772]
![image](https://github.com/zed-industries/zed/assets/98399119/2e20c339-49b7-49c3-b87c-4cc840045f10)

This is in the latest version of Zed

**Comment by Moshyfawn** [comment]
Duplicate of #8772

**Comment by Moshyfawn** [comment]
Be sure to +👍 the other issue and add any additional information that might be missing from it.
