### ISSUE TITLE
[vim] block cursor does not render italic

### ISSUE THREAD

**Issue by llllvvuu** [zed-industries/zed#8799]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/5601392/20ca87fb-154a-4aa9-8dee-e09a03e521cd

Tested Vim Mode, Catppuccin Theme, Operator Mono font. But any theme/font with italic should work.

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Imgkl** [comment]
@llllvvuu how did you get the cursor to be in block? is there a setting you need to configure?

**Comment by Imgkl** [comment]
@TENX-S oh right, that makes sense. Thanks.

**Comment by weartist** [comment]
@llllvvuu Do you still encounter this issue in the latest version?

**Comment by llllvvuu** [comment]
Zed 0.129.2 still has the issue.

I reproduced it with a free font in case that's easier:
```json
{
  "theme": "Catppuccin Macchiato",
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "buffer_font_size": 12,
  "vim_mode": true,
  "ui_font_family": "JuliaMono",
  "buffer_font_family": "JuliaMono",
  "terminal": {
    "dock": "right",
    "font_family": "Iosevka Term"
  }
}
```

**Comment by weartist** [comment]
> Zed 0.129.2 still has the issue.
> 
> I reproduced it with a free font in case that's easier:
> 
> ```json
> {
>   "theme": "Catppuccin Macchiato",
>   "telemetry": {
>     "diagnostics": false,
>     "metrics": false
>   },
>   "buffer_font_size": 12,
>   "vim_mode": true,
>   "ui_font_family": "JuliaMono",
>   "buffer_font_family": "JuliaMono",
>   "terminal": {
>     "dock": "right",
>     "font_family": "Iosevka Term"
>   }
> }
> ```

Thanks for the configuration! I reproduced, I will submit a PR to fix this issue

**Comment by weartist** [comment]
> Zed 0.129.2 still has the issue.
> 
> I reproduced it with a free font in case that's easier:
> 
> ```json
> {
>   "theme": "Catppuccin Macchiato",
>   "telemetry": {
>     "diagnostics": false,
>     "metrics": false
>   },
>   "buffer_font_size": 12,
>   "vim_mode": true,
>   "ui_font_family": "JuliaMono",
>   "buffer_font_family": "JuliaMono",
>   "terminal": {
>     "dock": "right",
>     "font_family": "Iosevka Term"
>   }
> }
> ```

Thanks for the configuration! I reproduced, I'll try to fix this
