### ISSUE TITLE
"Installed" extensions filter reports no installed extensions

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#8802]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Title

### Environment

Zed: v0.126.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1608" alt="SCR-20240303-udut" src="https://github.com/zed-industries/zed/assets/19867440/fb61f395-a17f-4026-93f1-b7feb32fa465">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
@JosephTLyons What happens if you run the `reload extensions` command?

**Comment by JosephTLyons** [comment]
> @JosephTLyons What happens if you run the `reload extensions` command?

Weirdly enough, I cannot reproduce it now - either I randomly hit bad luck multiple times in a row and something wasn't fully loaded when I tried switching filters, or something changed upstream?

**Comment by failable** [comment]
Can not list extensions at all. I have some of them installed. No logs and randomly happened.

<img width="952" alt="image" src="https://github.com/zed-industries/zed/assets/5475262/6a1a949a-9f8c-4455-af32-e81e68484a5d">
<img width="949" alt="image" src="https://github.com/zed-industries/zed/assets/5475262/e67c0cbc-5df9-46c0-865a-b36cbc63b744">
<img width="955" alt="image" src="https://github.com/zed-industries/zed/assets/5475262/141ada1b-ef6f-4d40-bed6-6e4ce1b064d7">

**Comment by JosephTLyons** [comment]
@failable - are you still experiencing this? I haven't ran into it since making this report.

**Comment by failable** [comment]
@JosephTLyons Hello, I can not reproduce it constantly. It randomly happened before. Possibly related to network condition.
