### ISSUE TITLE
I need source control feature

### ISSUE THREAD

**Issue by nguyenthanhan201** [zed-industries/zed#8810]
### Check for existing issues

- [ ] Completed

### Describe the feature

In vscode I see source control feature. It is handy for me

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="282" alt="Screenshot 2024-03-04 at 14 20 27" src="https://github.com/zed-industries/zed/assets/80932055/bd5c5c06-05e6-4d17-a812-867402486b18">

**Comment by Moshyfawn** [comment]
Duplicate of #4367
