### ISSUE TITLE
Xcode Keymap

### ISSUE THREAD

**Issue by evrsen** [zed-industries/zed#8819]
### Check for existing issues

- [X] Completed

### Describe the feature

This issue proposes adding Xcode's keymaps to the available base keymaps in Zed. As of now, only VSCode, JetBrains, SublimeText and Atom are available. You can see how JetBrains [Xcode Keymap](https://plugins.jetbrains.com/plugin/13093-xcode-keymap) plugin did it [here](https://github.com/JetBrains/intellij-community/tree/master/platform/platform-resources/src/keymaps).

**Comment by Moshyfawn** [comment]
I think this was already explored in #5076 and the decision was made not to pursue it.

**Comment by evrsen** [comment]
Ah thanks @Moshyfawn, sad to hear about the decision. Are you aware of any issue that covers the ability for extensions to override keymaps?

**Comment by Moshyfawn** [comment]
Not that I know of. But it's probably not a bad idea for an extension! It would unlock keymap sets independent of what Zed officially provides out of the box. My advice would be to create a new issue describing your desire for a keymap set extension.

**Comment by evrsen** [comment]
Sure thing, thanks again, will be closing this issue 👍
