### ISSUE TITLE
"typescript.tsserver.maxTsServerMemory" VSCode equivalent

### ISSUE THREAD

**Issue by maschwenk** [zed-industries/zed#8821]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode recently opened up support for spawning a separate Typescript Language Server for really large projects so that you can set higher memory limits. Without this, my large Typescript monorepo is frequently hitting a 4GiB memory limit and hitting:

```
[lspserver] [tsclient] [tsserver] Exited. Code: null. Signal: SIGABRT
```

**Comment by maschwenk** [comment]
Excellent, I’ll leave this open for a moment just in case maintainers might want to make this more of a first class thing, but I think this is enough of a fringe issue having this Issue googleable is pretty sufficient.

**Comment by baptisteArno** [comment]
Just wrote about my performance issue (#8884).

I tried to increase `maxTsServerMemory` to `8192` but that doesn't seem to fix my tsserver speed issue.

**Comment by maschwenk** [comment]
Going to close because that fixed our issue, so really just a matter of discoverability. Feel free to reopen!

**Comment by dimuuu** [comment]
omg, finally figured it out, thanks!

**Comment by zen0wu** [comment]
I was trying this out and I don't think that settings work. This is what I have in Zed's setting

```json
  "lsp": {
    "typescript-language-server": {
      "initialization_options": {
        "maxTsServerMemory": 16000
      }
    }
  }
```

**Comment by jwilm** [comment]
> I was trying this out and I don't think that settings work. This is what I have in Zed's setting
> 
> ```json
>   "lsp": {
>     "typescript-language-server": {
>       "initialization_options": {
>         "maxTsServerMemory": 16000
>       }
>     }
>   }
> ```

This approach doesn't work with current release of Zed. Zed's [TypeScript language docs](https://zed.dev/docs/languages/typescript#large-projects) have the solution.
