### ISSUE TITLE
SQL support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#8860]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed should ship with SQL support out of the box

tree-sitter: https://github.com/evrsen/tree-sitter-sql
language server: https://github.com/joe-re/sql-language-server

**Comment by jansol** [comment]
PR: #7082 
Previously: zed-industries/extensions#206
Tangentially related: #4838

**Comment by JosephTLyons** [comment]
Maybe we should bring that older one back from the extensions repo with all the upvotes and close this one out?

**Comment by JosephTLyons** [comment]
Closing this out, as we have a SQL extension in the extensions store.
