### ISSUE TITLE
editor::Outdent doesn't work on the first character of the line

### ISSUE THREAD

**Issue by fserb** [zed-industries/zed#8867]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If I press `cmd+]` (editor::Outdent on Mac) and the cursor is at any position after the first character, it works as intended. On the first character it doesn't do anything.

Can repro on a new empty Plain Text file.

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Is this how you would reproduce the issue? I can't seem to hit the same thing.

https://github.com/zed-industries/zed/assets/16290753/01815bfd-3545-4b5f-afef-729aa6c25585

**Comment by fserb** [comment]
Exactly like that.

I just got the latest Zed Preview and it seems to be fixed now:

```
Zed: v0.125.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64
```

I had tested on Zed Preview but it was an old one (I didn't notice the "Downloading" on the bottom).

Sorry.

**Comment by Moshyfawn** [comment]
No problem! Glad it's fixed 🚀
