### ISSUE TITLE
LSP logs server selector checkbox style inconsistencies

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#8868]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open the command palette _(`cmd-shift-p`)_.
2. Select `debug: open language server logs`.
3. Click on the language server name in the top left corner _(must have at least one server running)_.
4. See checkbox right border is missing.
5. See checkbox width and height don't match and border is missing _(make sure you check `RPC Messages`)_.

### Environment

Zed: v0.125.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![zed-lsp-dropdown](https://github.com/zed-industries/zed/assets/16290753/b6edc3bc-9dac-49ed-ad79-b1705c387049)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
The LSP logs dropdown UI issue was similarly reported in https://github.com/zed-industries/zed/issues/4664#issuecomment-1908629505 but the issue itself is about an outdate dropdown view.

**Comment by Moshyfawn** [comment]
I think the popover itself needs padding too.

**Comment by maxdeviant** [comment]
> I think the popover itself needs padding too.

Done in https://github.com/zed-industries/zed/pull/9197.

**Comment by maxdeviant** [comment]
@Moshyfawn I'm having trouble reproducing this locally in any version of Zed 🤔 

Are you pretty consistently seeing the missing checkbox border, or are there some other factors that influence it?

**Comment by Moshyfawn** [comment]
> Are you pretty consistently seeing the missing checkbox border, or are there some other factors that influence it?

I was just about to ask you about the border issue 🤭

Yes, it's there all the time on my machine. 
I'm not quite sure what might be causing it as I don't have any spectacular video/rendering configs in place. My system environment is listed in the issue description, but I'll look into what else might be causing it in a bit.

**Comment by maxdeviant** [comment]
> > Are you pretty consistently seeing the missing checkbox border, or are there some other factors that influence it?
> 
> I was just about to ask you about the border issue 🤭
> 
> Yes, it's there all the time on my machine. I'm not quite sure what might be causing it as I don't have any spectacular video/rendering configs in place. My system environment is listed in the issue description, but I'll look into what else might be causing it in a bit.

This might be a long shot, but does changing the theme have any impact?

Also, would you mind posting/linking to your Zed `settings.json` so I can see if there's anything in there?

**Comment by Moshyfawn** [comment]
> This might be a long shot, but does changing the theme have any impact?

I haven't tried every default theme, but most of them (both light and dark) have no effect on the border problem, just higher or lower contrast on what's "left of the checkbox".

> Also, would you mind posting/linking to your Zed `settings.json` so I can see if there's anything in there?

You are spot on about the issue being related to my config: `"ui_font_size": 14` makes the board "disappear".

**Comment by maxdeviant** [comment]
> > Also, would you mind posting/linking to your Zed `settings.json` so I can see if there's anything in there?
> 
> You are spot on about the issue being related to my config: `"ui_font_size": 14` makes the board "disappear".

Bingo!

<img width="283" alt="Screenshot 2024-03-11 at 4 37 55 PM" src="https://github.com/zed-industries/zed/assets/1486634/12285081-1ff5-44e4-ad77-5ead862744c4">
