### ISSUE TITLE
add close button for terminal panel

### ISSUE THREAD

**Issue by pigletfly** [zed-industries/zed#8882]
### Check for existing issues

- [X] Completed

### Describe the feature

there is `new terminal` and `zoom in` button on terminal panel, it would be better when there is a `hide panel` icon button.

**Comment by Moshyfawn** [comment]
You can click both the close button (1) in the specific tab of the terminal instance you want to close, and the terminal pane toggle button (2) at the bottom of the window to toggle it on and off. Let me know if this works for you.

![zed-term-toggle](https://github.com/zed-industries/zed/assets/16290753/2b301688-b6e7-44a3-a1bb-5f7f5c616c8f)
