### ISSUE TITLE
Constant tab bar drop area redrawing/flickering

### ISSUE THREAD

**Issue by hmemcpy** [zed-industries/zed#8883]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I encountered this while working on #6818.

With @maxdeviant's help, I added `debug_bg_cyan` to visualize the problem: the "clickable" area is constantly shrinking to a small rectangle, preventing the full use of the "double-click to open a new buffer" feature.

I understand this issue is already known, but I couldn't find this specific ticket. If duplicate - please feel free to close!

### Environment

Zed: v0.125.0 (Zed Dev)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![2024-03-05 13 04 53](https://github.com/zed-industries/zed/assets/601206/1f76f77e-c304-4b83-801d-f60e7104c848)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
There is a similar issue currently active in #8598 regarding the project panel, which may have the same underlining cause, but let's leave your issue open for now.
