### ISSUE TITLE
Allow downgrading an extension

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#8898]
### Check for existing issues

- [X] Completed

### Describe the feature

If an extension is pushed that is broken, there is no way to downgrade after upgrading.

**Comment by Moshyfawn** [comment]
Downgrade or even select any existing version, not just the previous one.

**Comment by JosephTLyons** [comment]
> Downgrade or even select any existing version, not just the previous one.

Good idea - I was thinking the same :)

**Comment by JosephTLyons** [comment]
Closed via: https://github.com/zed-industries/zed/pull/9890
