### ISSUE TITLE
Error while building on Arch via yay

### ISSUE THREAD

**Issue by gNewl** [zed-industries/zed#8901]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried running yay -s zed-editor and it gave me an error. Probably something I did wrong while installing btw

### Environment

Arch Linux with Plasma 6 (same issue on Plasma 5)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

   Compiling db v0.1.0 (/home/gbrl/.cache/yay/zed-editor/src/zed-0.125.1-pre/crates/db)
error[E0463]: can't find crate for `sqlez_macros`
 --> crates/db/src/kvp.rs:1:5
  |
1 | use sqlez_macros::sql;
  |     ^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `sqlez_macros`
  --> crates/db/src/db.rs:12:9
   |
12 | pub use sqlez_macros;
   |         ^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `sqlez_macros`
  --> crates/db/src/db.rs:19:5
   |
19 | use sqlez_macros::sql;
   |     ^^^^^^^^^^^^ can't find crate

error: cannot determine resolution for the macro `$crate::sqlez_macros::sql`
  --> crates/db/src/query.rs:50:32
   |
50 |                   let sql_stmt = $crate::sqlez_macros::sql!($($sql)+);
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: crates/db/src/kvp.rs:27:5
   |
27 | /     query! {
28 | |         pub async fn delete_kvp(key: String) -> Result<()> {
29 | |             DELETE FROM kv_store WHERE key = (?)
30 | |         }
31 | |     }
   | |_____- in this macro invocation
   |
   = note: import resolution is stuck, try simplifying macro imports
   = note: this error originates in the macro `query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot determine resolution for the macro `$crate::sqlez_macros::sql`
  --> crates/db/src/query.rs:66:32
   |
66 |                   let sql_stmt = $crate::sqlez_macros::sql!($($sql)+);
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: crates/db/src/kvp.rs:21:5
   |
21 | /     query! {
22 | |         pub async fn write_kvp(key: String, value: String) -> Result<()> {
23 | |             INSERT OR REPLACE INTO kv_store(key, value) VALUES ((?), (?))
24 | |         }
25 | |     }
   | |_____- in this macro invocation
   |
   = note: import resolution is stuck, try simplifying macro imports
   = note: this error originates in the macro `query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot determine resolution for the macro `$crate::sqlez_macros::sql`
   --> crates/db/src/query.rs:171:28
    |
171 |               let sql_stmt = $crate::sqlez_macros::sql!($($sql)+);
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: crates/db/src/kvp.rs:15:5
    |
15  | /     query! {
16  | |         pub fn read_kvp(key: &str) -> Result<Option<String>> {
17  | |             SELECT value FROM kv_store WHERE key = (?)
18  | |         }
19  | |     }
    | |_____- in this macro invocation
    |
    = note: import resolution is stuck, try simplifying macro imports
    = note: this error originates in the macro `query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot determine resolution for the macro `sql`
  --> crates/db/src/db.rs:29:43
   |
29 | const DB_INITIALIZE_QUERY: &'static str = sql!(
   |                                           ^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `sql`
  --> crates/db/src/db.rs:25:51
   |
25 | const CONNECTION_INITIALIZE_QUERY: &'static str = sql!(
   |                                                   ^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `sql`
 --> crates/db/src/kvp.rs:6:7
  |
6 |     &[sql!(
  |       ^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

For more information about this error, try `rustc --explain E0463`.
error: could not compile `db` (lib) due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: zed-editor-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
zed-editor - exit status 4

**Comment by teynav** [comment]
The package zed-editor although present is not `buildable` yet, Please read  pinned comment on https://aur.archlinux.org/packages/zed-editor
Track progress of linux package here https://github.com/zed-industries/zed/issues/7015
