### ISSUE TITLE
Assistant: Claude API support

### ISSUE THREAD

**Issue by kosswald** [zed-industries/zed#8914]
### Check for existing issues

- [X] Completed

### Describe the feature

With the release of Claude 3 Opus, it advertises the best coding assistant performance available today. Would be nice to be able to use different APIs with Zed

https://www.anthropic.com/api

**Comment by kosswald** [comment]
Also being discussed in https://github.com/zed-industries/zed/issues/6708

**Comment by BryanJBryce** [comment]
Just playing with the free model it's _very_ impressive

**Comment by jaanli** [comment]
Major +1 on this, would help switch from VS code :)

**Comment by liam-k** [comment]
Yes please! although I would probably rename this issue to "make custom assistant APIs possible".  Because who knows what the next best LLM will be?

**Comment by elaminy** [comment]
YES claude 3 opus has been unmatched in terms of context length!

**Comment by lessless** [comment]
I'm not going back to ChatGPT anytime soon, so Claude support is very desired feature

**Comment by noozo** [comment]
+1

**Comment by windhorn** [comment]
I'm looking forward to Claude3's support!

**Comment by jaanli** [comment]
Here's the best that's available now of how I'm coping: https://colab.research.google.com/github/jaanli/language-model-notebooks/blob/main/notebooks/getting-started.ipynb

**Comment by JosephTLyons** [comment]
Claude is available in Zed [v0.136.0-pre](https://zed.dev/releases/preview/0.136.0).

**Comment by jaanli** [comment]
Yay! Thanks so much @JosephTLyons !!!

**Comment by jaanli** [comment]
@as-cii - is there more documentation or a way to check whether Claude or `GPT4o` is set? 

I can't figure out the way to add the `ANTHROPIC_API_KEY` command line variable.

Has anyone gotten Claude working in Zed with their API key?

**Comment by rafaelbiten** [comment]
Same here. I've been trying to set an open API key to work with `GPT4o` within Zed and I can't get it work. It keeps saying: `Failed to connect to OpenAI API: The model 'gpt-40' does not exist or you do not have access to it.`

**Comment by as-cii** [comment]
> @as-cii - is there more documentation or a way to check whether Claude or `GPT4o` is set?
> 
> I can't figure out the way to add the `ANTHROPIC_API_KEY` command line variable.
> 
> Has anyone gotten Claude working in Zed with their API key?

Hey @jaanli, you should be able to set it in your shell rc file or by launching zed via the command line:

```
ANTHROPIC_API_KEY=xyz zed /path/to/project
```

Make sure you set this in your `settings.json`:

```json
"assistant": {
    "version": "1",
    "provider": {
      "name": "anthropic"
    }
  }
```

------------------------------

> Same here. I've been trying to set an open API key to work with `GPT4o` within Zed and I can't get it work. It keeps saying: `Failed to connect to OpenAI API: The model 'gpt-40' does not exist or you do not have access to it.`

@rafaelbiten: it seems like you're misspelling `gpt-4o` (`0` vs `o`)?

**Comment by rafaelbiten** [comment]
Sorry, I just misspelled that in my initial message. Do I have to setup the assistant in the `settings.json` file? I tried resetting the key a few times. Also, just want to confirm one thing. The instructions say:

> Make sure your OpenAI account has credits.

Is that the case if we're subscribed to ChatGPT Plus? If it is, then that's my problem...

**Comment by maxmckenzie** [comment]
Ok so just for anyone else that needs a reference of how to do this. You dont need to add the ANTHROPIC_API_KEY and launch it via the command line.

you can just add these assistant settings as @as-cii says
```json
"assistant": {
    "version": "1",
    "provider": {
      "name": "anthropic"
    }
  }
```

Then when you save the settings (cmd+s) the assistant panel will pop open and ask you to add your API key. Which you need to get from here https://console.anthropic.com/settings/keys

Even if you pay for Claude pro, you will still have to pay for additional credits to use it via the API. Which you can do here https://console.anthropic.com/settings/plans

This confused the hell out of me. So hopefully someone else finds this comment useful.

**Comment by maxmckenzie** [comment]
I've added the above instructions to the documentation https://github.com/zed-industries/zed/pull/13765
