### ISSUE TITLE
Missing apt dependencies 

### ISSUE THREAD

**Issue by AeroBliss** [zed-industries/zed#8930]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Follow the [building zed for Linux instructions](https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_linux.md), skipping over the backend dependencies section.
2. Run `cargo run`
3. Get "error occurred: Failed to find tool. Is `c++` installed?"
4. Install `g++`. Remove `clang` if installed, or change `c++` command alias to `g++`.
5. Run `cargo run`
6. Get a huge wall of text, and at the end of that wall of text:
"/usr/bin/ld: cannot find -lstdc++: No such file or directory
          collect2: error: ld returned 1 exit status"
7. Install `libstdc++-12-dev`
8. Run `cargo run` (successfully)

### Environment

I am unable to get the command palette open.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by AeroBliss** [comment]
#8622 related

**Comment by phromo** [comment]
I still get this error on Ubuntu 23.04. `clang` is installed because `script/linux` installs it.
