### ISSUE TITLE
linux x11: Input breaks after opening file dialog

### ISSUE THREAD

**Issue by Waqar144** [zed-industries/zed#8931]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Input breaks if you:

1. Create new file
2. Hit `Ctrl + O`, keep it pressed, when the dialog appears, release
3. Close the dialog
4. Try to type something -> You get nothing

The input event handling seems to be broken.

### Environment

Operating System: Manjaro Linux
KDE Plasma Version: 5.27
Qt Version: 5.15.11
Kernel Version: 6.6.10-1-MANJARO (64-bit)
Graphics Platform: X11

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
This seems to have been fixed int he last three months. Please let me know if you can still reproduce.
