### ISSUE TITLE
Automatic indentation wrong when deleting lines

### ISSUE THREAD

**Issue by sixhobbits** [zed-industries/zed#8942]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**What I did**

if I have the following Python script 

```
if True:
    if True:
        pass
    print("Useless line")
else:
    pass
```

I put my cursor on the print statement in line 4 and pressed `dd` to delete the line.

**What I expect**

The line is deleted and other lines remain the same

**What happens**

The following line `else` is indented one level, to match the inner if above. This causes a syntax error on the last line as they are both at the same level.

https://i.ritzastatic.com/images/a572d1065ec14d55bbc91cc2dd75b7e5/zed.gif

### Environment

```
Zed: v0.125.1 (Zed Preview)
OS: macOS 14.0.0
Memory: 64 GiB
Architecture: aarch64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://i.ritzastatic.com/images/a572d1065ec14d55bbc91cc2dd75b7e5/zed.gif

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment]
Somewhat related #5194

**Comment by osiewicz** [comment]
It looks like indent is preserved across deletion, as in `else` gets the same indent as the line that was just deleted:

![image](https://github.com/zed-industries/zed/assets/24362066/a449c201-a578-48e9-8f77-1c6fee3db874)
