### ISSUE TITLE
New python modules require editor restart

### ISSUE THREAD

**Issue by Yu266426** [zed-industries/zed#8960]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

When a new python file is created, I am unable to get the editor to recognize the module without restarting Zed.

This might have to do with Pyright, I am unsure.

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/75224008/25ffea8c-3cda-489d-bf48-66a03f62c3be

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by failable** [comment]
Or restart LSP only.

**Comment by Moshyfawn** [comment]
Potentially related #7296

**Comment by JosephTLyons** [comment]
In the past, I've made the assumption that this was just a pyright deficiency, but I'm going to throw this on the project board for next week's quality week and have someone more qualified than I see if there's anything we can do on our end - even if we need to put in a hack.

**Comment by osiewicz** [comment]
This looks to be a Pyright issue indeed; we properly notify a language server about path changes, yet it doesn't react.
Oddly enough, when I've set `PYRIGHT_PYTHON_DEBUG` environment variable to get LSP logs, the whole thing started working. weird.

**Comment by JosephTLyons** [comment]
Are you saying that new modules are being recognized while in debug mode? If there are no performance issues with it, I wonder if we can just stay in debug mode. Others may not agree, but I think I'm for putting in a hack here to get this to work, since I hope to be rid of Pyright somewhere down the line anyway. That being said, the issue of relying on some weird side effect is that it might go away at any moment.

**Comment by JosephTLyons** [comment]
@osiewicz and I double checked and it seems like pyright is currently

- resolving imports to newly-added local files
- resolving imports to  newly-added dependencies, if you have a `pyrightconfig.json` file properly configured and added

The version of pyright listed in `~/Library/Application Support/Zed/languages/pyright/package.json`  is `^1.1.320`

Is anyone else able to reproduce the original issue here? If not, we will close it out.
