### ISSUE TITLE
Treating Vue template prop binding and mustache text interpolation as JS/TS syntax (for highlighting)

### ISSUE THREAD

**Issue by rev4324** [zed-industries/zed#8989]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great if Zed would treat Vue prop bindings with `:prop` syntax and text interpolation mustache syntax `{{ }}` as JS/TS. Here's a little comparison of Zed and Neovim with tree-sitter in that regard to demonstrate what I mean:

neovim:
<img width="1549" alt="image" src="https://github.com/zed-industries/zed/assets/69842744/e2eba280-d64b-4b38-bbd0-2384dd3e3cc2">

Zed:
<img width="1283" alt="image" src="https://github.com/zed-industries/zed/assets/69842744/3d736270-c42a-4321-b2e4-8a8e5a30ae37">

As you can hopefully see, in neovim `:prop` props are using `member_expression` nodes, while in Zed all attributes are treated equally - with `quoted_attribute_value` nodes. There are also other instances where this JS syntax highlighting would be useful and is already there in nvim and vscode - like `v-for`, `v-if` and other `v-` directives or aformentioned mustache text interpolation `{{ }}` syntax.

### If applicable, add mockups / screenshots to help present your vision of the feature

As in the description, Vue syntax highlighting working like in Neovim.
<img width="1549" alt="image" src="https://github.com/zed-industries/zed/assets/69842744/cba66cfc-104f-40b2-81ec-016fdc3cf8b9">

**Comment by Amstrong** [comment]
100%
