### ISSUE TITLE
Markdown preview skips everything after newlines

### ISSUE THREAD

**Issue by Dagunov** [zed-industries/zed#8990]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When working with markdown, adding new lines with two spaces or `\` results in preview not rendering anything after that newline in the same section.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="900" alt="image" src="https://github.com/zed-industries/zed/assets/24490298/e88656db-6214-44eb-a1c8-298e51d8ac70">

**Comment by bennetbo** [comment]
https://github.com/zed-industries/zed/blob/d450fde1edac685f7a9e5ce1046d6551a0983169/crates/markdown_preview/src/markdown_parser.rs#L194

It looks like the insertion of the line break is missing here. If I insert `\n` there, the preview displays correctly. I'm not sure if this breaks other stuff, I'll look into it.

**Comment by raashidanwar** [comment]
Hi @bennetbo,

I would be happy to pick this up.
