### ISSUE TITLE
Contradicting Recent Projects cmd+enter behavior

### ISSUE THREAD

**Issue by raphi011** [zed-industries/zed#8991]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hey! Noticed this just now while trying out the new release: the release notes mention that cmd+enter will open the window in a new window

<img width="636" alt="Screenshot 2024-03-07 at 09 11 03" src="https://github.com/zed-industries/zed/assets/1379944/003851b4-dd9f-458b-b838-3b93f594a931">

but the inline hint says (and does) the opposite.

<img width="569" alt="Screenshot 2024-03-07 at 09 11 18" src="https://github.com/zed-industries/zed/assets/1379944/acc9680e-e703-4c84-8f95-0628b6dd7182">

Not sure what the intended behavior is?

### Environment

Should be the same everywhere

**Comment by SomeoneToIgnore** [comment]
Sorry for that, had been doing sort of an A/B test with Zed Preview.
We wanted to make "open in this window" as a new default, as VSCode does and some people requested, but that part did not work well with our collab projects and established habits of other group of people.

So now, there's the same "open in new window by default" strategy that Zed uses for projects, but with much more customization options: first of all, all those `cmd-enter` things enabled by default and the new keybindings options:
```
// Change the default action on `menu::Confirm` by setting the parameter
// "alt-cmd-o": [
//     "projects::OpenRecent",
//     {
//         "create_new_window": true
//     }
// ]
```

that allow setting the defaults however the user wants.
Maybe we should make this default to VSCode keymap, but it's up to the community I'd say.
