### ISSUE TITLE
Add ability to only run `code_actions` on format, no formatter

### ISSUE THREAD

**Issue by mrnugget** [zed-industries/zed#8992]
### Check for existing issues

- [X] Completed

### Describe the feature

See: https://github.com/zed-industries/zed/issues/4325#issuecomment-1981161243

Essentially: users want to only format their code using ESLint (or other language server's code actions).

Problem: we have `code_actions_on_format`, which allow you to run code actions when formatting, but if you turn formatting off (`formatter: "off"`) then those won't get run either.

So we have a few options on how we want to enable this:

1. `"noop"`-formatter:

```json
{
  "TypeScript": {
    "formatter": "noop", // <-- new
    "code_actions_on_format": {
      "source.fixAll.eslint": true
    }
  }
}
```

2. `code_actions` as a formatter:

```json
{
  "TypeScript": {
    "formatter": {
      "code_actions": {
        "source.fixAll.eslint": true
      }
    }
  }
}
```

3. Introduce `code_actions_on_save` (save!):
```json
{
  "TypeScript": {
    "formatter": "off",
    "code_actions_on_save": {
      "source.fixAll.eslint": true
    }
  }
}
```

I'm not super happy with any of them, but might lean towards `noop` the most, since it's the simplest and doesn't introduce any new concepts and orderings. But it does feel weird to have a `noop` formatter and then run code actions? So from that perspective, (2) seems good. Problem with (2) is that it's unclear how it behaves when code actions on format are also set? Do we run it twice?

### If applicable, add mockups / screenshots to help present your vision of the feature

noop

**Comment by klaframboise** [comment]
This seems to be a fine workaround for now

settings.json
```json
"languages": {
  "JavaScript": {
    "formatter": {
      "external": {
        "command": "cat << EOF",
        "arguments": []
      }
    },
    "code_actions_on_format": {
      "source.fixAll.eslint": true
    }
  }
}
```

**Comment by Skandinavchik** [comment]
It works but it throws a formatting failed message.
<img width="655" alt="Screenshot 2024-03-25 at 11 59 52" src="https://github.com/zed-industries/zed/assets/12948487/61df5425-792d-4dc8-88da-a3f3e58f2346">
<img width="697" alt="Screenshot 2024-03-25 at 12 02 18" src="https://github.com/zed-industries/zed/assets/12948487/4f0ba95d-7775-4169-8ec6-43dd091c5131">
