### ISSUE TITLE
Page up/page down does not move the cursor

### ISSUE THREAD

**Issue by andrewfan** [zed-industries/zed#8993]
### Check for existing issues

- [X] Completed

### Describe the feature

In Vscode, PageUp/Down also moves the cursor; however, in Zed, it stays in the same position.

**Comment by andrewfan** [comment]
@Moshyfawn in the editor. 
Just open any long file and use PageUp/Down key on the keyboard. 
When I do the same in Vscode the caret moves to the end of the page if I click PageDown or up if I click PageUp

**Comment by sanbox-irl** [comment]
To defend this decision, if pageup/pagedown *doesn't* move the cursor, it has much less utility, since I'll need to manually move the mouse, at which point, i might have well have just scrolled.

On a personal level, I see page up/down as a "big arrow key", which should work just like the arrow keys but over many lines (ideally the vertical size of the screen, though tbth, a set amount like 80 is fine too)

**Comment by bennetbo** [comment]
This is possible using the `editor::MovePageDown`/`editor::MovePageUp` actions. 
The default keybinding for this is `shift-pageup`/`shift-pagedown`, but you can reconfigure it to use `pageup`/`pagedown` by default using the following keymap.json overrides:
```json
[
  {
    "context": "Editor",
    "bindings": {
      "pageup": "editor::MovePageUp",
      "pagedown": "editor::MovePageDown"
    }
  }
]
```

What I don't think is possible to select text when holding shift and using pagedown/pageup, like this (using vscode here):

https://github.com/zed-industries/zed/assets/53836821/8de48b7e-3b61-4e4e-99ab-9403d4be26b0

**Comment by sannysanoff** [comment]
Just now I pasted excerpt of a log file for keeping specific rare error codes in my work: few interesting lines and few pages of not interesting lines between them, with intent to leave only interesting. I normally use pgup/pgdown with shift to select large blocks to delete (adjusting selected block with up/down where necessary). Can't do this in zed ;(

**Comment by andrewfan** [comment]
thanks @bennetbo, this solves the issue

**Comment by israrwz** [comment]
i achieved the desired effect with the following in my `keymap.json` file:

```
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-u": ["workspace::SendKeystrokes", "1 5 k z z"],
      "ctrl-d": ["workspace::SendKeystrokes", "1 5 j z z"]
    }
  }
]
```

essentially it's mapping `ctrl-u` with 15 `up` keys followed by `z z` keys to center the scrolled to line in the screen. obviously 15 lines works with my font settings, you should adjust accordingly.

**Comment by benswift** [comment]
> Is this for when you are navigating in the editor or terminal?

@Moshyfawn is it possible to do page up/down in the terminal (without moving the cursor)? Because I haven't found a way to do it, and it'd be _really_ handy not to have to reach for the mouse to scroll back through terminal output that has gone off-screen.
