### ISSUE TITLE
vim: it & at won't work when cursor is positioned over/before tag

### ISSUE THREAD

**Issue by vricop** [zed-industries/zed#8994]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The new it/at vim-like won't work as expected. It only works if you're inside a tag.

### Environment

macOS Sonoma 14.2.1 MacBook Pro 14" M1

**Comment by ConradIrwin** [comment]
@vricop To clarify the behavior you're missing is when your cursor is inside the tag itself? `<tag|name>boo</tagname>`, or are there more edge cases?

Either way, happy to work together on a fix for this: https://calendly.com/conradirwin/pairing

**Comment by vricop** [comment]
> @vricop To clarify the behavior you're missing is when your cursor is inside the tag itself? `<tag|name>boo</tagname>`, or are there more edge cases?
> 
> Either way, happy to work together on a fix for this: https://calendly.com/conradirwin/pairing

@ConradIrwin In neovim/vim all **textobjects** will work if these conditions are met: your cursor is either before, hover or inside the tag. Let’s say we wanna change some text inside a tag. Entering `cit` (Change Inside Tag) in normal mode will work:

`|<strong>Some text</strong>`
`<str|ong>Some text</strong>`
`<strong>Some |text</strong>`

Right now it only work for the third scenario.

**Comment by weartist** [comment]
@ConradIrwin If we want to have the same effect as vim, I think we might need to pass the `selection` over, and a single point is not enough to make those deal, so we change the `object.range` upstream method of the object to receive the `selection`, and then for the other objects, we still pass `selection.head` to execute it, for html, we pass `selection`, do you think that is possible?

**Comment by ConradIrwin** [comment]
Makes sense, though we probably need the same behavior for all objects, so passing a range instead of a point always makes sense to me.
