### ISSUE TITLE
Double-clicking the tab bar of the Terminal panel should open a new Terminal instead of a new buffer

### ISSUE THREAD

**Issue by hmemcpy** [zed-industries/zed#9003]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In #8431, a feature to open a new buffer when double-clicking on the tab area was added. Unfortunately, as a consequence, double-clicking the tab bar in a Terminal panel opens a new buffer. Instead, it should open a new Terminal tab.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![2024-03-07 14 30 33](https://github.com/zed-industries/zed/assets/601206/e272a4a9-a14f-44a7-aa11-e9163eab5fea)

**Comment by hmemcpy** [comment]
@maxdeviant it seems that this functionality should not be coded directly on the drag_area of the tab bar, but perhaps configured externally, by exposing the tab bar as a property of the Pane structure, allowing registering a custom handler. WDYT?

**Comment by maxdeviant** [comment]
> by exposing the tab bar as a property of the Pane structure, allowing registering a custom handler

I'd need to take a closer look at the code to understand what's going on, but I don't think is a direction we want to go in.
