### ISSUE TITLE
Tooltip flicker when other editor panel is used in zoom

### ISSUE THREAD

**Issue by jnsprnw** [zed-industries/zed#9010]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open editor with two panels
2. Have right panel active with cursor in it
3. Hover over left left panel to trigger tooltip
4. Press Shift+Esc to trigger zoom for (active) right panel
5. The tooltip from the left panel starts to flicker
6. Sometimes, a tooltip from the zoomed-in panel also starts to flicker

https://github.com/zed-industries/zed/assets/5550700/14ccd7dd-148b-4463-b9b8-06870ba999c7

### Environment

Zed 0.125.3
MacOS 14.3.1 (23D60)
M2 Pro
The whole editor is used in full screen

**Comment by greduan** [comment]
Can't reproduce in same way, because I don't have any splits, but during Slack screenshare today I was experiencing this issue of the tooltip flickering like this.
