### ISSUE TITLE
zed.dev/features#language_servers 'and more' link is a 404

### ISSUE THREAD

**Issue by ernstki** [zed-industries/zed#9011]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* visit https://zed.dev/features#language_servers (via https://zed.dev/faq, "Where are language servers stored?" section)
* click "and more"
* link to https://github.com/zed-industries/zed/tree/main/crates/zed/src/languages is currently an Error 404

### Environment

Firefox (latest) on macOS (irrelevant)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

The path `crates/zed/src/languages`—the 404 mentioned above—probably corresponds to `crates/language` now. I didn't have an in-depth look at the code to confirm. For a non-Rust programmer, there's nothing much of use there anyway on the top of "show me a list of all the languages Zed supports."

I recommend linking to https://github.com/zed-industries/zed/tree/main/docs/src/languages instead, provided that's kept up-to-date as new languages are added.

Lastly: curiously, https://zed.dev/features does not seem to be linked from the footer, or a prominent place on the home page. Just once at the end of the "In the box" section—easy to miss. It's only linked _once_ from the FAQ page. It seems like `/features` deserves a lot more visibility!

<img width="923" alt="Screenshot of the number of occurrences of '/features' on the zed.dev home page" src="https://github.com/zed-industries/zed/assets/4009681/597e9f2a-05e3-413b-8e91-9225044e0a26">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_n/a_

**Comment by ernstki** [comment]
@JosephTLyons s'all good. Thanks for having a look.

**Comment by JosephTLyons** [comment]
This has been resolved at some point since this issue was filed - thank you!

**Comment by ernstki** [comment]
@JosephTLyons https://zed.dev/features is still practically an orphan, referred to (as far as I can tell) only by the language servers section of the FAQ.

It seems like it really deserves to be linked prominently from the main page, from the nav bar, or at least under the "Product" heading in the footer.

Open a new issue for this?
