### ISSUE TITLE
Collaboration features don't work

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9021]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Seeing "offline" Sign In button while being signed into GitHub.

Can't join channel chats.

### Environment

Zed: v0.126.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[INFO] add connection to peer
[INFO] waiting for server hello
[INFO] set status on client 57425: ConnectionError
[ERROR] failed to connect timed out waiting on hello message from server
[INFO] set status on client 57425: ReconnectionError { next_reconnection: Instant { tv_sec: 579445, tv_nsec: 992402500 } }
[ERROR] crates/channel/src/channel_buffer.rs:197: not connected

**Comment by JosephTLyons** [comment]
Are you still seeing this @Moshyfawn?

**Comment by Moshyfawn** [comment]
Seems to be fixed now

**Comment by Moshyfawn** [comment]
I saw several reports on Discord as well as a few people connecting in the collab channel, so it could be that someone was "just testing in production" lmao Anyway, all good.
