### ISSUE TITLE
'See the configuration' link in language docs broken

### ISSUE THREAD

**Issue by tjamesmac** [zed-industries/zed#9022]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There is a broken link on the [python language configuration](https://zed.dev/docs/python) page under the code formatting header

> See the [configuration](https://zed.dev/configuration/configuring-zed.md) documentation for more information.

This issue also applies to the javascript page

### Environment

N/A

**Comment by JosephTLyons** [comment]
Thanks for letting us know, @tjamesmac! The fix should be live now.
