### ISSUE TITLE
Tooltip obscures modals

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9045]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The tooltip is displayed above the command palette, obscuring the visibility of the items.

The problem is only reproducible when the **tooltip position is above the syntax element** that produces it, as shown in the screenshot. If the tooltip is anchored to the bottom of the syntax element, the tooltip is not displayed above the command palette.

The same applies to project symbols and file finder modals.

### Environment

Zed: v0.126.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1394" alt="zed-tooltip" src="https://github.com/zed-industries/zed/assets/16290753/879614be-00ce-4383-a9e6-e3293e29db73">

**Comment by Moshyfawn** [comment]
The issue is related to tooltip stacking in #8276 overall, though not quite a duplicate.

**Comment by notpeter** [comment]
It appears tooltips are now dismissed when the command palette is launched, so I think it is no longer possible to trigger this behavior.  If I'm incorrect, happy to reopen.
