### ISSUE TITLE
Freeze when scrolling a large file (large file performance)

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#9055]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open a large file it opens relatively quickly, but as soon as I scroll it scrolls for a couple of lines and then I get the spinning beach ball for several seconds and then it repeats.
After a couple rounds Zed just freezes entirely.
My file is ~170MB, 3.1 million lines (CI logs 🙈)

A ~few weeks ago this was no problem. I could easily scroll to the bottom of the file to find what I was looking for.

### Environment

Zed: v0.126.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
@mrnugget Do you think this could be a similar cause to what you originally reported in #8434?

**Comment by mrnugget** [comment]
I thought so too at first, but I can't reproduce #8434 anymore with a release build. And it sounds like what we're looking at here is a regression, which makes me wonder whether this is something new.

**Comment by mrnugget** [comment]
I can't reproduce this with a plain-old `*.txt` file. I downloaded logs of our CI here and concatenated them into a 474MB file with 2.9mil lines and I can scroll through that smoothly:

https://github.com/zed-industries/zed/assets/1185253/59a05e2e-a3e2-4aaf-ac8e-1fd0b4760b32

Did it look different for you? Did you, for example, change the language so it gets interpreted as something other than text?

**Comment by mrnugget** [comment]
Another question: what specs does your laptop have? Low battery? Connected to power?

---

Another note: someone on Twitter [is saying](https://twitter.com/shaneikennedy/status/1768220554895479165) that on a 2016 MBP with 2 cores, scrolling gets stuttery

**Comment by ramyak-mehra** [comment]
Hey, here from twitter I also experience very similar issues, but not in scrolling when opening a file but the moment i searched for something the editor becomes stuttery or sometimes straight out hang. Usually happens when the search item has a lot of occurances.
I am on `M3 Pro 18GB`. Zed build `0.125.3`
The file size is around `235MB`. I tested it with `112MB` file similar results
`~/Library/Logs/Zed/Zed.log` logs
<img width="1171" alt="Screenshot 2024-03-14 at 6 09 17 PM" src="https://github.com/zed-industries/zed/assets/55009050/322da122-0aea-4b47-8459-6d04115f89bf">
Let me know if u need any more info in reproducing this, I am not sure if i can share the exact file publicaly but if u can't reproduce it I can spend some effort creating a dummy verison of my file.

**Comment by mrnugget** [comment]
Hey @ramyak-mehra, thanks for reporting. 

> the moment i searched for something the editor becomes stuttery

Do you mean the buffer search?

**Comment by ramyak-mehra** [comment]
yes

**Comment by mrnugget** [comment]
@ramyak-mehra I'm not sure if I can reproduce. Here, that's a 300k line file and I search in it. It doesn't stutter or hang

https://github.com/zed-industries/zed/assets/1185253/d8e61ece-6701-408b-8fad-e98bd8efea31

Can you give me a screenshot of what it looks like for you? Or how to reproduce?

**Comment by ramyak-mehra** [comment]
This particular file was 950K but like i mentioned earlier it happened on the smaller file also 

https://github.com/zed-industries/zed/assets/55009050/174b9a7b-ca02-4e83-b991-f794ac9a892c

**Comment by mrnugget** [comment]
@ramyak-mehra thanks so much! You're helping a ton! 

Question: can you turn off the scrollbar and see if it goes away? In your settings:

```json
  "scrollbar": {
    "show": "never"
  },
```

**Comment by ramyak-mehra** [comment]
turning the scrollbar off fixed the stutter.

**Comment by mrnugget** [comment]
Thanks!

**Comment by nathanael-ruf** [comment]
> @N8th8n8el can you confirm that disabling the scrollbar "fixes" the issue?

Interestingly I can't reproduce this anymore without the search open which leads me to believe that I may have had it open when I reported this.
So
- scrolling the file without search but with scrollbar works fine.
- scrolling the file with search and scrollbar is unusably slow and the rendering is broken (see screenshot).
- without the scrollbar searching is fine
![Screenshot 2024-03-21 at 12 04 01](https://github.com/zed-industries/zed/assets/104262550/d9985d2b-fa2d-49f9-9a46-df2653202584)

**Comment by nathanael-ruf** [comment]
![Screenshot 2024-03-21 at 12 05 18](https://github.com/zed-industries/zed/assets/104262550/3443b94f-1449-43b9-a129-5a38d85d968d)

The file looks something like that and I searched for `buildFor`.

**Comment by nathanael-ruf** [comment]
What I noticed today (with an even larger file, 300mb, ~6 million lines) is that the scrolling with a trackpad isn't smooth anymore. It just abruptly stops when I lift my fingers from the trackpad.

**Comment by mrnugget** [comment]
That seems related to the scrollbar issues, right? I just opened a 450mb file and could smoothly scroll through it with the trackpad and it kept scrolling after lifting finger.

**Comment by osiewicz** [comment]
@nathanael-ruf do you experience this scrolling behaviour only in a specific part of a file? E.g. does it happen at the start of a file, or is scrolling smooth there?

**Comment by iwansyahp** [comment]
I encounter this problem when using Zed opening a `*.txt` file on Arch Linux.

Here is the screenshot of `journalctl` on my system. 

![image](https://github.com/user-attachments/assets/fb66dadd-072b-44f8-b30c-eed172eb3b27)

File size is: 6.7MB
Number of lines: 39791
