### ISSUE TITLE
Recent Ruby changes add more keystrokes for me: class names and symbols

### ISSUE THREAD

**Issue by kaspth** [zed-industries/zed#9069]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After some recent Zed updates, I'm getting different behavior when I try to edit class names and symbols.

Today I was trying to type out `ActiveModel::Model`, but had a misspelling like `ActiveModel::Kod` and as I went to hit to opt+delete to correct, Zed deleted the whole thing instead of just `Kod`. I've been used to `::` being considered a word boundary previously.

Double-clicking on `ActiveModel::Model` or `ActiveModel::Kod` also selects the whole namespace as opposed to just a piece.

The same thing happens for symbols, so double-clicking on `:some_symbol` or `some_symbol_keyword:` in `def some_method(some_symbol_keyword:)` now includes `:` in the select.

I find both these changes quite frustrating as a user because it reduces my ability to navigate around Zed with a keyboard.

As a bit tough to recall when these things changed, but I'm guessing they're related to the recent `highlights.scm` changes.

cc @mrnugget

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

**Comment by mrnugget** [comment]
Hey @kaspth! Very interesting. I guess the only relevant change in recent weeks was this one: https://github.com/zed-industries/zed/commit/3921259b6c054db46245a6d13b95add0d5dc3d83. That was to fix https://github.com/zed-industries/zed/issues/7819 but maybe I overdid it and we shouldn't include `:` here.

If you want to run Zed from source and give it a short: simply remove `:` from here https://github.com/zed-industries/zed/blob/a550b9cecf1f889c67e1c5c5e114880b84d07d7b/crates/languages/src/ruby/config.toml#L40 and `cargo run`.

If not, I'll give it a shot next week.

Thanks for reporting!

**Comment by kaspth** [comment]
@mrnugget ah thank you! I'll try to run it from source, but that commit does look like it could be it.

From an editing standout, I have liked that those characters weren't part of the word. But yeah, if autocomplete doesn't work without them, then…

Well, I'll try to play around with this first!

**Comment by mrnugget** [comment]
I have a branch in which I remove the `:` and after playing around with it, here's what I think:

It restores some of the old behavior: `w` in Vim mode will jump to `::Model` (like you wanted @davekaro), double-clicking on `ActiveRecord` in `ActiveRecord::Base` will only select `ActiveRecord`, ...

The problem is that it breaks auto-complete for symbols, because now `:` isn't considered part of the word anymore. Investigating.

**Comment by mrnugget** [comment]
Fix is here: https://github.com/zed-industries/zed/pull/9170

Short version: restores old word boundaries, fixes completion to work with those word boundaries.

**Comment by kaspth** [comment]
@mrnugget woot, that's so cool! Thank you!
