### ISSUE TITLE
Support for code _snippets_

### ISSUE THREAD

**Issue by gm0stache** [zed-industries/zed#9071]
### Check for existing issues

- [X] Completed

### Describe the feature

i as a developer would like to insert custom code scaffoldings while editing.
the feature can generally be described as the existing one in VS Code: https://code.visualstudio.com/docs/editor/userdefinedsnippets

### If applicable, add mockups / screenshots to help present your vision of the feature

the feature can generally be described as the existing one in VS Code: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by Moshyfawn** [comment]
Duplicate of
- #4611

Be sure to +👍 the other issue to show your interest.
