### ISSUE TITLE
Move lsp-less grammars our of Zed repo to extensions

### ISSUE THREAD

**Issue by SomeoneToIgnore** [zed-industries/zed#9072]
### Check for existing issues

- [X] Completed

### Describe the feature

Now, Zed source code has the following tree-sitter grammar dependencies to support the corresponding languages:

- [ ] bash
- [ ] glsl
- [ ] nix
- [ ] markdown
- [ ] proto
- [ ] scheme
- [ ] racket

all of them do not have any LSP server adapter associated and may be already moved into https://github.com/zed-industries/extensions to reduce code Zed editor compilation speed and resource usage.

(there are also go and terraform related grammars that have no language server adapter, but they are part of a bigger language support idea, so let's not remove them yet)

**Comment by SomeoneToIgnore** [comment]
Removal example: https://github.com/zed-industries/zed/pull/9025

**Comment by Entjic** [comment]
hi, first time contributor here

just for clarification, in https://github.com/zed-industries/extensions you reference the actual extension repos via git submodules. Now should all the languages listed in your issue be moved into their own extension repo or just one for all of them? I am assuming the first option?

**Comment by SomeoneToIgnore** [comment]
Hey, yes, separate submodules and no repetition sounds about right.
This is the first time such migration happens, so no good path is prepared yet, and there could be some questions along the way.

**Comment by SomeoneToIgnore** [comment]
The new plans are to move all things with LSP at once, as we're closing the state where extensions will be able to provide LSP-related functionality: https://github.com/zed-industries/zed/pull/9288#issuecomment-1995906541
