### ISSUE TITLE
Project Panel: Allow opening selected file with ➡️  (arrow key right)

### ISSUE THREAD

**Issue by gm0stache** [zed-industries/zed#9074]
### Check for existing issues

- [X] Completed

### Describe the feature

i think it would make keyboard navigation easier, when it would be possible to open a selected file in the _project panel_ with ➡️  (arrow key right).

please make sure that the vim equivalent (normal mode, `l`) works too. thanks!

**Comment by Moshyfawn** [comment]
You can already set up a custom keymap to implement the behaviour you describe.

```json
{
  "context": "ProjectPanel && not_editing",
  "bindings": {
    "right": "project_panel::Open"
  }
}
```

**Comment by gm0stache** [comment]
nice, thank you!
