### ISSUE TITLE
Multi window Zed loses focus

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9077]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Sometimes you click in one window, but cursor moves to another window instead

### Environment

Zed: v0.127.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
Seems like this issue #8735.

**Comment by JosephTLyons** [comment]
Yeah, that seems right to me^. I'll close this out in favor of that one.
