### ISSUE TITLE
Support shift-tab to Outdent.

### ISSUE THREAD

**Issue by charles-r-earp** [zed-industries/zed#9089]
### Check for existing issues

- [X] Completed

### Describe the feature

Preface to say that I just installed Zed (linux), and having really liked Atom, it looks wonderful. This is probably my one small gripe.

Currently tab works to add tabs, but shift tab does not remove tabs. 

Looking at the [keymaps](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-linux.json) (linux, macos is similar), it looks like shift tab maps to tab prev (whatever that means). What works is ctrl-[.
```
[
    {
        "context": "Editor",
        "bindings": {
            "tab": "editor::Tab",
            "shift-tab": "editor::TabPrev",
        }
    }
    // Bindings from VS Code
    {
        "context": "Editor",
        "bindings": {
            "ctrl-[": "editor::Outdent",
            "ctrl-]": "editor::Indent",
        }
    }
]
```
Is this intended behavior?

I tried creating a "keymap.json" file per the docs:
```
[
    {
        "context": "Editor",
        "bindings": {
            "shift-tab": "editor::Outdent",
        }
    }
]
```
But this doesn't have any effect. 

Minimally it would be nice to allow customizing this, potentially there is some reason that shift doesn't work. It seems odd that tab maps to indent, but outdent is requires a different set of keys entirely. Unless shift-tab is meant to map to some conflicting operation, I don't see why this can't work as expected.

**Comment by Moshyfawn** [comment]
This seems to be a Linux specific problem, as `shift-tab` outdents the line on MacOS with both VSCode and Atom keymaps.
