### ISSUE TITLE
Missing screen mode for crtc specified mode id

### ISSUE THREAD

**Issue by VitorRamos** [zed-industries/zed#9105]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Panic in the initialization on:

Thread "main" panicked with "Missing screen mode for crtc specified mode id" at crates/gpui/src/platform/linux/x11/client.rs:330:14
   0: Zed::init_panic_hook::{closure#0}
             at crates/zed/src/main.rs:596:29
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18

The first crtc may not be a valid one.

### Environment

Linux x11

**Comment by mikayla-maki** [comment]
I believe this has been fixed.
