### ISSUE TITLE
A setting to turn off Copilot when writing comments

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9133]
### Check for existing issues

- [X] Completed

### Describe the feature

Title

**Comment by notpeter** [comment]
See also:
- https://github.com/zed-industries/zed/issues/14372

Similarly I think it should similarly be possible to disable inline completions while in the Assistant, currently this requires disabling it by-language via Markdown.  Perhaps we should have multiple selectable areas to disable inline completions (comments, assistant panel; future: commit messages)
