### ISSUE TITLE
Searching within ignored files hangs forever

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9135]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"Searching within ignored files hangs forever - If I turn on Included ignored, search hangs and pegs the CPU (at 750%). I have to quit Zed to fix this. I have circular symlinks in my project; perhaps that’s causing this?"

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by mrnugget** [comment]
I don't think that's the problem, but it could be and it's a bug anyway:

https://github.com/zed-industries/zed/pull/9333

**Comment by mrnugget** [comment]
This could also improve performance here: https://github.com/zed-industries/zed/pull/9341

**Comment by ConradIrwin** [comment]
Some improvements shipped to 0.128.0-pre, closing this for now, but we should reopen on subsequent reports.
