### ISSUE TITLE
Drag and drop to arrange layout

### ISSUE THREAD

**Issue by thanhphuong163** [zed-industries/zed#9148]
### Check for existing issues

- [X] Completed

### Describe the feature

For now, I just see the terminal pane at the bottom of the window. I jus wish I could move it to the left or right of the window.

**Comment by Moshyfawn** [comment]
Is this what you're after?

https://github.com/zed-industries/zed/assets/16290753/e4452f9c-7fe2-45e8-9359-9b4a2fe64a45

**Comment by thanhphuong163** [comment]
Yes.

**Comment by Moshyfawn** [comment]
You can do this by dragging the Terminal window to the far right of the workspace.

![zed-right-pane](https://github.com/zed-industries/zed/assets/16290753/f203e31c-9641-4e0f-975f-ed67b05c08dd)

**Comment by JosephTLyons** [comment]
@thanhphuong163 - does this satisfy what you were looking for? Can we close this out, or is there something else you are missing?
