### ISSUE TITLE
Show "expanded" command when running tasks

### ISSUE THREAD

**Issue by claytonrcarter** [zed-industries/zed#9149]
### Check for existing issues

- [X] Completed

### Describe the feature

First off, tasks are *great*, and variables/contexts make them even better. Really phenomenal addition!

One quibble I have is that I can't see what is being run, though. For example, this task:
```json
    {
        "label": "phpunit (function)",
        "command": "vendor/bin/phpunit",
        "args": ["$ZED_FILE", "--filter", "$ZED_SYMBOL"]
    }
```

produces this output (in its entirety)
```
PHPUnit 9.6.16 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.432, Memory: 36.50 MB

OK (1 test, 13 assertions)
```

This is ... not wrong, but could lead to difficult debugging if a) my usages of the vars is incorrect, or b) I happen to run the wrong task, or c) I happen to rerun the wrong task, etc etc.

My suggestion is to start the output with the command being run, with variables expanded. For example
```diff
+Command: vendor/bin/phpunit /path/to/test/File.php --filter test_function_being_tested
 PHPUnit 9.6.16 by Sebastian Bergmann and contributors.
 ...
```

This would improve situational awareness (eg ability to confirm I ran the right test), and would also make sharing easier, eg if I wanted to copy this command into a chat, issue, documentation, etc.

**Comment by baldwindavid** [comment]
@claytonrcarter I had a [similar comment](https://github.com/zed-industries/zed/pull/8974#issuecomment-1983645016) the other day. The PR commented on there should help, but sounds like it's not too straightforward to display the command in the terminal. The eventual plan is to get there though.

**Comment by osiewicz** [comment]
I know this doesn't quite solve the problem, but you can also use `set -x; vendor/bin/phpunit`to see the full command.

I've had command expansion in UI in mind (to e.g. show labels with environment variables), but I worry that it may not be quite correct (we'd have to worry about .bashrc/it's shell equivalents in user shell); speed is also a bit of a concern. I'm not saying it's a bad idea by any means, it's just not straightforward.
