### ISSUE TITLE
Linux: Clicking ctrl-shift-p in Editor context doesn't open Command Palette, but does in File Explorer

### ISSUE THREAD

**Issue by TheRedXD** [zed-industries/zed#9155]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Clicking ctrl-shift-p in the Editor only moves the cursor up and makes a selection, but doesn't open the command palette.

Expected: Clicking ctrl-shift-p in basically any context should bring up the command palette.

Steps to reproduce:
1. Open up Zed (I'm on linux, so I just did `cargo run --release`)
2. Open up a project of some kind, and open up a file in it.
3. While focused on the Editor context, click ctrl-shift-p. You will notice, that it doesn't pop up the command palette.
4. Now click on empty space in the File Explorer, and press the same key combination. The command palette pops up.

I will also note there is a related issue, where at times, typing into Zed doesn't work, but key combinations do. However, I haven't been able to reproduce that issue reliably so far.

### Environment

Here's what the command returns:
Zed: v1.0.0 (Zed Dev)
OS: Linux 1.0.0
Memory: 29.3 GiB
Architecture: x86_64

However, I believe that might not be enough to diagnose the issue, therefore, I'm listing some more here:
```
thered@archbtw:Codebases/zed ‹faster-scrolling›$ neofetch
                   -`                    thered@archbtw 
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: TUF Gaming FX505DV_FX505DV 1.0 
               `+oooooo:                 Kernel: 6.7.9-zen1-1-zen 
               -+oooooo+:                Uptime: 12 hours, 58 mins 
             `/:-:++oooo+:               Packages: 1217 (pacman), 3 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080, 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 6.0.1 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: Vivid-Blur-Dark-Aurorae-6 
       -osssssso.      :ssssssso.        Theme: [Plasma], Vivid-Dark-GTK [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Vivid-Dark-Icons [Plasma], Vivid-Dark-Icons [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: konsole 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: Fira Code Retina 12 
  `+sso+:-`                 `.-/+oso:    CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
 `++:.                           `-/+/   GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
 .`                                 `/   GPU: NVIDIA GeForce RTX 2060 Mobile 
                                         Memory: 10550MiB / 30008MiB 

thered@archbtw:Codebases/zed ‹faster-scrolling›$
```
I am using SDDM as my display manager and KDE Plasma 6 as my Desktop Environment.
It is also important to note that I'm using X11, not Wayland, as Wayland gets quite buggy with multiple displays for me.

**Comment by TheRedXD** [comment]
> Would like to add the same happens for `Ctrl + B` and `Ctrl + P`. Also while `Ctrl + ~` shows the in built terminal, pressing it again doesn't close it. There may be other shortcuts but i haven't noticed any so far

I can confirm the same happens for me. Likely an issue with the keymap and not a programming error, it would be great if instead of trying to shove every single keybind under the sun into Zed (there will be conflicts and therefore I don't recommend something like that), there should be presets, where you could choose how you want your keybinds to be configured, and then customize them to your liking - ideally, there would be some kind of settings interface, instead of having to manually configure everything in a json file, such that it's more intuitive for the user. Also, settings should be accessible with a single click of a button, as well as your keybinds, because these things are a huge part of what makes development fast.

I think a settings button and a keybinds button would fit well here:
![image](https://github.com/zed-industries/zed/assets/56270596/904f3b47-ad39-4c9a-8b5e-cb94a02ed279)

instead of having to click on the dropdown and click Settings or whatever, or click the respective keybind for it, it should be accessible via both a keybind AND via a single click. Configuring the editor should be a charm, not a chore.

Quick mockup I made:
![Frame 1](https://github.com/zed-industries/zed/assets/56270596/67ad7009-c84b-4083-b10e-ac0aff66874a)
Spacing isn't perfect, but this is a mockup, so when actually implementing it, it'll be a lot easier to align everything.

![mockup_of_full_app](https://github.com/zed-industries/zed/assets/56270596/0c1c2f90-8b9d-493e-a6fc-7945c251df4d)
![mockup_of_full_app_another](https://github.com/zed-industries/zed/assets/56270596/675228e9-133a-499f-aee2-bca00d032668)

It's not perfect obviously, but I might make a feature request about this. I'll see.

**Comment by jansol** [comment]
See also #8491

**Comment by flukejones** [comment]
Unsure how related but the way I fixed this was to unmap a few related bindings in:
```
  {
    "context": "Editor",
    "bindings": {
      "ctrl-p": null,
      "ctrl-shift-p": null,
```

**Comment by TheRedXD** [comment]
> Unsure how related but the way I fixed this was to unmap a few related bindings in:
> 
> ```
>   {
>     "context": "Editor",
>     "bindings": {
>       "ctrl-p": null,
>       "ctrl-shift-p": null,
> ```

Can confirm, this works for me. However, the issue needs to be addressed on the default keymap that comes with Zed.

**Comment by cyberphantom52** [comment]
For now i have just defined my own keybinds for things i need. Attaching it here in case anyone needs them.

```json
[
  {
    "bindings": {
      "ctrl-shift-p": "command_palette::Toggle",
      "ctrl-p": "file_finder::Toggle",
      "ctrl-left": "editor::MoveToPreviousWordStart",
      "ctrl-shift-left": "editor::SelectToPreviousWordStart",
      "ctrl-right": "editor::MoveToNextWordEnd",
      "ctrl-shift-right": "editor::SelectToNextWordEnd",
      "ctrl-shift-f": "pane::DeploySearch",
      "ctrl-b": "workspace::ToggleLeftDock",
      "alt-up": "editor::MoveLineUp",
      "alt-down": "editor::MoveLineDown",
      "alt-1": ["pane::ActivateItem", 0],
      "alt-2": ["pane::ActivateItem", 1],
      "alt-3": ["pane::ActivateItem", 2],
      "alt-4": ["pane::ActivateItem", 3],
      "alt-5": ["pane::ActivateItem", 4],
      "alt-6": ["pane::ActivateItem", 5],
      "alt-7": ["pane::ActivateItem", 6],
      "alt-8": ["pane::ActivateItem", 7],
      "alt-9": ["pane::ActivateItem", 8]
    }
  }
]

```

**Comment by mikayla-maki** [comment]
I believe this has been fixed.
