### ISSUE TITLE
Something off with default themes in Zed

### ISSUE THREAD

**Issue by evrsen** [zed-industries/zed#9159]
### Check for existing issues

- [X] Completed

### Describe the issue

Hello, I don't know if I'm alone in the feeling of something being off with most default themes in zed (aside one dark), and i'm unable to point it out as i'm not sure exactly what it is.

But one thing that comes to my mind which I think can be related to this, is from the looks of it the default themes don't utilise the entire colour palette of the relevant themes? Take solarized dark for example, only 5 accent colours are being used for syntax highlighting, meanwhile the [actual colour palette](https://ethanschoonover.com/solarized) has 8 accent colours. Helix's solarized dark theme is a league better, from my quick observation it seems to use 7 of the 8 accent colours for syntax highlighting. Solarized dark is just an example, I get this feeling for virtually all themes in Zed?

This is off-topic to the issue above, but since I mentioned solarized I'd also like to point out that there seems to be a white and green foreground colour that's not even apart of the [actual colour palette](https://ethanschoonover.com/solarized), that white colour is supposed to be one of the grey content tones and that green colour is supposed to be the cyan colour. The Rosé Pine theme also has these issues (see https://github.com/zed-industries/zed/issues/9151).

As per [this](https://discord.com/channels/869392257814519848/995403703894954060/1216512058775048343) I'm sad to hear that contributions to built-in themes are not being accepted at this time... Hoping this will change soon, I'd be willing to fix the solarized dark theme, I can't speak for the rest though.

### Screenshots

![image](https://github.com/zed-industries/zed/assets/146845123/1f8b743f-bf2b-4440-aa08-e6e67ac7b36b)
![image](https://github.com/zed-industries/zed/assets/146845123/6fa255ac-c108-4c90-90bc-7f8df69faa87)

**Comment by maxdeviant** [comment]
We're aware that many of the Zed themes do not match up 1:1 with their namesakes. The TL;DR is that, at present, the themes bundled with Zed should be thought of as derivative themes that are inspired by/happen to share the same name as the themes they are based on.

Any discrepancies with themes would best be resolved by creating more true-to-form themes as extensions.

I'm aware of at least one extension that aims to provide a faithful Solarized theme: https://github.com/carlocaione/NeoSolarized.zed

At this time we're not looking to make any changes to our built-in themes, so I'm going to close this issue out.
