### ISSUE TITLE
Crash on Windows 10 with missing DCompositionWaitForCompositorClock

### ISSUE THREAD

**Issue by kazatsuyu** [zed-industries/zed#9166]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`DCompositionWaitForCompositorClock` is only supported on Windows 11 and will crash on Widows 10.
This problem has not occurred in my environment, but I am submitting this issue because of multiple reports on Discord.

### Environment

Windows 10

**Comment by ThatFrogDev** [comment]
This happens for all environment below Windows 11. I'll look into the docs for this function and see if I can fix it.

**Comment by ThatFrogDev** [comment]
Yeah, the problem is we're currently using a function which is only available in Windows 11 and up, namely `DCompositionWaitForCompositorClock`. It is possible to make a function for Windows 10 and below, but I can't test if it works since I don't have a Windows 10 machine. So, is there someone here who owns a Windows 10 computer and has some `win32` api knowledge?

**Comment by zkna** [comment]
> I've been compiling with win10 all afternoon, with install rust environment, compiling zed, with github very slow internet speed.

Sorry, I'm not familiar with win32 api. 
But I can offer my win10 computer if you need it.

**Comment by golanguage** [comment]
I have tried hello world demo of GPUI, got same result -- DComp The ENTRY POINT issue.

But I have not enough win32 api skill to debug it.

**Comment by ThatFrogDev** [comment]
@zkna do you have Discord? Then we can communicate that way, just leave a message in the #windows-port channel. Also it seems like someone already is working on it, but it just needs some changes for better FPS.

**Comment by zkna** [comment]
@ThatFrogDev I registered an account and sent you a friend request. My Name is zkna.

**Comment by ThatFrogDev** [comment]
@zkna to what account did you send the friend request? my Discord name is m_0342sa

**Comment by zkna** [comment]
@ThatFrogDev Domestic to foreign networks are very poor. So you'll have to build it yourself. 
I thought the contact info on your homepage was your account number.

**Comment by ThatFrogDev** [comment]
@zkna oh yeah - that's my old account, I can not access it anymore. I hope I regain access soon but for now you can use the other one.

**Comment by chuwak86** [comment]
for those people who did not have ability to compile exe file, you can use my one.

https://terabox.com/s/1A0nvgwNnizhhslvH-blR6w

it  is build for this pr 
https://github.com/zed-industries/zed/pull/9351/commits/3d70bb68c262792b31755d9e13bd66ec256e6850
