### ISSUE TITLE
don't add matching quotes in comments (use_autoclose)

### ISSUE THREAD

**Issue by passichenko** [zed-industries/zed#9195]
### Check for existing issues

- [X] Completed

## Repro
type `// don't do this` in go code

## Expected
`// don't do this`

## Actual
`// don't do this'`

At least in VS Code it works as expected. Alternatively, detect that it's a contraction somehow. In https://github.com/zed-industries/zed/issues/4803 I saw that there is a way to turn pairing off, but I think that a better default would be to not do it in comments.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
I think the setting for this already exists #4543.

**Comment by passichenko** [comment]
If I understand correctly, `use_autoclose` will disable autoclose everywhere, while I suggest having the option to disable it only in comments (ideally by default). This is the behavior that VS Code has out-of-the-box.

**Comment by Wanja-L** [comment]
This frequently causes friction for me frequently when writing comments that contain apostrophes.

**Comment by x032205** [comment]
In my opinion a bigger problem is the quotes being added when a word is connected to the first quote. If quotes only auto-closed when there's a space in front of the first quote, then we would not have quotes closing on words like "it's", "don't", and "they're".

This would partially solve your issue.
