### ISSUE TITLE
Editor cut in half

### ISSUE THREAD

**Issue by maxdeviant** [zed-industries/zed#9198]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Just noticed this in Nightly:

<img width="1268" alt="Screenshot 2024-03-11 at 4 38 39 PM" src="https://github.com/zed-industries/zed/assets/1486634/847ac437-da94-4bed-8096-5c84bdb31fb8">

Don't have any concrete repro steps yet.

It seems very similar to what happens in https://github.com/zed-industries/zed/issues/4281.

### Environment

Zed: v0.127.0 (Zed Nightly)
OS: macOS 14.3.0
Memory: 24 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
Visually, it looks the same as #9200.

**Comment by JosephTLyons** [comment]
I went ahead and put this on quality week - feels important.
