### ISSUE TITLE
Pressing escape should dismiss the "do you want to save" prompt

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#9203]
### Check for existing issues

- [X] Completed

### Describe the feature

#8980 adds a custom prompt when closing a file with unsaved changes. Normally pressing the escape key on such prompts has the same result as clicking on the cancel button. This is currently not the case. (nothing happens)

**Comment by jansol** [comment]
This is specific to the custom prompts added in #8980 which are used on Linux. I think macOS still uses the system-provided prompts?

**Comment by jadijadi** [comment]
Right. tested on a Linux machine too. You are right. On Mac we use the system-provided prompt and htis happens on Linux.

**Comment by ConradIrwin** [comment]
This should be fixed on main
