### ISSUE TITLE
linux: can't resize window

### ISSUE THREAD

**Issue by onbjerg** [zed-industries/zed#9205]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Building and running Zed from source works fine, but I am unable to resize or move the window. I am also unable to open the command palette. No shell is rendered for the window.

Holding down super and dragging the window allows me to move it around.

Commit: 14a0d8039b9d666ca4f989fc835bc1789b6e3e75

### Environment

```
Zed: v1.0.0 (Zed Dev)
OS: Linux 1.0.0
Memory: 31.2 GiB
Architecture: x86_64
```

Output of `uname -a`:

```
Linux dagr 6.7.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000 x86_64 GNU/Linux
```

I am using Wayland and Gnome 45.4

CPU: AMD Ryzen 9 5950X
GPU: AMD Radeon RX 6700 XT

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed is always opened in the top left of my screen, unable to be resized
![image](https://github.com/zed-industries/zed/assets/8862627/c8285f4e-532f-4ec2-a640-4cafb3fd8ce3)

**Comment by onbjerg** [comment]
As a note, I can also resize the window using Super + middle mouse

**Comment by onbjerg** [comment]
Just to clarify, the resize/move is also a known factor? If so, I'll close my issue

**Comment by bbb651** [comment]
Being able to drag the headerbar to move and the borders to resize is part of the CSD, Are you able to resize with <kbd>Super</kbd> + <kbd>Up</kbd> or <kbd>Super</kbd> + <kbd>Right Click</kbd> / <kbd>Middle Click</kbd>?

**Comment by onbjerg** [comment]
yes! I'll close this issue, ty for clarifying

**Comment by phocks** [comment]
Seems like we can run i X11 mode using `WAYLAND_DISPLAY='' cargo run`

I made a `Zed.desktop` file in my `~/.local/share/applications` with 

```
[Desktop Entry]
Type=Application
Name=Zed
Exec=WAYLAND_DISPLAY='' /home/phocks/bin/Zed
Icon=/home/phocks/bin/Zed.jpg
Terminal=false
Categories=Utility;
```

Now it's usable. Can't wait for native client side decoration in Wayland!

**Comment by onbjerg** [comment]
Yooo, that's awesome news!

**Comment by peppergrayxyz** [comment]
Hi,

I'm facing the issue that I'm not able to resize the window, because the arrows are not showing up if I move to edge. Resizing by using the full-screen switch or Super+mouse wheel works. 

Norml window behvaior:
![image](https://github.com/user-attachments/assets/ebdccdd0-2343-451c-965d-7ba80f57748a)

Zed:
![image](https://github.com/user-attachments/assets/b01d7ffa-def2-439c-a622-8a5996808030)
