### ISSUE TITLE
Allow Languages to provide Commands

### ISSUE THREAD

**Issue by sanbox-irl** [zed-industries/zed#9206]
### Check for existing issues

- [X] Completed

### Describe the feature

RA has several commands in VSC like "Go to parent module" or "Go to Cargo.toml". These are really nifty and I'd love to have them in the command palette in zed too.

**Comment by SomeoneToIgnore** [comment]
This is a part of the Tasks initiative and is currently being worked on: https://github.com/zed-industries/zed/issues/7108#issuecomment-1983264373

**Comment by sanbox-irl** [comment]
Ah they're called TASKS in Zed! Sorry sounds good
