### ISSUE TITLE
Zed switches to a temporary file when a file is edited in Xcode

### ISSUE THREAD

**Issue by Autocrit** [zed-industries/zed#9211]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Screenshot 2024-03-12 at 06 02 59](https://github.com/zed-industries/zed/assets/3815155/3d0b097c-f59b-4b58-a57e-7c1be1ad9d76)

I'm editing C++ in Zed on MacOS Sonoma and switching to Xcode for debugging. Xcode autosaves files.

Often, but not always, after making a change in Xcode, and returning to Zed, Zed will have switched to a temporary copy of the file and closed the real one.

This seems like a bug as it's easy to edit and save changes to the temporary file thinking it's the real file.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
Somewhat related #4846
