### ISSUE TITLE
ESLint integration broken 5 days ago when new ESLint prerelease was pushed

### ISSUE THREAD

**Issue by mrnugget** [zed-industries/zed#9213]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Our ESLint integration broke 5 days when ESLint pushed a new pre-release: https://github.com/microsoft/vscode-eslint/releases/tag/3.0.1-alpha.1

That's because our code assumes that we always fetch the latest pre-release (because ESLint hasn't had a pre-release in 3 years and only pushed new released, which is why we're on `2.2.20-Insiders` still).

Fix is to use a specific tag for now, push a hotfix, then see if we can forward fix and use newest ESLint version (once that's stabilized)

### Environment

N/A

**Comment by mrnugget** [comment]
Fix is in https://github.com/zed-industries/zed/releases/tag/v0.126.2-pre

**Comment by anton-patrushev** [comment]
is there any chance to release `0.126.0` into stable asap?
or maybe someone can cherry-pick and release it as a patch for the latest stable `0.125` as `0.125.4?

**Comment by mrnugget** [comment]
I'm on it! Stable release coming soon.

**Comment by mrnugget** [comment]
Now also in stable: https://github.com/zed-industries/zed/releases/tag/v0.125.4

**Comment by anton-patrushev** [comment]
awesome news, thanks @mrnugget
