### ISSUE TITLE
custom keybinding for ToggleRightDock doesn't work

### ISSUE THREAD

**Issue by tomatau** [zed-industries/zed#9226]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My first custom key mappings, 2 work fine but the `ToggleRightDock` doesn't work. I haven't changed any other settings, this is a fresh install. `cmd-r` currently works for `ToggleRightDock` but remapping it doesn't work. I use this same keymapping, `ctrl-shift-\` in other editors for the same purpose

Here's my keymap

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-\\": "workspace::ToggleLeftDock",
      "ctrl-shift-\\": "workspace::ToggleRightDock",
      "ctrl-shift-t": "workspace::ToggleBottomDock"
    }
  }
]
```

### Environment

```
Zed 0.125.4 – /Applications/Zed.app
```

```
Software:

    System Software Overview:

      System Version: macOS 14.3.1 (23D60)
      Kernel Version: Darwin 23.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: tom3tao
      User Name: Thomas Hudspith-Tatham (tomatao)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 9 days, 13 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac15,10
      Model Number: MRX53B/A
      Chip: Apple M3 Max
      Total Number of Cores: 14 (10 performance and 4 efficiency)
      Memory: 36 GB
      System Firmware Version: 10151.81.1
      OS Loader Version: 10151.81.1
      Serial Number (system): J0JX5G0069
      Hardware UUID: D25E4B41-E5EA-5044-A763-335D874E2790
      Provisioning UDID: 00006034-001221523E88001C
      Activation Lock Status: Enabled
```

**Comment by JosephTLyons** [comment]
Hey @tomatau, try:

`"ctrl-|": "workspace::ToggleRightDock"`

I do think this is a bit inconsistent on our end, but it looks like if its not an alphabetic character, that we use the actual symbol produced when shift is being held, in this case `|`.

**Comment by OmerYesilkaya** [comment]
I have spent 5-6 hours trying to find this... Some sort of a warning or info box about this on docs could help a lot.
