### ISSUE TITLE
Apply theme extensions on install

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9228]
### Check for existing issues

- [X] Completed

### Describe the feature

It might be handy to be able to apply or even preview the theme extension after it's installed.

There are a few ways to do this, each with its own UX trade-offs:

- Automatically apply the installed theme.
- Show a toast/popup asking if you want to apply the theme.

Some editors even preview the theme on the current window when selected, but this isn't possible with the current extensions market layout.

**Comment by versecafe** [comment]
@Moshyfawn how would this behave in cases of themes with multiple options such as Catppuccin which has 4 themes? popup window with all the options?

**Comment by ConradIrwin** [comment]
This shipped to 0.128.0-pre and will hit stable next week
