### ISSUE TITLE
linux: go to definition with ctrl+click on symbol

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#9237]
### Check for existing issues

- [X] Completed

### Describe the feature

On macOS it's possible to jump to the definition of a symbol by clicking it with cmd held down. On other platforms this is expected to be bound to ctrl+click, but currently does not seem to work. (at least on linux/wayland)

**Comment by almartino** [comment]
By implementing the modifiers function:

```rust
// crates/gpui/src/platform/linux/x11/window.rs
fn modifiers(&self) -> Modifiers {
        let mapping = self.0.xcb_connection.get_modifier_mapping()
            .unwrap()
            .reply()
            .unwrap();
        let keycodes = mapping.keycodes;

        Modifiers{
            control: keycodes.contains(&(1<<2)), // ControlMask
            alt: keycodes.contains(&(1<<3)), // Mod1Mask
            shift: keycodes.contains(&(1<<0)), // ShiftMask
            command: keycodes.contains(&(1<<6)), // Mod4Mask
            function: false,
        }
    }
```

The hover link feature works but only for variables definitions:
```
fn test_fn(user_id: &str) { // "Ctrl + hover on user_id works, ctrl + click does nothing"
// ...
}
``
Furthermore, the link hover is triggered only with the `command` modifier.

**Comment by J-Cake** [comment]
I would also very much appreciate this but on wayland

**Comment by apricotbucket28** [comment]
Fixed by https://github.com/zed-industries/zed/pull/10061

**Comment by jansol** [comment]
Yep, seems to work now!

**Comment by lupodellasleppa** [comment]
I'm on a fresh install of Ubuntu 24.04 with Zed 0.186.12 (`5898c2e18c0defd20f644fb3c7944cc765cc0cc5` this comes out when I click on "About Zed") and click to go to definition is not working for me either with ctrl or alt

**Comment by jansol** [comment]
> click to go to definition is not working for me either with ctrl or alt

Go to definition relies on having a working language server for whatever you are editing. What language are you working with and do you have the relevant support extension installed? (And optionally the language server installed from apt)

**Comment by lupodellasleppa** [comment]
In Python, it actually works if I comment out the custom settings for ruff and let Zed use whatever default language server it's using, so I guess I'll have to tinker with ruff's settings to get this working with it as well. Thank you for pointing me in the right direction! And sorry for reviving this old thread 😛
