### ISSUE TITLE
Build issue in the current release 

### ISSUE THREAD

**Issue by shivaay108** [zed-industries/zed#9240]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

Hi guys ,

Was trying to run the current release of Zed , but came across this error. I have docker installed in the machine and ran the dependencies from it i.e. livekit-server and others. 

While building the release error is coming up ; 
error: failed to run custom build command for `live_kit_server v0.1.0 (D:\zed\crates\live_kit_server)`                                     

Caused by:
  process didn't exit successfully: `D:\zed\target\debug\build\live_kit_server-04a9a9f280a32227\build-script-build` (exit code: 101)       
  --- stderr
  thread 'main' panicked at crates\live_kit_server\build.rs:4:10:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/livekit_room.proto: No such file or directory\r\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Have ran the dependencies over docker 
![Screenshot 2024-03-13 010122](https://github.com/zed-industries/zed/assets/118446333/dcb6a8bc-dc9f-4bbb-92af-0d928203d19e)
![Screenshot 2024-03-13 010137](https://github.com/zed-industries/zed/assets/118446333/8719d30d-5620-4529-9cd0-ca3ba180dfb7)

Please advise. 

### Environment

Processor	AMD Ryzen 5 5600U with Radeon Graphics            2.30 GHz
Installed RAM	16.0 GB (15.3 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by maxdeviant** [comment]
Based on the errors, it looks like the LiveKit protocol Git submodule is missing.

Did you initialize the Git submodules as instructed here?

https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_windows.md#repository

**Comment by shivaay108** [comment]
Hi maxdeviant,

Thanks , certainly the submodules were not initialized.

Thanks

**Comment by salverde** [comment]
fck a dck! had exact same issue and exact solution solved it! thanks much

**Comment by ntua-el17897** [comment]
had the exact same issue. for people who are meant to write lines upon lines of code we sure can't read instructions properly :p
