### ISSUE TITLE
Need to restart to load new changes in TypeScript files

### ISSUE THREAD

**Issue by acidlake** [zed-industries/zed#9249]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

So in Svelte/Sveltekit Project running typescript, every time i create a new ts file, or add any changes to a ts file, like a new definition, a new function, module etc, auto competition is not working, i need to restart the editor for zed to pickup those new changes.

### Environment

Zed: v0.126.2 (Zed Preview)
OS: macOS 14.4
Memory: 16 GiB
Architecture: ARM

**Comment by JosephTLyons** [comment]
This sounds an awfully lot like: #8960
