### ISSUE TITLE
[Windows] Zed not running in debug and release both builds

### ISSUE THREAD

**Issue by shivaay108** [zed-industries/zed#9251]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Came up with the error when launched the zed /target/debug binary : 

<details><summary>expand for log</summary><pre>
D:\zed>cargo run     
warning: unused variable: `path`
   --> crates\fs\src/fs.rs:119:36
    |
119 |     async fn create_symlink(&self, path: &Path, target: PathBuf) -> Result<()> {
    |                                    ^^^^ help: if this is intentional, prefix it with an underscore: `_path`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `target`
   --> crates\fs\src/fs.rs:119:49
    |
119 |     async fn create_symlink(&self, path: &Path, target: PathBuf) -> Result<()> {
    |                                                 ^^^^^^ help: if this is intentional, prefix it with an underscore: `_target`

warning: `fs` (lib) generated 2 warnings (run `cargo fix --lib -p fs` to apply 2 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 4.31s
     Running `target\debug\Zed.exe`
[2024-03-13T05:04:12+05:30 ERROR util] crates\settings\src\settings_file.rs:76: EOF while parsing a value at line 1 column 0
[2024-03-13T05:04:14+05:30 ERROR util] crates\zed\src/zed.rs:620: EOF while parsing a value at line 1 column 0
[2024-03-13T05:04:14+05:30 ERROR util] crates\zed\src/main.rs:692: The system cannot find the path specified. (os error 3)
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: NotSupportedError" at crates\gpui\src\platform\windows\window.rs:143:14
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98
   1: backtrace::backtrace::trace_unsynchronized<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:176
   4: backtrace::capture::Backtrace::new
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:140
   5: Zed::init_panic_hook::closure$0
             at crates\zed\src\main.rs:596
   6: alloc::boxed::impl$49::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\alloc\src\boxed.rs:2029
   7: std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:783
   8: std::panicking::begin_panic_handler::closure$0
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:657
   9: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\sys_common\backtrace.rs:171
  10: std::panicking::begin_panic_handler
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:645
  11: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\panicking.rs:72
  12: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\result.rs:1649
  13: core::result::Result::unwrap<blade_graphics::hal::Context,blade_graphics::NotSupportedError>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\result.rs:1073
  14: gpui::platform::windows::window::WindowsWindowInner::new
             at crates\gpui\src\platform\windows\window.rs:133
  15: gpui::platform::windows::window::wnd_proc
             at crates\gpui\src\platform\windows\window.rs:1086
  16: DispatchMessageW
  17: DispatchMessageW
  18: CallNextHookEx
  19: KiUserCallbackDispatcher
  20: NtUserCreateWindowEx
  21: CreateWindowExW
  22: CreateWindowExW
  23: CreateWindowExW
  24: windows::Win32::UI::WindowsAndMessaging::CreateWindowExW<windows_core::strings::pcwstr::PCWSTR,ref$<windows_core::strings::hstring::HSTRING>,windows::Win32::Foundation::HWND,windows::Win32::UI::WindowsAndMessaging::HMENU,windows::Win32::Foundation::HINSTA
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.53.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:540
  25: gpui::platform::windows::window::WindowsWindow::new
             at crates\gpui\src\platform\windows\window.rs:654
  26: gpui::platform::windows::platform::impl$3::open_window
             at crates\gpui\src\platform\windows\platform.rs:340
  27: gpui::window::Window::new
             at crates\gpui\src\window.rs:324
  28: gpui::app::impl$4::open_window::closure$0<workspace::Workspace,workspace::impl$10::new_local::closure$0::async_block$0::closure_env$5>
             at crates\gpui\src\app.rs:489
  29: gpui::app::AppContext::update<gpui::window::WindowHandle<workspace::Workspace>,gpui::app::impl$4::open_window::closure_env$0<workspace::Workspace,workspace::impl$10::new_local::closure$0::async_block$0::closure_env$5> >
             at crates\gpui\src\app.rs:354
  30: gpui::app::AppContext::open_window<workspace::Workspace,workspace::impl$10::new_local::closure$0::async_block$0::closure_env$5>
             at crates\gpui\src\app.rs:486
  31: gpui::app::async_context::AsyncAppContext::open_window<workspace::Workspace,workspace::impl$10::new_local::closure$0::async_block$0::closure_env$5>
             at crates\gpui\src\app\async_context.rs:133
  32: workspace::impl$10::new_local::closure$0::async_block$0
             at crates\workspace\src\workspace.rs:872
  33: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<gpui::window::WindowHandle<workspace::Workspace>,alloc::vec::Vec<enum2$<core::option::Option<enum2$<core::result::Resul
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\future\future.rs:124
  34: async_task::runnable::impl$6::spawn_local::impl$1::poll<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<gpui::window::WindowHandle<workspace::Workspace>,alloc::vec::Vec<enum2$<core::optio
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:455
  35: async_task::raw::RawTask::run<async_task::runnable::impl$6::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<gpui::window::WindowHandle<workspace::Workspace>,alloc::ve
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\raw.rs:557
  36: async_task::runnable::Runnable::run<tuple$<> >
             at C:\Users\sharm\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:781
  37: gpui::platform::windows::platform::WindowsPlatform::run_foreground_tasks
             at crates\gpui\src\platform\windows\platform.rs:211
  38: gpui::platform::windows::platform::impl$3::run
             at crates\gpui\src\platform\windows\platform.rs:282
  39: gpui::app::App::run<Zed::main::closure_env$3>
             at crates\gpui\src\app.rs:142
  40: Zed::main
             at crates\zed\src\main.rs:119
  41: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ops\function.rs:250
  42: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\std\src\sys_common\backtrace.rs:155
  43: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\std\src\sys_common\backtrace.rs:155
  44: std::rt::lang_start::closure$0<tuple$<> >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\std\src\rt.rs:166
  45: std::rt::lang_start_internal::closure$2
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\rt.rs:148
  46: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:552
  47: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:516
  48: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panic.rs:142
  49: std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\rt.rs:148
  50: std::rt::lang_start<tuple$<> >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\std\src\rt.rs:165
  51: main
  52: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  53: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  54: BaseThreadInitThunk
  55: RtlUserThreadStart

error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)
</pre></details>
### Environment

Processor	AMD Ryzen 5 5600U with Radeon Graphics            2.30 GHz
Installed RAM	16.0 GB (15.3 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/118446333/33be91fb-1a54-4d84-b8fd-771a9568f360)
![image](https://github.com/zed-industries/zed/assets/118446333/db23e614-2c4b-4592-b77a-ab5a26ef342a)
![image](https://github.com/zed-industries/zed/assets/118446333/3b74b641-1d77-47c6-9b8c-c8d02cef8c79)

**Comment by kazatsuyu** [comment]
`NotSupportedError` means "your graphics system is not supported". You could probably get more information with `RUST_LOG=blade=debug`.
However, it may be difficult to solve this issue quickly.

**Comment by ASlava12** [comment]
I have a similar problem
[zed.error.txt](https://github.com/zed-industries/zed/files/14887266/zed.error.txt)
[zed.error.vulkaninfo.txt](https://github.com/zed-industries/zed/files/14887267/zed.error.vulkaninfo.txt)
[dmidecode.txt](https://github.com/zed-industries/zed/files/14887271/dmidecode.txt)
[dkpg.txt](https://github.com/zed-industries/zed/files/14887287/dkpg.txt)

graphic card: radeon rx590, install official driver

```
WAYLAND_DISPLAY='' cargo run
cargo run
```

```
slava@slava-tower:~/zed$ RUST_LOG=blade_graphics=debug cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target/debug/Zed`
[2024-04-05T18:52:23+03:00 DEBUG blade_graphics::hal::init] Bugs SystemBugs {
    intel_unable_to_present: false,
}
[2024-04-05T18:52:23+03:00 WARN  blade_graphics::hal::init] Rejected for device extension "VK_EXT_inline_uniform_block" not supported
[2024-04-05T18:52:23+03:00 WARN  blade_graphics::hal::init] Rejected for device extension "VK_KHR_dynamic_rendering" not supported
[2024-04-05T18:52:23+03:00 WARN  blade_graphics::hal::init] Rejected for device extension "VK_KHR_timeline_semaphore" not supported
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: NotSupportedError" at crates/gpui/src/platform/linux/x11/window.rs:234:14

....
```
All text in file

**Comment by kazatsuyu** [comment]
https://www.amd.com/ja/support/kb/release-notes/rn-rad-win-vulkan
Radeon graphics driver supports Vulkan extentions used by `blade`. If your driver is older than supported version, you need to update it.

**Comment by kazatsuyu** [comment]
We should add troubleshooting for this.
https://github.com/zed-industries/zed/blob/3aa242e0766813e2cfb8cb84d6ca73606c8a5d49/docs/src/developing_zed__building_zed_windows.md

**Comment by tbrockman** [comment]
Ran into this issue with out-of-date GeForce GTX 1070 drivers, updating solved the issue and led to a functional Windows build! 🎉

**Comment by notpeter** [comment]
Following up @shivaay108 a lot has happened in the six months since you filed this.
Can you try building again and see if you have better luck.
If not, please comment with the error messages you're seeing and I'm happy to reopen.
Thanks
