### ISSUE TITLE
[Vim mode] shift-y to yank to end of line

### ISSUE THREAD

**Issue by hnbnh** [zed-industries/zed#9254]
### Check for existing issues

- [X] Completed

### Describe the feature

In Vim normal mode, `shift-y` will yank current line (Zed default behavior - `vim::YankLine`).

In Neovim, the functionality is a bit different, `shift-y` will yank to the end the current line.

Can we have a new motion like `vim::YankToEndOfLine`, so user can easily remap the key binding?

**Comment by ConradIrwin** [comment]
@hnbnh It's a bit obtuse, but you can put the following in your keymap file to fix this:

```
[
{
  "context": "vim_mode == normal || vim_mode == visual",
  "bindings": {
     "shift-y": ["workspace::SendKeystrokes", "y $"]
  }
}
]
```
