### ISSUE TITLE
Exception  INVALID_OPTIONS on mach port 0 (guarded with 0x0000000000000000)

### ISSUE THREAD

**Issue by ConradIrwin** [zed-industries/zed#9261]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* Exception  INVALID_OPTIONS on mach port 0 (guarded with 0x0000000000000000) on thread 0 (com.apple.main-thread)
* Version:
dev.zed.Zed (0.125.4)
* Incident:
[33D9C61B…](https://zed-crash-reports.nyc3.digitaloceanspaces.com/33D9C61B-61A1-4D5A-9052-A1CC6EE0B6DE.ips)

We see a couple of similar crashes each week; I'm not at all sure how to figure out more details about why though.

```
mach_msg2_trap
mach_msg2_internal
mach_msg_overwrite
mach_msg
_XMIGPostNotification
_AXUIElementPostNotificationWithInfo
_NSAccessibilityNotifyWithAXElement
_NSAccessibilityNotify
NSAccessibilityPostNotificationForObservedElementWithUserInfo
-[NSWindow _setFrameCommon:display:fromServer:]
-[_NSFullScreenMouseDetectionWindow setFrame:display:]
-[_NSFullScreenMenuBarCompanionController _updateMouseDetectionWindowIfNecessary]
-[_NSFullScreenMenuBarCompanionController _updateMenuBarReveal:toolbarReveal:]
-[_NSFullScreenToolbarRevealAnimation setCurrentProgress:]
__43-[NSAnimation _advanceTimeWithDisplayLink:]_block_invoke
NSPerformVisuallyAtomicChange
-[NSAnimation _advanceTimeWithDisplayLink:]
-[NSScreenDisplayLink _fire]
___NSRunLoopTimerCreateWithHandler_block_invoke
__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
```

### Environment

x

**Comment by as-cii** [comment]
Looks like somebody else experienced this crash: https://github.com/mpv-player/mpv/issues/12632. It's also happening on Firefox: https://crash-stats.mozilla.org/report/index/704dd040-2473-4e91-a5ce-ddd780240225.

Also this: https://github.com/Ranchero-Software/NetNewsWire/issues/4220. Here they point at some accessibility feature that might be buggy in macOS.
