### ISSUE TITLE
Light/Dark Appearance Theme Setting

### ISSUE THREAD

**Issue by mgroholski** [zed-industries/zed#9262]
### Check for existing issues

- [X] Completed

### Describe the feature

A setting that allows the user the select different themes for light and dark system appearances. For example, during the day when my system appearance is set to light mode, Zed will automatically swift to the light appearance I preselected. Similar for the dark appearance.

Information on Appearance: https://support.apple.com/guide/mac-help/use-a-light-or-dark-appearance-mchl52e1c2d2/mac#:~:text=On%20your%20Mac%2C%20choose%20Apple,may%20need%20to%20scroll%20down.)&text=Select%20Light%2C%20Dark%2C%20or%20Auto%20on%20the%20right.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="793" alt="Screenshot 2024-03-12 at 9 33 01 PM" src="https://github.com/zed-industries/zed/assets/94934629/06a04634-867e-4aa1-ad1a-146a6dbe2799">

The corresponding feature in VS code.

**Comment by Congyuwang** [comment]
I think you can already do it with:
```json
  "theme": {
    "mode": "system",
    "light": "Xcode Default Light",
    "dark": "Xcode Default Dark"
  },
```
in settings in recent stable releases.
