### ISSUE TITLE
Copy file/folder from workspace to workspace

### ISSUE THREAD

**Issue by piotrkulpinski** [zed-industries/zed#9305]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi, 
I'd like to request a possibility to add support for copying files/folders between workspaces. 
Currently, this only works within the same workspace/window.

Thanks.

**Comment by asesh** [comment]
Recently, I noticed this issue too. It would be great, if this feature was added to Zed. It can be easily done in VS Code.

**Comment by Moshyfawn** [comment]
Also ties into #7386 discussion.

**Comment by notpeter** [comment]
I'm going to close in favor of:
- https://github.com/zed-industries/zed/issues/11757

Please 👍 that issue to express you interest and subscribe to be notified of progress.
Thanks for reporting!
