### ISSUE TITLE
Editor action buttons flicker on modal open

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9340]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the LSP logs modal is on, the actions in the editor toolbar will flicker on and off.

1. Open LSP logs.
2. Click to toggle the LSP logs on and off.
3. Move the cursor inside the Zed window.
4. Watch the action buttons flicker.

### Environment

Zed: v0.127.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/04ef4671-50f8-4ec2-b6c9-a1c95e6e2f08

**Comment by JosephTLyons** [comment]
@as-cii @nathansobo
