### ISSUE TITLE
[Vim] Cannot remap project_search::ToggleFocus to open Project Search

### ISSUE THREAD

**Issue by hnbnh** [zed-industries/zed#9343]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The following keymap will not open the Project Search:

```json
  {
    "context": "Editor && vim_mode == normal && vim_operator == none && !VimWaiting",
    "bindings": {
      "space /": "project_search::ToggleFocus"
    }
  }
```

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

No log was added.

**Comment by baldwindavid** [comment]
@hnbnh Unless something has changed, I think the typical suggestion would be a context for both normal and visual mode...

```json
    "context": "Editor && VimControl && !VimWaiting && !menu",
```

And if you really only want it in normal mode in...

```json
    "context": "Editor && vim_mode == normal && !VimWaiting && !menu",
```

Guess I'm unfamiliar with the `vim_operator == none` part there.
