### ISSUE TITLE
Zig "orelse" keyword mistakenly highlighted as symbol

### ISSUE THREAD

**Issue by TeamPuzel** [zed-industries/zed#9355]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="374" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/c55cce67-8ca1-419e-89df-85a524b3c3bd">

In all themes the orelse keyword is not highlighted correctly, instead being treated as a symbol. Does not happen in vscode.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by TeamPuzel** [comment]
Noticed some additional weirdness

### The error `!` is highlighted like a keyword
<img width="198" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/3b219ee2-24b3-4857-8693-a2ccdb65ce43">

### Some builtin functions are colored like keywords, others are not
<img width="288" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/8a9d78b7-ab9a-4a27-9462-3ae9b7e3e715">
<img width="420" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/9eda8c2c-daed-4044-b3ab-4cbaebd4cf94">
<img width="297" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/d19599b9-a58a-4c89-b93b-2ac6ea88cc05">

**Comment by TeamPuzel** [comment]
<img width="234" alt="image" src="https://github.com/zed-industries/zed/assets/94306330/e90aaa81-3541-4525-9ee9-3bb1fb2f39f1">

Found more, `or` and `and` keywords are also not highlighted properly

**Comment by mrnugget** [comment]
Hey @TeamPuzel! Zig highlights are defined here, via tree-sitter queries: https://github.com/zed-industries/zed/blob/main/crates/languages/src/zig/highlights.scm

To fix those (if you want to take a stab, or someone else):

1. Get Zed running from source: `cargo run /path/to/zig/project`
2. Open a Zig file
3. Open the debug tree-sitter view: `debug: open syntax tree view`
4. Move your cursor to syntax node that you think needs changed highlighting
5. See what the node name is in the tree view
6. Open `crates/languages/src/zig/highlights.scm` in another editor instance, edit the highlights in there, save and you should see changes
7. Repeat (6) until you're happy with results.

Recommendation: look at highlights of other languages to see what the proper captures are (the things that start with `@`). Rust is probably our best-supported language.

**Comment by TeamPuzel** [comment]
<img width="364" alt="image" src="https://github.com/user-attachments/assets/87eb326e-4ddb-4d49-bfb7-368d2ab58675">

Yes it's still the same.
