### ISSUE TITLE
the tooltip panel blinks when the mouse hovers a line with an error

### ISSUE THREAD

**Issue by KennyMack** [zed-industries/zed#9379]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the mouse hovers over a line with an error the tooltip blinks, I think the problem occurs when the mouse is between two lines with a syntax problem.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/6962171/865709b4-1e82-497b-b60a-b624669a155b

**Comment by Moshyfawn** [comment]
Could you try the latest [`v0.127.1`](https://zed.dev/releases/preview/0.127.1) where it was addressed?

**Comment by Moshyfawn** [comment]
Initial issue report: #9010

**Comment by Moshyfawn** [comment]
I'm going to close this issue, but if it's still relevant, please feel free to reopen it.
