### ISSUE TITLE
hover popover flicker

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#9382]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```rs
fn main() {
    let _ = "";
    let _ = "";
    let _ = "";
    let _ = "";
    let _ = "";
    let s = &mut false;
    s = &false;
    println!("Hello, world!");
}
```

<img width="643" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/6acd0293-f8fc-449d-92e4-bb1069a5e5bf">

![1](https://github.com/zed-industries/zed/assets/11925432/8aff1526-0756-439d-a63c-60f6d9d3e154)

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by kzhui125** [comment]
duplicate

**Comment by Moshyfawn** [comment]
[`v0.127.1`](https://zed.dev/releases/preview/0.127.1) should have the fix. See https://github.com/zed-industries/zed/issues/9379#issuecomment-1998886382.

Duplicate of
- #9379
