### ISSUE TITLE
vim: `a` And `i` Used With Counts Issues

### ISSUE THREAD

**Issue by nlordell** [zed-industries/zed#9383]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using `a` or `i` **with a count** from normal mode does not work as expected. In particular:
* You cannot append the character `0` this way
* The text insertion is considered two separate edits WRT undo

Examples included below:

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Some examples with `a`:

<details><summary>Appended `0`s considered part of count</summary>

```
let i = 0|x
```

`4a10<esc>`

```
let i = 0x111111111111111111111111111111111111111|1
```

_Notice that there are 40 times `1` instead of 4 times `10`. As a correlary to this, `{n}a0<esc>` will not append anything._

</details>

<details><summary>Incorrect undo behaviour</summary>

```
buffe|r
```

`3a.<esc>`

```
buffer..|.
```

`u`

```
buffer|.
```

_Notice that there is a leftover `.`. It is as if the repeated appended text is a separate edit._

`u`

```
buffer|
```

_Notice the cursor position being past the last character._

</details>

**Comment by ConradIrwin** [comment]
Thanks for this, I can reproduce both issues.

If you'd like to pair with me on fixing them, https://calendly.com/conradirwin/pairing

**Comment by nlordell** [comment]
@ConradIrwin - unfortunately, you seem fully booked :see_no_evil:

**Comment by ConradIrwin** [comment]
Sorry! I'm on vacation from Friday and next week. If you want to take a pass by yourself feel free, otherwise we can pick this up together in April.

**Comment by nlordell** [comment]
This issue is still not fully resolved, as incorrect undo behaviour is still around:

```
buffe|r
```

`3a.<esc>`

```
buffer..|.
```

`u`

```
buffer.|
```

_Notice that there is a leftover `.` and that the cursor is after the end of the line. It is as if the repeated appended text is a separate edit._

`u`

```
buffer|
```

_Notice the cursor position being past the last character._

**Comment by nlordell** [comment]
Created a separate issue to track the undo issues: https://github.com/zed-industries/zed/issues/13573
