### ISSUE TITLE
Vim mode new line (O) consistently requires saving twice to save

### ISSUE THREAD

**Issue by ozozozd** [zed-industries/zed#9395]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Vim mode O
2) Attempt to save with cmd-S
3) Observe that on the first attempt the save hasn't happened.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 13.6.5
Memory: 16 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@ozozozd very strange! I cannot reproduce this locally, but seems like something we should fix.

* What file-type are you using (and do you have on-save formatters that might interact with this?)
* Do you have any custom keybindings for `shift-o` or saving?

When you say "the save isn't happening", I assume the blue dot stays in zed, and the file on disk is not written?

**Comment by ozozozd** [comment]
I forgot to mention a key detail. The following custom keymap entry:
```{
    "context": "Editor && vim_mode == insert",
    "bindings": {
      "j j": "vim::NormalBefore", // remap jj in insert mode to escape.
      "j k": "vim::NormalBefore", // remap jj in insert mode to escape.
      "cmd-s": ["vim::NormalBefore", "workspace::Save"]
    }
  },
```
Sorry 😬 

Cmd-s will switch to normal mode but not save.

And you are right, just to confirm:
- blue dot stays,
- file is not written,
- no on-save formatters (other than default pyright, but I think for some projects I have format-on-save turned off)

**Comment by ConradIrwin** [comment]
@ozozozd makes sense!

We don't currently have a way to map one key to multiple actions (but it is a relatively common request). For now the "best" way to do this is to use workspace::SendKeystrokes.

```
  {
    "context": "Editor && vim_mode == insert",
    "bindings": {
      "cmd-s": ["workspace::SendKeystrokes", "escape cmd-s"]
    }
  },
```

There are further problems with this approach (in particular if we didn't change the context with `escape` then `cmd-s` would recursively call our SendKeystrokes action), but this should do what you want.
