### ISSUE TITLE
Vue language server does not auto-update

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9401]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This PR added auto-updating of node-based language servers, but skipped vue, as it does multiple language server installs. It should be fairly easy to add in though:

- https://github.com/zed-industries/zed/pull/9361

### Environment

Zed: v0.128.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by WalkAlone0325** [comment]
the same problem. zed：0.128.3, macos 14.3.1, node 18 or 20 is not working.

**Comment by mrnugget** [comment]
We pinned it to 1.8 because >1.8 does not work yet with Zed: https://github.com/zed-industries/zed/pull/9846

**Comment by koiralakiran1** [comment]
Is this still a valid issue? vue was been moved to extensions api in https://github.com/zed-industries/zed/pull/10486
