### ISSUE TITLE
Better handing for dismissing inline errors

### ISSUE THREAD

**Issue by danielzsh** [zed-industries/zed#9433]
### Check for existing issues

- [x] Completed

### Describe the feature

The issue was kinda mentioned [here](https://github.com/zed-industries/zed/issues/4743#issuecomment-1908632300): it's not quite transparent how inline error messages should be dismissed. I myself was completely unaware `esc` worked, and resorted to just closing and reopening the file (certainly suboptimal!) One idea I had was simply clicking on the error to dismiss it (seeing as there's already a copy button so we shouldn't need to worry about the user doing click + drag). Also, having the error go away once the code is fixed will probably greatly improve UX as well.

**Comment by izuzak** [comment]
There's also this old issue: [Inline error removal is not discoverable](https://github.com/zed-industries/zed/issues/5175).

**Comment by danielzsh** [comment]
Ah missed that one, thanks!

**Comment by Moshyfawn** [comment]
Be sure to +👍 the other issue.

Duplicate of
- #5175
