### ISSUE TITLE
Flashing rust-analyzer popup

### ISSUE THREAD

**Issue by berkus** [zed-industries/zed#9444]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/80306/a6594921-9075-42aa-880c-05dc22446d5d

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

**Comment by danielzsh** [comment]
I can confirm this issue occurs for clang as well.

**Comment by danielzsh** [comment]
https://github.com/zed-industries/zed/assets/65467530/3cdda487-e1a3-4207-9fb5-c54682026f97

It also occurs really inconsistently...in the video, some of the popups flash, and the others don't.

**Comment by colin-grant-work** [comment]
I wonder whether it has to do with the code merged to fix [this issue](https://github.com/zed-industries/zed/issues/5227)?

**Comment by coolemur** [comment]
I encountered similar flashing problem when I have few files open + terminal open. And make terminal full height.

**Comment by Moshyfawn** [comment]
This has already been brought up in #6990. Let's close this thread in favour of the other one to keep the upvotes and discussion in one place. Be sure to +👍 and add any additional information.

Duplicate of
- #6990

**Comment by colin-grant-work** [comment]
@Moshyfawn, given that the central issue in #6990 is not the same and the behavior reported here seems to be relatively recent - I think that it only started recently, which is why I mentioned #9257, which was merged only last week - I'm not sure they belong on the same ticket.

**Comment by Moshyfawn** [comment]
Missed your comment, my bad. Makes sense. Let's reopen.

**Comment by berkus** [comment]
Seems to be working fine now!
