### ISSUE TITLE
Tasks: Spawn in Center Terminal

### ISSUE THREAD

**Issue by baldwindavid** [zed-industries/zed#9445]
### Check for existing issues

- [X] Completed

### Describe the feature

The recently released #9064 is super-nice to run things like a "Test Under Cursor" task in the "dock".

```json
"space t": ["task::Spawn", { "task_name": "Test Under Cursor" }],
```

However, another use case that I'd like to run as a task is posted in #9067 

I'm simulating a netrw-ish experience by opening in a file explorer (`ya` for yazi explorer in this example) in a center terminal with...

```json
"-": [
  "workspace::SendKeystrokes",
  ": c r p enter : new center terminal enter ya space cmd-v enter"
],
```

This works, but would be much cleaner using this "task_name" argument in a keybinding.

```json
"-": ["task::Spawn", { "task_name": "List Files" }],
```

The issue is that this opens in the "dock" rather than the current pane.

I think it would be nice if a target could be specified alongside the task name with something like...

```json
"-": ["task::Spawn", { "task_name": "List Files", "target": "center" }],
```

By default this "target" could be "dock". I suppose this "target" _could_ instead be specified within the task. This would limit the flexibility a bit, but maybe that's the way to go to avoid spreading task options across both the task and the keybinding.

It appears this request is also noted in a comment within a discussion at https://github.com/zed-industries/zed/discussions/8485#discussioncomment-8795161

**Comment by osiewicz** [comment]
> This would limit the flexibility a bit, but maybe that's the way to go to avoid spreading task options across both the task and the keybinding.

Or, going the other way: Task::Spawn could accept subset of task definition and override them at spawn
A pretty dummy example:
given a definition:
```
{
"label": "My task",
"cmd": "echo",
"args": ["/bin"]
}
```
and a binding:
"-": ["task::Spawn", { "task_name": "My task", "cmd": "ls"}],

When using keybinding, `cmd` field of the original task definition would be overridden with "cmd".
Naturally, you may choose to override just a subset of fields (or no fields at all).

**Comment by baldwindavid** [comment]
@osiewicz That sounds like a slick and consistent way to do it. A few related notes:
- TIL that either "command" or "cmd" can be specified in `tasks.json`
- I wonder about the consistency of the task being named "label" in `tasks.json`, but "task_name" in the keybinding. Supposing these parameters can be overriden via keybinding, I don't think "task_name" is something that one would override. All that is to say, would it be simpler to make those overrides an optional third argument and the task name not in an object at all? (e.g. `"-": ["task::Spawn", "My task", {"cmd": "ls"}],`)
- Digressing here but, ultimately, it would be real nice if Zed someday were to support a target of the currently selected text. For example, if we wanted to, say, rewrap selected text to 80 characters...

```json
  {
    "label": "Reflow Comments",
    "target": "$ZED_SELECTED_TEXT",
    "command": "$ZED_SELECTED_TEXT | fmt -w 80"
  },
```

I would note that the $ZED_SELECTED_TEXT doesn't seem to account for multi-cursor at the moment. For reference, Helix has these commands that have similar behavior, but on all current selections...

```md
| `:insert-output` | Run shell command, inserting output before each selection. |
| `:append-output` | Run shell command, appending output after each selection. |
| `:pipe` | Pipe each selection to the shell command. |
| `:pipe-to` | Pipe each selection to the shell command, ignoring output. |
| `:run-shell-command`, `:sh` | Run a shell command |
```

**Comment by osiewicz** [comment]
Re:
1. Whoops, actually I was writing it off the top of my head; `cmd` is not a thing, sorry. :/
2. Yeah, good point (though I guess we do need to store task_name in the object in the end); I think it may look like:
`"-": ["task::Spawn", { "task_name": "My task", "overrides": {"command": "ls"}}],`
3. Yeah, the story around SELECTED_TEXT is still a bit rough. Right now we're more so focused on integrating with extensions. I think some way to pipe the output back into the editor may be cool, but I'd rather not have us do that right now and extend task capabilities as needed.

**Comment by baldwindavid** [comment]
1. Oh, ha, I actually tried it quickly and thought it worked, but see that it didn't actually save so was using the original.

2. and 3. 👍

**Comment by baldwindavid** [comment]
Closing in favor of #13754

**Comment by susl** [comment]
Hi! 

Could you please reopen this issue as the linked #13754 does not address the ability to be able to spawn a new terminal in the center at all.

I also miss a feature like this, I currently use a combination of tasks and rg+fzf to quickly search and jump to files in zed. I like it a lot and it's pretty close now to telescope in neovim, but I do miss the popup/center terminal a lot.

There's a hack in zed currently to send keystrokes, instead of invoking a task, but it fills like a hack.

Thanks!

**Comment by baldwindavid** [comment]
@susl Sure, I'd like both features, but I'd not seen much interest in task updates since earlier this year and thought perhaps it had been classified as a "won't do". Appears this now has a handful of thumb ups so probably worth keeping open.

**Comment by danielfigueiredo** [comment]
Spawn task in new center terminal would be amazing!
