### ISSUE TITLE
Generation prompt fails to connect to openAI

### ISSUE THREAD

**Issue by htor** [zed-industries/zed#9446]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When hitting`ctrl+enter`, inserting a string`test` and hitting `enter` I get an openAI error message saying:

```
Failed to connect to OpenAI API: The model `gpt-4-1106-preview` does not exist or you do not have access to it. [...]
```

I have credits and a valid API key. The assistant panel works fine with gpt-3 selected (not gpt-4). I would expect the prompt to use the same model, but it insists on using gpt-4 which I probably don't have free access to.

<img width="1440" alt="Screenshot 2024-03-16 at 19 43 33" src="https://github.com/zed-industries/zed/assets/1709263/34644f91-e6b4-4626-9f5c-148c510bc133">

Assistant working nicely:
<img width="1440" alt="Screenshot 2024-03-16 at 19 55 19" src="https://github.com/zed-industries/zed/assets/1709263/45815181-e49f-4e95-bcf2-69e4630a7c4a">

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 12.6.9
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14624918/Zed.log)

**Comment by htor** [comment]
It works now. You just need to override the default settings in `settings.json`: 
```
  "assistant": {
    "provider": {
      "type": "openai",
      "api_url": "https://api.openai.com/v1",
      "default_model": "gpt-3.5-turbo-0613" <----- This line is changed from gpt-4
    }
  }
```

**Comment by Moshyfawn** [comment]
This actually seems to relate to the report from earlier. Be sure to +👍 and add any missing information.

Duplicate of
- #4486

**Comment by seljabali** [comment]
@htor may you please share your complete settings.json file? I tried entering your snippet & it didn't quite work out for me. Thanks

**Comment by Moshyfawn** [comment]
> @htor may you please share your complete settings.json file? I tried entering your snippet & it didn't quite work out for me. Thanks

This worked for me

```json
  "assistant": {
    "provider": {
      "type": "openai",
      "api_url": "https://api.openai.com/v1",
      "default_model": "gpt-3.5-turbo-0613"
    }
  }
}
```

You need to restart Zed for this setting to take effect.
