### ISSUE TITLE
cursorSurroundingLines

### ISSUE THREAD

**Issue by ericviana** [zed-industries/zed#9447]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, Zed lacks a configuration option to set the number of surrounding lines visible when navigating through a file, akin to the cursorSurroundingLines feature in VSCode. This feature is invaluable for users who prefer to keep their cursor centered within the viewport while scrolling through code.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1062" alt="Screenshot 2024-03-16 at 17 30 26" src="https://github.com/zed-industries/zed/assets/76598237/c0ba3cdb-13f2-4f67-8970-b93634478495">

**Comment by christofferbergj** [comment]
Are you looking for this setting?

```json
"vertical_scroll_margin": 8
```

**Comment by ericviana** [comment]
@christofferbergj
That's exactly what I wanted, thank you.
