### ISSUE TITLE
Relative Date

### ISSUE THREAD

**Issue by abtonc** [zed-industries/zed#9457]
### Check for existing issues

- [X] Completed

### Describe the feature

You can use shields to provide more readable "updated at" information at #5393 in addition to full EDT string.

[Documentation](https://shields.io/badges/relative-date)

Couldn't add "open source" label.

### If applicable, add mockups / screenshots to help present your vision of the feature

example:
https://img.shields.io/date/1710569311?label=Updated

preview:
![Preview](https://img.shields.io/date/1710569311?label=Updated)

**Comment by maxdeviant** [comment]
Thanks for the suggestion, @abtonc!

I don't think this is necessary, as that timestamp is moreso just to know that the bot is running (it could probably even get moved to the footer of that issue body).
