### ISSUE TITLE
storybook focus.rs broke at tag v0.127.0-pre

### ISSUE THREAD

**Issue by stormasm** [zed-industries/zed#9462]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- [focus.rs](https://github.com/zed-industries/zed/blob/main/crates/storybook/src/stories/focus.rs)

worked fine at https://github.com/zed-industries/zed/releases/tag/v0.126.2

but for some reason is no longer working here

https://github.com/zed-industries/zed/releases/tag/v0.127.0-pre

Wanted to write a quick note about it and will do more research and update more
tomorrow as I chase down what happened...

### Environment

Zed: v0.127.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by stormasm** [comment]
@as-cii Unfortunately I "think" https://github.com/zed-industries/zed/pull/9012
is the commit point where this code no longer working...

I tested the code at this commit point and it works https://github.com/zed-industries/zed/pull/9073

If this is indeed the case --- any insight as to why this code may have broken focus.rs and a path forward to possibly fix it would be much appreciated.

In the meantime I will do more research to try and figure out what in #9012 would have caused the storybook focus.rs story to no longer work...

Thank you !

**Comment by stormasm** [comment]
Unless the fix is simple I may go ahead and just rewrite this story so it takes advantage of 

```rust
impl FocusableView for FocusStory
```

for both the parent and the two children...

**Comment by as-cii** [comment]
Thanks for noticing this, @stormasm! It should be fixed now.
