### ISSUE TITLE
Some characters cannot be typed using Hungarian keyboard layout

### ISSUE THREAD

**Issue by palotasb** [zed-industries/zed#9465]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Some characters cannot be typed using a Hungarian keyboard layout, such as `[` or `{`. Both are typed using the right `Alt` key plus `f` or `b` respectively, so maybe a default keybinding is interfering with the keyboard input.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
You are exactly correct in your guess, the default keymap contains:
```
      "alt-b": "editor::MoveToPreviousWordStart",
      "alt-f": "editor::MoveToNextWordEnd",
```
To fix this for Hungarian you can remove them by adding the following to your keymap (cmd-k cmd-s):

```json
[
  {
    "bindings": {
      "alt-b": null,
      "alt-f": null
    }
  }
]
```

**Comment by ConradIrwin** [comment]
(you may need to do the same for alt-{d,h,t,v,z} too)
