### ISSUE TITLE
Saving multi buffer should only touch modified files

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#9475]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure if this is a 'bug'.

Now saving a multi buffer will save all the related buffers / files. 

This will cause some unexpected behaviors. Supposed there are 10 buffers there (created by project search), and only 2 are modified, the other 7 buffers will also be saved. If "format on save" option is on, those 7 buffer will also be formatted even if they are not modified.

Moreover, even one do nothing on the any of the search results and simply press "save" shortcut, the buffers will still be touched and saved.

### Environment

Zed: v0.127.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment]
Both #5148 and #9475 touch a little on the general behaviour.
