### ISSUE TITLE
Orphan Node Process After Zed Quit (And Sometimes Node 100+% CPU Usage)

### ISSUE THREAD

**Issue by Congyuwang** [zed-industries/zed#9482]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Launch Zed
- Quit Zed
- Check Processes

https://github.com/zed-industries/zed/assets/52687642/4d8dee86-7d2a-4f08-b502-eb40f6ecec45

### Environment

Zed: v0.127.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by Congyuwang** [comment]
After a while, you get many node processes in your ps.

**Comment by Congyuwang** [comment]
Sometimes the node process does terminate with Zed. But sometimes it doesn't.

**Comment by mrnugget** [comment]
> * Quit Zed.

How do you quit Zed? `Cmd-q`? 

Can you double-click on that `node` process in Activity Monitor and share what open files/ports there are?

![screenshot-2024-03-18-10 47 01@2x](https://github.com/zed-industries/zed/assets/1185253/9cda82d9-6f49-4c6d-9551-93d0a86dfee0)

Also: can you reproduce without the HTTP Proxy?

**Comment by Congyuwang** [comment]
```
/
/Users/congyuwang/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node
/Library/Preferences/Logging/.plist-cache.wJ1zQyEi
count=0, state=0
->0xd34c6ddb16e108bb
->0x7f2ad81e1608ffc2
->0x3f0661dedaba8ce1
->0x4251cd543a1cb6da
->0x5b8e9bdd4679249c
->0xe09a77c471638aa3
->0x6099311481aac8d0
->0x3cee5284165dbd36
count=0, state=0xa
->0xe1f001c956020258
->0x1d5772f18038ab79
->0xc67c8b5dfa26bb7a
->0x212f82a090ced6d1
count=0, state=0xa
->0xdfd4691c9ade3e6f
->0xb0b8da0cce4b299
->0xa54a44565423aa13
->0xf230626631cec1d2
/dev/null
->0x9794602cfea487dd
10.30.40.216:57032->20.205.243.168:https
->0x74cda15b86a7758a
->0xf8bee8cd04f0feff
->0x82e6d44608d17f4e
->0x94e39ead52ff305e
[ctl com.apple.netsrc id 7 unit 71]
/private/var/folders/fc/bckw5h_s4c9fz9dlgltf7b840000gn/C/dev.zed.Zed-Preview/com.apple.metal/16777235_402/functions.data
/private/var/folders/fc/bckw5h_s4c9fz9dlgltf7b840000gn/C/dev.zed.Zed-Preview/com.apple.metal/16777235_402/functions.list
```


https://github.com/zed-industries/zed/assets/52687642/7761e3e4-6d60-42b3-8f78-bc6531067b4e


Yes. Can reproduce without proxy. But also note as is in the screen recording, Zed stuck trying to check rust-analyzer update, so perhaps the connection to GitHub is not good.
