### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by AA1999** [zed-industries/zed#9488]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As a continuation of #8168 after running `WAYLAND_DISPLAY='' cargo run` on the zed git repo I get the following output:

https://pastebin.com/FXCKzJwc

I'm not entirely sure why this happens as the `.git` directory in the repo has been unaltered

### Environment

OS: Arch Linux x86_64
Kernel: 6.8.1-arch1-1
DE: KDE Plasma 6.0.2
WM: KWin (Wayland)
CPU: Intel(R) Core(TM) i7-7700HQ (8) @ 3.80 GHz
GPU 1: NVIDIA GeForce GTX 1050 Ti Mobile

**Comment by mikayla-maki** [comment]
This looks like a strange build error on your system. I'd suggest wiping out your Zed clone and trying from a fresh clone, but not really the kind of thing we can do more with.

**Comment by dzid26** [comment]
I have that on a fresh clone on Windows. Similarly it is caused by the `curl-sys`.

It doesn't like gcc:
```
warning: curl-sys@0.4.67+curl-8.3.0: gcc: fatal error: no input files
warning: curl-sys@0.4.67+curl-8.3.0: compilation terminated.
warning: curl-sys@0.4.67+curl-8.3.0: ToolExecError: Command "C:\\Users\\dzidm\\.cargo\\bin\\sccache.exe" "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "curl/lib" "-I" "curl/include" "-I" "C:\\Users\\dzidm\\Downloads\\zed\\target\\release\\build\\libz-sys-6e24cc93abfc54dd\\out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\Users\\dzidm\\Downloads\\zed\\target\\release\\build\\curl-sys-b31617ee090e8e33\\out\\build\\4da0da058b5259b3-headers.o" "-c" "curl/lib/headers.c" with args "gcc" did not execute successfully (status code exit code: 1).cargo:warning=GNU compiler is not supported for this target
```

I had a `CC=gcc` system env.  I removed it and it went through.  Ehh
