### ISSUE TITLE
File management creates Aliases

### ISSUE THREAD

**Issue by savoygrizzly** [zed-industries/zed#9489]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the side file viewer to create or move file it can become a real pain and break your entire tree. I noticed on multiple occasions when renaming folders that Zed seems to create aliases, you end up with instance of a single file being open (say you rename a folder productView to ProductView and had the file ProductView.js that was inside an open in the editor). The ProductView.js file will sometimes open a second time, except one will be shown as coming from an alias: ProductView/ProductView.js and the other one from productView/ProductView.js

closing and reopening the editor or the project’s folder doesn’t fix it. The only solution is to delete the folder via the Finder (after quitting Zed), then opening Zed, and the recreating the folder (this time obviously you either use the terminal or the Finder because you don’t wanna waste your time again)

### Environment

Mac OS Sonoma

**Comment by Moshyfawn** [comment]
Sounds similar to #4797
