### ISSUE TITLE
Pane resize available through expanded bottom panel

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9501]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the bottom panel is expanded to full screen, the panels below it can still be resized. The expected behaviour is that the resize cursor doesn't appear and panes can't be resized if they are under the bottom panel.

### Environment

Zed: v0.127.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/e9ebda3d-4c11-4169-86c2-55b2a3c988ec

**Comment by osiewicz** [comment]
I can't repro it on the latest nightly. You can still resize the panes by grabbing a divider above the terminal, but I can't do it on the terminal itself.

**Comment by Moshyfawn** [comment]
I'm stilling seeing it in `Zed Nightly 0.129.0` 🤔

https://github.com/zed-industries/zed/assets/16290753/d1a0ed1d-1d52-474c-99fb-cd6758e46917

**Comment by osiewicz** [comment]
Oh, I see! I can indeed repro it too.

I was trying to resize the pane divider, whereas here it's the vertical panel divider that's leaking through.
