### ISSUE TITLE
the hover state of menu items shouldn't get passed through to menu items beneath

### ISSUE THREAD

**Issue by slymax** [zed-industries/zed#9519]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/3922572/a4b2b6d6-6c26-4024-a635-6594ff7f6892

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
For context, this is a known issue stemming from the solution to the flickering problems made in https://github.com/zed-industries/zed/pull/9012.

**Comment by ConradIrwin** [comment]
This was fixed by the 0.127 release
