### ISSUE TITLE
https://zed.dev/features is not linked to in the docs

### ISSUE THREAD

**Issue by bartekpacia** [zed-industries/zed#9534]
### Check for existing issues

- [X] Completed

### Describe the feature

I did a Google search for "Zed outline view" and the first result is this page: https://zed.dev/features

But it is not linked to from [the main documentation](https://zed.dev/docs/getting-started), which I find a bit strange.

**Comment by maxdeviant** [comment]
This page hasn't been updated recently, so that's why we're not linking to it, at present.

We're going to rework it at some point.
