### ISSUE TITLE
Move between panes with `CTRL+{HJKL}` in Vim mode.

### ISSUE THREAD

**Issue by t-eckert** [zed-industries/zed#9547]
### Check for existing issues

- [X] Completed

### Describe the feature

This is similar to the issue [here](https://github.com/zed-industries/zed/issues/5574). That issue describes moving between panes using `CTRL+W` followed by `hjkl` as commonly seen in Vim. Extending this idea, many Vim users will configure `CTRL+{hjkl}` directly in order to move between panes (or buffers in Vim). 

Is this something I can do today by adding something to my Zed configuration? If so, I think that suffices. If not, I would love to have this be implemented as it's one of the key parts of my flow when working in Vim. 

Thank you so much for your hard work on Zed!

**Comment by ConradIrwin** [comment]
@t-eckert You can!

If you open your custom key-bindings (type `:keymap` in vim mode) you can add:
```
{
  "bindings": {
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"],
  }
}
```

**Comment by t-eckert** [comment]
Wonderful! Thank you!

**Comment by christian-gama** [comment]
I had to do something like this to work properly, because once I was in the terminal, it did not change the Pane and sometimes when I was in the ProjectPanel moving to the right direction would not work. Doing something like this makes everything work as expected.

```json
{
  {
    "bindings": {
      "ctrl-w ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-w ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-w ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-w ctrl-j": ["workspace::ActivatePaneInDirection", "Down"]
    }
  },
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-w ctrl-k": "workspace::ActivateNextPane"
    }
  },
  {
    "context": "ProjectPanel",
    "bindings": {
      "ctrl-w ctrl-l": "workspace::ActivateNextPane"
    }
  }
}
```

**Comment by nmsobri** [comment]
> @t-eckert You can!
> 
> If you open your custom key-bindings (type `:keymap` in vim mode) you can add:
> 
> ```
> [
>   {
>     "bindings": {
>       "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
>       "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
>       "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
>       "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"],
>     }
>   }
> ]
> ```

is this bindings even work? i tested on `0.145.1` and its not working

**Comment by nmsobri** [comment]
> @t-eckert You can!
> 
> If you open your custom key-bindings (type `:keymap` in vim mode) you can add:
> 
> ```
> [
>   {
>     "bindings": {
>       "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
>       "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
>       "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
>       "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"],
>     }
>   }
> ]
> ```

i tested this one on `0.145.1` and moving down and up the pane its not working

**Comment by lungarella-raffaele** [comment]
I am on 0.162.5 and moving from pane to pane is working effortlessly with this configuration:
```
[
  {
    "bindings": {
      "ctrl-h": ["workspace::ActivatePaneInDirection", "Left"],
      "ctrl-l": ["workspace::ActivatePaneInDirection", "Right"],
      "ctrl-k": ["workspace::ActivatePaneInDirection", "Up"],
      "ctrl-j": ["workspace::ActivatePaneInDirection", "Down"],
    }
  }
]
```

**Comment by Codys-Wright** [comment]
Commenting for posterity, make sure to but it in the "Editor" context in order to have it override the defaults of toggle search and selection etc. 

```
 {
    "context": "Editor",
    "bindings": {
      "ctrl-h": "workspace::ActivatePaneLeft",
      "ctrl-l": "workspace::ActivatePaneRight",
      "ctrl-k": "workspace::ActivatePaneUp",
      "ctrl-j": "workspace::ActivatePaneDown"
    }
  },
```

**Comment by IbraMF** [comment]
You could also add "Terminal" as context so you can change the Pane from terminals too.

```json
{
    "context": "Editor || Terminal",
    "bindings": {
      "ctrl-h": "workspace::ActivatePaneLeft",
      "ctrl-l": "workspace::ActivatePaneRight",
      "ctrl-k": "workspace::ActivatePaneUp",
      "ctrl-j": "workspace::ActivatePaneDown"
    }
},
```

**Comment by nathanyu1** [comment]
To also include project panel as of April 2026:
```
{
    "context": "Editor || Terminal || ProjectPanel",
    "bindings": {
      "ctrl-h": "workspace::ActivatePaneLeft",
      "ctrl-l": "workspace::ActivatePaneRight",
      "ctrl-k": "workspace::ActivatePaneUp",
      "ctrl-j": "workspace::ActivatePaneDown",
    },
  },
```
