### ISSUE TITLE
Zed doesn't appear to read from import_map.json (Deno)

### ISSUE THREAD

**Issue by NetOpWibby** [zed-industries/zed#9555]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed views my import paths as errors because `Relative import path "edgedb" not prefixed with / or ./ or ../`.

<img width="648" alt="SS 2024-03-19 at 7 29 09 PM" src="https://github.com/zed-industries/zed/assets/1288356/42056f54-7e39-422a-b0b6-f0e7c56c0e34">

However, my `import_map.json` contains:

```json
{
  "imports": {
    "dbschema": "./dbschema/edgeql-js/index.ts",
    "dbschema/": "./dbschema/edgeql-js/",
    "dep/": "./dep/",
    "edgedb": "https://deno.land/x/edgedb@v1.4.1/mod.ts",
    "edgedb/": "https://deno.land/x/edgedb@v1.4.1/",
    "src/": "./src/",
    "std/": "https://deno.land/std@0.213.0/"
  }
}
```

This behavior is supported by [Deno's documentation](https://docs.deno.com/runtime/manual/basics/import_maps).

### Environment

Zed: v0.126.3 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
Check out this discussion for possible solution https://github.com/zed-industries/zed/issues/5361#issuecomment-1922777342.

**Comment by NetOpWibby** [comment]
Guess I have to add `"importMap": "import_map.json"` to my `deno.json` file. Sublime Text doesn't but ah well. Fixed?
