### ISSUE TITLE
Project is not permissioned for semantic indexing when semantic_index true

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9558]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

~~I tried to edit a copy of Zed Log in a new unsaved "untitled" file using the inline assistant, but it never ran and displayed in a pending state. The logs contained the error below.~~

I've specifically enabled semantic search by default.

```json
"semantic_index": {
  "enabled": true
}
```

But I keep getting the error mentioned below in my logs. 

I don't have the search / project search open.

### Environment

Zed: v0.127.3 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```log
[ERROR] crates/assistant/src/assistant_panel.rs:3069: project is not permissioned for semantic indexing
```

**Comment by Moshyfawn** [comment]
I've had to update the title and description of the issue as I've found that the inline assistant was actually running, but I couldn't see the progress due to the length of the file I was trying to edit _(can probably become an enhancement request)_.

I'll leave the first part of my report in crossed over for context. I still get the error log mentioned from time to time. It may be related to when I run the inline assistant, but I can't figure out the pattern.

**Comment by Moshyfawn** [comment]
> The semantic index was removed in #7367:
> 
> > We are temporarily removing the semantic index in order to redesign it from scratch.

I see. So the error is the consequence of that change discussed in #9564, right?

**Comment by maxdeviant** [comment]
> > The semantic index was removed in #7367:
> > > We are temporarily removing the semantic index in order to redesign it from scratch.
> 
> I see. So the error is the consequence of that change discussed in #9564, right?

Not sure if it's related (as I think those changes only _just_ went out), but I think we can close, as it's not relevant anymore.

**Comment by Moshyfawn** [comment]
Sounds good, thanks for the info!
