### ISSUE TITLE
Image scaling doesn't occur when shrinking Zed vertically

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9560]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The image is scaled when shrinking the window horizontally, but not when shrinking vertically.

### Environment

Zed: v0.128.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/19867440/1dd1e39e-610b-4536-9161-7dcb969a489d

**Comment by JosephTLyons** [comment]
cc @rgbkrk

**Comment by rgbkrk** [comment]
Thanks for reporting this!

**Comment by DissolveDZ** [comment]
pretty sure this can be closed

**Comment by JosephTLyons** [comment]
This appears to be fixed in 0.161.0.
