### ISSUE TITLE
The indentation differs between 'npx prisma format' and 'format_on_save' in Prisma.

### ISSUE THREAD

**Issue by Ko1103** [zed-industries/zed#9567]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When saving the schema.prisma file in Zed, the indentation is changed to four spaces. When using 'npx prisma format', the indentation is changed to two spaces. I want to align it with 'npx prisma format'.

I have prepared a git repository to reproduce both cases.
https://github.com/Ko1103/prisma-format-reproduce

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.2
Memory: 16 GiB
Architecture: arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Using `format_on_save` in Zed
<img width="1552" alt="スクリーンショット 2024-03-20 17 38 15" src="https://github.com/zed-industries/zed/assets/22885290/b54acab2-23ac-4d97-89c7-005626a75d26">

Using `npx prisma format`
<img width="1552" alt="スクリーンショット 2024-03-20 17 38 27" src="https://github.com/zed-industries/zed/assets/22885290/8756c2b8-e9a9-4c62-b09e-52164d5286f9">

**Comment by Moshyfawn** [comment]
Have you tried specifying an external [`formatter`](https://zed.dev/docs/configuring-zed#formatter) in the settings?

**Comment by Ko1103** [comment]
@Moshyfawn I tried it, but it remained indented with four spaces and did not improve.

I changed .zed/settings.json 

```json
// Folder-specific settings
//
// For a full list of overridable settings, and general information on folder-specific settings,
// see the documentation: https://zed.dev/docs/configuring-zed#folder-specific-settings
{
  "language_overrides": {
    "Prisma": {
      "format_on_save": "on",
      "formatter": "language_server" // I added this line.
    }
  }
}
```

**Comment by alexewsv** [comment]
Here are my config it works 

```
"languages": {
		"Prisma": {
			"formatter": {
				"language_server": {
					"name": "prisma-language-server"
				}
			}
		},
		"JavaScript": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		},
		"TypeScript": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		},
		"TSX": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		},
		"GraphQL": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		},
		"HTML": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		},
		"CSS": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		},
		"JSON": {
			"formatter": {
				"language_server": {
					"name": "biome"
				}
			}
		}
	}

```
