### ISSUE TITLE
[Vim] w, e, b motions are skipping punctuation

### ISSUE THREAD

**Issue by hnbnh** [zed-industries/zed#9576]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When encountering a string with punctuation like `:` within a word, such as `Hello::World`

If the cursor is on the `H`, pressing the `w` key does not advance it to the `W`. Instead, it moves to the next line.

For example,

```text

Hello::World
^
Test
```

- Press `w`
```text
Hello::World
Test
^
```

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
Hmm, this is working for me...

@hnbnh do you have any custom keybindings, or are you editing a particular file type? (vim mode respects a given language's notion of word character).

**Comment by mrnugget** [comment]
Are you, by any chance, in Ruby? Because if so, I think the fix to this has been merged last week: https://github.com/zed-industries/zed/pull/9170 So it should be in 0.127.x

**Comment by hnbnh** [comment]
@mrnugget Yes I was in Ruby, update to 0.127.3 fixed the issue, thank you!

**Comment by sersorrel** [comment]
This still happens with `-` in Markdown files, which is moderately disconcerting.

**Comment by mrnugget** [comment]
> This still happens with `-` in Markdown files, which is moderately disconcerting.

Seems like that was added by @bennetbo in https://github.com/zed-industries/zed/pull/7514.

And yeah, in Vim `-` is not part of a "word" in markdown.
