### ISSUE TITLE
Dependency Conflict with `tree-sitter` when using `settings` from GPUI

### ISSUE THREAD

**Issue by PierreLouisLetoquart** [zed-industries/zed#9585]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When attempting to build a new Rust project with the `settings` dependency sourced from the zed.dev UI lib GPUI 2, a conflict arises with the `tree-sitter` package. The error message suggests that the `settings` package requires a version of `tree-sitter` with the `wasm` feature, but no such version is currently available.

**Steps to Reproduce:**

1. Create a new Rust project using Cargo:
```bash
cargo new gpui-testing
```
2. Edit the `Cargo.toml` file to include the `settings` dependency:
```toml
[dependencies]
settings = { git = "https://github.com/zed-industries/zed" }
```
3. Build or run the project using Cargo:
```bash
cargo build
cargo run
```
**Error Output:**
```sql
    Updating git repository `https://github.com/zed-industries/zed`
    Updating crates.io index
    Updating git repository `https://github.com/zed-industries/font-kit`
    Updating git repository `https://github.com/DioxusLabs/taffy`
    Updating git repository `https://github.com/kvark/blade`
    Updating git repository `https://github.com/zed-industries/bromberg_sl2`
error: failed to select a version for `tree-sitter`.
    ... required by package `settings v0.1.0 (https://github.com/zed-industries/zed#59bc81d1)`
    ... which satisfies git dependency `settings` of package `gpui-testing v0.1.0 (/path/to/gpui-testing)`
versions that meet the requirements `^0.20` are: 0.20.10, 0.20.9, 0.20.8, 0.20.7, 0.20.6, 0.20.5, 0.20.4, 0.20.3, 0.20.2, 0.20.1, 0.20.0

the package `settings` depends on `tree-sitter`, with features: `wasm` but `tree-sitter` does not have these features.

failed to select a version for `tree-sitter` which could resolve this conflict
```
**Attempted Resolution:**

I have attempted to resolve the issue by using a previous commit of the `settings` dependency. However, this approach is a workaround and introduces other errors. I am currently testing alternative solutions and will update this issue if I find a satisfactory resolution.

To test it with previous commits:

```
settings = { git = "https://github.com/zed-industries/zed", rev="sha..." }
```

### Environment

Hardware Overview:

      Model Name: MacBook Pro
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      Activation Lock Status: Enabled

System Software Overview:

      System Version: macOS 14.3.1 (23D60)
      Kernel Version: Darwin 23.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: mac
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

**Comment by osiewicz** [comment]
Hi,
We're using a patch version of tree-sitter, as seen [in our Cargo.toml](https://github.com/zed-industries/zed/blob/main/Cargo.toml#L378). I'm afraid you'd have to use that version as well to make dependency resolution happy.

**Comment by PierreLouisLetoquart** [comment]
Hello,

I get it .. thanks for the info !

**Comment by osiewicz** [comment]
I'm gonna close this issue for now. Feel free to reopen if that problem arises again in the future.
