### ISSUE TITLE
Toolbar Overlay Rendering Artifact

### ISSUE THREAD

**Issue by CurbaiCode** [zed-industries/zed#9588]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open menu item `Zed` > `About Zed...` or command `Zed: copy system specs to clipboard`.

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 12.6.6
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present the bug

![Screen Shot 2024-03-20 at 11 54 35 AM](https://github.com/zed-industries/zed/assets/47488521/9eefec96-2e59-4cdc-9995-0955f5aeaddc)

**Comment by Moshyfawn** [comment]
Interesting. I can't seem to reproduce.

<img width="754" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/efe978dc-f786-441e-94f4-37cb9b1780c8">

**Comment by 0x2CA** [comment]
me too

Zed: v0.128.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

https://github.com/zed-industries/zed/assets/19868292/52f22772-e2c9-4bc6-9b8d-07f41bb51774

**Comment by Moshyfawn** [comment]
Closed in #9812
