### ISSUE TITLE
Clipped Traffic Light Control Buttons

### ISSUE THREAD

**Issue by CurbaiCode** [zed-industries/zed#9589]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See title.

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 10.15.7
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present the bug

![Screen Shot 2024-03-20 at 11 55 05 AM](https://github.com/zed-industries/zed/assets/47488521/ca8402b9-bf47-4e64-9c54-ee633a73bedd)

**Comment by JosephTLyons** [comment]
I'm not sure how to reproduce this and I've not see it personally. I'm going to close this issue out, but feel free to open a new one if you run into it again.
