### ISSUE TITLE
Inline assistant modal for GitHub Copilot and not only for OpenAI key.

### ISSUE THREAD

**Issue by dimeeentor** [zed-industries/zed#9593]
### Check for existing issues

- [X] Completed

### Describe the feature

To be able to trigger this kind of modal when using GitHub Copilot:
<img width="729" alt="image" src="https://github.com/zed-industries/zed/assets/32683179/a78addf8-a36e-410e-8278-186d05f4d027">

Right now when I trigger **Inline Assistant**, I get only this option – OpenAI API key:
<img width="1608" alt="image" src="https://github.com/zed-industries/zed/assets/32683179/2abc5a40-4bcb-4410-a127-aaf198644b5f">

**Comment by Moshyfawn** [comment]
You will need to provide your own OpenAI key to be able to use the Inline Assistant at this stage.
