### ISSUE TITLE
Can't enable Copilot

### ISSUE THREAD

**Issue by enjoythemomentum** [zed-industries/zed#9597]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Can't enable Copilot even though it is "enabled" in settings. 

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/43861907/cd6d6e2c-bdbf-4fef-9b0e-fdc6dbe54fb2)

**Comment by Moshyfawn** [comment]
Just a sanity check: have you logged in to Copilot?

<img width="1017" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/26355824-fb2d-444f-a726-fd75fbf8de46">

**Comment by pibotdev** [comment]
Same here. Both of these two buttons are unresponsive for me. Cannot even connect in the first place. (MacBook Pro, Sonoma 14.1.1 / Zed 0.127.3)
<img width="348" alt="image" src="https://github.com/zed-industries/zed/assets/54510730/ae899c2a-c897-4f6b-8fb2-ed57f0fe1b0e">

**Comment by Moshyfawn** [comment]
> Same here. Both of these two buttons are unresponsive for me. Cannot even connect in the first place. (MacBook Pro, Sonoma 14.1.1 / Zed 0.127.3) <img alt="image" width="348" src="https://private-user-images.githubusercontent.com/54510730/314668650-ae899c2a-c897-4f6b-8fb2-ed57f0fe1b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NjgwODksIm5iZiI6MTcxMDk2Nzc4OSwicGF0aCI6Ii81NDUxMDczMC8zMTQ2Njg2NTAtYWU4OTljMmEtYzg5Ny00ZjZiLThmYjItZWQ1N2YwZmUxYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIwNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MmQwMjJmOTY2YmRkYjkwNDYyOGI3ZjI3NGNmN2M2OTU0ZmQ5ZmFiOWJkNzg3ZWMzMzRkNTVlNzVhYjk1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m0kEktaAEm70kHyZbB6VJCxefXVVHvQZZR8rWuQ0BzI">

The problem you're experiencing seems to be the one described in #9596.

**Comment by Moshyfawn** [comment]
Have you noticed anything strange in the Zed logs when you try to login/activate Copilot `zed: open log`?

**Comment by yeo311** [comment]
Same here. This is the log.
```
2024-03-22T22:32:29+09:00 [ERROR] Cancelled LSP request task for "signInConfirm" id 7 which took over 120s
2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-22T22:34:09+09:00 [ERROR] crates/ai/src/providers/open_ai/embedding.rs:177: NotPresent
2024-03-22T22:34:09+09:00 [ERROR] crates/semantic_index/src/semantic_index.rs:87: user is not authenticated
2024-03-22T22:35:32+09:00 [ERROR] Cancelled LSP request task for "signInConfirm" id 9 which took over 120s
```

**Comment by Moshyfawn** [comment]
> Same here. The button doesn't respond. This is the log. (Sonoma 14.3.1 / Zed 0.127.3)
> 
> ```
> 2024-03-22T22:32:29+09:00 [ERROR] Cancelled LSP request task for "signInConfirm" id 7 which took over 120s
> 2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
> 2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
> 2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
> 2024-03-22T22:34:07+09:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
> 2024-03-22T22:34:09+09:00 [ERROR] crates/ai/src/providers/open_ai/embedding.rs:177: NotPresent
> 2024-03-22T22:34:09+09:00 [ERROR] crates/semantic_index/src/semantic_index.rs:87: user is not authenticated
> 2024-03-22T22:35:32+09:00 [ERROR] Cancelled LSP request task for "signInConfirm" id 9 which took over 120s
> ```

"The button doesn't respond": this is the other issue #9596 that's been fixed in [`0.128.1`](https://zed.dev/releases/preview/0.128.1).

**Comment by Moshyfawn** [comment]
Hi @enjoythemomentum. I've come across #7309 where they had a problem with the Copilot modal being cut off. Can you check if that's the case for you or not?

They recommend trying to set `"show_copilot_suggestions": false`.

**Comment by enjoythemomentum** [comment]
> Hi @enjoythemomentum. I've come across #7309 where they had a problem with the Copilot modal being cut off. Can you check if that's the case for you or not?
> 
> They recommend trying to set `"show_copilot_suggestions": true`.

Yes! Thank you! Sorry for late reply.
