### ISSUE TITLE
Prettier doesn't work in 127.3

### ISSUE THREAD

**Issue by znycheporuk** [zed-industries/zed#9600]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Getting error when trying to format file with prettier after update, worked fine in 126.3

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/42861377/cba8f344-5681-433b-abab-387f6fa0a3ba

https://github.com/zed-industries/zed/assets/42861377/de02eafc-cb1f-433b-b2e4-8595fc293912

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14672842/Zed.log)

**Comment by znycheporuk** [comment]
I also tried Zed Preview 128.0, and issue is also present there

**Comment by znycheporuk** [comment]
Tried to format another project that uses biome, and it does work
<img width="1728" alt="Screenshot 2024-03-21 at 00 03 22" src="https://github.com/zed-industries/zed/assets/42861377/4545dfac-4cf4-427f-a14a-e15ff4f2908e">

**Comment by mrnugget** [comment]
What happens if you use `"formatter": "prettier"`?

**Comment by RemcoSmitsDev** [comment]
> What happens if you use `"formatter": "prettier"`?

Yeah, or if you really want to specify it like this, you have to add `npx` before the `prettier` command.
```json
{
  "formatter": {
    "external": {
      "command": "npx prettier",
      "arguments": ["--stdin-filepath", "{buffer_path}"]
    }
  }
}
```

**Comment by znycheporuk** [comment]
@mrnugget, it did help, thank you
