### ISSUE TITLE
`api_url` for openai provider in v0.128.0

### ISSUE THREAD

**Issue by Congyuwang** [zed-industries/zed#9617]
### Check for existing issues

- [X] Completed

### Describe the feature

Previous versions allow setting custom api_url for openai, which allows custom reverse proxy.
```json
{
  "assistant": {
    "provider": {
      "type": "openai",
      "api_url": "https://api.openai.com/v1",
      "default_model": "gpt-4-turbo-preview"
    }
  }
}
```

However, since v0.128, `api_url` just disappeared?
```json
{
  "assistant": {
    "provider": {
      "name": "openai",
      "default_model": "gpt-4-turbo-preview"
    }
  }
}
```

Further, what does the change from `type` to `name` mean? This is not in the release note.

**Comment by Moshyfawn** [comment]
You still can provide `assistant.provider.api_url`.

```json
{
  "assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "api_url": "https://api.openai.com/v1"
    }
  },
}
```

**Comment by Moshyfawn** [comment]
The assistant settings shape has been updated in #7367 to allow for the proxing of the AI interactions through Zed servers.

**Comment by Congyuwang** [comment]
Ok. Got it. The problem is with my own connection. Sry.
