### ISSUE TITLE
Transparency / Blurry for Different Panels

### ISSUE THREAD

**Issue by Congyuwang** [zed-industries/zed#9620]
### Check for existing issues

- [X] Completed

### Describe the feature

Related issue: #5040

I see that PR #9610 enables blurred / transparent window background, which is great. But it would be even more awesome to allow setting **different parts** of the window blurred / transparent, since making the text editing part opaque gives clearer code display.

For example, Xcode makes the left panel blurry, but the main editor part opaque:

<img width="1470" alt="截圖 2024-03-21 13 34 17" src="https://github.com/zed-industries/zed/assets/52687642/d648b160-0a93-4d44-8dcc-7b013006ea7f">

Having a blurred project / left panel gives a beautiful and native feel, while making the main editor part opaque is still most helpful for text editing.

**Comment by jansol** [comment]
This is easy to do with #9610, since themes have different keys for the background of the project pane and the editor. If you make the editor background opaque, the project pane transparent, and set window background to blurred you get essentially the effect described here.

**Comment by evrsen** [comment]
> This is easy to do with #9610, since themes have different keys for the background of the project pane and the editor. If you make the editor background opaque, the project pane transparent, and set window background to blurred you get essentially the effect described here.

Hi, how can i do this, what's the settings.json i need to configure?

**Comment by jansol** [comment]
It needs to be done in your theme, not settings. (but for testing and small tweaks you can use `experimental.theme_overrides`)

You need to set `background.appearance` to "blurred" or "transparent" and then make sure *all* background colors in your theme have an alpha value that is not "ff" (unless you want some individual backgrounds to be opaque).

**Comment by DataRaj** [comment]
> You need to set `background.appearance` to "blurred" or "transparent" and then make sure _all_ background colors in your theme have an alpha value that is not "ff" (unless you want some individual backgrounds to be opaqu

please share your configs, I not working in my linux machine

**Comment by jansol** [comment]
The easiest way to get started is to install a theme that is already transparent such as `Catpuccin Blur` from the Extensions store.

Also, if you are using X11 without a compositor I don't think transparency can work properly. And blur on Linux currently only works on KDE when running in Wayland mode.
