### ISSUE TITLE
Zed is not opening

### ISSUE THREAD

**Issue by ArmmGh** [zed-industries/zed#9623]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since yesterday after Zed update to v0.127.3 it basically stopped opening.
Tried:
- Logs are clear and no any logs after trying opening Zed
- Reinstall Zed and download from github
- Installed Zed via Homebrew
- Opening a folder via Zed CLI
- Restart Macbook

seems similar to this issue, but no https://github.com/zed-industries/zed/issues/9493

Will be very appreciated if you help with solving the issue!!

### Environment

Environment
Zed: v0.127.3 (Zed)
OS: macOS 14.4
Memory: 18 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
What's the output of `ls -la /Applications/Zed.app/Contents/MacOS` on your machine?

**Comment by ArmmGh** [comment]
<img width="439" alt="image" src="https://github.com/zed-industries/zed/assets/21320770/833acdb8-9c82-491e-a47d-c50fa46eacaa">

**Comment by osiewicz** [comment]
OK, good; at first glance you seem to have universal binary, so the update did go through.

What happens when you run zed from that directory in the shell? Does it open for you?
`/Applications/Zed.app/Contents/MacOS/zed`

**Comment by ArmmGh** [comment]
Hmm seems some permission problem

<img width="701" alt="image" src="https://github.com/zed-industries/zed/assets/21320770/7c83e734-fa89-44bd-8870-8f9b9db6a90d">

**Comment by ArmmGh** [comment]
```
➜  ~ RUST_BACKTRACE=full /Applications/Zed.app/Contents/MacOS/zed
thread 'main' panicked at crates/zed/src/main.rs:472:54:
could not create tmp path: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
   0:        0x104c3eaec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb478ebbfb46e27ce
   1:        0x1034344c8 - core::fmt::write::he4d5fa2daff1f531
   2:        0x104c3a05c - std::io::Write::write_fmt::hc5a47a68eba63d9f
   3:        0x104c3e8e4 - std::sys_common::backtrace::print::h79bd952cc5812e7a
   4:        0x104c40254 - std::panicking::default_hook::{{closure}}::h82301f6222887737
   5:        0x104c3ff50 - std::panicking::default_hook::h1e49abbb3f1d7dbf
   6:        0x104c40858 - std::panicking::rust_panic_with_hook::h1e70c5d905e30e9d
   7:        0x104c40634 - std::panicking::begin_panic_handler::{{closure}}::h399e32952efd26a4
   8:        0x104c3ef84 - std::sys_common::backtrace::__rust_end_short_backtrace::h2ab87f841a2323e7
   9:        0x104c403c8 - _rust_begin_unwind
  10:        0x10640f0f4 - core::panicking::panic_fmt::h33e40d2a93cab78f
  11:        0x10640f4a8 - core::result::unwrap_failed::h79c2cb9e4fc28c72
  12:        0x102c868ec - Zed[5b2c4ff9e7167a66]::main
  13:        0x102c2c1a4 - std[fcd23fca98dce159]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  14:        0x102c54a20 - std[fcd23fca98dce159]::rt::lang_start::<()>::{closure#0}
  15:        0x104c31cd8 - std::rt::lang_start_internal::hf4f3eb1e51305b96
  16:        0x102c9bed8 - _main
  ```

**Comment by manishsencha** [comment]
check if it opens with sudo

**Comment by osiewicz** [comment]
Ok, that says a lot: the line referenced in your panic message is: https://github.com/zed-industries/zed/blob/v0.127.x/crates/zed/src/main.rs#L472
So yeah, we can't create/open a directory in `~/.cache/zed`.

**Comment by ArmmGh** [comment]
> check if it opens with sudo

with sudo Zed opened

**Comment by manishsencha** [comment]
Directory permissions might be a problem. Check if your user has access.

**Comment by ArmmGh** [comment]
after 1 time opening with sudo, it started to open normally

**Comment by osiewicz** [comment]
Glad to help. :) Feel free to reopen if you run into this issue again.

**Comment by whois-root** [comment]
not able to open with sudo zed too. anyone can help?

**Comment by ArmmGh** [comment]
> ~/.cache/zed

try to give permission to your user to the folder `~/.cache/zed`

**Comment by whois-root** [comment]
[no such file ](chmod: /Users/sani/.cache/zed: No such file or directory)

am i missing something?

**Comment by OSokunbi** [comment]
> [no such file ](chmod: /Users/sani/.cache/zed: No such file or directory)
> 
> am i missing something?

run these commands in this order, it's what worked for me: 
```
rm ~/.cache
mkdir -p ~/.cache
mkdir -p ~/.cache/zed
chmod 700 ~/.cache/zed
```

**Comment by mrw31ss** [comment]
it stopped opening for me too... tried sudo and the message is:
"CoreGraphics PDF has logged an error. Set environment variable "CG_PDF_VERBOSE" to learn more."
<img width="658" alt="Screenshot 2024-06-25 at 02 22 12" src="https://github.com/zed-industries/zed/assets/28610489/8a1c46f6-14c1-4137-8ede-c931e653866c">
