### ISSUE TITLE
Mention theme auto-switching in default settings

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9627]
### Check for existing issues

- [X] Completed

### Describe the feature

Auto-switching themes according to system settings [landed to Zed in February](https://github.com/zed-industries/zed/pull/7404), but there is no mention of this in the `default settings`:

```
// The name of the Zed theme to use for the UI
  "theme": "One Dark",
```

Shouldn't it be something like:
```
// The name of the Zed theme to use for the UI
"theme": "One Dark",
// Use optional field 'mode' to indicate which theme should be used:
// "system" - Use the theme that corresponds to the system's appearance.
// "light" - Use the theme indicated by the light field.
// "dark" - Use the theme indicated by the dark field.
// "theme": {
//    "mode": "system",
//    "light": "One Light",
//    "dark": "One Dark"
//  },
```

**Comment by fbartho** [comment]
I came here to try to contribute exactly this example, but it appears the https://zed.dev/docs/themes page isn't managed in [this repository](https://github.com/zed-industries/zed) -- is there a different public repo where a contributor could provide a tweak or example for the documentation?

**Comment by JosephTLyons** [comment]
https://zed.dev/releases/preview/0.143.0
