### ISSUE TITLE
Add -r [reuse] cli feature

### ISSUE THREAD

**Issue by o3wiz** [zed-industries/zed#9632]
### Check for existing issues

- [X] Completed

### Describe the feature

Adding a `zed -r [path]` feature to reopen directories in the same window would be super handy. The `r` is for "reuse", kind of like what VSCode does. It's a real game-changer of a feature!

### If applicable, add mockups / screenshots to help present your vision of the feature

Here is how it works in vscode:

https://github.com/zed-industries/zed/assets/76743397/4d4a8304-d92d-4c2d-8306-6d0297b0c364

**Comment by Moshyfawn** [comment]
I believe this has been available as a new `-a` flag since [`0.127.3`](https://zed.dev/releases/stable/0.127.3). I'm going to close this issue, but feel free to reopen it if this is not what you're looking for.

> Added -n/--new and -a/--add to the zed CLI. When neither is specified, if you open a directory you get a new workspace, otherwise files are added to your existing workspace. With --new files are always opened in a new workspace, with --add directories are always added to an existing workspace.
