### ISSUE TITLE
Editor doesn't remember project panel state on restart

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9638]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

> After upgrading to 0.128.x, quitting Zed then restart or opening new projects / switching projects the left panel is always shown.

> I use `"ctrl-cmd-l": "workspace::ToggleLeftDock"` and press `ctrl-cmd-l` to close it. 
> 
> ----
> 
> Updated: I tried the menu bar (`View - Toggle Left Dock`), the result is same.
> 
> I don't have any project specific settings. And it happens on all projects.

_Originally posted by @failable in https://github.com/zed-industries/zed/discussions/9630#discussioncomment-8866915_

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS

**Comment by JosephTLyons** [comment]
Oh boy, this is the one that plagued you and I so much before - I think I still run into it still.

**Comment by Moshyfawn** [comment]
> Oh boy, this is the one that plagued you and I so much before - I think I still run into it still.

Yeah, it sounded familiar, but the thing is: I couldn't reproduce it this time 🤔

**Comment by failable** [comment]
I removed everything in .config/zed with a fresh installation, the issue is still there.

**Comment by meguriau** [comment]
Same issue. This issue is very annoying because I frequently switch projects and open/close Zed every day and have to close the project panel every time.
