### ISSUE TITLE
Improve CSV files view

### ISSUE THREAD

**Issue by Spoutnik97** [zed-industries/zed#9653]
### Check for existing issues

- [X] Completed

### Describe the feature

I used to read/modify csv files for my data tasks.

With VSCode there are a lot of extensions to handle that (I used [this to view](https://github.com/mechatroner/vscode_rainbow_csv) and [this to edit](https://github.com/janisdd/vscode-edit-csv) )

I could help to develop this extension, but what is the best technical strategy ? 

Currently I see a lot of grey lines. It is unusable because I can't see columns for instance

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="752" alt="image" src="https://github.com/zed-industries/zed/assets/30442116/219c2316-cf18-43eb-8cf2-7e06f5a1f5ca">

<img width="815" alt="image" src="https://github.com/zed-industries/zed/assets/30442116/e475d6e0-5739-43c3-90df-bd85c5fa5540">

**Comment by JosephTLyons** [comment]
Hey @Spoutnik97, just to mention it, we have an CSV extension in the store now that provides some highlighting, which might help a bit here. We don't have a dedicated table-view of the CSV file though.

<img width="1174" alt="SCR-20240411-msqk" src="https://github.com/zed-industries/zed/assets/19867440/01ee1e7c-26e6-4bea-9c3b-5526941cf41d">

**Comment by JosephTLyons** [comment]
I guess I should've just moved this issue over to the extensions repo, but I mindlessly recreated it:

- https://github.com/zed-industries/extensions/issues/475
