### ISSUE TITLE
Ability to pull pane tab into separate window

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#9657]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like ZED to allow me to pull any of the Pane Tabs into separate stand-alone window.

### If applicable, add mockups / screenshots to help present your vision of the feature

Move pane tab into separate window

**Comment by Moshyfawn** [comment]
I think you suggested this in #6078 and it was closed in favour of #5229.

**Comment by krstp** [comment]
Ah indeed! I could not find it. Thanks. Closing then.
