### ISSUE TITLE
Resize causes characters to disappear

### ISSUE THREAD

**Issue by ajstarks** [zed-industries/zed#9666]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When resizing random characters will disappear.  Undoing the resize will cause the characters to re-appear

See screencast

https://github.com/zed-industries/zed/assets/169692/1f7c3d59-41cb-4eab-8a99-091da1572223

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 11.7.9
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

before and after screen shots
<img width="1030" alt="s0" src="https://github.com/zed-industries/zed/assets/169692/dc2ecdae-a6ee-4ce3-b37d-039558c3a617">

<img width="1023" alt="s1" src="https://github.com/zed-industries/zed/assets/169692/563c6538-76d9-461e-a3ab-473dae34bf69">

**Comment by Moshyfawn** [comment]
Could it be that you're seeing the same problem as in #5062, as resizing the window seems to act like scrolling through the file?

**Comment by ajstarks** [comment]
@Moshyfawn perhaps, yes.  It also could be related to NVIDIA GPU that others have reported. (my machine has a NVIDIA GeForce GT 750M).

**Comment by JosephTLyons** [comment]
Should we close this one out in favor of #5062?

**Comment by ajstarks** [comment]
It's not clear that #5062 is the same behavior, but looking at other rendering bugs a common theme is older Macs with NVIDIA GPUs.  I'd say keep it separate for now.

**Comment by ajstarks** [comment]
The problem persists with the latest version (0.132.5), and in fact may be worse,  This is what I get on initial load:
<img width="1048" alt="screenshot 2024-04-30 at 12 45 22 PM" src="https://github.com/zed-industries/zed/assets/169692/32b62980-16e8-44c1-96c7-125c3e4035f3">
