### ISSUE TITLE
failed to format via language server error!

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#9669]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when i save the formatter is giving me an error that say "Failed to format via language server" 

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1030" alt="Screenshot 2024-03-21 alle 22 47 36" src="https://github.com/zed-industries/zed/assets/53220110/063a0ee6-315f-412d-8b95-98261a4ecedd">

**Comment by Moshyfawn** [comment]
Could you check the latest preview version `0.128.1` to see if it's still a problem?

**Comment by Iovans** [comment]
I Will try this evening,i'll let you know

**Comment by mrnugget** [comment]
Can you also post your Zed `settings.json`?

**Comment by Iovans** [comment]
i cant download in 0.128 because it gave me an error that says its not supported i dont know why, i'll give you the settings.json

**Comment by Moshyfawn** [comment]
> i cant download in 0.128 because it gave me an error that says its not supported i dont know why

Interesting! Seems to be related to Zed shipping the non-universal binary 🤔

**Comment by Iovans** [comment]
for sure! but why they did in that way?

**Comment by osiewicz** [comment]
Could you try with: https://zed.dev/api/releases/preview/0.128.1/Zed-x86_64.dmg

**Comment by Iovans** [comment]
Ok cool,i tried the 0.128 and the error Is still there

**Comment by mrnugget** [comment]
Can you give us some steps to reproduce? Example file, cargo.toml, etc.?

In the logs it sounds like `rustfmt` is involved, but there's nothing in Zed that invokes rustfmt, we only talk to rust-analyzer. So I'm wondering where that comes from and why it doesn't work.

**Comment by Iovans** [comment]
I updated it and the error it disaeppear!
