### ISSUE TITLE
Zed don't change the theme.

### ISSUE THREAD

**Issue by yansena** [zed-industries/zed#9683]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to change the Zed theme his just don't change.

cmd + K cmd + t

https://github.com/zed-industries/zed/assets/61507998/194a7b97-c7b0-4f58-b83e-b01f47b9ddb6

### Environment

 Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Model Number:	MGN63LL/A
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	10151.41.12
  OS Loader Version:	10151.41.12

**Comment by maxdeviant** [comment]
@yansena What version of Zed are you seeing this in?

**Comment by samritchie** [comment]
I see this issue also - regardless of whether I apply the theme via settings or the "Select Theme" popup, it briefly flashes the theme and then reverts back to the default. Zed 0.136.2

**Comment by notpeter** [comment]
I was able to reproduce something similar when my settings.json is in an invalid state.  The theme selector pop-up would let you preview the theme but when you selected it would revert.

I think we do a better job detecting and handling invalid settings now and so I don't think this is less of an issue now.  I'm going to close this issue, but if you're still seeing this issue, please reply and I'm happy to re-open and help troubleshoot. Thanks!
