### ISSUE TITLE
Add support for typos-lsp

### ISSUE THREAD

**Issue by hnbnh** [zed-industries/zed#9686]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if Zed has support for https://github.com/tekumara/typos-lsp

**Comment by Moshyfawn** [comment]
I think the general idea of a spell checker in Zed has already been raised in #5305, where `typos` was also mentioned as a solution. Let's close this issue in favour of the ongoing discussion to keep the conversation in one place. Be sure to +👍 and add any information to the other thread.

Duplicate of
- #5305

**Comment by notpeter** [comment]
FYI there is now an "typos" extension that integrates typos-lsp:

https://github.com/BaptisteRoseau/zed-typos
