### ISSUE TITLE
Discord Presence support

### ISSUE THREAD

**Issue by Alexander1022** [zed-industries/zed#9690]
### Check for existing issues

- [X] Completed

### Describe the feature

- Shows what you are editing in Zed
- Easily manually reconnect to Discord
- Enable/Disable Rich Presence for workspaces
- Support for all the languages available in Zed

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="704" alt="Discord Rich Presence Showcase" src="https://github.com/zed-industries/zed/assets/36764735/e7acec7a-47b4-4ff3-93b4-65b5e0d93ca8">

**Comment by Moshyfawn** [comment]
This has already been covered in another issue. Let's close this issue in favour of the existing one to keep the discussion in one place. Be sure to +👍 and add any missing information.

Duplicate of
- #4497
