### ISSUE TITLE
Unable to select text with double-clicking

### ISSUE THREAD

**Issue by hackedd** [zed-industries/zed#9707]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't select text in Zed buffers or the terminal pane by double-clicking words or triple-clicking a line.

### Environment

Zed: v1.0.0 (Zed Dev)
OS: Linux 1.0.0
Memory: 62 GiB
Architecture: x86_64

**Comment by apricotbucket28** [comment]
Are you using Wayland or X11? Double click should be supported on Wayland (https://github.com/zed-industries/zed/pull/9608). But X11 is still not supported.

**Comment by hackedd** [comment]
X11. Thanks for confirming, not sure how I didn't find that PR earlier.
