### ISSUE TITLE
Un-even title bar spacing

### ISSUE THREAD

**Issue by pouyakary** [zed-industries/zed#9709]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open the Zed, and put the `ui_font_size` to 16.

This will be how zed looks:

<img width="790" alt="Screenshot 1403-01-03 at 7 56 56 PM" src="https://github.com/zed-industries/zed/assets/2157285/09cc59dd-43b7-457f-9886-1c73d972fb28">

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Open the Zed, and put the `ui_font_size` to 16.

This will be how zed looks:

<img width="431" alt="Screenshot 1403-01-03 at 7 53 40 PM" src="https://github.com/zed-industries/zed/assets/2157285/431e9572-0735-49d4-96e8-e7928a875548">

Now if you look, you'll see the bottom spacing is behind by 2 pixels:

![SCR-14030103-rnc](https://github.com/zed-industries/zed/assets/2157285/7c48866e-74ad-40a9-a415-3c1a6d1a2d5a)

**Comment by Aaron-212** [comment]
Change min height of title bar from 32px to 34px fixes it.
<img width="258" alt="image" src="https://github.com/zed-industries/zed/assets/38318044/16bda69e-9f3a-4c80-b2b1-44698d3bc1ee">

`crates/ui/src/components/title_bar/title_bar.rs`
```rust
impl TitleBar {
    #[cfg(not(target_os = "windows"))]
    pub fn height(cx: &mut WindowContext) -> Pixels {
        (1.75 * cx.rem_size()).max(px(34.)) // 32 -> 34
    }

...
```

**Comment by JosephTLyons** [comment]
We just shipped [v0.129.0-pre](https://zed.dev/releases/preview/0.129.0), which has a fix for this.

**Comment by pouyakary** [comment]
@JosephTLyons @Aaron-212  thank you both a lot!

**Comment by Aaron-212** [comment]
<img width="224" alt="image" src="https://github.com/user-attachments/assets/d5806f79-6236-49cf-84b5-c6759532947a">

The issue seems to come back somehow 🥲
