### ISSUE TITLE
Diagnostics sometimes don't show a useful amount of context

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#9714]
The diagnostics view (and all mutlibuffers) only shows a hard coded number of lines. This often isn't enough context to do useful refactoring, and worse there's no way to change it from what it gives you. 

![image](https://github.com/zed-industries/zed/assets/2280405/3ccb6a1f-6041-4e33-a6a1-9c6f70a9565c)

**Comment by mikayla-maki** [comment]
Solutions: 

1. Add an icon to show how to jump to surrounding file
2. Make default multibuffer lines configurable, and add buttons for expanding them from this default
3. Integrate the `select larger syntax node` with multi buffers to expand the lines of an excerpt

**Comment by JosephTLyons** [comment]
Can we move the new info out and into

- https://github.com/zed-industries/zed/issues/5377

and then close this issue out @mikayla-maki?

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/zed/pull/10300
