### ISSUE TITLE
Open recent project: 'Enter reuses this window...' label does not fit in the pane

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9719]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`Enter reuses this window...` label does not fit in the `Open recent project` panel:

<img width="416" alt="Снимок экрана 2024-03-22 в 22 07 12" src="https://github.com/zed-industries/zed/assets/230824/3c92c32c-6c5f-47bc-a56f-c0ec4d96211a">

### Environment

Zed Preview 0.128.1
MacOS 12.7.4

**Comment by JosephTLyons** [comment]
I think @iamnbutler will have ideas on how to clean this up - I think adding text into the input was likely a temporary solution here.

**Comment by Moshyfawn** [comment]
The "Recent Projects" popover is now a floating modal, which now fits the input placeholder just nicely. I'll close this one as complete.

<img width="1398" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/7485a43f-9b15-426a-a8f9-66423a9f386e">
