### ISSUE TITLE
Right clicking the left project bar doesn't show a menu

### ISSUE THREAD

**Issue by lino-levan** [zed-industries/zed#9723]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Normally, when you right click the empty space in the project bar on the left, a popup menu appears where you are able to create new files and such. This was originally broken on the first move to GPUI2, was fixed, and now seems to be broken again.

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

AND

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Thanks for the report @lino-levan - Is this a regression @SomeoneToIgnore? Tagging you since you are on the PR here:

- https://github.com/zed-industries/zed/pull/3954

**Comment by SomeoneToIgnore** [comment]
Thank you, fixed it in https://github.com/zed-industries/zed/pull/9806
