### ISSUE TITLE
The extension theme is still applied when the theme selection modal is dismissed

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#9724]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open the Extensions tab
2. Click Install on any Theme Extension
3. See the theme selection modal
4. Exit the modal by pressing Escape
5. Observe that the theme is still applied

The expected behaviour would be for the theme to be reset to the one applied before the new one was installed.

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/00726f3c-79b7-41ca-87e8-4e406673c9d2

**Comment by Moshyfawn** [comment]
Related feature request: #9228

**Comment by Moshyfawn** [comment]
This only happens if you install -> apply theme -> uninstall -> install -> dismiss, so I guess [`original_theme`](https://github.com/zed-industries/zed/blob/6ebe599c980508aa8c7e87fad3e59e5a43892368/crates/theme_selector/src/theme_selector.rs#L84C5-L84C19) isn't reset when you uninstall the extension.

**Comment by JosephTLyons** [comment]
I'm not able to reproduce this issue, so I'm going to close this one out!
