### ISSUE TITLE
Keyboard shortcuts to swap lines broke in 0.127

### ISSUE THREAD

**Issue by sebastiansandqvist** [zed-industries/zed#9727]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Prior to 0.127 I was able to use <kbd>ctrl</kbd><kbd>cmd</kbd><kbd>up</kbd> and <kbd>ctrl</kbd><kbd>cmd</kbd><kbd>down</kbd> to swap the current/highlighted line(s) with the line above or below the cursor. After updating I lost that keybinding.

I'm using the default Sublime keymap with Vim mode enabled.

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
This was an intetional breaking change:

- https://zed.dev/releases/stable/0.127.3

Our default keymap has always been based off of VS Code's keymap, so these changes brought us closer. We still have some minor differences here and there, so there will likely be more breaking changes, before 1.0.

You can rebind the old keybinding in your `keymap.json`:

```json
{
  "context": "Editor",
  "bindings": {
    "ctrl-cmd-up": "editor::MoveLineUp",
    "ctrl-cmd-down": "editor::MoveLineDown"
  }
},
```

**Comment by sebastiansandqvist** [comment]
Thank you! Any idea why the `MoveLineDown` command with this binding triggers the audible bell? My mac makes a little "pop" sound whenever I run <kbd>ctrl</kbd><kbd>cmd</kbd><kbd>down</kbd>, but there's no sound for the `MoveLineUp` command.

**Comment by JosephTLyons** [comment]
> Thank you! Any idea why the `MoveLineDown` command with this binding triggers the audible bell? My mac makes a little "pop" sound whenever I run ctrlcmddown, but there's no sound for the `MoveLineUp` command.

That issue is being tracked here:

https://github.com/zed-industries/zed/issues/5083

We haven't come up with a solution for it, it was a bug that plagued Atom too. We'll likely have to put in some sort of hack to get around it, if possible. I wonder how other editors deal with it.
