### ISSUE TITLE
project panel  Expand folder display error

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#9729]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/19868292/af1abf96-3110-4015-9f62-57952b014172

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by d1y** [comment]
Maybe it's the same problem 😵‍💫

> Zed: v0.128.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

![fixx](https://github.com/zed-industries/zed/assets/45585937/85076b3d-f3f6-4917-98db-30cbd0c54ead)

**Comment by alwayrun** [comment]
The same issue exists. After some testing, it seems to be related to directory naming. When the directory name is in the format of a.b.c, the problem can be reproduced as described above.

```
Zed: v0.127.4
OS: macOS 13.6.3
Memory: 16 GiB
Architecture: x86_64
```
