### ISSUE TITLE
Big memory leak issue since version 0.126.2

### ISSUE THREAD

**Issue by waelrabah11** [zed-industries/zed#9744]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was running 2 instances of Zed working between 2 repos with small codebases. Each repo has ~2k lines of code. This culminated in ZED crashing by using up most of the Ram and swap and 4 CPU cores being used by the editor.
I still don't know how to reproduce this but I will be updating the issue.

### Environment

Chip: Apple M1 Pro
Memory: 16 GB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="539" alt="image" src="https://github.com/zed-industries/zed/assets/142890800/96865467-8bf9-4142-8564-a615d34d63ec">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14731996/Zed.log)

**Comment by mikayla-maki** [comment]
I'm going to close this one as can't repro, thanks for the issue :)
