### ISSUE TITLE
local tasks are lost after restart when `.zed/` in `.gitignore`

### ISSUE THREAD

**Issue by ZombieHarvester** [zed-industries/zed#9747]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when `.zed/` is in `.gitignore`:

1. Local tasks are not accessible after restart via hot keys even though `.zed/tasks.json` still has tasks info.
2. `.zed/tasks.json` becomes empty after running `zed: open local tasks` after restart.

#### Steps to reproduce:

1. create local tasks
4. add .zed/ to .gitignore
5. check that `tasks.json` is not empty

```
> cat .zed/tasks.json
[
  {
    "label": "All tests",
    "command": "rspec",
    ...
```
6. `shit-option-t` opens list of local tasks
7. close tasks.json tab
8. reload zed
9. `shit-option-t` now opens empty list
10. but `cat .zed/tasks.json` still shows tasks
11. run `zed: open local tasks`
12. see tab with default task blueprint

```
// Static tasks configuration.
//
// Example:
[
  {
    "label": "Example task",
    ...
```

13. check that `tasks.json` is now empty

```
> cat .zed/tasks.json
>
```

If you keep `tasks.json` file open in a tab or when `.zed/` is removed from `.gitignore`, then `tasks.json` doesn't get erased after restart.

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 12.7.4
Memory: 16 GiB
Architecture: x86_64

**Comment by osiewicz** [comment]
This most likely applies to other zed files like settings and keymaps too.
