### ISSUE TITLE
suggestions in zed settings 

### ISSUE THREAD

**Issue by LeOndaz** [zed-industries/zed#9750]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed settings are in a json files, we can incorporate json schemas to have settings validated & for auto complete as well

**Comment by Moshyfawn** [comment]
JSON validation is already a thing, as noted in #5358. Do you have something else in mind?

**Comment by LeOndaz** [comment]
> JSON validation is already a thing, as noted in #5358. Do you have something else in mind?


This only validates the json, it doesn't suggest what the available options are, for example

I expect the auto-complete to pop up when I start typing in the key-map setting, to show the available options

**Comment by Moshyfawn** [comment]
Autocomplete is there as well.

<img width="1554" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/76c80857-36c4-4255-9b77-91923867e8fa">

**Comment by LeOndaz** [comment]
> Autocomplete is there as well.
> 
> 
> 
> <img width="1554" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/76c80857-36c4-4255-9b77-91923867e8fa">
> 
> 
> 
> <img width="1554" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/0d25338c-5273-49e9-a3b6-c8c509b3301b">
> 
> 
> 
> 


Thanks for pointing out, can't seem to show on my end though, does this exist in the latest updatable version through the in/app update?

Anyway, since they addressed it, I will be better with this issue closed

**Comment by Moshyfawn** [comment]
> Thanks for pointing out, can't seem to show on my end though, does this exist in the latest updatable version through the in/app update?

What happens if you put the cursor where you want to add a setting and call `editor: show completions` from the command palette?

**Comment by LeOndaz** [comment]
> > Thanks for pointing out, can't seem to show on my end though, does this exist in the latest updatable version through the in/app update?
> 
> 
> 
> What happens if you put the cursor where you want to add a setting and call `editor: show completions` from the command palette?

Will tell you in the morning as it's late

**Comment by Moshyfawn** [comment]
Sounds good! I'm going to close this issue as it's already been addressed. Feel free to reply here whenever you've got time.

Have a good night!

**Comment by phromo** [comment]
A schema or a way to inform agents of viable zed settings would be really useful. The built-in zed agent struggles to configure zed.
