### ISSUE TITLE
Symbols are duplicated in symbol search

### ISSUE THREAD

**Issue by danielzsh** [zed-industries/zed#9752]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

All symbols are displayed twice in symbol search:
<img width="487" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/68be4b99-9a48-4420-bab3-7c4376901c26">

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.1.1
Memory: 8 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
I think this is expected for the structs in your screenshots: they're 2 structs with the same name, defined by the `actions' macro _(excuse my terminology, I'm still new to Rust lol)_. Other symbols aren't duplicated either.

**Comment by danielzsh** [comment]
<img width="488" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/4ddb6e0e-1940-45d8-8866-164fcd04d0ac">
Hm, `ElementContext` appears to be doubled too, and it's only defined once?

**Comment by Moshyfawn** [comment]
Interesting, I don't see that. I'll let other devs have a look at it.

<img width="1554" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/1ddaebbd-32a7-4b11-88a7-f9124f376216">

**Comment by danielzsh** [comment]
Huh, I quit and reopen Zed and it's back to normal...

**Comment by danielzsh** [comment]
Ok, the issue resurfaced, so there's certainly something that causes the pane to bug out, but I'm not sure exactly what yet.
