### ISSUE TITLE
Single-line comments syntax being highlighted on PHP

### ISSUE THREAD

**Issue by d8vjork** [zed-industries/zed#9756]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Related to #4381

The bug occurs when a code like this is being typed:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        // @var ServiceProvider $serv
        # @var ServiceProvider $serv
        /** @var ServiceProvider $serv */
    }

    public function boot()
    {
    }
}
```

Although Github's Markdown doesn't fully support this, VSCode does (see screenshot below this section)

![image](https://github.com/zed-industries/zed/assets/2331052/1603b40a-04cd-465d-83b0-b34003eda6c4)

**In PHP only multi-line comments written as single line or multiple lines can and should support syntax highlighting so `#` or `//` should not have any syntax highlight**

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.2.1
Memory: 48 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/2331052/3ea01ce4-b2d0-404c-8bc9-7237b497322e)

This is how it should work (screenshot taken from VSCode using a PHP extension)

**Comment by RemcoSmitsDev** [comment]
I think this issue can be closed as the pull request for `php-doc` syntax highlighting is merged. #11695
