### ISSUE TITLE
Windows: zed.exe can't find `TaskDialogIndirect` symbol at startup

### ISSUE THREAD

**Issue by ognevny** [zed-industries/zed#9757]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the executable can't find `TaskDialogIndirect` symbol from `comctl32.dll`. ntldd shows this
```
comctl32.dll => C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\comctl32.dll (0x00000280890a0000)
```
while the .dll file is also contained in `C:\Windows\System32` directory

if run with `cargo run --release`, ``error: process didn't exit successfully: `target\release\Zed.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)`` is shown

### Environment

Windows build 22631
rustc -Vv:
```
rustc 1.76.0 (07dca489a 2024-02-04) (Rev1, Built by MSYS2 project)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

the error message (translation: `the entry point to the TaskDialogIndirect procedure is not found in the DLL C:\msys64\clang64\bin\zed.exe library`)
![image](https://github.com/zed-industries/zed/assets/119937608/dd99291d-e201-4ac5-b497-78f99e43e6fa)

**Comment by ognevny** [comment]
looks like this comes from winapi bug. the minimal code to reproduce

<details>

src/main.rs
```rust
extern crate win_task_dialog;

use std::thread;
use std::time::Duration;
use win_task_dialog::*;

fn callback(link: String) {
    println!("{}", link);
}

fn main() {
    let mut conf = TaskDialogConfig {
        flags: TDF_USE_COMMAND_LINKS | TDF_ENABLE_HYPERLINKS,
        common_buttons: TDCBF_OK_BUTTON | TDCBF_CANCEL_BUTTON,
        window_title: "Title 标题".to_string(),
        main_instruction: "Привет".to_string(),
        content: "こんにちは".to_string(),
        verification_text: "VerificationText".to_string(),
        footer: "footer\n<a href=\"http://example.com\">example.com</a>".to_string(),
        buttons: vec![
            TaskDialogButton {
                id: 10,
                text: "One".to_string(),
            },
            TaskDialogButton {
                id: 11,
                text: "贰".to_string(),
            },
        ],
        default_button: 11,
        radio_buttons: vec![
            TaskDialogButton {
                id: 10,
                text: "Option 1".to_string(),
            },
            TaskDialogButton {
                id: 11,
                text: "Option 2".to_string(),
            },
        ],
        main_icon: TD_SHIELD_ICON,
        footer_icon: TD_INFORMATION_ICON,
        hyperlinkclicked_callback: callback,
        ..TaskDialogConfig::default()
    };

    let result = show_task_dialog(&mut conf).unwrap();
    println!(
        "{} {} {}",
        result.button_id, result.radio_button_id, result.checked,
    );

    show_dynamic_text_dialog();
    show_process_bar_marquee();
    show_process_bar();

    show_msg_dialog("Title", "Hi", "Info", TD_INFORMATION_ICON);
    show_msg_dialog("Title", "!!!", "Error", TD_ERROR_ICON);
}

// Show dynamic text dialog
fn show_dynamic_text_dialog() {
    let mut conf = TaskDialogConfig {
        window_title: "Dynamic Text".to_string(),
        main_instruction: "Main".to_string(),
        content: "Content".to_string(),
        footer: "Footer".to_string(),
        expanded_information: "Info".to_string(),
        ..Default::default()
    };

    let conf_ptr: *mut TaskDialogConfig = &mut conf;
    let conf_long_ptr = conf_ptr as isize;
    thread::spawn(move || unsafe {
        let conf = std::mem::transmute::<isize, *mut TaskDialogConfig>(conf_long_ptr);
        for i in 1..4 {
            thread::sleep(Duration::from_secs(1));
            (*conf).set_main_instruction(format!("Main {}", i).as_str());
            (*conf).set_content(format!("Content {}", i).as_str());
            (*conf).set_footer(format!("Footer {}", i).as_str());
            (*conf).set_expanded_information(format!("Info {}", i).as_str());
        }
        (*conf).set_main_instruction("Main !!!");
        (*conf).set_content("Content !!!");
        (*conf).set_footer("Footer !!!");
        (*conf).set_expanded_information("Info !!!");
    });

    show_task_dialog(&mut conf).unwrap();
}

// Process Bar Marquee
fn show_process_bar_marquee() {
    let mut conf = TaskDialogConfig {
        window_title: "Process Bar".to_string(),
        main_instruction: "Process Bar Marquee 1".to_string(),
        ..Default::default()
    };
    conf.enable_process_bar(true);

    let conf_ptr: *mut TaskDialogConfig = &mut conf;
    let conf_long_ptr = conf_ptr as isize;
    thread::spawn(move || unsafe {
        thread::sleep(Duration::from_secs(1));
        let conf = std::mem::transmute::<isize, *mut TaskDialogConfig>(conf_long_ptr);
        (*conf).set_process_bar_marquee(true, 100);
        thread::sleep(Duration::from_secs(5));
        (*conf).set_main_instruction("Process Bar Marquee 2");
        (*conf).set_process_bar_marquee(true, 1);
        thread::sleep(Duration::from_secs(3));
        (*conf).set_main_instruction("Process Bar Marquee Stop");
        (*conf).set_process_bar_marquee(false, 1);
    });

    show_task_dialog(&mut conf).unwrap();
}

// Process Bar (Not Marquee)
fn show_process_bar() {
    let mut conf = TaskDialogConfig {
        window_title: "Process Bar".to_string(),
        main_instruction: "Process Bar (Not Marquee)".to_string(),
        content: "".to_string(),
        ..Default::default()
    };
    conf.enable_process_bar(false);

    let conf_ptr: *mut TaskDialogConfig = &mut conf;
    let conf_long_ptr = conf_ptr as isize;
    thread::spawn(move || unsafe {
        let conf = std::mem::transmute::<isize, *mut TaskDialogConfig>(conf_long_ptr);
        for i in 0..101 {
            if (*conf).is_destroyed {
                return;
            }
            thread::sleep(Duration::from_millis(20));
            (*conf).set_process_bar(i);
        }
    });

    show_task_dialog(&mut conf).unwrap();
}
```

Cargo.toml:
```toml
[dependencies]
win-task-dialog = { git = "https://github.com/robincodex/win-task-dialog-for-rust", rev = "e1d01ceada0a7b74fc5267ef32e6d7aa460abac6" }

[build-dependencies]
embed-resource = "2.1"
```

<details/>

**Comment by Kreijstal** [comment]
Maybe implementing this in windows-rs will fix it?

**Comment by ognevny** [comment]
> looks like this comes from winapi bug. the minimal code to reproduce
> 
> **src/main.rs:**
> 
> ```rust
> extern crate win_task_dialog;
> 
> use std::thread;
> use std::time::Duration;
> use win_task_dialog::*;
> 
> fn callback(link: String) {
>     println!("{}", link);
> }
> 
> fn main() {
>     let mut conf = TaskDialogConfig {
>         flags: TDF_USE_COMMAND_LINKS | TDF_ENABLE_HYPERLINKS,
>         common_buttons: TDCBF_OK_BUTTON | TDCBF_CANCEL_BUTTON,
>         window_title: "Title 标题".to_string(),
>         main_instruction: "Привет".to_string(),
>         content: "こんにちは".to_string(),
>         verification_text: "VerificationText".to_string(),
>         footer: "footer\n<a href=\"http://example.com\">example.com</a>".to_string(),
>         buttons: vec![
>             TaskDialogButton {
>                 id: 10,
>                 text: "One".to_string(),
>             },
>             TaskDialogButton {
>                 id: 11,
>                 text: "贰".to_string(),
>             },
>         ],
>         default_button: 11,
>         radio_buttons: vec![
>             TaskDialogButton {
>                 id: 10,
>                 text: "Option 1".to_string(),
>             },
>             TaskDialogButton {
>                 id: 11,
>                 text: "Option 2".to_string(),
>             },
>         ],
>         main_icon: TD_SHIELD_ICON,
>         footer_icon: TD_INFORMATION_ICON,
>         hyperlinkclicked_callback: callback,
>         ..TaskDialogConfig::default()
>     };
> 
>     let result = show_task_dialog(&mut conf).unwrap();
>     println!(
>         "{} {} {}",
>         result.button_id, result.radio_button_id, result.checked,
>     );
> 
>     show_dynamic_text_dialog();
>     show_process_bar_marquee();
>     show_process_bar();
> 
>     show_msg_dialog("Title", "Hi", "Info", TD_INFORMATION_ICON);
>     show_msg_dialog("Title", "!!!", "Error", TD_ERROR_ICON);
> }
> 
> // Show dynamic text dialog
> fn show_dynamic_text_dialog() {
>     let mut conf = TaskDialogConfig {
>         window_title: "Dynamic Text".to_string(),
>         main_instruction: "Main".to_string(),
>         content: "Content".to_string(),
>         footer: "Footer".to_string(),
>         expanded_information: "Info".to_string(),
>         ..Default::default()
>     };
> 
>     let conf_ptr: *mut TaskDialogConfig = &mut conf;
>     let conf_long_ptr = conf_ptr as isize;
>     thread::spawn(move || unsafe {
>         let conf = std::mem::transmute::<isize, *mut TaskDialogConfig>(conf_long_ptr);
>         for i in 1..4 {
>             thread::sleep(Duration::from_secs(1));
>             (*conf).set_main_instruction(format!("Main {}", i).as_str());
>             (*conf).set_content(format!("Content {}", i).as_str());
>             (*conf).set_footer(format!("Footer {}", i).as_str());
>             (*conf).set_expanded_information(format!("Info {}", i).as_str());
>         }
>         (*conf).set_main_instruction("Main !!!");
>         (*conf).set_content("Content !!!");
>         (*conf).set_footer("Footer !!!");
>         (*conf).set_expanded_information("Info !!!");
>     });
> 
>     show_task_dialog(&mut conf).unwrap();
> }
> 
> // Process Bar Marquee
> fn show_process_bar_marquee() {
>     let mut conf = TaskDialogConfig {
>         window_title: "Process Bar".to_string(),
>         main_instruction: "Process Bar Marquee 1".to_string(),
>         ..Default::default()
>     };
>     conf.enable_process_bar(true);
> 
>     let conf_ptr: *mut TaskDialogConfig = &mut conf;
>     let conf_long_ptr = conf_ptr as isize;
>     thread::spawn(move || unsafe {
>         thread::sleep(Duration::from_secs(1));
>         let conf = std::mem::transmute::<isize, *mut TaskDialogConfig>(conf_long_ptr);
>         (*conf).set_process_bar_marquee(true, 100);
>         thread::sleep(Duration::from_secs(5));
>         (*conf).set_main_instruction("Process Bar Marquee 2");
>         (*conf).set_process_bar_marquee(true, 1);
>         thread::sleep(Duration::from_secs(3));
>         (*conf).set_main_instruction("Process Bar Marquee Stop");
>         (*conf).set_process_bar_marquee(false, 1);
>     });
> 
>     show_task_dialog(&mut conf).unwrap();
> }
> 
> // Process Bar (Not Marquee)
> fn show_process_bar() {
>     let mut conf = TaskDialogConfig {
>         window_title: "Process Bar".to_string(),
>         main_instruction: "Process Bar (Not Marquee)".to_string(),
>         content: "".to_string(),
>         ..Default::default()
>     };
>     conf.enable_process_bar(false);
> 
>     let conf_ptr: *mut TaskDialogConfig = &mut conf;
>     let conf_long_ptr = conf_ptr as isize;
>     thread::spawn(move || unsafe {
>         let conf = std::mem::transmute::<isize, *mut TaskDialogConfig>(conf_long_ptr);
>         for i in 0..101 {
>             if (*conf).is_destroyed {
>                 return;
>             }
>             thread::sleep(Duration::from_millis(20));
>             (*conf).set_process_bar(i);
>         }
>     });
> 
>     show_task_dialog(&mut conf).unwrap();
> }
> ```
> 
> **Cargo.toml:**
> 
> ```toml
> [dependencies]
> win-task-dialog = { git = "https://github.com/robincodex/win-task-dialog-for-rust", rev = "e1d01ceada0a7b74fc5267ef32e6d7aa460abac6" }
> 
> [build-dependencies]
> embed-resource = "2.1"
> ```
> 
> the error: `` error: process didn't exit successfully: `target\debug\mytest.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND) ``

the reason of the error that there is a missing manifest for exe

**Comment by sky96111** [comment]
This problem seems still exists on latest stable windows build zed, but sometimes zed can start properly.
```
Zed 0.212.3 
7a7a92d6b324956a86a2014b28c88bb8a8a035bc
```

[Zed.log](https://github.com/user-attachments/files/23514209/Zed.log)

<img width="2244" height="1306" alt="Image" src="https://github.com/user-attachments/assets/31b4bcd5-35d2-4197-aed0-b639c8a9ce3f" />
