### ISSUE TITLE
Failed to open file: invalid utf-8 sequence of 1 bytes from index 51. Please try again.

### ISSUE THREAD

**Issue by volfcan** [zed-industries/zed#9771]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

I am trying to open an mp4 file on the project panel and get the following error:

Failed to open file:

> invalid utf-8 sequence of 1 bytes from index 51. Please try again.

Is this an expected issue or is it just happening to me?

### Environment

 

Software:

    System Software Overview:

      System Version: macOS 13.1 (22C65)
      Kernel Version: Darwin 22.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Volkan’s MacBook Pro
      User Name: Volkan Bozkurt (volfcan)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 hour, 33 minutes

<img width="796" alt="Screenshot 2024-03-25 at 13 16 58" src="https://github.com/zed-industries/zed/assets/68243739/191ae9bf-700c-4b15-b278-c84ac10c1242">

**Comment by osiewicz** [comment]
It is expected, we do not support working with binary files at the moment. MP4 files are not text files that we can display. See also: #5250
