### ISSUE TITLE
Searching in terminal issue

### ISSUE THREAD

**Issue by pinefin** [zed-industries/zed#9779]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the arrow buttons IN the terminal to search while the code editor is active it will interact with the code editor arrows, whether the search utilities are showing on the code editor or not.

Apologies for the cropped video, this is to keep my name or any other info out of this

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.1.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/45133527/0731d6cb-1f6a-4b1c-aca0-2f0c5e1a65e5

**Comment by notpeter** [comment]
It appears that sometime in the last six months that this was fixed as I can no longer reproduce.  If you are still experiencing this with a recent Zed release @pinefin please feel free to comment and I'm happy to reopen.

Thanks for reporting!
