### ISSUE TITLE
Problems with undo-history and selections (vim mode)

### ISSUE THREAD

**Issue by elkowar** [zed-industries/zed#9781]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using vim mode:
- open a file
- do some edits
- select a few lines, hit `>` to indent them
- do a few more edits
- undo repeatedly
- --> Once you reach the indent-action, instead of simply undoing the indent, zed will loop between selecting and de-selecting the things you indented

(On a sidenote, the vim implementation should really keep the selection active when doing `>` and other selection-operations, but that's a different bug, I'd think).

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.1.1
Memory: 32 GiB
Architecture: x86_64

**Comment by ConradIrwin** [comment]
@elkowar I believe this was fixed by zed 0.128.x
