### ISSUE TITLE
UI "vanishing" on search

### ISSUE THREAD

**Issue by leo-mangold** [zed-industries/zed#9792]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This never happened to me before but today suddenly when searching for a string in regex mode the entire text vanished from the ui:
<img width="3008" alt="Screenshot 2024-03-25 at 21 47 46" src="https://github.com/zed-industries/zed/assets/42837960/d25a564f-d972-41e0-b7bc-3666211ecff6">

This weirdly enough only happens after a pretty big window size (good chunk bigger than 14" mac book screen)

This is what it looks like in test search mode:
<img width="3008" alt="Screenshot 2024-03-25 at 21 50 26" src="https://github.com/zed-industries/zed/assets/42837960/4e08db35-ad46-4ecb-be7c-9eb5f044a102">

And this on a smaller screen size with regex mode (text mode also works fine):
<img width="3008" alt="Screenshot 2024-03-25 at 21 49 37" src="https://github.com/zed-industries/zed/assets/42837960/ca1131a9-b19d-47b9-aa4f-4f8194f86db2">

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14749405/Zed.log)

**Comment by leo-mangold** [comment]
After restarting only the search bar and file title vanish when in regex search mode on a large screen:
<img width="1292" alt="Screenshot 2024-03-25 at 21 54 30" src="https://github.com/zed-industries/zed/assets/42837960/dc2308f4-0eb6-4fe8-8eaa-1f26af8c1e49">

**Comment by leo-mangold** [comment]
The problem is fixed if I toggle "Match Whole Word" on. I think there were just too many matches displayed and that's why the text vanished

**Comment by JosephTLyons** [comment]
For the team, this happens to me too when searching for `e` in `editor.rs`, with default search settings:

<img width="1608" alt="SCR-20240328-ogtx" src="https://github.com/zed-industries/zed/assets/19867440/9709ccc0-1a60-485d-9001-5a6be38a1987">

**Comment by JosephTLyons** [comment]
Just a note - disabling the scrollbar causes the issue to go away.
