### ISSUE TITLE
Documentation: Configuration › Key bindings’ list of All key bindings is incorrect (out-of-date)

### ISSUE THREAD

**Issue by acusti** [zed-industries/zed#9796]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

a recent release of zed seems to have changed the default key bindings (#4703). i noticed it immediately when i saw that `ctrl` ⌘ ↑ and `ctrl` ⌘ ↓ no longer trigger the `editor::MoveLineUp` and `editor::MoveLineDown` commands (along with ⌘⇧ D no longer triggering `editor::DuplicateLine`). i immediately [when to the docs](https://zed.dev/docs/key-bindings) to see what the commands were supposed to be and saw that they were listed as i expected, so i figured that the functionality was just broken. after a few days and installing a few updates, i decided to check the default key bindings file myself and saw that they had just been changed, and that the docs reference is simply out-of-date.

a related thought: #4703 says the changes landed in [v0.126.0](https://zed.dev/releases/preview/0.126.0) but there is no mention of them in the release notes. changing the default key bindings is a big deal, at least for my usage, so i think it’s worth calling it out so that users understand that they can adapt to the changes to restore the previous editor behavior. i would actually be happy to take a stab at updating the docs, but i didn’t see a commit or PR referenced anywhere that encompasses the changes to use to verify which entries in the docs need to be updated.

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Thanks for letting us know @acusti - yeah, we don't have a good story for keeping these up to date. We used to have a script, but I think that system was lost in the migration of moving docs from a dedicated website to our website. As for now, there is no way for users to help with docs, since they are mixed with zed.dev code, which is private for now. An idea here is to make the docs portion a public submodule that zed.dev pulls in.

**Comment by JosephTLyons** [comment]
Also, I think I was mistaken in #4703, the changes landed in:

https://zed.dev/releases/stable/0.127.3

There's a section in there mentioning the breaking change.
