### ISSUE TITLE
Can't update extensions

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9799]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Extension is stuck in an infinite update loop

### Environment

Zed: v0.129.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/19867440/c699d302-f1e1-4ccf-a8a6-6494f5417f57

**Comment by maxdeviant** [comment]
@JosephTLyons Is it a particular extension you’re trying to upgrade?

**Comment by Moshyfawn** [comment]
> @JosephTLyons Is it a particular extension you’re trying to upgrade?

`Catppuccin Themes` based on the amount of installs.

**Comment by Moshyfawn** [comment]
Just ran into this bug as well.

**Comment by maxbrunsfeld** [comment]
I believe it's because they switched from `extension.json` to `extension.toml`, but our upgrade process does not delete the `extension.json`.

**Comment by JosephTLyons** [comment]
> @JosephTLyons Is it a particular extension you’re trying to upgrade?

I cropped to make it easier to see, and totally spaced that it would hide the extension name. 🤦‍♂️

Yep, like @Moshyfawn, it was `Catppuccin Themes`
