### ISSUE TITLE
[Linux] Incorrect Detection of Caps Lock/Shift Key Status

### ISSUE THREAD

**Issue by Yazeed1s** [zed-industries/zed#9808]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On linux, the input system is incorrectly detecting the status of the Caps Lock/Shift key. Specifically, it behaves as though the Caps Lock or Shift key is pressed when it is not. This problem persists until the actual Shift key is pressed, at which point the behavior reverts to normal. 

To reproduce the bug, under x11 click super+shift+desktop_number (this sends the window to a different workspace in my WM). After that zed shuld behave as if shift key is still being held down. 

### Environment

OS: Arch Linux x86_64
CPU: AMD Ryzen 7 PRO 6850U
GPU: AMD Radeon 680M

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

.config/zed/logs directory is empty

**Comment by Yazeed1s** [comment]
The [libxkbcommon](https://xkbcommon.org/doc/current/group__state.html) states that x11 clients should use `xkb_state_update_mask(...)` instead of `xkb_state_update_key(...)` and the current key press/release [handler](https://github.com/zed-industries/zed/blob/eaec04632a1b3ee973a80251353018059f624e96/crates/gpui/src/platform/linux/x11/client.rs#L203) uses `xkb_state_update_key()` instead.    

I think the issue happens because the state mask is not being updated, I have replaced `state.xkb.update_key(..)` with `state.xkb.update_mask(..)` and then removed the Shift consumption code in `Keystroke::from_xkb(..)`. This seems to have resolved the issue. However, I'm uncertain whether or not this is a clean fix for the problem."
 
```diff
            Event::KeyPress(event) => {
                let window = self.get_window(event.event)?;
                let modifiers = super::modifiers_from_state(event.state);
                let keystroke = {
                    let code = event.detail.into();
                    let mut state = self.state.borrow_mut();
+                    let mask = (event.state.bits() & !(1 << 2)) as u32;
+                    state.xkb.update_mask(0, 0, mask, 0, 0, 0);
                    let keystroke = crate::Keystroke::from_xkb(&state.xkb, modifiers, code);
-                    // state.xkb.update_key(code, xkbc::KeyDirection::Down);
                    keystroke
                };

                window.handle_input(PlatformInput::KeyDown(crate::KeyDownEvent {
                    keystroke,
                    is_held: false,
                }));
            }
```

**Comment by mikayla-maki** [comment]
I recommend opening a PR for this @Yazeed1s! That fix looks fine, maybe just add a little documentation about why the mask is computed that way :)

**Comment by mikayla-maki** [comment]
Closing this for now as the community just fixed a bunch of our keyboard issues, feel free to re-open if there are new problems
