### ISSUE TITLE
Status Page Shows 100% Uptime in 1774

### ISSUE THREAD

**Issue by adam1uphealth** [zed-industries/zed#9809]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I think the Zed status page may not reflect reality. The `Collaboration` field shows 100% uptime for all time going back at least to the 1700s. By navigating back via buttons a user can navigate far back beyond when Zed Industries existed. By updating the URL path, a user can navigate to 01/0001 at `https://status.zed.dev/history/8097`, showing 100% uptime the whole way.

<img width="990" alt="Screenshot 2024-03-26 at 10 02 00 AM" src="https://github.com/zed-industries/zed/assets/90338079/054042b4-7687-4152-9e97-ab2ce91d9a4a">

### Environment

N/A

**Comment by mikayla-maki** [comment]
Actually, this is an alpha feature we're working on right now. We're trying to project our collaborative software into the past, to ensure that current-day software can be built on a solid foundation. It's tough to gain a competitive advantage in this tight tech market, so we're just trying a few things ☺️

**Comment by maxdeviant** [comment]
There's nothing to do here, as there's no way in Instatus to set a start date for uptime.

**Comment by maxdeviant** [comment]
Set the service start date to our open source date: January 24, 2024.

Dates older than that now show with "Service hasn't started yet":

<img width="989" alt="Screenshot 2024-03-26 at 3 40 18 PM" src="https://github.com/zed-industries/zed/assets/1486634/6daabae0-8918-4a2f-ab88-e1e4bef09d93">
