### ISSUE TITLE
GPUI prompts are not using the UI font

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#9810]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Prompt:
![image](https://github.com/zed-industries/zed/assets/2588851/ee4e9189-2a2c-477e-9ba8-0333870bd3d4)

UI:
![image](https://github.com/zed-industries/zed/assets/2588851/85826eae-f1bd-4147-9ba7-4efad154e1c5)

I would expect them to use the same font.

### Environment

Ubunt 24.04
GNOME Wayland
Zed Dev 0.129.0 e77d3138

**Comment by maxdeviant** [comment]
IIRC these prompts are system prompts, so they match the style of the system, and not of GPUI itself.

**Comment by jansol** [comment]
This is specifically about the GPUI-provided fallback prompts implemented in #8980 which are used on Linux (and possibly Windows?)

**Comment by ConradIrwin** [comment]
Fixed by 0.141
