### ISSUE TITLE
Check if `solargraph` is already installed and in `$PATH` in project dir

### ISSUE THREAD

**Issue by odedharth** [zed-industries/zed#9811]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Autocomplete works for certain files like JS for example, but doesn't work at all for Ruby files.
See here: https://www.loom.com/share/5dc993f5cba24413b43b350c0d0a6d19

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.4.1
Memory: 64 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @odedharth, I think our implementation of Ruby currently expects you to install solargraph manually. I'm not sure what situation we ran into that caused us to make that decision, but here are the docs on it:

https://zed.dev/docs/ruby

Let me know if you get it up and running.

Just to mention it, @mrnugget has a PR open that switches us over to `ruby-lsp`:

- https://github.com/zed-industries/zed/pull/8613

**Comment by odedharth** [comment]
Hey @JosephTLyons,

Yes, the issue is that I already have solargraph installed. It used to work in the past and seems to have gotten broken in one of the last versions.

**Comment by mrnugget** [comment]
@odedharth can you paste the language server logs (`debug: open language server logs`) right after it starts up? The only recent change I can think of is this https://github.com/zed-industries/zed/pull/9170 which should provide _more_ completions.

On latest Zed stable version it works for me. In the case of `DateTime` I had to first `require 'date'`:

https://github.com/zed-industries/zed/assets/1185253/7ad08cd7-445d-4498-9fac-388645d62e64

**Comment by odedharth** [comment]
@mrnugget sure, that's what I'm seeing there after startup:

<img width="850" alt="Screenshot at Mar 27 10-46-52" src="https://github.com/zed-industries/zed/assets/624023/28ae6e07-73b4-4c0f-a316-867ff2f8d356">

And when I require 'date', it still doesn't do anything.

**Comment by mrnugget** [comment]
Can you select `solargraph` where it says `copilot` in your screenshot?

**Comment by odedharth** [comment]
@mrnugget, it's not showing as an option (even though the gem is installed)
<img width="666" alt="Screenshot at Mar 27 18-22-10" src="https://github.com/zed-industries/zed/assets/624023/fcb0909b-3420-4b91-9ce5-7a18c91dad52">

**Comment by mrnugget** [comment]
Huh! Interesting! That means it didn't even start yet.

Can you paste the logs from `~/Library/Logs/Zed/Zed.log` right after you open a Ruby file?

**Comment by odedharth** [comment]
@mrnugget sure, here is the log file:

[Zed.log](https://github.com/zed-industries/zed/files/14776927/Zed.log)

**Comment by mrnugget** [comment]
It looks like solargraph is installed with a different version than the one you're using in your projects:

```
2024-03-13T17:04:02+02:00 [ERROR] server stderr: Some("rbenv: version `3.1.3' is not installed (set by /Users/odedharth/Documents/Apps/Rails/MDAcne/.ruby-version)\n")
...
2024-03-13T17:04:08+02:00 [ERROR] server stderr: Some("rbenv: version `2.6.10' is not installed (set by /Users/odedharth/Documents/Apps/Rails/MDHair/.ruby-version)\n")
```

Can you even run solargraph manually? What happens if you do this:

```
env -i HOME="$HOME" $SHELL -i -l -c 'cd /Users/odedharth/Documents/Apps/Rails/MDHair && solargraph'
```

**Comment by odedharth** [comment]
@mrnugget it's strange that it was looking for rbenv, since I've switched to chruby. 
I've deleted rbenv, but it still doesn't work. It seems that it's looking for a gem in ruby 3.2.3 when the project is using ruby 2.6.10

Please see the new log file:
[Zed.log](https://github.com/zed-industries/zed/files/14786006/Zed.log)

**Comment by odedharth** [comment]
I've installed Solargraph manually with Ruby 3.2.3, and it fixed it. I'm wondering why was Zed looking for the 3.2.3 ruby version?

**Comment by mrnugget** [comment]
It depends on how you've setup your Ruby versions. What Zed does by default is to load the env of a user in the homedirectory. So if you have rbenv/chruby set to use version X.Y in your home dir, but to Z.X in your project dir, then Zed won't pick that up. We _can_ change it and look up solargraph dynamically.

**Comment by mrnugget** [comment]
thanks @rhatherall for the comment. Your description of the setup finally gave me confidence that this is the right solution. I went ahead and opened https://github.com/zed-industries/zed/pull/10835, which should fix this for you.
