### ISSUE TITLE
Zed mono em dash wrongly rendered in terminal

### ISSUE THREAD

**Issue by htor** [zed-industries/zed#9821]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Em dashes (`U+2014` unicode point) renders on top of the next character. This does not happen in regular buffers, but only in the terminal AFAIK:

<img width="1440" alt="Screenshot 2024-03-26 at 17 25 25" src="https://github.com/zed-industries/zed/assets/1709263/8881723c-e9f3-440f-99a3-8cb01b93aef0">

It seems to happen in any app using any Zed mono font:

<img width="884" alt="Screenshot 2024-03-26 at 17 41 38" src="https://github.com/zed-industries/zed/assets/1709263/f7cf756c-42ea-4da5-b33d-2b6be48f8e8d">

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 12.7.4
Memory: 16 GiB
Architecture: aarch64

**Comment by htor** [comment]
Also discovered these mathematical symbols are also a bit wide:

<img width="855" alt="Screenshot 2024-03-26 at 22 55 20" src="https://github.com/zed-industries/zed/assets/1709263/4b1e9764-4339-4659-a402-f5c404c73b8d">

`U+220f` `U+2210` and `U+2211`.

**Comment by notpeter** [comment]
This was fixed when we switched default fonts from `Zed Mono` to `Zed Plex Mono`.

btw, beautiful reproduction steps @htor:
```
printf "foo\u2013bar\n"
for hex in 220f 2210 2211; do printf "\u${hex}foo\n"; done
```
Bravo.

<img width="958" alt="image" src="https://github.com/user-attachments/assets/9e178d22-b2af-442c-9816-4ad6ca567bac">

**Comment by htor** [comment]
No problem. Thanks for the fix!
