### ISSUE TITLE
Add projects paths inside recent projects popup

### ISSUE THREAD

**Issue by nothugofsea** [zed-industries/zed#9822]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello, recently I faced with problem, I've two folders with same name and different locations and while another project is open I don't know which one I need to open. I suggest to add project path near project name inside recent projects menu. I think this feature would improve UX.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="604" alt="image" src="https://github.com/zed-industries/zed/assets/91194878/a1af1e94-df08-48cb-98ea-883b2776644d">

**Comment by JosephTLyons** [comment]
Hey @nothugofsea, just to be sure, you are wanting to have the path names to show up in this popover when clicking on the project name in the titlebar?

<img width="373" alt="SCR-20240326-muwz" src="https://github.com/zed-industries/zed/assets/19867440/92dd77c2-6674-477d-bb05-975108a091d1">

As in your screenshot, the paths are already in the recent projects modal.

**Comment by jansol** [comment]
Huh, that is a surprising inconsistency. `projects: Open Recent` from the command palette does show the paths, but the quick switcher in the title bar does not, despite looking otherwise identical.

**Comment by bennetbo** [comment]
The paths are displayed as a tooltip when you hover over the project names (both in the command palette and the picker).

However it looks like there is a regression, normally there are tooltips inside the project switcher in the upper left, but its only working for the command palette right now

![image](https://github.com/zed-industries/zed/assets/53836821/82a8524f-8536-4c5f-9b42-23d5f6553a99)

**Comment by nothugofsea** [comment]
> Huh, that is a surprising inconsistency. `projects: Open Recent` from the command palette does show the paths, but the quick switcher in the title bar does not, despite looking otherwise identical.

Thanks!

**Comment by nothugofsea** [comment]
> The paths are displayed as a tooltip when you hover over the project names (both in the command palette and the picker).
> 
> However it looks like there is a regression, normally there are tooltips inside the project switcher in the upper left, but its only working for the command palette right now
> 
> ![image](https://private-user-images.githubusercontent.com/53836821/317003391-82a8524f-8536-4c5f-9b42-23d5f6553a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODM5MzIsIm5iZiI6MTcxMTQ4MzYzMiwicGF0aCI6Ii81MzgzNjgyMS8zMTcwMDMzOTEtODJhODUyNGYtODUzNi00YzVmLTliNDItMjNkNWY2NTUzYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwMDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMDE5ZjQ3ZDdkOTkwYjc4MjkyM2ZlODU5YTFkYmIzOTVmYjhiNzAyMDM3MDhiOTQ1YTY5ZDE2NWQ5YWUyMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZIyFAsSd7etQewmoYKTG_LZka-g_KBeMa_T5FBZsywY)

I apologize for my carelessness...

**Comment by nothugofsea** [comment]
> Hey @nothugofsea, just to be sure, you are wanting to have the path names to show up in this popover when clicking on the project name in the titlebar?
> 
> <img alt="SCR-20240326-muwz" width="373" src="https://private-user-images.githubusercontent.com/19867440/316993446-92dd77c2-6674-477d-bb05-975108a091d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODM5MzIsIm5iZiI6MTcxMTQ4MzYzMiwicGF0aCI6Ii8xOTg2NzQ0MC8zMTY5OTM0NDYtOTJkZDc3YzItNjY3NC00NzdkLWJiMDUtOTc1MTA4YTA5MWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwMDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZDU1MTE3MTM5YzliMDdlNDE3OWMwNWUzYjNjMjcwMjUwYzBmNmY3ZDI0NDM0ZGFlYWViN2UyYWUyMGYzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V9GH2dIEzV5eeEWZ_OdkLXHx4e7a8tJFYJUkYSw43ok">
> As in your screenshot, the paths are already in the recent projects modal.

Please accept my apologies, I didn't know that Zed already has a modal with projects paths.

**Comment by bennetbo** [comment]
#9911 fixes the tooltips not appearing inside the popup anymore. 
![image](https://github.com/zed-industries/zed/assets/53836821/99912fe0-58de-4cc7-899f-709ac441a8f2)

I don't really think we need to display the paths in the popup, as you can either use the recent projects modal or hover over the project name to see the path it belongs to.
Also I like that the popup is more compact than the recent projects modal and therefore fits better into that popup style we also use for the recent branch picker.
