### ISSUE TITLE
Spell checking in Markdown & code comments via Vale

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#9823]
### Check for existing issues

- [X] Completed

### Describe the feature

https://vale.sh/
Rule-based offline prose linter that understands markdown and code, has an official LSP implementation.

Does Zed currently support running multiple language servers for the same file?

**Comment by JosephTLyons** [comment]
This seems really cool - should we include the info here?

- https://github.com/zed-industries/zed/issues/5305

I'd really like to get spell check into Zed, feels like be a massive QoL boost.

**Comment by jansol** [comment]
Mm yeah, on second thought it's probably better to just add it to that issue.
