### ISSUE TITLE
Can't open text file due to encoding

### ISSUE THREAD

**Issue by mileusna** [zed-industries/zed#9833]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While I managed to open some large XML files, there are some TXT files that I just can't open this using Zed. All I got is the blank page, can't edit or anything. There are also some other files which I was unable to open (500KB+)

I can't open this text file of 2.9MB:
[infotek.txt](https://github.com/zed-industries/zed/files/14764531/infotek.txt)

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is what I get in Zed compared to Sublime Text. VS Code, BB Edit, they all open file without problem.

<img width="1479" alt="Screenshot 2024-03-26 at 21 37 58" src="https://github.com/zed-industries/zed/assets/4697935/7de566bf-08bb-4404-a22b-71a8f5882ee4">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14764528/Zed.log)

**Comment by osiewicz** [comment]
That file doesn't look like a valid UTF-8; at present that's the only encoding that we support (plus UTF16 I think), see also: #5250  and #9771

**Comment by mileusna** [comment]
> Hey, thanks for the report. The issue here is not the size of a file, but its encoding - that file doesn't look like a valid UTF-8; at present that's the only encoding that we support (plus UTF16 I think), see also: #5250 and #9771

Yes, it is some old file from the archive which was used to import data in DB back then, but it is still regular TXT file, it should be opened as ASCII file I guess. It is stupid not to be able to open a txt file, even built-in macOS TextEdit can open the file without problems.

<img width="642" alt="Screenshot 2024-03-27 at 11 45 31" src="https://github.com/zed-industries/zed/assets/4697935/3cedbb34-91b8-4b4b-b66b-763711432c22">

**Comment by jansol** [comment]
Also related: #6938 #5348 #5294

**Comment by notpeter** [comment]
I'm closing the duplicate issues in favor of a unified issue for this feature here:
- https://github.com/zed-industries/zed/issues/16965

Please upvote 👍 to help prioritize this issue and click subscribe if you would like to receive notifications on its progress.  Thanks for reporting.
