### ISSUE TITLE
Extensions add go-wasm SDK and example

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#9838]
### Check for existing issues

- [X] Completed

### Describe the feature

I know @maxbrunsfeld posted [zed_extension_api](https://crates.io/crates/zed_extension_api)<0.0.4>
But this is a rust package. I really want to use Go to write (lsp) extensions. The obvious benefit is that it can reduce the difficulty of development.
> https://github.com/bytecodealliance/wit-bindgen#guest-tinygo

And. Then https://github.com/zed-industries/extensions can also contribute extensions written in Go :)

**Comment by maxdeviant** [comment]
We're currently just targeting Rust for extension development. It's the most mature option in the Wasm ecosystem and there are things (like `wit-bindgen`) that we currently rely on.

It's possible that we'll support authoring extensions in other compile-to-Wasm languages in the future, but I don't suspect it will be anytime soon.

**Comment by peter-jerry-ye** [comment]
@maxdeviant Just wondering, would it be possible if we provide a WebAssembly component as extension directly?
