### ISSUE TITLE
Failed upgrade of extension adds to Download count of an extension

### ISSUE THREAD

**Issue by Suhaybu** [zed-industries/zed#9840]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For some reason I was unable to upgrade the Catppuccin Theme, however despite the upgrade failing, I could see the counter of total downloads go up.

I'm not sure if adding upgrades to the total download count was intended as that would mean an extension with many updates is just going to have huge advantage just because the developer pushed a bunch of updates.

Video attached for demonstration.
🎩
😃 Have a good day

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/75957262/42bfc71f-38f2-4c73-8c54-ac8ea263d27e

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

These logs go on for the same number of times I attempted to install it.

```
2024-03-27T05:12:45+03:00 [INFO] installing extension catppuccin 0.2.3
2024-03-27T05:12:46+03:00 [INFO] rebuilt extension index in 194.392583ms
2024-03-27T05:12:46+03:00 [INFO] extensions updated. loading 0, reloading 1, unloading 0
2024-03-27T05:12:47+03:00 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "88cdf40e-cf96-48f0-9d6a-8dfae7ed968f",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-27T05:15:21+03:00 [INFO] installing extension catppuccin 0.2.3
2024-03-27T05:15:22+03:00 [INFO] rebuilt extension index in 194.456042ms
2024-03-27T05:15:22+03:00 [INFO] extensions updated. loading 0, reloading 1, unloading 0
2024-03-27T05:15:23+03:00 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "5d66cb1b-63b7-492f-8716-7a889ea5664d",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-27T05:15:23+03:00 [INFO] rebuilt extension index in 160.92ms
2024-03-27T05:15:23+03:00 [INFO] extensions updated. loading 0, reloading 1, unloading 0
2024-03-27T05:15:23+03:00 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "7e979683-687f-4f9a-860d-1b1a3aecec38",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}```

**Comment by Moshyfawn** [comment]
This was discovered in #9799. Strange, I was able to upgrade to the latest `Catppuccin Theme` in Preview today. Has the fix gone out to Stable? cc: @JosephTLyons

**Comment by Moshyfawn** [comment]
Could be the same cause #9802

**Comment by Suhaybu** [comment]
> This was discovered in #9799. Strange, I was able to upgrade to the latest `Catppuccin Theme` in Preview today. Has the fix gone out to Stable? cc: @JosephTLyons

I ended up having to reinstall it as you can see in the video. I thought the issue might just be with Catppuccin specifically since I had no other extensions to update so I chose not to report that.

That's why my issue is reporting the counter and not the extension not upgrading.

**Comment by JosephTLyons** [comment]
We just cherry picked the PR that fixes the original upgrade bug we had into stable, so that should be going out with both preview and stable today. Not sure if its the same bug or not, but if it is, it should be fixed.

**Comment by JosephTLyons** [comment]
Hey @Suhaybu, can you see if your issue is fixed in the newest stable?

[0.128.3](https://zed.dev/releases/stable/0.128.3)

**Comment by Suhaybu** [comment]
> Hey @Suhaybu, can you see if your issue is fixed in the newest stable?
> 
> [0.128.3](https://zed.dev/releases/stable/0.128.3)

Hi, unfortunately I can't verify if it does because I ended up uninstalling the extension and installing it. If any of the extensions I use have an update, I'll be sure to give you an update.

**Comment by JosephTLyons** [comment]
Ok, no worries. Let's close this one out, as it seems like the bug has been fixed for others in similar situations. We can open a new issue if it still exists.

**Comment by Suhaybu** [comment]
> Ok, no worries. Let's close this one out, as it seems like the bug has been fixed for others in similar situations. We can open a new issue if it still exists.
@JosephTLyons 

Just wanted to confirm that yes the new update did indeed fix the issue with not being able to update. However as you can see the counter for the total downloads is still going up despite this is an update and not a unique download.

Is that supposed to be a feature?

![CleanShot 2024-04-02 at 13 52 59](https://github.com/zed-industries/zed/assets/75957262/b8e48333-5cc0-4abc-87be-28cb396e37db)

**Comment by JosephTLyons** [comment]
@Suhaybu - yeah, right now our system for bumping the count needs a bit of work. It also allows bumps the count when uninstalling and installing, allowing anyone to boost their package's count, if they really wanted.  So yeah, we have a few things to fix in the area of extension download count.
