### ISSUE TITLE
Project files require a horizontal scrollbar

### ISSUE THREAD

**Issue by hjb0924** [zed-industries/zed#9841]
### Check for existing issues

- [ ] Completed

### Describe the feature

Project files require a horizontal scrollbar
<img width="231" alt="image" src="https://github.com/zed-industries/zed/assets/16297540/bc78714c-f3c8-47f5-8521-e8c05cac884f">

**Comment by Moshyfawn** [comment]
There's already a feature request for a horizontal scrollbar. I'm going to close this as a duplicate to keep the conversation in one place. Be sure to +👍 the other issue if you're interested.

Duplicate of
- #4427

**Comment by lucasmat7** [comment]
Is it really the same thing? One is requesting for the file explorer, the other for the text editing area
