### ISSUE TITLE
Automatically identify the language used by the file

### ISSUE THREAD

**Issue by ljh740** [zed-industries/zed#9842]
### Check for existing issues

- [X] Completed

### Describe the feature

I want to set all files named 'podfile' to be identified using ruby.
How should I configure?

**Comment by RemcoSmitsDev** [comment]
Here is an example how it's done: https://github.com/zed-industries/zed/pull/9290

**Comment by Moshyfawn** [comment]
Yup, file association already exists via #9290. I'm going to close this issue, but feel free to report back.

Duplicate of
- #5178
