### ISSUE TITLE
"inside tag" vim motion selects outer tag if cursor is on the first symbol inside current tag

### ISSUE THREAD

**Issue by everdimension** [zed-industries/zed#9844]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Example
```
<div>
  <span>Text</span>
</div>
```

If cursor is on letter "T" of "Text", vim motions such as `vit` select everything inside the `div` tag
Expected behavior: select everything inside `span` tag

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 13.5.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
Related #8994

**Comment by weartist** [comment]
Believe this issue has been fixed

**Comment by ConradIrwin** [comment]
Yup, thanks! This will merge to preview on April 3rd, and to stable a week later!
