### ISSUE TITLE
Markdown autoformatting breaks the document (is not stable)

### ISSUE THREAD

**Issue by gdamore** [zed-industries/zed#9869]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If I start with the following markdown:

```
nng_pub_open --- create *PUB* socket
```

Then I save, it gets changed to:

```
nng_pub_open --- create _PUB_ socket
```

This is fine.

But then if I save *again*, it then gets change to the following broken content:

```
nng*pub_open --- create \_PUB* socket
```

This is very much *not* what I desire.

I suppose this may not be a Zed issue directly, but via Prettier or something.  But it happens automatically in Zed, and I don't know how to stop it.

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

**Comment by VKondakoff** [comment]
This is prettier issue:

<img width="634" alt="Снимок экрана 2024-03-29 в 19 03 27" src="https://github.com/zed-industries/zed/assets/230824/5a13e512-ecf4-4593-a168-7e4c5a28451f">

**Comment by VKondakoff** [comment]
Here is the issue: https://github.com/prettier/prettier/issues/16160
