### ISSUE TITLE
Parenthesis match (% key) does not work in Markdown

### ISSUE THREAD

**Issue by gdamore** [zed-industries/zed#9870]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use the % match in vim (e.g. d% to delete to the matching paren) all the time.

This doesn't work in Markdown mode.  I suspect it doesn't work in any mode that doesn't have a declared set of matching brackets.

Perhaps it would be good to have a default set of matching brackets for syntax modes that don't supply them?  This would give the most "vi-equivalent" behavior.

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

**Comment by manosriram** [comment]
Is anyone working on this, or can i pick this up? @JosephTLyons

**Comment by ConradIrwin** [comment]
Feel free to pick it up! 

If you want to work on this together, I have some time listed here: https://calendly.com/conradirwin/pairing.

**Comment by ConradIrwin** [comment]
I've found the opposite in most cases :D. 30 minutes of working together can save hours of back and forth in PR reviews.

**Comment by manosriram** [comment]
Ohkay :) I'll pick a time.
