### ISSUE TITLE
Tabbar: bad tabs autoscrolling when there are to many open tabs

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9878]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently the autoscrolling of tabs works not very well: when there are too many open tabs the names of recently opened buffers are almost not visible (only small part of the active tab is visible):

https://github.com/zed-industries/zed/assets/230824/586817df-b99a-4bb1-af91-1a74de1a7787

### Environment

Zed: v0.129.0 (Zed Preview)
OS: macOS 12.7.4
Memory: 32 GiB
Architecture: x86_64

**Comment by mathieujobin** [comment]
Maybe its Okay to keep this one close because it is very similar to https://github.com/zed-industries/zed/issues/9880
but I wanted to repeat this here.

> the auto-close feature is set way too fast. issues are not being watched, and replied to for 6 months. github auto flag as staled. and 1 month later it closes it.
too fast for your bandwidth it seems.
