### ISSUE TITLE
`Default settings` and `Default key bindings` buffers are named `untitled` in Zed toolbar

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9881]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Buffers, which are generated by Zed (`Default settings`, `Default key bindings`) are named `untitled` in Zed toolbar:

<img width="449" alt="Снимок экрана 2024-03-27 в 20 11 12" src="https://github.com/zed-industries/zed/assets/230824/f307ff8a-4425-442a-9246-7bbc2e67697b">

<img width="449" alt="Снимок экрана 2024-03-27 в 20 11 17" src="https://github.com/zed-industries/zed/assets/230824/5bd24ec3-3a67-48b4-b015-78adeeb881c5">

### Environment

Zed: v0.129.0 (Zed Preview)
OS: macOS 12.7.4
Memory: 32 GiB
Architecture: x86_64

**Comment by SomeoneToIgnore** [comment]
![image](https://github.com/user-attachments/assets/654e382d-4719-409f-8acf-10f28ced77cc)

Looks fixed in `2470db490115322720f85e2ad57e922de930ee1b`

**Comment by notpeter** [comment]
That was me!
- https://github.com/zed-industries/zed/pull/16906
