### ISSUE TITLE
Image Viewer: Switching to an image tab should highlight the file in project panel

### ISSUE THREAD

**Issue by slymax** [zed-industries/zed#9897]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Switching to an image tab should highlight the file in the explorer to behave like editor tabs

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
Reveal in Project Panel and Open in Terminal are also missing from the right click context menu on the tab.
![image](https://github.com/user-attachments/assets/ef811ab1-41d2-44ba-921c-40f34638c62e)

**Comment by bennetbo** [comment]
This was fixed in #19717
