### ISSUE TITLE
Zed does not prompt before deleting files containing usaved changes

### ISSUE THREAD

**Issue by hmemcpy** [zed-industries/zed#9905]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If a buffer contains unsaved changes, deleting the file (or its containing folder) from the project panel does not prompt about the unsaved changes and deletes the file on confirmation.

![2024-03-28 11 34 30](https://github.com/zed-industries/zed/assets/601206/0c0491b1-026f-4b8a-a1fc-979c7c928c6c)
(the delete popup isn't visible in the gif above for some reason)

If a buffer contains unsaved changes, Zed should warn about deleting such files.
Equivalent VSCode prompt:
<img width="311" alt="image" src="https://github.com/zed-industries/zed/assets/601206/6c8e19ea-9866-4c6e-9b05-1b1aa830ab01">

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Thanks for the report @hmemcpy, I *think* this used to prompt - so this feels like a regression.

**Comment by hmemcpy** [comment]
Thanks, but I now think I need to rephrase this. It does prompt to delete the file, it wasn't visible in the gif. But if the file contains unsaved changes - it should warn that the file deleted contains unsaved changes.

I noticed this weird behavior when I deleted a folder containing a "dirty" file. The folder and the file were removed from the project panel, but the tab remained opened in the editor. Upon pressing Save, the folder and the file reappeared in the project panel.

I *think* this was fixed, so that a deleted file also closes the tab, but I still think it should warn before deleting files containing saved changes.

So perhaps this is more of a feature request rather than a bug.

**Comment by dbakong** [comment]
I also experienced this issue, while using zed `v0.146.5` on mac.
Zed doesn't seem to prompt for sending to trash(⌘⌫). Zed only seems to prompt when permanently deleting the file (⌘⌥⌫).
https://github.com/user-attachments/assets/6f970b21-7747-4323-94da-d0db5999e768
