### ISSUE TITLE
Hover tooltip isn't dismissed / refreshed on scroll

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9928]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

~~Unlike popovers in the editable regions of the editor, scrolling doesn't dismiss the popover on git blame lines in the gutter. I think the popover should be dismissed on scroll, and the new line that the cursor ultimately lands on should trigger Zed to show that line's blame info.~~

This doesn't seem to be a bug with git blame, but tooltips on elements that are in scrollable lists in general. Hovering over the `...` button on a message in the chat view produces a `More` tooltip, and when scrolling, the tooltip stucks, just like it does in the git blame view.

### Environment

Zed: v0.130.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/19867440/7abed8f2-6e7e-45dc-867a-ca0b27f2900a

**Comment by mrnugget** [comment]
Yeah, this is a general problem with hover tooltips. See this one in the multi-buffer, which behaves slightly better but I think it's the same underlying problem.

https://github.com/zed-industries/zed/assets/1185253/27c799ba-fec9-4667-93ed-1490a6bc52a2
