### ISSUE TITLE
gtk4 and libadwaita support for zed code editor

### ISSUE THREAD

**Issue by userforsource** [zed-industries/zed#9944]
### Check for existing issues

- [X] Completed

### Describe the feature

Gtk4 for adwaita support for zedapp
https://gtk-rs.org/
https://www.gtk.org/docs/language-bindings/rust

**Comment by maxdeviant** [comment]
@userforsource Could you clarify on what the ask is here?

**Comment by userforsource** [comment]
> @userforsource Could you clarify what the ask is here?

Yes i want this app to use gtk4 so it looks good in linux desktop

**Comment by walking-octopus** [comment]
Non-applicable. Zed uses its own UI library, not Gtk-4. Unless you suggest starting over from scratch just to use Gtk, that cannot be done. :)

Perhaps you have more specific concerns about why it does not "look good" at the moment? Scaling, theming, dialog integration?

**Comment by userforsource** [comment]
That is ok but can you ise libadwaita for the theme
Like we see in mac os all apps have 4corners rounded which is really good. visually.

**Comment by walking-octopus** [comment]
You can try to imitate it visually, but as far as I'm aware, you cannot just pull widgets out of it if you don't use GTK. Still, the community could probably remedy it with greater theming support, perhaps exposing border radius, someone can make a more Adwaita-like theme.

**Comment by someone13574** [comment]
I made a theme which imitates the color scheme of libadwaita, but since you cannot change the actual geometry through a theme yet, that's all you can do.

https://github.com/someone13574/zed-adwaita-theme

**Comment by mikayla-maki** [comment]
We are not planning on supporting GTK themes.
