### ISSUE TITLE
Zed.dev -> Docs -> Themes -> FAQ: answers are without questions

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9957]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed.dev -> Docs -> Themes -> FAQ: answers are without questions ( https://zed.dev/docs/themes#theme-faq ).

![IMG_0779](https://github.com/zed-industries/zed/assets/230824/8a00127d-e83e-4f0f-b6ee-72d4eb76808d)

### Environment

MacOS 12.7.4
Safari 17.4.1 (17618.1.15.111.8, 17618)

**Comment by bcmeireles** [comment]
I'd like to fix this if possible but where could I find the relevant questions?

**Comment by maxdeviant** [comment]
This section of the theme docs wasn't relevant anymore and has been removed. Changes should be live in a few minutes.
