### ISSUE TITLE
Git blame differs from VS Code within submodules

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9958]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the Zed screenshot, it shows a commit Marshall made and only on 1 of the 3 lines. In the VS Code screenshot, it shows the commits I made. I'm not sure, but I'm guessing VS Code is accurately reading the git information of the submodule, where Zed is gathering git info about the parent module.

### Environment

Zed: v0.130.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed blame

<img width="1608" alt="SCR-20240329-licd" src="https://github.com/zed-industries/zed/assets/19867440/53bec3a9-36d4-4de3-8fcb-300739728868">

VS Code blame

<img width="1608" alt="SCR-20240329-lioe" src="https://github.com/zed-industries/zed/assets/19867440/abbc7f67-d366-4006-bf02-9156db5c15e0">

**Comment by mrnugget** [comment]
I don't even see how you made it show up. When I open `extensions/elisp/README.md` and turn on `git blame` I get the following error message in the console:

```
fatal: this operation must be run in a work tree
```
