### ISSUE TITLE
I can't move the main window

### ISSUE THREAD

**Issue by fredix** [zed-industries/zed#9964]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to move Zed with the mouse pointer on the top bar, it's impossible to move. Anyway I can move it with a push on the window key and click the left mouse button.

### Environment

- Tried on Linux Ubuntu 22 LTS after a fresh git clone and a cargo build --release.
- Tried on Manjaro from de AUR depot : https://aur.archlinux.org/packages/zed-editor

I'm using on both distribution, Wayland.

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 30.6 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14807496/Zed.log)

**Comment by jansol** [comment]
Client-side decorations for Wayland have not been implemented yet and this would be part of those.
