### ISSUE TITLE
Buffer is marked as dirty, despite contents being same as on disk

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9970]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I think there were some changes applied to how we tell if a buffer is dirty recently, but I noticed something that feels like a regression:

1. Indent a line
2. Un-indent the line
3. See that the file's status is marked as dirty, despite being in its original form

It is possible there is some hidden character being produced that I'm missing - I have the whitespace characters turned on in the video below.

---

Note that in some cases, it works correctly:

1. Indent a line
2. `cmd-z` the change
3. See that the file's status i marked as clean

### Environment

Zed: v0.130.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

In this video, I indent and un-indent the line, then manually save after a while to make the status clean again:

https://github.com/zed-industries/zed/assets/19867440/91ae7c22-2d12-4f9c-8acf-5118c3b23668

**Comment by osiewicz** [comment]
As for OP this works exactly as intended; we no longer compare contents with what's on disk and instead we track just the dirty bit. The fact that undoing clears the dirty bit is by design too.

As for diff hunks, I think it depends on its implementation (if reverting is implemented as undoing then it should clear the dirty bit imho).

**Comment by JosephTLyons** [comment]
I see. At a weird junction between wanting to be more permanent and also correctly identifying what's different between memory and disk.

**Comment by JosephTLyons** [comment]
Here's a video where I'm doing the same thing in a `.py` file (indent, then un-indent) and the status is fluctuating between dirty and clean, unlike with the json file above.

https://github.com/zed-industries/zed/assets/19867440/ae9cc805-a89b-4149-a36d-b47babbc51c7

**Comment by osiewicz** [comment]
Hm, indent + unindent combo gets me into a clean state in both JSON and Python files.

https://github.com/zed-industries/zed/assets/24362066/bfe92ad7-47fb-4d3e-8f38-7a23ff1615bb

**Comment by osiewicz** [comment]
Okay, we've figured it out on Slack; basically, unindent-indent action combo "clears" the dirty bit (as it should), but if you indent via tab/tab-prev, the buffer stays dirty. That's basically the bug in a nutshell.
