### ISSUE TITLE
Rust-analyzer configuration per workspace

### ISSUE THREAD

**Issue by taunusflieger** [zed-industries/zed#9984]
### Check for existing issues

- [X] Completed

### Describe the feature

When working on embedded Rust projects, one typically needs a rust-analyser configuration specific to the target (i.e. target tripple). VSCode supports this through workspace specific settings. Can we please have workspace specific settings in ZED?

### If applicable, add mockups / screenshots to help present your vision of the feature

{
    "rust-analyzer.cargo.features": [
        "rt",
        "stm32h743v",
        "defmt"
    ],
    "rust-analyzer.check.allTargets": false,
    "rust-analyzer.check.targets": "thumbv7em-none-eabihf",

**Comment by jansol** [comment]
You can already have workspace-specific Zed config (which can include LSP config I think?) if you search the command palette for `zed: open local settings`.

**Comment by taunusflieger** [comment]
Didn't know that - thanks - yes works nicely

**Comment by pronebird** [comment]
Do you mind sharing example how to configure the target in Zed settings?
